### ISSUE TITLE
Shader stuff

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#10000]
### Describe your problem here.

How can I make the camera have chromaticAberration?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Mastercopper2346** [comment]
10000 LETS GO

**Comment by Mastercopper2346** [comment]
O yeah, not possible in lua.

**Comment by bruh1cat** [comment]
What about this? https://github.com/ShadowMario/FNF-PsychEngine/issues/9954#issuecomment-1200302769

**Comment by CrusherMods** [comment]
> O yeah, not possible in lua.

it is with the new action builds

**Comment by TheAverageGitHubUser** [comment]
Damn 10.000 issue

**Comment by TheAverageGitHubUser** [comment]
respect to shaders

**Comment by bruh1cat** [comment]
> What about this? [#9954 (comment)](https://github.com/ShadowMario/FNF-PsychEngine/issues/9954#issuecomment-1200302769)

I just don’t know how to use them

**Comment by Mastercopper2346** [comment]
> What about this? https://github.com/ShadowMario/FNF-PsychEngine/issues/9954#issuecomment-1200302769

THATS SOURCE!!!

**Comment by bruh1cat** [comment]
> > What about this? [#9954 (comment)](https://github.com/ShadowMario/FNF-PsychEngine/issues/9954#issuecomment-1200302769)
> 
> THATS SOURCE!!!

It isn't dude FunkinLua is for Lua functions

**Comment by raindow05** [comment]
> 10000 LETS GO

EEEEEEEEEEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by YKoF-CALm** [comment]
> > > What about this? [#9954 (comment)](https://github.com/ShadowMario/FNF-PsychEngine/issues/9954#issuecomment-1200302769)
> > 
> > 
> > THATS SOURCE!!!
> 
> It isn't dude FunkinLua is for Lua functions

Yes, FunkinLua simply gives a list of available Lua functions for use, and it seems like shaders have been re-enabled or something.

Based on previous versions, I guess that you need a .frag file for your shader and put that in a folder called "shaders", and just leave that folder in your mod directory (so don't drop it in another folder like 'images" or something).

Initialize with `initLuaShader(shadername, glslVersion)` and try to figure out stuff from there on with the other functions.

IDK, I'm just guessing, I don't have any shader files to experiment with.

**Comment by tylerandari12** [comment]
Is there some sorta shader template I could edit or a website (or application that isnt Adobe Animate) that I could use to edit them?

**Comment by YKoF-CALm** [comment]
> Is there some sorta shader template I could edit or a website (or application that isnt Adobe Animate) that I could use to edit them?

https://gamebanana.com/tuts/14452

Guess you could try this. IDK I'm not gonna tinker with shaders in the meantime.

**Comment by bruh1cat** [comment]
> Seriously, it's a dave and bambi (possibly not, not sure, but shaders is the most hated thing by here) question, at **10,000** posts.

It's not for Dave and Bambi thankfully also, just wanted to know how to use the new shader functions. For now I'll close this issue since no one knows how to use it.
