### ISSUE TITLE
Adding more song menus

### ISSUE THREAD

**Issue by AbyssalChaos** [ShadowMario/FNF-PsychEngine#10001]
### Describe your problem here.

I've been trying to make another for a few hours but for the life of me I can't figure out the proper way to, I just wanna add a seperate Freeplay menu that's for a different set of songs, similar to how indie cross does it I guess.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Added characters and stages via Lua

**Comment by CrusherMods** [comment]
just copy freeplay shit and modify it
i did it before
it works

**Comment by AbyssalChaos** [comment]
I was able to do that, but now I'm struggling to change the song list within, is there like, a line i'm missing in Freeplay State or something?
