### ISSUE TITLE
script problem

### ISSUE THREAD

**Issue by ripsyhehe** [ShadowMario/FNF-PsychEngine#10006]
### Describe your problem here.

made an event where u gotta spam space or else you die, but the script like breaks when it does it for the third time, like for the first time i dont spam space i take damage, second time i do spam it i take no damage, then when i dont spam again i gain health and dont die?

heres my code: 

`spacePresses = 0;

function onCreate()
    spacePresses = 0;
    precacheImage('spacebar');
    precacheSound('DODGE');
	precacheSound('Dodged');
end

function onUpdate(elapsed)
     if keyJustPressed('space') then
          spacePresses = spacePresses + 1;
     end
end

function onEvent(name, value1, value2)
    if name == "DodgeEvent" then
    cameraFlash('other', 'ff0000', 0.5, false)
    runTimer('Mashh', 4.5);
    runTimer('NOMashes', 4.5);
	makeAnimatedLuaSprite('spacebar', 'spacebar', 420, 200);
    luaSpriteAddAnimationByPrefix('spacebar', 'spacebar', 'spacebar', 25, true);
	luaSpritePlayAnimation('spacebar', 'spacebar');
	setObjectCamera('spacebar', 'other');
	scaleLuaSprite('spacebar', 0.70, 0.70); 
    addLuaSprite('spacebar', true); 
    makeLuaText('mashhhhh', 'MASH SPACE!!', 1300, 10, 450)
    setTextColor('mashhhhh', '990000')
    setTextSize('mashhhhh', 56)
    setObjectCamera('mashhhhh', 'camOther')
    addLuaText('mashhhhh')
    cameraShake('hud', 0.01, 4.5)
    cameraShake('game', 0.01, 4.5)
    cameraShake('other',0.01, 4.5)
    playSound('DODGE');
	end
end

function onTimerCompleted(tag, loops, loopsLeft)
           if tag == 'NOMashes' and spacePresses < 10 then
                        removeLuaSprite('spacebar'); 
                        removeLuaText('mashhhhh');
                        setProperty('health', 100);
           elseif tag == 'Mashh' and spacePresses  > 10 then
                        removeLuaSprite('spacebar'); 
                        removeLuaText('mashhhhh');
                        setProperty('health', 100);
            end
end
`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
you didn't reset the variable when the event is called
and why are you running two timers that do the same thing

**Comment by ripsyhehe** [comment]
Dawg please just help me out and fix it up for me. it seems like you know what to fix lmao, im new to coding

**Comment by frantastic24** [comment]
don't ask people to do it for you

**Comment by ripsyhehe** [comment]
ok fine but wdym when you said i didnt reset the variable

**Comment by frantastic24** [comment]
Set it to 0

**Comment by ripsyhehe** [comment]
the timer??

**Comment by frantastic24** [comment]
no, the variable

**Comment by ripsyhehe** [comment]
which variable? idk which ur talking abt

**Comment by frantastic24** [comment]
There is only one variable in the script

**Comment by ripsyhehe** [comment]
what is it bro

**Comment by bruh1cat** [comment]
> what is it bro

I think the variable is `spacePresses'

**Comment by ripsyhehe** [comment]
it is 0?

**Comment by bruh1cat** [comment]
Idk if this made it into 1 but 'spacePresses = spacePresses + 1;'

**Comment by dezercheap10** [comment]
i think he means the 1st setProperty() in the onTimerCompleted() function

**Comment by ripsyhehe** [comment]
what do i do

**Comment by dezercheap10** [comment]
change the last function to this and see if it works:

function onTimerCompleted(tag, loops, loopsLeft)
if tag == 'NOMashes' and spacePresses < 10 then
removeLuaSprite('spacebar');
removeLuaText('mashhhhh');
setProperty('health', 0);
elseif tag == 'Mashh' and spacePresses > 10 then
removeLuaSprite('spacebar');
removeLuaText('mashhhhh');
setProperty('health', 1);
end
end

**Comment by ripsyhehe** [comment]
i gain health when i dont press space, why?

**Comment by ripsyhehe** [comment]
the first two times it works but on the third try it does that

**Comment by dezercheap10** [comment]
try removing one of the timers then this:

function onTimerCompleted(tag, loops, loopsLeft)
if tag == 'Mashh' and spacePresses < 10 then
removeLuaSprite('spacebar');
removeLuaText('mashhhhh');
setProperty('health', 0);
elseif tag == 'Mashh' and spacePresses > 10 then
removeLuaSprite('spacebar');
removeLuaText('mashhhhh');
setProperty('health', 1);
end
end

**Comment by ripsyhehe** [comment]
still does it

**Comment by dezercheap10** [comment]
may I see the current script?

**Comment by ripsyhehe** [comment]
spacePresses = 0;

function onCreate()
    precacheImage('spacebar');
    precacheSound('DODGE');
	precacheSound('Dodged');
end


function onUpdate(elapsed)
     if keyJustPressed('space') then
          spacePresses = spacePresses + 1;
     end
end

function onEvent(name, value1, value2)
    if name == "DodgeEvent" then
    cameraFlash('other', 'ff0000', 0.5, false)
    runTimer('Mashh', 5);
	makeAnimatedLuaSprite('spacebar', 'spacebar', 420, 200);
    luaSpriteAddAnimationByPrefix('spacebar', 'spacebar', 'spacebar', 25, true);
	luaSpritePlayAnimation('spacebar', 'spacebar');
	setObjectCamera('spacebar', 'other');
	scaleLuaSprite('spacebar', 0.70, 0.70); 
    addLuaSprite('spacebar', true); 
    makeLuaText('mashhhhh', 'MASH SPACE!!', 1300, 10, 450)
    setTextColor('mashhhhh', '990000')
    setTextSize('mashhhhh', 56)
    setObjectCamera('mashhhhh', 'camOther')
    addLuaText('mashhhhh')
    cameraShake('hud', 0.01, 4.5)
    cameraShake('game', 0.01, 4.5)
    cameraShake('other',0.01, 4.5)
    playSound('DODGE');
    if keyJustPressed('space') then
          spacePresses = spacePresses + 1;
     end
	end
end

function onTimerCompleted(tag, loops, loopsLeft)
           if tag == 'Mashh' and spacePresses < 10 then
                        removeLuaSprite('spacebar'); 
                        removeLuaText('mashhhhh');
                        setProperty('health', 0);
           elseif tag == 'Mashh' and spacePresses  > 10 then
                        removeLuaSprite('spacebar'); 
                        removeLuaText('mashhhhh');
            end
end

**Comment by dezercheap10** [comment]
honestly idk whats wrong

**Comment by frantastic24** [comment]
> you didn't reset the variable when the event is called

**Comment by ripsyhehe** [comment]
HOW do i reset it? do i move the variable under on event?

**Comment by frantastic24** [comment]
> Set it to 0

**Comment by ripsyhehe** [comment]
then theres no point to the event?
it wont do anything?

**Comment by frantastic24** [comment]
No, as the event is now it has no point because you can mash space at the start of the song and completely ignore the event
That is why you reset the variable to 0

**Comment by ripsyhehe** [comment]
its already 0....?

**Comment by frantastic24** [comment]
> spacePresses = spacePresses + 1;

Are you just ignoring this line

**Comment by ripsyhehe** [comment]
yeah because if i change it to 0 the event wont do anything

**Comment by ripsyhehe** [comment]
i just fixed it

**Comment by ripsyhehe** [comment]
nvm it still doesnt work

**Comment by frantastic24** [comment]
> yeah because if i change it to 0 the event wont do anything

I didn't tell you to change it 💀 that line is the reason you need to reset the value

**Comment by ripsyhehe** [comment]
dawg, then how do i reset it, ive been on this shi for days what do i change bruv

**Comment by frantastic24** [comment]
I've already told you twice

**Comment by ripsyhehe** [comment]
spacePresses = spacePresses + 0; ????

**Comment by frantastic24** [comment]
That's adding 0, it does nothing

**Comment by ripsyhehe** [comment]
its not spacePresses = spacePresses + 1; or  spacePresses = 0; so what is it

**Comment by Mastercopper2346** [comment]
HeY tHaT’s My cOdE

**Comment by ripsyhehe** [comment]
yea thanks

**Comment by Mastercopper2346** [comment]
```
spacePresses = 0;
pressesCount = false;

function onCreate()
     precacheImage('spacebar');
     precacheSound('DODGE');
     precacheSound('Dodged');
end

function onUpdate(elapsed)
     if keyJustPressed('space') and pressesConut then
          spacePresses = spacePresses + 1;
     end
end

function onEvent(name, value1, value2)
     if name == "DodgeEvent" then
          cameraFlash('other', 'ff0000', 0.5, false)
          runTimer('Mashh', 5);
          makeAnimatedLuaSprite('spacebar', 'spacebar', 420, 200);
          addAnimationByPrefix('spacebar', 'spacebar', 'spacebar', 25, true); 
          playAnimation('spacebar', 'spacebar');
          setObjectCamera('spacebar', 'other');
          scaleObject('spacebar', 0.70, 0.70);
          addLuaSprite('spacebar', true);
          makeLuaText('mashhhhh', 'MASH SPACE!!', 1300, 10, 450)
          setTextColor('mashhhhh', '990000')
          setTextSize('mashhhhh', 56)
          setObjectCamera('mashhhhh', 'camOther')
          addLuaText('mashhhhh')
          cameraShake('hud', 0.01, 4.5)
          cameraShake('game', 0.01, 4.5)
          cameraShake('other',0.01, 4.5)
          playSound('DODGE');
          pressesCount = true;
     end
end

function onTimerCompleted(tag, loops, loopsLeft)
     if tag == 'Mashh' and spacePresses < 10 then
          removeLuaSprite('spacebar');
          removeLuaText('mashhhhh');
          setProperty('health', 0);
     elseif tag == 'Mashh' and spacePresses > 10 then
          removeLuaSprite('spacebar');
          removeLuaText('mashhhhh');
     end
end
 ```
Try this.

**Comment by ripsyhehe** [comment]
doesnt work
also i updated the code:

 spacePresses = 0;
 pressesCount = false;


 function onUpdate(elapsed)
         if keyJustPressed('space') and pressesConut then
                   spacePresses = spacePresses + 1;
         end
end

function onEvent(name, value1, value2)
    if name == "DodgeEvent" then
    removeLuaText('ten')
    removeLuaText('nine')
    removeLuaText('eight')
    removeLuaText('seven')
    removeLuaText('six')
    removeLuaText('five')
    removeLuaText('four')
    removeLuaText('three')
    removeLuaText('two')
    removeLuaText('one') 
    removeLuaText('zero')
    cameraFlash('other', 'ff0000', 0.5, false)
    runTimer('Mashh', 4.5);
    runTimer('byebye', 4.5);
    runTimer('10', 0.01);
    runTimer('9', 0.01);
    runTimer('8', 0.01);
    runTimer('7', 0.01);
    runTimer('6', 0.01);
    runTimer('5', 0.01);
    runTimer('4', 0.01);
    runTimer('3', 0.01);
    runTimer('2', 0.01);
    runTimer('1', 0.01);
	makeAnimatedLuaSprite('spacebar', 'spacebar', 420, 200);
    luaSpriteAddAnimationByPrefix('spacebar', 'spacebar', 'spacebar', 25, true);
	luaSpritePlayAnimation('spacebar', 'spacebar');
	setObjectCamera('spacebar', 'other');
	scaleLuaSprite('spacebar', 0.70, 0.70); 
    addLuaSprite('spacebar', true); 
    makeLuaText('mashhhhh', 'MASH SPACE!!!', 1300, 10, 450)
    setTextColor('mashhhhh', '990000')
    setTextSize('mashhhhh', 56)
    setObjectCamera('mashhhhh', 'camOther')
    addLuaText('mashhhhh')
    cameraShake('hud', 0.01, 4.5)
    cameraShake('game', 0.01, 4.5)
    cameraShake('other',0.01, 4.5)
    playSound('DODGE');
    pressesCount = true;
end

function onTimerCompleted(tag, loops, loopsLeft)
           if tag == 'Mashh' and spacePresses < 10 then
                        setProperty('health', 0);
           elseif tag == 'Mashh' and spacePresses  >=10 then
               doNothing()
           elseif tag == '10' and spacePresses  >= 0 then --ten
                        makeLuaText('ten', ' 10', 1300, 10, 450)
                        addLuaText('ten')
           elseif tag == '10' and spacePresses  >= 1 then  --ten
                        removeLuaText('ten')
           elseif tag == '9' and spacePresses  >= 1 then
                        makeLuaText('nine', ' 9', 1300, 10, 450)
                        addLuaText('nine')
           elseif tag == '9' and spacePresses  >= 2 then 
                        removeLuaText('nine')
           elseif tag == '8' and spacePresses  >= 2 then
                        makeLuaText('eight', ' 8', 1300, 10, 450)
                        addLuaText('eight')
           elseif tag == '8' and spacePresses  >= 3 then 
                        removeLuaText('eight')
           elseif tag == '7' and spacePresses  >= 3 then
                        makeLuaText('seven', ' 7', 1300, 10, 450)
                        addLuaText('seven')
           elseif tag == '7' and spacePresses  >= 4 then 
                        removeLuaText('seven')
           elseif tag == '6' and spacePresses  >= 4 then
                        makeLuaText('six', ' 6', 1300, 10, 450)
                        addLuaText('six')
           elseif tag == '6' and spacePresses  >= 5 then 
                        removeLuaText('six')
           elseif tag == '5' and spacePresses  >= 5 then
                        makeLuaText('five', ' 5', 1300, 10, 450)
                        addLuaText('five')
           elseif tag == '5' and spacePresses  >= 6 then 
                        removeLuaText('five')
           elseif tag == '4' and spacePresses  >= 6 then
                        makeLuaText('four', ' 4', 1300, 10, 450)
                        addLuaText('four')
           elseif tag == '4' and spacePresses  >= 7 then 
                        removeLuaText('four')
           elseif tag == '3' and spacePresses  >= 7 then
                        makeLuaText('three', ' 3', 1300, 10, 450)
                        addLuaText('three')
           elseif tag == '3' and spacePresses  >= 8 then 
                        removeLuaText('three')
           elseif tag == '2' and spacePresses  >= 8 then
                        makeLuaText('two', ' 2', 1300, 10, 450)
                        addLuaText('two')
           elseif tag == '2' and spacePresses  >= 9 then 
                        removeLuaText('two')
           elseif tag == '1' and spacePresses  >= 9 then
                        makeLuaText('one', ' 1', 1300, 10, 450)
                        addLuaText('one')
           elseif tag == '1' and spacePresses  >= 10 then 
                        removeLuaText('one')
           elseif tag == 'byebye' then
                       cameraFlash('other', '000000', 0.5, false)
                       removeLuaSprite('spacebar');
                       removeLuaText('mashhhhh')
            end
end
end

and i know its completely messy idk how else to fix it

**Comment by ripsyhehe** [comment]
plz help me
