### ISSUE TITLE
I wanna know how to play a video (.mp4) cutscene before the title screen.

### ISSUE THREAD

**Issue by AxzonZero** [ShadowMario/FNF-PsychEngine#10010]
### What is your question?

So I'm not sure how exactly to do this (hence me posting this question -_-), so here we go:

I wanna know how to play a video (.mp4) cutscene before the title screen.

Basically, as soon as you start the game up, the video plays. Then, when it finishes, it takes you straight to the main menu screen.

The most convenient answer for me would just be if someone told me the codeline I need and the line I need to add it to in TitleState.hx.

(This is just an extra, but if I find out how to make the main menu screen fade in, that would be _great._ But my main priority is above..)

Thanks to anyone who tries to help!

**Comment by frantastic24** [comment]
#8659

**Comment by AxzonZero** [comment]
> #8659

Alright I'll see if this works. Thanks!

**Comment by AxzonZero** [comment]
> #8659

Wait so what line in TitleState.hx do I put "new FlxVideo(assets/videos/videonName.mp4')?"

**Comment by AxzonZero** [comment]
> #8659

This didn't work.
What's the codeline I'm supposed to add in TitleState.hx and on what line is it?
