### ISSUE TITLE
New Sprites

### ISSUE THREAD

**Issue by KingRGames** [ShadowMario/FNF-PsychEngine#10017]
### Describe your problem here.

When tying to put in a new sprite over a character using the 8 key, The game says error. What is happening, is this a bug, what do I do?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Can't help if you don't show the error or the files
