### ISSUE TITLE
PsychEngine crashes when i load a stage

### ISSUE THREAD

**Issue by yStep101** [ShadowMario/FNF-PsychEngine#10013]
### Describe your bug here.

whenever i load a stage, psych engine always crashes, idk y pls help

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2571)
PlayState.hx (line 2426)
PlayState.hx (line 1060)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
Crash dump saved in crash/PsychEngine_2022-08-02_13'10'35.txt
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

none

**Comment by Carmonplay** [comment]
use this script for the lua on your stage and keep the stageback the same. and also you can resize the stage with the scaleObject.

function onCreate()
	-- background shit
	makeLuaSprite('stageback', 'your stage name', -300, -600);
	setScrollFactor('stageback', 0.9, 0.9);
	scaleObject('stageback', 1, 1);
	

	addLuaSprite('stageback', false);
	
	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end
