### ISSUE TITLE
I need a little help

### ISSUE THREAD

**Issue by NavaGaming** [ShadowMario/FNF-PsychEngine#10014]
### Describe your problem here.

function onBeatHit()
    --for every beat
    health = getProperty('health')
    if getProperty('health') > 0.2 then
        setProperty('health', health- 0.03);
    end
end

Is there any way to make that script a toggleable event?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by tylerandari12** [comment]
Usually people dont take kindly to asking for code (Its usually not allowed.) but I'm nice so I'll give it to you...

You'll need a blank Lua file named "Health Drain" in the events folder...

You'll need an optional text file named "Health Drain" also in the events folder:
```
Drains health lol.
Value 1: true / false (leave blank to toggle iether one)
Value 2: Unused
```

And you'll need this in the scripts folder:
```lua
local can = false

function onBeatHit()
	--for every beat
	if getProperty('health') > 0.2 and can == true then
		setProperty('health', getProperty('health') - 0.03)
	end
end

function onEvent(Name, Value1, Value2)
	if Name == "Health Drain" then
		if string.lower(Value1) == "true" then
			can = true
		elseif string.lower(Value1) == "false" then
			can = false
		else
			can = not can
		end
	end
end
```
