### ISSUE TITLE
Is there a way to code an anticheat function into Psych Engine?

### ISSUE THREAD

**Issue by TheWorksOfBH** [ShadowMario/FNF-PsychEngine#10019]
### Describe your problem here.

I want to make a song with a very unforgiving modchart, by adding a health drain, noscroll (as in no notes show up) and nine keys* all at the same time, but I feel like people will bypass this by enabling botplay or opening the chart editor.

In order to make the modchart more unforgiving, I'd like to run a script if you press the 7 key or enable botplay, then it redirects you to Rick Astley's Never Gonna Give You Up. Is there a way to check if botplay is enabled, and is there also a way to open external links in Psych Engine merely by using Lua?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

*no, I didn't steal the Shaggy Source code. I found a Lua script which helps with multikeys.

**Comment by NesDoesGithub** [comment]
```
function onCreatePost()
    setProperty('debugKeysChart', null);
end

function onUpdate()
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
        (your code here)

    if botPlay then
        (your code here)
    end
end
```

**Comment by tylerandari12** [comment]
> 

Im afraid you forgot an `end` in your code...

```lua
function onCreatePost()
    setProperty('debugKeysChart', null);
end

function onUpdate()
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
        --(your code here)
   end-- forgot this lol
    if botPlay then
        --(your code here)
    end
end
```

**Comment by tylerandari12** [comment]
I haven't found a way to open links yet...

**Comment by CrusherMods** [comment]
> I haven't found a way to open links yet...

I think you can do so with HScript but idk if it works

**Comment by TheWorksOfBH** [comment]
> I haven't found a way to open links yet...

`os.execute("start [Insert link here]")`

**Comment by tylerandari12** [comment]
> > I haven't found a way to open links yet...
> 
> `os.execute("start [Insert link here]")`

They brought back the `os` library?

**Comment by TheWorksOfBH** [comment]
> > > I haven't found a way to open links yet...
> > 
> > 
> > `os.execute("start [Insert link here]")`
> 
> They brought back the `os` library?

I think that's just a general Lua function....

**Comment by tylerandari12** [comment]
> > > > I haven't found a way to open links yet...
> > > 
> > > 
> > > `os.execute("start [Insert link here]")`
> > 
> > 
> > They brought back the `os` library?
> 
> I think that's just a general Lua function....

It is but I thought they removed it for security reasons...

**Comment by Parsellol** [comment]
```
function onCreatePost()
    addHaxeLibrary("CoolUtil")
    setProperty("debugKeysChart", null);
    if botPlay then
        endSong()
        runHaxeCode[[
            CoolUtil.browserLoad('https://www.youtube.com/watch?v=dQw4w9WgXcQ');
        ]]
    end
end

function onUpdate()
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
        endSong()
        runHaxeCode[[
            CoolUtil.browserLoad('https://www.youtube.com/watch?v=dQw4w9WgXcQ');
        ]]
    end
end 
```
