### ISSUE TITLE
Gameover thing or other stuff

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#10018]
### What is your question?

How would I keep track of things in lua like how many times the player has died or how much the player has played, and is there a way to keep track of those thing even after the game has been closed

**Comment by tylerandari12** [comment]
Using `getTextFromFile()` and `saveFile()` you can make a system that saves it to the files and doesn't go away once the game is closed... (and `deleteFile()` for erasing saves)

**Comment by tylerandari12** [comment]
To get the amount died for each session use `getPropertyFromClass("PlayState", "deathCounter")`...

**Comment by TFLTV** [comment]
> Using `getTextFromFile()` and `saveFile()` you can make a system that saves it to the files and doesn't go away once the game is closed... (and `deleteFile()` for erasing saves)

bruh thats sick but I can't test it right now

**Comment by tylerandari12** [comment]
> > Using `getTextFromFile()` and `saveFile()` you can make a system that saves it to the files and doesn't go away once the game is closed... (and `deleteFile()` for erasing saves)
> 
> bruh thats sick but I can't test it right now

Nrrrrr :(

**Comment by TFLTV** [comment]
> > > Using `getTextFromFile()` and `saveFile()` you can make a system that saves it to the files and doesn't go away once the game is closed... (and `deleteFile()` for erasing saves)
> > 
> > 
> > bruh thats sick but I can't test it right now
> 
> Nrrrrr :(

Now I can.  How do I save text inside the file, and how to save it to a path
and how would getTextFromFile Work?

**Comment by TFLTV** [comment]
> getTextFromFile()

how do I open the file (with lua if you know what I mean)
