### ISSUE TITLE
I wanna know how to play a video (.mp4) cutscene before the title screen. 

### ISSUE THREAD

**Issue by AxzonZero** [ShadowMario/FNF-PsychEngine#10024]
### Describe your problem here.

So I'm not sure how exactly to do this (hence me posting this question -_-), so here we go:

I wanna know how to play a video (.mp4) cutscene before the title screen.

Basically, as soon as you start the game up, the video plays. Then, when it finishes, it takes you straight to the main menu screen.

The most convenient answer for me would just be if someone told me the codelines I need and what file to put it in.

(This is just an extra, but if I find out how to make the main menu screen fade in, that would be great. But my main priority is above..)

Thanks to anyone who tries to help!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope. I changed absolutely nothing.

**Comment by Chidubemmo** [comment]
#9051
