### ISSUE TITLE
Add a Lua and Source tags to Bug Reports and Help Wanted posts...

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#10025]
### What feature do you want to get added on the **base** engine?

I don't know if this can be automated but if you can please do so...

Basically on anything that says "Are you modding on source or Lua" should get a tag that says which one that their modding with. This way people who do specifically source don't have to shuffle through Lua and people with Lua don't have to shuffle through source...

If it can't be done that's fine lol...

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CheesecakeForever** [comment]
I agree, but they won't read any of that, i asked to rename the "UPDATE HAXE TO 4.2.4" to "UPDATE HAXE TO 4.2.5" but ig just a simple rename can't be done.

**Comment by tylerandari12** [comment]
> I agree, but they won't read any of that, i asked to rename the "UPDATE HAXE TO 4.2.4" to "UPDATE HAXE TO 4.2.5" (haxe is something for source and 4.2.4 is buggy) but ig just a simple rename can't be done.

I remember seeeing that post lol...
