### ISSUE TITLE
Yet another source problem... (Yay)

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#10021]
### Describe your problem here.

I was fiddling around with Haxe when I discovered I was able to compile straight to HTML5. Quickly I tried to compile the source code for Psych Engine when I was met with this error...

(This is the closest I've been to successfully compiling to source btw.)

```
C:\Users\IT Desktop\FNF-PsychEngine-main >lime test html5
source/FunkinLua.hx:3054: characters 23-28 : Type not found : State
source/CoolUtil.hx:18: lines 18-141 : ... Defined in this class
source/PlayState.hx:3752: characters 40-68 : Class<FunkinLua> has no field getPropertyLoopThingWhatever
source/PlayState.hx:4895: characters 8-12 : Funkin Lua has no field call
source/PlayState.hx: 4896: characters 8-12 : FunkinLua has no field stop
```
![bug](https://user-images.githubusercontent.com/97060639/182482398-85513ae4-2a38-4ef4-800b-f2dc7afe34e9.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5/Browser

### Did you edit anything in this build? If so, mention or summarize your changes.

Just downloaded the source form [here](https://github.com/ShadowMario/FNF-PsychEngine). Nothing changed.

**Comment by BeastlyGhost** [comment]
html5 is not fully supported for psych, just compile for windows

**Comment by tylerandari12** [comment]
> html5 is not fully supported for psych, just compile for windows

The reason I made this issue is because I get this error on every build...

I put it as HTML5 because that one is the shortest but I did try some others...

**Comment by TheKitBoi** [comment]
> html5 is not fully supported for psych, just compile for windows

the dev team weren't focusing on Lua Errors when compiling HTML5

**Comment by BeastlyGhost** [comment]
just came back to this

I recommend using [this](https://cdn.discordapp.com/attachments/931776548250468382/1004049224616378439/setup.bat) for setting up haxe libraries and stuff like that, should solve most problems with source compiling you might have
