### ISSUE TITLE
i cant compile it

### ISSUE THREAD

**Issue by hgamingyt** [ShadowMario/FNF-PsychEngine#1002]
### Describe your problem here.

LINK : fatal error LNK1181: cannot open input file 'user32.lib'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

**Comment by perngjiafu** [comment]
[here](https://social.msdn.microsoft.com/Forums/en-US/2fb64598-1caf-4e45-ba46-aa7a5c233343/fatal-error-lnk1104cannot-open-file-user32lib?forum=Vsexpressvc)
