### ISSUE TITLE
Outdated Version Popup

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#10029]
### Describe your bug here.

When using an outdated version, and activating a mod, which restarts the game, will softlock you, needing you to manually restart the game

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not via source

**Comment by ZeitHeld** [comment]
It might also still be on 0.6.2, but I cannot test it-
Because there is no new update-

**Comment by ZeitHeld** [comment]
One could try it with 0.6.1, but I do not have it currently downloaded

**Comment by ShadowMario** [comment]
Just update your game lmfao
