### ISSUE TITLE
Add an indication of full clearing a song in the freeplay menu

### ISSUE THREAD

**Issue by SkyanUltra** [ShadowMario/FNF-PsychEngine#1003]
### What feature do you want to get added on the base engine?

It could be as basic as just a couple letters next to your score in the freeplay menu, or little medals if that fits your fancy

all that's needed is FC, GFC for FCs with only goods or better, and SFC for FCs with only sicks

it's basically just useful for people with tiny balls who need to redeem themselves with good accuracy in a video game (me)

**Comment by FuseIsHere813** [comment]
MFC is the full combo with sicks, so the SFC can be changed to that.

**Comment by ShadowMario** [comment]
Having a score/accuracy = You completed a song
100% Accuracy = Congratulations you FC'ed.
Wasn't that obvious enough?

**Comment by SkyanUltra** [comment]
yeah but what about misses
