### ISSUE TITLE
Can't play the song

### ISSUE THREAD

**Issue by MaksimmK** [ShadowMario/FNF-PsychEngine#10037]
### Describe your problem here.

When I tried to play my custom song, the game just crashed

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Added a custom song, character and week

**Comment by frantastic24** [comment]
you're supposed to post the error

**Comment by MaksimmK** [comment]
> you're supposed to post the error

ok

**Comment by frantastic24** [comment]
If you're not going to do it then close this

**Comment by tylerandari12** [comment]
Was there even an error or did it just say `PsycheEngine.exe is not responding`?

**Comment by LilMewo** [comment]
make sure you have Inst.ogg and Voices.ogg in mods/songs/%YOUR_SONG_NAME% and json files in mods/data/%YOUR_SONG_NAME%
