### ISSUE TITLE
How to add animated icons

### ISSUE THREAD

**Issue by Chidubemmo** [ShadowMario/FNF-PsychEngine#10035]
### Describe your problem here.

I just want to add animated icons just like sans's in indie cross without lua

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added menu characters in the main menu

**Comment by frantastic24** [comment]
Duplicate #8522

**Comment by Mastercopper2346** [comment]
E

**Comment by Chidubemmo** [comment]
Found out
```
iconP1.frames = Paths.getSparrowAtlas('icons/[ICONNAME]')
iconP2.frames = Paths.getSparrowAtlas('icons/[ICONNAME]')

iconP1.animation.addByPrefix('normal', 'normal', 24, true);
iconP2.animation.addByPrefix('normal', 'normal', 24, true);
```
