### ISSUE TITLE
What are the variables for the objects stated below?

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#10031]
### Describe your problem here.

So the objects are:
- the score sprites (Shit, Bad, Good, Sick)
- the score numbers (e. g. 002, 013, 027...)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

mods folder

**Comment by frantastic24** [comment]
They aren't objects you can manipulate

**Comment by CheesecakeForever** [comment]
Okay
