### ISSUE TITLE
A request for Shadow Mario

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#10033]
### What is your question?

Please, can you make a version of the example event (opponent fade) that uses the _function eventEarlyTrigger(name)_. It would be very helpful for _everyone,_ since **_NO ONE ELSE HAS ANY IDEA OF HOW TO USE IT!_** 

I'VE CHECKED MULTIPLE WEBSITES, AND _NO ONE_ ELSE KNOWS! _EVEN WITH THE_ [TEMPLATE SCRIPT](https://raw.githubusercontent.com/ShadowMario/FNF-PsychEngine/main/docs/TemplateScript.lua)! 

So please Shadow Mario, can you provide an example event that uses it. It'll be useful for _everyone_, as right now, _the function basically doesn't exist._ 

_**Please.**_

**Comment by Mastercopper2346** [comment]
Should be in enhancements

**Comment by BeastlyGhost** [comment]
```Lua
function eventEarlyTrigger(name, value)
{
    if name == 'Event Name' then
          return value;
    end
}
```

**Comment by wubbzyfan** [comment]
> Should be in enhancements

enhancements?

**Comment by wubbzyfan** [comment]
@BeastlyGhost 

didn't work :(    (though it didn't say "WhOoPs YoU fUcKeD uP aT lUa.69" or anything)

**Comment by tylerandari12** [comment]
> ```lua
> function eventEarlyTrigger(name, value)
> {
>     if name == 'Event Name' then
>           return value;
>     end
> }
> ```

That looks like you tried to use a source code function with a Lua if...
(You dont need to put a function in a table lol...)

@wubbzyfan Try this...

```lua
function eventEarlyTrigger(name, value)
    if name == 'Event Name' then
          return value; -- should be how many milliseconds earlier you want your event to trigger
    end
end
```

**Comment by tylerandari12** [comment]
> > Should be in enhancements
> 
> enhancements?

He means putting this under the Feature Request option when creating a new issue...

**Comment by wubbzyfan** [comment]
@tylerandari12 it didn't work, and i'll try the request thing

**Comment by tylerandari12** [comment]
> @tylerandari12 it didn't work, and i'll try the request thing

******************************Boowomp******************************

**Comment by frantastic24** [comment]
Why is `value` in function variables, it only uses `name`
I tested this and it worked, if it doesn't for you then your event name is wrong or something else in your script has issues

**Comment by wubbzyfan** [comment]
@frantastic24 so you did
function eventEarlyTrigger(name)
    if name == '(Event Name)' then
          return (value); 
    end
end

and where did you put the event stuff (ie the code that makes it do thing)

**Comment by wubbzyfan** [comment]
> The actual event code goes in another function and doesn't really matter here

Ok, I wasn’t sure how it worked! Thanks!

**Comment by wubbzyfan** [comment]
ok i'm just fundamentally wrong i guess thats cool

**Comment by wubbzyfan** [comment]
can someone send me an event with it in there

like the LUA of an event

**Comment by frantastic24** [comment]
Like I said, the actual event doesn't matter here
```lua
function eventEarlyTrigger(name, value)
    if name == 'Change Character' then
          return 1000
    end
end
```
This makes all `Change Character` events trigger 1 second early, note than in this case it's case sensitive

**Comment by wubbzyfan** [comment]
oh so it’s in a script file? ok lemme try

**Comment by wubbzyfan** [comment]
does it not work on lua events?

**Comment by wubbzyfan** [comment]
even with copy and pasting your thing, it doesn't work? is it something wrong with 6.2?

**Comment by frantastic24** [comment]
i guess it was fixed in source because it works in latest commits

**Comment by wubbzyfan** [comment]
huh. Guess I’ll have to wait till 6.3

**Comment by frantastic24** [comment]
Or just get a commit build

**Comment by BeastlyGhost** [comment]
I've talked to SM for a while now, he said eventEarlyTriggers always return stuffs in milliseconds, however some people said it doesn't actually work properly with luas, you should be able to trigger them the same way you do with source code, but in case it doesn't work, it's probably just broken

**Comment by wubbzyfan** [comment]
it seems to be broken

**Comment by tylerandari12** [comment]
> Or just get a commit build

Where could I get one?
(I can't build the source because of an error (#10021))

**Comment by frantastic24** [comment]
Actions
