### ISSUE TITLE
Stupid "Source" Bug When Not Using Source lol

### ISSUE THREAD

**Issue by TheCrepperMaster** [ShadowMario/FNF-PsychEngine#10036]
### Describe your bug here.

When i play ANY song on Chart Editor or on a Normal Gameplay the game crashes and show this shit:

![image](https://user-images.githubusercontent.com/72352491/182686270-5eb93174-b69e-4101-a395-5eb2d3d121f7.png)

Only i can play the first 2 seconds of the song lol.
I hate this because i cant continue with my mod.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I dontsent do something. This happens so much times dont care if i download a old or new version.

**Comment by TheCrepperMaster** [comment]
Sorry for my bad english :)

**Comment by frantastic24** [comment]
Not a bug
Note texture is missing animations

**Comment by TheCrepperMaster** [comment]
So i need to repair something on the chart or what?

**Comment by frantastic24** [comment]
Note texture

**Comment by TheCrepperMaster** [comment]
What do you mean?

**Comment by frantastic24** [comment]
your note texture is missing `end` animations

**Comment by TheCrepperMaster** [comment]
I checked out all, i think its the psych engine version what have a problem on the source. But i find the solution. Thanks.
