### ISSUE TITLE
Arrow Key Input

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#10030]
### Describe your bug here.

For some reason, you cannot press down all four arrow keys, with them working. Sometimes it is even reduced to two, not allowing to press the other two.

(Mainly the left key may be the issue?)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not via source

**Comment by CrusherMods** [comment]
Not a bug that's a keyboard thing
My controls are QWOP and I can press them all down at once and it works
but if I press down all my arrow keys down at once either 2 or 3 will work
so its a keyboard problem not psych problem

**Comment by ZeitHeld** [comment]
that's stupid-
but also same appllies sometimes to mutlikey shaggy mods-
