### ISSUE TITLE
crash because of i don't know

### ISSUE THREAD

**Issue by MarioLOLZ** [ShadowMario/FNF-PsychEngine#10038]
### Describe your bug here.

i'm making stuff for the mods folder like i have been. i wanted to do a song and chart, so i made the week file and the song data file. when i play the song, it comes up with the error that i have pasted below. i have no idea what is going on or how to fix it

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
Character.hx (line 164)
PlayState.hx (line 913)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

made a week with test, and re-added in hot-dilf

**Comment by frantastic24** [comment]
not a bug
character is missing .xml
