### ISSUE TITLE
Frequent crash because of "missing BF" when he is here

### ISSUE THREAD

**Issue by KillerAvecRage** [ShadowMario/FNF-PsychEngine#10032]
### Describe your bug here.

My game crashes frequently in chart editor because of a missing file: "bf.json"
But the file is here
![image](https://user-images.githubusercontent.com/103606542/182640617-c183f301-34b6-4d98-a3ad-8af3adcddb38.png)

I don't know why and as I said this crash is frequent, so I'm wondering what is the problem?

Edit: I have a crash file now:
![image](https://user-images.githubusercontent.com/103606542/182645777-1f576b1e-b880-4607-9ec6-9d547faed10d.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I was testing my mod that I wanted to fix

**Comment by tylerandari12** [comment]
The game automatically thinks that base game stuff (like `bf.json`) is in the assets folder (hence the missing file is `assets/characters/bf.json`).

Name your custom bf something else and do the same for any other characters...

**Comment by tylerandari12** [comment]
Also the original bf is missing from the asstes folder. You might wanna look into that...

**Comment by KillerAvecRage** [comment]
The OG BF **IS** in the assets folder, this is the problem, but I tried deleting the duplicates, I'll see how it goes

**Comment by KillerAvecRage** [comment]
Deleting duplicates doesn't seem to help, I just got the crash again

**Comment by KillerAvecRage** [comment]
Alright, 23 days later, I haven't got this problem anymore so I'm gonna close this, if you ever encounter this problem in the future, check if there are any duplicate and delete them if there are
