### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#10044]
### Describe your problem here.

I am making a score text that will replace the stats under the health bar, it works, but it's always set to 0.
![image](https://user-images.githubusercontent.com/98123933/182822494-9b7c2edc-7c42-478c-8b65-d1130a83fea9.png)
Even when I hit a note and when the score rises it doesn't change. Help?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Mods folder

**Comment by Mastercopper2346** [comment]
Send the script

**Comment by bruh1cat** [comment]
Make sure that you have setTextString('name of text', score) if that doesn't work send the script

**Comment by CheesecakeForever** [comment]
thanks just had to put setTextString('tag', 'text'..score) under onUpdate(elapsed)
