### ISSUE TITLE
Game crashed then i tried load character sprites

### ISSUE THREAD

**Issue by TurlyGitHub** [ShadowMario/FNF-PsychEngine#10045]
### Describe your bug here.

I draw a character, make a png with sprites, make xml, drop them in /image/characters. Then i open game, enter character editor, try to load sprites but then open error and after pressing "ok" game crashed.
![image](https://user-images.githubusercontent.com/81519674/182831845-1fb99e0b-33b1-4885-8b25-3c08f3735511.png)

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 239)
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 285)
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 117)
C:\HaxeToolkit\haxe\std/Xml.hx (line 122)
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
editors/CharacterEditorState.hx (line 840)
editors/CharacterEditorState.hx (line 520)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: haxe.xml.XmlParserException: Expected attribute name at line 4 char 0
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Absolutely nothing.

**Comment by frantastic24** [comment]
not a bug your xml is fucked
