### ISSUE TITLE
Error: __boot__.cpp

### ISSUE THREAD

**Issue by duckyduck1q** [ShadowMario/FNF-PsychEngine#10049]
### Describe your bug here.

Error: __boot__.cpp
C:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/linc_discord_rpc.h(7): fatal error C1083: No se puede abrir el archivo incluir: '../lib/discord-rpc/include/discord-rpc.h': No such file or directory

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Not a bug and duplicate #8379

**Comment by frantastic24** [comment]
And you opened three fucking duplicates
