### ISSUE TITLE
__boot__.cpp

### ISSUE THREAD

**Issue by duckyduck1q** [ShadowMario/FNF-PsychEngine#10041]
### Describe your problem here.

source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/MainMenuState.hx:69: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:370: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/CharacterEditorState.hx:94: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/DialogueCharacterEditorState.hx:87: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

Compiling group: haxe
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/ -IC:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/ -I C:/HaxeToolkit/haxe/lib/hxCodec/2,5,1/lib/vlc/include/ -I C:/HaxeToolkit/haxe/lib/hxCodec/2,5,1/lib/vlc/src/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\Usuario\Downloads\FNF-PsychEngine-0.6.2\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_CHECK_POINTER(haxe) -DHXCPP_STACK_LINE(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/__boot__.cpp
 - src/llua/Lua_helper.cpp
 - src/openfl/display/_StageAlign/StageAlign_Impl_.cpp
 - src/flixel/input/gamepad/id/SwitchJoyconLeftID.cpp
 - src/lime/text/GlyphMetrics.cpp  [haxe,release]
 - src/flixel/input/actions/FlxActionManager.cpp
 - src/editors/MenuCharacterEditorState.cpp
Error: __boot__.cpp
C:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/linc_discord_rpc.h(7): fatal error C1083: No se puede abrir el archivo incluir: '../lib/discord-rpc/include/discord-rpc.h': No such file or directory

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by tylerandari12** [comment]
You can ignore all the depreciated stuff as it wont halt your game...

The main error is the last line:
```
C:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/linc_discord_rpc.h(7): fatal error C1083: No se puede abrir el archivo incluir: '../lib/discord-rpc/include/discord-rpc.h': No such file or directory
```

I'm no source guy but it looks like your missing the Discord-RPC stuff...

Try doing `haxelib import discord` in your command prompt or delete line 140 (`<haxelib name="discord_rpc" if="desktop"/>`) in [Project.xml](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/Project.xml).

**Comment by HarithHkm08** [comment]
Try reinstalling the entire Haxe and its library. Redo all the steps from the Kade Engine website.
https://kadedev.github.io/Kade-Engine/building

IMPORTANT: Don't reinstall discord rpc if it was installed or the same problem will occured again
