### ISSUE TITLE
tweening stage opacity

### ISSUE THREAD

**Issue by QuestioningAccount** [ShadowMario/FNF-PsychEngine#10042]
### Describe your problem here.

How do you tween the opacity of a stage object in the PlayState?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, but none of the changes will affect my problem.

**Comment by BernardoGP4504** [comment]
do a FlxTween of the alpha value (go to haxeflixel's website and search for FlxTween for more info on how to use)
