### ISSUE TITLE
Can someone give me an example of this?

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#10051]
### Describe your problem here.

Can someone send an example of using _italic_ on text? I found it on the wiki, but i don't know what to write except for the `tag`.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Mods folder

**Comment by frantastic24** [comment]
`true`

**Comment by CheesecakeForever** [comment]
so like `setTextItalic('tag', true)` ?

**Comment by CheesecakeForever** [comment]
Accidentally closed it

**Comment by frantastic24** [comment]
you could just test it

**Comment by CheesecakeForever** [comment]
I'll try again, but it didn't work last time

**Comment by CheesecakeForever** [comment]
Still, nothing

**Comment by CheesecakeForever** [comment]
y'know what nevermind it's good enough this way
