### ISSUE TITLE
Error: __boot__.cpp

### ISSUE THREAD

**Issue by duckyduck1q** [ShadowMario/FNF-PsychEngine#10050]
### Describe your problem here.

Error: __boot__.cpp
C:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/linc_discord_rpc.h(7): fatal error C1083: No se puede abrir el archivo incluir: '../lib/discord-rpc/include/discord-rpc.h': No such file or directory

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheAverageGitHubUser** [comment]
Duplicated + re-download haxe or psych engine

**Comment by tylerandari12** [comment]
Pretty sure I've said in a duplicate you've uploaded...
`haxelib install discord` in your command bar o terminal

**Comment by Mastercopper2346** [comment]
STOP SPAMMING THIS

**Comment by duckyduck1q** [comment]
shut tha fuck up

**Comment by ShadowMario** [comment]
> @ShadowMario Duplicate lol.

Don't tag me, i have notifications turned off and am 24/7 on "Do not disturb", it won't do shit.
