### ISSUE TITLE
ANDRIOD

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#10057]
### Describe your problem here.

how do I build android

I installed everything

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No (other than the accuracy 'ratingStuff'), just modded in the "example_mods" folder

**Comment by frantastic24** [comment]
Not supported

**Comment by TFLTV** [comment]
> Not supported

what does that mean
