### ISSUE TITLE
My healthbar is gone

### ISSUE THREAD

**Issue by FartMaster57** [ShadowMario/FNF-PsychEngine#10059]
### Describe your problem here.

Suddenly the healthbar (including the score and accuracy etc.) is just gone from literally every song in my copy of psych engine, I even tried installing a new version and it's still gone. Please help how do I fix this
![2022-08-04 (6)](https://user-images.githubusercontent.com/58342249/182992158-8f35fb96-2ae0-4dc7-8cd9-a8e5832f4e84.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a lot of mods in my mods folder idk

**Comment by Lorekeeper49** [comment]
Uncheck Hide HUD

**Comment by TFLTV** [comment]
> Uncheck Hide HUD

options > visual and UI > hide UI

**Comment by FartMaster57** [comment]
Bro how tf did hide hud even get checked lmao
Anyways thanks
