### ISSUE TITLE
Mp4 support for mac

### ISSUE THREAD

**Issue by adamsaustria** [ShadowMario/FNF-PsychEngine#10054]
### What feature do you want to get added on the **base** engine?

Add mp4 support for mac users

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by TheRealJake12** [comment]
its already there. You just gotta install the git version of hxCodec (`haxelib git hxCodec https://github.com/polybiusproxy/hxCodec`) and replace all the `vlc.MP4Handler` with `VideoHandler`

**Comment by TheRealJake12** [comment]
close this issue.

**Comment by adamsaustria** [comment]
i don't know how to replace it how do you do that

**Comment by TheRealJake12** [comment]
oh you are a lua user. Then just wait. Or you could try and download source and change what I said to.

**Comment by tylerandari12** [comment]
> i don't know how to code so i was trying to ask someone to do it

For future reference it's not taken lightly when someone asks for code...
