### ISSUE TITLE
Flipping the healthbar in source

### ISSUE THREAD

**Issue by ivorivorhepl** [ShadowMario/FNF-PsychEngine#10069]
### Describe your problem here.

im trying to make the health bar flip in source and it wont work. can anyone help?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Added some random shit but nothing affects the healthbar

**Comment by Mastercopper2346** [comment]
`healthBar.flipX = true; `??

**Comment by ivorivorhepl** [comment]
oh wait lmao lemme try that

**Comment by ivorivorhepl** [comment]
it uh crashed the game lmao

**Comment by Mastercopper2346** [comment]
`healthBar.angle = 180;`??

**Comment by ivorivorhepl** [comment]
another crash lol

**Comment by SrtHero278** [comment]
Where from source are you flipping healthbar?
And where are you putting this line?

**Comment by ivorivorhepl** [comment]
Putting it near the "stress" game overstate thing. i thought it would work fine there lol

**Comment by Mastercopper2346** [comment]
IT DOESNT HAVE THE HEALTHBAR THATS WHY ITS CRASHING

**Comment by Mastercopper2346** [comment]
Sorry caps

**Comment by ivorivorhepl** [comment]
me being a idiot:
okay lemme try that lmao
