### ISSUE TITLE
Holding down a number in the Vortex Editor should make a hold note

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#10067]
### What feature do you want to get added on the **base** engine?

(read title)
It’d make using this better, so you down have to stop at every long note

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
Duplicate of #9953

**Comment by wubbzyfan** [comment]
oh ok
