### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#10060]
### Describe your problem here.

how do I make the game crash in source code

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No (other than the accuracy 'ratingStuff'), just modded in the "example_mods" folder

**Comment by Raltyro** [comment]
smh

```hx
Sys.exit(0);
```

**Comment by TFLTV** [comment]
> smh
> 
> ```hx
> Sys.exit(0);
> ```

cool
