### ISSUE TITLE
Crashing when importing a chart

### ISSUE THREAD

**Issue by Bowzerz9001** [ShadowMario/FNF-PsychEngine#10064]
### Describe your bug here.

So I've been working on recharting that old soulless 5 chart, and it now just refuses to load the chart, I've checked the area that it specifies and nothing seems to be wrong with the chart in that area
![image](https://user-images.githubusercontent.com/72467767/183095179-22ff9dfc-df72-48b0-a61b-3568ced571fc.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No this is a completely stock build

**Comment by Bowzerz9001** [comment]
Here's the exact positions of both parts of the chart too
![image](https://user-images.githubusercontent.com/72467767/183096387-413e93f7-e336-4717-9f3a-95afe8c0f363.png)
![image](https://user-images.githubusercontent.com/72467767/183096297-44802773-220d-4541-80a8-3f6022634f3c.png)

**Comment by LilMewo** [comment]
could you send me the chart? my discord is LilMewo#8045

**Comment by Bowzerz9001** [comment]
Sent a request
