### ISSUE TITLE
ending dialogue giving weird error

### ISSUE THREAD

**Issue by Alt-Reality** [ShadowMario/FNF-PsychEngine#1006]
### Describe your problem here.

I already made an issue on this and found out what the code was, but i got the following error:
![image](https://user-images.githubusercontent.com/88809517/141605779-29e0c0fc-e740-447f-b7ac-1c2f0a237570.png)
before i could report this error in my issue, it was closed, so i didnt know what else to do apart from making a new issue on this.
Basically, i want to make a code to make my dialogue happen before and after in a one song mod. I already know how to make dialogue happen at the beginning, but not at the end. Shadow mario helped my out with this by giving code for this
![image](https://user-images.githubusercontent.com/88809517/141605958-6d19e9b2-4344-4e46-92bb-b67a10815517.png)
And so, i did it, i made the new postSongDialogue function and line 2888-2891
![image](https://user-images.githubusercontent.com/88809517/141605960-06c6c12b-1a31-4aab-82e0-d36f149d1116.png)
However, when I tried compiling the game I got these errors:
![image](https://user-images.githubusercontent.com/88809517/141605981-d500300b-23b7-407f-806f-3de97308569e.png)
I was about to report this in my original issue, but it was closed. 
How do I fix this? Code? and for the area where i play the dialogue, would i just do postSongDialogue(dialogueJson); or should i do just postSongDialogue();

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

PlayState.hx for stage code and the enddialogue stuff i just did, FreeplayState, StoryMenuState, and CoolUtil to remove a difficulty.

**Comment by perngjiafu** [comment]
you cant

just use a cutscene?

**Comment by Alt-Reality** [comment]
> you cant
> 
> just use a cutscene?

I think that if the creator of the engine gave me code for this, they would basically be saying "yes you can."

**Comment by ShadowMario** [comment]
My bad, `postSongDialogue` instead of `postSongDialogue()` on the finishCallback thing.

**Comment by Alt-Reality** [comment]
> My bad, `postSongDialogue` instead of `postSongDialogue()` on the finishCallback thing.

didnt fix anything unfortunately 
![image](https://user-images.githubusercontent.com/88809517/141698210-7700aa8b-0859-49d3-b860-21f33a2d6a44.png)
![image](https://user-images.githubusercontent.com/88809517/141698224-c98ac944-ab4a-4b07-9621-e32af5c816ee.png)

**Comment by ShadowMario** [comment]
You forgot to put the song name on `Paths.formatToSongPath(SONG.song)`
Change it to `Paths.formatToSongPath(SONG.song) == 'my-song-name'`

And change:
```haxe
var file:String = Paths.json(songName + '/dialogueEnd');
var dialogueJson:String = DialogueBoxPsych.parseDialogue(file);
startDialogue(dialogueJson);
```
to:
```haxe
var songName:String = Paths.formatToSongPath(SONG.song);
var file:String = Paths.json(songName + '/dialogueEnd');
startDialogue(DialogueBoxPsych.parseDialogue(file));
```
