### ISSUE TITLE
Game crashing mid-way through a song

### ISSUE THREAD

**Issue by thawnglv** [ShadowMario/FNF-PsychEngine#10068]
### Describe your bug here.

All of my songs randomly start lagging and eventually crashes the game around the 2:20 and 2:25 mark.
I don't know if there's an easy solution that I'm missing because I have little coding experience.  

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

All I did was make the mod (Adding Songs, sprites, stages, etc)

**Comment by Whiteconbi** [comment]
do u have the textures and stuff?
