### ISSUE TITLE
Story Mode & Freeplay won't load.

### ISSUE THREAD

**Issue by thawnglv** [ShadowMario/FNF-PsychEngine#10063]
### Describe your bug here.

I'm making my mod, and wanted to preview it on freeplay, so when I did, I got this message: 
FreeplayState.hx (line 74)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

I don't know if I'm missing anything, or if there's an easy solution because I have very little coding experience

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

All I did was make the mod (Adding Songs, sprites, stages, etc)

**Comment by frantastic24** [comment]
Issue with your week file

**Comment by thawnglv** [comment]
Okay yeah, I just has to replace it with a new one

**Comment by frantastic24** [comment]
You can close this
