### ISSUE TITLE
song restarting after finished, no notes only music

### ISSUE THREAD

**Issue by MarioLOLZ** [ShadowMario/FNF-PsychEngine#10074]
### Describe your bug here.

it's exactly as the title says. i was in full screen mode, where you press alt + enter to get in and out of it. i played a song as normal as normal from the freeplay menu, it worked. after the song was finished, but not before the menu music played, i pressed alt + enter to get out of full screen. it paused the song, and when i unpaused the song started over from the beginning with no notes at all. my accuracy and points were exactly the same as the end of the song, but at the beginning. bf doesn't do his idle, but the opponent and gf do. the camera even does its job of tracking the "must hit section"s of the chart for turns. not sure if this was documented already since i'm too lazy to check, but it has something to do with pausing a song just as it's ended and transitioning to the menu. i've attached a video of what i'm describing happening.
https://user-images.githubusercontent.com/108432831/183237810-17008861-c0f5-4720-8057-18c943f98ba3.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by tylerandari12** [comment]
So you paused the song and restarted during the end transition and it restarted itself?

**Comment by MarioLOLZ** [comment]
I pressed alt + enter to get out of full screen, and it paused. I pressed resume to resume it and finish the song, but it restarted after I pressed resume with the stuff I said.

**Comment by tylerandari12** [comment]
They need to make it where the game wont pause if `alt` is being pressed...
