### ISSUE TITLE
Make it possible for value1 and value2 to be used in earlyEventTrigger

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#10079]
### What feature do you want to get added on the **base** engine?

So there's the function of earlyeventtrigger, which is currently only able to use the event name as a... whatever the (things, like, this) are called, but it would be very neat if it had the values like the onEvent function, so that things that would need a different return time based on if value1 is 1 or 2 or something can be done and that would be neat

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tylerandari12** [comment]
This is cool but I feel like we'd need a way to iterate over all the events in the song...
(Kinda like iterating over all notes to change the texture of them...)

**Comment by frantastic24** [comment]
The game already does that

**Comment by tylerandari12** [comment]
>>This is cool but I feel like we'd need a way to iterate over all the events in the song...
>>(Kinda like iterating over all notes to change the texture of them...)
> 
> The game already does that

Then how do I do it?

**Comment by frantastic24** [comment]
You don't, like I said the game does that already

**Comment by wubbzyfan** [comment]
so how do I use value1 and value2

**Comment by frantastic24** [comment]
You can't

**Comment by wubbzyfan** [comment]
can it be added to the engine please?

**Comment by frantastic24** [comment]
You are free to open a PR or just make your own fork

**Comment by wubbzyfan** [comment]
time to learn how to code source then i guess :))))))))))))))))))

**Comment by ShadowMario** [comment]
Done on experimental branch

**Comment by wubbzyfan** [comment]
YOOOO POGGERS
