### ISSUE TITLE
How do I make an image appear when Hitting a note?

### ISSUE THREAD

**Issue by SENFULLHD4K** [ShadowMario/FNF-PsychEngine#10073]
### What is your question?

**I want to know how to make an image appear when hitting the arrow, the arrow is a custom that makes it cover the gameplay so as not to be visible**

 **Also that the Custom Arrow does not decrease the life of Bf**

Please I would really appreciate it

**Comment by Mastercopper2346** [comment]
makeLuaSrpite()

**Comment by SENFULLHD4K** [comment]
> makeLuaSprite()

Yes, but what exactly do I have to do to make the image appear when a certain note fails?

**Comment by SENFULLHD4K** [comment]
> makeLuaSprite()

Yes, but what exactly do I have to do to make the image appear when a certain note fails?

**Comment by frantastic24** [comment]
[Callbacks are on wiki](https://raw.githubusercontent.com/ShadowMario/FNF-PsychEngine/main/docs/TemplateScript.lua)
