### ISSUE TITLE
Song crashes randomly at certain part without error or consolelog.

### ISSUE THREAD

**Issue by JacksonTheDev** [ShadowMario/FNF-PsychEngine#10070]
### Describe your bug here.

Hello.

I recently started coding a song for my mod, it goes well and there's no lag or anything.
The problem comes at the last part, where the song randomly lags 2 frames, and the game crashes.

This happens on another song too, which is from my customization.

The code is nowhere intended to do anything on that part, neither the source or lua are acting there,
as well as no events going on.

I've also tested if the sprites were causing the problem but didn't help the issue.

Something also strange is that when I launch the application on debug mode, the song does not
crash so I can't figure out the error either

https://user-images.githubusercontent.com/56284814/183227927-22dfe7e1-141f-4d48-acef-cf40b6e370bf.mp4

.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

The only modified files are StoryMode, TitleScreen and add-ons through the Mods folder (No lua Scripts)

**Comment by Jevilm** [comment]
IT KEEPS HAPPENING TO ME TOO BUT ITS ON A DOWNLOADED BUILD

**Comment by JacksonTheDev** [comment]
> 

Aye! A friend called out that this occures because of a high fps selection, i was on 240 fps and lowered down to 90 and no more crashes at all, try on that, -J

**Comment by letsgoawaydev** [comment]
that fix works, but its a bit annoying @JacksonTheDev 

especially since new monitors with higher refresh rates are coming out and people would like to play games smoothly

i say psych engine team either finds out why this happens or they temporarily lower the fps limit in settings to 120, because at least for me 120 does not crash the game

**Comment by letsgoawaydev** [comment]
also, whatts weirder is if you play on the chart editor test mode (no chars or bg) it doesnt crash
