### ISSUE TITLE
Psych Engine keeps crashing for no reason

### ISSUE THREAD

**Issue by Jevilm** [ShadowMario/FNF-PsychEngine#10078]
### Describe your bug here.

Im using a downloaded build of psych engine 0.5.1 and the engine keeps crashing for no reason, idk why, like its not giving me a warning or something, The engine lags more as i get into a song aswell

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added 2 lua scripts. Literally 2 of them.

**Comment by frantastic24** [comment]
A bug on an outdated version isn't valid

**Comment by Jevilm** [comment]
ok
