### ISSUE TITLE
Whenever i try to open a custom character game crashes

### ISSUE THREAD

**Issue by marbloxy** [ShadowMario/FNF-PsychEngine#10076]
### Describe your bug here.

So whenever i try to open a custom character to edit it, i get this error and the game crashes.
![image](https://user-images.githubusercontent.com/102739159/183245280-e1f6f2e4-75da-4a2e-a656-a62056f7a6f2.png)

I use the 32bit latest version

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i did not edit anything in this build.

**Comment by frantastic24** [comment]
Not a bug
Fix your xml

**Comment by marbloxy** [comment]
> Not a bug Fix your xml

I'll check. I exported the spritesheet and xml using adobe and looked for all issues and fixed them. Maybe i did smth wrong

**Comment by marbloxy** [comment]
> > Not a bug Fix your xml
> 
> I'll check. I exported the spritesheet and xml using adobe and looked for all issues and fixed them. Maybe i did smth wrong

Looked inside the xml and couldn't find anything. Ill try to look more into it
