### ISSUE TITLE
Too much Lua may cause Lags

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#10077]
### Describe your bug here.

I don't know, if that is entirely true, but I kind of noticed, that a lot of use of Lua (in a short time?), may cause it to lag.

For example, I charted a song and have an event that puts the Lyrics on the screen (with replacing the strings conent from before)
After a while I got about two lag spikes.

Or another one, where I made little Icons appear on screen and they bop a bit on beat and move in the same direction, as the arrows are pointing at

On faster/longer songs it got a few lag spikes. Or even on Triple Trouble (where I then simply replaced the icon and it's position), but with the exception, that the game just straight up crashed.

So I think, that using too much lua/making too many lua calls, might lag out the game quite a bit.
But IDK if it can be "fixed" or my computer then simply is too weak.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Lua changes/examples are written, source code is none

**Comment by frantastic24** [comment]
It's a memory leak

**Comment by ZeitHeld** [comment]
I know that, that is the only that causes lags-
but it is still annyoing, if the game freezes for a bit while you should be hitting ntoes

**Comment by frantastic24** [comment]
Idk even before I fixed it myself it didn't lag

**Comment by tylerandari12** [comment]
> Idk even before I fixed it myself it didn't lag

You have a fest PC lol

**Comment by frantastic24** [comment]
I very much don't

**Comment by KillerAvecRage** [comment]
The only way I see is trying to optimise your code, like trying to change any "onUpdate()" to "onCreate()"

**Comment by ZeitHeld** [comment]
Though I didn't change very much-
It was literally that thing probably-
"FNF Freeplay", the mod I modified, is a bit bigger, but I really didn't do too much in it.
So I think it really might be the probably constant call of "onBeatHit()" which would then again be sadly stupid-
It's like implementing a feature, where it is good from the idea, but the game will crash each time-
