### ISSUE TITLE
Lua Sprite Becomes Black Graphic Error

### ISSUE THREAD

**Issue by gamenwatch412** [ShadowMario/FNF-PsychEngine#10087]
### Describe your problem here.

Hello, I have this mechanic in my mod where as time in the song passes, a bar increases and at 100% it drains your health. To decrease the bar you have hit a certain note I coded. My lua script works, however hitting said note when the bar is at zero causes graphical errors where the bar sprites turn black.

I have provided a video demonstration as well as my code. Any help would be greatly appreciated on how to fix this!

`freezeval=0;
percent=0;
shaking=false;

function onCreate()
makeLuaSprite('sheercold', 'SheerColdBar', 640-(281/2), 142);
makeLuaSprite('freezewarning', 'freezewarning', 465, 116);
makeLuaSprite('totallyrealbar', nil, 503, 226);
makeGraphic('totallyrealbar', freezeval, 10, 'dafafc');
scaleObject('freezewarning', 1.1, 1.3);
addLuaSprite('freezewarning');
addLuaSprite('totallyrealbar', true);
setBlendMode('freezewarning', darken);
setObjectCamera('freezewarning', 'hud');
setObjectCamera('sheercold', 'hud');
setObjectCamera('totallyrealbar', 'hud');
addLuaSprite('sheercold');

makeLuaSprite('blackgradient', 'BlackGradient', -200, -250);
setObjectCamera('blackgradient', 'other');
setScrollFactor('blackgradient', 0, 0);
scaleObject('blackgradient', 1.4, 1.4)
setProperty('blackgradient.visible', false);
addLuaSprite('blackgradient', true);

makeLuaSprite('gradient', 'bluegradient', -70, -50);
setObjectCamera('gradient', 'other');
setScrollFactor('gradient', 0, 0);
scaleObject('gradient', 1.15, 1.15);
setProperty('gradient.angle', 180);
addLuaSprite('gradient', true);

if getPropertyFromClass('ClientPrefs', 'downScroll') == true then
setProperty('gradient.angle', 360);
end

if getPropertyFromClass('ClientPrefs', 'downScroll') == false then
   setProperty('sheercold.y', 470);
   setProperty('freezewarning.y', 444);
   setProperty('totallyrealbar.y', 554);
   end
end

function onBeatHit(id, direction, noteType, isSustainNote)
if curBeat % 2 == 0 then 
percent = percent + 5;
freezeval = percent * 2.61;
end

if percent > 100 then
    percent = 100;
    local minushealth=0.0475;
    local health=getProperty('health');
    local minusfreezeval=0;
    if getProperty('health') > 0.2 then
    setProperty('health', health- 0.03);
    end
elseif percent < 0 then
    percent = 0;
end

makeGraphic('totallyrealbar', freezeval, 10, 'dafafc');
setProperty('health', health - minushealth - minusfreezeval)
end

-- Note miss/hit
function goodNoteHit(id, direction, noteType, isSustainNote)
    if noteType == 'Warm Note' then
        percent = percent - 10;
        freezeval = percent * 2.5;
    elseif noteType == 'Sheer Cold Note' then
        percent = percent + 5;
        freezeval = percent * 2.5;
end

makeGraphic('totallyrealbar', freezeval, 10, 'dafafc');
setProperty('health', health - minushealth - minusfreezeval)
end

function onUpdate(elapsed)
       if percent == 0 then
          setProperty('gradient.alpha', 0.0);
          setProperty('freezewarning.alpha', 0.0);
          cameraShake('camera', 0, 999);
          cameraShake('camHUD', 0, 999);
       end
       if percent == 10 then
          setProperty('gradient.alpha', 0.1);
          setProperty('freezewarning.alpha', 0.1);
         cameraShake('camera', 0.001, 999);
         cameraShake('camHUD', 0.001, 999);
       end
       if percent == 20 then
          setProperty('gradient.alpha', 0.2);
          setProperty('freezewarning.alpha', 0.2);
          cameraShake('camera', 0.002, 999);
          cameraShake('camHUD', 0.002, 999);
       end
       if percent == 30 then
          setProperty('gradient.alpha', 0.3);
          setProperty('freezewarning.alpha', 0.3);
          cameraShake('camera', 0.003, 999);
          cameraShake('camHUD', 0.003, 999);
       end
       if percent == 40 then
          setProperty('gradient.alpha', 0.4);
          setProperty('freezewarning.alpha', 0.4);
          cameraShake('camera', 0.004, 999);
          cameraShake('camHUD', 0.004, 999);
       end
       if percent == 50 then
          setProperty('gradient.alpha', 0.5);
          setProperty('freezewarning.alpha', 0.5);
          cameraShake('camera', 0.005, 999);
          cameraShake('camHUD', 0.005, 999);
       end
       if percent == 60 then
          setProperty('gradient.alpha', 0.6);
          setProperty('freezewarning.alpha', 0.6);
          cameraShake('camera', 0.006, 999);
          cameraShake('camHUD', 0.006, 999);
       end
       if percent == 70 then
          setProperty('gradient.alpha', 0.7);
          setProperty('freezewarning.alpha', 0.7);
          cameraShake('camera', 0.007, 999);
          cameraShake('camHUD', 0.007, 999);
       end
       if percent == 80 then
          setProperty('gradient.alpha', 0.8);
          setProperty('freezewarning.alpha', 0.8);
          cameraShake('camera', 0.008, 999);
          cameraShake('camHUD', 0.008, 999);
       end
       if percent == 90 then
          setProperty('gradient.alpha', 0.9);
          setProperty('freezewarning.alpha', 0.9);
          cameraShake('camera', 0.009, 999);
          cameraShake('camHUD', 0.009, 999);
       end
       if percent == 100 then
          setProperty('gradient.alpha', 1.0);
          setProperty('freezewarning.alpha', 1.0);
          cameraShake('camera', 0.010, 999);
          cameraShake('camHUD', 0.010, 999);
       end
    end`

https://user-images.githubusercontent.com/81721386/183271059-0fc93433-d6c3-42f5-bcaf-60f1aceea001.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Mastercopper2346** [comment]
```lua
freezeval=0;
percent=0;
shaking=false;

function onCreate()
     makeLuaSprite('sheercold', 'SheerColdBar', 640-(281/2), 142);
     makeLuaSprite('freezewarning', 'freezewarning', 465, 116);
     makeGraphic('totallyrealbar', freezeval, 10, 'dafafc');
     scaleObject('freezewarning', 1.1, 1.3);
     addLuaSprite('freezewarning');
     setBlendMode('freezewarning', darken);
     setObjectCamera('freezewarning', 'hud');
     setObjectCamera('sheercold', 'hud');
     addLuaSprite('sheercold');

     makeLuaSprite('blackgradient', 'BlackGradient', -200, -250);
     setObjectCamera('blackgradient', 'other');
     setScrollFactor('blackgradient', 0, 0);
     scaleObject('blackgradient', 1.4, 1.4)
     setProperty('blackgradient.visible', false);
     addLuaSprite('blackgradient', true);

     makeLuaSprite('gradient', 'bluegradient', -70, -50);
     setObjectCamera('gradient', 'other');
     setScrollFactor('gradient', 0, 0);
     scaleObject('gradient', 1.15, 1.15);
     setProperty('gradient.angle', 180);
     addLuaSprite('gradient', true);

     if getPropertyFromClass('ClientPrefs', 'downScroll') == true then
          setProperty('gradient.angle', 360);
     end

     if getPropertyFromClass('ClientPrefs', 'downScroll') == false then
          setProperty('sheercold.y', 470);
          setProperty('freezewarning.y', 444);
     end
end

function onBeatHit()
     if curBeat % 2 == 0 then
          percent = percent + 5;
          freezeval = percent * 2.61;
     end

     if percent > 100 then
          percent = 100;
          local minushealth=0.0475;
          local health=getProperty('healthBar.percent');
          local minusfreezeval=0;
          if getProperty('healthBar.percent') > 10 then
               setProperty('health', health- 1.5);
          end
          elseif percent < 0 then
          percent = 0;
     end

     makeGraphic('totallyrealbar', freezeval, 10, 'dafafc');
     setProperty('health', health - minushealth - minusfreezeval)
end

function goodNoteHit(id, direction, noteType, isSustainNote)
     if noteType == 'Warm Note' then
          percent = percent - 10;
          freezeval = percent * 2.5;
     elseif noteType == 'Sheer Cold Note' then
          percent = percent + 5;
          freezeval = percent * 2.5;
     end

     makeGraphic('totallyrealbar', freezeval, 10, 'dafafc');
     setProperty('health', health - minushealth - minusfreezeval)
end

function onUpdate(elapsed)
     if percent <= 0 then
          setProperty('gradient.alpha', 0.0);
          setProperty('freezewarning.alpha', 0.0);
          cameraShake('camera', 0, 999);
          cameraShake('camHUD', 0, 999);
     end
     if percent == 10 then
          setProperty('gradient.alpha', 0.1);
          setProperty('freezewarning.alpha', 0.1);
          cameraShake('camera', 0.001, 999);
          cameraShake('camHUD', 0.001, 999);
     end
     if percent == 20 then
          setProperty('gradient.alpha', 0.2);
          setProperty('freezewarning.alpha', 0.2);
          cameraShake('camera', 0.002, 999);
          cameraShake('camHUD', 0.002, 999);
     end
     if percent == 30 then
          setProperty('gradient.alpha', 0.3);
          setProperty('freezewarning.alpha', 0.3);
          cameraShake('camera', 0.003, 999);
          cameraShake('camHUD', 0.003, 999);
     end
     if percent == 40 then
          setProperty('gradient.alpha', 0.4);
          setProperty('freezewarning.alpha', 0.4);
          cameraShake('camera', 0.004, 999);
          cameraShake('camHUD', 0.004, 999);
     end
     if percent == 50 then
          setProperty('gradient.alpha', 0.5);
          setProperty('freezewarning.alpha', 0.5);
          cameraShake('camera', 0.005, 999);
          cameraShake('camHUD', 0.005, 999);
     end
     if percent == 60 then
          setProperty('gradient.alpha', 0.6);
          setProperty('freezewarning.alpha', 0.6);
          cameraShake('camera', 0.006, 999);
          cameraShake('camHUD', 0.006, 999);
     end
     if percent == 70 then
          setProperty('gradient.alpha', 0.7);
          setProperty('freezewarning.alpha', 0.7);
          cameraShake('camera', 0.007, 999);
          cameraShake('camHUD', 0.007, 999);
     end
     if percent == 80 then
          setProperty('gradient.alpha', 0.8);
          setProperty('freezewarning.alpha', 0.8);
          cameraShake('camera', 0.008, 999);
          cameraShake('camHUD', 0.008, 999);
     end
     if percent == 90 then
          setProperty('gradient.alpha', 0.9);
          setProperty('freezewarning.alpha', 0.9);
          cameraShake('camera', 0.009, 999);
          cameraShake('camHUD', 0.009, 999);
     end
     if percent == 100 then
          setProperty('gradient.alpha', 1.);
          setProperty('freezewarning.alpha', 1);
          cameraShake('camera', 0.01, 999);
          cameraShake('camHUD', 0.01, 999);
     end
end
```
try this?

**Comment by gamenwatch412** [comment]
> ```lua
> freezeval=0;
> percent=0;
> shaking=false;
> 
> function onCreate()
>      makeLuaSprite('sheercold', 'SheerColdBar', 640-(281/2), 142);
>      makeLuaSprite('freezewarning', 'freezewarning', 465, 116);
>      makeGraphic('totallyrealbar', freezeval, 10, 'dafafc');
>      scaleObject('freezewarning', 1.1, 1.3);
>      addLuaSprite('freezewarning');
>      setBlendMode('freezewarning', darken);
>      setObjectCamera('freezewarning', 'hud');
>      setObjectCamera('sheercold', 'hud');
>      addLuaSprite('sheercold');
> 
>      makeLuaSprite('blackgradient', 'BlackGradient', -200, -250);
>      setObjectCamera('blackgradient', 'other');
>      setScrollFactor('blackgradient', 0, 0);
>      scaleObject('blackgradient', 1.4, 1.4)
>      setProperty('blackgradient.visible', false);
>      addLuaSprite('blackgradient', true);
> 
>      makeLuaSprite('gradient', 'bluegradient', -70, -50);
>      setObjectCamera('gradient', 'other');
>      setScrollFactor('gradient', 0, 0);
>      scaleObject('gradient', 1.15, 1.15);
>      setProperty('gradient.angle', 180);
>      addLuaSprite('gradient', true);
> 
>      if getPropertyFromClass('ClientPrefs', 'downScroll') == true then
>           setProperty('gradient.angle', 360);
>      end
> 
>      if getPropertyFromClass('ClientPrefs', 'downScroll') == false then
>           setProperty('sheercold.y', 470);
>           setProperty('freezewarning.y', 444);
>      end
> end
> 
> function onBeatHit()
>      if curBeat % 2 == 0 then
>           percent = percent + 5;
>           freezeval = percent * 2.61;
>      end
> 
>      if percent > 100 then
>           percent = 100;
>           local minushealth=0.0475;
>           local health=getProperty('healthBar.percent');
>           local minusfreezeval=0;
>           if getProperty('healthBar.percent') > 10 then
>                setProperty('health', health- 1.5);
>           end
>           elseif percent < 0 then
>           percent = 0;
>      end
> 
>      makeGraphic('totallyrealbar', freezeval, 10, 'dafafc');
>      setProperty('health', health - minushealth - minusfreezeval)
> end
> 
> function goodNoteHit(id, direction, noteType, isSustainNote)
>      if noteType == 'Warm Note' then
>           percent = percent - 10;
>           freezeval = percent * 2.5;
>      elseif noteType == 'Sheer Cold Note' then
>           percent = percent + 5;
>           freezeval = percent * 2.5;
>      end
> 
>      makeGraphic('totallyrealbar', freezeval, 10, 'dafafc');
>      setProperty('health', health - minushealth - minusfreezeval)
> end
> 
> function onUpdate(elapsed)
>      if percent <= 0 then
>           setProperty('gradient.alpha', 0.0);
>           setProperty('freezewarning.alpha', 0.0);
>           cameraShake('camera', 0, 999);
>           cameraShake('camHUD', 0, 999);
>      end
>      if percent == 10 then
>           setProperty('gradient.alpha', 0.1);
>           setProperty('freezewarning.alpha', 0.1);
>           cameraShake('camera', 0.001, 999);
>           cameraShake('camHUD', 0.001, 999);
>      end
>      if percent == 20 then
>           setProperty('gradient.alpha', 0.2);
>           setProperty('freezewarning.alpha', 0.2);
>           cameraShake('camera', 0.002, 999);
>           cameraShake('camHUD', 0.002, 999);
>      end
>      if percent == 30 then
>           setProperty('gradient.alpha', 0.3);
>           setProperty('freezewarning.alpha', 0.3);
>           cameraShake('camera', 0.003, 999);
>           cameraShake('camHUD', 0.003, 999);
>      end
>      if percent == 40 then
>           setProperty('gradient.alpha', 0.4);
>           setProperty('freezewarning.alpha', 0.4);
>           cameraShake('camera', 0.004, 999);
>           cameraShake('camHUD', 0.004, 999);
>      end
>      if percent == 50 then
>           setProperty('gradient.alpha', 0.5);
>           setProperty('freezewarning.alpha', 0.5);
>           cameraShake('camera', 0.005, 999);
>           cameraShake('camHUD', 0.005, 999);
>      end
>      if percent == 60 then
>           setProperty('gradient.alpha', 0.6);
>           setProperty('freezewarning.alpha', 0.6);
>           cameraShake('camera', 0.006, 999);
>           cameraShake('camHUD', 0.006, 999);
>      end
>      if percent == 70 then
>           setProperty('gradient.alpha', 0.7);
>           setProperty('freezewarning.alpha', 0.7);
>           cameraShake('camera', 0.007, 999);
>           cameraShake('camHUD', 0.007, 999);
>      end
>      if percent == 80 then
>           setProperty('gradient.alpha', 0.8);
>           setProperty('freezewarning.alpha', 0.8);
>           cameraShake('camera', 0.008, 999);
>           cameraShake('camHUD', 0.008, 999);
>      end
>      if percent == 90 then
>           setProperty('gradient.alpha', 0.9);
>           setProperty('freezewarning.alpha', 0.9);
>           cameraShake('camera', 0.009, 999);
>           cameraShake('camHUD', 0.009, 999);
>      end
>      if percent == 100 then
>           setProperty('gradient.alpha', 1.);
>           setProperty('freezewarning.alpha', 1);
>           cameraShake('camera', 0.01, 999);
>           cameraShake('camHUD', 0.01, 999);
>      end
> end
> ```
> 
> try this?

Your code did in fact fix the black graphic issue, however the bar that increases is now invisible. Is there any way to include that? Its sprite name is totallyrealbar in my original code.

**Comment by TBiscuit1** [comment]
When you make a color square, if the graphic is 0/negative in lenght, the game will NOT like it (and when I say not, I mean it).
Only solution is to add a small epsilon to the value so it never reach 0/negative (even condition sometime still causes the glitch, it is super sensible for some reason)

**Comment by gamenwatch412** [comment]
Ah I see that makes sense, so basically, I should set the percent limit to something like 0.01? But even when doing so, hitting the warm note causes the glitch still.

This is the code I have at the moment:

`freezeval=0.01;
percent=0.01;
shaking=false;

function onCreate()
     makeLuaSprite('sheercold', 'SheerColdBar', 640-(281/2), 142);
     makeLuaSprite('freezewarning', 'freezewarning', 465, 116);
     makeLuaSprite('totallyrealbar', nil, 503, 226);
     makeGraphic('totallyrealbar', freezeval, 10, 'dafafc');
     scaleObject('freezewarning', 1.1, 1.3);
     addLuaSprite('freezewarning');
     addLuaSprite('totallyrealbar', true);
     setBlendMode('freezewarning', darken);
     setObjectCamera('freezewarning', 'hud');
     setObjectCamera('sheercold', 'hud');
     setObjectCamera('totallyrealbar', 'hud');
     addLuaSprite('sheercold');

     makeLuaSprite('blackgradient', 'BlackGradient', -200, -250);
     setObjectCamera('blackgradient', 'other');
     setScrollFactor('blackgradient', 0, 0);
     scaleObject('blackgradient', 1.4, 1.4)
     setProperty('blackgradient.visible', false);
     addLuaSprite('blackgradient', true);

     makeLuaSprite('gradient', 'bluegradient', -70, -50);
     setObjectCamera('gradient', 'other');
     setScrollFactor('gradient', 0, 0);
     scaleObject('gradient', 1.15, 1.15);
     setProperty('gradient.angle', 180);
     addLuaSprite('gradient', true);

     if getPropertyFromClass('ClientPrefs', 'downScroll') == true then
          setProperty('gradient.angle', 360);
     end

     if getPropertyFromClass('ClientPrefs', 'downScroll') == false then
          setProperty('sheercold.y', 470);
          setProperty('freezewarning.y', 444);
     end
end

function onBeatHit()
     if curBeat % 2 == 0 then
          percent = percent + 5;
          freezeval = percent * 2.61;
     end

     if percent > 100 then
          percent = 100;
          local minushealth=0.0475;
          local health=getProperty('healthBar.percent');
          local minusfreezeval=0;
          if getProperty('healthBar.percent') > 10 then
               setProperty('health', health- 1.5);
          end
          elseif percent < 0.01 then
          percent = 0.01;
          freezeval = 0.01;
     end

     makeGraphic('totallyrealbar', freezeval, 10, 'dafafc');
     setProperty('health', health - minushealth - minusfreezeval)
end

function goodNoteHit(id, direction, noteType, isSustainNote)
     if noteType == 'Warm Note' then
          percent = percent - 2;
          freezeval = percent * 2.5;
     elseif noteType == 'Sheer Cold Note' then
          percent = percent + 5;
          freezeval = percent * 2.5;
     end

     makeGraphic('totallyrealbar', freezeval, 10, 'dafafc');
     setProperty('health', health - minushealth - minusfreezeval)
end

function onUpdate(elapsed)
     if percent <= 0.01 then
          setProperty('gradient.alpha', 0.0);
          setProperty('freezewarning.alpha', 0.0);
          cameraShake('camera', 0, 999);
          cameraShake('camHUD', 0, 999);
     end
     if percent == 10 then
          setProperty('gradient.alpha', 0.1);
          setProperty('freezewarning.alpha', 0.1);
          cameraShake('camera', 0.001, 999);
          cameraShake('camHUD', 0.001, 999);
     end
     if percent == 20 then
          setProperty('gradient.alpha', 0.2);
          setProperty('freezewarning.alpha', 0.2);
          cameraShake('camera', 0.002, 999);
          cameraShake('camHUD', 0.002, 999);
     end
     if percent == 30 then
          setProperty('gradient.alpha', 0.3);
          setProperty('freezewarning.alpha', 0.3);
          cameraShake('camera', 0.003, 999);
          cameraShake('camHUD', 0.003, 999);
     end
     if percent == 40 then
          setProperty('gradient.alpha', 0.4);
          setProperty('freezewarning.alpha', 0.4);
          cameraShake('camera', 0.004, 999);
          cameraShake('camHUD', 0.004, 999);
     end
     if percent == 50 then
          setProperty('gradient.alpha', 0.5);
          setProperty('freezewarning.alpha', 0.5);
          cameraShake('camera', 0.005, 999);
          cameraShake('camHUD', 0.005, 999);
     end
     if percent == 60 then
          setProperty('gradient.alpha', 0.6);
          setProperty('freezewarning.alpha', 0.6);
          cameraShake('camera', 0.006, 999);
          cameraShake('camHUD', 0.006, 999);
     end
     if percent == 70 then
          setProperty('gradient.alpha', 0.7);
          setProperty('freezewarning.alpha', 0.7);
          cameraShake('camera', 0.007, 999);
          cameraShake('camHUD', 0.007, 999);
     end
     if percent == 80 then
          setProperty('gradient.alpha', 0.8);
          setProperty('freezewarning.alpha', 0.8);
          cameraShake('camera', 0.008, 999);
          cameraShake('camHUD', 0.008, 999);
     end
     if percent == 90 then
          setProperty('gradient.alpha', 0.9);
          setProperty('freezewarning.alpha', 0.9);
          cameraShake('camera', 0.009, 999);
          cameraShake('camHUD', 0.009, 999);
     end
     if percent == 100 then
          setProperty('gradient.alpha', 1.);
          setProperty('freezewarning.alpha', 1);
          cameraShake('camera', 0.01, 999);
          cameraShake('camHUD', 0.01, 999);
     end
end`
