### ISSUE TITLE
disappear with a button a sprite

### ISSUE THREAD

**Issue by SENFULLHD4K** [ShadowMario/FNF-PsychEngine#10083]
### What is your question?

**what I want to say is that I have a mechanism that works that when pressing a button the sprite disappears and an animation is played at the same time and I don't know how the `KeyJustPressed` works, if someone explains it would help me a lot**

**also if you do not press the button a in time bf dies**
 

> I hope I explained myself well
please I would really appreciate it 😃

**Comment by tylerandari12** [comment]
This script will print the word HI every time your `up` keybind is pressed...
```lua
function onUpdate()
	if keyJustPressed("up") then
		debugPrint("HI")
	end
end
```
And this script will print the word HI every time `E` is pressed...
```lua
function onUpdate()
	if keyboardJustPressed("E") then
		debugPrint("HI")
	end
end
```

**Comment by SENFULLHD4K** [comment]
THANKS YOUUU 😀

**Comment by CrusherMods** [comment]
if you know now
then close the issue

**Comment by bruh1cat** [comment]
I made your script as an event if you need i
[mods.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/9275851/mods.zip)
t

**Comment by tylerandari12** [comment]
> THANKS YOUUU :grinning:

You're welcomes :D
