### ISSUE TITLE
Do one thing one after the other (Lua)

### ISSUE THREAD

**Issue by EvanOrSomething** [ShadowMario/FNF-PsychEngine#10089]
### Describe your problem here.

I want to rotate gf left, then rotate her right. But I'm not sure how to make the game wait for her to finish rotating in one direction before rotating in the other.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
`function onTweenCompleted(tag)`

**Comment by EvanOrSomething** [comment]
What would you put in the (tag)? Like the name of the tween?

**Comment by frantastic24** [comment]
`tag` is just a variable name, it returns the tag of a tween when it finishes

**Comment by EvanOrSomething** [comment]
It doesn't seem to be working, maybe it's because my first tween is under `function onStepHit()`

**Comment by EvanOrSomething** [comment]
Here's what the tweens look like
![image](https://user-images.githubusercontent.com/58342249/183271936-1bbd562c-fda3-4637-9b34-3a7b990182d8.png)

**Comment by frantastic24** [comment]
You are doing a tween every step and doing two tweens at once

**Comment by EvanOrSomething** [comment]
I know I am, but I don't know how to fix it

**Comment by frantastic24** [comment]
Make one tween and loop it with the function I mentioned

**Comment by EvanOrSomething** [comment]
How? (sorry, I'm not smart)

**Comment by frantastic24** [comment]
make one tween, under the new function you can check the current angle and do the other tween to create the loop

**Comment by EvanOrSomething** [comment]
How do you check the current angle?

**Comment by frantastic24** [comment]
`getProperty('object.angle')`

**Comment by EvanOrSomething** [comment]
so just like this?
![image](https://user-images.githubusercontent.com/58342249/183272574-10fcc046-bf89-4517-8b26-48341d431b9b.png)

**Comment by EvanOrSomething** [comment]
No, that doesn't work

**Comment by frantastic24** [comment]
you need at least one `if` and the function shouldn't be inside another one

**Comment by Itz-Miles** [comment]
I think you also need to put "gfRotateL" in `onTweenCompleted()`.

**Comment by EvanOrSomething** [comment]
So like? 
![image](https://user-images.githubusercontent.com/58342249/183272683-dca4c54a-3b71-428e-936a-01375db9d2c2.png)

**Comment by frantastic24** [comment]
it's getting there but you're not checking the angle value

**Comment by EvanOrSomething** [comment]
How do you do that? Like this? idk
![image](https://user-images.githubusercontent.com/58342249/183272754-2d30ef01-0064-4b24-bf34-f2d38df87fc3.png)

**Comment by Itz-Miles** [comment]
```
doTweenAngle("gfRotateL", "gf", -15, 0.14, "expoIn")
if getProperty("gf.angle") = `your desired angle` then
doTweenAngle("gfRotateL", "gf", 15, 0.14, "expoIn")
end
```
check to see if this works.

**Comment by EvanOrSomething** [comment]
does the desired angle go in quotations?

**Comment by Itz-Miles** [comment]
alternatively:
```
doTweenAngle("gfRotateL", "gf", -15, 0.14, "expoIn")
function onTweenCompleted("gfRotateL")
doTweenAngle("gfRotateR", "gf", 15, 0.14, "expoIn")
end
```

**Comment by frantastic24** [comment]
> Like this? idk

yeah that's correct, now you need to add the other tween below it using `else`

**Comment by EvanOrSomething** [comment]
She still won't rotate to the right

**Comment by EvanOrSomething** [comment]
Maybe it's because it's waiting for the 2 really long tweens I have to finish instead of the angle tween

**Comment by Itz-Miles** [comment]
If you were talking about the snippet I pasted, I forgot to change "gfRotateL" to "gfRotateR",

**Comment by EvanOrSomething** [comment]
which "gfRotateL"?

**Comment by EvanOrSomething** [comment]
Is there a way to maybe instead of making it wait for the tween to finish, just waiting like 50 steps and then playing the next one, and then waiting again

**Comment by EvanOrSomething** [comment]
If it's ok I'm just gonna work on this some other time, because this is making my brain hurt.

**Comment by Itz-Miles** [comment]
```
doTweenAngle("gfRotateL", "gf", -15, 0.14, "expoIn")
if getProperty("gf.angle") = `your desired angle` then
doTweenAngle("gfRotateL", "gf", 15, 0.14, "expoIn")
end

**Comment by EvanOrSomething** [comment]
Ended up fixing it on my own. I instead made 2 different scripts and put them in the same song, one for just them floating, and one for gf rotating
![image](https://user-images.githubusercontent.com/58342249/183313790-f1d32b0d-ce04-4f32-a623-edcf440b2801.png)
![image](https://user-images.githubusercontent.com/58342249/183313799-5bd5cd38-b812-49f7-a658-a3af3e303790.png)
