### ISSUE TITLE
I don't know how to code in fnf psych

### ISSUE THREAD

**Issue by duckyduck1q** [ShadowMario/FNF-PsychEngine#10080]
### Describe your problem here.

thats it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by wubbzyfan** [comment]
just… look it up on YouTube for fucks sake

**Comment by TheKitBoi** [comment]
> ### Describe your problem here.
> thats it

Then take coding lessons no brainer

**Comment by tylerandari12** [comment]
If you want to learn source code then the language they use is called `HScript`. I recommend taking courses for it somewhere online...

**Comment by Itz-Miles** [comment]
> If you want to learn source code then the language they use is called `HScript`. I recommend taking courses for it somewhere online...
The luascripting API uses hsScript, the game itself just uses haxe.

**Comment by Parsellol** [comment]
ok

**Comment by tylerandari12** [comment]
> > If you want to learn source code then the language they use is called `HScript`. I recommend taking courses for it somewhere online...
> 
> The luascripting API can use hsScript, the game itself just uses haxe.

oki
