### ISSUE TITLE
How to trigger game over screen for a custom character.

### ISSUE THREAD

**Issue by Owen-sys** [ShadowMario/FNF-PsychEngine#1008]
### Describe your problem here.

Even though I have the game over implemented in the game it  keeps using bf's default  game over for some reason. Am i supposed to code a specific thing or is this a bug of some sort?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

**Comment by Reycko** [comment]
[this](https://www.youtube.com/watch?v=dQw4w9WgXcQ) or using `setPropertyFromClass` may help.
Example script: (Click [here](https://cdn.discordapp.com/attachments/889357899015540736/901470021652447233/script.lua))

**Comment by Owen-sys** [comment]
tank you for your service
