### ISSUE TITLE
The game keeps crashing when I try to add character even in older builds

### ISSUE THREAD

**Issue by Popstarbird25** [ShadowMario/FNF-PsychEngine#10081]
### Describe your bug here.

whenever I use the character editor, the game would crash upon loading the spritesheet of my characters despite putting in the name correcty.

It would be nice if you guys can fix this bug, as this would be a great thing for me to help get my mod up and running again. :)

### Command Prompt/Terminal logs (if existing)
C:\HaxeToolkit\haxe\std/haxe/xml/Access.hx (line 44)
flixel/graphics/frames/FlxAtlasFrames.hx (line 260)
editors/CharacterEditorState.hx (line 840)
editors/CharacterEditorState.hx (line 520)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: SubTexture is missing attribute width
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

```


### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Not a bug
Your XML is missing attributes as the error says

**Comment by Popstarbird25** [comment]
can you please specify because I need to know the details.

**Comment by frantastic24** [comment]
We can't because you did not post the file

**Comment by Popstarbird25** [comment]
then who come you responded then? Not trying to be mean, I'm just saying

**Comment by frantastic24** [comment]
By reading the error

**Comment by Chidubemmo** [comment]
If you used adobe animated/flash to make the sprites select the animations's symbols, right click, click generate sprite sheet and selects sparrow v2 in data format, if you didn't use adobe animate/flash (why), use the [sprite sheet and xml generator](https://gamebanana.com/tools/7136) or use microsoft excel and similar
