### ISSUE TITLE
Default Camera Offsets for Characters replacing BF, GF, and Dad.

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#10094]
### What is your question?

Are there any variables or functions I can use to get the camera offset for any type character? (BF, GF, Dad)
If so, that would make me happy.

**Comment by fnfdemonboi314159** [comment]
Its defined by their json files btw

**Comment by Lorekeeper49** [comment]
`getProperty('character.camera.x)` or `getProperty('character.camera.y)` depending on the axis you want to use

**Comment by fnfdemonboi314159** [comment]
thanks
