### ISSUE TITLE
Interesting...

### ISSUE THREAD

**Issue by NewSajgonki** [ShadowMario/FNF-PsychEngine#10099]
### Describe your bug here.

Simply pressing 1 in value 1 causes the game to crash
![image](https://user-images.githubusercontent.com/108466805/183312037-dc48e966-6678-483a-a45f-fe902db1d228.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I just added 3 characters, and a song. nothing else. and i forgot to add the map but normally everything is fine

**Comment by EvanOrSomething** [comment]
I think this happens when you try to enter a value for an event that is not placed, you have to place the event in your chart before entering your values or it crashes. Still should get fixed though.
