### ISSUE TITLE
Screen Center thing

### ISSUE THREAD

**Issue by roaring213** [ShadowMario/FNF-PsychEngine#10096]
### What needs to be documented?

so i was scrolling through `FunkinLua.hx` and i found this function:
```lua
screenCenter(obj:String, pos:String = 'xy')
```
I think this would go in either General Functions, Custom Sprites Functions or Object Functions. I hope shadow mario notices this, because it would help me out a lot. this is where i found it starting at line 1804:
```hx
Lua_helper.add_callback(lua, "screenCenter", function(obj:String, pos:String = 'xy') {
	var spr:FlxSprite = PlayState.instance.getLuaObject(obj);

	if(spr==null){
		var killMe:Array<String> = obj.split('.');
		spr = getObjectDirectly(killMe[0]);
		if(killMe.length > 1) {
			spr = getVarInArray(getPropertyLoopThingWhatever(killMe), killMe[killMe.length-1]);
		}
	}
```
That's it. cya

**Comment by frantastic24** [comment]
https://api.haxeflixel.com/flixel/FlxObject.html#screenCenter
