### ISSUE TITLE
Is there a way to resize the arrows/notes?

### ISSUE THREAD

**Issue by ItsMeTyler25** [ShadowMario/FNF-PsychEngine#10090]
### Describe your problem here.

Hi! So um I've been wanting to resize the opponents notes to be much smaller then they are. 
I tried using the note tween like this: noteTweenX('opponentNoteTween', '4.scale', 0.3, 0.01, 'linear') but nothing seemed to work.

Just curious if its possible to do it like this? If so what am I doing wrong.  And if not is there any other way of changing the size of the notes/arrows?

Any help with this is appreciated! Thanks!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I have not, using LUA.

**Comment by frantastic24** [comment]
Use `setPropertyFromGroup()` instead of tweens if you're just going to set a property

**Comment by ItsMeTyler25** [comment]
> Use `setPropertyFromGroup()` instead of tweens if you're just going to set a property

I see, I've never used that before. What would I have to put?

**Comment by frantastic24** [comment]
```lua
setPropertyFromGroup(strums, id, 'scale.x', value)
```
`strums` can be `opponentStrums`, `playerStrums` or `strumLineNotes`
`id` is 0-3, or 0-7 for `strumLineNotes`
`scale.x` can also be `scale.y` or any other property 
`value` is scale, 1 is original size

**Comment by ItsMeTyler25** [comment]
> 
holy crap that worked! Thanks so much!

**Comment by SlushieDrawzCoolDrawingX480** [comment]
> ```lua
> setPropertyFromGroup(strums, id, 'scale.x', value)
> ```
> 
> `strums` can be `opponentStrums`, `playerStrums` or `strumLineNotes` `id` is 0-3, or 0-7 for `strumLineNotes` `scale.x` can also be `scale.y` or any other property `value` is scale, 1 is original size

is there a way to tween it?
