### ISSUE TITLE
How to make different notestyle for opponent

### ISSUE THREAD

**Issue by h4master** [ShadowMario/FNF-PsychEngine#10092]
### Describe your problem here.

I want to make different oponent notestyle, but idk how
Psych Engine version: 0.5.2h

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I make different opponent strums, but it doesn't work with notes.

**Comment by ManMaster707** [comment]
This can probably be done in an easier way but i cant be bothered so use this:

```lua
function onCreatePost()
	for i=0,3 do
            setPropertyFromGroup('opponentStrums',i,'texture', 'customNOTE_assets')
	end	

	for i=0, getProperty('unspawnNotes.length')-1 do
	    if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
		setPropertyFromGroup('unspawnNotes', i, 'texture', 'customNOTE_assets')
	end
    end
end

**Comment by Mastercopper2346** [comment]
OOOOHHHH MEE

**Comment by Mastercopper2346** [comment]
``lua
function onCreatePost()
	for i = 0, getProperty('unspawnNotes.length') do
		if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'BFNOTE_assets'); --Change texture
		end
	end
end
```
for the notes

**Comment by Gostar64** [comment]
> ```lua
> function onCreatePost()
> 	for i = 0, getProperty('unspawnNotes.length') do
> 		if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
> 			setPropertyFromGroup('unspawnNotes', i, 'texture', 'BFNOTE_assets'); --Change texture
> 		end
> 	end
> end
> ```
> 
> for the notes

I'm pretty sure they asked for source in the issue

**Comment by Mastercopper2346** [comment]
O yeah
