### ISSUE TITLE
Why does this not work

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#10101]
### Describe your problem here.

It works but when you hit a note it becomes normal again up until you aren't hitting notes

ok = 1

function onUpdate(elasped)
    if ok == 1 then
        if getProperty('health') == 2 then
        runTimer('alpha', 0.01, 1)
        else
        setProperty('healthBar.alpha', 1)

        setProperty('iconP1.alpha', 1)
        setProperty('iconP2.alpha', 1)

        setProperty('timeBarBG.visible', true);
        setProperty('timeBar.visible', true);
        setProperty('timeTxt.visible', true);

        setProperty('scoreTxt.visible', true)
        end
    end
end

function onTimerCompleted(tag, loops, loopsLeft)
    if tag == 'alpha' then
        setProperty('healthBar.alpha', 0.3)

        setProperty('iconP1.alpha', 0.3)
        setProperty('iconP2.alpha', 0.3)

        setProperty('timeBarBG.visible', false);
        setProperty('timeBar.visible', false);
        setProperty('timeTxt.visible', false);

        setProperty('scoreTxt.visible', false)
    end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by EvanOrSomething** [comment]
What is the code supposed to do

**Comment by bruh1cat** [comment]
Make the healthbar almost completely transparent when at full hp

**Comment by bruh1cat** [comment]
But when I hit a note it becomes non transparent and becomes transparent again after not hitting a note

**Comment by EvanOrSomething** [comment]
I'm gonna try fixing it, give me a few minutes

**Comment by EvanOrSomething** [comment]
Is this what it's supposed to look like?
https://user-images.githubusercontent.com/58342249/183315986-79850a12-9b87-4c9e-903d-5e45e19eb316.mp4

**Comment by bruh1cat** [comment]
> Is this what it's supposed to look like?
> 
> https://user-images.githubusercontent.com/58342249/183315986-79850a12-9b87-4c9e-903d-5e45e19eb316.mp4
> 
> 
> 
> 

Yes also sorry for not responding I was having trouble with my system

**Comment by EvanOrSomething** [comment]
Ok here's the code
`ok = 1

function onUpdate(elasped)
if ok == 1 then
if getProperty('health') == 2 then
    setProperty('healthBar.alpha', 0.3)

    setProperty('iconP1.alpha', 0.3)
    setProperty('iconP2.alpha', 0.3)

    setProperty('timeBarBG.visible', true);
    setProperty('timeBar.visible', true);
    setProperty('timeTxt.visible', true);

    setProperty('scoreTxt.visible', true)
elseif getProperty('health') <= 2 then
    setProperty('healthBar.alpha', 1)

    setProperty('iconP1.alpha', 1)
    setProperty('iconP2.alpha', 1)

    setProperty('timeBarBG.visible', true);
    setProperty('timeBar.visible', true);
    setProperty('timeTxt.visible', true);

    setProperty('scoreTxt.visible', true)
    end
end
end`

**Comment by bruh1cat** [comment]
What does <= and >= do?

**Comment by EvanOrSomething** [comment]
<= means less than and >= means more than
