### ISSUE TITLE
source/FunkinLua.hx:342: lines 342-346 : Int should be Bool source/FunkinLua.hx:342: lines 342-346 : ... For function argument 'f'

### ISSUE THREAD

**Issue by Zarmvation** [ShadowMario/FNF-PsychEngine#10103]
### Describe your problem here.

so i just got a new pc and my old pc had all my progress in it and i dont know how to move them to my new pc, so i decided to compile psych engine again and just restart then as i did lime test windows it came up with

source/FunkinLua.hx:342: lines 342-346 : Int should be Bool
source/FunkinLua.hx:342: lines 342-346 : ... For function argument 'f'

someone please help me i tried finding solutions but none of them seem to work. 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
get the changed version

**Comment by Zarmvation** [comment]
thanks man i appreciate it i got it working now
