### ISSUE TITLE
What is going on in the chart editor?!

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#10105]
### Describe your bug here.

So, before I start, this is not involving within the source code, like, "haha you forgot a song file in [insert difficulty name here] mode hehe 🤓". No, what this is, is that when you have the song playing in the chart editor, and you use the mouse scroll to scroll through the chart, the instrumental stops, sure, but the vocals keep playing. What's going on here?!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by FujiwaraZachWatterson** [comment]
you have to make voice extended as instrumental,  aka same length vocal and instrumental song (if don't work, idk what i'm gonna do)

**Comment by Lorekeeper49** [comment]
> you have to make voice extended as instrumental,  aka same length vocal and instrumental song (if don't work, idk what i'm gonna do)

I believe that he's saying that the instrumental is stopping when he stops the song within the chart editor but not the vocals

**Comment by fnfdemonboi314159** [comment]
> > you have to make voice extended as instrumental,  aka same length vocal and instrumental song (if don't work, idk what i'm gonna do)
> 
> I believe that he's saying that the instrumental is stopping when he stops the song within the chart editor but not the vocals

Well, I scroll using the Mouse Wheel, which stops the Instrumental, but not the Vocals.
