### ISSUE TITLE
How can I invert the health bar in lua?

### ISSUE THREAD

**Issue by AssasinShadows** [ShadowMario/FNF-PsychEngine#10100]
### Describe your problem here.

I want to invert the health bar so that I am on the opponent's side and the opponent is on the bf's side.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by FlintIshe** [comment]
flipX ?

**Comment by Mastercopper2346** [comment]
`setProperty(‘healthBar.angle’, 180);` or
`setProperty(‘healthBar.flipX, true);`

**Comment by WolfyTail** [comment]
> `setProperty(‘healthBar.angle’, 180);` or `setProperty(‘healthBar.flipX, true);`

It just flips the colors, but not the icons.

**Comment by Mastercopper2346** [comment]
> > `setProperty(‘healthBar.angle’, 180);` or `setProperty(‘healthBar.flipX, true);`
> 
> It just flips the colors, but not the icons.

For icons:
```lua
setProperty(‘iconP1.flipX’, true);
setProperty(‘iconP2.flipX’, true);
setProperty(‘iconP1.x’, iconP2.x);
setProperty(‘iconP2.x’, iconP1.x);
```

**Comment by WolfyTail** [comment]
The icons are flipped, but they didn't move.
![16611048821264974606594351299192](https://user-images.githubusercontent.com/95707370/185804645-eae06aaf-0ba3-4926-a26f-aa1926964356.jpg)

**Comment by WolfyTail** [comment]
I already used both of them.

```
function onUpdate(elapsed)
           if songName == 'Tutorial' then
                      setProperty('healthBar.flipX', true);
                      setProperty(‘iconP1.flipX’, true);
                      setProperty(‘iconP2.flipX’, true);
                      setProperty(‘iconP1.x’, iconP2.x);
                      setProperty(‘iconP2.x’, iconP1.x);
           end
end
```
It doesn't work.

**Comment by Mastercopper2346** [comment]
```lua
function onCreatePost() -- not onUpdate
           if songName == 'Tutorial' then
                      setProperty('healthBar.flipX', true);
                      setProperty(‘iconP1.flipX’, true);
                      setProperty(‘iconP2.flipX’, true);
                      setProperty(‘iconP1.x’, iconP2.x);
                      setProperty(‘iconP2.x’, iconP1.x);
           end
end
```

**Comment by frantastic24** [comment]
here's one that actually works
```lua
function onCreatePost()
    setProperty('iconP1.flipX', 1)
    setProperty('iconP2.flipX', 1)
    setProperty('healthBar.flipX', 1)
end

function onUpdatePost()
    setProperty('iconP1.x', -593+getProperty('healthBar.x') + (getProperty('healthBar.width')*(remapToRange(getProperty('healthBar.percent'), 0, -100, 100, 0)*0.01))-(150 * getProperty('iconP1.scale.x'))/2 - 26*2)
    setProperty('iconP2.x', -593+getProperty('healthBar.x') + (getProperty('healthBar.width')*(remapToRange(getProperty('healthBar.percent'), 0, -100, 100, 0)*0.01))+(150 * getProperty('iconP2.scale.x')-150)/2 - 26)
end

function remapToRange(value, start1, stop1, start2, stop2)
    return start2 + (value - start1) * ((stop2 - start2) / (stop1 - start1))
end
```

**Comment by AssasinShadows** [comment]
> here's one that actually works
> 
> ```lua
> function onCreatePost()
>     setProperty('iconP1.flipX', 1)
>     setProperty('iconP2.flipX', 1)
>     setProperty('healthBar.flipX', 1)
> end
> 
> function onUpdatePost()
>     setProperty('iconP1.x', -593+getProperty('healthBar.x') + (getProperty('healthBar.width')*(remapToRange(getProperty('healthBar.percent'), 0, -100, 100, 0)*0.01))-(150 * getProperty('iconP1.scale.x'))/2 - 26*2)
>     setProperty('iconP2.x', -593+getProperty('healthBar.x') + (getProperty('healthBar.width')*(remapToRange(getProperty('healthBar.percent'), 0, -100, 100, 0)*0.01))+(150 * getProperty('iconP2.scale.x')-150)/2 - 26)
> end
> 
> function remapToRange(value, start1, stop1, start2, stop2)
>     return start2 + (value - start1) * ((stop2 - start2) / (stop1 - start1))
> end
> ```

thanks bro it worked, really thanks to all
