### ISSUE TITLE
Something is missing in song

### ISSUE THREAD

**Issue by matiunitynagithub** [ShadowMario/FNF-PsychEngine#10107]
### What needs to be documented?

I was testing my port of curse sonic's song and I got this error:
`Note.hx (line 124)
PlayState.hx (line 2353)
PlayState.hx (line 1053)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
`

I added missing song assets but something is still missing.

**Comment by CrusherMods** [comment]
This doesn't need to be documented.

**Comment by Mastercopper2346** [comment]
well, line 1053 is:
```haxe
generateSong(SONG.song);
```
and line 2353 is:
```haxe
swagNote.noteType = songNotes[3];
```

**Comment by Mastercopper2346** [comment]
so, i'm assuming that means you added a custom note skin, but it's null.

**Comment by matiunitynagithub** [comment]
I didn't

**Comment by matiunitynagithub** [comment]
No events and lua script about this. Even the chart code have: '"arrowSkin": ""'

**Comment by matiunitynagithub** [comment]
I checked the stage and there's no issues in code

**Comment by matiunitynagithub** [comment]
ok I guess
