### ISSUE TITLE
Translating a Lua Modchart file from Kade to Psych

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#10106]
### Describe your problem here.

I am in the process of porting VS Ron 2.5 (Week 1 and Trojan Virus) into Psych Engine. There is this lua file I am struggling with to convert from Kade Engine (the og engine in which Ron 2.5 runs on) to Psych. is there a way to translate it?

Here's the script btw:
```
local moveing = false

function update (elapsed)
    local currentBeat = (songPos / 1000)*(bpm/60)
    if moveing then
        for i=0,7 do
            setActorX(_G['defaultStrum'..i..'X'] + 32 * math.sin((currentBeat + i*0.25) * math.pi), i)
        end
    else
		for i=0,7 do
			setActorX(_G['defaultStrum'..i..'X'] + 16 * math.sin((currentBeat/4 + i*0.25) * math.pi), i)
		end
	end
end

function stepHit(step)
	if curStep == 384 then
		moveing = true
	end
    if curStep == 640 then
		moveing = false
    end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Mastercopper2346** [comment]
```
local moving = false;

function update (elapsed)
    local currentBeat = (songPos / 1000)*(bpm/60)
    if moving then
        for i=0,7 do
            setActorX(_G['defaultStrum'..i..'X'] + 32 * math.sin((currentBeat + i*0.25) * math.pi), i);
        end
    else
		for i=0,7 do
			setActorX(_G['defaultStrum'..i..'X'] + 16 * math.sin((currentBeat/4 + i*0.25) * math.pi), i);
		end
	end
end

function stepHit(step)
	if step == 384 then
		moving = true;
	end
    if step == 640 then
		moving = false;
    end
end
```lua

**Comment by MemeHoovy** [comment]
> ```lua
> local moving = false;
> 
> function update (elapsed)
>     local currentBeat = (songPos / 1000)*(bpm/60)
>     if moving then
>         for i=0,7 do
>             setActorX(_G['defaultStrum'..i..'X'] + 32 * math.sin((currentBeat + i*0.25) * math.pi), i);
>         end
>     else
> 		for i=0,7 do
> 			setActorX(_G['defaultStrum'..i..'X'] + 16 * math.sin((currentBeat/4 + i*0.25) * math.pi), i);
> 		end
> 	end
> end
> 
> function stepHit(step)
> 	if step == 384 then
> 		moving = true;
> 	end
>     if step == 640 then
> 		moving = false;
>     end
> end
> ```

this doesn't work as "SetActorX" isn't a thing in Psych Engine.
what you can do is replace the first SetActorX line with this,
``` 
setPropertyFromGroup('strumLineNotes', i, 'x', defaultNotePos[i + 1][1] + 32 * math.sin((currentBeat + i*0.25) * math.pi))
```
And then the second line with this
```
setPropertyFromGroup('strumLineNotes', i, 'x', defaultNotePos[i + 1][1] + 16 * math.sin((currentBeat + i*0.25) * math.pi))
```

**Comment by CrusherMods** [comment]
> ```lua
> 
> local moving = false;
> 
> 
> 
> function update (elapsed)
> 
>     local currentBeat = (songPos / 1000)*(bpm/60)
> 
>     if moving then
> 
>         for i=0,7 do
> 
>             setActorX(_G['defaultStrum'..i..'X'] + 32 * math.sin((currentBeat + i*0.25) * math.pi), i);
> 
>         end
> 
>     else
> 
> 		for i=0,7 do
> 
> 			setActorX(_G['defaultStrum'..i..'X'] + 16 * math.sin((currentBeat/4 + i*0.25) * math.pi), i);
> 
> 		end
> 
> 	end
> 
> end
> 
> 
> 
> function stepHit(step)
> 
> 	if step == 384 then
> 
> 		moving = true;
> 
> 	end
> 
>     if step == 640 then
> 
> 		moving = false;
> 
>     end
> 
> end
> ```

bruh thats just the code they posted 💀

**Comment by CrusherMods** [comment]
> > ```lua
> 
> > local moving = false;
> 
> > 
> 
> > function update (elapsed)
> 
> >     local currentBeat = (songPos / 1000)*(bpm/60)
> 
> >     if moving then
> 
> >         for i=0,7 do
> 
> >             setActorX(_G['defaultStrum'..i..'X'] + 32 * math.sin((currentBeat + i*0.25) * math.pi), i);
> 
> >         end
> 
> >     else
> 
> > 		for i=0,7 do
> 
> > 			setActorX(_G['defaultStrum'..i..'X'] + 16 * math.sin((currentBeat/4 + i*0.25) * math.pi), i);
> 
> > 		end
> 
> > 	end
> 
> > end
> 
> > 
> 
> > function stepHit(step)
> 
> > 	if step == 384 then
> 
> > 		moving = true;
> 
> > 	end
> 
> >     if step == 640 then
> 
> > 		moving = false;
> 
> >     end
> 
> > end
> 
> > ```
> 
> 
> 
> this doesn't work as "SetActorX" isn't a thing in Psych Engine.
> 
> what you can do is replace the first SetActorX line with this,
> 
> ``` 
> 
> setPropertyFromGroup('strumLineNotes', i, 'x', defaultNotePos[i + 1][1] + 32 * math.sin((currentBeat + i*0.25) * math.pi))
> 
> ```
> 
> And then the second line with this
> 
> ```
> 
> setPropertyFromGroup('strumLineNotes', i, 'x', defaultNotePos[i + 1][1] + 16 * math.sin((currentBeat + i*0.25) * math.pi))
> 
> ```
> 
> And this is the result.
> 
> ```
> 
> local moving = false;
> 
> 
> 
> function update (elapsed)
> 
>     local currentBeat = (songPos / 1000)*(bpm/60)
> 
>     if moving then
> 
>         for i=0,7 do
> 
>             setPropertyFromGroup('strumLineNotes', i, 'x', defaultNotePos[i + 1][1] + 32 * math.sin((currentBeat + i*0.25) * math.pi))
> 
>         end
> 
>     else
> 
> 		for i=0,7 do
> 
> 			setPropertyFromGroup('strumLineNotes', i, 'x', defaultNotePos[i + 1][1] + 16 * math.sin((currentBeat + i*0.25) * math.pi))
> 
> 		end
> 
> 	end
> 
> end
> 
> 
> 
> function stepHit(step)
> 
> 	if step == 384 then
> 
> 		moving = true;
> 
> 	end
> 
>     if step == 640 then
> 
> 		moving = false;
> 
>     end
> 
> end
> 
> ```
> 
> 

oh and the update(elapsed) function should become onUpdate(elapsed)
and stepHit(step) should become onStepHit(step)

**Comment by fnfdemonboi314159** [comment]
> > ```lua
> > local moving = false;
> > 
> > function update (elapsed)
> >     local currentBeat = (songPos / 1000)*(bpm/60)
> >     if moving then
> >         for i=0,7 do
> >             setActorX(_G['defaultStrum'..i..'X'] + 32 * math.sin((currentBeat + i*0.25) * math.pi), i);
> >         end
> >     else
> > 		for i=0,7 do
> > 			setActorX(_G['defaultStrum'..i..'X'] + 16 * math.sin((currentBeat/4 + i*0.25) * math.pi), i);
> > 		end
> > 	end
> > end
> > 
> > function stepHit(step)
> > 	if step == 384 then
> > 		moving = true;
> > 	end
> >     if step == 640 then
> > 		moving = false;
> >     end
> > end
> > ```
> 
> this doesn't work as "SetActorX" isn't a thing in Psych Engine. what you can do is replace the first SetActorX line with this,
> 
> ```
> setPropertyFromGroup('strumLineNotes', i, 'x', defaultNotePos[i + 1][1] + 32 * math.sin((currentBeat + i*0.25) * math.pi))
> ```
> 
> And then the second line with this
> 
> ```
> setPropertyFromGroup('strumLineNotes', i, 'x', defaultNotePos[i + 1][1] + 16 * math.sin((currentBeat + i*0.25) * math.pi))
> ```
> 
> And this is the result.
> 
> ```
> local moving = false;
> 
> function update (elapsed)
>     local currentBeat = (songPos / 1000)*(bpm/60)
>     if moving then
>         for i=0,7 do
>             setPropertyFromGroup('strumLineNotes', i, 'x', defaultNotePos[i + 1][1] + 32 * math.sin((currentBeat + i*0.25) * math.pi))
>         end
>     else
> 		for i=0,7 do
> 			setPropertyFromGroup('strumLineNotes', i, 'x', defaultNotePos[i + 1][1] + 16 * math.sin((currentBeat + i*0.25) * math.pi))
> 		end
> 	end
> end
> 
> function stepHit(step)
> 	if step == 384 then
> 		moving = true;
> 	end
>     if step == 640 then
> 		moving = false;
>     end
> end
> ```

ik. I just want it translated over to psych.

**Comment by fnfdemonboi314159** [comment]
thanks folks!
