### ISSUE TITLE
How do you move something instantly (lua)

### ISSUE THREAD

**Issue by EvanOrSomething** [ShadowMario/FNF-PsychEngine#10102]
### Describe your problem here.

I know how to tween stuff to a position but I don't know how to move them instantly to a position, how do I do that?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
`setProperty()`

**Comment by FlintIshe** [comment]
```ruby
setProperty('thing.x', -900)
```
