### ISSUE TITLE
Rotated notes "Jump" when pressed

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#1011]
### Describe your bug here.

Rotated notes "Jump" when pressed
![image](https://user-images.githubusercontent.com/93293747/141642184-62851efb-a5b6-4f21-bd2c-984553791b57.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Everything I've done has been within the mods folder.

**Comment by perngjiafu** [comment]
its like that

just deal with it

**Comment by ItsCapp** [comment]
> its like that
> 
> just deal with it

Really? is there not a single solution? @ShadowMario

**Comment by perngjiafu** [comment]
yup

**Comment by ItsCapp** [comment]
> yup

sadge

**Comment by perngjiafu** [comment]
ok

**Comment by nintendofan44** [comment]
this got fixed basically yesterday lol

**Comment by ItsCapp** [comment]
> this got fixed basically yesterday lol

like, when the update comes out it'll work?

**Comment by ShadowMario** [comment]
Yeah, i couldn't find a math formula for this so fuck it.
