### ISSUE TITLE
How to use setTextColor?

### ISSUE THREAD

**Issue by SteveeWasTaken** [ShadowMario/FNF-PsychEngine#10115]
### Describe your problem here.

I'm trying to set a text's color to Green, but it isn't working. I tried with `setTextColor(atkText, 'Green')` and `setTextColor(atkText, '37eb13')` but none of these work. Why?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Tag should be a string

**Comment by FlintIshe** [comment]
may be put apostrophe

 at 'atkText' and the color without apostrophe 37eb13

**Comment by Gostar64** [comment]
do what frantastic24 said, and if that doesn't work (or gives you the wrong color), make sure to do
```Lua 
         setTextColor('example' ,  getColorFromHex('37eb13'))

**Comment by SteveeWasTaken** [comment]
> may be put apostrophe
> 
> at 'atkText' and the color without apostrophe 37eb13

it says "malformed number near '37eb13'"

**Comment by SteveeWasTaken** [comment]
> do what frantastic24 said, and if that doesn't work (or gives you the wrong color), make sure to do
> 
> ```lua
>          setTextColor('example' ,  getColorFromHex('37eb13'))
>   
> ```

this one worked, thank you!
