### ISSUE TITLE
How can I play a sound during the first dialogue of a dialogue ?

### ISSUE THREAD

**Issue by Galbio** [ShadowMario/FNF-PsychEngine#10114]
### Describe your problem here.

I'm porting Tabi and I need help for playing the dialogue during the first dialogue. Here is what the script looks like
![image](https://user-images.githubusercontent.com/101997612/183513958-7fc5cd30-9835-4923-97b5-3f83a9343619.png)
if count == 0 don't work.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by AltronMaxX** [comment]
You can play first sound with start of the first dialogue. Count in onNextDialogue function can't be 0.

**Comment by Lorekeeper49** [comment]
Use `playSound()` in the function that starts the dialogue
