### ISSUE TITLE
Map making

### ISSUE THREAD

**Issue by NewSajgonki** [ShadowMario/FNF-PsychEngine#10112]
### What is your question?

What if i make images for a map every single one of them 1260 x 1300 (or bigger/smaller) like floor on the bottom, roof on the top and the BG and i set the location of it all to 0.0 what will happend?

**Comment by frantastic24** [comment]
They will be aligned but you don't want images to be bigger than you need them to be

**Comment by Lorekeeper49** [comment]
All of Hotline 024's stages are done pretty much exactly how you described here so that should give you a pretty good idea of what'll happen
