### ISSUE TITLE
Am I using the score variable right?

### ISSUE THREAD

**Issue by elixioo** [ShadowMario/FNF-PsychEngine#10116]
### Describe your problem here.

Hi! Currently working on a feature that shows an image when the player reaches a certain score. Here's the code I have.

`function onCreate()
    if score == '10000' then
        makeLuaSprite('tenscore', 'tenthousand', 0, 0)
        setObjectCamera('tenscore', 'hud');
        addLuaSprite('tenscore', true);
    end
end`

It's located in mods/scripts, and the image is in mods/images.

Nothing happens when I reach score 10000. There's no errors. Am I using the score variable right?

(Building from source, but coding this feature in lua.)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
`onCreate()` is only called when loading the song, use another function

**Comment by elixioo** [comment]
> 

Any idea what function to use? I'm new to lua.

**Comment by elixioo** [comment]
> `onCreate()` is only called when loading the song, use another function

Just tried both onUpdate and onBeatHit. Didn't work.

**Comment by frantastic24** [comment]
Score shouldn't be a string

**Comment by elixioo** [comment]
> Score shouldn't be a string

Didn't work still.

**Comment by frantastic24** [comment]
Post the script and format it properly

**Comment by elixioo** [comment]
> Post the script and format it properly

```
function onBeatHit()
    if score == 10000 then
        makeLuaSprite('tenscore', 'tenthousand', 0, 0)
        setObjectCamera('tenscore', 'hud');
        addLuaSprite('tenscore', true);
    end
end
```

Hopefully this works.

**Comment by frantastic24** [comment]
Use >=

**Comment by elixioo** [comment]
> Use >=

That worked! Thanks!!
