### ISSUE TITLE
i cant do it

### ISSUE THREAD

**Issue by Monkevr23231** [ShadowMario/FNF-PsychEngine#10118]
### Describe your problem here.

How do i fix my xml?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

_No response
![Screenshot (2)](https://user-images.githubusercontent.com/96747478/183798179-fdd7325a-6bc2-4dbd-95f3-36781b57c305.png)
![Screenshot (11)](https://user-images.githubusercontent.com/96747478/183800038-99a0ce2a-2a6e-43b7-b8c2-0d41d39bb5c6.png)
![Screenshot (12)](https://user-images.githubusercontent.com/96747478/183800041-0e864726-cd74-44c2-9c17-3230a3ef59b0.png)
![Screenshot (13)](https://user-images.githubusercontent.com/96747478/183800042-48cedb95-56de-4447-b66c-0d2c8628a713.png)
![Screenshot (14)](https://user-images.githubusercontent.com/96747478/183800043-8ae281f6-3f83-4b87-b271-1407ebb5632e.png)
![Screenshot (15)](https://user-images.githubusercontent.com/96747478/183800046-8de547ee-3195-4ae2-9458-9eeff1989156.png)
![Screenshot (9)](https://user-images.githubusercontent.com/96747478/183800049-4e21092d-2bbc-48fc-8f90-269d2976cf1d.png)
![Screenshot (10)](https://user-images.githubusercontent.com/96747478/183800050-2ef64ede-b3f1-4e9a-8b15-5b79bf5be406.png)
_

**Comment by TheKitBoi** [comment]
send the file dum dum

**Comment by Ninjakaiden523** [comment]
We would need to know at least what is wrong with the XML
