### ISSUE TITLE
Camera tween cancelled by it zooming on the beat

### ISSUE THREAD

**Issue by naether** [ShadowMario/FNF-PsychEngine#10128]
### Describe your bug here.

i am making an event that lets you change the zoom level of any camera with a custom easing type
however when i use it, whenever the camera zooms to the beat it's interrupted or it goes back to the default zoom level
does anybody know how to fix this?
here is the event code

```
-- stolen code from https://stackoverflow.com/a/51985083 :trollface:

function str_split(str, sep)
    if sep == nil then
        sep = '%s'
    end 

    local res = {}
    local func = function(w)
        table.insert(res, w)
    end 

    string.gsub(str, '[^'..sep..']+', func)
    return res 
end

function onEvent(name, value1, value2)
	if name == 'Change Zoom Level' then
		doTweenZoom("funnyZoom"..str_split(value2,",")[1], str_split(value2,",")[1], str_split(value1,",")[2], str_split(value1,",")[1], str_split(value2,",")[2])
	end
end
```

i am sorry in advance if the answer is incredibly obvious

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Meme1079** [comment]
heres the code that fixes it

```lua
function Split(s, delimiter) -- i stole this 
     result = {};
     for match in (s..delimiter):gmatch("(.-)"..delimiter) do
         table.insert(result, match);
     end
     return result;
end
 
function onEvent(name, value1, value2)
     local Splits = Split(value1, ", ")
     if name == 'Change Zoom Level' then
          doTweenZoom("funnyZoom", Splits[1], Splits[2], Splits[3], Splits[4])
          setProperty('defaultCamZoom', Splits[2])
     end
end
```

```txt
Changes Zoom

Value 1: cam, value, duration, ease
```

**Comment by naether** [comment]
> heres the code that fixes it
> 
> ```lua
> function Split(s, delimiter) -- i stole this 
>      result = {};
>      for match in (s..delimiter):gmatch("(.-)"..delimiter) do
>          table.insert(result, match);
>      end
>      return result;
> end
>  
> function onEvent(name, value1, value2)
>      local Splits = Split(value1, ", ")
>      if name == 'Change Zoom Level' then
>           doTweenZoom("funnyZoom", Splits[1], Splits[2], Splits[3], Splits[4])
>           setProperty('defaultCamZoom', Splits[2])
>      end
> end
> ```
> 
> ```
> Changes Zoom
> 
> Value 1: cam, value, duration, ease
> ```

the problem with this solution is that if is use camHUD, then camGame eases to the camHUD value, and camHUD goes back to the normal zoom level

**Comment by Meme1079** [comment]
Sorry but it's not the script problem its the `doTweenZoom()` after the tween is complete it will return to normal. I don't know why it does this but i don't know how to stop this from happening.
