### ISSUE TITLE
I don't know how to make a watermark in source

### ISSUE THREAD

**Issue by duckyduck1q** [ShadowMario/FNF-PsychEngine#10124]
### Describe your problem here.

I did it with lua script but I want to port it to the source cod

https://user-images.githubusercontent.com/94813393/183674649-fa398081-87c2-4840-9cc2-26e2dc64e729.mp4

e

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ManMaster707** [comment]
#8176
