### ISSUE TITLE
Custom Stages won't work for me well

### ISSUE THREAD

**Issue by FwostyX3** [ShadowMario/FNF-PsychEngine#1012]
### Describe your problem here.

just look at dis

![image](https://user-images.githubusercontent.com/87388604/141651805-c5f63fcb-8db8-49a3-81d7-b66fc106c2dd.png)

![image](https://user-images.githubusercontent.com/87388604/141651680-a089e3d6-24ca-47d3-9a23-d96b569d0bb3.png)

can anyone help?

yes i made a setting for no backgrounds it works with other stages..

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I have a NoBG option

**Comment by perngjiafu** [comment]
try

**function onCreate()
    makeLuaSprite('room', 'room', -600, -300);
    setScrollFactor('room', 0.9, 0.9);
    addLuaSprite('room', false);
end**

idk what is NoBG for tbh. the code above just adds the room

**Comment by FwostyX3** [comment]
> try
> 
> **function onCreate() makeLuaSprite('room', 'room', -600, -300); setScrollFactor('room', 0.9, 0.9); addLuaSprite('room', false); end**
> 
> idk what is NoBG for tbh. the code above just adds the room

dosnt work . - . ?????????
![image](https://user-images.githubusercontent.com/87388604/141656608-a4890714-9382-4596-9f6a-3d56f70b85d7.png)
![image](https://user-images.githubusercontent.com/87388604/141656613-0383b08b-84b3-4b40-af4e-1af4ba03c77f.png)
![image](https://user-images.githubusercontent.com/87388604/141656638-b8c62124-8e7b-403d-80b6-b79a1968e860.png)

**Comment by perngjiafu** [comment]
i need to see the files in order to see if your location of files are correct

**Comment by FwostyX3** [comment]
noBG is a option i made that removes the BG and never loads it for preformance

**Comment by FwostyX3** [comment]
the locations match up like other files

**Comment by perngjiafu** [comment]
so why did you put room in nobg for?

**Comment by perngjiafu** [comment]
cause usually it looks like this

![image](https://user-images.githubusercontent.com/54176781/141656785-e2d476aa-cb61-4aae-9246-dfc1aad2c472.png)

**Comment by FwostyX3** [comment]
i put room in if not noBG cause that means it will only load if noBG is off so that means that there will be "No BG"

**Comment by FwostyX3** [comment]
i just put the room file in the mods folder

**Comment by perngjiafu** [comment]
so its like lowquality?

**Comment by FwostyX3** [comment]
yes and it works when i put it in normal stage

**Comment by perngjiafu** [comment]
its just like putting room inside not lowquality

**Comment by FwostyX3** [comment]
yes

**Comment by perngjiafu** [comment]
lemme think

**Comment by perngjiafu** [comment]
idk but your suppose to add the “addLuaSprite” in the noBG too

**Comment by perngjiafu** [comment]
it maybe try restarting the whole game and loading it by cmd

**Comment by perngjiafu** [comment]
if none of them works then idk anymore. my brain smol

**Comment by FwostyX3** [comment]
![image](https://user-images.githubusercontent.com/87388604/141657359-28acced7-499d-4f5c-b495-aaeda8d3af64.png)
i removed the other functions a while ago it still dosnt work at all

**Comment by perngjiafu** [comment]
i dont think you need the close but if that also doesnt works then i cant help anymore. brains overheating man

**Comment by FwostyX3** [comment]
oofies :(

**Comment by perngjiafu** [comment]
lol

**Comment by perngjiafu** [comment]
gl with your code! eventually, it will work

**Comment by titopops** [comment]
the making of the lua sprite should be
makeLuaSprite('room','folder name here!!/room', -600,-300) if its in a folder, if that helps

**Comment by ShadowMario** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/44785097/141667189-61bb7b3b-984e-4ac7-a5bf-8276ef6df550.png)
Missing texture

**Comment by FwostyX3** [comment]
nothing works -3-

**Comment by MayoALT** [comment]
if its working now then you can close the issue
