### ISSUE TITLE
character change

### ISSUE THREAD

**Issue by joxu13v** [ShadowMario/FNF-PsychEngine#10133]
### Describe your problem here.

I'm looking for a way to make a change character based on the misses of a song

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by EyeDaleHim** [comment]
Look for scripts in the Psych Engine Discord Server

**Comment by CrusherNotDrip** [comment]
you can use
```lua
if misses == whatever then
    --code goes here
end
```

**Comment by joxu13v** [comment]
This doesn't work, what am I doing wrong?```
function onUpdate()
    if misses == 10 then
    triggerEvent('Change Character','Bf', 'tom')
end
```

**Comment by Meme1079** [comment]
try this
```lua
function onUpdate(elapsed)
     if misses == 10 then
          triggerEvent('Change Character', 'bf', 'tom')
     end
end
```

**Comment by joxu13v** [comment]
Thanks

**Comment by FlintIshe** [comment]
close this if any of the above work
