### ISSUE TITLE
Null Object Reference upon starting song

### ISSUE THREAD

**Issue by NotAhmedEpic** [ShadowMario/FNF-PsychEngine#10137]
### Describe your bug here.

So I have added a new combo counter (following the tutorial from GameBanana), but after that I've had lots of trouble with compiling the game. Now whenever I try to enter a song it gives me a Null Object Reference error saying that something is.. It's not even possibly understandable what does it say.

Error:
![L](https://user-images.githubusercontent.com/97828056/183950997-a61f7cdb-4669-4995-9f36-37304f1261b9.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited PlayState.hx and tried to change the combo counter

**Comment by frantastic24** [comment]
Not a bug since you edited the game, check line 1212

**Comment by NotAhmedEpic** [comment]
> Not a bug since you edited the game, check line 1212

Oh, sorry about that. But at line 1212 theres nothing. naeRating is my variable I put for a custom combo counter
![h](https://user-images.githubusercontent.com/97828056/183957868-33dbc4b3-fd7f-4886-bb88-ef59f99a7a12.png)

**Comment by frantastic24** [comment]
Seems like the object doesn't exist

**Comment by Ninjakaiden523** [comment]
Check to make sure all the assets used in the song exist, (Character's .PNGs, background assets, son on) this happens in both source and lua. As well as check the .JSON of the characters in the song to make sure you didn't misspell anything.
