### ISSUE TITLE
I don't know how to make a watermark in source

### ISSUE THREAD

**Issue by duckyduck1q** [ShadowMario/FNF-PsychEngine#10130]
### Describe your problem here.

I did it with lua script but I want to port it to the source code

https://user-images.githubusercontent.com/94813393/183765997-c716329e-0051-4e67-a0f0-744071dcef21.mp4

in playstate I put
var watermark:FlxText = new FlxText(2, 695, 0, "(your watermark)", 18);
add(watermark);

i compile the game but powershell had an error

source/PlayState.hx:277: characters 5-8 : Expected }

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
you already opened an issue and got an answer

**Comment by duckyduck1q** [comment]
i compile the game but powershell had an error

source/PlayState.hx:277: characters 5-8 : Expected }

**Comment by duckyduck1q** [comment]
i compile the game but powershell had an error

source/PlayState.hx:277: characters 5-8 : Expected }

**Comment by frantastic24** [comment]
You fucked up the code

**Comment by duckyduck1q** [comment]
what
be more specific

**Comment by frantastic24** [comment]
You need to be more specific, not me

**Comment by duckyduck1q** [comment]
What mean source/PlayState.hx:277: characters 5-8 : Expected }

**Comment by duckyduck1q** [comment]
help me

**Comment by duckyduck1q** [comment]
help me

**Comment by Mastercopper2346** [comment]
do it under `add(scoreTxt)`

**Comment by duckyduck1q** [comment]
thanks
