### ISSUE TITLE
HaxeFlixel keeps telling "Array[flixel.FlxCamera]" and something else

### ISSUE THREAD

**Issue by NotAhmedEpic** [ShadowMario/FNF-PsychEngine#10136]
### Describe your bug here.

So I have wanted a custom combo counter, so I used a tutorial on GameBanana. But after I have edited the game this error wouldnt stop coming up when trying to export the game. Self-explanatory 
![LOL](https://user-images.githubusercontent.com/97828056/183942707-cd36e675-36d2-4b65-ad44-b125ed635e1b.PNG)

### Command Prompt/Terminal logs (if existing)

```bash
D:\FNF-PsychEngine-0.6.2\FNF-PsychEngine-0.6.2>lime test windows
source/PlayState.hx:1212: characters 3-23 : Array<flixel.FlxCamera> should be flixel.text.FlxText
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited PlayState.hx and tried to change the combo counter

**Comment by CrusherNotDrip** [comment]
you didnt put `.cameras` at the end of `naeRating`.
