### ISSUE TITLE
Stuck on 0 FPS

### ISSUE THREAD

**Issue by VFtheboi** [ShadowMario/FNF-PsychEngine#10138]
### Describe your bug here.

When i open Psych engine, it's just a black screen and it's just on 0 fps
any way to fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by VFtheboi** [comment]
Someone please help me, this is stressing me out

**Comment by VFtheboi** [comment]
please help me, i just want to use psych engine again.

**Comment by TheKitBoi** [comment]
then goto C:\Users\ur name\AppData\Roaming\ShadowMario\PsychEngine\ninjamuffin99
and delete controls_v2.sol file

**Comment by VFtheboi** [comment]
nope, didnt work

**Comment by VFtheboi** [comment]
nevermind, i kinda tried ur thing and i just deleted the psych engine folder and reopened the exe
it works now i guess, thanks!
