### ISSUE TITLE
How to have an animated sprite play on screen through an event multiple times (read below for better explanation sorry!)

### ISSUE THREAD

**Issue by Troystar23** [ShadowMario/FNF-PsychEngine#10145]
### Describe your problem here.

I was able to create an event that basically plays an animated sprite on screen and tweens its alpha to fade away simple. What I did not realise was that when you try play the event right after you just played it, rather than playing it twice and keeping two on the screen it instead removes the first one to play for the second one meaning it is only possible to have one on the screen at a time (or at least the way I coded it which is most likely wrong) if anyone can help me out on how to make it so that when this event is played after one another that the animated sprite prior isnt cancelled out for the next one that would be great :) (essentially I want to be able to have multiple sprites using the same event if possible) 

![image](https://user-images.githubusercontent.com/97416596/184069458-644e0ebf-6888-433e-8d1d-6edcdca29c75.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
```lua
count = 0

function onEvent()
     count = count + 1
     makeAnimatedLuaSprite('huh'..count, image)
     --do the same ('huh'..count) with other lines
     --why was the tween here
     runTimer('huh'..count, tonumber(value2))
end

function onTimerCompleted(tag)
     if tag:find('^huh') then
          doTweenAlpha(tag, tag, 0, 1.2)
     end
end

function onTweenCompleted(tag)
     if tag:find('^huh') then
          removeLuaSprite(tag)
     end
end
```

**Comment by Troystar23** [comment]
count = 0

function onEvent()
     count = count + 1
     makeAnimatedLuaSprite('huh'..count, 'PowerUpText/huhText', 690,300)
	 addAnimationByPrefix('huh'..count, 'huhText', 'huhBounce', 24, false)
	 setObjectOrder('huh'..count, 18)
	 scaleObject('huh'..count, 1.7, 1.7)
	 objectPlayAnimation('huh'..count, 'huhText', false)	     
     runTimer('huh'..count, tonumber(value2))
end

function onTimerCompleted(tag)
     if tag:find('^huh') then
          doTweenAlpha(tag, tag, 0, 1.2)
     end
end

function onTweenCompleted(tag)
     if tag:find('^huh') then
          removeLuaSprite(tag)
     end
end


haha sorry I noticed as I looked back at the image thinking why did I put the tween there lol. So it works it produces multiple sprites now thank you so much for that, but the issue I'm having now is that rather than stopping after I place for example 4 events it repeats and loops over and over even tho there is no event telling it to play why is that?

**Comment by frantastic24** [comment]
It may be triggering with other events because you didn't add the name check, I left it out on the example I sent but it's necessary if you have other events

**Comment by Troystar23** [comment]
Thanks for helping me solve this 👍 🥇
