### ISSUE TITLE
lua call crash?

### ISSUE THREAD

**Issue by cyn0x8** [ShadowMario/FNF-PsychEngine#10143]
### Describe your bug here.

while working on a mod, ive found that having lua scripts (at least 1) running without an update function will eventually crash the game
the time it takes for this to happen lessens with higher fps (around 2 min at 240fps), so the prime suspect is onupdate and onupdatepost
im also thinking it could be related to callonluas in general, but i dont have a song nearly as long enough to test that outside of the update functions (2 min at 240fps is like 28800 calls)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no changes (latest commit)

**Comment by Ninjakaiden523** [comment]
try to not use onUpdate then, if that isn't a possibility then, I don't know.
