### ISSUE TITLE
Just a curious question (character skins)

### ISSUE THREAD

**Issue by YKoF-CALm** [ShadowMario/FNF-PsychEngine#10147]
### Describe your problem here.

Is it possible to toggle between different character skins with Lua, like, before a song starts?
I know this thing is mostly done with source, just curious to see if it can be done with Lua.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing.

**Comment by ZeitHeld** [comment]
https://gamebanana.com/mods/348526

The selectables mod is one way.
You can maybe use the code and modify it as you like

**Comment by YKoF-CALm** [comment]
> https://gamebanana.com/mods/348526
> 
> The selectables mod is one way. You can maybe use the code and modify it as you like

Yo, this one worked like a charm. Thanks for showing it to me.
