### ISSUE TITLE
Pause Screen With Lua

### ISSUE THREAD

**Issue by PedroNinjaM** [ShadowMario/FNF-PsychEngine#10142]
### What is your question?

someone knows how to make **a pause screen in lua for psych engine 0.62?**
![image](https://user-images.githubusercontent.com/97981969/184043580-6413afe1-1e2e-4a50-b518-099c9fb6b6b5.png)
like this

**Comment by FlintIshe** [comment]
you failed the test + lua won't work on menus

**Comment by Ninjakaiden523** [comment]
I think final escape has one

**Comment by ManMaster707** [comment]
You can download the script in [this video](https://www.youtube.com/watch?v=AgS4gzhIjBs) (make sure to give credit!) and then change whatever you like.

**Comment by PedroNinjaM** [comment]
Ok, thanks bro
