### ISSUE TITLE
dodgeable attack

### ISSUE THREAD

**Issue by dtgaming5737** [ShadowMario/FNF-PsychEngine#10148]
### What is your question?

im making a mod where i want to have bf dodge the opponents attack by hitting a dodge note but idk how to do that can someone plz help me

**Comment by Ninjakaiden523** [comment]
I've done it before, although I'm not at my windows right now, so I can't give you the code, but try looking it up, something like "Caution notes psych engine lua" may help

**Comment by WilliamGaming12** [comment]
> ### What is your question?
> im making a mod where i want to have bf dodge the opponents attack by hitting a dodge note but idk how to do that can someone plz help me
[dodge event.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/9311252/dodge.event.zip)
here ya go, now go make your amazing mod

**Comment by dtgaming5737** [comment]
thx so much

**Comment by TheKitBoi** [comment]
Close this

**Comment by dtgaming5737** [comment]
wait what do you do with the zip

**Comment by TheKitBoi** [comment]
Extract it and put it into custom_events folder

**Comment by dtgaming5737** [comment]
i already have dodge notes downloaded i just want the opponent to do a animation so bf can dodge and if he miss he dies

**Comment by dtgaming5737** [comment]
sorta like in vs Accelerant Hank
