### ISSUE TITLE
Unlocking Difficulties

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#10140]
### What feature do you want to get added on the **base** engine?

Being able to Unlock Difficulties upon beatin one before would be pretty neat.
I can imagine pretty well for the Upcoming ERECT Difficulty.
That one would have to beat the whole Week on HARD, before being able to play the same songs on ERECT.

And for some mods it may also be a pretty nice opportunity for more creativity. E.g: Being able to play A cover of that same song/week

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
Hmm, I’ll make a pr.

**Comment by ShadowMario** [comment]
No.
