### ISSUE TITLE
Please fix this crash.

### ISSUE THREAD

**Issue by FridayNight123** [ShadowMario/FNF-PsychEngine#10149]
### Describe your bug here.

This is pretty weird. When I go to freeplay or chart editor and enter a song, it will show me this: 

StrumNote.hx (line 139)
flixel/group/FlxGroup.hx (line 175)
flixel/group/FlxGroup.hx (line 175)
flixel/addons/ui/FlxUIState.hx (line 212)
MusicBeatState.hx (line 66)
PlayState.hx (line 2878)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

Please fix this.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't.

**Comment by MateuzinhoX02** [comment]
Probably some file is missing from your build.

**Comment by TheKitBoi** [comment]
The Note Skin is missing
