### ISSUE TITLE
Discord RPC

### ISSUE THREAD

**Issue by SuperSonicAl64** [ShadowMario/FNF-PsychEngine#10153]
### Describe your bug here.

I tried to use a method that works with 0.5.2h that lets Discord show a picture of the song's art just like in Vs. Afton. The prompts I did are here. I also put SONG.song.toLowerCase, for example
DiscordClient.changePresence(detailsText, SONG.song + " (" + storyDifficultyText + ")", iconP2.getCharacter(),  #SONG.song.toLowerCase());
![Capture](https://user-images.githubusercontent.com/83192392/184182562-9297f1bd-b9ba-4507-a5ea-122b9f5af388.PNG)
:

### Command Prompt/Terminal logs (if existing)

```bash
Original:
		DiscordRpc.presence({
			details: details,
			state: state,
			largeImageKey: 'icon',
			largeImageText: "Engine Version: " + MainMenuState.psychEngineVersion,
			smallImageKey : smallImageKey,
			// Obtained times are in milliseconds so they are divided so Discord can use it
			startTimestamp : Std.int(startTimestamp / 1000),
            endTimestamp : Std.int(endTimestamp / 1000)

New:

		DiscordRpc.presence({
			details: details,
			state: state,
			largeImageKey: largeImage,
			largeImageText: "Engine Version: " + MainMenuState.psychEngineVersion,
			smallImageKey : smallImageKey,
			// Obtained times are in milliseconds so they are divided so Discord can use it
			startTimestamp : Std.int(startTimestamp / 1000),
            endTimestamp : Std.int(endTimestamp / 1000)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Command Prompts are there

**Comment by frantastic24** [comment]
Not a bug, you didn't declare `largeImage`

**Comment by SuperSonicAl64** [comment]
What do you mean declare it? I’m confused.

**Comment by frantastic24** [comment]
The variable doesn't exist

**Comment by SuperSonicAl64** [comment]
I’ll try and find out how to fix it, if not. Then I’ll ask you. But thank you!

**Comment by frantastic24** [comment]
it should be as simple has
```haxe
var largeImage:String = '';
```

**Comment by SuperSonicAl64** [comment]
![MinaciousSonicBoutToGetPunchedByKnuckles](https://user-images.githubusercontent.com/83192392/184209123-a4038feb-e8f2-48b7-bd63-695384281ae7.png)
I'm a fucking dumbass.
I forgot one line of fucking code!:
public static function changePresence(details:String, state:Null<String>, ?smallImageKey : String, ?hasStartTimestamp : Bool, ?endTimestamp: Float, largeImage:String = 'icon')

**Comment by frantastic24** [comment]
It do be like that
Well if it's fixed, this can be closed

**Comment by SuperSonicAl64** [comment]
Thank you for your help!
Thank you!

**Comment by frantastic24** [comment]
You didn't close the issue

**Comment by SuperSonicAl64** [comment]
Oh sorry, heh heh
