### ISSUE TITLE
does the game build in 64 bit or 32 bit

### ISSUE THREAD

**Issue by AD1340** [ShadowMario/FNF-PsychEngine#1015]
### Describe your problem here.

plz help idk if the game builds in 64 bit or 32 bit

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

**Comment by FuseIsHere813** [comment]
It can be built on both x64 and x32, the problem is on x32, some things are only x64 useable which can't be used on 32 bit systems.

**Comment by ShadowMario** [comment]
Yes, but x32 isn't capable of loading videos.
