### ISSUE TITLE
Loading screens

### ISSUE THREAD

**Issue by Hazardows** [ShadowMario/FNF-PsychEngine#10155]
### Describe your problem here.

I am creating a mod and I would like to add loading screens to the game as was done in the "vs FNAF 1" mod

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i added a few stages, some characters and 7 songs

**Comment by Chidubemmo** [comment]
#1912

**Comment by KookerFoxYT** [comment]
sorry for being late but just go into the source code's Project.xml and enable ``NO_PRELOAD_ALL`` to desktop (plus remove ``PRELOAD_ALL``)
would probably work, although the songs may not start even when the load bar finished
also desktop builds don't need it anyway, even if some engines utilize it

besides its mainly a duplicate of #1912
