### ISSUE TITLE
game crash when any song played(even non-fanmade songs)

### ISSUE THREAD

**Issue by Mario-Drawer** [ShadowMario/FNF-PsychEngine#10151]
### Describe your bug here.

Anytime I play song in my fnf mod my game crashes and says this
---------------------------------------------------------------------------
Paths.hx (line 352)
NoteSplash.hx (line 51)
NoteSplash.hx (line 19)
PlayState.hx (line 1045)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
------------------------------------------------------
I checked the code and it seems fine so I was wondering if you can tell me the problem?
Thanks

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I put everything in the mods folder

**Comment by frantastic24** [comment]
Not a bug
Note splash texture is missing
