### ISSUE TITLE
"Test Play" Characters

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#10156]
### What feature do you want to get added on the **base** engine?

I got the idea to maybe add a button, or to like press "Enter" when being in the Character Editor. That way you can see, how it looks in-game (useful for custom stages, etc)

Usually, the new Character will then be put in Dad's place, except if it's a "Playable Character". Then it will be put in BF's place, before the song starts

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
You can already do that, press 8 in a song

**Comment by ZeitHeld** [comment]
No. It doesn't put the character in a song.
For example, if I opened Dadbattle or Test and then changed the Mom offsets, I'd then need to save it first, and then change it in the chart editor again.

**Comment by frantastic24** [comment]
So make a chart that has your character? If you're making a mod you kinda need that so how is that a problem

**Comment by ZeitHeld** [comment]
But if like you'd have to do a bunch of characters at once-

**Comment by TheKitBoi** [comment]
> But if like you'd have to do a bunch of characters at once-

Good luck when memory stores up
