### ISSUE TITLE
alt animation

### ISSUE THREAD

**Issue by dtgaming5737** [ShadowMario/FNF-PsychEngine#10168]
### What is your question?

how do i add alt animation to spritesheet

**Comment by Mastercopper2346** [comment]
Draw it

**Comment by TheKitBoi** [comment]
> ### What is your question?
> how do i add alt animation to spritesheet

then use https://github.com/UncertainProd/FnF-Spritesheet-and-XML-Maker/releases/tag/v4.2.5

**Comment by dtgaming5737** [comment]
where on the sheet do you draw it

**Comment by frantastic24** [comment]
This isn't psych engine related
