### ISSUE TITLE
how to make it so when you unlock an achievement a song unlocks in freeplay

### ISSUE THREAD

**Issue by ivorivorhepl** [ShadowMario/FNF-PsychEngine#10160]
### Describe your problem here.

pretend if you unlock the achievement "debugger", the song "Test" will appear in freeplay. how do i do that lol

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

messed with playstate but it did not break anything at all

**Comment by Mastercopper2346** [comment]
Yey source boi

**Comment by ivorivorhepl** [comment]
what

**Comment by ivorivorhepl** [comment]
nvm i figured it out with save data lmfao
