### ISSUE TITLE
changing the files

### ISSUE THREAD

**Issue by DaUi21real** [ShadowMario/FNF-PsychEngine#10164]
### What feature do you want to get added on the **base** engine?

change the assets folder to be the same as the mods folder, I got it to work by removing all the sprites except bf and gf and every week except the tutorial

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by TheKitBoi** [comment]
That would ruin other mods that are from an old version
Also

Y̸̥͙͓͖̬͚̅ͅO̶̪̺̞̊͒͌̃͊̄U̵͖̪̗͈͍̫̤̲̔̏͒͗̍͋̎͜ ̸͖̃F̶͔̝̟̣̩̜̔͋̽́̕A̵̡̢͚͚̗̲̓́̈́̌̂̑̆͋͗Į̷̛͉̪̳̻͈͒̃̋̇̾̽͒̍L̴̢̙̣̤̱̤̮̜̀͂̕Ȩ̸̪̗͒̈́̕͜͝Ḑ̶͕̯̠̠͖͖̣̓̋̿̀̍̑́̚͠ ̶̡̹̝͙͔̟̹̀̐͊͗͑̐͘͜T̵̨̨̼̮͙̰̪́̋̈͘H̸̨̠͚̄̅̍E̸̥̜̮̩̖̹͖̰͗̂͛͗̚ ̵̞̳̪͙̗̫̓̒͋Ţ̵̢̹͇̪̘̥̪̊̐͋͗͂̕Ę̸̭̭̻̱͆̈̌̈́͗́̈̚̚S̷̯̳̫̻̭̳̲̦͌͊͊͝Ṯ̴̼̥̦̭̝̙̪̹͂̎̾͝

**Comment by EyeDaleHim** [comment]
No.

**Comment by Mastercopper2346** [comment]
NO!

**Comment by CrusherNotDrip** [comment]
No + Failed test

**Comment by MemeHoovy** [comment]
Literally no.

**Comment by Meme1079** [comment]
No^∞

**Comment by ShadowMario** [comment]
This truly wasn't a good idea that you requested
