### ISSUE TITLE
I don't know how to make an option in source code

### ISSUE THREAD

**Issue by duckyduck1q** [ShadowMario/FNF-PsychEngine#10167]
### Describe your problem here.

I want to make an option in gameplay is icon bop
i am spanish and i'm using google translate

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Chidubemmo** [comment]
Go on optionstate.hx(source/options) and add under any case
```
                        case 'Optionname': 
                                 openSubState(new options.YourSubstateStatename());
```
You also have to create YourSubstateStatename.hx in the options folder.
You can now edit YourSubstateStatename.hx and add whatever you want.
I'm no expert in coding but I'm fairly sure that's how you do it.
