### ISSUE TITLE
What to put for directory in stage JSONs

### ISSUE THREAD

**Issue by PizzaSheriff** [ShadowMario/FNF-PsychEngine#10161]
### Describe your problem here.

I want a stage's assets in a folder but nothing i've tried has worked so far. I'm very confused and in need of help.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by NewSajgonki** [comment]
directiony is what the map is used to so if u set ur map directiony to a custom week, it will be in a custom week i think

**Comment by Duothehedgehog** [comment]
could you ellaborate but if you are talking about the directory its supposed to be in it is supposed to be in mods/images

**Comment by Ninjakaiden523** [comment]
Just put the assets in mods/images

**Comment by Lorekeeper49** [comment]
The directory does nothing in the mods folder for some reason

**Comment by CrusherNotDrip** [comment]
> The directory does nothing in the mods folder for some reason 

yeah because you dont need to put anything for directory in mods folder
if you look at limo stage it loads from the week4 folder in assets

**Comment by PizzaSheriff** [comment]
> could you ellaborate but if you are talking about the directory its supposed to be in it is supposed to be in mods/images

So I have all of my stage's assets just hanging around in the images folder, right? but There's so much junk in there that I want to have a folder with just the stage's assets in them. What would I need to put for directory in the stage's JSON file? is it even possible?

**Comment by frantastic24** [comment]
just make a folder in images

**Comment by fnfdemonboi314159** [comment]
Ik this is unrelated but #10197. I need help with this.
