### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by FlintIshe** [ShadowMario/FNF-PsychEngine#10169]
### Describe your problem here.

Basically what i am making is whenever you hit a note the image will scale a little

```ruby
cardScale = 0.1;

function onUpdate()
makeLuaSprite('card', 'cuphead/cardfull', 0,0 )
            setObjectCamera('card', 'hud')
           addLuaSprite('card', true)
           setProperty('card.scale.y', cardScale)
           setProperty('card.visible', true)

end

function goodNoteHit()
       plus = cardScale;
        cardScale = plus + 0.02;


end



function onGameOver()
     removeLuaSprite('card')

end
```

However the problem is whenever it GameOvers the image is still there and the onGameOver() doesn't even work

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Why is the sprite created every frame
Just do `onCreate()` then `scaleObject()` with every hit and you don't even need `onGameOver()`

**Comment by FlintIshe** [comment]
Can you show me an example?

**Comment by frantastic24** [comment]
Show the code

**Comment by FlintIshe** [comment]
Line 77 to 81 and line 292 to 295
[state.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/9330852/state.zip)

**Comment by frantastic24** [comment]
It's not scaling because there's nothing setting the scale

**Comment by FlintIshe** [comment]
Sorry for being stupid but wdym by nothing the scale ?
for example?

**Comment by FlintIshe** [comment]
> It's not scaling because there's nothing setting the scale

I just find a solution lmao btw thanks for your tips!
