### ISSUE TITLE
i got this error

### ISSUE THREAD

**Issue by Tamir-YT** [ShadowMario/FNF-PsychEngine#10162]
### Describe your bug here.

i got that error when i was loading a song

### Command Prompt/Terminal logs (if existing)

```bash
Paths.hx (line 352)
BGSprite.hx (line 24)
PlayState.hx (line 534)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Ninjakaiden523** [comment]
Check to make sure the assets of the song you were loading exist and aren't misspelled
