### ISSUE TITLE
Button combinations for images

### ISSUE THREAD

**Issue by Aden-Mystio** [ShadowMario/FNF-PsychEngine#10179]
### What is your question?

Is there a script for certain button combinations to access images, Like the Konami code I want to use it for my mod. Every time you put in the combination it's a different image. Could that possibly work?

**Comment by ZeitHeld** [comment]
I think it's source code only

But the general idea could be like, making a long if question and then asking
if keyJustPressed == KEY
if keyJustPressed == KEY2
etc..
and on the end, if ALL the if's are TRUE, then you will call a random number called img (for example)
then show image with id img

and then you could have like a table of images, lets say
if img == 1
image is image1
if img == 2
image is image2
if img == 3
image is image3

technically easy to pull off
