### ISSUE TITLE
Mid/End-song crash

### ISSUE THREAD

**Issue by FinGonz** [ShadowMario/FNF-PsychEngine#10173]
### Describe your bug here.

So in one of the songs in my mod, the game crashes around the halfway mark (1:00-2:30, the song is just over 3 minutes long).
The game shows no crash logs, not even a "null object reference". Just nothing, it lags the game then it crashes with no explanation. My FPS is 240, only have one script in my scripts folder (intro text like song name) but a ton of changes using source. I have no idea where the code goes wrong, since there are zero crash logs. On an older version of the mod, (0.5.2h) it doesn't crash.
If you have experienced this crash, and somehow fixed it, please help.

Video: https://cdn.discordapp.com/attachments/895899962943082509/1007994389416640562/guhhh.mp4

### Command Prompt/Terminal logs (if existing)

```bash
Doesn't even show anything, I've tried using -debug but there isn't anything there either.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

There were too much changes for me to put in this, even summarized. But the important ones are: More options, HUD change (tested), New Main Menu, Better Freeplay Menu and More achievements.

**Comment by FinGonz** [comment]
More info: I've also noticed that this happens only on songs longer than 3 minutes.

**Comment by Danya20072019** [comment]
try to change fps to 60, I gonna make mod on 0.5.2h and its crashes on 60+ fps.

**Comment by cyn-8** [comment]
i had problems with this recently #10143
a solution i found is to just include both onupdate and onupdatepost in each and every script
they can even be empty and without parameters and it will still fix the crashes

**Comment by FinGonz** [comment]
> i had problems with this recently #10143 a solution i found is to just include both onupdate and onupdatepost in each and every script they can even be empty and without parameters and it will still fix the crashes

hmmm, thanks for the info, I will try this method to see if it works or not.

**Comment by FinGonz** [comment]
> i had problems with this recently #10143 a solution i found is to just include both onupdate and onupdatepost in each and every script they can even be empty and without parameters and it will still fix the crashes

alright, that fixed the problem with it crashing mid-song, but now it crashes towards the end.
like 4 or so seconds before the song finishes

**Comment by FinGonz** [comment]
#10141

**Comment by FinGonz** [comment]
> i had problems with this recently #10143 a solution i found is to just include both onupdate and onupdatepost in each and every script they can even be empty and without parameters and it will still fix the crashes

but you helped fix another song that was over 3 minutes, thanks

**Comment by FinGonz** [comment]
> > i had problems with this recently #10143 a solution i found is to just include both onupdate and onupdatepost in each and every script they can even be empty and without parameters and it will still fix the crashes
> 
> alright, that fixed the problem with it crashing mid-song, but now it crashes towards the end. like 4 or so seconds before the song finishes

fixed, just ported an icon bopping script to source.
