### ISSUE TITLE
Pressing Space Dosen't Work Debug And Charactor Editor

### ISSUE THREAD

**Issue by DerpySlurrpe** [ShadowMario/FNF-PsychEngine#1017]
### Describe your bug here.

space button doesn't work with the latest version in character and debug I think it might be only html5. html5 builds of different mods with the engine don't work in other sites online so it's not just me. 

the part when you press space while typing in something in the character editor it doesn't work if that's not clear

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
HTML5 sucks ass.
