### ISSUE TITLE
Add camera zoom to character editor

### ISSUE THREAD

**Issue by PizzaSheriff** [ShadowMario/FNF-PsychEngine#10172]
### What feature do you want to get added on the **base** engine?

a simple addition to change the zoom value during a character's turn. useful for characters that are much larger than bf, without having him be ant-sized throughout the whole song.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
Would probably cause issues with zoom changes, and you can already do this

**Comment by PizzaSheriff** [comment]
really now? I've never seen anything of the sort. could you enlighten me?

**Comment by frantastic24** [comment]
You can just change defaultCamZoom each section

**Comment by Mastercopper2346** [comment]
Not really a bad idea.
