### ISSUE TITLE
arrows doesnt show 💀

### ISSUE THREAD

**Issue by gabrysfor555** [ShadowMario/FNF-PsychEngine#10174]
### Describe your bug here.

when i change the character when it was before the arrows dissapeard and the opponents arrows doesnt work at all and i miss when i miss and the arrows are late too

### Command Prompt/Terminal logs (if existing)

```bash
n'yes
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

idk

**Comment by gabrysfor555** [comment]
please help

**Comment by ZeitHeld** [comment]
what script did you use
it could be, that you let all arrows go transparent instead of just the opponents, if you did anything like that

**Comment by gabrysfor555** [comment]
sorry it was an speed error when it was 2 i though when you type -1 it will
be 1 sorry it works now

[image: width=]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Nie
zawiera wirusów.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

sob., 13 sie 2022 o 22:59 ZeitHeld ***@***.***> napisał(a):

**Comment by frantastic24** [comment]
Close the issue
