### ISSUE TITLE
please fix this shit

### ISSUE THREAD

**Issue by IhopeYouHaveAids** [ShadowMario/FNF-PsychEngine#10178]
### Describe your bug here.

whenever i load a song I made it gives me an error screen.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i added a new song and character

**Comment by frantastic24** [comment]
Not a bug, you messed something up

**Comment by Ninjakaiden523** [comment]
Error details?
