### ISSUE TITLE
runHaxeCode Not Working

### ISSUE THREAD

**Issue by meeptey2** [ShadowMario/FNF-PsychEngine#10177]
### Describe your problem here.

I'm trying to get an alert window to pop up using runHaxeCode, but I can't get it working. I've even tried just modifying the opponent's x value using it, but it didn't work. How can I fix runHaxeCode?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
It would help if you shower the code

**Comment by meeptey2** [comment]
Sorry! Forgot to do that.
`function onCreatePost()
    runHaxeCode([[
        lime.app.Application.current.window.alert("TEST");
    ]])
end`

**Comment by frantastic24** [comment]
you didn't add the library
```lua
function onCreatePost()
    addHaxeLibrary('Application', 'lime.app')
    runHaxeCode([[Application.current.window.alert('description', 'title');]]) 
end
```

**Comment by meeptey2** [comment]
THANK YOU

**Comment by MemeHoovy** [comment]
> I KIDNAP KIDS FOR CODING, EAT DAT PUSSY445

what

**Comment by MemeHoovy** [comment]
> that was edp445 username!!!! let me make thumbnail art for Ghost VIP rechart!!!!!!!!!!!!

https://youtu.be/td1BYb6LKdc
