### ISSUE TITLE
Psych Engine crashes when MODS_ALLOWED is disabled.

### ISSUE THREAD

**Issue by Itz-Miles** [ShadowMario/FNF-PsychEngine#10176]
### Describe your bug here.

	
	
	

Disabling mods or luascript support through project.xml crashes 0.5 - 0.6 without any terminal feedback; nobody has explained what caused issues after it was supposedly fixed later. (breakpoints also didn't give me any insight on what was happening either, it may be that the optional packages for the filesystem aren't put in conditional compilation blocks though)

https://user-images.githubusercontent.com/95124554/184499893-c51e1504-34f1-4225-b797-41d29a6d08bb.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I have a gutted 0.5 build, I had to try fixing some defines just so it'd compile.

**Comment by LilMewo** [comment]
one: holy thats a cool mod
two: why did you try to disable MODS_ALLOWED if you have a mod?

**Comment by Itz-Miles** [comment]
> one: holy thats a cool mod two: why did you try to disable MODS_ALLOWED if you have a mod?

Disabling the mod loader on already modded source code disables modpack loading, which vastly improves performance in places it's not needed.

The major reason why this mod uses source code is because I have a few matrix transformation packages that uses trigonometry to wrap sprites to a z axis, mimicking 3D. (here's an old example: https://www.youtube.com/watch?v=sAy39Xrfd8o&t=14s)

**Comment by ShadowMario** [comment]
We are currently at 0.6.2, not 0.5

**Comment by fnfdemonboi314159** [comment]
> We are currently at 0.6.2, not 0.5

Thats true, ShadowMario. Great work on Psych Engine!
