### ISSUE TITLE
How can I change the icon of the .exe file?

### ISSUE THREAD

**Issue by Nullyz** [ShadowMario/FNF-PsychEngine#10170]
### What is your question?

Hey so I'm working on a mod and I was wondering if there's a way I can change the icon of the .exe file via source code, if anyone knows how to do this?

**Comment by duckyduck1q** [comment]
Application.current.window.setIcon( Image.fromBitmapData( BitmapData.fromFile( Paths.modImage( 'myIcon.png' ) ) ) );

**Comment by Nullyz** [comment]
where can i find the file to change?

**Comment by duckyduck1q** [comment]
Go into the art folder and edit icon16 to 64 and iconOG

**Comment by Nullyz** [comment]
That's all that already changes the icon of the mod?

**Comment by duckyduck1q** [comment]
yes

**Comment by gabrysfor555** [comment]
i need help with that too 💀

**Comment by StefanBETA2008** [comment]
Do You Want The Change The Psych Engine Icon? Just Change To The art/ And You Will Find The 4 Icon's

**Comment by BygainYT** [comment]
> Go into the art folder and edit icon16 to 64 and iconOG

dude where is the art folder
how do i find it cause i aint have anything like that
