### ISSUE TITLE
Start Menu BG

### ISSUE THREAD

**Issue by SENFULLHD4K** [ShadowMario/FNF-PsychEngine#10175]
### What is your question?

**What I want to say is that normally in the title there is always a black background, I want to change it to an animated one and I ask if there is a way to do it**

It would help me a lot if you answer me immediately, I would really appreciate it.

**Comment by Jevilm** [comment]
Downloaded Build:
Go into assets/images, go to gfdancetitle.json and go to bg and replace whatever is there with your image
the image must be in mods/images

**Comment by SENFULLHD4K** [comment]
> Downloaded Build:
> Go into assets/images, go to gfdancetitle.json and go to bg and replace whatever is there with your image
> the image must be in mods/images

but you don't need to put an xml for the move or something??

**Comment by SENFULLHD4K** [comment]
> Downloaded Build:
> Go into assets/images, go to gfdancetitle.json and go to bg and replace whatever is there with your image
> the image must be in mods/images

but you don't need to put an xml for the move or something??

**Comment by Jevilm** [comment]
idk

**Comment by SENFULLHD4K** [comment]
Bruh
