### ISSUE TITLE
Source code string into lua

### ISSUE THREAD

**Issue by hotpocketsarepoggers** [ShadowMario/FNF-PsychEngine#10180]
### Describe your problem here.

I'm having trouble getting this source code string into lua. Can anyone help me?

case 572:

						if (isStoryMode)
						{
							add(blackFade);
							
							FlxTween.tween(blackFade, {alpha: 1.0}, 0.2, 
							{ease: FlxEase.quadIn});

							FlxTween.tween(camHUD, {alpha: 0}, 1.2, 
								{ease: FlxEase.quadInOut});
						}
				}
			}

		}

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers

**Comment by hotpocketsarepoggers** [comment]
figured it out
