### ISSUE TITLE
scripts crashing on Version 0.4 

### ISSUE THREAD

**Issue by neighborduck** [ShadowMario/FNF-PsychEngine#1018]
### Describe your bug here.

So I have the version 0.4 build of psych and whenever using some certain scripts I notice that when the song reaches mid point it causes the game to auto close even when using some Scripts from the API documentation 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
0.4 isn't supported anymore, use 0.4.2.
