### ISSUE TITLE
add custom intro texts to folder mods

### ISSUE THREAD

**Issue by aflacc** [ShadowMario/FNF-PsychEngine#10184]
### What feature do you want to get added on the **base** engine?

i feel like we should be able to put an `introText.txt` file into a mods data folder and it should at least add the texts to the already existing list. it's literally something the base fnf game can do

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
Using the one in assets does work though.

**Comment by Lorekeeper49** [comment]
I believe that that actually _does_ work, you just need your mod at the top of `modsList.txt`

**Comment by Gostar64** [comment]
> I believe that that actually _does_ work, you just need your mod at the top of `modsList.txt`

I think he wants it to specifically be added on and not overwritten? (idk I always copy and paste the og intro text before I add mine to my mods)

**Comment by ShadowMario** [comment]
should work
