### ISSUE TITLE
Null object refrence

### ISSUE THREAD

**Issue by Whiteconbi** [ShadowMario/FNF-PsychEngine#10181]
### Describe your bug here.

every time i get in a minute of a song the crash error pops up it says
Paths.hx (line 352)
PlayState.hx (line 3983)
PlayState.hx (line 4485)
PlayState.hx (line 4157)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i just added some people and stuff

**Comment by Whiteconbi** [comment]
im not a coder

**Comment by frantastic24** [comment]
Not a bug
Missing rating textures

**Comment by Whiteconbi** [comment]
????

**Comment by Whiteconbi** [comment]
how do i fix

**Comment by frantastic24** [comment]
Get the textures you're missing

**Comment by Whiteconbi** [comment]
k

**Comment by Whiteconbi** [comment]
everytime it hits the lose icon it crashes

**Comment by Whiteconbi** [comment]
i have the lose icons
