### ISSUE TITLE
source/FunkinLua.hx:578: characters 4-7 : Expected , or )

### ISSUE THREAD

**Issue by zPuertah** [ShadowMario/FNF-PsychEngine#10183]
### Describe your problem here.

I cant run the "haxelib run lime test windows"

![image](https://user-images.githubusercontent.com/82531214/184510791-8586f30e-eb57-4082-9b3d-4fa3ae2e91c4.png)

![image](https://user-images.githubusercontent.com/82531214/184510818-ccab8da5-9643-46c3-9985-1ec224434058.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I only change the credits :(

**Comment by MemeHoovy** [comment]
1.Use VS Code (Visual Studio Code), although I used Notepad++ before, VS Code is better in many ways.
2. Delete that extra curly bracket on line 574.

**Comment by Sasuke-thelast** [comment]
Thanks
but now show me 4 errors 
XD
But thanks

![image](https://user-images.githubusercontent.com/82531214/184543404-f95aa23a-b950-41cd-a7cc-a81828cd64b0.png)

**Comment by MemeHoovy** [comment]
```
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit 
```
to fix the lua errors.
And
```
haxelib install hxCodec
```
to fix the mp4handler errors.
