### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by FlintIshe** [ShadowMario/FNF-PsychEngine#10188]
### Describe your problem here.

How can I make a specific sound only plays once instead of playing on every frame

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by bruh1cat** [comment]
function onStepHit()
if curStep == 69 then --You can check the Step in the chart editor
playSound(' ')
end
end

**Comment by FlintIshe** [comment]
thanks
