### ISSUE TITLE
Error with "Setobjectorder"?

### ISSUE THREAD

**Issue by JhinerDoux** [ShadowMario/FNF-PsychEngine#10187]
### What is your question?

Is it normal for the "setObjectOrder" command to add a sprite that doesn't even have "AddLuaSprite" in the lua?

**Comment by frantastic24** [comment]
It removes and readds the object at the specified position so yes

**Comment by JhinerDoux** [comment]
Oh, esta bien

**Comment by JhinerDoux** [comment]
thanks for clarifying my question
