### ISSUE TITLE
Crash when trying to play one of my custom songs

### ISSUE THREAD

**Issue by XTERMlN8** [ShadowMario/FNF-PsychEngine#10190]
### Describe your bug here.

![crash](https://user-images.githubusercontent.com/111227688/184534235-d6d7aab3-d62d-429d-9952-b93c59442f38.PNG)
I have no idea what this is

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by frantastic24** [comment]
Not a bug
JSON file is broken

**Comment by XTERMlN8** [comment]
ah ok I'll close it
