### ISSUE TITLE
I guess I cant have certain Scripts then...

### ISSUE THREAD

**Issue by PsychEnjoyer** [ShadowMario/FNF-PsychEngine#10199]
### Describe your bug here.

Whenever I have the unique opponent scripts on. no matter what script I use. it always crashes on me! I can use other scripts but this one is just a pain in the ass I suppose.
BONUS ADDED
it shows this message
StrumNote.hx (line 139)
flixel/group/FlxGroup.hx (line 175)
flixel/group/FlxGroup.hx (line 175)
flixel/addons/ui/FlxUIState.hx (line 212)
MusicBeatState.hx (line 66)
PlayState.hx (line 2878)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope. No changes. only extra mods but that doesnt mess with the executable

**Comment by frantastic24** [comment]
not a bug
note texture has invalid/missing animations

**Comment by PsychEnjoyer** [comment]
but i never changed anything with the notes and it worked before the script got added? how does that mess with the note texture???

**Comment by frantastic24** [comment]
You didn't show any of the files you're using so can't really help

**Comment by PsychEnjoyer** [comment]
i only used a script

**Comment by frantastic24** [comment]
The point of reporting a bug is showing the script
