### ISSUE TITLE
compiling issue

### ISSUE THREAD

**Issue by Jaysfs** [ShadowMario/FNF-PsychEngine#10198]
### Describe your problem here.

when i type lime test windows it says could not find haxelib "discord_rpc" does it need to be installed and discord rpc is already installed

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I looked up a video and it said copy "<haxelib name="discord_rpc" if="desktop"/>" in project.xml and then paste it and then add .DiscordRpc at the end and it didnt work

**Comment by PogofruitKM** [comment]
Remove changes in project.xml
Discord RPC is determined if you're on desktop or not.
If issue still persists go all over instructions again.
