### ISSUE TITLE
any attempt to change health via function good note hit doesn't work anymore

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#10195]
### Describe your bug here.

so basically, one day i was coding, and suddenly a bunch of notes just didn't work right. any note that didn't give health gave health, any custom note that damaged you but didn't instantly kill you gave health, basically any note with code that looked something like this
function goodNoteHit(id, noteData, noteType, isSustainNote)
	
	  bruh = getProperty('health');
	  setProperty('health', bruh - 0.023);
	
end
just didn't work at all!
And this was on all psych engine instances! just stopped working! didn't matter what version! idk what i did to cause this!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by acap09** [comment]
this also happens to me

**Comment by frantastic24** [comment]
it works fine for me, did you change health gain multiplier

**Comment by wubbzyfan** [comment]
No I didn’t

**Comment by fnfdemonboi314159** [comment]
also, this is not related, but #10197

**Comment by frantastic24** [comment]
No shut up

**Comment by wubbzyfan** [comment]
apparently, i did. i want to die.

**Comment by PogofruitKM** [comment]
If this note is a Kill Note (Misses upon pressing) then the function is noteMiss.
