### ISSUE TITLE
how do i fix this?

### ISSUE THREAD

**Issue by BlankHuh** [ShadowMario/FNF-PsychEngine#10191]
### What is your question?

I want to fix this but IDK how
![image](https://user-images.githubusercontent.com/93549849/184534314-7daea0d4-aa18-425e-98d8-f4dc9b254bae.png)
when I compile the build and finish Freeplay song or week it goes to the bonus option

**Comment by Mastercopper2346** [comment]
Make the variables separate. here you’re putting the code with the freeplay code.

**Comment by BlankHuh** [comment]
> Make the variables separate. here you’re putting the code with the freeplay code.

ohhhhhhh, alr
