### ISSUE TITLE
Base FNF Style Icon Bop

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#10197]
### Describe your problem here.

Long story short, I need a Lua script to make the icons bop similarly to the base game's icon bop. can you help me out?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by fnfdemonboi314159** [comment]
also, I tried looking this up, and there was a gamebanana question about this topic, but it involved source code. I don't do source code. There was a Kade Engine UI Makeover for Psych, but there wasn't any code for the Icon Bopping anywhere. I wanted the Kade style Icon bop in Lua, for Psych Engine.

**Comment by PogofruitKM** [comment]
Then you'll have to literally rewrite the entire HUD in Lua. (Which I don't think is possible because of lack of variables)
Source or No original icon bop.

**Comment by fnfdemonboi314159** [comment]
> Then you'll have to literally rewrite the entire HUD in Lua. (Which I don't think is possible because of lack of variables) Source or No original icon bop.

Well I just wanted the icon bop. not the HUD.

**Comment by frantastic24** [comment]
You could just look it up on source code and write that in Lua

**Comment by Mastercopper2346** [comment]
If you go WAYYYY back in closed discussions, you will find one.

**Comment by fnfdemonboi314159** [comment]
> If you go WAYYYY back in closed discussions, you will find one.

and what is the number for that closed discussion?

**Comment by TFLTV** [comment]
```lua
local turnvalue = 20
function onBeatHit()

turnvalue = 20
if curBeat % 2 == 0 then
turnvalue = -20
end

setProperty('iconP2.angle',-turnvalue)
setProperty('iconP1.angle',turnvalue)

doTweenAngle('iconTween1','iconP1',0,crochet/1000,'circOut')
doTweenAngle('iconTween2','iconP2',0,crochet/1000,'circOut')


end -- CREDIT TO BBPANZU FOR THE SCRIPT
```

**Comment by fnfdemonboi314159** [comment]
> ```lua
> local turnvalue = 20
> function onBeatHit()
> 
> turnvalue = 20
> if curBeat % 2 == 0 then
> turnvalue = -20
> end
> 
> setProperty('iconP2.angle',-turnvalue)
> setProperty('iconP1.angle',turnvalue)
> 
> doTweenAngle('iconTween1','iconP1',0,crochet/1000,'circOut')
> doTweenAngle('iconTween2','iconP2',0,crochet/1000,'circOut')
> 
> 
> end -- CREDIT TO BBPANZU FOR THE SCRIPT
> ```

man, this is not the script I need. I wanted the base game style script. not the icons turning
