### ISSUE TITLE
Type not found : FlxVideo

### ISSUE THREAD

**Issue by Al-AmeenAdewunmi** [ShadowMario/FNF-PsychEngine#10201]
### Describe your problem here.

It seems that I'm the only one to have this issue. I'm trying to add a cutscene that plays as soon as you open the game. In TitleState.hx I added "new FlxVideo(assets/videos/intro.mp4);", but whenever I try building, I end up with:
"source/TitleState.hx:664: characters 9-17 : Type not found : FlxVideo"

How do I fix this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by BeastlyGhost** [comment]
FlxVideo is not used on Psych anymore (as for 0.6), try using MP4Handler instead, or importing said class to your desired state

```Haxe
import MP4Handler;
//...
//...
//...

var video:MP4Handler;
video.playVideo(intro)';
video.finishCallback = function()
{
	startIntro();
	return;
}
```

**Comment by Al-AmeenAdewunmi** [comment]
I'm getting "Expected }" as an error now.

**Comment by Al-AmeenAdewunmi** [comment]
Uh, anyone?

**Comment by Al-AmeenAdewunmi** [comment]
> FlxVideo is not used on Psych anymore (as for 0.6), try using MP4Handler instead
> 
> ```hx
> import MP4Handler;
> 
> // on the create function;
> 
> var video:MP4Handler = new MP4Handler();
> video.playVideo(Paths.video('intro'));
> video.finishCallback = function()
> {
> 	startIntro();
> }
> ```
> 
> alternatively, check your imports to see if FlxVideo is there in case you are using an older version




![Screenshot (5511)](https://user-images.githubusercontent.com/53586162/185293452-68a6818f-d670-4cd9-a674-605e8a3600e8.png)
![Screenshot (5510)](https://user-images.githubusercontent.com/53586162/185293458-fc66a04e-9a52-4c47-9122-272d3b506b6c.png)

Figured it'd make more sense to show screenshots.

**Comment by CrusherNotDrip** [comment]
> > FlxVideo is not used on Psych anymore (as for 0.6), try using MP4Handler instead
> 
> > 
> 
> > ```hx
> 
> > import MP4Handler;
> 
> > 
> 
> > // on the create function;
> 
> > 
> 
> > var video:MP4Handler = new MP4Handler();
> 
> > video.playVideo(Paths.video('intro'));
> 
> > video.finishCallback = function()
> 
> > {
> 
> > 	startIntro();
> 
> > }
> 
> > ```
> 
> > 
> 
> > alternatively, check your imports to see if FlxVideo is there in case you are using an older version
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ![Screenshot (5511)](https://user-images.githubusercontent.com/53586162/185293452-68a6818f-d670-4cd9-a674-605e8a3600e8.png)
> 
> ![Screenshot (5510)](https://user-images.githubusercontent.com/53586162/185293458-fc66a04e-9a52-4c47-9122-272d3b506b6c.png)
> 
> 
> 
> Figured it'd make more sense to show screenshots.

put import somewhere at the very top

**Comment by Al-AmeenAdewunmi** [comment]
> > > FlxVideo is not used on Psych anymore (as for 0.6), try using MP4Handler instead
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > import MP4Handler;
> > 
> > 
> > > 
> > 
> > 
> > > // on the create function;
> > 
> > 
> > > 
> > 
> > 
> > > var video:MP4Handler = new MP4Handler();
> > 
> > 
> > > video.playVideo(Paths.video('intro'));
> > 
> > 
> > > video.finishCallback = function()
> > 
> > 
> > > {
> > 
> > 
> > > ```
> > > startIntro();
> > > ```
> > 
> > 
> > > }
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > alternatively, check your imports to see if FlxVideo is there in case you are using an older version
> > 
> > 
> > ![Screenshot (5511)](https://user-images.githubusercontent.com/53586162/185293452-68a6818f-d670-4cd9-a674-605e8a3600e8.png)
> > ![Screenshot (5510)](https://user-images.githubusercontent.com/53586162/185293458-fc66a04e-9a52-4c47-9122-272d3b506b6c.png)
> > Figured it'd make more sense to show screenshots.
> 
> put import thing somewhere at the very top

Okay, I did that, but now I'm getting "Type not found : MP4Handler" as an error. And I made sure that I installed hxCodec so, I don't know what I'm doing wrong here.

**Comment by MemeHoovy** [comment]
> > > > FlxVideo is not used on Psych anymore (as for 0.6), try using MP4Handler instead
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > import MP4Handler;
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > // on the create function;
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > var video:MP4Handler = new MP4Handler();
> > > 
> > > 
> > > > video.playVideo(Paths.video('intro'));
> > > 
> > > 
> > > > video.finishCallback = function()
> > > 
> > > 
> > > > {
> > > 
> > > 
> > > > ```
> > > > startIntro();
> > > > ```
> > > 
> > > 
> > > > }
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > alternatively, check your imports to see if FlxVideo is there in case you are using an older version
> > > 
> > > 
> > > ![Screenshot (5511)](https://user-images.githubusercontent.com/53586162/185293452-68a6818f-d670-4cd9-a674-605e8a3600e8.png)
> > > ![Screenshot (5510)](https://user-images.githubusercontent.com/53586162/185293458-fc66a04e-9a52-4c47-9122-272d3b506b6c.png)
> > > Figured it'd make more sense to show screenshots.
> > 
> > 
> > put import thing somewhere at the very top
> 
> Okay, I did that, but now I'm getting "Type not found : MP4Handler" as an error. And I made sure that I installed hxCodec so, I don't know what I'm doing wrong here.

Did you make sure you're using the haxelib version instead of the git version?
Do
``` 
haxelib install hxCodec
```

**Comment by Al-AmeenAdewunmi** [comment]
> > > > > FlxVideo is not used on Psych anymore (as for 0.6), try using MP4Handler instead
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > import MP4Handler;
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > // on the create function;
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > var video:MP4Handler = new MP4Handler();
> > > > 
> > > > 
> > > > > video.playVideo(Paths.video('intro'));
> > > > 
> > > > 
> > > > > video.finishCallback = function()
> > > > 
> > > > 
> > > > > {
> > > > 
> > > > 
> > > > > ```
> > > > > startIntro();
> > > > > ```
> > > > 
> > > > 
> > > > > }
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > alternatively, check your imports to see if FlxVideo is there in case you are using an older version
> > > > 
> > > > 
> > > > ![Screenshot (5511)](https://user-images.githubusercontent.com/53586162/185293452-68a6818f-d670-4cd9-a674-605e8a3600e8.png)
> > > > ![Screenshot (5510)](https://user-images.githubusercontent.com/53586162/185293458-fc66a04e-9a52-4c47-9122-272d3b506b6c.png)
> > > > Figured it'd make more sense to show screenshots.
> > > 
> > > 
> > > put import thing somewhere at the very top
> > 
> > 
> > Okay, I did that, but now I'm getting "Type not found : MP4Handler" as an error. And I made sure that I installed hxCodec so, I don't know what I'm doing wrong here.
> 
> Did you make sure you're using the haxelib version instead of the git version? Do
> 
> ```
> haxelib install hxCodec
> ```
> 
> Also you put the import near the other imports not next to the variable for the MP4Handler and put vlc.MP4Handler instead of just MP4Handler like seen here. ![Screenshot 2022-08-18 011029](https://user-images.githubusercontent.com/97995998/185298805-d3494543-c979-468d-9f70-e127aa35490e.png)

Oh, that was the issue. I never placed vlc.MP4Handler. Now it builds.

Just uh, one issue. How do I make the video play before the intro text pops up?

**Comment by MemeHoovy** [comment]
Replace the the line in the picture.
![Screenshot 2022-08-18 012509](https://user-images.githubusercontent.com/97995998/185300904-b8ed2b12-869f-4c99-abcc-7d9ecdcb0e50.png)
With this.
```
			if (initialized){
				var video:MP4Handler = new MP4Handler();
				video.playVideo(Paths.video('example'));
				video.finishCallback = function() {
					startIntro();
				}
			}
			else
			{
				var video:MP4Handler = new MP4Handler();
				video.playVideo(Paths.video('example'));
				video.finishCallback = function() {
					startIntro();
				}
			}
```
Here's a picture of what it should look like.
![Screenshot 2022-08-18 012839](https://user-images.githubusercontent.com/97995998/185301078-1240153c-a89c-4c3b-b54b-bbc9c675480e.png)
Replace "example" with the video you're trying to load.

**Comment by Al-AmeenAdewunmi** [comment]
Alright, everything is fine now. Thanks.
