### ISSUE TITLE
Troubleshooting afterimage event?

### ISSUE THREAD

**Issue by hotpocketsarepoggers** [ShadowMario/FNF-PsychEngine#10206]
### Describe your problem here.

During the song Nightrider the characters get a after image effect for each note they hit. How can I make a lua script of that?

Example being if they hit a up note a after image appears that goes up

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by bruh1cat** [comment]
addHaxeLibrary('FlxTrail', 'flixel.addons.effects')
    runHaxeCode('game.addBehindDad(new FlxTrail(game.dad, null, 4, 24, 0.3, 0.069));')

**Comment by hotpocketsarepoggers** [comment]
> addHaxeLibrary('FlxTrail', 'flixel.addons.effects') runHaxeCode('game.addBehindDad(new FlxTrail(game.dad, null, 4, 24, 0.3, 0.069));')

how can I do this with lua though?

**Comment by frantastic24** [comment]
That is Lua, but it's not really the effect you want, it doesn't move up

**Comment by hotpocketsarepoggers** [comment]
How would I put it in a lua script? What function would I use?

**Comment by bruh1cat** [comment]
> How would I put it in a lua script? What function would I use?

function opponentNoteHit(id, direction, noteType, isSustainNote)
addHaxeLibrary('FlxTrail', 'flixel.addons.effects')
runHaxeCode('game.addBehindDad(new FlxTrail(game.dad, null, 4, 24, 0.3, 0.069));')-- Works the same as goodNoteHit, but for Opponent's notes being hit
end

**Comment by bruh1cat** [comment]
Or if you want it on a specific section:

function onStepHit()
if curStep == 1 then
addHaxeLibrary('FlxTrail', 'flixel.addons.effects')
runHaxeCode('game.addBehindDad(new FlxTrail(game.dad, null, 4, 24, 0.3, 0.069));')
end

**Comment by hotpocketsarepoggers** [comment]
> > How would I put it in a lua script? What function would I use?
> 
> function opponentNoteHit(id, direction, noteType, isSustainNote) addHaxeLibrary('FlxTrail', 'flixel.addons.effects') runHaxeCode('game.addBehindDad(new FlxTrail(game.dad, null, 4, 24, 0.3, 0.069));')-- Works the same as goodNoteHit, but for Opponent's notes being hit end
> 
> Also change the game.dad to boyfriend if you want the player to have this effect

I put this in and nothing happens

**Comment by bruh1cat** [comment]
> > > How would I put it in a lua script? What function would I use?
> 
> > 
> 
> > function opponentNoteHit(id, direction, noteType, isSustainNote) addHaxeLibrary('FlxTrail', 'flixel.addons.effects') runHaxeCode('game.addBehindDad(new FlxTrail(game.dad, null, 4, 24, 0.3, 0.069));')-- Works the same as goodNoteHit, but for Opponent's notes being hit end
> 
> > 
> 
> > Also change the game.dad to boyfriend if you want the player to have this effect
> 
> 
> 
> I put this in and nothing happens

Be sure to use the action builda

**Comment by hotpocketsarepoggers** [comment]
> > > > How would I put it in a lua script? What function would I use?
> > 
> > 
> > > 
> > 
> > 
> > > function opponentNoteHit(id, direction, noteType, isSustainNote) addHaxeLibrary('FlxTrail', 'flixel.addons.effects') runHaxeCode('game.addBehindDad(new FlxTrail(game.dad, null, 4, 24, 0.3, 0.069));')-- Works the same as goodNoteHit, but for Opponent's notes being hit end
> > 
> > 
> > > 
> > 
> > 
> > > Also change the game.dad to boyfriend if you want the player to have this effect
> > 
> > 
> > I put this in and nothing happens
> 
> Be sure to use the action builda

How do I use the action build?

**Comment by bruh1cat** [comment]
> > > > > How would I put it in a lua script? What function would I use?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > function opponentNoteHit(id, direction, noteType, isSustainNote) addHaxeLibrary('FlxTrail', 'flixel.addons.effects') runHaxeCode('game.addBehindDad(new FlxTrail(game.dad, null, 4, 24, 0.3, 0.069));')-- Works the same as goodNoteHit, but for Opponent's notes being hit end
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Also change the game.dad to boyfriend if you want the player to have this effect
> 
> > > 
> 
> > > 
> 
> > > I put this in and nothing happens
> 
> > 
> 
> > Be sure to use the action builda
> 
> 
> 
> How do I use the action build?

Where the "issues" tab is you'll see a tab called action go there and download the latest one (it's just the same as the normal builds).

**Comment by hotpocketsarepoggers** [comment]
> > > > > > How would I put it in a lua script? What function would I use?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > function opponentNoteHit(id, direction, noteType, isSustainNote) addHaxeLibrary('FlxTrail', 'flixel.addons.effects') runHaxeCode('game.addBehindDad(new FlxTrail(game.dad, null, 4, 24, 0.3, 0.069));')-- Works the same as goodNoteHit, but for Opponent's notes being hit end
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > Also change the game.dad to boyfriend if you want the player to have this effect
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I put this in and nothing happens
> > 
> > 
> > > 
> > 
> > 
> > > Be sure to use the action builda
> > 
> > 
> > How do I use the action build?
> 
> Where the "issues" tab is you'll see a tab called action go there and download the latest one (it's just the same as the normal builds).

alright thanks!

**Comment by Parsellol** [comment]
why is this still open

**Comment by MemeHoovy** [comment]
> why is this still open

they forgot to close the issue

**Comment by Parsellol** [comment]
> > why is this still open
> 
> they forgot to close the issue

yeah i was just saying close the issue in a funny hilarious way

**Comment by hotpocketsarepoggers** [comment]
Oops my bad
