### ISSUE TITLE
Uncaught Error: Null Object Reference

### ISSUE THREAD

**Issue by CappyOn** [ShadowMario/FNF-PsychEngine#10209]
### Describe your bug here.

I don't know why but when I was playing the Whitty Psych Port mod I got an error. It's logs are pasted below.

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 1061)
flixel/util/FlxTimer.hx (line 195)
flixel/util/FlxTimer.hx (line 285)
flixel/FlxGame.hx (line 745)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 178)
openfl/display/DisplayObject.hx (line 516)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Isn't the mod a fork? Go report it in its repository, not here
