### ISSUE TITLE
Play Story to Unlock Freeplay

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#10208]
### What feature do you want to get added on the **base** engine?

It would be cool to have the option, not always being foced to it, but to be able to decide it, if certain songs (or even whole weeks which probably works easier) should be played first in Story mode, after being able to play them in freeplay.

Like that one can make sure, that you play it properly and not possibly skip the whole story
After that, you can play it in freeplay, as often as you want, and not having to see the cutscenes and dialogues

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
That would ruin mods :/

**Comment by TFLTV** [comment]
you can just make a normal week (the main one) and make it so it won't be able to be played in freeplay.  Then make a second week with everything the same BUT you can only find it in freeplay and link it to the main week so when you complete that week the second week will be unlocked

**Comment by TFLTV** [comment]
So, you can ALREADY do this

**Comment by Parsellol** [comment]
> That would ruin mods :/

how

**Comment by Lorekeeper49** [comment]
> That would ruin mods :/

Great mods like Indie Cross do this

**Comment by DW-EriccruzYT** [comment]
bro;_;
fir that the mods will going down but is your  mod i dont have anything to say.

**Comment by BeastlyGhost** [comment]
strongly disagree with this as it takes away the "freedom" that the game gives you to beat any song you want at any given time, this could however be nice for mods that heavily modify the source code, but as a feature for the base engine itself, it seems kinda pointless

**Comment by ZeitHeld** [comment]
I mean, I said it CAN be an OPTION, like in week.json.
It won't be activated by default.

Just thought of it, to avoid skipping stories before playing it all in Freeplay.

Like if you beat Week 1, you can play songs of Week 1. And only them.
Though it'd then be disabled for the base game.

Or like you downloaded a lua mod with 2 weeks and a whole story, you gotta play modweek1 then play those songs in freeplay.

Also, it can avoid any kinds of "spoilers", like new transformations or new characters that appear in that song


I often do these requests and get the ideas, as my pc won't compile source codes (like in general, it's a pain in the ass) and lua has been so far a great advancement for myself to play around with in fnf.

I mean, it would not be bad if it isn't added, this for example, I can see why it can be added, but also why not. Because it's how fnf always behaved so far

**Comment by ShadowMario** [comment]
> > you can just make a normal week (the main one) and make it so it won't be able to be played in freeplay. Then make a second week with everything the same BUT you can only find it in freeplay and link it to the main week so when you complete that week the second week will be unlocked
> 
> That may be possible, but it would then require duplicates. Whihc is then a bit of extra work nobody really wants to do. Plus, the score will not be the same

Too bad! Modding isn't "The tool should do every thing for me", nobody will care if you do duplicates, just do it and stop asking me to add literally everything into it, i don't wanna bloat Psych more than i've already done.

**Comment by DW-EriccruzYT** [comment]
wow Hi shadow
