### ISSUE TITLE
Scroll speed note 

### ISSUE THREAD

**Issue by joxu13v** [ShadowMario/FNF-PsychEngine#10202]
### Describe your problem here.

So, I want to create a note that, when not pressed, considerably increases the scroll speed, along with a flash of an image on the screen

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by FlintIshe** [comment]
just use the change scroll speed event and place it on the same line as your note 

for the camera do 

cameraFlash('hud', FFFFFF, 1)

**Comment by Parsellol** [comment]
```lua
local theFuni = 1
function noteMiss(id, noteData, noteType, isSustainNote)
	if noteType == 'Instakill Note' then
		theFuni = theFuni + 0.1
		triggerEvent("Change Scroll Speed", theFuni, "0.01")
	end
end
-- theres probably a better way of doing this but yeah also im way too lazy to do the image thing
```

**Comment by joxu13v** [comment]
Thanks
