### ISSUE TITLE
why is this happening?

### ISSUE THREAD

**Issue by EzzyDunez** [ShadowMario/FNF-PsychEngine#10200]
### Describe your bug here.

if i load a song, especially my fnf song, after a few secends it says "Paths.hx (line 352)
PlayState.hx (line 3983)
PlayState.hx (line 4485)
PlayState.hx (line 4157)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng"
but i have no idea why.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

idk if i edited anything in the build

**Comment by Mastercopper2346** [comment]
Is it specifically when the opponent/player hits a note?

**Comment by Ninjakaiden523** [comment]
Something is missing, check to make sure all the assets in the engine, and all the assets you've added exist, and are labeled correctly

**Comment by EzzyDunez** [comment]
> Is it specifically when the opponent/player hits a note? i dont think so
