### ISSUE TITLE
how to swipe bf left in mid song like triple trouble?

### ISSUE THREAD

**Issue by deathline1938** [ShadowMario/FNF-PsychEngine#10211]
### Describe your problem here.

**`title says eveything`**

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by frantastic24** [comment]
Change Character and move strums

**Comment by deathline1938** [comment]
I am play opponent now

**Comment by tylerandari12** [comment]
> > I am play opponent now
> 
> what

You heard him...
He is play opponent now...
