### ISSUE TITLE
Accuracy System

### ISSUE THREAD

**Issue by Ultimate57** [ShadowMario/FNF-PsychEngine#10218]
### What feature do you want to get added on the **base** engine?

Seriously needs to be reworked.

I'd get 53 sicks and 2 goods would bring down all the way to 99.09.

Also color the ratings I can't see what I got because its all white.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
> Also color the ratings I can't see what I got because its all white.

true

**Comment by Mastercopper2346** [comment]
> > Also color the ratings I can't see what I got because its all white.
> 
> true

but you can still edit the images to be colored.

**Comment by Ultimate57** [comment]
that's honestly the main reason I despise pysch engine

**Comment by Ultimate57** [comment]
> > > Also color the ratings I can't see what I got because its all white.
> > 
> > 
> > true
> 
> but you can still edit the images to be colored.

yeah but that would mean I would have to do that with EVERY SINGLE MOD

**Comment by Mastercopper2346** [comment]
> > > > Also color the ratings I can't see what I got because its all white.
> > > 
> > > 
> > > true
> > 
> > 
> > but you can still edit the images to be colored.
> 
> yeah but that would mean I would have to do that with EVERY SINGLE MOD

I’ll just make a pr.

**Comment by Ultimate57** [comment]
> > > > > Also color the ratings I can't see what I got because its all white.
> > > > 
> > > > 
> > > > true
> > > 
> > > 
> > > but you can still edit the images to be colored.
> > 
> > 
> > yeah but that would mean I would have to do that with EVERY SINGLE MOD
> 
> I’ll just make a pr.

?

**Comment by Ultimate57** [comment]
> ShadowMario decided to do harsher judgment's, cuz as he says:
> 
> `//trying to do ms judgment as demanded` (I don't remember the comment, will edit)

That's stupid

**Comment by Ultimate57** [comment]
> > > ShadowMario decided to do harsher judgment's, cuz as he says:
> > > `//trying to do ms judgment as demanded` (I don't remember the comment, will edit)
> > 
> > 
> > That's stupid
> 
> cry

screw you

**Comment by Mastercopper2346** [comment]
> > > > > > Also color the ratings I can't see what I got because its all white.
> > > > > 
> > > > > 
> > > > > true
> > > > 
> > > > 
> > > > but you can still edit the images to be colored.
> > > 
> > > 
> > > yeah but that would mean I would have to do that with EVERY SINGLE MOD
> > 
> > 
> > I’ll just make a pr.
> 
> ?

Make a pull request?

**Comment by ShadowMario** [comment]
Nah

**Comment by Ultimate57** [comment]
> Nah, not every FNF engine has to work in the same way regarding judgements/ratings etc

true very true but when your accuracy is this inaccurate then we have a problem
the ONLY song I feel works for this is Ballistic and Ballistic Remix

**Comment by frantastic24** [comment]
My brother in Christ there are gameplay modifiers you can use
Playing a rhythm game that's actually meant to be hard is also an option

**Comment by Ultimate57** [comment]
> My brother in Christ there are gameplay modifiers you can use Playing a rhythm game that's actually meant to be hard is also an option

its not hard coded is the problem

**Comment by MemeHoovy** [comment]
> > My brother in Christ there are gameplay modifiers you can use Playing a rhythm game that's actually meant to be hard is also an option
> 
> its not hard coded is the problem

wdym?

**Comment by Ultimate57** [comment]
> > > My brother in Christ there are gameplay modifiers you can use Playing a rhythm game that's actually meant to be hard is also an option
> > 
> > 
> > its not hard coded is the problem
> 
> wdym?

if the health is hardcoded to be hard then that actually feels like its hard not me manually having to do it
and it really doesn't matter if my eyes are glued to the accuracy

**Comment by MemeHoovy** [comment]
> > > > My brother in Christ there are gameplay modifiers you can use Playing a rhythm game that's actually meant to be hard is also an option
> > > 
> > > 
> > > its not hard coded is the problem
> > 
> > 
> > wdym?
> 
> if the health is hardcoded to be hard then that actually feels like its hard not me manually having to do it and it really doesn't matter if my eyes are glued to the accuracy

oh
