### ISSUE TITLE
Hold Notes

### ISSUE THREAD

**Issue by Ultimate57** [ShadowMario/FNF-PsychEngine#10215]
### What feature do you want to get added on the **base** engine?

Make hold notes give accuracy.
Add an option where hold notes don't give health.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tylerandari12** [comment]
Second one is already possible in Lua...

**Comment by Ultimate57** [comment]
i cant code

**Comment by Mastercopper2346** [comment]
> Second one is already possible in Lua...

No, it’s impossible to make a option in lua
