### ISSUE TITLE
How to make the code wait for some time

### ISSUE THREAD

**Issue by doitover** [ShadowMario/FNF-PsychEngine#10210]
### What is your question?

I am making a note type that makes it to where if you hit it, a image pops up and then it waits a little bit then closes the game
i wrote some code but its not working please tell me why
i dont really know what i can use for the wait could someone tell me

![image](https://user-images.githubusercontent.com/91207983/184916558-6ba86a72-5aa7-483f-87e2-4cf0e7441cbc.png)

**Comment by FlintIshe** [comment]
may be runTimer()

and 
os.exit()

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers#runtimertagstring-timefloat--1-loopsint--1

**Comment by doitover** [comment]
i tried to run a timer but it did not work

**Comment by doitover** [comment]
![image](https://user-images.githubusercontent.com/91207983/184918048-87bb3b26-8052-4f0a-85fa-fac3b08115de.png)

**Comment by FlintIshe** [comment]
you need to make a new function called onTimerCompleted()

**Comment by doitover** [comment]
didnt work 
![image](https://user-images.githubusercontent.com/91207983/184919007-1b3167d1-3af4-454a-8713-0f955d9eeb29.png)

**Comment by frantastic24** [comment]
You forgot the function variable

**Comment by FlintIshe** [comment]
![image](https://user-images.githubusercontent.com/101379721/184921629-4ba03fe8-701d-4a4e-8039-4c7ad644f5fc.png)

**Comment by doitover** [comment]
Yes it worked
but just one more question how could i make it to where if i hit enter then it would close?

**Comment by FlintIshe** [comment]
```ruby
if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.ENTER) then
     os.exit()

end
```

**Comment by doitover** [comment]
like this? 
![image](https://user-images.githubusercontent.com/91207983/184924878-e51acb49-4593-4009-a747-241b81258052.png)

**Comment by frantastic24** [comment]
No, it goes under `function onUpdate()`

**Comment by FlintIshe** [comment]
and why are you putting this in a note script?

**Comment by frantastic24** [comment]
Will never understand how or why closing the fucking game while you're playing is a mechanic

**Comment by tylerandari12** [comment]
I was stumped for a day on this too...
Theres no `wait()` command like in Roblox Studio...

**Comment by PogofruitKM** [comment]
maybe?
removeLuaSprite('fooled')
