### ISSUE TITLE
Making other Image's appear at a certain curBeat Via Lua Script

### ISSUE THREAD

**Issue by neighborduck** [ShadowMario/FNF-PsychEngine#1021]
### What is your question?

so what im trying to do is im trying to add different images show up at a different curBeat this is the whole script LUA

function onCreate() <------ START
    addLuaSprite('MissMe1', false);  
    doTweenAlpha('MissMe1', 'MissMe1', '0', '0.0001', 'linear')  ---image appears but is invisible
end
    

function onBeatHit()
    if curBeat == 15 then   ---fade in
        doTweenAlpha('MissMe1', 'MissMe1', '100', '1', 'linear')
    end
        if curBeat == 25 then   ---fade out
            doTweenAlpha('MissMe1', 'MissMe1', '0', '1', 'linear')
        end
    end <------ FINISH

as of now it shows the image but what I'm trying to get at is how would I add onto this to where it show the rest of the images
at other curBeat

**Comment by ShadowMario** [comment]
What?

**Comment by SrtHero278** [comment]
I think you forgot to make the Lua Sprite in the first place.
