### ISSUE TITLE
Changing and removing the debug key...

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#10217]
### What is your question?

I know you can use `setProperty("debugKeysChart", nil)` to turn off the ability to presss 7...
But how do you turn off the ability to press 8?
(8 is the character editor by the way...)

**Comment by Mastercopper2346** [comment]
`debugKeysCharacter`

**Comment by tylerandari12** [comment]
> `debugKeysCharacter`

Ah thanks :O
