### ISSUE TITLE
function onAnimationLoop(tag)

### ISSUE THREAD

**Issue by EgguMan** [ShadowMario/FNF-PsychEngine#10228]
### What feature do you want to get added on the **base** engine?

a function that triggers on an animation loop

yeah

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
Good idea man

**Comment by frantastic24** [comment]
You could use a timer
