### ISSUE TITLE
Time Bar

### ISSUE THREAD

**Issue by Ultimate57** [ShadowMario/FNF-PsychEngine#10229]
### What feature do you want to get added on the **base** engine?

The ability to center time bar. 

What I mean is when i take the health bar an rename it time bar it would work but it isn't centered.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
Why did you make another issue

**Comment by Ultimate57** [comment]
> It’s already centered

if your talking about the actual time bar then no thats not what I mean

**Comment by frantastic24** [comment]
Can already be done

**Comment by Ultimate57** [comment]
> Can already be done

how do i do it then

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Value-Setting-and-Getting-Functions#setpropertyvariablestring-valuedynamic

**Comment by Ultimate57** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Value-Setting-and-Getting-Functions#setpropertyvariablestring-valuedynamic

does this require me to know how to code

**Comment by frantastic24** [comment]
No it just expects you to have a working braincell

**Comment by Ultimate57** [comment]
> No it just expects you to have a working braincell

bruh

**Comment by frantastic24** [comment]
Now close this

**Comment by Ultimate57** [comment]
> Now close this

cool thanks for no help
