### ISSUE TITLE
Regarding the "Test" Song

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#10225]
### What feature do you want to get added on the **base** engine?

I personally would find it pretty neat, if the **Test song** had a kind of _script already_ inside, **showcasing** a few possibilites, that LUA in FNF:PE is capable off.
Or at least, there could be a demonstration of the **different Events** (and _Note Types_)

But also, this could be _locked away_ in the _own difficulty_ of the test song, whchc would first require to know **_how to make a week_**

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
No

**Comment by Mastercopper2346** [comment]
No

**Comment by Mastercopper2346** [comment]
WTH IT DUPED

**Comment by ShadowMario** [comment]
It's kinda troubling cuz Lua doesn't run on HTML5
