### ISSUE TITLE
change of maximum Health

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#10222]
### What is your question?

Is it currently possible to edit the maximum health? I mean, sure, you can make it smaller, but can you also expand it?
It would be pretty cool for some mods, which have health drain by default, to then make the hp larger, instead of draining less, as you heal too much-

And if it isn't possible now, will it be possible to change it? Like with a variable or lua function?

**Comment by MemeHoovy** [comment]
It's possible through source code, not lua though.
Replace the two next to the zero with three, seen in the picture below.
Before:
![Screenshot 2022-08-17 222011](https://user-images.githubusercontent.com/97995998/185278571-9b4c59fe-cd31-4c53-9568-953f0d900e53.png)
After:
![Screenshot 2022-08-17 222159](https://user-images.githubusercontent.com/97995998/185278743-3c191116-e1ab-4730-bf7c-33c4a7446e2d.png)

**Comment by ZeitHeld** [comment]
Cool that it works-
Though I can't compile source code (my pc simply won't), therefore, it is not as helpful, but thanks!
I'll close it
