### ISSUE TITLE
Bug with something.

### ISSUE THREAD

**Issue by GordoiteYT** [ShadowMario/FNF-PsychEngine#10227]
### Describe your bug here.

I'm currently making a mod, i haven't compiled it (using psych engine build downloaded). but im getting this error.

"C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
FreeplayState.hx (line 377)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/vegeance/vegeance-hard.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng"

what does this mean?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

none, also i havent compiled it?

**Comment by frantastic24** [comment]
Not a bug
Missing chart

**Comment by GordoiteYT** [comment]
> Not a bug Missing chart

might be because I took it from somewhere, thanks for atleast telling me.

**Comment by GordoiteYT** [comment]
> Not a bug Missing chart

but the other songs also bug out.

**Comment by GordoiteYT** [comment]
UPDATE - Fixed the problem. I entered the name wrong because of a misspelling (oops). Thank you @frantastic24 for trying to help.
