### ISSUE TITLE
Combo splash lags on spammy songs

### ISSUE THREAD

**Issue by syskill-the-coder** [ShadowMario/FNF-PsychEngine#10224]
### What feature do you want to get added on the **base** engine?

Make a feature to disable combo splash not just visually, but completely disable counting.
It lags very much and i traced the issue to combo counting.

### To test your sight, and reliability, please select the option of what should NOT be requested.

6k charts, stage editor blah blah

**Comment by frantastic24** [comment]
Try checking options again, there is Hide UI

**Comment by syskill-the-coder** [comment]
> Try checking options again, there is Hide UI

Thats sounds like visual, but ok ill try

**Comment by syskill-the-coder** [comment]
@frantastic24 Nope, dosent work
> not just visually, but completely disable counting.

**Comment by frantastic24** [comment]
It makes the UI not get rendered, if it's lagging then consider investing on a better PC

**Comment by ShadowMario** [comment]
This sounds kinda false cuz it deletes the objects after their alpha tween is completed and my PC runs it fine
