### ISSUE TITLE
Camera Functions - CameraShow()

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#10226]
### What feature do you want to get added on the **base** engine?

I would like to have a kind of command, that lets one undo all the effects of `cameraFade()` and `cameraFlash()`. As of now, that would be a super cool tool and wouldn't require mods to have an image that is literally pitch black or white _(or whatever other color you want to use)_.
It could either just show the chosen camera immediately, or like a reverse way of `cameraFade()`

it would look like this _(can be slightly altered of course)_:

`CameraShow(camera:String, duration:Float)`

Additionally, it would be very nice, if all tween-like events which have a duration of 0, would be instant.

**And this below, is what is available currently, regarding the Camera.**
_(gf as a target is nice too)_

![image](https://user-images.githubusercontent.com/76132257/185237039-0b5883c4-ca02-4c2c-b43b-d7ffb0a76040.png)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
You don't need an image, makeGraphic exists. So do runHaxeCode and doTweenAlpha
A tween with duration of 0 means it's over before it starts, it's intended to not do anything

**Comment by ZeitHeld** [comment]
I don't know how to do HaxeCode, plus it would be, in my opinion too far from Lua only again.
I mean, there is makeGraphic, yeah, but I never really knew what it was before until today.

Plus, if the Camera can Fade, then it should come back as well.
It even would just be a small thing to add probably. small, but fine

**Comment by frantastic24** [comment]
How is it not Lua if it is running through Lua??
And if you're going to keep opening feature request you should at least experiment with what you can and can't do beforehand
