### ISSUE TITLE
Help i have a problem

### ISSUE THREAD

**Issue by vocodexxcalimetalrapha** [ShadowMario/FNF-PsychEngine#10223]
### Describe your problem here.

https://media.discordapp.net/attachments/907118258728095786/1009513451762241578/unknown.png?width=1043&height=586

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by DW-EriccruzYT** [comment]
what you are making??

**Comment by vocodexxcalimetalrapha** [comment]
im making my hog mod

**Comment by vocodexxcalimetalrapha** [comment]
but when i load the song it crashes

**Comment by DW-EriccruzYT** [comment]
mmm probaly needs a xml use a random xml
