### ISSUE TITLE
no voices

### ISSUE THREAD

**Issue by RyanRumble** [ShadowMario/FNF-PsychEngine#1023]
### Describe your bug here.

for some reason, the voices wont play for the songs i add

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

added a new song with inst and voices

**Comment by CrusherMods** [comment]
"Use Voice Track" has to be on the songs in debug menu

**Comment by CrusherMods** [comment]
or something simualar named to that all I know is that something needs to be enabled

**Comment by RyanRumble** [comment]
im so stupid for not looking at this thank you
