### ISSUE TITLE
How can i make a 3rd strum

### ISSUE THREAD

**Issue by Akumalol** [ShadowMario/FNF-PsychEngine#10237]
### Describe your problem here.

how can i do a 3 strum like bonedoggle

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Indie cross source code is public, use that

**Comment by ManMaster707** [comment]
> Indie cross source code is public, use that

where?!?! i crave for that

**Comment by frantastic24** [comment]
google

**Comment by ManMaster707** [comment]
oh thanks

**Comment by MemeHoovy** [comment]
> > Indie cross source code is public, use that
> 
> where?!?! i crave for that

https://github.com/brightfyregit/Indie-Cross-Public

close the issue

**Comment by MemeHoovy** [comment]
> ASS ASS BARF BARF PISS PISS ASS ASS BARF BARF PISS PISS ASS.
> 
> GTFO OUT

![6B3C8EC0-E7AA-4291-B988-202D337C7347](https://user-images.githubusercontent.com/97995998/185726452-2b989f10-8356-4cb9-9680-95f5f9aa9403.jpeg)
