### ISSUE TITLE
Left & RIght Fix for NOT "Playable" Characters as Players

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#10238]
### What feature do you want to get added on the **base** engine?

When people use opponent characters (ex. dad, mom) as players, like some people do for covers or similar, it is easy to forget (or they're too lazy) to switch left and right anims, as these are supposed to look into the other direction.

My suggestion to "fix it" is, to use the "playable" checkmark for that.

if the bf character is NOT a "playable" one, (ex. dad) then animations (& offset) of singLeft & singRight get Swapped. 
so, hitting RIGHTNOTE, will trigger the singLEFT animation in this case

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
duplicate of #8560

**Comment by Mastercopper2346** [comment]
close it now

**Comment by ZeitHeld** [comment]
Relax, I was asleep-

Also, pretty stupid how he said, that it would "break mods" even though it wouldn't technically?

**Comment by frantastic24** [comment]
Yes it would

**Comment by ZeitHeld** [comment]
Reason

**Comment by frantastic24** [comment]
Simple
Characters that are already properly coded end up with this "issue" instead, which would also lead to _more_ "feature" requests to cover for people not doing stuff correctly
Even if it didn't break mods, it's a pointless addition
