### ISSUE TITLE
Script isn't working

### ISSUE THREAD

**Issue by justanundertalefan** [ShadowMario/FNF-PsychEngine#10232]
### Describe your problem here.

The script isn't working.
`function OnCreate()
local Coins = 1;

function OnSongStart()
makeLuaText('Coin counter', (Coins), 1250, 0, 480)
setTextAlignment('Coin counter', 'Center')
addLuaText('Coin counter')
setTextSize('Coin counter', 28)
end
end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by justanundertalefan** [comment]
this happened
`mods/test/data/testsong/script.lua:4: unexpected symbol near '..'`

**Comment by justanundertalefan** [comment]
i changed the script to
`function onCreate()
local Coins = 1;
end
makeLuaText('Coin counter', ..Coins, 400, 500, 500)
setTextAlignment('Coin counter', 'center')
setTextSize('Coin counter', 1000)

function onSongStart()
addLuaText('Coin counter')
end`

**Comment by Parsellol** [comment]
apologies i made a mistake its just ```Coins``` not ```..Coins``` also put
```
makeLuaText('Coin counter', ..Coins, 400, 500, 500)
setTextAlignment('Coin counter', 'center')
setTextSize('Coin counter', 1000)
 ```
under  ```function onSongStart()```

**Comment by Mastercopper2346** [comment]
```lua
local Coins = 1;

function onCreate()
     makeLuaText('Coin counter', ..Coins, 400, 500, 500)
     setTextAlignment('Coin counter', 'center')
     setTextSize('Coin counter', 1000)
end

function onSongStart()
     addLuaText('Coin counter')
end
```
Try this.

**Comment by Parsellol** [comment]
> ```lua
> local Coins = 1;
> 
> function onCreate()
>      makeLuaText('Coin counter', Coins, 400, 500, 500)
>      setTextAlignment('Coin counter', 'center')
>      setTextSize('Coin counter', 1000)
> end
> 
> function onSongStart()
>      addLuaText('Coin counter')
> end
> ```
> 
> Try this.

yeah that should work i think

**Comment by justanundertalefan** [comment]
is there any way to make the variable increase everytime a custom note is hit?

**Comment by h4master** [comment]
local Coins = 1;

function onCreate()
     makeLuaText('Coin counter', 'Coins', 400, 500, 500)
     setTextAlignment('Coin counter', 'center')
     setTextSize('Coin counter', 1000)
end

function onSongStart()
     addLuaText('Coin counter')
end

**Comment by Parsellol** [comment]
> is there any way to make the variable increase everytime a custom note is hit?

```lua
function goodNoteHit(id, direction, noteType, isSustainNote)
	if noteType == "Awesome Note" then
		var = var + 1
	end
end

```
