### ISSUE TITLE
How to get object order of strums?

### ISSUE THREAD

**Issue by KirbyKid256** [ShadowMario/FNF-PsychEngine#10233]
### Describe your problem here.

I'm trying to make a note skin for the strums of a song. And because that skin has more than 5 frames, I need to make it a lua sprite. How would I be able to get the value of the object order of each strum note for both the player and opponent so I can put the new skin directly on top of the old skin?

Please note that I'm working with the pixel notes, not the regular notes. Otherwise this would've been easy.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Mastercopper2346** [comment]
I don’t think you need to

**Comment by KirbyKid256** [comment]
> I don’t think you need to

I forgot to mention that I'm using the pixel notes. So I do need to because there isn't a public variable that changes the height divisor.

**Comment by KirbyKid256** [comment]
Okay. So thanks for nothing. I found out which object to get the object order from. For anyone viewing this and needing this information, it's this: 
`getObjectOrder("strumLineNotes")`
For some reason, none of the other strum notes like opponent and player strums work.
