### ISSUE TITLE
Wavy effect in Wiggle effect

### ISSUE THREAD

**Issue by Warlokk28** [ShadowMario/FNF-PsychEngine#10234]
### Describe your problem here.

HELP ME:( okay so,in fnf i am have "wiggle effect,or just WAVY effect in this site https://haxeflixel.com/demos/BlendModeShaders/ "
can someone help,what the command in stage i am need to use?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ZakyFerdian** [comment]
what version of psych you use?

**Comment by TheKitBoi** [comment]
> what version of psych you use?

6.2 or action builds

**Comment by ZakyFerdian** [comment]
you wanna make 3d background like dnb?

**Comment by Warlokk28** [comment]
i am use 0 5 2

**Comment by Warlokk28** [comment]
> you wanna make 3d background like dnb?

yup

**Comment by CrusherNotDrip** [comment]
> i am use 0 5 2

but we are on 0.6 and above
therefore you have outdated code

**Comment by Warlokk28** [comment]
> > i am use 0 5 2
> 
> but we are on 0.6 and above therefore you have outdated code
then,i am just need the command use in stage

**Comment by YoshiGames64** [comment]
i need it for the letters
