### ISSUE TITLE
Hold notes are broken

### ISSUE THREAD

**Issue by BlazingDragonsYT** [ShadowMario/FNF-PsychEngine#10236]
### Describe your bug here.

The hold notes for me are broken. Every time I add one, when I save and come back to the song I'm charting, the hold note's tail shortens. Why is this happening?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not edit anything.

**Comment by TheKitBoi** [comment]
It’s the same thing as https://github.com/ShadowMario/FNF-PsychEngine/issues/9524
Also what version are you using

**Comment by BlazingDragonsYT** [comment]
I'm not even using Change BPM, they're just broken for me. And I'm using 0.5.2h.

**Comment by TheKitBoi** [comment]
> I'm not even using Change BPM, they're just broken for me. And I'm using 0.5.2h.

Then update to action build that fixes it https://github.com/ShadowMario/FNF-PsychEngine/actions/runs/2864975591
And close the issue
![472E9CBF-F405-406E-998B-3B8A90D4CE4B](https://user-images.githubusercontent.com/84044666/185770751-99338356-e753-4a8a-b407-78339a683f53.jpeg)

**Comment by BlazingDragonsYT** [comment]
That's the EXACT build I'm trying to avoid because of another issue that I put up.

**Comment by frantastic24** [comment]
You're using an old version, close this

**Comment by BlazingDragonsYT** [comment]
Ok, thanks for the help. Wish me luck as 0.6 or 0.6.1 will probably crash as well.

**Comment by BlazingDragonsYT** [comment]
Nope, 0.6 doesn't fix the issue.

**Comment by MemeHoovy** [comment]
quit opening and closing the issue

**Comment by BlazingDragonsYT** [comment]
Sorry, sorry. This issue just isn't being fixed and I can't figure out what to do. The thoughts in my mind are "Should I reopen this?" "Should I make a new one?" "What should I do?" This problem is really getting to me.
