### ISSUE TITLE
PR

### ISSUE THREAD

**Issue by Ultimate57** [ShadowMario/FNF-PsychEngine#10240]
### What is your question?

Whats a pull request

**Comment by Mastercopper2346** [comment]
Someone who wants to add a feature/fix bug, 
**NOW CLOSE**

**Comment by MemeHoovy** [comment]
🤦🏻‍♂️

**Comment by Parsellol** [comment]
> ### What is your question?
> Whats a pull request

why are u asking this here google exists lol

**Comment by CrusherNotDrip** [comment]
**heres a lovely tutorial on how to get questions answered without actually making issues**

https://user-images.githubusercontent.com/90648119/185642672-4b2983c8-ac31-491c-9783-7f030ea3cd32.mp4

**Comment by ShadowMario** [comment]
[https://www.google.com](https://www.google.com)
