### ISSUE TITLE
lua script api

### ISSUE THREAD

**Issue by Yoshi-RBLX** [ShadowMario/FNF-PsychEngine#10249]
### What is your question?

there are lots of files that cant be opened in the lua script api. one of them being the cutscene script. it loads the url but then it says
This site can’t be reached
The webpage at https://cdn.discordapp.com/attachments/840678333602857040/888568130283139082/bopeeboTestVideo.zip might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

im thinking maybe the link was deleted, so can you guys please upload new links?

**Comment by ADuckInBlack** [comment]
> **it's because it is deleted dumbass**

i mean, you could've been a little more polite about it

**Comment by dtgaming5737** [comment]
same thing for me

**Comment by dtgaming5737** [comment]
same thing for me

**Comment by Yoshi-RBLX** [comment]
> **it's because it is deleted dumbass**

ik it's deleted, that's why my question is upload new links
obviously -_-
