### ISSUE TITLE
About GameOver voice lines.

### ISSUE THREAD

**Issue by Lag0sEra** [ShadowMario/FNF-PsychEngine#10244]
### What is your question?

Is there any chance that some LUA script exists for audio files to play on death in 0.6.2?
Everything else I've researched is outdated.

**Comment by Parsellol** [comment]
```
local line

function onGameOverStart()
    line = getRandomInt(1, 11)
   playSound("FleetLines/" ..line, 1)
end
 ```
u will have to edit it a bit but something like this

**Comment by FlintIshe** [comment]
### here
```ruby
math.randomseed(os.time())
local sound = math.random(1, 6);
playSound(sound, 2) 

```

### and also rename your audio file to number 1 to 6

**Comment by Shaggers-official** [comment]
Is there a way to do it non-randomised ? Like, when the player died the first time it plays the audio "1", if the player died twice, it plays the audio "2", etc...

**Comment by Mokona5901** [comment]
I know there is a variable that counts the number of deaths (yn when you pause the game) but I don't know where to find it.

**Comment by EpicShapeShifter** [comment]
local randomNumber = math.random(1,10)
local soundDirectory = 'STRING'
playSound(soundDirectory..'SOUNDNAME'..tostring(randomNumber), 1)

**Comment by EpicShapeShifter** [comment]
Also the variable for deaths is:     getProperty('deathCounter');

**Comment by Parsellol** [comment]
has the issue been solved?
