### ISSUE TITLE
Get Monitor Resolution

### ISSUE THREAD

**Issue by gghj678910** [ShadowMario/FNF-PsychEngine#10245]
### Describe your problem here.

How to get monitor resolution with Lua? Please help.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheKitBoi** [comment]
so are you referencing the change resolution script
or something else

**Comment by TFLTV** [comment]
> so are you referencing the change resolution script or something else

He is talking about the current resolution of the monitor (not the game)
![image](https://user-images.githubusercontent.com/105890618/185726580-976614c8-03fc-46a2-ab39-57a2676dca68.png)

**Comment by gghj678910** [comment]
> > so are you referencing the change resolution script or something else
> 
> He is talking about the current resolution of the monitor (not the game) ![image](https://user-images.githubusercontent.com/105890618/185726580-976614c8-03fc-46a2-ab39-57a2676dca68.png)

Yup!
