### ISSUE TITLE
dialogue after cutscene without the countdown starting before

### ISSUE THREAD

**Issue by HiroOfc** [ShadowMario/FNF-PsychEngine#1024]
### Describe your problem here.

i was trying to add a dialogue after a cutscene, but, when the custcene is over, the song starts while the dialogue starts
i wanna know how to fix it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yeah sure, i added lines at PlayState.hx to make the dialogue and cutscene play

**Comment by HiroOfc** [comment]
forgot to mention something:
the dialogue starts while cutscene starts too lol

**Comment by NotEpik** [comment]
idk

**Comment by MayoALT** [comment]
if its the second song in a week then you can make the cutscene play at the end of the second song

**Comment by HiroOfc** [comment]
> if its the second song in a week then you can make the cutscene play at the end of the second song

nah, the dialogue and cutscene stays at the first song, idk how to solve it

**Comment by VicDash78** [comment]
So, video cutscene and then dialogue? i cant code haxe but if your build supports lua then [this script](https://github.com/ShadowMario/FNF-PsychEngine/files/7581236/funny.txt) might help (taken from gboard) (make sure to save it as a lua and save it to your song's data folder)

**Comment by HiroOfc** [comment]
> So, video cutscene and then dialogue? i cant code haxe but if your build supports lua then [this script](https://github.com/ShadowMario/FNF-PsychEngine/files/7581236/funny.txt) might help (taken from gboard) (make sure to save it as a lua and save it to your song's data folder)

o yeaa, thank u
