### ISSUE TITLE
They need to fix this!

### ISSUE THREAD

**Issue by Tamir-YT** [ShadowMario/FNF-PsychEngine#10246]
### Describe your bug here.

Hello i got this error

Paths.hx (line 352)
BGSprite.hx (line 24)
PlayState.hx (line 534)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

please fix this at the next update

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by FlintIshe** [comment]
be more specific , where did you get the error? entering the song or smth

**Comment by frantastic24** [comment]
Not a bug
Missing week 3 stage textures

**Comment by Mastercopper2346** [comment]
> Not a bug
> Missing week 3 stage textures

Ye I was about to say missing image

**Comment by Tamir-YT** [comment]
> be more specific , where did you get the error? entering the song or smth

yea i was entering the song

**Comment by frantastic24** [comment]
you are missing game files, close the issue

**Comment by TheKitBoi** [comment]
Close the issue
![Uploading D99B1A60-8A47-4D47-AD96-D3F6A208CC10.jpeg…]()

**Comment by TheKitBoi** [comment]
Close the issue
![7F8A7641-EDE4-4AF8-A04C-D980082DFC56](https://user-images.githubusercontent.com/84044666/185767753-9737fa3a-e1d8-4472-aba7-147ac5f3ff1b.jpeg)
