### ISSUE TITLE
Splash Notes

### ISSUE THREAD

**Issue by Ultimate57** [ShadowMario/FNF-PsychEngine#10241]
### What feature do you want to get added on the **base** engine?

Make smaller splash notes.

The ones we have are so big their distracting.

I usually just turn them off. 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
He won’t

**Comment by Mastercopper2346** [comment]
Plus it’s supposed to go around the note, defeating the purpose of it.

**Comment by frantastic24** [comment]
Skill issue

**Comment by CrusherNotDrip** [comment]
> The ones we have are so big their distracting.

They are splashes what the hell do you expect
of course its gonna be a little bit distracting
either way you can modify the splashes inside the spritesheet if they are really that big

**Comment by MemeHoovy** [comment]
> > The ones we have are so big their distracting.
> 
> They are splashes what the hell do you expect of course its gonna be a little bit distracting either way you can modify the splashes inside the spritesheet if they are really that big

not to mention, you can literally turn off the notesplashes
