### ISSUE TITLE
custom character not reading

### ISSUE THREAD

**Issue by ColdlordXRepositories** [ShadowMario/FNF-PsychEngine#10247]
### Describe your problem here.

![bf-worse_assets](https://user-images.githubusercontent.com/49921877/185640166-b973e656-17b1-4129-8db7-34cab0c75a1b.png)
<?xml version='1.0' encoding='utf-8'?>
<TextureAtlas imagePath="bf-worse_assets.png">
<SubTexture name="bf worse idle0000" x="280" y="246" width="152" height="233" frameX="0" frameY="0" frameWidth="152" frameHeight="233" />
<SubTexture name="bf worse idle0001" x="0" y="246" width="153" height="235" frameX="0" frameY="0" frameWidth="153" frameHeight="235" />
<SubTexture name="bf worse idle0002" x="304" y="0" width="172" height="237" frameX="0" frameY="0" frameWidth="172" frameHeight="237" />
<SubTexture name="bf worse idle0003" x="0" y="246" width="153" height="235" frameX="0" frameY="0" frameWidth="153" frameHeight="235" />
<SubTexture name="bf worse left0000" x="432" y="246" width="148" height="233" frameX="0" frameY="0" frameWidth="148" frameHeight="233" />
<SubTexture name="bf worse left0001" x="653" y="0" width="149" height="233" frameX="0" frameY="0" frameWidth="149" frameHeight="233" />
<SubTexture name="bf worse down0000" x="177" y="0" width="127" height="240" frameX="0" frameY="0" frameWidth="127" frameHeight="240" />
<SubTexture name="bf worse down0001" x="153" y="246" width="127" height="235" frameX="0" frameY="0" frameWidth="127" frameHeight="235" />
<SubTexture name="bf worse up0000" x="476" y="0" width="177" height="237" frameX="0" frameY="0" frameWidth="177" frameHeight="237" />
<SubTexture name="bf worse up0001" x="0" y="0" width="177" height="246" frameX="0" frameY="0" frameWidth="177" frameHeight="246" />
<SubTexture name="bf worse right0000" x="0" y="481" width="173" height="233" frameX="0" frameY="0" frameWidth="173" frameHeight="233" />
<SubTexture name="bf worse right0001" x="173" y="481" width="176" height="233" frameX="0" frameY="0" frameWidth="176" frameHeight="233" />
</TextureAtlas>
I did everything on the tutorial, and the character isnt reading.
![Friday Night Funkin'_ Psych Engine 8_19_2022 10_27_42 AM](https://user-images.githubusercontent.com/49921877/185640917-35dc8234-c7ff-4274-9dc1-b13e9cc0188d.png)
![Friday Night Funkin'_ Psych Engine 8_19_2022 10_28_02 AM](https://user-images.githubusercontent.com/49921877/185640974-4fb21055-9dbd-4575-bf0e-036b64ff2c01.png)
tips? im making fnf but worse.
Edit: github is weird and not letting the  second set of images display

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

added stuff for a custom character

**Comment by Mokona5901** [comment]
I had same problem, make sure in Animation tab the "Animation on .XML/.TXT file" is the same in the XML (I mean if in the xml the first sprite name of the pose is bf worse idle0000, you need to type bf worse idle in the text box)

**Comment by ColdlordXRepositories** [comment]
> I had same problem, make sure in Animation tab the "Animation on .XML/.TXT file" is the same in the XML (I mean if in the xml the first sprite name of the pose is 'bf worse idle0000', you need to type 'bf worse idle' in the text box)

I did that and the character just didn't appear, it stayed as regular bf.

**Comment by Mastercopper2346** [comment]
Make sure char path is characters/[char name] and image and xml is in mods/images/characters or assets/shared/images/characters
