### ISSUE TITLE
Help Me Guys #1

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10253]
### Describe your problem here.

My Code On MainMenuState For The Animated Background Working, But It's Still Showing The HaxeFlixel Mini Logo On The Center, But I Don't Have Image. Can You Help Me?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

Just Trying To Make The Animated Background On MainMenuState

**Comment by Mastercopper2346** [comment]
You need the image or else there will be a haxeflixel logo

**Comment by StefanBETA2008** [comment]
> You need the image or else there will be a haxeflixel logo

Nevermind, Im Fixed
