### ISSUE TITLE
how do i use shaders

### ISSUE THREAD

**Issue by RubenDatOneBoi3446** [ShadowMario/FNF-PsychEngine#10251]
### Describe your problem here.

i have no idea how to use shaders except for putting the frag files in the shaders file

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
```lua
setSpriteShader(object, shader)

removeSpriteShader(object)
```

**Comment by RubenDatOneBoi3446** [comment]
for like the whole moment of the song too but thanks

**Comment by RubenDatOneBoi3446** [comment]
wait-

**Comment by frantastic24** [comment]
You can close this
