### ISSUE TITLE
How do i use lua on psych

### ISSUE THREAD

**Issue by MugMiles** [ShadowMario/FNF-PsychEngine#10258]
### Describe your problem here.

Hi, I have no experience coding, what is an lua and how do i use it to mod in psych?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Meme1079** [comment]
Lua is a programming language that is easy to use, if you want learn the basic click [here](https://github.com/Meme1079/PsychWiki/wiki/Lua-Script-API:-Basics-of-Coding). And to use it put it on a `scripts`, `stages`, `data/songname`, `custom_notetype`, or `custom_events` folder.
