### ISSUE TITLE
More Features

### ISSUE THREAD

**Issue by CC-J4xon** [ShadowMario/FNF-PsychEngine#1025]
### **_MORE BEGINNER SUPPORT FOR ADDING BACKGROUNDS:_**

I Have Never Made An FNF Mod Before, But I Really Want To Make One.
I Am Using Psyche Engine And Psyche Makes It Easier To Make FNF Mods Than Kade Engine, But There Is One Thing That I Find Hard For Beginners (Like Me) To Do.
Adding Custom Backgrounds.
Can You Please Add A New Folder In ''mods/images'' Called ''backgrounds'' (Also Add One For The JSON File In ''mods'' Called ''backgrounds'').

### **_NOTE VARIETY:_**

In The Bob And Bosip Mod, Each Of The Different Characters Have Different Note Colours, Can You Add In Another Folder In ''mods/images'' Called ''noteskins''.
It Would Also Work As Another Place To Put The Normal Icons, Hurt Notes And Custom Note Image Files.
When Anyone Has A Custom Note Skin, It Automatcally Disables The Custom Note Colour You Equipped In The ''Note'' Menu In The ''Settings Tab''.
The Custom Note Skin Would Be Equipped With A New Event (My Next Idea), But It Cannot Be Equipped Any Other Way.
If This Gets Added Into Psyche Engine, It Would Work Really Well With My Next Idea:

### **_THE ARROW POSITION EVENT:_**

I Do Not Know How To Code In Custom Events, So My Idea Is The ''Arrow Position'' Event.
Like In The Song ''Missingno'' From Hypno's Lulliby The ''Arrow Position'' Event Would Allow You To Move And Rotate The Player (And Enemy's Arrows Too). It Would Work Like This Once You Have Selected It In The Events Tab:

Value 1:
Value 2:
Value 3:
Value 4:
Value 5:
Value 6:

Value 1 Would Be Who's Arrows You Would Like To Change
Value 2 Would Be The Note Sprites (From My First Idea) It Has To Remove The Custom Arrow Colour Though (But It Will Be A Very Big Help For The Mod That I Am Working On)
Value 3, 4, 5 And 6 Will Be The Arrows, Here Is An Example (9, 03, 0.6, 8) The First Number  Would Be The ''X'' Position, The Second Number Would Be The ''Y'' Position, The Third Number Would Be The ''X'' Rotation And The Fourth Number Would Be The ''Y'' Rotation.
If You Make A Value A Positive Number It Would Be On A Different Side Of The Arena To A Value With A Negative Number.

### **_TWO NEW EVENTS:_**

_**EVENT 1, THE BACKGROUND EVENT**_

My First Idea Was To Put Backgrounds In A Folder Called ''backgrounds'' In ''mods/images'' (And ''mods'') And Choose Each Song's Background With The ''Freeplay'' Menu Once You Are In The ''Week Editor'' Menu.
But This First Event Changes The Background To A Different One While You Are Hitting Notes.
It Will Be Called The ''Background Event''.
You Will Access It The Same Way You Access Normal Custom Events, But This Will Only Have One Value.
It Will Look Like This:

Value 1:

Value 1 Is Where You Type The Name Of The Background Asset You Want To Switch To, (Leave It Blank For The Default One The Song Started With.)

_**EVENT 2, THE HEALTH EVENT**_

The Second New Event Is Similar To What Happens In The Tabi Mod In The Song ''6enocide'' (6 = G, I Wanted To Keep It Family Friendly).
Tabi Drains BF's Health Over Time.
Well, My Idea Is The ''Health Event''.
It Would Look Like This:

Value 1:
Value 2:
Value 3:
Value 4:

Value 1 Is How Much Health The Player Will Stop At, For Example 0 Would Be At The Lowest Health And 100 Would Be At The Max Health.
Value 2 Is If The Player Gains Or Loses Heath (You Would Type either ''Gain'' or ''Lose'').
Value 3 Is How Much The Player Will Gain Or Lose Per Second.
And Value 4 Is Whether It Should Kill The Player Or Not.
(If You Keep All Of Those Blank, It Sets It Back To Normal FNF Health Mechanics)

### **_SOME EXTRA STUFF I WOULD LIKE TO BE ADDED, BUT ARE NEVER GOING TO BE ADDED:_**

_**THE KEYS EVENT**_

5, 6, 7, 8 Or 9 Key Support Would Be Great, I Would Add Them Though Custom Event.
It Would Be Called The ''Keys'' Event
Here Is What The Custom Event Would Look Like:

Value 1:
Value 2:
Value 3:
Value 4:
Value 5:
Value 6:
Value 7:
Value 8:
Value 9:
Value 10:

Value 1, 2, 3 And 4 Are The Default Keys.
Value 5 Adds A Space Bar Button In Between The Up Arrow (W) And The Down Arrow (S)
Value 6 Is 6 Key Shaggy
Value 7 Is 6 Key Shaggy With A Space Bar Button In The Middle Of The Arrows
Value 8 Is 9 Key Shaggy Without Space Bar
Value 9 Is 9 Key Shaggy
Value 10 Is The Character You Want To Have These Specific Notes
If You Set The Values Blank, It Doesn't Add Them
If Value 10 Is Blank, It Resets To The Default Keys
(Paired Together With The ''Arrow Position'' Event, You Can Move BF's Arrows To The Upper Middle Of The Screen And Hide The Opponent's Arrows And Make A Short-Term Defeat Scenario And Then Move The Arrows Back To Normal)

_**EXTRA SECRET SONGS**_

You Have To Do A Precise Combination To Get To Missingno's Song In Hypno's Lulliby, What If You Add That To Psyche Engine?
When You Press ''7'' On The Main Menu, It Takes You To A Debug Mode.
Why Not Add It There?
I Don't Have Any More Ideas For This Concept Though
:(

### **THANK YOU:**

Thank You For Reading This, I Worked Hard Writing All Of This Down.
If You Add Any Of My Ideas, Thank You It Means A Lot
Psyche Engine Is The Best Engine Ever!
:)

**Comment by HiroOfc** [comment]
bro, this will probably be closed by something you've written, like the extra keys, cuz ShadowMario already said that this feature will not be official to the engine

**Comment by ShadowMario** [comment]
Beautiful how you're blind to not notice this
![Screenshot_2](https://user-images.githubusercontent.com/44785097/141889129-ecaa736d-4e1b-4af3-a23f-5116b53e0b05.png)

**Comment by CC-J4xon** [comment]
I Did Notice It, I Said It Was Not Going To Be Added
![keys](https://user-images.githubusercontent.com/94282827/145445662-f6705f9b-5369-4f12-9f91-62935a0bb89b.PNG)
