### ISSUE TITLE
Number 1 in value 1 while using the event: Change Character

### ISSUE THREAD

**Issue by NewSajgonki** [ShadowMario/FNF-PsychEngine#10259]
### Describe your bug here.

Pressing "1" in value 1 while using the event "Change Character" causes the game to crash and its a "Null Object Refrence"? Idk about that

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, Except putting new bf and sonic into it with GF with .JSON file for them and no bg but even without a BG it worked well, while entering the song

**Comment by NewSajgonki** [comment]
Also to avoid the bug is first adding the character to change from to (ex.: Dad (1 | value 1) Mom (mom | value 2)

**Comment by wubbzyfan** [comment]
The numbers don’t work now, it’s “dad”, “bf”, and “gf” (or “girlfriend” I’m not entirely sure)
