### ISSUE TITLE
Tween on Game Over

### ISSUE THREAD

**Issue by Shaggers-official** [ShadowMario/FNF-PsychEngine#10255]
### Describe your problem here.

Hey, so i'm making a mod and i want bf to fall into an abyss on the game over screen but i don't want to animate it as a BF animation but rather code the fall. I tried to getProperty('GameOverSubstate') or 'bf' or 'boyfriend' or anything like that, nothing worked :(

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
`function onGameOverStart()`

**Comment by Shaggers-official** [comment]
oh, i didn't know that existed, thank you, maybe i didn't looked at the API close enough
