### ISSUE TITLE
Can we change the mouse asset ?

### ISSUE THREAD

**Issue by Shaggers-official** [ShadowMario/FNF-PsychEngine#10256]
### What is your question?

Hello, i would to replace the mouse sprite like srPerez did in Shaggy x Matt, is there actually a way to do it in Psych ? (in Lua by preferance, but if it requires the Source Code i'm okay with it). Thanks in advance

**Comment by TheKitBoi** [comment]
function onCreate()
    precacheImage('cursor-image-here')
    makeLuaSprite('Cursor','cursor-image-here',getMouseX('other'),getMouseY('other'))
    setObjectCamera('Cursor','other')
    addLuaSprite('Cursor',true)
end

function onUpdate()
    setPropertyFromClass('flixel.FlxG','mouse.visible',false)
    setProperty('Cursor.x',getMouseX('other'))
    setProperty('Cursor.y',getMouseY('other'))
end

copy and paste this script in a CursorChange.lua and edit the cursor-image-here with the image it needs

**Comment by Shaggers-official** [comment]
Awesome, thank you so much !
