### ISSUE TITLE
Unrandomized Death Quotes ?

### ISSUE THREAD

**Issue by Shaggers-official** [ShadowMario/FNF-PsychEngine#10267]
### What is your question?

Is there a way to do a non-randomised death quotes that, when the player died for the first time, it plays the audio "1", if the player died twice, it plays the audio "2", etc...

**Comment by LilMewo** [comment]
honest either u gotta have source code and a knowledge of haxe or just norma and a knowledge of lua idk

**Comment by Shaggers-official** [comment]
I use Lua

**Comment by Shaggers-official** [comment]
I'm just dumb, i don't know how to code so well, i understand the language but i can't speak the language, if you get what i mean...

**Comment by Lorekeeper49** [comment]
I think there is a blueballed variable that you can use in Lua, it's usually shown at the top right corner of the pause screen

**Comment by Parsellol** [comment]
```lua
function onGameOverStart()
    if deathCounter == 1 then
        playSound("fuck1")
    end
    if deathCounter == 2 then
        playSound("fuck2")
        -- and so on
    end
end
````
didnt test so idk if this will work but give it a try

**Comment by Lorekeeper49** [comment]
> ```lua
> function onGameOverStart()
>     if deathCounter == 1 then
>         playSound("fuck1")
>     end
>     if deathCounter == 2 then
>         playSound("fuck2")
>         -- and so on
>     end
> end
> ````
> didnt test so idk if this will work but give it a try

Better way of doing this:
```lua
function onGameOverStart()
    playSound('fuck' .. deathCounter);
end
````

**Comment by Shaggers-official** [comment]
Alright thanks
