### ISSUE TITLE
How to make stun note in psych engine

### ISSUE THREAD

**Issue by Nemophyya** [ShadowMario/FNF-PsychEngine#10263]
### What is your question?

First of all, I am Japanese, so my English is not very good. (I write using a translator)

I am a member of a mod production team, and we have an idea to create a note that will be inoperable for a certain period of time when pressed.
I know some things about lua, but I don't know how to intentionally make it inoperable for a certain period of time.

Please help me.(or us)

**Comment by Mastercopper2346** [comment]
tProperty('boyfriend.stunned', true); を使用します。
良いノートヒットまたはノートミスの下で

**Comment by Nemophyya** [comment]
At least I succeeded in stun.
How can I make this continue only for a certain period of time and then become operational?
I want it to last only a second or two, where do I add the timer?

**Comment by Gostar64** [comment]
put what's below in the goodNoteHit function (make sure the timer is in the check for the specific note type)
```Lua
   runTimer('deactivate', 2)
```
then add at the bottom of the note type script
```Lua
function onTimerCompleted(tag, loops, loopsLeft)
      if tag == 'deactivate' then
             setProperty('boyfriend.stunned', false);
      end
end
```

**Comment by Nemophyya** [comment]
ok it worked
Thank you!!

**Comment by Nemophyya** [comment]
I reopened it because I forgot one thing.
When combined with a dodge event with the space bar, the space bar is still functioning during the stun.
Is there any way to make the space bar not work as well?

**Comment by Parsellol** [comment]
> I reopened it because I forgot things. When combined with a dodge event with the space bar, the space bar is still functioning during the stun. Is there any way to make the space bar not work as well? Also, is there any way to not have the miss animation during the stun?

i think its probably because ur space bar timer dosent have a tag so its triggered everytime ```function onTimerCompleted()``` is triggered

**Comment by Nemophyya** [comment]
ok so please elaborate

**Comment by wubbzyfan** [comment]
personally, how I would do it is by having it set a variable (that’s set to true onCreate) to false and setting it back to true on the end of the timer, and having the space thing require the variable to be true to continue, with a “if (variable) == true then” 

If the space bar thing is in a different thing from the stun notes, just make it so that in the space thing, there’s the timer stuff and on hit stuff from the stun notes, so the timer works there too

**Comment by Nemophyya** [comment]
I tried everything I could, but I couldn't figure it out.
Can anyone provide a detailed code? I am not very familiar with programming.

**Comment by frantastic24** [comment]
Just make a check if boyfriend is stunned or not

**Comment by Nemophyya** [comment]
hmmm then is it possible to set the target key for boyfriend.stunned?

**Comment by frantastic24** [comment]
Not sure what you mean

**Comment by Nemophyya** [comment]
Sorry for my lack of English.
Is it possible to customize the key of boyfriend.stunned?
If it is impossible, I would like to know more about how to set up stun note in lua.
Or you can tell us how to do it by source code.
