### ISSUE TITLE
Texture Atlas Adobe Animate 2021/2022 support

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#10268]
### What feature do you want to get added on the **base** engine?

So pretty much I would like to have a support for texture atlases from newer versions of Adobe Animate. A documentation for them would also be useful to add then.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
Do it for me in a way that doesn't suck then cuz i have no fucking idea how to do it 👍
