### ISSUE TITLE
Moving the notes

### ISSUE THREAD

**Issue by SomeRandomGuyHere** [ShadowMario/FNF-PsychEngine#1026]
### Describe your problem here.

I'm trying to make the notes move just like in the Dave & Bambi cheating song for a port but the notes don't move and doesn't repeat.
Cheating: https://www.youtube.com/watch?v=em-87F0UL-w

`function onSongStart()`
`	repeat`
`		noteTweenX('red', 4, 500, 4, 'quartInOut');`
`		noteTweenX('blue', 5, 550, 4, 'quartInOut');`
`		noteTweenX('green', 6, 600, 4, 'quartInOut');`
`		noteTweenX('purple', 7, 650, 4, 'quartInOut');`
`		wait(4)`
`		noteTweenX('red2', 0, 800, 4, 'quartInOut');`
`		noteTweenX('blue2', 1, 920, 4, 'quartInOut');`
`		noteTweenX('green2', 2, 1040, 4, 'quartInOut');`
`		noteTweenX('purple2', 3, 1160, 4, 'quartInOut');`
`		wait(4)`
`	until(curStep == 1599)`
`end`
edit: i forgot to fix the song start but the notes dont move back
![image](https://user-images.githubusercontent.com/94274443/141674799-1e08fb4b-ed4a-4c45-aae7-7d294898b3e6.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only edited the build for another difficulty and achivements

**Comment by Reycko** [comment]
Try using `onCreate()` instead of `onSongStart()`

**Comment by DEV-idiotXD** [comment]
did u read the wiki?

0 - 3 opponent receptors / strums

4 - 7 player receptors / strums

replace the color names with these


@ShadowMario ya knw what to do

**Comment by SomeRandomGuyHere** [comment]
oh yeah i forgot to change the 0, 1, 2, 3 to 4, 5, 6, 7 but it still doesnt move back

**Comment by DEV-idiotXD** [comment]
> oh yeah i forgot to change the 0, 1, 2, 3 to 4, 5, 6, 7 but it still doesnt move back

the tween cannot tween at the same time it does it one at a time in the order top to bottom
put this

pos = 0
bobinglimit = 10
speed = 10
bobbing = pos + bobinglimit * math.cos(var - 3 * speed)

then make a tween spcipt with a duration of 0.001 and use linear

noteTweenX(0, 0, defaultPlayerStrumX0 + bobbing, 0.001, 'linear')

then continue from 0 to 7 (make sure to make the tag different or it wont work atleast with my experience using tweens)

if this works then close it
[Script.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7535549/Script.txt)


if ya didnt understand then just use the file attached


variable instructions

pos : it is the starting point of the bobbing thing
bobinglimit : limit of how far the bobbing can go
speed : how fast u want it to bob

(rename the .txt part of the file to .lua cuz github doesnt support .lua files XD)

**Comment by DEV-idiotXD** [comment]
> oh yeah i forgot to change the 0, 1, 2, 3 to 4, 5, 6, 7 but it still doesnt move back

the tween cannot tween at the same time it does it one at a time in the order top to bottom
put this

pos = 0
bobinglimit = 10
speed = 10
bobbing = pos + bobinglimit * math.cos(var - 3 * speed)

then make a tween spcipt with a duration of 0.001 and use linear

noteTweenX(0, 0, defaultPlayerStrumX0 + bobbing, 0.001, 'linear')

then continue from 0 to 7 (make sure to make the tag different or it wont work atleast with my experience using tweens)

if this works then close it
[Script.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7535549/Script.txt)


if ya didnt understand then just use the file attached


variable instructions

pos : it is the starting point of the bobbing thing
bobinglimit : limit of how far the bobbing can go
speed : how fast u want it to bob

(rename the .txt part of the file to .lua
[Script.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7535564/Script.txt)
 cuz github doesnt support .lua files XD)

**Comment by MarkToonsHD** [comment]
Here's a script from the Issues tab I used on my version on cheating. I don't know where the question is anymore, though, so I can't provide a link :\

function onUpdate(elapsed)
	if curStep >= 0 and curStep < 2560 then
		songPos = getSongPosition()
		local currentBeat = (songPos/5000)*(curBpm/60)
		noteTweenX(defaultPlayerStrumX0, 4, defaultPlayerStrumX0 + 0*math.sin((currentBeat+10*0.25)*math.pi), 0.5)
		noteTweenX(defaultPlayerStrumX1, 5, defaultPlayerStrumX1 + 250*math.sin((currentBeat+10*0.25)*math.pi), 0.5)
		noteTweenX(defaultPlayerStrumX2, 6, defaultPlayerStrumX2 + 0*math.sin((currentBeat+10*0.25)*math.pi), 0.5)
		noteTweenX(defaultPlayerStrumX3, 7, defaultPlayerStrumX3 + 250*math.sin((currentBeat+10*0.25)*math.pi), 0.5)

		noteTweenX(defaultOpponentStrumX0, 0, defaultOpponentStrumX0 - 250*math.sin((currentBeat+10*0.25)*math.pi), 0.5)
		noteTweenX(defaultOpponentStrumX1, 1, defaultOpponentStrumX1 - 0*math.sin((currentBeat+10*0.25)*math.pi), 0.5)
		noteTweenX(defaultOpponentStrumX2, 2, defaultOpponentStrumX2 - 250*math.sin((currentBeat+10*0.25)*math.pi), 0.5)
		noteTweenX(defaultOpponentStrumX3, 3, defaultOpponentStrumX3 - 0*math.sin((currentBeat+10*0.25)*math.pi), 0.5)

	end
end

**Comment by SomeRandomGuyHere** [comment]
the code was kinda broken but when i fixed it, it was working

**Comment by Reycko** [comment]
can you give me the fixed version ? @SomeRandomGuyHere
