### ISSUE TITLE
Arrow doesn't match with the editor

### ISSUE THREAD

**Issue by NewSajgonki** [ShadowMario/FNF-PsychEngine#10262]
### Describe your bug here.

This arrow doesn't care. It just goes out
![image](https://user-images.githubusercontent.com/108466805/185785732-af241794-dba3-4ddc-abc0-0c4735fc308e.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, apsolutely nothing

**Comment by Mastercopper2346** [comment]
If you changed bpm, then it’s gonna do that.
If you changed beats per section, it does that and is a bug.

**Comment by tylerandari12** [comment]
That arrow said "Im outta here"...

**Comment by TheKitBoi** [comment]
> If you changed bpm, then it’s gonna do that. If you changed beats per section, it does that and is a bug.

thats a refrence to my issues thats closed https://github.com/ShadowMario/FNF-PsychEngine/issues/9524
