### ISSUE TITLE
Event selection

### ISSUE THREAD

**Issue by NewSajgonki** [ShadowMario/FNF-PsychEngine#10260]
### What feature do you want to get added on the **base** engine?

I want @ShadowMario to add like a "event selection" where you select events with a spesific event (ex.: selected: Screen Shake), and then you can change their values (ex.: old: value 1: 1,0.05 | value 2: 1,0.05) [Im tired of scrolling down yeah im lazy lol]

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by DisIsNOt** [comment]
Wdym it's already there

**Comment by TheKitBoi** [comment]
> ### What feature do you want to get added on the **base** engine?
> I want @ShadowMario to add like a "event selection" where you select events with a spesific event (ex.: selected: Screen Shake), and then you can change their values (ex.: old: value 1: 1,0.05 | value 2: 1,0.05) [Im tired of scrolling down yeah im lazy lol]

Charting mode exists
So close this
![2BE80F4F-9E39-45AF-AC3D-A389268BEE0E](https://user-images.githubusercontent.com/84044666/185795538-5e17ee34-73d6-49e8-9d84-c381d8d34923.jpeg)

**Comment by CrusherNotDrip** [comment]
1. failed test
2. already possible
close this
