### ISSUE TITLE
get functions to play in an order

### ISSUE THREAD

**Issue by qvilligan** [ShadowMario/FNF-PsychEngine#10271]
### Describe your problem here.

just that. i am wanting to have a series of a character's anims play once each one is done.

Ex.
		characterPlayAnim('croc','1k', false)
		----then once completed, the next plays
		characterPlayAnim('croc','2k', false)
		----and so on 
		characterPlayAnim('boo','3k', false)
		
		
		

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Use timers or time it with your chart

**Comment by NS-Unfair** [comment]
Or, you could use getProperty to do what you want to do (which is better if you want it timed perfectly.) You could use this snippet to use in your Lua script.
`
-- Replace "[character]" with "girlfriend", "boyfriend", "dad," or some other hard-coded character you added
getProperty('[character].animation.finished')
-- ^^^ Returns true if the current animation is finished, false if not.
`

**Comment by NS-Unfair** [comment]
If that doesn't work for some reason, you can take a look at [this](https://api.haxeflixel.com/flixel/animation/FlxAnimationController.html) to figure out a solution to your problem. It contains documentation for the HaxeFlixel FlxSprite, which is what the FNF character is extended from.

**Comment by frantastic24** [comment]
You can still have it perfectly timed even with a timer, and on top of that you don't have code running every frame
