### ISSUE TITLE
Updates for Selected Objects Persists through Pause in Lua

### ISSUE THREAD

**Issue by KirbyKid256** [ShadowMario/FNF-PsychEngine#10276]
### What feature do you want to get added on the **base** engine?

Since there's a new update that allows people to create a custom substate and pause the game, it might be useful to add code that allows selected objects to update while the game is paused for both custom substates and the default paused game.
Also, I just noticed that sometimes, when pauseGame is true, it doesn't actually pause the game. It just pauses the visuals.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
that's not how haxe states work
