### ISSUE TITLE
Presence or absence of health drain by difficulty

### ISSUE THREAD

**Issue by Nemophyya** [ShadowMario/FNF-PsychEngine#10275]
### What is your question?

Another.

How do I set up the presence or absence of health drain by difficulty?
Either lua or source code is fine. (If possible, lua is easier to work with.)

**Comment by frantastic24** [comment]
```lua
if difficulty == number then
```

**Comment by Gostar64** [comment]
or if you want it to not be on a certain difficulty you could do
```Lua
if difficulty ~= number then
```

**Comment by Nemophyya** [comment]
How and where should I write?

```
function opponentNoteHit()
       health = getProperty('health')
    if getProperty('health') > 0.1 then
       setProperty('health', health- 0.016);
	end
end
```

**Comment by frantastic24** [comment]
Inside the function and before all the code

**Comment by Nemophyya** [comment]
I tried, but couldn't do it.
Do I need something else, or is there something wrong somewhere?

```
function opponentNoteHit()
if difficulty == number then
       health = getProperty('health')
    if getProperty('health') > 0.1 then
       setProperty('health', health- 0.016);
	end
end
end
```

**Comment by frantastic24** [comment]
You are supposed to change number

**Comment by Gostar64** [comment]
The base difficulty numbers are (0 = Easy, 1 = Normal, 2= Hard)

**Comment by Nemophyya** [comment]
Hmm I don't know
I am not using numbers because I want to use custom difficulty.
```
function opponentNoteHit()
if difficulty == ("veryhard") then
       health = getProperty('health')
    if getProperty('health') > 0.1 then
       setProperty('health', health- 0.016);
	end
end
end
```

**Comment by frantastic24** [comment]
It works with custom difficulties, the number is the order of the difficulty

**Comment by Nemophyya** [comment]
It worked! Thank you!

**Comment by Nemophyya** [comment]
I've closed this issue, but I've placed another question, so if anyone would like to help me, please do so.
#10263
