### ISSUE TITLE
Can you change the mouse cursor without using source code?

### ISSUE THREAD

**Issue by TheManwhoisdyinghere** [ShadowMario/FNF-PsychEngine#10279]
### What is your question?

Can you do it with Lua or is it source code only?

**Comment by ManMaster707** [comment]
[Yes you can.](https://github.com/Theoyeah/PsychEngineDiscussions/discussions/200)

**Comment by TheKitBoi** [comment]
And if have an older version than 6.2 then
https://github.com/ShadowMario/FNF-PsychEngine/issues/10256
