### ISSUE TITLE
help me please! source/FunkinLua.hx:593: lines 593-597

### ISSUE THREAD

**Issue by LevieStarly** [ShadowMario/FNF-PsychEngine#10282]
### Describe your problem here.

Whenever I compile the fnf psych engine source code it says this

source/FunkinLua.hx:593: lines 593-597 : Int should be Bool
source/FunkinLua.hx:593: lines 593-597 : ... For function argument 'f'

please can somebody help me

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope didn't touch nor open a single file

**Comment by TheKitBoi** [comment]
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
