### ISSUE TITLE
Compiling the game (error: Uncaught exception)

### ISSUE THREAD

**Issue by Troystar23** [ShadowMario/FNF-PsychEngine#10287]
### Describe your problem here.

I'm not really sure what happened, as far as I was aware the compiling worked beforehand but when I tried compiling tonight I was thrown with this error that I cant seem to find a fix online. Does anyone know how I can fix this? Thanks in advance!

![image](https://user-images.githubusercontent.com/97416596/186154226-23933c19-81b4-4c67-9e63-ffac38ba3a52.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Thedumbdude** [comment]
did you add anything in the example_mods folder

**Comment by MemeHoovy** [comment]
update to haxe 4.2.5

**Comment by Troystar23** [comment]
I'm positive I have it up to date but I'll double check just in case

**Comment by MemeHoovy** [comment]
no you don't
![186154226-23933c19-81b4-4c67-9e63-ffac38ba3a52szz](https://user-images.githubusercontent.com/97995998/186274811-1f66a684-5afd-45da-8771-b7abcb91660f.png)

**Comment by Troystar23** [comment]
I'll make sure to update it now, thank you :)

**Comment by CrusherNotDrip** [comment]
if it worked close the issue

**Comment by Troystar23** [comment]
I haven't tested it yet cause I'm not home atm but I will do if it did fix it though :)

**Comment by Troystar23** [comment]
![image](https://user-images.githubusercontent.com/97416596/186391443-e14c4a08-5280-427f-8401-bd6a8d443d9a.png)
so weirdly enough haxe was already installed but I think on another harddrive so my program that was on my main ssd couldnt access it (I assume) so I reinstalled haxe 4.2.5 like you said and did all the haxelib installs all over again and yet I was prompted with the same issue any other suggestions? :(

**Comment by MemeHoovy** [comment]
OK, I think your trying to compile from outside the project folder, not in the root of it, if your trying to run that where there's no project.XML file and no source folder, then there's your problem.
See: https://community.haxe.org/t/error-from-the-command-haxelib-run-lime-test-windows/3010

**Comment by Troystar23** [comment]
![image](https://user-images.githubusercontent.com/97416596/186454899-22f87fc2-a293-489d-89d5-50089c28403f.png)
I usually compile from within this folder and it always works is this where im meant to compile? It odes have the project.xml and everything I thought it needed but still prompts the same error

**Comment by MemeHoovy** [comment]
> 

yeah, and if it still giving you the same error, then I'm out of ideas, your haxe might just be completely screwed up.

**Comment by Troystar23** [comment]
I'll try look into it a bit more later but thanks you for the time and effort you took to help :)

**Comment by Troystar23** [comment]
FIGURED IT OUT! And so the problem for people who are also having the same issue is that no files are allowed to be edited outside of the mods folder (AT LEAST WHAT IVE GATHERED AND JUST FIGURED OUT RIGHT AT THIS MOMENT DOSENT MEAN ITS CORRECT IM JUST TRYING TO HELP). I simply added my own dataminershaven folder with pictures in it and thats all it took to completely stop me from compiling, so make sure anything you add (i assume add only) is only in the mods folder anything in preload is not takin so lightly by the compiling process clearly.
