### ISSUE TITLE
Game keeps crashing Mid song

### ISSUE THREAD

**Issue by Among124** [ShadowMario/FNF-PsychEngine#10284]
### Describe your bug here.

The game keeps crashing mid song when i try to play it.
![Replay 2022-08-23 01-35-51](https://user-images.githubusercontent.com/107786575/186078570-c158ed54-26dc-4462-9e6a-46c8d8299eb1.gif) The quality is so bad to fit the file size limit
 

### Command Prompt/Terminal logs (if existing)

```bash
No logs
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TFLTV** [comment]
whats the script

**Comment by Among124** [comment]
i have a lot of scripts, but i removed most of them then it stopped crashing
