### ISSUE TITLE
HTML Build and FunkinLua

### ISSUE THREAD

**Issue by letsgoaway-games** [ShadowMario/FNF-PsychEngine#10285]
### Describe your bug here.

Build for html.
Pain
I didnt download from releases, if that makes a difference, i used it as a template on git hub then downloaded it from github.
I have also uninstalled and reinstalled linc_luajit MULTIPLE TIMES. Windows Build works fine but this doesnt. Other than that psych engine is pretty good so far :). Please help me if you can.

### Command Prompt/Terminal logs (if existing)

```bash
C:\fnf>echo BUILDING GAME
BUILDING GAME

C:\fnf>lime test html5 -release
source/FunkinLua.hx:3061: characters 23-28 : Type not found : State
source/CoolUtil.hx:18: lines 18-141 : ... Defined in this class
source/PlayState.hx:3752: characters 40-68 : Class<FunkinLua> has no field getPropertyLoopThingWhatever
source/PlayState.hx:4895: characters 8-12 : FunkinLua has no field call
source/PlayState.hx:4896: characters 8-12 : FunkinLua has no field stop
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

In the referenced files in the log, i did not edit anything.

**Comment by ethpsa09** [comment]
NVM This PR Worked! https://github.com/ShadowMario/FNF-PsychEngine/pull/10214
Keeping it open for other people to see if they are making a mod and want to html

**Comment by TheKitBoi** [comment]
Close this
![07E81513-200F-44D9-9B62-2E52A5A3D67C](https://user-images.githubusercontent.com/84044666/186164043-57811143-c4d9-4ea2-a0ed-a7230fd20b15.jpeg)

**Comment by CrusherNotDrip** [comment]
> Keeping it open for other people to see if they are making a mod and want to html

The fucking search bar exists
and Shadow Mario will probably close this anyways

**Comment by TheKitBoi** [comment]
great job
Ur late to do that
