### ISSUE TITLE
Project.xml problem

### ISSUE THREAD

**Issue by fljdfkssjkdjkdsjkds** [ShadowMario/FNF-PsychEngine#10280]
### Describe your bug here.

when I try to compile the Friday night funkin Psych engine there is a pop-up that says Error: You must have a "project.xml" file or specify another valid project file when using the 'build' command

### Command Prompt/Terminal logs (if existing)

```bash
Error: You must have a "project.xml" file or specify another valid project file when using the 'build' command
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheKitBoi** [comment]
if you think that work then close this issue
![close the dam issue](https://user-images.githubusercontent.com/84044666/185947241-e75acdf5-d2b4-44dc-8e36-056d21a6ea27.jpeg)

**Comment by TheKitBoi** [comment]
> ### Describe your bug here.
> when I try to compile the Friday night funkin Psych engine there is a pop-up that says Error: You must have a "project.xml" file or specify another valid project file when using the 'build' command

https://github.com/ShadowMario/FNF-PsychEngine/blob/main/Project.xml
YO SHIT FOR BRAINS WHAT GOD DAMN FILE IS THIS HUH
YOU FUCKING BLIND MOTHERFUCKER WHO THE FUCK DO YOU THINK YOU ARE
COMING HERE SHITTING IN MY MAILBOX
PLAYING MY GOD DAMN VIDEO GAMES
YOU GONNA LEARN HOW TO DOWNLOAD THIS
YOU DUMB FORESKIN

**Comment by MemeHoovy** [comment]
> > ### Describe your bug here.
> > when I try to compile the Friday night funkin Psych engine there is a pop-up that says Error: You must have a "project.xml" file or specify another valid project file when using the 'build' command
> 
> https://github.com/ShadowMario/FNF-PsychEngine/blob/main/Project.xml YO SHIT FOR BRAINS WHAT GOD DAMN FILE IS THIS HUH YOU FUCKING BLIND MOTHERFUCKER WHO THE FUCK DO YOU THINK YOU ARE COMING HERE SHITTING IN MY MAILBOX PLAYING MY GOD DAMN VIDEO GAMES YOU GONNA LEARN HOW TO DOWNLOAD THIS YOU DUMB FORESKIN

jesus

**Comment by fljdfkssjkdjkdsjkds** [comment]
> **DON'T FUCKING DELETE THE PROJECT.XML**
I didn't I'll give you a picture

**Comment by fljdfkssjkdjkdsjkds** [comment]
![Uploading project.xml - Search Results in FNF-PsychEngine-main (3) 24_08_2022 7_19_43 PM (1).png…]()

**Comment by fljdfkssjkdjkdsjkds** [comment]
> **DON'T FUCKING DELETE THE PROJECT.XML**

file:///C:/Users/mwset/Videos/Captures/project.xml%20-%20Search%20Results%20in%20FNF-PsychEngine-main%20(3)%2024_08_2022%207_19_43%20PM.png

**Comment by fljdfkssjkdjkdsjkds** [comment]
> file:///C:/Users/mwset/Videos/Captures/project.xml%20-%20Search%20Results%20in%20FNF-PsychEngine-main%20(3)%2024_08_2022%207_19_43%20PM.png

https://drive.google.com/drive/folders/1-tJ0DLkwaG1NjwVMaoDbM6obv99Eto5k

**Comment by fljdfkssjkdjkdsjkds** [comment]
> bruh, we don't have access to your hard-drive idiot

your fucking annoying me you are so rude I think you shut the fuck up you pussy ass bitch wtf have I done to you fucking asshole go fuck yourself fucking hell. I am pissed as fuck you ugly shit lip

**Comment by StefanBETA2008** [comment]
Just Don't Delete The Project.xml Or Your Compile It's Not Working.

**Comment by StefanBETA2008** [comment]
> 
> jesus

Yeah, Im Know, Right?

**Comment by fljdfkssjkdjkdsjkds** [comment]
> Just Don't Delete The Project.xml Or Your Compile It's Not Working.

ok thank you

**Comment by fljdfkssjkdjkdsjkds** [comment]
> Just Don't Delete The Project.xml Or Your Compile It's Not Working.

Don't want to ba annoying but it didn't work

**Comment by Legendary-Candice-Joe** [comment]
To be clear, you are compiling it from the project root directory right?

Make sure when you do 'lime test windows' that you are in the top folder, NOT in the source directory.
