### ISSUE TITLE
Chart crashing 

### ISSUE THREAD

**Issue by NMesca** [ShadowMario/FNF-PsychEngine#10288]
### Describe your bug here.

Hello i had a problem with my chart, i made a custom chart, create the .json folder and everything, and when i click on reload .son i had that message: 
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
editors/ChartingState.hx (line 2911)
editors/ChartingState.hx (line 428)
Prompt.hx (line 44)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/island/island.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
so i thank the one who can give me the accurate answer

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Of course a new song

**Comment by TheKitBoi** [comment]
The json is missing

**Comment by NMesca** [comment]
> The json is missing

But i create the .json

**Comment by TheKitBoi** [comment]
> But i create the .json

did you put it into the right folder
assets/data/island/island.json

**Comment by NMesca** [comment]
> > But i create the .json
> 
> did you put it into the right folder assets/data/island/island.json

Eh i don't how do i do that, sorry i am new to this

**Comment by NMesca** [comment]
> > But i create the .json
> 
> did you put it into the right folder assets/data/island/island.json

Yes of course

**Comment by TheKitBoi** [comment]
> Yes of course

test it to see if it wotks

**Comment by NMesca** [comment]
> 
![Capture d’écran (1)](https://user-images.githubusercontent.com/111884239/186181942-853ac9e1-d927-4384-aa51-32cf35ca381a.png)

**Comment by NMesca** [comment]
> 

No, it won't work

**Comment by TheKitBoi** [comment]
> No, it won't work

Your supposed to create a folder named island and put the json in here

**Comment by TheKitBoi** [comment]
close this issue
![5781169C-334D-44E7-BF88-E4E19BA19CDC](https://user-images.githubusercontent.com/84044666/186184391-fb4c711c-e242-4cfb-8743-8fbb4acfb5e6.jpeg)

**Comment by NMesca** [comment]
done
