### ISSUE TITLE
Cannot open chart editor ( Psych Engine 0.6.2 )

### ISSUE THREAD

**Issue by melocotonwaztaken** [ShadowMario/FNF-PsychEngine#10296]
### Describe your bug here.

Failed to open chart editor when pressing "7" , Game closes down randomly

### Command Prompt/Terminal logs (if existing)

```bash
Paths.hx (line 352)
HealthIcon.hx (line 43)
HealthIcon.hx (line 20)
editors/ChartingState.hx (line 251)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I've removed some icons and some other folders in assets

**Comment by frantastic24** [comment]
Not a bug
Dad icon is missing

**Comment by melocotonwaztaken** [comment]
oh ok tysm
