### ISSUE TITLE
game crashes while using chart editor on 0.6 and onward

### ISSUE THREAD

**Issue by LandonIsE** [ShadowMario/FNF-PsychEngine#10298]
### Describe your bug here.

every time i try to chart a song in the chart editor, after about 2-3 minutes, the game suddenly crashes. and if I save the json before the game crashes then try to play the chart, the game also crashes.

### Command Prompt/Terminal logs (if existing)

```bash
Uncaught Error: Could not create thread
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by BlazingDragonsYT** [comment]
I've also been having this issue.

**Comment by wubbzyfan** [comment]
I can fix the chart crashing when played issue, check if it’s a .json or a “file”, if it’s “file” then add .json and it’ll work

**Comment by BlazingDragonsYT** [comment]
Does it fix the fact that whenever I press a key, it has a chance of crashing?

**Comment by KillerAvecRage** [comment]
> BlazingDragonsYT

This is not the same problem, here you're missing notesplashes

**Comment by BlazingDragonsYT** [comment]
Alright, I think I might have an idea. Are using a JSON from an older version? Are you using events?

**Comment by LandonIsE** [comment]
no older versions, no events, the game just crashes after a while

**Comment by BlazingDragonsYT** [comment]
Well, mine now only happens when I use a malformed event.
