### ISSUE TITLE
Function for Different Character Focus

### ISSUE THREAD

**Issue by NullObjectRef** [ShadowMario/FNF-PsychEngine#10291]
### What is your question?

I'm working in Lua and I was wondering if you could have a function so that if it's a mhs (must hit section), then this happens, but if it's not an mhs, then something else happens.

**Comment by CrusherNotDrip** [comment]
mustHitSection is a variable you can mess around with
you can use it in `if` shit

**Comment by NullObjectRef** [comment]
should've thought about that lol, thanks
