### ISSUE TITLE
delete menus no source code pls

### ISSUE THREAD

**Issue by goldenpotatowastaken** [ShadowMario/FNF-PsychEngine#10292]
### Describe your problem here.

its already in the title please help source code is too complicated for me

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

terraria mod

**Comment by Mastercopper2346** [comment]
Which menus

**Comment by Mastercopper2346** [comment]
Wait..

**Comment by Mastercopper2346** [comment]
It’s not possible in lua

**Comment by Mastercopper2346** [comment]
Sorry bro

**Comment by CrusherNotDrip** [comment]
not possible in lua.

**Comment by Parsellol** [comment]
this aint possible

**Comment by TheKitBoi** [comment]
close this issue
![04E08581-A137-4624-A49B-F65D0CC5CFAD](https://user-images.githubusercontent.com/84044666/186420954-c3728ba1-5d92-4f9b-9659-d67ce825a289.jpeg)

**Comment by Grape-Boy** [comment]
> close this issue ![04E08581-A137-4624-A49B-F65D0CC5CFAD](https://user-images.githubusercontent.com/84044666/186420954-c3728ba1-5d92-4f9b-9659-d67ce825a289.jpeg)

i agree so much with you
