### ISSUE TITLE
how i create a FlxUITabMenu?

### ISSUE THREAD

**Issue by GreenSoupDeveloper** [ShadowMario/FNF-PsychEngine#10299]
### Describe your problem here.

how i create a FlxUITabMenu?

its for a editor state

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by frantastic24** [comment]
You already have an open issue, don't create another one

**Comment by GreenSoupDeveloper** [comment]
> You already have an open issue, don't create another one

so, how i make a flxuitabmenu

**Comment by TheKitBoi** [comment]
> so, how i make a flxuitabmenu

don't duplicate the same issue and be patient

**Comment by frantastic24** [comment]
Idk, it's not even psych engine related

**Comment by tylerandari12** [comment]
> Idk, it's not even psych engine related

Haxe and Psyche seem pretty related to me...

**Comment by frantastic24** [comment]
well no this is for psych engine issues, not haxe

**Comment by CrusherNotDrip** [comment]
> > Idk, it's not even psych engine related
> 
> 
> 
> Haxe and Psyche seem pretty related to me...

psych uses haxe, but the thing he is requesting is not psych related sooooo
