### ISSUE TITLE
Let function earlyEventTrigger use the value1 and value2 of the event that’s being triggered early

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#10297]
### What feature do you want to get added on the **base** engine?

So the function earlyEventTrigger only lets you use the name of the event as one of the (things,in,parenthesis), and I feel that letting it use the value1 and value2 of the event could be pretty helpful, if a change in the value1 would make it better to have a different return time for example.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
Don't open duplicates

**Comment by wubbzyfan** [comment]
alright then, guessing no value1 and value2 considering how the old one (#10079 for anyone else who sees this) kinda… didn’t
