### ISSUE TITLE
Crash for some reason

### ISSUE THREAD

**Issue by Rainestorm222** [ShadowMario/FNF-PsychEngine#10290]
### Describe your problem here.

Paths.hx (line 352)
BGSprite.hx (line 24)
PlayState.hx (line 559)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

it said that after i edited a PNG image and saved it.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Missing texture, what version are you using

**Comment by frantastic24** [comment]
Be more specific, recent commit or recent release
