### ISSUE TITLE
Custom stage problem

### ISSUE THREAD

**Issue by neighborduck** [ShadowMario/FNF-PsychEngine#103]
Whenever I add a custom stage to the stages folder the mods/stages and load it the characters load in perfectly fine but the stage assets don’t load in

**Comment by ShadowMario** [comment]
Where did you put your stages? And what is the code for the stage?

**Comment by neighborduck** [comment]
i put my stage assets in the shared assets and this is the image for the code
![Screenshot_131](https://user-images.githubusercontent.com/91151439/134284520-d6508b94-4355-435c-b3d7-eb9f5beeeb19.png)


but when i run the lime test windows i get this error
![Screenshot_132](https://user-images.githubusercontent.com/91151439/134284612-26708e80-3d47-42fa-a1e5-d508646cacb7.png)

**Comment by neighborduck** [comment]
This is the source code in the playstat
![Screenshot_131](https://user-images.githubusercontent.com/91151439/134284674-85b1da5f-e45b-4525-8aed-33576c314e2b.png)
e

**Comment by DarkDawnzenith** [comment]
I think the game is actually expecting a closet bracked in the line 385 not 360. That if there is an open bracket in 359

**Comment by ShadowMario** [comment]
The problem seems to actually start before line 360
