### ISSUE TITLE
Increased Events = Increased Lag 

### ISSUE THREAD

**Issue by ADPie2008** [ShadowMario/FNF-PsychEngine#10306]
### Describe your problem here.

I'm making a BETADCIU mod and already have everything ready. But when I swap between the characters, the more "Change Character" events I use, the more my computer lags. My computer is an Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz. Is there any workaround to the lag?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
You are storing a ton of graphics, your PC probably isn't very strong so it will lag
Best you can do is remove empty space from spritesheets to reduce memory

**Comment by antoSKRLOL** [comment]
the delays more than due to the event is due to the size of the sprites that you are using, both characters and scenarios, etc., they occupy a lot of device resources, unless you know how to do this type of thing there is no good solution, I recommend you to install versions optimized of the mods that you will use in question

**Comment by antoSKRLOL** [comment]
> You are storing a ton of graphics, your PC probably isn't very strong so it will lag Best you can do is remove empty space from spritesheets to reduce memory

that works but not very effective as it still takes too much space on big sprites, its better to remake the sheets with the fla file or look for low end optimized versions

I am an optimizer and the difference is noticeable

I attach an example
![momCar](https://user-images.githubusercontent.com/103867370/186857468-15fef17a-f530-4f27-89d9-d4ff004a06eb.png)
:

**Comment by ADPie2008** [comment]
> the delays more than due to the event is due to the size of the sprites that you are using, both characters and scenarios, etc., they occupy a lot of device resources, unless you know how to do this type of thing there is no good solution, I recommend you to install versions optimized of the mods that you will use in question

Do you mean psych ports? Because that’s what I’ve been doing. I’ve also turned on Low Quality to see if it would do anything. I even tried my other computer, and that was still outputting low frames. The cover is Madness with 35 characters, is it possibly too much for Psych Engine?
