### ISSUE TITLE
[0.6.2] Charts that were Exported without Modifying an existing one break on older versions of Psych and alternative engines

### ISSUE THREAD

**Issue by BeastlyGhost** [ShadowMario/FNF-PsychEngine#10301]
## Explanation
so I exported a new chart using Psych Engine's chart editor, when opening on 0.6.2, it works just as intended, however, the problem starts when you open it on versions prior to 0.6 (0.5.2h or before), or alternative engines such as Forever Engine

---------------------------

## Steps to Reproduce
1- go to the Main Menu and open the Master Editor Menu
2- select Chart Editor, and while in there, chart anything you want
3- Export the Chart and try to use it with an older version of Psych or an alternative engine

---------------------------

## RESULT
the result should be something like this, whether it's psych 0.5.2h or any other engine

https://user-images.githubusercontent.com/45212377/186536609-4d33f3f9-016e-4662-9eb5-89f8369b740c.mp4

reminder that this problem doesn't exist on versions prior to 0.6, so charting there **can** be a solution, just not a definitive one

the chart definitely works, however it breaks the chart editor, which can be a problem in several different ways

### Are you modding a build from source or with Lua?

Not at all

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, this is a clean Psych Engine Build, straight from the Releases Tab

## UPDATE
apparently, for 0.6, with the new chart data, you just gotta change the line that says `"sectionBeats": 4,` to `"lengthinSteps": 16,`, this fixes the issue, however it's not a definitive solution

**Comment by MemeHoovy** [comment]
how particular, I honestly didn't know this was a bug and idk why this happens either, just look at old commits to see what breaks the charts or something I don't know

**Comment by wubbzyfan** [comment]
You’ve gotta put the file extension on it, because for some reason it saves without one if you don’t put “.json” or whatever the file extension for whatever you make (.xml for pngs (which psych doesn’t make so irrelevant), .json for charts and characters, and .lua for scripts, events, notes, etc) should be. It’s stupid, but for some reason it has to be done. Idk why it stopped having the extension auto added to it

**Comment by frantastic24** [comment]
Just tested it with a latest commit on 0.5.2h and Kade, both worked fine
Either it was fixed already or it's something with your file

**Comment by BeastlyGhost** [comment]
UPDATE: apparently, for 0.6, with the new chart data, you just gotta change the line that says `"sectionBeats": 4,` to `"lengthinSteps": 16,`, this fixes the issue, however it's not a definitive solution

**Comment by BeastlyGhost** [comment]
> You’ve gotta put the file extension on it, because for some reason it saves without one if you don’t put “.json” or whatever the file extension for whatever you make (.xml for pngs (which psych doesn’t make so irrelevant), .json for charts and characters, and .lua for scripts, events, notes, etc) should be. It’s stupid, but for some reason it has to be done. Idk why it stopped having the extension auto added to it

the file extension is valid, it was related to the data on the file itself.

**Comment by BeastlyGhost** [comment]
clsoing because i already found out
