### ISSUE TITLE
Bug with compiling the source code

### ISSUE THREAD

**Issue by tomdadude** [ShadowMario/FNF-PsychEngine#10305]
### Describe your bug here.

This error message comes up when i try to compile the source code
![Screenshot (30)](https://user-images.githubusercontent.com/93546179/186722006-1d3ccc49-c00c-4a8d-9494-0d3e7fe2ecd9.png)
 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Not a bug and a duplicate, look it up on issues
