### ISSUE TITLE
how to detect when player dies

### ISSUE THREAD

**Issue by LiterallyWize** [ShadowMario/FNF-PsychEngine#10300]
functions variables anything to detect when the player dies

detect when its game over in a song

in lua

in 0.5.2h

**Comment by TheKitBoi** [comment]
inGameOver

**Comment by LiterallyWize** [comment]
> inGameOver

see thats the thing, how do i make it detect only once

**Comment by Mastercopper2346** [comment]
> > inGameOver
> 
> see thats the thing, how do i make it detect only once

Wdym by that

**Comment by LiterallyWize** [comment]
> > > inGameOver
> > 
> > 
> > see thats the thing, how do i make it detect only once
> 
> Wdym by that

i mean how do i make it detect only once, like, only once right when the player goes into the game over screen

**Comment by Mastercopper2346** [comment]
function onGameOver

**Comment by LiterallyWize** [comment]
> function onGameOver

thank you
