### ISSUE TITLE
Haxe build problem 

### ISSUE THREAD

**Issue by Lorekeeper49** [ShadowMario/FNF-PsychEngine#10309]
### Describe your problem here.

I don't know if this is a problem with the engine or a problem with haxe but, whenever I initiate the command `lime build windows` (keep in mind that it only happens with this command, all other commands do what they're supposed to without this happening), I have to reinstall haxe in order to initiate lime commands again.

### Haxe version:

4.2.5

### Psych engine version:

0.6.2

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Mastercopper2346** [comment]
Try lime test windows

**Comment by Lorekeeper49** [comment]
> Try lime test windows

Like I said, that command works fine without this happening, it only happens with `lime build windows`
