### ISSUE TITLE
bug of the event

### ISSUE THREAD

**Issue by SENFULLHD4K** [ShadowMario/FNF-PsychEngine#10304]
### Describe your bug here.

When I put an event that I made myself And I inserted it almost at the end of the song, But I start the level and a few curstep later the event fires at a place I don't insert 

For example Imagine that you put any event in a Curstep 100 (example) and the event is activated in the curstep 20 

and that is what causes the problem for me and I cannot find a solution 

If you answer me quickly it would help me please 

### Command Prompt/Terminal logs (if existing)

`function onEvent(name, value1, value2)

--GenteFondo
makeAnimatedLuaSprite('Fg', 'Gente Fondo', -300, 300)
addAnimationByPrefix('Fg', 'idle', 'gente fondo idle', 24, true)
setObjectOrder('Fg', '3')
scaleObject('Fg', 0.7, 0.7)
setScrollFactor('Fg', 1.0, 1.0)
addLuaSprite('Fg', false)

--GatoBlanco (perdon por el nombreXDDD)
makeAnimatedLuaSprite('gato', 'GatoBlanco', 100, 200)
addAnimationByPrefix('gato', 'idle', 'Gato Idle', 24, true)
setObjectOrder('gato', '4')
scaleObject('gato', 1, 1)
setScrollFactor('gato', 1.0, 1.0)
addLuaSprite('gato', false)

--NocheMala (XD)
makeAnimatedLuaSprite('nm', 'NocheMala Idle', 900, 400)
addAnimationByPrefix('nm', 'idle', 'Nochemala Idle', 24, true)
setObjectOrder('nm', '4')
scaleObject('nm', 1.5, 1.5)
setScrollFactor('nm', 1.0, 1.0)
addLuaSprite('nm', false) 

end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nop

**Comment by frantastic24** [comment]
Not a bug
You didn't show the script, you probably didn't add a check for the event name

**Comment by SENFULLHD4K** [comment]
> Not a bug
> You didn't show the script, you probably didn't add a check for the event name


show you the script?

**Comment by SENFULLHD4K** [comment]
> Not a bug
> You didn't show the script, you probably didn't add a check for the event name


show you the script?

**Comment by frantastic24** [comment]
Show the script, it would be pointless to report a bug if it can't be easily reprosuced

**Comment by SENFULLHD4K** [comment]
> Show the script, it would be pointless to report a bug if it can't be easily reprosuced


`function onEvent(name, value1, value2)

    --GenteFondo
    makeAnimatedLuaSprite('Fg', 'Gente Fondo', -300, 300)
    addAnimationByPrefix('Fg', 'idle', 'gente fondo idle', 24, true)
    setObjectOrder('Fg', '3')
    scaleObject('Fg', 0.7, 0.7)
    setScrollFactor('Fg', 1.0, 1.0)
    addLuaSprite('Fg', false)


    --GatoBlanco (perdon por el nombreXDDD)
    makeAnimatedLuaSprite('gato', 'GatoBlanco', 100, 200)
    addAnimationByPrefix('gato', 'idle', 'Gato Idle', 24, true)
    setObjectOrder('gato', '4')
    scaleObject('gato', 1, 1)
    setScrollFactor('gato', 1.0, 1.0)
    addLuaSprite('gato', false)

    --NocheMala (XD)
    makeAnimatedLuaSprite('nm', 'NocheMala Idle', 900, 400)
    addAnimationByPrefix('nm', 'idle', 'Nochemala Idle', 24, true)
    setObjectOrder('nm', '4')
    scaleObject('nm', 1.5, 1.5)
    setScrollFactor('nm', 1.0, 1.0)
    addLuaSprite('nm', false) 
    

end`

**Comment by frantastic24** [comment]
Yeah it doesn't have a name check like I said, it's not a bug it's an issue with your code

**Comment by SENFULLHD4K** [comment]
> Yeah it doesn't have a name check like I said, it's not a bug it's an issue with your code

and how do i solve it?

**Comment by frantastic24** [comment]
```lua
if name == 'event name' then
```

**Comment by SENFULLHD4K** [comment]
> ```lua
>  then
> ```

sorry for being so stupid you're right I had forgotten but thank you very much
