### ISSUE TITLE
The Shader Help

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10308]
### Describe your problem here.

How To Add The Wavy Backgrounds Like From The Dave And Bambi On The New Psych Engine Update?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

It's For The Test Or The Something. Don't Ask

**Comment by MemeHoovy** [comment]
you can't, not unless you readd the old shader code yourself

**Comment by CrusherNotDrip** [comment]
> you can't, not unless you readd the old shader code yourself

yes you can
and plus its source so lots of things are possible

**Comment by MemeHoovy** [comment]
> > you can't, not unless you readd the old shader code yourself
> 
> yes you can and plus its source so lots of things are possible

that's what I meant, not unless you **readd** the _old shader code_ I don't know about the new shader code though
