### ISSUE TITLE
The Timebar Color Help

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10312]
### Describe your problem here.

How To Make The Custom Color For The Timebar With The Source Code, Like The Sonic.EXE 2.5/3.0 Cancelled Update? It's Possible For The New Update?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

The PlayState.hx Timebar

**Comment by PurSnake** [comment]
In PlayState change hex colors in that line}
```timeBar.createFilledBar(0xFF000000, `0xFFFFFFFF);```

**Comment by StefanBETA2008** [comment]
> In PlayState change hex colors in that line `` timeBar.createFilledBar(0xFF000000, `0xFFFFFFFF); ``

Thank You So Much. I Will Try To Change To Orange.
