### ISSUE TITLE
Character changes boyfriend instead of dad

### ISSUE THREAD

**Issue by Reycko** [ShadowMario/FNF-PsychEngine#1031]
### Describe your problem here.

So i'm trying to change characters from Maevings to Ron on my mod and it changes boyfriend.

Screenshots (to see the values):

![image](https://user-images.githubusercontent.com/78082869/141679764-76148feb-465f-4930-8b7f-e211fc43a599.png)

![image](https://user-images.githubusercontent.com/78082869/141679786-6365760e-ed80-4e6c-b774-d0bf22a0b64d.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

New background, New week, 2 more characters, me, Maevings and wildy on credits.

**Comment by titopops** [comment]
dad uses 1 for the value 1, (the top one), girlfriend uses 2, and anything else is for boyfriend

**Comment by Reycko** [comment]
ty!
