### ISSUE TITLE
Force Middlescroll & Invisible Opponent Notes

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#10310]
### What is your question?

EDit: Should've done a "help me" instead, oops

For a song I want to Force Middlescroll for the player
(which usually worked even)
And I want to make the notes of the opponen invisble when done so
(which worked too I think)

But It somehow doesn't anymore. can anyone help out with this?

I'll send the script I used (The script used for the song only)
(changed it to txt to be able to send it over)

[script.lua.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9432190/script.lua.txt)

And this is the result I get every time
No Middle scroll
No hidden opponent notes
![image](https://user-images.githubusercontent.com/76132257/186879682-5169ec6c-f92f-4f7e-a821-516bd4f0eba5.png)

**Comment by ZeitHeld** [comment]
Also, I took a similar script, which worked on a different song-
But it doeesn't here. and the mod/script is waay more complex.

(even though it still has a bug as well but that has to be caused by the mod)

So, why is this happening?

**Comment by Meme1079** [comment]
here

```lua
function onCreate()     
     if not middlescroll then
          setPropertyFromClass('ClientPrefs', 'middleScroll', true)
     end
end

function onCreatePost()
     for i = 0,3 do
          setPropertyFromGroup('opponentStrums', i, 'y', 1300)
     end
end

function onDestroy() -- end of the song or you exited
     if not middlescroll then
          setPropertyFromClass('ClientPrefs', 'middleScroll', false)
     end
end
```

**Comment by ZeitHeld** [comment]
> here
> 
> ```lua
> function onCreate()     
>      if not middlescroll then
>           setPropertyFromClass('ClientPrefs', 'middleScroll', true)
>      end
> end
> 
> function onCreatePost()
>      for i = 0,3 do
>           setPropertyFromGroup('opponentStrums', i, 'y', 1300)
>      end
> end
> 
> function onDestroy() -- end of the song or you exited
>      if not middlescroll then
>           setPropertyFromClass('ClientPrefs', 'middleScroll', false)
>      end
> end
> ```

Not quite the effect I wanted (as it's only moved down) but it works for the middle scroll. I somehwo got it even to work after playing with another mod, which is very weird tbh.

Plus, rather move the x value and not y, as the arrows can still be seen if someone uses donwscroll

**Comment by ZeitHeld** [comment]
Also, is it important to use onCreatePost() instead of onCreate()? if so, why?
because then the stuff is loaded in already?

**Comment by Meme1079** [comment]
> Also, is it important to use onCreatePost() instead of onCreate()? if so, why?
because then the stuff is loaded in already?

Yes if the code is not working on `onCreate()`

**Comment by ZeitHeld** [comment]
Pretty stupid imo.

But I also noticed as I updated the script (I put it in a second lua) That not everything properly reloads sometimes
