### ISSUE TITLE
Cannot get to main menu screen (HELP!!!)

### ISSUE THREAD

**Issue by Nemophyya** [ShadowMario/FNF-PsychEngine#10311]
### Describe your bug here.

I released the mod today and a bug was reported that can no longer navigate to the menu screen.
I need to fix it as soon as possible because the mod is already public, but I don't know how to fix it.
When I try to open the menu screen, it crashes with the following error message.

MainMenuState.hx (line 151)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https: //github.com/ShadowMario/FNF-PsychEngine

Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

None of MainMenuState.hx, flixel/FlxGame.hx and openfl has been edited.

**Comment by KillerAvecRage** [comment]
Your game is missing a file, check assets/images and see if you have the following files:
-logoBumpin.png
-logoBumpin.xml
-gfDanceTitle.png
-gfDanceTitle.xml

Psych Engine could live without its heart (assets folder) but now it seems like it can't so yeah, you need to be careful

**Comment by Nemophyya** [comment]
I checked, and there it is.
And when I re-started it, for some reason I was able to get to the main menu screen normally.

But titleEnter is not working properly (stops after the first frame) even though I have not edited anything.
What is the cause of this?

**Comment by BeastlyGhost** [comment]
if it stops after the first frame, then you have flashing lights turned off, this is intentional.

**Comment by Nemophyya** [comment]
It was my lack of confirmation. Thank you.

**Comment by BeastlyGhost** [comment]
no problem, if the issue seems to be fully solved, you should really close this

**Comment by Nemophyya** [comment]
I left it open because I still need to be sure, but I'm going to close it for now. If it happens again, I will reopen it. (Or I may create a new one...)
