### ISSUE TITLE
just found a new bug.

### ISSUE THREAD

**Issue by bopeebosus** [ShadowMario/FNF-PsychEngine#10313]
### Describe your bug here.

i have a new bug when the error happened if give me a note output the error message and it says this :Note.hx (line 124)
PlayState.hx (line 2353)
PlayState.hx (line 1053)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
;

### Command Prompt/Terminal logs (if existing)

```bash
Note.hx (line 124)
PlayState.hx (line 2353)
PlayState.hx (line 1053)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

idk

**Comment by Grape-Boy** [comment]
You need a newer build
