### ISSUE TITLE
Chart Editor Memory Leak

### ISSUE THREAD

**Issue by swordcube** [ShadowMario/FNF-PsychEngine#10318]
### Describe your bug here.

The memory goes up alot if you scroll in the chart editor for some reason
It also just goes up over time

https://user-images.githubusercontent.com/49110074/186961957-abcae473-f0c4-4205-817e-ee839c6af75d.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no because i'm not using source

**Comment by frantastic24** [comment]
Disable vsync from your driver settings

**Comment by BeastlyGhost** [comment]
disable vsync on your GPU driver settings

alternatively, it's a flixel problem, as scrolling through grids increases memory, even on the base game

**Comment by swordcube** [comment]
> disable vsync on your GPU driver settings
> 
> alternatively, it's a flixel problem, as scrolling through grids increases memory, even on the base game

I have intel integrated graphics, where do i change this

**Comment by Leather128** [comment]
how does disabling vsync fix a memory leak in the charter what

**Comment by swordcube** [comment]
i literally don't even have an option to disable vsync, also i agree with leather

**Comment by frantastic24** [comment]
It's either a haxe or driver issue, it just doesn't like vsync on
It also doesn't just affect charting

**Comment by Leather128** [comment]
but why is the actual allocated memory of the game affected by a gpu driver of all things?

**Comment by swordcube** [comment]
I don't get how it would be a driver issue

It seems more likely that it would be a flixel issue (which would be stupid)

**Comment by swordcube** [comment]
but it would make more sense

**Comment by BeastlyGhost** [comment]
> It seems more likely that it would be a flixel issue (which would be stupid)

grids just take THAT much memory, so much so that Kade Engine had an option to hide the grid

**Comment by swordcube** [comment]
> > It seems more likely that it would be a flixel issue (which would be stupid)
> 
> grids just take THAT much memory, so much so that Kade Engine had an option to hide the grid

I find it strange that HaxeFlixel has troubles with a grid of 2d pixel squares

**Comment by BeastlyGhost** [comment]
> 

it renders and updates said grid every single frame, that's why it uses that much memory

**Comment by ShadowMario** [comment]
That's a weird issue (the vsync thing you guys said)

**Comment by frantastic24** [comment]
I have no idea why it happens, the reason I suggest it's a driver issue is because this only started happening to me after some recent AMD updates, it worked fine with vsync on before them
