### ISSUE TITLE
Compiling the source code

### ISSUE THREAD

**Issue by tomdadude** [ShadowMario/FNF-PsychEngine#10316]
### Describe your problem here.

everytime i compile the source code it comes up with this 

source/FunkinLua.hx:342: lines 342-346 : Int should be Bool
source/FunkinLua.hx:342: lines 342-346 : ... For function argument 'f'

I've seen i needed linc_luajit but even when i have it installed and up to date it still comes up with the same thing

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheKitBoi** [comment]
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

**Comment by TheKitBoi** [comment]
no matter how many times I'm gonna copy and paste the same issue
and they didn't even look at the README on what to upgrade/fix themselves
so
close this
![close the dam issue](https://user-images.githubusercontent.com/84044666/186989077-bae391ea-30f1-4df3-9db8-59047d662c91.jpeg)

**Comment by RodrigoElGamer** [comment]
everytime i compile the source code it comes up with this

source/PlayState.hx:74: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1586: characters 13-23 : Type not found : MP4Handler

What I can do?

**Comment by MemeHoovy** [comment]
```
Haxelib install hxCodec 2.5.1
```
Or if you already installed that
```
haxelib set hxCodec 2.5.1
```

**Comment by RodrigoElGamer** [comment]
Thanks You!

**Comment by MemeHoovy** [comment]
> Thanks You!

your welcome
