### ISSUE TITLE
delete practice mode

### ISSUE THREAD

**Issue by tposejank** [ShadowMario/FNF-PsychEngine#10315]
### What feature do you want to get added on the **base** engine?

delete practice mode

why
doesnt do shit
it just deletes dying
does not affect ur score
overall complicates code

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by BeastlyGhost** [comment]
not a real enhancement + ratio

**Comment by Mastercopper2346** [comment]
🤣

**Comment by ShadowMario** [comment]
...That's why it's called "Practice Mode", you can play the song freely without dying.
