### ISSUE TITLE
not

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#10320]
### Describe your problem here.

how to use not statements
I have stupid

```lua
if not dadName == 'gf' then
      --funny code
end
```

this does not work aaaaaaaaaaaaaaa

this code executes correctly (except gf executes the code) if I remove the "not" for some reason

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No (other than the accuracy 'ratingStuff'), just modded in the "example_mods" folder

**Comment by KillerAvecRage** [comment]
Here, "not" lets you do your "funny code" IF the name of the character replacing GF ISN'T "gf"

If you litterally translate it, you'd say "if the name of the opponent **isn't** (that's where your "not" intervenes) gf, then I do "funny code"

I hope this helped, I'm not good at explaining since english isn't even my native language

**Comment by TFLTV** [comment]
> Here, "not" lets you do your "funny code" IF the name of the character replacing GF ISN'T "gf"
> 
> If you litterally translate it, you'd say "if the name of the opponent **isn't** (that's where your "not" intervenes) gf, then I do "funny code"
> 
> I hope this helped, I'm not good at explaining since english isn't even my native language

that's literally what I'm trying to do, and it doesn't work

**Comment by frantastic24** [comment]
This is something you should've looked up on google since Lua isn't specific to psych
```lua
if not (dadName == 'gf') then

if dadName ~= 'gf' then
```

**Comment by TFLTV** [comment]
>if not (dadName == 'gf') then

I did search it up but didn't get this result A
