### ISSUE TITLE
there a weird bug 

### ISSUE THREAD

**Issue by greplol** [ShadowMario/FNF-PsychEngine#1032]
### Describe your bug here.

the note is glitching https://www.youtube.com/watch?v=zD6r8zAs_0I

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Reycko** [comment]
Restart your game, it's a problem when you do Win+L and try to play the game without restarting.
[Phantom Fear](https://www.youtube.com/channel/UCRab81QtbYFqbnkvhYC9G4A) has a [video](https://www.youtube.com/watch?v=J838jxoGcOQ) with this glitch.

**Comment by greplol** [comment]
i restarted it many times

**Comment by perngjiafu** [comment]
you didnt even put the song

**Comment by FuseIsHere813** [comment]
You forgot the Inst and Voices for the song.

Put the Inst and Voices in `mods/songs/your-song-name`

**Comment by acap09** [comment]
> You forgot the Inst and Voices for the song.
> 
> Put the Inst and Voices in `mods/songs/your-song-name`

@FuseIsHere813 
this is source code, not lua/download build

**Comment by Micasddsa** [comment]
You probably have the names of the song and json messed up (it's case-sensitive)
if that doesn't work, idk then.

**Comment by greplol** [comment]
@acap09 i made ugh cover but i put in voices and inst
and @Micasddsa i have the names good

**Comment by ShadowMario** [comment]
Inst.ogg and Voices.ogg file are missing.
Be sure you've recompiled after moving the files.
