### ISSUE TITLE
The Timebar Size

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10325]
### Describe your problem here.

I Wanna Want Make The Timebar Like This With The Source Code

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yeah. PlayState.hx

**Comment by CrusherNotDrip** [comment]
the edit button exists btw
I see you made another issue with the image but yeah you can edit this I believe

**Comment by StefanBETA2008** [comment]
> the edit button exists btw I see you made another issue with the image but yeah you can edit this I believe

Line Please?

**Comment by TheKitBoi** [comment]
> Line Please?

![image](https://user-images.githubusercontent.com/84044666/187010564-ea7b72ec-a150-42dc-9033-718b302fe288.png)

**Comment by StefanBETA2008** [comment]
I Have Only 3 Options:
![Screenshot_20220827-042711~2](https://user-images.githubusercontent.com/109828559/187010719-0f03a6e3-30d7-4667-b515-55b884d68dd5.png)

**Comment by TheKitBoi** [comment]
Press edit button

**Comment by StefanBETA2008** [comment]
I Pressed.

**Comment by TheKitBoi** [comment]
Then add the image and also
Check your duplicate
