### ISSUE TITLE
Weird Song End

### ISSUE THREAD

**Issue by yoyoscreations** [ShadowMario/FNF-PsychEngine#10323]
### Describe your bug here.

When the song ends, the character does a really annoying sound, and I've changed the vocals a million times and still, the guy keeps doing it

https://user-images.githubusercontent.com/109829117/187001437-425dc3a6-1176-451e-8394-fe269887273c.mp4

.

btw sorry for the raw editing of the video (pls help with the issue)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i just added a new song and this shit happened

**Comment by BeastlyGhost** [comment]
the sound length for the vocal file is shorter than the inst file, they should have the same length

**Comment by yoyoscreations** [comment]
thanks! now lemme see if it works tho

**Comment by yoyoscreations** [comment]
It actually worked! thank you!
