### ISSUE TITLE
pls hlp!1

### ISSUE THREAD

**Issue by swobodac** [ShadowMario/FNF-PsychEngine#10324]
### Describe your problem here.

pls help with a custom pause menu layout

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

wavy bg action bulid lol

**Comment by MemeHoovy** [comment]
you can't do that with lua

**Comment by BeastlyGhost** [comment]
> you can't do that with lua

actually you can but anyways

**Comment by swobodac** [comment]
how

**Comment by swobodac** [comment]
HOW!!

**Comment by Mastercopper2346** [comment]
> 

THEN TELL US

**Comment by Mastercopper2346** [comment]
> > you can't do that with lua
> 
> actually you can but anyways

TELL US

**Comment by BeastlyGhost** [comment]
https://cdn.discordapp.com/attachments/929801502829215745/1013170691882877100/subStateExample.lua

**Comment by DisIsNOt** [comment]
Go search YouTube goddammit

**Comment by Mastercopper2346** [comment]
> > you can't do that with lua
> 
> actually you can but anyways

Wait you mean like, using setPropertyFromClass(); ?
