### ISSUE TITLE
Reopening Again Issue With The Timebar Size.

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10326]
### Describe your problem here.

![Screenshot_20220827-032452~2](https://user-images.githubusercontent.com/109828559/187009033-b7e4f189-b798-423f-9ec6-09ea058fac6f.png)
I Just Want To Make The Timebar To Look Like This With The Source Code.
Can You Help Me?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

For The Better Style.

**Comment by TheKitBoi** [comment]
theres no need to reopen the issue
you can just press the 3 dots and press edit
for the fix
go to assets/shared/images/timebar.png
and replace it

**Comment by StefanBETA2008** [comment]
> theres no need to duplicate the issue you can just press the 3 dots and press edit for the fix go to assets/shared/images/timebar.png and replace it

I Just Trying To Find To All Mods, But It's Old Classic TimeBar

**Comment by TheKitBoi** [comment]
> I Just Trying To Find To All Mods, But It's Old Classic TimeBar

What do you mean

**Comment by StefanBETA2008** [comment]
> What do you mean
Mods Only Have This Old Time Bar:
![timeBar](https://user-images.githubusercontent.com/109828559/187011658-9903e4bc-ee01-4d89-9964-f02d76288075.png)

**Comment by TheKitBoi** [comment]
> > ![timeBar](https://user-images.githubusercontent.com/109828559/187011658-9903e4bc-ee01-4d89-9964-f02d76288075.png)

you can just replace it because it's a sprite

**Comment by Mastercopper2346** [comment]
Make the sprite longer
