### ISSUE TITLE
How to relock weeks

### ISSUE THREAD

**Issue by Drixppx** [ShadowMario/FNF-PsychEngine#10327]
### Describe your problem here.

i was testing out my mod and i wanted to relock the weeks that unlocked<How can i do that?!?!?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by StefanBETA2008** [comment]
Relock? I Think You Can't Or You Can. Just Edit The Week.json File I Think

**Comment by Drixppx** [comment]
i tried doing that but even when i lock it again it just shows up unlocked

**Comment by TheKitBoi** [comment]
> i tried doing that but even when i lock it again it just shows up unlocked

send a video of the issue

**Comment by Drixppx** [comment]
https://user-images.githubusercontent.com/87683927/187011671-f33b1c15-4daf-48ec-9768-cb328702821e.mp4

Imma send its with 2 more flies to big

**Comment by Drixppx** [comment]
https://user-images.githubusercontent.com/87683927/187011728-533fed67-0314-4810-83b1-4760a78baa5e.mp4

**Comment by Drixppx** [comment]
so it still lets me play them even tho its locked

**Comment by TheKitBoi** [comment]
make custom weeks
or just press the R button to reset unlocking

**Comment by Drixppx** [comment]
they are custom and the r doesnt work (the prob is that we dont have some assets atm thats why it looks like that)

**Comment by TheKitBoi** [comment]
> they are custom and the r doesnt work (the prob is that we dont have some assets atm thats why it looks like that)

you literally replaced it in the assets/weeks folder instead of the mods/weeks folder

**Comment by Drixppx** [comment]
no its because thats the folder i used for a template

**Comment by TheKitBoi** [comment]
and that's why you need to rename the weeks

**Comment by Mastercopper2346** [comment]
Rename the week name needed to complete the week? And also rename the week needed to be unlocked the same name.
