### ISSUE TITLE
I am trying to port Personnel To My mod pack of sonic.exe 3.0 but with less space (And I dont have 64 bits) and my psych engine just crashes

### ISSUE THREAD

**Issue by ElPro7777** [ShadowMario/FNF-PsychEngine#10339]
### Describe your bug here.

I am trying to port Personnel To My mod pack of sonic.exe 3.0 but with less space (And I dont have 64 bits) and my psych engine just crashes

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 223)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 143)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 90)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
StageData.hx (line 91)
StageData.hx (line 63)
editors/ChartingState.hx (line 1657)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid escape sequence \E at position 23
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Not a bug
Broken stage json

**Comment by Gostar64** [comment]
It's a problem with Personel's original .json, you're gonna have to edit the json in a text editor or something. (You should move the events that are in notes as -1 to actual events)

**Comment by ElPro7777** [comment]
> 

Ok Gracias!

**Comment by ElPro7777** [comment]
> Es un problema con el .json original de Personel, tendrá que editar el json en un editor de texto o algo así. (Debe mover los eventos que están en notas como -1 a eventos reales)

Ok Gracias!

**Comment by ElPro7777** [comment]
Thanks To Gostar64 To help to fix the problem
