### ISSUE TITLE
How do i make a character not backwards?

### ISSUE THREAD

**Issue by imalink100** [ShadowMario/FNF-PsychEngine#10337]
### How do I make a character not backwards?

Someone help me with this.
![image](https://user-images.githubusercontent.com/106406304/187042930-fe65e7a5-64aa-40d4-9274-35f82b7bbf1f.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

This was from the old character json issue, I fixed it and now it's backwards??

**Comment by Mastercopper2346** [comment]
Check/uncheck flip x box

**Comment by imalink100** [comment]
> Check/uncheck flip x box

I'll try to see if i can find that.

**Comment by imalink100** [comment]
Ok it works. Thxes.

**Comment by Aidenkp112** [comment]
wh
