### ISSUE TITLE
LUA Scripts not running in HTML5

### ISSUE THREAD

**Issue by fnfmodscom** [ShadowMario/FNF-PsychEngine#10334]
### Describe your problem here.

Hello Guys,

I want my mod for HTML5 but I have used LUA Scripts in my mod. Now LUA Scripts are not loading in HTML5. Please tell me what I do.  Sites like KBHgames.com are using LUA Scripts in HTML5. How are they using LUA in HTML5?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

HTML5/Browser

**Comment by BeastlyGhost** [comment]
Lua Scripts do not function on HTML5

**Comment by fnfmodscom** [comment]
> Lua Scripts do not function on HTML5, nor they can run on it

I checked PsychEngine.js of one of mod of KBH Games. How are they using LUA in HTML5. 

this.makeLuaSprite("bg","bg",-1100,-650),this.setLuaSpriteScrollFactor("bg",.9,.9),this.scaleLuaSprite("bg",1.4,1.4),this.makeLuaSprite("CasaFH","CasaFH",-1900,-800),this.scaleLuaSprite("CasaFH",1.4,1.4),this.addLuaSprite("bg",!1),this.addLuaSprite("CasaFH",!1)

This code is showing.

**Comment by Mastercopper2346** [comment]
Try to put this. In front of everything them
