### ISSUE TITLE
How Do You Change Rating Texts On Different Songs?

### ISSUE THREAD

**Issue by CC-J4xon** [ShadowMario/FNF-PsychEngine#10333]
### Describe your problem here.

How To Change "Sick" To Another Image And "1", "2", E.T.C.
While Keeping The Original PNGs In A Different Song.

(These Images:)
![hkjskadhkjshk](https://user-images.githubusercontent.com/94282827/187030006-ee1fbdbe-b159-4f27-b731-66830956d76b.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I Added Characters, Songs, Scripts, Custom Events, Custom Notes, Credits, Changed The Rating Texts.

**Comment by Mastercopper2346** [comment]
Which version

**Comment by Lorekeeper49** [comment]
Use this: [Lua Editable Combo Ratings!] (https://gamebanana.com/tools/9273)

**Comment by CC-J4xon** [comment]
> Use this: [Lua Editable Combo Ratings!](https://gamebanana.com/tools/9273)

Thank You! :D
Do You Know How To Make The Misses Have The Default Colour Of The Image Or Does It Have To Be Red?

**Comment by CC-J4xon** [comment]
> > Use this: [Lua Editable Combo Ratings!](https://gamebanana.com/tools/9273)
> 
> Thank You! :D Do You Know How To Make The Misses Have The Default Colour Of The Image Or Does It Have To Be Red?

NVM
