### ISSUE TITLE
Events not working on custom difficulties

### ISSUE THREAD

**Issue by Spookandscare** [ShadowMario/FNF-PsychEngine#10348]
### Describe your bug here.

I added a new difficulty on a song and now the events from that song aren't working
It might not be a bug and I need to do something but I am not sure what if that's the case

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added a few songs, some characters, and a new difficulty

**Comment by Gostar64** [comment]
The events might have been saved into the difficulty json and not an events json
