### ISSUE TITLE
Texture Atlas 2022 support

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#10349]
### What feature do you want to get added on the **base** engine?

basically just a support for 2022 version of texture atlases. The [flxanimate](https://github.com/Dot-Stuff/flxanimate) library supports both 2018 and 2022 version of texture atlases. I am not making a pull request because i am too lazy to make it compatible with the  other code.
So if anyone wants to take on the challenge and try to make it compatible then go for it

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by TheKitBoi** [comment]
waiting is the key

**Comment by tylerandari12** [comment]
> waiting is the key

Banna Sonic

**Comment by CrusherNotDrip** [comment]
he said this
![image](https://user-images.githubusercontent.com/90648119/187104434-ce1d6eea-4ff6-413b-83bc-ca6abceb7e4d.png)

**Comment by lemz1** [comment]
> he said this ![image](https://user-images.githubusercontent.com/90648119/187104434-ce1d6eea-4ff6-413b-83bc-ca6abceb7e4d.png)

I know he said this but maybe someone else knows how to make it compatible

**Comment by TheKitBoi** [comment]
> I know he said this but maybe someone else knows how to make it compatible

im making one
the commits may be a mess once i pull request it because i use actions to see where the issues to fix

**Comment by lemz1** [comment]
> ill invite you to my private flxanimate port if you can help

I can try to help but i have to work on some other stuff so maybe i won't make many commits

**Comment by Cheemsandfriends** [comment]
hm
interesting
