### ISSUE TITLE
loadSong needs some fixes

### ISSUE THREAD

**Issue by RodneyAnImaginativePerson** [ShadowMario/FNF-PsychEngine#10340]
### Describe your bug here.

So it never really works half the time AND YES I have asked for help about it 1,000 times and idrk what the main issue is but I think it has something to do with modded songs.

[Click Here for a Video](https://www.youtube.com/watch?v=6YvcNkNg9YU)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No Base Download

**Comment by Mastercopper2346** [comment]
change -1 to A difficulty

**Comment by Lorekeeper49** [comment]
The second value is not supposed to be negative

**Comment by Gostar64** [comment]
why is the difficulty -1?

**Comment by tylerandari12** [comment]
Exact opposite happened to me one time...
It would load other songs just fine but didnt reload the current song...

**Comment by ImaginationSuperHero528** [comment]
For yall confused -1 is current difficultly.

**Comment by ImaginationSuperHero528** [comment]
> The second value is not supposed to be negative 

-1 is current diff

**Comment by ImaginationSuperHero528** [comment]
> change -1 to A difficulty

-1 is current diff
