### ISSUE TITLE
Window Movement

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#10344]
### Describe your problem here.

I am coding a VS Bob Psych 0.6.2 Port. I just finished the main bob week, and I am working on Bob's Onslaught. I just need help on how to get the window moving (like in the OG Mod) if you're in Windowed Mode.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I am using ProjectFNF (https://github.com/l1ttleO/ProjectFNF/releases), which is a modified version of Psych.

**Comment by fnfdemonboi314159** [comment]
So, here are the 3 steps I plan to approach to finish Onslaught:

1. Extreme Camera Bop
2. Ads Flying all over the place
3. Window Movement

That is it. I just need Window Movement. Is there at least a script to help me here?

**Comment by tylerandari12** [comment]
I recomment using `math.cos` and `math.sin` to get circular movement...
```
setPropertyFromClass('openfl.Lib', 'application.window.x', 0);
setPropertyFromClass('openfl.Lib', 'application.window.y', 0);
```

**Comment by fnfdemonboi314159** [comment]
How should I move it in an Infinity Signs?

**Comment by fnfdemonboi314159** [comment]
nvm figured it out, thanks!
