### ISSUE TITLE
Freeplay menu text

### ISSUE THREAD

**Issue by EpicShapeShifter** [ShadowMario/FNF-PsychEngine#10345]
### What is your question?

Is there a way to make custom text appear on the screen in the freeplay menu depending on the song you've selected?

**Comment by jamuelthegamer** [comment]
Yes Source Code

**Comment by EpicShapeShifter** [comment]
That was, the idea

**Comment by WhittyOfficialFNF** [comment]
I don't know

**Comment by EpicShapeShifter** [comment]
It works now
