### ISSUE TITLE
My code doesn't work. Could anyone help me fix it? (SOURCE CODE)

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#10354]
### Describe your problem here.

So i want the code to make `camGame` to be invisible on one `curStep`, and then to re-appear. Here's my code:
```
		if (SONG.song == 'Mystery')
			function stepHit()
				if (curStep == 272) then;
					camGame.visible == false;
				end
				if (curStep == 304) then;
					camGame.visible == true;
				end
			end
		end
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

PlayState.hx

**Comment by CheesecakeForever** [comment]
nvm got it to work ig

**Comment by CheesecakeForever** [comment]
nevermind, new code here (**bold** is from PlayState.hx, `code` is mine):
	**override function stepHit()
	{
		super.stepHit();
		if (Math.abs(FlxG.sound.music.time - (Conductor.songPosition - Conductor.offset)) > 20
			|| (SONG.needsVoices && Math.abs(vocals.time - (Conductor.songPosition - Conductor.offset)) > 20))
		{
			resyncVocals();
		}

		if(curStep == lastStepHit) {
			return;
		}

		lastStepHit = curStep;
		setOnLuas('curStep', curStep);
		callOnLuas('onStepHit', []);**
/*	}
	{*/
	```
	if (SONG.song == "MYSTERY")
		{
			switch (curStep)
			{
				case 272:
					camGame.visible = false;
				case 304:
					camGame.visible = true;
			}
		}
```
		**super.stepHit();
	}**

**Comment by hayfii** [comment]
Um, that's now how you use functions either source code :)

**Comment by CheesecakeForever** [comment]
I've searched in the issues a bit and i've found the answer
