### ISSUE TITLE
Chart Crash (Psych Engine 0.6.2)

### ISSUE THREAD

**Issue by SonicMapper** [ShadowMario/FNF-PsychEngine#10356]
### Describe your bug here.

I was doing a cover of fatality, and when I went to test the chart for some reason the game warned that it hears a crash error

the Error:
Note.hx (line 124)
PlayState.hx (line 2353)
PlayState.hx (line 1053)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

I can no longer modify or play the chart
Please help me

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't change anything in the .HX files

**Comment by BeastlyGhost** [comment]
go to your chart's json file and replace every instance of `"lengthinSteps": 16,` with `"sectionBeats": 4,`
