### ISSUE TITLE
Linux Builds

### ISSUE THREAD

**Issue by Erisfiregamer1** [ShadowMario/FNF-PsychEngine#1035]
### What feature do you want to get added on the base engine?

Build Psych for Linux, so we can experience FNF without crashing.
(cmon man I want to suffer on Accelerant Hank already)

**Comment by Erisfiregamer1** [comment]
before you say you can't do it yourself, workflows.
just use that.

**Comment by ShadowMario** [comment]
Duplicate of #219

**Comment by Erisfiregamer1** [comment]
Not a duplicate. I would HAPPILY run the actions for the builds!
