### ISSUE TITLE
Stop the camGame from 'idling' 

### ISSUE THREAD

**Issue by Shaggers-official** [ShadowMario/FNF-PsychEngine#10359]
### Describe your problem here.

Hey, so i wanna make the camGame stop doing the idle thing, you know like at every section it does a small zoom, i just want to figure out a way of stopping it from doing so (it's probably very easy to do, im still learning)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHoovy** [comment]
you mean this?
```
function onUpdate(elapsed)
setProperty('camZooming', false);
end
```

**Comment by Shaggers-official** [comment]
it seems so obvious every single time, but i'm not even able to do it, thank you

**Comment by MemeHoovy** [comment]
> it seems so obvious every single time, but i'm not even able to do it, thank you

your welcome
