### ISSUE TITLE
Low health event script.

### ISSUE THREAD

**Issue by melocotonwaztaken** [ShadowMario/FNF-PsychEngine#10350]
### Describe your problem here.

Basically I need help with a lua script that triggers an event when boyfriend is at low health, basically let's say bf's health is at 30%, the event is triggered, if it's above 30% the event is removed.

Failed script : 
function onUpdate(elapsed)
  if health > -0.85 then
    triggerEvent('statt',15,'1')
  elseif health < -0.85 then 
    triggerEvent('statt',0.5,'0.5')
  end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Tried to make my own script but nothing happened

**Comment by frantastic24** [comment]
`health` doesn't exist, use `getHealth()`

**Comment by PogofruitKM** [comment]
Why are you checking negative health again?

**Comment by Mastercopper2346** [comment]
```lua
function onUpdate(elapsed)
     if getProperty(‘health’) > 0.6 then
          triggerEvent('statt',15,'1')
     elseif getProperty(‘health’) < 0.6 then
          triggerEvent('statt',0.5,'0.5')
     end
end

**Comment by melocotonwaztaken** [comment]
Thanks copper it worked, also the reason I used negative was to test if it was working or not..

**Comment by CrusherNotDrip** [comment]
if you fixed it then close it goddamn it

**Comment by melocotonwaztaken** [comment]
Sorry im new to github

**Comment by TheKitBoi** [comment]
right here
![close the dam issue](https://user-images.githubusercontent.com/84044666/187684674-a1fe2d99-5143-4f21-84a8-09962596fd90.jpeg)

**Comment by melocotonwaztaken** [comment]
wow im brainless fr
