### ISSUE TITLE
A function that returns all the animation names in an object

### ISSUE THREAD

**Issue by KirbyKid256** [ShadowMario/FNF-PsychEngine#10355]
### What feature do you want to get added on the **base** engine?

There should be a function that would return a list of all the animations that you put into an object. It would most likely use the Haxe function "getNameList()" and would list all the animations into an array.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
Literally just `tag.animation.curAnim.name`

**Comment by KirbyKid256** [comment]
I mean a function that gets all of the animations at once. Because I made an event that would allow a seamless transition between animations. Depending on the order of the animations (for example, animations named "a", "b", "c", and "d"), if the current animation is "a" and you change the animation to "d", it will first play a frame of animation "b" and animation "c" before animation "d".

**Comment by ShadowMario** [comment]
Idk if that's possible and there's very few use cases for it.
