### ISSUE TITLE
psych engine dont open on 0.6 above

### ISSUE THREAD

**Issue by NitneDT** [ShadowMario/FNF-PsychEngine#10357]
### Describe your bug here.

the engine dont open when its extracted, but open normal on zipped folder

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing, its just for mods they want the psych engine mods folder

**Comment by ZeitHeld** [comment]
did you try to change the location where you extract it?
