### ISSUE TITLE
Storymode button loads a week

### ISSUE THREAD

**Issue by EpicShapeShifter** [ShadowMario/FNF-PsychEngine#10352]
### Describe your problem here.

I'm trying to modify the main menu so that the story_mode button loads week 6 instead of the story mode menu.
For some reason it repeatedly crashes during the transition. (This image was taken in MainMenuState.hx), also attemption to make it load the week in hard mode.
![image](https://user-images.githubusercontent.com/112112290/187171199-32ba61fa-db02-4e75-913d-8b8d38b79910.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Changed the options in the main menu

**Comment by Reycko** [comment]
I guess you can try directly loading the song instead of doing it from the custom week.

**Comment by EpicShapeShifter** [comment]
oh ye

**Comment by EpicShapeShifter** [comment]
but what about the other songs in the week?

**Comment by EpicShapeShifter** [comment]
and loading the song directly doesn't seem to work either
