### ISSUE TITLE
can you help me

### ISSUE THREAD

**Issue by swobodac** [ShadowMario/FNF-PsychEngine#10362]
### Describe your problem here.

i want to make the icons bounce on the freeplay menu
btw i dont know how to code lol

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

wavy bg action bulid for 0.5.1 lol

**Comment by TheKitBoi** [comment]
Lua cannot be used outside of playstate

**Comment by Mastercopper2346** [comment]
> Lua cannot be used outside of playstate

https://github.com/ShadowMario/FNF-PsychEngine/issues/10324#issuecomment-1229072034
Says no but ok

**Comment by CrusherNotDrip** [comment]
> > Lua cannot be used outside of playstate
> 
> [#10324 (comment)](https://github.com/ShadowMario/FNF-PsychEngine/issues/10324#issuecomment-1229072034) Says no but ok

thats pause not freeplay buddy
and pause menu is a substate

**Comment by hayfii** [comment]
> > Lua cannot be used outside of playstate
> 
> [#10324 (comment)](https://github.com/ShadowMario/FNF-PsychEngine/issues/10324#issuecomment-1229072034) Says no but ok

The pause menu is INSIDE PlayState.hx you dum dum, the freeplay ISN'T!

**Comment by DisIsNOt** [comment]
Find the icon bounce code in PlayState or smth

**Comment by CrusherNotDrip** [comment]
> Find the icon bounce code in PlayState or smth

bruh

![image](https://user-images.githubusercontent.com/90648119/187589372-e00f17ae-d504-4859-a561-cd6cc37f3373.jpeg)

**Comment by DisIsNOt** [comment]
Lmao

**Comment by Parsellol** [comment]
cl,ose this issue as its not possible to be solved i think
