### ISSUE TITLE
Lua doTweenX help!!!

### ISSUE THREAD

**Issue by leobro1106** [ShadowMario/FNF-PsychEngine#10366]
### What is your question?

I tried to make an event in Lua that made a timer run then moved a sprite and faded it out, but only the fade worked as intended. The tweenX worked as soon as the event started, but the tweenAlpha worked after the timer was over, yet, they were in the SAME GOD DAMN FUNCTION. WHAT THE HELL!!!! Doctor! Help Me!!!

**Comment by frantastic24** [comment]
Where is the code

**Comment by leobro1106** [comment]
oh shit sorry
`function onCreate()
	makeAnimatedLuaSprite('uwu', 'SUNKEEEEHHHHHHHHH/uwu', 315, 150)
	addAnimationByPrefix('uwu', 'uwu', 'uwu', 24, false)
	setObjectCamera('uwu', 'camHUD')
	scaleObject('uwu', 0.75, 0.75)
	setProperty('uwu.alpha', 1)
end

function onEvent(name, value1, value2)
	if name == "uwu" then
		runTimer('fadeOut', 5)
		addLuaSprite('uwu', true)
		doTweenAlpha('uwu_tweenAlpha', 'uwu', 0.5, 2.5, 'linear')
	end
end

function onTimerCompleted(fadeOut)
	doTweenAlpha('uwu_tweenAlpha2', 'uwu', 0, 1.5, 'linear')
	doTweenX('uwu_tweenX', 'uwu', 415, 5, 'linear')
end`

**Comment by leobro1106** [comment]
It worked for about like 30 minutes but then it broke after editing the makeAnimatedLuaSprite x and y values

**Comment by frantastic24** [comment]
The only issue I see is that any timer will trigger the tweens, try adding a tag check

**Comment by leobro1106** [comment]
Thanks!
