### ISSUE TITLE
How do you fix this error?

### ISSUE THREAD

**Issue by TehSunkyMoment** [ShadowMario/FNF-PsychEngine#1036]
### Describe your bug here.

![unknown](https://user-images.githubusercontent.com/91031638/141692389-a882bc2e-e135-44b3-8458-f97c5a23795c.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Edited CreditsState.hx and MainMenuState.hx

**Comment by KFC-Chicken-1212** [comment]
![image](https://user-images.githubusercontent.com/89538185/141700279-7fc6dc20-ccf7-44a7-8f74-7b9c9c61b11e.png)

same issue

**Comment by ShadowMario** [comment]
Should be fixed now
