### ISSUE TITLE
the song inst and voices dont sync properly

### ISSUE THREAD

**Issue by LodedRick** [ShadowMario/FNF-PsychEngine#10361]
### Describe your bug here.

when i open a song the vocals and instrumental arent synced which makes the song sound like shit. I did check in fl studio and it was synced properly. is this fixable?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

not yet

**Comment by TheKitBoi** [comment]
get audacity to match inst and vocals together

**Comment by LodedRick** [comment]
> get audacity to match inst and vocals together

the song isnt synced only in game it is synced everywhere else

**Comment by ShinyXZ9** [comment]
The same thing is happening to mine and I don't know why
