### ISSUE TITLE
Some error came up and i dont really know what it means

### ISSUE THREAD

**Issue by Tweuebweue** [ShadowMario/FNF-PsychEngine#10364]
### Describe your bug here.

i was workin on adding a new week and after i compile the game in try to go in freeplay this comes up
(command prompt)
what do you guys think is going on?

### Command Prompt/Terminal logs (if existing)

```bash
FreeplayState.hx (line 74)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i dont know what it specifically was but it happened after adding a new week

**Comment by frantastic24** [comment]
Not a bug, it's an issue with your file
You can just make a new one
