### ISSUE TITLE
trying to compile psych engine

### ISSUE THREAD

**Issue by CodyGGaT** [ShadowMario/FNF-PsychEngine#10363]
### Describe your problem here.

ok im trying to compile psych engine for html5 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5/Browser

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Mastercopper2346** [comment]
`lime test html5` or
`lime build html5`

**Comment by Mastercopper2346** [comment]
C:

**Comment by CodyGGaT** [comment]
this is what i got
source/FunkinLua.hx:3073: characters 23-28 : Type not found : State
source/CoolUtil.hx:18: lines 18-141 : ... Defined in this class
source/PlayState.hx:3752: characters 40-68 : Class<FunkinLua> has no field getPropertyLoopThingWhatever
source/PlayState.hx:4895: characters 8-12 : FunkinLua has no field call
source/PlayState.hx:4896: characters 8-12 : FunkinLua has no field stop

**Comment by Mastercopper2346** [comment]
What version

**Comment by CodyGGaT** [comment]
0.6.2

**Comment by CrusherNotDrip** [comment]
> this is what i got source/FunkinLua.hx:3073: characters 23-28 : Type not found : State source/CoolUtil.hx:18: lines 18-141 : ... Defined in this class source/PlayState.hx:3752: characters 40-68 : Class has no field getPropertyLoopThingWhatever source/PlayState.hx:4895: characters 8-12 : FunkinLua has no field call source/PlayState.hx:4896: characters 8-12 : FunkinLua has no field stop

for the first error
go to funkinlua and go to the error and put
`#if LUA_ALLOWED`
on top of the function and then
`#end`
at the end of it
its a html5 skill issue

**Comment by CodyGGaT** [comment]
this is what i get now
source/FunkinLua.hx:72: characters 2-8 : public modifier is not supported for module-level fields
