### ISSUE TITLE
Charting Mode Bug 2: Electric Boogaloo

### ISSUE THREAD

**Issue by Unholywanderer** [ShadowMario/FNF-PsychEngine#10368]
### Describe your bug here.

If you go into the charting state, backspace into the Master Editor menu and backspace to the main menu, charting mode stays on just like in my previous issue

I don't think dat's quite right 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, raw Psych Engine goodness

**Comment by Lorekeeper49** [comment]
It's been that way since 0.5.2h and it's kinda annoying
