### ISSUE TITLE
It's This New Error?

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10360]
### Describe your bug here.

I Just Compiliing The Game And This It's Happened:
![Screenshot_20220829-223704~2](https://user-images.githubusercontent.com/109828559/187294756-f37a20c8-e553-49b5-94c9-73986042cc82.png)
Windows Build Has Have The Problem.

### Command Prompt/Terminal logs (if existing)

```bash
1s
Run haxelib run lime build windows --app-version="4.0.0-2951547312"
Called from ? line 1
Called from CommandLineTools.hx line 1895
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 125
Called from CommandLineTools.hx line 1703
Called from lime/tools/ProjectXMLParser.hx line 21
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 50
Called from lime/tools/ProjectXMLParser.hx line 2043
Called from lime/tools/ProjectXMLParser.hx line 1528
Called from lime/tools/ProjectXMLParser.hx line 608
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 709
Called from /Users/runner/hostedtoolcache/haxe/4.2.1/x64/std/neko/_std/sys/FileSystem.hx line 69
Called from /Users/runner/hostedtoolcache/haxe/4.2.1/x64/std/neko/_std/sys/FileSystem.hx line 60
Uncaught exception - std@sys_file_type
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yeah

**Comment by Chidubemmo** [comment]
I'm no programmer but I think you need you reinstall haxe ( and possibly the libs)

**Comment by StefanBETA2008** [comment]
> I'm no programmer but I think you need you reinstall haxe ( and possibly the libs)

Nevermind, I Just Fixed
