### ISSUE TITLE
Error when trying to start the songs in the game

### ISSUE THREAD

**Issue by Piero03** [ShadowMario/FNF-PsychEngine#10365]
### Describe your bug here.

Basically, every time I tried to play a song (Freeplay), the game crashes and a message appears explaining what happened.
Problem is, I'm using the no-code version, so I can't do much.

Detail: This does not occur in Senpai's week.

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
Character.hx (line 164)
PlayState.hx (line 912)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
(Text speaking to warn you.)

> Crash Handler written by: sqirra-mg
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not. I didn't change any code.

**Comment by frantastic24** [comment]
Not a bug
Missing girlfriend texture files

**Comment by Piero03** [comment]
> Not a bug Missing girlfriend texture files
Oh, that's right, i see it now. Thanks!
