### ISSUE TITLE
Trying To Get The Time To Tween Of Multiple Objects To Sync With Any BPM And Chart Speed

### ISSUE THREAD

**Issue by LuckyMist8** [ShadowMario/FNF-PsychEngine#10379]
### Describe your problem here.

I'm Trying To Re-Create The Little Beat Bars In Games Like Guitar Hero That Scroll With The Notes And The Notes Are Like Attached To Them. But I Need Them To Be Synced With The BPM And Chart Speed Of Any Song.

onBeatHit Would Spawn My Object On The Right Beat, But I Need The Time To Complete YTween To Match That Of The Time 16 Steps Takes To Pass In The Song

Something Like Using onCountdownTick To Spawn Them Early As The Song Starts So The First Beat Line Reaches The Arrows As Soon As The Song Starts Playing (Downscroll Only Btw)

And Obviously Using onTweenCompleted To Reset The Positions And "Looping" It

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I Haven't Touched Source Code At All

**Comment by tylerandari12** [comment]
All I know is the `crochet` and `stepCrochet` variables are supposed to be the time in between hits, but I could never get them to work...

**Comment by LuckyMist8** [comment]
So Now I Need To Figure Out How To Translate getProperty('crochet') Into A Time Variable For The YTweens?

**Comment by LuckyMist8** [comment]
I'm Pretty Sure There May Not Be A Chart Speed Variable To Get, So Imma Use The Constant Speed Setting In Psych Options Lol

Still Need To Figure Out The 'crochet' Thing

**Comment by LuckyMist8** [comment]
I Used `60/curBpm` Which Gives Me The Right Time Per Beat Of Any Bpm

Can Confirm `crochet` Is Not What I'm Looking For

I Have Also Managed To Use This : `setProperty('songSpeed', 480/curBpm)` Which Gets Me VERY CLOSE

But My Tweens Are Delayed For Some Reason And After Enough Time To Beat Hits Get Desynced Anyway Ugh
