### ISSUE TITLE
Are the week 6 arrows suppose to be this small?

### ISSUE THREAD

**Issue by yourself62** [ShadowMario/FNF-PsychEngine#1037]
### What is your question?

Alright so I'm using 0.4.2 and when I launched it up with lime test windows I go to week 6 and the arrows are usually small, I'm not
 sure if they're suppose to be like that but based off other versions they're not that small, but if they are suppose to be that small are they anyways I can change the size of the notes?
![smallarrows](https://user-images.githubusercontent.com/78885503/141692627-45a891c7-bb25-4585-ad13-98590394f447.PNG)

**Comment by CrusherMods** [comment]
its happening to me too

**Comment by gaminbottomtext** [comment]
Did you change the swagWidth in note.hx, that might be the problem
