### ISSUE TITLE
stage

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#10373]
### What is your question?

whas the variable for stages in lua I couldn't find it on the wiki.

```lua
if stage == 'school' then
       canMove = false
end
```

**Comment by CrusherNotDrip** [comment]
try curStage, you might have to try getProperty though

**Comment by tylerandari12** [comment]
I just went and looked and there is no variable for the current stage...

**Comment by TFLTV** [comment]
> I just went and looked and there is no variable for the current stage...

a

**Comment by CrusherNotDrip** [comment]
OH WAIT YOU HAVE TO GET IT FROM THE SONG PROPERTY MB MB
use getProperty('SONG.curStage') maybe????
