### ISSUE TITLE
I want to rotate the note track so the notes come from the side

### ISSUE THREAD

**Issue by Ace5542** [ShadowMario/FNF-PsychEngine#10378]
Ex:https://www.youtube.com/watch?v=qzlu4NV776A  1:14

**Comment by wubbzyfan** [comment]
It’s not possible right now :(

**Comment by Ace5542** [comment]
> It’s not possible right now :(

so umm setPropertyFromGroup('playerStrums', 0, 'direction', 150); 
:)

**Comment by wubbzyfan** [comment]
wait really

**Comment by wubbzyfan** [comment]
doesnt work

**Comment by MemeHoovy** [comment]
> doesnt work

setPropertyFromGroup('playerStrums', whicharrow(0-4,) 'x or y', anynumber);

For example
```
for i = 0, 3 do
setPropertyFromGroup('playerStrums', i, 'x', 500);
end
```
don't know what that does to the notes but find out for yourself

**Comment by Ace5542** [comment]
> > doesnt work
> 
> setPropertyFromGroup('playerStrums', whicharrow(0-4), 'x or y', anynumber);
> 
> For example
> 
> ```
> for i = 0, 3 do
> setPropertyFromGroup('playerStrums', i, 'x', 500);
> end
> ```
> 
> don't know what that does to the notes but find out for yourself

It rotates the strum

**Comment by MemeHoovy** [comment]
> > > doesnt work
> > 
> > 
> > setPropertyFromGroup('playerStrums', whicharrow(0-4), 'x or y', anynumber);
> > For example
> > ```
> > for i = 0, 3 do
> > setPropertyFromGroup('playerStrums', i, 'x', 500);
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > don't know what that does to the notes but find out for yourself
> 
> It rotates the strum
> 
> Ex: setPropertyFromGroup('playerStrums', 0, 'direction', 150);
Here's for all the strums.
```
for i = 0, 3 do
setPropertyFromGroup('playerStrums', i, 'direction', 150);
end
```

**Comment by wubbzyfan** [comment]
IT WORK!

**Comment by MemeHoovy** [comment]
And here's an example of splitscroll
```
function onCreatePost()
for i = 2,4 do
setPropertyFromGroup('playerStrums', i, 'y', 550);
setPropertyFromGroup('playerStrums', i, 'downScroll', true)
end
end
```
