### ISSUE TITLE
More LUA Features

### ISSUE THREAD

**Issue by N1CKN0TAD3** [ShadowMario/FNF-PsychEngine#10374]
### What feature do you want to get added on the **base** engine?

Hello devs//idk who, And I exist to tell you that you should add more lua function to the engine. Like, Example:

--Main menu redesign made into one lua script you can code

And on the side if you could:

--UI editor (a thing you could add to the editors)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by frantastic24** [comment]
Duplicate + won't do

**Comment by Mastercopper2346** [comment]
Bro noooooo

**Comment by TheKitBoi** [comment]
> ### What feature do you want to get added on the **base** engine?
> Hello devs//idk who, And I exist to tell you that you should add more lua function to the engine. Like, Example:
> 
> --Main menu redesign made into one lua script you can code
> 
> And on the side if you could:
> 
> --UI editor (a thing you could add to the editors)
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Proper credit that was forgotten

Add them urself

**Comment by MaybeMaru** [comment]
failed test +  bad features

**Comment by MemeHoovy** [comment]
test failed

**Comment by tylerandari12** [comment]
These are cool but they would take a lot of time to make...

Also for future reference under the thing that you put what NOT to request, put stage editor, 6k support, and winning icons...

**Comment by CrusherNotDrip** [comment]
> These are cool but they would take a lot of time to make...
> 
> Also for future reference under the thing that you put what NOT to request, put stage editor, 6k support, and winning icons...

the whole point of the test was if they could read or not though
it already basically tells the answer
