### ISSUE TITLE
Is it possible to change the offset/position of the Ratings? (Sick, Good, Bad, Shit)

### ISSUE THREAD

**Issue by ItsMeTyler25** [ShadowMario/FNF-PsychEngine#10376]
### Describe your problem here.

Hi! So I'm trying to figure out if there's a way to change the offset of the Ratings but I couldn't find anything.

Is this possible? Any help is appreciated!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I have not, using Lua.

**Comment by DisIsNOt** [comment]
Ratio + Find it in the settings

**Comment by ItsMeTyler25** [comment]
> Ratio + Find it in the settings

Sorry I should I have been more clear. Is it possible to do using Lua? Like a setProperty() or something similar to that?

**Comment by DisIsNOt** [comment]
Like may be no

**Comment by NKTCurrect** [comment]
May it help you? https://gamebanana.com/questions/45942
