### ISSUE TITLE
Is this possible in psych engine?

### ISSUE THREAD

**Issue by TheManwhoisdyinghere** [ShadowMario/FNF-PsychEngine#10371]
### What is your question?

I want to spin a character with a script but i dont even know if that is possible **(i also dont know the code to do it)**

example of what im trying to do:
![Can i do this](https://user-images.githubusercontent.com/95798867/187480068-d1b8fcf5-7a0b-4524-9992-06b3c4b6be09.gif)

**Comment by DisIsNOt** [comment]
doTweenAngle

**Comment by TheManwhoisdyinghere** [comment]
> doTweenAngle

**what :(**
**where??**

**Comment by Meme1079** [comment]
`doTweenAngle(tag, object, value, duration, ease)`

Example:
`doTweenAngle('tag', 'boyfriend', 360, 1.5, 'linear')`

Note:
The tag from the tween calls `onTweenCompleted(tag)` after the tween is finish

**Comment by TheManwhoisdyinghere** [comment]
> `doTweenAngle(tag, object, value, duration, ease)`
> 
> Example:
> 
> ```lua
> function onCreatePost()
>      doTweenAngle('tag', 'boyfriend', 360, 1.5, 'linear') -- does a 360 angle on bf
> end
> ```
> 
> Note: The tag from the tween calls `onTweenCompleted(tag)` after the tween is finish
> 
> And if you called it with the same `tag` it will cancel the tween

Thank you

**Comment by TheKitBoi** [comment]
Close this issue
![E17282E1-F75A-40B9-AB8E-19A003C0EC64](https://user-images.githubusercontent.com/84044666/187499341-cefcee8c-936b-4a68-969b-65e785ab98f6.jpeg)
