### ISSUE TITLE
I need some help.

### ISSUE THREAD

**Issue by Ollieq1977336** [ShadowMario/FNF-PsychEngine#10370]
### Describe your problem here.

I need help making a danger note. Im using the ERECT BF SKIN From the ERECT BOPEEBO song. So can anyone of you help me? I want it so when you hit the danger note BF will play the dodge animation based on the note direction hit.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited Note.hx.

**Comment by Mastercopper2346** [comment]
I would send code but I’m gonna be busy

**Comment by Mastercopper2346** [comment]
I’ll be back spon

**Comment by CrusherNotDrip** [comment]
Doesn't that one accelerant hank mod do this already?
