### ISSUE TITLE
Does anybody know if it is possible to check system Specs with source

### ISSUE THREAD

**Issue by EgguMan** [ShadowMario/FNF-PsychEngine#10383]
### What is your question?

Hello, for one of my projects I would like the game to automatically identify how much ram you have and change a BG based off that (and possibly some clientPrefs) to make sure the game runs well

I am using an extremely large BG (30,000 x 4000) for high, medium sized BG (10,000x4000) and small sized BG (4,000x4,000)

Does anybody know if I could do something like the following

`if (systemRam <= 4) {
      ClientPrefs.BgQuality = low;
} else if (systemRam <= 8) {
      ClientPrefs.BgQuality = medium;
} else if (systemRam <= 16 or systemRam > 16) e
      ClientPrefs.BgQuality = high;
}
`
I do not need you to ask what it is for, why I am doing it, or how I can make the images smaller. The images are the best they can be and they will not change.

**Comment by EgguMan** [comment]
Sorry for poor formatting, I’m on mobile and github is blocked at my schools.

**Comment by MemeHoovy** [comment]
```
if (Math.pow(2, 32) < Math.pow(2, 32)) { ClientPrefs.BgQuality = low; } elseif (Math.pow(2, 32) * 2.0 < Math.pow(2, 32) * 2.0) { ClientPrefs.BgQuality = medium; } elseif (Math.pow(2, 32) * 4.0 < Math.pow(2, 32) * 4.0 || Math.pow(2, 32) * 4.0 > Math.pow(2, 32) * 4.0) ClientPrefs.BgQuality = high; }
```
