### ISSUE TITLE
Can someone help me develop a animated bg change event?

### ISSUE THREAD

**Issue by melocotonwaztaken** [ShadowMario/FNF-PsychEngine#10382]
### Describe your problem here.

Hello I was wondering if someone could help me script a animated bg change event for nicos rap bots! It would be so helpful if possible!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by DisIsNOt** [comment]
`
function onCreate()

         makeLuaSprite('stage1', 'bg', 0,0)
          addLuaSprite('stage1', false)

          makeLuaSprite('stage2', 'bg2', 0,0)
         
   

end


function onStepHit()
       if curStep == 1 then
            addLuaSprite('stage2', false)
      end




end


    `

**Comment by melocotonwaztaken** [comment]
thx
