### ISSUE TITLE
i also got this error

### ISSUE THREAD

**Issue by Tamir-YT** [ShadowMario/FNF-PsychEngine#10389]
### Describe your bug here.

i also got this error

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
FreeplayState.hx (line 377)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/faker/faker-hard.json]

how can i fix it???
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Not a bug
Missing chart

**Comment by tylerandari12** [comment]
> Not a bug Missing chart

Hard chart specifically...
