### ISSUE TITLE
Window Un-focus

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#10386]
### Describe your problem here.

How can I make it so that when I click out of the game window it isn't paused.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHoovy** [comment]
```
FlxG.autoPause = false;
```

**Comment by bruh1cat** [comment]
> ```
> 
> FlxG.autoPause = false;
> 
> ```

Where would I put it?

**Comment by MemeHoovy** [comment]
> > ```
> > 
> > FlxG.autoPause = false;
> > ```
> 
> Where would I put it?

In main, in the "SetupGame" function or something, or whatever state you want it to be in.

**Comment by Mastercopper2346** [comment]
Nice

**Comment by bruh1cat** [comment]
> Nice

Wym nice?

**Comment by bruh1cat** [comment]
> > > ```
> 
> > > 
> 
> > > FlxG.autoPause = false;
> 
> > > ```
> 
> > 
> 
> > Where would I put it?
> 
> 
> 
> In main, in the "SetupGame" function or something, or whatever state you want it to be in.
> 
> 
> 
> And don't forget to import this.
> 
> ```
> 
> import flixel.FlxG;
> 
> ```

I'll try the import stuff later but maybe that's why it wasn't working

**Comment by tylerandari12** [comment]
> > Nice
> 
> Wym nice?

He means nice...

**Comment by bruh1cat** [comment]
> > > Nice
> 
> > 
> 
> > Wym nice?
> 
> 
> 
> He means nice...

I just found it weird.
