### ISSUE TITLE
I cannot launch the psych engine

### ISSUE THREAD

**Issue by 02012002** [ShadowMario/FNF-PsychEngine#10381]
### Describe your bug here.

I cannot launch the psych engine when un-zipped. Can anyone help me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just downloaded the update

**Comment by Mastercopper2346** [comment]
Double click the exe

**Comment by TFLTV** [comment]
If you're building it, then reinstall luaJIT

**Comment by 02012002** [comment]
> If you're building it, then reinstall luaJIT

I am using LUA

**Comment by 02012002** [comment]
> Double click the exe

I do, but it only load and not open

**Comment by tylerandari12** [comment]
If it loads the window but just shows a black screen then you might not have your audio device hooked up...

**Comment by 02012002** [comment]
> If it loads the window but just shows a black screen then you might not have your audio device hooked up...

it didn't load the window

**Comment by 02012002** [comment]
No one is answering so ye...
