### ISSUE TITLE
What can cause images to not appear

### ISSUE THREAD

**Issue by EgguMan** [ShadowMario/FNF-PsychEngine#10385]
### Describe your problem here.

I am making an infinately scrolling BG with FlxBackdrop, and for everyone BUT me its appearing as completly black

theyve tried it with the full 30,000x4000 images, and the 6000x4000 images, but to no avail. Snippit of code below.

`var void:FlxSprite = new FlxSprite().loadGraphic(Paths.image('void'));
					void.y = -1000;
					void.x = -1500;
					void.scale.set(50,50);
					void.scrollFactor.set(0,0);
					void.antialiasing = ClientPrefs.globalAntialiasing;
					void.updateHitbox();
					add(void);`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, playstate.

**Comment by Grape-Boy** [comment]
maybe their computers can't handle the huge file

**Comment by EgguMan** [comment]
> maybe their computers can't handle the huge file

I get it, but 6000x4000 is not huge. BF is 8000x8000
