### ISSUE TITLE
Negative offset plzz

### ISSUE THREAD

**Issue by MrMusical** [ShadowMario/FNF-PsychEngine#10380]
### What feature do you want to get added on the **base** engine?

Would be coolswag if ya'll added negative offset, i cant play songs without them sounding off thx xoxo

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
Huh???? Is your audio playing on the future or what

**Comment by MrMusical** [comment]
no no, I end up hitting a lot of notes late due to my audio being delayed and normally I set my offset to around -20 ms but on psych engine the lowest I can go is 0 so it would be nice if it was brought down to like idk -500 ig since the max is 500

**Comment by ShadowMario** [comment]
If your audio is delayed, you gotta set the offset to +20, not -20

**Comment by MrMusical** [comment]
It doesn't work like that tho? If I set my offset as +20 in psych it becomes even more late then it already was meaning I need to lower it, just make the minimum around -500 or something

**Comment by tylerandari12** [comment]
> Huh???? Is your audio playing on the future or what

This phenomenon happens because the monitor is slow...
His audio is fine its the visuals that are delayed...

**Comment by AyMarte** [comment]
If neither -20 nor +20 work, use +0

**Comment by KookerFoxYT** [comment]
probably #9847 this should help
