### ISSUE TITLE
Song Dependent FPS Cap?

### ISSUE THREAD

**Issue by Blade204** [ShadowMario/FNF-PsychEngine#10387]
### What is your question?

Would it be possible (using either lua or source) to modify the FPS Cap on a song-to-song basis? 
For example: A script that will force the FPS Cap to 60, but only while playing Bopeebo.

I've looked through the issues and found [this comment here](https://github.com/ShadowMario/FNF-PsychEngine/issues/8106#issuecomment-1098293549) but their script seems to not work at all. 
For reference, my FPS Cap is set to 240, and I'd like to lower it to 60. I'm also running the latest version of the engine if that makes a difference.

**Comment by Meme1079** [comment]
```lua
function onCreate()
     setPropertyFromClass('ClientPrefs', 'framerate', 60)
end
```

**Comment by Blade204** [comment]
Awesome, thanks.
