### ISSUE TITLE
how to change scroll direction midsong

### ISSUE THREAD

**Issue by LiterallyWize** [ShadowMario/FNF-PsychEngine#10392]
`setPropertyFromClass('ClientPrefs', 'downScroll', true)` doesnt seem to work

**im using 0.5.2h**

**Comment by wubbzyfan** [comment]
setPropertyFromGroup('(opponentStrums/playerStrums)', (0 for left, 1 for down, 2 for up, 3 for right), 'downScroll', (false/true))
