### ISSUE TITLE
How to change the texture of a single note/The left note using Lua?

### ISSUE THREAD

**Issue by ItsMeTyler25** [ShadowMario/FNF-PsychEngine#10391]
### Describe your problem here.

Hi! So I'm trying to change only one of the four notes texture using Lua. I've found many scripts and lines of code that change them all four notes, but I'm confused on how to change only one? 

Any help is appreciated with this!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I have not, using Lua.

**Comment by frantastic24** [comment]
Simply don't use the `for` statement

**Comment by ItsMeTyler25** [comment]
> Simply don't use the `for` statement

Ok I tried it and it seemed to only change the strumLineNote? Here's the code I tried in case I did something wrong.

`function onCreatePost()
	   setPropertyFromGroup('playerStrums', 0, 'texture', 'Note Skins/majin')
	   setPropertyFromGroup('unspawnNotes', 0, 'texture', 'Note Skins/majin')
end`

My apologies if I'm missing something.

**Comment by frantastic24** [comment]
You didn't mention you were also changing notes, you will need the `for` to do that
Then check unspawnNotes `noteData` to only change left arrows

**Comment by ItsMeTyler25** [comment]
> You didn't mention you were also changing notes, you will need the `for` to do that Then check unspawnNotes `noteData` to only change left arrows

Thanks so much it worked!
