### ISSUE TITLE
Setting Note Skin In Lua Overwrites Special Notes' Skin

### ISSUE THREAD

**Issue by LuckyMist8** [ShadowMario/FNF-PsychEngine#10395]
### Describe your problem here.

How Do I Change The Note Skin Of The Default Arrows And Default Pixel Arrows In Lua WITHOUT Overwriting Other Custom Notes? 

``` Lua
function onCreatePost()
                for i = 0, getProperty('playerStrums.length')-1 do
			setPropertyFromGroup('playerStrums', i, 'texture', 'NOTE_guitar');
		end
		for i = 0, getProperty('unspawnNotes.length')-1 do
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'NOTE_guitar');
			end
		end
		for i = 0, getProperty('unspawnNotes.length')-1 do
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'guitarSplashes');
			end
	end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I Haven't Touched Source Code At All

**Comment by frantastic24** [comment]
```lua
if getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' then
```

**Comment by LuckyMist8** [comment]
It Doesn't Seem To Work

if getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' then
		for i = 0, getProperty('playerStrums.length')-1 do
			setPropertyFromGroup('playerStrums', i, 'texture', 'NOTE_guitar');
		end
		for i = 0, getProperty('unspawnNotes.length')-1 do
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'NOTE_guitar');
			end
		end
		for i = 0, getProperty('unspawnNotes.length')-1 do
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'guitarSplashes');
			end
		end
	end

**Comment by frantastic24** [comment]
Why is it outside the `for` statement
Why are there 2 `for` statements that do the same thing

**Comment by LuckyMist8** [comment]
Like This?
```Lua
		for i = 0, getProperty('playerStrums.length')-1 do
			if getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' then
			setPropertyFromGroup('playerStrums', i, 'texture', 'NOTE_guitar');
		end
		for i = 0, getProperty('unspawnNotes.length')-1 do
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') and getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'NOTE_guitar');
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'guitarSplashes');
			end
		end
	end
```

**Comment by LuckyMist8** [comment]
> Like This?
> 
> ```lua
> 		for i = 0, getProperty('playerStrums.length')-1 do
> 			if getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' then
> 			setPropertyFromGroup('playerStrums', i, 'texture', 'NOTE_guitar');
> 		end
> 		for i = 0, getProperty('unspawnNotes.length')-1 do
> 			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') and getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' then
> 			setPropertyFromGroup('unspawnNotes', i, 'texture', 'NOTE_guitar');
> 			setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'guitarSplashes');
> 			end
> 		end
> 	end
> ```

This Does Work After Testing Thank You
I'm A Sloppy Coder Lol

**Comment by frantastic24** [comment]
Remove it from the first `for`, it has nothing do with notes

**Comment by LuckyMist8** [comment]
``` Lua
if getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' or 'GF Sing' or 'No Animation' then
```

I'm Trying To Add More Than 1 Notetype To Be Changed Now And This Doesn't Work Lol

**Comment by frantastic24** [comment]
You have add the `getPropertyFromGroup` stuff each time

**Comment by LuckyMist8** [comment]
> You have add the `getPropertyFromGroup` stuff each time

``` Lua
if getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' and getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'No Animation' then
```
Also Does Nothing, But Knowing Me I'm Probably Writing It Wrong Again Augh

**Comment by LuckyMist8** [comment]
Here Is My Full Current Code
``` Lua
function onCreatePost()

	if DADG == 'yes' then
	for i = 0, getProperty('opponentStrums.length')-1 do
			if getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' then
			setPropertyFromGroup('opponentStrums', i, 'texture', 'NOTE_guitar');
		end
		for i = 0, getProperty('unspawnNotes.length')-1 do
			if getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' or getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'No Animation' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'NOTE_guitar');
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'guitarSplashes');
			end
		end
	end
end
```
