### ISSUE TITLE
Missing Move Event

### ISSUE THREAD

**Issue by AyMarte** [ShadowMario/FNF-PsychEngine#10398]
### What needs to be documented?

Do you know anything about the missing _Move Notes Event_? Because The [Page](https://github.com/ShadowMario/FNF-PsychEngine/discussions/893?sort=new) Is Gone.

**Comment by Mastercopper2346** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers#notetweenxtagstring-noteint-valuedynamic-durationfloat-easestring

**Comment by wubbzyfan** [comment]
discussions got thanos snapped on april 1st and never returned. Why shadow Mario.

**Comment by CrusherNotDrip** [comment]
> Why shadow Mario.

shit moderation
and more importantly
shit spamming

**Comment by silvashp** [comment]
and more importantly
dnb fans
