### ISSUE TITLE
Stage loading crashes the application

### ISSUE THREAD

**Issue by Yoshi-RBLX** [ShadowMario/FNF-PsychEngine#10397]
### Describe your bug here.

So I'm tryna get a stage for my mod working, it's a good enough size, the script is working (cause it's the same scripts as the other stages in my mod, which are working) but this time, when I load the stage, it freezes when it's supposed to start the countdown, waits like 2-3 seconds, and then crashes (also i'm on v0.5.2h because it's IMO one of the best versions) so is there a way to fix this, also if you need the stage stuff, here it is rq:

btw sorry github messed up how the things are shown, very weird

json

{
	"directory": "",
	"defaultZoom": 0.9,
	"isPixelStage": false,
	"hide_girlfriend": false,

	"boyfriend": [770, -375],
	"girlfriend": [700, -275],
	"opponent": [100, -375]
}

lua

function onCreate()
	-- background shit
	makeLuaSprite('turtle-tops', 'turtle-tops', -600, -300);
	setScrollFactor('turtle-tops', 0.9, 0.9);

	addLuaSprite('turtle-tops', false);
	
	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end

Hope this can be fixed! :D

### Command Prompt/Terminal logs (if existing)

```bash
Doesn't show an error, yet it shows it's "successfully loaded the stage"
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

changed the not associated with newgrounds text in titlestate.hx and the app name in project.xml file

**Comment by DisIsNOt** [comment]
Dude idk may be remove the close(true)

**Comment by Yoshi-RBLX** [comment]
@DisIsNOt didn't work, still crashes in the same amount of time.

**Comment by Yoshi-RBLX** [comment]
I think I may have found my issue, it wasn't the stage, it was the character I chose as GF, I'll look into that so it'll work.

**Comment by DisIsNOt** [comment]
Ok nice
