### ISSUE TITLE
How to add gallery

### ISSUE THREAD

**Issue by Nemophyya** [ShadowMario/FNF-PsychEngine#10393]
### What is your question?

I feel like I've used this place many times, but I opened this because I wanted to know something new.

How do I add a gallery like Twinsomnia, etc.?

There is a proposal in my mod production team to add a gallery to include artwork and fanart, but I don't know how to do it.
Does anyone know of a way to do this that would be helpful?

**Comment by LilMewo** [comment]
Is your mod by any chance source code?

**Comment by DisIsNOt** [comment]
If you're making a source mod just make a new State or somthing

**Comment by Nemophyya** [comment]
> Is your mod by any chance source code?

Yes.
We haven't gotten around to any sort of source code yet, but we are convinced that it will be needed.
