### ISSUE TITLE
Funkin Lua issues

### ISSUE THREAD

**Issue by CodyGGaT** [ShadowMario/FNF-PsychEngine#10396]
### Describe your problem here.

im trying to add mirror mode but i keep getting funkin lua errors even though im not messing with funkin lua how do i fix this error source/FunkinLua.hx:333: lines 333-337 : Int should be Bool
source/FunkinLua.hx:333: lines 333-337 : ... For function argument 'f'
source/FunkinLua.hx:439: lines 439-442 : Int should be Bool
source/FunkinLua.hx:439: lines 439-442 : ... For function argument 'f'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes i added a lot of stuff

**Comment by frantastic24** [comment]
Duplicate, search other issues

**Comment by marius851000** [comment]
For people looking at this later, said duplicate bug is https://github.com/ShadowMario/FNF-PsychEngine/issues/10103 (it is the first result on GitHub)
