### ISSUE TITLE
I'm just wondering

### ISSUE THREAD

**Issue by KillerAvecRage** [ShadowMario/FNF-PsychEngine#10409]
### Describe your problem here.

Hi,

I've seen this new feature that was added in v0.6.0:
_"Ratings data can be changed through Lua"_
However I don't know what this means and how to use it, can I have help with that?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by swobodac** [comment]
this might help btw also works with 0.5.1
`function onUpdate()
    if ratingName == 'Sick!' then
        setRatingName('Replace Me')
    end
    if ratingName == 'Perfect!!' then
        setRatingName('Replace Me')
    end
    if ratingName == 'Nice' then
        setRatingName('Replace Me')
    end
    if ratingName == 'You Suck!' then
        setRatingName('Replace Me')
    end
    if ratingName == 'Shit' then
        setRatingName('Replace Me')
    end
    if botPlay then
        setRatingName('Replace Me')
    end
    if ratingName == 'Meh' then
        setRatingName('Replace Me')
    end
    if ratingName == 'Bad' then
        setRatingName('Replace Me')
    end
    if ratingName == 'Good' then
        setRatingName('Replace Me')
    end
end
`
replace "Replace Me" with whatever

**Comment by KillerAvecRage** [comment]
Thanks! However I thought you could be able to change the accuracy needed for a rating to appear, is this possible with lua?

**Comment by frantastic24** [comment]
Ratings data refers to hit judgement (sick, good, etc), accuracy rating has been editable for a long time and you can find how if you search in issues

**Comment by KillerAvecRage** [comment]
Aaaaah I see, well I misunderstood then, thanks again !
