### ISSUE TITLE
I need help please

### ISSUE THREAD

**Issue by randomcat119** [ShadowMario/FNF-PsychEngine#10403]
### Describe your problem here.

i need help what does this mean?
<img width="443" alt="Screenshot 2022-09-01 205233" src="https://user-images.githubusercontent.com/112675356/188049226-fe0327eb-9e2b-4e5a-a8e3-9f0e078402f7.png">

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by DisIsNOt** [comment]
song or

**Comment by BernardoGP4504** [comment]
chart either does not exist or the file is messed up
