### ISSUE TITLE
Bug with Adding New Songs to the Mods Folder

### ISSUE THREAD

**Issue by BoxOfGolds** [ShadowMario/FNF-PsychEngine#10401]
### Describe your bug here.

Every time I put a song in the mods folder and try to access it in Freeplay, this error pops up. 

(also gonna mention I have the source code but I couldn't compile it because of a bunch of errors with Haxe. This issue is from the Lua Build)

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
FreeplayState.hx (line 377)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/complicated/complicated.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Declock** [comment]
check if u have a JSON file for the chart

**Comment by BoxOfGolds** [comment]
> check if u have a JSON file for the chart
okay so the issue was I accidentally put the wrong name for the song chart file lmao

sorry for taking up your time
