### ISSUE TITLE
Is it just me or does every single build from Actions crash whenever you play like 20+ seconds of a song?

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#10400]
### What is your question?

Seriously, why does every build crash? I just wanna use function earlyEventTrigger! It’s not even related to the function, it crashes even with base game, no mods if it’s a build from Actions! What’s going on! It doesn’t even give a report, it just dies!

**Comment by SrtHero278** [comment]
Are you not getting a window when it crashes?

**Comment by wubbzyfan** [comment]
None
