### ISSUE TITLE
Force a lua sprite to do a different animation

### ISSUE THREAD

**Issue by DinoBobby** [ShadowMario/FNF-PsychEngine#10415]
### Describe your problem here.

I want a lua sprite to interrupt mid animation to preform a different one. I've tried using the force:true passthrough on objectPlayAnimation, but to no avail.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
New animations will always override the current one, `force` just means it will restart if the current animation is played again

**Comment by DinoBobby** [comment]
first off thanks for replying so fast!!
but If you wouldn't mind, when you get a good second, 
looking at the .lua script:
![image](https://user-images.githubusercontent.com/60831563/188253183-482ee50e-3822-482c-819f-13627875c3f9.png)
the events in the chart editor:
![image](https://user-images.githubusercontent.com/60831563/188253188-994e518b-ec3e-44d5-aadf-40b2c86739ad.png)
and help me with why they wont play 😭 

https://user-images.githubusercontent.com/60831563/188253376-56a0bf44-72ef-4a9d-aef2-bdfc320d2411.mp4

**Comment by DinoBobby** [comment]
nvm im so dumb looking at it like this made me see SingDown is not SingDOWN
