### ISSUE TITLE
Change stages

### ISSUE THREAD

**Issue by Ethian876** [ShadowMario/FNF-PsychEngine#10410]
### What is your question?

How to switch from one stage to another

**Comment by N1CKN0TAD3** [comment]
https://youtube.com/watch?v=vQswzz9dfgc&adlt=strict&toWww=1&redig=84EF1D070DCB4A04989A5ECB97EAB763 here. this video should help.

**Comment by Ethian876** [comment]
didnt work

**Comment by Parsellol** [comment]
u cant
just make objects visible and invisible at certain parts of the song

**Comment by Ethian876** [comment]
oh ok a little disappointed

**Comment by frantastic24** [comment]
This has been asked a million times already
Close the issue

**Comment by Ethian876** [comment]
ok
