### ISSUE TITLE
if Variable in Haxe

### ISSUE THREAD

**Issue by NotAhmedEpic** [ShadowMario/FNF-PsychEngine#10416]
### What is your question?

Basically
I wrote a code to change language in my custom Psych Engine build, but I dont understand something.
For example, if it was lua you could just write if GetPropertyFromClass('ClientPrefs', currentLanguage=English) and much more things like that. Does a kind of familar to Lua's if variable exist in Haxe/HaxeFlixel? Sorry if you don't understand anything

**Comment by NotAhmedEpic** [comment]
Better example:
So, in this screenshot, after the black line I wanna add something like if getPropertyFromClass('ClientPrefs', 'currentLanguage') == Russian and then insert the versionShit line except it will be with translated text if the player's settings are in Russian. 
![EXAMPLE](https://user-images.githubusercontent.com/97828056/188261499-055a0c5c-5244-4436-9972-68684b23a79b.PNG)

**Comment by NotAhmedEpic** [comment]
Edit:
I have created something like this, i dont know if anything is right but please fix me if its not. Basically, if the language for current client is Russian, put russian Psych Engine watermarks instead of English (versionShitRus) and remove English watermarks (versionShit)
![Example2](https://user-images.githubusercontent.com/97828056/188261778-fcd63ef4-0303-4056-81a2-4c1403eb45a8.png)

**Comment by ACrazyTown** [comment]
> Edit: I have created something like this, i dont know if anything is right but please fix me if its not. Basically, if the language for current client is Russian, put russian Psych Engine watermarks instead of English (versionShitRus) and remove English watermarks (versionShit) ![Example2](https://user-images.githubusercontent.com/97828056/188261778-fcd63ef4-0303-4056-81a2-4c1403eb45a8.png)

The way you're doing it right now will just make overlapping text if the language is set to Russian. I'd suggest you don't do it this way, but rather change the strings if the language is russian, like: `languageBoogie == Russian ? "russian text" : "english text". But this won't work if you're planning on having multiple languages.

For multiple languages you'd want to come up with a system but if you're a beginner you should probably learn more before heading into something like this immediately

**Comment by NotAhmedEpic** [comment]
> languageBoogie == Russian ? "russian text" : "english text"

Sorry for replying late, but... how am I supposed to like write it? The string you put in your comment
So you just delete the var versionShit:FlxText or something I dont know? I'm good in Haxe but this is a problem to me
![XD SEX](https://user-images.githubusercontent.com/97828056/189382179-f7029e4d-b482-4374-895c-f41005067190.PNG)
So here I replaced versionShit of Russian texts to versionShitRus
Do you just remove the versionShitRus crap and put three strings of languageBoogie == Russian ? "russian text" : "english text" or something?

**Comment by ACrazyTown** [comment]
> > languageBoogie == Russian ? "russian text" : "english text"
> 
> Sorry for replying late, but... how am I supposed to like write it? The string you put in your comment So you just delete the var versionShit:FlxText or something I dont know? I'm good in Haxe but this is a problem to me ![XD SEX](https://user-images.githubusercontent.com/97828056/189382179-f7029e4d-b482-4374-895c-f41005067190.PNG) So here I replaced versionShit of Russian texts to versionShitRus Do you just remove the versionShitRus crap and put three strings of languageBoogie == Russian ? "russian text" : "english text" or something?

That is definitely not how you should do multi language support. Originally, I meant making a system so that you can easily do something like:
```hx
var versionShit:FlxText = new FlxText(69, 69, 0, Language.get("version-mod"), 12);
add(versionShit);
```
But if you don't want to do that, DON'T do what you originally did.
It's just gonna clutter up memory and is not a clean way of doing it.
Instead, use the ternary operator like I suggested.
Something like this:
```hx
var versionShit:FlxText = new FlxText(FlxG.height - 64, 0, (languageBoogie == "Russian") ? "String in Russian" : "String in English", 12);
(...)
```
But like I said before, this won't work with multiple languages, just one.
