### ISSUE TITLE
how do i add a custom pixel note?

### ISSUE THREAD

**Issue by Declock** [ShadowMario/FNF-PsychEngine#10419]
### Describe your problem here.

so im trying to add a custom pixel note but when i play the chart the note isnt using the correct spritesheet and is really big

Heres a screenshot:
![big note](https://user-images.githubusercontent.com/85374715/188283914-3c1f2c7b-942d-46d1-8856-5a8632dab596.jpg)

and if needed heres some other screenshots:
![adfsdsfadfsa](https://user-images.githubusercontent.com/85374715/188283957-2c2b223e-27bc-44e2-9b02-20fa3f8867b4.jpg)

![aaaaaaaaaaaa](https://user-images.githubusercontent.com/85374715/188283979-8ac7ab16-de7a-441d-989d-0473c8953333.jpg)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Mastercopper2346** [comment]
Go to mods/images and make a folder called pixelUI and put the texture and xml inside the folder

**Comment by Declock** [comment]
> Go to mods/images and make a folder called pixelUI and put the texture and xml inside the folder

thanks
