### ISSUE TITLE
My character wont do its arrow animations

### ISSUE THREAD

**Issue by Saokom** [ShadowMario/FNF-PsychEngine#10411]
### Describe your problem here.

When i go into freeplay, load in my character into one of the songs and play it, the character wont do any of its arrow animations (left, right, up or down.)  It only does the idle and whenever it hits a note, it only moves but still just does the idle. idk whats wrong but like i need help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Wrong animation names, they have to be called singLEFT, singDOWN, and so on
It's also case sensitive

**Comment by Saokom** [comment]
it worked!! thank you :DDD
