### ISSUE TITLE
multiplatform file system/mods on html

### ISSUE THREAD

**Issue by Itz-Miles** [ShadowMario/FNF-PsychEngine#10418]
### What feature do you want to get added on the **base** engine?

I don't know all about the new asset caching involving multiple file systems since it was added in 0.6 or something, but I just noticed that OpenFL improved it's filesystem in the [`9.2.0`](https://lib.haxe.org/p/openfl/9.2.0/changelog) update. Does this mean we could ditch the SYS compilation flag and load mods on HTML with some tweaking?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Lorekeeper49** [comment]
This should be tagged as a question, not an enhancement

**Comment by Itz-Miles** [comment]
> This should be tagged as a question, not an enhancement

You should reply with an answer, unless it's not a question.

**Comment by Lorekeeper49** [comment]
I don't really have an answer to this question
