### ISSUE TITLE
Keep getting this crash when loading a chart

### ISSUE THREAD

**Issue by GrimTheDragonLord** [ShadowMario/FNF-PsychEngine#10414]
### Describe your problem here.

C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 318)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 99)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 90)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
Song.hx (line 140)
Song.hx (line 132)
editors/ChartingState.hx (line 2908)
editors/ChartingState.hx (line 428)
Prompt.hx (line 44)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

I have no idea what any of this means
Using recent version (6.2) and I keep getting this when I load a certain chart in. I keep changing stuff like moving events and such but nothing works. I would upload the chart here for everyone to look at but idk how to.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, Ive added A   L O T

**Comment by MemeHoovy** [comment]
your chart is missing

**Comment by GrimTheDragonLord** [comment]
> your chart is missing

I dont understand how the chart is missing? Here's the JSON file for the chart (of course converted to text so it can send here)
[true-genocide-danger.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9481524/true-genocide-danger.txt)

**Comment by MemeHoovy** [comment]
> > your chart is missing
> 
> I dont understand how the chart is missing? Here's the JSON file for the chart (of course converted to text so it can send here) [true-genocide-danger.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9481524/true-genocide-danger.txt)

which version of Psych are you using? It'd kinda help.
Also, did you add a new difficulty? Make sure it's in CoolUtil.hx if you did so.
![Screenshot 2022-09-02 201337](https://user-images.githubusercontent.com/97995998/188248151-6525f148-50cb-4242-98dd-af1cba053a33.png)

**Comment by GrimTheDragonLord** [comment]
> > > your chart is missing
> > 
> > 
> > I dont understand how the chart is missing? Here's the JSON file for the chart (of course converted to text so it can send here) [true-genocide-danger.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9481524/true-genocide-danger.txt)
> 
> which version of Psych are you using? It'd kinda help to know. Also, did you add a new difficulty? Make sure it's in CoolUtil.hx if you did so. ![Screenshot 2022-09-02 201337](https://user-images.githubusercontent.com/97995998/188248151-6525f148-50cb-4242-98dd-af1cba053a33.png)

Yea I added a new difficulty. The new difficulty works fine with other songs and plus im on lua on version 6.2 (the most recent version).

**Comment by frantastic24** [comment]
It's not a missing chart, that error looks nothing like this
It's incorrect syntax inside the file, it's obvious by the mentions of `JsonParser.hx`

**Comment by MemeHoovy** [comment]
> It's not a missing chart, that error looks nothing like this It's incorrect syntax inside the file, it's obvious by the mentions of `JsonParser.hx`

good to know

**Comment by GrimTheDragonLord** [comment]
> It's not a missing chart, that error looks nothing like this It's incorrect syntax inside the file, it's obvious by the mentions of `JsonParser.hx`

Oh great now I just have to find it

**Comment by BeastlyGhost** [comment]
JsonParser.hx is a library file, meaning you can't find it on the source code, which means your chart is broken, try opening it on the chart editor with Shift+Enter while selecting a song on freeplay

**Comment by GrimTheDragonLord** [comment]
> JsonParser.hx is a library file, meaning you can't find it on the source code, which means your chart is broken, try opening it on the chart editor with Shift+Enter while selecting a song on freepla, if it opens then save it and try again

Just tried it and it gave me the same error
