### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by hKZhkTmj8shRRYf** [ShadowMario/FNF-PsychEngine#10413]
### Describe your problem here.

I don't know what this means
I don't know what the problem is

<img width="325" alt="Pic" src="https://user-images.githubusercontent.com/112731255/188236603-6d908d21-0b49-403e-a7f7-e014a1ee5315.png">

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHoovy** [comment]
that line refers to removing notes, are you sure there is nothing wrong with your custom note textures or something, or if there's something wrong with your custom notes XML file?

**Comment by hKZhkTmj8shRRYf** [comment]
I just overwritten the downloaded mode, but there's an error like that... 
I used to be fine, but I haven't been able to do any songs since I changed the mode

**Comment by MemeHoovy** [comment]
> I just overwritten the downloaded mode, but there's an error like that... I used to be fine, but I haven't been able to do any songs since I changed the mode

so from what I'm understanding, is that you overwritten the PlayState.hx file from another Psych Engine mod yes?
or that you overwritten some code in PlayState and that is now showing up?

**Comment by hKZhkTmj8shRRYf** [comment]
I just overwritten the downloaded mods in the mods file, but it's happening like that

**Comment by MemeHoovy** [comment]
> I just overwritten the downloaded mods in the mods file, but it's happening like that

oh, so maybe try removing some mods and maybe you can figure out which mod is causing the issue?

**Comment by hKZhkTmj8shRRYf** [comment]
There is only one mod that I installed...

**Comment by MemeHoovy** [comment]
> There is only one mod that I installed...

oh, well maybe there's something in there that could be causing an issue? perhaps, there's something wrong with the custom notes textures or something (if there's any.) otherwise I'm really just not sure what is wrong with the mod you installed

**Comment by hKZhkTmj8shRRYf** [comment]
I'll try as hard as I can...
Thank you for your help!

**Comment by MemeHoovy** [comment]
> I'll try as hard as I can...
Thank you for your help!

your welcome
