### ISSUE TITLE
multiple dialogue sound support

### ISSUE THREAD

**Issue by AgentF4Z** [ShadowMario/FNF-PsychEngine#10426]
### What feature do you want to get added on the **base** engine?

just saying, it would be neat if there was an ability to add certain sounds to a certain character when they talk in dialogue. like say for bf you could make it so he has his own, and gf has her own as well.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MemeHoovy** [comment]
![Screenshot 2022-09-04 032253](https://user-images.githubusercontent.com/97995998/188302310-489a3933-c275-43ed-b300-109c7e2d6467.png)
coming from the changelog for psych engine 0.5.2

**Comment by CrusherNotDrip** [comment]
This is possible.
You may need to do a bit of **JSON** editing after but its possible since I've done it.
