### ISSUE TITLE
How to get rid of the master editor

### ISSUE THREAD

**Issue by MegaMatt2712** [ShadowMario/FNF-PsychEngine#10422]
### Describe your problem here.

How do i get rid of the master editor? (Sorry if bad english)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nop

**Comment by MemeHoovy** [comment]
![Screenshot 2022-09-03 200400](https://user-images.githubusercontent.com/97995998/188291324-ddd9d117-f31a-4559-b170-eea56654ad24.png)
Delete everything seen in the picture, **except** the curly bracket _encircled_ in red.

**Comment by TheKitBoi** [comment]
And also remove these line to not cause a crash
![CB7E1640-63B0-4D9F-9498-A16AC491B7D8](https://user-images.githubusercontent.com/84044666/188291663-91c42cc1-aeaa-46af-a3c8-8e4791d7c448.jpeg)

**Comment by PortilizenHub** [comment]
comment out the line
MusicBeatState.switchState(new MasterEditorMenu());

it should end up being 
// MusicBeatState.switchState(new MasterEditorMenu());

**Comment by MemeHoovy** [comment]
> comment out the line MusicBeatState.switchState(new MasterEditorMenu());
> 
> it should end up being // MusicBeatState.switchState(new MasterEditorMenu());

Yeah, but also make sure to comment out the line ```selectedSomethin = true;``` else it'll just cause issues.

**Comment by Grape-Boy** [comment]
close this
