### ISSUE TITLE
Can't Start A Song For Some Reason

### ISSUE THREAD

**Issue by Gamerdacchund99** [ShadowMario/FNF-PsychEngine#10425]
### Describe your bug here.

So Basically, I Can't Start A Song. The Song Is Called "Shark Hunt" It Starts With A Custom Note. (PLS HELP!!!)

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2868)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Lorekeeper49** [comment]
I'm pretty sure the error is referring to the fact there is either no image or no XML
