### ISSUE TITLE
Can i change the bottom left text on the main screen with lua?

### ISSUE THREAD

**Issue by NukeThief** [ShadowMario/FNF-PsychEngine#10429]
### Describe your problem here.

I want to make the Fnf version text be v69.420 bcs im unfunny

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
source is the only way
edit this line and change psychEngineVersion to this overrated thing
![image](https://user-images.githubusercontent.com/84044666/188314727-ba76f053-9c7f-49a7-bf54-30c40dc7324e.png)

**Comment by MemeHoovy** [comment]
> source is the only way
> 
> go to MainMenuState.hx
> 
> edit this line and change psychEngineVersion to this overrated thing
> 
> ![image](https://user-images.githubusercontent.com/84044666/188314727-ba76f053-9c7f-49a7-bf54-30c40dc7324e.png)
> 
> 

what they said

**Comment by NukeThief** [comment]
sad :(
