### ISSUE TITLE
possible state of a given variable

### ISSUE THREAD

**Issue by DinoBobby** [ShadowMario/FNF-PsychEngine#10421]
### Describe your problem here.

given the function: function `opponentNoteHit(id, direction, noteType, isSustainNote)` 
what are the possible outputs for id, direction, noteType, and isSustainNote?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by Lorekeeper49** [comment]
id is the strumtime, the time at which the note is over the strumline in milliseconds

direction is whichever lane the note is placed in, `left = 0, down = 1, up = 2, right = 3`

noteType is the type of the note which can be defined in the `custom_notetypes` folder or by using a preset from the chart editor's note tab.

isSustainNote is a bool that suggests if the note that is being hit is a long note trail 


These same principles apply to `function goodNoteHit(id, direction, noteType, isSustainNote)`, it's just on the player's side as opposed to the opponent's side

**Comment by Declock** [comment]
id = when the note will be exactly lined up with the strumline (number)
direction = number from 0-3 (0 being left and 3 is right)
noteType = what type of note (string) (example: a note called "Bullet" will return the value "Bullet")
isSustainNote = is it a long note? (true or false)
