### ISSUE TITLE
Help in a "secret song"

### ISSUE THREAD

**Issue by DuhLM** [ShadowMario/FNF-PsychEngine#10420]
### Describe your problem here.

Well , I want to make a secret song in my mod , the thing is that I want that in a song if you press the left mouse button it takes you to that song
is that possible? if so, how?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by DisIsNOt** [comment]
If mouseClicked(name:String) then
       endSong(true)
        loadSong('amogus', 1, false)


end

**Comment by wubbzyfan** [comment]
i don't think you need the endSong so
If mouseClicked('left') then
loadSong('amogus', 1)
end

**Comment by DisIsNOt** [comment]
Oh lol

**Comment by DuhLM** [comment]
> If mouseClicked(name:String) then endSong(true) loadSong('amogus', 1, false)
> 
> end

@

**Comment by DuhLM** [comment]
doesn't works :(

**Comment by TheKitBoi** [comment]
Put it in function onUpdate()

**Comment by DisIsNOt** [comment]
function onUpdate()
   if mousePressed('left') then
         loadSong('funni', -1)
   end


end

**Comment by DuhLM** [comment]
I had already done it but for some reason it didn't work, although I already saw the problem, thx guys
