### ISSUE TITLE
Can i make a certain song ignore a certain script?

### ISSUE THREAD

**Issue by NukeThief** [ShadowMario/FNF-PsychEngine#10431]
### Describe your problem here.

I'm making a mod, and i want one song to ignore a script.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
`songName` variable

**Comment by Lorekeeper49** [comment]
> `songName` variable 

What if the script is extremely long and you don't want to deal with that?

**Comment by frantastic24** [comment]
You deal with it

**Comment by TheKitBoi** [comment]
> What if the script is extremely long and you don't want to deal with that?
then make this
function onCreate()
	if songName == 'urmother' then
	removeLuaScript('scripts/fak')
	end
end

**Comment by Lorekeeper49** [comment]
> > What if the script is extremely long and you don't want to deal with that?
> 
> then make this function onCreate() if songName == 'urmother' then removeLuaScript('scripts/fak') end end

I tried that before and it didn't work

**Comment by NukeThief** [comment]
It worked for me
