### ISSUE TITLE
Open .lua Scripts When The Game Opens

### ISSUE THREAD

**Issue by ghost** [ShadowMario/FNF-PsychEngine#10435]
### What feature do you want to get added on the **base** engine?

They Can Add That When The Game Runs, The .lua Scripts Will Open(For Things Like Custom Menus In Lua,Etc)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MaybeMaru** [comment]
no.

**Comment by Mastercopper2346** [comment]
no

**Comment by MemeHoovy** [comment]
> ### What feature do you want to get added on the **base** engine?
> They Can Add That When The Game Runs, The .lua Scripts Will Open(For Things Like Custom Menus In Lua,Etc)
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Stage Editor, 6K+ support, and winning icons.

no

**Comment by CrusherNotDrip** [comment]
no

**Comment by TheKitBoi** [comment]
> ### What feature do you want to get added on the **base** engine?
> They Can Add That When The Game Runs, The .lua Scripts Will Open(For Things Like Custom Menus In Lua,Etc)

piss off

**Comment by Gostar64** [comment]
no

**Comment by Jevilm** [comment]
no

**Comment by DisIsNOt** [comment]
Jesus christ

**Comment by tylerandari12** [comment]
Heres an Idea:
Instead of editing the main menu make a song, return `Function_Stop` under `onStartCountdown()`, and make a new menu in the song...

**Comment by Parsellol** [comment]
no
