### ISSUE TITLE
(NO MORE ISSUE, SOLVED)

### ISSUE THREAD

**Issue by Kirsenal** [ShadowMario/FNF-PsychEngine#10437]
### Describe your problem here.

(I needed help but the problem has been fixed, no longer need help)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CrusherNotDrip** [comment]
if its solved then close it
![image](https://user-images.githubusercontent.com/90648119/188354268-5b559392-89d5-47fc-996e-e0f48c90c87a.png)
