### ISSUE TITLE
How to change bg during song?

### ISSUE THREAD

**Issue by Fullpillpa** [ShadowMario/FNF-PsychEngine#10434]
### Describe your problem here.

How I have to the change bg during song? Because I'm making something and I trying to add bg change during song, but I don't know how do I add bg change in during song?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes I try everything

**Comment by frantastic24** [comment]
#3137 this has been asked to death already, search before opening an issue

**Comment by Fullpillpa** [comment]
> #3137 this has been asked to death already, search before opening an issue

ok

**Comment by TheKitBoi** [comment]
then close this
