### ISSUE TITLE
How to open a song when opening chart editor?

### ISSUE THREAD

**Issue by PotatoKing0419** [ShadowMario/FNF-PsychEngine#10439]
### Describe your problem here.

Hey!
So, I'd like to know how to open a SONG when pressing 7 instead of the chart editor in LUA?
Simple as that really!

idk how to code so plz set up a script for me :|

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHoovy** [comment]
```
function onUpdate(elapsed)
if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
loadSong('song','difficulty')
end
end
```

**Comment by PotatoKing0419** [comment]
> ```
> function onUpdate(elapsed)
> if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
> loadSong('song','difficulty')
> end
> end
> ```

Is there a way to make it play INSTEAD of  opening the chart?
For me it opens the chart and then I have to press enter to load the new song...
If not, then I'll take it

**Comment by TheKitBoi** [comment]
> Is there a way to make it play INSTEAD of opening the chart? For me it opens the chart and then I have to press enter to load the new song... If not, then I'll take it

not possible

**Comment by DisIsNOt** [comment]
Idk may be try

`function onUpdate()
   if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN) then
        endSong(true)
        loadSong('funnisong', 1)
  end


end`

**Comment by PotatoKing0419** [comment]
> function onUpdate(elapsed)
> if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
> loadSong('song','difficulty')
> end
> end

it just ends the song

**Comment by PotatoKing0419** [comment]
> Idk may be try
> 
> `function onUpdate() if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN) then endSong(true) loadSong('funnisong', 1) end
> 
> end`

it just ends the song

**Comment by CrusherNotDrip** [comment]
> > Idk may be try
> > `function onUpdate() if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN) then endSong(true) loadSong('funnisong', 1) end
> > end`
> 
> it just ends the song

remove `endSong(true)`

**Comment by PotatoKing0419** [comment]
> ```lua
> function onCreate()
>     setProperty("debugKeysChart", null)
> end
> 
> function onUpdate()
>     if keyboardJustPressed("SEVEN") then
>         loadSong("bopeebo", 2)
>     end
> end
> ```

Wow, this is perfect! Thank you!
