### ISSUE TITLE
stuck at 8 fps

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#10438]
### Describe your bug here.

idk if it has something to do with my laptop or not but every psych engine mod i try playing runs at 8 fps or somewhere close to that and I don't know how to fix it
plz help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

N O

**Comment by creeperkidking** [comment]
its at the highest framerate

**Comment by MemeHoovy** [comment]
> ### Describe your bug here.
> idk if it has something to do with my laptop or not but every psych engine mod i try playing runs at 8 fps or somewhere close to that and I don't know how to fix it plz help
> 
> ### Command Prompt/Terminal logs (if existing)
> _No response_
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> N O

either turn down the fps cap, or your laptop is just shit, and isn't powerful enough to run Psych Engine

**Comment by creeperkidking** [comment]
it ran great before

**Comment by PotatoKing0419** [comment]
> its at the highest framerate

just gotta put framerate at 60 and anti aliasing off in settings
should fix

**Comment by creeperkidking** [comment]
i did
it work way bett4r but still lags a bit
