### ISSUE TITLE
Compiling The Source Code

### ISSUE THREAD

**Issue by MrSnacks1** [ShadowMario/FNF-PsychEngine#10430]
### Describe your problem here.

Trying to open Psych Engine but everytime I try I keep getting this message

source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Missing visual studio components

**Comment by MrSnacks1** [comment]
alright ill check Visual Studio 
Thanks
