### ISSUE TITLE
How do I change a character's z position?

### ISSUE THREAD

**Issue by Kirsenal** [ShadowMario/FNF-PsychEngine#10446]
### Describe your problem here.

I'm currently making a project where one character is meant to be closer to the camera, but the other needs to be farther away, so it actually gives it more depth and lines up with the stage. How do I make a character close to the backstage? Is this part of editing the character, or the stage?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CrusherNotDrip** [comment]
```lua
setScrollFactor(obj:String, scrollX:Float, scrollY:Float)
```
set obj to boyfriendGroup, gfGroup or dadGroup depending which one you want
and make sure to put it in onCreatePost
and if you have to then scale them

**Comment by Kirsenal** [comment]
> ```lua
> setScrollFactor(obj:String, scrollX:Float, scrollY:Float)
> ```
> 
> set obj to boyfriendGroup, gfGroup or dadGroup depending which one you want and make sure to put it in onCreatePost and if you have to then scale them

i put this in and there is a crash message, as in the image. how do i fix this
![image](https://user-images.githubusercontent.com/112831705/188519819-e0117742-07c2-4c25-8773-764cecc9b71f.png)

**Comment by CrusherNotDrip** [comment]
remove string float stuff

**Comment by CrusherNotDrip** [comment]
like the :String stuff

**Comment by CrusherNotDrip** [comment]
oh and I recommend it under 1 if its for the background

**Comment by PrismLight** [comment]
bro where tf in the second dimension is a z axis huh?

**Comment by Kirsenal** [comment]
> oh and I recommend it under 1 if its for the background for x and y

okay this makes a lot more sense, i was never strong with coding, thanks a ton

**Comment by CrusherNotDrip** [comment]
> > oh and I recommend it under 1 if its for the background for x and y
> 
> okay this makes a lot more sense, i was never strong with coding, thanks a ton

if it works then
![image](https://user-images.githubusercontent.com/90648119/188526087-b908d1e8-782a-4531-b59c-dfdcccbe679e.png)

**Comment by Lorekeeper49** [comment]
> bro where tf in the second dimension is a z axis huh?

A z axis in a 2 dimensional space is basically image layering to make it look 3d

**Comment by PrismLight** [comment]
> > bro where tf in the second dimension is a z axis huh?
> 
> A z axis in a 2 dimensional space is basically image layering to make it look 3d

yes obviously but somehow he dont know
