### ISSUE TITLE
Clickable buttons

### ISSUE THREAD

**Issue by Isaagomen** [ShadowMario/FNF-PsychEngine#10444]
### Describe your problem here.

How do i make it that the story menu buttons and everything can be clicked with the mouse, 
![image](https://user-images.githubusercontent.com/100414374/188509303-38d6bc79-841e-4210-8b6d-98ccedda5c0d.png)
like the impostor mod

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, songs

**Comment by MemeHoovy** [comment]
[you steal code from the mod](https://github.com/Clowfoe/ImpostorWeek2)

**Comment by CrusherNotDrip** [comment]
> [you steal code from the mod](https://github.com/Clowfoe/ImpostorWeek2)

what happened to borrowing?

**Comment by MemeHoovy** [comment]
> > [you steal code from the mod](https://github.com/Clowfoe/ImpostorWeek2)
> 
> what happened to borrowing?

nothing, I edited it

also, this could help
```
import flixel.input.mouse.FlxMouseEventManager;

var sprite = new FlxSprite();
FlxMouseEventManager.add(sprite, onMouseDown, onMouseUp, onMouseOver, onMouseOut); 

function onMouseDown(sprite:FlxSprite) {}
function onMouseUp(sprite:FlxSprite) {}
function onMouseOver(sprite:FlxSprite) {}
function onMouseOut(sprite:FlxSprite) {}
```

**Comment by Isaagomen** [comment]
> 

thanks

**Comment by Isaagomen** [comment]
> > > [you steal code from the mod](https://github.com/Clowfoe/ImpostorWeek2)
> > 
> > 
> > what happened to borrowing?
> 
> nothing, I edited it
> 
> also, this could help
> 
> ```
> import flixel.input.mouse.FlxMouseEventManager;
> 
> var sprite = new FlxSprite();
> FlxMouseEventManager.add(sprite, onMouseDown, onMouseUp, onMouseOver, onMouseOut); 
> 
> function onMouseDown(sprite:FlxSprite) {}
> function onMouseUp(sprite:FlxSprite) {}
> function onMouseOver(sprite:FlxSprite) {}
> function onMouseOut(sprite:FlxSprite) {}
> ```

wait to which line do i put it in

**Comment by DisIsNOt** [comment]
FlxG.mouse.overlaps()

**Comment by DisIsNOt** [comment]
FlxG.mouse.overlaps()

**Comment by DisIsNOt** [comment]
may be fine the override function update or something
