### ISSUE TITLE
Some kind of Freeplay (and story mode) bug

### ISSUE THREAD

**Issue by LilMewo** [ShadowMario/FNF-PsychEngine#10442]
### Describe your bug here.

I don't know how to describe it, freeplay and story mode crash.

### Command Prompt/Terminal logs (if existing)

```bash
FreeplayState.hx (line 74)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added the V.S. Void Psych Port (which is done)

**Comment by frantastic24** [comment]
Not a bug
Make a new week file

**Comment by LilMewo** [comment]
nvm I had a character json there =P
