### ISSUE TITLE
Note that opponent ignores

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#10445]
### Describe your problem here.

What do I put in the note code to make it so the note makes the opponent completely ignore it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
It's in the notetype script example 
```lua
setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true);
```

**Comment by Isaagomen** [comment]
just use the damn "no animation" note that is built in

**Comment by Mastercopper2346** [comment]
> just use the damn "no animation" note that is built in

Not what he was asking for.

**Comment by bruh1cat** [comment]
Sorry for the late response but, what I was trying to do was to make the opponent ignore a certain notetype but not the custom 3rd character which can only hit that specific notetype character (not gf) what would I do to make the opponent ignore that certain notetype?

**Comment by bruh1cat** [comment]
> Sorry for the late response but, what I was trying to do was to make the opponent ignore a certain notetype but not the custom 3rd character which can only hit that specific notetype character (not gf) what would I do to make the opponent ignore that certain notetype?

Figured something out
