### ISSUE TITLE
Stage Loading Bug

### ISSUE THREAD

**Issue by LilMewo** [ShadowMario/FNF-PsychEngine#10441]
### Describe your bug here.

So I was psych porting the void mod, and when I loaded the stage this error came up.

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2496)
PlayState.hx (line 2324)
PlayState.hx (line 1053)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, other than the port of the mod (so far just the character and broken/glitched stage)

**Comment by LilMewo** [comment]
also I'll put the port on GB once it's done

**Comment by frantastic24** [comment]
Not a bug
Remove philly glow

**Comment by LilMewo** [comment]
I don't have philly glow

**Comment by LilMewo** [comment]
on the chart

**Comment by TheKitBoi** [comment]
Then check events

**Comment by LilMewo** [comment]
and its fixed
