### ISSUE TITLE
/assets instead of /mods

### ISSUE THREAD

**Issue by EpicShapeShifter** [ShadowMario/FNF-PsychEngine#10443]
### Describe your problem here.

How do I make it so when the system is looking for a file, it can only use /assets instead of /mods.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yup, changed menus, added events and a new title screen

**Comment by Mastercopper2346** [comment]
That automatica

**Comment by CrusherNotDrip** [comment]
you can remove MODS_ALLOWED although I think it might break lua a bit but I don't think so

**Comment by EpicShapeShifter** [comment]
I tried removing mods allowed but it broke when compiling

**Comment by TheKitBoi** [comment]
Then show error
