### ISSUE TITLE
compile html5

### ISSUE THREAD

**Issue by KFC-Chicken-1212** [ShadowMario/FNF-PsychEngine#1044]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/89538185/141700162-21c3fc4f-7211-4615-bc24-74e0c1acc565.png)

>lime test html5 -release
source/CreditsState.hx:15: characters 8-22 : You cannot access the sys package while targeting js (for sys.FileSystem)
source/MainMenuState.hx:220: characters 42-54 :     referenced here

>pause
Press any key to continue . . .

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

**Comment by ShadowMario** [comment]
Fixed

**Comment by Nagol12344** [comment]
Im having this bug, here is the error.
```
source/WeekData.hx:11: characters 8-19 : You cannot access the sys package while targeting js (for sys.io.File)
source/editors/WeekEditorState.hx:34: characters 8-16 : ... referenced here
source/editors/MasterEditorMenu.hx:119: characters 37-52 : ... referenced here
```
