### ISSUE TITLE
Random position

### ISSUE THREAD

**Issue by joxu13v** [ShadowMario/FNF-PsychEngine#10448]
### Describe your problem here.

so I'm trying to make an event that by selecting a random number determines a new position for the opponent depending on whether his number is from 1 to 5 (using X) , but I don't know how to do it, can someone help me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
```lua
getRandomInt(min, max, exclude?)
```

**Comment by joxu13v** [comment]
But how i use it?

**Comment by Mastercopper2346** [comment]
```lua
local x = getRandomInt(1, 5);
function onCreatePost()
    setProperty(‘dad.x’, x);
end
```

**Comment by joxu13v** [comment]
> ```lua
> local x = getRandomInt(1, 5);
> function onCreatePost()
>     setProperty(‘dad.x’, x);
> end
> ```

this does not work
