### ISSUE TITLE
Move HUD elements with LUA?

### ISSUE THREAD

**Issue by Retr0wavy** [ShadowMario/FNF-PsychEngine#10449]
### What is your question?

I just wanted to know if there was some kind of lua script that allows you to move basic elements of the HUD (such as the healthbar, the timebar, the miss, the accuracy and the score counter (each counter separate from each other)) to different positions on the screen

**Comment by CrusherNotDrip** [comment]
setProperty
setPropertyFromGroup
doTweenX
doTweenY
so much possibilities

**Comment by Lorekeeper49** [comment]
> setProperty
> setPropertyFromGroup
> doTweenX
> doTweenY
> so much possibilities

Be sure to use `camHUD` for those

**Comment by Mastercopper2346** [comment]
> ### What is your question?
> I just wanted to know if there was some kind of lua script that allows you to move basic elements of the HUD (such as the healthbar, the timebar, the miss, the accuracy and the score counter (each counter separate from each other)) to different positions on the screen

The miss, accuracy, and score are in one thing, so you’ll have to make it invisible and make text for each one.
