### ISSUE TITLE
Note splashes bug

### ISSUE THREAD

**Issue by Guranlikesblue** [ShadowMario/FNF-PsychEngine#10453]
### Describe your bug here.

There is a bug that Note splashes do not disappear
https://user-images.githubusercontent.com/89185139/188643541-2a27da51-a980-47dc-817f-97dd83420cb1.mp4

This only happens on one chart
I'd be happy if you could tell me something

### Command Prompt/Terminal logs (if existing)

source/Paths.hx:358: oh no its returning null NOOOO

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Add character. Add stages and winning icons in PlayState.hx. Add Custom Note in Lua.

**Comment by MemeHoovy** [comment]
something is wrong with your notesplashes xml file

**Comment by Guranlikesblue** [comment]
> something might be wrong with your notesplashes xml file

I already fixed it, but now it happened
Works fine except for this song

**Comment by MemeHoovy** [comment]
> > something might be wrong with your notesplashes xml file
> 
> I already fixed it, but now it happened Works fine except for this song

how odd

**Comment by Guranlikesblue** [comment]
> > > something might be wrong with your notesplashes xml file
> > 
> > 
> > I already fixed it, but now it happened Works fine except for this song
> 
> how odd

xml uses the one re-downloaded from this repository
Note.hx, NoteSplash.hx not edited

**Comment by frantastic24** [comment]
Not a bug
Your song uses a splash texture that doesn't exist

**Comment by Guranlikesblue** [comment]
> Not a bug Your song uses a splash texture that doesn't exist

How can it be fixed?
I looked at songchart.json but didn't choose the splash texture.
No, I was choosing, it may be correct
But removing it doesn't fix it

**Comment by frantastic24** [comment]
go to your json and remove the note splash field entirely or just change the string to null

**Comment by Guranlikesblue** [comment]
> go to your json and remove the note splash field entirely or just change the string to null

Completely removing it didn't fix it, but after changing the string null, it worked
Thank you!!
