### ISSUE TITLE
unplayable game bug

### ISSUE THREAD

**Issue by Nightfall2401** [ShadowMario/FNF-PsychEngine#10450]
### Describe your bug here.

so i updated psych engine, and for some reason i cannot get past the title screen anymore, it spits out a error that says

''[openfl.display.Shader] ERROR: Unable to initialize the shader program, Fragments shader(s) failed to link, vertex shader(s) linked.''

i redownloaded the update from github to see if it was a internet issue that somehow corrupted something while downloading but got the same error, downgraded to 0.6.1 and the error was suddendly gone, i could play everything normally, no error pops up

with the error i can only use character editor and stuff to make mods, but actually playing the videogame is impossible due to the error

i made a custom build which removed gf from the title screen (i was deleting random stuff to see what made the error not pop up, i was thinking it could be a sprite issue because i still thought i had my psych engine build corrupted, and removing gf from the title screen did the trick well) so i could atleast access the main menu (where story mode, freeplay, etc. are located), but when i load in-game the error pops up rendering 0.6.2 unplayable for me

is there a way to fix this?, or is this a pc issue type of thing

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

only removed gf from the title screen, so that i could access at the very least the main menu

**Comment by CrusherNotDrip** [comment]
It says you removed gf from title screen correct?
Did you delete her png, xml file or???

**Comment by kingyomoma** [comment]
its an issue related to the ColorSwap shader in TitleState.hx

**Comment by ByAstroYT** [comment]
> It says you removed gf from title screen correct? Did you delete her png, xml file or???

i made a custom titlescreen that removed gf, it basically only rendered the logo, it ran fine after that

**Comment by Nightfall2401** [comment]
> It says you removed gf from title screen correct? Did you delete her png, xml file or???

i removed her in the sense that i made it so that gf doesn't render, only the logo renders, leaving the title screen to only be the fnf logo, instead of the normal classic logo + gf

idk if that's a good explanation considering i suck at explaining

**Comment by Nightfall2401** [comment]
> its an issue related to the ColorSwap shader in TitleState.hx

makes sense, i'll look into TitleState, still bugs me how that also affects in-game/playing the songs, but not for the menus n stuff
