### ISSUE TITLE
Zoom Camera in on Game Over Screen

### ISSUE THREAD

**Issue by HJacet** [ShadowMario/FNF-PsychEngine#10459]
### Describe your problem here.

I'd like to zoom in on the Players Death Animation when the player dies, but I can't seem to get it correct. This is what it looks like right now, the default stage zoom is 0.4, and no, I do not want to change the zoom setting, I set it to 0.4 because the stage would need that space to show everything on the screen. I don't know if there's a way to zoom in on death using .Lua. So if anyone could help it's appreciated!
![Movies   TV 9_6_2022 8_51_43 PM](https://user-images.githubusercontent.com/106554377/188771421-7bf36acb-e5d7-41ba-8e1e-19e6a33f8b9d.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by LuckyMist8** [comment]
```Lua
function onUpdate()
     if inGameOver then
     setProperty('defaultCamZoom', 0.7)
     end
end
```
This Seems Like It Would Work, I Can't Test Though

**Comment by frantastic24** [comment]
```lua
function onGameOverStart()
     setPropertyFromClass('flixel.FlxG', 'camera.zoom', value)
end
```
