### ISSUE TITLE
All "Lua script API" downloading as XMLs.

### ISSUE THREAD

**Issue by Projectmasternoi** [ShadowMario/FNF-PsychEngine#10451]
### Describe your bug here.

Hi. 
I tried downloading the cutscene Lua script but it downloaded as a .zip.xml. Tried opening up and says this:

<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details></Error>

Happens with all the Lua files.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by TheKitBoi** [comment]
then you have an issue with chrome

**Comment by Projectmasternoi** [comment]
> 

Tried using many different browsers

**Comment by ShadowMario** [comment]
It's an issue with the documentation's links
