### ISSUE TITLE
why long song easy to crash?

### ISSUE THREAD

**Issue by AnimaX27** [ShadowMario/FNF-PsychEngine#10454]
### What is your question?

so my question is why cant you play long song when you fps is above **60** (such as triple trouble or ominpresent) when i do it it will crash certain place without the error message so i think is this my perfomance issue ? (but when 60 fps is ok ) so i curious bc what is the limit the song length that psych engine  can play so that my quesiton ig but if possible what state is problem in source code

**Comment by KillerAvecRage** [comment]
Mods tells you to put 60 FPS or lower to play it for a reason and you should respect it, else you won't be able to play the song

VS Sky remanifested asks you to put 60 FPS even if the songs are short, so it's not a performance issue or a song length issue, it's just the mod
