### ISSUE TITLE
Pysch Engine is Crashing

### ISSUE THREAD

**Issue by CalvinDome** [ShadowMario/FNF-PsychEngine#10458]
### Describe your bug here.

I download some mods like the Holiday Mod Part 2 and I can only play the song Zanta and when I try to play the others it closes my Pysch Engine. I got the Final Escape mod today and it won't let me play it cause it closes.

[modsList.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9501579/modsList.txt)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by amongius** [comment]
Maybe the file is too large, and the pc overheats. I dont know, im just giving an option

**Comment by KillerAvecRage** [comment]
If it closes it without an error... that's weird?
