### ISSUE TITLE
i'm so mad

### ISSUE THREAD

**Issue by Tamir-YT** [ShadowMario/FNF-PsychEngine#10452]
### Describe your bug here.

If i load a song, it just crashes the game, THIS IS WAT MAKE ME SO MAD!!!1!!!!!

help me what to do :(

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i'll not explain

**Comment by Tamir-YT** [comment]
even if i load the app

**Comment by CrusherNotDrip** [comment]
Does a message pop-up when it crashes???

**Comment by KillerAvecRage** [comment]
Can't give you an idea if you don't provide a crash.txt file

However if you don't get one, play at 60 FPS and try again

**Comment by ProbablyKam** [comment]
when this happened to me it was because i did something dumb with the events, if you used any events in the chart try removing them and adding them again
