### ISSUE TITLE
Question about doing a delay/wait

### ISSUE THREAD

**Issue by ProbablyKam** [ShadowMario/FNF-PsychEngine#10469]
### What is your question?

I'm not sure how to do delay/wait in the psych engine luascript. My introduction to lua was roblox and in that you simply do wait(number of seconds) but i tried that and it didn't work. Does anybody know how to do a delay?

**Comment by Isaagomen** [comment]
you use the timer function in the wiki

**Comment by ProbablyKam** [comment]
ok thanks
