### ISSUE TITLE
haxetoolkit error psych engine

### ISSUE THREAD

**Issue by pier12123** [ShadowMario/FNF-PsychEngine#10467]
### Describe your problem here.

so im trying to start my son but one error appears and it says uncaught error:[file_contest, assets/data/''mysong''. but when i started it on some random mod it worked please help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by pier12123** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/95217879/188948733-4dd34371-70f4-4efa-9403-9092c7be4075.png)

**Comment by pier12123** [comment]
this is the error

**Comment by KillerAvecRage** [comment]
You're missing "boxing-match-hard" in your files, have you checked if it's available in mods/data or mods/[your name of mod]/data or assets/data ?

**Comment by CrusherNotDrip** [comment]
your missing a chart
