### ISSUE TITLE
Json File Bug idk

### ISSUE THREAD

**Issue by AlnerIsHere** [ShadowMario/FNF-PsychEngine#10463]
### Describe your bug here.

when i save a chart, weeks or characters it saves as (insert name).file idk if someone is also having this issue or its just me

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Jevilm** [comment]
im also having this issue
