### ISSUE TITLE
How i fix it?

### ISSUE THREAD

**Issue by joxu13v** [ShadowMario/FNF-PsychEngine#10466]
### Describe your problem here.

I'm looking for how to change dad's position but it doesn't work as it should, it always stays in the same position when the event should change it randomly
This is the code
`    local x = {900,400,500}

function onEvent(name, value1, value2)
    if name == "Dodge" then
	cameraFlash('hud', '000000', 2, false)
	setProperty('dad.x',x)
	end
end`
How i can fix it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by KillerAvecRage** [comment]
try to change setProperty('dad.x',x) to setProperty('dad.x', 'x')

**Comment by frantastic24** [comment]
You didn't tell the code what array value to use

**Comment by joxu13v** [comment]
> You didn't tell the code what array value to use

What do you mean?

**Comment by joxu13v** [comment]
> try to change setProperty('dad.x',x) to setProperty('dad.x', 'x')

that doesn't work

**Comment by frantastic24** [comment]
an array is useless if you don't give it an index to use

**Comment by joxu13v** [comment]
could you give me an example?  I still don't fully understand

**Comment by frantastic24** [comment]
Google
https://www.tutorialspoint.com/lua/lua_arrays.htm

**Comment by joxu13v** [comment]
> Google
> https://www.tutorialspoint.com/lua/lua_arrays.htm

Something like this?
```
local x = {500, 900, 300}
	    for i = 0, 3 do
            SetProperty('dad.x' , x[i])
     end
endo
```

**Comment by joxu13v** [comment]
> > Google
> > https://www.tutorialspoint.com/lua/lua_arrays.htm
> 
> Something like this?
> ```
> local x = {500, 900, 300}
> 	    for i = 0, 3 do
>             SetProperty('dad.x' , x[i])
>      end
> end
> ```

But this doesn't work

**Comment by frantastic24** [comment]
That's not random

**Comment by frantastic24** [comment]
You're using the array properly not but that's not random

**Comment by joxu13v** [comment]
how can i use it correctly?
