### ISSUE TITLE
Dialogue Mid-Song

### ISSUE THREAD

**Issue by ArthurYago** [ShadowMario/FNF-PsychEngine#10464]
### Describe your problem here.

Basically, i wanna start a dialogue mid song, and make it disappear after some seconds.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by KillerAvecRage** [comment]
`function onCreate()
makeLuaText('dialogue', '', 1200, 40, 560)
addLuaText('dialogue')
setTextSize('dialogue', 40)
setObjectCamera('dialogue', 'other')
end

function onUpdate(elapsed)
if curStep == (insert Step findable in chart) then
setTextString('dialogue', '(insert text)')
end
if curStep == (insert step of end) then
setTextString('dialogue', '')
end`

**Comment by ArthurYago** [comment]
Thank you

**Comment by KillerAvecRage** [comment]
no problem
