### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by amongius** [ShadowMario/FNF-PsychEngine#10465]
### Describe your bug here.

When i type in lime test windows this shows up:

### Command Prompt/Terminal logs (if existing)

```bash
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\usuario\Downloads\bubsy mod thing\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i deleted "mods, awards and donate", i changed the game title and i changed the "Psych Engine (insert version)"

**Comment by frantastic24** [comment]
Not a bug
Missing visual studio components

**Comment by amongius** [comment]
> Not a bug Missing visual studio components

oh, thanks! so i need to download visual studio 2017 instead?

**Comment by frantastic24** [comment]
2019 works too

**Comment by amongius** [comment]
> 2019 works too

sorry for being late, but ill try it! ill say if it worked when i use the lime test windows command, after downloading the visual studio 2019 of course

**Comment by amongius** [comment]
>  2019 works too

wait, i need to download the 2019 one or the 2022 one?

**Comment by MemeHoovy** [comment]
> > 2019 works too
> 
> wait, i need to download the 2019 one or the 2022 one?

2019

**Comment by amongius** [comment]
> > > 2019 works too
> > 
> > 
> > wait, i need to download the 2019 one or the 2022 one?
> 
> 2019

ok thanks

**Comment by MemeHoovy** [comment]
> > > > 2019 works too
> > > 
> > > 
> > > wait, i need to download the 2019 one or the 2022 one?
> > 
> > 
> > 2019
> 
> ok thanks

your welcome, now close the issue please

**Comment by amongius** [comment]
> > > > > 2019 works too
> > > > 
> > > > 
> > > > wait, i need to download the 2019 one or the 2022 one?
> > > 
> > > 
> > > 2019
> > 
> > 
> > ok thanks
> 
> your welcome, now close the issue please

im dumb, how do i close it?

**Comment by amongius** [comment]
> > > > > 2019 works too
> > > > 
> > > > 
> > > > wait, i need to download the 2019 one or the 2022 one?
> > > 
> > > 
> > > 2019
> > 
> > 
> > ok thanks
> 
> your welcome, now close the issue please

alright

**Comment by amongius** [comment]
uh, guys? this still shows up:
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\usuario\Downloads\bubsy mod thing\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
i think i need to compile the source code all over again

**Comment by amongius** [comment]
guys? i think i need to compile the source code all over again, this still shows up:
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\usuario\Downloads\bubsy mod thing\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by MemeHoovy** [comment]
> guys? i think i need to compile the source code all over again, this still shows up: source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead C:\Users\usuario\Downloads\bubsy mod thing\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion Warning: Could not find Visual Studio 2017 VsDevCmd Missing HXCPP_VARS Error: Could not automatically setup MSVC

you gotta install all the necessary components, find and read the visual studio instructions here
https://github.com/ninjamuffin99/Funkin

**Comment by amongius** [comment]
> > guys? i think i need to compile the source code all over again, this still shows up: source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead C:\Users\usuario\Downloads\bubsy mod thing\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion Warning: Could not find Visual Studio 2017 VsDevCmd Missing HXCPP_VARS Error: Could not automatically setup MSVC
> 
> you gotta install all the necessary components, find and read the visual studio instructions here https://github.com/ninjamuffin99/Funkin
> 
> and when you install `MSVC v142 - VS 2019 C++ x64/x86 build tools` in visual studio, make sure it's **latest**

oooh right, thanks!
