### ISSUE TITLE
playSound on curStep very noisy 

### ISSUE THREAD

**Issue by Shaggers-official** [ShadowMario/FNF-PsychEngine#10468]
### What is your question?

Hey, so i want to trigger a 'playSound' command when the curStep of a song = 264 (or anything else doesn't matter) but when i do it, it just triggers like 3 billion times at once, i think it's triggering over and over in that current Step, is there a way to prevent this from happening, like play the sound once, and can prevent the same problem with triggerEvent commands (which does the same) ? (Note : I am using 0.5.2h, i don't know if this was patched since then)

**Comment by ProbablyKam** [comment]
try doing a delay or wait right after the playSound command, im not sure if this will work but it's worth a shot

**Comment by Shaggers-official** [comment]
how do i add delay/wait functions to lua ?

**Comment by frantastic24** [comment]
Did you put it under onUpdate

**Comment by Shaggers-official** [comment]
of course, should i put it under onStepHit() ?

**Comment by Isaagomen** [comment]
try with the cur beat

**Comment by frantastic24** [comment]
You don't need to check the step every frame, so yes make it trigger when a step happens

**Comment by DisIsNOt** [comment]
now close this
