### ISSUE TITLE
Dad battle spotlight

### ISSUE THREAD

**Issue by DeeJay8** [ShadowMario/FNF-PsychEngine#10478]
### What is your question?

Okay so I have this problem where the game crashes when I try to add the dad battle spotlight event. The game never crashed before for me only when I try to put this specific event into a custom song/stage. I'm doing everything correctly as far as I know. any ideas how I could possibly fix this?

**Comment by Mastercopper2346** [comment]
It’s hardcoded into week1, that’s why

**Comment by DeeJay8** [comment]
> 

And is there a way to add the event to custom songs with lua or something?

**Comment by TheKitBoi** [comment]
> And is there a way to add the event to custom songs with lua or something?

no
