### ISSUE TITLE
Can you easily transfer LUA to Source Code?

### ISSUE THREAD

**Issue by PotatoKing0419** [ShadowMario/FNF-PsychEngine#10473]
### What is your question?

So I'm making a mod and I've been building it completely on LUA, but is it possible to switch it over to Source Code with all the 
lua events, stages, whatever? I'm not remaking everything on Source, so I wanna know before I transfer my whole mod to a place where it doesn't work.

**Comment by blowerslol** [comment]
![image](https://user-images.githubusercontent.com/108375156/188989935-c9a39546-98dd-44be-8e83-ba4ce7ed19a0.png)

**Comment by blowerslol** [comment]
Inside the source folder

**Comment by blowerslol** [comment]
> ![image](https://user-images.githubusercontent.com/108375156/188989935-c9a39546-98dd-44be-8e83-ba4ce7ed19a0.png)

Inside the source folder.

**Comment by DisIsNOt** [comment]
First, you need some knowledge at haxe

**Comment by PotatoKing0419** [comment]
> > ![image](https://user-images.githubusercontent.com/108375156/188989935-c9a39546-98dd-44be-8e83-ba4ce7ed19a0.png)
> 
> Inside the source folder.

I'll take that as a yes than, thank you!
