### ISSUE TITLE
How do I make my character have no animation with a note? (like bob)

### ISSUE THREAD

**Issue by JadenMudge** [ShadowMario/FNF-PsychEngine#10471]
### Describe your problem here.

I see that there is a "no animation" note, but I don't want to replace all the normal notes!
I can't code really good...

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by bruh1cat** [comment]
function onStepHit()
if curStep == 1 and dadName == 'your-char' then
setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true);
end
end

**Comment by Isaagomen** [comment]
just clone your current character and put his idle as the poses and in hints put 0 so he wont move

**Comment by bruh1cat** [comment]
> just clone your current character and put his idle as the poses and in hints put 0 so he wont move

I'm trying to make the opponent ignore a certain notetype but not the 3rd character (not gf) what would I do to make the opponent ignore that certain notetype?

**Comment by JadenMudge** [comment]
> just clone your current character and put his idle as the poses and in hints put 0 so he wont move

cool, but how XD

**Comment by JadenMudge** [comment]
#

> > just clone your current character and put his idle as the poses and in hints put 0 so he wont move
> 
> I'm trying to make the opponent ignore a certain notetype but not the 3rd character (not gf) what would I do to make the opponent ignore that certain notetype?

making a 2v1?

**Comment by bruh1cat** [comment]
> > > just clone your current character and put his idle as the poses and in hints put 0 so he wont move
> > 
> > 
> > I'm trying to make the opponent ignore a certain notetype but not the 3rd character (not gf) what would I do to make the opponent ignore that certain notetype?
> 
> making a 2v1?

kind of (port of a pretty high end computer mod)

**Comment by bruh1cat** [comment]
> > just clone your current character and put his idle as the poses and in hints put 0 so he wont move
> 
> cool, but how XD

copy and paste the json file of your character then make all animations his idle

**Comment by JadenMudge** [comment]
Then it will look like its frozen when it hits 1/4 notes in a line

**Comment by bruh1cat** [comment]
Wait are you trying to do this or just make the character not move at all.

https://static.wikia.nocookie.net/fridaynightfunking/images/9/99/BobHellAnim.gif/revision/latest?cb=20210815031430

**Comment by JadenMudge** [comment]
> Wait are you trying to do this or just make the character not move at all.
> 
> https://static.wikia.nocookie.net/fridaynightfunking/images/9/99/BobHellAnim.gif/revision/latest?cb=20210815031430

yes

**Comment by bruh1cat** [comment]
yes what

**Comment by JadenMudge** [comment]
> yes what

to make it not move at all, replaying the same animation, without it restarting it.

**Comment by JadenMudge** [comment]
just like bob, when it hits notes, it will continue his idle like nothing at all happened.

**Comment by JadenMudge** [comment]
i have an idea i can try!
i can make gf invisible, make it so she hits the notes!

**Comment by bruh1cat** [comment]
> i have an idea i can try! i can make gf invisible, make it so she hits the notes!

You'd still have to rechart it

**Comment by JadenMudge** [comment]
I found out that I'm stupid dumb dumb! I thought it would replay like in other engines!
SO another way is to NOT do that, but instead leave 1 animation working and it will keep using that animatoin, and NOT replay it.
This engine can do things like that, i never knew!

**Comment by JadenMudge** [comment]
soo im done, solved.
you can add me on discord you you'd like: JadenMudge#2598

**Comment by ProbablyKam77** [comment]
I think this was already solved butttt put this in custom note type luascript

setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true);

**Comment by ProbablyKam77** [comment]
my bad nvm that dont work
