### ISSUE TITLE
health counter in lua

### ISSUE THREAD

**Issue by swobodac** [ShadowMario/FNF-PsychEngine#10476]
### Describe your problem here.

do you know how to make health counter in lua like this no being mean
![Screenshot 2022-09-07 184757](https://user-images.githubusercontent.com/98852602/188996861-52a13724-8e82-4fca-9216-2f8b2f617f47.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

0.5.1 shaders bulid lol

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/LUA-Script-API:-Custom-Text

**Comment by swobodac** [comment]
I need a script
I suck at makin code

**Comment by frantastic24** [comment]
Do it yourself

**Comment by swobodac** [comment]
Read the comment I just said

**Comment by frantastic24** [comment]
Don't care, if you suck then sit down and learn. Don't ask people to do it for you

**Comment by ProbablyKam** [comment]
> Don't care, if you suck then sit down and learn. Don't ask people to do it for you

asshole move but fair point

**Comment by ProbablyKam** [comment]
anyways is this supposed to be a counter for the actual health as shown on the health bar or a separate system

**Comment by frantastic24** [comment]
> asshole move

yeah asking people to do stuff for you is an asshole move fr

**Comment by swobodac** [comment]
Ok makin a new new one
