### ISSUE TITLE
Is it possible to make a note play an animation via lua

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#10475]
### Describe your problem here.

To make animated notes and stuff in lua.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Notes are animated by default, if you want custom animations you can probably use runHaxeCode

**Comment by wubbzyfan** [comment]
how would I go about doing that?

**Comment by wubbzyfan** [comment]
> Notes are animated by default, if you want custom animations you can probably use runHaxeCode

How do I do that?

**Comment by wubbzyfan** [comment]
> characterPlayAnim('dad', 'ANIMATIONAME', true);
> characterPlayAnim('boyfriend', 'ANIMATIONAME', true);

I mean the notes themselves, not the characters.

**Comment by MMalkeZ** [comment]
> > characterPlayAnim('dad', 'ANIMATIONAME', true);
> > characterPlayAnim('boyfriend', 'ANIMATIONAME', true);
> 
> I mean the notes themselves, not the characters.

If you have the ready xml file, I think the game will auto load the animation for it, it happened for all of mine animated notes

**Comment by wubbzyfan** [comment]
> > > characterPlayAnim('dad', 'ANIMATIONAME', true);
> > > characterPlayAnim('boyfriend', 'ANIMATIONAME', true);
> > 
> > 
> > I mean the notes themselves, not the characters.
> 
> If you have the ready xml file, I think the game will auto load the animation for it, it happened for all of mine animated notes

How do I make I play another animation though?
