### ISSUE TITLE
The Week6 Dialogue Text

### ISSUE THREAD

**Issue by ghost** [ShadowMario/FNF-PsychEngine#10483]
### Describe your problem here.

How To Edit The Week6 Dialogue?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes

**Comment by MemeHoovy** [comment]
> ### Describe your problem here.
> How To Edit The Week6 Dialogue?
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> Yes

the dialogues are txt files inside the week6 songs in the data folder

**Comment by StefanBETA2008** [comment]
> > ### Describe your problem here.
> > How To Edit The Week6 Dialogue?
> > ### Are you modding a build from source or with Lua?
> > Source
> > ### What is your build target?
> > Windows x64
> > ### Did you edit anything in this build? If so, mention or summarize your changes.
> > Yes
> 
> the dialogues are txt files inside the week6 songs in the data folder, if that's what you meant

I Think. Let Me See
