### ISSUE TITLE
Change Character event disappearing in chart editor

### ISSUE THREAD

**Issue by ArtikInGithubLmao** [ShadowMario/FNF-PsychEngine#10480]
### Describe your bug here.

Every time I add the change character event in the chart editor, after saving and going back to the chart editor it's just not there.
I tried the "Load Events" button but it's not working

Iunno if it's just me or the engine, _tho it's probably my computer_

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by KillerAvecRage** [comment]
You can still check in the .json of your chart if the event is here, if it is then nice, if it's not well idk

**Comment by ArtikInGithubLmao** [comment]
When I save the events again after adding different events, the change character events just disappear from the file as well.
