### ISSUE TITLE
lua help

### ISSUE THREAD

**Issue by swobodac** [ShadowMario/FNF-PsychEngine#10482]
### What is your question?

do you know the script for a lua health counter no being mean!!!
![Screenshot 2022-09-07 184757](https://user-images.githubusercontent.com/98852602/189214813-1063cce9-7a9e-4e47-9312-d94a998ab6e0.png)

**Comment by MemeHoovy** [comment]
```
local Counter_Size = 25 -- default: 25
local Position = 'up' -- positions: left, up, right

------------------------------------------------------------------------------------------

function onCreate()
	if not downscroll then
		if Position == 'right' then
			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,950,635)
			setTextSize('counter', Counter_Size)
			addLuaText('counter')
		elseif Position == 'up' then
			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,640,550)
			setTextSize('counter', Counter_Size)
			addLuaText('counter')
		elseif Position == 'left' then
			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,275,635)
			setTextSize('counter', Counter_Size)
			addLuaText('counter')
		end
	elseif downscroll then
		if Position == 'right' then
			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,950,70)
			setTextSize('counter', Counter_Size)
			addLuaText('counter')
		elseif Position == 'left' then
			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,275,70)
			setTextSize('counter', Counter_Size)
			addLuaText('counter')
		elseif Position == 'up' then
			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,640,10)
			setTextSize('counter', Counter_Size)
			addLuaText('counter')
		end
	end
end

function onUpdate()
	setTextString('counter',getProperty('healthBar.percent') .. '%')
end
```

**Comment by swobodac** [comment]
> ```
> local Counter_Size = 25 -- default: 25
> local Position = 'up' -- positions: left, up, right
> 
> ------------------------------------------------------------------------------------------
> 
> function onCreate()
> 	if not downscroll then
> 		if Position == 'right' then
> 			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,950,635)
> 			setTextSize('counter', Counter_Size)
> 			addLuaText('counter')
> 		elseif Position == 'up' then
> 			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,640,550)
> 			setTextSize('counter', Counter_Size)
> 			addLuaText('counter')
> 		elseif Position == 'left' then
> 			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,275,635)
> 			setTextSize('counter', Counter_Size)
> 			addLuaText('counter')
> 		end
> 	elseif downscroll then
> 		if Position == 'right' then
> 			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,950,70)
> 			setTextSize('counter', Counter_Size)
> 			addLuaText('counter')
> 		elseif Position == 'left' then
> 			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,275,70)
> 			setTextSize('counter', Counter_Size)
> 			addLuaText('counter')
> 		elseif Position == 'up' then
> 			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,640,10)
> 			setTextSize('counter', Counter_Size)
> 			addLuaText('counter')
> 		end
> 	end
> end
> 
> function onUpdate()
> 	setTextString('counter',getProperty('healthBar.percent') .. '%')
> end
> ```
> 
> go search github for the things you want to look for next time, it helps **a lot** you goofballs and also to learn not to be a bunch of assholes next time

it did not work

**Comment by MemeHoovy** [comment]
> > ```
> > local Counter_Size = 25 -- default: 25
> > local Position = 'up' -- positions: left, up, right
> > 
> > ------------------------------------------------------------------------------------------
> > 
> > function onCreate()
> > 	if not downscroll then
> > 		if Position == 'right' then
> > 			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,950,635)
> > 			setTextSize('counter', Counter_Size)
> > 			addLuaText('counter')
> > 		elseif Position == 'up' then
> > 			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,640,550)
> > 			setTextSize('counter', Counter_Size)
> > 			addLuaText('counter')
> > 		elseif Position == 'left' then
> > 			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,275,635)
> > 			setTextSize('counter', Counter_Size)
> > 			addLuaText('counter')
> > 		end
> > 	elseif downscroll then
> > 		if Position == 'right' then
> > 			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,950,70)
> > 			setTextSize('counter', Counter_Size)
> > 			addLuaText('counter')
> > 		elseif Position == 'left' then
> > 			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,275,70)
> > 			setTextSize('counter', Counter_Size)
> > 			addLuaText('counter')
> > 		elseif Position == 'up' then
> > 			makeLuaText('counter',getProperty('healthBar.percent') .. '%',0,640,10)
> > 			setTextSize('counter', Counter_Size)
> > 			addLuaText('counter')
> > 		end
> > 	end
> > end
> > 
> > function onUpdate()
> > 	setTextString('counter',getProperty('healthBar.percent') .. '%')
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > go search github for the things you want to look for next time, it helps **a lot** you goofballs and also to learn not to be a bunch of assholes next time
> 
> it did not work

It worked for me. Did you put it in scripts folder?

**Comment by swobodac** [comment]
yes

**Comment by MemeHoovy** [comment]
> yes

well idk, it worked for me, are you using Psych Engine 0.5.1 or less, because I don't think this script works on 0.5.1 or versions below that.

**Comment by swobodac** [comment]
im using a action bulid with shaders

**Comment by MemeHoovy** [comment]
> im using a action bulid with shaders

oh, well I don't really know, it should work, idk why it's not working for you, for some reason

**Comment by Parsellol** [comment]
```lua
function onCreatePost()
	makeLuaText("health", "Health:" .. getProperty("health") * 50 .."%", 200, 0, 275)
	addLuaText("health")
end

function onRecalculateRating()
	setTextString("health", "Health:" .. getProperty("health") * 50 .."%");
end
```
