### ISSUE TITLE
Can someone make some base stages on lua?

### ISSUE THREAD

**Issue by jaekyle122** [ShadowMario/FNF-PsychEngine#1048]
### What feature do you want to get added on the base engine?

I'm sorry that this isnt really related to the base engine, but can someone do it please?

**Comment by DEV-idiotXD** [comment]
> ### What feature do you want to get added on the base engine?
> I'm sorry that this isnt really related to the base engine, but can someone do it please?

wdym?

**Comment by RafaelGiacom** [comment]
> > ### What feature do you want to get added on the base engine?
> > I'm sorry that this isnt really related to the base engine, but can someone do it please?
> 
> wdym?

he means remaking the base game stages in lua

**Comment by MayoALT** [comment]
[one of the example scripts is a template stage, if thats what you are asking for](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API)

**Comment by RafaelGiacom** [comment]
the other ones is what they're asking for

**Comment by ShadowMario** [comment]
Lazy asf lmao
