### ISSUE TITLE
Character sprites invisible

### ISSUE THREAD

**Issue by MMalkeZ** [ShadowMario/FNF-PsychEngine#10481]
### Describe your bug here.

Well so, for a while now I've been dealing with this and it's really annoying fr, out of nowhere, Psych Engine just decided to not show some of the character sprites in-game, they just appear to be invisible as the image bellow shows:
![WhatsApp Image 2022-08-08 at 03 37 36](https://user-images.githubusercontent.com/108292251/189211539-0da3b3fa-e84a-4f16-98ee-1509a5df4560.jpeg)

I thought it was a glitch on the xml or the json file, but no, i sent them to a friend of mine to test it for me to see if it was also glitched for him, but as the image here clearly shows, they are both working fine:
![hNsWHNS - Imgur](https://user-images.githubusercontent.com/108292251/189211126-f7f8afc2-323d-4d1d-b831-2f6e453ee23f.jpg)

I am really curious because I really have no idea of what could be causing this, they were indeed working fine before, it just started to happen all sudden with random characters, not all, just some of them, another clear exemple is this from week 7, that neither tankman and bfholdinggf are visible

![image](https://user-images.githubusercontent.com/108292251/189212761-6404bd81-d876-49d2-b8f1-31b78548cee4.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't edit anything on the source code

**Comment by MMalkeZ** [comment]
Can I get at least one answer here, I really want to fix it pLEAsE

**Comment by MMalkeZ** [comment]
Can I get at least one answer here, I really wanna fix this plEASE

**Comment by MemeHoovy** [comment]
> Can I get at least one answer here, I really wanna fix this plEASE

I feel like this is an issue with psych engine itself, Idk, I never encountered this issue at all.

**Comment by MMalkeZ** [comment]
> > Can I get at least one answer here, I really wanna fix this plEASE
> 
> I feel like this is an issue with psych engine itself, Idk. I never encountered this issue at all. It's just a weird ass issue that nobody knows what the cause of it is.

well shit

**Comment by MemeHoovy** [comment]
> > > Can I get at least one answer here, I really wanna fix this plEASE
> > 
> > 
> > I feel like this is an issue with psych engine itself, Idk. I never encountered this issue at all. It's just a weird ass issue that nobody knows what the cause of it is.
> 
> well shit

yeah, we're just FUCKED.
