### ISSUE TITLE
pls read this, of not it dosent matter

### ISSUE THREAD

**Issue by jakonboi** [ShadowMario/FNF-PsychEngine#10487]
### What feature do you want to get added on the **base** engine?

You can enhance the engine maybe with,
Custom Achievements (no source code),
Updated menu music,
Test week,
A guide on how to make custom menu items,
Updated icons,
Better design,
And **useable fonts for the game.**
Unluckily, OS Engine has took the gold for "Stage Editor". sorry buds.

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by jakonboi** [comment]
why did i recommend so much

**Comment by CrusherNotDrip** [comment]
you failed the test

**Comment by TheKitBoi** [comment]
> ### What feature do you want to get added on the **base** engine?
> You can enhance the engine maybe with, Custom Achievements (no source code), Updated menu music, Test week, A guide on how to make custom menu items, Updated icons, Better design, And **useable fonts for the game.** Unluckily, OS Engine has took the gold for "Stage Editor". sorry buds.

for .1 https://gamebanana.com/mods/398462 use of hscript (if u use this remember to credit
for .2 maybe not
for .3 no. there only sticking to the original
for .4 hscript supports custom states
for .5 referring to .3
for .6 be patient on update diffrences
and for .7 setTextFont("this-issue", "nothing.ttf") this exist

**Comment by jakonboi** [comment]
ok

**Comment by jakonboi** [comment]
my issue is done then
