### ISSUE TITLE
Adding more control over notesplash properties

### ISSUE THREAD

**Issue by TheRealJake12** [ShadowMario/FNF-PsychEngine#10494]
### What feature do you want to get added on the **base** engine?

Adding more control over notesplashes. As the title suggests. Like being able to control the alpha or framerate of a specific set of notesplashes (ie alpha of 1 and framerate of 48).

Jsons. Yea

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tylerandari12** [comment]
I approve...

**Comment by MemeHoovy** [comment]
nice idea

**Comment by TheRealJake12** [comment]
I had this idea for my own engine but couldn't figure out how to soft code shit. Might aswell ask the mod support engine

**Comment by ShadowMario** [comment]
done through txts file now
