### ISSUE TITLE
dave and bambi 3d wave bg funni thing

### ISSUE THREAD

**Issue by swobodac** [ShadowMario/FNF-PsychEngine#10490]
### What is your question?

do you know how to make wavy backgrounds in 0.6.2
i have it for 0.5.1

**Comment by swobodac** [comment]
yah i use it
but it was dissounced

**Comment by MemeHoovy** [comment]
> It doesn't matter, close this & use OS Engine. It has the fucking shaders.
> 
> Discontinued doesn't really matter, you get what you get

agreed

**Comment by wubbzyfan** [comment]
Or hell, pre-render the wave and make it an animated background!

**Comment by smisanasshole** [comment]
Here take this. I can confirm it works with 0.6.2 and also 0.5.1 i think.
Also it's not exact but it's similar.
(also also stolen from dimensional deep end lol)

`cx = 0;`
`cy = 0;`
`function onCreate()`
`    local hx = 3148 / 2;`
`    local hy = 1664 / 2;`
`    cx = -500 + hx;`
`    cy = -200 + hy;`
`    makeLuaSprite('rbg', 'image', cx, cy)`
`    setProperty('rbg.offset.x', hx);`
`    setProperty('rbg.offset.y', hy);`
`    setProperty('rbg.antialiasing', true);`
`    addLuaSprite('rbg', false)`
`end`
`fr = 0`
`function onUpdate(elapsed)`
`    fr = fr + elapsed;`
`    setProperty('background.scale.x', (1 + math.cos(fr) / 4) * 1)`
`    setProperty('background.scale.y', (1 + math.cos(fr + 1) / 4) * 1)`
`    setProperty('rbg.scale.x', 1 + math.cos(fr*3) / 6)`
`    setProperty('rbg.scale.y', 1 + math.cos(fr*3 + 2) / 6)`
`    setProperty('rbg.angle', math.sin(fr*3) * 8);`
`    setProperty('rbg.x', cx + math.sin(fr*3) * 200);`
`    setProperty('rbg.y', cy + math.cos(fr*3) * 200);`
`end`

So uh yeah stfu random people saying to just use OS (whatever that is).

**Comment by StefanBETA2008** [comment]
How To Change Possition?

**Comment by smisanasshole** [comment]
Change the values of cx and cy at the top to change the position.
I'm not really sure how to fix the size problem other than to just make the image itself bigger.
I'll get back to you if I figure something out.

**Comment by StefanBETA2008** [comment]
> 

Okay

**Comment by smisanasshole** [comment]
Would it be possible for you to send me the image?

**Comment by StefanBETA2008** [comment]
> Would it be possible for you to send me the image?

Sure:
![Untitled32](https://user-images.githubusercontent.com/109828559/190430354-b3e10694-04c9-46de-9fe6-8d9e5a67186c.png)

**Comment by StefanBETA2008** [comment]
> https://drive.google.com/drive/folders/1Hh0aF-RgVlR7G2qVLE1ytltDYdXRbbXF?usp=sharing Replace the Lua files and image file with the stuff in here. I managed to get it working.

Thanks

**Comment by swobodac** [comment]
never mind
im usin os
