### ISSUE TITLE
How would I go about taking out all the unnecessary assets that I don't need?

### ISSUE THREAD

**Issue by SammuSucksAtCode** [ShadowMario/FNF-PsychEngine#1049]
### What is your question?

Like say, I want to take out just ALL of the base weeks, how would I go about doing that. Please help. I've been trying to figure this out for 3 months. I haven't found any other help. I would greatly appreciate any and all help given. I will buy you a nice steak dinner.*

_*Steak Dinner not included_

**Comment by DEV-idiotXD** [comment]
depends on which version your deleting contet from if the downloaded build then they wil just be gone if you delete it befor compiling then the weeks will still be in story menu but will crash trying to go into one

**Comment by DEV-idiotXD** [comment]
ok wheres my steak?

**Comment by SammuSucksAtCode** [comment]
but how would I also go about removing the weeks themselves from the story menu as well then

**Comment by HiroOfc** [comment]
> but how would I also go about removing the weeks themselves from the story menu as well then

just delete the weeks json archives at preload/weeks

**Comment by ShadowMario** [comment]
Delete the weeks in `assets/preload/weeks/` on Source Code (or `assets/weeks/` on Downloaded Build), you can also remove the `assets/week#/` folders that you aren't going to use for decreasing the folder size
