### ISSUE TITLE
The Loading Screen On The 0.6.2

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10496]
### What is your question?

It's Possible To Add The Loading Screen On The 0.6.2? I Want For Something

**Comment by MemeHoovy** [comment]
> ### What is your question?
> It's Possible To Add The Loading Screen On The 0.6.2? I Want For Something

remove all the NO_PRELOAD shit in loadingstate.hx

**Comment by StefanBETA2008** [comment]
> > ### What is your question?
> > It's Possible To Add The Loading Screen On The 0.6.2? I Want For Something
> 
> remove all the NO_PRELOAD shit in loadingstate.hx

I Will Try, Beacuse For The My Dave And Bambi Fanmade Mod

**Comment by MemeHoovy** [comment]
https://user-images.githubusercontent.com/97995998/189464758-64d85f4a-46a9-48fc-9782-cd91717f4431.mp4

**Comment by StefanBETA2008** [comment]
> > ### What is your question?
> > It's Possible To Add The Loading Screen On The 0.6.2? I Want For Something
> 
> remove all the NO_PRELOAD shit in loadingstate.hx

I Need To Remove:
`#if NO_RELOAD`
You Mean This Line?

**Comment by MemeHoovy** [comment]
> > > ### What is your question?
> > > It's Possible To Add The Loading Screen On The 0.6.2? I Want For Something
> > 
> > 
> > remove all the NO_PRELOAD shit in loadingstate.hx
> 
> I Need To Remove: `#if NO_RELOAD` You Mean This Line?

yes, and the #end lines too.

**Comment by StefanBETA2008** [comment]
> > > > ### What is your question?
> > > > It's Possible To Add The Loading Screen On The 0.6.2? I Want For Something
> > > 
> > > 
> > > remove all the NO_PRELOAD shit in loadingstate.hx
> > 
> > 
> > I Need To Remove: `#if NO_RELOAD` You Mean This Line?
> 
> yes, and the #end lines too.

It's Work. Thank You. How You Did Know This? I Saw, You Need To Add Cache.hx And The Edit On The Main.hx `TitleState` ---> `Cache` Before?

**Comment by MemeHoovy** [comment]
> > > > > ### What is your question?
> > > > > It's Possible To Add The Loading Screen On The 0.6.2? I Want For Something
> > > > 
> > > > 
> > > > remove all the NO_PRELOAD shit in loadingstate.hx
> > > 
> > > 
> > > I Need To Remove: `#if NO_RELOAD` You Mean This Line?
> > 
> > 
> > yes, and the #end lines too.
> 
> It's Work. Thank You. How You Did Know This? I Saw, You Need To Add Cache.hx And The Edit On The Main.hx `TitleState` ---> `Cache` Before?

not needed

**Comment by StefanBETA2008** [comment]
Dude, You Are Insane. I Can Now Close The Issue. It's Working Fine:
![Screenshot_20220910-041820~2](https://user-images.githubusercontent.com/109828559/189465112-c21d99ae-fdeb-4ab9-bc17-2984ee425d0b.png)
If You Don't Like The AndroidBuild, It's Fine. I Just Don't Have The PC :(

**Comment by MemeHoovy** [comment]
> Dude, You Are Insane. I Can Now Close The Issue. It's Working Fine: ![Screenshot_20220910-041820~2](https://user-images.githubusercontent.com/109828559/189465112-c21d99ae-fdeb-4ab9-bc17-2984ee425d0b.png) If You Don't Like The AndroidBuild, It's Fine. I Just Don't Have The PC :(

no android builds fine

**Comment by StefanBETA2008** [comment]
> > Dude, You Are Insane. I Can Now Close The Issue. It's Working Fine: ![Screenshot_20220910-041820~2](https://user-images.githubusercontent.com/109828559/189465112-c21d99ae-fdeb-4ab9-bc17-2984ee425d0b.png) If You Don't Like The AndroidBuild, It's Fine. I Just Don't Have The PC :(
> 
> no android builds fine

:) Here. I Will Give You Cookie 🍪

**Comment by MemeHoovy** [comment]
> > > Dude, You Are Insane. I Can Now Close The Issue. It's Working Fine: ![Screenshot_20220910-041820~2](https://user-images.githubusercontent.com/109828559/189465112-c21d99ae-fdeb-4ab9-bc17-2984ee425d0b.png) If You Don't Like The AndroidBuild, It's Fine. I Just Don't Have The PC :(
> > 
> > 
> > no android builds fine
> 
> :) Here. I Will Give You Cookie 🍪

thanks :D
