### ISSUE TITLE
The Shader Pulse Problem

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10499]
### Describe your problem here.

Okay, I Got This Error:
  
`source/PlayState.hx:155: characters 33-52 : Module Shaders does not define type PulseEffect
source/CoolUtil.hx:18: lines 18-141 : ... Defined in this class
source/PlayState.hx:126: characters 2-47 : Method set_songSpeed required by property songSpeed is missing
source/PlayState.hx:9: characters 8-15 : Module Shaders does not define type Shaders
source/CoolUtil.hx:18: lines 18-141 : ... Defined in this class
source/animateatlas/AtlasFrameMaker.hx:45: characters 14-22 : Class<PlayState> has no field instance
source/StoryMenuState.hx:329: characters 14-27 : Class<PlayState> has no field campaignScore
source/StoryMenuState.hx:330: characters 14-28 : Class<PlayState> has no field campaignMisses
source/FunkinLua.hx:3111: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:139: characters 33-45 : Class<PlayState> has no field seenCutscene
source/FunkinLua.hx:170: characters 35-43 : Class<PlayState> has no field instance
source/FunkinLua.hx:171: characters 35-43 : Class<PlayState> has no field instance
source/FunkinLua.hx:172: characters 36-44 : Class<PlayState> has no field instance
source/FunkinLua.hx:173: characters 28-36 : Class<PlayState> has no field instance
source/FunkinLua.hx:174: characters 29-37 : Class<PlayState> has no field instance
source/FunkinLua.hx:184: characters 38-46 : Class<PlayState> has no field instance
source/FunkinLua.hx:185: characters 38-46 : Class<PlayState> has no field instance
source/FunkinLua.hx:186: characters 37-45 : Class<PlayState> has no field instance
source/FunkinLua.hx:187: characters 37-45 : Class<PlayState> has no field instance
source/FunkinLua.hx:188: characters 39-47 : Class<PlayState> has no field instance
source/FunkinLua.hx:189: characters 39-47 : Class<PlayState> has no field instance
source/FunkinLua.hx:2880: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:2916: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:244: characters 18-26 : Class<PlayState> has no field instance
source/FunkinLua.hx:3227: characters 41-49 : Class<PlayState> has no field instance
source/FunkinLua.hx:3289: characters 20-28 : Class<PlayState> has no field instance
source/FunkinLua.hx:3289: characters 76-84 : Class<PlayState> has no field instance
source/FunkinLua.hx:257: characters 39-47 : Class<PlayState> has no field instance
source/FunkinLua.hx:438: characters 30-38 : Class<PlayState> has no field instance
source/FunkinLua.hx:439: characters 35-43 : Class<PlayState> has no field instance
source/FunkinLua.hx:460: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:506: characters 35-43 : Class<PlayState> has no field instance
source/FunkinLua.hx:506: characters 25-52 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/FunkinLua.hx:561: characters 35-43 : Class<PlayState> has no field instance
source/FunkinLua.hx:561: characters 25-52 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/FunkinLua.hx:614: characters 35-43 : Class<PlayState> has no field instance
source/FunkinLua.hx:614: characters 25-52 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/FunkinLua.hx:738: characters 35-43 : Class<PlayState> has no field instance
source/FunkinLua.hx:738: characters 25-52 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/FunkinLua.hx:780: characters 36-44 : Class<PlayState> has no field instance
source/FunkinLua.hx:780: characters 26-53 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/FunkinLua.hx:789: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:825: characters 36-44 : Class<PlayState> has no field instance
source/FunkinLua.hx:825: characters 26-53 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/FunkinLua.hx:831: characters 19-27 : Class<PlayState> has no field instance
source/FunkinLua.hx:2789: characters 47-55 : Class<PlayState> has no field instance
source/FunkinLua.hx:2804: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2808: characters 19-27 : Class<PlayState> has no field instance
source/FunkinLua.hx:2809: characters 22-30 : Class<PlayState> has no field instance
source/FunkinLua.hx:887: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:892: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:894: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:895: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:3008: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:3009: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:3010: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:3011: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1072: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:1074: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1075: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1085: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:1087: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1088: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1098: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:1100: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1101: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1111: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:1113: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1114: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1124: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:1126: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1127: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1142: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:1144: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1145: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1157: characters 39-47 : Class<PlayState> has no field instance
source/FunkinLua.hx:1157: characters 88-96 : Class<PlayState> has no field instance
source/FunkinLua.hx:1160: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:1162: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1163: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1171: characters 39-47 : Class<PlayState> has no field instance
source/FunkinLua.hx:1171: characters 88-96 : Class<PlayState> has no field instance
source/FunkinLua.hx:1174: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:1176: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1177: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1185: characters 39-47 : Class<PlayState> has no field instance
source/FunkinLua.hx:1185: characters 88-96 : Class<PlayState> has no field instance
source/FunkinLua.hx:1188: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:1190: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1191: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1199: characters 39-47 : Class<PlayState> has no field instance
source/FunkinLua.hx:1199: characters 88-96 : Class<PlayState> has no field instance
source/FunkinLua.hx:1202: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:1204: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1205: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1279: characters 39-47 : Class<PlayState> has no field instance
source/FunkinLua.hx:1279: characters 88-96 : Class<PlayState> has no field instance
source/FunkinLua.hx:1282: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:1284: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1285: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1293: characters 39-47 : Class<PlayState> has no field instance
source/FunkinLua.hx:1293: characters 88-96 : Class<PlayState> has no field instance
source/FunkinLua.hx:1296: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:1298: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1299: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:3026: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:3027: characters 38-46 : Class<PlayState> has no field instance
source/FunkinLua.hx:3030: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1311: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1313: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:1315: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:1315: characters 61-70 : Arrays of mixed types are only allowed if the type is forced to Array<Dynamic>
source/FunkinLua.hx:1315: characters 61-70 : Int should be String
source/FunkinLua.hx:1357: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1358: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1361: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1362: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1365: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1366: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1369: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1370: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1373: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1374: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1377: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1378: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1381: characters 21-29 : Class<PlayState> has no field instance
source/FunkinLua.hx:1384: characters 21-29 : Class<PlayState> has no field instance
source/FunkinLua.hx:1387: characters 21-29 : Class<PlayState> has no field instance
source/FunkinLua.hx:1391: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1394: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1397: characters 21-29 : Class<PlayState> has no field instance
source/FunkinLua.hx:1480: characters 34-42 : Class<PlayState> has no field instance
source/FunkinLua.hx:1481: characters 34-42 : Class<PlayState> has no field instance
source/FunkinLua.hx:1482: characters 32-40 : Class<PlayState> has no field instance
source/FunkinLua.hx:1483: characters 35-43 : Class<PlayState> has no field instance
source/FunkinLua.hx:1484: characters 36-44 : Class<PlayState> has no field instance
source/FunkinLua.hx:1485: characters 34-42 : Class<PlayState> has no field instance
source/FunkinLua.hx:1486: characters 35-43 : Class<PlayState> has no field instance
source/FunkinLua.hx:1487: characters 35-43 : Class<PlayState> has no field instance
source/FunkinLua.hx:1495: characters 34-42 : Class<PlayState> has no field instance
source/FunkinLua.hx:1496: characters 34-42 : Class<PlayState> has no field instance
source/FunkinLua.hx:1497: characters 32-40 : Class<PlayState> has no field instance
source/FunkinLua.hx:1498: characters 35-43 : Class<PlayState> has no field instance
source/FunkinLua.hx:1506: characters 34-42 : Class<PlayState> has no field instance
source/FunkinLua.hx:1507: characters 34-42 : Class<PlayState> has no field instance
source/FunkinLua.hx:1508: characters 32-40 : Class<PlayState> has no field instance
source/FunkinLua.hx:1509: characters 35-43 : Class<PlayState> has no field instance
source/FunkinLua.hx:1520: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1534: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1540: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1544: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1545: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1549: characters 14-22 : Class<PlayState> has no field instance
source/PauseSubState.hx:300: characters 13-21 : Class<PlayState> has no field instance
source/PauseSubState.hx:302: characters 13-21 : Class<PlayState> has no field instance
source/FunkinLua.hx:1560: characters 14-34 : Class<PlayState> has no field cancelMusicFadeTween
source/FunkinLua.hx:1561: characters 48-56 : Class<PlayState> has no field instance
source/FunkinLua.hx:1571: characters 14-31 : Class<PlayState> has no field changedDifficulty
source/FunkinLua.hx:1572: characters 14-26 : Class<PlayState> has no field chartingMode
source/FunkinLua.hx:1573: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1584: characters 23-31 : Class<PlayState> has no field instance
source/FunkinLua.hx:1586: characters 23-31 : Class<PlayState> has no field instance
source/FunkinLua.hx:1588: characters 23-31 : Class<PlayState> has no field instance
source/FunkinLua.hx:1594: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:1596: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:1598: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:1604: characters 23-31 : Class<PlayState> has no field instance
source/FunkinLua.hx:1606: characters 23-31 : Class<PlayState> has no field instance
source/FunkinLua.hx:1608: characters 23-31 : Class<PlayState> has no field instance
source/FunkinLua.hx:1614: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:1616: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:1618: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:1626: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:3099: characters 44-52 : Class<PlayState> has no field instance
source/FunkinLua.hx:3100: characters 48-56 : Class<PlayState> has no field instance
source/FunkinLua.hx:3102: characters 20-28 : Class<PlayState> has no field instance
source/FunkinLua.hx:1644: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1647: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1650: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1741: characters 27-35 : Class<PlayState> has no field instance
source/FunkinLua.hx:1742: characters 44-52 : Class<PlayState> has no field instance
source/FunkinLua.hx:1742: characters 75-83 : Class<PlayState> has no field instance
source/FunkinLua.hx:1743: characters 24-32 : Class<PlayState> has no field instance
source/FunkinLua.hx:2994: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2998: characters 38-46 : Class<PlayState> has no field instance
source/FunkinLua.hx:3001: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:3004: characters 13-21 : Class<PlayState> has no field instance
source/FunkinLua.hx:1756: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1766: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1773: characters 34-42 : Class<PlayState> has no field instance
source/FunkinLua.hx:1775: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:1785: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1786: characters 36-44 : Class<PlayState> has no field instance
source/FunkinLua.hx:1804: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1805: characters 36-44 : Class<PlayState> has no field instance
source/FunkinLua.hx:3193: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:3194: characters 36-44 : Class<PlayState> has no field instance
source/FunkinLua.hx:1832: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1833: characters 38-46 : Class<PlayState> has no field instance
source/FunkinLua.hx:1874: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1875: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:1888: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1889: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:1899: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1900: characters 41-49 : Class<PlayState> has no field instance
source/FunkinLua.hx:1908: characters 20-28 : Class<PlayState> has no field instance
source/FunkinLua.hx:1914: characters 37-45 : Class<PlayState> has no field instance
source/FunkinLua.hx:1914: characters 72-80 : Class<PlayState> has no field instance
source/FunkinLua.hx:1915: characters 21-29 : Class<PlayState> has no field instance
source/FunkinLua.hx:1915: characters 56-64 : Class<PlayState> has no field instance
source/FunkinLua.hx:1916: characters 30-38 : Class<PlayState> has no field instance
source/FunkinLua.hx:1916: characters 65-73 : Class<PlayState> has no field instance
source/FunkinLua.hx:1917: characters 28-36 : Class<PlayState> has no field instance
source/FunkinLua.hx:1917: characters 63-71 : Class<PlayState> has no field instance
source/FunkinLua.hx:1918: characters 30-38 : Class<PlayState> has no field instance
source/FunkinLua.hx:1918: characters 65-73 : Class<PlayState> has no field instance
source/FunkinLua.hx:1920: characters 18-26 : Class<PlayState> has no field instance
source/FunkinLua.hx:1929: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1930: characters 36-44 : Class<PlayState> has no field instance
source/FunkinLua.hx:1950: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1951: characters 36-44 : Class<PlayState> has no field instance
source/FunkinLua.hx:1971: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:1972: characters 36-44 : Class<PlayState> has no field instance
source/FunkinLua.hx:1993: characters 38-46 : Class<PlayState> has no field instance
source/FunkinLua.hx:1994: characters 37-45 : Class<PlayState> has no field instance
source/FunkinLua.hx:2003: characters 18-26 : Class<PlayState> has no field instance
source/FunkinLua.hx:2007: characters 39-47 : Class<PlayState> has no field instance
source/FunkinLua.hx:2019: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2024: characters 21-29 : Class<PlayState> has no field instance
source/FunkinLua.hx:2027: characters 21-29 : Class<PlayState> has no field instance
source/FunkinLua.hx:2030: characters 21-29 : Class<PlayState> has no field instance
source/FunkinLua.hx:2039: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:2040: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:2048: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:2049: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:2061: characters 25-33 : Class<PlayState> has no field instance
source/FunkinLua.hx:2081: characters 25-33 : Class<PlayState> has no field instance
source/FunkinLua.hx:2101: characters 34-42 : Class<PlayState> has no field instance
source/FunkinLua.hx:2133: characters 26-34 : Class<PlayState> has no field instance
source/FunkinLua.hx:2200: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:2208: characters 18-26 : Class<PlayState> has no field instance
source/FunkinLua.hx:2209: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:2211: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:2227: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2228: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2230: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2242: characters 18-26 : Class<PlayState> has no field instance
source/FunkinLua.hx:2243: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:2245: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2246: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:2247: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:2246: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:2247: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:2246: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:2247: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:2254: characters 50-58 : Class<PlayState> has no field instance
source/FunkinLua.hx:2255: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2256: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2260: characters 50-58 : Class<PlayState> has no field instance
source/FunkinLua.hx:2261: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2265: characters 50-58 : Class<PlayState> has no field instance
source/FunkinLua.hx:2266: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2272: characters 24-32 : Class<PlayState> has no field instance
source/FunkinLua.hx:2273: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2280: characters 24-32 : Class<PlayState> has no field instance
source/FunkinLua.hx:2281: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2289: characters 24-32 : Class<PlayState> has no field instance
source/FunkinLua.hx:2290: characters 39-47 : Class<PlayState> has no field instance
source/FunkinLua.hx:2293: characters 16-24 : Class<PlayState> has no field instance
source/FunkinLua.hx:2302: characters 24-32 : Class<PlayState> has no field instance
source/FunkinLua.hx:2303: characters 22-30 : Class<PlayState> has no field instance
source/FunkinLua.hx:2312: characters 24-32 : Class<PlayState> has no field instance
source/FunkinLua.hx:2313: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2317: characters 50-58 : Class<PlayState> has no field instance
source/FunkinLua.hx:2318: characters 22-30 : Class<PlayState> has no field instance
source/FunkinLua.hx:2323: characters 50-58 : Class<PlayState> has no field instance
source/FunkinLua.hx:2324: characters 39-47 : Class<PlayState> has no field instance
source/FunkinLua.hx:2980: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2984: characters 36-44 : Class<PlayState> has no field instance
source/FunkinLua.hx:2987: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:2990: characters 13-21 : Class<PlayState> has no field instance
source/FunkinLua.hx:3313: characters 24-32 : Class<PlayState> has no field instance
source/FunkinLua.hx:2365: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:2857: characters 20-28 : Class<PlayState> has no field instance
source/FunkinLua.hx:2857: characters 68-76 : Class<PlayState> has no field instance
source/FunkinLua.hx:2857: characters 133-141 : Class<PlayState> has no field instance
source/FunkinLua.hx:2475: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2476: characters 39-47 : Class<PlayState> has no field instance
source/FunkinLua.hx:2485: characters 18-26 : Class<PlayState> has no field instance
source/FunkinLua.hx:2489: characters 37-45 : Class<PlayState> has no field instance
source/FunkinLua.hx:2501: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2506: characters 18-26 : Class<PlayState> has no field instance
source/FunkinLua.hx:2510: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2516: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2518: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2524: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2526: characters 50-58 : Class<PlayState> has no field instance
source/FunkinLua.hx:2533: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2535: characters 32-40 : Class<PlayState> has no field instance
source/FunkinLua.hx:2609: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2610: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2625: characters 19-27 : Class<PlayState> has no field instance
source/FunkinLua.hx:2626: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2628: characters 19-27 : Class<PlayState> has no field instance
source/FunkinLua.hx:2628: characters 52-60 : Class<PlayState> has no field instance
source/FunkinLua.hx:2629: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2631: characters 19-27 : Class<PlayState> has no field instance
source/FunkinLua.hx:2632: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2637: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2641: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2646: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2647: characters 41-49 : Class<PlayState> has no field instance
source/FunkinLua.hx:2656: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2662: characters 42-50 : Class<PlayState> has no field instance
source/FunkinLua.hx:2671: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2672: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2677: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2678: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2686: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2687: characters 15-23 : Class<PlayState> has no field instance
source/FunkinLua.hx:2694: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2695: characters 41-49 : Class<PlayState> has no field instance
source/FunkinLua.hx:2704: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2707: characters 64-72 : Class<PlayState> has no field instance
source/FunkinLua.hx:2713: characters 42-50 : Class<PlayState> has no field instance
source/FunkinLua.hx:2719: characters 17-25 : Class<PlayState> has no field instance
source/FunkinLua.hx:2722: characters 64-72 : Class<PlayState> has no field instance
source/FunkinLua.hx:2729: characters 35-43 : Class<PlayState> has no field instance
source/PauseSubState.hx:41: characters 16-28 : Class<PlayState> has no field chartingMode
source/PauseSubState.hx:46: characters 18-26 : Class<PlayState> has no field instance
source/PauseSubState.hx:94: characters 51-63 : Class<PlayState> has no field deathCounter
source/PauseSubState.hx:105: characters 36-44 : Class<PlayState> has no field instance
source/PauseSubState.hx:114: characters 36-48 : Class<PlayState> has no field chartingMode
source/PauseSubState.hx:215: characters 16-33 : Class<PlayState> has no field changedDifficulty
source/PauseSubState.hx:216: characters 16-28 : Class<PlayState> has no field chartingMode
source/PauseSubState.hx:233: characters 16-24 : Class<PlayState> has no field instance
source/PauseSubState.hx:233: characters 51-59 : Class<PlayState> has no field instance
source/PauseSubState.hx:234: characters 16-33 : Class<PlayState> has no field changedDifficulty
source/PauseSubState.hx:235: characters 39-47 : Class<PlayState> has no field instance
source/PauseSubState.hx:240: characters 16-28 : Class<PlayState> has no field chartingMode
source/PauseSubState.hx:244: characters 17-28 : Class<PlayState> has no field startOnTime
source/PauseSubState.hx:251: characters 18-26 : Class<PlayState> has no field instance
source/PauseSubState.hx:252: characters 18-26 : Class<PlayState> has no field instance
source/PauseSubState.hx:258: characters 16-24 : Class<PlayState> has no field instance
source/PauseSubState.hx:260: characters 16-24 : Class<PlayState> has no field instance
source/PauseSubState.hx:260: characters 52-60 : Class<PlayState> has no field instance
source/PauseSubState.hx:261: characters 16-33 : Class<PlayState> has no field changedDifficulty
source/PauseSubState.hx:262: characters 16-24 : Class<PlayState> has no field instance
source/PauseSubState.hx:262: characters 56-64 : Class<PlayState> has no field instance
source/PauseSubState.hx:263: characters 16-24 : Class<PlayState> has no field instance
source/PauseSubState.hx:264: characters 16-24 : Class<PlayState> has no field instance
source/PauseSubState.hx:267: characters 16-28 : Class<PlayState> has no field chartingMode
source/PauseSubState.hx:269: characters 16-28 : Class<PlayState> has no field deathCounter
source/PauseSubState.hx:270: characters 16-28 : Class<PlayState> has no field seenCutscene
source/PauseSubState.hx:278: characters 16-36 : Class<PlayState> has no field cancelMusicFadeTween
source/PauseSubState.hx:280: characters 16-33 : Class<PlayState> has no field changedDifficulty
source/PauseSubState.hx:281: characters 16-28 : Class<PlayState> has no field chartingMode
source/GameOverSubstate.hx:45: characters 13-21 : Class<PlayState> has no field instance
source/GameOverSubstate.hx:54: characters 13-21 : Class<PlayState> has no field instance
source/GameOverSubstate.hx:97: characters 13-21 : Class<PlayState> has no field instance
source/GameOverSubstate.hx:198: characters 14-22 : Class<PlayState> has no field instance
source/GameOverSubstate.hx:111: characters 14-26 : Class<PlayState> has no field deathCounter
source/GameOverSubstate.hx:112: characters 14-26 : Class<PlayState> has no field seenCutscene
source/GameOverSubstate.hx:113: characters 14-26 : Class<PlayState> has no field chartingMode
source/GameOverSubstate.hx:122: characters 14-22 : Class<PlayState> has no field instance
source/GameOverSubstate.hx:163: characters 13-21 : Class<PlayState> has no field instance
source/StrumNote.hx:57: characters 45-56 : Class<PlayState> has no field daPixelZoom
source/Note.hx:318: characters 45-56 : Class<PlayState> has no field daPixelZoom
source/Note.hx:324: characters 69-80 : Class<PlayState> has no field daPixelZoom
source/Note.hx:256: characters 18-26 : Class<PlayState> has no field instance
source/Note.hx:258: characters 36-44 : Class<PlayState> has no field instance
source/Note.hx:270: characters 26-37 : Class<PlayState> has no field daPixelZoom
source/editors/EditorPlayState.hx:891: characters 59-70 : Class<PlayState> has no field daPixelZoom
source/editors/EditorPlayState.hx:892: characters 63-74 : Class<PlayState> has no field daPixelZoom
source/editors/EditorPlayState.hx:925: characters 64-75 : Class<PlayState> has no field daPixelZoom
source/Conductor.hx:38: characters 38-46 : Class<PlayState> has no field instance
source/Conductor.hx:182: characters 30-38 : Class<PlayState> has no field instance
source/Conductor.hx:182: characters 73-81 : Class<PlayState> has no field instance`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

For Something

**Comment by StefanBETA2008** [comment]
I Don't Know. I Just Want To Try To See If I Can Get Back The Wavy Background Code On 0.6.2 :(.

**Comment by MemeHoovy** [comment]
try using the shaders.hx file from here
https://github.com/InsKal/Psych-Engine-With-Android-Shaders-And-More-Callbacks

**Comment by StefanBETA2008** [comment]
> try using the shaders.hx file from here https://github.com/InsKal/Psych-Engine-With-Android-Shaders-And-More-Callbacks

I Will Try

**Comment by EgguMan** [comment]
did what you tried work

**Comment by StefanBETA2008** [comment]
> did what you tried work

I Just Following The Old Shader Code For Wavy Background And I Got Error
