### ISSUE TITLE
Checkpoint custom notes

### ISSUE THREAD

**Issue by spinlesss** [ShadowMario/FNF-PsychEngine#10493]
### Describe your problem here.

is there any way to make custom notes that are checkpoints? it would be perfect for long songs like triple trouble

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Mastercopper2346** [comment]
Yeah, not possible in lua.

**Comment by BlazingDragonsYT** [comment]
I mean, it might be possible, just very difficult.

**Comment by wubbzyfan** [comment]
The main issue is preserving info across deaths, something that would be really useful if possible, shadow Mario that’d be really cool

**Comment by spinlesss** [comment]
> Yeah, not possible in lua.

if you know how, can you send the code plz, i will credit you for the code

**Comment by StefanBETA2008** [comment]
> ### Describe your problem here.
> is there any way to make custom notes that are checkpoints? it would be perfect for long songs like triple trouble
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No

Did You Talked To 5Keys?

**Comment by MemeHoovy** [comment]
> > ### Describe your problem here.
> > is there any way to make custom notes that are checkpoints? it would be perfect for long songs like triple trouble
> > ### Are you modding a build from source or with Lua?
> > Lua
> > ### What is your build target?
> > Windows x64
> > ### Did you edit anything in this build? If so, mention or summarize your changes.
> > No
> 
> Did You Talked To 5Keys?

wdym?

**Comment by StefanBETA2008** [comment]
> > > ### Describe your problem here.
> > > is there any way to make custom notes that are checkpoints? it would be perfect for long songs like triple trouble
> > > ### Are you modding a build from source or with Lua?
> > > Lua
> > > ### What is your build target?
> > > Windows x64
> > > ### Did you edit anything in this build? If so, mention or summarize your changes.
> > > No
> > 
> > 
> > Did You Talked To 5Keys?
> 
> wdym?

Let Me Explain:
The Opponent Has Have Only 4 Keys
And The Boyfriend Has Have 5 Keys.
I Saw Someone Has Maked The Lua Code For The Extra Keys. You Can Find The Video About The Lua Extra Keys. If You Want Boyfriend Do Have 5 Keys, Just Go To The `Chart Editor` ---> `Events` And Find The `Player 1`.
`Player1` = `Boyfriend`
`Player2` = `Opponent`

**Comment by MemeHoovy** [comment]
> Let Me Explain: The Opponent Has Have Only 4 Keys And The Boyfriend Has Have 5 Keys. I Saw Someone Has Maked The Lua Code For The Extra Keys. You Can Find The Video About The Lua Extra Keys. If You Want Boyfriend Do Have 5 Keys, Just Go To The `Chart Editor` ---> `Events` And Find The `Player 1`. `Player1` = `Boyfriend` `Player2` = `Opponent`
> 
> `YOU NEED TO INSTALL THE EVENT FIRST TO WORK BEFORE OR THE MOD`

ok, but how's that any way related to this issue?

**Comment by StefanBETA2008** [comment]
> > Let Me Explain: The Opponent Has Have Only 4 Keys And The Boyfriend Has Have 5 Keys. I Saw Someone Has Maked The Lua Code For The Extra Keys. You Can Find The Video About The Lua Extra Keys. If You Want Boyfriend Do Have 5 Keys, Just Go To The `Chart Editor` ---> `Events` And Find The `Player 1`. `Player1` = `Boyfriend` `Player2` = `Opponent`
> > `YOU NEED TO INSTALL THE EVENT FIRST TO WORK BEFORE OR THE MOD`
> 
> ok, but how's that any way related to this issue?

I Don't Know Dude.

**Comment by MemeHoovy** [comment]
> > > Let Me Explain: The Opponent Has Have Only 4 Keys And The Boyfriend Has Have 5 Keys. I Saw Someone Has Maked The Lua Code For The Extra Keys. You Can Find The Video About The Lua Extra Keys. If You Want Boyfriend Do Have 5 Keys, Just Go To The `Chart Editor` ---> `Events` And Find The `Player 1`. `Player1` = `Boyfriend` `Player2` = `Opponent`
> > > `YOU NEED TO INSTALL THE EVENT FIRST TO WORK BEFORE OR THE MOD`
> > 
> > 
> > ok, but how's that any way related to this issue?
> 
> I Don't Know Dude.

😐

**Comment by BlazingDragonsYT** [comment]
> Let Me Explain: The Opponent Has Have Only 4 Keys And The Boyfriend Has Have 5 Keys. I Saw Someone Has Maked The Lua Code For The Extra Keys. You Can Find The Video About The Lua Extra Keys. If You Want Boyfriend Do Have 5 Keys, Just Go To The `Chart Editor` ---> `Events` And Find The `Player 1`. `Player1` = `Boyfriend` `Player2` = `Opponent`
> 
> `YOU NEED TO INSTALL THE EVENT FIRST TO WORK BEFORE OR THE MOD`

Yeaaahhh, don't know how that's really related to this issue. Also, I know that someone's already stated this, but I just don't get how this helps this issue.

**Comment by Itz-Miles** [comment]
If bf hits one of these said checkpoint notes, make sure he doesn't die when his health isn't 0 and set the song time to the last hit checkpoint note.

it's also easy to read/write information past the death barrier, even if you save variables into a file

**Comment by spinlesss** [comment]
> If bf hits one of these said checkpoint notes, make sure he doesn't die when his health isn't 0 and set the song time to the last hit checkpoint note.
> 
> it's also easy to read/write information past the death barrier, even if you save variables into a file

I dont understand, can you explain it more easily?
