### ISSUE TITLE
Sprite bug

### ISSUE THREAD

**Issue by 3hex1** [ShadowMario/FNF-PsychEngine#10506]
### Describe your bug here.

(Using spritesheet and xml genertator) 1st what happens is when i use the character editor in the top it says idle(error) whilst in the game is fully crashes

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2868)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by DisIsNOt** [comment]
You didn't do the json file correctly
