### ISSUE TITLE
How do i move "timeTxt" position

### ISSUE THREAD

**Issue by NukeThief** [ShadowMario/FNF-PsychEngine#10507]
### Describe your problem here.

i cant find how

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHoovy** [comment]
setProperty('timeBar.x', anynumber)
setProperty('timeBar.y', anynumber)

**Comment by NukeThief** [comment]
thank :)

**Comment by NukeThief** [comment]
Altough it's supposed to be:

setProperty('**timeTxt**.x', number)
setPropperty('**timeTxt**.y', numba)
