### ISSUE TITLE
Mhm, a question, how to compile and run project?

### ISSUE THREAD

**Issue by vega0** [ShadowMario/FNF-PsychEngine#10503]
### What is your question?

How to compile and run project? 
Haxe is installed.

**Comment by TheKitBoi** [comment]
lime build windows
or 
lime test windows

**Comment by MemeHoovy** [comment]
> lime build windows
> or
> lime test windows

lime build windows -release or -debug
or
lime test windows -release or -debug
just correcting you @TheKitBoi

**Comment by vega0** [comment]
lime is external source?

**Comment by MemeHoovy** [comment]
> lime is external source?

yes, do ```haxelib install lime``` then run the commands above
