### ISSUE TITLE
Bullet Note Texture Disapearing After I Hit It Once

### ISSUE THREAD

**Issue by doitover** [ShadowMario/FNF-PsychEngine#10502]
### What is your question?

so basically I have three bullet notes for me to hit the first one has the texture
the second one does not
and the third one does not also
I have a video of the code and everything
please, help me!
https://www.youtube.com/watch?v=O9nIOXRkWQU&feature=youtu.be

**Comment by TheKitBoi** [comment]
send the script

**Comment by doitover** [comment]
https://www.mediafire.com/file/pn2oug2hh19wv26/Bullet+Note.lua/file

**Comment by doitover** [comment]
nvm just had to update PE
