### ISSUE TITLE
how do i change the scroll factor of bf?

### ISSUE THREAD

**Issue by Only-a-cat** [ShadowMario/FNF-PsychEngine#10505]
### Describe your problem here.

how do i change the scroll factor of bf?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JP297** [comment]
function onUpdate()

	setProperty('boyfriend.scrollFactor.x', 0.9);
	setProperty('boyfriend.scrollFactor.y', 0.9);

end




**_Hopefully this works, just change the number to whatever you want ofc_**

**Comment by CrusherNotDrip** [comment]
> function onUpdate()
> 
> ```
> setProperty('boyfriend.scrollFactor.x', 0.9);
> setProperty('boyfriend.scrollFactor.y', 0.9);
> ```
> 
> end
> 
> **_Hopefully this works, just change the number to whatever you want ofc_**

Why onUpdate
just use onCreatePost

**Comment by Only-a-cat** [comment]
thank you so much!
to change the layer of the bf is the same thing? (I'm trying to place the opponent in front of an object from the background)

**Comment by Lorekeeper49** [comment]
> thank you so much!
> to change the layer of the bf is the same thing? (I'm trying to place the opponent in front of an object from the background)

Not exactly, you need to use `setObjectOrder('bfGroup', int), setObjectOrder('gfGroup', int), or setObjectOrder('dadGroup', int)` for that
