### ISSUE TITLE
Different strum textures for player and opponent

### ISSUE THREAD

**Issue by EpicShapeShifter** [ShadowMario/FNF-PsychEngine#10508]
### Describe your problem here.

How do I make the two note groups have different textures?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not yet no

**Comment by MemeHoovy** [comment]
this has what your looking for
https://gamebanana.com/tools/7714

**Comment by EpicShapeShifter** [comment]
ok thanks

**Comment by MemeHoovy** [comment]
> ok thanks

your welcome, now close the issue please
