### ISSUE TITLE
Mid song health drain

### ISSUE THREAD

**Issue by joxu13v** [ShadowMario/FNF-PsychEngine#10514]
### Describe your problem here.

I need some way to start and stop the health drain mid song using.lua, can someone help me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by DisIsNOt** [comment]
nobitches = false;

function onBeatHit()
     if nobitches = true then
             shit()

     end



end


function shit()
    hp = getProperty('health')
    
    if hp > 0.010 and nobitches == true then
        setProperty('health', hp - 0.025)
    end

end


may be it will work or somthing idk

**Comment by joxu13v** [comment]
Thanks a lot
