### ISSUE TITLE
I want .lua file

### ISSUE THREAD

**Issue by Virnor** [ShadowMario/FNF-PsychEngine#10512]
### What is your question?

How to make no damage from long note (which on Kade Engine mods) (If understood me of course, because my English is bad).

**Comment by MemeHoovy** [comment]
> ### What is your question?
> How to make no damage from long note (which on Kade Engine mods) (If understood me of course, because my English is bad).

not possible with lua

**Comment by ItsMeTyler25** [comment]
> ### What is your question?
> How to make no damage from long note (which on Kade Engine mods) (If understood me of course, because my English is bad).

This should do it!

**function noteMiss(id, direction, noteType, isSustainNote)
       if isSustainNote then
              addHealth('0.0475')
end
end**

**Comment by kingyomoma** [comment]
> not possible with lua
```lua
function onCreate()
	for i = 0, getProperty('unspawnNotes.length')-1 do
		if getPropertyFromGroup('unspawnNotes', i, 'isSustainNote') then
			setPropertyFromGroup('unspawnNotes', i, 'hitHealth', 0)
		end
	end
end
```

**Comment by MemeHoovy** [comment]
> > not possible with lua
> 
> ```lua
> function onCreate()
> 	for i = 0, getProperty('unspawnNotes.length')-1 do
> 		if getPropertyFromGroup('unspawnNotes', i, 'isSustainNote') then
> 			setPropertyFromGroup('unspawnNotes', i, 'hitHealth', 0)
> 		end
> 	end
> end
> ```

they asked to take no **damage** when you miss a sustain note, not when you hit one

**Comment by Virnor** [comment]
Thank you, ItsMeTyler25!

**Comment by kingyomoma** [comment]
> > > not possible with lua
> > 
> > 
> > ```lua
> > function onCreate()
> > 	for i = 0, getProperty('unspawnNotes.length')-1 do
> > 		if getPropertyFromGroup('unspawnNotes', i, 'isSustainNote') then
> > 			setPropertyFromGroup('unspawnNotes', i, 'hitHealth', 0)
> > 		end
> > 	end
> > end
> > ```
> 
> they asked to take no **damage** when you miss a sustain note, not when you hit one

fixed

**Comment by MemeHoovy** [comment]
> > > > not possible with lua
> > > 
> > > 
> > > ```lua
> > > function onCreate()
> > > 	for i = 0, getProperty('unspawnNotes.length')-1 do
> > > 		if getPropertyFromGroup('unspawnNotes', i, 'isSustainNote') then
> > > 			setPropertyFromGroup('unspawnNotes', i, 'hitHealth', 0)
> > > 		end
> > > 	end
> > > end
> > > ```
> > 
> > 
> > they asked to take no **damage** when you miss a sustain note, not when you hit one
> 
> fixed

wdym? there's nothing different

**Comment by kingyomoma** [comment]
i edited the original message

**Comment by MemeHoovy** [comment]
> i edited the original message

oh

**Comment by DisIsNOt** [comment]
Now close this
