### ISSUE TITLE
(am I being dumb?) How do I get the opponent's name?

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#10517]
### Describe your problem here.

everytime i try to use `dadname` or `getProperty('dad.curCharacter')` it returns a null string
![Captura de Tela (52)](https://user-images.githubusercontent.com/101405920/189555353-a39ca089-93c8-4aec-88b7-438fe6857dc6.png)
### code:
![Captura de Tela (51)](https://user-images.githubusercontent.com/101405920/189555396-a8712019-d7f2-4f66-96a1-0ca41ca4f6d7.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

not anything important just charts

**Comment by BernardoGP4504** [comment]
i even tried using `getPropertyFromClass('ChartingState', 'player2')` but the player2 returns itself not it's value

**Comment by frantastic24** [comment]
`dadName` under `onCreatePost()`

**Comment by BernardoGP4504** [comment]
> `dadName` under `onCreatePost()`

Thanks will try
