### ISSUE TITLE
twoooooooooooooooo

### ISSUE THREAD

**Issue by swobodac** [ShadowMario/FNF-PsychEngine#10516]
### What is your question?

do you know how to make a video play if you press 2

**Comment by bruh1cat** [comment]
function onUpdate()
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.TWO') then
        startVideo('spiderman')
    end
end

**Comment by bruh1cat** [comment]
Also since you don't want to learn coding and are asking people to do your work I hope that whatever mod you're working on you at least credit us.

**Comment by DisIsNOt** [comment]
💀💀

**Comment by bruh1cat** [comment]
> 💀💀bro still can't learn to close issue

Fr, also he wants to make a shitty  d&b mod 🤣

**Comment by TheKitBoi** [comment]
lemme bring the image just to make his brain 1% better
![close the dam issue](https://user-images.githubusercontent.com/84044666/189709107-a64943dd-5059-4928-aef6-0a9da787648e.gif)

**Comment by bruh1cat** [comment]
> lemme bring the image just to make his brain 1% better
> 
> ![close the dam issue](https://user-images.githubusercontent.com/84044666/189709107-a64943dd-5059-4928-aef6-0a9da787648e.gif)

🤣🤣🤣

**Comment by swobodac** [comment]
btw firged it out by my self
