### ISSUE TITLE
Tweens Being Dumb

### ISSUE THREAD

**Issue by smisanasshole** [ShadowMario/FNF-PsychEngine#10515]
### Describe your problem here.

So I'm trying to make it so that during the song GF floats upward and off the screen but for some reason it isn't working. All the other tweens I used in the song work fine but for some reason these ones don't and I have no idea why.

Here's the code that's supposed to do the thing.
`if curStep == 2440 then`
`	doTweenAngle('kword', 'girlfriend', -50, 4, 'easeIn')`
`	doTweenY('lword', 'girlfriend', -400, 4, 'easeIn')`
`	doTweenX('mword', 'girlfriend', 1150, 4, 'easeIn')`
`end`

Also this probably isn't relevant but GF is doing a hold note at the point in the song that the tweens are supposed to happen (on the player's side specifically). Seriously doubt that's the issue but maybe it is.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, the source code has not been messed with any way.

**Comment by frantastic24** [comment]
`'gf'`

**Comment by ItsMeTyler25** [comment]
> ### Describe your problem here.
> So I'm trying to make it so that during the song GF floats upward and off the screen but for some reason it isn't working. All the other tweens I used in the song work fine but for some reason these ones don't and I have no idea why.
> 
> Here's the code that's supposed to do the thing. `if curStep == 2440 then` ` doTweenAngle('kword', 'girlfriend', -50, 4, 'easeIn')` ` doTweenY('lword', 'girlfriend', -400, 4, 'easeIn')` ` doTweenX('mword', 'girlfriend', 1150, 4, 'easeIn')` `end`
> 
> Also this probably isn't relevant but GF is doing a hold note at the point in the song that the tweens are supposed to happen (on the player's side specifically). Seriously doubt that's the issue but maybe it is.
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No, the source code has not been messed with any way.

I believe replacing "girlfriend" in the tween with "gfGroup" should do make it work!

**Comment by smisanasshole** [comment]
> `'gf'`

That worked. Thanks!
