### ISSUE TITLE
Custom Pause Menu

### ISSUE THREAD

**Issue by N1CKN0TAD3** [ShadowMario/FNF-PsychEngine#10510]
### Describe your problem here.

Hello people of github. Does anybody have A way I can perhaps make a custom pause menu? What file would I even edit the code to? If someone could answer me, then I would appreciate it! (Also, I'm trying not to fail the test, shadow.)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I removed all code related to the Easter egg in TitleState.hx

**Comment by N1CKN0TAD3** [comment]
Also: Message me on discord if you need! N1CKN0TAD3//MONKEKING#2593

**Comment by TheKitBoi** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/PauseSubState.hx

**Comment by N1CKN0TAD3** [comment]
Thanks
