### ISSUE TITLE
I need help to export the engine

### ISSUE THREAD

**Issue by Carlnal** [ShadowMario/FNF-PsychEngine#10518]
### Describe your problem here.

When I export the Psych Engine, I get an error that says " Unknown identifier : cam" in the rows 134-140 and I don´t know what to do.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by machonessiebaby** [comment]
screenshot your terminal error and send your code around those lines

**Comment by Votex-coder** [comment]
> screenshot your terminal error and send your code around those lines

he guess someone this

![Image](https://github.com/user-attachments/assets/d8ec29eb-b39c-410a-9248-ecac42307e2b)
