### ISSUE TITLE
Emergency Menu Combination

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#10520]
### What feature do you want to get added on the **base** engine?

In case that someone gets soft Locked, you could press a certain Combination on the keyboard, to return to the menu
(Ex: ESC, LSHIFT, RSHIFT, ENTER)

If one messes up with some code (which can be done easily by calling multiple scripts for example, like dialogues), you then don't have to reopen the game, and maybe lose unsaved progress, or time

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by DisIsNOt** [comment]
Just do exitSong when a certain key is pressed

**Comment by Parsellol** [comment]
honestly naaaaah

it sure is annoying when u get soft locked and u have to restart ur game while making a script but just make it so the song restarts when hitting a certain key
