### ISSUE TITLE
This is possible?

### ISSUE THREAD

**Issue by SENFULLHD4K** [ShadowMario/FNF-PsychEngine#10523]
### What is your question?

I don't know if this is possible in lua but I want to make it so that when an arrow is pressed an image appears covering the arrows and they are not visible (the arrow is a custom arrow and should not be pressed)

If someone helps me it would be a great appreciation, thanks for your attention

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Custom-Sprites-Functions

**Comment by SENFULLHD4K** [comment]
And now what do I do?

**Comment by frantastic24** [comment]
Start coding probably

**Comment by SENFULLHD4K** [comment]
HOW MAAN

**Comment by kingyomoma** [comment]
by learning how to
![shoebill](https://user-images.githubusercontent.com/96543290/189998340-1d9aeef9-e76e-4800-a46d-4dfa7a736482.png)

**Comment by SENFULLHD4K** [comment]
epic

**Comment by TheKitBoi** [comment]
Close this issue

**Comment by SENFULLHD4K** [comment]
:Ccccccccc
