### ISSUE TITLE
The AfterTitleState.hx

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10526]
### What is your question?

It's Possible To Add Like This Before You Entering The MainMenu:
![Screenshot_20220913-190434](https://user-images.githubusercontent.com/109828559/189963270-87de78b8-f4fa-4dde-8ab0-f76668773664.png)

**Comment by MemeHoovy** [comment]
> ### What is your question?
> It's Possible To Add Like This Before You Entering The MainMenu: ![Screenshot_20220913-190434](https://user-images.githubusercontent.com/109828559/189963270-87de78b8-f4fa-4dde-8ab0-f76668773664.png)

ok, but what the hell is the point of this?

**Comment by StefanBETA2008** [comment]
> > ### What is your question?
> > It's Possible To Add Like This Before You Entering The MainMenu: ![Screenshot_20220913-190434](https://user-images.githubusercontent.com/109828559/189963270-87de78b8-f4fa-4dde-8ab0-f76668773664.png)
> 
> ok, but what the hell is the point of this?

**Comment by TheKitBoi** [comment]
> ### What is your question?
> It's Possible To Add Like This Before You Entering The MainMenu

switch states

**Comment by StefanBETA2008** [comment]
> > ### What is your question?
> > It's Possible To Add Like This Before You Entering The MainMenu
> 
> switch states

Nevermind, I Just Maked. Thanks
