### ISSUE TITLE
The Watermark 

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10525]
### Describe your problem here.

How To Make The Watermark With The Source Code?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes.

**Comment by MemeHoovy** [comment]
> ### Describe your problem here.
> How To Make The Watermark With The Source Code?
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> Yes.

Just borrow code from Kade Engine.

**Comment by Parsellol** [comment]
make a flxtext

**Comment by StefanBETA2008** [comment]
Code For Watermark Please Or Line 🙏🏻

**Comment by MemeHoovy** [comment]
> Code For Watermark Please Or Line 🙏🏻

here's only half of it
```
		kadeEngineWatermark = new FlxText(4,healthBarBG.y + 50,0,SONG.song + " - " + CoolUtil.difficultyFromInt(storyDifficulty) + (Main.watermarks ? " | KE " + MainMenuState.kadeEngineVer : ""), 16);
		kadeEngineWatermark.setFormat(Paths.font("vcr.ttf"), 16, FlxColor.WHITE, RIGHT, FlxTextBorderStyle.OUTLINE,FlxColor.BLACK);
		kadeEngineWatermark.scrollFactor.set();
		add(kadeEngineWatermark);
```
look in here for the rest
https://github.com/MemeHoovy/Kade-Engine-1.5.4

**Comment by Parsellol** [comment]
> > Code For Watermark Please Or Line 🙏🏻
> 
> here's only half of it
> 
> ```
> 		kadeEngineWatermark = new FlxText(4,healthBarBG.y + 50,0,SONG.song + " - " + '$storyDifficulty' + (Main.watermarks ? " | KE " + MainMenuState.kadeEngineVer : ""), 16);
> 		kadeEngineWatermark.setFormat(Paths.font("vcr.ttf"), 16, FlxColor.WHITE, RIGHT, FlxTextBorderStyle.OUTLINE,FlxColor.BLACK);
> 		kadeEngineWatermark.scrollFactor.set();
> 		add(kadeEngineWatermark);
> ```
> 
> look in here for the rest https://github.com/MemeHoovy/Kade-Engine-1.5.4

made it compaitable with psych

look for the line ```import Conductor.Rating;``` at the top of playstate and add ```import MainMenuState;``` below it

then look for the line ```add(scoreTxt);``` and add this below it
```haxe
		var peWatermark = new FlxText(4,healthBarBG.y + 50,0,SONG.song + " - " + storyDifficultyText + " | PE " + MainMenuState.psychEngineVersion, 16);
		peWatermark.setFormat(Paths.font("vcr.ttf"), 16, FlxColor.WHITE, RIGHT, FlxTextBorderStyle.OUTLINE,FlxColor.BLACK);
		peWatermark.scrollFactor.set();
		add(peWatermark);
```

**Comment by StefanBETA2008** [comment]
I Will Try, But Thanks For The Line And Code

**Comment by MemeHoovy** [comment]
> > > Code For Watermark Please Or Line 🙏🏻
> > 
> > 
> > here's only half of it
> > ```
> > 		kadeEngineWatermark = new FlxText(4,healthBarBG.y + 50,0,SONG.song + " - " + '$storyDifficulty' + (Main.watermarks ? " | KE " + MainMenuState.kadeEngineVer : ""), 16);
> > 		kadeEngineWatermark.setFormat(Paths.font("vcr.ttf"), 16, FlxColor.WHITE, RIGHT, FlxTextBorderStyle.OUTLINE,FlxColor.BLACK);
> > 		kadeEngineWatermark.scrollFactor.set();
> > 		add(kadeEngineWatermark);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > look in here for the rest https://github.com/MemeHoovy/Kade-Engine-1.5.4
> 
> made it compaitable with psych
> 
> look for the line `import Conductor.Rating;` at the top of playstate and add `import MainMenuState;` below it
> 
> then look for the line `add(scoreTxt);` and add this below it
> 
> ```hx
> 		var peWatermark = new FlxText(4,healthBarBG.y + 50,0,SONG.song + " - " + storyDifficultyText + " | PE " + MainMenuState.psychEngineVersion, 16);
> 		peWatermark.setFormat(Paths.font("vcr.ttf"), 16, FlxColor.WHITE, RIGHT, FlxTextBorderStyle.OUTLINE,FlxColor.BLACK);
> 		peWatermark.scrollFactor.set();
> 		add(peWatermark);
> ```
> 
> then lastly put `peWatermark.cameras = [camHUD];` under `scoreTxt.cameras = [camHUD];`

you don't gotta import mainmenustate you know

**Comment by StefanBETA2008** [comment]
> > > > Code For Watermark Please Or Line 🙏🏻
> > > 
> > > 
> > > here's only half of it
> > > ```
> > > 		kadeEngineWatermark = new FlxText(4,healthBarBG.y + 50,0,SONG.song + " - " + '$storyDifficulty' + (Main.watermarks ? " | KE " + MainMenuState.kadeEngineVer : ""), 16);
> > > 		kadeEngineWatermark.setFormat(Paths.font("vcr.ttf"), 16, FlxColor.WHITE, RIGHT, FlxTextBorderStyle.OUTLINE,FlxColor.BLACK);
> > > 		kadeEngineWatermark.scrollFactor.set();
> > > 		add(kadeEngineWatermark);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > look in here for the rest https://github.com/MemeHoovy/Kade-Engine-1.5.4
> > 
> > 
> > made it compaitable with psych
> > look for the line `import Conductor.Rating;` at the top of playstate and add `import MainMenuState;` below it
> > then look for the line `add(scoreTxt);` and add this below it
> > ```hx
> > 		var peWatermark = new FlxText(4,healthBarBG.y + 50,0,SONG.song + " - " + storyDifficultyText + " | PE " + MainMenuState.psychEngineVersion, 16);
> > 		peWatermark.setFormat(Paths.font("vcr.ttf"), 16, FlxColor.WHITE, RIGHT, FlxTextBorderStyle.OUTLINE,FlxColor.BLACK);
> > 		peWatermark.scrollFactor.set();
> > 		add(peWatermark);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then lastly put `peWatermark.cameras = [camHUD];` under `scoreTxt.cameras = [camHUD];`
> 
> you don't gotta import mainmenustate you know

It's Working. Thank You

**Comment by Parsellol** [comment]
> 

but would the version thingie still work if u didnt

**Comment by MemeHoovy** [comment]
> > 
> 
> but would the version thingie still work if u didnt

yes, I've tried this kind of thing before, and it worked without the import

**Comment by Parsellol** [comment]
> > > 
> > 
> > 
> > but would the version thingie still work if u didnt
> 
> yes, I've tried this kind of thing before, and it worked without the import

just tried and ur right ima fix rq sorry im not very experienced with haxe lol

**Comment by StefanBETA2008** [comment]
> > 
> 
> but would the version thingie still work if u didnt

source/PlayState.hx:1192: characters 76-95 : Unknown identifier : storyDifficultyText
source/PlayState.hx:1192: characters 76-95 : ... For optional function argument 'Text' Really?
![Screenshot_20220914-160750](https://user-images.githubusercontent.com/109828559/190177159-dd9e5314-c653-408a-b690-19f58b8be31b.png)

**Comment by MemeHoovy** [comment]
> > > > 
> > > 
> > > 
> > > but would the version thingie still work if u didnt
> > 
> > 
> > yes, I've tried this kind of thing before, and it worked without the import
> 
> just tried and ur right ima fix rq sorry im not very experienced with haxe lol

💀

**Comment by Parsellol** [comment]
wha

**Comment by MemeHoovy** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > but would the version thingie still work if u didnt
> > > > 
> > > > 
> > > > yes, I've tried this kind of thing before, and it worked without the import
> > > 
> > > 
> > > just tried and ur right ima fix rq sorry im not very experienced with haxe lol
> > 
> > 
> > bruh💀
> 
> Only Windows, Linux And Mac Has Doesn't Have The Problem

move the storydifficultytext outside of the #If_DISCORD_ALLOWED macro

**Comment by Parsellol** [comment]
> > wha
> 
> source/PlayState.hx:1192: characters 76-95 : Unknown identifier : storyDifficultyText source/PlayState.hx:1192: characters 76-95 : ... For optional function argument 'Text'
> 
> Only For The Android Port

do what memehoovy said or something idk

**Comment by StefanBETA2008** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > but would the version thingie still work if u didnt
> > > > > 
> > > > > 
> > > > > yes, I've tried this kind of thing before, and it worked without the import
> > > > 
> > > > 
> > > > just tried and ur right ima fix rq sorry im not very experienced with haxe lol
> > > 
> > > 
> > > bruh💀
> > 
> > 
> > Only Windows, Linux And Mac Has Doesn't Have The Problem
> 
> move the storydifficultytext outside of the #If_DISCORD_ALLOWED macro(s)

Line Please.

**Comment by MemeHoovy** [comment]
![Screenshot 2022-09-14 101242](https://user-images.githubusercontent.com/97995998/190178368-d37a9ab3-6eb4-4ce5-a4bc-c978d736381c.png)
![Screenshot 2022-09-14 101157](https://user-images.githubusercontent.com/97995998/190178376-cae1afdf-8896-4639-9a68-2c3731e9abb5.png)

**Comment by StefanBETA2008** [comment]
> ![Screenshot 2022-09-14 101242](https://user-images.githubusercontent.com/97995998/190178368-d37a9ab3-6eb4-4ce5-a4bc-c978d736381c.png) ![Screenshot 2022-09-14 101157](https://user-images.githubusercontent.com/97995998/190178376-cae1afdf-8896-4639-9a68-2c3731e9abb5.png)

Let Me See

**Comment by StefanBETA2008** [comment]
Than I Can't Fix This Error. I Got For All 4 Builds:

source/PlayState.hx:1192: characters 68-69 : Expected expression

**Comment by StefanBETA2008** [comment]
> > Than I Can't Fix This Error. I Got For All 4 Builds:
> > source/PlayState.hx:1192: characters 68-69 : Expected expression
> 
> can you share screenshots on what you did?

I Don't Know, I Just Deleted The Discord And That's Why I Getted

**Comment by Parsellol** [comment]
> > > Than I Can't Fix This Error. I Got For All 4 Builds:
> > > source/PlayState.hx:1192: characters 68-69 : Expected expression
> > 
> > 
> > can you share screenshots on what you did?
> 
> I Don't Know, I Just Deleted The Discord And That's Why I Getted

did u also delete the #end

**Comment by Parsellol** [comment]
> 

yep pretty sure

**Comment by MemeHoovy** [comment]
> > > > > Than I Can't Fix This Error. I Got For All 4 Builds:
> > > > > source/PlayState.hx:1192: characters 68-69 : Expected expression
> > > > 
> > > > 
> > > > can you share screenshots on what you did?
> > > 
> > > 
> > > I Don't Know, I Just Deleted The Discord And That's Why I Getted
> > 
> > 
> > did u also delete the #end
> 
> No? I Need To Delete?

no, don't.

**Comment by MemeHoovy** [comment]
> > > Than I Can't Fix This Error. I Got For All 4 Builds:
> > > source/PlayState.hx:1192: characters 68-69 : Expected expression
> > 
> > 
> > can you share screenshots on what you did?
> 
> I Don't Know, I Just Deleted The Discord And That's Why I Getted

you weren't suppost to delete the entire discord thing

**Comment by StefanBETA2008** [comment]
> > > > Than I Can't Fix This Error. I Got For All 4 Builds:
> > > > source/PlayState.hx:1192: characters 68-69 : Expected expression
> > > 
> > > 
> > > can you share screenshots on what you did?
> > 
> > 
> > I Don't Know, I Just Deleted The Discord And That's Why I Getted
> 
> you weren't suppost to delete the entire discord thing, just move the storydifficultytext variable outside of the macro

Nevermind Guy's, I Just Can't Add Ghe Watermark. Im Closing The Issue

**Comment by Parsellol** [comment]
ah well damn
