### ISSUE TITLE
Im testing a custom event and when i use it in the song the game crashes, whats happening?

### ISSUE THREAD

**Issue by Jevilm** [ShadowMario/FNF-PsychEngine#10528]
### Describe your problem here.

im using a custom event and when it occurs the game freezes and does not give me an error

vvv

function onEvent(name, value1, value2) 
 triggerEvent('Blammed Lights', '900')
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Edited HUD

**Comment by CrusherNotDrip** [comment]
I dont think blammed lights exist anymore

**Comment by Jevilm** [comment]
sadness
