### ISSUE TITLE
Dialogue help

### ISSUE THREAD

**Issue by joxu13v** [ShadowMario/FNF-PsychEngine#10529]
### Describe your problem here.

I can't find a dialog script that works correctly, can someone help me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Aidenkp112** [comment]
[dialouge funny.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/9599890/dialouge.funny.zip)
use this
its also on the wiki if u didnt know
