### ISSUE TITLE
Change Voices.ogg based on what character is used (via .lua)

### ISSUE THREAD

**Issue by NickPlayzGITHUB** [ShadowMario/FNF-PsychEngine#10535]
### What is your question?

So I was wondering if there was a way to play a different voices track depending on what characters are being used in the game using something like "if boyfriendName == 'characterHere' then" (I think that's it) could you then maybe use something like setProperty to change the vocal track?

**Comment by BernardoGP4504** [comment]
atleast to do this if statement:
```lua
function onCreatePost()
    if boyfriendName == 'characterHere' then
        --code here
    end
end
```

**Comment by frantastic24** [comment]
```lua
function onCreatePost()
    addHaxeLibrary('FlxSound', 'flixel.system')
    runHaxeCode([[
        game.vocals = new FlxSound().loadEmbedded(Paths.returnSound('songs', Paths.formatToSongPath("song name") + '/Voices')); --add suffix to /Voices or w/e
        FlxG.sound.list.add(game.vocals);
    ]])
end
```

**Comment by NickPlayzGITHUB** [comment]
> ```lua
> function onCreatePost()
>     addHaxeLibrary('FlxSound', 'flixel.system')
>     runHaxeCode([[
>         game.vocals = new FlxSound().loadEmbedded(Paths.returnSound('songs', Paths.formatToSongPath("song name") + '/Voices')); --add suffix to /Voices or w/e
>         FlxG.sound.list.add(game.vocals);
>     ]])
> end
> ```

Doesn't work, the vocals just don't play

**Comment by frantastic24** [comment]
You messed something up then

**Comment by NickPlayzGITHUB** [comment]
I modified it a bit but it shouldn't have messed it up.

function onCreatePost()
    if boyfriendName == 'thecharacternameisherebutIchangeditforthispostomgcrazy' then
        addHaxeLibrary('FlxSound', 'flixel.system')
        runHaxeCode([[
            game.vocals = new FlxSound().loadEmbedded(Paths.returnSound('songs', Paths.formatToSongPath("song name") + '/Voices1'));
            FlxG.sound.list.add(game.vocals);
        ]])
    else
        addHaxeLibrary('FlxSound', 'flixel.system')
        runHaxeCode([[
            game.vocals = new FlxSound().loadEmbedded(Paths.returnSound('songs', Paths.formatToSongPath("song name") + '/Voices'));
            FlxG.sound.list.add(game.vocals);
        ]])
    end
end

**Comment by frantastic24** [comment]
Why does it still say song name
I've already tested this and can confirm it works so something in your script is wrong, could be boyfriendName, or the Voices path or name

**Comment by NickPlayzGITHUB** [comment]
oh, I thought the song name thing grabbed the song name that was being played LMAO

**Comment by frantastic24** [comment]
You could use the PlayState variable to grab it, but I don't care enough to do it myself and it works anyway

**Comment by SIG7Pro** [comment]
Maybe you change the song depending on which character is being played as.
For instance something like:
if player character is = bf
switch song to = overview
if player character is = meanie
switch song to overview_minus

(idk how to have)
