### ISSUE TITLE
Is It Possible To boyfriend.stunned Only Certain Notes? Left, Down, etc.

### ISSUE THREAD

**Issue by LuckyMist8** [ShadowMario/FNF-PsychEngine#10531]
### Describe your problem here.

I Want To Be Able To Stun Only One Note At A Time, Not All Of Them
And Only Maybe Not Freeze The Idle Animation Lol

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I Haven't Touched Source Code At All

**Comment by DisIsNOt** [comment]
May be not possible

**Comment by Mastercopper2346** [comment]
Not possible in lua
