### ISSUE TITLE
How do you set a timer to restart the song once? (LUA)

### ISSUE THREAD

**Issue by LeefLett** [ShadowMario/FNF-PsychEngine#10539]
### What is your question?

As the title suggests, my question is how do you set a timer to restart the song once using lua? Ok, I thought about it, and I am not sure it will be possible without looping the timer over and over again due to the song restarting and the script being used again. If anyone is smart enough to help me than I will gladly accept. Thanks!

**Comment by LeefLett** [comment]
Yeah, thats what I thought. Well, thanks!

**Comment by frantastic24** [comment]
Save data #8286
