### ISSUE TITLE
The LoadingState.hx Problem 

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10536]
### Describe your problem here.

source/LoadingState.hx:49: characters 89-93 : Expected , or )

I Just Trying To Add The Radnom LoadingScreen On LoadingState.hx, But It's Still Showing The Error.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Just LoadingState

**Comment by DisIsNOt** [comment]
Just put a , or ) whatever it's on that line

**Comment by StefanBETA2008** [comment]
> Just put a , or ) whatever it's missing on that line

Nevermind, I Fixed
