### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by choptop84** [ShadowMario/FNF-PsychEngine#10534]
### Describe your bug here.

So, for some reason the game just crashes when I try to open the story mode, don't know why...

### Command Prompt/Terminal logs (if existing)

```bash
StoryMenuState.hx (line 275)
flixel/group/FlxGroup.hx (line 740)
StoryMenuState.hx (line 273)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited the Mod Folder and a little of MainMenuState, but that's all

**Comment by DisIsNOt** [comment]
what lines did you edit
