### ISSUE TITLE
opponentplay Help

### ISSUE THREAD

**Issue by zeadd21g1233** [ShadowMario/FNF-PsychEngine#10549]
### Describe your problem here.

i add opponentplay in sonic exe

and worked but i have a problem in sing anim

https://user-images.githubusercontent.com/95078441/190410165-f309b3b3-3bb9-4aee-ab9b-d95f2d361706.MP4
 
i use (Extra Keys && ExtraKeys Android)

I think Problom In KeyShit

	private function keyShit():Void
	{
	        if(!ClientPrefs.keyboardMode)
		{
		        #if android
		        for (i in 0..._hitbox.array.length) {
			        if (_hitbox.array[i].justPressed)
			        {
				       onKeyPress(new KeyboardEvent(KeyboardEvent.KEY_DOWN, true, true, -1, keysArray[mania][i][0]));
			        }
		        }
		        #end
		}

		// FlxG.watch.addQuick('asdfa', upP);
		if (!boyfriend.stunned && generatedMusic)
		{
			// rewritten inputs???
			notes.forEachAlive(function(daNote:Note)
			{
	                        if(!ClientPrefs.keyboardMode)
		                {
                                        #if android
				        // hold note functions
				        if (daNote.isSustainNote && hitboxDataKeyIsPressed(daNote.noteData)
				        && daNote.canBeHit && daNote.mustPress && !daNote.tooLate 
				        && !daNote.wasGoodHit) {
					       goodNoteHit(daNote);
				        }
                                        #end
                                }
                                else
                                {
				        // hold note functions
				        if (daNote.isSustainNote && dataKeyIsPressed(daNote.noteData)
				        && daNote.canBeHit && daNote.mustPress && !daNote.tooLate 
				        && !daNote.wasGoodHit) {
					       goodNoteHit(daNote);
				        }
                                }
			});
	                if(!ClientPrefs.keyboardMode)
		        {
                                #if android
			        if (hitboxKeysArePressed() && !endingSong) {
				        #if ACHIEVEMENTS_ALLOWED
				        var achieve:String = checkForAchievement(['oversinging']);
				        if (achieve != null) {
					       startAchievement(achieve);
				        }
				        #end
			        }
			} else if (!opponentChart && boyfriend.holdTimer > Conductor.stepCrochet * 0.001 * boyfriend.singDuration && boyfriend.animation.curAnim.name.startsWith('sing')
			&& !boyfriend.animation.curAnim.name.endsWith('miss') || opponentChart && boyfriend.holdTimer > Conductor.stepCrochet * 0.002 
			* boyfriend.singDuration)
				boyfriend.dance();

			 if (opponentChart && dad.holdTimer > Conductor.stepCrochet * 0.001 * dad.singDuration && dad.animation.curAnim.name.startsWith('sing') && !dad.animation.curAnim.name.endsWith('miss'))
			
				dad.dance();
				        //boyfriend.animation.curAnim.finish();
			        }
                                #end
                        }
                        else
                        {
			        if (keysArePressed() && !endingSong) {
				        #if ACHIEVEMENTS_ALLOWED
				        var achieve:String = checkForAchievement(['oversinging']);
				        if (achieve != null) {
					       startAchievement(achieve);
				        }
				        #end
			        
			} else if (!opponentChart && boyfriend.holdTimer > Conductor.stepCrochet * 0.001 * boyfriend.singDuration && boyfriend.animation.curAnim.name.startsWith('sing')
			&& !boyfriend.animation.curAnim.name.endsWith('miss') || opponentChart && boyfriend.holdTimer > Conductor.stepCrochet * 0.002 
			* boyfriend.singDuration)
				boyfriend.dance();

			if (opponentChart && dad.holdTimer > Conductor.stepCrochet * 0.001 * dad.singDuration && dad.animation.curAnim.name.startsWith('sing') && !dad.animation.curAnim.name.endsWith('miss'))
			
				dad.dance();

				        //boyfriend.animation.curAnim.finish();
			        }
                        }
		

          
                  
	        if(!ClientPrefs.keyboardMode)
		{
		        #if android
		        for (i in 0..._hitbox.array.length) {
			        if (_hitbox.array[i].justReleased)
			        {
				       onKeyRelease(new KeyboardEvent(KeyboardEvent.KEY_UP, true, true, -1, keysArray[mania][i][0]));
			        }
		        }
		        #end
		}
	}
idont know where the problem i think its here this only 2 code have dad sing && inCutscene in opponentchart code

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i add to playState opponentchart and i edit GameplayChangersSubstate

**Comment by StefanBETA2008** [comment]
I Can't See The Video.

**Comment by MemeHoovy** [comment]
> I Can't See The Video.

neither can I

**Comment by zeadd21g1233** [comment]
the characters Sing Together in opponent Play Idont know how to fix problom an the video you can download and see it the quality shit my Pc Is Shit
