### ISSUE TITLE
Psych Engine 0.6.2 crashes when editing any event in the Chart Editor

### ISSUE THREAD

**Issue by TheNormalestPeep** [ShadowMario/FNF-PsychEngine#10541]
### Describe your bug here.

In Psych Engine 0.6.2, editing any value of any event causes the game to crash.

### Command Prompt/Terminal logs (if existing)

```bash
editors/ChartingState.hx (line 1469)
flixel/addons/ui/FlxUI.hx (line 164)
flixel/addons/ui/FlxUIInputText.hx (line 46)
flixel/addons/ui/FlxInputText.hx (line 466)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Mastercopper2346** [comment]
Make sure to place the event.

**Comment by KillerAvecRage** [comment]
Exactly, place the event

If you placed the event BUT charted a bit before changing the event: #10511 
Bug in the engine, nothing we can do
