### ISSUE TITLE
MP4 Video Handler

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10547]
### Describe your problem here.

How To Add MP4 Video Handler On Psych Engine?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes

**Comment by TheKitBoi** [comment]
what’s the library for that

**Comment by StefanBETA2008** [comment]
> what’s the library for that

I Think For The Something, But Im Forget

**Comment by MemeHoovy** [comment]
> > what’s the library for that
> 
> I Think For The Something, But Im Forget

hxcodec

**Comment by StefanBETA2008** [comment]
> > > what’s the library for that
> > 
> > 
> > I Think For The Something, But Im Forget
> 
> hxcodec

Yeah
