### ISSUE TITLE
Separate Haxe Scripts? Backdrop maybe?

### ISSUE THREAD

**Issue by YKoF-CALm** [ShadowMario/FNF-PsychEngine#10546]
### Describe your problem here.

I was digging around in the source code for some method to create a pseudo backdrop in Lua when I stumbled upon `runHaxeCode` and `addHaxeLibrary`. Can anyone tell me how to use these? Do I need to put in a separate Haxe file or something, or do I just write it in the script?

Alternatively, if anyone can give me a method of creating a backdrop in Lua, that's also appreciated.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing (except for adding modpacks).

**Comment by MaybeMaru** [comment]
runHaxeCode is a lua function that runs the code you write inside the [[]]
so it would be like
``runHaxeCode([[daCode]])``
add Haxe library allows you to add cool stuff like FLxG, check funkinLua.hx for all the ones you can use

**Comment by CrusherNotDrip** [comment]
> runHaxeCode is a lua function that runs the code you write inside the [[]] so it would be like `runHaxeCode([[daCode]])` add Haxe library allows you to add cool stuff like FLxG, check funkinLua.hx for all the ones you can use

actually for the libraries for the funkinlua.hx part that just puts it in so thats the ones you can use without using `addHaxeLibrary`

**Comment by YKoF-CALm** [comment]
I see, thanks.
Closing this because I managed to force a "backdrop" in Lua lmao.
