### ISSUE TITLE
Icon Shake on a specific song / week / character / etc.

### ISSUE THREAD

**Issue by twizinho** [ShadowMario/FNF-PsychEngine#10555]
### is there a way i can make an icon shake?
if yes, i can make it work with lua or haxe?

[how it works: when the icon is normal, it shakes _a little bit_, when the icon is on the losing state, it shakes _a little bit_ more.]
[[example](https://youtu.be/A9Sx3b9p8qk?t=261).]

**Comment by Shaggers-official** [comment]
The original script is from the vs Ourple Guy mod, i just modified it a bit

function onUpdate(e)
	local angleOfsLose = math.random(-4, 4)
	local angleOfsNormal = math.random(-2, 2)
	if getProperty('healthBar.percent') > 80 then
		setProperty('iconP2.angle', angleOfsLose)--opponent
	else
		setProperty('iconP2.angle', angleOfsNormal)--opponent
	end
end

Is that what you needed ?

**Comment by twizinho** [comment]
> The original script is from the vs Ourple Guy mod, i just modified it a bit
> 
> function onUpdate() local angleOfsLose = math.random(-4, 4) local angleOfsNormal = math.random(-2, 2) if getProperty('healthBar.percent') > 80 then setProperty('iconP2.angle', angleOfsLose)--opponent else setProperty('iconP2.angle', angleOfsNormal)--opponent end end
> 
> Is that what you needed ? (I don't know why the code looks weird lol, i'm new to Github)

yes!!!! holy crap it's perfect! thnk you so much man
