### ISSUE TITLE
color problems/questions

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#10559]
### Describe your problem here.

_**is there any way how to set the color of an object with `setProperty`
I looked at a example but it didn't work**_
(answered)

how to set an object color to white with `doTweenColor()` (or setProperty)

what does _0x_`(hex color)` mean?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No (other than the accuracy 'ratingStuff'), just modded in the "example_mods" folder

**Comment by DisIsNOt** [comment]
You can tween an object's color by  doTweenColor(tag:String, vars:String, targetColor:String, duration:Float, ease:String)

else idk

**Comment by BernardoGP4504** [comment]
```lua
setProperty(getProperty('[the object].color'), '[hex color value here]')
```
change `[the object]`  to the object name
change `[hex color value here]` to the color you want (needs to be hex color code, all caps)

**Comment by frantastic24** [comment]
Why is getProperty there ????

**Comment by BernardoGP4504** [comment]
And by that you're able to use that property anywhere on that file now

Em sáb, 17 de set de 2022 20:17, Bernardo Gameplays E mais 2021 <
***@***.***> escreveu:

**Comment by frantastic24** [comment]
that is not how it works

**Comment by BernardoGP4504** [comment]
It works that way for me atleast

Em sáb, 17 de set de 2022 20:19, frantastic24 ***@***.***>
escreveu:

**Comment by frantastic24** [comment]
You do not need getProperty

**Comment by BernardoGP4504** [comment]
Ok, thanks.

Em sáb, 17 de set de 2022 20:23, frantastic24 ***@***.***>
escreveu:

**Comment by BernardoGP4504** [comment]
To get the color property out of the object

Em sáb, 17 de set de 2022 19:05, frantastic24 ***@***.***>
escreveu:
