### ISSUE TITLE
why custom_events no work

### ISSUE THREAD

**Issue by perngjiafu** [ShadowMario/FNF-PsychEngine#1055]
### Describe your problem here.

when i put the custom events in the folder, it doesnt show up

![image](https://user-images.githubusercontent.com/54176781/141777309-3d73a106-f6c1-4cee-a0f6-79d2e0c6859f.png)

![image](https://user-images.githubusercontent.com/54176781/141777671-aff14316-81fa-4f14-b735-dd60fbeb0cf7.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nop

**Comment by FuseIsHere813** [comment]
Provide your event's code.

**Comment by perngjiafu** [comment]
nvm im dum
