### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#10556]
### What is your question?

what kind of error is this? 
source/PlayState.hx:3580: characters 36-64 : Static access to instance field getPropertyLoopThingWhatever is not allowed
![image](https://user-images.githubusercontent.com/56323671/190529401-2271588c-c5a3-4a72-a8f4-8b381d766c9c.png)
![image](https://user-images.githubusercontent.com/56323671/190529411-c14a3296-eee1-4b77-839a-2339fc83213a.png)
yes i get this has something to do with shaders but this is the first time i have had a code error like this xd

**Comment by DisIsNOt** [comment]
Idk may be add .instance behind or something

**Comment by Grape-Boy** [comment]
wasn't this fixed??
