### ISSUE TITLE
How do i add a attack pose for the oppent so bf can doge

### ISSUE THREAD

**Issue by Imatriceratops** [ShadowMario/FNF-PsychEngine#10553]
### Describe your problem here.

So I'm trying to make an attack animation so bf can dodge the fire but I have no idea how to do that and google cant help at all

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no i dont have a lua scrpit

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#characterplayanimcharacterstring-animstring-forcedbool--false

**Comment by Imatriceratops** [comment]
ok what do i do now wich one do i use

**Comment by frantastic24** [comment]
Probably the one the link takes you to, which literally says play animation

**Comment by DisIsNOt** [comment]
Just play the opponent's animation and time bf's dodge animation to play

**Comment by BernardoGP4504** [comment]
i think what you should do is first play the animation on the opponent then use an if statement to detect if the opponent played that animation and if yes then it runs a timer for a certain time bf has to dodge and then detect if the player pressed the spacebar after the timer and if yes it plays the dodge animation on bf but if else then the hit animation plays on bf and bf's health goes down
