### ISSUE TITLE
Camera Movement 

### ISSUE THREAD

**Issue by ghost** [ShadowMario/FNF-PsychEngine#10551]
### What is your question?

Can You Give Me Code Or Line For The Camera Movement?

Reason: I Want To Add To My Engine.

**Comment by StefanBETA2008** [comment]
If You Wanna Say On Lua, Don't Give Me It. I Just Trying To Source

**Comment by zeadd21g1233** [comment]
Its Too Easy Go to Song.hx

go below 
var vaildscore:Bool;
add
var cameraMoveOnNotes:Bool;

and go below class song

below 
public  var needsVoices:Bool = true;
add
public var cameraMoveOnNotes:Bool = false;

Now Go To PlayState

If Want Dad Cam Movement go 

below

function opponentNoteHit(note:Note):Void

below
                       var char:Character = dad;
                        var animToPlay:String = 'sing' + Note.keysShit.get(mania).get('anims')[note.noteData] + altAnim; (idk i use Extra Keys Version)
			if(note.gfNote) {
				char = gf;
			}

add

			if (SONG.cameraMoveOnNotes) {
				if(SONG.notes[Math.floor(curStep / 16)].mustHitSection == false && !note.isSustainNote)
					{
						if (!dad.stunned)
							{
								switch(Std.int(Math.abs(note.noteData)))
								{
                                                                        //dad
									case 0:
										camFollow.set(dad.getMidpoint().x + 150, dad.getMidpoint().y - 100);
										camFollow.x += dad.cameraPosition[0] - cameramovingoffset; camFollow.y += dad.cameraPosition[1];
									case 1:
										camFollow.set(dad.getMidpoint().x + 150, dad.getMidpoint().y - 100);
										camFollow.x += dad.cameraPosition[0]; camFollow.y += dad.cameraPosition[1] + cameramovingoffset;
									case 2:
										camFollow.set(dad.getMidpoint().x + 150, dad.getMidpoint().y - 100);
										camFollow.x += dad.cameraPosition[0]; camFollow.y += dad.cameraPosition[1] - cameramovingoffset;
									case 3:							
										camFollow.set(dad.getMidpoint().x + 150, dad.getMidpoint().y - 100);
										camFollow.x += dad.cameraPosition[0] + cameramovingoffset; camFollow.y += dad.cameraPosition[1];
									case 4:
										camFollow.set(dad.getMidpoint().x + 150, dad.getMidpoint().y - 100);
										camFollow.x += dad.cameraPosition[0] + cameramovingoffset; camFollow.y += dad.cameraPosition[1];
									case 5:
										camFollow.set(dad.getMidpoint().x + 150, dad.getMidpoint().y - 100);
										camFollow.x += dad.cameraPosition[0] + cameramovingoffset; camFollow.y += dad.cameraPosition[1];
									case 6:
										camFollow.set(dad.getMidpoint().x + 150, dad.getMidpoint().y - 100);
										camFollow.x += dad.cameraPosition[0] + cameramovingoffset; camFollow.y += dad.cameraPosition[1];
									case 7:							
										camFollow.set(dad.getMidpoint().x + 150, dad.getMidpoint().y - 100);
										camFollow.x += dad.cameraPosition[0] + cameramovingoffset; camFollow.y += dad.cameraPosition[1];
									case 8:							
										camFollow.set(dad.getMidpoint().x + 150, dad.getMidpoint().y - 100);
										camFollow.x += dad.cameraPosition[0] + cameramovingoffset; camFollow.y += dad.cameraPosition[1];
									case 9:							
										camFollow.set(dad.getMidpoint().x + 150, dad.getMidpoint().y - 100);
										camFollow.x += dad.cameraPosition[0] + cameramovingoffset; camFollow.y += dad.cameraPosition[1];
									case 10:							
										camFollow.set(dad.getMidpoint().x + 150, dad.getMidpoint().y - 100);
										camFollow.x += dad.cameraPosition[0] + cameramovingoffset; camFollow.y += dad.cameraPosition[1];
                                                                        //BF
									case 11:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 12:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 13:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 14:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 15:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 16:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 17:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 18:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 19:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 20:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 21:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
								}                   
							}
					} 
			}

and go to

function goodNoteHit(note:Note):Void

below

			if (ClientPrefs.hitsoundVolume > 0 && !note.hitsoundDisabled)
			{
				FlxG.sound.play(Paths.sound('hitsound'), ClientPrefs.hitsoundVolume);
			}
add
			if (SONG.cameraMoveOnNotes) {
				if(SONG.notes[Math.floor(curStep / 16)].mustHitSection == false && !note.isSustainNote)
					{
						if (!boyfriend.stunned)
							{
								switch(Std.int(Math.abs(note.noteData)))
								{
                                                                        // You can Edit offset or the Keys (Remember I Use Extra Keys Just Make it To Your Game Keys Nember is 7 dad Keys is end at 3 And Bf End at 7)
                                                                        //BF
									case 11:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 12:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 13:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 14:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 15:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 16:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 17:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] + cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 18:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] - cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 19:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] - cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 20:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] - cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
									case 21:							
										camFollow.set(boyfriend.getMidpoint().x + 150, boyfriend.getMidpoint().y - 100);
										camFollow.x += boyfriend.cameraPosition[0] - cameramovingoffset; camFollow.y += boyfriend.cameraPosition[1];
								}                   
							}
					} 
			}

And Now Go To Charting State

below 
needsVoices: true,
add 
cameraMoveOnNotes: false,

Add This At  

var clear_events:FlxButton = new FlxButton(320, 310, 'Clear events', function()

Lines that add Buttons


                var check_cameraMove = new FlxUICheckBox(300, loadEventJson.y+170, null, null, "Move Camera on Note Hits", 100);
		check_cameraMove.checked = _song.cameraMoveOnNotes;
		check_cameraMove.callback = function()
		{
			_song.cameraMoveOnNotes = check_cameraMove.checked;
		};
go to 
private function saveEvents()

Below Any Value Line

add
cameraMoveOnNotes: _song.cameraMoveOnNotes,

This is Wirdest Tutorial

**Comment by zeadd21g1233** [comment]
This Will add Key In Chart Editor Named CameraMove i think This Code Form Engine I dont Remember there Name
I add That in my Engine
