### ISSUE TITLE
Lua shader

### ISSUE THREAD

**Issue by joxu13v** [ShadowMario/FNF-PsychEngine#10558]
### Describe your problem here.

How can I add a .frag format shader to a stage using .lua, can someone tell me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Duplicate of #10251

**Comment by DisIsNOt** [comment]
setSpriteShader() yes

**Comment by frantastic24** [comment]
setCameraShader isn't a thing

**Comment by joxu13v** [comment]
> setCameraShader isn't a thing 

but without that it doesn't work either

**Comment by frantastic24** [comment]
Your object is wrong, the shader is wrong, shader doesn't exist or your version doesn't support shaders
