### ISSUE TITLE
FNF psych engine video cutscene's not working (latest version and no source code)

### ISSUE THREAD

**Issue by StablerMarmot7** [ShadowMario/FNF-PsychEngine#10554]
### Describe your bug here.

I'm working on a fnf mod on psych engine 0.6.2 with no source code. I wanted to add a cutscene on the week. But the cutscene script is just not working. I looked on the mods/data/script folder and the mods/video folder to see if i'm messed up something. And there was nothing wrong. The video was mp4 and the resolution was correct (1280 x 720).  Everything looks fine, but entering the game week just crashed, I looked on the internet and see if i'm missing something. There was nothing wrong which i don't know know what to do anymore. Does anyone knows what is happening or is it because my windows can't handle it because i'm using a laptop.

And here the lua script and please let me know if i missed something or is this is just a bug:

local allowCountdown = false
function onStartCountdown()
	if not allowCountdown and isStoryMode and not seenCutscene then --Block the first countdown
		startVideo('cutscene1');
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

### Command Prompt/Terminal logs (if existing)

```bash
https://user-images.githubusercontent.com/95502580/190488703-03d83703-e87f-4437-a4a0-cf2ef9cf03bf.png
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Not a bug
Missing gf texture

**Comment by StablerMarmot7** [comment]
there was no missing gf texture

**Comment by frantastic24** [comment]
It's what your error says so

**Comment by StablerMarmot7** [comment]
i didn't see any errror that says missing gf

**Comment by frantastic24** [comment]
It's literally in the crash log you posted my guy

**Comment by StablerMarmot7** [comment]
well i checked on it like 3 times, there was no error says missing and the gf in the game was fine. I even tried put the cutscene by installing another 0.6.2 engine and it still crashed

**Comment by DisIsNOt** [comment]
May be it's missing gf animation? Idk
