### ISSUE TITLE
Not an issue, don't know where to put this

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#1056]
### What is your question?

Can someone make me an event that affects arrow alpha?
These are the value I want:
Value 1: how long it will last
Value 2: transparency

I'm not too good at coding.

### Are you modding a build from source or with Lua?

Lua

**Comment by ItsCapp** [comment]
already done, https://github.com/ShadowMario/FNF-PsychEngine/discussions/893
It is a moving arrows custom event that I made, but if you want to mess with transparency don't do anything with the moving arrow stuff

**Comment by ShadowMario** [comment]
This isn't the place for asking for people to code stuff to you specifically.
