### ISSUE TITLE
"Push back" time bar

### ISSUE THREAD

**Issue by DaInfLoop** [ShadowMario/FNF-PsychEngine#10567]
### Describe your problem here.

I want to be able to set a "fake song end time" so when a certain event happens in the song, it sets it to the song's actual length.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

I've added songs, characters and 2 weeks. No source code edits though.

**Comment by frantastic24** [comment]
#8299

**Comment by DaInfLoop** [comment]
thanks!
