### ISSUE TITLE
Character editor isn't working

### ISSUE THREAD

**Issue by OhWow-IDontCare** [ShadowMario/FNF-PsychEngine#10565]
### Describe your problem here.

Whenever I put in my sprite sheet in the character editor, and put in the animation name it just stays on one idle frame.

https://user-images.githubusercontent.com/113413512/190841100-e3787d13-a740-4ec8-b551-0b5681d2d99f.mp4

And yes, I have double-checked the XML file.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by DisIsNOt** [comment]
copy the anim code from the .xml file for example , "gfDance0000"

**Comment by Mastercopper2346** [comment]
Make sure it’s the EXACT same on on the xml

**Comment by OhWow-IDontCare** [comment]
Thanks a lot for helping, it worked!
