### ISSUE TITLE
Make score text say "HP: 20 - amount of misses"

### ISSUE THREAD

**Issue by luigiman0** [ShadowMario/FNF-PsychEngine#10562]
### What is your question?

I'm trying to make an HP mechanic, where the score text says "HP: (20 subtracted by number of misses)", when it reaches 0, you die. 

I've already made the death part, now I'm trying to do the score text part. Does anyone know how to do this?

**Comment by DisIsNOt** [comment]
```ruby
thing = getProperty('misses')
makeLuaText('e', 'HP: (20 * '..thing, 0, 0, 0)

```

idk

**Comment by Mastercopper2346** [comment]
```lua
function onCreatePost()
     thing = getProperty('misses')
     makeLuaText('e', 'HP: (20 - '..thing, 0, 0, 0)
end
 ```

**Comment by Lorekeeper49** [comment]
```lua
function onUpdate()
     local thing = getProperty('misses')
     makeLuaText('e', 'HP: (20 - '..thing, 0, 0, 0)
end
```

**Comment by Parsellol** [comment]
do u mean something like this?

```lua
local hp = 20

function onUpdate()
    setProperty("scoreTxt.text", "HP: " ..hp - misses)
end
```

**Comment by DisIsNOt** [comment]
May be

**Comment by luigiman0** [comment]
To add on to this, basically I'm trying to change the score text to display the amount of HP rather than anything else. I've tried these other scripts but they aren't appearing to do anything.
