### ISSUE TITLE
Window Title

### ISSUE THREAD

**Issue by DisIsNOt** [ShadowMario/FNF-PsychEngine#10564]
### What is your question?

How can I change the windows title by Source ?

**Comment by MemeHoovy** [comment]
> ### What is your question?
> How can I change the windows title by Source ?

project.xml

**Comment by CrusherNotDrip** [comment]
Edit Project.xml
or unless you wanna change it when you do a certain thing then use Application.current.window.title = "whatever the fuck youwa nt";

**Comment by DisIsNOt** [comment]
Ik project xml but I wanna change the title when I enter a certain State

**Comment by CrusherNotDrip** [comment]
> Ik project xml but I wanna change the title when I enter a certain State, is it possible?

I just said "or unless you wanna change it when you do a certain thing then use Application.current.window.title = "whatever the fuck youwa nt";"

**Comment by DisIsNOt** [comment]
Of sry I didn't notice lmao I'll test that later

**Comment by DisIsNOt** [comment]
it works thanks!
