### ISSUE TITLE
Pixel .lua sprites looking blurry

### ISSUE THREAD

**Issue by MaxGamex485** [ShadowMario/FNF-PsychEngine#10561]
### What is your question?

My pixel sprites look blurry when I upscale them and I don't know if there's any anti-aliasing function in lua. My character sprites don't look blurry 'cause in the character editor there is an anti-alliasing function, so please help me if there's any way to put anti-aliasing to my .lua objects or any other methot to make them not look blurry (also if there's any misspelling is because my English is bad.)
![Sin título](https://user-images.githubusercontent.com/97711205/190833179-89cd0455-78e2-45bf-b68c-75faf46ea3fe.png)

**Comment by MaxGamex485** [comment]
I'm refering to the background

**Comment by CrusherNotDrip** [comment]
setProperty exists

**Comment by MaxGamex485** [comment]
Oh thanks, but I don't know how setProperty works

**Comment by MaxGamex485** [comment]
Forget what I just said, now I know how to use it. Thank you.
