### ISSUE TITLE
Null Object reference when playing certain songs

### ISSUE THREAD

**Issue by ZdzichuOfficialReal** [ShadowMario/FNF-PsychEngine#10566]
### Describe your bug here.

Null Object reference when playing certain songs on PE 6.2

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2469)
PlayState.hx (line 2425)
PlayState.hx (line 1053)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didnt even touch the source code

**Comment by frantastic24** [comment]
Not a bug
Remove dadbattle spotlight

**Comment by BeastlyGhost** [comment]
not a bug

the following events are **hardcoded** to their songs

* Philly Glow (Week 3)
* Dadbattle Spotlight (Week 1)

they CANNOT be used anywhere else
