### ISSUE TITLE
Any way to fix this?

### ISSUE THREAD

**Issue by Among124** [ShadowMario/FNF-PsychEngine#10569]
### Describe your bug here.

Week 1's songs keep appearing even after i deleted it COMPLETELY from the files (Shown below) any way to fix this?
![vvb bcxvxvbxcvb](https://user-images.githubusercontent.com/107786575/190872118-9936f778-a4fa-401a-ac08-2fe35c2b8e7b.png)
![klf jdlfhjkfsgl](https://user-images.githubusercontent.com/107786575/190872122-4f07fbb2-a762-4bfa-81a5-2bc2634e9d7c.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Not a bug
File is probably still present in export

**Comment by Among124** [comment]
Nope i deleted it
![Screenshot 2022-09-17 145639](https://user-images.githubusercontent.com/107786575/190872407-24537d9a-9fe4-465c-8347-2ec0357e1ae9.png)

**Comment by frantastic24** [comment]
Are you doing lime build or test, they use different files, it could also be in mods
Weeks are softcoded so the game can't add something that doesn't exist in _your_ files

**Comment by BernardoGP4504** [comment]
check in the preload folder
if you deleted from there then make sure you have a debug build and delete in there.
if that doesn't do anything try to check the source files because maybe the weeks are hard coded in

**Comment by Among124** [comment]
ok, i just found out that one of the weeks i had added have the default songs bopeebo etc.. so i had to remove the week.
