### ISSUE TITLE
Null Object Reference?

### ISSUE THREAD

**Issue by kidwithagun** [ShadowMario/FNF-PsychEngine#10573]
### Describe your bug here.

I was loading up one of my psych engine modpack that's Tails Gets Trolled and for some reason on 0.6.1, when trying to play No Villians, there was an error that crashes my game. Do you know what happened? If you need any other data I'll post as soon as I can. (Edit: I got 0.6.2 to see if it would work on a newer version but the same error screen popped up)
(Image of the error)
https://user-images.githubusercontent.com/103972070/190881066-bead61bb-68f1-4875-96c3-131a2c20c38b.jpg

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I never touched the source code, this was all done through the mods folder

**Comment by KillerAvecRage** [comment]
You are missing one or multiple files, this is often the reason of Null Object Reference

**Comment by kidwithagun** [comment]
You were right. I was missing a custom note asset and deleted it from the JSON and the song's working. Thank you!
