### ISSUE TITLE
Is there a way to play a song when you press 7 in lua

### ISSUE THREAD

**Issue by rexythegamer2002** [ShadowMario/FNF-PsychEngine#10575]
### Describe your problem here.

Is it possible to play a song with lua when pressed 7 or any number like dave and bambi

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
There are so many posts like this already
Use the search feature

**Comment by ImaginationSuperHero528** [comment]
Just go to official psych engine discord server

**Comment by Parsellol** [comment]
next time use the search feature
#10439
if the script dosent work just remove the ", 2" on loadSong or something

**Comment by GWEjbik** [comment]
> next time use the search feature #10439 if the script dosent work just remove the ", 2" on loadSong or something

It doesn't work
It just disables the chart editor (Psych v0.6.2)

**Comment by MemeHoovy** [comment]
> Did u even try this (made by parsellol https://github.com/Parsellol)
> 
> ```lua
> function onCreate()
>      setProperty("debugKeysChart", null)
> end
> 
> function onUpdate()
>      if keyboardJustPressed("SEVEN") then
>          loadSong("bopeebo", 2)
>      end
> end
> ```
`
function onCreate()
     setProperty("debugKeysChart", nil)
end

function onUpdate()
     if keyboardJustPressed("SEVEN") then
         loadSong("bopeebo", 2)
     end
end
`

**Comment by GWEjbik** [comment]
> > Did u even try this (made by parsellol https://github.com/Parsellol)
> > ```lua
> > function onCreate()
> >      setProperty("debugKeysChart", null)
> > end
> > 
> > function onUpdate()
> >      if keyboardJustPressed("SEVEN") then
> >          loadSong("bopeebo", 2)
> >      end
> > end
> > ```
> 
> actually null should be nil, since that's the lua equivalent of null
> 
> ```
> function onCreate()
>      setProperty("debugKeysChart", nil)
> end
> 
> function onUpdate()
>      if keyboardJustPressed("SEVEN") then
>          loadSong("bopeebo", 2)
>      end
> end
> ```

It won't work
I tried it and it only prevents you from getting into the chart editor
It won't play a song

**Comment by Parsellol** [comment]
> > > Did u even try this (made by parsellol https://github.com/Parsellol)
> > > ```lua
> > > function onCreate()
> > >      setProperty("debugKeysChart", null)
> > > end
> > > 
> > > function onUpdate()
> > >      if keyboardJustPressed("SEVEN") then
> > >          loadSong("bopeebo", 2)
> > >      end
> > > end
> > > ```
> > 
> > 
> > actually null should be nil, since that's the lua equivalent of null
> > ```
> > function onCreate()
> >      setProperty("debugKeysChart", nil)
> > end
> > 
> > function onUpdate()
> >      if keyboardJustPressed("SEVEN") then
> >          loadSong("bopeebo", 2)
> >      end
> > end
> > ```
> 
> It won't work I tried it and it only prevents you from getting into the chart editor It won't play a song

it does, believe it or not i test my scripts before posting them.
the number in loadsong is the number of the difficulty (0 = easy, 1 = normal, 2 = hard), which means if it dosent work ur song probably has less than 3 difficulties, which means change the number in loadsong or just remove it or something

**Comment by GWEjbik** [comment]
> > > > Did u even try this (made by parsellol https://github.com/Parsellol)
> > > > ```lua
> > > > function onCreate()
> > > >      setProperty("debugKeysChart", null)
> > > > end
> > > > 
> > > > function onUpdate()
> > > >      if keyboardJustPressed("SEVEN") then
> > > >          loadSong("bopeebo", 2)
> > > >      end
> > > > end
> > > > ```
> > > 
> > > 
> > > actually null should be nil, since that's the lua equivalent of null
> > > ```
> > > function onCreate()
> > >      setProperty("debugKeysChart", nil)
> > > end
> > > 
> > > function onUpdate()
> > >      if keyboardJustPressed("SEVEN") then
> > >          loadSong("bopeebo", 2)
> > >      end
> > > end
> > > ```
> > 
> > 
> > It won't work I tried it and it only prevents you from getting into the chart editor It won't play a song
> 
> it does, believe it or not i test my scripts before posting them. the number in loadsong is the number of the difficulty (0 = easy, 1 = normal, 2 = hard), which means if it dosent work ur song probably has less than 3 difficulties, which means change the number in loadsong or just remove it or something

It works on songs with regular difficulties only.
Is it possible to make it work on custom difficulties?

**Comment by ImaginationSuperHero528** [comment]
> > > > > Did u even try this (made by parsellol https://github.com/Parsellol)
> > > > > ```lua
> > > > > function onCreate()
> > > > >      setProperty("debugKeysChart", null)
> > > > > end
> > > > > 
> > > > > function onUpdate()
> > > > >      if keyboardJustPressed("SEVEN") then
> > > > >          loadSong("bopeebo", 2)
> > > > >      end
> > > > > end
> > > > > ```
> > > > 
> > > > 
> > > > actually null should be nil, since that's the lua equivalent of null
> > > > ```
> > > > function onCreate()
> > > >      setProperty("debugKeysChart", nil)
> > > > end
> > > > 
> > > > function onUpdate()
> > > >      if keyboardJustPressed("SEVEN") then
> > > >          loadSong("bopeebo", 2)
> > > >      end
> > > > end
> > > > ```
> > > 
> > > 
> > > It won't work I tried it and it only prevents you from getting into the chart editor It won't play a song
> > 
> > 
> > it does, believe it or not i test my scripts before posting them. the number in loadsong is the number of the difficulty (0 = easy, 1 = normal, 2 = hard), which means if it dosent work ur song probably has less than 3 difficulties, which means change the number in loadsong or just remove it or something
> 
> It works on songs with regular difficulties only. Is it possible to make it work on custom difficulties?

It works with custom

**Comment by GWEjbik** [comment]
> 

Just tested it again and it turned out that it works
Sorry for trouble
