### ISSUE TITLE
how do you add images to the menu

### ISSUE THREAD

**Issue by uhhhhuhhhhhhokay** [ShadowMario/FNF-PsychEngine#10571]
### Describe your problem here.

i want to add a image to the main menu but i dont know how to, is there like a code or something?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

MainMenuState.hx

**Comment by DisIsNOt** [comment]
make a var 
then

asses = new FlxSprite().loadGraphic(Paths.images('image'));
asses.x += 0;
asses.y += 0;
add(asses);

**Comment by BernardoGP4504** [comment]
make a variable for your sprite:
```haxe
var sprite:FlxSprite;

sprite = new FlxSprite(X, Y).loadGraphic(Paths.image('yourimage'));
add(sprite);
```
- change `X` and `Y` into the coordinates you want your sprite to be
- change `yourimage` to the sprite's graphic
- change the `sprite` variable to be called whatever you want

## For easier movement
```haxe
var sprite:FlxSprite;

sprite = new FlxSprite(0, 0).loadGraphic(Paths.image('yourimage'));
sprite.x += X; //for negative coordinates use -= instead
sprite.y += Y;

add(sprite);
```
- change `X` into the x position you want your sprite to go
- same for the `Y`

**Comment by uhhhhuhhhhhhokay** [comment]
thanks it works :D

**Comment by raxyd** [comment]
yo why does it go off the screen once I scrolled to options

**Comment by BernardoGP4504** [comment]
> yo why does it go off the screen once I scrolled to options

Camera movement
Just do `sprite.scrollFactor.set();`, changing `sprite` to the variable that is your sprite

**Comment by raxyd** [comment]
thanks bro

**Comment by Velikiycho** [comment]
Help please, I'm using psych engine 0.7.3 and getting this error when compiling:
source/states/MainMenuState.hx:232: characters 3-9 : Unexpected sprite

**Comment by BernardoGP4504** [comment]
> Help please, I'm using psych engine 0.7.3 and getting this error when compiling: source/states/MainMenuState.hx:232: characters 3-9 : Unexpected sprite

change `sprite` to your sprite variable
Like if you have a `var overlay:FlxSprite`, for example, and wanted to use that, change it to `overlay.scrollFactor.set();`

**Comment by Velikiycho** [comment]
> > Помогите пожалуйста, я использую Psych Engine 0.7.3 и получаю эту ошибку при компиляции: source/states/MainMenuState.hx:232: символы 3-9 : Неожиданный спрайт
> 
> Измените `sprite`переменную спрайта. Например, если у вас есть `var overlay:FlxSprite`, и вы хотите использовать его, измените его на`overlay.scrollFactor.set();`

It looks like I'm too stupid for this, please write a code example

**Comment by raxyd** [comment]
var sprite:FlxSprite;

sprite = new FlxSprite(0, 0).loadGraphic(Paths.image('yourimage'));
sprite.x += X; //for negative coordinates use -= instead
sprite.y += Y;

sprite.scrollFactor.set();

add(sprite);
