### ISSUE TITLE
Don't know why this keeps happening.

### ISSUE THREAD

**Issue by MandoMandofox** [ShadowMario/FNF-PsychEngine#1057]
### Describe your bug here.

Each time I try to chart a song, the engine keeps crashing. I don't know what keeps causing this, I tried most of what I could but I don't see any sort of solution. As far as I remember, I don't recall doing anything to the .json.

Here's a video a recorded of the bug. https://streamable.com/izwuxt

 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Besides replacing one of the songs with different Inst and Voices, as well as a new .json, No.

**Comment by ShadowMario** [comment]
Run in a debug build then send the console trace...
