### ISSUE TITLE
Null Object reference when trying to load dialogue before a song

### ISSUE THREAD

**Issue by TheJoetube** [ShadowMario/FNF-PsychEngine#10578]
### Describe your bug here.

Whenever a song with dialogue tries to load in the story mode it crashes and gives this error.

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 1548)
PlayState.hx (line 1320)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added a custom week, dialogue, characters, songs, ect...

**Comment by frantastic24** [comment]
Have you edited PlayState, if you have then show the lines mentioned in the error
If not, what version are you using

**Comment by TheJoetube** [comment]
> Have you edited PlayState, if you have then show the lines mentioned in the error
> If not, what version are you using

I  am using 0.6.2

These are the lines it points too
case 'chocolate':
	startDialogue(dialogueJson);

if(dialogueFile.dialogue.length > 0) {
			inCutscene = true;
			precacheList.set('dialogue', 'sound');
			precacheList.set('dialogueClose', 'sound');
			psychDialogue = new DialogueBoxPsych(dialogueFile, song);
			psychDialogue.scrollFactor.set();

**Comment by BernardoGP4504** [comment]
> > Have you edited PlayState, if you have then show the lines mentioned in the error
> > If not, what version are you using
> 
> I am using 0.6.2
> 
> These are the lines it points too case 'chocolate': startDialogue(dialogueJson);
> 
> if(dialogueFile.dialogue.length > 0) { inCutscene = true; precacheList.set('dialogue', 'sound'); precacheList.set('dialogueClose', 'sound'); psychDialogue = new DialogueBoxPsych(dialogueFile, song); psychDialogue.scrollFactor.set();

change `startDialogue(dialogueJson)` to `startDialogue([dialoguefile])`
`[dialoguefile]` is the dialogue file you're going to load

**Comment by TheJoetube** [comment]
> change `startDialogue(dialogueJson)` to `startDialogue([dialoguefile])`
> `[dialoguefile]` is the dialogue file you're going to load

when I do that it gives this error when compiling

source/PlayState.hx:1320: characters 21-33 : Unknown identifier : dialoguefile
source/PlayState.hx:1320: characters 21-33 : ... For function argument 'dialogueFile'

**Comment by BernardoGP4504** [comment]
I said change `[dialogueFile]` to the file name of the dialogue file you
want it to load

Em seg, 19 de set de 2022 07:13, TheJoetube ***@***.***>
escreveu:

**Comment by TheJoetube** [comment]
> I said change [dialogueFile] to the file name of the dialogue file you want it to load

changed it to the file name but it gives more errors

**Comment by BernardoGP4504** [comment]
So i think something is wrong with the dialogue file itself

Em ter, 20 de set de 2022 12:54, TheJoetube ***@***.***>
escreveu:

**Comment by TheJoetube** [comment]
> So i think something is wrong with the dialogue file itself

There is nothing wrong with the dialogue file, since it works when I try the Lua solution to making dialogue play before a song.
Also I should have clarified that it gives errors when compiling, not in game.

**Comment by BernardoGP4504** [comment]
So then I think the variable dialogueFile is returning null or the game is
not finding the file by the haxe method

Em ter, 20 de set de 2022 18:16, TheJoetube ***@***.***>
escreveu:

**Comment by TheJoetube** [comment]
> So then I think the variable dialogueFile is returning null or the game is not finding the file by the haxe method

Is there any way to fix it then?

**Comment by BernardoGP4504** [comment]
I don't know.

Em ter, 20 de set de 2022 19:06, TheJoetube ***@***.***>
escreveu:

**Comment by Mastercopper2346** [comment]
actually, the source version is broken. For now only lua works, I can confirm because I tried with source but to kept giving me a compiler error but with lua it works perfectly

**Comment by TheJoetube** [comment]
> actually, the source version is broken. For now only lua works, I can confirm because I tried with source but to kept giving me a compiler error but with lua it works perfectly

Alright, guess I'll just use Lua until they fix it, thanks
