### ISSUE TITLE
downloading cutscene example doesn't work

### ISSUE THREAD

**Issue by ethaxo99** [ShadowMario/FNF-PsychEngine#10576]
### Describe your bug here.

not sure if this is intentional, but when i try to download the video example in Lua Script Api, it'll say it can't find the page.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by cinnadust** [comment]
they deleted the link

**Comment by ethaxo99** [comment]
why

**Comment by TheKitBoi** [comment]
Try it again with a different browser
