### ISSUE TITLE
Object

### ISSUE THREAD

**Issue by DisIsNOt** [ShadowMario/FNF-PsychEngine#10579]
### Describe your problem here.

How can I detect when a object is a flixel missing texture logo?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nop

**Comment by BernardoGP4504** [comment]
```haxe
if ([object].graphic == null)
{
    //code here
}
```
`[object]` is the object you're trying to detect

**Comment by DisIsNOt** [comment]
Ok thanks my guy

**Comment by BernardoGP4504** [comment]
> How bout Lua?

Idk

**Comment by DisIsNOt** [comment]
nvrm i think i get it
