### ISSUE TITLE
eyesores in lua

### ISSUE THREAD

**Issue by swobodac** [ShadowMario/FNF-PsychEngine#10574]
### What is your question?

do you have a event that can make eyesores like dnb
its for a port

**Comment by Jevilm** [comment]
Theres a dave and bambi port by Gifter's Creations on youtube that has eyesores in lua

**Comment by Jevilm** [comment]
Or try to use random blammed lights idk

**Comment by swobodac** [comment]
1.you cant steal assets from it
2.blammed lights was removed

**Comment by swobodac** [comment]
> ask for permission!!!!!!!!!!

it says this in the trailer
![Screenshot 2022-09-24 144802](https://user-images.githubusercontent.com/98852602/192113984-c68acb20-ab49-4e42-8fc3-4a3eb03fe46c.png)
