### ISSUE TITLE
Game crash when song is long and there is too much events 

### ISSUE THREAD

**Issue by adamsaustria** [ShadowMario/FNF-PsychEngine#10577]
### Describe your bug here.

Game Crashes if a song is too long like triple trouble and yes this on psych engine 0.6.2 it has nothing to do with lag

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

NO

**Comment by KillerAvecRage** [comment]
Lower your FPS to 60

**Comment by adamsaustria** [comment]
My fps is already at 60

**Comment by adamsaustria** [comment]
@ShadowMario can you pls fix this
