### ISSUE TITLE
How to flip the health bar?

### ISSUE THREAD

**Issue by DacroyleYT** [ShadowMario/FNF-PsychEngine#10584]
### Describe your problem here.

Is there any way I can make the health bar flipped? In other words, where the player's icon is on the left and opponent's icon on the right? If so, tell me. Thanks!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
duplicate, use the search feature before opening an issue #10100
