### ISSUE TITLE
animated sprite not bopping head to beat

### ISSUE THREAD

**Issue by Aidenkp112** [ShadowMario/FNF-PsychEngine#10587]
### Describe your problem here.

so im back from the dead i guess
this time stage problem!!! (woo this guy stinks)
first problem solved so next

sprite is there now! yipee. problem: he doesnt go along with the beat

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

tried changing the sprite position didnt help tho

**Comment by frantastic24** [comment]
Wrong object tag
It's called sen, not beach_senator

**Comment by Aidenkp112** [comment]
im a idiot ngl

**Comment by Aidenkp112** [comment]
still cant find the sprite
i see it nowhere

**Comment by Aidenkp112** [comment]
nvm hes there now

**Comment by frantastic24** [comment]
Close it

**Comment by Aidenkp112** [comment]
i got a new problem

**Comment by Aidenkp112** [comment]
head bop to beat = no
so yipee
i'll close it after this

**Comment by frantastic24** [comment]
You didn't even show the script
It's probably also using the wrong tag

**Comment by Aidenkp112** [comment]
makeAnimatedLuaSprite('sen', 'beach/beach_senator', 0, 0);
        addAnimationByPrefix('sen', 'sen bop', 'sen bop', 16, true);
        objectPlayAnimation('sen', 'sen bop', true);
        setScrollFactor('sen', 1, 1);

	end

    addLuaSprite('beach/beach_sky', false);
    addLuaSprite('beach/stand', false);
    addLuaSprite('beach/beach_umbrella', false);
    addLuaSprite('sen', true);

    setObjectOrder('beach/beach_sky', 0);
    setObjectOrder('beach/beach_sand', 2);
    setObjectOrder('beach/beach_umbrella', 1);
    setObjectOrder('sen', 3);

**Comment by Aidenkp112** [comment]
thats the fixed
idk how to fix bop

**Comment by frantastic24** [comment]
Is that the entire thing? There's no code telling it to play the animation on beat

**Comment by Aidenkp112** [comment]
yeah thats the entire code nothing above

**Comment by frantastic24** [comment]
Cool you got your answer then

**Comment by Aidenkp112** [comment]
i still need it to play on the beat
i guess i'll go scavenger hunting

**Comment by frantastic24** [comment]
Read the wiki, it has template scripts
