### ISSUE TITLE
Type not found : FlxGraphic

### ISSUE THREAD

**Issue by bloxee** [ShadowMario/FNF-PsychEngine#10588]
### Describe your problem here.

So I'm trying to compile a mod to HTML5 however I'm greeted with "source/Paths.hx:318: characters 53-63 : Type not found : FlxGraphic".

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5/Browser

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Aidenkp112** [comment]
i haven't used source code yet but im gonna guess something like a character file is missing

**Comment by ShadowMario** [comment]
Fixed HTML5 issues again
