### ISSUE TITLE
plz help i cannot do it

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#10582]
### Describe your problem here.

I'm trying to detect if the item in `FreeplayState.hx` is the curSelected one but i don't know how to do it
![helpme](https://user-images.githubusercontent.com/101405920/190916879-095965a9-cc5a-4eb2-8582-69a538fcd93f.png)
plz help me

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, MainMenuState.hx, Paths.hx, CreditsState.hx, FreeplayState.hx, StoryMenuState.hx, etc.

**Comment by kingyomoma** [comment]
you are checking if a number is equal to a `SongMetadata` object

**Comment by BernardoGP4504** [comment]
> you are checking if a number is equal to a `SongMetadata` object

yeah ik but how can i detect it right?
