### ISSUE TITLE
HELP ME PLEASE

### ISSUE THREAD

**Issue by TonyRonii** [ShadowMario/FNF-PsychEngine#1058]
### Describe your problem here.

IM WORKING ON MY FRIENDS MOD AND EVERYTIME I INPUT A NOTE CLICK OR KEYBOARD PRESS IT CRASHES WHAT DO I DO PLEASE HELP

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I editied a lot of things today Playstate, Achiements, Credits, AchiementsMenuState and some image assets

**Comment by Steviegt6** [comment]
We can't see your code, how do you expect us to help you?

**Comment by TonyRonii** [comment]
send the whole playstate code?

**Comment by Steviegt6** [comment]
> send the whole playstate code?

It'd be nicer if you could create a diff between all modified code (i.e. publishing your code to GitHub).

**Comment by ShadowMario** [comment]
Sounds like a duplicate of #343 
Plus no replies since 2 days so i will suppose OP fixed it.
