### ISSUE TITLE
FunkinLua.hx issue

### ISSUE THREAD

**Issue by hakerethangithub** [ShadowMario/FNF-PsychEngine#10589]
### Describe your problem here.

Hello, I was trying to build psych engine using the visual studio code terminal, but I encountered an error upon running the command "lime test windows".

![image](https://user-images.githubusercontent.com/100083373/191029108-e24eaeb7-c26d-4c4f-b45d-6703483b3873.png)

I have little to no experience in haxe, so I cannot pinpoint the exact issue here. Any help would be **greatly** appreciated, thanks.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, just tried to build the base engine found off of github.

**Comment by hakerethangithub** [comment]
update: older versions seem to work, so this issue must have been due to the lua tweaks in 0.6.1

**Comment by Mastercopper2346** [comment]
> update: older versions seem to work, so this issue must have been due to the lua tweaks in 0.6.1

What no lol

**Comment by Mastercopper2346** [comment]
> > update: older versions seem to work, so this issue must have been due to the lua tweaks in 0.6.1
> 
> What no lol

Install the new luajit (whatever it’s called)

**Comment by hakerethangithub** [comment]
> > > update: older versions seem to work, so this issue must have been due to the lua tweaks in 0.6.1
> > 
> > 
> > What no lol
> 
> Install the new luajit (whatever it’s called)

done, my issue still persists.
