### ISSUE TITLE
Game keeps crashing

### ISSUE THREAD

**Issue by Ziro35** [ShadowMario/FNF-PsychEngine#10599]
### Describe your bug here.

After I recently edited the files on the engine the game doesn't seem to load anymore

### Command Prompt/Terminal logs (if existing)

```bash
flixel/animation/FlxAnimationController.hx (line 710)
TitleState.hx (line 357)
TitleState.hx (line 227)
flixel/util/FlxTimer.hx (line 195)
flixel/util/FlxTimer.hx (line 285)
flixel/FlxGame.hx (line 745)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i only added files from other mods l

**Comment by frantastic24** [comment]
did you delete titleEnter or replace it?
