### ISSUE TITLE
Game keeps crashing for no reason

### ISSUE THREAD

**Issue by Jevilm** [ShadowMario/FNF-PsychEngine#10591]
### Describe your bug here.

the game keeps crashing for no reason, it doesnt give me an error or anything, the game freezes :[

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Edited UI thingy idk

**Comment by TFLTV** [comment]
> the game keeps crashing for no reason, it doesnt give me an error or anything, the game freezes :[

has there been patterns with it crashing

**Comment by Jevilm** [comment]
no

> > the game keeps crashing for no reason, it doesnt give me an error or anything, the game freezes :[
> 
> has there been patterns with it crashing

no

**Comment by KillerAvecRage** [comment]
Try without your edits, if it still crashes, then check your mods
