### ISSUE TITLE
Adding Version To FOS Like From The Leather Engine.

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10594]
### Describe your problem here.

`source/openfl/display/FPS.hx:80: characters 16-22 : Class<ClientPrefs> has no field showSB
source/openfl/display/FPS.hx:80: characters 85-93 : String has no field endsWith
source/openfl/display/FPS.hx:80: characters 135-142 : String has no field replace
source/openfl/display/FPS.hx:81: characters 20-33 : Class<MainMenuState> has no field versionSuffix`

I Just Want To Add The Version To FPS Style, But I Can't. I Will Try To Fix It

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I Edited FPS.hx To Look Like Leather Engine.

**Comment by StefanBETA2008** [comment]
source/openfl/display/FPS.hx:80: characters 52-84 : String cannot be called
source/openfl/display/FPS.hx:80: characters 174-176 : String should be Void

I Got Again Error

**Comment by StefanBETA2008** [comment]
source/openfl/display/FPS.hx:80: characters 48-80 : String should be UInt
source/openfl/display/FPS.hx:80: characters 48-80 : ... For function argument 'num'

Help Me Guys

**Comment by StefanBETA2008** [comment]
Please

**Comment by nennneko5787** [comment]
Add the following code to line 92 of FPS.hx
<pre>
text += "\nPsychEngine v0.6.2";
</pre>

**Comment by Jevilm** [comment]
bro just take leather engine source code

**Comment by nennneko5787** [comment]
It seems that the following code can also be used (although I have not tried it)
<pre>
text += "PsychEngine v "+ MainMenuState.PsychEngineVersion;
</pre>
