### ISSUE TITLE
question about opening a file with Lua.

### ISSUE THREAD

**Issue by twizinho** [ShadowMario/FNF-PsychEngine#10590]
### What is your question?

one of my friends is making a mod where it's a compilation of Sonic.exe songs, such as Fatality, Round-a-bout, etc.
and he asked me a question, and i had **no clue** how to do it, so, i'm asking here.

can I open a .exe file with Lua?

**Comment by ManMaster707** [comment]
os.execute('nameoftheexefilehere')

**Comment by LeefLett** [comment]
Is os.execute usable again?

**Comment by MemeHoovy** [comment]
> Is os.execute usable again?

apparently so in newer versions

**Comment by LeefLett** [comment]
cool!
