### ISSUE TITLE
Custom Variables for Lua Scripts

### ISSUE THREAD

**Issue by Abe57** [ShadowMario/FNF-PsychEngine#10595]
[me asking for global variables, which already exist here]

**Comment by MaybeMaru** [comment]
global variables are a thing

**Comment by Abe57** [comment]
> global variables are a thing

fr how???

**Comment by Gostar64** [comment]
don't have "local" before the variable and use getGlobalFromScript
I suggest going into the code part on github and going into FunkinLua.hx to see how getGlobalFromScript works

**Comment by Abe57** [comment]
> don't have "local" before the variable and use getGlobalFromScript I suggest going into the code part on github and going into FunkinLua.hx to see how getGlobalFromScript works

thanks ig, gonna delete this now maybe
