### ISSUE TITLE
Video Plays On Death

### ISSUE THREAD

**Issue by Username2120** [ShadowMario/FNF-PsychEngine#10598]
### Describe your problem here.

Is there a way to make a video play on death instead of the normal death animation? Lua or source idc I'm working with both.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited PlayState.hx, TitleState.hx, StoryMenuState.hx, MainMenuState.hx, and FreeplayState.hx. mostly menu stuff.

**Comment by Chidubemmo** [comment]
In GameOverSubstate.hx replace `boyfriend.playAnim('first-death');` with
```haxe
video.playCutscene('cutscenename');
```

**Comment by Username2120** [comment]
Do you know how to make it only happen on one song?
