### ISSUE TITLE
How do you put dialogue before cutscene at the end of the song? (lua)

### ISSUE THREAD

**Issue by StablerMarmot7** [ShadowMario/FNF-PsychEngine#10606]
### What is your question?

I want to make a dialogue at the end + a ending which it is a ending credits

But i don't know how to do it. I tried to look on the internet but i never found it. It just keeps saying How do i put dialogue after cutscene

Can someone please help me with that?

**Comment by Lupingllogi111** [comment]
I guess you have to take the example script in this wiki and change the function to onEndSong()

**Comment by StablerMarmot7** [comment]
It didn't work. It just goes the opposite way
