### ISSUE TITLE
How can I tween/edit a value in a shader?

### ISSUE THREAD

**Issue by EgguMan** [ShadowMario/FNF-PsychEngine#10609]
### Describe your problem here.

hello, I am using a blur shader, but, I do not know how to tween the Size value of it (controls how blurred it is)

can someone help me out?

code below, the shader is applied to camGame

![image](https://user-images.githubusercontent.com/100107293/191624743-1bc3dbc8-7a12-4ebe-94f5-10bd1d895b40.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited playstate to give camGame a shaderFilter and created BlurShader.hx

**Comment by UncertainProd** [comment]
You can use shader uniforms to externally provide inputs to a shader. Just add the line
```glsl
uniform float Size;
```
into your shader, above mainImage(), then in the haxe code, you can control it with
```haxe
yourShaderObject.data.Size.value = [ (some-float-value) ];
```

**Comment by EgguMan** [comment]
Oh, thank you so much!!

Do you think I can tween it with

FlxTween.tween(camGame.data.Size, {value: [0.0]},0.1);

or would the brackets mess with it.

Apologies for bad formatting, I am on mobile

**Comment by EgguMan** [comment]
> 



> You can use shader uniforms to externally provide inputs to a shader. Just add the line
> 
> ```glsl
> uniform float Size;
> ```
> 
> into your shader, above mainImage(), then in the haxe code, you can control it with
> 
> ```hx
> yourShaderObject.data.Size.value = [ (some-float-value) ];
> ```

so, I did this, but its giving me the error below (yes, I know the variable is not the same.)
![image](https://user-images.githubusercontent.com/100107293/192163428-6bfd260d-a468-48c1-8d4d-dbb30291cb51.png)
I tried it with camGame, but, it did the same

**Comment by UncertainProd** [comment]
I think you used the class directly instead of an object of that class, it should look something like:
```haxe
var myshader = new IntenseShadere();
// set the uniforms and stuff
camGame.setFilters([ new ShaderFilter(myshader) ]);
```
