### ISSUE TITLE
How to make player sprites go behind opponent?

### ISSUE THREAD

**Issue by BoxOfGolds** [ShadowMario/FNF-PsychEngine#10612]
### Describe your problem here.

Hi! 

Is there any kind of Lua script I can use to make the player character go behind the opponent for a single song?

 I don't really know any code so if anyone can help me out, I'll be extremely grateful.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#object-orderremoving

**Comment by BoxOfGolds** [comment]
forgot to close this but I got it. Thank you so much for helping me!
