### ISSUE TITLE
Disable default camera beats

### ISSUE THREAD

**Issue by ArthurYago** [ShadowMario/FNF-PsychEngine#10618]
### Describe your problem here.

I want to disable the camera beat zooms, that happens when i the game hits a beat.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Jevilm** [comment]
its in options idiot

**Comment by ManMaster707** [comment]
> 

i think he means disabling it mid-song

**Comment by ManMaster707** [comment]
btw this should work: `setProperty('camZooming', false)`

**Comment by ArthurYago** [comment]
i found a variable that maybe can work, thank you guys anyways

**Comment by ArthurYago** [comment]
I think none of them worked, i just wanna make custom beats, that's why i wan't to disable the default ones
