### ISSUE TITLE
How can i make a main menu like in twinsomnia

### ISSUE THREAD

**Issue by RubenDatOneBoi3446** [ShadowMario/FNF-PsychEngine#10614]
### Describe your problem here.

I want to add a scrolling bg in the main menu with a panel like twinsomnia bur i dont know shish about source code can someone help me?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Chidubemmo** [comment]
I only know to make the menu characters
This's some code made with ETI's tutorials which aren't availible anymore for whatever reason, luckily they made a [github project](https://github.com/real-jaco0bb/PE-tutorials) they are for 0.4.2 and above as long ShadowMario doesn't anything important.
Add in MainMenuState.hx this variable
```
var char:FlxSprite;
```
Then below super create();
```haxe
		switch (FlxG.random.int(1, number of characters)) //You can change it with any number if there are more
		{
		case 1:
			char = new FlxSprite(X, Y).loadGraphic(Paths.image('mainmenu/pngName'));//Thanks to EIT for the tutorial
			char.frames = Paths.getSparrowAtlas('mainmenu/char1');
			char.animation.addByPrefix('a name for the animation', 'animation on xml', framerate, true); //the bool value's for deciding if it loops or not
			char.animation.play('a name for the animation');
			char.scrollFactor.set();
			char.flipX = false; //You should have already animated it in the right position in Animate
			char.antialiasing =ClientPrefs.globalAntialiasing;
			FlxG.sound.play(Paths.sound('sound'), 2); //optional
			add(char);
		}
```
You later just copypaste it and modify it how many times you want

**Comment by RubenDatOneBoi3446** [comment]
THANK U
