### ISSUE TITLE
Custom Note Being Weird

### ISSUE THREAD

**Issue by smisanasshole** [ShadowMario/FNF-PsychEngine#10610]
### Describe your problem here.

So I took this code directly from another mod I'm making and it works fine in that other mod but for some reason it doesn't work in the mod I just put it in.

Both the mods use the latest version of Psych Engine so I have no idea why the hell it's not working.

`function onCreate()`
`	for i = 0, getProperty('unspawnNotes.length')-1 do`
`		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Instakill Note' then`
`			setPropertyFromGroup('unspawnNotes', i, 'texture', 'dead-note');`
`			--setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'dead-splash');`
`			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then`
`				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true);`
`			end`
`		end`
`	end`
`	--debugPrint('Script started!')`
`end`
`function goodNoteHit(id, noteData, noteType, isSustainNote)`
`	if noteType == 'Instakill Note' then`
`		setProperty('health', -500);`
`	end`
`end`

For some reason the textures don't display and the code that makes it kill you when you hit it works but for some reason it gives you a miss whenever you miss it.

Like I said it works fine in the other mod so like I really have no idea what's happening.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, the source code has not been messed with any way.

**Comment by cinnadust** [comment]
copy the textures into your mods/images folder
and the miss is supposed to happen

**Comment by wubbzyfan** [comment]
> and the miss is supposed to happen

No it isn’t? IgnoreNote is supposed to be so you can make hurt notes, ie notes that you SHOULDN’T hit, so if it gave a miss, FCs would be impossible.
