### ISSUE TITLE
Having issues with custom splash texture offsets (Lua)

### ISSUE THREAD

**Issue by ClovesCloestar** [ShadowMario/FNF-PsychEngine#10615]
### Describe your problem here.

I am currently trying to add a custom splash texture for a custom bullet note for a mod i am working on.
However! The splash's offsetting isn't correct here:
![image](https://user-images.githubusercontent.com/106201664/191778287-2399a0b3-63d1-42dc-8759-177a45795702.png)
I've tried searching for a solution but i couldn't find any... 
There is this one [Darnell mod with a video script](https://gamebanana.com/mods/398469) where it has _the vanilla note splash with new offsets for them_, i have tried to just copying and pasting them and adding a variable to just work on the bullet notes, but that didn't worked _**specifically when its the normal notes and the bullet ones at the same time!**_

Here's how the code looks like btw:
![image](https://user-images.githubusercontent.com/106201664/191782085-2669c8b4-9ed0-437d-a362-f20844d34bf7.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by DisIsNOt** [comment]
setPropertyFromGroup('grpNoteSplashes', i, 'offset.x', -20)
 setPropertyFromGroup('grpNoteSplashes', i, 'offset.y', -30)

**Comment by ClovesCloestar** [comment]
Nevermind i've found a solution rn!! 
All that i had to do was just edit the splash xml's frameX and frameY's :P

**Comment by DisIsNOt** [comment]
ooo noice
