### ISSUE TITLE
Display milliseconds like KadeEngine

### ISSUE THREAD

**Issue by nennneko5787** [ShadowMario/FNF-PsychEngine#10625]
### Describe your problem here.

I would like to display milliseconds when a note is hit, like KadeEngine, but I don't know how to do it.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Changed FPS.hx, MainMenuState.hx, ClientPrefs.hx and OutdatedState.hx.

**Comment by StefanBETA2008** [comment]
Use Code From The OS Engine And Thank Change The Color What You Want.

**Comment by nennneko5787** [comment]
I tried, but it didn't work.

**Comment by StefanBETA2008** [comment]
> I tried, but it didn't work.

Did You Added Everything Or You Just Missed? Maybe You Didn't Added To The ClientPrefs.hx `ms`

**Comment by nennneko5787** [comment]
I forgot to say.
I just added the milliseconds display portion of OSEngine and I get the "Null Object Reference" dialog.

**Comment by nennneko5787** [comment]
Resolved. Here is the source code

Break line at line 275.
On line 276, add the following:
<pre>
	var allNotesMs:Float = 0;
	var averageMs:Float = 0;

	var msTimeTxt:FlxText = null;
	var timeShown:Int = 0;
</pre>
private function popUpScore(note:Note = null):Add the following at the end of void:
<pre>
		allNotesMs += noteDiff;
		averageMs = allNotesMs/songHits;

		msTimeTxt = new FlxText(0, 0, 0, "0ms");
		timeShown = 0;
		switch (daRating.name)
		{
			case 'shit' | 'bad':
				msTimeTxt.color = FlxColor.RED;
			case 'good':
				msTimeTxt.color = FlxColor.GREEN;
			case 'sick':
				msTimeTxt.color = FlxColor.CYAN;
		}
		msTimeTxt.borderStyle = OUTLINE;
		msTimeTxt.borderSize = 1;
		msTimeTxt.borderColor = FlxColor.BLACK;
		msTimeTxt.text = Std.string(Math.round(noteDiff)) + "ms";
		msTimeTxt.size = 20;

		if (msTimeTxt.alpha != 1)
			msTimeTxt.alpha = 1;

		add(msTimeTxt);

		msTimeTxt.screenCenter();
		msTimeTxt.x = comboSpr.x + 100;
		msTimeTxt.y = rating.y + 100;
		msTimeTxt.acceleration.y = 600;
		msTimeTxt.velocity.y -= 150;

		msTimeTxt.velocity.x += comboSpr.velocity.x;

		msTimeTxt.updateHitbox();

		msTimeTxt.cameras = [camHUD];

		if (msTimeTxt != null)
			msTimeTxt.alpha -= 0.02;
		timeShown++;

		if (msTimeTxt != null && timeShown >= 20)
			{
				remove(msTimeTxt);
				msTimeTxt = null;
			}
</pre>

**Comment by nennneko5787** [comment]
1.
