### ISSUE TITLE
please someone help me 

### ISSUE THREAD

**Issue by gumba21** [ShadowMario/FNF-PsychEngine#10629]
### Describe your problem here.

Anybody know how to fix this?
Error!
C:\Haxe Toolkit\haxe\std/haxe/xml/Parser.hx (line 217) C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 117) C:\HaxeToolkit\haxe\std/Xml.hx (line 122) flixel/graphics/frames/Fix AtlasFrames.hx (line 246) Character.hx (line 164) PlayState.hx (line 912) flixel/FlxGame.hx (line 637) flixel/FlxGame.hx (line 724) flixel/Flx Game.hx (line 677) flixel/FixGame.hx (line 545) openfl/events/EventDispatcher.hx (line 402) openfl/display/DisplayObject.hx (line 1399)
Uncaught Error: haxe.xml.xmlParserException: Expected node name at line 3 char 7 Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine
> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by nennneko5787** [comment]
Execute the following command at the command prompt
<pre>
haxelib install lime
haxelib install openfl
haxelib install flixel
haxelib run lime setup flixel
haxelib run lime setup
haxelib install flixel-tools
haxelib run flixel-tools setup
haxelib install flixel-addons
haxelib install flixel-ui
haxelib install hscript
haxelib install newgrounds
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
haxelib install hxCodec
</pre>
