### ISSUE TITLE
❌ The Compile Problem With The Windows ❌.

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10627]
### Describe your problem here.

I Got This Error Again Before:
`Called from ? line 1
Called from CommandLineTools.hx line 1904
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 124
Called from CommandLineTools.hx line 1705
Called from lime/tools/ProjectXMLParser.hx line 21
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 50
Called from lime/tools/ProjectXMLParser.hx line 2041
Called from lime/tools/ProjectXMLParser.hx line 1538
Called from lime/tools/ProjectXMLParser.hx line 608
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 709
Called from /Users/runner/hostedtoolcache/haxe/4.2.5/x64/std/neko/_std/sys/FileSystem.hx line 69
Called from /Users/runner/hostedtoolcache/haxe/4.2.5/x64/std/neko/_std/sys/FileSystem.hx line 60
Uncaught exception - std@sys_file_type`

Please Help Me Guys
It's Only Windows Build. `Android`, `Linux` And `Mac` Hasn't Have The Problem On My Engine

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing For Now. Just Manually Run

**Comment by Mastercopper2346** [comment]
idk

**Comment by CrusherNotDrip** [comment]
> idk

then why comment?

**Comment by StefanBETA2008** [comment]
> > idk
> 
> then why comment?

If You're Don't Know How To Help Me, Just Close The Comment: "idk"

**Comment by cheblol** [comment]
try doing lime rebuild tools tho
