### ISSUE TITLE
How do i make the opponent miss notes?

### ISSUE THREAD

**Issue by luigiman0** [ShadowMario/FNF-PsychEngine#10624]
### What is your question?

Basically I'm looking for a custom note type that makes the opponent not hit the notes, and instead have them fly past the strum thing.

**Comment by MemeHoovy** [comment]
try this
```
if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
          setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true); --Miss has no penalties
```

**Comment by machonessiebaby** [comment]
so you mean like
ill send you the zip file
[MISSNOTES_assets.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/9640939/MISSNOTES_assets.zip)
[MissNote.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/9640940/MissNote.zip)
the assets in assets/images
the MissNote.lua in custom notetype

**Comment by MemeHoovy** [comment]
> so you mean like ill send you the zip file [MISSNOTES_assets.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/9640939/MISSNOTES_assets.zip) [MissNote.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/9640940/MissNote.zip) the assets in assets/images the MissNote.lua in custom notetype

I don't think that's what they meant
