### ISSUE TITLE
How to hide ratings?

### ISSUE THREAD

**Issue by MMalkeZ** [ShadowMario/FNF-PsychEngine#10639]
### What is your question?

I don't mean those that go under the health bar, I mean the images that pop on the screen every time you hit a note, like "Sick!", "Good", "Bad" etc, I tried everything I could with "setProperty lastRating" and it doesn't seem to work, also I don't want to just remove the sprites, because that would remove it to every song, I just want to remove it on a specific song.

**Comment by kingyomoma** [comment]
`setProperty('showRating', false)`

**Comment by MMalkeZ** [comment]
> `setProperty('showRating', false)`

thanks it worked, but what about the numbers?

**Comment by kingyomoma** [comment]
`setProperty('showCombo', false)`

**Comment by MMalkeZ** [comment]
> `setProperty('showCombo', false)`

nah this one isnt working

**Comment by LarissaCeleste** [comment]
`showRating` shows the note judgments. (Sick!! / Good! / Bad / Shit)
`showComboNum` show the combo number under it.
`showCombo` literally just shows the WORD "COMBO". _(It's `false` by default, so that's why you almost never see it XD)_

So try using `setProperty('showComboNum', false)` to get rid of the numbers.

**Comment by MMalkeZ** [comment]
> `showRating` shows the note judgments. (Sick!! / Good! / Bad / Shit) `showComboNum` show the combo number under it. `showCombo` literally just shows the WORD "COMBO". _(It's `false` by default, so that's why you almost never see it XD)_
> 
> So try using `setProperty('showComboNum', false)` to get rid of the numbers.

Now there we go, thanks ma'am
