### ISSUE TITLE
Can you play a video on game over in LUA?

### ISSUE THREAD

**Issue by PotatoKing0419** [ShadowMario/FNF-PsychEngine#10633]
### Describe your problem here.

Is there a script or event or anything that when you die, it plays a video like in too fest 2.5?
You know, but in LUA... cuz my computer wont let me download source for some reason?
I suck at coding plz help ;-;

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by DisIsNOt** [comment]
function onGameOver()
       playVideo('video');
      return Function_Stop;
end
return Function_Continue;

you can try this but idk if it works properly or no

**Comment by Mastercopper2346** [comment]
I’m sorry you’ve been caught up in the “nimu” mess

**Comment by MemeHoovy** [comment]
> I’m sorry you’ve been caught up in the “nimu” mess

I took down one of their accounts

**Comment by PotatoKing0419** [comment]
> I’m sorry you’ve been caught up in the “nimu” mess

Nimu mess?

**Comment by MemeHoovy** [comment]
> 
> 
> 
> 
> 
> 
> > I’m sorry you’ve been caught up in the “nimu” mess
> 
> 
> 
> Nimu mess?

It's a long story
