### ISSUE TITLE
Hide song from freeplay.

### ISSUE THREAD

**Issue by Stupid-github-fan** [ShadowMario/FNF-PsychEngine#1063]
### What feature do you want to get added on the base engine?

When on the freeplay editor for your week, you can select  a"hide song from freeplay?" button. And when selected, the song will appear half-vanished.

**Comment by ShadowMario** [comment]
Add it in a different week or some shit? idk.

**Comment by Stupid-github-fan** [comment]
nono i mean like this
![Captura de pantalla (127)](https://user-images.githubusercontent.com/87396034/142744070-4bd8b806-6618-420b-b44b-47334ab85aed.png)
