### ISSUE TITLE
How do you make a freeplay menu like sonic.exe?

### ISSUE THREAD

**Issue by uhhhhuhhhhhhokay** [ShadowMario/FNF-PsychEngine#10634]
I want to make the freeplay menu look like this, is there a code for it (i use source code)
![image](https://user-images.githubusercontent.com/113805777/192070877-c7e8f872-cbdb-4012-9e7b-67003d76d202.png)

**Comment by Lorekeeper49** [comment]
I'm pretty sure you can just steal code from the source material

**Comment by MemeHoovy** [comment]
> I'm pretty sure you can just steal code from the source material

the source code for sonic.exe 2.5/3.0 isn't available

**Comment by ManMaster707** [comment]
> > I'm pretty sure you can just steal code from the source material
> 
> the source code for sonic.exe 2.5/3.0 isn't available

the freeplaystate.hx got officially posted by marstarbro and playstate.hx got leaked

**Comment by SoftDev1101** [comment]
Where are the files at, looked it up and I can’t find nothing lol

**Comment by ManMaster707** [comment]
> Where are the files at, looked it up and I can’t find nothing

the freeplaystate.hx is on mar's twitter i believe, meanwhile the playstate.hx can be found on certain discord servers like this one: [https://discord.gg/VFNx6AYk]() (BEWARE THAT THERE'S NSFW STUFF AND MORE LEAKS IN THERE)

**Comment by uhhhhuhhhhhhokay** [comment]
> 

i just looked on his twitter, i cant find it, is there a specific link with the file?

**Comment by DevAntiSocial** [comment]
Could you link it i cannot find it for the life of me :(

**Comment by KalashniPepsi** [comment]
May i have the link? I can't find it lol

**Comment by MemeHoovy** [comment]
https://github.com/DuskieWhy/exe-2.5-code

**Comment by MemeHoovy** [comment]
> > https://github.com/DuskieWhy/exe-2.5-code here, sonic.exe 2.5/3.0 source code
> 
> ayyyy thx man

your welcome, close the issue please
