### ISSUE TITLE
How to disable spam arrows

### ISSUE THREAD

**Issue by TrigJop** [ShadowMario/FNF-PsychEngine#10641]
### What is your question?

How to disable spam arrows? (script lua or json)

**Comment by TheKitBoi** [comment]
not possible + skill issue

**Comment by StefanBETA2008** [comment]
Spam Arrows? I Think It's Possible

**Comment by MemeHoovy** [comment]
> Spam Arrows? I Think It's Possible

they asked to _disable_ it, learn to read
