### ISSUE TITLE
Cannot leave chart editor

### ISSUE THREAD

**Issue by Julnz** [ShadowMario/FNF-PsychEngine#10645]
### Describe your bug here.

In Psych Engine 0.6.2, whenever I try to leave the chart editor, it doesn't work. I can't die either. I've checked countless times and I do not have practice mode enabled. I only have lua mods enabled, but source songs don't work either.  [https://cdn.discordapp.com/attachments/922851510143045684/1022736634099269712/2022-09-03_15-17-04.mp4](url)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, but the only changes were the icon, app name, and discord appearance.

**Comment by DisIsNOt** [comment]
did you have any specific script running

**Comment by Mastercopper2346** [comment]
I’m sorry you’ve been caught up in the “nimu” mess

**Comment by MemeHoovy** [comment]
> I’m sorry you’ve been caught up in the “nimu” mess

yeah, but I took down one of their accounts

**Comment by TheGithubPsychEngineFan** [comment]
Easily just close the game, and then reopen it again, Simple, Right?
