### ISSUE TITLE
random stage event

### ISSUE THREAD

**Issue by joxu13v** [ShadowMario/FNF-PsychEngine#10648]
### Describe your problem here.

How can I get the stage characters to cross the screen from side to side like in funkin is magic mod, giving random addresses and appearances to the characters using .lua?
![IMG_20220924_190632](https://user-images.githubusercontent.com/98199731/192120261-fd9087c4-0036-450d-8f07-b21de71c0ecc.jpg)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TFLTV** [comment]
how about you learn lua




math.random() is a part of lua and not fnf luajit api

**Comment by joxu13v** [comment]
> doTweenX

but how can I return the appearance of random characters?

**Comment by DisIsNOt** [comment]
math.randomseed(os.time())
 local charcter = math.random();

idk

**Comment by Mastercopper2346** [comment]
I’m sorry you’ve been caught in in “nimu” mess

**Comment by TFLTV** [comment]
> > doTweenX
> 
> but how can I return the appearance of random characters?

>** _ How can I get the stage characters to cross the screen from side to side_**

hmm moment

math.random();

also, are you good at coding?

**Comment by joxu13v** [comment]
> > > doTweenX
> > 
> > but how can I return the appearance of random characters?
> 
> >**How can I get the stage characters to cross the screen from side to side**
> 
> hmm moment
> 
> math.random();
> 
> also, are you good at coding?
> 
> 

not so much, I'm new to this, I don't know many ways to do what I'm looking for

**Comment by DisIsNOt** [comment]
Basically just use math.random for the random character appearance and

FlipX and doTweenX for the character's direction

**Comment by joxu13v** [comment]
> Basically just use math.random for the random character appearance and
> 
> FlipX and doTweenX for the character's direction

ok, i think i got it, thanks

**Comment by DisIsNOt** [comment]
so uhh did It work?

**Comment by MemeHoovy** [comment]
> > Basically just use math.random for the random character appearance and
> > FlipX and doTweenX for the character's direction
> 
> ok, i think i got it, thanks

if it worked, close the issue please

**Comment by TFLTV** [comment]
```lua
local funni = 0
local funnier = 0
--black square variables
local BlackNumberTweens = 1
local willBlackNumberTweens = false
local BCTA = false
--white square variables

function onCreate()
    setProperty("defaultCamZoom", 0.4)
    makeLuaSprite('1', nil, -400, 600);
    makeGraphic('1', 200, 200, '000000');

    makeLuaSprite('2', nil, 0, 0);
    makeGraphic('2', 200, 200, 'FFFFFF');

    addLuaSprite("2", true)
    addLuaSprite("1", true)
end

function onBeatHit()
    funni = math.random(1, 2)
    funnier = math.random(1, 20)
    if funnier == 1 then
        if funni == 1 then
            if BCTA == false then
                if willBlackNumberTweens == true then
                    BlackNumberTweens = BlackNumberTweens + 1
                end
                BCTA = true
                doTweenX( BlackNumberTweens .. 'WalkingDown', '1', 1600, 8);
            end
        else
            --code the white square yourself, nerd.
        end
    end
end

function onTweenCompleted(t)
    if t == "1WalkingDown" then
        doTweenX('1WalkingBack', '1', -400, 0.001);
        willBlackNumberTweens = true
        BCTA = false
    end
    if t == BlackNumberTweens .. "WalkingDown" then
        doTweenX('1WalkingBack', '1', -400, 0.001);
        BCTA = false
    end
end
```

**Comment by TFLTV** [comment]
close the issue
