### ISSUE TITLE
Can I make changes to the main menu with Lua?

### ISSUE THREAD

**Issue by QuetzalcoutlDev** [ShadowMario/FNF-PsychEngine#10647]
### What is your question?

I know the question may sound silly, but can you change the main menu with Lua?

**Comment by joxu13v** [comment]
No

**Comment by MemeHoovy** [comment]
> ### What is your question?
> I know the question may sound silly, but can you change the main menu with Lua?

no you can't

**Comment by DisIsNOt** [comment]
no

**Comment by StefanBETA2008** [comment]
> ### What is your question?
> I know the question may sound silly, but can you change the main menu with Lua?

It's Impossible Dude. No One Can Do This

**Comment by QuetzalcoutlDev** [comment]
Okey 😅😅
