### ISSUE TITLE
Custom fade transition

### ISSUE THREAD

**Issue by RubenDatOneBoi3446** [ShadowMario/FNF-PsychEngine#10646]
### What is your question?

Is there anyway i can make a custom transition but with images instead of source?

**Comment by DisIsNOt** [comment]
no

**Comment by ripsyhehe** [comment]
its not possible without source, wednesday infidelity did it with custom images using source, so i recommend look at the source build and use the CustomFadeTransition.hx file, and add kevin_normal.png into preload/images! [https://github.com/lunarcleint/Wednesdays-Infidelity](url)

**Comment by RubenDatOneBoi3446** [comment]
> its not possible without source, wednesday infidelity did it with custom images using source, so i recommend look at the source build and use the CustomFadeTransition.hx file, and add kevin_normal.png into preload/images! [https://github.com/lunarcleint/Wednesdays-Infidelity](url)

Alright thank u
