### ISSUE TITLE
Building HTML5 Does not work

### ISSUE THREAD

**Issue by BL0KYBL0K** [ShadowMario/FNF-PsychEngine#1066]
### Describe your bug here.

So i wanted to embed my fnf mod into a website but i need to have it in a html file to do that but when i export i get an error
it exports fine with windows / .exe exports so why does html5 get an error

### Command Prompt/Terminal logs (if existing)

```bash
lime build html5
source/CreditsState.hx:15: characters 8-22 : You cannot access the sys package while targeting js (for sys.FileSystem)
source/MainMenuState.hx:220: characters 42-54 :     referenced here
PS C:\Users\carso\Downloads\wafdwafwafsae\FNF-PsychEngine-main>
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

I made a mod but the changes work because all my changes were in lua and it works when i export to windows

**Comment by ShadowMario** [comment]
Fixed
