### ISSUE TITLE
how to disable the chart editor in lua

### ISSUE THREAD

**Issue by lucasfelez** [ShadowMario/FNF-PsychEngine#10669]
### What is your question?

How to disable the key 7?

**Comment by MemeHoovy** [comment]
> ### What is your question?
> How to disable the key 7?

```
function onCreatePost()
    setProperty('debugKeysChart', nil);
end
```

**Comment by lucasfelez** [comment]
> > ### What is your question?
> > How to disable the key 7?
> 
> ```
> function onCreatePost()
>     setProperty('debugKeysChart', nil);
> end
> ```

thanks
