### ISSUE TITLE
Character Selector

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#10673]
### Describe your problem here.

I just need a Character Selector for my mod.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by CaptainBaldi** [comment]
please don't ask people to code everything for you, look at the psych wiki its not difficult to make one

**Comment by fnfdemonboi314159** [comment]
> please don't ask people to code everything for you, look at the psych wiki its not difficult to make one

hang on, lemme check rq
