### ISSUE TITLE
what does it mean, and did I do something wrong?

### ISSUE THREAD

**Issue by LolokejMC** [ShadowMario/FNF-PsychEngine#10675]
### Describe your problem here.

i trying compile psych engine but but I still see it

![image](https://user-images.githubusercontent.com/114352623/192153276-e15da9ef-1de1-4461-97f6-56df6ae43e5c.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

**Comment by DisIsNOt** [comment]
May be go search google

**Comment by MemeHoovy** [comment]
> ### Describe your problem here.
> i trying compile psych engine but but I still see it
> 
> ![image](https://user-images.githubusercontent.com/114352623/192153276-e15da9ef-1de1-4461-97f6-56df6ae43e5c.png)
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x86/x32
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> _No response_

from what [I found](https://github.com/HaxeFoundation/haxe/issues/4778) it means you don't have Visual Studio correctly setup
