### ISSUE TITLE
How can I make the preload folder reload new assets?

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#10679]
### Describe your problem here.

I put new files in the preload folder but it isn't reloading, how do I make it reload the new assets?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by DisIsNOt** [comment]
idk be more specfic

**Comment by bruh1cat** [comment]
> idk be more specfic

Already fixed it just forgot to close it mb.

**Comment by DisIsNOt** [comment]
Ok lol
