### ISSUE TITLE
STAGES SHITTT

### ISSUE THREAD

**Issue by Gurudevsing** [ShadowMario/FNF-PsychEngine#10674]
### Describe your problem here.

![Screenshot (26)](https://user-images.githubusercontent.com/87480185/192150151-bc28afce-46c8-4d99-985b-08d9904acac4.png)
Hey man, above image you can see i add agoti speakers using lua but it seems too big or enlarge whatever, tell me how to zoom out and i need to know speakers moving code man i work it out but it did't work [I KNOW MY ENGLISH IS SHIT ] help me out man 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
Go to stages foleder find (stageurusing).json
And edit  "defaultZoom": 1, to 0.e

**Comment by TheKitBoi** [comment]
ar u gonna respond

**Comment by Gurudevsing** [comment]
sorry i had exam  in past days , did't see your response, thanks man  i have one more doubt

**Comment by Gurudevsing** [comment]
> ar u gonna respond


sorry i had exam in past days , did't see your response, thanks for your time and i have one more doubt take a look

https://user-images.githubusercontent.com/87480185/193348091-ee3f4741-19c1-4ece-b9f5-667753b812ad.mp4
camera shitss
![Screenshot (28)](https://user-images.githubusercontent.com/87480185/193349018-48751d00-6937-41f0-8a45-a238c6814552.png)


i coded but i miss something, solve this error: [Expected commajson(514)]

and thanks

**Comment by Gurudevsing** [comment]
hello kidboy?

**Comment by Gurudevsing** [comment]
> ar u gonna respond

hello?

**Comment by Gostar64** [comment]
put a comma at the end of the "opponent" line

**Comment by Gurudevsing** [comment]
> put a comma at the end of the "opponent" line

in opponent line? comma is already there

**Comment by TheKitBoi** [comment]
{
	"directory": "",
	"defaultZoom": 0.4,
	"isPixelStage": false,

	"boyfriend": [800, 200],
	"girlfriend": [350, 230],
	"opponent": [100, 100],

	"camera_boyfriend": [0, 0],
	"camera_opponent": [0, 0],
	"camera_girlfriend": [0, 0],
	"camera_speed": 1
}
