### ISSUE TITLE
How to make the timebar extend like wednesday infidelity mod in unknown suffering

### ISSUE THREAD

**Issue by lucasfelez** [ShadowMario/FNF-PsychEngine#10671]
### What is your question?

i want to make the timebar extend like wednesday infidelity mod in unknown suffering in lua

**Comment by MemeHoovy** [comment]
> ### What is your question?
> i want to make the timebar extend like wednesday infidelity mod in unknown suffering in lua

not possible in lua

**Comment by StefanBETA2008** [comment]
> > ### What is your question?
> > i want to make the timebar extend like wednesday infidelity mod in unknown suffering in lua
> 
> not possible in lua

Maybe Has Need To Copy Source Code From lunarclient

**Comment by MemeHoovy** [comment]
> > > ### What is your question?
> > > i want to make the timebar extend like wednesday infidelity mod in unknown suffering in lua
> > 
> > 
> > not possible in lua
> 
> Maybe Has Need To Copy Source Code From lunarclient

they wanted to do it in _lua_ though, which isn't possible

**Comment by StefanBETA2008** [comment]
> > > > ### What is your question?
> > > > i want to make the timebar extend like wednesday infidelity mod in unknown suffering in lua
> > > 
> > > 
> > > not possible in lua
> > 
> > 
> > Maybe Has Need To Copy Source Code From lunarclient
> 
> they wanted to do it in _lua_ though, which isn't possible

I See Now

**Comment by bruh1cat** [comment]
> ### What is your question?
> 
> 
> 
> i want to make the timebar extend like wednesday infidelity mod in unknown suffering in lua

Maybe make the end time just normal text since it never changes and then use seTextString to change it to the real end time.


Ex: 6:12/6:15

**Comment by lucasfelez** [comment]
aight then it's settled
