### ISSUE TITLE
Discord.hx and DiscordRpc

### ISSUE THREAD

**Issue by Kessmonster** [ShadowMario/FNF-PsychEngine#10688]
### Describe your problem here.

I compile the game for the first time without editing anything and it shows this:

source/Discord.hx:4: characters 8-30 : Type not found : discord_rpc.DiscordRpc
source/Discord.hx:19: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:29: characters 4-14 : Type not found : DiscordRpc
source/Discord.hx:34: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:39: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:44: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:81: characters 3-13 : Type not found : DiscordRpc

does anyone know how to fix this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I changed nothing. I just unzipped it and installed all libraries

**Comment by TheKitBoi** [comment]
This man never looks how to compile properly
haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
+
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

**Comment by Kessmonster** [comment]
I did and I did it again but its the same error.

**Comment by Kessmonster** [comment]
I have everything installed but it still gives the DiscordRpc error
