### ISSUE TITLE
Discord.hx not working

### ISSUE THREAD

**Issue by Kessmonster** [ShadowMario/FNF-PsychEngine#10689]
### Describe your problem here.

I have installed all libraries and the needed stuff and unzipped it but it says this

source/Discord.hx:4: characters 8-30 : Type not found : discord_rpc.DiscordRpc
source/Discord.hx:19: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:29: characters 4-14 : Type not found : DiscordRpc
source/Discord.hx:34: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:39: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:44: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:81: characters 3-13 : Type not found : DiscordRpc

Anyone know how to help with this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I changed nothing. I just unzipped it and installed everything needed

**Comment by Thedumbdude** [comment]
use this `haxelib git discord_rpc`

**Comment by Kessmonster** [comment]
> open command prompt and paste this in `haxelib git discord_rpc` and press enter

that still gave me the same errors prior

**Comment by Kessmonster** [comment]
![Screenshot 2022-09-26 200140](https://user-images.githubusercontent.com/114443089/192401476-47a68e13-219b-4f79-9c14-0c6a2e16446c.png)

**Comment by Thedumbdude** [comment]
> ![Screenshot 2022-09-26 200140](https://user-images.githubusercontent.com/114443089/192401476-47a68e13-219b-4f79-9c14-0c6a2e16446c.png)

ok i will try and think what the problem is

**Comment by Kessmonster** [comment]
> 

I also tried the git path being the github Discord RPC page link
