### ISSUE TITLE
I cant use the oswald from W.I

### ISSUE THREAD

**Issue by ElPro7777** [ShadowMario/FNF-PsychEngine#10683]
### Describe your bug here.

I cant use the oswald from W.I My psych engine crashes

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
Character.hx (line 164)
PlayState.hx (line 940)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Not a bug
Missing character texture files

**Comment by Gostar64** [comment]
Oswald and many other W.I. characters use JSONs instead of XMLs, but not like an animation atlas JSON.

**Comment by ElPro7777** [comment]
> Not a bug Missing character texture files

I have the texture and the json (the oswald sprite use JSON not XML)

**Comment by ElPro7777** [comment]
> Oswald and many other W.I. characters use JSONs instead of XMLs, but not like an animation atlas JSON.
How i can fix it? i dont have adobe animator

**Comment by frantastic24** [comment]
> I have the texture and the json (the oswald sprite use JSON not XML)

psych doesn't support json, you'll have to make an xml

**Comment by MemeHoovy** [comment]
> > I have the texture and the json (the oswald sprite use JSON not XML)
> 
> 
> 
> psych doesn't support json, you'll have to make an xml

It literally has support for texture atlas

**Comment by frantastic24** [comment]
which uses a completely different system you clown

**Comment by MemeHoovy** [comment]
> which uses a completely different system you clown

yeah, but still, support for json characters, instead of just xml

**Comment by frantastic24** [comment]
they're not using texture atlas, your comment is pointless

**Comment by MemeHoovy** [comment]
> they're not using texture atlas, your comment is pointless

still, they're using flxanimate, and here's the description for it ```Adobe Animate's texture atlases player for HaxeFlixel```

**Comment by frantastic24** [comment]
Don't know what you're trying to prove here since texture atlas has nothing to do with this post, like I said

**Comment by MemeHoovy** [comment]
> Don't know what you're trying to prove here since texture atlas has nothing to do with this post, like I said

that's what the characters in Wednesdays infidelity use, Oswald as well, they use an texture atlas, and in the source code, they use an texture atlas to load the characters, so yeah, it's probably possible to use Oswald's character file and sprites, and everything you said before was wrong

**Comment by MemeHoovy** [comment]
some proof of evidence

![Screenshot 2022-09-26 203249](https://user-images.githubusercontent.com/97995998/192404673-b32f875e-da38-4538-9ff4-b840b85ea129.png)
![Screenshot 2022-09-26 203311](https://user-images.githubusercontent.com/97995998/192404687-cd2ed800-11d8-49e0-a243-9039045dc05c.png)

**Comment by frantastic24** [comment]
> that's what the characters in Wednesdays infidelity use

No? They use texture packer just like XML but in json format

**Comment by ElPro7777** [comment]
Know what i will Make a BETADCIU for other song

**Comment by ElPro7777** [comment]
CLOSED

**Comment by MemeHoovy** [comment]
> > that's what the characters in Wednesdays infidelity use
> 
> No? They use texture packer just like XML but in json format It's literally in your screenshot?

look it doesn't even matter anymore, the issue's closed, so you can just piss off
