### ISSUE TITLE
Game Crashes when Loading Custom Character in Song

### ISSUE THREAD

**Issue by Wulavr** [ShadowMario/FNF-PsychEngine#10687]
### Describe your problem here.

I just added a character after charting the song for it, and everything works well in the character editor. But when I load the json of the character in a song the game crashes, showing this.
![error](https://user-images.githubusercontent.com/114381081/192201284-acfb43d4-c53d-4def-923f-6f9dca9d25dc.png)
I've tried everything and don't know what to do. This has happened to me every time I try to load a character in the past.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a sprite sheet and xml of the character (I used the xml generator cause no adobe animate) and I charted a custom song. I also added an icon for the character and a week.

**Comment by Rom4chek** [comment]
Not right path/sprite name prb

**Comment by Rom4chek** [comment]
Idk

**Comment by RGonzo47** [comment]
I’m using MacBuild for Psych engine I put my custom character that I put in mods images and characters when I load the character it crashes
