### ISSUE TITLE
how do you change the window size in one single song

### ISSUE THREAD

**Issue by Taetek** [ShadowMario/FNF-PsychEngine#10682]
### What is your question?

im working on a sonic.exe mod and i want to change the size of the window (like fatality or milk) how would i do that i use source so i cant use lua

**Comment by MemeHoovy** [comment]
> ### What is your question?
> im working on a sonic.exe mod and i want to change the size of the window (like fatality or milk) how would i do that i use source so i cant use lua

https://github.com/DuskieWhy/exe-2.5-code

**Comment by MemeHoovy** [comment]
you should also know that duskie doesn't like sonic.exe revivals though, just wanna throw that out there
