### ISSUE TITLE
Discord.hx Problem

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10680]
### Describe your problem here.

I Got This:
source/Discord.hx:6: characters 8-30 : Type not found : discord_rpc.DiscordRpc
source/Discord.hx:85: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:21: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:31: characters 4-14 : Type not found : DiscordRpc
source/Discord.hx:38: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:43: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:48: characters 3-13 : Type not found : DiscordRpc

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

I Just Edited Something From The Discord.hx

**Comment by LilDrippyMyFnf** [comment]
discord?

**Comment by Thedumbdude** [comment]
open command prompt and paste this in `haxelib git discord_rpc` and press enter

**Comment by StefanBETA2008** [comment]
Nevermind, Fixed.
