### ISSUE TITLE
How can make real seamless infinately scrolling BGs

### ISSUE THREAD

**Issue by EgguMan** [ShadowMario/FNF-PsychEngine#10697]
### Describe your problem here.

When making an infinately scrolling BG, the left takes more time to load. How can I make it so this does not happen? Ive tried changing the backdrop's X and BFs X but the same thing happens

example below

https://user-images.githubusercontent.com/100107293/192885044-58f85462-a415-4e83-b1b7-3af7f0215495.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

playstate to make the BG work

**Comment by Mastercopper2346** [comment]
Slow it down probably lol

**Comment by Mastercopper2346** [comment]
Also can you send the code of how to do this? It’s cool!

**Comment by CaptainBaldi** [comment]
you might be able to do it with velocity shit but erm i dont know how the funny source code works

**Comment by EgguMan** [comment]
> you might be able to do it with velocity shit but erm i dont know how the funny source code works

dont comment if you dont know how source works

**Comment by EgguMan** [comment]
> Also can you send the code of how to do this? It’s cool!

`var buildings:FlxBackdrop = new FlxBackdrop(Paths.image('bg/tropicalResort/open/buildings'),1,1,true,false);
buildings.velocity.set(-1800, 0);
//buildings.scale.set(2,2);
buildings.updateHitbox();
add(buildings);`

"slow it down" do you see how fast it is?

**Comment by Mastercopper2346** [comment]
```haxe
var buildings:FlxBackdrop = new FlxBackdrop(Paths.image('bg/tropicalResort/open/buildings'),1,1,true,false); 
buildings.velocity.set(-1800, 0); 
//buildings.scale.set(2,2); 
buildings.updateHitbox(); 
add(buildings);
```
I fixed the code to be more lined-up at more understanding here

**Comment by DisIsNOt** [comment]
idk may be change scrollX ? idk I didn't even use FlxBackdrop before

**Comment by EgguMan** [comment]
> idk may be change scrollX ? idk I didn't even use FlxBackdrop before

ScrollX is the scrollFactor

**Comment by Username2120** [comment]
I don't know if you fully want to stick to source. however if you are willing to throw a Lua script together I do have some code for that. as far as I can tell its seamless so I don't see why it wouldn't work for you.
```
local width = 0
local spriteName = "sprite name here"

function onCreate()
	makeLuaSprite("bg1", spriteName, 0, 0)
	width = getProperty("bg1.width")	
	
	makeLuaSprite("bg2", spriteName, width-20, 0)

	addLuaSprite("bg1", false)
	addLuaSprite("bg2", false)

	doTweenX("bg1Tween", "bg1", -width, 1, "linear")
	doTweenX("bg2Tween", "bg2", -20, 1, "linear")
end

function onTweenCompleted(tag)
	if tag == "bg1Tween" then
		setProperty("bg1.x", 0)
		setProperty("bg2.x", width-20)
		
		doTweenX("bg1Tween", "bg1", -width, 1, "linear")
		doTweenX("bg2Tween", "bg2", -20, 1, "linear")
	end
end
```
This script is demonstrated in the video below.

https://user-images.githubusercontent.com/93958902/196589856-b0024973-57da-4d99-813f-daf9a95bfa8e.mp4

**Comment by EgguMan** [comment]
> I don't know if you fully want to stick to source. however if you are willing to throw a Lua script together I do have some code for that. as far as I can tell its seamless so I don't see why it wouldn't work for you.
> 
> ```
> local width = 0
> local spriteName = "sprite name here"
> 
> function onCreate()
> 	makeLuaSprite("bg1", spriteName, 0, 0)
> 	width = getProperty("bg1.width")	
> 	
> 	makeLuaSprite("bg2", spriteName, width-20, 0)
> 
> 	addLuaSprite("bg1", false)
> 	addLuaSprite("bg2", false)
> 
> 	doTweenX("bg1Tween", "bg1", -width, 1, "linear")
> 	doTweenX("bg2Tween", "bg2", -20, 1, "linear")
> end
> 
> function onTweenCompleted(tag)
> 	if tag == "bg1Tween" then
> 		setProperty("bg1.x", 0)
> 		setProperty("bg2.x", width-20)
> 		
> 		doTweenX("bg1Tween", "bg1", -width, 1, "linear")
> 		doTweenX("bg2Tween", "bg2", -20, 1, "linear")
> 	end
> end
> ```
> 
> This script is demonstrated in the video below.
> 
>  8mb.video-3xi-Stn2awK1.mp4

im sticking to 100% source for this mod, I would rather code my own FlxBackdrop instead of making the users have to wait on the start up of the song

**Comment by Username2120** [comment]
ah, okay. then i cant really help you much further as im still learning source, sorry. best of luck to ya.

**Comment by NavaGaming** [comment]
> I don't know if you fully want to stick to source. however if you are willing to throw a Lua script together I do have some code for that. as far as I can tell its seamless so I don't see why it wouldn't work for you.
> 
> ```
> local width = 0
> local spriteName = "sprite name here"
> 
> function onCreate()
> 	makeLuaSprite("bg1", spriteName, 0, 0)
> 	width = getProperty("bg1.width")	
> 	
> 	makeLuaSprite("bg2", spriteName, width-20, 0)
> 
> 	addLuaSprite("bg1", false)
> 	addLuaSprite("bg2", false)
> 
> 	doTweenX("bg1Tween", "bg1", -width, 1, "linear")
> 	doTweenX("bg2Tween", "bg2", -20, 1, "linear")
> end
> 
> function onTweenCompleted(tag)
> 	if tag == "bg1Tween" then
> 		setProperty("bg1.x", 0)
> 		setProperty("bg2.x", width-20)
> 		
> 		doTweenX("bg1Tween", "bg1", -width, 1, "linear")
> 		doTweenX("bg2Tween", "bg2", -20, 1, "linear")
> 	end
> end
> ```
> 
> This script is demonstrated in the video below.
> 
>  8mb.video-3xi-Stn2awK1.mp4

Epic Code, until sprite looks like this
![thismf](https://user-images.githubusercontent.com/105751462/211133995-fc6fca84-3efd-4202-ae0f-ca0f0f838bd4.png)

**Comment by EgguMan** [comment]
> > I don't know if you fully want to stick to source. however if you are willing to throw a Lua script together I do have some code for that. as far as I can tell its seamless so I don't see why it wouldn't work for you.
> > ```
> > local width = 0
> > local spriteName = "sprite name here"
> > 
> > function onCreate()
> > 	makeLuaSprite("bg1", spriteName, 0, 0)
> > 	width = getProperty("bg1.width")	
> > 	
> > 	makeLuaSprite("bg2", spriteName, width-20, 0)
> > 
> > 	addLuaSprite("bg1", false)
> > 	addLuaSprite("bg2", false)
> > 
> > 	doTweenX("bg1Tween", "bg1", -width, 1, "linear")
> > 	doTweenX("bg2Tween", "bg2", -20, 1, "linear")
> > end
> > 
> > function onTweenCompleted(tag)
> > 	if tag == "bg1Tween" then
> > 		setProperty("bg1.x", 0)
> > 		setProperty("bg2.x", width-20)
> > 		
> > 		doTweenX("bg1Tween", "bg1", -width, 1, "linear")
> > 		doTweenX("bg2Tween", "bg2", -20, 1, "linear")
> > 	end
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This script is demonstrated in the video below.
> > 8mb.video-3xi-Stn2awK1.mp4
> 
> Epic Code, until sprite looks like this ![thismf](https://user-images.githubusercontent.com/105751462/211133995-fc6fca84-3efd-4202-ae0f-ca0f0f838bd4.png)

Holy SHIT, no offense but this question is so old the bug got fixed, I learned to do it myself, and I stopped using lua all together, lmao.

**Comment by NavaGaming** [comment]
> > > I don't know if you fully want to stick to source. however if you are willing to throw a Lua script together I do have some code for that. as far as I can tell its seamless so I don't see why it wouldn't work for you.
> > > ```
> > > local width = 0
> > > local spriteName = "sprite name here"
> > > 
> > > function onCreate()
> > > 	makeLuaSprite("bg1", spriteName, 0, 0)
> > > 	width = getProperty("bg1.width")	
> > > 	
> > > 	makeLuaSprite("bg2", spriteName, width-20, 0)
> > > 
> > > 	addLuaSprite("bg1", false)
> > > 	addLuaSprite("bg2", false)
> > > 
> > > 	doTweenX("bg1Tween", "bg1", -width, 1, "linear")
> > > 	doTweenX("bg2Tween", "bg2", -20, 1, "linear")
> > > end
> > > 
> > > function onTweenCompleted(tag)
> > > 	if tag == "bg1Tween" then
> > > 		setProperty("bg1.x", 0)
> > > 		setProperty("bg2.x", width-20)
> > > 		
> > > 		doTweenX("bg1Tween", "bg1", -width, 1, "linear")
> > > 		doTweenX("bg2Tween", "bg2", -20, 1, "linear")
> > > 	end
> > > end
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This script is demonstrated in the video below.
> > > 8mb.video-3xi-Stn2awK1.mp4
> > 
> > 
> > Epic Code, until sprite looks like this ![thismf](https://user-images.githubusercontent.com/105751462/211133995-fc6fca84-3efd-4202-ae0f-ca0f0f838bd4.png)
> 
> Holy SHIT, no offense but this question is so old the bug got fixed, I learned to do it myself, and I stopped using lua all together, lmao.

I literally just check every question about scrolling bg's looking for kind of help, cuz i just suck at codding

**Comment by EgguMan** [comment]
> > > > I don't know if you fully want to stick to source. however if you are willing to throw a Lua script together I do have some code for that. as far as I can tell its seamless so I don't see why it wouldn't work for you.
> > > > ```
> > > > local width = 0
> > > > local spriteName = "sprite name here"
> > > > 
> > > > function onCreate()
> > > > 	makeLuaSprite("bg1", spriteName, 0, 0)
> > > > 	width = getProperty("bg1.width")	
> > > > 	
> > > > 	makeLuaSprite("bg2", spriteName, width-20, 0)
> > > > 
> > > > 	addLuaSprite("bg1", false)
> > > > 	addLuaSprite("bg2", false)
> > > > 
> > > > 	doTweenX("bg1Tween", "bg1", -width, 1, "linear")
> > > > 	doTweenX("bg2Tween", "bg2", -20, 1, "linear")
> > > > end
> > > > 
> > > > function onTweenCompleted(tag)
> > > > 	if tag == "bg1Tween" then
> > > > 		setProperty("bg1.x", 0)
> > > > 		setProperty("bg2.x", width-20)
> > > > 		
> > > > 		doTweenX("bg1Tween", "bg1", -width, 1, "linear")
> > > > 		doTweenX("bg2Tween", "bg2", -20, 1, "linear")
> > > > 	end
> > > > end
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > This script is demonstrated in the video below.
> > > > 8mb.video-3xi-Stn2awK1.mp4
> > > 
> > > 
> > > Epic Code, until sprite looks like this ![thismf](https://user-images.githubusercontent.com/105751462/211133995-fc6fca84-3efd-4202-ae0f-ca0f0f838bd4.png)
> > 
> > 
> > Holy SHIT, no offense but this question is so old the bug got fixed, I learned to do it myself, and I stopped using lua all together, lmao.
> 
> I literally just check every question about scrolling bg's looking for kind of help, cuz i just suck at codding

Cool, I’m not here to help you out, you don’t come into a 3 month old question about source code asking for lua help. Sucks you can’t use FlxBackdrop in lua but get over it I guess.
