### ISSUE TITLE
FlxCamera problem and others

### ISSUE THREAD

**Issue by Kessmonster** [ShadowMario/FNF-PsychEngine#10698]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/114443089/192912171-c35e69d9-3433-4fd3-853b-144f168aacd5.png)

Idk why this is happening nor what to do to fix it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I have everything installed and Im trying to compile it without changing anything

**Comment by frantastic24** [comment]
FlxCamera stuff are just warnings, they can be ignored
You're missing visual studio components

**Comment by Kessmonster** [comment]
What am I missing?

**Comment by Kessmonster** [comment]
> 

I thought I had everything I needed

**Comment by frantastic24** [comment]
You should look up the error in issues and/or go through the list of components again, haxe isn't very specific about these

**Comment by DisIsNOt** [comment]
Try install visual studio community 2019

**Comment by Kessmonster** [comment]
> Try install visual studio community 2019

That worked, thank you
