### ISSUE TITLE
Note that changes alpha of an image

### ISSUE THREAD

**Issue by Shaggers-official** [ShadowMario/FNF-PsychEngine#10696]
### Describe your problem here.

So, i wanna make a custom mechanic that, first, if the alpha of a picture is > 0.60, it slowly comes back to 0.60.
Then, if boyfriend presses a note, it adds 0.02 to the alpha.
I've tried everything i know but for some reasons i cannot find out how to make it, here's the code if you think you can find what i did wrong.

```
function onUpdate(elasped)
    while getProperty('filter.alpha') > 0.60 do
        setProperty('filter.alpha', getProperty('filter.alpha') - 0.001)
    end
end

function goodNoteHit(id, direction, noteType, isSustainNote)
    if getProperty('filter.alpha') >= 0.6 then
        if not isSustainNote then
             setProperty('filter.alpha', getProperty('filter.alpha') + 0.04)
        else
             setProperty('filter.alpha', getProperty('filter.alpha') + 0.02)
        end
    end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHoovy** [comment]
> **_NOT_** a .Lua person. Sorry

then why did you comment?

**Comment by Meme1079** [comment]
There's two reasons why it's not working. The first is `while-do` loop, this loop will be repeated on `onUpdate()` over and over again making it, not adding opacity. The second is that I don't really know why it's not working on the `getProperty('filter.alpha') > 0.60` on the `goodNoteHit()` probably a bug or something.

Anyways here the fixed:

```lua
function onUpdate(elasped)
     if getProperty('filter.alpha') > 0.60 then
          setProperty('filter.alpha', getProperty('filter.alpha') - 0.001)
     end
end

function goodNoteHit(id, direction, noteType, isSustainNote)
     if getProperty('filter.alpha') > 0.50 then
          if not isSustainNote then
               setProperty('filter.alpha', getProperty('filter.alpha') + 0.04)
          else
               setProperty('filter.alpha', getProperty('filter.alpha') + 0.02)
          end
     end
end
```

**Comment by Shaggers-official** [comment]
Alright, thank you so much ! I understand my mistake now
