### ISSUE TITLE
The Question 2

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10690]
### What is your question?

How To Add The New Rating Image, Like: Marvelous, Perfect And More? Help Guys Please.

**Comment by bruh1cat** [comment]
Copy code from playstate and rename it.

**Comment by MemeHoovy** [comment]
> Copy code from playstate and rename it. Search for sick in playstate to find it quicker.

that's not at all a good solution, just borrow code from BEAT!Engine https://github.com/Z11Coding/Beat-Engine-Revived
