### ISSUE TITLE
How to remove main weeks?

### ISSUE THREAD

**Issue by JavoniCraft** [ShadowMario/FNF-PsychEngine#10692]
### Describe your problem here.

I am making a mod using source code and I want to remove weeks 1 through 7. How can I do so?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't edit anything.

**Comment by frantastic24** [comment]
`assets/weeks`

**Comment by ShadowMilky** [comment]
delete all week json files in assets/weeks
easy peasy

**Comment by Taetek** [comment]
btw cause i had the same problem delete them from the export folder (if you already compiled)
