### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by CBa08** [ShadowMario/FNF-PsychEngine#107]
When I write lime test windows
This happens.
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1810: characters 22-28 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1810: characters 22-28 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1815: characters 22-28 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1815: characters 22-28 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1831: characters 24-30 : lime.utils.UInt32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1831: characters 24-30 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1836: characters 24-30 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1836: characters 24-30 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1841: characters 24-30 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1841: characters 24-30 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:143: characters 5-23 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.OpenGLES2RenderContext
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:144: characters 5-23 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.WebGLRenderContext
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:150: characters 6-24 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.OpenGLES3RenderContext
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:151: characters 6-25 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.WebGL2RenderContext
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/math/FlxPoint.hx:31: characters 3-15 : flixel.math.FlxPoint should be { _inPool : Bool }
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/math/FlxPoint.hx:31: characters 3-15 : ... The field _inPool is not public
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4740: characters 74-75 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4740: characters 74-75 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/math/FlxPoint.hx:17: characters 2-53 : error: The field _inPool is not public
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/math/FlxPoint.hx:17: characters 2-53 : ... have: { get: (...) -> { set: (...) -> flixel.math.FlxPoint } }
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/math/FlxPoint.hx:17: characters 2-53 : ... want: { get: (...) -> { set: (...) -> { _inPool } } }
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/math/FlxPoint.hx:70: characters 10-19 : { get : () -> { set : (Float, Float) -> { _inPool : Bool } } } has no field putUnsafe
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/group/FlxGroup.hx:473: characters 80-91 : Type not found : ObjectClass
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/math/ColorMatrix.hx:117: characters 12-17 : lime.math.ColorMatrix should be Null<lime.utils.ArrayBufferView>
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/math/ColorMatrix.hx:117: characters 12-17 : ... For optional function argument 'view'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2313: characters 36-42 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2313: characters 36-42 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2319: characters 36-42 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2319: characters 36-42 : ... For function argument 'params'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4617: characters 63-64 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4617: characters 63-64 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4631: characters 64-65 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4631: characters 64-65 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4639: characters 66-67 : lime.utils.UInt32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4639: characters 66-67 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4655: characters 70-71 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4655: characters 70-71 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4669: characters 71-72 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4669: characters 71-72 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4678: characters 73-74 : lime.utils.UInt32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4678: characters 73-74 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4696: characters 80-81 : lime.utils.Float32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4696: characters 80-81 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4712: characters 81-82 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4712: characters 81-82 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4721: characters 83-84 : lime.utils.UInt32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4721: characters 83-84 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4757: characters 75-76 : lime.utils.Int32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4757: characters 75-76 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4767: characters 77-78 : lime.utils.UInt32Array should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4767: characters 77-78 : ... For function argument 'v'
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/media/OpenALAudioContext.hx:573: characters 3-40 : lime.media.openal.ALBuffer should be Int
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/text/harfbuzz/HBBlob.hx:47: characters 3-48 : Float should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/text/harfbuzz/HBBlob.hx:56: characters 3-57 : Float should be lime.utils.DataPointer
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/math/Matrix4.hx:235: characters 12-17 : lime.math.Matrix4 should be Null<lime.utils.ArrayBufferView>
C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/math/Matrix4.hx:235: characters 12-17 : ... For optional function argument 'view'
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/math/FlxPoint.hx:485: characters 3-15 : { get : () -> { set : (Float, Float) -> { _inPool : Bool } } } should be flixel.util.IFlxPool<flixel.math.FlxPoint>
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/group/FlxGroup.hx:852: characters 19-30 : Type not found : ObjectClass
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/system/frontEnds/PluginFrontEnd.hx:47: characters 19-28 : Type not found : ClassType
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/system/frontEnds/PluginFrontEnd.hx:94: characters 20-29 : Type not found : ClassType

Can anyone tell me how to fix this?

**Comment by ShadowMario** [comment]
Looks like you're missed something while installing Haxe/libraries, refer to this tutorial.

**Comment by DybaTubeYT1** [comment]
didnt worked shadowmario
