### ISSUE TITLE
Im having a slight problem.

### ISSUE THREAD

**Issue by Qishdingus** [ShadowMario/FNF-PsychEngine#10704]
### What is your question?

![2022-09-29](https://user-images.githubusercontent.com/114708404/193161492-7eb856b8-4c28-4e26-a2e4-931e9089f994.png)

This little window appears whenever I try playing a custom song right after I switch the bf character to a custom character.

**Comment by Qishdingus** [comment]
Does anyone know how to fix this. I'm using LUA.

**Comment by tposejank** [comment]
> Does anyone know how to fix this. I'm using LUA.
we wouldn't know if you didn't tell us what your code is (is that logical?)

**Comment by DisIsNOt** [comment]
is your character's files even there
