### ISSUE TITLE
Framerate Drastically Drops when Entering new State I made.

### ISSUE THREAD

**Issue by elixioo** [ShadowMario/FNF-PsychEngine#10705]
### Describe your problem here.

Hi there! Making a custom credits menu, it was going well until suddenly, when i wait a few seconds in said menu, the frame rate drastically drops all the way to 30.

Video Attached.

https://user-images.githubusercontent.com/88951878/193162286-c53fbcce-5154-4309-89e5-c18c5c36ae47.mp4

Here's the code for the menu

`package;

#if desktop
import Discord.DiscordClient;
#end
import flash.text.TextField;
import flixel.FlxG;
import flixel.FlxSprite;
import flixel.addons.display.FlxGridOverlay;
import flixel.group.FlxGroup.FlxTypedGroup;
import flixel.math.FlxMath;
import flixel.text.FlxText;
import flixel.util.FlxColor;
import flixel.addons.transition.FlxTransitionableState;
import flixel.tweens.FlxTween;
import flixel.tweens.FlxEase;
import flixel.input.mouse.FlxMouseEventManager;
#if MODS_ALLOWED
import sys.FileSystem;
import sys.io.File;
#end
import lime.utils.Assets;

using StringTools;

//indie cross codes was referenced when making this thank you brightfyre very kewl

class CreditsState extends MusicBeatState
{

	static final credits:Array<Array<String>> = [
		[
			'Elixio',
			"You WILL find true happiness.. you should LOVE yourself NOW!",
			'Director, Musician, Artist',
			"0",
			"https://www.youtube.com/c/Elixioo"
		],
		[
			'BeeBop', 
			"pothead hours", 
			"Artist", 
			"0", 
			"https://www.youtube.com/channel/UC0njvFS3Y4AjrFuRbMNEahw"
		]
	];

	var curSelected:Int = -1;

	private var grpOptions:FlxTypedGroup<Alphabet>;
	private var iconArray:Array<AttachedSprite> = [];
	private var creditsStuff:Array<Array<String>> = [];

	var bg:FlxSprite;
	var credsText:FlxSprite;
	var descText:FlxText;
	var intendedColor:Int;
	var colorTween:FlxTween;
	var descBox:AttachedSprite;

	var offsetThing:Float = -75;

	override function create()
	{
		#if desktop
		// Updating Discord Rich Presence
		DiscordClient.changePresence("lookin at the swaggy credits", null);
		#end

		transIn = FlxTransitionableState.defaultTransIn;
		transOut = FlxTransitionableState.defaultTransOut;

		FlxG.mouse.visible = true;

		persistentUpdate = true;
		bg = new FlxSprite().loadGraphic(Paths.image('creditsMenu/bgGradient'));
		add(bg);
		bg.screenCenter();

		credsText = new FlxSprite().loadGraphic(Paths.image('creditsMenu/teamText'));
		add(credsText);
		credsText.screenCenter();
	
	}
	
	
	override function update(elapsed:Float)
	{
		var elixioIcon = new FlxSprite(300, FlxG.height * 0.38).loadGraphic(Paths.image('creditsMenu/elixioIcon'));
		add(elixioIcon);

		var beebopIcon = new FlxSprite(735, FlxG.height * 0.38).loadGraphic(Paths.image('creditsMenu/beebopIcon'));
		add(beebopIcon);

		var quotes:FlxText = new FlxText(12, FlxG.height - 24, 0, "quote here", 12);
		quotes.setFormat("VCR OSD Mono", 16, FlxColor.WHITE, LEFT, FlxTextBorderStyle.OUTLINE, FlxColor.BLACK);
		add(quotes);

		
		if(FlxG.mouse.overlaps(beebopIcon)){
			if(FlxG.mouse.justPressed){
				PlayState.SONG = Song.loadFromJson('goofy-hard', 'goofy');
				LoadingState.loadAndSwitchState(new PlayState());
			}
		}

		if (FlxG.sound.music.volume < 0.7)
		{
			FlxG.sound.music.volume += 0.5 * FlxG.elapsed;
		}

		if (controls.BACK)
			{
				FlxG.sound.play(Paths.sound('cancelMenu'));
				MusicBeatState.switchState(new MainMenuState());
			}
	}
}`

How can I fix this, if I can?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Made a custom credit menu.

**Comment by MemeHoovy** [comment]
maybe not put these in override update, since that's where everything is constantly updated
```
	var elixioIcon = new FlxSprite(300, FlxG.height * 0.38).loadGraphic(Paths.image('creditsMenu/elixioIcon'));
	add(elixioIcon);

	var beebopIcon = new FlxSprite(735, FlxG.height * 0.38).loadGraphic(Paths.image('creditsMenu/beebopIcon'));
	add(beebopIcon);

	var quotes:FlxText = new FlxText(12, FlxG.height - 24, 0, "quote here", 12);
	quotes.setFormat("VCR OSD Mono", 16, FlxColor.WHITE, LEFT, FlxTextBorderStyle.OUTLINE, FlxColor.BLACK);
	add(quotes);
```
instead, move them to override create

**Comment by elixioo** [comment]
> maybe not put these in override update, since that's where everything is constantly updated
> 
> ```
> 	var elixioIcon = new FlxSprite(300, FlxG.height * 0.38).loadGraphic(Paths.image('creditsMenu/elixioIcon'));
> 	add(elixioIcon);
> 
> 	var beebopIcon = new FlxSprite(735, FlxG.height * 0.38).loadGraphic(Paths.image('creditsMenu/beebopIcon'));
> 	add(beebopIcon);
> 
> 	var quotes:FlxText = new FlxText(12, FlxG.height - 24, 0, "quote here", 12);
> 	quotes.setFormat("VCR OSD Mono", 16, FlxColor.WHITE, LEFT, FlxTextBorderStyle.OUTLINE, FlxColor.BLACK);
> 	add(quotes);
> ```
> 
> instead, move them to override create

When I do that, this piece of code breaks.
source/CreditsState.hx:102: characters 26-36 : Unknown identifier : beebopIcon
source/CreditsState.hx:102: characters 26-36 : For function argument 'ObjectOrGroup'


```
		if(FlxG.mouse.overlaps(beebopIcon)){
			if(FlxG.mouse.justPressed){
				PlayState.SONG = Song.loadFromJson('goofy-hard', 'goofy');
				LoadingState.loadAndSwitchState(new PlayState());
			}
```

**Comment by elixioo** [comment]
> > maybe not put these in override update, since that's where everything is constantly updated
> > ```
> > 	var elixioIcon = new FlxSprite(300, FlxG.height * 0.38).loadGraphic(Paths.image('creditsMenu/elixioIcon'));
> > 	add(elixioIcon);
> > 
> > 	var beebopIcon = new FlxSprite(735, FlxG.height * 0.38).loadGraphic(Paths.image('creditsMenu/beebopIcon'));
> > 	add(beebopIcon);
> > 
> > 	var quotes:FlxText = new FlxText(12, FlxG.height - 24, 0, "quote here", 12);
> > 	quotes.setFormat("VCR OSD Mono", 16, FlxColor.WHITE, LEFT, FlxTextBorderStyle.OUTLINE, FlxColor.BLACK);
> > 	add(quotes);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > instead, move them to override create
> 
> When I do that, this piece of code breaks. source/CreditsState.hx:102: characters 26-36 : Unknown identifier : beebopIcon source/CreditsState.hx:102: characters 26-36 : For function argument 'ObjectOrGroup'
> 
> ```
> 		if(FlxG.mouse.overlaps(beebopIcon)){
> 			if(FlxG.mouse.justPressed){
> 				PlayState.SONG = Song.loadFromJson('goofy-hard', 'goofy');
> 				LoadingState.loadAndSwitchState(new PlayState());
> 			}
> ```

WAIT NVM I GOT IT LOL TYTY

**Comment by elixioo** [comment]
.
