### ISSUE TITLE
fnf not loading anything i put in

### ISSUE THREAD

**Issue by sa3gaming** [ShadowMario/FNF-PsychEngine#10700]
### Describe your problem here.

PlayState.hx (line 2593)
PlayState.hx (line 2448)
PlayState.hx (line 1081)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Mastercopper2346** [comment]
Go to PlayState and the lines it tells you 🤦🏼

**Comment by sa3gaming** [comment]
FORGET imma use kade engine
