### ISSUE TITLE
Bringing back the judgement display next to gf like on vanilla fnf and older psych versions.

### ISSUE THREAD

**Issue by NukeThief** [ShadowMario/FNF-PsychEngine#10702]
### What feature do you want to get added on the **base** engine?

I really miss that. It'll be best to have that as an option for the ones who like it more on the hud cam.
![image](https://user-images.githubusercontent.com/81801547/193127325-8677dc35-c207-476d-b27b-6c97543a54c4.png)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by TheKitBoi** [comment]
Rejected + Not a good request

**Comment by MemeHoovy** [comment]
> ### What feature do you want to get added on the **base** engine?
> I really miss that. It'll be best to have that as an option for the ones who like it more on the hud cam. ![image](https://user-images.githubusercontent.com/81801547/193127325-8677dc35-c207-476d-b27b-6c97543a54c4.png)
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Stage Editor, 6K+ support, and winning icons.

no

**Comment by MemeHoovy** [comment]
> > Reference i
> 
> sonic exe hardcode simps: Gimme the fucking source code!!!!111!!!1111222

1. where did you even quote text that from?
2. https://github.com/DuskieWhy/exe-2.5-code source code for 2.5/3.0

**Comment by NukeThief** [comment]
> Too fucking easy to add:
> 
> 
> 
> Make sure you have the "comboSpr" NOT ON THE HUD.
> 
> Move it to where gf is.

But thats only with Source right?
