### ISSUE TITLE
How to modify the window name on downloaded build?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#1071]
### What is your question?

How to modify the window name on downloaded build?
![Snipaste_2021-11-16_22-05-35](https://user-images.githubusercontent.com/13177997/142001001-e4be9520-aba5-4271-b074-687dd51c69a3.png)

**Comment by FuseIsHere813** [comment]
Not possible, use source code to edit it.

**Comment by ShadowMario** [comment]
Project.xml file on Source Code
