### ISSUE TITLE
The crash in in recent version of Friday night funkin'

### ISSUE THREAD

**Issue by Junari10** [ShadowMario/FNF-PsychEngine#10718]
### Describe your bug here.

Everytime i try to spam it show the crash text

### Command Prompt/Terminal logs (if existing)

```bash
Paths.hx (line 352)
PlayState.hx (line 3983)
PlayState.hx (line 4485)
PlayState.hx (line 4157)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I not the helper of psych engine.

**Comment by MemeHoovy** [comment]
> ### Describe your bug here.
> Everytime i try to spam it show the crash text
> 
> ### Command Prompt/Terminal logs (if existing)
> ```shell
> Paths.hx (line 352)
> PlayState.hx (line 3983)
> PlayState.hx (line 4485)
> PlayState.hx (line 4157)
> openfl/events/EventDispatcher.hx (line 402)
> openfl/display/DisplayObject.hx (line 1399)
> 
> Uncaught Error: Null Object Reference
> Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine
> 
> > Crash Handler written by: sqirra-rng
> ```
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No I not the helper of psych engine.

skill issue

**Comment by Junari10** [comment]
Look I may have a skill issue but I am practicing

**Comment by Junari10** [comment]
Look I may be have a skill issue but I am trying hard

**Comment by frantastic24** [comment]
not a bug
missing rating textures

**Comment by MaybeMaru** [comment]
rip bozo
