### ISSUE TITLE
Problems to export

### ISSUE THREAD

**Issue by Carlnal** [ShadowMario/FNF-PsychEngine#10717]
### Describe your problem here.

When I export the game in the version 0.6.2 , the message appears:
source/FunkinLua.hx:593: lines 593-597 : Int should be Bool
source/FunkinLua.hx:593: lines 593-597 : ... For function argument 'f'

![f](https://user-images.githubusercontent.com/95714446/193358419-18bebc6b-ee8f-4199-af1a-4a6364ecf2d7.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHoovy** [comment]
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

**Comment by MemeHoovy** [comment]
> You don't have Nebulazorua's fork of Luajit.

that's what I said

**Comment by Carlnal** [comment]
> haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

What do I have to do?

**Comment by MemeHoovy** [comment]
> haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

run that command in a command prompt
