### ISSUE TITLE
CRASH ON SONG(S)

### ISSUE THREAD

**Issue by Ollieq1977336** [ShadowMario/FNF-PsychEngine#10725]
### Describe your bug here.

Hi. My game is crashing while going through the song i ported: "Splitathon". Its 10 Minutes and I HAVE NO IDEA whats causing it. Its even crashing through spammy songs. Its no lag but crashing alot.

### _**VIDEO LOW QUALITY DUE TO COMPRESSION!**_

The video is a playthrough of the song. It will crash at the end of the video.

https://user-images.githubusercontent.com/112081585/193399765-055e6e7e-c53a-4871-a473-9a17d6c09a9a.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited PlayState.hx and made a HEALTH and COMBO Counter for the song. I also made less botplay lag on spammy songs/All songs.

**Comment by MaybeMaru** [comment]
low quality? bitch this shit looks like it came out from an atari 2600

**Comment by KillerAvecRage** [comment]
Perfect video quality

**Comment by MemeHoovy** [comment]
nice potato computer

**Comment by Grape-Boy** [comment]
set your fps to 60 in options and/or have a script with just
```lua
function onUpdatePost() end
```
in it
