### ISSUE TITLE
Pixel Splash (not really a bug)

### ISSUE THREAD

**Issue by Mokona5901** [ShadowMario/FNF-PsychEngine#1072]
### Describe your bug here.

I just noticed that the sick note splash in week 6 isn't pixelated

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by HiroOfc** [comment]
bro, i noticed that too, i did pixel splashes in psych for me
hope they add this futurely
