### ISSUE TITLE
CAMERA shittt

### ISSUE THREAD

**Issue by Gurudevsing** [ShadowMario/FNF-PsychEngine#10728]
### Describe your problem here.

FUckingg cams
 the whole thing is moving  when focusing character TAKE A LOOKKKK 
https://user-images.githubusercontent.com/87480185/193348091-ee3f4741-19c1-4ece-b9f5-667753b812ad.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by LilDrippyMyFnf** [comment]
bruh really

**Comment by LilDrippyMyFnf** [comment]
that's cuz the camera is out too far

**Comment by MaybeMaru** [comment]
1. shit framerate and port
2. just set the scroll factor to 1

**Comment by Gurudevsing** [comment]
> 1. shit framerate and port
> 2. just set the scroll factot
thanks it worked but how do you know its 1, i mean it always be 1 or it will change for other bg

**Comment by Gurudevsing** [comment]
and tell me how to edit custom camera for individual character using .json [CAMERA FOUSING INDIVIDUAL CHARACTER]
and some lua code Thanks
