### ISSUE TITLE
How to disable secret title bump characters (aka "RiverBump" character bump)

### ISSUE THREAD

**Issue by HJacet** [ShadowMario/FNF-PsychEngine#10720]
### What is your question?

Is there a way to disable the secret title screen bumps for the title screen? I have a custom title bump but the secret ones load instead even if I have the mod pack that has the custom title bump turned on.

![Friday Night Funkin'_ Psych Engine 9_30_2022 5_48_32 PM](https://user-images.githubusercontent.com/106554377/193366784-9944752c-1501-45e4-8bba-d95a51ae24ac.png)

**Comment by HJacet** [comment]
> > You must be playing on a compiled build with this enabled.
> 
> Or you must be PLAYING the official build.

I am playing the official build, I just messed around with the secret things but now I just cant turn them off, I didn't mess around with any source code as well. If there's a way to turn them on there has to be a way to turn them off.

**Comment by impostor5875** [comment]
ik this is already closed but you type the thing again and it goes away
