### ISSUE TITLE
The MainMenuState

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10727]
### Describe your problem here.

I Want To Look Like This To My Engine:
![Screenshot_20221001-145923~2](https://user-images.githubusercontent.com/109828559/193410809-f8bbfe52-71c3-45c2-8bc0-94355dc63cb6.png)
I Just Want This. I Know Already How To Add The Animated Cubes On The MainMenuState.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, The MainMenuState.hx

**Comment by MaybeMaru** [comment]
os engine lol

**Comment by StefanBETA2008** [comment]
> os engine lol

Yeah, Yeah 🙄 , But Can You Help Me Or I Closing This

**Comment by StefanBETA2008** [comment]
Nevermind, I Fixed This
