### ISSUE TITLE
can you make your own crash screen?

### ISSUE THREAD

**Issue by cooldude47980597** [ShadowMario/FNF-PsychEngine#10723]
### What is your question?

can you make your own crash screen? i wanna make my own

**Comment by MemeHoovy** [comment]
you can modify the crash handler code in newer versions of psych engine

**Comment by cooldude47980597** [comment]
i cant compile source code

**Comment by MemeHoovy** [comment]
> i cant compile source code

well that's the only way to modify the crash handler
