### ISSUE TITLE
Titles are percentage signs instead of title name

### ISSUE THREAD

**Issue by adamsaustria** [ShadowMario/FNF-PsychEngine#10721]
### Describe your bug here.

Like the issue name says and it happens when I replace the whole image folder and I don’t know what image it’s changing

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

If you mean by source then no

**Comment by frantastic24** [comment]
that is a very vague description
did you replace alphabet.png, if so it's not a bug

**Comment by adamsaustria** [comment]
yes i did and how is it not a bug

**Comment by frantastic24** [comment]
You can edit it, if you fuck it up you get what you described
