### ISSUE TITLE
Guys, Error in FNF PSYCH ENGINE's new version

### ISSUE THREAD

**Issue by SapatoSemSola** [ShadowMario/FNF-PsychEngine#10734]
### Describe your bug here.

When I tried to add events (dadbattle spotlight and blammed glow) it crashed

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2496)
PlayState.hx (line 2425)
PlayState.hx (line 1053)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHoovy** [comment]
> ### Describe your bug here.
> When I tried to add events (dadbattle spotlight and blammed glow) it crashed
> 
> ### Command Prompt/Terminal logs (if existing)
> ```shell
> PlayState.hx (line 2496)
> PlayState.hx (line 2425)
> PlayState.hx (line 1053)
> flixel/FlxGame.hx (line 637)
> flixel/FlxGame.hx (line 724)
> flixel/FlxGame.hx (line 677)
> flixel/FlxGame.hx (line 551)
> openfl/events/EventDispatcher.hx (line 402)
> openfl/display/DisplayObject.hx (line 1399)
> 
> Uncaught Error: Null Object Reference
> Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine
> 
> > Crash Handler written by: sqirra-rng
> ```
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No

dadbattle spotlight only works in week 1 and philly glow only works in week 3

**Comment by SapatoSemSola** [comment]
> 

Thanks!!

**Comment by MemeHoovy** [comment]
> > 
> 
> Thanks!!

your welcome, now close the issue please
