### ISSUE TITLE
onStartCountdown + return Function_Stop = death

### ISSUE THREAD

**Issue by probablynotbetopia** [ShadowMario/FNF-PsychEngine#10732]
### Describe your bug here.

it's exactly what it sounds like

ok so on the latest action build (the playback rate one) when function_stopping countdown the game yells at me:
```
PlayState.hx (line 3180)
flixel/group/FlxGroup.hx (line 769)
PlayState.hx (line 3175)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
```
this would lead me to:
```hx
//PlayState, lines 3175 - 3180
notes.forEachAlive(function(daNote:Note)
{
          var strumGroup:FlxTypedGroup<StrumNote> = playerStrums;
          if(!daNote.mustPress) strumGroup = opponentStrums;

          var strumX:Float = strumGroup.members[daNote.noteData].x;
```
which blames the strum group(s) for it (they dont exist until the countdown starts so theyre all null causing the n.o.r)
but like why is it only happening now???? this piece of code has remained unchanged for a long long time and its only reacting just now??
i know how to fix this, i made this issue just to let you know about this bug

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

n

**Comment by MemeHoovy** [comment]
why does haxe gotta be so fucking weird?

**Comment by probablynotbetopia** [comment]
> why does haxe gotta be so fucking weird?

idk
