### ISSUE TITLE
Accuracy refreshes later than usual

### ISSUE THREAD

**Issue by KillerAvecRage** [ShadowMario/FNF-PsychEngine#10738]
### Describe your bug here.

I've been noticing this bug for quite a moment for now and it's really weird:

https://user-images.githubusercontent.com/103606542/193447398-232a872e-74f0-4be6-9ce7-3baeb0fc7448.mp4

![Souci](https://user-images.githubusercontent.com/103606542/193447413-800de806-882b-4173-8a81-a529b9266082.PNG)

All notes have a 1 hit delay before they count in the accuracy and only the accuracy has this problem as you can see with the image.

If you got any help with this that would be very appreciated.

Thank you in advance.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I've put custom ratings to match Robeats' ratings

**Comment by ManMaster707** [comment]
have you checked the accuracy lua script to see if anything's wrong?

**Comment by KillerAvecRage** [comment]
There isn't that much and I think I've done it correctly, here is the script though:

```
function onUpdate()
if getProperty('ratingPercent') > 0.955 then
	setRatingName('A+')
elseif getProperty('ratingPercent') > 0.875 then
	setRatingName('A')
elseif getProperty('ratingPercent') > 0.75 then
	setRatingName('B')
elseif getProperty('ratingPercent') > 0.575 then
	setRatingName('C')
elseif getProperty('ratingPercent') > 0 then
	setRatingName('F')
end
end
```

**Comment by BeastlyGhost** [comment]
instead on `onUpdate`, use `onUpdateScore`

**Comment by KillerAvecRage** [comment]
> instead on `onUpdate`, use `onUpdateScore` or `onRecalculateRating`

It doesn't fix the issue unfortunately, might dig further though to see if I can fix this

**Comment by KillerAvecRage** [comment]
Well I didn't find anything, however I noticed that the "ratingPercent" property gets refreshed correctly

**Comment by KillerAvecRage** [comment]
I just tried source code and the first thing I've changed is the ratings

And it still refreshes later than usual, I don't know what I should do
