### ISSUE TITLE
Where to you put special note sprite ?

### ISSUE THREAD

**Issue by Mokona5901** [ShadowMario/FNF-PsychEngine#1074]
### What is your question?

Where do you have to put special note sprite ?
In mods/custom_notetypes folder ?

**Comment by Real-Pog** [comment]
no
you put what the note does in mods/custom/notetypes folder you should put the xml and image of your custom note in
mods/images

**Comment by FuseIsHere813** [comment]
what was with the reopen?

**Comment by ShadowMario** [comment]
> what was with the reopen?

He probably closed it in accident.

Anyway, the question seems to have been resolved, so i will close it again.
