### ISSUE TITLE
Tweening setting positions correctly

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#10744]
### What is your question?

does tweening actually set the position/scale/etc vaule of what you're tweening?

**Comment by frantastic24** [comment]
Yes

**Comment by TFLTV** [comment]
> Yes

Just tested it...  This leads to a lot of opportunities, last time I checked (I was using 0.5.2h) it didn't work.

**Comment by frantastic24** [comment]
Tweens didn't change afaik, they are handled by haxe, not psych after all

**Comment by TFLTV** [comment]
> 

hmm...  Maybe I was just so bad at coding I couldn't do it, somehow.

**Comment by TFLTV** [comment]
> > 
> 
> hmm... Maybe I was just so bad at coding I couldn't do it, somehow.

Or, maybe it was because I didn't the current version of Haxe I'm using right now...  Idk.
