### ISSUE TITLE
Strange song glitch

### ISSUE THREAD

**Issue by Fronekowy** [ShadowMario/FNF-PsychEngine#10745]
### Describe your problem here.

So I have this strange song glitch were the chart is looping on itself and you can't do pretty much anything. If someone knows how to fix it it would be helpful.
https://user-images.githubusercontent.com/77848995/193474036-fa4a1e72-2fbc-4df0-90f3-bc8c32aba5b4.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TFLTV** [comment]
I happened before to me because there was no `Inst.ogg` and `Voices.ogg`
inside the `songs` folder

**Comment by Fronekowy** [comment]
> this happened to me before to me because there was no `Inst.ogg` and `Voices.ogg` inside the `songs` folder

I have an isn't and I disabled voices!

**Comment by TFLTV** [comment]
> > this happened to me before to me because there was no `Inst.ogg` and `Voices.ogg` inside the `songs` folder
> 
> I have an Inst.ogg and I disabled voices!

Welp, I don't have another solution...

**Comment by Fronekowy** [comment]
And if that could help there is the mod folder!
[Uploading help.zip…]()

**Comment by frantastic24** [comment]
Re-export your instrumental, the game can't read it

**Comment by Fronekowy** [comment]
[help.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/9693428/help.zip)

**Comment by Fronekowy** [comment]
> Re-export your instrumental, the game can't read it

Re-export?

**Comment by frantastic24** [comment]
Convert it into .ogg again

**Comment by Fronekowy** [comment]
Ok

**Comment by Fronekowy** [comment]
Fixed it
