### ISSUE TITLE
Can't access freeplay and story mode

### ISSUE THREAD

**Issue by Ethian876** [ShadowMario/FNF-PsychEngine#10746]
### Describe your bug here.

I can't go in freeplay everytime i do I shows me this: 
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 318)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 147)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 117)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 117)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 90)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
WeekData.hx (line 222)
WeekData.hx (line 190)
WeekData.hx (line 178)
FreeplayState.hx (line 60)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid char 125 at position 353

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

only in mods folder

**Comment by frantastic24** [comment]
Not a bug
Broken week file

**Comment by Ethian876** [comment]
what does a broken week file look like?

**Comment by frantastic24** [comment]
It could look like anything if it's just a syntax error, you should just make a new one

**Comment by Ethian876** [comment]
oh ok thx frantastic
