### ISSUE TITLE
Character issue

### ISSUE THREAD

**Issue by Teddythedev0** [ShadowMario/FNF-PsychEngine#10747]
### Describe your problem here.

The character i made in psych engine turns into a haxeflixel logo when i load it from the chart editor.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CrusherNotDrip** [comment]
Missing Texture

**Comment by Teddythedev0** [comment]
how do you replace it?

**Comment by MemeHoovy** [comment]
> how do you replace it?

the texture files for the character are missing, you didn't add the textures or something is wrong with your characters xml file
