### ISSUE TITLE
source code to lua

### ISSUE THREAD

**Issue by hotpocketsarepoggers** [ShadowMario/FNF-PsychEngine#10743]
### Describe your problem here.

so I found this bit of source code that I managed to get to work in lua
```
                                        case 372:

						FlxTween.tween(BGflash, {alpha: 1.0}, 0.2, 
							{ease: FlxEase.expoOut});

					case 373:

						FlxTween.tween(BGflash, {alpha: 0.0}, 0.8, 
							{ease: FlxEase.quadInOut});

```
but im trying to get this also to work in lua but I cant get it to work(yes I looked at the timer section in the lua  api)
```
	/*		BGflash.alpha = 1;
						new FlxTimer().start(0.1, function(tmr:FlxTimer)
							{
								BGflash.alpha -= 0.10;
					
								if (BGflash.alpha > 0)
								{
									
									tmr.reset(0.1);
								}
							});    */
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Make the same timer run again if the alpha is higher than 0

**Comment by MemeHoovy** [comment]
> doesnt runHaxeCode exist?

yes
