### ISSUE TITLE
Using arrays in lua crashes the game

### ISSUE THREAD

**Issue by Minecrafter615** [ShadowMario/FNF-PsychEngine#10749]
### Describe your bug here.

Trying to call or make an array using lua will crash the game.

For reference,

```
function onCreate()
array = {}
end
```

will crash immediately. Using onSongStart for example will crash the game once the song starts.

If you place the `array = {}` outside of a function, the game won't crash, but the array won't exist.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, this is all base v0.6.2

**Comment by Lorekeeper49** [comment]
It looks to be crashing because you're not doing this
```lua
local array = {};
