### ISSUE TITLE
Crash in the middle of a song when you try to change the arrows and everything to pixel or so I think

### ISSUE THREAD

**Issue by DierdixYT** [ShadowMario/FNF-PsychEngine#10742]
### Describe your bug here.

Hello, well, my Psych engine crashes in the middle of a song and it has happened to me in two songs so far and they have something in common that they try to change the arrows to pixel and other things to pixel mode, in case you are wondering, I have not changed anything from the source , I get the following error when crashing:
PlayState.hx (line 3076)
flixel/group/FlxGroup.hx (line 769)
PlayState.hx (line 3031)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No i didnt

**Comment by Username2120** [comment]
as far as i know you can only change things that are pixel specific (such as pixel note skins)  if "isPixelStage" is set to true.
looks something like this,
	`"isPixelStage": true`
it should be inside any stages JSON file and im not to sure if its changeable mid song by using the "setProperty" commend in Lua scripting
