### ISSUE TITLE
Bug for Mac Build

### ISSUE THREAD

**Issue by HazardRail** [ShadowMario/FNF-PsychEngine#10751]
### Describe your bug here.

I don't know what this means

### Command Prompt/Terminal logs (if existing)

```bash
Note.hx (line 158)
PlayState.hx (line 2495)
PlayState.hx (line 1084)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by cooldude47980597** [comment]
Note.hx (line 158)
PlayState.hx (line 2495)
PlayState.hx (line 1084)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
go to your drive then go to the files fixel and openfl edit the files

**Comment by MemeHoovy** [comment]
> Note.hx (line 158) PlayState.hx (line 2495) PlayState.hx (line 1084) flixel/FlxGame.hx (line 637) flixel/FlxGame.hx (line 724) flixel/FlxGame.hx (line 677) flixel/FlxGame.hx (line 545) openfl/events/EventDispatcher.hx (line 402) openfl/display/DisplayObject.hx (line 1399) go to your drive then go to the files fixel and openfl edit the files

they're using lua

**Comment by MemeHoovy** [comment]
> ### Describe your bug here.
> I don't know what this means
> 
> ### Command Prompt/Terminal logs (if existing)
> ```shell
> Note.hx (line 158)
> PlayState.hx (line 2495)
> PlayState.hx (line 1084)
> flixel/FlxGame.hx (line 637)
> flixel/FlxGame.hx (line 724)
> flixel/FlxGame.hx (line 677)
> flixel/FlxGame.hx (line 545)
> openfl/events/EventDispatcher.hx (line 402)
> openfl/display/DisplayObject.hx (line 1399)
> 
> Uncaught Error: Null Object Reference
> ```
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Mac
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> no

this leads to ```noteSplashHue = colorSwap.hue;``` does your note textures or whatever exist?
