### ISSUE TITLE
Click something in the BG to access a secret song

### ISSUE THREAD

**Issue by Aidenkp112** [ShadowMario/FNF-PsychEngine#10754]
### What is your question?

So back when discussions got deleted and i just stayed on mayos discussions for psych engine, i saw a bg click thingy just like the title, but now i cant find the thing anymore bc i cant find the resporijjrj however u spell it whatever anyways

so yeah im looking for a script of a bg click thing and all i need is code and i'll use 10 minutes prob of my life trying to put it in the correct area cus im stupid

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#mouse-click-functions

**Comment by Aidenkp112** [comment]
im bad at lua so i would like a script and then i'll fix the problems i find or smh idk

**Comment by frantastic24** [comment]
No don't ask people to code for you

**Comment by Aidenkp112** [comment]
:|

**Comment by Noel3454565FNF** [comment]
did someone find how?
if yes can i know how please?

(discord: NOEL#4280)
