### ISSUE TITLE
[READ BEFORE OPENING ISSUES] BEGINNERS GUIDE FOR COMPILING (ERROR FIXES)

### ISSUE THREAD

**Issue by BeastlyGhost** [ShadowMario/FNF-PsychEngine#10756]
## MAIN COMPILING

Download [this setup file](https://cdn.discordapp.com/attachments/931776548250468382/1004049224616378439/setup.bat) and execute it, follow the steps accordingly in order to compile the game

([for Linux / Mac](https://cdn.discordapp.com/attachments/931776548250468382/1004049224926773278/setup.sh))

## ERROR FIXES

all of these need a terminal / command prompt open, so get ready to type stuff

Press Windows+R and type "cmd"
if you are on Linux, just refer to your Desktop Environment's keybinds to open a new terminal (usually Ctrl+Shift+T)

...or launch it from your start menu

> "Library not found: hxCodec" | "Invalid Class: MP4Handler" FIX

type the following commands
`haxelib remove hxCodec`
`haxelib install hxCodec`

> LUA RELATED ERRORS (mainly FunkinLua.hx returning errors)

type the following
`haxelib remove linc_luajit`
`haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit`

> HXCPP_MSVC_CUSTOM ERROR (This is WINDOWS only error)

**NOTICE: you need git installed in order for the next commands to work**

type the following

`curl -# -O https://download.visualstudio.microsoft.com/download/pr/3105fcfe-e771-41d6-9a1c-fc971e7d03a7/8eb13958dc429a6e6f7e0d6704d43a55f18d02a253608351b6bf6723ffdaf24e/vs_Community.exe`

`vs_Community.exe --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.19041 -p`

`del vs_Community.exe`

NOTICE: if `del vs_Community.exe` returns an error, simply delete the file manually

**Comment by MemeHoovy** [comment]
this is for linux though

**Comment by BeastlyGhost** [comment]
> this is for linux though

it's not

**Comment by MemeHoovy** [comment]
```
curl -# -O https://download.visualstudio.microsoft.com/download/pr/3105fcfe-e771-41d6-9a1c-fc971e7d03a7/8eb13958dc429a6e6f7e0d6704d43a55f18d02a253608351b6bf6723ffdaf24e/vs_Community.exe
```

**Comment by MemeHoovy** [comment]
that's a linux command

**Comment by BeastlyGhost** [comment]
> ```
> curl -# -O https://download.visualstudio.microsoft.com/download/pr/3105fcfe-e771-41d6-9a1c-fc971e7d03a7/8eb13958dc429a6e6f7e0d6704d43a55f18d02a253608351b6bf6723ffdaf24e/vs_Community.exe
> ```

curl works on windows

**Comment by MemeHoovy** [comment]
does it though?

**Comment by MemeHoovy** [comment]
how do you know that?

**Comment by BeastlyGhost** [comment]
it does, just try it

**Comment by BeastlyGhost** [comment]
> how do you know that?

I tried doing the command in the first place, it works

**Comment by MemeHoovy** [comment]
well I'll be damned, it does work

**Comment by MemeHoovy** [comment]
I think, the installer didn't show up

**Comment by BeastlyGhost** [comment]
> I think, the installer didn't show up though

it takes a bit depending on your system, but it works

**Comment by MemeHoovy** [comment]
> > I think, the installer didn't show up though
> 
> it takes a bit depending on your system, but it works

it's been a full 2 and a half minutes and it's still not there

**Comment by MemeHoovy** [comment]
> did you use the next command after `curl`?

no I didn't do that but I just did and it showed up

**Comment by cooldude47980597** [comment]
does it work on mac because lime test mac

**Comment by BeastlyGhost** [comment]
> does it work on mac because lime test mac

it works on every platform

**Comment by cooldude47980597** [comment]
but theres no psych engine mac verison on the gamebanana

**Comment by BeastlyGhost** [comment]
doesn't matter, this is for fixing *compiling* errors

**Comment by cooldude47980597** [comment]
💀

**Comment by StefanBETA2008** [comment]
O Wow

**Comment by UsNoobs** [comment]
i get this
source/FunkinLua.hx:346: lines 346-350 : Int should be Bool
source/FunkinLua.hx:346: lines 346-350 : For function argument 'f'

**Comment by MemeHoovy** [comment]
> haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

**Comment by UsNoobs** [comment]
nvm works now

**Comment by MemeHoovy** [comment]
bruh

**Comment by cooldude47980597** [comment]
>nvm works now

Guy acts like it’s twitter

**Comment by sans400** [comment]
![Screenshot 2022-10-18 104303](https://user-images.githubusercontent.com/78706113/196464265-3e5e8cc0-6016-42fc-87d6-dd60f11c8940.png)
I Just Downloaded It, Why Does This Keep Happening?

**Comment by sans400** [comment]
This Happens Everytime With 0.6.0's Updates.

**Comment by cooldude47980597** [comment]
oh fuck it happen to me

**Comment by sans400** [comment]
Did You Find A Fix For It?

**Comment by sans400** [comment]
That Did Not Work, And I Got Hit With More Errors
![Screenshot 2022-10-24 201344](https://user-images.githubusercontent.com/78706113/197657334-cfa58ce1-72f7-485d-a1a9-7798c8ddd66b.png)

**Comment by UncertainProd** [comment]
> ![Screenshot 2022-10-18 104303](https://user-images.githubusercontent.com/78706113/196464265-3e5e8cc0-6016-42fc-87d6-dd60f11c8940.png) I Just Downloaded It, Why Does This Keep Happening?

Which version of haxe and haxeflixel are you using?

**Comment by sans400** [comment]
Haxe 4.2.4.

**Comment by sans400** [comment]
Ok I'll Try That.

**Comment by MemeHoovy** [comment]
and make sure your using flixel 4.11.0

**Comment by sans400** [comment]
My Flixel Version Is The Latest Update. So WHAT'S GOING ON HERE?

**Comment by sans400** [comment]
Is There A Typo? I Tried It. And This Popped Up.
![Screenshot 2022-10-25 133200](https://user-images.githubusercontent.com/78706113/197842713-df3ce036-f5f7-4690-969b-60841f739ed1.png)

**Comment by MemeHoovy** [comment]
> Is There A Typo? I Tried It. And This Popped Up. ![Screenshot 2022-10-25 133200](https://user-images.githubusercontent.com/78706113/197842713-df3ce036-f5f7-4690-969b-60841f739ed1.png)

haxelib update flixel you dumbass

**Comment by sans400** [comment]
F***ING FINALLY! Thanks So Much!

**Comment by sans400** [comment]
Apparently Flixel WASN'T 4.11.0

**Comment by cooldude47980597** [comment]
> > Is There A Typo? I Tried It. And This Popped Up. ![Screenshot 2022-10-25 133200](https://user-images.githubusercontent.com/78706113/197842713-df3ce036-f5f7-4690-969b-60841f739ed1.png)
> 
> haxelib update **flixel** you dumbass

ok idoit

**Comment by MemeHoovy** [comment]
> > > Is There A Typo? I Tried It. And This Popped Up. ![Screenshot 2022-10-25 133200](https://user-images.githubusercontent.com/78706113/197842713-df3ce036-f5f7-4690-969b-60841f739ed1.png)
> > 
> > 
> > haxelib update **flixel** you dumbass
> 
> ok idoit

the only idiot here is you

**Comment by cooldude47980597** [comment]
> > > > Is There A Typo? I Tried It. And This Popped Up. ![Screenshot 2022-10-25 133200](https://user-images.githubusercontent.com/78706113/197842713-df3ce036-f5f7-4690-969b-60841f739ed1.png)
> > > 
> > > 
> > > haxelib update **flixel** you dumbass
> > 
> > 
> > ok idoit
> 
> the only idiot here is you

wait you donnt even put issues on my engine..SO EVERYTHING IS FINE WITH IT????/

**Comment by MemeHoovy** [comment]
> > > > > Is There A Typo? I Tried It. And This Popped Up. ![Screenshot 2022-10-25 133200](https://user-images.githubusercontent.com/78706113/197842713-df3ce036-f5f7-4690-969b-60841f739ed1.png)
> > > > 
> > > > 
> > > > haxelib update **flixel** you dumbass
> > > 
> > > 
> > > ok idoit
> > 
> > 
> > the only idiot here is you
> 
> wait you donnt even put issues on my engine..SO EVERYTHING IS FINE WITH IT????/

I don't even care about your engine, your just a total dumbass

**Comment by cooldude47980597** [comment]
> > > > > > Is There A Typo? I Tried It. And This Popped Up. ![Screenshot 2022-10-25 133200](https://user-images.githubusercontent.com/78706113/197842713-df3ce036-f5f7-4690-969b-60841f739ed1.png)
> > > > > 
> > > > > 
> > > > > haxelib update **flixel** you dumbass
> > > > 
> > > > 
> > > > ok idoit
> > > 
> > > 
> > > the only idiot here is you
> > 
> > 
> > wait you donnt even put issues on my engine..SO EVERYTHING IS FINE WITH IT????/
> 
> I don't even care about your engine, your just a total dumbass

dude im sorry

**Comment by MemeHoovy** [comment]
> > > > > > > Is There A Typo? I Tried It. And This Popped Up. ![Screenshot 2022-10-25 133200](https://user-images.githubusercontent.com/78706113/197842713-df3ce036-f5f7-4690-969b-60841f739ed1.png)
> > > > > > 
> > > > > > 
> > > > > > haxelib update **flixel** you dumbass
> > > > > 
> > > > > 
> > > > > ok idoit
> > > > 
> > > > 
> > > > the only idiot here is you
> > > 
> > > 
> > > wait you donnt even put issues on my engine..SO EVERYTHING IS FINE WITH IT????/
> > 
> > 
> > I don't even care about your engine, your just a total dumbass
> 
> dude im sorry

it's fine

**Comment by cooldude47980597** [comment]
i fucking hate mythslist hes so fucking annoying on gamebanana

**Comment by BeastlyGhost** [comment]
done, you can lock this again
