### ISSUE TITLE
MissingNo "Modchart"

### ISSUE THREAD

**Issue by Fronekowy** [ShadowMario/FNF-PsychEngine#10759]
### What is your question?

Someone knows how to make a MissingNo modchart that randomized notes placement every 10-20 seconds (or just tell me a good way to randomize numbers)

**Comment by frantastic24** [comment]
getRandomInt

**Comment by Fronekowy** [comment]
> getRandomInt

Let me try that

**Comment by Fronekowy** [comment]
Hmmm

**Comment by Fronekowy** [comment]
It's works

**Comment by Fronekowy** [comment]
But thanks
