### ISSUE TITLE
The variable checking the note splash option

### ISSUE THREAD

**Issue by Draconic-Hybrid** [ShadowMario/FNF-PsychEngine#10757]
### What is your question?

Is the variable for checking the Note Splash option 'noteSplashes'? Because I don't get anything when putting it in `debugPrint()`. If that isn't the variable, what is it?

**Comment by kingyomoma** [comment]
`getPropertyFromClass('ClientPrefs', 'noteSplashes')`

**Comment by Draconic-Hybrid** [comment]
Thanks!
