### ISSUE TITLE
crash log not showing a file location 

### ISSUE THREAD

**Issue by Flubbedsoda6010** [ShadowMario/FNF-PsychEngine#10752]
### Describe your problem here.

while i was trying to rechart the official game 
i kept getting this crash 
[PsychEngine_2022-10-03_20'47'17.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9697637/PsychEngine_2022-10-03_20.47.17.txt)
this thing is annoys me so hard and im trying to fix it but i don't have time to do that cuz im just 14 
i dont know if it was a bug so i setted this as a help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Broken week file

**Comment by Flubbedsoda6010** [comment]
mine was actually missing
