### ISSUE TITLE
How to change note transparency, but without changing the strums'

### ISSUE THREAD

**Issue by NickPotato** [ShadowMario/FNF-PsychEngine#10769]
### Describe your problem here.

I'd like to change the transparency of all of the notes in a song, but I wanna keep the strums visible since I don't wanna change their transparency, is it possible to do this with only Lua?
I've tried messing with setPropertyFromGroup(), but I can't find the right variables in PlayState.hx, or I just don't know how to use it properly

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
If you just want them to be invisible you can just set `visible` to false
If you for some reason need to change their alpha first you need to disable `copyAlpha` for each note, then change `alpha`

**Comment by NickPotato** [comment]
It worked! Thanks a lot man
Didn't even know copyAlpha was a thing
