### ISSUE TITLE
Modchart storage ?

### ISSUE THREAD

**Issue by Shaggers-official** [ShadowMario/FNF-PsychEngine#10763]
### What is your question?

Can we have like, a place where we could find custom modcharts, like a bank of modcharts available for everyone, so like people that doesn't have any modcharting skills (like i do cuz i'm bad with math) can find modcharts that they would like to use for their mods and get inspirations(?) from those.

**Comment by Fronekowy** [comment]
That's a nice idea

**Comment by MemeHoovy** [comment]
just go search on gamebanana

**Comment by CaptainBaldi** [comment]
so basically discussions but even worse

**Comment by MemeHoovy** [comment]
> That's a nice idea

no it's not

**Comment by TheKitBoi** [comment]
> ### What is your question?
> Can we have like, a place where we could find custom modcharts, like a bank of modcharts available for everyone

Just go here to find crap
https://github.com/Theoyeah/PsychEngineDiscussions/discussions
