### ISSUE TITLE
Detect when a specific note type is missed

### ISSUE THREAD

**Issue by KalashniPepsi** [ShadowMario/FNF-PsychEngine#10761]
### Describe your problem here.

how do i detect when a specific note typed is missed? trynna make a thing happen when it does.
(If you tell me to use the sonic.exe source code i swear to god i'll punt you, those notes are broken)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

ChartingState, Playstate, and Note

**Comment by MemeHoovy** [comment]
put this under noteMiss
```
if (daNote.noteType == 'yournotetype') {
      // insert code
}
```

**Comment by KalashniPepsi** [comment]
> put this under noteMiss
> 
> ```
> if (daNote.noteType == 'yournotetype') {
>       // insert code
> }
> ```

didnt do anything

**Comment by KalashniPepsi** [comment]
> if (daNote.noteType == 'yournotetype') {
>       // insert code
> }

damn. aight hold on lemme try something real quick. no one close this

**Comment by KalashniPepsi** [comment]
> I've tried something like this before and I'm pretty sure it worked for me

hold on, which noteMiss? it appears like 7 times

**Comment by MemeHoovy** [comment]
```
function noteMiss(daNote:Note):Void { //You didn't hit the key and let it go offscreen, also used by Hurt Notes
```

**Comment by MemeHoovy** [comment]
put it under that

**Comment by MemeHoovy** [comment]
example code from demolition engine
![Screenshot 2022-10-04 125410](https://user-images.githubusercontent.com/97995998/193880097-b3a35f06-88cd-4c2e-a7d4-04157fe11751.png)

**Comment by KalashniPepsi** [comment]
> if (daNote.noteType == 'yournotetype') {
> // insert code
> }

I tried to test it by programming the note to close the game with Sys.exit(0); but nothing happened. game continued as if i just missed a normal note.

**Comment by MemeHoovy** [comment]
did you put it where I showed you in the picture?

**Comment by KalashniPepsi** [comment]
> did you put it where I showed you in the picture?

yeah, exactly like that

**Comment by KalashniPepsi** [comment]
> well idk, it's just how psych engine works or something
