### ISSUE TITLE
Setting the Camera X and Y position (target) for a duration of time

### ISSUE THREAD

**Issue by Troystar23** [ShadowMario/FNF-PsychEngine#10764]
### Describe your problem here.

I have sadly just found out the that camerasettarget only works on bf and dad so that ruined my plan that I had (was going to set it to gf), I'm currently unsure though if its possible to set the cameras x and y position to the middle of the screen so that the camera is nor targeted on bf or dad it is focused in-between them (on nothing) and set it there for 4 seconds. I'm completely lost on how I would do it and if it is even possible. So once again I'm asking for anyone's help, please prove me wrong I'm really hoping its possible, thanks in advance.

LUA Preferably as my Source compiling is broken right now but if you only know source code please feel free to leave your suggestion down anyways, thanks.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
There is an event specifically for this

**Comment by Troystar23** [comment]
> There is an event specifically for this

I didnt think that it worked because of the fact that every time I used it it sent the camera to the top left but I just needed to set the X and Y really high for me to actually see a difference thanks for commenting so quick and helping me out it was right in front of me the whole time....Thanks again! 👍
