### ISSUE TITLE
Freeplay doesn't work

### ISSUE THREAD

**Issue by Reeactor** [ShadowMario/FNF-PsychEngine#10767]
### Describe your bug here.

I tried accessing freeplay on hokens rtx utau mod but I got this message when i clicked on freeplay:
FreeplayState.hx (line 160)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Command Prompt/Terminal logs (if existing)

```bash
FreeplayState.hx (line 160)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added every folder from psych engine except for the mods folder to this mod since it was just a mods folder mod

**Comment by CaptainBaldi** [comment]
this isnt a base psych bug this is the mod's fault
