### ISSUE TITLE
good idea

### ISSUE THREAD

**Issue by cooldude47980597** [ShadowMario/FNF-PsychEngine#10768]
### What feature do you want to get added on the **base** engine?

Add a feature where you can customzie your mouse

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MemeHoovy** [comment]
no

**Comment by cooldude47980597** [comment]
memehoovy always commets

**Comment by TheKitBoi** [comment]
Man just
https://github.com/ShadowMario/FNF-PsychEngine/issues/10256

**Comment by CaptainBaldi** [comment]
this idea is worthless

**Comment by CrusherNotDrip** [comment]
This is absolutely **useless** because the only thing your gonna need to click is stuff in Character Editor and Charting and other editors, That's it. Unless there is a game mechanic involving your mouse like that one bbpanzu mod but still a useless feature.

**Comment by cooldude47980597** [comment]
> this idea is worthless

WHY DO YOU FOLLOW ME EVERYWERE I GO

**Comment by CrusherNotDrip** [comment]
> WHY DO YOU FOLLOW ME EVERYWERE I GO

because he is in your walls

**Comment by TheGithubPsychEngineFan** [comment]
I am legit gonna make this real, I just need to know how to change the mouse skin.

**Comment by MemeHoovy** [comment]
> I am legit gonna make this real, I just need to know how to change the mouse skin.

https://github.com/ShadowMario/FNF-PsychEngine/issues/10256

**Comment by cooldude47980597** [comment]
complain all day idc

**Comment by tylerandari12** [comment]
`getMouseX()`
`getMouseY()`
add an image
boom custom mouse

**Comment by cooldude47980597** [comment]
your fucking useless

**Comment by TheKitBoi** [comment]
> your fucking useless

you act like this is twitter
