### ISSUE TITLE
how do i make hud like mcm (source code only)

### ISSUE THREAD

**Issue by Taetek** [ShadowMario/FNF-PsychEngine#10770]
### What is your question?

how would i do this 
![image](https://user-images.githubusercontent.com/113743064/194166461-0ae4bd82-7851-4442-b831-35682d9ec737.png)
source code only

**Comment by MemeHoovy** [comment]
https://github.com/pahaze/Mistful-Crimson-Morning

**Comment by MemeHoovy** [comment]
it's all lua

**Comment by MemeHoovy** [comment]
but if want source code https://github.com/xenkap/IceEngine

**Comment by Taetek** [comment]
thanks bruv
