### ISSUE TITLE
all fonts trun to ###

### ISSUE THREAD

**Issue by bz001** [ShadowMario/FNF-PsychEngine#10777]
### Describe your problem here.

i was porting a mod,but then i found that the all fonts trun to ###,such as the 'GAMEPLAY' trun to '########' in the options,did u know how can i fix it, thanks!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by bz001** [comment]
here's the image:https://ibb.co/C2LGmPC

**Comment by bz001** [comment]
here's the image that u need to look:https://ibb.co/yQL0yyy

**Comment by CaptainBaldi** [comment]
probably related to the new alphabet system if ur using newer actions, replace the current alphabet image you have with the one from actions

**Comment by StefanBETA2008** [comment]
Yeah. ShadowMario Has Maked The New Alphabet System. It's W.I.P Or Else, Work In Progress.

**Comment by StefanBETA2008** [comment]
> here's the image:https://ibb.co/C2LGmPC

Dude, You Can Upload The Image Here 😑
