### ISSUE TITLE
The **** To My Version Image Problem

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10772]
### Describe your bug here.

I Just Try To Edit The **** To My Version And I Got This Error
![freak](https://user-images.githubusercontent.com/109828559/194226412-9c59aec2-45c3-4940-ab56-a9e1f8de8a25.png)

### Command Prompt/Terminal logs (if existing)

```bash
/opt/hostedtoolcache/haxe/4.2.5/x64/std/cpp/_std/Reflect.hx (Linija 41)
Conductor.hx (Linija 182)
PlayState.hx (Linija 4372)
PlayState.hx (Linija 4963)
PlayState.hx (Linija 3459)
flixel/group/FlxGroup.hx (Linija 769)
PlayState.hx (Linija 3383)
flixel/FlxState.hx (Linija 203)
flixel/FlxGame.hx (Linija 747)
flixel/FlxGame.hx (Linija 677)
flixel/FlxGame.hx (Linija 551)
openfl/events/EventDispatcher.hx (Linija 402)
openfl/display/DisplayObject.hx (Linija 1399)

Uncaught Error: Invalid field:freaks
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

For Now I Didn't Edit Nothing

**Comment by MemeHoovy** [comment]
so, all you did was try to edit the shit rating?

**Comment by StefanBETA2008** [comment]
> If You See: "Linija", Just Ignore. It's From My Engine

I Will Translate:
"Line"

**Comment by StefanBETA2008** [comment]
> so, all you did was try to edit the shit rating?

Yeah

**Comment by MemeHoovy** [comment]
no it already is, if you only just edited the png then you don't need to do anything there

**Comment by StefanBETA2008** [comment]
> no it already is, if you only just edited the png then you don't need to do anything there

I Just Tested The My Build On Android, But It's Same Error

**Comment by MemeHoovy** [comment]
I don't have an android btw, so I can't really do much :/

**Comment by MemeHoovy** [comment]
albeit I do have bluestacks

**Comment by StefanBETA2008** [comment]
And + I Just Edited The Three, Two, Go And It's Work, But Rating It's Problem When The Boyfriend Has Touched The Notes

**Comment by StefanBETA2008** [comment]
> albeit I do have bluestacks

Nevermind, I Will Close Issue :(
