### ISSUE TITLE
how to use onTweenCompleted()

### ISSUE THREAD

**Issue by ProbablyKam** [ShadowMario/FNF-PsychEngine#10771]
### What is your question?

I'm trying to make a mod chart and I want to make the notes move one after another like a wave but I don't know how to use onTweenCompleted() so I can't. Please reply if you know how.

**Comment by bruh1cat** [comment]
function onTweenCompleted(tag)
if tag == 'name' then
--insert code

**Comment by Draconic-Hybrid** [comment]
If you want to make a loop, go with something like

```
function onTweenCompleted(tag)
    if tag == '[first tag]' then
        [tween with second tag]
    end

    if tag == '[second tag]' then
        [tween with second tag]
    end
end
```

**Comment by ProbablyKam** [comment]
@Draconic-Hybrid Thanks for solving the problem ima go use this newfound knowledge!
