### ISSUE TITLE
Wont Compile

### ISSUE THREAD

**Issue by Superlogan321** [ShadowMario/FNF-PsychEngine#10773]
### Describe your problem here.

I try to compile it with no edits to the script FunkinLua or any script but it fails to compile I attached a screenshot
![image](https://user-images.githubusercontent.com/110323819/194228627-43e03377-27b4-4d65-9ad4-2ef870ee2afc.png)
Please Help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MemeHoovy** [comment]
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

**Comment by Superlogan321** [comment]
Thanks it works now
