### ISSUE TITLE
My custom font won't work?

### ISSUE THREAD

**Issue by WeldedFlap** [ShadowMario/FNF-PsychEngine#1078]
### Describe your bug here.

I tried adding a custom font, but whenever I added it it just crashed. I kept the normal name and changed the source code text.
![image](https://user-images.githubusercontent.com/90015471/142083019-5fa98fde-7f0b-46c0-a53c-baff1a4ec6f4.png)
![image](https://user-images.githubusercontent.com/90015471/142083115-4d0fc8ee-4238-419b-b4ba-1b60adc9cf60.png)

here the font link: [Font](https://www.dafont.com/rust.font)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Just added the font and changed the code so it directs to the font.

**Comment by ShadowMario** [comment]
Your font seems weirdly... lighter than VCR for comparison.
It might have been corrupted/isn't supported in Haxe.
