### ISSUE TITLE
Example Event Script Download Broken

### ISSUE THREAD

**Issue by BluCoolKnux** [ShadowMario/FNF-PsychEngine#10789]
### What needs to be documented?

I'm looking to make my custom events for my mod, but when I go to download the Example Event script file hyperlinked on the "Wiki" page for "Creating an Event," it just brings me to a New Tab (see attachment).

![image](https://user-images.githubusercontent.com/63269642/194683041-4cf20907-bb72-4eda-a894-b627061cff5a.png)

In short, I can't download or edit the Example Event script currently. Unsure why this is.

**Comment by MemeHoovy** [comment]
yeah the example script link is broken
