### ISSUE TITLE
The Descbox From Freeplay.

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#10786]
### What is your question?

How To Remove The Descbox Thing On The Freeplay?

**Comment by DisIsNOt** [comment]
Go to freeplay state and find it out

**Comment by MemeHoovy** [comment]
exactly, and quit asking for people to code for you

**Comment by StefanBETA2008** [comment]
> exactly, and quit asking for people to code for you

Okay, Sorry.
