### ISSUE TITLE
I have a problem porting DnB 3.0 Characters into Psych Engine Latest Version

### ISSUE THREAD

**Issue by DJAPK88** [ShadowMario/FNF-PsychEngine#10784]
### Describe your problem here.

(I will use Dave as an example)

Everytime Dave hits a note, he does the animation + the miss animation, how do I fix it? 

(by the way I am using the built-in character editor with a normal PE Build)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by impostor5875** [comment]
add a 0 after the normal singing animation's name from the xml (don't actually change the xml though)
for example: "down0" or "up0"

**Comment by DJAPK88** [comment]
It worked! Tysm man :D
