### ISSUE TITLE
setRatingName doesn't work on latest Action Build

### ISSUE THREAD

**Issue by Jaldabo** [ShadowMario/FNF-PsychEngine#10781]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/104400900/194444187-e402e6d8-da37-4eda-a1bd-d14879853493.png)
[Current Action Build]

![image](https://user-images.githubusercontent.com/104400900/194444309-396b936e-ca7d-4add-b5f7-cbf393c4f158.png)
[Current Release Build]

Both images are using the same script, which looks like this:

```
function onUpdate()
    -- Changes Names to Letters on Score Text
    if ratingName == 'Perfect!!' then
    setRatingName('SSS')
    end
    if ratingName == 'Sick!' then
    setRatingName('SS')
    end
    if ratingName == 'Great' then
    setRatingName('S')
    end
    if ratingName == 'Good' then
    setRatingName('A')
    end
    if ratingName == 'Nice' then
    setRatingName('B')
    end
    if ratingName == 'You Suck!' then
    setRatingName('C')
    end
    if ratingName == 'Meh' then
    setRatingName('D')
    end
    if ratingName == 'Bruh' then
    setRatingName('E')
    end
    if ratingName == 'Shit' then
    setRatingName('F')
    end
    end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Lorekeeper49** [comment]
I think it's meant to be used on `goodNoteHit()` as that's what updates the rating

**Comment by CaptainBaldi** [comment]
> I think it's meant to be used on `goodNoteHit()` as that's what updates the rating

it would probably also work with onUpdate since it gets called every frame

**Comment by Jaldabo** [comment]
Important to note that the script is constant here, so its 100% a source thing
