### ISSUE TITLE
When I try to save a character json it just breaks and doesn't respond

### ISSUE THREAD

**Issue by imalink100** [ShadowMario/FNF-PsychEngine#10788]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/106406304/194667667-4c12d19a-1889-4209-8b9c-bd241b5199ee.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by tiaomafy** [comment]
which version of psych engine are you using

**Comment by imalink100** [comment]
> which version of psych engine are you using

i don't know, it's baldi's funkin class and i dont know what version that is

**Comment by UsNoobs** [comment]
Put It In Bin/Mods/Characters/Whatever.json

**Comment by UsNoobs** [comment]
then click 7, and if it works, you will see playtime or what you name it.

**Comment by MemeHoovy** [comment]
if there is a bin folder

**Comment by imalink100** [comment]
> if there is a bin folder

it's PSYCH ENGINE.

**Comment by MemeHoovy** [comment]
yeah I know that

**Comment by imalink100** [comment]
> yeah I know that dipshit

there's no bin folders in psych engine.

**Comment by MemeHoovy** [comment]
sometimes there is, sometimes there isn't, especially when you compile the game

**Comment by imalink100** [comment]
> Put It In Bin/Mods/Characters/Whatever.json

bruh it wont let me download the json file

**Comment by MemeHoovy** [comment]
> > Put It In Bin/Mods/Characters/Whatever.json
> 
> bruh it wont let me download the json file

wdym it won't let you download the json?

**Comment by imalink100** [comment]
> > > Put It In Bin/Mods/Characters/Whatever.json
> > 
> > 
> > bruh it wont let me download the json file
> 
> wdym it won't let you download the json?

when i click save character it just doesn't respond and it won't ever download it on my pc
