### ISSUE TITLE
Create an option that allows you to have the voice of BF, GF and the Opponent separately. Example: Voices_BF.ogg, Voices_GF.ogg, Voices_OP.ogg

### ISSUE THREAD

**Issue by QuetzalcoutlDev** [ShadowMario/FNF-PsychEngine#10787]
### What feature do you want to get added on the **base** engine?

Having an option that allows the game to have the BF's voice separate from the opponent's would make it easier to chart songs, and if there is a moment in the song where GF sings then that's separate as well.

I don't know if it's a good idea

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by CaptainBaldi** [comment]
honestly i dont feel like this would benefit many people 
depending on circumstances charting is pretty easy via psych i dont think this is needed

**Comment by DragShot** [comment]
I support this idea.

**Comment by tylerandari12** [comment]
I like this...

**Comment by ShadowMario** [comment]
I'm waiting for the official implementation for it to stay the same as week 8's.
