### ISSUE TITLE
Where does runHaxeCode() run from?

### ISSUE THREAD

**Issue by dombomb64** [ShadowMario/FNF-PsychEngine#10794]
### What is your question?

What class does the function `runHaxeCode()` run its script in? I’m asking so I can understand this function better.

**Comment by MemeHoovy** [comment]
lua

**Comment by dombomb64** [comment]
You mean `FunkinLua`?

**Comment by MemeHoovy** [comment]
it's runs in lua scripts

**Comment by dombomb64** [comment]
I know, but what would to need to type to, for example, change some variable in `PlayState`? I know that’s possible without this function, but I can’t think of a better example right now.

**Comment by MemeHoovy** [comment]
here's some example code from the vs ambush mod
```
	runHaxeCode([[

		var filepath = Paths.video('boo');
		//get the video path
		
		var video = new MP4Handler();
		//create the video object

		video.playVideo(filepath);
		//play the video file

		video.visible = false;
		//make the video object overlay invisible

		setVar('video',video);
		//set global variable

		FlxG.stage.removeEventListener('enterFrame', video.update); 
		//removes the native update event the video has (disables skipping pressing enter)
	]])
```

**Comment by frantastic24** [comment]
It does run from the `FunkinLua` class

**Comment by dombomb64** [comment]
This is cool and all, but how would I run, say, `setProperty('boyfriendGroup.x')` inside a script in `runHaxeCode()`? Would I call his X position `boyfriendGroup.x`? `PlayState.boyfriendGroup.x`? Sorry that I’m asking so many questions, it’s just that I’m not sure you know what I mean, not to sound condescending or anything.

**Comment by dombomb64** [comment]
> It does run from the `FunkinLua` class
Why did this reply not show up, GitHub?!

**Comment by frantastic24** [comment]
You would use `game.`, an example would be using `game.boyfriend.x = 50` which would be like using `setProperty('boyfriend.x', 50)`

**Comment by dombomb64** [comment]
Thank you! This worked! Although, what’s the `setVar()` function for, then? I found it in `FunkinLua`, but I don’t know how it works. I tried using it like a normal function with parameters inside parentheses, but it didn’t do anything.
