### ISSUE TITLE
how i do a secret song 

### ISSUE THREAD

**Issue by alexxdddddd** [ShadowMario/FNF-PsychEngine#10796]
### What is your question?

How do I make a song that to play it you have to press a specific arrow

for example if I press a notetype that its function is to take me to that song, it takes me to that song.

(I use the google translator sorry if I wrote bad)

**Comment by alexxdddddd** [comment]
also i use .lua

**Comment by MemeHoovy** [comment]
use ```loadSong(name, difficultynumber)```
