### ISSUE TITLE
how can i change this

### ISSUE THREAD

**Issue by Sebasyn0se** [ShadowMario/FNF-PsychEngine#1079]
### Describe your problem here.

i wanna the animation plays every 2 beats, because if it plays every beat it goes so fast.

clarification:( the animation works, i just wanna it plays every 2 beats )

![● test-ddlc-bg lua - Visual Studio Code 16_11_2021 23_12_21](https://user-images.githubusercontent.com/93066244/142096530-a7f7fc07-212a-4fec-9c09-31f9cb0eca64.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

**Comment by 4wdthinks** [comment]
```lua
function onBeatHit()
	-- triggered 4 times per section
	if curBeat % 2 == 0 then
		luaSpritePlayAnimation('yuri', 'Idle', true);
	end
end
```
