### ISSUE TITLE
Why is this happening

### ISSUE THREAD

**Issue by HorrorGameFan1** [ShadowMario/FNF-PsychEngine#10799]
![Screenshot 2022-10-09 202848](https://user-images.githubusercontent.com/115405898/194756860-0b6060f0-327f-4bf0-92eb-c3f204aa0e32.png)
### Describe your problem here.

Everytime i try to load up a song from ddto encore, it shows a message and tells me to report it here and it happens with a few other songs as well

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

If adding mods count, then yes

**Comment by TheKitBoi** [comment]
You need to add the deleted.json on the folder

**Comment by HorrorGameFan1** [comment]
how?

**Comment by TheKitBoi** [comment]
Save the json with a -deleted.json on the name

**Comment by KillerAvecRage** [comment]
You are missing "mishmash-(natsayuri-mix)-deleted.json" in your mod folder, you have to add it
