### ISSUE TITLE
Is it normal for the game to take multiple days to compile?

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#10791]
### What is your question?

Ive heard some people say it takes an entire day for the game to first compile, but mines been trying to compile for a little over 2 days now and still nothing...

Under `export/release/windows/bin` all the normal fnf stuff is there except for the exe btw...

Also there are no errors. Just something about `FlxCamera` being depreciated...

**Comment by MemeHoovy** [comment]
the flxcamera deprecation is just a a warning, and also, I'm pretty sure it's not normal for the game to take days to compile

**Comment by tylerandari12** [comment]
> the flxcamera deprecation thing is just a warning, and also, I'm pretty sure it's not normal for the game to take days to compile

Interesting...
It doesnt let me use the command line which leads me to believe it's still going...

**Comment by MemeHoovy** [comment]
it shouldn't be

**Comment by tylerandari12** [comment]
One more thing I should note is that my PC is kinda slo...
I'm gonna let it run one more night and if it doesnt work by tomorrow I'll shut it down...

**Comment by tylerandari12** [comment]
Tomorrow has come and still nothing :(
