### ISSUE TITLE
How do you change discord rpc? 

### ISSUE THREAD

**Issue by cooldude47980597** [ShadowMario/FNF-PsychEngine#10790]
### What is your question?

how do i change discord rpc to my mod??

**Comment by MemeHoovy** [comment]
source code only

**Comment by MemeHoovy** [comment]
https://www.youtube.com/watch?v=KKH_xRJbEYw

**Comment by tylerandari12** [comment]
> source code only

says who?
`changePresence(details:String, state:String, ?smallImageKey:String, ?hasStartTimestamp:Bool, ?endTimestamp:Float)`

Found on line 2306 of [FunkinLua.hx](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/FunkinLua.hx#L2306),

**Comment by MemeHoovy** [comment]
oh right, I forgot about that

**Comment by cooldude47980597** [comment]
like this? runHaxeCode changePresence(details:String, state:String, ?smallImageKey:String, ?hasStartTimestamp:Bool, ?endTimestamp:Float)

**Comment by MemeHoovy** [comment]
no, not like that

**Comment by tylerandari12** [comment]
> like this? runHaxeCode changePresence(details:String, state:String, ?smallImageKey:String, ?hasStartTimestamp:Bool, ?endTimestamp:Float)

Its a Lua function...

`runHaxeCode` is not needed
