### ISSUE TITLE
Add Shaders To Main Menu.

### ISSUE THREAD

**Issue by UsNoobs** [ShadowMario/FNF-PsychEngine#10797]
### Describe your problem here.

This Isn't Really a Psych Engine Question, But An OS Engine Question. But How Do You Add Shaders to The Main Menu In OS Engine, Like County Funkin'?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, Main Menu, And Project.xml.

**Comment by UsNoobs** [comment]
Also I Put It Here Because OS Engine Github Is Only Read-Only.

**Comment by MemeHoovy** [comment]
it's not possible with lua

**Comment by UsNoobs** [comment]
Oh
