### ISSUE TITLE
Freeplay Categories Help

### ISSUE THREAD

**Issue by DJAPK88** [ShadowMario/FNF-PsychEngine#10795]
### Describe your problem here.

How do I put Freeplay Categories into my mod? I've been searching for months but without success (i am asking for help, I am not asking to ShadowMario if he can put that into the game)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

A bit of everything (FreeplayState.hx, added some files, etc.)

**Comment by Jevilm** [comment]
d+b source code has freeplay sections and so does indie cross

**Comment by DJAPK88** [comment]
I know, but how do I make the categories? What files do I need to take/edit?

**Comment by Jevilm** [comment]
I dont use source code so dk

**Comment by MemeHoovy** [comment]
> I know, but how do I make the categories? What files do I need to take/edit?

just use source code from indie cross

**Comment by Isaagomen** [comment]
> > I know, but how do I make the categories? What files do I need to take/edit?
> 
> just use source code from indie cross

its kade engine

**Comment by MemeHoovy** [comment]
no shit

**Comment by DJAPK88** [comment]
How do I convert it?

**Comment by MemeHoovy** [comment]
literally just change some code
