### ISSUE TITLE
ratings

### ISSUE THREAD

**Issue by susussususus** [ShadowMario/FNF-PsychEngine#10792]
### What is your question?

how do i change the ratings I have 32bit and i can't find how to change them.

**Comment by susussususus** [comment]
like how do i change you suck to your bad for an example

**Comment by TheKitBoi** [comment]
Go onto 85 to change there

![77463068-4170-4EB7-ADD1-66B50009B951](https://user-images.githubusercontent.com/84044666/194713549-7ade2762-b54f-478d-accf-216028d8540b.jpeg)

If ur talking about lua then (I’ll get the script in a moment)

**Comment by susussususus** [comment]
where is 85?

**Comment by susussususus** [comment]
what file is it in?

**Comment by susussususus** [comment]
also sry for so many questions but will this work in version 0.42

**Comment by TheKitBoi** [comment]
PlayState.hx and yes it works

**Comment by susussususus** [comment]
The only files i see are json files

**Comment by susussususus** [comment]
I can't find any hx files

**Comment by MemeHoovy** [comment]
> I can't find any hx files

they're in the source code

**Comment by susussususus** [comment]
where is the source code

**Comment by MemeHoovy** [comment]
https://github.com/ShadowMario/FNF-PsychEngine

**Comment by susussususus** [comment]
how do i put the souce in the game tho

**Comment by MemeHoovy** [comment]
you gotta download it

**Comment by susussususus** [comment]
how

**Comment by MemeHoovy** [comment]
just click on code & click on download zip

**Comment by MemeHoovy** [comment]
here's some tutorials, they're old as hell, but they should still work
https://youtu.be/DABfz3rfuWc
https://youtu.be/8CCqdzEWXIc
