### ISSUE TITLE
indication needed and error loading a spritesheet

### ISSUE THREAD

**Issue by Jamongusxd** [ShadowMario/FNF-PsychEngine#108]
when i drop my character xml and png to the mods/images/characters and i load up the game and load the character on the editor for making its json file it crashes. what do i do?

and when i try to add a new charactermenu i do the process and i go to the week editor and i load him and its a slightly bigger bf.

and when i try to add a new background for the menu its blank. where do i put it and also same error happens with the week png. i need help for locating the place to drop those files! 
![image](https://user-images.githubusercontent.com/88459965/134399154-495ad158-3fa8-40e6-b34b-f968c785b622.png)
![image](https://user-images.githubusercontent.com/88459965/134399559-79e4245f-5854-4bbc-bd20-2fc4c562d021.png)
![image](https://user-images.githubusercontent.com/88459965/134399613-09f8e6bb-fb04-420a-a96c-6443b922f764.png)

**Comment by Jamongusxd** [comment]
is it case sensitive?

**Comment by ShadowMario** [comment]
Yes, it is case sensitive, and you're putting the files on the wrong folders.

Menu characters go on `mods/menucharacters/`

Menu backgrounds go on `mods/menubackgrounds/`

Menu items go on `mods/storymenu/`

[Refer to this](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Adding-a-New-Week)

**Comment by Jamongusxd** [comment]
adding menu items doesnt work either, i cant place my week logo.
