### ISSUE TITLE
Game crash upon input

### ISSUE THREAD

**Issue by NoobyWasTaken** [ShadowMario/FNF-PsychEngine#1080]
### Describe your problem here.

When I press any input during any song, the game crashes.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I removed/replaced some achievements (Achievements.hx, PlayState.hx)

**Comment by ShadowMario** [comment]
Run in a debug build and send the crash trace.

**Comment by NoobyWasTaken** [comment]
i ended up having to reinstall a bunch of stuff lol

**Comment by NoobyWasTaken** [comment]
> Run in a debug build and send the crash trace.

![image_2021-11-21_202638](https://user-images.githubusercontent.com/88544062/142796561-242b6823-dacf-41b5-b6b6-df1b5a0f9af6.png)
