### ISSUE TITLE
The game closes at chart mode for no reason

### ISSUE THREAD

**Issue by StickManos** [ShadowMario/FNF-PsychEngine#10801]
### Describe your bug here.

So basically when i use the charting mode to do my work ( charting ) at some point the game just closes. Not a crash or anything. The game just stops, and closes itself. I don't know why this is happening, and a good reason would be pretty good, but you guys should fix this as it just makes the life of an everyday charter more difficult

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, just started charting, and it happened

**Comment by CaptainBaldi** [comment]
pc issue :scream:

also doesnt autosave exist just use that

**Comment by TheKitBoi** [comment]
> ### Describe your bug here.
> So basically when i use the charting mode to do my work ( charting ) at some point the game just closes. Not a crash or anything. The game just stops, and closes itself. I don't know why this is happening, and a good reason would be pretty good, but you guys should fix this as it just makes the life of an everyday charter more difficult

Ok 2GB ram user
