### ISSUE TITLE
acces a song by typing a word

### ISSUE THREAD

**Issue by redcap7956** [ShadowMario/FNF-PsychEngine#10804]
### Describe your problem here.

I want to make so when you type a secret word on you're keyboard, it opens a secret song, but, I'm not a coder, neither a lua guy, so, can someone pass me a script to do that?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHoovy** [comment]
don't ask people to code for you, learn to do it yourself

**Comment by redcap7956** [comment]
alright then, i'll find a guide

**Comment by LilDrippyMyFnf** [comment]
> don't ask people to code for you, learn to do it yourself

no cap tho

**Comment by LilDrippyMyFnf** [comment]
> > don't ask people to code for you, learn to do it yourself
> 
> no cap tho

probably me too 💀
