### ISSUE TITLE
How to load a song on key press

### ISSUE THREAD

**Issue by plasticocelot123** [ShadowMario/FNF-PsychEngine#10803]
### Describe your problem here.

I am trying to make a mod that has a secret song. To access it, you would press 3 on the keyboard and it would load the song. I do not know very much about programming in lua and I was hoping others might.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I am modding on this build and have mostly everything done.

**Comment by MemeHoovy** [comment]
```loadSong(name, difficultyNumber)```

**Comment by MemeHoovy** [comment]
and don't ask for people to code for you
