### ISSUE TITLE
There is no score when using botplay, how to let the score be shown?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#1081]
### What is your question?

There is no score when using botplay, how to let the score be shown?

![Snipaste_2021-11-17_17-44-53](https://user-images.githubusercontent.com/13177997/142177505-54e64985-2ff4-4e9d-b3fc-24b8e6084bc3.png)

**Comment by nintendofan44** [comment]
botplay doesn't save you score
neither add more or less when using it

**Comment by zwl1619** [comment]
@nintendofan44 Can I save score with lua script? If yes, how to do it?

**Comment by acap09** [comment]
You could hard-code it with setScore, or if you're too lazy, then do addScore. If you don't know how to do it, it's on [the wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions)!

**Comment by ShadowMario** [comment]
That's intentional.
