### ISSUE TITLE
tween question

### ISSUE THREAD

**Issue by DisIsNOt** [ShadowMario/FNF-PsychEngine#10816]
### What is your question?

some questions

1. How can I make an object tween depends on the timebar
2. how to get a song's percentage

**Comment by bruh1cat** [comment]
> ### What is your question?
> 
> 
> 
> some questions
> 
> 
> 
> 1. How can I make an object tween depends on the timebar
> 
> 2. how to get a song's percentage

1. If by timebar you mean an exact point in a song then use function onStepHit() if curStep == 69 then,
  you can check the steps in the chart editor (every step is one event square) or function onBeatHit()

2. Idk abt percentage but you can use the variable songLength, though it'll return the length of the song in milliseconds.
