### ISSUE TITLE
I shit myself

### ISSUE THREAD

**Issue by TheKillerA1** [ShadowMario/FNF-PsychEngine#10817]
### Describe your bug here.

Help

### Command Prompt/Terminal logs (if existing)

```bash
No
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

Help me pls

**Comment by TheKillerA1** [comment]
https://user-images.githubusercontent.com/115441433/194922497-af6543ac-4887-459b-a838-b8840ae58b00.MOV

**Comment by voxovistired** [comment]
Bro, genuinely no one cares. This is about shit regarding Psych, you’re just posting unnecessary shit. Delete this please and thanks.

**Comment by TheKitBoi** [comment]
> ### Describe your bug here.
> Help

this shit isn’t discord shit stain

**Comment by MemeHoovy** [comment]
https://user-images.githubusercontent.com/97995998/194926550-1b11a984-8d12-42d7-bccd-eab0e1dcbb09.mp4

**Comment by ShadowMario** [comment]
proof?
