### ISSUE TITLE
'end' expected (to close 'function' at line 3) near if

### ISSUE THREAD

**Issue by MMalkeZ** [ShadowMario/FNF-PsychEngine#10818]
### Describe your problem here.

![Screenshot_195](https://user-images.githubusercontent.com/108292251/194930076-f31696be-e62b-4011-8490-4e4ed8e42275.png)
![Screenshot_196](https://user-images.githubusercontent.com/108292251/194930081-52433518-4f34-481b-9608-67659b61b248.png)

someone help me here

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by KillerAvecRage** [comment]
You are missing an "end" to close your onEndSong() function
add an "end" to your script and try it again

**Comment by MMalkeZ** [comment]
> You are missing an "end" to close your onEndSong() function add an "end" to your script and try it again

but where?, i thought the "end" at line 14 was already closing it

**Comment by CaptainBaldi** [comment]
you cant have code after returning it just breaks shit

**Comment by MMalkeZ** [comment]
> you cant have code after returning it just breaks shit

so i should make it like this?
![image](https://user-images.githubusercontent.com/108292251/194945341-88486ecf-4704-4d26-9df7-69c514a76c67.png)

**Comment by TheKitBoi** [comment]
hp = tonumber (getProperty("health' ))
function onEndSong()
    if hp >= 1 then
    startvideo (' goodEnding")
    else if not hp >= 1 then
    startvideo('badEnding*)
    end
    if keyJustPressed ('ACCEPT" ) then
    return Function Continue;
    end
    return Function_ Stop;
end

**Comment by MMalkeZ** [comment]
> hp = tonumber (getProperty("health' )) function onEndSong() if hp >= 1 then startvideo (' goodEnding") else if not hp >= 1 then startvideo('badEnding*) end if keyJustPressed ('ACCEPT" ) then return Function Continue; end return Function_ Stop; end

![image](https://user-images.githubusercontent.com/108292251/194949719-d3d533f5-eb9a-498d-a21a-9b1ff46c3058.png)
 same

**Comment by Lorekeeper49** [comment]
> > hp = tonumber (getProperty("health' )) function onEndSong() if hp >= 1 then startvideo (' goodEnding") else if not hp >= 1 then startvideo('badEnding*) end if keyJustPressed ('ACCEPT" ) then return Function Continue; end return Function_ Stop; end
> 
> ![image](https://user-images.githubusercontent.com/108292251/194949719-d3d533f5-eb9a-498d-a21a-9b1ff46c3058.png)
>  same

Technically not the same, now it's asking to place 'end' near '<eof>', something that is not part of the file

**Comment by MMalkeZ** [comment]
> 

still didnt fixed my problem, soo... same

**Comment by Lorekeeper49** [comment]
> > 
> 
> still didnt fixed my problem, soo... same

My solution whenever I got this was to literally copy the code into a different file and delete the origin while making no changes to the code that I pasted into the new file, a solution that shouldn't work but does for some reason.

**Comment by frantastic24** [comment]
`elseif`

**Comment by Meme1079** [comment]
Here's what causing it to have an error. There's a `getProperty()` function in a variable outside of a function. The `return Function_Stop` should move on the end of a function not above. 

Also I modified the code a bit in order for it work properly.

Heres the fix:
```lua
local allowCountdown = false;
function onEndSong()
     if not allowCountdown then
          if getProperty('health') > 1 then
               startVideo('goodEnding')
          else
               startVideo('badEnding')
          end
          allowCountdown = true
          return Function_Stop
     end
     return Function_Continue
end
```

**Comment by KillerAvecRage** [comment]
![image](https://user-images.githubusercontent.com/103606542/195394979-fc62f34d-504f-48be-a661-9f60cbd20978.png)
With this script, the game worked without any issue, might try by yourself

**Comment by MMalkeZ** [comment]
both of these just made the song freeze at the start, not even the countdown is playing

**Comment by Meme1079** [comment]
> both of these just made the song freeze at the start, not even the countdown is playing

Use `startCountdown()` and make a timer like this

```lua
function onTimerCompleted(tag, loops, loopsLeft)
     if tag == 'end' then
          startCountdown()
     end
end
```

Then put `runTimer('end', 2)` on `onStartCountdown()` function. Also the 2 in the parameter is, how many seconds will it activate the tag

```lua
local allowCountdown = false
function onStartCountdown()
     if not allowCountdown and not seenCutscene then
         -- the cutscene stuff
         runTimer('end', 2) -- put it at the bottom
	 allowCountdown = true;
         return Function_Stop;
     end
     return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
     if tag == 'end' then
          startCountdown()
     end
end
```
