### ISSUE TITLE
My cats not working

### ISSUE THREAD

**Issue by TheKillerA1** [ShadowMario/FNF-PsychEngine#10812]
### Describe your bug here.

I tried slapping in 4 times and now I see red sauce on the ground, idk I think it short circuited

### Command Prompt/Terminal logs (if existing)

```bash
Legit just said nothing, weird…
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Flash/Air-based target

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Lorekeeper49** [comment]
You need to give more information on what you are talking about

**Comment by MemeHoovy** [comment]
> ### Describe your bug here.
> I tried slapping in 4 times and now I see red sauce on the ground, idk I think it short circuited
> 
> ### Command Prompt/Terminal logs (if existing)
> ```shell
> Legit just said nothing, weird…
> ```
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Flash/Air-based target
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No

you need to fucking die

**Comment by TheKillerA1** [comment]
> You need to give more information on what you are talking about

Damn that lsd is kicking in
