### ISSUE TITLE
Saul goodman

### ISSUE THREAD

**Issue by TheKillerA1** [ShadowMario/FNF-PsychEngine#10814]
### What feature do you want to get added on the **base** engine?

Add saul goodman into psych engine

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by DisIsNOt** [comment]
![3dsaulcover.jpg](https://user-images.githubusercontent.com/78010753/194867573-343e0f95-da21-487a-9732-336d512d0eee.jpg)

**Comment by TheKillerA1** [comment]
![42292151-11B2-4D93-B342-6B273D40CE27](https://user-images.githubusercontent.com/115441433/194900414-4a778011-3c0e-46b9-98e5-9a9ea0a2f064.jpeg)

**Comment by MemeHoovy** [comment]
you're unbelieveable

**Comment by TheKillerA1** [comment]
> you're unbelieveable

That was not very saul goodman of you

**Comment by ivorivorhepl** [comment]
saulin time

**Comment by ShadowMario** [comment]
Added, thank you for the suggestion
