### ISSUE TITLE
White Image Flash fade doesn't fade for some reason.

### ISSUE THREAD

**Issue by HJacet** [ShadowMario/FNF-PsychEngine#10820]
### Describe your problem here.

I need some help with an event's code, for some reason when the images flashes it doesn't fade out like it's supposed to do. I think the code is set up correctly but it's like the game completely ignores that specific part.

Here's the code for reference: 

```
function onEvent(name, value1, value2)
    if name == 'Image Flash' then
        makeLuaSprite('image', value1, 0, 0);
        addLuaSprite('image', true);
        scaleObject('image', 0.5, 0.52);
        doTweenColor('hello', 'image', 'FFFFFFFF', 0.1, 'quartIn');
        setObjectCamera('image', 'other');
        runTimer('wait', value2);
        
        function onTimerCompleted(tag, loops, loopsleft)
            if tag == 'wait' then
                doTweenAlpha('byebye', 'image', 0, 1, 'linear');
            end
        end
        
        function onTweenCompleted(tag)
            if tag == 'byebye' then
                removeLuaSprite('image', true);
            end
        end
    end
end
```

I'm guessing the Tween Alpha is correct so I don't know why it won't fade out.

Example of what's happening (**white flash warning i guess**):

https://user-images.githubusercontent.com/106554377/194961860-7b8b2d00-5870-4033-9244-0b5e01adc028.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by HJacet** [comment]
Nevermind, I got it working!

**Comment by LilDrippyMyFnf** [comment]
> Nevermind, I got it working!

are you good at coding?

**Comment by HJacet** [comment]
I'm a bit experienced

> > Nevermind, I got it working!
> 
> are you good at coding?

**Comment by Mastercopper2346** [comment]
Can you teach me lua again
