### ISSUE TITLE
How do i Compile... so whats next?

### ISSUE THREAD

**Issue by cooldude47980597** [ShadowMario/FNF-PsychEngine#10825]
### Describe your problem here.

so i have the stuff to compile but how do i build it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Lorekeeper49** [comment]
`lime test windows` or whatever is your using for testing the code

**Comment by MemeHoovy** [comment]
> `lime test windows` or whatever is your using for testing the code

that's what I said
