### ISSUE TITLE
How do you get file paths to folders outside of images?

### ISSUE THREAD

**Issue by ItsMeTyler25** [ShadowMario/FNF-PsychEngine#10823]
### Describe your problem here.

Hello! So, I'm trying to get the file paths of the songs folder, because I want to be able to play the Inst of a song using:
**playMusic('song inst here', 1, 'inst')**

I tried using this at first:
**playMusic('mods/songs/tutorial/Inst', 1, 'inst')** 
but that didn't seem to work so just wondering if there's any other way to get the file path? Thanks for any help!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I have not, using LUA.

**Comment by frantastic24** [comment]
playMusic looks for files inside `music`, you can't use it to load something in `songs`

**Comment by ItsMeTyler25** [comment]
> playMusic looks for files inside `music`, you can't use it to load something in `songs`

Oh I see,  is there a way to load and play a file from songs then?

**Comment by frantastic24** [comment]
there is #10535 this is for vocals but can be edited to work with instrumentals

**Comment by ItsMeTyler25** [comment]
> there is #10535 this is for vocals but can be edited to work with instrumentals

Ok well I tried using this but it didnt seem to work, this is my first time using runHaxeCode() so i'm sorry for the trouble
Is there something im doing wrong?

function onCreatePost()
        addHaxeLibrary('FlxSound', 'flixel.system')
        runHaxeCode([[
            game.inst = new FlxSound().loadEmbedded(Paths.returnSound('songs', Paths.formatToSongPath("Tutorial") + '/Inst'));
            FlxG.sound.list.add(game.inst);
        ]])
end

**Comment by frantastic24** [comment]
You should take a look at the source code and see how music is handled
