### ISSUE TITLE
Map goes over Characters (not notes)

### ISSUE THREAD

**Issue by Raxusd** [ShadowMario/FNF-PsychEngine#10832]
### Describe your bug here.

The map is shown, but not the characters.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

All I did was import my map to the song and it happened.

**Comment by Raxusd** [comment]
![image](https://user-images.githubusercontent.com/109549066/195261420-838ef956-80f3-4f97-89c4-4e44f7466aca.png)

**Comment by frantastic24** [comment]
Not a bug + didn't show code

**Comment by Raxusd** [comment]
sorry, the only thing I have is a looping modchart, and the map.
![Thangy](https://user-images.githubusercontent.com/109549066/195267538-d1863b44-9b38-4d7e-a692-06e78b1fe067.png)

**Comment by Raxusd** [comment]
The modchart:local defaultNotePos = {};
local spin = true;
local arrowMoveX = 40;
local arrowMoveY = 20;
 
function onSongStart()
    for i = 0,7 do 
        x = getPropertyFromGroup('strumLineNotes', i, 'x')
        y = getPropertyFromGroup('strumLineNotes', i, 'y')
        table.insert(defaultNotePos, {x,y})
    end
end
function onUpdate(elapsed)
    songPos = getPropertyFromClass('Conductor', 'songPosition');
    currentBeat = (songPos / 1000) * (bpm / 60)
    if spin == true then 
        for i = 0,7 do 
            setPropertyFromGroup('strumLineNotes', i, 'x', defaultNotePos[i + 1][1] + arrowMoveX * math.sin((currentBeat + i*0.25) * math.pi))
            setPropertyFromGroup('strumLineNotes', i, 'y', defaultNotePos[i + 1][2] + arrowMoveY * math.cos((currentBeat + i*0.25) * math.pi))
        end
    end
end

**Comment by frantastic24** [comment]
The modchart has literally nothing to do with the stage or the characters

**Comment by Isaagomen** [comment]
object order problem

**Comment by CaptainBaldi** [comment]
> ![image](https://user-images.githubusercontent.com/109549066/195261420-838ef956-80f3-4f97-89c4-4e44f7466aca.png)

800mb of ram jesus fucking christ

anyways when adding the bg you probably put true in addluasprite's second parameter

**Comment by Raxusd** [comment]
thanks guys
