### ISSUE TITLE
Every Song That is Over 4 Minutes Crashes 4 Minutes in?

### ISSUE THREAD

**Issue by FriskyWasTaken** [ShadowMario/FNF-PsychEngine#10830]
### Describe your problem here.

Every song in the mod I'm making (0.6.2 Source code) crashes 4 minutes into any song that is over 4 minutes, and I have no clue why, My FPS is 60 and there aren't any scripts that update every frame, I tried checking the cmd prompt after it crashes, but nothing pops up

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I made a new main menu, and added a few new awards (that's all I remember adding)

**Comment by Justudude321** [comment]
You could try updating to 0.6.3
