### ISSUE TITLE
How do i fix this???

### ISSUE THREAD

**Issue by FriskyWasTaken** [ShadowMario/FNF-PsychEngine#10831]
### Describe your problem here.

every time I build my mod, this pops up after it opens(no title screen, or text pops up before)
![bruuh](https://user-images.githubusercontent.com/104544923/195246959-69d7ee17-d418-4a07-8f34-fc1fca6f5f73.PNG)
I don't know what happened, it worked before, all iI did was change the Icon16 file

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I made a new main menu, and added a few new awards, and changed the name, and icon of the Executable file(that's all I remember adding)

**Comment by frantastic24** [comment]
Missing XML file for a TitleState object

**Comment by FriskyWasTaken** [comment]
Can you give me an example of a Title state object?

**Comment by FriskyWasTaken** [comment]
> Missing XML file for a TitleState object

Can you give me an example of a TitleState object?

**Comment by frantastic24** [comment]
It's an animated sprite, I don't know what you edited in the state so I can't tell you which one

**Comment by FriskyWasTaken** [comment]
> It's an animated sprite, I don't know what you edited in the state so I can't tell you which one

I didn't edit the TitleState.hx file

**Comment by frantastic24** [comment]
Would've been easier if you just looked up the lines of code
It looks like logoBumpin is missing texture files
