### ISSUE TITLE
How to make that if you press 7 during a song, a secret song plays?

### ISSUE THREAD

**Issue by GWEjbik** [ShadowMario/FNF-PsychEngine#10835]
### What is your question?

I would really want the game to play an anti-cheat song when trying to enter the debug menu. You know, like cheating in D&B

**Comment by Parsellol** [comment]
> oh my lord there are so many issues about this already, USE THE SEARCH BAR

#10439 boom

**Comment by GWEjbik** [comment]
> > oh my lord there are so many issues about this already, USE THE SEARCH BAR
> 
> #10439 boom

Thank you!
