### ISSUE TITLE
Flickering Notes

### ISSUE THREAD

**Issue by SourDoseOfGG** [ShadowMario/FNF-PsychEngine#10837]
### What feature do you want to get added on the **base** engine?

With source code btw. I want the notes to randomly move to some parts of the screen but idk how(constantly moving to parts of the screen).

### To test your sight, and reliability, please select the option of what should NOT be requested.

Thing that would not cause problems

**Comment by CaptainBaldi** [comment]
why is this labeled as an enhancement

**Comment by MemeHoovy** [comment]
no

**Comment by SourDoseOfGG** [comment]
how do you label it something else

**Comment by TheKitBoi** [comment]
u can’t lol

**Comment by MemeHoovy** [comment]
unless your a collaborator or something

**Comment by SourDoseOfGG** [comment]
how do you make that just
