### ISSUE TITLE
Game is stuck at 30 fps

### ISSUE THREAD

**Issue by Jevilm** [ShadowMario/FNF-PsychEngine#10833]
### Describe your bug here.

When ever i play the game, it runs at 20 - 40 fps, it usually run on 50 - 60 fps, whats happening?
![Screenshot (84)](https://user-images.githubusercontent.com/110422450/195339231-a39630f0-ea08-40a3-a8b3-03ef48063819.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

(don kill me) D+B hud

**Comment by Jevilm** [comment]
its only on Playstate though, anything else runs fine

**Comment by CaptainBaldi** [comment]
can be scripts related or 
pc issue

**Comment by Jevilm** [comment]
probabl script related, idk whats causing it though

**Comment by cooldude47980597** [comment]
> can be scripts related or
> pc issue

OK make sure you copy and paste "playstate.hx" and put it in scripts then Put at the begining "RunHaxeCode" then change the fps

**Comment by CaptainBaldi** [comment]
> > can be scripts related or
> > pc issue
> 
> OK make sure you copy and paste "playstate.hx" and put it in scripts then Put at the begining "RunHaxeCode" then change the fps

honestly with you i cant tell if ur being serious or not
also its runHaxeCode not RunHaxeCode

**Comment by Jevilm** [comment]
this is lua idiot

**Comment by Jevilm** [comment]
like by playstate i didnt mean source code based

**Comment by Lorekeeper49** [comment]
Check you fps cap

**Comment by Lorekeeper49** [comment]
> i am "the guy who lives in my walls"

Random, but okay

**Comment by Jevilm** [comment]
minimum fps cap is 60

**Comment by cooldude47980597** [comment]
> this is lua idiot

you fucking think is is twitter

**Comment by cooldude47980597** [comment]
> like by playstate i didnt mean source code based
i didnt ask mf

**Comment by voxovistired** [comment]
Bruh y’all ain’t helping my guy at all. Ok so, can you briefly explain what scripts you have and their purpose and we can go from there.

**Comment by Jevilm** [comment]
> > like by playstate i didnt mean source code based
> > i didnt ask mf

dont fucking talk to me ever again BITCH

**Comment by Jevilm** [comment]
I have 3, one is the icons, one is the hud, and one is the ratings, the ratings have options so you can add combo and that

**Comment by Raxusd** [comment]
lag

**Comment by Jevilm** [comment]
i actually managed to fix this but i forgot to close it oops

**Comment by Jevilm** [comment]
a

**Comment by Jevilm** [comment]
a

**Comment by Jevilm** [comment]
a
