### ISSUE TITLE
How to let the text "BOTPLAY" not be displayed?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#1084]
### What is your question?

How to let the text "BOTPLAY" not be displayed?
![Snipaste_2021-11-17_19-07-56](https://user-images.githubusercontent.com/13177997/142190341-25577045-5a69-45b7-aaaf-d13ba95f873d.png)

**Comment by lemz1** [comment]
go to PlayState.hx and search `botplayTxt = new FlxText(400, timeBarBG.y + 55, FlxG.width - 800, "BOTPLAY", 32);` now just remove BOTPLAY
it should look like this:
`botplayTxt = new FlxText(400, timeBarBG.y + 55, FlxG.width - 800, "", 32);`

**Comment by lemz1** [comment]
go to PlayState.hx and search `botplayTxt = new FlxText(400, timeBarBG.y + 55, FlxG.width - 800, "BOTPLAY", 32);`
now remove BOTPLAY
it should look like this now:
`botplayTxt = new FlxText(400, timeBarBG.y + 55, FlxG.width - 800, "", 32);`

**Comment by ShadowMario** [comment]
Remove the `add(botplayTxt);` line in PlayState.hx
