### ISSUE TITLE
FunkinLua Broken?

### ISSUE THREAD

**Issue by ColinCartoons** [ShadowMario/FNF-PsychEngine#10842]
### Describe your problem here.

ok so i have this lua script for a despair port im making that SHOULD spawn striker and piper, but doesnt. i think it has something to do with my funkinlua or playstate cuz when i port it to a regular psych engine download, it works. but in my edited sourced version it wont. if anyone knows please help im on my hands and knees at this point. (also the attachments are in txt files cuz github doesnt support lua or hx)
[PiperStrickerScript.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9781079/PiperStrickerScript.txt)
[FunkinLua.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9781080/FunkinLua.txt)
[PlayState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9781087/PlayState.txt)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i did edit some stuff in my source but it was mainly for menu stuff and what not

**Comment by Jevilm** [comment]
did you do the thing with MODS_ALLOWED on source idfk

**Comment by ColinCartoons** [comment]
oh forgot this was open but i figured it out
