### ISSUE TITLE
Notes to far down and notes missing

### ISSUE THREAD

**Issue by gamingpeep** [ShadowMario/FNF-PsychEngine#10845]
### Describe your problem here.

I'm charting a song and the notes are all misaligned and missing for some reason and they were not like this yesterday. 
Anyone know how to fix it without ruining the chart?

video of problem: https://www.youtube.com/watch?v=uHZ02SX8i3g

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Jevilm** [comment]
are there any BPM changes in the song?

**Comment by gamingpeep** [comment]
I don't believe so. I can't check at the moment, I'll reply back when possible.

**Comment by gamingpeep** [comment]
No, there's none it stays at 160 BPM.

**Comment by gamingpeep** [comment]
could not figure out
