### ISSUE TITLE
Character's hold note shaking (I do not know how to explain it better)

### ISSUE THREAD

**Issue by GWEjbik** [ShadowMario/FNF-PsychEngine#10848]
### What feature do you want to get added on the **base** engine?

You could pick how many frames would be repeated while pressing a long note. 
1-Character would stand still when holding
2-Character would play 2 frames repeatedly till the note ends
3-Character would play 3 frames repeatedly till the note ends
And so on until it reaches the last frame of a specific animation.

It would be helpful, I think.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by MemeHoovy** [comment]
this kinda has something like that https://github.com/xenkap/IceEngine

**Comment by cooldude47980597** [comment]
> Failed the test + useless shut the fuck up dumbass motherfucker

**Comment by frantastic24** [comment]
You are pathetic

**Comment by cooldude47980597** [comment]
> You are pathetic

L+ratio+bozo+didnt ask

**Comment by CaptainBaldi** [comment]
> > Failed the test + useless
> > shut the fuck up dumbass motherfucker

insert nerd emoji here

**Comment by cooldude47980597** [comment]
> > > Failed the test + useless
> > > shut the fuck up dumbass motherfucker
> 
> insert nerd emoji here

i didnt ask

**Comment by CrusherNotDrip** [comment]
> > > > Failed the test + useless
> > > > shut the fuck up dumbass motherfucker
> > 
> > 
> > insert nerd emoji here
> 
> i didnt ask

didnt ask if you asked or not

**Comment by CaptainBaldi** [comment]
> > > > Failed the test + useless
> > > > shut the fuck up dumbass motherfucker
> > 
> > 
> > insert nerd emoji here
> 
> i didnt ask

this is a public website i have the right to share my thoughts regardless if you asked or not

**Comment by cooldude47980597** [comment]
> > > > > Failed the test + useless
> > > > > shut the fuck up dumbass motherfucker
> > > 
> > > 
> > > insert nerd emoji here
> > 
> > 
> > i didnt ask
> 
> this is a public website i have the right to share my thoughts regardless if you asked or not

https://youtu.be/iSEFtS0qnuY

**Comment by CrusherNotDrip** [comment]
> > > > > > Failed the test + useless
> > > > > > shut the fuck up dumbass motherfucker
> > > > 
> > > > 
> > > > insert nerd emoji here
> > > 
> > > 
> > > i didnt ask
> > 
> > 
> > this is a public website i have the right to share my thoughts regardless if you asked or not
> 
> https://youtu.be/iSEFtS0qnuY

how does this affect lebrons legacy though ???
