### ISSUE TITLE
Just adding songs crashes the game.

### ISSUE THREAD

**Issue by SLX1** [ShadowMario/FNF-PsychEngine#10846]
### Describe your bug here.

im trying to add some songs and this is happening and i dont know how to fix it. AT ALL.
![Friday Night Funkin'_ Psych Engine 10_14_2022 12_13_37 AM](https://user-images.githubusercontent.com/115778354/195792377-2f6e0edd-496d-4dcc-96e5-d791a0f9d821.png)

### Command Prompt/Terminal logs (if existing)

FreeplayState.hx (line 160)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, only added pngs, xmls, and useful scripts/ luas.

**Comment by KillerAvecRage** [comment]
You have to be missing a file since your error is Null object Reference
