### ISSUE TITLE
Can you change character when health is low?

### ISSUE THREAD

**Issue by jacobsthingswastaken** [ShadowMario/FNF-PsychEngine#10859]
### Describe your problem here.

I want to change the character when the player’s health goes into the losing icon (at 0.39 health) but I can’t find a script for it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Lorekeeper49** [comment]
Maybe try something like this:
```lua
onUpdate(e)
    if getProperty('health') <= 0.39 then
        triggerEvent('Change Character', 'bf', 'your character') --values may need to be swapped as I don't remember the change character values and I'm too lazy to look it up
    end
end

**Comment by jacobsthingswastaken** [comment]
> Maybe try something like this:
> 
> ```lua
> function onUpdate(e)
>     if getProperty('health') <= 0.39 then
>         triggerEvent('Change Character', 'bf', 'your character') --values may need to be swapped as I don't remember the change character values and I'm too lazy to look it up
>     end
> end
> ```

This works! Thank you so much!

**Comment by CaptainBaldi** [comment]
> Maybe try something like this:
> 
> ```lua
> function onUpdate(e)
>     if getProperty('health') <= 0.39 then
>         triggerEvent('Change Character', 'bf', 'your character') --values may need to be swapped as I don't remember the change character values and I'm too lazy to look it up
>     end
> end
> ```

friendly reminder `getProperty('healthBar.percent')` exists
