### ISSUE TITLE
Psych Engine Startup Problem (FIXED)

### ISSUE THREAD

**Issue by YourRedditor** [ShadowMario/FNF-PsychEngine#10854]
### Describe your bug here.

Every time I open Psych Engine the game window will pop up but I will get stuck on 0 fps and never start

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by YourRedditor** [comment]
All I had to do was delete the Psych Engine Appdata folder

**Comment by itsDARK768** [comment]
The issue will usually happen if the fps cap was set to something invalid.

**Comment by frantastic24** [comment]
Close the issue
