### ISSUE TITLE
an error loading a sprite sheet

### ISSUE THREAD

**Issue by Tamir-YT** [ShadowMario/FNF-PsychEngine#10852]
### Describe your bug here.

hello, i got this while loading the sprite sheet

flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
editors/CharacterEditorState.hx (line 840)
editors/CharacterEditorState.hx (line 520)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

how do i fix it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i'll not explain

**Comment by frantastic24** [comment]
Not a bug
Missing .xml

**Comment by Tamir-YT** [comment]
OH YOU'RE RIGHT THANK YOU
