### ISSUE TITLE
Arrow Bugs

### ISSUE THREAD

**Issue by khuonghoanghuy** [ShadowMario/FNF-PsychEngine#10857]
### Describe your bug here.

When i hold a note, pause the game while i hold key bind, stop hold the key arrow while i pause the game, return the game but the arrow **still** in a hold animation

i using Psych Engine 0.6.2

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

none edit something

**Comment by MemeHoovy** [comment]
I'm pretty sure I've seen something like this happen before

**Comment by MemeHoovy** [comment]
might make a PR that fixes this
