### ISSUE TITLE
64 but is not automatically supported

### ISSUE THREAD

**Issue by Raxusd** [ShadowMario/FNF-PsychEngine#10853]
### Describe your problem here.

 code:Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing edited

**Comment by DisIsNOt** [comment]
fucking install VSC 2019

**Comment by MemeHoovy** [comment]
> fucking install VSC 2019

Visual studio 2019, VSC means visual studio code
