### ISSUE TITLE
Opening a song

### ISSUE THREAD

**Issue by Ethian876** [ShadowMario/FNF-PsychEngine#10855]
### Describe your bug here.

I open the song and this is what I get:
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
Character.hx (line 164)
PlayState.hx (line 1007)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

only in mods folder

**Comment by frantastic24** [comment]
Not a bug
Character is missing texture files

**Comment by Ethian876** [comment]
what are those

**Comment by Ethian876** [comment]
and how do i fix it

**Comment by MemeHoovy** [comment]
if your literally too stupid to understand what a character image is then we can't help you

**Comment by Ethian876** [comment]
ok man jeez it was untold loneliness
