### ISSUE TITLE
this there a porblem?

### ISSUE THREAD

**Issue by cooldude47980597** [ShadowMario/FNF-PsychEngine#10864]
### Describe your problem here.

source/FunkinLua.hx:613: lines 613-617 : Int should be Bool
source/FunkinLua.hx:613: lines 613-617 : ... For function argument 'f'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHoovy** [comment]
it's on the readme
```haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit```

**Comment by cooldude47980597** [comment]
Nah
