### ISSUE TITLE
Arrow Directions ModChart

### ISSUE THREAD

**Issue by zeadd21g1233** [ShadowMario/FNF-PsychEngine#10865]
### Describe your problem here.

How To Change Arrow Directions in mid song like To Downscroll and it Changes To Up Scroll 
or one note go To Up Scroll and other Notes is Down Scroll

i try that

 daNote.distance = (0.45 * (Conductor.songPosition - daNote.strumTime) * songSpeed);

And The Notes Is Glitched And The Code Used In Downscroll Why It Glitched

Something like That

ModChart in Source Code

No lua I know how to make it in lua My Build Is Source So No Lua Here

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope Nothing Work

**Comment by Drawoon2** [comment]
`noteTweenDirection(TAG, Int=NoteId, 0-360, float, 'circInOut')`
