### ISSUE TITLE
source/MainMenuState.hx:43: characters 5-12 : Expected }

### ISSUE THREAD

**Issue by Warlokk28** [ShadowMario/FNF-PsychEngine#10860]
### Describe your bug here.

hello,in source code i am want to make my engine,but,it gives me errer source/MainMenuState.hx:43: characters 5-12 : Expected }
can someone help me? please

### Command Prompt/Terminal logs (if existing)

```bash
source/MainMenuState.hx:43: characters 5-12 : Expected }
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i edit PlayState.hxand MainMenuState.hx

**Comment by TheKitBoi** [comment]
You need to add the }
p̶e̶o̶p̶l̶e̶ ̶t̶h̶e̶s̶e̶ ̶d̶a̶y̶s̶ ̶n̶e̶v̶e̶r̶ ̶r̶e̶s̶e̶a̶r̶c̶h̶

**Comment by ShadowMario** [comment]
send the MainMenuState.hx code or we can't do anything

**Comment by cooldude47980597** [comment]
> send the MainMenuState.hx code or we can't do anything

Shadow why the fuck did you comment???

**Comment by Lorekeeper49** [comment]
> > send the MainMenuState.hx code or we can't do anything
> 
> Shadow why the fuck did you comment???

Because he's the owner and can give feedback on the issues provided by people who use his stuff, like everyone else who creates stuff like this.

**Comment by cooldude47980597** [comment]
> > > send the MainMenuState.hx code or we can't do anything
> > 
> > 
> > Shadow why the fuck did you comment???
> 
> Because he's the owner and can give feedback on the issues provided by people who use his stuff, like everyone else who creates stuff like this.

Oh, dont other people comment? not him???????

**Comment by KillerAvecRage** [comment]
Send line 43 of MainMenuState.hx

**Comment by Warlokk28** [comment]
i dont have the error now,i fixed it

**Comment by CrusherNotDrip** [comment]
> i dont have the error now,i fixed it

then close the issue

**Comment by TheKitBoi** [comment]
> i dont have the error now,i fixed it

![close the dam issue](https://user-images.githubusercontent.com/84044666/201208334-4dc4046f-aa50-4195-8383-8ac7e42274fa.gif)
