### ISSUE TITLE
How do you move each main menu item individually

### ISSUE THREAD

**Issue by SuperWA-HOOMan** [ShadowMario/FNF-PsychEngine#10867]
### Describe your problem here.

So I'm trying to edit the main menu, and part of that is moving each of the menu items individually. The thing is that all of the menu items seem to be grouped together in MainMenuState.hx. So how do i do this

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I've changed MainMenuState.hx and PlayState.hx

**Comment by CaptainBaldi** [comment]
![image](https://user-images.githubusercontent.com/86160807/196011820-51a59def-6ef3-4c00-82bc-9714006d7bd0.png)

the menu sprites are made in a for loop that 'groups' them together. You would have to mess with this to make them not group.
How? Idk, I don't do source man
