### ISSUE TITLE
Toggle trail colors

### ISSUE THREAD

**Issue by hotpocketsarepoggers** [ShadowMario/FNF-PsychEngine#10863]
### Describe your problem here.

Using the Toggle Trail event from the mind games mod is it possible to make it so depending on what note is hit the color of the trail changes?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
just change the color variable

**Comment by hotpocketsarepoggers** [comment]
> just change the color variable

I know that but I want it to change between 4 colors depending on what note is hit

**Comment by frantastic24** [comment]
The wiki has a list of callbacks

**Comment by DisIsNOt** [comment]
function goodNoteHit()

**Comment by hotpocketsarepoggers** [comment]
I know which function to use Im just not sure how to add more than 1 color then make it change

**Comment by hotpocketsarepoggers** [comment]
I should explain it better. I'm trying to make it so each frame of the trail is a different color so like if bf does hits a 'up' then 'down' note, his up animation in the trail will always be a green color while down would always be blue. If that helps explain it better
