### ISSUE TITLE
Shadow Mario closing issues

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#10868]
### What is your question?

Shadow Mario would sometimes close issues for no apparent reason
#9385

Is this a mistake SM made or is it because the thing the issue was describing is just not possible????

**Comment by MemeHoovy** [comment]
it's likely due to inactivity

**Comment by TFLTV** [comment]
> it's likely due to inactivity

Ah, makes sense.  I'll just open another issue if that's ok.
