### ISSUE TITLE
The ver 6.0 onwards game doesn't open ;-;

### ISSUE THREAD

**Issue by BonnieFan2000** [ShadowMario/FNF-PsychEngine#10878]
### Describe your bug here.

Hello, I'm here to report an issue with Psych Engine version 6.0 onwards, I double-click on the game's icon but it doesn't open, what should I do in this case?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just wanted to open the game

**Comment by MemeHoovy** [comment]
any errors that appear?

**Comment by BonnieFan2000** [comment]
Nope, it just doesn't open, I double-click on it, it loads, but doesn't open

**Comment by MemeHoovy** [comment]
well idk, reinstall psych engine or something or just don't use 0.6 or above since nobody seems to like those versions

**Comment by BonnieFan2000** [comment]
Tried many times, still didn't opened

**Comment by frantastic24** [comment]
it may be your system blocking it

**Comment by ShadowMario** [comment]
Delete your save data. `%appdata%/Roaming/ShadowMario/FNF-PsychEngine`
