### ISSUE TITLE
How to make a randomizer that picks a number and in a specific number it brings you to a song??

### ISSUE THREAD

**Issue by RushMyster** [ShadowMario/FNF-PsychEngine#10877]
### Describe your problem here.

Kinda a hard question but i need this for my mod!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
`getRandomInt()`

**Comment by Chidubemmo** [comment]
> `getRandomInt()`

I think you need to use source since lua only works in Playstate which is were stages, character, events, and the chart are played.
I suppose you would want to do it in like the Main Menu or freeplay

**Comment by frantastic24** [comment]
They didn't explain what they want to do at all so you can't go into specifics

**Comment by Draconic-Hybrid** [comment]
There's also math.random()
