### ISSUE TITLE
Cool Arrow effects and Randomized menu song

### ISSUE THREAD

**Issue by ElPro7777** [ShadowMario/FNF-PsychEngine#10875]
### What feature do you want to get added on the **base** engine?

Cool Arrow effects and Randomized menu song
Like Arrows moving or rotating and the Randomized menu song its like if you start again the game or beating a song the menu song will be different

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
You can already mess with strums

**Comment by cooldude47980597** [comment]
this idea is worthless
