### ISSUE TITLE
Help me please!

### ISSUE THREAD

**Issue by SprialNebula** [ShadowMario/FNF-PsychEngine#10870]
### Describe your bug here.

I load up psych engine, go to freeplay, and load up a song from there. But then, a few seconds later, I end up with this:

Error!

Note.hx (line 158)
PlayState.hx (line 2494)
PlayState.hx (line 1084)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

Can you help me please? The song's json file is there, so it can't be that. And this happened in two different songs.
Help me please.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

ported a few dave and bambi mods into the build

**Comment by KillerAvecRage** [comment]
You are missing a note texture, check your chart by the .json to see what notes you need to put

**Comment by SprialNebula** [comment]
> You are missing a note texture, check your chart by the .json to see what notes you need to put

ok

**Comment by SprialNebula** [comment]
alright I'll try

**Comment by SprialNebula** [comment]
yep I see the problem now
