### ISSUE TITLE
How To Make Characters Go Out Of The Screen

### ISSUE THREAD

**Issue by TacoGH** [ShadowMario/FNF-PsychEngine#10879]
### Describe your problem here.

How to make pop out of the screen like this :
https://youtu.be/z8aEaWbFPo8?t=135
heres a sreenshot
![image](https://user-images.githubusercontent.com/98825505/196061087-a63236e9-2430-4192-8dc5-2f9b61511e91.png)

can anyone send some code where i put it?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No i didnt change any yet (so far)

**Comment by MemeHoovy** [comment]
https://github.com/MoldyGH/VsDave

**Comment by impostor5875** [comment]
make a new window that's borderless and transparent, then render the pixels of the dad character

in other words: https://github.com/MoldyGH/VsDave

**Comment by TacoGH** [comment]
> make a new window that's borderless and transparent, then render the pixels of the dad character
> 
> in other words: https://github.com/MoldyGH/VsDave

how though?
