### ISSUE TITLE
doTweenZoom() returns to normal

### ISSUE THREAD

**Issue by SilverSnow07** [ShadowMario/FNF-PsychEngine#10872]
### Describe your bug here.

For some reason, the command `doTweenZoom()` will return to the original camera zoom without staying at its given zoom, and I don't know how to fix this.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Change `defaultCamZoom`

**Comment by SilverSnow07** [comment]
I want to temporarily keep, let's say, 2 times the default camera zoom on a specific part and then change it back to default, so changing the default camera zoom on the stage isn't helping.

**Comment by frantastic24** [comment]
It's a PlayState variable, change that, not the one in your stage

**Comment by SilverSnow07** [comment]
So it works with `setProperty('defaultCamZoom',_value_)`, but it's still a bit weird how the original command snaps back to its original value. Thanks for the answer!
