### ISSUE TITLE
Character Scale.

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#1087]
### Describe your bug here.

Psych Engine (4.2 Windows 64bit)
Hi,
so for some reason when the scale doesn't work.
Since the character is too small I wanted to make it bigger and used a scale of 1.3
But when the character is loaded it is still small. I tried restarting but nothing changes

here's a video/gif:
![megaawesomegif](https://user-images.githubusercontent.com/87707926/142214824-f9d48097-1f3a-448a-aab6-a18f85fc710c.gif)

Here's a picture of the json
![Screenshot (119)](https://user-images.githubusercontent.com/87707926/142215091-154cceb3-fa45-4c10-8ea9-c937926db88f.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added new options like old healthbar, new rating.

**Comment by lemz1** [comment]
I already saved it

**Comment by ShadowMario** [comment]
If you saved it outside of the export folder, you have to recompile.
