### ISSUE TITLE
stupid poopoo glitch that makes me have a brain aneurysm every time

### ISSUE THREAD

**Issue by NotNimu** [ShadowMario/FNF-PsychEngine#10885]
### Describe your bug here.

https://user-images.githubusercontent.com/115769608/196311123-766de81e-095b-4df6-bdd0-f74c4a7784bd.mp4

my build is psych 0.6.2

As you can see here, Well...  I cant describe it.
all i know is that it prevents typing xml data,
note that you have to SAVE THE JSON AND RELOAD THE ENTIRE CHARACTER EDITOR TO MAKE IT (SOMETIMES) WORK

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i legit changed nothing, no mod packs, just charts and lua code that does nothing

**Comment by ShadowMario** [comment]
Zoom issue, it's already fixed on the Actions build
