### ISSUE TITLE
Shaders

### ISSUE THREAD

**Issue by Jevilm** [ShadowMario/FNF-PsychEngine#10888]
### Describe your bug here.

I added a shader to a background, when i pause the game the shader appears on the pause screen, when i change the camera or callback it either doesnt work

https://user-images.githubusercontent.com/110422450/196433377-a8d2a93e-fc86-4d06-9049-ac1d15196da1.mp4

If the quality is bad im sorry

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Shaders, on 0.6.3

**Comment by Jevilm** [comment]
here code
local shadname = "wavy"
function onCreatePost()
        initLuaShader(shadname)
    
    makeLuaSprite("grapshad")
    makeGraphic("grapshad", screenWidth, screenHeight)
        setSpriteShader("grapshad", shadname)
        addHaxeLibrary("ShaderFilter", "openfl.filters")
        runHaxeCode([[
	  game.camOther.setFilters([new ShaderFilter(game.getLuaObject("grapshad").shader)]);
    ]])  
	
end

function wavytime(xwave,ywave,xtime,ytime)
	setShaderFloat('grapshad','xwave',xwave)
	setShaderFloat('grapshad','ywave',ywave)
	setShaderFloat('grapshad','xtime',xtime)
	setShaderFloat('grapshad','ytime',ytime)
end
function onUpdatePost(elapsed)
		wavytime(8,5,8,5)
    setShaderFloat("grapshad", "iTime", os.clock())
    setSpriteShader("redsky", shadname)
end

**Comment by Jevilm** [comment]
Is there a way to fix it? like making a new camera or something?

**Comment by EyeDaleHim** [comment]
No dude why the fuck would you apply it to `camOther` in the first place

**Comment by Jevilm** [comment]
because if i do it to any other camera it wont even work like damn chill out

**Comment by EyeDaleHim** [comment]
Although I deal with the stupidest things I've seen, why the hell were you setting a shader to `camOther`? It serves no purpose.

**Comment by Jevilm** [comment]
> Although I deal with the stupidest things I've seen, why the hell were you setting a shader to `camOther`? It serves no purpose.
> 
> I don't care about "but it doesn't work", I want to actually know why.

WHAT OTHER CAMERAS ARE THERE THEN???? HUH?????

**Comment by Jevilm** [comment]
Im closing this im about to go fucking insane

**Comment by Jevilm** [comment]
fuck

**Comment by Jevilm** [comment]
> Its camGame not camOther stupid dnb fan.

Also, im not the stupid one here, if i set it to camgame then the characters also turn wavy

**Comment by EyeDaleHim** [comment]
> > Its camGame not camOther stupid dnb fan.
> 
> Also, im not the stupid one here, if i set it to camgame then the characters also turn wavy

What exactly do you want? You never gave a reason why you (supposedly) needed to set a filter to `camOther`, just remove that line dawg.

**Comment by Jevilm** [comment]
https://user-images.githubusercontent.com/110422450/196505688-a452aa95-dbb2-44d7-8ab9-6b23cbd2b886.mp4

Thats what happens when i remove the code

**Comment by EyeDaleHim** [comment]
ok maybe ill just leave since i dont wanna waste time on a closed issue

**Comment by BernardoGP4504** [comment]
Apply the shader on the bg element idiot 🤦🏻‍♂️
