### ISSUE TITLE
Somethings Wrong

### ISSUE THREAD

**Issue by sans400** [ShadowMario/FNF-PsychEngine#10883]
### Describe your bug here.

Everytime I Try To Do The Command, Lime Test Windows, The Game Doesn't Open, And Gives Me 2 Errors.
![Screenshot 2022-10-17 200433](https://user-images.githubusercontent.com/78706113/196305642-10b6b635-cb45-47e6-97e4-34e2b55abd15.png) Please Help Me.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, It's A Brand New Download Of Version 0.6.2 I Just Got.

**Comment by cooldude47980597** [comment]
make sure your running 0.6.3 not 0.6.2
