### ISSUE TITLE
Question about the dialogue portrait editor system

### ISSUE THREAD

**Issue by Yoshi-RBLX** [ShadowMario/FNF-PsychEngine#10884]
### Describe your problem here.

So is there a way I can add in just regular png images without xmls, like in Dave and Bambi, they're just solid images and don't require any xml files, if I try to load just the image I get a crash. Do I just make an empty xml?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
XML files tell the game where to crop textures to make animations, so yes you do need it

**Comment by Mastercopper2346** [comment]
You can make a one-frame image yes, but not exactly without an xml :/

**Comment by voxovistired** [comment]
If you’re editing through source you could easily make the dialogue shit only require just a singular bitmap. But through Lua you’re going to need a bitmap that acquires an XML.
