### ISSUE TITLE
Psych Engine 0.6.3 x86 build is not actually a 32-bit build.

### ISSUE THREAD

**Issue by VirtMTTR** [ShadowMario/FNF-PsychEngine#10887]
### What is your question?

This was probably just a mistake but I'd just like to point out that the 32-bit build isn't actually 32-bit. And I did redownload it to be sure and made sure to click on the 32-bit download.

Just wanted to notify you about it!
![image](https://user-images.githubusercontent.com/115607391/196363105-3ab645ac-d3d8-4408-97ff-c6e7bb053177.png)

**Comment by Jevilm** [comment]
Yeah, but thats an old version of windows damn

**Comment by MemeHoovy** [comment]
exactly

**Comment by MemeHoovy** [comment]
> Yeah, but thats an old version of windows damn

I know a friend who still uses Windows 8 to this day
