### ISSUE TITLE
Aspect Ratio Change

### ISSUE THREAD

**Issue by rejoicreborn** [ShadowMario/FNF-PsychEngine#10882]
### Describe your problem here.

I am working on a mod rn and I wanted to do a free play level but I thought for this level I needed a specific aspect ratio. I wanted to the one they did in Fatality. Can you please tell me how to do that in Psych engine? Or is that not available?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by NotNimu** [comment]
I needed this too lmao

**Comment by Drawoon2** [comment]
Test this
`runHaxeCode([[
    FlxG.resizeWindow(640, 360)
]])`

**Comment by MemeHoovy** [comment]
https://github.com/DuskieWhy/exe-2.5-code
