### ISSUE TITLE
Shader Help (small question hopefully)

### ISSUE THREAD

**Issue by YKoF-CALm** [ShadowMario/FNF-PsychEngine#10886]
### What is your question?

Quick question: How do you disable a shader after initializing it?

**Comment by CaptainBaldi** [comment]
`removeSpriteShader(obj:String)`

**Comment by YKoF-CALm** [comment]
I tried that, but it didn't remove the shader. It's still there.

**Comment by YKoF-CALm** [comment]
Wait, am I able to use `setSpriteShader` without using `initLuaShader`?

**Comment by YKoF-CALm** [comment]
NVM, apparently I figured it out haha.
On a side note (just out of curiosity), anyone able to find a Psych Engine shader pack for public use?
