### ISSUE TITLE
how the fuck do i use setVar lmao

### ISSUE THREAD

**Issue by CaptainBaldi** [ShadowMario/FNF-PsychEngine#10890]
### Describe your problem here.

i know im gonna look really fucking stupid for asking this cause its probably one tiny ass problem but um
how the fuck to i use HScript's setVar?
this is my code 
![image](https://user-images.githubusercontent.com/86160807/196532120-4825f83f-9a24-40d7-a3b3-fc10b88f8087.png)
I legit have no fuckin idea why this doesn't work lmao

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

im trying to make a game in psych engine lua if that helps lmao

**Comment by MemeHoovy** [comment]
`interp.variables.set('setVar', function(name:String, value:Dynamic)`

**Comment by CaptainBaldi** [comment]
> `interp.variables.set('setVar', function(name:String, value:Dynamic)` dynamic can be anything

i probably explained this poorly lmao
i know what to put in the arguments, the problem is i cant get it to actually set the value
the example variable i showed here still remains 0, and does not become 1, which is what I put in setVar

**Comment by MemeHoovy** [comment]
how odd

**Comment by CaptainBaldi** [comment]
> notebooks should be a string

![image](https://user-images.githubusercontent.com/86160807/196537784-1c073e85-0e4c-4431-b72f-4f6fb8a80a91.png)
nope, still returns 0 when printing

**Comment by frantastic24** [comment]
Are you talking about `debugPrint`? Because that's returning the variable in your _lua script_, which never changes so it will be 0
