### ISSUE TITLE
Make the Real 32 Bits Build

### ISSUE THREAD

**Issue by ElPro7777** [ShadowMario/FNF-PsychEngine#10895]
### What feature do you want to get added on the **base** engine?

Make the Real 32 Bits Build
Because i am stuck now 0.6.2 (I have a 32 Bits PC)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

### Make The Real 32 Bits Build For 0.6.3

YES

**Comment by ShadowMario** [comment]
IDK why but it doesn't compile as 32 bits anymore

**Comment by ElPro7777** [comment]
> IDK why but it doesn't compile as 32 bits anymore
You tried to see if you messed up something on the .bat file?

**Comment by ShadowMario** [comment]
> > IDK why but it doesn't compile as 32 bits anymore
> > You tried to see if you messed up something on the .bat file?

I did.

**Comment by ElPro7777** [comment]
> > > IDK why but it doesn't compile as 32 bits anymore
> > > You tried to see if you messed up something on the .bat file?
> n
> I did.

Try to uhh see if something on the source is incorrect?

**Comment by BeastlyGhost** [comment]
lime did something on 8.0 that basically broke 32 bit support

either they are fixing it, or they will never fix it

which sadly might mean that 32 bit *flixel games that use lime as a compiler* might officially be deprecated
