### ISSUE TITLE
Old Mods Broken

### ISSUE THREAD

**Issue by Martinelplayz** [ShadowMario/FNF-PsychEngine#10897]
### Describe your bug here.

I am working on the mods  "FNF Drago Edition", "Margherita mix Deluxe", and "Friday Night Animators" with a team of people and this new update completely *Destroyed* the mods. none of the scripts, or events, are compatible anymore (and i have retested them). is there a way to fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by NotNimu** [comment]
Me when backwards compatibility brocken for the 918912023363692262826th time
![C447F67F-856E-4BAC-936F-299CA96125FD](https://user-images.githubusercontent.com/115769608/196584039-955e4ae8-0060-46fe-a3e1-b9f5757ed30f.jpeg)

**Comment by CaptainBaldi** [comment]
idk how you mfs keep breaking shit ive ported my 1 port across several different versions (from 0.5.2 to 0.6.3) and it works perfectly fine with no issues

**Comment by NotNimu** [comment]
> idk how you mfs keep breaking shit ive ported my 1 port across several different versions (from 0.5.2 to 0.6.3) and it works perfectly fine with no issues

Most likely due to unstable code that has been changed in a source update. (Aka: spaghetti code)
