### ISSUE TITLE
Speaking out on this entire repo's issue

### ISSUE THREAD

**Issue by ghost** [ShadowMario/FNF-PsychEngine#10896]
### What is your question? (Btw fix the damn 32 build)

**:[Successfully joined psych engine wiki]:**
![136CF404-A26A-499E-8824-7FFBEE8D83DC](https://user-images.githubusercontent.com/115769608/196582456-0692789c-3a82-4d40-b4c4-0167fa7eba3a.gif)

After the **GrandmasKisses** incident that legit took 4 seconds for them to get banned, I thought I would take the time in my life to actually address the issue with this repo

Think of it though, we get either trolls with their alt being banned in like 6 hours (I’m a retired troll so trust me) or you can find dumbasses with an iq of 2 merging every branch in a 6 mile radius thinking it’s “good code”

And of course, people who fail the test and make a shitty """"issue"""" That you could’ve easily prevented by making discussions **N O T** disabled. 

TD:LR: **everyone here is a dumbass in one or six ways**

**Comment by MemeHoovy** [comment]
agreed

**Comment by CaptainBaldi** [comment]
true

**Comment by Meme1079** [comment]
I 100% agreed with you

**Comment by ManMaster707** [comment]
You're absolutely right.

Now, let's talk about the discord server. *crouches down and covers ears*
*don't forget the helmet!*
![bullying](https://user-images.githubusercontent.com/101059988/196777511-e8994cb0-0fce-4f94-9a25-bbb3e4cffd1b.png)

**Comment by MemeHoovy** [comment]
dear oh dear

**Comment by NotNimu** [comment]
> > You're absolutely right.
> > Now, let's talk about the discord server. _crouches down and covers ears_
> > _don't forget the helmet!_
> > ![bullying](https://user-images.githubusercontent.com/101059988/196777511-e8994cb0-0fce-4f94-9a25-bbb3e4cffd1b.png)
> 
> toxic work environment but no one here is an employee so just a toxic environment

I don’t have discord. however, y’all could make an issue also exposing the server, while i expose the wiki! Deal?

**Comment by Grape-Boy** [comment]
what wiki tho

**Comment by Aidenkp112** [comment]
prob means this wiki dont quote me on that if its wrong tho (bet i wont yet will)

**Comment by NotNimu** [comment]
> prob means this wiki dont quote me on that if its wrong tho (bet i wont yet will)

Yeah this one

**Comment by NotNimu** [comment]
so I found these in the abyss that is his twitter acc

![37851EF2-C51A-44FC-A069-40606B946FA9](https://user-image
![EA89062F-AA07-4907-B566-171B72204E88](https://user-images.githubusercontent.com/115769608/196812290-0e9144b7-82d7-489b-95d9-9e42f60eb8ba.jpeg)
s.githubusercontent.com/115769608/196812282-7e06a646-cef4-4bd2-ae47-3caf92fc2597.jpeg)

**Comment by ManMaster707** [comment]
> > You're absolutely right.
> > Now, let's talk about the discord server. _crouches down and covers ears_
> > _don't forget the helmet!_
> > ![bullying](https://user-images.githubusercontent.com/101059988/196777511-e8994cb0-0fce-4f94-9a25-bbb3e4cffd1b.png)
> 
> toxic work environment but no one here is an employee so just a toxic environment

☝️
