### ISSUE TITLE
Changing background scale in lua

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#1089]
### Describe your problem here.

the background is too big!
how do I make it smaller?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed the note texture

**Comment by titopops** [comment]
Since your using lua, use "scaleObject" seen here, because it makes the image larger
![image](https://user-images.githubusercontent.com/93490646/142293411-7b6b1e9d-85ab-413a-8728-295bac442f26.png)
