### ISSUE TITLE
Dialogue not Loading in the week

### ISSUE THREAD

**Issue by QuagFire101** [ShadowMario/FNF-PsychEngine#109]
Hello! So, I am trying to write dialogue for my mod but it doesn't seem to be working. I made the dialogue .json file, and a script lua file which looks like this
![image](https://user-images.githubusercontent.com/90576570/134428810-60c622fe-5508-4600-ac1e-e92661168cd2.png)

And put it in the song folder so it currently works like this
![image](https://user-images.githubusercontent.com/90576570/134428857-aa7245e8-363d-4482-a8b1-bc8507206677.png)

The dialogue doesn't crash when I open it in the editor and everything is laid out perfectly, so I'm not sure why the dialogue is not loading in the week.

Granted the only song done for that week is the song where this dialogue plays, so I assume that may be what the problem is. Whatever the case, can you help me figure out what may be the issue here? Because I did everything basically perfectly.

**Comment by ShadowMario** [comment]
[Try downloading the new example script.](https://cdn.discordapp.com/attachments/866856727621795850/890335034786062336/script.lua)

**Comment by QuagFire101** [comment]
It still isn't working right. It still skips over the dialogue.json file. And according to the Powershell its LOADING the script, so I'm not sure what the problem is.

Am I supposed to edit the script or could it be some other problem?

**Comment by ShadowMario** [comment]
Check your version.
