### ISSUE TITLE
Engine may crash unexpectedly after updated to 0.6.3

### ISSUE THREAD

**Issue by YKoF-CALm** [ShadowMario/FNF-PsychEngine#10904]
### Describe your bug here.

I honestly don't know if this is a bug, but I've only encountered it now, and this thing has worked before, so whatever.

Basically, my game crashes at the post-song dialogue, which is hella confusing, since it didn't do that before.

Here's the script:

```
local dia1 = false
local dia2 = false
local blockEnd = true

function onStartCountdown()
	if not dia1 then
		setProperty('inCutscene', true)
		runTimer('startDialogue', 0.8)
        dia1 = true
		return Function_Stop
	end
	return Function_Continue
end

function onEndSong()
    if blockEnd then
		if not dia2 then
			dia2 = true
        	setProperty('inCutscene', true)
			startDialogue('dialogue2')
			runTimer('delayEnd', 300)
		end
		return Function_Stop;
	end
	return Funtion_Continue;
end

function onNextDialogue(count)
	if count >= 149 then
        runTimer('endthethingalready', 20)
        blockEnd = false
		cancelTimer('delayEnd')
	end
end

function onTimerCompleted(tag, loops, loopsLeft)
    if tag == 'startDialogue' then
		startDialogue('dialogue')
	end

    if tag == 'delayEnd' then
		blockEnd = false
		endSong()
	end

    if tag == 'endthethingalready' then
        blockEnd = false
        endSong()
    end
end
```

Someone please help, I'm honestly confused as to what's wrong here.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing (except for adding modpacks).

**Comment by CaptainBaldi** [comment]
jesus fucking christ this code is the messiest thing i have ever seen in my life

**Comment by elixioo** [comment]
> jesus fucking christ this code is the messiest thing i have ever seen in my life

LITERALLY

**Comment by TheKitBoi** [comment]
why send the whole thing
just find the line that cause shit

**Comment by YKoF-CALm** [comment]
I put the whole thing on there because I don't know what's causing the crash.

Here's the dialogue code, then. IDK what's causing the problem.

```

local dia1 = false
local dia2 = false
local blockEnd = true

function onStartCountdown()
	if not dia1 then
		setProperty('inCutscene', true)
		runTimer('startDialogue', 0.8)
        dia1 = true
		return Function_Stop
	end
	return Function_Continue
end

function onEndSong()
    if blockEnd then
		if not dia2 then
			dia2 = true
        	setProperty('inCutscene', true)
			startDialogue('dialogue2')
			runTimer('delayEnd', 300)
		end
		return Function_Stop;
	end
	return Funtion_Continue;
end

function onNextDialogue(count)
	if count >= 149 then
        runTimer('endthethingalready', 20)
        blockEnd = false
		cancelTimer('delayEnd')
	end
end

function onTimerCompleted(tag, loops, loopsLeft)
    if tag == 'idleresumesans' then
        sansIdle = true
    end

    if tag == 'idleresumebf' then
        bfIdle = true
    end

    if tag == 'startDialogue' then
		startDialogue('dialogue')
	end

    if tag == 'delayEnd' then
		blockEnd = false
		endSong()
	end

    if tag == 'endthethingalready' then
        blockEnd = false
        endSong()
    end
end
```

**Comment by Mastercopper2346** [comment]
wait a minute…

**Comment by Mastercopper2346** [comment]
https://github.com/Theoyeah/PsychEngineDiscussions/discussions/538

**Comment by YKoF-CALm** [comment]
Alright, I went and did some debugging. Turns out that Psych Engine might also crash in the middle of a Bad Time cover I did for no reason at all. This crashing problem is probably a bug in the engine update, and might need to be looked into, because for both crashing cases, they worked in 0.6.2.

**Comment by YKoF-CALm** [comment]
Okay, apparently I'm not alone, there's another issue with similar problems.
#10901
