### ISSUE TITLE
Higher quality saul

### ISSUE THREAD

**Issue by NotNimu** [ShadowMario/FNF-PsychEngine#10902]
### What feature do you want to get added on the **base** engine?

More saul, less memes, saul only.

![Saul png](https://user-images.githubusercontent.com/115769608/196587986-a90295f1-5b1e-4647-b693-a77cc0c82555.jpg)

![CC9C6171-559C-4C43-A452-8E0EB09E3390](https://user-images.githubusercontent.com/115769608/196588134-c5c18f77-9122-4fac-93b8-82c67ee196cd.gif)
(https://github.com/NotNimu/HigherQualitySaul)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Jevilm** [comment]
You arent funny

**Comment by CrusherNotDrip** [comment]
> You arent funny

its a good idea though

**Comment by CaptainBaldi** [comment]
> > You arent funny
> 
> its a good idea though

you arent funny either

**Comment by NotNimu** [comment]
> > > You arent funny
> > 
> > 
> > its a good idea though
> 
> you arent funny either

its a good idea though

**Comment by Jevilm** [comment]
> > > > You arent funny
> > > 
> > > 
> > > its a good idea though
> > 
> > 
> > you arent funny either
> 
> its a good idea though

You arent funny

**Comment by CrusherNotDrip** [comment]
> you arent funny either

I know 😁

**Comment by NotNimu** [comment]
> > > > > You arent funny
> > > > 
> > > > 
> > > > its a good idea though
> > > 
> > > 
> > > you arent funny either
> > 
> > 
> > its a good idea though
> 
> You arent funny

its a good idea though

**Comment by ShadowMario** [comment]
JPG 👎

**Comment by NotNimu** [comment]
PNG 👍
