### ISSUE TITLE
Alphabet Sprites

### ISSUE THREAD

**Issue by TheGuy-yeah** [ShadowMario/FNF-PsychEngine#10905]
### Describe your bug here.

the alphabets are just "%" instead other sprites in "mods" folder

### Command Prompt/Terminal logs (if existing)

```bash
please fix this or i'll quit this engine
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheGuy-yeah** [comment]
oh wait it just because the alphabet.xml changed.

**Comment by CrusherNotDrip** [comment]
ok if you know now then close the issue

**Comment by TheKitBoi** [comment]
![close the dam issue](https://user-images.githubusercontent.com/84044666/196744154-7883b5c9-1028-46bd-b25a-49e882c71ab5.gif)

**Comment by dombomb64** [comment]
I'm using a custom alphabet.xml, and even though a bold dollar sign exists in it, it just shows up as a question mark. Same for the tilde.

![image](https://user-images.githubusercontent.com/49823019/197420168-3171c7fe-eb13-4ee1-b75c-fc4542669c20.png)
![image](https://user-images.githubusercontent.com/49823019/197420256-6a26e934-6c81-494f-83f9-88641aed31bf.png)

(If you're wondering why I have a song name that's just a tilde repeated four times, they're supposed to be invisible to hide something below.)

**Comment by dombomb64** [comment]
Never mind. It's just that "bold" is always after the name now. At least it's more organized.
