### ISSUE TITLE
Chromebook

### ISSUE THREAD

**Issue by notahumans-official** [ShadowMario/FNF-PsychEngine#10907]
### What feature do you want to get added on the **base** engine?

Ok so I want to make an FNF mod, but I have a Chromebook, and can't get my hands on another computer. Could you please make a Chromebook edition of the engine? It would help a lot!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MemeHoovy** [comment]
lime can't compile to a Chromebook, but it can compile to Linux which chrome OS is based on

**Comment by notahumans-official** [comment]
Oh, ok. Thanks!
