### ISSUE TITLE
everything is % signs 

### ISSUE THREAD

**Issue by Begyosh** [ShadowMario/FNF-PsychEngine#10900]
### Describe your bug here.

so i download psych engine 6.3 and transferd all my data to the new one and now its all % signs now

https://user-images.githubusercontent.com/108202285/196585020-56f24d87-cafe-493c-bdcd-32a5604a7ad0.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i didnt edit anything, all i did was copy my data from the last psych engine to the new one

**Comment by NotNimu** [comment]
%%%%%%%%%%%%%%%%%%%%

**Comment by NotNimu** [comment]
> %%%%%%%%%%%%%%%%%%%%

Yeah this new update fucked everything up

**Comment by Begyosh** [comment]
is it this one? if it is, then it still doesnt work

![alphabet](https://user-images.githubusercontent.com/108202285/196586109-63966968-d157-468a-a85f-d6966b157e38.png)

**Comment by frantastic24** [comment]
Is the XML correct

**Comment by CaptainBaldi** [comment]
> > %%%%%%%%%%%%%%%%%%%%
> 
> Yeah this new update fucked everything up

actually it didn't
its ur fault if you ended up porting the wrong alphabet into the newer builds

**Comment by NotNimu** [comment]
Little comparison

![alphabet](https://user-images.githubusercontent.com/108202285/196586109-63966968-d157-468a-a85f-d6966b157e38.png)

![525FB824-D7A7-448D-97D3-0BDAAF5058BF](https://user-images.githubusercontent.com/115769608/196695721-2b307d23-f80e-43fe-b75d-ac813b57e22c.png)

**Comment by ShadowMario** [comment]
Alphabet.png is fucked up
