### ISSUE TITLE
Someone Help Me PLEASE

### ISSUE THREAD

**Issue by CopyDogOFC** [ShadowMario/FNF-PsychEngine#10915]
### Describe your bug here.

When I Compile The Source Only Compile Files But The Application Not I Use lime test windows Someone Help Me?

### To Be Clearer
When I Compile Psych Source Its Only Compile The Other Files But The .exe Application Dont Compile Im Using lime test windows In Command Prompt I Have Haxe And All Can You Help Me?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I Edited Nothing

**Comment by CopyDogOFC** [comment]
> provide us an ss (screenshot) of the compilation.

ok

**Comment by CopyDogOFC** [comment]
![bug](https://user-images.githubusercontent.com/116233113/197421585-9da8969f-41ff-4fc7-991f-847eb91a6903.png)

**Comment by frantastic24** [comment]
that is the release folder, not the test one

**Comment by DabbinDude316B** [comment]
> recompile, kid. you fucking deleted the exe twat

Actually, when I started compiling (without VS), it didn’t provide the exe or **icon**.

**Comment by DabbinDude316B** [comment]
> pls someone help me

Install Visual Studio 2019 (only 2017 works for some reason)

**Comment by CopyDogOFC** [comment]
> > pls someone help me
> 
> Install Visual Studio 2019 (only 2017 works for some reason)

i will try thank you

**Comment by CopyDogOFC** [comment]
> recompile, kid. you fucking deleted the exe twat

no i dont deleted it

**Comment by DabbinDude316B** [comment]
> > recompile, kid. you fucking deleted the exe twat
> 
> no i dont deleted it

Don’t worry. He loves to beat up children with hate

**Comment by CopyDogOFC** [comment]
> > > recompile, kid. you fucking deleted the exe twat
> > 
> > 
> > no i dont deleted it
> 
> Don’t worry. He loves to beat up children with hate

ok im installing visual studio 2017 but what visual studio i use community

**Comment by CopyDogOFC** [comment]
> > pls someone help me
> 
> Install Visual Studio 2019 (only 2017 works for some reason)

Dont work its say:
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/MainMenuState.hx:82: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:424: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/CharacterEditorState.hx:94: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/DialogueCharacterEditorState.hx:87: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/StageEditorState.hx:123: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\Casa\Desktop\FNF-OSEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
