### ISSUE TITLE
Flashlight notes

### ISSUE THREAD

**Issue by SourDoseOfGG** [ShadowMario/FNF-PsychEngine#10913]
### What feature do you want to get added on the **base** engine?

flashlight notes
need to hit them to keep the light bright if you dont keep hitting them you DIE

### To test your sight, and reliability, please select the option of what should NOT be requested.

Thing that would not cause problems

**Comment by frantastic24** [comment]
Failed the test
Bad idea
Do it yourself

**Comment by bruh1cat** [comment]
This seems more like a request than a enhancement.

**Comment by CaptainBaldi** [comment]
this is a bad idea lmao

**Comment by MemeHoovy** [comment]
> ### What feature do you want to get added on the **base** engine?
> flashlight notes need to hit them to keep the light bright if you dont keep hitting them you DIE
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Thing that would not cause problems

this fucking sucks

**Comment by SourDoseOfGG** [comment]
ok like i have a thing so when you like press the note itll change the character and the bg

**Comment by CaptainBaldi** [comment]
> when you like press the note itll change the character and the bg

make it yourself lazybones

**Comment by CopyDogOFC** [comment]
cool idea but no sorry
