### ISSUE TITLE
Custom Keybind Notes 

### ISSUE THREAD

**Issue by ArthurYago** [ShadowMario/FNF-PsychEngine#10910]
### What is your question?

How do i make a note that only OTHER KEYBINDS can press? Like, if your default keybinds are D, F, J, K, BUT a specific note can only be hit using ◀️, 🔽, 🔼 and ▶️.

In LUA.

**Comment by MemeHoovy** [comment]
`keyPressed(keyname)`

**Comment by ArthurYago** [comment]
Nice but, the other keybinds would work too, and how do i make the note be FORCED to be hit?

**Comment by MemeHoovy** [comment]
`
if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
         setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', false);
`

**Comment by ArthurYago** [comment]
How it works? I was thinking about when the player presses any of the custom keybinds, the note gets hit, using the canBeHit stuff and noteHit

**Comment by MemeHoovy** [comment]
oh sorry that's for notetypes

**Comment by ArthurYago** [comment]
Lol

**Comment by ArthurYago** [comment]
noteWasHit*

**Comment by ArthurYago** [comment]
You can see some public variables at Note.hx, they might help a lot

**Comment by MemeHoovy** [comment]
NotewasHit seems to be unused

**Comment by MemeHoovy** [comment]
so it more or less does nothing

**Comment by MemeHoovy** [comment]
as for canBeHit...
`
setPropertyFromGroup('unspawnNotes', i, 'canBeHit', false);
`

**Comment by MemeHoovy** [comment]
oh scratch that, that's reserved aswell

**Comment by ArthurYago** [comment]
Like i said, maybe when the player presses a specific keybind, the canBeHit = false note turns into canBeHit = true and the note automatically gets hit (i know canBeHit doesn't work with the =)

**Comment by MemeHoovy** [comment]
yeah, but unfortunately it doesn't make it so it automatically hits the note though

**Comment by ArthurYago** [comment]
Wdym? Im not that good at English

**Comment by MemeHoovy** [comment]
> Wdym? Im not that good at English

it basically doesn't make it hit notes automatically from what I can tell

**Comment by ArthurYago** [comment]
F
