### ISSUE TITLE
I got problems with onEndSong() function

### ISSUE THREAD

**Issue by KillerAvecRage** [ShadowMario/FNF-PsychEngine#10918]
### Describe your bug here.

I wanted to make something like Parappa ratings in FNF, script that I made and tested on 0.6.2 and worked perfectly

But now, with 0.6.3, the game kills me because of bad accuracy really well

But if I finish a song with a "Bad" or "Awful" rating, it just completes the song

I tried onStepHit() instead of onUpdate() for the invicibility (because the ratings depend on the accuracy only so I have to make the life always full to prevent the game killing you because of health drain) and all I got was "getting killed but completing the song and coming back to freeplay"

Here is the full script:
`devmode = 0 --Lets you see the extremely precise frequency in game (1 = enabled)

function onCreate()
setProperty('ratingPercent', 0.91) --To not kill you at the start of the song
accuracy = getProperty('ratingPercent')
makeLuaText('rappin', "U rappin'            !", 0, 0, 328)
addLuaText('rappin')
setTextSize("rappin", "36")
setTextFont("rappin", "Parappa.otf");
makeLuaText('cool', "Cool", 0, 133, 292)
addLuaText('cool')
setTextSize("cool", "36")
setTextFont("cool", "Parappa.otf");
makeLuaText('Good', "Good", 0, 133, 328)
addLuaText('Good')
setTextSize("Good", "36")
setTextFont("Good", "Parappa.otf");
makeLuaText('Bad', "Bad", 0, 133, 364)
addLuaText('Bad')
setTextSize("Bad", "36")
setTextFont("Bad", "Parappa.otf");
makeLuaText('Awful', "Awful", 0, 133, 400)
addLuaText('Awful')
setTextSize("Awful", "36")
setTextFont("Awful", "Parappa.otf");
end

function onUpdate()
setProperty('scoreTxt.visible', false);
setProperty('iconP1.visible', false);
setProperty('iconP2.visible', false);
setProperty('healthBarBG.visible', false);
setProperty('healthBar.visible', false)
if devmode == 1 then
makeLuaText('accuracy', accuracy, 0, 250, 400)
addLuaText('accuracy')
end
if getProperty('ratingPercent') > 0.999 then --You can change this value, it's the 'COOL' rating
makeLuaText('rappin', "U rappin'          !", 0, 0, 292)
addLuaText('rappin')
setTextSize("rappin", "36")
setTextFont("rappin", "Parappa.otf");
elseif getProperty('ratingPercent') > 0.9 then --You can change this value, it's the 'GOOD' rating
makeLuaText('rappin', "U rappin'            !", 0, 0, 328)
addLuaText('rappin')
setTextSize("rappin", "36")
setTextFont("rappin", "Parappa.otf");
elseif getProperty('ratingPercent') > 0.8 then --You can change this value, it's the 'BAD' rating
makeLuaText('rappin', "U rappin'         !", 0, 0, 364)
addLuaText('rappin')
setTextSize("rappin", "36")
setTextFont("rappin", "Parappa.otf");
elseif getProperty('ratingPercent') > 0.70 then --You can change this value, it's the 'AWFUL' rating
makeLuaText('rappin', "U rappin'             !", 0, 0, 400)
addLuaText('rappin')
setTextSize("rappin", "36")
setTextFont("rappin", "Parappa.otf");
elseif getProperty('ratingPercent') < 0.70 then --You can change this value, it's the '-----' rating (kills you)
setProperty('health', -2)
end
end

function noteMiss(id, noteData, noteType, isSustainNote)
setProperty("health", 2)
if devmode == 1 then
accuracy = getProperty('ratingPercent')
makeLuaText('accuracy', accuracy, 0, 250, 400)
addLuaText('accuracy')
end
end

function goodNoteHit(id, noteData, noteType, isSustainNote)
if devmode == 1 then
accuracy = getProperty('ratingPercent')
makeLuaText('accuracy', accuracy, 0, 250, 400)
addLuaText('accuracy')
end
end

function onStepHit()
setProperty("health", 2)
end

function onEndSong()
if getProperty('ratingPercent') < 0.9 then --To check if you have a better rating than "Bad"
setProperty("health", -2)
end
end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by ZeitHeld** [comment]
you would simply need to stop the function from working to actually end it function_stop

**Comment by KillerAvecRage** [comment]
Closed issue, yeah you just need to stop it
