### ISSUE TITLE
What I Want In Psych

### ISSUE THREAD

**Issue by CopyDogOFC** [ShadowMario/FNF-PsychEngine#10925]
### What feature do you want to get added on the **base** engine?

Hello i want in psych engine: new events, wavy backgrounds for my mod and change character with zoom like Taimuresu (Expunged Song From Maveings) Thats All!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CaptainBaldi** [comment]
new events : make them urself
wavy backrounds : already possible outside of source code
change character with zoom : what

**Comment by CopyDogOFC** [comment]
> new events : make them urself wavy backrounds : already possible outside of source code change character with zoom : what

change character with zoom: change the caracter and do zoom like Taimuresu
and how i can make wavy backgrounds with no source

**Comment by CaptainBaldi** [comment]
> > new events : make them urself wavy backrounds : already possible outside of source code change character with zoom : what
> 
> change character with zoom: change the caracter and do zoom like Taimuresu and how i can make wavy backgrounds with no source

mf what the fuck is taimuresu 
and i could give you the wavy backround shit but im not cause i can tell you're only gonna use it for some shitty d&b mod with no effort whatsoever

**Comment by Mastercopper2346** [comment]
> ### What feature do you want to get added on the **base** engine?
> Hello i want in psych engine: new events, wavy backgrounds for my mod and change character with zoom like Taimuresu (Expunged Song From Maveings) Thats All!
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Stage Editor, 6K+ support, and winning icons.

Not to be mean, but CLOSE THIS BEFORE SHADOW BANS YOU

**Comment by CopyDogOFC** [comment]
> > ### What feature do you want to get added on the **base** engine?
> > Hello i want in psych engine: new events, wavy backgrounds for my mod and change character with zoom like Taimuresu (Expunged Song From Maveings) Thats All!
> > ### To test your sight, and reliability, please select the option of what should NOT be requested.
> > Stage Editor, 6K+ support, and winning icons.
> 
> Not to be mean, but CLOSE THIS BEFORE SHADOW BANS YOU

why

**Comment by CopyDogOFC** [comment]
> > > new events : make them urself wavy backrounds : already possible outside of source code change character with zoom : what
> > 
> > 
> > change character with zoom: change the caracter and do zoom like Taimuresu and how i can make wavy backgrounds with no source
> 
> mf what the fuck is taimuresu and i could give you the wavy backround shit but im not cause i can tell you're only gonna use it for some shitty d&b mod with no effort whatsoever

taimuresu is a fnf song bruh

**Comment by CopyDogOFC** [comment]
> > > new events : make them urself wavy backrounds : already possible outside of source code change character with zoom : what
> > 
> > 
> > change character with zoom: change the caracter and do zoom like Taimuresu and how i can make wavy backgrounds with no source
> 
> mf what the fuck is taimuresu and i could give you the wavy backround shit but im not cause i can tell you're only gonna use it for some shitty d&b mod with no effort whatsoever

just give me pls

**Comment by Jevilm** [comment]
> taimuresu is a fnf song bruh
Taimuresu is a "SONG"
also,  add your needs youself, im sure they are all possible in lua

**Comment by Jevilm** [comment]
> at this point, every FNF mod is trash and should be shielded away from the internet

I agree!! FNF mods are too modern psych engine now!! you probably dont understand a word i said!!
