### ISSUE TITLE
Opponents note skin

### ISSUE THREAD

**Issue by jaydin12341123** [ShadowMario/FNF-PsychEngine#10929]
### Describe your problem here.

How do i change the opponents note skin and keep bfs noteskin the same in source ive been trying to find a tutorial but i cant find any please help.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Justudude321** [comment]
This could work but bear in mind that you would need to add it in the override public function update part and add your stage there as a case
```
for (i in 0...unspawnNotes.length - 1) {
	if(!unspawnNotes[i].mustPress)unspawnNotes[i].texture = ur note skin; (String)
}
for (i in 0...opponentStrums.length) {
	opponentStrums.members[i].texture = ur note skin;
}
```

**Comment by Justudude321** [comment]
Sorry, I was giving my own answer to this.
