### ISSUE TITLE
I Want Psych Engine Add This

### ISSUE THREAD

**Issue by CopyDogOFC** [ShadowMario/FNF-PsychEngine#10922]
### What feature do you want to get added on the **base** engine?

Pls Add **Wavy Backgrounds Like Dave And Bambi Mods, In Settings Add Game Opimization, Fix Compile Bugs And Create New File 3D Objects :)**

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

### And Fuck You Guys This Is A Good Idea

**Comment by MemeHoovy** [comment]
fuck no

**Comment by NotNimu** [comment]
Shut the fuck up + Dave and bambi fan + ratio
https://user-images.githubusercontent.com/115769608/197066672-fbd86fd4-bf5f-41b0-9b02-3c81816de8e6.mp4

**Comment by CopyDogOFC** [comment]
you guys are a fucking idiots im a dave and bambi fan im creating a mod of it YOU GUYS SHUT THE FUCK UP GAYS

**Comment by CopyDogOFC** [comment]
> fuck no

fuck you imagine being anime fan

**Comment by CopyDogOFC** [comment]
> Shut the fuck up + Dave and bambi fan + ratio
> 
>  ssstwitter.com_1666297753734.mp4

imagine BEING FUCKING CRINGE

**Comment by CopyDogOFC** [comment]
i will fucking close this shit

**Comment by CopyDogOFC** [comment]
fuck you guys

**Comment by TheKitBoi** [comment]
You have the cheek to make a bait issue just to get hate on 
And try to hate them back
fuck off

**Comment by CopyDogOFC** [comment]
> You have the cheek to make a bait issue just to get hate on And try to hate them back fuck off

shut the fuck up kid

**Comment by CopyDogOFC** [comment]
> You have the cheek to make a bait issue just to get hate on And try to hate them back fuck off

motherfucker.

**Comment by CopyDogOFC** [comment]
os engine is better

**Comment by TheKitBoi** [comment]
you literally just created a account and attempt to be homophobic
![9AD670D0-EA7E-464F-A440-98951244CA4B](https://user-images.githubusercontent.com/84044666/197073767-02b3e515-205a-418b-807c-1ea67e8c7879.jpeg)

**Comment by CopyDogOFC** [comment]
> you literally just created a account and attempt to be homophobic ![9AD670D0-EA7E-464F-A440-98951244CA4B](https://user-images.githubusercontent.com/84044666/197073767-02b3e515-205a-418b-807c-1ea67e8c7879.jpeg)

i created because i fucked yo mom and imagine being sonic fan

**Comment by TheKitBoi** [comment]
it impossible to win an argument of someone being retarded

**Comment by CopyDogOFC** [comment]
i will fucking report you guys i will never hate dave and bambi mod and yes im retarded

**Comment by CopyDogOFC** [comment]
I WILL BLOCK YOU GUYS FOREVER

**Comment by CopyDogOFC** [comment]
YOU GUYS ARE FUCKING BULLYING ME FUCK YOU GUYS RATS

**Comment by CopyDogOFC** [comment]
holy shit

**Comment by CopyDogOFC** [comment]
> fuck no

furry

**Comment by CrusherNotDrip** [comment]
> os engine is better

its made from psych engine though
without psych it would be completely different

**Comment by Jevilm** [comment]
> > fuck no
> 
> furry

i dont have a fucking problem with furries like damn

**Comment by CrusherNotDrip** [comment]
> > > fuck no
> > furry
> i dont have a fucking problem with furries like damn

we wasnt talkin bout you

**Comment by Jevilm** [comment]
> > > > fuck no
> > > > furry
> > > > i dont have a fucking problem with furries like damn
> 
> we wasnt talkin bout you

a
