### ISSUE TITLE
How Do I Make Wavy Bg With LUA?

### ISSUE THREAD

**Issue by CopyDogOFC** [ShadowMario/FNF-PsychEngine#10926]
### What is your question?

How Do I Make Wavy Bg With LUA? (Like Dave And bambi)

**Comment by CaptainBaldi** [comment]
ok fr now pls fuck off

**Comment by CopyDogOFC** [comment]
> ok fr now pls fuck off

ok

**Comment by Jevilm** [comment]
i like dave and bambi this is why i always say "dont kill me" in my issues

**Comment by luigiman0** [comment]
Here's a video I saw recently that shows off how to do this.
https://www.youtube.com/watch?v=vy4GXWQbbr0
Hope this helps!

**Comment by kstr743** [comment]
here's the answer so yall will calm down (MUST BE RUNNING 0.6.3 or ACTIONS BUILD)


```
function onCreatePost()
    initLuaShader("shadername")

	makeLuaSprite('bgname','imagename',-300,-400)
	addLuaSprite('bgname',false)

    setSpriteShader("bgname", "shadername")
end
function onUpdate()
    setShaderFloat("bgname", "iTime", os.clock())
--exclusive to wavy shader, remove/modify if you're not using it!!!!
    setShaderFloat("bgname", "uWaveAmplitude", 0.1)
    setShaderFloat("bgname", "uSpeed", 2)
    setShaderFloat("bgname", "uFrequency", 5)
end
```

**Comment by CopyDogOFC** [comment]
> 

thank you

**Comment by imdumlol** [comment]
dos does not work
![Screenshot (130)](https://user-images.githubusercontent.com/118001986/210042485-6ac14b19-864e-4ad9-abfb-533d42741e0f.png)
