### ISSUE TITLE
Combo Restored

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#10923]
### What is your question?

Hello, I actually want to restore the combo text and, in the settings of combo delay and that stuff, change or move the combo text to the position I want. If someone can help me, pls tell me how. I would aprecciate it a lot.

> NOTE: I am using the source code.

**Comment by MemeHoovy** [comment]
`add(comboSpr);`
under
`
comboSpr.velocity.x += FlxG.random.int(1, 10) * playbackRate;
`

**Comment by GatoMorado621** [comment]
> `add(comboSpr);` under `comboSpr.velocity.x += FlxG.random.int(1, 10) * playbackRate;`

But in which hx file???

**Comment by GatoMorado621** [comment]
> `add(comboSpr);` under `comboSpr.velocity.x += FlxG.random.int(1, 10) * playbackRate;`

I just put `add(comboSpr)` and in the settings dosen't appear for change the postions

**Comment by GatoMorado621** [comment]
> `add(comboSpr);` under `comboSpr.velocity.x += FlxG.random.int(1, 10) * playbackRate;`

It dosen't see the combo text on the settings of combo offset for change the position

**Comment by MemeHoovy** [comment]
because it ain't in there at all

**Comment by GatoMorado621** [comment]
> because it ain't in there at all

Oh... ok. Thanks for the help anyways, ty 😊

**Comment by MemeHoovy** [comment]
yeah, np
