### ISSUE TITLE
How can i stop this?

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#10920]
### What is your question?

How can i stop the feedback popping up when i hit a note (canceling the tween so it appears statically)
![i tried to provide a image](https://user-images.githubusercontent.com/101405920/197051869-280eb1dc-6fd7-47f4-9f00-dce56a98a093.png)

**Comment by CopyDogOFC** [comment]
uhm

**Comment by VoidedBattery** [comment]
What kind of feedback is popping up?

**Comment by BernardoGP4504** [comment]
You don't know?

Em qui, 20 de out de 2022 18:00, CopyDogOFC ***@***.***>
escreveu:

**Comment by frantastic24** [comment]
Hide the hardcoded ones and make them yourself

**Comment by BernardoGP4504** [comment]
> What kind of feedback is popping up?
Sick but with a different graphic

**Comment by frantastic24** [comment]
> Ok but can you send the code for it?

No

**Comment by BernardoGP4504** [comment]
Why not

Em qui, 20 de out de 2022 18:59, frantastic24 ***@***.***>
escreveu:

**Comment by frantastic24** [comment]
Because you can do it yourself

**Comment by BernardoGP4504** [comment]
Yea but idk how

Em qui, 20 de out de 2022 19:08, frantastic24 ***@***.***>
escreveu:

**Comment by frantastic24** [comment]
Then learn
