### ISSUE TITLE
Default BF

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#10937]
### What is your question?

Hello... A-gain... Well the point is that... Could there be a way (with the **SOURCE CODE**) set my character as the default bf character? If so, could you pls tell me how? I would appreciate it a lot :)

**Comment by MemeHoovy** [comment]
bf is already the default character

**Comment by GatoMorado621** [comment]
> bf is already the default character 😑

Yea, but is there a way to change it to my character???

**Comment by CrusherNotDrip** [comment]
There is literally a var that let's you change it

**Comment by GatoMorado621** [comment]
> There is literally a var that let's you change it

Is the first "bf" text of Boyfriend.hx, right???

**Comment by MemeHoovy** [comment]
no, in character.hx

**Comment by MemeHoovy** [comment]
DEFAULT_CHARACTER

**Comment by GatoMorado621** [comment]
> `DEFAULT_CHARACTER`

😅😅😅... I found it... Well, thank you so much for the help. Bye :)

**Comment by CrusherNotDrip** [comment]
close the goddamn issue then like bruh
![thebestreactionalt](https://user-images.githubusercontent.com/90648119/197301063-858772ca-fb37-4aff-8fe6-327a3686bd4d.png)

**Comment by CrusherNotDrip** [comment]
oh yay he closed it now I wont have to send a bomb somewhere
