### ISSUE TITLE
Indie Cross sprites crash game

### ISSUE THREAD

**Issue by bruh-guy** [ShadowMario/FNF-PsychEngine#10941]
### Describe your bug here.

I was porting the indie cross sprites to psych (sans and cuphead) and I can use the character editor just fine but whatever song I actually load them into they just crash the game. I have no idea what the log means but I do recognize that it's mentioning something about the playstate file.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I have not touched the source code at all.

**Comment by bruh-guy** [comment]
I didn't know a version released literally a few days ago, so I tried that one instead and it's slightly better. The game no longer crashes, but the characters just stay suspended in the air and don't play any animations. Cuphead is stuck in his idle but it's completely still, and sans is stuck on his down pose also completely still.

**Comment by frantastic24** [comment]
Not a bug
Issue with your texture files

**Comment by InsiderIV** [comment]
You have to retype all the animation names. 
For example, bf's idle animation is called, "BF idle dance". But Indie Cross's bf has a different animation name, called, "0Idle".
Just replace all the names and the animation _should_ play as normal.
