### ISSUE TITLE
first time trying to compile source and

### ISSUE THREAD

**Issue by MMalkeZ** [ShadowMario/FNF-PsychEngine#10942]
### Describe your problem here.

tf does this mean man
![image](https://user-images.githubusercontent.com/108292251/197310605-eacdee88-68b3-4f93-b51b-34bce9247fc3.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MemeHoovy** [comment]
make sure your using haxe 4.2.5 & flixel 4.11.0

**Comment by MemeHoovy** [comment]
well it's **wrong**

**Comment by MMalkeZ** [comment]
> well it's **wrong**

how do i check flixel version? also if i update it will i need to reinstall all the shits on cmd again?

**Comment by MemeHoovy** [comment]
`haxelib install flixel` and probably not

**Comment by MMalkeZ** [comment]
> `haxelib install flixel` and probably not

didnt fixed it dude i'm dead 😭
