### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SawadaAndzen** [ShadowMario/FNF-PsychEngine#10945]
### Describe your bug here.

I have a crash.
![Снимок экрана 2022-10-22 114701](https://user-images.githubusercontent.com/105200073/197330283-090637aa-38d9-4330-b50b-9522fda73d83.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I just add new character

**Comment by frantastic24** [comment]
Not a bug
Missing texture files

**Comment by SawadaAndzen** [comment]
Thanks

сб, 22 жовт. 2022 р. о 18:20 frantastic24 ***@***.***> пише:
