### ISSUE TITLE
Bug that i dont know what it is

### ISSUE THREAD

**Issue by Nick-Github11** [ShadowMario/FNF-PsychEngine#10950]
### Describe your bug here.

when i was entering a song i got this error 

### Command Prompt/Terminal logs (if existing)

```bash
Paths.hx (line 356)
HealthIcon.hx (line 43)
editors/CharacterEditorState.hx (line 990)
editors/CharacterEditorState.hx (line 952)
editors/CharacterEditorState.hx (line 434)
FlxUIDropDownMenuCustom.hx (line 512)
FlxUIDropDownMenuCustom.hx (line 361)
flixel/ui/FlxButton.hx (line 521)
flixel/addons/ui/FlxUITypedButton.hx (line 1172)
flixel/addons/ui/FlxUIButton.hx (line 362)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing, i just loaded a song i tested earlier and it crashed.

**Comment by frantastic24** [comment]
Not a bug
Missing icon

**Comment by Nick-Github11** [comment]
> Not a bug Missing icon

missing icon? well it had the icon so

**Comment by frantastic24** [comment]
It's what the error says and I don't have any o your files so that's all I can tell you

**Comment by Nick-Github11** [comment]
> It's what the error says and I don't have any of your files so that's all I can tell you

well ok, various erros are happening rn so
