### ISSUE TITLE
Help!!!! :((((

### ISSUE THREAD

**Issue by STCraftMC7344** [ShadowMario/FNF-PsychEngine#10952]
### Describe your problem here.

[PsychEngine_2022-10-22_22'01'57.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9844653/PsychEngine_2022-10-22_22.01.57.txt)
Help me :(((
How to fix this!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MaybeMaru** [comment]
Null Object Reference :trollface:
