### ISSUE TITLE
let me use spritemaps from later adobe animate versions!!!

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#10958]
### What feature do you want to get added on the **base** engine?

let me use spritemaps from later adobe animate versions!!!!!
![image](https://user-images.githubusercontent.com/93293747/197356192-67ab791b-7d64-4446-ba98-c5efc6cb263e.png)
:(

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MemeHoovy** [comment]
use flxanimate https://github.com/Dot-Stuff/flxanimate

**Comment by MemeHoovy** [comment]
but yeah, good feature

**Comment by ItsCapp** [comment]
> use flxanimate https://github.com/Dot-Stuff/flxanimate

it's for source and I'm using lua ;-;

**Comment by MemeHoovy** [comment]
> > use flxanimate https://github.com/Dot-Stuff/flxanimate
> 
> it's for source and I'm using lua ;-;

well you better just hope shadowmario adds support for flxanimate
