### ISSUE TITLE
Psych engine more keys  Null Object Reference

### ISSUE THREAD

**Issue by VeritonR** [ShadowMario/FNF-PsychEngine#10953]
### Describe your bug here.

I tried to play the mod on fnf more keys but when it gets to the middle of the level the game crashes
![error](https://user-images.githubusercontent.com/67881127/197347564-fe28f48e-2a1e-41cd-9061-bda8ae9376c1.PNG)

### Command Prompt/Terminal logs (if existing)

```bash
editors/EditorPlayState.hx (line 456)
flixel/group/FlxGroup.hx (line 769)
editors/EditorPlayState.hx (line 361)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Isn't that a fork? This report doesn't go here
You also posted two different errors

**Comment by VeritonR** [comment]
> ### Describe your bug here.
> I tried to play the mod on fnf more keys but when it gets to the middle of the level the game crashes ![error](https://user-images.githubusercontent.com/67881127/197347564-fe28f48e-2a1e-41cd-9061-bda8ae9376c1.PNG)
> 
> ### Command Prompt/Terminal logs (if existing)
> ```shell
> editors/EditorPlayState.hx (line 456)
> flixel/group/FlxGroup.hx (line 769)
> editors/EditorPlayState.hx (line 361)
> flixel/FlxState.hx (line 203)
> flixel/FlxGame.hx (line 747)
> flixel/FlxGame.hx (line 677)
> flixel/FlxGame.hx (line 551)
> openfl/events/EventDispatcher.hx (line 402)
> openfl/display/DisplayObject.hx (line 1399)
> 
> Uncaught Error: Null Object Reference
> Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine
> 
> > Crash Handler written by: sqirra-rng
> ```
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No



> Isn't that a fork? This report doesn't go here You also posted two different errors

sorry I don't know how to use github much.
but I managed to solve the problem myself!
This error is related to the game's NOTE_assets.png
