### ISSUE TITLE
spritemaps

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#10956]
### Describe your problem here.

tryna port hypno v2
a character uses spritemaps rather than xmls
I've got a bit of help on this and found that psych supports spritemaps made with animate 2018
but the spritemap is made with a higher version so it doesn't work

```
function onCreate()
	makeAnimatedLuaSprite('dawn', 'characters/dawn', 0, 0, 'tex')
	addLuaSprite('dawn', true)
end
```

is there any other way to use this spritemap without using source?

(also I'm trying to make this spritemap into a character)
if I'm able to import spritemaps into animate then that'd be cool but adobe doesn't seem to like that

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

everything is lua

**Comment by frantastic24** [comment]
```lua
function loadFrames(spr:FlxSprite, image:String, spriteType:String)
```

**Comment by ItsCapp** [comment]
> ```
> loadFrames(variable:String, image:String, spriteType:String)
> ```

what do I do with this

**Comment by ItsCapp** [comment]
also the issue is more that this happens
![image](https://user-images.githubusercontent.com/93293747/197353799-87f8e8b7-9e1e-492d-895c-74fe17c81fdb.png)

**Comment by frantastic24** [comment]
Then no you can't without source, you'd need to update texture atlas code to support your files

**Comment by ItsCapp** [comment]
is there a way to import spritemaps into adobe animate so that I can re-export them as a spritesheet?

**Comment by MemeHoovy** [comment]
> is there a way to import spritemaps into adobe animate so that I can re-export them as a spritesheet?

unless you have the FLAS, then no

**Comment by ItsCapp** [comment]
> > is there a way to import spritemaps into adobe animate so that I can re-export them as a spritesheet?
> 
> unless you have the FLAS, then no

![image](https://user-images.githubusercontent.com/93293747/197355350-92c353ba-79d2-4456-9a3c-2fb0b3f01b10.png)
