### ISSUE TITLE
Crash when entering the character editor.

### ISSUE THREAD

**Issue by 40U538072** [ShadowMario/FNF-PsychEngine#10957]
### Describe your bug here.

When I access the character editor, my characters sprites don't appear. It is just the placeholder image. I try to access it again and get crashes with an error message and I don't if it was cause by something I did. I have no clue what happened to it. I can't seem to access my character editor now.

### Command Prompt/Terminal logs (if existing)

```bash
Error!
Paths.hx (line 356) Character.hx (line 164) editors/CharacterEditor State.hx (line 925) editors/CharacterEditor State.hx (line 115) flixel/FlxGame.hx (line 637) flixel/FlxGame.hx (line 724) flixel/FlxGame.hx (line 677) flixel/FixGame.hx (line 545) openfl/events/EventDispatcher.hx (line 402) openfl/display/DisplayObject.hx (line 1399)
Uncaught Error: Null Object Reference Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine
> Crash Handler written by: sqirra-ing
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not that I am aware of. Sorry.

**Comment by MemeHoovy** [comment]
same here

**Comment by frantastic24** [comment]
not a bug
missing texture files

**Comment by 40U538072** [comment]
Where can I find the missing files? What texture files are missing?

**Comment by frantastic24** [comment]
A character is missing textures, I don't have your files so I can't tell you specifically which

**Comment by 40U538072** [comment]
Where can I find these files? Is it possible to send a screenshot so we can figure something out?

**Comment by frantastic24** [comment]
That depends where _you_ put the files? They're inside images, characters can go anywhere inside

**Comment by 40U538072** [comment]
I think I may have solved the issue. I just noticed that the entire assets/characters folder is completely missing. Don't know how but I am going to add the files back into the folder and see if that fixes it.

**Comment by 40U538072** [comment]
Able to access the chart editor but placeholder image still continues to linger. What should I do at this point?

**Comment by 40U538072** [comment]
Gonna close this issue now. Don't know what to do at this point. When another fix comes, I will think about reopening this issue.
