### ISSUE TITLE
week error

### ISSUE THREAD

**Issue by gadeno1919** [ShadowMario/FNF-PsychEngine#10968]
### Describe your bug here.

everytime i click on my week this error pops up
![capture 1](https://user-images.githubusercontent.com/116480114/197377507-4cae1caf-1907-4bbd-a55d-85961bd499ce.PNG)
is there a way to fix it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes*

**Comment by frantastic24** [comment]
Not a bug
Missing chart

**Comment by gadeno1919** [comment]
> Not a bug Missing chart

oh thanks

**Comment by gadeno1919** [comment]
> Not a bug Missing chart

i tried recharting but it still get the same error

**Comment by frantastic24** [comment]
You don't need to rechart, just copy another difficulty and rename

**Comment by gadeno1919** [comment]
I think i fixed it
