### ISSUE TITLE
imagine adding copy events and paste events that would be so cool but yep  idk how to code  A

### ISSUE THREAD

**Issue by anonybean** [ShadowMario/FNF-PsychEngine#1096]
### What feature do you want to get added on the base engine?
![image](https://user-images.githubusercontent.com/94534428/142262969-1e8b2111-f67f-4a2b-8815-c33433bbc10b.png)

**Comment by Mokona5901** [comment]
Yeah that would be faster to create a mod

**Comment by ShadowMario** [comment]
what?

**Comment by HiroOfc** [comment]
> what?

i think he said like, a button at the chart editor to copy all the events at a section and paste to another section, like the copy and paste arrows mechanism

**Comment by SrtHero278** [comment]
It does that already. I've seen it.

**Comment by HiroOfc** [comment]
> It does that already. I've seen it.

yeah, idk why he posted it

**Comment by anonybean** [comment]
> i think he said like, a button at the chart editor to copy all the events at a section and paste to another section, like the copy and paste arrows mechanism

yep this is what am talking about
