### ISSUE TITLE
Visual Studio 2022

### ISSUE THREAD

**Issue by TheFoxtails18** [ShadowMario/FNF-PsychEngine#10961]
### Describe your problem here.

Kind people, after reinstalling Windows, I needed to install Visual Studio. I used to have the 2019 version, and I downloaded it literally in one click. And now in 2022 it is necessary to choose components and so on. On github, I didn't understand exactly what components are needed. Can you list ALL the components that need to be installed?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

**Comment by MemeHoovy** [comment]
MSVC v142 - VS 2019 C++ x64/x86 build tools **Latest**
Windows SDK (10.0.17763.0)

**Comment by MemeHoovy** [comment]
also you shouldn't be using VS 2022 for haxeflixel

**Comment by Justudude321** [comment]
This is what I have if you're using VS 2022
![image](https://user-images.githubusercontent.com/105064710/197365045-fc520010-54f0-4612-9192-4bc17ddd33ed.png)
hope it helps

**Comment by MemeHoovy** [comment]
> This is what I have if you're using VS 2022 ![image](https://user-images.githubusercontent.com/105064710/197365045-fc520010-54f0-4612-9192-4bc17ddd33ed.png) hope it helps

that's literally what I just said

**Comment by Justudude321** [comment]
Ik, I needed MSVS v143 and the highest number of the SDK when got VS 2022

**Comment by nennneko5787** [comment]
The Visual Studio 2019 installer is available here: 
https://download.visualstudio.microsoft.com/download/pr/3105fcfe-e771-41d6-9a1c-fc971e7d03a7/8eb13958dc429a6e6f7e0d6704d43a55f18d02a253608351b6bf6723ffdaf24e/vs_Community.exe
