### ISSUE TITLE
Issue with stage

### ISSUE THREAD

**Issue by Yoshi-RBLX** [ShadowMario/FNF-PsychEngine#10960]
### Describe your problem here.

So I've coded in a stage, and have night versions of it for a song that takes place in the same location at night.
Here's how it went. I made the stage for day, and then for night I copied it and replaced the names of the files to the night images, but it's still showing the same images. I made sure I changed the file name, and the stage in the chart editor. But it's still not working. Anybody know how to fix this so it shows the night versions of the images?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHoovy** [comment]
did you change the Lua file for the stage or the JSON file?

**Comment by Yoshi-RBLX** [comment]
> did you change the Lua file for the stage or the JSON file?

I changed the lua file.

**Comment by MemeHoovy** [comment]
so did you make sure you set it to the _correct_ images?

**Comment by MemeHoovy** [comment]
did you even draw the night stage?

**Comment by Yoshi-RBLX** [comment]
I copied the names and put them in place of where they would be in the lua file of the stage (also yea I did add the night stage images)

**Comment by Yoshi-RBLX** [comment]
I'm not too good at coding stages, I've only done it twice so chances are I'm doing something wrong.

**Comment by Yoshi-RBLX** [comment]
> so did you make sure you set it to the _correct_ images?

Do you want the lua files of the stages if that'll help?

**Comment by MemeHoovy** [comment]
it's likely you put in the wrong names for each stages, or that you forgot something (such as changing the stages lua file, didn't change them in the songs chart via chart editor, and many more)

**Comment by MemeHoovy** [comment]
> > so did you make sure you set it to the _correct_ images?
> 
> Do you want the lua files of the stages if that'll help?

yeah, sure

**Comment by Yoshi-RBLX** [comment]
BTW I did change the stages in the chart editor, and the sky change is visible but nothing else changes

**Comment by Yoshi-RBLX** [comment]
Day stage code
function onCreate()
	-- background shit
	makeLuaSprite('ICANTBELIEVEIHAVETOCLARIFYTHIS', 'ICANTBELIEVEIHAVETOCLARIFYTHIS', -800, -100);
	setScrollFactor('ICANTBELIEVEIHAVETOCLARIFYTHIS', 0.3, 0.3);

	makeLuaSprite('day-hills', 'day-hills', -1000, -250);
	setScrollFactor('day-hills', 1, 0.9);
	
	makeLuaSprite('day-gate', 'day-gate', -700, 300);
	setScrollFactor('day-gate', 1, 1);	
	
	makeLuaSprite('day-grass', 'day-grass', -1000, 500);
	setScrollFactor('day-grass', 1, 1);

	addLuaSprite('ICANTBELIEVEIHAVETOCLARIFYTHIS', false);
	addLuaSprite('day-hills', false);
	addLuaSprite('day-gate', false);
	addLuaSprite('day-grass', false);

	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end

**Comment by Yoshi-RBLX** [comment]
Night stage code
function onCreate()
	-- background shit
	makeLuaSprite('sky-night', 'sky-night', -800, -100);
	setScrollFactor('sky-night', 0.3, 0.3);

	makeLuaSprite('hills-night', 'hills-night', -1000, -250);
	setScrollFactor('hills-night', 1, 0.9);
	
	makeLuaSprite('gate-night', 'gate-night', -700, 300);
	setScrollFactor('gate-night', 1, 1);	
	
	makeLuaSprite('grass-night', 'grass-night', -1000, 500);
	setScrollFactor('grass-night', 1, 1);

	addLuaSprite('sky-night', false);
	addLuaSprite('hills-night', false);
	addLuaSprite('gate-night', false);
	addLuaSprite('grass-night', false);

	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end

**Comment by MemeHoovy** [comment]
here's an example stage in the wiki
https://cdn.discordapp.com/attachments/866856727621795850/900523259345371177/ExampleStage.zip

**Comment by Yoshi-RBLX** [comment]
Do I just copy the code from the previous stage into that one, cause if not I'll have to recode everything to be exact

**Comment by MemeHoovy** [comment]
> Do I just copy the code from the previous stage into that one, cause if not I'll have to recode everything to be exact

you can use it as a base next time

**Comment by Yoshi-RBLX** [comment]
Alright I'll try it, I'll repost here if it ends up working.

**Comment by Yoshi-RBLX** [comment]
Didn't work sadly. Uhh I forgot to specify this I'm using OS Engine (which is literally just a Psych Engine build with some extra things)

**Comment by MemeHoovy** [comment]
alright, well I'll let someone else help since I'm working on about 15 different projects

**Comment by Yoshi-RBLX** [comment]
Alright thanks for trying to help tho

**Comment by MemeHoovy** [comment]
> Alright thanks for trying to help tho

np

**Comment by frantastic24** [comment]
do you mind posting all the stage files so i can see what the issue is, all i can think of is restarting the game if you were editing the images

**Comment by Yoshi-RBLX** [comment]
> do you mind posting all the stage files so i can see what the issue is, all i can think of is restarting the game if you were editing the images

IMAGES:
![ICANTBELIEVEIHAVETOCLARIFYTHIS](https://user-images.githubusercontent.com/111145576/197364721-185dc9af-863d-4871-8409-37891214660c.png)
![sky-night](https://user-images.githubusercontent.com/111145576/197364722-fc785b12-221a-4edc-a37f-4b335a7407c8.png)
![day-gate](https://user-images.githubusercontent.com/111145576/197364723-1f7d2929-b34f-437c-b0c8-3d602059e612.png)
![day-grass bg](https://user-images.githubusercontent.com/111145576/197364724-edff2a96-7bb6-4a9c-9659-f2302e19c954.png)
![day-grass](https://user-images.githubusercontent.com/111145576/197364725-a9adcbe8-bd75-4115-9e6f-f825f815a41d.png)
![day-hills](https://user-images.githubusercontent.com/111145576/197364726-f63d8985-996c-43f5-9677-22268cabec7b.png)
![gate-night](https://user-images.githubusercontent.com/111145576/197364727-e34c1ed7-6022-4f75-ac0f-8bbb5b03f83d.png)
![grass bg-night](https://user-images.githubusercontent.com/111145576/197364728-f0022ccb-43df-4b1e-95d8-8ca1dae18cef.png)
![grass-night](https://user-images.githubusercontent.com/111145576/197364729-8d9cfdfa-f63a-47fc-a366-d2d8c888d489.png)
![hills-night](https://user-images.githubusercontent.com/111145576/197364730-fbf54a4c-72e3-490c-bb8d-375fbae073da.png)

LUA FILES:

Day:
function onCreate()
	-- background shit
	makeLuaSprite('ICANTBELIEVEIHAVETOCLARIFYTHIS', 'ICANTBELIEVEIHAVETOCLARIFYTHIS', -800, -100);
	setScrollFactor('ICANTBELIEVEIHAVETOCLARIFYTHIS', 0.3, 0.3);

	makeLuaSprite('day-hills', 'day-hills', -1000, -250);
	setScrollFactor('day-hills', 1, 0.9);
	
	makeLuaSprite('day-gate', 'day-gate', -700, 300);
	setScrollFactor('day-gate', 1, 1);	
	
	makeLuaSprite('day-grass', 'day-grass', -1000, 500);
	setScrollFactor('day-grass', 1, 1);

	addLuaSprite('ICANTBELIEVEIHAVETOCLARIFYTHIS', false);
	addLuaSprite('day-hills', false);
	addLuaSprite('day-gate', false);
	addLuaSprite('day-grass', false);

	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end

Night:
function onCreate()
	-- background shit
	makeLuaSprite('sky-night', 'sky-night', -800, -100);
	setScrollFactor('sky-night', 0.3, 0.3);

	makeLuaSprite('hills-night', 'hills-night', -1000, -250);
	setScrollFactor('hills-night', 1, 0.9);
	
	makeLuaSprite('gate-night', 'gate-night', -700, 300);
	setScrollFactor('gate-night', 1, 1);	
	
	makeLuaSprite('grass-night', 'grass-night', -1000, 500);
	setScrollFactor('grass-night', 1, 1);

	addLuaSprite('sky-night', false);
	addLuaSprite('hills-night', false);
	addLuaSprite('gate-night', false);
	addLuaSprite('grass-night', false);

	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end

**Comment by Yoshi-RBLX** [comment]
WAIT SHIT IM SO STUPID IT WAS CHANGING THE FILES BUT I JUST DIDNT NOTICE A CHANGE WHAT THE-

**Comment by MemeHoovy** [comment]
> WAIT SHIT IM SO STUPID IT WAS CHANGING THE FILES BUT I JUST DIDNT NOTICE A CHANGE WHAT THE-

what was the change?
