### ISSUE TITLE
how do you stop the song from starting until you want to start it?

### ISSUE THREAD

**Issue by NickPlayzGITHUB** [ShadowMario/FNF-PsychEngine#10967]
### What is your question?

So basically, I wanted to make a little mini menu before you start a song. But I couldn't get it to stop and then start again.

I used code from the Cutscene script to try and test this, but nothing seemed to work. The song just either freezes indefinitely or just plays normally.

Here is the code
![image](https://user-images.githubusercontent.com/87223282/197373686-f0700a18-1d06-4861-8c49-2cea2f6a621d.png)

What am I getting wrong here?

**Comment by frantastic24** [comment]
You forgot `startCountdown()`

**Comment by NickPlayzGITHUB** [comment]
> You forgot `startCountdown()`

what do you mean?

**Comment by frantastic24** [comment]
The countdown needs to start again when the timer finishes

**Comment by NickPlayzGITHUB** [comment]
so where would I put startCountdown()?

**Comment by frantastic24** [comment]
> when the timer finishes

Also `return Function _Stop` is in the wrong `if` branch, you don't even need the `else`

**Comment by NickPlayzGITHUB** [comment]
Hey it works now! Thanks a lot!
