### ISSUE TITLE
Error when compiling: source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler

### ISSUE THREAD

**Issue by Thecoolgamer6745** [ShadowMario/FNF-PsychEngine#10966]
### Describe your bug here.

When trying to compile the game it brings this up:
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler
How do i fix this?

### Command Prompt/Terminal logs (if existing)

```bash
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No i changed nothing

**Comment by MemeHoovy** [comment]
`haxelib install hxCodec 2.5.1`

**Comment by JonnycatMeow** [comment]
use my version  
haxelib git hxCodec https://github.com/JonnycatMeow/hxCodec-old-version.git 
its the old version but it was mac support

**Comment by BeastlyGhost** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/10756
