### ISSUE TITLE
when pressing "reload json", the game crashes

### ISSUE THREAD

**Issue by blueknight64** [ShadowMario/FNF-PsychEngine#10969]
### Describe your bug here.

i was trying to chart a song and took a break, when i came back and tried to recover the chart(using reload json), the game displays an error and crashes, i placed my chart into the "data" folder inside the "mods" folder, and this bug doesn't work on base game songs. did i do something wrong?
(forgot to mention, im using Psych Engine 0.6.3 i think, just incase it might help)

### Command Prompt/Terminal logs (if existing)

```bash
"C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
editors/ChartingState.hx (line 2957)
editors/ChartingState.hx (line 434)
Prompt.hx (line 44)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/triple-trouble/triple-trouble.json]
please report this error to the GitHub page:(it shows a link to the engine's github page)


>Crash Handler written by: sqirra-rng"
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

not anything major really, just a new song

**Comment by frantastic24** [comment]
Missing normal difficulty chart

**Comment by blueknight64** [comment]
> Missing normal difficulty chart
thanks man, i'll close this for now.

i'll reopen it again if it doesn't work

**Comment by TheKitBoi** [comment]
U didn’t close it

**Comment by blueknight64** [comment]
sorry lol im tryna find how to close this thing
