### ISSUE TITLE
Removing a Lua Script mid song

### ISSUE THREAD

**Issue by Sonicgamer2000** [ShadowMario/FNF-PsychEngine#10963]
### Describe your problem here.

Okay so I'm trying to remove a Lua Script mid song with Lua Commands but for some reason even though the lua file loads normally, it doesn't work at all. Also for your information, I am using the stephit lua line.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not at all

**Comment by CaptainBaldi** [comment]
![image](https://user-images.githubusercontent.com/86160807/197388636-d29e4492-abae-4e45-916c-ed7e9096ff92.png)
its literally a default psych function but ok
