### ISSUE TITLE
noteData not working

### ISSUE THREAD

**Issue by 4wdthinks** [ShadowMario/FNF-PsychEngine#1097]
### Describe your bug here.

I've been trying to use noteData for a custom note, but it never seems to register
eg. when i try hit a note and debugprint noteData, it prints nothing

code:
![image](https://user-images.githubusercontent.com/79160331/142266616-56d09da2-63eb-43ee-8060-93a452f352d9.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, the note is a lua file on source code. This has also happened on downloaded build before.

**Comment by ShadowMario** [comment]
directions[direction]
