### ISSUE TITLE
How to open a link upon dying with lua

### ISSUE THREAD

**Issue by Wolverin18** [ShadowMario/FNF-PsychEngine#10972]
### What is your question?

I know that there's a way to open a link on google upon dying with lua, but I don't really know how to do it. Can someone help me out here?

**Comment by MemeHoovy** [comment]
this has what you're looking for: https://github.com/MemeHoovy/FNF-PsychEngine-Extra-1

**Comment by Wolverin18** [comment]
Before I go check, does it have the script with lua? Because that's what I'm looking for and what you sent seems to be a source code build-

**Comment by MemeHoovy** [comment]
there's releases in there

**Comment by Wolverin18** [comment]
Where can I find the link script in the build though?

**Comment by MemeHoovy** [comment]
oh scratch that, that was my version of psych engine, nvm use this instead https://github.com/notweuz/FNF-OSEngine

**Comment by MemeHoovy** [comment]
it actually has what your looking for, use `openURL(URL)`

**Comment by Wolverin18** [comment]
I see that this is a modified version of psych, what version of psych did it modify?
I need a version that at least has the loadSong function so I just figured I would ask-

**Comment by MemeHoovy** [comment]
0.6.2

**Comment by Wolverin18** [comment]
alright that should work!

and about the openURL(URL:String) thing- is that a lua function?

**Comment by MemeHoovy** [comment]
> alright that should work!
> 
> and about the openURL(URL:String) thing- is that a lua function?

yes

**Comment by CaptainBaldi** [comment]
> oh scratch that, that was my version of psych engine, nvm use this instead https://github.com/notweuz/FNF-OSEngine

instead of using os engine, you could just
`os.execute('start https://github.com/ShadowMario/FNF-PsychEngine/issues/10972')`
obv replace `https://github.com/ShadowMario/FNF-PsychEngine/issues/10972` with your link

**Comment by MaybeMaru** [comment]
now close this

**Comment by Drawoon2** [comment]
Too you can use this
`runHaxeCode([[
		FlxG.openURL('site');
]])`
Change site for your URL
