### ISSUE TITLE
Bug when compiling the game

### ISSUE THREAD

**Issue by Thecoolgamer6745** [ShadowMario/FNF-PsychEngine#10970]
### Describe your bug here.

When trying to compile the game this shows up:
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

### Command Prompt/Terminal logs (if existing)

```bash
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No i changed nothing

**Comment by TheKitBoi** [comment]
you need to install Visual Studio Community 2019

**Comment by Thecoolgamer6745** [comment]
> 

What do i do after that?

**Comment by TheKitBoi** [comment]
Install the components
MSVC v142 - VS 2019 C++ x64/x86 build tools
Windows SDK (10.0.17763.0)

**Comment by Thecoolgamer6745** [comment]
> 

Oh ok
Then thats it?

**Comment by TheKitBoi** [comment]
yes

**Comment by Thecoolgamer6745** [comment]
> yes

oh ok thanks
