### ISSUE TITLE
How to put a picture during the countdown

### ISSUE THREAD

**Issue by Nork1234** [ShadowMario/FNF-PsychEngine#10979]
### What is your question?

How do I put a picture during the countdown in the start of the song. What I mean by this is that in the very beginning of MCM's Joe Mama https://www.youtube.com/watch?v=Dk1uF_xFRkU&t=38s, when the 3, 2, 1, Go Countdown is happening, there's a picture of Squidward saying you won't get copyrighted. How do I put a picture there in lua?

**Comment by frantastic24** [comment]
`function onStartCountdown()` or `function onCountdownTick(counter)`
