### ISSUE TITLE
Opponent Ignoring Notes still plays the directions animations

### ISSUE THREAD

**Issue by Shaggers-official** [ShadowMario/FNF-PsychEngine#10971]
### What is your question?

If you've played Hypno Lullaby V2, you know what i'm talking about but, i wanna port that mechanic to lua.
I know that 
```
if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
    setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true);
end
```
but i don't know how to reactivate the animations after the note are being missed

i tried :

```
function opponentNoteHit(id, direction, noteType, isSustainNote, noteData)

	if noteType == 'Amusia Notes' then
		if noteData == '1' then
			triggerEvent('Play Animation' , 'singLEFT', 'dad')
		end
	end

end
```

i don't actually know if that actually could work or if i'm doing it wrong

**Comment by CaptainBaldi** [comment]
iirc if ignoreNote is set to true and that notetype is hit it doesn't do a callback for opponentNoteHit etc

**Comment by Shaggers-official** [comment]
Oh yeah, i'm dumb, any ideas how i could change that ?
