### ISSUE TITLE
What am i missing?

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#10977]
### Describe your problem here.

Im trying to do a thingy in freeplay and the console says
source/FreeplayState.hx:270: characters 5-48 : Not enough arguments, expected color:Int
i need help to locate or atleast get the arguments needed
it should be here

```
	public function addWeek(songs:Array<String>, weekNum:Int, weekColor:Int, ?songCharacters:Array<String>)
		{
			if (songCharacters == null)
				songCharacters = ['bf'];
			var num:Int = 0;
			for (song in songs)
			{
				addSong(song, weekNum, songCharacters[num]);
				this.songs[this.songs.length-1].color = weekColor;
				if (songCharacters.length != 1)
					num++;
			}
		}
```

please let me know if you know what happened here\
if not its alright ill try to figure it out

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

FreeplayState TitleState MainMenuState

**Comment by frantastic24** [comment]
`addSond` is missing an argument
```haxe
public function addSong(songName:String, weekNum:Int, songCharacter:String, color:Int)
```

**Comment by machonessiebaby** [comment]
> ```hx
> public function addSong(songName:String, weekNum:Int, songCharacter:String, color:Int)
> ```

thanks man!

**Comment by machonessiebaby** [comment]
> `addSong` is missing an argument
> 
> ```hx
> public function addSong(songName:String, weekNum:Int, songCharacter:String, color:Int)
> ```

alright time to fix some stuff thanks for this!

**Comment by machonessiebaby** [comment]
> `addSong` is missing an argument
> 
> ```hx
> public function addSong(songName:String, weekNum:Int, songCharacter:String, color:Int)
> ```

real quickly is weekNum just the weeks name or number?

**Comment by frantastic24** [comment]
it's an int
