### ISSUE TITLE
Character and Icons

### ISSUE THREAD

**Issue by rbrtmappjr** [ShadowMario/FNF-PsychEngine#10986]
### Describe your problem here.

When you put some characters in the engine the character is not there same with the icons

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Jevilm** [comment]
What

**Comment by TheKitBoi** [comment]
> ### Describe your problem here.
> When you put some characters in the engine the character is not there same with the icons

explain why

**Comment by DisIsNOt** [comment]
omg plz be more specific

**Comment by Gostar64** [comment]
I think they mean that they can't see the characters and icons

**Comment by rbrtmappjr** [comment]
I put a script for the icons when I win without the winning icon it shows an image will I fixed the problem
