### ISSUE TITLE
Song crashes at start

### ISSUE THREAD

**Issue by TurquoiseTheOctagon** [ShadowMario/FNF-PsychEngine#10980]
### Describe your bug here.

So, I was charting an Angry Munci song I made for a mod, I tested it out but for some reason, it crashed at the second verse. There weren't any scripts in the data folder yet and I don't know what caused it. I didn't get a crash popup or anything it just froze and closed. Can anyone help? I'm on 0.6.3 and I don't know what to do.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't edit anything in the build

**Comment by TheKitBoi** [comment]
stop spamming

**Comment by TurquoiseTheOctagon** [comment]
k
