### ISSUE TITLE
Shaders, Lua or No Lua ? I'm confused

### ISSUE THREAD

**Issue by Shaggers-official** [ShadowMario/FNF-PsychEngine#10983]
### Describe your problem here.

I was trying to search a way to add this :

```
function onCreatePost()
    addVCREffect('camGame')
    addVCREffect('camHUD')
end
```
Into a modded cover i'm making

But i've seen many posts saying that shaders are no longer available on Lua and that you had to use Source Code, so i was like 'Ok, i'll search how to add them in source', but then i saw one of the comments saying that it's useless since the 0.6.3 actually reuses shaders with LUA. 

I just wanna use the vcr effect :( 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Jevilm** [comment]
You will have to manually add an accurate clone of the shaders, or use an 0.6.2 action build with shaders

**Comment by CaptainBaldi** [comment]
shaders do not work like that anymore
you can't just go `addGlitchShader('piss')` and have it work
Psych Engine 0.6.3 shaders use a entirely new system
I wrote a quick tutorial [here](https://gamebanana.com/tuts/15316) on how to use basic shaders.
