### ISSUE TITLE
I need help making pre-song cutscenes

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#1098]
### Describe your problem here.

I don't know how to make pre-song cutscenes (not dialogues), can someone help me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

2 new characters, a new stage and deleted week 1-6 default json and png

### hi

**Comment by acap09** [comment]
### help me #

**Comment by ShadowMario** [comment]
MP4 cutscenes on animated in sprites?

**Comment by acap09** [comment]
MP4, i have the MP4, i believe it is already 1280x720. Just the coding is my problem.

**Comment by acap09** [comment]
hi

**Comment by craftersshaft** [comment]
there's a video example here for bopeebo, could probably be reworked to fit your needs: https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API

**Comment by ShadowMario** [comment]
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/748

**Comment by FedorVaice** [comment]
And animated in sprites?
