### ISSUE TITLE
Add Time to Song Mid Way? (Timer Fakeout)

### ISSUE THREAD

**Issue by ColinCartoons** [ShadowMario/FNF-PsychEngine#10987]
### What is your question?

i was just wondering if anyone has a code that can add more time to a song mid way through it. ive had this cool idea ive been wanting to do for a month now but i dont know how to do it. (just out of curiosity)

**Comment by bruh1cat** [comment]
> ### What is your question?
> 
> i was just wondering if anyone has a code that can add more time to a song mid way through it. ive had this cool idea ive been wanting to do for a month now but i dont know how to do it. (just out of curiosity)

Like unknown suffering, if so then #10671?

**Comment by ColinCartoons** [comment]
well yes, but i suck at coding and i dont know what function to use or what to put the setTextString part with (im sorry)

**Comment by bruh1cat** [comment]
> well yes, but i suck at coding and i dont know what function to use or what to put the setTextString part with (im sorry)

Function onStepHit()
if curStep == 69 then
setTextString(timeTxt, 69:420)
elseif curStep == 120 then
setTextString(timeTxt, 10:50)
end
end
end

Of course you'd have to first set it up like WI so that it functions the same, but with this it should just change the time text to 69:420 and 10:50.

**Comment by ColinCartoons** [comment]
<img width="857" alt="yay" src="https://user-images.githubusercontent.com/90355052/197889595-25475982-6206-40d5-9d41-343d3b87b4cb.png">

what did i do wrong (also i already put the function part)

	if curStep == 0 then
	setTextString(timeTxt, 1:21)
		elseif curStep == 120 then
		setTextString(timeTxt, 2:30)
		end
	end
end

**Comment by ColinCartoons** [comment]
<img width="857" alt="yay" src="https://user-images.githubusercontent.com/90355052/197889915-6e130e0a-485e-441d-8c97-432b1bae6634.png">

what did i do wrong (i already put the function onStepHit part btw)

	if curStep == 0 then
		setTextString(timeTxt, 1:21)
		elseif curStep == 120 then
		setTextString(timeTxt, 10:50)
		end
	end
end

**Comment by DabbinDude316B** [comment]
> <img alt="yay" width="857" src="https://user-images.githubusercontent.com/90355052/197889915-6e130e0a-485e-441d-8c97-432b1bae6634.png">
> 
> what did i do wrong (i already put the function onStepHit part btw)
> 
> ```
> if curStep == 0 then
> 	setTextString(timeTxt, 1:21)
> 	elseif curStep == 120 then
> 	setTextString(timeTxt, 10:50)
> 	end
> end
> ```
> 
> end

Extra end

**Comment by ColinCartoons** [comment]
still says the same thing :/

function onStepHit()
if curStep == 0 then
	setTextString(timeTxt, 1:21)
	elseif curStep == 120 then
	setTextString(timeTxt, 10:50)
	end
end

**Comment by bruh1cat** [comment]
> still says the same thing :/
> 
> 
> 
> function onStepHit()
> 
> if curStep == 0 then
> 
> 	setTextString(timeTxt, 1:21)
> 
> 	elseif curStep == 120 then
> 
> 	setTextString(timeTxt, 10:50)
> 
> 	end
> 
> end

Its the :

**Comment by ColinCartoons** [comment]
ok well now it doesnt change anything. 

	if curStep == 0 then
		setTextString(timeTxt, 81)
		elseif curStep == 120 then
		setTextString(timeTxt, 1050)
	end
end

**Comment by frantastic24** [comment]
#8299

**Comment by ColinCartoons** [comment]
oh wow thank you!
