### ISSUE TITLE
LUA SHITS

### ISSUE THREAD

**Issue by Gurudevsing** [ShadowMario/FNF-PsychEngine#10981]
### Describe your problem here.

https://user-images.githubusercontent.com/87480185/197472226-16d7dcb8-5f95-48dc-bbd9-b7819e2a88bd.mp4

![Screenshot (33)](https://user-images.githubusercontent.com/87480185/197472592-5649fbb9-c7f6-428e-9a6e-1e078908d932.png)

YOU CAN SEE THE ANIMATION MOVING ON SAME SPOT, HOW TO MOVE ON ITS NEXT POSITION

AND ANOTHER QUESTION THE FAIR WHEEL WON'T ROTATE ,GUESS IT SEEMS I NEED TO USE INCREAMENT OPERATOR OR SOMTHING.  IDK CODE RIGHT  HELP ME OUT

SHITTTTTT

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by DisIsNOt** [comment]
Bro forget objectPlayAnimation and doTweenX exists 💀

**Comment by CaptainBaldi** [comment]
> Bro forget objectPlayAnimation and doTweenX exists 💀

Bro forget playAnim exists 💀

**Comment by Gurudevsing** [comment]
> Bro forget objectPlayAnimation and doTweenX exists 💀



> > Bro forget objectPlayAnimation and doTweenX exists 💀
> 
> Bro forget playAnim exists 💀

![Screenshot (37)](https://user-images.githubusercontent.com/87480185/197747459-ead52040-1dfd-486d-85a9-ae0042e54287.png)

 HUH i don't understand well ,please tell me how to use those code and explain it's  function with example 
thankyou

**Comment by DisIsNOt** [comment]
objectPlayAnimation('tag','anim')

**Comment by Gurudevsing** [comment]
> bjectPlayAnimation('tag','anim'

did't work
![Screenshot (38)](https://user-images.githubusercontent.com/87480185/197754388-4101f4f0-3156-41b0-b6f0-0e03ae028b0e.png)

https://user-images.githubusercontent.com/87480185/197754272-7a3a3dad-0c2e-4d64-9e82-70418af479e9.mp4

**Comment by DisIsNOt** [comment]
instead of putting the xml name on it put the animation name "walk"

**Comment by Gurudevsing** [comment]
![Screenshot (39)](https://user-images.githubusercontent.com/87480185/198039526-b8096484-48eb-492e-a39f-1d1ccdd4d33f.png)

> instead of putting the xml name on it put the animation name "walk"

Bro i did what you said but its still moving on the same spot  is anything to do with tweenx shits

**Comment by DisIsNOt** [comment]
doTweenX('tag', 'objecttag', 'value', 'duration', 'linear')

**Comment by Gurudevsing** [comment]
![Screenshot (40)](https://user-images.githubusercontent.com/87480185/198286701-3802e9a7-83a0-44ff-b650-66ecdd74faad.png)
yes its a animation ,

what is supposed to linear....

> doTweenX('tag', 'objecttag', 'value', 'duration', 'linear')
> 
> don't change linear it just a funni tween method
> 
> and did your object's animation played?

**Comment by Gostar64** [comment]
Linear is the [tween method](https://api.haxeflixel.com/flixel/tweens/FlxEase.html), you don't have to change it

**Comment by Gurudevsing** [comment]
> Linear is the [tween's easing](https://api.haxeflixel.com/flixel/tweens/FlxEase.html), you don't have to change it



THIS CODING SHITT FFUCKKKs 

https://user-images.githubusercontent.com/87480185/198642194-a129be4d-640a-4497-a434-4a55761bf3cb.mp4




BRO IF YOU HAVE EXAMPLE CODE ,SHARE WITH ME

**Comment by DisIsNOt** [comment]
makeAnimatedLuaSprite('jesus', 'sansUndertale', 0,0)
addAnimationByPrefix('jesus', 'ded', 'sans  ded instance', 24, false)
objectPlayAnimation('jesus', 'ded')
addLuaSprite('jesus', false)
