### ISSUE TITLE
Is is possible to enable dark title in psych engine 0.5.2h?

### ISSUE THREAD

**Issue by ZdzichuOfficialReal** [ShadowMario/FNF-PsychEngine#10985]
### What is your question?

Is is possible to enable dark title in psych engine 0.5.2h using source code? If yes then how?

**Comment by ShadowMario** [comment]
What is a "Dark title"?

**Comment by ZdzichuOfficialReal** [comment]
I mean is it possible to enable dark mode on this
![image](https://user-images.githubusercontent.com/113778371/197842550-d0813ebc-dcc1-4111-82d0-c1f6271c2cbc.png)

**Comment by frantastic24** [comment]
That's handled by your OS, not the game

**Comment by ShadowMario** [comment]
This is not something controlled by me
