### ISSUE TITLE
the song section on fnf wouldnt load my custom 

### ISSUE THREAD

**Issue by MojoXYT** [ShadowMario/FNF-PsychEngine#10996]
### Describe your problem here.

i added a chart and a song but it wont load the section
![Screenshot 2022-10-25 150923](https://user-images.githubusercontent.com/116654205/197805518-b2b063a4-f582-45ff-b077-1cfe8b050cb3.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Game can't read your instrumental, export it again

**Comment by Username2120** [comment]
make sure the file name is the exact same as what your typing into the chart editor.

**Comment by Daikicalla** [comment]
There's two possibilities that this isn't working:
- The Instrumental you used isn't in OGG format.
- The Instrumental isn't called "Inst" in the proper folder.

Be sure that your Inst is in .OGG format, and that it's called Inst.
