### ISSUE TITLE
Camera goes to wrong position

### ISSUE THREAD

**Issue by SonicSezy** [ShadowMario/FNF-PsychEngine#10999]
### Describe your problem here.

I'm making a mod, in one song the opponent and player are set on opposite sides of the stage, {Op: Right, Bf Left}, but the camera keeps going to the right side for Boyfriends sections, and the left for the op's, how do I fix it?, I did change it myself but I managed to forgot the day later..

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed the camera positioning

**Comment by ProbablyKam** [comment]
In the character JSON file try loading it up, repositioning the camera, and saving.
