### ISSUE TITLE
Mod reset

### ISSUE THREAD

**Issue by Mokona5901** [ShadowMario/FNF-PsychEngine#1099]
### What is your question?

Is there a way to reset a FNF mod like when we are going to post a mod ? Achievements, scores and others things.

**Comment by HiroOfc** [comment]
well, i think u don't need to reset score and anything to post a mod cuz it's by save data, but i think there is something at options to reset data. Or, just delete the ShadowMario folder at `C:/Users/(your username)/AppData/Roaming`, and this will reset your data at Psych Engine

**Comment by ShadowMario** [comment]
No.
