### ISSUE TITLE
Running Haxe Code without actually using Source Code

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#10990]
### Describe your problem here.

hey, so I want to import the Dave and Bambi Wavy Background and Eyesore Effect, but I want to do it without the source code.

Here is what I have in mind:
1. I could take the entirety of the shaders file from the 2.5c Source Code, since I has access to that, and pop it into ```function onCreate()
     runHaxeCode{[[
MY CODE
]]}.
end``` would that work? IDK
2. figure out how to port the whole thing into .frag shader files

could you help me with one of these?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I am making an External Mod Folder.

**Comment by CaptainBaldi** [comment]
god save me

**Comment by fnfdemonboi314159** [comment]
> god save me

dude, why are you extremely picky all of a sudden with all my requests?

**Comment by fnfdemonboi314159** [comment]
all I want is help, that's all

**Comment by CaptainBaldi** [comment]
> > god save me
> 
> dude, why are you extremely picky all of a sudden with all my requests?

i have literally no idea who you are
if i see a ridiculous issue, i comment on it, that's literally it

**Comment by fnfdemonboi314159** [comment]
> > > god save me
> > 
> > 
> > dude, why are you extremely picky all of a sudden with all my requests?
> 
> i have literally no idea who you are if i see a ridiculous issue, i comment on it, that's literally it

you're calling my problem ridiculous?

**Comment by TheKitBoi** [comment]
hscript it's literally haxe code within lua
plus there literally shaders
just go to these
https://github.com/MoldyGH/VsDave/blob/main/source/WiggleEffect.hx
https://github.com/MoldyGH/VsDave/blob/main/source/VCRDistortionShader.hx
copy the #pragma header until it reaches the ) at the end

paste them as a whatever-name.frag

use this file from the PE Discord Server as an example

[shader.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9880947/shader.txt)
github doesn't accept lua so change .txt into .lua
