### ISSUE TITLE
Does Psych Support Sprite Atlases?

### ISSUE THREAD

**Issue by NickPlayzGITHUB** [ShadowMario/FNF-PsychEngine#10991]
### What is your question?

Title says it all, Does Psych support Atlases? if so how do I use them?

**Comment by Lorekeeper49** [comment]
That's basically what a sprite sheet is, all animated assets within fnf use a sprite sheet

**Comment by NickPlayzGITHUB** [comment]
Yeah but Sprite atlases have all the parts all separate

**Comment by frantastic24** [comment]
[It's on the wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki)
