### ISSUE TITLE
Please tell me

### ISSUE THREAD

**Issue by SprialNebula** [ShadowMario/FNF-PsychEngine#10997]
### Describe your problem here.

How do you make it so that when you press 7 on a song it brings you to another song? I really want it in my mod.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

ported a few Dave and Bambi mods

**Comment by TheKitBoi** [comment]
Don’t make duplicates

**Comment by MemeHoovy** [comment]
use `loadSong`

**Comment by bruh1cat** [comment]
> ### Describe your problem here.
> 
> How do you make it so that when you press 7 on a song it brings you to another song? I really want it in my mod.
> 
> ### Are you modding a build from source or with Lua?
> 
> Lua
> 
> ### What is your build target?
> 
> Mac
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> 
> ported a few Dave and Bambi mods

For the love of everything use the search bar.

**Comment by notahumans-official** [comment]
Well, 7 leads to chart editor. You could use, like, 2 or 5 or something. But use loadSong. also, know that 0, 7, and 8 already have assigned features, 0 is mute/unmute, 7 is chart editor, 8 is sprite editor!

**Comment by bruh1cat** [comment]
> Well, 7 leads to chart editor. You could use, like, 2 or 5 or something. But use loadSong. also, know that 0, 7, and 8 already have assigned features, 0 is mute/unmute, 7 is chart editor, 8 is sprite editor!

Actually there is a way to disable the chart editor with lua

**Comment by notahumans-official** [comment]
> > Well, 7 leads to chart editor. You could use, like, 2 or 5 or something. But use loadSong. also, know that 0, 7, and 8 already have assigned features, 0 is mute/unmute, 7 is chart editor, 8 is sprite editor!
> 
> Actually there is a way to disable the chart editor with lua

Oh, shoot, really? I'm fr sorry, didn't know, lol. Thanks for telling me!

**Comment by bruh1cat** [comment]
> > > Well, 7 leads to chart editor. You could use, like, 2 or 5 or something. But use loadSong. also, know that 0, 7, and 8 already have assigned features, 0 is mute/unmute, 7 is chart editor, 8 is sprite editor!
> > 
> > 
> > Actually there is a way to disable the chart editor with lua
> 
> Oh, shoot, really? I'm fr sorry, didn't know, lol. Thanks for telling me!

Yep just put this under onCreate setProperty('debugKeysChart', nil)

**Comment by SprialNebula** [comment]
alright then
