### ISSUE TITLE
How to center the freeplay menu songs using source code on pe 0.6.3?

### ISSUE THREAD

**Issue by ZdzichuOfficialReal** [ShadowMario/FNF-PsychEngine#10998]
### What is your question?

How to center the freeplay menu songs using source code on pe 0.6.3?

**Comment by DisIsNOt** [comment]
I remember there's a yt vid about this and it's gone for now so no

**Comment by DisIsNOt** [comment]
> > I remember there's a yt vid about this and it's gone for now so no
> 
> EIT was a dickhead and closed the entire thing for practically no reason 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 

True💀💀💀💀💀💀💀☠️☠️

**Comment by TheKitBoi** [comment]
https://github.com/nebulazorua/tails-gets-trolled-v3/blob/master/source/states/FreeplayState.hx

**Comment by RubenDatOneBoi3446** [comment]
eit's way (at least i dont think) doesnt work with 0.6.3 the new alphabet thing
