### ISSUE TITLE
How to fix crash while adding a custom song

### ISSUE THREAD

**Issue by MojoXYT** [ShadowMario/FNF-PsychEngine#10995]
### Describe your problem here.

i was trying to add a custom song to fnf psyche engine but it keeps crashing and the song dont load.
![Screenshot 2022-10-25 143540](https://user-images.githubusercontent.com/116654205/197791491-67742794-532e-4406-aa2f-4e9f468625e6.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheKitBoi** [comment]
you were loading
copy the horrid-henry.json
paste it and rename the copy to horrid-henry-hard.json

**Comment by MojoXYT** [comment]
![Screenshot 2022-10-25 143540](https://user-images.githubusercontent.com/116654205/197796764-d2aacba0-fa9d-4997-b521-1384bb28119b.png)
 the song section wont load

**Comment by CaptainBaldi** [comment]
![image](https://user-images.githubusercontent.com/86160807/197809297-0a5477bb-eb81-4b7a-93c6-a6c10eebf772.png)
is there a reason there are people making entire fucking github accounts just to fuck with this repo
