### ISSUE TITLE
when i click the character i made the game crashes

### ISSUE THREAD

**Issue by GabYTGithub** [ShadowMario/FNF-PsychEngine#110]
Its not the BOM utf-8 thing, it just randomly crashes
[](url)
![noerror](https://user-images.githubusercontent.com/91231237/134440032-a365142b-0fd5-45a7-bc7c-d76ace7c8117.PNG)
no error either

**Comment by GabYTGithub** [comment]
please help mr mario man

**Comment by Mellow2110** [comment]
did you make you put your character files in mods folder?

**Comment by GabYTGithub** [comment]
i put an example in the mod folder but the actual one is on the characters folder

**Comment by Mellow2110** [comment]
and also did you add the libraries in project.xml?

**Comment by ShadowMario** [comment]
[https://github.com/ShadowMario/FNF-PsychEngine/wiki/Creating-a-Character](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Creating-a-Character)
