### ISSUE TITLE
Animated Stage Sprite cannot be created because of setProperty Antialiasing (6.3)

### ISSUE THREAD

**Issue by TheKitBoi** [ShadowMario/FNF-PsychEngine#11007]
### Describe your bug here.

I making a port on the latest version and setProperty antialiasing is causing it
checking the code

![image](https://user-images.githubusercontent.com/84044666/198034429-0abc0a3f-9995-428e-bea2-4c2f82e9caef.png)

checking the right folder 

![image](https://user-images.githubusercontent.com/84044666/198035578-76ebaef0-3b3d-40b1-9e95-f70603e09cb1.png)

checking the stage file

![image](https://user-images.githubusercontent.com/84044666/198034780-30b2e254-b331-44d6-b47e-103f839f7b1a.png)

and it doesn't work
I got a video on why

https://user-images.githubusercontent.com/84044666/198035640-8d886284-71e8-4624-9c4a-88c5045296d1.mp4

![image](https://user-images.githubusercontent.com/84044666/198036817-f2fe7617-37d1-4a24-8a77-ea1e519d6c42.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by impostor5875** [comment]
ok but there's no variable simply called antialiasing
you'd need to move that to after the sprite is created and change it to setProperty('truefatal.antialiasing', false)

**Comment by TheKitBoi** [comment]
should i close this issue
