### ISSUE TITLE
add character on FNF spy engine

### ISSUE THREAD

**Issue by Noel3454565FNF** [ShadowMario/FNF-PsychEngine#11006]
### Describe your bug here.

heya, i try to create an custom characters for my own mods FNF, but when i try to load it i have this error 
![Friday Night Funkin'_ Psych Engine 26_10_2022 12_45_30](https://user-images.githubusercontent.com/58745415/198007289-eac8fc9b-3889-465a-8286-55b9f6e917a1.png)

someone can help me please :,(((((

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i change different assets and add custom notes

**Comment by TheKitBoi** [comment]
this is Psych Engine not Spy Engine
+ not a bug check the xml or send it over

**Comment by Noel3454565FNF** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/58745415/198034185-49aada50-08a2-42b2-beb8-6a3c3fbb22a1.png">
this is the xlm file

**Comment by TheKitBoi** [comment]
it's supposed to be this
![image](https://user-images.githubusercontent.com/84044666/198038433-4dc5127f-0ad8-48e2-abb3-a97164748257.png)

didn't you use adobe animate or this software https://github.com/UncertainProd/FnF-Spritesheet-and-XML-Maker
