### ISSUE TITLE
When I open story mode or freeplay, the game crashes

### ISSUE THREAD

**Issue by Fridox-lol** [ShadowMario/FNF-PsychEngine#11005]
### Describe your bug here.

C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 318)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 110)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 90)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
WeekData.hx (line 222)
WeekData.hx (line 190)
WeekData.hx (line 178)
StoryMenuState.hx (line 58)/FreeplayState.hx (line 60) (depends on which menu I open)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid char 93 at position 476
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited the main menu

**Comment by TheKitBoi** [comment]
Not a bug
week file needs fixing
send it over

**Comment by Fridox-lol** [comment]
nevermind there was an issue in the week file and i fixed it
