### ISSUE TITLE
Feature request: animations based on ratings

### ISSUE THREAD

**Issue by FNFUNBLOCKED** [ShadowMario/FNF-PsychEngine#11008]
### What feature do you want to get added on the **base** engine?

so i had an idea the other day, (based off of this: https://www.youtube.com/watch?v=dObzU7amIBU), and i thought "what if animations were based off of the player's ratings?" like bad would be like a miss animation, and etc.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by FNFUNBLOCKED** [comment]
this does not relate to icons, the icons are normal, and they don't have to change.

**Comment by impostor5875** [comment]
you can make that yourself in lua or something, there's no way that's getting added to the base engine

**Comment by FNFUNBLOCKED** [comment]
maybe it will... who knows? plus im dumb and dont know how to code in lua :|

**Comment by impostor5875** [comment]
it should be pretty simple to make anyways, you just check for if any of the ratings changed (like `local curSicks = sicks` and `if curSicks < sicks then`) and then do the funny animation stuff

**Comment by TheKitBoi** [comment]
> maybe it will... who knows? plus im dumb and dont know how to code in lua :|

you can wait until the script from the video releases

**Comment by FNFUNBLOCKED** [comment]
ok

i am stupid haha

**Comment by FNFUNBLOCKED** [comment]
thanks for the help
