### ISSUE TITLE
luaDebugMode not working in 0.6.3

### ISSUE THREAD

**Issue by helpmeiguess** [ShadowMario/FNF-PsychEngine#11009]
### Describe your bug here.

So, I was trying to find port an old script that broke in 0.6.3, and attempted to turn on luaDebugMode (YES, I DID IT INSIDE OF A FUNCTION, SPECIFICALLY ONCREATEPOST), and nothing was printed. I thought that it was just lua sucking in general so i decided to test out luaDebugMode with something that would obviously print an error. The code is shown here.
`function onSongStart()
	luaDebugMode = true
	debugPrint(hjjkgjg)
end`
No error is printed.
I tried launching with cmd, and when i try to debugPrint the undefined variable, this is printed in the terminal.
`source/FunkinLua.hx:3130:`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added a lua file with the contents "function onSongStart() 	luaDebugMode = true 	debugPrint(hjjkgjg) end"

**Comment by TheKitBoi** [comment]
It supposed to work on create
function onCreate()
    luaDebugMode = true
end

**Comment by helpmeiguess** [comment]
acutally @TheKitBoi, it still doesnt work, and it wouldnt work even then because luaDebugMode isnt defined at the time of oncreate, as are many other variables and functions

**Comment by frantastic24** [comment]
you're getting "nothing" because it's null?

**Comment by TheKitBoi** [comment]
I forgot there’s a change it supposed to be 2 =
luaDebugMode == true

**Comment by helpmeiguess** [comment]
I am aware of that, but it is supposed to print an error because luaDebugMode is true.

**Comment by helpmeiguess** [comment]
redownload fixed the problem

**Comment by VoidedBattery** [comment]
I'm getting this bug too on 0.7.3 where I'm purposefully making errors on runHaxeScript() but it isn't throwing any errors
