### ISSUE TITLE
How to make thank you image after completing the mod (0.5.2h only please)

### ISSUE THREAD

**Issue by shilzzzlol** [ShadowMario/FNF-PsychEngine#11015]
### Describe your problem here.

so uhhhh I'm tryna make a thank you image for after completing every singular song in 0.5.2h (if it's even possible) credit will also be given

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

only discord.hx and project.xml

**Comment by Justudude321** [comment]
Hmm, I know how to do this for weeks but for songs perhaps just a bunch of Bools for each song and a counter?
```
public static var "Song1":Bool = false; ...
public static var "Songwhatevr the last num is":Bool = false;
public static var "songCounter":Int = 0;
```

Skip to
```
public function endSong():Void
{
```

Set up a String that gets the song name and just shove a bunch of if statements in there relating to the Bools of each song
```
var theName:String = Paths.formatToSongPath(SONG.song);
if(theName == 'whatever the song's name is' && !Song1) {
Song1= true;
songCounter++;
}
```
It should never be false again after you finish the song the first time, after all those ifs' put one more for the counter
```
if(songCounter== (the total amount of songs you have)) whatever code there is to show an image since idk how to do that part 
```
You could make a short video of that image and just shove it in the video folder and just make an extra variable
```var allowEnd:Bool = false;```
And change the song counter code to have
``` 
... amount of songs you have && !allowEnd){
startVideo('Thank You for playing');
allowEnd = true;
return;
}
```

**Comment by Justudude321** [comment]
This is probably messy but it should work, I think...

**Comment by shilzzzlol** [comment]
thanks man

**Comment by TheKitBoi** [comment]
close the issue
![close the dam issue](https://user-images.githubusercontent.com/84044666/201172013-2769ecf6-1a5f-43a8-9db5-13a216545d80.gif)
