### ISSUE TITLE
Path to sound file without error when building

### ISSUE THREAD

**Issue by DMMaster636** [ShadowMario/FNF-PsychEngine#11019]
### Describe your problem here.

So, i want the game to check if the sound file exists first (pic 1), and then load it, but when I do this, i get this error (pic 2)
![image](https://user-images.githubusercontent.com/86197998/198354393-80ea91a2-1a11-4626-ba41-f8130df73af1.png)
![image](https://user-images.githubusercontent.com/86197998/198354205-d611f000-85cc-4184-a7eb-3077bee7d1d2.png)
While I could just do "assets/sounds/freestyle/", i feel like it would be inconsistent and not good.
Is there any other way to do it?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited PlayState to do something when pressing a key

**Comment by DisIsNOt** [comment]
May be it's Paths.something or something idk
