### ISSUE TITLE
no transition for custom state

### ISSUE THREAD

**Issue by alex-codes-stuff** [ShadowMario/FNF-PsychEngine#11014]
### Describe your problem here.

whenever i enter my custom state, the transition fades in, but instead of fading out after, it just kinda snaps.
**_also im using v5.1_**
### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, MainMenuState.hx and some other smaller stuff

**Comment by alex-codes-stuff** [comment]
nevermind fixed it

**Comment by Bobchara** [comment]
How did you fix it?I have the same problem as well
