### ISSUE TITLE
how to add song in mod folder 

### ISSUE THREAD

**Issue by Whiteconbi** [ShadowMario/FNF-PsychEngine#11016]
### Describe your problem here.

not a problem i just need help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Whiteconbi** [comment]
im building from lua

**Comment by DisIsNOt** [comment]
Put your song's json , inst and voices in the data/yoursong and songs/yoursongs

**Comment by Whiteconbi** [comment]
i tried that and the music wont play

**Comment by DisIsNOt** [comment]
can you show an example of that?

**Comment by Whiteconbi** [comment]
sure

**Comment by Whiteconbi** [comment]
https://steamuserimages-a.akamaihd.net/ugc/1886472472721001520/7B6F1F4BA1F46C07D911547F2B9EBFEE7D4EB87E/
