### ISSUE TITLE
Charting Mode GF Icons

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#11010]
### What feature do you want to get added on the **base** engine?

I know, it's very small, but maybe that, if you're having custom gf, and activate the gf-section, that it will then also select the character's icon, that is in place of gf. 
example: stress, it has speakers with pico shooting. so when gf section is on, it will show pico's icon, instead of GF's

oh also second idea:
if you happen to use not implemented characters, like you're trying to port a mod, and it has like the name "whitty" in the chart, but you have no "whitty" character yet. then it will show the "face"-icon. maybe to make some charting better/more readable, it would be cool if  the default faces in chart editor would then be replaced with dad (opponent) and bf (player)
it's somewhat helpful, when you rechart "game over", as the pixel characters have no icons really implemented

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
#5386
