### ISSUE TITLE
How to check whether uses needs alt animation or not (lua)

### ISSUE THREAD

**Issue by mayo78** [ShadowMario/FNF-PsychEngine#1101]
### What is your question?

how to i use lua to check if the current section uses alt animations
![image](https://user-images.githubusercontent.com/75394229/142287795-b6d610d4-7462-4e4a-a11b-876f08af6b61.png)
![image](https://user-images.githubusercontent.com/75394229/142287851-8c617ce5-2990-4cd1-ae31-8abf19956313.png)

**Comment by ShadowMario** [comment]
I will add a check to it on the next update, my bad.

**Comment by mayo78** [comment]
cool thanks
