### ISSUE TITLE
(0.6.2) Whats the lua variable for value one in an event?

### ISSUE THREAD

**Issue by ColdlordXRepositories** [ShadowMario/FNF-PsychEngine#11011]
### Describe your problem here.

I'm trying to change the window name and i just can't get it. Can anyone tell me?
My code:
`function onCreate() setPropertyFromClass("openfl.Lib", "application.window.title", (value1)) end`
please tell me if im doing something wrong

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
`onCreate()` doesn't use variables, you're supposed to use `onEvent()`
the wiki has a list of callbacks

**Comment by Drawoon2** [comment]
For change that you need run a haxe code
 `addHaxeLibrary('Application', 'lime.app') 
runHaxeCode([[
   Application.current.window.title="String";
]])`

**Comment by CaptainBaldi** [comment]
> For change that you need run a haxe code `addHaxeLibrary('Application', 'lime.app') runHaxeCode([[ Application.current.window.title="String"; ]])`

you don't need runHaxeCode to change the window title

**Comment by ColdlordXRepositories** [comment]
Nobody even tried giving me an answer for my original question.
Whatever, I managed to figure it out

**Comment by CaptainBaldi** [comment]
> Nobody even tried giving me an answer for my original question. Whatever, I managed to figure it out

clearly you cant read then
