### ISSUE TITLE
LUA SHITS

### ISSUE THREAD

**Issue by Gurudevsing** [ShadowMario/FNF-PsychEngine#11029]
### Describe your problem here.

FUNKDELA MOD

HOW TO REDUCE TRANSPARANCY OF VINTAGE SCREEN
![Screenshot (35)](https://user-images.githubusercontent.com/87480185/198650241-df0a29ad-a90d-46b5-ae4c-7ee5a9f9b328.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
would you stop saying 'LUA SHITS' on every issue that you make
and show what line the vintage created

**Comment by TFLTV** [comment]
setProperty("vintage.alpha", 0.5)

value one: put the name of the vintage and put .alpha at the end

value two: the value you want to change the alpha to

**Comment by Gurudevsing** [comment]
> would you stop saying 'LUA SHITS' on every issue that you make and show what line the vintage created

ooookkkk

**Comment by Gurudevsing** [comment]
> setProperty("vintage.alpha", 0.5)

thanks
