### ISSUE TITLE
Psych crash upon loading chart editor or song

### ISSUE THREAD

**Issue by Generalisk** [ShadowMario/FNF-PsychEngine#11028]
### Describe your problem here.

`StrumNote.hx (line 139)
flixel/group/FlxGroup.hx (line 175)
flixel/group/FlxGroup.hx (line 175)
flixel/addons/ui/FlxUIState.hx (line 212)
MusicBeatState.hx (line 70)
PlayState.hx (line 3028)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng`

Psych crashes with this error message upon loading the chart editor or a song, any ideas on whats causing this (yes, haxe is up-to-date)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I only added a extra stage to PlayState.hx

**Comment by notahumans-official** [comment]
Try deleting and then readding the new stage. Otherwise, you might want to try uninstalling the editor and then redownloading it. Hope this helps.
