### ISSUE TITLE
Add sprites to a Custom Substate

### ISSUE THREAD

**Issue by KirbyKid256** [ShadowMario/FNF-PsychEngine#11020]
### What feature do you want to get added on the **base** engine?

The ability to add sprites into a custom substate. Because whenever you add a Lua sprite, regardless of whether or not you use, for example, onCustomSubstateCreate, sprites are always made and used in the PlayState class. If the substate pauses your game, this can cause an animated sprite to not be animated. So there should be a way to add sprites to the Custom Substate instead of PlayState.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
runHaxeCode exists for this

**Comment by KirbyKid256** [comment]
So how would I use runHaxeCode to do that? I'm not too familiar with Haxe code.

**Comment by frantastic24** [comment]
```haxe
CustomSubstate.add(object);
```

**Comment by ShadowMario** [comment]
```lua
function onSongStart()
	runTimer('start break', 0.2);
end

function onTimerCompleted(tag, a, b)
	if tag == 'start break' then
		openCustomSubstate('littleBreak', true);
	end
end

function onCustomSubstateCreate(tag)
	if tag == 'littleBreak' then
		runHaxeCode([[
			FlxG.sound.play(Paths.sound('confirmMenu'));
			bgSpr = new FlxSprite().makeGraphic(FlxG.width, FlxG.height, 0xFF000000);
			bgSpr.alpha = 0.4;
			CustomSubstate.instance.add(bgSpr);

			new FlxTimer().start(1.0, function(tmr)
			{
				FlxG.sound.play(Paths.sound('cancelMenu'));
				game.closeSubState();
			});
		]])
	end
end```
