### ISSUE TITLE
Graphics Menu Error

### ISSUE THREAD

**Issue by FrogB** [ShadowMario/FNF-PsychEngine#11027]
### Describe your problem here.

While trying to compile the mod, test it and test the options menu, I found out that pressing GRAPHICS instantly give me an error and closes the game.

To be more specific:
options/BaseOptionsMenu.hx (line 262)
flixel/FlxState.hx (line 203)
flixel/FlxState.hx (line 212)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

I know this doesn't look like much but is there any suggestions/fixes I can do in order to actually "get into" the graphics menu? Because for instance if people wanted to turn off shaders for the mod, they'll come complaining to me with the error.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Shaders.Hx, Freeplay.Hx, PlayState.hx and GraphicsSettingsSubState.hx

**Comment by Raltyro** [comment]
wtf a shaders.hx

**Comment by lemz1** [comment]
BaseOptionsMenu.hx checks in line 262 if boyfriend isn't null so you probably deleted the bf.json file

**Comment by ACrazyTown** [comment]
Looks like the error's called because `boyfriend.animation.curAnim` is null, are you sure you've called an animation?

**Comment by FrogB** [comment]
I got it fixed, thanks.
