### ISSUE TITLE
Bug with discord_rpc

### ISSUE THREAD

**Issue by Soeiz** [ShadowMario/FNF-PsychEngine#11031]
### Describe your bug here.

Recently, I had a huge bug on my pc and it was running very slowly. I reset it, and now I wanted to download everything to be able to compile. Everything went fine, but then I had to download discord_rpc. I typed "haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc", it says "You already have discord_rpc version git installed.", and then, "Updating discord_rpc version git ...". After that, nothing's happening. I really don't understand why. If you could help me, it would be super awesome. 

### Command Prompt/Terminal logs (if existing)

```bash
F:\games\...\psych engine MAIN 582>haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
You already have discord_rpc version git installed.
Updating discord_rpc version git ...
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ACrazyTown** [comment]
Did you download [git-scm?](https://git-scm.com/)

**Comment by Soeiz** [comment]
> Did you download [git-scm?](https://git-scm.com/)

Yes, I did. Everything was working expect for discord_rpc, I don't understand why

**Comment by DisIsNOt** [comment]
May be uninstall it and install it again idk

**Comment by Soeiz** [comment]
> May be uninstall it and install it again idk

I already done that twice.

**Comment by ACrazyTown** [comment]
> > May be uninstall it and install it again idk
> 
> I already done that twice.

It might be an anti-virus program interfering, if you have any try disabling them while you install

**Comment by DisIsNOt** [comment]
> > May be uninstall it and install it again idk
> 
> I already done that twice.

burj

**Comment by Soeiz** [comment]
> > > May be uninstall it and install it again idk
> > 
> > 
> > I already done that twice.
> 
> It might be an anti-virus program interfering, if you have any try disabling them while you install

It is not working, could I delete the discord_rpc folder or file to try re-download it again ?

**Comment by ACrazyTown** [comment]
> > > > May be uninstall it and install it again idk
> > > 
> > > 
> > > I already done that twice.
> > 
> > 
> > It might be an anti-virus program interfering, if you have any try disabling them while you install
> 
> It is not working, could I delete the discord_rpc folder or file to try re-download it again ?

You could try. The discord_rpc folder will be located at `C:\HaxeToolkit\haxe\Lib\discord_rpc` IF you didn't change the default path. Otherwise, you're gonna have to find it yourself.
