### ISSUE TITLE
Add sex

### ISSUE THREAD

**Issue by tailsicweneedtocook** [ShadowMario/FNF-PsychEngine#11035]
### What feature do you want to get added on the **base** engine?

Sex achievement you get by pfc'ing all weeks

This was supposed to be bait but it’s actually a good feature rather than getting nothing from it other than internet points

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CaptainBaldi** [comment]
what is this github page anymore

**Comment by MemeHoovy** [comment]
Go fuck yourself

**Comment by TheKitBoi** [comment]
> ### What feature do you want to get added on the **base** engine?
> Sex achievement you get by pfc'ing all weeks.

Do it yourself
https://gamebanana.com/mods/398462

**Comment by tailsicweneedtocook** [comment]
> > ### What feature do you want to get added on the **base** engine?
> > Sex achievement you get by pfc'ing all weeks.
> 
> do it yourself https://gamebanana.com/mods/398462

no

**Comment by cooldude47980597** [comment]
What the fuck is your problem you wasted  potential in this your falling+ no bitches

**Comment by ender69-hx** [comment]
No
