### ISSUE TITLE
Feature Request: Lua PlayState Scripts

### ISSUE THREAD

**Issue by crispyi2** [ShadowMario/FNF-PsychEngine#1103]
### What feature do you want to get added on the base engine?

# Feature Description

Lua scripts that run whenever you load playstate a song regardless of the song you choose

# Ideas

## Filesystem

Playstate scripts would go in the playstate_scripts or custom_scripts folder in both the assets directory and the mods directory and will be run whenever the player loads into a song.

## Enabling and Disabling scripts

I also think it would be a good idea if you could enable and disable certain scripts on certain songs. Maybe this could be done through the chart editor in a scripts tab of sorts...

and speaking of which

### Scripts Tab
___

#### Scripts Tab Menu Structure:

<details><summary>📁 Scripts</summary>
    A dropdown menu containing a list of all the lua scripts located in the playstate_scripts folder
    When a script is selected you can change this setting:
    <details><summary>📁 Enabled</summary>
    	A checkbox toggling the script being on and off
    </details>
</details>

**Comment by ShadowMario** [comment]
That's... certainly a neat idea.

**Comment by crispyi2** [comment]
> That's... certainly a neat idea.

Thanks! I got the idea of it while thinking about having to rewrite playstate.hx whenever I want to update the engine version my mod is running on

**Comment by ShadowMario** [comment]
Done.
Put them in `mods/scripts/` or `mods/your-mod-name/scripts/`
