### ISSUE TITLE
Ok, hear me out...

### ISSUE THREAD

**Issue by notahumans-official** [ShadowMario/FNF-PsychEngine#11032]
### What feature do you want to get added on the **base** engine?

Ok, hear me out...
Browser Edition?

Just a simple, basic, browser edition to save storage on our computers, please?

This would be quite useful.

Or is there one already?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MemeHoovy** [comment]
just build to html5

**Comment by CaptainBaldi** [comment]
psych unextracted is like 300mb how fucking trash is your computer

**Comment by cooldude47980597** [comment]
> psych unextracted is like 300mb how fucking trash is your computer

The creator: go fucking play baldis basics dumbass

**Comment by notahumans-official** [comment]
> psych unextracted is like 300mb how fucking trash is your computer

im on a chromebook dumbass i cant run .exe files.
