### ISSUE TITLE
The game crashes mid song

### ISSUE THREAD

**Issue by irfan2008** [ShadowMario/FNF-PsychEngine#11043]
### Describe your problem here.

When I start playing the song, it starts off normal until it crashes in the middle of the song, it doesn't give any error it just close the game with no reason, this issue only happen on source code. Btw what version do you use to make psych engine 0.6.3 (like haxe, git, etc) because i wanna try it out and see if it doesn't crash.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I was trying to add back the shader for dave and bambi shit

**Comment by ripsyhehe** [comment]
try lowering fps to 60 if its more than that

**Comment by irfan2008** [comment]
> try lowering fps to 60 if its more than that

It work, but it doesn't crash on the song below 5 minutes, it still happen on my 5 minutes song which crashes on roughly 0:24

**Comment by Jevilm** [comment]
what version are you on, if its below 0.6 then you crash more (i think)

**Comment by irfan2008** [comment]
> what version are you on, if its below 0.6 then you crash more (i think)

I'm on version 0.6.3

**Comment by Jevilm** [comment]
> > what version are you on, if its below 0.6 then you crash more (i think)
> 
> I'm on version 0.6.3

oof, does it have any custom events or modcharts? or bad pc

**Comment by irfan2008** [comment]
> > > what version are you on, if its below 0.6 then you crash more (i think)
> > 
> > 
> > I'm on version 0.6.3
> 
> oof, does it have any custom events or modcharts? or bad pc

not even custom event or modchart, but my pc can handle very spammy note, but maybe not 8 notes stack on each other when botplay tries to hit them, but it still doesn't crash

**Comment by ACrazyTown** [comment]
It's hard to debug crashes without any errors. You might have to just slap a trace each line to narrow down the problem. if it happens in the middle of the song, it's probably something from update(). Check if you have edited anything from update(), try to fix it, otherwise debug with traces.

**Comment by irfan2008** [comment]
> It's hard to debug crashes without any errors. You might have to just slap a trace each line to narrow down the problem. if it happens in the middle of the song, it's probably something from update(). Check if you have edited anything from update(), try to fix it, otherwise debug with traces.

Okay now I don't know. What if I give you that source with google drive and you compile it, if it doesn't crash then give me the compiled build so i can test it if it still crash or not.

**Comment by dombomb64** [comment]
I'm having this problem too, but I'm only using Lua, and it crashes closer to the end of the song.

**Comment by Jevilm** [comment]
> I'm having this problem too, but I'm only using Lua, and it crashes closer to the end of the song.

What version are you on

**Comment by dombomb64** [comment]
I'm on version 0.6.3, the latest one. I'm thinking it may have something to do with my scripts overloading the game. What's the maximum amount of scripts to reasonably run on a song?

**Comment by Jevilm** [comment]
> I'm on version 0.6.3, the latest one. I'm thinking it may have something to do with my scripts overloading the game. What's the maximum amount of scripts to reasonably run on a song?

I'd say about 5 if your on a low end device, and 12  - 15 if your on a good

**Comment by dombomb64** [comment]
Oh.
_Oh._
So... there shouldn't be 18 scripts of varying sizes set for release in the scripts folder along with scripts in the chart folders?
Okay. I'll try to combine them.

**Comment by Jevilm** [comment]
> Oh. _Oh._ So... there shouldn't be 18 scripts of varying sizes set for release in the scripts folder along with scripts in the chart folders? Okay. I'll try to combine them.

18 scripts?? What the fuck???

**Comment by dombomb64** [comment]
...Yeah... I didn't think the smaller scripts would be as intensive...

**Comment by dombomb64** [comment]
Okay, I combined them into less files, and it works better. I'll let you guys discuss the original poster's issue.

**Comment by TheKitBoi** [comment]
then close this issue

**Comment by dombomb64** [comment]
It's not mine, though. I just commented here because I felt that it was related enough and because everybody seemed to have stopped talking.

**Comment by irfan2008** [comment]
I'm not using that much script, I'm on source, I say that it only crashes on source, but on lua, it's not

**Comment by Noel3454565FNF** [comment]
same here, but its working on low version of Psych engine
