### ISSUE TITLE
Screen flashing event

### ISSUE THREAD

**Issue by AbyssalChaos** [ShadowMario/FNF-PsychEngine#1104]
### What is your question?

I don't know if this is planned to be put in the engine, but I can't figure out how to do it, so may I implore on how to add an event where the screen flashes a certain color or image?

**Comment by MayoALT** [comment]
you can [make an object](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions)
then [tween the alpha value](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers)

**Comment by ItsCapp** [comment]
somebody's made an event for this, all you have to do is put a png that is just completely white in your images folder and then call it in the custom even
[Image Flash.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/7573492/Image.Flash.zip)
