### ISSUE TITLE
Step Based BPM-Changes

### ISSUE THREAD

**Issue by MarkimusZer0** [ShadowMario/FNF-PsychEngine#11047]
### What feature do you want to get added on the **base** engine?

It's really annoying to have BPM changes be section based since it's really limiting, plus it straight up makes BPM changes that are mid-section completely impossible to do, that or you have to do some really annoying beats per section fuckery, which is not always ideal or even solves the issue

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CaptainBaldi** [comment]
next think you know they're gonna want decimal step based bpm changes

**Comment by MarkimusZer0** [comment]
> next thing you know they're gonna want decimal step based bpm changes

I dunno why that's ur response because BPM changes being section based is a royal pain in the ass, also i think the way BPM changes work is among the reasons why Monster is only a debug song

**Comment by ShadowMario** [comment]
Would require another rewrite on the BPM Changes system, i'm not willing to do it and won't accept PRs about it aswell.
You can pretty much already do this through reducing the amount of steps per section

**Comment by MarkimusZer0** [comment]
> Would require another rewrite on the BPM Changes system, i'm not willing to do it and won't accept PRs about it aswell. You can pretty much already do this through reducing the amount of steps per section

I'd agree but the beats per section system can be a little limiting on that front, i guess if you really didn't want it to be step based you could increase or even just take the cap off of how many beats per section one can use since it's limited to 6
