### ISSUE TITLE
compile bug

### ISSUE THREAD

**Issue by Tamir-YT** [ShadowMario/FNF-PsychEngine#11042]
### Describe your bug here.

i got this error while compiling

Called from ? line 1
Called from CommandLineTools.hx line 1904
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 124
Called from CommandLineTools.hx line 1705
Called from lime/tools/ProjectXMLParser.hx line 21
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 50
Called from lime/tools/ProjectXMLParser.hx line 2041
Called from lime/tools/ProjectXMLParser.hx line 1670
Called from lime/tools/ProjectXMLParser.hx line 1538
Called from lime/tools/ProjectXMLParser.hx line 608
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 709
Called from /Users/runner/hostedtoolcache/haxe/4.2.5/x64/std/neko/_std/sys/FileSystem.hx line 69
Called from /Users/runner/hostedtoolcache/haxe/4.2.5/x64/std/neko/_std/sys/FileSystem.hx line 60
Uncaught exception - std@sys_file_type

is there something i missed??

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Fearester2008** [comment]
It me too
