### ISSUE TITLE
How to make a sprite move in pause menu?

### ISSUE THREAD

**Issue by DestDeHat** [ShadowMario/FNF-PsychEngine#11049]
### Describe your problem here.

I want to do something like Hypno's Lullaby v2.0 where art of the characters show up in the pause menu. I made a script that basically does that, but, the only problem is that the tweens do not function. (Well, they do function, but are frozen in the menu.)

My code:
```lua
local paused = false
local tweenSpeed = 0.45

function onUpdate()
    if songName == "songname" then
        if keyJustPressed("pause") then
            if paused == false then
                paused = true
                makeLuaSprite("pauseSprite","pausecharacters/slime",screenWidth,(screenHeight/2)-((600*0.75)/2))
                addLuaSprite("pauseSprite")
                scaleObject("pauseSprite", 0.75, 0.75)
                doTweenX("pauseSpriteMove", "pauseSprite", screenWidth-((600*0.75)-50), tweenSpeed, "circularInOut")
                setScrollFactor("pauseSprite",0,0)
                setObjectCamera("pauseSprite","other")
                debugPrint("the f")
            elseif paused == true then
                paused = false
                doTweenX("pauseSpriteMove", "pauseSprite", screenWidth, tweenSpeed, "circularInOut")
            end
        end
    end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't.

**Comment by MemeHoovy** [comment]
it’s not possible in lua

**Comment by DestDeHat** [comment]
sad

**Comment by ripsyhehe** [comment]
Im pretty sure it is, this guy made a video of making a custom pause screen in lua, so maybe download the script in the disc, and edit it a bit? [https://youtu.be/AgS4gzhIjBs](url)

**Comment by DestDeHat** [comment]
> Im pretty sure it is, this guy made a video of making a custom pause screen in lua, so maybe download the script in the disc, and edit it a bit? [https://youtu.be/AgS4gzhIjBs](url)

I made a custom pause menu by myself, which fixed the issue, you can't tween sprites in the real pause menu however.

**Comment by PDL2CGamejolt** [comment]
Help. the image is not appearing
