### ISSUE TITLE
I don't get this.

### ISSUE THREAD

**Issue by SprialNebula** [ShadowMario/FNF-PsychEngine#11046]
### Describe your problem here.

So, I made a few adjustments to a songs .json file and then when I go to the chart editor to reload the .json file, it immediately gives me this:

/Users/runner/hostedtoolcache/haxe/4.2.5/x64/std/haxe/format/JsonParser.hx (line 322)
/Users/runner/hostedtoolcache/haxe/4.2.5/x64/std/haxe/format/JsonParser.hx (line 145)
/Users/runner/hostedtoolcache/haxe/4.2.5/x64/std/haxe/format/JsonParser.hx (line 117)
/Users/runner/hostedtoolcache/haxe/4.2.5/x64/std/haxe/format/JsonParser.hx (line 117)
/Users/runner/hostedtoolcache/haxe/4.2.5/x64/std/haxe/format/JsonParser.hx (line 90)
/Users/runner/hostedtoolcache/haxe/4.2.5/x64/std/haxe/format/JsonParser.hx (line 90)
/Users/runner/hostedtoolcache/haxe/4.2.5/x64/std/haxe/format/JsonParser.hx (line 57)
Song.hx (line 140)
Song.hx (line 132)
FreeplayState.hx (line 371)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid number at position 247: 0.	
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

So, tell me what's the problem. Could it be that the adjustments I made in the file were a bit incorrect? Or something else? 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

ported a few Dave and Bambi mods into the build

**Comment by TheKitBoi** [comment]
send the file

**Comment by SprialNebula** [comment]
how do I do it tho

**Comment by SprialNebula** [comment]
> send the file

it doesn't support json files

**Comment by CrusherNotDrip** [comment]
> > send the file
> it doesn't support json files

copa pasta

**Comment by SprialNebula** [comment]
bro its too long for me to copy

**Comment by DisIsNOt** [comment]
Ctrl+A exists

**Comment by CaptainBaldi** [comment]
![image](https://user-images.githubusercontent.com/86160807/198841966-14cd2646-92df-4a4a-9f3b-7e29ac1514de.png)
this indicates your json is probably fucked

**Comment by TheKitBoi** [comment]
> > send the file
> 
> it doesn't support json files

rename .json to .txt and send it

**Comment by InsiderIV** [comment]
Which .json file are you trying to port over. Like which song?

**Comment by MarkimusZer0** [comment]
Looks like a fucked JSON, if i had to guess you may have accidentally replaced the chart file with save events or improperly ported a song from another engine

**Comment by SprialNebula** [comment]
All I did to the json file was changing the change character script

**Comment by SprialNebula** [comment]
Because in game it wouldn't work

**Comment by MarkimusZer0** [comment]
> Because in game it wouldn't work
What did you change in them exactly and how did you change it because that matters

**Comment by ShadowMilky** [comment]
> bro its too long for me to copy

EXPORT IT AS A TXT FILE
(sorry for caps)
