### ISSUE TITLE
Error on building 0.6.3

### ISSUE THREAD

**Issue by VPcume-Dev** [ShadowMario/FNF-PsychEngine#11044]
### Describe your problem here.

This is the first I build Psych Engine source code and I get this error:
![ảnh](https://user-images.githubusercontent.com/87105792/198831236-2c5996fe-f650-4c8f-97ef-f4e2ec013fff.png)
Can someone help me?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by DisIsNOt** [comment]
Ratio + you need vsc 2019
