### ISSUE TITLE
Hurtnotes not appearing

### ISSUE THREAD

**Issue by FyreTheGuy** [ShadowMario/FNF-PsychEngine#1105]
### Describe your problem here.

I added the instakill notes into my game, and it works. But i try to change the texture of them and it stops working. I took the hurtnotes and changed how they look, put them back in, and now they're invisible. Help?
![Hurtnotes](https://user-images.githubusercontent.com/93235062/142322955-08d00aad-345e-4a92-a4ee-47bcb599f91f.png)

These are the hurtnotes im trying to use

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

**Comment by NS-Unfair** [comment]
I can't really help you with the information I have. Can you show the .xml file for your hurtnotes? I'm thinking it may be an error in the .xml file.

**Comment by FyreTheGuy** [comment]
i figured it out, .xml file for some reason had no text when it was saying what the file is so it said:

<TextureAtlas imagePath="">

and i just wrote down the name of the file.
