### ISSUE TITLE
Change the title bar text

### ISSUE THREAD

**Issue by nennneko5787** [ShadowMario/FNF-PsychEngine#11054]
### What is your question?

When you try to change the title bar, click on the 
(PlayState.hx)
<pre>
#if desktop
import Discord.DiscordClient;
</pre>
and add the following under
<pre>
import lime.app.Application;
</pre>
In addition, add the following to
<pre>
var songName:String = Paths.formatToSongPath(SONG.song);
</pre>
and add the following under
<pre>
Application.current.window.title("Friday Night Funkin': Psych Engine - Now playing "+songName);
</pre>
In addition, add the following to
<pre>
		if(endingSong)
		{
</pre>
added the following under the
<pre>
Application.current.window.title("Friday Night Funkin': Psych Engine");
</pre>
However, I get the following error at build time
<pre>
source/PlayState.hx:1676: characters 4-72 : String cannot be called
source/PlayState.hx:441: characters 3-95 : String cannot be called
</pre>
This may be strange because I am using DeepL translation.

**Comment by frantastic24** [comment]
it's not a function
```

**Comment by frantastic24** [comment]
it's not a function
```

**Comment by frantastic24** [comment]
it's not a function
```haxe
Application.current.window.title = "Title Here";
```

**Comment by nennneko5787** [comment]
Thank you! It worked!
