### ISSUE TITLE
.lua script help

### ISSUE THREAD

**Issue by alexxdddddd** [ShadowMario/FNF-PsychEngine#11056]
### Describe your problem here.

so basicly i did a sprite that is inside a folder that the script get the name of the song and it looks for a file called like the name of the song, for some reason it doesn't work

	makeLuaSprite('head', 'Headings//..songName..' , -1200, 500)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
String should end earlier
```lua
'Headings/' .. songName
```
