### ISSUE TITLE
minor mistake

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#11050]
### Describe your bug here.

Idk how I noticed this
![0 6 3 never really did exist](https://user-images.githubusercontent.com/105890618/198848154-6f5a16b7-7417-461a-9414-524671a1b531.PNG)

(I was playing 0.6.3)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nah, just ported my 0.6.2 mod to 0.6.3

**Comment by MemeHoovy** [comment]
because you are playing 0.6.2

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/commit/a921ced39d5a1ef625cd505d56894d74a3a07a03

**Comment by TFLTV** [comment]
idk downloaded it from here a hour ago 
https://github.com/ShadowMario/FNF-PsychEngine/tree/0.6.3
