### ISSUE TITLE
GF Sad Animation

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#11051]
### Describe your problem here.

I want when the player misses a note, the gf will do the animation crying. If someone could help me I would really appreciate it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ACrazyTown** [comment]
I've literally never done lua before, but by looking through the wiki I think something like this might work
```lua
function noteMiss()
    characterPlayAnim("gf", "sad", true);
end
```

**Comment by GatoMorado621** [comment]
> I've literally never done lua before, but by looking through the wiki I think something like this might work
> 
> ```lua
> function noteMiss()
>     characterPlayAnim("gf", "sad", true);
> end
> ```
> 
> or if using source code, just add:
> 
> ```hx
> if (gf != null) gf.playAnim("sad", true);
> ```
> 
> to the noteMiss function

In the source code, in which file do I need to put that???

**Comment by Gostar64** [comment]
> > I've literally never done lua before, but by looking through the wiki I think something like this might work
> > ```lua
> > function noteMiss()
> >     characterPlayAnim("gf", "sad", true);
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or if using source code, just add:
> > ```hx
> > if (gf != null) gf.playAnim("sad", true);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to the noteMiss function
> 
> In the source code, in which file do I need to put that???

I'd assume in Playstate.hx

**Comment by GatoMorado621** [comment]
> > > I've literally never done lua before, but by looking through the wiki I think something like this might work
> > > ```lua
> > > function noteMiss()
> > >     characterPlayAnim("gf", "sad", true);
> > > end
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > or if using source code, just add:
> > > ```hx
> > > if (gf != null) gf.playAnim("sad", true);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > to the noteMiss function
> > 
> > 
> > In the source code, in which file do I need to put that???
> 
> PlayState.hx

Oki let me check

**Comment by GatoMorado621** [comment]
> > > I've literally never done lua before, but by looking through the wiki I think something like this might work
> > > ```lua
> > > function noteMiss()
> > >     characterPlayAnim("gf", "sad", true);
> > > end
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > >

> > > I've literally never done lua before, but by looking through the wiki I think something like this might work
> > > ```lua
> > > function noteMiss()
> > >     characterPlayAnim("gf", "sad", true);
> > > end
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > or if using source code, just add:
> > > ```hx
> > > if (gf != null) gf.playAnim("sad", true);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > to the noteMiss function
> > 
> > 
> > In the source code, in which file do I need to put that???
> 
> PlayState.hx

Thank you so much. Now I can continue with my mod. TYSM ❤️❤️

**Comment by ACrazyTown** [comment]
ur welcome
