### ISSUE TITLE
objectsOverlap doesn't support rotated objects

### ISSUE THREAD

**Issue by DisIsNOt** [ShadowMario/FNF-PsychEngine#11055]
### Describe your bug here.

nevermind undertale moment

https://user-images.githubusercontent.com/78010753/198862473-fc4c489a-9493-4110-991e-60c30b5a4a75.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

e

**Comment by frantastic24** [comment]
Haxe issue

**Comment by DisIsNOt** [comment]
real
