### ISSUE TITLE
Shader Help

### ISSUE THREAD

**Issue by Thimque** [ShadowMario/FNF-PsychEngine#11067]
### Describe your problem here.

So, im trying to get a shader for 0.6.3 of Psych Engine to work, but i have no idea what to do and would really like some help
Shader im trying to use
https://www.shadertoy.com/view/MdffD7

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not.

**Comment by CaptainBaldi** [comment]
i wrote [this](https://gamebanana.com/tuts/15316) tutorial on shaders that gives a basic understanding of them

**Comment by Thimque** [comment]
> i wrote [this](https://gamebanana.com/tuts/15316) tutorial on shaders that gives a basic understanding of them

Okay, so it seems like everything is working, the shaders are loading, but when putting in the initLuaShader code, it doesnt load but at the same time doesnt give me an error. And when going down another path (i followed a shader tut last night before bed) it loads, but gives me a black screen.

This is the code the shader tut gave me
function onCreatePost()
     luaDebugMode = true
    initLuaShader("vhsshader")

    makeLuaSprite("shaderImage")
    makeGraphic("shaderImage", screenWidth, screenHeight)

    setSpriteShader("shaderImage", "vhsshader")

    addHaxeLibrary("ShaderFilter", "openfl.filters")
    runHaxeCode([[
        trace(ShaderFilter);
        game.camGame.setFilters([new ShaderFilter(game.getLuaObject("shaderImage").shader)]);
        game.camHUD.setFilters([new ShaderFilter(game.getLuaObject("shaderImage").shader)]);
    ]])
end

function onUpdate(elapsed)
    setShaderFloat("shaderImage", "iTime", os.clock())
end

**Comment by CaptainBaldi** [comment]
> > i wrote [this](https://gamebanana.com/tuts/15316) tutorial on shaders that gives a basic understanding of them
> 
> Okay, so it seems like everything is working, the shaders are loading, but when putting in the initLuaShader code, it doesnt load but at the same time doesnt give me an error. And when going down another path (i followed a shader tut last night before bed) it loads, but gives me a black screen.
> 
> This is the code the shader tut gave me function onCreatePost() luaDebugMode = true initLuaShader("vhsshader")
> 
> ```
> makeLuaSprite("shaderImage")
> makeGraphic("shaderImage", screenWidth, screenHeight)
> 
> setSpriteShader("shaderImage", "vhsshader")
> 
> addHaxeLibrary("ShaderFilter", "openfl.filters")
> runHaxeCode([[
>     trace(ShaderFilter);
>     game.camGame.setFilters([new ShaderFilter(game.getLuaObject("shaderImage").shader)]);
>     game.camHUD.setFilters([new ShaderFilter(game.getLuaObject("shaderImage").shader)]);
> ]])
> ```
> 
> end
> 
> function onUpdate(elapsed) setShaderFloat("shaderImage", "iTime", os.clock()) end

I've noticed that applying shaders to the hud can make everything black
most shaders seem to tweak alpha and camHUD's alpha is usually 0
im not much of an expert with shaders, i wrote some basic documentation of them, that's about it
best thing i can think of is that you apply the shader to each hud object manually instead of doing it all at once
for shorter code you can use tables, but in the long run it doesn't really matter

**Comment by Thimque** [comment]
> > > i wrote [this](https://gamebanana.com/tuts/15316) tutorial on shaders that gives a basic understanding of them
> > 
> > 
> > Okay, so it seems like everything is working, the shaders are loading, but when putting in the initLuaShader code, it doesnt load but at the same time doesnt give me an error. And when going down another path (i followed a shader tut last night before bed) it loads, but gives me a black screen.
> > This is the code the shader tut gave me function onCreatePost() luaDebugMode = true initLuaShader("vhsshader")
> > ```
> > makeLuaSprite("shaderImage")
> > makeGraphic("shaderImage", screenWidth, screenHeight)
> > 
> > setSpriteShader("shaderImage", "vhsshader")
> > 
> > addHaxeLibrary("ShaderFilter", "openfl.filters")
> > runHaxeCode([[
> >     trace(ShaderFilter);
> >     game.camGame.setFilters([new ShaderFilter(game.getLuaObject("shaderImage").shader)]);
> >     game.camHUD.setFilters([new ShaderFilter(game.getLuaObject("shaderImage").shader)]);
> > ]])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > end
> > function onUpdate(elapsed) setShaderFloat("shaderImage", "iTime", os.clock()) end
> 
> I've noticed that applying shaders to the hud can make everything black most shaders seem to tweak alpha and camHUD's alpha is usually 0 im not much of an expert with shaders, i wrote some basic documentation of them, that's about it best thing i can think of is that you apply the shader to each hud object manually instead of doing it all at once for shorter code you can use tables, but in the long run it doesn't really matter

Im not really sure how to do that.. im a very basic coder, novice if anything, so idk much about all this stuff, is there a tut i should watch that will help me with that stuff?
