### ISSUE TITLE
Old 0.5.1 script crashing the game (0.6.3)

### ISSUE THREAD

**Issue by Intancote** [ShadowMario/FNF-PsychEngine#11062]
### Describe your problem here.

Psych Engine crashes when it tries to do `if curBeat == 96 then
		for i = 0, getProperty('playerStrums.length')-1 do
			setPropertyFromGroup('playerStrums', i, 'texture', 'invisiblenote')
		end`
The function plays again at `curBeat == 240` and crashes it if the first one is there but not if it's not (is comment or similar).
This worked before on 0.5.1 but now it just doesn't.
Been trying to fix this for 3 hours now and just don't know what to do. the main problem is at `setPropertyFromGroup`

(I'm mostly new to Lua, so sorry ahead of time)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, it's a release build

**Comment by MemeHoovy** [comment]
Lua has changed a lot since 0.5.1 so old scripts might not work anymore or at all

**Comment by Intancote** [comment]
> Lua has changed a lot since 0.5.1 so old scripts might not work properly or at all

I know that... which makes it even more confusing when it works when the first one is disabled but not enabled.

**Comment by Intancote** [comment]
I made it work now. Instead of changing the strums to a different texture, I just did this: `setProperty('strumLineNotes.visible', false)` and true later to make it visible again.
