### ISSUE TITLE
time left on timer

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#11065]
### What is your question?

is there a way to get the time left on a timer

in lua (forgot to put this here)

**Comment by MemeHoovy** [comment]
In lua?

**Comment by TFLTV** [comment]
> In lua? You didn’t specify

its in lua

**Comment by frantastic24** [comment]
```lua
runHaxeCode('return game.modchartTimers["timer"].timeLeft')
```

**Comment by TFLTV** [comment]
how would you do this?
```lua
    makeLuaText("PowerTimer", runHaxeCode('return game.modchartTimers["PowerCooldown"].timeLeft'), 300, 1050, 500)
    addLuaText('PowerTimer')
```

(lua)

**Comment by frantastic24** [comment]
yeah that looks fine

**Comment by TFLTV** [comment]
> yeah that looks fine

Dosen't work (forgot to reply)

**Comment by TFLTV** [comment]
> yeah that looks fine

No, it doesn't work, how would I display the timer on text.  The text does not appear using that code.

**Comment by frantastic24** [comment]
works just fine for me

**Comment by TFLTV** [comment]
figured it out but,
how do you attach a variable with a string?

```lua
makeLuaText("PowerTimer", runHaxeCode('return game.modchartTimers["PowerCooldown" .. TimesPoweredUp].timeLeft'), 300, 1050, 500)
addLuaText('PowerTimer')
```

**Comment by frantastic24** [comment]
Assuming the variable is from your script, you need to do it through Lua, not haxe
I think this should work?
```lua
runHaxeCode('game.modchartTimers["PowerCooldown' .. TimesPoweredUp  .. '"].timeLeft')
```

**Comment by TFLTV** [comment]
> Assuming the variable is from your script, you need to do it through Lua, not haxe I think this should work?
> 
> ```lua
> runHaxeCode('game.modchartTimers["PowerCooldown' .. TimesPoweredUp  .. '"].timeLeft')
> ```

That does not work...

**Comment by TFLTV** [comment]
I tried
```lua
runHaxeCode('game.modchartTimers[\"PowerCooldown\" .. TimesPoweredUp  .. \"].timeLeft\"')

runHaxeCode('game.modchartTimers[\"PowerCooldown\' .. TimesPoweredUp  .. \'\"].timeLeft')

runHaxeCode('game.modchartTimers[\"PowerCooldown\" .. TimesPoweredUp  .. \"].timeLeft\"')

```

**Comment by frantastic24** [comment]
what i sent is working for me, you don't need to edit it

**Comment by TFLTV** [comment]
figured it out right before you commented lol

I did:
function onUpdate()
    setTextString('PowerTimer', runHaxeCode('game.modchartTimers["PowerCooldown' .. TimesPoweredUp  .. '"].timeLeft' ))
end
