### ISSUE TITLE
helppppppp

### ISSUE THREAD

**Issue by furry1212** [ShadowMario/FNF-PsychEngine#11060]
### Describe your problem here.

im using ver 0.6.3

sooo i was doing stage stuf and i wote some code for the "scripts" folder in mod folder, and this happned
![Screenshot 2022-10-30 175721](https://user-images.githubusercontent.com/116885855/198872941-6daeed83-9344-4642-bd2d-4d2697357cea.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

i edit nothin

**Comment by furry1212** [comment]
it was my stage!!!!!! AAAAAAAAAAAAAAAHHHHHHHHHHHHH       🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶

**Comment by TheKitBoi** [comment]
Well
that was disappointing

**Comment by DisIsNOt** [comment]
tru
