### ISSUE TITLE
setProperty does not work

### ISSUE THREAD

**Issue by PlasmaOJ15** [ShadowMario/FNF-PsychEngine#11064]
### Describe your bug here.

Using setProperty to change alpha value, setProperty('gf.alpha',0), did not do anything, and neither does setProperty('defaultCamZoom', 0.5)
Exact code used for camZoom:
function onBeatHit()
       if curBeat == 4 then
            setProperty('defaultCamZoom', 0.5)
       end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only LUA coding

**Comment by PlasmaOJ15** [comment]
Okay found a less important but still a bug, CamZoom change wont work unless there are notes in the chart

**Comment by frantastic24** [comment]
Not a bug, it's how the game works
