### ISSUE TITLE
Problem with game crash after coding clickable weeks

### ISSUE THREAD

**Issue by DavidDXOfficial** [ShadowMario/FNF-PsychEngine#11069]
### Describe your problem here.

So, the problem is: When I try going into a week on a hardcoded story mode menu with clickable weeks, the game crashes with null object reference. The issue is allocated in the PlayState.hx line 447 or which line that string is: detailsText = "Story Mode: " + WeekData.getCurrentWeek().weekName;. If you came up with a solution, let me know :).

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yeah, I made a clickable StoryMenuState.hx from scratch

**Comment by TFLTV** [comment]
show your code

**Comment by DavidDXOfficial** [comment]
nevermind I fixed it
