### ISSUE TITLE
Error when changing stages

### ISSUE THREAD

**Issue by itsoutchy-projects** [ShadowMario/FNF-PsychEngine#11061]
### Describe your bug here.

This occurred just now.

So, basically if I open the chart editor, change the stage and play the song, I get this error:

PlayState.hx (line 2610)
PlayState.hx (line 2465)
PlayState.hx (line 1084)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

This didn't happen before. I haven't modified PlayState.hx in any way.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited MainMenuState.hx and made all items go to the left side of the screen.

**Comment by frantastic24** [comment]
Seems like you're trying to use an event hardcoded to one stage, if so this is not a bug

**Comment by itsoutchy-projects** [comment]
> Seems like you're trying to use an event hardcoded to one stage, if so this is not a bug

Ahh thanks, I'm gonna take a guess that it was the dad battle spotlights.
