### ISSUE TITLE
Songcharts from Mods folder not overriding base-game charts.

### ISSUE THREAD

**Issue by KingMB-XJ** [ShadowMario/FNF-PsychEngine#11068]
### What feature do you want to get added on the **base** engine?

A small problem I've encountered while modding with the mods folder:

If you put a songchart in "PsychEngine/mods/"mod name"/data/"song-name" and you have the name of the chart be one of the base-game's songs, it will not override that chart while the mod is loaded. For example:

If I make a custom chart, call it "tutorial.json" and put it in the folder "PsychEngine/mods/"mod name"/data/tutorial", The chart for tutorial will not change to the custom one while the mod is active. The only way that the custom Tutorial chart will start is if you go into the chart editor, change "Test" to "Tutorial", and reload the Json and audio.

Could you please change it to work like replacing images,  characters, or music through the "PsychEngine/mods/"mod name"/images" folder, "PsychEngine/mods/"mod name"/images/characters" folder, and "PsychEngine/mods/"mod name"/music" folder respectively?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MemeHoovy** [comment]
Do you understand how difficult that would be?

**Comment by KingMB-XJ** [comment]
> Do you understand how difficult that would be?

If we can already replace images, characters, character sprites, music, etc. through the mods folder, probably a copy/paste level difficulty. Yet again, I don't know that to be true since I don't code.

**Comment by UmbratheUmbreon** [comment]
Isn't this already implemented?

<Song,hx loadFromJson function>
![image](https://user-images.githubusercontent.com/101066547/199022946-010e2119-14fe-4e5a-8d02-183f5ba06aaf.png)

**Comment by CaptainBaldi** [comment]
tbh i dont see the point in this. just add the charts in assets/

**Comment by KingMB-XJ** [comment]
> Isn't this already implemented?
> 
> <Song,hx loadFromJson function> ![image](https://user-images.githubusercontent.com/101066547/199022946-010e2119-14fe-4e5a-8d02-183f5ba06aaf.png)

For whatever reason, it wasn't working the last time I tried. I'll test it again when I have the time.

**Comment by KingMB-XJ** [comment]
> tbh i dont see the point in this. just add the charts in assets/

I was modding with **the mods folder** so that it could be dragged and dropped into Psych when I publish the mod, the way modding was intended with this engine. There is no assets folder in the mods folder.

**Comment by KingMB-XJ** [comment]
I have pinpointed my issue.

If you put a custom bopeebo chart in "PsychEngine/mods/data/bopeebo" then it works and replaces the original chart. **BUT**, if you put a bopeebo chart in "PsychEngine/mods/"modname"/data/bopeebo", it will not work.

So it works if you have it in the mods folder, but it doesn't work inside of a drag and drop mod.

**Comment by KingMB-XJ** [comment]
Works:
![image](https://user-images.githubusercontent.com/64709475/199078061-623d714b-6282-4162-9f0d-1ee1931a7e05.png)

Doesn't Work
![image](https://user-images.githubusercontent.com/64709475/199078188-3d9862d7-92c3-4473-924e-8a58b087da68.png)

This was tested in a fresh install of PsychEngine 6.3.
