### ISSUE TITLE
can you port this engine to (fnf) mods that or in unity

### ISSUE THREAD

**Issue by cooldude47980597** [ShadowMario/FNF-PsychEngine#11063]
### What is your question?

how

**Comment by MemeHoovy** [comment]
No

**Comment by CaptainBaldi** [comment]
what

**Comment by CrusherNotDrip** [comment]
https://user-images.githubusercontent.com/90648119/198929241-467ea5b0-1797-487a-84d5-54a75cefaff4.MOV

**Comment by Parsellol** [comment]
wat

**Comment by ManMaster707** [comment]
I'm assuming he's asking how to port this engine into Unity.

Here's my answer:
Technically you can, but it will be difficuilt since you have to recreate the core functions of FNF from scratch, not mentioning the new features this engine adds, like the mods folder.

**Comment by MemeHoovy** [comment]
> does haxe compile its files into c++

yes, it does

**Comment by ShadowMario** [comment]
![image](https://user-images.githubusercontent.com/44785097/218208030-657f693f-7f51-489b-a91c-cf6f1a1feb5d.png)
