### ISSUE TITLE
OGG File not loading

### ISSUE THREAD

**Issue by signedupidiot** [ShadowMario/FNF-PsychEngine#11070]
### Describe your problem here.

So the engine can't load a specific ogg file I use, I'm pretty sure it is the ogg file itself since I tried other ones and they work just fine. Of the various comments **the only thing I've heard about close enough is an "unsupported ogg file"**, it doesnt make sense and I really want to fix this.
**AND NO**, I didn't rename the file, I actually converted a mp4 to ogg with a program but this messes with me.

![image](https://user-images.githubusercontent.com/117076784/198980768-82f90fa2-667d-4bde-96eb-9f17a0b258a8.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TFLTV** [comment]
upload the ogg

**Comment by bruh1cat** [comment]
> ### Describe your problem here.
> 
> 
> 
> So the engine can't load a specific ogg file I use, I'm pretty sure it is the ogg file itself since I tried other ones and they work just fine. Of the various comments **the only thing I've heard about close enough is an "unsupported ogg file"**, it doesnt make sense and I really want to fix this.
> 
> **AND NO**, I didn't rename the file, I actually converted a mp4 to ogg with a program but this messes with me.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/117076784/198980768-82f90fa2-667d-4bde-96eb-9f17a0b258a8.png)
> 
> 
> 
> 
> 
> ### Are you modding a build from source or with Lua?
> 
> 
> 
> Lua
> 
> 
> 
> ### What is your build target?
> 
> 
> 
> Windows x64
> 
> 
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> 
> 
> 
> _No response_

I think it's just an unsupported ogg file, what I would do is record the audio and upload it to youtube or something, and then use 4k video downloader (not sponsoring) to download the vid as ogg and export as Vorbis not the other one.

**Comment by ColdlordXRepositories** [comment]
Try listening to it. Will anything play?

**Comment by signedupidiot** [comment]
> Convert it again, most online converters should work

never though of that, but thank you

**Comment by frantastic24** [comment]
It's a pretty common issue I guess haxe is just really picky about the format??? Thankfully online tools seem to work

**Comment by ACrazyTown** [comment]
Iirc this can happen if your audio file's sample rate over 44.1KHz, you can check it by right clicking on the file and clicking properties and going to the details tab.
