### ISSUE TITLE
how can you set up FlxTrail for a Lua object through HScript

### ISSUE THREAD

**Issue by CaptainBaldi** [ShadowMario/FNF-PsychEngine#11073]
### What is your question?

So I'm trying to find out how I can use FlxTrail to add a trail to a Lua object. I've done some messing around with it by finding some examples in source and trying to convert it to Lua's HScript but I can't figure it out. Does anyone know how?

**Comment by frantastic24** [comment]
#10206

**Comment by CaptainBaldi** [comment]
> #10206

thank youuu
