### ISSUE TITLE
How can I use an atlas instead of a spritesheet

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#11075]
### Describe your problem here.

I'm trying to make an atlas work but idk how to, I'm using this: sprite.frames = AtlasFrameMaker.construct(Path,excludeArray) though I don't exactly know how to make it work.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ACrazyTown** [comment]
You're supposed to replace `Path` and `excludeArray` with your own data. I've never used the atlas library but from what I can tell `Path` is supposed to be the name of your atlas folder. If you have an atlas with the path "assets/images/MyCoolAtlas" the path would be "MyCoolAtlas". Keep `excludeArray` null if you want to add all the animations.
So all that would be something like this:
```haxe
sprite.frames = AtlasFrameMaker.construct("MyCoolAtlas");
```
Replacing MyCoolAtlas with the name of your atlas obviously.
