### ISSUE TITLE
How To Add Shaders On main Menu

### ISSUE THREAD

**Issue by luacoder279** [ShadowMario/FNF-PsychEngine#11076]
### Describe your problem here.

How Do I Add Shaders On The Main Menu Like Dave And Bambi 3.0 When Its On Expunged Mode

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHoovy** [comment]
https://github.com/MoldyGH/VsDave

**Comment by ShadowMilky** [comment]
copy the code in VsDave’s mainmenustate.hx that adds the shader code
and then paste it to the psych mainmenustate.hx
easy peasy
