### ISSUE TITLE
Files in "PsychEngine/mods/"modname" Not overriding base-game files. Only overrides in "PsychEngine/mods".

### ISSUE THREAD

**Issue by KingMB-XJ** [ShadowMario/FNF-PsychEngine#11071]
### Describe your bug here.

For Example: If you put a custom bopeebo chart in "PsychEngine/mods/data/bopeebo" then it works and replaces the original chart. BUT, if you put a bopeebo chart in "PsychEngine/mods/"modname"/data/bopeebo", it will not work and use the original chart.

Works:
![image](https://user-images.githubusercontent.com/64709475/199080526-89f540fd-3261-4dc8-a2b7-f1fd113df926.png)

Doesn't Work:
![image](https://user-images.githubusercontent.com/64709475/199080551-c3daef36-8993-46d7-bbed-b822aa633c93.png)

So it works if you have it in the mods folder, but it doesn't work inside of a folder in the mods folder.

The reason why I'm asking this to be fixed is because the "Modname" folder in "PsychEngine/mods" type of mod replaces music (like the title screen song, pause menu song, game over song, etc;) and music, so why not charts?

_I tested this in a fresh install of PsychEngine 6.3_

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by KingMB-XJ** [comment]
To test it:

1. Get a fresh install of Psych
2. Change a chart of a song in the base game (like bopeebo) and save it in "PsychEngine/mods/data/name of the song you changed"
3. Restart Psych
4. Play the song you changed (if saved as "song-hard" or "song-easy", play on Hard or Easy)
The changed chart should play.

Now, to test what I'm having problems with:

1. Follow the last steps if you haven't already
2. Close Psych
3. Go into "PsychEngine/mods"
4. Make a new folder and put the contents of "PsychEngine/mods" into that folder. The only folder in "PsychEngine/mods" hould be the new folder you made with everything in it
5. Start Psych
6. Make sure that the mod is on
7. Start the song you changed
If my issue is consistent, the new chart won't play.

**Comment by KingMB-XJ** [comment]
Another minor bug I encountered:

If you have only 1 "PsychEngine/mods/modname" mod in the /mods folder, it will always show as "on" in the mods menu.

**Comment by MemeHoovy** [comment]
> Another minor bug I encountered:
> 
> If you have only 1 "PsychEngine/mods/modname" mod in the /mods folder, it will always show as "on" in the mods menu.

Mods are enabled by default

**Comment by KingMB-XJ** [comment]
> > Another minor bug I encountered:
> > If you have only 1 "PsychEngine/mods/modname" mod in the /mods folder, it will always show as "on" in the mods menu.
> 
> Mods are enabled by default

What I meant was, if you turn it off, exit the menu, and go back in the menu, it'll still be on. at least for mods that reastart the game, like the one I made to test. If I had just one mod, it never stayed off, but if I had 2, they would work as normal.

**Comment by MemeHoovy** [comment]
oh, okay

**Comment by KingMB-XJ** [comment]
But what about my first problem with the data folder not overriding in a "PsychEngine/mods/modname" mod?

**Comment by MemeHoovy** [comment]
Idk man, I can’t do shit atm

**Comment by KingMB-XJ** [comment]
It's alright, but is there anyone here who can? Or are you going to do it when you can? Idk who does what around here.

**Comment by KingMB-XJ** [comment]
I've also found the same problem with the /characters folder. I made a custom "hey" animation for gf-Tankmen and it worked in the character editor, just not when I loaded a week 7 song, or even when I changed gf to gf-Tankmen in a different song. It didn't override the gf-Tankmen.json file whether I put it in "PsychEngine/mods/modname/characters" or "PsychEngine/mods/characters". I don't know if "PsychEngine/mods/modname/images/characters" overrides or not, I'll test it when I get to my computer.

**Comment by KingMB-XJ** [comment]
Here's my findings.

Key: 
M = Only works with "PsychEngine/mods"
MN = Only works with "PsychEngine/mods/modname"
B = Works with Both
N = Works with Neither

Characters = M
Data = M
Images/characters = M
Images/icons = M (editor)
Images/menubackgrounds = M
Images/menucharacters = M
Images/storymenu = M
Music = B
Songs = M
Sounds = B
Stages = M
Weeks = M

From these results, the only files that override base game files while in "PsychEngine/mods/modname" format are Music and Sounds. **By making a "PsychEngine/mods/modname" format mod, you can only replace Music (like freakyMenu.ogg, breakfast.ogg, and gameOver.ogg), and Sounds (Like scrollMenu.ogg, confirmMenu.ogg, cancelMenu.ogg, etc;).**

**Comment by RowanSkie** [comment]
Have you uh, tried opening up your mod.json and setting runsGlobally to true?
