### ISSUE TITLE
Game crashes if a song's name is in quotes but only in 0.6.3

### ISSUE THREAD

**Issue by Blik10** [ShadowMario/FNF-PsychEngine#11072]
### Describe your bug here.

My mod features a fake-out song called **"Blammed"**, both to not replace the base game's **Blammed** and to hint to the player that it isn't actually **Blammed**. Psych and Windows didn't like that name, so I had to write it in the mod's folders as **''blammed''** (with double apostrophes instead of quotes) and in the code as **"''Blammed''"** (quotes then apostrophes, and then apostrophes and quotes) which made everything work as intended.

As of 0.6.3, this method no longer works and crashes upon trying to load the song, displaying this error message:

C:HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
FreeplayState.hx (line 371)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/blammed''/blammed'-hard.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by sqirra-rng

Notably, I would expect the error to say:

[file_contents,assets/data/''blammed''/''blammed''-hard.json]

but instead of that, some of the apostrophes are missing. I went back to 0.6.2 and the song worked fine, so my best guess is that something changed in 0.6.3 that makes the engine read the quotes differently, which crashes my mod.

To confirm that as the issue I tried renaming the song to something else without any quotes or apostrophes, which did fix the crashing, but then the music didn't load (which was even more confusing because I renamed that folder too). I also tried simply setting the data contents to lowercase like the error log displays and that didn't change anything.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Draconic-Hybrid** [comment]
I think this is a bug with the Psych chart editor in general. I've had it crash with that exact same error (save the song name) due to attempting to load one of my modded songs.

**Comment by Blik10** [comment]
I'd be surprised if this was an issue of the chart editor. When I renamed the song to exclude the quotes and apostrophes the chart editor worked flawlessly with the correct notes, music, and events, but then trying to play it anywhere except the chart editor didn't load the music or the song's script (because while the json loaded **BlammedL** perfectly fine, they both went back to **''Blammed''**, which didn't exist anymore).

**Comment by Draconic-Hybrid** [comment]
Hm. Might be an issue on my end in that case.

**Comment by Blik10** [comment]
After a bit of digging I realized that the renamed song wasn't loading the music or scripts because of my own mistake, so that's fixed. The engine still doesn't read the apostrophes like the previous versions do so I'd really appreciate that being checked out eventually.
