### ISSUE TITLE
make numbers space out on each sprite press (idk how to explain it)

### ISSUE THREAD

**Issue by ripsyhehe** [ShadowMario/FNF-PsychEngine#11079]
### Describe your problem here.

i need actual help, ive been stuck on this for like a day :crying:  im trying to do where you press a sprite it adds a number on screen, ive got that but im trying to do multiple numbers, how do i make them spaced out on each press? because it just stacks the numbers (IM IN SOURCE)

https://user-images.githubusercontent.com/93651331/199161573-5ff77fec-bc43-4ce1-85ab-7a03fc9f27b1.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

my own state

**Comment by ACrazyTown** [comment]
Add some kind of tracker integer that increases by one with each number press then multiply with it. Eg something like:
```haxe
myNumber.x = 69 + (i * 80);
```
69 is the starting position, and you can adjust 80 with whatever u want

**Comment by ripsyhehe** [comment]
what does the 80 do?

**Comment by ACrazyTown** [comment]
> what does the 80 do?

It's how many pixels the next sprite will space out, with one number (i = 1) it will be 80, two (i = 2) 160, etc.

**Comment by ripsyhehe** [comment]
it gives me these errors:  Unknown identifier : i and ... For function argument 'NewX'

**Comment by ACrazyTown** [comment]
> it gives me these errors: Unknown identifier : i and ... For function argument 'NewX'

What? What's NewX? Show some code please

**Comment by ripsyhehe** [comment]
![image](https://user-images.githubusercontent.com/93651331/199216133-092cc200-d06f-4a99-9c2c-8c68794e2d62.png)
 im new to coding sorry if code is messy or weird

**Comment by ripsyhehe** [comment]
![image](https://user-images.githubusercontent.com/93651331/199216260-876e66fc-92f1-4a9f-a498-90cf8dc6d8e5.png)
and the one with ur code thing

**Comment by ACrazyTown** [comment]
Well you didn't initialise `i`. You need to do something like `var i:Int = 0;` outside of a function. And also increase i by 1 whenever you click a number, so `i++;`

**Comment by ripsyhehe** [comment]
https://user-images.githubusercontent.com/93651331/199219280-7d4eb51a-721a-4cb0-acd9-40ab2cb8f9f9.mp4
uh it kinda works, but as you can see from the video it just disappears when i let go, i'm trying to make it like you're typing something with a keyboard ykwim?

**Comment by ACrazyTown** [comment]
> https://user-images.githubusercontent.com/93651331/199219280-7d4eb51a-721a-4cb0-acd9-40ab2cb8f9f9.mp4 uh it kinda works, but as you can see from the video it just disappears when i let go, i'm trying to make it like you're typing something with a keyboard ykwim?

It's rapidly moving because you keep increasing the int because the mouse is pressed. You just have to increase it once. As for the dissapearing, I'm not sure why it happens

**Comment by ripsyhehe** [comment]
do you have discord or something so i can send my code?

**Comment by ACrazyTown** [comment]
> do you have discord or something so i can send my code?

Yeah but I don't give it out, sorry. You just have to check if the mouse was [justPressed](https://api.haxeflixel.com/flixel/input/mouse/FlxMouse.html#justPressed) while it's overlapping the number and if it was increase the `i` variable by 1. This should give you proper spacing.

You can also ask for help in the [Haxe discord server](https://discord.com/invite/0uEuWH3spjck73Lo) (for non-FNF stuff; your thing doesn't really count since it's a custom state)

**Comment by ripsyhehe** [comment]
alr, but one last question, when i try to remove the number, it just doesnt remove it and stays there

**Comment by ripsyhehe** [comment]
nvm, i got it! thanks!
