### ISSUE TITLE
Goes to fast when i play it

### ISSUE THREAD

**Issue by WDrawstic** [ShadowMario/FNF-PsychEngine#11078]
### Describe your bug here.

When I try to play in this build, the song goes very fast and everything.
What can i do?
its in 0.6.3

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Press Control before selecting a week/song, or get good

**Comment by UmbratheUmbreon** [comment]
You could have possibly left playback speed higher than 1, or scroll speed depending on which speed you mean. In either case, you can open the gameplay modifiers menu with Control and press Reset (default is R) to set the modifiers to their defaults.
