### ISSUE TITLE
some names give the error "null object reference"

### ISSUE THREAD

**Issue by c00lkase** [ShadowMario/FNF-PsychEngine#11088]
### Describe your bug here.

when typing 'nul', 'con', or 'aux', the game crashes with the error "null object reference"

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMilky** [comment]
they are reserved windows file names which they cannot be used in any file name or folder
