### ISSUE TITLE
64 bit not supported? MY PC IS 64 BITS.

### ISSUE THREAD

**Issue by loool250** [ShadowMario/FNF-PsychEngine#11082]
### Describe your problem here.

So i got this error:
`Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths`
BUUUUT. my Computer is 64 bits. So i dont know whats wrong. If someone knows how to fix it please help.And i dont wanna hear any "your pc is shit" because it isnt.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No. I only downloaded the recent source code version. didnt do any changes.

**Comment by loool250** [comment]
I will close this after its fixed or if it doesnt work.

**Comment by ACrazyTown** [comment]
Looks like you installed the 32bit version of VSC. Delete it and install the 64bit version.

**Comment by loool250** [comment]
Alright.

**Comment by loool250** [comment]
I already have VSC.

**Comment by loool250** [comment]
Still didnt work.

**Comment by loool250** [comment]
> Install VSC 2019 or something

Alright. will try

**Comment by ACrazyTown** [comment]
That error might also appear if you did not install MSVC, did you install MSVC?

**Comment by loool250** [comment]
> That error might also appear if you did not install MSVC, did you install MSVC?

Im installing it.

**Comment by loool250** [comment]
THANK YOU SO MUCH BRO I REALLY LOVE YOU I WOULD KISS YOU RIGHT NOW
