### ISSUE TITLE
I don’t know what is wrong with this?

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#11081]
### Describe your problem here.

![731D15E0-6FC9-4D5F-BB85-3E97ABDF7162](https://user-images.githubusercontent.com/107759455/199195426-6ff8882b-8b9a-410b-a8a1-abb1cb33b336.jpeg)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing I don’t think so

**Comment by NightmaresPlayz** [comment]
if i can do anything then tell me

**Comment by furry1212** [comment]
the crash clearly ses some thing wong with character stuf **"character.hx (line 164)"** and there is a null object reference **"uncaught error: null object reference"**  try checking the code you resently wote!!!!!! i hope this help or sumthin.

**Comment by NightmaresPlayz** [comment]
I don’t really understand

**Comment by furry1212** [comment]
bru... check the code that you wote before the crash hapened, it is a simple bug hunting/glich finding skill

**Comment by NightmaresPlayz** [comment]
The ones I recently wrote were the charting and the week.JSON

**Comment by furry1212** [comment]
then check them and see it they mess with the chracters or reference another code file thing

**Comment by NightmaresPlayz** [comment]
Still don’t know

**Comment by NightmaresPlayz** [comment]
Im new to this so I need a dumbed down explanation

**Comment by NightmaresPlayz** [comment]
Plus I’m using 0.6.2

**Comment by furry1212** [comment]
just use lua if u want a dummed down ver of Psych

**Comment by furry1212** [comment]
>w<            >W<          Ow<

**Comment by NightmaresPlayz** [comment]
Actually, it only happens when I want to change the characters in charting

**Comment by NightmaresPlayz** [comment]
Only gf and opponent

**Comment by DisIsNOt** [comment]
You using source ?

**Comment by ACrazyTown** [comment]
Character.hx line 164 is `frames = Paths.getSparrowAtlas(json.image);`. Assuming you haven't changed anything in Character.hx, this would mean that the path to the character's image in your character's json file is invalid.

**Comment by ManMaster707** [comment]
> ----->w< ------ >W< ------ Ow<

![look-up-scared](https://user-images.githubusercontent.com/101059988/199327186-f1c3bdb4-bd38-4d57-ad58-9cdf29d9886c.gif)
