### ISSUE TITLE
HTML code Help

### ISSUE THREAD

**Issue by cooldude47980597** [ShadowMario/FNF-PsychEngine#11085]
### What is your question?

Here’s some code if you need it  
   var sourceHTML = document.getElementById("notes").innerHTML;
     
   var source = 'data:application/vnd.ms-word;charset=utf-8,' +    encodeURIComponent(sourceHTML);
   var fileDownload = document.createElement("a");
   document.body.appendChild(fileDownload);
   fileDownload.href = source;
 
   var lines = $('#notes').val().split('.');//gives all lines
    const firstLine=lines[0];
  console.log(firstLine)
   fileDownload.download = firstLine + ".doc";
   fileDownload.click();
   document.body.removeChild(fileDownload);
}

**Comment by CrusherNotDrip** [comment]
> ### What is your question?
> Here’s some code if you need it

this isn't what issues are for

**Comment by MemeHoovy** [comment]
Exactly

**Comment by cooldude47980597** [comment]
> Exactly

Woah your a contributor?

**Comment by cooldude47980597** [comment]
Wait you need talk I can’t close it

**Comment by MemeHoovy** [comment]
I can’t close it either
