### ISSUE TITLE
Song crashes with dadbattle spotlight

### ISSUE THREAD

**Issue by fenneey** [ShadowMario/FNF-PsychEngine#11098]
### Describe your bug here.

I used the dadbattle spotlight inside of guns in week 7 and whenever I load up the song it crashes.
![image](https://user-images.githubusercontent.com/117320391/199614929-d5c640c6-6ff8-4b32-9036-316f6fc678a7.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Not a bug

**Comment by KingMB-XJ** [comment]
Dadbattle Spotlight only works with the week 1 stage, same with how Philly Glow only works in the week 3 stage. You could remake the event to work on all stages, but it won't work otherwise.

**Comment by BeepSheep254** [comment]
> Dadbattle Spotlight only works with the week 1 stage, same with how Philly Glow only works in the week 3 stage. You could remake the event to work on all stages, but it won't work otherwise.

yea, too bad no one made a dadbattle spotlight recreation event on lua

**Comment by Parsellol** [comment]
its purposely hardcoded into week 1

**Comment by Gostar64** [comment]
> > Dadbattle Spotlight only works with the week 1 stage, same with how Philly Glow only works in the week 3 stage. You could remake the event to work on all stages, but it won't work otherwise.
> 
> yea, too bad no one made a dadbattle spotlight recreation event on lua yet

https://gamebanana.com/tools/11052

**Comment by BeepSheep254** [comment]
> > > Dadbattle Spotlight only works with the week 1 stage, same with how Philly Glow only works in the week 3 stage. You could remake the event to work on all stages, but it won't work otherwise.
> > 
> > 
> > yea, too bad no one made a dadbattle spotlight recreation event on lua yet
> 
> https://gamebanana.com/tools/11052

welp i spoke too soon

**Comment by TheKitBoi** [comment]
close this issue
