### ISSUE TITLE
Default Week Editing?

### ISSUE THREAD

**Issue by GamingInfinite** [ShadowMario/FNF-PsychEngine#11090]
### What feature do you want to get added on the **base** engine?

I tried to modify the base weeks (in an attempt to result in something like the b-sides mod by rozebud) basically to add a new difficulty through the modding API, but I found that it defaults to the one that is in the default folder, and not the one in the mod, even when I just want to add my own diff to existing songs.

For example: Trying to add B-Side diff to week 4.  All charts are added correctly under the songs (like next to milf and whatnot).  Music files are loaded correctly.  But upon trying to get it to add onto the existing week, I have to edit the file that is included in the download, and can't edit it via a file added via mod.  The reason this is important is because in trying to port or create my own mods I want to be able to do stuff like this or even add multiple different versions of the tutorial (if a different one is included) and be able to distribute it in such a way that its plug and play, and people don't have to go into the main files to modify it.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Lorekeeper49** [comment]
You can do this already, just copy the week jsons from `assets/weeks` and place them into `mods/weeks` and edit from there

**Comment by GamingInfinite** [comment]
thats what im saying, that didn't work when I tried it (version 0.6.3)

**Comment by KingMB-XJ** [comment]
I've been having the same problem and posted it here, but I've yet to get a response to my most recent reply. Should I re-post it and try to get our issue solved faster or is that not allowed?
