### ISSUE TITLE
Using Source variables in Lua

### ISSUE THREAD

**Issue by Draconic-Hybrid** [ShadowMario/FNF-PsychEngine#11091]
### What is your question?

Is there a way to use for Source variables in Lua? I think there's a variable that checks for the total misses when playing a week in Story Mode. 

If there is a way, could you tell me how?

**Comment by EyeDaleHim** [comment]
`getPropertyFromClass`, The [API](https://github.com/ShadowMario/FNF-PsychEngine/wiki) exists for a reason!

**Comment by Draconic-Hybrid** [comment]
Wait, I just realized campaignMisses IS in PlayState, dammit

Sorry for wasting your time
