### ISSUE TITLE
counter on how notes you hit

### ISSUE THREAD

**Issue by lime360** [ShadowMario/FNF-PsychEngine#11094]
### Describe your problem here.

so i have a question: how do i make counter on total notes hit using source code that will be places between score and miss counters

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i edited PlayState.hx so i can change accuracy texts and CoolUtil.hx to replace hard and easy difficulty with beginner difficulty

**Comment by Parsellol** [comment]
between ``scoreTxt.text = 'Score: ' + songScore`` and ``+ ' | Misses: ' + songMisses`` add ``+ ' | Total Note Hits: ' + songHits``

**Comment by lime360** [comment]
thank you
