### ISSUE TITLE
bug with charting sustains

### ISSUE THREAD

**Issue by CaptainBaldi** [ShadowMario/FNF-PsychEngine#11109]
### Describe your bug here.

im using 0.6.3 btw
been charting a bit lately and ive noticed that after saving a song with 1 step sustains and then exiting/restarting the song, the sustains don't actually show in game
in the chart editor they appear fine, in game they just aren't there
I've tried 2 songs, one with 110 bpm and another with 150.5 (if that helps at all) and this has happened.
the 1 step sustain length for the second song im charting is 100, however in the json it for some reason drops down to 99.ashittonofnumbers, and since psych engine doesn't render sustains less then 1 step(another problem with charting), they don't show
For the first song I've been able to edit it through the JSON to get it working, but with the second I literally can't do that so I'm kinda stuck here.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i did the funny chart editing

**Comment by DabbinDude316B** [comment]
The texture spawns behind the note, so making a sustain not short it’s there, and not a bug

**Comment by CaptainBaldi** [comment]
> The texture spawns behind the note, so making a sustain not short it’s there, and not a bug

making a 1 step sustain works unless you reload the chart after saving, if you save it reverts the sustain in the json to slighly less then one step making it so it isn't there

**Comment by DabbinDude316B** [comment]
Have you missed my answer

**Comment by DabbinDude316B** [comment]
> > The texture spawns behind the note, so making a sustain not short it’s there, and not a bug
> 
> making a 1 step sustain works unless you reload the chart after saving, if you save it reverts the sustain in the json to slighly less then one step making it so it isn't there

_Then don’t reload it_

**Comment by CaptainBaldi** [comment]
> > > The texture spawns behind the note, so making a sustain not short it’s there, and not a bug
> > 
> > 
> > making a 1 step sustain works unless you reload the chart after saving, if you save it reverts the sustain in the json to slighly less then one step making it so it isn't there
> 
> _Then don’t reload it_

how can i not reload it if starting the song reloads the json
