### ISSUE TITLE
Silly question 

### ISSUE THREAD

**Issue by Gabo137** [ShadowMario/FNF-PsychEngine#11102]
### What is your question?

Is it possible to make an object shop in source code instead of lua? and not in freeplay?

**Comment by MemeHoovy** [comment]
yeah https://github.com/PopcornColonell/hypnosource

**Comment by Gabo137** [comment]
WOW, THANKS. I'M GOING TO TRY IT RIGHT NOW!!!

**Comment by TheKitBoi** [comment]
Close this

**Comment by Gabo137** [comment]
Ok
