### ISSUE TITLE
someone explain this

### ISSUE THREAD

**Issue by EnderBoi201** [ShadowMario/FNF-PsychEngine#11104]
### Describe your bug here.

FreeplayState.hx (line 154)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i edited MainMenuState.hx, and Discord.hx

**Comment by TheKitBoi** [comment]
![image](https://user-images.githubusercontent.com/84044666/199783168-6569595e-f83f-4c1c-b0f8-06f7e4f04dbb.png)

you may have a faulty week.json that attempts to read

![image](https://user-images.githubusercontent.com/84044666/199783605-3188c983-5d8c-43d3-a07f-15cc06555aac.png)

**Comment by EnderBoi201** [comment]
thanks it works now

**Comment by Parsellol** [comment]
u can close the issue now
