### ISSUE TITLE
Video death

### ISSUE THREAD

**Issue by RubenDatOneBoi3446** [ShadowMario/FNF-PsychEngine#11101]
### Describe your problem here.

Is there a way to make a mp4 video death screen?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheKitBoi** [comment]
function onGameOver()
startVideo('urvid')
end

**Comment by RubenDatOneBoi3446** [comment]
thank u very much i shall go die now
