### ISSUE TITLE
Can you use "wait()" in Lua?

### ISSUE THREAD

**Issue by AnomaleZ** [ShadowMario/FNF-PsychEngine#11103]
### Describe your problem here.

So I'm coding, right? I have this idea where... if you get below 90% accuracy you have ten seconds to recover from it before you die. Something similar to Insomnia's mechanic.
The problem? I don't know if I'm using "wait()" wrong, or if that's invalid.
Worst part, I don't even know if that's the wrong way to execute my idea, the wait command is not working so I am unable to give a test and see if it does work.
Is it because later versions of Psych Engine don't have the wait command, or does it just not exist as a command in Lua at all?

(Mind you, I'm still new to Lua coding (and coding in general) so please give me feedback over how to make this code work (refer to attachment) because this is extremely faulty)
![worst code to ever exist](https://user-images.githubusercontent.com/83148927/199647282-822c1b59-f4ef-442f-99de-3d151e36977f.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
It's not a function, use a timer
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers

**Comment by AnomaleZ** [comment]
I feel awfully stupid, if I remember correctly this should work right?
I've never properly ran a timer before I've only checked Lua from other mods as reference

![wowcode1](https://user-images.githubusercontent.com/83148927/199650093-19d4683e-bcca-4c9d-9695-33782fa7c0b8.png)
![wowcode2](https://user-images.githubusercontent.com/83148927/199650096-63b66b6b-63c4-4e69-93cb-1ed230334ef5.png)

**Comment by AnomaleZ** [comment]
woops

**Comment by Grape-Boy** [comment]
you could add a check so that you don't run the timer again if it hasn't been cancelled

**Comment by Draconic-Hybrid** [comment]
Is this in a `function onUpdate()`?

Like Grape-Boy said, you could add a check. The best my brain can come up with is something like this:
```lua
local danger = false;

function onUpdate()
    if rating < 0.9 and not danger then
        danger = true
        setProperty('defaultCamZoom', 1.4)
        runTimer('die', 10)
    elseif rating >= 0.9 and danger then
        danger = false
        cancelTimer('die')
        setProperty('defaultCamZoom', 1.2)
    end
end
```

Your `onTimerCompleted()` is fine, by the way

**Comment by AnomaleZ** [comment]
Sorry for the late reply, but this works tysm🙏

**Comment by AnomaleZ** [comment]
Okay it SORT OF works
