### ISSUE TITLE
constant scroll speed gets multiplied by playback speed

### ISSUE THREAD

**Issue by Brandon32204** [ShadowMario/FNF-PsychEngine#11112]
### Describe your bug here.

the constant scroll speed option gets multiplied by the playback speed

kinda annoying since i always play with 3 scroll speed but then i make the songs faster and suddenly the notes move way faster than they prob should, unless this is intended

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by uiojaafdosijfafdssf** [comment]
i found a way to fix it. replace all `ClientPrefs.getGameplaySetting('scrollspeed', 1)` with `ClientPrefs.getGameplaySetting('scrollspeed', 1) / playbackRate)` in PlayState.hx. if u use multiplicative, then dont replace it on line 2417 (or the line right below where it says `case "multiplicative":` if more lines got added in PlayState.hx).

and if u want it to not change the safe frames, then comment out or remove `Conductor.safeZoneOffset = (ClientPrefs.safeFrames / 60) * 1000 * value;`
