### ISSUE TITLE
Can you make events work no matter the stage?

### ISSUE THREAD

**Issue by Brandon32204** [ShadowMario/FNF-PsychEngine#11111]
### What is your question?

for example i wanted to put the dad battle spotlight on guns,
turns out that it crashes if its on anything but the week 1 stage

ive heard philly glow will do the same thing

**Comment by tposejank** [comment]
Shadow Mario won't

**Comment by Parsellol** [comment]
u cant unless u find or create a lua recreation

**Comment by Gostar64** [comment]
Here's Dadbattle Spotlight: https://gamebanana.com/tools/11052
and Here's Philly Glow: https://gamebanana.com/mods/402235
