### ISSUE TITLE
Health Icon ordering/layering

### ISSUE THREAD

**Issue by Troystar23** [ShadowMario/FNF-PsychEngine#11115]
### What is your question?

So I have went and made two sprites using Lua which are practically boyfriend and dads separate health bars. What im finding a challenge to figure out is how do relayer/order the icons so that they are above the new healthbars i created  (they are attached to the hud using "setObjectCamera"). To clarify i would like to have my healthbars below the icons when as of right now they are not. If you know how i could get around this let me know that would be great thanks. 

Dosent have to be lua i can source code too but found using Lua was just quick for me to do at the time. Either or works :)

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#object-orderremoving

**Comment by Troystar23** [comment]
Cheers!
