### ISSUE TITLE
Error: source/FunkinLua.hx:82: characters 5-10 : Expected }

### ISSUE THREAD

**Issue by plasticocelot123** [ShadowMario/FNF-PsychEngine#11110]
### Describe your problem here.

What does this error on the title mean? And, how do I fix it? I am modding a Friday Night Funkin: Psych Engine 0.6.3 build.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited MainMenuState.hx to remove some parts of the main menu like the donate button.

**Comment by TheKitBoi** [comment]
send the line or the whole file to fix ur easy to make a mistake

**Comment by plasticocelot123** [comment]
Where do I send the file and which file to send, MainMenuState or FunkinLua.hx

**Comment by TheKitBoi** [comment]
FunkinLua.hx
rename .hx to txt

**Comment by plasticocelot123** [comment]
Here's the file and also a screenshot of the error...
[FunkinLua.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9934546/FunkinLua.txt)
![error](https://user-images.githubusercontent.com/113000222/199872844-b1e36c6b-584a-4110-9fac-895e7c48f45a.PNG)

**Comment by TheKitBoi** [comment]
[FunkinLua.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9934566/FunkinLua.txt)
fixed it for ya
rename .txt to .hx

**Comment by plasticocelot123** [comment]
thx for help

**Comment by plasticocelot123** [comment]
Compiling gives new error:
![error](https://user-images.githubusercontent.com/113000222/199874054-299f11b3-82eb-4b26-98f9-0ad5fcc42c08.PNG)

**Comment by TheKitBoi** [comment]
[FunkinLua.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9934591/FunkinLua.txt)

**Comment by plasticocelot123** [comment]
![error](https://user-images.githubusercontent.com/113000222/199874682-4fe865a1-6065-4a83-8442-59f4bb21b2d8.PNG)

**Comment by TheKitBoi** [comment]
[FunkinLua.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9934610/FunkinLua.txt)

**Comment by plasticocelot123** [comment]
![error](https://user-images.githubusercontent.com/113000222/199875148-cb9bd3c6-64ce-4395-9cea-a79be48d4a98.PNG)

**Comment by TheKitBoi** [comment]
[FunkinLua.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9934654/FunkinLua.txt)

**Comment by plasticocelot123** [comment]
![error](https://user-images.githubusercontent.com/113000222/199876057-4bd8e82d-e6b6-4247-a6f9-4c973502310e.PNG)

**Comment by TheKitBoi** [comment]
[FunkinLua.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9934681/FunkinLua.txt)

**Comment by MemeHoovy** [comment]
are you renaming them to hx?

**Comment by plasticocelot123** [comment]
yes

**Comment by MemeHoovy** [comment]
well you have to replace the file of course

**Comment by plasticocelot123** [comment]
i did

**Comment by plasticocelot123** [comment]
![error](https://user-images.githubusercontent.com/113000222/199876445-f78e0946-c453-4764-aab0-d292e8b781d9.PNG)
Could not fit all errors on screenshot.

**Comment by MemeHoovy** [comment]
did you do this `haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit`

**Comment by plasticocelot123** [comment]
yes, same error
