### ISSUE TITLE
i know this is a dumb question, but...

### ISSUE THREAD

**Issue by lime360** [ShadowMario/FNF-PsychEngine#11117]
### Describe your problem here.

how to i set variables in lua (from the script, not flxstate)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by bruh1cat** [comment]
Variable = 69

**Comment by lime360** [comment]
"Psych didn't invent Lua, use Google" i know
