### ISSUE TITLE
Multiple freeplay menus (story, freeplay, etc)

### ISSUE THREAD

**Issue by nikkalotz** [ShadowMario/FNF-PsychEngine#11127]
### What is your question?

Trying to make custom freeplay menus where there would be a menu with selectable options like they were songs, but selecting them brings you to another menu with just those songs. idk how else to describe it, i think indie cross did something similar

any help is appreciated, but im mainly just looking for how you would make it so only certain week .jsons show up in certain menus; would you have to hardcode it in like how it used to work in FNF or would it be only displaying weeks with a specific name (i.e. week1 goes in story songs but week2 goes into freeplay, etc)

**Comment by MemeHoovy** [comment]
https://github.com/brightfyregit/Indie-Cross-Public

**Comment by nikkalotz** [comment]
sick i didnt even know indie cross src code went public
