### ISSUE TITLE
Error when doing lime test windows

### ISSUE THREAD

**Issue by GenaroYT** [ShadowMario/FNF-PsychEngine#1112]
### Describe your bug here.

Idk why does this appear but can someone pls give a solution? I already have Visual Studio 2017, 2019, and Visual Code

### Command Prompt/Terminal logs (if existing)

```bash
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/ -IC:/HaxeToolki
t/haxe/lib/linc_luajit/0,0,4//linc/ -I C:/Users/Genaro/Documents/FNF-PsychEngine
-main/source/vlc/cpp/include/ -I C:/Users/Genaro/Documents/FNF-PsychEngine-main/
source/vlc/cpp/src/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi
(debug) -FdC:\Users\Genaro\Documents\FNF-PsychEngine-main\export\release\windows
\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -Oy-
-c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_V
ISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SE
CURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMAT
CH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/openfl/display/_internal/Context3DElementType.cpp
Error: Context3DElementType.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.1
6.27023\include\crtdefs.h(10): fatal error C1083: Cannot open include file: '_mi
ngw.h': No such file or directory
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't edit anything

**Comment by Micasddsa** [comment]
This happened to me before. You most likely didn't install everything required for compiling. because I believe that it's looking for header files that it can't find, try checking the old fnf installation guide (requires 22gbs but is more reliable) or double check that you have everything installed.
