### ISSUE TITLE
Chart Editor in Main Menu does not bring you to "Charting Mode"

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#11120]
### Describe your bug here.

When using the Chart Editor that is in the Main Menu, and you then hit enter, to play the song, you don't enter the charting mode. it only appears after then press 7 again, and pressing enter.

the song I used, is directly stored into mods/songs and mods/data if that is important

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Blik10** [comment]
Can confirm. It doesn't seem to be specific to anything, it just works this way.
