### ISSUE TITLE
Black Squares and Dying 

### ISSUE THREAD

**Issue by Groovemate** [ShadowMario/FNF-PsychEngine#11132]
### I have some errors.

Boyfriend and GF has black squares. NOT only them, but some of the others.
Likely, mods, bgs, etc.

While playing a mod, i died then the game crashed.
Here it is.
![Psych Engine Error](https://user-images.githubusercontent.com/108041604/200112697-6cbe519e-8a3b-456a-acda-c138ab68ab4f.png)

Black Squares

![mod glicj](https://user-images.githubusercontent.com/108041604/200112736-d5c8d08e-63a8-4e50-8336-f2044bf0e54d.png)

### Command Prompt/Terminal logs (if existing)

GameOverSubstate.hx (line 106)
flixel/FlxState.hx (line 203)
flixel/FlxState.hx (line 212)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, the mod was made by CherryCY.

**Comment by KillerAvecRage** [comment]
Invalid death animation

And I got black squares once and it was a PC performance issue

**Comment by Groovemate** [comment]
updated to windows 11, no more black squares but i still get error when i die

**Comment by frantastic24** [comment]
You can look up the error
#9388

**Comment by Groovemate** [comment]
de-updated because of audio (Windows 10)
black squares came back
and i discovered, to remove the black squares and lag
im supposed to update my opengl to 3.3/3.1/3.1.0 (mine is 2.1/2.1.0)
so how to update opengl

**Comment by frantastic24** [comment]
Update your graphics drivers

**Comment by Groovemate** [comment]
idk how

**Comment by KillerAvecRage** [comment]
You can download current drivers from the  manufacturer websites:

    nVidia - http://www.nvidia.com/content/drivers/drivers.asp
    ATI - http://www.ati.com/support/driver.html
    Matrox - http://www.matrox.com/mga/support/drivers/home.cfm
    PowerVR - http://www.powervr.com/Downloads.asp
    Intel - http://support.intel.com/support/graphics
    3dfx - http://www.voodoofiles.com/3dfxhelp.asp

(Even though this is from a README from an old game, it still can help)

**Comment by Groovemate** [comment]
oh no
it turns out, my gpu is Intel GMA 4500
and Intel GMA 4500 does not support opengl  3.3/3.1/3.1.0.
so im kinda in a pickle right now

**Comment by Groovemate** [comment]
oh no
it turns out, my gpu is Intel GMA 4500
and Intel GMA 4500 does not support opengl 3.3/3.1/3.1.0.
so im kinda in a pickle right now

**Comment by KillerAvecRage** [comment]
You need to upgrade your graphics card then

**Comment by Groovemate** [comment]
I DID IT.
I CHANGED MY PC.
THE PC WAS CORRUPTED.
I FIXED IT.
GPU IS Skylake(GT2).
UPDATED 1.1.0 OPENGL TO 4.4.0.
THANK YOU ALL.

**Comment by Groovemate** [comment]
I DID IT.
I CHANGED MY PC.
THE PC WAS CORRUPTED.
I FIXED IT.
GPU IS Skylake(GT2).
UPDATED 1.1.0 OPENGL TO 4.4.0.
THANK YOU ALL.
edit: i got the death message again :(

**Comment by frantastic24** [comment]
This was answered months ago

**Comment by Groovemate** [comment]
turns out
it's the only corrupted mod
so it's normal (i think)
i'll close this for now
