### ISSUE TITLE
Game crash when I change the X position axis of the time text

### ISSUE THREAD

**Issue by RBeansDev** [ShadowMario/FNF-PsychEngine#11131]
### Describe your problem here.

So, I tried changing the position of the time text cuz it didn't sync with the time bar stuff I modified. After I went to a song it threw null object reference and crashed the game. Anyone came up with ideas how to fix this issue?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

PlayState.hx, everything on the time bar

**Comment by InsiderIV** [comment]
hella late but try this

setProperty('timeTxt.x', getProperty('scoreTxt.x')+ number) --change number to whatever number you need

**Comment by EnragedBambiOfficialCodes** [comment]
> hella late but try this
> 
> setProperty('timeTxt.x', getProperty('scoreTxt.x')+ number) --change number to whatever number you need

I don't do it in lua I do it hardcoded
