### ISSUE TITLE
stuff just wont work (Building issue)

### ISSUE THREAD

**Issue by The6thelement** [ShadowMario/FNF-PsychEngine#11130]
### Describe your bug here.

i have everything in the read me installed including all of the base funkin stuff.

### Command Prompt/Terminal logs (if existing)

```bash
Windows

C:\a - Copy>lime build windows
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead


For HTML5 i get this error

C:\a - Copy>lime build html5
source/FunkinLua.hx:3104: characters 23-28 : Type not found : State
source/CoolUtil.hx:18: lines 18-141 : ... Defined in this class
source/PlayState.hx:3760: characters 40-68 : Class<FunkinLua> has no field getPropertyLoopThingWhatever
source/PlayState.hx:4903: characters 8-12 : FunkinLua has no field call
source/PlayState.hx:4904: characters 8-12 : FunkinLua has no field stop
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Just the Name of the applaction in the project.xml file

**Comment by frantastic24** [comment]
there's no error in the windows log
pretty sure html5 was fixed, it works fine for me

**Comment by The6thelement** [comment]
so i now get this error
