### ISSUE TITLE
Please help, read below.

### ISSUE THREAD

**Issue by N1CKN0TAD3** [ShadowMario/FNF-PsychEngine#11136]
### Describe your problem here.

So, I'm thinking to add the game jolt login thing from indie cross when you get to the menu, and I need help with that. I want that game jolt thing because I want to link my achievements from my game onto a game jolt account so when you get an achievement in game, you get one on your account too.

Thanks.

N1CKN0TAD3

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by MemeHoovy** [comment]
https://github.com/brightfyregit/Indie-Cross-Public
