### ISSUE TITLE
weird glitchy text

### ISSUE THREAD

**Issue by WhiteKapi** [ShadowMario/FNF-PsychEngine#11145]
### Describe your bug here.

I don't know why, but certain songs have their names glitched. It mostly happens to the songs that have colored names, but I've seen some songs that have the default white color glitched too. I don't even know how they are colored or how to change the color. This happens in 6.3, in 6.2 they look fine. I've also noticed that a song with dots in it crashes in 6.3 but works fine if I remove the dots.

6.3: 
![Screenshot (319)](https://user-images.githubusercontent.com/97306028/200148788-b1796596-7a93-48c9-b0c2-c7cea0373eba.png)
6.2: 
![Screenshot (320)](https://user-images.githubusercontent.com/97306028/200148792-41def841-f32f-41cc-8efb-98bd28cd7eb6.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't

**Comment by CrusherNotDrip** [comment]
alphabet stuff changed in 0.6.3 related to xml and a whole lot more

**Comment by WhiteKapi** [comment]
> alphabet stuff changed in 0.6.3 related to xml and a whole lot more

what do I need to do to fix this?

**Comment by WhiteKapi** [comment]
ok I found out, I just needed to delete the alphabet png and xml from the mod's folder, however it's still weird that you can have dots in the song's name in 6.2 but not in 6.3.
