### ISSUE TITLE
A Bug, yeah im dumb

### ISSUE THREAD

**Issue by GlamesDem0tivated** [ShadowMario/FNF-PsychEngine#11148]
### Describe your bug here.

So I grabbed Fatality from Vs Sonic.exe's Json file for a cover, If I go into the chart editor, it does indeed load up, but crashes at the 14 second mark. It doesn't even open in the Freeplay menu.

![Screenshot 2022-11-05 214146](https://user-images.githubusercontent.com/109561022/200151117-1719a383-b024-4b47-9615-72134a4145b4.png)

This is the Error from the charting menu

![Screenshot 2022-11-05 214146 (2)](https://user-images.githubusercontent.com/109561022/200151322-d33efad1-cf1b-4972-b752-86dcfeb04be2.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, I mostly don't know how to code. I don't have the source code for the engine.

**Comment by CaptainBaldi** [comment]
broken json
