### ISSUE TITLE
Crash after adding dadbattle lights / philly glow?

### ISSUE THREAD

**Issue by IceboundCat6** [ShadowMario/FNF-PsychEngine#11149]
### Describe your problem here.

idk how this stuff works or why this is bugged, but I don't wanna lose 2 hours of my life charting because of this. I can't load the chart from debug, same error. Anyone more experienced know a way to fix this from the .json itself?

Google Drive link to chart: https://drive.google.com/file/d/17BSJRledwFeG42cPwYRgQ5a0mwv_FdKe/view?usp=sharing

![image_2022-11-06_013412973](https://user-images.githubusercontent.com/73092638/200155857-09157716-be14-4c87-8c43-52a5ce6cd2da.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHoovy** [comment]
dadbattle spotlight only works on week1, & philly glow only works on week 3, get this through your dumb brain

**Comment by IceboundCat6** [comment]
> dadbattle spotlight only works on week1, & philly glow only works on week 3, get this through your dumb brain

1. Makes sense
2. Was charting using week 3 as a base
3. Doesn't solve my problem

**Comment by MemeHoovy** [comment]
well that's just how it works

**Comment by IceboundCat6** [comment]
Listen if you can't help me stop responding. Calling me dumb doesn't fix anything.

**Comment by MemeHoovy** [comment]
that's your fix, just don't use them on other weeks, other then the appropriate weeks

**Comment by IceboundCat6** [comment]
So your fix is to not use them in the first place?
Too late buddy. I'm so stupid that I already did! That's why I'm asking for help! Too bad you're the only one here. I'll wait until tomorrow to see if anyone has anything helpful to say :)

**Comment by MemeHoovy** [comment]
**you can't use dadbattle spotlight on any other week then week1, & philly glow can only be used on week3**, that's how it fucking works

**Comment by frantastic24** [comment]
The error you posted is missing chart

**Comment by IceboundCat6** [comment]
> The error you posted is missing chart

Added a drive link

**Comment by frantastic24** [comment]
the song is called pico, not pico-hard
![imagen](https://user-images.githubusercontent.com/95725102/200156607-b2d65cf3-59aa-4964-904f-e52c5494b520.png)

**Comment by IceboundCat6** [comment]
> the song is called pico, not pico-hard ![imagen](https://user-images.githubusercontent.com/95725102/200156607-b2d65cf3-59aa-4964-904f-e52c5494b520.png)

Ah, I was choosing normal diff. in freeplay when I went to change the song via debug, wasn't aware that you don't put the -hard at the end in that case.
Thanks for the _helpful_ reply!
