### ISSUE TITLE
custom note thing

### ISSUE THREAD

**Issue by lime360** [ShadowMario/FNF-PsychEngine#11142]
### Describe your problem here.

basically i ported shape notes from vs dave 3.0 into lua, but there is one problem...

how do i make them able to hit during the time that player holds space (just to make it closely to the original)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by CaptainBaldi** [comment]
if ur not pressing space set the blockHit var to true if you are then set it to false
simple keyboardJustPressed and setPropertyFromGroup shit

**Comment by lime360** [comment]
ok thx

**Comment by lime360** [comment]
i tried to add some code, but it shows me the error if i load a song with specific notes in a chart

***the error:***
![image](https://user-images.githubusercontent.com/56405352/200162203-92fc695f-8237-456d-b50b-0ff959f9f216.png)

***code itself:***
```
function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is an Instakill Note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Shape Notes' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'NOTE_assets_Shape'); --Change texture

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', false); --Miss has no penalties
			end
		end
	end
	--debugPrint('Script started!')
end

local blockHit = true;

if keyPressed("space") then
    setPropertyFromGroup("local", 0, "blockHit", false);
	else
	setPropertyFromGroup("local", 0, "blockHit", true);
end

if blockHit then
	setPropertyFromGroup('unspawnNotes', i, 'hitCausesMiss', true);
else
	setPropertyFromGroup('unspawnNotes', i, 'hitCausesMiss', false);
end
```

**Comment by Daikicalla** [comment]
The value you called the keyPressed doesn't exist.

On line 18, say "if keyPressed("SPACE") then". Should fix your problem.

If you keep running into errors like these, take a look at the HaxeFlixel documentation for FlxKeyList [here.](https://api.haxeflixel.com/flixel/input/keyboard/FlxKeyList.html)

**Comment by lime360** [comment]
i tried and it still gave me an annoying error

***code:***

```
function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is an Instakill Note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Shape Notes' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'NOTE_assets_Shape'); --Change texture

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', false); --Miss has no penalties
			end
		end
	end
	--debugPrint('Script started!')
end

local blockHit = true;

if keyPressed("SPACE:true") then
    blockHit = false;
end

if keyReleased("SPACE:true") then
    blockHit = true;
end

if blockHit then
	setPropertyFromGroup('unspawnNotes', i, 'hitCausesMiss', true);
else
	setPropertyFromGroup('unspawnNotes', i, 'hitCausesMiss', false);
end
```
i changed it a bit, looks incorrect bc this is my first time using flxinput stuff

**Comment by Draconic-Hybrid** [comment]
Pretty sure it should be `if keyPressed("SPACE") == true` instead of `if keyPressed("SPACE:true").` Same applies to keyReleased.
