### ISSUE TITLE
is there a way to play a video underneath the ui?

### ISSUE THREAD

**Issue by Anzion10** [ShadowMario/FNF-PsychEngine#11141]
### Describe your problem here.

basically, i want to make a song that instead of using sprites, a bg and stuff, uses just a .mp4 video for graphics, with the ui on top of the video.
Like this: (mockup in krita)

![weird](https://user-images.githubusercontent.com/117538567/200135729-1e486a25-b79b-4f45-94b9-cbad28d7fdba.PNG)

(yeah its an smg4 mod)
Is there any way to do this? source code or lua based, any way is appreciated

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I'm using psych engine Extra keys by tposejank

**Comment by UmbratheUmbreon** [comment]
Videos are added a childs so they are always above the game regardless

**Comment by TheKitBoi** [comment]
You must use Psych Engine 6.2 or Up
idk what your thinking about when your using PE extra keys mod

[videoSprite.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9944690/videoSprite.txt)
1.put this file in your mods your making folder
2.find the line (var filepath = Paths.video('yourvideo');)
3.edit yourvideo to the video name your using
4.put this file into scripts ( [videosprite.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9944692/videosprite.txt) )

**Comment by Anzion10** [comment]
do i need to change the extension to lua?

**Comment by TheKitBoi** [comment]
yes

**Comment by Sonk998** [comment]
Is there a way to make the video appear at a certain curStep?

**Comment by s-h-i-f-t-y-z** [comment]
> Is there a way to make the video appear at a certain curStep?

`function onUpdatePost(elapsed)
    if curStep == int then
        playVideo('video')
    end
end`

i think its that youll have to double check with others bc i just started coding

yes ik this is old but i js had to

**Comment by EEssential** [comment]
how exactly does the curStep part work?

**Comment by PleaseEnterUsernameHere** [comment]
it plays at a specific step of a song

![image](https://github.com/user-attachments/assets/ccbd1628-832f-4e31-8ed4-cfef6db14e8f)

if i want it to play at step 100, then you would put:
`function onUpdatePost(elapsed) if curStep == 100 then playVideo('video') end end`
