### ISSUE TITLE
Can't add noteskin

### ISSUE THREAD

**Issue by BoltDT** [ShadowMario/FNF-PsychEngine#11144]
### Describe your problem here.

I am trying to add in a custom noteskin, but despite following the directions to a tee, I can't get it to load in-game. I am working on 0.5.2, bc that's the only version that will let me edit characters, so if you know a fix, please hit me up 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

Added 1 .png file and 1 .xml file

**Comment by frantastic24** [comment]
Hard to tell without any of the files or an actual description of what's happening

**Comment by BoltDT** [comment]
When I type the name of the skin in and add the notes, the notes are invisible. If I try to go in-game, an error message pops up.

**Comment by frantastic24** [comment]
That's still barely any info
The point of the error is to post it, it's useless to just mention it

**Comment by BoltDT** [comment]
Here's the text file for the error
[crash_2022-11-05_17'58'50.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9944929/crash_2022-11-05_17.58.50.txt)

**Comment by frantastic24** [comment]
seems like a duplicate of #9507
