### ISSUE TITLE
Center Window

### ISSUE THREAD

**Issue by thedumbestcat** [ShadowMario/FNF-PsychEngine#11156]
### Describe your problem here.

Hi, does anyone know how i can center the window on the screen ? I made a script that moves the window, but i don't know how i can center it at the end of the song.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Grape-Boy** [comment]
[I think this could help](https://api.openfl.org/openfl/system/Capabilities.html#screenResolutionX)

**Comment by UncertainProd** [comment]
You could get the full screen dimensions using
```lua
local fullscreenwidth = getPropertyFromClass('flixel.FlxG', 'stage.fullScreenWidth')
local fullscreenheight = getPropertyFromClass('flixel.FlxG', 'stage.fullScreenHeight')
```
and then use your window movement script to move the window to these x and y values:
```lua
x = (fullscreenwidth/2) - (screenWidth/2)
y = (fullscreenheight/2) - (screenHeight/2)
```
