### ISSUE TITLE
Issue importing character .png/.xml

### ISSUE THREAD

**Issue by starminn** [ShadowMario/FNF-PsychEngine#11151]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/117562793/200159038-422d81bb-bb7a-43bc-88bd-86b477b1e837.png)
this error appears when i click "Reload Image" after typing in the file name for a custom character sprite.

i personally suspect that it's to do with the way .xml files are exported (i use flash CS6 for sprites)
i think this has something to do with it because the .xml files i export look different than ones from sprites other people have made
my .xml:
![image](https://user-images.githubusercontent.com/117562793/200159221-4c114fbd-b417-4d0b-9d51-db294298c7a8.png)
whitty .xml for comparison:
![image](https://user-images.githubusercontent.com/117562793/200159264-1d86076b-aa5a-49c8-b6e1-021620ddfcdc.png)
other than that i really don't know what's happening, even less how to fix it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no, in fact i just downloaded this instance of psych

**Comment by frantastic24** [comment]
Change encoding to utf-8 when exporting

**Comment by starminn** [comment]
> Change encoding to utf-8 when exporting

how would i go about this? when exporting a sprite there's no option related to the encoding for the .xml
![image](https://user-images.githubusercontent.com/117562793/200160516-9d216aec-9d44-430f-98d7-249847566aea.png)

**Comment by Daikicalla** [comment]
> > Change encoding to utf-8 when exporting
> 
> how would i go about this? when exporting a sprite there's no option related to the encoding for the .xml ![image](https://user-images.githubusercontent.com/117562793/200160516-9d216aec-9d44-430f-98d7-249847566aea.png)

This is an issue outside of Psych Engine. I've done some simple online searches and a little research but couldn't find anything to change its encoding. I suggest using a different app, research about changing the encoding or finding a converter that can change UTF-16 to UTF-8. I can't find any more better suggestions for you.

**Comment by starminn** [comment]
> This is an issue outside of Psych Engine. I've done some simple online searches and a little research but couldn't find anything to change its encoding. I suggest using a different app, research about changing the encoding or finding a converter that can change UTF-16 to UTF-8. I can't find any more better suggestions for you.

this actually helps a bit, thank you. I did a quick search this morning for a tool to convert the encoding to utf-8 and think I found a valuable resource, so your response definitely tells me I'm on the right track, thank you so so much. I'll let you know if I find a solution!
