### ISSUE TITLE
Game crashes by pressing enter in the logo bump menu

### ISSUE THREAD

**Issue by Sword352** [ShadowMario/FNF-PsychEngine#11159]
### Describe your bug here.

Hi! i deleted the main fnf files (week2 etc) so it add more space to the game's workspace. But the game crashes with that message from the crash handler.

### Command Prompt/Terminal logs (if existing)

```bash
Paths.hx (line 356)
MainMenuState.hx (line 88)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited MainMenuState.hx to add an image on the menu and thats it.

**Comment by CaptainBaldi** [comment]
probably invalid image file

**Comment by frantastic24** [comment]
Not a bug
Look at your source, MainMenuState had an object with missing textures

**Comment by Sword352** [comment]
Thanks, it was an invalid image. But the path of the image is correct! Weird...

**Comment by Gostar64** [comment]
> Thanks, it was an invalid image. But the path of the image is correct! Weird... Heres a screenshot just in case ![image_2022-11-07_132048119](https://user-images.githubusercontent.com/99792114/200308985-4eb95d27-b1c0-4718-8cfb-9c3f0ec47624.png)

maybe get rid of the "Object:" in add(Object:baller)
