### ISSUE TITLE
Uhhh

### ISSUE THREAD

**Issue by BuildyArka** [ShadowMario/FNF-PsychEngine#11158]
### Describe your bug here.

ummmm....... how do i fix this

D:\Haxe\haxe\std/haxe/xml/Parser.hx (line 396)
D:\Haxe\haxe\std/haxe/xml/Parser.hx (line 285)
D:\Haxe\haxe\std/haxe/xml/Parser.hx (line 117)
D:\Haxe\haxe\std/Xml.hx (line 122)
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
MainMenuState.hx (line 111)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: haxe.xml.XmlParserException: Unclosed node <TextureAtlas> at line 5 char 0
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Edited Healthicon.hx And Playstate.hx To Add Win Icon,Edited Playstate.hx To Change The Menu Camera From Moving To Static

**Comment by CaptainBaldi** [comment]
probably broken xml

**Comment by BuildyArka** [comment]
what xml project.xml or parser.hx or something else i dunno how to fix this im a dumbass ok!

**Comment by TheKitBoi** [comment]
your character xml

**Comment by frantastic24** [comment]
One of your main menu objects has a broken XML, check the line the error mentions to find out which one
