### ISSUE TITLE
Source code to .exe

### ISSUE THREAD

**Issue by JavoniCraft** [ShadowMario/FNF-PsychEngine#11166]
### Describe your problem here.

I am using source code to make my mod. how do modders turn source code to .exe files and .dlls?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't edit anything.

**Comment by UmbratheUmbreon** [comment]
You need to install the prerequisites, then open command prompt and navigate to your source code's root folder. Then type **lime test windows** and it will compile into the export folder.

**Comment by ACrazyTown** [comment]
> You need to install the prerequisites, then open command prompt and navigate to your source code's root folder. Then type **lime test windows** and it will compile into the export folder.

^^ This except Javoni's build target is linux so it should be `lime test linux`. There's also additional flags such as `-debug` but those aren't neccessary.
If you're building a final build, it's recommended to use `lime build <target> -final`.
