### ISSUE TITLE
animation stuff

### ISSUE THREAD

**Issue by Gurudevsing** [ShadowMario/FNF-PsychEngine#11169]
### Describe your problem here.

![Screenshot (42)](https://user-images.githubusercontent.com/87480185/200220042-ebbf99c3-376d-4905-95c8-69de84b83de7.png)
how to animate  particular images 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#animations-functions

**Comment by Gurudevsing** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#animations-functions
![Screenshot (43)](https://user-images.githubusercontent.com/87480185/200469701-4140ee25-5017-482b-9f27-9e36d9311155.png)



it does't workkkk what to do

**Comment by frantastic24** [comment]
Can't help if you don't show your XML or explain what "doesn't work" means

**Comment by Gurudevsing** [comment]
> Can't help if you don't show your XML or explain what "doesn't work" means




BELOW VIDEO YOU CAN SEE ,CHARACTERS MOVING BUT THERE IS NOTHING WRONG WITH THAT I JUST WANT TO ANIMATE PARTICULAR IMAGE IN PNG LIKE,
                                              
HOW TO ANIMATE PARICULAR IMAGE  THAT I HAVE MARKED

hope you'll understand ...my english is shit THANKS
![Screenshot (42)](https://user-images.githubusercontent.com/87480185/200623010-5a49301c-1f37-467a-8064-25d4de841449.png)

THIS THE CODE I DID
![Screenshot (45)](https://user-images.githubusercontent.com/87480185/200622712-c4de01d2-79c2-4f32-9e97-6b39bfb7e161.png)

https://user-images.githubusercontent.com/87480185/200622537-3e046e35-a754-4683-b1fd-7735b25743f4.mp4

**Comment by Gurudevsing** [comment]
> > https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#animations-functions
> > ![Screenshot (43)](https://user-images.githubusercontent.com/87480185/200469701-4140ee25-5017-482b-9f27-9e36d9311155.png)
> 
> it does't workkkk what to do

![Screenshot (44)](https://user-images.githubusercontent.com/87480185/200626306-685e2ee4-5d49-4131-bf5e-
38826789a351.png)


THIS THE XML FILE OF THE ANIMATION

**Comment by Gostar64** [comment]
There are indices in the .xml file. From what I see, Ruv and Sarvente's indices should be 0004, 0005, 0006, 0007, 0008.  But you should show the xml file still and use addAnimationByIndices

**Comment by Gurudevsing** [comment]
HERE THE XML

THIS THE CODE I USED  addAnimationByIndices('crowdshit','walk','characters_walking',0004,0005,0006,0007 ,15,true)

it does't work everything blank
![Screenshot (44)](https://user-images.githubusercontent.com/87480185/200628075-6899a3f8-e558-4150-8689-af1339ec21ab.png)


> There are indices in the .xml file. From what I see, Ruv and Sarvente's indices should be 0004, 0005, 0006, 0007, 0008. But you should show the xml file still and use addAnimationByIndices

**Comment by Gostar64** [comment]
put the indices in a string like '0004, 0005, 0006, 0007, 0008' or '4,5,6,7,8', also do you have addLuaSprite(crowdshit)?

**Comment by Gurudevsing** [comment]
yes i added the sprite  but still everything blank
![Screenshot (46)](https://user-images.githubusercontent.com/87480185/200728705-ab9b5276-3f12-4af2-af02-629321cdce14.png)

**Comment by Gurudevsing** [comment]
> put the indices in a string like
> 
> ```lua
> '0004,0005,0006,0007,0008'
> ```
> 
> or
> 
> ```lua
> '4,5,6,7,8'
> ```
> 
> also do you have addLuaSprite(crowdshit)?

yes i added the sprite but still blank
![Screenshot (46)](https://user-images.githubusercontent.com/87480185/200729156-f981dde2-328b-46c5-9abd-636f7c488c91.png)

**Comment by Gurudevsing** [comment]
> put the indices in a string like
> 
> ```lua
> '0004,0005,0006,0007,0008'
> ```
> 
> or
> 
> ```lua
> '4,5,6,7,8'
> ```
> 
> also do you have addLuaSprite(crowdshit)?

Helo
