### ISSUE TITLE
double opponents

### ISSUE THREAD

**Issue by Gurudevsing** [ShadowMario/FNF-PsychEngine#11168]
### Describe your problem here.

https://user-images.githubusercontent.com/87480185/200218095-b3980de5-492d-4c1e-990a-0fe50aeeb3c6.mp4

![Screenshot (41)](https://user-images.githubusercontent.com/87480185/200218420-5906947f-9030-402d-b960-13559245d015.png)

second opponent is't moving

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Read the bottom of the screenshot, it only works with No Animation notes

**Comment by Gurudevsing** [comment]
> Read the bottom of the screenshot, it only works with No Animation notes

i did't notice tnx
