### ISSUE TITLE
Animation Priority is weird

### ISSUE THREAD

**Issue by Ace5542** [ShadowMario/FNF-PsychEngine#11160]
### Describe your problem here.

I'm trying to make an animation play while still playing notes and the priority on the play animation gets cancelled by not animation, can I play an animation that ignores note without using no animation notes or creating a new character altogether?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
You can't
You could make the character invisible and use a Lua sprite in their place instead

**Comment by Ace5542** [comment]
> You can't You could make the character invisible and use a Lua sprite in their place instead

Exactly what I didnt want to do lmao

**Comment by Ace5542** [comment]
I wanted it to work with all animations

**Comment by Ace5542** [comment]
also how do I know when the animation is over?

**Comment by Ace5542** [comment]
so I could switch them back?

**Comment by Ace5542** [comment]
could do a timer but I would like it to work with more than 1 animation for convenience

**Comment by frantastic24** [comment]
> I wanted it to work with all animations

It can if you're smart enough 


> also how do I know when the animation is over?

`getProperty('object.animation.curAnim.finished')` or use a timer

**Comment by Ace5542** [comment]
> > I wanted it to work with all animations
> 
> It can if you're smart enough
> 
> > also how do I know when the animation is over?
> 
> `getProperty('object.animation.curAnim.finished')` or use a timer

Alr thx, dont know how people find things like that

**Comment by Ace5542** [comment]
> 

if so I could just make the notes have no animation until the animation is over

**Comment by frantastic24** [comment]
Haxe has a wiki, is open source and these are even used in FNF
It's a matter of researching a few minutes

**Comment by Ace5542** [comment]
> Haxe has a wiki, is open source and these are even used in FNF It's a matter of researching a few minutes

good to know, thank you

**Comment by Ace5542** [comment]
> Haxe has a wiki, is open source and these are even used in FNF It's a matter of researching a few minutes

hey, one last thing I've been looking around for a way for bf to not play any note animations until the animation is done, but I cant find any way to stop the note animations

**Comment by frantastic24** [comment]
I already said you can't

**Comment by Ace5542** [comment]
> I already said you can't

damm

**Comment by CaptainBaldi** [comment]
> You can't You could make the character invisible and use a Lua sprite in their place instead

Don't notes have a noAnimation property? Why not use that?

**Comment by frantastic24** [comment]
You could, but for that you'd have to iterate over every present note and change the var if the animation matches, then switch it back if you don't want your character to idle for a few notes, all of this happening every frame
At that point may as well go with my first suggestion: hidden character and a mock up just for the animation, less code, easier to trigger, etc etc

**Comment by CaptainBaldi** [comment]
> You could, but for that you'd have to iterate over every present note and change the var if the animation matches, then switch it back if you don't want your character to idle for a few notes, all of this happening every frame At that point may as well go with my first suggestion: hidden character and a mock up just for the animation, less code, easier to trigger, etc etc

yeah fair enough
