### ISSUE TITLE
charting bug i think 

### ISSUE THREAD

**Issue by Lollidk** [ShadowMario/FNF-PsychEngine#11161]
### Describe your bug here.

I don't know if I'm stupid or something, but when I go to edit chart and insert the name of my song and do reload audio, the steps go to 0 and I can't do shit!!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

just added my characters

**Comment by frantastic24** [comment]
Not a bug
The game can't read your instrumental, re-export it

**Comment by Lollidk** [comment]
> Not a bug The game can't read your instrumental, re-export it
i just tried it and it doesn't work

**Comment by frantastic24** [comment]
Use an online converter

**Comment by TheKitBoi** [comment]
> i just tried it and it doesn't work

Then what file is your Inst

**Comment by Lollidk** [comment]
ogg

**Comment by frantastic24** [comment]
#11070

**Comment by Lollidk** [comment]
> Usa un convertitore online


> #11070


I tried everything and nothing changed, I give up for today lol

**Comment by frantastic24** [comment]
Either way it's not a bug

**Comment by Gostar64** [comment]
This might be a stupid question, but did you put in your song name correctly, as in like the folder name where the inst and voices files are?

**Comment by ACrazyTown** [comment]
> > #11070
> 
> I tried everything and nothing changed, I give up for today lol

Like I said in the mentioned issue, your audio file's sample rate might be over 44.1KHz. Convert it so it's at 44.1KHz or lower

**Comment by Lollidk** [comment]
Ok guys problem solved! Thank you for your help! :DD
