### ISSUE TITLE
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler  and  source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler how fix?

### ISSUE THREAD

**Issue by SideAR25XX** [ShadowMario/FNF-PsychEngine#11167]
### Describe your problem here.

i need a help how fix this error7:source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler i try to build psych and i have this error

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no i don't edit

**Comment by SideAR25XX** [comment]
i fix this i just dump

**Comment by final-23** [comment]
if you use hxcodec 2.5.1, you can compiled them
If you use hxcodec new version(git), you should to do:
1.delete this:
      #if VIDEOS_ALLOWED
      import vlc.MP4Handler;
      #end
2.change var video:
     MP4Handler = new MP4Handler(); to
     var video:VideoHandler = new VideoHandler();

**Comment by final-23** [comment]
if you use hxcodec 2.5.1, you can compiled them
If you use hxcodec new version(git), you should to do:
1.delete this:
#if VIDEOS_ALLOWED
import vlc.MP4Handler;
#end
2.change this:
var video:MP4Handler = new MP4Handler(); to
var video:VideoHandler = new VideoHandler();

**Comment by final-23** [comment]
tips: in the playstate.hx

**Comment by Noel3454565FNF** [comment]
now i have this 
source/PlayState.hx:1617: characters 13-25 : Type not found : VideoHandler

**Comment by final-23** [comment]
You CAN Do This:


In This:


#if VIDEOS_ALLOWED
import vlc.MP4Handler
#end



TRY To Change:


#if VIDEOS_ALLOWED
import hxcodec.VideoHandler;
#end

&nbsp;


2641215639
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月1日(星期三) 晚上7:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ShadowMario/FNF-PsychEngine] source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler  and  source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler how fix? (Issue #11167)





 
now i have this
 source/PlayState.hx:1617: characters 13-25 : Type not found : VideoHandler

**Comment by Noel3454565FNF** [comment]
okay sorry its working now :D

**Comment by final-23** [comment]
OK!

&nbsp;


2641215639
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月1日(星期三) 晚上9:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ShadowMario/FNF-PsychEngine] source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler  and  source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler how fix? (Issue #11167)





 
okay sorry its working now :D

**Comment by Time0utXC** [comment]
> i fix this i just dump

how? help pls

**Comment by Time0utXC** [comment]
> You CAN Do This: In This: #if VIDEOS_ALLOWED import vlc.MP4Handler #end TRY To Change: #if VIDEOS_ALLOWED import hxcodec.VideoHandler; #end &nbsp; 2641215639 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年2月1日(星期三) 晚上7:25 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [ShadowMario/FNF-PsychEngine] source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler and source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler how fix? (Issue #11167) now i have this source/PlayState.hx:1617: characters 13-25 : Type not found : VideoHandler — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

not working

**Comment by Noel3454565FNF** [comment]
> > i fix this i just dump
> 
> how? help pls

download playstate.hx again
