### ISSUE TITLE
Pico Speaker JSON File

### ISSUE THREAD

**Issue by YKoF-CALm** [ShadowMario/FNF-PsychEngine#11172]
### What is your question?

So I'm planning to do a Lua port of a Starlight Mayhem stage, and I wanna ask 3 questions:

1. In Stress, how does the `picospeaker` JSON file work (the file in the `data` file for Stress)?
2. Can I do something similar for other characters not in `dadGroup`, `gfGroup`, or `boyfriendGroup` (e.g. Lua characters)?
3. Can I run a character file in Lua and incorporate that with a file similar to `picospeaker`?

**Comment by YKoF-CALm** [comment]
Bumping this because I still can't figure it out.

**Comment by KutikiPlayz** [comment]
it uses another json file called picospeaker which is basically just a normal chart file except it uses those notes to make pico play different shooting animations
as far as I can see there's no way to make this work with other characters without changing the source code, what you can do however is use the play animation event to make something similar, however, that only works with dad bf and gf so if you wanna do it with a background character per se then you'd have to make a custom event to make that character play animations
