### ISSUE TITLE
Blackout the background (lua)

### ISSUE THREAD

**Issue by Nork1234** [ShadowMario/FNF-PsychEngine#11170]
### What is your question?

I want to know if I could do this in lua that could blackout the background. What I mean by this is like in Bold or Brash https://www.youtube.com/watch?v=HXvX8-XdDyY&t=96s . The background turns black in the clarinet solo. Ant then it turns back once the clarinet is gone. How could I do this in lua? edit: (kinda how blammed light did that with the BACKGROUND, not the coloring).

**Comment by frantastic24** [comment]
You could make the background invisible, since the default background color is black
If you have several background elements you could make a black box and layer it

**Comment by DisIsNOt** [comment]
setProperty('kidnamedfinger.visible', false)
