### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Kjjq** [ShadowMario/FNF-PsychEngine#11173]
### Describe your bug here.

StoryMenuState.hx (line 464)
StoryMenuState.hx (line 452)
StoryMenuState.hx (line 219)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
it crashed like this when i put down a chart for a song, i tried remaking the week that had this issue yet nothing worked help!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ACrazyTown** [comment]
Learn to debug, it will help you alot.
Line 464 in StoryMenuState is `grpWeekCharacters.members[i].changeCharacter(weekArray[i]);`, from this you can automatically figure out the problem. It crashes attempting to change the character so something about your character is not proper.
