### ISSUE TITLE
How to make background element float like in Vs. Shaggy?

### ISSUE THREAD

**Issue by luigiman0** [ShadowMario/FNF-PsychEngine#11177]
### What is your question?

Basically I'm trying to make one part of the background in my stage float up and down using Lua, similar to the rock platforms in Vs. Shaggy. Can anyone help me make this?

**Comment by CaptainBaldi** [comment]
pretty sure shaggy uses math to make the objects move, but considering no one likes math just use tweens

**Comment by wubbzyfan** [comment]
function onCreatePost()
  runTimer('fuckinUP', 0.001)
end

function onTimerCompleted(tag, loops, loopsLeft)
    if tag == 'fuckinUP' then
        doTweenY('fuckinshit1', 'object1', [basething - someamountidfk], TIME, {Ease}InOut)
        doTweenY('fuckinshit2', 'object2', [basething - someamountidfk], TIME, {Ease}InOut)
    runTimer('fuckinDOWN', TIME)
 elseif tag == 'fuckinDOWN' then
        doTweenY('fuckinshit1', 'object1', [basething + someamountidfk], TIME, {Ease}InOut)
        doTweenY('fuckinshit2', 'object2', [basething + someamountidfk], TIME, {Ease}InOut)
    runTimer('fuckinUP', TIME)
   end
end

**Comment by Isaagomen** [comment]
> function onCreatePost() runTimer('fuckinUP', 0.001) end
> 
> function onTimerCompleted(tag, loops, loopsLeft) if tag == 'fuckinUP' then doTweenY('fuckinshit1', 'object1', [basething - someamountidfk], TIME, {Ease}InOut) doTweenY('fuckinshit2', 'object2', [basething - someamountidfk], TIME, {Ease}InOut) runTimer('fuckinDOWN', TIME) elseif tag == 'fuckinDOWN' then doTweenY('fuckinshit1', 'object1', [basething + someamountidfk], TIME, {Ease}InOut) doTweenY('fuckinshit2', 'object2', [basething + someamountidfk], TIME, {Ease}InOut) runTimer('fuckinUP', TIME) end end

but its not on beat tho, maths are hard okay but you can find tutorials on the internet
