### ISSUE TITLE
decompilation problem

### ISSUE THREAD

**Issue by Nullyz** [ShadowMario/FNF-PsychEngine#11192]
### Describe your problem here.

in this my build it works normally, but as i'm on a new pc i decided to install the source again but it's giving this error i already tried to search and installed all the right plugins
![Capturar](https://user-images.githubusercontent.com/95359581/200716619-530092f5-4e74-4e83-9066-51d001125c42.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
> installed all the right plugins

if you get this error it means you did not

**Comment by ACrazyTown** [comment]
You didn't install Windows SDK and MSVC

**Comment by Nullyz** [comment]
but i installed all sdk's and MSCVV
![imagem_2022-11-09_195950607](https://user-images.githubusercontent.com/95359581/200960323-ef8dda4e-a85b-4852-b4c2-5ad4870a7ed9.png)

**Comment by BeastlyGhost** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/10756

**Comment by BambiFNF-NOFAEK** [comment]
You spelled "windows" incorrectly.
