### ISSUE TITLE
cant make some text as a part of the HUD

### ISSUE THREAD

**Issue by Flubbedsoda6010** [ShadowMario/FNF-PsychEngine#11197]
### Describe your problem here.

i'm trying to make my combo info be as part of the HUD but i couldn't 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#setobjectcameraobjstring-camerastring

**Comment by bruh1cat** [comment]
SetObjectCamera('object-name', 'camHUD')

**Comment by Flubbedsoda6010** [comment]
anyways i got it done after i had to make the setObjectCamera('sick/tnh','camHUD')
