### ISSUE TITLE
How to make it so +, -, and 0 won't fuck up audio, and how to restore 7 and 8 functionality after removing it?

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#11191]
### Describe your problem here.

So, I'm doing a typing gimmick (how original), and I know how to do setProperty('debugKeysChart', nil) and setProperty('debugKeysCharacter', nil). But I want to know how to make it so +, -, and 0 (the raise volume, lower volume, and mute volume keys) don't do stuff either. Basically, what's the key thingy that goes in place of 'debugKeysChart' to disable them

Also, how would I restore the functionality of them, ie: what would I put in place of nil to make the keys function again?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Grape-Boy** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/TitleState.hx#L118 and the next 2 lines

**Comment by wubbzyfan** [comment]
it just broke the thing after it

**Comment by wubbzyfan** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/TitleState.hx#L118 and the next 2 lines

it just broke the parts of it after the part where i try to turn the keys off

**Comment by Grape-Boy** [comment]
whar

**Comment by wubbzyfan** [comment]
The mute and stuff kept not being nil, and the script after the line where I tried them didn’t run

**Comment by wubbzyfan** [comment]
anyone please
