### ISSUE TITLE
Is this a compile error or is it normal?

### ISSUE THREAD

**Issue by SENFULLHD4K** [ShadowMario/FNF-PsychEngine#11194]
### Describe your problem here.

when I add lime test windows to cmd it says 

`source/Achievements.hx:132:` characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.set
DefaultDrawTarget` instead
source/MainMenuState.hx:69: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setD
defaultDrawTarget` instead
source/PlayState.hx:370: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefa
ultDrawTarget` instead
source/editors/CharacterEditorState.hx:94: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `Fl
xG.cameras.setDefaultDrawTarget` instead
source/editors/DialogueCharacterEditorState.hx:87: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated,
 use `FlxG.cameras.setDefaultDrawTarget` instead
source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.ca
meres.setDefaultDrawTarget` `instead`

and it stays like that without saying anything, that's why I have the doubt if it is being compiled or not I forgot to mention that I'm on windows 7

### Are you modding a build from source or with Lua? 

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Use the search feature before opening an issue
This has been asked to death, no those are not errors and will not prevent you from compiling

**Comment by SENFULLHD4K** [comment]
So it is compiling correctly?
