### ISSUE TITLE
multiple voice tracks

### ISSUE THREAD

**Issue by Neatoh** [ShadowMario/FNF-PsychEngine#11190]
### What is your question?

want to put two voice tracks for a song in the mod, is there any way for that to be possible

**Comment by DisIsNOt** [comment]
Just merge two audio clips together

**Comment by Neatoh** [comment]
I explained it horribly, but I want bf vocals and the opponents' vocals to be separate Ogg files but still work  in game if that makes sense

**Comment by Mokona5901** [comment]
> I explained it horribly, but I want bf vocals and the opponents' vocals to be separate Ogg files but still work in game if that makes sense

Maybe a lua script like
```
function OnSongStart()
     playMusic('opponent_voice', 1, false)
end
```
and have bf voice as voices.ogg

**Comment by Neatoh** [comment]
it didn't work for me

**Comment by Chidubemmo** [comment]
If you are using source I think you need to start by copying the code for the vocals in Paths.hx. I'm trying to do the same thing.
```haxe
	inline static public function dadvoice(song:String):Any
	{
		var songKey:String = '${formatToSongPath(song)}/dadvoice';
		var dadvoice = returnSound('songs', songKey);
		return dadvoice;
	}
```
The real problem would be trying to let it play in PlayState. I will update this if I finish (can you tell me if you manage to do it before than me?)
