### ISSUE TITLE
MP4 handler not found

### ISSUE THREAD

**Issue by FrealdFunk** [ShadowMario/FNF-PsychEngine#11202]
### Describe your problem here.

when i write lime test windows i say source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler, how do I fix it? Tell! I urgently need it!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by DisIsNOt** [comment]
Or you didn't import vlc.MP4Handler
