### ISSUE TITLE
Custom Splashes don't work properly

### ISSUE THREAD

**Issue by Wojtazzzekkk** [ShadowMario/FNF-PsychEngine#11201]
### Describe your problem here.

I wanted to add Indie Cross Splashes but they have more keyframes and different naming so I made a new sprite sheet and XML with the correct names but It doesn't work properly.

It sometimes spawns the first frame and sometimes it looks like it works fine with bad alignment. Can someone help me fix it?

![ezgif com-gif-maker](https://user-images.githubusercontent.com/76519877/201140189-8895926d-f6ca-4310-b2a4-a179566d31e3.gif)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by frantastic24** [comment]
Psych uses multiple animations per color, if one isn't found you get stuck with a still frame
You'll have to fix the alignment yourself through the XML

**Comment by Wojtazzzekkk** [comment]
But it looks like it uses one for each color, or is 20000 a different animation?
![image](https://user-images.githubusercontent.com/76519877/201145094-b73c0c35-d762-4cd3-b503-20de6ea8e767.png)

**Comment by frantastic24** [comment]
It's a different one, that's why there's a 1 or a 2 in front of the frame number

**Comment by Wojtazzzekkk** [comment]
Alright, I just duplicated every animation and changed it to 20000 smth and it works. Now I need to align it with framex framey yes?

**Comment by Wojtazzzekkk** [comment]
Alright now it works and looks nice, Thanks for help :>
