### ISSUE TITLE
Making GF as opponent more accessible

### ISSUE THREAD

**Issue by ScarabWasTaken** [ShadowMario/FNF-PsychEngine#11206]
### What feature do you want to get added on the **base** engine?

Currently in a chart if the [opponent] trait is set to "gf" (or at least a string that starts or ends in "gf") then the character will render as an opponent and will not render dancing gf. 
This means that any gf type characters cannot be played against unless they explicitly have gf in their character name without going into the source code. 

One alternate implementation would be to set [gf] trait as the character to sing against then simply set the [opponent] trait to "gf". So if [opponent] == "gf" then render dancing gf and dont render opponent.
Another implementation would be to set BOTH [gf] and [opponent] to the same value (opponent character).
So if [opponent] == [gf] then render opponent and dont render dancing gf.

Though these two options result in different objects being chosen, they have functionally identical outcomes.

![image](https://user-images.githubusercontent.com/85250052/201212119-7fb67bc2-adc6-4246-aa4d-c1fc7a7e94fc.png)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Draconic-Hybrid** [comment]
There's a workaround for this in Lua, but yeah that'd be nice

**Comment by Yuta12342** [comment]
A good idea, since using invisible opponents for alternate GFs is tiring.

**Comment by ScarabWasTaken** [comment]
Funny you mention it, I did end up using invisible character.

**Comment by Draconic-Hybrid** [comment]
Please close the issue, then.
