### ISSUE TITLE
Why does my modpack keep crashing?

### ISSUE THREAD

**Issue by Shmovver** [ShadowMario/FNF-PsychEngine#11209]
### Describe your problem here.

Im trying to make a fnf mod pack the pack it self shows up when its empty and it has no assets but when i put the assets in and open the mods category this is what i get,
![image](https://user-images.githubusercontent.com/117977272/201298785-4bafc309-0fd3-4cb2-a7b8-843bf0abc0ab.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by DisIsNOt** [comment]
Fix your .json

**Comment by TheKitBoi** [comment]
or just send the file

**Comment by Shmovver** [comment]
> Fix your .json

how do i fix it

**Comment by TheKitBoi** [comment]
if you have notepad++ you can find the line
if not rename the .json to .txt and send the file here so I can fix it
and ill send it back and you rename .txt to .json to replace the file
