### ISSUE TITLE
Different music on the week selected

### ISSUE THREAD

**Issue by JaceygekkieYT** [ShadowMario/FNF-PsychEngine#11208]
### Describe your problem here.

I need to know how people do it Like in Fnf HD if je selected a different week a different music will play how do you do that in psych engine????

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
https://github.com/Smokey555/FNF-HD-Open-Source/blob/main/source/StoryMenuState.hx
