### ISSUE TITLE
So i got this error.

### ISSUE THREAD

**Issue by ALEKSCRAFTPLAY** [ShadowMario/FNF-PsychEngine#11204]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/56561971/201151526-37770978-a1b7-413b-a2f6-2e472f9feead.png)

note: i was using fnf old engine's chart and was spamming keys without arrows showing up from boredness

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

only reskins and added extra characters and nothing else

**Comment by frantastic24** [comment]
You did not explain _when_ does it happen

**Comment by ALEKSCRAFTPLAY** [comment]
it came with xml file

**Comment by frantastic24** [comment]
I see
Yeah that's not a bug, your note skin is missing `end` animations

**Comment by ALEKSCRAFTPLAY** [comment]
> I see Yeah that's not a bug, your note skin is missing `end` animations

then why you can't make compatibility for old notes by checking the xml if it has it, if not, just use old note code. why it shouldn't support old notes? i mean it dosen't have to but it could be helpful if your moving mod from another engine that dosen't have it. btw thanks for helping

**Comment by frantastic24** [comment]
It uses the same system as base FNF

**Comment by ALEKSCRAFTPLAY** [comment]
oh im dumb, i just realized this noteskin is old :/
