### ISSUE TITLE
i got this bug

### ISSUE THREAD

**Issue by Tamir-YT** [ShadowMario/FNF-PsychEngine#11214]
### Describe your bug here.

source/editors/CharacterEditorState.hx:94: characters 16-36 : Cannot rebind this method : please use 'dynamic' before method declaration
source/editors/DialogueCharacterEditorState.hx:87: characters 16-36 : Cannot rebind this method : please use 'dynamic' before method declaration
source/MainMenuState.hx:66: characters 16-36 : Cannot rebind this method : please use 'dynamic' before method declaration
source/Achievements.hx:324: characters 3-64 : (camera : flixel.FlxCamera, value : Bool) -> Void should be Array<flixel.FlxCamera>
source/options/NoteOffsetState.hx:57: characters 16-36 : Cannot rebind this method : please use 'dynamic' before method declaration
source/PlayState.hx:319: characters 16-36 : Cannot rebind this method : please use 'dynamic' before method declaration

how can i fix this

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Tamir-YT** [comment]
why no one commented

**Comment by TheKitBoi** [comment]
be patient

**Comment by Tamir-YT** [comment]
fine
