### ISSUE TITLE
some properties of LuaObject doesn't function

### ISSUE THREAD

**Issue by CreamAlphaWolfram** [ShadowMario/FNF-PsychEngine#11212]
### Describe your bug here.

LuaObject.acceleration.x/y and LuaObject.velocity.x/y aren't working, that's all

(Using version: 0.6.3)

### Command Prompt/Terminal logs (if existing)

*no response*

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I only used Lua.

**Comment by frantastic24** [comment]
Velocity works, don't know about acceleration
These are haxe related anyways, Lua has nothing to do with them

**Comment by CreamAlphaWolfram** [comment]
We can use setProperty()
But somehow changing them via setProperty('LuaObject.velocity.x/y / LuaObject.acceleration.x/y', val) just doesn't work

**Comment by frantastic24** [comment]
I use velocity and it does work
These are haxe properties, not Lua

**Comment by CreamAlphaWolfram** [comment]
Huh.

Maybe I'll try removing that acceleration.x/y first

**Comment by CreamAlphaWolfram** [comment]
![My script snippet](https://user-images.githubusercontent.com/102781612/201368468-7b1badf8-e8fd-4c51-a7f3-2986aff70da8.png)
But wait, if the whole thing is functioning well and the velocity & acceleration doesn't function...

The things can't be changed via Lua I guess?

**Comment by frantastic24** [comment]
i just tested all of them, all worked

**Comment by CreamAlphaWolfram** [comment]
Uh,

so weird

**Comment by CreamAlphaWolfram** [comment]
![Test image](https://user-images.githubusercontent.com/102781612/201458287-298f537d-55be-4a22-a5e1-3b1d3a3afad2.png)
So, the setProperty is working, and yes it doesn't function, bruh
