### ISSUE TITLE
are there any good tutorials for coding in lua?

### ISSUE THREAD

**Issue by noskincz** [ShadowMario/FNF-PsychEngine#11210]
### Describe your problem here.

i need help with porting a mod and i dont want to get all the code from someone and i dont know how to use lua

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by UncertainProd** [comment]
I found that Lua's own website was pretty good: https://www.lua.org/pil/contents.html#P1
As for video tutorials, there's this one: https://www.youtube.com/watch?v=iMacxZQMPXs
And for Psych Engine specific lua stuff, just check their [wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki)

**Comment by noskincz** [comment]
> 

thanks

**Comment by noskincz** [comment]
> I found that Lua's own website was pretty good: https://www.lua.org/pil/contents.html#P1 As for video tutorials, there's this one: https://www.youtube.com/watch?v=iMacxZQMPXs And for Psych Engine specific lua stuff, just check their [wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki)

also do you have the custom event template? i am trying to make one

**Comment by DisIsNOt** [comment]
function onEvent(n, v1,v2)
    if name == 'eventname' then
           makeLuaText('funnitext', v1, 0, 300, 400)
           setObjectCamera('funnitext', 'hud')
           addLuaText('funnitext')
          if v1 == nil then
             setTextString('funnitext', 'nothing is here')
          end


    end


end 

idk

**Comment by noskincz** [comment]
> function onEvent(n, v1,v2) if name == 'eventname' then makeLuaText('funnitext', v1, 0, 300, 400) setObjectCamera('funnitext', 'hud') addLuaText('funnitext') if v1 == nil then setTextString('funnitext', 'nothing is here') end
> 
> ```
> end
> ```
> 
> end
> 
> idk

Ok thanks i will try making a event
