### ISSUE TITLE
stage error

### ISSUE THREAD

**Issue by Yoshi-RBLX** [ShadowMario/FNF-PsychEngine#11215]
### Describe your problem here.

so im making an animated thingy in a stage, and it shows its trying to load in the sprite but it only shows the haxeflixel logo, and i copy and pasted the image name, so i dont know why it doesnt recognize the image name or anything

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no source code was edited

**Comment by CaptainBaldi** [comment]
invalid image path

**Comment by Yoshi-RBLX** [comment]
> 

thats weird it shouldnt be because i literally copy and pasted the image name

**Comment by CaptainBaldi** [comment]
can you send your line

**Comment by Yoshi-RBLX** [comment]
makeAnimatedLuaSprite('animation', 'crowdbop', 300, 200); 
	addAnimationByPrefix('animation', 'dance', 'dance', 24, true);
	setScrollFactor('animation', 1, 1);

**Comment by CaptainBaldi** [comment]
hm
not sure why it doesnt work
maybe throw the image in a subfolder and adjust the code accordingly to see if it works
alternatively you can try `checkFileExists` to see if the engine is reading your file

**Comment by Yoshi-RBLX** [comment]
maybe instead of being in characters cause i put it there ill just put it in images
ill try again

**Comment by Yoshi-RBLX** [comment]
yea putting it in images worked ty
