### ISSUE TITLE
Help me asap

### ISSUE THREAD

**Issue by Aden-Mystio** [ShadowMario/FNF-PsychEngine#11217]
### Describe your problem here.

What does this mean

C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 318)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 99)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
WeekData.hx (line 222)
WeekData.hx (line 190)
WeekData.hx (line 178)
StoryMenuState.hx (line 58)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid char 123 at position 3
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
It means your week json is broken

**Comment by TheKitBoi** [comment]
Send the file
rename .json to .txt
