### ISSUE TITLE
Title menu not working

### ISSUE THREAD

**Issue by Fridox-lol** [ShadowMario/FNF-PsychEngine#11224]
### Describe your bug here.

When I boot up the game, the menu just doesn't work.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited TitleState (i replaced the og menu with funkin for bikini bottom's and fixed everything so it works in psych) and other things

**Comment by frantastic24** [comment]
It's probably something you broke, explain what "doesn't work" means

**Comment by Fridox-lol** [comment]
> It's probably something you broke, explain what "doesn't work" means

It just freezes without doing anything, the animations still work tho

**Comment by TheKitBoi** [comment]
Then show the code

**Comment by Fridox-lol** [comment]
[TitleState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9995887/TitleState.txt)
I just copied it from Funkin for Bikini Bottom (because yes) and made it work on Psych

**Comment by TheKitBoi** [comment]
are the image files on the right place

**Comment by Fridox-lol** [comment]
> are the image files on the right place

yes

**Comment by Fridox-lol** [comment]
I ended up redoing the thing so yeah
