### ISSUE TITLE
Uncaught Error- Deltarune Mod

### ISSUE THREAD

**Issue by Leorndo10** [ShadowMario/FNF-PsychEngine#11222]
### Describe your bug here.

I'm trying to acces a secret song, and this error keeps poping. Though it's my first time on Github, if something's wrong or missing, please let me know !

### Command Prompt/Terminal logs (if existing)

```bash
C:/HaxeToolkit/haxe/std/cpp/_std/io/File.hx(line 30
Song.hx(Line 104)
editors/ChartingState.hx(Line 2954)
editors/ChartingState.hx(Line 434)
Prompt.hx (Line 44)
flixel/ui/FlxButton.hx (Line 521)
flixel/ui/FlxButton.hx (Line 507)
openfl/events/EventDispatcher.hx (Line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught error: [File_content,assets/data/man/man-hard.json]
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Idk anything

**Comment by TheKitBoi** [comment]
You forgot the man-hard.json

**Comment by CaptainBaldi** [comment]
not a bug
missing chart
