### ISSUE TITLE
Vocal Loop

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#11226]
### Describe your problem here.

In three songs because I don't know if in more, when the song "ends" the vocals are like starting again. In two songs is just a short loop of the vocals but it is bothering me. And in one song when the notes are over the vocals are starting again but in this song is so much time. It keeps bothering me that and I want to see if someone can help me pls.

> NOTE: I put lua because I think is in json... I dont know

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
happens when inst and vocals aren't the same length

**Comment by GatoMorado621** [comment]
> happens when inst and vocals aren't the same length

Oh.... Ok thanks
