### ISSUE TITLE
Not sure if it is a bug and not using source code

### ISSUE THREAD

**Issue by MitchyBo** [ShadowMario/FNF-PsychEngine#11225]
### Describe your bug here.

PlayState.hx (line 4633)
PlayState.hx (line 3240)
flixel/group/FlxGroup.hx (line 769)
PlayState.hx (line 3179)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
when and how does this happen? need info to recreate
are you using a custom note texture?
