### ISSUE TITLE
How can i add cinematic bars (SOURCE CODE)

### ISSUE THREAD

**Issue by Akumalol** [ShadowMario/FNF-PsychEngine#11228]
### Describe your problem here.

Does anyone know how to add cinematic bars? like the troll face funkin but at specific times

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TFLTV** [comment]
Maybe code an event in source?

**Comment by TheKitBoi** [comment]
https://discord.com/channels/922849922175340586/1023746975860002858/1023746975860002858
then use this event

**Comment by TheKitBoi** [comment]
That was made in lua
