### ISSUE TITLE
Layering characters

### ISSUE THREAD

**Issue by BrayTheGreat** [ShadowMario/FNF-PsychEngine#11227]
### Describe your problem here.

Im working on a bonus song for my mod, and I need my boyfriend character to be behind the opponent layer-wise. As of right now, the bf sprite is above the opponent layer. I would really like some help with this small issue. Thank you all for your time.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#object-orderremoving

**Comment by BrayTheGreat** [comment]
Thanks!
