### ISSUE TITLE
 What is the principle of botplay? where is the source code?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#1123]
### What is your question?

 What is the principle of botplay?
I want to see the source code, but I don't find it.
![image](https://user-images.githubusercontent.com/13177997/142412862-7b2527b8-4ad4-4178-ac59-d708eca63e44.png)

**Comment by 4wdthinks** [comment]
??

**Comment by zwl1619** [comment]
@4wdthinks I want to check the source code.

**Comment by 4wdthinks** [comment]
the source code is literally on this site...

**Comment by zwl1619** [comment]
@4wdthinks I see, but I search it with keyword  "botplay", I don't find the specific implementation.

**Comment by 4wdthinks** [comment]
so what do you mean by "principle"? are you looking for how botplay actually works?

**Comment by zwl1619** [comment]
@4wdthinks yes. I don't know what word to use.

**Comment by lemz1** [comment]
botplay is called cpucontrolled

this the code for hitting the notes line 2299

```
if(daNote.mustPress && cpuControlled) {
					if(daNote.isSustainNote) {
						if(daNote.canBeHit) {
							goodNoteHit(daNote);
						}
					} else if(daNote.strumTime <= Conductor.songPosition || (daNote.isSustainNote && daNote.canBeHit && daNote.mustPress)) {
						goodNoteHit(daNote);
					}
				}
```
`goodNoteHit(daNote);` makes the bot hit the note. If you would change it to `noteMiss(daNote);` then the bot would miss the note

this is the code for the animation line 3528
```
if(cpuControlled) {
				var time:Float = 0.15;
				if(note.isSustainNote && !note.animation.curAnim.name.endsWith('end')) {
					time += 0.15;
				}
				StrumPlayAnim(false, Std.int(Math.abs(note.noteData)) % 4, time);
```
time is how long the animation is.
