### ISSUE TITLE
Vocals loop due to Instrumental being shorter.

### ISSUE THREAD

**Issue by RowanSkie** [ShadowMario/FNF-PsychEngine#11233]
### Describe your bug here.

In the official Week 7 build, if you play the song Thorns and wait till the end, it'll be quiet.

However, in the release and the latest source code build, the vocals suddenly loop back to the start.

It's not as annoying as a glitchy sound found pre-Week 7 builds, but it's still a bit jarring.

It's just #8400 and #9515, basically.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No edits.

**Comment by TheKitBoi** [comment]
There’s nothing we can do about it

**Comment by RowanSkie** [comment]
How'd the Newgrounds/Week 7 version did it then? Also I think one version ago already had this fixed aswell.
