### ISSUE TITLE
Aspect ratio looks off in Linux

### ISSUE THREAD

**Issue by Playertrip777** [ShadowMario/FNF-PsychEngine#11237]
### Describe your bug here.

The aspect ratio of Psych Engine looks off and doesn't center properly, and the games zooms out automatically if a opponent starts singing, this applies to every song.

https://user-images.githubusercontent.com/90383277/201894402-4dc0fa06-eb91-4b2f-8f7b-89628ffb8885.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't edit anything

**Comment by TheKitBoi** [comment]
you pressed fullscreen while it was finishing loading

**Comment by Playertrip777** [comment]
> you pressed fullscreen while it was finishing loading

I don't think I press something that sets it to fullscreen.

**Comment by Playertrip777** [comment]
nvm i found a fix
