### ISSUE TITLE
How can I change what folder the .sol save data file is in? (SOURCE CODE)

### ISSUE THREAD

**Issue by NesDoesGithub** [ShadowMario/FNF-PsychEngine#11231]
### Describe your problem here.

I would like to change where the .sol save data is located but I got no clue how I can do that, can anyone help me?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

**Comment by TheKitBoi** [comment]
you can change the package name in the project.xml at line 5
packageName="com.shadowmario.psychengine" package="com.shadowmario.psychengine"
