### ISSUE TITLE
Window Shake

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#11236]
### Describe your problem here.

I was wondering if there is a script when the opponent sings, the app or the window shake. If you can help me with the script I would appreciate it a lot.

> NOTE: Is for my mod...

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Kufferey** [comment]
I'll try and make a lua script.

**Comment by GatoMorado621** [comment]
> I'll try and make a lua script. What version you on?

Thanks. In the 0.6.3... The recent 😅😅

**Comment by Kufferey** [comment]
Ok, I'll try my best/

**Comment by Kufferey** [comment]
DID it

**Comment by Kufferey** [comment]
Just fittle with the values i made ok?

**Comment by Kufferey** [comment]
Here is ui.

**Comment by Kufferey** [comment]
function opponentNoteHit(id, direction, noteType, isSustainNote)
	cameraShake('hud', '0.5', '1')
end

**Comment by Kufferey** [comment]
Here is both UI and on-UI

**Comment by Kufferey** [comment]
`function opponentNoteHit(id, direction, noteType, isSustainNote)
	cameraShake('hud', '0.5', '1')
    cameraShake('game', '0.5', '1')
end`

**Comment by Kufferey** [comment]
function opponentNoteHit(id, direction, noteType, isSustainNote)
	cameraShake('hud', '0.5', '1')
    cameraShake('game', '0.5', '1')
end

**Comment by Kufferey** [comment]
there.

**Comment by GatoMorado621** [comment]
> there.

Thank You So Much ❤️❤️😊😊

**Comment by Kufferey** [comment]
Did it work for ya?

**Comment by GatoMorado621** [comment]
> Did it work for ya?

Yes. Thank You :)

**Comment by Kufferey** [comment]
Hey!

**Comment by Kufferey** [comment]
I made a vid to make it work better! here hold up.

**Comment by Kufferey** [comment]
https://www.youtube.com/watch?v=4MYz0l497_8

**Comment by Kufferey** [comment]
sorry for bad english.

**Comment by GatoMorado621** [comment]
> sorry for bad English.

Dont worry. Its litery what I want. Thank You So Much 😊😊😊❤️❤️

**Comment by GatoMorado621** [comment]
> I made it better if you want to see that skip to 1:50

A lots of TYSM xD... No but seriously thank you so much this will be perfect for my mod. Again TYSM 😊😊😊😊❤️❤️❤️❤️

**Comment by Kufferey** [comment]
here is new code

**Comment by Kufferey** [comment]
function opponentNoteHit(id, direction, noteType, isSustainNote)
	cameraShake('hud', '0.05', '0.1')
    cameraShake('game', '0.05', '0.1')
end

**Comment by Kufferey** [comment]
btw welcome

**Comment by Kufferey** [comment]
Welcome
