### ISSUE TITLE
Window name for non-source code users!

### ISSUE THREAD

**Issue by TheGaloXx** [ShadowMario/FNF-PsychEngine#11243]
### What feature do you want to get added on the **base** engine?

I think people should be able to change the window name to whatever they want.
This should be easy, just a text file in the 'data' folder, and code something like this:
![image](https://user-images.githubusercontent.com/88469278/202083238-c882d317-1a0e-4709-aeaa-d36ffddab3c2.png)

Also custom window icons could be great.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Draconic-Hybrid** [comment]
I know it's possible to do that during a song. You can also use onDestroy to permanently change it during the menus as well when a song ends.

The code is 
setPropertyFromClass("openfl.Lib", "application.window.title", "[whatever you want]")
