### ISSUE TITLE
can i tie shaders to events in psych engine

### ISSUE THREAD

**Issue by Thimque** [ShadowMario/FNF-PsychEngine#11244]
### Describe your problem here.

So, I wanna know if its possible to tie shaders to events? Similar to how the Hypnos Lullaby mod does it _(although its an entirely different engine)_ Can I do it via Lua or will I have to do source? _(please say I can do Lua)_

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by naether** [comment]
yes! just initiate the shader onCreate() in the event and then onEvent() actually apply it to the sprite

**Comment by Thimque** [comment]
> yes! just initiate the shader onCreate() in the event and then onEvent() actually apply it to the sprite

Do you mind explaining or showing me some example? Im not really good at coding lmao-
