### ISSUE TITLE
null object reference

### ISSUE THREAD

**Issue by tenout** [ShadowMario/FNF-PsychEngine#11248]
### Describe your bug here.

i was going to play omnipresent until...

C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
FreeplayState.hx (line 371)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/omnipresent/omnipresent-hard.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.. not yet.

**Comment by frantastic24** [comment]
Not a bug
Missing chart

**Comment by Ninjakaiden523** [comment]
> Not a bug Missing chart

No I think missing charts have a different reaction than a null object reference, those happen when a file essential to another file baked in the source code is missing (or something like that), trust me I would know. To the person who made this issue, try checking everything, from your code to your character's image name in the .Json, anything that could have loaded when you got the error.

**Comment by frantastic24** [comment]
No this is exactly how a missing chart error looks like, look at the uncaught error part

**Comment by Ninjakaiden523** [comment]
Oh, wait yeah, I didn't read that, I just saw the name and assumed that it was a null object reference. But now they know what to do for one in the future if they get a real null object reference.
