### ISSUE TITLE
Practice Mode

### ISSUE THREAD

**Issue by Jevilm** [ShadowMario/FNF-PsychEngine#11249]
### What is your question?

Can you change the score text if practice mode is enabled with lua?

**Comment by Parsellol** [comment]
```lua
function onUpdateScore()
    if getProperty("practiceMode") == true then
        setProperty("scoreTxt.text", "FUCK YOU!!!!!!!!!!!!!!!!")
    end
end
```

if it dont work then try changing onUpdateScore to just onUpdate

**Comment by CaptainBaldi** [comment]
> ```lua
> function onUpdateScore()
>     if getProperty("practiceMode") == true then
>         setProperty("scoreTxt.text", "FUCK YOU!!!!!!!!!!!!!!!!")
>     end
> end
> ```
> 
> if it dont work then try changing onUpdateScore to just onUpdate

there's a variable for practice smh
```function onCreatePost()
        if practice then
                debugPrint('stoopid cheater')
        end

**Comment by Jevilm** [comment]
i couldnt find the variable thank  you
