### ISSUE TITLE
Uh-hard coded title screen stufff

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#1124]
### What feature do you want to get added on the base engine?

For the title screen gf and logo, maybe there could be offset txt files for them, so if people make custom logos or gf’s,they can be placed in the correct area if needed. Or just full lua files containing the entire title screen and opening stuff. So people can customize that way easier.

**Comment by MayoALT** [comment]
but what about when multiple mods override the title screen?

**Comment by crispyboi24** [comment]
There’s gonna be a mod menu to disable and re-enable mods so overwriting shouldnt be a problem

**Comment by ShadowMario** [comment]
No
