### ISSUE TITLE
can't compile (again)

### ISSUE THREAD

**Issue by lime360** [ShadowMario/FNF-PsychEngine#11246]
### Describe your problem here.

this time the console gives me another error

```
BUILDING GAME
source/PlayState.hx:332: characters 2-10 : Unexpected override

done.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i edited FunkinLua.hx and PlayState.hx (this time is just removing wavy backgrounds)

**Comment by hexogit** [comment]
show line 332

**Comment by lime360** [comment]
![image](https://user-images.githubusercontent.com/56405352/202393113-01917fd0-7d1f-4ef2-b882-e12ae0db647b.png)
here

**Comment by hexogit** [comment]
> ![image](https://user-images.githubusercontent.com/56405352/202393113-01917fd0-7d1f-4ef2-b882-e12ae0db647b.png) here

what class does it extend

**Comment by lime360** [comment]
playstate

**Comment by lime360** [comment]
ok so i removed another code from sc 1.5 (this time it's eyesores), and i will try to recompile it, i will close this issue once the compiler will work

**Comment by lime360** [comment]
ok it still gives my the unexcepted override error
