### ISSUE TITLE
Script Difficulty help

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#11256]
### Describe your problem here.

I was putting a script for a just difficulty. In the script I put 2 functions that 1 function would be for a difficulty and the another one would be for the other difficulty. I search which number would be a difficulty and here comes the problem. I just have 2 difficultys "hard" and "expert" in the week but I have 4 diffcultys in the data (this is for information). And I thougth that the number 0 is for the "hard" and the number 1 would be for the "expert" but for some reason, the function, that is suppose to be in the dificulty, is in the another difficulty.
Here is the script:
```
function opponentNoteHit(id, direction, noteType, isSustainNote)
	if difficulty == 0 then
		cameraShake('hud', '0.005', '0.1')
		cameraShake('game', '0.005', '0.1')
	elseif difficulty == 1 then
		cameraShake('hud', '0.006', '0.1')
		cameraShake('game', '0.006', '0.1')
	end
end
```
The fist function that is the number 0, is for the "hard" difficulty, but the function of the number 1 (expert) is in the number 0 (hard). And I want that the function of the number 1 (expert) is in the same difficulty (expert).
EDIT: The second function is in the 2 difficultys and I want that one function would be in the difficulty that is suppose to be

If someone could help me with this, I would appreciate it a lot. If you didn't understand something, I will explain you.
But pls help me....

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
You already have an open issue, you didn't need to open another one
You could just switch the values? The difficulty index depends on the order in your week file
