### ISSUE TITLE
Werid error

### ISSUE THREAD

**Issue by Cap6ailB3an** [ShadowMario/FNF-PsychEngine#11250]
### What is your question?

i cannot add a preveiw of the error but when i search up the .EXE and go to the file the game goes black, than it brings up a weird message something like "librarie folder could not be found" then it crashes. can you tell me about this?

**Comment by DevFregnub** [comment]
You might have deleted or moved a critical file that resulted in the game not working, I recommend you try redownloading the game and testing if it works that way.

**Comment by Cap6ailB3an** [comment]
i figured out what the bug was upon opening psych engine.exe the file crashes (because it is just opened from the search bar and is not an app)
