### ISSUE TITLE
Script Difficulty

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#11253]
### Describe your problem here.

I don't know if is possible but I want that a script just work in one difficulty. If someone can help me with that pls help me....
I would appreciate it a lot.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Duplicate of several other issues, use the search feature

**Comment by TurtleFanCoder** [comment]
if difficulty == 2 then

**Comment by TurtleFanCoder** [comment]
numbers correspond to dificulty

**Comment by GatoMorado621** [comment]
> numbers correspond to dificulty

Thank You So Much

**Comment by TurtleFanCoder** [comment]
your welcome

**Comment by TheKitBoi** [comment]
close this issue
![close the dam issue](https://user-images.githubusercontent.com/84044666/203140700-31a4d665-47b7-4fb1-8309-16b5be1be36f.gif)

**Comment by GatoMorado621** [comment]
> close this issue ![close the dam issue](https://user-images.githubusercontent.com/84044666/203140700-31a4d665-47b7-4fb1-8309-16b5be1be36f.gif) [ ![close the dam issue](https://user-images.githubusercontent.com/84044666/203140700-31a4d665-47b7-4fb1-8309-16b5be1be36f.gif) ](https://user-images.githubusercontent.com/84044666/203140700-31a4d665-47b7-4fb1-8309-16b5be1be36f.gif) [ ](https://user-images.githubusercontent.com/84044666/203140700-31a4d665-47b7-4fb1-8309-16b5be1be36f.gif)

Sorry, I forgot
