### ISSUE TITLE
UI Transparency Feature

### ISSUE THREAD

**Issue by DevFregnub** [ShadowMario/FNF-PsychEngine#11259]
### What feature do you want to get added on the **base** engine?

In the settings of psych, I've seen the "Healthbar Transparency" Option and I personally think it would be a good idea to make an option for every UI feature such as: Notes, Judgement (Score, Misses & Rating), ect. or maybe all of them together. Just a little side thought of mine.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Lorekeeper49** [comment]
> `camHUD.alpha = ClientPrefs.hudAlpha`.
> 
> plus you can already do this with lua? `setProperty('camHUD.alpha', your number)`

I think he's looking for the health bar in particular

**Comment by CaptainBaldi** [comment]
> > `camHUD.alpha = ClientPrefs.hudAlpha`.
> > plus you can already do this with lua? `setProperty('camHUD.alpha', your number)`
> 
> I think he's looking for the health bar in particular

that isnt hard to do either
