### ISSUE TITLE
there is a way for the enemy to have different note style than boyfriend ??

### ISSUE THREAD

**Issue by AlyssonRo** [ShadowMario/FNF-PsychEngine#1125]
### What is your question?

like the bob and bosip mod could be in source code or in lua
![Sem título](https://user-images.githubusercontent.com/92331433/142435547-23c5e9f0-9e2b-4613-86cb-1d14ff2ab8e7.png)

**Comment by MayoALT** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/discussions/995

**Comment by mapleeeeeeeeeeeeee** [comment]
@AlyssonRo Make a custom note type when u chart use it in the enemy's side though you cant change the note glow and the grey thing its the closest thing

**Comment by MayoALT** [comment]
close the issue

**Comment by ShadowMario** [comment]
Close it yourself next time.
