### ISSUE TITLE
Custom Substates don't open on certain callbacks

### ISSUE THREAD

**Issue by MarkimusZer0** [ShadowMario/FNF-PsychEngine#11255]
### Describe your bug here.

Trying to open custom substates onCreate, onCreatePost or onCountdownStart doesn't work, 
from what I've seen they only seem to open once the song has started (onSongStart) but otherwise no

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nah

**Comment by Meme1079** [comment]
Not a bug you have to put them in here:

### onCustomSubstateCreate(name)
The start of the lua script on the custom substate.

- `name` - The name of the custom substate. (This is important to use!)

### onCustomSubstateCreatePost(name)
The post/after start of the lua script on the custom substate.

### onCustomSubstateUpdate(name, elapsed)
The every frame on the game currently on the custom substate.

### onCustomSubstateUpdatePost(name, elapsed)
The post/after every frame on the game currently on the custom substate.

### onCustomSubstateDestroy(name)
The end of the lua script on the custom substate.

**Comment by MarkimusZer0** [comment]
> Not a bug you have to put them in here:
> 
> ### onCustomSubstateCreate(name)
> The start of the lua script on the custom substate.
> 
> * `name` - The name of the custom substate. (This is important to use!)
> 
> ### onCustomSubstateCreatePost(name)
> The post/after start of the lua script on the custom substate.
> 
> ### onCustomSubstateUpdate(name, elapsed)
> The every frame on the game currently on the custom substate.
> 
> ### onCustomSubstateUpdatePost(name, elapsed)
> The post/after every frame on the game currently on the custom substate.
> 
> ### onCustomSubstateDestroy(name)
> The end of the lua script on the custom substate.

Not what I'm talking about,

The act of opening the specific substates doesn't work,
Say i use openCustomSubstate onCreate, it won't open for whatever reason.

Only when the song starts does it actually open and run the custom substate code

**Comment by Meme1079** [comment]
> Not what I'm talking about,

Ohhh my bad
