### ISSUE TITLE
Feature Request: Separate PlayState.hx

### ISSUE THREAD

**Issue by crispyi2** [ShadowMario/FNF-PsychEngine#1126]
### What feature do you want to get added on the base engine?

# Explanation

The PlayState.hx script is very long making it hard for people going from scripting with lua to scripting with the source code (and me) to figure out where everything is

# Ideas

### I think the following things could be separated into different scripts

- Hud sprite group
	- this should be changed from FlxTypedGroup to FlxTypedSpriteGroup
		- this basically just makes it so that the entire hud is treated as one big sprite allowing the group as a whole to be changed while still being able to change the sprites individually
- Note sprite group
	- Includes the note track for bf and the opponent as well as the group containing all the notes
	- this should also be changed from FlxTypedGroup to FlxTypedSpriteGroup
- A new group containing animated characters
	- New characters can be added to this group through lua scripting or plain old source code editing
	- this should be a FlxTypedSpriteGroup
- A new group containing all the assets from the stage
	- This group wil also contain the animated character group along with all of the stage sprites
- Playstate camera manipulation
- Input system
- Lua script loading
	- Contains ```luaArray<FunkinLua>``` (not FunkinLua itself)
	- Also contains all the code detecting lua files and adding them to LuaArray

**I will add more to this list when I think of more**

### New lua functions, callbacks, and variables

- Input system
	- run a Lua callback when bf or the opponent hits a note
		- Both should be separate functions
		- parameters:
			- direction
				- the direction the hit note
			- rating
				- the rating earned when hitting the note
			- time
				- the amount of time it took the player to hit the note
			- type
				- the type of note that was hit
		- function names:
			- bfNoteHit
			- opponentNoteHit
	- run Lua callback when bf or the opponent misses a note
		- Both should be separate functions
		- parameters
			- direction
				- the direction of the missed note
			- type
				- type of note that was missed
		- function names:
			- bfNoteMiss
			- opponentNoteMiss
- Note sprite group
	- check a Lua variable to determine if middlescroll is forced
		- type: Boolean
		- variable name: forceMiddlescroll
	- check a Lua variable to determine if downscroll is forced
		- type: Boolean
		- variable name: forceDownscroll
- animated characters group
	- check if a Lua function was called that adds an animated character
		- parameters:
			- characterName
				- the name of the character (will be used to identify characters in other functions)
			- characterJson
				- will read json file in the characters directory specified
		- function name: addAnimatedCharacter
	- check if a Lua function was called that plays an animation in the animArray variable specified in the parameters
		- parameters:
			- characterName
				- specifies the character with the animation to play
			- animName
				- name of the animation from animArray to play
			- fps
				- frames per second
		- function name: playCharacterAnim
	- check if a Lua function was called that plays an animation in the animArray variable specified in the 
    	- Stops any animations that are playing
		- parameters:
			- characterName
				- specifies the character to stop animating
		- function name: stopCharacterAnim
- A bunch of other lua functions that handle tweening, positioning, rotating, alpha, etc. I don't feel like writing them here because Ive already spent like 2 hours on this

#### Example Lua script:

```lua
forceMiddlescroll = true;
forceDownscroll = false;

function onCreate()
    addAnimatedCharacter("testChar", "testChar.json");
    playCharacterAnim("testChar", "testAnim", 24);
    stopCharacterAnim("testChar");
end

function bfNoteHit(direction, rating, time, type)

end

function opponentNoteHit(direction, rating, time, type)

end

function bfNoteMiss(direction, type)

end

function opponentNoteMiss(direction, type)

end
```

**Comment by 4wdthinks** [comment]
i agree with the opponent note hitting, im trying to make 2 characters sing at once but there's currently no detection for when dad hits a note.

**Comment by crispyi2** [comment]
> i agree with the opponent note hitting, im trying to make 2 characters sing at once but there's currently no detection for when dad hits a note.

There is detection for when dad hits a note... although its practically hidden in the wasGoodNoteHit() function in PhayState.hx

**Comment by 4wdthinks** [comment]
> 
> 
> > i agree with the opponent note hitting, im trying to make 2 characters sing at once but there's currently no detection for when dad hits a note.
> 
> There is detection for when dad hits a note... although its practically hidden in the wasGoodNoteHit() function in PhayState.hx

currently using lua, goodNoteHit doesn't do anything when dad hits as note.

**Comment by KlavierGayming** [comment]
use opponentNoteHit(), works for me!

**Comment by ShadowMario** [comment]
I'm not going to separate PlayState.

**Comment by crispyi2** [comment]
> I'm not going to separate PlayState.

Fair enough
