### ISSUE TITLE
something wrong with FunkinLua.hx

### ISSUE THREAD

**Issue by gold198** [ShadowMario/FNF-PsychEngine#11262]
### Describe your bug here.

when i type lime test windows i get this error: source/FunkinLua.hx:613: lines 613-617 : Int should be Bool
source/FunkinLua.hx:613: lines 613-617 : ... For function argument 'f'

and yes, I did use what it says in readme

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I haven't edited anything yet, I was just compiling it

**Comment by frantastic24** [comment]
Not a bug
Duplicate
Read pinned issue
