### ISSUE TITLE
Week Misses

### ISSUE THREAD

**Issue by Draconic-Hybrid** [ShadowMario/FNF-PsychEngine#11268]
### What is your question?

Do any of y'all know how to get the total week misses in Lua? Theoretically, it should appear with `getProperty('campaignMisses')`, but `debugPrint(getProperty('campaignMisses'))` doesn't print anything.

Am I doing something wrong?

**Comment by Draconic-Hybrid** [comment]
> https://github.com/lunarcleint/Wednesdays-Infidelity (and you have to ask permission because I am pretty sure he made the code for that on PlayState).

Sorry, I should have mentioned that this is for Lua

**Comment by DabbinDude316B** [comment]
It’s actually just `campaignMisses`

**Comment by Draconic-Hybrid** [comment]
> It’s actually just `campaignMisses`

Still prints nothing...

**Comment by KutikiPlayz** [comment]
you sure it's not the way you're printing it that's the problem?
like do you have some wack if statement that isn't letting you print it or something

**Comment by Draconic-Hybrid** [comment]
It's literally just
```
function onBeatHit()
	if curBeat == 4 then
		debugPrint(campaignMisses)
	end
end
```

Did I somehow mess this up

**Comment by frantastic24** [comment]
```lua
getPropertyFromClass('PlayState', 'campaignMisses')
```

**Comment by Draconic-Hybrid** [comment]
> ```lua
> getPropertyFromClass('PlayState', 'campaignMisses')
> ```

It worked! Cool, but I thought `getPropertyFromClass()` was supposed to get something that WASN'T in PlayState. Is the documentation outdated, or?

**Comment by frantastic24** [comment]
It's for any class, the main purpose is for other classes but it also works for those rare cases where getProperty doesn't
I believe the difference is `getProperty()` treats PlayState as an instance which I think doesn't work with static vars

**Comment by Draconic-Hybrid** [comment]
I see. Thanks!
