### ISSUE TITLE
Icon Bounce Source Code

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#11267]
### Describe your problem here.

I was looking an icon bounce that I liked and I found it but I want that the script would be in the source code. If someone can help me to put the script to the source code I would appreciate it a lot.

Here is the script:
```
function onUpdatePost()
	setProperty("iconP1.scale.y", (getProperty("iconP1.scale.y") - 1) / -2 + 1)
	setProperty("iconP2.scale.y", (getProperty("iconP2.scale.y") - 1) / -1 + 1)
	setProperty("iconP1.y", 500 + (getProperty("iconP1.scale.y") * 75))
	setProperty("iconP2.y", 500 + (getProperty("iconP2.scale.y") * 75))
   
	if getPropertyFromClass('ClientPrefs', 'downScroll') == true then
	   setProperty("iconP1.y", -65 + (getProperty("iconP1.scale.y") * 75))
	   setProperty("iconP2.y", -65 + (getProperty("iconP2.scale.y") * 75))
	end
end
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
https://github.com/ItzEpicstickman/VsEvilCorruptedDaveDay3Final/blob/main/source/PlayState.hx

**Comment by GatoMorado621** [comment]
> https://github.com/ItzEpicstickman/VsEvilCorruptedDaveDay3Final/blob/main/source/PlayState.hx

Thanks but can you tell me in which line??? 😅😅

**Comment by TheKitBoi** [comment]
at 4078 to 4099
![image](https://user-images.githubusercontent.com/84044666/202868865-74888b60-e318-4f57-a630-a65f79e15293.png)

**Comment by GatoMorado621** [comment]
> at 4078 to 4099 ![image](https://user-images.githubusercontent.com/84044666/202868865-74888b60-e318-4f57-a630-a65f79e15293.png)

Ok so all of that I will put in the playstate.hx in any line, right???

**Comment by TheKitBoi** [comment]
yes

**Comment by GatoMorado621** [comment]
> yes

Thank You So Much ❤️❤️❤️❤️
