### ISSUE TITLE
Fade In

### ISSUE THREAD

**Issue by SeriouslyAnimations** [ShadowMario/FNF-PsychEngine#11264]
### What is your question?

I'm using the cameraFade function and there isnt a fade out function that i know of so how can i make the color fade back in

**Comment by CaptainBaldi** [comment]
cameraFade(camera:String, 'FFFFFF', duration:Float,forced:Bool)

**Comment by SeriouslyAnimations** [comment]
Sorry but it didn't work

**Comment by TheKitBoi** [comment]
Did u edit the code if not then
cameraFade(camHUD, 'FFFFFF', 1,0)

**Comment by SeriouslyAnimations** [comment]
It just turns white

**Comment by frantastic24** [comment]
You can't change whether it fades in or out, either use runHaxeCode or make a solid color graphic and tween its alpha for the same effect

**Comment by ZeitHeld** [comment]
Maybe you can try to tween the alpha of the cam?
(idk if the vars for the cam is correct though, and didn't test it, as I am checking if colortweens work)
first out
doTweenAlpha('bye',getProperty("camGame")',0,0.5,'linear)

then back in
doTweenAlpha('hi',getProperty('camGame'),1,0.5,'linear)
