### ISSUE TITLE
opponent offset

### ISSUE THREAD

**Issue by Gurudevsing** [ShadowMario/FNF-PsychEngine#11266]
### Describe your problem here.

   how do you add offsets for each individual animation? (like up, right, left, and down)

https://user-images.githubusercontent.com/87480185/202866961-9cc96f3e-7fef-4e66-9ac1-4dd4c1752337.mp4

![Screenshot (48)](https://user-images.githubusercontent.com/87480185/202866990-e8a78862-7e36-488b-937e-25d32827b53e.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
`addOffset('anim', X, Y)`

**Comment by CaptainBaldi** [comment]
> `addOffset('anim', X, Y)`

actually I believe it's
`addOffset('obj', 'anim', X, Y)`

**Comment by frantastic24** [comment]
![20221103_141534.jpg](https://user-images.githubusercontent.com/95725102/202873193-850c88c1-9398-4c49-9f23-ab2ac5eafbec.jpg)

My bad though fr

**Comment by Gurudevsing** [comment]
> > `addOffset('anim', X, Y)`
> 
> actually I believe it's `addOffset('obj', 'anim', X, Y)`


> `addOffset('anim', X, Y)`


![Screenshot (50)](https://user-images.githubusercontent.com/87480185/202889776-43d56775-5c33-4d9b-b3c7-9fdfeba5676e.png)


its not working 

here code
addOffset('Dad2','idle',100,50)
addOffset('Dad2','0',100,50)
addOffset('Dad2','1',100,50)
addOffset('Dad2','2',100,50)
addOffset('Dad2','3',100,50)

**Comment by frantastic24** [comment]
Remember to use `playAnim()`
#9330

**Comment by frantastic24** [comment]
> Variables with ? before it means it's an optional value

**Comment by Gurudevsing** [comment]
What about ,? reverse  and start frame. 

> > Variables with ? before it means it's an optional value
> 
> `forced` is just if you want it to restart the animation if it's already playing, otherwise set to false

**Comment by frantastic24** [comment]
Play animation reversed and start animation from X frame
If you don't know what they do, you probably do not need them

**Comment by Gurudevsing** [comment]
> Play animation reversed and start animation from X frame If you don't know what they do, you probably do not need them
I THINIK I MESSED UP EXAMPLE CODE PLEASE 
![Screenshot (53)](https://user-images.githubusercontent.com/87480185/203338132-b257f6a9-4fc1-420d-87de-6d83e347a7c7.png)

**Comment by frantastic24** [comment]
Case sensitivity

**Comment by frantastic24** [comment]
PlayAnim isn't a function, playAnim is

**Comment by Gurudevsing** [comment]
Do me a favor if you have example code for anim offset share with me  bro I am trying to fix that shit more than 3 dayss

Make me example code bro pls

**Comment by Gurudevsing** [comment]
> PlayAnim isn't a function, playAnim is

Do me a favor if you have example code for anim offset share with me bro I am trying to fix that shit more than 3 dayss
example code bro pls

**Comment by frantastic24** [comment]
I just told you what to change? You did everything right except you put uppercase where you aren't supposed to

**Comment by Gurudevsing** [comment]
> I just told you what to change? You did everything right except you put uppercase where you aren't supposed to

Thankss

**Comment by Gurudevsing** [comment]
> I just told you what to change? You did everything right except you put uppercase where you aren't supposi 

still cant move individual anim ,below video you can see i put addOffset('Dad2','1',0,-1000) it must be down somewhere but it remains same

when i put playAnim('Dad2','1',false) ,"1" IS THE ANIM tag of note down it moves entire x and y
 position of anim sprite


![Screenshot (55)](https://user-images.githubusercontent.com/87480185/203687924-ab34d81f-507f-4290-ad38-86335b95c764.png)

https://user-images.githubusercontent.com/87480185/203687902-482de4f8-6600-4fcc-9b8a-0d748f984a92.mp4

**Comment by frantastic24** [comment]
Show the full script

**Comment by Gurudevsing** [comment]
> Show the full script

![Screenshot (56)](https://user-images.githubusercontent.com/87480185/203724810-92de2397-9e0c-4eef-af45-9584ae22bb04.png)

**Comment by frantastic24** [comment]
You're using objectPlayAnimation, this function doesn't load offsets

**Comment by Gurudevsing** [comment]
> You're using objectPlayAnimation, this function doesn't load offsets

Than what do I need to do, do I need to replace objectPlayAnimation or delete that line

**Comment by Gurudevsing** [comment]
> You're using objectPlayAnimation, this function doesn't load offsets

Is this line is correct playanim('Dad2','hhh',false)

**Comment by frantastic24** [comment]
Replace them with playAnim obviously

**Comment by Gurudevsing** [comment]
> Replace them with playAnim obviously

Finally..........tnx
