### ISSUE TITLE
JSONI8 Support nonfunctional

### ISSUE THREAD

**Issue by RiftWings** [ShadowMario/FNF-PsychEngine#11278]
### Describe your bug here.

in Psych Engine v0.6.3, despite Aseprite JSONI8 support being added, an error occurs and the character does not load. used the example given by the creator of this feature (that was officially added) to make sure I wasn't just being a dumbass, but the error still occurred. the beginning and end of the stack error I was given, despite my efforts, do not appear to exist in the source code for that version of this engine. I then tried using the character I had created in their version of the engine, and it worked perfectly fine. Not sure exactly what went wrong.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Because it was never added

**Comment by ThatGuy099** [comment]
So ummm acktuaally according to my casllculations you are wrong!!🤓🤓
JSONI8 was added to 0.6.3 and there is two files in haxe langeuage called JSONdata.hx and AtlasFrameMaker.hx. 🤓
and thechniccly it was added. We just don't know how to use. according to the file "AtlasFrameMaker.hx" you can only use JSON data from adobe animate 2018 as its said here:
### 
	{
			PlayState.instance.addTextToDebug("Only Spritemaps made with Adobe Animate 2018 are supported", FlxColor.RED);
			trace("Only Spritemaps made with Adobe Animate 2018 are supported");
			return null;
		}
		
I don't know why tho.

**Comment by frantastic24** [comment]
Not the same thing at all

**Comment by ShadowMario** [comment]
There is no JSONI8 support.
