### ISSUE TITLE
VS Dave Icon Bounce

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#11271]
### Describe your problem here.

I have been looking the lines and the code for put the icon bounce of the mod. Is not like a bounce is like a jump of the icon. Like the icon gets smalle instantly and then gets to the normal size. Look for that if you don't know what it is. Well the point is if someone can help me finding or saying the code for that bounce. If you help me I would appreciate it a LOT!!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Ctrl + F and just look for any lines that affect iconP1/2, it should not be that difficult

**Comment by GatoMorado621** [comment]
> Ctrl + F and just look for any lines that affect iconP1/2, it should not be that difficult

Ok but in the Vs Dave source code???

**Comment by GatoMorado621** [comment]
> Ctrl + F and just look for any lines that affect iconP1/2, it should not be that difficult

Look I have this script and also I want to put that code to the source code, obviosly being able to compiling:
```
function onUpdatePost()
	setProperty("iconP1.scale.y", (getProperty("iconP1.scale.y") - 1) / -2 + 1)
	setProperty("iconP2.scale.y", (getProperty("iconP2.scale.y") - 1) / -1 + 1)
	setProperty("iconP1.y", 500 + (getProperty("iconP1.scale.y") * 75))
	setProperty("iconP2.y", 500 + (getProperty("iconP2.scale.y") * 75))
   
	if getPropertyFromClass('ClientPrefs', 'downScroll') == true then
	   setProperty("iconP1.y", -65 + (getProperty("iconP1.scale.y") * 75))
	   setProperty("iconP2.y", -65 + (getProperty("iconP2.scale.y") * 75))
	end
end
```

**Comment by frantastic24** [comment]
You already have all the values there, all you have to do is get rid of the Lua callbacks

**Comment by GatoMorado621** [comment]
> You already have all the values there, all you have to do is get rid of the Lua callbacks

Ok... and which are the Lua callbacks???...

**Comment by GatoMorado621** [comment]
> You already have all the values there, all you have to do is get rid of the Lua callbacks

Can you pls answer me????

**Comment by CaptainBaldi** [comment]
this is why you dont give d&b fans source code

**Comment by GatoMorado621** [comment]
> this is why you dont give d&b fans source code

Look dude, I was all day looking for the script because I like that bounce and actually I am looking for it.

**Comment by GatoMorado621** [comment]
> > > this is why you dont give d&b fans source code
> > 
> > 
> > Look dude, I was all day looking for the script because I like that bounce and actually I am looking for it.
> 
> https://github.com/MoldyGH/VsDave , shut the fuck up and go to playstate and search for "FlxTween.tween(iconP1 "

I cannot find it...
I just find FlxTween.tween(iconP2 but disapear the icons

**Comment by Jevilm** [comment]
https://discord.com/channels/922849922175340586/1023712921357918299/threads/1038080755206725663

**Comment by TheKitBoi** [comment]
join the psych discord server
https://discord.gg/2ka77eMXDv
