### ISSUE TITLE
drag selection and multi note replacement

### ISSUE THREAD

**Issue by 4wdthinks** [ShadowMario/FNF-PsychEngine#1127]
### What feature do you want to get added on the base engine?

sometimes when charting, i accidentaly use a note type i dont want to and/or i want to replace a whole section's notes quickly.
so i present **drag selection.**

it allows you to use right click to drag over an area of notes/event notes and select all the notes inside the selection box. from there you can easily replace many notes at once.

**Comment by ShadowMario** [comment]
I don't wanna do it, i'm clearly busy with better stuff now
