### ISSUE TITLE
Stage Error

### ISSUE THREAD

**Issue by MaIfunctional** [ShadowMario/FNF-PsychEngine#11276]
### Describe your problem here.

![Screenshot (385)](https://user-images.githubusercontent.com/99407501/202908928-e3cca51b-44e3-49ab-805f-2ddf837a8dd3.png)
I tried to add a custom stage here, but whenever I try to load in the custom stage this error message pops up and crashes PsychEngine. What can I do about this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I tried to add a stage new custom stage with the example lua and json files.

**Comment by frantastic24** [comment]
Duplicate of several other issues
You are using an event hardcoded to a specific stage

**Comment by MaIfunctional** [comment]
Is there any way I could fix that?

**Comment by MaIfunctional** [comment]
Nevermind, I found the issue. I replaced the blammed with my stage and that was causing the error. I couldn't do week 1 because it kept crashing every time I loaded it but everything is fixed now.
