### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by EricWasTakenWasTaken** [ShadowMario/FNF-PsychEngine#11279]
### Describe your bug here.

whenever i try to build the game, i get thrown some errors

### Command Prompt/Terminal logs (if existing)

```bash
source/Main.hx:85: characters 61-65 : Float should be Int                                                               source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'                              source/Main.hx:85: characters 61-65 : ... For function argument 'child'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by EricWasTakenWasTaken** [comment]
nvm fixed it

**Comment by AphmauFan2010** [comment]
> nvm fixed it

how did you fix this? I'm having the sam issue.

**Comment by Heropowerbrine** [comment]
Same error here, it's also happening on any other engine I try to compile with, even though the compiling was working absolutely fine yesterday, how did you fix it
