### ISSUE TITLE
Game crashes halfway into some of my songs (v0.6.3)

### ISSUE THREAD

**Issue by Minecrafter615** [ShadowMario/FNF-PsychEngine#11273]
### Describe your bug here.

I load into a song using the debug editor, begin playing it, and the game will crash without an error or anything to signal it. This tends to happen in the same spot in the song(s), though varies by maybe a second or two. I know for certain this is not caused by any script I've made or custom notetype/event as there are none in the specific song, and none were in the scripts folder.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, this is all base v0.6.3

**Comment by Minecrafter615** [comment]
nevermind i'm stupid there WAS a script thing going on

**Comment by Noel3454565FNF** [comment]
can you tell me what type of script is it? what is inside pls i have the same issue
