### ISSUE TITLE
just something

### ISSUE THREAD

**Issue by Cap6ailB3an** [ShadowMario/FNF-PsychEngine#11270]
### What feature do you want to get added on the **base** engine?

Hi there i would love it if you could change the LUA script api downloads just bc I cant go on Discord and its blocked by Malwarebytes.

It would be a big help!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
Solution: open Google and search how to disable an antivirus

**Comment by CaptainBaldi** [comment]
most of the downloads are broken anyway
