### ISSUE TITLE
Creating a Event

### ISSUE THREAD

**Issue by rbrtmappjr** [ShadowMario/FNF-PsychEngine#11289]
### Describe your problem here.

When I'm trying to get the Example Event script I can't get it for somehow it keeps showing this screen
![chrome_S6Fy0G9W65](https://user-images.githubusercontent.com/116595732/203158797-a99adda3-200c-4f29-93b3-69ec1d2055bc.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Mokona5901** [comment]
> ### Describe your problem here.
> 
> When I'm trying to get the Example Event script I can't get it for somehow it keeps showing this screen
> 
> ![chrome_S6Fy0G9W65](https://user-images.githubusercontent.com/116595732/203158797-a99adda3-200c-4f29-93b3-69ec1d2055bc.png)
> 
> ### Are you modding a build from source or with Lua?
> 
> Lua
> 
> ### What is your build target?
> 
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> 
> No

Broken download, we can't do anything, except maybe asking to ShadowMario to put another link

**Comment by rbrtmappjr** [comment]
OK

**Comment by TheKitBoi** [comment]
close this issue
![close the dam issue](https://user-images.githubusercontent.com/84044666/203426208-52b5a821-5560-4bb9-b99f-938a0c1ab77c.gif)

**Comment by Mokona5901** [comment]
Agreed
