### ISSUE TITLE
Shaders, again

### ISSUE THREAD

**Issue by Thimque** [ShadowMario/FNF-PsychEngine#11280]
### Describe your problem here.

_God its like I cant do shaders right-_
So im trying to this shader to work https://www.shadertoy.com/view/ldXGW4
but im just having to many issues and am not having a good time. If there is any way I can add shaders easier or if there's some website I can go to to walk me thru adding shaders of any kind or a website with shaders for Psych please do tell me im not having fun.
If someone could just turn the code from the shader link into a usable shader for Psych that would be great, thank you!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not.

**Comment by Mokona5901** [comment]
Simple shader tutorial from Captain Baldi : https://gamebanana.com/tuts/15316
Don't forget to add this into your song code because it's an animated shader (this may decrease game performance on slow PCs): 
```
function onUpdate()
   setShaderFloat('theBackGround', 'iTime', os.clock())
end
```
I tested and it's works.

btw it's to put shader on a _sprite_, if it's for camGame I have no clue.

**Comment by Thimque** [comment]
> Simple shader tutorial from Captain Baldi : https://gamebanana.com/tuts/15316 Don't forget to add this into your song code because it's an animated shader (this may decrease game performance on slow PCs):
> 
> ```
> function onUpdate()
>    setShaderFloat('yourSprite', 'iTime', os.clock())
> end
> ```
> 
> I tested and it's works.
> 
> btw it's to put shader on a _sprite_, if it's for camGame then I have no clue.

Well that got rid of ONE issue, now theres another. So, now it doesnt give me any errors, good. But now it wont load so idk wtf i did lmao

**Comment by Mokona5901** [comment]
> > Simple shader tutorial from Captain Baldi : https://gamebanana.com/tuts/15316 Don't forget to add this into your song code because it's an animated shader (this may decrease game performance on slow PCs):
> 
> > 
> 
> > ```
> 
> > function onUpdate()
> 
> >    setShaderFloat('yourSprite', 'iTime', os.clock())
> 
> > end
> 
> > ```
> 
> > 
> 
> > I tested and it's works.
> 
> > 
> 
> > btw it's to put shader on a _sprite_, if it's for camGame then I have no clue.
> 
> 
> 
> Well that got rid of ONE issue, now theres another. So, now it doesnt give me any errors, good. But now it wont load so idk wtf i did lmao

What type of errors you got ?
If you want I can give you the code.
