### ISSUE TITLE
Rotating Problem

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#11282]
### Describe your problem here.

So I was doing that a luaSprite rotate when the opponent sings like in Gospel. Here is the code:
```
function opponentNoteHit(id, direction, noteType, isSustainNote)
	setProperty('circulo1.angle', 10)
end
```
But the problem is that when it runs the Sprite dosen't rotate just moves to the direction I put (number).
If someone can help I really appreciate it a lot

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by DisIsNOt** [comment]
function opponentNoteHit(id, direction, noteType, isSustainNote)
        setProperty('circulo1.angle', getProperty('circulo.angle) + 10)


end

 may be

**Comment by GatoMorado621** [comment]
> function opponentNoteHit(id, direction, noteType, isSustainNote) setProperty('circulo1.angle', getProperty('circulo1.angle) + 10)
> 
> end

Yes it works but when it starts rotating it dosen't stay in the same place and I want that is in the same place

**Comment by DisIsNOt** [comment]
I thought that only changes it's angle not the position lmao
