### ISSUE TITLE
Can I call a function that is in PlayState.hx with lua script?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#1128]
### What is your question?

There are many variables and functions in `PlayState.hx`, 
the wiki said:

>getProperty(variable:String)
>Returns a current variable from PlayState's name.
>It can also be used to get the variable from an object that is inside PlayState or a Lua Sprite.
>Example: If you wanted to get the current health's value, you should use getProperty('health').
>Example 2: If you'd want to get Boyfriend's current character, you should use getProperty('boyfriend.curCharacter')

from: https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Value-Setting-and-Getting-Functions

Question:
Can I call a function that is in PlayState.hx with lua script?

**Comment by KlavierGayming** [comment]
you cant.
