### ISSUE TITLE
Note type miss animation

### ISSUE THREAD

**Issue by Troystar23** [ShadowMario/FNF-PsychEngine#11286]
### Describe your problem here.

So essentially I've made a note type that has a goodnotehit section where it will play animations corresponding to a note when it is hit. duh. which works fine but on function notemiss I was planning to have a miss animation for if u dont hit the note but rather than playing this custom miss animation that i intended it plays the default ones. The way I have written it was as a trigger event play anim 'anim name' for bf, but it wont play because its being cancelled out by the default miss anim rather than this custom one (Another thing to clarify is that i want this custom miss only on if u miss this notetype so changing bfs miss animations will not solve the issue)

If you need any more information to figure out what im even talking about or any clarification please ask away im struggling to think of a way around this and any help is appreciated :)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Notes have `noMissAnimation` and `animSuffix` vars you can use

**Comment by Troystar23** [comment]
so in the note miss function could I just add a set property 'noMissAnimation' to true and that would remove the miss anims?

**Comment by Troystar23** [comment]
ah thanks for that I placed it under my oncreate function and it seems to be working now
