### ISSUE TITLE
5k similar to death toll

### ISSUE THREAD

**Issue by TurtleFanCoder** [ShadowMario/FNF-PsychEngine#11287]
### Describe your problem here.

Is there a way to add 5k similar to death toll (a middle button that plays a custom animation when hit) with lua scripts?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No I did not.

**Comment by Grape-Boy** [comment]
There's a script that adds multi-key support in the Psych Engine Discord Server

**Comment by TurtleFanCoder** [comment]
Can i make it do custom animations

**Comment by TheKitBoi** [comment]
yes if you know what your doing

**Comment by TurtleFanCoder** [comment]
ok thanks
