### ISSUE TITLE
Gospel Background

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#11281]
### Describe your problem here.

So I was making my background until I thougth that I want a background that when the opponent or the player sings the background rotate but I don't know how to do it. If someone can help me I will appreciate it a lot.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
`setProperty('obj.angle', angle)`

**Comment by GatoMorado621** [comment]
> 

Ok, so 'obj.angle' is suppose to be the object. And the 'angle' is the angle that it will be rotating, right???

**Comment by frantastic24** [comment]
Should be straightforward enough yes
`angle` is the value it will be set to

**Comment by GatoMorado621** [comment]
> Should be straightforward enough yes `angle` is the value it will be set to

Ok, thank you so much
