### ISSUE TITLE
How to make opponents health bar color change when they're in danger? (AKA when they're danger/death icon is showing)

### ISSUE THREAD

**Issue by luigiman0** [ShadowMario/FNF-PsychEngine#11296]
### What is your question?

Is there any way using a lua script to change an opponents health bar color while they're death icon is showing?

**Comment by Gostar64** [comment]
> 

I think it should be
```lua
if getProperty('health') >= 1.6 then
```
instead of if rating >= 0.8, since they're talking about the opponents death icon

**Comment by luigiman0** [comment]
![image](https://user-images.githubusercontent.com/113739072/203882698-f8bafc5f-ae74-416f-8393-f5425aa49dc7.png)
Tried using the first script by Mokona5901 with the "if" thing Gostar64 made, but I keep getting this error. How do I fix this?

**Comment by Mokona5901** [comment]
> ![image](https://user-images.githubusercontent.com/113739072/203882698-f8bafc5f-ae74-416f-8393-f5425aa49dc7.png) Tried using the first script by Mokona5901 with the "if" thing Gostar64 made, but I keep getting this error. How do I fix this?

Did you replaced `leftHex:String` by someting like `'000000'` for black ?
(I hope you didn't wrote something like `leftHex:'000000'`)

**Comment by Mokona5901** [comment]
> > 
> 
> I think it should be
> 
> ```lua
> if getProperty('health') >= 1.6 then
> ```
> 
> instead of if rating >= 0.8, since they're talking about the opponents death icon

Idk I think rating goes from 0 (death) to 1

**Comment by Mokona5901** [comment]
Wait I'm dumb, rating is different of health, so I think Gostar64 is right if health goes from 0 to 2

**Comment by luigiman0** [comment]
> > ![image](https://user-images.githubusercontent.com/113739072/203882698-f8bafc5f-ae74-416f-8393-f5425aa49dc7.png) Tried using the first script by Mokona5901 with the "if" thing Gostar64 made, but I keep getting this error. How do I fix this?
> 
> Did you replaced `leftHex:String` by someting like `'000000'` for black ? (I hope you didn't wrote something like `leftHex:'000000'`)

I did try writing leftHex:000000 lmao

gonna try not doing that and see if it fixes it

**Comment by luigiman0** [comment]
`function onUpdate(elapsed)
if getProperty('health') >= 1.6 then
setHealthBarColors('opponenthex', 'bfhex')
end
if getProperty('health') <= 1.6 then
setHealthBarColors('opponenthex', 'bfhex')
end
end`

This is the final script I came up with, using a combination of the previous scripts, as well as the new info Mokona added.
Replace opponenthex and bfhex with the hex codes for the colors you want.

First part is for when the death icon is showing, and the second part is for when it's not.
