### ISSUE TITLE
No-Appear image

### ISSUE THREAD

**Issue by BAMBFAN** [ShadowMario/FNF-PsychEngine#11291]
### Describe your bug here.

I tried to import a character to the editor, but when i select my new character, the image is remplaced by the logo of the fnf team "i think", please help!!

### Command Prompt/Terminal logs (if existing)

```bash
Import the spritesheet and xml, imported the json, select the character in the fnf editor, IMAGE DOESNT APPEAR
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, Just added the new character stuff.

**Comment by DisIsNOt** [comment]
Your character's image doesn't in the right path may be
