### ISSUE TITLE
Dad in front of Boyfriend

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#1129]
### What is your question?

How can I make dad be infront of boyfriend when dad sings 
and boyfriend be in front of dad when boyfriend sings?
(Source Code)

**Comment by MayoALT** [comment]
![image](https://user-images.githubusercontent.com/94536972/142629680-f6eee1c3-decd-48c7-b970-97d24772d25b.png)
around this area after the stage code make a switch statement that changes which order the characters are added per stage or character

**Comment by lemz1** [comment]
sorry I probably should have been much clearer I want to make it so if dad sings he is in front of boyfriend and if boyfriend sings boyfriend is in front of dad.

**Comment by Owen-sys** [comment]
you can change the global character offsets of the character in the character editor menu. I did a similar thing with bf in a duet cover. As seen in this: https://www.youtube.com/watch?v=OzP2BKnnIeM

**Comment by lemz1** [comment]
with infront of I meant the layer not the position
changing the offset doesn't make boyfriend be infront of dad

**Comment by ShadowMario** [comment]
To get dad behind boyfriend:
```haxe
remove(dadGroup);
insert(members.indexOf(boyfriendGroup), dadGroup);
```

To get boyfriend behind dad:
```haxe
remove(boyfriendGroup);
insert(members.indexOf(dadGroup), boyfriendGroup);
```
