### ISSUE TITLE
Time Bar Color

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#11290]
### Describe your problem here.

So I was trying to put the timebar color depending of the color of the week but I don't know how. Here is something that I was trying:
![Captura FNF Source Code](https://user-images.githubusercontent.com/116233921/203164946-ed30f9d4-4a56-4a7c-9b21-7a0ffd46858e.png)

If someone can help me with this I really appreciate it a lot

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Minalog** [comment]
you might wanna add 0xFF000000 before the FlxColor bullshit

**Comment by GatoMorado621** [comment]
> you might wanna add 0xFF000000 before the FlxColor bullshit

So what are you saying is that i need to put the first color and then the code that I put in the image???

**Comment by GatoMorado621** [comment]
> 

It didn't work :(
