### ISSUE TITLE
Compiling now giving errors

### ISSUE THREAD

**Issue by Heropowerbrine** [ShadowMario/FNF-PsychEngine#11292]
### Describe your bug here.

This bug had begun showing up yesterday, and it is still not fixed
Basically Main.hx now has some issues that is preventing the game from even compiling at all, even when no changes have been made to it
I had compiled a generated repo of Psych Engine two days ago with no errors, so when I tried again yesterday after I found this bug on a different engine it could not compile due to this same error
This does not only affect Psych Engine, but other FNF engines as well
If anyone knows a fix, please let us know

### Command Prompt/Terminal logs (if existing)

```bash
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing has been edited, it could compile normally before yesterday

**Comment by frantastic24** [comment]
This was caused by a haxe update, `zoom` is no longer used

**Comment by Heropowerbrine** [comment]
> This was caused by a haxe update, `zoom` is no longer used

Ah ok, thanks for your help!

**Comment by PDL2CGamejolt** [comment]
I also get this error

**Comment by PDL2CGamejolt** [comment]
> This was caused by a haxe update, `zoom` is no longer used

How do I remove the zoom

**Comment by PDL2CGamejolt** [comment]
Wait, I think I got it

**Comment by realShanDev** [comment]
> Wait, I think I got it

how did you fix it?
