### ISSUE TITLE
Dialogue Not Showing Up.

### ISSUE THREAD

**Issue by FuseIsHere813** [ShadowMario/FNF-PsychEngine#113]
Pretty same some have this same issue, but when I added the dialogue.json and script.lua, it goes straight to the song. Any reason why?

**Comment by FuseIsHere813** [comment]
By the way, i am using the downloaded build.

**Comment by FuseIsHere813** [comment]
i assigned it to the song "bopeebo", using the example @ShadowMario gave out.

**Comment by FuseIsHere813** [comment]
but still no luck, try restarting, doesn't work.

**Comment by FuseIsHere813** [comment]
Ehhh, i will just use source code since lua is having problem. Case C L O S E D.

**Comment by FuseIsHere813** [comment]
Reopening this because the dialogue lua script needs a fix to detect and load the shit. :grief:

**Comment by ShadowMario** [comment]
No it doesn't? The script works perfectly on my end

**Comment by FuseIsHere813** [comment]
Must be an issue on my end. Will close this for now to test the script on the recent version of the engine.

**Comment by FuseIsHere813** [comment]
Reopening this shit again, my end kept having issues even on the recent version. :grief:

**Comment by FuseIsHere813** [comment]
By the way, tried downloading new example script in a simliar issue, did NOT work. So yeah.

**Comment by ShadowMario** [comment]
So you're doing something wrong then, yeah.

Place both the dialogue.json file and the script.lua file from the example in the same folder, the chart's data folder: `mods/data/your-song-name/`

**Comment by FuseIsHere813** [comment]
I am going to see if that helped.

**Comment by TonyRonii** [comment]
omg thank you so much it's working now

**Comment by FuseIsHere813** [comment]
Got the issue fixed. Thanks.
