### ISSUE TITLE
stupid menu idea + more stuff

### ISSUE THREAD

**Issue by Aidenkp112** [ShadowMario/FNF-PsychEngine#11306]
### Describe your problem here.

so i have stupid plan for my mod and guess who thought they could make the menu perfectly fine? (absolutely dumb)
so yeah i have concepts for menus

**MAIN MENU CONCEPT:**
![concept for menus](https://user-images.githubusercontent.com/108594286/203886015-a1d32d87-c6c1-4d03-adc5-34c0e4464be5.png)

**FREEPLAY CONCEPT:**
![concept for freeplay](https://user-images.githubusercontent.com/108594286/203886708-0f5a215b-01c5-4036-9beb-ef2115cefdaa.png)

**WEEK CONCEPT:**
![concept for weeks](https://user-images.githubusercontent.com/108594286/203887707-6be8d4df-da74-4a38-ab25-9153000abdfd.png)

i kinda rushed these so uh yeah
i would like code to paste (sounds greedy i know) and if it is a bit wrong then i'll fix it myself

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
> ### Describe your problem here.
> so i have stupid plan for my mod and guess who thought they could make the menu perfectly fine? (absolutely dumb) so yeah i have concepts for menus

> i kinda rushed these so uh yeah i would like code to paste (sounds greedy i know) and if it is a bit wrong then i'll fix it myself

what ar u doing with your life
you think this is an fnf help wanted request repo

**Comment by Aidenkp112** [comment]
my iq for coding is coffee table tbh
