### ISSUE TITLE
Week 7 Styled Cutscenes

### ISSUE THREAD

**Issue by Nork1234** [ShadowMario/FNF-PsychEngine#11307]
### What is your question?

Is there any way to make cutscenes like in week 7? What I mean by this is that the week 7 cutscenes are not videos, but the assets playing the animation in game. Can I make cutscenes like this myself, and how?

**Comment by Grape-Boy** [comment]
[look at this function](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/PlayState.hx#L1768)
