### ISSUE TITLE
A Little Lua Convenience

### ISSUE THREAD

**Issue by ItsIsaacIO** [ShadowMario/FNF-PsychEngine#11300]
### What feature do you want to get added on the **base** engine?

I'm not sure if I'm stupid and can't find any documentation or code anywhere in the engine for this, but can you add a TweenValue or something to lua scripts? It would be really nice instead of making my own tween code or using runHaxeCode to do it. Thanks!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Draconic-Hybrid** [comment]
[Documentation has a "Show 3 more pages" button at the bottom of the Table of Contents.](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers)
