### ISSUE TITLE
Failure in compiling

### ISSUE THREAD

**Issue by Superlogan321** [ShadowMario/FNF-PsychEngine#11309]
### Describe your problem here.

im Modding the psych engine but even if i try to compile with no edits it still fails can someone help
heres the error:
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
source/CreditsState.hx:85: characters 6-16 : Expected , or ]

the credits state look like this:
['Superlogan Covers Team]
			['Superlogan',			'superlogan',		'Main Reprogrammer skinner remixer creator of the mod'			'https://twitter.com/logan_bissett',	'444444'],

main menu states fine it isnt included in the error

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

MainMenuState.hx, CreditsState.hx

**Comment by GamingFan3926** [comment]
For CreditsState.hx, change "['Superlogan Covers Team]" to "['Superlogan Covers Team'],". 

Then, change

"['Superlogan', 'superlogan', 'Main Reprogrammer skinner remixer creator of the mod' 'https://twitter.com/logan_bissett', '444444'],"

to

"['Superlogan', 'superlogan', 'Main Reprogrammer skinner remixer creator of the mod', 'https://twitter.com/logan_bissett', '444444'],"

For MainMenuState.hx, it is possible that you are simply using the wrong version of flixel. simply type these commands in Command Prompt in the following order:

haxelib remove flixel
haxelib install flixel 4.11.0

**Comment by Superlogan321** [comment]
Thanks

**Comment by Superlogan321** [comment]
i tried what you did and it worked but know it says im missing a ] when i dont think its supposed to be there 
![image](https://user-images.githubusercontent.com/110323819/204067769-a80120f3-b764-4b66-8342-018aa2a242e2.png)

**Comment by Superlogan321** [comment]
![image](https://user-images.githubusercontent.com/110323819/204067995-6699833a-bb25-43fe-b542-a324c4980e91.png)
