### ISSUE TITLE
How to check if opponent is playing an alt animation

### ISSUE THREAD

**Issue by PlasmaOJ15** [ShadowMario/FNF-PsychEngine#11305]
### Describe your problem here.

I'm trying to make an animation of an object play only when the opponent hits an alt animation. I can get it to work, but only when the note itself is an alt animation, and not when the 'play alt animation' box is checked. How can I set it to also play when the 'play alt animation' box is checked?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
`altAnim`
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Variables#gameplay-variables

**Comment by PlasmaOJ15** [comment]
I'm trying to implement that, but it still isn't working, but only for the altAnim variable
Is this how to correctly make the if statement:
`if getProperty('altAnim') == true or noteType == 'Alt Animation' then`

**Comment by frantastic24** [comment]
You don't use getProperty, it's a shortcut

**Comment by Mokona5901** [comment]
so its just `if altAnim == true or noteType == 'Alt Animation' then` to be clear

**Comment by frantastic24** [comment]
`== true` is redundant but yes
