### ISSUE TITLE
Bruh My Custom Stage Crashed

### ISSUE THREAD

**Issue by ElPro7777** [ShadowMario/FNF-PsychEngine#11303]
### Describe your bug here.

Why And Also I am using 0.6.2 because you all know why the 0.6.3 32x bits build is fake

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
Character.hx (line 164)
PlayState.hx (line 912)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I Add A custom Lua Stage

**Comment by frantastic24** [comment]
Not a bug
Gf character is missing texture files

**Comment by ElPro7777** [comment]
oh

**Comment by ElPro7777** [comment]
STILL

**Comment by frantastic24** [comment]
Don't reopen, this isn't a problem with the game

**Comment by ElPro7777** [comment]
i tryed changing gf with the default one and still

**Comment by ElPro7777** [comment]
i think is a problem with the lua script (because i am a idiot)

**Comment by ElPro7777** [comment]
Well so i will try to code the stage again (why)
