### ISSUE TITLE
Shaking Camera Substitute

### ISSUE THREAD

**Issue by KacperOSM** [ShadowMario/FNF-PsychEngine#1131]
### Describe your problem here.

How can I make the substitute, so I won't have to use the Default Shaking Camera Event?

Here are the problems (maybe) that I've seen occur:

1. There is no way to control whenever it should end, it's only the duration in seconds

2. If I pause during the song, the camera still shakes, and the camera will stop shaking earlier when at the end of the song meaning it will still play the effect even if it is paused or not

I'm not sure how I can achieve the effect with the pausing (like if you pause the song, the shake would stop until you unpause it) and how can I make it so that when the Current Beat is set, it would just disable or remove the effect.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

**Comment by SrtHero278** [comment]
What do you need a substitute for?

**Comment by ShadowMario** [comment]
> There is no way to control whenever it should end, it's only the duration in seconds

Make a timer with the same duration as the screen shake duration, wasn't that obvious enough?
