### ISSUE TITLE
how can i make dad look over boyfriend? (yes, i'm not english)

### ISSUE THREAD

**Issue by AssasinShadows** [ShadowMario/FNF-PsychEngine#11316]
### Describe your problem here.

how can i make dad look over boyfriend like they look over gilrfriend,How do I change the order?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Gostar64** [comment]
It should be
```Lua
function onCreatePost()
       setObjectOrder('bf', getObjectOrder('dadGroup) + 1)
end
```

If that doesn't work, replace bf with bfGroup

**Comment by AssasinShadows** [comment]
> 

hmm it doesn't work

**Comment by frantastic24** [comment]
It's `boyfriendGroup`

**Comment by AssasinShadows** [comment]
> It's `boyfriendGroup`

thanks, it works
