### ISSUE TITLE
Shader help

### ISSUE THREAD

**Issue by Guranlikesblue** [ShadowMario/FNF-PsychEngine#11310]
### Describe your problem here.

I tried to use Shader by frag file referring to this >> #11067, https://gamebanana.com/tuts/15316
but couldn't. Error appeared.
Error is `ERROR (onCreatePost): assets/data/souls/script.lua:12: attempt to call global 'initLuaShader' (a nil value)` and `ERROR (onUpdate): assets/data/souls/script.lua:28: attempt to call global 'setShaderFloat' (a nil value)`

code used is
```
function onCreatePost()
	luaDebugMode = true
	initLuaShader("glitch")

	makeLuaSprite("shaderImage")
	makeGraphic("shaderImage", screenWidth, screenHeight)

	setSpriteShader("shaderImage", "glitch")

	addHaxeLibrary("ShaderFilter", "openfl.filters")
	runHaxeCode([[
		trace(ShaderFilter);
		game.camGame.setFilters([new ShaderFilter(game.getLuaObject("shaderImage").shader)]);
		game.camHUD.setFilters([new ShaderFilter(game.getLuaObject("shaderImage").shader)]);
	]])
end

function onUpdate(elapsed)
	setShaderFloat("shaderImage", "iTime", os.clock())
end
```

Please help me about this

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

winning icons in PlayState.hx.

**Comment by Mokona5901** [comment]
show shader code

**Comment by Grape-Boy** [comment]
are you sure you have a build with shaders implemented?

**Comment by Guranlikesblue** [comment]
> are you sure you have a build with shaders implemented?

Hmm... Maybe no

**Comment by Guranlikesblue** [comment]
> Error is ERROR `(onCreatePost): assets/data/souls/script.lua:12: attempt to call global 'initLuaShader' (a nil value)` and `ERROR (onUpdate): assets/data/souls/script.lua:28: attempt to call global 'setShaderFloat' (a nil value)`

This was fixed, but another error appeared
undefined

**Comment by Guranlikesblue** [comment]
This problem solved
