### ISSUE TITLE
errors during compiling

### ISSUE THREAD

**Issue by jan-doez-animationz** [ShadowMario/FNF-PsychEngine#11319]
### Describe your problem here.

i get this error 
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
idk what to do

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by Nightmare-boyfriend** [comment]
I got the same problem too but i just got it to compile now 
try deleting all the commands and install them make sure you install haxelib install hxCodec and haxelib install newgrounds command then install haxelib install flixel 4.11.0 and try run this command also haxelib run lime setup flixel I hope this works.

**Comment by Nightmare-boyfriend** [comment]
then lime rebuild extension-webm <platfrom> and i close it and reopen it again and do 'lime test'.

**Comment by frantastic24** [comment]
or just follow #11301 or #11299

**Comment by Nightmare-boyfriend** [comment]
well that's how i do it.

**Comment by frantastic24** [comment]
Not having to reinstall everything is better I'd say

**Comment by Foxy-Studio** [comment]
i got it too here is why i think
https://github.com/ninjamuffin99/Funkin/issues/2075#issuecomment-1328207952

**Comment by jan-doez-animationz** [comment]
new error bruuhhh moment 
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

**Comment by frantastic24** [comment]
That's not an error

**Comment by Mokona5901** [comment]
this is just a warning, this doesn't stop you from compiling

**Comment by jan-doez-animationz** [comment]
oh

**Comment by jan-doez-animationz** [comment]
then what do i do??????

**Comment by jan-doez-animationz** [comment]
why does it open a random website that has a haxeflixel  thingy that doesnt work

**Comment by Mokona5901** [comment]
html5 build ?

**Comment by jan-doez-animationz** [comment]
prob but it doesnt work it just shows the haxeflixel loading screen then fades to black
