### ISSUE TITLE
Is there a way to get the "height" of a lua object

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#11325]
### Describe your problem here.

So is there a way to find out how "tall" the object is, ie, if i were to add the object's y value and its "height" , i'd get the position of the bottom of it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
https://api.haxeflixel.com/flixel/FlxSprite.html

**Comment by wubbzyfan** [comment]
thank
