### ISSUE TITLE
How to operate the mouse when playing the game with mouse?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#1132]
### What is your question?

There is a script  "Play with your Mouse instead of Arrow Keys"   in the wiki.
![image](https://user-images.githubusercontent.com/13177997/142592572-2f38c885-ad9f-4714-8b3d-0173f869fc10.png)

from  https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API

Question:
I put the `script.lua` file in the chart folder. Then how to operate the mouse?

**Comment by ShadowMario** [comment]
Why are you even make duplicates????
