### ISSUE TITLE
Uncaught error: Null object reference 

### ISSUE THREAD

**Issue by vesel4ak** [ShadowMario/FNF-PsychEngine#11326]
### Describe your bug here.

well this bug appears during song that i put in "mods" folder in psych engine. who knows how to fix this bugggggggggggg
![Снимок экрана 2022-11-27 124957](https://user-images.githubusercontent.com/119149152/204119941-a976c57c-9a2c-47fa-aece-95e17b045aa6.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Not a bug
Note texture is missing sustain end animations

**Comment by vesel4ak** [comment]
> 

then what should i do

**Comment by frantastic24** [comment]
Add them to your note texture

**Comment by vesel4ak** [comment]
> Add them to your note texture

kk

**Comment by frantastic24** [comment]
You can close the issue

**Comment by vesel4ak** [comment]
I DIDNT GET THIS

**Comment by TheKitBoi** [comment]
and why
