### ISSUE TITLE
Fnf covers

### ISSUE THREAD

**Issue by Thecoolgamer6745** [ShadowMario/FNF-PsychEngine#11321]
### What is your question?

Is there an easy way to make midis like a .json to midi or mp3 to midi or do i have to make it by hand?

**Comment by TheKitBoi** [comment]
no

**Comment by CaptainBaldi** [comment]
This is not related to Psych Engine

**Comment by bruh1cat** [comment]
Not related to psych but try searching up Midi2fnf or just find the original song and use that chart since it's a cover.

**Comment by bruh1cat** [comment]
Close this
