### ISSUE TITLE
Not Enough Arguments

### ISSUE THREAD

**Issue by FrogB** [ShadowMario/FNF-PsychEngine#11327]
### Describe your problem here.

When compiling the game, I get this error:

source/PlayState.hx:166: characters 55-72 : Not enough arguments, expected waveSpeed:Float, waveFrequency:Float, waveAmplitude:Float

Do you guys know a fix to this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Attempting to add eyesores, as well as a NPS counter in Playstate.hx

**Comment by browhycanthishappemn** [comment]
i think your trying to import wavy bgs, i think u have to stick to 0.4.2 to 0.5.1 (try 0.5.2/h)
