### ISSUE TITLE
Remove opponent arrow glow

### ISSUE THREAD

**Issue by SteveeTheCreeper** [ShadowMario/FNF-PsychEngine#11329]
### What is your question?

Hello
I just wanna know how to remove opponent arrow glow like in base game and kade engine using Lua scripts
And I don't mean the "sick" and "good" or the splash stuff
I mean when the arrows itself glow when it's the opponent turn

**Comment by TheRealJake12** [comment]
I don't think you can. You can easily remove it in source. If you know how, I can show you

**Comment by GatoMorado621** [comment]
Try this:

```
function onSongStart()
    for i = 0, getProperty('opponentStrums.length') - 1 do
        setPropertyFromGroup('opponentStrums', i, 'visible', false);

        local strum = 'dadStrum' .. i;
        local dir = 'LEFT';

        if i == 1 then
            dir = 'DOWN';
        elseif i == 2 then
            dir = 'UP'
        elseif i == 3 then
            dir = 'RIGHT';
        end

        makeAnimatedLuaSprite(strum, getPropertyFromGroup('opponentStrums', i, 'texture'),
            getPropertyFromGroup('opponentStrums', i, 'x'), getPropertyFromGroup('opponentStrums', i, 'y'));
        addAnimationByPrefix(strum, 'static', 'arrow' .. dir);
        scaleObject(strum, getPropertyFromGroup('opponentStrums', i, 'scale.x'),
            getPropertyFromGroup('opponentStrums', i, 'scale.y'));
        setObjectCamera(strum, 'hud');
        addLuaSprite(strum);
        objectPlayAnimation(strum, 'static');
    end
end

function onUpdatePost(elasped)
    for i = 0, getProperty('opponentStrums.length') - 1 do
        local strum = 'dadStrum' .. i;
        setProperty(strum .. '.x', getPropertyFromGroup('opponentStrums', i, 'x'));
        setProperty(strum .. '.y', getPropertyFromGroup('opponentStrums', i, 'y'));
        setProperty(strum .. '.angle', getPropertyFromGroup('opponentStrums', i, 'angle'));
        setProperty(strum .. '.alpha', getPropertyFromGroup('opponentStrums', i, 'alpha'));
    end

    if not botPlay then
        setTextString('funScore', 'Score: ' .. score .. '            Misses: ' .. misses);
    end
end
```

**Comment by GatoMorado621** [comment]
> Try this:
> 
> ```
> function onSongStart()
>     for i = 0, getProperty('opponentStrums.length') - 1 do
>         setPropertyFromGroup('opponentStrums', i, 'visible', false);
> 
>         local strum = 'dadStrum' .. i;
>         local dir = 'LEFT';
> 
>         if i == 1 then
>             dir = 'DOWN';
>         elseif i == 2 then
>             dir = 'UP'
>         elseif i == 3 then
>             dir = 'RIGHT';
>         end
> 
>         makeAnimatedLuaSprite(strum, getPropertyFromGroup('opponentStrums', i, 'texture'),
>             getPropertyFromGroup('opponentStrums', i, 'x'), getPropertyFromGroup('opponentStrums', i, 'y'));
>         addAnimationByPrefix(strum, 'static', 'arrow' .. dir);
>         scaleObject(strum, getPropertyFromGroup('opponentStrums', i, 'scale.x'),
>             getPropertyFromGroup('opponentStrums', i, 'scale.y'));
>         setObjectCamera(strum, 'hud');
>         addLuaSprite(strum);
>         objectPlayAnimation(strum, 'static');
>     end
> end
> 
> function onUpdatePost(elasped)
>     for i = 0, getProperty('opponentStrums.length') - 1 do
>         local strum = 'dadStrum' .. i;
>         setProperty(strum .. '.x', getPropertyFromGroup('opponentStrums', i, 'x'));
>         setProperty(strum .. '.y', getPropertyFromGroup('opponentStrums', i, 'y'));
>         setProperty(strum .. '.angle', getPropertyFromGroup('opponentStrums', i, 'angle'));
>         setProperty(strum .. '.alpha', getPropertyFromGroup('opponentStrums', i, 'alpha'));
>     end
> 
>     if not botPlay then
>         setTextString('funScore', 'Score: ' .. score .. '            Misses: ' .. misses);
>     end
> end
> ```

Oh I forgot. The script also change the info bar. If you dont wanna that happen erase the lines when start the `if not botPlay then` and also erase the line that is above of that code
