### ISSUE TITLE
Health Color

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#11324]
### What is your question?

In the source code there is like a var that says dad.healthColorArray to get the color of the character in the rgb, but is there a var for get the rgb color of the songs???
Because I want to put the time bar color of the color of the song.

**Comment by Minalog** [comment]
Well, the only thing I know how to do is turn the RGB (eg. 123, 12, 84) into a hex value (eg. 7b0c54) and then I just enter this code.
```lua
doTweenColor("fpsongbar", "timeBar", "7b0c54", 0.01, "linear")
```

**Comment by GatoMorado621** [comment]
> Well, the only thing I know how to do is turn the RGB (eg. 123, 12, 84) into a hex value (eg. 7b0c54) and then I just enter this code.
> 
> ```lua
> doTweenColor("fpsongbar", "timeBar", "7b0c54", 0.01, "linear")
> ```

Ummm, not to be rude, but that is not what I want and I use source code. But thanks
