### ISSUE TITLE
Stage "hill" won't show up when i am in a song with the "hill" stage putted in

### ISSUE THREAD

**Issue by NewSajgonki** [ShadowMario/FNF-PsychEngine#11330]
### What needs to be documented?

I made a stage hill.lua and hill.json but it can't even show up in a song that i putted the stage in :/
Is anything missing?

hill.lua code:
function onCreate()

	makeLuaSprite('hill', 'hill', -600, -300);
	addLuaSprite('theBackGround', false)
	setScrollFactor('theBackGround', 1.0, 1.0);
	
	close(true);

end

--------------------------------------------------------------------------------

hill.json code:
{
	"directory": "hill",
	"defaultZoom": 0.9,
	"isPixelStage": false,

	"boyfriend": [770, 100],
	"girlfriend": [400, 130],
	"opponent": [100, 100]
}

---------------------------------------------------------------------------------

help please!

**Comment by TheKitBoi** [comment]
Remove the (true); part

**Comment by NewSajgonki** [comment]
oh ok thx

**Comment by TheKitBoi** [comment]
You can now close this issue

**Comment by NewSajgonki** [comment]
![image](https://user-images.githubusercontent.com/108466805/204140967-025ff6cb-1658-4bfd-8be9-a4267ff51a51.png)
welp i don't think it works :/

**Comment by TheKitBoi** [comment]
function onCreate()
    makeLuaSprite('theBackGround', 'hill', -600, -300);
    setScrollFactor('theBackGround', 1.0, 1.0);
    addLuaSprite('theBackGround', false);
    close
end

**Comment by NewSajgonki** [comment]
the same thing happend
![image](https://user-images.githubusercontent.com/108466805/204141215-f2995561-5e61-41da-9af1-35e16c094082.png)

**Comment by TheKitBoi** [comment]
function onCreate()
    makeLuaSprite('theBackGround', 'hill', -600, -300);
    setScrollFactor('theBackGround', 1.0, 1.0);
    addLuaSprite('theBackGround', false);
end

**Comment by NewSajgonki** [comment]
tysm it works now properly
