### ISSUE TITLE
How does the source code judge note miss and good note hit?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#1134]
### What is your question?

How does the source code judge note miss and good note hit?
I check the `PlayState.hx` file but I don't know where the specific code is.

**Comment by lemz1** [comment]
`function notemiss(daNote:Note):Void` line 3365
there is the function for missing a note

`function goodNoteHit(note:Note):Void` line 3450
there is the function for hitting a note

**Comment by zwl1619** [comment]
@lemz1 How does it judge I press the right key and wrong key?
