### ISSUE TITLE
Different Rating

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#11347]
### Describe your bug here.

For some reason, the rating inside of the Score Text, is not fully equals the rating you get from lua, using rating/getProperty('ratingPercent')

Testing it on TUTORIAL gives me the result, that the scoreText is always one singular Note behind

![image](https://user-images.githubusercontent.com/76132257/204621587-73e5b5fc-735c-4355-a60c-502a7b22df38.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no build changed

**Comment by Draconic-Hybrid** [comment]
That's intentional. It's rounded so it doesn't become too attention-grabbing.

**Comment by ZeitHeld** [comment]
No, that is not what I mean. I know that the value is rounded.
But it isn't updated properly.
When you first hit a note, you'd have maximum 350 points, upon a sick note
hit.
But the score text doesn't update yet. It is always one note behind.
If you land a second hit, your rating would be 700, but it shows 350.

And that gives off a wrong value. Especially if you work with accuracy. It
could then be 89 in reality, while it still shows 92.
And when having like a script, let's say, you die if you're under 90%,
you'd die despite the game showing a different value.

Draconic-Hybrid ***@***.***> schrieb am So., 18. Dez. 2022,
03:43:

**Comment by Draconic-Hybrid** [comment]
Looked at the wrong thing, sorry lmao

No idea how to fix that
