### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by imdumlol** [ShadowMario/FNF-PsychEngine#11343]
### Describe your problem here.

this is my error:

source/Main.hx:75: characters 61-65 : Float should be Int
source/Main.hx:75: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:75: characters 61-65 : ... For function argument 'child'
source/TitleState.hx:326: characters 58-61 : Float should be flixel.util.FlxAxes
source/TitleState.hx:326: characters 58-61 : ... For optional function argument 'repeatAxes'
source/GameExitState.hx:65: characters 70-73 : Float should be flixel.util.FlxAxes
source/GameExitState.hx:65: characters 70-73 : ... For optional function argument 'repeatAxes'

help?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by JonnycatMeow** [comment]
do a #if (flixel < "5.0.0")  and at the end of the code do #end

**Comment by FrogB** [comment]
For the issue with Main.hx, replace it with this one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

As for the TitleState and GameExitState issues, do a if flixel 5.0.0 (see Jonnycat's comment)
