### ISSUE TITLE
The Shaders.hx Problem

### ISSUE THREAD

**Issue by StefanBETA2008** [ShadowMario/FNF-PsychEngine#11346]
### Describe your problem here.

```source/Shaders.hx:33: characters 14-25 : Missing ;``` I Don't Know What Im Missed. Someone Help Me

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yeah, The Shaders On Lua Like From The OS Engine

**Comment by StefanBETA2008** [comment]
I Already Added The: ";" On Line 33, But I Don't Know What Im Missed

**Comment by StefanBETA2008** [comment]
> show the code or is it based of a shader you tried compiling.

Here You Go:
https://github.com/StefanBETA2008/FNF-SB-Engine/blob/dab/source/Shaders.hx

**Comment by TheKitBoi** [comment]
That supposed to be in uniform float alphaShit; 
public function new()
void main()

**Comment by StefanBETA2008** [comment]
> That uniform float alphaShit; supposed to be in public function new() void main()

Wait, I Need To Add The ``public function new()`` And The ``void man()`` Too And Delete The ``float alpha****``?

**Comment by StefanBETA2008** [comment]
Are You Kidding Me: ``source/Shaders.hx:34: characters 10-14 : Missing ;``? I Just Deleted The ``float alpha****`` And It's Giving Me This Error.

**Comment by StefanBETA2008** [comment]
I Will Close This Issue :(
