### ISSUE TITLE
Friday Night Funkin' crashes and doesn't run.

### ISSUE THREAD

**Issue by 40U538072** [ShadowMario/FNF-PsychEngine#11348]
### Describe your bug here.

Recently Friday Night Funkin' has been refusing to run on my brother's pc and crashes every time. He has tried compatibility troubleshooting with all sorts of settings and it has refused to run for him. I am reporting this for him so that he doesn't have to. Some possible advice and fixes would be appreciated. Thanks a lot.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope. Just started crashing a refusing to run. Was fine yesterday.

**Comment by TheKitBoi** [comment]
low pc issue

**Comment by 40U538072** [comment]
He can open the program at the moment but it crashes frequently on the chart editor. No autosaves.

**Comment by 40U538072** [comment]
Gonna close this issue now. Gotta focus on the recent issues I opened. I am going to let my brother find out how to fix it on his own.
