### ISSUE TITLE
The hell? COmpile doesn't work on download?

### ISSUE THREAD

**Issue by KadePleaseHelpMe** [ShadowMario/FNF-PsychEngine#11345]
This just happened. It's a fresh download of 0.6.3 with no changes. What the hell
![image](https://user-images.githubusercontent.com/89645987/204530644-1b3857be-cd27-47b2-9de1-7527bf134284.png)

**Comment by CrusherNotDrip** [comment]
Duplicate Issue

**Comment by CrusherNotDrip** [comment]
There could be a PR that fixes this
this issue as it only occurs on flixel 5.0.0 and over

**Comment by Mokona5901** [comment]
Lower your flixel version to 4.11.0

**Comment by imdumlol** [comment]
i had the same error but then this happened

C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:94: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:142: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:150: characters 18-19 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:151: characters 18-19 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:413: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:419: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:420: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:423: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:424: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:426: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:427: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:429: characters 21-22 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:429: characters 44-45 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:430: characters 21-22 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:430: characters 44-45 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:450: characters 20-21 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:456: characters 20-21 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:493: characters 30-31 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:494: characters 30-31 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:191: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:209: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:212: characters 19-20 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:221: characters 19-20 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:262: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:312: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:316: characters 19-20 : flixel.util.FlxAxes has no field x
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:325: characters 19-20 : flixel.util.FlxAxes has no field y
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:182: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes
source/TitleState.hx:329: characters 58-61 : Float should be flixel.util.FlxAxes
source/TitleState.hx:329: characters 58-61 : ... For optional function argument 'repeatAxes'

help??

**Comment by Mokona5901** [comment]
What is your flixel version ?

**Comment by TheRealJake12** [comment]
go to main.hx, go to where it says `game = (someshit)` remove the zoom from it.

**Comment by TheRealJake12** [comment]
use flixel 5.0.1

**Comment by TheKitBoi** [comment]
or just replace line 85
addChild(new FlxGame(gameWidth, gameHeight, initialState, #if (flixel < "5.0.0") zoom, #end framerate, framerate, skipSplash, startFullscreen));

**Comment by TheRealJake12** [comment]
yes

**Comment by imdumlol** [comment]
well now i have this...

source/TitleState.hx:329: characters 58-61 : Float should be flixel.util.FlxAxes
source/TitleState.hx:329: characters 58-61 : ... For optional function argument 'repeatAxes'

**Comment by KadePleaseHelpMe** [comment]
> > i had the same error but then this happened
> > C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:94: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:142: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:150: characters 18-19 : flixel.util.FlxAxes has no field x C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:151: characters 18-19 : flixel.util.FlxAxes has no field y C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:413: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:419: characters 21-22 : flixel.util.FlxAxes has no field x C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:420: characters 21-22 : flixel.util.FlxAxes has no field y C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:423: characters 21-22 : flixel.util.FlxAxes has no field x C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:424: characters 21-22 : flixel.util.FlxAxes has no field y C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:426: characters 21-22 : flixel.util.FlxAxes has no field x C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:427: characters 21-22 : flixel.util.FlxAxes has no field y C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:429: characters 21-22 : flixel.util.FlxAxes has no field x C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:429: characters 44-45 : flixel.util.FlxAxes has no field x C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:430: characters 21-22 : flixel.util.FlxAxes has no field y C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:430: characters 44-45 : flixel.util.FlxAxes has no field y C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:450: characters 20-21 : flixel.util.FlxAxes has no field x C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:456: characters 20-21 : flixel.util.FlxAxes has no field y C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:493: characters 30-31 : flixel.util.FlxAxes has no field x C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:494: characters 30-31 : flixel.util.FlxAxes has no field y C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:191: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:209: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:212: characters 19-20 : flixel.util.FlxAxes has no field x C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:221: characters 19-20 : flixel.util.FlxAxes has no field y C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:262: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:312: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:316: characters 19-20 : flixel.util.FlxAxes has no field x C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:325: characters 19-20 : flixel.util.FlxAxes has no field y C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,0/flixel/addons/display/FlxBackdrop.hx:182: characters 7-25 : flixel.FlxType should be flixel.util.FlxAxes source/TitleState.hx:329: characters 58-61 : Float should be flixel.util.FlxAxes source/TitleState.hx:329: characters 58-61 : ... For optional function argument 'repeatAxes'
> > help??
> 
> Psych Engine doesnt support Flixel Addons 3.0.0, try a lower version.

seeing if this works brb

**Comment by KadePleaseHelpMe** [comment]
EVERYONE HERE: I have a new issue

`source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\PROJECT-GlFnd\Downloads\Reset\export\debug\windows\obj>setlocal enabledelayedexpansion
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths`

Hwat now

**Comment by ACrazyTown** [comment]
> EVERYONE HERE: I have a new issue
> 
> **source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead C:\Users\PROJECT-GlFnd\Downloads\Reset\export\debug\windows\obj>setlocal enabledelayedexpansion Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths**
> 
> Hwat now
> 
> Edit: here's an image of there. Keep in mind, fresh, clean copy of 0.6.3, using flixel-addons 3.0.0 ![image](https://user-images.githubusercontent.com/89645987/204662214-f754b67d-63f5-4d75-8af7-c12dedf55017.png)

The warning doesn't mean anything. You need to install MSVC. Also don't use `flixel-addons` 3.0.0 if you're using Flixel 4.11.0, use `2.11.0`

**Comment by KadePleaseHelpMe** [comment]
@ACrazyTown I installed flixel-addons 2.11.0 and it's still deprecated
what now
![image](https://user-images.githubusercontent.com/89645987/205174664-40047338-b930-416e-8d60-e15a490c5661.png)

**Comment by ACrazyTown** [comment]
> @ACrazyTown I installed flixel-addons 2.11.0 and it's still deprecated
> what now
> ![image](https://user-images.githubusercontent.com/89645987/205174664-40047338-b930-416e-8d60-e15a490c5661.png)
> 

Like I said, it's a warning. It wont affect compiling, you dont have to edit anything

**Comment by KadePleaseHelpMe** [comment]
@ACrazyTown it affected compiling, I have to edit something
![image](https://user-images.githubusercontent.com/89645987/205179761-d28c72a9-e89c-4ecd-ac11-a72f05aff0d6.png)

**Comment by Nightmare-boyfriend** [comment]
I tried the flixel-addons 2.11.0 and it worked

**Comment by ACrazyTown** [comment]
> @ACrazyTown it affected compiling, I have to edit something
> ![image](https://user-images.githubusercontent.com/89645987/205179761-d28c72a9-e89c-4ecd-ac11-a72f05aff0d6.png)
> 

Install MSVC

**Comment by KadePleaseHelpMe** [comment]
how do I do that?

**Comment by KadePleaseHelpMe** [comment]
should that have done something

**Comment by ACrazyTown** [comment]
> should that have done something

No that's a VSCode extension. You need to install MSVC thru the Visual Studio Installer

**Comment by KadePleaseHelpMe** [comment]
> > should that have done something
> 
> No that's a VSCode extension. You need to install MSVC thru the Visual Studio Installer

please link me to that I couldn't find it. DK if it's just me being an idiot but I searched for 5 minutes and couldn't find it

**Comment by ACrazyTown** [comment]
> > > should that have done something
> > 
> > 
> > No that's a VSCode extension. You need to install MSVC thru the Visual Studio Installer
> 
> please link me to that I couldn't find it. DK if it's just me being an idiot but I searched for 5 minutes and couldn't find it

Open Visual Studio Installer, find your Visual Studio install and select "Modify"
![image](https://user-images.githubusercontent.com/47027981/205374572-5be30599-2669-4016-b9bb-a7aabd92dcc5.png)

From there go to "Individual components": 
![image](https://user-images.githubusercontent.com/47027981/205374617-b6532560-845e-43f7-9cf6-416589fe9a0e.png)

Then search and select these two components:
- MSVC v143 C++ x64/x86 build tools (Latest)
- Windows 10 SDK (Anything above or equal to 10.0.19041.0 should work fine I think)

And after you select them, click Modify in the bottom right corner and wait for it to download and install. It should work after that

**Comment by KadePleaseHelpMe** [comment]
once again, where is the installer?

**Comment by ACrazyTown** [comment]
> once again, where is the installer?

https://visualstudio.microsoft.com/downloads/

Download Visual Studio 2022 Community, as the others are paid

**Comment by KadePleaseHelpMe** [comment]
found
downloading

**Comment by KadePleaseHelpMe** [comment]
@ACrazyTown you are a legend
![image](https://user-images.githubusercontent.com/89645987/205401460-d605092e-211e-4153-8152-506b1bbc2d3d.png)

**Comment by Nightmare-boyfriend** [comment]
cool

**Comment by alex-codes-stuff** [comment]
> well now i have this...
> 
> source/TitleState.hx:329: characters 58-61 : Float should be flixel.util.FlxAxes source/TitleState.hx:329: characters 58-61 : ... For optional function argument 'repeatAxes'
run haxelib install flixel-addons 2.11.0 in cmd prompt and set it as current flixel addons version
