### ISSUE TITLE
Sprite refuses to appear

### ISSUE THREAD

**Issue by EEYM** [ShadowMario/FNF-PsychEngine#11342]
### Describe your bug here.

I put in a sprite that's meant to appear during curStep 1836 of the song, but for some reason it just doesn't happen.
Strangely enough, it _does_ show up if I use the "Skip Time" feature to go straight to that point.
I've tried using just about everything I could do to make it appear. Putting it into an event, moving it into a different LUA script, making it part of a TimerCompleted function. Does anyone know what the issue could be?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Can't help if you don't show the code

**Comment by EEYM** [comment]
That's the thing, I've used multiple code methods, and they all failed

Activating through an event:
function onEvent(name, value1, value2)
     if name == 'Mastery Event' then
          if value1 == 1 then
               addLuaSprite('bambi', true);
               objectPlayAnimation('bambi', 'throw', true);
               setObjectOrder('bambi', 7);
          end
          if value2 == 2 then
               addLuaSprite('bozo', true);
               setObjectOrder('bozo', 8);
               doTweenAlpha('bfDie', 'boyfriend', 0, 0.00000001, linear);
          end
end

Activating through curStep:
function onUpdate()
     if curStep == 1834 then
          addLuaSprite('bambi', true);
          objectPlayAnimation('bambi', 'throw', true);
          setObjectOrder('bambi', 7);
     end
     if curStep == 1836 then
          addLuaSprite('bozo', true);
          setObjectOrder('bozo', 8);
          doTweenAlpha('bfDie', 'boyfriend', 0, 0.00000001, linear);
     end
end

Increasing the transparency through curStep:
function onUpdate()
     if curStep == 1834 then
          doTweenAlpha('bambiAppear', 'bambi', 1, 0.00000001, linear);
          objectPlayAnimation('bambi', 'throw', true);
          setObjectOrder('bambi', 7);
     end
     if curStep == 1836 then
          doTweenAlpha('bozoAppear', 'bozo', 1, 0.00000001, linear);
          setObjectOrder('bozo', 8);
          doTweenAlpha('bfDie', 'boyfriend', 0, 0.00000001, linear);
     end
end

Activating through a timer:
function onTimerCompleted(tag)
     if tag == '1' then
          addLuaSprite('bambi', true);
          objectPlayAnimation('bambi', 'throw', true);
          setObjectOrder('bambi', 7);
     end
     if tag == '2' then
          addLuaSprite('bozo', true);
          setObjectOrder('bozo', 8);
          doTweenAlpha('bfDie', 'boyfriend', 0, 0.00000001, linear);
     end
end

Using curStep to quickly move the sprites in:
function onUpdate()
     if curStep == 1834 then
          doTweenX('bambiAppear', 'bambi', -750, 0.00000001, linear);
          objectPlayAnimation('bambi', 'throw', true);
          setObjectOrder('bambi', 7);
     end
     if curStep == 1836 then
          doTweenX('bozoAppear', 'bozo', 625, 0.00000001, linear);
          setObjectOrder('bozo', 8);
          doTweenAlpha('bfDie', 'boyfriend', 0, 0.00000001, linear);
     end
end

Ditto, but through doTweenY:
function onUpdate()
     if curStep == 1834 then
          doTweenY('bambiAppear', 'bambi', -475, 0.00000001, linear);
          objectPlayAnimation('bambi', 'throw', true);
          setObjectOrder('bambi', 7);
     end
     if curStep == 1836 then
          doTweenY('bozoAppear', 'bozo', 575, 0.00000001, linear);
          setObjectOrder('bozo', 8);
          doTweenAlpha('bfDie', 'boyfriend', 0, 0.00000001, linear);
     end
end

**Comment by EEYM** [comment]
Forgot to mention, I already have all the script for the objects themselves pre-made in another LUA script

function onCreate()
ㅤㅤmakeLuaSprite('bozo', 'gardead', 625, 575);
ㅤㅤsetProperty('bozo.flipX', true);
	
ㅤㅤmakeAnimatedLuaSprite('bambi', 'bambiCutscene', -750, -475);
ㅤㅤsetProperty('bambi.flipX', true);
ㅤㅤaddAnimationByPrefix('bambi','throw','a_bambi throw','24',true);
end

**Comment by EEYM** [comment]
Figured it out, setObjectOrder just didn't work properly

**Comment by EEYM** [comment]
Figured it out, setObjectOrder just didn't work properly

**Comment by frantastic24** [comment]
setObjectOrder works by removing and reading an object, so it probably is working properly but is also stopping the tween because there is no object
