### ISSUE TITLE
How do i make that the opponent gets out of the window

### ISSUE THREAD

**Issue by ElPro7777** [ShadowMario/FNF-PsychEngine#11357]
### What is your question?

How do i make that the opponent gets out of the window without Source

**Comment by TheKitBoi** [comment]
windowDad = Application.current.createWindow({
            title: 'Name',
            width: 680,
            height: 360,
            borderless: true,
            alwaysOnTop: true

Application.current.window.focus();
		
		windowDad.stage.color = 0x0000FF00;
        FlxG.mouse.useSystemCursor = true;
        FlxG.autoPause = false;
    
        
    
        windowDad.x = 20;
        windowDad.y = -50;
        dadWin = new Sprite();
        var dadScrollWin = new Sprite();
        windowDad.stage.addEventListener("keyDown", FlxG.keys.onKeyDown);
        windowDad.stage.addEventListener("keyUp", FlxG.keys.onKeyUp);
        var m = new Matrix();
    
      
    
        
        dadWin.graphics.beginBitmapFill(game.dad.pixels, m);
        dadWin.graphics.drawRect(0, 0, game.dad.pixels.width, game.dad.pixels.height);
        dadWin.graphics.endFill();
        windowDad.stage.addChild(dadWin);
        dadWin.scaleX = 1;
        dadWin.scaleY = 1;

**Comment by TheRealJake12** [comment]
> ```
> windowDad = Application.current.createWindow({
>             title: 'Name',
>             width: 680,
>             height: 360,
>             borderless: true,
>             alwaysOnTop: true
>         });
> 
>         Application.current.window.focus();
> 		
> 	windowDad.stage.color = 0x0000FF00;
>         FlxG.mouse.useSystemCursor = true;
>         FlxG.autoPause = false;
> 
>         windowDad.x = 20;
>         windowDad.y = -50;
>         dadWin = new Sprite();
>         var dadScrollWin = new Sprite();
>         windowDad.stage.addEventListener("keyDown", FlxG.keys.onKeyDown);
>         windowDad.stage.addEventListener("keyUp", FlxG.keys.onKeyUp);
>         var m = new Matrix();
>     
>       
>     
>         
>         dadWin.graphics.beginBitmapFill(game.dad.pixels, m);
>         dadWin.graphics.drawRect(0, 0, game.dad.pixels.width, game.dad.pixels.height);
>         dadWin.graphics.endFill();
>         windowDad.stage.addChild(dadWin);
>         dadWin.scaleX = 1;
>         dadWin.scaleY = 1;
> ```

this is source. It isn't even the complete guide on how to do it lmaooooo. You can't do it in lua.

**Comment by TheKitBoi** [comment]
> this is source. It isn't even the complete guide on how to do it lmaooooo. You can't do it in lua.

runHaxeCode() exist
[charlInWindow.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/10134226/charlInWindow.txt) rename .txt to .lua

and add this line onCreatePost or onStepHit if your timing
addLuaScript('charInWindow')
and add this if you want to remove it on some timing
removeLuaScript('fatalInWindow')

**Comment by TheRealJake12** [comment]
💀

**Comment by ElPro7777** [comment]
> > this is source. It isn't even the complete guide on how to do it lmaooooo. You can't do it in lua.
> 
> runHaxeCode() exist [charInWindow.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/10134250/charInWindow.txt) rename .txt to .lua
> 
> and add this line onCreatePost or onStepHit if your timing addLuaScript('charInWindow') and add this if you want to remove it on some timing removeLuaScript('charInWindow')

so thanks! and also I never Know That Run haxe code Now I can port Sonic.exe 3.0 For Low end PC or port Dave And Bambi 3.0

**Comment by ElPro7777** [comment]
and also i can do my mod where the opponent in a secret song takes over your pc

**Comment by TheRealJake12** [comment]
not a good idea but 🤷🏻

**Comment by ElPro7777** [comment]
> why is not working in 0.7.3

the question is why are you responding to something from 2 YEARS AGO

**Comment by Nkill68** [comment]
> > this is source. It isn't even the complete guide on how to do it lmaooooo. You can't do it in lua.
> 
> runHaxeCode() exist [charInWindow.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/10134250/charInWindow.txt) rename .txt to .lua
> 
> and add this line onCreatePost or onStepHit if your timing addLuaScript('charInWindow') and add this if you want to remove it on some timing removeLuaScript('charInWindow')

that generate only the window bordless white and corrupt all the game image (In Game Not In The Explorer)

**Comment by ElPro7777** [comment]
> > > this is source. It isn't even the complete guide on how to do it lmaooooo. You can't do it in lua.
> > 
> > 
> > runHaxeCode() exist [charInWindow.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/10134250/charInWindow.txt) rename .txt to .lua
> > and add this line onCreatePost or onStepHit if your timing addLuaScript('charInWindow') and add this if you want to remove it on some timing removeLuaScript('charInWindow')
> 
> that generate only the window bordless white and corrupt all the game image (In Game Not In The Explorer)

THIS IS FROM 2 YEARS AGO. IT DOES NOT WORK IN 1.0.0

**Comment by Nkill68** [comment]
i have 0.7.3

**Comment by ElPro7777** [comment]
> i have 0.7.3
Still. It must be from an old version. I don't remember what version tho. I think it was some version from around 2022

**Comment by ElPro7777** [comment]
It must be 0.6.3 that was the one that was released at that time

**Comment by thatguyatrix** [comment]
> i have 0.7.3

Use 0.6.3

**Comment by AnotherPlayer8** [comment]
> > i have 0.7.3
> 
> Use 0.6.3

i tried using 0.6.3, but the game crashed when entering the song i placed the script in
it did create a window before closing

**Comment by thatguyatrix** [comment]
> > > i have 0.7.3
> > 
> > 
> > Use 0.6.3
> 
> i tried using 0.6.3, but the game crashed when entering the song i placed the script in it did create a window before closing

idk man. thats what happens when you try to use an outdated thing as reference. i already forgot what version i had :P (maybe is something pc related btw)
