### ISSUE TITLE
Freeplay bug

### ISSUE THREAD

**Issue by OmartheMetaRunner** [ShadowMario/FNF-PsychEngine#11350]
### Describe your bug here.

FreePlay bug when importing my mod into psych engine it just never responds. with every psych engine version
![Screenshot_20221129_025624](https://user-images.githubusercontent.com/119460424/204667109-3f38b541-09eb-4e70-84dc-135f1c5a3b18.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I just added things in my mod which only include new art, new songs, and new mechanics, no remaking parts to bug the game

**Comment by TheKitBoi** [comment]
you fucked up your week.json
