### ISSUE TITLE
rotate arrow when the player sing

### ISSUE THREAD

**Issue by SilvoSNonsense** [ShadowMario/FNF-PsychEngine#11355]
### Describe your problem here.

i sartaed using lua and i'm wodering if there is a way to make a code that rotate a bit one of your arrow when you tap them,
if someone can help me, that would be really cool

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Lorekeeper49** [comment]
`noteTweenAngle()` exists but I'm unsure of how to get the current angle of the note to accomplish your goal
