### ISSUE TITLE
GitHub says there's 708 Issues, I think there should only be ~30 or less

### ISSUE THREAD

**Issue by ItsLJcool** [ShadowMario/FNF-PsychEngine#11352]
### Describe your bug here.

For me the GitHub for PsychEngine says "708 issues" but the developers can't be that dumb to respond or close most of them... right?

How do I fix the issue?
![image](https://user-images.githubusercontent.com/54383469/204676235-6699280f-5026-48a1-a365-6e0b14dab32b.png)
![image](https://user-images.githubusercontent.com/54383469/204676286-9fb6b7b9-8ad9-4682-bd21-b28ae60cc10c.png)
![image](https://user-images.githubusercontent.com/54383469/204676308-d7b3cae1-4a28-401e-9eba-7cfba22b7039.png)

:trollface: 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

uh no

**Comment by voiddevv** [comment]
god fucking damn it

**Comment by CaptainBaldi** [comment]
its an engine with 2 million views, im not sure what you expect

**Comment by TheKitBoi** [comment]
> ### Describe your bug here.
> For me the GitHub for PsychEngine says "708 issues" but the developers can't be that dumb to respond or close most of them... right?

fuck you there is 7/11 issues 
![image](https://user-images.githubusercontent.com/84044666/204862922-f7d6e12a-0728-4311-bb42-adca5ace95c4.png)

i hope your in a building

**Comment by Ninjakaiden523** [comment]
A lot of people just don't close their issues, they post it forget it exists or get no responses and fix the issue themselves.

**Comment by CaptainBaldi** [comment]
> > 
> 
> people shouldn't be encountering issues this fucking often?!?!!??!!?!!?

im not sure if you noticed, but there are question and help wanted labels for issues. That's what most of the issues are. And most issues with the bug label are either duplicates or people just being stupid and reporting something as a bug when it's something they did

**Comment by Grape-Boy** [comment]
if people weren't stupid, there would be a lot less issues
