### ISSUE TITLE
I'm just gonna let you look and see what's wrong here.. no i can't fix it

### ISSUE THREAD

**Issue by imalink100** [ShadowMario/FNF-PsychEngine#11358]
### 

![image](https://user-images.githubusercontent.com/106406304/204919314-9ac6ae0b-def0-48a4-b315-36ca112a0e78.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheKitBoi** [comment]
did u disable auto scroll

**Comment by imalink100** [comment]
> did u disable auto scroll

theres no auto scroll option in options

**Comment by imalink100** [comment]
OH
