### ISSUE TITLE
opponent strums tween

### ISSUE THREAD

**Issue by hotpocketsarepoggers** [ShadowMario/FNF-PsychEngine#11351]
### Describe your problem here.

How can I make it, so the opponents strums (not each individual arrow but the entire opponents strum line) move in certain directions depending on what note is hit

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Lorekeeper49** [comment]
You're gonna have to do something like this:
```lua 
function opponentNoteHit(s, d, t, l)
    if d == number then --replace number with an integer of 0-3 
        noteTweenX('tweenName0', 0, 0.3, 'linear')
        noteTweenX('tweenName1', 1, 0.3, 'linear')
        noteTweenX('tweenName2', 2, 0.3, 'linear')
        noteTweenX('tweenName3', 3, 0.3, 'linear')
        --noteTweenY if vertical
    end
end
```
I know this all seems individual, but they'll all move at the same time like this
