### ISSUE TITLE
Feature Request: Displaying Text in Scripts (LUA)

### ISSUE THREAD

**Issue by KacperOSM** [ShadowMario/FNF-PsychEngine#1135]
### What feature do you want to get added on the base engine?

Drawing Text in the Lua scripts so whenever we signal the code to make text, then it will draw a text and display it on screen.

It might be useful for displaying Warnings and adding Subtitles in the songs.

**Comment by KlavierGayming** [comment]
i agree

**Comment by THOBY555** [comment]
> ### What feature do you want to get added on the base engine?
> Drawing Text in the Lua scripts so whenever we signal the code to make text, then it will draw a text and display it on screen.
> 
> It might be useful for displaying Warnings and adding Subtitles in the songs.

u can a text image [text.png] and use a folder on mods/images/text images and use the sprites images like tricky psych port

**Comment by KacperOSM** [comment]
> > ### What feature do you want to get added on the base engine?
> > Drawing Text in the Lua scripts so whenever we signal the code to make text, then it will draw a text and display it on screen.
> > It might be useful for displaying Warnings and adding Subtitles in the songs.
> 
> u can a text image [text.png] and use a folder on mods/images/text images and use the sprites images like tricky psych port

I don't think it would be efficient to just add an image as a substitute for texts

**Comment by KacperOSM** [comment]
> > > ### What feature do you want to get added on the base engine?
> > > Drawing Text in the Lua scripts so whenever we signal the code to make text, then it will draw a text and display it on screen.
> > > It might be useful for displaying Warnings and adding Subtitles in the songs.
> > 
> > 
> > u can a text image [text.png] and use a folder on mods/images/text images and use the sprites images like tricky psych port
> 
> I don't think it would be efficient to just add an image as a substitute for texts

Plus I suggested that idea (The TEXT in the song's script) and I didn't ask how to add text to the song

**Comment by ShadowMario** [comment]
Done
