### ISSUE TITLE
tutorial breaker?

### ISSUE THREAD

**Issue by plotmanlover** [ShadowMario/FNF-PsychEngine#11366]
### Describe your bug here.

so im very new to makeing the spych engine but i have learned a little bit of how to make the spritesheet works and how to put my spritesheet in the game. which ive manage to figure it out and i was going to take a test drive of my spritesheet i put in (took me 6 hr to figure it out on character editor). so when i went to freeplay i instantly crashed and idk what happen to freeplay cuz i nvr touch the coding in the assets i was only following the mod tutorials.

### Command Prompt/Terminal logs (if existing)

```bash
FreeplayState.hx (line 74)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i only edit the animation spritesheets idk how it crash me on freeplay

**Comment by frantastic24** [comment]
Not a bug
You have a broken week file

**Comment by plotmanlover** [comment]
nvrm i found the problem so i did somthin i added another week in there i was hoping to prepare later on but i didnt know it would break if i leave it empty.
