### ISSUE TITLE
Odd bug

### ISSUE THREAD

**Issue by Ninjakaiden523** [ShadowMario/FNF-PsychEngine#11360]
### Describe your bug here.

When I was making a character with an external XML generator (AHEM https://gamebanana.com/tools/7136) I did everything right and when I loaded in the animations were fine. In the character editor when I went in game the character had no idle and when a note was pressed just teleported under BF's right (Player's left) foot like he was stomping on the character. 

I looked up  label:bug character animations  in the search and found only two questions: #3535 #2283 they're old I know, one was answered by shadow mario but the answer he gave was vague that answer being "Missing song files." Which I do think spookeez isn't missing it's song files so that's not the answer. If you had a similar bug or found another issue please tell me.

### Command Prompt/Terminal logs (if existing)

```bash
None
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not in the source files, only lua. Added a few characters and a few songs (all charted and using base game assets as place holders)

**Comment by Ninjakaiden523** [comment]
Honestly it is very funny the first time you see it, but I want the character to work. 
I even followed what the comments said on the second one, it didn't help.

**Comment by Ninjakaiden523** [comment]
I'm very desperate right now.

**Comment by frantastic24** [comment]
Some footage would help but it sounds like you either typed the animation names wrong or didn't change offsets

**Comment by Draconic-Hybrid** [comment]
Given that your other issue is solved, please close this one.
