### ISSUE TITLE
Main.hx error GitHub fix?

### ISSUE THREAD

**Issue by DabbinDude316B** [ShadowMario/FNF-PsychEngine#11369]
### Describe your problem here.

So, I did all the main.hx things to fix the error, but when GitHub tried to compile, it gives than same error

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just want to fix the GitHub man

**Comment by TheKitBoi** [comment]
made a pr fixing that https://github.com/ShadowMario/FNF-PsychEngine/pull/11299
also replace this line at 85 addChild(new FlxGame(gameWidth, gameHeight, initialState, #if (flixel < "5.0.0") zoom, #end framerate, framerate, skipSplash, startFullscreen));

**Comment by DabbinDude316B** [comment]
Thanks!
