### ISSUE TITLE
Charecter wont load correctly

### ISSUE THREAD

**Issue by Cap6ailB3an** [ShadowMario/FNF-PsychEngine#11367]
### Describe your problem here.

Hi, whenever i try to load a charecter from my spritesheet it glitches and still says its (ERROR!) Screenshot
![error](https://user-images.githubusercontent.com/111667187/205195047-b8c924b3-6ced-4056-923f-1ecb311b9cfe.png)
i dont know if im messing up but can some one help!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added 2 XMLs both of them dont work

**Comment by frantastic24** [comment]
It's not glitching, the animation name doesn't match with the one on your XML

**Comment by Mokona5901** [comment]
To be precise, on the `Animation on the .XML/.TXT file :` it's must be for example `bambiXD idle` for idle pose

**Comment by Cap6ailB3an** [comment]
thanks for the help!
