### ISSUE TITLE
Please help me adding rotate when note hitted

### ISSUE THREAD

**Issue by SilvoSNonsense** [ShadowMario/FNF-PsychEngine#11368]
### Describe your problem here.

i'm new to using the engine and i'm trying to find a way as evrytimes the player hit a note, the arrow rotate a bit like 30degres, please, help me to accomplish my goal

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nop

**Comment by Cap6ailB3an** [comment]
this is for arrow flip but might help you: https://gamebanana.com/tuts/14786adlt=strict&toWww=1&redig=102D183F42904F6B9EBCC174C1725B33
