### ISSUE TITLE
Crash when playing a chart editor song (unknown if its just a song with that character in it)

### ISSUE THREAD

**Issue by Landoritoo** [ShadowMario/FNF-PsychEngine#11376]
### Describe your bug here.

I added in my character to the game and when I tried opening a song with him in it crashed with an undocumented crash report.

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
editors/ChartingState.hx (line 2957)
editors/ChartingState.hx (line 434)
Prompt.hx (line 44)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/neo/neogen.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added a modded character.

**Comment by frantastic24** [comment]
Character has nothing to do with it, this is a missing chart file
No clue why the song and the chart have different names though
