### ISSUE TITLE
arrow speed bug

### ISSUE THREAD

**Issue by Zelocoolboy** [ShadowMario/FNF-PsychEngine#11374]
### Describe your bug here.

this might just be my pc but every song I play the arrow speed is slow and I cant change it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i did add a new dad.json but i redownloaded a new fresh one nothing changed in it and this is still happening

**Comment by TheKitBoi** [comment]
did you press ctrl in freeplay to check the scroll speed
![image](https://user-images.githubusercontent.com/84044666/205384373-11680753-e4c9-4f02-916a-ffc3e63a4dc4.png)
