### ISSUE TITLE
Custom health bar 

### ISSUE THREAD

**Issue by Gurudevsing** [ShadowMario/FNF-PsychEngine#11378]
### Describe your problem here.

HOW TO ADD CUSTOM HEALTH BAR IN LUA SCRIPT

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Place your custom healthBar.png inside images

**Comment by Jevilm** [comment]
If it is transparent, i recommend hiding the health bar background and making a new health bar sprite because changing a health bar color of the sprite will be harder to do

**Comment by Gurudevsing** [comment]
> Place your custom healthBar.png inside images
No i don't want to create custom health bar . I just want to use another mode health bar To my mod and I want to fix that health bar on particular stage not particular song

**Comment by Gurudevsing** [comment]
> Place your custom healthBar.png inside images

No i don't want to create custom health bar . I just want to use another mode health bar To my mod and I want to fix that health bar on particular stage not particular song

**Comment by Gurudevsing** [comment]
> Place your custom healthBar.png inside images

No i don't want to create custom health bar . I just want to use another mode health bar ,(INDIE CROSS)To my mod and I want to fix that health bar on particular stage not particular song

**Comment by Gurudevsing** [comment]
> Place your custom healthBar.png inside images

????

**Comment by Gurudevsing** [comment]
> > > Place your custom healthBar.png inside images
> > 
> > 
> > ????
> 
> He means, put your new healthbar.png sprite inside Mods/Images, and then change the positions with lua


![Screenshot (58)](https://user-images.githubusercontent.com/87480185/205939094-20b61459-1c26-4768-a0a8-db24248eabc9.png)

THIS SPRITE FROM HOPE AND MADNESS MOD , I PUT MY EXAMPLE SPRITE IN CORRECT LOCATION, AND I DON'T KNOW FUNCTION ON ADDING BOTH P1 AND P2 HEALTH BAR 


![Screenshot (59)](https://user-images.githubusercontent.com/87480185/205947078-29e9da45-c3be-4811-9bf0-b0e5a3f03828.png)

I THINK THIS CODE IS FOR CHANGING ICON P1, P2 HELP ME

**Comment by Jevilm** [comment]
do something like setProperty('healthBar.y', getProperty('scoreTxt.y') + 5)
you arent meant to change the icons

**Comment by Gurudevsing** [comment]
> do something like setProperty('healthBar.y', getProperty('scoreTxt.y') + 5) you arent meant to change the icons

No i don't mean about changing icon iam about adding those health bar only

**Comment by Gurudevsing** [comment]
> do something like setProperty('healthBar.y', getProperty('scoreTxt.y') + 5) you arent meant to change the icons





> do something like setProperty('healthBar.y', getProperty('scoreTxt.y') + 5) you arent meant to change the icons


the default health bar is still there. how to add the bar

**Comment by Jevilm** [comment]
> > do something like setProperty('healthBar.y', getProperty('scoreTxt.y') + 5) you arent meant to change the icons
> 
> > do something like setProperty('healthBar.y', getProperty('scoreTxt.y') + 5) you arent meant to change the icons
> 
> the default health bar is still there. how to add the bar

setProperty('healthBarBG.visible', false)

makeLuaSprite('healthBarBGNEW', 'your image here', 0, 0)
setObjectCamera('healthBarBGNEW', 'camHUD')
addLuaSprite('healthBarBGNEW')

Please check the wiki

**Comment by BLAZ3RZ** [comment]
Can someone send me a script of this entire thing please? Ive been trying to look for something similar to this everywhere, and I couldn't find anything. ;-;

**Comment by JogadorCriador** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Variables This can help maybe
