### ISSUE TITLE
i need help???

### ISSUE THREAD

**Issue by imdumlol** [ShadowMario/FNF-PsychEngine#11371]
### Describe your problem here.

How do i change the misses text to combo breaks????? 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by imdumlol** [comment]
no but like in the source code???

**Comment by CaptainBaldi** [comment]
> no but like in the source code???

`Playstate.hx` line 2304
