### ISSUE TITLE
problems from compiling the game

### ISSUE THREAD

**Issue by CleanerCosine14** [ShadowMario/FNF-PsychEngine#11381]
### Describe your problem here.

lime test windows
source/Main.hx:73: characters 61-65 : Float should be Int
source/Main.hx:73: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:73: characters 61-65 : ... For function argument 'child'

its not working pls help me, what do i install

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheKitBoi** [comment]
Wait until this https://github.com/ShadowMario/FNF-PsychEngine/pull/11299 gets merged
if ur inpatient then replace line 85 at Main.hx addChild(new FlxGame(gameWidth, gameHeight, initialState, #if (flixel < "5.0.0") zoom, #end framerate, framerate, skipSplash, startFullscreen));

**Comment by NicholasCasarez** [comment]
haxelib set flixel 4.11.0
