### ISSUE TITLE
Random character in Main Menu

### ISSUE THREAD

**Issue by tvbetinho2015** [ShadowMario/FNF-PsychEngine#11389]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/77619594/205461758-74b3a4fa-6501-4426-86ca-6b084d40a8c5.png)
### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I was getting the code there from the DDTO source code, but nothing appears!!

**Comment by Minalog** [comment]
Here's the [Haxe "Random" documentation](https://lib.haxe.org/p/random/) page.
