### ISSUE TITLE
how do I check if note is Sick/Good/Bad/Shit and react appropriately?

### ISSUE THREAD

**Issue by RowanSkie** [ShadowMario/FNF-PsychEngine#11380]
### Describe your problem here.

A rather minor question, since the solution at #9360 sadly no longer works, and no matter what I do it still counts as a Sick note.

Relevant parts of the lua script I made for it:

```lua
function goodNoteHit(id, direction, noteType, isSustainNote)
	oldScore = score
	
	if not botPlay then
			
		if getProperty('sicks') then
			noteVType = 1000
			accScore = accScore + sickScore
			setScore(oldScore + sickScore)
		
		elseif getProperty('goods') then
			noteVType = 0100
			accScore = accScore + goodScore
			setScore(oldScore + goodScore)
			
		elseif getProperty('bads') then
			noteVType = 0010
			accScore = accScore + badScore
			setScore(oldScore + badScore)
			
		elseif getProperty('shits') then
			noteVType = 0001
			accScore = accScore + shitScore
			setScore(oldScore + shitScore)
			
		end
		scoreCheck(oldScore, accScore, noteVType)
	end
	
	if activateDebugText == 1 and activateDebugScores == 1 then
		debugPrint('[INFO] Actual Score:\t'..accScore)
		debugPrint('[INFO] Game Score:\t'..score)
	end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
This is how you do it iirc
```lua
function goodNoteHit(id, direction, noteType, isSustainNote)
    getPropertyFromGroup('notes', id, 'rating')
end
```

`getProperty('sicks')` just gets you total sicks

**Comment by RowanSkie** [comment]
Okay, so that's how to pull everything, now how do I check if the note is sick/good/shit/bad with that getPropertyFromGroup function?

**Comment by frantastic24** [comment]
It's just a string: sick, good, etc
You also could've just used debugPrint to check lol

**Comment by frantastic24** [comment]
No, `sick` is the value, `rating` is the variable
Why would there be a different variable for each rating

**Comment by RowanSkie** [comment]
Trying to think about how to do the code with getPropertyFromGroup, in 0.5.2h the previous code worked fine.

```lua
if getPropertyFromGroup('notes',id,'rating') == 'sick'
```
like that?

**Comment by frantastic24** [comment]
It's missing `then` but yes that's correct

**Comment by RowanSkie** [comment]
Okay, so I ran it into the code and now the score system decides to count in the opponent turns to the score itself.

**Comment by RowanSkie** [comment]
Fixed it. Just made the getProperty to set unknown notes as hold. It'll... hold, for now.
