### ISSUE TITLE
got this error :/

### ISSUE THREAD

**Issue by ethannn123** [ShadowMario/FNF-PsychEngine#11384]
### Describe your bug here.

so while i was testing out my songs, i got an error message (aka it crashed), all of the other songs work except for the ones with dots on them (ex. itch.io), so i removed the dots from the weeks, songs, and data and see if that could work. it didnt :(
(also i dont mean the dots on the files, just on the song name)

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
FreeplayState.hx (line 371)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/bopeebo-(itchio-build)/bopeebo-(itchio-build)-hard.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i put a few songs in the mod.

**Comment by frantastic24** [comment]
Not a bug
Symbols and special characters are ignored and replaced when searching for the folder, the error is telling you what your folder should be named
