### ISSUE TITLE
Psych Engine Feature Idea

### ISSUE THREAD

**Issue by plasticocelot123** [ShadowMario/FNF-PsychEngine#11396]
### What is your question?

Idea: Add a shop. It would make gameplay a lot better if you could start with a health boost or something. (Note: You WOULD have an option when you first start up the game to enable/disable the shop.) Ideas for shop items: Buying Weeks; You would have to go through the weeks in order to get the next weeks, leading up to week 7. 2nd Idea: Add Gameplay Boosts; This would mean you could spend currency (Of your choice) and buy boost that would give you a health boost, or a health regeneration effect. 3rd Idea: Currency by Beating Songs; If you beat a song, you get money. You would be able to spend that money on the shop. And THAT, is my idea for Psych Engine. Please add this.

**Comment by DabbinDude316B** [comment]
If you want this no.

if you want more features in general, yes

**Comment by Lorekeeper49** [comment]
First of all, wrong tag 
Secondly, there's a reason why people don't add a shop to their fnf engines

**Comment by DabbinDude316B** [comment]
> First of all, wrong tag Secondly, there's a reason why people don't add a shop to their fnf engines

`setPropertyFromClass('ShopState', 'coins', 999999999999999999999999999999)`

**Comment by CaptainBaldi** [comment]
this is the worst fucking idea ive ever seen for an engine

**Comment by Imashitheadthatducks** [comment]
EA engine

**Comment by Sword352** [comment]
No. and if you want it code it yourself bruh an engine has to add moddig features while being same as original.
