### ISSUE TITLE
how to make char info

### ISSUE THREAD

**Issue by guisende** [ShadowMario/FNF-PsychEngine#11391]
### Describe your problem here.

how im make this on source code pysch engine 0.5.2h

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
wdym

**Comment by guisende** [comment]
what?

**Comment by TheKitBoi** [comment]
explain what kind

**Comment by guisende** [comment]
as character description type mod documic.txt v2

**Comment by Imashitheadthatducks** [comment]
steal source code
