### ISSUE TITLE
Character wont load into chart 

### ISSUE THREAD

**Issue by TriUmph2025** [ShadowMario/FNF-PsychEngine#11392]
### Describe your problem here.

PlayState.hx (line 3075)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Ive changed no main components

**Comment by TheKitBoi** [comment]
send the broken char.json

**Comment by TriUmph2025** [comment]
I would but github doesn't support .json files

**Comment by TheKitBoi** [comment]
Rename .json to .txt

**Comment by TriUmph2025** [comment]
[Stickman.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/10149637/Stickman.txt)

How is this?

**Comment by TheKitBoi** [comment]
Your char has no health icon
replace "healthicon": "", with an name image from mode/images/icons "healthicon": "name",

**Comment by TriUmph2025** [comment]
I really didnt think that would make a difference! 
Alright I'll give that a shot

**Comment by TriUmph2025** [comment]
NICE! it worked. Thanks
