### ISSUE TITLE
most of the example links are dead links

### ISSUE THREAD

**Issue by Carss1235** [ShadowMario/FNF-PsychEngine#11395]
### What needs to be documented?

most of the example links on the LUA SCRIPT API page are dead links that lead to nothing

**Comment by TheKitBoi** [comment]
be patient until the new ones come in

**Comment by Imashitheadthatducks** [comment]
![BA1C9B58-6F80-45DF-994E-309508FADB2A](https://user-images.githubusercontent.com/119896118/205744564-9d29b7cf-5671-4c69-aa28-c24f249c8ea8.jpeg)
this will not age well

**Comment by Minalog** [comment]
they used fucking discord to host their files lol
weird but that's a way
