### ISSUE TITLE
How do I put 321 go in mid song

### ISSUE THREAD

**Issue by Fullpillpa** [ShadowMario/FNF-PsychEngine#11403]
So How do I put the 3 2 1 go in the during song?

**Comment by Cap6ailB3an** [comment]
look through Legacy endless code in here https://github.com/Zexlo/FNF-Sonic-EXE-psych-engine-port

**Comment by Fullpillpa** [comment]
Um I don't really know what do I do in code

**Comment by Cap6ailB3an** [comment]
go to data then Legacy endless

**Comment by Cap6ailB3an** [comment]
then come back

**Comment by frantastic24** [comment]
> because it is quite difficult to center them properly

1. It's simple math?
2. `screenCenter(obj)`

**Comment by ZeitHeld** [comment]
Oh, screenCenter does exist? Convenient.

I worried that screenCenter would put the origin (top left of the image) in
the middle. And not the middle.

So I think manually it would be kind of like screenHeight/2-image.height/2
as y and same with width instead for x
(I just forget to use math sometimes)

frantastic24 ***@***.***> schrieb am Mi., 7. Dez. 2022, 18:04:

**Comment by InsiderIV** [comment]
function onEvent(name, value1, value2)

 if name == 'startcountdown' then

  playSound('intro3',0.6)

  runTimer('wait2', crochet/1000)

 end

end

function onTimerCompleted(tag)

 if tag == 'wait2' then

  playSound('intro2',0.6)

  makeLuaSprite('countdownready', 'ready',262,178)

  setObjectCamera('countdownready', 'hud')

  addLuaSprite('countdownready', true)

  doTweenAlpha('readyend','countdownready',0,crochet/1000,'cubeInOut')

  runTimer('wait1', crochet/1000)

 end

 if tag == 'wait1' then

  playSound('intro1',0.6)

  makeLuaSprite('countdownset', 'set',289,199)

  setObjectCamera('countdownset', 'hud')

  addLuaSprite('countdownset', true)

  doTweenAlpha('setend','countdownset',0,crochet/1000,'cubeInOut')

  runTimer('waitgo', crochet/1000)

 end

 if tag == 'waitgo' then

  playSound('introGo',0.6)

  makeLuaSprite('countdowngo', 'go',361,145)

  setObjectCamera('countdowngo', 'hud')

  doTweenAlpha('goend','countdowngo',0,crochet/1000,'cubeInOut')

  addLuaSprite('countdowngo', true)

 end

end

function onCreate()

 setProperty('skipCountdown',true)

end


just use this as an event.
