### ISSUE TITLE
Thread.hx:26: characters 8-52 : This class is not available on this target

### ISSUE THREAD

**Issue by family1242** [ShadowMario/FNF-PsychEngine#1140]
### Describe your problem here.

When I compiled HTML5, I got an error:
lime test html5 -release
C:\HaxeToolkit\haxe\std/sys/thread/Thread.hx:26: characters 8-52 : This class is not available on this target

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

I don't think so. At least not recently.

**Comment by ShadowMario** [comment]
I am able to build it here, so you must have messed with something.

**Comment by ShadowMario** [comment]
Should be fixed now that i reverted a buggy PR
