### ISSUE TITLE
how do i fix this?

### ISSUE THREAD

**Issue by doitover** [ShadowMario/FNF-PsychEngine#11407]
### Describe your problem here.

I keep trying to load my new stage and it won't work.
![2022-12-04](https://user-images.githubusercontent.com/91207983/205513623-da26b5a9-3b89-44e8-be2d-37eeb88c926b.png)

![2022-12-04 (1)](https://user-images.githubusercontent.com/91207983/205513624-e4268074-d85a-4779-809a-bdbbe3c88d7a.png)

One is a picture of the error and the code.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by luacoder279** [comment]
try to set close to false
`close(false);`

**Comment by doitover** [comment]
didn't work.

**Comment by frantastic24** [comment]
What version are you using

**Comment by TheKitBoi** [comment]
Remove close()

**Comment by TheKitBoi** [comment]
He’s using os engine
![ECBE9972-FDC1-4749-901A-41AA1E4E8E33](https://user-images.githubusercontent.com/84044666/205515620-d32192af-39c6-45e0-a53e-15bcb3549476.jpeg)

**Comment by TheKitBoi** [comment]
> ### Describe your problem here.
> I keep trying to load my new stage and it won't work.

remove close()

**Comment by doitover** [comment]
> What version are you using

latest

**Comment by doitover** [comment]
> > ### Describe your problem here.
> > I keep trying to load my new stage and it won't work.
> 
> remove close()

I did.

**Comment by frantastic24** [comment]
> He’s using os engine

Cool
Why the fuck was this opened here

**Comment by doitover** [comment]
Because its forked from psych, and the code is the same.

**Comment by frantastic24** [comment]
It's a different engine, the code is not the same
This does not go here

**Comment by TheKitBoi** [comment]
Expect os shit

**Comment by doitover** [comment]
> It's a different engine, the code is not the same This does not go here

bro, yes it does

**Comment by TheKitBoi** [comment]
> > It's a different engine, the code is not the same This does not go here
> 
> bro, yes it does

What kind of brain cell tells you that tells you that os and psych are the same

**Comment by doitover** [comment]
> > > It's a different engine, the code is not the same This does not go here
> > 
> > 
> > bro, yes it does
> 
> What kind of brain cell tells you that tells you that os and psych are the same

![image](https://user-images.githubusercontent.com/91207983/205519748-5704f71f-15ac-49b8-9528-258a25c39a9a.png)

**Comment by TheKitBoi** [comment]
That’s a figure of speech

**Comment by doitover** [comment]
No, it literally means it uses the same code as OS engine. my fucking god. Learn some vocabulary.

**Comment by TheKitBoi** [comment]
You decide to spit words that make Psych Engine not having any rules about os engine
![34B69FD9-B77D-439C-BF11-9A492EC42A5A](https://user-images.githubusercontent.com/84044666/205519924-a5095d87-063e-41ba-9ffa-c2bf2bde38e2.jpeg)
There’s people in the psych discord server saying os engine and psych engine ain’t the same

**Comment by doitover** [comment]
7

> You decide to spit words that make Psych Engine not having any rules about os engine ![34B69FD9-B77D-439C-BF11-9A492EC42A5A](https://user-images.githubusercontent.com/84044666/205519924-a5095d87-063e-41ba-9ffa-c2bf2bde38e2.jpeg) There’s people in the psych discord server saying os engine and psych engine ain’t the same

Imagine digging in a discord server to prove yourself right.

**Comment by doitover** [comment]
OH NO! omg I'm so sorry please forgive me. bruh you think i give an actual fuck about you.

**Comment by frantastic24** [comment]
You don't even know what a fork is
If you're using another engine, go ask in that engine's repo

**Comment by doitover** [comment]
> You don't even know what a fork is If you're using another engine, go ask in that engine's reop

I ported it to psych and it still isn't working.

**Comment by Imashitheadthatducks** [comment]
> You decide to spit words that make Psych Engine not having any rules about os engine
> ![34B69FD9-B77D-439C-BF11-9A492EC42A5A](https://user-images.githubusercontent.com/84044666/205519924-a5095d87-063e-41ba-9ffa-c2bf2bde38e2.jpeg)
> There’s people in the psych discord server saying os engine and psych engine ain’t the same

Mf digging in ohio

**Comment by doitover** [comment]
> > You decide to spit words that make Psych Engine not having any rules about os engine
> > ![34B69FD9-B77D-439C-BF11-9A492EC42A5A](https://user-images.githubusercontent.com/84044666/205519924-a5095d87-063e-41ba-9ffa-c2bf2bde38e2.jpeg)
> > There’s people in the psych discord server saying os engine and psych engine ain’t the same
> 
> Mf digging in ohio

true shit bro

**Comment by Imashitheadthatducks** [comment]
I’m not on anyones side though, it literally says “forked from psych engine” meaning changes in the code are different

**Comment by doitover** [comment]
> Just because it uses it as a base, doesn’t mean it’s the same thing bro

Right, but stage code from psych should still work on OS engine.

**Comment by Imashitheadthatducks** [comment]
> > Just because it uses it as a base, doesn’t mean it’s the same thing bro
> 
> Right, but stage code from psych should still work on OS engine.

Did removing close() work tho

**Comment by doitover** [comment]
no

**Comment by doitover** [comment]
I don't know what to do. I've been doing this for like 12 hours.

**Comment by frantastic24** [comment]
> Right, but stage code from psych should still work on OS engine.

The error is pointing at PlayState, it's something else you messed up
Isn't OS source public? You can just go check those lines

**Comment by ManMaster707** [comment]
The problem may be that you typed in "addLuaSprite" twice in the code, and in one of the instances the code is being inputed before the sprite is even created.
I don't use OS engine, though since psych and OS are kinda similar, that could be the issue.

**Comment by ManMaster707** [comment]
> > You decide to spit words that make Psych Engine not having any rules about os engine
> > ![34B69FD9-B77D-439C-BF11-9A492EC42A5A](https://user-images.githubusercontent.com/84044666/205519924-a5095d87-063e-41ba-9ffa-c2bf2bde38e2.jpeg)
> > There’s people in the psych discord server saying os engine and psych engine ain’t the same
> 
> Mf digging in the Chernobyl toxic discord server

FAX, someone asks a question and gets fucking bombed on 😭

**Comment by Gostar64** [comment]
I think it's because you have an extra addLuaSprite at the beginning
so it should be
```Lua
function onCreate()
  makeLuaSprite('chapter1', 'chapter1', -600, -300);
  setScrollFactor('chapter1', 0.9, 0.9)
  
  addLuaSprite('chapter1', false)

  close(true)
end

**Comment by doitover** [comment]
It didn't work.

**Comment by MemeHovy** [comment]
> It didn't work.


https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/42208bda-772b-4afa-96f0-4cd79277e2b3
