### ISSUE TITLE
os engine migration

### ISSUE THREAD

**Issue by lime360** [ShadowMario/FNF-PsychEngine#11408]
### What is your question?

should i migrate [my mod](https://github.com/lime360/FNF-VS-lime360) into os engine? if so, then please tell me how do i import features i added in vs lime360 engine (modded psych engine 0.6.3), being only font shit and credits stuff in the charts

**Comment by TheKitBoi** [comment]
This repo is not the place for os engine talk

**Comment by lime360** [comment]
ik but os engine is based on pysch engine

**Comment by lime360** [comment]
screw this I'm closing the issue
