### ISSUE TITLE
Anim Jitter Hold Note

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#11405]
### What is your question?

I've seen a lot of character that dosen't matter the bpm or anything they jitter when holding a note but, is a little bit crazy, but I like that the characters jitter when holding a note. So can you say to me if is there anything to do for that the animations jitter no matter the bpm or anything, pls???

**Comment by TheKitBoi** [comment]
That how it supposed to work
and no one’s argues about it

**Comment by GatoMorado621** [comment]
> That how it supposed to work and no one’s argues about it

So I cannot do anything like in adobe animate to make them jitter???

**Comment by TheKitBoi** [comment]
for the char editor add the anim-hold for each pose to 1 frame

**Comment by GatoMorado621** [comment]
> for the char editor add the anim-hold for each pose to 1 frame

How???
I just put in the advanced (animations indices) the number 0 that will be the first frame???

**Comment by GatoMorado621** [comment]
> for the char editor add the anim-hold for each pose to 1 frame

So I just put the 0 in the animation indices (advanced) that wil be the first frame???

**Comment by TheKitBoi** [comment]
yes

**Comment by GatoMorado621** [comment]
> yes

Ok, let me try it

**Comment by GatoMorado621** [comment]
> yes

It didn't work

**Comment by GatoMorado621** [comment]
> yes

Nvm I fixed it. I just need to remove one frame in adobe animate. Thank you anyway for the help
