### ISSUE TITLE
Shadow Ref Character Editor

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#11413]
### Describe your problem here.

I was wondering if I can put like a shadow character in the position of the main character to get an idea of where need to be the character in the character editor. Is like yoshi engine. If someone can help me with this I would really appreciate it a lot

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Imashitheadthatducks** [comment]
speak english

**Comment by Imashitheadthatducks** [comment]
> > speak english
> 
> ???

I literally had to read this 7 times over to make sure I wasn’t tripping balls

**Comment by GatoMorado621** [comment]
> > > speak english
> > 
> > 
> > ???
> 
> I literally had to read this 7 times over to make sure I wasn’t tripping balls

Oh

**Comment by Mokona5901** [comment]
Oh i understand what you mean

**Comment by GatoMorado621** [comment]
> Oh i understand what you mean (I never used yoshi engine 🗿)

😐

**Comment by RubenDatOneBoi3446** [comment]
to have the idle in the bg as a shadow, so you can make the positioning of the other anims right

**Comment by GatoMorado621** [comment]
> to have the idle in the bg as a shadow, so you can make the positioning of the other anims right

I didn't understand. You mean like the ghost of the character??

**Comment by RubenDatOneBoi3446** [comment]
yes

**Comment by RubenDatOneBoi3446** [comment]
wait- 
nvm imma go

**Comment by GatoMorado621** [comment]
> wait- nvm imma go

Ok?
