### ISSUE TITLE
feature request: a noteskin selector in the settings menu

### ISSUE THREAD

**Issue by fnfporterhi** [ShadowMario/FNF-PsychEngine#11418]
### What feature do you want to get added on the **base** engine?

like dave and bambi, but not the characters, cause some people cant read arrows, and some can only read bars, so like you could have like osu circles, regular notes, or bars.

seems like a good idea.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Imashitheadthatducks** [comment]
Shadow fuck you man, we needed this

**Comment by CaptainBaldi** [comment]
just replace the note assets :skull:

**Comment by fnfporterhi** [comment]
EXACTLY! FUCK SHADOW!

**Comment by TheKitBoi** [comment]
Why argue
Learn and do it your self

**Comment by Imashitheadthatducks** [comment]
> Why argue
> Learn and do it your self

Ok but why not just add it to the engine so you don’t have to do it or download a shady build of the dark web

**Comment by CaptainBaldi** [comment]
> > just replace the note assets 💀
> 
> But that’s time consuming, why not just have a menu where you can change it (won’t apply for death notes)

beggars cant be choosers
if you're too lazy to code it yourself and you're scared of a "shady build", then do the alternative and replace the note assets

**Comment by Imashitheadthatducks** [comment]
> > > just replace the note assets 💀
> > 
> > 
> > But that’s time consuming, why not just have a menu where you can change it (won’t apply for death notes)
> 
> beggars cant be choosers if you're too lazy to code it yourself and you're scared of a "shady build", then do the alternative and replace the note assets

or

**Comment by DabbinDude316B** [comment]
> > Why argue
> > Learn and do it your self
> 
> Ok but why not just add it to the engine so you don’t have to do it or download a shady build off the dark web

Is that “extreme laziness” i see?

**Comment by Imashitheadthatducks** [comment]
> > > Why argue
> > > Learn and do it your self
> > 
> > 
> > Ok but why not just add it to the engine so you don’t have to do it or download a shady build off the dark web
> 
> Is that “extreme laziness” i see?

yes

**Comment by Imashitheadthatducks** [comment]
:trollface:

**Comment by fnfporterhi** [comment]
:trollface:

**Comment by Average-FNF-Modder** [comment]
"Won't do" lol
