### ISSUE TITLE
feature request: rating counter

### ISSUE THREAD

**Issue by fnfporterhi** [ShadowMario/FNF-PsychEngine#11417]
### What feature do you want to get added on the **base** engine?

a rating counter. there are some modded songs that are so fuckin fast, to the point you cant tell how many sicks/goods/misses you have, so thats why i think a rating counter would be a good idea to add to the engine.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by fnfporterhi** [comment]
1st of all. rude
2nd of all, i suck at coding

**Comment by TheKitBoi** [comment]
https://discord.com/channels/922849922175340586/1030643487735042098

**Comment by CaptainBaldi** [comment]
> 1st of all. rude 2nd of all, i suck at coding

its not my fault you dont know how to code very basic stuff

**Comment by fnfporterhi** [comment]
reopened cause this is something that might be added into the engine

**Comment by MaybeMaru** [comment]
no?

**Comment by fnfporterhi** [comment]
?

**Comment by ShadowMario** [comment]
That's not happening

**Comment by fnfporterhi** [comment]
mk
