### ISSUE TITLE
Freeplay Center

### ISSUE THREAD

**Issue by RubenDatOneBoi3446** [ShadowMario/FNF-PsychEngine#11419]
### What is your question?

How do i make the freeplay menu in the middle of the screen

**Comment by Imashitheadthatducks** [comment]
![F58ECC46-65CB-4DCB-A3EC-E49F31B435C9](https://user-images.githubusercontent.com/119896118/205745639-b2c3257e-bbe7-4485-b8bf-874ec0a7ccd8.jpeg)
i am inside of your walls

**Comment by Imashitheadthatducks** [comment]
omg please dont tell me this is dave and bambi again

**Comment by RubenDatOneBoi3446** [comment]
i just wanna figure out how to make the freeplay menu in the center

**Comment by RubenDatOneBoi3446** [comment]
also what is it with people in psych engine related stuff and dnb

**Comment by TheKitBoi** [comment]
https://github.com/nebulazorua/tails-gets-trolled-v3/blob/master/source/states/FreeplayState.hx

**Comment by Imashitheadthatducks** [comment]
crisis averted

**Comment by Imashitheadthatducks** [comment]
![DD2B4A31-A663-422F-A8CC-5FFB79ADF41D](https://user-images.githubusercontent.com/119896118/206018777-27e37156-da95-44a4-9dfa-99b8935ec6dd.jpeg)
nice bio

**Comment by RubenDatOneBoi3446** [comment]
thanks btw <3

**Comment by Imashitheadthatducks** [comment]
that was sarcasm, your bio made me believe someone can have 88 heart attacks from words

**Comment by RubenDatOneBoi3446** [comment]
thanks

**Comment by RubenDatOneBoi3446** [comment]
that was all sarcasm as well bru

**Comment by RubenDatOneBoi3446** [comment]
mofo instead of making fun of me for using a dnb example can you actually HELP?

**Comment by Imashitheadthatducks** [comment]
Steal source code from tails gets trolled

**Comment by RubenDatOneBoi3446** [comment]
i mean obviously, but i dont exactly know what to take, i dont know anything abt code

**Comment by RubenDatOneBoi3446** [comment]
Can someone ACTUALLY help me?

**Comment by RubenDatOneBoi3446** [comment]
wait- lemme try again thx

**Comment by RubenDatOneBoi3446** [comment]
Where exactly do i put this in freeplay state, do i just put it where its supposed to originally be?

> > Can someone ACTUALLY help me?
> 
> yk fuck you here is the code (not mine + probably dont take it.) if (isMenuItemCenter) { var scaledY = FlxMath.remapToRange(targetY, 0, 1, 0, 1.3);
> 
> ```
> 			var lerpVal:Float = CoolUtil.boundTo(elapsed * 9.6, 0, 1);
> 			y = FlxMath.lerp(y, (scaledY * yMult) + (FlxG.height * 0.48) + yAdd, lerpVal);
> 			if(forceX != Math.NEGATIVE_INFINITY) {
> 				screenCenter(X);
> 			} else {
> 				screenCenter(X);
> 			}
> 		}
> ```

**Comment by Imashitheadthatducks** [comment]
> > Can someone ACTUALLY help me?
> 
> yk fuck you here is the code (not mine + probably dont take it.) if (isMenuItemCenter) { var scaledY = FlxMath.remapToRange(targetY, 0, 1, 0, 1.3);
> 
> ```
> 			var lerpVal:Float = CoolUtil.boundTo(elapsed * 9.6, 0, 1);
> 			y = FlxMath.lerp(y, (scaledY * yMult) + (FlxG.height * 0.48) + yAdd, lerpVal);
> 			if(forceX != Math.NEGATIVE_INFINITY) {
> 				screenCenter(X);
> 			} else {
> 				screenCenter(X);
> 			}
> 		}
> ```

Uhh your twitter got deleted
https://twitter.com/FGJFB_NEWS

**Comment by RubenDatOneBoi3446** [comment]
yknow what i got it

**Comment by Deity03-star** [comment]
@RubenDatOneBoi3446 i need help with this actually
