### ISSUE TITLE
Psych engine crashes when I import a Yoshi engine chart.

### ISSUE THREAD

**Issue by RushMyster** [ShadowMario/FNF-PsychEngine#11412]
### What is your question?

idk if i should put this here or Yoshi engine's github but when i import a Yoshi engine chart it displays this message: "Conductor.hx (line119)
editors/ChartingState.hx (line 292)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)

Uncaught Error: Null Object Reference"
idk if this is a Psych bug or Yoshi, I can repost to Yoshi engine if this is a problem leaning towards them.

**Comment by TheKitBoi** [comment]
Go here
https://github.com/YoshiCrafter29/YoshiCrafterEngine/issues
and find an issue that looks similar

**Comment by TheKitBoi** [comment]
Yoshi Engine Chart export is different that psych

**Comment by RushMyster** [comment]
Is there any way of getting it to work? Ive made most of my mods on Yoshi Engine with intent of bringing them to Psych Engine

**Comment by Imashitheadthatducks** [comment]
oh boy you better enjoy recharting things
![AE73D9FF-DB35-4967-B405-9C804FAE8082](https://user-images.githubusercontent.com/119896118/205743382-622d2be1-b844-4ad9-8d9f-77f6ba304a2d.png)

**Comment by darkresident55** [comment]
it has to depend if it has events in the song. i imported a yoshi chart and it worked for me

**Comment by RushMyster** [comment]
I got the charts working :DDDDD
