### ISSUE TITLE
why isn't pico speaker working in different songs

### ISSUE THREAD

**Issue by MysticFox990** [ShadowMario/FNF-PsychEngine#11410]
### Describe your problem here.

I'm trying to figure out why pico speaker isn't working on other songs and all the crash text say is 

TankmenBG.hx (line 27)
PlayState.hx (line 955)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

 and I'm not even using source code

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

**Comment by TheKitBoi** [comment]
It’s only hard coded into week 7 only

**Comment by MysticFox990** [comment]
> It’s only hard coded into week 7 only

do you think it will work if I make a separate character file

**Comment by TheKitBoi** [comment]
Yeah

**Comment by MysticFox990** [comment]
> Yeah

it worked thanks
