### ISSUE TITLE
This is source. It tells me to set HXCPP_MSVC_CUSTOM and configure the executable, but I do not know how.

### ISSUE THREAD

**Issue by Raxusd** [ShadowMario/FNF-PsychEngine#11421]
### Describe your problem here.

no code input, so I will put code here. C:\Users\noneya\Desktop\Psychsourcebreh>lime test windows
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\noneya\Desktop\Psychsourcebreh\export\release\windows\obj>setlocal enabledelayedexpansion
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing edited

**Comment by DisIsNOt** [comment]
Bro use the frickin search bar 
And install MSVC 2019
