### ISSUE TITLE
advanced copy-paste / copy slots

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#11426]
### What feature do you want to get added on the **base** engine?

Multiple copy slots for when you want to repeat a part of the chart from earlier in the song, but you don't want to go all the way back to copy-paste over and over again to get the whole part copy-pasted over.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Imashitheadthatducks** [comment]
pretty sure what they want is the ability to select sections and copy it

**Comment by Lorekeeper49** [comment]
> pretty sure what they want is the ability to select sections and copy it

That's exactly what the copy last section counter does

**Comment by ZeitHeld** [comment]
you can use copy last section, but let it go into the negatives

**Comment by Imashitheadthatducks** [comment]
> > pretty sure what they want is the ability to select sections and copy it
> 
> That's exactly what the copy last section counter does

exactly

**Comment by Imashitheadthatducks** [comment]
but he wants to copy more sections than 1

**Comment by creeperkidking** [comment]
ye

**Comment by ZeitHeld** [comment]
It would be easy to implement with recursion and for loop, but I think if
you forget about it, you can mess up your chart quite much.
As there is no real undo button. Or I do not recall there being one.

TheCreeperKidKing ***@***.***> schrieb am Mi., 7. Dez. 2022,
17:37:
