### ISSUE TITLE
Error message when opening modded week in story tab.

### ISSUE THREAD

**Issue by WindowsGod2** [ShadowMario/FNF-PsychEngine#11429]
### Describe your problem here.

I was transferring files from an older psyche engine model (ver 0.4.2) to the most recent build (ver 0.6.3) so I could have a better experience, and everything was going fine and dandy until I tried playing the first week in my mod. This showed up and I'm not sure how to handle/fix it.
![2022-12-06 (1)](https://user-images.githubusercontent.com/102393943/206103256-1f7ebbb0-72d1-4bdb-91bd-724c01159554.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
Check ur mods/images/menucharacters
