### ISSUE TITLE
Centered freeplay help

### ISSUE THREAD

**Issue by RubenDatOneBoi3446** [ShadowMario/FNF-PsychEngine#11427]
### Describe your problem here.

How do i make the freeplay menu centered in 0.6.3

#11419

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Imashitheadthatducks** [comment]
did you seriously copy your issue twice

**Comment by Imashitheadthatducks** [comment]
Your gonna get banned you gay ass fucking furry

**Comment by RubenDatOneBoi3446** [comment]
ill delete it lmao

**Comment by RubenDatOneBoi3446** [comment]
or close it
