### ISSUE TITLE
a little rare bug

### ISSUE THREAD

**Issue by Galaxia224YT** [ShadowMario/FNF-PsychEngine#11428]
### Describe your bug here.

is very hard to describe.. Literally say this 
![image](https://user-images.githubusercontent.com/119993377/206082854-c3bca6db-f69c-4e77-994f-6423e566d88c.png)

someone can help me?

### Command Prompt/Terminal logs (if existing)

```bash
No, i don't know.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i added a new character and two songs news

**Comment by Galaxia224YT** [comment]
pls :C

**Comment by frantastic24** [comment]
This doesn't match with psych's code, are you using a fork? If so then this doesn't go in this repo

**Comment by DisLolTV** [comment]
I think this is duplicate of one of my older Issues with psych engine. It can be something in arrows.
