### ISSUE TITLE
5-second transitions

### ISSUE THREAD

**Issue by DarkMinerULTRA** [ShadowMario/FNF-PsychEngine#11431]
### Describe your bug here.

This has happened with all the psych engine mods I have on my computer at the moment, other engines like Forever Engine don't have the bug. The fading gradient transitions take about 5 seconds to fully complete and the game is extremely laggy until I open a song. The video i recorded is too big so you can't see it :(

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

All i did was change the intro and add some characters. This bug wasn't me, though, as other psych engine mods have it too.

**Comment by Imashitheadthatducks** [comment]
your computer sucks

**Comment by frantastic24** [comment]
Is it laggy or just slow but smooth animation/movement
Forcing vsync on causes the latter

**Comment by DarkMinerULTRA** [comment]
hm yea it's the second one. how do i fix that?

**Comment by frantastic24** [comment]
Turn vsync off in your graphics card/driver settings

**Comment by DarkMinerULTRA** [comment]
it's fixed! tysm :)
