### ISSUE TITLE
Lua sprites

### ISSUE THREAD

**Issue by JVgradiz** [ShadowMario/FNF-PsychEngine#11435]
### Describe your problem here.

i need an Lua Sprite to apear in front of dad and behind bf at the same time

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#object-orderremoving

**Comment by DisIsNOt** [comment]
setObjectOrder('dad', 3)
setObjectOrder ('mid', 2)
setObjectOrder ('bf', 1)

idk

**Comment by JVgradiz** [comment]
Thanks
