### ISSUE TITLE
Is there any way to have a note do a dodge animation on miss but not count AS a miss

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#11438]
### Describe your problem here.

So basically, what it boils down to is having function noteMiss activate so it'll play a dodge animation on it, but not have to deal with the consequences of it counting as miss.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by wubbzyfan** [comment]
HEY

**Comment by wubbzyfan** [comment]
ANYONE

**Comment by wubbzyfan** [comment]
@ShadowMario MUST I SACRAFICE A LAMB

**Comment by wubbzyfan** [comment]
@frantastic24 ples

**Comment by TheKitBoi** [comment]
don’t ping him
be patient

**Comment by DabbinDude316B** [comment]
You can play animations in the chart at the most, you need source for it to actually happen that way

**Comment by Draconic-Hybrid** [comment]
Add `setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true);` in the `function onCreate()` in your custom note.

In `function noteMiss()` you put `playAnim('boyfriend', '[whatever your dodge animation is named]', true);`

**Comment by DabbinDude316B** [comment]
> Add `setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true);` in the `function onCreate()` in your custom note.
> 
> In `function noteMiss()` you put `playAnim('boyfriend', '[whatever your dodge animation is named]', true);`

Ignore note makes it so notes don’t count as a miss, so noteMiss will do nothing.

**Comment by Draconic-Hybrid** [comment]
What about `strumNoteHit` then? I've seen it before, although I'm less sure about it. Theoretically, it triggers when a note hits a strum, right? Or is it when either player hits a note?
