### ISSUE TITLE
how do i port a psych engine chart to yoshi engine

### ISSUE THREAD

**Issue by RubenDatOneBoi3446** [ShadowMario/FNF-PsychEngine#11436]
### What is your question?

im tryna do smth on yoshi engine yet i need to port a mod to it from psych engine
how do i port psych engine charts to yoshi engine?

**Comment by Imashitheadthatducks** [comment]
![F23574C8-E4A5-4186-A02B-34E153A67406](https://user-images.githubusercontent.com/119896118/206514199-f6e2fe41-3947-4426-ae18-9d5d3f8e4067.gif)

**Comment by Imashitheadthatducks** [comment]
Duplicate of #11412

we have a search bar Y’know

**Comment by RubenDatOneBoi3446** [comment]
think you coulda just said that? but thanks
