### ISSUE TITLE
Give opponent their own note colors?

### ISSUE THREAD

**Issue by luigiman0** [ShadowMario/FNF-PsychEngine#11442]
### What is your question?

Is there any way to give the opponent their own note colors using Lua?

There's not really much to explain with this one, basically just a script that can somewhat emulate how the note color thing works maybe? Or just a script that changes the opponents notes to a different png works as well.

**Comment by redninja768** [comment]
https://www.mediafire.com/file/ddznxnaiq55r13p/opponentnote.lua/file

Try using this.
This might help
