### ISSUE TITLE
Uncaught Error: Null Object Reference

### ISSUE THREAD

**Issue by josesm18** [ShadowMario/FNF-PsychEngine#11443]
### Describe your bug here.

since I edited to add events it doesn't let me enter

### Command Prompt/Terminal logs (if existing)

```bash
Error!
flixel/graphics/frames/FlxAtlas Frames.hx (line 250)
i
Character.hx (line 164)
PlayState.hx (line 1542)
PlayState.hx (line 2600)
PlayState.hx (line 2570)
PlayState.hx (line 1086)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402) openfl/display/DisplayObject.hx (line 1399)
Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine
> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Not a bug
The character you're trying to add is missing texture files

**Comment by notzthatone** [comment]
that happened to me

**Comment by DisLolTV** [comment]
WARNING: Not all Null Object Refrences all the same. Please just send the Issue to Github to let everyone to check it.
