### ISSUE TITLE
opponent over the hud 

### ISSUE THREAD

**Issue by MysticFox990** [ShadowMario/FNF-PsychEngine#11445]
### Describe your problem here.

is there a way to have the opponent over the hud?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions

**Comment by MysticFox990** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions

can i get an example?

**Comment by frantastic24** [comment]
The wiki explains what each value is

**Comment by MysticFox990** [comment]
> The wiki explains what each value is

I know but I already tried doing it

**Comment by Drawoon2** [comment]
`setObjectCamera('dad', 'hud')`
