### ISSUE TITLE
I'm using psych engine 0.5.2h

### ISSUE THREAD

**Issue by husseinalaaplayz** [ShadowMario/FNF-PsychEngine#11447]
### Describe your bug here.

Hi there is a bug where the engine doesn't open on my laptop is there any way to get rid of it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I didn't

**Comment by DisLolTV** [comment]
Just restart laptop or delete some files in your pc.
Delete files from : prefetch (all of them because they are apps instalation files), temp and %temp% (much as you can because they are tempoary files), appdata and %appdata% (App data so delete only files from apps you deleted).
