### ISSUE TITLE
notes behind the player or the opponent?

### ISSUE THREAD

**Issue by MysticFox990** [ShadowMario/FNF-PsychEngine#11444]
### What feature do you want to get added on the **base** engine?

an event or option in the chart editor that makes the notes behind the player and/or the opponent

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by frantastic24** [comment]
No one's gonna use that and it's just distracting??

**Comment by Lorekeeper49** [comment]
Test = failed

**Comment by Stilic** [comment]
> 

sorry but you are wrong
soulless dx has that effect on a song
it looks very cool

**Comment by Stilic** [comment]
> No one's gonna use that and it's just distracting??

sorry but you are wrong
soulless dx has that effect on a song
it looks very cool

**Comment by frantastic24** [comment]
Damn!! One song!! That's so many!!

**Comment by Stilic** [comment]
> 

wtf

**Comment by Stilic** [comment]
> Damn!! One song!! That's so many!!

wtf

**Comment by MysticFox990** [comment]
> No one's gonna use that and it's just distracting??

distracting is the point

**Comment by MaybeMaru** [comment]
Test failed, also you can do this with hscript easily

**Comment by ShadowMario** [comment]
Too much of an issue for a thing that will very likely not be used in many mods.
