### ISSUE TITLE
So apparently memebitchy didn’t get off the internet like they should’ve

### ISSUE THREAD

**Issue by Imashitheadthatducks** [ShadowMario/FNF-PsychEngine#11441]
### What is your question?

Their yt channel https://www.youtube.com/channel/UCMh09vutNZAA6y1ogPqq_9Q
There was a video posted 2 days ago on there, the drama was a month ago.

DEAR GOD, they should change their name to isiah weston chandler at this point. 
Seriously, you post fucking nsfw and your view hungry ass thinks you can get away with it.

Mass report this mf for what they have done, don’t let them be able to ban evade either.

that aint an instance bitch

proof they posted nsfw #11150
![8FCF3E2B-99CA-4F9F-AEE1-45FF68E0C3C2](https://user-images.githubusercontent.com/119896118/206518613-bbce2e0a-b615-4b59-be8a-e6a19c705f3b.png)

**Comment by bruh1cat** [comment]
You want to ban memehoovy from youtube bc he posted nsfw in github? He's alr banned from github whats the point of banning him form youtube?

**Comment by Imashitheadthatducks** [comment]
> You want to ban memehoovy from youtube bc he posted nsfw in github? He's alr banned from github whats the point of banning him form youtube?

Your question is the same as “amoraltra groomed children on discord so what’s the point of cancelling him on other platforms?”

**Comment by bruh1cat** [comment]
> > You want to ban memehoovy from youtube bc he posted nsfw in github? He's alr banned from github whats the point of banning him form youtube?
> 
> 
> 
> Your question is the same as “amoraltra groomed children on discord so what’s the point of cancelling him on other platforms?”

Grooming aint the same thing as posting nsfw and he hasn't posted nsfw on his youtube either, so I don't see a reason for banning him on other platforms.

**Comment by EpicShapeShifter** [comment]
What does this have to do with Psych Engine exactly?

**Comment by bruh1cat** [comment]
> What does this have to do with Psych Engine exactly?

Nothing with psych tho a bit with this repo.

**Comment by DisIsNOt** [comment]
Not a psych engine related issue + burh

**Comment by CrusherNotDrip** [comment]
if issues for this repo gets closed its gonna be because of issues like this
