### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by WillyPlayz** [ShadowMario/FNF-PsychEngine#11454]
### Describe your problem here.

source/Main.hx:78: characters 61-65 : Float should be Int
source/Main.hx:78: characters 61-65 : For optional function argument 'updateFramerate'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just downloaded

**Comment by PDL2CGamejolt** [comment]
Basically, you’ll need to modify the Main.hx file because Haxe updated and now you’ll need to change the code.

**Comment by PDL2CGamejolt** [comment]
![3A333306-EB64-40AA-AB2E-B5E2B520015C](https://user-images.githubusercontent.com/94698464/206869028-f5855c29-5b3d-4635-8f7f-fa445973b4ee.jpeg)
![9A6890D3-27CD-499B-A892-C7F8A2569E45](https://user-images.githubusercontent.com/94698464/206869030-dadfa330-d12c-4149-af58-77a47beb4a88.jpeg)
I did this in my Source Code modification called “FNF: Payten Edition” and it now compiles.

**Comment by WillyPlayz** [comment]
@PDL2CGamejolt Now it gives me : source/FunkinLua.hx:491: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:509: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:515: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:567: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:573: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:613: lines 613-617 : Int should be Bool
source/FunkinLua.hx:613: lines 613-617 : For function argument 'f'

**Comment by WillyPlayz** [comment]
You just gave me code that changed nothing

**Comment by PDL2CGamejolt** [comment]
> You just gave me code that changed nothing

…

**Comment by PDL2CGamejolt** [comment]
> You just gave me code that changed nothing

Oh

**Comment by TheKitBoi** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx
then replace ur main.hx

**Comment by WillyPlayz** [comment]
@TheKitBoi Solved!
