### ISSUE TITLE
Score with botplay on

### ISSUE THREAD

**Issue by SteveeTheCreeper** [ShadowMario/FNF-PsychEngine#11451]
### What is your question?

Can someone tell me how to add score when botplay is on?
Like if the note is hit and it's sick, good, etc.. then addscore(value) but in a lua script

**Comment by TheKitBoi** [comment]
That will break score records and replace your score

**Comment by SteveeTheCreeper** [comment]
> That will break score records and replace your score

I don't care
I just want it for gameplays

**Comment by SteveeTheCreeper** [comment]
.

**Comment by CaptainBaldi** [comment]
> > That will break score records and replace your score
> 
> I don't care I just want it for gameplays

aka he wants it so he can post his fake scores on youtube to attempt to be the next flippy

**Comment by frantastic24** [comment]
[Score Functions](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#scoreaccuracy-functions)
[Variables](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Variables#gameplay-variables)

**Comment by SteveeTheCreeper** [comment]
> > > That will break score records and replace your score
> > 
> > 
> > I don't care I just want it for gameplays
> 
> aka he wants it so he can post his fake scores on youtube to attempt to be the next flippy

Iam just using it cuz of my android corruption recreation and I want it to look like the original vid but I suck at upscroll so that's all

**Comment by fnfporterhi** [comment]
I don't think this will be added into the base engine, because someone could easily remove the botplay text, claim they got a world record (even though they didn't), and then they would become the next SillyFanGirl.

**Comment by fnfporterhi** [comment]
It is a great question though. Just it's not that much needed in the engine.

**Comment by fnfporterhi** [comment]
> > > > That will break score records and replace your score
> > > 
> > > 
> > > I don't care I just want it for gameplays
> > 
> > 
> > aka he wants it so he can post his fake scores on youtube to attempt to be the next flippy
> 
> I just want to use it cuz of my android corruption recreation and I want it to look like the original vid but I suck at upscroll so that's all

What video? Why would you want to recreate a video about that? I know your type of people, and you all want to be the BEST FNF player in the world, even though you suck at it. I will say one thing about this, and then I'm leaving this issue. \
Get.
Good.
At. 
The.
Game.
Then, if you're good, and somehow break a good world record, then yes, you can post it to youtube. It's a dumb idea to copy others stuff. CaptainBaldi, I completley agree. He just wants to get FC's for content and subs on youtube. Stupid. Fucking Stupid.

**Comment by SteveeTheCreeper** [comment]
> > > > > That will break score records and replace your score
> > > > 
> > > > 
> > > > I don't care I just want it for gameplays
> > > 
> > > 
> > > aka he wants it so he can post his fake scores on youtube to attempt to be the next flippy
> > 
> > 
> > I just want to use it cuz of my android corruption recreation and I want it to look like the original vid but I suck at upscroll so that's all
> 
> What video? Why would you want to recreate a video about that? I know your type of people, and you all want to be the BEST FNF player in the world, even though you suck at it. I will say one thing about this, and then I'm leaving this issue. Get. Good. At. The. Game. Then, if you're good, and somehow break a good world record, then yes, you can post it to youtube. It's a dumb idea to copy others stuff. CaptainBaldi, I completley agree. He just wants to get FC's for content and subs on youtube. Stupid. Fucking Stupid.

Dude
I swear to god I'm good at the game
It's just that I'm trying to make my corruption videos look like the original
Here is my yt channel for prove dude
https://youtube.com/@SteveTheCreeper
