### ISSUE TITLE
A Stage Editor

### ISSUE THREAD

**Issue by Raulmegapro2303** [ShadowMario/FNF-PsychEngine#11452]
### What is your question?

Please Made A Stage Editor

**Comment by bruh1cat** [comment]
![image](https://user-images.githubusercontent.com/98327930/206863377-01701acf-70ff-4f73-ac2e-5d7ecc047280.jpeg)

**Comment by ShadowMilky** [comment]
> ### What is your question?
> Please Made A Stage Editor

ARE YOU BLIND
SHADOW MARIO DOESNT ALLOW THAT BRUH

**Comment by Raulmegapro2303** [comment]
> ### What is your question?
> Please Made A Stage Editor

**Comment by ShadowMilky** [comment]
oh thank god

**Comment by PDL2CGamejolt** [comment]
> oh thank god

OMG!
