### ISSUE TITLE
Missing Documentation/Need Help: Animation indices

### ISSUE THREAD

**Issue by crispyi2** [ShadowMario/FNF-PsychEngine#1145]
### What needs to be documented?

I was adding a character and couldn't help but notice the Animation Indices section in the character editor.

I can't find the documentation for it, so either I'm blind or there isn't any

if there isn't any documentation for it I would greatly appreciate if someone told me what it was for

![Screenshot 2021-11-18 191917](https://user-images.githubusercontent.com/49764346/142517732-e3d14495-cbfd-4b06-baee-e84a731b1f6f.png)

**Comment by MayoALT** [comment]
basically, you insert which frames to play manually instead of it automatically doing it through xml names
ex: 1,2,3,5
this example will make it so it DOESNT play frame 4, if left blank then it will play all frames in order

**Comment by crispyi2** [comment]
> basically, you insert which frames to play manually instead of it automatically doing it through xml names ex: 1,2,3,5 this example will make it so it DOESNT play frame 4, if left blank then it will play all frames in order

Ohhhh thx for letting me know :)
