### ISSUE TITLE
how to use the animation indices

### ISSUE THREAD

**Issue by ChickenSwimmer2020** [ShadowMario/FNF-PsychEngine#11457]
### Describe your problem here.

so. lemme set the stage for my issues. I'm developing an fnf mod with psych engine and for my custom player sprite sheet the microphone spins for all directional animations. however, the animations completely break down when a held note is pressed. and so I thought I could set up animation indices to make it so the mic spins for the whole of the held note. but whenever I try to use the animation indices. I always get the (ERROR!) so I don't understand how to use it. does anyone know? if you do know how to use the animation indices then pls tell me.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no the most i have done is added a week 3 songs and 2 characters each with completely working jsons/xmls

**Comment by TheKitBoi** [comment]
0,1,2,3
There counted for each frame of the anim

**Comment by ChickenSwimmer2020** [comment]
ok. but everytime it still gives me an error! i don't know why tho I do it like the gf spritesheet but it wont work

**Comment by BernardoGP4504** [comment]
on the character editor, open the anim you want to add indices then find a field that says something about indices then add the indices like this: `0,1,2,3,4`

**Comment by ChickenSwimmer2020** [comment]
thats the exact thing i did and it only gave me errors. could the problem be that I'm using the newest version of phsych engine or adobe animate? or possibly the fact that I'm using a custom character spritesheet?

**Comment by HamsterMiguelGH** [comment]
It is possible that you put the wrong animation .xml/.txt file for example: in the pibby scout mod, the oof animation is supposed to be oof_ instead of oof. Look in the .txt/.xml file.
