### ISSUE TITLE
How do I make when the enemy sings the camera follows the enemy's movements

### ISSUE THREAD

**Issue by Missa13** [ShadowMario/FNF-PsychEngine#1146]
### Describe your problem here.

Is it an event or a script I need help on this pls help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

**Comment by DEV-idiotXD** [comment]
code (riped from fnf vandalizization


local followchars = true;
local ofs = 50;
local xx2 = 952.9;
local yy2 = 350;
local xx = 420.95;
local yy = 313;


function onUpdate()
	    if followchars == true then
        if mustHitSection == false then
            setProperty('defaultCamZoom',1.2)
            if getProperty('dad.animation.curAnim.name') == 'singLEFT' then
                triggerEvent('Camera Follow Pos',xx-ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singRIGHT' then
                triggerEvent('Camera Follow Pos',xx+ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singUP' then
                triggerEvent('Camera Follow Pos',xx,yy-ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singDOWN' then
                triggerEvent('Camera Follow Pos',xx,yy+ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singLEFT-alt' then
                triggerEvent('Camera Follow Pos',xx-ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singRIGHT-alt' then
                triggerEvent('Camera Follow Pos',xx+ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singUP-alt' then
                triggerEvent('Camera Follow Pos',xx,yy-ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singDOWN-alt' then
                triggerEvent('Camera Follow Pos',xx,yy+ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'idle-alt' then
                triggerEvent('Camera Follow Pos',xx,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'idle' then
                triggerEvent('Camera Follow Pos',xx,yy)
            end
        else

            setProperty('defaultCamZoom',0.9)
            if getProperty('boyfriend.animation.curAnim.name') == 'singLEFT' then
                triggerEvent('Camera Follow Pos',xx2-ofs,yy2)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT' then
                triggerEvent('Camera Follow Pos',xx2+ofs,yy2)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singUP' then
                triggerEvent('Camera Follow Pos',xx2,yy2-ofs)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN' then
                triggerEvent('Camera Follow Pos',xx2,yy2+ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'idle-alt' then
                triggerEvent('Camera Follow Pos',xx2,yy2)
            end
            if getProperty('dad.animation.curAnim.name') == 'idle' then
                triggerEvent('Camera Follow Pos',xx2,yy2)
            end
        end
    else
        triggerEvent('Camera Follow Pos','','')
    end

**Comment by Missa13** [comment]
And what do I do with this to make it work?

**Comment by MayoALT** [comment]
put it in the song data folder **_AS A .LUA FILE_**

**Comment by Missa13** [comment]
Bro It doesn't work. There are other scripts. Oh, something I can make it work. Please?

**Comment by Missa13** [comment]
Bro It doesn't work. There are other scripts. Oh, something I can make it work. Please?

**Comment by DEV-idiotXD** [comment]
> Bro It doesn't work. There are other scripts. Oh, something I can make it work. Please?

rename it to Script.lua (remove the .txt extension) then drag it into the song json folder
