### ISSUE TITLE
HUD Changing

### ISSUE THREAD

**Issue by LucasOnGithub** [ShadowMario/FNF-PsychEngine#11460]
### Describe your problem here.

Is there a way to hide everything about the HUD except the Lua Hud stuff that the player adds?
Like for example, No notes, No Health bar or score, just event Lua sprites, and script Hud stuff.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by bruh1cat** [comment]
yes, just do them individually.

**Comment by LucasOnGithub** [comment]
> yes, just do them individually.

could you send some example code?

**Comment by bruh1cat** [comment]
> > yes, just do them individually.
> 
> could you send some example code?

 setProperty('healthBar.alpha', false)
    setProperty('healthBarOverlay.alpha', false)
    setProperty('iconP1.alpha', false)
    setProperty('iconP2.alpha', false)
    setProperty'defaultPlayerStrum0.alpha', 0);

**Comment by CaptainBaldi** [comment]
> > > yes, just do them individually.
> > 
> > 
> > could you send some example code?
> 
> setProperty('healthBar.alpha', tonumber(0)) setProperty('healthBarOverlay.alpha', tonumber(0)) setProperty('iconP1.alpha', tonumber(0)) setProperty('iconP2.alpha', tonumber(0)) setProperty'defaultPlayerStrum0.alpha', 0);

ew imagine not using tables

**Comment by LucasOnGithub** [comment]
> setProperty('healthBar.alpha', tonumber(0))
> setProperty('healthBarOverlay.alpha', tonumber(0))
> setProperty('iconP1.alpha', tonumber(0))
> setProperty('iconP2.alpha', tonumber(0))
> setProperty'defaultPlayerStrum0.alpha', 0);

**setProperty'defaultPlayerStrum0.alpha', 0);** doesnt work. it keeps giving me an error about **unexpected symbol near ','**

**Comment by LucasOnGithub** [comment]
> setProperty'defaultPlayerStrum0.alpha', 0);

`setProperty'defaultPlayerStrum0.alpha', 0);` doesnt work at all. the code is broken, and even when i try to fix it, it doesnt work either way.

**Comment by DacroyleYT** [comment]
if the lua's ui is on camera "other", you could just do:
`doTweenAlpha('hudgone', 'camHUD', 1, 0.5, linear)`

if you want to set it directly, maybe change "0.5" to "0". If that doesn't work try a really small number
