### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by notzthatone** [ShadowMario/FNF-PsychEngine#11468]
### Describe your problem here.

flixel/system/FlxSound.hx (line 589)
flixel/system/FlxSound.hx (line 727)
flixel/system/FlxSoundGroup.hx (line 52)
flixel/system/frontEnds/SoundFrontEnd.hx (line 314)
flixel/system/frontEnds/SoundFrontEnd.hx (line 306)
flixel/FlxGame.hx (line 613)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by notzthatone** [comment]
> You broke your video render.

what do you mean

**Comment by KiyoshiTakigawa** [comment]
Something its missing, example: you make an custom character, but they don't have an down loop (If its an opponent)

**Comment by notzthatone** [comment]
> Something its missing, example: you make an custom character, but they don't have an down loop (If its an opponent)
like what

**Comment by Dollemo** [comment]
> Something its missing, example: you make an custom character, but they don't have an down loop (If its an opponent)

Well yea, but how would you go about fixing that? I'm having a similar problem, when I switch the opponent to my custom character in the conductor (the little menu after you press 7 during a song), all it says is "Null Object Reference", and I can't figure out what's missing. I followed bbpanzu's YouTube tutorial since I don't know much about code...
