### ISSUE TITLE
1 stage hold notes not appearing after chart being saved

### ISSUE THREAD

**Issue by FishyMudkips** [ShadowMario/FNF-PsychEngine#11462]
### Describe your bug here.

 When charting a song I realized something weird for some reason hold notes of 1 stage do not appear when the chart is saved and reloaded. Example clip attached 

https://user-images.githubusercontent.com/120286842/206881198-3b56f445-cb4c-470e-9c8a-d93024f29692.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

uh no Im just charting.

**Comment by CaptainBaldi** [comment]
I've had this issue too
its really annoying
