### ISSUE TITLE
Add score if botplay is on

### ISSUE THREAD

**Issue by SteveeTheCreeper** [ShadowMario/FNF-PsychEngine#11465]
### What is your question?

Heya 
I want to make a lua script that adds score even if botplay is on
Like if a note is hit and it's sick, good, etc.. then addscore(value) but Idk how to make it
And I need it for my corruption gameplay vids cuz I want it to look like the original video and I suck at upscroll and not to fake gameplays

**Comment by TheKitBoi** [comment]
Don’t making duplicate
https://github.com/ShadowMario/FNF-PsychEngine/issues/11451

**Comment by SteveeTheCreeper** [comment]
> Don’t making duplicate #11451

Okay I won't
It's just that nobody answers me

**Comment by Jevilm** [comment]
fine ill answer it smh

function goodNoteHit()
     if botPlay then
           addScore(350)
     end
end

**Comment by SteveeTheCreeper** [comment]
> fine ill answer it smh
> 
> function goodNoteHit() if botPlay then addScore(350) end end

Thank you it works
But there is a small problem
When a hold note/arrow comes in, it just adds extra score

**Comment by fnfporterhi** [comment]
Are you talking about when it has a hold note, it keeps adding score with the hold note?

**Comment by SteveeTheCreeper** [comment]
> Are you talking about when it has a hold note, it keeps adding score with the hold note?

Yeah that right
It keeps adding more than 350 with one hold note

**Comment by CaptainBaldi** [comment]
if you would look at one of the wikis for 2 damn seconds you would know how to do this shit but istg you lazy asses want everything done for you

function goodNoteHit(index, nData, nType, sustain)
    if botPlay and not sustain then
        addScore(350)
    end
end

**Comment by SteveeTheCreeper** [comment]
> if you would look at one of the wikis for 2 damn seconds you would know how to do this shit but istg you lazy asses want everything done for you
> 
> function goodNoteHit(index, nData, nType, sustain) if botPlay and not sustain then addScore(350) end end

Thank you so much it works
Also btw, I'm a guy that only optimizes pngs and stuff
I'm not a coder and stuff so it's a lil hard for me to write codes
Anyways thank you

**Comment by rolexwatch123** [comment]
> fine ill answer it smh
> 
> function goodNoteHit() if botPlay then addScore(350) end end

the score goes up but switches back to the question mark

**Comment by SomeGDPerson123** [comment]
> if you would look at one of the wikis for 2 damn seconds you would know how to do this shit but istg you lazy asses want everything done for you
> 
> function goodNoteHit(index, nData, nType, sustain) if botPlay and not sustain then addScore(350) end end

Is there a script that can make it so that when using this, the score doesn't save? My butt doesn't know how to code, and I'm lazy.
