### ISSUE TITLE
Moving camera offset for a stage

### ISSUE THREAD

**Issue by redstonemaster60** [ShadowMario/FNF-PsychEngine#11461]
### Describe your problem here.

I mean like moving the camera up a certain amount but only on a certain stage (not just on any of the individual characters or moving the stage/characters up/down, only the camera).

I'm not sure if you'd do this with lua or in the stage's json but either way works.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Drawoon2** [comment]
that is for Json
for boyfriend is
`"camera_boyfriend": [x,y]`
for girlfriend is 
`"camera_girlfriend":[x,y]`
and for opponent is
`"camera_opponent":[x,y]`

**Comment by redstonemaster60** [comment]
this worked, thanks!
