### ISSUE TITLE
Lua - onAnimationFinished(name, tag)

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#11474]
### What feature do you want to get added on the **base** engine?

It would be pretty cool, if there would be a function, that checks, if an animation has ended, and it would revert back to going idle.
Like if there is a special cutscene midsong, and the chacarcter would then either fade away or change.
and to prevent those visual effects from happening. you could use for example
```
function onAnimationFinished(name, tag)
   if name = 'CustomAnim' then
   setProperty('dad.alpha',0)
end
```
the animation name could either be defined in the character json, if it is a character, or if it is a lua sprite, used via script or even in a stage, it could be checked with those define by `addAnimationbyIndices()` or `addAnimationByPrefix()`

also, seeing the issue from #11437 

it could then work similar or as a more comfort way of using
```
if getProperty('dad.animation.curAnim.name') == 'singLEFT' then
   if getProperty('dad.animation.curAnim.finished') then
      debugPrint("LEL")
   end
end
```
just with a check of, what the current anim is and then if it is finished or not (also because that construction somehow does not work?)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CaptainBaldi** [comment]
tbh i really dont think this is needed

**Comment by ZeitHeld** [comment]
then at least, how would I check, if a specific animation is finished?

**Comment by impostor5875** [comment]
if getProperty(dad.animation.finished) and getProperty(dad.animation.curAnim.name) == 'animName' then
