### ISSUE TITLE
How do i fix this hashtag issue

### ISSUE THREAD

**Issue by OmartheMetaRunner** [ShadowMario/FNF-PsychEngine#11476]
### Describe your problem here.

I fixed my whole mod but now it sorta does this shit
![hashtag bug](https://user-images.githubusercontent.com/119460424/206953158-5a4a515c-503b-4be5-9664-4cde17dd461b.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

only did things that mods typically use

**Comment by bruh1cat** [comment]
use the new alphabet provided with newer version of psych.

**Comment by OmartheMetaRunner** [comment]
> use the new alphabet provided with newer version of psych.

there's a new one?

**Comment by OmartheMetaRunner** [comment]
> use the new alphabet provided with newer version of psych.

nvm it did not work

**Comment by bruh1cat** [comment]
What version are you using? Have you edited alphabet.hx?

**Comment by OmartheMetaRunner** [comment]
> What version are you using? Have you edited alphabet.hx?

i have not edited it and im on 0.6.1 it says or some shit

**Comment by Minalog** [comment]
he's playing fnf in roblox lol
