### ISSUE TITLE
''+'' Button doesnt work bruh

### ISSUE THREAD

**Issue by JustMrAle** [ShadowMario/FNF-PsychEngine#11477]
### What is your question?

So uh,my ''+'' button on psych engine doesnt work,so i can't hear NOTHING,so uhm,does someone know how to actually fix this? (btw i'm using 6.3,and i didnt modify any archive)

Oh and btw i'm spanish sorry if you can't understand nothing lol

**Comment by DabbinDude316B** [comment]
Um check ur pc volume 🤓

**Comment by JustMrAle** [comment]
> Um check ur pc volume 🤓

dude i mean the volume inside the game like,you can change the volume of the game inside of it,but doesnt affect the PC.

**Comment by frantastic24** [comment]
Controls menu

**Comment by DabbinDude316B** [comment]
> > Um check ur pc volume 🤓
> 
> dude i mean the volume inside the game like,you can change the volume of the game inside of it,but doesnt affect the PC.

Um Check if you pressed 0 🤓

**Comment by Draconic-Hybrid** [comment]
> > > Um check ur pc volume 🤓
> > 
> > 
> > dude i mean the volume inside the game like,you can change the volume of the game inside of it,but doesnt affect the PC.
> 
> Um Check if you pressed 0 🤓

Um achksually if you press + after pressing 0 it will unmute

In all seriousness, though, it probably is your PC volume. That or your speakers are damaged.
