### ISSUE TITLE
!!HELP!!!

### ISSUE THREAD

**Issue by TDTxhas** [ShadowMario/FNF-PsychEngine#11478]
### Describe your bug here.

source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CaptainBaldi** [comment]
duplicate of several other issues

**Comment by Mokona5901** [comment]
just lower you flixel version to 4.11.0 but yes duplicate

**Comment by frantastic24** [comment]
Update your source

**Comment by KiyoshiTakigawa** [comment]
This error hapen to me too...
