### ISSUE TITLE
Event with more than 2 values

### ISSUE THREAD

**Issue by Only-a-cat** [ShadowMario/FNF-PsychEngine#11475]
### Describe your problem here.

How to create an event with three/four values? (like in the screen shake event, the second value is divided by ",")

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MaybeMaru** [comment]
find a split string lua function online

**Comment by Drawoon2** [comment]
`stringSplit(string,',')`
Use this line, give you a array
