### ISSUE TITLE
Crash When Adding Portraits

### ISSUE THREAD

**Issue by earthboundfan64** [ShadowMario/FNF-PsychEngine#1147]
### Describe your problem here.

Everytime I try to load a portrait through the portrait editor, it crashes. I don't know what I am doing wrong since I have the PNG and XML.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by DEV-idiotXD** [comment]
you have to put the assets in the mods folder not the assets folder

**Comment by ShadowMario** [comment]
> you have to put the assets in the mods folder not the assets folder

^
If you're still crashing after it, your XML file is broken.
