### ISSUE TITLE
is possible to check if a Lua Sprite exist?

### ISSUE THREAD

**Issue by Noel3454565FNF** [ShadowMario/FNF-PsychEngine#11486]
### Describe your problem here.

heya :D, im actually doing a script for a mods and i need to know if is it possible to check if a certain lua Sprite exist and how to use it, i already sheerch in the doc and i can't find anything.

thanks for your futur help :D

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nop, im just doing LUA script and other things

**Comment by CaptainBaldi** [comment]
if luaSpriteExists('sprite') then
        -- do shit
end

**Comment by Noel3454565FNF** [comment]
i already try that and its not working

**Comment by CaptainBaldi** [comment]
> i already try that and its not working

well then it's clearly something you're doing wrong, maybe outdated psych version or invalid sprite?

**Comment by Noel3454565FNF** [comment]
I use the last versionbof psych engine,
I can test Again with another sprite

**Comment by Isaagomen** [comment]
> if luaSpriteExists('sprite') then -- do shit end

does this command even exists

**Comment by Noel3454565FNF** [comment]
I don’t know…
Its why i asking

**Comment by CaptainBaldi** [comment]
> > if luaSpriteExists('sprite') then -- do shit end
> 
> does this command even exists

![image](https://user-images.githubusercontent.com/86160807/208132846-5e80b4c6-53d9-47c9-8a89-902f6dee5363.png)

**Comment by Noel3454565FNF** [comment]
i don't know, its why i asking dude

**Comment by Noel3454565FNF** [comment]
> > > if luaSpriteExists('sprite') then -- do shit end
> > 
> > 
> > Cette commande existe-t-elle même ?
> 
> ![image](https://user-images.githubusercontent.com/86160807/208132846-5e80b4c6-53d9-47c9-8a89-902f6dee5363.png)

okay but how i can call it? i already try and its not working
