### ISSUE TITLE
HealthBar Problem

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#11480]
### Describe your problem here.

I tried to put a custom healthbar style for my mod but when i put the healthbar the bar of the colors gets bigger and is above of the healthbar style. Can anyone help me here pls.
Here is the image:
![healthBar](https://user-images.githubusercontent.com/116233921/207206343-3cb21807-99b0-48a1-9480-a92f62e21ea5.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not at all

**Comment by DabbinDude316B** [comment]
It takes the png size and fits it like that, try just the healthBar and not the extra fx
