### ISSUE TITLE
can someone make a bouncy arrow script?

### ISSUE THREAD

**Issue by darkresident55** [ShadowMario/FNF-PsychEngine#11488]
### What is your question?

im wanting to know if somebody here can give me a script that will make the arrows bounce to the beat of a spicific song

**Comment by Minalog** [comment]
Hopefully this satisfies your needs.
```lua
function onBeatHit()
  for i=0, 8 do
  noteTweenX("boom"..i, i, defaultPlayerStrumY0, crochet-0.05, "circOut")
  end
end
```
