### ISSUE TITLE
Need Project.xml

### ISSUE THREAD

**Issue by Nork1234** [ShadowMario/FNF-PsychEngine#11483]
### Describe your bug here.

When I'm trying to compile, it says "Error: You must have a "project.xml" file or specify another valid project file when using the 'test' command" But the project.xml file is right there.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Lorekeeper49** [comment]
Make sure you're compiling via the entire engine folder and not just the source folder

**Comment by Nork1234** [comment]
thanks

**Comment by CaptainBaldi** [comment]
close the issue

**Comment by DisLolTV** [comment]
If it's still not working check if your system deleted "by accident" your Project.xml file (Windows 11 is pro at that kind of bullshit). Check zipped source you used and copy Project.xml file to unzipped source.
