### ISSUE TITLE
I can't put my custom character in psych engine! 

### ISSUE THREAD

**Issue by KiyoshiTakigawa** [ShadowMario/FNF-PsychEngine#11492]
My Psych Engine (Version 0.6.3 "the latest") crash after i try to reload the image (To create my custom opponent), my image its an normal png (The spritesheet) and the XML file, but DON'T WORK! Help please...

[PsychEngine_2022-12-14_08'42'07.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/10228003/PsychEngine_2022-12-14_08.42.07.txt)
![People](https://user-images.githubusercontent.com/120257429/207605940-6ec0474a-cb0b-4332-99cf-eb836e885c53.png)
![image](https://user-images.githubusercontent.com/120257429/207606733-947472db-ddc0-4040-929d-19c540ea883e.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, default build.

**Comment by Ratio-Combinder** [comment]
send the xml + yo image have a watermark
