### ISSUE TITLE
Same thing as #11360

### ISSUE THREAD

**Issue by Ninjakaiden523** [ShadowMario/FNF-PsychEngine#11491]
### Describe your bug here.

Same thing as #11360 but with images, I was hoping more people would see this one as well.
![image](https://user-images.githubusercontent.com/77185327/207543241-97ff6cc8-7979-4d1e-87b0-0d74ce9e5856.png)

![image](https://user-images.githubusercontent.com/77185327/207543355-deba11f1-0fd9-4fd8-9b36-99b7a1ff5931.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not in the source files, only lua. Added a few characters and a few songs (all charted and using base game assets as place holders)

**Comment by Ratio-Combinder** [comment]
you could have post that into the main and not make duplicates

**Comment by frantastic24** [comment]
You never provided any files
I already said your animation names may be wrong since according to you none of them actually play
And this should've gone under the issue you already had open, it's a duplicate

**Comment by Ninjakaiden523** [comment]
The animation names are correct, as they play fine in the character editor. As for the other thing, I don't know if replying to something on a different page would make it go to the front page in order to be noticed, plus there isn't a working fix on any of the issues referenced in this issue and the other one, Plus I posted the other issue as well. I just want this issue fixed

**Comment by frantastic24** [comment]
If the animations don't play in a song, it means they aren't named correctly 
Provide files or show what you named your animations (XML and in-game)

**Comment by Ninjakaiden523** [comment]
https://www.mediafire.com/folder/o5m525fn7xn8d/Roger_files I'm pretty sure they're all the same names, also I realized that I had two idle animations because I accidentally named right's animation the idle animation

**Comment by frantastic24** [comment]
I was right, all the animation names are wrong
The animation names in-game should be called singLEFT/singRIGHT/etc, not just Left/Right/Up
There's also an uppercase in Idle, it should be all lowercase

**Comment by Ninjakaiden523** [comment]
Geez I did not realize that it was that specific, yeah renaming the animation name to that worked, do not know how I didn't pick that up from cross referencing other lua mods

**Comment by frantastic24** [comment]
Close the other issue
