### ISSUE TITLE
Character Does Not Load

### ISSUE THREAD

**Issue by OriALT** [ShadowMario/FNF-PsychEngine#11496]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/120613293/207752921-8e6ed913-6072-4167-b3e9-f1a449a646f7.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

New Character, Broken

**Comment by vesel4ak** [comment]
check if character's name and sprites' image mathces or check if u entered character's name correct in debug menu

**Comment by OriALT** [comment]
> check if character's name and sprites' image matches or check if u entered character's name correct in debug menu

i did, its not working

**Comment by TheKitBoi** [comment]
What type of image are you using
