### ISSUE TITLE
Editors Master Menu not opening.

### ISSUE THREAD

**Issue by Simmo0n** [ShadowMario/FNF-PsychEngine#115]
As the title says, I have tried multiple times to open it pressing 7 but nothing is working.

**Comment by ShadowMario** [comment]
Are you on HTML5? I've disabled it on HTML5 for now

**Comment by FuseIsHere813** [comment]
> As the title says, I have tried multiple times to open it pressing 7 but nothing is working.

As said, Shadow Mario stated that pressing 7 in HTML5 is disabled temporarily.

**Comment by Simmo0n** [comment]
No, I'm using the source code exe.

**Comment by FuseIsHere813** [comment]
check PlayState.hx to see if it's enabled then.

**Comment by ShadowMario** [comment]
https://user-images.githubusercontent.com/44785097/134778311-064c3644-60a1-4d02-baa3-8ad77814b91f.mp4

**Comment by harisshaukat96** [comment]
wait why is pressing 7 on the main menu disabled on html5?
