### ISSUE TITLE
...

### ISSUE THREAD

**Issue by OriALT** [ShadowMario/FNF-PsychEngine#11504]
### What feature do you want to get added on the **base** engine?

Auto Save. Its Nice To Have One Because It Didnt Save When It Crashed.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by Lorekeeper49** [comment]
Test = failed

**Comment by OriALT** [comment]
wdym by that lorekeeper

**Comment by Lorekeeper49** [comment]
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> 
> Useful feature

It should say this:
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> 
> Stage Editor, 6K+ support, and winning icons

**Comment by TheKitBoi** [comment]
> ### What feature do you want to get added on the **base** engine?
> Auto Save. Its Nice To Have One Because It Didnt Save When It Crashed.

just save from each beat you charted

**Comment by MaybeMaru** [comment]
you failed the test and there is already autosaves of charts
