### ISSUE TITLE
IM STUCKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK

### ISSUE THREAD

**Issue by OriALT** [ShadowMario/FNF-PsychEngine#11503]
### Describe your bug here.

https://user-images.githubusercontent.com/120613293/208003686-c766238a-3a9a-4b9a-b279-2551f08a1c92.mp4

### Command Prompt/Terminal logs (if existing)

```bash
buajksehqnjceth9nrum
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

SONG NOEP

**Comment by frantastic24** [comment]
Not a bug
Duplicate of #11161

**Comment by OriALT** [comment]
yes it is

**Comment by frantastic24** [comment]
Read the issue I tagged and close this

**Comment by ShadowMilky** [comment]
Set the sample rate to 44.1khz or lower

**Comment by RubenDatOneBoi3446** [comment]
Rather convert your song file to an ogg, Rename the folder of the audio to your song name, or rename the files in the folder inst and voices

**Comment by OriALT** [comment]
Yet ShadowMilky Was Right. Thx For Fix.

**Comment by frantastic24** [comment]
Close the issue

**Comment by MaybeMaru** [comment]
Close this

**Comment by DisIsNOt** [comment]
holy shit
