### ISSUE TITLE
Menu songs based on date

### ISSUE THREAD

**Issue by DaInfLoop** [ShadowMario/FNF-PsychEngine#11508]
### What is your question?

I'd like to make an addition to my mod so when it's a certain time of the year, a different menu theme will play (e.g. Christmas theme, Halloween theme and a normal theme for every other time)

Is this possible without having to edit source code and having to build the game myself?

**Comment by frantastic24** [comment]
No

**Comment by TheKitBoi** [comment]
> ### What is your question?
> I'd like to make an addition to my mod so when it's a certain time of the year, a different menu theme will play (e.g. Christmas theme, Halloween theme and a normal theme for every other time)

it might but we ain’t helping you with ur 'oh this website will help me to get people to code complex things for me' bullshit

**Comment by lemz1** [comment]
> > > ### What is your question?
> 
> > > I'd like to make an addition to my mod so when it's a certain time of the year, a different menu theme will play (e.g. Christmas theme, Halloween theme and a normal theme for every other time)
> 
> > 
> 
> > it might but we ain’t helping you with ur 'oh this website will help me to get people to code complex things for me' bullshit
> 
> 
> 
> it isn't complex at all actually, stop bashing on him.
> 
> 
> 
> `if (date.getMonth() == 11 && date.getDate() == 1)`
> 
> `{`
> 
> `FlxG.sound.music.play(Paths.music("freakyHolidayMusic"));`
> 
> `}`
> 
> 
> 
> stop being a jerk to people which code isn't complicated.


he wanted it in lua your code is haxe

thats why kitboi said if it works on lua then it is probably  complicated

**Comment by ElPro7777** [comment]
> > > > ### What is your question?
> > 
> > 
> > > > I'd like to make an addition to my mod so when it's a certain time of the year, a different menu theme will play (e.g. Christmas theme, Halloween theme and a normal theme for every other time)
> > 
> > 
> > > 
> > 
> > 
> > > it might but we ain’t helping you with ur 'oh this website will help me to get people to code complex things for me' bullshit
> > 
> > 
> > it isn't complex at all actually, stop bashing on him.
> > `if (date.getMonth() == 11 && date.getDate() == 1)`
> > `{`
> > `FlxG.sound.music.play(Paths.music("freakyHolidayMusic"));`
> > `}`
> > stop being a jerk to people which code isn't complicated.
> 
> he wanted it in lua your code is haxe
> 
> thats why kitboi said if it works on lua then it is probably complicated

runHaxe() is a command in funkin lua that lets you run haxe code

**Comment by frantastic24** [comment]
FunkinLua doesn't run outside of PlayState
