### ISSUE TITLE
How do I make it so you can’t hit a type of note

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#11501]
### Describe your problem here.

So basically, I want to do something where you can only sometimes hit a note, and otherwise you can’t, as it won’t do anything when you try to hit it? Is there any way to do so? I don’t care how hacky it is, any way would be nice.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by wubbzyfan** [comment]
.

**Comment by Drawoon2** [comment]
`setPropertyFromGroup('unspawnNotes', i, 'blockHit',bool);`
You can try using this code for make it
