### ISSUE TITLE
shadertoy shaders don't work 

### ISSUE THREAD

**Issue by imdumlol** [ShadowMario/FNF-PsychEngine#11506]
### Describe your bug here.

it crash's when i try them

link:https://www.shadertoy.com/

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CaptainBaldi** [comment]
not a bug
you have to modify certain aspects of shaders in order for them to work

**Comment by imdumlol** [comment]
oh ok

**Comment by imdumlol** [comment]
what do i have to modify?

**Comment by TheKitBoi** [comment]
Copy this and place it in the top of the shader
```
//SHADERTOY PORT FIX
#pragma header
vec2 uv = openfl_TextureCoordv.xy;
vec2 fragCoord = openfl_TextureCoordv*openfl_TextureSize;
vec2 iResolution = openfl_TextureSize;
uniform float iTime;
#define iChannel0 bitmap
#define texture flixel_texture2D
#define fragColor gl_FragColor
#define mainImage main
//****MAKE SURE TO remove the parameters from mainImage.
//SHADERTOY PORT FIX
```

**Comment by imdumlol** [comment]
thx

**Comment by imdumlol** [comment]
it still crashs

**Comment by TheKitBoi** [comment]
Show the error details

**Comment by imdumlol** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/118001986/208143755-6c151e71-56df-42e0-bb4d-2f64baadef83.png)

**Comment by imdumlol** [comment]
right there

**Comment by imdumlol** [comment]
hello?

**Comment by Mokona5901** [comment]
Could I have the link to the shader ? (the one you gave is the site link)

**Comment by TheKitBoi** [comment]
> Could I have the link to the shader ? (the one you gave is the site link)

https://www.shadertoy.com/view/MltXzN

this one is a optimised version
https://www.shadertoy.com/view/7lcfDB

**Comment by MaybeMaru** [comment]
for this kind of help go to the psych discord server, there is a text channel for shaders help, also dont label it as bug if its a you thing lmao

**Comment by imdumlol** [comment]
k
