### ISSUE TITLE
Play as an opponent

### ISSUE THREAD

**Issue by nennneko5787** [ShadowMario/FNF-PsychEngine#11507]
### What is your question?

I am modifying PsychEngine with source code.
Where in PlayState.hx should I tweak to implement a mode where I play as an opponent?
(This may be a really dumb question)

**Comment by TheKitBoi** [comment]
https://github.com/l1ttleO/ProjectFNF/blob/main/source/PlayState.hx

**Comment by nennneko5787** [comment]
Where is it? Maybe it's not PlayState.hx...

**Comment by nennneko5787** [comment]
I found it! Currently undergoing modifications...

**Comment by nennneko5787** [comment]
Resolved! Thank you very much.
