### ISSUE TITLE
Crash for no reason (maybe there's a reason but I don't what is it)

### ISSUE THREAD

**Issue by add071** [ShadowMario/FNF-PsychEngine#11500]
### Describe your bug here.

I was playing the "technicolor-tussle" song from the Indie Cross mod, but for some reason the game crashed, so what I did after that was go to this website and report the crash.

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
FreeplayState.hx (line 371)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/technicolor-tussle/technicolor-tussle-hell.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

The only thing i did was to add mods.

**Comment by frantastic24** [comment]
Not a bug
Missing chart

**Comment by Gavman69** [comment]
missing the chart for the hell difficulty smh

**Comment by vesel4ak** [comment]
add your data folder of song

**Comment by DisLolTV** [comment]
Missing chart (probably you named the chart wrong)
