### ISSUE TITLE
b3 endless event

### ISSUE THREAD

**Issue by RubenDatOneBoi3446** [ShadowMario/FNF-PsychEngine#11505]
### What is your question?

Is there a script event that does that one b3 endless event where the characters are in front of everything, more closer to the screen like a standoff
![Screenshot 2022-12-15 9 16 11 PM](https://user-images.githubusercontent.com/108199247/208027712-cff47f71-7cc0-4b7d-926e-8a5faeadc13c.png)

**Comment by RubenDatOneBoi3446** [comment]
Someone?

**Comment by VoidedBattery** [comment]
you can probably make the illusion of that by resizing them and setting their scroll factor on something higher than one

**Comment by RubenDatOneBoi3446** [comment]
alr thx
