### ISSUE TITLE
Uncaught Error: Null Object Reference

### ISSUE THREAD

**Issue by Snappor** [ShadowMario/FNF-PsychEngine#11513]
### Describe your bug here.

When loading a song In Psych engine (soft mod) After 2 seconds the game crashes due an Uncaught Error: Null Object Reference
This would help alot if yall can fix this

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 4633)
PlayState.hx (line 3240)
flixel/group/FlxGroup.hx (line 769)
PlayState.hx (line 3179)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by Grape-Boy** [comment]
[[the line]](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/PlayState.hx#L4633)
there's a chance the xml is fucked up

**Comment by Snappor** [comment]
> [[the line]](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/PlayState.hx#L4633)
> there's a chance the note assets xml is fucked up

Well that sucks. But can you explain what this is for error?

**Comment by Grape-Boy** [comment]
> > [[the line]](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/PlayState.hx#L4633)
> > there's a chance the note assets xml is fucked up
> 
> Well that sucks. But can you explain what this is for error?

Basically it tries to get a note's current animation's name but the (current) animation object doesn't exist so it errors because it's null

**Comment by Snappor** [comment]
> > > [[the line]](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/PlayState.hx#L4633)
> > > there's a chance the note assets xml is fucked up
> > 
> > Well that sucks. But can you explain what this is for error?
> 
> Basically it tries to get a note's current animation's name but the (current) animation object doesn't exist so it errors because it's null

Ohh okay. Thanks!

**Comment by NathanXDmoder** [comment]
Quando eu tento adicionar o evento "play animation" ou o evento "philly glow" aparece erro de objecto nulo.
Como posso consertar isso?

**Comment by NathanXDmoder** [comment]
Aqui está o erro do philly glow

**Comment by NathanXDmoder** [comment]
editors/ChartingState.hx (line 1474)
flixel/addons/ui/FlxUI.hx (line 164)
flixel/addons/ui/FlxUIInputText.hx (line 46)
flixel/addons/ui/FlxInputText.hx (line 466)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/jigsaw-4277821/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

**Comment by Snappor** [comment]
Devido ao fato de que pode ser um script fodido. Provavelmente um arquivo corrompido. Talvez por causa da atualização para 0.6.2 para 0.6.3, pode estragar o script (eu sou inglês, então isso está traduzido).

**Comment by BoiNoName** [comment]
Hey im just writing here because i have the same issue 
i was working on a chart then i just took a break for a while
i came back and now no matter what i do i cant open the chart because i get this:
![image](https://user-images.githubusercontent.com/65833167/212573891-23a8afc3-7c1b-4b59-b21b-a233097d93ad.png)

it worked and played perfectly before i left and nothings been done to it
ive tried removing the events, swapping the chart for a older version i have of it, nothings worked
i tried seeing if it was the characters that were the problem but they were fine, same goes for the inst and vocals, so its a problem within in the chart itself
can i have some help please, i honestly dont know how to fix this

**Comment by Grape-Boy** [comment]
it looks like your chart doesn't have a part that contains notes, but I may be wrong. can you send your json?

**Comment by TheKitBoi** [comment]
and rename it to txt for attaching file

**Comment by SoftieIsVibing** [comment]
> it looks like your chart doesn't have a part that contains notes, but I may be wrong. can you send your json?
Sure, https://drive.google.com/drive/folders/1pIRH-7ni3hEJW_VatqZUbG3wMceJINCE?usp=sharing
i put the folder since its got scripts and such

**Comment by Grape-Boy** [comment]
how exactly are you trying to access the chart? when I look at the source code, it makes me think that the game can't find your chart (so it's null)

**Comment by SoftieIsVibing** [comment]
Well i'd add it to a week and then open it that way. It worked like that before but now it doesn't for some reason, I haven't moved the charts location or anything

**Comment by Puzzl3Mak3r** [comment]
I got this message and still don't know what it means
[I'm modding without using haxe, just the files and debug menu]
![Screenshot 2023-03-03 072152](https://user-images.githubusercontent.com/126822705/222543605-59a6d096-dd3d-449d-a502-4c2609121cb5.png)

**Comment by Rome0621** [comment]
I keep getting this error when trying to use the "Change Scroll Speed" event. im trying to make my own chart of too slow encore using the rechart/psych engine port
![Friday Night Funkin'_ Psych Engine 3_3_2023 7_27_42 PM](https://user-images.githubusercontent.com/126928660/222868243-812357e4-cd74-4d6a-b83d-f956d22d2b79.png)

**Comment by Grape-Boy** [comment]
> I keep getting this error when trying to use the "Change Scroll Speed" event. im trying to make my own chart of too slow encore using the rechart/psych engine port
> ![Friday Night Funkin'_ Psych Engine 3_3_2023 7_27_42 PM](https://user-images.githubusercontent.com/126928660/222868243-812357e4-cd74-4d6a-b83d-f956d22d2b79.png)
> 

don't know how to fix it, but you should try using lua instead
setProperty('songSpeed', 3)

**Comment by Puzzl3Mak3r** [comment]
I just used a different song chart and recharted it and it's working now (without changing the lua file)
