### ISSUE TITLE
Make Screen Shake actually move the camera's pos and not have the black from moving the game camera itself show

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#11515]
### What feature do you want to get added on the **base** engine?

Seriously, why does Screen Shake just move the camera instead of moving the camera's pos? It'd still shake, and you wouldn't have black show on the sides of the screen!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MaybeMaru** [comment]
you can do this with lua, so nah

**Comment by EgguMan** [comment]
This is an issue with how cameras work in HaxeFlixel, it would be easy to just make the camera larger in it of itself, plus I imagine this would break events like camFollowPos and the lerp from character to character

**Comment by ShadowMario** [comment]
Flixel issue
