### ISSUE TITLE
I can't chart my song! But it goes deeper...

### ISSUE THREAD

**Issue by SophiaFC01** [ShadowMario/FNF-PsychEngine#11510]
### Describe your bug here.

I can't chart my songs, I go in the chart editor, and I change the song name, but it detects no audio, my songs are in the songs folder (no my mod folder) in the .ogg format, I copied bopeebo and put it in my data, changed the song name and everything! But nothing! My game crashes, and the song played the first note, then nothing, I tried something else, by changing the song name in the script, but, then, my game started crashing every time I loaded the song! It won't play anything, and it won't show the instrumental blue thingy!
I tried everything I could find, but, nothing! (I'm on Mac, if this is relevant)

### Command Prompt/Terminal logs (if existing)

```bash
/Users/runner/hostedtoolcache/haxe/4.2.5/x64/std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
editors/ChartingState.hx (line 2911)
editors/ChartingState.hx (line 428)
Prompt.hx (line 44)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I tried adding a new song, and tried to chart it, I also created a new week, and new characters, menu characters, background menus, new icons

**Comment by AnonymousPerson10112** [comment]
Check for any spelling errors or missing elements. If this does not resolve the issue, try recompiling the build.

**Comment by SophiaFC01** [comment]
Ok, thanks, I'll try!

**Comment by LodedRick** [comment]
you can try converting the ogg file with a converter to mp3 and then back to ogg

for some reason the ogg file just doesnt work and that fixes it
worked for me atleast
