### ISSUE TITLE
Error when running "lime test windows" to build the game.

### ISSUE THREAD

**Issue by Icehero22YTreal** [ShadowMario/FNF-PsychEngine#11519]
### Describe your problem here.

so whenever I run "lime test windows" it shows the following

source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'

Extra Information:
1. To build the game I used LongestSoloEver's tutorial(https://www.youtube.com/watch?v=4IuC8ti6_4o&t=221s)
2.  I use windows 11, specifically Version 10.0.22621 Build 22621
3.  Flixel version is 5.0.2 and Haxe version is 4.2.5
4.  Psych Engine version is 0.6.3

If you need more information to solve this issue of mine, you may request and I will deliver.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, not a single thing in this build has been edited.

**Comment by Icehero22YTreal** [comment]
Nvm, I fixed it.

The fix for me was re downloading the source code from here:
![image](https://user-images.githubusercontent.com/120553391/208287454-c734c01c-ace1-4f66-9833-c5a0d784e4ca.png)

**Comment by FutureXDD** [comment]
dude i try that and keeping me saying that
