### ISSUE TITLE
How do i Make Screen Shake actually move the camera's pos and not have the black from moving the game camera itself show

### ISSUE THREAD

**Issue by ElPro7777** [ShadowMario/FNF-PsychEngine#11526]
### What is your question?

How do i Make Screen Shake actually move the camera's pos and not have the black from moving the game camera itself show in lua

**Comment by Jevilm** [comment]
You cant edit built in events with lua, sorry

**Comment by ElPro7777** [comment]
> You cant edit built in events with lua, sorry

I mean How to make a custom event that is the Screen Shake but actually move the camera's pos and not have the black from moving the game camera itself show

**Comment by TheKitBoi** [comment]
[widescreenSupport.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/10262588/widescreenSupport.txt)

this script removes boarders (credit Raltyro) rename txt to lua
