### ISSUE TITLE
failed to compile shaders

### ISSUE THREAD

**Issue by Jarachyreal1400** [ShadowMario/FNF-PsychEngine#11529]
### Describe your bug here.

i play a lot of fnf mods with wavy BGs and other stuff and everytime i load a song this error pops up (and its large) saying that failed compile shaders and this happened when my computer has gotten an update and this computer is a windows 11 (idk if that helps) and it is made for games so i dont know  what is the problem

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i dont really know and if there even lua script i dont think it works still

**Comment by TheKitBoi** [comment]
Show the error

**Comment by Jarachyreal1400** [comment]
> Show the error

@TheKitBoi 

![image](https://user-images.githubusercontent.com/120975290/208315785-d046128b-cbfb-44d9-90c3-c716796239ba.png)
heres most of it i cant see the bottom strangely

**Comment by Drawoon2** [comment]
That is problem from the shader

**Comment by Grape-Boy** [comment]
> heres most of it i cant see the bottom strangely

shader error messages are always long like that, idk why
anyway, can you send the shader that's causing problems?
