### ISSUE TITLE
Uncaught Error: Null Object Reference

### ISSUE THREAD

**Issue by InfernoBrighton** [ShadowMario/FNF-PsychEngine#11520]
Whenever I want to go and edit my charts for the songs I have added, this error pops up and closes Psych Engine I have tried to do everything but I can't get it to work

<img width="443" alt="Screenshot 2022-12-18 112358" src="https://user-images.githubusercontent.com/96926140/208295914-2ce899d0-43b0-44f2-806b-34c4c5c397ce.png">

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Grape-Boy** [comment]
Go to another song that doesn't crash and turn off waveform
Something's probably wrong with your audio file(s)

**Comment by InfernoBrighton** [comment]
ok

**Comment by InfernoBrighton** [comment]
> Go to another song that doesn't crash and turn off waveform Something's probably wrong with your audio file(s)

what could be wrong with my audio files and the waveform

**Comment by Grape-Boy** [comment]
> > Go to another song that doesn't crash and turn off waveform Something's probably wrong with your audio file(s)
> 
> what could be wrong with my audio files and the waveform

I don't know for sure but maybe the sampling frequency is too high or low OR maybe the game can't find your audio file(s)

**Comment by InfernoBrighton** [comment]
> > > Go to another song that doesn't crash and turn off waveform Something's probably wrong with your audio file(s)
> > 
> > 
> > what could be wrong with my audio files and the waveform
> 
> I don't know for sure but maybe the sampling frequency is too high or low OR maybe the game can't find/read your audio file(s)

my audio and my chart works but when I just want to go and press 7 to go to charting mode the error pops up and it is really sad because I don't want to start my chart all over again.

**Comment by InfernoBrighton** [comment]
> Go to another song that doesn't crash and turn off waveform Something's probably wrong with your audio file(s)

Ok thanks for the help it works now tysm once again
