### ISSUE TITLE
Characters show up as filled squares 

### ISSUE THREAD

**Issue by InfernoBrighton** [ShadowMario/FNF-PsychEngine#11525]
### Characters Come Up As Black Squares

The images/sprites for the characters are not corrupted or anything but just literal squares then i go to the character editor to check it out ones working. This happens when I try to play Tutorial, whenever the sprites are normal and not black squares and I try to play Tutorial, it kicks me out and then the next time I play it, it works but GF and my custom characters are all corrupted squares.
<img width="886" alt="Screenshot 2022-12-18 164024" src="https://user-images.githubusercontent.com/96926140/208309430-86cb2fd4-7d34-429e-be3f-27a303364815.png">

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by frantastic24** [comment]
Not a bug
Your PC isn't powerful enough for bigger spritesheets

**Comment by InfernoBrighton** [comment]
> Not a bug Your PC isn't powerful enough for bigger spritesheets

It still shows up from time to time

**Comment by frantastic24** [comment]
It's not a problem with the game

**Comment by InfernoBrighton** [comment]
> It's not a problem with the game

welp that sucks

**Comment by InfernoBrighton** [comment]
The sprites show up on PsychEngine but not my mod, that's weird
