### ISSUE TITLE
i am trying to compile html5 on psych engine 0.5.2h but it leads me to this error

### ISSUE THREAD

**Issue by CleanerCosine14** [ShadowMario/FNF-PsychEngine#11523]
### Describe your problem here.

lime test html5
source/WeekData.hx:11: characters 8-19 : You cannot access the sys package while targeting js (for sys.io.File)
source/editors/WeekEditorState.hx:34: characters 8-16 : ... referenced here
source/editors/MasterEditorMenu.hx:119: characters 37-52 : ... referenced here

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5/Browser

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by DisIsNOt** [comment]
idk may be run this command on da terminal 
`
haxelib set openfl 3.0.0-beta.3`

**Comment by ACrazyTown** [comment]
> idk may be run this command on da terminal ` haxelib set openfl 3.0.0-beta.3`

That installs a OpenFL version from 7 years ago 💀 

You cant compile for HTML5 because Psych Engine uses some features only available on native targets. You're gonna have to remove all instances of `sys.io.File`
