### ISSUE TITLE
Disc like rotating freeplay

### ISSUE THREAD

**Issue by Jevilm** [ShadowMario/FNF-PsychEngine#11530]
### What is your question?

How do i make the freeplay look like this, 
![goas](https://user-images.githubusercontent.com/110422450/208315880-51735c54-c9eb-4add-be80-e0e84b9b71c7.PNG)
in source code, like dave and bambi 2.5?

**Comment by TheKitBoi** [comment]
https://github.com/FuseIsHere813/VsDave/blob/main/source/FreeplayState.hx

**Comment by Jevilm** [comment]
> https://github.com/FuseIsHere813/VsDave/blob/main/source/FreeplayState.hx

i tried doing that earlier today and it gave me an error for too many arguments

**Comment by Jevilm** [comment]
> > https://github.com/FuseIsHere813/VsDave/blob/main/source/FreeplayState.hx
> 
> i tried doing that earlier today and it gave me an error for too many arguments

![sadfghj](https://user-images.githubusercontent.com/110422450/208316793-2578d5ca-bc05-4d67-b78f-ea663f0eddb9.PNG)
