### ISSUE TITLE
Calling a Nil Value

### ISSUE THREAD

**Issue by Thimque** [ShadowMario/FNF-PsychEngine#11536]
### Describe your problem here.

Trying to get shaders to work *lmao*, and for some reason, it just keeps giving me "attempt to call global 'initLuaShader' (a nil value), all i wanted to do was have a nice shader

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
send the script into txt

**Comment by Thimque** [comment]
> 
initLuaShader('GSA')
setSpriteShader('Dad', 'GSA')

**Comment by Thimque** [comment]
> 
Well now its just a black screen.

**Comment by CaptainBaldi** [comment]
problem with your shader

**Comment by Thimque** [comment]
> problem with your shader

Is there a way i can fix it? i really do wanna use this shader

**Comment by Thimque** [comment]
Got it fixed, nvm

**Comment by MrDed9979** [comment]
> Got it fixed, nvm

How did you get it fixed im having the same problem but with my stage .lua file
