### ISSUE TITLE
Faster navigation through chart editor

### ISSUE THREAD

**Issue by mooonyx** [ShadowMario/FNF-PsychEngine#11537]
### What feature do you want to get added on the **base** engine?

Some way to easily go to a specific beat/section in your chart without having to scroll through the chart to get to it. Would save time, especially with longer songs.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
hold shift
