### ISSUE TITLE
onAnimCompleted function

### ISSUE THREAD

**Issue by Troystar23** [ShadowMario/FNF-PsychEngine#11538]
### What is your question?

Basically what im after (if it exists) is if there is a function similar to onTweenCompleted and onTimerCompleted but for animation. This would basically be a function that would allow you to follow up on something after the anim is completed, I dont know if the function exists I basically just need a yes or no answer because if it did exist it would be making life a whole lot easier rn. Thanks in advance :)

**Comment by Drawoon2** [comment]
Yes exist something similar and this is code 
`getProperty("TAG.animation.curAnim.finished")`

**Comment by Troystar23** [comment]
> Yes exist something similar and this is code `getProperty("TAG.animation.curAnim.finished")`

Does this still work in Lua? I'm sorry I completely forgot to specify Lua would be the best for me my mistake

**Comment by RedstoneRuler** [comment]
That is lua code.

**Comment by Troystar23** [comment]
Not sure if I'm doing it right, but why is it that when I call to the object to play an animation after its finished one, the **Next** animation does not play? I wrote it along the lines of if get property tag.animation.curanim.finished then objectplayanimation tag true (I replaced tag with the name of the objects animations names of course)
Any Ideas or Suggestions would be great!

**Comment by frantastic24** [comment]
Make sure the code is under onUpdate or onUpdatePost, watch the uppercase and probably add a check for the animation name
Personally I just use timers for these

**Comment by Troystar23** [comment]
So just in case I went and tested and I found that both the animations alone play fine but once I tell it to play one after the first is finished it just dosent work, I tried in both onUpdate and onupdatePost but no success :(. I'm just going to go with the timer route since I also use it most of the time 👍 (I just wanted to see if there was an alternative way :P)
Thanks again guys :)
