### ISSUE TITLE
strange freeplay crash

### ISSUE THREAD

**Issue by soupnuts6061** [ShadowMario/FNF-PsychEngine#11535]
### Describe your bug here.

tried to play a song in the freeplay menu and the game crashed

error log: ```
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 318)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 99)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 90)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
Song.hx (line 140)
Song.hx (line 132)
FreeplayState.hx (line 371)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid char 118 at position 49445
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Command Prompt/Terminal logs (if existing)

_No response_

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

altered the song tofu to remove all nsfw sprites

**Comment by TheKitBoi** [comment]
your json is broken

**Comment by soupnuts6061** [comment]
false, i do not have an events.json file

**Comment by Grape-Boy** [comment]
your json is fucked up

**Comment by soupnuts6061** [comment]
im telling you, i dont have an events.json file

**Comment by Grape-Boy** [comment]
your chart not events

**Comment by Noel3454565FNF** [comment]
same here but its working with old version of Psych engine
