### ISSUE TITLE
chromebook - exec format error

### ISSUE THREAD

**Issue by NoodleDX** [ShadowMario/FNF-PsychEngine#11531]
### Describe your problem here.

So basically I want to play FNF on my Chromebook.

I have a Linux build.

And when I tried to run it:
`-bash: ./PsychEngine: cannot execute binary file: Exec format error`
And if I run it with `sudo`:
`./PsychEngine: 1: Syntax error: ")" unexpected`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't build it, I got it from Actions

**Comment by Randomxdp** [comment]
if you have arm64 you can try [compiling box64](https://github.com/ptitSeb/box64)

**Comment by pixsplanet** [comment]
> the linux binaries are for x86_64, and if the chrome book has an arm cpu (ig??) then it cant run the binary because of architecture differences

I see

**Comment by pixsplanet** [comment]
how so
