### ISSUE TITLE
Source code filesize just keeps growing

### ISSUE THREAD

**Issue by Icametoforkprojects23** [ShadowMario/FNF-PsychEngine#11533]
### Describe your bug here.

It just keeps GROWING in file size, how do i stop it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not yet, I can't download it...

**Comment by Icametoforkprojects23** [comment]
it's at 148 MB

**Comment by Grape-Boy** [comment]
wdym, what exactly is growing? what are you trying to do?
