### ISSUE TITLE
Error loading character 

### ISSUE THREAD

**Issue by Pavern7** [ShadowMario/FNF-PsychEngine#11543]
### Describe your bug here.

PlayState.hx (line 2928)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx(line 1399)

Uncaught Error: Null Object Refrence

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No i don't do anything

**Comment by DisLolTV** [comment]
Something in character that is required is missing. The required animations are: idle, left, right, up and down
