### ISSUE TITLE
Disable text antialiasing

### ISSUE THREAD

**Issue by Jevilm** [ShadowMario/FNF-PsychEngine#11546]
### What is your question?

How can i make psych engine texts look smoother? With source code

![choppy](https://user-images.githubusercontent.com/110422450/208955313-88e1af8b-b51f-4501-9c85-568f9bcde333.PNG)

**Comment by CaptainBaldi** [comment]
`text.antialiasing = false;`

**Comment by Jevilm** [comment]
> `text.antialiasing = false;`

Thank you
