### ISSUE TITLE
Adding Custom Stages gives me an error and just loads a black background

### ISSUE THREAD

**Issue by TruefateYT** [ShadowMario/FNF-PsychEngine#11544]
### Describe your problem here.

I'm using Psych Engine 6.3 and I was trying to add a custom stage using the example but it just gives me an error and a black background when trying to load my custom stage

The Code if needed: 

function onCreate()
	makeLuaSprite('gm_heartlandback', 'gm_heartlandback', -600, -300);
	setScrollFactor('gm_heartlandback', 0.9, 0.9);
	
	makeLuaSprite('gm_heartlandfront', 'gm_heartlandfront', -600, -300);
	setScrollFactor('gm_heartlandfront', 0.9, 0.9);
	
    makeLuaSprite('gm_heartlandcurtains', 'gm_heartlandcurtains', -600, -300);
	setScrollFactor('gm_heartlandcurtains', 0.9, 0.9);
 end
	
	addLuaSprite('gm_heartlandback', false);
	addLuaSprite('gm_heartlandfront', false);
	addLuaSprite('gm_heartlandcurtains', false); 

![image](https://user-images.githubusercontent.com/75186046/208907488-f9e53828-0f8f-4b8b-b319-28fe821eef7e.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Why is addLuaSprite outside of onCreate

**Comment by TruefateYT** [comment]
> Why is addLuaSprite outside of onCreate

well I just fixed it by moving the addLuaSprite into the side of onCreate, so uh thanks for help
