### ISSUE TITLE
Weeks aren't in right position

### ISSUE THREAD

**Issue by InfernoBrighton** [ShadowMario/FNF-PsychEngine#11545]
So I made a week 10 in my mod and it has been placed between 7 and 8 and not after week 9.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Lorekeeper49** [comment]
Place a `weeksList.txt` file in the weeks folder and type each file name in their in the order you want by line

**Comment by InfernoBrighton** [comment]
ok cheers

**Comment by InfernoBrighton** [comment]
that didnt work

**Comment by InfernoBrighton** [comment]
i dont know if i am doing it incorrectly

**Comment by InfernoBrighton** [comment]
oh i know what i did wrong it is Weeklist.txt not weekslist.txt
