### ISSUE TITLE
Is there a way to add videos on the PsychEngine Source code without Lua? 

### ISSUE THREAD

**Issue by prockscac** [ShadowMario/FNF-PsychEngine#11542]
### What is your question?

I'm on MacBook and I wan't to know if there's a way to edit the source code and add videos to the game.
(since it doesn't work for Lua)

**Comment by CaptainBaldi** [comment]
there is a function for it in source code that the lua function uses, however if mac doesnt support videos for lua it may not support it for source either
anyways the function is `startVideo`, it's in PlayState

**Comment by prockscac** [comment]
I see the code, but how do I connect the video with the song I'm trying to play?

**Comment by prockscac** [comment]
> there is a function for it in source code that the lua function uses, however if mac doesnt support videos for lua it may not support it for source either
> anyways the function is `startVideo`, it's in PlayState

I see the code, but how do I connect the video with the song I'm trying to play?
