### ISSUE TITLE
the freaking null object reference

### ISSUE THREAD

**Issue by AmsDeve** [ShadowMario/FNF-PsychEngine#11540]
### Describe your bug here.

For this reason I think the psych engine is crashing, last night I was trying to add a new story menu, when doing the thing that changes songs with a cur selected or whatever, I was getting null object reference, it happens Also when I put the diamond transition and enter the freeplay, please fix this

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

story menu and transition thing

**Comment by CaptainBaldi** [comment]
if you're gonna label an error you made as a bug then at least show the error

**Comment by TheKitBoi** [comment]
@AmsDeve show the error

**Comment by Grape-Boy** [comment]
show the error:bangbang: :trident::fire:
