### ISSUE TITLE
A shader editor and javascript and c# support (if possible)

### ISSUE THREAD

**Issue by ElPro7777** [ShadowMario/FNF-PsychEngine#11548]
### What feature do you want to get added on the **base** engine?

A shader editor for the pals that dont know how to make a shader and javascript and c# support (if possible)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CaptainBaldi** [comment]
💀

**Comment by TheKitBoi** [comment]
(wont-do) moment

**Comment by ShadowMilky** [comment]
shader editor? nah, text editor is better
also Javascript and C# support isn't possible in haxe im pretty sure

**Comment by ElPro7777** [comment]
> I'm pretty sure that Javascript and C# support isn't possible in haxe

Haxe can build cross-platform applications targeting JavaScript, C++, C#, Java, JVM, Python, Lua, PHP, Flash, and allows access to each platform's native capabilities. Haxe has its own VMs (HashLink and NekoVM) but can also run in interpreted mode. Code written in Haxe can be compiled to any target Haxe supports. (Source: https://haxe.org/#:~:text=Haxe%20can%20build%20cross%2Dplatform,to%20any%20target%20Haxe%20supports.)

**Comment by EyeDaleHim** [comment]
> > I'm pretty sure that Javascript and C# support isn't possible in haxe
> 
> Haxe can build cross-platform applications targeting JavaScript, C++, C#, Java, JVM, Python, Lua, PHP, Flash, and allows access to each platform's native capabilities. Haxe has its own VMs (HashLink and NekoVM) but can also run in interpreted mode. Code written in Haxe can be compiled to any target Haxe supports. (Source: https://haxe.org/#:~:text=Haxe%20can%20build%20cross%2Dplatform,to%20any%20target%20Haxe%20supports.)

We want suggestions, not trash bloats.

**Comment by EyeDaleHim** [comment]
I get what you were trying to do with Shader Editor, you initially had the idea that it is revolutionary.

It really isn't suggestive. But we'll see.

**Comment by Minalog** [comment]
About the JavaScript and C# support, you can run Haxe code already. Just type in `runHaxeCode()` and put your code inside the parentheses. Don't forget about the quotes. ("")

**Comment by ShadowMilky** [comment]
> > I'm pretty sure that Javascript and C# support isn't possible in haxe
> 
> Haxe can build cross-platform applications targeting JavaScript, C++, C#, Java, JVM, Python, Lua, PHP, Flash, and allows access to each platform's native capabilities. Haxe has its own VMs (HashLink and NekoVM) but can also run in interpreted mode. Code written in Haxe can be compiled to any target Haxe supports. (Source: https://haxe.org/#:~:text=Haxe%20can%20build%20cross%2Dplatform,to%20any%20target%20Haxe%20supports.)

no not the targets, the file support in a similar way of lua

**Comment by ShadowMario** [comment]
ShaderToy
