### ISSUE TITLE
Im trying to create a fnf mod and When ever i create a .json for a song this happens 

### ISSUE THREAD

**Issue by DakoReal** [ShadowMario/FNF-PsychEngine#11559]
### Describe your problem here.

C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
FreeplayState.hx (line 371)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/painfull-end/painfull-end-hard.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
 And for the other song 
 C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)

FreeplayState.hx (line 371)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/problems/problems-hard.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No i just added the song and i didnt add any notes in freeplay and this just happens

**Comment by CaptainBaldi** [comment]
missing chart file

**Comment by DakoReal** [comment]
No i put the Data in mods/Data/Problems There just wasnt any notes in there But there was a data file for every song it just hasnt been charted yet

**Comment by Minalog** [comment]
Since I know you created a chart file, does it end with "-hard"?
