### ISSUE TITLE
Difficulty selection screen?

### ISSUE THREAD

**Issue by Emeninja972** [ShadowMario/FNF-PsychEngine#11556]
### What is your question?

I was Wondering if anyoe Knows how too make a difficulty selection screen. For if your song starts in the main menu like in twinsonia

**Comment by Minalog** [comment]
So I assume you're building with the source. All I know is you might want to create a file called DifficultySelector.hx and make it to where when you enter a level, you go to the difficulty selector and you enter the level with the difficulty you just chose.

**Comment by Emeninja972** [comment]
Hmmm Ok lemme see.
