### ISSUE TITLE
onClick doesn't work properly

### ISSUE THREAD

**Issue by LodedRick** [ShadowMario/FNF-PsychEngine#11557]
### Describe your problem here.

![w](https://user-images.githubusercontent.com/112434798/209221941-42c696f7-e9c6-4747-8e1a-7e98ea332a07.png)
when i open the song and click it takes me to the song when its supposed to take me to the song if i click at a specific thing
or it just doesn't work at all

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
That's not how it works
It checks if a mouse button was pressed, not where

**Comment by LodedRick** [comment]
> That's not how it works It checks if a mouse button was pressed, not where

is there even any way to make it work how i want

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#mouse-position-functions

**Comment by LodedRick** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#mouse-position-functions

what abt it

**Comment by frantastic24** [comment]
Use that to make it work like you want it to

**Comment by LodedRick** [comment]
> Use that to make it work like you want it to

how do i use that

**Comment by Minalog** [comment]
> > Use that to make it work like you want it to
>
> how do i use that

I just built example code to show how it might work. I'm not entirely sure either haha
```lua
if getMouseX("hud") > --[[ farthest left point of your button ]] and
    getMouseX("hud") < --[[ farthest right point of your button ]] and
    getMouseY("hud") > --[[ farthest bottom point ]] and
    getMouseX("hud") < --[[ farthest top point ]] then
    -- code
end
```

**Comment by LodedRick** [comment]
> > > Use that to make it work like you want it to
> > 
> > 
> > how do i use that
> 
> I just built example code to show how it might work. I'm not entirely sure either haha
> 
> ```lua
> if getMouseX("hud") > --[[ farthest left point of your button ]] and
>     getMouseX("hud") < --[[ farthest right point of your button ]] and
>     getMouseY("hud") > --[[ farthest bottom point ]] and
>     getMouseY("hud") < --[[ farthest top point ]] then
>     -- code
> end
> ```

doesnt seem to work
