### ISSUE TITLE
Can't open psych engine on unzipped files but i only can open it on zipped files by using winrar

### ISSUE THREAD

**Issue by NonsenseOculto** [ShadowMario/FNF-PsychEngine#11566]
### What is your question?

I can't  open psych engine when i try to open on a zip file. But i can open in winrar files, but i kinda did not like to use winrar to open psych engine. How do i fix it?

**Comment by Minalog** [comment]
Explain further please. No offense but you're kinda confusing me lol

**Comment by Lorekeeper49** [comment]
Archives are meant to be extracted before you can do anything with them

**Comment by Minalog** [comment]
By extracting, he means basically taking everything out and putting it in a folder or somethin

**Comment by NonsenseOculto** [comment]
im kinda confused abt your comments lol. my psych engine only works on 32 bits but my computer is 64 bits and its kinda not working in 64 bits version ._.

**Comment by Final-Miku** [comment]
So, why not unzip it and use it?

**Comment by NonsenseOculto** [comment]
oh, i forgot to say it was unzipped, i can only open zip files in winrar ._.

**Comment by NonsenseOculto** [comment]
and i mean the psych engine on zip file while winrar

**Comment by NonsenseOculto** [comment]
the unzipped file is not working

**Comment by NonsenseOculto** [comment]
is there a solution?
