### ISSUE TITLE
How to do flipX with the object we made with makeAnimatedLuaSprite function ?

### ISSUE THREAD

**Issue by BillyLOLwkwk** [ShadowMario/FNF-PsychEngine#11567]
### What is your question?

So actually how to do it ?
If i use the scale function, it just move the character too. I dont want it happen. Could some one help me code it in Lua ? i just confuse how to algorithm work...

This flipX is same with the sample with the flipX in character editor...

**Comment by Minalog** [comment]
After you create the Lua sprite, add this line of code.
```lua
setProperty("newSprite.scale.x", -1)
```

**Comment by BillyLOLwkwk** [comment]
> After you create the Lua sprite, add this line of code.
> 
> ```lua
> setProperty("newSprite.scale.x", -1)
> ```

but it's like mirroring the the sprite and make the sprite in different location, i meant like still in that place...

**Comment by Minalog** [comment]
Did you create your resource in Adobe Animate? If so, then you might want to move every frame to the center and do some more readjusting so it doesn't shift your sprite.

**Comment by BillyLOLwkwk** [comment]
> Did you create your resource in Adobe Animate? If so, then you might want to move every frame to the center and do some more readjusting so it doesn't shift your sprite.

No i dont, i even dont know adobe animate. But do you know how to get every frame width of all sing animation ? if you know please tell me... of course with lua

**Comment by Gostar64** [comment]
```Lua
setProperty('theSprite.flipX', true)
