### ISSUE TITLE
The event crashes the game

### ISSUE THREAD

**Issue by microsoft026** [ShadowMario/FNF-PsychEngine#11560]
### Describe your bug here.

what happened is that I was doing a mod and between wing song and crash me and did not show the reason fast me

### Command Prompt/Terminal logs (if existing)

```bash
no
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by CaptainBaldi** [comment]
bro you literally said "The event crashes the game" and DIDNT EVEN SPECIFY THE EVENT 💀 
you most likely used one of the events that are hardcoded to a specific stage

**Comment by microsoft026** [comment]
Ins data/yoursongsxd
Yoursongs.json
Script1
Script2
Events

**Comment by Yuta12342** [comment]
> Ins data/yoursongsxd Yoursongs.json Script1 Script2 Events

These are just names of files. You need to specify what these "Scripts" even are, and the actual Events contained in the song that could be a contributor to the crash.

Saying filenames doesn't exactly tell us anything.
