### ISSUE TITLE
How do I make a strum line move another way?

### ISSUE THREAD

**Issue by Minalog** [ShadowMario/FNF-PsychEngine#11569]
### Describe your problem here.

This may seem like a stupid question, but how do I make an arrow go another way?
I don't want it going like
🡆
🡆
↑↑
...But rather like
⇉🡆 🡆
How would I do this? And I don't even care if it needs `runHaxeCode()` I just want it done 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, just created a mod

**Comment by Drawoon2** [comment]
Use`	noteTweenDirection(tag,note id,direction,time,ease)`

**Comment by Minalog** [comment]
Oh ok
