### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by InfernoBrighton** [ShadowMario/FNF-PsychEngine#11576]
### Describe your bug here.

Game Randomly crashes after i switch between songs, I don't know if it is because of the different charts or different characters.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by DisLolTV** [comment]
same

**Comment by InfernoBrighton** [comment]
Seems like no one helped

**Comment by Noel3454565FNF** [comment]
but with old version its working
