### ISSUE TITLE
Font is not right

### ISSUE THREAD

**Issue by DisLolTV** [ShadowMario/FNF-PsychEngine#11575]
I think the font is not great because it's bugged. I only imported my mod from 0.6.2 to 0.6.3. I don't really khow what this.
It's just "%" not the letter of the song.

**Comment by TheKitBoi** [comment]
replace ur mod alphabet with a new one assets\images
![image](https://user-images.githubusercontent.com/84044666/209475386-f27e07d1-1184-4b75-94c1-4a95189b2df4.png)

**Comment by DisLolTV** [comment]
ok I'II check if it works

**Comment by DisLolTV** [comment]
It's still the same

**Comment by DisLolTV** [comment]
wait i think i khow the solution

**Comment by DisLolTV** [comment]
I did repair it. I had in mods folder old alphabet file that's why.

**Comment by DisLolTV** [comment]
If alphabet is just "%" check assets/images and mods/images
