### ISSUE TITLE
Help (LUA)

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#11577]
### Describe your problem here.

I would like to put the player behind the opponent, to change the layer order, but idk how to. could someone write me a script for that?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, PlayState.hx, TitleState.hx, StoryMode.hx and MainMenuState.hx (idk maybe i got the names wrong)

**Comment by GatoMorado621** [comment]
You could use the object order. This is in the wiki. If you need more help tell me.

**Comment by CheesecakeForever** [comment]
Sorry, forgot to close the issue, found that out shortly after i wrote this. Thanks though!
