### ISSUE TITLE
how can i fix the sustain note its broken

### ISSUE THREAD

**Issue by Den198888** [ShadowMario/FNF-PsychEngine#11574]
### Describe your problem here.

i scaled the note to 0.55 but then this happened the sustain notes is broken idk how to fix it

https://user-images.githubusercontent.com/96397208/209474457-f7d2ecb9-2955-4ba1-8c5a-9a90128e93bb.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

**Comment by Drawoon2** [comment]
Try with this code
`	for i = 0, getProperty('unspawnNotes.length')-1 do
		if getPropertyFromGroup('unspawnNotes', i, 'isSustainNote') and not stringEndsWith(getPropertyFromGroup('unspawnNotes', i, 'animation.curAnim.name'),'end') then
		setPropertyFromGroup('unspawnNotes', i, 'scale.y',11) 
		end
		updateHitboxFromGroup('unspawnNotes',i) 
	end`

**Comment by Den198888** [comment]
Thank u😃
