### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by lime360** [ShadowMario/FNF-PsychEngine#11572]
### What is your question?

how do i make ability to read charts in `charts/` folder without putting jsons into a seperate folder just like [there](https://github.com/Erizur/FNF-DaveEngine/tree/main/assets/preload/data/charts), same thing goes to lua scripts and dialogues

**Comment by Jevilm** [comment]
Are you doing this without source code? Then it is not possible

**Comment by lime360** [comment]
i am doing it with source code
