### ISSUE TITLE
I cannot build the engine.

### ISSUE THREAD

**Issue by OofieTheNoob** [ShadowMario/FNF-PsychEngine#11579]
### Describe your bug here.

Basically, I have everything that is used for building the engine, but the problem is that whenever I build it, it says source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
![Screenshot 2022-12-25 184859](https://user-images.githubusercontent.com/118780797/209486706-c6f1d5b5-c4f5-4035-b798-d3895a1d2044.png)

### Command Prompt/Terminal logs (if existing)

```bash
Image is on the bug.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by TheKitBoi** [comment]
copy the new Main.hx
https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

**Comment by OofieTheNoob** [comment]
thanks
