### ISSUE TITLE
UHHHH-

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#11587]
### Describe your bug here.

THE GAME CRASHES MIDSONG, WITH NO TERMINAL LOG!
Look. Click the drive link.
https://drive.google.com/file/d/1SgrZpGnrJCbBz6DseIZfwjLWNH8gJfo8/view?usp=sharing

### Command Prompt/Terminal logs (if existing)

```bash
N/A
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I used both Source and Lua to make the mod

**Comment by PDL2CGamejolt** [comment]
I forgor the microphone was on

**Comment by RandomDev3** [comment]
Depending on the video, you have a lot of stuff programmed inside the song, the only 2 things I can say is, that your mod went over the RAM allocation limit (RAM allocation is used for restricting the amount of your memory the game uses, so it doesn't crash your computer), or there is an error interfering with the gameplay (you should re-check your code and troubleshoot for anything).

**Comment by PDL2CGamejolt** [comment]
Oof

**Comment by PDL2CGamejolt** [comment]
I removed some parts of the script, and it stopped crashing!
