### ISSUE TITLE
Want to change the font in Dialogues

### ISSUE THREAD

**Issue by EvaaaaaYO** [ShadowMario/FNF-PsychEngine#11585]
### Describe your problem here.

I downloaded FNF-PsychEngine-main and noticed the font in Dialogues is an Image file. 
I want to change it for .ttf file,and also find that  some files are related: Alphabet.hx , TypedAlphabet.hx , DialogueBoxPsych.hx , DialogueEditorState.hx.
Because I'm a rookie programmer,I don't know how to edit these file.
Please somebody help me.
(I tried to edit the font in DialogueBox.hx (which is used for senpai) ,it worked. But I don't want to give up on PsychEngine's beautiful animated dialogue boxes. )

Sorry,my English is not very good.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I tried to change "var daText:TypedAlphabet = null;"  for  "var daText:FlxText;" in the DialogueBoxPsych.hx ,but it's failed.

**Comment by DisIsNOt** [comment]
what are you trying to do exactly?

**Comment by EvaaaaaYO** [comment]
> what are you trying to do exactly?

I want to change this font
![插圖](https://user-images.githubusercontent.com/121437461/209842033-91fadf94-c5a7-4d57-bfe3-8523f0d7986a.jpg)
for like that font
![插圖2](https://user-images.githubusercontent.com/121437461/209841681-855ea96a-c416-4594-812e-7e33318a8cb4.jpg)

Sorry for the confusion.
