### ISSUE TITLE
Main.hx problems

### ISSUE THREAD

**Issue by RandomDev3** [ShadowMario/FNF-PsychEngine#11589]
### Describe your bug here.

Whenever I try to compile the game, it shows **Main.hx** errors.

- I use Haxe 4.2.4
- All of the components are up to date. 
- I installed every necessary modules to compile.

### Command Prompt/Terminal logs (if existing)

```bash
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited PlayState.hx for a custom losing screen, and I put some stuff in example_mods folder. But it didn't show any errors on these files/folders.

**Comment by nennneko5787** [comment]
Install Haxe 4.2.5, the latest version of Haxe

**Comment by RandomDev3** [comment]
I did that, but the version give me HxCodec version and entirely messes up the code, this is the line the error highlights:

`addChild(new FlxGame(gameWidth, gameHeight, initialState, zoom, framerate, framerate, skipSplash, startFullscreen));`

**Comment by nennneko5787** [comment]
Replacing Main.hx with the latest should solve the problem!
https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

**Comment by RandomDev3** [comment]
Thank you very much, it worked

**Comment by TheKitBoi** [comment]
close this issue

**Comment by nennneko5787** [comment]
close this issue
https://i.imgur.com/UTha07F.png
