### ISSUE TITLE
Support for slower and faster playback speeds

### ISSUE THREAD

**Issue by 40U538072** [ShadowMario/FNF-PsychEngine#11582]
### What feature do you want to get added on the **base** engine?

So far, playback speeds can go from .5x to 3x. I am thinking maybe it is possible to support a wider range of speeds, possibly from 0.25x to 4x or higher. Wondering of that is a possibility.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CaptainBaldi** [comment]
there's no reason why this should be a thing

**Comment by TheKitBoi** [comment]
> ### What feature do you want to get added on the **base** engine?
> So far, playback speeds can go from .5x to 3x.

do it ur self
https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/GameplayChangersSubstate.hx#L66

**Comment by 40U538072** [comment]
@TheKitBoi Thanks. I should get to learning source code at some point. Closing this now.
