### ISSUE TITLE
I encountered some problems while playing the 0.52 mod.

### ISSUE THREAD

**Issue by Final-Miku** [ShadowMario/FNF-PsychEngine#11599]
### What is your question?

Invalid char 0 at position 0

I don't know why I reported this wrong.

But some don't report mistakes.

I asked the author, and he said he had never seen it either, so I wanted to ask.

Here may be the answer I want.

**Comment by TheKitBoi** [comment]
send the file that causing it
also rename it to txt for attaching files

**Comment by Final-Miku** [comment]
I don't know what caused it. It didn't tell me which file it was.
I guess I'll just have to send the wrong file.

**Comment by Final-Miku** [comment]
#的副本I don't know what caused it. It didn't tell me which file it was.
I guess I'll just have to send the wrong file.

**Comment by Final-Miku** [comment]
Duplicate of # I don't know what caused it. It didn't tell me which file it was.

I guess I'll just have to send the wrong file.

**Comment by Final-Miku** [comment]
Duplicate of # Oh, didn't 0.52 report an error?

Then I may need to go to the next 0.62h

**Comment by Final-Miku** [comment]
[PsychEngine_2022-12-28_22'51'27.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/10316938/PsychEngine_2022-12-28_22.51.27.txt)

**Comment by TheKitBoi** [comment]
your char has a missing json file

**Comment by Final-Miku** [comment]
Duplicate of #
No, no, no
This is a problem with Psych Engine
I wrote the json of char with Visual Stodio, but it didn't work.

**Comment by frantastic24** [comment]
It's a problem with your file

**Comment by Final-Miku** [comment]
Duplicate of #
I'm sure there is no problem, because the text inside is copied from the original version.

**Comment by Final-Miku** [comment]
Duplicate of #
Both name and xml are matched, and the format is completely original content, but it can't work.

**Comment by frantastic24** [comment]
Names are the problem, it's the formatting inside
Can't help much if you don't share the files
