### ISSUE TITLE
Character Head Bobbing

### ISSUE THREAD

**Issue by OmartheMetaRunner** [ShadowMario/FNF-PsychEngine#11595]
### What is your question?

Does anyone know how to make the character's head beat faster without making the BPM higher than it needs to be?

**Comment by Drawoon2** [comment]
Change `setProperty('dad.danceEveryNumBeats',1)` default is 2

**Comment by OmartheMetaRunner** [comment]
> Change `setProperty('dad.danceEveryNumBeats',1)` default is 2

thank u

**Comment by Drawoon2** [comment]
I recomend make this in the onCreatePost()

**Comment by OmartheMetaRunner** [comment]
> I recomend make this in the onCreatePost()

ok
