### ISSUE TITLE
How to fix this???? | Source code

### ISSUE THREAD

**Issue by DisLolTV** [ShadowMario/FNF-PsychEngine#11596]
### Describe your problem here.

![Zrzut ekranu_20221228_103540](https://user-images.githubusercontent.com/121395767/209791390-e6535424-4f07-4a50-9703-c2dd0aca7a79.png)

How to fix this???

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

**Comment by Chidubemmo** [comment]
Remove zoom in Main.hx, that how I solved it

**Comment by TheKitBoi** [comment]
replace Main.hx with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

**Comment by DisLolTV** [comment]
Thank you, I only need to reinstall VS 2019 because I deleted it and I need it
