### ISSUE TITLE
changing menu backgrounds for each menu option. 

### ISSUE THREAD

**Issue by prockscac** [ShadowMario/FNF-PsychEngine#11597]
### What is your question?

how can I make  the main menu background change for each main menu option?

**Comment by Jevilm** [comment]
Go to the code tab, click on <> code and click on "Download as ZIP"

**Comment by CaptainBaldi** [comment]
> 

how is this related to the question

**Comment by Jevilm** [comment]
> > 
> 
> how is this related to the question

I commented on the wrong one oops
