### ISSUE TITLE
How to make password

### ISSUE THREAD

**Issue by Steve35117** [ShadowMario/FNF-PsychEngine#11592]
### Describe your problem here.

I am making a mod where before you enter a song, you need a password. how?
![hoaaa](https://user-images.githubusercontent.com/95169213/209687578-373827db-eb75-4e02-9e57-abb936199faf.png)
aka like this

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes

**Comment by DisLolTV** [comment]
I donn't khow. I think you must ask programmer of the mod

**Comment by RandomDev3** [comment]
Check the mod if it has source code available, maybe you can "borrow" a thing or two.

**Comment by IdiotLimitedEdition** [comment]
FlxInputText maybe???
