### ISSUE TITLE
tag.xAdd won't work

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#11591]
### Describe your problem here.

So i am (obviously) coding something and this thing won't work. here's the batch of code it's used in. I really don't know what is the problem.

```
		var pauseart = new AttachedSprite('pauseart');
		pauseart.screenCenter(X);
		pauseart.screenCenter(Y);
		pauseart.alpha = 0;
		pauseart.xAdd = 40;
		add(pauseart);
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, PlayState.hx, TitleState.hx, StoryMode.hx and MainMenuState.hx (idk maybe i got the names wrong)

**Comment by TheKitBoi** [comment]
it’s supposed to be pauseart.x without the Add

**Comment by Drawoon2** [comment]
`pauseart.x += 40;`
