### ISSUE TITLE
I really need help

### ISSUE THREAD

**Issue by Normalhuman1475** [ShadowMario/FNF-PsychEngine#116]
Im on Visual Studio code, and as soon as i go into the psych engine folder i see this
![image](https://user-images.githubusercontent.com/89854107/134688420-8fce2137-9ec8-4905-842d-a269bcde7e6e.png)
and then i check what was going on and I see this
![image](https://user-images.githubusercontent.com/89854107/134688599-415e9ee1-f0c3-47df-b1ef-59278246f0e3.png)
What is going on???
Im also on linux if that means anything

**Comment by FuseIsHere813** [comment]
You might be missing some haxe libraries. Check for any non installed libraries in the "Project.xml" file and install them if you found them libraries. If not, contact @ShadowMario for help.

**Comment by ShadowMario** [comment]
As i've never had a machine other than Windows, i can't be sure about these issues.

**Comment by Normalhuman1475** [comment]
> As i've never had a machine other than Windows, i can't be sure about these issues.
I mean its probably the same thing

**Comment by ShadowMario** [comment]
First off, you didn't import sys.FileSystem on your Paths, second, there's a missing comma on line 3302, and lastly it looks like you installed haxe wrong on your machine, since it is missing FlxActionInputDigitalAndroid

**Comment by Normalhuman1475** [comment]
> First off, you didn't import sys.FileSystem on your Paths, second, there's a missing comma on line 3302, and lastly it looks like you installed haxe wrong on your machine, since it is missing FlxActionInputDigitalAndroid
Ok, thank you for responding, but I only have few more questions, 1, Is sys.FileSystem like something i need to install because I went there and i saw this.
![image](https://user-images.githubusercontent.com/89854107/134912990-93696521-0eac-4562-a02e-e2ea1758fdf3.png)
And 2, Where do i put the comma at line 3302?
![Screenshot 2021-09-27 8 52 02 AM](https://user-images.githubusercontent.com/89854107/134913296-e4e095e6-b06d-4eae-a525-c97107b631eb.png)
