### ISSUE TITLE
Making the health bar dissapear

### ISSUE THREAD

**Issue by GWRRailway** [ShadowMario/FNF-PsychEngine#11606]
### What is your question?

How do I make the health bar be invisible/out of view with lua?

**Comment by TheKitBoi** [comment]
setProperty('iconP1.visible',false)
setProperty('iconP2.visible',false)
setProperty('healthBar.visible',false)
setProperty('healthBarBG.visible',false)

**Comment by Drawoon2** [comment]
setProperty('iconP2.visible',false)
setProperty('iconP1.visible',false)
setProperty('healthBar.alpha',0)
