### ISSUE TITLE
title screen

### ISSUE THREAD

**Issue by CertMusic** [ShadowMario/FNF-PsychEngine#11601]
### What is your question?

how do i disable this?
![image](https://user-images.githubusercontent.com/121579919/209867315-d84e6890-7d72-4c5a-9d4b-949b4266b1a3.png)

**Comment by TheKitBoi** [comment]
type shadow again

**Comment by CertMusic** [comment]
thanks

**Comment by TheKitBoi** [comment]
close this issue
