### ISSUE TITLE
Problem loading a custom song

### ISSUE THREAD

**Issue by Jammington24** [ShadowMario/FNF-PsychEngine#11602]
### Describe your problem here.

C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
FreeplayState.hx (line 371)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/legacy-d-side/legacy-d-side-rechart.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

So, I copied and pasted the .json file of the song into the data folder of the new one. I already have the assets and the .ogg of the song. My new song is already visible on Freeplay, but displays this error message when I try to open it... am I missing something? I don't really know what this error message tries to tell me.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I used a 1 song mod folder, added my custom song's inst, and tried to duplicate a .json file to later edit it in the engine. I modified the week folder so it displays my song's title, and it IS visible, but doesn't load.

**Comment by TheKitBoi** [comment]
did you add the -rechart into the json name

**Comment by Jammington24** [comment]
Oh
Now I did it.
It works now! Thanks!

**Comment by TheKitBoi** [comment]
close this issue
