### ISSUE TITLE
Issue with writing a lua script

### ISSUE THREAD

**Issue by SteveeTheCreeper** [ShadowMario/FNF-PsychEngine#11609]
### Describe your problem here.

Hello
I was writing a lua script about that if the camera will focus on bf then opponent will change pose to idle like the base game
When I tried it, it said: Expected arguments near ')' and it didn't work
Here is the script

function onMoveCamera(focus)
	if focus == 'boyfriend' then
characterDance(character:Dad) 
end
end
 Can someone help me fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by Drawoon2** [comment]
`function onMoveCamera(focus)
    if focus == 'boyfriend' then
    characterDance('dad')
    end
end`

**Comment by SteveeTheCreeper** [comment]
> `function onMoveCamera(focus) if focus == 'boyfriend' then characterDance('dad') end end`

It works
Thanks
