### ISSUE TITLE
Something Is not right with the build

### ISSUE THREAD

**Issue by DisLolTV** [ShadowMario/FNF-PsychEngine#11605]
### Describe your problem here.

When I tried to compile for the first time I got this:

![Zrzut ekranu_20221229_131632](https://user-images.githubusercontent.com/121395767/209950178-e3206774-d0a8-4a7a-b6ae-ab6cf2fb25fc.png)

I think something is missing but I don't khow what is missing.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ArdoDev-stupid** [comment]
it's prob just hxCodec being stupid, don't worry. just close this
