### ISSUE TITLE
how would i make a song appear after pressing seven in a certain song

### ISSUE THREAD

**Issue by CertMusic** [ShadowMario/FNF-PsychEngine#11603]
### Describe your problem here.

i'm trying to make it so it shows a song is locked but it can't be unlocked until pressing 7 on certain song but it's not working

this is my code:
```
function onCreatePost()
  setProperty('debugKeysChart', null);
end
function onUpdate()
   if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
      loadSong('goob');
   end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No I didn't edit the script except for changing the song name.

**Comment by Kufferey** [comment]
Hold Up ima write some code.

**Comment by idk479** [comment]
delete the function onCreatePost script

**Comment by PDL2CGamejolt** [comment]
It;s Nil instead of "Null"
