### ISSUE TITLE
Opponent Sing on Player Note Hit

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#11615]
### Describe your problem here.

I am making a mod, and at some point, I need a way for the opponent to sing when a note is pressed (THIS IS WITH CUSTOM NOTETYPES), is there any possible scripts I could use to do so?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by fnfdemonboi314159** [comment]
nvm, figured it out, after a little bit of thinking.

**Comment by fnfdemonboi314159** [comment]
turns out the code is EXTREMELY SIMPLE TO Code, So what's the point of this whole issue?

**Comment by THite06** [comment]
For those who had a similar problem looking for a way to do this, here's the simple way I found:

`function goodNoteHit(id, direction, noteType, isSustainNote)
	if noteType == 'OpponentSing' then
		if direction == 0 then
			objectPlayAnimation('dad', 'singLEFT', true, 24)
		elseif direction == 1 then
			objectPlayAnimation('dad', 'singDOWN', true, 24)
		elseif direction == 2 then
			objectPlayAnimation('dad', 'singUP', true, 24)
		elseif direction == 3 then
			objectPlayAnimation('dad', 'singRIGHT', true, 24)
		end
	end
end`

**Comment by frantastic24** [comment]
when no array

**Comment by fnfdemonboi314159** [comment]
> 

Here's a simplified version
```
local dir = {'LEFT', 'DOWN', 'UP', 'RIGHT'};
function goodNoteHit(membersIndex, noteData, noteType, isSustainNote)
    if noteType == "OpponentSing" then
        playAnim('dad', 'sing' .. dir[noteData+1], true)
    end 
end
```
