### ISSUE TITLE
How to save the ratingFC of a song after completing it?

### ISSUE THREAD

**Issue by Chidubemmo** [ShadowMario/FNF-PsychEngine#11619]
### Describe your problem here.

I tried to simply do
```hx
scoreText.text = 'PERSONAL BEST: ' + lerpScore + ' (' + ratingSplit.join('.') + '%)'+ '('+ PlayState.ratingFC + ')';
```
but it saved the rating of the last song I played
How do I save the highscore of every song and update it?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Randomized main menu characters in Mainmenu.hx

**Comment by nennneko5787** [comment]
Replace HighScore.hx with the following
https://pastebin.com/wAddRBzi
Replace this line in PlayState.hx with
<pre>
Highscore.saveScore(SONG.song, songScore, storyDifficulty, percent);
</pre>
Replace with this
<pre>
Highscore.saveScore(SONG.song, songScore, storyDifficulty, percent, ratingFC);
</pre>
Replace FreeplayState.hx with the following
https://pastebin.com/hSsFaGxy
This should do it.

**Comment by Chidubemmo** [comment]
> Replace HighScore.hx with the following
> https://pastebin.com/wAddRBzi
> Replace this line in PlayState.hx with
> <pre>
> Highscore.saveScore(SONG.song, songScore, storyDifficulty, percent);
> </pre>
> Replace with this
> <pre>
> Highscore.saveScore(SONG.song, songScore, storyDifficulty, percent, ratingFC);
> </pre>
> Replace FreeplayState.hx with the following
> https://pastebin.com/hSsFaGxy
> This should do it.

MY MAN
