### ISSUE TITLE
locals

### ISSUE THREAD

**Issue by alexxdddddd** [ShadowMario/FNF-PsychEngine#11614]
### What is your question?

so this does not work

local addfont = true
local fontname = "SpecialElite.ttf"
                     if addfont == true then
            setTextFont('text', ''..fontname)

**Comment by XTihX1** [comment]
**here, should work i think.

```
local addfont = true
local fontname = "SpecialElite.ttf"
if addfont == true then
setTextFont('text', fontname)
end
```**
