### ISSUE TITLE
Note tweens being weird. (SOURCE CODE)

### ISSUE THREAD

**Issue by NesDoesGithub** [ShadowMario/FNF-PsychEngine#11610]
### Describe your problem here.

I'm trying to make the notes swap to the other side of the screen with a tween, but sometimes the tween goes off the screen but other times it works fine, does anyone have a different way of doing this?

```
						opponentStrums.forEach(function(spr:FlxSprite) 
							{
								if(!ClientPrefs.middleScroll)
									FlxTween.tween(spr, {x: spr.x += 640, y: spr.y}, 0.01, {ease: FlxEase.quartOut});
								// spr.x += 700;
							});
						playerStrums.forEach(function(spr:FlxSprite)
							{
								if(!ClientPrefs.middleScroll)
									FlxTween.tween(spr, {x: spr.x -= 640, y: spr.y}, 0.01, {ease: FlxEase.quartOut});
								// spr.x -= 600;
							});
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

**Comment by UncertainProd** [comment]
In both of the FlxTween.tween lines, replace `{x: spr.x += 640 .....` with `{x: spr.x + 640 .....`
basically like this:
```haxe
opponentStrums.forEach(function(spr:FlxSprite) 
{
								if(!ClientPrefs.middleScroll)
									FlxTween.tween(spr, {x: spr.x + 640, y: spr.y}, 0.01, {ease: FlxEase.quartOut});
								// spr.x += 700;
							});
						playerStrums.forEach(function(spr:FlxSprite)
							{
								if(!ClientPrefs.middleScroll)
									FlxTween.tween(spr, {x: spr.x - 640, y: spr.y}, 0.01, {ease: FlxEase.quartOut});
								// spr.x -= 600;
							});
```

**Comment by NesDoesGithub** [comment]
> In both of the FlxTween.tween lines, replace `{x: spr.x += 640 .....` with `{x: spr.x + 640 .....` basically like this:
> 
> ```hx
> opponentStrums.forEach(function(spr:FlxSprite) 
> {
> 								if(!ClientPrefs.middleScroll)
> 									FlxTween.tween(spr, {x: spr.x + 640, y: spr.y}, 0.01, {ease: FlxEase.quartOut});
> 								// spr.x += 700;
> 							});
> 						playerStrums.forEach(function(spr:FlxSprite)
> 							{
> 								if(!ClientPrefs.middleScroll)
> 									FlxTween.tween(spr, {x: spr.x - 640, y: spr.y}, 0.01, {ease: FlxEase.quartOut});
> 								// spr.x -= 600;
> 							});
> ```

it still happens whenever i play the song, is there a completely different way of switching the notes around?

**Comment by UncertainProd** [comment]
something like this could work too
```haxe
for(i in 0...playerStrums.members.length)
{
  var playerNoteX = playerStrums.members[i].x;
  var opponentNoteX = opponentStrums.members[i].x;
  FlxTween.tween(playerStrums.members[i], { x: opponentNoteX }, 0.01, {ease: FlxEase.quartOut});
  FlxTween.tween(opponentStrums.members[i], { x: playerNoteX }, 0.01, {ease: FlxEase.quartOut});
}
```

**Comment by NesDoesGithub** [comment]
> something like this could work too
> 
> ```hx
> for(i in 0...playerStrums.members.length)
> {
>   var playerNoteX = playerStrums.members[i].x;
>   var opponentNoteX = opponentStrums.members[i].x;
>   FlxTween.tween(playerStrums.members[i], { x: opponentNoteX }, 0.01, {ease: FlxEase.quartOut});
>   FlxTween.tween(opponentStrums.members[i], { x: playerNoteX }, 0.01, {ease: FlxEase.quartOut});
> }
> ```

it still doesn't work, im resorting to lua.
