### ISSUE TITLE
Psych Engine 5.1 Compiling Issue

### ISSUE THREAD

**Issue by kukl222** [ShadowMario/FNF-PsychEngine#11618]
### Describe your problem here.

I keep having this error where it just keeps saying this:
source/Main.hx:113: characters 22-35 : Class<DiscordClient> has no field isInitialized (Suggestion: initialize)
I'm trying to save an fnf mod because they need someone who can compile the game.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I put the new Main.hx code in the build.

**Comment by TheKitBoi** [comment]
haxelib install flixel 4.11.0

**Comment by kukl222** [comment]
didn't work. idk what else to write so uhhh yeah

**Comment by TheKitBoi** [comment]
then replace it with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx
