### ISSUE TITLE
Uh-

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#11613]
### Describe your bug here.

The game crashed with no terminal log while I made an unfinished chart with 11k+ notes...

### Command Prompt/Terminal logs (if existing)

```bash
N/A
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I used both Source and Lua to make the mod

**Comment by TheKitBoi** [comment]
ar u using extra keys mod

**Comment by CaptainBaldi** [comment]
ur pc probably just hates you
goofy ahh mf has a song with 11k notes my pc would be dying

**Comment by PDL2CGamejolt** [comment]
> ar u using extra keys mod

No.

**Comment by PDL2CGamejolt** [comment]
> ar u using extra keys mod

I'm using the og PE. (I mean on 0.6.3)

**Comment by PDL2CGamejolt** [comment]
> ur pc probably just hates you goofy ahh mf has a song with 11k notes my pc would be dying

I just nerfed the chart and it didn't crash
