### ISSUE TITLE
How to change song's name?

### ISSUE THREAD

**Issue by vesel4ak** [ShadowMario/FNF-PsychEngine#11624]
### Describe your problem here.

How to change song's name?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Lorekeeper49** [comment]
As in in the middle of it?

**Comment by vesel4ak** [comment]
> As in in the middle of it?

no

**Comment by Drawoon2** [comment]
Change the variable `"song": "SongName",` from the json

**Comment by DisIsNOt** [comment]
In a song or what

**Comment by DisIsNOt** [comment]
Idk
setTextString('songTxt', 'hi')
