### ISSUE TITLE
Chart Editor glitched out and overwrote a completed chart with a blank chart

### ISSUE THREAD

**Issue by LaymooDR** [ShadowMario/FNF-PsychEngine#11628]
### Describe your bug here.

Json was reloaded, but it never did anything. The chart was then saved, accidentally overwriting the chart, with no way to recover it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, nothing was edited.

**Comment by LaymooDR** [comment]
Oh, and please do not be rude and say PC issue. That shows that you don't know what you are doing and you are just saying that to get a reaction. Post an actual serious reply. Thanks.

**Comment by Yuta12342** [comment]
Can you step me through everything you did before needing to reload the JSON?

**Comment by CaptainBaldi** [comment]
this seems like a "Clear Notes" moment

**Comment by LaymooDR** [comment]
> Can you step me through everything you did before needing to reload the JSON?

All that was done was a JSON reload. It never worked and was too late to notice. The button never worked. It was clicked, but it didn't do anything at the wrong time.

**Comment by LaymooDR** [comment]
> this seems like a "Clear Notes" moment

It most certainly isn't. I never mentioned "clear notes" on the post. If "clear notes" was involved, it would have said so. This is what I am talking about when I say that most of you don't take this seriously and neglect to read.

**Comment by Draconic-Hybrid** [comment]
Did you make the chart as a blank file beforehand, and then add things to it? Because that could be the issue. You've gotta click save and overwrite the previous file, otherwise the game will keep loading the blank file.

**Comment by Yuta12342** [comment]
> Did you make the chart as a blank file beforehand, and then add things to it? Because that could be the issue. You've gotta click save and overwrite the previous file, otherwise the game will keep loading the blank file.

It's either this, or a previous save of the file somehow failed, so the reload came with a blank file.

**Comment by LaymooDR** [comment]
No, a copy of another chart was used as the data to edit. It was then saved as a complete JSON when charting was finished, but the reload button didn't do anything, so it was too late to notice that it didn't work like it was supposed to. As far as I am concerned, the file saved correctly, as it had notes at the beginning section 0, like it was supposed to, during the last time it correctly reloaded.

> Did you make the chart as a blank file beforehand, and then add things to it? Because that could be the issue. You've gotta click save and overwrite the previous file, otherwise the game will keep loading the blank file.

**Comment by Draconic-Hybrid** [comment]
Check the file itself. Is its size 0 kb? If it is, then something went wrong. Not sure what, though.

**Comment by LaymooDR** [comment]
> Check the file itself. Is its size 0 kb? If it is, then something went wrong. Not sure what, though.

What went wrong was that the file was accidentally saved and overwritten, due to a chart editor bug that prevented the finished chart from loading. Why doesn't it seem like people read the title? They just enter these issue threads and post something random, expecting it to fix the issue.
