### ISSUE TITLE
horizontally scrolling story menu

### ISSUE THREAD

**Issue by nikkalotz** [ShadowMario/FNF-PsychEngine#11622]
### What is your question?

i wanna make the story mode weeks scroll left to right instead of up to down BUT i've been looking and i can't find the object that displays the "WEEK 1" images (the ones in images/storymenu). does anyone know where it is?

**Comment by EyadTheHedgehog** [comment]
that's something you want to play on the StoryMenuState.hx

if there is
upP
downP
change it to leftP and rightP

**Comment by Percossi283** [comment]
HeroEyad But Android It might work im doing VS Guy V2 Ok ON mobile I Use Github is Platform to compile It I use in Mobile
