### ISSUE TITLE
trouble with engine build

### ISSUE THREAD

**Issue by suskas** [ShadowMario/FNF-PsychEngine#11620]
### Describe your bug here.

hi.i am trying psych engine since it was 3 months since i used it.
i keep getting errors when building.
heres the error:
![Screenshot 2022-12-30 220726](https://user-images.githubusercontent.com/95119042/210111775-ff231202-19a9-472a-bcb5-9332002a16d2.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no.

**Comment by frantastic24** [comment]
Not a bug and duplicate of several issues
Revert to an older flixel or update Main.hx

**Comment by suskas** [comment]
how do i update main.hx?

**Comment by TheKitBoi** [comment]
> how do i update main.hx?

get it in here https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

**Comment by suskas** [comment]
thank you! I think its now fixed!
