### ISSUE TITLE
Crashes when I open story menu

### ISSUE THREAD

**Issue by JulianGeckoWasp** [ShadowMario/FNF-PsychEngine#11626]
### Describe your bug here.

Hello! Whenever I open the story menu, it crashes and gives me this error:
![D70C000A-FBA0-415A-AE29-382A62926098](https://user-images.githubusercontent.com/110136934/210152953-7ce47942-6ea6-4ceb-a2fb-68b2b462e6f6.jpeg)
Does anybody know how to solve this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I made all the weeks hidden from story and freeplay modes

**Comment by frantastic24** [comment]
Not a bug
There's a broken week json

**Comment by JulianGeckoWasp** [comment]
> Not a bug
> There's a broken week json

Thanks. I broke the week 3 json in the process of hiding the weeks. Now it works.
