### ISSUE TITLE
Character crashing da gaem

### ISSUE THREAD

**Issue by Heitor2864** [ShadowMario/FNF-PsychEngine#11627]
### Describe your bug here.

when i put my character's file name and click reload image it crashes instantly some how saying object not found but he's in mods folder in the exact section i saw how to add characters to the gaem

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i inserted my character and it's XML file

**Comment by frantastic24** [comment]
Not a bug
You messed up your files
Next time you get an error, post a screenshot because this is useless

**Comment by Heitor2864** [comment]
kay

**Comment by Heitor2864** [comment]
but how? The XML and PNG are named the same

**Comment by frantastic24** [comment]
You never posted the error so I can't help

**Comment by Heitor2864** [comment]
k

**Comment by Heitor2864** [comment]
gonna post it 01/01/2023
