### ISSUE TITLE
It's fairly stupid, but...

### ISSUE THREAD

**Issue by ChandelureF-5** [ShadowMario/FNF-PsychEngine#11621]
### What is your question?

How does one write camera shake directly to a characters json file?

It kinda feels like it could be possible but I don't know if it actually is.

**Comment by CrusherNotDrip** [comment]
you can attach a lua file to characters
it would be put in the same location as the json is in

**Comment by Kufferey** [comment]
Maybe this will work  

function onUpdate()
    if dadName == 'YOU CHARACTER NAME' then
        cameraShake('hud', 0.50, 0.1)
        cameraShake('hud', 0.50, 0.1)
    end
end

**Comment by Kufferey** [comment]
This might work

function onUpdate()
    if dadName == 'YOU CHARACTER NAME' then
        elseif opponentNoteHit() then
            cameraShake('hud', 0.50, 0.1)
            cameraShake('hud', 0.50, 0.1)
    end
end
