### ISSUE TITLE
Reload Audio Charting "bug"

### ISSUE THREAD

**Issue by Unholywanderer** [ShadowMario/FNF-PsychEngine#11629]
### Describe your bug here.

if you spam the shit out of "Reload Audio" in the chart menu, the voices will stack up causing masterpieces like this

https://user-images.githubusercontent.com/96925902/210158805-f0ac4736-c144-48bc-ae82-222413cdadb9.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I did not

**Comment by Yuta12342** [comment]
I think that's just a loading and sync issue. Pretty sure it should fix itself after loading into / out of the chart, or relaunching the game itself. That's kinda funny, tho.
