### ISSUE TITLE
Chart Editor Backup Function

### ISSUE THREAD

**Issue by 40U538072** [ShadowMario/FNF-PsychEngine#11630]
### What feature do you want to get added on the **base** engine?

Don't know if this is the right category to post this. I want instead of an autosave function, I want an automatic backup function. Instead of loading the recent save depending on if it did autosave or not, you can choose between a list of chart backups and load the selected one. I think this will make charting so much easier because the autosave function is bugged. Auto save didn't work and now my chart has been wiped and I have no way of recreating it or recovering it without errors.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by 40U538072** [comment]
Exactly brother. I wish it was automatic and we would have to accidently autosave through a blank chart or overwrite it. Instead, we could choose a list of backups. It would be so much better. That is what I am saying my friend.

**Comment by 40U538072** [comment]
I hate this engine.

**Comment by TheKitBoi** [comment]
then leave if your going to throw a rot in every issue

**Comment by 40U538072** [comment]
Then you leave and just try to be a bit nicer, okay?

**Comment by 40U538072** [comment]
> > > then leave if your going to throw a rot in every issue
> > 
> > 
> > I am going to have to reopen this now. Jerks like you just can't stop with this crap. Since the pc issue comment, you haven't changed from the last time I seen you.
> 
> oh and that guy actually works for vs steve (iirc)

Just had to look it up to be sure, and it is nor TheKitBoi. It's TheGaboDiaz that worked on it.
