### ISSUE TITLE
My week isn’t loading

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#11637]
### Describe your problem here.

The week is not loading properly. I am not sure why. the song doesn’t show in free play or story mode when I imported the weeks. Do I need to make a separate week file

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Yuta12342** [comment]
Can you send the Week File that you are using?

**Comment by NightmaresPlayz** [comment]
Maybe tomorrow I will

**Comment by 40U538072** [comment]
Psych Engine is crappywith bugs they won't solve. Don't mean to be harsh. Just a suggestion, but give up, I guess.

**Comment by Yuta12342** [comment]
> Psych Engine is crappy with bugs they won't solve. Don't mean to be harsh. Just a suggestion, but give up, I guess.

I personally wouldn't say that. These kinda issues are usually softcoded issues, that need to be dealt with on that side. 

It's hard to turn a fully hard-coded game into a easily moddable one.

**Comment by 40U538072** [comment]
> > Psych Engine is crappy with bugs they won't solve. Don't mean to be harsh. Just a suggestion, but give up, I guess.
> 
> I personally wouldn't say that. These kinda issues are usually softcoded issues, that need to be dealt with on that side.
> 
> It's hard to turn a fully hard-coded game into a easily moddable one.

Well, it is advertised as one. And pretty much all the issues I ever reported anyways never even got a single response anyways. So, what is the point in solving an issue when they don't even help you in the first place, and being really rude jerks?

**Comment by Yuta12342** [comment]
> > > Psych Engine is crappy with bugs they won't solve. Don't mean to be harsh. Just a suggestion, but give up, I guess.
> > 
> > 
> > I personally wouldn't say that. These kinda issues are usually softcoded issues, that need to be dealt with on that side.
> > It's hard to turn a fully hard-coded game into a easily moddable one.
> 
> Well, it is advertised as one. And pretty much all the issues I ever reported anyways never even got a single response anyways. So, what is the point in solving an issue when they don't even help you in the first place, and being really rude jerks?

Well, for one, Psych Engine is technically still in development and being improved, so they are constantly trying to solve problems.

And for two, they are constantly trying to make updates - as well as many others - to make it run better. Not everyone has time, or is always looking at the Issues page. 

Sure, it is a softcoded engine for the most part, but it doesn't mean that it's flawless. It's certainly better for me than any other engine, though.

**Comment by NightmaresPlayz** [comment]
Solved it!

**Comment by 40U538072** [comment]
> > > > Psych Engine is crappy with bugs they won't solve. Don't mean to be harsh. Just a suggestion, but give up, I guess.
> > > 
> > > 
> > > I personally wouldn't say that. These kinda issues are usually softcoded issues, that need to be dealt with on that side.
> > > It's hard to turn a fully hard-coded game into a easily moddable one.
> > 
> > 
> > Well, it is advertised as one. And pretty much all the issues I ever reported anyways never even got a single response anyways. So, what is the point in solving an issue when they don't even help you in the first place, and being really rude jerks?
> 
> Well, for one, Psych Engine is technically still in development and being improved, so they are constantly trying to solve problems.
> 
> And for two, they are constantly trying to make updates - as well as many others - to make it run better. Not everyone has time, or is always looking at the Issues page.
> 
> Sure, it is a softcoded engine for the most part, but it doesn't mean that it's flawless. It's certainly better for me than any other engine, though.

I would beg to differ. Mods folder refuses to load charts, characters, even the entire mod itself. Chart editor is broken and can wipe your chart clean at any moment. You won't be able to edit your character because it won't show up in the editor. I am surprised very few people are complaining about it.
