### ISSUE TITLE
loadSong() not working properly - Causes Crashes.

### ISSUE THREAD

**Issue by Yuta12342** [ShadowMario/FNF-PsychEngine#11635]
### Describe your bug here.

On newer versions of Psych Engine, I've tried to use loadSong() to go into a different song for a special thing I'm doing, which it seems to do fine, but a few seconds into the song, or sometimes just immediately depending on which song it switches to, it seems to suddenly crash. It seems to not be working right with events or something, but I can't fully tell.

The Crash Log is here: 
[PsychEngine_2022-12-31_19'01'41.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/10328976/PsychEngine_2022-12-31_19.01.41.txt)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Kufferey** [comment]
How are you loading it?

**Comment by Kufferey** [comment]
By Functions, KeyPressed that kind of thing/

**Comment by Kufferey** [comment]
Btw Copy and the code and send it in the chat thing.

**Comment by Yuta12342** [comment]
It's simply loaded automatically, like this:

`function onCreate()

loadSong('song', -1)

end

`

**Comment by Yuta12342** [comment]
It's not complicated, and even with other examples, it didn't seem to matter what function called loadSong. It just crashes either immediately, or during the song, after it had already switched to it.

**Comment by 40U538072** [comment]
It is just that Psych Engine is crappy and super buggy. Maybe stop with it and do something else. Not being mean. Just a suggestion. That's all.

**Comment by Kufferey** [comment]
Is it ok if i remodify your script?

**Comment by Kufferey** [comment]
Here i remodify ur script. Press spacebar to do it

```
function onUpdate()
    if keyJustPressed('space') then
        loadSong('YOUR SONG NAME')
    end
end
```

**Comment by Kufferey** [comment]
If you want a key on your keyboard to do it then
instead of keyJustPressed Do keyboardJustPressed('A-Z')

**Comment by Yuta12342** [comment]
I don't know how, but using a Key did change the outcome, and did something weird also in the process.

I have a setup where during a song, it suddenly ends with an event, and switches to a new one. I tested this by looping back to it from the song it usually changes to (from Story Mode), and for some reason, it ended up softlocking at the end point. I think I know why that is though, so that's fine.

The only issue is the point of my script being as it was, is because I need it to automatically switch, due to being a gimmick where one story mode song switches to something else in the case of certain results of the previous song, so figuring out why it crashes with an automatic setup is key in this particular instance.

**Comment by Yuta12342** [comment]
Actually, I believe I found what's causing the issue now. It might be something to do with a video being interrupted on transition, when I was testing things. Didn't think that could be the problem until now. I probably shoulda realized it when the "MP4Handler" was mentioned in the log.

**Comment by Noel3454565FNF** [comment]
> En fait, je crois que j’ai trouvé ce qui cause le problème maintenant. Cela pourrait être quelque chose à voir avec une vidéo interrompue lors de la transition, alors que je testais des choses. Je ne pensais pas que cela pourrait être le problème jusqu’à présent. J’aurais probablement dû m’en rendre compte lorsque le « MP4Handler » a été mentionné dans le journal.

do you find something or you steel need help?
