### ISSUE TITLE
My custom stage doesn't appear because the game can't find the assets (source)

### ISSUE THREAD

**Issue by IdiotLimitedEdition** [ShadowMario/FNF-PsychEngine#11639]
### Describe your problem here.

Ok so basically I decided to override the stage with source 
The code in question:
```hx
				var wall:BGSprite = new BGSprite('karlson/Wall', -59.15, -229.5, 0.9, 0.9);
				add(wall);

				var floor:BGSprite = new BGSprite('karlson/Floor', -147.4, 474.25, 0.9, 0.9);
				floor.setGraphicSize(Std.int(floor.width * 1.1));
				floor.updateHitbox();
				add(floor);
				if(!ClientPrefs.lowQuality) {
					var light:BGSprite = new BGSprite('karlson/light', 138, -735.15, 0.9, 0.9);
					light.setGraphicSize(Std.int(light.width * 1.1));
					light.updateHitbox();
					add(light);
				}
```
the json
```json
{
	"directory": "genericfolder",
	"defaultZoom": 1,
	"isPixelStage": false,

	"boyfriend": [908.7, 500.2],
	"girlfriend": [400, 130],
	"opponent": [-90.6, -192.3],
	"hide_girlfriend": false,

	"camera_boyfriend": [0, 0],
	"camera_opponent": [0, 0],
	"camera_girlfriend": [0, 0],
	"camera_speed": 1
}
```
But everytime I enter there's only the characters in a black void and the Haxeflixel logo (Ignore the fucked up icon)
![Screenshot (147)](https://user-images.githubusercontent.com/111077202/210248702-69be6b42-0942-4cc8-b83d-6836d69dc3ea.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Randomized main menu characters and RatingFC being saved

**Comment by 40U538072** [comment]
I am sorry but Psych Engine is such a crappy engine with bugs they won't fix. Try starting back from the beginning and redo everything. If you can't do that, then it is best if you give up. No hard feelings. I wish there was a better engine.

**Comment by IdiotLimitedEdition** [comment]
You didn't really help me but ok

**Comment by imdumlol** [comment]
> I am sorry but Psych Engine is such a crappy engine with bugs they won't fix. Try starting back from the beginning and redo everything. If you can't do that, then it is best if you give up. No hard feelings. I wish there was a better engine.

bro shut yo goofy ass up i bet you could not do better

**Comment by TheKitBoi** [comment]
> I am sorry but Psych Engine is such a crappy engine with bugs they won't fix. Try starting back from the beginning and redo everything. If you can't do that, then it is best if you give up. No hard feelings. I wish there was a better engine.

Imagine losing your shit over an error you can’t fix on your own issue

**Comment by Yuta12342** [comment]
> I am sorry but Psych Engine is such a crappy engine with bugs they won't fix. Try starting back from the beginning and redo everything. If you can't do that, then it is best if you give up. No hard feelings. I wish there was a better engine.

What's your problem? Jeez.

**Comment by Yuta12342** [comment]
Also, I dunno how Psych works with Source Code Stages, but it's usually recommended to avoid them, I'm pretty sure.

**Comment by 40U538072** [comment]
> > I am sorry but Psych Engine is such a crappy engine with bugs they won't fix. Try starting back from the beginning and redo everything. If you can't do that, then it is best if you give up. No hard feelings. I wish there was a better engine.
> 
> What's your problem? Jeez.

Psych Engine, that is my problem. I can't catch a break.

**Comment by 40U538072** [comment]
> > I am sorry but Psych Engine is such a crappy engine with bugs they won't fix. Try starting back from the beginning and redo everything. If you can't do that, then it is best if you give up. No hard feelings. I wish there was a better engine.
> 
> Imagine losing your shit over an error you can’t fix on your own issue

Maybe if people like you would have taken things more seriously, I probably wouldn't have this problem.

**Comment by 40U538072** [comment]
> > I am sorry but Psych Engine is such a crappy engine with bugs they won't fix. Try starting back from the beginning and redo everything. If you can't do that, then it is best if you give up. No hard feelings. I wish there was a better engine.
> 
> bro shut yo goofy ass up i bet you could not do better

This is a great example of how much every single one of you are being jerks. I literally hate you all.

**Comment by IdiotLimitedEdition** [comment]
Uuh... So can someone help me?

**Comment by 40U538072** [comment]
> Uuh... So can someone help me?

Honestly, I would say making a stage with the mods folder or lua coding is way easier because I never learned how to use source code. Stage has a chance of bugging out because of how that work though.

**Comment by DabbinDude316B** [comment]
> > Uuh... So can someone help me?
> 
> Honestly, I would say making a stage with the mods folder or lua coding is way easier because I never learned how to use source code. Stage has a chance of bugging out because of how that works though.

Uhh source coder here!

Did you add your case?

Maybe the image is too far offscreen?

I recommend using lua then inputing into source-

so ya don’t have to recompile for moving it 10 x.

**Comment by IdiotLimitedEdition** [comment]
> > > Uuh... So can someone help me?
> > 
> > 
> > Honestly, I would say making a stage with the mods folder or lua coding is way easier because I never learned how to use source code. Stage has a chance of bugging out because of how that works though.
> 
> Uhh source coder here!
> 
> Did you add your case?
> 
> Maybe the image is too far offscreen?
> 
> I recommend using lua then inputing into source-
> 
> so ya don’t have to recompile for moving it 10 x.
> 
> Also, try not to do a folder. It sometimes doesn’t work, so stick with none.

1. My stage is an overwrite of the week 1 stage
2. I  should have specified that the game isn't able to find the images It's says` source/Paths.hx:362: oh no its returning null NOOOO` in the command  prompt
So I'm sure the reason the images don't load is because it can't find them somehow???

**Comment by 40U538072** [comment]
> > > Uuh... So can someone help me?
> > 
> > 
> > Honestly, I would say making a stage with the mods folder or lua coding is way easier because I never learned how to use source code. Stage has a chance of bugging out because of how that works though.
> 
> Uhh source coder here!
> 
> Did you add your case?
> 
> Maybe the image is too far offscreen?
> 
> I recommend using lua then inputing into source-
> 
> so ya don’t have to recompile for moving it 10 x.
> 
> Also, try not to do a folder. It sometimes doesn’t work, so stick with none.

Agreed. Compared to source coding, using lua coding is easier and less complicated.

**Comment by Eventretta** [comment]
> I am sorry but Psych Engine is such a crappy engine with bugs they won't fix. Try starting back from the beginning and redo everything. If you can't do that, then it is best if you give up. No hard feelings. I wish there was a better engine.

goofy ahhh comment moment

**Comment by ArdoDev-stupid** [comment]
> I am sorry but Psych Engine is such a crappy engine with bugs they won't fix. Try starting back from the beginning and redo everything. If you can't do that, then it is best if you give up. No hard feelings. I wish there was a better engine.

the better engines are:
Codename Engine and also Yoshi Engine

**Comment by 40U538072** [comment]
> > I am sorry but Psych Engine is such a crappy engine with bugs they won't fix. Try starting back from the beginning and redo everything. If you can't do that, then it is best if you give up. No hard feelings. I wish there was a better engine.
> 
> the better engines are: Codename Engine and also Yoshi Engine

Can you explain what makes them better? Never heard of Codename Engine but have heard of Yoshi Engine. Don't know what makes them better though.

**Comment by ArdoDev-stupid** [comment]
> > > I am sorry but Psych Engine is such a crappy engine with bugs they won't fix. Try starting back from the beginning and redo everything. If you can't do that, then it is best if you give up. No hard feelings. I wish there was a better engine.
> > 
> > the better engines are: Codename Engine and also Yoshi Engine
> 
> Can you explain what makes them better? Never heard of Codename Engine but have heard of Yoshi Engine. Don't know what makes them better though.

Hscript support instead of lua. So you can basically do anything and more than lua and Codename is created by the creator of yoshi engine

**Comment by IdiotLimitedEdition** [comment]
I made this issue to get help not to see the fnf modding equivalent of some people arguing over arguing about which political side is better

**Comment by ShadowMilky** [comment]
> I am sorry but Psych Engine is such a crappy engine with bugs they won't fix. Try starting back from the beginning and redo everything. If you can't do that, then it is best if you give up. No hard feelings. I wish there was a better engine.

![7671up](https://user-images.githubusercontent.com/62410083/212522304-ef6c5237-db0f-4daf-96c5-ccdbf3d85cb8.gif)

**Comment by Robert124l** [comment]
> I made this issue to get help not to see the fnf modding equivalent of some people arguing over arguing about which political side is better

It's the most random issue I've ever seen XD,
