### ISSUE TITLE
What is an animation indice?????

### ISSUE THREAD

**Issue by ColdlordXRepositories** [ShadowMario/FNF-PsychEngine#11642]
### What needs to be documented?

Its advanced, but it may fix a problem i have now.

**Comment by frantastic24** [comment]
Google
https://gamebanana.com/questions/30758

**Comment by Jarachyreal1400** [comment]
i do believe its a certain frame to use for like the idle if your character dances left then dances right and you want that to sync with the BPM you can split the idle animation by two parts by putting what frames are in this part of the animation
