### ISSUE TITLE
Hi! I idk wat need type. Just say me, what its?

### ISSUE THREAD

**Issue by lesnovartem** [ShadowMario/FNF-PsychEngine#11644]
### What needs to be documented?

![image](https://user-images.githubusercontent.com/82836511/210414784-49c89029-48db-420a-97d0-ae5c45c77a94.png)

**Comment by TheKitBoi** [comment]
Replace Main.hx with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

**Comment by alex-codes-stuff** [comment]
for me it worked by just downloading a older flixel addons version
