### ISSUE TITLE
Icons fnf are flixel icons

### ISSUE THREAD

**Issue by Danya20072019** [ShadowMario/FNF-PsychEngine#11648]
### Describe your bug here.

I ran into a problem that putting any game icon on the flixel made the flixel icon.
the resolution is the same
example on screenshots
![image](https://user-images.githubusercontent.com/97068888/210465403-e6490dac-20ca-40d4-9d72-8b189cfa614a.png)
![image](https://user-images.githubusercontent.com/97068888/210465434-e6350605-8c05-4887-8a90-24cd9ac68f77.png)
![image](https://user-images.githubusercontent.com/97068888/210465445-b86874f9-b70f-4d72-89f8-39d9db78834a.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i compile all flixel/haxe games and this flixel icon has been replace my icons

**Comment by Yuta12342** [comment]
To me, it seems that the icon is either unspecified or invalid in the code for some reason.

**Comment by Yuta12342** [comment]
Either that, or your compiler is doing something.

**Comment by dombomb64** [comment]
I’ve also had issues with the icon, except that my custom 16x16 icon that’s different from the others doesn’t replace the normal one at the top of the window or even in the icon file itself, according to an online icon editor I found.

**Comment by EyeDaleHim** [comment]
OpenFL/Lime has issues with the icons, not sure if there's a fix. But this is related to the recent versions though.

No I won't answer your questions, I'm only pinpointing the fact.

**Comment by Danya20072019** [comment]
I fixed it! The first thing is to make the permission of the icons under all possible ones (I don't know if this is mandatory or not), and the second is to remove the spaces in the file name. After that everything worked!

**Comment by dombomb64** [comment]
> The first thing is to make the permission of the icons under all possible ones (I don't know if this is mandatory or not),

What do you mean by that first step? Can you send your changes, please?

> and the second is to remove the spaces in the file name.

Do you mean the exe file or the folder with the project name?

**Comment by Danya20072019** [comment]
> 

![image](https://user-images.githubusercontent.com/97068888/218217113-b7770c26-2e3e-401c-9fef-897d9c6c0d00.png)
i try this
![image](https://user-images.githubusercontent.com/97068888/218217251-05233834-d1d1-4670-a1c5-9b6ddb3d7820.png)
i mean exe
