### ISSUE TITLE
How can you access an object made in HScript, in another instance of HScript?

### ISSUE THREAD

**Issue by CaptainBaldi** [ShadowMario/FNF-PsychEngine#11647]
### What is your question?

So I've made a FlxButton using runHaxeCode(), 
![image](https://user-images.githubusercontent.com/86160807/210446541-60fc8832-72d5-44de-ba72-4901fc25d663.png)
and I'm trying to access it in another instance so I can destroy said FlxButton.

Trying to destroy the button in another instance of HScript does not seem to work, and I'm not sure how I can get it working.

**Comment by Drawoon2** [comment]
Use the functions `setVar(tag,var)` and in the other runHaxeCode() use `getVar(tag)` I use it in a code for multiple characters
PD:that gave you the reference in lua

**Comment by CaptainBaldi** [comment]
> Use the functions `setVar(tag,var)` and in the other runHaxeCode() use `getVar(tag)` I use it in a code for multiple characters PD:that gave you the reference in lua

can you show an example of what you did cause ive tried this before and i couldnt get it working

**Comment by Drawoon2** [comment]
> 

`    runHaxeCode([[
        var Dad2:Character;
        Dad2 = new Character(500,600,'pico');
        game.add(Dad2);
        Dad2.dance();
        setVar('DAD3',Dad2);
    ]])
    runHaxeCode([[
        getVar('DAD3').holdTimer=0;
        getVar('DAD3').playAnim('singUP',true);
    ]])`

**Comment by CaptainBaldi** [comment]
> > 
> 
> ` runHaxeCode([[ var Dad2:Character; Dad2 = new Character(500,600,'pico'); game.add(Dad2); Dad2.dance(); setVar('DAD3',Dad2); ]]) runHaxeCode([[ getVar('DAD3').holdTimer=0; getVar('DAD3').playAnim('singUP',true); ]])`

thank you so much ive been wondering how to do this forever
