### ISSUE TITLE
Ok so

### ISSUE THREAD

**Issue by Luciano686** [ShadowMario/FNF-PsychEngine#11646]
### Describe your problem here.

Ok so, does anyone know how to make that like when you lose, a random sound plays?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Zer0PXL** [comment]
function onGameOver()
     playSound(sound:String, volume:Float = 1, ?tag:String)
end

**Comment by Draconic-Hybrid** [comment]
Do you want it to be in conjunction with the default death sound or do you want to replace the death sound entirely?

**Comment by Luciano686** [comment]
> function onGameOver() playSound(sound 1, tag) end
> 
> Replace sound with where the sound is placed in the files and tag with a name for the sound (it's just used for pausing the sound so it doesn't really matter).

Yes i know that, but what i want to do is that when you die, a random sound appears

**Comment by Luciano686** [comment]
> Do you want it to be in conjunction with the default death sound or do you want to replace the death sound entirely?

No, i dont want to replace the death sound, i want to play a random sound when you die

**Comment by Zer0PXL** [comment]
local myTable = { 'sounda', 'soundb', 'soundc', 'soundd' }

function onGameOver()
playSound( myTable[ math.random( 0, #myTable - 1 ) ], 1, tag )
end

Didn't test so idk if it works

**Comment by Luciano686** [comment]
> local myTable = { 'sounda', 'soundb', 'soundc', 'soundd' }
> 
> function onGameOver() playSound( myTable[ math.random( 0, #myTable - 1 ) ], 1, tag ) end
> 
> Didn't test so idk if it works

do i change the tag on the function thing?

**Comment by Drawoon2** [comment]
`local myTable = { 'sounda', 'soundb', 'soundc', 'soundd' }
setPropertyFromClass('GameOverSubstate','deathSoundName',myTable[getRandomInt(1,#myTable)])`

**Comment by Luciano686** [comment]
> setPropertyFromClass('GameOverSubstate','deathSoundName',myTable[getRandomInt(1,#myTable)])

do i have to put that on the function game over?

**Comment by Drawoon2** [comment]
> > setPropertyFromClass('GameOverSubstate','deathSoundName',myTable[getRandomInt(1,#myTable)])
> 
> do i have to put that on the function game over?

You can use in all the functions of preference I recommend put it in onCreate()

**Comment by Luciano686** [comment]
> > > setPropertyFromClass('GameOverSubstate','deathSoundName',myTable[getRandomInt(1,#myTable)])
> > 
> > 
> > do i have to put that on the function game over?
> 
> You can use in all the functions of preference I recommend put it in onCreate()

ok ill try it out
