### ISSUE TITLE
Stage too small

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#11641]
### Describe your problem here.

The stage is smaller than the characters and the view does not fit them all

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Yuta12342** [comment]
There's multiple reasons why this could happen, depending on how you have objects set up:

- Object LUA Scaling (The LUA scales the object to be smaller than normal.)
- Image Size (The Image itself is small.)

You should probably check how your LUA handles creating the objects compared to other LUA Stages, or check if the image itself is smaller than you expect it to be.

**Comment by Yuta12342** [comment]
You should possibly also show the code for the LUA Stage, and a Screenshot to make it easier, if this doesn't help.

**Comment by NightmaresPlayz** [comment]
Maybe it is the stage image size because when I changed them to size of the original stage, it worked but I still couldn’t change the characters scale (is there a way though?)

**Comment by TheKitBoi** [comment]
close this issue

**Comment by NightmaresPlayz** [comment]
How do I 😕
