### ISSUE TITLE
If there is an image in front of the chrs like in ddto bad ending where there are tables in front of bf and sayori, how do I get rid of them when the stage changes

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#11649]
### Describe your problem here.

Yeah, just read question, you will get it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Layering doesn't matter, it works like any other object

**Comment by Ratio-Combinder** [comment]
removeLuaSprite('tag' true)
