### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by DevArtiom** [ShadowMario/FNF-PsychEngine#11643]
### Describe your problem here.

I want to know how to align weeks in a specific order.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

**Comment by TheKitBoi** [comment]
weeklist.txt
Check assets/data and do it for mods/‘yourmod’/data

**Comment by DevArtiom** [comment]
I forgot that week list exists
