### ISSUE TITLE
onPixelBG option help

### ISSUE THREAD

**Issue by GatoMorado621** [ShadowMario/FNF-PsychEngine#11655]
### Describe your problem here.

I am trying to do that the image a put in the character editor (a character) be another image (pixelated) when I change the background to the senpai stage. And I tried a lot of times with `if(onPixelBG)` but it dosen't work. If you can help how to make this I would really appreciate it.

- NOTE: The image thing is a character.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I did but I errase it.

**Comment by CaptainBaldi** [comment]
`onPixelBG` is not a variable, it's `isPixelStage`

**Comment by GatoMorado621** [comment]
> `onPixelBG` is not a variable, it's `isPixelStage`

I know. That's why I want that when I change to the pixel stage, the image change to the image pixelated

**Comment by ArdoDev-stupid** [comment]
you can't make the character image pixelated, you have edit it
