### ISSUE TITLE
Note trail don't appear in-game

### ISSUE THREAD

**Issue by Bababea** [ShadowMario/FNF-PsychEngine#11657]
### Describe your bug here.

Idk if it's only a visual bug, but when I chart, close the game and reopen, all the note's trails diminish by 1 square in 16th beat snap.
In chart editor:
![image](https://user-images.githubusercontent.com/106120001/210680765-6cd302e7-793d-49f2-96f9-8d769cf77bf2.png)

In-game:
![image](https://user-images.githubusercontent.com/106120001/210680802-d5dd0599-43ae-40d7-855e-ce3a8292eed8.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't edit anything in this build.

**Comment by Draconic-Hybrid** [comment]
The length of a sustain depends on a couple of things, from what I've seen
1) The note speed. If the note speed is low, sustains tend to be very hidden.
2) Your zoom in the editor in conjunction with the sustain time. Say your sustain time was large enough to fit one box, as you have shown, but your zoom is 1/16. That likely won't show up in-game.

Mind showing me the whole editor screenshot?

**Comment by Bababea** [comment]
> The length of a sustain depends on a couple of things, from what I've seen
> 
> 1. The note speed. If the note speed is low, sustains tend to be very hidden.
> 2. Your zoom in the editor in conjunction with the sustain time. Say your sustain time was large enough to fit one box, as you have shown, but your zoom is 1/16. That likely won't show up in-game.
> 
> Mind showing me the whole editor screenshot? I might be able to get a better sense of the issue. Important tabs are the Event and Song tabs



> The length of a sustain depends on a couple of things, from what I've seen
> 
> 1. The note speed. If the note speed is low, sustains tend to be very hidden.
> 2. Your zoom in the editor in conjunction with the sustain time. Say your sustain time was large enough to fit one box, as you have shown, but your zoom is 1/16. That likely won't show up in-game.
> 
> Mind showing me the whole editor screenshot? I might be able to get a better sense of the issue. Important tabs are the Event and Song tabs

1. Song speed in this song is 3.0, so I don't think that the speed is the problem here.
2. U might be right
![image](https://user-images.githubusercontent.com/106120001/210771871-13c3234b-293a-4b06-8563-0ea5ce397ab4.png)
![image](https://user-images.githubusercontent.com/106120001/210771893-b08c5333-274a-45d6-9772-45ccb0fdca85.png)
Here's.

**Comment by Draconic-Hybrid** [comment]
Doesn't look like there's a problem here in the editor. Sorry I couldn't be of much help.
