### ISSUE TITLE
Scrolling Background by Lua

### ISSUE THREAD

**Issue by NavaGaming** [ShadowMario/FNF-PsychEngine#11658]
### Describe your problem here.

Is there a way to make scrolling background(Like Danger and Nightmare Run stuff) using Lua?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by NavaGaming** [comment]
![fgPlatform](https://user-images.githubusercontent.com/105751462/210712103-7e326f99-5284-4575-afb2-7a05206fcbc5.png)
This thingie

**Comment by alex-codes-stuff** [comment]
you could do it using runhaxecode() as i think its easier in haxe but idk how to make it in lua, ill update you if i figure out how

**Comment by Draconic-Hybrid** [comment]
You could either have an animated background or use a Tween.

If you know how to make animated sprites in Lua, then just do that for the background.

For tweens, you'll first have to remove the `close()` in your stage script. Then, align the image correctly and have a forever-looping tween, which looks something like this.

```lua
function onCreate()
	makeLuaSprite('bg', 'background', 0, 0);
	setScrollFactor('bg', 1, 1);

	addLuaSprite('bg', false);
    doTweenX('bgMove', 'bgClouds', -4500, 3, 'linear')
end


function onTweenCompleted(tag)
	if tag == 'bgReset' then
		setProperty('bgClouds.visible', false)
		doTweenX('bgMove', 'bg', 1500, 1, 'linear')
	end
	if tag == 'bgMove' then
		setProperty('bgClouds.visible', true)
		doTweenX('bgReset', 'bg', -4500, 15, 'linear')
	end
end
```

You can tinker with the code to your needs, such as the name of the image, how far you need the image to move, how fast you want it to move, etc.

**Comment by NavaGaming** [comment]
> You could either have an animated background or use a Tween.
> 
> If you know how to make animated sprites in Lua, then just do that for the background.
> 
> For tweens, you'll first have to remove the `close()` in your stage script. Then, align the image correctly and have a forever-looping tween, which looks something like this.
> 
> ```lua
> function onCreate()
> 	makeLuaSprite('bg', 'background', 0, 0);
> 	setScrollFactor('bg', 1, 1);
> 
> 	addLuaSprite('bg', false);
>         doTweenX('bgMove', 'bgClouds', -4500, 3, 'linear')
> end
> 
> 
> function onTweenCompleted(tag)
> 	if tag == 'bgReset' then
> 		setProperty('bgClouds.visible', false)
> 		doTweenX('bgMove', 'bg', 1500, 1, 'linear')
> 	end
> 	if tag == 'bgMove' then
> 		setProperty('bgClouds.visible', true)
> 		doTweenX('bgReset', 'bg', -4500, 15, 'linear')
> 	end
> end
> ```
> 
> You can tinker with the code to your needs, such as the name of the image, how far you need the image to move, how fast you want it to move, etc.

Thanks!

**Comment by Draconic-Hybrid** [comment]
If you want it to be truly seamless, it might work to have two of the same sprite scrolling with the same method I just method, and then when the first one gets off-screen, reset it, etc. etc.

**Comment by NavaGaming** [comment]
> If you want it to be truly seamless, it might work to have two of the same sprite scrolling with the same method I just method, and then when the first one gets off-screen, reset it, etc. etc.

Tried to do so, but i suck at codding, that's it lmao

**Comment by NavaGaming** [comment]
Still does stop moving after first tweening, for some reason

**Comment by NavaGaming** [comment]
oh, nvm!
i messed up with other code and it worked perfectly!
