### ISSUE TITLE
 X location of the notes in middlescroll

### ISSUE THREAD

**Issue by Fronekowy** [ShadowMario/FNF-PsychEngine#11653]
### What is your question?

Someone knows the X location of the notes in middlescroll. I was doing a song with forced middlescroll and I wanted the add that the notes moved to the middlescroll location but idk where it is.

**Comment by Draconic-Hybrid** [comment]
412 - Left
524 - Down
636 - Up
748 - Right

**Comment by Fronekowy** [comment]
Thanks
