### ISSUE TITLE
How to change stage in song?

### ISSUE THREAD

**Issue by ItzEpicstickman** [ShadowMario/FNF-PsychEngine#1165]
### What needs to be documented?

I really want to know how to change stage while in song
like an event for it
please help
if anybody knows please tell

**Comment by ShadowMario** [comment]
This was answered multiple times:

Spawn stage 1 and stage 2 sprites
Hide stage 2 sprites
When you want to use stage 2, hide stage 1 sprites and show stage 2 sprites.
