### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by hotpocketsarepoggers** [ShadowMario/FNF-PsychEngine#11654]
### Describe your problem here.

Im trying to compile version 0.6.3 but i keep getting this error

source/Main.hx:78: characters 61-65 : Float should be Int
source/Main.hx:78: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:78: characters 61-65 : ... For function argument 'child'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMilky** [comment]
update flixel to 5.0.0

**Comment by hotpocketsarepoggers** [comment]
> update flixel to 5.1.0

Its already on 5.1.0

**Comment by nennneko5787** [comment]
Replace Main.hx with the latest version
https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

**Comment by ShadowMilky** [comment]
> > update flixel to 5.1.0
> 
> Its already on 5.1.0

ok... but are you using the 0.6.3 build from the releases tab
or the latest build commit

**Comment by alex-codes-stuff** [comment]
> Replace Main.hx with the latest version https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx
either do this or install flixel addons 2.1 idk it worked for me
