### ISSUE TITLE
Psych engine 0.4.2 error

### ISSUE THREAD

**Issue by Montymations** [ShadowMario/FNF-PsychEngine#11656]
### Describe your problem here.

I have been modding on a version of 0.4.2 for a while now. And just now suddenly it gave me three errors.
source/Main.hx:73: characters 61-65 : Float should be Int
source/Main.hx:73: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:73: characters 61-65 : ... For function argument 'child'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i haven't modified anything past adding songs and charts

**Comment by 40U538072** [comment]
Your version of Psych Engine is outdated. If you have not already, please download version 0.6.3. It fixes and patches whatever bugs were in this version.

**Comment by ShadowMilky** [comment]
or... just change the main.hx file to the latest version

**Comment by 40U538072** [comment]
> or... just change the main.hx file to the latest version
That could work too.
