### ISSUE TITLE
very used tutorial videos missing?

### ISSUE THREAD

**Issue by alex-codes-stuff** [ShadowMario/FNF-PsychEngine#11650]
### Describe your problem here.

so some time ago i remembered seeing these useful source code tutorials by some guy that showed cool things like a title screen with a scrolling bg, main menu with scrolling semi-transparent bg and more, but for some reason i cant find ANY of the videos anymore.

ive noticed that a lot of other mods like strident crisis used some of the scripts from that guy.

anyone have info on him? i remembered he sounded kinda indian and his pfp had a light blue bg

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by RubenDatOneBoi3446** [comment]
EIT's videos yah, i think he deleted his stuff

**Comment by RubenDatOneBoi3446** [comment]
heres the link to the stuff he did

**Comment by alex-codes-stuff** [comment]
OH MY GOD THANK YOU!!!!!!!

**Comment by alex-codes-stuff** [comment]
![image](https://user-images.githubusercontent.com/104297510/210771318-4ae5e929-fb84-4fe1-acfd-11b740063d01.png)
i was wondering if someone had a archove of his videos or something as i have nearly no clue how to use the code from thr github page. i linked a screenshot of his channel just in case il make it more hepful.

**Comment by RubenDatOneBoi3446** [comment]
not that i think so

**Comment by RubenDatOneBoi3446** [comment]
i think you should probably just close this now
