### ISSUE TITLE
Source bg

### ISSUE THREAD

**Issue by RubenDatOneBoi3446** [ShadowMario/FNF-PsychEngine#11669]
### Describe your problem here.

How do i make a background with source?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by DisIsNOt** [comment]
find switch(curStage) at PlayState

**Comment by RubenDatOneBoi3446** [comment]
alr thx
