### ISSUE TITLE
Bot Play not appearing

### ISSUE THREAD

**Issue by Bolinho905** [ShadowMario/FNF-PsychEngine#11666]
### Describe your problem here.

Good morning, I downloaded the PsychEngine-Windows64.zip version 0.6.3
I am not finding the section to activate the bot play.
I can't find it in the game options on the start screen or during gameplay. 
Is there a specific command or another way to activate it?
Thanks for your attention. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by nennneko5787** [comment]
Press Ctrl key in Free Play menu or Story Mode menu

**Comment by Bolinho905** [comment]
> Pressione a tecla Ctrl no menu Free Play ou no menu Story Mode

It worked, thanks for the help.

**Comment by ShadowMilky** [comment]
> > Pressione a tecla Ctrl no menu Free Play ou no menu Story Mode
> 
> It worked, thanks for the help.

you didnt notice the close issue button
click it for god's sake

**Comment by ArdoDev-stupid** [comment]
CLOSE THE FUCKING ISSUE
