### ISSUE TITLE
dialogue script only working for one week

### ISSUE THREAD

**Issue by prockscac** [ShadowMario/FNF-PsychEngine#11667]
### Describe your bug here.

I put the dialogue script in every song in the data folder, and its only working for one week, every time I restart the game and click a week that weeks dialogue works and the others don't, not even the week 6 dialogue works.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by eAntivisurus** [comment]
even of putting in data put it in scripts floder so u can put it in every song

**Comment by prockscac** [comment]
> even of putting in data put it in scripts floder so u can put it in every song
I tried it and that doesn't work either

**Comment by eAntivisurus** [comment]
> > even of putting in data put it in scripts floder so u can put it in every song
> > I tried it and that doesn't work either

what version of pysch engine are u using?
is it in source code is it (no source code)
and send that lua
