### ISSUE TITLE
No object reference

### ISSUE THREAD

**Issue by Nateces** [ShadowMario/FNF-PsychEngine#11662]
### Describe your bug here.

 Everytime I try charting and then play the chart I've created it always pop-ups this error ;
[Crash_sight.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/10354317/Crash_sight.txt)
 I don't have any idea what went wrong in the files that bumped this one out. Any ideas/suggestions on how could I fix this?
Anything related to the source code?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yea, I tried adding a new strumline

**Comment by Yuta12342** [comment]
It seems that something is wrong with your Noteskin.

Is your chart trying to specify one?

It seems to be related to the code in StrumNote.hx that refers to Pixel Stages.

**Comment by Nateces** [comment]
so it is about the noteskins
