### ISSUE TITLE
"Endless" Scrolling Floor(Stage) for Lua

### ISSUE THREAD

**Issue by NavaGaming** [ShadowMario/FNF-PsychEngine#11665]
### Describe your problem here.

Yea, already second request for help, cuz i have no idea how to make it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by NavaGaming** [comment]
the previous thing not really looks like working

**Comment by Draconic-Hybrid** [comment]
Well, did you edit the tag names/image name? When I posted the code previously, it actually had a few mistakes that I only noticed recently

**Comment by NavaGaming** [comment]
> Well, did you edit the tag names/image name? When I posted the code previously, it actually had a few mistakes that I only noticed recently
 i did changed image name only, that's it, i tried to make code work, but i just suck at codding

**Comment by Draconic-Hybrid** [comment]
Go back to the thing I posted previously. I messed up a bit of the code, so I edited the thing a bit

**Comment by NavaGaming** [comment]
> Go back to the thing I posted previously. I messed up a bit of the code, so I edited the message a bit

k
