### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by Fronekowy** [ShadowMario/FNF-PsychEngine#11663]
### Describe your problem here.

I was coding defeat and a custom hud at the same time until I ran into a problem. The custom hud and defeat code was crashing the game and I don't know why.
Custom HUD (In Progress)
`local oppscore = 0

function onCreate()
--sets up everything so it can display score and forces upscroll
  makeLuaText('scorep', 'PLAYER', 0, 1250, 650);
  makeLuaText('scoreopp', 'ENEMY', 0, 100, 650);
  setTextSize('scorep', 50);
  setTextSize('scoreopp', 50);
  addLuaText('scorep');
  addLuaText('scoreopp');
  setProperty('downscroll', false)
end

function onSongStart()
--Forces MiddleScroll
  noteTweenX(1, 4, 524, 1)
  noteTweenX(2, 5, 636, 1)
  noteTweenX(3, 6, 748, 1)
  noteTweenX(4, 7, 860, 1)
end`
Defeat
`function onUpdate()
  setProperty('health', 1)
end

function onSongStart()
  noteTweenAlpha('fade1', 0, 0, 1)
  noteTweenAlpha('fade2', 1, 0, 1)
  noteTweenAlpha('fade3', 2, 0, 1)
  noteTweenAlpha('fade4', 3, 0, 1)
end
function onCreate()
  if hideTime == true then
    setProperty('hideTime', false);
  end
  if downscroll == true then
    setProperty('downscroll', false);
  end
end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No x-x

**Comment by Yuta12342** [comment]
I can't entirely tell, but I'm not sure if it's the best practice to call the same function multiple times, as different functions.

Not sure if that's the cause or not, though.

**Comment by Fronekowy** [comment]
> I can't entirely tell, but I'm not sure if it's the best practice to call the same function multiple times, as different functions.
> 
> Not sure if that's the cause or not, though.

I don't think so

**Comment by Fronekowy** [comment]
> I can't entirely tell, but I'm not sure if it's the best practice to call the same function multiple times, as different functions.
> 
> Not sure if that's the cause or not, though.

I think I found the problem

**Comment by Fronekowy** [comment]
> > I can't entirely tell, but I'm not sure if it's the best practice to call the same function multiple times, as different functions.
> > 
> > Not sure if that's the cause or not, though.
> 
> I think I found the problem

Fixed the crashing but nor the HUD Is hidden nor the arrows are forced to upscroll
