### ISSUE TITLE
How to get the coordinate value of the notes?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#1166]
### What is your question?

How to get the coordinate value of the notes in area 1 and area 2 with lua script?
![Snipaste_2021-11-19_17-52-31](https://user-images.githubusercontent.com/13177997/142603423-dba4ed87-cb7f-41fd-b265-3632056b1afe.png)

**Comment by MayoALT** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Variables

**Comment by zwl1619** [comment]
@MayoALT Which functions? I don't find them.

**Comment by MayoALT** [comment]
look for the strum/receptor area

**Comment by ShadowMario** [comment]
```lua
getProperyFromGroup('playerStrums', 0, 'x') --Get X position of arrow 0 from player (Left)
getProperyFromGroup('opponentStrums', 2, 'y') --Get Y position of arrow 2 from opponent (Up)

getProperyFromGroup('notes', 0, 'y') --Get Y position of spawned note 0
-- The spawned note ID is not relative from spawn or charted order!!! It's based on which note is more up (or more down if you're on Downscroll)
```
