### ISSUE TITLE
How do i fucking fix this

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#11664]
### What is your question?

<img width="857" alt="image" src="https://user-images.githubusercontent.com/102251392/210895181-a47f4ac9-f4ac-42ad-9eb7-9cd175d1bf81.png">

PLEASE help meh

**Comment by TheKitBoi** [comment]
haxelib install hxCodec

**Comment by EgguMan** [comment]
Install hxCodec

**Comment by hayfii** [comment]
not sure why u have to curse

**Comment by CrusherNotDrip** [comment]
> not sure why u have to curse

he minus well shoulda said
How the fuck do I fucking fix this fucking shit

**Comment by EgguMan** [comment]
> not sure why u have to curse

Shut the fuck up nerd

**Comment by ArdoDev-stupid** [comment]
CLOSE THIS ALREADY YOU CUNT
