### ISSUE TITLE
add this api to the wiki please PELAE PLE-

### ISSUE THREAD

**Issue by alex-codes-stuff** [ShadowMario/FNF-PsychEngine#11660]
### What needs to be documented?

https://gamebanana.com/tuts/15333
please add this or i will kill a family

**Comment by CaptainBaldi** [comment]
the official wiki isn't really updated anymore, you can use [mine](https://github.com/CaptainBaldi/PsychRewrittenWiki/wiki) instead, it has most of the things from the page you linked

**Comment by EgguMan** [comment]
Just look on FunkinLua.hx or bookmark that lmao
