### ISSUE TITLE
Error when installing haxelib

### ISSUE THREAD

**Issue by PhoenixRise06** [ShadowMario/FNF-PsychEngine#11679]
### Describe your problem here.

basically after using the "haxelib run hmm install" command in cmd it returns:

"Validation error: hmm.json not found in current working directory
Use "hmm help" to see usage"

Using "hmm help" command returns:

"The "hmm" command is either misspelled or
could not be found."

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
You run the command from the source root folder, same as you would when compiling
