### ISSUE TITLE
False Credit for VSCode Lua API

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#11675]
### What needs to be documented?

Not missing, but a wrong credit is given. Somebody else just made me aware, that I stand in the PE Wiki for some reason.
Though, I may use it, and recommend it, but **I didn't make it**

Original Post (Wiki):
![image](https://user-images.githubusercontent.com/76132257/211117341-2f936b4c-d988-4f18-942c-6a5a6f6ecfb8.png)

Original Submission (Gamebana)
![image](https://user-images.githubusercontent.com/76132257/211117399-4fc424ed-4f3f-4e25-b1c2-edb448c20c8b.png)

So, said short, **_please credit DotZZ_** instead for this.
thank you ^^

**Comment by ShadowMario** [comment]
Understood, I apologize for the miscredit!
