### ISSUE TITLE
Missing/Invisible Text

### ISSUE THREAD

**Issue by PhoenixRise06** [ShadowMario/FNF-PsychEngine#11678]
### Describe your bug here.

When starting 0.6.3, the intro text (including credits) is missing/invisible.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by EgguMan** [comment]
Assuming you did not edit source, you probably accidentally delete/had overwritten the introText txt file. Check if it’s still in assets>preload>data.
