### ISSUE TITLE
Error when compiling on linux

### ISSUE THREAD

**Issue by Thecoolgamer6745** [ShadowMario/FNF-PsychEngine#11673]
### Describe your problem here.

I get this error when trying to compile on linux:
Error: In file included from ./src/vlc/VlcBitmap.cpp:128:
/mnt/chromeos/MyFiles/Downloads/IMPOSTOR-UPDATE-main/IMPOSTOR-UPDATE-main/source/vlc/cpp/src/LibVLC.cpp:4:10: fatal error: StdInt.h: No such file or directory
4 | #include <StdInt.h>
| ^~~~~~~~~~
compilation terminated.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ArdoDev-stupid** [comment]
and the problem is that you don't have hxCodec

**Comment by Munoida** [comment]
> and the problem is that you don't have hxCodec
That and because of how the Linux file system works, it's case-sensitive.

go into `/source/vlc/cpp/src/LibVLC.cpp` and replace

```#include <mutex>
#include <iostream>
#include <string>
#include <StdInt.h>
#include <windows.h>
```
with

```#include <mutex>
#include <iostream>
#include <string>
#include <stdint.h>
//#include <windows.h>
```

and then your problem should be solved! granted you also have the libvlc-dev or whatever the equivalent is for your package manager.
