### ISSUE TITLE
how do i.....

### ISSUE THREAD

**Issue by imdumlol** [ShadowMario/FNF-PsychEngine#11672]
### Describe your problem here.

change the font and move it down
![how](https://user-images.githubusercontent.com/118001986/211078555-3f2f556b-e2ae-49eb-86a6-e501e8e4de03.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i am using this (0.4.2 version) https://github.com/Basicpeople/FNF-PsychEngine-With-Shaders-Support/releases/tag/0.4.2

**Comment by TheKitBoi** [comment]
Change 'Font Name Here' to the font your using

```
var versionShit:FlxText = new FlxText(12, FlxG.height - 24, 0, "Golden Apple Engine 0.1.2", 12);
versionShit.scrollFactor.set();
versionShit.setFormat("Font Name Here", 16, FlxColor.WHITE, LEFT, FlxTextBorderStyle.OUTLINE, FlxColor.BLACK);
add(versionShit);
```

**Comment by imdumlol** [comment]
![did not work](https://user-images.githubusercontent.com/118001986/211113522-5914f8a0-d31f-4a00-b5c8-c84a34fe3152.png)

**Comment by imdumlol** [comment]
did not work

**Comment by TheKitBoi** [comment]
Did you set the font right

**Comment by imdumlol** [comment]
![wh](https://user-images.githubusercontent.com/118001986/211115448-83f233ba-a3d3-43fe-b30a-92d6a1822e8f.png)

**Comment by imdumlol** [comment]
i put it in assets/fonts

**Comment by TheKitBoi** [comment]
there supposed to be a comic_normal.filename
rename filename to the file

**Comment by imdumlol** [comment]
ok

**Comment by imdumlol** [comment]
i moved to 0.5.2H how do i do it now?

**Comment by TheKitBoi** [comment]
rename Font Name Here.filename to comic_normal.tff
```
var versionShit:FlxText = new FlxText(12, FlxG.height - 24, 0, "Golden Apple Engine 0.1.2", 12);
versionShit.scrollFactor.set();
versionShit.setFormat("Font Name Here.filename", 16, FlxColor.WHITE, LEFT, FlxTextBorderStyle.OUTLINE, FlxColor.BLACK);
add(versionShit);
```

**Comment by imdumlol** [comment]
what line (can't find it)

**Comment by TheKitBoi** [comment]
MainMenuState.hx

**Comment by imdumlol** [comment]
still did not work
