### ISSUE TITLE
Expanded functionality in Character.hx

### ISSUE THREAD

**Issue by EgguMan** [ShadowMario/FNF-PsychEngine#11681]
### What feature do you want to get added on the **base** engine?

Hello, I feel as is, character.hx is lacking in its abilities 

while yes, the character json system is great and should not be understated, I feel like the scope of it is underutilized.

for example, you could have a Bool for animated icons, have a value for trails, etc etc

For example, I modified my character.hx to include a ‘running variable’ which just continues the animation from the last frames animation, which would be insanely easy to add to the source code

while this is not much of a big deal for Source Code users, we gotta treat the lua kiddies kindly too. But in all seriousness, I feel this would just make redundancy less of an issue when adding stuff like this to multiple repos.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CaptainBaldi** [comment]
things such as animated icons and trails can be pretty easily done through source, and it isnt hard to do them in lua either, at most you need to do some runhaxecode bullshit to use flxtrail
i think these like this would just bloat the engine considering how easy these things can be done on both sides

**Comment by CaptainBaldi** [comment]
> things such as animated icons and trails can be pretty easily done through source, and it isnt hard to do them in lua either, at most you need to do some runhaxecode bullshit to use flxtrail i think things like that would just bloat the engine considering how easy these things can be done on both sides

**Comment by EgguMan** [comment]
> while this is not much of a big deal for Source Code users, we gotta treat the lua kiddies kindly too. But in all seriousness, I feel this would just make redundancy less of an issue when adding stuff like this to multiple repos.

I covered this in the post, "while this is not much of a big deal for Source Code users, we gotta treat the lua kiddies kindly too. But in all seriousness, I feel this would just make redundancy less of an issue when adding stuff like this to multiple repos."

I don't quite feel like it would bloat the engine, due to it not effecting the user side and only accounting for 1 part of the dev side.
