### ISSUE TITLE
My dumb script doesn't work (like my life)

### ISSUE THREAD

**Issue by PrismaSucks** [ShadowMario/FNF-PsychEngine#11686]
### Describe your problem here.

I was doing some scripting and when I tested it it didn't work :(. Someone knows why?
`function onCreate()
  credits = json.parse(getTextFromFile('Testing/data/defeat/credits.json'))
  title = credits.title
  composer = credits.composer
end

function onSongStart()
  setTextString('scoreTxt', '')
  makeLuaText('testing', 'Title: ' .. title, 0, 100, 100)
  setTextSize('testing', 50)
  addLuaText('testing')
end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by AyMarte** [comment]
1. rewrite it like this

`function onCreate()
	credits_composer = "The Composer"
	credits_artist = "The Artist"
	credits_charter = "The Chart Editor"
	credits_title = "Song Title"
	title = credits_title
	composer = credits_composer
end

function onSongStart()
	setTextString('scoreTxt', "Put Your Value Here Or Replace With The Quotes With A Variable")
	makeLuaText('testing', 'Title: ' .. title, 0, 100, 100)
	setTextSize('testing', 50)
	addLuaText('testing')
	makeLuaText('composer', credits_composer, 0, 105, getProperty('testing.y') + 60)
	setTextSize('composer', 30)
	addLuaText('composer')
	makeLuaText('artist', credits_artist, 0, 105, getProperty('composer.y') + 40)
	setTextSize('artist', 30)
	addLuaText('artist')
	makeLuaText('charter', credits_charter, 0, 105, getProperty('artist.y') + 40) --From Here To The "addLuaText" you can copy To Make More, Just Change The "artist.y' to the latest one that you didnt just make.
	setTextSize('charter', 30)
	addLuaText('charter')
	runTimer('sus', 5)
end

function onTimerCompleted(tag)
	if tag == 'sus' then
		removeLuaText('testing')
		removeLuaText('composer')
		removeLuaText('artist')
		removeLuaText('charter')
	end
end`

This Should 100% Work Fine
You Can Add Extra Values, Just Make Sure You Add Them To The `'sus'` timer completed function so it can remove itself
