### ISSUE TITLE
Cant Import Character sprite

### ISSUE THREAD

**Issue by Galaxmon** [ShadowMario/FNF-PsychEngine#11688]
### Describe your bug here.

When loading Sprite crashes game

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 217)
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 117)
C:\HaxeToolkit\haxe\std/Xml.hx (line 122)
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
editors/CharacterEditorState.hx (line 840)
editors/CharacterEditorState.hx (line 520)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: haxe.xml.XmlParserException: Expected node name at line 2 char 2
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only Credits hx

**Comment by Galaxmon** [comment]
This is XML `<?xml version="1.0" encoding="UTF-16"?>
<TextureAtlas imagePath="BoyFriend2Mix.png">
	
	
	<SubTexture name="BF HEY!!0000" x="0" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0001" x="0" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0002" x="419" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0003" x="419" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0004" x="838" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0005" x="1257" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0006" x="1676" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0007" x="2095" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0008" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0009" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0010" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0011" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0012" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0013" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0014" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0015" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0016" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0017" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0018" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0019" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0020" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0021" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0022" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0023" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0024" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF HEY!!0025" x="2514" y="0" width="419" height="422"/>
	<SubTexture name="BF NOTE DOWN0000" x="2933" y="0" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0001" x="2933" y="0" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0002" x="3308" y="0" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0003" x="3308" y="0" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0004" x="3683" y="0" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0005" x="0" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0006" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0007" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0008" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0009" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0010" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0011" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0012" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0013" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0014" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0015" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0016" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0017" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0018" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0019" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0020" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0021" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0022" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0023" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0024" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0025" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0026" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0027" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0028" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN0029" x="375" y="422" width="375" height="362"/>
	<SubTexture name="BF NOTE DOWN MISS0000" x="750" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0001" x="1127" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0002" x="1127" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0003" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0004" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0005" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0006" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0007" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0008" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0009" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0010" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0011" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0012" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0013" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0014" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0015" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0016" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0017" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0018" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0019" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0020" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0021" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0022" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0023" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0024" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0025" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0026" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0027" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE DOWN MISS0028" x="1504" y="422" width="377" height="357"/>
	<SubTexture name="BF NOTE LEFT0000" x="1881" y="422" width="387" height="407"/>
	<SubTexture name="BF NOTE LEFT0001" x="1881" y="422" width="387" height="407"/>
	<SubTexture name="BF NOTE LEFT0002" x="2268" y="422" width="387" height="407"/>
	<SubTexture name="BF NOTE LEFT0003" x="2268" y="422" width="387" height="407"/>
	<SubTexture name="BF NOTE LEFT0004" x="2655" y="422" width="387" height="407"/>
	<SubTexture name="BF NOTE LEFT0005" x="3042" y="422" width="387" height="407"/>
	<SubTexture name="BF NOTE LEFT0006" x="3429" y="422" width="387" height="407"/>
	<SubTexture name="BF NOTE LEFT0007" x="3429" y="422" width="387" height="407"/>
	<SubTexture name="BF NOTE LEFT0008" x="3429" y="422" width="387" height="407"/>
	<SubTexture name="BF NOTE LEFT0009" x="3429" y="422" width="387" height="407"/>
	<SubTexture name="BF NOTE LEFT0010" x="3429" y="422" width="387" height="407"/>
	<SubTexture name="BF NOTE LEFT0011" x="3429" y="422" width="387" height="407"/>
	<SubTexture name="BF NOTE LEFT0012" x="3429" y="422" width="387" height="407"/>
	<SubTexture name="BF NOTE LEFT0013" x="3429" y="422" width="387" height="407"/>
	<SubTexture name="BF NOTE LEFT0014" x="2268" y="422" width="387" height="407"/>
	<SubTexture name="BF NOTE LEFT MISS0000" x="0" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0001" x="390" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0002" x="390" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0003" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0004" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0005" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0006" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0007" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0008" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0009" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0010" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0011" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0012" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0013" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0014" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0015" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0016" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0017" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0018" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0019" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0020" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0021" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0022" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0023" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0024" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0025" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0026" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0027" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0028" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0029" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0030" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0031" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0032" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE LEFT MISS0033" x="780" y="829" width="390" height="406"/>
	<SubTexture name="BF NOTE RIGHT0000" x="1170" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0001" x="1170" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0002" x="1579" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0003" x="1579" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0004" x="1988" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0005" x="2397" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0006" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0007" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0008" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0009" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0010" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0011" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0012" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0013" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0014" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0015" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0016" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0017" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0018" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0019" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0020" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0021" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0022" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0023" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0024" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0025" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0026" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0027" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0028" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0029" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0030" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0031" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0032" x="3215" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0033" x="3215" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0034" x="3624" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0035" x="0" y="1238" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0036" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0037" x="409" y="1238" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0038" x="409" y="1238" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0039" x="818" y="1238" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0040" x="1227" y="1238" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0041" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0042" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0043" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0044" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0045" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0046" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0047" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0048" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0049" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0050" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0051" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0052" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0053" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0054" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0055" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0056" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0057" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0058" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0059" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0060" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT0061" x="2806" y="829" width="409" height="409"/>
	<SubTexture name="BF NOTE RIGHT MISS0000" x="1636" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0001" x="2044" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0002" x="2044" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0003" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0004" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0005" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0006" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0007" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0008" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0009" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0010" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0011" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0012" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0013" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0014" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0015" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0016" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0017" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0018" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0019" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0020" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0021" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0022" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0023" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0024" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0025" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0026" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0027" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0028" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0029" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0030" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0031" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0032" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0033" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0034" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0035" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0036" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0037" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0038" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0039" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0040" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0041" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0042" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0043" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0044" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE RIGHT MISS0045" x="2452" y="1238" width="408" height="406"/>
	<SubTexture name="BF NOTE UP0000" x="2860" y="1238" width="384" height="446"/>
	<SubTexture name="BF NOTE UP0001" x="2860" y="1238" width="384" height="446"/>
	<SubTexture name="BF NOTE UP0002" x="3244" y="1238" width="384" height="446"/>
	<SubTexture name="BF NOTE UP0003" x="3244" y="1238" width="384" height="446"/>
	<SubTexture name="BF NOTE UP0004" x="3628" y="1238" width="384" height="446"/>
	<SubTexture name="BF NOTE UP0005" x="0" y="1684" width="384" height="446"/>
	<SubTexture name="BF NOTE UP0006" x="384" y="1684" width="384" height="446"/>
	<SubTexture name="BF NOTE UP0007" x="384" y="1684" width="384" height="446"/>
	<SubTexture name="BF NOTE UP0008" x="384" y="1684" width="384" height="446"/>
	<SubTexture name="BF NOTE UP0009" x="384" y="1684" width="384" height="446"/>
	<SubTexture name="BF NOTE UP0010" x="384" y="1684" width="384" height="446"/>
	<SubTexture name="BF NOTE UP0011" x="384" y="1684" width="384" height="446"/>
	<SubTexture name="BF NOTE UP0012" x="384" y="1684" width="384" height="446"/>
	<SubTexture name="BF NOTE UP0013" x="384" y="1684" width="384" height="446"/>
	<SubTexture name="BF NOTE UP0014" x="384" y="1684" width="384" height="446"/>
	<SubTexture name="BF NOTE UP MISS0000" x="768" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0001" x="1149" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0002" x="1149" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0003" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0004" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0005" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0006" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0007" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0008" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0009" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0010" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0011" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0012" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0013" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0014" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0015" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0016" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0017" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0018" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0019" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0020" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0021" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0022" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF NOTE UP MISS0023" x="1530" y="1684" width="381" height="446"/>
	<SubTexture name="BF idle dance0000" x="1911" y="1684" width="412" height="415"/>
	<SubTexture name="BF idle dance0001" x="1911" y="1684" width="412" height="415"/>
	<SubTexture name="BF idle dance0002" x="2323" y="1684" width="412" height="415"/>
	<SubTexture name="BF idle dance0003" x="2323" y="1684" width="412" height="415"/>
	<SubTexture name="BF idle dance0004" x="2735" y="1684" width="412" height="415"/>
	<SubTexture name="BF idle dance0005" x="2735" y="1684" width="412" height="415"/>
	<SubTexture name="BF idle dance0006" x="3147" y="1684" width="412" height="415"/>
	<SubTexture name="BF idle dance0007" x="3147" y="1684" width="412" height="415"/>
	<SubTexture name="BF idle dance0008" x="3559" y="1684" width="412" height="415"/>
	<SubTexture name="BF idle dance0009" x="3559" y="1684" width="412" height="415"/>
	<SubTexture name="BF idle dance0010" x="0" y="2130" width="412" height="415"/>
	<SubTexture name="BF idle dance0011" x="412" y="2130" width="412" height="415"/>
	<SubTexture name="BF idle dance0012" x="824" y="2130" width="412" height="415"/>
	<SubTexture name="BF idle dance0013" x="824" y="2130" width="412" height="415"/>
</TextureAtlas>
`

**Comment by frantastic24** [comment]
Not a bug
Duplicate of #9296

**Comment by Galaxmon** [comment]
oh ok

**Comment by Galaxmon** [comment]
I've tried Exporting Sparrow V2 in Adobe Flash, Animate CC, and I have tried to paste into notepad and encode in UTF-8 and convert it into a XML(Instructions where unclear I'll add) but my problem is still not resolved?

**Comment by Galaxmon** [comment]
nvm solved it
