### ISSUE TITLE
Source Code Achievements Bug

### ISSUE THREAD

**Issue by KhailanDoesGaming** [ShadowMario/FNF-PsychEngine#11699]
### Describe your problem here.

So basically, source code won't compile for me. It's showing the code below.
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\khail\Desktop\FNF-PsychEngine-0.6.3\FNF-PsychEngine-0.6.3\export\debug\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

Please help with this issue I've been trying to use source code for so long

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I replaced old Main.hx with new Main.hx, that's it

**Comment by EyeDaleHim** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/10756
