### ISSUE TITLE
Sprite sheet crashes game when loading in a song

### ISSUE THREAD

**Issue by FatherGibus** [ShadowMario/FNF-PsychEngine#11697]
### Describe your bug here.

I have a issue where the game outright crashes with no error messages
The sprite is exported in Adobe Anime using the settings: Sparrow v2 at 8192 px with format at PNG 32 bit
It loads perfectly fine in the character editor but just crashes without any errors when its inserted into any song.
Its strange as this is the first time its done this with despite adding in other sprites prior which work fine.
Any help would be appreciated.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Fresh build straight from releases, everything where it usually goes.

**Comment by Yuta12342** [comment]
You should probably send the problematic image/xml.

**Comment by FatherGibus** [comment]
uploaded it on a drive:
https://drive.google.com/file/d/1qNatfSmirnQsSYsOcufMENuktTP5x1P4/view?usp=sharing
I appreciate any help :)

**Comment by frantastic24** [comment]
the character if working fine here, though all of their animations are wrong
could it be a script or the song/stage being too heavy?
![imagen](https://user-images.githubusercontent.com/95725102/211457679-502e61cd-e881-4a64-a149-efc1aad22cd6.png)

**Comment by FatherGibus** [comment]
How strange, for me i tested it straight from the build in releases with nothing else. It crashes on any base game song for me. I'll see if redoing the json in the character editor will fix it.

**Comment by TheKitBoi** [comment]
[floosip.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/10394276/floosip.txt) rename txt to json
Fixed JSON since no one did it
(check the xml for the correct anims)
