### ISSUE TITLE
game crashing when trying to load an custom character

### ISSUE THREAD

**Issue by pudimcool** [ShadowMario/FNF-PsychEngine#11698]
### Describe your bug here.

When i go on freeplay or story mode go to a song and press 7 and click to change characters so that i can see if it works the game crashes showing up a message. 

I dont know if it is a problem with the place i put the json (PsychEngine > mods > characters) or if it is my computer
it worked on my other re skins the bug only started when i updated my PsychEngine to the newest version. 

The build that im using only has 2 other re skins and a custom song the other re skins stopped working when i updated too so i dont know

### Command Prompt/Terminal logs (if existing)

```bash
PlaState.hx (line 3070) 
flixel/FlxState.hx (line 202) 
flixel/FlxState.hx (line 747) 
flixel/FlxState.hx (line 677) 
flixel/FlxState.hx (line 551) 

openfl/events/EventDispatcher.hx (line 402)
openfl/events/DisplayObject.hx (line 1399)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, it was just to test if a re skin worked

**Comment by 40U538072** [comment]
The json could have not saved properly. Can you access the custom character in the character editor? Press 7, go to 'Character Editor', and look for the name of the character. Does it crash when you do? Could have saved as a standard file. You can fix it by changing the file type in the name. Just add '.json' next to the name and it should work. Could have also bugged like Psych Engine usually does and you will have to start all over.
