### ISSUE TITLE
remove mods folder?

### ISSUE THREAD

**Issue by imdumlol** [ShadowMario/FNF-PsychEngine#11690]
### Describe your problem here.

how do i remove it?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

yes 0.4.2 with shaders

**Comment by IdiotLimitedEdition** [comment]
Remove it normally and then go to the Project.xml and remove this
```xml
	<section if="MODS_ALLOWED">
		<assets path='example_mods' rename='mods' embed='false'/>
	</section>
```
Then you can try to to compile it

**Comment by imdumlol** [comment]
i can't find that line (on psych 0.4.2)

**Comment by Setter-Function** [comment]
![line](https://user-images.githubusercontent.com/108081370/211735225-1e4eadeb-1187-4336-976b-f6b775040573.png)
Remove line 95. And if you've already compiled it, delete 'bin' folder too. And then, please compile it again.

**Comment by imdumlol** [comment]
alright thx
