### ISSUE TITLE
Hide icons in Freeplay (SOURCE)

### ISSUE THREAD

**Issue by WolfyTail** [ShadowMario/FNF-PsychEngine#11694]
### Describe your problem here.

Is it possible to hide the freeplay icons when a song is not selected? Something like this?:

icon.alpha = 0;
**if (item.targetY == 0)** icon.alpha = 1;

I've already tried to put that at the code, but it doesn't work. How could I do this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
if’s supposed to be
iconP1.alpha and iconP2.alpha = 0

**Comment by tposejank** [comment]
> if’s supposed to be iconP1.alpha and iconP2.alpha = 0
i have a tip option on my brave browser but based on the knowledge of your comment i shouldnt tip at all.

**Comment by WolfyTail** [comment]
> if’s supposed to be iconP1.alpha and iconP2.alpha = 0

In the FREEPLAY MENU, not the PlayState.

**Comment by DisIsNOt** [comment]
icon.visible = false; 

idk

**Comment by TheKitBoi** [comment]
remove these lines
![image](https://user-images.githubusercontent.com/84044666/212409541-19c090d1-d4f1-4ace-aa9b-453c4d1d4705.png)

![image](https://user-images.githubusercontent.com/84044666/212409315-20317795-2034-48d1-b43f-33048c7a0713.png)

![image](https://user-images.githubusercontent.com/84044666/212409619-fab60361-af66-46a2-8d2b-5b1fd650221f.png)

**Comment by WolfyTail** [comment]
It didn't work, but dw, I've already figured out how to do it. Thank y'all.
