### ISSUE TITLE
alright so...

### ISSUE THREAD

**Issue by imdumlol** [ShadowMario/FNF-PsychEngine#11691]
### Describe your problem here.

i need to replace a button on main menu how do i do that?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

yes shaders in 0.4.2

**Comment by RubenDatOneBoi3446** [comment]
Just replace the 
menu_freeplay with your custom menu_freeplay
both xml and png need be replaced, (if you have xml unless you just edited one without an xml)

**Comment by imdumlol** [comment]
but it has a different xml name on the animations.

**Comment by RubenDatOneBoi3446** [comment]
what is the sprite name on your png?
