### ISSUE TITLE
problems with the character editor, and with the sprites

### ISSUE THREAD

**Issue by lufenodritoz** [ShadowMario/FNF-PsychEngine#11696]
### Describe your bug here.

Hello, I have a problem that I don't know if it's the engine, or my sprites or because I use flash to animate, it turns out that a few weeks ago I made some sprites, but when I went to the character editor to edit the sprites I got an error I didn't pay attention to it and left it abandoned, now the problem reappeared. These days a friend asked me to make some sprites for them, I did it and I passed them to him, and it turns out that the same thing happens to him, we are trying to solve it and we have no idea how

here is what the error specifies in case you are curious to know 
![image](https://user-images.githubusercontent.com/122238827/211225590-ae44ce8c-8bdf-4673-8c68-937d5ccfeed1.png)
 
pls help me

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheKitBoi** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/9296
