### ISSUE TITLE
Custom main menu image not loading

### ISSUE THREAD

**Issue by Jevilm** [ShadowMario/FNF-PsychEngine#11693]
### Describe your bug here.

You read the title, i made a custom main menu section and the image is the haxe logo, help please?
![weghrhj](https://user-images.githubusercontent.com/110422450/211204444-304999b6-1398-4bb6-a79b-05cd42d3ee9b.PNG)
![sardtyhgf](https://user-images.githubusercontent.com/110422450/211204478-80d7c953-0085-4172-ad7d-53b127b82468.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i modified MainMenuState.hx and added a new section

**Comment by CaptainBaldi** [comment]
it can't find your file

**Comment by Jevilm** [comment]
> it can't find your file

im pretty sure i placed it in images/mainmenu

**Comment by IdiotLimitedEdition** [comment]
I'm no programming expert but I think the game is trying to find a file called menu_Extras with an uppercase E just go to the array and make it lowercase

**Comment by Jevilm** [comment]
> I'm no programming expert but I think the game is trying to find a file called menu_Extras with an uppercase E just go to the array and make it lowercase

It is lowercase, i checked just now
But for now im gonna close this
