### ISSUE TITLE
How To Add A Custom Music For Custom Week?

### ISSUE THREAD

**Issue by SaVia01** [ShadowMario/FNF-PsychEngine#117]
i don't know how to add custom music and i really need help cuz i need to chart something random ae

**Comment by FuseIsHere813** [comment]
For songs, put the Inst and Voices into "assets/songs/your-song-name" 

Then, the charts or made charts goes into "assets/preload/data/your-song-name"

**Comment by ShadowMario** [comment]
If you're doing it on a Downloaded build:
Charts - `mods/data/your-song-name/`
Song - `mods/songs/your-song-name/`

If you're doing it on the source code:
Charts - `assets/preload/data/your-song-name/`
Song - `assets/songs/your-song-name/`
