### ISSUE TITLE
I can't save my chart for some reason...

### ISSUE THREAD

**Issue by Zoe096423** [ShadowMario/FNF-PsychEngine#11704]
### Describe your problem here.

I created a json file "A.json" for song-A and made sure it worked well.
Then I copied "A.json" and renamed the copy version "B.json". I wanted to use "B.json" as song-B's temporary chart file.
Later on, I finally get to chart song-B, and I made sure to save the new "B.json" in the correct folder, replacing the old one.
Weirdly, everytime I re-chart song-B, re-build and open the game, song-B never once used the new charts. Instead, it ALWAYS used the old charts copied from "A.json".

Is there anyway I can solve this problem?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Luigitin** [comment]
Did you edit the name of the song A? inside the .json file its a line of code that says the name of the song, its probably that
if not, then idk

**Comment by 40U538072** [comment]
Make sure you are not clicking load autosave. Autosaving is pretty buggy and you have to make sure you are clicking 'Save', though that can be a bit buggy too in my case.

**Comment by Yuta12342** [comment]
This may seem stupid, but I did this once - If you are charting, and saving into the Export Folder, and not the Source Folder, building it is likely going to override whatever saves you made.

**Comment by Zoe096423** [comment]
@40U538072 Yeah, I wasn't using autosave.
I'll keep that in mind, tho.

@Yuta12342 I tried, I saved the chart into both (1) the original assets folder and (2) the assets folder in export bin, but none of them seem to override successfully.

**Comment by 40U538072** [comment]
See if the location you are saving it to is not set to read only. That can prevent the writing of files.
