### ISSUE TITLE
no custom credits??

### ISSUE THREAD

**Issue by plotmanlover** [ShadowMario/FNF-PsychEngine#11702]
### Describe your problem here.

I need help to put down custom credits in spyche engine as im makin a mod along with a small noob team we are, so i did what im supposed to do(file in images called credits for the icon credits and i put credits.txt in the data folder)
name::iconname::description::link::0xFF
(i already put everything i need in there)
 but its not working for some reason and idk why and i want to add credits)
![credits txt - Notepad 1_11_2023 12_30_04 PM](https://user-images.githubusercontent.com/119635880/211876681-10b9a12c-cab4-4b2d-99c8-7b023639bc01.png)
![Friday Night Funkin'_ Psych Engine 1_11_2023 12_27_22 PM](https://user-images.githubusercontent.com/119635880/211876732-631f92e0-90f8-49f9-ba20-6ef4431f87de.png)

 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
Remove the 0x from each line

**Comment by plotmanlover** [comment]
that did not work

**Comment by plotmanlover** [comment]
IVE FOUND THE PROBLEM. I had to remove the .txt from the credits it was preventing me from making the credits
