### ISSUE TITLE
All sprites replaces with black rectangles.

### ISSUE THREAD

**Issue by vesel4ak** [ShadowMario/FNF-PsychEngine#11707]
### Describe your bug here.

This bug was even earlier, but it did not occur so often. I played the VS Impostor v4 mod (there was a bug not only in it). My computer broke down and I ONLY had to change the hard drive. This bug has not been fixed, it still exists. In general, the bug is that sprites, backgrounds, splashes, etc. were replaced with black rectangles. I don't think the problem is in fashion, rather in my computer, because it is VERY UNPRODUCTIVE. Maybe it is possible to fix it somehow or not? (for example, if the first song had only a black square background, then the next song could be just one black square, but the arrows will be visible, they are default)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Not a bug
Time to invest in a better graphics card

**Comment by vesel4ak** [comment]
> Not a bug Time to invest in a better graphics card

gotcha
