### ISSUE TITLE
can someone tell me how to use this thing the camera follow pos event

### ISSUE THREAD

**Issue by anonybean** [ShadowMario/FNF-PsychEngine#1170]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/94534428/142605217-9871ddd6-d0de-4fbc-b73b-c67fa9c39dc2.png)
 A

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

**Comment by MayoALT** [comment]
which thing??????

**Comment by anonybean** [comment]
> which thing??????

the camera follow pos event how do I use it

**Comment by MayoALT** [comment]
value 1: x
value 2: y

**Comment by anonybean** [comment]
yea i tried but nothing happend

> value 1: x value 2: y

**Comment by Adriangamer1246** [comment]
the value one is how up or down the camera is the and the sec value is how left or right the camera goes example: 200 300
