### ISSUE TITLE
Source code event that changes the speed of the camera zooming

### ISSUE THREAD

**Issue by SuperWA-HOOMan** [ShadowMario/FNF-PsychEngine#11701]
### Describe your problem here.

I'm trying to add an event to the source code that changes the speed and intensity of the camera zooming in to the beat, but im too stupid. does anybody know how to do that? (also im using 0.5.2h)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Ratio-Combinder** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/blob/0.5.2h/source/PlayState.hx#L2437

**Comment by SuperWA-HOOMan** [comment]
nvm i found a workaround
