### ISSUE TITLE
Access HUD elements within Lua

### ISSUE THREAD

**Issue by TaoTheBlock** [ShadowMario/FNF-PsychEngine#11706]
### What is your question?

I wanna know if I can access some HUD elements using Lua. I tried to do it once and it didn't work. So how do I do it?

**Comment by Drawoon2** [comment]
```

'iconP2'--dad icon
'iconP1'--bf icon
'healthBar'--health bar
'scoreTxt'--rating text
'timeBar'--Time Bar
'timeTxt'--Time text
```

**Comment by Zexlo** [comment]
dont forget to close the issue.

**Comment by TaoTheBlock** [comment]
Thanks Drawoon2. Very Cool!
