### ISSUE TITLE
Pixel Character not working?

### ISSUE THREAD

**Issue by Luigitin** [ShadowMario/FNF-PsychEngine#11705]
### Describe your problem here.

So, i was going to make a pixel character, i even made the xml file, but when i playtested it it used it as if it was a normal character (not pixel) and i dont know what to do :p

screenshot:
![image](https://user-images.githubusercontent.com/111601864/211984628-465c4f02-3744-4166-b171-76a7abf3626d.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

not really, its just a modpack

**Comment by Ratio-Combinder** [comment]
send the files in a zip folder

**Comment by Luigitin** [comment]
> send the files in a zip folder

sorry for answering way too late, but here it is:
https://www.mediafire.com/file/thhjrn33s2gtgj0/pico-Pixellized.rar/file

**Comment by TheKitBoi** [comment]
[pico-Pixellized (Fixed).zip](https://github.com/ShadowMario/FNF-PsychEngine/files/10407881/pico-Pixellized.Fixed.zip)

the xml properties are wrong
so I separated the frames and combind them into a fix

**Comment by Luigitin** [comment]
thanks
