### ISSUE TITLE
Hmph

### ISSUE THREAD

**Issue by Deathm00n** [ShadowMario/FNF-PsychEngine#11712]
### What is your question?

![스크린샷(92)](https://user-images.githubusercontent.com/122658685/212449136-a629cc94-f73a-4c95-b51e-50bebaee8d5f.png)

**Comment by CaptainBaldi** [comment]
missing chart file

**Comment by Deathm00n** [comment]
Thank you man

**Comment by Ratio-Combinder** [comment]
close the issue
![close the issue anim](https://user-images.githubusercontent.com/120575989/212704866-7b915b6f-391a-4098-8d6e-39470a4f1e51.gif)
