### ISSUE TITLE
sprites with errors, and mixed

### ISSUE THREAD

**Issue by lufenodritoz** [ShadowMario/FNF-PsychEngine#11711]
### Describe your bug here.

Well, I had already solved the problem with the xml (problem here #11696) but now I have the problem that the animations are mixed, or the animation does not appear, or the animation that is not appears, again, here I leave a examples, to facilitate your help

example1: https://drive.google.com/file/d/1i7Tni_ErlAtkY_gAx6AowTR2qoXThxMT/view?usp=sharing
example2: https://drive.google.com/file/d/1j0FnunY0XL0NiX-d8OD02xsW3gHcvAc1/view?usp=sharing

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

just edit the json of the character

**Comment by frantastic24** [comment]
Not a bug
Animation names don't match your XML

**Comment by lufenodritoz** [comment]
> Animation names don't match your XML

but, that doesn't make sense, although I don't know, but does it have a solution?

**Comment by frantastic24** [comment]
Edit your character and their animations 
Can't help more than that because you didn't show any of your files

**Comment by TheKitBoi** [comment]
> but, that doesn't make sense, although I don't know, but does it have a solution?

then send the files in a zip so i can fix them

**Comment by lufenodritoz** [comment]
> Edit your character and their animations Can't help more than that because you didn't show any of your files

I did that, I even exported the sprites and xml in other algorithms and data formats

**Comment by lufenodritoz** [comment]
> > but, that doesn't make sense, although I don't know, but does it have a solution?
> 
> then send the files in a zip so i can fix them

https://drive.google.com/drive/folders/1YfLk2rYJjtEbMMKNkW6qTZupVJhQBMRK?usp=sharing

**Comment by frantastic24** [comment]
You didn't post the character json

**Comment by lufenodritoz** [comment]
> You didn't post the character json
> 
> The normal animations playing miss animations happens because they have similar names and the game picks up both, add a 0 to the end of the normal animation

what, I don't understand, can you explain it to me in more detail?

**Comment by frantastic24** [comment]
Look at boyfriend's animations for reference, his normal and miss animations have similar names so to prevent the game from playing both there's a 0 at the end of the normal ones

**Comment by lufenodritoz** [comment]
> Look at boyfriend's animations for reference, his normal and miss animations have similar names so to prevent the game from playing both there's a 0 at the end of the normal ones
> 
> Also still no character json

I still don't understand, but well let's pretend that yes, so the solution is?

**Comment by TheKitBoi** [comment]
are you gonna send the character frames

**Comment by lufenodritoz** [comment]
> are you gonna send the character frames

Marco, what do you mean, I'm sorry I'm not so fluent in English

**Comment by TheKitBoi** [comment]
every sprite frames from the files you sent us

**Comment by lufenodritoz** [comment]
> every sprite frames from the files you sent us

from the fla or the xml?

**Comment by TheKitBoi** [comment]
From fla

**Comment by lufenodritoz** [comment]
> From fla

ok
idle nikusa frame
![image](https://user-images.githubusercontent.com/122238827/214432312-ba798986-def1-44a9-9faf-41e8b1931c22.png)
poses frame
![image](https://user-images.githubusercontent.com/122238827/214432448-74bc4fad-ae0a-4b35-8259-400d56f3530f.png)
hey animation (laugh alt)
![image](https://user-images.githubusercontent.com/122238827/214432877-a95c0c33-6d9a-49a0-8117-c24503df298e.png)
hey animation (laugh)
![image](https://user-images.githubusercontent.com/122238827/214433056-fa92d515-bbd8-4e6f-a185-d5ed13bc8f7d.png)

ns if you want tbm from bf's skin

**Comment by TheKitBoi** [comment]
send the fla files in a zip
nikusa and bf reskin

**Comment by lufenodritoz** [comment]
nikusa reanimated https://drive.google.com/file/d/1tskWhjEsbDFn-yWreFzKcGJAgNZDcgu9/view?usp=share_link
bf reskin https://drive.google.com/file/d/1CjD6NaIM087g2d3e1tD-XLO93g4C6sut/view?usp=share_link

**Comment by TheKitBoi** [comment]
exported the bf one and
this is the wrong nikusa file
![image](https://user-images.githubusercontent.com/84044666/215279399-e8be1abd-7af7-4d47-addc-d1d97f83fc56.png)

**Comment by lufenodritoz** [comment]
ok hehe
https://drive.google.com/file/d/1aJl96oPK6WinEKhSBVy5Pm0baGcwKcQK/view?usp=share_link

**Comment by TheKitBoi** [comment]
here you go
[fixed.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/10562243/fixed.zip)
