### ISSUE TITLE
Is there a way to set the note colors for a specific song?

### ISSUE THREAD

**Issue by luigiman0** [ShadowMario/FNF-PsychEngine#11710]
### What is your question?

Basically, I'm trying to have a song where the note colors are different than the base game ones. I figured since Psych Engine has a built in Note Colors option, this might be possible. Is there any way to do this in Lua?

**Comment by NightmaresPlayz** [comment]
I’m pretty sure you can do it in the charting area, there will be 2 boxes, one for the assets note and one for the splashes

**Comment by luigiman0** [comment]
> I’m pretty sure you can do it in the charting area, there will be 2 boxes, one for the assets note and one for the splashes. But you have to add the images in the image file to be able to do it.

thanks!
