### ISSUE TITLE
Rating Score

### ISSUE THREAD

**Issue by TaoTheBlock** [ShadowMario/FNF-PsychEngine#11715]
### What is your question?

Hi, It's me again.

Last question for today.
How much score does each rating give? like Sick, Good, Bad and the worst one.

Am a nice guy so yeah.

**Comment by APRO716** [comment]
Sick = 350
Good = 200
Bad = 100
Shit (Worst one) = 50

**Comment by TaoTheBlock** [comment]
Thanks APRO716. Very Cool!
