### ISSUE TITLE
Game won't compile after updating to Haxe 5.1.0

### ISSUE THREAD

**Issue by NickPlayzGITHUB** [ShadowMario/FNF-PsychEngine#11719]
### Describe your problem here.

So I was working on a mod and there was this issue where the camera and hud would zoom out really far for some reason and this would happen on every song. And my team said that updating Haxe fixed the issue, so after I updated it wouldn't let me compile the build
![image](https://user-images.githubusercontent.com/87223282/212486778-92ffece4-ba35-4cee-a247-e97b1d99c288.png)
anyone know how to fix this? We are on a tight schedule rn

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by IdiotLimitedEdition** [comment]
Reinstall flixel
 ```batchfiles 
haxelib remove flixel 
```
```batchfiles 
haxelib install flixel 
```

**Comment by NickPlayzGITHUB** [comment]
just tried that, same issue.

**Comment by NickPlayzGITHUB** [comment]
it only compiles using flixel 4.9.0 but the camera is all zoomed out for some reason
