### ISSUE TITLE
More stuff accessible within Lua script

### ISSUE THREAD

**Issue by TaoTheBlock** [ShadowMario/FNF-PsychEngine#11714]
### What feature do you want to get added on the **base** engine?

I have think about this for a while now and I feel interested about this.

I love to code in Lua and also made a mod out of them without even touching a Source Code.

My suggestions are:
1. If possible. Could the engine be able to support for Lua Custom Achievement in the future?
2. If possible. Could the engine be able to support for Lua Freeplay Menu? Like be able to to some custom menu thing in Freeplay from Lua?

That's all my suggestions. If it not possible or too difficult then that fine.
Sorry if my English is weird...

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6+ support, and winning icons.

**Comment by nennneko5787** [comment]
![image](https://user-images.githubusercontent.com/95109758/212463456-1d91eb04-c2ad-44c9-a978-88c84701cfc0.png)

**Comment by TaoTheBlock** [comment]
Oops! I do it wrong. I fixed it now!

**Comment by CaptainBaldi** [comment]
psych engine repo users try not to make stupid ideas (impossible, instant fail)

**Comment by TaoTheBlock** [comment]
Bruh.
