### ISSUE TITLE
Charting

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#11718]
### Describe your problem here.

My charting won’t work, it is stuck on 0:00 timing with no notes

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Mokona5901** [comment]
if you don't have inst or voices, did you unchecked on chart editor ?

**Comment by NightmaresPlayz** [comment]
I tried that but still didn’t work
