### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Toffee-Coffee** [ShadowMario/FNF-PsychEngine#11725]
### Describe your bug here.

![Screenshot (33)](https://user-images.githubusercontent.com/122753911/212568581-dba0c01b-191c-43a7-ba6c-f50699850ac3.png)
 so basically, i was making a week for my internet persona, and this showed up when i went to play the song, idk what it means though

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

trying to make a new week, but this showed up when i tried to play a song

**Comment by TheKitBoi** [comment]
Send the file rename it to .txt

**Comment by Toffee-Coffee** [comment]
thank you, this worked
