### ISSUE TITLE
Note Texture

### ISSUE THREAD

**Issue by xboomerboyx** [ShadowMario/FNF-PsychEngine#11723]
### Describe your problem here.

So I'm making a mod and I made a custom note texture for week 6. I don't know how to make the texture appear in game.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by RedAlertEli** [comment]
If you're talking about applying a note texture to a specific song, then follow these steps.

1) Go to your copy of Psych, then go to mods/images

2) Make a new folder called pixelUI

3) Put your custom pixel note assets in there. It's preferred if you rename them to something like "CUSTOMNOTE_assets" and "CUSTOMNOTE_assetsENDS

4) Go to the Chart Editor and open whichever song you are wanting to apply the noteskin to, then put "CUSTOMNOTE_assets" (just my example.) into the Note Texture box, then press Change Notes.

Hope this helps! Good luck with your mod! :)
![image_2023-01-15_154902681](https://user-images.githubusercontent.com/122751953/212566532-b33c45fe-2e5f-4c47-8098-7f778ab871de.png)

**Comment by xboomerboyx** [comment]
Thank you, this helped a lot. I figured it out!

**Comment by xboomerboyx** [comment]
Thank you, this helped a lot. I figured it out!3
