### ISSUE TITLE
How to change "Sick!!", "Good", "Bad", and "S***" textures for a certain stage only?

### ISSUE THREAD

**Issue by DacroyleYT** [ShadowMario/FNF-PsychEngine#11728]
### Describe your problem here.

Using lua, I want to change the judgement textures (sick, good, bad and s) but only for a certain stage, not all songs. How do I do that?

P.S. I'm doing this for a pixel stage.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by fr459** [comment]
ok

**Comment by fr459** [comment]
daddy

**Comment by fr459** [comment]
send the project right now

**Comment by fr459** [comment]
pls
s

**Comment by fr459** [comment]
if not

**Comment by fr459** [comment]
I will k!ll y0u

**Comment by DacroyleYT** [comment]
@fr459 ok
[wallichad.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/10421516/wallichad.zip)

**Comment by DacroyleYT** [comment]
@REALHaydenGaming is this right? it doesnt work so maybe not
```
    setProperty('ratingData[0].image', 'goat/sick-bedwars')
    setProperty('ratingData[1].image', 'goat/good-bedwars')
    setProperty('ratingData[2].image', 'goat/bad-bedwars')
    setProperty('ratingData[3].image', 'goat/dookie-bedwars')
```
(the images are in images/goat instead of images)

**Comment by frantastic24** [comment]
Pixel assets go inside `images/pixelUI`

**Comment by DacroyleYT** [comment]
@frantastic24 still doesnt work :(

**Comment by frantastic24** [comment]
Just noticed there's a typo
It's `ratingsData`

**Comment by DacroyleYT** [comment]
@frantastic24 Ok it sort of works, but the ratings are now tiny haxeflixel logos (in other words, missing images). How to fix that?

**Comment by DacroyleYT** [comment]
Never mind I just appended "-pixel" to the file names and it worked! Thank you :)

**Comment by zFabriRz** [comment]
can you use "Function onCreate?"
