### ISSUE TITLE
BPM Broken

### ISSUE THREAD

**Issue by SonicMapper** [ShadowMario/FNF-PsychEngine#11724]
### Describe your bug here.

I have a song that is at 146 BPM, so I wanted to change it to 130 BPM, but for some reason after I changed the BPM, the notes became invisible

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't change anything in the .HX files

**Comment by 40U538072** [comment]
Maybe another bug that Psych Engine won't fix. Clear your chart and start all over. Shouldn't be that hard.
