### ISSUE TITLE
hxcodec not working

### ISSUE THREAD

**Issue by MothEggs** [ShadowMario/FNF-PsychEngine#11726]
### Describe your problem here.

if i use hxcodec 2.6.0 i get this

source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler

and if i use hxcodec 2.5.1 i get this

source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
Error: Could not find haxelib "hxCodec", does it need to be installed?

what do i do to fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheRealJake12** [comment]
actually you'd be using source, anyway just go to PlayState.hx, remove the vlc.MP4Handler first one and then change the second one to VideoHandler

**Comment by MothEggs** [comment]
yah i changed it to source originally but it didnt work i guess
