### ISSUE TITLE
I'm probably stupid but plz help

### ISSUE THREAD

**Issue by MrYes3215** [ShadowMario/FNF-PsychEngine#11727]
### What is your question?

So I was compiling psych engine when suddenly I realized I'm stupid and don't know how to fix this,
![error](https://user-images.githubusercontent.com/105925512/212571574-b5c83f38-ed16-449b-9a4d-a958b9742a37.PNG)

**Comment by MrYes3215** [comment]
PLEASE HELP I'VE TRIED EVERYTHING!!!

**Comment by fr459** [comment]
ok

**Comment by fr459** [comment]
is hard

**Comment by TheKitBoi** [comment]
@fr459 why are u commenting useless text

for @MrYes3215 change vlc.MP4Handler to VideoHandler
and replace Main.hx with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

**Comment by PDL2CGamejolt** [comment]
> @fr459 why are u commenting useless text
> 
> for @MrYes3215 change vlc.MP4Handler to VideoHandler and replace Main.hx with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

Now it's saying that VIDEOHANDLER is non-existent!

**Comment by TheKitBoi** [comment]
you commented on an issue no one replied for a week
so
```
haxelib remove hxCodec
haxelib install hxCodec 2.5.1
```
