### ISSUE TITLE
where do i put mainmenustate.hx

### ISSUE THREAD

**Issue by apple-drop** [ShadowMario/FNF-PsychEngine#11739]
### Describe your problem here.

so im making a gallery thing and i need to put a hx file in psych but idk where. can anyone help?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Lorekeeper49** [comment]
The source folder, anywhere in there will work

**Comment by apple-drop** [comment]
> The source folder, anywhere in there will work

Where is that?

**Comment by CaptainBaldi** [comment]
💀 💀 💀

**Comment by TheKitBoi** [comment]
> Where is that?

![image](https://user-images.githubusercontent.com/84044666/212955848-620d914b-304d-4d9c-bea6-a868a87c7b09.png)

ar u 5 year old or something

**Comment by ShadowMilky** [comment]
> ### Describe your problem here.
> so im making a gallery thing and i need to put a hx file in psych but idk where. can anyone help?

bruh, source folder

**Comment by apple-drop** [comment]
> > ### Describe your problem here.
> > so im making a gallery thing and i need to put a hx file in psych but idk where. can anyone help?
> 
> bruh, source folder this idiot cant memorize folders

I dont have a source folder in my psych engine

**Comment by apple-drop** [comment]
> 

Can you send a link to one

**Comment by apple-drop** [comment]
> > Can you send a link to one
> 
> https://github.com/ShadowMario/FNF-PsychEngine/archive/refs/heads/main.zip

And i just put the source folder in my current psych engine or do i have to add everything to that one

**Comment by TheKitBoi** [comment]
Your supposed to put the mainmenustate.hx in the source folder from the link

**Comment by codeyballpa** [comment]
but where do i PUT the folder? do i put it in scripts? (im still new to using psych so please help)
