### ISSUE TITLE
Are Gameplay Changers Accessible By Lua?

### ISSUE THREAD

**Issue by AnomaleZ** [ShadowMario/FNF-PsychEngine#11730]
### What is your question?

So you know about the Gameplay Changers when you press Ctrl in Freeplay?
I've been curious if you can access and change the multiplier for health gain/loss via Lua.
If not, is there any alternative ways to customize how much health you gain/lose?

**Comment by TheKitBoi** [comment]
check line 197 https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/FunkinLua.hx#L197 to 213 in FunkinLua.hx

**Comment by ItsMeTyler25** [comment]
> ### What is your question?
> So you know about the Gameplay Changers when you press Ctrl in Freeplay? I've been curious if you can access and change the multiplier for health gain/loss via Lua. If not, is there any alternative ways to customize how much health you gain/lose?

Try these! I believe they should work!
**setProperty('healthGain', 1)
setProperty('healthLoss', 1)**
