### ISSUE TITLE
stage error

### ISSUE THREAD

**Issue by plotmanlover** [ShadowMario/FNF-PsychEngine#11735]
### Describe your problem here.

i did a copy and paste sooooooooooooo and it keep saying expected near end 'nursejoy  idk  if its just me so i check lua app and it seem to tell me the same
![Lua 1_16_2023 1_13_21 PM](https://user-images.githubusercontent.com/119635880/212744022-3a4fe747-d68f-4a6e-9f02-a43e8b04fe81.png)

What do i do?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

its a copy n  paste from hxs to lua  spript

**Comment by plotmanlover** [comment]
oh and im unable to find  dis

**Comment by CaptainBaldi** [comment]
💀💀💀

**Comment by plotmanlover** [comment]
bruh

**Comment by frantastic24** [comment]
That is not lua

**Comment by plotmanlover** [comment]
ik but  it react the same  thing in the game it somehow still reconize it

**Comment by frantastic24** [comment]
It's not going to work, you can try running the code through `runHaxeCode()`, but as it is it won't run in a script

**Comment by plotmanlover** [comment]
aight so i did an altered way and  it work  i put em together as one png 
ty  for tryna help me yall
