### ISSUE TITLE
Hi, me again

### ISSUE THREAD

**Issue by Toffee-Coffee** [ShadowMario/FNF-PsychEngine#11738]
### Describe your bug here.

so basically, i already charted my song with the vocals and such and saved it in it's own folder in the mods folder, but when i exit chart editor, my song and charting wont load. instead, bopeebo plays, and idk how to fix this
(if it wasnt obvious, this is my first time making a mod)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

added new week, new song/charting, new sprites

**Comment by Toffee-Coffee** [comment]
Okay so I figured the audio part out, but the chart is still resetting

**Comment by HackersLOLwskasdhq3ew** [comment]
Uh did you select the song in the chart menu?

**Comment by Yuta12342** [comment]
Just to make sure things are correct:

Your Chart should be in "mods/data/[song-name]".

To load the chart you are looking for, it either needs to be in a week, or loaded from the Chart Editor directly.

To properly load a song from the chart editor, you need to type the name, and press "Reload JSON".

Note that the Chart Editor will load the chart based on the difficulty of the song you accessed it from, defaulting to "Normal" (No extension) if you used the Main Menu's 7 Menu.

Make sure that you're actually loading the chart, and saved it properly.

**Comment by Toffee-Coffee** [comment]
Alright, thank you, I figured it out
