### ISSUE TITLE
Lua file: hurt note

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#11731]
### What is your question?

How do I make hurt note lua file for psych engine. I don’t know how to make the code

**Comment by HaxLua** [comment]
Read the FREAKING WIKI

**Comment by Ratio-Combinder** [comment]
> How do I make hurt note lua file for psych engine. I don’t know how to make the code


[Example of a Custom Note Type - Instakill Note](https://cdn.discordapp.com/attachments/866856727621795850/903863842763841556/Instakill_Note.zip)

**Comment by NightmaresPlayz** [comment]
Like how to make it into hurt notes

**Comment by CaptainBaldi** [comment]
> Like how to make it into hurt notes. That is instakill
💀 bro doesnt know how to change one value

**Comment by NightmaresPlayz** [comment]
True

**Comment by NightmaresPlayz** [comment]
I dont

**Comment by NightmaresPlayz** [comment]
What value do I change
