### ISSUE TITLE
Issue with dialogue portraits

### ISSUE THREAD

**Issue by SuperWA-HOOMan** [ShadowMario/FNF-PsychEngine#11732]
### Describe your bug here.

I put the image and xml for the dialogue portrait in the mods/images/dialogue folder, but when i try to put it in the dialogue portrait editor, it just stays as bf. For some reason it does show up in the actual dialogue, though. (btw in case it matters im on 0.5.2h)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a few events to the source code

**Comment by CaptainBaldi** [comment]
why would you count this as a bug if you're using 0.5.2?
not our fault you're using an outdated version of the engine
upgrade to 6.3, test it again, if the problem persists, keep this issue open, otherwise, close it

**Comment by SuperWA-HOOMan** [comment]
i dont remember it happening before even on this version but alright, ill try it on the new vesrion
