### ISSUE TITLE
30 fps cap?

### ISSUE THREAD

**Issue by Mitt0** [ShadowMario/FNF-PsychEngine#11736]
### Describe your bug here.

It was fine before but now, when i opened the game, it stays at 30 fps? help?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not much, i just edited the anti spam on PlayState.hx

**Comment by 40U538072** [comment]
Make sure your GPU isn't climbing to 100% usage. That can effect frame rate.

**Comment by Mitt0** [comment]
> Make sure your GPU isn't climbing to 100% usage. That can effect frame rate.

No its not my GPU i think because i checked and my GPU was running fine (15% to 20%~)

**Comment by 40U538072** [comment]
See if your CPU isn't climbing as well. That could also be the issue. If not, see if your ram is climbing more than 75%. Also, do you know how much RAM you have installed?

**Comment by Mitt0** [comment]
> See if your CPU isn't climbing as well. That could also be the issue. If not, see if your ram is climbing more than 75%. Also, do you know how much RAM you have installed?

Oh no wait yeah, thanks
