### ISSUE TITLE
Pls help my game is broken

### ISSUE THREAD

**Issue by BQKK1293018** [ShadowMario/FNF-PsychEngine#11737]
### Describe your bug here.

it shows this every time i launch the game i dont know why the game just doesnt work pls help

C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 318)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 147)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
ModsMenuState.hx (line 733)
ModsMenuState.hx (line 329)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid char 37 at position 0
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMilky** [comment]
im pretty sure its a pack.json problem
show me the pack.json file

**Comment by Ratio-Combinder** [comment]
and rename it to .txt cus github doesn't support .json file from the attachment

**Comment by 40U538072** [comment]
Could be you have deleted the wrong files. The game can't run properly without the right files.
