### ISSUE TITLE
How Do I Compile The Source Code Into A Zip File?

### ISSUE THREAD

**Issue by sans400** [ShadowMario/FNF-PsychEngine#1173]
### What is your question?

How Do I Compile The Source Code Into A Zip File?

**Comment by MayoALT** [comment]
you have to zip it yourself

**Comment by sans400** [comment]
> 
![Screenshot 2021-11-19 122306](https://user-images.githubusercontent.com/78706113/142664918-fc3fd637-6519-4683-8ded-86040e37dccb.png)
i mean like this

**Comment by Micasddsa** [comment]
yea, you have to zip it yourself.
compiling doesn't automatically zip the files.
if you are still confused, idk then

**Comment by HiroOfc** [comment]
u need to select all the build folders/files and then compress it
you will be needing to use WinRAR or 7Zip in some operational systems

**Comment by ShadowMario** [comment]
WinRAR exists 👍

**Comment by sans400** [comment]
> WinRAR exists 👍

ik winRAR exists
