### ISSUE TITLE
Time controlled events

### ISSUE THREAD

**Issue by LukasderCrafter** [ShadowMario/FNF-PsychEngine#11734]
### What is your question?

Hello, i wanted to ask if you can some how do events that run every beat wiht different values.

**Comment by plotmanlover** [comment]
i chart  so if u go to event, add camera zoom and give its  value
value1 is camera on beat
value is the hud on beat
is asking for intensity
![events](https://user-images.githubusercontent.com/119635880/212753356-27db37fa-a576-4947-a5bd-58c16ec72ccc.png)

**Comment by Yuta12342** [comment]
If you're talking about Custom Events, you need to either:

1. Create an Event on every beat with specified values,
or
2. Add an onBeatHit() function that runs whatever values are currently set up on your Custom Event.

**Comment by bruh1cat** [comment]
Function onBeatHit()
if curBeat == 'starting beat' then
triggerEvent('Event name', 'value1', 'value2')
elseif curBeat == 'other beat' then
triggerEvent('Event name', 'value1', 'value2')

**Comment by YoshiGames64** [comment]
> Function onBeatHit() if curBeat == 'starting beat' then triggerEvent('Event name', 'value1', 'value2') elseif curBeat == 'other beat' then triggerEvent('Event name', 'value1', 'value2')

what about the custom events that are required for value 1 or 2 to be leave in blink
