### ISSUE TITLE
Polymod error Help.

### ISSUE THREAD

**Issue by sans400** [ShadowMario/FNF-PsychEngine#11742]
### Describe your problem here.

![Screenshot 2023-01-17 120450](https://user-images.githubusercontent.com/78706113/212999014-15194edd-de10-4974-9d56-18978aacc8ab.png)
Whenever I run the setup.bat file, it can't install Polymod for some reason, any help is appreciated.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Ratio-Combinder** [comment]
polymod isn't used in psych engine
so close this

**Comment by ShadowMilky** [comment]
Polymod is unused in Psych, so for that, use another engine that DOES support Polymod, like Kade and such.
So, please close this.

**Comment by sans400** [comment]
Why the fuck am I so fucking stupid. sorry for wasting time.
