### ISSUE TITLE
BRUH WHY IS MP4HANDER IS FUCKING WRONG IN BUILDWINDOWS PLS FIX IT

### ISSUE THREAD

**Issue by ayedbahan** [ShadowMario/FNF-PsychEngine#11749]
### What is your question?

MP4HANDER TYPE NOT FOUND 
VLC.MP4HANDER TYPE NOT FOUND 
IN PLAYSTATE.HX PLS YOU CAN FIX IT

**Comment by TheKitBoi** [comment]
You capping 
be patient or use
```
haxelib remove hxCodec
haxelib install hxCodec 2.5.1
```

**Comment by pakieFNF** [comment]
> haxelib remove hxCodec
> haxelib install hxCodec 2.5.1

i already did that and still gives me the error wtf

**Comment by pakieFNF** [comment]
still doesn't work for me
