### ISSUE TITLE
Character Editor Autosave

### ISSUE THREAD

**Issue by helpimbadatusernames** [ShadowMario/FNF-PsychEngine#11745]
### What feature do you want to get added on the **base** engine?

If the game crashes in the Character Editor it should autosave from time to time so progress wont be lost

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Jevilm** [comment]
Load autosave on the chart editor be like

**Comment by Jevilm** [comment]
> > Load autosave on the chart editor be like
> 
> they mean the character editor, not the chart editor

oh i cant read

**Comment by Jevilm** [comment]
anyway an autosave feature would be pretty cool on the chart editor
me approved 👍
