### ISSUE TITLE
I edited a mod but now don't work

### ISSUE THREAD

**Issue by JuliabLucianowinowsfan** [ShadowMario/FNF-PsychEngine#11744]
### Describe your bug here.

I edited some files of the Sky mod but now doesn't work and the background keep flashing
![IMG_20230117_183037882](https://user-images.githubusercontent.com/99436234/213020735-406f464b-a8b3-4790-bc76-256f5c6ada83.jpg)
![IMG_20230117_183246024](https://user-images.githubusercontent.com/99436234/213020738-23624310-b000-4316-bfd5-b978aebe9161.jpg)

![IMG_20230117_183649223_HDR](https://user-images.githubusercontent.com/99436234/213020728-922701b2-41e3-48a1-95d0-04faccbcc7b6.jpg) I don't know if it's Lua or source but I saw some Lua files so I guess it's lua

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited the Dialogues and some pics

**Comment by JuliabLucianowinowsfan** [comment]
Also the Character editor or the chart editor doesn't work and the game is frozen (Except for the background), I can't open the Pause menu  I only can close the game.

**Comment by 40U538072** [comment]
You can't edit files of an existing mod without damaging the property. Instead, you would have to port the files one by one and port your own characters. If chart editor crashes, the Test.json file is missing and need to run that file in order to access the song properly. Could also be you either edited some or remove the characters json files and will not load properly. Can also be because the code doesn't match the png or xml data, which would explain why the character freezes and doesn't move at all. Let me know if any of this fixes any of the problems.

**Comment by JuliabLucianowinowsfan** [comment]
> You can't edit files of an existing mod without damaging the property. Instead, you would have to port the files one by one and port your own characters. If chart editor crashes, the Test.json file is missing and need to run that file in order to access the song properly. Could also be you either edited some or remove the characters json files and will not load properly. Can also be because the code doesn't match the png or xml data, which would explain why the character freezes and doesn't move at all. Let me know if any of this fixes any of the problems.
> 
> Basically, be careful of the files you edit or remove in the game or mod you are editing.

I also edited the Boyfriend Pics and run normal

**Comment by 40U538072** [comment]
Editing that file is risky and could be the reason why the game is bugging out. You will have to create the character yourself and make a separate json file for the character.

**Comment by JuliabLucianowinowsfan** [comment]
I will send you a video file of a normal level and Character editor by Drive.

**Comment by 40U538072** [comment]
Okay. Let me know what you have it.

**Comment by JuliabLucianowinowsfan** [comment]
Here's the Character editor one 
https://drive.google.com/file/d/1i67yE-9RtLQdgwlZwQHWBD2BczbfUGHG/view?usp=drivesdk

**Comment by JuliabLucianowinowsfan** [comment]
I didn't did Pre-attack,Attack, Dodge or hurt cuz they don't appear in the game and I didn't want to lose time

**Comment by 40U538072** [comment]
The character editor looks okay to me? is there something I'm missing?

**Comment by JuliabLucianowinowsfan** [comment]
Heres the normal level 
https://drive.google.com/file/d/1i6ikARbfz4Z5Il1Rpp_mkkVCa8skj1z5/view?usp=drivesdk

**Comment by 40U538072** [comment]
Really don't see anything out of the ordinary. I am not sure if I have the right information yet. Anything else I can look into?

**Comment by JuliabLucianowinowsfan** [comment]
When I play the Mod song in FreePlay It plays

**Comment by JuliabLucianowinowsfan** [comment]
But no dialogue

**Comment by 40U538072** [comment]
From what I could tell, everything seems to run fine. You have said something about dialogue. I don't think there is supposed to be dialogue in the song you are playing.

**Comment by JuliabLucianowinowsfan** [comment]
Explain the Second Pic, Where is a Json File dialogue

**Comment by JuliabLucianowinowsfan** [comment]
Here's a picture of BF Icon in "Dead status"

**Comment by JuliabLucianowinowsfan** [comment]
Here's a pic of BF Icon "Dead status" 
![IMG_20230117_194845924](https://user-images.githubusercontent.com/99436234/213029353-bf4e2ae2-0b56-478c-bac4-e987fffedd1f.jpg)

**Comment by 40U538072** [comment]
Dialogue will not play in Freeplay unless you have a special code. Don't know what though. The dead status image looks fine from here.

**Comment by JuliabLucianowinowsfan** [comment]
I think I found the problem here on Dialogue editor...

**Comment by JuliabLucianowinowsfan** [comment]
![Uploading IMG_20230117_202251338.jpg…]()

**Comment by JuliabLucianowinowsfan** [comment]
Here
![IMG_20230117_202251338](https://user-images.githubusercontent.com/99436234/213034226-e13f65e9-b7e8-442a-93f6-a4a675f4b6c2.jpg)

**Comment by JuliabLucianowinowsfan** [comment]
The problem is on the wife-forever song

**Comment by JuliabLucianowinowsfan** [comment]
Ok I fixed now let's check

**Comment by 40U538072** [comment]
Sorry if I didn't answer for a while, but lets see if it is fixed now.

**Comment by JuliabLucianowinowsfan** [comment]
Bruh I'm dumb I fixed it but I didn't save it

**Comment by JuliabLucianowinowsfan** [comment]
See it by yourself ;)
https://drive.google.com/file/d/1iCeBHDnJXnxlzhiqZcQOOaUzJjkmSvMl/view?usp=drivesdk

**Comment by 40U538072** [comment]
Nice to hear the solution was found.
