### ISSUE TITLE
character still shows up

### ISSUE THREAD

**Issue by Steve35117** [ShadowMario/FNF-PsychEngine#11743]
### Describe your bug here.

so, whenever i wanna change characters mid song, the previous character is still there. how can i change this?
![Whitty corruption'_ The last hope  17 01 2023 21_08_35](https://user-images.githubusercontent.com/95169213/213001594-c3efe670-0899-4c6c-88fd-f804cdb03180.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

actually everything but everything was fine until this bs

**Comment by Steve35117** [comment]
the characer behind whitty isnt supposed to show up

**Comment by 40U538072** [comment]
There is an event in the chart that changes the character or there are special arrows that assign to alt animations. Edit or remove any of these and that should fix it. If it doesn't, the mod the you are editing, if you are editing an existing mod, is hard coded and there is not much you can do about it.
