### ISSUE TITLE
The Null Object Thing

### ISSUE THREAD

**Issue by hdfhdsajd** [ShadowMario/FNF-PsychEngine#11741]
### Describe your problem here.

i tried to load a chart from Vs Impostor V4 (pretty much has been happening a while when i tried to load other custom charts) and this just pops up:

Note.hx (line 158)
editors/ChartingState.hx (line 2683)
editors/ChartingState.hx (line 2642)
editors/ChartingState.hx (line 2156)
editors/ChartingState.hx (line 2460)
editors/ChartingState.hx (line 1561)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

im probably stupid but idk how to fix it and i need help lol
any kind of help would be great

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Grape-Boy** [comment]
something wrong with note types, maybe the chart has a note type that you haven't added yet

**Comment by TWgames2020** [comment]
You don't use charts from there! The authors have put all sorts of different things there and it can't be transferred so easily! Search the Internet for alterations to the original engine. I recommend it: https://gamebanana.com/mods/422721   The man did a good job. Also used and everything is fine
