### ISSUE TITLE
what did i do wrong???

### ISSUE THREAD

**Issue by idk479** [ShadowMario/FNF-PsychEngine#11755]
### Describe your problem here.

i was trying to make a health percentage under my modified health bar and...
![Screenshot (195)](https://user-images.githubusercontent.com/122388966/213694335-489db696-5d46-4de3-84b6-755db26c59d7.png)

here is the script

function onCreate()
    makeLuaText('healthText', ' ' .. math.floor(getProperty("health") * 50), 300, screenWidth / 2 - 300 / 2, screenHeight / 2 - 300 / 1.5, x:-740, y:420)
    addLuaText('healthText')
    setTextSize('healthText', 30);
end
function onUpdate(elapsed)
    setTextString('healthText', ' ' .. math.floor(getProperty("health") * 50))
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
remove :x and :y

**Comment by Ratio-Combinder** [comment]
there's yo fix
```
function onCreate()
    makeLuaText('healthText', ' ' .. math.floor(getProperty("health") * 50), 300, screenWidth / 2 - 300 / 2, screenHeight / 2 - 300 / 1.5, -740, 420)
    addLuaText('healthText')
    setTextSize('healthText', 30);
end

function onUpdate(elapsed)
    setTextString('healthText', ' ' .. math.floor(getProperty("health") * 50))
end
```

**Comment by idk479** [comment]
k thanks
