### ISSUE TITLE
Lock Difficulty per Week

### ISSUE THREAD

**Issue by glitchygmr** [ShadowMario/FNF-PsychEngine#1175]
### Describe your problem here.

I made a custom difficulty (suffix -b) but i dont want it to be used in some weeks. how would i make it so certain weeks/songs dont have that difficulty as an option?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added a new Difficulty, suffix -b.

**Comment by PDL2CGamejolt** [comment]
idk

**Comment by DEV-idiotXD** [comment]
> ### Describe your problem here.
> I made a custom difficulty (suffix -b) but i dont want it to be used in some weeks. how would i make it so certain weeks/songs dont have that difficulty as an option?
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> Added a new Difficulty, suffix -b.

like in vs shaggy? where if u dont choose canon it will hide some songs?
