### ISSUE TITLE
my song won't load

### ISSUE THREAD

**Issue by aydenxml123456** [ShadowMario/FNF-PsychEngine#11754]
### Describe your problem here.

i count get a instmentral for my song so i used the same song for the game but when i went to play the song i got an error

C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
FreeplayState.hx (line 371)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/ayden-the-cool/ayden-the-cool.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

please help!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

**Comment by frantastic24** [comment]
Missing chart

**Comment by aydenxml123456** [comment]
thank you it worked

**Comment by milkyanimates398** [comment]
?

**Comment by TheKitBoi** [comment]
Close this issue
