### ISSUE TITLE
(CLOSED) Need help with lua

### ISSUE THREAD

**Issue by Paintman5001** [ShadowMario/FNF-PsychEngine#11750]
### Describe your problem here.

I'm trying to make a Lua script so when you press a series if keys it loads a new song.
here's what I tried

function onUpdate()
if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.H') then ('flixel.FlxG', 'keys.justPressed.I') then
loadSong('example')
end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by TheKitBoi** [comment]
https://gamebanana.com/tuts/15313

**Comment by Paintman5001** [comment]
> the code you did looks so wrong so this link will help you https://gamebanana.com/tuts/15313

thank you ill try it

**Comment by Paintman5001** [comment]
> the code you did looks so wrong so this link will help you https://gamebanana.com/tuts/15313

hello i need some help with some more lua if you can help with it then thats amazing heres the code 

function onGameOverEnd()
local bfdedlol = true;
	if tag =='bfdedlol' then		--no legit way to crash psych engine sadly.
		exitSong();
	end
	if tag == 'Stop' then
        missPenalty=false;
end
end
