### ISSUE TITLE
Im Doing this and something is wrong

### ISSUE THREAD

**Issue by eAntivisurus** [ShadowMario/FNF-PsychEngine#11756]
### Describe your problem here.

```
C:\Users\LEO\Downloads\FNF-PsychEngine-main\FNF-PsychEngine-main>lime test windows
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1573: characters 13-23 : Type not found : MP4Handler
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
use this
```
haxelib remove hxCodec
haxelib install hxCodec 2.5.1
```

**Comment by eAntivisurus** [comment]
C:\Users\LEO\Downloads\FNF-PsychEngine-main\FNF-PsychEngine-main>lime test windows
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\LEO\Downloads\FNF-PsychEngine-main\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by eAntivisurus** [comment]
C:\Users\LEO\Downloads\FNF-PsychEngine-main\FNF-PsychEngine-main>lime test windows
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\LEO\Downloads\FNF-PsychEngine-main\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

Thats i got

**Comment by eAntivisurus** [comment]
> use this
> 
> ```
> haxelib remove hxCodec
> haxelib install hxCodec 2.5.1
> ```

```
C:\Users\LEO\Downloads\FNF-PsychEngine-main\FNF-PsychEngine-main>lime test windows
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\LEO\Downloads\FNF-PsychEngine-main\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
```

**Comment by Grape-Boy** [comment]
#10756 maybe this could help
