### ISSUE TITLE
Psych engine, or any engine in particular doesn't work now. I don't know what's wrong. It worked 1 month ago. I didn't change anything.

### ISSUE THREAD

**Issue by sans400** [ShadowMario/FNF-PsychEngine#11751]
### Describe your problem here.

![Screenshot 2023-01-19 114034](https://user-images.githubusercontent.com/78706113/213512336-3bd11597-5678-4044-a5b5-828a3c57a69a.png)
I have tried solution after solution, and nothing worked, I don't know what to do.
Please help me.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheKitBoi** [comment]
replace main.hx with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

and use
```
haxelib remove hxCodec
haxelib install hxCodec 2.5.1
```

**Comment by sans400** [comment]
Thank you so fricking much!

**Comment by PDL2CGamejolt** [comment]
what a cool looking thing!
