### ISSUE TITLE
how do i fix my song wont load here is the error

### ISSUE THREAD

**Issue by milkyanimates398** [ShadowMario/FNF-PsychEngine#11765]
### Describe your problem here.

C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
editors/ChartingState.hx (line 2957)
editors/ChartingState.hx (line 434)
Prompt.hx (line 44)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/dlow/dlow.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
Missing chart
add the dlow.json

**Comment by milkyanimates398** [comment]
can't find it

**Comment by TheKitBoi** [comment]
The add the chart

**Comment by TWgames2020** [comment]
You don't have chart to song, just copy chart from dad battle or other chart and put in folder with name of the song (or any name but you need write in chart right song name, for this open chart with Visual Studio Code and go to end and change song name on your song ;) ) If you want make your chart put copied file in folder rename your json file, open FNF and open chart editor in debug menu, type your chart name and clear old strum list and you can begin chart!

But if you want use other chart just move chart folder to your project.
