### ISSUE TITLE
Need help with Lua tweening

### ISSUE THREAD

**Issue by Zer0PXL** [ShadowMario/FNF-PsychEngine#11766]
### Describe your problem here.

Is there a limit to how many commands you can run in one if statement? The code I wrote tweens 7 things at once, but only 5 work...

Code:
function onStepHit()       
----if curStep == 34 then      
--------noteTweenAlpha("NoteMove1", 0, 0, 0.5, cubeInOut)
--------noteTweenAlpha("NoteMove2", 1, 0, 0.5, cubeInOut)
--------noteTweenAlpha("NoteMove3", 2, 0, 0.5, cubeInOut)
--------noteTweenAlpha("NoteMove4", 3, 0, 0.5, cubeInOut)
--------doTweenAlpha(helf, "healthBar", 0, 0.5, cubeInOut)
--------doTweenAlpha(ican, "iconP2", 0, 0.5, cubeInOut)
--------doTweenAlpha(txt, "scoreTxt", 0, 0.5, cubeInOut)
----end     
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment]
The last three tags aren't strings

**Comment by Zer0PXL** [comment]
it worked, but the scoretext tween worked even with the missing string... why did the icon and healthbar not work? thanks, anyway

**Comment by frantastic24** [comment]
Because all three return the same tag, so the last one overrides the other 2
