### ISSUE TITLE
How to change Discord RPC Icon

### ISSUE THREAD

**Issue by TheLegion00** [ShadowMario/FNF-PsychEngine#11760]
### Describe your problem here.

In Discord.hx where does `largeImageKey: 'icon'` draw the icon file from?
I'm just curious as I've scoured the source files and cant find where its getting the Psych Engine logo image from.
![image](https://user-images.githubusercontent.com/103993637/213842605-6b67e0e4-82a4-4647-ac43-0dad0675218b.png)

Thanks in advance!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Currently editing Discord RPC

**Comment by impostor5875** [comment]
it gets it from psych's discord application

you can make your own by going to the [discord developer portal](https://www.discord.com/developers) and making a new application. there, you can change the name (you don't need to change the profile picture, as that won't change anything in the rich presence) and get the application id. the application id is a thing you'll need to replace in line 20 of discord.hx.
after replacing that, go back to the discord developer portal and go to the rich presence tab. near the bottom, you can add images. add the image for your icon and rename it to "icon" (you can't change it later, so if you misspell it you'll have to delete it and re-add it. also discord caching is kinda goofy so it'll "stay" there for a while after deleting it)

and there you added your goofy icon to the rich presence
