### ISSUE TITLE
trying to add a mod pack

### ISSUE THREAD

**Issue by jjprnk** [ShadowMario/FNF-PsychEngine#11769]
### Describe your problem here.

I was trying to put in the Buffet Night Burstin' mod pack but no matter what I do, I can never get it to work. it's either it's on but nothings happening or an error screen 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by braydenthesquirtle** [comment]
Could you attach your PsychEngine folder as a .zip file?

**Comment by fnfporterhi** [comment]
how i added my mod pack: used the default characters, and added some of the icons for the characters for the songs (ex.matt) by putting the images into the mods/images folder
