### ISSUE TITLE
Is there a way to move Girlfriend mid song?

### ISSUE THREAD

**Issue by NavaGaming** [ShadowMario/FNF-PsychEngine#11764]
### Describe your problem here.

Is there a way to move Girlfriend mid song?
like using some kind of `setProperty("girlfriend.x", 2700)` or something idk

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Drawoon2** [comment]
`setProperty("gf.x", 2700)` This is the correct tag

**Comment by biomseed** [comment]
You can also use tweens to move her smoothly.
