### ISSUE TITLE
How does the source code check the keyboard pressed and unpressed?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#1176]
### What is your question?

I want to know when I play the game, when I press the left/right/up/down key of the keyboard, how does  the source code get the key information. I don't find the specific source code. Where are they?

**Comment by ShadowMario** [comment]
`controls.NOTE_LEFT, controls.NOTE_DOWN, controls.NOTE_UP, controls.NOTE_RIGHT`, if you want the specific keys pressed on the keyboard you can use `FlxG.keys.justPressed.A` for example (This will check if you pressed A)

[List of keys](https://api.haxeflixel.com/flixel/input/keyboard/FlxKey.html)
[List of FlxG.keys functions](https://api.haxeflixel.com/flixel/input/FlxKeyManager.html)
