### ISSUE TITLE
custom game over on source

### ISSUE THREAD

**Issue by Robert124l** [ShadowMario/FNF-PsychEngine#11771]
### Describe your problem here.

Hello, I have a question and it is: how can I do a custom gameover? I know there is a script or also the code of week 6 and 7, but it doesn't work for me. I would like to do a game over similar to insomnia (lullaby mod). I know it's in the source code but I don't know how to program it, the source of that mod is very different from the psych xd, but hey, if someone knows please help me.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i try to edit in gameoversubstate but idk why it doesn't work.

**Comment by IdiotLimitedEdition** [comment]
Somewhere Inside the update function
```hx
if(Playstate.SONG.song == 'Insomnia')//Inside GameOverSubstate.hx btw
Playstate.startVideo('name');
```
Or something in the lines of that. You can check the week 7 code at around line 118

**Comment by Robert124l** [comment]
> Somewhere Inside the update function
> 
> ```hx
> if(Playstate.SONG.song == 'Insomnia')//Inside GameOverSubstate.hx btw
> Playstate.startVideo('name');
> ```
> 
> Or something in the lines of that. You can check the week 7 code at around line 118

Thanks, i will try it

**Comment by Robert124l** [comment]
> Somewhere Inside the update function
> 
> ```hx
> if(Playstate.SONG.song == 'Insomnia')//Inside GameOverSubstate.hx btw
> Playstate.startVideo('name');
> ```
> 
> Or something in the lines of that. You can check the week 7 code at around line 118

sorry but isn't work. does not load the video, only the game over default

**Comment by Robert124l** [comment]
update, now it's work but aa, dosen't stop to reproduce again and again, also i have to put this code to work (
if (PlayState.SONG.song == 'song')
				{
					startVideo('gameover test');
}

**Comment by Ratio-Combinder** [comment]
is the song the 'name of the song'

**Comment by Robert124l** [comment]
> is the song the 'name of the song'

Yes, but even if I put .stage directly, it doesn't work
