### ISSUE TITLE
An option to add unique text sounds for characters

### ISSUE THREAD

**Issue by Ali-Nothing-Creative** [ShadowMario/FNF-PsychEngine#1177]
### What feature do you want to get added on the base engine?

What if the Dialogue Portrait Editor let you give each character a unique "text typing" sound instead of always using the default?
Here's a quick mockup I made in GIMP of what it would look like:
![rngijernge](https://user-images.githubusercontent.com/66648090/142671672-7519a055-4702-4abe-97b7-d4d285d02977.png)

**Comment by HiroOfc** [comment]
maybe an issue that looks like #332
