### ISSUE TITLE
can't compile anymore

### ISSUE THREAD

**Issue by MMalkeZ** [ShadowMario/FNF-PsychEngine#11772]
### Describe your problem here.

showing this error:

![image](https://user-images.githubusercontent.com/108292251/213895394-ff49bbbb-c557-48bb-9911-08a58d5d70ba.png)

after this (apparently):

![image](https://user-images.githubusercontent.com/108292251/213895483-9867863d-da41-484d-a29d-444991c499ce.png)

i dont have much information since this is happening with a friend, not me (he shy to ask for help uwu)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing in the source

**Comment by TheKitBoi** [comment]
Replace Main.hx with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

**Comment by MMalkeZ** [comment]
ty
