### ISSUE TITLE
issue with source compiling

### ISSUE THREAD

**Issue by JulianGeckoWasp** [ShadowMario/FNF-PsychEngine#11776]
### Describe your problem here.

when compiling the source version of PE, I get this error.

source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler

can anyone help fix?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheKitBoi** [comment]
Replace Main.hx with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

And use
```
haxelib remove hxCodec
haxelib install hxCodec 2.5.1
```

**Comment by JulianGeckoWasp** [comment]
> 

thanks for the help. i tried and now theres a different error:

source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\me\Downloads\FNF-PsychEngine-0.6.3\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by DisIsNOt** [comment]
install vsc 2019 burj

**Comment by JulianGeckoWasp** [comment]
Alright, I fixed it.
I had to reinstall visual studio. (2017 version)
