### ISSUE TITLE
Why does FlxColor not work through Hscript

### ISSUE THREAD

**Issue by CaptainBaldi** [ShadowMario/FNF-PsychEngine#11777]
### Describe your problem here.

So I'm trying to use FlxColor, but whenever I try to set an object's color, I always get an error reading "Invalid access to field" + whatever color im trying to use
![image](https://user-images.githubusercontent.com/86160807/214051913-80696283-c836-427c-b0f0-f019b91755e3.png)
this also happens when trying to use any function from FlxColor, and similar errors occur when trying to use other libraries, like FlxTextBorderStyle
 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by sayofthelor** [comment]
it's an abstract, abstracts are converted into their raw values at compile time so at runtime FlxColor doesn't exist

**Comment by CaptainBaldi** [comment]
ah ok, thanks for the answer

**Comment by sayofthelor** [comment]
also for all abstracts you can just sub them for the raw values, which you can find at the API page, like here: https://api.haxeflixel.com/flixel/util/FlxColor.html
