### ISSUE TITLE
the engine can't compile, need help

### ISSUE THREAD

**Issue by 3zoosE** [ShadowMario/FNF-PsychEngine#11773]
### Describe your bug here.

it seems i can't compile because there is a problem, i tried changing the version of haxe, installing the libraries as i was told
but it didn't work, it is telling me this:
`obj\msvc19-arm64-nc\70e38311_Context3DElementType.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'ARM64'`

any help would be appreciated in any way

### Command Prompt/Terminal logs (if existing)

```bash
obj\msvc19-arm64-nc\70e38311_Context3DElementType.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'ARM64'
```

### Are you modding a build from source or with Lua?

source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, ever since i finished installing libraries, i immediately started compiling.

**Comment by Jevilm** [comment]
that is a VERY weird error
