### ISSUE TITLE
I want a week to include an extra song on certain difficulties

### ISSUE THREAD

**Issue by ScarabWasTaken** [ShadowMario/FNF-PsychEngine#11770]
### Describe your problem here.

Essentially I want a script that loads a song at the end of another song.
I want to queue up a song when played in story mode on certain difficulty settings only. Sort of like Sonic EXE's Faker. Though i havent been able to find a port that includes Faker and queues up the next song with a script.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheKitBoi** [comment]
edit the number on how many difficulty are there
`if difficulty = 2 then`

**Comment by ScarabWasTaken** [comment]
That wasnt my question

**Comment by CaptainBaldi** [comment]
```
function onEndSong()
       if difficulty == 2 then
               loadSong('song', difficulty)
       end
       return Function_Stop
end
```

**Comment by ScarabWasTaken** [comment]
Thanks this was exactly what I needed
