### ISSUE TITLE
Random Bugs and IDK the reason why

### ISSUE THREAD

**Issue by InfernoBrighton** [ShadowMario/FNF-PsychEngine#11779]
### Random Bugs Happening And IDK Why

GF doesn't pop up and comes up in black squares BUT in some other songs she does show up?!
One song I play works but then the other doesn't and kicks me out of my mod. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Not a bug
Your graphics card is too weak

**Comment by InfernoBrighton** [comment]
> Not a bug Your graphics card is too weak

so would it be fine for other people to play?

**Comment by frantastic24** [comment]
If their PC is decent enough yes

**Comment by InfernoBrighton** [comment]
> If their PC is decent enough yes

im on a laptop and I didn't expect this bug to happen because it's a pretty decent laptop

**Comment by frantastic24** [comment]
I just said it's not a bug and if your PC is decent you may want to either look into driver updates or a refund
