### ISSUE TITLE
OS Engine build error

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#11784]
### Describe your bug here.

I once changed the "MP4Handler" to "VideoHandler" because it said that "MP4Handler" was not found. NOW IT'S SAYING THAT VIDEOHANDLER IS NOT FOUND! Help....

### Command Prompt/Terminal logs (if existing)

```bash
source/PlayState.hx:75: characters 8-20 : Type not found : VideoHandler
source/PlayState.hx:1762: characters 13-25 : Type not found : VideoHandler
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I used both Source and Lua to make the mod (On OS Engine)

**Comment by TheKitBoi** [comment]
people are gonna hate you on why you made an issue from os engine but

revert VideoHandler to MP4Handler
and use 
```
haxelib remove hxCodec
haxelib install hxCodec 2.5.1
```

**Comment by PDL2CGamejolt** [comment]
> people are gonna hate you on why you made an issue from os engine but
> 
> revert VideoHandler to MP4Handler and use
> 
> ```
> haxelib remove hxCodec
> haxelib install hxCodec 2.5.1
> ```

OS engine's issues are closed since the repo is archived

**Comment by PDL2CGamejolt** [comment]
Also, I use the GitHub actions.

**Comment by PDL2CGamejolt** [comment]
![image](https://user-images.githubusercontent.com/94698464/214448378-6f7d0e3a-f0bd-4027-b147-e4bf102a749d.png)

**Comment by PDL2CGamejolt** [comment]
@TheKitBoi I have a problem. It didn’t work and it still says that it doesn’t exist

**Comment by PDL2CGamejolt** [comment]
HELLLPLPLPLPLPL

**Comment by PDL2CGamejolt** [comment]
Help me.

**Comment by PDL2CGamejolt** [comment]
![image](https://user-images.githubusercontent.com/94698464/214727918-edc5c58d-df85-4844-8477-424dfe803d30.png)
@TheKitBoi I changed it back to VideoHandler, but it STILL DOESN'T FRICKIN' WORK!

**Comment by CrusherNotDrip** [comment]
> OS engine's issues are closed since the repo is archived

that doesn't mean psych engine is the new os engine discussions though
just sayin

**Comment by PDL2CGamejolt** [comment]
WHERE ELSE AM I SUPPOSED TO PUT THE ISSUES FOR OS ENGINE?

**Comment by CaptainBaldi** [comment]
maybe on gamebanana?????

**Comment by Ratio-Combinder** [comment]
there made a pr for ur fix
https://github.com/PDL2CGamejolt/FNFPaytenEditionNEW/pull/2
