### ISSUE TITLE
Can a custom note be a gif ?

### ISSUE THREAD

**Issue by Mokona5901** [ShadowMario/FNF-PsychEngine#1178]
### What is your question?

Can a custom note be a gif ?

**Comment by Steviegt6** [comment]
No. You could do some source modding to *maybe* get one to display; I would recommend using atlases with specified animation frames as an alternative.

**Comment by RoseJessX** [comment]
It can, though you have to convert it into a valid spritesheet format manually.

**Comment by ShadowMario** [comment]
Haxe doesn't support GIFs.
