### ISSUE TITLE
is there a way to crash the game after gameover cutscene

### ISSUE THREAD

**Issue by LodedRick** [ShadowMario/FNF-PsychEngine#11782]
### Describe your problem here.

im trying to make the game crash after game over cutscene 
im using this code right here

function onGameOver()
    startVideo('lose'); 
         return Function_Continue;
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheKitBoi** [comment]
runHaxeCode([[
		System.exit(0);
		]])

**Comment by LodedRick** [comment]
> runHaxeCode([[ System.exit(0); ]])

doesn't work 
i can use os.exit and it works tho idk where to put it 
when i put it before return function it crashes immediately and if before the script doesnt work

**Comment by TheGithubPsychEngineFan** [comment]
> 

You have to add addHaxeLibrary("System", "lime.system")
