### ISSUE TITLE
how to make the screen look pixelated?

### ISSUE THREAD

**Issue by TacoGH** [ShadowMario/FNF-PsychEngine#11783]
### Describe your problem here.

how do you make the whole screen look pixelate?

for exmaple like this (this screenshot is on yoshicrafter):
![image](https://user-images.githubusercontent.com/98825505/214412660-08bb0b5e-33d5-4b31-b07b-f4dd7ba42686.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No i didnt change anything

**Comment by TheKitBoi** [comment]
runHaxeCode([[
FlxG.scaleMode.width = 640;
FlxG.scaleMode.height = 360;
]])
