### ISSUE TITLE
Mp4 error

### ISSUE THREAD

**Issue by Montymations** [ShadowMario/FNF-PsychEngine#11792]
### Describe your problem here.

I need help because my engine gave me this error message.

source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1573: characters 13-23 : Type not found : MP4Handler

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i haven't modified anything past adding songs and charts

**Comment by TheKitBoi** [comment]
use
```
haxelib remove hxCodec
haxelib install hxCodec 2.5.1
```

**Comment by KirbyKid256** [comment]
They changed the name and location of MP4Handler in hxCodec.
If you're using the latest hxCodec (currently 2.6.1), at line 75, replace `import vlc.MP4Handler;` with `import hxcodec.VideoHandler;`.
And at line 1573, replace `var video:MP4Handler = new MP4Handler();` with `var video:VideoHandler = new VideoHandler();`

**Comment by AstroGamesIndie** [comment]
it doesn't work to me

**Comment by TheKitBoi** [comment]
> it doesn't work to me

did you even try
show the code

**Comment by ZMIXR4** [comment]
AAAHHHH I HATE THIS I GOT THE MESSAGE source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1573: characters 13-23 : Type not found : MP4Handler

**Comment by TheKitBoi** [comment]
> AAAHHHH I HATE THIS I GOT THE MESSAGE source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler source/PlayState.hx:1573: characters 13-23 : Type not found : MP4Handler

did you do
```
haxelib remove hxCodec
haxelib install hxCodec 2.5.1
```

**Comment by ManuArtXD** [comment]
> They changed the name and location of MP4Handler in hxCodec. If you're using the latest hxCodec (currently 2.6.1), at line 75, replace `import vlc.MP4Handler;` with `import hxcodec.VideoHandler;`. And at line 1573, replace `var video:MP4Handler = new MP4Handler();` with `var video:VideoHandler = new VideoHandler();`

On what file am i supposed to do that?
Sorry if the question is kinda stupid, im just new to this

**Comment by gummycyanyt** [comment]
Same issue, but the script is import hxcodec.flixel.FlxVideo;
import flixel.FlxG; It gives an error which says "ERROR ON LOADING: mods/callioushuck/scripts/PlayVideo.hx:7: Type not found : hxcodec.flixel.FlxVideo"
