### ISSUE TITLE
Arrow bug

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#11794]
### Describe your bug here.

The splashes are purple (all of them) and they stay on the arrows for the entire song and I can’t get rid of them

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Ratio-Combinder** [comment]
send the image and the xml in a zip

**Comment by frantastic24** [comment]
Not a bug
You messed up the animation names

**Comment by NightmaresPlayz** [comment]
I fixed it nevermind
