### ISSUE TITLE
A question about .frag Shaders

### ISSUE THREAD

**Issue by fatalvoid** [ShadowMario/FNF-PsychEngine#11791]
### What is your question?

Is there any way to activate or disable a .frag shader via Events? If so how can I do it?

**Comment by CaptainBaldi** [comment]
initLuaShader, setSpriteShader and removeSpriteShader

**Comment by PumpkinSheee** [comment]
> initLuaShader, setSpriteShader and removeSpriteShader

yo and how could i write that into a script? everytime i use them i get an error but thats most likely since i suck at lua

**Comment by MemeHovy** [comment]
> > initLuaShader, setSpriteShader and removeSpriteShader
> 
> yo and how could i write that into a script? everytime i use them i get an error but thats most likely since i suck at lua

look at the wiki and learn to do it yourself, you gotta learn somehow

**Comment by PumpkinSheee** [comment]
> > > initLuaShader, setSpriteShader and removeSpriteShader
> > 
> > 
> > yo and how could i write that into a script? everytime i use them i get an error but thats most likely since i suck at lua
> 
> look at the wiki and learn to do it yourself, you gotta learn somehow

fair enough
