### ISSUE TITLE
Alternate MP4Handler Fix with hxCodec 2.6.1

### ISSUE THREAD

**Issue by KirbyKid256** [ShadowMario/FNF-PsychEngine#11798]
### What feature do you want to get added on the **base** engine?

This is an extremely easy fix where you have to replace `import vlc.MP4Handler;` with `import hxcodec.VideoHandler;` and any instance of "MP4Handler" with "VideoHandler".
You don't need to keep hxCodec 2.5.1, especially when the current version (2.6.1) has additional features, such as macOS support. I tested it in my Lunar Engine fork, and it works well.
[hxCodec (2.6.1)](https://lib.haxe.org/p/hxCodec/)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by TheKitBoi** [comment]
There's a pr in the works but it's WIP
https://github.com/ShadowMario/FNF-PsychEngine/pull/11720

**Comment by polybiusproxy** [comment]
hxCodec creator here,

Why not use the latest version (v2.6.1)?
It may require changing the code but it's worth it considering the new changes made to the library.

**Comment by BeastlyGabi** [comment]
it has been fixed

**Comment by KirbyKid256** [comment]
> it has been fixed

Yes, but this fix would also allow videos to play on macOS. HxCodec 2.5.1 doesn't support macOS.

**Comment by BeastlyGabi** [comment]
> > it has been fixed
> 
> Yes, but this fix would also allow videos to play on macOS. HxCodec 2.5.1 doesn't support macOS.

I meant that it was already updated on the latest psych version
