### ISSUE TITLE
Changeable global scripts folder

### ISSUE THREAD

**Issue by BlueColorsin** [ShadowMario/FNF-PsychEngine#11796]
### READ THIS, I CAN'T GET A BETTER TITLE IDEA
so what do I mean by global scripts folder?

what I mean is a changeable file location for the scripts folder so for all of your psych installations you can still use the same scripts without even needing to drag all of your scripts to the folder 
it will just already be there

and ofc you would be able to turn it off in settings but tbh I could see this as a really good way for people who use psych engine
though why would you have more then 1 psych installation?

simple 
Source code mods, source code mods OR better yet mods partly made in source and lua tend to need there own .exe to work
so instead of needing to drag everything in there it will be already be there 

### how would this work?
simple change the path of the folder where it looks for scripts to whatever the player choses in the options menu 👍

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Lorekeeper49** [comment]
If you make a scripts folder in `mods/`---just `mods/` not `mods/modpack/`---the scripts inside will be global for all the mod packs within.
