### ISSUE TITLE
Add ability to enter arrow mode in Chart Editor

### ISSUE THREAD

**Issue by J0nathan550** [ShadowMario/FNF-PsychEngine#11795]
### What feature do you want to get added on the **base** engine?

Hello, in Chart editor, there is ability to add notes by pressing 1-2-3-4 (player), 5-6-7-8(enemy) keys, can you add ability to do the same but with help of WASD keys or Arrow Keys? 

You can add special key combination to enter that mode, or button where charting and music start playing, and by pressing arrow or WASD keys, you can type the note you like. 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by CaptainBaldi** [comment]
1. you failed the test
2. this idea sucks

**Comment by TheKitBoi** [comment]
> ### What feature do you want to get added on the **base** engine?
> Hello, in Chart editor, there is ability to add notes by pressing 1-2-3-4 (player), 5-6-7-8(enemy) keys

ok Kade engine user

**Comment by ShadowMilky** [comment]
> ### What feature do you want to get added on the **base** engine?
> Hello, in Chart editor, there is ability to add notes by pressing 1-2-3-4 (player), 5-6-7-8(enemy) keys

i dont think psych has that, kade user

**Comment by J0nathan550** [comment]
> > ### What feature do you want to get added on the **base** engine?
> > Hello, in Chart editor, there is ability to add notes by pressing 1-2-3-4 (player), 5-6-7-8(enemy) keys
> 
> i dont think psych has that, kade user

Try to go to Chart Editor, enable Vortex Mode and start to press keys, bozo

**Comment by J0nathan550** [comment]
> > ### What feature do you want to get added on the **base** engine?
> > Hello, in Chart editor, there is ability to add notes by pressing 1-2-3-4 (player), 5-6-7-8(enemy) keys
> 
> ok Kade engine user

Sir, you smell like a fish

**Comment by J0nathan550** [comment]
> 1. you failed the test
> 2. this idea sucks

Which fucking test? Are you dumb or what?
Whole Idea of Issues, is to report, suggest. Not fucking complain you dumb.

**Comment by CaptainBaldi** [comment]
> > 1. you failed the test
> > 2. this idea sucks
> 
> Which fucking test? Are you dumb or what? Whole Idea of Issues, is to report, suggest. Not fucking complain you dumb.

![image](https://user-images.githubusercontent.com/86160807/215033828-477172d7-bfd2-4b00-98b7-94336fd70f7f.png) "not fucking complain, you dumb" they said

**Comment by TheKitBoi** [comment]
> Which fucking test?

You didn't pick the right answer 
![Screenshot_20230127_105017_Chrome](https://user-images.githubusercontent.com/84044666/215069190-70069f61-3b7d-4c21-a0e9-e56eaf11e30e.png)
