### ISSUE TITLE
New Difficulty Maker Not Working

### ISSUE THREAD

**Issue by Qecci** [ShadowMario/FNF-PsychEngine#118]
I tried to make the same example that ShadowMario did. I followed all of the rules correctly, I wrote in the code inside the source correctly, I even made a chart for Crazy Mode, but, nothing. Please help if you know. :)

(https://user-images.githubusercontent.com/91340807/134715143-c8979b97-14b0-47a1-825e-ef5c894d34e4.png)

**Comment by ShadowMario** [comment]
What exactly is not working? Detail it dude

**Comment by Qecci** [comment]
> What exactly is not working? Detail it dude

When I try to make a new difficulty, it doesn't appear in the main game.

**Comment by FuseIsHere813** [comment]
You tried compiling? If not, re-compile the game and try again.

**Comment by DarkDawnzenith** [comment]
There's a missing comma in hard.
