### ISSUE TITLE
my chart is bugged

### ISSUE THREAD

**Issue by dtgaming5737** [ShadowMario/FNF-PsychEngine#11809]
### Describe your problem here.

for some reason when i load up my song, the chart bugs out and just scrolls but then keeps going back
idk whats wrong please help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by OverFlow69** [comment]
video???

**Comment by RubenDatOneBoi3446** [comment]
Your missing the song

**Comment by RubenDatOneBoi3446** [comment]
that or whatever your song file is, is not an ogg or the name isnt voices.ogg or inst.ogg
Like this 
[Song Name/Folder] > [Inst.ogg] & [Voices.ogg]

**Comment by dtgaming5737** [comment]
i have the songs and the ogg file

**Comment by dtgaming5737** [comment]
https://user-images.githubusercontent.com/111058046/215607764-bd1a54ac-ab9b-4333-bcd9-aa1d0dfd676c.mp4

heres a video

**Comment by RubenDatOneBoi3446** [comment]
Is the song an actual ogg or did you download the song and rename it to ogg? If you downloaded it just use an ogg converter online

**Comment by dtgaming5737** [comment]
no i took fresh and put it in my songs folder

**Comment by RubenDatOneBoi3446** [comment]
Show me a screenshot

**Comment by dtgaming5737** [comment]
![Screenshot 2023-01-30 172155](https://user-images.githubusercontent.com/111058046/215609228-169d85c6-7b4e-49ac-8692-ac21368fa276.png)

**Comment by TheKitBoi** [comment]
whats the file typ

**Comment by dtgaming5737** [comment]
ogg

**Comment by RubenDatOneBoi3446** [comment]
folder name?

**Comment by dtgaming5737** [comment]
its my songs name in the mods>songs folder

**Comment by TheKitBoi** [comment]
is it in mods/songs/double-trouble

**Comment by dtgaming5737** [comment]
yes but without -

**Comment by dtgaming5737** [comment]
when the data folders name and json is double trouble it gives me this
![Screenshot 2023-01-30 173559](https://user-images.githubusercontent.com/111058046/215611850-acef2431-c78a-4f06-afa4-53bddc062cb8.png)

**Comment by RubenDatOneBoi3446** [comment]
Copy the chart but add a -hard at the end 
or just play on normal

**Comment by RubenDatOneBoi3446** [comment]
the json file

**Comment by dtgaming5737** [comment]
there is a -hard

**Comment by RubenDatOneBoi3446** [comment]
Just rename the whole thing double-trouble-hard.json

**Comment by frantastic24** [comment]
Duplicate of #11161

**Comment by RubenDatOneBoi3446** [comment]
> Just rename the whole thing double-trouble-hard.json



> Just rename the whole thing double-trouble-hard.json

also add a - on the space of the folder as well

**Comment by dtgaming5737** [comment]
guys i fixedd it thanks
