### ISSUE TITLE
Error on my lua code

### ISSUE THREAD

**Issue by fox-64** [ShadowMario/FNF-PsychEngine#11801]
### Describe your problem here.

my rating code is giving me a error, i am not understading what is the issue, could anyone explaing the error that i made

![error](https://user-images.githubusercontent.com/88749155/215160396-1cd06712-251a-4f04-a1d3-b97ce61f38d3.png)
![code](https://user-images.githubusercontent.com/88749155/215160438-641d14af-68ca-4fb2-9b54-a6b00e31eaad.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
There are unnecessary `end`s all over the place
https://www.lua.org/pil/4.3.1.html

**Comment by TheKitBoi** [comment]
here's yo fix
`--adding the txt
function onCreatePost()
	makeLuaText('ratingS', 'So sick!', 90, 40, 50)
	makeLuaText('ratingG', 'good', 90, 40, 50)
	makeLuaText('ratingB', 'bruh', 90, 40, 50)
	setProperty('ratingS.visable', false)
	setProperty('ratingG.visable', false)
	setProperty('ratingB.visable', false)
end

--to change the texts lol lol
function onUpdate()
	--rating "So Sick!" code
	if rating <= 1 then
		addLuaText('ratingS')
		doTweenAlpha('S','ratingS',1,0.1,'linear')
		doTweenAlpha('G','ratingG',0,0.1,'linear')
		doTweenAlpha('B','ratingB',0,0.1,'linear')
	end
	
	--rating "good" code
	if rating <= 0.90 then
		addLuaText('ratingG')
		doTweenAlpha('S','ratingS',0,0.1,'linear')
		doTweenAlpha('G','ratingG',1,0.1,'linear')
		doTweenAlpha('B','ratingB',0,0.1,'linear')
	end
	
	--rating "bruh" code
	if rating <= 0.50 then
		addLuaText('ratingB')
		doTweenAlpha('S','ratingS',0,0.1,'linear')
		doTweenAlpha('G','ratingG',0,0.1,'linear')
		doTweenAlpha('B','ratingB',1,0.1,'linear')
	end
end`
