### ISSUE TITLE
fnf lost my mind and breaking point.

### ISSUE THREAD

**Issue by Bentheboy** [ShadowMario/FNF-PsychEngine#11804]
### Describe your problem here.

my game keeps crashing at the "GET OUT OF MY HEAD" part.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no i did edit at all.

**Comment by Bentheboy** [comment]
sorry i am eleven so i don't know what some stuff is

**Comment by KalashniPepsi** [comment]
> sorry i am eleven so i don't know what some stuff is

isnt the age requirement for Github like 13?

**Comment by Bentheboy** [comment]
i don't know i just need help

**Comment by Bentheboy** [comment]
do you know how to help?

**Comment by Bentheboy** [comment]
StrumNote.hx (line 139)
flixel/group/FlxGroup.hx (line 175)
flixel/group/FlxGroup.hx (line 175)
flixel/addons/ui/FlxUIState.hx (line 212)
MusicBeatState.hx (line 70)
PlayState.hx (line 3025)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

**Comment by KalashniPepsi** [comment]
> do you know how to help?

alrighty then. Have you checked if your Psych Engine is up to date? and what device are you using?

**Comment by Bentheboy** [comment]
is what it says when i get to that part

**Comment by Bentheboy** [comment]
and it is v0.2.3 friday night funkin'

**Comment by Bentheboy** [comment]
0.6.3 psych engine

**Comment by Bentheboy** [comment]
wait sorry it's 0.2.8 friday night funkin'

**Comment by KalashniPepsi** [comment]
have you possibly tampered with the files or are you playing the mod as is?

**Comment by Bentheboy** [comment]
system type  64-bit operating system, x64-based processor

**Comment by Bentheboy** [comment]
and i'm playing the mod as is

**Comment by KalashniPepsi** [comment]
imma download the mod and check if i get any similar issues, i'll be back with a reply soon

**Comment by Bentheboy** [comment]
cool

**Comment by Bentheboy** [comment]
this is the link: https://drive.google.com/file/d/1UHjZtXYL4O0ixP_vWr_JaNo28ZbHDRSy/view

**Comment by KalashniPepsi** [comment]
do you have any other mods enabled?

**Comment by Bentheboy** [comment]
yes

**Comment by Bentheboy** [comment]
i have the lost to darkness mod enabled

**Comment by KalashniPepsi** [comment]
this is kind of a shot in the dark, but try disabling all mods except the one you're trynna play

**Comment by Bentheboy** [comment]
ok, i'll let you know if it works.

**Comment by Bentheboy** [comment]
it did'nt work

**Comment by Bentheboy** [comment]
didn't

**Comment by Bentheboy** [comment]
sorry i have trouble with that word.

**Comment by KalashniPepsi** [comment]
np

**Comment by KalashniPepsi** [comment]
aight, what are your Psych Engine options? anything noteworthy?

**Comment by Bentheboy** [comment]
my fps max is 60 or else lost to darkness doesn't work

**Comment by Bentheboy** [comment]
i have default settings

**Comment by Bentheboy** [comment]
except i changed the controls to dfjk

**Comment by Bentheboy** [comment]
d: left f: down j:up k:right

**Comment by KalashniPepsi** [comment]
I couldnt recreate the bug so i checked the Youtube comments for the mod.

Someone said that it crashes at the part you're talking about, but only when they didn't hit those triple notes.
Could that be whats happening to you?

**Comment by Bentheboy** [comment]
i don't know

**Comment by Bentheboy** [comment]
i usually miss one or two of them

**Comment by Bentheboy** [comment]
i am bad at triple notes

**Comment by Bentheboy** [comment]
i hit them but i don't think it worked cause it crashed again

**Comment by KalashniPepsi** [comment]
Ok this is another shot in the dark, im honestly just spitballing at this point.

Try reinstalling the mod, if that doesnt work then try reinstalling the engine, if THAT doesnt work then i got no clue.

**Comment by Bentheboy** [comment]
i have reinstalled the mod before but i haven't tried reinstalling the engine

**Comment by Bentheboy** [comment]
it did'nt work

**Comment by Bentheboy** [comment]
i was really looking forward to this mod.

**Comment by Bentheboy** [comment]
and it doesn't even work

**Comment by KalashniPepsi** [comment]
I mean, you could always play it Gamaverse

**Comment by Bentheboy** [comment]
what is that?

**Comment by KalashniPepsi** [comment]
its a website, google it

**Comment by KalashniPepsi** [comment]
oh yeah, and dont forget to close the issue if you're done here

**Comment by Bentheboy** [comment]
they don't have it there

**Comment by KalashniPepsi** [comment]
https://gamaverse.com/fnf-lost-my-mind-sonic-vs-xain-game/

**Comment by Bentheboy** [comment]
oh never mind

**Comment by Bentheboy** [comment]
ok but i want it downloaded just in case i am offline

**Comment by KalashniPepsi** [comment]
in that case, tough luck. i got nothin

**Comment by Bentheboy** [comment]
i have the huggy mod so imma move the mod over there and see if it works

**Comment by Bentheboy** [comment]
if it doesn't i'll just deal with it

**Comment by KalashniPepsi** [comment]
and dont forget to close the issue

**Comment by Bentheboy** [comment]
but i'm gonna keep it open just in case someone knows how.

**Comment by Bentheboy** [comment]
thank you for your help

**Comment by KalashniPepsi** [comment]
np, kid

**Comment by Bentheboy** [comment]
(:   (:     (:

**Comment by TheKitBoi** [comment]
Close this issue

**Comment by Bentheboy** [comment]
why i haven't solved the problem of the download and i'm sure someone will figure it out.

**Comment by Bentheboy** [comment]
it worked

**Comment by Bentheboy** [comment]
i thing i have to hit all the notes in that part to stop it from crashing

**Comment by Bentheboy** [comment]
thank you KalashinPepsi

**Comment by Xain422** [comment]
bro this game chrases when i pass get out of my head part
