### ISSUE TITLE
Is there any way of playing an animation on the stage with a event?

### ISSUE THREAD

**Issue by Luigitin** [ShadowMario/FNF-PsychEngine#11818]
### What is your question?

Are there any ways in that i could play a animation, pause or start an animation on a stage with a event?

**Comment by OverFlow69** [comment]
Source or lua??????

**Comment by Luigitin** [comment]
.lua

**Comment by Ratio-Combinder** [comment]
objectPlayAnimation('tag' 'animation' false)
