### ISSUE TITLE
This Is Not Really Question But A REMINDER!!!!!! (FOR MACOS USERS)

### ISSUE THREAD

**Issue by JovadinoDev** [ShadowMario/FNF-PsychEngine#11816]
### What is your question?

                                                       -------This is a reminder for the MacOS USERS!!------

If you have a older macOS computer or recent, you may have to read this! I'm in a older macOS and i used to use the latest haxefixel version but not anymore cuz, I have yt channel and i did a poll that i will port week 8 to week 7(NOT PSYCH ENGINE) and switched to the older Haxefixel and THEN switched it back to the newest version when it did not work and it got worse... Haxe got an new update and IT FUCKED UP THE WHOLE FUCKING THING!!!!!!! So know i gotta use the older version of Haxe to compile stuff on psych engine(If you don't know what is the older version, FNF Source Code uses Haxe 4.1.5 Psych Engine Uses the latest version of haxe 4.2.5) So if you gonna do something with the OG fnf source code or other stuff with other engines, JUST PICK ONE ENGINE!! (Trust me it would be better..)

But IDK If it effects other versions of macOS so i might be wrong..
![411180 jpg](https://user-images.githubusercontent.com/86385501/215365511-06df0923-6dca-4992-aac9-12b8d99b0d44.png)

**Comment by JovadinoDev** [comment]
Sorry For The Cringy Emoji, i thought it was cool

**Comment by TheKitBoi** [comment]
what the hell is this

**Comment by OverFlow69** [comment]
bro, the version doesn't matter for the base game or something that requires older haxe. you are just stupid and close this issue
