### ISSUE TITLE
psych engine bug

### ISSUE THREAD

**Issue by idk464** [ShadowMario/FNF-PsychEngine#11817]
### Describe your bug here.

some of the animation are going of screen

https://user-images.githubusercontent.com/111885251/215366862-b1652616-2754-4990-9575-e6d75d692029.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

not really

**Comment by frantastic24** [comment]
That's literally what offsets are for how is this a bug

**Comment by TheKitBoi** [comment]
> ### Describe your bug here.
> some of the animation are going of screen

clown detected

**Comment by OverFlow69** [comment]
just use offsets and close this

**Comment by DisIsNOt** [comment]
Adjust is position using the arrow keys on your keyboard of smth

**Comment by idk464** [comment]
sorry im not really good with psych engine i did not know what offsets was

**Comment by idk464** [comment]
like seriously im 11

**Comment by idk464** [comment]
https://user-images.githubusercontent.com/111885251/215902466-a9c85864-42b3-4e1e-9c1a-702d6faf4b3b.mp4

but now when the camera is looking at hall monitor its looking down

**Comment by TheKitBoi** [comment]
> but now when the camera is looking at hall monitor its looking down

then adjust the Camera X and Y positions

**Comment by idk464** [comment]
how do i do that (sorry for wasting your time)

**Comment by idk464** [comment]
nevermind

**Comment by idk464** [comment]
thanks for helping though and sorry for wasting everybody's time

**Comment by CrusherNotDrip** [comment]
maybe close the issue???

**Comment by idk464** [comment]
this is now closed
