### ISSUE TITLE
noteskin overrides custom note texture

### ISSUE THREAD

**Issue by Itz-Miles** [ShadowMario/FNF-PsychEngine#11810]
### Describe your bug here.

Setting the noteskin in the chart editor overrides hardcoded custom notes.

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2354)
PlayState.hx (line 1431)
flixel/group/FlxGroup.hx (line 769)
PlayState.hx (line 1381)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Heavily edited build. Not sure how many merges I've made since then, but it sounds like a 0.6 bug.

**Comment by OverFlow69** [comment]
WHAT THE FUCK DID YOU EXPECT

**Comment by Itz-Miles** [comment]
Who even are you? You're not adding much to the conversation when you fail to understand that a Hurt Note shouldn't be wrongly masked as a "small, irregularly timed note", only to crash the game and ruin the autosave when it crosses the strumline.

A simple change to Note.hx has more though put into it than your reply. https://github.com/ShadowMario/FNF-PsychEngine/pull/11811
