### ISSUE TITLE
compiling issues

### ISSUE THREAD

**Issue by FrogB** [ShadowMario/FNF-PsychEngine#11815]
### Describe your problem here.

so when i try to compile the game, i get this error

source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
source/TitleState.hx:219: characters 55-58 : Float should be flixel.util.FlxAxes
source/TitleState.hx:219: characters 55-58 : ... For optional function argument 'repeatAxes'

any fixes to this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
Replace Main.hx with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

**Comment by FrogB** [comment]
> Replace Main.hx with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

I am now left with the following error, thanks for fixing the Main.HX issue.

source/TitleState.hx:219: characters 55-58 : Float should be flixel.util.FlxAxes
source/TitleState.hx:219: characters 55-58 : ... For optional function argument 'repeatAxes'

What should I do next?

**Comment by TheKitBoi** [comment]
> What should I do next?

do a #if (flixel < "5.0.0") and at the end of the code do #end

**Comment by FrogB** [comment]
how do i put it in?

**Comment by Ratio-Combinder** [comment]
at line 218 at the end 220

**Comment by FrogB** [comment]
Thanks!

**Comment by FrogB** [comment]
OK I was about to jesus, no need to be rude
