### ISSUE TITLE
The .mp4 doesn't fucking work (Also Main.hx as well)

### ISSUE THREAD

**Issue by OverFlow69** [ShadowMario/FNF-PsychEngine#11819]
### Describe your problem here.

Why
![image](https://user-images.githubusercontent.com/98959759/215433703-c46495cb-ea7e-4bc3-a175-dfb03be3cdfc.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, a shit ton of stuff

**Comment by Ratio-Combinder** [comment]
haxelib remove hxCodec
haxelib install hxCodec 2.5.1

**Comment by OverFlow69** [comment]
what about Main.hx?????

**Comment by Ratio-Combinder** [comment]
replace it with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

**Comment by OverFlow69** [comment]
it's already fixed, i was trying to add jason and he thought auto save was toggled already. since he formatted his pc he didn't have it enabled
