### ISSUE TITLE
ANIMATED SPRITE QUESTION

### ISSUE THREAD

**Issue by PotatoKing0419** [ShadowMario/FNF-PsychEngine#11825]
### Describe your problem here.

So, basically I just want an object to play an animation, wait a bit, and then play another animation.
This is my code right now, to get a better understanding.

else
	playSound('DENIED');
	objectPlayAnimation('botato shop', 'broke', false)
        [INSERT HOWEVER TO DELAY THESE]
	objectPlayAnimation('botato shop', 'idle', false)

So i basically just want a way to delay the 2nd animation so it plays the first one fully.
no one ever responds to these please help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
[Timers](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers#runtimertagstring-timefloat--1-loopsint--1)

**Comment by PotatoKing0419** [comment]
> [Timers](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers#runtimertagstring-timefloat--1-loopsint--1)

im gonna sound really dumb but can you give me an example of how these are used

**Comment by CaptainBaldi** [comment]
```
runHaxeCode([[
        game.getLuaObject('luaSpr').playAnim('stuff');
        new FlxTimer().start(2, function(tmr:FlxTimer)
	{
		game.getLuaObject('luaSpr').playAnim('stuff2');
	});
]])
```

mmm this a lua timer but one main in hscipt cause i dont like how lua timers work

**Comment by Ratio-Combinder** [comment]
lua ver
```
runTimer('wait', 2, 1)

onTimerCompleted(wait)
    characterPlayAnim('dad', 'anim', false)
end
```

**Comment by PotatoKing0419** [comment]
> lua ver
> 
> ```
> runTimer('wait', 2, 1)
> 
> onTimerCompleted(wait)
>     characterPlayAnim('dad', 'anim', false)
> end
> ```

it only plays the second animation

**Comment by PotatoKing0419** [comment]
Nvm it works I put it in wrong XDD
