### ISSUE TITLE
Source code compiling issues

### ISSUE THREAD

**Issue by Viment** [ShadowMario/FNF-PsychEngine#11822]
### Describe your problem here.

source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler

What do I need to do?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I replaced Main.hx with new Main.hx

**Comment by TheKitBoi** [comment]
haxelib remove hxCodec
haxelib install hxCodec 2.5.1

**Comment by Viment** [comment]
> 

Thanks a lot! I compile it!
