### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by TrollerYT0** [ShadowMario/FNF-PsychEngine#11828]
### Describe your bug here.

When i wanna open song in chart editor and type name of song i click reload json and this error pop ups

![obraz_2023-01-31_132353745](https://user-images.githubusercontent.com/124052835/215758869-8d0ad369-e0ab-445c-ac12-b9457c3d6a6a.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't edit anything

**Comment by FunkoDev** [comment]
> not a bug missing chart file

i haven't seen this crash handler before.
