### ISSUE TITLE
What's the maximum length a song can be?

### ISSUE THREAD

**Issue by smisanasshole** [ShadowMario/FNF-PsychEngine#11829]
### What is your question?

Hi so I attempted to put quite the long song into Psych Engine but I'm pretty sure the engine couldn't handle it because the game just kinda froze.

Anyway I'm planning on cutting some parts out just to make it short enough for Psych Engine to handle but I still don't know what the limit is.

(btw if youre wondering what i mean by it wont work the chart just stops working and the chart editor shows that the song has a negative number of sections which i assume means an integer overflow happened or something)

I'm using 0.6.2 btw.

**Comment by TheKitBoi** [comment]
23 minutes

**Comment by KirbyKid256** [comment]
> 22 minutes

So exactly at the 22-minute mark is when the song would freeze?
Also, if you want to keep the song parts, I suggest making transitions in the song and splitting them up across the week. You would also need to skip the countdown.

**Comment by Sussy-Sam** [comment]
For the most recent version of Psych Engine, the farthest I could go was 25 minutes and 21.69 seconds.
