### ISSUE TITLE
fnf lost my mind bug is back

### ISSUE THREAD

**Issue by Bentheboy** [ShadowMario/FNF-PsychEngine#11837]
### Describe your bug here.

the game crashes at the "GET OUT OF MY HEAD!" part and i thought i figured it out but it didn't work i even tried playing online but my browser crashes to.

### Command Prompt/Terminal logs (if existing)

```bash
StrumNote.hx (line 139)
flixel/group/FlxGroup.hx (line 175)
flixel/group/FlxGroup.hx (line 175)
flixel/addons/ui/FlxUIState.hx (line 212)
MusicBeatState.hx (line 70)
PlayState.hx (line 3025)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Bentheboy** [comment]
I need help.

**Comment by frantastic24** [comment]
Not a bug 
#9507

**Comment by Bentheboy** [comment]
ok how do i fix the problem then

**Comment by Bentheboy** [comment]
never mind i figured it out.
