### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by Noel3454565FNF** [ShadowMario/FNF-PsychEngine#11839]
### Describe your bug here.

i try ti compil the game but i have this
![image](https://user-images.githubusercontent.com/58745415/216025193-bd093c81-68f9-4f6e-a4ba-66455386b655.png)

someone can help me?
im on haxe 4.2.4, trying to compil Psych engine 

### Command Prompt/Terminal logs (if existing)

```bash
BUILDING GAME
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler

done.
Appuyez sur une touche pour continuer...
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheKitBoi** [comment]
use
```
haxelib remove hxCodec
haxelib install hxCodec
```

**Comment by Noel3454565FNF** [comment]
not working :,(
its the same error

**Comment by Noel3454565FNF** [comment]
BUILDING GAME
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler

done.

**Comment by TheKitBoi** [comment]
I forgot to add a version
```
haxelib remove hxCodec
haxelib install hxCodec 2.5.1
```

**Comment by Noel3454565FNF** [comment]
im gonna try that thanks

**Comment by Noel3454565FNF** [comment]
i think its work but i have this now:
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

**Comment by Noel3454565FNF** [comment]
its not finish yet but i told ya if i get other error

**Comment by Noel3454565FNF** [comment]
thanks a lot

**Comment by Noel3454565FNF** [comment]
THANKS @TheKitBoi  its working now :DDDDDD
