### ISSUE TITLE
The Xs and Ys of the character are weird

### ISSUE THREAD

**Issue by IdiotLimitedEdition** [ShadowMario/FNF-PsychEngine#11832]
### Describe your problem here.

So I finally managed to get my stage assets to load but when I open it the characters are all misplaced even though I used the same that were in Flash in fact all the stage assets are placed correctly. This is how it's supposed to look like
![likecomeon](https://user-images.githubusercontent.com/111077202/215880707-32d026e6-eea8-4cfa-9e90-bad03d096620.png)
And how it looks in game
[image_1](https://user-images.githubusercontent.com/111077202/215881176-ad2e378d-f7af-4e60-ab91-7ea9f40dfd5f.png)

[image_2)](https://user-images.githubusercontent.com/111077202/215881509-0633e219-3b21-4d0c-a1a3-5f290454ec07.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Animated Icons, GameJolt, Main menu characters

**Comment by frantastic24** [comment]
BF has a Y Offset by default (350)
Can't help with your custom character because you posted none of your files

**Comment by IdiotLimitedEdition** [comment]
[Spritesheet](https://user-images.githubusercontent.com/111077202/216139426-c349ffc5-36c4-46ff-b27f-22cd73af0f59.png)
[xml n json](https://drive.google.com/drive/folders/1-Gv67rPsaX_OlJpZQYbBXuHxBrjpusZy?usp=share_link)
