### ISSUE TITLE
how do i make dialogue mid song

### ISSUE THREAD

**Issue by idk464** [ShadowMario/FNF-PsychEngine#11833]
### Describe your problem here.

https://user-images.githubusercontent.com/111885251/215909777-d4b54764-cc49-4697-8ace-19ba1ba5e0a9.mp4

im working on algebra but in psych engine and i want to add dialogue when dave is roasting bf

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

not really

**Comment by CaptainBaldi** [comment]
you could use TypedAlphabet i suppose

**Comment by PotatoKing0419** [comment]
https://gamebanana.com/tools/10348
Hopefully this helps :)

**Comment by idk464** [comment]
thanks @PotatoKing0419 this really helped! this is closed now
