### ISSUE TITLE
Death Animation Placement

### ISSUE THREAD

**Issue by MarkAwesomeness** [ShadowMario/FNF-PsychEngine#11834]
### Describe your problem here.

Im just wondering if the position of the death animation is hardcoded. If not, how would I move it. Im using a custom death animation, so I want to move it because half of it is cut off by the top of the screen

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MarkAwesomeness** [comment]
I'd also like to know how to change the speed of the camera movement if that isnt hardcoded as well

**Comment by InsiderIV** [comment]
For your first question, it is hardcoded. For the second question, use this line:

setProperty('cameraSpeed', 5)
