### ISSUE TITLE
how do i put a character in a background

### ISSUE THREAD

**Issue by idk464** [ShadowMario/FNF-PsychEngine#11840]
### Describe your problem here.
![crowd - Copy](https://user-images.githubusercontent.com/111885251/216037445-8cf148c7-3c6d-4b52-9d03-d8d2f518f804.png)

im trying to put these characters in the big dingle song on my psych engine

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

not really

**Comment by TheKitBoi** [comment]
function onCreate()
    makeAnimatedLuaSprite('bg-people', 'image location', X,Y) -- change the X and Y to a number
    addAnimationByPrefix('bg-people, 'animation', 'bg-people', 24, false) -- change animation to a anim from XML
    addLuaSprite('bg-people', false)
end

function onBeatHit()
    objectPlayAnimation('bg-people', 'animation', false)
end
