### ISSUE TITLE
What happened here?

### ISSUE THREAD

**Issue by Mrbowsergaming** [ShadowMario/FNF-PsychEngine#11846]
### What is your question?

Paths.hx (line 356)
HealthIcon.hx (line 43)
HealthIcon.hx (line 20)
editors/WeekEditorState.hx (line 615)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

This error came up when i went into week editor freeplay mode and also chart editior but with a slightly different message:
Paths.hx (line 356)
HealthIcon.hx (line 43)
HealthIcon.hx (line 20)
editors/ChartingState.hx (line 254)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

How do i fix this?

**Comment by TheKitBoi** [comment]
you have a missing icon

**Comment by Mrbowsergaming** [comment]
Where is the icon missing and why is it caused by me opening chart/freeply week editor?

**Comment by TheKitBoi** [comment]
send the files for each week

**Comment by Mrbowsergaming** [comment]
it won't let me upload json lol

**Comment by TheKitBoi** [comment]
rename it to .txt

**Comment by Mrbowsergaming** [comment]
![icon-mouse](https://user-images.githubusercontent.com/124312055/216462176-76486921-6956-4575-b50d-711c1cc4bcea.png)
[weeknoob.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/10573929/weeknoob.txt)
here they are

**Comment by TheKitBoi** [comment]
![image](https://user-images.githubusercontent.com/84044666/216463424-d61558f7-2a99-4663-ada6-31d90810a408.png)

seems to work on mine
is the image name same as the week file icon

**Comment by Mrbowsergaming** [comment]
yep
it was working yesterday and i can still play the song
however i tried put double trouble in (from main imposter v4 build) and it broke everything ( i am very stupid sometimes)
