### ISSUE TITLE
countdown skipping lua script

### ISSUE THREAD

**Issue by idk479** [ShadowMario/FNF-PsychEngine#11848]
### What is your question?

I know how to do this but since psych's lua API changed like a few times it keeps having errors

**Comment by TheKitBoi** [comment]
use
```
function onCreate()
	setPropertyFromClass('flixel.FlxG','sound.music.volume',0)
	setProperty('skipCountdown',true)
	setProperty('vocals.time',0)
end

function onCreatePost()
	setProperty('vocals.volume',0)
	setProperty('vocals.time',0)
end

function onSongStart()
	setProperty('vocals.volume',1)
	setProperty('vocals.time',0)
	setPropertyFromClass('flixel.FlxG','sound.music.volume',1)
end
```

**Comment by idk479** [comment]
> use
> 
> ```
> function onCreate()
> 	setPropertyFromClass('flixel.FlxG','sound.music.volume',0)
> 	setProperty('skipCountdown',true)
> 	setProperty('vocals.time',0)
> end
> 
> function onCreatePost()
> 	setProperty('vocals.volume',0)
> 	setProperty('vocals.time',0)
> end
> 
> function onSongStart()
> 	setProperty('vocals.volume',1)
> 	setProperty('vocals.time',0)
> 	setPropertyFromClass('flixel.FlxG','sound.music.volume',1)
> end
> ```

thanks
