### ISSUE TITLE
load a song when you press enter on titlestate

### ISSUE THREAD

**Issue by Jevilm** [ShadowMario/FNF-PsychEngine#11849]
### What is your question?

how do you load a song when you press enter on titlestate
this is for my d̶a̶v̶e̶ ̶a̶n̶d̶ ̶b̶a̶m̶b̶i̶ ̶p̶o̶r̶t̶  custom menus in lua

**Comment by IdiotLimitedEdition** [comment]
You can only do it in source code

**Comment by Jevilm** [comment]
> You can only do it in source code

yeah im trying to do it in source and then load a song and use lua from there

**Comment by IdiotLimitedEdition** [comment]
```hx
Song.loadFromJsonRAW('json path'); //inside if(pressedenter) at line 510 btw
```

**Comment by Jevilm** [comment]
> ```hx
> Song.loadFromJsonRAW('json path'); //inside if(pressedenter) at line 510 btw
> ```

thank you
