### ISSUE TITLE
VS Impostor V4 Compiling Issue

### ISSUE THREAD

**Issue by LolMan1022** [ShadowMario/FNF-PsychEngine#11842]
### What is your question?

Ive been having an issue with compiling vs impostor v4, i dont know if this is the best place to ask for this kind of help but ive been looking everywhere and cant find any solution

source/Main.hx:87: characters 61-65 : Float should be Int
source/Main.hx:87: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:87: characters 61-65 : ... For function argument 'child'
source/AmongStoryMenuState.hx:145: characters 73-74 : Int should be flixel.util.FlxAxes
source/AmongStoryMenuState.hx:145: characters 73-74 : ... For optional function argument 'repeatAxes'
source/AmongStoryMenuState.hx:152: characters 79-80 : Int should be flixel.util.FlxAxes
source/AmongStoryMenuState.hx:152: characters 79-80 : ... For optional function argument 'repeatAxes'
source/AmongStoryMenuState.hx:246: characters 24-27 : Static access to instance field add is not allowed
source/AmongStoryMenuState.hx:272: characters 25-28 : Static access to instance field add is not allowed
source/AmongStoryMenuState.hx:552: characters 24-27 : Static access to instance field add is not allowed
source/MainMenuState.hx:83: characters 73-74 : Int should be flixel.util.FlxAxes
source/MainMenuState.hx:83: characters 73-74 : ... For optional function argument 'repeatAxes'
source/MainMenuState.hx:89: characters 73-74 : Int should be flixel.util.FlxAxes
source/MainMenuState.hx:89: characters 73-74 : ... For optional function argument 'repeatAxes'
source/OptionsState.hx:48: characters 73-74 : Int should be flixel.util.FlxAxes
source/OptionsState.hx:48: characters 73-74 : ... For optional function argument 'repeatAxes'
source/OptionsState.hx:55: characters 79-80 : Int should be flixel.util.FlxAxes
source/OptionsState.hx:55: characters 79-80 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:800: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:800: characters 71-72 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:807: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:807: characters 71-72 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:814: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:814: characters 71-72 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:821: characters 71-72 : Int should be flixel.util.FlxAxes
source/PlayState.hx:821: characters 71-72 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:828: characters 74-75 : Int should be flixel.util.FlxAxes
source/PlayState.hx:828: characters 74-75 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:996: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:996: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1003: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1003: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1010: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1010: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1017: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1017: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1024: characters 84-85 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1024: characters 84-85 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1357: characters 75-76 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1357: characters 75-76 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1365: characters 75-76 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1365: characters 75-76 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1468: characters 27-30 : Static access to instance field add is not allowed
source/PlayState.hx:1729: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:1729: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:3458: characters 81-82 : Int should be flixel.util.FlxAxes
source/PlayState.hx:3458: characters 81-82 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:3583: characters 4-18 : Warning : This case is unused
source/PlayState.hx:4350: characters 81-91 : Warning : This pattern is unused
source/ShopState.hx:325: characters 30-33 : Static access to instance field add is not allowed
source/AmongFreeplayState.hx:142: characters 73-74 : Int should be flixel.util.FlxAxes
source/AmongFreeplayState.hx:142: characters 73-74 : ... For optional function argument 'repeatAxes'
source/AmongFreeplayState.hx:149: characters 73-74 : Int should be flixel.util.FlxAxes
source/AmongFreeplayState.hx:149: characters 73-74 : ... For optional function argument 'repeatAxes'
source/AmongFreeplayState.hx:286: characters 24-27 : Static access to instance field add is not allowed
source/TitleState.hx:187: characters 73-74 : Int should be flixel.util.FlxAxes
source/TitleState.hx:187: characters 73-74 : ... For optional function argument 'repeatAxes'
source/TitleState.hx:193: characters 73-74 : Int should be flixel.util.FlxAxes
source/TitleState.hx:193: characters 73-74 : ... For optional function argument 'repeatAxes'

Sorry thats its so much but i dont know what else to do, thanks.

**Comment by Stefan2008GitHub** [comment]
Flixel 5.0.1 it's released

**Comment by LolMan1022** [comment]
it worked but the songs crash when playing in freeplay

**Comment by LolMan1022** [comment]
ok just found out all songs just crash rip

**Comment by TheKitBoi** [comment]
this issue belongs to https://github.com/Clowfoe/IMPOSTOR-UPDATE
