### ISSUE TITLE
Yoshi engine charts to Psych engine charts

### ISSUE THREAD

**Issue by MisterEGaming** [ShadowMario/FNF-PsychEngine#11852]
### What is your question?

Anyone know how to port a Yoshi engine chart to a psych engine port

**Comment by TheKitBoi** [comment]
not possible + why

**Comment by ShadowMilky** [comment]
> ### What is your question?
> Anyone know how to port a Yoshi engine chart to a psych engine port

theres no option but to rechart it + why

**Comment by MrRainbowCoding** [comment]
I'm wondering this too.
