### ISSUE TITLE
Character editor background

### ISSUE THREAD

**Issue by JVgradiz** [ShadowMario/FNF-PsychEngine#11855]
### What feature do you want to get added on the **base** engine?

In the character editor set any background ( from the engine or the selected mod ), so it is easier to set the mod character in the correct position

( sorry if my english isn't the best )

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Jevilm** [comment]
that would be kinda cool to see in psych engine
i approve 👍

**Comment by ShadowMario** [comment]
Can't
