### ISSUE TITLE
Is it possible to change the looping points of animations?

### ISSUE THREAD

**Issue by KutikiPlayz** [ShadowMario/FNF-PsychEngine#1185]
### What is your question?

My friend has a character that has some really nice smooth animations, and they look really nice on single notes, but sustain notes make it loop the entire animation and it looks terrible that way, is it possible to make the animation loop at the last 2 frames so that it looks decent?

**Comment by ShadowMario** [comment]
*-loop animations exist.

You can make for example singLEFT-loop, this animation type will be triggered once singLEFT (the original animation) is ended.
