### ISSUE TITLE
Any ways of making a "Fake" note? (no miss and no add score)

### ISSUE THREAD

**Issue by Luigitin** [ShadowMario/FNF-PsychEngine#11850]
### What is your question?

So, is there any way of making a fake note in lua? (no miss and no add score)
I really think its gonna be useful
Also im in 0.6.2

**Comment by Luisinhi010** [comment]
i only know in source

**Comment by TheKitBoi** [comment]
function onCreate()
	for i = 0, getProperty("unspawnNotes.length")-1 do
		if getPropertyFromGroup("unspawnNotes", i, "noteType") == "Note Name" then
			setPropertyFromGroup("unspawnNotes", i, "texture", "NOTENAME_assets")
			setPropertyFromGroup("unspawnNotes", i, "hitHealth", "0")
			setPropertyFromGroup("unspawnNotes", i, "missHealth", "0")
			setPropertyFromGroup("unspawnNotes", i, "hitCausesMiss", false)

			if getPropertyFromGroup("unspawnNotes", i, "mustPress") then
				setPropertyFromGroup("unspawnNotes", i, "ignoreNote", true)
			end
		end
	end
end

**Comment by Luigitin** [comment]
ayo thanks
