### ISSUE TITLE
Wierd compiler bug

### ISSUE THREAD

**Issue by DelilahStone-NeverWinter** [ShadowMario/FNF-PsychEngine#11857]
### Describe your bug here.

>\Whenever I tried to compile it for the first time, I was met with this

### Command Prompt/Terminal logs (if existing)

```bash
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
H:\Wonka DS2\fnf cover mod\PsychEngine-Windows64\Funky Cover Friday V3.0 (SOURCE)\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, it was the first time building it

**Comment by SMB-5** [comment]
I have that same problem too

**Comment by TheKitBoi** [comment]
install vs19

**Comment by xlebza09** [comment]
Install Visual Studio with choosing Windows SDK and MSVC 142 in installation. I had the same problem.

**Comment by SMB-5** [comment]
oh yeah i forgot to update my case installing vsc 2019 worked and i compiled source a few days ago so thx for suggesting that hopefully the other guy has they's fixed

**Comment by TheKitBoi** [comment]
close this issue
