### ISSUE TITLE
WHAT THE FUCK IS THIS

### ISSUE THREAD

**Issue by Jevilm** [ShadowMario/FNF-PsychEngine#11863]
### Describe your bug here.

??????????
![Screenshot (124)](https://user-images.githubusercontent.com/110422450/216835656-1ef04c66-461b-4099-b954-ab43063e4b84.png)
I NEED ANSWERS

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

YEAH BUT I DONT REMEMBER EDITING LIME.NDLL

**Comment by Jevilm** [comment]
I FIXED IT BUT I STILL HAVE NO CLUE WHAT HAPPENED

**Comment by AyMarte** [comment]
lol
