### ISSUE TITLE
Null Object Reference when loading character json

### ISSUE THREAD

**Issue by schoolchromebookgaming** [ShadowMario/FNF-PsychEngine#11868]
### Describe your bug here.

I was trying to add a custom character, it works just fine in the character editor but when I load it into a song it breaks.
It's only one frame and isn't too complicated. Here's the XML and JSON:

`<?xml version='1.0' encoding='utf-8'?>
<TextureAtlas imagePath="Grandma.png">
<SubTexture name="Grandma Idle" x="0" y="0" width="554" height="968" frameX="-21" frameY="-82" frameWidth="600" frameHeight="1074" />
</TextureAtlas>`

`{
	"animations": [
		{
			"offsets": [
				0,
				0
			],
			"indices": [],
			"fps": 24,
			"anim": "idle",
			"loop": false,
			"name": "Grandma Idle"
		}
	],
	"no_antialiasing": false,
	"image": "characters/Grandma",
	"position": [
		-120,
		-130
	],
	"healthicon": "",
	"flip_x": false,
	"healthbar_colors": [
		161,
		161,
		161
	],
	"camera_position": [
		0,
		300
	],
	"sing_duration": 0,
	"scale": 0.5
}`

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2920)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheKitBoi** [comment]
Send the files in a .txt format

**Comment by schoolchromebookgaming** [comment]
The crash report or the json/xml files?

**Comment by TheKitBoi** [comment]
json/xml files

**Comment by schoolchromebookgaming** [comment]
I've fixed it now I changed something in the json but I forgot what

**Comment by SimoTxSN** [comment]
can you please tell me how you fixed it? im having the same problem for some reason

**Comment by gusborg88** [comment]
its been a while, honestly I forgor
