### ISSUE TITLE
Everytime I'm trying to import my character in, it won't load or it crashes

### ISSUE THREAD

**Issue by AntikingCoder** [ShadowMario/FNF-PsychEngine#11862]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/101297055/216805930-243f6ed0-0ef3-441e-a212-bcaaad74dda0.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No response

**Comment by CaptainBaldi** [comment]
💀

**Comment by TheKitBoi** [comment]
is the name even the right thing from the image
