### ISSUE TITLE
Inputs are randomly hitting 2 notes at once

### ISSUE THREAD

**Issue by LaymooDR** [ShadowMario/FNF-PsychEngine#11864]
### Describe your bug here.

When I hit an arrow input, it almost always hits 2 notes at the same time, making accuracy drop.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by CaptainBaldi** [comment]
i've literally never had this issue

**Comment by LaymooDR** [comment]
> 

0.6.3. Yes, the offset is just fine.
