### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by squidisbrowsinggithub** [ShadowMario/FNF-PsychEngine#11869]
### Describe your problem here.

I'm importing a new .ogg song, in the mods folder, everything is set correctly, and there's no inst. Can you please tell me what happened and what i need to do next>
![image](https://user-images.githubusercontent.com/112262894/217400156-d016aaa2-5670-4db3-bbc5-b9ed86b23d23.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I tried making a new song.

**Comment by squidisbrowsinggithub** [comment]
Also i used that dad battle spotlight event thing

**Comment by squidisbrowsinggithub** [comment]
it may have seem that the events were the problem?

**Comment by squidisbrowsinggithub** [comment]
:/

**Comment by TheKitBoi** [comment]
the point 
it only hard coded into week 1
