### ISSUE TITLE
Crash(Segmentation fault) on blammed

### ISSUE THREAD

**Issue by N0Respect** [ShadowMario/FNF-PsychEngine#1186]
### Describe your bug here.

OS: KDE Neon 5.23 (Ubuntu Focal)
Crash with segmentation fault in section 32.
No problem with "Pico" and "Philly Nice".

### Command Prompt/Terminal logs (if existing)

```bash
ource/Discord.hx:62: Discord Client initialized
source/Discord.hx:12: Discord Client starting...
source/Discord.hx:19: Discord Client started.
source/FreeplayState.hx:283: blammed-hard
source/FreeplayState.hx:290: CURRENT WEEK: week3
source/LoadingState.hx:162: Setting asset folder to week3
source/Conductor.hx:59: new BPM map BUDDY []
source/PlayState.hx:306: stage is: null
[1]    18519 segmentation fault  ./PsychEngine
./PsychEngine  7.78s user 1.13s system 10% cpu 1:26.99 total
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing.

**Comment by ShadowMario** [comment]
Linux isn't supported as i don't have a virtual machine for it.
