### ISSUE TITLE
Anyway I can change the note offset itself?

### ISSUE THREAD

**Issue by Lorekeeper49** [ShadowMario/FNF-PsychEngine#11861]
### Describe your problem here.

for clarification, the note trail moves with the note when using `setPropertyFromGroup('unspawnNotes', i, 'offsetX', value);` or `setPropertyFromGroup('unspawnNotes', i, 'offsetY', value);` and I clearly don't want that
![image](https://user-images.githubusercontent.com/93066594/216803444-09081ff2-265b-4e68-ac95-0377042fa9ad.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Drawoon2** [comment]
`    for i=0,getProperty('unspawnNotes.length')-1 do
        if not getPropertyFromGroup('unspawnNotes',i,'isSustainNote') then
            setPropertyFromGroup('unspawnNotes',i,'offsetX',value)
            setPropertyFromGroup('unspawnNotes',i,'offsetY',value)
        end

    end`

**Comment by Lorekeeper49** [comment]
> `    for i=0,getProperty('unspawnNotes.length')-1 do
>         if not getPropertyFromGroup('unspawnNotes',i,'isSustainNote') then
>             setPropertyFromGroup('unspawnNotes',i,'offsetX',value)
>             setPropertyFromGroup('unspawnNotes',i,'offsetY',value)
>         end
> 
>     end`

I should have known that, thanks.
