### ISSUE TITLE
Different Zoom on different character

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#11866]
### Describe your problem here.

I don't know if there is a kind of smooth implementation of this, or if it would be tedious to do, but to say what I mean

Let us say I have a huge enemy like hell clown tricky thing. and when the cam is on the opponent, I want the cam to zoom out so that it can be looked at properly. But, if it goes to bf or anybody else, it should be the regular size. Or if there is a smaller character, like little man, the camera should zoom in there.
So, a variable cam zoom that is defined on each cahracter. Is that possible to do in lua, without writing so much around? If not, can it maybe be added to engine? I think it would be rarely used, but ppl would gladly take it if they can.
(Not using the resizing option, because sometimes you just want to have them so big or small by definition of the char)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not via source

**Comment by CaptainBaldi** [comment]
you can just check which side the camera is on with onMoveCamera(char) and then change the camera zoom accordingly
for example you could do something like
```function onMoveCamera(char)
    if char == 'dad' then
        setProperty('defaultCamZoom', 0.5)
    else
        setProperty('defaultCamZoom', 0.8)
end```

**Comment by ZeitHeld** [comment]
I see. If I combine it with a dadname or bfname check, then I could turn it into character script.
Alright, thanks!

**Comment by Thiago821** [comment]
> I see. If I combine it with a dadname or bfname check, then I could turn it into character script. Alright, thanks!

if bfname dont work then use boyfriendname
