### ISSUE TITLE
Uhh I cant compile

### ISSUE THREAD

**Issue by ThatGuy1ol** [ShadowMario/FNF-PsychEngine#11873]
### Describe your bug here.

When compiling Psych Engine, I was up to the point where I needed to type 'lime test windows'. But when doing so...
'source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1573: characters 13-23 : Type not found : MP4Handler'
came up.

I have no idea how to fix this.

### Command Prompt/Terminal logs (if existing)

```bash
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1573: characters 13-23 : Type not found : MP4Handler
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I just downloaded it, did nothing to the file

**Comment by superplayhero2** [comment]
check your hxCodec version and make sure it's 2.5.1 else do
```
haxelib remove hxCodec
haxelib install hxCodec 2.5.1
```
or just do 
```
```

**Comment by ThatGuy1ol** [comment]
I can comfirm this works, thank you
