### ISSUE TITLE
I can't enter mods menu

### ISSUE THREAD

**Issue by maxi230151** [ShadowMario/FNF-PsychEngine#11874]
### Describe your bug here.

I was modding and then this error pop up
![image](https://user-images.githubusercontent.com/86842359/217587966-b957859a-18b4-4ec6-9105-8133b8a19f46.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CaptainBaldi** [comment]
broken pack.json file

**Comment by maxi230151** [comment]
oh thanks
