### ISSUE TITLE
Goofy ahh error trying to compile

### ISSUE THREAD

**Issue by Speedrunner-doomguy** [ShadowMario/FNF-PsychEngine#11870]
### Describe your problem here.

I keep having this odd problem where certain hx files flat out won't work, please someone help, I've spent hours trying to fix this lmao

![image](https://user-images.githubusercontent.com/71648353/217413194-2b252d47-e212-4357-ad7b-2edb79937dcf.png)

(image of everything that I have installed into Haxe for reference)
![image](https://user-images.githubusercontent.com/71648353/217413491-65d58be2-566f-4e8d-9a3b-d9897278745e.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing yet but if need be I'll edit whatever

**Comment by TheKitBoi** [comment]
Replace Main.hx with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

**Comment by Speedrunner-doomguy** [comment]
It worked!! Thanks a million!
