### ISSUE TITLE
Little problem with main.hx on 6.2

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#11875]
### Describe your bug here.

Psych engine 6.2 has a weird thing if you updated your haxe and lime so line 85 on main.hx ```addChild(new FlxGame(gameWidth, gameHeight, initialState, zoom, framerate, framerate, skipSplash, startFullscreen));``` seems to be broken and wont let me compile (terminal below)
i havent gotten this error in a bit and i cant really change the engine to 6.3 because of some stuff is 6.2 exclusive

![image](https://user-images.githubusercontent.com/56323671/217655116-066dd809-1709-4d0e-90a3-57c245a4e8c3.png)

### Command Prompt/Terminal logs (if existing)

```bash
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

mainmenustate.hx main.hx titlestate.hx

**Comment by frantastic24** [comment]
This was already fixed in 68b372789ea2e161a01ff1469dda27fa52dc4760

**Comment by TheKitBoi** [comment]
replace Main.hx with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

**Comment by machonessiebaby** [comment]
> replace Main.hx with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

thanks
