### ISSUE TITLE
hmm.json error

### ISSUE THREAD

**Issue by groovington43** [ShadowMario/FNF-PsychEngine#11872]
### What is your question?

First of all i dont know where to put this issue so i just did it under question, its about downloading the engine. When trying to download psych engine, after writing "haxelib run hmm install" in Powershell an error comes up saying "Validation error: hmm.json not found in current working directory" I dont know what the problem is or even how to fix it. Does anyone know whats wrong?
![Screenshot 2023-02-08 181231](https://user-images.githubusercontent.com/124503824/217460025-cbaaab9c-b5fc-4703-b21d-b5a481ceaf58.png)

**Comment by TheKitBoi** [comment]
did u try 
haxelib run hmm setup

**Comment by Ratio-Combinder** [comment]
did u even add this
https://github.com/ShadowMario/FNF-PsychEngine/blob/main/hmm.json

**Comment by groovington43** [comment]
> did u even add this https://github.com/ShadowMario/FNF-PsychEngine/blob/main/hmm.json

where do you add it?

**Comment by superplayhero2** [comment]
download the psych repostiory 
then do
```
cd ToPsychsPath
```
and then do
```
haxelib run hmm install
```

**Comment by groovington43** [comment]
> > > download the psych repostiory (if not already downloaded) then do
> > > ```
> > > cd PathToPsych
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and then do
> > > ```
> > > haxelib run hmm install
> > > ```
> > 
> > 
> > how do you download the psych repository?
> 
> go here https://github.com/ShadowMario/FNF-PsychEngine then click code and click download zip <img alt="image" width="648" src="https://user-images.githubusercontent.com/89041944/217531425-32dfc891-df17-4c59-bd36-0af97ca8d68d.png">

Thanks, i tried doing "cd PathToPsych" didnt work so i then just did "C:\Users\(my name)\Downloads\FNF-PsychEngine-main and it worked so i hope its fine.

**Comment by superplayhero2** [comment]
> > > > download the psych repostiory (if not already downloaded) then do
> > > > ```
> > > > cd PathToPsych
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > and then do
> > > > ```
> > > > haxelib run hmm install
> > > > ```
> > > 
> > > 
> > > how do you download the psych repository?
> > 
> > 
> > go here https://github.com/ShadowMario/FNF-PsychEngine then click code and click download zip <img alt="image" width="648" src="https://user-images.githubusercontent.com/89041944/217531425-32dfc891-df17-4c59-bd36-0af97ca8d68d.png">
> 
> Thanks, i tried doing "cd PathToPsych" didnt work so i then just did "C:\Users(my name)\Downloads\FNF-PsychEngine-main" and it worked so i hope its fine.

i didn't literally mean "cd PathToPsych" i mean't the path you just did but eeh okay your welcome also close the issue

**Comment by ShadowMilky** [comment]
i request you to click the close issue button

**Comment by MemeHovy** [comment]
@groovington43 close this

**Comment by Grape-Boy** [comment]
close

**Comment by TerminallyAwesome** [comment]
it didnt work for me

**Comment by TerminallyAwesome** [comment]
nevermind
