### ISSUE TITLE
sprites crashing game

### ISSUE THREAD

**Issue by jotlees** [ShadowMario/FNF-PsychEngine#11884]
### Describe your bug here.

hey i just got done making sprites (and also had some pre made ones) and every time i go to load them in a chart they both crash the game. ones sprite sheet is very large the other not so much but i was wondering if this was a bug or just a issue. this hasn't happened before and it only recently started happening

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

only added 1 chart

**Comment by TheKitBoi** [comment]
Send the files on what’s causing it
