### ISSUE TITLE
Revamped Debugging

### ISSUE THREAD

**Issue by Itz-Miles** [ShadowMario/FNF-PsychEngine#11881]
### What feature do you want to get added on the **base** engine?

With a few changes made, debug traces to the terminal help detect and solve problems quite a lot! Once a compiled build is opened independently however, there's no terminal to print to. Adding a debug log option in settings or adding both lua and terminal output to the crash handler would solve issues before they happen.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
This would most likely make me need a debug build, which would have a lower performance
