### ISSUE TITLE
unknown error disaster

### ISSUE THREAD

**Issue by plotmanlover** [ShadowMario/FNF-PsychEngine#11882]
### Describe your bug here.

what the heck happen i did Death-Toll yesterday on chart and test it and did it on freeplay and it went well. and today now it just crashes idk why it wont let me in

[PsychEngine_2023-02-09_15'39'49.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/10701393/PsychEngine_2023-02-09_15.39.49.txt)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheKitBoi** [comment]
add the death-toll.json in the data/death-troll

**Comment by plotmanlover** [comment]
> add the death-toll.json in the data/death-troll

oh found it was my custom difficulty not on the right week
