### ISSUE TITLE
Sideways Scroll

### ISSUE THREAD

**Issue by xboomerboyx** [ShadowMario/FNF-PsychEngine#11883]
### Describe your problem here.

Hello, I am writing to ask if it is possible to make certain arrows have a sideways scroll. I would like to know how to, as it would help me with a mod I am making.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
What do you want is to look like

**Comment by xboomerboyx** [comment]
I am making the notes into a cross hair in the middle of the screen, and I am trying to make the left notes come from the left side, up notes from the top of the screen, and so on.
![crosshair](https://user-images.githubusercontent.com/122742140/217964032-a4593c6f-ea63-4bbc-9349-e8f17a625405.png)


> What do you want is to look like
