### ISSUE TITLE
help needed: game crashes using 1 song

### ISSUE THREAD

**Issue by fnfporterhi** [ShadowMario/FNF-PsychEngine#11895]
### Describe your problem here.

i converted a osu chart into psych engine (thanks maniaconverter), and when i try it, there’s a hard .json chart, but when i run it it gives me a crash handler. how do i fix this? 

also, i edited the BF model and the menu screen. besides that nothing changed

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, edited the BF model and edited the menu screen, and also added a couple of mods ported using the default characters

**Comment by CaptainBaldi** [comment]
yknow maybe it would help if you actually gave the crash error, just a thought

**Comment by fnfporterhi** [comment]
ill send it when i’m at home i’m at my grandparents rn

**Comment by fnfporterhi** [comment]
![Screenshot 2023-02-14 083429](https://user-images.githubusercontent.com/99343223/218753812-d96b3c7d-2b85-4688-9df9-b58ae5d74a7f.png)
theres the error it's weird

**Comment by fnfporterhi** [comment]
it's built under normal diff

**Comment by TheKitBoi** [comment]
is it even the-end.json

**Comment by fnfporterhi** [comment]
yes

**Comment by TheKitBoi** [comment]
And is it in the the-end folder at mods/data

**Comment by fnfporterhi** [comment]
yes, i have it both in the songs for the .ogg files, and the .json files in the data folder, under the-end.

**Comment by fnfporterhi** [comment]
fixed, just realized that it tried to default to hard instead of normal, had to change the lock diff.
