### ISSUE TITLE
after using noteTweenDirection lane flips 

### ISSUE THREAD

**Issue by Zbyszeq** [ShadowMario/FNF-PsychEngine#11897]
### Describe your bug here.

So...
i have been playing around with notes lateley, an I found a cool feature called noteTweenDirection.
Unfortunateley, it doesen't seem to work well.
after flipping the lane by 180° notes got flipped in x, also custom note texture is off centered.
![IMG_20230211_224751](https://user-images.githubusercontent.com/97297958/218282833-54a4a5b5-df0a-4b01-8f6d-5e3bb48f70ab.jpg)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheGithubPsychEngineFan** [comment]
It isn't a bug problem, It's just that the notetweendirection function is kinda buggy so of course the notes get off centered.
