### ISSUE TITLE
Galleries anyone?

### ISSUE THREAD

**Issue by Speedrunner-doomguy** [ShadowMario/FNF-PsychEngine#11893]
### Describe your problem here.

I'm working on a mod and would like to add a gallery in the main menu. Can anyone please tell me how to add it to the main menu or link me to what I need?

Preferable in source so that it can be hardcoded into the engine and have it on the main menu. I'd also like to avoid the lua script that just adds it to the freeplay menu like it's the plague but if I have no other option then I could work with it.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I've disabled achievements and am looking to add a gallery!

**Comment by MemeHovy** [comment]
learn to do it yourself and stop asking for people to code for you

**Comment by MemeHovy** [comment]
that's one way to get better at coding really, trial and error

**Comment by Speedrunner-doomguy** [comment]
okay? I'm working on that anyways though I figured it'd be worth a shot

**Comment by BernardoGP4504** [comment]
Just create a new state (FlxState) by creating it yourself

**Comment by Speedrunner-doomguy** [comment]
is- is it really that easy? I just gotta make a new state by making it? nice

**Comment by BernardoGP4504** [comment]
> is- is it really that easy? I just gotta make a new state by making it? nice

Yes and no, while needed you still need to code the whole gallery

**Comment by Speedrunner-doomguy** [comment]
seems about right lol, thanks for the aid

**Comment by BernardoGP4504** [comment]
> seems about right lol, thanks for the aid

Btw, for the base overall shape of the file, you can use any file that ends with `State` as a template

**Comment by Speedrunner-doomguy** [comment]
> Btw, for the base overall shape of the file, you can use any file that ends with `State` as a template

aight gotchu

**Comment by Speedrunner-doomguy** [comment]
I'm currently working with a friend on it! pretty soon we'll have it completed and even have custom music built into the menu change! Imma close the issue from here on out so thanks yall
