### ISSUE TITLE
Randomised sprite on state load?

### ISSUE THREAD

**Issue by TheLegion00** [ShadowMario/FNF-PsychEngine#11894]
### Describe your problem here.

I'm curious as to how I can implement a sprite that is randomised from an array every time it is loaded.
E.g. If I were to open the main menu (load 1), go into freeplay, and then back to the main menu again (load 2).

Thanks in advance!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not relevant.

**Comment by BernardoGP4504** [comment]
```haxe
var sprite:FlxSprite;

switch(FlxG.random.int(0, 1)) {
    case 0:
        sprite = new FlxSprite(0, 0).loadGraphic(Paths.image('spriteimg1'));
        add(sprite);
    case 1:
        sprite = new FlxSprite(0, 0).loadGraphic(Paths.image('spriteimg2'));
        add(sprite);
}
```
If you want more sprite alternatives, change the second number in the `random.int` function and add another case.

Also `spriteimg` is the image your going to use in your sprite and the numbers in FlxSprite are coordenates.

And sorry for any grammar mistakes, English is not my main language
