### ISSUE TITLE
Friday night funkin character problem

### ISSUE THREAD

**Issue by KaptainChris** [ShadowMario/FNF-PsychEngine#11892]
### Describe your problem here.

I am using the psych engine and when I go into chart editor the character, I am making is working fine, but when I add it to a story mode song in Freeplay it just goes into this java scrip thing that I don't know how to fix it! I don't know anything about the modding source and target so ignore that if you see it!
![image](https://user-images.githubusercontent.com/125098984/218222113-6d727149-4af7-4e9a-bec2-6a2d6c2b1afc.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by KaptainChris** [comment]
I am new to modding the psych engine, so everything is new to me and difficult! If you need more information, say it below in a comments!

**Comment by TheKitBoi** [comment]
missing image file
tell us where

**Comment by KaptainChris** [comment]
Where could I find it?

**Comment by KaptainChris** [comment]
I have added the image of the character in the mod character section, assets, character

**Comment by KaptainChris** [comment]
I feel like I added it everywhere possible! The assets outside of the mods folder and inside the mods folder!

**Comment by KaptainChris** [comment]
@TheKitBoi where should I go to not have the missing image file?

**Comment by TheKitBoi** [comment]
from the character you made

**Comment by KaptainChris** [comment]
@TheKitBoi I think I found the problem and it's with the .json file! I saved it from the character editor and added it on to the characters in the correct place it's just that there is a problem with the file, and I don't know if you need to save your character a different place. I can't talk right now because I have to do other things, but I will ping you when I get back and I am ready to do more things. You can leave your answer here and wait for me to speak.

**Comment by TheKitBoi** [comment]
is the image file name same as the json inupt

**Comment by KaptainChris** [comment]
@TheKitBoi for some reason when i get out of the tabs in the files and go back the capital letters change to the little l when I had it to this L

**Comment by BernardoGP4504** [comment]
> I have added the image of the character in the mod character section, assets, character

The image is supposed to be in mods/images/characters or assets/shared/images/characters

**Comment by KaptainChris** [comment]
Ok I will try to do that!

**Comment by KaptainChris** [comment]
@BernardoGP4504 every time I try to rename the image inside of mods/images/characters it keeps on renaming itself to have a capital letter on it when it's not supposed to! Do I have to remake the sprite and rename it something else?

**Comment by BernardoGP4504** [comment]
> @BernardoGP4504 every time I try to rename the image inside of mods/images/characters it keeps on renaming itself to have a capital letter on it when it's not supposed to! Do I have to remake the sprite and rename it something else?

First rename it without the first letter then put the letter back

**Comment by BernardoGP4504** [comment]
That's a issue from Windows itself

**Comment by BernardoGP4504** [comment]
> it keeps on renaming itself to have a capital letter on it when it's not supposed to!


That's a issue from Windows itself

**Comment by KaptainChris** [comment]
@BernardoGP4504 it only works in when I am charting a song from the menu, but when I go to the actual song in Freeplay it doesn't work! Is that a bug or is that how it works?

**Comment by BernardoGP4504** [comment]
> @BernardoGP4504 it only works in when I am charting a song from the menu, but when I go to the actual song in Freeplay it doesn't work! Is that a bug or is that how it works?

Wdym? The character doesn't appear in the song or the character doesn't work?

**Comment by TheKitBoi** [comment]
> @BernardoGP4504 it only works in when I am charting a song from the menu, but when I go to the actual song in Freeplay it doesn't work! Is that a bug or is that how it works?

did u even save the json

**Comment by KaptainChris** [comment]
@TheKitBoi I don't know if I saved it correctly, but I saved it to my computer and it's on here and it's in files! I don't know if I have to save it a different way if there is tell me!

**Comment by TheKitBoi** [comment]
which location

**Comment by BernardoGP4504** [comment]
> @TheKitBoi I don't know if I saved it correctly, but I saved it to my computer and it's on here and it's in files! I don't know if I have to save it a different way if there is tell me!

The json has to go in mods/characters
But the spritesheet and xml goes in mods/images/characters

**Comment by KaptainChris** [comment]
@BernardoGP4504 I did exactly that and took it away from unneeded places and it still doesn't work. The files are correctly renamed and everything and it only works in chart editor and not in Freeplay

**Comment by BernardoGP4504** [comment]
> @BernardoGP4504 I did exactly that and took it away from unneeded places and it still doesn't work. The files are correctly renamed and everything and it only works in chart editor and not in Freeplay

But what do you mean by "doesn't work"?

**Comment by KaptainChris** [comment]
@BernardoGP4504 It still shows the same picture as above (the JavaScript logo) in normal Freeplay mode while in the chart editor the sprite works really well! this is psych engine by the way if it changes anything

**Comment by TheKitBoi** [comment]
then did you even save the chart

**Comment by TheKitBoi** [comment]
also send the script code

**Comment by KaptainChris** [comment]
@TheKitBoi I didn't really code I looked at tutorials about making a mod without code and I used xml sheets

**Comment by BernardoGP4504** [comment]
> @TheKitBoi I didn't really code I looked at tutorials about making a mod without code and I used xml sheets

He meant the json file

**Comment by KaptainChris** [comment]
@TheKitBoi 

https://user-images.githubusercontent.com/125098984/218564884-b52fc8e6-f8c6-43a3-8df7-eb5bf41ac0a4.mp4

**Comment by TheKitBoi** [comment]
rename .json to .txt and send it here

**Comment by BernardoGP4504** [comment]
> @TheKitBoi
> FlowLab.-.Notepad.2023-02-13.15-11-56.mp4

Maybe try removing the loop animations (since you're not using them) and make sure the XML names on the json are right

**Comment by KaptainChris** [comment]
@TheKitBoi How do I do that because for me it doesn't work?

**Comment by BernardoGP4504** [comment]
> @TheKitBoi How do I do that because for me it doesn't work?

Create a copy of the json (Ctrl+C then Ctrl+V) then make sure you have "show file extensions" enabled then rename .json on the file to .txt then send it here

**Comment by KaptainChris** [comment]
It is not working for me to get the extention because I need something I don't have on the computer :(

**Comment by BernardoGP4504** [comment]
> It is not working for me to get the extension because I need something I don't have on the computer :(

Just go in the file explorer settings and enable file extensions from there

**Comment by KaptainChris** [comment]
YOOO I DID IT :DDDDDDD There you go!
[FlowLab - Copy.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/10726391/FlowLab.-.Copy.txt)

**Comment by TheKitBoi** [comment]
i may need the image files for easier fixing

**Comment by KaptainChris** [comment]
@TheKitBoi I can show you a video of the XML files so you can see, but I can't share it to you directly

**Comment by KaptainChris** [comment]
![XML](https://user-images.githubusercontent.com/125098984/218593741-40cb5158-c47a-41b0-a77c-aa877b5083d3.png)
![Screenshot 2023-02-13 175905](https://user-images.githubusercontent.com/125098984/218593743-f1c97ac6-5d14-40e0-962d-773607c3c96b.png)
![E](https://user-images.githubusercontent.com/125098984/218593745-d5314890-f971-4f44-9b54-b54804be1812.png)

**Comment by TheKitBoi** [comment]
[FlowLab.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/10726966/FlowLab.txt)
here

**Comment by KaptainChris** [comment]
Still the same product
![image](https://user-images.githubusercontent.com/125098984/218595035-c8a31111-8867-418a-99c3-7209499d2695.png)

**Comment by KaptainChris** [comment]
@TheKitBoi while it works in charting mode
![image](https://user-images.githubusercontent.com/125098984/218595647-ed87c7a8-56a1-43ae-9157-2c2e550cce5b.png)

**Comment by TheKitBoi** [comment]
show the chart your using

**Comment by KaptainChris** [comment]
XML?

**Comment by KaptainChris** [comment]
![E](https://user-images.githubusercontent.com/125098984/218597847-5f336d47-df5c-4c1c-989c-58d7c72d1386.png)
![XML](https://user-images.githubusercontent.com/125098984/218597851-0c93912a-3195-4934-b5b2-e32a958279fb.png)
![Screenshot 2023-02-13 175905](https://user-images.githubusercontent.com/125098984/218597852-0e76c122-4dd2-484e-82ab-9b7784683641.png)

**Comment by KaptainChris** [comment]
What do you mean @TheKitBoi

**Comment by KaptainChris** [comment]
It is the "test" song, and I am using psych engine to chart this mod.

**Comment by TheKitBoi** [comment]
then did u even save the chart

**Comment by KaptainChris** [comment]
No

**Comment by KaptainChris** [comment]
Was I supposed to for it to work?

**Comment by TheKitBoi** [comment]
you need to save the chart to get the char working

**Comment by TheKitBoi** [comment]
yes save the chart

**Comment by KaptainChris** [comment]
Well I was looking for the animations

**Comment by KaptainChris** [comment]
@TheKitBoi you're saying that if I want the song to work, I have to chart it first, then save it and then it works?

**Comment by TheKitBoi** [comment]
yes

**Comment by KaptainChris** [comment]
I will update you soon once I chart the song I am doing.

**Comment by KaptainChris** [comment]
@TheKitBoi @BernardoGP4504 The character stopped working and I can't fix it for some reason! I need help so here is the txt and the Xml sheet is below!
[Flowlab.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/10761111/Flowlab.txt)
![image](https://user-images.githubusercontent.com/125098984/219493819-2b5ef036-f6bc-4c71-aaf5-3c3ff4db1801.png)
![image](https://user-images.githubusercontent.com/125098984/219493886-74ebbca5-dfd3-4b9f-836a-d7d0bc0e7869.png)

**Comment by KaptainChris** [comment]
Also just so you guys know I made sure it was in the right places and it still wouldn't work! I myself will experiment some more, but you guys have more knowledge than me!

**Comment by BernardoGP4504** [comment]
> 

Can you also send the XML as a txt file and send the PNG?

**Comment by KaptainChris** [comment]
I don't want to get my Idea stolen tho!

**Comment by KaptainChris** [comment]
@BernardoGP4504 could you try to find the issue with that?

**Comment by BernardoGP4504** [comment]
> @BernardoGP4504 could you try to find the issue with that?

Sure

**Comment by KaptainChris** [comment]
@BernardoGP4504 Thank you!

**Comment by TheKitBoi** [comment]
> I don't want to get my Idea stolen tho!

then send in a private dm
Thekitboi#9705

**Comment by KaptainChris** [comment]
> > I don't want to get my Idea stolen tho!
> 
> then send it in a private dm Thekitboi#9705

I dont want you guys to steal it!

**Comment by TheKitBoi** [comment]
why are you getting serious of keeping your assets
there not even good to begin with
also we cant fix your issue unless you provide the assets

**Comment by BernardoGP4504** [comment]
> > > I don't want to get my Idea stolen tho!
> > 
> > 
> > then send it in a private dm Thekitboi#9705
> 
> I dont want you guys to steal it!

Yeah I kinda see your point but without the assets, we can't see what's the issue with your character

**Comment by KaptainChris** [comment]
@TheKitBoi @BernardoGP4504 Who do I dm?

**Comment by TheKitBoi** [comment]
if you have discord Thekitboi#9705
if you don’t have it
any alternatives

**Comment by KaptainChris** [comment]
I dont have discord!

**Comment by TheKitBoi** [comment]
then any alternatives

**Comment by KaptainChris** [comment]
Flowab Community page Dms tell me your user if you make one!

**Comment by TheKitBoi** [comment]
![C1014D32-7A64-4AA9-85AB-7D58E0A82524](https://user-images.githubusercontent.com/84044666/219893600-d50b97c2-b020-49a4-973f-aaac4f455b07.jpeg)
here

**Comment by KaptainChris** [comment]
send me the link to your profile

**Comment by TheKitBoi** [comment]
https://community.flowlab.io/u/thekitboi/summary

**Comment by KaptainChris** [comment]
@TheKitBoi Is it alright if I could only send you the idle animation for it because on flowlab it is saying the file is too large!

**Comment by TheKitBoi** [comment]
Try catbox uploader

**Comment by KaptainChris** [comment]
@TheKitBoi I have uploaded them the link is on flowlab

**Comment by TheKitBoi** [comment]
![image](https://user-images.githubusercontent.com/84044666/220202312-8581557e-5736-405c-ae43-b9d2361fc72c.png)

cant send messages on this site at the moment 
ima send the test footage here

**Comment by TheKitBoi** [comment]
https://user-images.githubusercontent.com/84044666/220203560-c672fc82-4cb8-46ea-86ff-fed06ef448bf.mp4

**Comment by KaptainChris** [comment]
@TheKitBoi Oh No! I didn't know that could happen lol! You should visit the site more often to be able to talk a lot more! You can send the test footage here for now

**Comment by KaptainChris** [comment]
@TheKitBoi How did you get it working!

**Comment by KaptainChris** [comment]
@TheKitBoi I will try to make a new Dm place in flowlab community and tell me if it works for you there!

**Comment by TheKitBoi** [comment]
ima send you the files

**Comment by TheKitBoi** [comment]
[Fixed.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/10787989/Fixed.zip)

**Comment by KaptainChris** [comment]
Could you delete the files now!!

**Comment by KaptainChris** [comment]
I got em already!

**Comment by KaptainChris** [comment]
Like the message!

**Comment by KaptainChris** [comment]
@TheKitBoi Thank You! Now it is time to make stuff happen!

**Comment by KaptainChris** [comment]
@TheKitBoi where do the files go again!

**Comment by TheKitBoi** [comment]
[Fixed.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/10788006/Fixed.zip)

**Comment by KaptainChris** [comment]
No, like mods/??

**Comment by KaptainChris** [comment]
@TheKitBoi also delate that post too lol

**Comment by TheKitBoi** [comment]
still cant message in flowlab

**Comment by KaptainChris** [comment]
@TheKitBoi you are my savior I got it to work and its thanks to you guys for helping. I thank you guy so much! If I need any more help I will ask, but thank you so much!

**Comment by KaptainChris** [comment]
When I say "I got" I meant I was able to put everything together in the files correctly lol!

**Comment by TheKitBoi** [comment]
did it work

**Comment by KaptainChris** [comment]
@TheKitBoi Yes, the character was able to move and do its stuff! Could I use the .json file and make some changes to the code in there and will the characters work fine, but with the change?

**Comment by TheKitBoi** [comment]
yes

**Comment by KaptainChris** [comment]
@TheKitBoi How do you shrink the character?

**Comment by TheKitBoi** [comment]
change the scale number

**Comment by KaptainChris** [comment]
@TheKitBoi How about to flip the character?

**Comment by KaptainChris** [comment]
Nevermind I found it lol!

**Comment by KaptainChris** [comment]
@TheKitBoi I have been seeing this combo thing that would pop up sometimes while you're gaming in fnf, I was wondering if you knew how I could add it into my mod!
![image](https://user-images.githubusercontent.com/125098984/220719658-013f04ea-7a6c-41dd-8115-0a23e42071d6.png)

**Comment by BernardoGP4504** [comment]
> @TheKitBoi I have been seeing this combo thing that would pop up sometimes while you're gaming in fnf, I was wondering if you knew how I could add it into my mod! ![image](https://user-images.githubusercontent.com/125098984/220719658-013f04ea-7a6c-41dd-8115-0a23e42071d6.png)

Pretty sure there's a script for that

**Comment by KaptainChris** [comment]
@TheKitBoi do you think you know where I could get the script?

**Comment by BernardoGP4504** [comment]
> @TheKitBoi do you think you know where I could get the script?

Just search "note combo script psych engine" on youtube

**Comment by KaptainChris** [comment]
alright!

**Comment by KaptainChris** [comment]
@TheKitBoi @BernardoGP4504 any of you guys could answer, but I was wondering if there was a way to make the icons for the hp bar animated? If you have an idea then take me to the place, I can add that to my mod please and thank you!
![image](https://user-images.githubusercontent.com/125098984/225415546-7b0945b2-60b5-46d1-b6e7-fbd4702cc83e.png)
