### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by StelUsing** [ShadowMario/FNF-PsychEngine#11906]
### Describe your problem here.

Im trying to compile psych's engine source code, but when i do **lime test windows**, it comes up with an error.
Error: Could not find include file "C:/HaxeToolkit/haxe/lib/hxCodec/2,6,1/vlc/lib/LibVLCBuild.xml"

Can anyone help me fix this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
haxelib remove hxCodec
haxelib install hxCodec 2.5.1

**Comment by RCrewmate** [comment]
when i do this i just get the errors:
source/PlayState.hx:74: characters 8-28 : Type not found : hxcodec.VideoHandler
source/PlayState.hx:1519: characters 13-25 : Type not found : VideoHandler
i already have hxCodex 2.5.1 installed
