### ISSUE TITLE
hay shadowmario. heres a new bug.

### ISSUE THREAD

**Issue by letsa-fuck-people** [ShadowMario/FNF-PsychEngine#11900]
### Describe your bug here.

so almost NO ONE ON THIS PLANET has experienced this bug. except me.
what i mean by this is the makeLuaSprite And/or addLuaSprite functions DOES NOT WORK FOR ME if i try to load a stage,
BLACK BG. if i try to make a event with images, NO SPRITE. etc. if any one has experienced this,
1. tell me how to fix it.
2. i can die happy.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no.

**Comment by frantastic24** [comment]
It's not a bug and you're not the only one
You need a better graphics card

**Comment by Jevilm** [comment]
Use onCreate() or onCreatePost(), stop using onUpdatePost()

**Comment by FunkoDev** [comment]
skill issue

**Comment by letsa-fuck-people** [comment]
> skill issue

shut up

**Comment by FunkoDev** [comment]
> > skill issue
> 
> shut up

ok 👍

**Comment by letsa-fuck-people** [comment]
> Use onCreate() or onCreatePost(), stop using onUpdatePost()

it doesnt work
