### ISSUE TITLE
how do I stop this from happening?

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#11901]
### Describe your problem here.

When I use my healthbar image, the image goes down and the bar gets extended. How can I fix that?
![Screenshot_20230211-213043-082](https://user-images.githubusercontent.com/101405920/218286975-30af3c33-d747-4058-9870-95e051631766.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheKitBoi** [comment]
what image is it

**Comment by BernardoGP4504** [comment]
This one
![healthBar](https://user-images.githubusercontent.com/101405920/218287356-1c048ee7-1df8-4c5d-a484-8d88e0ea692d.png)

**Comment by TheKitBoi** [comment]
it's because it getting the amount of pixels the image has so i seperated into parts
![timeBar](https://user-images.githubusercontent.com/84044666/218287714-d2d560a1-3ddb-4c61-af9f-668eea2fb5ad.png)

![healthBarPart](https://user-images.githubusercontent.com/84044666/218287717-81e6b8e5-518a-4e1f-9118-690d6df2ac79.png)

and added offsets to it
```
function onCreate()
	makeLuaSprite('healthbarpart','healthBarPart', 339, 584)
	setObjectCamera('healthbarpart', 'camhud');
	addLuaSprite('healthbarpart')
end
```

**Comment by BernardoGP4504** [comment]
Now this happens:
![Screenshot_20230211-223239](https://user-images.githubusercontent.com/101405920/218288315-e8c76348-c2ee-4b07-9446-2ed9ab3f4276.png)

**Comment by BernardoGP4504** [comment]
Also ignore anything else except the healthbar

**Comment by BernardoGP4504** [comment]
> it's because it getting the amount of pixels the image has so i seperated into parts ![healthBar](https://user-images.githubusercontent.com/84044666/218287823-00298873-03c4-4d40-b6a7-d68b5d9a215b.png)
> 
> ![healthBarPart](https://user-images.githubusercontent.com/84044666/218287717-81e6b8e5-518a-4e1f-9118-6 90d6df2ac79.png)
> 
> and added offsets to it
> 
> ```
> function onCreate()
> 	makeLuaSprite('healthbarpart','healthBarPart', 339, 584)
> 	setObjectCamera('healthbarpart', 'camhud');
> 	addLuaSprite('healthbarpart')
> end
> ```

Alright, thanks! Also I had to adapt the script to work with downs roll but it works now. Thank you. Also do you happen to have any icon so I can credit you?

**Comment by TheKitBoi** [comment]
nah but you can use my pfp as an example

**Comment by BernardoGP4504** [comment]
> nah but you can use my pfp as an example

Ok, I made a custom icon based on ur pfp
But overall, thanks, it's for a android port
