### ISSUE TITLE
Add sections

### ISSUE THREAD

**Issue by SpiritualGo78** [ShadowMario/FNF-PsychEngine#11902]
### What feature do you want to get added on the **base** engine?

For the chart editor, I wish there was a feature to add a section mid-song without restarting since I forgot to add a section that contains no notes. Can someone also teach me how to use the chart json since if I try to add a section through the json. It just always duplicate on the other characters side or it doesn't show up at all.

### To test your sight, and reliability, please select the option of what should NOT be requested.

nothing

**Comment by Lorekeeper49** [comment]
Test = failed

**Comment by BeastlyGabi** [comment]
game automatically does that when going to another section, you can't add new sections if the song is over

**Comment by SpiritualGo78** [comment]
I’m saying mid-song, not at the end of the song.
