### ISSUE TITLE
A small bug regarding the opponent's icon.

### ISSUE THREAD

**Issue by ManMaster707** [ShadowMario/FNF-PsychEngine#11909]
### Describe your bug here.

(I wasn't able to give proof since this glitch occurs for only a split second, so bear with me.)

During my playthroughs, i've encountered a bug where if you pause, there's a small chance that the opponent's icon will snap to the far left of the hud for a split second, and then return to its default position.

I don't know what causes this, but it didn't happen in earlier versions (i'm using 0.6.3), and if it doesn't happen to anyone else i'm guessing it's one of the scripts i've added, but otherwise it's an actual bug.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i just added things trough the "mods" folder.

**Comment by CaptainBaldi** [comment]
ive never had this happen to me before, so it may be your scripts

**Comment by FunkoDev** [comment]
So me your scripts.
