### ISSUE TITLE
V

### ISSUE THREAD

**Issue by Unkrown6YT** [ShadowMario/FNF-PsychEngine#11919]
### What is your question?

Misses is a 'songmisses'
what about bpm, beat and step?

**Comment by ManMaster707** [comment]
In order of listing, their names are:

- `bpm` or `curBpm`;
- `curBeat`;
- `curStep`.

**Comment by Unkrown6YT** [comment]
> In order of listing, their names are:
> 
> * `bpm` or `curBpm`;
> * `curBeat`;
> * `curStep`.

Thanks
