### ISSUE TITLE
Moving the rating sprites

### ISSUE THREAD

**Issue by Nightmistlol** [ShadowMario/FNF-PsychEngine#11914]
### What is your question?

Okay so like, I have a stage with a "moving" background and I want the "SICK", "GOOD", "BAD" and "SHIT" rating text to move along with the background like in Ejected or Danger, is that possible?
I'm using lua btw.

**Comment by CaptainBaldi** [comment]
adjust the combo offset

**Comment by Lorekeeper49** [comment]
> adjust the combo offset

I think he wants to have the ratings fly by the camera when they appear;
In which case, the easiest way I can think of is to modify Unholywanderer's [Lua Editable Combo Ratings script](https://gamebanana.com/tools/9273) by adding `doTweenX` to it for each object.

**Comment by Nightmistlol** [comment]
> > adjust the combo offset
> 
> I think he wants to have the ratings fly by the camera when they appear; In which case, the easiest way I can think of is to modify Unholywanderer's [Lua Editable Combo and Ratings script](https://gamebanana.com/tools/9273) by adding `doTweenX` to it for each object.

Oh sick, tysm
