### ISSUE TITLE
I got everytime this error everywhere

### ISSUE THREAD

**Issue by Soeiz** [ShadowMario/FNF-PsychEngine#11918]
### Describe your problem here.

I got these 2 errors everytime I compile, and everywhere (every version)

source/Main.hx:78: characters 61-65 : Float should be Int
source/Main.hx:78: characters 61-65 : For optional function argument 'updateFramerate'

My PC has maybe an error, before it was the discord_rpc that was taking infinite time to download, reset my pc and now it's that.
I tried many things like deleting and re-installing things, etc. 
Could you help me please !!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
use flixel 4.11.0 and flixel addons 2.11.0 @Soeiz

**Comment by Soeiz** [comment]
It seems that I didn't had these, but the problem's still here ! Thanks anyway x)

**Comment by TheKitBoi** [comment]
replace Main.hx with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

**Comment by Soeiz** [comment]
Thanks mate !!
