### ISSUE TITLE
How to check if more than one note was hit?

### ISSUE THREAD

**Issue by Wojtazzzekkk** [ShadowMario/FNF-PsychEngine#11927]
### Describe your problem here.

Hi, I want to make something like in Vs Impostor where if you hit more than one note the screen zooms a bit but idk how to check if you hit more than one note

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Soeiz** [comment]
look at the combo var, like getProperty("combo")

**Comment by Wojtazzzekkk** [comment]
But It's combo, not double notes
