### ISSUE TITLE
custom health bar, kinda like dnb 3.0 and time bar

### ISSUE THREAD

**Issue by CleanerCosine14** [ShadowMario/FNF-PsychEngine#11921]
### Describe your problem here.

I am trying to position the healthbar from vs dave and bambi 3.0 and time bar but i dont what the size of the height or width the ui of the timebar/healthbar is. can someone please send me the code im doing it on source code. here the healthbar image.
![healthBarNew](https://user-images.githubusercontent.com/103971101/218873000-97284364-453d-494a-bcd8-6bf09a87def2.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

NULL

**Comment by TheKitBoi** [comment]
get it in here
https://github.com/FuseIsHere813/VsDave-3.0/blob/main/source/PlayState.hx
also good luck not getting the "omg not dave & bambi again"

**Comment by CleanerCosine14** [comment]
damn that quick. ty

**Comment by TheKitBoi** [comment]
close this issue
