### ISSUE TITLE
Lua events no longer working

### ISSUE THREAD

**Issue by 4wdthinks** [ShadowMario/FNF-PsychEngine#1192]
### Describe your bug here.

I have  been using the downloaded build for doing things for some time, but not long ago i switched to source code because lua  felt limiting.
I ported all my lua events and notes over but the lua events no longer work. I've checked them to see if there's outdated code but they all seemed to be up to date.

I can still make lua events, but previous ones are broken and dont do anything.

### Command Prompt/Terminal logs (if existing)
NONE

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Source code changes and lua stuff.

**Comment by ShadowMario** [comment]
You've probably put them in assets/ instead of mods/
