### ISSUE TITLE
weekBefore field is not respected properly.

### ISSUE THREAD

**Issue by ScarabWasTaken** [ShadowMario/FNF-PsychEngine#11920]
### Describe your bug here.

Here I attempt to add weeks between 2,3 and between 4,5
Both appear after week 7 in alphabetical order of filename.

Also did not work in previous versions.
Happens both in mod folder and assets folder.
Neither name of file nor "WeekName" are valid.

Only work around is to rename all weeks to not follow week# notation. But that also necessitates renaming the story list week pngs.

![image](https://user-images.githubusercontent.com/85250052/218850122-513c98c9-f2ea-408a-b13d-c95cb8308cec.png)
![image](https://user-images.githubusercontent.com/85250052/218850247-42543305-177e-4cc5-9cd1-52d1cd2fd8a5.png)
![image](https://user-images.githubusercontent.com/85250052/218850394-b5ef4087-f172-4f42-bdbe-9eafafd85dd8.png)
![image](https://user-images.githubusercontent.com/85250052/218850495-4c1c0c24-5845-46e3-8586-4c68f36c594d.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No source code changes. Clean 0.6.3

**Comment by TheKitBoi** [comment]
it supposed to be same as the file name 
week2e
week4e

**Comment by frantastic24** [comment]
`weekBefore` is for unlocking
Create `weekList.txt` if you want to order them manually

**Comment by ScarabWasTaken** [comment]
Ok I was misunderstanding.

Made a week list, but it seems placing it in mods folder does not override the one in assets folder. I have to edit the original one instead. And if i delete the OG and only have the one in mods folder it all still works except for tutrial being the last song for some reason.

So I guess I'll close this since its resolved and start a seperate report for WeekList not overriding.
