### ISSUE TITLE
Trigger source achievements using RunHaxeCode

### ISSUE THREAD

**Issue by TheLegion00** [ShadowMario/FNF-PsychEngine#11933]
### Describe your problem here.

I'm trying to figure out how to activate an achievement with a Lua script, as the mod I'm working on isn't hard coded into source, but nothing I do seems to work. 

I've tried to use a Lua script that `onSongEnd` runs Haxe code `Achievements.unlockAchievement(achievement);`, but it doesn't seem to work. I even tried variations without the `Achievements.` part or running it as an event but nothing has been successful yet. 
For context, I'm trying to shortcut to the `if (unlock)` code in PlayState.hx:
```
if(unlock) {
	Achievements.unlockAchievement(achievementName);
	return achievementName;
}
```
using this Lua script:
```
function onEndSong()
	runHaxeCode([[
		Achievements.unlockAchievement(achievementName);
	]])
end
```

Any advice?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Achievements and PlayState.hx

**Comment by CaptainBaldi** [comment]
yknow its onEndSong, not onSongEnd right?

**Comment by TheLegion00** [comment]
Sorry about that, just a typo. I used the correct function in the Lua script.

**Comment by Noel3454565FNF** [comment]
its working so if you still want it i can send it to you
