### ISSUE TITLE
Trying to make a dodge mechanic, but failing miserably...

### ISSUE THREAD

**Issue by Zer0PXL** [ShadowMario/FNF-PsychEngine#11937]
### Describe your problem here.

So, text pops up saying PRESS SPACE, if you press space, the screen should flash, if you don't, you die. But nothing works, the text pops up, you press space... Nothing happens... You don't press space... Nothing happens again...

Code :
function onUpdate()
	waiisrn = getProperty('curStep')
	keyboardJustPressed(key)
end

function onEvent(name, value1, value2)
	eventHit = waiisrn
	if name == "space action" then
		makeLuaText('text', value2, 770, 250, 620);
		setTextSize('text', '50') --text size 
		addLuaText('text', true);
		setObjectCamera('text', 'other');
		runTimer('delay', value1);
	end
end

function onStepHit()
	if waiisrn == eventHit + value1 then
		if key == 'space' then
			triggerEvent('Flash', "9999FF")
			playSound('hitsound')
		else
			setProperty('health', -69)
		end
	end
end

function onTimerCompleted(tag, loops, loopsleft)
	if tag == 'delay' then
		doTweenAlpha('disappear', 'text', 0, 0.3, 'linear');
	end
end

function onTweenCompleted(tag)
	if tag == 'disappear' then
		removeLuaText('text', true);
	end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Nightmistlol** [comment]
```
function onEvent(name, value1, value2)
    if name == "space action" then
        makeLuaText('text', value2, 770, 250, 620);
        setTextSize('text', '50') --text size
        addLuaText('text', true);
        setObjectCamera('text', 'other');
        runTimer('delay', value1);
        runTimer('deathTimer', value1);
        dodgeable = true;
    end
end

function onUpdate()
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SPACE') and dodgeable == true then
        triggerEvent('Flash', "9999FF")
        playSound('hitsound')
        cancelTimer('deathTimer')
        dodgeable = false;
    end
end

function onTimerCompleted(tag, loops, loopsleft)
    if tag == 'delay' then
        doTweenAlpha('disappear', 'text', 0, 0.3, 'linear');
    end
    if tag == 'deathTimer' then
        setHealth(-69)
    end
end

function onTweenCompleted(tag)
    if tag == 'disappear' then
        removeLuaText('text', true);
    end
end
```
This should work (I'm not good at coding but it worked when I tried.)

**Comment by Zer0PXL** [comment]
That works perfectly. Thank you very much!
