### ISSUE TITLE
How to bind the modchart key to other keys??? 😟 

### ISSUE THREAD

**Issue by lava4-LvLOG** [ShadowMario/FNF-PsychEngine#11939]
### What is your question?

Hey fellas I have a new idea for my modding...
that I want to bind the modchart keys(in Psych its 7) to another number like 1
How should I do???

(I want to made it in lua, cause when i pack i got thousand diffrent error.)

**Comment by Lorekeeper49** [comment]
There is an option to change the bind in the options menu under `controls` 
Also, modcharts are when the HUD elements move according to the song, the chart editor that you are referring to is just for placing the notes for the song

**Comment by lava4-LvLOG** [comment]
> There is an option to change the bind in the options menu under `controls` Also, modcharts are when the HUD elements move according to the song, the chart editor that you are referring to is just for placing the notes for the song

Sry I say it wrong, I mean chart editor key

**Comment by lava4-LvLOG** [comment]
> There is an option to change the bind in the options menu under `controls` Also, modcharts are when the HUD elements move according to the song, the chart editor that you are referring to is just for placing the notes for the song

and I want to made it in lua and let everyone who play the mod can only press 1 for using chart editor
Also my english sucks thx

**Comment by lava4-LvLOG** [comment]
> There is an option to change the bind in the options menu under `controls` Also, modcharts are when the HUD elements move according to the song, the chart editor that you are referring to is just for placing the notes for the song

and I want to made it in lua and let everyone who play the mod can only press 1 for using chart editor
Also my english sucks thx
