### ISSUE TITLE
Changing the Combo Numbers and Rating sprites camera.

### ISSUE THREAD

**Issue by YourRedditor** [ShadowMario/FNF-PsychEngine#11940]
### Describe your problem here.

I need help moving the Combo numbers and rating sprites to camGame instead of camHUD.
I tried using setProperty() and also runHaxeCode() but it wouldn't work for some reason or maybe because I'm just dumb.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheKitBoi** [comment]
replace the assets in the mods folder
with the same name files from the assets folder

**Comment by YourRedditor** [comment]
Forgot to mention that I also used setObjectCamera()

**Comment by YourRedditor** [comment]
'rating', 'comboSpr', And 'numScore'. Im not sure if I'm using the correct tags

**Comment by frantastic24** [comment]
You can't afaik, you'll have to recreate them

**Comment by VoidedBattery** [comment]
Yeah, I experimented with those as well. Like frantastic24 says, yeah you might have to create some sort of artificial sprite system if you want to _guarantee_ a sprite change, but for now you might have to keep looking in the source code to find what you need.

**Comment by YourRedditor** [comment]
Alright, thanks for the help
