### ISSUE TITLE
Setting the 'antialiasing' property breaks object rendering

### ISSUE THREAD

**Issue by junetried** [ShadowMario/FNF-PsychEngine#11944]
### Describe your bug here.

I didn't find it in the documentation, but apparently according to #8157 it is possible to control antialiasing by running `setProperty('myobject.antialiasing', true/false)`. However, running this function at all, regardless of the true/false value, causes the object not to render.

Here is a minimum reproducible example:
```lua
function onCreate()
	makeLuaSprite("object", "any-image-you-want", 1280/2, 720/2)

	-- Change the boolean in the following line, nothing will happen.
	-- Comment the following line, and the object will be rendered.
	addProperty("object.antialiasing", false)

	addLuaSprite("object", false)
	close(true)
end
```

I have reproduced this with a [main branch](https://github.com/ShadowMario/FNF-PsychEngine/tree/9c30ee13acc75c6403f7479549163209dc53e715) Linux-native build and the [latest release at time of writing](https://github.com/ShadowMario/FNF-PsychEngine/releases/tag/0.6.3) using wine, with identical behavior.

My environment is openSUSE Tumbleweed snapshot 20230204, amd64, and wine 8.0.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing has been changed.

**Comment by CaptainBaldi** [comment]
idk what youre doing wrong this works fine for me

**Comment by junetried** [comment]
> idk what youre doing wrong this works fine for me

I'll try to set up a Windows environment to test in later, to see if that is a factor, but it shouldn't be. I don't know what else could be wrong if it works for you.

**Comment by junetried** [comment]
I just tested it in Windows 10, using the same build I linked above, with the same issue. @CaptainBaldi, are you running engine version 0.6.3?

**Comment by CaptainBaldi** [comment]
> I just tested it in Windows 10, using the same build I linked above, with the same issue. @CaptainBaldi, are you running engine version 0.6.3?

Yes, I'm testing on 0.6.3

**Comment by junetried** [comment]
Just figured it out. The original code works if I replace `addProperty` with `setProperty`. Then it works as expected.

Though, looking at [the Lua hooks](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/FunkinLua.hx), I can't find a function `addProperty` at all, so I have no idea why it would affect rendering or do anything at all other than throw an error.

**Comment by junetried** [comment]
> Incorrect functions stop the following code from running It's not affecting rendering, it's preventing `addLuaSprite` from running

That's strange. I would've expected any feedback at all from a script that returned an error. Oh well, that's a different issue. This one is solved.
