### ISSUE TITLE
/mods/weeks/weeklist.txt doesn't override /assets/weeks/weeklist.txt

### ISSUE THREAD

**Issue by ScarabWasTaken** [ShadowMario/FNF-PsychEngine#11942]
### Describe your bug here.

Mentioned in report 11920

Very simple straight forward

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheKitBoi** [comment]
dont make duplicates

**Comment by ScarabWasTaken** [comment]
wheres the duplicate

**Comment by TheKitBoi** [comment]
the one you made right here
theres the original https://github.com/ShadowMario/FNF-PsychEngine/issues/11941
and you made a duplicate relating in here

**Comment by TheKitBoi** [comment]
so close this

**Comment by ScarabWasTaken** [comment]
No this has nothing to do with the #11941
This i came across 4 days ago when I posted #11920

**Comment by NightmaresPlayz** [comment]
Did you have the same week image for the week list

**Comment by NightmaresPlayz** [comment]
If so, you have to have a different week image for the week to work I’m pretty sure, this happened to me before, I realised how to fix this so if it doesn’t work, I don’t know how to fix this

**Comment by ScarabWasTaken** [comment]
Image? What image? Why would weekList.txt have an image associated with it, and where is it?

Do you mean the individual week images used for story mode?

**Comment by NightmaresPlayz** [comment]
Yes
