### ISSUE TITLE
main.hx giving errors

### ISSUE THREAD

**Issue by EvertonPinwheel** [ShadowMario/FNF-PsychEngine#11946]
### Describe your problem here.

can someone help me?
everytime i build 0.4.2 game this error happens
``source/Main.hx:73: characters 61-65 : Float should be Int
source/Main.hx:73: characters 61-65 : For optional function argument 'updateFramerate'``
this never happened before

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

only images

**Comment by TheKitBoi** [comment]
replace Main.hx with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

**Comment by EvertonPinwheel** [comment]
> replace Main.hx with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx
didnt worked
now i have
``source/Main.hx:163: characters 2-9 : Unexpected package``

**Comment by FunkoDev** [comment]
Go back to the old ```
Main.hx```, and tell me what you changed.

**Comment by TheKitBoi** [comment]
> > didnt worked
> > now i have
> > `source/Main.hx:163: characters 2-9 : Unexpected package`

did you even replace it right

**Comment by EvertonPinwheel** [comment]
i already fixed it
nevermind
