### ISSUE TITLE
`setGraphicSize` and `scaleObject` have different behavior

### ISSUE THREAD

**Issue by junetried** [ShadowMario/FNF-PsychEngine#11945]
### Describe your bug here.

[The documentation claims](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#scaleobjectobjstring-multxfloat-multyfloat--0) that `scaleObject` is identical to `setGraphicSize`. However, they are not.

`scaleObject` works as expected, but `setGraphicSize` seems to break object rendering, so it doesn't render at all, even with values that the documentation claims are default.

Minimum reproducible example:
```lua
function onCreate()
	makeLuaSprite("object", "school-sd", 1280/2, 720/2)

	-- Try this with only the first line uncommented,
	-- then with only the second.
	--setGraphicSize("object", 1, 1)
	--scaleObject("object", 1, 1)

	addLuaSprite("object", false)
	close(true)
end
```

I'm not sure if this is a documentation issue, but it looks like a bug anyway so I've opened the issue using the bug report template.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing has been changed.

**Comment by CaptainBaldi** [comment]
this is indeed a documentation issue.
setGraphicSize sets the specified object to the exact amount of pixels specified
scaleObject, well, scales it.
I would not recommend using the official documentation, as it's outdated and isn't properly updated anymore, i would recommend using one of the fanmade documentations

**Comment by junetried** [comment]
> this is indeed a documentation issue. setGraphicSize sets the specified object to the exact amount of pixels specified scaleObject, well, scales it. I would not recommend using the official documentation, as it's outdated and isn't properly updated anymore, i would recommend using one of the fanmade documentations

I understand. I'll leave this issue open since it is an issue, but in the meantime can you link one of these documentations that might be more accurate?

**Comment by ManMaster707** [comment]
> I understand. I'll leave this issue open since it is an issue, but in the meantime can you link one of these documentations that might be more accurate?

 I personally use two (all credits go to the authors):
@Meme1079's wiki (https://github.com/Meme1079/PsychWiki/wiki),
and @CaptainBaldi's wiki (https://github.com/CaptainBaldi/PsychRewrittenWiki/wiki).

**Comment by XTihX1** [comment]
i think its bacause that two function has a last variable that updates the hitbox, try to use:

```
scaleObject("object", 1, 1, false);
setGraphicSize("object", 1, 1, false);
```

**Comment by junetried** [comment]
Wait, I'm confused. You closed the issue before updating the documentation. This issue should still be open, shouldn't it?
