### ISSUE TITLE
hxCodec not found

### ISSUE THREAD

**Issue by Nightmistlol** [ShadowMario/FNF-PsychEngine#11948]
### Describe your problem here.

I've been trying to compile Psych but I keep getting an error saying that hxCodec isn't found.
I have tried reinstalling hxCodec a few times as well as using 2.5.1 and the latest version, and none of them work.
(I don't need help with MP4Handler/VideoHandler, I already figured that out.)
```
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
Error: Could not find haxelib "hxCodec", does it need to be installed?
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I have only removed the vanilla songs.

**Comment by TheKitBoi** [comment]
is it the same install name
double check with haxelib install hxCodec 2.5.1

**Comment by Nightmistlol** [comment]
I uh... just figured it out-
I had to run the command in `C:\HaxeToolkit\haxe` instead of the source code folder.
