### ISSUE TITLE
Replaced Vanilla Weeks hidden from freeplay don't actually register.

### ISSUE THREAD

**Issue by ScarabWasTaken** [ShadowMario/FNF-PsychEngine#11941]
### Describe your bug here.

If you replace a vanilla week using the mods folder, then set "hideFreeplay": true. Going into freeplay will not process the replacing file because it is hidden from freeplay. Therefore it will not replace the original and will display it.
![image](https://user-images.githubusercontent.com/85250052/219951881-86e7c153-8774-449c-b7bb-c75d23d970b6.png)
Here I want to have a file that is freeplay only, and a file that is Story mode only. Meaning there's 3 files pertaining to this week:
/assets/week2.json
/mods/week2.json which is used for story mode and has "hideFreeplay": true
/mods/week2fp.json which is used for freeplay list and has "hideStoryMode": true

The workaround would obviously be to edit /assets/week2.json instead of using /mods/ folder, but I'd rather not.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ScarabWasTaken** [comment]
The inverse is also true
![image](https://user-images.githubusercontent.com/85250052/219952395-6990cca5-02a9-40e5-895a-80f529770d5e.png)

**Comment by TheKitBoi** [comment]
then press r in the freeplay and erase the save data to check
