### ISSUE TITLE
Cant Open Psych Engine

### ISSUE THREAD

**Issue by Fefols** [ShadowMario/FNF-PsychEngine#11956]
### Describe your problem here.

I cant run psych engine for some reason. Whenever I try to open the exe file nothing happens. I cant open any of the newer versions but 0.5.2h works. Does any one know what is going on?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ROCK201888** [comment]
delete C:\Users\usernameHere\AppData\Roaming\ShadowMario\PsychEngine\ninjamuffin99 folder
