### ISSUE TITLE
How do I initialize key settings?

### ISSUE THREAD

**Issue by paperpeak** [ShadowMario/FNF-PsychEngine#11957]
### Describe your problem here.

I changed all the key settings to enter, but I don't know how to reset it.

(I'm using a transducer. There could be misinterpretation.)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
why would you do that
also find C:\Users\pcname\AppData\Roaming\ShadowMario\PsychEngine\ninjamuffin99
and delete controls_v2.sol

**Comment by CaptainBaldi** [comment]
bro are you dumb why would you do that

**Comment by paperpeak** [comment]
Koreans can't stand being curious.

**Comment by paperpeak** [comment]
So do my friends.

**Comment by TheKitBoi** [comment]
Why the spam
