### ISSUE TITLE
Trying to build for html5 results in errors.

### ISSUE THREAD

**Issue by itsoutchy-projects** [ShadowMario/FNF-PsychEngine#11955]
### Describe your problem here.

Whenever I try to compile my mod for html5, it gives me these errors:
`source/FunkinLua.hx:2892: characters 25-39 : PlayState has no field runtimeShaders
source/FunkinLua.hx:2898: characters 45-49 : Class<Paths> has no field mods
source/FunkinLua.hx:2900: characters 35-39 : Class<Paths> has no field mods
source/FunkinLua.hx:2902: characters 20-33 : Class<Paths> has no field getGlobalMods
source/FunkinLua.hx:2902: characters 14-35 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/FunkinLua.hx:2903: characters 35-39 : Class<Paths> has no field mods
source/FunkinLua.hx:2907: characters 7-17 : Type not found : FileSystem`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5/Browser

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I modified PlayState.hx and ChartingState.hx to add a new events folder inside the preload path. I also added 2 new songs, their charts, a new BF character and edited the week 1 stage.

**Comment by EyeDaleHim** [comment]
Psych Engine isn't primarily built on Web targets in mind.

**Comment by itsoutchy-projects** [comment]
> Psych Engine isn't primarily built on Web targets in mind.

Oh dang.

**Comment by Ratio-Combinder** [comment]
but the fix will be coming
if he back to working on the engine
