### ISSUE TITLE
How to change tempo of song midway with lua?

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#11953]
### What is your question?

Check title

**Comment by Lorekeeper49** [comment]
First of all, there is no need to do this.
And secondly, that would mess with charting since charts rely on bpm and the note placement literally changes with bpm.
So just change the bpm/tempo with the chart editor, it's a lot easier

**Comment by NightmaresPlayz** [comment]
Ok okay
