### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MisterEGaming** [ShadowMario/FNF-PsychEngine#11951]
### Describe your problem here.

whenever i load my song i get the error,

Note.hx (line 158)
PlayState.hx (line 2499)
PlayState.hx (line 1087)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

i don't know know how to fix it...

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Ratio-Combinder** [comment]
your missing a note texture
