### ISSUE TITLE
How can I make animation play when notes are pressed

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#11960]
### What is your question?

Look up

**Comment by Lorekeeper49** [comment]
That's sort of default, you're gonna have to be a little more specific

**Comment by NightmaresPlayz** [comment]
So you know how notes are specified to the animation played by characters and in mods like DDTO Bad Ending, you can play animations while notes are being pressed. My notes are still tied to the specified animation instead of the one I want to use

**Comment by NightmaresPlayz** [comment]
I’ll show a video when I can

**Comment by Chidubemmo** [comment]
If I understod what you meant (in source)
```hx
if (note.noteData == 0) //left
{
boyfriend.playAnim('whatever');
}
else if (note.noteData == 1) //down
{
boyfriend.playAnim('whatever');
else if (note.noteData == 2) //up
{
boyfriend.playAnim('whatever');
else if (note.noteData == 3) //right
{
boyfriend.playAnim('whatever');
```

**Comment by frantastic24** [comment]
> you can play animations while notes are being pressed

No Animation notetype, you could've just looked at the chart

**Comment by NightmaresPlayz** [comment]
But it’s in lua

**Comment by NightmaresPlayz** [comment]
No it was normal note type like 0 note

**Comment by NightmaresPlayz** [comment]
Just Realised
