### ISSUE TITLE
Movie length songs

### ISSUE THREAD

**Issue by VSjnk** [ShadowMario/FNF-PsychEngine#11966]
### Describe your bug here.

when I tried to import the Shrek movie audio file into this engine, the game does  something very bizarre that is hard to explain.

Basically I get put into a soft locked state with the chart refusing to read.

I've tried to do the same in other engines but I keep getting the same error.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I am using a build from game banana

**Comment by MemeHovy** [comment]
and that it's named Inst and the voices being simply `Voices`

**Comment by TheKitBoi** [comment]
nope song length has be to 22 min and 30 secs on each part

**Comment by CaptainBaldi** [comment]
pretty sure this isn't a psych engine limitation but rather a haxe one

**Comment by Getsaa** [comment]
i mean... why would you try to run the Shrek movie in Psych Engine...

**Comment by VSjnk** [comment]
> i mean... why would you try to run the Shrek movie in Psych Engine...

Because why not! I want the world record for the longest single fnf song in the game. I know a shrek mod already exists but I want it in one song, not split into 5 different songs

**Comment by Getsaa** [comment]
bro answered 3 months later
