### ISSUE TITLE
Can anyone explain this?

### ISSUE THREAD

**Issue by PotatoKing0419** [ShadowMario/FNF-PsychEngine#11968]
### Describe your problem here.

I tried going into a custom week in the story menu and this popped up.
How do I make it uhh... not do this?
![Screenshot 2023-02-22 193625](https://user-images.githubusercontent.com/92553022/220816624-aeff14a0-656f-4a5c-b2a8-7c90d41412cc.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CleanerCosine14** [comment]
you gotta make a charting for it so create the shop folder on the data folder in assets/data. And then once you finished charting. move it to your shop folder and once you have done that. enjoy. now close this issue

**Comment by PotatoKing0419** [comment]
forgot to close this, sorry
