### ISSUE TITLE
How can I go about using LUA scripts to remove the automatic camera zoom on beat hits?

### ISSUE THREAD

**Issue by TurkIsTwisted** [ShadowMario/FNF-PsychEngine#11967]
### Describe your problem here.

Specifically I'm looking for some kind of code that can both get rid of the cam zooms that happen automatically while still allowing event based cam zooms to happen.

I asked on Gamebanana and got "setPropertyFromClass('ClientPrefs', 'camZooms', false)"
I tried it out and that one simply stops all cam zooms from happening, which I don't want. The person who helped me out on GB initially also suggested "setPropertyFromClass('ClientPrefs', 'camZooms', false)" but that ended up not doing anything.

I've already also tried looking around YT and generally outside of it and couldn't find anything related to my specific issue. Help would be super appreciated!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by PotatoKing0419** [comment]
> ### Describe your problem here.
> Specifically I'm looking for some kind of code that can both get rid of the cam zooms that happen automatically while still allowing event based cam zooms to happen.
> 
> I asked on Gamebanana and got "setPropertyFromClass('ClientPrefs', 'camZooms', false)" I tried it out and that one simply stops all cam zooms from happening, which I don't want. The person who helped me out on GB initially also suggested "setPropertyFromClass('ClientPrefs', 'camZooms', false)" but that ended up not doing anything.
> 
> I've already also tried looking around YT and generally outside of it and couldn't find anything related to my specific issue. Help would be super appreciated!
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> Nope

function onUpdate(elapsed)
	setProperty('camZooming', false)
end

**Comment by TurkIsTwisted** [comment]
> function onUpdate(elapsed) 
> setProperty('camZooming', false) 
> end

This is definitely a step in the right direction but now there's a new problem in that cam zoom events now simply zoom in the camera permanently. Any ideas?

**Comment by Lorekeeper49** [comment]
> > function onUpdate(elapsed) 
> > setProperty('camZooming', false) 
> > end
> 
> This is definitely a step in the right direction but now there's a new problem in that cam zoom events now simply zoom in the camera permanently. Any ideas?
> 

I'm pretty that's an issue with there being no notes.  For context, when you use the `Add Cam Zoom` event before a note has been hit, there's this weird glitch where it will stay zoomed in until a note is hit (which side the note is hit on doesn't matter).

**Comment by TurkIsTwisted** [comment]
>I'm pretty that's an issue with there being no notes. For context, when you use the Add Cam Zoom event before a note has been hit, there's this weird glitch where it will stay zoomed in until a note is hit (which side the note is hit on doesn't matter) and then it will go back to normal.

I'm aware of this glitch, I've had it happen to me before. Except this is pretty much the same exact glitch but it happens no matter what. I have cam zoom events placed after notes are hit for testing and they cause the camera to stay perma-zoomed despite there being notes prior to it.

**Comment by frantastic24** [comment]
> Specifically I'm looking for some kind of code that can both get rid of the cam zooms that happen automatically while still allowing event based cam zooms to happen.

This should work
```lua
function onCreate() -- onCreatePost() if it fails
    setProperty('camZoomingMult', 0)
end
```


> For context, when you use the Add Cam Zoom event before a note has been hit, there's this weird glitch where it will stay zoomed in until a note is hit

It's not a glitch, it's behavior from the base game where `camZooming` will stay false until the opponent hits a note, then the camera will zoom accordingly
There's no song in vanilla where bf sings first so no workaround was necessary

**Comment by TurkIsTwisted** [comment]
>function onCreate() -- onCreatePost() if it fails
>    setProperty('camZoomingMult', 0)
>end

ok this worked PERFECTLY, thank you so so sooo much
