### ISSUE TITLE
Custom Options For Da Game.

### ISSUE THREAD

**Issue by AyMarte** [ShadowMario/FNF-PsychEngine#11963]
### What is your question?

Is there any way I can add custom options into the base game without editing the source code of the main game.

## What Version Of The Engine Are You Using?
I am using v0.6.3 version.
## Have You Edited The Source Code?
No, I haven't even put a single scratch on it.

**Comment by MemeHovy** [comment]
no you can't @AyMarte

**Comment by AyMarte** [comment]
ok
