### ISSUE TITLE
Inconsistent camera position when character is flipped

### ISSUE THREAD

**Issue by junetried** [ShadowMario/FNF-PsychEngine#11969]
### What feature do you want to get added on the **base** engine?

I consider this a bug, but it looks like intended behavior, or more likely a hack, so I'm tagging this as a feature request.

When you create a character, their camera offset is broken if you flip the X axis of the character. You can enter the character editor and toggle "Playable Character" to see this in action. Here's an example:

![camera](https://user-images.githubusercontent.com/22205580/220887565-dc1f75c3-6eab-42ea-ac38-29830d92a4cb.png)

Working around this currently requires silly hacks, like having a redundant character file with different camera values.

The cause is an inconsistent camera offset position. In the example above you can set Senpai's camera offset to [0, 0] and observe that the camera is placed in the middle of the stage, but when enabling "Playable Character" the camera is now somehow placed behind him.

Changing this behavior is a breaking change.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
It's not unintended, it's just the same values used on Base game's code for the camera.

**Comment by junetried** [comment]
> It's not unintended, it's just the same values used on Base game's code for the camera.

I disagree that being the same behavior as the base game makes it a bug unworthy of being fixed.

Could it at least be opt out? There could be a field like "consistent camera positions" that defaults to false, and when true, fixes this bug.
