### ISSUE TITLE
how can i make the opponent icons shake?

### ISSUE THREAD

**Issue by Tamir-YT** [ShadowMario/FNF-PsychEngine#11975]
### What is your question?

how can i make the opponent icons shake?. and also a screen bug script like the latest spongebob mod that 1up animations composed on

(works for 0.6.2)

**Comment by VoidedBattery** [comment]
You can make a script that changes the position of the icons randomly when onUpdatePost() is called

**Comment by Shaggers-official** [comment]
You can try this code for the opponent icon shake (original in Ourple Guy v2) : 
```
function onUpdate(elapsed)
    local angleOfs = math.random(-5, 5)
    setProperty('iconP2.angle', angleOfs)
end
```

**Comment by NotStampyC** [comment]
This code is longer but more controllable and understandable

local turnvalue = 0 --Dont Touch this

function onBeatHit()
turnvalue = 4 --Backwards
if curBeat % 2 == 0 then
turnvalue = -2 --Forewards
end
--Dont Touch any of this code down here

setProperty('iconP2.angle',-turnvalue)
setProperty ('iconP1.angle',turnvalue)
doTweenAngle ('iconTween1','iconP1',0,crochet/1000,'circIn')
doTweenAngle ('iconTween2','iconP2',0,crochet/1000,'circIn')
end

function onCreatePost()
setObjectOrder('iconP1',getObjectOrder('iconP2'))
end

**Comment by nico2019374** [comment]
can i make this in source code?
