### ISSUE TITLE
Hundredths decimal character scaling

### ISSUE THREAD

**Issue by GWEjbik** [ShadowMario/FNF-PsychEngine#11978]
### What feature do you want to get added on the **base** engine?

Being able to scale characters like 0.45, 0.85, 0.23 and so on
I know i'm not the only one that has problems with their character being too big or too small
I hope i explained it well

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by Ratio-Combinder** [comment]
you failed the test plus edit the json character scale to pass it

**Comment by ShadowMario** [comment]
Invalid due to sight/reliability test fail
