### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nmslq** [ShadowMario/FNF-PsychEngine#11977]
### Describe your problem here.

When I load a song, it will crash.
link: https://github.com/nmslq/FNF-PsychEngine-Android-Support

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

**Comment by EyeDaleHim** [comment]
Invalid help, ask instead in that repository's Issue tab instead.

**Comment by Ratio-Combinder** [comment]
> ### Describe your problem here.
> When I load a song, it will crash.

dumbass
https://github.com/nmslq/FNF-PsychEngine-Android-Support/issues

**Comment by EyeDaleHim** [comment]
This is the wrong place to ask for help, report the issue into that repository's issue tab, please read and do not be disrespectful.

**Comment by EyeDaleHim** [comment]
If you are having trouble creating issues, please click the green `New issue` button in the repository's `Issue` tab, from there, find `Bug report` and click `Get started`. From there, fill out the required information.
