### ISSUE TITLE
How to add animated sprites in event

### ISSUE THREAD

**Issue by NicklGames** [ShadowMario/FNF-PsychEngine#1197]
### Describe your problem here.

I wanna spawn an animated sprite whenever the event is triggered
I say that there's an object i wanna spawn and i tell where are frames for this object:
![image](https://user-images.githubusercontent.com/60806448/142727337-dc417cd9-e38c-42aa-93c4-f9fc00861797.png)
Then I say that the frames i added earlier are the frames for the object and add an animation:
![image](https://user-images.githubusercontent.com/60806448/142727390-e2abdd1f-6af0-4c1d-99f8-ab9e31b53ac4.png)
![image](https://user-images.githubusercontent.com/60806448/142727615-a38d9182-7d12-4f97-a819-83ce49274754.png)

Then I spawn the object and make in into the center:
![image](https://user-images.githubusercontent.com/60806448/142727435-b7a6e0b4-9275-4142-9878-d774c9bb6870.png)
And that's what it spawns:
![image](https://user-images.githubusercontent.com/60806448/142727488-8a25dcce-aea3-4a4d-a1fb-07f479aa0e37.png)
Instead of this:
![pick](https://user-images.githubusercontent.com/60806448/142727499-d63c3178-9d67-47bb-a101-586292b6f683.png)
(it's located in shared/images though)
What am I doing wrong??

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

**Comment by 4wdthinks** [comment]
you dont even define the image to use, you can't just set its frames without setting the image? i could be wrong though

**Comment by NicklGames** [comment]
> you dont even define the image to use, you can't just set its frames without setting the image? i could be wrong though

isnt it in the first image?
tho how to fix that can you tell pls?

**Comment by ShadowMario** [comment]
`Paths.getSparrowAtlas('pick')`, you don't have to add "images" to it because it is already added automatically.
