### ISSUE TITLE
How to change colour of time bar mid song Lua?

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#11970]
### What is your question?

Up

**Comment by frantastic24** [comment]
Duplicate of #8678
Please use the search feature

**Comment by NightmaresPlayz** [comment]
Sorry

**Comment by NightmaresPlayz** [comment]
This is midsong, not start of song

**Comment by frantastic24** [comment]
setProperty works any time?

**Comment by TheKitBoi** [comment]
> This is midsong, not start of song

ffs
```
function onStepHit()
    if curStep == number then
        setProperty('timeBar.color', hex color)
    end
end
```

**Comment by NightmaresPlayz** [comment]
Are these in the stage file

**Comment by NightmaresPlayz** [comment]
And is cursteps like the numbers in json that shows when events are or the square events in chart editor

**Comment by NightmaresPlayz** [comment]
I got confused with the last stage change mid song
