### ISSUE TITLE
Inverted healthbar

### ISSUE THREAD

**Issue by Lupingllogi111** [ShadowMario/FNF-PsychEngine#11971]
### What feature do you want to get added on the **base** engine?

I think it would be a good idea to make it so that in chart editor there is a box to switch on or off the inverted healthbar (make it so that 0 health is at the left side instead of at the right side).
It wouldn't be very useful for vanilla FNF, but maybe for mods that do not use source but need to change the orientation of the health bar could be benefited.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by TheKitBoi** [comment]
lua exist
```
function onUpdatePost(elapsed)
	P1Mult = getProperty('healthBar.x') + ((getProperty('healthBar.width') * getProperty('healthBar.percent') * 0.01) + (150 * getProperty('iconP1.scale.x') - 150) / 2 - 26)
	P2Mult = getProperty('healthBar.x') + ((getProperty('healthBar.width') * getProperty('healthBar.percent') * 0.01) - (150 * getProperty('iconP2.scale.x')) / 2 - 26 * 2)
	setProperty('iconP1.x',P1Mult - 110)
	setProperty('iconP1.origin.x',240)
	setProperty('iconP1.flipX',true)
	setProperty('iconP2.x',P2Mult + 110)
	setProperty('iconP2.origin.x',-100)
	setProperty('iconP2.flipX',true)
	setProperty('healthBar.flipX',true)
end
```
