### ISSUE TITLE
Lua debugging QoL

### ISSUE THREAD

**Issue by junetried** [ShadowMario/FNF-PsychEngine#11988]
### What feature do you want to get added on the **base** engine?

Correct me if I'm wrong, but debugging Lua currently is tedious. The only way to get output from a script at all is either by writing to a file or writing to the screen. Moreover errors within the script itself are silent and stop functions from continuing.

My idea would be to give the ability to `print` to stdout (but NOT to the screen). This alone would help a lot, making it easier to export tons of lines to stdout without exploding the screen.

Preferably also write Lua errors to stdout. I recently [opened an issue](https://github.com/ShadowMario/FNF-PsychEngine/issues/11944) believing a function was having bugged behavior, only to learn that the function was not correct and the errors were completely silent.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
Boy i wish i knew how.

**Comment by UncertainProd** [comment]
A temporary solution would be to use Lua's own exception handling to test for errors (Using the function `pcall` as shown here: https://www.lua.org/pil/8.4.html ) So in the case of your code in [#11904](https://github.com/ShadowMario/FNF-PsychEngine/issues/11944) you could do something like this while testing:

```lua
function testMe()
	makeLuaSprite("object", "any-image-you-want", 1280/2, 720/2)

	-- Change the boolean in the following line, nothing will happen.
	-- Comment the following line, and the object will be rendered.
	addProperty("object.antialiasing", false)

	addLuaSprite("object", false)
end

function onCreate()
	local status, reason = pcall(testMe)
	if status then
		debugPrint("Success!")
	else
		debugPrint("Error!", reason)
	end
end
```

This does show the error:
![error handled](https://user-images.githubusercontent.com/83609901/227743721-bada28d4-e04d-462e-be82-0b6299d5a03c.png)

**Comment by junetried** [comment]
Why was this closed exactly?
