### ISSUE TITLE
Images on (32bit) crashs game

### ISSUE THREAD

**Issue by lazyremixmanordummyplayinggmod** [ShadowMario/FNF-PsychEngine#11986]
When loading into a song with lua related sprites for character it will crash or fail to load them entirely

(but keep this in mind i am running on wine but its still a 32bit problem)

footage https://streamable.com/lvonm1

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No it is unedited and prebuilt default

**Comment by junetried** [comment]
Are you running a 32-bit version of the engine? It has issues loading particularly large textures.

**Comment by lazyremixmanordummyplayinggmod** [comment]
yes

**Comment by lazyremixmanordummyplayinggmod** [comment]
i also did more testing and the sprite sheet broke also

**Comment by lazyremixmanordummyplayinggmod** [comment]
im switching to 64 bit
