### ISSUE TITLE
Null Object reference with thorns bgGhouls

### ISSUE THREAD

**Issue by PortilizenHub** [ShadowMario/FNF-PsychEngine#11989]
### Describe your bug here.

When loading into thorns it will give out a error from playState line 2829 with this code presumably (i highlighted the code)
![image](https://user-images.githubusercontent.com/99573698/221423282-fcc605e2-c819-4a1c-92fe-b88cca1c97b3.png)

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2829)
flixel/FlxState.hx (line 203)
flixel.FlxGame.hx (line 752)
flixel.FlxGame.hx (line 682)
flixel.FlxGame.hx (line 550)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a SkinPicker (its in the works but I was testing it and found this error)

**Comment by beksert** [comment]
interesting enough, i have the same problem in another moded psych engine

**Comment by beksert** [comment]
> interesting enough, i have the same problem in another moded psych engine

Also i enabling low quality works, but i see that the characters aren't in the right places

**Comment by verbes4** [comment]
same error for me when loading MILF
