### ISSUE TITLE
curBeat thing. (PLEASE HELP)

### ISSUE THREAD

**Issue by FluffB01** [ShadowMario/FNF-PsychEngine#11983]
### What is your question?

How do I check the current beat of a song?

I don't know if it is a thing in the debug menu or smth else.

**Comment by Shaggers-official** [comment]
In the Chart Editor, go to the place where you want to get the Current Beat from and look at the text on the right, there should be written "Beat : [the beat the song is at]"

**Comment by EyeDaleHim** [comment]
> In the Chart Editor, go to the place where you want to get the Current Beat from and look at the text on the right, there should be written "Beat : [the beat the song is at]"

This is an incorrect answer, he's asking for the current beat of a song, The answer is just `curBeat`.

**Comment by TheKitBoi** [comment]
if curBeat == number then -- change the number to how many there is
