### ISSUE TITLE
Must Hit Section Bug

### ISSUE THREAD

**Issue by Foxy7363** [ShadowMario/FNF-PsychEngine#11985]
### Describe your bug here.

when starting a song, the camera will sometimes start off by pointing to the dad even if the chart is in a must hit section at the beginning of the song

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

chart

**Comment by CaptainBaldi** [comment]
must hit sections are registered... each section... not before the song starts...

**Comment by junetried** [comment]
> must hit sections are registered... each section... not before the song starts...

This is not true, and it's easy to test.

**Comment by junetried** [comment]
Check the json and verify that there isn't another section at the start. I have found strange json files which start with a single step section.

**Comment by CaptainBaldi** [comment]
> must hit sections are registered... each section... not before the song starts...

correction : must hit sections are actually registered on create according to playstate lol
