### ISSUE TITLE
bug Compiling source code

### ISSUE THREAD

**Issue by TON-Games** [ShadowMario/FNF-PsychEngine#11998]
### Describe your bug here.

Plz tell me how 2 fix funkin_lua
![Screenshot (37)](https://user-images.githubusercontent.com/80106427/221854006-b0e89415-4e69-4080-a0f9-864d151c482b.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't do anything to funkin-lua file

**Comment by MemeHovy** [comment]
use nebulazorua’s fork of linc_luajit

**Comment by TheKitBoi** [comment]
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
