### ISSUE TITLE
Removing Misses

### ISSUE THREAD

**Issue by StelUsing** [ShadowMario/FNF-PsychEngine#11991]
### Describe your problem here.

I need to find a way to remove the misses text below the health bar using source code

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Ratio-Combinder** [comment]
remove line 2258
![image](https://user-images.githubusercontent.com/120575989/221517542-487a34c3-442c-4814-a598-dcd797675955.png)
