### ISSUE TITLE
How to Remove Opponent Light Strum

### ISSUE THREAD

**Issue by RandomUserOnInternet** [ShadowMario/FNF-PsychEngine#11997]
### Describe your problem here.

I want to remove opponent note hit then strum light up I want to make it like Base Game
thank you :) (Source Code only pls)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
look for `StrumPlayAnim(true, Std.int(Math.abs(note.noteData)), time);` and delete that

**Comment by RandomUserOnInternet** [comment]
> look for `StrumPlayAnim(true, Std.int(Math.abs(note.noteData)), time);` and delete that

Oh My God that actually work ,Thank You!

**Comment by MemeHovy** [comment]
you're welcome bud
