### ISSUE TITLE
How to get a lua sprite using runHaxeCode

### ISSUE THREAD

**Issue by hotpocketsarepoggers** [ShadowMario/FNF-PsychEngine#11994]
### Describe your problem here.

Im trying to make a looping angle tween using this code using runHaxeCode
     							if(object.angle == 0) 
								     FlxTween.angle(object, 0, 180, 15);
							if(object.angle == 180) 
								FlxTween.angle(object, 180, 360, 15);

but whenever I put replace 'object' with the lua sprite tag it does nothing

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by CaptainBaldi** [comment]
you can get a Lua object in HScript by using ```game.getLuaObject('luaObj')```

**Comment by hotpocketsarepoggers** [comment]
> you can get a Lua object in HScript by using `game.getLuaObject('luaObj')`

Thanks!
