### ISSUE TITLE
Help Me

### ISSUE THREAD

**Issue by CasualCypress** [ShadowMario/FNF-PsychEngine#11995]
### Describe your problem here.

I keep getting this error every time I compile

source/flxanimate/animate/FlxSymbol.hx:116: characters 75-80 : error: Int should be String
source/flxanimate/animate/FlxSymbol.hx:116: characters 75-80 :  have: Null<Int>
source/flxanimate/animate/FlxSymbol.hx:116: characters 75-80 :  want: haxe.extern.EitherType<String, ...>
source/flxanimate/animate/FlxSymbol.hx:116: characters 75-80 : For function argument 'name'
source/flxanimate/animate/FlxSymbol.hx:116: characters 61-82 : Void should be Array<flxanimate.animate.FlxLayer>
source/flxanimate/animate/FlxSymbol.hx:100: characters 34-39 : error: Int should be String
source/flxanimate/animate/FlxSymbol.hx:100: characters 34-39 :  have: Null<Int>
source/flxanimate/animate/FlxSymbol.hx:100: characters 34-39 :  want: haxe.extern.EitherType<String, ...>
source/flxanimate/animate/FlxSymbol.hx:100: characters 34-39 : For function argument 'name'
source/flxanimate/animate/FlxTimeline.hx:96: characters 25-29 : error: flxanimate.animate.FlxLayer should be Int
source/flxanimate/animate/FlxTimeline.hx:96: characters 25-29 :  have: haxe.extern.EitherType<..., flxanimate.animate.FlxLayer>
source/flxanimate/animate/FlxTimeline.hx:96: characters 25-29 :  want: haxe.extern.EitherType<..., Int>
source/flxanimate/animate/FlxTimeline.hx:96: characters 25-29 : For function argument 'name'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
this is not the right place to make the issue

**Comment by TheKitBoi** [comment]
> ### Describe your problem here.
> I keep getting this error every time I compile
> 

why did you attempt at porting flxanimate to this flxframecollection engine

**Comment by CasualCypress** [comment]
> why did you attempt at porting flxanimate to this flxframecollection engine

i didnt port flxAnimate

**Comment by TheKitBoi** [comment]
haxelib remove flxanimate

**Comment by Ratio-Combinder** [comment]
> i didnt port flxAnimate

check your source
