### ISSUE TITLE
more keys support (5k, 6k, etc etc)

### ISSUE THREAD

**Issue by Dunuty** [ShadowMario/FNF-PsychEngine#12]
( for reference - https://gamebanana.com/mods/311713 or https://github.com/TheZoroForce240/FNF-with-extra-keys )

would it be possible to port this into the chart editor? i know Shaggy and this other mod and stuff are made with kade engine, but maybe it is possible to redo the code on Psych Engine?

**Comment by ShadowMario** [comment]
Would probably be too annoying to code and make compatible with the changes already in.
