### ISSUE TITLE
Floating characters

### ISSUE THREAD

**Issue by Valorzz** [ShadowMario/FNF-PsychEngine#12001]
### Describe your problem here.

Whenever the camera moves to either bf or the enemy, it doesnt look like they are standing on the ground/stuck to the background or staying attached to it. it looks like theyre just floating
![tbhin3](https://user-images.githubusercontent.com/96262089/222083378-4f1f8674-d689-4d99-917e-26fe7e9c8d7c.PNG)
![thing](https://user-images.githubusercontent.com/96262089/222083380-99c3ac93-5fc4-4321-accb-14a2923321b2.PNG)
the 1st image is whenever its bf's turn, the 2nd image is whenever it is the enemy's turn 
(Btw cablecrows hand is supposed to stay on the pole, but he looks like he moves off of it during bf's turn)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheKitBoi** [comment]
did you adjust the positions

**Comment by Valorzz** [comment]
in the backgrounds lua?

**Comment by TheKitBoi** [comment]
ur char positiob

**Comment by Valorzz** [comment]
In the characters json? Or the backgrounds json?

**Comment by TheKitBoi** [comment]
char json

**Comment by Valorzz** [comment]
oh yeah i tried that and it didnt work

**Comment by TheKitBoi** [comment]
send it as a zip

**Comment by Valorzz** [comment]
[BF.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/10866069/BF.zip)

**Comment by Valorzz** [comment]
thats the bf im using, not the one in the image, theyre doing the same thing though

**Comment by Valorzz** [comment]
did u find the problem? @TheKitBoi

**Comment by TheKitBoi** [comment]
nope might have been your background position

**Comment by Valorzz** [comment]
ohh okay ill try to change that
