### ISSUE TITLE
Compiling HTML5 with mods and lua enabled

### ISSUE THREAD

**Issue by GMan2006i** [ShadowMario/FNF-PsychEngine#12000]
### Describe your problem here.

First off, does it work even?

If it does, I keep getting this error:
``source/TitleState.hx:19: characters 8-22 : You cannot access the sys package while targeting js (for sys.FileSystem)
source/Main.hx:32: characters 37-47 : ... referenced here``

and for the life of me I can't figure out how to fix it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5/Browser

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited the project.xml file to disable videos for web and enable mods and lua regardless.

**Comment by MemeHovy** [comment]
psych engine isn't really made for html5

**Comment by TheKitBoi** [comment]
> ### Describe your problem here.
> First off, does it work even?

wait till shadowmario or someone brings up fixes

**Comment by GMan2006i** [comment]
update:

so real quick status update.
Even in a fresh install of all the haxe shit and with an unmodified psych engine source build (besides the project file shit)

doesnt work either and gives the same errors.

i know for a fact that `sys.io.file` works just fine in openFL for html5, so im pretty sure that its just a janky build lmao

**Comment by MemeHovy** [comment]
you can't

> update:
> 
> so real quick status update. Even in a fresh install of all the haxe shit and with an unmodified psych engine source build (besides the project file shit)
> 
> doesnt work either and gives the same errors.
> 
> im pretty sure `sys.io.file` and anything regarding `sys` just doesnt work with web building
> 
> so I have a new question,
> 
> how in the fuck can you get the mods folder working in a web build of psych engine??

you can't

**Comment by GMan2006i** [comment]
> you can't
> 
> > update:
> > so real quick status update. Even in a fresh install of all the haxe shit and with an unmodified psych engine source build (besides the project file shit)
> > doesnt work either and gives the same errors.
> > im pretty sure `sys.io.file` and anything regarding `sys` just doesnt work with web building
> > so I have a new question,
> > how in the fuck can you get the mods folder working in a web build of psych engine??
> 
> you can't

pain.
there isnt ANY solution to even POSSIBLY get this to work, or even work around it?

**Comment by MemeHovy** [comment]
> > you can't
> > > update:
> > > so real quick status update. Even in a fresh install of all the haxe shit and with an unmodified psych engine source build (besides the project file shit)
> > > doesnt work either and gives the same errors.
> > > im pretty sure `sys.io.file` and anything regarding `sys` just doesnt work with web building
> > > so I have a new question,
> > > how in the fuck can you get the mods folder working in a web build of psych engine??
> > 
> > 
> > you can't
> 
> pain. there isnt ANY solution to even POSSIBLY get this to work, or even work around it?

not as far as I know

**Comment by MemeHovy** [comment]
so basically, no

**Comment by GMan2006i** [comment]
> so basically, no

the pain.

well what about lua at least?

**Comment by MemeHovy** [comment]
nope

**Comment by MemeHovy** [comment]
it's not compatible at all

**Comment by GMan2006i** [comment]
for psych specifically? or just haxe in general?

**Comment by MemeHovy** [comment]
both

**Comment by GMan2006i** [comment]
well shit.
im gonna close this for now then. this is definitely even more of a pain in the ass then i thought.

**Comment by GMan2006i** [comment]
Closed this because (as far as I can tell) it just isnt possible in haxe.
