### ISSUE TITLE
how do I play an alt idle animation on opponent during the countdown

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#12005]
### What is your question?

How do I trigger the alt idle animation event on the countdown or trigger the alt animation?

**Comment by CleanerCosine14** [comment]
![image](https://user-images.githubusercontent.com/103971101/222307297-48502f68-859a-4b6c-b228-b197ac4504d6.png)

**Comment by CleanerCosine14** [comment]
if your character has an alt animation on an xml file, then it will work, you gotta make an singUpalt an alt animation for an example

**Comment by BernardoGP4504** [comment]
> At around line 2261 inside switch(swagCounter) paste this 2 line wherever you want
> 
> ```hx
> dad.playAnim('idle-alt');
> dad.playAnim('singLEFT-alt'); //Or whatever it is tbh
> ```

But I'm on a compiled build

**Comment by Chidubemmo** [comment]
> > At around line 2261 inside switch(swagCounter) paste this 2 line wherever you want
> > ```hx
> > dad.playAnim('idle-alt');
> > dad.playAnim('singLEFT-alt'); //Or whatever it is tbh
> > ```
> 
> But I'm on a compiled build

Check the wiki there's likely something similar

**Comment by BernardoGP4504** [comment]
> > But I'm on a compiled build
> 
> hscript exists

I am trying it but it says it doesn't know what variable "dad" is

**Comment by BernardoGP4504** [comment]
Guys, the best attempt I got was this:
```lua
function onSongStart()
    luaDebugMode = true;
    playAnim(getPropertyFromClass('PlayState', 'dad'), "idle-alt", true);
end
```
But it still plays after the countdown

**Comment by frantastic24** [comment]
[Wiki has a callback list](https://raw.githubusercontent.com/ShadowMario/FNF-PsychEngine/main/docs/TemplateScript.lua)
You also don't need `getPropertyFromClass`, the function already gets the object

**Comment by BernardoGP4504** [comment]
I don't need it anymore lol
