### ISSUE TITLE
yvals.h crtcbg.h problem with building

### ISSUE THREAD

**Issue by Fadeyauso** [ShadowMario/FNF-PsychEngine#12008]
### Describe your problem here.

all needed libraries is installed
i have vs 2022
https://cdn.discordapp.com/attachments/1056940189437677639/1080885688867758100/image.png

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MemeHovy** [comment]
you need to use vs 2019

**Comment by Fadeyauso** [comment]
> 

already tried it, same problem
