### ISSUE TITLE
Expected expression

### ISSUE THREAD

**Issue by Stefan2008Git** [ShadowMario/FNF-PsychEngine#12009]
### Describe your problem here.

`source/PlayState.hx:4499:` characters 4-5 : Expected expression` I just tried to add fixed shader's on game, but i got this error message
![Snimak ekrana 2023-03-02 182157](https://user-images.githubusercontent.com/126715034/222508696-79b7fe69-6d3b-4270-8e60-3f5eaba9da85.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Just added lua shader's, removed achievent's on PlaysState.hx and that's it

**Comment by Stefan2008Git** [comment]
Sorry for bad grammar

**Comment by MemeHovy** [comment]
missing {

**Comment by Stefan2008Git** [comment]
> > missing {
> 
> Line?

I alreeady added, but a same issue

**Comment by MemeHovy** [comment]
> > missing {
> 
> Line?

isn't it obvious
