### ISSUE TITLE
Add Fengari Lua for web version of psych engine

### ISSUE THREAD

**Issue by GMan2006i** [ShadowMario/FNF-PsychEngine#12003]
### What feature do you want to get added on the **base** engine?

do it please i beg you
you cant use lua in the web version of psych engine (to my knowledge) and i am fucking FIENDING for that that good lua web support.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MemeHovy** [comment]
from https://github.com/AndreiRudenko/linc_luajit
`This library works with the Haxe cpp target only.`

**Comment by MemeHovy** [comment]
which means it does **NOT** work on web

**Comment by GMan2006i** [comment]
im not saying to use linc_luajit only or exclusively.

their ARE libraries for using lua on js exported haxe programs


> from https://github.com/AndreiRudenko/linc_luajit `This library works with the Haxe cpp target only.`

**Comment by MemeHovy** [comment]
yeah but it's only JS, it can't be used with haxe

**Comment by MemeHovy** [comment]
just only haxe apps exported to JS

**Comment by GMan2006i** [comment]
the whole point is to export it into js/web version of psych. id imagine itd be either a fork or a separate branch or something. I'd do it myself but I don't know much haxe or js

**Comment by MemeHovy** [comment]
that would be very difficult as hell, and I'm pretty sure it doesn't work like that

**Comment by GMan2006i** [comment]
> that would be very difficult as hell, and I'm pretty sure it doesn't work like that

it would pretty sick if it existed though

**Comment by MemeHovy** [comment]
but it don't
