### ISSUE TITLE
I'm trying to compile then this shows up.

### ISSUE THREAD

**Issue by NewlyRBX** [ShadowMario/FNF-PsychEngine#12015]
### Describe your problem here.

source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1573: characters 13-23 : Type not found : MP4Handler

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by AtlasGamer27** [comment]
change your hxCodec version to 2.5.1 using

`haxelib remove hxCodec`
`haxelib install hxCodec 2.5.1`

**Comment by NewlyRBX** [comment]
Now it says this source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Program Files (x64)\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by AtlasGamer27** [comment]
Did you install Visual Studio? I believe you do have to install Visual Studio to compile it
