### ISSUE TITLE
Trying Compile But This Keep Appearing

### ISSUE THREAD

**Issue by BuildyArka** [ShadowMario/FNF-PsychEngine#12017]
### Describe your problem here.

I Don't Know How To Fix This¯\_(-_-)_/¯
source/Main.hx:87: characters 61-65 : Float should be Int
source/Main.hx:87: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:87: characters 61-65 : ... For function argument 'child'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I Edited Playstate.hx to add a stage and winning icon

**Comment by MemeHovy** [comment]
use flixel 4.11.0 and flixel addons 2.11.0 or edit main.hx and change zoom to this `#if (flixel < "5.0.0") zoom, #end`
