### ISSUE TITLE
Transparence sprite based on health

### ISSUE THREAD

**Issue by NavaGaming** [ShadowMario/FNF-PsychEngine#12013]
### Describe your problem here.

How do i code the funny that makes sprite more visible when bf have less hp?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
```lua
function onUpdate(elapsed)
    local healthPercent = (getHealth() / 2) --When your health is at "2" it means 100% health, 0 means no health.
    setProperty('spriteName.alpha', 1 - healthPercent)
end
```
