### ISSUE TITLE
how to make characters float,

### ISSUE THREAD

**Issue by cheemynugget2** [ShadowMario/FNF-PsychEngine#1201]
### Describe your problem here.

In some mods characters float up and down like flying

sarv,dave,ect

https://www.youtube.com/watch?v=effw_5KV4-Q&t=553s

look the mans flyin!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

so far ive added characters and changed stage lua codes and a bit more but not much

**Comment by HiroOfc** [comment]
i think you can do this by editting the characters offset at the stage json. Idk how to program at lua, but i think there is a json for the stage

**Comment by mayo78** [comment]
use tweenY

**Comment by PDL2CGamejolt** [comment]
IDK

**Comment by Ordinary3** [comment]
function onUpdate(elapsed)
    songPos = getSongPosition()
    local currentBeat = (songPos/5000)*(curBpm/60)
    doTweenY('dadFloatY', 'dad', defaultOpponentY+(math.sin(songPos*0.003)*300)+100, 0.1, 'sineIn')
end

**Comment by PDL2CGamejolt** [comment]
> function onUpdate(elapsed) songPos = getSongPosition() local currentBeat = (songPos/5000)_(curBpm/60) doTweenY('dadFloatY', 'dad', defaultOpponentY+(math.sin(songPos_0.003)*300)+100, 0.1, 'sineIn') end

but the thing didnt work and broke the .lua file

**Comment by PDL2CGamejolt** [comment]
> function onUpdate(elapsed) songPos = getSongPosition() local currentBeat = (songPos/5000)_(curBpm/60) doTweenY('dadFloatY', 'dad', defaultOpponentY+(math.sin(songPos_0.003)*300)+100, 0.1, 'sineIn') end

can you send me a script file

**Comment by Ordinary3** [comment]
> but the thing didnt work and broke the .lua file

oh yeah mb i fogor to put a *, so this should work

function onUpdate(elapsed)
	songPos = getSongPosition()
	local currentBeat = (songPos/5000)(curBpm/60)
	doTweenY('dadFloatY', 'dad', defaultOpponentY+(math.sin(songPos0*003)*300)+100, 0.1, 'sineIn')
end

**Comment by cheemynugget2** [comment]
> 

uh the 1st didnt work and the seconds one just made him fly into the sky and not come down he just sorta left

**Comment by cheemynugget2** [comment]
> > but the thing didnt work and broke the .lua file
> 
> oh yeah mb i fogor to put a *, so this should work
> 
> function onUpdate(elapsed) songPos = getSongPosition() local currentBeat = (songPos/5000)(curBpm/60) doTweenY('dadFloatY', 'dad', defaultOpponentY+(math.sin(songPos0*003)*300)+100, 0.1, 'sineIn') end
> 
> if that still doesnt work you could try this function onUpdate() if curStep % 4 == 0 then doTweenY('dadUP2', 'dad', 400, 0.55, 'sineIn') end if curStep % 4 == 2 then doTweenY('dadDown2', 'dad', -400, 0.55, 'sineIn') end end

so the second worked but it just made him fly up and never come back down he flew off the screen

**Comment by Ura785** [comment]
function onUpdate()
    songPos = getSongPosition()
    local currentBeat = (songPos/5000)(curBpm/60)
    setCharacterY('dad', getCharacterY('dad') + (math.sin(currentBeat) * 2))
end

**Comment by Ura785** [comment]
set the * 2 to * 1 if you don't want people to see the void

**Comment by TrashEy4** [comment]
where do i put the script lol

**Comment by PDL2CGamejolt** [comment]
> function onUpdate() songPos = getSongPosition() local currentBeat = (songPos/5000)*(curBpm/60) setCharacterY('dad', getCharacterY('dad') + (math.sin(currentBeat) * 2)) end
> 
> -- Tested and it works perfectly

It didnt work

**Comment by TimRedGamerYT** [comment]
uhh how do i make bOTH characters fly at the same time? like i want the right one to be like shaggy n the other to be like sarv.

bc im tryna make a sarv vs ghost twins cover with gameplay and im dumb n have been searching for a script.

Here's what i have.

function onUpdate()
songPos = getSongPosition()
local currentBeat = (songPos/5000)*(curBpm/60)
setCharacterY('dad', getCharacterY('dad') + (math.sin(currentBeat) * 1))
end

function onUpdate(elapsed)

  if curStep >= 0 then

    songPos = getSongPosition()

    local currentBeat = (songPos/1000)*(bpm/80)

    doTweenY(dadTweenY, 'bf', 300-110*math.sin((currentBeat*0.25)*math.pi),0.001)

  end

end

it just makes both chrs not float but stay still. WHAT DO I DOOOO 😭

**Comment by YadernyjPocoPingvin** [comment]
to make the camera follow ur dad flying youll have to this code

```
if mustHitSection == true then
cameraSetTarget("boyfriend")
elseif mustHitSection == false then
cameraSetTarget("dad")
end
```

put this code in onUpdatePost
