### ISSUE TITLE
vlc.MP4Handler doesn't worked to compiling. hxcodec.VideoHandler does worked to compiling

### ISSUE THREAD

**Issue by realMohammadDev** [ShadowMario/FNF-PsychEngine#12019]
### Describe your bug here.

i cant compiling when it's vlc.MP4Handler, and i try to compiling with using MP4Handler, and it doesn't work. and please use it VideoHandler from hxcodec because it works at all, i try compiling with using VideoHandler, and it works for me. please fix it thanks
![Screenshot_20230304_123105](https://user-images.githubusercontent.com/103966427/222897502-c4633621-0c6e-4b4b-9d56-dd559c0aa74f.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by TheKitBoi** [comment]
haxelib remove hxCodec
haxelib install hxCodec 2.5.1

**Comment by realMohammadDev** [comment]
> 

but that videohandler works like a same

**Comment by realMohammadDev** [comment]
> haxelib remove hxCodec haxelib install hxCodec 2.5.1

i try it but it doesn't works normally

**Comment by TheKitBoi** [comment]
did you even revert it

**Comment by realMohammadDev** [comment]
> did you even revert it

no, MP4Handler it doesn't work. but Only VideoHandler it works because this is worked to using
