### ISSUE TITLE
Type not found : WiggleShader

### ISSUE THREAD

**Issue by YoshiGames64** [ShadowMario/FNF-PsychEngine#12027]
### Describe your problem here.

I wanted to put in the wavy effect to the Alphabet.hx

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
you didn’t import the shader

**Comment by YoshiGames64** [comment]
Thanks. But I have these errors now:

source/Alphabet.hx:8: characters 8-20 : Type name WiggleShader is redefined from module WiggleShader
source/Alphabet.hx:24: characters 13-19 : Redefinition of variable shader in subclass is not allowed. Previously declared at flixel.FlxSprite

**Comment by MemeHovy** [comment]
because your using the same name the class your extending has

**Comment by YoshiGames64** [comment]
so do i just delete the var

**Comment by MemeHovy** [comment]
or rename it

**Comment by YoshiGames64** [comment]
ok

**Comment by YoshiGames64** [comment]
Method set_wavyEffect required by property wavyEffect is missing

**Comment by MemeHovy** [comment]
I meant rename the var in alphabet

**Comment by MemeHovy** [comment]
🤦🏻‍♂️

**Comment by YoshiGames64** [comment]
what if is "isAlphabet" do i change it to

**Comment by MemeHovy** [comment]
no

**Comment by MemeHovy** [comment]
otherwise no

**Comment by YoshiGames64** [comment]
yooooooooooooooooooooooo its working

**Comment by MemeHovy** [comment]
there you go
