### ISSUE TITLE
Songs with period "." in name can't be loaded.

### ISSUE THREAD

**Issue by ScarabWasTaken** [ShadowMario/FNF-PsychEngine#12023]
### Describe your bug here.

Song names with full stops / periods / dots can't be found.

Try renaming /Fresh/ song folder to /Fre.sh/ and changing <"song":  "Fresh"> in the chart to:
"song": "Fre.sh" won't work
"song": "Fre.sh/" won't work
"song":  "Fre^.sh" won't work
"song": "Fre\.sh" will crash due to unrecognised character

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Draconic-Hybrid** [comment]
Anything after a period Windows will read as a file type. So in the case of Fre.sh, it'll read the name as "Fre" and the file type as "sh"

**Comment by AyMarte** [comment]
example: fresh.json and fre.sh are two different files.

**Comment by KookerFoxYT** [comment]
its probably not a psych engine issue, rather a windows one

**Comment by ShatteredEcHOs** [comment]
I would recommend just not using a period in the name of a song?
