### ISSUE TITLE
How to make you play as opponent at a specific difficulty using lua script?

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#12025]
### What is your question?

Up

**Comment by NightmaresPlayz** [comment]
If you don’t understand, then like you swap the positions of the character and the arrows positions and also invert the healthbar

**Comment by Lorekeeper49** [comment]
I did almost all of this with some simple methods in my mod [Stardust Charts](https://gamebanana.com/mods/373000) I'm only really missing the properly flipped health bar 
If you wish to use any of the code in the `scripts/Opponent difficulty`, `custom_notetypes/other`, or `custom_notetypes/other-alt` files, all you need to do is credit me
