### ISSUE TITLE
How do you make an image pop up every time you miss a note

### ISSUE THREAD

**Issue by PotatoKing0419** [ShadowMario/FNF-PsychEngine#12026]
### Describe your problem here.

read the title

:devious:

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by NightmaresPlayz** [comment]
I’m pretty sure there is like a lua file like that, just use the static notes lua file and edit the notes image so it is the one you want to use and see if you can get the image to change instead of static. I haven’t done this before so if it doesn’t work, I’m not sure how it is
