### ISSUE TITLE
Changing combo sprites via a lua script

### ISSUE THREAD

**Issue by spark-the-dragon** [ShadowMario/FNF-PsychEngine#12021]
### Describe your problem here.

Hello, I was just wondering if I can change the combo sprites in Lua, for just 1 song in a mod I'm working on and be able to change them back to a different sprite when i want too. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
You can edit ratings (#9413) but not combo counter, you'll have to recreate it

**Comment by spark-the-dragon** [comment]
> You can edit ratings (#9413) but not combo counter, you'll have to recreate it
