### ISSUE TITLE
Song won't start

### ISSUE THREAD

**Issue by GlamesDem0tivated** [ShadowMario/FNF-PsychEngine#12038]
### Describe your bug here.

So, I tried to port in Triple Run to Psych Engine (I.E. grabbing the song data folder and throwing it in a different mod's data folder), and when I tried to run it, it just crashed.

![Screenshot 2023-03-07 222232](https://user-images.githubusercontent.com/109561022/223612734-7bb99a8b-cdcc-4ba0-af54-7188bb0a38a1.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I'm not using the Source Code.

**Comment by frantastic24** [comment]
Not a bug
Missing chart

**Comment by GlamesDem0tivated** [comment]
Oh
Could you tell me how I actually find the chart? Since I've tried removing some pieces, and nothing works.

**Comment by frantastic24** [comment]
The chart goes in `data/freaks-run` and should be named `freaks-run-hard`

**Comment by Ratio-Combinder** [comment]
read up ^
@GlamesDem0tivated

**Comment by NightmaresPlayz** [comment]
Find the chart for the song in original files or if there isn’t any chart for it, the only choice you would have is to chart it yourself

**Comment by GlamesDem0tivated** [comment]
> The chart goes in `data/freaks-run` and should be named `freaks-run-hard`

I can assure you that there's a file in there. the folder name, the file name, and even the song name inside the file itself is named "freaks-run"

**Comment by GlamesDem0tivated** [comment]
> Find the chart for the song in original files or if there isn’t any chart for it, the only choice you would have is to chart it yourself

Fuck

**Comment by frantastic24** [comment]
> I can assure you that there's a file in there. the folder name, the file name, and even the song name inside the file itself is named "freaks-run"

You missed the `-hard` suffix

**Comment by GlamesDem0tivated** [comment]
> > I can assure you that there's a file in there. the folder name, the file name, and even the song name inside the file itself is named "freaks-run"
> 
> You missed the `-hard` suffix

![Screenshot 2023-03-09 211644](https://user-images.githubusercontent.com/109561022/224206235-e60c3834-b14c-4f64-99ab-c3c855d0b949.png)

It's here

also if you're wondering about the script it's a simple camera shake script being

```
function opponentNoteHit(id, direction, noteType, isSustainNote)  

    cameraShake('game', 0.01, 0.05)

end
```
