### ISSUE TITLE
I don't know what to do when I compile it.

### ISSUE THREAD

**Issue by someonewhoexsits** [ShadowMario/FNF-PsychEngine#12035]
### Describe your problem here.

So I try to compile psych engine and it gives me,
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'update framerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler

I don't know what to do.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited the title so when I compile it it says what I want, also the thing at the bottom left corner that says Psych Engine v6.3.

**Comment by KookerFoxYT** [comment]
use the latest hxcodec
and change the main.hx to the latest one from the repo

**Comment by MemeHovy** [comment]
use latest hxCodec and update main and replace zoom with this `#if (flixel < "5.0.0") zoom, #end`

**Comment by TheKitBoi** [comment]
> ### Describe your problem here.
> So I try to compile psych engine and it gives me, source/Main.hx:85: characters 61-65 : Float should be Int source/Main.hx:85:

use
```
haxelib remove hxCodec
haxelib install hxCodec 2.5.1
```
and replace Main.hx with a new one https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

**Comment by someonewhoexsits** [comment]
thank you

**Comment by someonewhoexsits** [comment]
hold up how do i take it down?

**Comment by someonewhoexsits** [comment]
oh nvm
