### ISSUE TITLE
Keep getting this non-sense errors

### ISSUE THREAD

**Issue by AstroGamesIndie** [ShadowMario/FNF-PsychEngine#12031]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/108987120/223163007-d1f96d25-af8b-46a8-ac41-ebdd185e95f6.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Only mainmenustate.hx

**Comment by TheKitBoi** [comment]
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

**Comment by AstroGamesIndie** [comment]
tysm that did it

**Comment by TheKitBoi** [comment]
close this issue
