### ISSUE TITLE
Story Mode Crashes Engine

### ISSUE THREAD

**Issue by Octodecillion** [ShadowMario/FNF-PsychEngine#12033]
### Describe your bug here.

Whenever Story Mode is accessed, an error will occur and crash the engine.

### Command Prompt/Terminal logs (if existing)

```bash
StoryMenuState.hx (line 275)
flixel/group/FlxGroup.hx (line 740)
StoryMenuState.hx (line 273)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a mod into the mods folder.

**Comment by NotStampyC** [comment]
You set the mod week to hide from story mode and if you removed all of the normal built in week JSON's then it will crash as nothing has appeared

**Comment by Baconroaster** [comment]
Here look at this i got the same issue But i cant fix it bc i dont understand Json I only know how to code Lua 
states/PlayState.hx (line 1520)
states/PlayState.hx (line 954)
backend/BaseStage.hx (line 120)
states/stages/School.hx (line 117)
states/stages/School.hx (line 87)
backend/BaseStage.hx (line 60)
states/stages/School.hx (line 9)
states/PlayState.hx (line 389)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
