### ISSUE TITLE
How do I make text that says the song name?

### ISSUE THREAD

**Issue by PotatoKing0419** [ShadowMario/FNF-PsychEngine#12034]
### Describe your problem here.

so i know how to make text, but how do i make it say the name of the current song?
(this is a script that will apply to all songs, so I can't just put the name of one song as the text)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
"..songName.."

**Comment by DisIsNOt** [comment]
setProperty("dutch.text", songName)

**Comment by PotatoKing0419** [comment]
> "..songName.."

I already tried that
if I set it as just "songName" then it'll just say "songName"

**Comment by TheKitBoi** [comment]
did it look like this.
`functionnameidk(""..songName.."", false);`

**Comment by PotatoKing0419** [comment]
nvm i figured it out

makeLuaText('songtitle', 'thingandstuff', 0, 1500, 0)
setTextString('songtitle', ""..songName.."")
