### ISSUE TITLE
How to move the character like Natsuki does in DDTO Bad Ending Home using lua?

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#12043]
### What is your question?

Up

**Comment by frantastic24** [comment]
[Check the wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers#dotweenxtagstring-varsstring-valuedynamic-durationfloat-easestring)
