### ISSUE TITLE
Lua script song load

### ISSUE THREAD

**Issue by Ninjakaiden523** [ShadowMario/FNF-PsychEngine#12042]
### What is your question?

Is it possible to make a song load by pressing something (Say seven) with Lua? I'm not sure if it is possible.

**Comment by Ratio-Combinder** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/10439

**Comment by Ninjakaiden523** [comment]
Sometimes you're close to the answer, but just far off enough that you call for help

**Comment by YadernyjPocoPingvin** [comment]
function onUpdate()
	if keyJustPressed('keyType') then -- type the key you want
		loadSong('test') -- change the test to the other song name
	end
end

**Comment by YadernyjPocoPingvin** [comment]
else if you want with the seven key, then

function onUpdate(elapsed)
	if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
		loadSong('test')
	end
end
