### ISSUE TITLE
Sprite problem

### ISSUE THREAD

**Issue by IvaskiyGooD** [ShadowMario/FNF-PsychEngine#12040]
### Describe your problem here.

I made a custom note type, but when using them in a track, the sprite is only shown on the first one, and the next ones are displayed as normal notes. Code below.

```
function onCreate()
	for i = 0, getProperty('unspawnNotes.length')-1 do
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'BulletNote' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'BulletNote');
			setPropertyFromGroup('unspawnNotes', i, 'strumNoteHit', false);

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true); --Miss has no penalties
			end
		end
	end
end
function goodNoteHit(id, noteData, noteType, isSustainNote)
    if noteType == 'BulletNote' then
    triggerEvent('Play Animation','dodge', 'bf')
    triggerEvent('Play Animation','Shot', 'dad')
        end
    end
function noteMiss(id, direction, noteType, isSustainNote)
    if noteType == 'BulletNote' then
    setProperty('health', getProperty('health')-0.2);
    triggerEvent('Play Animation','hurt', 'bf')
    triggerEvent('Play Animation','Shot', 'dad')
    end
        end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
`strumNoteHit` isn't a variable, that line may be preventing the rest of the code from running

**Comment by IvaskiyGooD** [comment]
> `strumNoteHit` isn't a variable, that line may be preventing the rest of the code from running

Then what should I write there?

**Comment by IvaskiyGooD** [comment]
> 



> Delete it, I don't know what that line was supposed to do

The noteMiss function does not work without this line.

**Comment by CaptainBaldi** [comment]
remove the `strumNoteHit` line and also remove 
```
if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
	setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true); --Miss has no penalties
end
``` 
from your code
this code stops misses from being calculated on the note

**Comment by IvaskiyGooD** [comment]
Thats works! Thanks so much!

**Comment by frantastic24** [comment]
> The noteMiss function does not work without this line.

As I said the variable doesn't exist so the line does nothing other than break the script

You can close this now
