### ISSUE TITLE
How to make BF visible only during must hit sections?

### ISSUE THREAD

**Issue by luigiman0** [ShadowMario/FNF-PsychEngine#12048]
### What is your question?

I'm trying to make a song where Boyfriend becomes invisible when it is not a must hit section, similar to Rumor from Friday Night Crunchin'. How could i do this?

**Comment by frantastic24** [comment]
`function onSectionHit()` and `mustHitSection`

**Comment by luigiman0** [comment]
> `function onSectionHit()` and `mustHitSection`

alright so i understand how to check for the must hit section but how do i make boyfriend fade away?

**Comment by frantastic24** [comment]
Set `alpha` to 0 or something incredibly low or `visible` to false
