### ISSUE TITLE
How to make the text under the health bar invisible?

### ISSUE THREAD

**Issue by fox-64** [ShadowMario/FNF-PsychEngine#12045]
### Describe your problem here.

I am trying to make the score text invisible but it does not work
I used `setProperty('scoreTxt.visible',false)`and `setvar('scoreTxt.visible',false)`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didnt

**Comment by frantastic24** [comment]
1. Are you running the code under `onCreate`, if so change it to `onCreatePost`
2. `setvar` isn't a function

**Comment by fox-64** [comment]
> 1. Are you running the code under `onCreate`, if so change it to `onCreatePost`
> 
>     2. `setvar` isn't a function

i am running on `onCreate`

**Comment by frantastic24** [comment]
So change it

**Comment by fox-64** [comment]
> So change it 

Ok, thanks for the help
