### ISSUE TITLE
Song Won't start #2: Electric Bogaloo

### ISSUE THREAD

**Issue by GlamesDem0tivated** [ShadowMario/FNF-PsychEngine#12049]
### Describe your bug here.

I press song on freeplay menu.
Song crashes, gives me this error
![Screenshot 2023-03-09 204712](https://user-images.githubusercontent.com/109561022/224202564-895d0546-d30f-41b8-9df8-83b92c4673c6.png)
and the song worked yesterday.
it ran perfectly fine yesterday.
Yeah I'm fine.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I'm not using the Source Code.

**Comment by CaptainBaldi** [comment]
json is broken
