### ISSUE TITLE
Changing Game Icon Using LUA Scripts

### ISSUE THREAD

**Issue by AyMarte** [ShadowMario/FNF-PsychEngine#12047]
### What is your question?

Like is there a possible way on how I can change the game icon that is on the top left corner of the fnf tab using just lua scripts?

**Comment by luigiman0** [comment]
The game icon on the top left changes depending on the current icon.ico file in use. For the icon to actually change, you would have to edit the icon.ico file and re-extract the game. Make sure your custom icon works in all the available resolutions. Once this is done, you should have your custom icon as the game icon and as the one that appears in the top left corner of the tab.

To my knowledge this isn't something that can be done with a lua script, but the method above worked for me (image below).
![epicbar](https://user-images.githubusercontent.com/113739072/224186538-ab286654-2304-42e6-ab57-573ffc11617d.png)

**Comment by TheKitBoi** [comment]
> To my knowledge this isn't something that can be done with a lua script, but the method above worked for me (image below).
rly
```
function onCreate()
    local IconPath = 'icon32' --Path of the image
    addHaxeLibrary('Application', 'lime.app')
    addHaxeLibrary('Image', 'lime.graphics')
    runHaxeCode([[
        var Icon:Image = Image.fromFile(Paths.modFolders('images/]]..IconPath..[[.png'))
        Application.current.window.setIcon(Icon);
    ]])
end
```
credit Drawoon_#2140
