### ISSUE TITLE
Change Scroll Speed event not working.

### ISSUE THREAD

**Issue by 40U538072** [ShadowMario/FNF-PsychEngine#12054]
### Describe your bug here.

No matter what values I set, the scroll speed will not even change mid-song. I have tried anabling and disabling certain setting or modifiers and nothing even did anything. I am reporting this as a bug just in case Psych is doing that thing again.

I just want to know if it can be fixed in some later update, or if there is something I am missing.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment]
Check your scroll speed type, if it's set to Constant then the event is coded to do nothing

**Comment by 40U538072** [comment]
I have is set to multiplicative.

**Comment by 40U538072** [comment]
Found the problem. I was pressing esc when I should press enter. Oversight in my case.
