### ISSUE TITLE
Maybe a solution to compile psych engine 0.6.3

### ISSUE THREAD

**Issue by Matheus-Hideki** [ShadowMario/FNF-PsychEngine#12055]
### What is your question?

not quite a question, but maybe a solution, i'll point what i did to compile the game, so maybe you fix the problem too!

First, i installed all of the necessary libs

these are the haxeflixel core libraries:
haxelib install lime
haxelib install openfl
haxelib install flixel

finishing the instalation to the core:
haxelib run lime setup flixel

Install the lime command:
haxelib run lime setup

complementary tools, just in case:
haxelib install flixel-tools
haxelib run flixel-tools setup

update haxeflixel
haxelib update flixel

these are needed to the compiling:
flixel
flixel-addons
flixel-ui
hscript
newgrounds

these too:
haxelib git polymod https://github.com/larsiusprime/polymod.git
haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc

install other flixel addons wich is required
haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons

then i installed these specific things from visual studio community 2019 16.11.23:
MSVC v142 - VS 2019 C++ x64/x86 build tools
Windows SDK (10.0.17763.0)

it takes 3,36 GB but is extremely required

now here comes the thing
i firstly tried to compile psych engine 0.5.2h
i solved the problem running these commands;

haxelib remove flixel
haxelib install flixel 4.11.0

these solved the problems i had, but then i tried compiling 0.6 version
the following pop up:

source/PlayState.hx:67: characters 8-22 : Type not found : vlc.MP4Handler
source/FunkinLua.hx:211: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:2704: characters 7-38 : Bool should be Int
source/FunkinLua.hx:229: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:235: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:287: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:293: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:333: lines 333-337 : Int should be Bool
source/FunkinLua.hx:333: lines 333-337 : ... For function argument 'f'
source/FunkinLua.hx:439: lines 439-442 : Int should be Bool
source/FunkinLua.hx:439: lines 439-442 : ... For function argument 'f'
source/PlayState.hx:1495: characters 13-23 : Type not found : MP4Handler

so, to solve these i ran the following code at the terminal:

haxelib remove hxCodec
haxelib install hxCodec 2.5.1
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

(i'm not sure if the following commands helps on anything but just in case)
haxelib remove lime
haxelib install lime 8.0.0

and so, it solved the problem at the psych engine 0.6, but surprisingly also solved at version 0.6.3, hope i helped!

**Comment by Matheus-Hideki** [comment]
note: It's not sure if it will work, i'm just relating what worked for me!

**Comment by TheKitBoi** [comment]
no hmm exists
