### ISSUE TITLE
Like Stagnant Doki

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#12050]
### What feature do you want to get added on the **base** engine?

Add extra stages like in the json, there is a pixel stage section, I thought is there a way I can add a happy stage section

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
You can already do this

**Comment by NightmaresPlayz** [comment]
Wait, how?!

**Comment by NightmaresPlayz** [comment]
With lua

**Comment by frantastic24** [comment]
Make both stages in one script, keep one invisible until the switch is supposed to happen
It works exactly like it does on source

**Comment by NightmaresPlayz** [comment]
Can it go from normal to pixel by this script:
function onCreate()
      function onStepHit()
         if curStep == number of steps
              “isPixelStage”: true
         end
     end
end

**Comment by NightmaresPlayz** [comment]
Is there a script for that if it is wrong

**Comment by NightmaresPlayz** [comment]
Pls, tell me if there is a script, I might need it soon

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Value-Setting-and-Getting-Functions#general-setters

**Comment by NightmaresPlayz** [comment]
I still don’t get it

**Comment by NightmaresPlayz** [comment]
Can you give me an example for changing ui

**Comment by NightmaresPlayz** [comment]
Example, pls

**Comment by NightmaresPlayz** [comment]
Is it like setProperty(‘isPixelStage’, true)

**Comment by ShadowMario** [comment]
you can change isPixelStage on the json file of the stage

**Comment by NightmaresPlayz** [comment]
In middle of song
