### ISSUE TITLE
Operate the main menu with the mouse

### ISSUE THREAD

**Issue by tnpr3432** [ShadowMario/FNF-PsychEngine#12059]
### What is your question?

I'm making a mod, is there any source code to control the main menu with the mouse? I've tried a few but they all give errors or don't work.

**Comment by someonewhoexsits** [comment]
Ok so i don't code good so don't get your hopes up when reading this, that is a good idea. i might use the comment that pops up saying the smart stuff

**Comment by tnpr3432** [comment]
ok

**Comment by tnpr3432** [comment]
I made a mistake and pressed the close with comment button, I'm sorry

**Comment by someonewhoexsits** [comment]
it's fine

**Comment by tnpr3432** [comment]
Thanks

**Comment by tnpr3432** [comment]
I will ask you again about other operation methods, so please let me know if you understand.
