### ISSUE TITLE
Run an app from the Game engine

### ISSUE THREAD

**Issue by Hazardows** [ShadowMario/FNF-PsychEngine#12064]
### Describe your problem here.

I am creating a mod for fnf and I need help. I want to make the game run an exe that is in the mods folder and then close the Game. How could i do it? (I'm modding from the source code)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by PotatoKing0419** [comment]
for lua i found
`os.execute("program.exe")`
I don't know how to do that in source code tho sorry :(

**Comment by Hazardows** [comment]
No problem, that Will work with a la script

**Comment by Hazardows** [comment]
perfect but I need the game to close when executing the exe

**Comment by PotatoKing0419** [comment]
os.execute("program.exe")
os.exit("otherprogram.exe")

**Comment by Hazardows** [comment]
Thanks PotatoKing0419!

**Comment by PotatoKing0419** [comment]
no problem :D

**Comment by Hazardows** [comment]
But it crashes the Game instead of closing it

**Comment by TheKitBoi** [comment]
show the script

**Comment by Hazardows** [comment]
local sus = false

function opponentNoteHit(){
    If not sus then
        os.execute("fei.bat")
        os.exit()
        sus = true
    end
end

**Comment by PotatoKing0419** [comment]
I think since there's nothing in the parentheses it closes both of them
Try putting the name for the application to be closed in the parentheses

**Comment by Ratio-Combinder** [comment]
@Hazardows 
```
local sus = false

function opponentNoteHit(){
    If not sus then
        os.execute("fei.bat")
        os.exit("PsychEngine.exe")
        sus = true
    end
end
```
