### ISSUE TITLE
HOW MAKE LUA BACKDROP??

### ISSUE THREAD

**Issue by MarkitoEngineerFNF** [ShadowMario/FNF-PsychEngine#12062]
### Describe your problem here.

I want to make the sky of Your Demise and Epiphany stages but when the sky dissapear don't repeat the velocity.x property, and I tried to use de Backdrop Lua but dosen't work. I don't know if I need make it in the play state scource or I can make it in the Stage Lua

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by KookerFoxYT** [comment]
use the script below
```
addHaxeLibrary('FlxBackdrop', 'flixel.addons.display');

posX = -1000;
posY = -700;
scale = 1.5;

makeLuaSprite('sky', 'bg1/sky', posX, posY);
setScrollFactor('sky', 0.1, 1);
scaleObject('sky', scale, scale);
addLuaSprite('sky', false);

runHaxeCode([[
	var clouds:FlxBackdrop = new FlxBackdrop(Paths.image('bg1/clouds'), 0x01);
	clouds.antialiasing = ClientPrefs.globalAntialiasing;
	game.insert(game.members.indexOf(game.getLuaObject('sky')) + 1, clouds);
	setVar('clouds', clouds);
]]);

setProperty('clouds.x', posX);
setProperty('clouds.y', posY);
setScrollFactor('clouds', 0.15, 1);
scaleObject('clouds', scale, scale);
setProperty('clouds.velocity.x', -10 * playbackRate);```

**Comment by KookerFoxYT** [comment]
btw you need to do the following in https://github.com/ShadowMario/FNF-PsychEngine/pull/9915 in order for it to work (requires source code)

**Comment by ShadowMario** [comment]
Backdrop wasn't ever used on the source so it didn't get compiled and so you can't use it with runHaxeCode.

**Comment by TheFNFRonFan** [comment]
function onCreate()
      makeLuaSprite('spriteName', 'imageName', x, y);  --creates a sprite
      setScrollFactory('spriteName' 1, 1);  --default
      scaleObject('spriteName',  1, 1); --default
      addLuaSprite('spriteName', false); --KEEP IT TO FALSE TO MAKE IT WORK
      close(true); --KEEP THIS TOO
end

sorry i don't know how to put  text like @charlesisfeline 's
