### ISSUE TITLE
How can I store a variable outside a song using Lua?

### ISSUE THREAD

**Issue by ScarabWasTaken** [ShadowMario/FNF-PsychEngine#12063]
### Describe your problem here.

I want to store a single boolean outside of a song that I can then access in different songs.

setProperty isn't working coz the property doesnt exist in the first place meaning it needs to be initialised. Could this be done with runHaxeCode()???

___

Well actually my goal is to be able to play multiple songs in a row as if they were a week using <loadSong(songName, difficulty)>
The trouble is when I load a song, the old script closes. Now placing the script in the scripts folder will make the script load on every song which would be fine as long as I have a way of knowing whether the song was loaded manually the normal way or via the script.
So I either need a way to keep the script open when the first song closes or I need a variable that exists outside the script that I can read/write to.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
#8286

**Comment by ScarabWasTaken** [comment]
Works like a charm, I just have no idea what master folder its using to save the file to.
