### ISSUE TITLE
HTML5 Songs Not Working

### ISSUE THREAD

**Issue by jasonglenevans** [ShadowMario/FNF-PsychEngine#12069]
### Describe your bug here.

The Songs Are Not Working In My HTML5 Build.
When I try to load one of the songs, it just gives me an error.

[lime.utils.Assets] ERROR: SOUND asset "songs:assets/songs/pb-extended/Voices.mp3" exists, but only asynchronously

Is there a fix for it?
What do I have to do to fix it?

### Command Prompt/Terminal logs (if existing)

```bash
[lime.utils.Assets] ERROR: SOUND asset "songs:assets/songs/pb-extended/Voices.mp3" exists, but only asynchronously
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

I was making a mod for pc, so i decided to make a html build.

**Comment by TheKitBoi** [comment]
convert ogg to mp3

**Comment by jasonglenevans** [comment]
> convert ogg to mp3

I did that already, i also tried to recompile the source code using the original assets, and they have the same error.

**Comment by ShadowMario** [comment]
Fixed.
