### ISSUE TITLE
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler

### ISSUE THREAD

**Issue by chasonic** [ShadowMario/FNF-PsychEngine#12061]
### Describe your problem here.

source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

NO

**Comment by AtlasGamer27** [comment]
Is this source code or a build from Releases?

**Comment by Matheus-Hideki** [comment]
try this: 
haxelib remove hxCodec
haxelib install hxCodec 2.5.1

**Comment by chasonic** [comment]
> try this in the terminal: haxelib remove hxCodec haxelib install hxCodec 2.5.1
> 
> they changed the MP4 method so this is required, maybe this works out

Installing hxCodec...
Error: Custom([file_write,C:/haxelib/hxCodec/2,5,1/ndll/Android/libvlc-64.so])

**Comment by Matheus-Hideki** [comment]
Try this:
haxelib remove lime
haxelib install lime 8.0.0

**Comment by KookerFoxYT** [comment]
> ### Describe your problem here.
> source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler
> 
> ### Are you modding a build from source or with Lua?
> Lua

while I could help you fix this, 
why choose the Lua option if you're trying to compile
