### ISSUE TITLE
Animated sprite not working in custom lua pause substate.

### ISSUE THREAD

**Issue by ManMaster707** [ShadowMario/FNF-PsychEngine#12070]
### Describe your problem here.

Basically, I wanted to make a custom lua pause substate (I'm in 0.6.3, which allows that) for a mod I'm working on, everything works fine except that an animated sprite required for it doesn't play its animation, which is supposed to loop, I tried everything but it wouldn't play (also yes, it played in normal circumstances so it's not a problem with the xml).

Is there a solution to this or is this normal behaviour (since every other animated sprite not in the pause menu pauses as well)?
And if it's normal behaviour, is there an alternative?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i just added things trough the "mods" folder.

**Comment by CaptainBaldi** [comment]
instead of using addLuaText/addLuaSprite or whatever use
`CustomSubstate.instance.add(game.getLuaObject('luaObj'));`

**Comment by ManMaster707** [comment]
> instead of using addLuaText/addLuaSprite or whatever use `CustomSubstate.instance.add(game.getLuaObject('luaObj'));`

Thank you very much, this worked!
