### ISSUE TITLE
How do I make sure os.execute executes a VBS script no matter where the game's folder is located?

### ISSUE THREAD

**Issue by Zer0PXL** [ShadowMario/FNF-PsychEngine#12072]
### Describe your problem here.

Title. I'm trying to make the game return a fake error message when you get a game over.

Code:

`function onGameOver()`
	
	os.execute("./undisclosed_files/crash_catch.vbs")
	os.exit()
	
`end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Luisinhi010** [comment]
i think psych lua dont have suport for os.

**Comment by CaptainBaldi** [comment]
as far as I know, you can't.

**Comment by CaptainBaldi** [comment]
> i think psych lua dont have suport for os.

It does.

**Comment by ROCK201888** [comment]
do this

function onGameOver()
    os.execute("start undisclosed_files/crash_catch.vbs")
    os.exit()
end

**Comment by Zer0PXL** [comment]
I'll just force the player put the game's folder on the desktop...
