### ISSUE TITLE
Can anyone help me to solve this fucking problem???

### ISSUE THREAD

**Issue by lava4-LvLOG** [ShadowMario/FNF-PsychEngine#12077]
### Describe your problem here.

when i try `lime build windows` and then the fucking errors are all popping out, so how to solve those???
`source/Main.hx:85: characters 35-36 : Int should be Null<Class<flixel.FlxState>>`
`source/Main.hx:85: characters 35-36 : ... For optional function argument 'initialState'`
`source/Main.hx:85: characters 35-36 : ... For function argument 'child'`
worry.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I pack it originally.

**Comment by Nightmistlol** [comment]
Replace Main.hx with https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

**Comment by lava4-LvLOG** [comment]
> Replace Main.hx with https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Main.hx

Compiling group: haxe
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/ -IC:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/ -I C:/HaxeToolkit/haxe/lib/hxCodec/2,5,1/lib/vlc/include/ -I C:/HaxeToolkit/haxe/lib/hxCodec/2,5,1/lib/vlc/src/ -nologo -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\LvLog\Desktop\FNFPE\export\release\windows\obj\obj/msvc64-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_CHECK_POINTER(haxe) -DHXCPP_STACK_LINE(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/flixel/system/debug/interaction/tools/Pointer.cpp
 - src/lime/_internal/backend/native/TextEventInfo.cpp
 - src/sys/io/_Process/Stdout.cpp
 - src/flixel/input/actions/_FlxSteamController/FlxSteamUpdater.cpp
 - src/flixel/input/actions/_FlxSteamController/FlxSteamControllerMetadata.cpp
 - src/flixel/path/FlxPathDrawData.cpp
 - src/openfl/display/_internal/Context3DElementType.cpp
Process creation failure : cl.exe

how about this
