### ISSUE TITLE
why is this happening?

### ISSUE THREAD

**Issue by YingWhatNow** [ShadowMario/FNF-PsychEngine#12079]
### Describe your bug here.

idk why but when ever i load my map the game crashes and shows this message

PlayState.hx (line 2641)
PlayState.hx (line 2469)
PlayState.hx (line 1086)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

help ;-;

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i just followed a tutorial

**Comment by frantastic24** [comment]
Not a bug
Don't use philly glow

**Comment by KookerFoxYT** [comment]
> ### Describe your bug here.
> idk why but when ever i load my map the game crashes and shows this message
> 
> PlayState.hx (line 2641) PlayState.hx (line 2469) PlayState.hx (line 1086) flixel/FlxGame.hx (line 637) flixel/FlxGame.hx (line 724) flixel/FlxGame.hx (line 677) flixel/FlxGame.hx (line 551) openfl/events/EventDispatcher.hx (line 402) openfl/display/DisplayObject.hx (line 1399)
> 
> Uncaught Error: Null Object Reference Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine
> 
> > Crash Handler written by: sqirra-rng
> 
> help ;-;
> 
> ### Command Prompt/Terminal logs (if existing)
> _No response_
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> i just followed a tutorial

philly glow is week 3-only
why not use a fanmade lua version of it then
