### ISSUE TITLE
Is it possible to make sustain behind Strumline like Forever Engine?

### ISSUE THREAD

**Issue by RandomUserOnInternet** [ShadowMario/FNF-PsychEngine#12073]
### Describe your problem here.

I want to make it like this (Source only) Thank You :) - If this issue duplicate, I'm sorry
![image](https://user-images.githubusercontent.com/105424534/224239000-82bc44a4-c908-4106-aa42-43503206f125.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MemeHovy** [comment]
unfortunately I'm at a loss on how, forever engine reworked FNF in many ways

**Comment by MemeHovy** [comment]
it might not be possible

**Comment by RandomUserOnInternet** [comment]
Oh It's ok Thank You MemeHovy to Answer my Question :)

**Comment by MemeHovy** [comment]
> Oh It's ok Thank You MemeHovy to Answer my Question :)

you're welcome :)
