### ISSUE TITLE
how do i fix this?

### ISSUE THREAD

**Issue by Trenton0** [ShadowMario/FNF-PsychEngine#1208]
### Describe your problem here.

i need help with this part in my script.lua

if 'ghostTapping' true then setProperty('ghostTapping') false,

i'm trying to disable ghosttapping whenever you play the song

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i didn't

**Comment by SrtHero278** [comment]
You need to add `, false` in the parenthesis. Like this:
```
if getProperty('ghostTapping') then --You can actually get rid of the '==' part if it's checking a Boolean value. Just add 'not' at the beginning if you're checking for 'false'
    setProperty('ghostTapping', false);
end
```

**Comment by Trenton0** [comment]
Thanks
