### ISSUE TITLE
Multiplayer Local & Online

### ISSUE THREAD

**Issue by BunfriendNinja2007** [ShadowMario/FNF-PsychEngine#12087]
### Describe your problem here.

How To Put The Multiplayer Mode To Play In Online And Local With Character Selector, GF Selector And Skins Selector With Source Code Only

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

MultiplayerState

**Comment by CaptainBaldi** [comment]
💀

**Comment by MemeHovy** [comment]
you are such an idiot @BunfriendNinja2007

**Comment by Hazardows** [comment]
☠️

**Comment by Nightmistlol** [comment]
Bruh 💀

**Comment by TheKitBoi** [comment]
> ### Describe your problem here.
> How To Put The Multiplayer Mode To Play In Online And Local With Character Selector, GF Selector And Skins Selector With Source Code Only

![ED04351E-9077-4451-A959-87EA37809B0E](https://user-images.githubusercontent.com/84044666/224700362-52bde261-a274-48a9-98b9-c6c981942f81.gif)

**Comment by KookerFoxYT** [comment]
bro, we only play fnf in single player 
bruh 💀

**Comment by KookerFoxYT** [comment]
and besides, there's already a local multiplayer lua script somewhere, but what's the point?!?

**Comment by BunfriendNinja2007** [comment]
The Point Is How To Play Multiplayer Online With Source Code Only

**Comment by TheKitBoi** [comment]
> The Point Is How To Play Multiplayer Online With Source Code Only

learn it yourself

**Comment by CasualCypress** [comment]
https://gamebanana.com/mods/431497

**Comment by KookerFoxYT** [comment]
> The Point Is How To Play Multiplayer Online With Source Code Only

im sorry but there is NO source code for any multiplayer mod here, so be it.
