### ISSUE TITLE
Error upon loading a sprite sheet in character editor

### ISSUE THREAD

**Issue by spooper1** [ShadowMario/FNF-PsychEngine#12088]
### Describe your bug here.

![image_2023-03-12_191127376](https://user-images.githubusercontent.com/127706361/224592393-04722e5f-db46-46ac-a49f-9c8232e061d1.png)
i got an error for loading a sprite sheet and when i hit ok it just closes idk if its the sprite sheet or .xml file
![pepino](https://user-images.githubusercontent.com/127706361/224592748-545f3b07-8d59-4d2d-9eec-ce1a492dcd8b.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by spooper1** [comment]
i know it uses pizza tower sprites i was just testing

**Comment by frantastic24** [comment]
not a bug
missing character files

**Comment by TheKitBoi** [comment]
> i know it uses pizza tower sprites i was just testing

send the damn files so we can fix ur crap

**Comment by spooper1** [comment]
> not a bug missing character files

ok good to know
