### ISSUE TITLE
Change Character work wrong

### ISSUE THREAD

**Issue by IvaskiyGooD** [ShadowMario/FNF-PsychEngine#12082]
### Describe your problem here.

When using Change Character, the BF changes instead of the opponent. It looks like I'm writing it right.

![image](https://user-images.githubusercontent.com/127319632/224555829-72d1e31d-6a45-4165-bfa1-294ef699f4f5.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Draconic-Hybrid** [comment]
Yeah, Change Character is kinda stupid in that its description is slightly misleading. Instead of putting text in Value 1, you'll need to put a number.

0 - Boyfriend
1 - Dad
2 - Girlfriend

**Comment by IvaskiyGooD** [comment]
> Yeah, Change Character is kinda stupid in that its description is slightly misleading. Instead of putting text in Value 1, you'll need to put a number.
> 
> 0 - Boyfriend 1 - Dad 2 - Girlfriend

Thanks!
