### ISSUE TITLE
How to change a looping animation to idle?

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#12089]
### What is your question?

Up

**Comment by Lorekeeper49** [comment]
I'm pretty sure using `playAnim()` to tell it to play the idle animation will work just fine

**Comment by NightmaresPlayz** [comment]
So playAnim(idle)

**Comment by NightmaresPlayz** [comment]
So for gf, it would be playAnim(‘gf’, ‘idle’)

**Comment by TheKitBoi** [comment]
yes
