### ISSUE TITLE
Can anyone help me with this ?

### ISSUE THREAD

**Issue by terrariakriss** [ShadowMario/FNF-PsychEngine#12084]
### Describe your bug here.

Paths.hx (line 356)
PlayState.hx (line 4105)
PlayState.hx (line 1377)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

Every time i want to play a song it crashes

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Not a bug
You are missing combo sprites
