### ISSUE TITLE
No opponent arrrow glow script doesn't work with pixel weeks

### ISSUE THREAD

**Issue by SteveeTheCreeper** [ShadowMario/FNF-PsychEngine#12083]
### Describe your problem here.

There is a script that I have that disables the arrow glow for opponent, but if I use it on any pixel week with pixel arrows the arrows just become big on the screen

![Screenshot_20230312_175622](https://user-images.githubusercontent.com/119169182/224556568-d60d2857-5a4d-4eda-9eab-866a4096d2f1.jpg)

Here is the code:
``function onSongStart() for i = 0, getProperty('opponentStrums.length') - 1 do setPropertyFromGroup('opponentStrums', i, 'visible', false); local strum = 'dadStrum' .. i; local dir = 'LEFT'; if i == 1 then dir = 'DOWN'; elseif i == 2 then dir = 'UP' elseif i == 3 then dir = 'RIGHT'; end makeAnimatedLuaSprite(strum, getPropertyFromGroup('opponentStrums', i, 'texture'), getPropertyFromGroup('opponentStrums', i, 'x'), getPropertyFromGroup('opponentStrums', i, 'y')); addAnimationByPrefix(strum, 'static', 'arrow' .. dir); scaleObject(strum, getPropertyFromGroup('opponentStrums', i, 'scale.x'), getPropertyFromGroup('opponentStrums', i, 'scale.y')); setObjectCamera(strum, 'hud'); addLuaSprite(strum); objectPlayAnimation(strum, 'static'); end end function onUpdatePost(elasped) for i = 0, getProperty('opponentStrums.length') - 1 do local strum = 'dadStrum' .. i; setProperty(strum .. '.x', getPropertyFromGroup('opponentStrums', i, 'x')); setProperty(strum .. '.y', getPropertyFromGroup('opponentStrums', i, 'y')); setProperty(strum .. '.angle', getPropertyFromGroup('opponentStrums', i, 'angle')); setProperty(strum .. '.alpha', getPropertyFromGroup('opponentStrums', i, 'alpha')); end if not botPlay then setTextString('funScore', 'Score: ' .. score .. ' Misses: ' .. misses); end end``

How to solve this problem?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by frantastic24** [comment]
`getPropertyFromGroup('opponentStrums', i, 'texture')` doesn't include the path to pixel sprites, just the texture name

**Comment by SteveeTheCreeper** [comment]
> `getPropertyFromGroup('opponentStrums', i, 'texture')` doesn't include the path to pixel sprites, just the texture name

I replaced the texture with pixel but the notes doesn't show anymore for both pixel and non pixel
![Uploading Screenshot_20230312_195144.jpg…]()

**Comment by frantastic24** [comment]
You didn't upload the image

**Comment by SteveeTheCreeper** [comment]
> You didn't upload the image

Edited the message

**Comment by frantastic24** [comment]
That means the texture doesn't exist

**Comment by Drawoon2** [comment]
Change the by this
`function opponentNoteHit(membersIndex, noteData, noteType, isSustainNote)
    runHaxeCode([[
		game.opponentStrums.members[]]..noteData..[[].playAnim('static', true)
	]])
end`

**Comment by frantastic24** [comment]
That works, as long as your static arrows are only 1 frame
