### ISSUE TITLE
How to operate the Doki yuri eyes like in Markov from DDTO Bad Ending in lua?

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#12099]
### What is your question?

Up

**Comment by CaptainBaldi** [comment]
can you stop asking questions like this
not everyone has played these mods and you dont explain what the thing you want is
you dont even give an example video of the mod or anything

**Comment by NightmaresPlayz** [comment]
Oh, sorry, I will send image and xml

**Comment by NightmaresPlayz** [comment]
![NOTE_splashes_doki](https://user-images.githubusercontent.com/107759455/225044986-012377a5-b8c6-4b70-b6b4-12ae5b132539.png)

**Comment by NightmaresPlayz** [comment]
And this is xml:

<?xml version="1.0" encoding="utf-8"?>
<TextureAtlas imagePath="NOTE_splashes_doki.png">
	
	
	<SubTexture name="note splash blue 2 instance 10000" x="10" y="10" width="376" height="376"/>
	<SubTexture name="note splash blue 2 instance 10001" x="396" y="10" width="376" height="376"/>
	<SubTexture name="note splash blue 2 instance 10002" x="782" y="10" width="376" height="376"/>
	<SubTexture name="note splash blue 2 instance 10003" x="1168" y="10" width="376" height="376"/>
	<SubTexture name="note splash blue 2 instance 10004" x="1554" y="10" width="376" height="376"/>
	<SubTexture name="note splash green 2 instance 10000" x="10" y="396" width="375" height="376"/>
	<SubTexture name="note splash green 2 instance 10001" x="395" y="396" width="375" height="376"/>
	<SubTexture name="note splash green 2 instance 10002" x="780" y="396" width="375" height="376"/>
	<SubTexture name="note splash green 2 instance 10003" x="1165" y="396" width="375" height="376"/>
	<SubTexture name="note splash green 2 instance 10004" x="1550" y="396" width="375" height="376"/>
	<SubTexture name="note splash purple 2 instance 10000" x="10" y="782" width="376" height="376"/>
	<SubTexture name="note splash purple 2 instance 10001" x="396" y="782" width="376" height="376"/>
	<SubTexture name="note splash purple 2 instance 10002" x="782" y="782" width="376" height="376"/>
	<SubTexture name="note splash purple 2 instance 10003" x="1168" y="782" width="376" height="376"/>
	<SubTexture name="note splash purple 2 instance 10004" x="1554" y="782" width="376" height="376"/>
	<SubTexture name="note splash red 2 instance 10000" x="10" y="1168" width="376" height="376"/>
	<SubTexture name="note splash red 2 instance 10001" x="396" y="1168" width="376" height="376"/>
	<SubTexture name="note splash red 2 instance 10002" x="782" y="1168" width="376" height="376"/>
	<SubTexture name="note splash red 2 instance 10003" x="1168" y="1168" width="376" height="376"/>
	<SubTexture name="note splash red 2 instance 10004" x="1554" y="1168" width="376" height="376"/>
</TextureAtlas>

**Comment by NightmaresPlayz** [comment]
<?xml version="1.0" encoding="utf-8"?>
<TextureAtlas imagePath="NOTE_splashes_doki.png">
	
	
	<SubTexture name="note splash blue 2 instance 10000" x="10" y="10" width="376" height="376"/>
	<SubTexture name="note splash blue 2 instance 10001" x="396" y="10" width="376" height="376"/>
	<SubTexture name="note splash blue 2 instance 10002" x="782" y="10" width="376" height="376"/>
	<SubTexture name="note splash blue 2 instance 10003" x="1168" y="10" width="376" height="376"/>
	<SubTexture name="note splash blue 2 instance 10004" x="1554" y="10" width="376" height="376"/>
	<SubTexture name="note splash green 2 instance 10000" x="10" y="396" width="375" height="376"/>
	<SubTexture name="note splash green 2 instance 10001" x="395" y="396" width="375" height="376"/>
	<SubTexture name="note splash green 2 instance 10002" x="780" y="396" width="375" height="376"/>
	<SubTexture name="note splash green 2 instance 10003" x="1165" y="396" width="375" height="376"/>
	<SubTexture name="note splash green 2 instance 10004" x="1550" y="396" width="375" height="376"/>
	<SubTexture name="note splash purple 2 instance 10000" x="10" y="782" width="376" height="376"/>
	<SubTexture name="note splash purple 2 instance 10001" x="396" y="782" width="376" height="376"/>
	<SubTexture name="note splash purple 2 instance 10002" x="782" y="782" width="376" height="376"/>
	<SubTexture name="note splash purple 2 instance 10003" x="1168" y="782" width="376" height="376"/>
	<SubTexture name="note splash purple 2 instance 10004" x="1554" y="782" width="376" height="376"/>
	<SubTexture name="note splash red 2 instance 10000" x="10" y="1168" width="376" height="376"/>
	<SubTexture name="note splash red 2 instance 10001" x="396" y="1168" width="376" height="376"/>
	<SubTexture name="note splash red 2 instance 10002" x="782" y="1168" width="376" height="376"/>
	<SubTexture name="note splash red 2 instance 10003" x="1168" y="1168" width="376" height="376"/>
	<SubTexture name="note splash red 2 instance 10004" x="1554" y="1168" width="376" height="376"/>
</TextureAtlas>

**Comment by NightmaresPlayz** [comment]
Bruh the xml won’t show

**Comment by NightmaresPlayz** [comment]
![Uploading 3DCEC486-9A6E-4AD6-A473-A47C6A9A72B9.png…]()

**Comment by frantastic24** [comment]
Read the wiki please, it has sprite and animation functions, that's all you need

**Comment by ActualMandM** [comment]
this is just an animated sprite placed onto camHUD, very easy to recreate it in lua

https://github.com/ActualMandM/Doki-Doki-Takeover-BAD-ENDING/blob/a571d1be24f68c37025821f0cf22741072027434/source/PlayState.hx#L4072-L4089
