### ISSUE TITLE
song not playing issue

### ISSUE THREAD

**Issue by dogflash11** [ShadowMario/FNF-PsychEngine#12093]
### Describe your problem here.

so my custom song gets stuck and the song doesn't play ANY sound at all. is there any solutions?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
wow this is the worst issue that ive ever seen
you dont describe what is happening at all

**Comment by dogflash11** [comment]
> wow this is the worst issue that ive ever seen you dont describe what is happening at all

alright, i described the problem, happy?
