### ISSUE TITLE
Crash on Week 6?

### ISSUE THREAD

**Issue by VirtMTTR** [ShadowMario/FNF-PsychEngine#12097]
### Describe your bug here.

Just wanted to play Week 6 again but every time I attempt to open any of the songs, it crashes with this error. I've removed my mods folder to be sure it wasn't a mod causing this issue.
This is the x86 build of Psych.

### Command Prompt/Terminal logs (if existing)

```bash
Paths.hx (line 356)
PlayState.hx (line 4098)
PlayState.hx (line 1377)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, apart from optimizing spritesheets.

**Comment by Ninjakaiden523** [comment]
What are the names of the new spritesheets?

**Comment by frantastic24** [comment]
Not a bug 
Missing rating sprites

**Comment by VirtMTTR** [comment]
Ah, apparently my copy of Psych just... never had rating sprites for pixel weeks??? Weird, I never touched those files. Added them back myself and week opens now. Thank you!
