### ISSUE TITLE
what does this error mean

### ISSUE THREAD

**Issue by PotatoKing0419** [ShadowMario/FNF-PsychEngine#12101]
### Describe your problem here.

what in the frizzley nizzley is this
![Screenshot 2023-03-14 174957](https://user-images.githubusercontent.com/92553022/225175325-8b0090a7-3ef7-4640-9056-39efff58cbfe.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Broken json

**Comment by PotatoKing0419** [comment]
ah ok thx
