### ISSUE TITLE
is there a way to put warnings in psych engine??

### ISSUE THREAD

**Issue by dogflash11** [ShadowMario/FNF-PsychEngine#12106]
### What is your question?

hey its me again, i have a question. So i added the screen shaking for a song and i dont want someone play that song without warning, what should i do?

**Comment by NightmaresPlayz** [comment]
There is a video on YouTube for that

**Comment by Chidubemmo** [comment]
I'm pretty sure that If you download the source code, by default there will be a warning screen for flashing lights when starting the mod even if you didn't change anything, just go inside FlashingState.hx and change the string value.
If you use lua instead you can simply generate some warning text or load an image inside the onCreate function or whatever it's called

**Comment by NightmaresPlayz** [comment]
i only know about lua 😅
