### ISSUE TITLE
song errors

### ISSUE THREAD

**Issue by plotmanlover** [ShadowMario/FNF-PsychEngine#12109]
### Describe your bug here.

so this happen for a WHOLE WEEK WITOUT NO ADDING SONG. due to this bug i cant put this last song in due to 1. it wont load it 2. i play with the chart with the data i already have in it and it just crashes. 3. IM LOSING MY MIND. no i dont change the stuff that is in it i only add songs, weeks, note_type, event, maps, and characters to the mod. only add i did... and yes they are .ogg
![a1](https://user-images.githubusercontent.com/119635880/225507024-1164f0f9-1f7c-4541-804d-4080d157f3b6.png)
![a2](https://user-images.githubusercontent.com/119635880/225507025-e42c2180-e2ca-4258-be4c-e0560b694d7b.png)
![a3](https://user-images.githubusercontent.com/119635880/225507037-b673fde2-7c66-40e9-9847-9a06fc6c5e20.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Not a bug
#11070

**Comment by plotmanlover** [comment]
oh shoot ok my inst and voices are 44.1k exactly ok ima fix that

**Comment by plotmanlover** [comment]
nope aint working. i even lower just a tensy bit

**Comment by plotmanlover** [comment]
if you wonder how i lowered it i used audacity

**Comment by plotmanlover** [comment]
so i find out you cant space the song name in the file for some reason
