### ISSUE TITLE
What happened here?

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#12117]
### Describe your problem here.

![Friday Night Funkin'_ Psych Engine 18_03_2023 10_59_22 AM](https://user-images.githubusercontent.com/107759455/226080925-36e03ea0-3b71-4f0f-b689-d5a168353410.png)
I have the data chart and it worked completely fine yesterday

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Chart isn't the problem, timeBar texture seems to be missing

**Comment by NightmaresPlayz** [comment]
Yeah, I tried adding some ddto plus assets, the note splash glitched because it was considered missing and so did the timebar
