### ISSUE TITLE
How can i read the number of difficulties a song/week has in lua?

### ISSUE THREAD

**Issue by ScarabWasTaken** [ShadowMario/FNF-PsychEngine#12118]
### Describe your problem here.

I just want some sort of "difficulty.length" if that makes sense.

I've tried:
#(getProperty(week), "difficulties")
#(getProperty(week).. "difficulties")
#getProperty(getProperty(week), "difficulties")
getProperty(getProperty(week), ".difficulties.length")
getProperty(getProperty(week).. ".difficulties.length")

among several other attempts

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by CaptainBaldi** [comment]
`getPropertyFromClass('CoolUtil', 'difficulties.length')` I think

**Comment by ScarabWasTaken** [comment]
Absolutely perfect thank you. You saved me probably another hour of trying to get this regex read of the week file to work.
