### ISSUE TITLE
 Expected }

### ISSUE THREAD

**Issue by Stefan2008Git** [ShadowMario/FNF-PsychEngine#12115]
### Describe your problem here.

I just tried to port credits to look likr from Denpa Engine, but i god this error
![Snimak ekrana 2023-03-18 000806](https://user-images.githubusercontent.com/126715034/226068268-294b7ece-deb2-4c2a-bb09-59ea743e7426.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yeah CreditsState.hx too look like Denpa Engine

**Comment by MemeHovy** [comment]
make sure you've put the `for` statement in the `changeSelection()` function and make sure to remove the duplicate Paths

**Comment by Stefan2008Git** [comment]
Fixed already

**Comment by Stefan2008Git** [comment]
Fixed already
