### ISSUE TITLE
engine doesn't allow the `global` keyword

### ISSUE THREAD

**Issue by Lorekeeper49** [ShadowMario/FNF-PsychEngine#12110]
### Describe your bug here.

with `global`:
![image](https://user-images.githubusercontent.com/93066594/225797181-762c299c-1bc7-4007-88e6-da0b4450d5c3.png)
with `local`:
![image](https://user-images.githubusercontent.com/93066594/225797235-c0a698ff-b57a-436a-a6ee-dc771ae1f3bf.png)

if this is the case, then how is `getGlobalFromScript(?luaFile:String, ?global:String)` and `setGlobalFromScript(luaFile:String, global:String, val:Dynamic)` supposed to work?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
Show me how you're using it

**Comment by Lorekeeper49** [comment]
> Show me how you're using it

Basically:
```lua 
global id = value 
```

**Comment by frantastic24** [comment]
> Global variables do not need declarations. You simply assign a value to a global variable to create it.
```lua
local d , f = 5 ,10     --declaration of d and f as local variables. 
d , f = 5, 10;          --declaration of d and f as global variables. 
d, f = 10               --[[declaration of d and f as global variables. 
                           Here value of f is nil --]]
```
https://www.lua.org/pil/1.2.html

**Comment by BeastlyGabi** [comment]
> > Show me how you're using it
> 
> Basically:
> 
> ```lua
> global id = value 
> ```

it's just `id = value`

**Comment by BeastlyGabi** [comment]
globals are automatically created when declaring a variable without `local` before it

**Comment by Lorekeeper49** [comment]
it worked, thanks guys
