### ISSUE TITLE
Game Crashed when loading a load stage

### ISSUE THREAD

**Issue by PortilizenHub** [ShadowMario/FNF-PsychEngine#12124]
### Describe your bug here.

everytime i load a lua stage it gives me a error and crashes the game

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2614)
PlayState.hx (line 2469)
PlayState.hx (line 1086)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

it wouldnt let me submit if nothing was here

**Comment by frantastic24** [comment]
Not a bug
Don't use philly glow

**Comment by PortilizenHub** [comment]
it doesnt

**Comment by PortilizenHub** [comment]
it it doesnt use philly glow

**Comment by frantastic24** [comment]
It was dadbattle spotlight, same thing
Don't use either of those

**Comment by PortilizenHub** [comment]
also it worked! nice and weird

**Comment by frantastic24** [comment]
They're hardcoded for their intended stages, it's intentional
