### ISSUE TITLE
My script is always being called when the song starts, but this is not what I want.

### ISSUE THREAD

**Issue by BlooDerg** [ShadowMario/FNF-PsychEngine#12129]
### Describe your problem here.

I want my lua event script to call whenever it is triggered in the chart editor, but it keeps triggering at the start of the song.

My script:
```
function onCreate()
	makeAnimatedLuaSprite('GATES', 'gate', -3000, -3500);
	addAnimationByPrefix('GATES', 'flow', 'gate', 24, true);
	objectPlayAnimation('GATES', 'flow');
	setProperty('GATES.scale.x', getProperty('GATES.scale.x') + 10);
	setProperty('GATES.scale.y', getProperty('GATES.scale.y') + 10);
end

function onEvent() -- this is what i want to start where i placed it to appear in the chart editor, but it is triggered when the song starts after the countdown
	addLuaSprite('GATES', true);
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, but there are too many changes I made to summarize them.

**Comment by xboomerboyx** [comment]
Have you tried just having it create the sprites on the event, instead of at the beginning of the song?

**Comment by BlooDerg** [comment]
thats what im asking, how do you do that?

**Comment by xboomerboyx** [comment]
You should just be able to copy the code from below the onSongStart function, and put it below the onEvent function but above the line that make the sprites.

**Comment by frantastic24** [comment]
onEvent is called for all events, if you don't check the event name it'll be called every time
This is why you use `function onEvent(name, value1, value2` and `if name == 'event name' then`

**Comment by xboomerboyx** [comment]
Oh right, thank you for correcting me.

**Comment by BlooDerg** [comment]
i realized i was missing an "=", but now its not doing anything.

**Comment by xboomerboyx** [comment]
Are you putting the name of your custom event?

**Comment by BlooDerg** [comment]
Yes, the name is correct

**Comment by xboomerboyx** [comment]
Let me see the code. I'll see if I ca n do anything.

**Comment by BlooDerg** [comment]
```
-- Lua stuff
function onCreate()
	makeAnimatedLuaSprite('GATES', 'gate', 0, 0);
	addAnimationByPrefix('GATES', 'flow', 'gate', 24, true);
	objectPlayAnimation('GATES', 'flow');
	setProperty('GATES.scale.x', getProperty('GATES.scale.x') + 10);
	setProperty('GATES.scale.y', getProperty('GATES.scale.y') + 10);
end

function onEvent(name, value1, value2)
	if name == 'GateFlow' then
		if value1 == 1 then
			addLuaSprite('GATES', true);
		elseif value1 == 0 then
			removeLuaSprite('GATES', true);
		end
	end
end
```

**the name of this event is "GateFlow"

**Comment by xboomerboyx** [comment]
Shouldn't it be, "addAnimatedLuaSprite"? Since you've made the rest of the sprite animated on the SongStart function.

**Comment by BlooDerg** [comment]
makeAnimatedLuaSprite has always worked for me

**Comment by xboomerboyx** [comment]
Im just saying, you're making it make a normal lua sprite when the event is called, but since youre trying to make it animated, shouldn't it be called as an animated lua sprite?

**Comment by BlooDerg** [comment]
doing either or hasnt change anything

**Comment by xboomerboyx** [comment]
Just so I'm clear, the two zeros in the first line of code are the coordinates, correct?

**Comment by BlooDerg** [comment]
yeah, but they're "-3000, -3500" now, still not appearing

**Comment by xboomerboyx** [comment]
Try 990, 540. I got these from an event I use that makes an image flash on the screen.

**Comment by BlooDerg** [comment]
that worked?????? i guess

**Comment by xboomerboyx** [comment]
Yeah. If the coords are in the thousands, they go off screen. And at 0, 0, I guess theyre also offscreen. Glad I could help some. Have fun with your mod.

**Comment by frantastic24** [comment]
`value1` and `value2` always return strings, you're comparing a string to an int so it will never be true
Use `if value 1 == '1' then` or `if tonumber(value1) == 1 then`
