### ISSUE TITLE
Visual Studio 2017 Bug

### ISSUE THREAD

**Issue by YodaFry8859** [ShadowMario/FNF-PsychEngine#12126]
### Describe your bug here.

I was on the final step of downloading the FNF Psyche Engine when it says "Could not find Visual Studio 2017" when I had downloaded Visual Studio already.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment]
Not a bug
You did not install visual studio and the necessary components properly
