### ISSUE TITLE
can i do smooth health adding with lua?

### ISSUE THREAD

**Issue by ROCK201888** [ShadowMario/FNF-PsychEngine#12125]
### What is your question?

the title will tell you

**Comment by MemeHovy** [comment]
pretty sure it's not possible

**Comment by CaptainBaldi** [comment]
I suppose you could try setting it's `numDivisions` property?
for Lua, you could try `setProperty('healthBar.numDivisions', value)`
for HScript you could try runHaxeCode('game.healthBar.numDivisions = value;')

**Comment by ROCK201888** [comment]
> 

both didn't work

**Comment by ROCK201888** [comment]
> You don't need source I copied the lerp function and used it with `setProperty('healthBar.value', value)`, it's not complicated

this don't work too , can i do it with runHaxeCode?

**Comment by Ratio-Combinder** [comment]
> this don't work too , can i do it with runHaxeCode?

did you change the number and what game version are you using

**Comment by ROCK201888** [comment]
> > this don't work too , can i do it with runHaxeCode?
> 
> did you change the number and what game version are you using

i changed the number and i am on 0.6.3

**Comment by ROCK201888** [comment]
> > i changed the number and i am on 0.6.3
> 
> then show the code

setProperty('healthBar.value', 100)

**Comment by frantastic24** [comment]
1. Where's the `lerp`
2. Value only goes up to 2, min 0

**Comment by ROCK201888** [comment]
> 1. Where's the `lerp`
> 2. Value only goes up to 2, min 0
oops wrong title

**Comment by ROCK201888** [comment]
> 1. Where's the `lerp`
> 2. Value only goes up to 2, min 0

oops wrong title

**Comment by frantastic24** [comment]
I don't know what you mean by that but I don't think there is a difference

**Comment by ROCK201888** [comment]
> I don't know what you mean by that but I don't think there is a difference

i mean like indie cross smooth health bar

**Comment by frantastic24** [comment]
Ok so it's the same thing
Use lerp

**Comment by ROCK201888** [comment]
> Ok so it's the same thing Use lerp

what is lerp?

**Comment by ROCK201888** [comment]
HELP
