### ISSUE TITLE
My UI Camera is completely broken

### ISSUE THREAD

**Issue by StpYT** [ShadowMario/FNF-PsychEngine#12120]
### Describe your problem here.

I don't know what happen, but it seems every Psych Engine I use is broken. The camera specifically. Every time the opponent hits their notes, the entire games UI just zooms in. And it's not just vanilla Psych. They're all doing. it seems to happen to all of them, I just want to see my Psych work again, correctly of course. even when downloading a fresh one, it's still does it 
![image](https://user-images.githubusercontent.com/118869379/226123313-0ce3f65e-1e9b-4f59-8448-474f7029a8ba.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no, every camera is broke

**Comment by TheKitBoi** [comment]
your running the game at a lower resolution
the default is 1280 by 720

**Comment by StpYT** [comment]
@TheKitBoi Yea your right, It's this monitor then, cus I'm at 1080. Thanks for telling me. Looks like I'ma need a new monitor
