### ISSUE TITLE
how fuck get property hide_girlfriend from stage

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#12133]
### Describe your problem here.

i hat getting proeprtyie sit never wokrs :(((

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by wubbzyfan** [comment]
im losng it

**Comment by DabbinDude316B** [comment]
set true to false

**Comment by wubbzyfan** [comment]
i know how to, how to detect it

**Comment by wubbzyfan** [comment]
how to getproperty it (/ getpropertyfromclass it)

**Comment by Lorekeeper49** [comment]
`getProperty('song.stage.hide_girlfriend')` I'm pretty sure, could be wrong though

**Comment by wubbzyfan** [comment]
didnt work

**Comment by Drawoon2** [comment]
Try this `runHaxeCode("return game.gf==null;")`
