### ISSUE TITLE
Does psych engine tell your friends you are playing fnf?

### ISSUE THREAD

**Issue by Boyfriedd** [ShadowMario/FNF-PsychEngine#12132]
### What is your question?

Does psych engine tell your friends if you are so basically like "(username) Playing Psych engine"

**Comment by CaptainBaldi** [comment]
but you have no friends?

**Comment by MemeHovy** [comment]
> ### What is your question?
> Does psych engine tell your friends if you are so basically like "(username) Playing Psych engine"

yes

**Comment by TheKitBoi** [comment]
> ### What is your question?
> Does psych engine tell your friends if you are so basically like "(username) Playing Psych engine"

`discord rpc exists`

**Comment by NotStampyC** [comment]
> > but you have no friends?
> 
> I do

nope u dont
