### ISSUE TITLE
What's the function to do it?

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#12130]
### What is your question?

I'm trying to do it so when `dadName` ends with "-ex", i do something different on the script but I don't know what function to detect that

**Comment by frantastic24** [comment]
This is a lua question, use Google
https://www.tutorialspoint.com/string-find-function-in-lua

**Comment by BernardoGP4504** [comment]
> This is a lua question, use Google https://www.tutorialspoint.com/string-find-function-in-lua

Alright, thanks! Helped out a thon!
