### ISSUE TITLE
addglitcheffect

### ISSUE THREAD

**Issue by BlazeBFBFlame** [ShadowMario/FNF-PsychEngine#12136]
### Describe your bug here.

I try to add the little "addGlitchEffect" to Psych Engine. 
But...

![image](https://user-images.githubusercontent.com/105085698/226504733-ce288bdd-e3dd-40b8-9464-b5f7cf1c37cd.png)

### Command Prompt/Terminal logs (if existing)

```bash
idk wtf is this
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yeah i added glitch effect duh

**Comment by BlazeBFBFlame** [comment]
> 'yeah i added glitch effect duh' yeah no one knows what your code even looks like duh you also didnt show the location of the error duh

bro its from os engine search "addshadertocamera"
and when i change public to private it 
do you have eyes the location its in the picture
its at the end of playstate

**Comment by ShadowMario** [comment]
Sorry but if it's code from another engine you're on your own on this.

**Comment by BlazeBFBFlame** [comment]
nvm i going back to source
