### ISSUE TITLE
Can custom notes having variables like events be added?

### ISSUE THREAD

**Issue by PoleyMagik** [ShadowMario/FNF-PsychEngine#1213]
### What feature do you want to get added on the base engine?

Can custom notes having variables like events be added, like this?
![image](https://user-images.githubusercontent.com/59105820/142743306-7627f041-762a-49c8-9f95-a6ac777e41c4.png)

**Comment by SrtHero278** [comment]
I would like to see that. It would be dandy.

**Comment by 4wdthinks** [comment]
yes, like with a hurt note you could configure its damage when hit.
![image](https://user-images.githubusercontent.com/79160331/143073622-8d2d67f3-12ca-4fc9-a9fb-03d159ab375d.png)
