### ISSUE TITLE
Error: Could not process argument tools.hxml (file not found) Invalid character:

### ISSUE THREAD

**Issue by WinV-Bros** [ShadowMario/FNF-PsychEngine#12134]
### Describe your problem here.

This is my first time trying to compile psych engine and I got the error that you saw on the title
help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing yet

**Comment by Ratio-Combinder** [comment]
`haxelib run lime setup`

**Comment by WinV-Bros** [comment]
same error

**Comment by WinV-Bros** [comment]
i fixed it, i just had to remove and readd lime
