### ISSUE TITLE
Error: Could not find include file "C:/HaxeToolkit/haxe/lib/hxCodec/2,6,1/vlc/lib/LibVLCBuild.xml"

### ISSUE THREAD

**Issue by Danky136** [ShadowMario/FNF-PsychEngine#12145]
### Describe your bug here.

I have been trying to compile my game for almost 2 and a half hours now. it is saying that I must update my hxCodec to 2.6.1 in order to compile the game. However, if I put it to 2.6.1 it then gives me the MP4Handler error. is there any possible way to fix this error?

### Command Prompt/Terminal logs (if existing)

```bash
Error: Could not find include file "C:/HaxeToolkit/haxe/lib/hxCodec/2,6,1/vlc/lib/LibVLCBuild.xml"
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by CaptainBaldi** [comment]
use the latest playstate i'm pretty sure they've fixed the errors with hxCodec

**Comment by Danky136** [comment]
Where do I find the latest version of its playstate?
