### ISSUE TITLE
This is probably an easy problem to help me with

### ISSUE THREAD

**Issue by KaptainChris** [ShadowMario/FNF-PsychEngine#12143]
### Describe your problem here.

I have no clue how to code whatsoever, but I want to make winning icons and losing icons, but I don't have the script for them? Anyone know how to do it. As a sample script I could edit later the dad script for the winning and losing icons should do.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
There are a lot of posts about this already, use the search feature
Also don't open duplicates

**Comment by KaptainChris** [comment]
Alright @frantastic24 Thanks!

**Comment by KaptainChris** [comment]
@frantastic24 How do I search here for the icons, I got 8 issues on them, but no answer?

**Comment by AyMarte** [comment]
Search: `is:closed Icons` it should find all the solved ones.

**Comment by KaptainChris** [comment]
Thank You!!!!!! @AyMarte

**Comment by AyMarte** [comment]
Any time, but you should still close this issue. It does flood with the other ones.

**Comment by KaptainChris** [comment]
Ok
