### ISSUE TITLE
Sprite visual effects? (IDK how to put it)

### ISSUE THREAD

**Issue by YKoF-CALm** [ShadowMario/FNF-PsychEngine#12144]
### What feature do you want to get added on the **base** engine?

I'm not too sure if this was mentioned before, but I'd like to see the HSB (Hue Saturation Brightness) color changing scheme applied to Lua sprites as well. For now we only have them on notes and note splashes. Apologies in advance if this has been brought up before or is already being worked on.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
It's a shader, you can use those through runHaxeCode

**Comment by YKoF-CALm** [comment]
I see. If you don't mind, can you show me how? Or where to look to start?

**Comment by YKoF-CALm** [comment]
Alright, NVM, I think I figured it out. However, for some reason, the shader (ColorSwap) won't accept negative values though. Why is that?

**Comment by YKoF-CALm** [comment]
NVM, figured it out as well.

**Comment by VoidedBattery** [comment]
> Alright, NVM, I think I figured it out. However, for some reason, the shader (ColorSwap) won't accept negative values though. Why is that?

Do you know how you got it? I could probably use some help figuring out how to do it as well

**Comment by YKoF-CALm** [comment]
> > Alright, NVM, I think I figured it out. However, for some reason, the shader (ColorSwap) won't accept negative values though. Why is that?
> 
> Do you know how you got it? I could probably use some help figuring out how to do it as well

You need to use `addHaxeLibrary('ColorSwap', 'shaders')`.
Then to use the shader, you do the following:
```
runHaxeCode([[
        var colorSwap = new ColorSwap();
        game.modchartSprites.get(SPRITENAMEHERE).shader = colorSwap.shader;
        colorSwap.hue = ?/360;
        colorSwap.saturation = ?/100;
        colorSwap.brightness = ?/100;
]])
```
And that should be done.
Note: you don't need to input all 3 values, just the ones you need. You can check the ColorSwap shader in the source code for the default values.

**Comment by VoidedBattery** [comment]
> > > Alright, NVM, I think I figured it out. However, for some reason, the shader (ColorSwap) won't accept negative values though. Why is that?
> > 
> > 
> > Do you know how you got it? I could probably use some help figuring out how to do it as well
> 
> You need to use `addHaxeLibrary('ColorSwap', 'shaders')`. Then to use the shader, you do the following:
> 
> ```
> runHaxeCode([[
>         var colorSwap = new ColorSwap();
>         game.modchartSprites.get(SPRITENAMEHERE).shader = colorSwap.shader;
>         colorSwap.hue = ?/360;
>         colorSwap.saturation = ?/100;
>         colorSwap.brightness = ?/100;
> ]])
> ```
> 
> And that should be done. Note: you don't need to input all 3 values, just the ones you need. You can check the ColorSwap shader in the source code for the default values.

TYSM! It worked!!

**Comment by VoidedBattery** [comment]
> > > Alright, NVM, I think I figured it out. However, for some reason, the shader (ColorSwap) won't accept negative values though. Why is that?
> > 
> > 
> > Do you know how you got it? I could probably use some help figuring out how to do it as well
> 
> You need to use `addHaxeLibrary('ColorSwap', 'shaders')`. Then to use the shader, you do the following:
> 
> ```
> runHaxeCode([[
>         var colorSwap = new ColorSwap();
>         game.modchartSprites.get(SPRITENAMEHERE).shader = colorSwap.shader;
>         colorSwap.hue = ?/360;
>         colorSwap.saturation = ?/100;
>         colorSwap.brightness = ?/100;
> ]])
> ```
> 
> And that should be done. Note: you don't need to input all 3 values, just the ones you need. You can check the ColorSwap shader in the source code for the default values.

Do you know by any chance if it could work with sprites the game already loaded, like the opponent, player, icons, etc?

**Comment by YKoF-CALm** [comment]
Yes, that would work for the characters. As for icons, I assume you would use `game.iconP1.shader` and `game.iconP2.shader`.
