### ISSUE TITLE
How to make the Icons Move like in the Week 7 Version of FNF

### ISSUE THREAD

**Issue by RiloTheFox** [ShadowMario/FNF-PsychEngine#1214]
### What is your question?

I was wondering, is it possible to adjust the Icon Moving on Beat speed to be smoother like in the Week 7 Version of FNF?

Other engines like Mic'd Up, and Andromeda also have the icons moving smoothly.

Note: This is for the Source Code.

**Comment by PoleyMagik** [comment]
Y'know? I never noticed they slightly changed that animation. Give me a bit and i'll try and figure out week 7's way of doing it for you.

**Comment by nintendofan44** [comment]
yo

**Comment by nintendofan44** [comment]
i know how to do that

**Comment by nintendofan44** [comment]
search for this with ctrl + f:
```
iconP1.setGraphicSize(Std.int(FlxMath.lerp(150, iconP1.width, CoolUtil.boundTo(1 - (elapsed * 30), 0, 1))));
iconP2.setGraphicSize(Std.int(FlxMath.lerp(150, iconP2.width, CoolUtil.boundTo(1 - (elapsed * 30), 0, 1))));
```

then swap it with this:
```
iconP1.setGraphicSize(Std.int(FlxMath.lerp(iconP1.width, 150, 0.09 / (openfl.Lib.current.stage.frameRate / 144))));
iconP2.setGraphicSize(Std.int(FlxMath.lerp(iconP2.width, 150, 0.09 / (openfl.Lib.current.stage.frameRate / 144))));
```

after that, search for this:
```
iconP1.setGraphicSize(Std.int(iconP1.width + 30));
iconP2.setGraphicSize(Std.int(iconP2.width + 30));
```

then swap it with this:
```
iconP1.setGraphicSize(Std.int(iconP1.width + 45));
iconP2.setGraphicSize(Std.int(iconP2.width + 45));
```

**Comment by PoleyMagik** [comment]
thank you for finding the answer looking through week 7's code suuucks idk why i said i would figure it out

**Comment by nintendofan44** [comment]
no problem

**Comment by gaminbottomtext** [comment]
you should probably  do this for the first one 		iconP1.setGraphicSize(Std.int(FlxMath.lerp(iconP1.width, 150, 0.15)));
		iconP2.setGraphicSize(Std.int(FlxMath.lerp(iconP1.width, 150, 0.15)));

and then for the second one, do this 		iconP1.setGraphicSize(Std.int(iconP1.width + 30));
		iconP2.setGraphicSize(Std.int(iconP2.width + 30));  this is the same thing

**Comment by PoleyMagik** [comment]
> you should probably do this for the first one
> 
> ```
> 		iconP1.setGraphicSize(Std.int(FlxMath.lerp(iconP1.width, 150, 0.15)));
> 		iconP2.setGraphicSize(Std.int(FlxMath.lerp(iconP1.width, 150, 0.15)));
> ```
> 
> and then for the second one, do this
> 
> ```
> 	iconP1.setGraphicSize(Std.int(iconP1.width + 30));
> 		iconP2.setGraphicSize(Std.int(iconP2.width + 30));
> ```
> 
> this is the same thing

actually this way is worse because it doesn't account for the framerate

anywho this issue can be closed

**Comment by ShadowMario** [comment]
Added
