### ISSUE TITLE
GLSL Version Problems

### ISSUE THREAD

**Issue by YKoF-CALm** [ShadowMario/FNF-PsychEngine#12153]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/65105169/227664135-7f848032-6e67-4a8f-b11e-a60e3bbde655.png)

So, I get this error, and after doing a bit of digging around, I realized that this is the problem of the GLSL version, since the shader requires version 130 while I was using version 120.
So I used `initLuaShader('chromaticabberation', 130)`, since the 2nd value was to denote the GLSL version of the shader.
I get the same error.
Is this a me problem where I'm doing something wrong, or is there just no workaround to this?

(`chromaticabberation` is the shader that I'm using)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing (except for adding modpacks).

**Comment by UncertainProd** [comment]
Try replacing the `texture` function with `texture2D` ?

**Comment by YKoF-CALm** [comment]
> Try replacing the `texture` function with `texture2D` ?

Tried it, and it doesn't give me the error anymore. However, the shader right now just does nothing at all.

**Comment by YKoF-CALm** [comment]
It works now, thanks.
