### ISSUE TITLE
Lua Timers are not consistent with Song Position

### ISSUE THREAD

**Issue by Templarfreak** [ShadowMario/FNF-PsychEngine#1215]
### Describe your bug here.

it looks like there can be a small amount of variance in timer lengths. probably due to being tied to frame rate?
![image](https://user-images.githubusercontent.com/2140802/142747901-a7c8e1d8-10d2-4e39-b1f2-ed4c4bf161de.png)

these numbers came from starting a timer on `onCreate` and then doing 

`debugPrint(getPropertyFromClass('Conductor', 'songPosition'));` 

on the timer completing to see where the time of the song is at. 

one would expect that this should give the exact-same `songPosition` every single time.

this doesnt seem like a lot of variance at first, but just a few milliseconds of difference like this could compound (like when starting a different timer after a timer has finished, or restarting or looping the same timer, many times) and lead to noticeable amounts of syncing problems

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
Song Position is tied to framerate.
If you want to get the current time use os.clock()

**Comment by Templarfreak** [comment]
that's not the issue i am reporting. the timer is never on the **SAME** song position. it is not predictable when the timer actually completes.
