### ISSUE TITLE
My game won't start

### ISSUE THREAD

**Issue by jefferysans** [ShadowMario/FNF-PsychEngine#12157]
### Describe your bug here.

Whenever I open the game it crashes. I have not modded anything
Whenever I use x32 it works but before I was able to use x64 and x32 has been doing the same thing recently too.
And for other ones I use i get 
[lime.utils.preloader] Error:There is no asset library with an id of "videos"
### Command Prompt/Terminal logs (if existing)

```bash
StoryMenuState.hx (line 130)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/notweuz/FNF-OSEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No nothing was changed for the base game. The modded games gave me the same error. EX being Mistful Crimson Morning.

**Comment by cookie-man123** [comment]
have you tried deleting some of the mods in your mods folder?
or deleted anything from the stock mods/assets/shared folders?

**Comment by jefferysans** [comment]
I have tried deleting the mods in the mod folder and that didnt work. I also have not changed a thing from the mods I had downloaded.

**Comment by cookie-man123** [comment]
have you tried downloading a new zip of psych engine

**Comment by Jeremyy591** [comment]
I got the same problem over here. There weren't any mod or anything when i downloaded the mod, i was able to play but just trying to go on the story mode crashes the game.

**Comment by NotStampyC** [comment]
Check the week files to see if anything is missing

**Comment by Adversiz** [comment]
I found a gamebanana post which helped me : https://gamebanana.com/posts/11444844

**Comment by TheNoicyGuy** [comment]
I HAVE BEEN ALSO HAVE THE SAME PROBLEM PLEASE GIVE A SOLUTION
