### ISSUE TITLE
How do you set the folder for initSaveData function ?

### ISSUE THREAD

**Issue by Shaggers-official** [ShadowMario/FNF-PsychEngine#12150]
### Describe your problem here.

I'm trying to create a data whenever a song loads itself but i don't know why, it doesn't create one, i've every single folder that exists in my mod, but still nothing happens. Maybe i'm setting the folder location the wrong way so i just want to know how to i put it in a specific song data folder. Here's my code btw : 

```
function onCreatePost()
    initSaveData('fnaf', 'data/brimstone')
    if getDataFromSave('fnaf', 'FC') == true then
        giveStar()
    elseif getDataFromSave('fnaf', 'Perfect') == true then
        giveStar()
    end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
save files arent generated in the psych engine folder

**Comment by Shaggers-official** [comment]
Oh okay, so i guess i have to figure out something else then. Thanks for the info
