### ISSUE TITLE
Wont Reload Character Images

### ISSUE THREAD

**Issue by FunkstaFNF** [ShadowMario/FNF-PsychEngine#12154]
### Describe your bug here.

Im making a fnf mod and i just tried to add some bf assets, i reloaded the images but the game showed an error and crashed. but now i dont know what to do cause i NEED these assets ive made to make my mod

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/frames/FlxAtlasFrames.hx (line 250)
editors/CharacterEditorState.hx (line 840)
editors/CharacterEditorState.hx (line 520)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

it wouldnt let me submit if nothing was here

**Comment by KookerFoxYT** [comment]
cant wait for frantastic24 to say "Not a bug, missing textures"

**Comment by FunkstaFNF** [comment]
that would be very dumb since i do have the png and json, and even when i had the json modified from the bf one to change the image path it still gave an error but it was kinda different so yuh. but this main issue is the main problem

**Comment by MemeHovy** [comment]
> cant wait for frantastic24 to go here and say "Not a bug, missing character files"

that's why I hate him

**Comment by MemeHovy** [comment]
he's an idiot

**Comment by frantastic24** [comment]
> cant wait for frantastic24 to go here and say "Not a bug, missing character files"

Correct you're so smart!! Characters don't use json

**Comment by CaptainBaldi** [comment]
> cant wait for frantastic24 to go here and say "Not a bug, missing character files"

frantastic24 w fr

**Comment by CaptainBaldi** [comment]
and that probably is the problem looking at the source files mentioned in the crash
