### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by SrBagel** [ShadowMario/FNF-PsychEngine#12163]
### Describe your problem here.

whenever I try to compile Psych engine this error appears 
'neko' is not recognized as an internal or external command,operable program or batch file.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a stage and added win icons

**Comment by LilDrippyMyFnf** [comment]
did you install neko?

**Comment by SrBagel** [comment]
> did you install neko?
no

**Comment by SrBagel** [comment]
> did you install neko?

i uninstalled it but that broke it even more

**Comment by MemeHovy** [comment]
you shouldn't need neko to compile to windows @SrBagel
