### ISSUE TITLE
I was wondering something

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#12164]
### What is your question?

Hey its been a while i was wondering

can you modify the text below the Tracks to have some songs names have different colors or just the letters shuffle?

sorry if this is confusing this is most likely impossible but i would like to know if it isnt

![image](https://user-images.githubusercontent.com/56323671/227801923-896fc615-8fbe-4eeb-8e9e-90dd1ae220d3.png)

**Comment by UncertainProd** [comment]
Don't think it's possible from lua but definitely possible with some source code changes
