### ISSUE TITLE
The animatedluasprite command isnt working,

### ISSUE THREAD

**Issue by ShatteredEcHOs** [ShadowMario/FNF-PsychEngine#12162]
### Describe your problem here.

I've been trying to add an explosion animation. The explosion animation is in the mods/images folder, the animation name on the .XML file is called, "explosion idle", here's the script. My problem is that the animation doesn't play.

function onStepHit()
    if curStep == 1025 then
        makeAnimatedLuaSprite('explosion', 'explosion', 850, 1200)
        playAnim('explosion', 'explosion idle', false)
    end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Its using the Ourple Guy mod. (Not source code just the mod.)

**Comment by CaptainBaldi** [comment]
you didnt even add the animation :skull:

**Comment by ShatteredEcHOs** [comment]
oh mb 
![explosion](https://user-images.githubusercontent.com/112781330/228061902-e7cbe5b4-9fff-473e-b238-4e7a0199b4a7.png)

**Comment by frantastic24** [comment]
They meant you didn't add the animation to the sprite, in your code
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#animations-functions

**Comment by ShatteredEcHOs** [comment]
i did i thought? I put "explosion idle", in the playanim. Where do I put it then?

**Comment by frantastic24** [comment]
That's not how it works
To play an animation you first have to add it to the object, read the wiki link for functions

**Comment by ShatteredEcHOs** [comment]
I got it, thank you guys!!!
