### ISSUE TITLE
pause not working

### ISSUE THREAD

**Issue by JKBowdenOfficial** [ShadowMario/FNF-PsychEngine#12161]
### Describe your bug here.

no clue why but im unable to pause in psych anymore, my only way of reverting to the menu is dying. really weird bug and it's spread across all my builds of 0.6.3, any idea of whats going on?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

all i did was add a couple of mods, e.g funkin' peanuts demo or jumpman (gangsta mario)

**Comment by SrBagel** [comment]
is there any sort of lua script that could be causing this?

**Comment by CaptainBaldi** [comment]
prob smth with ur mods

**Comment by AyMarte** [comment]
@JKBowdenOfficial, try to find this line of code in any of the scripts in your game:
```
function onPause()
retunr Function_Stop;
end
```

**Comment by AyMarte** [comment]
Like stating here: [|||||||](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/docs/TemplateScript.lua#L59-L63)

**Comment by JKBowdenOfficial** [comment]
> 

honestly it ended up just suddenly working again without explanation so god knows what my pysch is doing
