### ISSUE TITLE
how to change camera of opponent notes

### ISSUE THREAD

**Issue by alex-codes-stuff** [ShadowMario/FNF-PsychEngine#12171]
### Describe your problem here.

how do i set the opponeny's notes camera (like how the setObjectCamera() function does it)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Drawoon2** [comment]
```
runHaxeCode([[
        game.strumLineNotes.members[0].cameras=[getVar('camName')];
        game.strumLineNotes.members[1].cameras=[getVar('camName')];
        game.strumLineNotes.members[2].cameras=[getVar('camName')];
        game.strumLineNotes.members[3].cameras=[getVar('camName')];
    ]])
```
