### ISSUE TITLE
McMadness Duplicating And Editing Visual Notes

### ISSUE THREAD

**Issue by AyMarte** [ShadowMario/FNF-PsychEngine#12176]
### What is your question?

Is there any possible way I could replicate the players notes duplication like for example in this [video](https://www.youtube.com/watch?v=ySTLrc35t_A)?

## What type of code are you using?
Lua

**Comment by UncertainProd** [comment]
I would recommend looking at this repo: https://github.com/TheZoroForce240/FNF-Modcharting-Tools
It allows you to do that kind of stuff (plus the repo is made by the coder for that mod anyway)

**Comment by AyMarte** [comment]
> I would recommend looking at this repo: https://github.com/TheZoroForce240/FNF-Modcharting-Tools It allows you to do that kind of stuff (plus the repo is made by the coder for that mod anyway)
But when I tried installing it, it failed.

**Comment by UncertainProd** [comment]
Were you using the latest versions of flixel (5.2.2) and flixel-addons (3.0.2) ?

**Comment by AyMarte** [comment]
> Were you using the latest versions of flixel (5.2.2) and flixel-addons (3.0.2) ?

Check this: [What I have tried to do and get help with](https://github.com/TheZoroForce240/FNF-Modcharting-Tools/issues/20)

**Comment by biomseed** [comment]
You could try using a shader to easily do this
