### ISSUE TITLE
Health Drain Thingie

### ISSUE THREAD

**Issue by NavaGaming** [ShadowMario/FNF-PsychEngine#12179]
### Describe your problem here.

How the hell i make health drain only at GF sections?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by DisIsNOt** [comment]
function opponentNoteHit()

**Comment by AyMarte** [comment]
Use this, this should work out.

`local healthToDrain = 0.03 --Set This To The Value Of How Much Health You Want To Drain.
function opponentNoteHit(id, noteType, noteData, isSustainNote)
     if noteType == "GF Sing" then
          setProperty('health', getProperty('health') - healthToDrain)`
