### ISSUE TITLE
Week and ETC breaking after unknown

### ISSUE THREAD

**Issue by chillbananas** [ShadowMario/FNF-PsychEngine#12185]
### Describe your bug here.

I made a character and recompiled the game, next time I tried to go into freeplay I get a crash report, i've had this issue many times when creating multiple characters, and the week just disappears for an unknown reason, I restored and even made another copy and still things did not work.

### Command Prompt/Terminal logs (if existing)

```bash
The crash log is:

FreeplayState.hx (line 74)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by chillbananas** [comment]
(Update)

I pressed W on the week menu and my week popped up for some strange reason, theres some weird secret week without a json blocking it, freeplay still doesn't work tho.

**Comment by DabbinDude316B** [comment]
icon most likely not added

**Comment by chillbananas** [comment]
I deleted the character and json after I made the actual thing, I usually make the json and then put in the icon, it was still BF tho.
