### ISSUE TITLE
how can you make fps higher than 240 like Strident Crisis V1.5 Delirium?

### ISSUE THREAD

**Issue by ROCK201888** [ShadowMario/FNF-PsychEngine#12187]
### What is your question?

how can you make fps higher than 240 like Strident Crisis V1.5 Delirium?
with lua

**Comment by DabbinDude316B** [comment]
impossible in lua

**Comment by MemeHovy** [comment]
use 
```lua
setProperty('framerate') = 300;
```

**Comment by NexIsDumb** [comment]
> try using this
> ```lua
> setProperty('framerate') = 300;
> ```

Would """break""" the actual option though

**Comment by NexIsDumb** [comment]
Just dont, cause if youre gonna set that as default some user may have trouble with their devices

Theres an option for deciding the fps for a reason

**Comment by ROCK201888** [comment]
so close?

**Comment by NexIsDumb** [comment]
> so close?

Well if you really want to change them, the right way is

```lua
function onCreate()
    setPropertyFromClass('FlxG', 'updateFramerate', 300)
    setPropertyFromClass('FlxG', 'drawFramerate', 300)
end
```

I'd suggest you to make it more complete it like this though
```lua
function onCreate()
    if 300 > getPropertyFromClass('FlxG', 'drawFramerate') then
        setPropertyFromClass('FlxG', 'updateFramerate', 300)
        setPropertyFromClass('FlxG', 'drawFramerate', 300)
    else
        setPropertyFromClass('FlxG', 'drawFramerate', 300)
        setPropertyFromClass('FlxG', 'updateFramerate', 300)
    end
end

function onDestroy()	
    if framerate > getPropertyFromClass('FlxG', 'drawFramerate') then
        setPropertyFromClass('FlxG', 'updateFramerate', framerate)
        setPropertyFromClass('FlxG', 'drawFramerate', framerate)
    else
        setPropertyFromClass('FlxG', 'drawFramerate', framerate)
        setPropertyFromClass('FlxG', 'updateFramerate', framerate)
    end
end
```

It basically makes the fps return back to the original value once you close the song / it ends
since I cannot use the computer, tell me if there are some errors

**Comment by NexIsDumb** [comment]
> > 
> 
> the fps go a bit better
> 
> > > so close?
> > 
> > Well if you really want to change them, the right way is (example for 300 fps limit)
> > 
> > ```lua
> > function onCreate()
> >     setPropertyFromClass('FlxG', 'updateFramerate', 300)
> >     setPropertyFromClass('FlxG', 'drawFramerate', 300)
> > end
> > ```
> > 
> > I'd suggest you to make it more complete like this though
> > 
> > ```lua
> > local fps = 300  -- Change this value to change the desired fps limit
> > 
> > function onCreate()
> >     if fps > getPropertyFromClass('FlxG', 'drawFramerate') then
> >         setPropertyFromClass('FlxG', 'updateFramerate', fps)
> >         setPropertyFromClass('FlxG', 'drawFramerate', fps)
> >     else
> >         setPropertyFromClass('FlxG', 'drawFramerate', fps)
> >         setPropertyFromClass('FlxG', 'updateFramerate', fps)
> >     end
> > end
> > 
> > function onDestroy()	
> >     if framerate > getPropertyFromClass('FlxG', 'drawFramerate') then
> >         setPropertyFromClass('FlxG', 'updateFramerate', framerate)
> >         setPropertyFromClass('FlxG', 'drawFramerate', framerate)
> >     else
> >         setPropertyFromClass('FlxG', 'drawFramerate', framerate)
> >         setPropertyFromClass('FlxG', 'updateFramerate', framerate)
> >     end
> > end
> > ```
> > 
> > It basically makes the fps limit return back to the original value once you close the song / it ends (and plus its more dynamic for future updates) since I cannot use the computer, tell me if there are some errors
> 
> fps go better

So it works?

**Comment by ROCK201888** [comment]
> > > 
> > 
> > 
> > the fps go a bit better
> > > > so close?
> > > 
> > > 
> > > Well if you really want to change them, the right way is (example for 300 fps limit)
> > > ```lua
> > > function onCreate()
> > >     setPropertyFromClass('FlxG', 'updateFramerate', 300)
> > >     setPropertyFromClass('FlxG', 'drawFramerate', 300)
> > > end
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I'd suggest you to make it more complete like this though
> > > ```lua
> > > local fps = 300  -- Change this value to change the desired fps limit
> > > 
> > > function onCreate()
> > >     if fps > getPropertyFromClass('FlxG', 'drawFramerate') then
> > >         setPropertyFromClass('FlxG', 'updateFramerate', fps)
> > >         setPropertyFromClass('FlxG', 'drawFramerate', fps)
> > >     else
> > >         setPropertyFromClass('FlxG', 'drawFramerate', fps)
> > >         setPropertyFromClass('FlxG', 'updateFramerate', fps)
> > >     end
> > > end
> > > 
> > > function onDestroy()	
> > >     if framerate > getPropertyFromClass('FlxG', 'drawFramerate') then
> > >         setPropertyFromClass('FlxG', 'updateFramerate', framerate)
> > >         setPropertyFromClass('FlxG', 'drawFramerate', framerate)
> > >     else
> > >         setPropertyFromClass('FlxG', 'drawFramerate', framerate)
> > >         setPropertyFromClass('FlxG', 'updateFramerate', framerate)
> > >     end
> > > end
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > It basically makes the fps limit return back to the original value once you close the song / it ends (and plus its more dynamic for future updates) since I cannot use the computer, tell me if there are some errors
> > 
> > 
> > fps go better
> 
> So it works? If you want to increase the fps limit even more, just change the value `300` to the number you want

ok
