### ISSUE TITLE
Changing Health Bar Colors Through Lua Scripting

### ISSUE THREAD

**Issue by AyMarte** [ShadowMario/FNF-PsychEngine#12189]
### What is your question?

Is there any possible way, with lua, that I can change both of the characters health bar colors, and might even icons?

**Comment by Meme1079** [comment]
Use `setHealthBarColors()` function.

Example:
```lua
function onCreatePost()
    -- first parameter is for the opponent healthbar and second is for the player healthbar
    setHealthBarColors('32a852', 'cb07ed'))
end
```

**Comment by AyMarte** [comment]
> Use `setHealthBarColors()` function.
> 
> Example:
> 
> ```lua
> function onCreatePost()
>     -- first parameter is for the opponent healthbar and second is for the player healthbar
>     setHealthBarColors('32a852', 'cb07ed'))
> end
> ```

Thank you, this worked perfectly!

**Comment by ArchonDemon** [comment]
you can change the icons with:

loadGraphic('iconP2','icons/icon-dad',150)
addAnimation('iconP2', 'idle', {0,1}, 0, true)

if you want to change bf's icon just replace iconP2 with iconP1

**Comment by YamiDarkness64** [comment]
> Use `setHealthBarColors()` function.
> 
> Example:
> 
> ```lua
> function onCreatePost()
>     -- first parameter is for the opponent healthbar and second is for the player healthbar
>     setHealthBarColors('32a852', 'cb07ed'))
> end
> ```

How do you use it with getProperty?
Like if I want to get BF's healthbar color value

**Comment by Meme1079** [comment]
> > Use `setHealthBarColors()` function.
> > Example:
> > ```lua
> > function onCreatePost()
> >     -- first parameter is for the opponent healthbar and second is for the player healthbar
> >     setHealthBarColors('32a852', 'cb07ed'))
> > end
> > ```
> 
> How do you use it with getProperty? Like if I want to get BF's healthbar color value

Here:
```lua
function onCreatePost()
     local bfIconColor = getProperty('boyfriend.healthColorArray')
     debugPrint(string.format('%02x%02x%02x', bfIconColor[1], bfIconColor[2], bfIconColor[3]))
end
```

**Comment by YamiDarkness64** [comment]
Woah thanks a lot
