### ISSUE TITLE
Improve antialiasing setting.

### ISSUE THREAD

**Issue by TheGaloXx** [ShadowMario/FNF-PsychEngine#12197]
### What feature do you want to get added on the **base** engine?

I think it’s better to use FlxSprite.defaultAntialiasing instead of setting the antialiasing acording to the player preferences on every sprite.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by KookerFoxYT** [comment]
well i may have agreed
although your attempt at the test is unsuccessful

**Comment by TheGaloXx** [comment]
> 

Sorry, what does that mean?

**Comment by ShadowMario** [comment]
`defaultAntialiasing` was only implemented long after i created the antialiasing setting.
![image](https://user-images.githubusercontent.com/44785097/230824945-264a6e7c-9970-4649-aef4-fa51014ec7f6.png)
