### ISSUE TITLE
Help for creating custom option substates!

### ISSUE THREAD

**Issue by AyMarte** [ShadowMario/FNF-PsychEngine#12195]
### Describe your bug here.

Does anyone know a clear way on how to fix this issue, I'm trying to make an April Fools Engine:
I'm trying to make a custom options sub state

### Command Prompt/Terminal logs (if existing)

```bash
source/options/OptionsState.hx:50: characters 22-51 : Type name options.GameplaySettingsSubState is redefined from module options.GameplaySettingsSubState
source/options/OptionsState.hx:50: characters 22-51 : ... For function argument 'SubState'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I replaced the Adjust Delay And Combo sub state with a custom subState: April Fools Consecutives, options.FoolsSettingsSubState

**Comment by DabbinDude316B** [comment]
i think you messed up ur coode in the substate

**Comment by NexIsDumb** [comment]
> i think you messed up ur coode in the substate

Yep

To understand the issue we need the actual code of the option you want to add

**Comment by AyMarte** [comment]
Eh, nevermind, I got a different solution.
