### ISSUE TITLE
Cannot copy to "export/release/windows/bin/PsychEngine.exe", is the file in use?

### ISSUE THREAD

**Issue by official-ys** [ShadowMario/FNF-PsychEngine#12194]
### Describe your bug here.

i keep getting this 
![image](https://user-images.githubusercontent.com/68799161/229310465-c997e252-d250-4c48-8c3b-b3cb1652f3de.png)

and its very annoying

because i don't have psych engine open and i do not know what is causing the problem
i tried compile like 50 times and i keep getting it help

I am using psych .5.2h

### Command Prompt/Terminal logs (if existing)

```bash
Error: Cannot copy to "export/release/windows/bin/PsychEngine.exe", is the file in use?
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes , a coder in my team edited playstate, funkinlua, and made a new state called boss rushstate, but i dont think this affected it because he added these a very long time ago and i was always able to compile with these edited hx files, this error has only been happening to me today

**Comment by DisIsNOt** [comment]
Burh close any file you're using on that path and compile it again

**Comment by official-ys** [comment]
> Burh close any file you're using on that path and compile it again

ok i will try gimme 1 sec

**Comment by official-ys** [comment]
i close every file on that path and its still giving me the error help

**Comment by official-ys** [comment]
ok someone on fnfmc discord helped me ( for anyone checking this thread with the same issue, the solution was to save your mod folder somewhere, like a zip file on google drive, then delete the export folder, then compile again, and it should be fixed)

**Comment by DisIsNOt** [comment]
Nice
