### ISSUE TITLE
cutscene + dialogue script not working

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#12193]
### Describe your bug here.

I was porting a mod from 0.6.1 to 0.6.2 (to another platform) but when I go into the song, the video and dialogue start normally. Except, the song also starts

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I literally didn't

**Comment by BernardoGP4504** [comment]
Also here's the script if it helps:
```lua
-- Dialogue shit
local playDialogue = false;
local playedVideo = false;
function onStartCountdown()
	if not playedVideo and isStoryMode and not seenCutscene then -- Block the first countdown and play video cutscene
		startVideo('norway');
		playDialogue = true;
		playedVideo = true;
		return Function_Stop;
	elseif playDialogue then -- Block the second countdown and start a timer of 0.8 seconds to play the dialogue
		playedVideo = true;
		playDialogue = false;
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);

		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('dialogue');
	end
end
```

**Comment by DabbinDude316B** [comment]
```lua
local playedVideo = false;
function onStartCountdown()
	if not playedVideo and isStoryMode and not seenCutscene then -- Block the first countdown and play video cutscene
		startVideo('norway');
		playedVideo = true;
		return Function_Stop;
	end
        if playedVideo then -- Block the second countdown and start a timer of 0.8 seconds to play the dialogue
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);

		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('dialogue');
	end
end
```
i haven't coded in a while- lua in forever, so here is what i got

**Comment by BernardoGP4504** [comment]
> ```lua
> local playedVideo = false;
> function onStartCountdown()
> 	if not playedVideo and isStoryMode and not seenCutscene then -- Block the first countdown and play video cutscene
> 		startVideo('norway');
> 		playedVideo = true;
> 		return Function_Stop;
> 	end
>         if playedVideo then -- Block the second countdown and start a timer of 0.8 seconds to play the dialogue
> 		setProperty('inCutscene', true);
> 		runTimer('startDialogue', 0.8);
> 
> 		return Function_Stop;
> 	end
> 	return Function_Continue;
> end
> 
> function onTimerCompleted(tag, loops, loopsLeft)
> 	if tag == 'startDialogue' then -- Timer completed, play dialogue
> 		startDialogue('dialogue');
> 	end
> end
> ```
> 
> i haven't coded in a while- lua in forever, so here is what i got

It still has the same problem but the dialogue plays forever

**Comment by BernardoGP4504** [comment]
I've figured out the Psych Engine build I'm using does not stop the countdown at cutscene scripts like that for some reason
