### ISSUE TITLE
WERE IS PHYCH ENGINE 1.0.0

### ISSUE THREAD

**Issue by lazyremixmanordummyplayinggmod** [ShadowMario/FNF-PsychEngine#12191]
### Describe your problem here.

were is it it has the new hscript suport download plz

**Comment by lazyremixmanordummyplayinggmod** [comment]
i thought it released today

**Comment by KookerFoxYT** [comment]
kid named 0.6.3:

**Comment by lazyremixmanordummyplayinggmod** [comment]
sorry this was aprill fools joke bye
