### ISSUE TITLE
How do I add one more character as an enemy?

### ISSUE THREAD

**Issue by AphelDD** [ShadowMario/FNF-PsychEngine#1219]
### Describe your problem here.

I want to add one more enemy like the Shaggy x Matt mod, but I don't know how to do it, could someone help me?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't edit anything

**Comment by ShadowMario** [comment]
This is not something simple to do, but you have to copy the variable `var dad:Character`, rename it to whatever you'd like to call it, then copy ALL of the note logic from dad for your new variable.
