### ISSUE TITLE
Mechanics notes

### ISSUE THREAD

**Issue by AlonerPhonk** [ShadowMario/FNF-PsychEngine#12209]
### Describe your problem here.

How to make a note with a condition?
Example: If a player's health is greater than 0.3 when pressed, they were dealt 0.3 damage. But if the player had less than or equal to 0.3 health when pressed, only 0.1 health was taken away from him. I ask for help.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by DragonTrance** [comment]
On the bottom of [this page](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API) are some scripting examples. Or, if you don't wanna check that out, add a file to `YourMod/custom_notetypes`, with the .lua extension. The name in the chart editor will be the same as the file name for the lua script you add.

Inside the lua script, you can use `function goodNoteHit(id, direction, noteType, isSustainNote)', where the ID should be the file name (without the extension). You can find some more documentation in that hyperlink above.

If you feel lazy, [here's some code](https://pastebin.com/ryCVf4YM)

**Comment by AlonerPhonk** [comment]
@DragonTrance 
And what should I do if I want to do it through the source code? For example, if I publish a mod on any sites, I don’t want every second player to be able to change the damage from the arrows and go through the mod without problems.
