### ISSUE TITLE
Hscript help

### ISSUE THREAD

**Issue by hotpocketsarepoggers** [ShadowMario/FNF-PsychEngine#12200]
### Describe your problem here.

I'm trying to add this line of code into a lua script but it never works. How do I fix it?
```
addHaxeLibrary('FlxMath', 'flixel.math')
runHaxeCode([[
     if (curBeat % 4 == 2 && game.SONG.notes[Math.floor(curStep / 16)].mustHitSection && game.dad.animation.curAnim.name == 'idle')
		game.dad.playAnim('idle');
]])
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by DragonTrance** [comment]
Messing with the haxe code directly imo is very finnicky, use lua instead to do what you wanna do. If you know how to code in haxe, it doesn't hurt to spend some time reading [PlayState.hx](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/PlayState.hx) or [FunkinLua.hx](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/FunkinLua.hx) if what you're trying to do can't be coded with lua.

I haven't used addHaxeLibrary before so take this with a grain of salt, but you could also try replacing "Math" with "FlxMath" instead. All of what you're doing here can also be used with lua, you can [look around in the documentation](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API) to try and make what you have in that code.
