### ISSUE TITLE
how to divide levels into sections like indie cross and w.i

### ISSUE THREAD

**Issue by Robert124l** [ShadowMario/FNF-PsychEngine#12204]
### Describe your problem here.

I would like to know how to divide the levels into sections such as story mode, bonus song like indie cross or w.i. and no, I'm not going to copy their code, I don't do that.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by DragonTrance** [comment]
I'm not entirely sure what indie cross does for levels, but [here's an example file I made a few days ago](https://pastebin.com/zDSDdikt) messing with shit and d-sides cycles.

**Comment by DragonTrance** [comment]
To divide songs into different weeks, you have to create a new week manifest for each "section" you want to add.
Here's an [example file](https://pastebin.com/1sx2cLWM) for adding a week.

When viewing songs in freeplay, they are ordered by the week sequence (as defined in the json as `"weekNext"` and `"weekBefore"`, and then those songs in a single week are displayed in the same order as defined in the `"songs"` part of the json.

**Comment by Robert124l** [comment]
> To divide songs into different weeks, you have to create a new week manifest for each "section" you want to add. Here's an [example file](https://pastebin.com/1sx2cLWM) for adding a week.
> 
> When viewing songs in freeplay, they are ordered by the week sequence (as defined in the json as `"weekNext"` and `"weekBefore"`, and then those songs in a single week are displayed in the same order as defined in the `"songs"` part of the json.
> 
> If you want to add "bonus," freeplay-only songs, the whole week file has to define `"hideStoryMode"` and set its value to `true` to stop that week from showing up in story mode.

Seriously sorry for the delay but thank you very much, I'm going to try it
