### ISSUE TITLE
No Pause Music / Exit Crash

### ISSUE THREAD

**Issue by MrDudeTheTurtle** [ShadowMario/FNF-PsychEngine#12208]
### Describe your bug here.

After messing around with a modified version of psych engine trying to program something in the pause menu, I noticed there was no pause music, and it was sometimes crashing when I tried exiting the song. I at first thought it was a bug in my modified version, but I downloaded the latest version of Psych, and sure enough, no pause music.

I did some testing and found that if I paused upon starting a song (during countdown, not sure if it crashed otherwise), waited a bit after turning the volume up and down and trying to exit, it crashed. I did it a couple more times, and as I was going to try and record it, it stopped crashing for some reason. I'm not sure why it stopped crashing, but it still doesn't have any music, so hopefully this is somewhat helpful?

Luckily, I did still have one crash log from when it _was_ crashing, so that could be of some use. Anyway, I hope this report is helpful, if not, my apologies, hope it gets fixed.

### Command Prompt/Terminal logs (if existing)

```bash
flixel/system/FlxSound.hx (line 589)
flixel/system/FlxSound.hx (line 727)
flixel/system/FlxSoundGroup.hx (line 52)
flixel/system/frontEnds/SoundFrontEnd.hx (line 314)
flixel/system/frontEnds/SoundFrontEnd.hx (line 306)
flixel/FlxGame.hx (line 613)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No edits, built 0.6.3 straight from download.

**Comment by glowsoony** [comment]
This has happened to me many times as well, to fix it I made it not let you pause unless the song actually started.
