### ISSUE TITLE
#if LUA_ALLOWED is messing up the compiling.

### ISSUE THREAD

**Issue by ShatteredEcHOs** [ShadowMario/FNF-PsychEngine#12205]
### Describe your bug here.

I try to compile the ourple source code, but the #if LUA_ALLOWED on line 1207 of the playstate is messing up things as its seen as a blockage. The reason I can't just delete it is because its the thing that makes lua scripts run in data folders. Anyone have a fix for this? I've tried putting it in different areas on the script but it is always seen as a blockage.

### Command Prompt/Terminal logs (if existing)

```bash
source/PlayState.hx:1207: characters 3-6 : Unclosed conditional compilation block

C:\Users\(my name)\Downloads\Ourple_Source\Ourple Source>
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

It's the ourple guy source code, so it would be edited yes, but theres no other issues with compiling except this one. (I've compiled it after deleting the line but lua scripts didn't work after words)

**Comment by CaptainBaldi** [comment]
if it's from another mod, don't make a bug report here about it

**Comment by ShatteredEcHOs** [comment]
valid
