### ISSUE TITLE
How to make some notes have different keybinds?

### ISSUE THREAD

**Issue by NicklGames** [ShadowMario/FNF-PsychEngine#1220]
### Describe your problem here.

Like, for example: default notes keybinds are dfjk, while HURT notes smth different

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

**Comment by NicklGames** [comment]
OR how to make some notes use different keybinds?

**Comment by ShadowMario** [comment]
You'd have to redo note logic, i can't help you with that.
