### ISSUE TITLE
Uhh..

### ISSUE THREAD

**Issue by Lsoissus** [ShadowMario/FNF-PsychEngine#12210]
### Describe your bug here.

So, im trying to load my song, it works in chart editor but doesnt work in normal game, Any help?
![Screenshot 2023-04-04 152839](https://user-images.githubusercontent.com/96982235/229734257-2301a452-985d-4940-b5e2-a646116dda47.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No probably, i only changed the title.

**Comment by NotStampyC** [comment]
I have the same problem and crash log. It was working fine and then it breaks when it has worked for ages

**Comment by NotStampyC** [comment]
Did you remove the week 2 to 7 folders. If you did, put them back cos they are hard coded and can break songs that are made in that engine.

**Comment by Lsoissus** [comment]
Never mind, the problem was cause the opponent was invisible
