### ISSUE TITLE
the engine doesnt want to compile anymore and i dont know why

### ISSUE THREAD

**Issue by Geniusbutfnf** [ShadowMario/FNF-PsychEngine#12214]
### Describe your bug here.

so i was gonna compile psych engine but now its giving me a weird message and i dont know how to fix it

### Command Prompt/Terminal logs (if existing)

```bash
source/Main.hx:72: characters 61-65 : Float should be Int
source/Main.hx:72: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:72: characters 61-65 : ... For function argument 'child'
source/MenuCharacter.hx:90: lines 90-91 : Warning : This case is unused
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Stefan2008Git** [comment]
Flixel 5.0.1 is released
