### ISSUE TITLE
Load Week Function

### ISSUE THREAD

**Issue by AyMarte** [ShadowMario/FNF-PsychEngine#12215]
### What feature do you want to get added on the **base** engine?

Could there be a new lua function that loads a week depending on which the values of the function are. Ex:
```
loadWeek('tutorial', 0, true) --This would load the tutorial week with the difficulty Id of 0, or easy mode, and last value would determine if the week that is loaded if the player completes the week is unlocked and visible in freeplay and story mode, depending on the json file for that specific week.
```
I honestly thought this could've been a need for modding for this engine.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CaptainBaldi** [comment]
not hard to make in hscript, do it yourself

**Comment by DragonTrance** [comment]
Something like that in a lua function would be kinda hard, since everything is just knitted together. Editing the source code for it would be more reliable.

Nonetheless, I don't have much to offer in terms of help for this specific problem, but if you want to explore a bit with this gimmick then here's a few things you can read. Anything that isn't [the lua documentation](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API) is just reading the base code.
[FreeplayState](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/FreeplayState.hx)
[StoryMenuState](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/StoryMenuState.hx)
[PlayState](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/PlayState.hx)

**Comment by CaptainBaldi** [comment]
> Something like that in a lua function would be kinda hard, since everything is just knitted together. Editing the source code for it would be more reliable.
> 
> Nonetheless, there isn't much to offer in terms of help for this specific problem, but if you want to explore a bit with this gimmick then here's a few things you can read. Anything that isn't [the lua documentation](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API) is just reading the base code.
> 
> [PlayState](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/PlayState.hx) [FreeplayState](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/FreeplayState.hx#L338) [StoryMenuState](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/StoryMenuState.hx)
> 
> Misc: [Song](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Song.hx) [StageData](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/StageData.hx)

```
runHaxeCode([[
	PlayState.storyPlaylist = ['song1', 'song2', 'etc'];
        PlayState.isStoryMode = true;
				
        PlayState.storyDifficulty = ]]..difficulty..[[;

	PlayState.SONG = Song.loadFromJson(PlayState.storyPlaylist[0].toLowerCase() + CoolUtil.getDifficultyFilePath(PlayState.storyDifficulty), PlayState.storyPlaylist[0].toLowerCase());
	PlayState.campaignScore = 0;
	PlayState.campaignMisses = 0;
				
	LoadingState.loadAndSwitchState(new PlayState(), true);
]])
```
Nothing is 'unreliable' about doing this in Lua. 
It's literally not hard to do, and it works fine.
Literally it took me a couple minutes to put this together.
Import the required libraries using `addHaxeLibrary` and boom

**Comment by Sonicfan2474** [comment]
I'm not that familiar with hScript, so what required libraries would need to be added and how?

**Comment by MaksPRO12667** [comment]
> > Something like that in a lua function would be kinda hard, since everything is just knitted together. Editing the source code for it would be more reliable.
> > Nonetheless, there isn't much to offer in terms of help for this specific problem, but if you want to explore a bit with this gimmick then here's a few things you can read. Anything that isn't [the lua documentation](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API) is just reading the base code.
> > [PlayState](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/PlayState.hx) [FreeplayState](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/FreeplayState.hx#L338) [StoryMenuState](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/StoryMenuState.hx)
> > Misc: [Song](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/Song.hx) [StageData](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/StageData.hx)
> 
> ```
> runHaxeCode([[
> 	PlayState.storyPlaylist = ['song1', 'song2', 'etc'];
>         PlayState.isStoryMode = true;
> 				
>         PlayState.storyDifficulty = ]]..difficulty..[[;
> 
> 	PlayState.SONG = Song.loadFromJson(PlayState.storyPlaylist[0].toLowerCase() + CoolUtil.getDifficultyFilePath(PlayState.storyDifficulty), PlayState.storyPlaylist[0].toLowerCase());
> 	PlayState.campaignScore = 0;
> 	PlayState.campaignMisses = 0;
> 				
> 	LoadingState.loadAndSwitchState(new PlayState(), true);
> ]])
> ```
> 
> Nothing is 'unreliable' about doing this in Lua. It's literally not hard to do, and it works fine. Literally it took me a couple minutes to put this together. Import the required libraries using `addHaxeLibrary` and boom

ERROR ON LOADING (PATH): SScript:NUM: Unknown variable: CoolUtil

I have this error
