### ISSUE TITLE
how to add custom note skin  lua

### ISSUE THREAD

**Issue by Gurudevsing** [ShadowMario/FNF-PsychEngine#12213]
### Describe your problem here.

![Screenshot 2023-04-05 002901](https://user-images.githubusercontent.com/87480185/229893812-c5e80ddb-8b1b-4178-bd7d-adfb4d125673.png)
hello this code from #5785  i did wrong tho
1, my  question is how to change skin of notes and arrows through lua

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by DisIsNOt** [comment]
Kid named that's not a in-game function go define it in function onCreate or something

**Comment by NexIsDumb** [comment]
Well, cause that code you just copied is an event not a script that works always
You need put that script inside the `custom_events` folder and then add a text file that describes the event and uts values

if you want to change the arrows you can do that directly in the chart editor, if you want to change only opponent ones though you can do this

```lua
local arrText = 'skins/notes/NOTE_assets'   -- Change this string to change the arrows location

function onCreatePost()
    if arrText ~= nil then
        for i = 0, getProperty('opponentStrums.length') - 1 do
            setPropertyFromGroup('opponentStrums', i, 'texture', arrText)
        end
        for i = 0, getProperty('unspawnNotes.length') - 1 do
            if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
                setPropertyFromGroup('unspawnNotes', i, 'texture', arrText)
            end
        end
    end
end
```

The string of the local variable `arrText` is an example of how you should write your arrows png and xml location (so ofc it wont work if youre just gonna leave it like that). If you want the default ones just rewrite that string (between the '') as NOTE_assets

**Comment by AyMarte** [comment]
local arrText = 'skins/notes/NOTE_assets'   -- Change this string to change the arrows location

>```
>function onCreatePost()
>    if arrText ~= nil then
>        for i = 0, getProperty('opponentStrums.length') - 1 do --copy from this line
>            setPropertyFromGroup('opponentStrums', i, 'texture', arrText)
>        end
>        for i = 0, getProperty('unspawnNotes.length') - 1 do
>            if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
>                setPropertyFromGroup('unspawnNotes', i, 'texture', arrText)
>            end
>        end -- to this line
>    end
>end
>```

The code with the comments with the `--` prefix should state which to copy, this makes every note that texture.

**Comment by AyMarte** [comment]
The `nil` part could be necessary, but it really isn't needed, and plus it makes the file smaller.

**Comment by Gurudevsing** [comment]
> Well, cause that code you just copied is an event not a script that always work You need put that script inside the `custom_events` folder and then add a text file that describes the event and its values
> 
> Otherwhise there are also other methods: If you want to change the arrows you can do that directly in the chart editor, if you want to change only opponent ones though you can do this
> 
> ```lua
> local arrText = 'skins/notes/NOTE_assets'   -- Change this string to change the arrows location
> 
> function onCreatePost()
>     if arrText ~= nil then
>         for i = 0, getProperty('opponentStrums.length') - 1 do
>             setPropertyFromGroup('opponentStrums', i, 'texture', arrText)
>         end
>         for i = 0, getProperty('unspawnNotes.length') - 1 do
>             if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
>                 setPropertyFromGroup('unspawnNotes', i, 'texture', arrText)
>             end
>         end
>     end
> end
> ```
> 
> The string of the local variable `arrText` is an example of how you should write your arrows png and xml location (so ofc it wont work if youre just gonna leave it like that). If you want the default ones just rewrite that string (between the '') as NOTE_assets

I want to change both opponent and player skin ,my question is if I  put this code on stage folder will it work and I want to change upper arrow skin too ....

**Comment by Gurudevsing** [comment]
I'll try

**Comment by NexIsDumb** [comment]
> > Well, cause that code you just copied is an event not a script that always work You need put that script inside the `custom_events` folder and then add a text file that describes the event and its values
> > 
> > Otherwhise there are also other methods: If you want to change the arrows you can do that directly in the chart editor, if you want to change only opponent ones though you can do this
> > 
> > ```lua
> > local arrText = 'skins/notes/NOTE_assets'   -- Change this string to change the arrows location
> > 
> > function onCreatePost()
> >     if arrText ~= nil then
> >         for i = 0, getProperty('opponentStrums.length') - 1 do
> >             setPropertyFromGroup('opponentStrums', i, 'texture', arrText)
> >         end
> >         for i = 0, getProperty('unspawnNotes.length') - 1 do
> >             if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
> >                 setPropertyFromGroup('unspawnNotes', i, 'texture', arrText)
> >             end
> >         end
> >     end
> > end
> > ```
> > 
> > The string of the local variable `arrText` is an example of how you should write your arrows png and xml location (so ofc it wont work if youre just gonna leave it like that). If you want the default ones just rewrite that string (between the '') as NOTE_assets
> 
> I want to change both opponent and player skin ,my question is if I  put this code on stage folder will it work and I want to change upper arrow skin too ....

well for that theres the feature in the chart editor, just press 7 when you're in a song (after the countdown) and once the chart editor loaded go to the song tab and look on bottom of the tab, theres the splash skins line and the arrows one: putting there the path of your png and xml will load them and change the arrows, this will change both opponents and player arrows

**Comment by NexIsDumb** [comment]
> >```
> >local arrText = 'skins/notes/NOTE_assets'   -- Change this string to change the arrows location
> >
> >
> >function onCreatePost()
> >    if arrText ~= nil then
> >        for i = 0, getProperty('opponentStrums.length') - 1 do --copy from this line
> >            setPropertyFromGroup('opponentStrums', i, 'texture', arrText)
> >        end
> >        for i = 0, getProperty('unspawnNotes.length') - 1 do
> >            if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
> >                setPropertyFromGroup('unspawnNotes', i, 'texture', arrText)
> >            end
> >        end -- to this line
> >    end
> >end
> >```
> 
> The code with the comments with the `--` prefix should state which to copy, this makes every note that texture.

> The `nil` part could be necessary, but it really isn't needed, and plus it makes the file smaller. 

bro wtf are you saying
how can the `nil` part make the file smaller💀
its just check that wont load the arrows if the string is null, cause ofc it's gonna give an error if the texture of the arrows its null

**Comment by Gurudevsing** [comment]
> > > Well, cause that code you just copied is an event not a script that always work You need put that script inside the `custom_events` folder and then add a text file that describes the event and its values
> > > Otherwhise there are also other methods: If you want to change the arrows you can do that directly in the chart editor, if you want to change only opponent ones though you can do this
> > > ```lua
> > > local arrText = 'skins/notes/NOTE_assets'   -- Change this string to change the arrows location
> > > 
> > > function onCreatePost()
> > >     if arrText ~= nil then
> > >         for i = 0, getProperty('opponentStrums.length') - 1 do
> > >             setPropertyFromGroup('opponentStrums', i, 'texture', arrText)
> > >         end
> > >         for i = 0, getProperty('unspawnNotes.length') - 1 do
> > >             if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
> > >                 setPropertyFromGroup('unspawnNotes', i, 'texture', arrText)
> > >             end
> > >         end
> > >     end
> > > end
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The string of the local variable `arrText` is an example of how you should write your arrows png and xml location (so ofc it wont work if youre just gonna leave it like that). If you want the default ones just rewrite that string (between the '') as NOTE_assets
> > 
> > 
> > I want to change both opponent and player skin ,my question is if I  put this code on stage folder will it work and I want to change upper arrow skin too ....
> 
> well for that theres the feature in the chart editor, just press 7 when you're in a song (after the countdown) and once the chart editor loaded go to the song tab and look on bottom of the tab, theres the splash skins line and the arrows one: putting there the path of your png and xml will load them and change the arrows, this will change both opponents and player arrows
> 
> But btw, yeah you can put that code I did in the stage too If the onCreatePost is already in the stage script just copy the `local arrText = [...]` part from `arrText ~= nil` to the second-last `end` but warning it will only change the opponent ones, if you want to change also the player notes just ask me

above code works fine bro
yes  i want to change both opponent and player skin

**Comment by NexIsDumb** [comment]
> > > > Well, cause that code you just copied is an event not a script that always work You need put that script inside the `custom_events` folder and then add a text file that describes the event and its values
> > > > Otherwhise there are also other methods: If you want to change the arrows you can do that directly in the chart editor, if you want to change only opponent ones though you can do this
> > > > ```lua
> > > > local arrText = 'skins/notes/NOTE_assets'   -- Change this string to change the arrows location
> > > > 
> > > > function onCreatePost()
> > > >     if arrText ~= nil then
> > > >         for i = 0, getProperty('opponentStrums.length') - 1 do
> > > >             setPropertyFromGroup('opponentStrums', i, 'texture', arrText)
> > > >         end
> > > >         for i = 0, getProperty('unspawnNotes.length') - 1 do
> > > >             if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
> > > >                 setPropertyFromGroup('unspawnNotes', i, 'texture', arrText)
> > > >             end
> > > >         end
> > > >     end
> > > > end
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > The string of the local variable `arrText` is an example of how you should write your arrows png and xml location (so ofc it wont work if youre just gonna leave it like that). If you want the default ones just rewrite that string (between the '') as NOTE_assets
> > > 
> > > 
> > > I want to change both opponent and player skin ,my question is if I  put this code on stage folder will it work and I want to change upper arrow skin too ....
> > 
> > 
> > well for that theres the feature in the chart editor, just press 7 when you're in a song (after the countdown) and once the chart editor loaded go to the song tab and look on bottom of the tab, theres the splash skins line and the arrows one: putting there the path of your png and xml will load them and change the arrows, this will change both opponents and player arrows
> > But btw, yeah you can put that code I did in the stage too If the onCreatePost is already in the stage script just copy the `local arrText = [...]` part from `arrText ~= nil` to the second-last `end` but warning it will only change the opponent ones, if you want to change also the player notes just ask me
> 
> above code works fine bro yes i want to change both opponent and player skin

Alright then the entire code is: 

```lua
local arrText = 'skins/notes/NOTE_assets'   -- Change this string to change the arrows location

function onCreatePost()
    if arrText ~= nil then
        for i = 0, getProperty('strumLineNotes.length') - 1 do
            setPropertyFromGroup('strumLineNotes', i, 'texture', arrText)
        end
        for i = 0, getProperty('unspawnNotes.length') - 1 do
            if getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' then
                setPropertyFromGroup('unspawnNotes', i, 'texture', arrText)
            end
        end
    end
end
```

Like this it will only change the texture of every note aside the special ones, and it will do on both sides (opponent and player)
But remember that you can also do this in the chart editor, saving that on the song Json

Hope this helped ye

**Comment by Gurudevsing** [comment]
> 

cool it really helps for my mode
