### ISSUE TITLE
Please help me.

### ISSUE THREAD

**Issue by Player181** [ShadowMario/FNF-PsychEngine#12217]
### Describe your problem here.

![error](https://user-images.githubusercontent.com/129997753/230201326-b023222d-c517-4898-ad92-683568b1821f.png)
I tried to create stage.I want to load my stage and then i've go this error. Can someone help me? 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by AyMarte** [comment]
This happens with me, it usually happens if something like if you mess with the `'scoreTxt'` on `onCreatePost()`, script errors continuingly, fatal errors, and more which I haven't encountered yet.

**Comment by frantastic24** [comment]
dadbattle spotlight only works in week 1 stage

**Comment by AyMarte** [comment]
yes true

**Comment by AyMarte** [comment]
I checked at the image closer and it says that it was caused by a `_null object reference_`. So maybe check your values, maybe by using `debugPrint(yourVariable)` to see which value is causing it.

**Comment by AyMarte** [comment]
I could try to get the creator of the engine in here. But he is busy right now.

**Comment by Player181** [comment]
> dadbattle spotlight only works in week 1 stage
Thank you so much.

**Comment by DragonTrance** [comment]
There could be a few problems with this, but there are also a few pull requests open addressing this issue which haven't been pulled yet.
#11965 #12029 #11811
