### ISSUE TITLE
how to delete the black lines on the side?

### ISSUE THREAD

**Issue by ROCK201888** [ShadowMario/FNF-PsychEngine#12216]
### What is your question?

how to delete the black lines on the side?
with lua
![image](https://user-images.githubusercontent.com/113576910/230113998-0cf0af66-a108-4437-b8df-aec982314f9f.png)

**Comment by DEMOLITIONDON96** [comment]
Not possible with Lua, window ratio issue

**Comment by AyMarte** [comment]
Yeah, you would need source in order to change the game's window area size.

**Comment by ROCK201888** [comment]
> Yeah, you would need source in order to change the game's window area size.

so close as not planned?

**Comment by AyMarte** [comment]
> > Yeah, you would need source in order to change the game's window area size.
> 
> so close as not planned?

Most likely. Unless you can do source code

**Comment by DEMOLITIONDON96** [comment]
> > > Yeah, you would need source in order to change the game's window area size.
> > 
> > 
> > so close as not planned?
> 
> Most likely. Unless you can do source code

you have to mostly edit the window size values in both Project.xml and Main.hx in order to update the window size, if you don’t do both, then your game is likely gonna be wonky with all the placement of the sprites and all

**Comment by TheKitBoi** [comment]
> ### What is your question?
> how to delete the black lines on the side? with lua

use this in mods/scripts
[widescreenSupport.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/11178842/widescreenSupport.txt) rename txt to lua
(credit Raltyro)

**Comment by ROCK201888** [comment]
> 

WOW THANKS
