### ISSUE TITLE
What is the different between MusicBeatState & LoadingState (use for switch menu)

### ISSUE THREAD

**Issue by RandomUserOnInternet** [ShadowMario/FNF-PsychEngine#12223]
### What is your question?

I'm curious what's the different of it (sorry if it duplicated)

**Comment by AyMarte** [comment]
If I am correct, the `MusicBeatState` should be a state when a beat is hit, and the `LoadingState` is a state during the loading screens, like on kbhgames.com versions of FNF.

**Comment by RandomUserOnInternet** [comment]
> If I am correct, the `MusicBeatState` should be a state when a song beat is hit, and the `LoadingState` is a state during the loading screens, like on kbhgames.com versions of FNF.

Cool! Thank You so much! I understand now :D
