### ISSUE TITLE
How would I set a StrumNote's X and Y Position?

### ISSUE THREAD

**Issue by somefnfplayerlol** [ShadowMario/FNF-PsychEngine#1222]
### What is your question?

The title explains it.

**Comment by NS-Unfair** [comment]
In lua, it is impossible to move just the strum note as the notes will move with the strum note, but you can use noteTweenX and noteTweenY to set its X and Y. Just set the duration to 0.0001

If you want to do this in haxe, ping me

**Comment by ShadowMario** [comment]
> In lua, it is impossible to move just the strum note currently as the notes will move with the strum note, but you can use noteTweenX and noteTweenY to set its X and Y. Just set the duration to 0.0001

False.
You can disable a note's copyX and copyY if you want to do your own logic for it, or set "offsetX" or "offsetY" if you just want to displace it slightly.
