### ISSUE TITLE
Global Function Support

### ISSUE THREAD

**Issue by Lorekeeper49** [ShadowMario/FNF-PsychEngine#12220]
### What feature do you want to get added on the **base** engine?

for reference, here's how you declare global functions:
```lua
globalFunction = function(params)
    --code
end
```
declaring the functions work but not calling them from another script, so I'd like support for that so we can call functions with song scripts or event scripts, please.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
[already exists](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/FunkinLua.hx#L494)

**Comment by KookerFoxYT** [comment]
> 



> ### What feature do you want to get added on the **base** engine?
> for reference, here's how you declare global functions:
> 
> ```lua
> globalFunction = function(params)
>     --code
> end
> ```
> 
> declaring the functions work but not calling them from another script, so I'd like support for that so we can call functions with song scripts or event scripts, please.

theres already a function that calls a function from another script, which being ``callScript() ``

**Comment by Lorekeeper49** [comment]
> > 
> 
> 
> 
> > ### What feature do you want to get added on the **base** engine?
> > for reference, here's how you declare global functions:
> > 
> > ```lua
> > globalFunction = function(params)
> >     --code
> > end
> > ```
> > 
> > declaring the functions work but not calling them from another script, so I'd like support for that so we can call functions with song scripts or event scripts, please.
> 
> theres already a function that calls a function from another script, which being ``callScript() ``
> 
> 

I didn't see that on the wiki I use, thanks for letting me know
