### ISSUE TITLE
setProperty('animatedsprite.color') turning no white

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#12221]
### Describe your bug here.

While working on a script, I randomly saw, that using setProperty for the color of an (animated) sprite to "FFFFFF" turns it black. however, when using doTweenColor() it works perfectly well.
(but also in general, if there is any "F" at any point. it might turn always to black (found out first, when wanting to use "FF0000")

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not via source

**Comment by frantastic24** [comment]
`setProperty('sprite.color', 0xFFFFFF)` works, it probably doesn't like stringsthis wouldn't be a psych bug anyway because this is handled by flixel

**Comment by DragonTrance** [comment]
First you have to get the color using the haxe engine, which thankfully there is a lua function for it: `getColorFromHex("FFFFFF")`

Example usage to make BF red and semi-transparent: `setProperty("boyfriendGroup.color", getColorFromHex("0x8FFF0000"))`

**Comment by ZeitHeld** [comment]
though it does work, when using `setProperty('123456')` or kind of. bf then turns green.

**Comment by frantastic24** [comment]
as i said above, it doesn't like strings
`0x123456` is what you should be doing
