### ISSUE TITLE
can you do soundFadeOut on the voices?

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#12237]
### Describe your problem here.

YOu can do it on the inst by not inputting a tag, but can it affect the vocals as well?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
no, not with the just the function. `soundFadeOut` only fades out sounds that are stored in the `modchartSounds` map in PlayState.
The vocals aren't in that map.
You could probably set them in there using HScript, then use `soundFadeOut` on them.

**Comment by wubbzyfan** [comment]
idk how to hscript though

**Comment by AyMarte** [comment]
> idk how to hscript though

Welp, can't help you with that.. I barely know 1/4 of the coding for the game.
