### ISSUE TITLE
Tiny Week 6 Notes

### ISSUE THREAD

**Issue by RedstoneRuler** [ShadowMario/FNF-PsychEngine#1223]
### Describe your bug here.

With the newest source code build adding the ability to change note sizes, the week 6 notes are incorrectly scaled. They appear much smaller than they should. Changing arrow sizes to 0.99x fixes it.
![bote](https://user-images.githubusercontent.com/87531116/142766253-7052c35d-0160-43b1-84cf-bf076044df5f.PNG)

### Command Prompt/Terminal logs (if existing)

```bash
Empty
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed the FPS Cap and made player icons smoother, everything else is stock.

**Comment by nintendofan44** [comment]
![image](https://user-images.githubusercontent.com/85742902/142767551-cca0602a-775b-48d5-8e61-9cdb69d8c3e0.png)
you used this?

**Comment by RedstoneRuler** [comment]
UPDATE: I have found a fix for this issue, I multiplied the arrow sizes by 0.45 for pixel stages, and that scales the notes properly.
