### ISSUE TITLE
Quick Acces for Top and Bottom of Freeplay

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#12235]
### What feature do you want to get added on the **base** engine?

I would find it pretty cool, if one could use Home and End on the Keyboard to quickly get back to the top/bottom of the freeplay song selection. (Especially useful, if you have waaay too many mods or songs)
Why? Idk, for some reason I wanted to do that.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by BeastlyGabi** [comment]
Shift+Up/Down

**Comment by ZeitHeld** [comment]
> Shift+Up/Down

That _is_ faster, yes. But not the top/bottom.

**Comment by ShadowMario** [comment]
mouse wheel + shift or holding shift + up and down for a while
