### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by ReSteGuy** [ShadowMario/FNF-PsychEngine#12230]
### Describe your problem here.

This is the first time compiling on a different pc. This is what I got.
`source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
C:/HaxeToolkit/haxe/lib/flixel/5,2,2/flixel/util/FlxDestroyUtil.hx:3: characters 8-32 : You cannot access the flash package while in a macro (for flash.display.BitmapData)
source/animateatlas/AtlasFrameMaker.hx:2: characters 8-34 : ... referenced here
source/Paths.hx:3: characters 8-36 : ... referenced here
C:\Users\redst\Desktop\FNF-PsychEngine-0.6.3\FNF-PsychEngine-0.6.3\source\import.hx:1: characters 8-13 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/media/AudioSource.hx:138: characters 53-100 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/media/Sound.hx:14: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/utils/Assets.hx:9: characters 8-26 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/text/_internal/TextEngine.hx:9: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/display/_internal/CairoTextField.hx:3: characters 8-40 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/display/_internal/CairoGraphics.hx:6: characters 8-36 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/events/RenderEvent.hx:4: characters 8-44 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/display/DisplayObject.hx:13: characters 8-33 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing.

**Comment by TheRealJake12** [comment]
1. you're using haxe 4.3.0 (doesn't work with compiling until the libraries update)
2. Change the vlc.MP4Handler to `hxcodec.VideoHandler` and install hxCodec from git
`https://github.com/polybiusproxy/hxCodec.git`

**Comment by ReSteGuy** [comment]
Thanks ill see if that works.

**Comment by ReSteGuy** [comment]
> 1. you're using haxe 4.3.0 (doesn't work with compiling until the libraries update)
> 2. Change the vlc.MP4Handler to `hxcodec.VideoHandler` and install hxCodec from git
>    `https://github.com/polybiusproxy/hxCodec.git`

`source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
source/PlayState.hx:75: character 8 : `package hxcodec;` in C:/HaxeToolkit/haxe/lib/hxCodec/git/hxCodec/VideoHandler.hx should be `package hxCodec;``
Got this.

**Comment by TheRealJake12** [comment]
ok
change the `hxcodec` to `hxCodec` and simply do
`haxelib install flixel 4.11.0`

**Comment by ReSteGuy** [comment]
> ok change the `hxcodec` to `hxCodec` and simply do `haxelib install flixel 4.11.0`

bro as soon as you replyed i figured it out but still thank you so much!

**Comment by DavidHyena28** [comment]
i have a question

where is vlc.videohandler?? i got the same problem and idk how to fix it
