### ISSUE TITLE
so i ran the hmm thing and now i have about 500 errors that dont make sense to me

### ISSUE THREAD

**Issue by DarkMinerULTRA** [ShadowMario/FNF-PsychEngine#12236]
### Describe your problem here.

so i ran the install command in the hmm project in haxelib (haxelib run hmm install) and when i type lime test windows, it says this:

![image](https://user-images.githubusercontent.com/78901200/230691568-211878ea-8c19-4771-8a78-8dd92ffa00c8.png)

i have NO idea what any of this means

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, but it used to work. Recently i've had to reinstall all of the requirements for compiling.

**Comment by DarkMinerULTRA** [comment]
also just realized that the main error is
D:/FNF/peachy funkin source/.haxelib/flixel/5,2,2/flixel/util/FlxDestroyUtil.hx:3: characters 8-32 : You cannot access the flash package while in a macro (for flash.display.BitmapData)

the rest of the stuff doesn't help

**Comment by MemeHovy** [comment]
use haxe 4.2.5

**Comment by DarkMinerULTRA** [comment]
ok i did that. now it says:
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

P.S. i've seen other people have this error and i've tried the solutions, still didn't work

**Comment by MemeHovy** [comment]
you need visual studio 2019

**Comment by MemeHovy** [comment]
with the correct components

**Comment by DarkMinerULTRA** [comment]
which exact components? i have these installed:
Windows SDK (10.0.17763.0)
MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.9-16.10)

**Comment by MemeHovy** [comment]
MSVC v142 - VS 2019 C++ x64/x86 build tools must be latest

**Comment by DarkMinerULTRA** [comment]
it is the latest

**Comment by DarkMinerULTRA** [comment]
oh wait nvm
i have to choose MSVC v142 - VS 2019 C++ x64/x86 build tools (Latest) ?

**Comment by MemeHovy** [comment]
yes

**Comment by DarkMinerULTRA** [comment]
ok im dumb :( thank u!!!

**Comment by MemeHovy** [comment]
> ok im dumb :( thank u!!!

you're welcome

**Comment by Cappes** [comment]
a question, when I install haxe 2.5 it starts saying that i need to update and that stuff, is there any way to disable it?

**Comment by MemeHovy** [comment]
you're supposed to be using 4.2.5

**Comment by Cappes** [comment]
;-; thats alright

thanks!

**Comment by MemeHovy** [comment]
yw

**Comment by Cappes** [comment]
actually I just ran the command and it says 

"include\vlc/bitmap/VlcBitmap.h(13): fatal error C1083: Cannot open include file: 'LibVLC.h': No such file or directory"

what does this mean?? also sorry for dragging this on again

**Comment by MemeHovy** [comment]
make a new issue for that

**Comment by Cappes** [comment]
alr
