### ISSUE TITLE
how to get your custom keybindings with lua?

### ISSUE THREAD

**Issue by ROCK201888** [ShadowMario/FNF-PsychEngine#12238]
### What is your question?

i am working on a custom pause screen and i can't get the keybindings with lua

**Comment by ZeitHeld** [comment]
`if keyJustPressed(key)`

key can be 'space', 'left', 'up', 'down', 'right', 'pause', 'back, 'accept', 'reset'

these are the keybinds

**Comment by ROCK201888** [comment]
> 

didn't work

**Comment by ROCK201888** [comment]
> `if keyJustPressed(key)`
> 
> key can be 'space', 'left', 'up', 'down', 'right', 'pause', 'back, 'accept', 'reset'
> 
> these are the keybinds

didn't work

**Comment by ROCK201888** [comment]
> `if keyJustPressed(key)`
> 
> key can be 'space', 'left', 'up', 'down', 'right', 'pause', 'back, 'accept', 'reset'
> 
> these are the keybinds

wait it work! thx!!!!!
