### ISSUE TITLE
The screen keeps shaking when pausing the game

### ISSUE THREAD

**Issue by anonybean** [ShadowMario/FNF-PsychEngine#1224]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/94534428/142767633-c7cc0695-2231-4f20-a23d-fbbf8db2f395.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by anonybean** [comment]
if no one understand I played the screen shake event

**Comment by ShadowMario** [comment]
That's how screen shake works for FlxCamera.
