### ISSUE TITLE
Higher FPS breaks some aspects of the engine.

### ISSUE THREAD

**Issue by twizinho** [ShadowMario/FNF-PsychEngine#12242]
### Describe your bug here.

to summarize the title, if you set your FPS to more than 60, this kinda... breaks how velocity and intensity on some parts of the engine itself.
(make sure to read everything here before answering.)

## examples [Haxe]
main menu [60 FPS]
https://user-images.githubusercontent.com/95052258/230733042-4b20a141-5088-45ab-b18c-e515515712ff.mp4

main menu [240 FPS]
https://user-images.githubusercontent.com/95052258/230733061-685521e8-7211-4eed-9a85-de81ea3ee2a6.mp4

## examples [Lua]
(Camera Follows Note Script made by [Super_Hugo](https://gamebanana.com/mods/389481))

gameplay [60 FPS]
https://user-images.githubusercontent.com/95052258/230733287-4ba86cfe-0621-40f8-8a3e-737829df0bc2.mp4

gameplay [240 FPS]
https://user-images.githubusercontent.com/95052258/230733345-80256cd4-dac1-4ef0-984c-18287f227ec3.mp4

and you may wonder _"Well, you ARE using a custom build of Psych Engine, did you modify something?"_
the answer may be obvious but this also affects **official builds** of Psych Engine, not only customs.

## examples [Lua]
(the main menu of the official build of Psych Engine doesn't have much effect.)

gameplay [60 FPS]
https://user-images.githubusercontent.com/95052258/230733879-ffcdbf19-68f3-4eb1-9519-2d6574eb6190.mp4

gameplay [240 FPS]
https://user-images.githubusercontent.com/95052258/230733965-93c82683-a8ec-4ba8-8f6b-6fbff5715e53.mp4

i'm exactly sure if this has been happening on older versions aswell, but this is happening for sure on version 0.6.3.
if anyone knows how to fix this, me and my friend haone would be very grateful if you could share your knowledge with us. :D

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, but as I said, this affects both official and non-official builds.

**Comment by LilDrippyMyFnf** [comment]
didn't you already make this issue?

like, 50 minutes ago

**Comment by twizinho** [comment]
> didn't you already make this issue?
> 
> like, 50 minutes ago

...what? no

**Comment by twizinho** [comment]
> didn't you already make this issue?
> 
> like, 50 minutes ago

GitHub decided to make the same post twice, or I just forgot that I sent the issue, I'm so sorry for this lol

**Comment by TheLeerName** [comment]
use `elapsed` variable in your calculations in `update()`

**Comment by twizinho** [comment]
> use `elapsed` variable in your calculations in `update()`

thing is, we do use the `elapsed` variable, but it still causes the problem.
even the main psych engine code uses it.
