### ISSUE TITLE
getRandomInt(0,x) never returns 0

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#12244]
### Describe your bug here.

for some random event, I did some testing and used `getRandomInt(0,2)`, to see if all images would get returned, as I numbered them from 0 to 2, but as it turned out, that the image attached to **0 never showed up**.
it only got fixed, by using `getRandomInt(1,3)`

And I did test it like 5 or 10 times, so, can it be that it somehow never returns the 0?
Also idk if that might just be another haxe error. _(I swear, haxe does have a few issues-)_

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not via source

**Comment by frantastic24** [comment]
remember that lua arrays start at index 1, not 0

**Comment by frantastic24** [comment]
seems like it's pushing into the exclude array despite there not being any values, which ends up becoming 0 and it gets excluded
lua arrays start at index 1 so it's not usually a problem but it should be easy to fix
