### ISSUE TITLE
Health bar is missing

### ISSUE THREAD

**Issue by That1RobloxPlayerYT** [ShadowMario/FNF-PsychEngine#12243]
### Describe your problem here.

every time i try to play a song, the healthbar is always gone
all the things that could possibly hide it are unchecked
but even when it should be showing, its not
please help!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ZeitHeld** [comment]
any global scripts attached? or similar?
are mods active? if yes, have you tried to inactivated all?

**Comment by NotStampyC** [comment]
Have u tried just looking in the options or making a lua to enable the healthbar

**Comment by That1RobloxPlayerYT** [comment]
even when i have no mods added to a psych build, its still not there.
and i dont really know how to code lua (yet)

**Comment by That1RobloxPlayerYT** [comment]
oh also ive checked settings and everything that would hide it is off.

**Comment by ZeitHeld** [comment]
Did you unpack/unzip the folder? And run it not inside of the zip (or rar)
file? Have you also tried other versions of psych engine? Or like
reinstalling it?

That1RobloxPlayerYT ***@***.***> schrieb am Do., 13. Apr.
2023, 01:20:

**Comment by AyMarte** [comment]
@That1RobloxPlayerYT Put this script into FNF and this should keep the healthbar visible.
```
function onCreate()
	setPropertyFromClass('ClientPrefs', 'healthBarAlpha', 1)
end
```
This script should set the health bar and icons alpha to 1, or fully visible.

**Comment by AyMarte** [comment]
I once had this issue, it is that a certain key does it or something to disable it idk.

**Comment by KillerAvecRage** [comment]
One of the installed scripts must have setProperty('healthBarBG.visible') and setProperty('healthBarBG.visible') set to false, you might want to check any script that could be the reason of this health bar's invisibility issue

**Comment by elchango69** [comment]
you should all get girls
