### ISSUE TITLE
can someone help me?

### ISSUE THREAD

**Issue by denumu07** [ShadowMario/FNF-PsychEngine#12258]
### Describe your bug here.

I tried adding the encore menu from sonic.exe and when I compiled it I got this error
Can someone help me?

### Command Prompt/Terminal logs (if existing)

```bash
source/MainMenuState.hx:222: characters 42-55 : Type name SongMetadata is redefined from module EncoreState
source/MainMenuState.hx:222: characters 42-55 : ... For function argument 'nextState'
source/PlayState.hx:3991: characters 36-49 : Module FreeplayState does not define type FreeplayState
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i tried finding SongMetaData and NextState

**Comment by Stefan2008Git** [comment]
How?
