### ISSUE TITLE
Exists, but only asynchronously

### ISSUE THREAD

**Issue by WayloFunk** [ShadowMario/FNF-PsychEngine#12256]
### Describe your problem here.

The mp3 files dont load and spit out an error message:
"[lime.utils.Assets] ERROR: SOUND asset \"songs:assets/songs/ugh/Voices.mp3\" exists, but only asynchronously"

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5/Browser

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by WayloFunk** [comment]
Here is the full log:

`PsychEngine.js:135343 
        
       The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.
lime_media_AudioContext @ PsychEngine.js:135343
lime_media_AudioManager.init @ PsychEngine.js:135375
lime__$internal_backend_html5_HTML5Application @ PsychEngine.js:6326
lime_app_Application @ PsychEngine.js:6877
openfl_display_Application @ PsychEngine.js:142091
ApplicationMain.create @ PsychEngine.js:7202
lime_system_System.embed.$hx_exports.lime.embed @ PsychEngine.js:137269
$hx_exports.lime.embed @ PsychEngine.js:193966
(anonymous) @ (index):75
PsychEngine.js:193977 
        
       The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.
_ @ PsychEngine.js:193977
init @ PsychEngine.js:193977
(anonymous) @ PsychEngine.js:193979
o @ PsychEngine.js:193977
lime_media_AudioBuffer.fromFiles @ PsychEngine.js:135219
lime_media_AudioBuffer.loadFromFiles @ PsychEngine.js:135245
loadAudioBuffer @ PsychEngine.js:139096
load @ PsychEngine.js:139046
load @ PsychEngine.js:140664
ApplicationMain.create @ PsychEngine.js:7254
lime_system_System.embed.$hx_exports.lime.embed @ PsychEngine.js:137269
$hx_exports.lime.embed @ PsychEngine.js:193966
(anonymous) @ (index):75
PsychEngine.js:193977 
        
       The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.
_ @ PsychEngine.js:193977
unload @ PsychEngine.js:193977
_unlockAudio @ PsychEngine.js:193977
init @ PsychEngine.js:193977
(anonymous) @ PsychEngine.js:193979
o @ PsychEngine.js:193977
lime_media_AudioBuffer.fromFiles @ PsychEngine.js:135219
lime_media_AudioBuffer.loadFromFiles @ PsychEngine.js:135245
loadAudioBuffer @ PsychEngine.js:139096
load @ PsychEngine.js:139046
load @ PsychEngine.js:140664
ApplicationMain.create @ PsychEngine.js:7254
lime_system_System.embed.$hx_exports.lime.embed @ PsychEngine.js:137269
$hx_exports.lime.embed @ PsychEngine.js:193966
(anonymous) @ (index):75
PsychEngine.js:124618 
        
       Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
lime__$internal_graphics_ImageCanvasUtil.createImageData @ PsychEngine.js:124618
lime__$internal_graphics_ImageCanvasUtil.convertToData @ PsychEngine.js:124521
lime__$internal_graphics_ImageCanvasUtil.colorTransform @ PsychEngine.js:124481
colorTransform @ PsychEngine.js:130903
colorTransform @ PsychEngine.js:60216
updateFramePixels @ PsychEngine.js:2984
calcFrame @ PsychEngine.js:2964
drawFrame @ PsychEngine.js:2648
stamp @ PsychEngine.js:2608
makeArrowBkg @ PsychEngine.js:78592
set_anchor @ PsychEngine.js:78465
refresh @ PsychEngine.js:78537
flixel_addons_ui_FlxUITooltip @ PsychEngine.js:77980
flixel_addons_ui_FlxUITooltipManager @ PsychEngine.js:78677
create @ PsychEngine.js:5439
create @ PsychEngine.js:5707
create @ PsychEngine.js:43087
switchState @ PsychEngine.js:57897
create @ PsychEngine.js:57782
__dispatchEvent @ PsychEngine.js:7451
__dispatchEvent @ PsychEngine.js:8321
__dispatchWithCapture @ PsychEngine.js:8361
addChildAt @ PsychEngine.js:9171
addChild @ PsychEngine.js:9122
setupGame @ PsychEngine.js:9813
init @ PsychEngine.js:9800
__dispatchEvent @ PsychEngine.js:7451
__dispatchEvent @ PsychEngine.js:8321
__dispatchWithCapture @ PsychEngine.js:8361
addChildAt @ PsychEngine.js:9171
addChild @ PsychEngine.js:9122
Main.main @ PsychEngine.js:9791
ApplicationMain.start @ PsychEngine.js:7271
tmp @ PsychEngine.js:7237
dispatch @ PsychEngine.js:129811
display_onUnload @ PsychEngine.js:149627
__dispatchEvent @ PsychEngine.js:7451
__dispatchEvent @ PsychEngine.js:8321
__dispatchWithCapture @ PsychEngine.js:8361
dispatchEvent @ PsychEngine.js:8218
onLoaded @ PsychEngine.js:102439
onEnterFrame @ PsychEngine.js:102514
__dispatchEvent @ PsychEngine.js:7451
__dispatch @ PsychEngine.js:8309
__broadcastEvent @ PsychEngine.js:150859
__onLimeRender @ PsychEngine.js:151946
dispatch @ PsychEngine.js:129894
handleApplicationEvent @ PsychEngine.js:6641
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
PsychEngine.js:193977 
        
       The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.
_autoResume @ PsychEngine.js:193977
play @ PsychEngine.js:193977
play @ PsychEngine.js:122774
play @ PsychEngine.js:135460
openfl_media_SoundChannel @ PsychEngine.js:180458
play @ PsychEngine.js:59591
startSound @ PsychEngine.js:103611
play @ PsychEngine.js:103526
playMusic @ PsychEngine.js:107930
startIntro @ PsychEngine.js:43125
(anonymous) @ PsychEngine.js:43111
onLoopFinished @ PsychEngine.js:117633
update @ PsychEngine.js:117694
update @ PsychEngine.js:57947
step @ PsychEngine.js:57925
onEnterFrame @ PsychEngine.js:57859
__dispatchEvent @ PsychEngine.js:7451
__dispatch @ PsychEngine.js:8309
__broadcastEvent @ PsychEngine.js:150859
__onLimeRender @ PsychEngine.js:151946
dispatch @ PsychEngine.js:129894
handleApplicationEvent @ PsychEngine.js:6641
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
PsychEngine.js:124618 
        
       Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
lime__$internal_graphics_ImageCanvasUtil.createImageData @ PsychEngine.js:124618
lime__$internal_graphics_ImageCanvasUtil.convertToData @ PsychEngine.js:124521
lime__$internal_graphics_ImageCanvasUtil.colorTransform @ PsychEngine.js:124481
colorTransform @ PsychEngine.js:130903
colorTransform @ PsychEngine.js:60216
updateFramePixels @ PsychEngine.js:2984
calcFrame @ PsychEngine.js:2964
drawFrame @ PsychEngine.js:2648
stamp @ PsychEngine.js:2608
makeArrowBkg @ PsychEngine.js:78592
set_anchor @ PsychEngine.js:78465
refresh @ PsychEngine.js:78537
flixel_addons_ui_FlxUITooltip @ PsychEngine.js:77980
flixel_addons_ui_FlxUITooltipManager @ PsychEngine.js:78677
create @ PsychEngine.js:5439
create @ PsychEngine.js:5707
create @ PsychEngine.js:42375
switchState @ PsychEngine.js:57897
update @ PsychEngine.js:57934
step @ PsychEngine.js:57925
onEnterFrame @ PsychEngine.js:57859
__dispatchEvent @ PsychEngine.js:7451
__dispatch @ PsychEngine.js:8309
__broadcastEvent @ PsychEngine.js:150859
__onLimeRender @ PsychEngine.js:151946
dispatch @ PsychEngine.js:129894
handleApplicationEvent @ PsychEngine.js:6641
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
PsychEngine.js:56400 source/LoadingState.hx:162: Setting asset folder to shared
PsychEngine.js:56400 source/LoadingState.hx:101: false
PsychEngine.js:56400 source/PlayState.hx:1445: Anim speed: 1
PsychEngine.js:56400 source/Conductor.hx:135: new BPM map BUDDY []
PsychEngine.js:140567 
        
       Uncaught haxe_ValueException {message: '[lime.utils.Assets] ERROR: SOUND asset "songs:asse…utorial/Inst.mp3" exists, but only asynchronously', __previousException: undefined, __nativeException: haxe_ValueException, __skipStack: 2, value: '[lime.utils.Assets] ERROR: SOUND asset "songs:asse…utorial/Inst.mp3" exists, but only asynchronously', …}
lime_utils_Log.error @ PsychEngine.js:140567
lime_utils_Assets.getAsset @ PsychEngine.js:139596
lime_utils_Assets.getAudioBuffer @ PsychEngine.js:139610
openfl_utils_Assets.getSound @ PsychEngine.js:186197
loadEmbedded @ PsychEngine.js:103451
generateSong @ PsychEngine.js:38517
create @ PsychEngine.js:37278
switchState @ PsychEngine.js:57897
update @ PsychEngine.js:57934
step @ PsychEngine.js:57925
onEnterFrame @ PsychEngine.js:57859
__dispatchEvent @ PsychEngine.js:7451
__dispatch @ PsychEngine.js:8309
__broadcastEvent @ PsychEngine.js:150859
__onLimeRender @ PsychEngine.js:151946
dispatch @ PsychEngine.js:129894
handleApplicationEvent @ PsychEngine.js:6641
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651
requestAnimationFrame (async)
handleApplicationEvent @ PsychEngine.js:6651`

**Comment by Hackx2** [comment]
Please use https://srcshare.io/
