### ISSUE TITLE
Scaling down the strums dosen't scale down the notes

### ISSUE THREAD

**Issue by Turneysevenix** [ShadowMario/FNF-PsychEngine#12250]
I want to scale down and move around my notes to fit the background. I'm not a coder I dont know anything about lua scripting and most of the things i have done were just coping and pasting from other scripts i have found. I have already found a way to move them around and scale down the strums, but the notes are way too big and i'm having a lot of trouble finding out how to scale them down too

This is the code that im using and some images to demonstrate what i mean, thank you!

![Sem título2](https://user-images.githubusercontent.com/115051090/230806944-12fb0e78-78ac-4dff-b1c1-7dd84e28ca7c.png)
![Sem título](https://user-images.githubusercontent.com/115051090/230806947-f250c359-7507-49dd-83fd-e59914c2f767.png)

"function onEvent(name, value1, value2)
	for i = 0,7 do -- sets id, idk what that means
	setPropertyFromGroup('strumLineNotes', i, 'scale.x', 0.4) -- scales both mine and the opponents strums to 0.4
	setPropertyFromGroup('strumLineNotes', i, 'scale.y', 0.4)
end

  setPropertyFromGroup('opponentStrums',0,'x','-500') -- moves opponents strums offscreen
  setPropertyFromGroup('opponentStrums',1,'x','-500')
  setPropertyFromGroup('opponentStrums',2,'x','-500')
  setPropertyFromGroup('opponentStrums',3,'x','-500')

  setPropertyFromGroup('playerStrums',0,'x','430') -- moves my strums to where i want
  setPropertyFromGroup('playerStrums',1,'x','495')
  setPropertyFromGroup('playerStrums',2,'x','560')
  setPropertyFromGroup('playerStrums',3,'x','625')
  
  setPropertyFromGroup('playerStrums',0,'y','335')
  setPropertyFromGroup('playerStrums',1,'y','335')
  setPropertyFromGroup('playerStrums',2,'y','335')
  setPropertyFromGroup('playerStrums',3,'y','335')
end	

function onCreate()
    setProperty('healthBar.alpha', tonumber(0))
    setProperty('iconP1.alpha', tonumber(0))
    setProperty('iconP2.alpha', tonumber(0))
end"

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no, its base PsychEngine

**Comment by ManMaster707** [comment]
Try adding this to the code, it should scale the notes as well.

```lua
-- Bear in mind that "unspawnNotes" is referring to the notes in the chart, not the strums!
for i= 0, getProperty('unspawnNotes.length')-1 do
    setPropertyFromGroup('unspawnNotes', i, 'scale.x', 0.4)
    setPropertyFromGroup('unspawnNotes', i, 'scale.y', 0.4)
end

**Comment by Turneysevenix** [comment]
> 

IT WORKED THANK YOUUUUUUUUUUUUUUU

also btw, where did you get those variables? i'm probably going to be doing more code related stuff but even if the wiki has a ton of stuff it dosent have everything, but yeah, thank you a LOT

**Comment by ManMaster707** [comment]
> > 
> 
> IT WORKED THANK YOUUUUUUUUUUUUUUU
> 
> also btw, where did you get those variables? i'm probably going to be doing more code related stuff but even if the wiki has a ton of stuff it dosent have everything, but yeah, thank you a LOT

When i first got my toes wet into lua coding i remember finding them in the custom note template script, as they're mainly used for custom notes.
(Also, no problem!)
