### ISSUE TITLE
Game Breaks when losing??

### ISSUE THREAD

**Issue by PotatoKing0419** [ShadowMario/FNF-PsychEngine#12257]
### Describe your problem here.

This is by far the WEIRDEST thing I've ever seen in psych engine ong

https://www.youtube.com/watch?v=5Q1grKGnUNI

So each time I lose, 50% of the time, it'll restart the song ONLY with the instrumental, no voices or charting, then once the song gets back to the point where I lost, it'll play all the voices and charting again, except all the notes go right past the arrows, whether I hit them or not. Oh yeah and all events and lua triggers don't work during this.
Unfortunately, I can never catch it on camera as it happens, only times where I start recording after it happens.
someone help idk how to fix this

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Hackx2** [comment]
most likely your pc can't handle it
