### ISSUE TITLE
Speed rates

### ISSUE THREAD

**Issue by dum-du-m** [ShadowMario/FNF-PsychEngine#1225]
### What feature do you want to get added on the base engine?

I would like changeable speed on songs to be added to Psych Engine.

**Comment by NS-Unfair** [comment]
@dum-du-m, this is already a feature. In Lua, you can use setProperty('SONG.speed',speed) to set the scroll speed.

**Comment by ShadowMario** [comment]
Duplicate of #317

**Comment by dum-du-m** [comment]
> @dum-du-m, this is already a feature. In Lua, you can use setProperty('SONG.speed',speed) to set the scroll speed.



> Duplicate of #317

not what i meant, like this https://youtu.be/HooSd3Z2ltE
