### ISSUE TITLE
30fps cap bug

### ISSUE THREAD

**Issue by EboiAnimations** [ShadowMario/FNF-PsychEngine#12268]
### Describe your bug here.

Basically, today FNF started being stuck at 30fps, but only when I click on the game. If the game is running but I click the desktop it goes back up to 60+. Help plz. I'm literally about to punch a hole in my pc.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added 1 song/week to the game.

**Comment by biomseed** [comment]
Delete the appdata/roaming/ShadowMario/PsychEngine folder to delete all the save data, which should reset the game to whatever it was back when you first opened it
