### ISSUE TITLE
Can't finish installation process

### ISSUE THREAD

**Issue by Pixelknife4** [ShadowMario/FNF-PsychEngine#12269]
### Describe your bug here.

I ran 'haxelib install hmm' and It worked but

I try to run 'haxelib run hmm install' but it returns, 

_Validation error: hmm.json not found in current working directory
Use "hmm help" to see usage_

### Command Prompt/Terminal logs (if existing)

```bash
Validation error: hmm.json not found in current working directory
Use "hmm help" to see usage
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, Can't install

**Comment by biomseed** [comment]
Make sure you are in the directory with hmm.json in it, the root directory.

**Comment by Pixelknife4** [comment]
How do I do that?

**Comment by Pixelknife4** [comment]
How do I do that?

**Comment by Pixelknife4** [comment]
nvm I got it

**Comment by Rudistoy** [comment]
> nvm I got it
how?

**Comment by TerminallyAwesome** [comment]
how?

**Comment by MemeHovy** [comment]
`cd` into the folder

**Comment by TerminallyAwesome** [comment]
into what folder?

**Comment by TerminallyAwesome** [comment]
nevermind just got it
