### ISSUE TITLE
Script Help

### ISSUE THREAD

**Issue by bf244** [ShadowMario/FNF-PsychEngine#12261]
### Describe your problem here.

i need help to make a script where the helthbar is below half the opponent will play an anim at the end of a song,
if is upper half boyfriend does the anim (always at the end of a song

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by NightmaresPlayz** [comment]
ill see if i can try to create that, i dont have experience but it seems simple

**Comment by NightmaresPlayz** [comment]
i can but you need to know the step where you want the anim to play

**Comment by NightmaresPlayz** [comment]
i can make a curStep code for you but u need to know the step you want anim to play

**Comment by bf244** [comment]
> 

i can do that thanks man
