### ISSUE TITLE
error when opening freeplay

### ISSUE THREAD

**Issue by Aadamgaming** [ShadowMario/FNF-PsychEngine#12265]
### Describe your bug here.

i tried to open free play but it showed a error
[PsychEngine_2023-04-14_17'51'45.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/11235319/PsychEngine_2023-04-14_17.51.45.txt)

### Command Prompt/Terminal logs (if existing)

```bash
Paths.hx (line 356)
HealthIcon.hx (line 43)
HealthIcon.hx (line 20)
editors/WeekEditorState.hx (line 615)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i added a mod to it with the mod folder

**Comment by biomseed** [comment]
You may have missing songs (or charts) i think
