### ISSUE TITLE
what the fuck does this mean

### ISSUE THREAD

**Issue by oogaboogajookag** [ShadowMario/FNF-PsychEngine#1226]
### Describe your problem here.

i put some fuckin uhhhhh tricky assets into the game, like the whole character file n everything not just an image. all the animations are in the file. i try and use the character in character editor and this shows up. hel
![psych](https://user-images.githubusercontent.com/94800435/142773261-93798f8c-197f-4aac-b9b7-8a22ef92e750.png)
p

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

**Comment by CrusherMods** [comment]
something is wrong with the json at line 725 (I think)

**Comment by NS-Unfair** [comment]
That means there is some kind of weird character at line 725. I think you have to delete whatever is at char91, line 725

**Comment by ShadowMario** [comment]
You're not editing the files manually, are you?
If not, when did this happen? Did you press anything for it to happen?

**Comment by lolbruhfart** [comment]
omg is that shadow maro from pop game fnf
