### ISSUE TITLE
I've gotten through the installation process but I don't know how to run it

### ISSUE THREAD

**Issue by Pixelknife4** [ShadowMario/FNF-PsychEngine#12270]
### Describe your problem here.

I know im stupid but I dont know where to run it, there is no .exe

### Are you modding a build from source or with Lua?

Source

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by AyMarte** [comment]
It should run, or there probably is an error that you may have missed inside of the command prompt that was opened.
