### ISSUE TITLE
How to use values using`getPropertyFromClass('ClientPrefs')` and `setPropertyFromClass('ClientPrefs')` for preset keybinds?

### ISSUE THREAD

**Issue by AyMarte** [ShadowMario/FNF-PsychEngine#12271]
### What is your question?

Is there a way that I can use `getPropertyFromClass('ClientPrefs')` to get the keybinds, like for example, something like this:
```
setPropertyFromClass('ClientPrefs', 'keybinds.LEFT', 'G')
```
If this is the correct way or not, please tell me, and if this is not the correct way, please do tell me.

**Comment by TheLeerName** [comment]
```lua
function onCreatePost()
	debugPrint("note_left (main): "..getKeyBind("note_left", false)) -- prints main key
	debugPrint("note_left (alt): "..getKeyBind("note_left", true)) -- prints alt key
end
-- Returns id of keybind
-- name : string - name of keybind
-- isAlternative : boolean - if true then returns alternative (second) key of bind, if false then main (first) key
function getKeyBind(name, isAlternative)
	return runHaxeCode("return ClientPrefs.keyBinds.get('"..name.."')["..(isAlternative and 1 or 0).."];")
end
```

**Comment by ROCK201888** [comment]
> ```lua
> function onCreatePost()
> 	debugPrint("note_left (main): "..getKeyBind("note_left", false)) -- prints main key
> 	debugPrint("note_left (alt): "..getKeyBind("note_left", true)) -- prints alt key
> end
> -- Returns id of keybind
> -- name : string - name of keybind
> -- isAlternative : boolean - if true then returns alternative (second) key of bind, if false then main (first) key
> function getKeyBind(name, isAlternative)
> 	return runHaxeCode("return ClientPrefs.keyBinds.get('"..name.."')["..(isAlternative and 1 or 0).."];")
> end
> ```

bro it is still the key id

**Comment by AyMarte** [comment]
Thx, sorry bout this tho
