### ISSUE TITLE
How to move character in Lua?

### ISSUE THREAD

**Issue by Luigitin** [ShadowMario/FNF-PsychEngine#12277]
### Describe your problem here.

I'm trying to recreate this part of Memory//Leak from FNF' Corruption, but like since i dont know anything about coding i cant. So, just asking, can someone help me/tell me how i can do this? (and also including easing)
sorry to bother you guys xd

(this is what im trying to recreate:)
https://user-images.githubusercontent.com/111601864/232358938-55ebaf9a-55fe-4dea-8819-ba2460333e77.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Lorekeeper49** [comment]
You can set the second value of the tween functions to `'bf'` `'gf'` or `'dad'` (with the quotes) to operate the characters that way
