### ISSUE TITLE
Uncaught Error: Null Object Reference  Crash Handler written by: sqirra-rng

### ISSUE THREAD

**Issue by JcOoferGang** [ShadowMario/FNF-PsychEngine#12275]
### Describe your problem here.

every time when im trying to export sprites it keep saying Null Object Reference.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Aguluntrun89** [comment]
same 🗿

**Comment by addanvipk** [comment]
Mô tả vấn đề của bạn ở đây.
mỗi khi tôi chơi nó thường bị đứng im
Bạn đang sửa đổi bản dựng từ nguồn hay bằng Lua?
Nguồn
Mục tiêu xây dựng của bạn là gì?
Windows x64
Bạn có chỉnh sửa gì trong bản dựng này không? Nếu vậy, hãy đề cập hoặc tóm tắt những thay đổi của bạn.
KHÔNG
