### ISSUE TITLE
cant run lime test

### ISSUE THREAD

**Issue by Youraveragefnffan** [ShadowMario/FNF-PsychEngine#12276]
### Describe your bug here.

![buga](https://user-images.githubusercontent.com/123619054/232352875-475849c5-c86b-4482-a1da-f453c9da8474.png)
I keep running into this issue every time to i try to run it, any idea on why it is?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not edit a single thing.

**Comment by MemeHovy** [comment]
use nebulazoruas fork of linc_luajit

**Comment by Youraveragefnffan** [comment]
how do i do that?

**Comment by MemeHovy** [comment]
`haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit`

**Comment by Youraveragefnffan** [comment]
Thank you

**Comment by MemeHovy** [comment]
np
