### ISSUE TITLE
lime test windows error

### ISSUE THREAD

**Issue by SeasonedCoffee** [ShadowMario/FNF-PsychEngine#12289]
### Describe your problem here.

Hello everybody.
Im trying to make an fnf mod, but i keep having this problem whenever I try to compile the code:

PS C:\codigofnf\FNF-PsychEngine-main> lime test windows
C:/codigofnf/FNF-PsychEngine-main/.haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
C:/codigofnf/FNF-PsychEngine-main/.haxelib/flixel/5,2,2/flixel/util/FlxDestroyUtil.hx:3: characters 8-32 : You cannot access the flash package while in a macro (for flash.display.BitmapData)
source/animateatlas/AtlasFrameMaker.hx:2: characters 8-34 : ... referenced here
source/Paths.hx:3: characters 8-36 : ... referenced here
C:\codigofnf\FNF-PsychEngine-main\source\import.hx:1: characters 8-13 : ... referenced here
C:\codigofnf\FNF-PsychEngine-main\.haxelib\lime\8,0,1/src/lime/media/AudioSource.hx:138: characters 53-100 : ... referenced here
C:/codigofnf/FNF-PsychEngine-main/.haxelib/openfl/9,2,1/src/openfl/media/Sound.hx:14: characters 8-30 : ... referenced here
C:/codigofnf/FNF-PsychEngine-main/.haxelib/openfl/9,2,1/src/openfl/utils/Assets.hx:9: characters 8-26 : ... referenced here
C:/codigofnf/FNF-PsychEngine-main/.haxelib/openfl/9,2,1/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here
C:/codigofnf/FNF-PsychEngine-main/.haxelib/openfl/9,2,1/src/openfl/text/_internal/TextEngine.hx:9: characters 8-24 : ... referenced here
C:/codigofnf/FNF-PsychEngine-main/.haxelib/openfl/9,2,1/src/openfl/display/_internal/CairoTextField.hx:3: characters 8-40 : ... referenced here
C:/codigofnf/FNF-PsychEngine-main/.haxelib/openfl/9,2,1/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here
C:/codigofnf/FNF-PsychEngine-main/.haxelib/openfl/9,2,1/src/openfl/display/_internal/CairoGraphics.hx:6: characters 8-36 : ... referenced here
C:/codigofnf/FNF-PsychEngine-main/.haxelib/openfl/9,2,1/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
C:/codigofnf/FNF-PsychEngine-main/.haxelib/openfl/9,2,1/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
C:/codigofnf/FNF-PsychEngine-main/.haxelib/openfl/9,2,1/src/openfl/events/RenderEvent.hx:4: characters 8-44 : ... referenced here
C:/codigofnf/FNF-PsychEngine-main/.haxelib/openfl/9,2,1/src/openfl/display/DisplayObject.hx:13: characters 8-33 : ... referenced here
C:/codigofnf/FNF-PsychEngine-main/.haxelib/openfl/9,2,1/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
C:/codigofnf/FNF-PsychEngine-main/.haxelib/openfl/9,2,1/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
C:\codigofnf\FNF-PsychEngine-main\.haxelib\lime\8,0,1/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
C:\codigofnf\FNF-PsychEngine-main\.haxelib\lime\8,0,1/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
C:\codigofnf\FNF-PsychEngine-main\.haxelib\lime\8,0,1/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
C:\codigofnf\FNF-PsychEngine-main\.haxelib\lime\8,0,1/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
C:\codigofnf\FNF-PsychEngine-main\.haxelib\lime\8,0,1/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
C:\codigofnf\FNF-PsychEngine-main\.haxelib\lime\8,0,1/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
C:\codigofnf\FNF-PsychEngine-main\.haxelib\lime\8,0,1/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
C:\codigofnf\FNF-PsychEngine-main\.haxelib\lime\8,0,1/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
C:\codigofnf\FNF-PsychEngine-main\.haxelib\lime\8,0,1/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
C:\codigofnf\FNF-PsychEngine-main\.haxelib\lime\8,0,1/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
C:\codigofnf\FNF-PsychEngine-main\.haxelib\lime\8,0,1/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
C:\codigofnf\FNF-PsychEngine-main\.haxelib\lime\8,0,1/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here

If anyone could help me, i would really appreciate it.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
use haxe 4.2.5

**Comment by SeasonedCoffee** [comment]
Ok, the problem was fixed, but now it shows this:
PS C:\codigofnf\FNF-PsychEngine-main> lime test windows
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\codigofnf\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

Any ideas on anything i could have missed or if i have to reinstall something else?
Thanks for the help btw.

**Comment by SeasonedCoffee** [comment]
> use haxe 4.2.5

Alright, the problem was fixed, but now it shows this:
PS C:\codigofnf\FNF-PsychEngine-main> lime test windows
source/Achievements.hx:132: characters 30-54 : Warning : FlxCamera.defaultCameras is deprecated, use FlxG.cameras.setDefaultDrawTarget instead
C:\codigofnf\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

Any ideas on anything i could have missed or if i have to reinstall something else?
Thanks for the help btw.

**Comment by MemeHovy** [comment]
download visual studio 2019 with the correct components

**Comment by SeasonedCoffee** [comment]
> download visual studio 2019 with the correct components

i did, i installed everything i had to install and i still get that error :(

**Comment by MemeHovy** [comment]
when you install `MSVC v142 - VS 2019 C++ x64/x86 build tools` it has to be **latest**

**Comment by SeasonedCoffee** [comment]
> when you install `MSVC v142 - VS 2019 C++ x64/x86 build tools` it has to be **latest**

they're the latest version, i just checked to make sure

**Comment by SeasonedCoffee** [comment]
> when you install `MSVC v142 - VS 2019 C++ x64/x86 build tools` it has to be **latest**

I still couldn't find a solution to the problem, but thanks for the help anyway, I'm going to open a new issue with it
