### ISSUE TITLE
fade in fade out effect

### ISSUE THREAD

**Issue by Gurudevsing** [ShadowMario/FNF-PsychEngine#12283]
### Describe your problem here.

how to do fade in fade out effect like ..indie cross 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by DisIsNOt** [comment]
doTweenAlpha

**Comment by Gurudevsing** [comment]
> doTweenAlpha



function onCreatePost()
    doTweenAlpha('1_alpha','1',0.2,2,'linear')
   setProperty('gf.alpha', 0)
  triggerEvent('Change Character', 'dad', 'die')
end

it works but i want to loop it

**Comment by Gurudevsing** [comment]
> rks but i want to loop it



> doTweenAlpha

how to loop that idk?
