### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by Darkergull256** [ShadowMario/FNF-PsychEngine#12280]
### Describe your problem here.

Hello, I'm new to this entire compiling thing, I've tried so many times to install and followed each step but every time I compile it doesn't go beyond this. Do you guys know what could be the issue or am I being stupid?

![image-4](https://user-images.githubusercontent.com/130863696/232642735-c8d58bc3-1f85-4715-b274-47ef8828178b.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
use haxe 4.2.5, haxe 4.3 has an issue with macros
