### ISSUE TITLE
Error en el menu del modo historia

### ISSUE THREAD

**Issue by ThdRazer12** [ShadowMario/FNF-PsychEngine#12285]
### What is your question?

Necesito saber si existe una solución para éste error que me lanza cuando entro al modo historia.
Aquí el error:

Paths.hx (line 354)
StoryMenuState.hx (line 419)
StoryMenuState.hx (line 224)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
Null Object Reference

**Comment by Aguluntrun89** [comment]
necesito saber si Pusiste un nuevo sprite, si es que lo hiciste copia el xl de otro personaje y le cambias el nombre

**Comment by ThdRazer12** [comment]
Lo que hice fue poner un mod pero aunque no tenga mods me sigue lanzando el
mismo error.

Solo cuando abro el story mode cuando empiezo a bajar
