### ISSUE TITLE
Character JSON values are not staying the same.

### ISSUE THREAD

**Issue by omotashi** [ShadowMario/FNF-PsychEngine#12282]
### Describe your bug here.

Good day, I am trying to make a character work in game, but every time it looks perfect in the character editor, in game the character is much smaller and offsets are wonky. Every value (minus icon values) are not being set properly OR it could be a scaling issue (since that's the easiest cause of the problem I can see.)

There are other mods in this psych engine "mods" folder I have made and never had this issue before.

A video of my steps and visual representation of what is happening can be found [here](https://streamable.com/klvd1n)

If you have any questions or need to see more please let me know.

### Command Prompt/Terminal logs (if existing)

```bash
N/A
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Other than adding the needed files for a character, no.

**Comment by KookerFoxYT** [comment]
maybe because of the character size code isnt that accurate to the stepper's value
