### ISSUE TITLE
no matter how many i times i replace hxcodec with 2.5.1, the engine doesn't compile

### ISSUE THREAD

**Issue by pakieFNF** [ShadowMario/FNF-PsychEngine#12297]
### Describe your problem here.

pretty self explanatory, basically no matter how many times i run "haxelib remove hxCodec
haxelib install hxCodec 2.5.1" the engine just straight up just refuses to compile with lime test windows, always giving me a "Could not find include file "C:/haxelib/hxCodec/2,6,1/vlc/lib/LibVLCBuild.xml" nag, even though i replaced it, what the fuck am i doing wrong?, if it helps, im using haxe 4.3.0

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
you need to use haxe 4.2.5

**Comment by pakieFNF** [comment]
thanks

**Comment by MemeHovy** [comment]
np
