### ISSUE TITLE
source/PlayState.hx:1641: characters 2-10 : Missing ;

### ISSUE THREAD

**Issue by thegabenamefine-thedumbcoder** [ShadowMario/FNF-PsychEngine#12293]
### Describe your bug here.

ive tried to fix this iusse but all its doing is making it worse
and i think i had this iusse before i got back into making a mod
can someone help me please?

### Command Prompt/Terminal logs (if existing)

```bash
PS D:\Docs\smilesussymod> lime build windows -release
source/PlayState.hx:1641: characters 2-10 : Missing ;
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
dude, you're literally missing a ; in your code, are you too blind to read?

**Comment by thegabenamefine-thedumbcoder** [comment]
elaborate the location douche

**Comment by MemeHovy** [comment]
> elaborate the location douche

kys
