### ISSUE TITLE
lime test windows stops working

### ISSUE THREAD

**Issue by hotpocketsarepoggers** [ShadowMario/FNF-PsychEngine#12290]
### Describe your problem here.

everytime i tried to compile it worked normally but for some reason now when i try to compile I get these errors

C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/text/FlxTypeText.hx:8: characters 8-29 : Type not found : flixel.sound.FlxSound
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/text/FlxTypeText.hx:77: characters 26-34 : Type not found : FlxSound
source/CoolUtil.hx:18: lines 18-141 : ... Defined in this class
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/PlayState.hx:1739: characters 13-23 : Type not found : MP4Handler
source/DialogueBox.hx:144: characters 16-22 : flixel.addons.text.FlxTypeText has no field sounds
source/DialogueBox.hx:244: characters 16-25 : flixel.addons.text.FlxTypeText has no field resetText
source/DialogueBox.hx:245: characters 16-21 : flixel.addons.text.FlxTypeText has no field start
source/DialogueBox.hx:246: characters 16-32 : flixel.addons.text.FlxTypeText has no field completeCallback
source/DialogueBox.hx:223: characters 18-22 : flixel.addons.text.FlxTypeText has no field skip
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/transition/FlxTransitionableState.hx:81: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by FunkoDev** [comment]
Update Haxe: 4.3.0

https://haxe.org/download/

**Comment by hotpocketsarepoggers** [comment]
> Update Haxe: 4.3.0
> 
> https://haxe.org/download/

It gave me more errors

**Comment by TheMuhammedAli** [comment]
Hello, I'm getting the same error, did you find a solution?
