### ISSUE TITLE
animation icons fnf on the health bar

### ISSUE THREAD

**Issue by Rifemall** [ShadowMario/FNF-PsychEngine#12298]
### Describe your problem here.

Hi, I'm one who is building a mod based on the pibby glitch, I wanted to know how to do animation to the icons on the health bar in a script.
Thank you for anyone who will reply to your message.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by LowoTV** [comment]
I do not fully understand this, but I will try and help you.

You create the animated icon in **Adobe Animate** Use it as **an icon**. You will see it _would be **animated**_

Please point out any mistakes. As I do not fully understand and so will be prone to errors.

**Comment by Rifemall** [comment]
thanks, now i know what i have to do
