### ISSUE TITLE
Compiling Issue 0.6.3

### ISSUE THREAD

**Issue by ItVid** [ShadowMario/FNF-PsychEngine#12301]
### Describe your bug here.

Just got back from a 6 month hiatus, resetted my PC, and now I dont even know whats going on. I downloaded everything im pretty sure and I get this: 
![image](https://user-images.githubusercontent.com/82421426/233760273-f826f58a-130d-4793-97bb-c8c36fb49ca3.png)

Would love help.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

**Comment by MemeHovy** [comment]
use flixel addons 2.11.0
