### ISSUE TITLE
How does the rhythm system work exactly?

### ISSUE THREAD

**Issue by rayanmargham** [ShadowMario/FNF-PsychEngine#12304]
### What is your question?

Hey!

Sorry if this question is stupid I'm quite new to the inner workings of rhythm games in general and this is quite a BROAD question but in the context of FNF and psych engine how does the rhythm system work in a broad summary. (Not talking about the conductor, I mean the input system and all that)

I'm trying to read through the code to understand it more but I only have a tiny understanding of how it works and I understand more of how it's implemented if you get what I mean.

I want to understand the concept for the scope of my own project.

**Comment by jimmyjamescool** [comment]
![15F1C70C-4344-4D43-BFA9-84810B3961E1](https://user-images.githubusercontent.com/131569352/234140959-8accb4df-e592-4786-8254-23fdf38ea439.jpeg)

In psych there’s a shitty antimash where you can’t press “left, up down.” Notes at the same time for some reason.

Accuracy is determined by how close you were to hitting a sick! So it saves those judgements and uses it to calculate your accuracy on a scale of 0% “(you suck!) to 100% (perfect!)”

combo is self explanatory.


If anyone wants to correct me do it

**Comment by MemeHovy** [comment]
@jimmyjamescool in psych it works like etterna, the 0.5 update changed how the timing windows work from vanilla fnf to etterna timing windows

**Comment by MemeHovy** [comment]
sorry not Etterna, I meant Judge four

**Comment by MemeHovy** [comment]
![image](https://user-images.githubusercontent.com/124418090/234145558-52a861da-2bef-459d-bac2-518b8cb68c39.png)

**Comment by jimmyjamescool** [comment]
Huh

**Comment by MemeHovy** [comment]
> Huh

psych engine 0.5 and above use judge four as it's timing windows

**Comment by MemeHovy** [comment]
what you showed in the picture was the vanilla timing windows

**Comment by jimmyjamescool** [comment]
Ik I was just saying “huh never knew that”

they also asked for the vanilla timing windows too so…

**Comment by MemeHovy** [comment]
ohhh, my b

**Comment by rayanmargham** [comment]
Your talking about timing and rating but what about how the notes are generated or how strumlines work in psych?
