### ISSUE TITLE
updated

### ISSUE THREAD

**Issue by Ajwyunsx** [ShadowMario/FNF-PsychEngine#12308]
### What is your question?

Psych engine Will it be updated?

**Comment by MemeHovy** [comment]
yes

**Comment by jimmyjamescool** [comment]
yes

**Comment by Superlogan123** [comment]
probably

**Comment by LokiLaufyeson** [comment]
Hi, Can You Please Tell Me how To Run PyschEngine, I've Downloaded It And Followed The Install Instructions But I Do Not Know How To Run It In Build Version
