### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by LokiLaufyeson** [ShadowMario/FNF-PsychEngine#12309]
### What is your question?

What Is The `Command Line` To Run The Build/Installed Version Of Pysch Engine Using **Haxelib**

**Comment by Jericho2013** [comment]
You mean.. "`Lime test windows`"?

**Comment by Jericho2013** [comment]
To build, use `Lime build windows`

**Comment by Jericho2013** [comment]
you can also change `"`windows"`` to your os
