### ISSUE TITLE
"Set Cam Zoom" script help

### ISSUE THREAD

**Issue by Al-AmeenAdewunmi** [ShadowMario/FNF-PsychEngine#12306]
### Describe your problem here.

So the Set Cam Zoom event wasn't working for some reason and I found out it was because the opponent didn't have any notes beforehand. But I don't want to use notes at a certain part of the song, so I was wondering if there was a script where I can get the same results without having to place notes. The most I could figure out was: `setProperty('camGame.zoom', 1.2)` but then that makes the zoom instant, not smooth. I just need a smooth zoom to 1.2 specifically.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment]
You can do
```lua
function onCreatePost()
    setProperty('camZooming', true)
end
```
And the camera will zoom without needing opponent notes

**Comment by Al-AmeenAdewunmi** [comment]
Oh nice, it worked. Thanks.
