### ISSUE TITLE
how do I re enable the haxe flixel splash screen?

### ISSUE THREAD

**Issue by RonyCommitment** [ShadowMario/FNF-PsychEngine#12310]
### Describe your problem here.

I want to re enable the haxe flixel splash screen that used to pop up when you'd launch older mods and still pops up when  launching vanilla FNF

I wanted to try my hand at replacing the splash screen similarly to what Sonic.EXE 2.0 did with my own version but I can't seem to find a way to even re enable the splash screen.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by JP297** [comment]
in the Main.hx file there should be an option called "skipSplash" set that to false.

**Comment by RonyCommitment** [comment]
Thanks! Any way to directly replace it or would I have to include it in the start screen instead?

**Comment by CaptainBaldi** [comment]
> Thanks! Any way to directly replace it or would I have to include it in the start screen instead?

I'm pretty sure you modify it by altering the `FlxSplash.hx` file in `flixel/system/FlxSplash`
Just make those folders in your source folder, take the `FlxSplash` file from `flixel-dev` and modify it to suit your needs

**Comment by FunkoDev** [comment]
In Main.hx
set skipSplash to false
```haxe
var game = {
	width: 1280, // WINDOW width
	height: 720, // WINDOW height
	initialState: TitleState, // initial game state
	zoom: -1.0, // game state bounds
	framerate: 60, // default framerate
	skipSplash: true, // if the default flixel splash screen should be skipped
	startFullscreen: false // if the game should start at fullscreen mode
};
```
