### ISSUE TITLE
Please give me the source code to create a freeplay like classified.

### ISSUE THREAD

**Issue by tnpr3432** [ShadowMario/FNF-PsychEngine#12315]
### What is your question?

title

**Comment by Unholywanderer** [comment]
no

**Comment by LowoTV** [comment]
why

**Comment by MemeHovy** [comment]
> ### What is your question?
> title

https://github.com/Ash-Stat-SYS/Classified-Source-Public

**Comment by Foxfelix8679** [comment]
?

**Comment by jimmyjamescool** [comment]
![752E50CF-5779-4366-B952-0D4BE632676E](https://user-images.githubusercontent.com/131569352/234140009-4d8af4a4-2c1c-447b-a933-34c0e91577fa.jpeg)
(Shadowmario are you okay or some shit I haven’t seen you close an issue or pr in 4 weeks)

**Comment by Unholywanderer** [comment]
> ![752E50CF-5779-4366-B952-0D4BE632676E](https://user-images.githubusercontent.com/131569352/234140009-4d8af4a4-2c1c-447b-a933-34c0e91577fa.jpeg) (Shadowmario are you okay or some shit I haven’t seen you close an issue or pr in 4 weeks)

He just has better things to do

**Comment by jimmyjamescool** [comment]
> > ![752E50CF-5779-4366-B952-0D4BE632676E](https://user-images.githubusercontent.com/131569352/234140009-4d8af4a4-2c1c-447b-a933-34c0e91577fa.jpeg) (Shadowmario are you okay or some shit I haven’t seen you close an issue or pr in 4 weeks)
> 
> He just has better things to do

mental health break W

**Comment by tnpr3432** [comment]
> > ### What is your question?
> > title
> 
> https://github.com/Ash-Stat-SYS/Classified-Source-Public

thanks

I was looking for a freeplay source code that displays images according to the song but doesn't move the image or song name. And asked for the source code of crassified, which, as far as I know, had code close to it. I didn't explain it. Im sorry.
