### ISSUE TITLE
How can i make platforms float.

### ISSUE THREAD

**Issue by Sliversonic64** [ShadowMario/FNF-PsychEngine#1231]
### Describe your problem here.

I'm trying to make my character stand on a platform that floats kind of like god eater.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
Place the platform under the character???
`setProperty('YourLuaSpriteNameHere.y', value);`

**Comment by Sliversonic64** [comment]
What I mean is having it float like up in down gently with the bf attached to it so he's also floating up and down.
