### ISSUE TITLE
Mac doesn't let open it

### ISSUE THREAD

**Issue by RexArnett473** [ShadowMario/FNF-PsychEngine#12312]
### Describe your bug here.

it will just say i do not have permission to open it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

i try to found a way but still tell me i was not allow to play it

**Comment by tnpr3432** [comment]
FNF can only run on Windows. If your Mac is Intel, you can run Windows using Boot Camp (somewhere in the settings it says if it's Intel or not, but I don't know where it is lol) If not, you can open it using an app called Wine. However, if you decide to use Wine, do so at your own risk.

**Comment by JonnycatMeow** [comment]
https://www.youtube.com/watch?v=sWSySXfR17c here is how to open the application

**Comment by toppatsonic** [comment]
another video if that one didn't work: https://youtu.be/9JWp3ocPDk8
