### ISSUE TITLE
Custom notes having the same texture as the note skin

### ISSUE THREAD

**Issue by KutikiPlayz** [ShadowMario/FNF-PsychEngine#1232]
### Describe your bug here.

When you set a custom note skin in the chart editor, it changes all other note types to that skin as well, which is problematic when it comes to notes that you can't hit. They also appear very small for some reason. Those things don't happen when there isn't a custom note skin, however.

https://user-images.githubusercontent.com/73810550/142780287-4afd4679-6662-44e6-9d9e-8000374d4b09.mp4

Here's a video of me placing some hurt notes and normal notes to show what happens.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not change anything.

**Comment by ShadowMario** [comment]
It's a shitty PR's fault, i reverted the changes.

**Comment by perry389** [comment]
> 그것은 똥 PR의 잘못입니다. 나는 변경 사항을 되돌렸습니다.

In the source code?
