### ISSUE TITLE
all colors are turned into a transparent white

### ISSUE THREAD

**Issue by dulnn** [ShadowMario/FNF-PsychEngine#12321]
### Describe your bug here.

Whenever i use a script that should change colors like this silhouette event it just makes everything transparent white. Ive tried this on the non source code build and it works but on the source code build it doesnt. ive tried a lot but cant get it to work

Script example :
function onCreatePost()
	makeLuaSprite('whitebg', '', 0, 0)
	setScrollFactor('whitebg', 0, 0)
	makeGraphic('whitebg', 3840, 2160, 'ffffff')
	addLuaSprite('whitebg', false)
	setProperty('whitebg.alpha', 0)
	screenCenter('whitebg', 'xy')
end
function onEvent(n, v1, v2)
	if n == 'badapplelol' and string.lower(v1) == 'a' then
		doTweenAlpha('applebadxd69', 'whitebg', 1, v2, 'linear')
		doTweenColor('badapplexd', 'boyfriend', '000000', v2, 'linear')
		doTweenColor('badapplexd1', 'dad', '000000', v2, 'linear')
		doTweenColor('badapplexd2', 'gf', '000000', v2, 'linear')
		doTweenColor('badapplexd6', 'healthBar', '000000', v2, 'linear')
		doTweenColor('badapplexd100', 'iconP1', '000000', v2, 'linear')
		doTweenColor('badapplexd10', 'iconP2', '000000', v2, 'linear')
	end
	if n == 'badapplelol' and string.lower(v1) == 'b' then
		doTweenAlpha('applebadxd', 'whitebg', 0, v2, 'linear')
		doTweenColor('badapplexd3', 'boyfriend', 'FFFFFF', v2, 'linear')
		doTweenColor('badapplexd4', 'dad', 'FFFFFF', v2, 'linear')
		doTweenColor('badapplexd5', 'gf', 'FFFFFF', v2, 'linear')
		doTweenColor('badapplexd7', 'healthBar', 'FFFFFF', v2, 'linear')
		doTweenColor('badapplexd101', 'iconP1', 'FFFFFF', v2, 'linear')
		doTweenColor('badapplexd11', 'iconP2', 'FFFFFF', v2, 'linear')
	end
end
(NOT MY SCRIPT)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes i edited import.hx and main.hx to get compiling to work

**Comment by elchango69** [comment]
lol who cares

**Comment by frantastic24** [comment]
Not a bug
Event values are strings
https://www.lua.org/manual/5.1/manual.html#pdf-tonumber

**Comment by frantastic24** [comment]
`v2` is a string, try using `tonumber(v2)`

**Comment by Gnk1702** [comment]
im having the same issue

**Comment by Gnk1702** [comment]
haxelib set hxcpp 4.2.1
