### ISSUE TITLE
Instant Set Cam Pos event

### ISSUE THREAD

**Issue by NavaGaming** [ShadowMario/FNF-PsychEngine#12324]
### Describe your problem here.

Is there a way to code Set Cam Pos event but with duration as value2? (Like how long it takes to Set position of camera)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by VoidedBattery** [comment]
If something's instant then it could work with

`setProperty('camFollowPos.x', 640)`

**Comment by NavaGaming** [comment]
Oh, right.. That could work, silly me
