### ISSUE TITLE
health bar border stuff

### ISSUE THREAD

**Issue by Gurudevsing** [ShadowMario/FNF-PsychEngine#12329]
### Describe your problem here.

![Screenshot (3)](https://user-images.githubusercontent.com/87480185/234959781-868c849c-285a-4aa8-b0a2-ae2989c66927.png)
you can see below the right corner arrow go through the health bar. how to fix this

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MINCREFAT** [comment]
idk how to fix this, i have not seen this happen before

**Comment by Gurudevsing** [comment]
> idk how to fix this, i have not seen this happen before
oh 👍

**Comment by ROCK201888** [comment]
setObjectOrder('your new health bar name', getObjectOrder('healthBar')-1);

**Comment by Gurudevsing** [comment]
> setObjectOrder('your new health bar name', getObjectOrder('healthBar')-1);

cool
