### ISSUE TITLE
locking weeks doesnt work

### ISSUE THREAD

**Issue by dolpshy** [ShadowMario/FNF-PsychEngine#12326]
### Describe your bug here.

my friend tried to lock the week and then the epic error happened with storymenustate lines 273 and 275

### Command Prompt/Terminal logs (if existing)

```bash
https://cdn.discordapp.com/attachments/1094743123042775073/1100905823842082886/image.png
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Username2120** [comment]
Did you remove all base weeks and then hide the one you're trying to lock from story mode? this error only really comes up when the story menu has no weeks to load.
