### ISSUE TITLE
Multiple Custom Death Screens

### ISSUE THREAD

**Issue by Kirsenal** [ShadowMario/FNF-PsychEngine#12328]
### Describe your problem here.

So I have the script that allows for custom game over screens, however I am making a mod with multiple songs and multiple playable characters, and it seems that when I have the script, it only does that game over no matter what character I am using. How do I make it to where it ONLY does it when using that character, and for bf it still does his normal one?

I would really love a response because this is slightly infuriating. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
rename the script to the name of your character and put it in the characters folder with your character

**Comment by elchango69** [comment]
go touch grass

**Comment by elchango69** [comment]
please

**Comment by Kirsenal** [comment]
> rename the script to the name of your character and put it in the characters folder with your character json

thank you, you are a lifesaver
