### ISSUE TITLE
Controls.hx:514: characters 9-13 : Pattern variables must be lower-case   But this never ask to me in other line 

### ISSUE THREAD

**Issue by Noel3454565FNF** [ShadowMario/FNF-PsychEngine#12323]
### Describe your problem here.

im trying to add more detected keys in Psych Engine but something happend like out of nowhere, i never seen this before and this not show in other lines
<img width="960" alt="image" src="https://user-images.githubusercontent.com/58745415/234703197-862f4477-ea15-4c69-838f-453892852ae8.png">

this is the line, you can see just above the other line i wrote but idk why its not returning error
<img width="960" alt="image" src="https://user-images.githubusercontent.com/58745415/234704032-da85e719-fe0a-482d-b7d2-3d83ce8abfc7.png">

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, Controls.hx (i added some detected inputs) and ControlsSubState.hx (i added the keys here to for later))

**Comment by BernardoGP4504** [comment]
Maybe the variable for APLR wasn't set at the start of the file, or wasn't set properly
