### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by talopakola** [ShadowMario/FNF-PsychEngine#12331]
### Describe your bug here.

Hello, I formatted my computer and now I'm having to compile the psych engine again, but when I try, this appears
(Google Translate was used)

### Command Prompt/Terminal logs (if existing)

```bash
source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
C:/Users/MyName/Desktop/FNF-PsychEngine-main/.haxelib/flixel/5,3,0/flixel/animation/FlxAnimation.hx:226: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
C:/Users/MyName/Desktop/FNF-PsychEngine-main/.haxelib/flixel-addons/3,1,0/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'Object'
source/FunkinLua.hx:2196: lines 2196-2199 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2196: lines 2196-2199 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object'
source/PlayState.hx:584: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:584: characters 25-35 : ... For function argument 'Object'
source/PlayState.hx:2388: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2388: characters 23-29 : ... For function argument 'Object'
source/PlayState.hx:2389: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2389: characters 23-83 : ... For function argument 'Object'
source/PlayState.hx:1781: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1781: characters 25-37 : ... For function argument 'Object'
source/PlayState.hx:1828: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1828: characters 25-34 : ... For function argument 'Object'
source/PlayState.hx:1899: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1899: characters 25-36 : ... For function argument 'Object'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1359: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1359: characters 24-30 : ... For function argument 'Object'
source/editors/ChartingState.hx:2196: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/Users/MyName/Desktop/FNF-PsychEngine-main/.haxelib/flixel/5,3,0/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
source/TitleState.hx:711: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:713: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:717: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by RCrewmate** [comment]
im having this issue too, i don't know how to fix it either

**Comment by NexIsDumb** [comment]
New flixel version moved some stuff

**Comment by talopakola** [comment]
How do I do it? Yes, I'm very stupid in these things, the only thing I know is programming and even then I'm not good .-.


(I used google translate so sorry for any mistakes)

**Comment by talopakola** [comment]
Forget it, I managed to do it, I'll test it and see if it works

**Comment by talopakola** [comment]
`C:/Users/Myname/Desktop/FNF-PsychEngine-main/.haxelib/flixel-addons/3,1,0/flixel/addons/text/FlxTypeText.hx:8: characters 8-29 : Type not found : flixel.sound.FlxSound
C:/Users/Myname/Desktop/FNF-PsychEngine-main/.haxelib/flixel-addons/3,1,0/flixel/addons/text/FlxTypeText.hx:77: characters 26-34 : Type not found : FlxSound
source/CoolUtil.hx:19: lines 19-154 : ... Defined in this class
C:/Users/Myname/Desktop/FNF-PsychEngine-main/.haxelib/flixel-addons/3,1,0/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/DialogueBox.hx:144: characters 16-22 : flixel.addons.text.FlxTypeText has no field sounds
source/DialogueBox.hx:244: characters 16-25 : flixel.addons.text.FlxTypeText has no field resetText
source/DialogueBox.hx:245: characters 16-21 : flixel.addons.text.FlxTypeText has no field start
source/DialogueBox.hx:246: characters 16-32 : flixel.addons.text.FlxTypeText has no field completeCallback
source/DialogueBox.hx:223: characters 18-22 : flixel.addons.text.FlxTypeText has no field skip
C:/Users/Myname/Desktop/FNF-PsychEngine-main/.haxelib/flixel-addons/3,1,0/flixel/addons/transition/FlxTransitionableState.hx:81: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field`

I hate my life

**Comment by RowanSkie** [comment]
Check issue #12334, we have the same problem and they suggested a version of flixel and flixel-addons.

**Comment by NexIsDumb** [comment]
> Check issue #12338, we have the same problem and they suggested a version of flixel and flixel-addons.

Yeah use that

**Comment by NexIsDumb** [comment]
Also if you wanna compile using that latest version, someone made a fix: #12334

**Comment by BeastlyGabi** [comment]
downgrade to haxe 4.2.5, it's a haxe issue

**Comment by talopakola** [comment]
I will close this problem in 7 days :/

**Comment by NexIsDumb** [comment]
> I will close this problem in 7 days :/

It didnt work?
It worked for me
What versions did you use in the end

**Comment by talopakola** [comment]
> > Vou fechar este problema em 7 dias :/
> 
> Não funcionou? Funcionou para mim Quais versões você usou no final Verifique-as no terminal

haxe: 4.2.5
flixel: 4.11.0
flixel-addons: 2.11.0
and it still doesn't work :/

**Comment by NexIsDumb** [comment]
> > > Vou fechar este problema em 7 dias :/
> 
> > 
> 
> > Não funcionou? Funcionou para mim Quais versões você usou no final Verifique-as no terminal
> 
> 
> 
> haxe: 4.2.5
> 
> flixel: 4.11.0
> 
> flixel-addons: 2.11.0
> 
> and it still doesn't work :/

Hmm, did you install those libraries inside the psych engine folder (hmm.json method) or did you install them in the main haxe folder (old psych engine method)

**Comment by NexIsDumb** [comment]
> I installed it in the main folder of the haxe :/
> 
> 
> 
> > > > > Vou fechar este problema em 7 dias :/
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Não funcionou? Funcionou para mim Quais versões você usou no final Verifique-as no terminal
> 
> > > 
> 
> > > 
> 
> > > haxe: 4.2.5
> 
> > > flixel: 4.11.0
> 
> > > flixel-addons: 2.11.0
> 
> > > and it still doesn't work :/
> 
> > 
> 
> > Hmm, did you install those libraries inside the psych engine folder (hmm.json method) or did you install them in the main haxe folder (old psych engine method)
> 
> 
> 
> I installed it in the main folder of the haxe :/
> 
> 

Hmm, see any .haxelib folder inside psych engine folder?
If you see it delete it and retry

**Comment by talopakola** [comment]
> > Instalei na pasta principal do haxe :/
> > > > > > Vou fechar este problema em 7 dias :/
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > Não funcionou? Funcionou para mim Quais versões você usou no final Verifique-as no terminal
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > haxe: 4.2.5
> > 
> > 
> > > > flexil: 4.11.0
> > 
> > 
> > > > flixel-addons: 2.11.0
> > 
> > 
> > > > e ainda não funciona :/
> > 
> > 
> > > 
> > 
> > 
> > > Hmm, você instalou essas bibliotecas dentro da pasta psych engine (método hmm.json) ou você as instalou na pasta haxe principal (antigo método psych engine)
> > 
> > 
> > Instalei na pasta principal do haxe :/
> 
> Hmm, veja alguma pasta .haxelib dentro da pasta psych engine? Se você vê-lo excluí-lo e tentar novamente

it worked lol

**Comment by NexIsDumb** [comment]
> > > Instalei na pasta principal do haxe :/
> 
> > > > > > > Vou fechar este problema em 7 dias :/
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > Não funcionou? Funcionou para mim Quais versões você usou no final Verifique-as no terminal
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > haxe: 4.2.5
> 
> > > 
> 
> > > 
> 
> > > > > flexil: 4.11.0
> 
> > > 
> 
> > > 
> 
> > > > > flixel-addons: 2.11.0
> 
> > > 
> 
> > > 
> 
> > > > > e ainda não funciona :/
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Hmm, você instalou essas bibliotecas dentro da pasta psych engine (método hmm.json) ou você as instalou na pasta haxe principal (antigo método psych engine)
> 
> > > 
> 
> > > 
> 
> > > Instalei na pasta principal do haxe :/
> 
> > 
> 
> > Hmm, veja alguma pasta .haxelib dentro da pasta psych engine? Se você vê-lo excluí-lo e tentar novamente
> 
> 
> 
> it worked lol

I knew it
Thats the problem with hmm new method
Seems easier but in the end its broken lol

**Comment by talopakola** [comment]
lol

**Comment by HeckerDe** [comment]
just downgrade the flixel think just flixel and the flixel-addons it's now working on me

**Comment by NexIsDumb** [comment]
> just downgrade the flixel think just flixel and the flixel-addons it's now working on me

What are your errors

**Comment by OperDal** [comment]
whats the old way

**Comment by NexIsDumb** [comment]
> whats the old way

Installing haxe libs in Haxe installed folder instead of Psych Engine folder

**Comment by OperDal** [comment]
> 

how im kinda dumb

**Comment by NexIsDumb** [comment]
> > 
> 
> how im kinda dumb

there are tons of tutorials on youtube
the thing that only changes is that u have to set the version of these libs like the ones in the hmm.json file in #12366

**Comment by OperDal** [comment]
> > > 
> > 
> > 
> > how im kinda dumb
> 
> there are tons of tutorials on youtube the thing that only changes is that u have to set the version of these libs like the ones in the hmm.json file in #12366

can you like give me a youtube link to one because you worded it wrong when you explained the old way

**Comment by NexIsDumb** [comment]
> > > > 
> 
> > > 
> 
> > > 
> 
> > > how im kinda dumb
> 
> > 
> 
> > there are tons of tutorials on youtube the thing that only changes is that u have to set the version of these libs like the ones in the hmm.json file in #12366
> 
> 
> 
> can you like give me a youtube link to one because you worded it wrong when you explained the old way

Uh I didn't worded wrong bruh
Anyways, you'll understand what I was trying to say: https://youtu.be/xVSR8mzPeh4
THOUGH the library versions must be like the ones in that hmm.json in that pull request i mentioned before

**Comment by AmongUs779** [comment]
These are my libraries versions and it works fine with these (FOR 0.7.3):
flixel-addons: 3.2.1
flixel-demos: 2.9.3
flixel-templates: 2.6.6
flixel-tools: 1.5.1
flixel-ui: 2.5.0
flixel: 5.6.2
hscript: 2.5.0
hxCodec: 2.6.1
hxcpp: 4.2.1
lime-samples: 7.0.0
lime: 8.0.2
openfl: 9.3.2
SScript: 21.0.0
