### ISSUE TITLE
Unknow error of hx files

### ISSUE THREAD

**Issue by Yetielcodificador** [ShadowMario/FNF-PsychEngine#12337]
### Describe your bug here.

This is an issue of hx when i try to load week 7, heres is the error:
![Captura de pantalla 2023-04-28 211642](https://user-images.githubusercontent.com/132117778/235281060-efebdb61-256f-4d6e-975d-1810d47a0e10.png)

maybe is by an event but i din't touch the hx file and i din't know where are placed im talking of a mod that im creating and week7 failed to load i dont know, please fix this

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2614)
PlayState.hx (line 2570)
PlayState.hx (line 1086)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i dint edit nothing of .hx files.

**Comment by Username2120** [comment]
all this means is that something that was called returned null so the game crashed, the only reason all of the hx files are showing up is because those are where the last commands were called prior to the crash happening.

**Comment by Yetielcodificador** [comment]
maybe the error is caused because of some .json or code archives, maybe its my fnf characters that is producing a error in week 7 songs, because i made it with a spritesheet and xml generator and not animate becuase i am a beginner and in fact I uninstall animate because it takes up space on my laptop that i made tthis mod

**Comment by Username2120** [comment]
the sprite sheet generator shouldnt cause any problems. so it might just be you character file (the .json file)

**Comment by Yetielcodificador** [comment]
if i remove the .json then weres the modded character in his week?!?!?!

**Comment by Username2120** [comment]
odd, what version is it?

**Comment by Yetielcodificador** [comment]
the version of pysch of my mod is 0.6.3

**Comment by Username2120** [comment]
is your stage hard coded or through Lua?

**Comment by Yetielcodificador** [comment]
a little bit but its only scripts that make hard the week

**Comment by Username2120** [comment]
then i guess im just as confused as you are. and your sure the json is fine?

**Comment by Yetielcodificador** [comment]
the character and the week 7 jsons are just fine maybe....
Thats it im gonna transfer my mod files to a Clean copy of the engine
