### ISSUE TITLE
Screen zoom randomly broke

### ISSUE THREAD

**Issue by Kirsenal** [ShadowMario/FNF-PsychEngine#12332]
### Describe your problem here.

ooookay so I have been having a lot of trouble with Psych Engine and had to put a lot of these things; so this time, I started using the "Add Camera Zoom" event, which the first few days it mimicked how at the start of every section, it does that quick zoom then zooms back out. I thought this was cool, but I tried using it again today and for some reason now it doesn't do that quick in and out motion, but instead only zooms in and stays like that. It even says in the description that it does it in MILF, so I looked in MILF and lo and behold it does what it's supposed to, why has it randomly stopped working??

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Leviohso** [comment]
Putting "setProperty('camZooming', true)" in the on create function fixed it for me.
I'm not sure what turns it off, but you can force it back on.

**Comment by MemeHovy** [comment]
> Putting "setProperty('camZooming', true)" in an on create function fixed it for me.
> I'm not sure what turns it off, but you can force it back on.
> (In a Lua file)

you do the same thing but change true to false

**Comment by Leviohso** [comment]
> > Putting "setProperty('camZooming', true)" in an on create function fixed it for me.
> > I'm not sure what turns it off, but you can force it back on.
> > (In a Lua file)
> 
> you do the same thing but change true to false

I know changing it to false will turn it off pffft but what I'm talking about is I don't know what in the source code makes it turn off for specific songs. The only thing I see in Playstate is that it gets set off after the song ends, (and when the variable is created I think) and doesn't get turned back on until the opponent hits their first note. (For some reason???) (And unless you're playing the tutorial)
So I think the idea is that the camera isn't supposed to bump until the singing starts (which would normally start with the opponent singing) and it in the process makes the camera zoom event not bump but rather stay zoomed in.
