### ISSUE TITLE
Color Tween Not Working

### ISSUE THREAD

**Issue by RCrewmate** [ShadowMario/FNF-PsychEngine#12333]
### Describe your bug here.

For some reason when I use the doTweenColor in lua to make BF and GF completely dark for a few seconds, then turn them to being visible afterwards, the tween makes them completely invisible when they're supposed to be dark, and half transparent when they're supposed to be visible. I don't know what happened or what I did because it was working fine before, it just suddenly doesn't work anymore and does this.

Here's the code I used incase it's wrong:
Dark: doTweenColor('bfcolor1', 'boyfriend', '0xFF0000', 0.2, 'circIn')
Visible: doTweenColor('bfcolor2', 'boyfriend', '0xFFFFFF', 1, 'linear')

### Are you modding a build from source or with Lua?

Source and Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

A few things relating to notes and icons, but nothing about tweens or colors

**Comment by CaptainBaldi** [comment]
missing 2 00's and 2 FF's

**Comment by RCrewmate** [comment]
i did what you said, and now bf and gf arent turning dark at all anymore
theyre just half transparent the whole time now

**Comment by RCrewmate** [comment]
> missing 2 00's and 2 FF's
this just made bf and gf half invisible the whole time

**Comment by RCrewmate** [comment]
> missing 2 00's and 2 FF's

this made bf and gf half invisible the whole time

**Comment by RCrewmate** [comment]
i compiled psych engine and it turns out that the doTweenColor changing the alpha instead of the color is a compiling issue
not sure what i have to install or change to fix this however

**Comment by RCrewmate** [comment]
i finally found out how to fix it, and if anyone else is reading this with the same issue, this is how you fix it.

run these commands into command prompt:
haxelib remove hxcpp
haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp

after that, compile your mod.
if it asks you to do something (as it did for me, but i forgot what it was) just enter "yes"
after your mod compiles, the bug should be fixed and tween color will work again

**Comment by xernexx** [comment]
thank you goat
