### ISSUE TITLE
"Uncaught Error" message

### ISSUE THREAD

**Issue by jearo1105** [ShadowMario/FNF-PsychEngine#12346]
### Describe your problem here.

After downloading a mod and attempting to play in story mode, I got a pop up message saying "Uncaught Error: [file_contents,assets/data/21/21.json]" Am I missing files or did I not download the files correctly? Thanks.
<img width="1348" alt="Screenshot 2023-04-30 at 12 31 32 PM" src="https://user-images.githubusercontent.com/132227858/235373279-e2c2f492-1dfa-4aa3-91d2-2d6270748f3a.png">

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by mcagabe19** [comment]
issue from chart file or chart not found thats all

**Comment by Stefan2008Git** [comment]
> issue from chart file or chart not found thats all

You need a correct difficulty name and song too to work or he is litterally need to edit weekname.json thing LOL

**Comment by mcagabe19** [comment]
> > issue from chart file or chart not found thats all
> 
> You need a correct difficulty name and song too to work or he is litterally need to edit weekname.json thing LOL

agreed
