### ISSUE TITLE
How do I play a video before a song on SOURCE

### ISSUE THREAD

**Issue by SrBagel** [ShadowMario/FNF-PsychEngine#12344]
### Describe your problem here.

I've looked everywhere and I can't find a tutorial on making a video play on source (not LUA) this is probably a repeat but I need help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing important

**Comment by SrBagel** [comment]
Never mind i figured it out [you do it similar to dialogue but you put this instead startVideo('your_video_name');]

**Comment by BygainYT** [comment]
hey dude could you tell me how to do it cause ive been looking and i cant find a working script
