### ISSUE TITLE
un-hard coded splash screen and credits menu

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#1234]
### What feature do you want to get added on the base engine?

For the splash screen stuff, it would be similar to the intro text, but its with the "this is a mod of" and "friday-night-funkin" text. so you could change it to the name of your mod.

The credits menu could just be ("name", "icon.png", "www.link.com")  in a txt or json file. so people can be credited in the game itself.

**Comment by swordcube** [comment]
in the source code, it appears as if the credits can be added without source, i don't know how the txt file is formatted, but i'd assume it's possible

you have to compile source to use it, unhardcoded splash screen would be nice

**Comment by ShadowMario** [comment]
I don't want to do it.
