### ISSUE TITLE
Health bar and note splashes  stuff

### ISSUE THREAD

**Issue by Gurudevsing** [ShadowMario/FNF-PsychEngine#12347]
### Describe your problem here.

i have two questions
1. how to increase height and width of health bar and health bar color
2. you can see below note splashes don't work properly

https://user-images.githubusercontent.com/87480185/235373654-846c7dbe-f366-41bd-86ec-ba0d2826532e.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by BernardoGP4504** [comment]
1. You can set those values up with `setProperty()` (except color)
2. The XML for them does not have the right animation names. Name them exacly as the original XML from psych

**Comment by Gurudevsing** [comment]
> 1. You can set those values up with `setProperty()` (except color)

setProperty()..... what are the value to put idk . help me with that

**Comment by BernardoGP4504** [comment]
> > 1. You can set those values up with `setProperty()` (except color)
> 
> setProperty()..... what are the value to put idk . help me with that

It's 2 values, use it like this for example:
```lua
setProperty('healthBar.visible', false)
```
> _the code above makes the healthbar go invisible btw_

The first value is whatever you want to set. If the value your setting doesn't work, try using the other "setProperty" functions or check if it's written correctly.
The second value is what your going to set it to.

_Check the wiki for this (https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Value-Setting-and-Getting-Functions#setpropertyvariablestring-valuedynamic)_
