### ISSUE TITLE
Can't compile the game

### ISSUE THREAD

**Issue by RBeansDev** [ShadowMario/FNF-PsychEngine#12356]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/117064691/235703860-1c35aa4f-ccc4-4ead-b78e-d8dc72620278.png)
this.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited Playstate and that's pretty much it

**Comment by Stefan2008Git** [comment]
Probably a issue. You need a install the old one

**Comment by RBeansDev** [comment]
I installed flixel version 4.11.x but it didn't work

Help

**Comment by Stefan2008Git** [comment]
Try this version: ``haxelib install hxCodec 2.5.1``

**Comment by RBeansDev** [comment]
> Try this version: `haxelib install hxCodec 2.5.1`

I already tried it, unfortunately no results
