### ISSUE TITLE
Compile issue Field

### ISSUE THREAD

**Issue by XenoEntity** [ShadowMario/FNF-PsychEngine#12359]
### Describe your problem here.

C:/HaxeToolkit/haxe/lib/flixel-addons/3,1,0/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/DialogueBox.hx:144: characters 16-22 : flixel.addons.text.FlxTypeText has no field sounds
source/DialogueBox.hx:244: characters 16-25 : flixel.addons.text.FlxTypeText has no field resetText
source/DialogueBox.hx:245: characters 16-21 : flixel.addons.text.FlxTypeText has no field start
source/DialogueBox.hx:246: characters 16-32 : flixel.addons.text.FlxTypeText has no field completeCallback
source/DialogueBox.hx:223: characters 18-22 : flixel.addons.text.FlxTypeText has no field skip
C:/HaxeToolkit/haxe/lib/flixel-addons/3,1,0/flixel/addons/transition/FlxTransitionableState.hx:81: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by RBeansDev** [comment]
First remove the recent versions of Flixel and Flixel-addons, using 
haxelib remove flixel
haxelib remove flixel-addons
Then install an older release of the libraries mentioned:
haxelib install flixel 4.11.0
haxelib install flixel-addons 2.11.0.

**Comment by KenjiOrogen** [comment]
> First remove the recent versions of Flixel and Flixel-addons, using haxelib remove flixel haxelib remove flixel-addons Then install an older release of the libraries mentioned: haxelib install flixel 4.11.0 haxelib install flixel-addons 2.11.0.

Error: "C:/HaxeToolkit/haxe/lib/hxCodec/2,6,1/include.xml" contains invalid XML data ??? i dint even mess with it

**Comment by XenoEntity** [comment]
Thank you so much @RBeansDev

**Comment by RBeansDev** [comment]
> Thank you so much @RBeansDev

No problems. If you still have compiler issues, go out to me
