### ISSUE TITLE
GUIDE TO FIXING THE NEW PSYCH COMPILING ISSUE!!

### ISSUE THREAD

**Issue by KenjiOrogen** [ShadowMario/FNF-PsychEngine#12354]
### BUG FIXES ###

> you might be greeted with a shit-ton of errors related to ```FlxSound``` and ```System``` if you're using the latest version of ```Psych Engine``` since it has gotten some new shit.

### CMD PROMPT STUFF ###

1. in a new CMD prompt Write ---  ```haxelib install flixel-addons 2.11.0``` as it will install the correct Flixel-Addons needed to compile

2. in that same CMD Prompt Write --- ```haxelib install flixel 4.11.0``` as it will install the correct HaxeFlixel Version needed to compile

> if you still have errors and remember that you updated the version for flixel and or flixel-addons

3. _in the CMD Prompt Write --- ```haxelib set flixel 4.11.0``` and ```haxelib set flixel-addons 2.11.0```_

>you may get an error along the lines of ```Error: "C:/HaxeToolkit/haxe/lib/hxCodec/2,6,1/include.xml" contains invalid XML data```  just remove hxCodec and reinstall it with the command `haxelib remove hxCodec` then `haxelib install hxCodec`

**hope this helps!**

**Comment by PDL2CGamejolt** [comment]
Run haxelib run lime build windows --app-version="4.0.0-4[8](https://github.com/PDL2CGamejolt/FNFPaytenEditionNEW/actions/runs/4865934776/jobs/8676876820#step:6:9)65[9](https://github.com/PDL2CGamejolt/FNFPaytenEditionNEW/actions/runs/4865934776/jobs/8676876820#step:6:10)34776"
C:/haxelib/flixel-addons/3,1,0/flixel/addons/text/FlxTypeText.hx:8: characters 8-29 : Type not found : flixel.sound.FlxSound
C:/haxelib/flixel-addons/3,1,0/flixel/addons/text/FlxTypeText.hx:77: characters 26-34 : Type not found : FlxSound
Error: Process completed with exit code 1.

**Comment by RBeansDev** [comment]
> Run haxelib run lime build windows --app-version="4.0.0-4[8](https://github.com/PDL2CGamejolt/FNFPaytenEditionNEW/actions/runs/4865934776/jobs/8676876820#step:6:9)65[9](https://github.com/PDL2CGamejolt/FNFPaytenEditionNEW/actions/runs/4865934776/jobs/8676876820#step:6:10)34776" C:/haxelib/flixel-addons/3,1,0/flixel/addons/text/FlxTypeText.hx:8: characters 8-29 : Type not found : flixel.sound.FlxSound C:/haxelib/flixel-addons/3,1,0/flixel/addons/text/FlxTypeText.hx:77: characters 26-34 : Type not found : FlxSound Error: Process completed with exit code 1.

Use an older version of flixel and flixel-addons

**Comment by KenjiOrogen** [comment]
Did you do the steps, in a CMD Window?

**Comment by KenjiOrogen** [comment]
> it happens this when i put lime test windows
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1810: characters 22-28 : lime.utils.Float32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1810: characters 22-28 : ... For function argument 'params'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1815: characters 22-28 : lime.utils.Float32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1815: characters 22-28 : ... For function argument 'params'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1831: characters 24-30 : lime.utils.UInt32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1831: characters 24-30 : ... For function argument 'params'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1836: characters 24-30 : lime.utils.Int32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1836: characters 24-30 : ... For function argument 'params'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1841: characters 24-30 : lime.utils.Int32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:1841: characters 24-30 : ... For function argument 'params'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:143: characters 5-23 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.OpenGLES2RenderContext
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:144: characters 5-23 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.WebGLRenderContext
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:150: characters 6-24 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.OpenGLES3RenderContext
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeWindow.hx:151: characters 6-25 : lime._internal.backend.native.NativeOpenGLRenderContext should be lime.graphics.WebGL2RenderContext
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4740: characters 74-75 : lime.utils.Float32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4740: characters 74-75 : ... For function argument 'v'
> export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
> C:/HaxeToolkit/haxe/lib/flixel/5,3,0/flixel/animation/FlxAnimation.hx:226: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
> export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
> source/FreeplayState.hx:341: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/FreeplayState.hx:341: characters 25-31 : ... For function argument 'Object'
> source/OldAlphabet.hx:328: characters 6-50 : flixel.sound.FlxSound should be flixel.system.FlxSound
> source/OldAlphabet.hx:230: characters 4-48 : flixel.sound.FlxSound should be flixel.system.FlxSound
> source/PauseSubState.hx:86: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/PauseSubState.hx:86: characters 23-33 : ... For function argument 'Object'
> source/PlayState.hx:2572: characters 20-25 : flixel.sound.FlxSound has no field pitch
> source/PlayState.hx:1562: characters 21-26 : flixel.sound.FlxSound has no field pitch
> C:/HaxeToolkit/haxe/lib/flixel-addons/3,1,0/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
> source/Character.hx:302: characters 101-106 : flixel.sound.FlxSound has no field pitch
> source/PlayState.hx:623: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/PlayState.hx:623: characters 25-35 : ... For function argument 'Object'
> source/PlayState.hx:3121: characters 20-25 : flixel.sound.FlxSound has no field pitch
> source/FunkinLua.hx:615: characters 10-15 : Class<llua.LuaL> has no field error
> source/FunkinLua.hx:633: characters 10-15 : Class<llua.LuaL> has no field error
> source/FunkinLua.hx:639: characters 10-15 : Class<llua.LuaL> has no field error
> source/FunkinLua.hx:687: characters 10-15 : Class<llua.LuaL> has no field error
> source/FunkinLua.hx:693: characters 10-15 : Class<llua.LuaL> has no field error
> source/FunkinLua.hx:729: lines 729-732 : Int should be Bool
> source/FunkinLua.hx:729: lines 729-732 : ... For function argument 'f'
> source/FunkinLua.hx:2293: lines [2293-2296](tel:2293-2296) : flixel.sound.FlxSound should be flixel.system.FlxSound
> source/FunkinLua.hx:2293: lines [2293-2296](tel:2293-2296) : ... For function argument 'value'
> source/PlayState.hx:2675: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/PlayState.hx:2675: characters 23-29 : ... For function argument 'Object'
> source/PlayState.hx:2676: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/PlayState.hx:2676: characters 23-83 : ... For function argument 'Object'
> source/PlayState.hx:2025: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/PlayState.hx:2025: characters 25-37 : ... For function argument 'Object'
> source/PlayState.hx:2029: characters 25-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/PlayState.hx:2029: characters 25-29 : ... For function argument 'Object'
> source/PlayState.hx:2033: characters 25-32 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/PlayState.hx:2033: characters 25-32 : ... For function argument 'Object'
> source/PlayState.hx:2083: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/PlayState.hx:2083: characters 25-34 : ... For function argument 'Object'
> source/PlayState.hx:2159: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/PlayState.hx:2159: characters 25-36 : ... For function argument 'Object'
> source/PlayState.hx:2606: characters 20-25 : flixel.sound.FlxSound has no field pitch
> source/PlayState.hx:4906: characters 81-86 : flixel.sound.FlxSound has no field pitch
> source/PlayState.hx:3519: characters 81-86 : flixel.sound.FlxSound has no field pitch
> source/PlayState.hx:5494: characters 20-25 : flixel.sound.FlxSound has no field pitch
> source/flixel/system/FlxSound.hx:734: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/flixel/system/FlxSound.hx:734: characters 21-25 : ... For function argument 'sound'
> source/flixel/system/FlxSound.hx:737: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/flixel/system/FlxSound.hx:737: characters 15-19 : ... For function argument 'sound'
> source/editors/ChartingState.hx:1421: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/editors/ChartingState.hx:1421: characters 24-30 : ... For function argument 'Object'
> source/editors/ChartingState.hx:2254: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
> source/editors/ChartingState.hx:2091: characters 23-28 : flixel.sound.FlxSound has no field pitch
> source/editors/ChartingState.hx:2092: characters 21-26 : flixel.sound.FlxSound has no field pitch
> C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
> C:/HaxeToolkit/haxe/lib/flixel/5,3,0/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
> source/TitleState.hx:842: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
> source/TitleState.hx:844: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
> source/TitleState.hx:848: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2313: characters 36-42 : lime.utils.Int32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2313: characters 36-42 : ... For function argument 'params'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2319: characters 36-42 : lime.utils.Float32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/_internal/backend/native/NativeOpenGLRenderContext.hx:2319: characters 36-42 : ... For function argument 'params'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4617: characters 63-64 : lime.utils.Float32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4617: characters 63-64 : ... For function argument 'v'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4631: characters 64-65 : lime.utils.Int32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4631: characters 64-65 : ... For function argument 'v'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4639: characters 66-67 : lime.utils.UInt32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4639: characters 66-67 : ... For function argument 'v'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4655: characters 70-71 : lime.utils.Float32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4655: characters 70-71 : ... For function argument 'v'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4669: characters 71-72 : lime.utils.Int32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4669: characters 71-72 : ... For function argument 'v'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4678: characters 73-74 : lime.utils.UInt32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4678: characters 73-74 : ... For function argument 'v'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4696: characters 80-81 : lime.utils.Float32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4696: characters 80-81 : ... For function argument 'v'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4712: characters 81-82 : lime.utils.Int32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4712: characters 81-82 : ... For function argument 'v'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4721: characters 83-84 : lime.utils.UInt32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4721: characters 83-84 : ... For function argument 'v'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4757: characters 75-76 : lime.utils.Int32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4757: characters 75-76 : ... For function argument 'v'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4767: characters 77-78 : lime.utils.UInt32Array should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/graphics/WebGL2RenderContext.hx:4767: characters 77-78 : ... For function argument 'v'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/math/ColorMatrix.hx:117: characters 12-17 : lime.math.ColorMatrix should be Null<lime.utils.ArrayBufferView>
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/math/ColorMatrix.hx:117: characters 12-17 : ... For optional function argument 'view'
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/media/OpenALAudioContext.hx:573: characters 3-40 : lime.media.openal.ALBuffer should be Int
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/text/harfbuzz/HBBlob.hx:47: characters 3-48 : Float should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/text/harfbuzz/HBBlob.hx:56: characters 3-57 : Float should be lime.utils.DataPointer
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/math/Matrix4.hx:235: characters 12-17 : lime.math.Matrix4 should be Null<lime.utils.ArrayBufferView>
> C:/HaxeToolkit/haxe/lib/lime/7,8,0/src/lime/math/Matrix4.hx:235: characters 12-17 : ... For optional function argument 'view'

Did you happen to do the steps correctly?

**Comment by CJ77GT6R** [comment]
prob no, i have visual studio 2022, i think i missing something
