### ISSUE TITLE
remove backspace to exit chart editor, or atleast have a prompt to save

### ISSUE THREAD

**Issue by dude0216** [ShadowMario/FNF-PsychEngine#12364]
### What feature do you want to get added on the **base** engine?

simple enough

### To test your sight, and reliability, please select the option of what should NOT be requested.

Actual feedback

**Comment by NightmaresPlayz** [comment]
isnt there already a save chart button

**Comment by wubbzyfan** [comment]
bro tip: if you go back into chart editor via the menu it sends you to, your chart will be there (if you enter another song though it will be wiped)

**Comment by ShadowMario** [comment]
Invalid due to sight and reliability test fail
