### ISSUE TITLE
The cutscenes just crashes the game

### ISSUE THREAD

**Issue by toppatsonic** [ShadowMario/FNF-PsychEngine#12362]
### Describe your bug here.

basically used the lua script to play cutscenes, and then it just crashes when the cutscene is about to play

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, all I did is added the .Lua file and the mp4 file and then it just crashes

**Comment by CaptainBaldi** [comment]
prob somethin wrong with ur mp4 then

**Comment by toppatsonic** [comment]
thanks for a bit of help
