### ISSUE TITLE
neko.exe stopped working :(

### ISSUE THREAD

**Issue by MagnumPoland** [ShadowMario/FNF-PsychEngine#12360]
### Describe your bug here.

when i try to compile source code of Psych Engine, neko.exe from nowhere is stop working... I notice that on (probably) every engine i try to compile, neko just stops working... I don't know why. I updated Haxe and Neko and it's not changing anything, i can't find any similar issue related to mine. Maybe I just installed something wrong?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited MainMenuState.hx, but I noticed that doesn't matter if I edit something or not in source

**Comment by SrBagel** [comment]
I had a similar problem try reinstalling Haxe and Neko

**Comment by MagnumPoland** [comment]
> I had a similar problem try reinstalling Haxe and Neko

Thank you for your response, but this doesn't work :(
I'll try rn reinstalling everything (that is Windows SDK, Haxe, Neko and other components)
Maybe it's stupid, but I hope that'll work.

**Comment by ender69funk** [comment]
conclusion, do not download hmm and do not update haxe (it doesn't work for me either)

**Comment by NexIsDumb** [comment]
> conclusion, do not download hmm and do not update haxe (it doesn't work for me either)

yep
#12331
