### ISSUE TITLE
Custom NoteType LUA

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#12363]
### What is your question?

Do you know how to make a LUA file for a note that doesnt contribute for a miss but contributes for a combo? and LUA file for a note that gives 2 misses if missed?

Like in MISSINGNO’ festival take
![885EC725-54DB-499E-931E-71077118B265](https://user-images.githubusercontent.com/107759455/236126308-db9497b0-16e8-4f07-8494-3424e21a9189.jpeg)
![A382FD54-4530-48E5-B671-26EC18E85219](https://user-images.githubusercontent.com/107759455/236126330-83685782-233c-4a4f-b992-b5917bc131d5.jpeg)

**Comment by MadLuck-20** [comment]
for misses: addMisses(1);
for combo maybe: setProperty('combo', getProperty('combo') + 2); or idk

**Comment by NotStampyC** [comment]
if misses == 1 or misses == 2 then
    misses = misses+1
