### ISSUE TITLE
Game doesnt compile, but error is confusing

### ISSUE THREAD

**Issue by NotAhmedEpic** [ShadowMario/FNF-PsychEngine#12368]
### Describe your problem here.

so i tried to compile psych engine (latest version) using powershell. i installed every essential library (linc_luaijt also), but the error is some gibberish i wont understand

error:
source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : (WDeprecated) flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : (WDeprecated) flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : (WDeprecated) flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
H:/Programs/Essentials/HaxeToolKit/haxe/lib/flixel/5,3,0/flixel/animation/FlxAnimation.hx:226: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/flixel-addons/3,1,0/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'Object'
source/FunkinLua.hx:491: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:509: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:515: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:567: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:573: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:613: lines 613-617 : Int should be Bool
source/FunkinLua.hx:613: lines 613-617 : ... For function argument 'f'
source/FunkinLua.hx:2221: lines 2221-2224 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2221: lines 2221-2224 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object'
source/PlayState.hx:582: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:582: characters 25-35 : ... For function argument 'Object'
source/PlayState.hx:2433: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2433: characters 23-29 : ... For function argument 'Object'
source/PlayState.hx:2434: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2434: characters 23-83 : ... For function argument 'Object'
source/PlayState.hx:1826: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1826: characters 25-37 : ... For function argument 'Object'
source/PlayState.hx:1873: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1873: characters 25-34 : ... For function argument 'Object'
source/PlayState.hx:1944: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1944: characters 25-36 : ... For function argument 'Object'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : (WDeprecated) flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1359: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1359: characters 24-30 : ... For function argument 'Object'
source/editors/ChartingState.hx:2193: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
H:/Programs/Essentials/HaxeToolKit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
H:/Programs/Essentials/HaxeToolKit/haxe/lib/flixel/5,3,0/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
source/TitleState.hx:723: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:725: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:729: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound
H:/Programs/Essentials/HaxeToolKit/haxe/lib/flixel/5,3,0/flixel/util/FlxDestroyUtil.hx:3: characters 8-32 : You cannot access the flash package while in a macro (for flash.display.BitmapData)
source/animateatlas/AtlasFrameMaker.hx:2: characters 8-34 : ... referenced here
source/Paths.hx:3: characters 8-36 : ... referenced here
I:\ \FNF-PsychEngine-0.6.3\FNF-PsychEngine-0.6.3\source\import.hx:1: characters 8-13 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/lime/8,0,1/src/lime/media/AudioSource.hx:138: characters 53-100 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/openfl/9,2,1/src/openfl/media/Sound.hx:14: characters 8-30 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/openfl/9,2,1/src/openfl/utils/Assets.hx:9: characters 8-26 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/openfl/9,2,1/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/openfl/9,2,1/src/openfl/text/_internal/TextEngine.hx:9: characters 8-24 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/openfl/9,2,1/src/openfl/display/_internal/CairoTextField.hx:3: characters 8-40 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/openfl/9,2,1/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/openfl/9,2,1/src/openfl/display/_internal/CairoGraphics.hx:6: characters 8-36 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/openfl/9,2,1/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/openfl/9,2,1/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/openfl/9,2,1/src/openfl/events/RenderEvent.hx:4: characters 8-44 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/openfl/9,2,1/src/openfl/display/DisplayObject.hx:13: characters 8-33 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/openfl/9,2,1/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/openfl/9,2,1/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/lime/8,0,1/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/lime/8,0,1/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/lime/8,0,1/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/lime/8,0,1/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/lime/8,0,1/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/lime/8,0,1/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/lime/8,0,1/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/lime/8,0,1/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/lime/8,0,1/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/lime/8,0,1/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
H:/Programs/Essentials/HaxeToolKit/haxe/lib/lime/8,0,1/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
H:\Programs\Essentials\HaxeToolKit\haxe\std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, but I only changed the version text in the menu and the package name in Project.xml

**Comment by Username2120** [comment]
it looks like you might have your version of haxe higher then 4.2.5, likely in the 5.0.0 to 5.3.0 range. i recommend using the 4.2.5 version of haxe because its the one the engine is built on.

**Comment by NotAhmedEpic** [comment]
> it looks like you might have your version of haxe higher then 4.2.5, likely in the 5.0.0 to 5.3.0 range. i recommend using the 4.2.5 version of haxe because its the one the engine is built on.

oh, alright, let me try downgrading

**Comment by NotAhmedEpic** [comment]
> it looks like you might have your version of haxe higher then 4.2.5, likely in the 5.0.0 to 5.3.0 range. i recommend using the 4.2.5 version of haxe because its the one the engine is built on.

It worked, and the game compiled normally, thanks alot!
