### ISSUE TITLE
Wavy background on main menu

### ISSUE THREAD

**Issue by Stefan2008Git** [ShadowMario/FNF-PsychEngine#12372]
### Describe your problem here.

Im trying to fix this error, but im getting this error:
![Snimak ekrana 2023-05-05 192543](https://user-images.githubusercontent.com/126715034/236528537-dea262ab-f0f0-4962-9cea-57e97ba1d605.png)
![Snimak ekrana 2023-05-05 192844](https://user-images.githubusercontent.com/126715034/236528942-e4501336-cc9b-47e8-89eb-475a58cf0edf.png)
![Snimak ekrana 2023-05-05 194240](https://user-images.githubusercontent.com/126715034/236528772-18c78ee5-678e-42f9-b216-cac03d41af7d.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

For testing only

**Comment by MemeHovy** [comment]
okay, is the first one really not that obvious? you're missing arguments for the function

**Comment by Stefan2008Git** [comment]
> I know, but im trying to fix it lol

![Snimak ekrana 2023-05-05 201507](https://user-images.githubusercontent.com/126715034/236536442-a7962b30-3f93-41d0-9aa7-42fb2f454eef.png)

Now i got this lol.

Second error showing this:
![Snimak ekrana 2023-05-05 201611](https://user-images.githubusercontent.com/126715034/236536795-e73104a7-9eef-44d5-8d70-9a76ccc6e18c.png)

**Comment by MemeHovy** [comment]
if statements can't be used in a function @Stefan2008Git

**Comment by Stefan2008Git** [comment]
UGH
What i need to do? Im still learning Haxe damn

**Comment by MemeHovy** [comment]
add the proper arguments

**Comment by MemeHovy** [comment]
![image](https://user-images.githubusercontent.com/124418090/236539830-1c0d9dc7-68b9-4713-9273-ac09da83f77b.png)
this is how
