### ISSUE TITLE
Optimization Mode for really shit PC's

### ISSUE THREAD

**Issue by swordcube** [ShadowMario/FNF-PsychEngine#1237]
### What feature do you want to get added on the base engine?

I would like an optimization mode to get added to Psych Engine, which removes backgrounds and characters entirely.

This could have the potential to help with performance on comically bad PC's...like mine and also focus.

If not optimization atleast some overlay below the arrows?, Low quality being on and anti-aliasing being off don't help with performance a whole lot.

I don't have anything else to say here

**Comment by lolbruhfart** [comment]
i can make a low opt ver for you

**Comment by tylerandari12** [comment]
This would be really good for making charts.
I'm on board.
