### ISSUE TITLE
Null Object Reference for the stage

### ISSUE THREAD

**Issue by SoggyCereal123** [ShadowMario/FNF-PsychEngine#12373]
### Describe your problem here.

Here is my error when I tried to add my stage

![image](https://user-images.githubusercontent.com/132719429/236585323-549a03cc-efeb-4e2c-865d-5c7838c301d8.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Do not use philly glow or dadbattle spotlight outside of their stages
Please look up the error next time, there's many duplicates already

**Comment by SoggyCereal123** [comment]
I know, I try loading in my map using dadbattle, I can't use it?

**Comment by frantastic24** [comment]
if you're not using the week 1 stage, no
