### ISSUE TITLE
4 arrows bug

### ISSUE THREAD

**Issue by MegaMattPro27** [ShadowMario/FNF-PsychEngine#12378]
### Describe your bug here.

I'm making a song, so at the time of trying it, in the moments of pressing the 4 keys, it bugs, because sometimes if it presses and sometimes not.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nop.

**Comment by UmbratheUmbreon** [comment]
This is a common issue with some keyboards, but this is not a bug with Psych Engine.

**Comment by coolfren** [comment]
your keyboard does not have antighosting and may result in keypresses not being registered, or known as [key rollover](https://en.wikipedia.org/wiki/Key_rollover)

**Comment by MegaMattPro27** [comment]
Okay.
