### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by LevieStarly** [ShadowMario/FNF-PsychEngine#12376]
### Describe your problem here.

Can yall help me please, when I try to compile psych engine it shows this: 

source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
C:/HaxeToolkit/haxe/lib/flixel/5,3,0/flixel/animation/FlxAnimation.hx:226: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
C:/HaxeToolkit/haxe/lib/flixel-addons/3,1,0/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'Object'
source/FunkinLua.hx:2196: lines 2196-2199 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2196: lines 2196-2199 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object'
source/PlayState.hx:584: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:584: characters 25-35 : ... For function argument 'Object'
source/PlayState.hx:2388: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2388: characters 23-29 : ... For function argument 'Object'
source/PlayState.hx:2389: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2389: characters 23-83 : ... For function argument 'Object'
source/PlayState.hx:1781: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1781: characters 25-37 : ... For function argument 'Object'
source/PlayState.hx:1828: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1828: characters 25-34 : ... For function argument 'Object'
source/PlayState.hx:1899: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1899: characters 25-36 : ... For function argument 'Object'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1359: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1359: characters 24-30 : ... For function argument 'Object'
source/editors/ChartingState.hx:2196: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/HaxeToolkit/haxe/lib/flixel/5,3,0/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
source/TitleState.hx:711: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:713: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:717: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope didn't touch nor open a single file

**Comment by Hogich** [comment]
oh I have this problem too

**Comment by RedstoneSC** [comment]
If you are doing it using github, you can use my .yml file for compiling.
(workflows btw!)

`# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime 8.0.1
          haxelib install openfl 9.2.1
          haxelib --never install flixel 5.2.2
          haxelib git flixel https://github.com/HaxeFlixel/flixel/tree/4.11.0
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 3.0.2
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hxCodec
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hxcpp https://github.com/Sirox228/hxcpp
          haxelib list
          haxelib install refactor
          haxelib run refactor replace source *.hx "/import vlc.MP4Handler;/import hxcodec.VideoHandler;\nimport hxcodec.VideoSprite;/"
          haxelib run refactor replace source *.hx "/MP4Handler/VideoSprite/"
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: windowsBuild
          path: export/release/windows/bin`

**Comment by Hogich** [comment]
um should I copy the command and run it?

**Comment by talopakola** [comment]
i am having this problem too #12331 .
The "solution" I was told would be to use: 

- Haxe 4.2.5

- Flixel 4.11.0

- Flixel-addons 2.11.0.

Try it, if it doesn't work, there's nothing I can do :/

For me it didn't work :/

(any mistakes blame Google Translate)

**Comment by Hogich** [comment]
um somebody hepls me or what? my problem #12375
