### ISSUE TITLE
How Can I Change The Tittle Of The Window?

### ISSUE THREAD

**Issue by Spectricium** [ShadowMario/FNF-PsychEngine#12383]
### What is your question?

¿How Can I Change The Tittle Of The Window?

**Comment by Spectricium** [comment]
Whitout Source Code

**Comment by MemeHovy** [comment]
> Whitout Source Code

you can't

**Comment by MemeHovy** [comment]
well, not without using lua ofc

**Comment by Spectricium** [comment]
i will try something

**Comment by Spectricium** [comment]
do it in lua

**Comment by Spectricium** [comment]
i did it
its just this line:setPropertyFromClass("openfl.Lib", "application.window.title", "yournamehere");
