### ISSUE TITLE
Issues Related to the Discord Status Script

### ISSUE THREAD

**Issue by medals-mini** [ShadowMario/FNF-PsychEngine#1238]
### Describe your problem here.

Whenever I try to compile, I get these 2 errors
source/Discord.hx:63: characters 48-49 : Unexpected )
source/Discord.hx:63: characters 48-49 : Unexpected )
Can anyone help (or at least tell me the problem?)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CrusherMods** [comment]
Either add or remove the ) at line 63

**Comment by medals-mini** [comment]
I tried that, but:
When I added an ), it gave me the same error
When I removed it, it gave me this error
source/Discord.hx:67: characters 2-7 : Unexpected trace
source/Discord.hx:4: characters 7-29 : Type not found : discord_rpc.DiscordRpc

**Comment by ShadowMario** [comment]
Should be fixed??
