### ISSUE TITLE
Ideas For My Engine

### ISSUE THREAD

**Issue by Spectricium** [ShadowMario/FNF-PsychEngine#12385]
### What is your question?

Answer Your Ideas Here And In The Engine I Will Credit The Creator Idea

EngineName: Sentinel Engine

**Comment by Lorekeeper49** [comment]
I get that the engine is probably a fork, but even then why are you posting it on here, GameBanana is a more suitable place for this type of post

**Comment by jimmyjamescool** [comment]
Duplicate of #12384
![35416CEB-4AC9-42A5-8BD1-4EB6004950E0](https://user-images.githubusercontent.com/131569352/236701764-9d0ce539-d0ae-4d48-bb28-86e968fec4b0.jpeg)

**Comment by Spectricium** [comment]
wow did u see this bruh
