### ISSUE TITLE
For My Engine

### ISSUE THREAD

**Issue by Spectricium** [ShadowMario/FNF-PsychEngine#12384]
### What is your question?

So Im Making An Engine Using Psych Engine As Base Named : SentinelEngine Is Made Without Source Code My Question Is:How Can I Run A Function When I Open The Engine? Without Source Code

**Comment by jimmyjamescool** [comment]
![6E654285-D626-4956-8748-D764CDCED579](https://user-images.githubusercontent.com/131569352/236659403-5c030480-1fd4-4dc2-a6da-cf6eefef2d22.jpeg)

**Comment by Spectricium** [comment]
f###

**Comment by Spectricium** [comment]
U KNOW WHAT IM USING AN AI
