### ISSUE TITLE
Standard library missign D:

### ISSUE THREAD

**Issue by Nubllyr** [ShadowMario/FNF-PsychEngine#12381]
### What is your question?

So umm, when i try to run "Lime build windows" it says:  Standard library not found. You may need to set your `HAXE_STD_PATH` environment variable. 
And i dont even know what to do, i would appreciate it if someone could help me :)

**Comment by KELOTOMU** [comment]
Do you use source code?

**Comment by Nubllyr** [comment]
> Do you use source code?

Yes, i do use source code
