### ISSUE TITLE
I cant use any Haxelib Install commands

### ISSUE THREAD

**Issue by ToddSenzy** [ShadowMario/FNF-PsychEngine#12387]
### Describe your bug here.

Commands like haxelib install lime or haxelib install hscript dont work!
They just give me the error Error: Failed with error: X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
Oddly enough things like haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit or haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc dont have any errors!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing, I cant even compile the build!

**Comment by frantastic24** [comment]
This has nothing to do with psych engine, don't report it as a bug

**Comment by ToddSenzy** [comment]
> This has nothing to do with psych engine, don't report it as a bug

my bad

**Comment by ytboogy** [comment]
it does relate to psych engine btw
