### ISSUE TITLE
icon mod

### ISSUE THREAD

**Issue by Spectricium** [ShadowMario/FNF-PsychEngine#12389]
### What is your question?

so i was making it i was going to put the icon i putted in and it doesn't work the code:
{
	"name": "Sentinel Engine",
	"description": "An Psych Engine Modification Named:Sentinel Engine",
	"restart":false,
	"runsGlobally": true,
	"color": [170, 0, 255],
	"icon": "icon/icon.png"
}

**Comment by jimmyjamescool** [comment]
Belongs in your fork + wtf

**Comment by Spectricium** [comment]
Im Not Using Source Code Also XD

**Comment by jimmyjamescool** [comment]
It’s impossible to make an engine without source code.

**Comment by Spectricium** [comment]
Also The BackGround Movement System Of VS DAVE AND BAMBI Is Done And I Will Never Use Source Code Why Because I HATE C/C++ I Like More C# Or Lua
