### ISSUE TITLE
How Can I Change The Icon Of The Executable Without Source Code

### ISSUE THREAD

**Issue by Spectricium** [ShadowMario/FNF-PsychEngine#12382]
### What is your question?

¿How Can I Change The Icon Of The Executable Without Source Code? Its My Question

**Comment by MemeHovy** [comment]
you can't

**Comment by MemeHovy** [comment]
well, atleast not without some tools

**Comment by Spectricium** [comment]
with what tools?

**Comment by MemeHovy** [comment]
http://www.angusj.com/resourcehacker/#download

**Comment by Spectricium** [comment]
Alright I Will Try To Do It

**Comment by Spectricium** [comment]
Thanks!

**Comment by MemeHovy** [comment]
np
