### ISSUE TITLE
How do I add bg characters?

### ISSUE THREAD

**Issue by VladTheFnfModder** [ShadowMario/FNF-PsychEngine#12386]
### Describe your problem here.

For a while now I'm trying to figure out how to add background characters to the source code version of psych, I can't find any tutorials on it.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added custom backgrounds in PlayState.hx .

**Comment by CaptainBaldi** [comment]
literally just make an animated sprite and play its idle animation on beat hit

**Comment by VladTheFnfModder** [comment]
But my problem is how to add it to the actual game itself, that doesn't explain me anything
