### ISSUE TITLE
Camera Error

### ISSUE THREAD

**Issue by NickWildy** [ShadowMario/FNF-PsychEngine#12392]
### Describe your problem here.

For some reason it tells me this :(
![image_2023-05-07_212310852](https://user-images.githubusercontent.com/105122799/236714186-d3f4f706-b3a6-4045-836a-56360bb00766.png)

how to i fix????????

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by MemeHovy** [comment]
that's only a warning, not a error

**Comment by NickWildy** [comment]
but how do i fix it??????

**Comment by NickWildy** [comment]
ok i resolved it

**Comment by NexIsDumb** [comment]
@NickWildy if you resolved then please close this issue
