### ISSUE TITLE
I cant use lime rebuild extension-webm windows

### ISSUE THREAD

**Issue by coookiesgo** [ShadowMario/FNF-PsychEngine#12397]
### Describe your problem here.

Every time i try to run this command it gives me this error:
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
but i've alredy installed VS studio, can somebody help me?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
psych engine does not use webm, and install visual studio 2019

**Comment by DragShot** [comment]
Perhaps you're missing the MS Visual C compiler.

Try browsing the [Visual Studio 2019 Catalog](https://visualstudio.microsoft.com/vs/older-downloads/) (you will need a Microsoft account for this), and download the most recent **Build Tools for Visual Studio 2019**. Once you get it running, install the modules `MSVC v142 - VS 2019 C++ x64/x86 build tools` and `Windows SDK (10.0.17763.0)` only. Restart your PC just to be sure, and then you should be able to compile the project.

**Comment by MemeHovy** [comment]
> Perhaps you're missing the MS Visual C compiler.
> 
> Try browsing the [Visual Studio 2019 Catalog](https://visualstudio.microsoft.com/vs/older-downloads/) (you will need a Microsoft account for this), and download the most recent **Build Tools for Visual Studio 2019**. Once you get it running, install the modules `MSVC v142 - VS 2019 C++ x64/x86 build tools` and `Windows SDK (10.0.17763.0)` only. Restart your PC just to be sure, and then you should be able to compile the project.

That’s what I just said 🗿

**Comment by Luke1411** [comment]
For some reason when i introduce the command, nothing happens, nothing has changed on the pc and that pisses me off any solution?

**Comment by chrisdoesstuff69** [comment]
> psych engine does not use webm, and install visual studio 2019

i cant download it tho

**Comment by Hotdawgman13** [comment]
I need some help. I did the instructions as planned but its still showing that message.
