### ISSUE TITLE
Quick question about the .json setup

### ISSUE THREAD

**Issue by civil1119** [ShadowMario/FNF-PsychEngine#12396]
### What is your question?

I'm currently making a (crappy) voice file creator for people who are too lazy to make their own voice file, which just gives 8 audio files for the sounds when bf notes are hit and sound when enemy notes are hit
I'm trying to reverse engineer the .json files layout so it can read the way the notes are made, simulate playing through it, and then record the audio played into a .ogg file named "Voice" to create the file without any expertise in music or any other music creator.
I was going through some of the .json files and I figured out the layout but what does it mean if the note "number" (1st list index for a note group) is more than three and how are double notes written using the note number? I know that 0-3 is left through right, but not much more than that
I couldn't find it anywhere online.
Thanks! 👍 
(example note group:
[66000.0,7,281.25]
)
(I was using ugh as the example song, where I first found notes with the identification of "7")

**Comment by MemeHovy** [comment]
look through Song.hx, that’s where the notes are made

**Comment by MemeHovy** [comment]
> Thanks

you're welcome
