### ISSUE TITLE
Using close() deactives other scripts

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#12391]
### Describe your bug here.

I am not sure if that should be like that, but I used in a stage script close(true) in CreatePost instead of Create because of one change I needed to do there, and then it suddenly deactivated the script that was tied to the song in the data folder.
More specifically, it was just a script using the function of opponentNoteHit()

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not via source

**Comment by DragShot** [comment]
I remember reading somewhere that the `close()` function is buggy and preferably it shouldn't be used. Perhaps that's what they were talking about.
