### ISSUE TITLE
Stuck at 16 - 19 FPS

### ISSUE THREAD

**Issue by Eassah** [ShadowMario/FNF-PsychEngine#12393]
### Describe your bug here.

Just today psych just gets stuck at 16 to 19 fps for no reason

![image](https://user-images.githubusercontent.com/96087796/236765597-4040e95d-7a44-4eba-b351-9f7bdf9b50fd.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ender69funk** [comment]
ur pc is bad and stucked

**Comment by FunkoDev** [comment]
i bet bros running on a intel pentium

**Comment by FunkoDev** [comment]
i bet bros running on a intel pentium

**Comment by KELOTOMU** [comment]
Happens to me if a mod I downloaded use shaders.
