### ISSUE TITLE
var variable:Int = (FlxG.random.int(jsonvariable[0], jsonvariable[1])); crashes and idk why :(

### ISSUE THREAD

**Issue by DafaTG** [ShadowMario/FNF-PsychEngine#12399]
### Describe your problem here.

I'm trying to set an Int variable to a random number between 2 json variables, but for some reason it just keeps on crashing
code:
var numberPortrait:Int = (FlxG.random.int(mainMenuJSON.portraitRandomizer[0], mainMenuJSON.portraitRandomizer[1])); 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I don't think so???

**Comment by Hackx2** [comment]
Why is ```FlxG.random.int``` in brackets?

**Comment by DafaTG** [comment]
I tried it without brackets, still crashes.

**Comment by Hackx2** [comment]
> ### Describe your problem here.
> I'm trying to set an Int variable to a random number between 2 json variables, but for some reason it just keeps on crashing code: var numberPortrait:Int = (FlxG.random.int(mainMenuJSON.portraitRandomizer[0], mainMenuJSON.portraitRandomizer[1]));
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> I don't think so???

It would help if you're able to send the full state.

Also what are you trying to do.

```jsonvariable[0]``` is returning a string so try ```jsonvariable[0].length```

**Comment by Hackx2** [comment]
@DafaTG 

Like

```haxe
var uhm:Int = FlxG.random.int(0, mainMenuJSON.portraitRandomizer[1].length);
```
if you want a random portrait to show.
You can accomplish that by using the built in system tools.

If you need help just ask. : )

**Comment by Hackx2** [comment]
It would help if you show the json file.

**Comment by Hackx2** [comment]
Add at the start of the MainMenuState class

```haxe
var contentJSON:MainMenuData;
var posJSON:PortraitData;
```
Inside the create function add the following...
```haxe
contentJSON = Json.parse(Paths.getTextFromFile('mainmenu/mainMenuLayout.json'));
```
Same as the other one 
```haxe Json.parse(Paths.getTextFromFile('mainmenu/'+ numberPortrait +'.json'));
```
I'll rewrite this once I get back home.

**Comment by DafaTG** [comment]
actually, nevermind I found the problem. The build makes the variable BEFORE even getting the mainMenuLayout.json data, making it crash when trying to find [mainMenuJSON.portraitRandomizer]. I just needed to put the variable after that and BOOM it works completely well. 

Still, thank you very much for trying to help :D 
Have a great day and goodbye :)
