### ISSUE TITLE
setRatingString() question

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#12407]
### What is your question?

I'm trying to get setRatingString/setRatingName working and I've tried EVERYTHING and nothings working.  EVERYTHING.  I search up how to in 0.6.3 and its all NOT WORKING.  I try looking at the 'templateScript.lua' file and it just says:

	-- return Function_Stop if you want to do your own rating calculation,
	-- use setRatingPercent() to set the number on the calculation and setRatingString() to set the funny rating name
	-- NOTE: THIS IS CALLED BEFORE THE CALCULATION!!!

I do the things that it saying, and nothing WORKS!  

**But the main reason I made this labeled as question is because im wondering if these functions even work in 0.6.3**

This was the last code I tried:

```
function onRecalculateRating()
	-- return Function_Stop if you want to do your own rating calculation,
	-- use setRatingPercent() to set the number on the calculation and setRatingString() to set the funny rating name
	-- NOTE: THIS IS CALLED BEFORE THE CALCULATION!!!
    debugPrint("aaaaa")
    setRatingString("a")
	return Function_Stop;
end
```

**Comment by CaptainBaldi** [comment]
as far as i know they don't work
why? Who knows

**Comment by loldog757** [comment]
I'm having same problem but i know it works in older versions on psych but it wont work on 0.6.3 for whatever reason
