### ISSUE TITLE
How do I give a specifc character a custom game over screen?

### ISSUE THREAD

**Issue by Sliversonic64** [ShadowMario/FNF-PsychEngine#1240]
### Describe your problem here.

I've been trying to add a different game over screen on a song but it's just always bf and I don't know how to change it for that song or character.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by CrusherMods** [comment]
an example script exists in the wiki for custom death animation
