### ISSUE TITLE
The entire thing broke.

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#12402]
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/94698464/3d4bd8ac-6fe9-4acc-891c-6af9df63664f)
I compiled the engine using GitHub actions and- uh... idk how to explain THIS.
The first time you boot it up and when you go to the Freeplay menu, it skips a song when you scroll down, and when you go into a song, the game is super tiny, and when the opponent hits a note, the HUD shrinks too. Did I do something wrong in the code? Also, when you get out of a song, you're able to scroll through the songs without it skipping. And Debug mode takes FOREVER to load and lags like HELL. and some of the Lua scripts stopped working.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I used both Source and Lua to make the mod

**Comment by PDL2CGamejolt** [comment]
Also, when you get out of a song, you're able to scroll through the songs without it skipping.

**Comment by PDL2CGamejolt** [comment]
Update: Debug doesn't work.

**Comment by FunkoDev** [comment]
bro this is psych engine not os engine

**Comment by PDL2CGamejolt** [comment]
> ~bro this is psych engine not os engine~
> 
> oops

OS engine is just an edited version of Psych engine. Also, idk WHAT happened to the whole engine after it was done compiling.

**Comment by frantastic24** [comment]
A fork is not psych engine please do not report issues here
