### ISSUE TITLE
what could this be?

### ISSUE THREAD

**Issue by AndrewNursh** [ShadowMario/FNF-PsychEngine#12401]
### Describe your problem here.

ive been trying to compile the engine for a bit now, and these errors pop up and i dont know what to do.
i need some help!
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/110268185/3c5346f6-1aa7-4a4a-b74a-1fe7c1f1f4a0)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, nothing

**Comment by NexIsDumb** [comment]
Downgrade Haxe 4.2.5
