### ISSUE TITLE
how can i change the wallpaper like shadowfi's missingno with lua?

### ISSUE THREAD

**Issue by ROCK201888** [ShadowMario/FNF-PsychEngine#12403]
### Describe your problem here.

or source

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

none for now

**Comment by CaptainBaldi** [comment]
ew

**Comment by ROCK201888** [comment]
bruh

**Comment by ROCK201888** [comment]
there must be a way

**Comment by lemz1** [comment]
stop trying to create malware

**Comment by ROCK201888** [comment]
y

**Comment by CaptainBaldi** [comment]
> stop trying to create malware

this is so true ong

**Comment by ROCK201888** [comment]
bruh no

**Comment by ROCK201888** [comment]
even it's a malware i will not post it

**Comment by ROCK201888** [comment]
i make vids

**Comment by TFLTV** [comment]
idk look at this ig https://www.reddit.com/r/lua/comments/1cdmzx/how_to_change_the_windows_wallpaper_with_lua/?utm_source=BD&utm_medium=Search&utm_name=Bing&utm_content=PSR1

**Comment by jimmyjamescool** [comment]
![D8581AAE-0EF5-4E49-A748-940E70CEBCAD](https://github.com/ShadowMario/FNF-PsychEngine/assets/131569352/89d48ce6-391c-4c5b-b212-ea646860c37a)

**Comment by ROCK201888** [comment]
:(





































































you should kill ur self

**Comment by MemeHovy** [comment]
> :(
> 
> you should kill ur self

![FD7EePqXMAoxuAc (1)](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/2fd486fb-099e-49ec-999b-4eebd49391da)

**Comment by jimmyjamescool** [comment]
> :(
> 
> you should kill ur self

![84FB2884-C364-45F7-877A-3003E8738E9A](https://github.com/ShadowMario/FNF-PsychEngine/assets/131569352/281cdca2-8ac3-4137-85fd-1f3d350662f0)

**Comment by SantiagoCalebe** [comment]
that was the most stupid conversation i ever heard

**Comment by Cee-Jay0900** [comment]
did you ever figure it out? i wanna know too
