### ISSUE TITLE
how to delete this black sh*t behind the judgement line?

### ISSUE THREAD

**Issue by 3gl1** [ShadowMario/FNF-PsychEngine#12412]
### What is your question?

see the label
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/126273058/81243ace-d806-4007-8a17-32fe2b2a3ccf)
mod: exosphere corruption v2.3

**Comment by TFLTV** [comment]
wheres the code????

**Comment by 3gl1** [comment]
> > ### What is your question?
> > see the label ![image](https://user-images.githubusercontent.com/126273058/238026468-81243ace-d806-4007-8a17-32fe2b2a3ccf.png) mod: exosphere corruption v2.3
> 
> it originates from os engine.

oh sorry

**Comment by 3gl1** [comment]
you need to set lane transparency to 0% if have the same problem
