### ISSUE TITLE
run lua in the main menu

### ISSUE THREAD

**Issue by ROCK201888** [ShadowMario/FNF-PsychEngine#12414]
### What feature do you want to get added on the **base** engine?

run lua in the main menu
because why not

### To test your sight, and reliability, please select the option of what should NOT be requested.

Better LUA mod support idea

**Comment by TheMrBlueShowYt** [comment]
this would be cool! maybe if you have enough experience make a pr

**Comment by CaptainBaldi** [comment]
oh god here's the 8 millionth issue about running lua in menu's

**Comment by KookerFoxYT** [comment]
> ### What feature do you want to get added on the **base** engine?
> run lua in the main menu because why not

[https://github.com/mayo78/psychenginescripts/tree/main/run%20code%20in%20menus](mayo78 already did that, **in** lua)

**Comment by KookerFoxYT** [comment]
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Better LUA mod support idea

also i think you already failed the test

**Comment by ROCK201888** [comment]
i don't mean this

**Comment by ROCK201888** [comment]
i mean change the `source` to make lua run in menu

**Comment by MemeHovy** [comment]
> i mean change the `source` to make lua run in menu

that’s exactly what you said before, and no

**Comment by MemeHovy** [comment]
how dumb are you

**Comment by ROCK201888** [comment]
> how dumb are you

plz just go avay if u cant help

**Comment by MemeHovy** [comment]
> > how dumb are you
> 
> plz just go avay if u cant help

you literally said the exact same thing beforehand

**Comment by ROCK201888** [comment]
> > > how dumb are you
> > 
> > 
> > plz just go avay if u cant help
> 
> you literally said the exact same thing beforehand

YEAH but dat guy dont know what im saying

**Comment by MemeHovy** [comment]
> > > > how dumb are you
> > > 
> > > 
> > > plz just go avay if u cant help
> > 
> > 
> > you literally said the exact same thing beforehand
> 
> YEAH but dat guy dont know what im saying

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/c50b017e-1a4b-4ae9-8d28-69a97d992bd8)

**Comment by MemeHovy** [comment]
it's literally in the options of what shouldn't be added

**Comment by ROCK201888** [comment]
y

**Comment by MemeHovy** [comment]
> y

cuz shadowmario doesn't want that added

**Comment by ROCK201888** [comment]
then make it in a other engine bro

**Comment by ROCK201888** [comment]
i just want to do run lua in menu

**Comment by MemeHovy** [comment]
> i just want to do run lua in menu

okay well, it ain't gonna happen here tho

**Comment by MemeHovy** [comment]
and you failed the test aswell
