### ISSUE TITLE
LUA Notesplashes being played regardless of hitting a Sick! or not

### ISSUE THREAD

**Issue by KindOfASpork** [ShadowMario/FNF-PsychEngine#12415]
### Describe your problem here.

i'm currently trying to fix a script from a HUD modpack. the main issue i am having is that i am trying to have notesplashes correctly play only when hitting a Sick!, as in this script's current state, it will always play the notesplash upon hitting a note regardless of rating.

here is the script in question, taken from the DDTO+ Hud Script by MinecraftBoy2038 (https://gamebanana.com/tools/12677)
[dokiSplashes.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/11468700/dokiSplashes.txt)

here is the issue in video (ignore the missing BF icon, that's because of a winning icon script i had on at the time)
https://streamable.com/04braq

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No edits were made to this build.

**Comment by frantastic24** [comment]
#11380
