### ISSUE TITLE
Problem With Compile

### ISSUE THREAD

**Issue by TARG1221** [ShadowMario/FNF-PsychEngine#12419]
### Describe your problem here.

When I run the "lime test windows" I get all these errors

source/FunkinLua.hx:479: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:497: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:503: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:553: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:559: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:599: lines 599-603 : Int should be Bool
source/FunkinLua.hx:599: lines 599-603 : ... For function argument 'f'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added <haxelib name="discord_rpc" if="Discord"/> to Project.xml

**Comment by MemeHovy** [comment]
use nebulazoruas fork of linc_luajit

**Comment by TARG1221** [comment]
Sorry I'm new to GitHub, How do I do that XD

**Comment by TARG1221** [comment]
Never Mind I Fixed It
