### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by OperDal** [ShadowMario/FNF-PsychEngine#12417]
### Describe your bug here.

every time i do lime test windows this happens

### Command Prompt/Terminal logs (if existing)

```bash
source/flixel/util/FlxDestroyUtil.hx:3: characters 8-32 : You cannot access the flash package while in a macro (for flash.display.BitmapData)
source/animateatlas/AtlasFrameMaker.hx:2: characters 8-34 : ... referenced here
source/Paths.hx:3: characters 8-36 : ... referenced here
D:\FNF-PsychEngine-main\source\import.hx:1: characters 8-13 : ... referenced here
(unknown) : ... referenced here
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SlickFromMars** [comment]
what version of haxe are you using? the new 4.3.1 has a lot of issues relating to macro
