### ISSUE TITLE
I cannot get my custom arrows to work properly

### ISSUE THREAD

**Issue by NotStampyC** [ShadowMario/FNF-PsychEngine#12420]
### Describe your problem here.

each time i play a song with this arrow if its played too many times it gives me this crash error

PlayState.hx (line 4633)
PlayState.hx (line 3240)
flixel/group/FlxGroup.hx (line 769)
PlayState.hx (line 3179)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

I barely have any experience with this 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by KELOTOMU** [comment]
Maybe because of the arrow animation names?

**Comment by NotStampyC** [comment]
> Maybe because of the arrow animation names?

No it was because you had to misspell purple with pruple end
