### ISSUE TITLE
Haxelib libraries

### ISSUE THREAD

**Issue by KELOTOMU** [ShadowMario/FNF-PsychEngine#12426]
### What needs to be documented?

I just saw a txt file from source code\export\release\windows\obj\Options.txt

It said some library versions so maybe it tells all the exact versions needed :

ACHIEVEMENTS_ALLOWED=1
CRASH_HANDLER=1
FLX_DRAW_QUADS=1
FLX_GAMEINPUT_API=1
FLX_GAMEPAD=1
FLX_KEYBOARD=1
FLX_MOUSE=1
FLX_MOUSE_ADVANCED=1
FLX_NO_DEBUG=1
FLX_NO_FOCUS_LOST_SCREEN=1
FLX_POINTER_INPUT=1
FLX_SOUND_SYSTEM=1
FLX_SOUND_TRAY=1
FLX_TOUCH=1
HXCPP_CHECK_POINTER=1
HXCPP_M64=1
HXCPP_STACK_LINE=1
LINC_LUA_RELATIVE_DYNAMIC_LIB=1
LUA_ALLOWED=1
MODS_ALLOWED=1
NAPE_RELEASE_BUILD=1
PRELOAD_ALL=1
PSYCH_WATERMARKS=1
VIDEOS_ALLOWED=1
desktop=1
discord_rpc=1.0.0
flixel=4.11.0
flixel-addons=2.11.0
flixel-ui=2.5.0
flixel_addons=2.11.0
flixel_ui=2.5.0
haxe=4.2.5
haxe3=1
haxe4=1
haxe_ver=4.205
hscript=2.5.0
hscriptPos=1
hxCodec=2.6.1
hxcpp=4.3.2
hxcpp_api_level=400
hxcpp_smart_strings=1
lime=8.0.1
lime-cairo=1
lime-cffi=1
lime-curl=1
lime-harfbuzz=1
lime-native=1
lime-openal=1
lime-opengl=1
lime-vorbis=1
lime_cairo=1
lime_cffi=1
lime_curl=1

no more hmm I guess cause it's buggy?
I will try to install all libraries manually to see if it fixes it for me.

**Comment by DragShot** [comment]
Beware tho, the hxCodec library doesn't work correctly when it's installed locally through `hmm`. What I did to fix this was issuing these three commands instead of what Psych's guide suggests:

```
haxelib --global install hmm
haxelib --global install hxCodec 2.5.1
haxelib run hmm install
```

Everything else worked correctly when I tried it two months ago.

**Comment by Athise83** [comment]
I not get my personel image all.
