### ISSUE TITLE
Credits background always white

### ISSUE THREAD

**Issue by MemeHovy** [ShadowMario/FNF-PsychEngine#12428]
### Describe your bug here.

There seems to be an issue where the background color in the credits would be completely white, even when changing selections.
As shown in the screenshot below.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/89850cca-03d9-46a7-b62a-166575400743)
This even occurs on a clean and unmodified psych engine. My suspicions turn to `hxcpp` as it could be one of the underlying issues with this, specifically with newer versions.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

None.

**Comment by Stefan2008Git** [comment]
That's happening to my build too, i don't know why

**Comment by MemeHovy** [comment]
> That's happening to my build too, i don't know why

it happens on almost every psych build

**Comment by DiamondMotions** [comment]
I have this too can someone help me.

**Comment by Stefan2008Git** [comment]
> I have this too can someone help me.

You can't fix that issue. It's a hxcpp issue

**Comment by DiamondMotions** [comment]
There must be someone way to fix it, it was working fine when I compiled it.

**Comment by DiamondMotions** [comment]
Nevermind I fixed It just remove the hxcpp and then go to this version haxelib install hxcpp 4.2.1

**Comment by KookerFoxYT** [comment]
> Nevermind I fixed It just remove the hxcpp and then go to this version haxelib install hxcpp 4.2.1

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/62410083/60abea7d-8adf-4734-baae-f262f5966a8b)

**Comment by KookerFoxYT** [comment]
> > Nevermind I fixed It just remove the hxcpp and then go to this version haxelib install hxcpp 4.2.1
> 
> ![image](https://user-images.githubusercontent.com/62410083/248527021-60abea7d-8adf-4734-baae-f262f5966a8b.png)

so ig theres probably no way to get the credit bg color working

**Comment by MemeHovy** [comment]
> > > Nevermind I fixed It just remove the hxcpp and then go to this version haxelib install hxcpp 4.2.1
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/62410083/248527021-60abea7d-8adf-4734-baae-f262f5966a8b.png)
> 
> so ig theres probably no way to get the credit bg color working

use the git version of hxcpp

**Comment by MemeHovy** [comment]
that seems to fix it, but, I wanna see if there’s a fix for it on 4.2.1, and also I’m pretty sure it said that due to you use haxe 4.3

**Comment by KookerFoxYT** [comment]
ohhhhh
but i was about to say i realized i updated to the latest version so

**Comment by KookerFoxYT** [comment]
perhaps i can try downgrading? maybe?

**Comment by KookerFoxYT** [comment]
oh wait its already compiling rn

**Comment by Stefan2008Git** [comment]
Guys, use 4.2.1 for that, beacuse latest version of hxcpp it's broken, so you can see my screenshot
![slika](https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/cb5bf235-f58f-4d2c-be09-12f85cfd4287)

**Comment by MemeHovy** [comment]
the latest works tho

**Comment by KookerFoxYT** [comment]
> Guys, use 4.2.1 for that, beacuse latest version of hxcpp it's broken, so you can see my screenshot ![slika](https://user-images.githubusercontent.com/126715034/248591744-cb5bf235-f58f-4d2c-be09-12f85cfd4287.png)

i was about to do that

**Comment by KookerFoxYT** [comment]
> the latest works tho

not for me
i downgraded back to haxe 4.2.5 and decided to downgrade 4.2.1 so lets hope it works for me

**Comment by KookerFoxYT** [comment]
it does

**Comment by KookerFoxYT** [comment]
just wait

**Comment by KookerFoxYT** [comment]
it worked but
(sorry for offtopic but) the charter got ruined because of it

**Comment by MemeHovy** [comment]
> it worked but
> (sorry for offtopic but) the charter got ruined because of it

hmm, noted

**Comment by doom699** [comment]
someone close this please

**Comment by Stefan2008Git** [comment]
> the latest works tho

For me it's still white LMAO

**Comment by Stefan2008Git** [comment]
> > Nevermind I fixed It just remove the hxcpp and then go to this version haxelib install hxcpp 4.2.1
> 
> ![image](https://user-images.githubusercontent.com/62410083/248527021-60abea7d-8adf-4734-baae-f262f5966a8b.png)

You need Haxe 4.2.5 for that and it's reccomended

**Comment by MemeHovy** [comment]
> someone close this please

I kept this open in case someone found an proper fix other then updating hxcpp

**Comment by Stefan2008Git** [comment]
> > > it worked but
> > > (sorry for offtopic but) the charter got ruined because of it
> > 
> > 
> > hmm, noted
> 
> nvm but because of this the RGB stuff doesnt work anymore in week editor

Everything it's working fine for me, but i don't know for you

**Comment by doom699** [comment]
> > someone close this please
> 
> I kept this open in case someone found an proper fix other then updating hxcpp

oh ok
