### ISSUE TITLE
i having some problems that just said mp4handler

### ISSUE THREAD

**Issue by CJ77GT6R** [ShadowMario/FNF-PsychEngine#12421]
### Describe your bug here.

when i put lime test windows, it happens this 
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1573: characters 13-23 : Type not found : MP4Handler

### Command Prompt/Terminal logs (if existing)

```bash
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1573: characters 13-23 : Type not found : MP4Handler
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by SlickFromMars** [comment]
Do you have hxCodec 2.5.1 installed? If not, that may be leading to the issue.

**Comment by NexIsDumb** [comment]
This got resolved with my commits in the latest version of Psych Engine

**Comment by NexIsDumb** [comment]
> @NexIsDumb I don't see the commits

#11905

**Comment by SlickFromMars** [comment]
oh alrighty. idk why I was expecting them to be already merged into main lol. @CJ77GT6R we can mark this as resolved

**Comment by NexIsDumb** [comment]
> oh alrighty. idk why I was expecting them to be already merged into main lol. @CJ77GT6R we can mark this as resolved

It is already merged into main wdym

**Comment by SlickFromMars** [comment]
OH IM STUPID I DIDNT SEE THEM. sorry about that hehe

**Comment by NexIsDumb** [comment]
> oh alrighty. idk why I was expecting them to be already merged into main lol. @CJ77GT6R we can mark this as resolved

But yeah, anyways ^

**Comment by SlickFromMars** [comment]
I'm assuming we have to wait for a person with permissions to come close this.

**Comment by NexIsDumb** [comment]
> I'm assuming we have to wait for a person with permissions to come close this.

Yup the ways are:
1) the submitter closes the issue
2) shadowmario closes this
3) 30 days passed since the issue creation

**Comment by SlickFromMars** [comment]
alrighty. still relatively new to issues, trying to be more active here. hopefully @CJ77GT6R closes it

**Comment by NexIsDumb** [comment]
> alrighty. still relatively new to issues, trying to be more active here. hopefully @CJ77GT6R closes it 

Oks, glad I was helpful to ye

**Comment by CJ77GT6R** [comment]
huh i see

**Comment by CJ77GT6R** [comment]
isn't hxCodec 2.5.1 right? @SlickFromMars

**Comment by CJ77GT6R** [comment]
source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/animation/FlxAnimation.hx:231: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
C:/HaxeToolkit/haxe/lib/flixel-addons/3,1,0/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'Object'
source/PlayState.hx:1573: characters 13-23 : Type not found : MP4Handler
source/FunkinLua.hx:2196: lines 2196-2199 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2196: lines 2196-2199 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object'
source/PlayState.hx:582: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:582: characters 25-35 : ... For function argument 'Object'
source/PlayState.hx:2386: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2386: characters 23-29 : ... For function argument 'Object'
source/PlayState.hx:2387: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2387: characters 23-83 : ... For function argument 'Object'
source/PlayState.hx:1779: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1779: characters 25-37 : ... For function argument 'Object'
source/PlayState.hx:1826: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1826: characters 25-34 : ... For function argument 'Object'
source/PlayState.hx:1897: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1897: characters 25-36 : ... For function argument 'Object'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1359: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1359: characters 24-30 : ... For function argument 'Object'
source/editors/ChartingState.hx:2193: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
source/TitleState.hx:711: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:713: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:717: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound
another error appeared
god damn

**Comment by NexIsDumb** [comment]
> source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
> source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
> source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
> C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/animation/FlxAnimation.hx:231: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
> source/Main.hx:85: characters 61-65 : Float should be Int
> source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
> source/Main.hx:85: characters 61-65 : ... For function argument 'child'
> source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
> C:/HaxeToolkit/haxe/lib/flixel-addons/3,1,0/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
> source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'Object'
> source/PlayState.hx:1573: characters 13-23 : Type not found : MP4Handler
> source/FunkinLua.hx:2196: lines 2196-2199 : flixel.sound.FlxSound should be flixel.system.FlxSound
> source/FunkinLua.hx:2196: lines 2196-2199 : ... For function argument 'value'
> source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object'
> source/PlayState.hx:582: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/PlayState.hx:582: characters 25-35 : ... For function argument 'Object'
> source/PlayState.hx:2386: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/PlayState.hx:2386: characters 23-29 : ... For function argument 'Object'
> source/PlayState.hx:2387: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/PlayState.hx:2387: characters 23-83 : ... For function argument 'Object'
> source/PlayState.hx:1779: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/PlayState.hx:1779: characters 25-37 : ... For function argument 'Object'
> source/PlayState.hx:1826: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/PlayState.hx:1826: characters 25-34 : ... For function argument 'Object'
> source/PlayState.hx:1897: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/PlayState.hx:1897: characters 25-36 : ... For function argument 'Object'
> source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
> source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
> source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
> source/editors/ChartingState.hx:1359: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
> source/editors/ChartingState.hx:1359: characters 24-30 : ... For function argument 'Object'
> source/editors/ChartingState.hx:2193: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
> C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
> source/TitleState.hx:711: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
> source/TitleState.hx:713: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
> source/TitleState.hx:717: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound
> another error appeared
> god damn

ok, no you fixed hxCodec but now there are new versions of flixel and flixel-addons troubles, you have to continue to downgrade it until the errors wont begone

**Comment by NexIsDumb** [comment]
> > source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
> > source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
> > source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
> > C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/animation/FlxAnimation.hx:231: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
> > source/Main.hx:85: characters 61-65 : Float should be Int
> > source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
> > source/Main.hx:85: characters 61-65 : ... For function argument 'child'
> > source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
> > C:/HaxeToolkit/haxe/lib/flixel-addons/3,1,0/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
> > source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
> > source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'Object'
> > source/PlayState.hx:1573: characters 13-23 : Type not found : MP4Handler
> > source/FunkinLua.hx:2196: lines 2196-2199 : flixel.sound.FlxSound should be flixel.system.FlxSound
> > source/FunkinLua.hx:2196: lines 2196-2199 : ... For function argument 'value'
> > source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
> > source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object'
> > source/PlayState.hx:582: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
> > source/PlayState.hx:582: characters 25-35 : ... For function argument 'Object'
> > source/PlayState.hx:2386: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
> > source/PlayState.hx:2386: characters 23-29 : ... For function argument 'Object'
> > source/PlayState.hx:2387: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
> > source/PlayState.hx:2387: characters 23-83 : ... For function argument 'Object'
> > source/PlayState.hx:1779: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
> > source/PlayState.hx:1779: characters 25-37 : ... For function argument 'Object'
> > source/PlayState.hx:1826: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
> > source/PlayState.hx:1826: characters 25-34 : ... For function argument 'Object'
> > source/PlayState.hx:1897: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
> > source/PlayState.hx:1897: characters 25-36 : ... For function argument 'Object'
> > source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
> > source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
> > source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
> > source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
> > source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
> > source/editors/ChartingState.hx:1359: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
> > source/editors/ChartingState.hx:1359: characters 24-30 : ... For function argument 'Object'
> > source/editors/ChartingState.hx:2193: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
> > C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
> > source/TitleState.hx:711: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
> > source/TitleState.hx:713: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
> > source/TitleState.hx:717: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound
> > another error appeared
> > god damn
> 
> ok, no you fixed hxCodec but now there are new versions of flixel and flixel-addons troubles, you have to continue to downgrade them until the errors wont begone

the libs should be like this:
haxe 4.2.5

lime 8.0.1

openfl 9.2.1

flixel 5.2.2

flixel-addons 3.0.2

flixel-tools 1.5.1

flixel-ui 2.5.0

hxcpp 4.2.1

tjson 1.4.0

hxjsonast 1.1.0

hxCodec 2.5.1

hscript 2.5.0

hxcpp-debug-server 1.2.4

**Comment by CJ77GT6R** [comment]
thx for telling me

**Comment by NexIsDumb** [comment]
> thx for telling me

Np, tell me if it works now

**Comment by CJ77GT6R** [comment]
ok the version i will use is 2.5.1 (that would prob wok, i think)

**Comment by NexIsDumb** [comment]
> ok the version i will use is 2.5.1 (that would prob wok, i think)

It should work for sure like that, but trying never hurts

**Comment by CJ77GT6R** [comment]
another error appeared it says source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

**Comment by CJ77GT6R** [comment]
wait nevermind it works, thx, now i will close this

**Comment by CJ77GT6R** [comment]
source/Achievements.hx:132: characters 3-64 : (camera : flixel.FlxCamera, value : Bool) -> Void should be Array<flixel.FlxCamera>
ok this error is strange

**Comment by NexIsDumb** [comment]
> source/Achievements.hx:132: characters 3-64 : (camera : flixel.FlxCamera, value : Bool) -> Void should be Array<flixel.FlxCamera>
> ok this error is strange

Can i see the line?

**Comment by NexIsDumb** [comment]
> > source/Achievements.hx:132: characters 3-64 : (camera : flixel.FlxCamera, value : Bool) -> Void should be Array<flixel.FlxCamera>
> > ok this error is strange
> 
> Can i see the line?

Wait no, try to downgrade flixel-addons to 2.11.0

**Comment by CJ77GT6R** [comment]
ok

**Comment by CJ77GT6R** [comment]
i did but it still show up the error source/Achievements.hx:132: characters 3-64 : (camera : flixel.FlxCamera, value : Bool) -> Void should be Array<flixel.FlxCamera>

**Comment by SlickFromMars** [comment]
that's quite strange, can I see the snippet of the code?

**Comment by NexIsDumb** [comment]
> that's quite strange, can I see the snippet of the code?

Yea, it is odd

**Comment by CJ77GT6R** [comment]
> that's quite strange, can I see the snippet of the code?

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/130906399/a3c43c25-c5ac-4666-9d91-f643c52c2564)

**Comment by CJ77GT6R** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/130906399/219f8efb-9f2f-4d70-b1db-f6163b8e03ee)

**Comment by CJ77GT6R** [comment]
![gtrgfesfescddsadssdssfd](https://github.com/ShadowMario/FNF-PsychEngine/assets/130906399/0b0b4a2f-1368-4089-817d-e9fc6e518d81)

**Comment by SlickFromMars** [comment]
Very strange. I have that exact same code and it works fine.

**Comment by SlickFromMars** [comment]
> Me too, its prob about one of his libs versions maybe?

quite possible

**Comment by NexIsDumb** [comment]
> > Me too, its prob about one of his libs versions maybe?
> 
> 
> 
> quite possible

Hmmm

**Comment by NexIsDumb** [comment]
@CJ77GT6R could you tell us what lib did you download and what versions are them

**Comment by CJ77GT6R** [comment]
2. 5. 1

**Comment by NexIsDumb** [comment]
> 2. 5. 1

nono, not just hxCodec, i mean all the libs you have installed

**Comment by CJ77GT6R** [comment]
i forgore, ithink 2. 5. 1

**Comment by NexIsDumb** [comment]
> i forgore, ithink 2. 5. 1

you can check the versions on the command prompt, there are also guides online

**Comment by NexIsDumb** [comment]
> hold on how do i do that command
> 
> 
> 
> > > i forgore, ithink 2. 5. 1
> 
> > 
> 
> > you can check the versions on the command prompt, there are also guides online
> 
> 
> 
> 

There are a lot of tutorials online

**Comment by CJ77GT6R** [comment]
bruh, another shit appeared with the same mp4handler thingy and this
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'

**Comment by NexIsDumb** [comment]
> bruh, another shit appeared with the same mp4handler thingy and this
> source/Main.hx:85: characters 61-65 : Float should be Int
> source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
> source/Main.hx:85: characters 61-65 : ... For function argument 'child'
> 

thats probably cause you outdated something

**Comment by CJ77GT6R** [comment]
ok

**Comment by CJ77GT6R** [comment]
i need the current version of hxCodec

**Comment by NexIsDumb** [comment]
> i need the current version of hxCodec

hxCodec must be 2.5.1

**Comment by CJ77GT6R** [comment]
oh ok

**Comment by CJ77GT6R** [comment]
the error still shows up

**Comment by CJ77GT6R** [comment]
ok now how do i close this report

**Comment by NexIsDumb** [comment]
> ok now how do i close this report

Well like this we cannot for sure help ya so yeah
