### ISSUE TITLE
how to fix it

### ISSUE THREAD

**Issue by Shaunland** [ShadowMario/FNF-PsychEngine#12427]
### What is your question?

D:\shaun downloads\Countryballs Engine\Countryballs Engine\CountryballsEngine>lime test windows
Called from ? line 1
Called from CommandLineTools.hx line 1904
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 124
Called from CommandLineTools.hx line 1705
Called from lime/tools/ProjectXMLParser.hx line 21
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 50
Called from lime/tools/ProjectXMLParser.hx line 2042
Called from lime/tools/ProjectXMLParser.hx line 1670
Called from lime/tools/ProjectXMLParser.hx line 1538
Called from lime/tools/ProjectXMLParser.hx line 608
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 709
Called from /Users/runner/hostedtoolcache/haxe/4.2.5/x64/std/neko/_std/sys/FileSystem.hx line 69
Called from /Users/runner/hostedtoolcache/haxe/4.2.5/x64/std/neko/_std/sys/FileSystem.hx line 60
Uncaught exception - std@sys_file_type

**Comment by MemeHovy** [comment]
don't open duplicate issues
