### ISSUE TITLE
Not knowing on how to remove shaders

### ISSUE THREAD

**Issue by JustMe1352** [ShadowMario/FNF-PsychEngine#12424]
### Describe your problem here.

So I wanted to make it so then the shader runs but then it gets removed after a while. I know how to make it so then it could remove after a while but I didn't know how to remove the shader. Anything I did, just didn't work. I did a little coding to see if it would work but nothing. Could you help me? (All of this is on lua)

The coder I did:
("cross hatch" is the shader name)
removeLuaSprite("cross hatch")
removeSpriteShader("shaderImage", "cross hatch")

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
`removeSpriteShader("object")`

**Comment by JustMe1352** [comment]
> `removeSpriteShader("object")`

Doesn't work because it goes though haxe code

**Comment by frantastic24** [comment]
Not sure what you mean by that, it doesn't matter if the shader was made through runHaxeCode
It would help if you showed the code

**Comment by JustMe1352** [comment]
> Not sure what you mean by that, it doesn't matter if the shader was made through runHaxeCode It would help if you showed the code

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/130803298/f157c060-5c70-4e7c-9ead-f1d4ff23b365)

**Comment by frantastic24** [comment]
you want to disable the ShaderFilter on the cameras right? you can just do `setProperty('camGame.filtersEnabled', false)`

**Comment by JustMe1352** [comment]
> 

Thanks a lot
