### ISSUE TITLE
Stage: object order issue

### ISSUE THREAD

**Issue by Kirsenal** [ShadowMario/FNF-PsychEngine#12423]
### Describe your problem here.

I have come across an issue with stages. I have a few luasprites on this stage, right, and I have a bunch of fire images that have object orders of 9 and 10. There is a background image with an order of 5 that is supposed to be behind the fire, however for some reason it appears in front of it even though it has a lower objectorder. When I try and mess around with the other backrground images, then THEY appear in front, even though not a single one of them ever go above 9 and 10. Why is this happening?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by KELOTOMU** [comment]
Can I get the lua file?

**Comment by Kirsenal** [comment]
> Can I get the lua file?

Like you want me to send the script or the actual file cuz the script is kinda long

**Comment by KELOTOMU** [comment]
> 

Maybe the actual file.

**Comment by Kirsenal** [comment]
> Maybe the actual file.

How can I get that to you?
