### ISSUE TITLE
Haxe Version

### ISSUE THREAD

**Issue by KELOTOMU** [ShadowMario/FNF-PsychEngine#12422]
### What is your question?

Do you need the exact version Haxe 4.2.4 or can you go into newer versions of it?

**Comment by MemeHovy** [comment]
haxe 4.3 compiling is broken atm, so it's best to use haxe 4.2.5 atm

**Comment by MemeHovy** [comment]
via doing this in import.hx

put `#if !macro` surrounding `import Paths;`
