### ISSUE TITLE
RankingSubState.hx recreation

### ISSUE THREAD

**Issue by Stefan2008Git** [ShadowMario/FNF-PsychEngine#12430]
### Describe your bug here.

I just tried to recreate RankingSubState from Micd'UP Engine and then when i tested the latest build and i got the crash error :((
![Snimak ekrana 2023-05-16 235012](https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/68af92a4-bd28-4b96-9e09-551b35ed5d13)

### Command Prompt/Terminal logs (if existing)

```bash
``C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (Line 30)
Song.hx (Line 104)
RankingSubState.hx (Line 120)
flixel/FlxState.hx (Line 203)
flixel/FlxState.hx (Line 212)
flixel/FlxGame.hx (Line 752)
flixel/FlxGame.hx (Line 682)
flixel/FlxGame.hx (Line 556)
openfl/events/EventDispatcher.hx (Line 402)
openfl/display/DisplayObject.hx (Line 1399)

Uncaught Error: [file_contents,assets/data//.json]``
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Adding some new features

**Comment by MemeHovy** [comment]
missing json
