### ISSUE TITLE
Stage Switch Custom Command

### ISSUE THREAD

**Issue by SeriouslyAnimations** [ShadowMario/FNF-PsychEngine#1243]
### Describe your problem here.

Hey, Im trying to make a change stage command using the psych engine source code, what code should i put for it? (value 1 will change certain elements and value 2 will be the whole stage.)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by ShadowMario** [comment]
Need more information about what exactly you need help with. [this might help you but i'm not sure.](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Creating-an-Event)
