### ISSUE TITLE
Re-enabling pausing on inactive window

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#12433]
### What is your question?

I don't know how or why it happened, but I know it wasn't there before.
Each time I tab out of PE (any unmodified build), it just stays active for some reason.

The reason might be, that I somehow got a crash whilst playing the Mic Of Time Mod (which used PE), which also reset ALL of (regular) PE scores and achievements I had (again)

Anyways, is there any way, to enable it again? It like stays even persistent after a restart of the computer

**Comment by CaptainBaldi** [comment]
unless i'm interpreting this wrong probably just change FlxG's autoPause variable I think that's what controls it
