### ISSUE TITLE
Keep getting "Expected }" at line 4327

### ISSUE THREAD

**Issue by HenryBATIM** [ShadowMario/FNF-PsychEngine#12440]
### Describe your problem here.

So, I don't know if this would be the right place to ask for this, but I'mma shoot my shot here.
I am trying to code some stuff for a custom Psych build, and I keep getting an "Expected }" at line 4327.
I'm not sure what's happening, but if I could get some help here, that'd be appreciated.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/98790485/af84c215-fd73-46a0-8935-0b85feea9d6e)
(The error I keep getting)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/98790485/11975410-c38b-4461-92bc-d256e73a3e59)
(The code in question)

I am by no means a professional Haxe coder, so I may've done something wrong here.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added a variable, "ratingCamType" to ClientPrefs and VisualsUISubState, and did some editing of PlayState.

**Comment by NexIsDumb** [comment]
I guess you're kinda new in coding, lemme explain it easy to understand:
Whenever you want to add more than one line after a condition (in this case, the ifs) you MUST add (before the lines) { and then (after the lines) }, like this:

```haxe
if (conditionExample == true)
{
    lmfao = true;
    shutUp = false;
}
```

Or you can also do it like this when its just one line:

```haxe
if (conditionExample == true) lmfao = true;
```

Or also (still for multilines):

```haxe
if (conditionExample == true) {
    lmfao = true;
    shutUp = false;
}
```

Basically it doesnt matter the position of { or } if its next to the ) or down

**Comment by HenryBATIM** [comment]
Okay, thanks.
That's now resolved one of my issues as of currently.

**Comment by NexIsDumb** [comment]
> Okay, thanks.
> That's now resolved one of my issues as of currently.

if it got resolved, you can now close this issue as completed

**Comment by HenryBATIM** [comment]
Aight, thank you.

**Comment by NexIsDumb** [comment]
> Aight, thank you.

npp
