### ISSUE TITLE
Dialogue speed not working

### ISSUE THREAD

**Issue by TheRealPepsi** [ShadowMario/FNF-PsychEngine#12443]
### Describe your bug here.

Hello. I'm having an issue with Psych Engine's dialogue function. I'm changing the speed on the dialogue, and it slows down in the editor, but viewing it in the story mode just causes it to have default speed. Any help?

### Command Prompt/Terminal logs (if existing)

```bash
None
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

None

**Comment by TheRealPepsi** [comment]
I've tried other mods, and they have the same problem, I think it might just be a bug with Psych 0.6.3

**Comment by HapJim** [comment]
also got this problem but that's about all i can say, nothing seems to fix it that i currently know about

**Comment by JVvVvVvVvV** [comment]
Yo i had the same problem for awhile but i figured out the solution. In the file "DialougeBoxPsych.hx" Go to the line of code where it says "daText.sound = curDialogue.sound;" and underneath that line code write "daText.delay = curDialogue.speed;" This should fix the dialogue speed problem.

**Comment by TheRealPepsi** [comment]
Is there maybe a way to do so without source code? Thanks!
