### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by booeoff** [ShadowMario/FNF-PsychEngine#12454]
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/111623085/ab01e7ee-fe48-4d58-b105-93fb49985116)
so uhhhhh, just recharted a song i originally made in yoshi engine, and this error popped up when i tried to play it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no.

**Comment by vesel4ak** [comment]
missing charting
prabably u saved ur charting like "name" but wanted to play on hard. When u save ur charting like this u save it as normal difficulty. So u should do like this: "name-hard"
