### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by combatfox** [ShadowMario/FNF-PsychEngine#12457]
### Describe your bug here.

I was playing some FNF and majority of the time I was in free play mode so I'm tired of playing in Freeplay mode and I go to story mode and then the game crashed

### Command Prompt/Terminal logs (if existing)

```bash
StoryMenuState.hx (line 130)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

-----------------------------------------------------------------------------------
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I did not

**Comment by vesel4ak** [comment]
this problem appears when some of ur files are missing.  u could delete important files so better not touch any game files except characters and songs.
