### ISSUE TITLE
somethings wrong with vocals

### ISSUE THREAD

**Issue by st0lent0aster** [ShadowMario/FNF-PsychEngine#12453]
### Describe your bug here.

before you say name the vocals voices, i have already named the vocals voices.

i was making a chart, the vocals work for the charting menu, but not when i test the songs chart.
i redownloaded psych engine because i thought something was wrong with the application, but for every psych engine i downloaded, it never worked. i tried remaking the chart and that didnt work. is it okay if you could help, but if not, its totally understandable.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i renamed the vocals to voices

**Comment by RushMyster** [comment]
Is the "Has voice track" enabled in the "song" section on the chart editor? I think thats what the problem is

**Comment by st0lent0aster** [comment]
uh idk i will check

**Comment by st0lent0aster** [comment]
oh, i found it. thanks!
