### ISSUE TITLE
I have created a stage in lua script with an animated object

### ISSUE THREAD

**Issue by duckyduck1q** [ShadowMario/FNF-PsychEngine#1245]
### Describe your problem here.

my problem is that I have created a stage in lua script and when I test it it gives me the error: mods / stages / 1.lua: 7: ')' expected near 'mii' the stage code is:

function onCreate ()

- background shit
makeLuaSprite ('stageback', 'stageback', -500, -300);
setLuaSpriteScrollFactor ('stageback', 0.9, 0.9);

        makeAnimatedLuaSprite ('mii,' mii ', -500, -300)
setLuaSpriteScrollFactor ('mii', 1.17, 1.17);
scaleObject ('mii', 1, 1);
addAnimationByPrefix ('mii', 'float', 'stagecurtains', 24, true)
             
- sprites that only load if Low Quality is turned off
if not lowQuality then

end

addLuaSprite ('stageback', false);

        objectPlayAnimation ('buttons', 'float', false)

close (true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i created a stage in lua script

**Comment by ShadowMario** [comment]
`makeAnimatedLuaSprite ('mii,'`
you've put the `'` after the `,`
