### ISSUE TITLE
how to make bf afraid at a certain time

### ISSUE THREAD

**Issue by vesel4ak** [ShadowMario/FNF-PsychEngine#12450]
### Describe your problem here.

dfg

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheRealPepsi** [comment]
Do you have bf afraid sprites?

**Comment by TFLTV** [comment]
play animation event maybe
