### ISSUE TITLE
how to use the "Key Press Functions"?

### ISSUE THREAD

**Issue by DEV-idiotXD** [ShadowMario/FNF-PsychEngine#1246]
### What is your question?

cuz im wondering how to use it is it like

keyPressed(name)
if name == 'down' then
setProperty('health', -500)

or

key_pressed = keyPressed('down')

if key_pressed == true then
setProperty('health', -500)

just pleae tell me

also can i use other keys than the normal keys?

**Comment by ShadowMario** [comment]
`key_pressed = keyPressed('down')`
This way.

You can detect a keyboard press from a specific key with `getPropertyFromClass('flixel.FlxG', 'keys.justPressed.INSERTKEYNAMEHERE')`

List of keys: https://api.haxeflixel.com/flixel/input/keyboard/FlxKey.html
List of FlxG.keys methods: https://api.haxeflixel.com/flixel/input/FlxKeyManager.html

**Comment by DEV-idiotXD** [comment]
thx!

**Comment by Gabopogi01** [comment]
same thx
