### ISSUE TITLE
Issue creating mod song

### ISSUE THREAD

**Issue by stuebbie** [ShadowMario/FNF-PsychEngine#12467]
### Describe your bug here.

Hi - I was trying to set up a FnF mod following the steps on https://www.wikihow.com/Make-a-Friday-Night-Funkin%27-Mod

However, when I get to the point of creating a chart for our mod game, I get the following error:

C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
FreeplayState.hx (line 371)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/mod-song-2/mod-song-2-easy-normal-hard.json]

This is the same for any of the mod songs we've created, with the only difference being the json file location on the error.

I apologise in advance if there's a really simple solution to this, any help is appreciated.

### Are you modding a build from source or with Lua?

From Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added new folders to mods/data, /mods/songs, /mods/characters

**Comment by TheOfficialSwords** [comment]
you're attempting to play a song on the "hard" difficulty, which is (presumably) not in the song's data directory.

try playing the song at normal difficulty or rename your song's json to have a "-hard" at the end.
