### ISSUE TITLE
Weird Errors with FlxSound.

### ISSUE THREAD

**Issue by AceThePan** [ShadowMario/FNF-PsychEngine#12464]
### Describe your problem here.

So, I'm trying to build the engine and I'm coming up with these errors:

source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
/Users/MyUser/Documents/GitHub/FunkinCorruption/.haxelib/flixel/5,3,1/flixel/animation/FlxAnimation.hx:231: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
/Users/MyUser/Documents/GitHub/FunkinCorruption/.haxelib/flixel-addons/3,1,1/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/editors/ChartingState.hx:2201: characters 14-20 : Cannot access private field _sound
source/editors/ChartingState.hx:2201: characters 38-44 : Cannot access private field _sound
source/editors/ChartingState.hx:2202: characters 29-35 : Cannot access private field _sound
source/editors/ChartingState.hx:2205: characters 12-18 : Cannot access private field _sound
source/editors/ChartingState.hx:2218: characters 14-20 : Cannot access private field _sound
source/editors/ChartingState.hx:2218: characters 38-44 : Cannot access private field _sound
source/editors/ChartingState.hx:2219: characters 29-35 : Cannot access private field _sound
source/editors/ChartingState.hx:2222: characters 12-18 : Cannot access private field _sound
/Users/MyUser/Documents/GitHub/FunkinCorruption/.haxelib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't!

**Comment by ExtractGames** [comment]
apparently i'm facing the same problem too, I can;t Fix It Yet
