### ISSUE TITLE
how do i fix this error

### ISSUE THREAD

**Issue by st0lent0aster** [ShadowMario/FNF-PsychEngine#12465]
### Describe your problem here.

when i was trying to input custom characters, it gave me this error
![Screenshot 2023-05-23 121243](https://github.com/ShadowMario/FNF-PsychEngine/assets/134238041/e871d088-91c4-4171-a9ec-680df3619429)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by vesel4ak** [comment]
probably missing sprites or invalid character's name
