### ISSUE TITLE
Tried to move 2 objects, but moves only the last one

### ISSUE THREAD

**Issue by NavaGaming** [ShadowMario/FNF-PsychEngine#12475]
### Describe your problem here.

```
function onUpdate(elapsed)

		songPos = getSongPosition()
  
		local currentBeat = (songPos/1000)*(bpm/80)
       
    doTweenY(thingTweenY, 'thing', -11 -41*math.sin((currentBeat*0.15)*math.pi),0.001)    
    doTweenY(thingyTweenY, 'thingy', -10 -40*math.sin((currentBeat*0.15)*math.pi),0.001)    
      
    end
```

I already asked that crap before, but not really understood the anwser, im just silly.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JVgradiz** [comment]
Isn't it better to use
setProperty('thing.y', -11 -41*math.sin((currentBeat*0.15)*math.pi))
setProperty('thingy.y', -10 -41*math.sin((currentBeat*0.15)*math.pi))

**Comment by NavaGaming** [comment]
> Isn't it better to use setProperty('thing.y', -11 -41_math.sin((currentBeat_0.15)_math.pi)) setProperty('thingy.y', -10 -41_math.sin((currentBeat*0.15)*math.pi))

Well, it's not really works

**Comment by NavaGaming** [comment]
Wait, it does.

**Comment by JVgradiz** [comment]
> Wait, it does.

glad i could help
