### ISSUE TITLE
some effects disappeared after I ported the mod from one engine to another engine

### ISSUE THREAD

**Issue by vesel4ak** [ShadowMario/FNF-PsychEngine#12472]
### Describe your problem here.

i ported "Mandela Z-Mixed" from developer's modified Psych engine to a default psych engine. Then some visual effects like static, chromatic aberration. The image has become clear, but I don't need it. Whats problem? Can i fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheOfficialSwords** [comment]
check the mod's source code, it'll usually have some stuff that's not in the lua scripts of a source mod also utilizing lua. _coff coff vs impostor_
