### ISSUE TITLE
no shader, although there should be

### ISSUE THREAD

**Issue by vesel4ak** [ShadowMario/FNF-PsychEngine#12474]
### Describe your problem here.

i have this shader from "Mandela Z-Mixed" mod
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/119149152/0283dc93-8124-4ecb-b79d-b1c6ddf6402d)
there is some issues in OS Engine, so i ported mod into psych engine. But shader isnt working. I didnt edit any game files, but just copied. 
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/119149152/03cefc50-62d7-40ad-8876-a2ddff31458c)
Shader isnt working. Why? Can i fix this somehow??? Next, I will attach screenshots on the original OS Engine, then a port on the Psych Engine
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/119149152/7adb0794-562d-4d28-a738-bd5c068df571)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/119149152/44ee6a73-d18e-46f3-803b-9bad24792b1b)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by SlickFromMars** [comment]
``addVCREffect()`` seems to be a custom function from the original mod. you might need to edit your lua file

**Comment by glowsoony** [comment]
the function for a VCR Shader was an old psych function, and was removed, so it's not a bug, you may need to use old psych builds to port it or update the SC to have the shader. or instead using a .frag that contains the VCR Shader! and then add it via scripts.

**Comment by vesel4ak** [comment]
> `addVCREffect()` seems to be a custom function from the original mod. you might need to edit your lua file

What I need to edit?

**Comment by glowsoony** [comment]
> > `addVCREffect()` seems to be a custom function from the original mod. you might need to edit your lua file
> 
> What I need to edit?

check the old psych builds or search for a .frag file.

**Comment by TheOfficialSwords** [comment]
that is an old psych function not present in latest versions anymore.

if you'd like to, head over to the [psych engine discord server](https://discord.gg/psychengine) and pick up this [vcr shader port](https://discord.com/channels/922849922175340586/1054432114197671977) created by solar.
