### ISSUE TITLE
Text error

### ISSUE THREAD

**Issue by Gavinator96** [ShadowMario/FNF-PsychEngine#12477]
### Describe your problem here.

For some reason, all the letters are % when I didn't change anything and I don't know how to fix it. If anyone knows how to fix this, please tell me how because I want to play this mod on the newest version of psych engine.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/99510438/c7f731d1-8375-40e0-b934-d73c362e42ff)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I imported Arcade Showdown to v0.6.3 and pasted every file from the assets and mods folders from Arcade Showdown into a folder inside of my mods folder.

**Comment by Gavinator96** [comment]
Also when I go into any song the game crashes and gives me a null object reference error.

**Comment by Lorekeeper49** [comment]
The text error is due to there being a new alphabet you need to put in the files
