### ISSUE TITLE
Help with using lua to trigger a mid-song alt animation

### ISSUE THREAD

**Issue by Tailikku** [ShadowMario/FNF-PsychEngine#12487]
### Describe your problem here.

Hi I've been struggling on my own for a little while and think it's time to ask for help because I am not a coder

I've got a hold of a script (courtesy of kiitoliroo over [here](https://gamebanana.com/mods/401461) ) that changes the animations of characters based on the combo counter. The goal isn't to use this with Boyfriend, but to instead use this with a custom Girlfriend.

The script is: 
```
local hitCombo = 0

function goodNoteHit(id, direction, noteType, isSustainNote)
    if not isSustainNote then
        hitCombo = getProperty(hitCombo)+ 1
    end
end

function noteMiss(id, direction, noteType, isSustainNote)
    if getProperty('songMisses')+ 1 then
		hitCombo = 0
	end
end

function onUpdatePost()
	if hitCombo >= 10 then -- this is the combo counter requirement. Change as needed.
		triggerEvent('Alt Idle Animation', 'GF', '-alt');
	end
	if hitCombo == 0 then
		triggerEvent('Alt Idle Animation', 'GF', '');
    end
end
```

The part I've been struggling with is that I can't seem to make this work mid-song, and I'm not sure why. I've verified through the debug menu/chart event that the GF does have working Alt Animations, and if I set the required hitCombo to 0 (and delete/change the part under it so it doesn't conflict), the script will activate and set Alt Animations on before the countdown. So that part works, sort of.

The issue is that I don't know how or why the script doesn't work mid-song. If I set the Combo Counter Requirement to anything higher than 0, then nothing will change mid-song. The combo counter will go above the requirement, but nothing will change. The same is true in reverse, as well. If I start the requirement at 0, and having any combo at all is set to undo the Alt Idle stuff, nothing will change there either.

To me, a non-coder, all of my toying around with this is leading me to believe that the script is not firing during the song for some reason that I'm not catching. I'd wonder if it was even possible if the gamebanana page didn't exist with most people saying it worked for them, or if I didn't know about Agent Girlfriend in that one 'Incident: 012F' mod doing basically exactly what I'm trying to do in (an earlier version of) Psych Engine

Is there an obvious error that I'm not seeing? Should I upload the GF json in case something is wrong there? (I will do that.) Record what I'm doing? Has this been asked before?

I'd love any pointers in the right direction.

[GenevaStanding.json but converted to a text file](https://github.com/ShadowMario/FNF-PsychEngine/files/11585440/GenevaStanding.txt)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added custom characters, one of which has alternate animations. Everything else is vanilla Psych Engine 0.6.3

**Comment by TheLeerName** [comment]
>     if getProperty('songMisses')+ 1 then
where condition

**Comment by Tailikku** [comment]
I totally forgot I put this request out, but the good news is that I think I have the script I want after stubbornly coming back to it a few times. The code I have now, which seems to be working, is this: 
```
local Combo = 0

function goodNoteHit(id, direction, noteType, isSustainNote)
    if not isSustainNote then 
        Combo = Combo + 1 
    end
	if Combo >= 10 then -- Combo Requirement
		triggerEvent('Alt Idle Animation','GF','-alt')
	end
end

function noteMiss(id, direction, noteType, isSustainNote)
    if getProperty('songMisses')+ 1 then
		triggerEvent('Alt Idle Animation', 'GF', '')
		Combo = 0
	end
end
```

I realized I didn't need an onUpdate function for my purposes (I hope) and cut that out, shuffling the tasks it had into the count and miss functions instead. Also, the original `hitCombo = getProperty(hitCombo)+ 1` seems to work if I remove the `getProperty` part of it.

And now I'm afraid to touch anything else. 

The combo count is working and puts GF in Alt Idle when the number is reached, it's properly booting GF back out of her Alt Idle when a miss happens, and building the combo back up again puts GF back into her Alt Idle, telling me that there's no problem redoing the process. It all works, and that's good enough for me.
