### ISSUE TITLE
Is there any way to get mod charts of Psych Engine to the lastest Kade Engine?

### ISSUE THREAD

**Issue by tomasxd12** [ShadowMario/FNF-PsychEngine#12485]
### What is your question?

Soo, i tried this like since 1 day like this: the .ogg files into songs (or so)  and the mod.json too. When i try to load it, it stops responding. Anyway around this like making it manually?

**Comment by tomasxd12** [comment]
Anw its 3am soo bye

**Comment by Lorekeeper49** [comment]
No, they work way too differently for that to work

**Comment by tomasxd12** [comment]
Well normal songs does expect those that have events that kade engine does not have, expect the mod things. The 2nd way is someway porting that sound or downloading the old version that ( if was Kade Engine, its gonna run)

**Comment by tomasxd12** [comment]
So do i close this?
