### ISSUE TITLE
How To Do TweenColor In No Time

### ISSUE THREAD

**Issue by BillyLOLwkwk** [ShadowMario/FNF-PsychEngine#12488]
### Describe your problem here.

Actually my problem is i want to change boyfriend skin to blue color. But i dont know what variable to change the color so i use tweenColor on him. But Actually if we want to do a tween, we need time input, but everytime i put 0 as the time, it cant be worked.  So does anyone know how to edit it ?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

NO

**Comment by frantastic24** [comment]
`setProperty('boyfriend.color', hex)`

**Comment by BillyLOLwkwk** [comment]
> `setProperty('boyfriend.color', hex)`
i got black color instead to my boyfriend

**Comment by TheOfficialSwords** [comment]
> you messed up the hex color
> `0xFFFFFF` change this to whatever you need

.color only supports hexadecimals. Use getColorFromHex(hex:String) if you wanna use hex codes.

_ex:_ `setProperty('boyfriend.color', getColorFromHex('0000FF'))`

**Comment by frantastic24** [comment]
`0xFFFFFF` is hex already

**Comment by TheOfficialSwords** [comment]
> `0xFFFFFF` is hex already 

that... still won't work?

**Comment by frantastic24** [comment]
It works just fine on my end
