### ISSUE TITLE
running C code with lua FFI

### ISSUE THREAD

**Issue by Doge2Dev** [ShadowMario/FNF-PsychEngine#12494]
### Describe your bug here.

So I was testing FFI with lua using a game framework.
I saw that running from pcall the FFI worked, when I remember that Psych Engine uses lua as scripting language to modding.
so I tried run C code on a lua script in psych just to test.
*also yes I tested without the lua installed on my computer, also uninstalled love (the game framework I mentioned)*

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheLeerName** [comment]
idk what u tryna to do but here example of it (properly getting scroll/num/lock pressed)
```lua
ffi = require "ffi"
ffi.cdef [[
	int GetKeyState(int key);
]]
-- https://learn.microsoft.com/ru-ru/windows/win32/inputdev/virtual-key-codes
function getScrollLockPressed() return bit.band(ffi.C.GetKeyState(0x91), 0x0001) ~= 0 end
function getNumLockPressed() return bit.band(ffi.C.GetKeyState(0x90), 0x0001) ~= 0 end
function getCapsLockPressed() return bit.band(ffi.C.GetKeyState(0x14), 0x0001) ~= 0 end

function onUpdate(elapsed)
	if getCapsLockPressed() then
		-- code
	end
end
```
