### ISSUE TITLE
how do I fix Error: Could not find haxelib "hxCodec", does it need to be installed?

### ISSUE THREAD

**Issue by JergamerGamer11** [ShadowMario/FNF-PsychEngine#12493]
### What is your question?

how do I fix the Error? Error: Could not find haxelib "hxCodec", does it need to be installed?

**Comment by MemeHovy** [comment]
because you didn't install hxCodec

**Comment by JergamerGamer11** [comment]
crap thx.

**Comment by MemeHovy** [comment]
> crap thx.

yw
