### ISSUE TITLE
Animation on stage play on beat???

### ISSUE THREAD

**Issue by Kirsenal** [ShadowMario/FNF-PsychEngine#12497]
### Describe your problem here.

So, I have a sprite in the background that is supposed to be a character, and I want her animation to play on beat, or like every 2 beats maybe like how normal characters' idle does. I turned off the loop:

makeAnimatedLuaSprite('obj3', 'rabblerouser', -230, 46)
	setObjectOrder('obj3', 1)
	addAnimationByPrefix('obj3', 'no_loop', 'rabble0', 12, false)
	playAnim('obj3', 'anim', true)
	addLuaSprite('obj3', true)

How do I make it go on beat? I tried putting a certain amount of frames in the xml and it for some reason played the animation on beats 2 and 4, and when I tried using skipCountdown her animation was just a tiny bit delayed. What can I do to make it on beat like that?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
[wiki has script examples](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API)
