### ISSUE TITLE
How to make opponent drain hp with notes but without sustain ones?

### ISSUE THREAD

**Issue by NavaGaming** [ShadowMario/FNF-PsychEngine#12498]
### Describe your problem here.

```
function goodNoteHit(noteID, noteDir, noteType, noteSustain)
    if noteSustain then
        setProperty('health', getProperty('health')-getPropertyFromGroup('notes', noteID, 'hitHealth'));
```
Something like this, but for opponent

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
opponentNoteHit :skull:

**Comment by NavaGaming** [comment]
> opponentNoteHit 💀

That's amazing!
It's not works.

**Comment by NavaGaming** [comment]
> > opponentNoteHit 💀
> 
> That's amazing! It's not works.

Oh, well, it is kinda working now, but in the most weird way possible
