### ISSUE TITLE
IDK what the bug is lol I cant even read this

### ISSUE THREAD

**Issue by SomeGDPerson123** [ShadowMario/FNF-PsychEngine#12490]
### Describe your bug here.

IDK what the bug is lol I cant even read this
Error occurs when I try to enter ANY song.
Please do mod fixing
![Screenshot 2023-05-29 081251](https://github.com/ShadowMario/FNF-PsychEngine/assets/134952617/b3e16e65-e490-4660-a43a-0c1109c26b0a)

### Command Prompt/Terminal logs (if existing)

```bash
Error!
Paths.hx (line 356)
Playstate.hx (line 4100)
Playstate.hx (line 1377)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes. I added some mods that were compatible with 0.6.3, then I tweaked one of them's text displays. Now this error pops up even when I remove the file.

**Comment by TheLeerName** [comment]
one of these mods breaked game

**Comment by SomeGDPerson123** [comment]
oh ok thanks
