### ISSUE TITLE
character changes error

### ISSUE THREAD

**Issue by Kosta66** [ShadowMario/FNF-PsychEngine#12499]
### Describe your problem here.

when trying to use the event, the character change happens (if possible, how can I fix it?)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

нет
https://github.com/ShadowMario/FNF-PsychEngine/assets/135017499/e4920659-e864-45c2-aa13-8b14f028d1ae

**Comment by Kosta66** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/assets/135017499/b1b880f3-2867-45be-afcb-b47325f42225

**Comment by TheLeerName** [comment]
which event
