### ISSUE TITLE
chart menu not working wtf

### ISSUE THREAD

**Issue by toadz77** [ShadowMario/FNF-PsychEngine#12492]
### Describe your bug here.

Whenever i use the engine and go to the chart editor it does not work properly just look at the reference video: https://www.youtube.com/watch?v=mba1qCo7KdA 

and NO. its not obs lag.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, it happens on any build

### end

**Comment by CaptainBaldi** [comment]
dumbass turn off disable autoscroll :skull:

**Comment by toadz77** [comment]
srry

**Comment by toadz77** [comment]
bruh dont call me a dumass IM SORRY
