### ISSUE TITLE
Adding Custom Stages

### ISSUE THREAD

**Issue by darklink064** [ShadowMario/FNF-PsychEngine#125]
Hi, I'm trying to add a custom stage (specifically the alley from VS Whitty, which is a just reskin of the Week 1 stage), but whenever I load the song, none of the assets load and the background is black. How can I get the assets to load? I can't find a place where they work.

**Comment by FuseIsHere813** [comment]
Are you using the downloaded build? If so, put the stage under "mods/stages".
If you are using source, put the stage under "assets/stages".

**Comment by darklink064** [comment]
I've tried putting both the HSCRIPT and PNG files in the mods/stages folder, and it didn't work
(Yes I'm using the download build incase that wasn't apparent)

**Comment by FuseIsHere813** [comment]
You were suppose to use the JSON format like the base game has, so that might be the problem.

**Comment by darklink064** [comment]
Let me check that rq

**Comment by darklink064** [comment]
That didn't work

**Comment by darklink064** [comment]
So let me get this straight I'm supposed to put the JSON and PNGs there in "mods/stages"?

**Comment by ShadowMario** [comment]
No, just the Json/Lua file for your stage, the Wiki says that all images should be inside mods/images/

And Hscript is not supported, there's literally an example stage on the Wiki
