### ISSUE TITLE
Flx.sound problem

### ISSUE THREAD

**Issue by Warlokk28** [ShadowMario/FNF-PsychEngine#12504]
### Describe your bug here.

source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
C:/haxelib/flixel/5,3,1/flixel/animation/FlxAnimation.hx:231: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
source/PlayState.hx:79: characters 8-22 : Type not found : vlc.MP4Handler
C:/haxelib/flixel-addons/3,1,1/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/FreeplayState.hx:447: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:447: characters 25-31 : ... For function argument 'Object'
source/FunkinLua.hx:442: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:460: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:466: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:518: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:524: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:564: lines 564-568 : Int should be Bool
source/FunkinLua.hx:564: lines 564-568 : ... For function argument 'f'
source/PlayState.hx:1925: characters 13-23 : Type not found : MP4Handler
source/FunkinLua.hx:2180: lines 2180-2183 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2180: lines 2180-2183 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object'
source/PlayState.hx:672: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:672: characters 25-35 : ... For function argument 'Object'
source/PlayState.hx:2740: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2740: characters 23-29 : ... For function argument 'Object'
source/PlayState.hx:2741: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2741: characters 23-83 : ... For function argument 'Object'
source/PlayState.hx:2131: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2131: characters 25-37 : ... For function argument 'Object'
source/PlayState.hx:2178: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2178: characters 25-34 : ... For function argument 'Object'
source/PlayState.hx:2249: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2249: characters 25-36 : ... For function argument 'Object'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1383: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1383: characters 24-30 : ... For function argument 'Object'
source/editors/ChartingState.hx:2226: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/haxelib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
source/TitleState.hx:734: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:736: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:740: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound
PS D:\Games\FNF-AdventureEdition\FNF-PsychEngine-0.6.3> haxelib run lime build windows
 *  History restored 

source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
C:/haxelib/flixel/5,3,1/flixel/animation/FlxAnimation.hx:231: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
source/PlayState.hx:79: characters 8-22 : Type not found : vlc.MP4Handler
C:/haxelib/flixel-addons/3,1,1/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/FreeplayState.hx:447: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:447: characters 25-31 : ... For function argument 'Object'
source/FunkinLua.hx:442: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:460: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:466: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:518: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:524: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:564: lines 564-568 : Int should be Bool
source/FunkinLua.hx:564: lines 564-568 : ... For function argument 'f'
source/PlayState.hx:1925: characters 13-23 : Type not found : MP4Handler
source/FunkinLua.hx:2180: lines 2180-2183 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2180: lines 2180-2183 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object'
source/PlayState.hx:672: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:672: characters 25-35 : ... For function argument 'Object'
source/PlayState.hx:2740: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2740: characters 23-29 : ... For function argument 'Object'
source/PlayState.hx:2741: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2741: characters 23-83 : ... For function argument 'Object'
source/PlayState.hx:2131: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2131: characters 25-37 : ... For function argument 'Object'
source/PlayState.hx:2178: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2178: characters 25-34 : ... For function argument 'Object'
source/PlayState.hx:2249: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2249: characters 25-36 : ... For function argument 'Object'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1383: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1383: characters 24-30 : ... For function argument 'Object'
source/editors/ChartingState.hx:2226: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/haxelib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
source/TitleState.hx:734: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:736: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:740: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound 

how to fix it?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i changed like half of source code

**Comment by Stefan2008Git** [comment]
Use flixel-addons 4.11

**Comment by Stefan2008Git** [comment]
> how to install it

``haxelib install flixel-addons 4.11.0`` i think

**Comment by Warlokk28** [comment]
Error: No such version 4.11.0 for library flixel-addons

**Comment by Warlokk28** [comment]
dont work :(((
