### ISSUE TITLE
Issue! Please help.

### ISSUE THREAD

**Issue by MazerslamTheProot** [ShadowMario/FNF-PsychEngine#12500]
### Describe your problem here.

It says this. AND I DONT KNOW HOW THE HELL TO READ CRASH HANDLER (IGNORE THE MODDING BUILD FROM SORCE OR LUA. I WAS ONLY MODDING VIA FILES)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 318)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 99)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 117)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 90)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 90)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
Song.hx (line 140)
Song.hx (line 132)
editors/ChartingState.hx (line 2957)
editors/ChartingState.hx (line 434)
Prompt.hx (line 44)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid char 103 at position 218
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I tried to add a cover of Test. :(

**Comment by powermeter2** [comment]
![image_2023-05-31_191811667](https://github.com/ShadowMario/FNF-PsychEngine/assets/135180547/b4bc3151-88e6-4b8f-9c9f-02f6153e36b9)
Same

**Comment by powermeter2** [comment]
kinda having the same issue

**Comment by VoidedBattery** [comment]
You'll have to read the source code on the website, along with the files

the lines (like line 99) should give insight on what was read wrong and where it went bad

**Comment by TheLeerName** [comment]
its just corrupted json, maybe u forgot comma or bracket

**Comment by MazerslamTheProot** [comment]
wow shadowmario said: this is done now
