### ISSUE TITLE
I need help compiling my game as it come up with this long error.

### ISSUE THREAD

**Issue by oliver6boy** [ShadowMario/FNF-PsychEngine#12507]
### Describe your problem here.

I typed in lime test windows and it came up with this :
C:/HaxeToolkit/haxe/lib/discord_rpc/1,0,0/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : (WDeprecated) flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : (WDeprecated) flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : (WDeprecated) flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/animation/FlxAnimation.hx:231: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'Object'
source/FunkinLua.hx:491: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:509: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:515: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:567: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:573: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:613: lines 613-617 : Int should be Bool
source/FunkinLua.hx:613: lines 613-617 : ... For function argument 'f'
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler
source/FunkinLua.hx:2221: lines 2221-2224 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2221: lines 2221-2224 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object'
source/PlayState.hx:582: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:582: characters 25-35 : ... For function argument 'Object'
source/PlayState.hx:2433: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2433: characters 23-29 : ... For function argument 'Object'
source/PlayState.hx:2434: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2434: characters 23-83 : ... For function argument 'Object'
source/PlayState.hx:1826: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1826: characters 25-37 : ... For function argument 'Object'
source/PlayState.hx:1873: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1873: characters 25-34 : ... For function argument 'Object'
source/PlayState.hx:1944: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1944: characters 25-36 : ... For function argument 'Object'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : (WDeprecated) flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1359: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1359: characters 24-30 : ... For function argument 'Object'
source/editors/ChartingState.hx:2193: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
source/TitleState.hx:723: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:725: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:729: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/util/FlxDestroyUtil.hx:3: characters 8-32 : You cannot access the flash package while in a macro (for flash.display.BitmapData)
source/animateatlas/AtlasFrameMaker.hx:2: characters 8-34 : ... referenced here
source/Paths.hx:3: characters 8-36 : ... referenced here
C:\Users\olive\Downloads\FNF-PsychEngine-0.6.3\FNF-PsychEngine-0.6.3\source\import.hx:1: characters 8-13 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/media/AudioSource.hx:138: characters 53-100 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/media/Sound.hx:14: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/utils/Assets.hx:9: characters 8-26 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/text/_internal/TextEngine.hx:9: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/_internal/CairoTextField.hx:3: characters 8-40 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/_internal/CairoGraphics.hx:6: characters 8-36 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/events/RenderEvent.hx:4: characters 8-44 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/DisplayObject.hx:13: characters 8-33 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here

Pls help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No ive just added haxe

**Comment by exhaustedle** [comment]
oh yeah i have the same exact problem I cant find the fix for some reason..

**Comment by oliver6boy** [comment]
Ok, at least I know that im not the only one...

**Comment by NightmaresPlayz** [comment]
Same thing with me

**Comment by TheLeerName** [comment]
### [source of message (join psych engine discord server)](https://discord.com/channels/922849922175340586/1108107923391008949/1108107923391008949)

# Deprecation warnings
Original: https://discord.com/channels/922849922175340586/931776548250468382/1104897104079507456
**Note these changes will remove all notices about functions and stuff being removed.**
*  For a permanent fix, Add `<haxedef name='no-deprecation-warnings' />` to your Project.xml above `</project>`.  For a temporary fix, add `-Dno-deprecation-warnings` to the command for compiling the game for a temporary fix
# source/Paths.hx:3: characters 8-36 : ... referenced here
Original: https://discord.com/channels/922849922175340586/931776548250468382/1102511827713265734
* Replace `import Paths;` with `#if(!macro) import Paths; #end` in your Import.hx
# flixel.system.FlxSound errors
Psych uses a custom FlxSound to allow for sound pitching, Flixel has done some updates and broken it, so we have to remove it by doing **all** of the following:
* Remove FlxSound.hx from your source code folder(Usually under source/flixel/system)
* Replace every instance of `import flixel.system.FlxSound;` with `import flixel.sound.FlxSound;`
* In source/editors/ChartingState.hx, add `@:privateAccess {` right above `if (FlxG.save.data.chart_waveformInst) {` around line 2195 add a `}` right after one of the `}` around line 2227
* If you get errors relating to pitch, comment any line that references the `pitch` field of a sound. You can just compile the game to see what (FILE):(LINE) have the issue

# flixel.animation.FlxAnimationController missing numFrames or getFrameDuration
* Open source > flixel > animation > FlxAnimationController.hx
* Delete everything inside of the file
* Replace it with the contents of https://gist.githubusercontent.com/superpowers04/0b01e40e0f272d134f87c5c30712cb66/raw/2366ea0b8d34b08c74119e22f7690d29e63e7f43/FlxAnimationController.hx

**Comment by oliver6boy** [comment]
Thank i will try it out!
