### ISSUE TITLE
Reflection inaccessible in Lua via runHaxeCode

### ISSUE THREAD

**Issue by Templarfreak** [ShadowMario/FNF-PsychEngine#12511]
### Describe your bug here.

Reflection is inaccessible while executing a HaxeScript via the runHaxeCode Lua function. Reflect is a standard class that should be accessible anywhere, it's not even a package that you can import. Interestingly, the error doesn't even get reported unless you try/catch it.

Example Lua code:

```
	runHaxeCode([[
	var abcdefg:Float = 0;
	try 
	{ 
		abcdefg = Reflect.getProperty(game.boyfriend, "x"); 
	} 
	catch(e:Any) 
	{ 
		trace(e); 
	}
	]]);
```

### Command Prompt/Terminal logs (if existing)

```bash
hscript:8: hscript:4: Unknown variable: Reflect
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CaptainBaldi** [comment]
I swear I've seen people use Reflect in their HaxeScript script's before.
Maybe they were using some other method for it who knows.

**Comment by TheLeerName** [comment]
💀💀💀
```lua
addHaxeLibrary("Reflect")
```

**Comment by Templarfreak** [comment]
ok, just importing the class itself does work, my b
