### ISSUE TITLE
Error Compile OS Engine

### ISSUE THREAD

**Issue by Wuznick** [ShadowMario/FNF-PsychEngine#12515]
### Describe your problem here.

OS Engine Error: source/Discord.hx:4: 8-30 characters: ... referenced here
source/Main.hx:20: characters 8-15: ... referenced here
I use lime test neko

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited nothing

**Comment by TheKitBoi** [comment]
try `lime test windows`

**Comment by Wuznick** [comment]
Got many mistakes

**Comment by Wuznick** [comment]
C:/HaxeToolkit/haxe/lib/discord_rpc/git/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
source/Alphabet.hx:200: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
source/editors/ChartingState.hx:149: characters 13-21 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:103: characters 40-48 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:150: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:240: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
source/FreeplayState.hx:242: characters 27-35 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:27: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:103: characters 68-76 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1762: characters 13-23 : Type not found : MP4Handler
source/FunkinLua.hx:2054: characters 18-26 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:2088: characters 18-26 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:65: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:346: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:348: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:602: characters 22-30 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2597: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2599: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2602: characters 27-35 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1967: characters 22-30 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1967: characters 37-45 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2014: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2014: characters 34-42 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2085: characters 21-29 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2085: characters 36-44 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:1452: characters 16-24 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:2311: characters 14-22 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:2312: characters 14-20 : Cannot access private field _sound
source/editors/ChartingState.hx:2312: characters 38-44 : Cannot access private field _sound
source/editors/ChartingState.hx:2313: characters 29-35 : Cannot access private field _sound
source/editors/ChartingState.hx:2316: characters 12-18 : Cannot access private field _sound
source/editors/ChartingState.hx:2328: characters 14-22 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:2329: characters 14-20 : Cannot access private field _sound
source/editors/ChartingState.hx:2329: characters 38-44 : Cannot access private field _sound
source/editors/ChartingState.hx:2330: characters 29-35 : Cannot access private field _sound
source/editors/ChartingState.hx:2333: characters 12-18 : Cannot access private field _sound
source/editors/EditorPlayState.hx:39: characters 13-21 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:110: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:112: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
source/TitleState.hx:329: characters 58-61 : Float should be flixel.util.FlxAxes
source/TitleState.hx:329: characters 58-61 : ... For optional function argument 'repeatAxes'
source/TitleState.hx:693: characters 15-23 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/util/FlxDestroyUtil.hx:3: characters 8-32 : You cannot access the flash package while in a macro (for flash.display.BitmapData)
source/animateatlas/AtlasFrameMaker.hx:2: characters 8-34 : ... referenced here
source/Paths.hx:3: characters 8-36 : ... referenced here
C:\Users\Samuel\OneDrive\Tdsa Edition Source Code\source\import.hx:1: characters 8-13 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display3D/_internal/Context3DState.hx:14: characters 8-29 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display3D/Context3D.hx:4: characters 8-49 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/BitmapData.hx:10: characters 8-34 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/_internal/DrawCommandBuffer.hx:3: characters 8-33 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/_internal/CairoGraphics.hx:3: characters 8-50 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/events/RenderEvent.hx:4: characters 8-44 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/DisplayObject.hx:13: characters 8-33 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here

**Comment by Wuznick** [comment]
I tried Lime Test Windows

**Comment by Wuznick** [comment]
help me

**Comment by AnimationZEZ** [comment]
> I tried Lime Test Windows

yeah man i also had this problem too when using fnf source code :(

**Comment by ender69funk** [comment]
> ### Describe your problem here.
> OS Engine Error: source/Discord.hx:4: 8-30 characters: ... referenced here source/Main.hx:20: characters 8-15: ... referenced here I use lime test neko
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> I edited nothing

bro, it's psych engine and yes use flixel 4.11.0

**Comment by Wuznick** [comment]
now there are more errors:
source/editors/ChartingState.hx:1652: characters 27-54 : String should be flash.media.Sound
source/editors/ChartingState.hx:1670: characters 27-56 : String should be flash.media.Sound
source/editors/ChartingState.hx:1133: characters 22-51 : String should be flash.media.Sound
source/editors/ChartingState.hx:1146: characters 24-51 : String should be flash.media.Sound
source/editors/EditorPlayState.hx:89: characters 41-74 : String should be flash.media.Sound
source/editors/EditorPlayState.hx:153: characters 24-55 : String should be flash.media.Sound
source/LoadingState.hx:140: characters 10-41 : String should be flash.media.Sound
source/LoadingState.hx:145: characters 10-43 : String should be flash.media.Sound
source/FreeplayState.hx:673: characters 43-76 : String should be flash.media.Sound
source/FreeplayState.hx:685: characters 26-57 : String should be flash.media.Sound
source/DialogueBox.hx:145: characters 16-22 : flixel.addons.text.FlxTypeText has no field sounds
source/DialogueBox.hx:250: characters 16-25 : flixel.addons.text.FlxTypeText has no field resetText
source/DialogueBox.hx:251: characters 16-21 : flixel.addons.text.FlxTypeText has no field start
source/DialogueBox.hx:252: characters 16-32 : flixel.addons.text.FlxTypeText has no field completeCallback
source/DialogueBox.hx:229: characters 18-22 : flixel.addons.text.FlxTypeText has no field skip
source/PlayState.hx:2085: characters 41-74 : String should be flash.media.Sound
source/PlayState.hx:2090: characters 51-82 : String should be flash.media.Sound
source/PlayState.hx:2047: characters 24-55 : String should be flash.media.Sound

**Comment by Wuznick** [comment]
source/editors/ChartingState.hx:1652: characters 27-54 : String should be flash.media.Sound
source/editors/ChartingState.hx:1670: characters 27-56 : String should be flash.media.Sound
source/editors/ChartingState.hx:1133: characters 22-51 : String should be flash.media.Sound
source/editors/ChartingState.hx:1146: characters 24-51 : String should be flash.media.Sound
source/editors/EditorPlayState.hx:89: characters 41-74 : String should be flash.media.Sound
source/editors/EditorPlayState.hx:153: characters 24-55 : String should be flash.media.Sound
source/LoadingState.hx:140: characters 10-41 : String should be flash.media.Sound
source/LoadingState.hx:145: characters 10-43 : String should be flash.media.Sound
source/FreeplayState.hx:673: characters 43-76 : String should be flash.media.Sound
source/FreeplayState.hx:685: characters 26-57 : String should be flash.media.Sound
source/PlayState.hx:2085: characters 41-74 : String should be flash.media.Sound
source/PlayState.hx:2090: characters 51-82 : String should be flash.media.Sound
source/PlayState.hx:2047: characters 24-55 : String should be flash.media.Sound
source/OstPlayerState.hx:418: characters 44-77 : String should be flash.media.Sound
source/OstPlayerState.hx:430: characters 27-58 : String should be flash.media.Sound

**Comment by Wuznick** [comment]
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/FlxBasic.hx:201: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/graphics/frames/FlxFrame.hx:680: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/graphics/frames/FlxFrame.hx:688: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/tweens/FlxTween.hx:24: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/FlxInput.hx:84: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/tile/FlxBaseTilemap.hx:1382: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/util/FlxDirectionFlags.hx:8: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/util/FlxDirection.hx:7: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/keyboard/FlxKey.hx:8: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/gamepad/FlxGamepadInputID.hx:12: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/mouse/FlxMouseButton.hx:85: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/text/FlxText.hx:1153: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/discord_rpc/git/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel-addons/2,11,0/flixel/addons/transition/FlxTransitionSprite.hx:135: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel-addons/2,11,0/flixel/addons/transition/TransitionData.hx:11: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel-ui/1,0,2/flixel/addons/ui/FlxUI.hx:2427: characters 8-16 : Expected expression

**Comment by Wuznick** [comment]
new error help me!^
                               I

**Comment by ender69funk** [comment]
one minute

**Comment by ender69funk** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions
