### ISSUE TITLE
when is 0.7.0/0.6.3h/0.6.4

### ISSUE THREAD

**Issue by doom699** [ShadowMario/FNF-PsychEngine#12518]
### What is your question?

i mean, it has been like ALMOST 8 months since you made an update, not trying to be rude or disturb you or anything. just asking is there anything more you have to do other than update this engine??

**Comment by CaptainBaldi** [comment]
if you had a braincell you would realize slowly he's been making changes to the experimental branch, if you want new features go fuck with that

**Comment by TheKitBoi** [comment]
> i mean, it has been like ALMOST 8 months since you made an update, not trying to be rude or disturb you or anything. just asking is there anything more you have to do other than update this engine??

impatient D&B Addict
the dev is working hard on some brazil fighting game
also compile shit yourself if you want updates

**Comment by coolaydang** [comment]
yall dont need to be rude all he was just asking
he didnt want to rush or be rude to anyone
he just wanted to know when the psych engine update was coming out
