### ISSUE TITLE
hi man i need help to this problme plis

### ISSUE THREAD

**Issue by AnimationZEZ** [ShadowMario/FNF-PsychEngine#12510]
### What is your question?

![Screenshot (54)](https://github.com/ShadowMario/FNF-PsychEngine/assets/117897380/6eddb297-a9cb-4fb7-b33b-5a5eec87f1a1)
I am very dizzy with this error plis help

**Comment by Stefan2008Git** [comment]
Probably you need to use old version of openfl or something
I don't know

**Comment by AnimationZEZ** [comment]
can you send me the opengl link of the old version ?

**Comment by Stefan2008Git** [comment]
Alright
So, just install a old version:
`haxelib install openfl 9.1.0`

**Comment by doom699** [comment]
put this as a help wanted tag.
