### ISSUE TITLE
No exe

### ISSUE THREAD

**Issue by leaningmonkevr** [ShadowMario/FNF-PsychEngine#12519]
### Describe your problem here.

I compile it but there is no exes

C:\Lean Engine\FNF-LEAN ENGINE\FNF-LeanEngine0.0.1>lime test windows
source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
C:/haxelib/flixel/5,3,1/flixel/animation/FlxAnimation.hx:231: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
C:/haxelib/flixel-addons/3,1,1/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'Object'
source/FunkinLua.hx:2196: lines 2196-2199 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2196: lines 2196-2199 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object'
source/PlayState.hx:584: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:584: characters 25-35 : ... For function argument 'Object'
source/PlayState.hx:2388: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2388: characters 23-29 : ... For function argument 'Object'
source/PlayState.hx:2389: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2389: characters 23-83 : ... For function argument 'Object'
source/PlayState.hx:1781: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1781: characters 25-37 : ... For function argument 'Object'
source/PlayState.hx:1828: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1828: characters 25-34 : ... For function argument 'Object'
source/PlayState.hx:1899: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1899: characters 25-36 : ... For function argument 'Object'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1359: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1359: characters 24-30 : ... For function argument 'Object'
source/editors/ChartingState.hx:2196: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/haxelib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
source/TitleState.hx:708: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:710: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:714: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound

C:\Lean Engine\FNF-LEAN ENGINE\FNF-LeanEngine0.0.1>

this is all 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes Project.xml and Main.hx

**Comment by TheLeerName** [comment]
### [source of message (join psych engine discord server)](https://discord.com/channels/922849922175340586/1108107923391008949/1108107923391008949)

# Deprecation warnings
Original: https://discord.com/channels/922849922175340586/931776548250468382/1104897104079507456
**Note these changes will remove all notices about functions and stuff being removed.**
*  For a permanent fix, Add `<haxedef name='no-deprecation-warnings' />` to your Project.xml above `</project>`.  For a temporary fix, add `-Dno-deprecation-warnings` to the command for compiling the game for a temporary fix
# source/Paths.hx:3: characters 8-36 : ... referenced here
Original: https://discord.com/channels/922849922175340586/931776548250468382/1102511827713265734
* Replace `import Paths;` with `#if(!macro) import Paths; #end` in your Import.hx
# flixel.system.FlxSound errors
Psych uses a custom FlxSound to allow for sound pitching, Flixel has done some updates and broken it, so we have to remove it by doing **all** of the following:
* Remove FlxSound.hx from your source code folder(Usually under source/flixel/system)
* Replace every instance of `import flixel.system.FlxSound;` with `import flixel.sound.FlxSound;`
* In source/editors/ChartingState.hx, add `@:privateAccess {` right above `if (FlxG.save.data.chart_waveformInst) {` around line 2195 add a `}` right after one of the `}` around line 2227
* If you get errors relating to pitch, comment any line that references the `pitch` field of a sound. You can just compile the game to see what (FILE):(LINE) have the issue

# flixel.animation.FlxAnimationController missing numFrames or getFrameDuration
* Open source > flixel > animation > FlxAnimationController.hx
* Delete everything inside of the file
* Replace it with the contents of https://gist.githubusercontent.com/superpowers04/0b01e40e0f272d134f87c5c30712cb66/raw/2366ea0b8d34b08c74119e22f7690d29e63e7f43/FlxAnimationController.hx
