### ISSUE TITLE
Null Object Refrence error

### ISSUE THREAD

**Issue by Godofbacon1** [ShadowMario/FNF-PsychEngine#1251]
### Describe your bug here.

Every time i put custom dialogue character or i put new dialogue in the song and play it it gets me like message it says Null Object Refrences.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No i didn't change anything in the scripts

And here is the evidence for my error

https://user-images.githubusercontent.com/94835099/142845323-cbe062d0-a161-40bb-be5a-7110a2111e43.mp4

**Comment by Godofbacon1** [comment]
And Here is the evidence that i have for this error

**Comment by VicDash78** [comment]
Starting ideas:
Maybe the image is not a png? You also need an xml.
Images are supposed to be located at: your fnf folder/mods/images/dialogue
Name both with the same name.
(Also, you should renember to put the dialogue character json on your fnf folder/mods/images/dialogue if you fix the issue)

**Comment by Godofbacon1** [comment]
1- My image is png
2- My image have a xml
3- They are the same name
4- i will try this
thx for your comment!

**Comment by Godofbacon1** [comment]
OMG ITS ACTULLY WORKING! THANK YOU SO MUCH!

**Comment by ShadowMario** [comment]
Then close your issue omfg
