### ISSUE TITLE
Error Flx.sound Compile OS Engine Fnf

### ISSUE THREAD

**Issue by Wuznick** [ShadowMario/FNF-PsychEngine#12516]
### Describe your problem here.

Error: C:/HaxeToolkit/haxe/lib/discord_rpc/git/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
export/debug/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
export/debug/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
source/PlayState.hx:1762: characters 13-23 : Type not found : MP4Handler
source/editors/ChartingState.hx:2312: characters 38-45 : flixel.sound.FlxSound has no field _buffer
source/editors/ChartingState.hx:2313: characters 29-36 : flixel.sound.FlxSound has no field _buffer
source/editors/ChartingState.hx:2316: characters 19-26 : flash.media.Sound has no field _buffer (Suggestion: __buffer)
source/editors/ChartingState.hx:2329: characters 45-52 : flash.media.Sound has no field _buffer (Suggestion: __buffer)
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
source/TitleState.hx:329: characters 58-61 : Float should be flixel.util.FlxAxes
source/TitleState.hx:329: characters 58-61 : ... For optional function argument 'repeatAxes'
C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/util/FlxDestroyUtil.hx:3: characters 8-32 : You cannot access the flash package while in a macro (for flash.display.BitmapData)
source/animateatlas/AtlasFrameMaker.hx:2: characters 8-34 : ... referenced here
source/Paths.hx:3: characters 8-36 : ... referenced here
C:\Users\Samuel\Downloads\Os Engine Source Code\source\import.hx:1: characters 8-13 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display3D/_internal/Context3DState.hx:14: characters 8-29 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display3D/Context3D.hx:4: characters 8-49 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/BitmapData.hx:10: characters 8-34 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/_internal/DrawCommandBuffer.hx:3: characters 8-33 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/_internal/CairoGraphics.hx:3: characters 8-50 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/events/RenderEvent.hx:4: characters 8-44 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/DisplayObject.hx:13: characters 8-33 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i changed all flx.system.FlxSound from .hx in source to flx.sound.FlxSound

**Comment by Wuznick** [comment]
help me!!!

**Comment by TheKitBoi** [comment]
Don’t make duplicates
Just be patient and wait

**Comment by Wuznick** [comment]
ok
