### ISSUE TITLE
help me is not working :(

### ISSUE THREAD

**Issue by AnimationZEZ** [ShadowMario/FNF-PsychEngine#12521]
### Describe your problem here.

![Screenshot (54)](https://github.com/ShadowMario/FNF-PsychEngine/assets/117897380/af161ef2-ea77-4fa1-9d60-41ca79753898)
how to fix it plis help me to fix this :(

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Makko135** [comment]
What's the problem exactly?

**Comment by TheLeerName** [comment]
remove `import.hx` file
