### ISSUE TITLE
Error in Song

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#12527]
### What is your question?

Well, i uploaded a 30min song to psych but everytime i go to song, timebar says 0:00 left but the song keeps playing and when i go to chart editor, the line thing in chart editor wont move. Is it because of how long the song is?

**Comment by TheKitBoi** [comment]
23 minutes is the limit to on how haxe can handle this

**Comment by NightmaresPlayz** [comment]
So, how will i allow the 30min song

**Comment by TheKitBoi** [comment]
not possible untill otherwise

**Comment by NightmaresPlayz** [comment]
I saw there was a 24min song on psych, if limit is 23 mins, then how did that work?

**Comment by CaptainBaldi** [comment]
limit is about 25 minutes, you can't really fix it too easily, there's a pr around here that supposedly fixes it so ig u can look into that
