### ISSUE TITLE
FlxSound has updated, leaving code with tons of errors

### ISSUE THREAD

**Issue by itsoutchy-projects** [ShadowMario/FNF-PsychEngine#12538]
### Describe your bug here.

There are lots of errors due to FlxSound being updated, the errors are mainly repeated, so the repeated errors are:
flixel.system.FlxSound should be flixel.sound.FlxSound
flixel.sound.FlxSound should be flixel.system.FlxSound
flixel.sound.FlxSound has no field pitch

I am unsure of how you would be able to fix the pitch changes

### Command Prompt/Terminal logs (if existing)

`source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'Object'
source/PlayState.hx:2802: characters 20-25 : flixel.sound.FlxSound has no field pitch
source/PlayState.hx:1441: characters 21-26 : flixel.sound.FlxSound has no field pitch
source/PlayState.hx:2288: characters 20-25 : flixel.sound.FlxSound has no field pitch
source/FunkinLua.hx:2196: lines 2196-2199 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2196: lines 2196-2199 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object'
source/Character.hx:301: characters 101-106 : flixel.sound.FlxSound has no field pitch
source/PlayState.hx:584: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:584: characters 25-35 : ... For function argument 'Object'
source/PlayState.hx:2388: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2388: characters 23-29 : ... For function argument 'Object'
source/PlayState.hx:2389: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2389: characters 23-83 : ... For function argument 'Object'
source/PlayState.hx:1781: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1781: characters 25-37 : ... For function argument 'Object'
source/PlayState.hx:1828: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1828: characters 25-34 : ... For function argument 'Object'
source/PlayState.hx:1899: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1899: characters 25-36 : ... For function argument 'Object'
source/PlayState.hx:2322: characters 20-25 : flixel.sound.FlxSound has no field pitch
source/PlayState.hx:4425: characters 125-130 : flixel.sound.FlxSound has no field pitch
source/PlayState.hx:3117: characters 127-132 : flixel.sound.FlxSound has no field pitch
source/PlayState.hx:4931: characters 20-25 : flixel.sound.FlxSound has no field pitch
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : (WDeprecated) flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1359: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1359: characters 24-30 : ... For function argument 'Object'
source/editors/ChartingState.hx:2196: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/editors/ChartingState.hx:1997: characters 20-25 : flixel.sound.FlxSound has no field pitch
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames 
source/TitleState.hx:711: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:713: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:717: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheLeerName** [comment]
### [source of message (join psych engine discord server)](https://discord.com/channels/922849922175340586/1108107923391008949/1108107923391008949)

# Deprecation warnings
Original: https://discord.com/channels/922849922175340586/931776548250468382/1104897104079507456
**Note these changes will remove all notices about functions and stuff being removed.**
*  For a permanent fix, Add `<haxedef name='no-deprecation-warnings' />` to your Project.xml above `</project>`.  For a temporary fix, add `-Dno-deprecation-warnings` to the command for compiling the game for a temporary fix
# source/Paths.hx:3: characters 8-36 : ... referenced here
Original: https://discord.com/channels/922849922175340586/931776548250468382/1102511827713265734
* Replace `import Paths;` with `#if(!macro) import Paths; #end` in your Import.hx
# flixel.system.FlxSound errors
Psych uses a custom FlxSound to allow for sound pitching, Flixel has done some updates and broken it, so we have to remove it by doing **all** of the following:
* Remove FlxSound.hx from your source code folder(Usually under source/flixel/system)
* Replace every instance of `import flixel.system.FlxSound;` with `import flixel.sound.FlxSound;`
* In source/editors/ChartingState.hx, add `@:privateAccess {` right above `if (FlxG.save.data.chart_waveformInst) {` around line 2195 add a `}` right after one of the `}` around line 2227
* If you get errors relating to pitch, comment any line that references the `pitch` field of a sound. You can just compile the game to see what (FILE):(LINE) have the issue

# flixel.animation.FlxAnimationController missing numFrames or getFrameDuration
* Open source > flixel > animation > FlxAnimationController.hx
* Delete everything inside of the file
* Replace it with the contents of https://gist.githubusercontent.com/superpowers04/0b01e40e0f272d134f87c5c30712cb66/raw/2366ea0b8d34b08c74119e22f7690d29e63e7f43/FlxAnimationController.hx

**Comment by itsoutchy-projects** [comment]
> ### [source of message (join psych engine discord server)](https://discord.com/channels/922849922175340586/1108107923391008949/1108107923391008949)
> # Deprecation warnings
> 
> Original: https://discord.com/channels/922849922175340586/931776548250468382/1104897104079507456 **Note these changes will remove all notices about functions and stuff being removed.**
> 
>     * For a permanent fix, Add `<haxedef name='no-deprecation-warnings' />` to your Project.xml above `</project>`.  For a temporary fix, add `-Dno-deprecation-warnings` to the command for compiling the game for a temporary fix
> 
> 
> # source/Paths.hx:3: characters 8-36 : ... referenced here
> 
> Original: https://discord.com/channels/922849922175340586/931776548250468382/1102511827713265734
> 
>     * Replace `import Paths;` with `#if(!macro) import Paths; #end` in your Import.hx
> 
> 
> # flixel.system.FlxSound errors
> 
> Psych uses a custom FlxSound to allow for sound pitching, Flixel has done some updates and broken it, so we have to remove it by doing **all** of the following:
> 
>     * Remove FlxSound.hx from your source code folder(Usually under source/flixel/system)
> 
>     * Replace every instance of `import flixel.system.FlxSound;` with `import flixel.sound.FlxSound;`
> 
>     * In source/editors/ChartingState.hx, add `@:privateAccess {` right above `if (FlxG.save.data.chart_waveformInst) {` around line 2195 add a `}` right after one of the `}` around line 2227
> 
>     * If you get errors relating to pitch, comment any line that references the `pitch` field of a sound. You can just compile the game to see what (FILE):(LINE) have the issue
> 
> 
> # flixel.animation.FlxAnimationController missing numFrames or getFrameDuration
> 
>     * Open source > flixel > animation > FlxAnimationController.hx
> 
>     * Delete everything inside of the file
> 
>     * Replace it with the contents of https://gist.githubusercontent.com/superpowers04/0b01e40e0f272d134f87c5c30712cb66/raw/2366ea0b8d34b08c74119e22f7690d29e63e7f43/FlxAnimationController.hx

Sorry for the late response.
Thank you so much for your detailed response, it has fixed the errors listed, though now characters never return to their idle animation.

I did try this in PlayState.hx at line: 3136:
```haxe
else if(boyfriend.animation.curAnim != null && boyfriend.holdTimer > Conductor.stepCrochet * (0.0011 / 1) * boyfriend.singDuration && boyfriend.animation.curAnim.name.startsWith('sing') && !boyfriend.animation.curAnim.name.endsWith('miss')) {
					boyfriend.dance();
					//boyfriend.animation.curAnim.finish();
				}
``` 
But that never fixed the issue.

**Comment by WallDotHX** [comment]
What would happen if you uncomment the boyfriend.animation.curAnim.finish();
