### ISSUE TITLE
Getting High score using lua

### ISSUE THREAD

**Issue by KillerAvecRage** [ShadowMario/FNF-PsychEngine#12537]
### Describe your problem here.

Hello,

I am trying to make a hud that would look like Gran Turismo's license tests, I am near finishing it but I just need one thing: getting **high score** (**not maximum score**) from lua, is there any possible way to do this?

Thank you in advance.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I am using my version of Psych Engine that I translated in French

**Comment by TheLeerName** [comment]
kid named
```lua
addHaxeLibrary("Highscore")
debugPrint('high score of song: '..runHaxeCode("return Highscore.getScore(PlayState.SONG.song, PlayState.storyDifficulty);"))
```

**Comment by KillerAvecRage** [comment]
It works fine, thanks a lot!
