### ISSUE TITLE
Reorder Boyfriend on stage?

### ISSUE THREAD

**Issue by Kirsenal** [ShadowMario/FNF-PsychEngine#12539]
### Describe your problem here.

Changing the opponent's order is used with "dadGroup", changing gf's is with "gfGroup" but I am unsure what it is for bf. I tried "bfGroup" but that doesn't work. I tried a number of other things but nothing seems to work. What do I put there?

setObjectOrder('bfGroup', 33)

Instead of bfGroup what do I input?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
`boyfriendGroup`
You should look at PlayState.hx for variables
