### ISSUE TITLE
compilation not working (unknown identifier : add)

### ISSUE THREAD

**Issue by Noel3454565FNF** [ShadowMario/FNF-PsychEngine#12535]
### Describe your problem here.

im trying to compil Psych engine but have some issue

![C__WINDOWS_system32_cmd exe 07_06_2023 16_47_17](https://github.com/ShadowMario/FNF-PsychEngine/assets/58745415/813861aa-bc27-4af0-96af-1d26509f707c)

can someone help me please?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, Achievements.hx and FunkinLua.hx

**Comment by MemeHovy** [comment]
> ### Describe your problem here.
> im trying to compil Psych engine but have some issue
> 
> ![C__WINDOWS_system32_cmd exe 07_06_2023 16_47_17](https://user-images.githubusercontent.com/58745415/244105579-813861aa-bc27-4af0-96af-1d26509f707c.png)
> 
> can someone help me please?
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> yes, Achievements.hx and FunkinLua.hx

those classes do not extend flxstate, thus don’t have add

**Comment by Noel3454565FNF** [comment]
can you explain please?
and what i can do to fix this?

**Comment by MemeHovy** [comment]
use flxg.state.add

**Comment by Noel3454565FNF** [comment]
> use FlxG.state.add

but how can i use it on a script?

**Comment by Noel3454565FNF** [comment]
like i replace add by FlxG.state.add?

**Comment by MemeHovy** [comment]
> like i replace add by FlxG.state.add?

well, it fixes the compile issue

**Comment by Noel3454565FNF** [comment]
okay thanks :>

**Comment by MemeHovy** [comment]
np
