### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by theboinga** [ShadowMario/FNF-PsychEngine#12531]
### Describe your problem here.

so like
i'm just recharting something right
and i try to play the chart
and.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/135666878/bcbb6dfa-11c6-4c0f-a344-267d0c771b29)
i have no idea what could've caused this, i don't remember editing something for it to do this
and it isn't just this song, every time i try to use the opponent character anywhere it says the same thing
i checked the files and nothing appears to be wrong
i have quite literally no knowledge of psych so any help would be appreciated

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I don't remember editing anything, it just started doing this

### wait a minute

i'm an idiot, i remembered wrong and found out that dadbattle spotlights, philly lights and henchmen deaths are **hardcoded** to their songs. they literally *can't* be used anywhere else. it infact wasn't the character but it was the events

i need to ask my animator how he got db spotlights to work in other songs

**Comment by frantastic24** [comment]
Close the issue
You can find a Lua recreation somewhere

**Comment by szb512** [comment]
same issue, except I went to load an autosave when it crashed.

**Comment by frantastic24** [comment]
It is not the same issue
At all

**Comment by PogofruitKM** [comment]
> > It is not the same issue At all
> 
> same problem, Null Object Reference, just a different scenario.
> 
> anyways, happened again when reloading a character (in particular the image of said character) ![instance#2](https://user-images.githubusercontent.com/47613831/244461153-3d47862c-49bf-4259-a5df-2ea0d435c15f.PNG)

Your character image/character health icon image doesn't exist

**Comment by szb512** [comment]
I know that part, I was just tweaking a few things before reloading the image to see if it fixed it before the engine threw the error at me. Also, the past few times I reloaded, the engine never threw "Null Object Reference" despite the icons still not existing

**Comment by szb512** [comment]
The engine never gave me the null object reference error despite reloading the image after tweaking something though, until this instance as shown in the picture above

**Comment by AnuAnu22** [comment]
Whats the fix? Why it closed?
