### ISSUE TITLE
question about runHaxeCode Lua function

### ISSUE THREAD

**Issue by Noel3454565FNF** [ShadowMario/FNF-PsychEngine#12536]
### What is your question?

im trying to execute a haxe code in my lua script and its not working well

this working
<img width="465" alt="image" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/58745415/734486a8-010f-4ed7-a0e0-e54a2217212c">

but why this one not working?
<img width="427" alt="Capture d'écran 2023-06-07 195637" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/58745415/4e66cfe1-e9f6-4000-883c-4b5ca5064a04">

i know its working on the source but why its not working in my script ;-;

**Comment by TheLeerName** [comment]
1. do `luaDebugMode = true` and it will be show mostly errors
2. u didnt added LoadingState, do `addHaxeLibrary("LoadingState")`
3. u didnt added Song, do `addHaxeLibrary("Song")`

**Comment by Noel3454565FNF** [comment]
i fixed it thanks :> (i just put the wrong sprite name)

**Comment by Noel3454565FNF** [comment]
> 1. do `luaDebugMode = true` and it will be show mostly errors
> 2. u didnt added LoadingState, do `addHaxeLibrary("LoadingState")`
> 3. u didnt added Song, do `addHaxeLibrary("Song")`

thanks im gonna try :>

**Comment by Noel3454565FNF** [comment]
THANKS ITS WORK NOW :D

**Comment by Noel3454565FNF** [comment]
so for make it work make sure you have in your lua script:

addHaxeLibrary("LoadingState")
addHaxeLibrary("Song")
