### ISSUE TITLE
dumb dumb crash multiple

### ISSUE THREAD

**Issue by MaIfunctional** [ShadowMario/FNF-PsychEngine#12549]
### Describe your bug here.

ive been tryna make a playable version of a doomsday mix i made, so i just edited the doomsday data file and added a few events being the one that makes characters black and the background white, similar to bad apple, and change character.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/99407501/377305e0-f092-4606-b170-9a69fe5f2278)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheLeerName** [comment]
u fucked up with events, cuz 2614 line is `eventNoteEarlyTrigger()` function
