### ISSUE TITLE
how do I make these menus and add a secret freeplay section when you press 7 on the keyboard in the menu in the fourth image?

### ISSUE THREAD

**Issue by matthewfro1717** [ShadowMario/FNF-PsychEngine#12545]
### Describe your problem here.

how do I make these menus and add a secret freeplay section when you press 7 on the keyboard in the menu in the fourth image?

![Screenshot 2023-06-08 9 22 39 AM](https://github.com/ShadowMario/FNF-PsychEngine/assets/114807610/f69693fc-00c2-4f2b-8744-99e187d68bba)
![Screenshot 2023-06-08 9 22 45 AM](https://github.com/ShadowMario/FNF-PsychEngine/assets/114807610/301a8957-4d29-42c7-9084-dd46e6ca716e)
![Screenshot 2023-06-08 9 22 51 AM](https://github.com/ShadowMario/FNF-PsychEngine/assets/114807610/b26f2431-68d8-436a-bcc4-262bbd87b94d)
![Screenshot 2023-06-08 9 23 02 AM](https://github.com/ShadowMario/FNF-PsychEngine/assets/114807610/dca5161e-8bcf-4f20-90da-cd7be262cb28)
![Screenshot 2023-06-08 9 25 32 AM](https://github.com/ShadowMario/FNF-PsychEngine/assets/114807610/0ea339ac-54f0-49eb-99b2-9dfd9ece2f64)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
average d&b fan

**Comment by raxyd** [comment]
> ```hx
> override function update(elapsed:Float) {
>     super.update(elapsed);
>     if (FlxG.keys.justPressed.SEVEN)
>         MusicBeatState.switchState(new StoryMenuState()); // an example
> }
> ```

where do I put it
