### ISSUE TITLE
ALT-Animations don't work

### ISSUE THREAD

**Issue by KingRGames** [ShadowMario/FNF-PsychEngine#12547]
### Describe your bug here.

All the ALT-Animations will not work for me! I did add winning icons to psych what do i do and is this a bug?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added winning icons!

**Comment by ender69funk** [comment]
idle-ALT
singLEFT-ALT
singDOWN-ALT
singUP-ALT
singRIGHT-ALT
