### ISSUE TITLE
bg.color = FlxColor.fromRGB(loadedWeeks[curWeek].FBGcolor[0], loadedWeeks[curWeek].FBGcolor[1], loadedWeeks[curWeek].FBGcolor[2]); keeps on crashing

### ISSUE THREAD

**Issue by DafaTG** [ShadowMario/FNF-PsychEngine#12540]
### Describe your problem here.

I made a bg:FlxSprite in the StoryMenuState, and tried to make it change color according to a week's FBGcolor variable, but it keeps on crashing.
This is pretty much everything that I added/changed [besides the WeekEditorState], and hopefully everything that you need to know 
![SMScodeproblem1](https://github.com/ShadowMario/FNF-PsychEngine/assets/132962034/a7ff0aa9-cb20-45f3-b82f-54c614c005ba)
![SMScodeproblem3](https://github.com/ShadowMario/FNF-PsychEngine/assets/132962034/a2223fdb-36d2-4152-91ea-5b74b0f3addf)
![SMScodeproblem2](https://github.com/ShadowMario/FNF-PsychEngine/assets/132962034/f1f76573-5992-4c02-bdb7-0feaa1067dd9)
![SMScodeproblem4](https://github.com/ShadowMario/FNF-PsychEngine/assets/132962034/d27c5d13-53c2-44a0-8de2-7dcf588ca27f)
![SMScodeproblem5](https://github.com/ShadowMario/FNF-PsychEngine/assets/132962034/e9608f76-0427-45f4-bc53-4ed576539235)
![SMScodeproblem6](https://github.com/ShadowMario/FNF-PsychEngine/assets/132962034/18129a7e-4602-4bb3-8705-740e3dbf4277)
last image is a week json

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Check the funny haha images

**Comment by TheLeerName** [comment]
cuz `loadedWeeks` is empty right where u added these lines, its not empty after `for` loop below

**Comment by DafaTG** [comment]
oh, hey! it works!! Thank you so much!!! Ig I wasn't looking around enough :b
