### ISSUE TITLE
Lua bug

### ISSUE THREAD

**Issue by ender69funk** [ShadowMario/FNF-PsychEngine#12546]
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/112335251/a04d3451-6a20-4018-a8fd-eb292e6526ea)
Using lua in a source code or event, the black color of some fucking will turn into white 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by CaptainBaldi** [comment]
what

**Comment by TheLeerName** [comment]
`haxelib install hxcpp 4.2.1`

**Comment by ender69funk** [comment]
> `haxelib install hxcpp 4.2.1`

thanks

**Comment by ender69funk** [comment]
> what

no one cares
