### ISSUE TITLE
got a crash

### ISSUE THREAD

**Issue by Noel3454565FNF** [ShadowMario/FNF-PsychEngine#12548]
### Describe your bug here.

got this crash
<img width="444" alt="image" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/58745415/e0b05393-9a8a-47ce-95a7-edc4cc4fa9bf">

i added that:
		bg = new FlxSprite().loadGraphic(Paths.image('menuDesat'));
		bg.antialiasing = ClientPrefs.globalAntialiasing;
		FlxG.state.add(bg);
		bg.screenCenter();
		//trace('Playback Rate: ' + playbackRate);
		Paths.clearStoredMemory();

### Command Prompt/Terminal logs (if existing)

```bash
nop
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Playstate.hx

**Comment by TheLeerName** [comment]
where u added it

**Comment by Noel3454565FNF** [comment]
it was in Playstate,
i fixed it sorry (the sprite name wasn't good)

**Comment by Noel3454565FNF** [comment]
just another question

**Comment by Noel3454565FNF** [comment]
how can i add a sprite and show it in the source ._. i don't understand and can't find it on the doc ;-;

**Comment by TheLeerName** [comment]
> it was in Playstate, i fixed it sorry (the sprite name wasn't good)

i mean which line

**Comment by Noel3454565FNF** [comment]
start at 339 and end at 344

**Comment by Noel3454565FNF** [comment]
i didn't know thanks ^^

**Comment by Noel3454565FNF** [comment]
THANKS its working now :>

**Comment by Noel3454565FNF** [comment]
omg im so dumb sometimes ;-;

**Comment by Noel3454565FNF** [comment]
the game not returning error but not working in the source.
i tried in runHaxecode and its working so idk ._.

**Comment by TheLeerName** [comment]
cuz lua scripts runs after [1224 line](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/PlayState.hx#L1224)

**Comment by Noel3454565FNF** [comment]
oh
