### ISSUE TITLE
I saw Flixel Got Problem for my compile

### ISSUE THREAD

**Issue by realMohammadDev** [ShadowMario/FNF-PsychEngine#12542]
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/103966427/bd7c17cd-5b34-4cb7-be35-ce2bea01c58b)

### Command Prompt/Terminal logs (if existing)

```bat
lime test windows -debug
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Flixel Got Problem to Compile

**Comment by TheLeerName** [comment]
idk do
```
haxelib remove flixel
haxelib install flixel
```

**Comment by itsoutchy-projects** [comment]
Idk what you should do since I don't know if you've edited anything.

> # Did you edit anything in this build? If so, mention or summarize your changes.
> Flixel got problem to compile
You need to say what you've edited here if you've edited anything.
