### ISSUE TITLE
how can i make an event when gf is pressed by the mouse?

### ISSUE THREAD

**Issue by Noel3454565FNF** [ShadowMario/FNF-PsychEngine#12550]
### Describe your problem here.

so, im trying to make a way to detect when the mouse is pressed when its over gf in haxe thanks :>

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, Playstate, FunkinLua, MainMenue, Achievements

**Comment by TheLeerName** [comment]
```hx
if (FlxG.mouse.justPressed && game.gf.pixelsOverlapPoint(FlxG.mouse.getPosition(), 0x01))
    trace('click!');
```

**Comment by Noel3454565FNF** [comment]
> ```hx
> if (FlxG.mouse.justPressed && game.gf.pixelsOverlapPoint(FlxG.mouse.getPosition(), 0x01))
>     trace('click!');
> ```

my game just freeze ._.

**Comment by Noel3454565FNF** [comment]
nvm its working thanks :>
