### ISSUE TITLE
cannot access camAchievement in static function

### ISSUE THREAD

**Issue by Noel3454565FNF** [ShadowMario/FNF-PsychEngine#12556]
### Describe your bug here.

im trying to make a function on PlayState but got a issue with the camAchivement and idk how to solve it ._.
<img width="867" alt="image" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/58745415/b04950cf-4b8e-43f0-9594-6bfe881b18b6">

if someone got a way this can help thanks :>

### Command Prompt/Terminal logs (if existing)

```bash
BUILDING GAME
source/PlayState.hx:1416: characters 62-76 : Cannot access camAchievement in static function
source/PlayState.hx:1416: characters 62-76 : ... For optional function argument 'camera'
source/PlayState.hx:1416: characters 62-76 : ... For function argument 'Object'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, Playstate, FunkinLua, MainMenue, Achievements

**Comment by Noel3454565FNF** [comment]
> `camAchievement` is not static

that's make sense but there is a way to use it or a other way?

**Comment by TheLeerName** [comment]
no why

**Comment by Noel3454565FNF** [comment]
> no why

just asking, thanks :>
