### ISSUE TITLE
Menu Shaders

### ISSUE THREAD

**Issue by Crimson-maker** [ShadowMario/FNF-PsychEngine#12554]
### What is your question?

Hi, I'm trying to figure out how to add shaders to the menus of the game. It will really help if anybody could help me out.

**Comment by TheLeerName** [comment]
```hx
import flixel.FlxG;
import flixel.FlxBasic;
import flixel.addons.display.FlxRuntimeShader;

class Shader extends FlxBasic {
    public var shader(default, null):FlxRuntimeShader = new FlxRuntimeShader('
        // .frag content
    ');
    public function new() {
        super();
        FlxG.state.add(this);
        shader.setFloat('iTime', 0);
    }
    override public function update(elapsed:Float) {
        super.update(elapsed);
        shader.setFloat('iTime', shader.getFloat('iTime') + elapsed);
    }
}
```
and use it like this:
```hx
var theshader = new Shader();
dad.shader = theshader.shader;
```

**Comment by Crimson-maker** [comment]
do i make a new script in source and add the code?

**Comment by TheLeerName** [comment]
> do i make a new script in source and add the code?

create file source/Shader.hx and put class and imports in it

**Comment by Crimson-maker** [comment]
How about the 

var theshader = new Shader();
dad.shader = theshader.shader;

**Comment by TheLeerName** [comment]
> 

where u want

**Comment by TheLeerName** [comment]
> How about the
> 
> var theshader = new Shader(); dad.shader = theshader.shader;

where u want
