### ISSUE TITLE
hev bf skin isn't working

### ISSUE THREAD

**Issue by Bentheboy** [ShadowMario/FNF-PsychEngine#12557]
### Describe your problem here.

i am trying to use the hev bf skin but everytime i do the game crashes.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Bentheboy** [comment]
this is the error 
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/123776002/7ddb5b52-083e-403a-b2e7-15e148a2e433)

**Comment by frantastic24** [comment]
Missing character texture files

**Comment by Bentheboy** [comment]
what does that mean.

**Comment by Bentheboy** [comment]
?

**Comment by Bentheboy** [comment]
never mind figured it out without your help.
