### ISSUE TITLE
Pysch engine literally crashes on long songs with events

### ISSUE THREAD

**Issue by VicDash78** [ShadowMario/FNF-PsychEngine#1256]
### Describe your bug here.

Yep. literally just created an account to point this out

Basically, 5 minute song crashes at about 2 mins of playing. After a lot of looking what the fuck was wrong i found out the event was making this issue (without the events the song works just fine), looking around on chart editor doesnt crash the game.

Are my events badly formatted or is this an actual issue? seems like someone got this too https://github.com/ShadowMario/FNF-PsychEngine/issues/872

Just in case, [here are the events.](https://github.com/ShadowMario/FNF-PsychEngine/files/7580967/events.zip)

### _**Extra notes:**_
It happens with an empty chart too.
Might be something related to removing base game weeks? (game files)
For some reason obs actually made me crash LATER on the level. maybe its something related to framerate? **_it is. crashes later on lower framerates._**

https://user-images.githubusercontent.com/94842270/142865383-73e0036e-1209-4958-90ad-2abd6b50bb9d.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i suck at haxeflixel.
Edit: As for lua, i made a few custom events on mods/custom_events.

**Comment by ShadowMario** [comment]
Looks like that issue from Psych 0.4.1, your version might be outdated.

**Comment by VicDash78** [comment]
Holy shit i think im blind lmao
![image](https://user-images.githubusercontent.com/94842270/142940123-58063c81-49dd-48cb-9f5a-d271a5af636d.png)

**Comment by VicDash78** [comment]
Let me test it rq

**Comment by VicDash78** [comment]
oops

**Comment by VicDash78** [comment]
Ok cool it works, thanks

**Comment by AzardeauxHTF** [comment]
hi ShadowMario i have a probleme. When i generating a sprites sheet, and i export it on mods-image-character and i open  the sprites its say "it seems that we do not support this file format". Can you help me please :(

**Comment by HarithHkm08** [comment]
> hi ShadowMario i have a probleme. When i generating a sprites sheet, and i export it on mods-image-character and i open  the sprites its say "it seems that we do not support this file format". Can you help me please :(
So, yeah. Is the sprite sheet json is a JSON file? If it says File file, blame the source. Fix? Rename your json file with .json at the end.

**Comment by Noel3454565FNF** [comment]
the problem is the same with the new version (6.3) but work with old (5.2)
