### ISSUE TITLE
Event that will change character X and Y values

### ISSUE THREAD

**Issue by SrBagel** [ShadowMario/FNF-PsychEngine#12563]
### Describe your problem here.

I'm trying to make an event that will change characters X and Y values for source but I'm stupid

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by TheLeerName** [comment]
bro u literally can copypaste it from FunkinLua
```hx
function setCharacterX(type:String, value:Float) {
	switch(type.toLowerCase()) {
		case 'dad' | 'opponent':
			PlayState.instance.dadGroup.x = value;
		case 'gf' | 'girlfriend':
			PlayState.instance.gfGroup.x = value;
		default:
			PlayState.instance.boyfriendGroup.x = value;
	}
}
function setCharacterY(type:String, value:Float) {
	switch(type.toLowerCase()) {
		case 'dad' | 'opponent':
			PlayState.instance.dadGroup.y = value;
		case 'gf' | 'girlfriend':
			PlayState.instance.gfGroup.y = value;
		default:
			PlayState.instance.boyfriendGroup.y = value;
	}
}
```

**Comment by SrBagel** [comment]
> 

Like I said I'm stupid thanks by the way

**Comment by SrBagel** [comment]
Update I don't know what to do with this

**Comment by SrBagel** [comment]
> bro u literally can copypaste it from FunkinLua
> 
> ```hx
> function setCharacterX(type:String, value:Float) {
> 	switch(type.toLowerCase()) {
> 		case 'dad' | 'opponent':
> 			PlayState.instance.dadGroup.x = value;
> 		case 'gf' | 'girlfriend':
> 			PlayState.instance.gfGroup.x = value;
> 		default:
> 			PlayState.instance.boyfriendGroup.x = value;
> 	}
> }
> function setCharacterY(type:String, value:Float) {
> 	switch(type.toLowerCase()) {
> 		case 'dad' | 'opponent':
> 			PlayState.instance.dadGroup.y = value;
> 		case 'gf' | 'girlfriend':
> 			PlayState.instance.gfGroup.y = value;
> 		default:
> 			PlayState.instance.boyfriendGroup.y = value;
> 	}
> }
> ```

What do I do with this?

**Comment by TheLeerName** [comment]
use it

**Comment by SrBagel** [comment]
> use it

Guess I phrased it wrong where do I put this and how do I make it into an event
