### ISSUE TITLE
I want play a song but this appear me

### ISSUE THREAD

**Issue by Chipitor** [ShadowMario/FNF-PsychEngine#12568]
### What is your question?

Paths.hx (line 364)
Character.hx (line 164)
PlayState.hx (line 571)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

**Comment by TheLeerName** [comment]
broken png?
