### ISSUE TITLE
compiling problem help plz

### ISSUE THREAD

**Issue by coolaydang** [ShadowMario/FNF-PsychEngine#12560]
### Describe your problem here.

I JUST WANTED TO COMPILE PSYCH ENGINE😭😭😭😭😭
and yes i tried to troubleshoot this my self by replacing the flixel.system.Flxsound with flixel.sound.Flxsound 
but one of the things needed to run psych engine isnt included in that

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/89037815/ed9beb33-0ddd-4def-99eb-a0170262871b)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ender69funk** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions - read this

**Comment by johhnyfnfb3** [comment]
replace "Main.hx" with this new version: https://raw.githubusercontent.com/ShadowMario/FNF-PsychEngine/main/source/Main.hx

the devs forgot to change it for some reason :/

**Comment by TheLeerName** [comment]
### [source of message (join psych engine discord server)](https://discord.com/channels/922849922175340586/1108107923391008949/1108107923391008949)

# Deprecation warnings
Original: https://discord.com/channels/922849922175340586/931776548250468382/1104897104079507456
**Note these changes will remove all notices about functions and stuff being removed.**
*  For a permanent fix, Add `<haxedef name='no-deprecation-warnings' />` to your Project.xml above `</project>`.  For a temporary fix, add `-Dno-deprecation-warnings` to the command for compiling the game for a temporary fix
# source/Paths.hx:3: characters 8-36 : ... referenced here
Original: https://discord.com/channels/922849922175340586/931776548250468382/1102511827713265734
* Replace `import Paths;` with `#if(!macro) import Paths; #end` in your Import.hx
# flixel.system.FlxSound errors
Psych uses a custom FlxSound to allow for sound pitching, Flixel has done some updates and broken it, so we have to remove it by doing **all** of the following:
* Remove FlxSound.hx from your source code folder(Usually under source/flixel/system)
* Replace every instance of `import flixel.system.FlxSound;` with `import flixel.sound.FlxSound;`
* In source/editors/ChartingState.hx, add `@:privateAccess {` right above `if (FlxG.save.data.chart_waveformInst) {` around line 2195 add a `}` right after one of the `}` around line 2227
* If you get errors relating to pitch, comment any line that references the `pitch` field of a sound. You can just compile the game to see what (FILE):(LINE) have the issue

# flixel.animation.FlxAnimationController missing numFrames or getFrameDuration
* Open source > flixel > animation > FlxAnimationController.hx
* Delete everything inside of the file
* Replace it with the contents of https://gist.githubusercontent.com/superpowers04/0b01e40e0f272d134f87c5c30712cb66/raw/2366ea0b8d34b08c74119e22f7690d29e63e7f43/FlxAnimationController.hx
