### ISSUE TITLE
weird Psych engine building error

### ISSUE THREAD

**Issue by sa3gaming** [ShadowMario/FNF-PsychEngine#12566]
### Describe your problem here.

I think this is the last error i have to face before i can build psych engine please help me

.haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
Error: Could not find include file "C:/haxelib/hxCodec/2,6,1/vlc/lib/LibVLCBuild.xml"

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by davidfnf** [comment]
help where do i put  building error at
