### ISSUE TITLE
Chart Import Error

### ISSUE THREAD

**Issue by sarinbecken** [ShadowMario/FNF-PsychEngine#12569]
### Describe your bug here.

I was importing a chart and this popped up everytime i tried to play it.

sample chart that i think has the problem: 
[beach-brawl-hard.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/11730851/beach-brawl-hard.txt)

### Command Prompt/Terminal logs (if existing)

```bash
Song.hx (line 66)
Song.hx (line 134)
FreeplayState.hx (line 371)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by sarinbecken** [comment]
bonus: every time i delete the @ things the chart doesnt load (and neither do the vocals)

**Comment by TheLeerName** [comment]
wtf where u found this corrupted as fuck chart
