### ISSUE TITLE
Custom Note Problem

### ISSUE THREAD

**Issue by Madeeepie34** [ShadowMario/FNF-PsychEngine#12579]
### Describe your problem here.

So whenever I put my custom note skin in mods/images, It wont work and it gives me this error. Mind helping me out. Plus I didnt really code this in so

![Screenshot 2023-06-14 224231](https://github.com/ShadowMario/FNF-PsychEngine/assets/136666012/40cb2505-f226-45a7-ae42-c0ceb6b546fd)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Madeeepie34** [comment]
![Madee_NOTE_assets](https://github.com/ShadowMario/FNF-PsychEngine/assets/136666012/a84c8412-4678-49cd-b0eb-426ea6c91cd1)

this is the spritesheet btw

**Comment by frantastic24** [comment]
#9296

**Comment by NotStampyC** [comment]
thats not the noteskin assets thats just normal note assets
and idk brobably missing xml or something

**Comment by TheLeerName** [comment]
yes u definitely have corrupted xml
