### ISSUE TITLE
loadSong and setRatingName doesnt work in anymore

### ISSUE THREAD

**Issue by iwanttokommitdead** [ShadowMario/FNF-PsychEngine#12571]
### Describe your bug here.

loadSong() doesnt work anymore, and neither does setRatingName() doesnt work anymore in the recent version (0.6.3), havent yet seen if it works on 0.6.x but i think it doesnt. it works on 0.5.x though

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i didnt use source code

**Comment by itsoutchy-projects** [comment]
You probably just need to try to keep up to date with the new versions of Psych Engine, if that doesn't help then idk.

**Comment by TheLeerName** [comment]
uh i think just send script u used?

**Comment by iwanttokommitdead** [comment]
okay turns out loadSong works, but i dont think setRatingName is, had to use another script instead of the simpler one that existed back then
