### ISSUE TITLE
How to removeluascript mid-song (LUA)

### ISSUE THREAD

**Issue by YoshiGames64** [ShadowMario/FNF-PsychEngine#12573]
### Describe your problem here.

feel like removeLuaScript does nothing
I was making a high effort Impostor V5 with Defeated V4 Transition and put in

```
function onStepHit()
    if curStep == 1168 then
        addLuaScript('data/defeated/pe');
        removeLuaScript('data/defeated/ke');
        close(true);
   end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheLeerName** [comment]
bro like u adding script and removing it in one frame 💀

**Comment by YoshiGames64** [comment]
💀

**Comment by YoshiGames64** [comment]
k nvm i fig
