### ISSUE TITLE
How can I optimize this script?

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#12578]
### What is your question?

What I've did was change the score text (in Lua)
But I've also implemented the accuracy changing to `?` before any notes are hit
But now every time I hit a note, the fps goes down by almost 20
![Screenshot_20230614-191658-899](https://github.com/ShadowMario/FNF-PsychEngine/assets/101405920/950da1ab-edbf-4e53-a386-0e696fbd7d92)

**Comment by TheLeerName** [comment]
how it can do lag 💀
like math.floor is too cost operation to ur device???

**Comment by ZeitHeld** [comment]
I personally used one inside of onUpdate() since it also counts misses and stuff. and that way
maybe it then is a bit more stable, since it checks a bit more often, and might be a less chunky

**Comment by BernardoGP4504** [comment]
> I personally used one inside of onUpdate() since it also counts misses and stuff. and that way maybe it then is a bit more stable, since it checks a bit more often, and might be a less chunky

But update runs every frame and I'm afraid it will affect loading times or something.
Also the fps going down when a note is hit is normal. It's that my script adds a -8 fps loss

**Comment by ZeitHeld** [comment]
just try it out. you can still revert it later on

**Comment by BernardoGP4504** [comment]
> just try it out. you can still revert it later on

It just made it worse also while having trouble on setting the text whenever a note was hit
