### ISSUE TITLE
Null Object Reference when trying to access Freeplay

### ISSUE THREAD

**Issue by ninjakaiden2522** [ShadowMario/FNF-PsychEngine#12589]
### Describe your bug here.

After I made a Spritesheet for my FNF mod and going to freeplay, I get this "Null Object Reference" error. I don't know why it happened but it just did, here is the error:
FreeplayState.hx (line 74)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by TheLeerName** [comment]
corrupted week file??
crash handler says `var leWeek:WeekData` is null
