### ISSUE TITLE
Time bar

### ISSUE THREAD

**Issue by JaxTheChameleon** [ShadowMario/FNF-PsychEngine#12581]
### What is your question?

Hi, so I wanted to ask you guys about time bar, or if being more specific how to make time bar revert time like in Wednesday infidelity?

**Comment by JVgradiz** [comment]
in lua or sourse?

**Comment by TheLeerName** [comment]
im lazy to check how it looks in this mod but i did this
```lua
function onStepHit()
	if curStep == 48 then
		switchReversed(true)
	end
	if curStep == 96 then
		switchReversed(false) -- returns time bar to normal
	end
end

function switchReversed(value)
	fakeOffset = -1000
	reversedTimeTxt = value
	setProperty('updateTime', not value)
end
function onUpdatePost(elapsed)
	if reversedTimeTxt then
		fakeOffset = fakeOffset - (elapsed * 2000)
		if getPropertyFromClass('ClientPrefs', 'timeBarType') ~= 'Disabled' then
			local time = getPropertyFromClass('Conductor', 'songPosition') - getPropertyFromClass('ClientPrefs', 'noteOffset')
			time = math.max(time + fakeOffset, 0)
			setProperty('songPercent', time / songLength)
			if getPropertyFromClass('ClientPrefs', 'timeBarType') == 'Time Left' then
				time = songLength - time
			end
			time = time / 1000
			local minutes = math.floor(time / 60)..''
			local seconds = math.floor(time % 60)..''
			if #seconds == 1 then seconds = '0'..seconds end
			if getPropertyFromClass('ClientPrefs', 'timeBarType') ~= 'Song Name' then
				setProperty('timeTxt.text', minutes..":"..seconds)
			end
		end
	end
end
```

**Comment by JVgradiz** [comment]
Not saying that TheLeerName's code is bad but here is a smaller version of the code
`local timeBarMaxSeconds = 10; -- Change to how much is the timebar's max value

timeBarMaxSeconds = timeBarMaxSeconds*1000;

function onCreate()
	makeLuaSprite('timeBarTime', '',timeBarMaxSeconds,0);
end
function onUpdatePost(elapsed)
	local time = (getSongPosition() - noteOffset)/1000;
	local alltime = getProperty('timeBarTime.x')/1000;
	setProperty('songPercent', time/alltime)

	local second = math.floor((alltime - time)%60)
	local minute = math.floor((alltime - time)/60)

	if timeBarType == 'Time Left' then
		if second < 10 then
			setProperty('timeTxt.text', minute .. ':0' .. second )
		else
			setProperty('timeTxt.text', minute .. ':' .. second )
		end
	end

	if curBeat == 24 then
		doTweenX('timebarTween','timeBarTime', songLength, 10, 'linear') -- Change the max to maxSongLength
	end
end`

**Comment by TheLeerName** [comment]
*smaller not equals better*

no pressure :)

**Comment by JVgradiz** [comment]
> _smaller not equals better_
> 
> no pressure :)

I agree with that, im just giving another possibility of code if he wants

**Comment by JaxTheChameleon** [comment]
OMG.
Guys, sorry for not responding, but I owe ya a huge thanks!
You really helped me out, thank you, both of you. It's all working as it should be
