### ISSUE TITLE
Make game crash at a specific time during Game Over in LUA

### ISSUE THREAD

**Issue by ghost** [ShadowMario/FNF-PsychEngine#12583]
### What is your question?

![Screenshot 2023-06-16 200214](https://github.com/ShadowMario/FNF-PsychEngine/assets/136813839/b210e192-4df9-446a-9e13-6ca2d0dfb1fe)

So basically I'm trying to make the game crash at a specific time during Game Over screen in lua and nothing seems to be working at this point.

**Comment by frantastic24** [comment]
1. `runTimer()`, case sensitivity
2. `return Function_Continue` does nothing

**Comment by XenJy** [comment]
oh I see, so is there like another way to do this without source code?

**Comment by XenJy** [comment]
I meant to make this whole fucking thing work

**Comment by frantastic24** [comment]
> 1. `runTimer()`, case sensitivity
> 2. `return Function_Continue` does nothing

i already explained

**Comment by XenJy** [comment]
oh my god i was so fucking stupid, you were right cuz the 't' letter on my runTimer is actually in lowercase. Thank you so much and sorry for me being dumbass
