### ISSUE TITLE
Crash every time a song finishes

### ISSUE THREAD

**Issue by DarkLightDboy** [ShadowMario/FNF-PsychEngine#12586]
### Describe your bug here.

I made the arrows in Monochrome move, and now every time the song finishes i get this:

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/129552573/ec8d541f-3199-4e62-b2fc-482cef5b217e)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, already described it

**Comment by DarkLightDboy** [comment]
Update: This happens after EVERY song or when pressing restart song now

**Comment by DarkLightDboy** [comment]
Another update: It seems to have fixed itself? Idk programming looks confusing

**Comment by NotStampyC** [comment]
probably a script thats incorrect or a major asset to the game is missing

**Comment by TheLeerName** [comment]
was smth wrong with volume, crash handler throwed line of get_volume
