### ISSUE TITLE
How do I make it to where a lua sprite shows when only a certain song plays? 

### ISSUE THREAD

**Issue by WoodsSilent05** [ShadowMario/FNF-PsychEngine#12585]
### What is your question?

I'm porting Impostor V4 to Psych for practice and for fun, but I don't know how to make a lua sprite appear if a certain song is playing, because I'm trying to make the bg stickmen appear when Armed is playing, but not for any other songs in the week.

**Comment by Lorekeeper49** [comment]
2 things you can do:
1. Add a script to the song itself that adds the sprites
2. Or, add an if clause to the stage script where it checks `if songName == 'your song' then` add the the sprites

**Comment by NotStampyC** [comment]
`function onCreatePost()`
`    if songName == 'song' then --put your song here`
`      triggerEvent('your event','', '');`
`    end`
`end`
