### ISSUE TITLE
Note Trouble

### ISSUE THREAD

**Issue by FwostyX3** [ShadowMario/FNF-PsychEngine#1259]
### Describe your problem here.

i should... Probably research a bit more

what code do i use to set the textures smh 
![image](https://user-images.githubusercontent.com/87388604/142883350-e363376e-37a0-4a4b-935f-6ece77786516.png)

its a lua note code!!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

**Comment by FwostyX3** [comment]
Now they are showing as normal notes AUHFOPSUIDCSDC

**Comment by FwostyX3** [comment]
did something else and now they are all just down notes ig

**Comment by ShadowMario** [comment]
Check Lua Script API for the custom note type example
