### ISSUE TITLE
Intro cutscenes (without source code)

### ISSUE THREAD

**Issue by PlasticFred** [ShadowMario/FNF-PsychEngine#12590]
### What feature do you want to get added on the **base** engine?

Not sure how possible this feature would be. But for the life of me, the Psych Engine source code will NOT compile. I'm planning on adding a cutscene right when the game is booted up, before the intro stuff. Since source code is out of the question, I'm asking for this to be a feature (if it's possible to add).

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by CaptainBaldi** [comment]
skill issue

**Comment by MemeHovy** [comment]
not happening, learn to code bruh ☠️

**Comment by waiter22** [comment]
yes'nt (cant be done, only source)

**Comment by Sword352** [comment]
Uuuh what?
This is probably not going to be added to the engine anyways, but what do you mean by "the Psych Engine source will NOT compile"? Did you get issues while compiling? If yes, what issues and what target did you try to compile to?

**Comment by NexIsDumb** [comment]
Uhm
You could just learn to edit the Splash screen of Flixel
Is that HaxelFlixel animated screen that used to pop up in the original FNF game for example

**Comment by PlasticFred** [comment]
> Uuuh what? This is probably not going to be added to the engine anyways, but what do you mean by "the Psych Engine source will NOT compile"? Did you get issues while compiling? If yes, what issues and what target did you try to compile to?

Despite following all the instructions, downloading all necessary software, and installing every command, I get this error whenever I type "lime test windows"--

"Error: You must have a "project.xml" file or specify another valid project file when using the 'test' command"

I HAVE THE SOURCE CODE VERSION OF PSYCH ENGINE DOWNLOADED AND PROJECT.XML EXISTS ON MY COMPUTER!!

So what am I missing?

**Comment by frantastic24** [comment]
You're supposed to run the command from your project folder, it will not find the project file otherwise
You can also use the .bat files in the art folder

**Comment by Sword352** [comment]
> > Uuuh what? This is probably not going to be added to the engine anyways, but what do you mean by "the Psych Engine source will NOT compile"? Did you get issues while compiling? If yes, what issues and what target did you try to compile to?
> 
> Despite following all the instructions, downloading all necessary software, and installing every command, I get this error whenever I type "lime test windows"--
> 
> "Error: You must have a "project.xml" file or specify another valid project file when using the 'test' command"
> 
> I HAVE THE SOURCE CODE VERSION OF PSYCH ENGINE DOWNLOADED AND PROJECT.XML EXISTS ON MY COMPUTER!!
> 
> So what am I missing?

What frantastic34 just said

**Comment by PlasticFred** [comment]
> > > Uuuh what? This is probably not going to be added to the engine anyways, but what do you mean by "the Psych Engine source will NOT compile"? Did you get issues while compiling? If yes, what issues and what target did you try to compile to?
> > 
> > 
> > Despite following all the instructions, downloading all necessary software, and installing every command, I get this error whenever I type "lime test windows"--
> > "Error: You must have a "project.xml" file or specify another valid project file when using the 'test' command"
> > I HAVE THE SOURCE CODE VERSION OF PSYCH ENGINE DOWNLOADED AND PROJECT.XML EXISTS ON MY COMPUTER!!
> > So what am I missing?
> 
> What frantastic34 just said

Thank you, I seem to be getting closer. Not sure what it means by this, though...

"Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup"

**Comment by Sword352** [comment]
> "Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup"

This is a warning, ignore it

**Comment by PlasticFred** [comment]
> > "Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup"
> 
> This is a warning, ignore it

To my understanding, typing "lime test windows" is the final step before it opens Psych Engine (the source version), meaning you're done compiling. When I typed "lime test windows", it just gave me that warning (and other random warning stuff) and then left me with nothing. All I can do is type it again if I wanted. Same outcome every time though.

**Comment by Sword352** [comment]
> To my understanding, typing "lime test windows" is the final step before it opens Psych Engine (the source version), meaning you're done compiling. When I typed "lime test windows", it just gave me that warning (and other random warning stuff) and then left me with nothing. All I can do is type it again if I wanted. Same outcome every time though.

Listen bro i think you just got some common errors so #source-code-info-fixes in the psych engine server ok thanks 🙏
