### ISSUE TITLE
So i was wondering

### ISSUE THREAD

**Issue by NavaGaming** [ShadowMario/FNF-PsychEngine#12596]
### Describe your problem here.

Is there a way to put` opponentStrums`(or the player one) on the `camGame`?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheLeerName** [comment]
setObjectCamera(obj, camera)?????

**Comment by TheLeerName** [comment]
ah yes u need change camera of `notes` too if you changing camera for player and opponent strums

**Comment by MaybeMaru** [comment]
use runHaxeCode, if i remember correctly there was a script of this already like a year ago in the discord server
