### ISSUE TITLE
Just a bit of needs for helping with the hardcoding characters

### ISSUE THREAD

**Issue by mechaniccdevlpr** [ShadowMario/FNF-PsychEngine#12599]
### Describe your problem here.

Now I've been stuck at this problem for 1-2 days, and I'm gonna explain thoroughly about this.

The problem with this is the paths, I don't know what to do about it as my knowledge with the engine is not as much as to assume, but here is some images to see the problem.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/130424149/fdaf8885-6ec4-4851-a161-ef9775ea2bb4)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/130424149/dd8f01ae-0430-46b8-bd58-188b40fca789)
(KEEP IN MIND OFFSETS ARE PLACEHOLDER)

Just needing assistance in the directory for the characters, I've also had the same problems with the json character creation.
I'm guessing the problem is the directory, the directory is literally "assets/tiffany" as using the standard "images/" and "shared/images" is a bit too repetitive.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Just the character.hx, just with characters that are not fully hardcoded.

**Comment by CaptainBaldi** [comment]
getSparrowAtlas looks for images and xmls in the images folder
honestly changing where the character files are because the image folders are "too repetitive" is a really fucking petty reason but you do you i guess
