### ISSUE TITLE
Font not loading

### ISSUE THREAD

**Issue by Zbyszeq** [ShadowMario/FNF-PsychEngine#12593]
### Describe your problem here.

So, I was messing around Project.xml, and I basically made a hiddenContent folder, then embedded it to be not present in the files. But for some reason, after I did that, the font wasn't loading anywhere : in the main menu, freeplay, songs, etc. Everything that used flxText was not loading its font. Can someone tell me why, and how to fix that?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited Project.xml and embedded one folder I added

**Comment by Username2120** [comment]
make sure to set embeddedText to true when you define the FlxText
