### ISSUE TITLE
I had the same error but on diffrent thing

### ISSUE THREAD

**Issue by Godofbacon1** [ShadowMario/FNF-PsychEngine#1260]
### Describe your bug here.

I did the dialogue for my mod and i made a command that when he select the week it start dialogue but when i start the week it gets me the same error its Null Object refrence

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I made a command in PlayState.hx that starts dialogue

And here is the evidence

https://user-images.githubusercontent.com/94835099/142885945-4e87df08-1196-4e57-83bb-4ee9f9e06eb6.mp4

**Comment by ShadowMario** [comment]
Show your code and where you saved your dialogue character sprites, where you saved your dialogue.json and your script.lua file for the dialogue.

**Comment by Godofbacon1** [comment]
wait actully i dont have the script

**Comment by Godofbacon1** [comment]
I think this is the problem

**Comment by Godofbacon1** [comment]
Here is the code:
![Screenshot 2021-11-23 074131](https://user-images.githubusercontent.com/94835099/142968783-0f82d658-3a6a-4ae5-b750-6a78831d0227.png)
I have put the dialogue sprites on bin/mods/images/dialogue:
![Screenshot 2021-11-23 074239](https://user-images.githubusercontent.com/94835099/142968878-35c8a396-6be3-43d5-ae01-1043c6140e63.png)
And I have put the dialogue and the script in bin/mods/data/my song folder:
![Screenshot 2021-11-23 074840](https://user-images.githubusercontent.com/94835099/142968932-625c44c9-2ddf-4ae0-ad5b-5f51b29d5008.png)

**Comment by Godofbacon1** [comment]
I have found the soulotion
