### ISSUE TITLE
Lua C++ Exception Error

### ISSUE THREAD

**Issue by dombomb64** [ShadowMario/FNF-PsychEngine#12608]
### Describe your problem here.

For some reason, when I try to change the `flipHealthBar` variable that I added in the source with a Lua script, I get the error "`ERROR: (onCreate) C++ exception`". I tried searching everywhere for what caused it to say that, but I couldn't find anything because there are so many extern functions. This also happens with two custom Lua functions that I added.
The variable has one of those functions that automatically triggers when it's set, if that helps.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Mainly unrelated things except for what was mentioned already.

**Comment by TheLeerName** [comment]
send lua script and lines from source which i added pls

**Comment by dombomb64** [comment]
Okay, here. There's some other stuff that I changed, like adding a second BF and Dad, but I don't think that those changes are that relevant.

testingChamber.lua:
```lua
function onCreate()
	luaDebugMode = true;
	makeLuaSprite('testingChamber1', 'stages/testingChamber1', 0, 0);
	setScrollFactor('testingChamber1', 0.5, 0.5);
	makeLuaSprite('testingChamber2', 'stages/testingChamber2', 0, 0);
	setScrollFactor('testingChamber2', 0.7, 0.7);
	makeAnimatedLuaSprite('testingChamber3', 'stages/testingChamber3', 550, 45);
	addAnimationByPrefix('testingChamber3', 'idle', 'Idle');
	setScrollFactor('testingChamber3', 0.8, 0.8);

	addLuaSprite('testingChamber1', false);
	addLuaSprite('testingChamber2', false);
	addLuaSprite('testingChamber3', false);

	--setProperty('flipHealthBar', true); -- All three of these cause the error
	--flipHealthBar(true);
	--swapStrums(true);

	close();
end
```

FunkinLua.hx:
Line 2772 (After the directoryFileList function is added):
```haxe
		Lua_helper.add_callback(lua, "flipHealthBar", function(value:Bool) {
			PlayState.instance.flipHealthBar = value;
		});
		Lua_helper.add_callback(lua, "swapStrums", function(cancelIfMiddlescroll:Bool = true) {
			if (cancelIfMiddlescroll && ClientPrefs.middleScroll)
				return;
			for (i in 0...4) {
				var tempX = PlayState.instance.playerStrums.members[i].x;
				var tempY = PlayState.instance.playerStrums.members[i].y;
				PlayState.instance.playerStrums.members[i].x = PlayState.instance.opponentStrums.members[i].x;
				PlayState.instance.playerStrums.members[i].y = PlayState.instance.opponentStrums.members[i].y;
				PlayState.instance.opponentStrums.members[i].x = tempX;
				PlayState.instance.opponentStrums.members[i].y = tempY;
			}
		});
```

PlayState.hx:
Line 200 (After healthBar is initialized):
```haxe
	public var flipHealthBar(default, set):Bool = false;
```

Line 5694 (The last function in the class):
```haxe
	private function set_flipHealthBar(value:Bool):Bool
	{
		healthBar.flipX = value;
		iconP1.flipX = value;
		iconP1b.flipX = value;
		iconP2.flipX = value;
		iconP2b.flipX = value;
		flipHealthBar = value;
		reloadHealthBarColors();
		return value;
	}
```

**Comment by TheLeerName** [comment]
onCreatePost()

**Comment by dombomb64** [comment]
> onCreatePost()

Thanks! This was it! I can't believe I didn't try that, to be honest.
