### ISSUE TITLE
pls Someone help me,i don't know how 2 fix this error

### ISSUE THREAD

**Issue by axolotl-mouka** [ShadowMario/FNF-PsychEngine#12607]
### Describe your problem here.

PS E:\downloads\!!!SURCE CODE!!!\FNF-PsychEngine-mainStupid\FNF-PsychEngine-main> lime test windows
source/PlayState.hx:75: characters 33-53 : Type not found : hxcodec.VideoHandler
source/FunkinLua.hx:479: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:497: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:503: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:553: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:559: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:599: lines 599-603 : Int should be Bool
source/FunkinLua.hx:599: lines 599-603 : ... For function argument 'f'
source/PlayState.hx:1575: characters 13-23 : Type not found : MP4Handler    

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheLeerName** [comment]
#12605
