### ISSUE TITLE
Error: Could not find include file "C:/HaxeToolkit/haxe/lib/hxCodec/3,0,0/vlc/lib/LibVLCBuild.xml"

### ISSUE THREAD

**Issue by Dslasha** [ShadowMario/FNF-PsychEngine#12603]
### Describe your bug here.

Error: Could not find include file "C:/HaxeToolkit/haxe/lib/hxCodec/3,0,0/vlc/lib/LibVLCBuild.xml"

### Command Prompt/Terminal logs (if existing)

```bash
Error: Could not find include file "C:/HaxeToolkit/haxe/lib/hxCodec/3,0,0/vlc/lib/LibVLCBuild.xml"
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Dslasha** [comment]
> `haxelib install hxCodec 2.5.1`

thx! it worked

**Comment by NullGang** [comment]
same error but I have the version of hxCodec the same
