### ISSUE TITLE
How i fixxxxxxxxxxxx this?

### ISSUE THREAD

**Issue by axolotl-mouka** [ShadowMario/FNF-PsychEngine#12605]
PS E:\downloads\!!!SOURCE CODE!!!\FNF-PsychEngine-mainStupid\FNF-PsychEngine-main> lime test windows
source/PlayState.hx:75: characters 33-53 : Type not found : hxcodec.VideoHandler
source/FunkinLua.hx:479: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:497: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:503: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:553: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:559: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:599: lines 599-603 : Int should be Bool
source/FunkinLua.hx:599: lines 599-603 : ... For function argument 'f'
source/PlayState.hx:1575: characters 13-23 : Type not found : MP4Handler

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by axolotl-mouka** [comment]
i'm fool,plz someone help me :(

**Comment by TheLeerName** [comment]
```
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
haxelib install hxCodec 2.5.1
```

**Comment by axolotl-mouka** [comment]
PS E:\downloads\!!!SURCE CODE!!!\FNF-PsychEngine-mainStupid\FNF-PsychEngine-main> lime test windows
source/FunkinLua.hx:479: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:497: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:503: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:553: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:559: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:599: lines 599-603 : Int should be Bool
source/FunkinLua.hx:599: lines 599-603 : ... For function argument 'f'

**Comment by axolotl-mouka** [comment]
> 
PS E:\downloads\!!!SURCE CODE!!!\FNF-PsychEngine-mainStupid\FNF-PsychEngine-main> lime test windows
source/FunkinLua.hx:479: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:497: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:503: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:553: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:559: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:599: lines 599-603 : Int should be Bool
source/FunkinLua.hx:599: lines 599-603 : ... For function argument 'f'

**Comment by axolotl-mouka** [comment]
> ```
> haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
> haxelib install hxCodec 2.5.1
> ```

it did't work

**Comment by axolotl-mouka** [comment]
> ```
> haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
> haxelib install hxCodec 2.5.1
> ```

PS E:\downloads\!!!SURCE CODE!!!\FNF-PsychEngine-mainStupid\FNF-PsychEngine-main> lime test windows
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
E:\downloads\!!!SURCE CODE!!!\FNF-PsychEngine-mainStupid\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion 
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by axolotl-mouka** [comment]
> ```
> haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
> haxelib install hxCodec 2.5.1
> ```

It work Thank u.
