### ISSUE TITLE
how to fix :c

### ISSUE THREAD

**Issue by Dslasha** [ShadowMario/FNF-PsychEngine#12600]
### Describe your bug here.

idk why but this pops up for some odd reason please help somebody

C:/Users/Downloads/FNF-PsychEngine-main/FNF-PsychEngine-main/.haxelib/flixel-addons/3,1,1/flixel/addons/text/FlxTypeText.hx:8: characters 8-29 : Type not found : flixel.sound.FlxSound
source/PlayState.hx:75: characters 33-53 : Type not found : hxcodec.VideoHandler
C:/Users/Downloads/FNF-PsychEngine-main/FNF-PsychEngine-main/.haxelib/flixel-addons/3,1,1/flixel/addons/text/FlxTypeText.hx:78: characters 26-34 : Type not found : FlxSound
source/CoolUtil.hx:19: lines 19-154 : ... Defined in this class
C:/Users/Downloads/FNF-PsychEngine-main/FNF-PsychEngine-main/.haxelib/flixel-addons/3,1,1/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/PlayState.hx:1575: characters 13-23 : Type not found : MP4Handler
source/DialogueBox.hx:144: characters 16-22 : flixel.addons.text.FlxTypeText has no field sounds
source/DialogueBox.hx:244: characters 16-25 : flixel.addons.text.FlxTypeText has no field resetText
source/DialogueBox.hx:245: characters 16-21 : flixel.addons.text.FlxTypeText has no field start
source/DialogueBox.hx:246: characters 16-32 : flixel.addons.text.FlxTypeText has no field completeCallback
source/DialogueBox.hx:223: characters 18-22 : flixel.addons.text.FlxTypeText has no field skip
C:/Users/dan20/Downloads/FNF-PsychEngine-main/FNF-PsychEngine-main/.haxelib/flixel-addons/3,1,1/flixel/addons/transition/FlxTransitionableState.hx:81: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field

### Command Prompt/Terminal logs (if existing)

```bash
C:/Users/Downloads/FNF-PsychEngine-main/FNF-PsychEngine-main/.haxelib/flixel-addons/3,1,1/flixel/addons/text/FlxTypeText.hx:8: characters 8-29 : Type not found : flixel.sound.FlxSound
source/PlayState.hx:75: characters 33-53 : Type not found : hxcodec.VideoHandler
C:/Users/Downloads/FNF-PsychEngine-main/FNF-PsychEngine-main/.haxelib/flixel-addons/3,1,1/flixel/addons/text/FlxTypeText.hx:78: characters 26-34 : Type not found : FlxSound
source/CoolUtil.hx:19: lines 19-154 : ... Defined in this class
C:/Users/Downloads/FNF-PsychEngine-main/FNF-PsychEngine-main/.haxelib/flixel-addons/3,1,1/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/PlayState.hx:1575: characters 13-23 : Type not found : MP4Handler
source/DialogueBox.hx:144: characters 16-22 : flixel.addons.text.FlxTypeText has no field sounds
source/DialogueBox.hx:244: characters 16-25 : flixel.addons.text.FlxTypeText has no field resetText
source/DialogueBox.hx:245: characters 16-21 : flixel.addons.text.FlxTypeText has no field start
source/DialogueBox.hx:246: characters 16-32 : flixel.addons.text.FlxTypeText has no field completeCallback
source/DialogueBox.hx:223: characters 18-22 : flixel.addons.text.FlxTypeText has no field skip
C:/Users/dan20/Downloads/FNF-PsychEngine-main/FNF-PsychEngine-main/.haxelib/flixel-addons/3,1,1/flixel/addons/transition/FlxTransitionableState.hx:81: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Username2120** [comment]
make sure you have hxcodec 2.5.1 and flixel addons 2.11.0

**Comment by Dslasha** [comment]
> make sure you have hxcodec 2.5.1 and flixel addons 2.11.0 and flixel 4.11.0

i do but it still doesnt work for me

**Comment by Dslasha** [comment]
> make sure you have hxcodec 2.5.1 and flixel addons 2.11.0 and flixel 4.11.0

thank u it worked :D
