### ISSUE TITLE
Camera Zoom Change

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#12616]
### What is your question?

As of now, is there a way to bypass, that either the dad, or bf has to hit a note, to be able to change the camera zoom?

**Comment by MemeHovy** [comment]
setProperty(“camZooming”, true);

**Comment by TheLeerName** [comment]
```lua
-- for change multiplier of zoom intensity: setProperty('camZoomingMult', 2)
-- for change multiplier of zoom turning to default: setProperty('camZoomingDecay', 2)

function opponentNoteHit(id, noteData, noteType, isSus)
  setProperty('camGame.zoom', 0.03 * getProperty('camZoomingMult'))
  setProperty('camHUD.zoom', 0.015 * getProperty('camZoomingMult'))
end
function goodNoteHit(id, noteData, noteType, isSus)
  setProperty('camGame.zoom', 0.03 * getProperty('camZoomingMult'))
  setProperty('camHUD.zoom', 0.015 * getProperty('camZoomingMult'))
end
```

**Comment by MemeHovy** [comment]
> ```lua
> -- for change multiplier of zoom intensity: setProperty('camZoomingMult', 2)
> -- for change multiplier of zoom turning to default: setProperty('camZoomingDecay', 2)
> 
> function opponentNoteHit(id, noteData, noteType, isSus)
>   setProperty('camGame.zoom', 0.03 * getProperty('camZoomingMult'))
>   setProperty('camHUD.zoom', 0.015 * getProperty('camZoomingMult'))
> end
> function goodNoteHit(id, noteData, noteType, isSus)
>   setProperty('camGame.zoom', 0.03 * getProperty('camZoomingMult'))
>   setProperty('camHUD.zoom', 0.015 * getProperty('camZoomingMult'))
> end
> ```

they’re asking so the camera zooms by default

**Comment by MemeHovy** [comment]
y’all need to learn to read, and I already answered the question too anyways
