### ISSUE TITLE
Pause Music Rename In Menu

### ISSUE THREAD

**Issue by coolmcslime** [ShadowMario/FNF-PsychEngine#12619]
### Describe your problem here.

How do I rename the pause music 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
can you be more specific?

**Comment by Lorekeeper49** [comment]
You don't, unless you mean using different music for the pause menu, in which case, you can either replace the file, or use `playMusic()` in `onPause()`

**Comment by TheLeerName** [comment]
```lua
local pauseMusicPath = 'musicfile'
function onCreate()
  savedPM = getPropertyFromClass('ClientPrefs', 'pauseMusic')
  setPropertyFromClass('ClientPrefs', 'pauseMusic', pauseMusicPath)
end
function onDestroy()
  setPropertyFromClass('ClientPrefs', 'pauseMusic', savedPM) -- return default
end
```

**Comment by coolmcslime** [comment]
> You don't, unless you mean using different music for the pause menu, in which case, you can either replace the file, or use `playMusic()` in `onPause()`

Right now I can change the music, but its song name still is the default , i want to change it

**Comment by Jericho2013** [comment]
I really think you should use source, I think there is no way to change it with Lua. You _might_ be able to detect it with Lua. Maybe like the "downscroll" detection or something.

**Comment by TheLeerName** [comment]
> I really think you should use source, I think there is no way to change it with Lua. You _might_ be able to detect it with Lua. Maybe like the "downscroll" detection or something.

nah bro my code works without source

**Comment by TheLeerName** [comment]
or if you want change it in options menu u cant really

**Comment by Jericho2013** [comment]
> or if you want change it in options menu u cant really


That is what he wants.
