### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by STIk-3807** [ShadowMario/FNF-PsychEngine#12610]
### Describe your problem here.

i tried compiling my psych source code and i get an error for "FlxAnimationController" and idk what to do

source/flixel/animation/FlxAnimationController.hx:164: characters 39-47 : flixel.graphics.frames.FlxFrame has no field duration

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i edited FlxAnimationController for a mod

**Comment by TheLeerName** [comment]
https://gist.githubusercontent.com/superpowers04/0b01e40e0f272d134f87c5c30712cb66/raw/2366ea0b8d34b08c74119e22f7690d29e63e7f43/FlxAnimationController.hx

and update flixel to latest
