### ISSUE TITLE
Move the combo thing?

### ISSUE THREAD

**Issue by Kirsenal** [ShadowMario/FNF-PsychEngine#12611]
### Describe your problem here.

So I was wondering if you could move the thing that like says your combo and "Sick!" or whatever on a song, because in one of them it covers things and it is kind of annoying

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
Look in the options menu :skull:

**Comment by Lorekeeper49** [comment]
> Look in the options menu :skull:

I think he wants a specific song to move the ratings to a certain position, and in that case, use Unholywanderer's custom ratings script

**Comment by Kirsenal** [comment]
> > Look in the options menu 💀
> 
> I think he wants a specific song to move the ratings to a certain position, and in that case, use Unholywanderer's custom ratings script

yeah so what part of the script is the part that lets me move it because in this twenty mile long script I am unsure what does it, what I'm seeing is this script changes a lot about the combo and such when all I want to do is move its position

**Comment by Lorekeeper49** [comment]
> > > Look in the options menu 💀
> > 
> > 
> > I think he wants a specific song to move the ratings to a certain position, and in that case, use Unholywanderer's custom ratings script
> 
> yeah so what part of the script is the part that lets me move it because in this twenty mile long script I am unsure what does it, what I'm seeing is this script changes a lot about the combo and such when all I want to do is move its position

it should be in the options

**Comment by TheLeerName** [comment]
`setPropertyFromClass('ClientPrefs', 'comboOffset', {ratingX, ratingY, numX, numY})`
`getPropertyFromClass('ClientPrefs', 'comboOffset')`
returns a table where
1 index - x of rating image
2 index - y of rating image
3 index - x of numbers image
4 index - y of numbers image

**Comment by Kirsenal** [comment]
> `setPropertyFromClass('ClientPrefs', 'comboOffset', {ratingX, ratingY, numX, numY})` `getPropertyFromClass('ClientPrefs', 'comboOffset')` returns a table where 1 index - x of rating image 2 index - y of rating image 3 index - x of numbers image 4 index - y of numbers image

whenever I load up the song with this it says the getPropertyFromClass is a nil value or something is there something else in that I need to input besides the x and y values

**Comment by TheLeerName** [comment]
put it in onCreate() and bro learn lua pls

**Comment by Kirsenal** [comment]
> put it in onCreate() and bro learn lua pls

chill working on it lmfao
