### ISSUE TITLE
How 2 fix this problem??????

### ISSUE THREAD

**Issue by axolotl-mouka** [ShadowMario/FNF-PsychEngine#12614]
### Describe your problem here.

When i Reopen the VSC,it show me problems:TYPE not found : 'everythings'   ,but i can still build my game.how 2 fix it.

![Problem](https://github.com/ShadowMario/FNF-PsychEngine/assets/134141822/8fa39a68-93bd-4607-a778-cd7f3f476df2)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheLeerName** [comment]
its stupid, it always shows it

**Comment by TheLeerName** [comment]
![zaQC7e2w2r](https://github.com/ShadowMario/FNF-PsychEngine/assets/85291330/8c46731d-8821-4e24-b178-8b0c966ca06c)
click that bell

**Comment by axolotl-mouka** [comment]
> Wait I might know why since it used to happen to me too Did you install any extensions for haxe in the visual studio code extensions manager?

i just install extension "haxe"

**Comment by NexIsDumb** [comment]
> > Wait I might know why since it used to happen to me too Did you install any extensions for haxe in the visual studio code extensions manager?
> 
> 
> 
> i just install extension "haxe"

You sure that is nothing else?
Try to delete all extensions and install just the Haxe one
Just that not even other Haxe's extensions

**Comment by axolotl-mouka** [comment]
> > > > > 等等，我可能知道为什么，因为它曾经也发生在我身上 您是否在Visual Studio代码扩展管理器中安装了Haxe的任何扩展？
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 我只是安装扩展“Haxe”
> > 
> > 
> > > 
> > 
> > 
> > > 你确定没有别的？尝试删除所有扩展并仅安装Haxe扩展 只是甚至没有其他Haxe的扩展
> > 
> > 
> > 不，它不起作用
> 
> 那么它只是 vsc 错误 你是如何安装库的 使用 Hmm 方法？

use cmd 'haxelib install'

**Comment by axolotl-mouka** [comment]
> Contributor



> > > > > Wait I might know why since it used to happen to me too Did you install any extensions for haxe in the visual studio code extensions manager?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > i just install extension "haxe"
> > 
> > 
> > > 
> > 
> > 
> > > You sure that is nothing else? Try to delete all extensions and install just the Haxe one Just that not even other Haxe's extensions
> > 
> > 
> > Nope,it did't work
> 
> Then it's just vsc fault How did you install the libraries Using the Hmm method?

Use CMD

**Comment by NexIsDumb** [comment]
> > Contributor
> 
> 
> 
> 
> 
> 
> 
> > > > > > Wait I might know why since it used to happen to me too Did you install any extensions for haxe in the visual studio code extensions manager?
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > i just install extension "haxe"
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > You sure that is nothing else? Try to delete all extensions and install just the Haxe one Just that not even other Haxe's extensions
> 
> > > 
> 
> > > 
> 
> > > Nope,it did't work
> 
> > 
> 
> > Then it's just vsc fault How did you install the libraries Using the Hmm method?
> 
> 
> 
> Use CMD

Yeah but did you do stiff like running hmm in the cmd?

**Comment by axolotl-mouka** [comment]
> > > Contributor
> > 
> > 
> > > > > > > Wait I might know why since it used to happen to me too Did you install any extensions for haxe in the visual studio code extensions manager?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > i just install extension "haxe"
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > You sure that is nothing else? Try to delete all extensions and install just the Haxe one Just that not even other Haxe's extensions
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Nope,it did't work
> > 
> > 
> > > 
> > 
> > 
> > > Then it's just vsc fault How did you install the libraries Using the Hmm method?
> > 
> > 
> > Use CMD
> 
> Yeah but did you do stuff like running hmm in the cmd?

no

**Comment by NexIsDumb** [comment]
> no

Then this is fr odd
But dw since you can build the game, it's not a big deal
