### ISSUE TITLE
WUT THE

### ISSUE THREAD

**Issue by Sonkinator1991** [ShadowMario/FNF-PsychEngine#12618]
### Describe your bug here.

So i was playing on ur engine, and I have 2 mods installed on it (Vs. Bazi and Stickin') but for some reason, opening songs from the og game will crash it, and idk wuts happening.

### Command Prompt/Terminal logs (if existing)

```bash
Paths.hx (line 356)
Character.hx (line 164)
Boyfriend.hx (line 16)
PlayState.hx (line 978)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added 2 mods

**Comment by TheLeerName** [comment]
corrupted character image

**Comment by Sonkinator1991** [comment]
O yea I tried to replace bf with hog Sent from Mail for Windows From: LeerSent: Sunday, June 25, 2023 11:56 AMTo: ShadowMario/FNF-PsychEngineCc: Sonkinator1991; AuthorSubject: Re: [ShadowMario/FNF-PsychEngine] WUT THE (Issue #12618) corrupted character image—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by dombomb64** [comment]
You'll want to make sure that, in the character JSON file, the animation names (as listed in the XML) and image path are pointing to the right things.

Also, epic embed fail. :trollface:
