### ISSUE TITLE
Working with globals is strange

### ISSUE THREAD

**Issue by Lorekeeper49** [ShadowMario/FNF-PsychEngine#12612]
### Describe your problem here.

It could very well be because the script is actually outside the modpack since that's what seemed to cause another problem where a certain song wouldn't show 2 different strumlines like it was supposed to, but using `setGlobalFromScript()` seems to not work in `onCreate()` or `onCreatePost()` unless the song has an intro.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheLeerName** [comment]
send two scripts u used

**Comment by Lorekeeper49** [comment]
[outside modpack](https://github.com/ShadowMario/FNF-PsychEngine/files/11860798/Anime.Rythm.Game.txt)
[inside modpack](https://github.com/ShadowMario/FNF-PsychEngine/files/11860799/Remove.Scripts.txt)

**Comment by TheLeerName** [comment]
1. why it .txt
2. you setting globals in `onCreatePost()` which used in `onStartCountdown()` ( cuz game firstly calls `onStartCountdown()` and then `onCreatePost()` )  use `onCreate()` instead of `onCreatePost()`

**Comment by Lorekeeper49** [comment]
> 1. why it .txt
> 2. you setting globals in `onCreatePost()` which used in `onStartCountdown()` ( cuz game firstly calls `onStartCountdown()` and then `onCreatePost()` ) uses `onCreate()` instead of `onCreatePost()`

1. GitHub doesn't allow uploading lua files
2. I tried that before, I don't think it worked
