### ISSUE TITLE
Hu idk but there is this

### ISSUE THREAD

**Issue by XuhXih9** [ShadowMario/FNF-PsychEngine#12615]
### hu idk
![sad](https://github.com/ShadowMario/FNF-PsychEngine/assets/137618556/d8417cdd-d6ce-4942-ac30-0630374a901d)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ZeitHeld** [comment]
what did you do? or what happened?

**Comment by XuhXih9** [comment]
> what did you do? or what happened?

idk i did not do anything

**Comment by ZeitHeld** [comment]
do you have any mods or scripts installed? if yes, then maybe turn them off.
if not, maybe try to reinstall?

**Comment by TheLeerName** [comment]
corrupted or not exist image
