### ISSUE TITLE
Hex colors didn't work

### ISSUE THREAD

**Issue by MrEG100** [ShadowMario/FNF-PsychEngine#12622]
### Describe your problem here.

I download source for Psych Engine 0.6.3, tried to put my mod on lua in here and for some reason commands for changing colors like "setProperty('sonic.color', getColorFromHaxe('1d226a'))" or doTweenColor('son1', 'sonic', '1d226a', 0.5, 'cubeOut') didn't work. I didn't change anything, just compiled it. Can you help me?

Here example in normal only unzipped Psych Engine:
![notsource](https://github.com/ShadowMario/FNF-PsychEngine/assets/103056109/dc118be9-a31b-4db6-a0cd-329c53cae712)
And here example in source code:
![source](https://github.com/ShadowMario/FNF-PsychEngine/assets/103056109/779eea85-bf63-404d-b6f7-5681b248d4f7)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by PaRappa1996** [comment]
the same thing happened to me, but it's a different mod and it's 0.5.2h

**Comment by KookerFoxYT** [comment]
> the same thing happened to me, but it's a different mod and it's 0.5.2h

hxcpp moment

**Comment by Drawoon2** [comment]
Is `getColorFromHex("1d226a")` and not is `getColorFromHaxe('1d226a')`

**Comment by MrEG100** [comment]
> Is `getColorFromHex("1d226a")` and not is `getColorFromHaxe('1d226a')`
Not have any difference. I'm coding in Lua for a year, I know how it's work

**Comment by MrEG100** [comment]
> hxcpp moment

nah, I downloaded latest version

**Comment by MemeHovy** [comment]
> > hxcpp moment
> 
> nah, I downloaded latest version

that fixes the issue

**Comment by MemeHovy** [comment]
but 4.2.1 is broken

**Comment by MrEG100** [comment]
> but 4.2.1 is broken

I use 4.3.2, but can use 4.2.1 or 4.1.15 to make sure that maybe one of them work

**Comment by MemeHovy** [comment]
> > but 4.2.1 is broken
> 
> I use 4.3.2, but can use 4.2.1 or 4.1.15 to make sure that maybe one of them work

4.2.1 for sure is broken, but 4.1.15 isn’t

**Comment by MrEG100** [comment]
> 



> > > but 4.2.1 is broken
> > 
> > 
> > I use 4.3.2, but can use 4.2.1 or 4.1.15 to make sure that maybe one of them work
> 
> 4.2.1 for sure is broken, but 4.1.15 isn’t

I tried 4.3.2 or 4.2.1, not worked. Now trying 4.1.15

**Comment by MrEG100** [comment]
> > 
> 
> > > > but 4.2.1 is broken
> > > 
> > > 
> > > I use 4.3.2, but can use 4.2.1 or 4.1.15 to make sure that maybe one of them work
> > 
> > 
> > 4.2.1 for sure is broken, but 4.1.15 isn’t
> 
> I tried 4.3.2 or 4.2.1, not worked. Now trying 4.1.15

It's worked! So! You need to download "hxcpp" version 4.1.15
Write "haxelib install hxcpp 4.1.15" and then "haxelib set hxcpp 4.1.15"

**Comment by MemeHovy** [comment]
using the latest git version and 4.3.2 worked for me
