### ISSUE TITLE
help me with source pls :(

### ISSUE THREAD

**Issue by Hogich** [ShadowMario/FNF-PsychEngine#12625]
### Describe your problem here.

i try to compile the psych engine main and i have this problem

Error: You must have a "project.xml" file or specify another valid project file when using the 'test' command

tell me how to fix it please?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed the x coordinate in MainMenuState.hx

**Comment by Username2120** [comment]
make sure when your trying to compile you are compiling to the folder with the project,xml in it. if your compiling through vs code change your selected folder from just the source code to the folder with the project.xml in it.

**Comment by Hogich** [comment]
I decided to try compiling again and now I have this error:
source/TitleState.hx:30: character 8 : `package;` in source/flixel/system/FlxSound.hx should be `package flixel.system;`
source/editors/ChartingState.hx:150: characters 13-21 : Type not found : FlxSound
