### ISSUE TITLE
Stage crashing

### ISSUE THREAD

**Issue by mik0primeb** [ShadowMario/FNF-PsychEngine#12626]
### Describe your bug here.

I was making the stage for my mod. When i done it i tested on mod song and it crashed with this error but when im loading the same stage on original fnf songs it works propely. 

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2641)
PlayState.hx (line 2469)
PlayState.hx (line 1086)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Duplicate of #12124

**Comment by mik0primeb** [comment]
> Duplicate of #12124

So the problem is that i used stage_clone from Wiki? If yes then what stage i should use to stop crashing?

**Comment by mik0primeb** [comment]
Nevermind
