### ISSUE TITLE
Error in Github Actions in this Engine

### ISSUE THREAD

**Issue by Jamesx0YT** [ShadowMario/FNF-PsychEngine#12624]
### Describe your problem here.

Error with Github Actions, I did not move anything, it is the same as I copied it before modifying the files but it gives me an error ;(
![Screenshot_20230625-135400](https://github.com/ShadowMario/FNF-PsychEngine/assets/95061460/1d3b1d4b-ff89-484d-9a4f-024d2fc454fa)
![Screenshot_20230625-135405](https://github.com/ShadowMario/FNF-PsychEngine/assets/95061460/d82557d3-48ef-4ce2-82f0-8982c03fa875)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no, don't edit anything

**Comment by Username2120** [comment]
make sure you have flixel 4.11.0 and haxe 4.2.5

**Comment by Jamesx0YT** [comment]
Thank you very much, I found the problem in the `hmm.json` document, there I was able to edit these 2 things and the haxe if it was in 4.2.5, the problem was the `flixel / flixel-addons`
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/95061460/2afe4c9b-1cad-4e9b-85a2-3dbb97dd3f13)
