### ISSUE TITLE
trying to do the test windows but having issue with this discord thing

### ISSUE THREAD

**Issue by swrt758** [ShadowMario/FNF-PsychEngine#12621]
### Describe your problem here.

when i try to make the "lime test windows" command, this thing appears:
source/Discord.hx:7: characters 8-16 : Type not found : llua.Lua
source/Discord.hx:8: characters 8-18 : Type not found : llua.State
source/Discord.hx:96: characters 45-50 : Type not found : State

what do i do?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit

**Comment by swrt758** [comment]
already did that

**Comment by swrt758** [comment]
> haxelib git linc_luajit https://github.com/superpowers04/linc_luajit

already did that

**Comment by MemeHovy** [comment]
did you disable lua in discord.hx?

**Comment by swrt758** [comment]
> did you disable lua in discord.hx?

how to do it?

**Comment by MemeHovy** [comment]
just by removing the lua imports, and the callback

**Comment by swrt758** [comment]
> just by removing the lua imports, and the callback

if i disable lua then i can't use lua scripts in my project at all and more errors start to appear

**Comment by TheLeerName** [comment]
do `haxelib list`, it should have linc_luajit

**Comment by swrt758** [comment]
ill try find own way to fix this problem with my friend.
