### ISSUE TITLE
The game opens and then immediately closes 

### ISSUE THREAD

**Issue by Loll05** [ShadowMario/FNF-PsychEngine#12628]
### Describe your problem here.

I tried to do lime test Windows to compile the source code and it made me wait for about ten minutes. Then the game opened but it immediately closed and I don't know how to proceed.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by TheLeerName** [comment]
uh idk, try use only english letters in folder names, cuz it crashes with it

**Comment by Loll05** [comment]
@TheLeerName nope it's all in english. I already checked

**Comment by Cyachao** [comment]
try clearing save data in AppData/Roaming

**Comment by Luisinhi010** [comment]
i'm having the same problem.
