### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by greenlife0226** [ShadowMario/FNF-PsychEngine#12620]
### Describe your problem here.

I'm having trouble dealing with the "Users/hp/Downloads/FNF-psychengine-main/.haxelib/flixel/5,3,1/flixel/system/macros/FlxDefines.hx:79: characters 61-65 : Unsupported Haxe version! Supported versions are 4.2.5 or newer (found 4.105)." 
error when buliding with lime test windows. I tried reinstalling haxelib,but that didn't work. if anyone knows another way, please let me know.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
use haxe 4.2.5

**Comment by MemeHovy** [comment]
can you really not read?

**Comment by greenlife0226** [comment]
hmm,building is difficult。
i used haxe 4.2.5 and it displayed this.↓

source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
C:/Users/hp/Downloads/FNF-psychengine-main/.haxelib/flixel/5,3,1/flixel/animation/FlxAnimation.hx:231: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
C:/Users/hp/Downloads/FNF-psychengine-main/.haxelib/flixel-addons/3,1,1/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'Object'
source/FunkinLua.hx:2196: lines 2196-2199 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2196: lines 2196-2199 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object'
source/PlayState.hx:584: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:584: characters 25-35 : ... For function argument 'Object'
source/PlayState.hx:2388: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2388: characters 23-29 : ... For function argument 'Object'
source/PlayState.hx:2389: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2389: characters 23-83 : ... For function argument 'Object'
source/PlayState.hx:1781: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1781: characters 25-37 : ... For function argument 'Object'
source/PlayState.hx:1828: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1828: characters 25-34 : ... For function argument 'Object'
source/PlayState.hx:1899: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1899: characters 25-36 : ... For function argument 'Object'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1359: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1359: characters 24-30 : ... For function argument 'Object'
source/editors/ChartingState.hx:2196: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/Users/hp/Downloads/FNF-psychengine-main/.haxelib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 55-60 : flixel.animation.FlxAnimationController has no field field
C:/Users/hp/Downloads/FNF-psychengine-main/.haxelib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 61-74 : Too many arguments

C:\Users\hp\Downloads\FNF-psychengine-main>lime test windows
source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
C:/Users/hp/Downloads/FNF-psychengine-main/.haxelib/flixel/5,3,1/flixel/animation/FlxAnimation.hx:231: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
C:/Users/hp/Downloads/FNF-psychengine-main/.haxelib/flixel-addons/3,1,1/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'Object'
source/FunkinLua.hx:2196: lines 2196-2199 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2196: lines 2196-2199 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object'
source/PlayState.hx:584: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:584: characters 25-35 : ... For function argument 'Object'
source/PlayState.hx:2388: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2388: characters 23-29 : ... For function argument 'Object'
source/PlayState.hx:2389: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2389: characters 23-83 : ... For function argument 'Object'
source/PlayState.hx:1781: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1781: characters 25-37 : ... For function argument 'Object'
source/PlayState.hx:1828: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1828: characters 25-34 : ... For function argument 'Object'
source/PlayState.hx:1899: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1899: characters 25-36 : ... For function argument 'Object'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1359: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1359: characters 24-30 : ... For function argument 'Object'
source/editors/ChartingState.hx:2196: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/Users/hp/Downloads/FNF-psychengine-main/.haxelib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames

**Comment by greenlife0226** [comment]
it says there is no field numframes,but I don't know how to write the code...

**Comment by TheLeerName** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by Baldi9262** [comment]
how to install 4.2.5 though
