### ISSUE TITLE
character and chart edititor

### ISSUE THREAD

**Issue by RedWindower** [ShadowMario/FNF-PsychEngine#12627]
### Describe your bug here.

everytime i press character or chart edititor it crashes over and over again and those are the most import things i need!

### Command Prompt/Terminal logs (if existing)

```bash
everytime i press character or chart edititor it crashes over and over again and those are the most import things i need!
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by TheLeerName** [comment]
show error
and bro pls read what u need to write in issue
