### ISSUE TITLE
How to use??

### ISSUE THREAD

**Issue by sevenhillsus** [ShadowMario/FNF-PsychEngine#12636]
### Describe your problem here.

This is my first time to coding a lua script, when I make a animated sprite is not showing in game
Code:
function onCreate()
    makeLuaSprite('floor', 'Ponk/spk', -1500, 300)
    addLuaSprite('floor', false)
    
    makeAnimatedLuaSprite('Sev', 'sevenhill', -1500, 300)
    addLuaSprite('Sev',false)
    luaSpriteAddAnimationByPrefix('Sev', dance, 'seven', 10, false)
    luaSpritePlayAnimation('Sev', dance, false)
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by InsiderIV** [comment]
Remove the "luaSprite" at the beginning of both "AddAnimationByPrefix" and "PlayAnimation".

**Comment by Lorekeeper49** [comment]
> Remove the "luaSprite" at the beginning of both "AddAnimationByPrefix" and "PlayAnimation".

Follow-up: "PlayAnimation" should just be "playAnim" (case matters)

**Comment by TheLeerName** [comment]
deprecated functions ☠☠☠
where u found this script lol

and second argument of addAnimationByPrefix is string (u writed `dance` instead of `'dance'`)
