### ISSUE TITLE
How to make a typing text in haxe code?

### ISSUE THREAD

**Issue by JustMe1352** [ShadowMario/FNF-PsychEngine#12633]
### Describe your problem here.

What I mean about typing text, is that I want a box where when you press on it you could type in it. Like a search bar.

![Screenshot 2023-06-26 213958](https://github.com/ShadowMario/FNF-PsychEngine/assets/130803298/a7e742d3-4b0b-493d-a6d6-40cb207e2890)

All of this I'm trying to put in haxe code because I want to go it in the MainMenuState.hx for reason.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
see https://api.haxeflixel.com/flixel/addons/ui/FlxInputText.html

**Comment by JustMe1352** [comment]
thanks

**Comment by MemeHovy** [comment]
> thanks

np
