### ISSUE TITLE
Giving Achievements Resets the Save Data?

### ISSUE THREAD

**Issue by RaginggYT** [ShadowMario/FNF-PsychEngine#12639]
### Describe your problem here.

In the PlayState.hx script, at the end in the checkForAchievement function I grant the achievement for completing a certain character's week. Everything then works fine, but once you reload the game, the save data is reset.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I've edited ClientPrefs to add some new variables, edited PlayState to do the thing mentioned above, and made a custom play menu instead of story mode and freeplay but that's not really relevant to this.

**Comment by TheLeerName** [comment]
do `ClientPrefs.saveSettings();` after `Achievements.unlockAchievement`

**Comment by RaginggYT** [comment]
> do `ClientPrefs.saveSettings();` after `Achievements.unlockAchievement`

I tried that and then checked the save file and everything is saved correctly, but once the game is opened again the save file is wiped.
