### ISSUE TITLE
Character image keeps unloading

### ISSUE THREAD

**Issue by K1N00** [ShadowMario/FNF-PsychEngine#12638]
### Describe your bug here.

I keep adding a character, but when i do the offsets its all good, then if i close the game for any reason and open it up. the character image wont load, ive chacked the name, ive checked everything. it only loads if i remake the enire sprite cheet over again

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no response

**Comment by CaptainBaldi** [comment]
are you saving the character

**Comment by K1N00** [comment]
> are you saving the character

yes, i save the character and use it, then next time i open the character, all the code is still their and the offsets but the image is unloaded, and idk why

**Comment by ShadowMario** [comment]
We need more info about where you stored all images and where are you trying to load them.

**Comment by ShadowMario** [comment]
Closed for inactivity
