### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by RBeansDev** [ShadowMario/FNF-PsychEngine#12635]
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/117064691/e79b93d3-3052-4e73-ba8c-e29030e60caf)
  it says that videoplayer and mp4player are missing. anyone got solution?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i edit playstate with a jumscare for a mod

**Comment by TheLeerName** [comment]
haxelib install hxCodec 2.5.1
