### ISSUE TITLE
Save Data Resetting

### ISSUE THREAD

**Issue by RaginggYT** [ShadowMario/FNF-PsychEngine#12634]
### Describe your problem here.

So I have a bool variable in ClientPrefs to save whether or not a certain week is completed. In PlayState, inside of the checkForAchievement function inside of if (unlock), I do ClientPrefs.loadPrefs(); then I set the week completed's variable to true and do ClientPrefs.saveSettings();

It works fine but when I reload the mod, the settings are all reset to default.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I've edited ClientPrefs to add some new variables, and edited PlayState to do the thing mentioned above.

**Comment by Luk9as** [comment]
what did you do to solve it, i have the same problem

**Comment by Chidubemmo** [comment]
Same

**Comment by Chidubemmo** [comment]
I'm begging you
