### ISSUE TITLE
I can't put a . in my song name

### ISSUE THREAD

**Issue by 1MFunnyThingsYT** [ShadowMario/FNF-PsychEngine#12637]
### Describe your problem here.

So, I'm making a mod and I wanna name one of the songs "Error.json" but, when I try, the game just bugs and the song won't work. And before you say anything, on an older build of the mod, naming it that actually worked (The build was on 0.52H i believe)
So any help i can get?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Only added some .lua files in the scripts folder (And an extra lua file in the song folder that just makes the notes move around)

**Comment by TheLeerName** [comment]
its must be `error.json` cuz game lowercases it
