### ISSUE TITLE
Amount of Notes Left for the Player Instead of All Notes

### ISSUE THREAD

**Issue by ChaoZBusterZ** [ShadowMario/FNF-PsychEngine#12647]
### Describe your problem here.

I'm making a mod and I'm trying to add a HUD detail where it shows you how many notes you have left to hit. Using `unspawnNotes.length` doesn't work, as it shows both the player's and the opponent's notes. Is there a way that it will only show how many player notes there are left instead of both?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by TheLeerName** [comment]
`if (note.mustPress)` - player
`if (!note.mustPress)` - opponent

**Comment by ChaoZBusterZ** [comment]
Thank you!
Also, where do I insert that code in to count it?
