### ISSUE TITLE
My Held Notes Dissapear

### ISSUE THREAD

**Issue by Panda85GH** [ShadowMario/FNF-PsychEngine#12644]
### Describe your bug here.

When I make a new chart in psych engine in the "chart editor" and I put sustain on a note it is seen in the editor and in the game when I test it in the normal game, but when I save the chart I close the game and open it again to edit the chart, the sustain just disappears when I test it, what do I do?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
don't make duplicate issues

**Comment by Panda85GH** [comment]
> don't make duplicate issues

I posted them on both by mistake because I didn't know which one to comment on

**Comment by MemeHovy** [comment]
> > don't make duplicate issues
> 
> I posted them on both by mistake because I didn't know which one to comment on

close the duplicate
