### ISSUE TITLE
This Error pops up from trying to enter story mode

### ISSUE THREAD

**Issue by EpicMawerDiff** [ShadowMario/FNF-PsychEngine#12640]
### Describe your bug here.

StoryMenuState.hx (line 275)
flixel/group/FlxGroup.hx (line 740)
StoryMenuState.hx (line 273)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

Freeplay works, for some reason...

 I think that the source code messed up during importing into my drive, but I don't know for sure

I have the build from before I put it in drive, so if that build is ok, I'll probably close this issue

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only downloaded the build on google drive and extracted it recently

**Comment by TheLeerName** [comment]
maybe image in `storemenu/` is not exists idk

**Comment by ODHG1** [comment]
a folder is missing

**Comment by EpicMawerDiff** [comment]
The another build works, I guess it did either miss a folder or something

**Comment by EpicMawerDiff** [comment]
Just figured out why, the computer for some reason didn't let that build to open the story mode, but I only needed to copy the mod and assets into a new psych engine build
