### ISSUE TITLE
Hold notes render incorrect lengths or no lengths at all.

### ISSUE THREAD

**Issue by ScarabWasTaken** [ShadowMario/FNF-PsychEngine#12649]
### Describe your bug here.

Hold notes get reduced by 1 step length including down to 0 from 1.

Its very easy to detect in lua post render.
(each step is 107..ms at 140 BPM)
Here I'm flagging notes with a sustainLength greater than 0 but a tail.length of 0.
You'll also notice the first line a sustainLength failing successfully to render as 8 (when it should be 7) 750/107..=7
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/85250052/880e7a69-0b7b-4cf2-bf5a-7e6e2d275305)

Sometimes the tail renders for 1step-sustains but they render as length of 2 step. This typically only happens in the first section of the song when there are no rounding errors.

The code I used to watch hold notes:

`function goodNoteHit(id, direction, noteType, isSustainNote)
	if not isSustainNote then
		debugPrint(getPropertyFromGroup('notes', id, 'tail.length'), "   ", getPropertyFromGroup('notes', id, 'sustainLength'));
		if getPropertyFromGroup('notes', id, 'sustainLength') > 0 and getPropertyFromGroup('notes', id, 'tail.length') == 0 then
			debugPrint("failed to load tail");
		end
	end
end`

I suspect the culprit starts at /PlayState.hx#L2457
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/85250052/8b260736-f885-41f3-a0e4-9437723ac67a)
There should be a Math.max(1, ...) to pick up on these missed sustain notes. But it doesnt explain the extra long 750ms hold.

The following issues also mention this bug
#10492
#11462

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ScarabWasTaken** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/85250052/96e98e7c-d385-4eb0-b465-c9df3741fce1)
I'll throw this one in as well.
A 2 step hold rendering as length 3 (The Left arrow being pressed)
And a 1 step hold note rendering as length 0 (The Down arrow being pressed)

**Comment by Bezizeja** [comment]
kade engine reference?!?

**Comment by PogofruitKM** [comment]
psych engine intentionally makes all sustains 1 step longer at `for (susNote in 0...floorSus+1)` in line 2464
and 1 step sustains being length 0 is most likely because of BPM being higher than charted, which math.floor just drops away
