### ISSUE TITLE
flixel.util.FlxTimer should be Int

### ISSUE THREAD

**Issue by Stefan2008Git** [ShadowMario/FNF-PsychEngine#12652]
### Describe your problem here.

Help me guys. For some reason it's giving me this error. Im trying to add loading bar from LoadingState.hx to CacheState.hx, but sadly i got this error

`flixel.util.FlxTimer should be Int`

![Snimak ekrana 2023-06-30 003031](https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/cd92fd68-4c70-4d62-aa5a-43b38304511c)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Adding from LoadingState.hx to CacheState.hx for better loading

**Comment by MemeHovy** [comment]
you can’t use flxtimer as an int or float

**Comment by Stefan2008Git** [comment]
> you can’t use flxtimer as an int or float

It's late. I closed :(

**Comment by MemeHovy** [comment]
> > you can’t use flxtimer as an int or float
> 
> It's late. I closed :(

damn
