### ISSUE TITLE
About the new note RGB values for custom notes

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#12650]
### What is your question?

As the experimental build showed, the way the colors of notes gets determined can be changed in the options.
Though, would one also be able to change those for custom notes?
Like, for the hurt note, that I would simply be able to set the RGB values to represent the same colors as the sprite did, that one would require. is it possible to do it like that too? Or would it then again affect the entire note, and recolor it/shift it's hue?

**Comment by Sword352** [comment]
You are able to change the hurt note's rgb values.
Check the `set_texture` function in the Note class, when setting your notetype you will be able to directly modify the RGB values of the shader.
```haxe
case "MyNoteType":
        rgbShader.r = 100; // this is an example
```

**Comment by ZeitHeld** [comment]
but that will then apply to the entire sprite, instead of just the border or middle, right?
(cause I am asking about the upcoming update too, but am unsure as of now)

And would it also be possible with lua?
