### ISSUE TITLE
Playing the song a few moments then crashing

### ISSUE THREAD

**Issue by BloodMoonDS** [ShadowMario/FNF-PsychEngine#12655]
### Describe your bug here.

# Hello
Since a long time ago I've been experiencing errors during the moment that the mod plays, first I thought the problem was I was building from source, I was only modifying the icon of the mod and the example-mods folder so, I didn't modify the engine's code, so i transferred my lua mod into the mods folder in the clean build and the error persists, At first i thought It was related to the chart thing because I used an old version back then when the engine allowed to use Philly stage lights outside its stage, so I deleted all the events inside this chart but It didn't work.

## What I need
I need to solve this error, if you need the chart or something you can tell me.

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 3224)
flixel/group/FlxGroup.hx (line 769)
PlayState.hx (line 3179)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only icons when using the source

**Comment by frantastic24** [comment]
not a bug
note texture is missing `end` animations
