### ISSUE TITLE
what is this problem?

### ISSUE THREAD

**Issue by axolotl-mouka** [ShadowMario/FNF-PsychEngine#12665]
### Describe your problem here.

I did't hide hit sound option inOptionsState but i can't see it in the game.

![d](https://github.com/ShadowMario/FNF-PsychEngine/assets/134141822/71830c6b-0850-44a4-8724-fdbdbc9086a2)
![f](https://github.com/ShadowMario/FNF-PsychEngine/assets/134141822/38c697ed-2c6e-4598-9c20-92274338a329)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes

**Comment by PogofruitKM** [comment]
but it's down there?? i don't understand your problem.

**Comment by MemeHovy** [comment]
> but it's down there?? i don't understand your problem.

me neither, you need to be more specific @axolotl-mouka
