### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by aless26pic** [ShadowMario/FNF-PsychEngine#12668]
### Describe your problem here.

source/Alphabet.hx:198: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:163: characters 13-21 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/Main.hx:74: characters 61-65 : Float should be Int
source/Main.hx:74: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:74: characters 61-65 : ... For function argument 'child'
source/PlayState.hx:120: characters 40-48 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:157: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:158: characters 25-33 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:238: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:3560: characters 38-41 : Warning : This pattern is unused
source/PlayState.hx:3569: characters 38-41 : Warning : This pattern is unused
source/PlayState.hx:120: characters 68-76 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:1146: characters 18-26 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:1180: characters 18-26 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:217: characters 28-36 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:293: characters 19-27 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:295: characters 19-27 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:605: characters 22-30 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2189: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2191: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2194: characters 27-35 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2196: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:28: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:52: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:1224: characters 16-24 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:39: characters 13-21 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:109: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:111: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
help please

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes

**Comment by LiveDaniReaction** [comment]
if you're still having this problem then tell me what version of flixel you're using

**Comment by ReSteGuy** [comment]
If you are using the hmm to compile, use this. Works for me

[hmm.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/12005862/hmm.txt)

**Comment by ReSteGuy** [comment]
Main folder

**Comment by aless26pic** [comment]
i have fix this

**Comment by ReSteGuy** [comment]
> i have fix this

if you fixed it close it
