### ISSUE TITLE
ChartingState.hx issue when compiling

### ISSUE THREAD

**Issue by SlimeGuyy** [ShadowMario/FNF-PsychEngine#12661]
### Describe your problem here.

I used the releases source code
This is the error I get when compiling;

C:\Users\dokid\OneDrive\Desktop\FNF-PsychEngine-0.6.3>lime test windows
source/editors/ChartingState.hx:2295: characters 3-5 : Expected }

I have the exact versions from https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions
Help will be appreciated
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/89882214/e326c59a-43d3-43c7-9af6-55c10fbda272)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited by using fixes from the comment that stands out; https://github.com/ShadowMario/FNF-PsychEngine/issues/12582

**Comment by CaptainBaldi** [comment]
missing } read the error

**Comment by Cyachao** [comment]
you didn't follow it
`In source/editors/ChartingState.hx, add @:privateAccess { right above if (FlxG.save.data.chart_waveformInst) { around line 2195 add a } right after one of the } around line 2227`
