### ISSUE TITLE
how 2 make freeplay menu like vs impostor v4(by code)

### ISSUE THREAD

**Issue by axolotl-mouka** [ShadowMario/FNF-PsychEngine#12662]
### Describe your problem here.

Change bg characters while select song.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ripsyhehe** [comment]
me when impostor v4 source code is public:
[](https://github.com/Clowfoe/IMPOSTOR-UPDATE/blob/main/source/AmongFreeplayState.hx)

**Comment by MemeHovy** [comment]
https://github.com/Clowfoe/IMPOSTOR-UPDATE

**Comment by axolotl-mouka** [comment]
> https://github.com/Clowfoe/IMPOSTOR-UPDATE

I want to make it by PE0.6.3

**Comment by Karim-Akra** [comment]
> 

Literally idk what can be useful with doing this but just copy and paste the mod code from the source

**Comment by Sword352** [comment]
This is very simple, you don't even have to look into VS impostor's source code, unless you are lazy.

https://api.haxefliwel.com
Trust me this website is the path to flixel-learning and familiarization with the framework because we cannot code everything for you.

**Comment by axolotl-mouka** [comment]
> This is very simple, you don't even have to look into VS impostor's source code, unless you are lazy.
> 
> https://api.haxefliwel.com Trust me this website is the path to flixel-learning and familiarization with the framework because we cannot code everything for you.

I know it,but thank u.

**Comment by Sword352** [comment]
No problem, glad to help!
