### ISSUE TITLE
how to remove extra buttons in main menu

### ISSUE THREAD

**Issue by vesel4ak** [ShadowMario/FNF-PsychEngine#12664]
### What feature do you want to get added on the **base** engine?

hi guys how do i remove buttons "awards, credits, donate"
I want only these buttons to remain: "Story mode, freeplay, options"

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by pablowolfgamerbr** [comment]
for this to work. u need to find optionShit in MainMenuState.hx

**Comment by pablowolfgamerbr** [comment]
and do it

**Comment by pablowolfgamerbr** [comment]
var optionShit:Array<String> = [
		'story_mode',
		'freeplay',
		//#if MODS_ALLOWED 'mods', #end
		//#if ACHIEVEMENTS_ALLOWED 'awards', #end
		//'credits',
		//#if !switch 'donate', #end
		'options'
	];

**Comment by codeyballpa** [comment]
but where do i put mainmenustate.hx? i know about the folder but the question is where do i PUT the folder?

**Comment by codeyballpa** [comment]
please help
im dying
