### ISSUE TITLE
Character based Health Drain

### ISSUE THREAD

**Issue by NotStampyC** [ShadowMario/FNF-PsychEngine#12671]
### What is your question?

I want to make a health drain that changes depending on the character.
This is what i have so far:

`function opponentNoteHit()`
`    health = getProperty('health')`
`    if charchange == 'bobPISSED' then`
`        if getProperty('health') > 0.05 then`
`        	setProperty('health', health- 0.05);`
`    elseif charchange == 'bob' then`
`        if getProperty('health') > 0.05 then`
`        	setProperty('health', health- 0.02);`
`    end`
`end`

`function goodNoteHit()`
`       health = getProperty('health')`
`    	if getProperty('health') < 1 then`
`        	setProperty('health', health+ 0.01);`
`	elseif getProperty('health') > 1.90 then`
`		setProperty('health', 1.90);`
`    end`
`end`

`function onUpdate()`
`    	health = getProperty('health')`
`       if ratingName == 'Bruh' or ratingName == 'Bad' or ratingName == 'Shit' or ratingName == 'You Suck!' then`
`		setProperty('health', 1);`
`    end`
`end`

**Comment by DisIsNOt** [comment]
local drainAmt = 0.024

function opponetNoteHit() 
     if(getProperty('boyfriend.curCharacter') == "someone") then
     drainAmt = 0.250

end

addHealth(-drainAmt)


end

**Comment by NotStampyC** [comment]
ok ill try

**Comment by NotStampyC** [comment]
'if getProperty('dad.curCharacter') == "someone" then'
Helped lots the rest of your code didnt work but this did so thanks DisIsNOt
