### ISSUE TITLE
Lua script that will change the "three two one go!" at the beginning of a song 

### ISSUE THREAD

**Issue by SrBagel** [ShadowMario/FNF-PsychEngine#12673]
### Describe your problem here.

I'm trying to make a Lua script that will change the sounds played at a songs intro but it doesn't work

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
#9578

**Comment by SrBagel** [comment]
> #9578

Thanks
