### ISSUE TITLE
any suggestions on this compiling fix?

### ISSUE THREAD

**Issue by Bezizeja** [ShadowMario/FNF-PsychEngine#12672]
### Describe your bug here.

i tried compiling engine and got this message

### Command Prompt/Terminal logs (if existing)

```bash
LINK : fatal error LNK1181: cannot open input file 'libvlc.lib'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by NexIsDumb** [comment]
> ### Describe your bug here.
> 
> i tried compiling engine and got this message
> 
> ### Command Prompt/Terminal logs (if existing)
> 
> ```bash
> LINK : fatal error LNK1181: cannot open input file 'libvlc.lib'
> ```
> 
> 
> ### Are you modding a build from source or with Lua?
> 
> Source
> 
> ### What is your build target?
> 
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> 
> nope

Did you change hxCodec version
