### ISSUE TITLE
I need help with the custom freeplay

### ISSUE THREAD

**Issue by JaxTheChameleon** [ShadowMario/FNF-PsychEngine#12676]
### What is your question?

So, hello again people. I wanted to ask ya'll, do any of you know how to put animated sprites in the freeplay?

**Comment by axolotl-mouka** [comment]
put this code in line120
var  animatedsprites:FlxSprite;
animatedsprites = new FlxSprite(X,Y).loadGraphic(Paths.image('mainmenucharacters/SpriteName'));
animatedsprites.frames = Paths.getSparrowAtlas('SpriteName');
animatedsprites.animation.addByPrefix('idle', 'YourAnimateName in xml', 12, true);
animatedsprites.animation.play('idle');
animatedsprites.scrollFactor.set();
animatedsprites.antialiasing = ClientPrefs.globalAntialiasing;
add(animatedsprites);

I don't know if it can work.

**Comment by axolotl-mouka** [comment]
Put this code in line 120

`var animatedsprite:FlxSprite;

animatedsprite = new FlxSprite(X,Y).loadGraphic(Paths.image('SpriteName in preload images'));
animatedsprite.frames = Paths.getSparrowAtlas('SpriteName in preload images');
animatedsprite.animation.addByPrefix('idle', 'XML animation name', 24, true);
animatedsprite.animation.play('idle');
animatedsprite.scrollFactor.set();
animatedsprite.antialiasing = ClientPrefs.globalAntialiasing;
add(animatedsprite);`

I don't know if it can work.

**Comment by DisIsNOt** [comment]
May be fine override function create or whatever, do something like this:

 var animatedSprite:FlxSprite = new FlxSprite();

animatedSprite.frames = Paths.getSparrowAtlas(path);
animatedSprite.animation.addByPrefix('idle', 'xml');

animatedSprite.animation.play('idle');
add(animatedSprite);


Idk it may be will work

**Comment by JaxTheChameleon** [comment]
Thank you both so much. Both of your codes are working.

**Comment by DisIsNOt** [comment]
May be fine override function create or whatever, do something like this:

 var animatedSprite:FlxSprite = new FlxSprite();

animatedSprite.frames = Paths.getSparrowAtlas(path);
animatedSprite.animation.addByPrefix('idle', 'xml');

animatedSprite.animation.play('idle');
add(animatedSprite);


Idk it may be will work
