### ISSUE TITLE
A couple things I want in Psych

### ISSUE THREAD

**Issue by SrBagel** [ShadowMario/FNF-PsychEngine#12682]
### What feature do you want to get added on the **base** engine?

1. A setting that makes the time bar display nothing like the bar is still there but it has no characters on it
2. I'm sure this has been requested already but the ability to change the note sustain length by dragging down like in Fps+

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MemeHovy** [comment]
interesting

**Comment by ShadowMario** [comment]
1. Lua Script
2. I am not gonna change Chart Editor for now

**Comment by SrBagel** [comment]
> 1. Lua Script
> 2. I am not gonna change Chart Editor for now

Alright thanks anyway.
