### ISSUE TITLE
Build Stuff

### ISSUE THREAD

**Issue by WaFl-XIV** [ShadowMario/FNF-PsychEngine#12681]
### What is your question?

So it's been a long time since I last ran "lime test windows" and when I ran it, it couldn't find haxelib "hxCodec". I had to download a new Psych Engine folder and move the files I added before to that one since there were too many new updates for me to replace my current code.

Do I have to download new stuff or did I break something when I moved some files?

**Comment by WaFl-XIV** [comment]
Ok so I did have to install new stuff, but now I'm getting an error where Type not found hxcodec.VideoHandler and MP4Handler. How do I fix this?

**Comment by WaFl-XIV** [comment]
Oh nvm I had to do more stuff. Now I just need to remember how to update Haxe because apparently I didn't have the latest version.

**Comment by WaFl-XIV** [comment]
So uhhh the version I'm currently using is apparently 4.2.3 (or 4.203 according to Windows PowerShell for some reason) and apparently I need at least version 4.2.5 so now I'm trying to remember when and where I first downloaded Haxe.

**Comment by ShadowMario** [comment]
[This page has a link for Haxe 4.2.5 along with all libraries versions in case something is not compiling](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)
