### ISSUE TITLE
BPM Change in scoreTxt.text

### ISSUE THREAD

**Issue by ChaoZBusterZ** [ShadowMario/FNF-PsychEngine#12683]
### Describe your problem here.

I'm making a mod where it shows the BPM in the Score Text, the one in PlayState.hx and where it says `scoreTxt.text =` . Right now I have `SONG.bpm + ' BPM'`, but that only shows the starting BPM and when the BPM changes, the text doesn't. Is there a way to  change the text with the BPM (**with source only**)?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ClassicBoost** [comment]
SONG.bpm would only display what the BPM is in the json file, even if it's changed mid song it won't change. Conductor.bpm will always display the current bpm.
Although since you are setting this to score text, it won't update until a note is hit/missed.

**Comment by ChaoZBusterZ** [comment]
Ah ok, thank you!

**Comment by MemeHovy** [comment]
> Ah ok, thank you! Also, do event notes count as the hit or missed thing?

event notes aren't real notes

**Comment by BeastlyGabi** [comment]
scoreText.text = 'BPM: ${Conductor.bpm}';
