### ISSUE TITLE
cant open freeplay or storymode without an error message

### ISSUE THREAD

**Issue by Alexanderlo58** [ShadowMario/FNF-PsychEngine#12687]
### Describe your bug here.

C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 318)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 110)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 90)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
WeekData.hx (line 222)
WeekData.hx (line 190)
WeekData.hx (line 178)
FreeplayState.hx (line 60)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 550)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid char 93 at position 81
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no not something special

**Comment by ClassicBoost** [comment]
Is there a problem with the week json file?
