### ISSUE TITLE
Expected "}"?

### ISSUE THREAD

**Issue by Macaroni262** [ShadowMario/FNF-PsychEngine#12695]
### Describe your problem here.

I'm just confused on where to put the "}" at in the script.

![C__Windows_System32_cmd exe 7_7_2023 2_13_37 PM](https://github.com/ShadowMario/FNF-PsychEngine/assets/138635463/d1d15345-288c-4b6c-9453-ff431264a1d7)

![ChartingState hx - Microsoft Visual Studio 7_7_2023 2_15_41 PM](https://github.com/ShadowMario/FNF-PsychEngine/assets/138635463/6087262a-d233-4f89-8822-4beb5eb8f2a7)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I've edited the chartingstate to allow private access, however those were in completely different line areas.

**Comment by MemeHovy** [comment]
read the error

**Comment by Macaroni262** [comment]
But where do I put it?

**Comment by BernardoGP4504** [comment]
The error seems to be at the `private` keyword before the function
