### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by EstagBread** [ShadowMario/FNF-PsychEngine#12690]
### Describe your problem here.

So i am getting this compiling error since i am new to FNF modding i need some help (i dont know if someone can help me because of the giant error that i got but if someone can please help me)

C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/FlxBasic.hx:201: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/graphics/frames/FlxFrame.hx:680: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/graphics/frames/FlxFrame.hx:688: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/tweens/FlxTween.hx:24: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/FlxInput.hx:84: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/tile/FlxBaseTilemap.hx:1382: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/util/FlxDirectionFlags.hx:8: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/util/FlxDirection.hx:7: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/keyboard/FlxKey.hx:8: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/mouse/FlxMouseButton.hx:85: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/gamepad/FlxGamepadInputID.hx:12: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/discord_rpc/1,0,0/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/actions/FlxActionInputAnalog.hx:17: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/actions/FlxActionInputAnalog.hx:393: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel-addons/2,11,0/flixel/addons/transition/FlxTransitionSprite.hx:135: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel-addons/2,11,0/flixel/addons/transition/TransitionData.hx:11: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/text/FlxText.hx:1153: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/FunkinLua.hx:491: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:509: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:515: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:567: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:573: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:613: lines 613-617 : Int should be Bool
source/FunkinLua.hx:613: lines 613-617 : ... For function argument 'f'
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler
C:/HaxeToolkit/haxe/lib/flixel-ui/2,4,0/flixel/addons/ui/FlxUICursor.hx:561: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/util/FlxDestroyUtil.hx:3: characters 8-32 : You cannot access the flash package while in a macro (for flash.display.BitmapData)
source/animateatlas/AtlasFrameMaker.hx:2: characters 8-34 : ... referenced here
source/Paths.hx:3: characters 8-36 : ... referenced here
F:\Friday Night Funkin\Mods por mi\Estag Pack\FNF-PsychEngine-0.6.3\source\import.hx:1: characters 8-13 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/media/AudioSource.hx:138: characters 53-100 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/media/Sound.hx:14: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/utils/Assets.hx:9: characters 8-26 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/text/_internal/TextEngine.hx:9: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/_internal/CairoTextField.hx:3: characters 8-40 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/_internal/CairoGraphics.hx:6: characters 8-36 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/events/RenderEvent.hx:4: characters 8-44 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/DisplayObject.hx:13: characters 8-33 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,2/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,2/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Vno12** [comment]
https://github.com/Vno12/Fix-Build-Physic-Engine I fix It
