### ISSUE TITLE
Week icon

### ISSUE THREAD

**Issue by Mokona5901** [ShadowMario/FNF-PsychEngine#1269]
### What is your question?

Where is the information to show week icon (from base weeks in the downloaded build)?

**Comment by ShadowMario** [comment]
What

**Comment by Mokona5901** [comment]
When you go in story mode, there are week icons. I would like to know where can you see the system call of the game (in a file) to show the week icon in because when i create a week, and change week icon access path, the game crashes.
I hope to be understood

**Comment by Godofbacon1** [comment]
Look my dude if u want to change the week icon:
1- Make sure ur icon is png
2- put it on path Ur fnf folder/mods/weeks/put ur image here
3- open the game
4- click 7 on main screen
5- go on week editor
6- there is the week icon place in there put ur png name
7- Done!

**Comment by Mokona5901** [comment]
Precisely, when I change the access path of the image of the week (in custom week), the game crashes. That's why I prefer to copy a base week and that's why I want to know in a base week the line of code (I don't know which file) which appeals to the image.

**Comment by ShadowMario** [comment]
So... are you going to show where you put the files and how you've set it in the editor?
