### ISSUE TITLE
The UI Assets Bug

### ISSUE THREAD

**Issue by Mellow2110** [ShadowMario/FNF-PsychEngine#127]
Hey There! 
I am coding for one of the mods that i'm working on right now. So, When I tried adding the custom UI assets, they apparently messed up or so. Thought that would be problems with the assets alignments or size so i tried to edit them. After, I again compiled the game and again they messed up. I tried this with the current and previous source codes.

**Here are some screenshots:**

![bandicam 2021-09-25 15-44-32-953](https://user-images.githubusercontent.com/90918496/134768104-4ebc82de-32cd-49c1-8982-cec70c140dbc.jpg)
![bandicam 2021-09-25 15-45-00-434](https://user-images.githubusercontent.com/90918496/134768105-baf68a5c-8048-49bd-a987-9f18263fabc8.jpg)
![bandicam 2021-09-25 15-44-30-487](https://user-images.githubusercontent.com/90918496/134768107-d71ed690-0f6c-44e7-86e7-9ffa847c42d5.jpg)

so I check everything, it doesn't seems a problem from my side
Any fix for this bug?

**Comment by ShadowMario** [comment]
Send the assets or i can't figure out what is the issue

**Comment by Mellow2110** [comment]
> Send the assets or i can't figure out what is the issue

ok
![titleEnter](https://user-images.githubusercontent.com/90918496/134777104-a86d1ae8-3554-4e55-a261-fb70e79d8d91.png)
![logoBumpin](https://user-images.githubusercontent.com/90918496/134777109-e8f835b3-6d1e-4648-a8d0-c26793e09a61.png)
![campaign_menu_UI_assets](https://user-images.githubusercontent.com/90918496/134777114-a906ddfe-e60c-4906-bc99-4c3e0e404b74.png)
![Menu_Tracks](https://user-images.githubusercontent.com/90918496/134777122-cebbb159-13ea-4296-bd14-7b3185758c78.png)

These were the UI Assets.
(also the xmls are same as the base one)

**Comment by ShadowMario** [comment]
You're aware the images resolution are totally different, right??? Export your spritesheet from Adobe Animate for it to automatically generate a .xml file
