### ISSUE TITLE
Issues with "hxCodec.MP4" / "VideoHandler"

### ISSUE THREAD

**Issue by BoxOfGolds** [ShadowMario/FNF-PsychEngine#12707]
### Describe your problem here.

i was basically following [this video](https://www.youtube.com/watch?v=XSB9M-JylH8) and no matter what i change, i still get these two errors on lime test windows

`source/PlayState.hx:75: characters 33-51 : Type not found : hxcodec.MP4Handler`
`source/PlayState.hx:1575: characters 13-25 : Type not found : VideoHandler`

if someone can help, that would be great!!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yeah, i switched Main.hx for this (https://raw.githubusercontent.com/ShadowMario/FNF-PsychEngine/main/source/Main.hx)

**Comment by 12abz** [comment]
run haxelib install hxCodec 2.5.1

**Comment by BoxOfGolds** [comment]
![god i hate coding](https://github.com/ShadowMario/FNF-PsychEngine/assets/90431413/17689d84-529c-470a-bddd-02c907abe06f)
sorry for the late response but i tried and it didn't work ;-;

**Comment by BernardoGP4504** [comment]
Have you tried uninstalling and reinstalling it?

**Comment by BoxOfGolds** [comment]
![god i hate coding 2](https://github.com/ShadowMario/FNF-PsychEngine/assets/90431413/31910822-eecf-47f5-b391-7db207a63056)
tried to uninstall hxcodec, same problem lmao (i'll try reinstalling the build next)

**Comment by BoxOfGolds** [comment]
okay, reinstallling the build worked, thanks everyone!!!!
