### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by raxyd** [ShadowMario/FNF-PsychEngine#12714]
### Describe your problem here.

source/Main.hx:77: characters 19-29 : Missing ;
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/130116093/b623bad9-9bcd-4f1b-a938-e775b526f577)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by raxyd** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/130116093/69e2748f-dbbb-48e9-8936-d81a69ba2ab9)

**Comment by ender69funk** [comment]
add ;

**Comment by raxyd** [comment]
> Try this:
> 
> ```
> if (zoom == -1) {
>     var ratioX:Int = gameWidth;
>     var ratioY:Int = gameHeight;
>     zoom = Math.min(ratioX, ratioY);
>     gameWidth = Math.ceil(stageWidth / zoom);
>     gameHeight = Math.ceil(stageHeight / zoom);
> }
> ```
> 
> Obviously I don't know what the rest of your code is like and this is just a guess based on the little bit you provided.

that made it worse

**Comment by TorchTheDragon** [comment]
> > Try this:
> > ```
> > if (zoom == -1) {
> >     var ratioX:Int = gameWidth;
> >     var ratioY:Int = gameHeight;
> >     zoom = Math.min(ratioX, ratioY);
> >     gameWidth = Math.ceil(stageWidth / zoom);
> >     gameHeight = Math.ceil(stageHeight / zoom);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Obviously I don't know what the rest of your code is like and this is just a guess based on the little bit you provided.
> 
> that made it worse

well as stated, I don't know what the file looks like, so I just did a guess

**Comment by raxyd** [comment]
https://cdn.discordapp.com/attachments/1128181185546297366/1128181289577611396/Main.hx

**Comment by TorchTheDragon** [comment]
Our code (mine is slightly different due to the way the variables are set up) is actually very similar, I can't tell what the issue is. 
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/72819066/ce83d00d-a3b3-45c0-862c-1c6403873f82)
Left is my code, right is yours
