### ISSUE TITLE
Keep vocals on

### ISSUE THREAD

**Issue by JVgradiz** [ShadowMario/FNF-PsychEngine#12712]
### Describe your problem here.

I want to keep the vocals at 1 in a part of the song but all the codes i've tried didn't work

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by SomeoneUnknownForReal** [comment]
You can't

**Comment by CaptainBaldi** [comment]
what does this even mean

**Comment by JVgradiz** [comment]
> what does this even mean

I want to keep the variable "vocals.volume" at 1 during a part of the song, but i don't know how
