### ISSUE TITLE
I give up please help me

### ISSUE THREAD

**Issue by ReSteGuy** [ShadowMario/FNF-PsychEngine#12718]
### Describe your problem here.

haven't used source code in a while, i get null object reference when compiled.
The code is from preloader.hx

im trying to make a video play as a splash screen.
```
package ;
 
import flixel.system.FlxBasePreloader;
import openfl.display.Sprite;
import flash.display.Bitmap;
import flash.display.BitmapData;
import flash.display.BlendMode;
import flash.display.Sprite;
import flash.Lib;
import flixel.FlxG;
#if (hxCodec >= "2.6.1") import hxcodec.VideoHandler as MP4Handler;
#elseif (hxCodec == "2.6.0") import VideoHandler as MP4Handler;
#else import vlc.MP4Handler; #end
 
class Preloader extends FlxBasePreloader
{
    public function new(MinDisplayTime:Float=7, ?AllowedURLs:Array<String>) 
    {
        super(MinDisplayTime, AllowedURLs);
    }

    override function create():Void 
    {   
        var filepath:String = Paths.video("splashIntro");
        var video:MP4Handler = new MP4Handler();
		video.playVideo(filepath);
        super.create();
    }
     
    override function update(Percent:Float):Void 
    {
        super.update(Percent);
    }
}
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, Preloader.hx

**Comment by TheKitBoi** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/84044666/23d907d8-2573-4bc9-bd8a-1621e1ec4557)
did you even set this to false

**Comment by ReSteGuy** [comment]
> ![image](https://user-images.githubusercontent.com/84044666/252568992-23d907d8-2573-4bc9-bd8a-1621e1ec4557.png) did you even set this to false

update: im dumb as hell thanks
