### ISSUE TITLE
Error: The object does not have the property "alpha"

### ISSUE THREAD

**Issue by SomeoneUnknownForReal** [ShadowMario/FNF-PsychEngine#12711]
### What needs to be documented?

flixel/tweens/misc/VarTween.hx (line 99)
flixel/tweens/misc/VarTween.hx (line 55)
flixel/tweens/FlxTween.hx (line 1263)
flixel/FlxGame.hx (line 750)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: The object does not have the property "alpha"

I tried to make an additional option in timebar settings.

**Comment by CaptainBaldi** [comment]
Read the error

**Comment by SomeoneUnknownForReal** [comment]
I did when it poped out

**Comment by SomeoneUnknownForReal** [comment]
Idk how but I realized that it is an lua error and not source so I have to fix smth with my code

**Comment by SomeoneUnknownForReal** [comment]
Yes it actually was the lua script

**Comment by pandasclips2** [comment]
hi hmm i downloaded a mod and repair the bugs but i can't slove this error so im here if you can fix it ?
