### ISSUE TITLE
Hardcode characters

### ISSUE THREAD

**Issue by DisIsNOt** [ShadowMario/FNF-PsychEngine#12710]
### Describe your problem here.

How can I hardcode characters?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
check Character.hx, there's a comment in there somewhere depicting where you are able to hardcode your characters

**Comment by DisIsNOt** [comment]
Ohh ok thanks
