### ISSUE TITLE
Could someone help me explain the sentences? 

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#1271]
### What is your question?

There is a function in `PlayState.hx`:

```
function goodNoteHit(note:Note):Void
{
	if (!note.wasGoodHit)
	{
		if(cpuControlled && (note.ignoreNote || note.hitCausesMiss)) return;   //sentence 1
                //...
               callOnLuas('goodNoteHit', [notes.members.indexOf(note), leData, leType, isSus]);   //sentence 2
                //...
        }
}

```
1、 What does sentence 1 do?
2、About sentence 2:
(1) Sentence 2 means I can use  function `goodNoteHit` in LUA Script, right? 
(2) What are the meanings of the four parameters `[notes.members.indexOf(note), leData, leType, isSus]`? Could you give me an example of using this function in LUA Script?
Thanks very much!

**Comment by NS-Unfair** [comment]
"Sentence 2," calls the function goodNoteHit with parameters of:
Index of the Note, Note (0-3 being left, down, up, right), Note Type, Is Sustain Note

"Sentence 1" is an if condition, it checks for if cpuControlled is true and if the note is ignores or if the note is a hurt/bad note.

**Comment by zwl1619** [comment]
@NS-Unfair "Sentence 1" only has a `return`, return to where?

**Comment by CyndaquilDAC** [comment]
> @NS-Unfair "Sentence 1" only has a `return`, return to where?

do you seriously not know what a return is?
