### ISSUE TITLE
Sttrident Crisis Freeplay Categories

### ISSUE THREAD

**Issue by PHGaming121** [ShadowMario/FNF-PsychEngine#12721]
### What feature do you want to get added on the **base** engine?

customizable freeplay categories
(uses source, but songs are set in a txt file)

or something like the screwed engine: https://github.com/miksel1/FNF-ScrewedEngine

plz someone answer me

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by jimmyjamescool** [comment]
failed test + not Dave and bambi again

**Comment by MemeHovy** [comment]
you failed the test
