### ISSUE TITLE
i need help with this

### ISSUE THREAD

**Issue by 4ntonySKR** [ShadowMario/FNF-PsychEngine#12725]
### Describe your problem here.

hi i am trying to compile psych 0.6.3 but i get this error
I fixed most errors but this one got me stuck

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/103867370/843e02bc-0f9a-4bd2-a1bb-ee38e7286373)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nop

**Comment by MemeHovy** [comment]
deadass?

in flxanimationcontroller, just replace frames with this ```haxe
	/**
	 * The total number of frames in this image.
	 * WARNING: assumes each row in the sprite sheet is full!
	 */
	public var numFrames(get, never):Int;

	/**
	 * The total number of frames in this image.
	 * WARNING: assumes each row in the sprite sheet is full!
	 */
	@:deprecated("frames is deprecated, use numFrames")
	public var frames(get, never):Int;
```

then add this function in too ```haxe
	#if (flixel >= "5.3.0")
	@:allow(flixel.animation.FlxAnimation)
	function getFrameDuration(index:Int)
	{
		return _sprite.frames.frames[index].duration;
	}
	#end
```

**Comment by 4ntonySKR** [comment]
one left, 2 to go
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames

**Comment by 4ntonySKR** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/103867370/1ea6bf32-3805-4bac-be87-fcbe011d9bb3)
THXXX

**Comment by MemeHovy** [comment]
np
