### ISSUE TITLE
I can't get my source code to build the EXE files.

### ISSUE THREAD

**Issue by ZaneFlynt01** [ShadowMario/FNF-PsychEngine#12723]
### Describe your problem here.

I want to work on a mod and I installed the source code and all the Haxe shit I need, but when I run the .bat file to build the game, it builds everything except for the exe file and the icon. I set the versions of everything I could to the versions that were listed via the wiki documentation for the versions or, in the case of Haxe itself, it's running on version 4.3.1

I've attached the entire result I get when running the .bat file here. I did them as .png files just as it was easiest for me.
![Screenshot 2023-07-11 160517](https://github.com/ShadowMario/FNF-PsychEngine/assets/71738041/2d5d8326-54f8-4bd6-9703-1e2ed9a36f9b)
![Screenshot 2023-07-11 160458](https://github.com/ShadowMario/FNF-PsychEngine/assets/71738041/9dbfa209-878e-4d09-a3ba-89ceaa02cd7a)

The files that are compiled are:

-assets (File Folder)
-manifest (File Folder)
-mods (File Folder)
-plugins (File Folder)
-do NOT readme (Text Document)
-libvlc (DLL Application Extension)
-libvlccore (DLL Application Extension)
-lime (NDLL File)

I've tried installing the source code twice for version 0.6.3 and the source code for the experimental 0.7b

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I slightly modified the StoryMenuState.hx to change the color of the text listing the names of each song, the MainMenuState.hx file to change the title screen to have my mod name and version instead of the psych engine version, as well as I've modified some of the asset files.

**Comment by aless26pic** [comment]
use this https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by ZaneFlynt01** [comment]
> use this https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

I have everything at the specific version that the page specified.
