### ISSUE TITLE
enable autosize/alignment for lua text at width of 0

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#12722]
### What feature do you want to get added on the **base** engine?

It would be pretty cool, if lua text got autosize centered, when the text alignment is in the middle. similar to the scoretext or botplaytext or whatsoever.
Since a width of 0 has no real length, it can go infinite. yet it does have a more or less starting/ending point (depending on the alignment). Setting the alignment without a width of at least 1 will never affect it. Which can cause some issues, if you would have wanted to center it.
And I think that scoreTxt and timeTxt are pretty long, but you cannot really create a txt with a width of like 10k.
so instead, why not jsut let the size on a text with alignment.center adjust it's size automatically?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
You can actually do that with setProperty
