### ISSUE TITLE
Dialogue Lua Script link

### ISSUE THREAD

**Issue by ArsonIndira** [ShadowMario/FNF-PsychEngine#12729]
### What needs to be documented?

The Link to download the .lua file for the script to enable the usage of dialogue doesn't work anymore, it just says that the site can't be reached, using other search engines have failed and I've had my friends also try and fail to download the .lua script.

![image_2023-07-12_220946652](https://github.com/ShadowMario/FNF-PsychEngine/assets/90337224/42df27a3-941b-4814-ad23-ab560d5b31a6)

**Comment by NeOn-pixel-prog** [comment]
Top

**Comment by ODHG1** [comment]
not ShadowMario closing this issue while the link is still dead lmfao
