### ISSUE TITLE
function noteMiss is not being called

### ISSUE THREAD

**Issue by SoggyCereal123** [ShadowMario/FNF-PsychEngine#12726]
### Describe your problem here.

function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is an Instakill Note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Shockwave' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'HURTNOTE_assets'); --Change texture

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true); --Miss has no penalties
			end
		end
	end
	--debugPrint('Script started!')
end

-- Function called when you hit a note (after note hit calculations)
-- id: The note member id, you can get whatever variable you want from this note, example: "getPropertyFromGroup('notes', id, 'strumTime')"
-- noteData: 0 = Left, 1 = Down, 2 = Up, 3 = Right
-- noteType: The note type string/tag
-- isSustainNote: If it's a hold note, can be either true or false
function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'Shockwave' then
		characterPlayAnim('bf', 'attack', false)
	end
end

function noteMiss(id, noteData, noteType, isSustainNote)
	if noteType == 'ShockWave' then
		setProperty('boyfriend.stunned', true)
		runTimer('stunned', 3, 1)
		characterPlayAnim('bf', 'hurt', false);
	end
end

function onTimerCompleted(tag)
	debugPrint("Current boyfriend character: ", getProperty("boyfriend.curCharacter"));
	if tag == 'stunned' then
		setProperty('boyfriend.stunned', false);
	end
end

This is my code, Im making a custom notetype that stuns the player if it misses, Although the note hitting works, the note missing does not. I use the debugging tool and it turns out that the function is not even being registered at all

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SoggyCereal123** [comment]
Yes, I have tried changing NoteData to direction

**Comment by Lorekeeper49** [comment]
> Yes, I have tried changing NoteData to direction

First of all, parameter names don't matter with built-in function callbacks.  
Secondly, string matching is case-sensitive, in `onCreate` the note type is `Shockwave` with an uppercase S and everything else lowercase.  However, in `noteMiss` you wrote it as `ShockWave` with an uppercase W, make that W lowercase and it should work.

**Comment by frantastic24** [comment]
You made it so the note can't be missed

**Comment by SoggyCereal123** [comment]
> > Yes, I have tried changing NoteData to direction
> 
> First of all, parameter names don't matter with built-in function callbacks. Secondly, string matching is case-sensitive, in `onCreate` the note type is `Shockwave` with an uppercase S and everything else lowercase. However, in `noteMiss` you wrote it as `ShockWave` with an uppercase W, make that W lowercase and it should work.

Alright, Thank You! Great to know it's Case sensitive!

**Comment by CaptainBaldi** [comment]
setting ignoreNote to true makes misses not have penalties it literally says that
