### ISSUE TITLE
64 bit compiling error

### ISSUE THREAD

**Issue by KELOTOMU** [ShadowMario/FNF-PsychEngine#12739]
### Describe your problem here.

So I already got all the library versions right even Haxe 4.2.5 but still got this error from compiling :(

`Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths`

Do I need the **32-bit** version of Haxe instead?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by TheLeerName** [comment]
#9693
