### ISSUE TITLE
help me to fix this plis :(

### ISSUE THREAD

**Issue by AnimationZEZ** [ShadowMario/FNF-PsychEngine#12737]
### Describe your problem here.

I don't know why when I want to compile the game suddenly there is this error
( 'lime' is not recognized as an internal or external command,
operable program or batch file. )

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by 4ntonySKR** [comment]
mmm, check that you have everything correctly installed, in any case you have to reinstall
