### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by axolotl-mouka** [ShadowMario/FNF-PsychEngine#12731]
### Describe your problem here.

I want to make a secret song and it will play this song when i click the button.but when i click the button it show me:

"MusicBeatState.hx (line 126)
ShopState.hx (line 44)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference"

Here is the code

```
package;

import flixel.FlxG;
import flixel.FlxState;
import flixel.ui.FlxButton;
import flixel.FlxSprite;
import flixel.addons.display.FlxGridOverlay;
import flixel.text.FlxText;
import flixel.input.keyboard.FlxKey;
import flixel.input.mouse.FlxMouse;
import flixel.ui.FlxButton;
import openfl.display.Bitmap;
import openfl.display.BitmapData;


class ShopState extends FlxState
{
	var _btnPlay:FlxButton;
	var _btnPlay2:FlxButton;


	override public function create()
	{
		var bean:FlxSprite = new FlxSprite(600, 20).loadGraphic(Paths.image('bean'));
		bean.scale.set(0.5,0.5);
		add(bean);
		
		var bg:FlxSprite = new FlxSprite(-80).loadGraphic(Paths.image('menuBG'));
		bg.scale.set(1,1);
		bg.screenCenter();
		bg.antialiasing = ClientPrefs.globalAntialiasing;
		add(bg);

		var bg2:FlxSprite = new FlxSprite(-80).loadGraphic(Paths.image('bg_'));
		//bg2.scale.set(1,1);
		bg2.screenCenter();
		bg2.antialiasing = ClientPrefs.globalAntialiasing;
		add(bg2);
		

		function clickPlay():Void
		{
			PlayState.SONG = Song.loadFromJson("bopeebo-hard", "bopeebo");
			LoadingState.loadAndSwitchState(new PlayState());
			//FlxG.switchState(new PlayState());
		}

		function clickPlay2():Void
		{
			FlxG.switchState(new MainMenuState());
		}

		_btnPlay = new FlxButton(0, 550, "FREE", clickPlay);
		//_btnPlay.scale.set(2.5, 2.5);
		_btnPlay.screenCenter(X);
		add(_btnPlay);

		_btnPlay2 = new FlxButton(10, 0, "", clickPlay2);
		_btnPlay2.loadGraphic(Paths.image('Exit'));
		//_btnPlay2.scale.set(2, 2);
		//_btnPlay2.screenCenter(X);
		add(_btnPlay2);

		super.create();
	}

	var selectedSomethin:Bool = false;

	var _BACK:Bool = false;

	override public function update(elapsed:Float)
	{
          /*  _BACK = FlxKey.anyPressed(W);
			if (_BACK)
			{
				selectedSomethin = true;
				FlxG.sound.play(Paths.sound('cancelMenu'));
				MusicBeatState.switchState(new MainMenuState());
			}*/

			
		super.update(elapsed);
	}}
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes

**Comment by TheLeerName** [comment]
function inside other function ☠

**Comment by MemeHovy** [comment]
> function inside other function ☠

they're call local functions

**Comment by axolotl-mouka** [comment]
> function inside other function ☠

Sorry, I don't understand what that means

**Comment by BernardoGP4504** [comment]
> > function inside other function ☠
> 
> Sorry, I don't understand what that means

He's talking about the 2 functions inside create
Also, you don't need separate functions, there's a pressed callback field in a FlxButton

**Comment by axolotl-mouka** [comment]
> > > function inside other function ☠
> > 
> > 
> > Sorry, I don't understand what that means
> 
> He's talking about the 2 functions inside create
> 
> Also, you don't need separate functions, you can do a anonymous function like:
> 
> ```hx
> function()
> {
>     // run your code here
> });
> ```

Thank you!

**Comment by axolotl-mouka** [comment]
> > > function inside other function ☠
> > 
> > 
> > Sorry, I don't understand what that means
> 
> He's talking about the 2 functions inside create
> 
> Also, you don't need separate functions, you can do a anonymous function like:
> 
> ```hx
> function()
> {
>     // run your code here
> });
> ```

wait,it did't work

![photo (2)](https://github.com/ShadowMario/FNF-PsychEngine/assets/134141822/cf0e9ddb-87ba-412c-a960-ce0707dfcef9)
![photo (1)](https://github.com/ShadowMario/FNF-PsychEngine/assets/134141822/8d4f78f5-535b-4754-8570-5cd036d94a80)
