### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by 16-bit-YT** [ShadowMario/FNF-PsychEngine#12738]
### Describe your problem here.

Im trying to compile for the first time and... lets say that I need some help
![Captura de pantalla 2023-07-13 100204](https://github.com/ShadowMario/FNF-PsychEngine/assets/139539631/fb883592-5ce2-46fc-8a1d-4979ec8a4521)
![Captura de pantalla 2023-07-13 100141](https://github.com/ShadowMario/FNF-PsychEngine/assets/139539631/6c3e62f8-6e8a-438f-a30f-006b2c7ed21f)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didnt edit anything yet

**Comment by TheLeerName** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions
