### ISSUE TITLE
Change Character freezes Spirit effect

### ISSUE THREAD

**Issue by pac2005** [ShadowMario/FNF-PsychEngine#12734]
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/42727282/2875e37d-0d82-4144-9da5-a4afb78af748)
As you can see here, using the Change Character event freezes the phantom image of the first character in the "dad" slot in place for the rest of the song.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/42727282/ccbac9c1-0cdb-493c-896e-8c5dcbedd18f)
Even when the character whose phantom image was frozen comes back into play, the image stays static and doesn't move along with the newly reinstated opponent.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

All I did this time was add character changes to demonstrate this bug.

**Comment by CaptainBaldi** [comment]
465 misses goes hard

**Comment by pac2005** [comment]
it's a long song and i was focused on taking screeenshots rather than playing well
