### ISSUE TITLE
How do I make the icons say still??

### ISSUE THREAD

**Issue by Retr0wavy** [ShadowMario/FNF-PsychEngine#12749]
### Describe your problem here.

I'm trying to make it so the character icons function the exact way they do normally, except they don't move. Does anyone know how to do that??

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by Ozofearlez** [comment]
Just do a changescale in the opposite size of the regular scale i think

**Comment by Retr0wavy** [comment]
> Just do a changescale in the opposite size of the regular scale i think

No no no, I mean the healthbar movement, not the bounce
I should've been more specific lol, sorry :P

**Comment by Ozofearlez** [comment]
> > Just do a changescale in the opposite size of the regular scale i think
> 
> No no no, I mean the healthbar movement, not the bounce
> I should've been more specific lol, sorry :P

Oh lemme find that out brb

**Comment by Retr0wavy** [comment]
> > > Just do a changescale in the opposite size of the regular scale i think
> > 
> > 
> > No no no, I mean the healthbar movement, not the bounce
> > I should've been more specific lol, sorry :P
> 
> Oh lemme find that out brb

Oke! No need to hurry by the way

**Comment by Ozofearlez** [comment]
Make that a script to put in data or mods/scripts

**Comment by Ozofearlez** [comment]
> > > > > Just do a changescale in the opposite size of the regular scale i think
> > > > 
> > > > 
> > > > No no no, I mean the healthbar movement, not the bounce
> > > > I should've been more specific lol, sorry :P
> > > 
> > > Oh lemme find that out brb
> > 
> > Oke! No need to hurry by the way
> 
> This should work
> 
> function onUpdate()
>    setProperty('health', 0)
> end

Set property needs to be indented

**Comment by Retr0wavy** [comment]
> > > > > > Just do a changescale in the opposite size of the regular scale i think
> > > > > 
> > > > > 
> > > > > No no no, I mean the healthbar movement, not the bounce
> > > > > I should've been more specific lol, sorry :P
> > > > 
> > > > 
> > > > Oh lemme find that out brb
> > > 
> > > 
> > > Oke! No need to hurry by the way
> > 
> > 
> > This should work
> > function onUpdate()
> > setProperty('health', 0)
> > end
> 
> Set property needs to be indented

I think I might've worded it weirdly again, I meant something like this, with the icons bouncing and changing according to the amount of health the player and the opponent have, but not being attached to the healthbar and staying still instead
![like this](https://github.com/ShadowMario/FNF-PsychEngine/assets/94808992/8ddec0ed-f9b5-4101-9bb5-cd61cc1a9cb6)

**Comment by Retr0wavy** [comment]
> `function onUpdatePost() setProperty('iconP1.x', 880) setProperty('iconP2.x', 280) end`

Thanks a lot dude!!! I really appreciate it :D
