### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by XavierD3v** [ShadowMario/FNF-PsychEngine#12747]
### Describe your bug here.

options/BaseOptionsMenu.hx (line 262)
flixel/FlxState.hx (line 220)
flixel/FlxState.hx (line 229)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 550)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

### Command Prompt/Terminal logs (if existing)

Compiling group: haxe
cl.exe -Iinclude -IC:/Users/**INFO**/Downloads/Project Flixelion Engine Source/Build/.haxelib/discord_rpc/git/linc/ -IC:/Users/NO/Downloads/Project Flixelion Engine Source/Build/.haxelib/linc_luajit/git//linc/ -I C:/HaxeToolkit/haxe/lib/hxCodec/2,5,1/lib/vlc/include/ -I C:/HaxeToolkit/haxe/lib/hxCodec/2,5,1/lib/vlc/src/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\SadAs\Downloads\Project Flixelion Engine Source\Build\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/Users/NO/Downloads/Project Flixelion Engine Source/Build/.haxelib/hxcpp/4,3,2/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_CHECK_POINTER(haxe) -DHXCPP_STACK_LINE(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/lime/utils/AssetCache.cpp  [haxe,release]
 - src/ApplicationMain.cpp
Link: ApplicationMain.exe
   Creating library ApplicationMain.lib and object ApplicationMain.exp
source/Discord.hx:18: Discord Client starting...
source/Discord.hx:68: Discord Client initialized
source/Discord.hx:25: Discord Client started.
source/Paths.hx:370: oh no its returning null NOOOO
source/Paths.hx:370: oh no its returning null NOOOO
source/Paths.hx:370: oh no its returning null NOOOO
source/Paths.hx:370: oh no its returning null NOOOO
source/Paths.hx:370: oh no its returning null NOOOO
source/Paths.hx:370: oh no its returning null NOOOO
options/BaseOptionsMenu.hx (line 262)
flixel/FlxState.hx (line 220)
flixel/FlxState.hx (line 229)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 550)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
Crash dump saved in crash/PsychEngine_2023-07-16_07'03'56.txt

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i editted the title, menu, HUD, options

**Comment by TheLeerName** [comment]
we dont know what exactly u edit

**Comment by PogofruitKM** [comment]
remove ALL boyfriend lines in options/ folder if you intend on removing him from options

**Comment by XavierD3v** [comment]
update: i fixed it.
