### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by 16-bit-YT** [ShadowMario/FNF-PsychEngine#12740]
### Describe your problem here.

C:/Users/sergi/Desktop/FNF-PsychEngine-main/.haxelib/flixel-addons/git/flixel/addons/text/FlxTypeText.hx:8: characters 8-29 : Type not found : flixel.sound.FlxSound
C:/Users/sergi/Desktop/FNF-PsychEngine-main/.haxelib/flixel-addons/git/flixel/addons/text/FlxTypeText.hx:77: characters 26-34 : Type not found : FlxSound
source/CoolUtil.hx:19: lines 19-154 : ... Defined in this class
C:/Users/sergi/Desktop/FNF-PsychEngine-main/.haxelib/flixel-addons/git/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/DialogueBox.hx:144: characters 16-22 : flixel.addons.text.FlxTypeText has no field sounds
source/DialogueBox.hx:244: characters 16-25 : flixel.addons.text.FlxTypeText has no field resetText
source/DialogueBox.hx:245: characters 16-21 : flixel.addons.text.FlxTypeText has no field start
source/DialogueBox.hx:246: characters 16-32 : flixel.addons.text.FlxTypeText has no field completeCallback
source/DialogueBox.hx:223: characters 18-22 : flixel.addons.text.FlxTypeText has no field skip
C:/Users/sergi/Desktop/FNF-PsychEngine-main/.haxelib/flixel-addons/git/flixel/addons/transition/FlxTransitionableState.hx:81: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didnt edit anything yet

**Comment by cheblol** [comment]
It's because of the new Haxe update, try opening this file inside of the .zip file (don't worry it's safe many people tried already)
[bat.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/12051388/bat.zip)

**Comment by cheblol** [comment]
Or just go to this solved issue link and do what it says
https://github.com/ShadowMario/FNF-PsychEngine/issues/10756

**Comment by TheLeerName** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions
