### ISSUE TITLE
How to add a Red flash event?

### ISSUE THREAD

**Issue by someone0r** [ShadowMario/FNF-PsychEngine#12744]
### Describe your problem here.

idk how to add a red flash event

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by PogofruitKM** [comment]
take a look at FunkinLua for functions
you can do `cameraFlash(<camera>, 'FF0000', <duration>)` to make a <camera> flash red for <duration>
creating an event is no hassle, you can use the template

**Comment by someone0r** [comment]
thanks

**Comment by TheLeerName** [comment]
close issue
