### ISSUE TITLE
Songs sorted into mod folders in Freeplay

### ISSUE THREAD

**Issue by CobaltBar** [ShadowMario/FNF-PsychEngine#12742]
### What feature do you want to get added on the **base** engine?
My idea:
In the Freeplay **menu**, sort the songs under their respective mod, and make the mods expandable and collapsable, like folders.
e.g.
- Mod A
    - Song A
    - Song B
    - Song C
- Mod B
    - Song A
    - Song B
    - Song C
- Mod C
    - Song A
    - Song B
    - Song C

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Lorekeeper49** [comment]
I'm one-upping this one, this would make things so much more organized and easier to name, because right now, you can't have 2 different weeks in 2 different mods with the same file name, only one ends up showing

**Comment by TheLeerName** [comment]
i think its too custom for engine

**Comment by TFLTV** [comment]
Ehhh could be nice in some cases

**Comment by CobaltGames** [comment]
> i think its too custom for engine

Maybe add an option to disable it in the Project.xml or through a setting

**Comment by meekjr** [comment]
if this were added I'd like separate story modes also, for crud like B-sides.
