### ISSUE TITLE
Player 1 an Player 2

### ISSUE THREAD

**Issue by Hunter13n** [ShadowMario/FNF-PsychEngine#1274]
### What feature do you want to get added on the base engine?

For when adding characters you should put like a player 1 an player 2, player 1 for the player/bf side, an player 2 for the opponent side, in stead of making separate json files, for example: pico for opponent side, pico-player for playable side, just make it where you put them as a player an opponent on the same json file. For example: Pico as a opponet an player.

**Comment by DEV-idiotXD** [comment]
> ### What feature do you want to get added on the base engine?
> For when adding characters you should put like a player 1 an player 2, player 1 for the player/bf side, an player 2 for the opponent side, in stead of making separate json files, for example: pico for opponent side, pico-player for playable side, just make it where you put them as a player an opponent on the same json file. For example: Pico as a opponet an player.

then just use the pico player json template
