### ISSUE TITLE
TweenX and TweenY functions are "coliding" with each other?

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#12745]
### Describe your problem here.

alr so

```
doTweenX("6am", "6am", 520, 2.5, "Linear")
doTweenY("6am", "6am", 320, 2.5, "Linear")
```

the last one only triggers.  So is it that the last tween executed overwrites the tween that triggered first?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No (other than the accuracy 'ratingStuff'), just modded in the "example_mods" folder

**Comment by CaptainBaldi** [comment]
yes
use a different tag for each tween

**Comment by TFLTV** [comment]
BRUH I FORGOT TAGS WERE A THING
