### ISSUE TITLE
Camera zoom adjuster

### ISSUE THREAD

**Issue by Ozofearlez** [ShadowMario/FNF-PsychEngine#12753]
### What feature do you want to get added on the **base** engine?

So, we all know that in character editor, we can change the position of the camera, but what if there was a camera size changer, where in the editor, there would be an adjustable rectangle around the character, which would determine how much it zooms in/zooms out when the character sings.
![Untitled1339_20230717124043](https://github.com/ShadowMario/FNF-PsychEngine/assets/126235087/f2d81d7e-87a9-4bc5-be22-98c99e91cbc1)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Winning Icons and Stage Editor

**Comment by Ozofearlez** [comment]
> Is this a joke because you put "Useful feature" in the 'To test your sight, and reliability, please select the option of what should NOT be requested.' part which is not the correct answer and theres already a way to make an event doing that using lua pretty easily.

Oh crap, I mustve skimmed over that part, lemme try to fix that.

**Comment by Ozofearlez** [comment]
> > Is this a joke because you put "Useful feature" in the 'To test your sight, and reliability, please select the option of what should NOT be requested.' part which is not the correct answer and theres already a way to make an event doing that using lua pretty easily.
> 
> Oh crap, I mustve skimmed over that part, lemme try to fix that.

I feel so stupid lmao

**Comment by TFLTV** [comment]
lmao

**Comment by TFLTV** [comment]
oh wait I dont thinks thats possible in lua. I thought you meant a charting event, now I feel stupid LMAO

**Comment by TFLTV** [comment]
Though you could make code that only executes if a character you want the camera to zoom out is the opponent or BF and zooms out when its their time to sing.

**Comment by CaptainBaldi** [comment]
meh already possible with lua
