### ISSUE TITLE
Standard Library not found Haxe_std_path not working

### ISSUE THREAD

**Issue by BadWordGit** [ShadowMario/FNF-PsychEngine#12758]
### Describe your problem here.

I've been trying to fix this problem, but it never seems to work. For some reason, every time I install the engine, its always missing the Standard Library. I've already tried to add the std file and the HAXE_STD_PATH myself, nothing seems to work. Is there something else I need to do, a command I need to up in? Help would be greatly appreciated :)
(Here's the error message for more context:
'Standard library not found. Please check your `HAXE_STD_PATH` environment variable (current value: "C:\HaxeToolkit\haxe\std")')

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Cyachao** [comment]
try reinstalling whole haxe
