### ISSUE TITLE
clicking on object

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#12755]
### Describe your problem here.

How would you make an if statement checking if you clicked on a specific object (for me its `mschitbox` or `mscbox`) in lua?
I'd assume its just checking if the player is clicking and is hovering over the desired object, known as `mschitbox` in the lua script.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheLeerName** [comment]
```lua
function onUpdate(elapsed)
    if mouseOverlaps('mschitbox') and mouseClicked('left') then
        -- bob do something
    end
end
function mouseOverlaps(tag)
    addHaxeLibrary('Reflect')
    return runHaxeCode([[
        var obj = game.getLuaObject(']]..tag..[[');
        if (obj == null) obj = Reflect.getProperty(game, ']]..tag..[[');
        if (obj == null) return false;
        return obj.getScreenBounds(null, obj.cameras[0]).containsPoint(FlxG.mouse.getScreenPosition(obj.cameras[0]));
    ]])
end
```
