### ISSUE TITLE
Creating bars with Flxbars on lua

### ISSUE THREAD

**Issue by fox-64** [ShadowMario/FNF-PsychEngine#12754]
### What feature do you want to get added on the **base** engine?

Like `makeBar(x, y, weight,  height, variable, max value, min value, color, direction)`
`x` = the x position
`y` = the y position
`weight` = the weight
`height` = the height
`variable` = the variable that the bar will follow to the bar represent 
`max value` = the maximum value 
`min value` = the minimum value 
`color` = the color of the bar
`direction` = the direction (from this: https://api.haxeflixel.com/flixel/ui/FlxBarFillDirection.html )

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by TFLTV** [comment]
you can already do this fairly simple in lua.

**Comment by fox-64** [comment]
> you can already do this fairly simple in lua.

How? I tried but it didn't work

**Comment by TFLTV** [comment]
it would be simple if you knew what you were doing though direction could be a bit tricky.
it would be a lot of code (which I dont want to write out) though would be easy to understand (I think)

**Comment by TFLTV** [comment]
youd have to use a image/graphic and then use scaleObject or something else that can change the image/graphic's scale

**Comment by TFLTV** [comment]
though this is possible in lua it would be helpful a lot for saving time and for biggening coders so I think ill up this

**Comment by fox-64** [comment]
> youd have to use a image/graphic and then use scaleObject or something else that can change the image/graphic's scale

good idea

**Comment by frantastic24** [comment]
runHaxeCode

**Comment by TFLTV** [comment]
> runHaxeCode

oh yea i forgor

**Comment by CaptainBaldi** [comment]
> runHaxeCode

runHaxeCode can be used with FlxBar's but it doesn't support FlxBarFillDirection, which is kinda inconvenient for some uses

**Comment by frantastic24** [comment]
Nothing flipXY can't fix

**Comment by CaptainBaldi** [comment]
> Nothing flipXY can't fix

i suppose this is true

**Comment by fox-64** [comment]
> Barely any instances where it could be used, so i won't add it

Ok ig
