### ISSUE TITLE
I need help compiling source code

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#12752]
### Describe your problem here.

C:/HaxeToolkit/haxe/lib/flixel/5,3,1/flixel/sound/FlxSoundGroup.hx:83: characters 10-25 : Cannot access private field updateTransform

This error keeps coming and i dont know what to do about it, it happens on all flixel, i tried 5,3,0

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, except of all the extra APIStuff.hx and that

**Comment by CobaltGames** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

Also, the flixel version Psych Engine uses is 5.2.2
