### ISSUE TITLE
Stage directory field doesn't work (SOURCE)

### ISSUE THREAD

**Issue by Chidubemmo** [ShadowMario/FNF-PsychEngine#12756]
### Describe your problem here.

So I made a stage with a custom directory called week1, I added the folder with all the images. When I load it in the game for some reason Paths.hx returns null? And it's all black and every object for the stage has been replaced with the HaxeFlixel logo
This is the json
```json
{
	"directory": "week1",
	"defaultZoom": 0.9,
	"isPixelStage": false,

	"boyfriend": [580.6, 521],
	"girlfriend": [400, 130],
	"opponent": [100, 100],
	"hide_girlfriend": false,

	"camera_boyfriend": [-200, 0],
	"camera_opponent": [0, 0],
	"camera_girlfriend": [0, 0],
	"camera_speed": 1
}
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Opening cutscene

**Comment by TFLTV** [comment]
please provide the full directory for it

**Comment by Chidubemmo** [comment]
Extra info
so i used trace(path) and this is what I found.
```
source/Paths.hx:360: assets/images/bg.png
source/Paths.hx:370: oh no its returning null NOOOO
source/Paths.hx:360: assets/images/lights.png
source/Paths.hx:370: oh no its returning null NOOOO
source/Paths.hx:360: assets/images/columns.png
source/Paths.hx:370: oh no its returning null NOOOO
source/Paths.hx:360: assets/images/MirrorWorld.png
```
instead of searching in the week1 folder it's using the assets one? I have no idea why

**Comment by BernardoGP4504** [comment]
that `week1/` folder has to be inside assets but without being inside `preload/` or `shared/`
Also, the images go in the folder `images/` inside week1

**Comment by BernardoGP4504** [comment]
If that doesn't work, try changing the path on the stage sprite itself on the source code
And make sure the folder is defined in `project.xml`

**Comment by Chidubemmo** [comment]
I got help we had to modify [BG Sprite.hx](https://pastebin.com/P4w8uPuz) and PlayState by adding a new argument
```hx
var mirrors:BGSprite = new BGSprite('bg', 'week1', 960, 417.3, 0.9, 0.9);
```
