### ISSUE TITLE
Note Color Switch toggle

### ISSUE THREAD

**Issue by Flezard** [ShadowMario/FNF-PsychEngine#12762]
### What feature do you want to get added on the **base** engine?

Basically, I think that having an option in note scripts to tell if the note should be affected by the note color change or not when it has a special noteskin would be a really good idea, because if the notes are still based on the regular colors, they should change color like the regular notes. If they're not based on the regular colors (for example the orange and blue notes in sansational and burning in hell), their color shouldn't be changed, because then you could have in sansational 8 differently colored bones notes, some you need to hit and some you need to not hit

Also some notes can in fact be changed color without ruining the gameplay, but it sometimes looks better with the OG as it was planned to (for example Markov notes or Attack notes (from the just now released D-Side natsuki mod)
I had that idea before but only wrote this after playing that Natsuki mod and seeing that the notes would have looked better in orange like how they were supposed to be, and would have stood out more in between the regular notes.

Maybe adding one line of code in psych lua for that would be really helpful

(also im really sorry for having 2 posts here in the span of one day)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Flezard** [comment]
How to use it if I may ask? I didn't found info on it in the wiki

**Comment by thegreatskep** [comment]
> How to use it if I may ask? I didn't found info on it in the wiki
idk exactly, this is what worked for me tho:
	setPropertyFromGroup('unspawnNotes', i, 'rgbShader.enabled', false)

**Comment by thegreatskep** [comment]
> How to use it if I may ask? I didn't found info on it in the wiki

idk exactly, this is what worked for me tho:
	setPropertyFromGroup('unspawnNotes', i, 'rgbShader.enabled', false)
