### ISSUE TITLE
How can i put dialouge after a song

### ISSUE THREAD

**Issue by cheemynugget2** [ShadowMario/FNF-PsychEngine#1276]
### Describe your problem here.

so my script has play cutscene, dialogue, and then song

but i also want dialogue at the end.

pls dont ban me if this is a duplicate

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

so far ive added characters and changed stage lua codes and a bit more but not much

**Comment by NotEpik** [comment]
local allowCountdown = false
function onEndSong()
	if not allowCountdown and isStoryMode and not seenCutscene then
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then
		startDialogue('dialogue', 'breakfast');
	end
end

**Comment by NotEpik** [comment]
```
local allowCountdown = false
function onStartCountdown()
	if not allowCountdown and isStoryMode and not seenCutscene then
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then
		startDialogue('dialogue', 'breakfast');
	end
end
```

**Comment by NotEpik** [comment]
```
local allowCountdown = false
function onEndSong()
	if not allowCountdown and isStoryMode and not seenCutscene then
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then
		startDialogue('dialogue', 'breakfast');
	end
end
```

**Comment by NotEpik** [comment]
for both start song dialogue and end song dialogue here

```
local allowCountdown = false
local startedFirstDialogue = false
local startedEndDialogue = false
function onStartCountdown()
	if not allowCountdown and isStoryMode and not startedFirstDialogue then
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		startedFirstDialogue = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onEndSong()
	if not allowCountdown and isStoryMode and not startedEndDialogue then
		setProperty('inCutscene', true);
		runTimer('startDialogueEnd', 0.8);
		startedEndDialogue = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then
		startDialogue('dialogue', 'breakfast');
	elseif tag == 'startDialogueEnd' then
		startDialogue('dialogueEnd', 'breakfast');
	end
end
```

change 'dialogueEnd' to whatever you named the end song dialogue file

**Comment by cheemynugget2** [comment]
ill try it

**Comment by cheemynugget2** [comment]
> for both start song dialogue and end song dialogue here
> 
> ```
> local allowCountdown = false
> local startedFirstDialogue = false
> local startedEndDialogue = false
> function onStartCountdown()
> 	if not allowCountdown and isStoryMode and not startedFirstDialogue then
> 		setProperty('inCutscene', true);
> 		runTimer('startDialogue', 0.8);
> 		startedFirstDialogue = true;
> 		return Function_Stop;
> 	end
> 	return Function_Continue;
> end
> 
> function onEndSong()
> 	if not allowCountdown and isStoryMode and not startedEndDialogue then
> 		setProperty('inCutscene', true);
> 		runTimer('startDialogueEnd', 0.8);
> 		startedEndDialogue = true;
> 		return Function_Stop;
> 	end
> 	return Function_Continue;
> end
> 
> function onTimerCompleted(tag, loops, loopsLeft)
> 	if tag == 'startDialogue' then
> 		startDialogue('dialogue', 'breakfast');
> 	elseif tag == 'startDialogueEnd' then
> 		startDialogue('dialogueEnd', 'breakfast');
> 	end
> end
> ```
> 
> change 'dialogueEnd' to whatever you named the end song dialogue file

In the code could you also include video cutscene like at the start of the song im not good at lua

like cutscene dialogu, song and dialogue again

**Comment by NotEpik** [comment]
> > for both start song dialogue and end song dialogue here
> > ```
> > local allowCountdown = false
> > local startedFirstDialogue = false
> > local startedEndDialogue = false
> > function onStartCountdown()
> > 	if not allowCountdown and isStoryMode and not startedFirstDialogue then
> > 		setProperty('inCutscene', true);
> > 		runTimer('startDialogue', 0.8);
> > 		startedFirstDialogue = true;
> > 		return Function_Stop;
> > 	end
> > 	return Function_Continue;
> > end
> > 
> > function onEndSong()
> > 	if not allowCountdown and isStoryMode and not startedEndDialogue then
> > 		setProperty('inCutscene', true);
> > 		runTimer('startDialogueEnd', 0.8);
> > 		startedEndDialogue = true;
> > 		return Function_Stop;
> > 	end
> > 	return Function_Continue;
> > end
> > 
> > function onTimerCompleted(tag, loops, loopsLeft)
> > 	if tag == 'startDialogue' then
> > 		startDialogue('dialogue', 'breakfast');
> > 	elseif tag == 'startDialogueEnd' then
> > 		startDialogue('dialogueEnd', 'breakfast');
> > 	end
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > change 'dialogueEnd' to whatever you named the end song dialogue file
> 
> In the code could you also include video cutscene like at the start of the song im not good at lua
> 
> like cutscene dialogu, song and dialogue again

I know a lot about lua but idk how to make cutscene start with dialogue

**Comment by NotEpik** [comment]
I will try figure out the code

**Comment by NotEpik** [comment]
I will try to figure out the code

**Comment by ShadowMario** [comment]
Use the dialogue script from Lua Script API, but:

1. Remove `not seenCutscene`
2. Rename onStartCountdown to onEndSong
