### ISSUE TITLE
idk why when i compile the source code it just stops at here

### ISSUE THREAD

**Issue by Ericgould54** [ShadowMario/FNF-PsychEngine#12761]
idk why when i compile the source code it just stops at here
C:\Users\samma\Downloads\FNF-PsychEngine-0.5.2h\FNF-PsychEngine-0.5.2h>lime test windows
source/Alphabet.hx:200: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:143: characters 13-21 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/Main.hx:78: characters 61-65 : Float should be Int
source/Main.hx:78: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:78: characters 61-65 : ... For function argument 'child'
source/PlayState.hx:84: characters 40-48 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:122: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:200: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:242: characters 28-36 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:27: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:84: characters 68-76 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:1370: characters 18-26 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:1404: characters 18-26 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:64: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:339: characters 19-27 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:341: characters 19-27 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:498: characters 22-30 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1787: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1789: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1792: characters 27-35 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:1275: characters 16-24 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:39: characters 13-21 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:109: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:111: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/TitleState.hx:653: characters 15-23 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
Psych 0.5.2h is not supported anymore

**Comment by Ericgould54** [comment]
in the newer version i get this
source/PlayState.hx:1621: characters 13-23 : Type not found : MP4Handler
source/FunkinLua.hx:2221: lines 2221-2224 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2221: lines 2221-2224 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object'
source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'Object'
source/PlayState.hx:583: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:583: characters 25-35 : ... For function argument 'Object'
source/PlayState.hx:2434: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2434: characters 23-29 : ... For function argument 'Object'
source/PlayState.hx:2435: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2435: characters 23-83 : ... For function argument 'Object'
source/PlayState.hx:1827: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1827: characters 25-37 : ... For function argument 'Object'
source/PlayState.hx:1874: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1874: characters 25-34 : ... For function argument 'Object'
source/PlayState.hx:1945: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1945: characters 25-36 : ... For function argument 'Object'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1359: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1359: characters 24-30 : ... For function argument 'Object'
source/editors/ChartingState.hx:2193: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/haxelib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
source/TitleState.hx:723: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:725: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:729: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound

**Comment by Ericgould54** [comment]
> Psych 0.5.2h is not supported anymore

in the newer version i get this
source/PlayState.hx:1621: characters 13-23 : Type not found : MP4Handler
source/FunkinLua.hx:2221: lines 2221-2224 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2221: lines 2221-2224 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object'
source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'Object'
source/PlayState.hx:583: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:583: characters 25-35 : ... For function argument 'Object'
source/PlayState.hx:2434: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2434: characters 23-29 : ... For function argument 'Object'
source/PlayState.hx:2435: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2435: characters 23-83 : ... For function argument 'Object'
source/PlayState.hx:1827: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1827: characters 25-37 : ... For function argument 'Object'
source/PlayState.hx:1874: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1874: characters 25-34 : ... For function argument 'Object'
source/PlayState.hx:1945: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1945: characters 25-36 : ... For function argument 'Object'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1359: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1359: characters 24-30 : ... For function argument 'Object'
source/editors/ChartingState.hx:2193: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/haxelib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
source/TitleState.hx:723: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:725: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:729: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound
