### ISSUE TITLE
Source Code compiling 

### ISSUE THREAD

**Issue by mikoprimeb** [ShadowMario/FNF-PsychEngine#12765]
### Describe your problem here.

I had a error while compiling and after finding a solution i got this error: 

source/PlayState.hx:75: characters 33-53 : Type not found : hxcodec.VideoHandler
source/FunkinLua.hx:479: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:497: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:503: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:553: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:559: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:599: lines 599-603 : Int should be Bool
source/FunkinLua.hx:599: lines 599-603 : ... For function argument 'f'
source/PlayState.hx:1575: characters 13-23 : Type not found : MP4Handler

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by mikoprimeb** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

I tried this, some of things doesn't want to set (flixel-ui ,flixel-addons, hscript, flixel-tools) rest of them works.
![obraz_2023-07-20_101727338](https://github.com/ShadowMario/FNF-PsychEngine/assets/95505478/1d76ca49-6b0d-4612-b9c1-d5245409d647)
![obraz_2023-07-20_101743051](https://github.com/ShadowMario/FNF-PsychEngine/assets/95505478/d3f2dcc1-1eb5-4796-b130-eddec2e81613)

If someone doesn't understand so i mean that when im typing something like haxelib set flixel-ui (for example) nothing happens.

**Comment by MemeHovy** [comment]
you can install them via their respective haxelib pages and commands
