### ISSUE TITLE
The color in Cinematic Bars Event are broken.

### ISSUE THREAD

**Issue by JustMe1352** [ShadowMario/FNF-PsychEngine#12766]
### Describe your problem here.

Hello. I was working on a mod and I had to use the Cinematic Bars Event in a song. When I tested it out it came out white and 0.5 alpha. I check the code on the event and it says that the color is black and there is nothing that changes the alpha.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/130803298/d8cda4c1-81db-4084-9294-dc8dc4ff13d8)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I tried to change it with a picture of a black asset, but didn't work.

**Comment by MemeHovy** [comment]
use hxcpp 4.2.1 or update to the latest git version

**Comment by JustMe1352** [comment]
using hxcpp 4.2.1 fixed it. Thanks

**Comment by MemeHovy** [comment]
np
