### ISSUE TITLE
Playbackrate more than 1 won't finish the song (experimental branch)

### ISSUE THREAD

**Issue by RandomUserOnInternet** [ShadowMario/FNF-PsychEngine#12768]
### Describe your bug here.

When I played any song that Playbackrate more than 1 (lower than 1 won't happen) It won't end the song. the result like this in the picture (Psych Engine 0.7b latest git)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/105424534/104e8048-726e-44a0-a479-7a38e1e2340c)

### Command Prompt/Terminal logs (if existing)

```bash
-
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MemeHovy** [comment]
hmm, I'mma see if I can reproduce the issue
