### ISSUE TITLE
Custom Noteskin Dissapearing [EXPERIMENTAL, 0.7b]

### ISSUE THREAD

**Issue by Flezard** [ShadowMario/FNF-PsychEngine#12760]
### Describe your bug here.

Before I start, know that the Purple Coin Note is literally a "Blammed Note" reskin that the song lua file maked that it adds 1 to a variable named PurpleCoins when note is hit. Nothing else changed at all, including the spritesheet name and path, and the splashes spritesheet name and path, and even the notetype name is still "Blammed Note"

When a Purple Coin note is on the chart, the first one appears normal, as it should (blue because i changed note colors).
![image_2023-07-19_132729265](https://github.com/ShadowMario/FNF-PsychEngine/assets/85451773/8df7d9aa-3eb6-4eef-a5be-8099b7140c21)

But as soon as a second one appear, it doesn't have the skin anymore. It still behaves like it should, but it looks like a normal note.
![image_2023-07-19_132755564](https://github.com/ShadowMario/FNF-PsychEngine/assets/85451773/d477faf7-f845-457e-9ccf-85952f8058c0)
I checked the script and it seems to be working fine, but I still put it here just in case (i changed the '.lua' to '.txt' since github doesnt allow the lua filetype here for some reason
[Blammed Note.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/12094463/Blammed.Note.txt)
I tested other songs and it does the same thing
I also tested other notetypes with skins (for example one with notes completely green) and it also does the same thing

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Not a bug
`noteSplashTexture` should be `noteSplashData.texture`

**Comment by Flezard** [comment]
It works, thank you so much!
