### ISSUE TITLE
Splash note variables

### ISSUE THREAD

**Issue by JVgradiz** [ShadowMario/FNF-PsychEngine#12763]
### What feature do you want to get added on the **base** engine?

Three variables

noteSplashAlpha
noteSplashOffset ( X and Y )

so you can change the noteSplash alpha and offset like notes in lua using
setPropertyFromGroup('unspawnNotes', i, 'SplashOffset.x',  [number] );
setPropertyFromGroup('unspawnNotes', i, 'SplashOffset.y',  [number] );
setPropertyFromGroup('unspawnNotes', i, 'noteSplashAlpha', 0.8);

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MemeHovy** [comment]
you could literally do just `for i = 0, getProperty('grpNoteSplashes.length')-1 do`
