### ISSUE TITLE
The button becomes a haxe logo

### ISSUE THREAD

**Issue by lez26** [ShadowMario/FNF-PsychEngine#12777]
### Describe your problem here.

The notation and location match the other images, and the file name is specified correctly, but for some reason Path.hx returns null.
I added a gallery button to the main menu. At that time, only that button will be a haxe logo. I tried various methods but it didn't work. I wrote the code to add a button to Mainmenustate like this.

		var offset:Float = 108 - (Math.max(optionShit.length, 5) - 5) * 80;
			var menuItem:FlxSprite = new FlxSprite(1200,100);
			menuItem.scale.x = scale;
			menuItem.scale.y = scale;
			menuItem.frames = Paths.getSparrowAtlas('mainmenu/menu_'+ optionShit[4]);
			menuItem.animation.addByPrefix('idle', optionShit[4] + " basic", 30);
			menuItem.animation.addByPrefix('selected', optionShit[4] + " white", 30);
			menuItem.animation.play('idle');
			menuItem.ID = 4;
			menuItem.setGraphicSize(Std.int(menuItem.width * 0.6));
			menuItems.add(menuItem);
			var scr:Float = (optionShit.length - 5) * 0.135;
			if(optionShit.length < 6) scr = 4;
			menuItem.scrollFactor.set(4, scr);
			menuItem.antialiasing = ClientPrefs.globalAntialiasing;
			menuItem.updateHitbox();
			trace('mainmenu/menu_'+ optionShit[4]);

I wrote "gallery" in option shit.
I think there is no mistake in the xml file.
![スクリーンショット 2023-07-21 211302](https://github.com/ShadowMario/FNF-PsychEngine/assets/119659879/75d06e5a-1c22-4a39-868a-a2724e4ac61f)

![スクリーンショット 2023-07-21 205040](https://github.com/ShadowMario/FNF-PsychEngine/assets/119659879/86e5281a-b9fe-4cd3-9ee0-af58373f107a)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
you’re supposed to put menu_gallery

**Comment by lez26** [comment]
It doesn't work even if the file name matches
"menu_gallery.png"

**Comment by MemeHovy** [comment]
> It doesn't work even if the file name matches "menu_gallery.png"

it has to match in the xml too

**Comment by lez26** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/119659879/2c6d5f76-fb7e-4623-85c2-88cac250ca6b)
Even this doesn't work

**Comment by MemeHovy** [comment]
also dude, the game adds buttons automatically

**Comment by MemeHovy** [comment]
all you had to do was add the gallery button in optionShit

**Comment by lez26** [comment]
But just adding "gallery" to the option shit didn't add the button.

**Comment by MemeHovy** [comment]
you made sure you added the images and such right?

**Comment by lez26** [comment]
In the main menu state?

**Comment by MemeHovy** [comment]
no, in the files

**Comment by lez26** [comment]
Yes, I have confirmed that I have added the image.

**Comment by MemeHovy** [comment]
well, you gotta make sure it's in the mainmenu folder, alongside the other images

**Comment by lez26** [comment]
it is there

**Comment by MemeHovy** [comment]
> it is there

alright, and when you putted in optionShit, you put it in the array yes? if so, show me the code

**Comment by lez26** [comment]
var optionShit:Array<String> = [
		'story_mode',
		'freeplay',
		'credits',
		'options',
		'gallery'
	];

**Comment by lez26** [comment]
It's been this way for a long time

**Comment by MemeHovy** [comment]
well, have you tried it without the custom code you implemented? if so, I'm honestly out of ideas

**Comment by lez26** [comment]
Yes, I commented it out and tried it. but it didn't work...

**Comment by Prem1umDev** [comment]
I do not know if I am too late, but have you put it in FNF-PsychEngine-Main\assets\preload\images\mainmenu

Normal assets folder in export is not detected by the Engine.
