### ISSUE TITLE
Process creation failure : cl.exe

### ISSUE THREAD

**Issue by altdude22** [ShadowMario/FNF-PsychEngine#12779]
im tryna compile psych engine but every time i try to compile it it comes up with an error that says: "Process creation failure : cl.exe"

plz help me i've been stuck on this problem for a month now

```bash
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

Compiling group: haxe
cl.exe -Iinclude -IC:/haxelib/discord_rpc/git/linc/ -IC:/haxelib/linc_luajit/git//linc/ -I C:/haxelib/hxCodec/2,5,1/lib/vlc/include/ -I C:/haxelib/hxCodec/2,5,1/lib/vlc/src/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\Zeeyaan Ali Noor\Downloads\FNF-PsychEngine-0.6.3\FNF-PsychEngine-0.6.3\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/haxelib/hxcpp/4,3,2/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_CHECK_POINTER(haxe) -DHXCPP_STACK_LINE(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/__ASSET__flixel_flixel_ui_img_hilight_png.cpp
 - src/lime/utils/_Int8Array/Int8Array_Impl_.cpp
 - src/flixel/addons/effects/chainable/FlxWaveDirection.cpp
 - src/flixel/system/debug/watch/Watch.cpp
 - src/lime/graphics/opengl/ext/OES_texture_half_float_linear.cpp
 - src/openfl/display/DisplayObjectRenderer.cpp  [haxe,release]
 - src/lime/utils/_Assets/LibrarySymbol.cpp  [haxe,release]
 - src/Prompt.cpp
 - src/lime/app/_Event_lime_ui_GamepadButton_Void.cpp  [haxe,release]
 - src/lime/system/JNIMethod.cpp  [haxe,release]
 - src/openfl/display/GraphicsShaderFill.cpp  [haxe,release]
 - src/flixel/input/gamepad/id/OUYAID.cpp
 - src/openfl/display3D/_internal/_AGALConverter/SourceRegister.cpp  [haxe,release]
 - src/lime/media/AudioManager.cpp  [haxe,release]
 - src/lime/_internal/format/PNG.cpp  [haxe,release]
 - src/flixel/addons/ui/AnchorPoint.cpp
 - src/flixel/addons/ui/interfaces/IFlxUIButton.cpp
 - src/haxe/ds/_List/ListNode.cpp
 - src/flixel/input/gamepad/mappings/FlxGamepadMapping.cpp
 - src/openfl/net/NetStream.cpp  [haxe,release]
 - src/lime/utils/Log.cpp  [haxe,release]
 - src/flixel/util/_FlxSignal/FlxTypedSignal_Impl_.cpp
 - src/DialogueCharacter.cpp
 - src/lime/app/_Event_Float_Float_lime_ui_MouseButton_Void.cpp  [haxe,release]
 - src/flixel/system/frontEnds/LogFrontEnd.cpp
 - src/openfl/display/_internal/_DrawCommandReader/LineGradientStyleView_Impl_.cpp
 - src/lime/app/Promise_String.cpp
 - src/haxe/io/Path.cpp
 - src/lime/app/IModule.cpp
 - src/sys/io/_Process/Stdin.cpp
 - src/lime/net/_HTTPRequest_lime_utils_Bytes.cpp  [haxe,release]
 - src/lime/graphics/opengl/ext/ANGLE_framebuffer_blit.cpp
 - src/flixel/system/debug/GraphicArrowRight.cpp
 - src/flixel/input/gamepad/mappings/Manufacturer.cpp
 - src/flixel/input/IFlxInput.cpp
 - src/openfl/display/SimpleButton.cpp  [haxe,release]
 - src/flixel/text/FlxText.cpp
 - src/lime/_internal/format/JPEG.cpp  [haxe,release]
 - src/flixel/util/FlxBitmapDataUtil.cpp
 - src/FlxUIDropDownMenuCustom.cpp
 - src/lime/graphics/opengl/ext/NV_texture_compression_s3tc_update.cpp
 - src/CutsceneHandler.cpp
 - src/options/VisualsUISubState.cpp
 - src/openfl/display/_internal/PerlinNoise.cpp  [haxe,release]
 - src/lime/graphics/opengl/ext/OES_depth24.cpp
 - src/flixel/util/FlxPool_flixel_math_FlxRect.cpp
 - src/flixel/system/FlxQuadTree.cpp
 - src/openfl/display/_internal/_DrawCommandReader/BeginShaderFillView_Impl_.cpp
 - src/lime/media/openal/_ALBuffer/ALBuffer_Impl_.cpp
 - src/flixel/math/FlxRandom.cpp
 - src/openfl/display/GraphicsStroke.cpp  [haxe,release]
 - src/flixel/ui/FlxBarFillDirection.cpp
 - src/openfl/display/OpenGLRenderer.cpp  [haxe,release]
 - src/__ASSET__flixel_flixel_ui_xml_default_loading_screen_xml.cpp
 - src/openfl/display/GraphicsBitmapFill.cpp  [haxe,release]
 - src/lime/graphics/opengl/ext/EXT_occlusion_query_boolean.cpp
 - src/haxe/zip/Huffman.cpp
 - src/flixel/util/_FlxSignal/FlxSignalHandler.cpp
 - src/openfl/display/_internal/Context3DBuffer.cpp
 - src/flixel/util/FlxPool_flixel_math_FlxPoint.cpp
 - src/haxe/io/Encoding.cpp
 - src/flixel/graphics/frames/FlxFrameCollectionType.cpp
 - src/openfl/display/_internal/_DrawCommandReader/DrawRoundRectView_Impl_.cpp
 - src/openfl/display/Tile.cpp  [haxe,release]
 - src/lime/system/CFFI.cpp  [haxe,release]
 - src/lime/graphics/opengl/ext/AMD_performance_monitor.cpp
 - src/flixel/util/_FlxBitmapDataPool/FlxBitmapDataPoolNode.cpp
 - src/flixel/system/frontEnds/BitmapFrontEnd.cpp
Process creation failure : cl.exe
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I did not edit anything

**Comment by MemeHovy** [comment]
https://stackoverflow.com/questions/31953769/visual-studio-2015-doesnt-have-cl-exe

**Comment by MemeHovy** [comment]
make sure you're using visual studio 2019/2022

**Comment by altdude22** [comment]
now it just says "Error" when i try compile it

**Comment by altdude22** [comment]
ah nvm it still says Process creation failure : cl.exe

**Comment by MemeHovy** [comment]
https://github.com/FunkinCrew/Funkin#build-instructions

**Comment by MemeHovy** [comment]
but instead of haxe 4.1.5, use 4.2.5, and don't install polymod

**Comment by altdude22** [comment]
now it says
source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
C:/haxelib/flixel/5,3,1/flixel/animation/FlxAnimation.hx:231: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
C:/haxelib/flixel-addons/git/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'Object'
source/FunkinLua.hx:2196: lines 2196-2199 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2196: lines 2196-2199 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object'
source/PlayState.hx:584: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:584: characters 25-35 : ... For function argument 'Object'
source/PlayState.hx:2388: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2388: characters 23-29 : ... For function argument 'Object'
source/PlayState.hx:2389: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2389: characters 23-83 : ... For function argument 'Object'
source/PlayState.hx:1781: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1781: characters 25-37 : ... For function argument 'Object'
source/PlayState.hx:1828: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1828: characters 25-34 : ... For function argument 'Object'
source/PlayState.hx:1899: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1899: characters 25-36 : ... For function argument 'Object'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1359: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1359: characters 24-30 : ... For function argument 'Object'
source/editors/ChartingState.hx:2196: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/haxelib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
source/TitleState.hx:711: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:713: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:717: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound

**Comment by MemeHovy** [comment]
> now it says source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup C:/haxelib/flixel/5,3,1/flixel/animation/FlxAnimation.hx:231: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration C:/haxelib/flixel-addons/git/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'Object' source/FunkinLua.hx:2196: lines 2196-2199 : flixel.sound.FlxSound should be flixel.system.FlxSound source/FunkinLua.hx:2196: lines 2196-2199 : ... For function argument 'value' source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'Object' source/PlayState.hx:584: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound source/PlayState.hx:584: characters 25-35 : ... For function argument 'Object' source/PlayState.hx:2388: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound source/PlayState.hx:2388: characters 23-29 : ... For function argument 'Object' source/PlayState.hx:2389: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound source/PlayState.hx:2389: characters 23-83 : ... For function argument 'Object' source/PlayState.hx:1781: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound source/PlayState.hx:1781: characters 25-37 : ... For function argument 'Object' source/PlayState.hx:1828: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound source/PlayState.hx:1828: characters 25-34 : ... For function argument 'Object' source/PlayState.hx:1899: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound source/PlayState.hx:1899: characters 25-36 : ... For function argument 'Object' source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound' source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound' source/editors/ChartingState.hx:1359: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound source/editors/ChartingState.hx:1359: characters 24-30 : ... For function argument 'Object' source/editors/ChartingState.hx:2196: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound C:/haxelib/flixel/5,3,1/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames source/TitleState.hx:711: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound source/TitleState.hx:713: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound source/TitleState.hx:717: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound

use flixel 4.11.0 and flixel-addons 2.11.0

**Comment by altdude22** [comment]
now it comes up with 
source/PlayState.hx:75: characters 33-53 : Type not found : hxcodec.VideoHandler
source/PlayState.hx:1575: characters 13-23 : Type not found : MP4Handler

**Comment by MemeHovy** [comment]
> now it comes up with
> source/PlayState.hx:75: characters 33-53 : Type not found : hxcodec.VideoHandler
> source/PlayState.hx:1575: characters 13-23 : Type not found : MP4Handler

which version of hxCodec are you using?

**Comment by altdude22** [comment]
i think 2.5.1

**Comment by MemeHovy** [comment]
update your hxCodec to 2.6.0
