### ISSUE TITLE
Error about compiling

### ISSUE THREAD

**Issue by Ve3h** [ShadowMario/FNF-PsychEngine#12770]
### Describe your bug here.

alrig, so i have download all the things that psych engine needs to build, the haxe, the libarys, etc
but when i go try this error that i put right down is happening
and i dont know how to fix, any help will be awesome
thx.

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\us\OneDrive\Documentos\FNF-PsychEngine-main>haxelib run lime build windows
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
Error: Could not find haxelib "hxCodec", does it need to be installed?
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i edited the play state, i have added/replaced
 
 
 ''#if VIDEOS_ALLOWED  #if (hxCodec >= "3.0.0") import hxcodec.flixel.FlxVideo as VideoHandler; #elseif (hxCodec >= "2.6.1") import hxcodec.VideoHandler as VideoHandler; #elseif (hxCodec == "2.6.0") import VideoHandler as VideoHandler; #else import vlc.VideoHandler; #end #end'' 

 and 
 
 
 ''public function startVideo(name:String) 	{ 		#if VIDEOS_ALLOWED 		inCutscene = true;  		var filepath:String = Paths.video(name); 		#if sys 		if(!FileSystem.exists(filepath)) 		#else 		if(!OpenFlAssets.exists(filepath)) 		#end 		{ 			FlxG.log.warn('Couldnt find video file: ' + name); 			startAndEnd(); 			return; 		}  		var video:VideoHandler = new VideoHandler(); 			#if (hxCodec >= "3.0.0") 			// Recent versions 			video.play(filepath); 			video.onEndReached.add(function() 			{ 				video.dispose(); 				startAndEnd(); 				return; 			}, true); 			#else 			// Older versions 			video.playVideo(filepath); 			video.finishCallback = function() 			{ 				startAndEnd(); 				return; 			} 			#end 		#else 		FlxG.log.warn('Platform not supported!'); 		startAndEnd(); 		return; 		#end 	}'' 

just thatlol

**Comment by MemeHovy** [comment]
you didn’t install hxCodec

**Comment by NexIsDumb** [comment]
Okay no, I know why it happens if you have **SUCCESSFULLY** downloaded all psych's libraries as the readme says

Basically hxCodec has a shitty thing which makes it bug
To make it work u have to install it normally (so without using hmm.json) in your main folder, basically how you would download normally an haxe lib using the command prompt on the desktop: it must **BE** the same version as the one install using hmm.json

Hopefully they're gonna fix this bug

**Comment by Ve3h** [comment]
> Okay no, I know why it happens if you have **SUCCESSFULLY** downloaded all psych's libraries as the readme says
> 
> Basically hxCodec has a shitty thing which makes it bug To make it work u have to install it normally (so without using hmm.json) in your main folder, basically how you would download normally an haxe lib using the command prompt on the desktop: it must **BE** the same version as the one install using hmm.json And then ofc u have to install the same hxCodec with the same version using hmm.json, so as the readme says
> 
> Hopefully they're gonna fix this bug

IT WORKED!!! Thank ya so much now im compiling it!1

**Comment by NexIsDumb** [comment]
> > Okay no, I know why it happens if you have **SUCCESSFULLY** downloaded all psych's libraries as the readme says
> > Basically hxCodec has a shitty thing which makes it bug To make it work u have to install it normally (so without using hmm.json) in your main folder, basically how you would download normally an haxe lib using the command prompt on the desktop: it must **BE** the same version as the one install using hmm.json And then ofc u have to install the same hxCodec with the same version using hmm.json, so as the readme says
> > Hopefully they're gonna fix this bug
> 
> IT WORKED!!! Thank ya so much now im compiling it!1

nppp

**Comment by RonRazar** [comment]
source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
i get this when do lime test windows how do i fix this im dumb

**Comment by MemeHovy** [comment]
> source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua i get this when do lime test windows how do i fix this im dumb

`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit master`

**Comment by RonRazar** [comment]
i used haxelib git linc_luajit https://github.com/superpowers04/linc_luajit master and it showed me this what do i do now?
 Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths

**Comment by MemeHovy** [comment]
> i used haxelib git linc_luajit https://github.com/superpowers04/linc_luajit master and it showed me this what do i do now? Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths

install visual studio

**Comment by RonRazar** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/116938209/bdc0eb55-1827-46d3-8971-9e6738f4af65)

I did it already

**Comment by MemeHovy** [comment]
that's visual studio code bro, not visual studio

**Comment by RonRazar** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/116938209/3e474e34-8af5-4724-ad92-a71e5b18add5)

Alr what do I do now?

**Comment by MemeHovy** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/ba4a2904-8df0-4444-82d6-db1a7b6abb69)

**Comment by RonRazar** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/116938209/784c59e8-def2-4857-95a7-1d207decd0d2)![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/116938209/d563a529-419d-4f1a-a0f1-903e1b70fc9d)

What do I do about this how do I set it up?

**Comment by MemeHovy** [comment]
MSVC v142 - VS 2019 C++ x64/x86 build tools has to be latest

**Comment by RonRazar** [comment]
I'm sorry but what do you mean by Latest how will I know its newer?

**Comment by RonRazar** [comment]
Hey I did it and it work I compiled it but for some reason I can't add stuff like images, songs and json like how I can't see my character in the character editor

**Comment by RonRazar** [comment]
Idk how to work the mod templete idk why I can't add characters or have json being shown in the compiled build

**Comment by NexIsDumb** [comment]
> Idk how to work the mod templete idk why I can't add characters or have json being shown in the compiled build

please make a new issue for that
this issue was originally just meant to be for the hxCodec compiling problem
This just not goes to you but to anyone else

**Comment by MemeHovy** [comment]
> > Idk how to work the mod templete idk why I can't add characters or have json being shown in the compiled build
> 
> please make a new issue for that this issue was originally just meant to be for the hxCodec compiling problem This just not goes to you but to anyone else too

yea and I’m getting tired of discussing this on a closed issue

**Comment by cotne1233** [comment]
> Okay no, I know why it happens if you have **SUCCESSFULLY** downloaded all psych's libraries as the readme says
> 
> Basically hxCodec 3.0.2 (and older versions too) has a shitty thing which makes it bug To make it work you have to install it normally (so without using hmm) in your main folder, basically how you would download normally an haxe lib using the command prompt on the desktop: it must **BE** the same version as the one installed using the hmm method And then ofc you have to install the same hxCodec with the same version using hmm if you didn't already, so as the readme says
> 
> This bug got fixed from hxCodec version 3.0.3

it still doesn't work for me

**Comment by NexIsDumb** [comment]
> > Okay no, I know why it happens if you have **SUCCESSFULLY** downloaded all psych's libraries as the readme says
> > 
> > Basically hxCodec 3.0.2 (and older versions too) has a shitty thing which makes it bug To make it work you have to install it normally (so without using hmm) in your main folder, basically how you would download normally an haxe lib using the command prompt on the desktop: it must **BE** the same version as the one installed using the hmm method And then ofc you have to install the same hxCodec with the same version using hmm if you didn't already, so as the readme says
> > 
> > This bug got fixed from hxCodec version 3.0.3
> 
> it still doesn't work for me

then it must be something else
maybe you didnt install properly some libs or else
report it creating a new issue so people can help you

**Comment by Aness6040** [comment]
> 

Did'nt Work

**Comment by NexIsDumb** [comment]
> Did'nt Work

then as i said before too, create a new issue and let other ppl help you, dont use this issue

**Comment by B1ueRabb1t7** [comment]
> ![image](https://private-user-images.githubusercontent.com/116938209/258312339-bdc0eb55-1827-46d3-8971-9e6738f4af65.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NzIzNTAsIm5iZiI6MTcxMDc3MjA1MCwicGF0aCI6Ii8xMTY5MzgyMDkvMjU4MzEyMzM5LWJkYzBlYjU1LTE4MjctNDZkMy04OTcxLTllNjczOGY0YWY2NS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMTQyNzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc1ZDBmMGIyMmY1OGI1MjAyM2IwOTM5YzM3N2M4NDcyNTUwOTU4MGYyMWRiNDUxMWJjNzViYjYyMmNmYWMzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Hj21QcCI-DpR1Bvqrw2YNt_qckgtnraYkBY8rhVjK8s)
> 
> I did it already

Why do you play Minecraft Bedrock?

**Comment by expertyeti** [comment]
Hello, I come to present a problem that occurred to me when compiling Psych engine, when compiling I simply found:

source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall

and it is simply tedious, run all the Visual Studio files, I remember having executed the necessary .bat that are inside the setup folder in this way installing the dependencies, as well as having correctly installed git and haxe, what should I do?

**Comment by B1ueRabb1t7** [comment]
> Hello, I come to present a problem that occurred to me when compiling Psych engine, when compiling I simply found:
> 
> source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall
> 
> and it is simply tedious, run all the Visual Studio files, I remember having executed the necessary .bat that are inside the setup folder in this way installing the dependencies, as well as having correctly installed git and haxe, what should I do?

I saw this and I must ask three things:
1: What Psych Engine version are you using?
2: What does TeaCall do? And send either a picture or a screenshot because this might help viewing your code, otherwise without the code, I don't think people can help a lot
3: Is English your first language or second?

**Comment by JaskeyWolf** [comment]
I have the same problem and the same thing appears, I don't know what to do

C:\Users\julio cesar\Desktop\mod de fnf\FNF-PsychEngine-main\FNF-PsychEngine-main>lime test windows
source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall

that's what I get when I try to compile

**Comment by FinderFromMac** [comment]
> Hello, I come to present a problem that occurred to me when compiling Psych engine, when compiling I simply found:
> 
> 
> 
> source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall
> 
> 
> 
> and it is simply tedious, run all the Visual Studio files, I remember having executed the necessary .bat that are inside the setup folder in this way installing the dependencies, as well as having correctly installed git and haxe, what should I do?

In source/psychlua.hx replace everything with "TeaCall" to "Tea"

**Comment by JaskeyWolf** [comment]
I did what you said and tried again to see if it works, but when I put "lime test windows" it didn't work and it gave me this:

source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here

**Comment by Enois213** [comment]
i need help "source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall"

**Comment by FuseIsHere813** [comment]
> i need help "source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall"

set all references of "TeaCall" to "Tea"
