### ISSUE TITLE
Can We get this on mac?

### ISSUE THREAD

**Issue by Tigedraglon10** [ShadowMario/FNF-PsychEngine#1277]
### What is your question?

Ive wanted to mod for a long time and this is the best choice, but its only for exe executors

**Comment by NS-Unfair** [comment]
Not true, you can build the game on mac following the instructions for building FNF on Windows.

**Comment by Tigedraglon10** [comment]
> Not true, it isn't only for exe executors, you can build the game on mac following the instructions for building FNF on Windows.
> 
> And to answer your question, yes.

Okay, thanks ill close this
