### ISSUE TITLE
Song Fade Out ?

### ISSUE THREAD

**Issue by Shaggers-official** [ShadowMario/FNF-PsychEngine#12783]
### Describe your problem here.

I'm trying to make a very rare event that will fade out the song. When i tried to do it, i realized that the game keeps trying to pull the volume of the inst and vocals to its original value, i tried this on Update : 
``
if flashback then setProperty('vocals.volume', getProperty('vocals.volume') - 0.035)
setPropertyFromClass('flixel.FlxG.sound.music', 'volume', getPropertyFromClass('flixel.FlxG.sound.music', 'volume') - 0.035); 
end
``
But it doesn't change anything, is there a way i could keep it from putting the volume to its original value that ?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
not with lua no

**Comment by Shaggers-official** [comment]
In source code then maybe ? Like, i can create a new function in source that i can re-use in lua right ?

**Comment by Shaggers-official** [comment]
Okay i figured it out. In the PlayState file, i searched the code that would set the volume of the vocals to 1 everytime the note hit was set to 'wasGoodHit' (for me it was at the line 4735) and made it only happen if the song name isn't what the name of the song i want to make the fade out on. After that, since i know it would actually break the volume system, i made in Lua a code on goodNoteHit() that if the variable 'flashback' isn't on (cuz yes, i'm making this fade out for a flashback mechanic), it would reset the volume of the vocals back to 1. Then, all i need to do, is to make a custom fadeOutVocals() function i added myself on the FunkinLua state and voila !
