### ISSUE TITLE
PROBLEM MY CUSTOM BF SPRITES WHEN I PUT THEM INTO PSYCH ENGINE!

### ISSUE THREAD

**Issue by SOOONNN** [ShadowMario/FNF-PsychEngine#12780]
### Describe your problem here.

![Screenshot 2023-07-21 200215](https://github.com/ShadowMario/FNF-PsychEngine/assets/140219626/7d720da4-1b2d-4f2f-a8ce-4fc33ecf2976)
![Screenshot 2023-07-21 200201](https://github.com/ShadowMario/FNF-PsychEngine/assets/140219626/f6138d5e-aa2e-4f68-bd92-d7b70ca09391)
Hello!!! My issue is hopefully a simple one to you guys, but it's nearly impossible for me. I created a custom- made, my artstyled BF sprite in flash CS4. I then downloaded CS6 and made it into a spritesheet there. I'm not sure if a specific pattern is needed, so i just put it in order like this: (DOWN, DOWN MISS, IDLE, RIGHT, RIGHT MISS, LEFT, LEST MISS, UP, UP MISS.
I loaded it into psych engine, and it gave me the error message ( i pasted it above )

Thank you for your time!!!
-SOON

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
don't make duplicate issues

**Comment by Chidubemmo** [comment]
FNF supports spritesheets in UTF-8 encoding until the release of Adobe Animate spritesheets were exported in UTF-16 encoding. Open the xml in Notepad and use save as... and change the format there or if you have notepad++ just change it at the bottom
