### ISSUE TITLE
How do I move Lua animation to the beat?

### ISSUE THREAD

**Issue by tnpr3432** [ShadowMario/FNF-PsychEngine#12786]
### Describe your problem here.

title

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

MainMenuState and FreePlayState Only

**Comment by MemeHovy** [comment]
`function onBeatHit(curBeat)`

**Comment by Akhia11** [comment]
ok now close this as solved

**Comment by tnpr3432** [comment]
thanks
