### ISSUE TITLE
Okay so i got a different error this time from building the game..

### ISSUE THREAD

**Issue by AzzyDrezzy12** [ShadowMario/FNF-PsychEngine#12784]
### Describe your problem here.

```
source/PlayState.hx:75: characters 33-53 : Type not found : hxcodec.VideoHandler
source/PlayState.hx:1575: characters 13-23 : Type not found : MP4Handler
```

idk how to fix this

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
what version of hxCodec are you using?

**Comment by AzzyDrezzy12** [comment]
Sorry for late response! But Anyway, The Version of hxCodec im using is  2.5.1

**Comment by MemeHovy** [comment]
> Sorry for late response! But Anyway, The Version of hxCodec im using is 2.5.1

update to 2.6.1

**Comment by AzzyDrezzy12** [comment]
now i got this error.

`source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
E:\FNF Source Code\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths`

**Comment by MemeHovy** [comment]
install visual studio

**Comment by AzzyDrezzy12** [comment]
alright, i'll let you know if it'll work or not.

**Comment by AzzyDrezzy12** [comment]
it actually worked, thank you MemeHovy

**Comment by MemeHovy** [comment]
> it actually worked, thank you MemeHovy

np
