### ISSUE TITLE
Stage making problems

### ISSUE THREAD

**Issue by Chidubemmo** [ShadowMario/FNF-PsychEngine#12785]
### Describe your problem here.

So I made this stage in Flash which you can see below
![image_2023-07-23_100949884](https://github.com/ShadowMario/FNF-PsychEngine/assets/87916057/a7d03d2f-a49e-44a9-8ce9-c48f7f108c88)
But when I export the assets and put the Xs and Ys use in flash the stage appears differently including the player (Note: the player is on the left instead of right).
![image_2023-07-23_101241843](https://github.com/ShadowMario/FNF-PsychEngine/assets/87916057/8b9858b2-4feb-49e0-a665-2685c567f536)
I want to figure out why it doesn't work

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
> ### Describe your problem here.
> So I made this stage in Flash which you can see below ![image_2023-07-23_100949884](https://user-images.githubusercontent.com/87916057/255381926-a7d03d2f-a49e-44a9-8ce9-c48f7f108c88.png) But when I export the assets and put the Xs and Ys use in flash the stage appears differently including the player (Note: the player is on the left instead of right). ![image_2023-07-23_101241843](https://user-images.githubusercontent.com/87916057/255382019-8b9858b2-4feb-49e0-a665-2685c567f536.png) I want to figure out why it doesn't work
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> _No response_

you need to set the stage scale

**Comment by Chidubemmo** [comment]
> 

I'm stupid... how?

**Comment by MemeHovy** [comment]
> > 
> 
> I'm stupid... how?

show me the code you used to make the stage first

**Comment by ShadowMario** [comment]
check the Stage .json file and edit accordingly to what you want

**Comment by Chidubemmo** [comment]
> > > 
> > 
> > 
> > I'm stupid... how?
> 
> show me the code you used to make the stage first
I modified BGSprite.hx because the game not finding the path (Psych 0.6.3)
```hx

		switch (curStage)
		{
			case 'mirrorhouse':
				var mirrors:BGSprite = new BGSprite('bg', 'week1', 960, 417.3, 0.9, 0.9);
				add(mirrors);

				if(!ClientPrefs.lowQuality)
				{
					var lights:BGSprite = new BGSprite('lights', 'week1', 953.75, -45.3, 0.9, 0.9);
					add(lights);
				}

				columns = new BGSprite('columns', 'week1', 1095, 540, 0, 0);
				

				mirrorworld = new BGSprite('MirrorWorld', 'week1', 1681.5, 542, 0.9, 0.9);
				add(mirrorworld);

		}
```
My main concern are the assets being weird
