### ISSUE TITLE
Is there a way to add visual effects without the source code?

### ISSUE THREAD

**Issue by LiterallyAnAxolotl** [ShadowMario/FNF-PsychEngine#1278]
### Describe your problem here.

**So I'm trying to make a note so when you hit it a jumpscare pops up but I can't figure out how to do it? if there is no way to do it without source code is there an easy way I can port everything I've done with lua easily?**

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

added 5 custom notes and a new week and deleted all songs but tutorial and my songs. working on a new note now

**Comment by Murasaki1514** [comment]
Yeah, the only change you have to make in the source code is in chartingState.hx where you add the arrowtype. Then in lua you can code the noteskin/arrow jupmscare effect when the note is pressed

**Comment by ShadowMario** [comment]
`makeLuaSprite` or `makeAnimatedLuaSprite` might help you in something.
Check the Lua Script API on the Wiki.
