### ISSUE TITLE
Any Mod that runs on Psych Engine won't start at all.

### ISSUE THREAD

**Issue by MrJackSteel** [ShadowMario/FNF-PsychEngine#12789]
### Describe your problem here.

As I said in the Title, for some reason none of the mods that use/run the Psych Engine boot up when I try to play them. I know this is whole section is about the actual usage of the Engine and issues while using it, but I'd really appreciate if someone could help me out with this, as I genuinely have no idea why this is happening, and I can't find any solutions online no matter how much I search..

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ZeitHeld** [comment]
Must be an issue if you are trying to put it 0.6.x mods inside of 0.7
the code changed quite a bit, and so stuff might need to rewritten a bit

**Comment by ShadowMario** [comment]
The source code got massively rewritten on 0.7, you might want to wait until Mod creators update their mods to 0.7 or something
