### ISSUE TITLE
https://cdn.discordapp.com/attachments/866856727621795850/890335034786062336/script.lua wont open

### ISSUE THREAD

**Issue by PaulActionMan** [ShadowMario/FNF-PsychEngine#12788]
### Describe your problem here.

can someone send me the code so i can copy and paste it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ThePlank** [comment]
![1030168800785596486](https://github.com/ShadowMario/FNF-PsychEngine/assets/75984453/e63c5cdf-c89e-4976-a899-6d1a5981163a)

**Comment by ShadowMario** [comment]
fixed

**Comment by donaldjuniortrump** [comment]
no! is not fixed! shit no load!
it's just a blank page!
