### ISSUE TITLE
Engine should replace basegame charts or songs like images do

### ISSUE THREAD

**Issue by ColdlordXRepositories** [ShadowMario/FNF-PsychEngine#12793]
### What feature do you want to get added on the **base** engine?

When you put images into mods\images, it replaces those images automatically.
I think it should also do that for songs and charts. could be useful for remix mods.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
you can already do that
