### ISSUE TITLE
Week 4 Layering Issue

### ISSUE THREAD

**Issue by CobaltGames** [ShadowMario/FNF-PsychEngine#12794]
### Describe your bug here.

GF is in front of the limo
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/79053181/f3ad125d-5ea1-4453-9a4b-6c3969589110)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
For god's sake i've already said it's not a bug

**Comment by SrBagel** [comment]
You could put it back with a lua script

function onCreate()
    setObjectOrder('gfGroup', 6)
 end

**Comment by Crappy-Productions** [comment]
> 

glad that doesn't work anymore due to this one line of code
![Screenshot 2023-09-11 164555](https://github.com/ShadowMario/FNF-PsychEngine/assets/98716926/ce506c35-7c3e-4dce-b85c-d02f27b5256e)
