### ISSUE TITLE
Health bar colors not working (0.7)

### ISSUE THREAD

**Issue by CookieGuyYT** [ShadowMario/FNF-PsychEngine#12798]
### Describe your bug here.

Health bar colors were reset to white after moving from 0.6.3 to 0.7
Example:
![bug](https://github.com/ShadowMario/FNF-PsychEngine/assets/140354216/8d048a43-09a3-4e76-8171-53cd1ba5d7a6)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, copy and pasted everything in the mods folder from 0.6.3 to 0.7's mods folder

**Comment by ender69funk** [comment]
it's not bug i quess

**Comment by FrancescosToon** [comment]
It is a bug, because the color data is still stored in the character files, in addition to that, the "healtBarBG" object no longer exists and it's instead just "healtBar" -> my guess is that the layers got messed up and the layer with the colors just got sent to the shadow realm...

**Comment by ShadowMario** [comment]
Should be fixed
