### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by Jericho2013** [ShadowMario/FNF-PsychEngine#12795]
### What is your question?

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/109614305/8acb62d8-4ff9-4246-b9f1-3ef7a2fccf87)
While compiling, an error says what's on the image, can anyone help?

**Comment by MemeHovy** [comment]
literally read the error

**Comment by ShadowMario** [comment]
Did you edit the file?

**Comment by Jericho2013** [comment]
I think so, I don't need help anyway. Thanks for helping though.
