### ISSUE TITLE
Can't open application

### ISSUE THREAD

**Issue by CatOfTheDarkness** [ShadowMario/FNF-PsychEngine#12799]
### Describe your problem here.

I'm using Psych Engine 0.7 (no source) but every time that I open the application, it just gets deleted. Can somebody help me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by MemeHovy** [comment]
make sure your antivirus isn't interfering

**Comment by ShadowMario** [comment]
Seems to be an Anti-virus issue

**Comment by CatOfTheDarkness** [comment]
> make sure your antivirus isn't interfering, it could be false flagging

Tysm

**Comment by CatOfTheDarkness** [comment]
> Seems to be an Anti-virus issue

Tysm
