### ISSUE TITLE
v0.7 Note skin/Note Splash bug

### ISSUE THREAD

**Issue by AfroDanceMan** [ShadowMario/FNF-PsychEngine#12791]
Mods that use custom note skins and splashes are broken. They are either overridden, are all white, or crash the game entirely. Note splashes sometimes work and if they do are using both the custom splashes as well as the splashes from the new update overlapping on each other. 
Example of white
![Screenshot_82](https://github.com/ShadowMario/FNF-PsychEngine/assets/140351548/942f7e96-4aa9-4b52-b669-a45189e29322) 
Error I got during a song (prob related to how events are handled and is nothing to do with notes or splashes but thought I should mention it anyway)
![Screenshot_83](https://github.com/ShadowMario/FNF-PsychEngine/assets/140351548/b7448a8b-b38f-44d5-a54c-6468b9a69471)
Note splashes overlapping
![Screenshot_84](https://github.com/ShadowMario/FNF-PsychEngine/assets/140351548/9c7bb5c0-54ee-4ff4-9957-fe3792180a5d)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

transferred mods over from v0.6.3

**Comment by ShadowMario** [comment]
Yes, this is a bug with old notesplashes/textures, and there's nothing i can do about mods that used it, just port your mods to 0.7
If you want to disable note colors completely you can do this:

```lua
function onCountdownStarted()
    for i = 0, getProperty('unspawnNotes.length') - 1 do
        setPropertyFromGroup('unspawnNotes', i, 'rgbShader.enabled', false)
    end
end
```
