### ISSUE TITLE
gf in front of car

### ISSUE THREAD

**Issue by sammysonic12345** [ShadowMario/FNF-PsychEngine#12809]
### Describe your bug here.

gf is just infront of car

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by SrBagel** [comment]
Its not a bug

**Comment by SrBagel** [comment]
> Its not a bug

Its a choice

**Comment by SrBagel** [comment]
You can move her back with a lua script 

function onCreate()
    setObjectOrder('gfGroup', 6)
 end

but why would you want to
