### ISSUE TITLE
I want to reset my note colors, WHERE THE F*CK IS THE RELOAD BUTTON?

### ISSUE THREAD

**Issue by JuansiYT** [ShadowMario/FNF-PsychEngine#12800]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/140355173/c6a77f6e-9321-4a38-a867-49240f76b03f)

I want to reset my note colors (now updated to 0.7) but... can you PLEASE tell me WHERE THE F*CK IS THE RELOAD BUTTON? i cant see it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by JuansiYT** [comment]
Oh i already found it, it was the R button on my keyboard, thanks c:

**Comment by JuansiYT** [comment]
Oh it was the R key on the keyboard, ty

**Comment by ShadowMario** [comment]
Close the fucking issue we're getting a lot of them lately
