### ISSUE TITLE
Changing backgrounds during song

### ISSUE THREAD

**Issue by GhostCyclo3999** [ShadowMario/FNF-PsychEngine#1280]
### What feature do you want to get added on the base engine?

I know this is stupid but, if possible:
**Add in a event where you change the background during a certain step or time or part of song.**
I'm being dead serious, if possible because then there'll be _alot_ of better mods with this, **_including ports._**

                                                          ### -Ghost cyclo

**Comment by Hafimieh** [comment]
yezzzzz great and cool idea

**Comment by DEV-idiotXD** [comment]
> how to make it

> disclamer u need to do this in the stages lua script or the songs lua script

makeLuaSprite('tag', 'char', 0, 0)
makeLuaSprite('tag2', 'char2', 2, 2)
addLuaSprite('tag2', false)



if curStep == 50 then
	removeLuaSprite('tag2', false)
	--repeat this with the rest of the sprites
	addLuaSprite('tag', false)
end

if curStep == 10 then
	removeLuaSprite('tag', false)
	--repeat this with the rest of the sprites
	addLuaSprite('tag2', false)
end


example u get it right? so ye there or use timers so it will be less clutered

**Comment by ShadowMario** [comment]
1. I'm sick tired of ports and i'm starting to hate them at this point.
2. Duplicate of #529
