### ISSUE TITLE
'PsychEngine.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by SomeSortOfSpark** [ShadowMario/FNF-PsychEngine#12804]
### Describe your problem here.

![GitIssue](https://github.com/ShadowMario/FNF-PsychEngine/assets/96387347/72849e12-9872-41c6-b09f-20bafe65aaa8)
'PsychEngine.exe' is not recognized as an internal or external command,
operable program or batch file.

I keep getting this issue after following everything. All libraries are installed and working, but the executable itself or 'PsychEngine.exe' to be specific won't seem to try and exist when I try doing: lime build windows & lime run windows

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
Your libraries or Haxe is on the wrong version, [check this page out](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)

**Comment by SomeSortOfSpark** [comment]
![GitUpdate](https://github.com/ShadowMario/FNF-PsychEngine/assets/96387347/410281f6-a415-492a-b141-4e6cc713593a)
So most of the things were fixed. Just video handler and the executable existing are left.
![GitUpdat1part2](https://github.com/ShadowMario/FNF-PsychEngine/assets/96387347/f318d7e1-e139-4454-801a-0be4bb1b9cb6)

**Comment by SomeSortOfSpark** [comment]
![Git4](https://github.com/ShadowMario/FNF-PsychEngine/assets/96387347/adabab7a-2b6a-40e2-ae0f-94d188bc9798)
![Git3](https://github.com/ShadowMario/FNF-PsychEngine/assets/96387347/f648cc09-8096-4d5d-828a-4316ec0b17a5)

**Comment by NexIsDumb** [comment]
#12770 and do lime test windows
