### ISSUE TITLE
can you bring back the old lua system?

### ISSUE THREAD

**Issue by JuansiYT** [ShadowMario/FNF-PsychEngine#12803]
### What feature do you want to get added on the **base** engine?

please do it, indie cross is broken on this new update and sans dodge mechanics dont work

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by ShadowMario** [comment]
It's literally impossible to bring it back, the source has been HIGHLY changed.

**Comment by JuansiYT** [comment]
Why dont just add 0.7 features to 0.6.3?
