### ISSUE TITLE
Error with 

### ISSUE THREAD

**Issue by fanproductions** [ShadowMario/FNF-PsychEngine#12805]
### Describe your problem here.

![Captura de tela 2023-07-23 214817](https://github.com/ShadowMario/FNF-PsychEngine/assets/115906994/f9896c8d-ed8d-42e0-9b51-db433afb4e65)
Back then I could compile the engine with no problem at all,
but then it started to give errors and this is the most recent one.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I only tried to compile it to see if it worked.

**Comment by fanproductions** [comment]
Any help is appreciated.

**Comment by ender69funk** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions
