### ISSUE TITLE
How to turn off note hue shifting

### ISSUE THREAD

**Issue by Bopple-McNuggets** [ShadowMario/FNF-PsychEngine#12802]
### Describe your problem here.

So I'm trying to see if there's a way to turn off the note hue shifting (the one in the options) because my build has several noteskins from 0.6.3 which have their colors broken by the game trying to shift their hues. I looked through the update changelog and did find this:
<img width="741" alt="stuff" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/107228487/b898f5d0-c16b-4492-8f5f-dde0b1a3b08f">
-but my current attempts to create a script that disables that have been unsuccessful. Is there something I'm missing, or does it not work in the LUA build?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Transferred mods from 0.6.3 to 0.7

**Comment by Bopple-McNuggets** [comment]
alternatively, how to change the hue shifting for different note types, that'd also fix the problem

**Comment by ShadowMario** [comment]
This should disable note colors
```lua
function onCountdownStarted()
    for i = 0, getProperty('unspawnNotes.length') - 1 do
        setPropertyFromGroup('unspawnNotes', i, 'rgbShader.enabled', false)
    end
end
```

**Comment by Bopple-McNuggets** [comment]
sweet, it worked. thx a ton, man! :D

**Comment by Bopple-McNuggets** [comment]
forgot to close it, hecc

**Comment by BigChocolateApple** [comment]
> ```lua
> function onCountdownStarted()
>     for i = 0, getProperty('unspawnNotes.length') - 1 do
>         setPropertyFromGroup('unspawnNotes', i, 'rgbShader.enabled', false)
>     end
> end
> ```

Bro omg how to just disable rgb on custom notes 😭

**Comment by MegalBits** [comment]
> > ```lua
> > function onCountdownStarted()
> >     for i = 0, getProperty('unspawnNotes.length') - 1 do
> >         setPropertyFromGroup('unspawnNotes', i, 'rgbShader.enabled', false)
> >     end
> > end
> > ```
> 
> Bro omg how to just disable rgb on custom notes please 😭

```lua
function onCountdownStarted()
    for i = 0, getProperty('unspawnNotes.length') - 1 do
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'NOTEID' then
        	setPropertyFromGroup('unspawnNotes', i, 'rgbShader.enabled', false)
		end
    end
end
```

Add an if with the note id (should be the same as the files name)

**Comment by MattyLma0** [comment]
> > > ```lua
> > > function onCountdownStarted()
> > >     for i = 0, getProperty('unspawnNotes.length') - 1 do
> > >         setPropertyFromGroup('unspawnNotes', i, 'rgbShader.enabled', false)
> > >     end
> > > end
> > > ```
> > 
> > 
> > Bro omg how to just disable rgb on custom notes please 😭
> 
> ```lua
> function onCountdownStarted()
>     for i = 0, getProperty('unspawnNotes.length') - 1 do
> 		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'NOTEID' then
>         	setPropertyFromGroup('unspawnNotes', i, 'rgbShader.enabled', false)
> 		end
>     end
> end
> ```
> 
> Add an if with the note id (should be the same as the files name)


where do you put the code, Im new to modding and I have no idea what Im doing lmao

**Comment by mattye-owo** [comment]
> This should disable note colors
> 
> ```lua
> function onCountdownStarted()
>     for i = 0, getProperty('unspawnNotes.length') - 1 do
>         setPropertyFromGroup('unspawnNotes', i, 'rgbShader.enabled', false)
>     end
> end
> ```

This worked for the note colors in general, but when press the note and it does that thing where its desaturated it is still with the changed colors
