### ISSUE TITLE
psych engine is a virus?

### ISSUE THREAD

**Issue by eeehhhidk** [ShadowMario/FNF-PsychEngine#12801]
### What is your question?

so i downloaded the new update and its getting recognized has a virus can anybody help me?

**Comment by thegreatskep** [comment]
if youre using windows (havent used any other os so idk if they do this) just click read more or whatever it says and then click run, there isnt a virus anywhere in the files
windows does that with anything that could potentially have a virus as far as i know

**Comment by eeehhhidk** [comment]
k thx
