### ISSUE TITLE
CPU Crash

### ISSUE THREAD

**Issue by ender69funk** [ShadowMario/FNF-PsychEngine#12817]
### Describe your bug here.

I downloaded last offical build and i turned cpu caching and crahed
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/112335251/d54a7ed5-0963-4cee-96b2-c3cb2d1b741e)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/112335251/84008845-339d-4aef-a73b-bfa34a0fc5ac)

### Command Prompt/Terminal logs (if existing)

first crash
backend/Paths.hx (line 267)
states/TitleState.hx (line 219)
states/TitleState.hx (line 180)
flixel/util/FlxTimer.hx (line 205)
flixel/util/FlxTimer.hx (line 295)
flixel/FlxGame.hx (line 750)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

second crash
backend/Paths.hx (line 267)
objects/StrumNote.hx (line 99)
objects/StrumNote.hx (line 20)
options/VisualsUISubState.hx (line 202)
options/VisualsUISubState.hx (line 190)
flixel/group/FlxGroup.hx (line 769)
options/VisualsUISubState.hx (line 189)
options/Option.hx (line 81)
options/BaseOptionsMenu.hx (line 183)
flixel/FlxState.hx (line 203)
flixel/FlxState.hx (line 212)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, it's offical build

**Comment by ShadowMario** [comment]
It looks like your PC/GPU is too weak to handle GPU Caching
