### ISSUE TITLE
Custom Pause Screen Bug Switching Over to New Version

### ISSUE THREAD

**Issue by SupahMonky** [ShadowMario/FNF-PsychEngine#12814]
### Describe your bug here.

I was making a lua mod and I put all of my mod folder files to the newer version and it broke a lot of minor things that I already finished doing like my custom healthbars layer and a custom timebar layer being slightly messed up. my custom gameover events also now default to the base game gameover. There's also a few camera event problems that started occurring. All of those things I could try to find a fix for but one thing that has me stumped is my custom pause screen. Most of the options on it will now crash the game upon selecting them, the only one working being continue game option.
![image_2023-07-23_230915482](https://github.com/ShadowMario/FNF-PsychEngine/assets/86164439/77a4e233-91b6-4270-981d-27a6f134f18d)

### Command Prompt/Terminal logs (if existing)

```bash
psychlua/CustomSubstate.hx (line 83)
flixel/FlxState.hx (line 162)
flixel/addons/transition/Flx TransitionableState.hx (line 69)
flixel/addons/ui/Flx UlState.hx (line 331)
states/PlayState.hx (line 2917)
flixel/FlxGame.hx (line 629)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/Flx Game.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine
> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Every song data folder has a different pause menu script that used to work in 1.6.3. The only things connected to this custom pause menu script are the assets that work fine for it switching over (the 2 characters coming from the left and right and the pause menu box)

**Comment by ShadowMario** [comment]
You will have to show the code for the substate

**Comment by ShadowMario** [comment]
This is not the substates code, just send the file or something please

**Comment by ShadowMario** [comment]
Closed from inactivity
