### ISSUE TITLE
I need a bit of help with hxCodec error when compiling.

### ISSUE THREAD

**Issue by TheSketchAlex** [ShadowMario/FNF-PsychEngine#12818]
### Describe your problem here.

This is the only error I currently get when compiling the 0.7 source code.

Error: Could not find include file "C:/HaxeToolkit/haxe/lib/hxCodec/2,5,1/project/Build.xml"

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not do any changes at all.

**Comment by ItzSonic1991** [comment]
How did you fix this?
