### ISSUE TITLE
maybe there should be a xml editor

### ISSUE THREAD

**Issue by toppatsonic** [ShadowMario/FNF-PsychEngine#12810]
### What feature do you want to get added on the **base** engine?

I always just making a mod and wondering, how do I make xml files. xml generator wont work on my device. and dont have adobe animate so yeah. but with a xml editor, it easier for people who cant use xml generator and people who dont have adobe animate.

CONCEPT ART:

![backdrop1 (8)](https://github.com/ShadowMario/FNF-PsychEngine/assets/126359328/8cdfb505-0e6b-4066-bc31-7d95867253d0)

Useful feature

**Comment by ShadowMario** [comment]
no retard

**Comment by toppatsonic** [comment]
ok

**Comment by toppatsonic** [comment]
:0 guess wishes do come true
