### ISSUE TITLE
Custom note skin week 6 crash

### ISSUE THREAD

**Issue by SrBagel** [ShadowMario/FNF-PsychEngine#12812]
### Describe your bug here.

When I use my custom note skin and try to play week 6 the game crashes. I think it happens because there is no pixel skin for my custom note skin

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

N/A

**Comment by ShadowMario** [comment]
try to copy base game's noteskins and rename then

**Comment by SrBagel** [comment]
I found a fix. If you make a pixelUI folder in mods/images and add a noteskin folder to it then copy the base pixel note and rename it to your custom note skin
