### ISSUE TITLE
Two Voices.ogg files (one for opponent, other for bf) - question

### ISSUE THREAD

**Issue by GreenNinja2525** [ShadowMario/FNF-PsychEngine#12815]
### What is your question?

I am very new to GitHub so excuse my informality, but I wanted to ask if having separate vocal tracks for bf and the opponent is possible or will be possible. I am pretty sure this is coming to the actual FNF full game (like when bf misses the opponent still sings and doesn't cut out) but if this is possible in Psych Engine that would be great. If so, is it a compiling thing only or can I name 2 Ogg files something and this will magically work? I don't understand the whole wiki thing on GitHub so if this is in the wiki I'm sorry for bothering you, thanks!

**Comment by CaptainBaldi** [comment]
not possible without source

**Comment by spark-the-dragon** [comment]
could be possible if you played 2 different audio files at the same time and had a blank voices file and set the respective voices file mute if a miss occurs by setting the volume to 0 until another note is hit

**Comment by GreenNinja2525** [comment]
That might work but I would rather wait until they add this to psych engine without source, if they eventually do. thanks again to both of you
