### ISSUE TITLE
Compiling experimental build gives an "Class<llua.Lua_helper> has no field sendErrorsToLua" error

### ISSUE THREAD

**Issue by RowanSkie** [ShadowMario/FNF-PsychEngine#12816]
### Describe your problem here.

Hello! I didn't notice we've gotten an experimental build after 0.6.3. So I attempted to build it, and I got this error:

```
source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
```

Any suggestions on how to fix this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by RowanSkie** [comment]
Fixed by deleting the entire repository and reinstalling everything. Must be an artifact from 0.6.3.

**Comment by CrazyDany** [comment]
remove of this block code
catch(e:Dynamic)
		{
			if(Lua_helper.sendErrorsToLua) {LuaL.error(l, 'CALLBACK ERROR! ${if(e.message != null) e.message else e}');return 0;}
			trace(e);
			throw(e);
		}

**Comment by MemeHovy** [comment]
> remove of this block code catch(e:Dynamic) { if(Lua_helper.sendErrorsToLua) {LuaL.error(l, 'CALLBACK ERROR! ${if(e.message != null) e.message else e}');return 0;} trace(e); throw(e); }

try blocks can't have no catch

**Comment by LUCARIOOO123** [comment]
haxelib remove linc_luajit

haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git
