### ISSUE TITLE
Unknown null object reference

### ISSUE THREAD

**Issue by Awe-Some-Jack** [ShadowMario/FNF-PsychEngine#12827]
### Describe your bug here.

![화면 캡처 2023-07-25 011733](https://github.com/ShadowMario/FNF-PsychEngine/assets/80558058/67afa152-780c-4433-9983-70cbd804bc02)

I Just Playing fnf MOD But When the song ended, this error window appeared along with the confirmMenu sound effect.
It is probably estimated that there was an error in the achievement.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

NO

**Comment by MemeHovy** [comment]
like shadow Mario said, psych engine 0.5.2h is not supported anymore
