### ISSUE TITLE
editors not showing up

### ISSUE THREAD

**Issue by Shibamer** [ShadowMario/FNF-PsychEngine#12826]
### Describe your bug here.

ive recently decided to try to make an fnf mod, and in the tutorial im using to makoe a sprite i need to use psych engine so of course i downloaded it and you gotta go to story mode because the editors will apparently be there but its just all the weeks from 1 to 7 and ive tried everything yet nothing worked

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope i think

**Comment by ShadowMario** [comment]
You're supposed to **press 7 on the MAIN MENU**, not Story Mode.
