### ISSUE TITLE
Error with compiling Psych

### ISSUE THREAD

**Issue by fanproductions** [ShadowMario/FNF-PsychEngine#12824]
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/115906994/406c09d3-f8a2-46d1-86fe-d54a55fda08d)
Uhhh... WHAT DO I DO

### Command Prompt/Terminal logs (if existing)

```bash
D:\Nova pasta\FNF-PsychEngine-0.7>lime test windows
source/states/PlayState.hx:63: characters 14-30 : Type not found : vlc.VideoHandler
source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
source/states/PlayState.hx:778: characters 13-25 : Type not found : VideoHandler
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by ConnorYT289** [comment]
Did you set hxCodec as git? That will fix the VideoHandler errors.

Also for "Class<llua.Lua_helper> has no field sendErrorsToLua", delete the code from it and the engine will compile.

**Comment by fanproductions** [comment]
> Did you set hxCodec as git? That will fix the VideoHandler errors.
> 
> Also for "Class<llua.Lua_helper> has no field sendErrorsToLua", delete the code from it and the engine will compile.

i tried but it just gave me another error
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/115906994/7881a69d-07c3-4237-a62c-db223dadf2fc)

**Comment by TowsterBusiness** [comment]
make sure you did `haxelib git hxCodec https://github.com/polybiusproxy/hxCodec` since they restructured hxcodec entirely

**Comment by ShadowMario** [comment]
Try doing this and tell me if it works:
```
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git
```
