### ISSUE TITLE
"Could not find haxelib 'hxCodec', does it need to be installed?" despite the fact hxCodec is installed

### ISSUE THREAD

**Issue by July2612** [ShadowMario/FNF-PsychEngine#12829]
### Describe your bug here.

So I am trying to compile Psych for the first time, I've done everything up until this point, but I continually get the following error upon attempting to compile the game.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/68839309/fe23b26c-496c-4285-8d30-4dc76f5e6bca)

What could I be doing wrong exactly? I've looked all over the internet for possible solutions but nothing I've tried has fixed it yet.

### Command Prompt/Terminal logs (if existing)

```bash
Microsoft Windows [Version 10.0.22621.1992]
(c) Microsoft Corporation. All rights reserved.

C:\Users\jeris>cd C:\Repos\FNF-PsychEngine-main

C:\Repos\FNF-PsychEngine-main>lime test windows -debug
Error: Could not find haxelib "hxCodec", does it need to be installed?
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I am simply trying to compile for the first time.

**Comment by SonicStyle2006** [comment]
Mayble try to do this 

haxelib remove hxCodec
haxelib install hxCodec 3.0.0

**Comment by July2612** [comment]
> Mayble try to do this
> 
> haxelib remove hxCodec haxelib install hxCodec 3.0.0

Despite the fact the version ShadowMario recommends is a version installed from Git (which is what I was using), I tried anyways. Didn't fix the issue, unfortunately.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/68839309/a7abed08-849f-47d0-bef9-472e288b204d)

**Comment by July2612** [comment]
I forgot to report on this yesterday, but it took 30 redownloads and a reboot but it eventually caved and worked. I will now close this issue.
