### ISSUE TITLE
COMPILE ERROR

### ISSUE THREAD

**Issue by SpriteNoobXD** [ShadowMario/FNF-PsychEngine#12823]
### Describe your problem here.

Whenever I try to compile 0.7 it gives me this error:

source/states/PlayState.hx:63: characters 14-30 : Type not found : vlc.VideoHandler
source/options/NotesSubState.hx:193: characters 48-60 : flixel.input.mouse.FlxMouse has no field deltaScreenX
source/options/NotesSubState.hx:193: characters 80-92 : flixel.input.mouse.FlxMouse has no field deltaScreenY
source/options/NotesSubState.hx:456: characters 62-71 : flixel.math.FlxPoint has no field degreesTo
source/options/NotesSubState.hx:457: characters 42-46 : flixel.math.FlxPoint has no field dist
source/states/PlayState.hx:778: characters 13-25 : Type not found : VideoHandler

I DONT KNOW WHAT TO DO

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by pablowolfgamerbr** [comment]
me and my friend are not able to compile

**Comment by ShadowMario** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by Galabeam** [comment]
I'm getting the same error, I've tried what you said and installed all required libraries.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/68124962/92c3c7fb-6f37-4a56-a1ff-bab6e7a9e327)
