### ISSUE TITLE
Fullscreens when I hit Enter (and can't undo) (resolved)

### ISSUE THREAD

**Issue by noogai9876** [ShadowMario/FNF-PsychEngine#12825]
### Describe your bug here.

I prefer playing FNF in windowed mode and in a small window, but sometimes when I play (not just on base Psych) it automatically switches to fullscreen when I hit Enter, and I can't exit fullscreen again without restarting the game.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Not a bug
This is a windows feature, press Alt + Enter

**Comment by Draconic-Hybrid** [comment]
That's Windows. Happens when you Alt-Tab sometimes, it thinks you're still holding Alt.

**Comment by noogai9876** [comment]
> Not a bug This is a windows feature, press Alt + Enter

Thx!

**Comment by Draconic-Hybrid** [comment]
Remember to close the issue

**Comment by noogai9876** [comment]
> Remember to close the issue
