### ISSUE TITLE
Compiling Error - "has no field sendErrorsToLua"

### ISSUE THREAD

**Issue by Unbekannnt0** [ShadowMario/FNF-PsychEngine#12828]
### Describe your problem here.

I'm trying to compile the Source Code, and this message keeps popping up:
"source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua"

[RowanSkie](https://github.com/RowanSkie) said that it's fixed by "deleting the entire repository and reinstalling everything"
can someone advice me what to do?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by coolaydang** [comment]
haxelib remove linc_luajit

haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git

**Comment by Pregmonaoter** [comment]
GOD THANK YOU THIS ACTUALLY WORKS NOWWWW

**Comment by AliboihiYT** [comment]
> haxelib remove linc_luajit
> 
> haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git

Thank you so much. Ive been trying to compile psych engine for 6 MONTHS its never worked ive used diffrent engines they never worked either. But i thought i had everything i needed but i didnt. Thank You so much

**Comment by max4th** [comment]
deleted everything but they asked for linc_luajit.
what should i do??

**Comment by RedChase07** [comment]
**thank you so much** i finely did it <:D after like **3-4 hours** thanks
