### ISSUE TITLE
How can I access non-static functions and variables in FunkinLua using HScript

### ISSUE THREAD

**Issue by CaptainBaldi** [ShadowMario/FNF-PsychEngine#12839]
### What is your question?

I seem to be having a problem where I can't access functions and variables contained in FunkinLua without the `static` keyword. This is a problem since I'm trying to access some of the shader related variables contained within said file, such as `public var runtimeShaders` and `initLuaShader`, through HScript.
However when doing this a lua trace error appears saying something along the lines of "Null Function/Null Function Pointer", but this only seems to happen with non static variables.

Snippet that works:
```
function onCreate()
        addHaxeLibrary('FunkinLua', 'psychlua')
        runHaxeCode([[
                FunkinLua.luaTrace('luaTrace is a static function ftr', false, false, 0xFFFFFFFF);
        ]])
end
```

Snippet that DOESN'T work
```
function onCreate()
        addHaxeLibrary('FunkinLua', 'psychlua')
        runHaxeCode([[
                // initLuaShader is a standard non-static function ftr
                FunkinLua.initLuaShader('shader');
        ]])
end
```

This wouldn't be as confusing if I couldn't access non static variables from other states, such as, well, PlayState.
Any help on how to fix this or even why this happens would be greatly appreciated.

**Comment by Drawoon2** [comment]
`parentLua`

**Comment by CaptainBaldi** [comment]
> `parentLua`

it works!
thanks man, you have no idea how much this helps me :)
