### ISSUE TITLE
global variables

### ISSUE THREAD

**Issue by iAmzzz278** [ShadowMario/FNF-PsychEngine#12837]
### What is your question?

how i can use the global variables and how can i change the value in other lua

**Comment by CaptainBaldi** [comment]
getGlobalFromScript/setGlobalFromScript

**Comment by Drawoon2** [comment]
Is better setVar/getVar

**Comment by Makine7** [comment]
> getGlobalFromScript/setGlobalFromScript

How to use these? Because when I try, I get tha error "attempt to call Global (a nil value)
