### ISSUE TITLE
freeplay and story mode crashing

### ISSUE THREAD

**Issue by CharlesCatYT** [ShadowMario/FNF-PsychEngine#12830]
### Describe your bug here.

my friend having problems with freeplay and story mode, it's crashing
(yes im "kadedev lite" but its obviously a joke nickname)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/62410083/69a6595e-d24e-416e-ab57-11454ac0995b)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/62410083/cfabab4e-d08c-4679-9e56-65b7b24dd474)

### Command Prompt/Terminal logs (if existing)

```bash
bro she used 0.5.1, there wasnt a crash handler
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

how should i know, it aint my build

**Comment by CaptainBaldi** [comment]
dont report it as a bug if its on older versions

**Comment by ShadowMario** [comment]
0.5.2h is too outdated, i give no support to it.
