### ISSUE TITLE
Custom notes in mods become oversaturated in 0.7.

### ISSUE THREAD

**Issue by HyperBeast43** [ShadowMario/FNF-PsychEngine#12832]
### Describe your bug here.

As it says in the title. 
Before 0.7:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/45052445/1b21902a-51ea-4a9c-8e75-87c53a1e2c5c)
After 0.7:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/45052445/4a7e1734-9a75-42f5-9ec2-b5b32397fd96)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by FrancescosToon** [comment]
Yea, all custom note are now broken because it overlays the colors on top of the textures, thus, if you had note skins with their own colors, now they ain't working -> WHICH IS NOT HOW I'D LIKE IT TO BE, darn it dang

**Comment by ShadowMario** [comment]
You can either disable them now through Chart Editor, or through lua/haxe, it is impossible for it to get fixed "automatically" as the engine cannot recognize what version was the mod made for originally
