### ISSUE TITLE
small question - can you change the scale of gfDanceTitle on the title screen without source?

### ISSUE THREAD

**Issue by GreenNinja2525** [ShadowMario/FNF-PsychEngine#12838]
### What is your question?

I could've sworn this was possible, idk how to do it. If it is possible then I can make my title screen look good.
What I changed: gfDanceTitle and gfDanceTitle.xml to be custom images, this works fine and I moved their positions by altering the .json
I just wanted to increase the size of the image without making the sprite sheet bigger.
Thanks again! :)

**Comment by CaptainBaldi** [comment]
this was a PR if i recall? Never merged though. Anyways, although I'm not exactly familiar with XML's, there might be a way to manually increase the size through them.
Or, obviously, make the image larger.
Would be handy thing having scale pre-built into the json though

**Comment by GreenNinja2525** [comment]
Ok, maybe I misremembered this, that's fine I can just increase sprites size and create a new xml. I might've used a similar engine that wasn't psych that had this. Thanks again! :)

**Comment by GreenNinja2525** [comment]
That seemed to work for now, maybe this can be added at some point idk
