### ISSUE TITLE
Time Bar Breaks if "doTweenColor" is used in v0.7

### ISSUE THREAD

**Issue by FrancescosToon** [ShadowMario/FNF-PsychEngine#12833]
### Describe your bug here.

Before v0.7, if I used the line:  doTweenColor('barColor', 'timeBar', '0xFFFF0000', 0.01, 'linear');
the time bar would change its color from the default white, to the new specified one

But now, it completely breaks it...

It colors the whole bar and it is present even before the HUD fades in during the intro countdown
![_BarTween_Issue](https://github.com/ShadowMario/FNF-PsychEngine/assets/106826854/6e6a75f2-48f4-4abe-864e-77bb1a3ce665)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CaptainBaldi** [comment]
not a bug
health and time bars were reworked
they use leftBar and rightBar FlxSprite's to display their colors

**Comment by SrBagel** [comment]
It was changed to this setTimeBarColors('ffffff', '000000'); the one on the left is the one you want to change
