### ISSUE TITLE
How to use scripts and images in 0.7?

### ISSUE THREAD

**Issue by TheKAPtain313** [ShadowMario/FNF-PsychEngine#12849]
### Describe your problem here.

I have lots of scripts and images that i need to pun into the game but i cant seem to find the scripts folder.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by CaptainBaldi** [comment]
create it :ox:

**Comment by ShadowMario** [comment]
You can create a scripts folder on mods/ just like on older versions, it was removed just to clear a bit the mods folder
