### ISSUE TITLE
Song Json Won't load

### ISSUE THREAD

**Issue by HeroSnackz** [ShadowMario/FNF-PsychEngine#12844]
### Describe your problem here.

So I tried loading a song into the chart editor and I kept getting an error that says "Uncaught Error:[file_contents,assets/data/sussus-nuzzus/sussus-nuzzus.json]". Any tips on how to fix this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
missing chart file
