### ISSUE TITLE
Discord Rich Presence in LUA

### ISSUE THREAD

**Issue by Neown247** [ShadowMario/FNF-PsychEngine#12842]
### What is your question?

I saw that in 0.7 update you can now add Rich Presence to lua. Can somebody help me with how to do it? I didn't find any documentation on how to do it.

**Comment by ShadowMario** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/59b8bdc3-0476-4fcf-abab-91bbeec7e4b0)
It's inside your mod's pack.json file

**Comment by KasenTS** [comment]
When i added my DRP in the pack, it didn't work.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/172998005/816bfd07-a22e-4a30-8603-3049d4c378ad)
