### ISSUE TITLE
Error: Could not find include file "E:/HaxeToolkit/haxe/lib/hxCodec/2,6,1/project/Build.xml"

### ISSUE THREAD

**Issue by candy-many323** [ShadowMario/FNF-PsychEngine#12840]
### Describe your problem here.

when I tried to compile, it gave me this.
Error: Could not find include file "E:/HaxeToolkit/haxe/lib/hxCodec/2,6,1/project/Build.xml"

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by 2JENO** [comment]
same

**Comment by NexIsDumb** [comment]
#12770

**Comment by 2JENO** [comment]
oh sorry for not closing its solved

**Comment by gabrielitapipoca** [comment]
same
