### ISSUE TITLE
Vanilla Note Splashes are blurry

### ISSUE THREAD

**Issue by biomseed** [ShadowMario/FNF-PsychEngine#12846]
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/73907153/873ceb31-e4b4-4e5e-91dc-22fab626d74b)
They are very blurry, which is not how they are supposed to look. That's not normal.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by CaptainBaldi** [comment]
man honestly who cares sob

**Comment by dumdum4347** [comment]
> man honestly who cares sob

me.

**Comment by ShadowMario** [comment]
Well, that's how it was when i exported the Spritesheet, if you check the FLA you can see they're blurry too

**Comment by biomseed** [comment]
> Well, that's how it was when i exported the Spritesheet, if you check the FLA you can see they're blurry too

They are not like that in Week 7's files. You can check right now.

**Comment by biomseed** [comment]
> Well, that's how it was when i exported the Spritesheet, if you check the FLA you can see they're blurry too

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/73907153/155bbdc7-39bc-48ef-8bbf-7d7c53d0fa58)
They don't look so blurry to me, at least in CS4.

**Comment by 2JENO** [comment]
> > Well, that's how it was when i exported the Spritesheet, if you check the FLA you can see they're blurry too
> 
> ![image](https://user-images.githubusercontent.com/73907153/256306807-155bbdc7-39bc-48ef-8bbf-7d7c53d0fa58.png) They don't look so blurry to me, at least in CS4. This is the exact frame. You must have exported them from the fixed splashes (only for animate) fla file, which must have those blurry "splash" symbols but with more frames instead of just one. The "note impact" symbols are the right ones, at least without effects. If you look at the spritesheet from Week 7, you can see it's not as blurry as the "note splash" symbols, meaning there must have been some bug with the fla or something.

how to get that fla???

**Comment by ShadowMario** [comment]
> > Well, that's how it was when i exported the Spritesheet, if you check the FLA you can see they're blurry too
> 
> ![image](https://private-user-images.githubusercontent.com/73907153/256306807-155bbdc7-39bc-48ef-8bbf-7d7c53d0fa58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODA4OTAsIm5iZiI6MTcwMzA4MDU5MCwicGF0aCI6Ii83MzkwNzE1My8yNTYzMDY4MDctMTU1YmJkYzctMzliYy00OGVmLThiYmYtN2Q3YzUzZDBmYTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEzNTYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYzQzOTQ4ODFiM2NlZDMzYWQ4MGFiNGIxZTEwOWQwZjI3ZGM0YWYwNmNkY2EwNjc4NjAzMGI1M2YzZDYxOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.39zchQ6-JLp4MXIz9tTZxBvt1z5szmsVa3q6oTcouSQ) They don't look so blurry to me, at least in CS4. This is the exact frame. You must have exported them from the fixed splashes (only for animate) fla file, which must have those blurry "splash" symbols but with more frames instead of just one. The "note impact" symbols are the right ones, at least without effects. If you look at the spritesheet from Week 7, you can see it's not as blurry as the "note splash" symbols, meaning there must have been some bug with the fla or something.

You're on the wrong symbol btw
