### ISSUE TITLE
NoteSplashes loaded fine in game, but in Debug it looks like this...

### ISSUE THREAD

**Issue by 2JENO** [ShadowMario/FNF-PsychEngine#12855]
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/108978152/f2797255-4a13-45dc-95a0-77d6c256ff0c)

### Command Prompt/Terminal logs (if existing)

```bash
source/backend/Paths.hx:281: oh no its returning null NOOOO: assets/images/noteSplashes.png
source/backend/Paths.hx:281: oh no its returning null NOOOO: assets/images/noteSplashes.png
source/backend/Paths.hx:281: oh no its returning null NOOOO: assets/images/noteSplashes.png
source/backend/Paths.hx:281: oh no its returning null NOOOO: assets/images/noteSplashes.png
source/backend/Paths.hx:281: oh no its returning null NOOOO: assets/images/noteSplashes.png
source/backend/Paths.hx:281: oh no its returning null NOOOO: assets/images/noteSplashes.png
source/backend/Paths.hx:281: oh no its returning null NOOOO: assets/images/noteSplashes.png
source/backend/Paths.hx:281: oh no its returning null NOOOO: assets/images/noteSplashes.png
source/backend/Paths.hx:281: oh no its returning null NOOOO: assets/images/noteSplashes.png
source/backend/Paths.hx:281: oh no its returning null NOOOO: assets/images/noteSplashes.png
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes i edited PlayState, Menus, ClientPrefs, Options, ETC. But I didn't edit anything related to NoteSplashes.

**Comment by 2JENO** [comment]
+ There is no problem with the built-in song, but this is an error that occurs when you run a song installed as a mod.

**Comment by ShadowMario** [comment]
your song has "noteSplashes" instead of "`noteSplashes/noteSplashes` on the chart's note splash skin, most likely because you got it from an old version, it shouldn't matter much though cuz it resets to the correct/default note splash if its missing

**Comment by 2JENO** [comment]
thank you for answer
