### ISSUE TITLE
note splash cant still not be addable

### ISSUE THREAD

**Issue by Bezizeja** [ShadowMario/FNF-PsychEngine#12857]
### What is your question?

so im trying to add a notesplash from andromeda engine that someone made for psych its still doesnt want to add it i only have 
: 
xml file 
and the sprite sheet

as it said that you can create text file from the editor but it doesn't load the image by itself

**Comment by SrBagel** [comment]
Make a text file called 'list.txt' and put it in the noteSplashes folder then add the note splash suffix to it noteSplashes-suffix open psych engine and go to options/visuals and ui set your note splash skin to the one you want to edit then press 7 on the main menu and go to note splash debug your note splashes should be there then enter the name of your splash animation and adjust the x and y values however you want

**Comment by YKoF-CALm** [comment]
Is this for source or for Lua?

**Comment by YKoF-CALm** [comment]
NVM, I figured it out.

**Comment by MemeHovy** [comment]
then close the issue

**Comment by YKoF-CALm** [comment]
> then close the issue

Psst, I wasn't the one opening the issue lmao.

**Comment by MemeHovy** [comment]
> > then close the issue
> 
> Psst, I wasn't the one opening the issue lmao.

neither was I referring to you
