### ISSUE TITLE
Credits in 0.7

### ISSUE THREAD

**Issue by phuctranz1039** [ShadowMario/FNF-PsychEngine#12856]
### What is your question?

How do i add my credits in 0.7? the mods/data/credits.txt doesnt work
![Ảnh chụp màn hình (10)](https://github.com/ShadowMario/FNF-PsychEngine/assets/137855931/348162f5-fe41-4a8d-b09c-3433189321d9)
![Ảnh chụp màn hình (9)](https://github.com/ShadowMario/FNF-PsychEngine/assets/137855931/2ac499f0-1612-4208-8ff8-567fa27dee7b)
![Ảnh chụp màn hình (11)](https://github.com/ShadowMario/FNF-PsychEngine/assets/137855931/819a2922-010e-46a5-a23b-d4aff171de38)

**Comment by ShadowMario** [comment]
Move it to `mods/Your-Mod-Name-Here/data/credits.txt`

**Comment by turtlethegamer** [comment]
I did the same aswell and it didnt work is this some sort of bug?
