### ISSUE TITLE
why i can't use pwd?

### ISSUE THREAD

**Issue by GatoMagoXD** [ShadowMario/FNF-PsychEngine#12854]
### What is your question?

i am trying to compile the psych engine with the file "built_x64" and this don't work for the command pwd
how i can use the command pwd?

**Comment by cardboardboxpepe** [comment]
`pwd` is a Linux command and doesn't exist on Windows. Try running the Windows specific scripts (anything that ends in .bat or .ps1)

**Comment by GatoMagoXD** [comment]
Thanks but I use the windows source, and y can conpile now the game

**Comment by GatoMagoXD** [comment]
Thanks but I use the windows source, and y can conpile now the game
