### ISSUE TITLE
I can play my week in 0.6.3 but can't in 0.7 (an error pops up)

### ISSUE THREAD

**Issue by BadWordGit** [ShadowMario/FNF-PsychEngine#12862]
### Describe your problem here.

I've been working on a mod basically rewriting the final songs of other week and putting them into one. When I ran my mod in 0.6.3 it worked perfectly fine but whenever i run it in 0.7 it pops up with this error:
![Screenshot 2023-07-26 122815](https://github.com/ShadowMario/FNF-PsychEngine/assets/134350668/22f23a46-b4eb-44ac-aa2e-10af49c6e033)

(For more info to better understand the error; I've added a video, followed by dialogue when the week begins. Ive remapped the notes and made a new sprite.)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
This error just, shouldn't be possible? FunkinLua only has 1658 lines when this error reports the problem at line 2831, PlayState is also not long enough for these errors to be valid

**Comment by BadWordGit** [comment]
Maybe that crash message is wrong, this is what actually pops up
![Screenshot 2023-07-26 122815](https://github.com/ShadowMario/FNF-PsychEngine/assets/134350668/163c054c-a75d-48e0-9baa-c7e1286f0fe1)
