### ISSUE TITLE
Remove rgbShader from my custom note?

### ISSUE THREAD

**Issue by TheRealPepsi** [ShadowMario/FNF-PsychEngine#12863]
### Describe your problem here.

Hey all, made a noteskin in 0.6.3, all worked fine, but it seems rgbShader messes with it. I tried this code from ShadowMario:

function onCountdownStarted()
    for i = 0, getProperty('unspawnNotes.length') - 1 do
        setPropertyFromGroup('unspawnNotes', i, 'rgbShader.enabled', false)
    end
end

but, that disabled all notehues. is there a way to disable it just for my custom note? 

Thanks!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

None

**Comment by ActualMandM** [comment]
You're forgetting to check for the note type:

```lua
if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'attackNote' then
			setPropertyFromGroup('unspawnNotes', i, 'rgbShader.enabled', false)
end
```

An example with [My Streets](https://gamebanana.com/mods/457142)'s attack note:
[attackNote.lua](https://github.com/ShadowMario/FNF-PsychEngine/files/12177134/attackNote.txt)
![2023-07-26_13-58-31_PsychEngine](https://github.com/ShadowMario/FNF-PsychEngine/assets/15317421/de7f5c74-4d93-4d21-a5d8-51552f780187)

**Comment by TheRealPepsi** [comment]
Worked like a charm! Thanks so much!
