### ISSUE TITLE
mod making

### ISSUE THREAD

**Issue by fffdsfdsfds** [ShadowMario/FNF-PsychEngine#12866]
### Describe your bug here.

i am a.. very inexperienced mod creator. ive made some impressive stuff now and then, but it wasnt without help of others.
Anyway, point here is, porting my mod has a lot of problems that are annoying.
I ported boiling point and added some bullet notes in there, but when i port it to 0.7, it just... crashes with no error..
ima attach a file to show what i mean

https://github.com/ShadowMario/FNF-PsychEngine/assets/134226764/b65daa26-d40c-4dd1-b389-ca4c20b94a74

this is quite annoying lol

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, im trying to port my mod (https://gamebanana.com/mods/446441)

**Comment by doom699** [comment]
this might get fixed, shadowmario trying to fix stuff as seen in commits, this should get fixed soon so dont worry
try using this. https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7
if not working u can stick to 0.6.3 until everything gets fixed

**Comment by fffdsfdsfds** [comment]
> this might get fixed, shadowmario trying to fix stuff as seen in commits, this should get fixed soon so dont worry try using this. https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7 if not working u can stick to 0.6.3 until everything gets fixed

hey wait where do i do this stuff

**Comment by doom699** [comment]
?

**Comment by fffdsfdsfds** [comment]
like, where do i do the changes in my mod

**Comment by doom699** [comment]
the lua scripts? well the link i gave u, change those lines to what it say
