### ISSUE TITLE
Custom Notes aren't displayed correctly

### ISSUE THREAD

**Issue by Unbekannnt0** [ShadowMario/FNF-PsychEngine#12861]
### Describe your bug here.

Currently, all Custom Notes are colored just like the normal notes, which is actually quite cool...

But they are also changed, if the colors are the normal ones, so the custom notes appear in a wrong color,
Is this intended? Is there any way to fix this? If yes, how?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
#12802
