### ISSUE TITLE
the update that just happened has really been screwy for me and im not sure why.

### ISSUE THREAD

**Issue by Griffinbackwords** [ShadowMario/FNF-PsychEngine#12869]
### Describe your problem here.

when i type lime test windows i get this error
 C:\Users\Griff\Desktop\FNF-PsychEngine-main\FNF-PsychEngine-
" main\source\import.hx:10: characters 8-16 : Type not found : llua.Lua "

and this error
" source/backend/Discord.hx:146: characters 45-50 : Type not found : State "

it looks like there is a issue with just the main source code but I could be wrong please point me in the right direction

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
Try doing this and tell me if it works:
`haxelib remove linc_luajit`
`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git`

**Comment by ShadowMario** [comment]
Closed from inactivity
