### ISSUE TITLE
keyJustPressed not working

### ISSUE THREAD

**Issue by SrBagel** [ShadowMario/FNF-PsychEngine#12867]
### What is your question?

I noticed that my scripts that have `if keyJustPressed('space')` no longer work. Was this changed?

**Comment by Drawoon2** [comment]
The Space was revome in this version for use it use `keyboardJustPressed("SPACE")`

**Comment by SrBagel** [comment]
> The Space was remove in this version for use it use `keyboardJustPressed("SPACE")`

Thank you
