### ISSUE TITLE
How do I make something wait?

### ISSUE THREAD

**Issue by ColdlordXRepositories** [ShadowMario/FNF-PsychEngine#12868]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/49921877/76d1b505-0a73-4da1-a810-0bab59cfa1f1)
I was making a note where if you hit it, the window will float away offscreen. It works, but it doesnt work.
Whenever I tried using a wait function in order to make the two tweens seperate, it didnt work.
Thats when i learned something, THERE IS NO WAIT FUNCTION. Not in this version of lua, anyway.
All of the other things said "use os.time" or something like that but you can't use os commands in funkinlua because of security risks?
Im confused. help.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ColdlordXRepositories** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/assets/49921877/c592894a-62d8-4e13-b373-c99f72513101

heres whats happening by the way

**Comment by frantastic24** [comment]
Use timers, you can run one from runHaxeCode or use [Lua functions](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers#runtimertagstring-timefloat--1-loopsint--1)

**Comment by ColdlordXRepositories** [comment]
> Use timers, you can run one from runHaxeCode or use [Lua functions](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers#runtimertagstring-timefloat--1-loopsint--1)

Thank you. You are a lifesaver.
