### ISSUE TITLE
help

### ISSUE THREAD

**Issue by fanproductions** [ShadowMario/FNF-PsychEngine#12879]
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/115906994/fb007ae6-bfa1-41da-9078-b0e479981632)

### Command Prompt/Terminal logs (if existing)

```bash
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
D:\Nova pasta\FNF-PsychEngine-0.6.3\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by CaptainBaldi** [comment]
stop reporting your inability to install proper dependency's as bugs
you need to install vs 2017 community

**Comment by fanproductions** [comment]
ok thanks and sorry
