### ISSUE TITLE
How Do I Fix This?

### ISSUE THREAD

**Issue by SuccvDucc** [ShadowMario/FNF-PsychEngine#12875]
### Describe your problem here.

source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Edited Project.xml to add Icon 24, 40, 48, 96, 128, 256, 512, 768

**Comment by Unbekannnt0** [comment]
This helped me:
just delete this code from the file

(originally said by [CrazyDany](https://github.com/CrazyDany) )

catch(e:Dynamic)
{
if(Lua_helper.sendErrorsToLua) {LuaL.error(l, 'CALLBACK ERROR! ${if(e.message != null) e.message else e}');return 0;}
trace(e);
throw(e);
}

**Comment by MemeHovy** [comment]
> This helped me: just delete this code from the file
> 
> (originally said by [CrazyDany](https://github.com/CrazyDany) )
> 
> catch(e:Dynamic) { if(Lua_helper.sendErrorsToLua) {LuaL.error(l, 'CALLBACK ERROR! ${if(e.message != null) e.message else e}');return 0;} trace(e); throw(e); }

yea but like, you can’t use try without catch

**Comment by MemeHovy** [comment]
okay nvm, turns out you can, but it’s not recommended

**Comment by lemonie1** [comment]
still cant fix
