### ISSUE TITLE
Transitioning my mod from 0.6.3 to 7.0 but fails to compile

### ISSUE THREAD

**Issue by BloodMoonDS** [ShadowMario/FNF-PsychEngine#12877]
### Describe your problem here.

I want to transfer my mod step-by-step to this new version but when I try to compile the new build with my icons this shows up in the output

source/states/PlayState.hx:61: characters 14-28 : Type not found : vlc.MP4Handler
source/states/PlayState.hx:844: characters 13-25 : Type not found : VideoHandler

What do I do? I ran <code> haxelib run hmm install </code> but still does not work what sould I install?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

icons 16 to 320

**Comment by biomseed** [comment]
i think you need to haxelib install hxCodec

**Comment by BloodMoonDS** [comment]
> I think you need to haxelib install hxCodec

I'm going to try it I'll tell you if it works

**Comment by biomseed** [comment]
> > I think you need to haxelib install hxCodec
> 
> I'm going to try it I'll tell you if it works

Try both the haxelib version and the git version.

**Comment by BloodMoonDS** [comment]
> > > I think you need to haxelib install hxCodec
> > 
> > 
> > I'm going to try it I'll tell you if it works
> 
> Try both the haxelib version and the git version.

The Git version Bumps this
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/71611133/784d751f-1872-43cf-b7bc-af00cc3348f4)
The Haxelib version bumps this
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/71611133/1fd5b424-2d15-4a55-8567-c4092b82b3d8)

I don't know what to do, Is there a specific version?

**Comment by biomseed** [comment]
> > > > I think you need to haxelib install hxCodec
> > > 
> > > 
> > > I'm going to try it I'll tell you if it works
> > 
> > 
> > Try both the haxelib version and the git version.
> 
> The Git version Bumps this ![image](https://user-images.githubusercontent.com/71611133/256643770-784d751f-1872-43cf-b7bc-af00cc3348f4.png) The Haxelib version bumps this ![image](https://user-images.githubusercontent.com/71611133/256643890-1fd5b424-2d15-4a55-8567-c4092b82b3d8.png)
> 
> I don't know what to do, Is there a specific version?

I'm not sure either. Try running the commands in the root directory of the source code if you aren't already. Other than that, I don't know much that can help you.

**Comment by BloodMoonDS** [comment]
> > > > > I think you need to haxelib install hxCodec
> > > > 
> > > > 
> > > > I'm going to try it I'll tell you if it works
> > > 
> > > 
> > > Try both the haxelib version and the git version.
> > 
> > 
> > The Git version Bumps this ![image](https://user-images.githubusercontent.com/71611133/256643770-784d751f-1872-43cf-b7bc-af00cc3348f4.png) The Haxelib version bumps this ![image](https://user-images.githubusercontent.com/71611133/256643890-1fd5b424-2d15-4a55-8567-c4092b82b3d8.png)
> > I don't know what to do, Is there a specific version?
> 
> I'm not sure either. Try running the commands in the root directory of the source code if you aren't already. Other than that, I don't know much that can help you.

Yes I tried that too I don't know what is going on there I'm always in the root folder so I don't know what is the issue

**Comment by biomseed** [comment]
> > > > > > I think you need to haxelib install hxCodec
> > > > > 
> > > > > 
> > > > > I'm going to try it I'll tell you if it works
> > > > 
> > > > 
> > > > Try both the haxelib version and the git version.
> > > 
> > > 
> > > The Git version Bumps this ![image](https://user-images.githubusercontent.com/71611133/256643770-784d751f-1872-43cf-b7bc-af00cc3348f4.png) The Haxelib version bumps this ![image](https://user-images.githubusercontent.com/71611133/256643890-1fd5b424-2d15-4a55-8567-c4092b82b3d8.png)
> > > I don't know what to do, Is there a specific version?
> > 
> > 
> > I'm not sure either. Try running the commands in the root directory of the source code if you aren't already. Other than that, I don't know much that can help you.
> 
> Yes I tried that too I don't know what is going on there I'm always in the root folder so I don't know what is the issue

https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions
The git version is the right version. Make sure to switch to it, just reminding you in case you forget.

**Comment by BloodMoonDS** [comment]
> 

Yes I switched to the git version
