### ISSUE TITLE
addittional // when compiling

### ISSUE THREAD

**Issue by Jesgran** [ShadowMario/FNF-PsychEngine#12871]
### Describe your problem here.

i'm tryng to make a android port of my mod and when i do 'lime build android' it build  it for a while then it gives me a error that is probably generated by a library error (i'm not sure) because this error:
![Schermata del 2023-07-27 09-51-15](https://github.com/ShadowMario/FNF-PsychEngine/assets/83729533/529311f3-709d-4cf1-a24b-8282640ed0ca)
i think it's a library error because as you can see it says linc_luajit/git//lib with 2 / i don't know if i can fix this by doing something in project.xml or while building

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

**Comment by ShadowMario** [comment]
linc_luajit can't run on Android, you can try removing it from `Project.xml` file on your source code
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/19154ec5-7293-4648-8a79-6b2e5b378106)

**Comment by Jesgran** [comment]
thanks it worked, i don't need lua but i have seen other ports support it
