### ISSUE TITLE
I was trying to compile when that happened, I'm stupid lol

### ISSUE THREAD

**Issue by Killerbrnow** [ShadowMario/FNF-PsychEngine#12876]
### Describe your problem here.
haxelib/SScript/4,0,0/src/macro/Macro.hx:46: characters 23-31 : Array<String> has no field 
contains

.haxelib/linc_luajit/git/llua/Convert.hx:92: characters 11-12 : Missing type declaration

### Are you modding a build from source or with Lua?

source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
Try the following:
`haxelib remove linc_luajit`
`haxelib git linc_luajit haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git`

Then tell me if your issue is fixed!

**Comment by Killerbrnow** [comment]
FNF-PsychEngine-0.7.1/.haxelib/SScript/4,0,0/src/macro/Macro.hx:46: characters 23-31 : Array<String> has no field contains
FNF-PsychEngine-0.7.1/.haxelib/linc_luajit/git/llua/Convert.hx:92: characters 11-12 : Missing type declaration

Same thing, nothing happened

**Comment by ShadowMario** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions
Check this page

**Comment by Killerbrnow** [comment]
IT WORKED!! but i got this now

Standard library not found. You may need to set your `HAXE_STD_PATH` environment variable

**Comment by Killerbrnow** [comment]
Obrigado mano!!!!!!!!
