### ISSUE TITLE
I keep getting this error when trying to do haxelib git polymod (0.7)

### ISSUE THREAD

**Issue by MitchyBo** [ShadowMario/FNF-PsychEngine#12873]
### Describe your bug here.

Whenever I try to do haxelib git polymod and authenticate it I have this error

### Command Prompt/Terminal logs (if existing)

```bash
Installing polymod from https://github.com/MasterEric/polymod.git
Error: Could not clone Git repository.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheLeerName** [comment]
what is polymod, psych not uses it

**Comment by SuperSabus21** [comment]
I wised some more clarification was in place in this chat.
