### ISSUE TITLE
Transition from 0.6.3 to 0.7.1 makes saving variables impossible?

### ISSUE THREAD

**Issue by KillerAvecRage** [ShadowMario/FNF-PsychEngine#12878]
### Describe your bug here.

Hello to anyone reading this, I've had a recent issue regarding saving variables using Lua.
For the 0.6.3 version of the engine, I've been using "initSaveData", "getDataFromSave", "setDataFromSave" and "flushSaveData" to save and reuse my variables in Lua. However, when transitioning to 0.7, the engine is unable to create the save file as I can't find it anywhere, has the keywords changed? If so, what are the new ones?

Thank you in advance for your answer.

~KillerAvecRage

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/103606542/50a2c392-dfc0-41f1-ba85-2e0220e20332)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/103606542/5a3c94bb-91ff-41de-bafa-7fafe8578473)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

-

**Comment by ShadowMario** [comment]
I don't think that's the issue, [my mod uses Save data](https://gamebanana.com/mods/458072), it's very likely that your script is either crashing before initializing the save data, or you are not flushing to save it: `flushSaveData('KARHudConfigSaveFile')`

**Comment by KillerAvecRage** [comment]
Oh yeah it is working now, well okay, good
