### ISSUE TITLE
I'm having a bit of trouble with timers and stuff

### ISSUE THREAD

**Issue by ColdlordXRepositories** [ShadowMario/FNF-PsychEngine#12888]
### Describe your problem here.
**please continue the discussion following the comments the code here is not what i have now**
honestly, I don't know what to do. I can't code, and I'm just trying to make a mechanic.
Code, in plain text because github is weird:
function onCreate()
	addHaxeLibrary('Application', 'lime.app')
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'WindowNote' then  --Checks if the note is the one in the script. Set this to the name of your file.
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'WindowNote'); --Changes the texture to your own
			setPropertyFromGroup('unspawnNotes', i, 'hitHealth', '0'); --Default is 0.023, sets the value you get on hit
			setPropertyFromGroup('unspawnNotes', i, 'missHealth', '0'); --Default is 0.0475, sets the value you get on miss
			setPropertyFromGroup('unspawnNotes', i, 'hitCausesMiss', false);

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true); --Miss has no penalties
			end
		end
	end
end

-- Function called when you hit a note (after note hit calculations)
-- id: The note member id, you can get whatever variable you want from this note, example: "getPropertyFromGroup('notes', id, 'strumTime')"
-- noteData: 0 = Left, 1 = Down, 2 = Up, 3 = Right
-- noteType: The note type string/tag
-- isSustainNote: If it's a hold note, can be either true or false
function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'WindowNote' then
		runHaxeCode([[
    FlxTween.tween(Application.current.window, { x: 320, y: 1080 }, 0.9, { ease: FlxEase.CubeIn})
]])
function runTimer("lol", 2, 1)
	end
	function onTimerCompleted("lol", 1, 0)
		runHaxeCode([[
    FlxTween.tween(Application.current.window, { x: 320, y: 180 }, 0.7, { ease: FlxEase.CubeOut})
]])
	    end
	end
end

-- Called after the note miss calculations
-- Player missed a note by letting it go offscreen
function noteMiss(id, noteData, noteType, isSustainNote)
	if noteType == 'WindowNote' then
		-- put something here if you want
	end
end
![Screenshot 2023-07-27 185837](https://github.com/ShadowMario/FNF-PsychEngine/assets/49921877/b8de23f5-6fc3-47ed-a26c-987813ba5901)
My goal here is to make a mechanic where if you press a note, the game window will float offscreen for one second. The timer is meant to make sure the two different tweens don't happen at once.
I don't know if I'm doing timers right, i assume im doing them terribly wrong, but i dont know anymore. I can't figure out what the error is trying to tell me.
The formatting fucked up on this post. Sorry, just try to read the code as best as you can.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ColdlordXRepositories** [comment]
UPDATE: I used the funkin script autocompleter to get a slightly better script, and what do you know, I have the same error.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/49921877/721c2ca8-724f-4d28-8a8d-c533e74f34e1)
i dont think im doing this wrong.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/49921877/b8315470-c670-4f35-abb6-c3b3a25667e6)

**Comment by KillerAvecRage** [comment]
"runTimer" is not a function and the "onTimerCompleted" function is not used correctly, here is the part of the wiki that shows you how to use a timer:

runTimer(tag:String, time:Float = 1, loops:Int = 1)

Runs a timer with a determined duration and loops count.

Calling this function will cancel another timer that is using the same tag!

    tag - Once the timer is finished, it will do a callback of onTimerCompleted(tag, loops, loopsLeft)
    time - Optional value, how much time it takes to finish a loop. Default value is 1
    loops - Optional value, how much loops should it do, if it's set to 0, it will repeat indefinitely. Default value is 1


And here is a part of the example script for lua explaining how "onTimerCompleted" works:

function onTimerCompleted(tag, loops, loopsLeft)
	-- A loop from a timer you called has been completed, value "tag" is it's tag
	-- loops = how many loops it will have done when it ends completely
	-- loopsLeft = how many are remaining
end

And an example of how both are used:

function onCreate()
runTimer('Timer1', 1)
end

function onTimerCompleted(tag, loops, loopsLeft)
if tag == 'Timer1' then
debugPrint('I love bricks')
end
end

Hope that helped!

**Comment by ColdlordXRepositories** [comment]
> "runTimer" is not a function and the "onTimerCompleted" function is not used correctly, here is the part of the wiki that shows you how to use a timer:
> 
> runTimer(tag:String, time:Float = 1, loops:Int = 1)
> 
> Runs a timer with a determined duration and loops count.
> 
> Calling this function will cancel another timer that is using the same tag!
> 
> ```
> tag - Once the timer is finished, it will do a callback of onTimerCompleted(tag, loops, loopsLeft)
> time - Optional value, how much time it takes to finish a loop. Default value is 1
> loops - Optional value, how much loops should it do, if it's set to 0, it will repeat indefinitely. Default value is 1
> ```
> 
> And here is a part of the example script for lua explaining how "onTimerCompleted" works:
> 
> function onTimerCompleted(tag, loops, loopsLeft) -- A loop from a timer you called has been completed, value "tag" is it's tag -- loops = how many loops it will have done when it ends completely -- loopsLeft = how many are remaining end
> 
> And an example of how both are used:
> 
> function onCreate() runTimer('Timer1', 1) end
> 
> function onTimerCompleted(tag, loops, loopsLeft) if tag == 'Timer1' then debugPrint('I love bricks') end end
> 
> Hope that helped!

I understand it pretty well now! but I'm getting an error saying
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/49921877/cae8cb30-2ff5-4e52-9d72-64efeef5451b)

My code:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/49921877/4098735f-7859-493d-aa48-cb8756e6a178)
Thanks for the help!
