### ISSUE TITLE
Apparently release 0.7.1 isn't actually 0.7.1, but 0.7

### ISSUE THREAD

**Issue by biomseed** [ShadowMario/FNF-PsychEngine#12880]
### Describe your bug here.

When I enter the 0.7.1 release build, the screen showing that your version is outdated shows up, and says that I am on 0.7, and 0.7.1 is the latest version. Nothing in it has changed at all, none of the features listed have showed up in the game. I think you may have accidentally published 0.7.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by TheKAPtain313** [comment]
I have the same prob

**Comment by biomseed** [comment]
The actions build works fine and shows 0.7.1 as the version.

**Comment by TheLeerName** [comment]
bro uploaded 0.7 version as 0.7.1 ☠

**Comment by ShadowMario** [comment]
I uploaded the wrong version out of a rush, oops
