### ISSUE TITLE
Weird Lua error?

### ISSUE THREAD

**Issue by CaptainBaldi** [ShadowMario/FNF-PsychEngine#12885]
### Describe your bug here.

When using a `runHaxeCode` instance in a Lua script, it gives me the error `CALLBACK ERROR! Null Object Reference`. The actual piece of code runs fine, but this error stops everything after the `runHaxeCode` from running if it's in the same function as it.

version is 0.7.1

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing through source.

**Comment by ShadowMario** [comment]
Should be fixed on the latest commits, please check it out

**Comment by CaptainBaldi** [comment]
> Should be fixed on the latest commits, please check it out

Seems to work now, thanks!
