### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by arandomkid1** [ShadowMario/FNF-PsychEngine#12884]
### Describe your bug here.

i was trying to compile then i got this
![Screenshot 2023-07-27 170423](https://github.com/ShadowMario/FNF-PsychEngine/assets/84911829/52b58ddb-ca6f-4da3-93c4-bda0830d5414)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No i did not.

**Comment by CyndaquilDAC** [comment]
I'm getting the same errors, worked fine before but I reinstalled all my haxe stuff to get up to date and now im getting these same ones
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/65635932/8a755b0a-a232-42c0-b63c-7e6099007f04)

**Comment by CyndaquilDAC** [comment]
Just tried downgrading lime incase that was the issue, it's not. help would be seriously appreciated, I can't compile any psych engine now

**Comment by CyndaquilDAC** [comment]
figured out the issue, downgraded lime to 8.0.1 and downgraded haxe to 4.2.5

**Comment by Gabo137** [comment]
I had the time to fix the errors of 0.7.X with the latest version of the libraries and Haxe.
Now it works correctly.
Soon I will send a repository of each fixed library
