### ISSUE TITLE
Transitioning 0.6.3 code to 0.7

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#12883]
### Describe your problem here.

Ok, so. I need help transitioning code for songPos into 0.7 because the source code rework apparently broke songPos completely.

for those that don't understand, songPos is usually written like this in lua: `songPos = getPropertyFromClass('Conductor', 'songPosition');` It basically makes everything tick. but with 0.7's rework update, that completely broke songPos.

if you don't believe me, try it yourself! and see that it doesnt work anymore.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope!

**Comment by BeastlyGhost** [comment]
replace `Conductor` with `backend.Conductor`, I recommend looking at the new source folder as everything on it changed so you need to adjust your code to fit the new folder structure

**Comment by fnfdemonboi314159** [comment]
> replace `Conductor` with `backend.Conductor`, I recommend looking at the new source folder as everything on it changed so you need to adjust your code to fit the new folder structure

thanks!

**Comment by Casius0810** [comment]
> replace `Conductor` with `backend.Conductor`, I recommend looking at the new source folder as everything on it changed so you need to adjust your code to fit the new folder structure

you are a life saver!
