### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by TheKAPtain313** [ShadowMario/FNF-PsychEngine#12881]
### Describe your bug here.

I updated to 7.0.1 but it still says that im running 7.0 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by biomseed** [comment]
There is no version called 7.0. There is no version called 7.0.1. We're still on the 0.x.x versions.

**Comment by CaptainBaldi** [comment]
shadowmario wtf :sob:

**Comment by TheKAPtain313** [comment]
> There is no version called 7.0. There is no version called 7.0.1. We're still on the 0.x.x versions.
im srry i did not know

**Comment by TheKAPtain313** [comment]
> There is no version called 7.0. There is no version called 7.0.1. We're still on the 0.x.x versions.
srry i did not know
