### ISSUE TITLE
Attempting to use a 0.7.1 chart in 0.6.3 results in an error

### ISSUE THREAD

**Issue by N30117** [ShadowMario/FNF-PsychEngine#12895]
### Describe your bug here.

Ditto to the title; here's the error.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/89752050/fd91a74c-8546-4089-8139-122ae10823b6)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope, fresh 0.6.3 build i was gonna use for a mod before 0.7 released

**Comment by CaptainBaldi** [comment]
probably something to do with the new data section in the chart, this doesnt really deserve a bug report, of course eventually backporting is going to cause some issue

**Comment by N30117** [comment]
> probably something to do with the new data section in the chart, this doesnt really deserve a bug report, of course eventually backporting is going to cause some issue

ah ok thanks!
