### ISSUE TITLE
I'm trying to add sprites and icons but nothing is changing.

### ISSUE THREAD

**Issue by Spensem** [ShadowMario/FNF-PsychEngine#12891]
### Describe your problem here.

Ok, so i'm trying to add my BF Sprites and icon into my mod. But when i go into the songs or anything. It changes nothing, I have been struggling to try to figure it out but i just cant. 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Spensem** [comment]
Oh Guys, i figured it out

**Comment by MemeHovy** [comment]
then close the issue
