### ISSUE TITLE
0.7.1 shaders not working

### ISSUE THREAD

**Issue by lazyremixmanordummyplayinggmod** [ShadowMario/FNF-PsychEngine#12897]
### Describe your bug here.

shaders just don't work at all

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by CaptainBaldi** [comment]
this isnt true but ok

**Comment by ShadowMario** [comment]
I'm using Shaders on a lua mod here, so i don't think that's the issue

**Comment by HappyAlexRomania** [comment]
I have the same issue. When I load a song, the game just crashes
