### ISSUE TITLE
0.7.1 Update breaks my mod entirely

### ISSUE THREAD

**Issue by void-needs-help** [ShadowMario/FNF-PsychEngine#12892]
### Describe your problem here.

Whenever I load the PsychEngine.exe the entire mod just breaks entirely.
gives the error "Could not load module lime@lime_application_create_prime

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64
[PsychEngine_2022-07-29_16'14'10.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/12189851/PsychEngine_2022-07-29_16.14.10.txt)

### Did you edit anything in this build? If so, mention or summarize your changes.

just a mods folder in /mods named Funkin' With Pibby

**Comment by mcagabe19** [comment]
``lime.ndll`` is corrupted or a lime issue

**Comment by KillerAvecRage** [comment]
The crash log you sent seems to show a missing json file in data/make-the-change

**Comment by lazyremixmanordummyplayinggmod** [comment]
wait for 0.7.1h or 0.7.2    0.7.1 is a mess

**Comment by lazyremixmanordummyplayinggmod** [comment]
stick with 0.7

**Comment by ShadowMario** [comment]
On the crash log you sent, it says file `data/make-the-change/make-the-change-vip.json` seems to be missing

**Comment by void-needs-help** [comment]
nah i accidentally used the x32 build while i was on x64.
