### ISSUE TITLE
In-Song videos crashing game

### ISSUE THREAD

**Issue by ninjaninja140** [ShadowMario/FNF-PsychEngine#12898]
### Describe your bug here.

Playing mods on psych (obviously) when loading up songs with videos at the start of the song (eg, interstellar and elude from suspicious funkin) the game just crashes, no logs or anything, just straight up closes the game with no like crash report thing at all.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Updated from 6.3 to 7 then 7 to 7.1 via just doing replace all

**Comment by biomseed** [comment]
0.7 isn't meant to be fully backwards compatible with 0.6.3 mods, so you should probably look [here](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7) to see what the issue could be

**Comment by ninjaninja140** [comment]
> 0.7 isn't meant to be fully backwards compatible with 0.6.3 mods, so you should probably look [here](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7) to see what the issue could be

oh thanks
