### ISSUE TITLE
i think HScript is bugged or something

### ISSUE THREAD

**Issue by Anoyinguser** [ShadowMario/FNF-PsychEngine#12902]
### Describe your problem here.

source/psychlua/FunkinLua.hx:58: characters 21-28 : Type not found : HScript

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No :'

**Comment by TheLeerName** [comment]
package `psychlua.HScript`

**Comment by mcagabe19** [comment]
keep your source updated

**Comment by CaptainBaldi** [comment]
import HScript :ox:

**Comment by Anoyinguser** [comment]
package psychlua.HScript where do I put it? @TheLeerName
