### ISSUE TITLE
Fixing a camera to a specific point in 0.7.x

### ISSUE THREAD

**Issue by VoidedBattery** [ShadowMario/FNF-PsychEngine#12907]
### Describe your bug here.

In version 0.7.x, I'm trying to set `camGame`'s position to a singular point. I'm not talking about the "Set cam position" event but something via script that sets it instantly to a singular point and keeps it there.

I'm doing this by attaching `setProperty('camGame.scroll.x', value)` to `onUpdate()`, but the camera jitters whenever it tries to focus on another position (I've tried it with `onUpdatePost()` too). This might be a bug where the .lua script sees a delay in `camGame.scroll`, but otherwise worked perfectly with `camFollowPos` in older 0.6.x versions.

Below is a diagram of what happens when I use `getProperty('camGame.scroll')` on a sprite, showing the "delay":
![diagram](https://github.com/ShadowMario/FNF-PsychEngine/assets/101370598/0299c900-b7dc-456c-9512-9410f0a8c56d)

Any help working around this situation (applying `setProperty('camGame.scroll.x', value)` to an onUpdate() and or onUpdatePost() without the jitter) is appreciated.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
same issue here

**Comment by RodneyAnImaginativePerson** [comment]
the wiki tells you how to fix this

**Comment by RodneyAnImaginativePerson** [comment]
like the actual psych wiki

**Comment by RodneyAnImaginativePerson** [comment]
[https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7)

**Comment by VoidedBattery** [comment]
> the wiki tells you how to fix this

I did what they said and used `camGame.scroll` as they specified, it was said in the issue
It results with a shaky screen like i mentioned, and delays its output if you apply it to a sprite

**Comment by ActualMandM** [comment]
does `setProperty('isCameraOnForcedPos', true);` not work in this case?

**Comment by CaptainBaldi** [comment]
if this isnt just human error, isnt this more of a Flixel issue? `.scroll` isnt developed by ShadowMario, its originally from HaxeFlixel

**Comment by VoidedBattery** [comment]
> does `setProperty('isCameraOnForcedPos', true);` not work in this case?

Yes, it does not. It only keeps the camera's target position at one spot permanently, and even then there's still no workaround for the "delayed camGame.scroll" part playing on the Luas

**Comment by VoidedBattery** [comment]
> if this isnt just human error, isnt this more of a Flixel issue? `.scroll` isnt developed by ShadowMario, its originally from HaxeFlixel

Most likely, but the way it is sent to the .lua files could be most likely

**Comment by VoidedBattery** [comment]
Okay, I figured it out for myself and got it fixed in this way:

I set the camera's followLerp to 0 to prevent it from "resisting" whenever the camera's being set
`setPropertyFromClass('flixel.FlxG', 'camera.followLerp', 0)`
After that, I set the camera position artificially to a sprite, mimicking the camera movement closely
From there I use the sprite's x and y coordinates to apply it to other objects, working just fine
