### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by 1MFunnyThingsYT** [ShadowMario/FNF-PsychEngine#12905]
### Describe your problem here.

I tried compiling my mod but i got this error: 
D:\FNF\projects\Object Funkin\FNF-PsychEngine-0.7.1-Source\FNF-PsychEngine-0.7.1>lime test windows
D:/FNF/projects/Object Funkin/FNF-PsychEngine-0.7.1-Source/FNF-PsychEngine-0.7.1/.haxelib/linc_luajit/git/llua/State.hx:11: characters 24-49 : You cannot access the cpp package while in a macro (for cpp.RawPointer)
D:/FNF/projects/Object Funkin/FNF-PsychEngine-0.7.1-Source/FNF-PsychEngine-0.7.1/.haxelib/linc_luajit/git/llua/Lua.hx:4: characters 8-18 : ... referenced here
D:\FNF\projects\Object Funkin\FNF-PsychEngine-0.7.1-Source\FNF-PsychEngine-0.7.1\source\import.hx:10: characters 8-16 : ... referenced here
D:\FNF\projects\Object Funkin\FNF-PsychEngine-0.7.1-Source\FNF-PsychEngine-0.7.1\source\import.hx:4: characters 8-23 : ... referenced here
D:\FNF\projects\Object Funkin\FNF-PsychEngine-0.7.1-Source\FNF-PsychEngine-0.7.1\.haxelib\lime\8,0,2/src/lime/media/AudioSource.hx:138: characters 53-100 : ... referenced here
D:/FNF/projects/Object Funkin/FNF-PsychEngine-0.7.1-Source/FNF-PsychEngine-0.7.1/.haxelib/openfl/9,2,2/src/openfl/media/Sound.hx:14: characters 8-30 : ... referenced here
D:/FNF/projects/Object Funkin/FNF-PsychEngine-0.7.1-Source/FNF-PsychEngine-0.7.1/.haxelib/openfl/9,2,2/src/openfl/utils/Assets.hx:9: characters 8-26 : ... referenced here
D:/FNF/projects/Object Funkin/FNF-PsychEngine-0.7.1-Source/FNF-PsychEngine-0.7.1/.haxelib/openfl/9,2,2/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here
D:/FNF/projects/Object Funkin/FNF-PsychEngine-0.7.1-Source/FNF-PsychEngine-0.7.1/.haxelib/openfl/9,2,2/src/openfl/text/_internal/TextEngine.hx:9: characters 8-24 : ... referenced here
D:/FNF/projects/Object Funkin/FNF-PsychEngine-0.7.1-Source/FNF-PsychEngine-0.7.1/.haxelib/openfl/9,2,2/src/openfl/display/_internal/CairoTextField.hx:3: characters 8-40 : ... referenced here
D:/FNF/projects/Object Funkin/FNF-PsychEngine-0.7.1-Source/FNF-PsychEngine-0.7.1/.haxelib/openfl/9,2,2/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here
D:/FNF/projects/Object Funkin/FNF-PsychEngine-0.7.1-Source/FNF-PsychEngine-0.7.1/.haxelib/openfl/9,2,2/src/openfl/display/_internal/CairoGraphics.hx:6: characters 8-36 : ... referenced here
D:/FNF/projects/Object Funkin/FNF-PsychEngine-0.7.1-Source/FNF-PsychEngine-0.7.1/.haxelib/openfl/9,2,2/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
D:/FNF/projects/Object Funkin/FNF-PsychEngine-0.7.1-Source/FNF-PsychEngine-0.7.1/.haxelib/openfl/9,2,2/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
D:/FNF/projects/Object Funkin/FNF-PsychEngine-0.7.1-Source/FNF-PsychEngine-0.7.1/.haxelib/openfl/9,2,2/src/openfl/events/RenderEvent.hx:4: characters 8-44 : ... referenced here
D:/FNF/projects/Object Funkin/FNF-PsychEngine-0.7.1-Source/FNF-PsychEngine-0.7.1/.haxelib/openfl/9,2,2/src/openfl/display/DisplayObject.hx:13: characters 8-33 : ... referenced here
D:/FNF/projects/Object Funkin/FNF-PsychEngine-0.7.1-Source/FNF-PsychEngine-0.7.1/.haxelib/openfl/9,2,2/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
D:/FNF/projects/Object Funkin/FNF-PsychEngine-0.7.1-Source/FNF-PsychEngine-0.7.1/.haxelib/openfl/9,2,2/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
D:\FNF\projects\Object Funkin\FNF-PsychEngine-0.7.1-Source\FNF-PsychEngine-0.7.1\.haxelib\lime\8,0,2/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
D:\FNF\projects\Object Funkin\FNF-PsychEngine-0.7.1-Source\FNF-PsychEngine-0.7.1\.haxelib\lime\8,0,2/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
D:\FNF\projects\Object Funkin\FNF-PsychEngine-0.7.1-Source\FNF-PsychEngine-0.7.1\.haxelib\lime\8,0,2/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
D:\FNF\projects\Object Funkin\FNF-PsychEngine-0.7.1-Source\FNF-PsychEngine-0.7.1\.haxelib\lime\8,0,2/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
D:\FNF\projects\Object Funkin\FNF-PsychEngine-0.7.1-Source\FNF-PsychEngine-0.7.1\.haxelib\lime\8,0,2/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
D:\FNF\projects\Object Funkin\FNF-PsychEngine-0.7.1-Source\FNF-PsychEngine-0.7.1\.haxelib\lime\8,0,2/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
D:\FNF\projects\Object Funkin\FNF-PsychEngine-0.7.1-Source\FNF-PsychEngine-0.7.1\.haxelib\lime\8,0,2/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
D:\FNF\projects\Object Funkin\FNF-PsychEngine-0.7.1-Source\FNF-PsychEngine-0.7.1\.haxelib\lime\8,0,2/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
D:\FNF\projects\Object Funkin\FNF-PsychEngine-0.7.1-Source\FNF-PsychEngine-0.7.1\.haxelib\lime\8,0,2/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
D:\FNF\projects\Object Funkin\FNF-PsychEngine-0.7.1-Source\FNF-PsychEngine-0.7.1\.haxelib\lime\8,0,2/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
D:\FNF\projects\Object Funkin\FNF-PsychEngine-0.7.1-Source\FNF-PsychEngine-0.7.1\.haxelib\lime\8,0,2/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
D:\FNF\projects\Object Funkin\FNF-PsychEngine-0.7.1-Source\FNF-PsychEngine-0.7.1\.haxelib\lime\8,0,2/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
D:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here

Can someone help me?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by Seleverlol** [comment]
i recommend compiling and using !0.7! and taking the instructions from this link, it helped me https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by 1MFunnyThingsYT** [comment]
> i recommend compiling and using !0.7! and taking the instructions from this link, it helped me https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

I tried that but same thing

**Comment by Alex347XD** [comment]
im having the same issue.

**Comment by Alex347XD** [comment]
i fixed it. you need to use lime 8.0.2 and [haxe 4.2.5](https://haxe.org/download/version/4.2.5/)

haxelib set lime 8.0.2

**Comment by 1MFunnyThingsYT** [comment]
> i fixed it. you need to use lime 8.0.2 and [haxe 4.2.5](https://haxe.org/download/version/4.2.5/)
> 
> haxelib set lime 8.0.2

I did both steps and still didn't work

**Comment by Gabo137** [comment]
Tomorrow I'll send you the repositories I made, fix all those errors.
It took me two hours to fix *suffering*

**Comment by 1MFunnyThingsYT** [comment]
> Tomorrow I'll send you the repositories I made, fix all those errors. It took me two hours to fix _suffering_

So, when that gonna happen?
