### ISSUE TITLE
Error compiling. Please Help

### ISSUE THREAD

**Issue by Alex347XD** [ShadowMario/FNF-PsychEngine#12901]
### Describe your problem here.

i keep getting this error when compiling
```
source/states/PlayState.hx:51: characters 33-53 : Type not found : hxcodec.VideoHandler
C:/Users/MYNAME/Downloads/FNF-PsychEngine-52f898223acf3c94be50a794b10f23a7e677929e/.haxelib/flixel/5,2,2/flixel/FlxG.hx:3: characters 8-17 : You cannot access the flash package while in a macro (for flash.Lib)
```
i fixed that but now i am getting this error
`C:/Users/MYNAME/Downloads/FNF-PsychEngine-main/.haxelib/linc_luajit/git/llua/State.hx:11: characters 24-49 : You cannot access the cpp package while in a macro (for cpp.RawPointer)`
please help me

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i edited TitleState to make the intro last 17 seconds.

**Comment by biomseed** [comment]
The videohandler error seems to not be related with TitleState, so you should fix whatever that is. Other than that, the other error is with haxeflixel itself, not anything with Psych engine

**Comment by Alex347XD** [comment]
> The videohandler error seems to not be related with TitleState, so you should fix whatever that is. Other than that, the other error is with haxeflixel itself, not anything with Psych engine

do you know how to fix the videohandler issue?

**Comment by biomseed** [comment]
> do you know how to fix the videohandler issue?

nah

**Comment by mcagabe19** [comment]
update your source and https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by Alex347XD** [comment]
> update your source and https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

ill try this thanks

**Comment by Alex347XD** [comment]
> update your source and https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

now im getting this error 
`C:/Users/MYNAME/Downloads/FNF-PsychEngine-main/.haxelib/linc_luajit/git/llua/State.hx:11: characters 24-49 : You cannot access the cpp package while in a macro (for cpp.RawPointer)`
