### ISSUE TITLE
Where are HX files supposed to go?

### ISSUE THREAD

**Issue by deco1212** [ShadowMario/FNF-PsychEngine#12900]
### Describe your problem here.

Im trying to make a Kade Engine styled Psych Engine using 0.7.1, im confused on what folder to put it in, infact, theres no HX folder.
Can someone help me with that?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by lazyremixmanordummyplayinggmod** [comment]
they are the same as lua but just sscript
