### ISSUE TITLE
editor feature idea for splash debug

### ISSUE THREAD

**Issue by Bezizeja** [ShadowMario/FNF-PsychEngine#12909]
### What feature do you want to get added on the **base** engine?

makes us choose a path where we can choose to save them either on a selected mod folder or in psych shared path to work globaly cuz im trying to add a splash and it shows flixel logo in the editor (i have splash notes files inside psych assets) so it would work with other mods

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by ShadowMario** [comment]
1. Invalid due to you failing the sight and reliability test
2. It is not an editor, it's just a relatively simpler **debug** menu, so it just is able to change the selected note splash
3. You gotta make your mod a Global mod if you want to load note splashes
