### ISSUE TITLE
I GOT AN ERROR ON VERSION 0.7 AND IM DUMB SO I BEG FOR YOUR HELP

### ISSUE THREAD

**Issue by StickyBeets** [ShadowMario/FNF-PsychEngine#12917]
### Describe your bug here.

I got an error about the video handler or smth

### Command Prompt/Terminal logs (if existing)

```bash
source/states/PlayState.hx:63: characters 14-30 : Type not found : vlc.VideoHandler
source/states/PlayState.hx:778: characters 13-25 : Type not found : VideoHandler
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by StickyBeets** [comment]
I think fixed it

**Comment by WolfyTail** [comment]
How
