### ISSUE TITLE
How in the wiener blasting shit can I fix this?

### ISSUE THREAD

**Issue by theblobbyman13** [ShadowMario/FNF-PsychEngine#12911]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/136876636/8b27d6ba-c5a7-4e8b-8a75-83f084832e70)
when I load this script (code below)

function onCreate()
	runHaxeCode([[
    FlxG.cameras.remove(game.camOther,false);
	FlxG.cameras.remove(game.camHUD,false);
	var CamStrum:FlxCamera =new FlxCamera();
	CamStrum.bgColor=0x00;
 
	setVar("CamStrum",CamStrum);
	FlxG.cameras.add(game.camHUD,false);
    FlxG.cameras.add(CamStrum,false);
    FlxG.cameras.add(game.camOther,false);
    ]])
    end

function onCreatePost()
	runHaxeCode([[
		game.strumLineNotes.camera = getVar("CamStrum");
		game.grpNoteSplashes.camera = getVar("CamStrum");
		game.notes.camera = getVar("CamStrum");
	]])
end

my game crashes
how can I fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by ShadowMario** [comment]
runHaxeCode is currently not working properly on 0.7.1 due to a last minute change

**Comment by theblobbyman13** [comment]
> 

Understandable, I will now close this now
