### ISSUE TITLE
WHEN I TRY TO COMPILE THE GAME I GET STUCK AT : Link: ApplicationMain.exe    Creating library ApplicationMain.lib and object ApplicationMain.exp

### ISSUE THREAD

**Issue by StickyBeets** [ShadowMario/FNF-PsychEngine#12920]
### Describe your problem here.

Link: ApplicationMain.exe
   Creating library ApplicationMain.lib and object ApplicationMain.exp

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by aless26pic** [comment]
what time do you wait
