### ISSUE TITLE
how to change the ui zoom

### ISSUE THREAD

**Issue by George08091** [ShadowMario/FNF-PsychEngine#1292]
### Describe your problem here.

![EBA59642-D5E3-496E-9D37-CCF476D178FA](https://user-images.githubusercontent.com/39782649/142991473-201a4460-f40c-4efb-8fe1-b3ec2b789338.png)

I’m trying to have the UI (notes, health, stats n stuff) go into the ‘discord screenshare’ 
like so;

![0E934BE0-156A-4753-BBE1-70BC588A468B](https://user-images.githubusercontent.com/39782649/142991656-8d275ac7-1892-412e-9fd0-06d31a72813f.png)
 
I’m able to kind of do this with add camera zoom but it simply goes away right after a character sings. Would I have to switch to source to do this or is there a way with lua?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by SrtHero278** [comment]
I haven't used this before but try using doTweenZoom(tag:String, vars:String, value:Dynamic, duration:Float, ease:String)
Go to the wiki for more info.
