### ISSUE TITLE
Crashing when i restart a song

### ISSUE THREAD

**Issue by fox-64** [ShadowMario/FNF-PsychEngine#12926]
### Describe your bug here.

Idk why but everytime i restart a song or replay it the game crashes 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by biomseed** [comment]
Finally someone who uses the bug label properly

**Comment by CaptainBaldi** [comment]
> Finally someone who uses the bug label properly

not exactly, as this very clearly isnt a global problem, i can restart and replay songs fine
this needs more information, youre not even giving the crash error

**Comment by fox-64** [comment]
> > Finally someone who uses the bug label properly
> 
> not exactly, as this very clearly isnt a global problem, i can restart and replay songs fine
> this needs more information, youre not even giving the crash error

I will download a new build amd see what happens
