### ISSUE TITLE
Game crashing upon trying to open charting menu

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#12932]
### Describe your bug here.

I played on Week 6 songs (Senpai and Roses maybe Thorns is affected too) sometimes, no always, sometimes when I press 7 to open the charting menu, the game just crashes with this message (see attached image below)
I played on Hard, Freeplay and only have a different pixel-gf and pixel-bf used, which should not have any effect though
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/76132257/1413f464-3e13-467a-a89c-63e5c34d13fe)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not via source

**Comment by biomseed** [comment]
>sometimes, no always, sometimes
Did you mean "not always"?
