### ISSUE TITLE
Move combo in 0.7.1

### ISSUE THREAD

**Issue by Kirsenal** [ShadowMario/FNF-PsychEngine#12933]
### Describe your problem here.

Hello so I recently opened an issue on how to move where the combo appears for a song. I was helped kindly and found that 

function onCreate()
setPropertyFromClass('ClientPrefs', 'comboOffset', {600, -300, 600, -300}) getPropertyFromClass('ClientPrefs', 'comboOffset')
end

worked to move it. However, now in the newer version this script doesn't seem to work and the combo stays default. I'm wondering maybe if just one of the variables' name changed, but I have a hard time finding variable names and was wondering if someone could help me pull this off with the newer version.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
`ClientPrefs` should now be referred to as `backend.ClientPrefs` and `comboOffset` should now be referred to as `data.comboOffset`, if that var hasn't had it's name changed anyways

**Comment by Kirsenal** [comment]
> `ClientPrefs` should now be referred to as `backend.ClientPrefs` and `comboOffset` should now be referred to as `data.comboOffset`, if that var hasn't had it's name changed anyways

thank you, you are a lifesaver
