### ISSUE TITLE
My character's scaling is smaller when playing a song.

### ISSUE THREAD

**Issue by rschoolu** [ShadowMario/FNF-PsychEngine#12930]
### Describe your problem here.

I don't know what's happening, but the character editor or the character during a song is incorrectly displaying my character.
When I first open character editor and select my character and do NOTHING ELSE, it reflects the one during gameplay.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/107159650/6454d9f5-8253-4771-bcec-56e440b3cae6)
but as soon as I change the scale it changes drastically.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/107159650/72048424-01a3-4178-8b27-5ed1ac5d17c2)
I have tried editing my character several times but it still is broken. I don't know what's going on.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I don't really know what this means, but I didn't edit any of the source code.

**Comment by aless26pic** [comment]
take dad fla for do the scaling

**Comment by rschoolu** [comment]
> take dad fla for do the scaling

Thank you! I will try that out.

**Comment by aless26pic** [comment]
it work ?

**Comment by rschoolu** [comment]
I'm lazy but I remembered I used other characters to make my own and it worked so yea it would but i'm just lazy lol
