### ISSUE TITLE
Dialogue Enhancements

### ISSUE THREAD

**Issue by Haano137** [ShadowMario/FNF-PsychEngine#1293]
### What feature do you want to get added on the base engine?

- Neutral dialogue box. It would be a dialogue box that has no direction, which could be used for narration dialogue.

- A loop and no-loop checkbox for speaking and idle dialogue portraits.

- An option to hide the dialogue box and/or portraits in certain parts of the dialogue.

- Custom dialogue box skin support.

(all of these features were suggested with lua mod support in mind)

**Comment by dum-du-m** [comment]
im pretty sure you can do the neutral dialogue box by just entering no character and no animation

**Comment by Haano137** [comment]
> im pretty sure you can do the neutral dialogue box by just entering no character and no animation

No dice. The engine literally has no assets to support that
![speech_bubble](https://user-images.githubusercontent.com/71540568/147226261-d72085d3-fa14-41be-91a3-8909b345fdfe.png)
