### ISSUE TITLE
Custom notes losing color

### ISSUE THREAD

**Issue by Thecoolgamer6745** [ShadowMario/FNF-PsychEngine#12934]
### Describe your problem here.

When importing my custom notes from 0.6.3 into 0.7.1, the notes lose their color and become completely white

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No i changed nothing

**Comment by Thecoolgamer6745** [comment]
figured it out

**Comment by Kullix** [comment]
can you write what the problem was ? other people can have this problem too (including me), it would be pretty cool if i knew how to fix it 🥺
