### ISSUE TITLE
Dodge custom event not working

### ISSUE THREAD

**Issue by Thecoolgamer6745** [ShadowMario/FNF-PsychEngine#12935]
### Describe your problem here.

The dodge event is supposed to let me press space to dodge but when i press it it dosent work. I imported the event from 0.6.3 to 0.7.1

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No i changed nothing

**Comment by CaptainBaldi** [comment]
me when 0.7 changed lua and people keep making the same issues on why their 0.6.3 event doesnt work on newer versions :scream:
