### ISSUE TITLE
VideoHandler Error 0.6.3

### ISSUE THREAD

**Issue by wlshedd** [ShadowMario/FNF-PsychEngine#12945]
### Describe your problem here.

ever since updating the libraries versions for 0.7 whenever i try to compile 0.6.3 now i get this error so my guess is updating or downgrading one of the libraries is the reason for it but idk what one it would be and what i should set it back to so if someone could help that would be great thanks!
![Desktop Screenshot 2023 07 30 - 21 14 18 69](https://github.com/ShadowMario/FNF-PsychEngine/assets/121220519/b5ef3cee-e96b-4bbe-9974-4e41e1f2bd72)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by biomseed** [comment]
Maybe you could comment out `<define name="VIDEOS_ALLOWED" if="windows || linux || android" unless="32bits"/>` in the Project.xml as a workaround

**Comment by NexIsDumb** [comment]
Ah this is an issue that i resolved some times ago through PRs since hxCodec updated a bunch of times
Since you don't have the new updated source just simply downgrade hxCodec to 2.5.1

**Comment by biomseed** [comment]
> Ah this is an issue that i resolved some times ago through PRs since hxCodec updated a bunch of times Since you don't have the new updated source just simply downgrade hxCodec to 2.5.1

the hxcodec version for psych engine is git, it should already be updated

**Comment by NexIsDumb** [comment]
> > Ah this is an issue that i resolved some times ago through PRs since hxCodec updated a bunch of times Since you don't have the new updated source just simply downgrade hxCodec to 2.5.1
> 
> the hxcodec version recommended for psych engine is git, it should already be updated

yes but you're trying to compile 0.6.3 which is an older version
