### ISSUE TITLE
The Scrolling in chart mode just dont go to the next section when he hits the limit

### ISSUE THREAD

**Issue by Ve3h** [ShadowMario/FNF-PsychEngine#12941]
### Describe your bug here.

So, when i was on psych rn, i was testing the chart menu with the new data section the things
but i have notice that the scrolling of chart menu just keeping going and dont go to the next section
making u need to go to other section manually

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/137530784/d414b3ff-bb1f-4142-a755-6e92a50dfd3b)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nop

**Comment by CaptainBaldi** [comment]
not a bug
its a chart editor setting
