### ISSUE TITLE
Error in compiling

### ISSUE THREAD

**Issue by scluxthefunkup** [ShadowMario/FNF-PsychEngine#12946]
### Describe your problem here.

after i type lime test windows this thing happened.

C:/Users/clave/Downloads/FNF-PsychEngine-main/.haxelib/linc_luajit/git/llua/State.hx:11: characters 24-49 : You cannot access the cpp package while in a macro (for cpp.RawPointer)
C:/Users/clave/Downloads/FNF-PsychEngine-main/.haxelib/linc_luajit/git/llua/Lua.hx:4: characters 8-18 : ... referenced here
C:\Users\clave\Downloads\FNF-PsychEngine-main\source\import.hx:10: characters 8-16 : ... referenced here
C:\Users\clave\Downloads\FNF-PsychEngine-main\source\import.hx:4: characters 8-23 : ... referenced here
C:\Users\clave\Downloads\FNF-PsychEngine-main\.haxelib\lime\8,0,2/src/lime/media/AudioSource.hx:138: characters 53-100 : ... referenced here
C:/Users/clave/Downloads/FNF-PsychEngine-main/.haxelib/openfl/9,2,2/src/openfl/media/Sound.hx:14: characters 8-30 : ... referenced here
C:/Users/clave/Downloads/FNF-PsychEngine-main/.haxelib/openfl/9,2,2/src/openfl/utils/Assets.hx:9: characters 8-26 : ... referenced here
C:/Users/clave/Downloads/FNF-PsychEngine-main/.haxelib/openfl/9,2,2/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here
C:/Users/clave/Downloads/FNF-PsychEngine-main/.haxelib/openfl/9,2,2/src/openfl/text/_internal/TextEngine.hx:9: characters 8-24 : ... referenced here
C:/Users/clave/Downloads/FNF-PsychEngine-main/.haxelib/openfl/9,2,2/src/openfl/display/_internal/CairoTextField.hx:3: characters 8-40 : ... referenced here
C:/Users/clave/Downloads/FNF-PsychEngine-main/.haxelib/openfl/9,2,2/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here
C:/Users/clave/Downloads/FNF-PsychEngine-main/.haxelib/openfl/9,2,2/src/openfl/display/_internal/CairoGraphics.hx:6: characters 8-36 : ... referenced here
C:/Users/clave/Downloads/FNF-PsychEngine-main/.haxelib/openfl/9,2,2/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
C:/Users/clave/Downloads/FNF-PsychEngine-main/.haxelib/openfl/9,2,2/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
C:/Users/clave/Downloads/FNF-PsychEngine-main/.haxelib/openfl/9,2,2/src/openfl/events/RenderEvent.hx:4: characters 8-44 : ... referenced here
C:/Users/clave/Downloads/FNF-PsychEngine-main/.haxelib/openfl/9,2,2/src/openfl/display/DisplayObject.hx:13: characters 8-33 : ... referenced here
C:/Users/clave/Downloads/FNF-PsychEngine-main/.haxelib/openfl/9,2,2/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
C:/Users/clave/Downloads/FNF-PsychEngine-main/.haxelib/openfl/9,2,2/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
C:\Users\clave\Downloads\FNF-PsychEngine-main\.haxelib\lime\8,0,2/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
C:\Users\clave\Downloads\FNF-PsychEngine-main\.haxelib\lime\8,0,2/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
C:\Users\clave\Downloads\FNF-PsychEngine-main\.haxelib\lime\8,0,2/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
C:\Users\clave\Downloads\FNF-PsychEngine-main\.haxelib\lime\8,0,2/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
C:\Users\clave\Downloads\FNF-PsychEngine-main\.haxelib\lime\8,0,2/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
C:\Users\clave\Downloads\FNF-PsychEngine-main\.haxelib\lime\8,0,2/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
C:\Users\clave\Downloads\FNF-PsychEngine-main\.haxelib\lime\8,0,2/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
C:\Users\clave\Downloads\FNF-PsychEngine-main\.haxelib\lime\8,0,2/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
C:\Users\clave\Downloads\FNF-PsychEngine-main\.haxelib\lime\8,0,2/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
C:\Users\clave\Downloads\FNF-PsychEngine-main\.haxelib\lime\8,0,2/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
C:\Users\clave\Downloads\FNF-PsychEngine-main\.haxelib\lime\8,0,2/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
C:\Users\clave\Downloads\FNF-PsychEngine-main\.haxelib\lime\8,0,2/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by doom699** [comment]
it seems like that you didnt install everything you need to compile, right? so
you must be on haxe 4.2.5 or else it wont work, what psych engine are you using? also
try this shit it helps u compile #10756 and do all u need incase this doesnt work you can try [this shit also](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions) if that doesnt work try this [tutorial](https://gamebanana.com/tuts/15301) then if that doesnt work, stick to 0.6x guessing you are on 0.7 and up until this fixes

**Comment by Gabo137** [comment]
Tomorrow I'll send you the repositories I made, fix all those errors.
It took me two hours to fix *suffering*
