### ISSUE TITLE
Compiling 0.7.1 Error Help

### ISSUE THREAD

**Issue by StpYT** [ShadowMario/FNF-PsychEngine#12949]
### Describe your problem here.

I’m new to source, and this is my first time trying to compile Psych, but I keep getting these errors 
![TroubleshootPsychEngine0 7 1-SourceCode](https://github.com/ShadowMario/FNF-PsychEngine/assets/118869379/903fe82a-310d-4c28-be07-f7c2b0d868e2)
Does anyone know how to fix this? 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No. It’s base psych engine

**Comment by StpYT** [comment]
Never mind. I found out by reading about problems others had with this. It's all good now

**Comment by NexIsDumb** [comment]
> Never mind. I found out by reading about problems others had with this. It's all good now

Close this issue then please

**Comment by jesseydeanimator** [comment]
> Never mind. I found out by reading about problems others had with this. It's all good now

HOW

**Comment by Gabo137** [comment]
Tomorrow I'll send you the repositories I made, fix all those errors.
It took me two hours to fix *suffering*

**Comment by NexIsDumb** [comment]
> Tomorrow I'll send you the repositories I made, fix all those errors.
> It took me two hours to fix *suffering*

but you just had to do what the readme says in psych 0.7+
why did you do that? its like work for nothing

**Comment by Gabo137** [comment]
Well, I wanted to do it because I didn't want to downgrade haxe and the other libraries, besides, it was a nice experience to fix all those errors.
I was so happy after fixing all those errors and seeing that the game started to compile and run.
Maybe it's a waste of time, but I liked doing it.

**Comment by NexIsDumb** [comment]
> Well, I wanted to do it because I didn't want to downgrade haxe and the other libraries, besides, it was a nice experience to fix all those errors.
> I was so happy after fixing all those errors and seeing that the game started to compile and run.
> Maybe it's a waste of time, but I liked doing it.

Not sure by what you meant with haxe but if you meant its libraries Psych 0.7+ uses the latest versions, while if you meant haxe itself using languages at their latest releases it's not always a great idea also because they might be buggy, which haxe latest version is iirc
not saying you did something wrong tho

**Comment by Gabo137** [comment]
I mean I used the haxe 4.3.1, and the updated libraries (flixel 5.3.1, flixel-addons 3.1.1, etc.) Those libraries had bugs and I fixed them.
I tested the game and it works fine.
If you want to verify it, I'll send you the corrected and updated libs and try it, ok?
And sorry for my bad English, I'm using a translator.

**Comment by NexIsDumb** [comment]
> I mean I used the haxe 4.3.1, and the updated libraries (flixel 5.3.1, flixel-addons 3.1.1, etc.) Those libraries had bugs and I fixed them.
> I tested the game and it works fine.
> If you want to verify it, I'll send you the corrected and updated libs and try it, ok?
> And sorry for my bad English, I'm using a translator.

ah dw, im not naive english either
ohhhh and so you meant that you literally forked libs like flixel and stuff? I see
Sure then, i'll just check your profile thanks
and at this point if you really feel like that you fixed them you could also make pull requests for those libs at this point

**Comment by Gabo137** [comment]
yes of course.
And wait, don't look at my profile yet, I still have to send the other libs, and the other libs I sent are private.
And I'll see if I can make a pull request

**Comment by NexIsDumb** [comment]
> yes of course.
> And wait, don't look at my profile yet, I still have to send the other libs, and the other libs I sent are private.
> And I'll see if I can make a pull request

Oop oke

**Comment by Gabo137** [comment]
I withdraw what was said about the libs that I was going to send it. Now I made it short with a file (Import.hx).
And now I made a pull request

https://github.com/ShadowMario/FNF-PsychEngine/pull/13025

**Comment by NexIsDumb** [comment]
> 



> I withdraw what was said about the libs that I was going to send it. Now I made it short with a file (Import.hx). And now I made a pull request
> 
> #13025

👍
