### ISSUE TITLE
"Source" folder containing HX files which you can edit to change the engine up a bit

### ISSUE THREAD

**Issue by deco1212** [ShadowMario/FNF-PsychEngine#12948]
### What feature do you want to get added on the **base** engine?

I've always dreamed of there being an "source" folder in Windows builds with HX files to modify PlayState.hx or other source code files right off the bat without any source code downloading and modifying, just download Windows build and change the engine from the source folder.
For example, i change StoryMenuState.hx to make the Story Menu have less options, just like the source code.
This would be a VERY, like CRAZY VERY useful feature for Psych Engine, **especially for me**
**IM FUCKING BEGGING YOU SHADOW MARIO!!! I WANT MY FREEPLAY MENU AND PAUSE MENU TO BE CENTERED AHSNUSNASPNS!!!**

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MemeHovy** [comment]
> ### What feature do you want to get added on the **base** engine?
> I've always dreamed of there being an "source" folder in Windows builds with HX files to modify PlayState.hx or other source code files right off the bat without any source code downloading and modifying, just download Windows build and change the engine from the source folder. For example, i change StoryMenuState.hx to make the Story Menu have less options, just like the source code. This would be a VERY, like CRAZY VERY useful feature for Psych Engine, **especially for me** **IM FUCKING BEGGING YOU SHADOW MARIO!!! I WANT MY FREEPLAY MENU AND PAUSE MENU TO BE CENTERED AHSNUSNASPNS!!!**
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Stage Editor, 6K+ support, and winning icons.

dude, source code exists for a reason, alongside lua you fucking retard

**Comment by deco1212** [comment]
dude i just want to modify non song sections of the game like the god damn menus, lua cant do that

**Comment by MemeHovy** [comment]
> dude i just want to modify non song sections of the game like the god damn menus, lua cant do that

you failed the test and this has been asked a thousand times already and it’s not happening

**Comment by CaptainBaldi** [comment]
this is so stupid 💀 
average d&b fan issue

**Comment by deco1212** [comment]
jesus fucking christ you guys dont get it lmao

**Comment by MemeHovy** [comment]
> jesus fucking christ you guys dont get it lmao, my mod will look like garbage if you guys keep being assholes and not adding it to the engine, thought you guys had the most customizable engine ever but nope, switching to yoshi engine then

because the idea you suggested is garbage

**Comment by deco1212** [comment]
wtfff dude imagine a 9 year old kid is new to modding and wants to change the app name and center up the freeplay menu but he cant cuz the lua api is just barely useful because it only works in songs and stages

**Comment by CaptainBaldi** [comment]
> jesus fucking christ you guys dont get it lmao, my mod will look like garbage if you guys keep being assholes and not adding it to the engine, thought you guys had the most customizable engine ever but nope, switching to yoshi engine then

dude i dont think anyone cares if you switch your d&b mod to yoshi like :sob:

**Comment by deco1212** [comment]
> > jesus fucking christ you guys dont get it lmao, my mod will look like garbage if you guys keep being assholes and not adding it to the engine, thought you guys had the most customizable engine ever but nope, switching to yoshi engine then
> 
> dude i dont think anyone cares if you switch your d&b mod to yoshi like 😭

im switching epik friday and my d&b mod to yoshi engine [probably]

**Comment by deco1212** [comment]
thats it im closing this shit - people dont bother and wont understand my pain

**Comment by MemeHovy** [comment]
> thats it im closing this shit - people dont bother and wont understand my pain

good

**Comment by MemeHovy** [comment]
![](https://pbs.twimg.com/media/FyMn2ABWwAAFkRM.jpg)

**Comment by deco1212** [comment]
> > jesus fucking christ you guys dont get it lmao, my mod will look like garbage if you guys keep being assholes and not adding it to the engine, thought you guys had the most customizable engine ever but nope, switching to yoshi engine then
> 
> how about you "ask" codename engine it's more optimized cry about it besides theres already a psych engine fork that add custom menus and shit

WAIT WHAT GIVE ME THE LINK I'LL SWITCH TO THAT

**Comment by deco1212** [comment]
> > > > jesus fucking christ you guys dont get it lmao, my mod will look like garbage if you guys keep being assholes and not adding it to the engine, thought you guys had the most customizable engine ever but nope, switching to yoshi engine then
> > > 
> > > 
> > > how about you "ask" codename engine it's more optimized cry about it besides theres already a psych engine fork that add custom menus and shit
> > 
> > 
> > WAIT WHAT GIVE ME THE LINK I'LL SWITCH TO THAT
> 
> [aight here you go](https://github.com/mayo78/FNF-PsychEngine-BambiAddon)

HOLY SHIT THANK YOU SO MUCHHH

**Comment by MemeHovy** [comment]
this issue did not need to be reopened

**Comment by deco1212** [comment]
Oops~!

**Comment by JokeBambi** [comment]
this is the stupidest issue i ever seen wtf
