### ISSUE TITLE
Shader script working in 0.6.3, but not 0.7

### ISSUE THREAD

**Issue by TheRealPepsi** [ShadowMario/FNF-PsychEngine#12947]
### Describe your bug here.

Hey all, title says it all, I'm using a script to create a glitch shader, and this script works in 0.6.3, but not in 0.7, here's the code, any help appreciated greatly

local shaderName = "glitch"
local check = 256
local check2 = 9999999

function onBeatHit()
	getProperty(check2)
	if curBeat > check2 then
	triggerEvent('Change Character', 'Dad', 'AngeredPepsiFreeOfEpilepsy')
	elseif curBeat < check2 and curStep > 255 then
	triggerEvent('Change Character', 'Dad', 'AngeredPepsi')
	triggerEvent('Alt Idle Animation', 'Dad', '-alt')
end
end

function onStepHit()
        if curStep == check then
            makeLuaSprite("glitch")
            makeGraphic("shaderImage", screenWidth, screenHeight)

            setSpriteShader("shaderImage", "glitch")

            runHaxeCode([[
                var shaderName = "]] .. shaderName .. [[";
                game.initLuaShader(shaderName);
                var shader0 = game.createRuntimeShader(shaderName);
                game.camGame.setFilters([new ShaderFilter(shader0)]);
                game.getLuaObject("glitch").shader = shader0; // setting it into temporary sprite so luas can set its shader uniforms/properties
                game.camHUD.setFilters([new ShaderFilter(game.getLuaObject("glitch").shader)]);
                return;
            ]])

    function onUpdate(elapsed)
        setShaderFloat("glitch", "iTime", os.clock() * 10) -- multiplying iTime by 10
    end

    function shaderCoordFix()
        runHaxeCode([[
            resetCamCache = function(?spr) {
                if (spr == null || spr.filters == null) return;
                spr.__cacheBitmap = null;
                spr.__cacheBitmapData = null;
            }
            
            fixShaderCoordFix = function(?_) {
                resetCamCache(game.camGame.flashSprite);
                resetCamCache(game.camHUD.flashSprite);
                resetCamCache(game.camOther.flashSprite);
            }
        
            FlxG.signals.gameResized.add(fixShaderCoordFix);
            fixShaderCoordFix();
            return;
        ]])
        
        local temp = onDestroy
        function onDestroy()
            runHaxeCode([[
                FlxG.signals.gameResized.remove(fixShaderCoordFix);
                return;
            ]])
            if (temp) then temp()
        end
    end
end
 end

function onUpdate()  
  if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.NUMPADONE') or getPropertyFromClass('flixel.FlxG', 'keys.justPressed.ONE') then
	debugPrint("Heavy Epilepsy Stuff Disabled")
	check = -1
	check2 = 9999999
	elseif getPropertyFromClass('flixel.FlxG', 'keys.justPressed.NUMPADTWO') or getPropertyFromClass('flixel.FlxG', 'keys.justPressed.TWO') then
	debugPrint("All Epilepsy Stuff Disabled")
	check = -1
	check2 = 1
	elseif getPropertyFromClass('flixel.FlxG', 'keys.justPressed.NUMPADTHREE') or getPropertyFromClass('flixel.FlxG', 'keys.justPressed.THREE') then
	debugPrint("Epilepsy Stuff Enabled")
	check2 = 9999999
	check = 256
end
end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheRealPepsi** [comment]
Sorry, forgot to say, that it crashes the game entirely without a crash log

**Comment by TheRealPepsi** [comment]
Just tested it on 0.7.1h, still doesn't work, only on 0.6.3

**Comment by rschoolu** [comment]
0.7 changed lots of things, so it's sure to break lua mods. i'm kind of not that into making shader scripts but maybe this page can help: https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7

**Comment by TheRealPepsi** [comment]
Thanks for your comment! I tried everything you sent, to no avail. the problem seems to be when refreshing the shader, it'll load the shader once, but trying to load it again just crashes the game entirely (this isn't a problem with 0.6.3
)
