### ISSUE TITLE
Pause function

### ISSUE THREAD

**Issue by ToBAYT** [ShadowMario/FNF-PsychEngine#1294]
### Describe your bug here.

So basically, the pause control won't change. I set it to be space and shift but only enter works (On downloaded version too!)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No. none of the top 2 stuff matter LOL

**Comment by ShadowMario** [comment]
Fixed, my bad
