### ISSUE TITLE
NativeCFFI Not Found

### ISSUE THREAD

**Issue by TrashManLOL** [ShadowMario/FNF-PsychEngine#12943]
### Describe your problem here.

im trying to compile but says this (sorry fpr bad english): System.hx:270: characters 15-25 : Type not found : NativeCFFI
characters 12-22 : Type not found : NativeCFFI
characters 12-22 : Type not found : NativeCFFI
characters 29-39 : Type not found : NativeCFFI

im using psych 0.7

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
There is no "NativeCCFI" on psych engine, i don't know what that library means.
