### ISSUE TITLE
camera dont go in the character who sings

### ISSUE THREAD

**Issue by aless26pic** [ShadowMario/FNF-PsychEngine#12957]
### Describe your bug here.

![Capture d’écran (162)](https://github.com/ShadowMario/FNF-PsychEngine/assets/109902083/90374248-35b5-476b-9d8f-effb40614563)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no source yet

**Comment by aless26pic** [comment]
the camera stuck in bf

**Comment by aless26pic** [comment]
@ShadowMario

**Comment by aless26pic** [comment]
why

**Comment by MemeHovy** [comment]
> @ShadowMario

he has his notifications turned off, don't ping him

**Comment by aless26pic** [comment]
> > @ShadowMario
> 
> he has his notifications turned off, don't ping him

ok
