### ISSUE TITLE
Trying to add new character sprites to non-mod folder doesn't work

### ISSUE THREAD

**Issue by VanessaMae1087** [ShadowMario/FNF-PsychEngine#12950]
### Describe your problem here.

how do you add new sprites? is there code im missing i need to edit?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, but only clientprefs.hx

**Comment by aless26pic** [comment]
you have to go in assets\shared\images\characters for the image and for json file go to assets\preload\characters

**Comment by aless26pic** [comment]
it work ?

**Comment by VanessaMae1087** [comment]
it just spits out this error attempting to load it
its named correctly in the json
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/72725655/a747a9e8-8ee4-4059-857b-3e7ec0bf56d4)

**Comment by aless26pic** [comment]
@VanessaMae1087 what source file do you change

**Comment by VanessaMae1087** [comment]
still having this issue
recompiling doesnt change anything, files are in the right places...

**Comment by VanessaMae1087** [comment]
re-exporting the sprite sheet fixed it for some reason but at least it works????
