### ISSUE TITLE
shadowmario you broke hscript again :sob:

### ISSUE THREAD

**Issue by CaptainBaldi** [ShadowMario/FNF-PsychEngine#12954]
### Describe your bug here.

I can only use `runHaxeCode` once per script it seems. Every instance after that simply doesn't run.
For example I have a `runHaxeCode` that runs on create to replace the cursor graphic, I also have another that removes the cursor graphic on destroy.
The one on create works because it's the first instance to run, the other one doesn't
0.7.1 hotfix hotfix :pensive:

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
Technically this wasn't my fault but i get what is the problem lol

**Comment by CaptainBaldi** [comment]
oh well, at least its acknowledged

**Comment by TheLeerName** [comment]
[btw temporary fix as script!!!!!!](https://drive.google.com/file/d/1e1BnGQcoL5ypAj0MA7Upg8iC-XLZ5szj)
