### ISSUE TITLE
what is this? pls how to fix

### ISSUE THREAD

**Issue by Anoyinguser** [ShadowMario/FNF-PsychEngine#12955]
### Describe your bug here.

source/psychlua/HScript.hx:42: characters 22-27 : Too many arguments
source/psychlua/HScript.hx:38: lines 38-50 : Missing super constructor call
source/psychlua/HScript.hx:228: characters 26-37 : psychlua.HScript has no field returnValue
source/psychlua/HScript.hx:229: characters 25-36 : psychlua.HScript has no field returnValue

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by aless26pic** [comment]
what version do you use

**Comment by Anoyinguser** [comment]
@aless26pic 0.7.1
