### ISSUE TITLE
Compiling error, need help.

### ISSUE THREAD

**Issue by TheSketchAlex** [ShadowMario/FNF-PsychEngine#12963]
### Describe your problem here.

source/psychlua/HScript.hx:42: characters 22-27 : Too many arguments
source/psychlua/HScript.hx:38: lines 38-50 : Missing super constructor call
source/psychlua/HScript.hx:228: characters 26-37 : psychlua.HScript has no field returnValue
source/psychlua/HScript.hx:229: characters 25-36 : psychlua.HScript has no field returnValue

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't.

**Comment by Anoyinguser** [comment]
just type in the system symbol 'haxelib update'

**Comment by ShadowMario** [comment]
`haxelib update SScript`
