### ISSUE TITLE
Bugged timebar

### ISSUE THREAD

**Issue by Anoyinguser** [ShadowMario/FNF-PsychEngine#12965]
### Describe your bug here.

time bar doesn't move :/, and the change color timebar script doesn't works

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by Anoyinguser** [comment]
here a screenshot
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/121916769/f1adfc24-0706-41b7-bbfd-f86d73b34f6a)

**Comment by ShadowMario** [comment]
Was it a script from 0.6.3? It might have broken with the update, if that's the case I can't fix what's not my fault.

**Comment by Anoyinguser** [comment]
welp i just erased the timebar in photoshop, now it works but with a white background
