### ISSUE TITLE
Not opening (nothing modified)

### ISSUE THREAD

**Issue by schoolchromebookgaming** [ShadowMario/FNF-PsychEngine#12972]
### Describe your bug here.

Psych 0.7.1h 32 bit isn't opening, nothing was modified

### Command Prompt/Terminal logs (if existing)

```bash
Could not load module lime@lime_application_create_prime
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by uhhso** [comment]
the thing is. I downloaded the game banana 32 bit build and the GitHub 32-bit build and.... UGHHH *it didn't work. * I'm going to try again then.

**Comment by uhhso** [comment]
thanks!

**Comment by schoolchromebookgaming** [comment]
i fixed it a while ago by downloading lime.ndll, i apologize i forgot to close it
