### ISSUE TITLE
Song Won't Load Even Though The json File Is There

### ISSUE THREAD

**Issue by HeroSnackz** [ShadowMario/FNF-PsychEngine#12979]
### Describe your problem here.

For some reason when I try to enter the json file for the song the engine says that the file is missing. What's going on?
![Screenshot 2023-08-01 153822](https://github.com/ShadowMario/FNF-PsychEngine/assets/140018626/f4af7d6a-5ad8-4153-99d9-f6320dbaf7cd)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by biomseed** [comment]
Your json file needs to be in the glitcher (monika mix) folder

**Comment by HeroSnackz** [comment]
> Your json file needs to be in the glitcher (monika mix) folder, and you need to play on normal unless you have -hard or -easy on the chart's name

I tried that, but I still keep getting the error saying that the file is missing.

**Comment by frantastic24** [comment]
Engine replaces spacing and some symbols with -
Name should be `glitcher-(monika-mix)`
