### ISSUE TITLE
Why can't I install the environment after upgrading my computer to the Win11 system

### ISSUE THREAD

**Issue by AZjessica122** [ShadowMario/FNF-PsychEngine#12970]
### Describe your problem here.

Unable to package due to lack of environment

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
can you be more specific?

**Comment by AZjessica122** [comment]
I reinstalled the Win11 system on my computer, and after installing it, I found that the environment was gone. When I tried to reinstall it with cmd, it prompted 'discord'_ Rpc: 'is not an internal or external command, nor is it a runnable program Or batch file.

**Comment by AZjessica122** [comment]
> 你能更具体一点吗？



> 你能更具体一点吗？

I reinstalled the Win11 system on my computer, and after installing it, I found that the environment was gone. When I tried to reinstall it with cmd, it prompted 'discord'_ Rpc: 'is not an internal or external command, nor is it a runnable program
Or batch file.

**Comment by AZjessica122** [comment]
> can you be more specific?
I reinstalled the Win11 system on my computer, and after installing it, I found that the environment was gone. When I tried to reinstall it with cmd, it prompted 'discord'_ Rpc: 'is not an internal or external command, nor is it a runnable program Or batch file.

**Comment by MemeHovy** [comment]
> > can you be more specific?
> > I reinstalled the Win11 system on my computer, and after installing it, I found that the environment was gone. When I tried to reinstall it with cmd, it prompted 'discord'_ Rpc: 'is not an internal or external command, nor is it a runnable program Or batch file.

reinstall haxe 4.2.5

**Comment by AZjessica122** [comment]
> reinstall haxe 4.2.5

I tried, but it didn't work

**Comment by AZjessica122** [comment]
> try this then `haxelib install hxcpp 4.3.2`

then？

**Comment by AZjessica122** [comment]
> > > try this then `haxelib install hxcpp 4.3.2`
> > 
> > 
> > then？
> 
> yes

I mean, what am I going to do next

**Comment by AZjessica122** [comment]
> > > > > try this then `haxelib install hxcpp 4.3.2`
> > > > 
> > > > 
> > > > then？
> > > 
> > > 
> > > yes
> > 
> > 
> > I mean, what am I going to do next
> 
> try to compile again -_______-

Still not working :(

**Comment by AZjessica122** [comment]
> > > > > try this then `haxelib install hxcpp 4.3.2`
> > > > 
> > > > 
> > > > then？
> > > 
> > > 
> > > yes
> > 
> > 
> > I mean, what am I going to do next
> 
> try to compile again -_______-

And what was clearly installable before, but now it cannot be installed
