### ISSUE TITLE
week editor freeplay image

### ISSUE THREAD

**Issue by aless26pic** [ShadowMario/FNF-PsychEngine#12974]
### What feature do you want to get added on the **base** engine?

you can use different image for all song

![Capture d’écran (163)](https://github.com/ShadowMario/FNF-PsychEngine/assets/109902083/fcd6a4a5-ea14-42da-b981-84b61220c4b0)
![Capture d’écran (164)](https://github.com/ShadowMario/FNF-PsychEngine/assets/109902083/3cdd21d3-1858-44cf-bc88-f9a4b4c891b3)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MemeHovy** [comment]
seems useless
