### ISSUE TITLE
0.7.1h won't compile properly

### ISSUE THREAD

**Issue by Sammobot5** [ShadowMario/FNF-PsychEngine#12975]
### Describe your problem here.

When I go to do the "lime test windows", I'm given these errors

source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
source/psychlua/CallbackHandler.hx:48: characters 41-46 : Class<llua.LuaL> has no field error
source/psychlua/FunkinLua.hx:273: lines 273-276 : Int should be Bool
source/psychlua/FunkinLua.hx:273: lines 273-276 : ... For function argument 'f'

![image_2023-08-01_110857176](https://github.com/ShadowMario/FNF-PsychEngine/assets/76877178/c630afd6-2193-49b7-a001-cb13cfcaf4e1)

I haven't modified any of the source code in any way, I just needed a base build to work with.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

One extremely minor thing, that being the tracklist color in StoryMenuState.hx on line 169

**Comment by MemeHovy** [comment]
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit master
