### ISSUE TITLE
Trouble with global variables

### ISSUE THREAD

**Issue by b8mate** [ShadowMario/FNF-PsychEngine#12971]
### Describe your problem here.

I am trying to use GetGlobalFromScript, but it just doesn't want to work at all

here's a part of the code
function onCreate()
	local orange = getGlobalFromScript("eyemech", "isOrange");
end

function opponentNoteHit(id, direction, noteType, isSustainNote)
    if noteType == "noteorange" then
			if not orange then
        		setProperty('health', getProperty('health') - 0.25);
			end
	end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by b8mate** [comment]
nevermind i found a way

**Comment by VoidedBattery** [comment]
Could I see the code of the working script? I'd like to know how you solved it
