### ISSUE TITLE
wont play modpack

### ISSUE THREAD

**Issue by BrokeHrt** [ShadowMario/FNF-PsychEngine#12983]
### Describe your bug here.

psych engine 0.7.1h and others wont play modpacks. ive tried many times and it wont

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Draconic-Hybrid** [comment]
Did you remember to check if they're enabled?

**Comment by BrokeHrt** [comment]
Yes. I enable them, turn them on, and press escape. And it doesn’t restart
psych engine to load the mod

**Comment by Draconic-Hybrid** [comment]
Press 7 on the Main Menu and see if you can load the mod directories. Try loading a song from the mod in the Chart Editor.

**Comment by BrokeHrt** [comment]
I'll try that.

**Comment by BrokeHrt** [comment]
That's weird
