### ISSUE TITLE
Custom Character won't show

### ISSUE THREAD

**Issue by GabeTheGlitch06** [ShadowMario/FNF-PsychEngine#12981]
### Describe your problem here.

Idk what happened between 0.6.3 and 0.7/0.7.1, but I transferred my characters over to the correct folders with the appropriate files and whatnot, but they wont appear on the character list in the chart editor. Some things I've tried were moving json files to the regular character folder (which resulted in something else, but that's not the issue here), manually editing the character list in the files, which kinda worked but wouldn't let me pick the character, and lastly I put in a edited json for one of the songs and the custom characters loaded as Boyfriends instead. Again, not sure what's gone wrong from before and after the code overhaul, but that ended up happening.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by aless26pic** [comment]
Can you send me a screenshots

**Comment by GabeTheGlitch06** [comment]
> Can you send me a screenshots
![Screenshot 2023-08-03 102650](https://github.com/ShadowMario/FNF-PsychEngine/assets/140927269/93233b28-9330-424b-a4bf-a7ac076f2ab1)
![Screenshot 2023-08-03 102734](https://github.com/ShadowMario/FNF-PsychEngine/assets/140927269/cf758910-30d5-4647-9c9d-cbec12f238de)

Here's the screenshots, if your wondering why one of them appeared on the list, that was from the manually edited list, which like I stated previously didnt work

**Comment by aless26pic** [comment]
where do you save it
in mods or assets

**Comment by GabeTheGlitch06** [comment]
> where do you save it in mods or assets

I saved everything in the appropriate folders in the mod folder

**Comment by RonRazar** [comment]
I have to same problem they won't show up on the mod template I made

**Comment by RonRazar** [comment]
I have compiled psych engine 0.7.1 and I have an issue where I made a mod template add the png and xml files for my character and it doesn't show I tried seeing if pressing the tempelete button in the character Editor but it won't show either

**Comment by aless26pic** [comment]
> > where do you save it in mods or assets
> 
> I saved everything in the appropriate folders in the mod folder

Mods folder have some bugs in 0.7

**Comment by Dsyboot** [comment]
Wow, the new version of psych Engine seems to be causing too many problems, but I think I know how you can solve it... If you go to the assets/data folder you will see a file named "characterList.txt", in this file you will see all the characters name of the game base, so you need to make a "characterList.txt" in your data mod folder and put the name of your characters, I guess that can help?
