### ISSUE TITLE
Game Crashes as soon as I touch anything in the menu

### ISSUE THREAD

**Issue by FirstShot07** [ShadowMario/FNF-PsychEngine#1298]
### Describe your problem here.

If I try to go to the master editor in the menu, the game freezes, and crashes. If I move up or down, it crashes. It was working 2 days ago, but now I can't see if my mod works

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed sprite sheets and other assets

**Comment by Mokona5901** [comment]
![Capture](https://user-images.githubusercontent.com/82078037/143051414-7d9a6558-ceaa-4b0a-93da-6f74e087c884.PNG)
idk if it can help

**Comment by CrusherMods** [comment]
> ![Capture](https://user-images.githubusercontent.com/82078037/143051414-7d9a6558-ceaa-4b0a-93da-6f74e087c884.PNG) idk if it can help maybe you moved them in the folder assets inadvertently

He's using source code, assets folder would work

**Comment by SrtHero278** [comment]
try using `lime test windows -debug` to find out the issue.
