### ISSUE TITLE
I CANT COMPILE SOURCE PE 0.71

### ISSUE THREAD

**Issue by Nurokini** [ShadowMario/FNF-PsychEngine#12986]
### Describe your problem here.

I checked all the issuess with the Source and this error (I'm bad at English)

source/options/NotesSubState.hx:193: characters 48-60 : flixel.input.mouse.FlxMouse has no field deltaScreenX
source/options/NotesSubState.hx:193: characters 80-92 : flixel.input.mouse.FlxMouse has no field deltaScreenY
source/options/NotesSubState.hx:456: characters 62-71 : flixel.math.FlxPoint has no field degreesTo
source/options/NotesSubState.hx:457: characters 42-46 : flixel.math.FlxPoint has no field dist

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by SrtHero278** [comment]
it looks like your flixel is outdated. try updating it and see what happens.

**Comment by Nurokini** [comment]
> it looks like your flixel is outdated. try updating it and see what happens.

ok

**Comment by StinkTheStinker** [comment]
> > it looks like your flixel is outdated. try updating it and see what happens.

even though i restarted my pc after that it does not work
