### ISSUE TITLE
0.6.2 error (I like 0.6.2 psych engine)

### ISSUE THREAD

**Issue by fanproductions** [ShadowMario/FNF-PsychEngine#12982]
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/115906994/bac56e5e-e980-42f5-9cc4-185db0c5b94f)
I know this is from 0.6.2 but I like the version to use, so don't bother me with, "use new version" just help please.

### Command Prompt/Terminal logs (if existing)

```bash
source/editors/ChartingState.hx:2148: characters 31-39 : flixel.system.FlxSound has no field __buffer
source/editors/ChartingState.hx:2149: characters 29-37 : flixel.system.FlxSound has no field __buffer
source/editors/ChartingState.hx:2152: characters 12-20 : flixel.system.FlxSound has no field __buffer
source/editors/ChartingState.hx:2165: characters 31-39 : flixel.system.FlxSound has no field __buffer
source/editors/ChartingState.hx:2166: characters 29-37 : flixel.system.FlxSound has no field __buffer
source/editors/ChartingState.hx:2169: characters 12-20 : flixel.system.FlxSound has no field __buffer
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by CaptainBaldi** [comment]
probably smth to do with library inconsistences + dont report bugs on old versions

**Comment by fanproductions** [comment]
b

> probably smth to do with library inconsistences + dont report bugs on old versions

but i tried to look up an bug with the buffer error, but theres none

**Comment by fanproductions** [comment]
ok i'll try it

**Comment by fanproductions** [comment]
@ShadowMario

**Comment by MemeHovy** [comment]
> @ShadowMario

he has his notifications off, don’t ping him

**Comment by fanproductions** [comment]
ok

**Comment by Dsyboot** [comment]
Why you are trying to use Psych Engine 0.6.2? The 0.6.3 it's better I guess?

**Comment by Dsyboot** [comment]
> > Why you are trying to use Psych Engine 0.6.2? The 0.6.3 it's better I guess?
> 
> he likes 0.6.2 more but idc 
> old = bad
> new = better

Makes sense for me, but not always the new it's better, the 0.7 is a head killer because of the bugs

**Comment by fanproductions** [comment]
> Why you are trying to use Psych Engine 0.6.2? The 0.6.3 it's better I guess?

now im trying to use 6.3

**Comment by fanproductions** [comment]
the new page https://gamebanana.com/questions/48406
