### ISSUE TITLE
Psyche Engine keeps crashing whenever you open freeplay or Exit a freeplay song

### ISSUE THREAD

**Issue by Ry3Void** [ShadowMario/FNF-PsychEngine#12980]
### Describe your bug here.

Whenever I hit enter on freeplay, it crashes, and when you exit a song from freeplay or from the chart editor, it also crashes

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by biomseed** [comment]
Psych*

**Comment by DaBrazillianBoi** [comment]
i have the same problem

**Comment by SwappedClothes1749** [comment]
having that EXACT same problem right now. 
anytime I specifically go to SNS Retake 2.5, it just crashes. No other mod of mine does that but SNS Retake. 
Any clue why????
