### ISSUE TITLE
Stress Cutscene Crash 

### ISSUE THREAD

**Issue by Nicore55** [ShadowMario/FNF-PsychEngine#12998]
### Describe your bug here.

when you play stress in storymode the cutscene crashes

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed breakfast.ogg

**Comment by MemeHovy** [comment]
can you give more details?

**Comment by Nicore55** [comment]
idk bro, maybe the cutscene is bad optimized? it crashes and the audio and video are not synchronized

**Comment by MemeHovy** [comment]
> idk bro, maybe the cutscene is bad optimized? it crashes and the audio and video are not synchronized

that's mainly an issue with your pc

**Comment by mcagabe19** [comment]
> > idk bro, maybe the cutscene is bad optimized? it crashes and the audio and video are not synchronized
> 
> that's mainly an issue with your pc

it crashes at our mobile port too and I literally have 6gb ram and 6gb swap mem phone still crashes
