### ISSUE TITLE
Engine Keeps Crashing When I Press Enter In The Chart Editor

### ISSUE THREAD

**Issue by HeroSnackz** [ShadowMario/FNF-PsychEngine#12996]
### Describe your bug here.

When I try to test my chart after pressing enter, the engine crashes. Is there a way to prevent this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by DamjanovPodrum** [comment]
lmao
