### ISSUE TITLE
Long note characters animation how i do

### ISSUE THREAD

**Issue by aless26pic** [ShadowMario/FNF-PsychEngine#12995]
### Describe your problem here.

https://github.com/ShadowMario/FNF-PsychEngine/assets/109902083/a35fe2ee-021e-4556-816c-cb12f865ac82

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Draconic-Hybrid** [comment]
The engine automatically generates long note animations based on the sing direction sprites. I believe it takes from the first four sprites in the animation, but that's purely a guess.

**Comment by aless26pic** [comment]
> The engine automatically generates long note animations based on the sing direction sprites. I believe it takes from the first four sprites in the animation, but that's purely a guess.

i have delete 1 frame and it work
