### ISSUE TITLE
edit anything without source code

### ISSUE THREAD

**Issue by doom699** [ShadowMario/FNF-PsychEngine#12999]
### What feature do you want to get added on the **base** engine?

make it so that you can edit the version and text in the main menu, including other states, if this is already being made, sorry but i thought it would be cool

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MemeHovy** [comment]
you failed the test
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/b7ae58ee-4b06-4ee3-8509-b701b6295c17)

**Comment by doom699** [comment]
shoot
