### ISSUE TITLE
Note RBG Setting

### ISSUE THREAD

**Issue by KlutchDj** [ShadowMario/FNF-PsychEngine#13]
When i was messing around with the note RGB setting (which i really like) , i find it hard to manage around with. for example , when i want to use the same color for 2 arrows , its not the same exact color when i set the same numbers for the RGB . My idea of fixing this issue is when selecting such note on the option menu , it should reset the whole note color to gray (as in the receptor gray where it has no color) , then afterwards you can set your prefered color. 
![Screenshot (415)](https://user-images.githubusercontent.com/81717689/130374195-3310dc8a-567d-48ec-94ce-1a75fefddf4a.png) image of the bug

**Comment by ShadowMario** [comment]
I don't really want to redo the notes for supporting RGB at the moment.

**Comment by ShadowMario** [comment]
Also making the notes grey would make the colors more stale/bland, i already have a solution for this but it would take a good while and too much work to do it.

**Comment by Vortex2Oblivion** [comment]
3 years later it's added
