### ISSUE TITLE
hold notes looking weird when skipping time in-game

### ISSUE THREAD

**Issue by CharlesCatYT** [ShadowMario/FNF-PsychEngine#13001]
### Describe your bug here.

the note gets cut off when skipping time 
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/62410083/e8c1dee8-6089-460d-94db-195f37468fd2)
this happens in every version starting from 0.5.2h (im using 0.7.1 btw)

### Command Prompt/Terminal logs (if existing)

No

### Are you modding a build from source or with Lua?

Source + Lua(?)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no its just the lane underlays just ignore it (and a mod im working on with my own dev team but i aint telling ya further)

**Comment by CaptainBaldi** [comment]
sustains are just different looking notes, so im pretty sure skipping time into the middle of the sustain might remove the parent, i wouldnt say its a bug but i wouldnt say its intended either
