### ISSUE TITLE
is 0.7.1h that bad

### ISSUE THREAD

**Issue by JokeBambi** [ShadowMario/FNF-PsychEngine#13000]
### What is your question?

i never seen any mods using 0.7 and above, and alot still use 0.6.x, is 0.7 bad? because i never seen any mod use it yet like i said so i want to know if 0.7 and above is good or bad because idk

**Comment by MemeHovy** [comment]
migrating to 0.7 from 0.6 is difficult and can be a rocky procress

**Comment by frantastic24** [comment]
hscript is almost completely broken: scripts can't use runHaxeCode more than once, for loops don't work, vars don't carry over to other runHaxeCode instances without setVar/getVar, vars could be used without being declared before sscript

**Comment by JokeBambi** [comment]
3 more reasons and ill close this

**Comment by Gabo137** [comment]
I had the time to fix the errors of 0.7.1h with the latest version of the libraries and Haxe.
Now it works correctly.
Soon I will send a repository of each fixed library

**Comment by JokeBambi** [comment]
> I had the time to fix the errors of 0.7.1h with the latest version of the libraries and Haxe. Now it works correctly. Soon I will send a repository of each fixed library

is it the libraries/versions one?

**Comment by JokeBambi** [comment]
nvm ima just close this
