### ISSUE TITLE
Song load

### ISSUE THREAD

**Issue by UnderFellSansRed2** [ShadowMario/FNF-PsychEngine#13002]
### What feature do you want to get added on the **base** engine?

It would be great if that function returned when you loaded a song, it would not be loaded again when entering, as well as in the 0.5 or 0.4.2

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by MemeHovy** [comment]
what do you mean by that?? I don't really get it

**Comment by Dsyboot** [comment]
Ohhhh i know what you want, you just want a option in the chart editor that allows you to select a specific sound
