### ISSUE TITLE
[Lua API] Add get character default camera offset functions

### ISSUE THREAD

**Issue by HappyAlexRomania** [ShadowMario/FNF-PsychEngine#13008]
### What feature do you want to get added on the **base** engine?

So, I was improving a script from the internet and the script changes the camera position a bit based on the character animations (left,down,up,right), like in the Sonic.exe mod, but I need default character camera get functions that determine the default camera offset to when the camera moves to the character and it seems that they don't exist. Just like the character position functions, the names can be similar:

- GetCharacterCamOffsetX('character_sprite_name'); 
- GetCharacterCamOffsetY('character_sprite_name');

They would be helpful for Lua API scripts like mine here:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/95385133/cf5c5cc4-3507-4219-befa-da0b8f932d6d)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
getProperty can already do this

**Comment by Lorekeeper49** [comment]
`getProperty('char.offset.x')` and `getProperty('char.offset.y')` work

**Comment by Lorekeeper49** [comment]
`getProperty('char.camera.x')` and `getProperty('char.camera.y')` work

**Comment by HappyAlexRomania** [comment]
> `getProperty('char.camera.x')` and `getProperty('char.camera.y')` work

It doesn't. I tried 'dad.camera.x' and 'boyfriend.camera.x' because I think I have to replace 'char' with dad, gf or boyfriend and it didn't work.
