### ISSUE TITLE
My problem with my custom character in the mod templete not working

### ISSUE THREAD

**Issue by RonRazar** [ShadowMario/FNF-PsychEngine#13009]
### Describe your problem here.

I have compiled psych engine 0.7.1 and I have an issue where I made a mod template add the png and xml files for my character and it doesn't show in the character editor and if I use a character json in the mod templete too it won't show on the list and I tried seeing if pressing the red template button in the character Editor but it won't show either

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Modxpgame** [comment]
It’s because your character images doesn’t exist. But idk how to fix it. I have the same problem too.
