### ISSUE TITLE
Stage docs please ;(

### ISSUE THREAD

**Issue by Alltoupload** [ShadowMario/FNF-PsychEngine#13005]
### What needs to be documented?

I don't see a page explaining how to create a stage!

**Comment by JokeBambi** [comment]
heres a template https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/states/stages/Template.hx

**Comment by Alltoupload** [comment]
> heres a template https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/states/stages/Template.hx

I'm using the release build

**Comment by frantastic24** [comment]
Wiki has most functions documented and an example stage

**Comment by Alltoupload** [comment]
> Wiki has most functions documented and an example stage

Thank you <3

**Comment by Alltoupload** [comment]
I don't understand any of the stuff in the json files

**Comment by frantastic24** [comment]
It's coordinates for your characters and camera positioning

**Comment by Alltoupload** [comment]
> It's coordinates for your characters and camera positioning

I'm talking about the directory.
Is it the mod directory, is it "(mod directory)\images"?

**Comment by frantastic24** [comment]
It's for week assets directories but it's unused for mods

**Comment by Alltoupload** [comment]
Does it load directly from "(mod directory)\images"?

**Comment by JokeBambi** [comment]
> > heres a template https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/states/stages/Template.hx
> 
> I'm using the release build

maybe be more specific next time
