### ISSUE TITLE
How do I get camera offset from characters?

### ISSUE THREAD

**Issue by HappyAlexRomania** [ShadowMario/FNF-PsychEngine#13011]
### Describe your problem here.

I posted a suggestion earlier and someone said that you can get character camera offset values with getProperty. Here's what he typed:

getProperty('char.camera.x')
getProperty('char.camera.y') 

I presumed that 'char' can be replaced with 'dad','boyfriend or 'gf' but it didn't work at all.

I wish the creators would add a list of variables that can be received with the 'getProperty' function (or I'm probably blind and didn't see it in the Psych Engine Wiki/Files). That way I wouldn't suggest for things that are already there and it would help me and other new Psych Engine Lua coders a lot

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I added a Lua script that makes your camera move depending on the characters' poses and the 'mustPressSection' variable

**Comment by frantastic24** [comment]
```lua
char.cameraPosition[0] --X
char.cameraPosition[1] --Y
```
You can find these in Character.hx, always refer to source and haxe wiki for properties

**Comment by HappyAlexRomania** [comment]
I'm using non-source (Lua API) so I can't acces Characters.hx :(

**Comment by HappyAlexRomania** [comment]
> ```lua
> char.cameraPosition[0] --X
> char.cameraPosition[1] --Y
> ```
> 
> You can find these in Character.hx, always refer to source and haxe wiki for properties

still doesn't work when I change it in the script. I tried 'getProperty(dad.cameraPosition.x)', no error, but it doesn't work. I tried 'getProperty(dad.cameraPosition)', same. I tried 'getProperty(dad.cameraPosition[0])' and it returned an error about a null object reference

**Comment by frantastic24** [comment]
getProperty uses strings (surrounded by `"`), if you typed them like in your reply then those are not strings and will throw an error

**Comment by HappyAlexRomania** [comment]
> getProperty uses strings (surrounded by `"`), if you typed them like in your reply then those are not strings and will throw an error

yeah I did that but I forgot to put the " in the comment lol

**Comment by frantastic24** [comment]
Can you show the full script

**Comment by HappyAlexRomania** [comment]
> Can you show the full script

Here:

```
local xx = getProperty('dad.cameraPosition.x');
local yy = getProperty('dad.cameraPosition.y');
local xx2 = getProperty('boyfriend.cameraPosition.x');
local yy2 = getProperty('boyfriend.cameraPosition.y');
local ofs = 20;
local followchars = true;
local followtype = 0;
local del = 0;
local del2 = 0;


function onUpdate()
	if followtype == 0 then
		followchars = false
	else
		followchars = true
	end
	if del > 0 then
		del = del - 1
	end
	if del2 > 0 then
		del2 = del2 - 1
	end
	if followchars == true then
		if mustHitSection == false then
			if getProperty('dad.animation.curAnim.name') == 'singLEFT' then
				triggerEvent('Camera Follow Pos',xx-ofs,yy)
			end
			if getProperty('dad.animation.curAnim.name') == 'singRIGHT' then
				triggerEvent('Camera Follow Pos',xx+ofs,yy)
			end
			if getProperty('dad.animation.curAnim.name') == 'singUP' then
				triggerEvent('Camera Follow Pos',xx,yy-ofs)
			end
			if getProperty('dad.animation.curAnim.name') == 'singDOWN' then
				triggerEvent('Camera Follow Pos',xx,yy+ofs)
			end
			if getProperty('dad.animation.curAnim.name') == 'singLEFT-alt' then
				triggerEvent('Camera Follow Pos',xx-ofs,yy)
			end
			if getProperty('dad.animation.curAnim.name') == 'singRIGHT-alt' then
				triggerEvent('Camera Follow Pos',xx+ofs,yy)
			end
			if getProperty('dad.animation.curAnim.name') == 'singUP-alt' then
				triggerEvent('Camera Follow Pos',xx,yy-ofs)
			end
			if getProperty('dad.animation.curAnim.name') == 'singDOWN-alt' then
				triggerEvent('Camera Follow Pos',xx,yy+ofs)
			end
			if getProperty('dad.animation.curAnim.name') == 'idle-alt' then
				triggerEvent('Camera Follow Pos',xx,yy)
			end
			if getProperty('dad.animation.curAnim.name') == 'idle' then
				triggerEvent('Camera Follow Pos',xx,yy)
			end
		else

			if getProperty('boyfriend.animation.curAnim.name') == 'singLEFT' then
				triggerEvent('Camera Follow Pos',xx2-ofs,yy2)
			end
			if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT' then
				triggerEvent('Camera Follow Pos',xx2+ofs,yy2)
			end
			if getProperty('boyfriend.animation.curAnim.name') == 'singUP' then
				triggerEvent('Camera Follow Pos',xx2,yy2-ofs)
			end
			if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN' then
				triggerEvent('Camera Follow Pos',xx2,yy2+ofs)
			end
			if getProperty('boyfriend.animation.curAnim.name') == 'idle' then
				triggerEvent('Camera Follow Pos',xx2,yy2)
			end
		end
	else
		triggerEvent('Camera Follow Pos','','')
	end

end

function onEvent(name,value1,value2)
	if name == 'Cam Follow Characters' then
		if value1 == '0' then
			followtype = 0
		elseif value1 == '1' then
			followtype = 1
		end
	end
end	
```

**Comment by frantastic24** [comment]
You need to put getProperty inside onCreatePost, characters don't exist until after it's called

**Comment by HappyAlexRomania** [comment]
> You need to put getProperty inside onCreatePost, characters don't exist until after it's called

it still doesn't work. It works if I put numbers but I want the script to do it based on the character's camera position.

```
local ofs = 20;
local followchars = true;
local followtype = 0;
local del = 0;
local del2 = 0;
function onCreatePost()
	local xx = getProperty('dad.cameraPosition.x');
	local yy = getProperty('dad.cameraPosition.y');
	local xx2 = getProperty('boyfriend.cameraPosition.x');
	local yy2 = getProperty('boyfriend.cameraPosition.y');
end

function onUpdate()
...
```

**Comment by HappyAlexRomania** [comment]
It's working. It worked but I didn't notice it. I had to do debugPrint(xx) to see if it was working or not. Thanks!
