### ISSUE TITLE
Can I make custom keybinds using Lua?

### ISSUE THREAD

**Issue by HappyAlexRomania** [ShadowMario/FNF-PsychEngine#13013]
### Describe your problem here.

I want to make a block key, but the 'space' control doesn't work and 'accept' control also executes when pausing the game. Is it possible to make custom controle using Lua?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I added a script that makes the player block using a shield by pressing space, but I need help with the keybind

**Comment by Draconic-Hybrid** [comment]
`getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SPACE')`
