### ISSUE TITLE
RunHaxeCode can only run once

### ISSUE THREAD

**Issue by flashintv** [ShadowMario/FNF-PsychEngine#13012]
### Describe your bug here.

Trying to run more than 1 `runHaxeCode` in a lua file, will not work past 0.6.3 versions.
This is because 0.6.3 initialized HScript and then ran the code, while the newer versions initialize HScript and run the code in the same function. Normally this wouldn't be a problem if the function didn't look like this:
`	public static function initHaxeModuleCode(parent:FunkinLua, code:String)`
`	{`
`		#if (SScript >= "3.0.0")`
`		if(parent.hscript == null)`
`		{`
`			trace('initializing haxe interp for: ${parent.scriptName}');`
`			parent.hscript = new HScript(parent, code);`
`		}`
`		#end`
`	}`
because once it runs `parent.hscript` isn't `null` anymore and then the code will never be able to be ran using `runHaxeCode` in LUA.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by TheRealPepsi** [comment]
Interesting. What happens when running it twice? Does it crash? Or just do nothing? (Asking this because this could be the issue to a problem I'm having)

**Comment by EytanZury** [comment]
> Interesting. What happens when running it twice? Does it crash? Or just do nothing? (Asking this because this could be the issue to a problem I'm having)

It just does nothing.
