### ISSUE TITLE
hitsound when pressing custom notes

### ISSUE THREAD

**Issue by mapleeeeeeeeeeeeee** [ShadowMario/FNF-PsychEngine#1302]
### Describe your problem here.

**How do you make a sound play when you hit a custom note type like the bullet notes in hank challenge?**

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by Ordinary3** [comment]
make sure you make a folder called sounds inside the mods folder and put ur sound in ogg inside there and add this to ur lua note
function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'yournotehere' then
		playSound('notice', 1)
	end
end

**Comment by PDL2CGamejolt** [comment]
> make sure you make a folder called sounds inside the mods folder and put ur sound in ogg inside there and add this to ur lua note function goodNoteHit(id, noteData, noteType, isSustainNote) if noteType == 'yournotehere' then playSound('notice', 1) end end

how do i make it play

**Comment by HafimieForever** [comment]
> > make sure you make a folder called sounds inside the mods folder and put ur sound in ogg inside there and add this to ur lua note function goodNoteHit(id, noteData, noteType, isSustainNote) if noteType == 'yournotehere' then playSound('notice', 1) end end
> 
> how do i make it play

LMAOOO JUST PUT IT ON UR CUSTOM NOTE AND IT WILL PLAY WHEN YOU PRESS IT💀💀💀💀💀💀
