### ISSUE TITLE
Too Many Errors

### ISSUE THREAD

**Issue by WinV-Bros** [ShadowMario/FNF-PsychEngine#13027]
### Describe your problem here.

help:
source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
C:/HaxeToolkit/haxe/lib/linc_luajit/git/llua/State.hx:11: characters 24-49 : You cannot access the cpp package while in a macro (for cpp.RawPointer)
C:/HaxeToolkit/haxe/lib/linc_luajit/git/llua/Lua.hx:4: characters 8-18 : ... referenced here
C:\Users\winst\Downloads\FNF-PsychEngine-0.7.1h\FNF-PsychEngine-0.7.1h\source\import.hx:10: characters 8-16 : ... referenced here
C:\Users\winst\Downloads\FNF-PsychEngine-0.7.1h\FNF-PsychEngine-0.7.1h\source\import.hx:4: characters 8-23 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/media/AudioSource.hx:138: characters 53-100 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/media/Sound.hx:14: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/utils/Assets.hx:9: characters 8-26 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/text/_internal/TextEngine.hx:9: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/display/_internal/CairoTextField.hx:3: characters 8-40 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/display/_internal/CairoGraphics.hx:6: characters 8-36 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/events/RenderEvent.hx:4: characters 8-44 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/display/DisplayObject.hx:13: characters 8-33 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,2,1/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SrtHero278** [comment]
for the first issue,
```
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
```
for the second issue,
- go to `import.hx`
- add `#if !macro` to the beginning of the file
- add `#end` to the end of the file

**Comment by WinV-Bros** [comment]
It works now! tysm :)

**Comment by CrisDaBruhMan** [comment]
> para el primer número,
> 
> ```
> haxelib remove linc_luajit
> haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
> ```
> 
> para el segundo número,
> 
> * ir a`import.hx`
> * agregar `#if !macro`al principio del archivo
> * agregar `#end`al final del archivo



> for the first issue,
> 
> ```
> haxelib remove linc_luajit
> haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
> ```
> 
> for the second issue,
> 
> * go to `import.hx`
> * add `#if !macro` to the beginning of the file
> * add `#end` to the end of the file

Where is ¨import.hx¨ located?

**Comment by ashhmillr** [comment]
/sourse/import.hx
