### ISSUE TITLE
How to replace the appearance of the Health bar in 0.6

### ISSUE THREAD

**Issue by Baumey72** [ShadowMario/FNF-PsychEngine#13026]
### Describe your problem here.

Hello, I'm here because I want to know how I can replace the appearance of the health bar with another and that the icon colors work on it.
I tried to do it, but it gives me an error and the game closes, I tried it in all possible ways but nothing.
Can you give me a solution?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JokeBambi** [comment]
if ur below 0.6.3 sorry we cant help you

**Comment by Dsyboot** [comment]
you try to change the texture of the healthbar and put it in your mod folder?

**Comment by Mawtr** [comment]
I use this script from AquaStrikr in my mod. It puts a image that can be used as a border for the heathbar. You might need to change the numbers as I used this for a longer healthbar.


-- Script by AquaStrikr (https://twitter.com/AquaStrikr_)
function onCreatePost()
	makeLuaSprite('Health', 'your-image')
	setObjectCamera('Health', 'hud')
	addLuaSprite('Health', true)
	setObjectOrder('Health', getObjectOrder('healthBar') + 1)
	setProperty('healthBar.visible', true)
end

function onUpdatePost(elapsed)
	setProperty('Health.x', getProperty('healthBar.x') - 3)
	setProperty('Health.y', getProperty('healthBar.y') - 24)
end

**Comment by Jahwsome** [comment]
would anyone know how to do this in 1.0?

**Comment by Epic-Mawer** [comment]
I assume you just replace the setObjectCamera() with setProperty('Health.camera', instanceArg('camHUD'), true, true)

**Comment by Jahwsome** [comment]
yeah but the hp colours don't fill the bar and the original bar isn't replaced
