### ISSUE TITLE
song length change??

### ISSUE THREAD

**Issue by ColinGamingYT** [ShadowMario/FNF-PsychEngine#13021]
### What is your question?

is there a way to change the max song length in the source code??????

**Comment by Dsyboot** [comment]
Yes, in PlayState.hx search the var "songLength", but i don't know how to change when the song started, it's better to use a Lua Script and call it in your song, just add this shit:

addHaxeLibrary('flixel.FlxG')
addHaxeLibrary('flixel.system.FlxSound')
runHaxeCode([[
    game.songLength = (val * 1000);
]])

val it's the seconds of your song, you can add that code in the function "onSongStart()":

function onSongStart()
  --the mentionated code
end
