### ISSUE TITLE
Modpack Version Attribute / Backwards Compatibility Option

### ISSUE THREAD

**Issue by ToasterCoaster5** [ShadowMario/FNF-PsychEngine#13032]
### What feature do you want to get added on the **base** engine?

In an attempt to combat issues that involve updates rendering some modpacks unusable, it might be useful to create a feature to contrast modpacks from their individual versions. This would involve future modpacks having a new attribute in their main .json file, identifying the engine version which it was sourced from and displaying it upon viewing the modpack. Then, the engine could identify legacy attributes in pack data, and automatically label older modpacks accordingly (perhaps with a warning that certain features are not functioning as a result).

To take this concept a step further, we could use this new attribute to determine how to treat individual packs when they are run in the code. the engine can once again sense these old attributes within the data, and it could be trained to acknowledge these legacy values, translating it into the current-version equivalent upon reading it. Alternatively, a different way to attack this could be to once again sense these legacy attributes, and directly change the pack code upon 'activation' into the engine.

I'm not a HaxeFlixel expert or anything, so I don't have any idea as to how difficult this type of concept inclusion would be to apply, how it would affect the code optimization, any of that jazz. This has probably been requested previously, but sometimes the best ideas come from the most obvious places.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
I'm sure it would affect optimization, i'd rather just not do it
