### ISSUE TITLE
Not hitting a certain note takes you to a different song

### ISSUE THREAD

**Issue by hotpocketsarepoggers** [ShadowMario/FNF-PsychEngine#13030]
### Describe your problem here.

So I have a song that has a special note and I was wondering how I can make it so if you do not hit any of the notes during the whole song at the end it loads a different song

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Draconic-Hybrid** [comment]
```lua
noteHit = false

function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == '[name of your note]'
		noteHit = true
	end
end

function onEndSong()
	if not noteHit then
		loadSong('[songName]')
	end
end

```
