### ISSUE TITLE
How do i change the opponents arrows looks apart from bf's

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#1303]
### Describe your problem here.

how do i make it without source code?

I saw it like dave and bambi.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I am making V.S. Anne Remastered.

**Comment by ShadowMario** [comment]
![](https://user-images.githubusercontent.com/44785097/143148916-09b2e40c-7559-4075-8b5b-cc8bb2c306b5.png)
