### ISSUE TITLE
сompile help

### ISSUE THREAD

**Issue by TarnSpill** [ShadowMario/FNF-PsychEngine#13036]
### Describe your problem here.

no matter what gives this error:

Haxe language server started
Haxe Path: haxe.exe
Using --server-connect
Haxe connected!
Listening on port 6000
Failed - try fixing the error(s) and restarting the language server:

(unknown) : Type not found : openfl.utils._internal.ExtraParamsMacro

I have already reinstalled everything from 0, the error does not go away

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by mcagabe19** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions
