### ISSUE TITLE
Psych Engine 0.6.3 hxCodec is Broken????? idk

### ISSUE THREAD

**Issue by Honton129** [ShadowMario/FNF-PsychEngine#13045]
### Describe your bug here.

So i am coding my mod in psych engine 0.6.3 (too lazy to port) and after update the libraries and stuff because the engine was like "i dont wanna compile" the videos started to have issues like an error popup when i first see a video on the game or the fact that videos doesn't loop.

yes, i changed to various versions (2.6.0, 2.5.1, git and 3.0.2)
and fixed the popup error and loop error but now i got a error that causes the game crash after the video play for the 3- 6 time while changing menus and getting get_buffer related errors.

The PopUp (i checked if the library was there and it is)
![imagen_2023-08-08_202002203](https://github.com/ShadowMario/FNF-PsychEngine/assets/85850584/2971ecd3-6d11-4d01-a2ef-f862a34fd464)

### Command Prompt/Terminal logs (if existing)

```bash
[h264 @ 00000162e6bf3280] get_buffer() failed
[h264 @ 00000162e6bf3280] thread_get_buffer() failed
[h264 @ 00000162e6bf3280] decode_slice_header error
[h264 @ 00000162e6bf3280] no frame!
[h264 @ 00000162e6bf0940] get_buffer() failed
[h264 @ 00000162e6bf0940] thread_get_buffer() failed
[h264 @ 00000162e6bf0940] decode_slice_header error
[h264 @ 00000162e6bf0940] no frame!
[h264 @ 00000162e7e7e8c0] get_buffer() failed
[h264 @ 00000162e7e7e8c0] thread_get_buffer() failed
[h264 @ 00000162e7e7e8c0] decode_slice_header error
[h264 @ 00000162e7e7e8c0] no frame!
[h264 @ 00000162e7e7ed40] get_buffer() failed
[h264 @ 00000162e7e7ed40] thread_get_buffer() failed
[h264 @ 00000162e7e7ed40] decode_slice_header error
[h264 @ 00000162e7e7ed40] no frame!
[h264 @ 00000162ee828480] get_buffer() failed
[h264 @ 00000162ee828480] thread_get_buffer() failed
[h264 @ 00000162ee828480] decode_slice_header error
[h264 @ 00000162ee828480] no frame!
[h264 @ 00000162ee828900] get_buffer() failed
[h264 @ 00000162ee828900] thread_get_buffer() failed
[h264 @ 00000162ee828900] decode_slice_header error
[h264 @ 00000162ee828900] no frame!

 *  El proceso del terminal "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command lime test windows --connect 6000" finalizó con el código de salida 1. 
 *  Las tareas reutilizarán el terminal, presione cualquier tecla para cerrarlo.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Most of the Files like PlayState and The Menus Looks but nothing related to the libraries codes, just the versions of them for compile lol

**Comment by RandomGuy4312** [comment]
The first one also happens to me and I deleted the file in the bin and recompiled it and the error went away, although after a while it comes out again but it is the only temporary way I know, the second one I don't know

**Comment by Honton129** [comment]
yeah, did that and solved the plugin thing but now the console keeps dropping that error and after 3-4 times from traveling trought menus the game crashes.
no idea why

**Comment by RandomGuy4312** [comment]
If you still have problems with that, I think I can help you now, I found something to download all the requirements and also change various things in the files, the game no longer crashes when I switch between menus, if you want to talk faster we can use discord

**Comment by Honton129** [comment]
oh sure why not
that would help me a lot
this is my discord: honton129

> If you still have problems with that, I think I can help you now, I found something to download all the requirements and also change various things in the files, the game no longer crashes when I switch between menus, if you want to talk faster we can use discord

**Comment by Honton129** [comment]
ok so externally we find out hxcodec just sucks only at mp4sprites wich is we got the problem lol
so i will just close this thing as not fixed and maybe when i found a solution or something i will comment it here
