### ISSUE TITLE
0.7.1h compiling error

### ISSUE THREAD

**Issue by twsity** [ShadowMario/FNF-PsychEngine#13047]
### Describe your problem here.

i suck at stuff so i dont know what to do

/usr/local/lib/haxe/std/sys/Http.hx:534: characters 4-9 : Uncaught exception X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
/usr/local/lib/haxe/std/sys/Http.hx:67: characters 4-14 : Called from here
/usr/local/lib/haxe/std/sys/Http.hx:253: characters 12-25 : Called from here
/usr/local/lib/haxe/std/sys/Http.hx:70: characters 3-30 : Called from here
/usr/local/lib/haxe/std/sys/Http.hx:536: characters 3-19 : Called from here
/Users/name/Downloads/FNF-PsychEngine-main-3/.haxelib/SScript/4,1,0/src/tea/backend/SScriptVer.hx:29: characters 45-142 : Called from here
/Users/name/Downloads/FNF-PsychEngine-main-3/.haxelib/SScript/4,1,0/src/macro/Macro.hx:44: characters 3-21 : Called from here
(unknown) : Called from here

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

if the folder name counts, then yes, i added -3 to the main folder because thats the third psych engine main folder i have

**Comment by WolfyTail** [comment]
Me too.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/95707370/04cdf733-3a75-4e82-87ef-41f6d491b0e8)
