### ISSUE TITLE
Can't add songs in 0.7.1h

### ISSUE THREAD

**Issue by 4stacks67** [ShadowMario/FNF-PsychEngine#13041]
### Describe your problem here.

I Added a song in the template mod, and it wouldn't work, if this doesn't work i'm just sticking to another engine i guess.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I Extracted Template Mod

**Comment by Draconic-Hybrid** [comment]
the music goes in `mod/songs`, not `mod/music`

**Comment by 4stacks67** [comment]
No i did everything i can even see my week or songs

**Comment by Draconic-Hybrid** [comment]
Need more information. How does it not work?

**Comment by 4stacks67** [comment]
So when i see my mod in the mods section of the engine it doesnt work i enabled it and nothing

**Comment by Draconic-Hybrid** [comment]
Do the songs not show up in the Story Mode/Freeplay menu?

**Comment by 4stacks67** [comment]
no it doesnt

**Comment by Draconic-Hybrid** [comment]
Can you load your mod's assets from the main menu? (Press 7 on the main menu and press right or left till your mod shows up at the body)

**Comment by 4stacks67** [comment]
thanks

**Comment by Draconic-Hybrid** [comment]
Did your songs show up again?

**Comment by 4stacks67** [comment]
hold on

**Comment by TankmanUtah** [comment]
same problems happening to me, i'm trying to add a song from starecrown definitive edition to the newest psych engine version but it doesn't do shit
