### ISSUE TITLE
something is wrong with the source thats stopping me from compiling a psych engine build

### ISSUE THREAD

**Issue by Geniusbutfnf** [ShadowMario/FNF-PsychEngine#13049]
### Describe your problem here.

<img width="567" alt="Screenshot 2023-08-08 at 11 39 01 PM" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/112906755/18e31a9a-2eb2-4f53-8510-463a6795cacb">
ive been getting this error for a while and i still dont know what to do 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by 12abz** [comment]
use this:
haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git
haxelib install flixel-addons 3.0.2
haxelib install flixel-tools 1.5.1
haxelib install flixel-ui 2.5.0
haxelib install flixel 5.2.2
haxelib install hscript 2.5.0
haxelib install hxCodec 2.5.1
haxelib install lime 8.0.1
haxelib run lime setup
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git
haxelib install openfl 9.2.1
