### ISSUE TITLE
How do i make a animated freeplay background?

### ISSUE THREAD

**Issue by jack-dutchie** [ShadowMario/FNF-PsychEngine#13040]
### Describe your problem here.

so i wanted to make a animated freeplay background but i dont know how to make that so i need help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Chidubemmo** [comment]
You can't

**Comment by Chidubemmo** [comment]
1. Make the background in animate/flash
2. Export it  as a spritesheet.
3. Go inside FreeplayState.hx 
4. Around line 110  you should find this line of code `bg = new FlxSprite().loadGraphic(Paths.image('menuDesat'));`, replace it with 
```hx
bg.frames = Paths.getSparrowAtlas('filepath of the bg');
bg.animation.addbyPrefix('a name for the animation', 'name on xml', framerate, true);
```

**Comment by jack-dutchie** [comment]
> 1. Make the background in animate/flash
> 2. Export it  as a spritesheet.
> 3. Go inside FreeplayState.hx
> 4. Around line 110  you should find this line of code `bg = new FlxSprite().loadGraphic(Paths.image('menuDesat'));`, replace it with
> 
> ```hx
> bg.frames = Paths.getSparrowAtlas('filepath of the bg');
> bg.animation.addbyPrefix('a name for the animation', 'name on xml', framerate, true);
> ```

how do i get source?

**Comment by Chidubemmo** [comment]
[Download it here](https://github.com/ShadowMario/FNF-PsychEngine/archive/refs/heads/main.zip),
[Install VS Code](https://code.visualstudio.com) and follow the instrunction in the [readme.md file](https://github.com/ShadowMario/FNF-PsychEngine)

**Comment by jack-dutchie** [comment]
> [Download it here](https://github.com/ShadowMario/FNF-PsychEngine/archive/refs/heads/main.zip), [Install VS Code](https://code.visualstudio.com) and follow the instrunction in the [readme.md file](https://github.com/ShadowMario/FNF-PsychEngine). After installing and editing the source code open the build_x64.bat or if you don't have a windows computer use `'lime build mac'` or `'lime build linux'` on the command prompt/powershell

ok so uh how do i use the file path of the bg

**Comment by Chidubemmo** [comment]
just replace 'filepath of the bg' with the name of the spritesheet, it should be shared/images

**Comment by jack-dutchie** [comment]
> just replace 'filepath of the bg' with the name of the spritesheet, it should be shared/images

is there any vids that could also help me

**Comment by Chidubemmo** [comment]
Do you have the animated spritesheet?

**Comment by jack-dutchie** [comment]
> Do you have the animated spritesheet?

yes

**Comment by Chidubemmo** [comment]
did you put it in the images subfolder inside the shared folder ?

**Comment by jack-dutchie** [comment]
> did you put it in the images subfolder inside the shared folder ?

in the assets/images

**Comment by Chidubemmo** [comment]
if you name the bg for example 'stupid_bg' you should use
bg.frames = Paths.getSparrowAtlas('stupid_bg');
I hope you understand now

**Comment by jack-dutchie** [comment]
> if you name the bg for example 'stupid_bg' you should use bg.frames = Paths.getSparrowAtlas('stupid_bg'); I hope you understand now

for some reason i did that but it doesnt show up in the freeplay it only show the normal bg
i putted this in 

102          bg.frames = Paths.getSparrowAtlas('testbg');
103		bg.animation.addbyPrefix('idle', 'idle', 1, true);
104		add(bg)
but i treid without the add bg and still nothing

**Comment by Chidubemmo** [comment]
Wait why is the framerate at 1fps?

**Comment by jack-dutchie** [comment]
> Wait why is the framerate at 1fps?

uh i am gonna change that i accidentally used 1

**Comment by Chidubemmo** [comment]
Pass me the spritesheet and the xml?

**Comment by jack-dutchie** [comment]
> Can you Pass me the spritesheet and the xml?

ok wait

**Comment by jack-dutchie** [comment]
> Can you Pass me the spritesheet and the xml?

wait how?

**Comment by jack-dutchie** [comment]
> send me like drive or mega.nz link

ok

**Comment by jack-dutchie** [comment]
https://drive.google.com/drive/folders/1MLB1SWSiNkktw05aZimC199GV9bfxLGq?usp=drive_link

> send me like drive or mega.nz link

**Comment by Chidubemmo** [comment]
i don't have acess

**Comment by jack-dutchie** [comment]
oh wait

**Comment by jack-dutchie** [comment]
now?

**Comment by jack-dutchie** [comment]
> i don't have acess

hello you there?

**Comment by Chidubemmo** [comment]
Figured it out... I think. It plays for me. 
The only thing wrong is that the xml is incorrect there's a line of code that says 'imagepath=sky.png' even though it should be imagepath=testbg.png since it's the name of the spritesheet. I was trying to figure out what was wrong since I'm not an expert. Just replace everything with the code below

```hx
bg = new FlxSprite().loadGraphic(Paths.image('testbg', 'shared'), true);
bg.frames = Paths.getSparrowAtlas('testbg', 'shared');
bg.animation.addByPrefix('idle', 'idle', 12); //Or whatever is the fps idgaf
bg.animation.play('idle');
bg.antialiasing = ClientPrefs.globalAntialiasing;
add(bg);
bg.screenCenter();
```

**Comment by jack-dutchie** [comment]
> Figured it out... I think. It plays for me. The only thing wrong is that the xml is incorrect there's a line of code that says 'imagepath=sky.png' even though it should be imagepath=testbg.png since it's the name of the spritesheet. I was trying to figure out what was wrong since I'm not an expert. Just replace everything with the code below
> 
> ```hx
> bg = new FlxSprite().loadGraphic(Paths.image('testbg', 'shared'), true);
> bg.frames = Paths.getSparrowAtlas('testbg', 'shared');
> bg.animation.addByPrefix('idle', 'idle', 12); //Or whatever is the fps idgaf
> bg.animation.play('idle');
> bg.antialiasing = ClientPrefs.globalAntialiasing;
> add(bg);
> bg.screenCenter();
> ```

im sorry man but i literally did not read or did the build instructions but im now stuck on a command that says 'haxelib' is not recognized as an internal or external command,
operable program or batch file. how do i fix

**Comment by jack-dutchie** [comment]
sorry for wasting your time but can you help me with that

**Comment by Chidubemmo** [comment]
[You didn't install haxe 4.2.5 (or any version for that matter)](https://haxe.org/download/version/4.2.5/)

**Comment by jack-dutchie** [comment]
nvm it worked
i had to reopen

**Comment by jack-dutchie** [comment]
> [You didn't install haxe 4.2.5 (or any version for that matter)](https://haxe.org/download/version/4.2.5/)

hey uh im having issues with my source it says 
source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
