### ISSUE TITLE
Problems running "hmm install"

### ISSUE THREAD

**Issue by ouie1st** [ShadowMario/FNF-PsychEngine#13056]
### Describe your problem here.

<img width="868" alt="Screenshot 2023-08-10 094145" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/141913098/f734e3b3-a7b4-44a3-8274-fa1e9f7573c2">
uh so i dont know how to put this but i cant seem to be able to run hmm install because it says that hmm.json couldn't be found in the directory and i dont know how to solve this. should i download hmm.json from somewhere else or is this something outside your realm of knowledge?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i haven't even been able to mess with psych yet :(

**Comment by ouie1st** [comment]
also btw im a boy and my sister lent me her old account to use since she literally hasn't touched in forever

**Comment by mcagabe19** [comment]
you have to cd into source after do ``haxelib run hmm install``

**Comment by GreenSoupDeveloper** [comment]
> you have to cd into source after do `haxelib run hmm install`

cd to source where
