### ISSUE TITLE
OUTDATED LINK

### ISSUE THREAD

**Issue by Alltoupload** [ShadowMario/FNF-PsychEngine#13051]
### Describe your problem here.

The Mod Template's link is outdated
Please, give me a link to download or (for ShadowMario) UPDATE THE LINK GOD DAMNIT
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/101133556/43a80762-d173-4ddb-9e8f-7b0188f58af4)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by HappyAlexRomania** [comment]
I think it's in the Psych Engine files. There's a ZIP file in the 'mods' folder. It's only there in 0.7+ but I think they're compatible with older versions of Psych if you want the template for an older version of Psych

**Comment by MrRainbowCoding** [comment]
Let me help you, it looks like that you want the raw code of [modTemplate.zip](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/example_mods/modTemplate.zip). You can view it by going to this link [here](https://github.com/ShadowMario/FNF-PsychEngine/raw/main/example_mods/modTemplate.zip). (it'll just download it though)

**Comment by Alltoupload** [comment]
Nevermind
