### ISSUE TITLE
how do i hide ratings?

### ISSUE THREAD

**Issue by PumpkinSheee** [ShadowMario/FNF-PsychEngine#13058]
### What is your question?

i honestly dont know how to disable these in lua, and before you comment yes i have seen the other post about this, and no it did not work for me, everytime i would use it in a script i would just get this error:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/109385410/2f18522c-b39d-4214-8e5d-925da8498f3d)
so what should i do? im on psych 0.7.1h

**Comment by Draconic-Hybrid** [comment]
What do you mean "ratings"? Do you mean the text below the healthbar?

**Comment by PumpkinSheee** [comment]
> What do you mean "ratings"? Do you mean the text below the healthbar?

no the "sick, good, bad, shit" and the combo numbers that appear everytime you hit a note

**Comment by Draconic-Hybrid** [comment]
This is doable without code. All you need is a transparent image.

Place the image in `mods/[mod name]/images`, and duplicate it 13 times. You should have 14 copies of this image.

Name the images as follows:
`num0.png`
`num1.png`
`num2.png`
`num3.png`
`num4.png`
`num5.png`
`num6.png`
`num7.png`
`num8.png`
`num9.png`
`sick.png`
`good.png`
`bad.png`
`shit.png`

Psych Engine automatically replaces default assets with ones in your mod, so in theory having a transparent image as these assets should solve the problem.

**Comment by PumpkinSheee** [comment]
> This is doable without code. All you need is a transparent image.
> 
> Place the image in `mods/[mod name]/images`, and duplicate it 13 times. You should have 14 copies of this image.
> 
> Name the images as follows: `num0.png` `num1.png` `num2.png` `num3.png` `num4.png` `num5.png` `num6.png` `num7.png` `num8.png` `num9.png` `sick.png` `good.png` `bad.png` `shit.png`
> 
> Psych Engine automatically replaces default assets with ones in your mod, so in theory having a transparent image as these assets should solve the problem.

shit why didnt i think of that, thanks

**Comment by Dsyboot** [comment]
> > This is doable without code. All you need is a transparent image.
> > Place the image in `mods/[mod name]/images`, and duplicate it 13 times. You should have 14 copies of this image.
> > Name the images as follows: `num0.png` `num1.png` `num2.png` `num3.png` `num4.png` `num5.png` `num6.png` `num7.png` `num8.png` `num9.png` `sick.png` `good.png` `bad.png` `shit.png`
> > Psych Engine automatically replaces default assets with ones in your mod, so in theory having a transparent image as these assets should solve the problem.
> 
> shit why didnt i think of that, thanks

Why you don't just use this?

```lua
function onCreatePost()
   setProperty('showRating', false);
   setProperty('showComboNum', false);
end
```
