### ISSUE TITLE
Game Over sprite and music change not working!

### ISSUE THREAD

**Issue by Loganthegamer12678** [ShadowMario/FNF-PsychEngine#13066]
### Describe your bug here.

I was working on a mod, and when I die in one of the songs, the sprites and music DID NOT FUCKING CHANGE, all I see is BF getting blue-balled and the default death sound and game over music!

### Command Prompt/Terminal logs (if existing)

```bash
function onCreate()
	setPropertyFromClass('GameOverSubstate', 'characterName', 'jotaro'); --Character json file for the death animation
	setPropertyFromClass('GameOverSubstate', 'deathSoundName', 'fnf_loss_sfx-jojo'); --put in mods/sounds/
	setPropertyFromClass('GameOverSubstate', 'loopSoundName', 'gameOver'); --put in mods/music/
	setPropertyFromClass('GameOverSubstate', 'endSoundName', 'gameOverEnd'); --put in mods/music/
end

(I do not own the sprite or character)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Not a bug
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7

**Comment by Draconic-Hybrid** [comment]
Change `GameOverSubstate` to `substates.GameOverSubstate`

**Comment by Loganthegamer12678** [comment]
> Change `GameOverSubstate` to `substates.GameOverSubstate`

Thank you and goodbye. (Late but still)
