### ISSUE TITLE
Gf speakers are not behind the limo

### ISSUE THREAD

**Issue by qdartheawesomeman** [ShadowMario/FNF-PsychEngine#13064]
The Week 4 GF isn't behind the front limo
Yeah so In week 4 gf is not behind the limo like in the original fnf. it looks like a graphical bug.
![Screenshot 2023-08-11 13-24-23](https://github.com/ShadowMario/FNF-PsychEngine/assets/71853801/2dab065d-603a-425c-8b21-d19faadfbfe6)
![maxresdefault](https://github.com/ShadowMario/FNF-PsychEngine/assets/71853801/6bd90377-cb0c-46ff-8450-fb4b00082df8)

would you please fix it in the new psych engine version. thank you.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i haven't

**Comment by MemeHovy** [comment]
this isn’t a bug, shadowmario likes it that way

**Comment by qdartheawesomeman** [comment]
> 

I Know but it actually feels off.
