### ISSUE TITLE
how can i play annimations while the 3,2,1 go thing happens

### ISSUE THREAD

**Issue by PumpkinSheee** [ShadowMario/FNF-PsychEngine#13068]
### What is your question?

like at the start of a song when it goes 3, 2, 1, GO, like in pibby apocalypse when bf reloads his gun at the start of a song, is there a way to use lua to do this?

**Comment by ckwood23** [comment]
Write a lua script to load the animation before the intro. Just ask if you need me to do that for you.

**Comment by PumpkinSheee** [comment]
> Write a lua script to load the animation before the intro. Just ask if you need me to do that for you.

yeah pls i dont know how to write lua yet im still learning so if you could that would be niceee

**Comment by ckwood23** [comment]
> > Write a lua script to load the animation before the intro. Just ask if you need me to do that for you.
> 
> yeah pls i dont know how to write lua yet im still learning so if you could that would be niceee

local allowCountdown = false

function onStartCountdown()
	
	if not allowCountdown and isStoryMode and not seenCutscene then
        
		setProperty('inCutscene', true);
		runTimer('beforeCountdownAnim', 2, 1) -- change this to your animation length
		allowCountdown = true;
        runTimer('animPlayed', 4, 1) -- change this to your animation length
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'beforeCountdownAnim' then 
       characterPlayAnim('character','anim',true) -- change this to whatever you want
	end
    
    if tag == 'animPlayed' then -- the animation has finished, so we now start the countdown.
        startCountdown();
    end
end

**Comment by PumpkinSheee** [comment]
> 

Thanks man! i did some editing acc using my basic lua knowledge lmao, so it works in freeplay and also plays it DURING the 321 go bit, heres the code cuz why now lmao:

`local allowCountdown = false

function onStartCountdown()

if not allowCountdown and not seenCutscene then
    
	setProperty('inCutscene', false);
	runTimer('beforeCountdownAnim', 1, 1) -- change this to your animation length
	allowCountdown = true;
	startCountdown();
    runTimer('animPlayed', 5, 5) -- change this to your animation length
	return Function_Stop;
end
return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
if tag == 'animPlayed' then
startCountdown();
characterPlayAnim('bf','still',true) -- change this to whatever you want
end
end`
