### ISSUE TITLE
How to Make a ScoreText Like Vs Impostor's Defeat

### ISSUE THREAD

**Issue by IRIHAYA-MAIN** [ShadowMario/FNF-PsychEngine#13063]
### Describe your problem here.

I keep looking for a way to select the number of Misses and have the score text change according to that number of Misses, like Defeat in Vs Impostor, but I can't find it! Please help.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Draconic-Hybrid** [comment]
(This is assuming you want a miss limit of five)
```lua
function onCreate()
    makeLuaText('missCounter', 'Misses: 0/5', 1000, [custom x-value here], [custom y-value here])
end

function onUpdate()
    setTextString('missCounter', 'Misses: ' ..misses.. '/5')
end
```

**Comment by IRIHAYA-MAIN** [comment]
> (これはミス制限を 5 にしたいと仮定しています)
> 
> ```lua
> function onCreate()
>     makeLuaText('missCounter', 'Misses: 0/5', 1000, [custom x-value here], [custom y-value here])
>     addLuaText('missCounter')
> end
> 
> function onUpdate()
>     setTextString('missCounter', 'Misses: ' ..misses.. '/5')
> 
>     if misses > 5 then
>         setProperty('health', 0)
>     end
> end
> ```

Thanks, I'll try to make one based on this.
