### ISSUE TITLE
how can i enable/disable shaders in lua?

### ISSUE THREAD

**Issue by PumpkinSheee** [ShadowMario/FNF-PsychEngine#13072]
### What is your question?

kinda hard to explain but basically i have a shader script and i wanna enable it using lua so that i can use it as an event that can enable it mid song, anyone know how to do this? (and if you can write it for me that would be epic)

**Comment by Draconic-Hybrid** [comment]
What does the shader script look like?

**Comment by PumpkinSheee** [comment]
> What does the shader script look like?

function onCreate()
    makeLuaSprite('shaders')
    initLuaShader('glitch')
    setSpriteShader('shaders', 'glitch')
    runHaxeCode([[
        shader0 = game.modchartSprites.get('shaders').shader;
        game.camGame.setFilters([new ShaderFilter(shader0)]);
        game.getLuaObject("shaders").shader = shader0;
        game.camHUD.setFilters([new ShaderFilter(game.getLuaObject("shaders").shader)]);
        return;
    ]])
end

function onUpdate(elapsed)
    setShaderFloat("shaders", "iTime", os.clock())
 end
    
    local temp = onDestroy
    function onDestroy()
        runHaxeCode([[
            FlxG.signals.gameResized.remove(fixShaderCoordFix);
            return;
        ]])
        if (temp) then temp() 
     end
end

**Comment by Draconic-Hybrid** [comment]
Ah. I'm not skilled with any sort of Haxe code, sorry.

**Comment by PumpkinSheee** [comment]
> Ah. I'm not skilled with any sort of Haxe code, sorry.

ah, ok it does work as a lua script though, it is softcoded so is there a way to disable/enable seperate lua files within an event?

**Comment by Draconic-Hybrid** [comment]
If the files have to be two different files, you could try `removeLuaScript` but I'm not entirely sure how that one works.

If you're able to keep it in one file, (and both values for the Event aren't occupied by something else) you could make one of the values for the event enable/disable the shaders.

**Comment by frantastic24** [comment]
`setProperty('camGame.filtersEnabled', false)`

**Comment by PumpkinSheee** [comment]
> `setProperty('camGame.filtersEnabled', false)`
that doesnt work, it just gives a null onject reference error, but it doesnt matter lmao i found the answer here:
https://gamebanana.com/questions/39926
