### ISSUE TITLE
Could not load module error.

### ISSUE THREAD

**Issue by SwirlyStone5877** [ShadowMario/FNF-PsychEngine#13078]
### Describe your bug here.

When I launch it, it gives me the following error:
Could not load module lime@lime_application_create__prime
Weird as hell. 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I tried to fix it by changing lime.ndll's file name to lime.dll, then to lime (no extension), but that didn't work.

**Comment by MemeHovy** [comment]
corrupted lime.ndll, and don’t tamper with the file name, it’s supposed to be like that

**Comment by SwirlyStone5877** [comment]
oh
so
do i get one from a previous version

**Comment by MemeHovy** [comment]
do `lime rebuild windows`

**Comment by MemeHovy** [comment]
or whatever platform you're compiling to

**Comment by SwirlyStone5877** [comment]
huh
wait what command prompt (or program) do i use
also i didn't compile it i just downloaded it
i dont have the knowledge to compile [@?#!]

**Comment by MemeHovy** [comment]
> huh wait what command prompt (or program) do i use also i didn't compile it i just downloaded it i dont have the knowledge to compile [@?#!]

it says you're modding a build using source tf you mean

**Comment by SwirlyStone5877** [comment]
there wasnt an option to say "idfk man i just downloaded it"

**Comment by SwirlyStone5877** [comment]
> > huh wait what command prompt (or program) do i use also i didn't compile it i just downloaded it i dont have the knowledge to compile [@?#!]
> 
> it says you're modding a build using source tf you mean

there wasnt an option to say "idfk man i just downloaded it"

**Comment by Phansa** [comment]
Hey I ran into this same thing, I downloaded the 32 bit version of psych engine with a 64 bit windows pc and got your original error. I then installed the correct version and it worked. I also downloaded it from the release page and didn't built from source

I also installed  haxe from here but I think that was irrelevant ->
https://haxe.org/download/version/4.2.5/
