### ISSUE TITLE
how to start a video in a state? (SOURCE)

### ISSUE THREAD

**Issue by Noel3454565FNF** [ShadowMario/FNF-PsychEngine#13074]
### Describe your problem here.

how cna i start a video in a custom state (named E.hx) when you enter in this play state?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nop

**Comment by Chidubemmo** [comment]
Inside the state(literally a copy paste of the startVideo function)
```hx
var video:VideoHandler = new VideoHandler();
			#if (hxCodec >= "3.0.0")
			// Recent versions
			video.play(filepath);
			video.onEndReached.add(function()
			{
				video.dispose();
				MusicBeatState.switchState(new MainMenuState());
				return;
			}, true);
			#else
			// Older versions
			video.playVideo(filepath);
			video.finishCallback = function()
			{
				MusicBeatState.switchState(new MainMenuState());
				return;
			}
			#end
```

**Comment by mikoprimeb** [comment]
i made a custom state named IntroState and putted this code and i got  "source/states/IntroState.hx:6: characters 4-9 : Unexpected video"  how to fix it?

**Comment by MemeHovy** [comment]
> i made a custom state named IntroState and putted this code and i got "source/states/IntroState.hx:6: characters 4-9 : Unexpected video" how to fix it?

you didn’t put it inside a function

**Comment by mikoprimeb** [comment]
After i did this now im getting unexpected var error and when im deleting it its now "unexpected =" or "unexpected :" or "unexpected new" no matter in what line it is or when i added package states like in other states its just the same error

**Comment by mikoprimeb** [comment]
after updating haxe and sscript to newer version now its says: unexpected keyword var

**Comment by MemeHovy** [comment]
> After i did this now im getting unexpected var error and when im deleting it its now "unexpected =" or "unexpected :" or "unexpected new" no matter in what line it is or when i added package states like in other states its just the same error

omfg you are such a retard

**Comment by mikoprimeb** [comment]
dont tell me,  you are calling me a retard for something that didnt happen on my fault (or maybe it is), oh well i guees i need to figure it out myself

**Comment by MemeHovy** [comment]
it was, definitely was

**Comment by mikoprimeb** [comment]
So it was huh, then im gonna figure what i did wrong. Either that thanks for help
