### ISSUE TITLE
Multiple Text in Lua

### ISSUE THREAD

**Issue by Neown247** [ShadowMario/FNF-PsychEngine#13071]
### Describe your problem here.

I'm trying to make a judgment counter where I put more texts, but for some reason only the first one is visible in the game.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/140524238/d254aed9-6e06-47a1-a39b-dbe369700d2c)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
you arent even creating the good, bad, or shit texts

**Comment by Neown247** [comment]
> you arent even creating the good, bad, or shit texts

I saw that Sick doesn't work, so I didn't bother to do the rest...

**Comment by Dsyboot** [comment]
Just change the "onCreate" to "onCreatePost" and please don't use the reservated names (sicks, goods, bads) change it to (sicksTxt, goodsTxt, badsTxt) I guess this can help you 😸

**Comment by Neown247** [comment]
Its still not working, only Combo is visible :(

**Comment by Dsyboot** [comment]
>  Its still not working, only Combo is visible :(
> 

Hey wait a moment, you tried to change the "recalculateRating" to "onUpdate"?
