### ISSUE TITLE
Character Editor Error

### ISSUE THREAD

**Issue by CatOfTheDarkness** [ShadowMario/FNF-PsychEngine#13088]
### Describe your bug here.

I'm trying to add this character and everytime this happens:

![Captura de Tela (168)](https://github.com/ShadowMario/FNF-PsychEngine/assets/124204264/cf775c85-e7e3-42ad-a6ce-817a1e894130)

As you can see, the poses are the same as the text on .xml file. And I clicked "add/update" button. Can somebody help me?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

ya, but I didn't edited nothing about sprites, characters n' stuff

And I promise, that's my last issue for a while

**Comment by frantastic24** [comment]
Not a bug
XML animation name is wrong
`banana-killer BananaLeft`

**Comment by CatOfTheDarkness** [comment]
> Not a bug XML animation name is wrong `banana-killer BananaLeft`

I think its the character name because spritesheet generator and the animation name, but I'll try it

**Comment by CatOfTheDarkness** [comment]
> Not a bug XML animation name is wrong `banana-killer BananaLeft`

Anyways, I'm a dumbo!

**Comment by CatOfTheDarkness** [comment]
> banana-killer BananaLeft

Worked! Tysm man! Sorry about making an issue with an easy and obvious soluction! I'm a stupid idiot lol
