### ISSUE TITLE
im having trouble compiling the game

### ISSUE THREAD

**Issue by jack-dutchie** [ShadowMario/FNF-PsychEngine#13082]
### Describe your problem here.

every time i run the command lime test windows -debug i get this message
source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by jack-dutchie** [comment]
nvm fixed it

**Comment by ItzKony** [comment]
> nvm fixed it

how?
