### ISSUE TITLE
Tweens

### ISSUE THREAD

**Issue by Hazardows** [ShadowMario/FNF-PsychEngine#13085]
### Describe your problem here.

How can i make a custom tween ussing lua scripts?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Draconic-Hybrid** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers

**Comment by Hazardows** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers

I know all those yet, what i need is a tween for a custom value

**Comment by Draconic-Hybrid** [comment]
Define "custom value"

**Comment by Dsyboot** [comment]
``Heeeey, I recently make a script that allows you to do a tween in a normal vars, example: if you want your health to be 2 with increments automatically with a specific time you can do it with:

doTweenVar(tag, object, mewValue, time)

```lua
function onSongStart()
    doTweenVar("healup", "health", 2, 12)
end
```

In this example, your health will up to two in twelve seconds, this works with all vars like this:

```lua
local a = 5

function onSongStart()
   doTweenVar("upshit", "a", 20, 5)
end
```

In this example the var will change his value to 20 in five seconds.

There's a game banana link if you want to test it:

https://gamebanana.com/mods/463490

**Comment by Hazardows** [comment]
> Heeeey, I recently make a script that allows you to do a tween in a normal vars, example: if you want your health to be 2 with increments automatically with a specific time you can do it with:
> 
> doTweenVar(tag, object, mewValue, time)
> 
> ```lua
> function onSongStart()
>     doTweenVar("healup", "health", 2, 12)
> end
> ```
> 
> In this example, your health will up to two in twelve seconds, this works with all vars like this:
> 
> ```lua
> local a = 5
> 
> function onSongStart()
>    doTweenVar("upshit", "a", 20, 5)
> end
> ```
> 
> In this example the var will change his value to 20 in five seconds.
> 
> There's a game banana link if you want to test it:
> 
> https://gamebanana.com/mods/463490

Man thanks a lot, you saved me

**Comment by Dsyboot** [comment]
> > Heeeey, I recently make a script that allows you to do a tween in a normal vars, example: if you want your health to be 2 with increments automatically with a specific time you can do it with:
> > 
> > doTweenVar(tag, object, mewValue, time)
> > 
> > ```lua
> > function onSongStart()
> >     doTweenVar("healup", "health", 2, 12)
> > end
> > ```
> > 
> > In this example, your health will up to two in twelve seconds, this works with all vars like this:
> > 
> > ```lua
> > local a = 5
> > 
> > function onSongStart()
> >    doTweenVar("upshit", "a", 20, 5)
> > end
> > ```
> > 
> > In this example the var will change his value to 20 in five seconds.
> > 
> > There's a game banana link if you want to test it:
> > 
> > https://gamebanana.com/mods/463490
> 
> Man thanks a lot, you saved me

You're welcome, but I just realized I don't changed the doTweenVar.txt LOL, sorry if you see spanish, it's just because Spanish it's my native language. Btw I hope this is useful for you, but if you try to do Tween in a local var using triggerEvent the shit doesn't work, you need to put the code in your script sorry, idk how to fix that

**Comment by Hazardows** [comment]
> > > Heeeey, I recently make a script that allows you to do a tween in a normal vars, example: if you want your health to be 2 with increments automatically with a specific time you can do it with:
> > > 
> > > doTweenVar(tag, object, mewValue, time)
> > > 
> > > ```lua
> > > function onSongStart()
> > >     doTweenVar("healup", "health", 2, 12)
> > > end
> > > ```
> > > 
> > > In this example, your health will up to two in twelve seconds, this works with all vars like this:
> > > 
> > > ```lua
> > > local a = 5
> > > 
> > > function onSongStart()
> > >    doTweenVar("upshit", "a", 20, 5)
> > > end
> > > ```
> > > 
> > > In this example the var will change his value to 20 in five seconds.
> > > 
> > > There's a game banana link if you want to test it:
> > > 
> > > https://gamebanana.com/mods/463490
> > 
> > Man thanks a lot, you saved me
> 
> You're welcome, but I just realized I don't changed the doTweenVar.txt LOL, sorry if you see spanish, it's just because Spanish it's my native language. Btw I hope this is useful for you, but if you try to do Tween in a local var using triggerEvent the shit doesn't work, you need to put the code in your script sorry, idk how to fix that

Bueno pues te agradezco que me lo hayas dicho y yo también hablo español. El español también es mi lenguaje nativo.
