### ISSUE TITLE
How To Make Notes Move Like In Furiosity In A Lua Script

### ISSUE THREAD

**Issue by AcePlayzGamesYT** [ShadowMario/FNF-PsychEngine#1308]
### What is your question?

Does anyone know how to make the notes move like in Furiosity in a Lua script? https://www.youtube.com/watch?v=Uhp2nzubU44 to see how the notes move if you didn't know.

**Comment by ShadowMario** [comment]
![](https://user-images.githubusercontent.com/44785097/143148611-007f068e-9bc0-4d92-8f02-f41ed81aba1c.png)
