### ISSUE TITLE
[Lua] Can I import Variables from other scripts?

### ISSUE THREAD

**Issue by HappyAlexRomania** [ShadowMario/FNF-PsychEngine#13087]
### Describe your problem here.

Can I import Variables from other scripts? If so, how can I do it? I wanted to make a dialogue script that takes the accuracy from the previous song and starts the "bad" dialogue if accuracy is bad, but start the "good" dialogue if the accuracy is good.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just added dialogues

**Comment by frantastic24** [comment]
Scripts are destroyed when the song ends, what you want are save files #8286
