### ISSUE TITLE
Can anyone tell me how to force an animation so it doesn't change?

### ISSUE THREAD

**Issue by Alberto20108** [ShadowMario/FNF-PsychEngine#13080]
### Describe your problem here.

I want to have a character play an animation that doesn't change until it finishes playing even if the character hits a note.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SrBagel** [comment]
Either use no animation notes or make the animation loop

**Comment by Alberto20108** [comment]
Is there a way to detect when an animation loops through code so i can change it back then?

**Comment by Draconic-Hybrid** [comment]
I think my method is a bit overly complicated, but it still works. 

```lua
function goodNoteHit(membersIndex, noteData, noteType, isSustainNote)
	if noteType == 'DoogHurtNote' then
		characterPlayAnim('boyfriend','dodge',true)
		setProperty('boyfriend.specialAnim', true)
		characterPlayAnim('dad','attack',true)
		setProperty('dad.specialAnim', true)
		disableCharaAnims()
	end
end

function noteMiss(membersIndex, noteData, noteType, isSustainNote)
	if noteType == 'DoogHurtNote' then
		playAnim('boyfriend','hurt',true)
		setProperty('boyfriend.specialAnim', true)
		characterPlayAnim('dad','attack',true)
		setProperty('dad.specialAnim', true)
		disableCharaAnims()
	end
end

function disableCharaAnims()
	for notesLength = 0,getProperty('notes.length')-1 do
            if getPropertyFromGroup('notes', notesLength, 'noteType') == '' then
			if not both and getPropertyFromGroup('notes', notesLength, 'mustPress') == true then
				setPropertyFromGroup('notes', notesLength, 'noAnimation', true)
				runTimer('reenableAnims',1)
			end
            end
        end
end

function onTimerCompleted(tag)
	if tag == 'reenableAnims' then
		for notesLength = 0,getProperty('notes.length')-1 do
			if getPropertyFromGroup('notes', notesLength, 'noteType') == '' then
				setPropertyFromGroup('notes', notesLength, 'noAnimation', false)
			end
		end
	end
end

```

**Comment by Alberto20108** [comment]
tysm it works :)

**Comment by TheKAPtain313** [comment]
> I think my method is a bit overly complicated, but it still works.
> 
> This is an excerpt from a custom note
> 
> ```lua
> function goodNoteHit(membersIndex, noteData, noteType, isSustainNote)
> 	if noteType == 'DoogHurtNote' then
> 		characterPlayAnim('boyfriend','dodge',true)
> 		setProperty('boyfriend.specialAnim', true)
> 		characterPlayAnim('dad','attack',true)
> 		setProperty('dad.specialAnim', true)
> 		disableCharaAnims()
> 	end
> end
> 
> function noteMiss(membersIndex, noteData, noteType, isSustainNote)
> 	if noteType == 'DoogHurtNote' then
> 		playAnim('boyfriend','hurt',true)
> 		setProperty('boyfriend.specialAnim', true)
> 		characterPlayAnim('dad','attack',true)
> 		setProperty('dad.specialAnim', true)
> 		disableCharaAnims()
> 	end
> end
> 
> function disableCharaAnims()
> 	for notesLength = 0,getProperty('notes.length')-1 do
>             if getPropertyFromGroup('notes', notesLength, 'noteType') == '' then
> 			if not both and getPropertyFromGroup('notes', notesLength, 'mustPress') == true then
> 				setPropertyFromGroup('notes', notesLength, 'noAnimation', true)
> 				runTimer('reenableAnims',1)
> 			end
>             end
>         end
> end
> 
> function onTimerCompleted(tag)
> 	if tag == 'reenableAnims' then
> 		for notesLength = 0,getProperty('notes.length')-1 do
> 			if getPropertyFromGroup('notes', notesLength, 'noteType') == '' then
> 				setPropertyFromGroup('notes', notesLength, 'noAnimation', false)
> 			end
> 		end
> 	end
> end
> ```

Can you put it in a .lua?

**Comment by Draconic-Hybrid** [comment]
Can't you copy and paste?
