### ISSUE TITLE
Game crashes when im adding an spritesheet and xml file made in Spritesheet and XML generator for FNF

### ISSUE THREAD

**Issue by GoshaCher360** [ShadowMario/FNF-PsychEngine#13089]
### Spritesheets and XML issue

![0-02-05-96781705b3b86b3bf5a187b3ec4036900fa18e084a6ad414ae0ccda74f6b2c6a_5f961fa8fb3f428b](https://github.com/ShadowMario/FNF-PsychEngine/assets/142249846/6285e7e7-c976-46f9-860b-fb46835b2719)

Its happened 08.14.2023. and I added new logo spritesheet and xml which made in application named "Spritesheet and XML generator for FNF" (Link if you are interested: https://gamebanana.com/tools/download/7136#FileInfo_831405)

Idk why its happened since its been normal since 2022 and now its crashed

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 217)
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 117)
C:\HaxeToolkit\haxe\std/Xml.hx (line 122)
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
states/TitleState.hx (line 219)
states/TitleState.hx (line 180)
flixel/util/FlxTimer.hx (line 205)
flixel/util/FlxTimer.hx (line 295)
flixel/FlxGame.hx (line 750)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: haxe.xml.XmlParserException: Expected node name at line 2 char 2
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't edited anything

**Comment by GoshaCher360** [comment]
Also Its happened on 0.7

**Comment by frantastic24** [comment]
Not a bug
Change encoding to UTF-8

**Comment by GoshaCher360** [comment]
> Not a bug Change encoding to UTF-8

ty
