### ISSUE TITLE
Healthbar Colours still dont work

### ISSUE THREAD

**Issue by PugglesomeBenji** [ShadowMario/FNF-PsychEngine#13086]
### Describe your bug here.

I don't know what happens but every time I set the icon health bar colours, its just white
![HBAR](https://github.com/ShadowMario/FNF-PsychEngine/assets/142172867/424e4079-6c16-4ded-89aa-08c6dc7ee175)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

**Comment by Jevilm** [comment]
u might of replaced the 0.7 health bar with the 0.6.3 and below health bar

**Comment by PugglesomeBenji** [comment]
Its been happening with every build with mods, even without replacing it

**Comment by MemeHovy** [comment]
> Its been happening with every build with mods, even without replacing it

lua has been changed a lot from 0.6.3 meaning old code might not work

**Comment by PugglesomeBenji** [comment]
I tried replacing the colours and saving the character but it still does not work

**Comment by PugglesomeBenji** [comment]
I have fixed it, I had a file in mods/images which replaced the health bar which might have bugged it. now i am gonna make a new issue :/
