### ISSUE TITLE
No Return Value in Hscript.hx (Help Needed)

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#13099]
### Describe your problem here.

source/psychlua/HScript.hx:228: characters 26-37 : psychlua.HScript has no field returnValue
source/psychlua/HScript.hx:229: characters 25-36 : psychlua.HScript has no field returnValue

I dont know how to fix it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

well, kinda removed a 3rd value in line 42 cause that was an error in hscript

**Comment by MemeHovy** [comment]
update SScript
