### ISSUE TITLE
I can't test my mod anymore!

### ISSUE THREAD

**Issue by Alltoupload** [ShadowMario/FNF-PsychEngine#13092]
### Describe your problem here.

I edited some code and I want to _test it._
I opened up **_PowerShell_** and used `lime test windows`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited the score text in `PlayState.hx`

**Comment by Alltoupload** [comment]
I have all the requirements, but whatever terminal I use, whatever I try, it says 
```
lime : The term 'lime' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ lime test windows
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (lime:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```

It really triggers me!

**Comment by mcagabe19** [comment]
> I have all the requirements, but whatever terminal I use, whatever I try, it **_STILL_** says
> 
> ```
> lime : The term 'lime' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
> the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + lime test windows
> + ~~~~
>     + CategoryInfo          : ObjectNotFound: (lime:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> ```
> 
> It really triggers me!

haxelib run lime setup -alias -y

**Comment by Alltoupload** [comment]
...
All I had to do was upgrade Haxe...

WHAT A GREAT LANGUAGE! >:(

**Comment by Alltoupload** [comment]
I have to upgrade EVERYTHING!?

WHAT A GREAT LANGUAGE! (v2)

**Comment by Alltoupload** [comment]
It says that there's a macro running. I don't know how to fix that

**Comment by mcagabe19** [comment]
add ``#if !macro`` in your import.hx like that (if doesn't have)
```haxe
#if !macro
//... (... as code things don't add that)
#end
```

**Comment by Alltoupload** [comment]
> add `#if !macro` in your import.hx like that (if doesn't have)
> 
> ```hx
> #if !macro
> //... (... as code things don't add that)
> #end
> ```

Where exactly?

**Comment by MemeHovy** [comment]
> > add `#if !macro` in your import.hx like that (if doesn't have)
> > ```hx
> > #if !macro
> > //... (... as code things don't add that)
> > #end
> > ```
> 
> Where exactly?

buddy, surround the imports with that

**Comment by Alltoupload** [comment]
Nevermind I actually did it right...

WHAT A GREAT ERROR SYSTEM!

**Comment by AllInGitHub** [comment]
> haxelib run lime setup -alias -y

I have a new laptop. I tried that, it shows me this
```
haxelib : The term 'haxelib' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ haxelib run lime setup -alias -y
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (haxelib:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
(Also, this is my **_alt_**, since I lost the password to my main)

**Comment by FuseIsHere813** [comment]
> > haxelib run lime setup -alias -y
> 
> I have a new laptop. I tried that, it shows me this
> 
> ```
> haxelib : The term 'haxelib' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
> spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + haxelib run lime setup -alias -y
> + ~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (haxelib:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> ```
>

did NOT have [haxe](https://haxe.org/download/version/4.2.5) installed. 💀
