### ISSUE TITLE
The source code is not working for me.

### ISSUE THREAD

**Issue by ItzKony** [ShadowMario/FNF-PsychEngine#13097]
### Describe your problem here.

When i type "lime test windows", nothing happen. :/

https://github.com/ShadowMario/FNF-PsychEngine/assets/126213565/9b7df7ef-8c0f-4a31-84f0-2f72ee7d02b4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
try lime build windows

**Comment by mcagabe19** [comment]
> > try lime build windows
> 
> it does nothing too

so odd try haxelib run lime test windows maybe?

**Comment by mcagabe19** [comment]
if this not works do haxelib run lime test windows -verbose

**Comment by ItzKony** [comment]
it does this
![image_2023-08-16_131202482](https://github.com/ShadowMario/FNF-PsychEngine/assets/126213565/f57d46d9-80c9-4ca7-9357-f1734556188c)

**Comment by mcagabe19** [comment]
try reinstalling lime idk (not from git)

**Comment by ItzKony** [comment]
> try reinstalling lime idk (not from git)

how?

**Comment by ItzKony** [comment]
> try reinstalling lime idk (not from git)

i reinstall it, but when i do "lime test windows", it always do nothing :/

**Comment by mcagabe19** [comment]
> > try reinstalling lime idk (not from git)
> 
> i reinstall it, but when i do "lime test windows", it always do nothing :/

well I'm out of ideas

**Comment by ItzKony** [comment]
> > > try reinstalling lime idk (not from git)
> > 
> > 
> > i reinstall it, but when i do "lime test windows", it always do nothing :/
> 
> well I'm out of ideas

:/

**Comment by ItzKony** [comment]
> > > try reinstalling lime idk (not from git)
> > 
> > 
> > i reinstall it, but when i do "lime test windows", it always do nothing :/
> 
> well I'm out of ideas

:/

**Comment by ItzKony** [comment]
> make sure you have the hxcpp compiler installed, as it is necessary for compiling windows builds

how do i see that?

**Comment by mcagabe19** [comment]
> > make sure you have the hxcpp compiler installed, as it is necessary for compiling windows builds
> 
> how do i see that?

haxelib list

**Comment by MemeHovy** [comment]
do you have visual studio installed?

**Comment by ItzKony** [comment]
> do you have visual studio installed?

yes

**Comment by ItzKony** [comment]
sooooo... i cant code psych engine?

**Comment by MemeHovy** [comment]
> sooooo... i cant code psych engine?

no it's just I was thinking of what I could do to help but nothing came to light

**Comment by MemeHovy** [comment]
also, check for duplicate issues, and see if someone has a solution, instead of opening duplicates

**Comment by ItzKony** [comment]
i'll search for
