### ISSUE TITLE
Noteskin Crashes Game

### ISSUE THREAD

**Issue by SpriteTheGamerhog** [ShadowMario/FNF-PsychEngine#13096]
### Describe your bug here.

I tried to install a note skin but whenever i reopened the game it gave me this error
objects/Note.hx (line 296)
objects/Note.hx (line 224)
states/PlayState.hx (line 1277)
states/PlayState.hx (line 501)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

<img width="1339" alt="Screenshot 2023-08-15 at 2 53 35 PM" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/127702864/6d976943-b281-4ec6-8fcf-823771515897">

### Command Prompt/Terminal logs (if existing)

```bash
objects/Note.hx (line 296)
objects/Note.hx (line 224)
states/PlayState.hx (line 1277)
states/PlayState.hx (line 501)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, Installed a noteskin mod

**Comment by ChumbleDev** [comment]
did you find any fix?

**Comment by SpriteTheGamerhog** [comment]
no, not for mac
