### ISSUE TITLE
Stage Lua Confusion

### ISSUE THREAD

**Issue by SeriouslyAnimations** [ShadowMario/FNF-PsychEngine#1309]
### What is your question?

Can someone make the lua stage files for all of the stages please. Its hard for me and dunno how to base all of them off the stage code

**Comment by DEV-idiotXD** [comment]
#1048 
duplicate
@ShadowMario this is a duplicate and invalid

btw just go into the code for the stages in thesc then just put the same coords for the same items so ye thts it

**Comment by SeriouslyAnimations** [comment]
thanks

**Comment by SeriouslyAnimations** [comment]
@DEV-idiotXD wait where

**Comment by SeriouslyAnimations** [comment]
if you dont mind me asking, where can i find that?

**Comment by CrusherMods** [comment]
> if you dont mind me asking, where can i find that?

PlayState.hx if Source Code
Wiki Lua example for lua

**Comment by SeriouslyAnimations** [comment]
thanks
