### ISSUE TITLE
Help me with this bug

### ISSUE THREAD

**Issue by PhasmF** [ShadowMario/FNF-PsychEngine#13093]
### Describe your bug here.

so... I keep getting an error saying like hxCodec isnt installed even tho its already installed with the haxelib run hmm install. Its just, it doesnt allow me to compile, help me out pls :(

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\SEAD\Downloads\FNF-PsychEngine-main\FNF-PsychEngine-main>haxelib run lime build windows
Error: Could not find haxelib "hxCodec", does it need to be installed?
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
remove all ur haxelibs and try that
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions
