### ISSUE TITLE
Disabling RGB on custom note splashes not meant for RGB on source.

### ISSUE THREAD

**Issue by JustCode-debug** [ShadowMario/FNF-PsychEngine#13102]
### Describe your problem here.

I'm having trouble with the rgb feature with note splashes in source.
I can disable the rgb feature on custom notes using rgbShader.enabled = false;.
But I just cannot figure out how to disable it for note splashes on source.
So if anyone can please tell me how to disable the rgb feature on note splashes in source, that would be very nice.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not Anything Major.

**Comment by VoidedBattery** [comment]
it'd also be nice to know how i can disable the shader on note splashes on LUA as well, because when I apply it to a note it still applies the shader anyway

**Comment by shikecool64amongus69** [comment]
that impossible even if you did disable it all the offsets would be wrong for the splashes
i hope shadow mario can fix this.
