### ISSUE TITLE
HELP ME FIX THIS ERROR PLS

### ISSUE THREAD

**Issue by cotne1233** [ShadowMario/FNF-PsychEngine#13101]
### Describe your problem here.

source/Alphabet.hx:200: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:143: characters 13-21 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/Main.hx:78: characters 61-65 : Float should be Int
source/Main.hx:78: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:78: characters 61-65 : ... For function argument 'child'
source/FreeplayState.hx:242: characters 28-36 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:27: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:1370: characters 18-26 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:1404: characters 18-26 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:64: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:339: characters 19-27 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:341: characters 19-27 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:1275: characters 16-24 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:39: characters 13-21 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:109: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:111: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/TitleState.hx:653: characters 15-23 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by mcagabe19** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by mcagabe19** [comment]
> > https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions
> 
> how do i change those versions, can you give me an example?

non-git: ``haxelib install (library) (ver)``
git: ``haxelib git (library) (link)``

**Comment by cotne1233** [comment]
source/Main.hx:78: characters 61-65 : Float should be Int
source/Main.hx:78: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:78: characters 61-65 : ... For function argument 'child'
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/text/FlxTypeText.hx:8: characters 8-29 : Type not found : flixel.sound.FlxSound
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/text/FlxTypeText.hx:78: characters 26-34 : Type not found : FlxSound
source/Achievements.hx:30: lines 30-216 : ... Defined in this class
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/PlayState.hx:1348: characters 9-17 : Type not found : FlxVideo
source/DialogueBox.hx:145: characters 16-22 : flixel.addons.text.FlxTypeText has no field sounds
source/DialogueBox.hx:250: characters 16-25 : flixel.addons.text.FlxTypeText has no field resetText
source/DialogueBox.hx:251: characters 16-21 : flixel.addons.text.FlxTypeText has no field start
source/DialogueBox.hx:252: characters 16-32 : flixel.addons.text.FlxTypeText has no field completeCallback
source/DialogueBox.hx:229: characters 18-22 : flixel.addons.text.FlxTypeText has no field skip
source/MusicBeatState.hx:43: characters 3-11 : Type not found : FlxVideo
source/MusicBeatState.hx:49: characters 3-11 : Type not found : FlxVideo
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/transition/FlxTransitionableState.hx:81: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field

**Comment by cotne1233** [comment]
> > > https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions
> > 
> > 
> > how do i change those versions, can you give me an example?
> 
> non-git: `haxelib install (library) (ver)` git: `haxelib git (library) (link)`

it keeps getting me this error

**Comment by devin503** [comment]
Try running these in a terminal:
```
haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git
haxelib install flixel-addons 3.0.2
haxelib install flixel-tools 1.5.1
haxelib install flixel-ui 2.5.0
haxelib install flixel 5.2.2
haxelib install sscript 4.0.1
haxelib install tjson 1.4.0
haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git
haxelib install openfl 9.2.1
haxelib install lime 8.0.1
```
(Terminal as in cmd)
