### ISSUE TITLE
WHY!?

### ISSUE THREAD

**Issue by Alltoupload** [ShadowMario/FNF-PsychEngine#13105]
### Describe your bug here.

Every song I open freezes the frame and shows a black screen!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited the score text in `PlayState.hx`

**Comment by Alltoupload** [comment]
ok nvm go to chart editor and back
At least I know it works!

**Comment by Alltoupload** [comment]
> can you be more specific?

On what?

**Comment by MemeHovy** [comment]
> > can you be more specific?
> 
> On what?


the issue
