### ISSUE TITLE
WaitForSingleObjectEx error: 0x102 on Crostini using Wine

### ISSUE THREAD

**Issue by octoreef** [ShadowMario/FNF-PsychEngine#1310]
### Describe your bug here.

So I have a Lenovo Chromebook C340-11 and wanted to try making a custom FNF chart, although I'm on Chrome OS, so that isn't easy. I had to install Wine on the Linux VM for Chrome OS (aka Crostini), download and unzip Psych Engine for Windows, and run it with Wine, and it worked for a while, then all of a sudden the terminal wouldn't stop returning what seems to be a library error and no matter what I did, it wouldn't go away. I tried to close the game and open back up, nothing. I deleted the game files (including Application Files), nothing. I'm close to deleting my Wine directory and making a new one, but I decided to get help here first. What's going on?

### Command Prompt/Terminal logs (if existing)

It returns
```bash
AL lib: (EE) ALCwaspiPlayback_mixerProc: WaitForSingleObjectEx error: 0x102
```
every second.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

First time I got the error I had change the Inst.ogg and tutorial.json files for the Tutorial. Second time, with a clean build, no.

**Comment by ShadowMario** [comment]
1. Chromebooks suck absolute BALLS.
2. Wine is a converter iirc, so it's expected that some things might break, it's not a native port, so it isn't actively supported.
