### ISSUE TITLE
can't compile 0.6.3 (No i don't want 0.7.1h)

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#13106]
### Describe your bug here.

yeah so uhm, I'm trying to compile 6.3 but i get this amount of errors
<img width="947" alt="image" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/102251392/3f60b439-ae60-4c04-9624-245b59fa4ae5">

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by mcagabe19** [comment]
then you can cry about it

**Comment by MemeHovy** [comment]
yea cry about it

**Comment by NightmaresPlayz** [comment]
ill help for one part, ummm, just go to source/flixel, then make a folder called sound, then put all code in system to sounds folder

**Comment by Hazardows** [comment]
![Captura de pantalla 2023-08-20 141203](https://github.com/ShadowMario/FNF-PsychEngine/assets/103978241/82dd1be5-4cd1-4b3a-9e2e-f38e1f7695e3)
install this libraries with the sepecific version on the picture
(if this dosen't work then idk)
