### ISSUE TITLE
This is an unexpected error, please someone help me fix it

### ISSUE THREAD

**Issue by cotne1233** [ShadowMario/FNF-PsychEngine#13119]
### Describe your problem here.

C:/HaxeToolkit/haxe/lib/hxCodec/git/project/Build.xml can someone help me fix this error

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by KELOTOMU** [comment]
are u using 0.6.3, if so set hxCodec to 2.6.1 and not git, if u use the latest version then just stay with git. Set it inside C:\users\$userName
