### ISSUE TITLE
Opponent Noteskin breaking when using a custom noteskin

### ISSUE THREAD

**Issue by VirtMTTR** [ShadowMario/FNF-PsychEngine#13114]
### Describe your problem here.

So I'm moving stuff into 0.7.1h and I'm still trying to understand how the note system works.
I've put the noteskin in the correct folder in the mod and it loads fine. The only issue is that the opponent's noteskin which I'm currently using a Lua script for (also pictured below) seems to break the script. Removing my new noteskin and using the default one on the engine fixes this issue but that means the player strums don't use the correct skin. Is there anything I'm missing to fix this opponent skin glitch?

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/115607391/3986eb7e-5d24-4d56-9db9-4e2331f7ef88)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/115607391/d78ad8a3-0514-481f-bc7c-3e5010ae75f7)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by AyMarte** [comment]
The noteskin prob doesn't have the xml properties as the `NOTE_ASSETS.xml`

**Comment by AyMarte** [comment]
And that the textures are messed up because of the image layout, try doing it on the `NOTE_ASSETS.png` first to see if each texture aligns with it.

**Comment by VirtMTTR** [comment]
The textures are identical, the opponent's is just color inverted but otherwise are the same.
I'm not currently at my PC but now that made me think it's because I'm using a texture and xml made in the old traditional layout to override the existing `NOTE_Assets.png` and `NOTE_Assets.xml` layout if that's what you mean?

If so, maybe just making the player one a new skin altogether that uses the old xml layout will fix the issue? If that makes any sense. I'll give an update when I try it on if that fixes the issue.

**Comment by VirtMTTR** [comment]
It turns out the xmls were different somehow? That's my bad for not seeing that though I swear they were the same since they use the same spritesheet as a base. Oh well, at least I've figured it out!
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/115607391/0dd4e114-52ea-4312-9eeb-21e0f427bd34)
