### ISSUE TITLE
Where are Hurt Notes

### ISSUE THREAD

**Issue by GatoMagoXD** [ShadowMario/FNF-PsychEngine#13111]
### What is your question?

I trying to the hurt notes skins for the other notes but i cant find it.
in what folder is the others hurts notes

**Comment by NekoIchiSan** [comment]
I believe the hurt notes are no longer a sprite within the assets but are coded within the note.hx with its color on the regular note skin assets (just like how the note colors are set up in 0.7+)
![notehxscreenshot](https://github.com/ShadowMario/FNF-PsychEngine/assets/93456379/ca1b827d-686f-4976-a937-a97d9dc336fe)

**Comment by GatoMagoXD** [comment]
i can put a assets for a hurt note for some form?

**Comment by NekoIchiSan** [comment]
oh I see, are you using mod support or source?

**Comment by GatoMagoXD** [comment]
i can use the source so im working in the dowloable version on psych engine
