### ISSUE TITLE
0.6.3 compiling error

### ISSUE THREAD

**Issue by sonicfan73112** [ShadowMario/FNF-PsychEngine#13118]
### Describe your bug here.

i get this bug every time i try and compile 0.6.3

source/MainMenuState.hx:121: characters 13-14 : flixel.FlxSprite has no field X
source/FunkinLua.hx:2565: characters 29-33 : Class<Paths> has no field mods
source/FunkinLua.hx:2901: characters 45-49 : Class<Paths> has no field mods
source/FunkinLua.hx:2903: characters 35-39 : Class<Paths> has no field mods
source/FunkinLua.hx:2905: characters 20-33 : Class<Paths> has no field getGlobalMods
source/FunkinLua.hx:2905: characters 14-35 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/FunkinLua.hx:2906: characters 35-39 : Class<Paths> has no field mods
source/PlayState.hx:1427: characters 45-49 : Class<Paths> has no field mods
source/PlayState.hx:1429: characters 35-39 : Class<Paths> has no field mods
source/PlayState.hx:1431: characters 20-33 : Class<Paths> has no field getGlobalMods
source/PlayState.hx:1431: characters 14-35 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/PlayState.hx:1432: characters 35-39 : Class<Paths> has no field mods
source/TitleState.hx:95: characters 9-23 : Class<Paths> has no field pushGlobalMods

### Command Prompt/Terminal logs (if existing)

```bash
source/MainMenuState.hx:121: characters 13-14 : flixel.FlxSprite has no field X
source/FunkinLua.hx:2565: characters 29-33 : Class<Paths> has no field mods
source/FunkinLua.hx:2901: characters 45-49 : Class<Paths> has no field mods
source/FunkinLua.hx:2903: characters 35-39 : Class<Paths> has no field mods
source/FunkinLua.hx:2905: characters 20-33 : Class<Paths> has no field getGlobalMods
source/FunkinLua.hx:2905: characters 14-35 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/FunkinLua.hx:2906: characters 35-39 : Class<Paths> has no field mods
source/PlayState.hx:1427: characters 45-49 : Class<Paths> has no field mods
source/PlayState.hx:1429: characters 35-39 : Class<Paths> has no field mods
source/PlayState.hx:1431: characters 20-33 : Class<Paths> has no field getGlobalMods
source/PlayState.hx:1431: characters 14-35 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/PlayState.hx:1432: characters 35-39 : Class<Paths> has no field mods
source/TitleState.hx:95: characters 9-23 : Class<Paths> has no field pushGlobalMods
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i edited the project.xml to disable mods

**Comment by MemeHovy** [comment]
use 0.7.1h then

**Comment by sonicfan73112** [comment]
> use 0.7.1h then

dont work

**Comment by sonicfan73112** [comment]
> use 0.7.1h then

also i dont like 0.7

**Comment by MemeHovy** [comment]
> > use 0.7.1h then
> 
> also i dont like 0.7

then cry about it

**Comment by sonicfan73112** [comment]
nvm fixed it

**Comment by sonicfan73112** [comment]
i cant disable the mods folder

**Comment by WilliamGaming12** [comment]
> nvm fixed it

how, i've been having the same errors
