### ISSUE TITLE
broken notes

### ISSUE THREAD

**Issue by LemoLev** [ShadowMario/FNF-PsychEngine#13124]
### Describe your bug here.

i had a song at 128 bpm, but i was charting at 150, but when i changed the bpm to 128, the notes became "ghost", they were up the sections, in the sections didnt even made a sound (with arrow ticks on), but in the game itself it was normal, also 127 was just normal. Is there something that i dont know about 128?
![note issue](https://github.com/ShadowMario/FNF-PsychEngine/assets/93066298/ea799580-2b1b-4ad6-b4d0-932dbecc57fa)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MemeHovy** [comment]
it’s a very old bug that has been around since the FNF chart editor was released

**Comment by NightmaresPlayz** [comment]
yeah, you gotta restart the whole entire chart i guess, change chart bpm after it has been completed, its impossible to make it work like how you want it to

**Comment by LemoLev** [comment]
its sad...
