### ISSUE TITLE
Adding custom characters in 0.7.1h

### ISSUE THREAD

**Issue by weeToL** [ShadowMario/FNF-PsychEngine#13120]
### Describe your problem here.

I was doing stuff, i tried to add custom characters, and it stuck on daddy's sprites. Source code overhauled in 0.7.1h, so i need a new tutorial, thanks.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by VoidedBattery** [comment]
i think the overhaul won't change much for the sprites, it works just fine on my end. just remember to use the right sprites on the character editor, and to use the right character on the chart editor

**Comment by weeToL** [comment]
Yeah, i was dumb, and the name in xml didn't match with the actual name.
