### ISSUE TITLE
How can I add a loading screen to Psych Engine?

### ISSUE THREAD

**Issue by Fellegend** [ShadowMario/FNF-PsychEngine#13128]
### What is your question?

I want to add a loading screen to my mod. How can I do it?

I'm using source code win 64 bits

Version: 0.7.1

**Comment by TheKAPtain313** [comment]
Go to https://gamebanana.com/tools/12004 and remake it

**Comment by Chidubemmo** [comment]
Remove all the no_preload stuff in loadingstate.he (source)

**Comment by Fellegend** [comment]
> Remove all the no_preload stuff in loadingstate.he (source)

LoadingState.hx ?

**Comment by Fellegend** [comment]
> Remove all the no_preload stuff in loadingstate.he (source)

source\states\LoadingState.hx:170:characters 3-7 : expected

**Comment by Fellegend** [comment]
> Go to https://gamebanana.com/tools/12004 and remake it

There is no scripts folder in mods/

**Comment by mcagabe19** [comment]
> > Go to https://gamebanana.com/tools/12004 and remake it
> 
> There is no scripts folder in mods/

then create it?

**Comment by Chidubemmo** [comment]
> > Remove all the no_preload stuff in loadingstate.he (source)
> 
> #IF NO_PREALOAD ?

Yes

**Comment by Fellegend** [comment]
> > > Go to https://gamebanana.com/tools/12004 and remake it
> > 
> > 
> > There is no scripts folder in mods/
> 
> then create it?

didn't work

**Comment by Fellegend** [comment]
nvm it's done
