### ISSUE TITLE
flixel.system.FlxSound has no field pitch 0.6.3 compiling help

### ISSUE THREAD

**Issue by NightmaresPlayz** [ShadowMario/FNF-PsychEngine#13125]
### Describe your problem here.

source/PlayState.hx:2859: characters 20-25 : flixel.system.FlxSound has no field pitch
source/PlayState.hx:2864: characters 11-16 : flixel.system.FlxSound has no field pitch
source/PlayState.hx:1486: characters 30-35 : flixel.system.FlxSound has no field pitch
source/PlayState.hx:1487: characters 21-26 : flixel.system.FlxSound has no field pitch
source/PlayState.hx:2334: characters 20-25 : flixel.system.FlxSound has no field pitch
source/PlayState.hx:2340: characters 11-16 : flixel.system.FlxSound has no field pitch
source/Character.hx:301: characters 101-106 : flixel.system.FlxSound has no field pitch
source/PlayState.hx:2433: characters 10-15 : flixel.system.FlxSound has no field pitch
source/PlayState.hx:2368: characters 20-25 : flixel.system.FlxSound has no field pitch
source/PlayState.hx:4479: characters 125-130 : flixel.system.FlxSound has no field pitch
source/PlayState.hx:3172: characters 126-131 : flixel.system.FlxSound has no field pitch
source/PlayState.hx:4985: characters 20-25 : flixel.system.FlxSound has no field pitch
source/editors/ChartingState.hx:1994: characters 20-25 : flixel.system.FlxSound has no field pitch
source/editors/ChartingState.hx:1995: characters 10-15 : flixel.system.FlxSound has no field pitch

How do i fix this

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Well, i edited the source/playstate.hx and it fixed an error, it was adding an extra value

**Comment by MemeHovy** [comment]
0.7 has fixed this issue

**Comment by mcagabe19** [comment]
0.6.3 not supporting anymore go to 0.7

**Comment by NightmaresPlayz** [comment]
well, i fixed it somehow in 0.6.3
