### ISSUE TITLE
Disabling Note Splash RGB in general.

### ISSUE THREAD

**Issue by JustCode-debug** [ShadowMario/FNF-PsychEngine#13127]
### Describe your problem here.

I want to know how to make certain note splashes not use the RGB Shader used in the engine.
Like if a note splash is not meant for RGB like the example below, then I want to disable it at all times.
If anyone can tell me how I can do this in source, I thank you.
(P.S. It's supposed to be a note splash that's unselectable in the visual and ui settings. And the version is v0.7.1h.)
![HURTnoteSplashes](https://github.com/ShadowMario/FNF-PsychEngine/assets/135799868/07ad7c87-28df-4f8e-890d-f851b9aa31f9)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not Anything Major.

**Comment by TheKAPtain313** [comment]
ok
![WIN_20220225_18_32_26_Pro](https://github.com/ShadowMario/FNF-PsychEngine/assets/140554874/42fc9d5a-9ea4-4704-a149-3acc6aba0942)
