### ISSUE TITLE
Pibby Apocalypse mod crash

### ISSUE THREAD

**Issue by ERed0** [ShadowMario/FNF-PsychEngine#13135]
### Describe your bug here.

En la última canción del freeplay de este mod, me aparece un error justo en el momento en el que se supone que llega a la segunda fase. He logrado sincronizarlo con Onedrive creyendo que ese era el problema, también lo he desbloqueado y no funciona. He llegado a la conclusión de que necesita que le de permisos especiales pero no me permite activarlos. Si alguien sabe el problema, que me diga cómo solucionarlo, por favor.

Este es el mod: https://gamebanana.com/wips/73842

### Command Prompt/Terminal logs (if existing)

```bash
hscript/Interp.hx (line 263)
hscript/Interp.hx (line 457)
StageConstructor.hx (line 114)
PlayState.hx (line 4546)
MusicBeatState.hx (line 58)
PlayState.hx (line 2517)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: assets/stages/treehouse/stage.hxs:5070: Invalid access to field alpha
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
That's a problem with the mod, not with the engine

**Comment by Urtyc** [comment]
I have the same problem, how do I solve it?

**Comment by riquelme2351** [comment]
I have the same problem how do I solve the error

**Comment by ADA-Funni** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/99497910/e306a240-1ef0-476b-a5af-b4c1d0b63905)
this bug happens because you played on low quality

**Comment by DFMDMFMG** [comment]
do you need a gaming pc?
