### ISSUE TITLE
Secret Song

### ISSUE THREAD

**Issue by AxelMal71** [ShadowMario/FNF-PsychEngine#13134]
### What is your question?

Hello, I'm making a mod and one of the songs, I want to be able to press a sequence of keys to get to a song from Freeplay.
How would I be able to achieve this?

**Comment by MemeHovy** [comment]
I'll let you figure this one out, you gotta learn somehow

**Comment by AxelMal71** [comment]
> I'll let you figure this one out, you gotta learn somehow

what

**Comment by AxelMal71** [comment]
i don't know lua, or haxeflixel
how am i supposed to figure this out

**Comment by MemeHovy** [comment]
> i don't know lua, or haxeflixel how am i supposed to figure this out

https://haxeflixel.com/documentation/
https://haxe.org/documentation/introduction/
https://www.lua.org/docs.html

**Comment by AxelMal71** [comment]
...

**Comment by AxelMal71** [comment]
i just need a simple script or something, can someone help please?
i'm not learning two entire languages just for a component of a mod.

**Comment by mcagabe19** [comment]
> > i just need a simple script or something, can someone help please? i'm not learning two entire languages just for a component of a mod.
> 
> go learn fucking haxe and lua ugh I hate these people

**Comment by MemeHovy** [comment]
> > i just need a simple script or something, can someone help please? i'm not learning two entire languages just for a component of a mod.
> 
> go learn fucking haxe and lua ugh I hate these people

ikr, even with the bare minimum, that should be good enough

**Comment by TheKAPtain313** [comment]
yall are so mean

**Comment by AxelMal71** [comment]
fr
