### ISSUE TITLE
Game won't build, not even showing a single error message

### ISSUE THREAD

**Issue by Zoe096423** [ShadowMario/FNF-PsychEngine#13136]
### Describe your problem here.
![Inked問題1](https://github.com/ShadowMario/FNF-PsychEngine/assets/87363436/d3de2f2e-4943-4782-a7a2-2753b7437480)
![Inked問題2](https://github.com/ShadowMario/FNF-PsychEngine/assets/87363436/2787a968-75f5-4414-86b2-3d2c4636617c)

So basically I finished following the steps in guide, installed hmm and setup file, and I'm trying to start the game.
For some reason it just doesn't start. There isn't any error bubbles popping out, not even a single line of error message.
The only file that generated from the "lime build windows" code is a nameless .build file and can't be opened.
Please help, I've been stuck with this issue for months and I'm so confused...

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ItzKony** [comment]
I have the same problem :/
