### ISSUE TITLE
Custom notes look like normal then turns to normal notes

### ISSUE THREAD

**Issue by toonlonk** [ShadowMario/FNF-PsychEngine#13132]
### Describe your bug here.

its the title

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Noobz4Life** [comment]
you most likely have an error in your lua script after setting the notes texture

try putting 'luaDebugMode = true' in your Create callback, it'll probably tell you what the error is
