### ISSUE TITLE
Custom Hurt Notes

### ISSUE THREAD

**Issue by DevSpookyDog** [ShadowMario/FNF-PsychEngine#13138]
### What is your question?

I'm wondering how to add custom note types to psych engine 0.7.1h I don't understand at all how to do it, so can someone help me?

**Comment by RodneyAnImaginativePerson** [comment]
Have you done it in 0.6.3 or lower? If so you already know how.

**Comment by DevSpookyDog** [comment]
Well I know how to code kinda but I don't know where I put it

**Comment by DevSpookyDog** [comment]
thanks! it worked!
