### ISSUE TITLE
Video Below HUD

### ISSUE THREAD

**Issue by AxelMal71** [ShadowMario/FNF-PsychEngine#13133]
### What is your question?

Hello, I know you can make videos appear in-game over the HUD, but it makes the game unplayable unless you've already memorized the notes. How do you play a video in-game while being able to see the notes and HUD at the same time?
(also, yes, I know [this](https://gamebanana.com/mods/426880) exists, it doesn't work in 0.7.1h as of now)

**Comment by ZeroZen0410** [comment]
so what was the solution?
