### ISSUE TITLE
I want to fix it

### ISSUE THREAD

**Issue by simp-comet** [ShadowMario/FNF-PsychEngine#13148]
### Describe your problem here.

<img width="411" alt="screenshot but upload for github" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/107211610/e4510c51-2c6f-41d5-82b8-3befcf655f5b">
I can always play any song the first time, but it always crashes when I try to play the second time.
Is there any way to fix this?
(I am not good at English so I use a translator)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by devin503** [comment]
Unless you have modified your Windows installation in some way to change the UI, it appears that you're building for either Linux or macOS. Have you tried building for the platform your system runs on, if not Windows?

macOS command: `lime build/test mac`
Linux command: `lime build/test linux`

**Comment by simp-comet** [comment]
> 

I was running a build for Windows released on this site on my Mac using wineskin.
Thanks for the advice!

**Comment by simp-comet** [comment]
(This problem was solved by turning off the mod that was causing the bug:))
