### ISSUE TITLE
PsychEngine version 0.7.1h crashes

### ISSUE THREAD

**Issue by MultiverseBF** [ShadowMario/FNF-PsychEngine#13140]
### Describe your problem here.

Not sure if It's only me but as I download the newest version of psychengine, every time I try to run a song the game either crash without loading the song or it crashes three seconds after the song start.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by mcagabe19** [comment]
try run psych in cmd and go song again and send cmd logs here

**Comment by MultiverseBF** [comment]
> try run psych in cmd and go song again and send cmd logs here

I tried but when I run it on cmd it says [lime.utils-Preloader] ERROR: There is no asset library with an ID of "videos"

**Comment by MemeHovy** [comment]
> > try run psych in cmd and go song again and send cmd logs here
> 
> I tried but when I run it on cmd it says [lime.utils.Preloader] ERROR: There is no asset library with an ID of "videos"

make sure you created the videos folder, and it's in Project.xml

**Comment by MultiverseBF** [comment]
> > > try run psych in cmd and go song again and send cmd logs here
> > 
> > 
> > I tried but when I run it on cmd it says [lime.utils.Preloader] ERROR: There is no asset library with an ID of "videos"
> 
> make sure you created the videos folder, and it's in Project.xml

The video folder already exist but It's in the modTemplate folder which wasn't even in the old version's of psychengine, still, how can I know/be sure It's in Project.xml?

**Comment by MemeHovy** [comment]
you look in there

**Comment by MultiverseBF** [comment]
> you look in there

well, I tried search everywhere but I can't find it, you maybe know where to search in the files?

**Comment by MemeHovy** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/blob/main/Project.xml

**Comment by MultiverseBF** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/blob/main/Project.xml

I prob need to create a note and add all of that in it right?

**Comment by MemeHovy** [comment]
> > https://github.com/ShadowMario/FNF-PsychEngine/blob/main/Project.xml
> 
> I prob need to create a note and add all of that in it right?

you're not using source code, so I all I can say is redownload psych

**Comment by MultiverseBF** [comment]
> > > https://github.com/ShadowMario/FNF-PsychEngine/blob/main/Project.xml
> > 
> > 
> > I prob need to create a note and add all of that in it right?
> 
> you're not using source code, so I all I can say is redownload psych

I know there's also a source code but yes, I'm using the downloadable version and I tried but it happen the same thing

**Comment by TheKAPtain313** [comment]
I have the same prob
