### ISSUE TITLE
How to shake the icon

### ISSUE THREAD

**Issue by IRIHAYA-MAIN** [ShadowMario/FNF-PsychEngine#13146]
### Describe your problem here.

I want to shake the icon when the opponent is pinch icon, but I don't know how to do it. If anyone knows how to do this, please let me know.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
from ourple guy sc
```lua
function onUpdatePost()
	local angleOfs = math.random(-5, 5)
	local posXOfs = math.random(-8, 8)
	local posYOfs = math.random(-4, 4)
	if getProperty('healthBar.percent') > 80 then
		setProperty('iconP2.angle', angleOfs)
		setProperty('iconP2.x', getProperty('iconP2.x') + posXOfs)
		setProperty('iconP2.y', defaultY + posYOfs)
	else
		setProperty('iconP2.angle', 0)
	end
end
```

**Comment by IRIHAYA-MAIN** [comment]
> 私たちの男SCから
> 
> ```lua
> function onUpdatePost()
> 	local angleOfs = math.random(-5, 5)
> 	local posXOfs = math.random(-8, 8)
> 	local posYOfs = math.random(-4, 4)
> 	if getProperty('healthBar.percent') > 80 then
> 		setProperty('iconP2.angle', angleOfs)
> 		setProperty('iconP2.x', getProperty('iconP2.x') + posXOfs)
> 		setProperty('iconP2.y', defaultY + posYOfs)
> 	else
> 		setProperty('iconP2.angle', 0)
> 	end
> end
> ```

Thanks
