### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by Alltoupload** [ShadowMario/FNF-PsychEngine#13159]
### What is your question?

`C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)`

I see this every time I run `lime test windows`

It's very annoying!

**Comment by devin503** [comment]
This is the repository for FNF Psych Engine. There's an [official flixel-ui repository](https://github.com/HaxeFlixel/flixel-ui) for flixel-ui where people may be better able to help you.
