### ISSUE TITLE
hmm.json fix

### ISSUE THREAD

**Issue by KELOTOMU** [ShadowMario/FNF-PsychEngine#13158]
### What feature do you want to get added on the **base** engine?

Really useful feature so compiling will be ALOT easier for the game. I already made the fixes for it.
> also for lazy ppl like me

> For psych 0.7.1h not sure if this works for 0.7.1 and 0.7

https://www.mediafire.com/file/2vgokaoa6k2vbyh/hmm.json/file

> For psych 0.6.3 and maybe below

https://www.mediafire.com/file/2tfky52ulnok1vx/hmm%25282%2529.json/file

If you ever see an error like this in psych 0.6.3 source code:
`Error: Could not find include file "D:/HaxeToolkit/haxe/lib/hxCodec/git/hxcodec/vlc/LibVLCBuild.xml"`
just cd out of the psych engine source code and set hxCodec to 2.6.1
`C:\>haxelib set hxCodec 2.6.1`

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by FrostyTheGlitch34** [comment]
Where do I put the "hmm.json" file?

**Comment by KELOTOMU** [comment]
> Where do I put the "hmm.json" file?

just inside the source code folder beside the other folders like assets, source, etc.

**Comment by ShadowMario** [comment]
This sounds like it would work better as a Pull Request instead of an Issue
