### ISSUE TITLE
How do i execute the game?

### ISSUE THREAD

**Issue by SalchipapaXD** [ShadowMario/FNF-PsychEngine#13155]
### What is your question?

Happens that i already have installed and compiled psych engine 7.1. The problem is that i have searched and i don't find any executable of the engine.
![imagen_2023-08-21_211258945](https://github.com/ShadowMario/FNF-PsychEngine/assets/106918333/0efdb15c-5c30-4f01-8402-f4869559c400)

**Comment by MemeHovy** [comment]
it's in the export folder

**Comment by SalchipapaXD** [comment]
> it's in the export folder

there is onky the debug folder and then the .debug script

**Comment by MemeHovy** [comment]
> > it's in the export folder
> 
> there is only the debug folder and then the .debug script

it’s inside the bin folder
