### ISSUE TITLE
Custom Notes not appearing on the Right Side 0.6.2

### ISSUE THREAD

**Issue by AyMarte** [ShadowMario/FNF-PsychEngine#13152]
## _This issue is in 0.6.2._

When I was making a custom note in a mod, no matter which side the note was placed in the chart, in-game, it is always on the opponent's side. Does anyone know why this happens? 

> I'll leave you with the 3 Lua scripts below for the notes.

### _The Note That Was Causing The Issue..._ Faker

`function onCreate()
	for i = 0, getProperty('unspawnNotes.length')-1 do
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Faker' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'HURTNOTE_assets')
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
				setPropertyFromGroup('unspawnNotes', i, 'mustPress', false)
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', false);
				setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true);
			end
		end
	end
end

function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'Faker' then
		if noteData == 0 then
			--Gonna Put Code Here Soon...
		elseif noteData == 1 then
			--Gonna Put Code Here Soon...
		elseif noteData == 2 then
			--Gonna Put Code Here Soon...
		elseif noteData == 3 then
			--Gonna Put Code Here Soon...
		end
	end
end`

### Bullet
`function onCreate()
	for i = 0, getProperty('unspawnNotes.length')-1 do
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Bullet' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'noteskins/bulletNote')
			setPropertyFromGroup('unspawnNotes', i, 'missHealth', 0.6)
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', false);
				setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true);
			end
		end
	end
end

function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'Bullet' and isSustainNote == false then
		playSound('gunshot')
		if noteData == 0 then
			playAnim('boyfriend', 'dodgeLeft', true, false, 0)
		elseif noteData == 1 then
			playAnim('boyfriend', 'dodgeDown', true, false, 0)
		elseif noteData == 2 then
			playAnim('boyfriend', 'dodgeUp', true, false, 0)
		elseif noteData == 3 then
			playAnim('boyfriend', 'dodgeRight', true, false, 0)
		end
	end
end`

### PoisonBullet

`function onCreate()
	for i = 0, getProperty('unspawnNotes.length')-1 do
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'PoisonBullet' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'noteskins/bulletNote')
			setPropertyFromGroup('unspawnNotes', i, 'missHealth', 0.6)
			setPropertyFromGroup('unspawnNotes', i, 'color', '4980555')
			setPropertyFromGroup('unspawnNotes', i, 'flipX', getRandomBool(69))
			setPropertyFromGroup('unspawnNotes', i, 'flipY', getRandomBool(69))
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', false);
				setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true);
			end
		end
	end
end

function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'PoisonBullet' and isSustainNote == false then
		playSound('gunshot')
		if noteData == 0 then
			playAnim('boyfriend', 'dodgeLeft', true, false, 0)
		elseif noteData == 1 then
			playAnim('boyfriend', 'dodgeDown', true, false, 0)
		elseif noteData == 2 then
			playAnim('boyfriend', 'dodgeUp', true, false, 0)
		elseif noteData == 3 then
			playAnim('boyfriend', 'dodgeRight', true, false, 0)
		end
	end
end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

There was stuff added, like the property that makes a specific certain color show whats behind the window, other than that, I'm not sure

**Comment by VoidedBattery** [comment]
`setPropertyFromGroup('unspawnNotes', i, 'mustPress', false)` puts the notes on the opponent's side, so you'd remove that line if you want it to be on the player's side.

**Comment by AyMarte** [comment]
Ty, I didn't expect that to cause that....
