### ISSUE TITLE
how do i fix this

### ISSUE THREAD

**Issue by DededeDrip** [ShadowMario/FNF-PsychEngine#13150]
### Describe your problem here.

I tried to compile psych 0.6.3 and ive been stuck with this message for days: source/PlayState.hx:1040: characters 69-71 : Expected , or ) does anyone know how to fix it? 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I only tried to change the timetxt color. nothing else

**Comment by KELOTOMU** [comment]
In PlayState line 1040 expected closing curly brackets "}" i think

**Comment by DededeDrip** [comment]
do you mean like line 1040 should use curly brackets instead of normal brackets?
