### ISSUE TITLE
I'm trying to do lime test html5

### ISSUE THREAD

**Issue by limebuilder** [ShadowMario/FNF-PsychEngine#1316]
### Describe your bug here.

pls help

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\Priyanshu77\Desktop\rn\FNF-PsychEngine-main>lime build html5
source/Achievements.hx:155: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/MainMenuState.hx:53: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:275: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/CharacterEditorState.hx:93: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/DialogueCharacterEditorState.hx:82: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

C:\Users\Priyanshu77\Desktop\rn\FNF-PsychEngine-main>
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Gui-iago** [comment]
see if you have all needed dependencies installed, open your web browser, then on the terminal type "lime test html5", then wait

these errors *should* be happening, mine looks like this

![image](https://user-images.githubusercontent.com/45212377/143295642-70f163a6-ffb6-4ec0-8baf-cd0a07e332f1.png)

however it actually sits there, and on my browser we have this 
![image](https://user-images.githubusercontent.com/45212377/143295701-59d8e1de-a9f9-40e6-bebe-f6c3f7f0e061.png)

**Comment by ShadowMario** [comment]
Those aren't errors, they're **warnings**, they won't stop your compiling. It's just some stupid Haxe thing saying that some functions i've used are outdated.
