### ISSUE TITLE
I dont know what this means, or how to fix it

### ISSUE THREAD

**Issue by Zeenathincodes** [ShadowMario/FNF-PsychEngine#13161]
### Describe your problem here.

I have been trying to make a character for a mod and it only has 3 animations for it (idle, left, and hey) and i dont know if it missing the down and right animation so i added them (in the character editor i just added the animations but not a new drawing) so i wanted to know how to fix this
![Screenshot 2023-08-22 115125](https://github.com/ShadowMario/FNF-PsychEngine/assets/90928935/93cee588-b41e-474b-86a0-e34e1dcdb3cb)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, I deleted dadbattle

**Comment by devin503** [comment]
Do you have an animation named `idle` in your character.json file? The xml can have its name as whatever, but the json needs to have the animation's "name" field set to "idle".
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/41199354/c2be39c5-185a-4bee-a196-1529be00bf83)

**Comment by Zeenathincodes** [comment]
all of the animations are named correctly already
