### ISSUE TITLE
HELP ME WITH THIS ERROR PLSSSS (the child error)

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#13168]
### What is your question?

yeah its just this goofy ahh error pls help me
<img width="637" alt="image" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/102251392/776cda2f-44b4-4410-b1dc-11b997f9b509">

**Comment by SrtHero278** [comment]
mind giving this line a shot?
```
addChild(new FlxGame(gameWidth, gameHeight, initialState, #if (flixel < "5.0.0") zoom, #end framerate, framerate, skipSplash, startFullscreen));
```
