### ISSUE TITLE
I cant import my character

### ISSUE THREAD

**Issue by CollerGIT** [ShadowMario/FNF-PsychEngine#13165]
### Describe your bug here.

When i try to lead my character it crashes and shows this message 
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/142944489/64567acc-981d-445e-ada7-a5d0f242f9b8)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just added mods.

**Comment by CollerGIT** [comment]
![CRAIG](https://github.com/ShadowMario/FNF-PsychEngine/assets/142944489/3996f35f-6b81-447c-bd18-9f9fce5bafde)
this is the sprite sheet btw

**Comment by Chidubemmo** [comment]
Wrong path?
