### ISSUE TITLE
removeLuaScript crashes the game in 0.7.1h

### ISSUE THREAD

**Issue by Wolfie1985yt** [ShadowMario/FNF-PsychEngine#13164]
### Describe your bug here.

Whenever I try to use removeLuaScript in the latest psych engine version, the game crashes and gives me an error message. All the paths are right but it keeps crashing when i use it, and it works in 0.6.3.

### Command Prompt/Terminal logs (if existing)

```bash
states/PlayState.hx (line 3225)
states/PlayState.hx (line 3208)
states/PlayState.hx (line 2147)
states/PlayState.hx (line 1910)
states/PlayState.hx (line 1772)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
old scripts from 0.6.3 might not work in 0.7

**Comment by Wolfie1985yt** [comment]
i am talking about removeLuaScript specifically and it is with a new lua script that works fine otherwise

**Comment by MemeHovy** [comment]
> i am talking about removeLuaScript specifically and it is with a new lua script that works fine otherwise with 0.7 and addLuaScript works in 0.7 still so shouldn't removeLuaScript as well

it's been changed

**Comment by Wolfie1985yt** [comment]
> > i am talking about removeLuaScript specifically and it is with a new lua script that works fine otherwise with 0.7 and addLuaScript works in 0.7 still so shouldn't removeLuaScript as well
> 
> it's been changed

Damn
