### ISSUE TITLE
I cannot add a song in source code!

### ISSUE THREAD

**Issue by deco1212** [ShadowMario/FNF-PsychEngine#13160]
### Describe your problem here.

When i try to add a song in source code, and when i try to play it, it crashes.

I tried adding both .OGG and .MP3 files [html uses mp3], i tried adding it in a week on the files, it simply did not work in anyway at all.

Do i need to do something extra?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5/Browser

### Did you edit anything in this build? If so, mention or summarize your changes.

Editing Donate in StoryMenuState.hx to play the song im talking about.

**Comment by AyMarte** [comment]
You usually want to make the song, you need these files listed for the song to work inside of either the `songs/your-song-name/` or `data/your-song-name`, depending on if it's sound or data: `Inst.ogg`,`Voices.ogg`,`Inst.mp3`, and `Voices.mp3` , and the song data that matches the name of the folder that it's in, aka the song name in the files, for example, `winter-wonderland` , with `.json` at the end of it., difficulties can be added with the addition before the `.json`, like for example, `philly-nice-hard'.

**Comment by deco1212** [comment]
Thanks, but that was already done, turns out the song name was just broken.
But now, i am stuck in the loading screen, what does that mean?
My possible theories is that the character is not loading.

**Comment by deco1212** [comment]
I found the problem, but then theres another problem.
Somehow, it could not load the song files that i previously had put, i tried replacing them with another one, which is a random song in the source code, and it loaded.
Sort of, now im stuck in a black screen.

**Comment by AyMarte** [comment]
Did it do the countdown?

**Comment by AyMarte** [comment]
If it did, then there is nothing to load on the screen
