### ISSUE TITLE
I cant compile the source help me!

### ISSUE THREAD

**Issue by matepro260** [ShadowMario/FNF-PsychEngine#13167]
### Describe your problem here.

Im trying to compile the game in my windows to mod the engine and if i try it, the terminal says this:

FNF-PsychEngine-0.6.3\FNF-PsychEngine-0.6.3\source\import.hx:1: characters 8-13 : ... referenced here
D:/Haxelib/haxe/lib/lime/8,0,2/src/lime/media/AudioSource.hx:138: characters 53-100 : ... referenced here
D:/Haxelib/haxe/lib/openfl/9,2,2/src/openfl/media/Sound.hx:14: characters 8-30 : ... referenced here
D:/Haxelib/haxe/lib/openfl/9,2,2/src/openfl/utils/Assets.hx:9: characters 8-26 : ... referenced here
D:/Haxelib/haxe/lib/openfl/9,2,2/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here
D:/Haxelib/haxe/lib/openfl/9,2,2/src/openfl/text/_internal/TextEngine.hx:9: characters 8-24 : ... referenced here
D:/Haxelib/haxe/lib/openfl/9,2,2/src/openfl/display/_internal/CairoTextField.hx:3: characters 8-40 : ... referenced here
D:/Haxelib/haxe/lib/openfl/9,2,2/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here
D:/Haxelib/haxe/lib/openfl/9,2,2/src/openfl/display/_internal/CairoGraphics.hx:6: characters 8-36 : ... referenced here
D:/Haxelib/haxe/lib/openfl/9,2,2/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
D:/Haxelib/haxe/lib/openfl/9,2,2/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
D:/Haxelib/haxe/lib/openfl/9,2,2/src/openfl/events/RenderEvent.hx:4: characters 8-44 : ... referenced here
D:/Haxelib/haxe/lib/openfl/9,2,2/src/openfl/display/DisplayObject.hx:13: characters 8-33 : ... referenced here
D:/Haxelib/haxe/lib/openfl/9,2,2/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
D:/Haxelib/haxe/lib/openfl/9,2,2/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
D:/Haxelib/haxe/lib/lime/8,0,2/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
D:/Haxelib/haxe/lib/lime/8,0,2/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
D:/Haxelib/haxe/lib/lime/8,0,2/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
D:/Haxelib/haxe/lib/lime/8,0,2/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
D:/Haxelib/haxe/lib/lime/8,0,2/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
D:/Haxelib/haxe/lib/lime/8,0,2/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
D:/Haxelib/haxe/lib/lime/8,0,2/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
D:/Haxelib/haxe/lib/lime/8,0,2/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
D:/Haxelib/haxe/lib/lime/8,0,2/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
D:/Haxelib/haxe/lib/lime/8,0,2/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
D:/Haxelib/haxe/lib/lime/8,0,2/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
D:/Haxelib/haxe/lib/lime/8,0,2/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
D:\Haxelib\haxe\std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here.

can someone can help me to this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no. i didnt

**Comment by JohnDoe3453** [comment]
yo download visual studio i will help ya, @NexIsDumb helped me

**Comment by NexIsDumb** [comment]
> yo download visual studio i will help ya, @NexIsDumb helped me

hm tho i think this could mean smth else

**Comment by NexIsDumb** [comment]
@matepro260 are you trying to compile the main or experimental branch
what haxe version do you have?
and if you're trying to compile the experimental one did you run the .bat in the setup folder?
