### ISSUE TITLE
some weird bug with source code

### ISSUE THREAD

**Issue by ChumbleDev** [ShadowMario/FNF-PsychEngine#13169]
### Describe your problem here.

i was trying to use the build game 64 feature but it said this (p.s. i have everything installed from the setup.bat dont say i need to install that cuz i already have and i have git already too) anyways heres the error: C:\HaxeToolkit\haxe\std/sys/Http.hx:495: characters 4-9 : Uncaught exception X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
C:\HaxeToolkit\haxe\std/sys/Http.hx:65: characters 4-14 : Called from here
C:\HaxeToolkit\haxe\std/sys/Http.hx:251: characters 12-25 : Called from here
C:\HaxeToolkit\haxe\std/sys/Http.hx:68: characters 3-30 : Called from here
C:\HaxeToolkit\haxe\std/sys/Http.hx:497: characters 3-19 : Called from here
C:/HaxeToolkit/haxe/lib/SScript/4,1,0/src/tea/backend/SScriptVer.hx:29: characters 45-142 : Called from here
C:/HaxeToolkit/haxe/lib/SScript/4,1,0/src/macro/Macro.hx:44: characters 3-21 : Called from here
(unknown) : Called from here

i literally dont know what to do ive tried everything it just wont work plz help btw im using psych engine 0.7.1h source code

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I didnt edit anything i used a fresh new build but its keeps on doing this error

**Comment by MemeHovy** [comment]
reinstall haxe 4.2.5

**Comment by ChumbleDev** [comment]
ill try reinstalling

**Comment by ChumbleDev** [comment]
update: everything was working until i downloaded sscript

**Comment by MemeHovy** [comment]
make sure you're using latest sscript

**Comment by blackvenom78** [comment]
i need your guys help bc i was trying to build psych engine and i ran into this same problem ive reinstalled haxe but its not working and i installed sscript and nothing i do works
