### ISSUE TITLE
cant go into visuals and ui and cant play any songs

### ISSUE THREAD

**Issue by ChumbleDev** [ShadowMario/FNF-PsychEngine#13176]
### Describe your problem here.

hi again so i was using psych engine and tried to go into visuals and ui but it gave me this error? (Error 1): objects/Note.hx (line 296)
objects/StrumNote.hx (line 27)
options/VisualsUISubState.hx (line 22)
options/OptionsState.hx (line 23)
options/OptionsState.hx (line 94)
flixel/FlxState.hx (line 220)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

that was only the first error, then i tried to play a song but then another error popped up (Error 2): objects/Note.hx (line 296)
objects/Note.hx (line 224)
states/PlayState.hx (line 1284)
states/PlayState.hx (line 503)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
 if anyone can help me please do

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ChumbleDev** [comment]
guess no ones gonna help

**Comment by AyMarte** [comment]
* Uncaught Error: Null Object Reference

**Comment by AyMarte** [comment]
>  Uncaught Error: Null Object Reference
It says it in the errors, something prob messed up with lua or if you have code or somethin'
