### ISSUE TITLE
Helpl

### ISSUE THREAD

**Issue by ItzKony** [ShadowMario/FNF-PsychEngine#13179]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/126213565/7da9a7dd-97d8-4718-a7ca-b7afa7358d3a)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
#12828

**Comment by ItzKony** [comment]
help again 
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/126213565/ee2ee7f7-a9e3-407d-a415-ce4b0aff927c)

**Comment by TerminallyAwesome** [comment]
how?
