### ISSUE TITLE
I try to open a mod and gives me crash

### ISSUE THREAD

**Issue by Buzzels** [ShadowMario/FNF-PsychEngine#13170]
### Describe your problem here.

When I press enter to start the mod, I get a crash and tells me there's something missing even though there's not and I know that for sure as I just downloaded this mod
![image_2023-08-23_145835599](https://github.com/ShadowMario/FNF-PsychEngine/assets/142964708/5ff820e1-68ba-4728-afdc-b149e0e26d70)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just downloaded the mod

**Comment by MemeHovy** [comment]
that's an issue with the mod, not the engine
