### ISSUE TITLE
stage asstes not using the right directory

### ISSUE THREAD

**Issue by Chidubemmo** [ShadowMario/FNF-PsychEngine#13174]
### Describe your problem here.

I made a custom stage with a direcotry called "genericfolder" for some reason it doesn't set the assets folder and instead remain as shared since it's the default.
When checking the command prompt Loading state was saying "Setting assets oath to shared". Weirdly enough the  genericfolder directory does in fact EXIST and I already added it in the xml.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by BernardoGP4504** [comment]
But where have you placed genericfolder?

**Comment by Chidubemmo** [comment]
outside of shared like the base weeks

**Comment by BernardoGP4504** [comment]
> outside of shared like the base weeks

The images inside of it are in the images folder like `genericfolder/images`

**Comment by Chidubemmo** [comment]
yes

**Comment by BernardoGP4504** [comment]
> yes

Then, in the stage hx file itself, what is the path that it's trying to use as an image?

**Comment by Chidubemmo** [comment]
I'm using 0.6.3, which has all the stages inside PlayState.hx. I hope I don't have to change the version for my mod

**Comment by BernardoGP4504** [comment]
> I'm using 0.6.3, which has all the stages inside PlayState.hx. I hope I don't have to change the version for my mod

Ok but what image is the stage object trying to load (like, the path that you put there)

**Comment by Chidubemmo** [comment]
Check this
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/87916057/0b4494f3-383c-4fe4-8db1-84654d733aee)

**Comment by BernardoGP4504** [comment]
They're inside that karlson folder in `genericfolder/images`?

**Comment by BernardoGP4504** [comment]
Also you don't need to call `updateHitbox()` if you're not using `setGraphicSize`

**Comment by Chidubemmo** [comment]
> They're inside that karlson folder in `genericfolder/images`?

Yes they are
> Also you don't need to call updateHitbox() if you're not using setGraphicSize

Ok

**Comment by BernardoGP4504** [comment]
Have you put `"genericfolder"` as an directory in the stage json?

**Comment by Chidubemmo** [comment]
yes

**Comment by BernardoGP4504** [comment]
> yes

But is it called `genericfolder` or `genericFolder`?

**Comment by Chidubemmo** [comment]
"genericfolder" I already checked. The problem is LoadingState.hx. For some reason it doesn't change the directory needed for loading the paths
