### ISSUE TITLE
Adding a new import sytstem for haxe

### ISSUE THREAD

**Issue by AyMarte** [ShadowMario/FNF-PsychEngine#13178]
### What is your question?

Is `import Random;` in the Psych Engine Haxe code, if not, can it be an addition to the engine?

**Comment by MemeHovy** [comment]
why are you trying to reinvent the wheel? and that is not an official haxe library

**Comment by CaptainBaldi** [comment]
`FlxRandom`:

**Comment by MemeHovy** [comment]
> `FlxRandom`:

I mean there's that, but why would you need that

**Comment by CaptainBaldi** [comment]
> > `FlxRandom`:
> 
> I mean there's that, but why would you need that

random bools, ints, floats, etc

**Comment by MemeHovy** [comment]
> > > `FlxRandom`:
> > 
> > 
> > I mean there's that, but why would you need that
> 
> random bools, ints, floats, etc

fair
