### ISSUE TITLE
Lua error i think?

### ISSUE THREAD

**Issue by Luciano686** [ShadowMario/FNF-PsychEngine#13186]
### Describe your problem here.

my friend is trying to compile the engine, but he's getting an error about lua? we don't really know

the error code:
source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheLeerName** [comment]
read wiki

**Comment by Luciano686** [comment]
> read wiki

but we made everything we don't know what to do

**Comment by SrtHero278** [comment]
wrong luajit lib.
try this.
```
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git
```

**Comment by Luciano686** [comment]
> wrong luajit lib. try this.
> 
> ```
> haxelib remove linc_luajit
> haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git
> ```

ok that is solved but we have another error

source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
source/PlayState.hx:1762: characters 13-23 : Type not found : MP4Handler
source/TitleState.hx:329: characters 58-61 : Float should be flixel.util.FlxAxes
source/TitleState.hx:329: characters 58-61 : ... For optional function argument 'repeatAxes'
