### ISSUE TITLE
steam somehow detected me playing a psych engine folder mod once and never again is this intended behavior

### ISSUE THREAD

**Issue by RUvlad1** [ShadowMario/FNF-PsychEngine#13187]
### What is your question?

i recently tried to play a psych mod that's installed by putting the mod in the mods folder, which is [rofnf funkin](https://gamebanana.com/mods/464122), and somehow, [one of my friends on steam got a notification about it](https://twitter.com/EVILN0NBINARY/status/1695036673124376744), which somehow even included the mod name

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/60317461/22265dbb-b1d3-49bb-89ac-971ecb866f82)

i didn't do anything else, other than add psych as a non-steam game to steam, which should also just show "Psych Engine", not the mod im playing

steam never even shows notifications for non-steam games, i cant replicate this and i genuinely no idea how this happened, but it did

**Comment by RUvlad1** [comment]
i should also note the mod never changed the titlebar text, so that's not what caused it

**Comment by ShadowMario** [comment]
LOL, this is probably either steam being steam or the mod changing something as a joke or whatever
