### ISSUE TITLE
I don't really know what to do here...

### ISSUE THREAD

**Issue by ToxicGamerz** [ShadowMario/FNF-PsychEngine#13180]
### Describe your problem here.

![umm why](https://github.com/ShadowMario/FNF-PsychEngine/assets/143048450/49ad5f58-a465-4e78-9428-65fed6b98ca0)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
make sure you add null checks

**Comment by ToxicGamerz** [comment]
how would i do that-

**Comment by MemeHovy** [comment]
`if (insertvarhere != null)`

**Comment by MemeHovy** [comment]
also make sure you take coding lessons and learn how haxe works too while you're at it

**Comment by ToxicGamerz** [comment]
i was just trying to play a fnf mod :(

**Comment by MemeHovy** [comment]
well it's a problem with the mod, not the engine
