### ISSUE TITLE
cant play or do anything in psych engine anymore

### ISSUE THREAD

**Issue by ChumbleDev** [ShadowMario/FNF-PsychEngine#13182]
### Describe your bug here.

hi again so i was using psych engine and tried to go into visuals and ui but it gave me this error? (Error 1): objects/Note.hx (line 296)
objects/StrumNote.hx (line 27)
options/VisualsUISubState.hx (line 22)
options/OptionsState.hx (line 23)
options/OptionsState.hx (line 94)
flixel/FlxState.hx (line 220)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

that was only the first error, then i tried to play a song but then another error popped up (Error 2): objects/Note.hx (line 296)
objects/Note.hx (line 224)
states/PlayState.hx (line 1284)
states/PlayState.hx (line 503)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
if anyone can help me please do

also heres another error i have when trying to change the note color: options/NotesSubState.hx (line 627)
options/NotesSubState.hx (line 140)
options/OptionsState.hx (line 17)
options/OptionsState.hx (line 94)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

### Command Prompt/Terminal logs (if existing)

```bash
i have none
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i did nothing

**Comment by Alltoupload** [comment]
Check the code, did you break it?

**Comment by CaptainBaldi** [comment]
no more psych engine for you

**Comment by ChumbleDev** [comment]
> no more psych engine for you

if your not gonna help and just gonna try to make me think i will never get psych engine back don’t comment

**Comment by ChumbleDev** [comment]
> Change your libraries' versions to the recommended ones

i tried that, still not working.

**Comment by CaptainBaldi** [comment]
:keoiki:

**Comment by ChumbleDev** [comment]
> :keoiki:

so are you gonna help? or are you just gonna make fun of me for an issue i can’t fix?

**Comment by MemeHovy** [comment]
![B8CA1DE6-CB3F-45C4-9F62-7E5B945C58C7](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/d4b56ae4-6bae-4618-a5cd-842187c891e9)

**Comment by ChumbleDev** [comment]
IS NO ONE GONNA FUCKING HELP?? IS EVERYBODY JUST GONNA MOCK ME FOR A ERROR I CANT FUCKING FIX??? WHY ARENT YOU HELPING AT ALL WHEN I CANT EVEN PLAY A NORMAL PSYCH ENGINE?? I JUST WANT TO PLAY PSYCH ENGINE AND ALL YOUR DOING IS NOT HELPING, ITS FUCKING USELESS TRYING TO ASK AT THIS POINT.

**Comment by MemeHovy** [comment]
well it's an issue with the mod, not the engine dumbass

**Comment by ChumbleDev** [comment]
> well it's an issue with the mods you have, not the engine dumbass

all i installed was a note splash skin, that’s it. and i can’t disable it because i can’t access the damn menu so what now

**Comment by Alltoupload** [comment]
close this

**Comment by ChumbleDev** [comment]
> close this

no i still havent it solved it retard also i took out the note splash skin dumbass

**Comment by SrtHero278** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/93018286/4d64ede3-f9d4-495c-bcb0-4090f4389714)
if the button doesnt work,
you may need to delete `funkin.sol` from [APP-DATA-FOLDER]/Roaming/ShadowMario/PsychEngine.

**Comment by ChumbleDev** [comment]
Ok thanks i’ll try that

**Comment by ChumbleDev** [comment]
One question though

**Comment by ChumbleDev** [comment]
how do i reset my save data without deleting the funkin.sol file?

**Comment by ChumbleDev** [comment]
or is it necessary?

**Comment by ChumbleDev** [comment]
Omg it worked thank you

**Comment by ChumbleDev** [comment]
I will make this solved now

**Comment by ChumbleDev** [comment]
Tysm

**Comment by ChumbleDev** [comment]
Goodbye everybody thanks for helping me fix psych engine i also found out it was a modpack that was the problem so yea thank you!

**Comment by ChumbleDev** [comment]
okay now i have another problem

**Comment by ChumbleDev** [comment]
the same thing happens whenever i try and play a song in psych engine for the second time

**Comment by ChumbleDev** [comment]
what the hell do i do now

**Comment by SrtHero278** [comment]
quick question, what mods/additional files do you have?

**Comment by ChumbleDev** [comment]
> quick question, what mods/additional files do you have?

i have splash pack

**Comment by SlashiiGithub** [comment]
for me i get an error where it says there is no decode_URL in libqt4_plugin.dll and then after that i get vlc had an error, does anyone have a fix for this
