### ISSUE TITLE
If you replace the health bar image, the icon colours break.

### ISSUE THREAD

**Issue by PugglesomeBenji** [ShadowMario/FNF-PsychEngine#13195]
### Describe your bug here.

I had a issue with the health bar colours, so I removed an image from mods/images which had the same name as the health bar. That fixed it

Now im here saying that if you have a file replacing the health bar image, the health bar colours will break

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

**Comment by frantastic24** [comment]
You need to update your health bar to the new format, it has to be transparent where the colors go

**Comment by PugglesomeBenji** [comment]
Oh ok! I was figuring that was the reason
