### ISSUE TITLE
blammed lights is only working on a certain song.

### ISSUE THREAD

**Issue by RandyKidYT2006** [ShadowMario/FNF-PsychEngine#1319]
### Describe your bug here.

for some reason, the blammed lights event is only working on a certain song that i ported into psyche engine(in this case it's Pibblammed), and shadow on the image below is a reskin of pico, so does it mean blammed lights only work when pico is the oppenent, or does it only work on this song?
![psyche-engine-bug-report](https://user-images.githubusercontent.com/93007681/143225128-91153b91-1343-4fd3-9800-41913c44ca0c.PNG)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

im using the downloaded build btw

**Comment by RandyKidYT2006** [comment]
guess i spoke too soon, the blammed lights event started working on all of the mod songs i ported that had the event, except for endless.
![psyche-engine-bug-report2](https://user-images.githubusercontent.com/93007681/143230120-449e52ff-82cf-42d8-a045-819fc7eb56b5.PNG)

**Comment by RandyKidYT2006** [comment]
had to reopen the issue, because the event decided to stop functioning again, here's the screenshot of how it looks.
![psyche-engine-bug-report3](https://user-images.githubusercontent.com/93007681/143231839-eb59bba5-e836-4aca-9002-33ffec4eead8.PNG)

**Comment by ShadowMario** [comment]
Looks like you forgot to save the events or is using it inappropriately.
