### ISSUE TITLE
help with compiling the game

### ISSUE THREAD

**Issue by Laskedjaslk** [ShadowMario/FNF-PsychEngine#13194]
### Describe your problem here.

so i was compiling and there was an error and it says this

source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
source/psychlua/CallbackHandler.hx:48: characters 41-46 : Class<llua.LuaL> has no field error
source/psychlua/FunkinLua.hx:273: lines 273-276 : Int should be Bool
source/psychlua/FunkinLua.hx:273: lines 273-276 : ... For function argument 'f'

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MemeHovy** [comment]
don't make duplicate issues
