### ISSUE TITLE
i have a little question about the engine

### ISSUE THREAD

**Issue by StefkeFnf** [ShadowMario/FNF-PsychEngine#13197]
### What is your question?

how do i add song json files in new psych engine 0.7.1h version
does anybody know
thanks

**Comment by SrtHero278** [comment]
json file handling has been uneffected in pysch 0.7. (or 7.1)
so same way as 6.3.

**Comment by StefkeFnf** [comment]
So how you do it then
How you import a chart

**Comment by DisIsNOt** [comment]
Kid named data/yourchartgoeshere
