### ISSUE TITLE
FNF mod ingrained crashes on first note and typing sections not working

### ISSUE THREAD

**Issue by Misoichysan** [ShadowMario/FNF-PsychEngine#13190]
### Describe your problem here.

Pretty much just the title but I want to play the fnf mod ingrained but for some reason when I play the song ingrained my game crashes after hitting the first note and when I play the song double kill the typing parts don't work and I can play the whole song without doing them even though there on my screen. I did change the color of all 4 of my arrows and when it crashes it says something about note splashes but when I put all the colors back to normal it does the same thing. I have the most up to date engine and newest version of the mod.
![Screenshot 2023-08-26 080031](https://github.com/ShadowMario/FNF-PsychEngine/assets/143266354/39c8cb27-9702-45ce-9f01-52fb4c96184d)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by SrtHero278** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/93018286/10f54cfe-6927-4ded-ae32-8eae756d2cfc)
line 121 is this.
there could be an issue with your spritesheet.

**Comment by Misoichysan** [comment]
> and now looking at flixel source, it seems to be your xml.

yeah, I have no idea what to do. I still haven't gotten it but I'm trying to find the saves for my settings so I can delete them and see if that works. mb I took so long to reply I rarely open up GitHub.

**Comment by Ozen2068** [comment]
Has this been solved, all the songs either have that same error or in the case of the may/gold song the notes are the default color and the monochrome timer doesn't appear making the song impossible to play.
![PsychEngine_e8HzhcfJEM](https://github.com/ShadowMario/FNF-PsychEngine/assets/155233509/4c1b7097-a200-48a5-b9e1-81a945b4994c)
![PsychEngine_ZOs1pKHBJJ](https://github.com/ShadowMario/FNF-PsychEngine/assets/155233509/3307d2fa-4f38-4e4e-8712-79d8c25bdbd8)
