### ISSUE TITLE
How can I get exact cam positions?

### ISSUE THREAD

**Issue by HappyAlexRomania** [ShadowMario/FNF-PsychEngine#13196]
### Describe your problem here.

I want to get the camera positions of these:
-camera position when it's in must hit section
-camera position when it's not in must hit section
-camera position when it's a gf section

But I don't know how. I did calculations and everything but it isn't accurate enough when I move the characters in a different stage. I tried getting the camera offset, character position, position offset, the scale and put them in a bunch of math stuff but nothing worked.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Drawoon2** [comment]
`    --For boyfriend
    --[[X]] getMidpointX('boyfriend') - 100 + getProperty("boyfriendCameraOffset[0]") - getProperty("boyfriend.cameraPosition[0]")
    --[[Y]] getMidpointY('boyfriend') - 100 + getProperty("boyfriendCameraOffset[1]") + getProperty("boyfriend.cameraPosition[1]")
    --For dad
    --[[X]] getMidpointX('dad') + 150 + getProperty("opponentCameraOffset[0]") + getProperty("dad.cameraPosition[0]")
    --[[Y]] getMidpointY('dad') - 100 + getProperty("opponentCameraOffset[1]") + getProperty("dad.cameraPosition[1]")
    --For gf
    --[[X]] getMidpointX('gf') + getProperty("girlfriendCameraOffset[0]") + getProperty("gf.cameraPosition[0]")
    --[[Y]] getMidpointY('gf') + getProperty("girlfriendCameraOffset[1]") + getProperty("gf.cameraPosition[1]")`

**Comment by HappyAlexRomania** [comment]
> ` --For boyfriend --[[X]] getMidpointX('boyfriend') - 100 + getProperty("boyfriendCameraOffset[0]") - getProperty("boyfriend.cameraPosition[0]") --[[Y]] getMidpointY('boyfriend') - 100 + getProperty("boyfriendCameraOffset[1]") + getProperty("boyfriend.cameraPosition[1]") --For dad --[[X]] getMidpointX('dad') + 150 + getProperty("opponentCameraOffset[0]") + getProperty("dad.cameraPosition[0]") --[[Y]] getMidpointY('dad') - 100 + getProperty("opponentCameraOffset[1]") + getProperty("dad.cameraPosition[1]") --For gf --[[X]] getMidpointX('gf') + getProperty("girlfriendCameraOffset[0]") + getProperty("gf.cameraPosition[0]") --[[Y]] getMidpointY('gf') + getProperty("girlfriendCameraOffset[1]") + getProperty("gf.cameraPosition[1]")`

I tried that but now it just doesn't want to move the camera. I put the variables in an onCreatePost function so probably it's because of that, but if it put it at the start, it will give me an error because if does it before the characters are getting created. Also, I'm using 'triggerEvent('Camera Follow Pos',dadX+200,dadY)' to move tha camera

**Comment by frantastic24** [comment]
![imagen](https://github.com/ShadowMario/FNF-PsychEngine/assets/95725102/d19c1b4b-8565-4184-8316-ecbb62e8103c)

**Comment by HappyAlexRomania** [comment]
> 

I put a triggerEvent at the end of the loop and left the values blank, but still doesn't work.

Here's the script:

```
function onUpdate()
	if followtype == 0 then
		followchars = false
	else
		followchars = true
	end
	
	if followchars == true then
		if followtype == 1 then
			if mustHitSection == false then
				if getProperty('dad.animation.curAnim.name') == 'singLEFT' then
					triggerEvent('Camera Follow Pos',dadX-ofs,dadY)
				end
				if getProperty('dad.animation.curAnim.name') == 'singRIGHT' then
					triggerEvent('Camera Follow Pos',dadX+ofs,dadY)
				end
				if getProperty('dad.animation.curAnim.name') == 'singUP' then
					triggerEvent('Camera Follow Pos',dadX,dadY-ofs)
				end
				if getProperty('dad.animation.curAnim.name') == 'singDOWN' then
					triggerEvent('Camera Follow Pos',dadX,dadY+ofs)
				end
				if getProperty('dad.animation.curAnim.name') == 'singLEFTalt' then
					triggerEvent('Camera Follow Pos',dadX-ofs,dadY)
				end
				if getProperty('dad.animation.curAnim.name') == 'singRIGHTalt' then
					triggerEvent('Camera Follow Pos',dadX+ofs,dadY)
				end
				if getProperty('dad.animation.curAnim.name') == 'singUPalt' then
					triggerEvent('Camera Follow Pos',dadX,dadY-ofs)
				end
				if getProperty('dad.animation.curAnim.name') == 'singDOWNalt' then
					triggerEvent('Camera Follow Pos',dadX,dadY+ofs)
				end
				if getProperty('dad.animation.curAnim.name') == 'idlealt' then
					triggerEvent('Camera Follow Pos',dadX,dadY)
				end
				if getProperty('dad.animation.curAnim.name') == 'idle' then
					triggerEvent('Camera Follow Pos',dadX,dadY)
				end
			else

				if getProperty('boyfriend.animation.curAnim.name') == 'singLEFT' then
					triggerEvent('Camera Follow Pos',bfX-ofs,bfY)
				end
				if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT' then
					triggerEvent('Camera Follow Pos',bfX+ofs,bfY)
				end
				if getProperty('boyfriend.animation.curAnim.name') == 'singUP' then
					triggerEvent('Camera Follow Pos',bfX,bfY-ofs)
				end
				if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN' then
					triggerEvent('Camera Follow Pos',bfX,bfY+ofs)
				end
				if getProperty('boyfriend.animation.curAnim.name') == 'idle' then
					triggerEvent('Camera Follow Pos',bfX,bfY)
				end
			end
		end
	else
		triggerEvent('Camera Follow Pos','','')
	end
	triggerEvent('Camera Follow Pos','','') -- I added this
end
```

**Comment by frantastic24** [comment]
You declared the vars as local, so the rest of the script can't access them

**Comment by HappyAlexRomania** [comment]
> You declared the vars as local, so the rest of the script can't access them

Oh, ok, thanks! It works now. Come to think of it, it does make sense because the lua API is just some functions that work in FNF and the functions are in other scripts. Sometimes I just don't realise some things :)

**Comment by frantastic24** [comment]
`boyfriend.height` or `boyfriend.frameHeight` should work

**Comment by HappyAlexRomania** [comment]
> boyfriend.height

Ok, thank you!
