### ISSUE TITLE
Text And Icon In Freeplay Change Position

### ISSUE THREAD

**Issue by franklhub** [ShadowMario/FNF-PsychEngine#13192]
### What feature do you want to get added on the **base** engine?

Change Positions For The Text And The Icon In Freeplay, Like The Text On The Icon Position, And The Icon In The Text Position

so nervous to ask something again about psych engine-

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
No
