### ISSUE TITLE
WHAT HAPPENEND???

### ISSUE THREAD

**Issue by I-am-someone-sh** [ShadowMario/FNF-PsychEngine#13199]
### Describe your problem here.

When I linking the app, is just give me a error

(sh: ./: Bad CPU type in executable)

this is never happenend before I promise!!
I searched on google, they tell me I have to install rosetta 2
but my macbook is intel chip so I can't
anyone can help me? I really need help on this

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't do anything

**Comment by mcagabe19** [comment]
uh the fuck? it's mot releated in psych engine?

**Comment by SevenHill-CyanS** [comment]
> 

I can compile before but is not working now

**Comment by AyMarte** [comment]
Prob try using a different device like an actual Mac, not a MacBook. It works perfectly fine compiling on my intel core i5 PC.

**Comment by AyMarte** [comment]
_if you messed with something, try undoing it and see if the issue still occurs_
