### ISSUE TITLE
what

### ISSUE THREAD

**Issue by simp-comet** [ShadowMario/FNF-PsychEngine#13203]
### Describe your problem here.

(I am not good at English so I use a translator. Sorry if the sentence is wrong.)
When using CustomSubstate and using restartSong() with an object inserted into the CustomSubstate instance, I get this error.
Is this a bug? Or can it be fixed in some way?
<img width="267" alt="a" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/107211610/929e4642-22a1-4997-a07a-e0ce03257f4f">

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

**Comment by mcagabe19** [comment]
probably lua code issue

**Comment by simp-comet** [comment]
> probably lua code issue

Hmmm, I think so too.
This error was happening in two scripts, one of which I solved by putting closeCustomSubstate() before restartSong().
However, the other does the same thing only to get the error.
What should I do:(

**Comment by simp-comet** [comment]
function onTimerCompleted(tag, loops,  loopsLeft)
		if tag == (tag name here) then
			closeCustomSubstate()
			restartSong(true)
		end
	end
When I write it this way, it no longer crashes.
Why doesn't it crash when I use runTimer?

**Comment by AyMarte** [comment]
It's probably a lua buildup issue, the Lua code shouldn't really run certain scripts together in a short period of time.
Also, the error message says _**`Null Object Reference`**_, usually means it's a script or code that messed up the lua
api.

**Comment by simp-comet** [comment]
I see, thank you very much!
