### ISSUE TITLE
.frag shader script?

### ISSUE THREAD

**Issue by TheRealPepsi** [ShadowMario/FNF-PsychEngine#13202]
### Describe your problem here.

Hey all, a script I was using to run my .frag shader works in 0.6.3, but anything after that crashes the game. Does anyone have a way of getting my .frag shader to work in 0.7.1h? Thanks!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by AyMarte** [comment]
You should probably try adding it at the start then turning the shader off, and then turn it back on when you need.
Other solutions may involve using a timer and setting local or global vars to the values you want to transfer.

**Comment by TheRealPepsi** [comment]
You wouldn't have a script for something like this, would you? I'd really appreciate it if you did!

**Comment by AyMarte** [comment]
I can make one, I just need the values for the .frag file, they usually are labeled as `uniform VALUETYPE`.

**Comment by AyMarte** [comment]
I found this website while gathering up my info, _guess something did save me some time coding up an entire file of code_:    [[SENSITIVE CONTENT] Shaders pack [Friday Night Funkin'] [Modding Tools]](https://gamebanana.com/tools/11481)

**Comment by AyMarte** [comment]
I hope that helps you out!

**Comment by TheRealPepsi** [comment]
Thank you! Funny enough, that's where I got the original script from, but I found another script online, and that works perfectly! Thanks for you help!
