### ISSUE TITLE
Freeplay Crashes?

### ISSUE THREAD

**Issue by CamOfChaos** [ShadowMario/FNF-PsychEngine#13205]
### Describe your bug here.

Engine crashes when entering freeplay menu, have tried anything within my ability and have no idea what to do.

### Command Prompt/Terminal logs (if existing)

```bash
states/FreeplayState.hx (line 71)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added characters, started making charts + Editing weeks

**Comment by ChumbleDev** [comment]
delete funkin.sol
