### ISSUE TITLE
how can i get BF or DAD Icon and change them with lua  ?

### ISSUE THREAD

**Issue by THOBY555** [ShadowMario/FNF-PsychEngine#1320]
### Describe your problem here.

how can i get BF or DAD Icon with lua ? lol i want to make wining icons to Psych engine that will be so cool if i could 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i edited the PlayState for cool things that working fine

**Comment by PoleyMagik** [comment]
I mean if you are already editing playstate I don't see the point in using lua for winning icons but here is something that could help #852

**Comment by ShadowMario** [comment]
`iconP1` and `iconP2`
