### ISSUE TITLE
Another compiling error.

### ISSUE THREAD

**Issue by arandomkid1** [ShadowMario/FNF-PsychEngine#13200]
### Describe your bug here.

just compiling and then i got this error.

### Command Prompt/Terminal logs (if existing)

```bash
Error: Could not find include file "C:/HaxeToolkit/haxe/lib/hxCodec/2,6,1/project/Build.xml"
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No i did not.

**Comment by Karim-Akra** [comment]
use haxelib remove hxCodec and try reinstalling hxCodec with haxelib install hxCodec 2.6.1
