### ISSUE TITLE
LUA

### ISSUE THREAD

**Issue by SeriouslyAnimations** [ShadowMario/FNF-PsychEngine#1321]
### What is your question?

Ive never experimented with lua, where can i go to know how to do thigs with it?

**Comment by CrusherMods** [comment]
The Wiki possibly, it also has examples there

**Comment by ShadowMario** [comment]
[Check the examples.](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API)
You should also Google about lua programming, it's hard to get a grasp on coding when you have no experience but yeah.
