### ISSUE TITLE
Hscripting enhancement

### ISSUE THREAD

**Issue by NoClueBruh** [ShadowMario/FNF-PsychEngine#13212]
### What feature do you want to get added on the **base** engine?

for the hscripts, you could use the haxe library 'Compile Time' to get all the classes that exist in the game (including the functions etc etc) so that everything is accessible with hscripts

//looks like this
 CompileTime.getAllClasses().map((classRef)->{
          //in this case, classRef as a string looks like: openfl.stuff.lmao.crap.Object
           classMap.set(Std.string(classRef), classRef);
          //in this case though, it looks more accessible as :Object!
          final classPath:Array<String> = Std.string(classRef).split('.');
          classMap.set(classPath[classPath.length-1], classRef);
         //you could of course add some checks to see if multiple references of 'Object' exist but you get the point
 });
//and of course some other classes that didnt get added through the CompileTime.getAllClasses().map method
//i have added all that on an engine i made sometime ago lol

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by AyMarte** [comment]
Lol I tried to do something like this recently, they kinda ignored it.
