### ISSUE TITLE
Source code compile error' :(

### ISSUE THREAD

**Issue by AnimationZEZ** [ShadowMario/FNF-PsychEngine#13219]
### Describe your problem here.

![fb50239f-b985-4e1b-8e03-0cea672f6ef8](https://github.com/ShadowMario/FNF-PsychEngine/assets/117897380/d62aa8bb-eb77-43fb-99cb-13e2a85c3a1c)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
download visual studio

**Comment by AnimationZEZ** [comment]
I have downloaded visual studio

**Comment by MemeHovy** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/c824ac55-031b-4c5e-84b6-9ffd5c74e2dd)
you need these too

**Comment by AnimationZEZ** [comment]
![IMG_20230831_193450401](https://github.com/ShadowMario/FNF-PsychEngine/assets/117897380/38615ea4-2db0-46a6-9adc-47d866e2b740)
I've downloaded it too since yesterday :l

**Comment by AnimationZEZ** [comment]
I've installed hxcpp but it still doesn't work
