### ISSUE TITLE
Playstate not found

### ISSUE THREAD

**Issue by ceruleancorntomatoes** [ShadowMario/FNF-PsychEngine#13211]
### Describe your problem here.

Updated to latest release, now every time I use getPropertyFromClass I can't get anything from playstate.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, recompiled multiple times without changing anything and still didn't work

**Comment by frantastic24** [comment]
PlayState has been moved, use `states.PlayState`

**Comment by ceruleancorntomatoes** [comment]
> PlayState has been moved, use `states.PlayState`

Thanks, probably should’ve dug a little deeper on my end in the first place
