### ISSUE TITLE
Compiling build gives an "Class<llua.Lua_helper> has no field sendErrorsToLua" error

### ISSUE THREAD

**Issue by Jamextreme140** [ShadowMario/FNF-PsychEngine#13215]
### Describe your problem here.

I've tried to compile the 0.7.1h source and every time I get this error:
`source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua`

I already did the `haxelib remove linc_luajit` & `haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git`, but It hasn't been solved.

Also, the VS Code shows me the error here:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/79620403/e8473e95-35e9-4dba-a99b-01fa3258e007)

Is there a solution fo this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Jamextreme140** [comment]
Nevermind, I solved it.

I ran again `haxelib remove linc_luajit` & `haxelib git linc_luajit https://github.com/superpowers04/linc_luajit`.
Maybe it was a Haxelib artifact

**Comment by MemeHovy** [comment]
it's a bug with haxelib/git, just do `haxelib git linc_luajit https://github.com/superpowers04/linc_luajit master` and override the local branch
