### ISSUE TITLE
Source code problem

### ISSUE THREAD

**Issue by Montymations** [ShadowMario/FNF-PsychEngine#13213]
### Describe your problem here.

ok so, apparently I have linc_luajit installed, but at the same time I don't? I don't understand.
![Screenshot 2023-08-30 104916](https://github.com/ShadowMario/FNF-PsychEngine/assets/84610277/a39d925f-38ab-4508-baee-a90aa26fc0f6)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by simp-comet** [comment]
`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit`
I think you need to run

**Comment by MemeHovy** [comment]
`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit master` to avoid an annoying haxelib/git bug

**Comment by Montymations** [comment]
> `haxelib git linc_luajit https://github.com/superpowers04/linc_luajit` I think you need to run

![Screenshot 2023-08-31 164256](https://github.com/ShadowMario/FNF-PsychEngine/assets/84610277/135c7b20-427c-49d7-8e4b-c6095d37f635)

**Comment by Montymations** [comment]
> `haxelib git linc_luajit https://github.com/superpowers04/linc_luajit master` to avoid an annoying haxelib/git bug

![Screenshot 2023-08-31 164351](https://github.com/ShadowMario/FNF-PsychEngine/assets/84610277/40bd996a-7c99-46f6-92dd-03ac8af6cca4)

**Comment by MemeHovy** [comment]
that's a bug from hmm
