### ISSUE TITLE
Validation error: how to fix (new to this stuff btw)

### ISSUE THREAD

**Issue by qkoime19** [ShadowMario/FNF-PsychEngine#13210]
### Describe your problem here.

Long story short i was installing the things for the psych engine and i needed to install ''haxelib run hmm install'' in windows PowerShell and i got that : Validation error: hmm.json not found in current working directory, how to fix it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
is the error not obvious to you? cd to your source code

**Comment by Alltoupload** [comment]
He's modding with Lua

**Comment by MemeHovy** [comment]
> He's modding with Lua

well that isn't a necessity then
