### ISSUE TITLE
Opponent Keeps Singing With Player Notes

### ISSUE THREAD

**Issue by AyMarte** [ShadowMario/FNF-PsychEngine#13214]
### Describe your problem here.

Hello, like the titled stated, every time I play a certain song with scripts, the opponent sings with the player uncommonly, despite the opponent not having a note cross their lane.

Scripts that are used will be linked in pastebin, _since i really don't want to f***ng flood this github repository_

* [Event that changes Wigglytuff's animation prefix](https://pastebin.com/sfWMniuy)
* [The Stage Script (Disabled.lua)](https://pastebin.com/ia03jsHT)
* [The Opponent's Note Script](https://pastebin.com/f9e2XCMH)
> Look at title and first line in the link above for more understanding.
* [Test Script(Mostly Extra BF Controller)](https://pastebin.com/W4c69DbW)

> I hope someone knows a solution to this `¯\_(ツ)_/¯`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing edited, just the usual Psych Engine >0.6.3<

**Comment by frantastic24** [comment]
Third script isn't checking if the note is for the player or not, so it will play the animation with any note

**Comment by AyMarte** [comment]
Thx for letting me know!

**Comment by AyMarte** [comment]
And btw, if anyone knows, where the note spin float around code it, let me know where with the script name, line number(s).
