### ISSUE TITLE
llua.lua helper bug

### ISSUE THREAD

**Issue by aislanbatistac** [ShadowMario/FNF-PsychEngine#13223]
### Describe your problem here.

![Captura de tela 2023-08-31 132242](https://github.com/ShadowMario/FNF-PsychEngine/assets/113957277/27be68fb-78d2-4db0-95b5-4f08503e1252)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MemeHovy** [comment]
`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit master`

**Comment by aislanbatistac** [comment]
Thank you

**Comment by MemeHovy** [comment]
np
