### ISSUE TITLE
" Unix.Unix_error(62, "recv", "") " How this it fix?

### ISSUE THREAD

**Issue by Votexz** [ShadowMario/FNF-PsychEngine#13228]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/91063818/32e0429a-7260-4203-95a5-c48f4b337f27)
  
  
Why this is don't fixing?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

This error appeared when I changed one character file

**Comment by MemeHovy** [comment]
the one thing I don't understand here is why you're getting a linux error

**Comment by MemeHovy** [comment]
also

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/3cf10b84-e326-4ef0-a972-f28ec9c6b31d)

**Comment by stikiPorter** [comment]
> the one thing I don't understand here is why you're getting a linux error

I don't know why I'm getting a linux error

**Comment by stikiPorter** [comment]
> also
> 
> ![image](https://user-images.githubusercontent.com/124418090/265115271-3cf10b84-e326-4ef0-a972-f28ec9c6b31d.png)

I'm sorry, I'm using a translator
