### ISSUE TITLE
How to add icon colours?

### ISSUE THREAD

**Issue by Ceznaf** [ShadowMario/FNF-PsychEngine#13220]
### What is your question?

For some reason when i updated to 0.7 and above the icon colour are just white. How to fix?

**Comment by MemeHovy** [comment]
make sure your healthbar image is updated too

**Comment by Ceznaf** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/assets/136116368/68a8866a-7ac0-48cf-b9ef-8eecc2c54775

**Comment by MemeHovy** [comment]
are you using any lua scripts that update the icon colors?

**Comment by Ceznaf** [comment]
no

**Comment by MemeHovy** [comment]
> make sure your healthbar image is updated too

note this applies to healthbars in the mods folders too

**Comment by Ceznaf** [comment]
imma check srry for late reply

**Comment by crowplexus** [comment]
delete healthBar.png from your mods
