### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by Gui-iago** [ShadowMario/FNF-PsychEngine#1322]
### Describe your problem here.

I forked the repository, then started editing the files, once I finished, I tried to compile it, and it gave me this error

![image](https://user-images.githubusercontent.com/45212377/143270916-da61cd10-dba1-4a9f-9a9c-32d000acb650.png)
i'm not exactly sure why, any help?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

PlayState.hx (ratings), CoolUtil.hx (Easy Difficulty Text), Credits.hx (added entire new lines to the code)

EDIT: HTML works, Windows or Linux compiling doesn't

![image](https://user-images.githubusercontent.com/45212377/143273958-4f181042-fd65-4958-bfb7-d9ece2c104f0.png)

Another EDIT: as it turns out, all changes from files that I've changed actually took effect, the issue is just that I can't compile the game for desktop, meanwhile, HTML5 simply works

**Comment by ShadowMario** [comment]
That's not Linux, that's HTML5.

**Comment by Gui-iago** [comment]
> That's not Linux, that's HTML5.

I compiled for HTML5 just for testing, and it worked, linux build is not working

**Comment by Gui-iago** [comment]
![image](https://user-images.githubusercontent.com/45212377/143291290-6bef1561-0f54-4c79-9708-637c38e5d87b.png)

**Comment by Gui-iago** [comment]
![image](https://user-images.githubusercontent.com/45212377/143291336-d01d8b3d-a7c5-4aea-a7d0-c8eea27b592d.png)

![image](https://user-images.githubusercontent.com/45212377/143291362-7ec8773e-26aa-453d-ab31-aa78d31cc101.png)

**Comment by PumpTutorials** [comment]
> That's not Linux, that's HTML5.

bruh the same happend to be you screwed the character.hx cuz i got the same error

source/Character.hx:134: characters 7-11 : Expected }

can u check out whats wrong there

**Comment by SrtHero278** [comment]
Just go to line 134 and remove the "}" but not the "{"
It worked for me.

**Comment by Gui-iago** [comment]
> Just go to line 134 and remove the "}" but not the "{" It worked for me.

works, thanks
