### ISSUE TITLE
This keeps poping up

### ISSUE THREAD

**Issue by Novatooos** [ShadowMario/FNF-PsychEngine#13222]
### Describe your problem here.

source/Main.hx:78: characters 61-65 : Float should be Int
source/Main.hx:78: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:78: characters 61-65 : ... For function argument 'child'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
0.5 and below are not supported

**Comment by ChumbleDev** [comment]
> 0.5 and below are not supported

this is exactly the reason i post psych engine errors on gamebanana instead of github

**Comment by MemeHovy** [comment]
> > 0.5 and below are not supported
> 
> this is exactly the reason i post psych engine errors on gamebanana instead of github

shadowmario said it himself, if you got nothing else to say, don't be here then

**Comment by Novatooos** [comment]
But it appears too when I compile the 0.6.3 version

**Comment by Novatooos** [comment]
and I was trying to compile 0.5.2h
