### ISSUE TITLE
invalid char 125 at position 152

### ISSUE THREAD

**Issue by WhittyOfficialFNF** [ShadowMario/FNF-PsychEngine#13224]
### Describe your bug here.

When I change the stage in the chart editor, I get this error message: invalid char 125 at position 152. Can anyone solve it for me? Thank you so much!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

.

**Comment by MemeHovy** [comment]
you screwed your stage json up
