### ISSUE TITLE
How do I add dialogue in the newest version?

### ISSUE THREAD

**Issue by zaynethedev** [ShadowMario/FNF-PsychEngine#13227]
### Describe your problem here.

In the dialogue wiki it says find "_**case 'senpai' | 'roses' | 'thorns' |**_" but in the newest version in **_PlayState.hx_** those lines don't exist, please help..

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing big.

**Comment by MemeHovy** [comment]
the dialogue stuff has been moved, check School.hx in stages

**Comment by Karim-Akra** [comment]
You now have to set the stuff on the stage HX file
Check week 6 stages to know more it's something like setDefaultIntro(shcoolIntro); if i remember correctly
