### ISSUE TITLE
the mod wont compile and gives me this error, im using 0.6.3

### ISSUE THREAD

**Issue by Sda-Pixel** [ShadowMario/FNF-PsychEngine#13221]
### Describe your problem here.

source/TitleState.hx:8: characters 8-29 : Type not found : flixel.sound.FlxSound
source/TitleState.hx:32: characters 8-29 : Type not found : flixel.sound.FlxSound
source/Alphabet.hx:10: characters 8-29 : Type not found : flixel.sound.FlxSound
source/editors/ChartingState.hx:33: characters 8-29 : Type not found : flixel.sound.FlxSound
source/editors/ChartingState.hx:150: character 13 : package flixel.system; in source/FlxSound.hx should be package;
source/FlxSound.hx:3: characters 20-41 : Type not found : flixel.sound.FlxSound

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
issues involving 0.6 are not supported

**Comment by ChumbleDev** [comment]
> issues involving 0.6 are not supported

wow, psych engine support at its fineist.

**Comment by Vortex2Oblivion** [comment]
run haxelib list flixel and send what it says here

**Comment by Sda-Pixel** [comment]
flixel-addons: 2.11.0 3.1.1 3.2.0 3.2.1 [git]
flixel-demos: 2.9.3 [3.0.0]
flixel-templates: [2.6.6]
flixel-tools: [1.5.1]
flixel-ui: [2.5.0]
flixel: 4.11.0 5.3.1 [5.4.0]

> run haxelib list flixel and send what it says here

**Comment by Vortex2Oblivion** [comment]
try
haxelib set flixel 4.11.0 
and 
haxelib set flixel-addons 2.11.0

**Comment by Sda-Pixel** [comment]
> try haxelib set flixel 4.11.0 and haxelib set flixel-addons 2.11.0

source/Main.hx:77: characters 4-44 : Float should be Int
source/Main.hx:78: characters 4-46 : Float should be Int
source/Main.hx:79: characters 4-35 : Float should be Int
source/flixel/sound/FlxSound.hx:117: characters 33-46 : Type not found : FlxSoundGroup
