### ISSUE TITLE
0.7.1h Issue

### ISSUE THREAD

**Issue by Montymations** [ShadowMario/FNF-PsychEngine#13236]
### Describe your problem here.

![Screenshot 2023-09-03 174627](https://github.com/ShadowMario/FNF-PsychEngine/assets/84610277/27fcefd2-ec6e-489d-90f4-829c4ca65244)

I keep getting this message every time

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Drawoon2** [comment]
check if linc-luajit is from this git `https://github.com/superpowers04/linc_luajit` and not from `https://github.com/AndreiRudenko/linc_luajit`
