### ISSUE TITLE
Add difficulty Problem (6.2.0)

### ISSUE THREAD

**Issue by GatoMagoXD** [ShadowMario/FNF-PsychEngine#13239]
### Describe your problem here.

I add a new difficulty but now dont load any difficulty correctly
Now load the .Json so '-tutorial--hard'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I add some sprites a songs

**Comment by Funkypupo** [comment]
make sure ur diff name is correct
(Ex: Crazy Difficulty)
name the .png file "crazy.png" or "insane.png" or whatever you like and put it in assets/images/menudifficulties
and make sure the json is correct so for example:

"tutorial-crazy.json"

and it should be the name of ur png file, and put it in assets/data/tutorial/ or whatever ur song name is

and finally, make sure the week has the difficulty in it. it should be in assets/weeks/ 
it should be a .json named your week name.
and inside it should be this template I made:
"
{
	"songs": [
		[
			"YOUR SONG",
			"ICON NAME",
			[
				235,
				235,
				255
			]
		]
                --PUT A COMMA IF YOU WANT 2 SONGS
	],
	"hiddenUntilUnlocked": false,
	"hideFreeplay": false,
	"weekBackground": "WEEKBG",
	"difficulties": "Easy, Normal, Hard, YOUR NEW DIFFICULTY",
	"weekCharacters": [
		"",
		"bf",
		""
	],
	"storyName": "???",
	"weekName": "YOUR WEEK",
	"freeplayColor": [
		146,
		113,
		253
	],
	"hideStoryMode": false,
	"weekBefore": "week1",
	"startUnlocked": true
}
"
after that it should be working

**Comment by GatoMagoXD** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/assets/135041008/6fcd8eda-89fb-4efe-90f3-25196ca41b94

**Comment by GatoMagoXD** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/assets/135041008/998d3f83-cc2b-4692-99e8-11ee9eea34f5

**Comment by BernardoGP4504** [comment]
There's a duplicate `-` somewhere

**Comment by GatoMagoXD** [comment]
I make other source folder to can end this proyect, thanks for your help
