### ISSUE TITLE
i need help on mouse pointer position

### ISSUE THREAD

**Issue by Funkypupo** [ShadowMario/FNF-PsychEngine#13235]
### What is your question?

**okay, so i want something that if you click the opponent, it triggers an event.** 
i read the wiki and it says "Mouse Position Functions" but it don't say nothing about clicking the opponent
and so i read the "Variables" section but there is still nothing about the position.
Sure i can just do
"if getMouseX('game') == # then"
but i can't really get it to work, please help

What am I using? Lua
what version? 0.7.1h

**Comment by Funkypupo** [comment]
also, i took a screenshot in case i am doing one of the functions wrong.
<img width="622" alt="Screenshot 2023-09-03 162449" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/95576360/b8769570-ad95-449d-8bc7-b1ab0312b790">

**Comment by MemeHovy** [comment]
make sure you’re using traces though to make sure your doing this correctly

**Comment by Funkypupo** [comment]
i made sure already

**Comment by MemeHovy** [comment]
just a reminder the wiki is still outdated and not updated to support 0.7 yet as far as I'm aware

**Comment by MemeHovy** [comment]
but it's not entirely wrong

**Comment by Funkypupo** [comment]
do u know how to get if the mouse pointer is at a specific sprite?
i tried to do something like
"if getProperty('mousePointer.pos') == getProperty('opponent.pos') then"
but that won't work

**Comment by MemeHovy** [comment]
[try looking at this for an example](https://github.com/mario1D240/fnf-inde-cross-html5-test/blob/ca98d55764d269a3ddd0adebd961e146acde89e6/assets/preload/data/dad-battle/attack.lua#L3)

**Comment by Funkypupo** [comment]
omg thanks

**Comment by MemeHovy** [comment]
> omg thanks

np
