### ISSUE TITLE
curl command doesnt work 

### ISSUE THREAD

**Issue by astridgaming75** [ShadowMario/FNF-PsychEngine#13237]
### Describe your bug here.

this is probably the wrong report category but i just need help

for some reason curl command wont work for me and i dont know why
it just gives me this error

_curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above._

i looked thru the entire github page and absolutely FUCKALL CHANGED
am i missing something?? did i not install a library correctly?? i need help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MemeHovy** [comment]
curl is a linux command, not a windows command

**Comment by astridgaming75** [comment]
> curl is a linux command, not a windows command-what the fuck are you trying to do

oh.

**Comment by crowplexus** [comment]
because you don't have git https://git-scm.com/download/win
