### ISSUE TITLE
[file_open,modsList.txt]

### ISSUE THREAD

**Issue by Fellegend** [ShadowMario/FNF-PsychEngine#13230]
### Describe your bug here.

Everytime I open the game, the error [file_open,modsList.txt] appears. 
I already extracted the modTemplate.zip file on the mods folder and example-mods folder.
Inside my modsList.txt folder: My-Mod|1

### Command Prompt/Terminal logs (if existing)

```bash
Cmd prompt: powershell.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only the application name and the intro text on titleState.hx

**Comment by MemeHovy** [comment]
modsList.txt is supposed to be automatically generated

**Comment by Fellegend** [comment]
> modsList.txt is supposed to be automatically generated

but it WAS generated automatically generated!

**Comment by Fellegend** [comment]
> modsList.txt is supposed to be automatically generated

nvm now it's workin and idk why
