### ISSUE TITLE
i get crashed

### ISSUE THREAD

**Issue by Lien2** [ShadowMario/FNF-PsychEngine#13238]
### Describe your problem here.

when i put my character in a random week, hit enter it will crash the game but other characters work normally, am i missing something?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
show the error

**Comment by GatoMagoXD** [comment]
The character be **missing important animation** or don't have the **.json in characters folder**, to know the specify Error need **see the error**
