### ISSUE TITLE
Opening game-coded substates like when pressing 7 or 8 in song.

### ISSUE THREAD

**Issue by AyMarte** [ShadowMario/FNF-PsychEngine#13233]
### Describe your problem here.

Sorry for the bother, but does anyone know how I could potentially open a substate source-coded into the game? I'm trying to make a custom pause screen in lua and it'd be a pleasure if someone knew how I could open a substate like the debug chart, thank you.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Like always, still using 0.6.3

Even when I tried it with lua haxe code, it just gave me an error `mods/scripts/TestPause.lua:onUpdatePost - hscript:1: Invalid access to field switchState`
I've added the `addHaxeLibrary()` functions at stated below:
```
addHaxeLibrary('FlxSubState', 'flixel.substate')
addHaxeLibrary('MusicBeatState', 'states.musicbeatstate')
addHaxeLibrary('ChartingState', 'states.editors.chartingstate')
addHaxeLibrary('TransitsionableState', 'flixel.addons.transition.transitionablestate')
addHaxeLibrary('PlayState', 'flixel.playstate')
```
and ran this line of code when I interacted with the chart editor custom option: `runHaxeCode('MusicBeatState.switchState(new ChartingState());')`

**Comment by AyMarte** [comment]
Even when I tried it with lua haxe code, it just gave me an error `mods/scripts/TestPause.lua:onUpdatePost - hscript:1: Invalid access to field switchState`

**Comment by CaptainBaldi** [comment]
none of these packages are valid

**Comment by AyMarte** [comment]
Do you have any ideas or packages that would be valid in this case?

**Comment by BernardoGP4504** [comment]
> Do you have any ideas or packages that would be valid in this case?
```haxe
backend.MusicBeatState
states.editors.ChartingState
backend.PlayState
```
All the others, check documentation on the flixel website, also don't forget any capital letters

**Comment by BernardoGP4504** [comment]
Also wdym import playstate, you're already in playstate, also use `game` instead
