### ISSUE TITLE
simply everytime i attempt lime test windows, this happens

### ISSUE THREAD

**Issue by MANKMORE** [ShadowMario/FNF-PsychEngine#13247]
### Describe your problem here.

please help me
![Screenshot (52)](https://github.com/ShadowMario/FNF-PsychEngine/assets/88376349/3592adb7-4a51-4688-9da6-cc1e1550fa42)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit master`

**Comment by MemeHovy** [comment]
and don't make duplicate issues

**Comment by MANKMORE** [comment]
k

**Comment by MANKMORE** [comment]
also i got error Eof when i tried

**Comment by MemeHovy** [comment]
> also i got error Eof when i tried

show

**Comment by MANKMORE** [comment]
Downloading linc_luajit-0,0,6.zip...
Download complete: 0.25KB in 0.8s (0.2KB/s)
Download complete: 1.83MB in 0.9s (1910.4KB/s)
Failed to download https://lib.haxe.org:443/files/3.0/linc_luajit-0,0,6.zip. (1/3)
Custom([file_write,C:/HaxeToolkit/haxe/lib/linc_luajit-0,0,6.zip])
Download complete: 0.25KB in 0.9s (0.2KB/s)
Download complete: 1.82MB in 1.4s (1253.3KB/s)
Failed to download https://lib.haxe.org:443/files/3.0/linc_luajit-0,0,6.zip. (2/3)
Custom([file_write,C:/HaxeToolkit/haxe/lib/linc_luajit-0,0,6.zip])
Download complete: 0.25KB in 0.8s (0.2KB/s)
Download complete: 3.43MB in 2.5s (1365.1KB/s)
Error: Eof

**Comment by MemeHovy** [comment]
make sure you have enough space to install it and it can also be a wifi issue, and not to mention you're supposed to do
`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit master` not install it from haxelib

**Comment by MANKMORE** [comment]
so it was space, i tried both. i might've fixed it
