### ISSUE TITLE
question: directory?

### ISSUE THREAD

**Issue by Funkypupo** [ShadowMario/FNF-PsychEngine#13242]
### What is your question?

this is not an issue, if this isn't allowed ill close this. 
so there is something in the stage json files that say ' "directory": week1'
now idk if this is only for source code :\ but yeah just wondering

**Comment by MemeHovy** [comment]
> ### What is your question?
> this is not an issue, if this isn't allowed ill close this. so there is something in the stage json files that say ' "directory": week1' now idk if this is only for source code :\ but yeah just wondering

that's for the week files

**Comment by frantastic24** [comment]
Only source
