### ISSUE TITLE
Compiling Error for 7.1h:  Unix.Unix_error(62, "recv", "")

### ISSUE THREAD

**Issue by Danky136** [ShadowMario/FNF-PsychEngine#13244]
### Describe your problem here.

I had reinstalled HxCodec and attempted to reinstall it. I was then greeted with the following error:
`Unix.Unix_error(62, "recv", "")`
Is there any possible solution to the error at this current moment?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
don't make duplicate issues
