### ISSUE TITLE
Where should I add lua in the mod folder?

### ISSUE THREAD

**Issue by KiryNUKE** [ShadowMario/FNF-PsychEngine#13245]
### What is your question?

Where should I add lua in the mod folder?

**Comment by MemeHovy** [comment]
depends on what it's for

**Comment by KiryNUKE** [comment]
And you can list everything and what the folder is for

**Comment by MemeHovy** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki have a look here
