### ISSUE TITLE
credits.txt is not working

### ISSUE THREAD

**Issue by Funkypupo** [ShadowMario/FNF-PsychEngine#13240]
### Describe your problem here.

kk, soooo i put my credits.txt in the mods/data folder and it's not working! 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope im using lua

**Comment by MemeHovy** [comment]
can you send over the file so we can examine it further?

**Comment by frantastic24** [comment]
Credits without a modpack won't show up, idk if it's intended or not but mods should be distributed inside a pack anyway

**Comment by Funkypupo** [comment]
> can you send over the file so we can examine it further?

yes here
[credits.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/12516792/credits.txt)

**Comment by Funkypupo** [comment]
> Credits without a modpack won't show up #12856

thanks bro
