### ISSUE TITLE
How to keep a video from disappearing?

### ISSUE THREAD

**Issue by CrystalClearer** [ShadowMario/FNF-PsychEngine#13253]
### Describe your problem here.

My problem is that I'm trying to use a video as a game over screen but when the video ends, it gets removed, showing the normal game over animation. I want to know how I can keep it on screen on the last frame of the video.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/112520718/2d289093-1634-47b8-846d-d0d79a40fd5a)
This is all the code I have for the video script.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

N/A

**Comment by CaptainBaldi** [comment]
probably remove `video.dispose` from the video's `onReachedEnd` function in `startVideo`
basically you can't do it unless you override `startVideo` with a recreation that doesn't dispose of the video on finish, which would at minimum require `runHaxeCode`
