### ISSUE TITLE
tryna compile, keep getting this error

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#13256]
### Describe your problem here.

```
C:\Users\james\ditto\Candy-Funkin-n-Fries>lime test windows

Compiling group: haxe
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/ -IC:/HaxeToolkit/haxe/lib/hxCodec/git/project/vlc/include -IC:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\james\ditto\Candy-Funkin-n-Fries\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,3,2/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_CHECK_POINTER(haxe) -DHXCPP_STACK_TRACE(haxe) -DHXCPP_STACK_LINE(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/lime/_internal/backend/native/TextEventInfo.cpp
 - src/sys/io/_Process/Stdout.cpp
 - src/openfl/display/_internal/Context3DElementType.cpp
 - src/flixel/system/debug/interaction/tools/Pointer.cpp
 - src/shaders/RGBPalette.cpp
 - src/flixel/path/FlxPathDrawData.cpp
 - src/openfl/system/SecurityDomain.cpp  [haxe,release]
Error: Pointer.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
```

please help ;-;
I'm on 0.7.1h

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by mcagabe19** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions
and downgrade hxcpp to 4.2.1

**Comment by ItsCapp** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions and downgrade hxcpp to 4.2.1

I tried it and it still has the same error ;-;

**Comment by mcagabe19** [comment]
> > https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions and downgrade hxcpp to 4.2.1
> 
> I tried it and it still has the same error ;-;

u seem like have ``VS Community 2022`` but u needed ``VS Community 2019`` and ``MSVC v142 - VS 2019 C++ x64/x86 build tools`` and also ``Windows SDK (10.0.17763.0)``

**Comment by ItsCapp** [comment]
> > > https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions and downgrade hxcpp to 4.2.1
> > 
> > 
> > I tried it and it still has the same error ;-;
> 
> u seem like have `VS Community 2022` but u needed `VS Community 2019` and `MSVC v142 - VS 2019 C++ x64/x86 build tools` and also `Windows SDK (10.0.17763.0)`

thanks! I needed to downgrade VS Community to the 2019 version
