### ISSUE TITLE
char 34 at position 49

### ISSUE THREAD

**Issue by DrkMtrGmr01** [ShadowMario/FNF-PsychEngine#13259]
### Describe your problem here.

![Screenshot 2023-09-09 101647](https://github.com/ShadowMario/FNF-PsychEngine/assets/144550898/70338b39-91f7-4685-8bd7-0578c8461c43)
I'm not sure what happened, but I tried editing the character position in the JSON file and all of a sudden the song wouldn't work. Could someone help me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
you messed up your JSON file

**Comment by DrkMtrGmr01** [comment]
> you messed up your JSON file

Do u know what I might have done tho? Cause I'm not sure, but I could check tho

**Comment by MemeHovy** [comment]
> > you messed up your JSON file
> 
> Do u know what I might have done tho? Cause I'm not sure, but I could check tho

you shouldn't tinker with it manually, that can cause issues like that

**Comment by DrkMtrGmr01** [comment]
> 

I tried redoing the charting but when I try to play the song or test it it says the exact same thing.

**Comment by DrkMtrGmr01** [comment]
> > 
> 
> I tried redoing the charting but when I try to play the song or test it it says the exact same thing.

Maybe it's the stage file, I could check
