### ISSUE TITLE
Camera comically zoomed out on all stages

### ISSUE THREAD

**Issue by MelodyMizuki** [ShadowMario/FNF-PsychEngine#13252]
### Describe your problem here.

All stages are zoomed out for some reason, not sure what's causing it
![whar](https://github.com/ShadowMario/FNF-PsychEngine/assets/105437565/67151c34-cdec-4cad-9c5d-cd24f8f988f1)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MelodyMizuki** [comment]
Forgot to say, I did edit the build with a mod pack but that was after I found the issue

**Comment by mcagabe19** [comment]
> Forgot to say, I did edit the build with a mod pack but that was after I found the issue

check any zoom codes if there's

**Comment by MelodyMizuki** [comment]
I ended up just moving to Psych 7, the json's were normal and I couldn't figure anything out
