### ISSUE TITLE
LoadingState.hx error

### ISSUE THREAD

**Issue by Fellegend** [ShadowMario/FNF-PsychEngine#13251]
### Describe your problem here.

Well I want to add a loading screen to Psych Engine and someone 
told me to remove the #if NO_PRELOAD_ALL stuff in LoadingState.hx. I removed it but when I tried to compile the game, I get this error here:

C:\Users\User\my mod folder>lime test windows
source/states/LoadingState.hx:170: characters 3-7 : Expected }

If someone can help me, uhh... help me please

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I removed the #if NO_PRELOAD_ALL

**Comment by BernardoGP4504** [comment]
Did you also remove the `#end` stuff

**Comment by Fellegend** [comment]
> Did you also remove the `#end` stuff

BRUH I'M DUMB!

**Comment by Fellegend** [comment]
oh

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Não
contém vírus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em seg., 11 de set. de 2023 às 21:51, BerGP ***@***.***>
escreveu:
