### ISSUE TITLE
source/states/MainMenuState.hx:83: characters 19-20: Missing ;

### ISSUE THREAD

**Issue by Fellegend** [ShadowMario/FNF-PsychEngine#13258]
### Describe your bug here.

Well, I tried to compile the came but this error appears:

**source/states/MainMenuState.hx:83: characters 19-20: Missing ;**

![Captura de Tela (169)](https://github.com/ShadowMario/FNF-PsychEngine/assets/142691547/73af05d2-bfbf-4a9c-92fd-0b9a66e356a2)

There is no ; missing at the lines 19 and 20. Can someone help me?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, but not the 19/20 lines

**Comment by SrBagel** [comment]
Its missing at line 83 not 19 and 20

**Comment by Fellegend** [comment]
> Its missing at line 83 not 19 and 20

Oh.
I'm really dumb
