### ISSUE TITLE
Crashes a few seconds after song loads

### ISSUE THREAD

**Issue by Superanthony8** [ShadowMario/FNF-PsychEngine#13255]
### Describe your bug here.

So I'm trying out a song for my mod but suddently it keeps crashing without showing any errors or causes, please help me if y'all can.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nah

**Comment by mcagabe19** [comment]
u needed show error logs

**Comment by Superanthony8** [comment]
> u needed show error logs

there's no error logs displaying anywhere, there's no crash folder too

**Comment by mcagabe19** [comment]
> > u needed show error logs
> 
> there's no error logs displaying anywhere, there's no crash folder too

did you check song file is ogg format?

**Comment by Superanthony8** [comment]
> a

ofc

**Comment by GatoMagoXD** [comment]
You have the suficiente ram to load the song?

**Comment by Superanthony8** [comment]
normally, yes

> You have the suficiente ram to load the song?
