### ISSUE TITLE
How to repeat the animation of icons in healthbar?

### ISSUE THREAD

**Issue by KiryNUKE** [ShadowMario/FNF-PsychEngine#13268]
### What is your question?

How to repeat the animation of icons in healthbar?

**Comment by MemeHovy** [comment]
don't open duplicate issues

**Comment by BernardoGP4504** [comment]
You mean "replicate"? Also, just port the source code into lua code it's not that hard

**Comment by MemeHovy** [comment]
> You mean "replicate"? Also, just port the source code into lua code it's not that hard

they're called duplicates

**Comment by BernardoGP4504** [comment]
> > You mean "replicate"? Also, just port the source code into lua code it's not that hard
> 
> they're called duplicates

wasn't talking to you, meant the title of the issuew where he said repeat instead of replicate
