### ISSUE TITLE
Z and X have unchangable keybindings

### ISSUE THREAD

**Issue by mayo78** [ShadowMario/FNF-PsychEngine#1326]
### Describe your bug here.

Z is permanently confirm and X is permanently cancel
![image](https://user-images.githubusercontent.com/75394229/143289434-9c189c1c-e392-4ed9-958d-e2c7e8d016a6.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

added a few mods

**Comment by ShadowMario** [comment]
0.4.2 issue, was already fixed on Source.
