### ISSUE TITLE
The Psych Engine v0.6.3 won't work

### ISSUE THREAD

**Issue by Ryan123as** [ShadowMario/FNF-PsychEngine#13267]
### Describe your problem here.

The problem with me here is every time I try to save something for example: weeks, etc.
It will either turn it into a file, not a JSON or it will just crash
And the reason why I use v0.6.3 not v0.7.1h, It's because I'm used 
to chart things in the version I'm using, not the newest versions
![Bruh](https://github.com/ShadowMario/FNF-PsychEngine/assets/108426077/3d670985-70d2-4c71-a889-009553841273)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
you gotta apend .json at the end of the filename

**Comment by Ryan123as** [comment]
I keep doing that and yet it doesn't work

**Comment by IceyX2** [comment]
click on view on explorer, click show, then click file name extensions
