### ISSUE TITLE
Error: Could not find haxelib "hxCodec", does it need to be installed?

### ISSUE THREAD

**Issue by IceyX2** [ShadowMario/FNF-PsychEngine#13264]
### Describe your problem here.

I keep getting this error, even though I've tried using haxelib to reinstall multiple times. I've even restarted my computer. Please help!
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/137276743/5200fc53-e72c-484d-886d-569751711451)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/137276743/c26e78bc-e9b1-419c-8be6-63338bc0517b)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by xFN10x** [comment]
welcome to the crew
https://github.com/ShadowMario/FNF-PsychEngine/issues/10756
https://github.com/ShadowMario/FNF-PsychEngine/issues/12770

**Comment by IceyX2** [comment]
I tried that but it still doesn't work

**Comment by IceyX2** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/137276743/e4dc6bcf-6103-4bae-92d0-30beea0e9fe9)
I noticed that the errors are different colors, maybe this has to do with the problem in some way?

**Comment by MemeHovy** [comment]
no, it doesn't

**Comment by xFN10x** [comment]
its red cause you just removed it

**Comment by xFN10x** [comment]
you did not add it back

**Comment by xFN10x** [comment]
I recommend making a text file in your root of the source code and then typing
`haxelib remove hxCodec`
`haxelib install hxCodec`
rename it to a .bat file, so you don't have to be typing the install/remove over and over. (trust me, reinstalling can make it work)

**Comment by bonzer75** [comment]
I had the same error recently. I fixed it installing hxCodec globally.

`haxelib install --global hxCodec`
