### ISSUE TITLE
How do I import the mods folder to the assets folder?

### ISSUE THREAD

**Issue by MrRainbowCoding** [ShadowMario/FNF-PsychEngine#13262]
### Describe your problem here.

I am trying to port my mod to HTML, but I don't know where to put everything. I tried putting things where they seem like they go, but it doesn't work. What am I doing wrong?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5/Browser

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited TitleState.hx, Project.xml, and MainMenuState.hx to add mod watermarks.

**Comment by mcagabe19** [comment]
html5 doesn't have mods support

**Comment by MrRainbowCoding** [comment]
That's what I'm saying, I want to turn it into the assets folder.

**Comment by mcagabe19** [comment]
> That's what I'm saying, I want to turn it into the assets folder.

html5 doesn't even have lua u needed port to haxe

**Comment by BernardoGP4504** [comment]
Port the folders having their appropriate counterpart on assets, while lua scripts have to be done in direct source code instead

**Comment by MrRainbowCoding** [comment]
@BernardoGP4504 , do I use preload for this or just assets or both?

**Comment by MrRainbowCoding** [comment]
@mcagabe19 how do I port it to haxe?

**Comment by BernardoGP4504** [comment]
> @BernardoGP4504 , do I use just preload for this or just assets or both?

Both.
Porting Lua scripts shouldn't be hard, look at the code on your Lua script and check what the functions there do on `FunkinLua.hx`, then implement them in the source code
