### ISSUE TITLE
4 errors with compileing

### ISSUE THREAD

**Issue by xFN10x** [ShadowMario/FNF-PsychEngine#13263]
### Describe your bug here.

i try to compile and it throws some errors and does not create any exe files

### Command Prompt/Terminal logs (if existing)

```bash
PS C:\Users\sonic\Desktop\fnfmod\FNF-PsychEngine-main\art> cd .
PS C:\Users\sonic\Desktop\fnfmod\FNF-PsychEngine-main\art> cd ..
PS C:\Users\sonic\Desktop\fnfmod\FNF-PsychEngine-main> lime test windows
------------------------SScript 5.1.0 Macro------------------------
Special Thanks:
- CrowPlexus

Checking version...
You are using the 4.2.5 version of Haxe, SScript works best with Haxe 4.3.2. Consider updating Haxe.
Continuing...
-------------------------------------------------------------------

source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
source/psychlua/CallbackHandler.hx:48: characters 41-46 : Class<llua.LuaL> has no field error
source/psychlua/FunkinLua.hx:273: lines 273-276 : Int should be Bool
source/psychlua/FunkinLua.hx:273: lines 273-276 : ... For function argument 'f'
PS C:\Users\sonic\Desktop\fnfmod\FNF-PsychEngine-main>
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Fearester2008** [comment]
I have it too

**Comment by mcagabe19** [comment]
```
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git
```

**Comment by xFN10x** [comment]
ok, i'll try that later

**Comment by xFN10x** [comment]
now i get this error

C:\Users\(username)\Desktop\fnfmod\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

also, i do have vs installed

**Comment by MemeHovy** [comment]
> now i get this error
> 
> C:\Users(username)\Desktop\fnfmod\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion Warning: Could not find Visual Studio VsDevCmd Missing HXCPP_VARS Error: Could not automatically setup MSVC
> 
> also, i do have vs installed

but you don’t have the right components needed is the issue

**Comment by xFN10x** [comment]
yeah

**Comment by xFN10x** [comment]
which one do i need?

**Comment by MemeHovy** [comment]
![A2622ACE-4233-4D79-9CB5-EFDFED930EEE](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/dbac90cb-d4c5-4b25-8ddc-dcfd8d73e4ef)

**Comment by xFN10x** [comment]
thats what i got

**Comment by xFN10x** [comment]
but the windows sdk is slightly newer, cause the old one did not show up in my vs installer

**Comment by MemeHovy** [comment]
because you’re using visual studio 2022 instead

**Comment by xFN10x** [comment]
oh ok

**Comment by xFN10x** [comment]
i uninstalled vs 2019 before but i guess i have to reinstall it

**Comment by xFN10x** [comment]
Yay more errors! Now i get this, Error: Could not find haxelib "hxCodec", does it need to be installed? 
even though i already have it installed the way they say in README.md

**Comment by CaptainBaldi** [comment]
`haxelib install hxCodec`

**Comment by xFN10x** [comment]
thats what i did

**Comment by xFN10x** [comment]
im going to try to haxelib remove then install

**Comment by xFN10x** [comment]
it took way longer but it still says
Error: Could not find haxelib "hxCodec", does it need to be installed?

**Comment by xFN10x** [comment]
after i reinstalled the thing like 10 times it is now compiling
