### ISSUE TITLE
0.6.3 comping error. (i dont need 0.7.x)

### ISSUE THREAD

**Issue by ToriRaksanin** [ShadowMario/FNF-PsychEngine#13273]
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/127664564/2e9c9691-28d6-4b69-b29b-ac46f342623f)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by MemeHovy** [comment]
remove the zoom thing in FlxGame, and use hxCodec 2.5.1

**Comment by ToriRaksanin** [comment]
> remove the zoom thing in FlxGame, and use hxCodec 2.5.1

What is FlxGame? I don't have such a .hx...

**Comment by ToriRaksanin** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/127664564/3c138db0-5e3d-4a67-bc2b-996665c0bd51)
You mean this?

**Comment by MemeHovy** [comment]
yes

**Comment by ToriRaksanin** [comment]
You're the only one who could help me in a week, damn it... Thank you so much, good luck. Bye!! <3

**Comment by MemeHovy** [comment]
> You're the only one who could help me in a week, damn it... Thank you so much, good luck. Bye!! <3

np, and cya <3
