### ISSUE TITLE
How To Add Two Events At The Same Time

### ISSUE THREAD

**Issue by HeroSnackz** [ShadowMario/FNF-PsychEngine#13275]
### Describe your problem here.

I want to change both background and character at the same time for a betadciu, but I don't know how to do it. How do I do it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by GatoMagoXD** [comment]
With **X** you can zoom the graph, with **Z** you can remove the zoom.
The maximum zoom is 1/24, **you can put two events very close with 24 zoom**. _(this is milliseconds apart but may work)_

**Comment by Lorekeeper49** [comment]
It's possible to combine 2 events into one, in the events tab there should be a plus and minus icon beside each other that you can click on, doing so while having an event selected will allow you to combine events
