### ISSUE TITLE
Clickable menu

### ISSUE THREAD

**Issue by Crimson-maker** [ShadowMario/FNF-PsychEngine#13272]
### What is your question?

I saw a lot of example on how to do this but they didn't really explain it that well for me able to code it in. And i want to be a little different. When you hover it plays an animation and of course the clicking functionality. I know it's probably a lot but it will really help me out!

(Also please tell me where to put stuff. I'm so bad at coding, Thanks)

**Comment by MemeHovy** [comment]
simple, you learn how to, you don't ask for others to code for you on a github issue

**Comment by DisIsNOt** [comment]
Check MainMenuState.hx it's the same logic
