### ISSUE TITLE
How Do I Add Multiple Events At The Same Time?

### ISSUE THREAD

**Issue by HeroSnackz** [ShadowMario/FNF-PsychEngine#13279]
### Describe your problem here.

I've always wanted to make a playable BETADCIU, but I don't know how to add multiple events for changing characters, playing animations, changing backgrounds, etc. Is there a way to do it?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by SrBagel** [comment]
Its in the chart editor just press the green plus 
![THISONE](https://github.com/ShadowMario/FNF-PsychEngine/assets/128989598/6f1f7242-0fcc-4005-8a1c-c31c9988b22f)

**Comment by HeroSnackz** [comment]
> Its in the chart editor just press the green plus ![THISONE](https://user-images.githubusercontent.com/128989598/268406195-6f1f7242-0fcc-4005-8a1c-c31c9988b22f.png)

Thanks
