### ISSUE TITLE
Texture Atlas Help

### ISSUE THREAD

**Issue by Funkypupo** [ShadowMario/FNF-PsychEngine#13274]
### Describe your problem here.

TEXTURE ATLAS
i read the docs in the source code and it helped a little.
but it there a way i can actually do it without source codee??
if there is not i can just ask a suggestion, but i wanna make sure you can do it before adding.
this is because i have a huge spritesheet and it would go over 8192x8192.
and here is the directory the spritemap is
<img width="592" alt="Screenshot 2023-09-12 191514" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/95576360/d4ac6042-2894-4340-a96a-fdcdc7f7639f">
<img width="668" alt="Screenshot 2023-09-12 191504" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/95576360/73ee5a8b-d3a9-4b1d-9eb9-067e93a68d6a">
this is the error im getting:

animateatlas/AtlasFrameMaker.hx (line 49)
states/editors/CharacterEditorState.hx (line 820)
states/editors/CharacterEditorState.hx (line 504)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no.

**Comment by Funkypupo** [comment]
the error im getting btw, is when i go into character editor, and type in characters/BF_AIRSHIP_DEAD/
or when i type characters/BF_AIRSHIP_DEAD/spritemap1

**Comment by GatoMagoXD** [comment]
You Need a **.PNG and a .XML** to load a Character.
If just Want use a **Extra Folder** this have 2 Cases.
### Case 1: If the Folder is **Inside of Characters Folder** Need put this: `characters/(example folder)/(your character name)`
### Case 2: If Use **other Folder Without the Characters Folder** Need Have the **Folder Inside Images** and Put this: `(example folder)/(your character name)`

**Comment by Funkypupo** [comment]
> You Need a **.PNG and a .XML** to load a Character. If just Want use a **Extra Folder** this have 2 Cases. _Case 1:_ If the Folder is **Inside of Characters Folder** Need put this: `characters/(example folder)/(your character name)` _Case 2:_ If Use **other Folder Without the Characters Folder** Need Have the **Folder Inside Images** and Put this: `(example folder)/(your character name)`

i don't have a png or xml, the reason why is because adobe animate says the spritesheet is too big, and when i export it, the xml file has an error which says it does not exist. for example: "BoyfriendIdle does not exist" that's why i am asking for texture atlas.

**Comment by Drawoon2** [comment]
Psych engine can't support texture atlas from Adobe Animate 2019 to up

**Comment by Funkypupo** [comment]
okay
