### ISSUE TITLE
Just wondering is it possible to make botplay look like an actual player?

### ISSUE THREAD

**Issue by Rex568** [ShadowMario/FNF-PsychEngine#13276]
### What is your question?

A friend wanted me to try and make this for them, and I could not figure out if it was possible so I decided to ask the people who know more than I do.

**Comment by Rex568** [comment]
Specifically a script to make bot-play, occasionally miss so it looks like a player.

**Comment by MemeHovy** [comment]
you can’t

**Comment by SrBagel** [comment]
Make the game lag that works for me
