### ISSUE TITLE
how to convert this?

### ISSUE THREAD

**Issue by I-am-someone-sh** [ShadowMario/FNF-PsychEngine#13281]
### Describe your problem here.

how can I convert this haxe code to lua script for psych engine?

bg.setGraphicSize(Std.int(bg.width * 1.63));

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no, I just need help

**Comment by Meme1079** [comment]
Maybe this???

```lua
local getBGInt = ({math.modf(getProperty('bg.width') * 1.63)})[1]
setGraphicSize('bg', getBGInt)
```

**Comment by I-am-someone-sh** [comment]
> Maybe this???
> 
> ```lua
> local getBGInt = ({math.modf(getProperty('bg.width') * 1.63)})[1]
> setGraphicSize('bg', getBGInt)
> ```

ok thanks you!
