### ISSUE TITLE
How to add scripts in version 0.7.1h

### ISSUE THREAD

**Issue by DiegoTheKid** [ShadowMario/FNF-PsychEngine#13289]
### What is your question?

When i downloaded the new version of Psych Engine, was making my mod, but the scripts file didnt exsist anymore, but i wanted to add them, so anyone knows how to add scripts in psych engine 0.7.1h?

**Comment by frantastic24** [comment]
Duplicate of #12849

**Comment by DiegoTheKid** [comment]
> Duplicate of #12849

Already did it thousand of times but didnt work and yes, i work with lua

**Comment by frantastic24** [comment]
The scripts folder works the same as it did before 0.7, this is a problem on your end

**Comment by DiegoTheKid** [comment]
> The scripts folder works the same as it did before 0.7, this is a problem on you
The scripts from the version 0.6.3 work the same way as 0.7.1h?

**Comment by DiegoTheKid** [comment]
> The scripts folder works the same as it did before 0.7, this is a problem on your end

The scripts from ver. 0.6.3 work the same as 0.7.1h?

**Comment by Cyachao** [comment]
You add them like 0.6.3; but your scripts may be using runHaxeCode (cannot be called twice or more) or set/getPropertyFromClass (0.7 organisation)
do `luaDebugMode = true` to see lua errors

**Comment by DiegoTheKid** [comment]
> You add them like 0.6.3; but your scripts may be using runHaxeCode (cannot be called twice or more) or set/getPropertyFromClass (0.7 organisation) do `luaDebugMode = true` to see lua errors

None of the scripts have those commands but they still not working anyway
