### ISSUE TITLE
Death Animation

### ISSUE THREAD

**Issue by Stickmation1234** [ShadowMario/FNF-PsychEngine#1328]
### What is your question?

Sorry to bother but I already added my death animation into the game but how do I set it where if that specific character loses it plays?

**Comment by Gui-iago** [comment]
script.lua

**Comment by SrtHero278** [comment]
https://cdn.discordapp.com/attachments/889357899015540736/901470021652447233/script.lua

**Comment by Stickmation1234** [comment]
Ok but how do you add a new pixel death animation to a certain character

**Comment by Stickmation1234** [comment]
> https://cdn.discordapp.com/attachments/889357899015540736/901470021652447233/script.lua
> This is a Lua script you need to modify the gameover.
> If you're using haxe, I have no idea.

So what if it’s a pixel death animation

**Comment by SrtHero278** [comment]
just modify the first line. the last parameter is the character's death animation you wanna use.
If the death animation was on a character named `"welp-he-dead"`
Then replace the third value with `"welp-he-dead"`.
Like this:
`setPropertyFromClass('GameOverSubstate', 'characterName', 'welp-he-dead');`

**Comment by Stickmation1234** [comment]
> just modify the first line. the last parameter is the character's death animation you wanna use.
> If the death animation was on a character named `"welp-he-dead"`
> Then replace the third value with `"welp-he-dead"`.
> Like this:
> `setPropertyFromClass('GameOverSubstate', 'characterName', 'welp-he-dead');`

What if I’m not using the Source Code and the regular game

**Comment by Stickmation1234** [comment]
> just modify the first line. the last parameter is the character's death animation you wanna use.
> If the death animation was on a character named `"welp-he-dead"`
> Then replace the third value with `"welp-he-dead"`.
> Like this:
> `setPropertyFromClass('GameOverSubstate', 'characterName', 'welp-he-dead');`

Oh wait I’m stupid sorry and thanks
