### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by nirocode** [ShadowMario/FNF-PsychEngine#13283]
### Describe your problem here.

heres an error: "C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/_internal/IBitmapDrawableType.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/BitmapDataChannel.hx:24: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/events/EventPhase.hx:8: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/BlendMode.hx:15: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/CapsStyle.hx:15: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/GradientType.hx:12: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/InterpolationMethod.hx:13: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/JointStyle.hx:14: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/LineScaleMode.hx:10: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/SpreadMethod.hx:14: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/TriangleCulling.hx:27: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/text/AntiAliasType.hx:10: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/ui/MouseCursor.hx:12: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/net/ObjectEncoding.hx:45: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/text/GridFitType.hx:10: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/text/TextFieldAutoSize.hx:10: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/text/TextFieldType.hx:10: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/Context3DMipFilter.hx:12: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/Context3DTextureFilter.hx:12: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/Context3DWrapMode.hx:12: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/_internal/ATFGPUFormat.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/Context3DBlendFactor.hx:49: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/Context3DCompareMode.hx:13: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/Context3DStencilAction.hx:14: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/Context3DTriangleFace.hx:13: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/_internal/AGALConverter.hx:821: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/utils/Endian.hx:22: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/ShaderParameterType.hx:12: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/Context3DProfile.hx:12: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/Context3DRenderMode.hx:12: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/ui/KeyLocation.hx:10: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/text/TextFormatAlign.hx:10: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/Context3DClearMask.hx:7: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/StageDisplayState.hx:10: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/FlxBasic.hx:201: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/graphics/frames/FlxFrame.hx:680: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/graphics/frames/FlxFrame.hx:688: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/tweens/FlxTween.hx:24: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/FlxInput.hx:84: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/tile/FlxBaseTilemap.hx:1382: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/util/FlxDirectionFlags.hx:8: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/util/FlxDirection.hx:7: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/keyboard/FlxKey.hx:8: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/utils/AssetType.hx:7: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/net/SharedObjectFlushStatus.hx:10: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/ui/MultitouchInputMode.hx:12: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/mouse/FlxMouseButton.hx:85: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/gamepad/FlxGamepadInputID.hx:12: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/StageAlign.hx:10: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/StageScaleMode.hx:10: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/discord_rpc/git/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/_internal/GraphicsDataType.hx:3: characters 13-19 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/net/URLLoaderDataFormat.hx:10: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/net/URLRequestMethod.hx:9: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/PixelSnapping.hx:11: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/ShaderPrecision.hx:29: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/ShaderParameterType.hx:12: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/StageQuality.hx:10: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/utils/CompressionAlgorithm.hx:12: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/text/_internal/TextLayout.hx:289: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/text/_internal/TextLayout.hx:354: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display/GraphicsPathWinding.hx:20: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/Context3DTextureFormat.hx:12: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/Context3DBufferUsage.hx:12: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/Context3DProgramFormat.hx:11: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/Context3DProgramType.hx:13: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/Context3DVertexBufferFormat.hx:13: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/geom/Orientation3D.hx:13: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/display3D/_internal/ATFFormat.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/text/FontStyle.hx:9: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/openfl/9,2,0/src/openfl/text/FontType.hx:11: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/text/FlxText.hx:1153: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/actions/FlxActionInputAnalog.hx:17: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/input/actions/FlxActionInputAnalog.hx:393: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
source/TitleState.hx:31: characters 8-29 : Type not found : flixel.sound.FlxSound
export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
source/Alphabet.hx:10: characters 8-29 : Type not found : flixel.sound.FlxSound
export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
source/editors/ChartingState.hx:2759: characters 2-9 : Expected }"
halp

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by MemeHovy** [comment]
use haxe 4.2.5

**Comment by nirocode** [comment]
> use haxe 4.2.5

i do

**Comment by nirocode** [comment]
> use haxe 4.2.5

source/TitleState.hx:31: characters 8-29 : Type not found : flixel.sound.FlxSound
source/Alphabet.hx:10: characters 8-29 : Type not found : flixel.sound.FlxSound
source/editors/ChartingState.hx:2759: characters 2-9 : Expected }

now what?

**Comment by MemeHovy** [comment]
update flixel

**Comment by nirocode** [comment]
> update flixel

i did, atleast, i did to 4.11.0, cuz that what i was told, and yes i did update flixel addons to 2.11.0 aswell

**Comment by MemeHovy** [comment]
well now you have to update it

**Comment by nirocode** [comment]
> well now you have to update it

to the latest ver?

**Comment by MemeHovy** [comment]
yes

**Comment by MemeHovy** [comment]
I'm saying now if you don't update it, it won't compile

**Comment by nirocode** [comment]
aight amma go do that and al tell ya if it works

> I'm saying now if you don't update it, it won't compile

**Comment by nirocode** [comment]
> I'm saying now if you don't update it, it won't compile

ok ok, some errors went away, now only got this (source/editors/ChartingState.hx:2759: characters 2-9 : Expected }

**Comment by MemeHovy** [comment]
you're missing a } in the code you modified, also download the haxe extension jesus christ

**Comment by nirocode** [comment]
> you're missing a } in the code you modified, also download the haxe extension jesus christ 🤦🏻‍♂️

where? where is the } supposed to be?
also i wasent told about no extention in the instructions so not my fault

**Comment by nirocode** [comment]
> you're missing a } in the code you modified, also download the haxe extension jesus christ 🤦🏻‍♂️

wait is haxe extention just, haxe? like just regular old haxe?

**Comment by MemeHovy** [comment]
it's just so you can view haxe files not as text files

**Comment by nirocode** [comment]
> it's just so you can view haxe files not as text files

i didnt know but that, i just know about haxe, as in the thing u download, from the website, didnt know bout no extention

**Comment by nirocode** [comment]
also i still dont know where to put the }

**Comment by MemeHovy** [comment]
there's pretty of vsc extensions for haxe

**Comment by nirocode** [comment]
> there's plenty of vsc extensions for haxe

mkay but now where is the } supposed to be?

**Comment by MemeHovy** [comment]
> > there's plenty of vsc extensions for haxe
> 
> mkay but now where is the } supposed to be?

look at the code you modified

**Comment by nirocode** [comment]
> > > there's plenty of vsc extensions for haxe
> > 
> > 
> > mkay but now where is the } supposed to be?
> 
> look at the code you modified, try looking at the colors of the {} for a hint

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/97875933/64f2817b-e6e2-4535-b6b7-a7ab88944dbf)

it says "2-9" but the cursor is at 9 rn so what am i gonna do?
