### ISSUE TITLE
haxelib run hmm install not working

### ISSUE THREAD

**Issue by Tikoulla** [ShadowMario/FNF-PsychEngine#13290]
### Describe your problem here.

i was trying to compile the engine, and when i put "haxelib run hmm install" it said
```
Validation error: hmm.json not found in current working directory
Use "hmm help" to see usage
```

and i don't know what to do

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
`cd` to the psych engine repo folder

**Comment by tnkarot1up** [comment]
Hello! Sorry for the inconvenience but where do I put the `cd`? I also have problems compiling
