### ISSUE TITLE
Question about booms/Add Camera Zooms

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#13297]
### What is your question?

Is there any way that I can make the booms/Add Camera Zooms faster using Lua?

**Comment by GatoMagoXD** [comment]
Can use a **custom Zoom**, can find in GameBanana

**Comment by WilliamGaming12** [comment]
No i mean THIS, the beats thingy, not a regular camera zoom
https://github.com/ShadowMario/FNF-PsychEngine/assets/102251392/374c21b9-edf5-44f0-9491-c20ae5c6e283
