### ISSUE TITLE
can you re-enable pausing when not focused in song?

### ISSUE THREAD

**Issue by squibbled** [ShadowMario/FNF-PsychEngine#13299]
### What is your question?

hi!

im trying to optimize a little project im using psych for, and i was wondering... can you re-enable pausing when clicking off the window through lua mid song? (runhaxecode is fine)

thank you :)

**Comment by MemeHovy** [comment]
not possible with Lua since it doesn't have any callbacks for when the window is unfocused, and idk about HScript

**Comment by MemeHovy** [comment]
actually wait, on 0.7 there's callbacks so do `function onFocusLost()`

**Comment by squibbled** [comment]
> actually wait, on 0.7 there's callbacks so do `function onFocusLost()`

i saw this, but i couldn't seem to get it working lol

**Comment by squibbled** [comment]
so sorry lol it was something i did

i set autoPause to true in main.hx, so since i did that, the variable wouldnt change

i just removed that, and now running `setPropertyFromClass('flixel.FlxG','autoPause','true')` will now pause it mid song :)

**Comment by pac2005** [comment]
but how do you prevent it from pausing like that
