### ISSUE TITLE
Compiling Error "source/Character.hx:134: characters 7-11 : Expected }"

### ISSUE THREAD

**Issue by PumpTutorials** [ShadowMario/FNF-PsychEngine#1329]
### Describe your bug here.

On the commit where it says you forgot soft code packer atlas thing that was the update that broke it and I looked and the thing they added or fixed just broke character hx and wont let me compile.

source/Character.hx:134: characters 7-11 : Expected }

### Command Prompt/Terminal logs (if existing)

```bash
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\banana\Desktop\FNF-PsychEngine-main> lime test windows
source/Character.hx:134: characters 7-11 : Expected }
PS C:\Users\banana\Desktop\FNF-PsychEngine-main>
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by SrtHero278** [comment]
Just go to line 134 and remove the "}" but not the "{"
It worked for me.
