### ISSUE TITLE
Freeplay crash

### ISSUE THREAD

**Issue by toovie** [ShadowMario/FNF-PsychEngine#13296]
### Freeplay Crash

i was making a new character and then when i closed out of the creation menu, the game crashed

### Command Prompt/Terminal logs (if existing)

```bash
states/FreeplayState.hx (line 71)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

added songs, characters, weeks, ect. the basic stuff.

**Comment by GatoMagoXD** [comment]
Cant find the something of the week, the **name of the song or minus** check the json and find the missing file

**Comment by toovie** [comment]
i checked everything. it still doesn't work

**Comment by GatoMagoXD** [comment]
You can **remake the Week** to can **Enter to the freeplay**

**Comment by toovie** [comment]
i'll try that

**Comment by toovie** [comment]
yeah. it was a week. loaded all of them up, except didn't load at all. i deleted it, and remade it. thanks.
