### ISSUE TITLE
[6.3 SOURCE] Pure Black gets converted to 50% Transparent White.

### ISSUE THREAD

**Issue by fregnup** [ShadowMario/FNF-PsychEngine#13291]
### Describe your problem here.

Every build ive compiled after the most recent psych engine update (i assume it was 7.1h) had an error where every lua scripted object with pure black (000000) or pure white (FFFFFF) got converted to a 50% transparent white object. (Example in image, normally a pure black cinematic event).

Looks cool but is really annoying considering that black screens will now not show.
Im not sure if this has something to do with my **Haxe library** or the game itself.
_(This does not happen on non-compiled engines (a.k.a the ones on gamebanana).)_

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/81653232/a31bf177-c4ca-4ea8-921f-adc60681493b)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I removed "zoom" in the Main.hx "addChild" line 80-85

**Comment by CaptainBaldi** [comment]
install hxcpp 4.2.1
