### ISSUE TITLE
Exiting back to song after a pause menu options selection

### ISSUE THREAD

**Issue by NpcSnoom397** [ShadowMario/FNF-PsychEngine#13306]
### What is your question?

So recently I added options to my psych's pause menu. However, I have no idea how to return back to a song after exiting rather than getting kicked back to the main menu.

**Comment by MemeHovy** [comment]
switch back to playstate instead of MainMenu via `LoadingState.loadAndSwitchState(new PlayState(), true);`

**Comment by NpcSnoom397** [comment]
I feel like it would help if I knew a way to check if the PlayState script is active.

**Comment by MemeHovy** [comment]
okay holdup, are you doing this on Lua?

**Comment by NpcSnoom397** [comment]
Here's a screenshot
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/107694396/1d7c83c0-bc1c-4b6f-a365-4d1348db9804)

**Comment by MemeHovy** [comment]
download the haxe extension for vsc, but alright

**Comment by NpcSnoom397** [comment]
I really need to understand how the Playstate variable works

**Comment by MemeHovy** [comment]
> I really need to understand how the Playstate variable works

class, it's a class

**Comment by MemeHovy** [comment]
alright

**Comment by NpcSnoom397** [comment]
Then I need to understand on how to make it "true"

**Comment by MemeHovy** [comment]
`onPlayState = true;`

**Comment by NpcSnoom397** [comment]
Not sure where to put it
If I put it in PlayState's create function, it just trowh's this
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/107694396/013dece6-b6e9-4bae-ad66-cbde1f5c3677)

**Comment by NpcSnoom397** [comment]
Ok never mind I managed to fix it all myself

**Comment by NpcSnoom397** [comment]
Seems like now I need to figure out on how to set it to false again

**Comment by NpcSnoom397** [comment]
Ok that's it I did it myself fr fr.
