### ISSUE TITLE
character editor

### ISSUE THREAD

**Issue by blackimpostor14** [ShadowMario/FNF-PsychEngine#13305]
### Describe your bug here.

so when i go to use ghost animation the one that is all the way down when i try to ghost it the game just crashes 😢 😢 😢  and im using the newest version idk why

### Command Prompt/Terminal logs (if existing)

```bash
😢
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i didnt code anything

**Comment by MemeHovy** [comment]
show the logs

**Comment by JordiiPop** [comment]
i think this only happens when you add new animations
so the solution is to add the new animations, save the character, and then re-enter the character editor and resume
