### ISSUE TITLE
Engine crashing when Story Mode and Freeplay opened

### ISSUE THREAD

**Issue by nlakos19** [ShadowMario/FNF-PsychEngine#13302]
### Describe your bug here.

The error shows up as I open Freeplay instantly, but **not in Story Mode**.
In Story Mode, I first have to **scroll to the custom week** for it to crash.

@ShadowMario said somewhere I should download some Haxe file or smth. Not sure if it's related to this problem.

### Command Prompt/Terminal logs (if existing)

```bash
states/StoryMenuState.hx (line 441)
states/StoryMenuState.hx (line 429)
states/StoryMenuState.hx (line 203)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added some images, custom week n' character, and made a custom menu character. That's it

**Comment by frantastic24** [comment]
what does your week file look like

**Comment by nlakos19** [comment]
[weekk.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/12647864/weekk.txt)

**Comment by frantastic24** [comment]
okay, this isn't a bug
the file is missing a brace `{` right at the very beginning, breaking it
![imagen](https://github.com/ShadowMario/FNF-PsychEngine/assets/95725102/969b1565-ecae-475e-900d-e4185b5970b3)
