### ISSUE TITLE
Black Squares appearing in HTML5 Ports

### ISSUE THREAD

**Issue by SnesLover26** [ShadowMario/FNF-PsychEngine#13303]
### Describe your bug here.

So I've been playing HTML5 ports of mods and the original HTML5 port of fnf, and a lot of the characters and scenery turns into black squares, as seen in the image provided. Some of the mods are using Psych Engine, some using Kade engine, and this glitch also appears in the Original FNF HTML5 newgrounds port. I'm playing on Chromebook, and I thought at first it was my schools wifi (I have an un-managed Chromebook) so I went home and it did the same exact thing. is this due to a chrome update or other?
![Screenshot 2023-09-17 9 43 43 PM](https://github.com/ShadowMario/FNF-PsychEngine/assets/129231024/f1c7cb1f-9c33-453a-b7a6-ea64b99e6569)
![Screenshot 2023-09-17 9 43 37 PM](https://github.com/ShadowMario/FNF-PsychEngine/assets/129231024/fc906901-7812-4025-91f9-ccf2aee10c04)
![Screenshot 2023-09-17 9 43 15 PM](https://github.com/ShadowMario/FNF-PsychEngine/assets/129231024/a32d74bd-290e-4396-aa25-0f93b25bf4a7)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

I'm playing on the sites: Snokido.com, KBHGames.com, and FridayNightFunkin.net

**Comment by frantastic24** [comment]
Not a bug
This is caused by the image being too large for the platform to render

**Comment by SnesLover26** [comment]
This wasn't happening before, a few months back. Everything was fine, and suddenly the same exact mods I was playing that were fine started showing this

**Comment by CaptainBaldi** [comment]
issue on your device, or the limitations of the platform

**Comment by SnesLover26** [comment]
I was using the same device as before. it just happened one day, with no update on my device in between. I've seen some other people experiencing this on HTML as well, but none with actual answers

**Comment by Cyachao** [comment]
that's a sign of running out of memory - issue of your device
perhaps gpu caching also has to do something with it?

**Comment by SnesLover26** [comment]
No Idea. I always played on my Chromebook and this never happened before. I thought maybe it's just the sites but then I made some github pages with mods on them, and they showed the same problem.

**Comment by ShadowMario** [comment]
HTML is not very supported anymore

**Comment by SnesLover26** [comment]
Found out the reason: went on my other chromebook running v.96, and the mods that didn't work ran fine (besides the chromebook sucking balls). Newer chrome updates, specifically around 113 to 115, changed the way that memory was handled (again) and older chromebooks (like my 100e gen 2) can no longer _properly_ run mods. Newer chromebooks with much more RAM can run the games properly, like the 100e gen 3. so if you have the newest update, if your hardware sucks or you don't have enough ram, the game loads in squares.
