### ISSUE TITLE
How may I hide a week if locked, and then show it when unlocked? (Repost of #1327 with correct label)

### ISSUE THREAD

**Issue by XtraXD1** [ShadowMario/FNF-PsychEngine#1330]
### What is your question?

I added the wrong label to #1327, but it's desc. is:
"For a mod I'm creating, I need to hide some weeks and then show them on their unlock. Also, I would need to hide some Freeplay levels if their week is locked, and then show them when unlocked.
Additionally, if you could help me to do so in Freeplay, but when their week is completed instead of just unlocked, I would be glad. :)"

**Comment by Templarfreak** [comment]
it's under the "lock" tab of the Week Editor.
![image](https://user-images.githubusercontent.com/2140802/143321345-479f595f-70e3-4e53-a96f-cbfde24b605a.png)

**Comment by XtraXD1** [comment]
> it's under the "lock" tab of the Week Editor. ![image](https://user-images.githubusercontent.com/2140802/143321345-479f595f-70e3-4e53-a96f-cbfde24b605a.png)
> 
> or do you mean make it completely not-visible at all? that might not be possible right now without modifying code

I mean to make it completely non-visible until unlocking it, but do someone know how to nearly do it? I mean, what code to modify.

**Comment by XtraXD1** [comment]
Nevermind, I figured it out. :)

**Comment by ShadowMario** [comment]
> Nevermind, I figured it out. :)

"When i purposely leave the issue open after figuring it out"
![image](https://user-images.githubusercontent.com/44785097/144627498-da85919f-cec6-49f6-927c-389975a0ccde.png)
