### ISSUE TITLE
Game crashes when I restart

### ISSUE THREAD

**Issue by MarkAwesomeness** [ShadowMario/FNF-PsychEngine#13308]
### Describe your bug here.

Whenever I restart a song or try and go to the options while in the pause menu , regardless of if a modpack is loaded or not, the entire game crashes. Its fine when I full on exit the song. I am working on the most recent version of Psych as of posting this (0.7.1h)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Theres only Lua files for 0.6.X that I need to fix to work with 0.7.1h

**Comment by MemeHovy** [comment]
the lua files are causing a crash, you need to fix them up
