### ISSUE TITLE
What does extension-webm.ndll do?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#1331]
### What is your question?

There is a `extension-webm.ndll` file.What does it do?
![Snipaste_2021-11-25_02-50-16](https://user-images.githubusercontent.com/13177997/143297411-f3d126c7-9562-427e-a648-3cd2bc7edf39.png)

**Comment by Gui-iago** [comment]
makes it possible so videos can play on like, cutscenes or even the game's introduction as far as I know

**Comment by ShadowMario** [comment]
This isn't related to Psych.
