### ISSUE TITLE
Error: Failed with error: X509 - Certificate verification failed, e.g. CRL, CA or signature check failed PROBLEMM!!!!

### ISSUE THREAD

**Issue by Mlaofmd** [ShadowMario/FNF-PsychEngine#13317]
### Describe your problem here.

i installed haxe 4.2.5 on my new pc, then i will want install libs for haxe, but i getting error "Error: Failed with error: X509 - Certificate verification failed, e.g. CRL, CA or signature check failed" anyone know how to fix it?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
https://community.openfl.org/t/getting-certification-error-using-haxelib-on-mac/13489/5

**Comment by Mlaofmd** [comment]
> https://community.openfl.org/t/getting-certification-error-using-haxelib-on-mac/13489/5

THANK YOU BROOO

**Comment by MemeHovy** [comment]
> > https://community.openfl.org/t/getting-certification-error-using-haxelib-on-mac/13489/5
> 
> THANK YOU BROOO

np
