### ISSUE TITLE
Psych Engine 0.7.x Discord RPC

### ISSUE THREAD

**Issue by Syssinad** [ShadowMario/FNF-PsychEngine#13310]
### Describe your problem here.

How do I change the icon of the Discord RPC?
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/76631184/ec37f528-1ed3-4a2c-8c31-0a1803fbf149)
I know how to change the large icon, but how do I change the small icon (the one that is showing GF in the image)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
go to https://discord.com/developers/applications and make a new application, and copy the id and replace it in Discord.hx

**Comment by Syssinad** [comment]
> go to https://discord.com/developers/applications and make a new application, and copy the id and replace it in Discord.hx

Sorry I should have specified, I mean in my own mod as an RPC
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/76631184/6952a21b-a957-45a3-91bd-301181391de1)

**Comment by Syssinad** [comment]
Nevermind, I managed to figure it out myself!
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/76631184/05c4b71a-43f8-457f-b77f-e32e2e4f6cb5)

**Comment by Syssinad** [comment]
Wanted to reopen this because I realised that this didn't work

**Comment by ShadowMario** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/54d81365-18e3-422f-abef-cdae9183ceec)
name it "itsumi" and it should work
