### ISSUE TITLE
Error to compile fnf

### ISSUE THREAD

**Issue by Xanter2002** [ShadowMario/FNF-PsychEngine#13316]
### Describe your problem here.

I tried to compile the FNF-Psych Engine files but I get:
**_FNFPsychEngine/.haxelib/SScript/5,2,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support._**

and then nothing happens.
I have all the dependencies and I followed the instructions to be able to program it but it doesn't work for me.
What can I do to make it work?
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/145635285/d98bc1a5-c68c-4d68-9798-c1a2c09307c4)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MemeHovy** [comment]
you can’t, wait until #13304 is merged cuz SScript is gone

**Comment by Xanter2002** [comment]
oh ok
thank you
I thought I had done something wrong and that I was unlucky.

**Comment by PixelBird0** [comment]
> you can’t, wait until #13304 is merged cuz SScript is gone

so can you literally not make anything until its merged?

**Comment by MemeHovy** [comment]
it's back, use BrewScript

**Comment by LaxModsStuff** [comment]
> it's back, use BrewScript

how do i install it? also, compiling will try to detect sscript so im not sure what else i need to do

**Comment by MemeHovy** [comment]
`haxelib install Brewscript` and use the experimental branch

**Comment by Jemkov** [comment]
Dont understand what you mean @MemeHovy 
I've installed Brewscript using your command and the git version 
(haxelib git hscript-improved https://github.com/TheLeerName/hscript-improved)
But it still say that SScript is not available

**Comment by MemeHovy** [comment]
> Dont understand what you mean @MemeHovy I've installed Brewscript using your command and the git version (haxelib git hscript-improved https://github.com/TheLeerName/hscript-improved) But it still say that SScript is not available And how to use the experimental branch

https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental and install SScript 4.1.0

**Comment by Jemkov** [comment]
Still don't work for me, maybe i misunderstood

**Comment by MemeHovy** [comment]
> Still don't work for me, maybe i misunderstood
> It still search for SScript

`haxelib install SScript 4.1.0`

**Comment by Jemkov** [comment]
Yes, that's what i did but sill nothing

**Comment by MemeHovy** [comment]
> Yes, that's what i did but sill nothing

show me

**Comment by s-h-i-f-t-y-z** [comment]
1 month and blud hasnt shown

**Comment by Baldi9262** [comment]
its still not working

**Comment by JimMeta-belike** [comment]
Nothing is working for me cuh
