### ISSUE TITLE
I added a new line to LoadingState.hx and I get this error:

### ISSUE THREAD

**Issue by Fellegend** [ShadowMario/FNF-PsychEngine#13322]
### Describe your bug here.

![Captura de Tela (171)](https://github.com/ShadowMario/FNF-PsychEngine/assets/142691547/17ec9163-88b7-456e-816b-a626831fabe5)

I just added FlxTween.tween(LoadingTextGoBrr, {y: LoadingTextGoBrr.y + 50}, 0.6, {ease: FlxEase.quadInOut, type: PINGPONG})
to LoadingState.hx and now there is an error and... there is a ; on 57th line

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added "FlxTween.tween(LoadingTextGoBrr, {y: LoadingTextGoBrr.y + 50}, 0.6, {ease: FlxEase.quadInOut, type: PINGPONG})" to LoadingState.hx

**Comment by MemeHovy** [comment]
you're missing an ; in that line of code, and also just as a recommendation, download the haxe language extension for vsc

**Comment by Fellegend** [comment]
> you're missing an ; in that line of code, and also just as a recommendation, download the haxe language extension for vsc

It's missing in what part?

**Comment by MemeHovy** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/7f1aa703-1e62-4bc7-a9ab-357c398de43d)

this, is it seriously not that obvious?

**Comment by Fellegend** [comment]
> ![image](https://user-images.githubusercontent.com/124418090/270085064-7f1aa703-1e62-4bc7-a9ab-357c398de43d.png)
> 
> this, is it seriously not that obvious?

Oh. I didn't think THAT was the error. I'm just a stupid begginer guy. I don't understand almost nothing about coding

**Comment by Fellegend** [comment]
> ![imagem](https://user-images.githubusercontent.com/124418090/270085064-7f1aa703-1e62-4bc7-a9ab-357c398de43d.png)
> 
> isso, sério, não é tão óbvio?

It was saying 57 so I thought the error was in that line

**Comment by Fellegend** [comment]
> ![imagem](https://user-images.githubusercontent.com/124418090/270085064-7f1aa703-1e62-4bc7-a9ab-357c398de43d.png)
> 
> isso, sério, não é tão óbvio?

thank you anyways :)

**Comment by MemeHovy** [comment]
np
