### ISSUE TITLE
How can I disable song editor?

### ISSUE THREAD

**Issue by Fellegend** [ShadowMario/FNF-PsychEngine#13324]
### What is your question?

In some mods like Vs Impostor V4 and Vs Nonsense V2 you can't edit the songs. Like, if you press 7 key in FNF you can open the song editor but in these mods you can't. How can I do that?

**Comment by TheLeerName** [comment]
in source?

**Comment by Fellegend** [comment]
> in source?

what file?

**Comment by DisIsNOt** [comment]
Bro just find the code that leads to the charting state and comment out it idk

**Comment by Fellegend** [comment]
> Bro just find the code that leads to the charting state and comment out it idk

thanx
