### ISSUE TITLE
Intro Text help needed (7.1h) No not the one in data

### ISSUE THREAD

**Issue by OutUnderdub** [ShadowMario/FNF-PsychEngine#13321]
### What is your question?

Sorry to keep bugging you guys
How do i edit the intro text that says stuff like
Psych Engine by, or, Friday night funkin'
ive tried searchin on youtube but not many people have done videos on 7.1h

**Comment by MemeHovy** [comment]
put it in your data folder in mods with the name introText.txt and it should override it, or you can edit the file in the data folder

**Comment by OutUnderdub** [comment]
Just to make sure where thinking of the same thing
are you talking about the lundum dare--extrordanare?
cuz thats not what im talking about

**Comment by OutUnderdub** [comment]
nvm figured it out
