### ISSUE TITLE
Error starting

### ISSUE THREAD

**Issue by Wantu34** [ShadowMario/FNF-PsychEngine#13320]
### Describe your problem here.

When i start the game pops up this:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/145811608/57809672-d742-4e90-b1a4-686f24129474)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes Achievements MenuState and Alphabet

**Comment by MemeHovy** [comment]
show the changes you made in MainMenuState

**Comment by Wantu34** [comment]
From line 111:
			var offset:Float = 108 - (Math.max(optionShit.length, 4) - 4) * 80;
			var menuItem:FlxSprite = new FlxSprite(0, (i * 140)  + offset);
			menuItem.scale.x = scale;
			menuItem.scale.y = scale;
			menuItem.frames = Paths.getSparrowAtlas('mainmenu/menu_' + optionShit[i]);
			menuItem.animation.addByPrefix('idle', optionShit[i] + " basic", 24);
			menuItem.animation.addByPrefix('selected', optionShit[i] + " white", 24);
			menuItem.animation.play('idle');
			menuItem.ID = i;
			// menuItem.screenCenter(X);
			menuItem.x += 100;
			menuItems.add(menuItem);
			var scr:Float = (optionShit.length - 4) * 0.135;
			if(optionShit.length < 6) scr = 0;
			menuItem.scrollFactor.set(0, scr);
			menuItem.antialiasing = ClientPrefs.globalAntialiasing;
			//menuItem.setGraphicSize(Std.int(menuItem.width * 0.58));
			menuItem.updateHitbox();

And delete:

 	#if ACHIEVEMENTS_ALLOWED
	// Unlocks "Freaky on a Friday Night" achievement
	function giveAchievement() {
		add(new AchievementObject('friday_night_play', camAchievement));
		FlxG.sound.play(Paths.sound('confirmMenu'), 0.7);
		trace('Giving achievement "friday_night_play"');
	}
	#end

**Comment by MemeHovy** [comment]
I meant line 152

**Comment by Wantu34** [comment]
that?

if(!Achievements.isAchievementUnlocked(Achievements.achievementsStuff[achieveID][2])) { //It's a friday night. WEEEEEEEEEEEEEEEEEE

**Comment by MemeHovy** [comment]
your achievement is probably null

**Comment by Wantu34** [comment]
how do I make it not null

**Comment by MemeHovy** [comment]
show me what you changed in the achivements

**Comment by Wantu34** [comment]
I delete almost all achievents

class Achievements {
	public static var achievementsStuff:Array<Dynamic> = [ //Name, Description, Achievement save tag, Hidden achievement
		["Freaky on a Friday Night",	"Play on a Friday... Night.",						'friday_night_play',	 true],
		["Roadkill Enthusiast",			"Watch the Henchmen die over 100 times.",			'roadkill_enthusiast',	false]
	];

**Comment by MemeHovy** [comment]
that's the reason why, the game's trying to access an non existent achivement

**Comment by Wantu34** [comment]
So do I put all the achievements back?

**Comment by MemeHovy** [comment]
no, just delete the one in MainMenuState

**Comment by Wantu34** [comment]
Which?

**Comment by MemeHovy** [comment]
`if(!Achievements.isAchievementUnlocked(Achievements.achievementsStuff[achieveID][2]))` this

**Comment by Wantu34** [comment]
It works thx

**Comment by MemeHovy** [comment]
> It works thx

np
