### ISSUE TITLE
ERROR: There is no asset library with an ID of "week2"

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#1332]
### What is your question?

There is an error below: 
![Snipaste_2021-11-25_03-00-34](https://user-images.githubusercontent.com/13177997/143298763-78a27045-9cd6-45cf-81e9-6b7645db4b7c.png)

What should I do?

**Comment by HiroOfc** [comment]
well, this happens if u delete the week folder and don't clear the folder's name at Project.xml. Are u sure if you did it?

**Comment by ShadowMario** [comment]
You forgot to delete week2 from Project.xml
