### ISSUE TITLE
lime not works

### ISSUE THREAD

**Issue by Mlaofmd** [ShadowMario/FNF-PsychEngine#13329]
### Describe your problem here.

i have problem with building, after installed haxe 4.2.5 and libs, but i cant build because lime not found. please help
my libs
actuate: [1.9.0]
discord_rpc: [git]
flixel-addons: [2.11.0]
flixel-screenshot-plugin: [git]
flixel-tools: [1.5.1]
flixel-ui: [2.5.0]
flixel: 5.2.2 [5.3.1]
flxanimate: [3.0.4]
haxelib: [4.1.0]
hmm: [3.1.0]
hscript-ex: [git]
hscript: [2.5.0]
hxCodec: [2.5.1]
hxcpp-debug-server: [1.2.4]
hxcpp: [4.3.2]
hxjsonast: [1.1.0]
lime: [8.0.2]
linc_luajit: [git]
openfl: [9.2.2]
thx.core: [0.44.0]
tjson: [1.4.0]
utest: [1.13.2]

![cmd_Z58VloaeQ2](https://github.com/ShadowMario/FNF-PsychEngine/assets/52864321/25be3a4c-948c-48e6-afbc-78773a66e491)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Karim-Akra** [comment]
Run `haxelib run lime setup` to make the lime command available as a command alias or use `haxelib run lime test windows`
