### ISSUE TITLE
The Custom Event Description Skips A Line Every New Line In The Event Description .txt File 

### ISSUE THREAD

**Issue by Jerry-The-SMG4-Fan** [ShadowMario/FNF-PsychEngine#13336]
### Describe your bug here.

So I want my custom event descriptions to be something like this.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/75190816/e6d96cbd-64e5-4e27-adf5-c5b47337d6b1)
(Compact descriptions with no line skips.)

This is what I typed in my event description .txt file.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/75190816/28706d2a-b7e8-46ee-856a-c9c4b4080c11)
But it came out like this...
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/75190816/cd6ab9ec-571b-4d04-8790-46e2caa9dfe6)

Using \n is useless as well since I did this:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/75190816/79996a67-6b90-4ada-b737-a94ebf6f4358)
But it came out like this:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/75190816/6b867fb9-dd87-4ede-bb14-2dfbd2725923)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, this is all in Lua.

**Comment by MemeHovy** [comment]
it's obviously gonna come out as what was in the text file, \n doesn't work for some reason so you have to do it manually

**Comment by BernardoGP4504** [comment]
It happens because those get defined in the source code, which in there `/n` is used

**Comment by MemeHovy** [comment]
> It happens because those get defined in the source code, which in there `\n` is used

it doesn't use .split(\n) aswell

**Comment by BernardoGP4504** [comment]
> > It happens because those get defined in the source code, which in there `\n` is used
> 
> it doesn't use .split(\n) aswell

As such @Jerry-The-SMG4-Fan , the only way to fix that would be either hard coding the description in the source code or making your explanation of the event smaller (so no need to use `\n` or `\r\n`

**Comment by Jerry-The-SMG4-Fan** [comment]
> > > It happens because those get defined in the source code, which in there `\n` is used
> > 
> > 
> > it doesn't use .split(\n) aswell
> 
> As such @Jerry-The-SMG4-Fan , the only way to fix that would be either hard coding the description in the source code or making your explanation of the event smaller (so no need to use `\n` or `\r\n`)
- @BernardoGP4504 

Aw...that sucks, but thanks for your response.
