### ISSUE TITLE
SScript is finished.

### ISSUE THREAD

**Issue by SScript-Guy** [ShadowMario/FNF-PsychEngine#13333]
### Describe your bug here.

![nope](https://github.com/ShadowMario/FNF-PsychEngine/assets/33851349/f76f8454-8ff3-498c-beb7-d74036b21db4)
Unfortunately, SScript seems to have shut it's doors down. Can't compile anything now.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Cyachao** [comment]
for now use the experimental branch
it has brewscript instead

**Comment by MemeHovy** [comment]
use brewscript
