### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by Mlaofmd** [ShadowMario/FNF-PsychEngine#13332]
### Describe your problem here.

i getting error 
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

but i have installed msvc v142 and windows sdk 10 17763

please help

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/52864321/0a26a0d5-30b9-45b7-9114-90a67a9c3879)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
install visual studio

**Comment by Mlaofmd** [comment]
> install visual studio

I HAVE INSTALLED

**Comment by MemeHovy** [comment]
![A1A5705C-E7C2-480F-BBD4-A791887B2C61](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/6aebac12-31d6-4292-93a6-66378d014ec7)

you need visual studio 2019 for these components since they’re not present in visual studio 2022

**Comment by TrulyS1r0** [comment]
Visual Studio 2019 is nowhere to be found for me. (Microsoft is donkey A and i cant download the files) so does anyone have a Visual Studio 2019 Installer?
