### ISSUE TITLE
how can i change the rating name using source on 0.7.1h?

### ISSUE THREAD

**Issue by Flubbedsoda6010** [ShadowMario/FNF-PsychEngine#13330]
### Describe your problem here.

i was trying to change the rating name and `

	public static var ratingStuff:Array<Dynamic> = [
		['You can get an achievement', 0.2], 
		['REALLY TERRIBLE', 0.4], 
		['Its not that hard', 0.5],
		['Really dude?', 0.6], 
		['Need more training', 0.7]
		['Keep hitting those sicks', 0.8], 
		['Pretty well', 0.9], 
		['SUCH A VETERAN', 0.96]
		['Doing AMAZING', 1], 
		['INCREDIBLE', 1] 
	];
but it didnt work 
and yes im using 0.7.1h

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i edited Playstate.hx and changed the rating names

**Comment by MemeHovy** [comment]
missing , on `['SUCH A VETERAN', 0.96]`

**Comment by Flubbedsoda6010** [comment]
I fixed that but didnt work

**Comment by MemeHovy** [comment]
wdym

**Comment by Flubbedsoda6010** [comment]
`
	public static var ratingStuff:Array<Dynamic> = [
		['You can get an achivement', 0.2], 
		['REALLY TERRIBLE', 0.4], 
		['Its not that hard', 0.5],
		['Really dude?', 0.6], 
		['Need more training', 0.7],
		['Keep hitting those sicks', 0.8], 
		['Pretty well', 0.9], 
		['SUCH A VETERAN', 0.96],
		['Doing AMAZING', 1], 
		['INCREDIBLE', 1] 
	];`

**Comment by MemeHovy** [comment]
did you recompile?

**Comment by Flubbedsoda6010** [comment]
thats where im having issue now

**Comment by MemeHovy** [comment]
show me
