### ISSUE TITLE
freeplay crash

### ISSUE THREAD

**Issue by levi-the-1** [ShadowMario/FNF-PsychEngine#13337]
### Describe your bug here.

every time i try to open the freeplay menu it always crashes! how do i fix this?

### Command Prompt/Terminal logs (if existing)

```bash
FreeplayState.hx (line 74)
flixel/Flx Game.hx (line 637)
flixel/Flx Game.hx (line 724)
flixel/Flx Game.hx (line 677)
flixel/Fix Game.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheLeerName** [comment]
week file with corrupted `songs` field

**Comment by levi-the-1** [comment]
> week file with corrupted `songs` field

thank you
