### ISSUE TITLE
SScript closed down?

### ISSUE THREAD

**Issue by TerminallyAwesome** [ShadowMario/FNF-PsychEngine#13335]
### Describe your problem here.

The source code isn't compiling, and it says "SScript is not available, thanks to everyone for their support."

If SScript is down, how am I supposed to compile the code?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by richTrash21** [comment]
just looked up to see what happened and there is no code now (in ALL versions). have NO FUCKING IDEA what is happening now

btw, i have 5.1.0, can drop you if you need

**Comment by TheLeerName** [comment]
use experimental branch bro

**Comment by SScript-Guy** [comment]
Experimenting always kills in the long run, my friend. https://github.com/SScript-Guy/SScript-new/

**Comment by crowplexus** [comment]
`git switch experimental`
`haxelib install BrewScript`

**Comment by SScript-Guy** [comment]
> `git switch experimental` `haxelib install BrewScript` `git pull` `lime test windows`

Majority opinion isn't always the correct opinion.

**Comment by crowplexus** [comment]
> Majority opinion isn't always the correct opinion.

said statement also applies to you

**Comment by Rudyrue** [comment]
please

FUCK off

learn basic respect

> Experimenting always kills in the long run, my friend. https://github.com/SScript-Guy/SScript-new/

**Comment by SScript-Guy** [comment]
blah blah blah whatever

**Comment by SScript-Guy** [comment]
I'm giving it back to the hands of the PEOPLE

**Comment by crowplexus** [comment]
and so are we, soon, friend.

**Comment by SScript-Guy** [comment]
> > Majority opinion isn't always the correct opinion.
> 
> said statement also applies to you

I'm not the one charging the light brigade with his ragtag band of newts. I'm all by my lonesome.

**Comment by MemeHovy** [comment]
just use brewscript, it's sscript but better

**Comment by MemeHovy** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/871c1b4f-3abd-4e05-9682-dd95d3be10a6)
oh hell nah, I'mma report your ass

**Comment by Rudyrue** [comment]
i've already tried

github reporting is ass because it just brings you to a dead end

**Comment by MemeHovy** [comment]
> i've already tried
> 
> github reporting is ass because it just brings you to a dead end

it's worked in my favor before

**Comment by Rudyrue** [comment]
ig

**Comment by TerminallyAwesome** [comment]
dude i just asked a question, no need to get violent

**Comment by Rudyrue** [comment]
yea but the kid's just trying to get cloutof someone's stress

not your fault sry that you got caught in the crossfire

**Comment by Rudyrue** [comment]
sscript's kinda been reuploaded by tahir anyways so the kid's dreams of clout is basically gone

**Comment by TerminallyAwesome** [comment]
> just looked up to see what happened and there is no code now (in ALL versions). have NO FUCKING IDEA what is happening now
> 
> btw, i have 5.1.0, can drop you if you need

yeah that'd be great but how would i install?

**Comment by Rudyrue** [comment]
you can just reinstall sscript as normal

`haxelib install SScript`

**Comment by TerminallyAwesome** [comment]
now im getting this

Type not found : SCall

**Comment by Rudyrue** [comment]
that's

odd

**Comment by TerminallyAwesome** [comment]
i know, what do i do?

**Comment by Rudyrue** [comment]
![](https://github.com/ShadowMario/FNF-PsychEngine/assets/73214127/ca94b9f2-c721-478a-8275-ec4dfb1935d7)
yea it should be up to date

maybe it got removed in the reupload ?? idk im confused why that doesn't exist

**Comment by Rudyrue** [comment]
make sure you have [this](https://github.com/ShadowMario/FNF-PsychEngine/pull/13338) in your build

**Comment by TerminallyAwesome** [comment]
what about that?

**Comment by TerminallyAwesome** [comment]
how does it work?
how do i use it?

**Comment by Rudyrue** [comment]
just put it in your code ?

shouldn't be that hard to integrate

**Comment by TerminallyAwesome** [comment]
lets say i know nothing about how to do that, what are you trying tell me

**Comment by TerminallyAwesome** [comment]
i put it in but it's still giving me the same error

**Comment by TerminallyAwesome** [comment]
source/psychlua/HScript.hx:168: characters 89-94 : Type not found : SCall

full error for anyone to help

**Comment by scloiD** [comment]
sscripts old versions are modified, its gone

**Comment by MemeHovy** [comment]
> sscripts old versions are modified, its gone

it’s back up now

**Comment by MemeHovy** [comment]
and @TerminallyAwesome replace SCall with TeaCall

**Comment by TerminallyAwesome** [comment]
@MemeHovy how would i do that?

**Comment by MemeHovy** [comment]
> @MemeHovy how would i do that?

by going into HScript.hx and changing it from there

**Comment by TerminallyAwesome** [comment]
I cant find anythind that says SCall

**Comment by MemeHovy** [comment]
Ctrl + f to search

**Comment by TerminallyAwesome** [comment]
got this

source/psychlua/HScript.hx:291: characters 9-16 : tea.SScript has no field destroy
source/psychlua/HScript.hx:286: characters 27-34 : Field destroy is declared 'override' but doesn't override any field
source/states/PlayState.hx:3161: characters 17-34 : psychlua.HScript has no field parsingExceptions (Suggestion: parsingException)
source/states/PlayState.hx:3161: characters 56-73 : psychlua.HScript has no field parsingExceptions (Suggestion: parsingException)
source/states/PlayState.hx:3164: characters 25-42 : psychlua.HScript has no field parsingExceptions (Suggestion: parsingException)
source/states/PlayState.hx:3164: characters 15-42 : You can't iterate on a Dynamic value, please specify Iterator or Iterable

**Comment by MemeHovy** [comment]
replace destroy with kill and remove the override on it, then replace parsingExceptions with exceptions

**Comment by TerminallyAwesome** [comment]
how do i remove the override

**Comment by TerminallyAwesome** [comment]
is this the override

	#if (SScript >= "3.0.3")
	override public function kill()
	{
		origin = null;
		parentLua = null;

		super.kill();
	}
	#else
	public function kill()
	{
		active = false;
	}
	#end

**Comment by MemeHovy** [comment]
not that, the destroy function

**Comment by TerminallyAwesome** [comment]
i dont see anything other than that after i had replaced destroy with kill

**Comment by TerminallyAwesome** [comment]
what if you just copied your HScript code and i put it in so it can work

**Comment by SScript-Guy** [comment]
> > i've already tried
> > github reporting is ass because it just brings you to a dead end
> 
> it's worked in my favor before

lolololol whatever
i'm not doing this for clout
i'm not gaining anything out of this

**Comment by TerminallyAwesome** [comment]
@MemeHovy Can you send me a copy of your HScript code so I can finally fix this?

**Comment by MemeHovy** [comment]
@TerminallyAwesome use the latest experimental branch

**Comment by TerminallyAwesome** [comment]
where do i find that?

**Comment by MemeHovy** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental it shows CI is working

**Comment by TerminallyAwesome** [comment]
would the file just be called setup?

**Comment by MemeHovy** [comment]
it's in the main folder

**Comment by TerminallyAwesome** [comment]
of what?

**Comment by crowplexus** [comment]
`haxelib git SScript https://github.com/crowplexus/SScript`

**Comment by TerminallyAwesome** [comment]
> of what?

nevermind

**Comment by TerminallyAwesome** [comment]
one more issue

source/psychlua/CallbackHandler.hx:54: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua

**Comment by TerminallyAwesome** [comment]
new error @MemeHovy 

Class<llua.Lua_helper> has no field sendErrorsToLua

**Comment by MemeHovy** [comment]
`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit master`

**Comment by TerminallyAwesome** [comment]
it didnt work and i forgot the full error

source/psychlua/CallbackHandler.hx:54: characters 11-26 : Class<llua.Lua> has no field sendErrorsToLua

**Comment by MemeHovy** [comment]
you need to override the branch

**Comment by crowplexus** [comment]
> it didnt work and i forgot the full error
> 
> source/psychlua/CallbackHandler.hx:54: characters 11-26 : Class<llua.Lua> has no field sendErrorsToLua

`haxelib remote linc_lua`
`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit master`

you have to remove it first so it ensures its on the correct version

**Comment by TerminallyAwesome** [comment]
how do you override the branch?

**Comment by MemeHovy** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/7a32e45c-8c52-4bbd-a1ef-708964dfe7de)

hit y

**Comment by TerminallyAwesome** [comment]
what now?

**Comment by MemeHovy** [comment]
try compiling again

**Comment by TerminallyAwesome** [comment]
didnt work, same error

**Comment by scloiD** [comment]
try somethin

**Comment by MemeHovy** [comment]
you need to do what was shown btw, not just install it from haxelib instead of github

**Comment by TerminallyAwesome** [comment]
I just got it to work and it wasnt that. the file "CallbackHandler" had a typo and I fixed it

**Comment by TerminallyAwesome** [comment]
but thank you @MemeHovy

**Comment by MemeHovy** [comment]
> but thank you @MemeHovy

np

**Comment by Frosty-The-Glitch** [comment]
> `git switch experimental` `haxelib install BrewScript` `git pull` `lime test windows`

Okay, so, I know this is old, but, How do I execute those?

**Comment by scloiD** [comment]
open a command prompt from navigation bar

**Comment by megalives717** [comment]
please help how to fix this error
