### ISSUE TITLE
Can't Compile 7.0 Source Code

### ISSUE THREAD

**Issue by Red64JG** [ShadowMario/FNF-PsychEngine#13334]
### Describe your problem here.

I don't know what this means,
I did all the steps to try to open source code but idk what this means, it's not letting me do Lime test

![Screenshot 2023-09-23 145741](https://github.com/ShadowMario/FNF-PsychEngine/assets/100157981/b60e78ab-ea90-49b2-920a-585b3959ccf5)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
install visual studio

**Comment by Red64JG** [comment]
> install visual studio

I did, it still says that

**Comment by MemeHovy** [comment]
![8D7A359A-B990-4EC2-8002-5FBC60F36383](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/952188a0-4cd0-4e17-ad96-3c3075ea65ae)
you need these components too

**Comment by Red64JG** [comment]
> ![8D7A359A-B990-4EC2-8002-5FBC60F36383](https://user-images.githubusercontent.com/124418090/270138971-952188a0-4cd0-4e17-ad96-3c3075ea65ae.jpeg) you need these components too

yea i did those two, but for some reason its just same thing idk why

**Comment by MemeHovy** [comment]
> > ![8D7A359A-B990-4EC2-8002-5FBC60F36383](https://user-images.githubusercontent.com/124418090/270138971-952188a0-4cd0-4e17-ad96-3c3075ea65ae.jpeg) you need these components too
> 
> yea i did those two, but for some reason its just same thing idk why

make sure build tools is latest

**Comment by Red64JG** [comment]
> > > ![8D7A359A-B990-4EC2-8002-5FBC60F36383](https://user-images.githubusercontent.com/124418090/270138971-952188a0-4cd0-4e17-ad96-3c3075ea65ae.jpeg) you need these components too
> > 
> > 
> > yea i did those two, but for some reason its just same thing idk why
> 
> make sure build tools is latest

Which one for Windows SDK, there no 10.0.17763.0

![Screenshot 2023-09-23 205941](https://github.com/ShadowMario/FNF-PsychEngine/assets/100157981/8bf7b277-4005-4815-a137-48059664da2d)

**Comment by MemeHovy** [comment]
> > > > ![8D7A359A-B990-4EC2-8002-5FBC60F36383](https://user-images.githubusercontent.com/124418090/270138971-952188a0-4cd0-4e17-ad96-3c3075ea65ae.jpeg) you need these components too
> > > 
> > > 
> > > yea i did those two, but for some reason its just same thing idk why
> > 
> > 
> > make sure build tools is latest
> 
> Which one for Windows SDK, there no 10.0.17763.0
> 
> ![Screenshot 2023-09-23 205941](https://user-images.githubusercontent.com/100157981/270140623-8bf7b277-4005-4815-a137-48059664da2d.png)

if you're using visual studio 2022, it won't have the components needed unfortunately, so you have to use 2019 instead

**Comment by Red64JG** [comment]
> > > > > ![8D7A359A-B990-4EC2-8002-5FBC60F36383](https://user-images.githubusercontent.com/124418090/270138971-952188a0-4cd0-4e17-ad96-3c3075ea65ae.jpeg) you need these components too
> > > > 
> > > > 
> > > > yea i did those two, but for some reason its just same thing idk why
> > > 
> > > 
> > > make sure build tools is latest
> > 
> > 
> > Which one for Windows SDK, there no 10.0.17763.0
> > ![Screenshot 2023-09-23 205941](https://user-images.githubusercontent.com/100157981/270140623-8bf7b277-4005-4815-a137-48059664da2d.png)
> 
> if you're using visual studio 2022, it won't have the components needed unfortunately, so you have to use 2019 instead

Yay! it works, thank you very much. Sorry if this was dumb, it's my first time on source

**Comment by MemeHovy** [comment]
np
