### ISSUE TITLE
Type not found : SCall

### ISSUE THREAD

**Issue by Alltoupload** [ShadowMario/FNF-PsychEngine#13343]
### Describe your problem here.

```PS
C:\HaxeToolkit\haxe\std/sys/Http.hx:534: characters 4-9 : Uncaught exception Http Error #404
C:\HaxeToolkit\haxe\std/sys/Http.hx:67: characters 4-14 : Called from here
C:\HaxeToolkit\haxe\std/sys/Http.hx:253: characters 12-25 : Called from here
C:\HaxeToolkit\haxe\std/sys/Http.hx:70: characters 3-30 : Called from here
C:\HaxeToolkit\haxe\std/sys/Http.hx:536: characters 3-19 : Called from here
C:/HaxeToolkit/haxe/lib/SScript/4,1,0/src/tea/backend/SScriptVer.hx:29: characters 45-142 : Called from here
C:/HaxeToolkit/haxe/lib/SScript/4,1,0/src/macro/Macro.hx:44: characters 3-21 : Called from here
(unknown) : Called from here
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I tried to:
Add an achievement (Achievements.hx, PlayState.hx)
Add a new gameplay changer (GameplayChangersSubstate.hx, ClientPrefs.hx)
etc.

**Comment by MemeHovy** [comment]
update sscript with haxelib install SScript 6.1.80

**Comment by Alltoupload** [comment]
Thank you

**Comment by Alltoupload** [comment]
It's showing me this now!
`source/psychlua/HScript.hx:168: characters 89-94 : Type not found : SCall`

**Comment by Alltoupload** [comment]
Nevermind, no hscript
