### ISSUE TITLE
No HScript script API

### ISSUE THREAD

**Issue by Alltoupload** [ShadowMario/FNF-PsychEngine#13341]
### What needs to be documented?

Haxe stuff

Yes you have to

**Comment by MemeHovy** [comment]
I’ve noticed the wiki doesn’t contain runHaxeCode so yea, that needs to be documented

**Comment by CaptainBaldi** [comment]
wiki is outdated and i doubt will be updated until psych engine is finished

**Comment by Alltoupload** [comment]
> wiki is outdated and i doubt will be updated until psych engine is finished

ok

**Comment by ShadowMario** [comment]
Do i really have to? Coding in HScript is nearly identical to normal Haxe
https://api.haxeflixel.com/
