### ISSUE TITLE
JSONs not saving as JSONs?

### ISSUE THREAD

**Issue by B3eper132** [ShadowMario/FNF-PsychEngine#13345]
### Describe your bug here.

So... I don't know why this happens but whenever I make a new JSON (anything but a Chart) unless specified in the file name, it saves as a file with no file extension.
it's weird because it says it'll save as a JSON. and...
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/145614528/12fc1ca9-e754-434b-a84a-d5325dfc84b1)
Note when making changes to a JSON it doesn't do that, it's making and saving a new one that fucks it up for some reason
and it only happens in their specific paths as well? I don't understand this!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by CaptainBaldi** [comment]
it works fine for me

**Comment by B3eper132** [comment]
IDK if it's an issue on my part

**Comment by BernardoGP4504** [comment]
Do you have show file extensions on?

**Comment by Mawtr** [comment]
sometimes the file doesn't categorise itself, I have the same problem, just after the name is file, type ".json", then it'll always convert into a .json file
