### ISSUE TITLE
How do I expand camGame (make it borderless)?

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#13347]
### What is your question?

> *Doing all of this in lua, I'm on Android so I can't use the source code*

I was doing a camera follow script where when left or right were hit, the angle of the camera would also change.

https://github.com/ShadowMario/FNF-PsychEngine/assets/101405920/50b4d453-341a-4db7-91b9-59f28ace2717

But I've ran into a problem, everytime I moved the camera, there would be a black background behind it (kinda like a border) and it would be in size, the exact width and height of the original position.

So how do I expand the camera so hopefully the black borders go away? Also I've tried a widescreen script but that only fixed the issue on the X position and stretched the hud even if I modified the script

**Comment by BernardoGP4504** [comment]
Nvm I fixed it, just used a `zCameraFix` script.

**Comment by WolfyTail** [comment]
how

**Comment by BernardoGP4504** [comment]
> just used a `zCameraFix` script.

But that didn't make it borderless, it just made the borders be actual borders, not a black background when changing the angle of `FlxG.camera`
