### ISSUE TITLE
powershell error

### ISSUE THREAD

**Issue by andrew694p2** [ShadowMario/FNF-PsychEngine#13340]
### Describe your problem here.

source/psychlua/HScript.hx:168: characters 89-94 : Type not found : SCall
what do i do???

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MemeHovy** [comment]
replace SCall with TeaCall

**Comment by andrew694p2** [comment]
> replace SCall with TeaCall

how do i do that? i know nothing about coding :[

**Comment by MemeHovy** [comment]
then learn how to

**Comment by rokyremix123** [comment]
que hp mamon de mierda

**Comment by MemeHovy** [comment]
> que hp mamon de mierda

how is that related?

**Comment by JohnDoe3453** [comment]
IM GONNA FIX IT BCUZ EVERYONE IS LAAAAAAAZZZYYYYY

haxelib remove SScript

haxelib install TeaScript
