### ISSUE TITLE
How i fix dis?

### ISSUE THREAD

**Issue by KingNickOfficial** [ShadowMario/FNF-PsychEngine#13346]
### Describe your problem here.

SOO... I was trying to compile the source code for 0.7.1h, and I got an error from my terminal that says this:

 source/states/TitleState.hx:192: characters 2-17 : Expected }

But on line 192 it's this....

backgroundTitle = new FlxSprite().loadGraphic(Paths.image('titleBG'));

I was just wondering if anyone could send me in the comments the fixed code for wherever the } is supposed to go.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited the title state so it doesnt show gf, and it shows the game's logo with an animation that makes it bop up and down.

**Comment by MemeHovy** [comment]
you're missing an } in the line of code you modified

**Comment by BernardoGP4504** [comment]
Can you show an screenshot of the function this is in? Also, you might have forgotten the `var` keyword before `backgroundTitle` if it isn't already defined with `var`
