### ISSUE TITLE
ERROR HELP ME PLS

### ISSUE THREAD

**Issue by Ramazanenesisik010** [ShadowMario/FNF-PsychEngine#13344]
### Describe your problem here.

BUILDING GAME
source/psychlua/HScript.hx:168: characters 89-94 : Type not found : SCall

done.
Press any key to continue . . .

When I want to test the Psych Engine, I get an error like this. I Installed Libraries, Still It Still Gives Errors, Can You Help?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
replace SCall with TeaCall

**Comment by Ramazanenesisik010** [comment]
New Error  : 
BUILDING GAME
source/psychlua/HScript.hx:291: characters 9-16 : tea.SScript has no field destroy
source/psychlua/HScript.hx:286: characters 27-34 : Field destroy is declared 'override' but doesn't override any field
source/states/PlayState.hx:3161: characters 17-34 : psychlua.HScript has no field parsingExceptions (Suggestion: parsingException)
source/states/PlayState.hx:3161: characters 56-73 : psychlua.HScript has no field parsingExceptions (Suggestion: parsingException)
source/states/PlayState.hx:3164: characters 25-42 : psychlua.HScript has no field parsingExceptions (Suggestion: parsingException)
source/states/PlayState.hx:3164: characters 15-42 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/psychlua/HScript.hx:206: characters 15-20 : Type not found : SCall

done.
Press any key to continue . . .

**Comment by Ramazanenesisik010** [comment]
New Error : 

New Error  : 
BUILDING GAME
source/psychlua/HScript.hx:291: characters 9-16 : tea.SScript has no field destroy
source/psychlua/HScript.hx:286: characters 27-34 : Field destroy is declared 'override' but doesn't override any field
source/states/PlayState.hx:3161: characters 17-34 : psychlua.HScript has no field parsingExceptions (Suggestion: parsingException)
source/states/PlayState.hx:3161: characters 56-73 : psychlua.HScript has no field parsingExceptions (Suggestion: parsingException)
source/states/PlayState.hx:3164: characters 25-42 : psychlua.HScript has no field parsingExceptions (Suggestion: parsingException)
source/states/PlayState.hx:3164: characters 15-42 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/psychlua/HScript.hx:206: characters 15-20 : Type not found : SCall

done.
Press any key to continue . . .

**Comment by MemeHovy** [comment]
1st one, replace destroy with kill, and remove the override. 2nd, do what was suggested, replace parsingExceptions with parsingException and the last one you already know

**Comment by Ramazanenesisik010** [comment]
What did you mean by the last one?

**Comment by Ramazanenesisik010** [comment]
What did you mean by the last one?

**Comment by MemeHovy** [comment]
![C0D34786-7CD2-4A49-9189-2238028EC2C4](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/fc027aa7-1220-4352-aba5-14c2474f67c5)

.this

**Comment by Ramazanenesisik010** [comment]
I did not understand anything. What do I need to change?

**Comment by MemeHovy** [comment]
here, maybe learn how to code before you do shit like this https://haxe.org/documentation/introduction/

**Comment by Ramazanenesisik010** [comment]
thank you

**Comment by MemeHovy** [comment]
np

**Comment by Ossianator** [comment]
wtf is happening

**Comment by Ossianator** [comment]
i need help or just give me the line of code i need to type

**Comment by Dyplex** [comment]
Download and install  Notepad++go to source\psychlua\HScript.hx, open the file, press ctrl and f at the same time, click replace and Find what : SCall and Replace with :TeaCall

**Comment by Ramazanenesisik010** [comment]
> ### Sorununuzu burada açıklayın.
> Bina Oyun Kaynağı/Psychlua/Hscript.HX: 168: Karakterler 89-94: Tip Bulunmadı: Scall
> 
> Tamamlandı. Devam etmek için herhangi bir tuşa basın . . .
> 
> Psych motorunu test etmek istediğimde, böyle bir hata alıyorum. Kütüphaneler yükledim, hala hatalar veriyor, yardım edebilir misiniz?
> 
> ### Kaynaktan mı yoksa lua ile mi yapıyorsunuz?
> Kaynak
> 
> ### Yapı hedefiniz nedir?
> Windows x64
> 
> ### Bu yapıdaki herhangi bir şeyi düzenlediniz mi? Eğer öyleyse, değişikliklerinizden bahsedin veya özetleyin.
> _Cevap yok_

**Comment by SMJofficial** [comment]
how about i find you

**Comment by fnfusermood** [comment]
Not to disturb but source/psychlua/HScript.hx:195: characters 2-3 : Missing ;


PLS

**Comment by ADA-Funni** [comment]
add a semicolon at line 195 in source/psychlua/HScript.hx
