### ISSUE TITLE
i cant change stage background mid-song

### ISSUE THREAD

**Issue by LogikZero** [ShadowMario/FNF-PsychEngine#1335]
### Describe your problem here.

i have been trying for a while but i cant figure out a way to change the background midway through the song. if anyone could help me by sending me a custom event to do it or just tell me how to code it into the custom stage's .lua file then that would be great.

PS: im on downloaded build, not source build. that one doesnt work for me. doesnt let me compile so i switched to downloaded version.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i havent changed anything. its just plain game, no modifications but i added stuff in the mods folder of course.

**Comment by Templarfreak** [comment]
you have to do it by adding/removing lua sprites, using `getObjectOrder` and `setObjectOrder`, and/or playing their animations through `objectPlayAnimation`. or you might be able to get away with it by having an xml animation for the background and playing its animations but i dont know how to get the object that is the background of your stage and that would also mean that your two separate backgrounds would have to be one image

**Comment by DEV-idiotXD** [comment]
@ShadowMario ya knw wut to do

**Comment by LogikZero** [comment]
**

```
> you have to do it by adding/removing lua sprites via `makeLuaSprite` and `addLuaSprite`, using `getObjectOrder` and `setObjectOrder`, and/or playing their animations through `objectPlayAnimation`. or you might be able to get away with it by having an xml animation for the background and playing its animations but i dont know how to get the object that is the background of your stage and that would also mean that your two separate backgrounds would have to be one image.
> 
> If all you need is just two static backgrounds that you swap between at a certain point, maybe with an animation to fade the screen in and out, then just creating all your sprites at the start and then changing the object order that they render in might be all you need.
```

**

thank you so much for your response and although i appreciate it i dont actually know any lua so your comment doesnt make much sense to me... sorry but thank you anyway for your time to write this and i hope you have a good day.
