### ISSUE TITLE
softlock on loading screen when using NO_PRELOAD_ALL

### ISSUE THREAD

**Issue by aflacc** [ShadowMario/FNF-PsychEngine#13358]
### Describe your bug here.

changing PRELOAD_ALL to NO_PRELOAD_ALL in project.xml causes the game to softlock itself when a loading screen shows up

the loading screen shows up, i see the loading bar move about half way and then it stops moving and the game doesnt do anything. it doesn't crash, it doesn't freeze, theres no errors in the terminal, it just freezes. my guess is its trying to load something and struggling to do that maybe?
 i also tested it and it does happen if you mess with the code a bit to get the loading screen to show up while having PRELOAD_ALL too so it's an issue with the loading screen or any functions its running 

### Command Prompt/Terminal logs (if existing)

```bash
there are none, the game doesnt crash it just softlocks itself
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No this happens on a completely unmodified copy of the build (other than marking NO_PRELOAD_ALL instead of PRELOAD_ALL)

**Comment by MemeHovy** [comment]
which version are you using? I've never encountered this issue last time I tried it, also just a note this uses Promise which is meant for HTML5 compatibility, and this is mainly made for HTML5 which functions very differently in terms of loading assets, so there could be an issue with how it's loading assets in

**Comment by aflacc** [comment]
this happens on 0.7.1 (latest as of right now) and possibly 0.7 and the experimental (i didn't see any commits that change the loading to be different) 
if promise is meant for html5 and not desktop that might actualyl be the cause
not sure how to fix it tho

**Comment by MemeHovy** [comment]
I’ll have to learn more about how Future and Promises work since I’m not exactly sure what could be going wrong here, but I do know they’re HTML5 compatible and this loading screen code was targeted towards HTML5

**Comment by CaptainBaldi** [comment]
[This commit](https://github.com/ShadowMario/FNF-PsychEngine/commit/f4cf818dac20859fd0223206609ba91b6818831f#diff-f0fb59a13101b937614861f93c817d2aea526d301e0b3a4bac29126efaa98856) is what I'm pretty sure broke it, you should be able to re-comment the lines changed for a fix.
If anyone could find a better method for this lmk it would probably be useful.

**Comment by aflacc** [comment]
> [This commit](https://github.com/ShadowMario/FNF-PsychEngine/commit/f4cf818dac20859fd0223206609ba91b6818831f#diff-f0fb59a13101b937614861f93c817d2aea526d301e0b3a4bac29126efaa98856) is what I'm pretty sure broke it...

it worked!! i'm not going to ask how that broke it i am just going to be happy that it works and move on
thank you so much

**Comment by WolfyTail** [comment]
> > [This commit](https://github.com/ShadowMario/FNF-PsychEngine/commit/f4cf818dac20859fd0223206609ba91b6818831f#diff-f0fb59a13101b937614861f93c817d2aea526d301e0b3a4bac29126efaa98856) is what I'm pretty sure broke it...
> 
> it worked!! i'm not going to ask how that broke it i am just going to be happy that it works and move on thank you so much

Didn't work for me, what did you do?
