### ISSUE TITLE
Weeks in assets/weeks Not Getting Replaced by the Weeks in mods/weeks

### ISSUE THREAD

**Issue by Jerry-The-SMG4-Fan** [ShadowMario/FNF-PsychEngine#13354]
### Describe your bug here.

so, when u place a file that has the same name of another file in the asset folder of psych engine into the mod folder of psych engine, the game replaces the file in the asset folder with the one in the mod folder (meaning if u put freakyMenu.ogg in mods/music the game will use that .ogg sound file instead of the one in assets/music)

i like this, and the nice thing is that it does this with every asset
EXCEPT one folder

weeks

for some reason when i put my tutorial.json and week1.json files in mods/weeks, psych engine does not use these json, instead they still use the .json files in assets/weeks, idk why the weeks folder is the only exception 

ig i just…
i want a way to make it so that the weeks that i put in mods/weeks that have the exact name as the weeks in assets/weeks will be used instead of the weeks in assets/weeks being used
is that not possible in psych engine?

(this is copy pasted from a message i sent in a big fnf modding server)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't alter the source code.

**Comment by CaptainBaldi** [comment]
Works fine for me

**Comment by Jerry-The-SMG4-Fan** [comment]
> Works fine for me
- @CaptainBaldi Weird, its not working for me

this is what my week1.json file looks like, its inside my "mods/[My Mod Name Here]/weeks" folder
(all i literally did was add new difficulties to it)

```lua
{
	"songs": [
		["Bopeebo", "dad", [146, 113, 253]],
		["Fresh", "dad", [146, 113, 253]],
		["Dad Battle", "dad", [146, 113, 253]]
	],

	"weekCharacters": [
		"dad",
		"bf",
		"gf"
	],
	"weekBackground": "stage",

	"storyName": "Daddy Dearest",
	"weekBefore": "tutorial",
	"weekName": "Week 1",
	"difficulties": "Easy, Normal, Hard, Extreme, Laryngitis",
	"startUnlocked": true,

	"hideStoryMode": false,
	"hideFreeplay": false
}
```

**Comment by Jerry-The-SMG4-Fan** [comment]
update: it does work if i put it in just mods/weeks
but if i put it in mods/[Modpack]/weeks it doesnt
@CaptainBaldi just letting u know w/ an update
