### ISSUE TITLE
How do i make an event in dialogues?

### ISSUE THREAD

**Issue by Steve35117** [ShadowMario/FNF-PsychEngine#13351]
### Describe your problem here.

As example: BF says something then the HUD shakes and a sound will play. I dont get this stuff tbh 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
![InvincibleThat'STheNeatPartGIF](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/31b85a17-947d-4845-ba1f-e70f0d9aa85d)

**Comment by MemeHovy** [comment]
it's not possible in Lua as far as I know

**Comment by Lorekeeper49** [comment]
You could probably do it with the `onNextDialogue()` callback and by tracking the dialogue counter to do events on specific dialogue lines

**Comment by MemeHovy** [comment]
> You could probably do it with the `onNextDialogue()` callback and by tracking the dialogue counter to do events on specific dialogue lines

yea but that’s as close as you can get it

**Comment by Steve35117** [comment]
> You could probably do it with the `onNextDialogue()` callback and by tracking the dialogue counter to do events on specific dialogue lines

Can you send an example?

**Comment by Steve35117** [comment]
> > You could probably do it with the `onNextDialogue()` callback and by tracking the dialogue counter to do events on specific dialogue lines
> 
> yea but that’s as close as you can get it

Example?
