### ISSUE TITLE
Chart Editor Crash when attempting to save.

### ISSUE THREAD

**Issue by forgettablepyromaniac** [ShadowMario/FNF-PsychEngine#13359]
### Describe your bug here.

I was simply hitting save while the chart was running in the background. It did have a different playback speed, if that helps.

The chart / window kept running in the background, and I tried to finish the saving process and thereafter hitting the ok button (which then forced the game to close), but it didn't save. Aw well.

I saw _"Uncaught Error: [file_contents,assets/characters/bf.json]"_ and also thought I should mention that while I have a custom bf.json in the characters folder of my mod, the only difference is the offsets, nothing else has been changed about it.

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
states/editors/ChartingState.hx (line 2642)
states/editors/ChartingState.hx (line 2607)
states/editors/ChartingState.hx (line 2602)
states/editors/ChartingState.hx (line 2581)
states/editors/ChartingState.hx (line 1645)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/characters/bf.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, this is a downloaded build (0.7.1h, specifically).

**Comment by MemeHovy** [comment]
did you delete it in assets/characters?

**Comment by forgettablepyromaniac** [comment]
> did you delete it in assets/characters?

I did not. I had not changed anything inside of assets/characters, I was just saving like any other attempt.

**Comment by MemeHovy** [comment]
> > did you delete it in assets/characters?
> 
> I did not. I had not changed anything inside of assets/characters, I was just saving like any other attempt.

well make sure you don’t have two characters with the same name since they can conflict

**Comment by forgettablepyromaniac** [comment]
> > > did you delete it in assets/characters?
> > 
> > 
> > I did not. I had not changed anything inside of assets/characters, I was just saving like any other attempt.
> 
> well make sure you don’t have two characters with the same name since they can conflict

previously, having two bfs meant that the one in the Mods folder would take priority, no?
And even despite that, what does bf.json have to do with anything in the chart editor?
