### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by rolexwatch123** [ShadowMario/FNF-PsychEngine#13356]
### Describe your problem here.

Does anyone have a script or way so when bot play is enabled it shows the rating and accuracy?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I have installed mods

**Comment by MemeHovy** [comment]
not exactly possible

**Comment by rolexwatch123** [comment]
> not exactly possible

is it possible to edit the source code either

**Comment by MemeHovy** [comment]
> > not exactly possible
> 
> is it possible to edit the source code either @MemeHovy

yea, that's why this github repo exists

**Comment by rolexwatch123** [comment]
then how do i do it

> > > not exactly possible
> > 
> > 
> > is it possible to edit the source code either @MemeHovy
> 
> yea, that's why this github repo exists
