### ISSUE TITLE
SCall error?

### ISSUE THREAD

**Issue by Frazcai** [ShadowMario/FNF-PsychEngine#13353]
### Describe your problem here.

'source/psychlua/HScript.hx:140: characters 100-105 : Type not found : SCall'

	'public function executeCode(codeToRun:String, ?funcToRun:String = null, ?funcArgs:Array<Dynamic>):SCall'.

I don't know why It's bugged. It was working fine earlier.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, edited some states.

**Comment by Frazcai** [comment]
0.7.1 btw

**Comment by CaptainBaldi** [comment]
use sscript 4.1.0- if you have it (you can't download older versions anymore) or use experimental branch with latest sscript

**Comment by Steve35117** [comment]
> use sscript 4.1.0- if you have it (you can't download older versions anymore) or use experimental branch with latest sscript

how

**Comment by MemeHovy** [comment]
> > use sscript 4.1.0- if you have it (you can't download older versions anymore) or use experimental branch with latest sscript
> 
> how

`haxelib install SScript 4.1.0` & https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental
