### ISSUE TITLE
Where can I find GF Sing?

### ISSUE THREAD

**Issue by TheRealPepsi** [ShadowMario/FNF-PsychEngine#13357]
### What is your question?

Hey all, I've been looking through Psych Engine's files, even the github source code, and I can't seem to find the code for [GF Sing](![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/134110892/48467f12-8164-4617-bf54-1f29af29aa0c). Where is it located? Or is it baked into the exe itself?

Thanks!

**Comment by RandomGuy4312** [comment]
It is in Note.hx and Playstate.hx

**Comment by TheRealPepsi** [comment]
Ah, so it's not in lua foramt, then?

**Comment by RandomGuy4312** [comment]
nope

**Comment by TheRealPepsi** [comment]
Well, that's unfortunate. Thanks for the help though!

**Comment by RandomGuy4312** [comment]
This simulates the gf sing note I hope it helps you



function onCreate()
            for i = 0, getProperty('unspawnNotes.length') - 1 do
            if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'GFSing' then
            setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true);   
         end
     end
end

function goodNoteHit(id,dir,type,sus)
	if type == 'GFSing' then
		characterPlayAnim('gf', getProperty('singAnimations')[math.abs(dir)+1], true)
		setProperty('gf.holdTimer', 0)
	end
end

function opponentNoteHit(id,dir,type,sus)
	if type == 'GFSing' then
		characterPlayAnim('gf', getProperty('singAnimations')[math.abs(dir)+1], true)
		setProperty('gf.holdTimer', 0)
	end
end
