### ISSUE TITLE
i need help i am new to this

### ISSUE THREAD

**Issue by TEAMSKILLGAMINGG** [ShadowMario/FNF-PsychEngine#13360]
### Describe your problem here.

hi so when i open the psych engine, it justs stopped working
![error](https://github.com/ShadowMario/FNF-PsychEngine/assets/116753156/f64033c9-9229-4011-88d9-8fc413c4b2da)
please help me

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
did you even wait for it to finish loading?

**Comment by TEAMSKILLGAMINGG** [comment]
> did you even wait for it to finish loading?

i did but it didnt work i even deleted it and reinstalled it and again it was the same error and its the newest i downloaded it and try other versions and 0.6.3 is working fine for me but its have some errors like i cant see the custorm back grounds from other mods

**Comment by Draconic-Hybrid** [comment]
Looks like a PC problem. What PC are you using?
