### ISSUE TITLE
convert haxe into lua

### ISSUE THREAD

**Issue by Mlaofmd** [ShadowMario/FNF-PsychEngine#13368]
### Describe your problem here.

im just want to convert this code on haxe to lua

`	

function redFlash() // HaxeFlixel documentaion be like - PurSnake || Rewrited - PurSnake
	
{
        if(healthBar.percent > 17) {
		    
if(isHealthCheckingEnabled)
		    isHealthCheckingEnabled = false;
		   
 if(iconP1.spriteType != "animated" && iconP1.spriteType != "single" || iconP1.spriteType.startsWith('trio') ) iconP1.animation.curAnim.curFrame = 1;   
 
if(iconP2.spriteType == 'trio') iconP2.animation.curAnim.curFrame = 2;

		    new FlxTimer().start(Conductor.crochet / 750 / playbackRate, function(tmr:FlxTimer)
		    {
			    isHealthCheckingEnabled = true;
		    });
        } 
 	}
`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
psych engine discord has a channel for this stuff if I remember correctly

**Comment by Mlaofmd** [comment]
> psych engine discord has a channel for this stuff if I remember correctly

what is channel?

**Comment by MemeHovy** [comment]
> > psych engine discord has a channel for this stuff if I remember correctly
> 
> what is channel? can you ask?

I can’t since I’m banned, but you can look here https://discord.gg/2ka77eMXDv
