### ISSUE TITLE
i can't compile the source code

### ISSUE THREAD

**Issue by Shiho-cmd** [ShadowMario/FNF-PsychEngine#13365]
### Describe your problem here.

i'm new to this stuff so in the first time i tried to compile the code this keeps happening
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/146484710/0e77e687-8ccd-426b-b969-a34b1a53a1db)
can someone help me with this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
use sscript 4.1.0

**Comment by Timbal5p** [comment]
maybe this can help you: #10756

**Comment by MemeHovy** [comment]
> maybe this can help you: #10756

I just gave the solution

**Comment by Shiho-cmd** [comment]
> use sscript 4.1.0

it didn't work

**Comment by MemeHovy** [comment]
> > use sscript 4.1.0
> 
> it didn't work

`haxelib install SScript 4.1.0`

**Comment by Shiho-cmd** [comment]
> haxelib install SScript 4.1.0

i already have it and still didn't work

**Comment by MemeHovy** [comment]
show

**Comment by Shiho-cmd** [comment]
> show

it still shows this error
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/146484710/c949fc5e-401b-4d4a-aeb1-88827d2d3b14)

**Comment by MemeHovy** [comment]
> > show
> 
> it still shows this error ![image](https://user-images.githubusercontent.com/146484710/271807155-c949fc5e-401b-4d4a-aeb1-88827d2d3b14.png)

use the latest experimental branch

**Comment by Shiho-cmd** [comment]
> > > show
> > 
> > 
> > it still shows this error ![image](https://user-images.githubusercontent.com/146484710/271807155-c949fc5e-401b-4d4a-aeb1-88827d2d3b14.png)
> 
> use the latest experimental branch

what is this?

**Comment by MemeHovy** [comment]
> > > > show
> > > 
> > > 
> > > it still shows this error ![image](https://user-images.githubusercontent.com/146484710/271807155-c949fc5e-401b-4d4a-aeb1-88827d2d3b14.png)
> > 
> > 
> > use the latest experimental branch
> 
> what is this?

https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental this

**Comment by Shiho-cmd** [comment]
> > > > > show
> > > > 
> > > > 
> > > > it still shows this error ![image](https://user-images.githubusercontent.com/146484710/271807155-c949fc5e-401b-4d4a-aeb1-88827d2d3b14.png)
> > > 
> > > 
> > > use the latest experimental branch
> > 
> > 
> > what is this?
> 
> https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental this

it worked thank you!!!

**Comment by MemeHovy** [comment]
> > > > > > show
> > > > > 
> > > > > 
> > > > > it still shows this error ![image](https://user-images.githubusercontent.com/146484710/271807155-c949fc5e-401b-4d4a-aeb1-88827d2d3b14.png)
> > > > 
> > > > 
> > > > use the latest experimental branch
> > > 
> > > 
> > > what is this?
> > 
> > 
> > https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental this
> 
> it worked thank you!!!

np
