### ISSUE TITLE
Need a bit of help

### ISSUE THREAD

**Issue by MarshypooLongToodles** [ShadowMario/FNF-PsychEngine#13364]
Im not sure what to do, im new to this whole thing
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/146395677/9b10ff0c-2190-49cd-9bf9-833160fb9e49)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ricoanimations** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental
use the latest experimental build
see if that works

**Comment by MarshypooLongToodles** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental use the latest experimental build see if that works

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/146395677/95d23828-278c-4706-bf83-1c3db00483a5)
im sorry 😓

**Comment by ricoanimations** [comment]
![projectxmllol](https://github.com/ShadowMario/FNF-PsychEngine/assets/119141397/a9efcdb6-e01f-4368-8325-71d336db1a99)

You need to compile the folder that has the "Project.xml" file in it or else it won't compile

**Comment by MarshypooLongToodles** [comment]
> ![projectxmllol](https://user-images.githubusercontent.com/119141397/271448093-a9efcdb6-e01f-4368-8325-71d336db1a99.PNG) You need to compile the folder that has the "Project.xml" file in it or else it won't compile

i have im now sure whats going on

**Comment by MarshypooLongToodles** [comment]
> > ![projectxmllol](https://user-images.githubusercontent.com/119141397/271448093-a9efcdb6-e01f-4368-8325-71d336db1a99.PNG) You need to compile the folder that has the "Project.xml" file in it or else it won't compile
> 
> i have im now sure whats going on

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/146395677/92f07a4b-c4e3-4f50-b11b-e8e964d6e3ea)

**Comment by ricoanimations** [comment]
Sorry for responding late but all you do is go to command prompt and type the following

`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit master`
