### ISSUE TITLE
I Tried To Play "Come Along With Me" On Pibby Apocalypse And It Keeps Saying Error

### ISSUE THREAD

**Issue by Niko-78037** [ShadowMario/FNF-PsychEngine#13366]
### Describe your problem here.

I Tried To Play "Come Along With Me" On Pibby Apocalypse And It Keeps Saying Error

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
ask the mod creator

**Comment by MemeHovy** [comment]
problem with the mod, not the engine

**Comment by Niko-78037** [comment]
Oh Okay Thanks

**Comment by Niko-78037** [comment]
Thank You
