### ISSUE TITLE
Only changing BF's note colors

### ISSUE THREAD

**Issue by NpcSnoom397** [ShadowMario/FNF-PsychEngine#13361]
### What is your question?

Is there any way to only apply the note colors to BF only ? Or just detect which character's note is it ?

**Comment by MemeHovy** [comment]
use the `mustPress` var in note like this, `note.mustPress` depending on what you named the note var

**Comment by NpcSnoom397** [comment]
Should it be use with an if, or in some different way ?
Since the notes are colored upon being created

**Comment by MemeHovy** [comment]
yea if statement

**Comment by NpcSnoom397** [comment]
I'm guessing the note var is called "this"
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/107694396/f18843b7-4d45-4e7c-b6bb-d05a48c2d789)

**Comment by NpcSnoom397** [comment]
It works fine
At least with the notes
Now I kinda need to figure out how to do the same with the Strums

**Comment by MemeHovy** [comment]
> It works fine
> At least with the notes
> Now I kinda need to figure out how to do the same with the Strums

look in the StrumNote class, and btw, install the Haxe extension for vsc

**Comment by NpcSnoom397** [comment]
I'm not sure on what and where to use
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/107694396/a1192253-675a-451c-ac17-27e4a7d8732e)
This didn't work

**Comment by MemeHovy** [comment]
> I'm not sure on what and where to use ![image](https://user-images.githubusercontent.com/107694396/271057388-a1192253-675a-451c-ac17-27e4a7d8732e.png) This didn't work

that's just the same thing

**Comment by MemeHovy** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/e1dfa5b2-d5e3-424d-a0b0-0b1a6a32629c)

what you would do is check `if (player == 1)`

**Comment by MemeHovy** [comment]
> It works perfectly
> Final question, is it possible to only change the colors on specific textures ?

yes, `if (texture == 'inserttexturehere')`
note it’s case sensitive
