### ISSUE TITLE
Why middle scroll doesn't work

### ISSUE THREAD

**Issue by I-am-someone-sh** [ShadowMario/FNF-PsychEngine#13369]
### Describe your problem here.

I am using psych engine 0.7 and I am trying to forced to middle scroll
function onCreate()     
	setPropertyFromClass('backend.ClientPrefs', 'middleScroll', true)
end
but doesn't work always although I put into the script folder, song data, stage. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
`data.middleScroll`
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7

**Comment by I-am-someone-sh** [comment]
> `data.middleScroll` https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7

god thanks you I didn't notice that when I am checking

**Comment by MemeHovy** [comment]
stop reopening the issue
