### ISSUE TITLE
HELP ME! IM COMPILING!

### ISSUE THREAD

**Issue by thetemmi** [ShadowMario/FNF-PsychEngine#13374]
### Describe your problem here.

what i am supposed to do? 
`source/psychlua/HScript.hx:168: characters 89-94 : Type not found : SCall`
(windows powershell when im running lime test windows)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/122259937/2c608b5f-ca3b-401f-ac51-4a893569c73c)

### UPD : I solved this problem but now i have new one

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/122259937/8a099cd4-92e6-4d29-8e1c-eac93ec7c6de)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Mlaofmd** [comment]
try use sscript 4.1.0

**Comment by thetemmi** [comment]
> try use sscript 4.1.0
already
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/122259937/1bf28f27-57e4-4fb1-9207-6c7b189bfde2)

**Comment by MemeHovy** [comment]
use the latest experimental branch

**Comment by thetemmi** [comment]
> use the latest experimental branch

k

**Comment by Red-Impostor** [comment]
try to rearrange SScript from git to 4.1.0
