### ISSUE TITLE
hxCodec gets errors

### ISSUE THREAD

**Issue by Mlaofmd** [ShadowMario/FNF-PsychEngine#13379]
### Describe your problem here.

please help
i tried reinstall, update, install git and NOTHING
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1699: characters 13-23 : Type not found : MP4Handler

PLS HELP

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Mlaofmd** [comment]
Guys I solved this problem, just need to set hxCodec 2.6.0, to get work, please pin this!

**Comment by chicken-nugget1104** [comment]
> Guys I solved this problem, just need to set hxCodec 2.6.0, to get work, please pin this!

did not work
