### ISSUE TITLE
Change Healt Bar (0.6.3)

### ISSUE THREAD

**Issue by GatoMagoXD** [ShadowMario/FNF-PsychEngine#13371]
### Describe your problem here.

I tried to Put a custom health bar
![HealthBar](https://github.com/ShadowMario/FNF-PsychEngine/assets/135041008/b771fddb-23b6-48fc-af34-23c37f450896)
But the color in the bar is a Rectangle, how I can change the form of the color bar? 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

The Bar

**Comment by Username2120** [comment]
you cant round off a FlxBar's corners, so there isnt a way to do this as far as im aware.
