### ISSUE TITLE
Where is the source code of reading and parsing  the song-name.json?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#1337]
### What is your question?

Where is the source code of reading and parsing  the song-name.json?
```
assets\data\song-name\song-name.json
assets\data\song-name\song-name-easy.json
assets\data\song-name\song-name-hard.json
```

**Comment by ShadowMario** [comment]
Be more specific because i'm confused on what you're trying to look for

**Comment by Gui-iago** [comment]
coolUtil.hx if that's what you meant
