### ISSUE TITLE
How Do You Tween In Haxe?

### ISSUE THREAD

**Issue by SuccvDucc** [ShadowMario/FNF-PsychEngine#13376]
How Do You Do

	doTweenX('topbartween1', 'topbar', 0, 3.2, 'Linear')
	if tag == 'topbartween1' then
		doTweenX('topbartween2', 'topbar', -640, 0.01, 'Linear')
	else
		if tag == 'topbartween2' then
		doTweenX('topbartween1', 'topbar', 0, 3.2, 'Linear')
	end

But In Haxe?

		tbar = new FlxSprite().loadGraphic(Paths.image('Freeplay/TopBar'));
		tbar.antialiasing = ClientPrefs.data.antialiasing;
		add(tbar);
		tbar.screenCenter();

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

MainMenuStateAnd FreeplayState

**Comment by Chidubemmo** [comment]
FlxTween https://api.haxeflixel.com/flixel/tweens/FlxTween.html

**Comment by SuccvDucc** [comment]
thank you😑👍
