### ISSUE TITLE
problemssss with complieee

### ISSUE THREAD

**Issue by Mlaofmd** [ShadowMario/FNF-PsychEngine#13375]
### Describe your problem here.

i getting this error

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/52864321/b360b1d4-ef7a-4eec-b1d3-0a606b41d50b)

please help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
update flixel and HxCodec
