### ISSUE TITLE
i dont understand what SCall is??

### ISSUE THREAD

**Issue by NotCurtainCat** [ShadowMario/FNF-PsychEngine#13378]
### Describe your problem here.

source/psychlua/HScript.hx:168: characters 89-94 : Type not found : SCall

what am i doing wrong?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Mlaofmd** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by NekaouMike** [comment]
All versions are correct and doesn't fix it for me
