### ISSUE TITLE
How do i make a custom death animation on 0.7.1h

### ISSUE THREAD

**Issue by LionKrono** [ShadowMario/FNF-PsychEngine#13377]
### Describe your problem here.

i try to use the classic:

function onCreate()
    setPropertyFromClass('GameOverSubstate', 'characterName', 'bf-dead'); --Character json file for the death animation
    setPropertyFromClass('GameOverSubstate', 'deathSoundName', 'fnf_loss_sfx'); --put in mods/sounds/
    setPropertyFromClass('GameOverSubstate', 'loopSoundName', 'gameOver'); --put in assets/shared/music/
    setPropertyFromClass('GameOverSubstate', 'endSoundName', 'gameOverEnd'); --put in assets/shared/music/
end

and it doesn't work, what can i do?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by GatoMagoXD** [comment]
In the **chart editor**, go to the **"Data" tab**, it works exactly the same as the script.

**Comment by Draconic-Hybrid** [comment]
Change `GameOverSubstate` to `substate.GameOverSubstate`
