### ISSUE TITLE
Spacebar/dodge mechanic doesn't seems to work

### ISSUE THREAD

**Issue by MultiverseBF** [ShadowMario/FNF-PsychEngine#13388]
### Describe your bug here.

So, I believe this version kinda broke some mods that I've played in the old version which I'll say in a moment. When I decide to import the other mods from the old version, which is 0.6.3, somehow in all the mods that require you to hit the spacebar to dodge anything or just hit it to not get one hit K.O it seems it doesn't register the input, even by changing the code or updating it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
it’s a problem with the mods you have, not the engine

**Comment by frantastic24** [comment]
You may need to update your mods #12867

**Comment by MultiverseBF** [comment]
> You may need to update your mods #12867
So by using whats in that post it then could work?

**Comment by MultiverseBF** [comment]
> You may need to update your mods #12867

Thank you so much, the code from the post you add there worked ^^

**Comment by ShadowMario** [comment]
Next time close the issue if you fixed your problem
