### ISSUE TITLE
I can't complile it!

### ISSUE THREAD

**Issue by XavierXP1** [ShadowMario/FNF-PsychEngine#13389]
### Describe your problem here.

I tried to compile the game, but it didn't work. I made `haxelib install SScript 4.1.0` and I did `lime test windows` in a experimental branch, but nothing. Can someone help me?

![Captura de Tela (16)](https://github.com/ShadowMario/FNF-PsychEngine/assets/91752998/1fab6c04-149f-4885-aee6-c3e61b1f97ae)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
holdup I have the files

**Comment by MemeHovy** [comment]
[4,1,0.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/12823258/4.1.0.zip)

replace the folder with the contents of this zip

**Comment by XavierXP1** [comment]
It works, but now it shows this error...

![Captura de Tela (17)](https://github.com/ShadowMario/FNF-PsychEngine/assets/91752998/ca996910-ef4a-4269-9d3c-1e3478e43683)

**Comment by XavierXP1** [comment]
It works, but now it shows this:

![Captura de Tela (18)](https://github.com/ShadowMario/FNF-PsychEngine/assets/91752998/b3aa8b41-b6cb-481b-b009-b8a3daa0aa90)

What to do?

**Comment by MemeHovy** [comment]
> It works, but now it shows this:
> 
> ![Captura de Tela (18)](https://user-images.githubusercontent.com/91752998/273049051-b3aa8b41-b6cb-481b-b009-b8a3daa0aa90.png)
> 
> What to do?

remove anything related to HTTP in SScript

**Comment by XavierXP1** [comment]
Okay...now it shows this: 

![Captura de Tela (20)](https://github.com/ShadowMario/FNF-PsychEngine/assets/91752998/ed63a079-a311-4679-ada2-babf3ed1c822)

**Comment by MemeHovy** [comment]
> Okay...now it shows this:
> 
> ![Captura de Tela (20)](https://user-images.githubusercontent.com/91752998/273055350-ed63a079-a311-4679-ada2-babf3ed1c822.png)

you still didn't remove it all

**Comment by XavierXP1** [comment]
Okay. I gotcha. After I removed everything that's **HTTP** it now show it this.

![Captura de Tela (21)](https://github.com/ShadowMario/FNF-PsychEngine/assets/91752998/2cf2c438-bdbb-4a5f-919e-fa06c6092b9a)

Here's the file that I modified: [SScriptVer.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/12824912/SScriptVer.zip)

**Comment by XavierXP1** [comment]
Do you have any idea what to do now @MemeHovy?
