### ISSUE TITLE
how do i update to the latest experimental branch

### ISSUE THREAD

**Issue by mrlion204** [ShadowMario/FNF-PsychEngine#13386]
### Describe your problem here.

im trying to compile the 0.71h engine but the error sscall not found some other people are confused including me  on how to update 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MemeHovy** [comment]
by going to here https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental and also, don't make an issue about this you fucking retard

**Comment by JimMeta-belike** [comment]
> by going to here https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental and also, don't make an issue about this you fucking retard
Why u rude
