### ISSUE TITLE
what the hell do i do here 

### ISSUE THREAD

**Issue by ZAlRU** [ShadowMario/FNF-PsychEngine#13382]
### What is your question?

Error: linc_discord_rpc.cpp
C:\HaxeToolkit\haxe\lib\discord_rpc\git\linc\linc_discord_rpc.h(7): fatal error C1083: Cannot open include file: '../lib/discord-rpc/include/discord-rpc.h': No such file or directory

**Comment by MemeHovy** [comment]
reinstall discord_rpc

**Comment by methewhenmeth3** [comment]
to anybody who finds this and prefers to have their problem actually fixed, my fix was `haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc`

**Comment by methewhenmeth3** [comment]
i do not know why this works because it should be equivalent to reinstalling, but im not complaining.
