### ISSUE TITLE
Player Controls control

### ISSUE THREAD

**Issue by GMan2006i** [ShadowMario/FNF-PsychEngine#1338]
### How to make player lose control of BF??

this is more of a question/request
is there some way to make the player not use any controls (temporarily) when a specific note is hit
and if this isn't a feature then could you add it?
I'm using a build version so it would be nice to have this available in Lua

thanks for help :)

**Comment by DEV-idiotXD** [comment]
> 

use the lua setpropertyfromgroup to change the inputs to a nil(make sure to make a table to save the inputs) value then restore it (from the table u ade)

**Comment by GMan2006i** [comment]
@DEV-idiotXD could i have an example?

**Comment by DEV-idiotXD** [comment]
idk i just knw u can chane client prefs with setpropertyfromgroup

**Comment by GMan2006i** [comment]
well what is the obj, index, variable, and value for controls??

**Comment by ShadowMario** [comment]
`setProperty('boyfriend.stunned', true);`

**Comment by DEV-idiotXD** [comment]
the obj is ClientPrefs idk the rest

**Comment by DEV-idiotXD** [comment]
> `setProperty('boyfriend.stunned', true);`

oh

**Comment by GMan2006i** [comment]
> `setProperty('boyfriend.stunned', true);`

yo thanks shadow
your mod is amazing :)
