### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by VideoBotYT** [ShadowMario/FNF-PsychEngine#13383]
### Describe your problem here.

<img width="443" alt="image" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/113830775/3118b453-fb1b-4100-8c59-f3df31741ff4">
it constantly gives me this error

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing has changed in this just a fresh build

**Comment by glowsoony** [comment]
update your SScript lib to 6.1.80 (haxelib install SScript 6.1.80) and use TeaCall instead.

**Comment by MemeHovy** [comment]
> update your SScript lib to 6.1.80 (haxelib install SScript 6.1.80) and use TeaCall instead.

what you said was wrong, use SScript 4.1.0 and use the latest experimental branch

**Comment by glowsoony** [comment]
the latest push to the experimental branch was updating back to SScript and it updated to 6.1.80 since 4.1.0 and versions under of SScript don't work. this being why TeaCall was used in the lastest expermential branch push.

**Comment by MemeHovy** [comment]
> the latest push to the experimental branch was updating back to SScript and it updated to 6.1.80 since 4.1.0 and versions under of SScript don't work. this being why TeaCall was used in the lastest expermential branch push.

TeaCall & SCall aren't the same thing, it will not work if you simply replace SCall with TeaCall

**Comment by glowsoony** [comment]
TeaCall and SCall work the same and they are the same typedef but are called differently because of the version used.
Updating to the latest experimental branch push will make you update to SScript 6.1.80 and it does in fact just replace the name of SCall with TeaCall which is why I recommended updating to 6.1.80 and using TeaCall instead of SCall.

**Comment by MemeHovy** [comment]
> TeaCall and SCall work the same and they are the same typedef but are called differently because of the version used. Updating to the latest experimental branch push will make you update to SScript 6.1.80 and it does in fact just replace the name of SCall with TeaCall which is why I recommended updating to 6.1.80 and using TeaCall instead of SCall.

I've heard from people that SScript 4.1.0 has been working, and when they tried to do that, it just gave more errors so believe me, SScript 4.1.0 works

**Comment by glowsoony** [comment]
I think people who already had SScript before it was updated, there SScript 4.1.0 will work but for those who didn't it won't work. I ain't saying you wrong either but replacing TeaCall with SCall in 4.1.0 and under will give errors because TeaCall is only 6.1.80 that's why. and I do have a version that includes SCall so I know you aren't wrong. Probably why it's throwing an error in this issue opened is because they have a version that does not have SCall.

**Comment by MemeHovy** [comment]
> I think people who already had SScript before it was updated, there SScript 4.1.0 will work but for those who didn't it won't work. I ain't saying you wrong either but replacing TeaCall with SCall in 4.1.0 and under will give errors because TeaCall is only 6.1.80 that's why. and I do have a version that includes SCall so I know you aren't wrong. Probably why it's throwing an error in this issue opened is because they have a version that does not have SCall.

no because SScript was completely different compared to before, and there was whole other issues unrelated to SCall

**Comment by GAMERMEER** [comment]
it worked now with the experimentel branch

> > update your SScript lib to 6.1.80 (haxelib install SScript 6.1.80) and use TeaCall instead.
> 
> what you said was wrong, use SScript 4.1.0 and use the latest experimental branch

**Comment by MemeHovy** [comment]
> it worked now with the experimentel branch
> 
> > > update your SScript lib to 6.1.80 (haxelib install SScript 6.1.80) and use TeaCall instead.
> > 
> > 
> > what you said was wrong, use SScript 4.1.0 and use the latest experimental branch

told ya so @glowsoony

**Comment by JohnDoe3453** [comment]
im havin the same issue

**Comment by Sanskywuzz** [comment]
> atualize sua lib SScript para 6.1.80 (haxelib install SScript 6.1.80) e use TeaCall em vez disso.

But how do I change Scall to TeaCall?

**Comment by JaredMcKano** [comment]
> it worked now with the experimentel branch

Where do I get the branch?

**Comment by JaredMcKano** [comment]
> Where do I get the branch?

NVM, got it and a new error...

**Comment by final-23** [comment]
try:
haxelib remove SScript
haxelib git SScript https://github.com/mcagabe19-stuff/SScript-6.1.80/
Thus, Problem solved.
