### ISSUE TITLE
Fnf 

### ISSUE THREAD

**Issue by 123gif1** [ShadowMario/FNF-PsychEngine#13380]
### Describe your problem here.

An error keeps popping up when I try to execute an executable psych engine mod the error is: [line.utils.preloader] error: there is no asset library with an id of "video" this is my first time on a PC, can someone help me

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Mlaofmd** [comment]
corrupted files or idk

**Comment by NexIsDumb** [comment]
this happens most of times when you delete the whole assets folder
are you sure you havent deleted anything?

**Comment by 123gif1** [comment]
> this happens most of times when you delete the whole assets folder are you sure you havent deleted anything?

No, I didn't delete any of the files from the folder the mod came with

**Comment by NexIsDumb** [comment]
> > this happens most of times when you delete the whole assets folder are you sure you havent deleted anything?
> 
> 
> 
> No, I didn't delete any of the files from the folder the mod came with

wait so you downloaded a mod?

**Comment by 123gif1** [comment]
> > > this happens most of times when you delete the whole assets folder are you sure you havent deleted anything?
> > 
> > 
> > No, I didn't delete any of the files from the folder the mod came with
> 
> wait so you downloaded a mod?

Yeah and it's not just this one specific mod it's for all the psych engine mod it's sometimes characters and not videos

**Comment by NexIsDumb** [comment]
> > > > this happens most of times when you delete the whole assets folder are you sure you havent deleted anything?
> > > 
> > > 
> > > No, I didn't delete any of the files from the folder the mod came with
> > 
> > wait so you downloaded a mod?
> 
> Yeah and it's not just this one specific mod it's for all the psych engine mod it's sometimes characters and not videos

could you send me a screenshot of whats inside the assets folder?

**Comment by 123gif1** [comment]
> > > > > this happens most of times when you delete the whole assets folder are you sure you havent deleted anything?
> > > > 
> > > > 
> > > > No, I didn't delete any of the files from the folder the mod came with
> > > 
> > > 
> > > wait so you downloaded a mod?
> > 
> > 
> > Yeah and it's not just this one specific mod it's for all the psych engine mod it's sometimes characters and not videos
> 
> could you send me a screenshot of whats inside the assets folder?

![IMG_20231018_181101](https://github.com/ShadowMario/FNF-PsychEngine/assets/146729302/b9938d77-a570-4654-ad32-bca84f56f7a1)

**Comment by NexIsDumb** [comment]
hmm is there instead a manifest.json in the main folder?

**Comment by 123gif1** [comment]
> hmm is there instead a manifest.json in the main folder?

No there's no manifest.json but there's the manifest folder with default.json and shared.json and songs.json and videos.json inside
![IMG_20231018_200608](https://github.com/ShadowMario/FNF-PsychEngine/assets/146729302/fc4e1bc1-b24f-44ed-b6e7-6b16d525e26b)

**Comment by NexIsDumb** [comment]
but hmm then its not psych's fault

**Comment by 123gif1** [comment]
> but hmm then its not psych's fault

Damn

**Comment by NexIsDumb** [comment]
yup

**Comment by NexIsDumb** [comment]
close this issue if you dont have anything else please

**Comment by 123gif1** [comment]
> close this issue if you dont have anything else please

Alright
