### ISSUE TITLE
Lua scripts are not executed(0.5.2h)

### ISSUE THREAD

**Issue by SilverWhite233** [ShadowMario/FNF-PsychEngine#13381]
### Describe your bug here.

I packed the files in the example_mods into the assets directory and changed Paths.hx, but then some lua scripts didn't execute
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/125836305/2f4f1834-c5bb-49af-86ad-4c6e6d26c59f)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/125836305/3daf468a-32c4-47d1-bab7-5dc4b5224b9c)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/125836305/e546607e-417b-46f5-9da9-eaac14b8c1a9)
BFSing.lua did not execute
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/125836305/01068eac-15cb-4a47-9d64-98528f653e5d)

### Command Prompt/Terminal logs (if existing)

```bash
source/Discord.hx:68: Discord Client initialized
source/Discord.hx:25: Discord Client started.
source/FreeplayState.hx:368: dad-battle-hard
source/FreeplayState.hx:374: CURRENT WEEK: week1
source/LoadingState.hx:162: Setting asset folder to shared
source/Conductor.hx:75: new BPM map BUDDY []
source/FunkinLua.hx:76: Lua file loaded succesfully:assets/scripts/BFSing.lua
source/FunkinLua.hx:76: Lua file loaded succesfully:assets/scripts/ui.lua
source/Conductor.hx:75: new BPM map BUDDY []
source/FunkinLua.hx:76: Lua file loaded succesfully:assets/scripts/BFSing.lua
source/FunkinLua.hx:76: Lua file loaded succesfully:assets/scripts/ui.lua
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes,I packed the files in the example_mods into the assets directory and changed Paths.hx

**Comment by MemeHovy** [comment]
0.5.2h and below are not supported

**Comment by SilverWhite233** [comment]
> 不支持 0.5.2h 及以下
thanks

**Comment by MemeHovy** [comment]
> > 不支持 0.5.2h 及以下
> > thanks

you're welcome?
