### ISSUE TITLE
Code compilation error SScript

### ISSUE THREAD

**Issue by XenoEntity** [ShadowMario/FNF-PsychEngine#13387]
### Describe your problem here.

I tried to compile the Psych code and I got this error: HEEELP

FNF-PsychEngine-main/.haxelib/SScript/4,0,1/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
bro if i see one more issue about this i swear :sob:
look at the DOZEN other issues about this

**Comment by MemeHovy** [comment]
use SScript 4.1.0, and update to the latest experimental branch

**Comment by Magniill** [comment]
you also can use SScript 6.1.80, just use the experimental branch
