### ISSUE TITLE
Such a problem with compilation.

### ISSUE THREAD

**Issue by ToriRaksanin** [ShadowMario/FNF-PsychEngine#13390]
### Describe your problem here.

Everything was fine. Deleted as it seemed to me the extra files from the folder with the game, it was weeks. Complained initially about their absence, restored them. Then the extra }, I fixed it too, now complains about it, I don't know how to deal with it anymore. Version 0.6.3.
![Снимокок5ок](https://github.com/ShadowMario/FNF-PsychEngine/assets/127664564/9f32a5bd-cc27-471b-a0ac-4cb8105c9711)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes. I added events via the source code from my past mod. Fixed a buggy bot play, also removed timebar. These are all changes.

**Comment by MemeHovy** [comment]
dude, is it not that obvious? read the error

**Comment by ToriRaksanin** [comment]
> dude, is it not that obvious? read the error

I read it. I tried to delete both ")" and different commas. Nothing helps...

**Comment by MemeHovy** [comment]
> > dude, is it not that obvious? read the error
> 
> I read it. I tried to delete both ")" and different commas. Nothing helps...

you're missing a } is the issue

**Comment by ToriRaksanin** [comment]
> > > dude, is it not that obvious? read the error
> > 
> > 
> > I read it. I tried to delete both ")" and different commas. Nothing helps...
> 
> you're missing a } is the issue

Thank you, it helped. But there were about 10-15 more errors. To be honest, I don't have enough nerves anymore. Do you have a discord? Can I contact you directly about this?

**Comment by MemeHovy** [comment]
> > > > dude, is it not that obvious? read the error
> > > 
> > > 
> > > I read it. I tried to delete both ")" and different commas. Nothing helps...
> > 
> > 
> > you're missing a } is the issue
> 
> Thank you, it helped. But there were about 10-15 more errors. To be honest, I don't have enough nerves anymore. Do you have a discord? Can I contact you directly about this?

yea it's on my profile
