### ISSUE TITLE
How do i open the game

### ISSUE THREAD

**Issue by AshotlWotl** [ShadowMario/FNF-PsychEngine#13393]
I fully installed haxe and got all the files for psych engine through the command prompt.
how do i open the game. im extremely new at coding.

im also new at github so if editing my issue is a problem plz tell me

**Comment by MemeHovy** [comment]
you’ll know if there’s a source folder or not

**Comment by AshotlWotl** [comment]
> you’ll know if there’s a source folder or not

I dont. Im like extremely new at this. I have used psych engine before i had to do this stuff and when it was just an exe.

**Comment by AshotlWotl** [comment]
> > you’ll know if there’s a source folder or not
> 
> I dont. Im like extremely new at this. I have used psych engine before i had to do this stuff and when it was just an exe.

Nvm i got the info i needed from https://github.com/ShadowMario/FNF-PsychEngine/issues/11872
I wont close this yet as stuff is still installing

**Comment by MemeHovy** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/2fdcdfc0-2ecb-473f-afe2-97b3afd68d22)

learn to use github

**Comment by AshotlWotl** [comment]
i updated title

**Comment by Magniill** [comment]
bro doesn't know what "lime test windows" is 💀

**Comment by AshotlWotl** [comment]
> bro doesn't know what "lime test windows" is 💀

Im extremely new at this do i go into windows terminal and type lime test windows
