### ISSUE TITLE
I tried making the story menu buttons go in a row and...

### ISSUE THREAD

**Issue by Marioispro1** [ShadowMario/FNF-PsychEngine#13392]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/133698570/b60753f2-1f0b-4e3e-afe8-53891a4e29f1)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited StoryMenuState.hx and tried to make the buttons go in a row.

**Comment by MemeHovy** [comment]
show the code you modified

**Comment by Marioispro1** [comment]
I’ll do it later becauze of school

**Comment by Marioispro1** [comment]
`    override function create()
    {
        Paths.clearStoredMemory();
        Paths.clearUnusedMemory();

        PlayState.isStoryMode = true;
        WeekData.reloadWeekFiles(true);
        if(curWeek >= WeekData.weeksList.length) curWeek = 0;
        persistentUpdate = persistentDraw = true;

        scoreText = new FlxText(10, 10, 0, "SCORE: 49324858", 36);
        scoreText.setFormat("VCR OSD Mono", 32);

        txtWeekTitle = new FlxText(FlxG.width * 0.7, 10, 0, "", 32);
        txtWeekTitle.setFormat("VCR OSD Mono", 32, FlxColor.WHITE, RIGHT);
        txtWeekTitle.alpha = 0.7;

        var rankText:FlxText = new FlxText(0, 10);
        rankText.text = 'RANK: GREAT';
        rankText.setFormat(Paths.font("vcr.ttf"), 32);
        rankText.size = scoreText.size;
        rankText.screenCenter(X);

        var ui_tex = Paths.getSparrowAtlas('campaign_menu_UI_assets');
        var bgYellow:FlxSprite = new FlxSprite(0, 56).makeGraphic(FlxG.width, 386, 0xFFF9CF51);
        bgSprite = new FlxSprite(0, 56);

        grpWeekText = new FlxTypedGroup<MenuItem>();
        add(grpWeekText);

        var blackBarThingie:FlxSprite = new FlxSprite().makeGraphic(FlxG.width, 56, FlxColor.BLACK);
        add(blackBarThingie);

        grpWeekCharacters = new FlxTypedGroup<MenuCharacter>();

        grpLocks = new FlxTypedGroup<FlxSprite>();
        add(grpLocks);

        #if desktop
        // Updating Discord Rich Presence
        DiscordClient.changePresence("In the Menus", null);
        #end

        var num:Int = 0;
        var weekWidth:Float = (FlxG.width - 20) / loadedWeeks.length;

        for (i in 0...loadedWeeks.length)
        {
            var weekFile:WeekData = loadedWeeks[i];
            var isLocked:Bool = weekIsLocked(weekFile.fileName);

            if (!isLocked || !weekFile.hiddenUntilUnlocked)
            {
                var weekThing:MenuItem = new MenuItem(10 + weekWidth * num, bgSprite.y + 396, weekFile.fileName);
                grpWeekText.add(weekThing);

                weekThing.screenCenter(Y);

                if (isLocked)
                {
                    var lock:FlxSprite = new FlxSprite(weekThing.width + 10 + weekThing.x);
                    lock.antialiasing = ClientPrefs.data.antialiasing;
                    lock.frames = ui_tex;
                    lock.animation.addByPrefix('lock', 'lock');
                    lock.animation.play('lock');
                    lock.ID = i;
                    grpLocks.add(lock);
                }
                num++;
            }
        }

        var charArray:Array<String> = loadedWeeks[0].weekCharacters;
        for (char in 0...3)
        {
            var weekCharacterThing:MenuCharacter = new MenuCharacter((FlxG.width * 0.25) * (1 + char) - 150, charArray[char]);
            weekCharacterThing.y += 70;
            grpWeekCharacters.add(weekCharacterThing);
        }

        difficultySelectors = new FlxGroup();
        add(difficultySelectors);

        leftArrow = new FlxSprite(grpWeekText.members[0].x + grpWeekText.members[0].width + 10, grpWeekText.members[0].y + 10);
        leftArrow.antialiasing = ClientPrefs.data.antialiasing;
        leftArrow.frames = ui_tex;
        leftArrow.animation.addByPrefix('idle', "arrow left");
        leftArrow.animation.addByPrefix('press', "arrow push left");
        leftArrow.animation.play('idle');
        difficultySelectors.add(leftArrow);

        Difficulty.resetList();
        if(lastDifficultyName == '')
        {
            lastDifficultyName = Difficulty.getDefault();
        }
        curDifficulty = Math.round(Math.max(0, Difficulty.defaultList.indexOf(lastDifficultyName)));

        sprDifficulty = new FlxSprite(0, leftArrow.y);
        sprDifficulty.antialiasing = ClientPrefs.data.antialiasing;
        difficultySelectors.add(sprDifficulty);

        rightArrow = new FlxSprite(leftArrow.x + 376, leftArrow.y);
        rightArrow.antialiasing = ClientPrefs.data.antialiasing;
        rightArrow.frames = ui_tex;
        rightArrow.animation.addByPrefix('idle', 'arrow right');
        rightArrow.animation.addByPrefix('press', "arrow push right", 24, false);
        rightArrow.animation.play('idle');
        difficultySelectors.add(rightArrow);

        add(bgYellow);
        add(bgSprite);
        add(grpWeekCharacters);

        var tracksSprite:FlxSprite = new FlxSprite(FlxG.width * 0.07, bgSprite.y + 425).loadGraphic(Paths.image('Menu_Tracks'));
        tracksSprite.antialiasing = ClientPrefs.data.antialiasing;
        add(tracksSprite);

        txtTracklist = new FlxText(FlxG.width * 0.05, tracksSprite.y + 60, 0, "", 32);
        txtTracklist.alignment = CENTER;
        txtTracklist.font = rankText.font;
        txtTracklist.color = 0xFFe55777;
        add(txtTracklist);
        // add(rankText);
        add(scoreText);
        add(txtWeekTitle);

        changeWeek();
        changeDifficulty();

        super.create();
    }` mostly this
