### ISSUE TITLE
What do i do now

### ISSUE THREAD

**Issue by AshotlWotl** [ShadowMario/FNF-PsychEngine#13399]
### Describe your problem here.

So ive installed everything how do i open the game

I dont know if im modding with source or Lua

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

I don't think ive done anything just installed stuff

**Comment by MemeHovy** [comment]
don't make duplicate issues and stick with the one you've already made
