### ISSUE TITLE
/usr/bin/ld: cannot find -lvlccore: No such file or directory collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by CruzoPlayz** [ShadowMario/FNF-PsychEngine#13391]
### Describe your bug here.

all i did was use lime test linux and it gave me an error right after **Link:** ApplicationMain

### Command Prompt/Terminal logs (if existing)

```bash
/usr/bin/ld: cannot find -lvlccore: No such file or directory
collect2: error: ld returned 1 exit status
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I am only using the experimental version.

**Comment by mcagabe19** [comment]
u forget install ``libvlc-dev`` or ``libvlccore-dev``
