### ISSUE TITLE
Why I can't compile it?

### ISSUE THREAD

**Issue by XavierXP1** [ShadowMario/FNF-PsychEngine#13398]
### Describe your problem here.

It's showing this error message:

C:/HaxeToolkit/haxe/lib/SScript/4,1,0/src/tea/backend/SScriptVer.hx:23: characters 5-11 : Missing ;

But I already put ; What to do?

P.S. Here's the file if you can help me: [SScriptVer.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/12835201/SScriptVer.zip)

![Captura de Tela (25)](https://github.com/ShadowMario/FNF-PsychEngine/assets/91752998/253a0135-14a1-40bd-aa06-d761cd1f4e0d)
![Captura de Tela (26)](https://github.com/ShadowMario/FNF-PsychEngine/assets/91752998/13c018b9-c081-4204-9a09-d69b5abfb515)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited SScriptVer.hx. I put a .zip file if someone could help me.

**Comment by Red-Impostor** [comment]
try reinstalling SScript

**Comment by MemeHovy** [comment]
> try reinstalling SScript

no, 

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/124418090/9d511558-44e4-4a31-8595-38b0b8e6767d)

this shouldn't have ;

**Comment by MemeHovy** [comment]
please for the love of god learn to code @XavierXP1

**Comment by XavierXP1** [comment]
> please for the love of god learn to code @XavierXP1

T_T

Anyways, when I take out ; it still shows the same message " Missing ; "

What can I do?

**Comment by XavierXP1** [comment]
HERE'S THE PROOF:

![Captura de Tela (27)](https://github.com/ShadowMario/FNF-PsychEngine/assets/91752998/4cf0ad70-eada-47ff-a679-263a025e1013)
![Captura de Tela (28)](https://github.com/ShadowMario/FNF-PsychEngine/assets/91752998/adab2f0b-fef6-4153-ba6a-d7240f8db751)

**Comment by Red-Impostor** [comment]
> > try reinstalling SScript
> 
> no,
> 
> ![image](https://user-images.githubusercontent.com/124418090/273366489-9d511558-44e4-4a31-8595-38b0b8e6767d.png)
> 
> this shouldn't have ;

i know

**Comment by XavierXP1** [comment]
Ok, so what I can do to compile it if it shows this message?

**Comment by MemeHovy** [comment]
> Ok, so what I can do to compile it if it shows this message?

remove the checkVer function

**Comment by XavierXP1** [comment]
Fuck...it's getting worst and worst...now it showing this error:

![Captura de Tela (29)](https://github.com/ShadowMario/FNF-PsychEngine/assets/91752998/936fec06-e5e9-4659-b4b5-0a461d2c20f0)

**Comment by XavierXP1** [comment]
Nevermind, I did it! I also taked out the checkVer function on Macro.hx too. Thanks @MemeHovy, you're a life savior! lol
