### ISSUE TITLE
how do i change the color of the enemy bar for a custom character?

### ISSUE THREAD

**Issue by exiliph** [ShadowMario/FNF-PsychEngine#134]
idk how to di it and ive asked different people but they dont know

**Comment by FuseIsHere813** [comment]
change the RGB in the character JSON.

**Comment by ShadowMario** [comment]
Literally on the Character Editor

**Comment by ShadowMario** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/44785097/134820435-48bbb532-fd99-4f5c-8837-a0be0395481a.png)
Just to be sure that you've found it
