### ISSUE TITLE
Most mods crash on/During BFs turn

### ISSUE THREAD

**Issue by TheKAPtain313** [ShadowMario/FNF-PsychEngine#13402]
### Describe your bug here.

when i start playing on bfs side in the middle of the turn without warning it just crashes. It does not make a crash report either.

### Command Prompt/Terminal logs (if existing)

```bash
none
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i added some hud scripts but thats abt it.

**Comment by MemeHovy** [comment]
issues with the mods you have, not the engine
