### ISSUE TITLE
How the heck do you round a number????

### ISSUE THREAD

**Issue by DacroyleYT** [ShadowMario/FNF-PsychEngine#13403]
### Describe your problem here.

I want to find a way to round the health number, like this:
`math.round(getProperty('health') * 50)`
for some reason `math.round()` doesn't work, so what does?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MemeHovy** [comment]
there is no math.round in Lua, but you can do `math.floor(getProperty('health') * 50 + 0.5) / 50)`

**Comment by Lorekeeper49** [comment]
> there is no math.round in Lua, but you can do `math.floor(getProperty('health') * 50 + 0.5))`

I think `math.ceil()` exists too

**Comment by DacroyleYT** [comment]
> there is no math.round in Lua, but you can do `math.floor(getProperty('health') * 50 + 0.5))`

Thank you so much!!! It works :D
