### ISSUE TITLE
Remove the credits/easter egg for a known predator

### ISSUE THREAD

**Issue by Kiyoshi999** [ShadowMario/FNF-PsychEngine#13400]
### What feature do you want to get added on the **base** engine?

Most people know by this point that Yoshubs is a pedophile, so why are they still credited within the engine? Why do they still have an easter egg within the engine? These are truly questions for the ages.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MemeHovy** [comment]
shadowmario never got to removing her credit

**Comment by MemeHovy** [comment]
@Kiyoshi999 I made a PR for this that removes her from the engine entirely

**Comment by crowplexus** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/45212377/8726e06b-34b4-41d9-b79f-8d12692a3609)

**Comment by Kiyoshi999** [comment]
alright, I'm satisfied with that.
