### ISSUE TITLE
I can't compile my mod

### ISSUE THREAD

**Issue by Lolsansy33** [ShadowMario/FNF-PsychEngine#13407]
### Describe your problem here.

I want to compile my mod, but it's keeps saying to me this:
lime : The term 'lime' is not recognized as the name of a cmdlet, function, script file, or executable program.
Check whether you typed the name correctly or, if you included a path, check that the path is correct and
Try again.
Online: 1 Character: 1
+ lime test windows
+ ~~~~
    + CategoryInfo : ObjectNotFound: (lime:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    That's weird because i have lime 8.0.1 installed

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MooManisLoud** [comment]
What haxe and psych engine version are you using?

**Comment by Magniill** [comment]
if you are using older or newer versions of haxe instead of the 4.2.5 version, YOURE AN IDIOT FOR NOT READING THE COMPILE INSTRUCTIONS!

**Comment by Username2120** [comment]
this happened to me and i just reinstalled lime and it worked again, not sure why it even happened but hopefully that helps.

**Comment by Lolsansy33** [comment]
i have the 4.2.5 version, i read the compile instructions
