### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by fnfusermood** [ShadowMario/FNF-PsychEngine#13408]
### Describe your bug here.

Engine crashes and it says, Null Object Refrence

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added Double Kill Cover.

**Comment by Username2120** [comment]
some object in the code is returning null when its not supposed to. thats the best i can give you, youll need to provide more info.

**Comment by fnfusermood** [comment]
Thank you, i've already solved it, but thank you for telling me cause of the issue.
