### ISSUE TITLE
Editable idle note colors.

### ISSUE THREAD

**Issue by wj1ajao39sjak927** [ShadowMario/FNF-PsychEngine#13401]
### What feature do you want to get added on the **base** engine?

Since versions 0.7X has a revamped note colors menu (where you can now freely edit the note colors), I was thinking that you should be able to edit the idle note colors (shown below) too.
![Idle notes](https://github.com/ShadowMario/FNF-PsychEngine/assets/147216891/eb0b5072-20c3-4537-acc5-6b277bb57106)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by crowplexus** [comment]
those notes aren't editable mainly because you were supposed to replace those with noteskins, making the extra functionality would take quite an expensive amount of time + would be useless as noteskins are already added

**Comment by wj1ajao39sjak927** [comment]
Makes sense.On Oct 8, 2023, at 2:17 AM, Crow ***@***.***> wrote:﻿
those notes aren't editable mainly because you were supposed to replace those with noteskins, making the extra functionality would take quite an expensive amount of time + would be useless as noteskins are already added

**Comment by wj1ajao39sjak927** [comment]
Close the issue I guess.On Oct 8, 2023, at 9:19 AM, tgtfan392 ***@***.***> wrote:﻿Makes sense.On Oct 8, 2023, at 2:17 AM, Crow ***@***.***> wrote:﻿
those notes aren't editable mainly because you were supposed to replace those with noteskins, making the extra functionality would take quite an expensive amount of time + would be useless as noteskins are already added

**Comment by wj1ajao39sjak927** [comment]
Yeah it would take too much time. I could try coding it in myself but again, it's too much work.On Oct 8, 2023, at 9:19 AM, tgtfan392 ***@***.***> wrote:﻿Makes sense.On Oct 8, 2023, at 2:17 AM, Crow ***@***.***> wrote:﻿
those notes aren't editable mainly because you were supposed to replace those with noteskins, making the extra functionality would take quite an expensive amount of time + would be useless as noteskins are already added

**Comment by wj1ajao39sjak927** [comment]
Should I try modding from source?On Oct 8, 2023, at 9:19 AM, tgtfan392 ***@***.***> wrote:﻿Makes sense.On Oct 8, 2023, at 2:17 AM, Crow ***@***.***> wrote:﻿
those notes aren't editable mainly because you were supposed to replace those with noteskins, making the extra functionality would take quite an expensive amount of time + would be useless as noteskins are already added

**Comment by wj1ajao39sjak927** [comment]
You do have a point, though.

**Comment by wj1ajao39sjak927** [comment]
Should the issue be closed?
