### ISSUE TITLE
stupid psychengine wont compile correctly cuz the main.hx gives me errors

### ISSUE THREAD

**Issue by coxxie286** [ShadowMario/FNF-PsychEngine#13404]
### Describe your problem here.

la error is:
source/Main.hx:14: characters 8-25 : Type not found : states.TitleState
source/Main.hx:89: characters 19-22 : Type not found : Lua
source/Main.hx:90: characters 12-20 : Class<Controls> has no field instance
source/Main.hx:90: characters 23-37 : Not enough arguments, expected name:String, scheme:KeyboardScheme
source/Main.hx:100: characters 33-37 : Class<ClientPrefs> has no field data
source/Main.hx:154: characters 21-28 : String has no field replace
source/Main.hx:155: characters 21-28 : String has no field replace
source/Main.hx:181: characters 3-16 : Type not found : DiscordClient
source/Main.hx:119: characters 3-16 : Type not found : DiscordClient
source/Main.hx:123: characters 3-7 : Type not found : FlxG

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no sirrebob

**Comment by MemeHovy** [comment]
remove states. in initialState

**Comment by coxxie286** [comment]
where exactly..?

**Comment by MemeHovy** [comment]
here, replace all your imports in main.hx with these ```haxe
package;

import flixel.graphics.FlxGraphic;
import flixel.FlxG;
import flixel.FlxGame;
import flixel.FlxState;
import openfl.Assets;
import openfl.Lib;
import openfl.display.FPS;
import openfl.display.Sprite;
import openfl.events.Event;
import openfl.display.StageScaleMode;
import lime.app.Application;

#if desktop
import Discord.DiscordClient;
#end

//crash handler stuff
#if CRASH_HANDLER
import openfl.events.UncaughtErrorEvent;
import haxe.CallStack;
import haxe.io.Path;
import sys.FileSystem;
import sys.io.File;
import sys.io.Process;
#end

using StringTools;
```

**Comment by MemeHovy** [comment]
and don't paste 0.7 code into your mod unless you know what you're doing

**Comment by coxxie286** [comment]
ok so it did fix some errors but there are still some errors,
the errors i got are:
source/Main.hx:90: characters 19-22 : Type not found : Lua
source/Main.hx:91: characters 12-20 : Class<Controls> has no field instance
source/Main.hx:91: characters 23-37 : Not enough arguments, expected name:String, scheme:KeyboardScheme
source/Main.hx:101: characters 33-37 : Class<ClientPrefs> has no field data
source/Main.hx:120: characters 17-22 : Class<DiscordClient> has no field start

**Comment by coxxie286** [comment]
> and don't paste 0.7 code into your mod unless you know what you're doing

any ideas?
