### ISSUE TITLE
How to use a video as a stage?

### ISSUE THREAD

**Issue by wj1ajao39sjak927** [ShadowMario/FNF-PsychEngine#13410]
### What is your question?

How do you use a video as a stage/background in a song?

**Comment by wj1ajao39sjak927** [comment]
Also, can you only do it with source or can you also do it with Lua?

**Comment by Magniill** [comment]
turn it into a spritesheet. there currently is no way to use .mp4's as stages.

**Comment by wj1ajao39sjak927** [comment]
So you actually need to make it as a spritesheet, and do you need an XML for it too?

**Comment by wj1ajao39sjak927** [comment]
Actually yeah, you would definitely need an XML. I'll close the issue from here.
