### ISSUE TITLE
Notes with a Smaller Hit Window

### ISSUE THREAD

**Issue by Bielhero-Oficial** [ShadowMario/FNF-PsychEngine#13418]
### Describe your problem here.

So, i wanted to do a Instant Death Note, but i wanted to make it with a smaller hit window to make it easier to not click on it, so that the sections could have more of it, the way it would work is like the default Hurt Note that is already on the engine, i tried look for the code on the files or the string that could make a small hit window but i wasn't able to find it, if you guys know how to it would help a lot. Thanks.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
```lua
setPropertyFromGroup('unspawnNotes', i, 'earlyHitMult', 1)
setPropertyFromGroup('unspawnNotes', i, 'lateHitMult', 1)
```

**Comment by Bielhero-Oficial** [comment]
Sorry if I am being annoying asking this, but i am a beginner at coding, so Ive been trying for the last 20 mins and i cant make a code that can stop the note to register inputs and only check for inputs in a certing value. If someone can help me do this it would help a lot. But thanks anyway for the code, it's a shame that im to dumb to know how to use it.
