### ISSUE TITLE
how to disable note colors

### ISSUE THREAD

**Issue by jengahh** [ShadowMario/FNF-PsychEngine#13413]
### What is your question?

this build in change note colors function are mess up my custom note skin (it brighter )
is there any way to make it normal 
and ofc i dont want to change my note skin coloring to make it work with this thing
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/87862624/d6b58e67-f31d-4b70-9fa3-1ca3d392f399)

**Comment by wj1ajao39sjak927** [comment]
I don't really know how to do that. Also that's a cool noteskin. Can I download it?

**Comment by Magniill** [comment]
you could disable this option feature by just removing the selection, don't really recommend tho.
