### ISSUE TITLE
Uhhhhh I'm not really sure about what I'm supposed to do here.

### ISSUE THREAD

**Issue by Macaroni262** [ShadowMario/FNF-PsychEngine#13420]
![Error thing](https://github.com/ShadowMario/FNF-PsychEngine/assets/138635463/9d25a8e8-f96f-4de2-8d7b-6ac1c1e9ecea)

Compiling Error that I'm not really sure what to do with.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

The only thing I did was change HScript to TeaScript.

**Comment by NexIsDumb** [comment]
Tried to run [setup-windows.bat](https://github.com/ShadowMario/FNF-PsychEngine/blob/experimental/setup/setup-windows.bat) (or if youre on mac / linux: [setup-unix.sh](https://github.com/ShadowMario/FNF-PsychEngine/blob/experimental/setup/setup-unix.sh))?
They both can be found in the setup folder
