### ISSUE TITLE
How do I use images as a health bar

### ISSUE THREAD

**Issue by SageTheDumbBlob** [ShadowMario/FNF-PsychEngine#13427]
### Describe your problem here.

I can't understand how to hell to do this, kinda needing help on that one.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/147659029/788f7b65-0c12-477e-9ae7-21d3aea34868)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Fellegend** [comment]
idk. sry. i think you need to make PNG files with these names. or else i think its only build but idk. im really sorry about it.

**Comment by NexIsDumb** [comment]
sure
PS: the image file must be ofc in png and put this code under the `onCreatePost()` function

```lua
runHaxeCode([[
    game.healthBar.bg.loadGraphic(Paths.image('[YOUR IMAGE FILEPATH HERE]'));
    game.healthBar.leftBar.loadGraphic(Paths.image('[YOUR IMAGE FILEPATH HERE]'));
    game.healthBar.rightBar.loadGraphic(Paths.image('ui/coloredBar'));
    game.healthBar.barWidth = Std.int(game.healthBar.bg.width);
    game.healthBar.barHeight = Std.int(game.healthBar.bg.height);
]])
```

**Comment by SageTheDumbBlob** [comment]
thanks mate

**Comment by NexIsDumb** [comment]
> thanks mate

worked?

**Comment by SageTheDumbBlob** [comment]
Sure as hell did

**Comment by NexIsDumb** [comment]
> Sure as hell did

great
glad im helped
you should close this issue as completed now, it'd help thx

**Comment by ZeonPlay** [comment]
This is for 0.6 or 0.7?
