### ISSUE TITLE
why

### ISSUE THREAD

**Issue by JohnDoe3453** [ShadowMario/FNF-PsychEngine#13424]
### Describe your bug here.

im following this tutorial to make a mod in fnf https://www.youtube.com/watch?v=4IuC8ti6_4o
but then in 8:50 i put "lime test windows" and it gives me an error

### Command Prompt/Terminal logs (if existing)

```bash
PS D:\FNF-PsychEngine-main> lime test windows
source/psychlua/HScript.hx:168: characters 89-94 : Type not found : SCall
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i not

**Comment by CaptainBaldi** [comment]
look at one of the dozen other issues about this

**Comment by JohnDoe3453** [comment]
ok

**Comment by JohnDoe3453** [comment]
i found some stuff: #13383

**Comment by JohnDoe3453** [comment]
and its getting worse
C:/HaxeToolkit/haxe/lib/SScript/4,1,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.

**Comment by Magniill** [comment]
are you using the main branch? use the experimental branch, then rerun everything.

**Comment by JohnDoe3453** [comment]
im on experimental

**Comment by NexIsDumb** [comment]
> im on experimental

dont follow that tutorial its old af
psych recently updated their setup method in the experimental, and since you want to use the experimental branch this is your case: tried to run [setup-windows.bat](https://github.com/ShadowMario/FNF-PsychEngine/blob/experimental/setup/setup-windows.bat) (or if youre on mac / linux: [setup-unix.sh](https://github.com/ShadowMario/FNF-PsychEngine/blob/experimental/setup/setup-unix.sh))?

**Comment by JohnDoe3453** [comment]
ok

god now i have to uninstall haxe lmao

**Comment by NexIsDumb** [comment]
> ok
> 
> 
> 
> god now i have to uninstall haxe lmao

huh why
what version do u have it on?

**Comment by JohnDoe3453** [comment]
4.2.5 ive installed it a lot of shit

**Comment by NexIsDumb** [comment]
did you install git aswell?

**Comment by JohnDoe3453** [comment]
ye

**Comment by NexIsDumb** [comment]
also that version of haxe is fine

**Comment by NexIsDumb** [comment]
> ye

then try to compile now

**Comment by JohnDoe3453** [comment]
ok

**Comment by NexIsDumb** [comment]
alr im gonna check this issue in a bunch of hours since now i gtg
continue to update me tho

**Comment by JohnDoe3453** [comment]
ok

**Comment by JohnDoe3453** [comment]
bro its not detecting lime

**Comment by JohnDoe3453** [comment]
well ._.

C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
D:\FNF-PsychEngine-experimental\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by NexIsDumb** [comment]
> well ._.
> 
> 
> 
> C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
> 
> D:\FNF-PsychEngine-experimental\export\release\windows\obj>setlocal enabledelayedexpansion
> 
> Warning: Could not find Visual Studio VsDevCmd
> 
> Missing HXCPP_VARS
> 
> Error: Could not automatically setup MSVC

do you see in the source folder an exe?
(should have downloaded in the final part of the setup)

**Comment by JohnDoe3453** [comment]
no, i dont see a.exe

**Comment by NexIsDumb** [comment]
> no, i dont see a.exe

so thats why
are you on windows?

**Comment by NexIsDumb** [comment]
oh yes you are just saw
then do this:
download this [file](https://download.visualstudio.microsoft.com/download/pr/3105fcfe-e771-41d6-9a1c-fc971e7d03a7/8eb13958dc429a6e6f7e0d6704d43a55f18d02a253608351b6bf6723ffdaf24e/vs_Community.exe) and put it in the folder of where you downloaded psych's repository
and then run a command prompt on that folder: `vs_Community.exe --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.19041 -p`

**Comment by JohnDoe3453** [comment]
it dosent detect it

seriously i placed the file in the folder

**Comment by NexIsDumb** [comment]
> it dosent detect it
> 
> seriously i placed the file in the folder

hm, okay then execute that .exe, don't click on any of the options to install workloads but instead go to the individual components tab and choose the following:

- MSVC v142 - VS 2019 C++ x64/x86 build tools (Latest)
- Windows 10 SDK (10.0.17763.0)

(ps its gonna take 4gb of space)

**Comment by JohnDoe3453** [comment]
one question: if im on windows 11 then i need to install windows 11 sdk?

**Comment by NexIsDumb** [comment]
nop u dont need to
im on w11 aswell if u want to know

**Comment by JohnDoe3453** [comment]
ok

**Comment by JohnDoe3453** [comment]
done, now what?

**Comment by NexIsDumb** [comment]
> done, now what?

try to compile now (lime test windows)

**Comment by JohnDoe3453** [comment]
uuhhh

C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
D:\FNF-PsychEngine-experimental\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by NexIsDumb** [comment]
> uuhhh
> 
> 
> 
> C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
> 
> D:\FNF-PsychEngine-experimental\export\release\windows\obj>setlocal enabledelayedexpansion
> 
> Warning: Could not find Visual Studio VsDevCmd
> 
> Missing HXCPP_VARS
> 
> Error: Could not automatically setup MSVC

wtf theres clearly something wrong in all of this, why cant it detect vsc??
hm at this point follow those psych installations tutorial you can find on youtube, but just the part where it installs the vsc component and tell me how it goes

**Comment by JohnDoe3453** [comment]
ok

**Comment by JohnDoe3453** [comment]
i think i know why is it fail

bcuz i installed the repo in A USB

so im gonna move into my ssd

**Comment by NexIsDumb** [comment]
> i think i know why is it fail
> 
> 
> 
> bcuz i installed the repo in A USB
> 
> 
> 
> so im gonna move into my ssd

hm i never actually tried that but i dont think thats the problem
try it though

**Comment by JohnDoe3453** [comment]
ok

but im gonna open the folder with visual studio

**Comment by JohnDoe3453** [comment]
ok i did and it gives me the same error

**Comment by JohnDoe3453** [comment]
https://www.bing.com/videos/riverview/relatedvideo?q=compile+psych+engine&mid=863EC200ECB9439984AD863EC200ECB9439984AD&FORM=VIRE

im gona follow this video

**Comment by NexIsDumb** [comment]
> https://www.bing.com/videos/riverview/relatedvideo?q=compile+psych+engine&mid=863EC200ECB9439984AD863EC200ECB9439984AD&FORM=VIRE
> 
> im gona follow this video

alr

**Comment by NexIsDumb** [comment]
remember though, just the vsc part

**Comment by JohnDoe3453** [comment]
YOOOOO I DID IT

**Comment by JohnDoe3453** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/146678984/ee107c19-9e15-48b1-9de9-eb671f64523b)

**Comment by NexIsDumb** [comment]
greatt :p

**Comment by NexIsDumb** [comment]
if you can put this issue as completed would be great

**Comment by JohnDoe3453** [comment]
ok finally

**Comment by dancingshadow1235** [comment]
how do i fix this  C:/HaxeToolkit/haxe/lib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available ive been trying to follow lots of methods but they dont work
