### ISSUE TITLE
Editable Menus/more accessible menus (NON SOURCE BUILDS)

### ISSUE THREAD

**Issue by RushMyster** [ShadowMario/FNF-PsychEngine#13421]
### What feature do you want to get added on the **base** engine?

PLs Make the menus more customizable in non source builds, i dont want anything crazy just pls let me put images in like the title screen and main menu, maybe a menu editor?? 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CaptainBaldi** [comment]
no

**Comment by Magniill** [comment]
no

**Comment by crowplexus** [comment]
this was requested many times and the answer will remain the same: no.

psych is not meant to have extreme modability, just some form of balance between modding meant for smaller projects and being able to STILL use the source code.
