### ISSUE TITLE
how do i make a custom freeplay and main menu without haxe

### ISSUE THREAD

**Issue by aydenxml123456** [ShadowMario/FNF-PsychEngine#13428]
### Describe your problem here.

I use psych engine(NOT SORCE CODE) and I wanted to have a custom main menu and freeplay menu for my mod 
if there's any way to do so please let me know also I wanted to know id there's a way to add a cutscene before the title screen with haxe

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Ozofearlez** [comment]
I dont think thats possible, ive been trying to figure that out myself, and all ive found is source code, but if you were restyling the menu, you could just use your art program, just not rearrange it

**Comment by Chidubemmo** [comment]
You can't (unless you just want to restyle while maintaing the positions the same)

**Comment by Martinelplayz** [comment]
well "technically" you could turn a song into a menu by preventing the song from actually starting in the first place, hiding the arrows, and coding a menu from scratch.

**Comment by Chidubemmo** [comment]
Yeah but they want to remak FREEPLAY and STORY MODE. Which aren't affected by lua

**Comment by FranciscoPlay32** [comment]
scripts only affect songs so
