### ISSUE TITLE
Note Dodge

### ISSUE THREAD

**Issue by Missa13** [ShadowMario/FNF-PsychEngine#1342]
### Describe your problem here.

Does anyone have When you touch the arrow do you dodge it like a bullet oh a hit?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Collabvmisgood** [comment]
# Lua
Put this in your note lua
`function goodNoteHit(id, noteData, noteType, isSustainNote)`
	`if noteType == 'D Note' then`
	`end`
`end`
Then add:
`characterPlayAnim('boyfriend', 'dodge', true);`

**Comment by DEV-idiotXD** [comment]
if noteType == 'notename'


function goodNoteHit(id, noteData, noteType, isSustainNote)
	characterPlayAnim('boyfriend', 'dodge', true)
end


end

**Comment by Collabvmisgood** [comment]
that is good to

**Comment by DEV-idiotXD** [comment]
> that is good to

put everything under if notetype == 'notename'

why? soo u dont need to c and pate;
if notetype == 'notename' then

**Comment by Collabvmisgood** [comment]
> > that is good to
> 
> put everything under if notetype == 'notename'
> 
> why? soo u dont need to c and paste; if notetype == 'notename' then

You are helpfull thanks this will help me to!

**Comment by DEV-idiotXD** [comment]
> > > that is good to
> > 
> > 
> > put everything under if notetype == 'notename'
> > why? soo u dont need to c and paste; if notetype == 'notename' then
> 
> You are helpfull thanks this will help me to!

np

**Comment by Missa13** [comment]
I do not understand

**Comment by DEV-idiotXD** [comment]
> # Lua
> Put this in your note lua
> 
> ```lua
> if noteType == 'notename' then
> function goodNoteHit(id, noteData, noteType, isSustainNote)
> 	end
> end
> ```
> 
> Then add:
> 
> ```lua
> characterPlayAnim('boyfriend', 'dodge', true);
> ```
> 
> So it will be like this:
> 
> ```lua
> if noteType == 'notename' then
> function goodNoteHit(id, noteData, noteType, isSustainNote)
>             characterPlayAnim('boyfriend', 'dodge', true);
>    end
> 
> end
> ```
> 
> ![image](https://user-images.githubusercontent.com/76410593/143375653-4990ef6b-ef14-4b07-a0ca-e6145614bdd1.png) This is a better idea
> 
> > > that is good to
> > 
> > 
> > put everything under if notetype == 'notename'
> > why? soo u dont need to c and paste; if notetype == 'notename' then
> 
> DEV-idiot is nice

thx

**Comment by ShadowMario** [comment]
This github repo is NOT made for asking for code pieces from other people.
