### ISSUE TITLE
cutscenes on mac port

### ISSUE THREAD

**Issue by Yohjihappy** [ShadowMario/FNF-PsychEngine#13430]
### What feature do you want to get added on the **base** engine?

i just want cutscenes on mac port (and maybe re-add previous mac ports) thats it, thx

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by NexIsDumb** [comment]
well this is not psych fault
you see psych uses a library for cutscene and that library (hxCodec) doesn't still fully work with mac
so you should report this in the hxCodec actual server / repository

**Comment by ShadowMario** [comment]
Can't do.
