### ISSUE TITLE
How to make mutliple characters in FNF how like fnf twinsomnia on Source Code

### ISSUE THREAD

**Issue by Mlaofmd** [ShadowMario/FNF-PsychEngine#13431]
### What is your question?

please ask im dumb

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/52864321/0921b6f6-37ff-4ca1-8ff8-6fda2821e72a)

**Comment by Mlaofmd** [comment]
> 1. make multiple characters on a single spritesheet
> 2. use hscript (specifically the nehind dad one)

i SAID on source code

**Comment by s-h-i-f-t-y-z** [comment]
well learn haxe then

**Comment by SrBagel** [comment]
You can't just use Gf as another character?

**Comment by Mlaofmd** [comment]
> You can't just use Gf as another character?

no i just need not use gf, just 2 opponents

**Comment by Chidubemmo** [comment]
You can try copying the opponent (dad)'s code in PlaysState and Chartingstate and then modify it

**Comment by Stefan2008Git** [comment]
> You can try copying the opponent (dad)'s code in PlaysState and Chartingstate and then modify it

And he needs to modify Character.hx to work too
