### ISSUE TITLE
How do non RGB notes?

### ISSUE THREAD

**Issue by Yohjihappy** [ShadowMario/FNF-PsychEngine#13437]
### What feature do you want to get added on the **base** engine?

I need help with making notes, how do i make notes withour RGB like bullet notes but not colorful, or the hurt note?

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by s-h-i-f-t-y-z** [comment]
copy the xml of hurt notes and edit it

**Comment by Yohjihappy** [comment]
i dont know where the hurt note is

**Comment by SrBagel** [comment]
Make this a question not an enhancement

**Comment by Yohjihappy** [comment]
how?

**Comment by BernardoGP4504** [comment]
Just set `rgbShader.enabled` to false

**Comment by Yohjihappy** [comment]
thx

**Comment by Yohjihappy** [comment]
> Just set `rgbShader.enabled` to false

do i use "setProperty('rgbShader.enabled', false);"?
