### ISSUE TITLE
I was banned from the psych engine server, in my description, I had put my age wrong.

### ISSUE THREAD

**Issue by pablowolfgamerbr** [ShadowMario/FNF-PsychEngine#13438]
### Describe your problem here.

Can someone put me on the server again? I put my age wrong in my description on my discord profile.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by s-h-i-f-t-y-z** [comment]
wuts ur username i can prolly try and appeal for you

**Comment by pablowolfgamerbr** [comment]
ok 

My userName: phrgamerbr1692
