### ISSUE TITLE
song.

### ISSUE THREAD

**Issue by ElInsanoFNF** [ShadowMario/FNF-PsychEngine#13434]
### What needs to be documented?

I have a json of my music that I am making, but I get this error, and I don't think it is such a serious error.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/147748055/d824880d-f616-46d9-89d9-636cf4985884)

**Comment by NexIsDumb** [comment]
what version are you using?
and label this issue as a bug instead of documentation
that crash might happen because your chart wasn't well done

**Comment by NexIsDumb** [comment]
also send a screenshot of the json name and where you placed it cause it could also be that the game just didn't find it (if the version is before than 0.7)

**Comment by matepro260** [comment]
you are doing this is source?
