### ISSUE TITLE
wtf did i do

### ISSUE THREAD

**Issue by VillianousJ0ker** [ShadowMario/FNF-PsychEngine#13432]
### Describe your bug here.

i got a crash loading into freeplay that just stated

states/FreeplayState.hx (line 71)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

so uh.. wtf does this mean.. :D 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i dont actually fucking know.

**Comment by NexIsDumb** [comment]
were you trying to make a custom build? like you edited any files in the source?

**Comment by NexIsDumb** [comment]
or since that line is related to week files
did you edit / delete any week file?

**Comment by VillianousJ0ker** [comment]
I don't think I did, I'll def check tho.
