### ISSUE TITLE
Error Shader in Freeplay

### ISSUE THREAD

**Issue by TheRoZiLLa** [ShadowMario/FNF-PsychEngine#13444]
### Describe your problem here.

source/flixel/addons/display/FlxRuntimeShader.hx:210: Loading fragment source from argument...
source/flixel/addons/display/FlxRuntimeShader.hx:532: [WARN] Shader float property iTime not found.
source/FreeplayState.hx:988: Going down: 0
source/flixel/addons/display/FlxRuntimeShader.hx:643: [WARN] Shader float property iTime not found.
source/flixel/addons/display/FlxRuntimeShader.hx:532: [WARN] Shader float property iTime not found.
flixel/graphics/tile/FlxDrawQuadsItem.hx (line 119)
flixel/FlxCamera.hx (line 683)
flixel/FlxGame.hx (line 870)
flixel/FlxGame.hx (line 558)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Freeplay.hx and shader.hx

**Comment by Stefan2008Git** [comment]
You can't use "`Paths.clearStoredMemory()`" and "`Paths.clearUnusedMemoy()`" for shaders

**Comment by TheRoZiLLa** [comment]
what should i do?

**Comment by Stefan2008Git** [comment]
Ah, sorry. I didn't even coded for shader

**Comment by TheRoZiLLa** [comment]
ok
