### ISSUE TITLE
Video/Audio sync calibrator

### ISSUE THREAD

**Issue by TheRealPepsi** [ShadowMario/FNF-PsychEngine#13441]
### What feature do you want to get added on the **base** engine?

Hey all, had an idea, what about syncing video and audio seperately? perhaps a calibrator tool as well, like how Clone Hero does it? I think that would be quite handy, in my opinion

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
I never played Clone Hero so idk what you mean
