### ISSUE TITLE
Scripting error

### ISSUE THREAD

**Issue by N0m0ph0bia** [ShadowMario/FNF-PsychEngine#13440]
### Describe your bug here.

Im not really sure what section this should go in but i guess this is considered a bug.

but anyway,

The script you can use for 0.7.1.H can be used for 0.6.3 but 0.6.3 scripts cannot be used for 0.7.1h

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I have no edited anything in the build

**Comment by CaptainBaldi** [comment]
this is such a dumb issue.
0.7 rewrote many aspects of the game, therefore certain aspects in 0.6.3 scripts will not work in 0.7.
Not a bug, get better and fix your scripts

**Comment by N0m0ph0bia** [comment]
> this is such a dumb issue. 0.7 rewrote many aspects of the game, therefore certain aspects in 0.6.3 scripts will not work in 0.7. Not a bug, get better and fix your scripts

Like I said I didn't know where to put it
