### ISSUE TITLE
Lime Test windows error

### ISSUE THREAD

**Issue by TheProCreator41** [ShadowMario/FNF-PsychEngine#13456]
### Describe your bug here.

Good afternoon or evening.... I want to report an engine build bug, basically when I run Lime Test Windows I get this:

![Captura de pantalla (ficics error)](https://github.com/ShadowMario/FNF-PsychEngine/assets/148003126/cdaa8265-066f-474d-b78b-4369946fdd58)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheProCreator41** [comment]
until I reinstall Haxe to version 4.2.5

**Comment by GAMERMEER** [comment]
> until I reinstall Haxe to version 4.2.5

dude shadowmario said in the repo that we need to stop using that version we need to use the latest version of haxe

**Comment by GAMERMEER** [comment]
or not it has changed
