### ISSUE TITLE
Error in psych engine while playing one of the mods

### ISSUE THREAD

**Issue by Kamix13** [ShadowMario/FNF-PsychEngine#13458]
### Describe your bug here.

states/PlayState.hx (line 2655)
states/PlayState.hx (line 2588) openfl/events/EventDispatcher.hx (line 402) openfl/display/DisplayObject.hx (line 1399)
Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine
> Crash Handler written by: sqirra-rng
![Zrzut ekranu 2023-10-16 204209](https://github.com/ShadowMario/FNF-PsychEngine/assets/136904448/d5384804-7252-44dc-90aa-1eb4062dce78)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, I didn't, I was playing a mod made by someone else already that I added to "mod" folder in the engines files

**Comment by NexIsDumb** [comment]
its not psych fault
its the mod developer fault, don't report this here
