### ISSUE TITLE
CreditsState.hx error

### ISSUE THREAD

**Issue by FrogB** [ShadowMario/FNF-PsychEngine#13454]
### Describe your problem here.

Got the following error while trying to modify credits state.

CreditsState.hx (line 314) <-- function  getCurrentBGColor();
CreditsState.hx (line 157) <-- bg.color =  getCurrentBGColor();
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 550)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

any fixes?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Mlaofmd** [comment]
hxcpp broken or idk

**Comment by FrogB** [comment]
Nevermind I found out the issue, apparently I mistyped one of the color hex
codes.
