### ISSUE TITLE
Type not found

### ISSUE THREAD

**Issue by XiaoQing114514** [ShadowMario/FNF-PsychEngine#13453]
### Describe your problem here.

source/objects/Note.hx:28: characters 4-12 : Type not found : FlxColor
source/states/TitleState.hx:42: characters 26-40 : Type not found : MusicBeatState

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Mlaofmd** [comment]
you can show your lua code?

**Comment by XiaoQing114514** [comment]
> 您可以出示您的 Lua 代码吗？

I don't have any Lua code, I'm just packaging the Psych Engine without any modifications
