### ISSUE TITLE
(im back lol) frame repeating

### ISSUE THREAD

**Issue by GMan2006i** [ShadowMario/FNF-PsychEngine#1345]
### What is your question?

okay so in shaggy mod on god eater sometimes the shagg will leave behide the previous sing frame with like half opacity

if anybody has any ideas on how to do this that would be very epic
(I know this post is way less quality than the previous, but im tired its like 11 pm when im writing this)

**Comment by ShadowMario** [comment]
https://api.haxeflixel.com/flixel/addons/effects/FlxTrail.html
Same thing as Spirit on school-evil stage.

**Comment by GMan2006i** [comment]
can this be achieved without changing the source? aka using a build version
