### ISSUE TITLE
hscript errors or something

### ISSUE THREAD

**Issue by L044washere** [ShadowMario/FNF-PsychEngine#13461]
### Describe your problem here.

hi. so i got a compile error and i don't know how to fix it.

`source/psychlua/HScript.hx:42: characters 22-27 : Too many arguments`
`source/psychlua/HScript.hx:38: lines 38-50 : Missing super constructor call`

can someone pls help me?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope, just started compiling for the first time (except removing the ReturnValue from the "funk.hscript" in HScript.hx)

**Comment by fnfusermood** [comment]
sorry having the same issue too

**Comment by L044washere** [comment]
fixed it

**Comment by Galaxie6** [comment]
HOW did you fix it dont just say fixed it
