### ISSUE TITLE
how do i turn off the cam boom where it randomly zooms in the song

### ISSUE THREAD

**Issue by jack-dutchie** [ShadowMario/FNF-PsychEngine#13463]
### Describe your problem here.

i want to turn of the random zooms during songs

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by BernardoGP4504** [comment]
just use `setProperty('camZooming', false)`

**Comment by jack-dutchie** [comment]
> just use `setProperty('camZooming', false)`

it worked but my song has camera zooming in scripts and chart and when the event does it thing then my camera zooms in but doesnt go back so it did work but the other zooms broke it

**Comment by BernardoGP4504** [comment]
> > just use `setProperty('camZooming', false)`
> 
> it worked but my song has camera zooming in scripts and chart and when the event does it thing then my camera zooms in but doesnt go back so it did work but the other zooms broke it

Simply turn it back to true before any events that do that zoom again, after the event is done, set it back to false

**Comment by jack-dutchie** [comment]
> > > just use `setProperty('camZooming', false)`
> > 
> > 
> > it worked but my song has camera zooming in scripts and chart and when the event does it thing then my camera zooms in but doesnt go back so it did work but the other zooms broke it
> 
> Simply turn it back to true before any events that do that zoom again, after the event is done, set it back to false

oh ok

**Comment by BernardoGP4504** [comment]
> > Simply turn it back to true before any events that do that zoom again, after the event is done, set it back to false
> 
> oh ok

Did it work? If so, close the issue.
