### ISSUE TITLE
Custom NoteType.txt

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#13464]
### What needs to be documented?

There's no documentation on how to use `.txt` files to make a custom notetype in 0.7.x or above. I've even looked at the source code but no answers were there

**Comment by CaptainBaldi** [comment]
make a txt file with the notetype name
in it, you can set properties you would find in `Note.hx`
Such as
```
rgbShader.enabled = false
multSpeed = 5
```

**Comment by BernardoGP4504** [comment]
I've been testing fields but almost none of them seem to be accessible by the script

**Comment by CaptainBaldi** [comment]
> I've been testing fields but almost none of them seem to be accessible by the script

ive done some testing myself and it seems to work fine

**Comment by BernardoGP4504** [comment]
Ok then, thanks!
