### ISSUE TITLE
I have a problem with changing characters i made in the character editor

### ISSUE THREAD

**Issue by Matnimations11** [ShadowMario/FNF-PsychEngine#13474]
### Describe your problem here.

So when i press 7 in a song and change to a character that i made in the character editor and when i click enter this pops up.
![Zrzut ekranu (286)](https://github.com/ShadowMario/FNF-PsychEngine/assets/148543237/cc20611e-3c9e-40be-91bc-6c60cb8eebc4)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Username2120** [comment]
this means that for some reason when the game trys to get the sprite it returns null, i recommend checking to see if the image path is right in the characters .json file

**Comment by Matnimations11** [comment]
> this means that for some reason when the game trys to get the sprite it returns null, i recommend checking to see if the image path is right in the characters .json file

i checked and everything looks fine to me.
