### ISSUE TITLE
lime test windows doesn't work

### ISSUE THREAD

**Issue by L1m3Official** [ShadowMario/FNF-PsychEngine#13476]
### Describe your bug here.

Whemever I try to use "lime test windows" to build the game it doesnt work, no Idea why (issue shown in the "Command Prompt/Terminal logs section").

### Command Prompt/Terminal logs (if existing)

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/82063123/8f9581e8-2e2b-43cd-b73d-a7daf5f68fd1)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed the BF and GF spritesheets / XML / Icons.

**Comment by JohnDoe3453** [comment]
bro reinstall lime

```haxelib run lime setup```
