### ISSUE TITLE
Multiple Voice Tracks In-game

### ISSUE THREAD

**Issue by ThaRizzah254** [ShadowMario/FNF-PsychEngine#13478]
### What is your question?

so, i know this question was asked before but ,i have the opponent and player voices separated(each has its own .ogg file) and i want them to play in game, Can someone make a code for this? The code from the same question a while ago doesnt work for me

**Comment by Lorekeeper49** [comment]
There's no real way to do this without editing the source code but there is a workaround by placing one or both of the files in the `music` folder and using the `playMusic()` function
