### ISSUE TITLE
source/psychlua/hscript.hx:168: characters 89-94 : type not found : scall

### ISSUE THREAD

**Issue by Cypresstuff** [ShadowMario/FNF-PsychEngine#13473]
### Describe your problem here.

when I try to run Lime test windows I get the message "source/psychlua/hscript.hx:168: characters 89-94 : type not found : scall"

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ProjectPlayer015** [comment]
Run haxelib set SScript 5.2.0 in the cmd!

**Comment by Scorpion105951** [comment]
> Run haxelib set SScript 5.2.0 in the cmd!
thx u this helped
