### ISSUE TITLE
Something relating to instakill on miss and the Weeks 1-7 achievements that require you not to miss.

### ISSUE THREAD

**Issue by wj1ajao39sjak927** [ShadowMario/FNF-PsychEngine#13485]
### What is your question?

If you're getting those achievements and if you turn on instakill on miss and you miss a note and die in a song during a week in Story Mode, will that affect getting the achievement or not in any way?

**Comment by CaptainBaldi** [comment]
as far as i know it shouldnt

**Comment by wj1ajao39sjak927** [comment]
Alright.
