### ISSUE TITLE
Centering song names in freeplay

### ISSUE THREAD

**Issue by NpcSnoom397** [ShadowMario/FNF-PsychEngine#13482]
### Describe your problem here.

So I put this to center my song names
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/107694396/e1ffa3b1-12d4-4023-a92c-932aafb03c80)
But now, any time I exit a song, all the names start moving horizantally very quickly, making them look like they shake

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Removed the freeplay bg to replace for a new one that doesn't tween colors, applied the color function for song names instead

**Comment by SammyXDDD** [comment]
Idk if this works in 0.7 but if your making your mod in 0.6.3 try this:
under : songText.isMenuItem = true;
Paste This:
 songText.screenCenter(X); 			songText.changeX = false;

**Comment by NpcSnoom397** [comment]
I'm making my mod on 0.6.2
And the error says that Alphabet doesn't have a field changeX
