### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by I-am-someone-sh** [ShadowMario/FNF-PsychEngine#13487]
### Describe your problem here.

 - Link: ApplicationMain: xcrun --sdk macosx clang++ -o ApplicationMain -rpath @executable_path -framework Cocoa -arch arm64 -framework Security @obj/darwinarm64/all_objs /usr/local/lib/haxe/lib/linc_luajit/git//lib/lua/lib/Mac/libluajit-5.1.a
ld: warning: ignoring file /usr/local/lib/haxe/lib/linc_luajit/git//lib/lua/lib/Mac/libluajit-5.1.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_luaL_callmeta", referenced from:
      linc::helpers::onError(lua_State*) in 8bcd09a4_linc_lua.o
  "_luaL_checklstring", referenced from:
      linc::lual::checklstring(lua_State*, int, unsigned long*) in 8bcd09a4_linc_lua.o
      linc::lual::checkstring(lua_State*, int) in 8bcd09a4_linc_lua.o
  "_luaL_error", referenced from:
      linc::lual::error(lua_State*, char const*) in 8bcd09a4_linc_lua.o
      linc::helpers::hx_trace(lua_State*) in 8bcd09a4_linc_lua.o
  "_luaL_findtable", referenced from:
      linc::lual::findtable(lua_State*, int, char const*, int) in 8bcd09a4_linc_lua.o
  "_luaL_gsub", referenced from:
      linc::lual::gsub(lua_State*, char const*, char const*, char const*) in 8bcd09a4_linc_lua.o
  "_luaL_loadfile", referenced from:
      psychlua::FunkinLua_obj::__construct(String) in 27c37d3c_FunkinLua.o
  "_luaL_newstate", referenced from:
      psychlua::FunkinLua_obj::__construct(String) in 27c37d3c_FunkinLua.o
  "_luaL_openlibs", referenced from:
      psychlua::FunkinLua_obj::__construct(String) in 27c37d3c_FunkinLua.o
  "_luaL_optlstring", referenced from:
      linc::lual::optlstring(lua_State*, int, char const*, unsigned long*) in 8bcd09a4_linc_lua.o
      linc::lual::optstring(lua_State*, int, char const*) in 8bcd09a4_linc_lua.o
  "_luaL_prepbuffer", referenced from:
      linc::lual::prepbuffer(luaL_Buffer*) in 8bcd09a4_linc_lua.o
  "_luaL_ref", referenced from:
      llua::Convert_obj::fromLua(cpp::Reference<lua_State>, int) in eafbd2af_Convert.o
  "_luaL_register", referenced from:
      linc::helpers::register_hxtrace_lib(lua_State*) in 8bcd09a4_linc_lua.o
  "_luaL_traceback", referenced from:
      linc::helpers::onError(lua_State*) in 8bcd09a4_linc_lua.o
  "_luaL_unref", referenced from:
      llua::LuaCallback_obj::dispose() in eafbd2af_LuaCallback.o
  "_lua_call", referenced from:
      linc::helpers::hx_trace(lua_State*) in 8bcd09a4_linc_lua.o
  "_lua_close", referenced from:
      psychlua::FunkinLua_obj::stop() in 27c37d3c_FunkinLua.o
  "_lua_createtable", referenced from:
      llua::Convert_obj::toLua(cpp::Reference<lua_State>, Dynamic) in eafbd2af_Convert.o
      llua::Convert_obj::arrayToLua(cpp::Reference<lua_State>, cpp::VirtualArray) in eafbd2af_Convert.o
      llua::Convert_obj::mapToLua(cpp::Reference<lua_State>, hx::ObjectPtr<haxe::ds::StringMap_obj>) in eafbd2af_Convert.o
      llua::Convert_obj::objectToLua(cpp::Reference<lua_State>, Dynamic) in eafbd2af_Convert.o
  "_lua_getfield", referenced from:
      linc::helpers::register_hxtrace_lib(lua_State*) in 8bcd09a4_linc_lua.o
      linc::helpers::hx_trace(lua_State*) in 8bcd09a4_linc_lua.o
      psychlua::FunkinLua_obj::call(String, cpp::VirtualArray) in 27c37d3c_FunkinLua.o
      psychlua::FunkinLua_obj::getBool(String) in 27c37d3c_FunkinLua.o
      psychlua::FunkinLua_obj::__construct(String)::_hx_Closure_8::_hx_run(String, String) in 27c37d3c_FunkinLua.o
  "_lua_getinfo", referenced from:
      linc::lua::getinfo(lua_State*, char const*, Dynamic) in 8bcd09a4_linc_lua.o
  "_lua_getstack", referenced from:
      linc::lua::getstack(lua_State*, int, Dynamic) in 8bcd09a4_linc_lua.o
  "_lua_gettop", referenced from:
      llua::Lua_helper_obj::callback_handler(cpp::Reference<lua_State>, String) in eafbd2af_Lua_helper.o
      linc::helpers::hx_trace(lua_State*) in 8bcd09a4_linc_lua.o
      llua::Convert_obj::callback_handler(Dynamic, cpp::Reference<lua_State>) in eafbd2af_Convert.o
      psychlua::CallbackHandler_obj::call(cpp::Reference<lua_State>, String) in 27c37d3c_CallbackHandler.o
  "_lua_isnumber", referenced from:
      psychlua::FunkinLua_obj::__construct(String)::_hx_Closure_8::_hx_run(String, String) in 27c37d3c_FunkinLua.o
  "_lua_isstring", referenced from:
      psychlua::FunkinLua_obj::__construct(String)::_hx_Closure_8::_hx_run(String, String) in 27c37d3c_FunkinLua.o
  "_lua_next", referenced from:
      llua::Convert_obj::toHaxeObj(cpp::Reference<lua_State>, int) in eafbd2af_Convert.o
  "_lua_pcall", referenced from:
      psychlua::FunkinLua_obj::__construct(String) in 27c37d3c_FunkinLua.o
      psychlua::FunkinLua_obj::call(String, cpp::VirtualArray) in 27c37d3c_FunkinLua.o
      llua::LuaCallback_obj::call(cpp::VirtualArray) in eafbd2af_LuaCallback.o
  "_lua_pushboolean", referenced from:
      psychlua::FunkinLua_obj::__construct(String)::_hx_Closure_8::_hx_run(String, String) in 27c37d3c_FunkinLua.o
      llua::Convert_obj::toLua(cpp::Reference<lua_State>, Dynamic) in eafbd2af_Convert.o
  "_lua_pushcclosure", referenced from:
      linc::lua::pushcclosure(lua_State*, cpp::Function<int (lua_State*)>, int) in 8bcd09a4_linc_lua.o
      linc::lua::pushcfunction(lua_State*, cpp::Function<int (lua_State*)>) in 8bcd09a4_linc_lua.o
      linc::helpers::setErrorHandler(lua_State*) in 8bcd09a4_linc_lua.o
      linc::callbacks::add_callback_function(lua_State*, char const*) in 8bcd09a4_linc_lua.o
  "_lua_pushinteger", referenced from:
      llua::Convert_obj::toLua(cpp::Reference<lua_State>, Dynamic) in eafbd2af_Convert.o
  "_lua_pushlstring", referenced from:
      linc::helpers::onError(lua_State*) in 8bcd09a4_linc_lua.o
  "_lua_pushnil", referenced from:
      linc::callbacks::remove_callback_function(lua_State*, char const*) in 8bcd09a4_linc_lua.o
      psychlua::FunkinLua_obj::__construct(String)::_hx_Closure_8::_hx_run(String, String) in 27c37d3c_FunkinLua.o
      llua::Convert_obj::toLua(cpp::Reference<lua_State>, Dynamic) in eafbd2af_Convert.o
      llua::Convert_obj::toHaxeObj(cpp::Reference<lua_State>, int) in eafbd2af_Convert.o
  "_lua_pushnumber", referenced from:
      psychlua::FunkinLua_obj::__construct(String)::_hx_Closure_8::_hx_run(String, String) in 27c37d3c_FunkinLua.o
      llua::Convert_obj::toLua(cpp::Reference<lua_State>, Dynamic) in eafbd2af_Convert.o
      llua::Convert_obj::arrayToLua(cpp::Reference<lua_State>, cpp::VirtualArray) in eafbd2af_Convert.o
  "_lua_pushstring", referenced from:
      linc::callbacks::add_callback_function(lua_State*, char const*) in 8bcd09a4_linc_lua.o
      psychlua::FunkinLua_obj::__construct(String)::_hx_Closure_8::_hx_run(String, String) in 27c37d3c_FunkinLua.o
      llua::Convert_obj::toLua(cpp::Reference<lua_State>, Dynamic) in eafbd2af_Convert.o
      llua::Convert_obj::mapToLua(cpp::Reference<lua_State>, hx::ObjectPtr<haxe::ds::StringMap_obj>) in eafbd2af_Convert.o
      llua::Convert_obj::objectToLua(cpp::Reference<lua_State>, Dynamic) in eafbd2af_Convert.o
  "_lua_pushvalue", referenced from:
      linc::helpers::hx_trace(lua_State*) in 8bcd09a4_linc_lua.o
  "_lua_rawgeti", referenced from:
      llua::LuaCallback_obj::call(cpp::VirtualArray) in eafbd2af_LuaCallback.o
  "_lua_setfield", referenced from:
      linc::callbacks::add_callback_function(lua_State*, char const*) in 8bcd09a4_linc_lua.o
      linc::callbacks::remove_callback_function(lua_State*, char const*) in 8bcd09a4_linc_lua.o
      psychlua::FunkinLua_obj::set(String, Dynamic) in 27c37d3c_FunkinLua.o
  "_lua_settable", referenced from:
      llua::Convert_obj::toLua(cpp::Reference<lua_State>, Dynamic) in eafbd2af_Convert.o
      llua::Convert_obj::arrayToLua(cpp::Reference<lua_State>, cpp::VirtualArray) in eafbd2af_Convert.o
      llua::Convert_obj::mapToLua(cpp::Reference<lua_State>, hx::ObjectPtr<haxe::ds::StringMap_obj>) in eafbd2af_Convert.o
      llua::Convert_obj::objectToLua(cpp::Reference<lua_State>, Dynamic) in eafbd2af_Convert.o
  "_lua_settop", referenced from:
      linc::helpers::register_hxtrace_lib(lua_State*) in 8bcd09a4_linc_lua.o
      linc::helpers::hx_trace(lua_State*) in 8bcd09a4_linc_lua.o
      psychlua::FunkinLua_obj::call(String, cpp::VirtualArray) in 27c37d3c_FunkinLua.o
      psychlua::FunkinLua_obj::getErrorMessage(int) in 27c37d3c_FunkinLua.o
      psychlua::FunkinLua_obj::getBool(String) in 27c37d3c_FunkinLua.o
      psychlua::FunkinLua_obj::__construct(String)::_hx_Closure_8::_hx_run(String, String) in 27c37d3c_FunkinLua.o
      llua::Convert_obj::toHaxeObj(cpp::Reference<lua_State>, int) in eafbd2af_Convert.o
      ...
  "_lua_toboolean", referenced from:
      psychlua::FunkinLua_obj::__construct(String)::_hx_Closure_8::_hx_run(String, String) in 27c37d3c_FunkinLua.o
      llua::Convert_obj::fromLua(cpp::Reference<lua_State>, int) in eafbd2af_Convert.o
  "_lua_tocfunction", referenced from:
      linc::lua::tocfunction(lua_State*, int) in 8bcd09a4_linc_lua.o
  "_lua_tolstring", referenced from:
      linc::lua::tostring(lua_State*, int) in 8bcd09a4_linc_lua.o
      linc::lua::tolstring(lua_State*, int, unsigned long*) in 8bcd09a4_linc_lua.o
      linc::helpers::onError(lua_State*) in 8bcd09a4_linc_lua.o
      linc::callbacks::luaCallback(lua_State*) in 8bcd09a4_linc_lua.o
      linc::helpers::hx_trace(lua_State*) in 8bcd09a4_linc_lua.o
  "_lua_tonumber", referenced from:
      psychlua::FunkinLua_obj::__construct(String)::_hx_Closure_8::_hx_run(String, String) in 27c37d3c_FunkinLua.o
      llua::Convert_obj::fromLua(cpp::Reference<lua_State>, int) in eafbd2af_Convert.o
      llua::Convert_obj::toHaxeObj(cpp::Reference<lua_State>, int) in eafbd2af_Convert.o
  "_lua_type", referenced from:
      linc::lual::ltypename(lua_State*, int) in 8bcd09a4_linc_lua.o
      linc::helpers::onError(lua_State*) in 8bcd09a4_linc_lua.o
      psychlua::FunkinLua_obj::call(String, cpp::VirtualArray) in 27c37d3c_FunkinLua.o
      psychlua::FunkinLua_obj::__construct(String)::_hx_Closure_8::_hx_run(String, String) in 27c37d3c_FunkinLua.o
      llua::Convert_obj::fromLua(cpp::Reference<lua_State>, int) in eafbd2af_Convert.o
      llua::Convert_obj::toHaxeObj(cpp::Reference<lua_State>, int) in eafbd2af_Convert.o
      llua::LuaCallback_obj::call(cpp::VirtualArray) in eafbd2af_LuaCallback.o
      ...
  "_lua_typename", referenced from:
      linc::lua::_typename(lua_State*, int) in 8bcd09a4_linc_lua.o
      linc::lual::ltypename(lua_State*, int) in 8bcd09a4_linc_lua.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

any body know how to fix this?
I tried both branch of PE and both not work

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19no2fa** [comment]
I don't think u can build psych in mac arm64/m1

**Comment by I-am-someone-sh** [comment]
> I don't think u can build psych in mac arm64/m1

nope I am using x86, also hxcpp version is 4.2.1

**Comment by mcagabe19** [comment]
> > I don't think u can build psych in mac arm64/m1
> 
> nope I am using x86, also hxcpp version is 4.2.1

did u try ``haxelib run lime build mac -64 -D HXCPP_M64``? and run ``uname -a`` after send output there

**Comment by I-am-someone-sh** [comment]
> > > I don't think u can build psych in mac arm64/m1
> > 
> > 
> > nope I am using x86, also hxcpp version is 4.2.1
> 
> did u try `haxelib run lime build mac -64 -D HXCPP_M64`? and run `uname -a` after send output there

oh I should try
