### ISSUE TITLE
uncaught error?

### ISSUE THREAD

**Issue by Starblast011** [ShadowMario/FNF-PsychEngine#13498]
### Describe your problem here.

When I tried to launch my mod it said this... 
![Screenshot (2308)](https://github.com/ShadowMario/FNF-PsychEngine/assets/149037894/d09e0cae-7690-4887-b1f4-b619c13d418d)
](url)

Do you know how I can fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by mcagabe19** [comment]
check your json files
