### ISSUE TITLE
Fixed Graphic Setting Sub State

### ISSUE THREAD

**Issue by afeefflox** [ShadowMario/FNF-PsychEngine#1349]
### Describe your bug here.

So, When I Compile a game then I went to options and I press the graphic. so the game got crash so fixed the GraphicSettingSubState

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Reycko** [comment]
Try putting `haxelib install polymod` into **Command Prompt**.

**Comment by ShadowMario** [comment]
> Try putting `haxelib install polymod` into **Command Prompt**.

Polymod is not a requirement for Psych Engine.

This issue has no information so this doesn't help in anything at all.
