### ISSUE TITLE
240 fps bug

### ISSUE THREAD

**Issue by Bezizeja** [ShadowMario/FNF-PsychEngine#13492]
### Describe your bug here.

soo i put my frames all the way in menu and gameplay camera moves suuper slow

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope freshly cooked

**Comment by NexIsDumb** [comment]
Its about new Flixel version
I made a PR that fixes that issue, if you want you can check it out: #13433

**Comment by NexIsDumb** [comment]
Or you can downgrade a bit Flixel
