### ISSUE TITLE
Custom Game Over animations?

### ISSUE THREAD

**Issue by toovie** [ShadowMario/FNF-PsychEngine#13496]
### Describe your problem here.

so, im making a mod, right?
i need to have custom game-overs for certain levels.
is there any way i can achieve that?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

weeks and new animations + songs and shit

**Comment by Ozofearlez** [comment]
I believe with the more recent psych updates, that's just an option you can select in the data tab of the chart editor
