### ISSUE TITLE
End-Of-Song Dialogue

### ISSUE THREAD

**Issue by darklink064** [ShadowMario/FNF-PsychEngine#135]
Hi again, I've got a custom stage and a beginning dialogue for a song set up currently. I also want my song to have an ending dialogue, but I've poked around the wiki and haven't found anything. How do I do this (on the download build)? 
And also I apologize if this actually on the wiki and I'm just blind.

**Comment by ShadowMario** [comment]
Same as the example dialogue script, but instead of it blocking onStartCountdown(), it should block onEndSong().

**Comment by darklink064** [comment]
Thanks
