### ISSUE TITLE
Uncaught Error: Null Object Reference

### ISSUE THREAD

**Issue by mysteryman57** [ShadowMario/FNF-PsychEngine#13509]
I'm not sure how to properly exsplan this, and forgive me as I'm very new to this. So I'm working on a personal halloween mod useing the charting and song code from VS sonic.exe. I had succesfully edidted the song, too-slow, to work with my character. However, I keep getting this error message whenevr I load up the character's song. Its only this song, none of the other are like this. Also the song was working fine awile ago, but now it dosent work properly. I looked into it, an I though it was a character problem but I'm not sure as my charater looks fine and loads find.

![Screenshot 2023-10-28 004537](https://github.com/ShadowMario/FNF-PsychEngine/assets/149222857/6b972b85-c6e5-46b7-a8f1-7b923a841678)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I made a new stage useing the 'stage' stage recreation templet

**Comment by Filip55561** [comment]
do you have the .xml file for it? Happed to me a lot that I accidentally deleted it

**Comment by Darling-epic** [comment]
how i get that file pls help

**Comment by Filip55561** [comment]
> how i get that file pls help

So you  have ur character right?
