### ISSUE TITLE
Crashes on open, using macOS Ventura.

### ISSUE THREAD

**Issue by PhantomDark26** [ShadowMario/FNF-PsychEngine#13505]
### Describe your bug here.

I opened the Mac built on MacOS Ventura and it crashed, I've never had this problem.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Sergio-Astro** [comment]
Yes same for me, crash report attached.
[PHD2-crash-report.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/13455705/PHD2-crash-report.txt)
