### ISSUE TITLE
How do all the .dll files work?

### ISSUE THREAD

**Issue by wj1ajao39sjak927** [ShadowMario/FNF-PsychEngine#13500]
### What is your question?

How does each .dll file work? (PsychEngine > plugins)

**Comment by mcagabe19** [comment]
these dll's for vlc plugins u can't add your custom dll's

**Comment by wj1ajao39sjak927** [comment]
No I'm using the latest version of Psych. Also, I asked because of the .dll files for plugins such as "audio_filter".

**Comment by wj1ajao39sjak927** [comment]
I think we should have ShadowMario explain all the .dll files.

**Comment by wj1ajao39sjak927** [comment]
I especially want to know how some of the .dll files such as the ones for "access" and "access_output" work.

**Comment by wj1ajao39sjak927** [comment]
oh ok.
