### ISSUE TITLE
I can't compile it

### ISSUE THREAD

**Issue by ShineUA** [ShadowMario/FNF-PsychEngine#13502]
### Describe your problem here.

I can't compile it, when I using `lime test windows`, I'm getting error: `source/psychlua/HScript.hx:168: characters 89-94 : Type not found : SCall`.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by JohnDoe3453** [comment]
use experimental branch

**Comment by JohnDoe3453** [comment]
hello?

**Comment by ShineUA** [comment]
> use experimental branch

with experemental branch I getting error: `source/psychlua/CallbackHandler.hx:54: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua`
