### ISSUE TITLE
i have a question

### ISSUE THREAD

**Issue by JohnDoe3453** [ShadowMario/FNF-PsychEngine#13503]
### What is your question?

why its not appearing the scripts folder in my mod folder

**Comment by mcagabe19** [comment]
> ### What is your question?
> why its not appearing the scripts folder in my mod folder

just create it

**Comment by JohnDoe3453** [comment]
done

**Comment by JohnDoe3453** [comment]
im gonna create the 1981 meme

**Comment by JohnDoe3453** [comment]
well the scripts are working

thx
