### ISSUE TITLE
Error Compiling during Psych Engine [PLS HELP]

### ISSUE THREAD

**Issue by VillianousJ0ker** [ShadowMario/FNF-PsychEngine#13512]
### Describe your bug here.

Installed Visual Studio and about everything I need I think and now I recently got this error.

### Command Prompt/Terminal logs (if existing)

```bash
Error: RGBPalette.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\yvals.h(21): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: SecurityDomain.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\yvals.h(21): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: Context3DElementType.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\yvals.h(21): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope, not yet, just been trying to compile.

**Comment by VillianousJ0ker** [comment]
Update: MORE ERRORS! WOW HOW SURPRISING!

Error: TextEventInfo.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\yvals.h(21): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: SecurityDomain.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\yvals.h(21): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: Stdout.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\yvals.h(21): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: RGBPalette.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\yvals.h(21): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: Context3DElementType.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\yvals.h(21): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: FlxPathDrawData.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\yvals.h(21): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

**Comment by mcagabe19** [comment]
U have to use Visual Studio _2019_ Community not 2022

**Comment by VillianousJ0ker** [comment]
ah, so is there a download link for that anywhere?

**Comment by TechnikTil** [comment]
> ah, so is there a download link for that anywhere?

Yes, there is if you just search visual studio 2019 community
