### ISSUE TITLE
When will Psych Engine 0.7.2 come out?

### ISSUE THREAD

**Issue by TragicMagneta** [ShadowMario/FNF-PsychEngine#13518]
### What is your question?

Update Please!

**Comment by BlueColorsin** [comment]
never 😈

**Comment by wj1ajao39sjak927** [comment]
It'll probably be coming out sometime soon. ShadowMario may be working on the next version as we speak.

**Comment by wj1ajao39sjak927** [comment]
What is the experimental branch? How to view the experimental branch?

**Comment by Vortex2Oblivion** [comment]
Click on the button to change the branch and choose experimental

**Comment by crowplexus** [comment]
give a week or two
