### ISSUE TITLE
Compiling Issues (Experimental)

### ISSUE THREAD

**Issue by slimeysonic400** [ShadowMario/FNF-PsychEngine#13513]
### Describe your problem here.

I'm having trouble with compiling my build, I have seemingly installed every needed library (ran the hmm code) but I am getting an error that says I do not have a needed library. I have already tried looking at other posts about the same problem but I keep getting the same error. I also followed at least 3 different compiling tutorials to see if I was doing something wrong but I had everything correct. 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed the build name/app name

**Comment by slimeysonic400** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/90658302/19aa462c-976a-42e8-9ba9-e500435ddfdc)
forgot to add this

**Comment by s-h-i-f-t-y-z** [comment]
replace it with TeaCall

**Comment by slimeysonic400** [comment]
how would i do that? thanks

**Comment by slimeysonic400** [comment]
how?

**Comment by TomVN1230101** [comment]
> how?

do like video https://drive.google.com/file/d/1qnVoUODGwAAosgqXzlSsuHrf5fz0pph1/view?usp=drive_link

**Comment by s-h-i-f-t-y-z** [comment]
go into the hscript.hx file in the source folder, scroll to line 168 and around characters 89-94, locate SCall and replace it with TeaCall
