### ISSUE TITLE
make the call functions return the values

### ISSUE THREAD

**Issue by FourTheGreat** [ShadowMario/FNF-PsychEngine#13514]
### What feature do you want to get added on the **base** engine?

make it so callOnScripts/callOnLuas/CallOnHscript returns the value of the function, and not just a `true` bool
cuz as of now we have to
`local returnValue = runHaxeCode('return game.callOnScripts('func',[args])')`
making the lua version of the function return the values would let us easily make lua functions be stopped with Function_Stop, for example, like in some hardcoded callbacks.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/483a855e-0fcd-47c3-b0eb-6b4167f0b12a)
It already works.
