### ISSUE TITLE
Get input from player

### ISSUE THREAD

**Issue by TaoTheBlock** [ShadowMario/FNF-PsychEngine#1351]
### Describe your problem here.

I try to get a userinput thing like they press Ctrl and bf do animation.
How to do that??? Sorry if my english is bad.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/1246
