### ISSUE TITLE
Pack Editor

### ISSUE THREAD

**Issue by SrBagel** [ShadowMario/FNF-PsychEngine#13517]
### What feature do you want to get added on the **base** engine?

Add a way to edit the pack.json file in the mods folder to the Master Editor Menu where you can make a new pack or edit an existing one similar to the week editor.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Keoiki** [comment]
The pack.json files are literally 6 lines long, why the fuck would you need an editor for this????????

**Comment by SrBagel** [comment]
> The pack.json files are literally 6 lines long, why the fuck would you need an editor for this????????

The menu character Json's are 10 lines long, why do we have an editor for them?

**Comment by Skullbite** [comment]
Because with characters, it's faster to achieve the desired result by visually editing it. `Pack.json`s literally have 4 keys to edit that tell you exactly what they're for. It's pointless to make an editor for that.

**Comment by SrBagel** [comment]
Ok cool. I still think it would be nice for the background color and discord rpc though
