### ISSUE TITLE
A feature that automatically updates Psych Engine when a new version is released.

### ISSUE THREAD

**Issue by wj1ajao39sjak927** [ShadowMario/FNF-PsychEngine#13522]
### What feature do you want to get added on the **base** engine?

There should be a feature that automatically updates Psych Engine when a new version of it is released so that you don't have to install it from the Gamebanana or GitHub page.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Lorekeeper49** [comment]
Unless HaxeFlixel can download files from web sources and we just never knew about it or something, I'm pretty sure this can't be implemented

**Comment by wj1ajao39sjak927** [comment]
Wait, maybe it should be something that downloads the latest version itself.

**Comment by Bezizeja** [comment]
this mod has a cool way to update psych engine
https://gamebanana.com/mods/471076

**Comment by Noobz4Life** [comment]
If it helps, I was working on a mod manager built in Haxe that could successfully download and install mods

[Here is the code for the downloader portion](https://gist.github.com/Noobz4Life/2d897686e77302cebacc823b7f74252e)

It can be used like this:

        downloader = new Downloader();
        downloader.addEventListener(DownloadEvent.DOWNLOAD_COMPLETE,downloadComplete); // Add downloadComplete

        var file:File = new File(destination); // Replace destination with where you want the file to download to
        downloader.download(url,file); // Replace url
        
The code for the downloader can definitely be improved, but for now it works

Haxe also has built-in functions to extract .zip files, [here is a working example for doing so.](https://gist.github.com/Noobz4Life/54b0c2e53d43de08d2056165d60bab19)

I might end up making a PR of this at some point, but at the moment I don't have time.

**Comment by ShadowMario** [comment]
I'm gonna stop updating Psych Engine soon, so it is too late to implement this in my opinion.

**Comment by wj1ajao39sjak927** [comment]
Wait a minute, Psych Engine is being discontinued soon?
