### ISSUE TITLE
Crash when I starting the song

### ISSUE THREAD

**Issue by LEWD1111** [ShadowMario/FNF-PsychEngine#13529]
### Describe your bug here.

![download](https://github.com/ShadowMario/FNF-PsychEngine/assets/149431067/b07d0138-89bf-4c0c-973f-636e23dc1ae2)
This crash report appeared when I was trying to start the song in freeplay. Help me pls. If I wrote something wrong I am sorry.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I wasn't

**Comment by SrBagel** [comment]
The json file does not exist

**Comment by LEWD1111** [comment]
> The json file does not exist

Thanks
