### ISSUE TITLE
Characters not appearing in game which crashes the whole game. 

### ISSUE THREAD

**Issue by DaBanana64** [ShadowMario/FNF-PsychEngine#1353]
### Describe your bug here.

I'm on the latest commit on Psych Engine, and when I go to character editor, none of the characters appear, including the base engine characters. 
![image](https://user-images.githubusercontent.com/82652849/143437006-2bf7c71d-9732-46ac-96f3-381ef6077723.png)
And this makes the whole game crash whenever I try to get into a song in Freeplay and Storymode as seen here.

https://user-images.githubusercontent.com/82652849/143440579-5a2fd63b-1aeb-45f1-8479-db4d7b88a20b.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not edit anything in the source. All I did was to compile the game through the source.

**Comment by PumpTutorials** [comment]
same thing happend to me best bet is just changing versions to before the softcode atlas package mistake

**Comment by afeefflox** [comment]
Ok Make Sure DON'T CHANGE THE softcode atlas package USE BY ORGINAL

**Comment by DaBanana64** [comment]
> same thing happend to me best bet is just changing versions to before the softcode atlas package mistake

Damn.

> Ok Make Sure DON'T CHANGE THE softcode atlas package USE BY ORGINAL

As I said before, I didn't change nor edit the files in the source, and I have no clue how to change that.

**Comment by PumpTutorials** [comment]
just got patched just reinstall

**Comment by DaBanana64** [comment]
![image](https://user-images.githubusercontent.com/82652849/143625160-58054d78-fee1-462c-8968-1fb5da7324a6.png)
Tried the on the latest commit and it's actually fixed! Thanks ShadowMario!
