### ISSUE TITLE
Help with compiling the source code

### ISSUE THREAD

**Issue by NonCanonBF** [ShadowMario/FNF-PsychEngine#13545]
### Describe your problem here.

When I would try to compile this error would pop up annoyingly.

**Error: Could not find haxelib "flxanimate", does it need to be installed?**

Then I would do:

`haxelib install flxanimate`

I would try to compile again:

**source/psychlua/FlxAnimateFunctions.hx:139: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)**

How do I solve this? Do I downgrade my Haxe version? 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Loro1090** [comment]
pls can you tell me how do yo solve that?

**Comment by Kayplays45** [comment]
try to use `haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev` it should Work if not try to Recompile
