### ISSUE TITLE
Change title Secrets

### ISSUE THREAD

**Issue by Fellegend** [ShadowMario/FNF-PsychEngine#13558]
### What is your question?

Alright, so... there is some secrets in Psych Engine title screen:
If you type "shadow", ShadowMario will appear
If you type "river", River will appear, etc.

I want to change it. I tried to do it by TitleState.hx but didn't work. I typed and nothing happened.
How can I do it?
I'm modding with Source

**Comment by SrBagel** [comment]
at line 65 in TitleState.hx you have to add the name of the character to the list. Then at line 132 add the offsets of your character. Then copy lines 261-263 and edit them to your liking. Then at line 647 add the jingle that plays when the easter egg is entered. That should work, but I'm not sure I've never tried it before

**Comment by Fellegend** [comment]
okay. i'll try

**Comment by Fellegend** [comment]
That's what I did, but the character doesn't show. That

**Comment by Fellegend** [comment]
> at line 65 in TitleState.hx you have to add the name of the character to the list. Then at line 132 add the offsets of your character. Then copy lines 261-263 and edit them to your liking. Then at line 647 add the jingle that plays when the easter egg is entered. That should work, but I'm not sure I've never tried it before

But thanks anyway :D

**Comment by SrBagel** [comment]
> That's what I did, but the character doesn't show.

Delete the` if="officialBuild"` at line 28 in Project.xml

**Comment by Fellegend** [comment]
Worked, but when I typed (I think it's "typed") the name I used to replace "SHADOW", this mess happened:

states/TitleState.hx (line 681)
states/TitleState.hx (line 333)
states/TitleState.hx (line 175)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

This is my TitleState.hx file:
[TitleState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/13260494/TitleState.txt)

I know this is a txt file, but GitHub doesn't let me upload hx files

**Comment by SrBagel** [comment]
[TitleState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/13260597/TitleState.txt)
Here I made a few changes that should work

**Comment by Fellegend** [comment]
Okay. I'm testing it. Thanks

**Comment by Fellegend** [comment]
WORKED!! Really, Tysm :D

> [TitleState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/13260597/TitleState.txt) Here I made a few changes that should work

**Comment by Fellegend** [comment]
Now I'll try with my own characters. I hope it will work
