### ISSUE TITLE
characters are just broken now lmoa

### ISSUE THREAD

**Issue by Krismowo** [ShadowMario/FNF-PsychEngine#1355]
### Describe your bug here.

characters be breakin in a way i didnt think was possible (also no i didnt add nothin to do with characters before compiling)

(img or smth idk)
![image](https://user-images.githubusercontent.com/82868738/143454881-26cff383-eb78-411a-a051-c921b42c9afc.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

simple funnies in playstate tryna do more moving camera thing (image thing will be here or smth idkkk)
![image](https://user-images.githubusercontent.com/82868738/143454994-5706fc60-30a5-4635-b5c0-a3f47b524f3f.png)

**Comment by afeefflox** [comment]
:/ So uh is there bf and mom character i think that is Crash

**Comment by Krismowo** [comment]
> :/ So uh is there bf and mom character i think that is Crash
literally all i did was compile the game, every normal asset that should be there, is there

**Comment by SrtHero278** [comment]
Whenever I look at fnf variables, it always defines what kind of variable it is.
I'm not good with source code but try replacing
```
var dadspeshy = 0;
var dadspeshx = 0;
```
with:
```
var dadspeshy:Int = 0;
var dadspeshx:Int = 0;
```
If you're planning on having decimals in this, replace `Int` with `Float`.

**Comment by Krismowo** [comment]
> Whenever I look at fnf variables, it always defines what kind of variable it is. I'm not good with source code but try replacing
> 
> ```
> var dadspeshy = 0;
> var dadspeshx = 0;
> ```
> 
> with:
> 
> ```
> var dadspeshy:Int = 0;
> var dadspeshx:Int = 0;
> ```
> 
> If you're planning on having decimals in this, replace `Int` with `Float`.

i mean that thing aint gonna fix the characters

**Comment by ShadowMario** [comment]
Fixed.
