### ISSUE TITLE
Biden blast mod crash when pressing a key

### ISSUE THREAD

**Issue by n0l1um** [ShadowMario/FNF-PsychEngine#13559]
### Describe your bug here.

playing with BIDEN BLAST mod, all files unzipped in mods folder and played through freeplay. error happened whne pressing a key

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
objects/NoteSplash.hx (line 121)
objects/NoteSplash.hx (line 57)
states/PlayState.hx (line 2985)
states/PlayState.hx (line 2979)
states/PlayState.hx (line 2433)
states/PlayState.hx (line 2921)
states/PlayState.hx (line 2632)
states/PlayState.hx (line 2588)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, just played with the biden blast mod

**Comment by Prem1umDev** [comment]
Please ask the mod developers, this is not a psych engine problem.
