### ISSUE TITLE
Can't Compile Error source/psychlua/HScript.hx:168: characters 89-94 : Type not found : SCall

### ISSUE THREAD

**Issue by 12abz** [ShadowMario/FNF-PsychEngine#13556]
### Describe your problem here.

When Compiling On Linux Ubuntu 22.04.3 PC SPECS
averey@averey-Vorticon 
OS: Ubuntu 22.04.3 LTS x86_64 
Host: Vorticon rev7 
Kernel: 6.2.0-36-generic 
Uptime: 42 mins 
CPU: Intel Celeron N4020 (2) @ 2.800 
GPU: Intel GeminiLake [UHD Graphics  
Memory: 925MiB / 3771MiB
Error:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/109289447/4e8bdcb9-21dc-4dcc-a8b6-76caf9c61f1a)
Sooooo... I Can't Compile It :disappointed:

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No. Bare Bones PsychEngine. But My PC Is A ChromeBook.

**Comment by Tikybutnot** [comment]
i have the same problem as well

**Comment by bimbifan** [comment]
exactly the same problem

**Comment by CaptainBaldi** [comment]
this issue has been made so many times please look at one of the literal dozens of issues about it

**Comment by 12abz** [comment]
Note: I'm Using Haxe 4.2.5

**Comment by TheKevinGDX** [comment]
same problem :(

**Comment by CaptainBaldi** [comment]
skull

**Comment by 12abz** [comment]
☠️

**Comment by ozstarhub** [comment]
> this issue has been made so many times please look at one of the literal dozens of issues about it

you mean the ones with no answer yet....
