### ISSUE TITLE
It won't let me install

### ISSUE THREAD

**Issue by BestEverOreos** [ShadowMario/FNF-PsychEngine#13551]
### Describe your problem here.

I tried to do the "haxelib run hmm install" thing but it kept telling me "Validation error: hmm.json not found in current working directory" I think I did everything right, I followed all the steps, I downloaded Haxe 4.2.5 and all the other dozens of things, so I don't know why it isn't working.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I'm trying to

**Comment by TomVN1230101** [comment]
do you want to compile game?
