### ISSUE TITLE
controller sensor

### ISSUE THREAD

**Issue by Funkypupo** [ShadowMario/FNF-PsychEngine#13560]
### Describe your problem here.

so basically im trying to make a script where you have to click to dodge, except i wanted to make it that you click a key on the controller since it would not be fair. is there a way?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by crowplexus** [comment]
you have these functions

```lua
anyGamepadJustPressed("buttonName") -- registers the button press (on the current frame)
anyGamepadPressed("buttonName") -- registers the button press for as long as you are holding the key down
anyGamepadReleased("buttonName") -- registers a button release
