### ISSUE TITLE
cutscenes on mac port

### ISSUE THREAD

**Issue by Yohjihappy** [ShadowMario/FNF-PsychEngine#13563]
### What feature do you want to get added on the **base** engine?

plss just do it

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by CaptainBaldi** [comment]
invalid + ask the `hxCodec` dev's not shadowmario

**Comment by JonnycatMeow** [comment]
there already is with the latest hxcodec

**Comment by ShadowMario** [comment]
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/13430
