### ISSUE TITLE
UPDATE TO SONOMA

### ISSUE THREAD

**Issue by Yohjihappy** [ShadowMario/FNF-PsychEngine#13564]
### What feature do you want to get added on the **base** engine?

PLS UPDATE THE MAC PORT TO MACOS SONOMA PLSSS I CANT PLAY PSYCH ON MAC PLSSS JUST UPDATE IT PLSSSSSS

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by mcagabe19** [comment]
you can try build yourself for sonoma

**Comment by ShadowMario** [comment]
I don't have a mac

**Comment by Yohjihappy** [comment]
so who's the dev who works on the mac port?

**Comment by ShadowMario** [comment]
> so who's the dev who works on the mac port?

That's the point, no one is lol, it has no \*proper\* support
