### ISSUE TITLE
What is SCall?!?!?!?!

### ISSUE THREAD

**Issue by Sanskywuzz** [ShadowMario/FNF-PsychEngine#13562]
### Describe your problem here.

![Captura de tela 2023-11-05 125005](https://github.com/ShadowMario/FNF-PsychEngine/assets/96800484/918d3ae9-6ca5-4d24-b550-2bfb29a577f2)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ricoanimations** [comment]
read all the other issues about this error

**Comment by Sanskywuzz** [comment]
> read all the other issues about this error

I read it but they didn't help me, two things that are there to do, I only did one, because the other I don't know how to do

**Comment by ricoanimations** [comment]
did you try to download the latest experimental build?

**Comment by Sanskywuzz** [comment]
> did you try to download the latest experimental build?

the latest version of the engine? If it is, yes.

**Comment by ricoanimations** [comment]
> > did you try to download the latest experimental build?
> 
> the latest version of the engine? If it is, yes.

no i mean the most current commit of the experimental branch

**Comment by Sanskywuzz** [comment]
> no i mean the most current commit of the experimental branch

I don't know what is experimental branch

**Comment by ricoanimations** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental

**Comment by Sanskywuzz** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental

After clicking on the link I click where?

**Comment by ricoanimations** [comment]
> > https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental
> 
> After clicking on the link I click where?

click code and download the zip file

**Comment by Sanskywuzz** [comment]
> > > https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental
> > 
> > 
> > After clicking on the link I click where?
> 
> click code and download the zip file

ok.. and now?

**Comment by Sanskywuzz** [comment]
> > > > > https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental
> > > > 
> > > > 
> > > > After clicking on the link I click where?
> > > 
> > > 
> > > click code and download the zip file
> > 
> > 
> > ok.. and now?
> 
> extract the file and try to compile the experimental build

A giant message popped up and just

**Comment by ricoanimations** [comment]
what does it say

**Comment by Sanskywuzz** [comment]
> what does it say

source/psychlua/CallbackHandler.hx:54: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat should be declared with 'override' since it is inherited from superclass flixel.graphics.frames.FlxAtlasFrames
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat overrides parent class with different or incomplete type
C:/HaxeToolkit/haxe/lib/flixel/5,4,1/flixel/graphics/frames/FlxAtlasFrames.hx:457: characters 18-24 : ... Base field is defined here
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : ... Different number of function arguments
source/psychlua/FlxAnimateFunctions.hx:139: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)

**Comment by ricoanimations** [comment]
nevermind, you should download this version instead
https://github.com/ShadowMario/FNF-PsychEngine/archive/2d932aa92142befef323fd07249ecce7950b998f.zip
this one should guarantee to work

**Comment by Sanskywuzz** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/archive/2d932aa92142befef323fd07249ecce7950b998f.zip

Gave the same message

**Comment by ricoanimations** [comment]
did you compile the right build?

**Comment by Sanskywuzz** [comment]
> did you compile the right build?

i compile the build you send me

**Comment by ricoanimations** [comment]
Are you using haxe 4.2.5

**Comment by Sanskywuzz** [comment]
> Are you using haxe 4.2.5

I don't think so

**Comment by Sanskywuzz** [comment]
> ricoanimations

i will update hax again

**Comment by ricoanimations** [comment]
> > Are you using haxe 4.2.5
> 
> I don't think so

You need to use haxe 4.2.5 because haxe  has a problem compiling older and newer versions

**Comment by Sanskywuzz** [comment]
> > > Are you using haxe 4.2.5
> > 
> > 
> > I don't think so
> 
> You need to use haxe 4.2.5 because h
ok

**Comment by Sanskywuzz** [comment]
> > > Are you using haxe 4.2.5
> > 
> > 
> > I don't think so
> 
> You need to use haxe 4.2.5 because haxe has a problem compiling older and newer versions
don't work

**Comment by Sanskywuzz** [comment]
I give up

**Comment by ricoanimations** [comment]
> I give up

I understand
