### ISSUE TITLE
Changing song when you press 7

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#1356]
### Describe your problem here.

How do you make it so that it changes the song when you press 7.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

V.S. Anne Remastered + Spong Revived + Poisoned Ivy Revived.

**Comment by 4wdthinks** [comment]
i was going to get code from vs dave and bambi but it looks like the source code is gone.

**Comment by Reycko** [comment]
into the song section, change the song name

**Comment by Reycko** [comment]
4wdthinks i have it lol

**Comment by PDL2CGamejolt** [comment]
PLZ I WANT IT FORM PYSCH ENGINE

**Comment by ShadowMario** [comment]
```lua
function onUpdate(elapsed)
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.FOUR') then
        endSong();
    end
end
```
Tested and it's functional.
Press 4 to skip song

**Comment by PDL2CGamejolt** [comment]
but how do i change a song?

**Comment by PDL2CGamejolt** [comment]
> ```lua
> function onUpdate(elapsed)
>     if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.FOUR') then
>         endSong();
>     end
> end
> ```
> 
> Tested and it's functional. Press 4 to skip song

but how do i change the song

**Comment by PDL2CGamejolt** [comment]
> 4wdthinks i have it lol


> > ```lua
> > function onUpdate(elapsed)
> >     if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.FOUR') then
> >         endSong();
> >     end
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Tested and it's functional. Press 4 to skip song
> 
> but how do i change the song

HELP ME!

**Comment by NeverNoodle** [comment]
> 

yeah but how do i make it switch a song

like set it to be Dadbattle if u press it on Bopeebo or something (just an example)
