### ISSUE TITLE
Random crash when enabling/disabling a mod in the Experimental branch

### ISSUE THREAD

**Issue by helpimbadatusernames** [ShadowMario/FNF-PsychEngine#13579]
### Describe your bug here.

Basically randomly the game crashes when you reload a mod in the experiment build.

flixel/graphics/frames/FlxAtlasFrames.hx (line 392)
flixel/graphics/frames/FlxAtlasFrames.hx (line 238)
objects/Alphabet.hx (line 422)
objects/Alphabet.hx (line 350)
C:\HaxeToolkit\haxe\std/cpp/_std/Type.hx (line 90)
flixel/group/FlxGroup.hx (line 367)
objects/Alphabet.hx (line 220)
objects/Alphabet.hx (line 87)
objects/Alphabet.hx (line 39)
states/TitleState.hx (line 495)
states/TitleState.hx (line 552)
backend/MusicBeatState.hx (line 165)
backend/MusicBeatState.hx (line 52)
states/TitleState.hx (line 488)
flixel/FlxState.hx (line 220)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
Try again on the newest commit.
