### ISSUE TITLE
HELP!!!!!

### ISSUE THREAD

**Issue by ArthurRibeirooo** [ShadowMario/FNF-PsychEngine#13576]
### Describe your bug here.

how do i fix??

C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/format/JsonParser.hx (line 318)
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/format/JsonParser.hx (line 115)
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/format/JsonParser.hx (line 90)
C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/haxe/format/JsonParser.hx (line 57)
WeekData.hx (line 222)
WeekData.hx (line 190)
WeekData.hx (line 178)
FreeplayState.hx (line 60)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid char 91 at position 104
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
![bandicam 2023-11-07 12-25-03-947](https://github.com/ShadowMario/FNF-PsychEngine/assets/142274686/25caaaed-d60e-4eaf-95ce-0da6410b68f4)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes

**Comment by mcagabe19** [comment]
you fucked up your json file
