### ISSUE TITLE
Psych Engine v0.5.2 Game is crashing on warning screen (Mod:Wednesday Infidelity v2)

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#13570]
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/114620759/6a704c60-d6be-4052-9008-7292e43a0c03)

How to fix this. HELP PLEASE!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I just remain only one string in Main.hx

**Comment by MaksPRO12667** [comment]
HELP ME PLEASE!

**Comment by ShadowMario** [comment]
This version is not supported and this could be an issue with the mod itself.

**Comment by MaksPRO12667** [comment]
> This version is not supported and this could be an issue with the mod itself.

But... This is mod only work on v0.5.2 version...
I think the game is crashing because of the cursor... Idk how i found it, but when i open game, I saw this:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/114620759/b2527bae-6168-412a-8afd-2bc314a43c15)

(I think I'm totally stupid)

**Comment by fnffan32918** [comment]
no this appears to be a new problem, im having it too
