### ISSUE TITLE
Add stacked events

### ISSUE THREAD

**Issue by CyndaquilDAC** [ShadowMario/FNF-PsychEngine#1357]
### Idea
I recommend you make it so multiple events can be stacked onto one event note.

### Why?
Without this, you can't sync multiple events on the same step, which is really annoying when you (for example) want to change gf's speed and swap one of the characters at the same time.

**Comment by titopops** [comment]
it is possible to stack events, with the strum time for notes, but its pretty much all we can do until we get more space for events
![image](https://user-images.githubusercontent.com/93490646/143510647-6b23f837-c630-4354-b844-8e99b232b84e.png)
(also strum time applies with selected event notes too)

**Comment by EddyEddyEd** [comment]
or just zoom in (press x, can go up to x24) and the notes will be so squished together that they will be basically one note

**Comment by IAMEC123** [comment]
> or just zoom in (press x, can go up to x24) and the notes will be so squished together that they will be basically one note

zooming in only zooms in for the chart editor and doesnt change the actual chart

**Comment by MayoALT** [comment]
> > or just zoom in (press x, can go up to x24) and the notes will be so squished together that they will be basically one note
> 
> zooming in only zooms in for the chart editor and doesnt change the actual chart

thats just wrong you can test it yourself in the chart editor

**Comment by ShadowMario** [comment]
0.5 is out.
