### ISSUE TITLE
can you add hxlua instead of linc_luajit?

### ISSUE THREAD

**Issue by JonnycatMeow** [ShadowMario/FNF-PsychEngine#13577]
### What is your question?

hxlua provides support for multiple diffrent operating systems including wasm which basically converts the cpp code into Friday night funkin web.  this could add a mods for the web so you could instead having to remake the source code.

here is the link:https://github.com/MAJigsaw77/hxlua

**Comment by JonnycatMeow** [comment]
i can understand why you could be a little iffy but I promise you its good and plus luajit can't build wasm

**Comment by CaptainBaldi** [comment]
theres no real reason to switch currently
i could see this maybe getting accepted as a pull request but i doubt shadow would implement this on his own

**Comment by ThePlank** [comment]
> here is the link:https://github.com/MAJigsaw77/hxlua

ok i guess but

why the mid hxlua tho

**Comment by JonnycatMeow** [comment]
because it would have wasm support or web support

**Comment by crowplexus** [comment]
this is pointless given that psych does not support html5 anymore
