### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by cheemynugget2** [ShadowMario/FNF-PsychEngine#1358]
### Describe your problem here.

Im trying to find a way to increase the intensity of the healthbar icons

sorta like 
https://www.youtube.com/watch?v=KqgI91g824k

or 

https://www.youtube.com/watch?v=effw_5KV4-Q

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

so far ive added characters and changed stage lua codes and a bit more but not much

**Comment by ShadowMario** [comment]
Oh no not another Dave & Bambi port omfg

**Comment by ShadowMario** [comment]
Plus Psych Lua doesn't support shaders.
