### ISSUE TITLE
Song bug (experimental)

### ISSUE THREAD

**Issue by LeonGamerPS4** [ShadowMario/FNF-PsychEngine#13581]
### Describe your bug here.

Game crashes whenever I try to play a song or play a song in the freeplay menu.

### Command Prompt/Terminal logs (if existing)

```bash
openfl/events/SampleDataEvent.hx (line 189)
openfl/media/Sound.hx (line 748)
flixel/sound/FlxSound.hx (line 623)
flixel/sound/FlxSound.hx (line 487)
flixel/system/frontEnds/SoundFrontEnd.hx (line 122)
states/PlayState.hx (line 1185)
states/PlayState.hx (line 1655)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: To be consistent with flash the listener function registered to SampleDataEvent has to provide between 2048 and 8192 samples.
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I only edited the songs, some images, Project.xml, and MainMenuState.hx

**Comment by LeonGamerPS4** [comment]
this is the latest experimental branch as of this issue

**Comment by JordanSantiagoYT** [comment]
are you using openfl git or openfl 9.2.1

**Comment by LeonGamerPS4** [comment]
openfl 9.3.2

**Comment by JordanSantiagoYT** [comment]
i had the issue as well but switching to 9.2.1 solved it

**Comment by LeonGamerPS4** [comment]
------------------------SScript 7.0.0 Macro------------------------
Special Thanks:
- CrowPlexus

Checking version...
You are using the 4.2.5 version of Haxe, SScript works best with Haxe 4.3.2. Consider updating Haxe.
Continuing...
-------------------------------------------------------------------

source/flixel/sound/FlxSound.hx:601: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/sound/FlxSound.hx:605: characters 19-27 : flash.media.SoundChannel has no field __source

**Comment by JordanSantiagoYT** [comment]
what version of flixel are you using? i think it works best with 5.2.2

**Comment by LeonGamerPS4** [comment]
```
------------------------SScript 7.0.0 Macro------------------------
Special Thanks:
- CrowPlexus

Checking version...
You are using the 4.2.5 version of Haxe, SScript works best with Haxe 4.3.2. Consider updating Haxe.
Continuing...
-------------------------------------------------------------------

source/flixel/sound/FlxSound.hx:601: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/sound/FlxSound.hx:605: characters 19-27 : flash.media.SoundChannel has no field __source
```

**Comment by LeonGamerPS4** [comment]
btw this only applies to modded songs
