### ISSUE TITLE
how do i fix this?

### ISSUE THREAD

**Issue by Airblast66** [ShadowMario/FNF-PsychEngine#13596]
### Describe your problem here.

i tried compiling 
![erfhsudcioiw](https://github.com/ShadowMario/FNF-PsychEngine/assets/136195953/abc8b598-5f17-4074-860d-c796b67408f6)
and i got this error

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no!

**Comment by crowplexus** [comment]
can you run these commands on your terminal and try again?

```
haxelib update flixel
haxelib update-flixel-addons
haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev
```
