### ISSUE TITLE
Trying to open Themed Concept on v0.6.3...

### ISSUE THREAD

**Issue by ConnorMugaasOfficial** [ShadowMario/FNF-PsychEngine#13597]
### Describe your problem here.

So, I made a track called Themed Concept, for Vs. Tailsonic V3. HOWEVER, after I _finally_ charted it, this happened:

PlayState.hx (line 1552)
PlayState.hx (line 1499)
PlayState.hx (line 2547)
PlayState.hx (line 2521)
PlayState.hx (line 1072)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

I labeled this as "Help me!" because I've been trying to work this around and have not gotten anywhere, so any help would be very much appreciated.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Plenty of things before, but not at the moment.

**Comment by ConnorMugaasOfficial** [comment]
If you want the chart, I'll send it here:
[tailsonic-themedconcept.json](https://github.com/ShadowMario/FNF-PsychEngine/files/13325897/tailsonic-themedconcept.json)
[bf-themedconcept.json](https://github.com/ShadowMario/FNF-PsychEngine/files/13325898/bf-themedconcept.json)
[bf-scared-themedconcept.json](https://github.com/ShadowMario/FNF-PsychEngine/files/13325899/bf-scared-themedconcept.json)
[gf.json](https://github.com/ShadowMario/FNF-PsychEngine/files/13325900/gf.json)
[tailsonicneon.json](https://github.com/ShadowMario/FNF-PsychEngine/files/13325901/tailsonicneon.json)
[bf.json](https://github.com/ShadowMario/FNF-PsychEngine/files/13325902/bf.json)
[themed-concept.json](https://github.com/ShadowMario/FNF-PsychEngine/files/13325903/themed-concept.json)

**Comment by ConnorMugaasOfficial** [comment]
[themed-concept.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/13325909/themed-concept.zip)

**Comment by ConnorMugaasOfficial** [comment]
The ZIP is just for the song audio.

**Comment by ConnorMugaasOfficial** [comment]
All other files except themed-concept.json is are character files.

**Comment by ConnorMugaasOfficial** [comment]
![TailsonicNEW](https://github.com/ShadowMario/FNF-PsychEngine/assets/122640683/edea259b-00f9-492e-93ac-faa46ee19131)
![BFTC](https://github.com/ShadowMario/FNF-PsychEngine/assets/122640683/fcf34901-c109-436e-8064-c11a9d105063)
![TailsonicNEWTC](https://github.com/ShadowMario/FNF-PsychEngine/assets/122640683/51a1aa58-d272-409b-b305-418cd9b35581)
![scaredBFTC](https://github.com/ShadowMario/FNF-PsychEngine/assets/122640683/bee1c40d-6311-4b66-b01e-af2fb8b7eee7)

**Comment by ConnorMugaasOfficial** [comment]
These are PNG files for the characters.

**Comment by ConnorMugaasOfficial** [comment]
[xmls.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/13325921/xmls.zip)
Zip file for XML character files.

**Comment by ConnorMugaasOfficial** [comment]
One more thing to mention: It works _without_ events, although they are technically required for the transition in the track. That's why the track was named "Themed Concept".

**Comment by crowplexus** [comment]
when making issues please try to generalize your question or bug report in such a way that it focus on the error

what version of the engine are you running?

**Comment by ConnorMugaasOfficial** [comment]
0.6.3

**Comment by crowplexus** [comment]
> 0.6.3

I have a hunch that your chart may be badly formatted, can you try to open it on the chart editor and see what happens?

**Comment by ConnorMugaasOfficial** [comment]
I tried it again and it still gave me the error

**Comment by ConnorMugaasOfficial** [comment]
But it will show when I click Reload JSON, it just won't let me play the chart.

**Comment by ConnorMugaasOfficial** [comment]
If you wanna look at the chart, I did attatch it in an earlier comment as "themed-concept.json".

**Comment by ConnorMugaasOfficial** [comment]
I believe part of this is an event issue, but I don't get what I did wrong.

**Comment by crowplexus** [comment]
send the json, I wanna try to fix it

**Comment by ConnorMugaasOfficial** [comment]
[themed-concept.json](https://github.com/ShadowMario/FNF-PsychEngine/files/13464914/themed-concept.json)

**Comment by crowplexus** [comment]
here

[themed-concept.json](https://github.com/ShadowMario/FNF-PsychEngine/files/13465033/themed-concept.json)
[events.json](https://github.com/ShadowMario/FNF-PsychEngine/files/13465034/events.json)

**Comment by ConnorMugaasOfficial** [comment]
I tried it again and it still didn't work, but now a few of the error lines went away even though some of them are still there. Thanks for helping though

**Comment by ConnorMugaasOfficial** [comment]
Also the error appears instantly when I open the chart again

**Comment by crowplexus** [comment]
did you modify the way psych loads notes? I tried to opened yours on a clean build and it worked just fine

**Comment by ConnorMugaasOfficial** [comment]
Even though this is closed now, I just wanted to say that I finally figured out what the problem was. Apparently, I didn't have the .json files and XML/PNG files in the right places.
