### ISSUE TITLE
i cant open my damn psych engine

### ISSUE THREAD

**Issue by crashok20185** [ShadowMario/FNF-PsychEngine#1359]
### Describe your problem here.

so when i try to execute the psych engine exe it doesnt open i click so much and it doesnt open still....if the devs or someone knows how to help please replie here and how

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Reycko** [comment]
If you opened from the .zip file, Extract it.
Else try reinstalling.
