### ISSUE TITLE
SScript version problem

### ISSUE THREAD

**Issue by VideoBotYT** [ShadowMario/FNF-PsychEngine#13594]
### Describe your problem here.

I'm updating my mod to the latest PsychEngine version but when i set all the libraries to the right version and i try to compile the game i get this
<img width="849" alt="image" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/113830775/2dcaada9-7860-4754-822a-299ad6c09dbc">

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no i always do a fresh compile even if everything is fine with installing i first try to compile it with no changes

**Comment by GAMERMEER** [comment]
ow by the way in this link https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions
it said for me to set SScript in this version: SScript: 6.1.80.

**Comment by GAMERMEER** [comment]
and if i use the latest version of SScript i get these errors
<img width="848" alt="image" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/113830775/be36ebee-3357-488d-b469-cc0fa83287ce">
