### ISSUE TITLE
How can I disable Anti-aliasing on the health bar?

### ISSUE THREAD

**Issue by TerminationDX** [ShadowMario/FNF-PsychEngine#13592]
### Describe your problem here.

I was changing the image of my health bar to a pixel one but it was too small.  So I scaled it up but it ended up blurry. Everything Ive tried doesn't remove the blurriness including setproperty("healthBar.antialiasing", false). What else can I do?
![healthBar](https://github.com/ShadowMario/FNF-PsychEngine/assets/102872464/d147704d-a142-4ac2-ba69-4f7fe8e6bf7f)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nah

**Comment by BernardoGP4504** [comment]
it's `setProperty` and, if you're using Psych 0.7+ then do
```lua
setProperty('healthBar.bg.antiliasing', false)
``` 

But, if you're using 0.6.3 or lower, instead do
```lua
setProperty('healthBarBG.antialiasing', false)
```

**Comment by TerminationDX** [comment]
THANK YOU

**Comment by TerminationDX** [comment]
@BernardoGP4504 If possible, Could you also tell me how to scale the health bar colors?

**Comment by TerminationDX** [comment]
THANKS BRO
