### ISSUE TITLE
Please stop overriding files in source/flixel/

### ISSUE THREAD

**Issue by Geokureli** [ShadowMario/FNF-PsychEngine#13590]
### Hello PsychEngine, It's me the HaxeFlixel Guy

I've come to request that you please stop putting replacement haxelib files in source/flixel, this is really really really REALLY terrible for the haxe ecosystem and it's personally causing a ton of suffering in my life. if you want to add a feature to a flixel class, either extend it or submit/request a change on the [flixel github](https://github.com/HaxeFlixel/flixel), every implemented feature I've seen here can easily be done without using a replacement file, and we implemented some of them in flixel.

I get a ton of people asking me about bugs that I've already fixed and I spend hours tearing my hair out trying to find out why it's still happening for them. You're also only hurting yourself, sure replacing a file may save you a deprecation warning, but it often causes errors in later updates, which is why this project is probably so behind. Further more it's impossible to tell why these files were replaced by looking at them, so fixing the root issue, or even identifying when they are fixed becomes very difficult. It's also harder to reuse code from/in other projects.

It's just really the worst thing you can do for open source software. 

I [forked the repo](https://github.com/Geokureli/FNF-PsychEngine/commit/5477ef5d690e7d340fe1d4ab4826a198db237229) and deleted the flixel, lime, openfl and hx folders and it seems to compile just fine, after a few minutes of work. If there's any specific things you want me to test with this fork, just let me know. I'm willing to step in and put in work getting this and a few dependent projects up to latest versions since it will greatly reduce my stress in the long run, and if you have future changes that require these file replacements please avoid them, do not normalize this, if you don't see a way around it, talk to me, I probably have a better suggestion. 

What I'm seeming here in this community is a wall being built between Psych and Flixel, when it could be a bridge!

Pinging contributors for better visability: @ShadowMario @crowplexus

**Comment by crowplexus** [comment]
YES, YES, YES, TEN TIMES YES

the amount of times I ran into issues compiling legacy versions of Psych because of overridden classes is unreal and I hate it so much

opening a PR soon

**Comment by Geokureli** [comment]
Also feel free to hit me up on discord to talk, I'm always in the flixel channel of the [Haxe Discord](https://discordapp.com/invite/rqEBAgF) or you can PM me

**Comment by Geokureli** [comment]
thanks!

**Comment by Geokureli** [comment]
Hey @ShadowMario, it's me again, I see this is still happening via [#137](https://github.com/ShadowMario/FNF-PsychEngine/pull/13795)

Pinging @FixedData as well
When people notice bugs in flixel and try to fix them by committing shadowed classes to Psych, please summon me, so that we can fix the issue in flixel rather than putting a temp bandaid in psych that will eventually cause errors further down the road

**Comment by Geokureli** [comment]
If you make an issue on the [flixel repos' issues](https://github.com/HaxeFlixel/flixel/issues), I'll usually do one or both of the following:
- fix the issue myself or provide help for others to make the fix if I don't have the time
- recommend a workaround, usually involving extension or something
