### ISSUE TITLE
Ghost Animations

### ISSUE THREAD

**Issue by xboomerboyx** [ShadowMario/FNF-PsychEngine#13593]
### Describe your problem here.

So I want to make a script for my mod where if you are holding 2 hold notes at the same time, one of the animations will be a half opacity animation, just like in the Among Us mod. Is there any way to do this, cause I think I looked up a tutorial before and I couldn't find one.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by SrBagel** [comment]
[NoteGhost.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/13343766/NoteGhost.txt)
Here's one that I use (change the file extension to lua and put it in mods/scripts)

**Comment by xboomerboyx** [comment]
> [NoteGhost.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/13343766/NoteGhost.txt)
> Here's one that I use (change the file extension to lua and put it in mods/scripts)

Thanks you so much. I don’t know how this works, and to be honest, I’m still pretty new to modding, so this helped out a ton.
