### ISSUE TITLE
Compiling trouble

### ISSUE THREAD

**Issue by KlavierGayming** [ShadowMario/FNF-PsychEngine#136]
Welp compiling worked fine before but I decided to mess with psych engine again and uhh
I now get an error saying “source/PlayState:3184:characters 2-10: unexpected override.”
I’ve been stuck on this goddamn error for 30 minutes and I have no idea how to fix it.
Someone help please.

**Comment by KlavierGayming** [comment]
Btw at that line there is override function destroy()

**Comment by ShadowMario** [comment]
The issue is on what happens before that line.

**Comment by KlavierGayming** [comment]
the line above is nothing :/

**Comment by JavierEsDab** [comment]
i also get that but in the vanilla engine
