### ISSUE TITLE
Game crashing when title screen appears HELP!

### ISSUE THREAD

**Issue by TristanBR666** [ShadowMario/FNF-PsychEngine#13605]
### Describe your bug here.

I dont rlly know whats going on can anyone help me, also im not a dev im just trying to play a mod and this happens

### Command Prompt/Terminal logs (if existing)

```bash
flixel/sound/FlxSound.hx (line 593)
flixel/sound/FlxSound.hx (line 731)
flixel/sound/FlxSoundGroup.hx (line 52)
flixel/system/frontEnds/SoundFrontEnd.hx (line 327)
flixel/system/frontEnds/SoundFrontEnd.hx (line 319)
flixel/FlxGame.hx (line 618)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by ShadowMario** [comment]
Seems like an issue with the assets folder
