### ISSUE TITLE
Null Object Reference when opening Character editor

### ISSUE THREAD

**Issue by TRSF-sonicman** [ShadowMario/FNF-PsychEngine#13604]
### Describe your problem here.

I received this message:

FlxUIDropDownMenuCustom.hx (line 343)
editors/CharacterEditorState.hx (line 1070)
editors/CharacterEditorState.hx (line 439)
editors/CharacterEditorState.hx (line 195)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

All I did was add images that I was told to implement, no changes within source as of now.

**Comment by ShadowMario** [comment]
Closing this issue because Chart Editor has been pretty much fully redone so it likely does not happen anymore
