### ISSUE TITLE
A few (CRASY) suggestions to the enguine!!!

### ISSUE THREAD

**Issue by LionKrono** [ShadowMario/FNF-PsychEngine#13600]
### What feature do you want to get added on the **base** engine?

My suggestions are these:

- Add an editor for the menus:
In Friday Night Funkin' there are a lot of things, one of those are the menus, what im suggesting is that i want to add a menu with LUA, like:
"i want to modify the Main Menu adding a Gallery button, after that the gallery button loads a song or something like that.."
and to modify the objects order and somethings like adding things to the background without the need of modify the assets that are already on the game.

Or in the Freeplay menu or Options, something more customisable.
This includes adding options via LUA

- Add Multiplayer
I know that this is crasy but, it would be cool to have a multiplayer menu. where you can play local and online, there is already a multiplayer mod made by Shaddow Mario ([this one](https://gamebanana.com/mods/44205)) why don't add something like that!!! a feature that whould end up seeng like the Unamed Multiplayer Mod

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by CaptainBaldi** [comment]
never suggest again........................

**Comment by LeonGamerPS4** [comment]
why

**Comment by DisIsNOt** [comment]
![skeleton-spinning.gif](https://github.com/ShadowMario/FNF-PsychEngine/assets/78010753/63786748-2b4d-4dd0-9180-671a9c72a2ee)

**Comment by BernardoGP4504** [comment]
First, this said multiplayer mod wasn't coded or made by ShadowMario. They just used some (if not all) code from Psych Engine.

Also, your suggestions are not gonna be even considered because you failed the test

**Comment by ThePlank** [comment]
> - Add Multiplayer

yeah no, most likely impossible.

if shadowmario whould add multiplayer he would need to make the client source closed to not allow for modified clients to use it

**Comment by Swapper1** [comment]
> * Add Multiplayer
>   I know that this is crasy but, it would be cool to have a multiplayer menu. where you can play local and online, there is already a multiplayer mod made by Shaddow Mario ([this one](https://gamebanana.com/mods/44205)) why don't add something like that!!! a feature that whould end up seeng like the Unamed Multiplayer Mod

That the feature for Full Ass Game, so... no. Not only when they have the another FNF multiplayer ones [like this one](https://gamebanana.com/mods/286594), but impossible. Especially if he make an close source.

**Comment by BernardoGP4504** [comment]
> * Add an editor for the menus:
> In Friday Night Funkin' there are a lot of things, one of those are the menus, what im suggesting is that i want to add a menu with LUA, like:
> "i want to modify the Main Menu adding a Gallery button, after that the gallery button loads a song or something like that.."
> and to modify the objects order and somethings like adding things to the background without the need of modify the assets that are already on the game.
> 
> 
> Or in the Freeplay menu or Options, something more customisable. This includes adding options via LUA
Bro 💀
If you have the ability to modify the source directly (which is easier) why use Lua? Scripting is meant to modify gameplay, not menus.

And we can't forget; **✨✨ **You Failed Successfully.** ✨✨**
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
>
> Proper credit that was forgotten

**Comment by BernardoGP4504** [comment]
Also, is there any admin to close this issue?

**Comment by PatoFlamejanteTV** [comment]
VERY CRASY LIL' BRO!!! HOPE Shaddow MARIO SEES THIS!!!
