### ISSUE TITLE
Issue!

### ISSUE THREAD

**Issue by ItsYaProgramPlayzXD** [ShadowMario/FNF-PsychEngine#13608]
### Describe your bug here.

Heres The Issue [Unknown Engine 2.0]
PlayState.hx (line 940)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 940)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes. I Put 2 Mods

**Comment by LeonGamerPS4** [comment]
wrong repo bud
