### ISSUE TITLE
Remove boyfriend arrow glow

### ISSUE THREAD

**Issue by PiotrekMineRoblox** [ShadowMario/FNF-PsychEngine#13602]
### What is your question?

Hello
I want to know how to remove boyfriend arrow glow like in base game and kade engine using Lua scripts
Also I don't mean the "sick" and "good" or the splash stuff
I mean when the arrows itself glow when it's the boyfriend turn

**Comment by wj1ajao39sjak927** [comment]
isn't that supposed to be for the opponent?

**Comment by Kelaphi** [comment]
> isn't that supposed to be for the opponent?

no :/ he just said boyfriend arrow glow... u blind?

**Comment by wj1ajao39sjak927** [comment]
i'm not blind i can see clearly thank you
also, maybe there's a script to get rid of the strumline glowing.

**Comment by wj1ajao39sjak927** [comment]
Is there a version that's for the opponent?

**Comment by Stefan2008Git** [comment]
> ### What is your question?
> Hello I want to know how to remove boyfriend arrow glow like in base game and kade engine using Lua scripts Also I don't mean the "sick" and "good" or the splash stuff I mean when the arrows itself glow when it's the boyfriend turn

You can disable it with source code method too instead of Lua only
