### ISSUE TITLE
Compiler error; source/psychlua/HScript.hx:168: characters 89-94 : Type not found : SCall

### ISSUE THREAD

**Issue by MrKitten1753** [ShadowMario/FNF-PsychEngine#13613]
### Describe your problem here.

I am attempting to compile a completly vanilla, unmodified version of this engine. However the compiler has only one error:

source/psychlua/HScript.hx:168: characters 89-94 : Type not found : SCall

I am reviewing the code in HScript.hx, and the line it is referring to is this:

public function executeCode(?funcToRun:String = null, ?funcArgs:Array<Dynamic> = null):SCall

I am unfamiliar with this language, and I am not sure what SCall is referring to. What do I do?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Piberto-hmm** [comment]
Yeah I have the same issue, im trying to find a way to fix it

**Comment by Piberto-hmm** [comment]
I think i found the solution https://github.com/ShadowMario/FNF-PsychEngine/issues/13632#issuecomment-1817653404
