### ISSUE TITLE
null object reference

### ISSUE THREAD

**Issue by dsbuduianoxjk** [ShadowMario/FNF-PsychEngine#13614]
### Describe your bug here.

every time i load up my character (it is a png and i have the mlx file for it but i might have done something wrong there) the character was made in Microsoft paint and the mxl file was made in notepad, there are five animations (they are all just one frame so technically five pictures) i put them in the my-mods\images\character folder

the character in paint
![image_2023-11-15_230901433](https://github.com/ShadowMario/FNF-PsychEngine/assets/150973960/52fe728d-20a4-4a7c-a78e-83f52c0729f1)

the character+xml file in the folder
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/150973960/53a23c0f-fd74-4845-989f-2ddab464b513)

the code for the xml file
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/150973960/45f51838-75ac-42ad-a00c-f7c7df4beebe)

and the error itself
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/150973960/b7838cae-26b4-4aa8-81e7-760e9ab6dfa8)

it only seems to happen when i put the characters name in the image section then refresh i get this

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

only added the character and xml file

**Comment by dsbuduianoxjk** [comment]
btw i downloaded the game from gamebannana if that helps

**Comment by dsbuduianoxjk** [comment]
if you want more info just ask i am happy to share (unless it's personal or not helpful for this lol)

**Comment by wj1ajao39sjak927** [comment]
it's supposed to be an xml not an mlx or whatever

**Comment by wj1ajao39sjak927** [comment]
i think you should split the sprites and make a new xml with spritesheet and xml generator for fnf or free texture packer

**Comment by wj1ajao39sjak927** [comment]
or adobe animate if you can afford that

**Comment by wj1ajao39sjak927** [comment]
basically you just got the file extension wrong, change it from "mlx" or "mxl" to "xml".

**Comment by dsbuduianoxjk** [comment]
it works now thanks @wj1ajao39sjak927
