### ISSUE TITLE
Errors about HScript/psychlua

### ISSUE THREAD

**Issue by NizamX64** [ShadowMario/FNF-PsychEngine#13615]
### Describe your bug here.

Everytime I tried to compile the game, it will always complaining about HScript/SScript. Haven't edit anything yet. I'm also using the source code from the experimental branch.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/99819772/1c39dd79-fe16-472a-914a-2e8c4c1f8e5e)

### Command Prompt/Terminal logs (if existing)

```bash
------------------------SScript 7.7.0 Macro------------------------
Special Thanks:
- CrowPlexus

Checking version...
You are using the 4.2.5 version of Haxe, SScript works best with Haxe 4.3.2 or newer. Update your Haxe version.
Continuing...
-------------------------------------------------------------------

source/psychlua/HScript.hx:301: characters 9-13 : tea.SScript has no field kill
source/psychlua/HScript.hx:296: characters 27-31 : Field kill is declared 'override' but doesn't override any field
source/psychlua/HScript.hx:33: characters 7-15 : psychlua.HScript has no field doScript
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, no files were edited yet.

**Comment by NizamX64** [comment]
I also have tried with the latest version of Haxe, but it will output more errors instead.

**Comment by NizamX64** [comment]
So, I found the fix:
1. For the error about the keyword 'override', go to source/psychlua/HScript.hx:296, then delete the keyword 'override'. Issue fixed.
2. For the doScript error, go to source/psychlua/HScript.hx:31, then comment the entire 'else' statement.
3. For the 'field kill' error, go to source/states/PlayState.hx, go to line 419, 604, 808 and comment the entire 'if' statement. And also comment line 3103.

**Comment by Charmanny** [comment]
> So, I found the fix:
> 
> 1. For the error about the keyword 'override', go to source/psychlua/HScript.hx:296, then delete the keyword 'override'. Issue fixed.
> 2. For the doScript error, go to source/psychlua/HScript.hx:31, then comment the entire 'else' statement.
> 3. For the 'field kill' error, go to source/states/PlayState.hx, go to line 419, 604, 808 and comment the entire 'if' statement. And also comment line 3103.
hey what do you mean by "comment the entire "else" statement" like do you mean delete it?
