### ISSUE TITLE
null object refference

### ISSUE THREAD

**Issue by BL09** [ShadowMario/FNF-PsychEngine#13628]
### Describe your bug here.

i can't play cash money (from ourple guy v3) since the glitch part because this error appears every time. i checked files and chart but all sems to be ok. any help?
![Captura de pantalla 2023-11-18 004114](https://github.com/ShadowMario/FNF-PsychEngine/assets/151303866/9f13c2aa-9b85-42da-91e9-602cb306fcbd)
![Captura de pantalla 2023-11-18 003001](https://github.com/ShadowMario/FNF-PsychEngine/assets/151303866/79b17ba1-c0f8-4408-ad25-24ebc5864cd4)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Stefan2008Git** [comment]
Report that error to VS Ourple Guy V3 developers. Psych can't help with that error

**Comment by Stefan2008Git** [comment]
> Report that error to VS Ourple Guy V3 developers. Psych can't help with that error

I mean, they can, but for popular mods can't if i am not wrong
