### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by SuperPokeBros** [ShadowMario/FNF-PsychEngine#13629]
### Describe your problem here.

BUILDING GAME
------------------------SScript 7.0.0 Macro------------------------
Special Thanks:
- CrowPlexus

Checking version...
You are using the 4.2.5 version of Haxe, SScript works best with Haxe 4.3.2. Consider updating Haxe.
Continuing...
-------------------------------------------------------------------

source/backend/Paths.hx:577: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)

done.
Press any key to continue . . .

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Jamextreme140** [comment]
The "loadAtlasEx" function does not exist in the official FlxAnimate code.

ShadowMario has a custom fork of FlxAnimate for it, so you need to install it from the custom fork:
`haxelib git flxanimate https://github.com/ShadowMario/flxanimate.git dev`

**Comment by Filip55561** [comment]
> The "loadAtlasEx" function does not exist in the official FlxAnimate code.
> 
> ShadowMario has a custom fork of FlxAnimate for it, so you need to install it from the custom fork: `haxelib git flxanimate https://github.com/ShadowMario/flxanimate.git dev`

weird, I can do it with just `haxelib install FlxAnimate` and the error is never there
