### ISSUE TITLE
How i can restore combo png like golden apple

### ISSUE THREAD

**Issue by matepro260** [ShadowMario/FNF-PsychEngine#13621]
### Describe your problem here.

so, im making a gapple port or smth  (i dont know really) but im trying to get combo Sprite like golden apple, 

so i cant do it.....

can someone help me?
![Captura de pantalla 2023-11-16 183855](https://github.com/ShadowMario/FNF-PsychEngine/assets/75801616/8cca71a5-2a82-4954-a524-16f95808ad26)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no. i didnt

**Comment by crowplexus** [comment]
place this on the `mods/<yourmod>/scripts` folder with the name `restoreComboSprite.lua`

```lua
setProperty("showCombo", true)
```

**Comment by BernardoGP4504** [comment]
> place this on the `mods/<yourmod>/scripts` folder with the name `restoreComboSprite.lua`
> 
> ```lua
> setProperty("showCombo", true)
> ```

Bro
> ### Are you modding a build from source or with lua?
> Source

**Comment by crowplexus** [comment]
find `showCombo` in PlayState and enable it

**Comment by matepro260** [comment]
thx for it! but its not like that

**Comment by BernardoGP4504** [comment]
In `popUpScore()`, change this line `insert(members.indexOf(strumLineNotes), rating)`, to this:
```haxe
insert(members.indexOf(strumLineNotes), rating);
insert(members.indexOf(strumLineNotes), comboSpr);
```

**Comment by matepro260** [comment]
im on experimental bracnh

**Comment by BernardoGP4504** [comment]
> im on experimental bracnh

Find `comboGroup.add(rating)` and change it to:
```haxe
comboGroup.add(rating);
comboGroup.add(comboSpr);
```

**Comment by matepro260** [comment]
didnt work,

**Comment by BernardoGP4504** [comment]
> didnt work,

How so? And send your popUpScore PlayState function here so I can help you

**Comment by matepro260** [comment]
so i need to send playstate.hx?

**Comment by BernardoGP4504** [comment]
> so i need to send playstate.hx?

No, only the popUpScore function

**Comment by matepro260** [comment]
how

**Comment by BernardoGP4504** [comment]
> how

You see, the internet has this cool thing called "✨ COPY and PASTE ✨"
So, just paste the function code inside a code block like this
```haxe
function popUpScore()
{
    // da code
}
```

**Comment by BernardoGP4504** [comment]
What's the code in your `popUpScore` in PlayState @matepro260 ?
