### ISSUE TITLE
i cant acces my mods in engine

### ISSUE THREAD

**Issue by noskincz** [ShadowMario/FNF-PsychEngine#13623]
### Describe your problem here.

Every single time i open the mods section in psych engine 0.6.3 it just gives me an error
the error:
![help](https://github.com/ShadowMario/FNF-PsychEngine/assets/84130850/7326690a-31e3-4ec8-b9b7-0a54dcd8d857)
if anyone knows how to fix it pls help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
One of your Mod's JSON files is broken (I'd say check your pack.json file if you have one), most likely missing a `,` somewhere or you added an extra `,` at the end.
