### ISSUE TITLE
BF voice plugins

### ISSUE THREAD

**Issue by Kronkze** [ShadowMario/FNF-PsychEngine#1363]
### What is your question?

bf's voice is getting shorter when going normal and seems fast (fl studio)

https://user-images.githubusercontent.com/95048943/143490159-4e101a61-5425-4264-b2ef-fa3c88c7cc07.mp4

![Ekran Alıntısı](https://user-images.githubusercontent.com/95048943/143490362-40a57493-6390-41cb-b476-bd3f0b5c7070.PNG)
o)

**Comment by PoleyMagik** [comment]
Not the place to post this, but to sum it up: Pitch and speed are things that directly corelate with one another when pitch chaning the rudimentary way. Find some other way to change the pitch of the samples.

**Comment by ShadowMario** [comment]
????
