### ISSUE TITLE
source code not compiling

### ISSUE THREAD

**Issue by Toys2313Real** [ShadowMario/FNF-PsychEngine#13637]
### Describe your problem here.

im trying to compile a psych build but i get multiple errors and it wont go, the engine is extra keys reimagined (tposejank)
also im posting this here cuz the disussions and stuff on the ek github page is dead af
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/144585770/803b0ac2-24d8-4bc1-8dc4-8a1d6634580f)
(https://github.com/tposejank/FNF-PsychEngine/tree/extra-keys-reimagined)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Filip55561** [comment]
for FlxSound use openfl version 9.3.0

**Comment by Toys2313Real** [comment]
i already have it installed and nothing changes when i reinstall

> for FlxSound use openfl version 9.3.0

**Comment by TomVN1230101** [comment]
> i already have it installed and nothing changes when i reinstall
> 
> > for FlxSound use openfl version 9.3.0

i know

**Comment by Filip55561** [comment]
try haxelib set SScript 7.0.0
and haxelib set openfl 9.3.0
