### ISSUE TITLE
Graphic Settings crashes the game

### ISSUE THREAD

**Issue by Gui-iago** [ShadowMario/FNF-PsychEngine#1364]
### Describe your bug here.

on the Compiled Linux Build, opening Graphic Settings simply crashes the game, even without modifying anything

https://user-images.githubusercontent.com/45212377/143494074-9f0ce146-4f89-4b55-be77-d2ebcf9be3f2.mp4

### Command Prompt/Terminal logs (if existing)

```bash
Compiling group: haxe
g++ -Iinclude -I/home/gui/.haxe/lib/discord_rpc/git/linc/ -c -fvisibility=hidden -O2 -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -m64 -DHXCPP_M64 -I/home/gui/.haxe/lib/hxcpp/4,2,1/include ... tags=[haxe,static]
 - src/lime/utils/AssetCache.cpp  [haxe,release]
Link: ApplicationMain
AL lib: (EE) GetLoadedHrtf: Invalid header in /usr/share/openal/hrtf/Default HRTF.mhr: "MinPHR03"
AL lib: (EE) GetLoadedHrtf: Failed to load /usr/share/openal/hrtf/Default HRTF.mhr
source/Discord.hx:67: Discord Client initialized
source/Discord.hx:17: Discord Client starting...
source/Discord.hx:24: Discord Client started.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't edit anything

**Comment by Gui-iago** [comment]
I should also mention the rest of the options menu works aside from the graphic settings

there's a big typo on "Hide Song Length", it just gives the Anti-Aliasing option Description

https://user-images.githubusercontent.com/45212377/143494418-6bbecd8b-870d-4fd0-a740-669e1a1877fc.mp4

**Comment by Sanscode1937** [comment]
this happen to me too
