### ISSUE TITLE
Exe Icon Won't Change

### ISSUE THREAD

**Issue by BlazingBoss** [ShadowMario/FNF-PsychEngine#13643]
### Describe your problem here.

In the older version, I could add my own icons to the art folder and change the line at the bottom of the project.xml file to correspond to that name. Now, when I try this with the latest version, neither changing the xml line name nor simply replacing the icon16 - iconOG file with the picture I want seems to change the icon. The name change stays but I don't know why the icon won't change. Just looking for any way to fix this. Not a huge deal but I just noticed this.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I tried to change the exe file icon in the project.xml file.

**Comment by BernardoGP4504** [comment]
Before you go changing the icons, make sure to delete older builds in the export folder, as sometimes Psych fails to override files

**Comment by BlazingBoss** [comment]
That did the trick, thank you. I was deleting the exe file before exporting but never thought to delete the whole bin file
