### ISSUE TITLE
Windows 7 - windows build starts, processes the assets, then never compiles the game (or ends)

### ISSUE THREAD

**Issue by Lasercar** [ShadowMario/FNF-PsychEngine#13640]
### Describe your problem here.

It's weird, because other people are able to build for windows on windows 7 perfectly fine.

I found someone else with this same issue - https://community.haxe.org/t/nothing-happens-while-compiling/3382
But they never got it solved either by the looks of it (other than using windows 10).

It gets stuck at these commands:

msvs VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\
msvs WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\

I've tried reinstalling MSVC v142 and Windows SDK 10 multiple times, but I get the same thing.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Filip55561** [comment]
I think the Windows SDK is only supported for win 10 and higher

**Comment by mcagabe19** [comment]
msvc 2019 doesn't support windows 7 afaik

**Comment by Filip55561** [comment]
> vs 2019 doesn't support windows 7 afaik

He's telling the truth

**Comment by wj1ajao39sjak927** [comment]
Why are you still using Windows 7? In 2023?

**Comment by JustAFnfPlayeer** [comment]
> Why are you still using Windows 7 in 2023?

Everyone is rich?

**Comment by Lasercar** [comment]
I ask mainly because there's this issue on the FNF source: https://github.com/FunkinCrew/Funkin/discussions/1750
Where people clearly say that they've got it building on windows 7.

**Comment by Filip55561** [comment]
> I ask mainly because there's this issue on the FNF source: [FunkinCrew/Funkin#1750](https://github.com/FunkinCrew/Funkin/discussions/1750) Where people clearly say that they've got it building on windows 7.

afaik Psych isn't the exact same thing as the original game
