### ISSUE TITLE
Help with translating LUA code from 6.3 to 7.1h

### ISSUE THREAD

**Issue by Tattleamelia** [ShadowMario/FNF-PsychEngine#13644]
### Describe your problem here.

I recently made the switch from 0.6.3 to 0.7.1h and doing so broke some code in a mod of mine that detects and increases the deathCounter for a fake death screen.
As such, I just wanted to know; how would I go about translating the following code to work on 7.1h?:
`setPropertyFromClass('PlayState', 'deathCounter', getPropertyFromClass('PlayState', 'deathCounter') + 1)`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by mcagabe19** [comment]
PlayState -> states.PlayState
GameOverSubstate -> substates.GameOverSubState

**Comment by BernardoGP4504** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7

**Comment by Tattleamelia** [comment]
Both of these helped! Thanks a bunch!
