### ISSUE TITLE
Custom Settings

### ISSUE THREAD

**Issue by Sonicgamer2000** [ShadowMario/FNF-PsychEngine#13641]
### Describe your problem here.

I was just wondering how you use the custom settings in the experimental build of psych engine. I got the settings done, I just got to figure out how to use them.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

**Comment by ShadowMario** [comment]
> ### Describe your problem here.
> I was just wondering how you use the custom settings in the experimental build of psych engine. I got the settings done, I just got to figure out how to use them.
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Linux
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> _No response_

You should do the following: `getModSetting('mySetting')`

If your setting is a `keybind`, cache your keys **outside of any function** (recommended) with: `local myKey = getModSetting('mySetting')`, here's an example on Lua, this will play the "hey" animation when you press the custom keybind:

```lua
local myKey = getModSetting('testkey')
debugPrint('testkey: '..myKey.keyboard..', '..myKey.gamepad)

function onUpdatePost(elapsed)
	if getProperty('boyfriend.animOffsets.hey', true) == null then --Character has no 'hey' animation
		return
	end

	if keyboardJustPressed(myKey.keyboard) or anyGamepadJustPressed(myKey.gamepad) then
		playAnim('boyfriend', 'hey', true)
		setProperty('boyfriend.heyTimer', 0.5)
		setProperty('boyfriend.specialAnim', true)
	end
end
```

And here's a HScript equivalent:
```haxe
var myKey = getModSetting('testkey');
debugPrint('testkey: ' + myKey.keyboard + ', ' + myKey.gamepad);

function onUpdatePost(elapsed)
{
	if (game.boyfriend.animOffsets["hey"] == null) //Character has no 'hey' animation
		return;

	if (keyboardJustPressed(myKey.keyboard) || anyGamepadJustPressed(myKey.gamepad))
	{
		game.boyfriend.playAnim('hey', true);
		game.boyfriend.heyTimer = 0.5;
		game.boyfriend.specialAnim = true;
	}
}
```

**Comment by BoomLingReady** [comment]
> > ### Describe your problem here.
> > I was just wondering how you use the custom settings in the experimental build of psych engine. I got the settings done, I just got to figure out how to use them.
> > ### Are you modding a build from source or with Lua?
> > Lua
> > ### What is your build target?
> > Linux
> > ### Did you edit anything in this build? If so, mention or summarize your changes.
> > _No response_
> 
> You should do the following: `getModSetting('mySetting')`
> 
> If your setting is a `keybind`, cache your keys **outside of any function** (recommended) with: `local myKey = getModSetting('mySetting')`, here's an example on Lua, this will play the "hey" animation when you press the custom keybind:
> 
> ```lua
> local myKey = getModSetting('testkey')
> debugPrint('testkey: '..myKey.keyboard..', '..myKey.gamepad)
> 
> function onUpdatePost(elapsed)
> 	if getProperty('boyfriend.animOffsets.hey', true) == null then --Character has no 'hey' animation
> 		return
> 	end
> 
> 	if keyboardJustPressed(myKey.keyboard) or anyGamepadJustPressed(myKey.gamepad) then
> 		playAnim('boyfriend', 'hey', true)
> 		setProperty('boyfriend.heyTimer', 0.5)
> 		setProperty('boyfriend.specialAnim', true)
> 	end
> end
> ```
> 
> And here's a HScript equivalent:
> 
> ```hx
> var myKey = getModSetting('testkey');
> debugPrint('testkey: ' + myKey.keyboard + ', ' + myKey.gamepad);
> 
> function onUpdatePost(elapsed)
> {
> 	if (game.boyfriend.animOffsets["hey"] == null) //Character has no 'hey' animation
> 		return;
> 
> 	if (keyboardJustPressed(myKey.keyboard) || anyGamepadJustPressed(myKey.gamepad))
> 	{
> 		game.boyfriend.playAnim('hey', true);
> 		game.boyfriend.heyTimer = 0.5;
> 		game.boyfriend.specialAnim = true;
> 	}
> }
> ```

holy moly the god himself replied

**Comment by AziziPGM** [comment]
but how to make a setting? not a key.

**Comment by AziziPGM** [comment]
I know I look dumb but someone can help me?

**Comment by Sonicfan0208** [comment]
[
	// All types:
	// bool - Has a checkbox only, meaning it can only be 'true' or 'false'.
	// int - Numbers with no decimals (ex. 1, 3, 9, -1)
	// float - Similar to int, but numbers can have decimals (ex. 1.5, 2.75)
	// percent - Similar to float, but the displayed value is multiplied by 100 (ex. 1.1 will be displayed as "110%")
	// string - A text instead of numbers/false and true, you gotta set up "options" variable to it
	// key - TO BE IMPLEMENTED
	{
		"save": "testbool",
		"name": "Test Bool Option", //Name shown on the mod settings menu
		"type": "bool",
		"description": "This is a test bool option", //Description shown on the mod settings menu
		"value": true //This is the default value
	},
	{
		"save": "testnumber",
		"name": "Test Number Option",
		"type": "float", //
		"description": "This is a test number option",
		"value": 5,
	
		// Int/Float/Percent only variables
		"min": 0, //How low can the value be
		"max": 10, //How high can the value be
		"step": 1, //How much is changed at once when you press left/right

		// Float/Percent only variables
		"decimals": 1, //If your option is type 'float' or 'percent', you should probably make it have atleast 1 decimal places
		"scroll": 5 //How fast you scroll while holding left/right (in this case, it changes 5 per second)
	},
	{
		"save": "teststring",
		"name": "Test String Option",
		"type": "string",
		"description": "This is a test string option",
		"value": "Sun",
		"format": "%vday", //Text formatting, '%v' means 'current value', so if my current value is 'Fri', it wil be shown as 'Friday'. You can also use '%d' to represent the default value

		// String only variables
		"options": ["Sun", "Mon", "Tues", "Wednes", "Thurs", "Fri", "Satur"] //Available options to choose
	},
	{
		"save": "testkey",
		"name": "Test Custom Key",
		"type": "keybind",
		"keyboard": "T",
		"gamepad": "RIGHT_TRIGGER"
	}
]
