### ISSUE TITLE
Images not loading inside the stage (SOURCE)(0.7.1h)

### ISSUE THREAD

**Issue by Chidubemmo** [ShadowMario/FNF-PsychEngine#13650]
### Describe your bug here.

I've made a stage, it has the .hx file, the right directory and everything else.
But every time I load it, It's entirely pitch black because the game couldn't find the image. By going to the command prompt I noticed that instead of using "weekD/images/inn.png" it instead uses "ASSETS/images/inn.png", the directory exists inside week_assets so I don't know what's wrong. 

### Command Prompt/Terminal logs (if existing)

```bash
source/states/LoadingState.hx:160: Setting asset folder to weekD
source/backend/Conductor.hx:128: new BPM map BUDDY []
source/backend/StageData.hx:92: getting stage file...
source/backend/StageData.hx:103: It exists Horray
source/backend/Paths.hx:281: oh no its returning null NOOOO (assets/images/inn.png)
source/backend/StageData.hx:92: getting stage file...
source/backend/StageData.hx:103: It exists Horray
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only added a stage

**Comment by crowplexus** [comment]
can you show us your stage's code?

**Comment by Chidubemmo** [comment]
It's just 2 lines of code (inside create)
```hx
var inn:BGSprite = new BGSprite('inn', X , Y);
add(inn);
```

**Comment by ShadowMario** [comment]
Show your stage .json file if this issue has not been resolved yet
