### ISSUE TITLE
Game crashing due to amount of notes

### ISSUE THREAD

**Issue by Gavinator96** [ShadowMario/FNF-PsychEngine#13657]
### Describe your bug here.

I'm trying to port a chart of Grains of Sand by Andrew Huang from the Clone Hero full 300k note chart to psych engine and the game keeps crashing due to there being too many notes. How do I make the game not crash?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I made a custom modpack with the data of the chart and the song of the chart and I'm on Psych Engine v0.6.3

**Comment by Gavinator96** [comment]
[grainsofsand.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/13445987/grainsofsand.zip)

**Comment by Gavinator96** [comment]
For 1 the song length was messed up, so I fixed that:
[grains-of-sand-chart-2.json](https://github.com/ShadowMario/FNF-PsychEngine/files/13446293/grains-of-sand-chart-2.json)
But the game still crashes whenever I press enter on the song due to 300,000 notes

**Comment by mcagabe19** [comment]
ram fault I did say

**Comment by Cyachao** [comment]
haxe limits 1 object to 1gb max
you can try compiling psych with `HXCPP_GC_BIG_BLOCKS` define flag
i do not guarantee it will work
