### ISSUE TITLE
Disabling the debug keys temporarily in 0.7.1h

### ISSUE THREAD

**Issue by AsterGTheFourth** [ShadowMario/FNF-PsychEngine#13659]
### Describe your problem here.

I've been working on a script, and I want it to have an option to disable access to the debug menus until the song ends, when it enables the keys again. However, it doesn't seem to be able to be doing what it's intended to do. In 0.6.3, this was done using these two sets of code respectively for each scenario:

`setProperty('debugKeysChart', null);
setProperty('debugKeysCharacter', null);`
`setProperty('debugKeysChart', debug_1);
setProperty('debugKeysCharacter', debug_2);`

The one I'm trying to use for disabling for 0.7.1h but I'm having problems with are:

`setPropertyFromClass('backend.ClientPrefs', 'debug_1', null)
setPropertyFromClass('backend.ClientPrefs', 'debug_2', null)`

Is there a working way to do so in Lua? If so, how?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I haven't touched the source code, I've just been using Lua and I've only used the source code as a reference.

**Comment by mcagabe19** [comment]
go Options > Controls and unbind debug

**Comment by AsterGTheFourth** [comment]
> go Options > Controls and unbind debug

True, but the problem is that the way I want it to work is for the script to disable both keys by itself when it's on, and then renable the debug keys once it stops running, regardless of whether or not there are keybinds for them or not.

**Comment by TomVN1230101** [comment]
i can help you

**Comment by AsterGTheFourth** [comment]
The main problem is that I want to make it in Lua, without changing anything in the source code itself. When I checked the difference between the 0.6.3 source code and the 0.7.1h source code, there were no mentions of debugKeysChart or debugKeysCharacter.

**Comment by ShadowMario** [comment]
I just added `allowDebugKeys` on the experimental branch, so this is done

**Comment by KaPi089** [comment]
setProperty('allowDebugKeys', false);
that worked for me
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/121261677/4517c6bf-820e-4443-bfdf-03819d08015b)

**Comment by AsterGTheFourth** [comment]
> setProperty('allowDebugKeys', false); that worked for me ![image](https://private-user-images.githubusercontent.com/121261677/296055367-4517c6bf-820e-4443-bfdf-03819d08015b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNTg3NzEsIm5iZiI6MTcwNTI1ODQ3MSwicGF0aCI6Ii8xMjEyNjE2NzcvMjk2MDU1MzY3LTQ1MTdjNmJmLTgyMGUtNDQ0My1iZmRmLTAzODE5ZDA4MDE1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQxODU0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTliMmNlYTE5ODY2ODhhNWQxODYyZGM1YjU3MDg1MDY5MTNmZWRmZDViMGQyZWJlZjJhMDMwY2QxNWMxZjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JmjJ6UlHbdADmLVe1vZv4XGL9DjpzZpetyJ9eYOTlns)

It was added in a later update, but still, thanks anyways.
