### ISSUE TITLE
Is there any way I can modify `uiPrefix` within Lua?

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#13656]
### What is your question?

In my stage, I set the ui to `cup`, which makes the ratings try to load from there.

But, I don't want to override these images in my custom UI. So how do I make the rating sprites **not** load from `cupUI/`?

**Comment by crowplexus** [comment]
due to the way I designed the system, its not something that you can really do, but I'd definitely go back now and make a better system for it for cases like this

**Comment by ShadowMario** [comment]
i could be wrong but this might be able to change the UI outside of the stage JSON:
`setPropertyFromClass('states.PlayState', 'stageUI', 'myStageUI')`

If you want to change healthBar, you can loadGraphic into its properties:
`loadGraphic('healthBar.bg', 'yourImageHere')`
`loadGraphic('healthBar.leftBar', 'yourImageHere')`
`loadGraphic('healthBar.rightBar', 'yourImageHere')`

Check if these work for whatever you're doing

**Comment by BernardoGP4504** [comment]
> i could be wrong but this might be able to change the UI outside of the stage JSON: `setPropertyFromClass('states.PlayState', 'stageUI', 'myStageUI')`
> 
> If you want to change healthBar, you can loadGraphic into its properties: `loadGraphic('healthBar.bg', 'yourImageHere')` `loadGraphic('healthBar.leftBar', 'yourImageHere')` `loadGraphic('healthBar.rightBar', 'yourImageHere')`
> 
> Check if these work for whatever you're doing

I don't want to change the stageUI directly, I want to stop the ratings (sick, good, etc. And numbers) to stop loading from my ui image folder

**Comment by ShadowMario** [comment]
> > i could be wrong but this might be able to change the UI outside of the stage JSON: `setPropertyFromClass('states.PlayState', 'stageUI', 'myStageUI')`
> > If you want to change healthBar, you can loadGraphic into its properties: `loadGraphic('healthBar.bg', 'yourImageHere')` `loadGraphic('healthBar.leftBar', 'yourImageHere')` `loadGraphic('healthBar.rightBar', 'yourImageHere')`
> > Check if these work for whatever you're doing
> 
> I don't want to change the stageUI directly, I want to stop the ratings (sick, good, etc. And numbers) to stop loading from my ui image folder
```lua
setProperty('showRating', false)
setProperty('showComboNum', false)
setProperty('showCombo', false)
```
Put those in function onCreatePost

**Comment by BernardoGP4504** [comment]
> ```lua
> setProperty('showRating', false)
> setProperty('showComboNum', false)
> setProperty('showCombo', false)
> ```
> 
> Put those in function onCreatePost

So I'm meant to create fake sprites?

**Comment by ShadowMario** [comment]
> So I'm meant to create fake sprites?

Oh so you wanted to make it use the vanilla sprites?? i mean you can just copy and paste them from shared folder

**Comment by BernardoGP4504** [comment]
> > So I'm meant to create fake sprites?
> 
> Oh so you wanted to make it use the vanilla sprites?? i mean you can just copy and paste them from shared folder

Not the graphics, but the sprites `PlayState` makes

**Comment by BernardoGP4504** [comment]
I want to use my custom rating graphics from the global images folder in my mod, where every stage ui uses those graphics
