### ISSUE TITLE
Characters are Broken on Git Build (except for Spirit for some reason)

### ISSUE THREAD

**Issue by Gui-iago** [ShadowMario/FNF-PsychEngine#1365]
### Describe your bug here.

aside from the Story Mode menu, Characters are broken, they don't have any animations and if you try to load any song, it will crash

on Character Editor (sorry if I took ages to check every single animation)

https://user-images.githubusercontent.com/45212377/143495448-bc42d743-685b-4687-884d-41848753647d.mp4

in Game

https://user-images.githubusercontent.com/45212377/143495490-2d4ba148-e175-420c-9d4f-fd77dd74721b.mp4

### Command Prompt/Terminal logs (if existing)

```
source/LoadingState.hx:162: Setting asset folder to shared
source/LoadingState.hx:162: Setting asset folder to shared
source/FreeplayState.hx:292: thorns-hard
source/FreeplayState.hx:299: CURRENT WEEK: week6
source/LoadingState.hx:162: Setting asset folder to week6
source/Conductor.hx:59: new BPM map BUDDY []
source/PlayState.hx:318: stage is: null
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't edit anything

**Comment by DaBanana64** [comment]
I did mention this (#1353) it seems like the whole "softcode atlas package" breaks the whole game, so all we can do is wait for this pull request (https://github.com/ShadowMario/FNF-PsychEngine/pull/1360#issue-1063815820) to merge into the base engine GitHub.

**Comment by Gui-iago** [comment]
> I did mention this (#1353) it seems like the whole "softcode atlas package" breaks the whole game, so all we can do is wait for this pull request ([#1360 (comment)](https://github.com/ShadowMario/FNF-PsychEngine/pull/1360#issue-1063815820)) to merge into the base engine GitHub.

funny enough, everything works on Web, from the previous Bug report I made (#1364), to the characters and the game itself



https://user-images.githubusercontent.com/45212377/143496840-c39e0a49-73bd-48b8-82a8-a183d4354fd1.mp4


https://user-images.githubusercontent.com/45212377/143496819-53a2f321-6dc0-41e6-b5d4-f16a0ea1d863.mp4

**Comment by DaBanana64** [comment]
> > I did mention this (#1353) it seems like the whole "softcode atlas package" breaks the whole game, so all we can do is wait for this pull request ([#1360 (comment)](https://github.com/ShadowMario/FNF-PsychEngine/pull/1360#issue-1063815820)) to merge into the base engine GitHub.
> 
> funny enough, everything works on Web, from the previous Bug report I made (#1364), to the characters and the game itself
> 
>  Characters.mp4 
>  Graphic.Settings.mp4

Maybe because the web version doesn't use the package? I'm not too sure.

**Comment by haya3218** [comment]
Pull request #1360 fixes this. Turns out it was some code failing or just not working and loading packer atlas for the other characters (hence why spirit works) instead of sparrow.

@ShadowMario u stoopid

**Comment by SrtHero278** [comment]
The reason only spirit works is because the game is only looking for txt files. Not both xml files and txt files.

**Comment by ShadowMario** [comment]
Fixed
