### ISSUE TITLE
Artificial Stuttering - Would I be able to code this in lua?

### ISSUE THREAD

**Issue by ColdlordXRepositories** [ShadowMario/FNF-PsychEngine#13653]
### What is your question?

Here's an example of what im talking about:

https://github.com/ShadowMario/FNF-PsychEngine/assets/49921877/0c285ad6-a22a-439e-a5ab-76bf78679fe4

Would there be a way to code this into the game with a lua script? Or do I need to use the source code?
The audio is already edited to work in tandem with the script.

**Comment by ShadowMario** [comment]
I think it IS possible, however I'm not sure how to do it myself.
