### ISSUE TITLE
mustpress is broken when looking at the notes group help

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#13654]
### Describe your problem here.

it's just utterly fucked, i just wanna check if there any notes on the player side why are you counting the oppoents notes, if you set it to set it to true if a note is mustpress EVERY NOTE GOES ON YOUR SIDE, despite the fact the opponents notes shouldn't be mustpress thats how it works right???mus 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
By default, notes follow the strum arrow that is supposed to hit it, however you can turn the note's `copyX` value off, by changing `unspawnNotes[0].copyX` for example

Here are other note properties:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/f1f228f7-7d80-4af8-aa04-174f4b5c395e)
