### ISSUE TITLE
source code not owrking

### ISSUE THREAD

**Issue by baldi2** [ShadowMario/FNF-PsychEngine#13652]
### Describe your problem here.

when i do lime test windows this error happens source/psychlua/HScript.hx:168: characters 89-94 : Type not found : SCall

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i didnt edit anything

**Comment by baldi2** [comment]
i did lime test windows

**Comment by baldi2** [comment]
it didnt work

**Comment by TomVN1230101** [comment]
> it didnt work

i know

**Comment by baldi2** [comment]
ok this is closed i fixed it
