### ISSUE TITLE
Any way to add custom acheivements without source code?

### ISSUE THREAD

**Issue by therealkiddude** [ShadowMario/FNF-PsychEngine#13668]
### Describe your problem here.

I want to make custom achievements, I watch tutorials and they require source code, I found a tutorial that shows how to make custom achievements without source code but realized it was for april fools! Please help!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by CaptainBaldi** [comment]
You will be able to in 0.7.2. Currently, there is no way.
