### ISSUE TITLE
Error when exporting source code about FlxAnimate

### ISSUE THREAD

**Issue by ZaMaXo87** [ShadowMario/FNF-PsychEngine#13667]
### Describe your problem here.

Hi, what's up? well I was trying to export the source code but when I put lime test windows I get
"source/backend/Paths.hx:577: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)"
If anyone could help me I would really appreciate it :)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by KarimAkra** [comment]
> ### Describe your problem here.
> Hi, what's up? well I was trying to export the source code but when I put lime test windows I get "source/backend/Paths.hx:577: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)" If anyone could help me I would really appreciate it :)
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No

run `haxelib remove flxanimate` then `haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev`

**Comment by ZaMaXo87** [comment]
> > ### Describe your problem here.
> > Hi, what's up? well I was trying to export the source code but when I put lime test windows I get "source/backend/Paths.hx:577: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)" If anyone could help me I would really appreciate it :)
> > ### Are you modding a build from source or with Lua?
> > Source
> > ### What is your build target?
> > Windows x64
> > ### Did you edit anything in this build? If so, mention or summarize your changes.
> > No
> 
> run `haxelib remove flxanimate` then `haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev`

I got the same thing ;-;

**Comment by ZaMaXo87** [comment]
sorry, I closed as an accident

**Comment by ZaMaXo87** [comment]
> > ### Describe your problem here.
> > Hi, what's up? well I was trying to export the source code but when I put lime test windows I get "source/backend/Paths.hx:577: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)" If anyone could help me I would really appreciate it :)
> > ### Are you modding a build from source or with Lua?
> > Source
> > ### What is your build target?
> > Windows x64
> > ### Did you edit anything in this build? If so, mention or summarize your changes.
> > No
> 
> run `haxelib remove flxanimate` then `haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev`

IDK What to do now
