### ISSUE TITLE
Sustain Note Extends Longer Than Intended

### ISSUE THREAD

**Issue by verecundius** [ShadowMario/FNF-PsychEngine#13660]
### Describe your bug here.

In the chart editor, when pressing E on a selected note, it is supposed to turn into a hold note. However, it extends unevenly with the grid (specifically its increased value is literally 1 too big) and results in what can be seen here. Is this just a me problem or is this global? Thanks!
![Screenshot (409)](https://github.com/ShadowMario/FNF-PsychEngine/assets/112294278/50146e2f-b3e5-405d-be18-5b5d89b849ab)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, this is downloaded straight from GameBanana

**Comment by ShadowMario** [comment]
This is not a bug, it's a thing to prevent an issue where the note would appear slightly longer on PlayState
