### ISSUE TITLE
How to duplicate camGame

### ISSUE THREAD

**Issue by BillyLOLwkwk** [ShadowMario/FNF-PsychEngine#13665]
### What is your question?

i tried this code
`function onCreate()
    luaDebugMode = true
    setProperty('camGame.width', 640) 
    runHaxeCode('public var myCam:FlxCamera;')
    runHaxeCode('myCam = new FlxCamera();')
    --runHaxeCode('myCam.bgColor.alpha = 0;')
    runHaxeCode('FlxG.cameras.add(myCam, false);')
    --runHaxeCode('FlxG.cameras.add(myCamera);')
end`

using lua, and i want this camera that i have created to duplicate the same thing as the camGame do. does someone can help meh ?

**Comment by JHAM25** [comment]
Papu lo hice así aqui el codigo:

function onCreate()
    addHaxeLibrary('FlxCamera', 'flixel')
    addHaxeLibrary('FlxObject', 'flixel')
    --setProperty('camGame.width', 640) 
    runHaxeCode([[
    public var myCam:FlxCamera;
    var Posicion;
    myCam = new FlxCamera();

    Posicion = new FlxObject(1200, 750, 1, 1);
    myCam.follow(Posicion);

    add(Posicion);
    FlxG.cameras.add(myCam, true);
    FlxG.cameras.add(game.camOther, false);

    myCam.scaleX = 0.25;
    myCam.scaleY = 0.25;
    myCam.width = 320;
    myCam.height = 180;
    myCam.zoom = 0.16;

    ]])
end

una imagen de como quedo:
![Camara duplicada](https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/139dd9dc-c7d0-48bf-8958-230a48fd70fe)
