### ISSUE TITLE
It doesn't work with shaders

### ISSUE THREAD

**Issue by JHAM25** [ShadowMario/FNF-PsychEngine#13669]
### Describe your bug here.

I've wanted to put shaders in the game
 but apparently they don't work. I tried mods that have shaders but it still doesn't work, and in the last update of the game, they added the function to change the color of the notes, and I think it also works with shaders but it's not working. Here's a photo:
![Prueba](https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/e451beaa-5add-4473-aef0-631dd7ad616a)

Can someone help me solve this?
¿alguien puede ayudarme?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CaptainBaldi** [comment]
your system probably isn't compatible, in that case it's not a psych engine issue. Otherise, check the shaders option in settings
