### ISSUE TITLE
MSVC errors "crtdbg.h" 

### ISSUE THREAD

**Issue by axolotl-mouka** [ShadowMario/FNF-PsychEngine#13671]
### Describe your problem here.

```
Error: MenuCharacterEditorState.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083:  Cannot open include file: "crtdbg.h”: No such file or directory

Error: WeekData.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083:  Cannot open include file: "crtdbg.h”: No such file or directory

Error:_boot__.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083:  Cannot open include file:"crtdbg.h”: No such file or directory
```

And i installed this

VS BuildTools2019 (version16.11.9):
```
MSVC v142 - VS 2019 C++ x64/x86 buildtools (latest)
Windows SDK (10.0.17763.0)
```

I've tried VS Community 2019 but can't get it fixed,
I've never had this problem before, since before I reinstalled the system.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TomVN1230101** [comment]
> ### Describe your problem here.
> ```
> Error: MenuCharacterEditorState.cpp
> C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083:  Cannot open include file: "crtdbg.h”: No such file or directory
> 
> Error: WeekData.cpp
> C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083:  Cannot open include file: "crtdbg.h”: No such file or directory
> 
> Error:_boot__.cpp
> C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083:  Cannot open include file:"crtdbg.h”: No such file or directory
> ```
> 
> And i installed this
> 
> VS BuildTools2019 (version16.11.9):
> 
> ```
> MSVC v142 - VS 2019 C++ x64/x86 buildtools (latest)
> Windows SDK (10.0.17763.0)
> ```
> 
> I've tried VS Community 2019 but can't get it fixed, I've never had this problem before, since before I reinstalled the system.
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No

do like me follow install this:
![Screenshot 2023-11-26 152909](https://github.com/ShadowMario/FNF-PsychEngine/assets/121646407/d0de007e-f0f0-4c14-82ff-29a507ba7854)

**Comment by axolotl-mouka** [comment]
> > ### Describe your problem here.
> > ```
> > Error: MenuCharacterEditorState.cpp
> > C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083:  Cannot open include file: "crtdbg.h”: No such file or directory
> > 
> > Error: WeekData.cpp
> > C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083:  Cannot open include file: "crtdbg.h”: No such file or directory
> > 
> > Error:_boot__.cpp
> > C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083:  Cannot open include file:"crtdbg.h”: No such file or directory
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And i installed this
> > VS BuildTools2019 (version16.11.9):
> > ```
> > MSVC v142 - VS 2019 C++ x64/x86 buildtools (latest)
> > Windows SDK (10.0.17763.0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I've tried VS Community 2019 but can't get it fixed, I've never had this problem before, since before I reinstalled the system.
> > ### Are you modding a build from source or with Lua?
> > Source
> > ### What is your build target?
> > Windows x64
> > ### Did you edit anything in this build? If so, mention or summarize your changes.
> > No
> 
> do like me follow install this: ![Screenshot 2023-11-26 152909](https://private-user-images.githubusercontent.com/121646407/285657573-d0de007e-f0f0-4c14-82ff-29a507ba7854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNzM5NzAsIm5iZiI6MTcwMjE3MzY3MCwicGF0aCI6Ii8xMjE2NDY0MDcvMjg1NjU3NTczLWQwZGUwMDdlLWYwZjAtNGMxNC04MmZmLTI5YTUwN2JhNzg1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQwMjAxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWYzNzEyMGNkMzk2NmJlOGI4ZjAxYTZhNzM4NWZhYzdlNWRiZjI0N2M2MDJhMWVjNWVmM2IwY2ExZTcwMGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k6LtdN4Iw54Kb_krZLbeATNEvLfnQP3IEAG0t6rmKQA)

Thx, but I've fixed the problem

**Comment by kakubus** [comment]
Could you describe this again, or reupload screenshoot? I have this same issue.
