### ISSUE TITLE
earlyeventtrigger. it doesn't work

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#13672]
### Describe your problem here.

i hate this function so much why doesn't it work again? what went wrong???

example of it not fucking working
function eventEarlyTrigger(name)
	if name == 'Flash' then
		return 1500
	end
end
it should do the flash event early
and guess what, it does NOTHING. AAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAASDaDSCEWRJRNFWO$NO#RNR#OJ

THIS FUNCTION IS THE SPAWN OF SATAN!!!! THE FUCKING DEVIL COME DOWN TO KICK ME IN THE NUTS WHY DOES IT NEVER WORK

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by wubbzyfan** [comment]
IM ON THE NEWST VERSION AD FUCKIGN EVERTTHING


WHAT BROKE IN 7.0

**Comment by wubbzyfan** [comment]
IT WORKED JSUT FINE IN6.3 BUT BY 7.1H OR WHATEVER ITSA FUCKED AGAIN KILL ME

**Comment by ShadowMario** [comment]
fixed on experimental builds
