### ISSUE TITLE
Lime test windows error

### ISSUE THREAD

**Issue by Retr0wavy** [ShadowMario/FNF-PsychEngine#1367]
### Describe your bug here.

When I try to run the "lime test windows" command in the command prompt, this appears:

I tried taking a look at the "Character.hx" file, but I don't see anything wrong in line 134 (The line with "} else {" written on it). What am I supposed to do?

### Command Prompt/Terminal logs (if existing)

```bash
D:\retro\OneDrive\Área de Trabalho\FNF-PsychEngine-main>lime test windows
source/Character.hx:134: characters 7-11 : Expected }   ⇦ (What appears in the command prompt)



if (!FileSystem.exists(path2))
				#else
				if(Assets.exists(Paths.getPath('images/' + json.image + '.txt', TEXT))) {
				#end
				//bozo forgot about the packer shits : P
					frames = Paths.getPackerAtlas(json.image);
				} else {
					frames = Paths.getSparrowAtlas(json.image);    ⇦ (What appears in Character.hx)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, didn't edit anything

**Comment by SrtHero278** [comment]
just move the "}" up a line on line 134. Not "{"

**Comment by Retr0wavy** [comment]
> just move the "}" up a line on line 134. Not "{"

Like this?  }        
		else {
