### ISSUE TITLE
How do I fix this? (Downscroll Mid-Song)

### ISSUE THREAD

**Issue by luigiman0** [ShadowMario/FNF-PsychEngine#13670]
### What is your question?

![gitHelp](https://github.com/ShadowMario/FNF-PsychEngine/assets/113739072/0e99428d-70b1-439c-aaa8-094373a4c2ac)
I'm having a problem where when I switch to Downscroll mid-song, the sustain notes fly past the intended note area. Is it possible to fix this using Lua? [Note that they usually only go to the middle of the square]

**Comment by JHAM25** [comment]
puedes intentar utilizar :
setProperty('noteKillOffset')

**Comment by luigiman0** [comment]
> puedes intentar utilizar : setProperty('noteKillOffset')

thanks! will test and see if it works

**Comment by JHAM25** [comment]
funciono?
