### ISSUE TITLE
Windows 32Bit 0.7.1h (Lastest Version) .ndll Error

### ISSUE THREAD

**Issue by JustAFnfPlayeer** [ShadowMario/FNF-PsychEngine#13675]
### Describe your bug here.

I Dowland **Windows32Bit.zip** , ı open file and ı open **Psych Engine** ,
![resim_2023-11-26_124409036](https://github.com/ShadowMario/FNF-PsychEngine/assets/152061532/ffd9692c-7819-411f-a3b8-81d712f4a7c0)
So i will translate to Engilish , ''Bozuk Görüntü'' is '**'Distorted İmage''** , ''Hata'' is **''Error'**' and **lime.ndll** is not working , How its possible? But **0.6.3h not have this error**

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No , I didnt edit anything

**Comment by crowplexus** [comment]
you need to compile the game yourself for 0.7

**Comment by mcagabe19** [comment]
@JustAFnfPlayeer crowplexus doğru diyor kendi windowsunda buildlemelisin
