### ISSUE TITLE
Sustain Stuff

### ISSUE THREAD

**Issue by MrSropical** [ShadowMario/FNF-PsychEngine#13676]
### What feature do you want to get added on the **base** engine?

So the thing i want to see in engine is that the sustain notes render under the notes
![Screenshot 11_26_2023 1_10_47 PM](https://github.com/ShadowMario/FNF-PsychEngine/assets/150122529/9679f3f3-f2d6-4836-9530-6352d6ba4910)

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by TomVN1230101** [comment]
> ### What feature do you want to get added on the **base** engine?
> So the thing i want to see in engine is that the sustain notes render under the notes ![Screenshot 11_26_2023 1_10_47 PM](https://private-user-images.githubusercontent.com/150122529/285649605-9679f3f3-f2d6-4836-9530-6352d6ba4910.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMDgyMTAsIm5iZiI6MTcwMTAwNzkxMCwicGF0aCI6Ii8xNTAxMjI1MjkvMjg1NjQ5NjA1LTk2NzlmM2YzLWYyZDYtNDgzNi05NTMwLTYzNTJkNmJhNDkxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQxNDExNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmY5MmVkOGIwZDI1NzFhMTE0YjgzNjVjNjU2MjBhZGNkNzQzZmU5NGMyODNmZDg1NGUzY2U3OGM3N2IyOTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T3ELo-gZGqX1A0eByLoZru0sl3aQr33vEmzhpP3Dxn0)
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> A good idea

if you want like base game just delete code find <strumPlayAnim> and delete code inside.
![Screenshot 2023-11-26 151326](https://github.com/ShadowMario/FNF-PsychEngine/assets/121646407/4e637148-f650-4a75-af80-e39ccd68f878)

**Comment by MrSropical** [comment]
i already did that where did you think i got the screenshot from? the main thing is that to see it as an ofiicial feature (like notes glow speed is now bpm based)

**Comment by SrBagel** [comment]
> ### What feature do you want to get added on the **base** engine?
> So the thing i want to see in engine is that the sustain notes render under the notes ![Screenshot 11_26_2023 1_10_47 PM](https://private-user-images.githubusercontent.com/150122529/285649605-9679f3f3-f2d6-4836-9530-6352d6ba4910.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMTYwODEsIm5iZiI6MTcwMTAxNTc4MSwicGF0aCI6Ii8xNTAxMjI1MjkvMjg1NjQ5NjA1LTk2NzlmM2YzLWYyZDYtNDgzNi05NTMwLTYzNTJkNmJhNDkxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQxNjIzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjAwZTQ2MmE2M2RjMDkwNWJlYmFjNmRjODNiNzU2OTUxNDk4NGJmOGI1YTQxMTM3ZmYzMzEzYTk1OTdhYWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OG0pVxcgjA2jpbj7xlEYc2SN4pm5-9fmOWYAuzZgBjs)
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> A good idea
   ^You failed the test

**Comment by TomVN1230101** [comment]
> i already did that where did you think i got the screenshot from? the main thing is that to see it as an official feature (like notes glow speed is now bpm based)

ok

**Comment by MrSropical** [comment]
> > ### What feature do you want to get added on the **base** engine?
> > So the thing i want to see in engine is that the sustain notes render under the notes ![Screenshot 11_26_2023 1_10_47 PM](https://private-user-images.githubusercontent.com/150122529/285649605-9679f3f3-f2d6-4836-9530-6352d6ba4910.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMTYwODEsIm5iZiI6MTcwMTAxNTc4MSwicGF0aCI6Ii8xNTAxMjI1MjkvMjg1NjQ5NjA1LTk2NzlmM2YzLWYyZDYtNDgzNi05NTMwLTYzNTJkNmJhNDkxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQxNjIzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjAwZTQ2MmE2M2RjMDkwNWJlYmFjNmRjODNiNzU2OTUxNDk4NGJmOGI1YTQxMTM3ZmYzMzEzYTk1OTdhYWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OG0pVxcgjA2jpbj7xlEYc2SN4pm5-9fmOWYAuzZgBjs)
> > ### To test your sight, and reliability, please select the option of what should NOT be requested.
> > A good idea
> 
> ^You failed the test

wha

**Comment by crowplexus** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/45212377/28f823b8-b65e-46d4-8de5-70954d2ff34a)
I swear to god

**Comment by crowplexus** [comment]
this is already in the engine, just use 0.7+
