### ISSUE TITLE
Song audio won't work! 

### ISSUE THREAD

**Issue by JackoBoi2022** [ShadowMario/FNF-PsychEngine#13683]
### Describe your problem here.

I'm making a mod for Psych Engine (Folder mod where you have to put it in Psych Engine) And have my songs folder in the right places (trust me, I checked in every place I could), and have the Inst and Vocals as an .ogg, however, whenever I go into the chart editor through the main menu, put the name of the song in, and press Reload Audio, all it does is load a blank slate! What I mean by this is that there's no audio, the section, beat, and step are set to zero and can't be changed, and trying to play the song does nothing.
I've looked everywhere and can't find anything, so an answer would be heavily appreciated! Thank you!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by wj1ajao39sjak927** [comment]
Did you name the voice track "Vocals.ogg"? It's supposed to be "Voices.ogg".

**Comment by wj1ajao39sjak927** [comment]
First letter must be capitalized. The "V", that is.

**Comment by Lorekeeper49** [comment]
> First letter must be capitalized. The "V", that is.

Actually that part's not required, I played a mod that was softcoded and all the audio files were named properly but without capitalization
