### ISSUE TITLE
uhhh compiling stuff problems

### ISSUE THREAD

**Issue by DaDinoGuy** [ShadowMario/FNF-PsychEngine#13680]
### Describe your problem here.

source/FunkinLua.hx:172: characters 42-54 : PlayState has no field playbackRate
source/FunkinLua.hx:470: characters 12-24 : flixel.addons.display.FlxRuntimeShader has no field setSampler2D
source/FunkinLua.hx:491: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:509: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:515: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:567: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:573: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:613: lines 613-617 : Int should be Bool
source/FunkinLua.hx:613: lines 613-617 : ... For function argument 'f'
source/PlayState.hx:5108: characters 13-23 : Class<FunkinLua> has no field haxeInterp

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TomVN1230101** [comment]
change other flixel

**Comment by DaDinoGuy** [comment]
i did but still doesnt work

**Comment by TomVN1230101** [comment]
this is psych engine?

**Comment by DaDinoGuy** [comment]
yea

**Comment by TomVN1230101** [comment]
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
