### ISSUE TITLE
script test

### ISSUE THREAD

**Issue by baldi2** [ShadowMario/FNF-PsychEngine#13688]
### Describe your problem here.

how do i change the psych engine resolution using a script??
i tried this script

local resolutionSet = false  -- stuff to track

function onUpdate(elapsed)
    if not resolutionSet then
        -- Set resolution to 10x10 when the song starts
        PsychEngine.setResolution(10, 10)
        resolutionSet = true -- IT'S TRACKED!!
    end

    -- Your existing resolution change logic based on key presses
    if keyJustPressed('left') then
        PsychEngine.setResolution(PsychEngine.getScreenWidth() + 1, PsychEngine.getScreenHeight() + 1)
    end
    if keyPressed('right') then
        PsychEngine.setResolution(PsychEngine.getScreenWidth() + 1, PsychEngine.getScreenHeight() + 1)
    end
    if keyPressed('up') then
        PsychEngine.setResolution(PsychEngine.getScreenWidth() + 1, PsychEngine.getScreenHeight() + 1)
    end
    if keyPressed('down') then
        PsychEngine.setResolution(PsychEngine.getScreenWidth() + 1, PsychEngine.getScreenHeight() + 1)
    end
end

and it didnt work

can somebody help me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i made a new script in a song

**Comment by TheRealPepsi** [comment]
For setting the window size (I think that's what you're trying to do), try this 

setPropertyFromClass("openfl.Lib", "application.window.x", number)

**Comment by baldi2** [comment]
thanks, i was trying to do that but now i want to set the resolution to 10x10 when the song starts.

im making a video and this is what the video should be like:
song starts at 10x10 resolution
when player sings, 1 pixel gets added
basically like that

**Comment by TheRealPepsi** [comment]
Maybe something like this?

Variable = 10

if keyJustPressed('left') then
Variable = Variable + 1
        setPropertyFromClass("openfl.Lib", "application.window.x", Variable)
        setPropertyFromClass("openfl.Lib", "application.window.y", Variable)

**Comment by baldi2** [comment]
hasn't seem to do anything. tried fixing it and stuff, nothing.
