### ISSUE TITLE
Error with doing

### ISSUE THREAD

**Issue by skyblue29** [ShadowMario/FNF-PsychEngine#13692]
### Describe your bug here.

i wrote haxelib run hmm install and this happened :(

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\USER>haxelib run hmm install
Validation error: hmm.json not found in current working directory
Use "hmm help" to see usage
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Filip55561** [comment]
You need to go in your Psych Engine folder then open terminal and run it
