### ISSUE TITLE
Chart Editor can't enter dot, uppercase letters; and Performance issues

### ISSUE THREAD

**Issue by CoolLKKPS** [ShadowMario/FNF-PsychEngine#13696]
### Describe your bug here.

The numeric keypad cannot enter dot, and it is not possible to enter uppercase letters:
some lua scripts require type uppercase letters, i know usually no need to use uppercase letters.
Performance issues:
even in lastest version, load song still doesn't check all events (and load the assets associated with them)(maybe?)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No im sure

**Comment by ShadowMario** [comment]
Flixel issue, not psych's
