### ISSUE TITLE
lordy lord what have i done

### ISSUE THREAD

**Issue by JustT04sty** [ShadowMario/FNF-PsychEngine#13693]
### Describe your problem here.

source/flixel/system/FlxSound.hx:597: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/system/FlxSound.hx:601: characters 19-27 : flash.media.SoundChannel has no field __source
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/text/FlxTypeText.hx:8: characters 8-29 : Type not found : flixel.sound.FlxSound
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/text/FlxTypeText.hx:78: characters 26-34 : Type not found : FlxSound
source/CoolUtil.hx:18: lines 18-141 : ... Defined in this class
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/effects/chainable/FlxEffectSprite.hx:137: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxExtendedMouseSprite.hx:5: characters 8-40 : Type not found : flixel.input.mouse.FlxMouseEvent
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxExtendedMouseSprite.hx:221: characters 3-16 : Type not found : FlxMouseEvent
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxExtendedMouseSprite.hx:625: characters 28-34 : flixel.input.mouse.FlxMouse has no field deltaX
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/display/FlxExtendedMouseSprite.hx:626: characters 28-34 : flixel.input.mouse.FlxMouse has no field deltaY
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler
source/DialogueBox.hx:144: characters 16-22 : flixel.addons.text.FlxTypeText has no field sounds
source/DialogueBox.hx:244: characters 16-25 : flixel.addons.text.FlxTypeText has no field resetText
source/DialogueBox.hx:245: characters 16-21 : flixel.addons.text.FlxTypeText has no field start
source/DialogueBox.hx:246: characters 16-32 : flixel.addons.text.FlxTypeText has no field completeCallback
source/DialogueBox.hx:223: characters 18-22 : flixel.addons.text.FlxTypeText has no field skip
C:/HaxeToolkit/haxe/lib/flixel-addons/3,2,1/flixel/addons/transition/FlxTransitionableState.hx:81: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i only deleted the check for updates line but that shouldn't do anything.

**Comment by SrBagel** [comment]
Did you make sure all your library's match? You can check here:
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by TomVN1230101** [comment]
what ver fnf pe you on using?

**Comment by JustT04sty** [comment]
0.6.3
its the only one that allows me to put ,my characters in.
