### ISSUE TITLE
Error on compile

### ISSUE THREAD

**Issue by slimeysonic400** [ShadowMario/FNF-PsychEngine#13700]
### Describe your problem here.

Tried compiling the game and got this error

source/flixel/sound/FlxSound.hx:601: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/sound/FlxSound.hx:605: characters 19-27 : flash.media.SoundChannel has no field __source
FNF-PsychEngine-experimental/.haxelib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat should be declared with 'override' since it is inherited from superclass flixel.graphics.frames.FlxAtlasFrames
FNF-PsychEngine-experimental/.haxelib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat overrides parent class with different or incomplete type
FNF-PsychEngine-experimental/.haxelib/flixel/5,5,0/flixel/graphics/frames/FlxAtlasFrames.hx:457: characters 18-24 : ... Base field is defined here
FNF-PsychEngine-experimental/.haxelib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : ... Different number of function arguments
source/backend/Paths.hx:577: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)

have no clue what to do 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TomVN1230101** [comment]
to fix do this:
haxelib install flxanimate

**Comment by slimeysonic400** [comment]
im using the latest experimental

**Comment by TomVN1230101** [comment]
download this file 
https://drive.google.com/file/d/1XmXIEeeqKblRNTY9uREXgHUBF_4_mp48/view?usp=sharing
