### ISSUE TITLE
Psych Engine not working!

### ISSUE THREAD

**Issue by Ehiokn** [ShadowMario/FNF-PsychEngine#13706]
### Describe your problem here.

So every time I try "lime test windows" I get an error message saying "C:\Users\Redni\Documents\Oneshot - Intune thing\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths"
Screenshot:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/142696059/51aedf75-d292-4fe2-8627-514c21d6b0e7)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Ehiokn** [comment]
Yeah, I installed visual studio

**Comment by JonnycatMeow** [comment]
but did you install the dependencies for it?

**Comment by Ehiokn** [comment]
Yes, I am pretty sure I have all of the dependencies in the correct versions as well

**Comment by Ehiokn** [comment]
shit, I closed the issue by accident
