### ISSUE TITLE
Character json bug

### ISSUE THREAD

**Issue by MANKMORE** [ShadowMario/FNF-PsychEngine#13701]
### Describe your bug here.

[flixel/graphics/tile/FlxDrawQuadsItem.hx (line 119)
flixel/FlxCamera.hx (line 763)
flixel/FlxGame.hx (line 875)
flixel/FlxGame.hx (line 563)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng]

The game did not see the xml/png spritesheet.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I attempted to make a character json.

**Comment by thejarriestjarr** [comment]
I'm having this same problem. I put my custom character's png and xml in images -> characters. I also used dad.json as a template for my new character, but I only see the HaxeFlixel icon when I load my character from the character list.

**Comment by thejarriestjarr** [comment]
I figured it out! Are you using the mod-template folder? If you are, all the files are also stored in the My-Mod folder, right? Take all the files (assets, data, images, etc.) and move them into the "mod-template" folder. Then, delete the "My-Mod" folder once you have emptied it out. The additional file direction created by "My-Mod" may be causing Psych engine issues with reading your mod contents. Just don't accidentally delete all the assets, data, etc. if you plan to try this.

**Comment by Helpme981** [comment]
I don't understand anything, I don't know what's going on, can you help me in detail please?

I am very desperate

**Comment by Helpme981** [comment]
Please help me as quickly as possible or contact us in another application. If you answer me, please let me know...
