### ISSUE TITLE
Game over camera off animation

### ISSUE THREAD

**Issue by Paintymaster** [ShadowMario/FNF-PsychEngine#13709]
### Describe your problem here.

![Pls Help me](https://github.com/ShadowMario/FNF-PsychEngine/assets/152902693/22ecb035-5759-4c92-8ff2-7be2be32b868)
The camera keeps going down here and is not moving up i've been trying to figure it out using multiple methods but nothing is working :'(

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing edited

**Comment by ShadowMario** [comment]
Should be fixable (when 0.7.2 is out) by changing the camera offset

**Comment by Paintymaster** [comment]
Thank :)
