### ISSUE TITLE
Can't add custom character in

### ISSUE THREAD

**Issue by ChristianAnimations** [ShadowMario/FNF-PsychEngine#13703]
### Describe your bug here.

I have been trying to add a custom character stripe sheet into the FNF Psych engine, but every time I type in both the asset name and the character icon, it just says error and doesn't add my character to the engine along with its icon, which is making it harder to make my FNF mod (Stripe made in adobe animate and icon made in photoshop).

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I try to add new stripes and icons

**Comment by ChristianAnimations** [comment]
> you cant add images inside the assets folder without compiling first just add them inside the mods folder

I did add them inside the mods folder, but they still don't work.

**Comment by NexIsDumb** [comment]
> > you cant add images inside the assets folder without compiling first just add them inside the mods folder
> 
> 
> 
> I did add them inside the mods folder, but they still don't work.

send the error

**Comment by SIYHW** [comment]
i have a few reasons for this issue
1:your at the wrong mod directory, check the pack.json or the name of the mod folder
2:in the xml, the name for the png might be different, if so then change the charactername.png to the correct character
3:the xml is coded in a wrong way, try comparing it with a xml that works
4:your image might be a different format than PNG, if so then try converting the format to PNG
