### ISSUE TITLE
Im compiling my friends mod, and this happens.

### ISSUE THREAD

**Issue by BBJAKABucketBoyJay** [ShadowMario/FNF-PsychEngine#13710]
### Describe your bug here.

Whenever i type the command "lime test windows", it always says source/flixel/system/FlxSound.hx:3: characters 20-26 : Unexpected import, i have searched it up and have found nothing on it. Can anyone help?

### Command Prompt/Terminal logs (if existing)

```bash
source/flixel/system/FlxSound.hx:3: characters 20-26 : Unexpected import
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by ShadowMario** [comment]
If you're on the newest version of flixel, delete `flixel/system/FlxSound.hx` and `flixel/sound/FlxSound.hx`, Psych used to override them because flixel didn't had a pitch changer at the time.
When you go back to this post and it resolved your problem, close the issue please.
