### ISSUE TITLE
"Paths" in TitleState (Not an issue. Just a question)

### ISSUE THREAD

**Issue by BlackCatOnYoutube** [ShadowMario/FNF-PsychEngine#13716]
### What is your question?

What does "Paths" do in source code? Does it like look for a specific file? Example:
gfDance.frames = Paths.getSparrowAtlas('ShadowBump');
gfDance.animation.addByPrefix('danceLeft', 'Shadow Title Bump', 24);
gfDance.animation.addByPrefix('danceRight', 'Shadow Title Bump', 24);
I found this in TitleState.

**Comment by talopakola** [comment]
looking at codes that involve it, I can understand that it is just a file that allows programmers to load files and mess with them

**Comment by CaptainBaldi** [comment]
its a utility class for loading different file types across mods etc. It can load things like images, sounds, bitmaps, spritemaps, etc with its various functions

**Comment by BlackCatOnYoutube** [comment]
CaptainBaldi I see.

**Comment by ShadowMario** [comment]
Paths.getSparrowAtlas gets both XML and PNG with the same name and transforms it into animation frames for characters and other animated sprites.

**Comment by BlackCatOnYoutube** [comment]
I hadn't paid attention to this: I understand now.
