### ISSUE TITLE
 ឵឵ 

### ISSUE THREAD

**Issue by fnafffnfandroidud** [ShadowMario/FNF-PsychEngine#13726]
### Describe your bug here.

i tried compiling

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

n

**Comment by Eric-R-Malice** [comment]
💀

**Comment by Num4ersur** [comment]
hi

**Comment by Eric-R-Malice** [comment]
hi hyd

**Comment by Num4ersur** [comment]
![imagen_2023-12-06_235433930](https://github.com/ShadowMario/FNF-PsychEngine/assets/94721285/f9c4cbba-1cd3-489f-8744-242e75edaa5a)

**Comment by Cobalt-Bar** [comment]
Every day
I lose hope in humanity

**Comment by richTrash21** [comment]
bro really tried compiling

**Comment by Num4ersur** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/94721285/36b5e83d-8aef-4fe8-bb41-b76c996bfb53)
