### ISSUE TITLE
how i make the opponent notes only downscroll?

### ISSUE THREAD

**Issue by ShihoXD** [ShadowMario/FNF-PsychEngine#13722]
### Describe your problem here.

i'm trying to make a script that make the opponent notes only go from up to down (downscroll) like this:
![95 Sem Título_20231206112614](https://github.com/ShadowMario/FNF-PsychEngine/assets/122299419/09b20f54-096c-4ee8-bec1-5f34ff84053c)

it can be in haxe or lua whatever but i just want an answer please

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by JHAM25** [comment]
podrías utilizar ''setPropertyFromGroup('opponentStrums', 0, 'y', 570)'' y ''setPropertyFromGroup('strumLineNotes', 1, 'direction', 270)'' creo que funcionaria

**Comment by ShihoXD** [comment]
it worked but the notes are like this:
![Screenshot_13](https://github.com/ShadowMario/FNF-PsychEngine/assets/122299419/39a04202-5fad-4e6e-9e6f-d0ec2194898b)

**Comment by ShihoXD** [comment]
> Prueba esto:
> 
> luaDebugMode = true NotasDad = {0, 570, 570, 570, 570}
> 
> function onCreatePost() for i = 0, 3 do setPropertyFromGroup('opponentStrums', i, 'y', NotasDad[i + 2]) end end
> 
> function onUpdatePost() songosition = getSongPosition() songSpeed = getProperty('songSpeed')
> 
> ```
> for i = 0, getProperty('notes.length') - 1 do
>     if not getPropertyFromGroup('notes', i, 'mustPress') then
>         noteData = getPropertyFromGroup('notes', i, 'noteData')
>         strumTime = getPropertyFromGroup('notes', i, 'strumTime')
>         Y = NotasDad[noteData + 2] + 0.45 * (songPosition - strumTime) * songSpeed
>         setPropertyFromGroup('notes', i, 'y', Y)
> 
>         if getPropertyFromGroup('notes', i, 'isSustainNote') then
>             setPropertyFromGroup('notes', i, 'angle', 180)
>         end
>     end
> end
> ```
> 
> end

it didn't work
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/122299419/9dc20b78-107e-4559-a316-d3feab8221de)

**Comment by JHAM25** [comment]
perdon me confundí en 'songosition = getSongPosition()'  en realidad es 'songPosition = getSongPosition()'
codigo:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/3f19d63f-9bb6-47da-a472-2eb9c147a48d)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/85f837f6-cc6e-443f-8a39-17c8cf1c0b1d)

**Comment by ShihoXD** [comment]
> perdon me confundí en 'songosition = getSongPosition()' en realidad es 'songPosition = getSongPosition()' codigo: ![image](https://private-user-images.githubusercontent.com/108441263/289176141-3f19d63f-9bb6-47da-a472-2eb9c147a48d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwODc0ODQsIm5iZiI6MTcwMjA4NzE4NCwicGF0aCI6Ii8xMDg0NDEyNjMvMjg5MTc2MTQxLTNmMTlkNjNmLTliYjYtNDdkYS1hNDcyLTJlYjljMTQ3YTQ4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQwMTU5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjkyNGIxMGY0ZDE3MjIxYjU5YzUwMjViYzhlYzlhNjEyNWFhZTc5NGFiYTdlMzJkYmUxZTMxNDk3MzIxNDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K2gjKxss-T0mRoXo-uRdkbCO-emmDCZ9y5gyKV1_VL0) ![image](https://private-user-images.githubusercontent.com/108441263/289176668-85f837f6-cc6e-443f-8a39-17c8cf1c0b1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwODc0ODQsIm5iZiI6MTcwMjA4NzE4NCwicGF0aCI6Ii8xMDg0NDEyNjMvMjg5MTc2NjY4LTg1ZjgzN2Y2LWNjNmUtNDQzZi04YTM5LTE3YzhjZjFjMGIxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQwMTU5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWI4MTk2NGFmNDExNTZmOGE5YzNjYzg2OWNlMDgyZDEyYzA2OGIzM2Q1ZjE1MTM3MGI4MTE5NDc0NjQ4OTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B93e-iZtI-fhfXyc4BS4qvsii6HP2TyMrH9CdUHVl9o)

i worked but the sustain notes look like this:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/122299419/1cb285b0-402a-4647-a6c5-10b89bbe7bda)

but thank you man i'm not all that good in lua script but this don't have solution right? anyway it's good for me thanks again

**Comment by JHAM25** [comment]
I tried on a faster song and also saw that error. So, I started looking for something to fix it in PlayState, and I found this, but I don't know if it works. The only thing is that you have to do it in Lua:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/2e287618-8488-4b56-971f-edd982049ca6)
