### ISSUE TITLE
I wan't to put this shader but it's crashing

### ISSUE THREAD

**Issue by FacunMax** [ShadowMario/FNF-PsychEngine#13731]
### Describe your problem here.

so i want to put this shader to my mod: https://www.shadertoy.com/view/3tfcD8
and it crashing like an incompatible shader. But i see a mod using it so idk pls help aaaaa ( i will not copy paste the code of that mod)

### Are you modding a build from source or with Lua?

Source and/or Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Cyachao** [comment]
you have port the shader for it to work on haxeflixel
stuff like `#pragma header` at very top and change some variable names

**Comment by FacunMax** [comment]
> you have port the shader for it to work on haxeflixel stuff like `#pragma header` at very top and change some variable names

there's some where do i lear to optimize shaders like that?

**Comment by ender69funk** [comment]
idk

**Comment by ShadowMario** [comment]
You don't just throw things in flixel and expect it to work perfectly, sorry man but this issue is not specific to Psych Engine

**Comment by FacunMax** [comment]
> You don't just throw things in flixel and expect it to work perfectly, sorry man but this issue is not specific to Psych Engine

i know
