### ISSUE TITLE
Competitive Mode Option

### ISSUE THREAD

**Issue by Johferson** [ShadowMario/FNF-PsychEngine#13732]
### What feature do you want to get added on the **base** engine?

Basically, what the option does is to toggle between Psych's normal input system and a competitive input system similar to SM/ITG and Mania. For tryhards like me.

(For more info, what this option should do is..
- adjusts hit windows to become tighter
- punishes players for getting a shit judgement
- uses accuracy system similar to Kade Engine)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CaptainBaldi** [comment]
I feel like most of if not all of these things you can do yourself

**Comment by ShadowMario** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/f4f89aba-bb30-4de2-a33a-cb32655e8a1c)
This is how you can adjust Hit Windows, it's already in psych for a good while.
