### ISSUE TITLE
ADDING CREDITS

### ISSUE THREAD

**Issue by mllso824** [ShadowMario/FNF-PsychEngine#13733]
### Describe your problem here.

YOU CAN'T ADD CREDITS IN 7.1H

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CaptainBaldi** [comment]
you can??

**Comment by ShadowMario** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/9f0f61b2-b9c2-4f28-bad9-028a6d352a94)
Ermm, double check your stuff!
