### ISSUE TITLE
2 Questions, Not Much

### ISSUE THREAD

**Issue by franklhub** [ShadowMario/FNF-PsychEngine#13738]
1. How Do I Remove The Title Screen Easter Eggs?

2. How Do I Remove The Difficulty Text From Freeplay?

**Comment by franklhub** [comment]
Another Question, How Do I Remove The Difficulty Text From Freeplay?

**Comment by crowplexus** [comment]
Title Screen easter eggs get automatically disabled when youc ompile the game for modding

to remove the difficulty text, just remove every instance of `diffText` in FreeplayState.hx

**Comment by franklhub** [comment]
thanks for the help :)
