### ISSUE TITLE
Tjson is not installed when it's already is

### ISSUE THREAD

**Issue by thefnfcoder** [ShadowMario/FNF-PsychEngine#13746]
### Describe your bug here.

_ have to deal with this every time I compile a build. (0.7.1h)
![tjson](https://github.com/ShadowMario/FNF-PsychEngine/assets/121651439/3ea2c33c-9b9c-4113-9be4-5dc224cfbf3a)
How do I fix this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Vortex2Oblivion** [comment]
Try 
```haxelib remove tjson```

```haxelib install tjson```
