### ISSUE TITLE
Add the psych engine logo to the github readme (and change the icon to the psych engine one)

### ISSUE THREAD

**Issue by Lasercar** [ShadowMario/FNF-PsychEngine#13742]
### What feature do you want to get added on the **base** engine?
Title (I couldn't figure out how to shorten it so yeah).

Kind of surprised that no one's done this yet.

I'm talking about the one made by riveren used in the two psych engine ost videos by iflicky - [https://www.youtube.com/watch?v=mX9sgiSUf5g](https://www.youtube.com/watch?v=mX9sgiSUf5g) and [https://www.youtube.com/watch?v=a7ksO5xVJU8](https://www.youtube.com/watch?v=a7ksO5xVJU8)

And while you're at it, you might want to consider changing the icon over the psych engine one:
![psych engine emblem](https://github.com/ShadowMario/FNF-PsychEngine/assets/64717068/64396e26-6d3d-4b55-9996-675f32e6e6aa)
(If you're wondering, I found it in the mind games megafolder. It was a bit out of proportion, but I fixed it)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CaptainBaldi** [comment]
but why

**Comment by Cobalt-Bar** [comment]
why?
theres no point

**Comment by Lasercar** [comment]
Well, none of the other issue templates fit this suggestion any better, nor is there a miscellaneous/other template.

Anyway, I don't really know how to explain it. It's like if a company employee created a cool, awesome logo, but the company decided not to use it and stick with no logo (and just plain text) for their branding and marketing because???

**Comment by ShadowMario** [comment]
I'm not putting psych's logo on the app icon, fuck branding/marketing dude this is an fnf mod engine lmfao

**Comment by Lasercar** [comment]
Yeah, I just find it weird that it's not using it's own logo and icon like literally every other mod in existence.

**Comment by Lasercar** [comment]
Ah well, issue's closed. At least I tried though.
