### ISSUE TITLE
Ticket For Ban Appeal

### ISSUE THREAD

**Issue by IrshaadAli1** [ShadowMario/FNF-PsychEngine#13747]
### Describe your problem here.

Just 2 hours before this post, I was banned.
The reason for this was posting a virus in Media.

Now, I did not post a virus. It was a script I made to remap keybinds.
What's different to the Microsoft remapper?
My keybind remapper can either go for the entire or specific games

What's the issue?
Just earlier, the code I made I sent to the media channel as a compiled exe file.
The file was scanned and marked as a virus.
The issue here is that even when I tried to explain it was not a virus, there was no testing made to ensure it was or was not a virus.
The only proof that was there were the virus scanners which turned to be inaccurate due to it being compiled in Pyinstaller.
https://github.com/pyinstaller/pyinstaller/issues/6754
A similar issue with this is posted above with another person.

What am I trying to say?
My code which I made was falsely pointed out to be a virus and was not fully tested/checked by VMware to ensure this file was not a virus. In the end, it was ignored and I was banned anyways.

What do I want from all of this?
I just want people to run Virtual machine so I can prove that it's not a virus and I also just want to be unbanned.

What was your source code?

START
----------------------------------------------------------------------
```py
import keyboard
import win32gui


class curFocus:

    def __init__(self, target: str = ""):
        super().__init__()

        self.focusID = win32gui.GetForegroundWindow()
        self.name = win32gui.GetWindowText(self.focusID)
        self.target = target
        self.focused = bool(self.name == self.target)

    def setFocus(self, keyToSet):
        keyboard.wait(keyToSet)
        self.target = curFocus().name
        return self.target


def lsplit(string: list[str] | str = "", split=" "):
    if split != "":
        split_cutter = []
        temp_text = ""
        result = []
        for splitter in split:
            split_cutter.append(splitter)
        for text in string:
            boolean_ = True
            for detector in split_cutter:
                if boolean_:
                    if text == detector:
                        boolean_ = False
                        if temp_text != "":
                            result.append(temp_text)
                        temp_text = ""
            if boolean_:
                temp_text += text
        if temp_text != "":
            result.append(temp_text)
        return result
    else:
        result = []
        for i in string:
            result.append(i)
        return result


def lsplit_to_str(val: list[str]):
    """
    Turns List of LSplit into Str
    """
    value: str = ""
    for i in val:
        value += i
    return value


def remapKey(key: str, remappedKey: str):
    if event.event_type == keyboard.KEY_DOWN:
        if event.name == key:
            keyboard.press(remappedKey)
    if event.event_type == keyboard.KEY_UP:
        if event.name == key:
            keyboard.release(remappedKey)


def readKeyBindText():
    with open("keybinds.txt", "r") as file:
        data = file.readlines()
        splitData = lsplit(lsplit_to_str(data), "\n")
        keySplitData = []
        for i in splitData:
            keySplitData.append(lsplit(i, " -> "))
        actualData: list[list[str, list[str, str]]] = [["Global"]]
        for i in keySplitData:
            if len(i) == 1:
                actualData.append([i[0]])
            elif len(i) == 2:
                actualData[len(actualData) - 1].append(i)
        return actualData


def remapKeys():
    data = readKeyBindText()
    globalVar = data.pop(0)
    globalVar.pop(0)
    for i in globalVar:
        remapKey(i[0], i[1])
    for i in data:
        if curFocus(i[0]).focused:
            for j in range(1, len(i)):
                remapKey(i[j][0], i[j][1])


event: keyboard

try:
    a = open("keybinds.txt", "r")
    a.close()
    while True:
        event = keyboard.read_event()
        remapKeys()
except FileNotFoundError:
    a = open("keybinds.txt", "w")
    a.close()
    howTo = open("How to Use.txt", "w")
    howTo.writelines(
        "-----------------------\n"
        "     How to Use!\n"
        "    By Irshaad Ali\n"
        "-----------------------\n"
        "\n"
        "Layout: [Insert Name Of Application Title]\n"
        "        [Insert Keybind. Example: \"a -> left\"]\n"
        "Global Keys:\n"
        "To use keybinds everywhere, just place them first without a name above it.\n\n"
        "Assigned Game Keys:\n"
        "To use for specific games, type the application title and then the keybinds you want to\n"
        "use below it\n\n"
        "Have fun! - Irshaad"
    )
```
------------------------------------------------------------------------------
END

This was compiled by PyInstaller Python 3.10 Windows 10
Packages: PyInstaller, keyboard, pywin32
Compiled Console Command: python -m PyInstaller -F KeybindRemapper.py

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by crowplexus** [comment]
this may not be the correct repository

**Comment by Cobalt-Bar** [comment]
WHEEZE

**Comment by Eric-R-Malice** [comment]
😭

**Comment by Cobalt-Bar** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/79053181/ba90c4f2-09be-4204-8acd-de0fea503e4a)

**Comment by IrshaadAli1** [comment]
Cobalt you didn't even RUN the VM for jeez sake

**Comment by Cobalt-Bar** [comment]
can we just unban this dude, close this issue, and call it a day?

**Comment by Unholywanderer** [comment]
is this a bruh moment

**Comment by IrshaadAli1** [comment]
very certified bruh moment

**Comment by SMB-5** [comment]
what on earth happened here???

**Comment by RowanSkie** [comment]
either it's a false positive, or your machine got a virus itself and latched to the exe

also this is the first time I saw that we have a discord lmao

**Comment by BlueColorsin** [comment]
what the

**Comment by ShadowMario** [comment]
Unbanning you, don't make appeals on this github again or you will never get unbanned and will also get a free github ban
