### ISSUE TITLE
hmm Installer doesn't start

### ISSUE THREAD

**Issue by Wire-Firey** [ShadowMario/FNF-PsychEngine#13743]
### Describe your bug here.

Hello, when i want to run the "Hmm installer" trough Command prompt, it doesn't work, if theres something to fix, i would need help

### Command Prompt/Terminal logs (if existing)

```bash
haxelib run install hmm
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

not yet

**Comment by Cobalt-Bar** [comment]
`haxelib install hmm`
`haxelib run hmm install`

**Comment by Cobalt-Bar** [comment]
and the setup folder exists
