### ISSUE TITLE
0.6.3 VS 0.7

### ISSUE THREAD

**Issue by therealkiddude** [ShadowMario/FNF-PsychEngine#13740]
### What is your question?

People are saying 0.6.3 are more stable than 0.7, Why?

**Comment by 2JENO** [comment]
It's because so many things have changed

**Comment by crowplexus** [comment]
just use [this](https://github.com/CrowPlexus-FNF/FNF-LegacyPsych)

it is 0.6.3 with some stuff from 0.7 that makes sense to have since its better

**Comment by therealkiddude** [comment]
> just use [this](https://github.com/CrowPlexus-FNF/FNF-LegacyPsych)
> 
> 
> 
> it is 0.6.3 with some stuff from 0.7 that makes sense to have since its better

Thx bro
