### ISSUE TITLE
Compiling problem relating to FlxSound

### ISSUE THREAD

**Issue by Leviohso** [ShadowMario/FNF-PsychEngine#13749]
### Describe your problem here.

Tried to build the game and got this error

source/flixel/sound/FlxSound.hx:601: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/sound/FlxSound.hx:605: characters 19-27 : flash.media.SoundChannel has no field __source

Anyone know how to help?

my version is 0.7.1h

![image_2023-12-10_223823993](https://github.com/ShadowMario/FNF-PsychEngine/assets/118631934/e3b68a11-b829-490a-bb2c-b9aaadb430e4)
![image_2023-12-10_223947069](https://github.com/ShadowMario/FNF-PsychEngine/assets/118631934/8625870c-981d-49a3-b503-39f91806e731)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Stefan2008Git** [comment]
You need an `OpenFL 9.2.1` for `flash.media.MediaChannel` fix

**Comment by Leviohso** [comment]
Thanks man!

**Comment by Stefan2008Git** [comment]
> Thanks man!

Yw
