### ISSUE TITLE
how to remove OutdatedState in psych engine 0.6.3?

### ISSUE THREAD

**Issue by pablowolfgamerbr** [ShadowMario/FNF-PsychEngine#13741]
### What is your question?

I try to do this and I never succeed

**Comment by 2JENO** [comment]
compile your self then maybe removed

**Comment by Stefan2008Git** [comment]
> compile your self then maybe removed

No, wrong. He need to delete an entire OutdatedState file and updater code on TitleState

**Comment by 2JENO** [comment]
> > compile your self then maybe removed
> 
> No, wrong. He need to delete an entire OutdatedState file and updater code on TitleState
But that code won't run unless the officialbuild tag is added.

**Comment by crowplexus** [comment]
it gets automatically disabled if you are compiling as a mod

you can also turn off "Check for Updates" in the Options Menu
