### ISSUE TITLE
Problem with Lime test windows

### ISSUE THREAD

**Issue by Drew1972-1972** [ShadowMario/FNF-PsychEngine#13744]
### Describe your problem here.

when I put it in, I have absolutely everything I can get my hands on, git, haxe, dependencies, EVERYTHING. But when I put in VScode in the terminal "lime test windows" I get this error:
```haxe
source/psychlua/HScript.hx:168: characters 89-94 : Type not found : SCall
``` 
What can I do?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Stefan2008Git** [comment]
You have the wrong HScript.hx file added and oldest version or fork of SScript

**Comment by Cobalt-Bar** [comment]
go into the file, and replace every instance of "SCall" with "TeaCall"

**Comment by Stefan2008Git** [comment]
> go into the file, and replace every instance of "SCall" with "TeaCall"

Yeah and use the latest SScript for that

**Comment by Drew1972-1972** [comment]
> Este problema está obsoleto porque ha estado abierto durante 5 días sin actividad.

1_nesesitaba esperar las respuestas, no puedo estar comentando cada 0.5 horas para eso
2_igual ya solucioe el problema

**Comment by PedroNiccola** [comment]
I am trying to compile Psych Engine Source Code Edition, but powershell always tells me to Replace "SCall" with "TeaCall", even if the HxScript.hx file doesn't have SCall
