### ISSUE TITLE
Cant compile [0.7.1h]

### ISSUE THREAD

**Issue by chillultimated** [ShadowMario/FNF-PsychEngine#13752]
### Describe your bug here.

I tried to compile original 0.7.1h Source and got this. I didnt even changed anything, I just typed 'lime test windows' (ofc I installed libriries before that)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/86905561/080ee0b8-c7e2-48fa-86b5-3a63d1f3a3c2)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ender69funk** [comment]
[use this](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)

**Comment by chillultimated** [comment]
> [use this](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/86905561/e7daace8-3a27-4d49-a347-5d7693bcd0f2)
it says this now

**Comment by Stefan2008Git** [comment]
> > [use this](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)
> 
> ![image](https://private-user-images.githubusercontent.com/86905561/291032370-e7daace8-3a27-4d49-a347-5d7693bcd0f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMjQ3NTksIm5iZiI6MTcwMzAyNDQ1OSwicGF0aCI6Ii84NjkwNTU2MS8yOTEwMzIzNzAtZTdkYWFjZTgtM2EyNy00ZDQ5LWEzNDctNWQ3NjkzYmNkMGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDIyMjA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlY2IwMGRlYTZkNGFlMDcxM2NlNDQxNjZkN2M3YWVhZDllMTYxZDcxYzYwMzQ4MzU4NWJlZGIzMDA5ZWYxN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XLvk8IhBqEIMp1L2VLhyzuVd7AJAvGbJtjEym8LqCVw) it says this now

You need to replace `SCall` with `TeaCall``

**Comment by chillultimated** [comment]
> > > [use this](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/86905561/291032370-e7daace8-3a27-4d49-a347-5d7693bcd0f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMjQ3NTksIm5iZiI6MTcwMzAyNDQ1OSwicGF0aCI6Ii84NjkwNTU2MS8yOTEwMzIzNzAtZTdkYWFjZTgtM2EyNy00ZDQ5LWEzNDctNWQ3NjkzYmNkMGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDIyMjA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlY2IwMGRlYTZkNGFlMDcxM2NlNDQxNjZkN2M3YWVhZDllMTYxZDcxYzYwMzQ4MzU4NWJlZGIzMDA5ZWYxN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XLvk8IhBqEIMp1L2VLhyzuVd7AJAvGbJtjEym8LqCVw) it says this now
> 
> You need to replace `SCall` with `TeaCall`

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/86905561/c74a0075-2276-46ac-8e51-0f787e28c027)

**Comment by Stefan2008Git** [comment]
> > > > [use this](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/86905561/291032370-e7daace8-3a27-4d49-a347-5d7693bcd0f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMjQ3NTksIm5iZiI6MTcwMzAyNDQ1OSwicGF0aCI6Ii84NjkwNTU2MS8yOTEwMzIzNzAtZTdkYWFjZTgtM2EyNy00ZDQ5LWEzNDctNWQ3NjkzYmNkMGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDIyMjA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlY2IwMGRlYTZkNGFlMDcxM2NlNDQxNjZkN2M3YWVhZDllMTYxZDcxYzYwMzQ4MzU4NWJlZGIzMDA5ZWYxN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XLvk8IhBqEIMp1L2VLhyzuVd7AJAvGbJtjEym8LqCVw) it says this now
> > 
> > 
> > You need to replace `SCall` with `TeaCall`
> 
> ![image](https://private-user-images.githubusercontent.com/86905561/291844786-c74a0075-2276-46ac-8e51-0f787e28c027.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjQ5MTYsIm5iZiI6MTcwMzA2NDYxNiwicGF0aCI6Ii84NjkwNTU2MS8yOTE4NDQ3ODYtYzc0YTAwNzUtMjI3Ni00NmFjLThlNTEtMGY3ODdlMjhjMDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA5MzAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNDI4YzZlZmY4MTkxODU4YWE2ZTdhMzZhNTgyN2Q0YTU3MGVmMjVjYmU5ODBhYzZlZDI1NGE1NTlkMzA3NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l-lbuqDuRyLBaBS_1Zpu2DMV94wSEBrCQZHOGtFFV0M)

Use Haxe 4.2.5 for this fix because the latest Haxe version is bugged as fuck

**Comment by chillultimated** [comment]
> > > > > [use this](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/86905561/291032370-e7daace8-3a27-4d49-a347-5d7693bcd0f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMjQ3NTksIm5iZiI6MTcwMzAyNDQ1OSwicGF0aCI6Ii84NjkwNTU2MS8yOTEwMzIzNzAtZTdkYWFjZTgtM2EyNy00ZDQ5LWEzNDctNWQ3NjkzYmNkMGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDIyMjA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlY2IwMGRlYTZkNGFlMDcxM2NlNDQxNjZkN2M3YWVhZDllMTYxZDcxYzYwMzQ4MzU4NWJlZGIzMDA5ZWYxN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XLvk8IhBqEIMp1L2VLhyzuVd7AJAvGbJtjEym8LqCVw) it says this now
> > > 
> > > 
> > > You need to replace `SCall` with `TeaCall`
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/86905561/291844786-c74a0075-2276-46ac-8e51-0f787e28c027.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjQ5MTYsIm5iZiI6MTcwMzA2NDYxNiwicGF0aCI6Ii84NjkwNTU2MS8yOTE4NDQ3ODYtYzc0YTAwNzUtMjI3Ni00NmFjLThlNTEtMGY3ODdlMjhjMDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA5MzAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNDI4YzZlZmY4MTkxODU4YWE2ZTdhMzZhNTgyN2Q0YTU3MGVmMjVjYmU5ODBhYzZlZDI1NGE1NTlkMzA3NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l-lbuqDuRyLBaBS_1Zpu2DMV94wSEBrCQZHOGtFFV0M)
> 
> Use Haxe 4.2.5 for this fix because the latest Haxe version is bugged as fuck

I do have Haxe 4.2.5, its also sais Im using Haxe 4.2.5 in the SScript thingy

**Comment by ShadowMario** [comment]
Tomorrow Psych Engine will be updated, try compiling it again once its out
