### ISSUE TITLE
How can I make Color Swap only effect BF's notes?

### ISSUE THREAD

**Issue by KutikiPlayz** [ShadowMario/FNF-PsychEngine#1375]
### What is your question?

In my mod, I have separate note skins for the opponents, but I still want people to be able to change their own note colors. How can I make it so the color change option in the settings only affects the player's notes? I'm using source code.

**Comment by ShadowMario** [comment]
Lua or Source Code?

**Comment by KutikiPlayz** [comment]
source

**Comment by ShadowMario** [comment]
note.colorSwap.hue
note.colorSwap.saturation
note.colorSwap.brightness
