### ISSUE TITLE
How Can Fix HaxeLib Run hmm Install Error: Blocked

### ISSUE THREAD

**Issue by CofeeCupGames** [ShadowMario/FNF-PsychEngine#13755]
### Describe your problem here.

How Can fix this Mistake
![Captura de pantalla 2023-12-13 175107](https://github.com/ShadowMario/FNF-PsychEngine/assets/153774143/ba225c36-6067-4c61-9092-bfd7e907dd03)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ThePlank** [comment]
seems to be a haxelib issue, not psych's fault

also
> ### Are you modding a build from source or with Lua?
> 
> Lua

lmao????

**Comment by CofeeCupGames** [comment]
if it was a Haxe problem, now it was installed
