### ISSUE TITLE
It's a me or Psych Engine 0.7.1h had an some issue with opening an note color menu?

### ISSUE THREAD

**Issue by Stefan2008Git** [ShadowMario/FNF-PsychEngine#13750]
### Describe your bug here.

It's seems like for some reason for me it gaves this error that i never saw
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/20f105fa-7940-4314-b7e2-875d70abd0df)

### Command Prompt/Terminal logs (if existing)

```bash
`options/NotesSubState.hx (Line 710)
options/NotesSubState.hx (Line 151)
options/OptionsState.hx (Line 19)
options/OptionsState.hx (Line 162)
flixel/FlxState.hx (Line 220)
flixel/FlxGame.hx (Line 752)
flixel/FlxGame.hx (Line 682)
flixel/FlxGame.hx (Line 556)
openfl/events/EventDispatcher.hx (Line 402)
openfl/display/DisplayObject.hx (Line 1399)

Uncaught Error: Null Object Reference`
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Just some importing from my 0.6.3 buggy fork. Nothing special

**Comment by mcagabe19** [comment]
your coding issue probably it works fine at our mobile port

**Comment by Stefan2008Git** [comment]
> your coding issue probably it works fine at our mobile port

What? I didn't even changed the NotesSubState.hx?

**Comment by ShadowMario** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/bb7b3382-e038-4fb6-823a-76f844bf2aa9)
This may be why

**Comment by Stefan2008Git** [comment]
> ![image](https://private-user-images.githubusercontent.com/44785097/289988599-bb7b3382-e038-4fb6-823a-76f844bf2aa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MTE2NTUsIm5iZiI6MTcwMjQxMTM1NSwicGF0aCI6Ii80NDc4NTA5Ny8yODk5ODg1OTktYmI3YjMzODItZTAzOC00ZmI2LTgyM2EtNzZmODQ0YmYyYWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDIwMDIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZWM1ZDI2MmM2YTRjMDk3ZGZmZTdjMGY4ODNiYTgwY2Q0YjQwOGZmYWIxNTkxZGMyYTk5ODVmMGQ0OTc0OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qlYU5wgzSwTM_IIM9gI5AurvkbNjSLLEiFHv7ibuVCU) This may be why

As i said "from my 0.6.3 buggy fork", that means the current assets and more. I just need to know why is crashing. It's seems like it can be the ``updateNotes(true)`` for me for some reason, but i guess i am so dumbass to explain better

**Comment by MaysLastPlayGithub** [comment]
> your coding issue probably it works fine at our mobile port
Bahahahahahahaha, your mobile port is piece of bugs, so shut up and go finally improve yourself, because you're slowly going to have another cancellation document
