### ISSUE TITLE
Crashes when I miss.

### ISSUE THREAD

**Issue by InkScarlet1996** [ShadowMario/FNF-PsychEngine#13754]
### Describe your bug here.

If I miss, the mod/engine displays this window and closes immediately afterwards.

![Capture d’écran 2023-12-13 153724](https://github.com/ShadowMario/FNF-PsychEngine/assets/153747365/b17dfa7e-07e6-4a1e-a931-40d9edc1ca0c)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by SIYHW** [comment]
something might be wrong with the mod itself, check the scripts files and see if anythings unusal
