### ISSUE TITLE
"Type not found : SCall" in HScript.hx when i complie, pls help

### ISSUE THREAD

**Issue by Miuthoi123** [ShadowMario/FNF-PsychEngine#13751]
### Describe your problem here.

i have modfied in pe 0.7.1h for make my own engine
then i complie with command -> "lime test windows -debug" (i only test engine as debug before i complie release build)
then happen
![complie failed 1](https://github.com/ShadowMario/FNF-PsychEngine/assets/117433468/61c52f16-ff43-4c81-b63c-9754d9fd42ba)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, but i not edit HScript.hx file

**Comment by AbdooOwd** [comment]
Maybe it literally misses a `}`? You should send the code or the line itself

**Comment by Drew1972-1972** [comment]
habia algo mas que tienes que instalar, si quieres, mañana lo busco y te digo que es para que corrijas tu error

**Comment by cabfile** [comment]
iirc all you need to do is replace all instances of `SCall` with `TeaCall` in that file and it should work

**Comment by Miuthoi123** [comment]
@cabfile it work?

**Comment by cabfile** [comment]
yes

**Comment by Drew1972-1972** [comment]
listo, solucione el problema, ahora tengo otro problema con el referenciar aqui, pero le puse otra discucion para buscar una solucion, busquenla en las ultimas partes
