### ISSUE TITLE
Why is the download artifact for the engine "expired"

### ISSUE THREAD

**Issue by AFKenny** [ShadowMario/FNF-PsychEngine#13761]
### Describe your problem here.

i tried downloading this thing but it seems like the file/code/artifact is expired and i cannot download it.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

**Comment by cabfile** [comment]
download a build from [releases](https://github.com/ShadowMario/FNF-PsychEngine/releases)

**Comment by ShadowMario** [comment]
They get deleted after a few days, they're there just for quick-testing of builds

**Comment by PoketrainerMS** [comment]
> download a build from [releases](https://github.com/ShadowMario/FNF-PsychEngine/releases)

they (and i) are trying to download for mac, theres only windows and source code in releases.

**Comment by PoketrainerMS** [comment]
for the time being, use #13940 i guess, i just yoinked their test release 16, its only on 0.7.2h though.
to get the game to actually open instead of closing instantly, you need to open the package contents and run MacOS/PsychEngine

welcome to the struggle of being a mac user 👍 (this wasnt by my choice)

**Comment by kenshinuno** [comment]
> for the time being, use #13940 i guess, i just yoinked their test release 16, its only on 0.7.2h though. to get the game to actually open instead of closing instantly, you need to open the package contents and run MacOS/PsychEngine
> 
> welcome to the struggle of being a mac user 👍 (this wasnt by my choice)

sorry for the REALLY late reply. im quite a noob on github and i dont know where to download it from https://github.com/ShadowMario/FNF-PsychEngine/pull/13940 as i cant find a download button or artifact page :(

**Comment by PoketrainerMS** [comment]
> i found it but still says [this application "psych engine" cannot be opened]

open your terminal and do `chmod -R 755` and drag the .app file into the terminal, delete the space at the end, then hit enter
