### ISSUE TITLE
What the hell happened

### ISSUE THREAD

**Issue by therealkiddude** [ShadowMario/FNF-PsychEngine#13767]
### Describe your bug here.

I was about to play demoltion, my screen started to blackout for a moment and then when my screen exits the blackscreen I see that fnf was closed

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

JESUS CHRIST NO

**Comment by ender69funk** [comment]
screenshot pls

**Comment by ShadowMario** [comment]
That's a problem with the mod
