### ISSUE TITLE
Git content doesn't install

### ISSUE THREAD

**Issue by Wire-Firey** [ShadowMario/FNF-PsychEngine#13763]
### Describe your bug here.

Hello, when i was installing ever libraries, only Git content was not installing, i need help how i can install Git Libraries

### Command Prompt/Terminal logs (if existing)

```bash
haxelib git (Name,Url,Code)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

not yet

**Comment by mcagabe19** [comment]
haxelib git (name) (url)

**Comment by Wire-Firey** [comment]
well, i think i'll close this form, it's just because Git was not installed from another source
Thanks for helping me at least

**Comment by mcagabe19** [comment]
> well, i think i'll close this form, it's just because Git was not installed from another source Thanks for helping me at least

silly
