### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by skuzbum** [ShadowMario/FNF-PsychEngine#13765]
### Describe your bug here.

OK, so. I am trying to mod, i replace week one, with my mod using the engines, editor feature. after that, this little like corrupted week that is no where to be found in the files shows up. 
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/135698603/faaf2a23-ab67-4711-ab1e-d0d5f85ad59a)
And when scrolling down to the week that just doesnt exist, it crashes the game and says that the week is null. And I decide to just get a new decompile, and move things over slowly, the same thing still shows up, and the week files are just the default week files. and instead of scrolling down. I scrolled up from the tutorial and it sends me to the bottom of the list; **2 different previously made weeks** (that work btw) show up ingame that are not in the files. I don't know how this is happening as i have reverted all changes to all weeklist txt files, but since i am remaking the story mode screen completely, this might not be an issue. But it does make freeplay _entirely_ unusable, I now have to rework code to make freeplay ignore null weeks/objects.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/135698603/031ac0c6-c5b8-4e51-882f-ef984ee259fa)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, i didnt edit any base code, i just used the built in editors.

**Comment by ender69funk** [comment]
1. on story mode have null object because don't have weekname.png
2. idk
