### ISSUE TITLE
camGame turns Black when i put shaders on camHUD

### ISSUE THREAD

**Issue by FacunMax** [ShadowMario/FNF-PsychEngine#13768]
### Describe your problem here.

yeah, the title say everything. But i don't understand why it happend. heres the code and screenshots 
![Captura de pantalla (435)](https://github.com/ShadowMario/FNF-PsychEngine/assets/148605202/9fdb364b-8eb5-461d-802a-52e6ce65d9e3)
![Captura de pantalla (437)](https://github.com/ShadowMario/FNF-PsychEngine/assets/148605202/7d8fcd94-69e4-434c-bfc2-46b1110626de)
![Captura de pantalla (438)](https://github.com/ShadowMario/FNF-PsychEngine/assets/148605202/d83d422a-698d-4ccc-b713-e783b41868b9)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by FacunMax** [comment]
this is just an example, it happend with every shader that i put by me self, the others from the community it works but i don't get it

**Comment by FacunMax** [comment]
also yes, even putting "#define iChannel0 bitmap" and change the bitmap to iChannel0 it happends anyway

**Comment by cabfile** [comment]
the shader doesnt know transparency, that's literally the problem
replace the contents of the `mainImage` function with this:
```glsl
vec2 uv = fragCoord.xy / iResolution.xy;
vec4 rawColor = texture(bitmap, uv);
float alpha = rawColor.w;
float gray = dot(pow(rawColor.xyz, vec3(2.0)), vec3(0.2126, 0.7152, 0.0722));
float gammaGray = sqrt(gray);
fragColor = vec4(vec3(gammaGray),alpha);
```
just tested this on shadertoy (added `fragColor = vec4(vec3(fragColor.w),1.0);` to see the alpha values), it definitely works

**Comment by FacunMax** [comment]
> the shader doesnt know transparency, that's literally the problem replace the contents of the `mainImage` function with this:
> 
> ```glsl
> vec2 uv = fragCoord.xy / iResolution.xy;
> vec4 rawColor = texture(bitmap, uv);
> float alpha = rawColor.w;
> float gray = dot(pow(rawColor.xyz, vec3(2.0)), vec3(0.2126, 0.7152, 0.0722));
> float gammaGray = sqrt(gray);
> fragColor = vec4(vec3(gammaGray),alpha);
> ```
> 
> just tested this on shadertoy (added `fragColor = vec4(vec3(fragColor.w),1.0);` to see the alpha values), it definitely works

Yo thank u so much, now it works
