### ISSUE TITLE
Hi! I got this error while trying to launch Psych Engine and I am not sure how to fix it

### ISSUE THREAD

**Issue by Ehiokn** [ShadowMario/FNF-PsychEngine#13769]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/142696059/450ec73e-fbff-40d4-aac0-91df7d783d83)
^ Error Message ^

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by cabfile** [comment]
replace all instances of `__source` with `__audioSource` in FlxSound.hx

**Comment by Ehiokn** [comment]
Thanks! it worked, but problem...
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/142696059/7f2b0de0-7590-40ce-b6be-6db72dfa6d90)
I am getting a different error now

**Comment by cabfile** [comment]
do you have visual studio installed? if so, what version?

**Comment by Ehiokn** [comment]
I've got Visual Studio code but not Visual Studio

**Comment by Ehiokn** [comment]
What version of Visual Studio would I need?

**Comment by cabfile** [comment]
preferably 2022 (what i personally have), with c++ extensions

**Comment by Ehiokn** [comment]
alr I'll download rn

**Comment by Ehiokn** [comment]
Do you know which exact extensions I should install?

**Comment by cabfile** [comment]
sorry for the late response, just tick c++ and you should be good to go

**Comment by Ehiokn** [comment]
alr thanks

**Comment by Ehiokn** [comment]
where do you tick c++ tho? (sorry I am a bit dum)
