### ISSUE TITLE
A bug from FlxSound.hx

### ISSUE THREAD

**Issue by Miuthoi123** [ShadowMario/FNF-PsychEngine#13773]
### Describe your bug here.

I trying compile psych 0.7.1 on github actions then happens.

### Command Prompt/Terminal logs (if existing)

```bash
Yes

source/flixel/sound/FlxSound.hx:601: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/sound/FlxSound.hx:605: characters 19-27 : flash.media.SoundChannel has no field __source
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes but i not edit FlxSound.hx

**Comment by ShadowMario** [comment]
This was fixed on the experimental branch of psych, just delete source/flixel/system/FlxSound.hx and source/flixel/sound/FlxSound.hx then update your flixel
