### ISSUE TITLE
error "... referenced here", I don't know what to do

### ISSUE THREAD

**Issue by Drew1972-1972** [ShadowMario/FNF-PsychEngine#13775]
### Describe your problem here.

When I compile my mod, I get that error and I don't know how to fix it.
I have all the libraries I need updated, I have everything I requested, I even have the Psych engine and the original FNF, the only thing I didn't do because I don't know if it had to be done, is if I had to put the Psych engine folder in the FNF folder or the other way around, please help me )=

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ender69funk** [comment]
screenshot pls

**Comment by Drew1972-1972** [comment]
![Uploading import.hx - FNF-PsychEngine-main - Visual Studio Code 18_12_2023 06_30_01.png…]()

**Comment by ShadowMario** [comment]
Your screenshot is not working
