### ISSUE TITLE
how to make videosprite event 

### ISSUE THREAD

**Issue by myagmb28** [ShadowMario/FNF-PsychEngine#13772]
### Describe your problem here.

i have removed the 1st pic's string of value1
1st pic is old tho
but keeps not working
![image-15](https://github.com/ShadowMario/FNF-PsychEngine/assets/127576420/ecad720d-058f-4107-ad62-9077cfff07fe)
![image-20](https://github.com/ShadowMario/FNF-PsychEngine/assets/127576420/56b62776-cedc-4d82-8505-cbf34240a41f)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ender69funk** [comment]
idk

**Comment by ShadowMario** [comment]
This is not an issue you should be posting on Psych Github, contact the script author or whatever.
