### ISSUE TITLE
hxdiscord_rpc Not Found

### ISSUE THREAD

**Issue by Wire-Firey** [ShadowMario/FNF-PsychEngine#13771]
### Describe your bug here.

Hello, when i want to compile Psych Engine, it says that hxdiscord_rpc is missing but i've installed it, i don't know how to fix that, if someone can help me

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

not yet

**Comment by JonnycatMeow** [comment]
maybe you have a diffrent source code other than the original one and do this for installing it. haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc.git

**Comment by ender69funk** [comment]
btw it's a experimental 
if u wanna use hxdiscord to use this https://github.com/ShadowMario/FNF-PsychEngine/commit/0d7c6e0121838e0d1f215da639a0e858f010cb6b
