### ISSUE TITLE
Convert FNF to HTML?

### ISSUE THREAD

**Issue by therealkiddude** [ShadowMario/FNF-PsychEngine#13770]
### Describe your problem here.

Is there any way to convert FNF to an HTML file so It can be put in a web version?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

HELL NAH

**Comment by ShadowMario** [comment]
Psych no longer supports HTML
