### ISSUE TITLE
how to fix it

### ISSUE THREAD

**Issue by Bobchara** [ShadowMario/FNF-PsychEngine#13778]
### Describe your problem here.

source/flixel/system/FlxSound.hx:597: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/system/FlxSound.hx:601: characters 19-27 : flash.media.SoundChannel has no field __source
source/FunkinLua.hx:497: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:515: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:521: characters 10-15 : Class<llua.LuaL> has no field error

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
Fixed on experimental branch
