### ISSUE TITLE
How to fix?

### ISSUE THREAD

**Issue by Drifteer** [ShadowMario/FNF-PsychEngine#13782]
### Describe your problem here.

When compiling I keep getting this error
.haxelib/flixel/5,2,2/flixel/system/FlxSound.hx:752: characters 17-25 : flash.media.SoundChannel has no field __source

characters 14-22 : flash.media.SoundChannel has no field __source
 
Is there any fix?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Stefan2008Git** [comment]
> ### Describe your problem here.
> When compiling I keep getting this error .haxelib/flixel/5,2,2/flixel/system/FlxSound.hx:752: characters 17-25 : flash.media.SoundChannel has no field __source
> 
> characters 14-22 : flash.media.SoundChannel has no field __source
> 
> Is there any fix?
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> no

Use OpenFL 9.2.1 for fix ans set to that version
