### ISSUE TITLE
i have problems

### ISSUE THREAD

**Issue by Darkness929** [ShadowMario/FNF-PsychEngine#13787]
### Describe your bug here.

help me

### Command Prompt/Terminal logs (if existing)

```bash
source/psychlua/CallbackHandler.hx:54: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
source/backend/Paths.hx:576: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)
source/objects/Character.hx:299: characters 87-101 : flxanimate.animate.FlxAnim has no field lastPlayedAnim
source/objects/Character.hx:330: characters 20-26 : flxanimate.animate.FlxAnim has no field resume
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

.

**Comment by ShadowMario** [comment]
You are using the wrong libraries for Lua and FlxAnimate, [type `haxelib remove flxanimate` and `haxelib remove linc_luajit` then install the ones from this page.](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)
