### ISSUE TITLE
Small error when compiling (it's a bit of a sound from what it says)

### ISSUE THREAD

**Issue by Drew1972-1972** [ShadowMario/FNF-PsychEngine#13785]
### Describe your problem here.

When I compile the game I get this error:
`source/flixel/sound/FlxSound.hx:601: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/sound/FlxSound.hx:605: characters 19-27 : flash.media.SoundChannel has no field __source`
That's all I need to know

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Drew1972-1972** [comment]
now I only have one error, I deleted the FlxSound.hx (not the one in the Sound folder, but the other one) and replaced the lines of code with what it asked me for, now in the FlxSound or whatever it is called from the Sound folder, it only marks me this error from line 601:
`Missing fields for this`

**Comment by Stefan2008Git** [comment]
> ### Describe your problem here.
> When I compile the game I get this error: `source/flixel/sound/FlxSound.hx:601: characters 16-24 : flash.media.SoundChannel has no field __source source/flixel/sound/FlxSound.hx:605: characters 19-27 : flash.media.SoundChannel has no field __source` That's all I need to know
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> _No response_

Don't delete the FlxSound tho. Just use an OpenFL 9.2.1 for that and set that version simply. I got this issue firstly on 0.7.1h and fixed it using OpenFL 9.2.1 for that

**Comment by Jamextreme140** [comment]
I had the same problem. It is about the lastest version of OpenFL

Check this [PR](https://github.com/ShadowMario/FNF-PsychEngine/pull/13634) for more details.

**Comment by Stefan2008Git** [comment]
> I had the same problem. It is about the lastest version of OpenFL
> 
> Check this [PR](https://github.com/ShadowMario/FNF-PsychEngine/pull/13634) for more details.

Yeah i know that already. It's an latest OpenFL issue

**Comment by ShadowMario** [comment]
Issue should be fixed in 0.7.2+
