### ISSUE TITLE
Null Object Reference upon using "FlxG.mouse.overlaps"

### ISSUE THREAD

**Issue by TheRedperson** [ShadowMario/FNF-PsychEngine#13788]
### Describe your problem here.

When I use FlxG.mouse.overlaps(_aspritenamehere_), it seems to give a null object ref. The object that I used in the code is visible and present, and appears just fine without the script enabled (commented), but when I click on the object (FlxG.mouse.justPressed is used too), it gives a null object reference. Any help?

Code in question:
```
     if (FlxG.mouse.justPressed && FlxG.mouse.overlaps(discord_icon)) {
	       CoolUtil.browserLoad('https://ninja-muffin24.itch.io/funkin'); //placeholder
        }
}
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, many menus have been heavily modified, but they act just normal with or without this script.

**Comment by Vortex2Oblivion** [comment]
Try
```haxe

if (FlxG.mouse.justPressed && FlxG.mouse.overlaps(discord_icon) && discord_icon != null) {
	       CoolUtil.browserLoad('https://ninja-muffin24.itch.io/funkin'); //placeholder
        }
}
```
Maybe?

**Comment by TheRedperson** [comment]
Unfortunately, gives same error. I have confirmed it is something with FlxG.mouse.overlap() as if I only use the FlxG.mouse.justPressed, it does everything just fine (besides that if you click at all it sends you to a site)
![FNF _ Multiversal Madness 12_19_2023 12_43_32 PM](https://github.com/ShadowMario/FNF-PsychEngine/assets/90159750/20413542-547b-4795-bbb7-b5126ebe6cd9)

**Comment by Vortex2Oblivion** [comment]
What is on line 241 in in mainmenustate?

**Comment by Stefan2008Git** [comment]
> ### Describe your problem here.
> When I use FlxG.mouse.overlaps(_aspritenamehere_), it seems to give a null object ref. The object that I used in the code is visible and present, and appears just fine without the script enabled (commented), but when I click on the object (FlxG.mouse.justPressed is used too), it gives a null object reference. Any help?
> 
> Code in question:
> 
> ```
>      if (FlxG.mouse.justPressed && FlxG.mouse.overlaps(discord_icon)) {
> 	       CoolUtil.browserLoad('https://ninja-muffin24.itch.io/funkin'); //placeholder
>         }
> }
> ```
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> Yes, many menus have been heavily modified, but they act just normal with or without this script.

I can help about that. So basically you can't `if (FlxG.mouse.justPressed && FlxG.mouse.overlaps(spriteName)` in same time, but try this instead:

`if (FlxG.mouse.overlaps(github))
		{
			github.alpha = 1;
			github.scale.x = (FlxMath.lerp(github.scale.x, 0.12, 0.1));
			github.scale.y = (FlxMath.lerp(github.scale.y, 0.12, 0.1));

			if (FlxG.mouse.justPressed)
			CoolUtil.browserLoad("https://ninja-muffin24.itch.io/funkin");
		}
		else
		{
			github.alpha = 0.5;
			github.scale.x = (FlxMath.lerp(github.scale.x, 0.098, 0.1));
			github.scale.y = (FlxMath.lerp(github.scale.y, 0.098, 0.1));
		}`

You can remove the scale and alpha shit if you don't need it on your modified Psych build. I just showed an fixed code for you if you need it. If you got an Null Object Reference again, then i can't help. It works for me perfectly fine

**Comment by TheRedperson** [comment]
> > ### Describe your problem here.
> > When I use FlxG.mouse.overlaps(_aspritenamehere_), it seems to give a null object ref. The object that I used in the code is visible and present, and appears just fine without the script enabled (commented), but when I click on the object (FlxG.mouse.justPressed is used too), it gives a null object reference. Any help?
> > Code in question:
> > ```
> >      if (FlxG.mouse.justPressed && FlxG.mouse.overlaps(discord_icon)) {
> > 	       CoolUtil.browserLoad('https://ninja-muffin24.itch.io/funkin'); //placeholder
> >         }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Are you modding a build from source or with Lua?
> > Source
> > ### What is your build target?
> > Windows x64
> > ### Did you edit anything in this build? If so, mention or summarize your changes.
> > Yes, many menus have been heavily modified, but they act just normal with or without this script.
> 
> I can help about that. So basically you can't `if (FlxG.mouse.justPressed && FlxG.mouse.overlaps(spriteName)` in same time, but try this instead:
> 
> `if (FlxG.mouse.overlaps(github)) { github.alpha = 1; github.scale.x = (FlxMath.lerp(github.scale.x, 0.12, 0.1)); github.scale.y = (FlxMath.lerp(github.scale.y, 0.12, 0.1));
> 
> ```
> 		if (FlxG.mouse.justPressed)
> 		CoolUtil.browserLoad("https://ninja-muffin24.itch.io/funkin");
> 	}
> 	else
> 	{
> 		github.alpha = 0.5;
> 		github.scale.x = (FlxMath.lerp(github.scale.x, 0.098, 0.1));
> 		github.scale.y = (FlxMath.lerp(github.scale.y, 0.098, 0.1));
> 	}`
> ```
> 
> You can remove the scale and alpha shit if you don't need it on your modified Psych build. I just showed an fixed code for you if you need it. If you got an Null Object Reference again, then i can't help. It works for me perfectly fine

Thank You this worked
