### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by prockscac** [ShadowMario/FNF-PsychEngine#13794]
### Describe your bug here.

every time I try and compile 0.7.1h it says things like this.

### Command Prompt/Terminal logs (if existing)

```bash
user-MBP FNF-PsychEngine-0.7.1h % lime test mac
------------------------SScript 7.0.0 Macro------------------------
Special Thanks:
- CrowPlexus

Checking version...
You are using the 4.2.5 version of Haxe, SScript works best with Haxe 4.3.2. Consider updating Haxe.
Continuing...
-------------------------------------------------------------------

source/flixel/sound/FlxSound.hx:601: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/sound/FlxSound.hx:605: characters 19-27 : flash.media.SoundChannel has no field __source
/usr/local/lib/haxe/lib/linc_luajit/git/llua/State.hx:11: characters 24-49 : You cannot access the cpp package while in a macro (for cpp.RawPointer)
/usr/local/lib/haxe/lib/linc_luajit/git/llua/Lua.hx:4: characters 8-18 : ... referenced here
/Users/user/Desktop/hidden/FNF-PsychEngine-0.7.1h/source/import.hx:10: characters 8-16 : ... referenced here
/Users/user/Desktop/hidden/FNF-PsychEngine-0.7.1h/source/import.hx:4: characters 8-23 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,1,1/src/lime/media/AudioSource.hx:138: characters 53-100 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/media/Sound.hx:23: characters 8-30 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/utils/Assets.hx:9: characters 8-26 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/text/_internal/TextEngine.hx:9: characters 8-24 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/_internal/CairoTextField.hx:3: characters 8-40 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/_internal/CairoGraphics.hx:6: characters 8-36 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/filters/BitmapFilter.hx:6: characters 8-44 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/BitmapData.hx:14: characters 8-35 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/desktop/Icon.hx:4: characters 8-33 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/filesystem/File.hx:6: characters 8-27 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/events/InvokeEvent.hx:5: characters 8-30 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/Application.hx:15: characters 8-33 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/utils/_internal/Lib.hx:6: characters 8-34 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/DisplayObject.hx:6: characters 8-34 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,1,1/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,1,1/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,1,1/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,1,1/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,1,1/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,1,1/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,1,1/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,1,1/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,1,1/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,1,1/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,1,1/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,1,1/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
/usr/local/lib/haxe/lib/SScript/7,0,0/src/tea/SScript.hx:6: characters 8-18 : ... referenced here
/usr/local/lib/haxe/lib/SScript/7,0,0/src/hscriptBase/Interp.hx:28: characters 8-19 : ... referenced here
/usr/local/lib/haxe/lib/SScript/7,0,0/src/hscriptBase/Tools.hx:68: characters 7-13 : ... referenced here
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by BlackCatOnYoutube** [comment]
SScript: haxelib set sscript 7.7.0
Lime: haxelib set lime 8.0.1
Flixel: haxelib set flixel 5.5.0
Go check the other libraries to make sure their correct. I was giving 3 error fixes that might work.
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by prockscac** [comment]
> SScript: haxelib set sscript 7.7.0 Lime: haxelib set lime 8.0.1 Flixel: haxelib set flixel 5.5.0 Go check the other libraries to make sure their correct. I was giving 3 error fixes that might work. https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

okay so I tried those and it says the same thing but for those specific versions. user-MBP FNF-PsychEngine-0.7.1h % lime test mac
------------------------SScript 7.7.0 Macro------------------------
Special Thanks:
- CrowPlexus

Checking version...
There was an error getting the latest version info, you may not have internet connection.
Continuing...
-------------------------------------------------------------------

source/flixel/sound/FlxSound.hx:601: characters 16-24 : flash.media.SoundChannel has no field __source
export/release/macos/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
source/flixel/sound/FlxSound.hx:605: characters 19-27 : flash.media.SoundChannel has no field __source
export/release/macos/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
/usr/local/lib/haxe/lib/linc_luajit/git/llua/State.hx:11: characters 24-49 : You cannot access the cpp package while in a macro (for cpp.RawPointer)
/usr/local/lib/haxe/lib/linc_luajit/git/llua/Lua.hx:4: characters 8-18 : ... referenced here
/Users/user/Desktop/hidden/FNF-PsychEngine-0.7.1h/source/import.hx:10: characters 8-16 : ... referenced here
/Users/user/Desktop/hidden/FNF-PsychEngine-0.7.1h/source/import.hx:4: characters 8-23 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,0,1/src/lime/media/AudioSource.hx:138: characters 53-100 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/media/Sound.hx:23: characters 8-30 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/utils/Assets.hx:9: characters 8-26 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/text/_internal/TextEngine.hx:9: characters 8-24 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/_internal/CairoTextField.hx:3: characters 8-40 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/_internal/CairoGraphics.hx:6: characters 8-36 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/filters/BitmapFilter.hx:6: characters 8-44 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/BitmapData.hx:14: characters 8-35 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/desktop/Icon.hx:4: characters 8-33 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/filesystem/File.hx:6: characters 8-27 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/events/InvokeEvent.hx:5: characters 8-30 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/Application.hx:15: characters 8-33 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/utils/_internal/Lib.hx:6: characters 8-34 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/DisplayObject.hx:6: characters 8-34 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
/usr/local/lib/haxe/lib/openfl/9,3,2/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,0,1/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,0,1/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,0,1/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,0,1/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,0,1/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,0,1/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,0,1/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,0,1/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,0,1/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,0,1/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
/usr/local/lib/haxe/lib/lime/8,0,1/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
/usr/local/lib/haxe/std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here

**Comment by BlackCatOnYoutube** [comment]
Have you read the libraries?

**Comment by prockscac** [comment]
> Have you read the libraries?

okay you were right I used 0.7.2 and it started to compile but as it was done compiling it says this now

 Error: In file included from /usr/local/lib/haxe/lib/hxcpp/4,3,2/src/hx/Date.cpp:31:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:39:10: fatal error: 'CarbonCore/Script.h' file not found
#include <CarbonCore/Script.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.

and it just stays there and doesn't compile anymore.

**Comment by prockscac** [comment]
> Have you read the libraries? Also, what version are you on? I advice to go to Psych Engine 0.7.2 because the libraries have been updated.

never mind I successfully compiled it now, I just forgot to download Xcode on Mac.
