### ISSUE TITLE
current self-lerping is inconsistent

### ISSUE THREAD

**Issue by cyn0x8** [ShadowMario/FNF-PsychEngine#13791]
I noticed recently that Psych's current method of self-lerping (using `elapsed * speed` as lerp alpha) is inconsistent across different framerates.

<img src="https://github.com/ShadowMario/FNF-PsychEngine/assets/58795684/d1f31297-d795-4937-b7bc-d497f3e5d421" width=50%>

The lower the framerate, the faster the value would approach the target (15/30/60/120/240 fps in the image above), and as the framerate approaches infinity, the path approaches `1 - 1 / (e ^ (elapsed * speed))`.

Conveniently, this also happens to be the alpha value of the lerp that will produce this path.

<p float="left">

<img src="https://github.com/ShadowMario/FNF-PsychEngine/assets/58795684/548b3ba5-b39d-494b-85dc-49b78e5e5c77" width=45%>

<img src="https://github.com/ShadowMario/FNF-PsychEngine/assets/58795684/c76271b9-cda7-45f3-8b6e-ea1308fa7219" width=45%>

</p>

Using `lerp(start, goal, 1 - 1 / exp(elapsed * speed))` (or more simply `lerp(goal, start, exp(-elapsed * speed))`) would make the value's path consistent across any framerate as well as rid of the need to bound the alpha value.

**Comment by ShadowMario** [comment]
I don't get the issue so could you make a PR?
