### ISSUE TITLE
Psych engine crashes when a song doesn't have a "nomiss" achievement

### ISSUE THREAD

**Issue by Larnny** [ShadowMario/FNF-PsychEngine#13797]
### Describe your bug here.

If there is no achievement it's just shouldn't display it instead of crashing the entire game
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/67014977/a55c5b47-a592-42a9-8e60-795cd29eee85)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by SrBagel** [comment]
You should report this in the Psych Engine discord server.

**Comment by ShadowMario** [comment]
resolved
