### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by oh-no36** [ShadowMario/FNF-PsychEngine#13793]
### Describe your problem here.

source/flixel/sound/FlxSound.hx:601: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/sound/FlxSound.hx:605: characters 19-27 : flash.media.SoundChannel has no field __source
/Users/harry/FNF-PsychEngine/.haxelib/linc_luajit/git/llua/State.hx:11: characters 24-49 : You cannot access the cpp package while in a macro (for cpp.RawPointer)
/Users/harry/FNF-PsychEngine/.haxelib/linc_luajit/git/llua/Lua.hx:4: characters 8-18 : ... referenced here
/Users/harry/FNF-PsychEngine/source/import.hx:10: characters 8-16 : ... referenced here
/Users/harry/FNF-PsychEngine/source/import.hx:4: characters 8-23 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/media/AudioSource.hx:138: characters 53-100 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/media/Sound.hx:23: characters 8-30 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/utils/Assets.hx:9: characters 8-26 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/text/_internal/TextEngine.hx:9: characters 8-24 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/_internal/CairoTextField.hx:3: characters 8-40 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/_internal/CairoGraphics.hx:6: characters 8-36 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/filters/BitmapFilter.hx:6: characters 8-44 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/BitmapData.hx:14: characters 8-35 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/desktop/Icon.hx:4: characters 8-33 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/filesystem/File.hx:6: characters 8-27 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/events/InvokeEvent.hx:5: characters 8-30 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/Application.hx:15: characters 8-33 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/utils/_internal/Lib.hx:6: characters 8-34 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/DisplayObject.hx:6: characters 8-34 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
/Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
/usr/local/lib/haxe/std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Stefan2008Git** [comment]
> ### Describe your problem here.
> source/flixel/sound/FlxSound.hx:601: characters 16-24 : flash.media.SoundChannel has no field __source source/flixel/sound/FlxSound.hx:605: characters 19-27 : flash.media.SoundChannel has no field __source /Users/harry/FNF-PsychEngine/.haxelib/linc_luajit/git/llua/State.hx:11: characters 24-49 : You cannot access the cpp package while in a macro (for cpp.RawPointer) /Users/harry/FNF-PsychEngine/.haxelib/linc_luajit/git/llua/Lua.hx:4: characters 8-18 : ... referenced here /Users/harry/FNF-PsychEngine/source/import.hx:10: characters 8-16 : ... referenced here /Users/harry/FNF-PsychEngine/source/import.hx:4: characters 8-23 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/media/AudioSource.hx:138: characters 53-100 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/media/Sound.hx:23: characters 8-30 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/utils/Assets.hx:9: characters 8-26 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/text/_internal/TextEngine.hx:9: characters 8-24 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/_internal/CairoTextField.hx:3: characters 8-40 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/_internal/CairoGraphics.hx:6: characters 8-36 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/filters/BitmapFilter.hx:6: characters 8-44 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/BitmapData.hx:14: characters 8-35 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/desktop/Icon.hx:4: characters 8-33 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/filesystem/File.hx:6: characters 8-27 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/events/InvokeEvent.hx:5: characters 8-30 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/Application.hx:15: characters 8-33 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/utils/_internal/Lib.hx:6: characters 8-34 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/DisplayObject.hx:6: characters 8-34 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/openfl/9,3,2/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/lime/system/System.hx:4: characters 8-48 : ... referenced here /Users/harry/FNF-PsychEngine/.haxelib/lime/8,1,1/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here /usr/local/lib/haxe/std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Mac
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No

1. For flash.media.MediaChannel use OpenFL version 9.2.1 ans set that version
2.Did you used an latest Haxe version?
3. How the fuck can Lua be the issue with Haxelib errors?

**Comment by BlackCatOnYoutube** [comment]
Install this batch: https://github.com/ShadowMario/FNF-PsychEngine/issues/10756
