### ISSUE TITLE
Pixel notes issue (For me)

### ISSUE THREAD

**Issue by Stefan2008Git** [ShadowMario/FNF-PsychEngine#13792]
### Describe your problem here.

Okay, so bassically i got this 2 issues and 1 weird bug:

1. When i press CTRL on NotesSubState to change to pixel notes, it's gonna give this error with `updatePixel(true)`
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/caf0f9db-7f0f-40e9-a83f-88dc3b1ccb15)

2. The pixel assets offset are rotated on left position
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/4568ca2f-27a7-4d58-bd32-dce308ef0e79)

3. When i press the keybinds (doesn't matter what keybind i pressed) it's gonna give this error
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/9a9634a9-6743-42fd-a0e6-50580e87e9f1)

Someone said it can be an Note.hx problem because there is an missing function for that or it's something different. I don't fucking know why is giving this shit for me. I tried with many method and other solutions, but not of them are working to fix this fucking issue for pixel notes. If someone knows how to fix this issue, that can be helpful. Thanks!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing litterally, I just compiled normally build 1 week ago and i got this error

**Comment by Stefan2008Git** [comment]
[Similar from this repository](https://github.com/ShadowMario/FNF-PsychEngine/issues/13750), but who cares? I fixed that shit already. Now i have this shit for now

**Comment by ShadowMario** [comment]
This looks like an XML issue
