### ISSUE TITLE
I have a compilation problem

### ISSUE THREAD

**Issue by angeljamil10** [ShadowMario/FNF-PsychEngine#13790]
source/Main.hx:172: characters 67-71 : Float should be Int
source/Main.hx:172: characters 67-71 : ... For optional function argument 'updateFramerate'
source/meta/state/charting/ChartingState.hx:523: characters 36-37 : Int should be flixel.util.FlxAxes
source/meta/state/charting/ChartingState.hx:523: characters 36-37 : ... For optional function argument 'repeatAxes'

This is the problem I have, can you please help me?

**Comment by CharlesCatYT** [comment]
wrong label
