### ISSUE TITLE
How can I make an animated sprite similar to the train in week 3?

### ISSUE THREAD

**Issue by CrunchBar41** [ShadowMario/FNF-PsychEngine#1380]
### What is your question?

I'm using the lua build of Psych Engine, and I want to add in something like the train that will randomly show up and pass by. Any tips for how to get this to happen?

**Comment by Orionkidgaming** [comment]
tip: open lua then open the .lua file with notepad then copy and paste the code to the lua app.

**Comment by ShadowMario** [comment]
The train isn't an animated sprite, it simply moves to left.
