### ISSUE TITLE
Psych Engine 0.7 and so on issue

### ISSUE THREAD

**Issue by FridayDayFunkin** [ShadowMario/FNF-PsychEngine#13803]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

The game compiles perfectly, right? Like EXACTLY perfect. but then I get this dumb util.preloader error that cannot find "videos", theres more to this tho. theres even "assets" if i disable videos and no one knows how to fix this
![image_2023-12-21_165450947](https://github.com/ShadowMario/FNF-PsychEngine/assets/92032896/93ba7133-8020-4898-ac97-92b102d49a09)

### Are you modding a build from source or with Lua?

Source

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i didnt edit almost anything

**Comment by ShadowMario** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/05a06d81-1b9e-479c-8431-72f19f98fedc)
Be sure to check you didn't delete these two lines on Project.xml
