### ISSUE TITLE
 name of cameras

### ISSUE THREAD

**Issue by JHAM25** [ShadowMario/FNF-PsychEngine#13809]
### What is your question?

I did this to find out the name of the cameras:

    runHaxeCode([[
            game.botplayTxt.text = 'nombre de camaras:' + game.cameras.name;
    ]])

but when executed it says Null, does anyone know why this happens or am I doing something wrong?
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/a8606d24-5373-409e-9455-70a5f317bcd7)

**Comment by ShadowMario** [comment]
camGame or FlxG.camera = Where characters are
camHUD = Where notes, time bar, score text and health bar are
camOther = Normally used by Dialogue and transition screen fade, this camera normally stays completely still with 1x zoom forever

**Comment by JHAM25** [comment]
Thank you, but let me tell you what I was trying to do. I usually play on Android, and the controls are on a separate camera. I wanted to perform some actions with the controls' camera, but I don't know its name. That's why I was trying to use that code to find the camera's name, but it seems like it's not working as expected.
