### ISSUE TITLE
Hold Notes Issue

### ISSUE THREAD

**Issue by therealkiddude** [ShadowMario/FNF-PsychEngine#13818]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

After updating to the latest version, something has been weird, whenever I press hold notes and hold onto them my score is not extending and when I miss one thing in the hold note it wont count a miss again until next hold note

### Are you modding a build from source or with Lua?

Lua

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

NOOOOOOOOOOOOOOOOOOOOOOO

**Comment by ShadowMario** [comment]
> ### Describe your bug here.
> Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.
> 
> After updating to the latest version, something has been weird, whenever I press hold notes and hold onto them my score is not extending and when I miss one thing in the hold note it wont count a miss again until next hold note
> 
> ### Command Prompt/Terminal logs (if existing)
> _No response_
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### Which branch of the engine are you using?
> Latest (main)
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> NOOOOOOOOOOOOOOOOOOOOOOO

This is not a bug! It's actually a new gameplay option, if you want to disable it, turn this off at the end of the gameplay options:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/8b801101-0ea1-4296-a1b9-7e549994dfa6)

**Comment by therealkiddude** [comment]
Ohhhhhhhh

**Comment by therealkiddude** [comment]
This did not solve my problem, Sustain notes still doesen't add to my HP as it did in older versions
