### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Pregmonaoter** [ShadowMario/FNF-PsychEngine#13810]
### What feature do you want to get added on the **base** engine?

When Pressing F2 ( or whatever keybind set in settings) will activate the hey animation for bf

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by SrBagel** [comment]
Lua script

**Comment by Pregmonaoter** [comment]
ok ig this is closed now

**Comment by Pregmonaoter** [comment]
done
