### ISSUE TITLE
Story mode broken

### ISSUE THREAD

**Issue by TheKAPtain313** [ShadowMario/FNF-PsychEngine#13819]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

Whenever i try to play story mode it pops up with an error 
![Screenshot 2023-12-22 162334](https://github.com/ShadowMario/FNF-PsychEngine/assets/140554874/019df79e-4e71-4f03-b79d-8d5a4063ea42)

edit: it happens in freeplay too
### Command Prompt/Terminal logs (if existing)

```bash
Shown in photo
```

### Are you modding a build from source or with Lua?

I am not modding

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i added some hud scripts but thats abt it. Oh and aslo i made a new song useing bopeebo

**Comment by TripleLLL9** [comment]
the same thing happens to me but the invalid field is "overlayColor" and not "weekPlayableCharacter"
(keep in mind i have a bunch of mods loaded and im 99% sure it's those mods)

**Comment by ShadowMario** [comment]
> the same thing happens to me but the invalid field is "overlayColor" and not "weekPlayableCharacter" (keep in mind i have a bunch of mods loaded and im 99% sure it's those mods)

> Whenever i try to play story mode it pops up with an error !

Yeah you guys are having the same error, try searching for a week .JSON file that contains these invalid fields and delete it, this should work for a while until I push an actual fix.

**Comment by TripleLLL9** [comment]
> > the same thing happens to me but the invalid field is "overlayColor" and not "weekPlayableCharacter" (keep in mind i have a bunch of mods loaded and im 99% sure it's those mods)
> 
> > Whenever i try to play story mode it pops up with an error !
> 
> Yeah you guys are having the same error, try searching for a week .JSON file that contains these invalid fields and delete it, this should work for a while until I push an actual fix.

alr thanks ^_^

**Comment by TheKAPtain313** [comment]
> the same thing happens to me but the invalid field is "overlayColor" and not "weekPlayableCharacter" (keep in mind i have a bunch of mods loaded and im 99% sure it's those mods)

Same

**Comment by TheKAPtain313** [comment]
> > > the same thing happens to me but the invalid field is "overlayColor" and not "weekPlayableCharacter" (keep in mind i have a bunch of mods loaded and im 99% sure it's those mods)
> > 
> > 
> > > Whenever i try to play story mode it pops up with an error !
> > 
> > 
> > Yeah you guys are having the same error, try searching for a week .JSON file that contains these invalid fields and delete it, this should work for a while until I push an actual fix.
> 
> alr thanks ^_^



> > the same thing happens to me but the invalid field is "overlayColor" and not "weekPlayableCharacter" (keep in mind i have a bunch of mods loaded and im 99% sure it's those mods)
> 
> > Whenever i try to play story mode it pops up with an error !
> 
> Yeah you guys are having the same error, try searching for a week .JSON file that contains these invalid fields and delete it, this should work for a while until I push an actual fix.

Thanks, but only one problem I’m not that good with code and I do not know how to do that. Keep in mind I don’t have any apps that help me do code stuff.

**Comment by TripleLLL9** [comment]
just search for "content:weekPlayableCharacter" or search ".json" and look through them one-by-one :P

**Comment by TripleLLL9** [comment]
> just search for "content:weekPlayableCharacter" or search ".json" and look through them one-by-one :P

then just find anything that has "weekPlayableCharacter", then delete that line

**Comment by ShadowMario** [comment]
Possibly fixed, check it pls

**Comment by TripleLLL9** [comment]
the fix is in the source code, right? just makin sure if i have to compile it or not (sorry this is late ;-;)

**Comment by ShadowMario** [comment]
Yeah
