### ISSUE TITLE
Psych Engine 0.7.2 Source Code Compile Error

### ISSUE THREAD

**Issue by StrangeSpyder** [ShadowMario/FNF-PsychEngine#13814]
### Describe your problem here.

![cmd_IhuXFJB72o](https://github.com/ShadowMario/FNF-PsychEngine/assets/74561703/d6b9fc7a-4afd-40a1-b28f-ebe55ec90230)
![cmd_kGt6inl0wV](https://github.com/ShadowMario/FNF-PsychEngine/assets/74561703/546118c7-0637-4928-809d-a00324cd4559)
![cmd_hIf2uTzYpf](https://github.com/ShadowMario/FNF-PsychEngine/assets/74561703/cb734a48-1cd0-4105-846d-813ce2b37461)

I am attempting to compile the latest Psych Engine, but for some reason I keep ending up with these errors here. I have reinstalled Haxe, all the libraries as recommended and even ran the setup file for Windows to ensure that everything was installed correctly and still keep receiving these errors. I just need to know what Im missing or messing up so I can clean it up. Thank you!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, Nothing was adjusted.

**Comment by Offenderman445** [comment]
------------------------SScript 7.7.0 Macro------------------------
Special Thanks:
- CrowPlexus

Checking version...
There was an error getting the latest version info, you may not have internet connection.
Continuing...
-------------------------------------------------------------------

source/psychlua/CallbackHandler.hx:54: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)

Can you help me find what''s wrong with it
