### ISSUE TITLE
Character won't save again after saving once

### ISSUE THREAD

**Issue by FNFVacks** [ShadowMario/FNF-PsychEngine#13816]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

In Character Editor, attempting to save the character after you saved once will no longer show the popup box for saving, forcing you to re-enter the state and lose all progress. _(This was tested on a clean version of the build.)_

https://github.com/ShadowMario/FNF-PsychEngine/assets/116096314/2bb3a519-d5a9-4823-9340-50a721c56bc5

### Are you modding a build from source or with Lua?

I am not modding

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by qdartheawesomeman** [comment]
i also encountered the same issue.

**Comment by FNFVacks** [comment]
found the issue (atleast for me). When saving, it doesn't dispatch the event of saving so the variable `_file` doesn't turn null by the save function `onSaveComplete()`. When attempting to save character again, it doesn't show the prompt of saving due to in the first line of the function that it should return if `_file` is not null. I've removed this line and it works as normal again.

**Comment by trayfellow** [comment]
> found the issue (atleast for me). When saving, it doesn't dispatch the event of saving so the variable `_file` doesn't turn null by the save function `onSaveComplete()`. When attempting to save character again, it doesn't show the prompt of saving due to in the first line of the function that it should return if `_file` is not null. I've removed this line and it works as normal again.
> 
> _(For more information, this issue is actually caused by `FileDialog` when using `save()` with `FileReference`, `FileReference` would use `browse` (if not html5) and the one that has the function 'browse' is `FileDialog`. `FileDialog` doesn't call the `onSave` dispatch when completed which is what makes `_file` not null so making this issue here is technically pointless.)_

You should make this a pull request

**Comment by FNFVacks** [comment]
Oh yeah, `browse` doesn't call `onSave` when completed and instead calls `onSelect` when completed. _(`open()` and `save()` would call `onOpen` and `onSave`)_

You could fix this `_file` not null issue by just adding a listener to `onSelect` and not `onSave` if you're using `FileReference`. I'd probably open a pull request here to change this.
