### ISSUE TITLE
missing documention: Week 4 GF is in front of the limo

### ISSUE THREAD

**Issue by RowanSkie** [ShadowMario/FNF-PsychEngine#13813]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

In Week 4, GF and her speakers are in front of the limo. This has not happened back on other versions of FNF.

If this is part of the changes, please put it on the changelog in 0.7.2 or the readme.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/11764533/d796273f-d048-460a-bb11-c3591fa5403a)
(0.7.2 Release)

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/11764533/1eb96fdf-ca1a-45f5-8439-9f37759d7e88)
(Modified base Funkin' build)

### Are you modding a build from source or with Lua?

I am not modding

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by RowanSkie** [comment]
This is a repost of a previous bug where I mislabeled it as Week 5 (#13480)

**Comment by RowanSkie** [comment]
Also, it would help prevent other issues similar to this such as #12794 and #13266.

**Comment by ShadowMario** [comment]
> For starters this change was made back in 0.7. Shadow Mario has already said it is NOT a bug.

Yeah i just prefer it like that lol
Also this is a duplicate

**Comment by RowanSkie** [comment]
> > For starters this change was made back in 0.7. Shadow Mario has already said it is NOT a bug.
> 
> Yeah i just prefer it like that lol Also this is a duplicate

It's not documented on the readme though.
