### ISSUE TITLE
Combo thingy

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#1381]
### What feature do you want to get added on the base engine?

In gameplay that’s been been shown after the week 7 update, the unused combo image is used when hitting more than 10 notes with no misses. Maybe you could add this to the game?

**Comment by ShadowMario** [comment]
You know they didn't release the assets right? ¬¬

**Comment by crispyboi24** [comment]
> You know they didn't release the assets right? ¬¬

no i mean the combo thing thats in the game files. the black and white one that just says "combo". im not talking abt the leaked one on stream lol.
