### ISSUE TITLE
Crashes when i hit the notes

### ISSUE THREAD

**Issue by qdartheawesomeman** [ShadowMario/FNF-PsychEngine#13823]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

There is a huge problem.

When i press the arrows at the right time, it crashes
here's some proof
![bandicam 2023-12-23 06-35-20-733](https://github.com/ShadowMario/FNF-PsychEngine/assets/71853801/9afdc9eb-f2e8-4f87-b0b1-4e45698835b3)

### Are you modding a build from source or with Lua?

I am not modding

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by 2JENO** [comment]
did you update openfl to 9.3.2?
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by ShadowMario** [comment]
fixed
