### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by fg133266** [ShadowMario/FNF-PsychEngine#13829]
### Describe your problem here.

When I tried lime test windows
It reported an error
source/psychlua/HScript.hx:291: characters 89-96 : Type not found : TeaCall

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't do anything

**Comment by ShadowMario** [comment]
Are you on the latest version (0.7.2h)? If so, update SScript

**Comment by fg133266** [comment]
> 您使用的是最新版本 （0.7.2h） 吗？如果是这样，请更新 SScript

I updated SScript and then lime test windows
he error again
source/psychlua/CallbackHandler.hx:54: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
source/Main.hx:143: characters 28-35 : flixel.FlxCamera has no field filters (Suggestion: _filters)
source/backend/animation/PsychAnimationController.hx:10: characters 31-40 : Unknown identifier : timeScale
source/backend/animation/PsychAnimationController.hx:11: characters 50-68 : Class<flixel.FlxG> has no field animationTimeScale
source/objects/Note.hx:423: characters 39-48 : Float should be Int
source/objects/Note.hx:423: characters 39-48 : ... For optional function argument 'frameRate'
source/backend/Paths.hx:574: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)
source/objects/Character.hx:300: characters 87-101 : flxanimate.animate.FlxAnim has no field lastPlayedAnim
source/objects/Character.hx:331: characters 20-26 : flxanimate.animate.FlxAnim has no field resume
source/states/editors/CharacterEditorState.hx:1112: characters 9-20 : flixel.text.FlxText has no field fieldHeight
source/states/editors/CharacterEditorState.hx:1156: characters 63-66 : Float should be Int
source/states/editors/CharacterEditorState.hx:1156: characters 63-66 : ... For optional function argument 'FrameRate'
source/states/editors/CharacterEditorState.hx:1158: characters 49-52 : Float should be Int
source/states/editors/CharacterEditorState.hx:1158: characters 49-52 : ... For optional function argument 'frameRate'
source/states/PlayState.hx:1916: characters 10-28 : Class<flixel.FlxG> has no field animationTimeScale
source/states/PlayState.hx:685: characters 8-26 : Class<flixel.FlxG> has no field animationTimeScale
source/psychlua/TextFunctions.hx:54: characters 9-20 : flixel.text.FlxText has no field fieldHeight
source/states/PlayState.hx:3049: characters 8-26 : Class<flixel.FlxG> has no field animationTimeScale
source/backend/PsychCamera.hx:63: characters 5-18 : Unknown identifier : bindScrollPos
source/backend/PsychCamera.hx:20: characters 42-49 : Unknown identifier : filters
source/backend/PsychCamera.hx:20: characters 42-49 : Void should be Array<openfl.filters.BitmapFilter>
source/backend/PsychCamera.hx:20: characters 42-49 : ... For function argument 'value'
The version is 0.7.2h

**Comment by fg133266** [comment]
> > 您使用的是最新版本 （0.7.2h） 吗？如果是这样，请更新 SScript
> 
> 我更新了 SScript，然后 lime 测试窗口再次出错 source/psychlua/CallbackHandler.hx：54：字符 18-33：Class<llua。Lua_helper>没有字段 sendErrorsToLua source/Main.hx：143：字符 28-35：flixel。FlxCamera没有字段过滤器（建议：_filters） source/backend/animation/PsychAnimationController.hx：10：字符 31-40：未知标识符：timeScale source/backend/animation/PsychAnimationController.hx：11：字符 50-68：Class<flixel。FlxG> 没有字段 animationTimeScale source/objects/Note.hx：423：字符 39-48：浮点数应为 Int source/objects/Note.hx：423：字符 39-48：...对于可选函数参数 'frameRate' source/backend/Paths.hx：574：字符 7-18：flxanimate。FlxAnimate 没有字段 loadAtlasEx（建议：loadAtlas） source/objects/Character.hx：300：字符 87-101：flxanimate.animate.FlxAnim 没有字段 lastPlayedAnim source/objects/Character.hx：331：字符 20-26：flxanimate.animate.FlxAnim 没有字段 resume source/states/editors/CharacterEditorState.hx：1112：字符 9-20：flixel.text.FlxText 没有字段 fieldHeightsource/states/editors/CharacterEditorState.hx：1156：字符 63-66：浮点数应为 Int source/states/editors/CharacterEditorState.hx：1156：字符 63-66：...对于可选函数参数 'FrameRate' source/states/editors/CharacterEditorState.hx：1158：字符 49-52：浮点数应为 Int source/states/editors/CharacterEditorState.hx：1158：字符 49-52：...对于可选函数参数 'frameRate' source/states/PlayState.hx：1916：字符 10-28：Class<flixel。FlxG> 没有字段 animationTimeScale source/states/PlayState.hx：685：字符 8-26：Class<flixel。FlxG> 没有字段 animationTimeScale source/psychlua/TextFunctions.hx：54：字符 9-20：flixel.text.FlxText 没有字段 fieldHeight source/states/PlayState.hx：3049：字符 8-26：类<flixel。FlxG> 没有字段 animationTimeScale source/backend/PsychCamera.hx：63：字符 5-18：未知标识符：bindScrollPos source/backend/PsychCamera.hx：20：字符 42-49：未知标识符：过滤器 source/backend/PsychCamera.hx：20：字符 42-49：Void 应该是 Array<openfl.filters.BitmapFilter> source/backend/PsychCamera.hx：20：字符 42-49：...对于函数参数“value”，版本为 0.7.2h

Oh I've solved this
