### ISSUE TITLE
Crashes when booting up on 0.7.2

### ISSUE THREAD

**Issue by Tattleamelia** [ShadowMario/FNF-PsychEngine#13824]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

Self-explanatory, can't play the new update because the game crashes when I try to boot it up on both the 32-bit and 64-bit versions. 32-bit says "Could not load module lime@lime_application_create__prime" while 64-bit says "[lime.utils.Preloader] ERROR: There is no asset library with an ID of "videos"".

### Are you modding a build from source or with Lua?

I am not modding

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Used the downloads directly on the Releases page.

**Comment by Theluck1125** [comment]
its like this in the 64 bits error?
![2023-12-23](https://github.com/ShadowMario/FNF-PsychEngine/assets/154700939/78b06d07-cae9-4249-8b39-f0b90dc79dc0)
btw i have the same problem

**Comment by Tattleamelia** [comment]
Yep, I mentioned it was like that.

**Comment by ShadowMario** [comment]
Did you extract it over an existing Psych folder?

**Comment by Tattleamelia** [comment]
Yes I did, does that cause issues?

**Comment by ShadowMario** [comment]
Yes it does
