### ISSUE TITLE
Will the existing achievements in Psych Engine ever be ported to lua now that lua achievements are possible?

### ISSUE THREAD

**Issue by Eric-R-Malice** [ShadowMario/FNF-PsychEngine#13820]
### What is your question?

Post name is self-explanatory - now that lua achievements are in Psych, will the existing achievements ever be moved from source to lua?

**Comment by crowplexus** [comment]
probably not given that psych was meant to be hybrid between source modding and lua modding

**Comment by Eric-R-Malice** [comment]
> probably not given that psych was meant to be hybrid between source modding and lua modding

Fuck. Welp, thanks for the response.

**Comment by ShadowMario** [comment]
Those achievements will be kept inside the source as an example of how you can do your owns

**Comment by Eric-R-Malice** [comment]
> Those achievements will be kept inside the source as an example of how you can do your owns

fair - turns out they werent that hard to remove anyway
