### ISSUE TITLE
Crashed When Exiting Mod Menu

### ISSUE THREAD

**Issue by Donobodude** [ShadowMario/FNF-PsychEngine#13821]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

I just updated the engine and moved all my mods over, but when I exited out of the new mod menu the game crashed

flixel/graphics/frames/FlxAtlasFrames.hx (line 401)
flixel/graphics/frames/FlxAtlasFrames.hx (line 247)
objects/Alphabet.hx (line 420)
objects/Alphabet.hx (line 348)
C:\HaxeToolkit\haxe\std/cpp/_std/Type.hx (line 90)
flixel/group/FlxGroup.hx (line 338)
objects/Alphabet.hx (line 218)
objects/Alphabet.hx (line 85)
objects/Alphabet.hx (line 37)
states/TitleState.hx (line 495)
states/TitleState.hx (line 552)
backend/MusicBeatState.hx (line 177)
backend/MusicBeatState.hx (line 64)
states/TitleState.hx (line 488)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I use the downloaded builds, but I have some mods installed

**Comment by ShadowMario** [comment]
Please try to identify which mod is causing this issue

**Comment by Donobodude** [comment]
I attempted to replicate it, and it didn't crash again _but_ it DID do some other funky things. [A Splatoon one-off mod](https://gamebanana.com/mods/445058) had the game restart when I moved it and I got softlocked every time

This is also on 0.7.2

**Comment by LeonGamerPS4** [comment]
i’m having the same issue as well, but it only applies to mods that restart the game
