### ISSUE TITLE
Miss popup

### ISSUE THREAD

**Issue by TheKAPtain313** [ShadowMario/FNF-PsychEngine#13835]
### What feature do you want to get added on the **base** engine?

I think you should add like a miss popup where like the sick goes every time you miss and have gf do a miss animation kinda like the one in the og game

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by LeonGamerPS4** [comment]
is this really needed? psych doesn't need to have so many features like this
