### ISSUE TITLE
Character JSONs no longer working

### ISSUE THREAD

**Issue by Bopple-McNuggets** [ShadowMario/FNF-PsychEngine#13838]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

When I updated to 0.7.2, it turns out a good handful of the spritesheets I had modded in the game that worked perfectly fine in 0.7.1 suddenly wouldn't function, turning into a sprite-less character with the default icon and red health bar. I can't find any consistency in this either, as certain other characters I'd modded in worked just fine. Hopefully this isn't a me-only thing.

Below are two of the jsons I put in the game, one which stopped working and one which still works.
[expunged-true-small-alt.json](https://github.com/ShadowMario/FNF-PsychEngine/files/13761033/expunged-true-small-alt.json) (this one is broken)
[disruption.json](https://github.com/ShadowMario/FNF-PsychEngine/files/13760979/disruption.json) (this one is fine)

### Are you modding a build from source or with Lua?

Lua

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
I really will need more information (screenshots or error log)

**Comment by Bopple-McNuggets** [comment]
ok so i was about to get those screenshots to send over (the delay came from a lack of internet access at the time) but it turns out yep, the problem was unneeded commas that fsr only now pose an issue lol
