### ISSUE TITLE
BRUH! My notes :(

### ISSUE THREAD

**Issue by shyguyFNF** [ShadowMario/FNF-PsychEngine#13830]
### Describe your problem here.

Just installed the new update for christmas and the freaking bullet notes are not working. 
The dodge animation for bf (called shoot) and attack animation for the opponent (called shot) (yeah I l know it's wrong lol) don't show! But in the last version were working perfectly. WHAT'S GOING ON help (love you :D)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by JHAM25** [comment]
Can you send the code because things have changed in the last update I think

**Comment by shyguyFNF** [comment]
> Can you send the code because things have changed in the last update I think

sure!

function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is an Instakill Note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Bullet_Note' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'noteTypes/Bullet_Note'); 

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then 
			end
		end
	end
	--debugPrint('Script started!')
end

-- Function called when you hit a note (after note hit calculations)
-- id: The note member id, you can get whatever variable you want from this note, example: "getPropertyFromGroup('notes', id, 'strumTime')"
-- noteData: 0 = Left, 1 = Down, 2 = Up, 3 = Right
-- noteType: The note type string/tag
-- isSustainNote: If it's a hold note, can be either true or false


-- Called after the note miss calculations
-- Player missed a note by letting it go offscreen

function goodNoteHit(id, direction, noteType, isSustainNote)
	if noteType == 'Bullet_Note' then
		playSound('gun', 1);
		triggerEvent('Play Animation', 'shoot', 'BF') 
		triggerEvent('Play Animation', 'shot', 'Dad') 
		cameraShake('camGame', 0.01, 0.2)
		setProperty('health', getProperty('health')+0.09);
	end
end

function noteMiss(id, direction, noteType, isSustainNote)
	if noteType == "Bullet_Note" then
		setProperty('health', -500);
	end
end

**Comment by JHAM25** [comment]
Try changing the file name to Bullet_Note.lua I named it and it works for me

**Comment by L0llFNF** [comment]
> Try changing the file name to Bullet_Note.lua I named it and it works for me

It doesn't for me, but I think that the problem is the update or lua filea cuz I just put the middle note lua file in my song data and it doesn't work either and instead in the old version did

**Comment by JHAM25** [comment]
I didn't realize that another version has been released, I will update and try to see what happens

**Comment by L0llFNF** [comment]
> I didn't realize that another version has been released, I will update and try to see what happens

Okaaaay

**Comment by ShadowMario** [comment]
Someone changed goodNoteHit's position on the code and i decided to just go along with it, so rename it to goodNoteHitPost

**Comment by L0llFNF** [comment]
> wait replace goodNoteHit with goodNoteHitPost and works

hey sorry I was out for christmas and couldn't reply, anyway it doesn't work sadly
