### ISSUE TITLE
Audio reset issue with new freeplay system

### ISSUE THREAD

**Issue by Omega-XYT** [ShadowMario/FNF-PsychEngine#13833]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

When previewing a song with the new freeplay system, if you press escape (or probably whatever your back bind is) it resets your game volume to max.

### Are you modding a build from source or with Lua?

Lua

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not edit any base game files.

**Comment by ShadowMario** [comment]
Fixed, redownload 0.7.2h
