### ISSUE TITLE
Need Help - Main Menu

### ISSUE THREAD

**Issue by KingNickOfficial** [ShadowMario/FNF-PsychEngine#13837]
### Describe your problem here.

So, I want to move all my buttons from the middle to the left, with a yellow box behind it. How would I do this in MainMenuState.hx?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I made a new title + pause screen, but I don't think any of that matters.

**Comment by VIRUSnik00** [comment]
Where is this file?
