### ISSUE TITLE
hit sounds

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#1384]
### Describe your problem here.

how do i add hit sounds to a custom note?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

idk

**Comment by Gui-iago** [comment]
do `playSound("sound-name", 1)` on your note's function
sound needs to go inside assets/sounds as far as I know

**Comment by THOBY555** [comment]
lmao i dont like hit Sounds mid-song

**Comment by PDL2CGamejolt** [comment]
aaaaaaaa

**Comment by NotEpik** [comment]
There is no folder in /mods named "sounds" right? Make one and get the file of sound you want in "Ogg" type and put this in the custom note Lua code.

```
function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'note type' then
		playSound("hitsound", 1.5)
	end
end
```

This should work :D

**Comment by MayoALT** [comment]
close issue plz

**Comment by BombasticTom** [comment]
> There is no folder in /mods named "sounds" right? Make one and get the file of sound you want in "Ogg" type and put this in the custom note Lua code.
> 
> ```
> function goodNoteHit(id, noteData, noteType, isSustainNote)
> 	if noteType == 'note type' then
> 		playSound("hitsound", 1.5)
> 	end
> end
> ```
> 
> You can change the volume to anything you want the loud it be and change "hitsound" to the file name
> 
> This should work :D
> 
> result:
> 
>  bandicam.2021-11-27.22-30-59-713.mp4

i know this is really old but you should do instead of note type maybe `if not isSustainNote` because the held notes will still play the sound while holding them.

**Comment by BombasticTom** [comment]
oh wait this is for a custom note whoops sorry
