### ISSUE TITLE
Help, I'm compiling the fnf psych ingine and I get this

### ISSUE THREAD

**Issue by Soylepero** [ShadowMario/FNF-PsychEngine#13846]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

source/states/PlayState.hx:13: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
source/states/editors/ChartingState.hx:9: characters 8-44 : Type not found : flixel.addons.display.FlxGridOverlay
source/states/editors/CharacterEditorState.hx:8: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
source/substates/PauseSubState.hx:7: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
source/states/MainMenuState.hx:4: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
source/states/PlayState.hx:36: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
source/states/TitleState.hx:7: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIState.hx:4: characters 8-43 : Type not found : flixel.addons.transition.Transition
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIState.hx:5: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
source/backend/MusicBeatState.hx:4: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
source/psychlua/FunkinLua.hx:12: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
source/psychlua/FunkinLua.hx:15: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
source/backend/Discord.hx:5: characters 8-29 : Type not found : hxdiscord_rpc.Discord
source/backend/Discord.hx:6: characters 8-27 : Type not found : hxdiscord_rpc.Types
source/backend/Discord.hx:13: characters 30-49 : Type not found : DiscordRichPresence

### Command Prompt/Terminal logs (if existing)

```bash
source/states/PlayState.hx:13: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
source/states/editors/ChartingState.hx:9: characters 8-44 : Type not found : flixel.addons.display.FlxGridOverlay
source/states/editors/CharacterEditorState.hx:8: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
source/substates/PauseSubState.hx:7: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
source/states/MainMenuState.hx:4: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
source/states/PlayState.hx:36: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
source/states/TitleState.hx:7: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIState.hx:4: characters 8-43 : Type not found : flixel.addons.transition.Transition
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIState.hx:5: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
source/backend/MusicBeatState.hx:4: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
source/psychlua/FunkinLua.hx:12: characters 8-55 : Type not found : flixel.addons.transition.FlxTransitionableState
source/psychlua/FunkinLua.hx:15: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
source/backend/Discord.hx:5: characters 8-29 : Type not found : hxdiscord_rpc.Discord
source/backend/Discord.hx:6: characters 8-27 : Type not found : hxdiscord_rpc.Types
source/backend/Discord.hx:13: characters 30-49 : Type not found : DiscordRichPresence
```

### Are you modding a build from source or with Lua?

Source

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

xd

**Comment by Soylepero** [comment]
I'm new to git hub

**Comment by ShadowMario** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions
Check this
