### ISSUE TITLE
Error Involving the PsychLua Folder

### ISSUE THREAD

**Issue by AnonymousPerson10112** [ShadowMario/FNF-PsychEngine#13847]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

I was busy trying to compile a build of Psych Engine 0.7.2, when all of a sudden, I got this error.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/100014521/8be48423-7e12-4e84-bd48-3569a8010c34)

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\l7910\Downloads\FNF-PsychEngine-0.7.2\FNF-PsychEngine-0.7.2>lime test windows
source/psychlua/CallbackHandler.hx:54: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
```

### Are you modding a build from source or with Lua?

Lua and Source

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes. I simply changed the name of the window title in the Project.xml file. Other than that, no.

**Comment by XTihX1** [comment]
do `haxelib remove linc_luajit` then `haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git`
