### ISSUE TITLE
Need help coding a lua achievement.

### ISSUE THREAD

**Issue by Loganthegamer12678** [ShadowMario/FNF-PsychEngine#13845]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/86275915/bf2bf1e4-1aa3-456f-8ba3-6c09725129c7)

Tried to make an achievement that can be unlocked if you got blueballed 10 times. This was inspired by an achievement from the Simpsons game that can be unlocked upon dying 10 times.

```
function onGameOver() 
addAchievementScore(pwned, 1, saveIfNotUnlocked = false);
end
```

I looked at everything, alright?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Loganthegamer12678** [comment]
I think I figured out the achievement part, but I still need help about the death count part

**Comment by Loganthegamer12678** [comment]
Tried the addAchievementScore function, but uh....

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/86275915/22f228fd-3e69-4e47-8f18-f4bf5341c886)

**Comment by Draconic-Hybrid** [comment]
You don't need the `saveIfNotUnlocked = `, just keep the `false`. And if you're doing a death counter, wouldn't you generally want it to be true?

**Comment by Loganthegamer12678** [comment]
Thanks for the tip. It's gonna take a while before I close this. But if I come across any more problems, I'll give you more updates.

**Comment by Loganthegamer12678** [comment]
Bad news: The score is not increasing even if I set it to true.

```
function onGameOver() 
addAchievementScore(pwnd, 1, true);
end
```

**Comment by Draconic-Hybrid** [comment]
The name of the achievement (the first part) is a string, so put quotes around it

Should look like this:
```lua
function onGameOver()
addAchievementScore("pwnd", 1, true)
end
```

**Comment by Loganthegamer12678** [comment]
OMG thank you! The code is working now! Can't wait to embarrass some noobs.
