### ISSUE TITLE
Key pressing is still enabled during cutscenes

### ISSUE THREAD

**Issue by trayfellow** [ShadowMario/FNF-PsychEngine#13848]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

During week 6's dialogue or week 7's talking cutscene when it hasn't ended yet, no ghost tapping players can still press keys causing them to lose health when they're not supposed to yet

### Are you modding a build from source or with Lua?

I am not modding

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, mods were taken off while testing this

**Comment by ShadowMario** [comment]
fixed
