### ISSUE TITLE
xml character randomly stops working

### ISSUE THREAD

**Issue by imsolito** [ShadowMario/FNF-PsychEngine#13859]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

Then I will tell in a basic and literal way what happened.
I made the XML, and all the files worked more than correctly, everything was fine.
I tried the Sprites in some songs and suddenly this error appeared.
"Ok, open the deleted chart" I thought, and literally everything is the same as before.
Reinstall Phsyc engine just in case, I don't understand why by playing a song the file should stop working in an instant.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/141895324/d7219738-07a0-4c17-ae92-76d9499c03a0)

### Are you modding a build from source or with Lua?

Lua

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I tried to install Hex, it didn't work.

**Comment by ShadowMario** [comment]
Did you manually edit the character json?
