### ISSUE TITLE
Android and IOS Port

### ISSUE THREAD

**Issue by MarioGuyWasTaken** [ShadowMario/FNF-PsychEngine#1385]
### What feature do you want to get added on the base engine?

If this is possible make a Android and iOS port!

**Comment by BocaIoachim** [comment]
i dont think he will

**Comment by Gui-iago** [comment]
there is a fanmade android port being made already, https://github.com/jigsaw-4277821/Psych-Engine-Android-Port/issues

apk: https://drive.google.com/file/d/1PI69tmcBK6IPdSmfwaRD7n7wBri8WDdM/view

**Comment by MaxlionButMyNameIsTakenSoThisIsmyName** [comment]
just add mouse compatability and and export to android/ios lmao
