### ISSUE TITLE
script compatibility

### ISSUE THREAD

**Issue by FNaS2ToySonic** [ShadowMario/FNF-PsychEngine#13850]
### What is your question?

Can someone help me make this piece of code be compatible with psych engine v0.7?
```
function goodNoteHit(id, direction, noteType, isSustainNote)
    dir = getPropertyFromClass("notes", direction)
    if dir == 0 then
        noteTweenAlpha("alpha1", 4, 1, 0.01)
        noteTweenAlpha("alphaback1", 4, 0.25, 0.25)
    end
--that's not the full code btw
```

**Comment by ShadowMario** [comment]
First off, remove `dir = getPropertyFromClass("notes", direction)` and change `if dir == 0` to `if direction == 0`, you were not using getPropertyFromClass correctly

**Comment by FNaS2ToySonic** [comment]
> First off, remove `dir = getPropertyFromClass("notes", direction)` and change `if dir == 0` to `if direction == 0`, you were not using getPropertyFromClass correctly

i already figured out how this works

**Comment by ShadowMario** [comment]
> > First off, remove `dir = getPropertyFromClass("notes", direction)` and change `if dir == 0` to `if direction == 0`, you were not using getPropertyFromClass correctly
> 
> i already figured out how this works

Then close the goddamn issue
