### ISSUE TITLE
I have a big issue trying to get this to run

### ISSUE THREAD

**Issue by underbend** [ShadowMario/FNF-PsychEngine#13854]
### Describe your problem here.

This current issue
"C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat should be declared with 'override' since it is inherited from superclass flixel.graphics.frames.FlxAtlasFrames
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat overrides parent class with different or incomplete type
C:/HaxeToolkit/haxe/lib/flixel/5,5,0/flixel/graphics/frames/FlxAtlasFrames.hx:457: characters 18-24 : ... Base field is defined here
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : ... Different number of function arguments
source/backend/Paths.hx:574: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)
source/objects/Character.hx:300: characters 87-101 : flxanimate.animate.FlxAnim has no field lastPlayedAnim
source/objects/Character.hx:331: characters 20-26 : flxanimate.animate.FlxAnim has no field resume"

I've done everything that necessary:
flixel: 5.5.0
flixel-addons: 3.2.1
flixel-tools: 1.5.1
flixel-ui: 2.5.0
flxanimate: git, to install use: haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev
hxCodec: git, to install, use: haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git
hxdiscord_rpc: git, to install, use: haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc.git
lime: 8.0.1
linc_luajit: git, to install, use: haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git
openfl: 9.3.2
SScript: 7.7.0
tjson: 1.4.0
 
 I even double checked to make sure these were working, and I keep getting this error message. Please help me

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by ShadowMario** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions
Read this, reinstall FlxAnimate and use the one in this link

**Comment by underbend** [comment]
Thank you shadow, psych is actually loading now- however for some reason when the application loads up it says: 

[lime.utilis.Preloader] ERROR: There is no asset library with an ID of "videos"

the strange thing is there is, there is a file named videos but it keep giving me that, what I did after was remove the VIDEO_ALLOWED Line of code to test things out, and then after that it hit me with:

[lime.utilis.Preloader] ERROR: There is no asset library with an ID of "songs"

Do you think you could help me with that too, I'm actually quite stumped on what it wants me to do here this time


> https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions Read this, remove FlxAnimate and install the one in this link

**Comment by thegreatskep** [comment]
what method are you using to run the executable?
