### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by kiruhasas22** [ShadowMario/FNF-PsychEngine#13857]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

when i opening this engine,i got crashed

---------------------------
Error
---------------------------
[lime.utils.Preloader] ERROR: There is no asset library with an ID of "videos"
---------------------------
ОК   
---------------------------

### Command Prompt/Terminal logs (if existing)

```bash
---------------------------
Error
---------------------------
[lime.utils.Preloader] ERROR: There is no asset library with an ID of "videos"
---------------------------
ОК   
---------------------------
```

### Are you modding a build from source or with Lua?

I am not modding

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
Be sure you're running the latest version (0.7.2h)

**Comment by kiruhasas22** [comment]
> Be sure you're running the latest version (0.7.2h)

Yea,i downloaded the latest version

**Comment by ShadowMario** [comment]
I have researched a bit and it's very possible that this is a broken installation (Haxe sometimes does that), try doing `lime test windows -clean` to clear your installation and re-compile it

Warning: You might lose files inside the export/ folder, so do a backup if you had anything inside it.

**Comment by kiruhasas22** [comment]
> I have researched a bit and it's very possible that this is a broken installation (Haxe sometimes does that), try doing `lime test windows -clean` to clear your installation and re-compile it
> 
> Warning: You might lose files inside the export/ folder, so do a backup if you had anything inside it.

I not using Source Code,i just download the latest build

**Comment by Dingussherry** [comment]
It didn't help
