### ISSUE TITLE
Error in Compiling

### ISSUE THREAD

**Issue by EvcazinDeveloper** [ShadowMario/FNF-PsychEngine#13863]
### Describe your problem here.

So basically, theres a big error while compiling my game.

`C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat should be declared with 'override' since it is inherited from superclass flixel.graphics.frames.FlxAtlasFrames
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat overrides parent class with different or incomplete type
C:/HaxeToolkit/haxe/lib/flixel/5,5,0/flixel/graphics/frames/FlxAtlasFrames.hx:457: characters 18-24 : ... Base field is defined here
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : ... Different number of function arguments
source/backend/Paths.hx:574: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)
source/objects/Character.hx:300: characters 87-101 : flxanimate.animate.FlxAnim has no field lastPlayedAnim
source/objects/Character.hx:331: characters 20-26 : flxanimate.animate.FlxAnim has no field resume`

Can anyone help me with this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't edit the build but i edited the FlxAnimate library to try to fix the first error.

**Comment by foxygood** [comment]
[](https://github.com/ShadowMario/FNhttps://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versionsF-PsychEngine/wiki/Libraries-versions)

**Comment by foxygood** [comment]
[Libraries versions](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)

**Comment by foxygood** [comment]
[Libraries versions](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)
try this
