### ISSUE TITLE
Character editor "Save character" button stops working after saving 1 character

### ISSUE THREAD

**Issue by AjTheFunky** [ShadowMario/FNF-PsychEngine#13860]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

After I save a single character, the save character button stops working and does not bring up the file explorer. I have to exit out of the character editor and reopen it.
I'm saving an alt version of the same character with a different spritesheet. The naming scheme I'm using for the spritesheets is "character", "character2", "character3", etc. if that helps.

### Are you modding a build from source or with Lua?

I am not modding

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I have not, this is base psych engine.

**Comment by ShadowMario** [comment]
Fixed (Redownload 0.7.2h)
