### ISSUE TITLE
Crash when pausing the game

### ISSUE THREAD

**Issue by ShadowSonic47** [ShadowMario/FNF-PsychEngine#13866]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

hello, i was using the pych engine version 0.7.2h and when i pause the game, i recieve ann error annd the game crashes, this is a screenshot of the error:
![Captura de pantalla 2023-12-27 085610](https://github.com/ShadowMario/FNF-PsychEngine/assets/154967812/0531fd82-fbdf-48c5-8270-24b581ba11fe)
and it's not a modified build, it's the original one
hope ou guys can fix that

### Are you modding a build from source or with Lua?

I am not modding

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i didn't edit anything

**Comment by cabfile** [comment]
a possible workaround is to try making a sound file with like 1 second of silence at /assets/shared/music/none.ogg as the error states

**Comment by ShadowMario** [comment]
Redownload 0.7.2h and try again, i re-uploaded the build with two extremely small bug fixes
