### ISSUE TITLE
Is there a way to get the text string for the song's timer??

### ISSUE THREAD

**Issue by Retr0wavy** [ShadowMario/FNF-PsychEngine#13862]
### What is your question?

So, I've been trying to set the string of a custom lua text that makes said text get the same property as the song's timer/timeTxt (y'know the one that appears in front of the time bar), but there doesn't seem to be any property that actually does that, or I just don't know its name, I'm not sure. But is there an actual way to do that???

Also a bit unrelated but Merry Christmas!!!

**Comment by Tattleamelia** [comment]
I believe `getProperty('timeTxt.text')` is what you're after.

**Comment by Retr0wavy** [comment]
It worked!! Thanks a bunch, I really appreciate it!!!
