### ISSUE TITLE
[0.7.1]Discord RPC problem during gameplay

### ISSUE THREAD

**Issue by scluxthefunkup** [ShadowMario/FNF-PsychEngine#13861]
### Describe your problem here.

I changed the icon and the text in developer app discord, but during gameplay the text changes to "Psych engine" and i don't know how to change it, it only happens during gameplay, help meeee
(Menus)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/138252386/c11d5a7b-4019-4b54-bd12-66f85f9d0aee)
(Gameplay) 
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/138252386/7b02a24d-e0f7-47f9-97ea-ca7fe8b50de2)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Discord.hx / only added the app id, large image key and large image text

**Comment by ShadowMario** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/8eab2624-ab97-49e7-888d-d145a6292f20)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/3eabd229-e97a-48d2-a481-2cd8710b8901)
Did you change these inside backend/Discord.hx? It's the only place in the whole engine where the icon asset and discord app ID are mentioned

**Comment by scluxthefunkup** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/138252386/ad4748b5-8fb0-4f46-ad07-be63617817e0)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/138252386/1c6347c5-6154-454e-ae52-ba56bd49897f)
I already changed them :(

**Comment by scluxthefunkup** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/138252386/67769b60-d1a2-4e65-b6fd-4bc7acb73f1e)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/138252386/c784e3d5-6bc8-45bf-9346-0e2836734bab)

LOL i closed by accident, i already changed them :(

**Comment by scluxthefunkup** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/138252386/3b2e1adb-99b8-45ed-a2ac-cab1496e3228)

I changed the "iconog" name to "icon" and now the original psych engine icon appears but i already changed the defaultID, idk what it's happening
