### ISSUE TITLE
???

### ISSUE THREAD

**Issue by 2JENO** [ShadowMario/FNF-PsychEngine#13873]
### Describe your bug here.

Suddenly it crashes at no time

### Command Prompt/Terminal logs (if existing)

```bash
Assertion failed: bytesToRead == bytesRead, file C:/HaxeToolkit/haxe/lib/hxdiscord_rpc/git/project/discord-rpc/src/connection_win.cpp, line 116
```

### Are you modding a build from source or with Lua?

Source

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i changed discord clientID to my app

**Comment by ZeitHeld** [comment]
Just had this exact issue as well
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/76132257/566d619d-60ad-40f8-b96d-342059ee52a5)
I opened discord while FNF ran in the bg (nothing moving though), opened an image, which opened in my browser (chrome) and then it gave me an error
though I did not change anything related to discord

**Comment by TheKAPtain313** [comment]
same

**Comment by 2JENO** [comment]
help please

**Comment by 2JENO** [comment]
not fixed help
