### ISSUE TITLE
playVideo lua code stops notes from moving even with Function_Stop and Function_Continue returns!

### ISSUE THREAD

**Issue by Loganthegamer12678** [ShadowMario/FNF-PsychEngine#13870]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/86275915/ba8cd51f-66cd-4f4e-864a-785302f6250d)

This is the same script I mentioned in the previous issue.
```
function onEvent(name, value1, value2)
	if name == 'playVideo' then
		startVideo(value1)
		return Function_Stop
	end
	return Function_Continue
end
```

Sure, the video works now, but I can't even control shit except for pausing. The song and vocals still play tho.

### Command Prompt/Terminal logs (if existing)

https://streamable.com/9oum0l

### Are you modding a build from source or with Lua?

Lua

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

N/A

**Comment by Loganthegamer12678** [comment]
Plus at rare times IT CRASHES whenever it loads...!

**Comment by frantastic24** [comment]
`Function_Stop` doesn't just make the game pause, I'm pretty sure videos are only intended for countdown and end of songs

**Comment by Loganthegamer12678** [comment]
> `Function_Stop` doesn't just make the game pause, I'm pretty sure videos are only intended for countdown and end of songs

So the point of having the video play mid-song and have you continue playing is pointless after 0.7.0?

**Comment by Loganthegamer12678** [comment]
Well this sucks..

**Comment by EvgenDev09** [comment]
It thinks that you're in a cutscene, so what I do is set `setProperty('inCutscene', false)` after playing the video:
`function onEvent(name, value1, value2)
	if name == 'playVideo' then
		startVideo(value1)
		setProperty('inCutscene', false)
		return Function_Stop
	end
	return Function_Continue
end`
