### ISSUE TITLE
I have this problem in psych engine 0.4.2, please i need help

### ISSUE THREAD

**Issue by BlackType20** [ShadowMario/FNF-PsychEngine#13877]
### Describe your problem here.

source/Main.hx:7: characters 8-24 : Type not found : debug.FPSCounter
source/Main.hx:19: characters 8-25 : Type not found : states.TitleState
source/Main.hx:51: characters 27-37 : Type not found : FPSCounter

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I haven't edited anything

**Comment by ShadowMario** [comment]
This version is not supported since 2022.
