### ISSUE TITLE
Update Texture Atlas Tutorial (please) !!

### ISSUE THREAD

**Issue by gomiigg** [ShadowMario/FNF-PsychEngine#13879]
### What needs to be documented?

(v0.7.2h)

The wiki still links to the old TextureAtlas library instead of the updated one. I followed the tutorial just in case it still works like that. The atlas *does* import correctly, but I can't seem to get the animations working. It's just looping all the animations in order.

**Comment by XTihX1** [comment]
Have you tried putting the name of the symbol? for example instead of 'idle', you will put 'anims/idle' 
![Screenshot_1](https://github.com/ShadowMario/FNF-PsychEngine/assets/95257883/14483588-8835-412a-a5f0-c87a236ca4fd)

**Comment by gomiigg** [comment]
Yeah. Still doesnt seem to work.

**Comment by XTihX1** [comment]
from what I tested, this type of problem only happens when you export the atlas by the wrong way

**Comment by gomiigg** [comment]
nvm i got it! working great
