### ISSUE TITLE
Freeplay And The Song Does Not Work, Don't say i have to reinstall bc i dont wanna start over

### ISSUE THREAD

**Issue by Orionkidgaming** [ShadowMario/FNF-PsychEngine#1387]
### Describe your bug here.

freeplay and the song is not working
i got the 2 videos recorded.

https://user-images.githubusercontent.com/95064898/143623464-cd2aa949-f371-4e67-92f2-4c54c1cf2b20.mp4

https://user-images.githubusercontent.com/95064898/143623475-3df71413-c09b-40b6-88a1-87fc5611970d.mp4

### Command Prompt/Terminal logs (if existing)

```bash
i dont think that would work
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no and also lua cant open lua files and idk where the source file is bc it dont exist.

**Comment by ShadowMario** [comment]
About Freeplay, it looks like you've set your Week wrong.
About the song itself, It's missing the Inst.ogg files from your song.
