### ISSUE TITLE
LET PEOPLE REMOVE DISCORDCLIENT

### ISSUE THREAD

**Issue by ZanderRivera** [ShadowMario/FNF-PsychEngine#13889]
### What feature do you want to get added on the **base** engine?

![Screenshot 2023-12-30 231037](https://github.com/ShadowMario/FNF-PsychEngine/assets/107231882/c26e8e1c-b46a-4f08-a6e4-757b231d9689)

Let people allow or not allow discord on their build if they're having an error like `include\backend/discordclient.h(11): fatal error c1083: cannot open include file: 'discord_rpc.h': no such file or directory` (referenced from issues #13881)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
Added in the latest commit of experimental 👍
