### ISSUE TITLE
Chart editor is broken

### ISSUE THREAD

**Issue by ElPro7777** [ShadowMario/FNF-PsychEngine#13887]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

The Chart editor is broken. i cant scroll correctly

https://github.com/ShadowMario/FNF-PsychEngine/assets/86174806/7abb92ae-8d5d-4cab-a78d-6f6ddf9791d4

### Are you modding a build from source or with Lua?

I am not modding

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I didint change anything. it started happening and idk what to do

**Comment by ElPro7777** [comment]
i cant make my mod because of this bug

**Comment by SpiritualGo78** [comment]
Go to the charting tab and check to see if you have autoscrolling disabled. Enable it so you can scroll to the next sections.

**Comment by ElPro7777** [comment]
> Go to the charting tab and check to see if you have autoscrolling disabled. Enable it so you can scroll to the next sections.

THX!!!! But. That Feature Needs to be removed. Its Buggy as Hell
