### ISSUE TITLE
wrong with .hx script

### ISSUE THREAD

**Issue by axolotl-mouka** [ShadowMario/FNF-PsychEngine#13886]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

Here is the codes
```
    hudBorderRed = new FlxBackdrop(null, 0x01).loadGraphic(Paths.image('ditherbg'));
    hudBorderRed.cameras = [game.camHUD];
    hudBorderRed.y = snapY(720 - 36);
    hudBorderRed2 = new FlxBackdrop(null, 0x01).loadGraphic(Paths.image('ditherbg'));
    hudBorderRed2.cameras = [game.camHUD];
```

It doesn't work in PE 0.7.2h but it work in PE0.7.1h
Is it related to SScript?

### Are you modding a build from source or with Lua?

Lua

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
Replace `0x01` with 1
