### ISSUE TITLE
Fatal error C1083

### ISSUE THREAD

**Issue by ZanderRivera** [ShadowMario/FNF-PsychEngine#13881]
### Describe your problem here.

![Screenshot 2023-12-29 232422](https://github.com/ShadowMario/FNF-PsychEngine/assets/107231882/8ca8bb91-3f4f-4aaa-a08a-87bafa9f8278)

I just want to know on what on earth to do with this.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No. This is a clean build.

**Comment by ZanderRivera** [comment]
@ShadowMario

**Comment by ZanderRivera** [comment]
I will disable discord-rpc for the moment until this is not resolved @ShadowMario. How? Don't ask.

**Comment by ShadowMario** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by ZanderRivera** [comment]
I want to close this as unexpected but since people can now remove discord I'll allow it to be closed as completed on your behalf because even the libraries didn't help my problem, so I accept the close.

**Comment by ZanderRivera** [comment]
I want to close this as unexpected but since people can now remove discord I'll allow it to be closed as completed on your behalf because even the libraries didn't help my problem, so I accept the close.
