### ISSUE TITLE
credits problem

### ISSUE THREAD

**Issue by axolotl-mouka** [ShadowMario/FNF-PsychEngine#13892]
### Describe your bug here.
I found one problem with credits menu
i put credits.txt on mods/data
it doesn't works in PE 0.7.2h but it can work in PE0.6.3
![case (1)](https://github.com/ShadowMario/FNF-PsychEngine/assets/134141822/3495f21e-3968-40c6-8523-8632fa0e20c6)
![case (2)](https://github.com/ShadowMario/FNF-PsychEngine/assets/134141822/a1c209e2-2be5-4a01-9f6f-fefa55804bec)

### Are you modding a build from source or with Lua?

Lua

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Credits only work in modpacks
