### ISSUE TITLE
Chart Editor Doesn't Show the charts

### ISSUE THREAD

**Issue by I-am-someone-sh** [ShadowMario/FNF-PsychEngine#13897]
### Describe your bug here.

Charts doesn't show after 2 sections, main and experimental branch has the same question.
version was 0.7.2h
![Screen Shot 2024-01-01 at 15 54 35](https://github.com/ShadowMario/FNF-PsychEngine/assets/134118442/3ac1f4be-9520-4df6-a0d5-3185cba6ac45)
![Screen Shot 2024-01-01 at 15 54 49](https://github.com/ShadowMario/FNF-PsychEngine/assets/134118442/5d916cb5-03bf-4b14-a391-306fce1606ab)

### Are you modding a build from source or with Lua?

I am not modding

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by JHAM25** [comment]
Desactiva (disable autoscroll)
![293611983-3ac1f4be-9520-4df6-a0d5-3185cba6ac45~2](https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/05c2ac6c-4e34-463c-8622-26c6a051c36d)
