### ISSUE TITLE
JUST FIX IT ALREADY

### ISSUE THREAD

**Issue by TheKAPtain313** [ShadowMario/FNF-PsychEngine#13890]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

COME ON MAN JUST FIX THE FREEPLAY AND STORYMODE NOT PLAYABLE BUG ALREADY I WANNA PLAY PYCHENGINE 
![Screenshot 2023-12-22 162334](https://github.com/ShadowMario/FNF-PsychEngine/assets/140554874/92301500-0335-4b37-bdd9-b6ae95b8ab13)

### Are you modding a build from source or with Lua?

Lua

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i added some hud and lua scripts to enhance my gameplay but thats abt it.

**Comment by XTihX1** [comment]
just remove the field "weekPlayableCharacter" from the week json file?
