### ISSUE TITLE
Variable Questions

### ISSUE THREAD

**Issue by Slush-o** [ShadowMario/FNF-PsychEngine#13899]
### What is your question?

What's the variables for the timer and other game objects, also how to you connect texts, i tried "setTextString('scoreTxt', songName.."test")" and "setTextString('scoreTxt', songName + "test")" and neither are working

**Comment by Slush-o** [comment]
also how can i edit the timeTxt text, i want to do "1:00/1:00" n shit like that

**Comment by JHAM25** [comment]
yo la hice algo asi:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/bcc6250f-8188-43fe-9e6c-feb503153bca)
codigo:

luaDebugMode = true
function onCreatePost()
addHaxeLibrary('FlxStringUtil', 'flixel.util')
end
function onUpdatePost()
	curTime = math.max(0, getPropertyFromClass('backend.Conductor', 'songPosition') - getPropertyFromClass('backend.ClientPrefs', 'data.noteOffset'))
	songCalc = curTime --(songLength - curTime);
	secondsTotal = math.floor(songCalc / 1000);
	--setProperty('scoreTxt.text', getProperty('timeTxt.text')..'|'..secondsTotal)
	runHaxeCode([[scoreTxt.text = FlxStringUtil.formatTime(]]..secondsTotal..[[, false) + ' | ' + FlxStringUtil.formatTime(]]..(songLength / 1000)..[[, false)]])
end
