### ISSUE TITLE
compiling issue for mac

### ISSUE THREAD

**Issue by caelio7** [ShadowMario/FNF-PsychEngine#139]
When I try to compile for mac this error pops up. 
`"_lua_typename", referenced from:
      linc::lua::_typename(lua_State*, int) in 61e53f39_linc_lua.o
      linc::lual::ltypename(lua_State*, int) in 61e53f39_linc_lua.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
I'm pretty sure I have everything installed, I have no clue what the fuck went wrong, help a man out.

**Comment by FuseIsHere813** [comment]
If i had a macbook, i would fix the issue.

**Comment by caelio7** [comment]
NVM I just needed to install the latest update!!
