### ISSUE TITLE
Error while running "limo test"

### ISSUE THREAD

**Issue by PiotrTheGamer** [ShadowMario/FNF-PsychEngine#13902]
### Describe your problem here.

When I try to run the command "limo test", the only response I get is -> Not_found

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited discord.hx and the project.xml file

**Comment by SrtHero278** [comment]
isnt it lime?

**Comment by ShadowMario** [comment]
lime*
