### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by b8mate** [ShadowMario/FNF-PsychEngine#13908]
### Describe your problem here.

I've been trying to look for an answer to this and it always comes to a dead end. How do I make the LoadingState(loading screen) work?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i only changed stuff in project.xml

**Comment by ShadowMario** [comment]
The loading screen implemented in Psych has no use in Desktop builds, it is specifically only meant to be used for downloading assets in HTML builds, it quite literally does nothing on Desktop.

**Comment by WolfyTail** [comment]
However, how can I activate the LoadingState? Idc if it's useless.
