### ISSUE TITLE
"Command 'Lime' not found, did you mean" Linux error

### ISSUE THREAD

**Issue by Stefan2008Git** [ShadowMario/FNF-PsychEngine#13903]
### Describe your problem here.

I installed everything correctly for Linux compiling and i got this error:
![Снимак екрана направљен дана 2024-01-02 19-03-45](https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/2380ab66-4a18-4190-90f5-8b8e94459439)
 Do i am missing something or?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just installed everything for compile

**Comment by AsterGTheFourth** [comment]
In Windows I got a similar thing, as I was trying to run simply `lime test windows` and not `haxelib run lime test windows`. So, whatever the variant for `haxelib run` is on Linux, you should probably add it before `lime test linux`.

**Comment by Stefan2008Git** [comment]
> In Windows I got a similar thing, as I was trying to run simply `lime test windows` and not `haxelib run lime test windows`. So, whatever the variant for `haxelib run` is on Linux, you should probably add it before `lime test linux`.

I tried with ``haxelib run lime test linux -64`` abd ut works, but that's kinda weird. On Windows, you can type with caps lock or without ``Lime``, but on Linux, that's kinda weird

**Comment by Stefan2008Git** [comment]
> In Windows I got a similar thing, as I was trying to run simply `lime test windows` and not `haxelib run lime test windows`. So, whatever the variant for `haxelib run` is on Linux, you should probably add it before `lime test linux`.
