### ISSUE TITLE
Getting Note Colours with Lua?

### ISSUE THREAD

**Issue by Tattleamelia** [ShadowMario/FNF-PsychEngine#13907]
### Describe your problem here.

Does anyone happen to know if and how I could get a Note's Colours with Lua and then convert the values to hex? Like, for instance `getProperty('notes', 0, 'rgbShader.r')` or something like that. I dunno what I would actually need to write in order to get that.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Lorekeeper49** [comment]
```lua
function rgbToHex(rgb)
	local hexadecimal = '0x'

	for key, value in pairs(rgb) do
		local hex = ''

		while(value > 0)do
			local index = math.fmod(value, 16) + 1
			value = math.floor(value / 16)
			hex = string.sub('0123456789ABCDEF', index, index) .. hex			
		end

		if(string.len(hex) == 0)then
			hex = '00'

		elseif(string.len(hex) == 1)then
			hex = '0' .. hex
		end

		hexadecimal = hexadecimal .. hex
	end

	return hexadecimal
end
```
found this code while I was searching for a similar problem, use this function for what you need

**Comment by Tattleamelia** [comment]
This only solves half of my problem, since I still need to know how to actually get a Note's colour to begin with. Still though, I appreciate the help!

**Comment by Tattleamelia** [comment]
Nevermind, I think I might have figured it out! Closing this for now.
