### ISSUE TITLE
Json error due to Note

### ISSUE THREAD

**Issue by Jamesx0YT** [ShadowMario/FNF-PsychEngine#13912]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

I wanted to make optimized ports in a mod but the json has problems playing it and this error appears:

### Command Prompt/Terminal logs (if existing)

```bash
objects/Note.hx (line 443)
states/PlayState.hx (line 2153)
flixel/group/FlxGroup.hx (line 769)
states/PlayState.hx (line 2147)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, edit nothing

**Comment by ShadowMario** [comment]
What version of the engine are you using? The lines aren't matching with your error.

**Comment by Jamesx0YT** [comment]
Oops, sorry, I forgot to use 0.7
But try to run with the json in the most recent version which is version 0.7.1h but it still shows this error
(now you can help me with this error but with 0.7.1h)
```
objects/Note.hx (line 464)
states/PlayState.hx (line 1764)
flixel/group/FlxGroup.hx (line 787)
states/PlayState.hx (line 1758)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

**Comment by Jamesx0YT** [comment]
> What version of the engine are you using? The lines aren't matching with your error.

Oops, sorry, I forgot to use 0.7
But try to run with the json in the most recent version which is version 0.7.1h but it still shows this error
(now you can help me with this error but with 0.7.1h)

```
objects/Note.hx (line 464)
states/PlayState.hx (line 1764)
flixel/group/FlxGroup.hx (line 787)
states/PlayState.hx (line 1758)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

**Comment by ShadowMario** [comment]
Did you edit the note's noteData or deleted a strum note? It seems to be trying to get properties from its parent strum note but can't.

**Comment by Jamesx0YT** [comment]
> Did you edit the note's noteData or deleted a strum note? It seems to be trying to get properties from its parent strum note but can't.

I think so, you can review the JSON DATA so you can see, because it detects it and everything, but when you play, that error appears
Here is the JSON DATA:
[https://pastebin.com/raw/03WDkYHw](url)

**Comment by Jamesx0YT** [comment]
I think I found the error:
I eliminated all the events that the JSON had there, it could be played, but it still detected in the game but it crashed due to having those events, thank you very much ShadowMario anyway.

Thanks ShadowMario
