### ISSUE TITLE
Question about the "WiggleEffect" Shader

### ISSUE THREAD

**Issue by StinkTheStinker** [ShadowMario/FNF-PsychEngine#13919]
### What is your question?

How do I even use it. I am confused

**Comment by ShadowMario** [comment]
You need to initialize this variable outside of any function: `var wiggleShit:WiggleEffect = new WiggleEffect();`

Here's an example of how you can apply it to an object (in this case, boyfriend):
```haxe
boyfriend.shader = wiggleShit.shader;
wiggleShit.effectType = FLAG;
wiggleShit.setValue(0);
wiggleShit.waveSpeed = 5;
wiggleShit.waveFrequency = 0.03;
wiggleShit.waveAmplitude = 0.03;
```

And lastly you will need to put this somewhere in update: `wiggleShit.update(elapsed);`

I gotta warn you though, applying this to sprites is not recommended, you should instead apply this shader to a camera or something.
`camHUD.setFilters([new ShaderFilter(wiggleShit.shader)]);`
