### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by Jamesx0YT** [ShadowMario/FNF-PsychEngine#13917]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

I tried to compile first to edit the Source code right now but I can't Compile because of this error
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/95061460/6d9873e5-09f3-4432-b9b5-fe8a7baf96c0)

### Command Prompt/Terminal logs (if existing)

```bash
source/backend/animation/PsychAnimationController.hx:6: characters 16-33 : Redefinition of variable followGlobalSpeed in subclass is not allowed. Previously declared at flixel.animation.FlxAnimationController

Only this error
```

### Are you modding a build from source or with Lua?

Source

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, edit nothing the source code

**Comment by ZanderRivera** [comment]
You may want to copy the whole code(use this)
package backend.animation;

import flixel.animation.FlxAnimationController;

class PsychAnimationController extends FlxAnimationController {
    public var followGlobalSpeed:Bool = true;

    public override function update(elapsed:Float):Void {
		if (_curAnim != null) {
            var speed:Float = timeScale;
            if (followGlobalSpeed) speed *= FlxG.animationTimeScale;
			_curAnim.update(elapsed * speed);
		}
		else if (_prerotated != null) {
			_prerotated.angle = _sprite.angle;
		}
	}
}

If it doesn't work, you may want to update the libraries(https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)
