### ISSUE TITLE
error using custom noteskin

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#13914]
### Describe your problem here.

so, i have this noteskin i made and i can't get it to work. idk whats the problem but the notes in the chart editor are invisible and when i try to play the game it crashes.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/98123933/7299ecb4-f382-4592-9fcd-e6b8044c4686)
and this is the crash report i get:
```
flixel/animation/FlxAnimationController.hx (line 739)
objects/Note.hx (line 420)
objects/Note.hx (line 398)
objects/Note.hx (line 370)
objects/Note.hx (line 146)
objects/Note.hx (line 234)
states/PlayState.hx (line 1344)
states/PlayState.hx (line 507)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

here's the png and xml of the noteskin idk whats the problem
[NOTE_assets-DontStarve.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/13834235/NOTE_assets-DontStarve.txt)
![NOTE_assets-DontStarve](https://github.com/ShadowMario/FNF-PsychEngine/assets/98123933/1b0a779c-30f6-484b-bb69-39b914770dca)
could someone help me get it to work? thanks in advance

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

not the build really just the mod folder (0.7.2h)

**Comment by gameygu-0213** [comment]
They work for me?
are you SURE its .xml and not .txt in your filename (make sure you check View > Show File Name Extensions)
are you SURE they both share the same start to the filename? "NOTE_assets-DontStarve"
