### ISSUE TITLE
HScript error

### ISSUE THREAD

**Issue by Charmanny** [ShadowMario/FNF-PsychEngine#13911]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

source/psychlua/HScript.hx:301: characters 9-13 : tea.SScript has no field kill
source/psychlua/HScript.hx:33: characters 7-15 : psychlua.HScript has no field doScript
is there any fix?
im useing 0.7.1h btw

### Are you modding a build from source or with Lua?

Source

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i did not

**Comment by ShadowMario** [comment]
Your SScript seems outdated, you might want to use the latest version instead considering you didn't change any code yet
