### ISSUE TITLE
ShadowMario Plz Reply

### ISSUE THREAD

**Issue by Orionkidgaming** [ShadowMario/FNF-PsychEngine#1392]
### What feature do you want to get added on the base engine?

The Inst Is Already There Rn, i got the image:
![Capture](https://user-images.githubusercontent.com/95064898/143657169-7333763b-d256-456f-ba5f-06294a70ebf8.PNG)

also if you about to say the voices is the problem i dont need it because the song dont have the voice to download, do you have the fix to it? and the week is this image:
![Capture2](https://user-images.githubusercontent.com/95064898/143657422-0624377f-04b1-4cbf-a83b-f7b938896124.PNG)

wait.. lemme show another image:
![Capture3](https://user-images.githubusercontent.com/95064898/143657444-ef99e5ff-c38d-4ce1-b0cc-1b80af0fe978.PNG)

can this be the problem, hope so.

**Comment by CrusherMods** [comment]
you put the inst in bopeebo, you put it in a custom folder in mods folder

**Comment by Orionkidgaming** [comment]
> you put the inst in bopeebo, you put it in a custom folder in mods folder

what custom folder, arent you talking about the text?

**Comment by CrusherMods** [comment]
> > you put the inst in bopeebo, you put it in a custom folder in mods folder
> 
> what custom folder, arent you talking about the text?

Go to the mods folder > songs folder then create a new folder with your custom song name and put the inst in that

**Comment by Orionkidgaming** [comment]
wait it works if i rename bopeebo into where does it fix the problem?
if so then thanks


> > > you put the inst in bopeebo, you put it in a custom folder in mods folder
> > 
> > 
> > what custom folder, arent you talking about the text?
> 
> Go to the mods folder > songs folder then create a new folder with your custom song name and put the inst in that

so renaming also works right?

**Comment by NotEpik** [comment]
> wait it works if i rename bopeebo into where does it fix the problem? if so then thanks
> 
> > > > you put the inst in bopeebo, you put it in a custom folder in mods folder
> > > 
> > > 
> > > what custom folder, arent you talking about the text?
> > 
> > 
> > Go to the mods folder > songs folder then create a new folder with your custom song name and put the inst in that
> 
> nvm

if you change "bopeebo" to "where" it still doesn't work just put the song folder with the name "where" in mods/songs
and put the JSON folder with the name "where" and inside with 3 difficult "where-easy", "where", "where-hard" in mods/data

**Comment by NotEpik** [comment]
bruh I'm having a headache and forgot to read the tag bruh I just post how to fix :/

**Comment by ShadowMario** [comment]
You are in a downloaded build, you have to put your inst in `mods/where/Inst.ogg`, not Bopeebo.

**Comment by Orionkidgaming** [comment]
> You are in a downloaded build, you have to put your inst in `mods/where/Inst.ogg`, not Bopeebo.

sounds great! i will try it!

**Comment by Orionkidgaming** [comment]
shadowmario it works!!! i will do my next one.
