### ISSUE TITLE
Lua Script not functioning

### ISSUE THREAD

**Issue by KillerAvecRage** [ShadowMario/FNF-PsychEngine#13924]
### Describe your problem here.

I am trying to load a song whenever a key is pressed (seven/eight, so debug keys), I took care of disabling the debug menu keys but it simply doesn't want to load the song I want it to load, here is the script (tested in my modified 0.6.3 build and release 0.7.1h build)

function onCreatePost() 
setProperty('boyfriend.x',1450)
setProperty('boyfriend.y',650)
end

function onCreate()
setProperty("debugKeysChart", null)
end

function onUpdate() 
if getPropertyFromClass('flixel.FlxG', 'keys.JustPressed.SEVEN') or getPropertyFromClass('flixel.FlxG', 'keys.JustPressed.EIGHT') then
loadSong('nosong1', 1)
end
end

There is an existant data AND song folder (with their files) EXACTLY named "nosong1", yet when I press 7, nothing happens, the original song continues to play

Any help with that? Thanks in advance

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I'm using a Psych Engine version translated in french, but I believe it doesn't matter in the problem

**Comment by frantastic24** [comment]
#13659

**Comment by KillerAvecRage** [comment]
The problem I'm having is that it doesn't open the song, I've just tried putting debugprints, one before the loadSong and one after, the print that is supposed to appear after the song is loaded doesn't show up

new script: 
function onCreatePost()
setProperty('boyfriend.x', 1450)
setProperty('boyfriend.y', 650)
end

function onCreate()
setProperty('debugKeysChart', null); setProperty('debugKeysCharacter', null);
end

function onUpdate()
if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') or getPropertyFromClass('flixel.FlxG', 'keys.justPressed.EIGHT') then
debugPrint('Trying to open song')
loadSong('nosong', 0)
debugPrint('Song should be loaded!')
end
end

function onDestroy()
setProperty('debugKeysChart', debug_1); setProperty('debugKeysCharacter', debug_2);
end

**Comment by KillerAvecRage** [comment]
Okay, I found what the problem was!

Since the song I loaded was on the hard difficulty, the game refused to load the song as it was on the normal difficulty, so I changed that and it works now.
