### ISSUE TITLE
RGB note shader option in Project.xml

### ISSUE THREAD

**Issue by Eric-R-Malice** [ShadowMario/FNF-PsychEngine#13929]
### What feature do you want to get added on the **base** engine?

The post title should explain itself - having a setting in Project.xml to disable the RGB note shader globally when compiling would be nice.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/6c963276-b336-471c-b853-e6ceeb4d709e)

**Comment by Eric-R-Malice** [comment]
> ![image](https://private-user-images.githubusercontent.com/44785097/294777497-6c963276-b336-471c-b853-e6ceeb4d709e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NTgxMzgsIm5iZiI6MTcwNDY1NzgzOCwicGF0aCI6Ii80NDc4NTA5Ny8yOTQ3Nzc0OTctNmM5NjMyNzYtYjMzNi00NzFjLWI4NTMtZTZjZWViNGQ3MDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDIwMDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZjA4MDBkZmYxYmJhMmYyNTZlZDBhNTk0MTE1ZTdhY2U1NjJiNjVlMmMxNGYxMzg0YjBlMWJlZmZmYTBiN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._5omyEWzuCyyMb0Ob5rae3efO-vIKBBnBL9EmWqSjEU)

I'd rather have a way to disable it globally than have to go through every song and manually disable it.
