### ISSUE TITLE
Compile error occurred

### ISSUE THREAD

**Issue by thefnfcoder** [ShadowMario/FNF-PsychEngine#13937]
### CallbackHandler not working
So... I did say about the tjson thing not working which now works but I have another problem with compiling this. I did everything from the installation libraries but installed the new versions instead. It works out fine until this appears and it is the only error that appears.

### Command Prompt/Terminal logs (if existing)

```bash
source/psychlua/CallbackHandler.hx:54: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
```

### Are you modding a build from source or with Lua?

Lua and Source

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Sonamaker1** [comment]
try this:
```
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
```
