### ISSUE TITLE
Switching audio output seemingly breaks the entire game

### ISSUE THREAD

**Issue by Eric-R-Malice** [ShadowMario/FNF-PsychEngine#13934]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

Post title should explain itself - if you switch audio outputs while playing Psych Engine, the game kinda just... breaks entirely?

I should explain real quick that this is not an issue I'm personally encountering, it's my friend's, but regardless it's something that should be addressed.

### Are you modding a build from source or with Lua?

I am not modding

### Which branch of the engine are you using?

Unstable (experimental)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Messed around with a few general things, but nothing audio-related.

**Comment by ShadowMario** [comment]
This is a known flixel issue, not Psych's fault.
