### ISSUE TITLE
how to add a mod to html of psych engine?

### ISSUE THREAD

**Issue by EnderNon** [ShadowMario/FNF-PsychEngine#13933]
### What is your question?

i built html psych engine but i don't see a mods folder. extracting someone's mod into the assets folder completely breaks it, what do i do?

**Comment by EnderNon** [comment]
also, just found this out, the html version can't seem to load the chart at all, no idea why. I enter a map and it fades to a black screen but gets stuck there.

**Comment by ShadowMario** [comment]
Html is not supported anymore as it was hindering the management in desktop builds

**Comment by EnderNon** [comment]
what was the last supported html version of psych engine?

**Comment by mcagabe19no2fa** [comment]
0.6.3
