### ISSUE TITLE
how to add mods to html version 0.6.3?

### ISSUE THREAD

**Issue by EnderNon** [ShadowMario/FNF-PsychEngine#13936]
### What is your question?

I'm trying to build html version using v0.6.3. Using the haxe library versions stated on wiki causes some fatal errors, so what versions were used during 6.3 version?

**Comment by Sonamaker1** [comment]
I don't know what versions were used exactly back then, but these are the commands I use currently to compile any source code mods that have been developed on 0.6.3 as of now: 
```
haxelib set flixel 4.11.0 
haxelib set lime 8.0.2 
haxelib run lime setup flixel 
haxelib run lime setup 
haxelib set openfl 9.2.1 
haxelib set flixel-tools 1.5.1 
haxelib set flixel-ui 2.4.0 
haxelib set flixel-addons 2.11.0 
haxelib set hxCodec 2.5.1 
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit 
haxelib git hscript https://github.com/HaxeFoundation/hscript 
haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex 
haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc 
haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp 
haxelib run lime rebuild hxcpp
haxelib set lime 8.0.2 
```

**Comment by EnderNon** [comment]
great, that works. do you know how to add a mod to html version as well?

**Comment by ShadowMario** [comment]
0.6.3 is not supported anymore

**Comment by EnderNon** [comment]
i know it's not supported, but as somoene else said it's literally the last version that supports html, and I'm trying to run a mod on a site.

**Comment by Vortex2Oblivion** [comment]
> i know it's not supported, but as somoene else said it's literally the last version that supports html, and I'm trying to run a mod on a site.

That's the neat part, you don't.
The mods folder doesn't work on html5
