### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by Trenton0** [ShadowMario/FNF-PsychEngine#1393]
### Describe your problem here.

Is there a way to add a character select screen in psych engine like how fnf minus has a character select screen? (It can be source or lua i just want to add a character select screen

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Just added a new difficulty (Insane)

**Comment by CrusherMods** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/discussions/445
