### ISSUE TITLE
"Alpha" not found in a constant alpha tween

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#13943]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/76132257/d7acc460-7fd9-4b53-bae8-d36fc471e20f)

basically, I have an alpha tween always going on (a menacing red thing on hud going in and out)
and when I tab out and wait a bit and then tab in again while this is active, it gives me this error

Oh, I should mention, these are two alpha tweens that always pass on on each other like this
```lua
if curBeat % 2 == 0 then --if here is 4 then other is uncommented
      doTweenAlpha('alarming', 'alarm', 1, crochet/1000, 'linear') --circin
else--if curBeat % 2 == 0 then
       doTweenAlpha('alarming', 'alarm', 0.5, crochet/1000, 'linear') --circout
end
```

### Are you modding a build from source or with Lua?

Lua

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

not via source

**Comment by JonnycatMeow** [comment]
i have this same issue too

**Comment by ZanderRivera** [comment]
Can we see the whole code? We can't help you if you don't upload the whole script.

**Comment by ZeitHeld** [comment]
```lua
local menacing = false
local yandere = false

function onCreatePost()
    menacing = false
    yandere = false
    dadColor = getProperty("dad.healthColorArray")
    father = rgbToHex(dadColor[1], dadColor[2], dadColor[3])

    makeLuaSprite('menace', '', -200, 0)
    makeGraphic('menace', 3000, 3000, father)
    addLuaSprite('menace')
    setProperty('menace.alpha', 0)
    setObjectOrder('menace',getObjectOrder('dadGroup')+1)

    makeLuaSprite('neeg', '', -200, 0)
    makeGraphic('neeg', 3000, 3000, '000000')
    addLuaSprite('neeg')
    setProperty('neeg.alpha', 0)
    --setObjectOrder('neeg',getObjectOrder('dadGroup')+1)

    makeLuaSprite('alarm', 'ycr', 0, 0)
    setObjectCamera('alarm', 'other')
    setProperty('alarm.alpha', 0)
    addLuaSprite('alarm')
end

function onStepHit()
    if curStep == 128 then
        cameraFlash('hud', 'FFFFFF', 0.5, false)
        --doTweenAlpha('menaceBye', 'menace', 0.2, 0.1, 'linear')
        yandere = true
    elseif curStep == 367 then
        yandere = false
    elseif curStep == 383 then
        menacing = true
        yandere = false
    elseif curStep == 384 then
        cameraFlash('hud', father, 1, false)
        --doTweenAlpha('menaceHi', 'menace', 0.2, 0.1, 'linear')
        menacing = true
    elseif curStep == 1152 then
        doTweenAlpha('neeghi', 'neeg', 1, 1, 'linear')
        doTweenAlpha('nohud', 'camHUD', 0, 0.5, 'linear')
        doTweenAlpha('noother', 'camOther', 0, 0.5, 'linear')
        cameraFlash('hud', 'FFFFFF', 0.5, false)
        doTweenAlpha('menaceBye', 'menace', 0, 0.5, 'linear')
    elseif curStep == 1184 then
        doTweenAlpha('neeghi', 'neeg', 0, 0.5, 'linear')
        doTweenAlpha('nohud', 'camHUD', 1, 0.5, 'linear')
        doTweenAlpha('noother', 'camOther', 1, 0.5, 'linear')
        cameraFlash('hud', 'FFFFFF', 0.5, false)
        yandere = true
    elseif curStep == 1304 then
        yandere = false
    elseif curStep == 1311 then
        yandere = true
    elseif curStep == 1439 then
        yandere = false
    elseif curStep == 1471 then
        yandere = true
    elseif curStep == 1951 then
        yandere = false
    elseif curStep == 1975 then
        cameraFlash('hud', 'FFFFFF', 0.5, false)
    elseif curStep == 1977 then
        cameraFlash('hud', 'FFFFFF', 0.5, false)
    elseif curStep == 1979 then
        cameraFlash('hud', 'FFFFFF', 0.5, false)
    elseif curStep == 1981 then
        cameraFlash('hud', 'FFFFFF', 0.5, false)
    elseif curStep == 1983 then
        cameraFlash('hud', 'FFFFFF', 0.5, false)
        --doTweenAlpha('menaceBye', 'menace', 0, 0.5, 'linear')
    elseif curStep == 2015 then
        cameraFlash('hud', '000000', 2, false)
    end
end

function rgbToHex(r, g, b)
    --%02x: 0 means replace " "s with "0"s, 2 is width, x means hex
	return string.format("%02x%02x%02x", 
		math.floor(r),
		math.floor(g),
		math.floor(b))
end


-----------------


function onBeatHit()
    if menacing then
        if curBeat % 4 == 0 then --if here is 4 then other is uncommented
            doTweenAlpha('menacing', 'menace', 0.25, crochet/1000, 'linear') --sinein
        elseif curBeat % 2 == 0 then
            doTweenAlpha('menacing', 'menace', 0.15, crochet/1000, 'linear') --sineout
        end
    else
        doTweenAlpha('menacing', 'menace', 0, 1, 'linear')
    end

    if yandere then
        if curBeat % 2 == 0 then --if here is 4 then other is uncommented
            doTweenAlpha('alarming', 'alarm', 1, crochet/1000, 'linear') --circin
        else--if curBeat % 2 == 0 then
            doTweenAlpha('alarming', 'alarm', 0.5, crochet/1000, 'linear') --circout
        end
    else
        doTweenAlpha('alarming', 'alarm', 0, 1, 'linear')
    end
end


function onTweenCompleted(tag)
if tag == "menaceBye" then
        menacing = false
    end
end
```

**Comment by ZanderRivera** [comment]
Here are a few suggestions to troubleshoot and resolve the issue:

1. **Check the 'menace' and 'neeg' Objects:**
   Ensure that the objects 'menace' and 'neeg' are created successfully and exist in your application. Double-check that these objects have the 'alpha' property. You can use debug prints or logging to check the properties of these objects during runtime.

2. **Debugging the Alpha Property Access:**
   Add some debug prints or logging statements to track the 'menace' and 'neeg' alpha values at various points in your code. This will help you identify when and where the alpha property is being accessed incorrectly.

    ```lua
    -- Example debug prints
    print("menace alpha: " .. getProperty('menace.alpha'))
    print("neeg alpha: " .. getProperty('neeg.alpha'))
    ```

3. **Ensure Objects Exist Before Tweens:**
   When using `doTweenAlpha`, make sure that the objects ('menace' and 'neeg') exist before attempting to tween their alpha values. Ensure that the objects are created in the `onCreatePost` function before any tweens are called.

4. **Check Object Orders:**
   Confirm that the objects 'menace' and 'neeg' are correctly ordered in relation to other objects. The line `setObjectOrder('menace', getObjectOrder('dadGroup')+1)` suggests that 'menace' should be placed above the objects in 'dadGroup'.

By addressing these points, you should be able to identify and fix the issue with accessing the 'alpha' property of the objects in your code. Additionally, consider providing more specific details about where in the code the error occurs for further assistance.

**Comment by ZeitHeld** [comment]
I know how to read the code. (I wrote it)
The functions work as expected normally. However there sometimes is an exception.

While it is active (most likely during the steps 128-1950 (This song is a cover of Fight or Flight from Sonic.exe btw)
It does not happen always, just sometimes randomly.

When I tab out of the game (which caused a few other issues on 0.7.2/h that weren't on 0.7.1 though), it says there is a missing alpha, despite the tween beeing more or less constant.
If I can somehow get it to work (to crash again), I will record a video of this

The only thing I could do, is to prevent it to tween from 0 to 0 again (`onBeatHit` else branch)

(Ain't no way, that he pulled up chatgpt for this :sob:)

**Comment by ZanderRivera** [comment]
I want to see the error personally. Can you find a way to send it to me somehow?

**Comment by ZanderRivera** [comment]
I'm not sure if it helps but can you just make it setProperty('alarm.visible', false) rather than setProperty('alarm.alpha', 0)? Just try it.

**Comment by ZeitHeld** [comment]
Could get a longer video record (obs is being a bit weird and idk what it did with the mp4)
https://www.mediafire.com/file/r2thn6ptyy0fwtj/2024-01-12_15-51-00.mp4/file
crash is at the end
Happened at about the step 1184 to 1311 I think
but only when tabbing out

Though, I discovered that for some odd reason, the sprite itself does not really appear. Which is strange-
Though, somehow it seems that there is an error with the yandere variable... which is really strange to me

----------

While trying to fix the issue, I just removed my suggested fix
> The only thing I could do, is to prevent it to tween from 0 to 0 again (`onBeatHit` else branch)
And that kinda fixed the issue

more specifically the line `if getProerty("alarm.alpha") ~= 0 then`
Which is a bit odd. Since even changing something about this with the song/game open and then removing or adding something to it, just closes the game without any error

I hope that is just haxe being stupid

**Comment by ZeitHeld** [comment]
Not recorded now, but during the similar time without this issue, it still happened after tabbing out for too long
Which is more confusing.
I do blame haxeflixel for it
