### ISSUE TITLE
How do I use the note texture thing in chart editor?

### ISSUE THREAD

**Issue by EddyEddyEd** [ShadowMario/FNF-PsychEngine#1394]
### What is your question?

the title is pretty self-explanatory isn't it?
I suppose u just need to put the name of the png but im not sure
its that I want to my song to have the pixel notes without having to chart it in any week 6 song
:)

**Comment by NotEpik** [comment]
![bandicam 2021-11-27 23-04-44-880](https://user-images.githubusercontent.com/88980162/143688516-16b03560-9702-4e12-889b-c041f50dac9c.jpg)

i guess cant do it

**Comment by NotEpik** [comment]
oh wait, it's about stage

if "isPixelStage" in the JSON file is true the note will become pixel so make it true with custom stage then

**Comment by THOBY555** [comment]
go to chartMenu there`s at the right `Song` Menu
![Desktop Screenshot 2021 11 28 - 20 27 19 08](https://user-images.githubusercontent.com/71563419/143779012-ae9db51d-3e76-49bf-aa50-3f4841cda805.png)
 pur ur texture on mods/images and it will work in my case i used a folder called notes to use it also a slpash texture i didnt use a folder for it lol

**Comment by EddyEddyEd** [comment]
NotEpik, thanks that really worked!
THOBY, what ur saying really work with I originally wanted but that seems really cool and im exited to test it one day. Thanks for the information

**Comment by EddyEddyEd** [comment]
![Desktop Screenshot 2021 11 30 - 16 36 24 68](https://user-images.githubusercontent.com/94937926/144115792-01497915-c3b4-4ca8-9a47-a04535a9de0b.png)
