### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by VIRUSnik00** [ShadowMario/FNF-PsychEngine#13947]
### Describe your problem here.

![2024-01-11](https://github.com/ShadowMario/FNF-PsychEngine/assets/156318515/ac650785-5ea1-47b6-8065-0af62764719c)
Its my frist nod, i need help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ZanderRivera** [comment]
From what I see in the error, There is a problem in the instrumental. You may need to change the Instrumental with a newer version of the song.
