### ISSUE TITLE
Title State Doesnt Works

### ISSUE THREAD

**Issue by DaricrahDev** [ShadowMario/FNF-PsychEngine#13948]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

Alright, i was working on a project and when i compiled the game for first time, the TitleState thing wasnt starting, the music wasnt even playing! And you will say, 'its an error from the music .ogg file', but it isnt, if i just use `FlxG.sound.playMusic(Paths.music('freakyMenu'), 0);` the music plays but the title stills not work. I tried to replace TitleState.hx code like... 5 times and it didnt work. What should i do?

### Are you modding a build from source or with Lua?

Source

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i just compiled for first time

**Comment by JHAM25** [comment]
I think it should be 1 and not 0. 
FlxG.sound.playMusic(Paths.music('freakyMenu'), 1);

**Comment by DaricrahDev** [comment]
> I think it should be 1 and not 0. FlxG.sound.playMusic(Paths.music('freakyMenu'), 1);

it still doesnt works, the problem is not the music, is the title state creds stuff

**Comment by ZanderRivera** [comment]
The problem is literally the music. Even if you insist, it will be the music that is broken. Re-download 'freakymenu' because it's saying that it's corrupted. To not make more problems, you should just re-download main(The whole source code) again because some of the .ogg's or even the other files may be corrupted. Just do It

**Comment by DaricrahDev** [comment]
> The problem is literally the music. Even if you insist, it will be the music that is broken. Re-download 'freakymenu' because it's saying that it's corrupted. To not make more problems, you should just re-download main(The whole source code) again because some of the .ogg's or even the other files may be corrupted. Just do It

ill try thanks
