### ISSUE TITLE
im sure what happened

### ISSUE THREAD

**Issue by ajejohn05** [ShadowMario/FNF-PsychEngine#13944]
### What needs to be documented?

![Screenshot (505)](https://github.com/ShadowMario/FNF-PsychEngine/assets/156159792/3dd181e0-5aea-4c33-9b05-202caad9af5f)
this is what happened when i tried to press freeplay and then it crashed

**Comment by thefnfcoder** [comment]
Was there any songs in the freeplay?

**Comment by ajejohn05** [comment]
> Was there any songs in the freeplay?

yeah i have a few mods installed

**Comment by thefnfcoder** [comment]
Probably it's a unexpected error

**Comment by ajejohn05** [comment]
> Probably it's a unexpected error

ohhh okay i see, im new to this kinda stuff so i have no idea what to do with this error
