### ISSUE TITLE
When I press END ROUND, it doesn't close.

### ISSUE THREAD

**Issue by Your-Local-LordXSimp** [ShadowMario/FNF-PsychEngine#13945]
### Describe your problem here.

Same as the title, here's the code.

function onCreate()
    makeLuaText('yes', 'START PLAYDATE', 900, -70, 430);
    setTextSize('yes', 45)
    setObjectCamera('yes','camOther')
    setTextFont('yes', 'ZONE.ttf')
    setTextColor('yes', 'FF190C')
    addLuaText('yes', true)

    makeLuaText('no', 'END ROUND', 900, 540, 430);
    setTextSize('no', 45)
    setObjectCamera('no','camOther')
    setTextFont('no', 'ZONE.ttf')
    setTextColor('no', 'FF190C')
    addLuaText('no', true)

    setPropertyFromClass('flixel.FlxG', 'mouse.visible', true);
end

local allowCountdown = false;
function onStartCountdown()
    if not allowCountdown then
        allowCountdown = true; 
        return Function_Stop;
    end    
    return Function_Continue;
end

function onUpdate(elapsed)
    if mouseClicked('left') then
        doTweenAlpha('yesA', 'yes', 0, 0.5, 'linear')
        doTweenAlpha('noA', 'no', 0, 0.5, 'linear')
        playSound('select', 1)
        startCountdown()
    end
    if mouseClicked('right') then
        os.exit();
    end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Choice menu before song starts and loading screens.

**Comment by ZanderRivera** [comment]
It seems like your Lua script is missing the necessary code to handle the "END ROUND" functionality. In the provided code snippet, there's no indication of what should happen when the 'no' LuaText object is clicked. To make the script exit when the "END ROUND" text is clicked, add this(or just copy) on the onUpdate function as follows: 
`function onUpdate(elapsed)
    if mouseClicked('left') then
        doTweenAlpha('yesA', 'yes', 0, 0.5, 'linear')
        doTweenAlpha('noA', 'no', 0, 0.5, 'linear')
        playSound('select', 1)
        startCountdown()
    end
    if mouseClicked('right') then
        os.exit();
    end

    -- Check for 'no' LuaText click
    if mouseClicked('no') then
        os.exit();  -- or any other code to handle the end of the round
    end
end
`
This assumes that you have a function or code to handle the cleanup or actions needed when the round ends.

**Comment by Your-Local-LordXSimp** [comment]
Thanks, I'll try it. :)

**Comment by Your-Local-LordXSimp** [comment]
END ROUND works fine, but now when I click START PLAYDATE, it closes the game as well, it plays the sound though. I use Sublime Text for coding, and for some reason it counts "else" and "else if" as errors, so the last "end" to close the function ends up as an error.

**Comment by ZanderRivera** [comment]
`function onUpdate(elapsed)
    if mouseClicked('left') or isMouseOver('yes') then
        doTweenAlpha('yesA', 'yes', 0, 0.5, 'linear')
        doTweenAlpha('noA', 'no', 0, 0.5, 'linear')
        playSound('select', 1)
        startCountdown()
    -- Check for 'no' LuaText click
    elseif mouseClicked('right') or  isMouseOver('no') then
        os.exit();
    end
end
`

If Sublime Text continues to flag errors, double-check the indentation and ensure that there are no missing end statements. If the issue still persists, it might be related to the Lua syntax highlighting settings in Sublime Text.

**Comment by Your-Local-LordXSimp** [comment]
Alright.
