### ISSUE TITLE
My week doesn't open in story mode but yes in free play

### ISSUE THREAD

**Issue by Foxy-621** [ShadowMario/FNF-PsychEngine#13955]
### I don't know what happend, the song just doesn't open in story mode.

https://github.com/ShadowMario/FNF-PsychEngine/assets/87053015/706cc029-b5bf-4f22-94f9-49859e49262d

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i did'nt manipulate the engine

**Comment by ZanderRivera** [comment]
The most rare case of it is that the mod you may have downloaded the mod corrupted. You may just need to re-download the mod again

**Comment by gameygu-0213** [comment]
its not obvious from here but if the above solution doesnt work, it might be trying to load a non-existent dialogue or cutscene
check the data folder of the song for a script.lua file and see if anything mentions isStoryMode or similarly.
