### ISSUE TITLE
Save chart/event/character issue

### ISSUE THREAD

**Issue by CyberProd235** [ShadowMario/FNF-PsychEngine#1395]
### Describe your bug here.

It works perfectly, until i save ANYTHING, when i do, the game immediately crashes, please help me fix this, as I just lost a 5-minute long song chart due to this issue.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
Looks like a problem that isn't related to the Engine, most possibly your computer lacks permission for saving files or something.

**Comment by CyberProd235** [comment]
ah, turns out i needed to restart my computer for some reason
