### ISSUE TITLE
Ourple guy v3 bug?

### ISSUE THREAD

**Issue by dying-parrot64** [ShadowMario/FNF-PsychEngine#13957]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

I'm trying to play the mod but every song has no music and I'm confused I could be missing something but i don't know what to do looking it up has no results I've tried to reinstall the mod and its the same could be where I'm getting it from here is where:https://ourpleguy.neocities.org
please tell me what I'm doing wrong

### Are you modding a build from source or with Lua?

I am not modding I think?

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by gameygu-0213** [comment]
im not part of the time but im pretty sure that
A. this doesn't go here as its not an official build of vanilla psych and you arent modding psych either
B. have you tried pressing the 0 key on your keyboard (effectively acts as mute/unmute)
C. if none of these solve your issue its something with your computer probably
(iif this sounds rude, sorry im not trying to be)

**Comment by dying-parrot64** [comment]
all good its not the 0 key cus the game had audio and the cutscene had misic but as soon as the first note appeared the music just stopped
