### ISSUE TITLE
my game keeps crashing when i die

### ISSUE THREAD

**Issue by jack-dutchie** [ShadowMario/FNF-PsychEngine#13959]
### Describe your problem here.

everytime i die in my mod i die but after a few seconds it will crash

https://github.com/ShadowMario/FNF-PsychEngine/assets/141778999/696831ef-344a-4c8c-9fba-76c9a480309e

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ZanderRivera** [comment]
Did you adjust something in the code? The 'You are dead bro' twitches with 'curSong' in the title, so in my case the code in the mod may be adjusted or corrupted(almost likely if you didn't adjust anything in the code)

**Comment by jack-dutchie** [comment]
> Did you adjust something in the code? The 'You are dead bro' twitches with 'curSong' in the title, so in my case the code in the mod may be adjusted or corrupted(almost likely if you didn't adjust anything in the code)

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/141778999/810a9861-5bb7-45fb-8abc-e3bd1df327eb)
 it says this but its dutch but a dutch friend of mine says: means its trying too load something it cant find

**Comment by gameygu-0213** [comment]
quick question does your characer's XML (in the same place as the image) have a bunch of "instance 1"'s in it?
it might just be that (although that doesn't usually crash it as far as im aware unless its a missing image problem and even then psych wouldnt crash like that)
wouldit also be possible to get access to the character's .json file in "(insert mod folder you're using here)/characters/(insert character name here)"?
