### ISSUE TITLE
text question (lua)

### ISSUE THREAD

**Issue by Slush-o** [ShadowMario/FNF-PsychEngine#13951]
### What is your question?

how do you make a text disappear after a player note is hit? also, how do you make a text different depending on the accuracy of the player pressing a note?

**Comment by ZanderRivera** [comment]
(This will be different if you are not in the main version(0.7.2h)
If it's on lua:

function onUpdate(elapsed)
	-- start of "update", some variables weren't updated yet
	-- key can be: 0 - left, 1 - down, 2 - up, 3 - right
        if 'keyPressed' == (the key you want to be pressed.) then
                //Choice 1
                setProperty('TheTextVariable.alpha', 0)
                //Choice 2
                setProperty('TheTextVariable.visible', false)
        end
end

If it's on haxe: 
function update(elapsed)
	-- start of "update", some variables weren't updated yet
	-- key can be: 0 - left, 1 - down, 2 - up, 3 - right
        if ('keyPressed' == (the key you want to be pressed.))
                //Choice 1
                TheTextVariable.alpha = 0;
                //Choice 2
                TheTextVariable.visible = false;
        end
end

I will do some more research if you are modding on a different version.

**Comment by Slush-o** [comment]
im using psych 0.7.2h (i think), i need it so when you press a note perfectly a text says "Sick!" then disappears before the next note hit
