### ISSUE TITLE
audio erpr

### ISSUE THREAD

**Issue by TimRedGamerYT** [ShadowMario/FNF-PsychEngine#13950]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

i was tryna load dialogue and it didnt work, and its not the script because it works in other mods.

### Command Prompt/Terminal logs (if existing)

```bash
openfl/media/Sound.hx (line 407)
backend/Paths.hx (line 429)
backend/Paths.hx (line 190)
objects/TypedAlphabet.hx (line 39)
flixel/group/FlxGroup.hx (line 144)
flixel/group/FlxSpriteGroup.hx (line 209)
cutscenes/DialogueBoxPsych.hx (line 301)
flixel/group/FlxGroup.hx (line 144)
flixel/addons/ui/FlxUIState.hx (line 212)
backend/MusicBeatState.hx (line 81)
states/PlayState.hx (line 1649)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Error loading sound from file: ./assets/shared/sounds/gf.ogg
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua and Source

### Which branch of the engine are you using?

Latest (main)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

All i added was a sound file named gf in mods>packname>sounds (which was in ogg format.)

**Comment by ZanderRivera** [comment]
The gf.ogg file may be corrupted(literally referenced from the error). You may need to recreate it(if you made the ogg) or re-download it.
