### ISSUE TITLE
0.6.3 Doesn't compile

### ISSUE THREAD

**Issue by WolfiyDaCat** [ShadowMario/FNF-PsychEngine#13952]
### Describe your bug here.

Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself.

C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/opengl/GL.hx:2638: characters 28-34 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:403: characters 28-34 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/RenderContextType.hx:6: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/PixelFormat.hx:6: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/graphics/ImageDataUtil.hx:1751: characters 28-34 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/LogLevel.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/system/System.hx:817: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/net/curl/CURLCode.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/net/curl/CURLMultiCode.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/net/HTTPRequestMethod.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoFilter.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/AssetType.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/ui/KeyCode.hx:6: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoAntialias.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoHintMetrics.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoHintStyle.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoOperator.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoExtend.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/ui/GamepadAxis.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/ui/GamepadButton.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeWindow.hx:668: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeWindow.hx:685: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoFormat.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/ui/MouseButton.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:636: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:657: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:679: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:707: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:741: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:773: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:806: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:829: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:859: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:888: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:923: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:955: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/discord_rpc/1,0,0/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Int16Array.hx:151: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Int16Array.hx:158: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Float64Array.hx:151: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Float64Array.hx:158: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Int8Array.hx:151: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Int8Array.hx:158: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/UInt8ClampedArray.hx:161: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/UInt8ClampedArray.hx:168: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoSubpixelOrder.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/text/harfbuzz/HBBufferClusterLevel.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/text/harfbuzz/HBDirection.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/text/harfbuzz/HBScript.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/text/harfbuzz/HBBufferContentType.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoStatus.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/ui/ScanCode.hx:7: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoFillRule.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoLineCap.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoLineJoin.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoContent.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/media/AudioContextType.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/net/curl/CURLMultiOption.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/net/curl/CURLInfo.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/net/curl/CURLOption.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/net/curl/CURLVersion.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/UInt16Array.hx:151: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/UInt16Array.hx:158: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/UInt8Array.hx:152: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/UInt8Array.hx:159: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/UInt32Array.hx:151: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/UInt32Array.hx:158: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Int32Array.hx:151: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Int32Array.hx:158: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Float32Array.hx:153: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Float32Array.hx:157: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Float32Array.hx:164: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:423: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:437: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:453: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:466: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:475: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:550: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:566: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:582: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:595: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:610: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:623: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:636: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:653: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:670: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:683: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:696: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:709: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:723: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:736: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:749: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:765: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:781: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:794: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:807: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:823: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:840: characters 2-10 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
source/PlayState.hx:1497: characters 26-37 : Class<flixel.animation.FlxAnimationController> has no field globalSpeed
source/PlayState.hx:1498: characters 49-60 : Class<flixel.animation.FlxAnimationController> has no field globalSpeed
source/PlayState.hx:1628: characters 13-23 : Type not found : MP4Handler
source/PlayState.hx:4991: characters 26-37 : Class<flixel.animation.FlxAnimationController> has no field globalSpeed
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/system/System.hx:817: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/opengl/GL.hx:2638: characters 28-34 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:403: characters 28-34 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/PixelFormat.hx:6: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/graphics/ImageDataUtil.hx:1751: characters 28-34 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/net/curl/CURLCode.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/net/curl/CURLMultiCode.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/net/HTTPRequestMethod.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/RenderContextType.hx:6: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/LogLevel.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoFilter.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/AssetType.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/ui/KeyCode.hx:6: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/flixel/5,5,0/flixel/graphics/FlxGraphic.hx:15: characters 8-32 : Type not found : openfl.display.Tilesheet
C:/HaxeToolkit/haxe/lib/flixel/5,5,0/flixel/graphics/tile/FlxDrawBaseItem.hx:9: characters 8-32 : Type not found : openfl.display.Tilesheet
C:/HaxeToolkit/haxe/lib/flixel/5,5,0/flixel/graphics/tile/FlxDrawTilesItem.hx:10: characters 8-32 : Type not found : openfl.display.Tilesheet
source/Paths.hx:24: characters 8-25 : You cannot access the flash package while in a macro (for flash.media.Sound)
C:\Users\asus\Desktop\Friendship-Insanity-main\source\import.hx:1: characters 8-13 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/media/AudioSource.hx:138: characters 53-100 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/media/Sound.hx:23: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/utils/Assets.hx:9: characters 8-26 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/text/_internal/TextEngine.hx:9: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/display/_internal/CairoTextField.hx:3: characters 8-40 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/display/_internal/CairoGraphics.hx:6: characters 8-36 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/filters/BitmapFilter.hx:6: characters 8-44 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/display/BitmapData.hx:14: characters 8-35 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/desktop/Icon.hx:4: characters 8-33 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/filesystem/File.hx:6: characters 8-27 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/events/InvokeEvent.hx:5: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/display/Application.hx:15: characters 8-33 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/utils/_internal/Lib.hx:6: characters 8-34 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/display/DisplayObject.hx:6: characters 8-34 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced her

### Are you modding a build from source or with Lua?

Source

### Which branch of the engine are you using?

Unstable (experimental)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't

**Comment by ZanderRivera** [comment]
You may want to change the lime, openfl and the flixel libraries because 0.6.3 isn't compatible with the latest libraries. 
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by WolfiyDaCat** [comment]
to which libraries

**Comment by ZanderRivera** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/12778

**Comment by WolfiyDaCat** [comment]
source/PlayState.hx:1497: characters 26-37 : Class<flixel.animation.FlxAnimationController> has no field globalSpeed
source/PlayState.hx:1498: characters 49-60 : Class<flixel.animation.FlxAnimationController> has no field globalSpeed
source/PlayState.hx:1628: characters 13-23 : Type not found : MP4Handler
source/PlayState.hx:4991: characters 26-37 : Class<flixel.animation.FlxAnimationController> has no field globalSpeed

**Comment by ZanderRivera** [comment]
This took me just now to realize that I can compare the latest revisions of the libraries in the wiki. This is what you need to use for 0.6.3.

haxelib install hxCodec 2.6.1
haxelib set hxCodec 2.6.1
haxelib install flixel 5.2.2
haxelib set flixel 5.2.2

**Comment by KELOTOMU** [comment]
Use Haxe 4.2.5 and set your openfl version to 9.2.1

**Comment by ShadowMario** [comment]
0.6.3 is not supported anymore
