### ISSUE TITLE
It doesn't work properly

### ISSUE THREAD

**Issue by Dingussherry** [ShadowMario/FNF-PsychEngine#13963]
### Describe your problem here.

If I try to run the Source code via cmd, it says [Lime.utils:Preloader] ERROR: there is no asset library with an ID of "videos"

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by thegreatskep** [comment]
im pretty sure youve gotta load it a certain way so it knows the folder exists (like for example opening the folder in file explorer and clicking on it, or creating a shortcut on the taskbar or start menu and clicking that)
