### ISSUE TITLE
Shader causes my game to crash at random moments

### ISSUE THREAD

**Issue by EpicMawerDiff** [ShadowMario/FNF-PsychEngine#13968]
### Describe your problem here.

I recently made a shader event that makes a glitchy-noise effect onto GF. But I keep crashing at random moments when the shader is active...

Event Script:

function onEvent(name)

   if name == 'Shader-GFChar' then
        initLuaShader('GFGlitch')
        setSpriteShader('gf', 'GFGlitch')
   end
end

function onUpdate()
        runHaxeCode([[
            game.createRuntimeShader('GFGlitch').setFloat('iTime', ]] .. os.clock() .. [[);
        ]])
end

Shader Itself:

#pragma header
vec2 uv = openfl_TextureCoordv.xy;
vec2 fragCoord = openfl_TextureCoordv * openfl_TextureSize;
vec2 iResolution = openfl_TextureSize;
uniform float iTime;
#define iChannel0 bitmap
#define texture flixel_texture2D
#define fragColor gl_FragColor

float rand(vec2 co){
    return fract(sin(dot(co.xy, vec2(1.9898,78.233))) * 43758.5453);
}

void main(void) {
    vec2 uv = fragCoord/iResolution;
    vec4 col = texture(iChannel0, uv);

    // Add moving glitch effect to RGB channels
    float glitchAmount = 0.001;
    float speed = 7.0;  // Adjust speed as needed
    float timeOffset = iTime * speed;
    float glitch = rand(uv + vec2(sin(timeOffset), cos(timeOffset))) * glitchAmount;

    col.r = texture(iChannel0, vec2(uv.x + glitch, uv.y)).r;
    col.g = texture(iChannel0, vec2(uv.x + glitch * 2.0, uv.y)).g;
    col.b = texture(iChannel0, vec2(uv.x + glitch * 3.0, uv.y)).b;

    // Add particle-like effects to full opacity pixels
    float particleDensity = 0.07;
    float particleSize = 0.1;
    float particleSpeed = 10.0;
    float particleIntensity = 0.5;

    float particleOffset = rand(uv) * particleDensity;
    float particlePhase = timeOffset * particleSpeed;
    float particle = rand(uv + vec2(sin(particlePhase), cos(particlePhase))) * particleIntensity;

    // Check if the current pixel has full opacity before applying the particle effect
    if (col.a == 1.0) {
        col.rgb += particle * texture(iChannel0, uv + vec2(particleOffset, particleOffset)).rgb;
    }

    fragColor = col;
}

It may have something to do with high FPS or the fact that I used too much shaders inside my song, but since I've made the event it has been crashing. It's okay with anyone can't help me

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I haven't

**Comment by JHAM25** [comment]
Y el codigo tampoco me funcionaba lo edite haci:
function onEvent(name)
if name == 'Shader-GFChar' then
initLuaShader('GFGlitch')
setSpriteShader('gf', 'GFGlitch')
setProperty('gf.useFramePixels', true)
end
end

function onUpdate()
setShaderFloat('gf', 'iTime', os.clock())
end

**Comment by EpicMawerDiff** [comment]
Turns out that the FPS was the issue, thanks anyway
