### ISSUE TITLE
lua question

### ISSUE THREAD

**Issue by Slush-o** [ShadowMario/FNF-PsychEngine#13961]
### Describe your problem here.

is there a way to squash and stretch notes, or scale notes?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JHAM25** [comment]
Cuando precionas una nota aumenta la escala

https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/0f1b8840-59d4-48a0-ae8e-eb9d6d5e761a
Codigo:


  luaDebugMode = true
function goodNoteHit(id, direction, noteType, isSustainNote)
    ------X
 setPropertyFromGroup('strumLineNotes', 2, 'scale.x',getPropertyFromGroup('strumLineNotes', 2, 'scale.x') + 0.1)
    ------Y
     setPropertyFromGroup('strumLineNotes', 2, 'scale.y',getPropertyFromGroup('strumLineNotes', 2, 'scale.y') + 0.1)
end

**Comment by Slush-o** [comment]
also, can you help me with a modchart with that script were on beat it scales up?

**Comment by JHAM25** [comment]
algo así?
Uploading 2024-01-14 21-13-31.mp4…

**Comment by JHAM25** [comment]
algo así?

https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/9727e93b-d382-417a-935f-ff1f91f33658

**Comment by Slush-o** [comment]
what are all the variables and functions / tweens for notes ?

**Comment by JHAM25** [comment]
Creo que las variables serian:
offsetX,offsetY,angle,flipX,flipY,x,y,alpha,scale.x,scale.y

y los tween:
noteTweenAlpha('aaaa1', 1, 0.5, 5, 'linear')
noteTweenAngle('aaaa2', 1, 180, 5, 'linear')
noteTweenDirection('aaaa3', 1, 180, 5, 'linear')
noteTweenY('aaaa4', 1, 20, 5, 'linear')
noteTweenX('aaaa5', 1, 500, 5, 'linear')

**Comment by Slush-o** [comment]
thank you bro
