### ISSUE TITLE
Note skins override note type.

### ISSUE THREAD

**Issue by SmashingGoomba** [ShadowMario/FNF-PsychEngine#1397]
### Describe your bug here.

NOTE: unsure if people have already discussed this issue.

The chart editor in the engine has a texture feature where you can add in a skin for your notes for a song. This is great, but the problem is if I added a note to the chart with the "Hurt Note" type or a note type I made similar to it, it will end up looking glitched.

I think the issue is that the skin is somehow overriding the note type. Hopefully this gets fixed.
![image](https://user-images.githubusercontent.com/69328615/143664309-3a1c6986-3a8c-4e07-89c5-93153e5f1578.png)

Before and After if you want more clarification:
![image](https://user-images.githubusercontent.com/69328615/143664369-308c9e02-15cb-4321-8951-ad5084876639.png)
![image](https://user-images.githubusercontent.com/69328615/143664376-db85863b-6173-4ed2-8f2a-9ab3b3ff7736.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Adding a new note type, making a note texture. This still applies to the Hurt Note type, though.

**Comment by SrtHero278** [comment]
Hurt notes change along with the Note textures so if you want to fix the hurt notes, Get the hurt note assets you want to use and name it `HURT` infront of your note texture name. So if your texture was called `EpicNotesWoah`, then your hurt note assets' name would look like
`HURTEpicNotesWoah`.

**Comment by SmashingGoomba** [comment]
> Hurt notes change along with the Note textures so if you want to fix the hurt notes, Get the hurt note assets you want to use and name it `HURT` infront of your note texture name. So if your texture was called `EpicNotesWoah`, then your hurt note assets' name would look like `HURTEpicNotesWoah`.

I'll see if that works. If it does, I'll close the issue.
