### ISSUE TITLE
this keeps happening

### ISSUE THREAD

**Issue by StellR06** [ShadowMario/FNF-PsychEngine#13972]
### Describe your bug here.

Everytime i try to load a song or even the note color options i get this error. I have no idea what im suppose to do to fix it so some help would be nice

options/NotesSubState.hx (line 630)
options/NotesSubState.hx (line 143)
options/OptionsState.hx (line 17)
options/OptionsState.hx (line 97)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I didnt modify anything, this is from a fresh install

**Comment by BernardoGP4504** [comment]
You apparently have selected an noteskin option that doesn't exist

**Comment by StellR06** [comment]
Like I said, this is from a fresh installation with no mods installed.

**Comment by StellR06** [comment]
for some reason this is only happening with a version that is before 0.7

**Comment by BernardoGP4504** [comment]
> for some reason this is only happening with a version that is before 0.7
Probably your download got corrupted, considering it's failing to load the note assets

**Comment by StellR06** [comment]
i tried the github download and the game banana download and the problem keeps persisting

**Comment by CheckMace** [comment]
I HAVE THE SAME PROBLEM did u find a fix for it
