### ISSUE TITLE
discord_rpc doesn't works

### ISSUE THREAD

**Issue by WolfiyDaCat** [ShadowMario/FNF-PsychEngine#13981]
### Describe your bug here.

source/Discord.hx:4: characters 8-30 : Type not found : discord_rpc.DiscordRpc
source/Discord.hx:39: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:81: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:19: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:29: characters 4-14 : Type not found : DiscordRpc
source/Discord.hx:34: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:44: characters 3-13 : Type not found : DiscordRpc

### Command Prompt/Terminal logs (if existing)

```bash
source/Discord.hx:4: characters 8-30 : Type not found : discord_rpc.DiscordRpc
source/Discord.hx:39: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:81: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:19: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:29: characters 4-14 : Type not found : DiscordRpc
source/Discord.hx:34: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:44: characters 3-13 : Type not found : DiscordRpc
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't

**Comment by 2JENO** [comment]
And this only happens when you edit the build.
