### ISSUE TITLE
Null Object Reference when installing mods

### ISSUE THREAD

**Issue by Xemo96Altyn** [ShadowMario/FNF-PsychEngine#13989]
### Describe your bug here.

new version of psychengine doesn't work with most part of mods. i tried this ones:
1. https://gamebanana.com/mods/437198
2. https://gamebanana.com/mods/490658
3. https://gamebanana.com/mods/487327

1 and 2 gives Null Object Reference in every menu in the game, the third one works fine (only in freeplay)
i searched for something similar here and in discord but it seems nobody solved it and nobody reported it here

### Command Prompt/Terminal logs (if existing)

```bash
in story mode:
states/StoryMenuState.hx (line 439)
states/StoryMenuState.hx (line 427)
states/StoryMenuState.hx (line 203)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

in freeplay:
states/FreeplayState.hx (line 72)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i didnt edit anything, i just downloaded mods from site and put them in mods folder

**Comment by XTihX1** [comment]
i tested all the three mods on psych 0.7.3, none erros. try turning on/off the mods on the mods menu

**Comment by Xemo96Altyn** [comment]
> try turning on/off the mods on the mods menu

now everything is working, but i really cant understand what was the problem, as i can remember i tried it already earlier and nothing
