### ISSUE TITLE
Crashing game about Pause menu music 

### ISSUE THREAD

**Issue by Eric-Fintanayi** [ShadowMario/FNF-PsychEngine#13986]
### Describe your bug here.

when I turn on a song (no matter what), the game crashes, as shown below. The funny thing is that I don’t have and never had such audio, I even deleted all my mods. I don't understand where Psych engine got the audio from the Fnf vs Impostor mod
![Снимок экрана 2024-01-17 083735](https://github.com/ShadowMario/FNF-PsychEngine/assets/154327109/3a9180ba-c36d-4558-84d6-3641c00d77e8)

![Снимок экрана 2024-01-17 083735](https://github.com/ShadowMario/FNF-PsychEngine/assets/154327109/ba4d725d-88aa-4939-8a26-ab4eb3c3f81f)
IT DOESN’T MATTER, I ALREADY FIXED EVERYTHING SO YOU DON’T NEED TO HELP ME, I JUST GOED TO THE PSYCH ENGINE SETTINGS IN VISUALS AND UI AND THERE IS NO MORE CRASH

IT DOESN’T MATTER, I ALREADY FIXED EVERYTHING SO YOU DON’T NEED TO HELP ME, I JUST GOED TO THE PSYCH ENGINE SETTINGS IN VISUALS AND UI AND THERE IS NO MORE CRASH

IT DOESN’T MATTER, I ALREADY FIXED EVERYTHING SO YOU DON’T NEED TO HELP ME, I JUST GOED TO THE PSYCH ENGINE SETTINGS IN VISUALS AND UI AND THERE IS NO MORE CRASH

IT DOESN’T MATTER, I ALREADY FIXED EVERYTHING SO YOU DON’T NEED TO HELP ME, I JUST GOED TO THE PSYCH ENGINE SETTINGS IN VISUALS AND UI AND THERE IS NO MORE CRASH

IT DOESN’T MATTER, I ALREADY FIXED EVERYTHING SO YOU DON’T NEED TO HELP ME, I JUST GOED TO THE PSYCH ENGINE SETTINGS IN VISUALS AND UI AND THERE IS NO MORE CRASH

IT DOESN’T MATTER, I ALREADY FIXED EVERYTHING SO YOU DON’T NEED TO HELP ME, I JUST GOED TO THE PSYCH ENGINE SETTINGS IN VISUALS AND UI AND THERE IS NO MORE CRASH

IT DOESN’T MATTER, I ALREADY FIXED EVERYTHING SO YOU DON’T NEED TO HELP ME, I JUST GOED TO THE PSYCH ENGINE SETTINGS IN VISUALS AND UI AND THERE IS NO MORE CRASH

IT DOESN’T MATTER, I ALREADY FIXED EVERYTHING SO YOU DON’T NEED TO HELP ME, I JUST GOED TO THE PSYCH ENGINE SETTINGS IN VISUALS AND UI AND THERE IS NO MORE CRASH

IT DOESN’T MATTER, I ALREADY FIXED EVERYTHING SO YOU DON’T NEED TO HELP ME, I JUST GOED TO THE PSYCH ENGINE SETTINGS IN VISUALS AND UI AND THERE IS NO MORE CRASH

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Vortex2Oblivion** [comment]
> IT DOESN’T MATTER, I ALREADY FIXED EVERYTHING SO YOU DON’T NEED TO HELP ME, I JUST GOED TO THE PSYCH ENGINE SETTINGS IN VISUALS AND UI AND THERE IS NO MORE CRASH
> 

Close the issue then
