### ISSUE TITLE
Story Mode Doesn't Work! Pls help me!

### ISSUE THREAD

**Issue by EstufaVoladora3000** [ShadowMario/FNF-PsychEngine#13984]
### Describe your problem here.

![Captura de pantalla (55)](https://github.com/ShadowMario/FNF-PsychEngine/assets/113256731/2b70fae7-522d-4a90-9892-159f395c35fb)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no.

**Comment by EpicMawerDiff** [comment]
I think I got this error before, just get a clean build, then put the files of whatever mod you're playing into the mod files
