### ISSUE TITLE
I had this but idk what's mean?

### ISSUE THREAD

**Issue by FacunMax** [ShadowMario/FNF-PsychEngine#13987]
### What is your question?

(don't ask me how i got this because i don't remember)
Yeah, the title said it, anybody can answer what is this pls?. I had a hx called FNFSprite, and idk if is an extension of FlxSprite or something. heres the code if anybody want:
![Captura de pantalla (574)](https://github.com/ShadowMario/FNF-PsychEngine/assets/148605202/8539618d-b1dc-41f9-8edd-32aee2abd9fe)

**Comment by KELOTOMU** [comment]
It's a similar version of BGSprite.hx, and yes it is an extension of FlxSprite

**Comment by FacunMax** [comment]
> It's a similar version of BGSprite.hx, and yes it is an extension of FlxSprite
