### ISSUE TITLE
compile stops with word "error"

### ISSUE THREAD

**Issue by CHEESECONTENT** [ShadowMario/FNF-PsychEngine#13983]
### Describe your problem here.

when i compile psych engine 0.6.3, it just says "error" then stops compiling all together

idk what to do
![Capture](https://github.com/ShadowMario/FNF-PsychEngine/assets/22923262/25eb23a2-5df0-4fc1-99bf-08c8e1731edb)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by CHEESECONTENT** [comment]
correction: this happens with every version

**Comment by Vortex2Oblivion** [comment]
Does it say anything under the word error?
It looks like something might be cut off in your screenshot

**Comment by CHEESECONTENT** [comment]
> Does it say anything under the word error? It looks like something might be cut off in your screenshot

no, it just says error then waits for me to type another command

**Comment by 2JENO** [comment]
> no, it just says error then waits for me to type another command

huh??

**Comment by mcagabe19** [comment]
ur visual studio messed up

**Comment by CHEESECONTENT** [comment]
any way to uninstall and reinstall them?

**Comment by CHEESECONTENT** [comment]
nothing worked, getting my pc fixed so ill try after that
