### ISSUE TITLE
My game's close when the character change in playstate

### ISSUE THREAD

**Issue by mik1eeuseila** [ShadowMario/FNF-PsychEngine#13988]
### What is your question?

hi uh my friend made a code for me when you reach step 529 in the song the opponent character changes, but when me reachs in step 529 in the song the character changes and the game CLOSES!

somebody know how to fix this?

this the code lma
![imagem_2024-01-17_123909925](https://github.com/ShadowMario/FNF-PsychEngine/assets/152651146/aab4b169-e644-4114-ac37-db7d938104ed)

**Comment by Vortex2Oblivion** [comment]
I wouldn't use trigger event and just place the event in the chart editor normally

**Comment by mik1eeuseila** [comment]
> I wouldn't use trigger event and just place the event in the chart editor normally

when i place the event in chart  editor he closes the game just like i said too

**Comment by BernardoGP4504** [comment]
Maybe it has to do with your character?

**Comment by Vortex2Oblivion** [comment]
> > I wouldn't use trigger event and just place the event in the chart editor normally
> 
> 
> 
> when i place the event in chart  editor he closes the game too just like i said 

Probably something is wrong with your character then but I still would recommend placing the event note normally

**Comment by BernardoGP4504** [comment]
> > when i place the event in chart  editor he closes the game too just like i said
> 
> I still would recommend placing the event note normally

It has no difference, placing the event normally already calls a `triggerEvent` by default
