### ISSUE TITLE
How to know which type of OS is used

### ISSUE THREAD

**Issue by Soeiz** [ShadowMario/FNF-PsychEngine#13982]
### What is your question?

Hello, I want to know if by using lua, we can recognise if the player is using windows 7, 10, or 11. Could we, and if yes, how can we do that ??

**Comment by KELOTOMU** [comment]
You definitely can't do that in Lua but I'm not sure about .hx, it can check the os of the client

**Comment by Soeiz** [comment]
Alright, thanks anyway
