### ISSUE TITLE
I m keep getting this error i tried reinstalling everythink but it didnt work

### ISSUE THREAD

**Issue by MEfeDemirel** [ShadowMario/FNF-PsychEngine#13998]
### Describe your problem here.

i m keep getting it. I checked the github too but nothink seemd off to me. I tried several tutorials but it didnt work either.

![error](https://github.com/ShadowMario/FNF-PsychEngine/assets/118128324/096b4846-6704-4eef-a8ad-0ba5051f015b)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

i just said yes to somethink and seleckted visual studio coding think.

**Comment by mysteriousfellow** [comment]
Could i get some help here? 
![2024-01-18 (4)](https://github.com/ShadowMario/FNF-PsychEngine/assets/150180696/49f8fee1-f598-4579-aeb8-64872498b71a)
