### ISSUE TITLE
The local variable stays at 0 when it's not supposed to.

### ISSUE THREAD

**Issue by Your-Local-LordXSimp** [ShadowMario/FNF-PsychEngine#13999]
### Describe your problem here.

`local possessRate = 0;

function onCreate()
	makeLuaText('poss', 'POSSESSION RATE: '..possessRate..'%', 900, -240, 570)
    setObjectCamera('poss', 'HUD')
    setTextFont('poss', 'Stressed.otf')
    setTextColor('poss', 'FF190C')
    setTextSize('poss', 45)
    addLuaText('poss')
end

function onUpdate(elapsed)
    health = getProperty('health')
    if getProperty('health') - 1 then
        possessRate = possessRate + 1;
    elseif getProperty('health') + 1 then
        possessRate = possessRate - 1;
    end
end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Custom pause menu and event.

**Comment by JHAM25** [comment]
La función onCreate() no se actualiza debes de hacer esto ponerlo en onUpdate()
setTextString('poss', possessRate)
