### ISSUE TITLE
FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : T ype not found : flixel.sound.FlxSound

### ISSUE THREAD

**Issue by Fellegend** [ShadowMario/FNF-PsychEngine#13993]
### Describe your problem here.

I tried to compile Psych Engine and I get this error:
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
source/states/PlayState.hx:36: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
source/psychlua/FunkinLua.hx:16: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\User\Desktop\My stuff\Games\FNF and stuff\FNF T.T\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall

And I didn't edit NOTHING!!

[<o>]

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by FZ-Green** [comment]
Use this:

haxelib install SScript 8.1.6

**Comment by Fellegend** [comment]
nothing happens

**Comment by Fellegend** [comment]
> Use this:
> 
> haxelib install SScript 8.1.6

I tried and nothing

**Comment by mcagabe19** [comment]
update your flixel

**Comment by Fellegend** [comment]
> downgrade your flixel

to what version?

**Comment by mcagabe19** [comment]
idk find

**Comment by Fellegend** [comment]
> idk find

bruh ok

**Comment by khuonghoanghuy** [comment]
Try replace `flixel.sound.FlxSound` to `flixel.system.FlxSound`

**Comment by N3oomy** [comment]
> Try replace `flixel.sound.FlxSound` to `flixel.system.FlxSound`

how do i do that

**Comment by khuonghoanghuy** [comment]
> > Try replace `flixel.sound.FlxSound` to `flixel.system.FlxSound`
> 
> how do i do that

you can just backspace `flixel.sound.FlxSound` and type `flixel.system.FlxSound`

**Comment by Fellegend** [comment]
> Try replace `flixel.sound.FlxSound` to `flixel.system.FlxSound`

i'll try

**Comment by Fellegend** [comment]
> > > Try replace `flixel.sound.FlxSound` to `flixel.system.FlxSound`
> > 
> > 
> > how do i do that
> 
> you can just backspace `flixel.sound.FlxSound` and type `flixel.system.FlxSound`

Wait, I don't understand

**Comment by Fellegend** [comment]
C:/haxelib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat should be declared with 'override' since it is inherited from superclass flixel.graphics.frames.FlxAtlasFrames
C:/haxelib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat overrides parent
class with different or incomplete type
C:/haxelib/flixel/5,5,0/flixel/graphics/frames/FlxAtlasFrames.hx:457: characters 18-24 : ... Base field is defined here
C:/haxelib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : ... Different number of function arguments
source/backend/Paths.hx:605: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)
source/objects/Character.hx:304: characters 87-101 : flxanimate.animate.FlxAnim has no field lastPlayedAnim
source/objects/Character.hx:335: characters 20-26 : flxanimate.animate.FlxAnim has no field resume

**Comment by Fellegend** [comment]
Nvm i made a new issue. problem solved

**Comment by Fellegend** [comment]
idk lol
