### ISSUE TITLE
I've tried everything but I couldn't

### ISSUE THREAD

**Issue by NeoMGS** [ShadowMario/FNF-PsychEngine#13994]
### Describe your problem here.

flixel/sound/FlxSound.hx (line 595)
flixel/sound/FlxSound.hx (line 739)
flixel/system/frontEnds/SoundFrontEnd.hx (line 183)
flixel/system/frontEnds/SoundFrontEnd.hx (line 241)
states/PlayState.hx (line 1003)
flixel/util/FlxTimer.hx (line 205)
flixel/util/FlxTimer.hx (line 295)
flixel/FlxGame.hx (line 750)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ian82758** [comment]
im trying to find the solution but nobody gives nothing
