### ISSUE TITLE
Lua question

### ISSUE THREAD

**Issue by DOGZ1234** [ShadowMario/FNF-PsychEngine#1399]
### What is your question?

Is it possible to force Psych Engine to use a different Lua runtime?
I have the .dylib file Which is basically the macOS equivalent of a .dll file.

**Comment by ShadowMario** [comment]
Lua support for Mac was added yesterday on Linc LuaJIT's repo. Update your stuff with `haxelib update linc_luajit`

**Comment by Isuckcoding** [comment]
how do i fix the update linc_luajit
