### ISSUE TITLE
AMAZING ENGINE...but charting issues

### ISSUE THREAD

**Issue by djawesomeyt** [ShadowMario/FNF-PsychEngine#140]
Alright, so this engine is awesome, but there are some charting stuff that need to get fixed.
1.) Copy and Pasting Sections
Whenever I copy and paste a section the pasted section is buggy and doesn't even appear in the chart ingame.

2.)After beating a song
I finished charting my song rand tested it in game instead of going back to the charting menu it back to the freeplay menu and I lost a huge chunk of my chart. it would be pretty cool that you somehow made it so when you chart a song you go into a charting state(like in mic'd up) where after you beat the song it goes back to the charting menu and you can access the charting menu in the pause menu. Just a suggestion.

other than that pog engine

**Comment by FuseIsHere813** [comment]
You can use Load Autosave in chart editor to bring back your work.

**Comment by ShadowMario** [comment]
Fixed Copy/Paste Sections, i was planning to implement the second thing later
