### ISSUE TITLE
Icons Preview for people who want to fix the icons offsets [like what i code in the video here]

### ISSUE THREAD

**Issue by THOBY555** [ShadowMario/FNF-PsychEngine#1400]
### What feature do you want to get added on the base engine?

https://user-images.githubusercontent.com/71563419/143674971-00330546-fef5-4378-9f8c-4b19a54d0eed.mp4

iits so simple i just put this on CharacterEditorState 

			\nF1 - Idle Health Icon
			\nF2 - Loss Health Icon

```
if (FlxG.keys.justPressed.F1)
			{
				leHealthIcon.updateHitbox();
				trace("Idle Health Icon");
				leHealthIcon.animation.curAnim.curFrame = 0;
				FlxG.sound.play(Paths.sound('scrollMenu'));
			}
			if (FlxG.keys.justPressed.F2)
				{
					trace("Loss Health Icon");
					leHealthIcon.animation.curAnim.curFrame = 1;
					FlxG.sound.play(Paths.sound('scrollMenu'));
				}
``` this for the default 2 icons but for me i use wining icons too 

i wish you add this to the new version of Psych Engine

i Love Pscyh Engine

**Comment by Reycko** [comment]
Try using [this image](https://user-images.githubusercontent.com/78082869/143678994-c116c23f-ed1a-4861-a16d-b6e536b1ab58.png) on your iconGr

**Comment by THOBY555** [comment]
> Try using [this image](https://user-images.githubusercontent.com/78082869/143678994-c116c23f-ed1a-4861-a16d-b6e536b1ab58.png) on your iconGrid
> 
> image preview: ![gridTemplate](https://user-images.githubusercontent.com/78082869/143679040-e340c64a-75a3-4e6c-a800-81c8b5a4ab70.png)

![Desktop Screenshot 2021 11 27 - 14 50 06 43](https://user-images.githubusercontent.com/71563419/143680093-f1ccba27-3e91-47fa-bec0-456313aa2445.png)
![icon-whitty](https://user-images.githubusercontent.com/71563419/143680083-bf018ff0-c07e-4ca1-8d4b-7d66bc68c0fa.png)
i dont fucking using iconGrids i use 1 image that has 3 frames like this

**Comment by ShadowMario** [comment]
Psych Engine doesn't support Winning Icons, and unless it gets added to the base game, it never will.

**Comment by THOBY555** [comment]
i didnt mean wining icons i mean editor for lose and idle icons this is just my case

**Comment by THOBY555** [comment]
also for fixing the icons offsets
