### ISSUE TITLE
Changing health bar icons during a song

### ISSUE THREAD

**Issue by Motip-131** [ShadowMario/FNF-PsychEngine#14009]
### Describe your problem here.

Does anyone know the correct command to change the icons of the characters during a match? I've been trying with setProperty('iconP1', 'images/icons/icon-agoti') and setProperty('iconP1', 'icons/icon-void') and similar commands. However, the game crashes. I don't know how to do it correctly; does anyone know the code?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by mcagabe19** [comment]
```lua
runHaxeCode([[game.icon(P1/P2).changeIcon('nameoficon')]])
```
