### ISSUE TITLE
Questions about the new 0.7.3 update

### ISSUE THREAD

**Issue by thefnfcoder** [ShadowMario/FNF-PsychEngine#14000]
### What is your question?

There aren't going to be much questions due to some small updates
Q: Can you still use the Voices.ogg. (aka the merged version of Voices-Player.ogg and Voices-Opponent.ogg)
and if we can still use it, does it have an effect for it? (Just realized that some fan builds for some mods did the separate vocals before this update)
Q: I know there aren't going to be updates about Winning Icons but was there any plans for it before it was unintended for the engine?
Q: What were the minor bug fixes? (My possible guest is when the code running the application when doing something crashes unexpected)
I know this isn't part of the questions but will there be a message that happens whenever no weeks or freeplay songs are shown?
(That's all the question I have for now)

**Comment by thefnfcoder** [comment]
I know the second question wasn't an update related. I just putted there if it was plan before.

**Comment by mcagabe19** [comment]
are u that lazy u can't try 1st question?

**Comment by thefnfcoder** [comment]
> are u that lazy u can't try 1st question?

I tried it, and it worked well. Are you one of the developers of the engine because I ran into a problem when the game lags. Whenever the game lags, both vocals and instrumental are off sync with the notes.

**Comment by thefnfcoder** [comment]
This happens sometimes but not all the time

**Comment by ShadowMario** [comment]
1. Yes
2. No
3. I don't remember all of them, this is just an "etc." type thing, you can check the commits for it
