### ISSUE TITLE
help to compile 0.7.3

### ISSUE THREAD

**Issue by Toadz77-2** [ShadowMario/FNF-PsychEngine#14005]
### Describe your problem here.

source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Toadz77-2** [comment]
im on 0.7.3

**Comment by mcagabe19** [comment]
```bash
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git
```

**Comment by Toadz77-2** [comment]
thank you
