### ISSUE TITLE
Song only playing title screen in chart editor

### ISSUE THREAD

**Issue by FEN-N3C** [ShadowMario/FNF-PsychEngine#14007]
### Describe your problem here.

When I try to load my song that I have, it only plays the title screen song in the chart editor, same with the actual thing. The song is located in the songs folder, it has a Inst and Voices .OGG file. It has the data in the data folder. I don't understand what is going wrong

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by BernardoGP4504** [comment]
When it plays that, it isn't finding the song files to load them on `PlayState`
