### ISSUE TITLE
Psych Engine won't enter any songs [v0.7.1h, HTML5 Source Code]

### ISSUE THREAD

**Issue by deco1212** [ShadowMario/FNF-PsychEngine#14006]
### Describe your problem here.

https://github.com/ShadowMario/FNF-PsychEngine/assets/95529667/7f43c2ff-5f8a-4057-92bc-a09f3e3d564d

I am currently trying to change up the source code for my mod, but this has been happening for a while now.

It is not a problem with the source code, as i have tried compiling a clean copy of the 0.7.1h source code, only to encounter the same result.

I suspect it's a library or compiling issue.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5/Browser

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, Story Menu, FlashingState, and much more has been changed.

**Comment by mcagabe19** [comment]
html5 support removed in 0.7+

**Comment by deco1212** [comment]
I see that, what's the library versions for 0.6.3?

**Comment by mcagabe19** [comment]
I'm not into that but u can try [our psych](https://github.com/MobilePorting/FNF-PsychEngine-Mobile) that has mobile support and html5 support

**Comment by deco1212** [comment]
Thank you, i needed HTML5 support a lot

**Comment by deco1212** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/95529667/d76287d3-e925-42e0-afe7-a7780c3159fb)

I accidentally ended up fixing it, just set all the libraries to the current ones as of 19/01/2024, then set openfl to 9.3.0
