### ISSUE TITLE
Icons aren't visible

### ISSUE THREAD

**Issue by Zanman06** [ShadowMario/FNF-PsychEngine#14004]
### Describe your problem here.

I have an event which makes new icons and swaps the icons and the health bar color when the event runs but the the on the event the p2 icon dissapears and the health bar colors changes

function onEvent(n, v1, v2)
if n == 'icon change' and v2 == 'black' then
setProperty('iconP2.visible', false)
setProperty('icon3.alpha', 1)
setProperty('icon4.visible', false)
setHealthBarColors('#3a1b4f', '#31b0d1')
end
if n == 'icon change' and v2 == 'white' then
setProperty('iconP2.visible', true)
setProperty('icon3.alpha', 0)
setProperty('icon4.visible', false)
setHealthBarColors('#d1d2f8', '#31b0d1')
end
if n == 'icon change' and v2 == 'both' then
setProperty('iconP2.visible', false)
setProperty('icon3.alpha', 0)
setProperty('icon4.visible', true)
setHealthBarColors('#3a1b4f', '#31b0d1')
end
end
function onCreate()
	if not hideHud then
	makeAnimatedLuaSprite('icon3', nil, getProperty('iconP2.x'), getProperty('iconP2.y'))
	loadGraphic('icon3', 'icons/icon-blackdk', 150)
	addAnimation('icon3', 'icons/icon-blackdk', {1, 0}, 0, true)
	addAnimation('icon3', 'icons/icon-blackdk', {0, 1}, 0, true)
	addLuaSprite('icon3', true)
	setObjectOrder('icon3', getObjectOrder('iconP2') - 1)
	setObjectCamera('icon3', 'hud')
	setProperty('icon3.alpha', 0)
	end

	if not hideHud then
	makeAnimatedLuaSprite('icon4', nil, getProperty('iconP2.x'), getProperty('iconP2.y'))
	loadGraphic('icon4', 'icons/icon-blacknwhite', 150)
	addAnimation('icon4', 'icons/icon-blacknwhite', {1, 0}, 0, true)
	addAnimation('icon4', 'icons/icon-blacknwhite', {0, 1}, 0, true)
	addLuaSprite('icon4', true)
	setProperty('icon4.visible', false)
	setObjectOrder('icon4', getObjectOrder('iconP2') - 1)
	setObjectCamera('icon4', 'hud')
	end
end

function onUpdatePost()
	if not hideHud then
	setProperty('icon3.y', getProperty('iconP2.y') - 0)
	setProperty('icon3.x', getProperty('iconP2.x') - 9)
	setProperty('icon3.scale.x', getProperty('iconP2.scale.x') - 0.15)
	setProperty('icon3.scale.y', getProperty('iconP2.scale.y') - 0.15)
	setObjectOrder('icon3', getObjectOrder('iconP2') - 1)
	setProperty('icon3.angle', getProperty('iconP2.angle'))
	end
	if getProperty('health') > 1.6 then
		setProperty('icon3.animation.curAnim.curFrame', '1')
	else
		setProperty('icon3.animation.curAnim.curFrame', '0')
	end

	if not hideHud then
	setProperty('icon4.y', getProperty('iconP2.y') - 0)
	setProperty('icon4.x', getProperty('iconP2.x') - 0)
	setProperty('icon4.scale.x', getProperty('iconP2.scale.x') - 0.15)
	setProperty('icon4.scale.y', getProperty('iconP2.scale.y') - 0.15)
	setObjectOrder('icon4', getObjectOrder('iconP2') - 1)
	setProperty('icon4.angle', getProperty('iconP2.angle'))
	end
	if getProperty('health') > 1.6 then
		setProperty('icon4.animation.curAnim.curFrame', '1')
	else
		setProperty('icon4.animation.curAnim.curFrame', '0')
	end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no i didn't

**Comment by KELOTOMU** [comment]
make the lua sprites for icon3 and icon4 inside the event itself, also onUpdatePost dont run in event scripts so remove them

**Comment by Zanman06** [comment]
it worked before 0.7.2

**Comment by BernardoGP4504** [comment]
Prerty sure you can use `callMethod('icon(P1/P2).changeIcon', {'namehere'})` to change icons instead of another sprite.

Also, pretty sure there are better ways to do your script, try turning `luaDebugMode` to true so maybe it gives an error on what goes wrong

**Comment by Zanman06** [comment]
> Prerty sure you can use `callMethod('iconP2.changeIcon', {'namehere'})` to change icons instead of using fake sprites.
> 
> Also, pretty sure there are better ways to do your script, try turning `luaDebugMode` to true so maybe it gives an error on what goes wrong

This worked, thanks a lot!

**Comment by KELOTOMU** [comment]
> Prerty sure you can use `callMethod('iconP2.changeIcon', {'namehere'})` to change icons instead of using fake sprites.
> 
> Also, pretty sure there are better ways to do your script, try turning `luaDebugMode` to true so maybe it gives an error on what goes wrong

I never knew you can call functions of instances with `setProperty()` in Lua, that would be really helpful for me
