### ISSUE TITLE
Step-long sustains don't appear in gameplay after a BPM change

### ISSUE THREAD

**Issue by basketcaise** [ShadowMario/FNF-PsychEngine#14011]
### Describe your bug here.

After a BPM change has been applied to a section, all new notes placed in that section and after don't have sustains in gameplay (in chart test and playstate) if their sustain length is a step long. Despite this, they still appear as having sustains in the chart editor. Using latest version.

Video has been added for clarification:
https://github.com/ShadowMario/FNF-PsychEngine/assets/96320621/a117a900-937f-43e9-ba99-5c24895d8e94

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing was edited in source

**Comment by KELOTOMU** [comment]
Thats expected changing the bpm to a faster or slower one will skip a lot of notes

**Comment by CoolGuyisHere** [comment]
> Thats expected changing the bpm to a faster or slower one will skip a lot of notes

Yeah, in the case of changing the BPM in an earlier section with notes already placed in later sections, this would make sense. However, this applies to new notes placed after the BPM change as well which shouldn't happen
