### ISSUE TITLE
Video Issue

### ISSUE THREAD

**Issue by TheSPREEGuy** [ShadowMario/FNF-PsychEngine#14010]
### Describe your problem here.

I built it from latest source and the mods that have videos crash without a crash popup and just closes,
but the latest public release works with videos its just when I try to compile it, it wont work.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by KutikiPlayz** [comment]
they for some reason put the `VIDEOS_ALLOWED` flag inside an if check that only allows it if the game's an official build, that's probably what's causing the issue
just go into Project.xml and move that line outside the if statement and you should be good

**Comment by TheSPREEGuy** [comment]
That worked thank you :>
