### ISSUE TITLE
Fatal error: obj\msvc1964-nc\f505ff26___ASSET__flixel_flixel_ui_xml_default_loading_screen_xml.obj corrupted or invalid

### ISSUE THREAD

**Issue by DxrkPxwer** [ShadowMario/FNF-PsychEngine#14017]
### Describe your bug here.

Yesterday, i was conding at fnf source normally, until i compiled the game and this error appeard: `obj\msvc1964-nc\f505ff26___ASSET__flixel_flixel_ui_xml_default_loading_screen_xml.obj : fatal error LNK1136: corrupt or invalid file`

I was confused and scared at the same time because if i don't find what exactly was the error, i wold lost ALL of the work that i've done.

It happened as soon that it was creating the application.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, but i think that the problem isn't the source it self.

**Comment by mcagabe19** [comment]
just delete the export folder recompile

**Comment by DxrkPxwer** [comment]
I LOST ALL OF MY WORK BE CAUSE OF YOU

**Comment by DxrkPxwer** [comment]
> just delete the export folder and recompile

but ill try

**Comment by DxrkPxwer** [comment]
IT WORKED

**Comment by Vortex2Oblivion** [comment]
> I LOST ALL OF MY WORK BE CAUSE OF YOU
> 
> 

If it happens again I think you just need to delete export/releaseordebugidk/windows(or whatever you are building for)/ and the haxe and obj folders and not the bin folder
