### ISSUE TITLE
Song Audio Not playing (without source code)

### ISSUE THREAD

**Issue by TamirPlaysYoutube** [ShadowMario/FNF-PsychEngine#1401]
### Describe your bug here.

i replaced the song audio with the new one and it doesn't play the audio and it's still 0 seconds

what should i do?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i replaced the song audio with the new one, and it's still 0 seconds

**Comment by ItsCapp** [comment]
is the song audio named "Inst" ?
the file also needs to be a .ogg file

**Comment by NotEpik** [comment]
make sure it's "ogg" file

**Comment by ShadowMario** [comment]
Missing the file `mods/songs/your-song-name-here/Inst.ogg`
Don't forget, the song path must be all in lowercase, and `Inst` starts with an uppercase i.
The file format also MUST be .ogg

**Comment by MKUKPL** [comment]
yup still aint workin. already did a issue so I wont explain
