### ISSUE TITLE
How do I convert bf to white?

### ISSUE THREAD

**Issue by JHAM25** [ShadowMario/FNF-PsychEngine#14018]
### What is your question?

How do I convert bf to white and tried several ways but it doesn't work

**Comment by pac2005** [comment]
what ways have you tried

**Comment by JHAM25** [comment]
try with setProperty('boyfriend.color', ffffff), setProperty('boyfriend.color', 'ffffff'), doTweenColor('bf', 'boyfriend', ffffff, 1), doTweenColor('bf', 'boyfriend' ', 'ffffff', 1) but it only turns black or removes the black color

**Comment by 2JENO** [comment]
default sprite color is "0xFFFFFFFF", so you need use ColorSwap shaders brightness

**Comment by JHAM25** [comment]
Thanks
