### ISSUE TITLE
It is asking for the hxdiscord_rpc to be installed when it already is 

### ISSUE THREAD

**Issue by Danky136** [ShadowMario/FNF-PsychEngine#14016]
### Describe your bug here.

I was attempting to compile the game when it had kept failing to do so. I have tried to troubleshoot the problem myself but they were all unsuccessful. is there any way to troubleshoot it?

### Command Prompt/Terminal logs (if existing)

```bash
Error: Could not find haxelib "hxdiscord_rpc", does it need to be installed?
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No changes were made to the source code

**Comment by KELOTOMU** [comment]
Try installing it in haxelib instead of using hmm/.haxelib folder

**Comment by Danky136** [comment]
I tried it, it's not working
![Problem](https://github.com/ShadowMario/FNF-PsychEngine/assets/128556070/cb9eee5d-ec36-4354-81b9-2475c86889f9)

**Comment by Danky136** [comment]
Accidentally closed it, my apologies

**Comment by WolfyTail** [comment]
How did you fix it?

**Comment by Danky136** [comment]
I wasn’t able to, until I found some commit or something like that. I can’t
remember what it was called
