### ISSUE TITLE
Accuracy Rating, Score, and Judgements editor

### ISSUE THREAD

**Issue by Average-FNF-Modder** [ShadowMario/FNF-PsychEngine#14022]
### What feature do you want to get added on the **base** engine?

Basically, the editor would allow to make custom judgements for hitting notes with custom millisecond windows for hitting them and images to go with, possibly with an option for players to be able to modify the hit windows in mod settings. As well as the ability to change out the variables and info shown on the score bar (Like adding # of hits for example), change the names of and accuracy percentages required for ratings, the amount of score judgements give and possibly an option for variable combo multiplier on score (Though that's an extra), and to change the name and requirement for your FCrating, like adding an option to have another rating for under 20 misses, or having your custom note judgements give unique FC names when you get no lower than them. The real dream would be to have some of these settable as mod settings, but that is also extra. Currently the only way to do things like this is through very long and convoluted LUA code that is annoying as hell to work with, so I think this would streamline the process. I know I'm asking for a lot, and I can't even begin to understand any complications with trying to code that in, but I think it would be cool. Once done, you could save your judgements with accuracy values and score bar setup as 2 Json files. You can drop either drop into a chart and they will be used automatically, or you can put them into a folder labeled "Scoring" Inside of the "data" folder in a mod and call them up from the data tab in a chart where they will be saved for use on that charts Json.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MrSropical** [comment]
> ### What feature do you want to get added on the **base** engine? Currently the only way to do things like this is through very long and convoluted LUA code
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Stage Editor, 6K+ support, and winning icons.

Bro, Psych Engine doesn't need this much feature, so just coding in lua or haxe

**Comment by Average-FNF-Modder** [comment]
> > ### What feature do you want to get added on the **base** engine? Currently the only way to do things like this is through very long and convoluted LUA code
> > ### To test your sight, and reliability, please select the option of what should NOT be requested.
> > Stage Editor, 6K+ support, and winning icons.
> 
> Bro, Really made an account yesterday to write the 2.0 psych engine update Psych Engine doesn't need this much feature, so just code it in lua or haxe

Chill out bro it was just an idea I've had for literal months.
