### ISSUE TITLE
Voice crackling

### ISSUE THREAD

**Issue by cabfile** [ShadowMario/FNF-PsychEngine#14026]
### Describe your bug here.

Sometimes the vocals seem to distort weirdly. It sounds like crackling. This seems to go away after restarting a song.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/pull/14008

**Comment by trayfellow** [comment]
> #14008

This should be fixed if this PR i quoted gets merged, i tested it out myself and it fixed the issue you had
