### ISSUE TITLE
The characters are not showing on HScript stage. Please help

### ISSUE THREAD

**Issue by Stefan2008Git** [ShadowMario/FNF-PsychEngine#14021]
### Describe your problem here.

So basically the title says. I am doing the VS Cheeky V3 PE port, but i got this:
![Снимак екрана направљен дана 2024-01-21 21-48-52](https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/f55a9252-d11c-4c7e-87fe-6e112b788fb2)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by mcagabe19** [comment]
maybe in layering (like bf in 1, gf in 2, dad in 3)

**Comment by Stefan2008Git** [comment]
> maybe in layering (like bf in 1, gf in 2, dad in 3)

I am kinda confused about layering, but it shows only on main coded stages instead on custom HScript stages

**Comment by Stefan2008Git** [comment]
> > maybe in layering (like bf in 1, gf in 2, dad in 3)
> 
> I am kinda confused about layering, but it shows only on main coded stages instead on custom HScript stages

Do you need an code or something @mcagabe19?

**Comment by mcagabe19** [comment]
idk about hscript stage too much sorry stefan

**Comment by Stefan2008Git** [comment]
> idk about hscript stage too much sorry stefan

It's fine LOL. The HScript stage is the same as source, but if you want to remove source coded objects, use "game.remove(tagObjectName)" (I just gave an one example),
