### ISSUE TITLE
how to change background

### ISSUE THREAD

**Issue by deathline1938** [ShadowMario/FNF-PsychEngine#1402]
![HOW](https://user-images.githubusercontent.com/94227585/143675591-4be9c6ba-0b2d-417f-8627-16a2d168fdfa.png)
### Describe your problem here.

I want the background to change in the middle of the song (psych engine)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by 4wdthinks** [comment]
you can't change the background, but you can overlay another flxsprite/lua sprite over the background and toggle it whenever.

**Comment by DEV-idiotXD** [comment]
@ShadowMario another duplicate

**Comment by Rorthgamer2XD** [comment]
Hmmm here a idea use the custom events from the ben drowned mod and drag it to your mod
