### ISSUE TITLE
Need help compiling Psych 0.7.3 source code

### ISSUE THREAD

**Issue by MeReaganGIT** [ShadowMario/FNF-PsychEngine#14024]
### Describe your problem here.

I keep having the same lines of issues when trying to compile. I have installed and updated all libraries and referred to any resource that I could find and still cannot get it to work. Does anyone know what to do to fix this? Thank you!

![image_2024-01-21_203450047](https://github.com/ShadowMario/FNF-PsychEngine/assets/157331169/9f0c9baa-6b78-4bd2-ba15-c2ca05bf081f)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, this is a fresh download of the source code.

**Comment by mcagabe19** [comment]
update your haxe

**Comment by MeReaganGIT** [comment]
> update your haxe

I have the most recent version installed

**Comment by MeReaganGIT** [comment]
> Update your SSCript and Haxe maybe Just type in
> 
> ```batchfile
> haxelib install SScript
> ```
> 
> in your cmd For Haxe, go to this link https://haxe.org/download/version/4.2.5/

I have the most recent version of Haxe and updated SSCript based on ShadowMario’s libraries page. I’ll try downgrading Haxe when I’m able.

**Comment by MeReaganGIT** [comment]
Downgrading Haxe to 4.2.5 and redownloading all libraries worked! Thank you all so much!
