### ISSUE TITLE
Note hit then Ratings scales

### ISSUE THREAD

**Issue by Mlaofmd** [ShadowMario/FNF-PsychEngine#14025]
### What is your question?

hello i wanna to code note hit then ratings scales on lua like that
![chrome_puY5INMLYF](https://github.com/ShadowMario/FNF-PsychEngine/assets/52864321/73b5feef-6039-4ac3-9543-a5007ecddcce)

**Comment by MrSropical** [comment]
Just download the mod and you'll get that script you want

**Comment by Mlaofmd** [comment]
> Just download the mod and you'll get that script you want

this code in source code coded, but this not have public source code
