### ISSUE TITLE
Am I Stupid?

### ISSUE THREAD

**Issue by CorrupToon** [ShadowMario/FNF-PsychEngine#14030]
### Describe your problem here.

I'm trying to import a chart but crash when i try to play it and get this error message                                                                                                                                   
                          
"objects/Note.hx (line 464)
states/PlayState.hx (line 1758)
flixel/group/FlxGroup.hx (line 787)
states/PlayState.hx (line 1752)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference"

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not counting mods, No

**Comment by CorrupToon** [comment]
> it seems to be something is missing

Can you be more specific

**Comment by MrSropical** [comment]
> > it seems to be something is missing
> 
> Can you be more specific
when there's note.hx means your probably forgot a note texture
