### ISSUE TITLE
Disable RGB Shaders

### ISSUE THREAD

**Issue by Average-FNF-Modder** [ShadowMario/FNF-PsychEngine#14039]
### What feature do you want to get added on the **base** engine?

Some note-skins get messed up by the new note RGB shader system. I know you can already disable it for one chart, but it would be nice if the player could turn it off in their note-skin settings to stop their skins from being messed up and if modders could have a way to set a skin to not have the RGB shader if they wish.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by FourTheGreat** [comment]
that's already a thing.
`setPropertyFromGroup('notes',id,'rgbShader.enabled', false)`

**Comment by ShadowMario** [comment]
`rgbShader.enabled = false` on the note type .txt file

**Comment by Average-FNF-Modder** [comment]
Oh cool thanks

**Comment by shikecool64amongus69** [comment]
hey yeah but how do you change it for note skins????? not notetypes
