### ISSUE TITLE
vocals repeating at the end of a song

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#14034]
### Describe your problem here.

So I'm having an issue where some of the song's vocals start repeating at the end of the song for a little bit and then the i get sent to the menu how do I stop the song from repeating in both Lua and Source

https://github.com/ShadowMario/FNF-PsychEngine/assets/95887947/a96e4625-eea6-4056-9b0a-169bf6315284

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no i just added a song and finished charting it

**Comment by mcagabe19** [comment]
add some empty thing to ur voices that makes same duration with inst

**Comment by SonicXFire1987** [comment]
> add some empty thing to ur voices that makes same duration with inst

oh ok. ill bring it up to our song writer and see if that fixes it

**Comment by SonicXFire1987** [comment]
> add some empty thing to ur voices that makes same duration with inst

Thank you so much! it worked!

**Comment by Stukleak** [comment]
Doesn't work anymore :/
