### ISSUE TITLE
I can't solve this problem

### ISSUE THREAD

**Issue by phrGithubGamerBR** [ShadowMario/FNF-PsychEngine#14032]
### Describe your bug here.

I'm using psych engine 0.6.3

### Command Prompt/Terminal logs (if existing)

```bash
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1624: characters 13-23 : Type not found : MP4Handler
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yeah

**Comment by pablowolfgamerbr** [comment]
ok

**Comment by pablowolfgamerbr** [comment]
didn't solve

**Comment by KELOTOMU** [comment]
Use hxCodex 2.6.1 and change the import from `vlc.MP4Handler;` to `hxcodec.VideoHandler as MP4Handler;`
