### ISSUE TITLE
Is there any way to show the timer in seconds?

### ISSUE THREAD

**Issue by luigiman0** [ShadowMario/FNF-PsychEngine#14033]
### What is your question?

I'm making a mod based on SMB1 for the NES, and I'm looking to see if it's possible to change the timeTxt to display in seconds rather than the minutes : seconds format. Is there perhaps a variable that can do this?

**Comment by JHAM25** [comment]
something like that?

https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/c88696a6-e3fe-438a-b84f-ff557842f1cb

**Comment by luigiman0** [comment]
> something like that?
> 
>  Screenrecorder-2024-01-26-11-19-16-603.mp4

This is a good start, but I was moreso looking for it to count down over time instead of up.

**Comment by JHAM25** [comment]
Asi?

https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/150ac2e6-c375-446d-8159-6b43595d86ee

**Comment by JHAM25** [comment]
Si es asi aquí esta el código:


luaDebugMode = true
function onCreatePost()

end
function onUpdatePost()
curTime = math.max(0, getPropertyFromClass('Conductor', 'songPosition') - getPropertyFromClass('ClientPrefs', 'noteOffset'))
songCalc = (songLength - curTime);
secondsTotal = math.floor(songCalc / 1000);
setProperty('timeTxt.text', secondsTotal)
end

**Comment by MugMiles** [comment]
When I try to use this it says that both the ClientPrefs and Conductor classes can't be found

**Comment by JHAM25** [comment]
> Cuando intento usar esto, dice que no se pueden encontrar las clases ClientPrefs y Conductor.

Puede ser por que estas en las últimas versiones del Psych engine intenta probar con esto:
getPropertyFromClass('backend.Conductor', 'songPosition') y lo mismo para el otro

**Comment by MugMiles** [comment]
This gets rid of the two errors, but using 

luaDebugMode = true

function onCreatePost()

end
function onUpdatePost()
	curTime = math.max(0, getPropertyFromClass('backend.Conductor', 'songPosition') - getPropertyFromClass('backend.ClientPrefs', 'noteOffset'))
	songCalc = (songLength - curTime);
	secondsTotal = math.floor(songCalc / 1000);
	setProperty('timeTxt.text', secondsTotal)
end

results in 
ERROR 7: attempt to preform arithmetic on a nil value

**Comment by JHAM25** [comment]
> This gets rid of the two errors, but using
> 
> luaDebugMode = true
> 
> function onCreatePost()
> 
> end function onUpdatePost() curTime = math.max(0, getPropertyFromClass('backend.Conductor', 'songPosition') - getPropertyFromClass('backend.ClientPrefs', 'noteOffset')) songCalc = (songLength - curTime); secondsTotal = math.floor(songCalc / 1000); setProperty('timeTxt.text', secondsTotal) end
> 
> results in ERROR 7: attempt to preform arithmetic on a nil value

Aqui ya esta solucionado lo probe y funciona:
luaDebugMode = true

function onCreatePost()

end
function onUpdatePost()
curTime = math.max(0, getPropertyFromClass('backend.Conductor', 'songPosition') - getPropertyFromClass('backend.ClientPrefs', 'data.noteOffset'))
songCalc = (songLength - curTime);
secondsTotal = math.floor(songCalc / 1000);
setProperty('timeTxt.text', secondsTotal)
end

El problema era en: getPropertyFromClass('backend.ClientPrefs', 'data.noteOffset'))

**Comment by MugMiles** [comment]
Works perfectly! Thank you so much!
