### ISSUE TITLE
Multi-week locking

### ISSUE THREAD

**Issue by pac2005** [ShadowMario/FNF-PsychEngine#14047]
### What feature do you want to get added on the **base** engine?

The feature I request is for a week to be locked behind multiple other weeks at a time.
Currently, you can only make it so you have to beat a single week to unlock another week. What I want to require is for multiple weeks to all be beaten, and only then will the locked week unlock.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by KELOTOMU** [comment]
That would be useful

**Comment by Average-FNF-Modder** [comment]
Actually Based Feature FRFR.

**Comment by pac2005** [comment]
Is there any way to do this in the current version of Psych Engine through some sort of Lua script?

**Comment by Average-FNF-Modder** [comment]
Yo why not bro this is fire

**Comment by WoodsSilent05** [comment]
fr tho, this is actually a good idea.
