### ISSUE TITLE
Crashing loading into ANY song including base game songs.

### ISSUE THREAD

**Issue by CherriCola** [ShadowMario/FNF-PsychEngine#14041]
### Describe your bug here.

Loading into any song, mod or base game crashes the game no matter what. Even in the chart editor. I haven't touched anything. I'm on version 0.7.3 rn but I've gone through older ones as well.

### Command Prompt/Terminal logs (if existing)

```bash
objects/Note.hx (line 154)
objects/Note.hx (line 167)
states/PlayState.hx (line 1339)
states/PlayState.hx (line 510)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just downloaded a new release build to make sure. It crashes on all my versions.

**Comment by ian82758** [comment]
I HAVE THE SAME ERROR I DONT KNOW HOW TO FIX IT
