### ISSUE TITLE
icon variables

### ISSUE THREAD

**Issue by SlushieDrawzCoolDrawingX480** [ShadowMario/FNF-PsychEngine#14044]
### What is your question?

what are the icon variables? like the group variables, scale variables, x, y, etc

**Comment by KELOTOMU** [comment]
It can be variables thats possible to be in a sprite, like `spr.scale.x`, `spr.scrollFactor`, `spr.y` etc.

**Comment by SlushieDrawzCoolDrawingX480** [comment]
whats the group sprite, for both iconP1 and iconP2?

**Comment by KELOTOMU** [comment]
> whats the group sprite, for both iconP1 and iconP2?

I dont think theres a specific group for the icons, but uigroup does exist

**Comment by KELOTOMU** [comment]
> > whats the group sprite, for both iconP1 and iconP2?
> 
> I dont think theres a specific group for the icons, but uiGroup exists. Try using HealthIcon

**Comment by KELOTOMU** [comment]
> > whats the group sprite, for both iconP1 and iconP2?
> 
> I dont think theres a specific group for the icons, but uiGroup exists. Try using HealthIcon

**Comment by VoidedBattery** [comment]
> whats the group sprite, for both iconP1 and iconP2?

The sprite names are literally named `iconP1` and `iconP2`
