### ISSUE TITLE
PE0.7.3 Voice Play ERROR

### ISSUE THREAD

**Issue by CFBGH** [ShadowMario/FNF-PsychEngine#14059]
### Describe your bug here.

Unable to play voice in Playstate， Missing files

### Command Prompt/Terminal logs (if existing)

source/states/FreeplayState.hx:364: bopeebo-hard
source/states/FreeplayState.hx:372: CURRENT WEEK: week1
source/states/LoadingState.hx:159: Setting asset folder to week1
source/backend/Conductor.hx:124: new BPM map BUDDY []
source/states/PlayState.hx:1270: Error loading sound from file: ./assets/songs/bopeebo/Voices-Player.ogg

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yap, I've removed all the components related to Discord rpc

**Comment by Ant643** [comment]
u have files for everything the log has?

**Comment by Ant643** [comment]
@CFBGH

**Comment by CFBGH** [comment]
no, ShadowMario wrote a try statement there, but catch didn't write any statement, so there was no error, just no sound
There are also no error logs

Command Prompt:
BUILDING GAME
Creating D:/Project/FNF-PsychEngine-0.7.3/export/release/windows/obj/obj/msvc1964-nc/__pch/haxe/hxcpp.pch...
hxcpp.cpp

Compiling group: haxe
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdD:\Project\FNF-PsychEngine-0.7.3\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,3,2/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_CHECK_POINTER(haxe) -DHXCPP_STACK_TRACE(haxe) -DHXCPP_STACK_LINE(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/ApplicationMain.cpp
 - src/lime/utils/AssetCache.cpp  [haxe,release]
Link: ApplicationMain.exe
  正在创建库 ApplicationMain.lib 和对象 ApplicationMain.exp
source/states/FreeplayState.hx:364: dad-battle-hard
source/states/FreeplayState.hx:372: CURRENT WEEK: week1
source/states/LoadingState.hx:159: Setting asset folder to week1
source/backend/Conductor.hx:124: new BPM map BUDDY []
source/states/PlayState.hx:1270: Error loading sound from file: ./assets/songs/dad-battle/Voices-Player.ogg

done.
请按任意键继续. . .

**Comment by Ant643** [comment]
maybe re-add discord_rpc

**Comment by mcagabe19** [comment]
make a dummy Voices-Player.ogg in assets/songs/dad-battle
