### ISSUE TITLE
[LUA] Add menuScripts folder (scripts that trigger when the game starts or when the title screen starts)

### ISSUE THREAD

**Issue by HappyAlexRomania** [ShadowMario/FNF-PsychEngine#14057]
### What feature do you want to get added on the **base** engine?

This would be a great improvement to the scripts. They have to be put in a folder called 'menuScripts', or change the scripts folder to "scripts/game" and "scripts/menu". It would be great especially for making custom menu screens.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by idkwhattonamethisimnevergoingtousethis** [comment]
No

**Comment by ThePlank** [comment]
no

**Comment by CobaltBar** [comment]
This would be a good idea IF it didnt change 95% of the engine

**Comment by HappyAlexRomania** [comment]
> This would be a good idea IF it didnt change 95% of the engine

How would it change 95% of the engine? It's just an addition of an option to trigger some scripts in the menu screen, like in the "scripts" folder.

**Comment by crowplexus** [comment]
this has been discussed before, this is not possible to do with the current Lua API, to make this possible the API would have to go through a major rework, essentially breaking every older mod that currently exists (if 0.7 didn't already break them enough, that is)

**Comment by HappyAlexRomania** [comment]
> this has been discussed before, this is not possible to do with the current Lua API, to make this possible the API would have to go through a major rework, essentially breaking every older mod that currently exists (if 0.7 didn't already break them enough, that is)

oh ok
