### ISSUE TITLE
Source code error

### ISSUE THREAD

**Issue by mikoprimeb** [ShadowMario/FNF-PsychEngine#14055]
### Describe your problem here.

I tried to compile a source of 0.7.1h and got error (exatcly, type not found: SCall) and someone told me to install the experimental branch. I tried that and got this error now: 

source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
source/psychlua/CallbackHandler.hx:55: characters 41-46 : Class<llua.LuaL> has no field error
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
source/psychlua/FunkinLua.hx:280: lines 280-283 : Int should be Bool
source/psychlua/FunkinLua.hx:280: lines 280-283 : ... For function argument 'f'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, im using clean experimental version.

**Comment by Jamextreme140** [comment]
You should install linc_lua from _git_.

Use: 
`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git`
