### ISSUE TITLE
So....

### ISSUE THREAD

**Issue by MonkyRr** [ShadowMario/FNF-PsychEngine#14051]
### Describe your problem here.

I'm trying to compile source code but...
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/155294656/620a9d79-f317-4721-b53a-e372dac39f04)
I used:
Lime: 8.1.1
OpenFL: 9.3.2
Flixel: 4.11.0
HScript: 2.5.0
Newgrounds: 2.0.2
HXcpp: 4.2.1
hxCodec: 3.0.2
(btw idk if this is the right catagory for these types of issues)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No. First time compilling

**Comment by KELOTOMU** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by MonkyRr** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

forgot to mention
this is 0.6.3
not 0.7.2

**Comment by MonkyRr** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/155294656/46b74729-4173-45d6-89b0-8a4e86f77894)
ok so I did everything there and it gives more errors

**Comment by KELOTOMU** [comment]
> > https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions
> 
> forgot to mention this is 0.6.3 not 0.7.2

oh, then I know the libraries for 0.6.3

discord_rpc: [git] https://github.com/Aidan63/linc_discord-rpc.git
flixel-addons: [3.0.2]
flixel-ui: [2.5.0]
flixel: [5.2.2]
hscript: [2.5.0]
hxCodec: [2.6.1]
hxcpp-debug-server: [1.2.4]
hxcpp: [4.3.2]
lime: [8.0.1]
linc_luajit: [git] https://github.com/superpowers04/linc_luajit.git
openfl: [9.2.1]
tjson: [1.4.0]
