### ISSUE TITLE
Screen variables?

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#1405]
### Describe your problem here.

So, in the documentation all I can find is `screen width` and `screen height`
I'm having trouble setting the values of these, I'm trying to do this:
```
function onEvent(name, value1, value2)
    if name == "ScreenCustomisation" then
        SetPropertyFromClass('FlxG', width, value1)
        SetPropertyFromClass('FlxG', height, value2)
    end
end
```
btw this is what I'm entering
![image](https://user-images.githubusercontent.com/93293747/143682337-f63e3488-7530-482c-85f1-2f1a58b887ff.png)

what isn't working?

also are there variables for `screen x` , `screen y` and `screen rotation` ?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Everything I've done has been within the mods folder.

**Comment by SrtHero278** [comment]
wouldn't `width` and `height` be surrounded by quotes?

**Comment by ShadowMario** [comment]
`setPropertyFromClass('flixel.FlxG', 'width', value1);`
If it doesn't work, oh well.
