### ISSUE TITLE
Note colors for specific songs?

### ISSUE THREAD

**Issue by NeroEmperor** [ShadowMario/FNF-PsychEngine#14052]
So, I want to put these note colors in some songs, but they apply to every song, and that glitches other note skins. Is there a way I can make them apply only to specific songs? Any coding? (Lua or HX, but Lua preferably)

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/135268886/1b37bc88-d4d8-4ecf-8eef-ad19df3e527e)

**Comment by HaydenGamingBack** [comment]
your gonna have to hardcode it idrk if you can use lua to help but its extremely complicated code
