### ISSUE TITLE
need help with a script for a timeBar in 0.6.3 (lua)

### ISSUE THREAD

**Issue by AzzyDrezzy12** [ShadowMario/FNF-PsychEngine#14063]
### Describe your problem here.

I apologize if there was the same thing to this but i tried my best to look everywhere for it, so let me get straight into it..

So what i'm trying to do is when the timebar is disabled (in the game settings), the thing that's covering the timebar should also be disappeared

(just incase, this is a picture of what im talking about)

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/33179418/5d01aafa-7221-4967-9ed4-a3108d9dc678)

as you seen the picture above, i want that thing to disappear when you set your timeBar disabled.

i really tried everything the best i could, if this is easy to do then i really need to learn more lmfao

and here's a lua script i made for the thing

```
function onCreatePost()
	makeLuaSprite('Time', 'timebar-seq/time9');
	setObjectCamera('Time', 'hud')
	addLuaSprite('Time', true)
	setObjectOrder('Time', getObjectOrder('timeBar') + 1)
	setProperty('timeBar.visible', true)
	setTextFont('timeTxt', 'Comfortaa-Bold.ttf')
end

function onUpdatePost(elapsed)
	setProperty('Time.visible', getProperty('timeBar.visible'))
	setProperty('Time.alpha', getProperty('timeBar.alpha'))
	scaleObject('Time', 1, 1.1)
	setProperty('Time.x', getProperty('timeBar.x') - 40)
	setProperty('Time.y', getProperty('timeBar.y') - 27)
end

function onUpdate()
if timeBarType == Disabled then
removeLuaSprite('Time')
end
end
```

i really tried stuff like ```setPropertyFromClass('ClientPrefs', 'TimeBarType')``` but it didn't work how i wanted it to be and i honestly wanted help on this.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by AzzyDrezzy12** [comment]
> I think I figured it out, Here:
> 
> function onUpdate() if setProperty('healthBar.visible', false) then setProperty('Time.visible', false) end end
> 
> Here, if 'Hide HUD' is turned on (or if the timebar isn't visible), the cover should disappear with the timebar!

that removed the healthbar colors and the timebar’s cover is still there

**Comment by EpicMawerDiff** [comment]
Sorry, I didn't check for if the hud was on
