### ISSUE TITLE
Running github actions for html5 doesnt work (0.6.3) 

### ISSUE THREAD

**Issue by Ant643** [ShadowMario/FNF-PsychEngine#14062]
### Describe your bug here.

this readHmmJsonOrThrow()  line really hates me, doesnt it?

### Command Prompt/Terminal logs (if existing)

```bash
Run haxelib setup ~/haxelib
haxelib repository is now /home/runner/haxelib

A new version (4.1.0) of haxelib is available.
Do `haxelib --global update haxelib` to get the latest version.

Downloading hmm-3,1,0.zip...
Installing hmm...
  Current version is now 3.1.0
Done
Installing dependency thx.core 0.44.0
Downloading thx,core-0,44,0.zip...
Installing thx.core...
  Current version is now 0.44.0
Done
Installing dependency utest 1.13.2
Downloading utest-1,13,2.zip...
Installing utest...
  Current version is now 1.13.2
Done
haxelib --never newrepo --quiet
Local repository created (/home/runner/work/fnf/fnf/.haxelib)
Unexpected error: Invalid char 34 at position 1018
from: hmm.HmmConfigs.readHmmJsonOrThrow() at 69


Called from /opt/homebrew/lib/haxe/std/haxe/format/JsonParser.hx line 318
Called from /opt/homebrew/lib/haxe/std/haxe/format/JsonParser.hx line 96
Called from /opt/homebrew/lib/haxe/std/haxe/format/JsonParser.hx line 117
Called from /opt/homebrew/lib/haxe/std/haxe/format/JsonParser.hx line 90
Called from /opt/homebrew/lib/haxe/std/haxe/format/JsonParser.hx line 57
Called from hmm/HmmConfig.hx line 59
Use "hmm help" to see usage
Error: Process completed with exit code 1.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

only added and edited hmm

###  Haxe version

4.2.5
### hmm version 
latest

**Comment by Ant643** [comment]
also ik that 0.6.3 isnt supported, i just wanna build for html5.

**Comment by mcagabe19** [comment]
ur hmm.json messy

**Comment by Ant643** [comment]
how to fix?

**Comment by Ant643** [comment]
nvm I just run command to install w/o hmm

**Comment by Ant643** [comment]
### Describe your bug here.

this readHmmJsonOrThrow()  line really hates me, doesnt it?

### Command Prompt/Terminal logs (if existing)
Run haxelib run lime build html5 -final
Warning: Could not generate *.woff web font for "assets/fonts/vcr.ttf"
Warning: Could not generate *.woff web font for "assets/fonts/pixel.otf"
Warning: Could not generate *.woff web font for "/opt/hostedtoolcache/haxe/4.2.5/x64/lib/flixel/5,5,0/assets/fonts/nokiafc22.ttf"
Warning: Could not generate *.woff web font for "/opt/hostedtoolcache/haxe/4.2.5/x64/lib/flixel/5,5,0/assets/fonts/monsterrat.ttf"
source/Main.hx:10[8](https://github.com/Ant643/fnf/actions/runs/7697804514/job/20975611089#step:5:9): characters 3-4 : Unexpected (
Error: Process completed with exit code 1.
```


### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

only added and edited hmm


###  Haxe version

4.2.5

**Comment by Ant643** [comment]
yea this is the only issue I have left
