### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by TheKAPtain313** [ShadowMario/FNF-PsychEngine#14068]
### What feature do you want to get added on the **base** engine?

I think that in the settings you should add a fullscreen mode or press f11 to fullscreen

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by JHAM25** [comment]
I think it is implementing combining the Alt + Enter keys to go to full screen.

**Comment by Lorekeeper49** [comment]
Just fullscreen with Alt + Enter

**Comment by Jamextreme140** [comment]
That's unnecessary. Haxeflixel games has the "Alt + Enter" shortcut for Fullscreen by default.

**Comment by WoodsSilent05** [comment]
The only reason why this is a good idea, is because using alt + enter to fullscreen sometimes doesn't work first try, and it still registers the enter key plainly, which if you were in freeplay or storymode, could start a song/week accidentally.
