### ISSUE TITLE
How can I change the position of the opponent's notes from source code?

### ISSUE THREAD

**Issue by QuetzalcoutlDev** [ShadowMario/FNF-PsychEngine#14077]
### What is your question?

I've been trying to find out how to change the position of the opponent's notes from the source code for a while.

In Lua it is easy with
setPropertyFromGroup('opponentStrums', 0, 'x', -50);

But how can I do it from Haxe?

I'm making a mod from the source code without Lua

**Comment by Punkinator7** [comment]
if you are also looking to move it vertically, 
you would use
` opponentStrums.members[i].y += -50 ` 
instead inside that for loop
