### ISSUE TITLE
Mod Settings aren´t updating after changes

### ISSUE THREAD

**Issue by PHG29** [ShadowMario/FNF-PsychEngine#14074]
### Describe your bug here.

Whenever i change a value in mod settings and try to use getModSettings() on the object i changed, it doesnt update the value, the way i found to update it its actually moving the settings.json from the data folder for somewhere else, restarting song, putting the settings.json back at data folder and changing the 'value' of it to what you want, restarting again and then it will update to the value you put at the settings.json

Here: changing the value -
![Captura de Tela (41)](https://github.com/ShadowMario/FNF-PsychEngine/assets/97354032/293f8bd6-b5b3-4cd6-ba98-c0ce2b93143c)

Here: what getModSetting returns (Should be 'Português' instead of English) -
![Captura de Tela (42)](https://github.com/ShadowMario/FNF-PsychEngine/assets/97354032/54697e6d-d1df-489c-ae72-80c728027025)

Here: The json in case of doubts -
![Captura de Tela (43)](https://github.com/ShadowMario/FNF-PsychEngine/assets/97354032/cff24707-ce1b-4511-9cc6-01a8a475cda2)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ZeitHeld** [comment]
the mod is running globally though?

**Comment by PHG29** [comment]
> the mod is running globally though?

Yeah, it's a runsGlobally mod
