### ISSUE TITLE
Background animation

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#14073]
### Describe your problem here.

So i have a background that will occasionally have 3 asteroids float by a window in a space ship and a commet in the background 

how do i get the asteroids to spin and float by occasionally

same goes for the commet

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no i just added a song and finished charting it

**Comment by JHAM25** [comment]
Puedes utilizar doTweenAngle y doTweenY o manda las imágenes para intentar hacerlo

**Comment by SonicXFire1987** [comment]
> Puedes utilizar doTweenAngle y doTweenY o manda las imágenes para intentar hacerlo

Can you give me an example? Im kinda new to coding

**Comment by JHAM25** [comment]
Ta bien pero si tienes sprites de los asteroides y lo demás envialo para explicarte mientras voy hacerlos con píxeles

**Comment by JHAM25** [comment]
Asi lo hice un poco simple para que entiendas. El  número 0 hace la función de girar el número, 1 hace la función fe flotar y el 2 hace las dos anteriores.

https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/0b492e66-bc0f-4d65-9eb5-d52920a023aa

**Comment by JHAM25** [comment]
Y el códicódig

function onCreate()
    makeLuaSprite('fondo', '', 0, 0)
    makeGraphic('fondo', 1280, 720, '000000')
    addLuaSprite('fondo', true)
    setObjectCamera('fondo', 'camHUD')

    makeLuaSprite('0', 'num0', 100 ,100)
    setObjectCamera('0', 'Other')
    addLuaSprite('0', true)
    doTweenAngle('Angulo_0', '0', 0, 2)

    makeLuaSprite('1', 'num1', 300, 100)
    setObjectCamera('1', 'Other')
    addLuaSprite('1', true)
    doTweenY('Altura_1', '1', 80, 1)
    
    makeLuaSprite('2', 'num2', 500, 100)
    setObjectCamera('2', 'Other')
    addLuaSprite('2', true)
    doTweenY('Altura_2', '2', 80, 1)
    doTweenAngle('Angulo_2', '2', 0, 2)

end



function onTweenCompleted(tag)
    if tag == 'Angulo_0' then
    doTweenAngle('Angulo_0_2', '0', 360, 6)
    end
    if tag == 'Angulo_0_2' then
    doTweenAngle('Angulo_0', '0', 0, 6)
    end

    if tag == 'Altura_1' then
    doTweenY('Altura_1_2', '1', 120, 2)
    end
    if tag == 'Altura_1_2' then
    doTweenY('Altura_1', '1', 80, 2)
    end

    if tag == 'Altura_2' then
    doTweenY('Altura_2_2', '2', 120, 2)
    end
    if tag == 'Altura_2_2' then
    doTweenY('Altura_2', '2', 80, 2)
    end

    if tag == 'Angulo_2' then
    doTweenAngle('Angulo_2_2', '2', 360, 6)
    end
    if tag == 'Angulo_2_2' then
    doTweenAngle('Angulo_2', '2', 0, 6)
    end
end

**Comment by SonicXFire1987** [comment]
> Y el códicódig
> 
> function onCreate() makeLuaSprite('fondo', '', 0, 0) makeGraphic('fondo', 1280, 720, '000000') addLuaSprite('fondo', true) setObjectCamera('fondo', 'camHUD')
> 
> ```
> makeLuaSprite('0', 'num0', 100 ,100)
> setObjectCamera('0', 'Other')
> addLuaSprite('0', true)
> doTweenAngle('Angulo_0', '0', 0, 2)
> 
> makeLuaSprite('1', 'num1', 300, 100)
> setObjectCamera('1', 'Other')
> addLuaSprite('1', true)
> doTweenY('Altura_1', '1', 80, 1)
> 
> makeLuaSprite('2', 'num2', 500, 100)
> setObjectCamera('2', 'Other')
> addLuaSprite('2', true)
> doTweenY('Altura_2', '2', 80, 1)
> doTweenAngle('Angulo_2', '2', 0, 2)
> ```
> 
> end
> 
> function onTweenCompleted(tag) if tag == 'Angulo_0' then doTweenAngle('Angulo_0_2', '0', 360, 6) end if tag == 'Angulo_0_2' then doTweenAngle('Angulo_0', '0', 0, 6) end
> 
> ```
> if tag == 'Altura_1' then
> doTweenY('Altura_1_2', '1', 120, 2)
> end
> if tag == 'Altura_1_2' then
> doTweenY('Altura_1', '1', 80, 2)
> end
> 
> if tag == 'Altura_2' then
> doTweenY('Altura_2_2', '2', 120, 2)
> end
> if tag == 'Altura_2_2' then
> doTweenY('Altura_2', '2', 80, 2)
> end
> 
> if tag == 'Angulo_2' then
> doTweenAngle('Angulo_2_2', '2', 360, 6)
> end
> if tag == 'Angulo_2_2' then
> doTweenAngle('Angulo_2', '2', 0, 6)
> end
> ```
> 
> end

oooooh ok but one thing how do you get them to move across the screen and only do it every now and again kinda like the train in pico's stage unless the code is already there ill give it a try real quick

**Comment by SonicXFire1987** [comment]
another thing i need them to keep rotating the same direction

**Comment by SonicXFire1987** [comment]
ok nevermind i was able to make not in front

**Comment by JHAM25** [comment]
Para que se muevan en posicion X se utiliza doTweenX


function onCreate()
    makeLuaSprite('fondo', '', 0, 0)
    makeGraphic('fondo', 1280, 720, '000000')
    --addLuaSprite('fondo', true)
    setObjectCamera('fondo', 'camHUD')

    makeLuaSprite('0', 'num0', 100 ,300)
    setObjectCamera('0', 'Other')
    addLuaSprite('0', true)
    doTweenAngle('Angulo_0', '0', 0, 2)

    doTweenX('0_X', '0', 1300, math.random(4, 9))

    makeLuaSprite('1', 'num1', 300, 100)
    setObjectCamera('1', 'Other')
    addLuaSprite('1', true)
    doTweenY('Altura_1', '1', 80, 1)
    
    makeLuaSprite('2', 'num2', 500, 100)
    setObjectCamera('2', 'Other')
    addLuaSprite('2', true)
    doTweenY('Altura_2', '2', 80, 1)
    doTweenAngle('Angulo_2', '2', 0, 2)

end



function onTweenCompleted(tag)
    if tag == '0_X' then
        doTweenX('0_X_2', '0', 1300, getRandomFloat(2, 4))
    end
    if tag == '0_X_2' then
    doTweenX('0_X', '0', -10, 0.01)
    end



    if tag == 'Angulo_0' then
    doTweenAngle('Angulo_0_2', '0', 360, 6)
    end
    if tag == 'Angulo_0_2' then
    doTweenAngle('Angulo_0', '0', 0, 6)
    end

    if tag == 'Altura_1' then
    doTweenY('Altura_1_2', '1', 120, 2)
    end
    if tag == 'Altura_1_2' then
    doTweenY('Altura_1', '1', 80, 2)
    end

    if tag == 'Altura_2' then
    doTweenY('Altura_2_2', '2', 120, 2)
    end
    if tag == 'Altura_2_2' then
    doTweenY('Altura_2', '2', 80, 2)
    end

    if tag == 'Angulo_2' then
    doTweenAngle('Angulo_2_2', '2', 360, 6)
    end
    if tag == 'Angulo_2_2' then
    doTweenAngle('Angulo_2', '2', 0, 6)
    end
end

https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/8589da6c-0f33-489e-9d94-40d36bcbe23f



Y en este añadir un efecto como si estuviera mas cerca o lejos le puse una escala random pero es una idea si la quieres utilizar:

https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/6736d7ef-e63f-4a0f-bfcc-7dba7268c402

**Comment by JHAM25** [comment]
funciono?
