### ISSUE TITLE
Known Issues from Experimental Branch as of February

### ISSUE THREAD

**Issue by Raltyro** [ShadowMario/FNF-PsychEngine#14079]
- Ugh Hard Difficulty Chart is Ugh Easy Difficulty Chart
- GPU Caching broken for LoadingState (Re-uploading Bitmapdata from different thread to GPU shows up fail safe bitmapdata)

Github Issues
- PRs and Workflows are failing because of an error in PlayState for finishSong.bind code

**Comment by mcagabe19** [comment]
> * hxdiscordrpc disfunctions after reconnecting discord multiple times

externs as `@:native` ones
![Screenshot_20240201_184513_Discord](https://github.com/ShadowMario/FNF-PsychEngine/assets/82843871/726d3865-9afd-49aa-8a92-2223c778c8aa)

**Comment by Raltyro** [comment]
Yeah i'm removing that from the list, it could be my issue, thanks for lmk

**Comment by mcagabe19** [comment]
@Raltyro this is not only happens in arRPC I got same before it's a discord rpc issue even jigsaw says it
