### ISSUE TITLE
Activating shaders at specific step/beat

### ISSUE THREAD

**Issue by GamerIsNotEg** [ShadowMario/FNF-PsychEngine#14081]
### Describe your problem here.

Is there a way to activate shaders at a step/beat 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No I didn't edit the build (it's version 6.3 btw)

**Comment by Average-FNF-Modder** [comment]
Use function onStepHit() or onBeatHit() to count beats, the use the addLuaScript() function to add the script. Here's some example code:

function onStepHit()
if curStep == (321) then --when it does the thing
addLuaScript('AFM's Charts/hotlineVHS - copy.lua') --put the path to find your script and its name.
end
end

    You could make a custom folder for these shader scripts or just leave them in the open in your mod folder, just make sure to give the right path to find it. You should drop this new script into the song and it will add the shader script when specified. To remove the shader, use removeLuaScript() instead.
Hope this helped!

_-AFM_

**Comment by GamerIsNotEg** [comment]
Thank you so much this work!! :)
