### ISSUE TITLE
Scripts Run Globally When Not Told To.

### ISSUE THREAD

**Issue by Average-FNF-Modder** [ShadowMario/FNF-PsychEngine#14088]
### Describe your bug here.

My scripts from one mod are leaking over in all songs even though I have runsGlobally turned off in the mods Json. I tried redo it and saving, restarting the engine, loading the songs differently, and moving around scripts. I'm unsure of what to do.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, sure didn't.

**Comment by Porcupine2009** [comment]
Put the script you want to play in a certain song in that song's data folder.

For example, if you want a camcorder overlay script on the Dadbattle song but not the others, simply out your scriptname.lua file into assets\data\dad-battle. It should only work for that song. DO NOT PUT THE EVENTS INTO MODS/modnamehere/SCRIPTS, this will make it run globally even if "runGlobally" in pack.json is turned off.

**Comment by Average-FNF-Modder** [comment]
It shouldn't. It didn't do this previously, one day I just booted it and it randomly started doing that. Mod scripts should only affect the mod they are put into.
