### ISSUE TITLE
Any version 7.0 and over crashes for me

### ISSUE THREAD

**Issue by WhyHighHatt** [ShadowMario/FNF-PsychEngine#14089]
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/138333160/55b66aed-05bb-4984-92e3-fb4d2b5aadb3)
Anytime I use a build on a mod or psych itself and the build version is 7.0 or above it crashes and shows me the same error message. This has been happening for like months now and nobody I ask knows why, please help.!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Raltyro** [comment]
Check any charts if they have noteskin data or whatever set to anything that doesnt exists

**Comment by WhyHighHatt** [comment]
> Check any charts if they have noteskin data or whatever set to anything that doesnt exists

This happens on all builds even when I download it off of gb and play it with no mods it still crashes and shows me that error message.

**Comment by ShadowMario** [comment]
Need more information, what build are you using (x64 or x32), does it happen after any specific action or is it on init

**Comment by WhyHighHatt** [comment]
> Need more information, what build are you using (x64 or x32), does it happen after any specific action or is it on init
It happens when I use x64 and x32, and if it has to do with the notes it crashes, chart editor, just simply trying to load up a song, etc

**Comment by Raltyro** [comment]
can you upload your savedata here so we can look what may probably causes it

**Comment by WhyHighHatt** [comment]
> can you upload your savedata here so we can look what may probably causes it

Honestly, I forgot about this whole thing, and it sounds dumb but, idk how to do that 
...
