### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by yeawatevermark** [ShadowMario/FNF-PsychEngine#14084]
### Describe your problem here.

while compiling the engine (again) i got this error right here

C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
source/states/PlayState.hx:36: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
source/psychlua/FunkinLua.hx:16: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
source/states/PlayState.hx:113: characters 40-48 : Type not found : FlxSound

C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main>lime test windows
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
source/states/PlayState.hx:36: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
source/psychlua/FunkinLua.hx:16: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
C:\Users\Mateus\Documents\Friday Night Funkin'\FNF-PsychEngine-main\source\import.hx:47: characters 8-29 : Type not found : flixel.sound.FlxSound
source/states/PlayState.hx:113: characters 40-48 : Type not found : FlxSound

it is something kinda repeatful idk

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i was still compiling

**Comment by mcagabe19** [comment]
update ur flixel

**Comment by yeawatevermark** [comment]
> update ur flixel

not it shows this

source/states/PlayState.hx:36: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
source/psychlua/FunkinLua.hx:16: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
C:/HaxeToolkit/haxe/lib/flixel-addons/3,0,2/flixel/addons/transition/FlxTransitionableState.hx:81: lines 81-90 : Warning : switchTo is deprecated, use startOutro
source/states/PlayState.hx:3479: characters 51-67 : Type not found : FlxRuntimeShader

**Comment by mcagabe19** [comment]
update ur flixel-addons and flixel-ui

**Comment by yeawatevermark** [comment]
> update ur flixel-addons and flixel-ui

did not work

**Comment by mcagabe19** [comment]
do `haxelib update` then idk

**Comment by yeawatevermark** [comment]
> do `haxelib update` then idk

i were using it

**Comment by yeawatevermark** [comment]
i just found out that my vscode wasnt fully installed so i installed it fully and it worked :D sorry mcgabe19 for making you lose some time.
