### ISSUE TITLE
can someone help me with this error?

### ISSUE THREAD

**Issue by adamgamer12333** [ShadowMario/FNF-PsychEngine#14086]
### Describe your bug here.

im new to source, and i wanted to compile cause i have everything set, so i compiled and, i got 2 errors,
and i want someone to solve it and fix it for me.

### Command Prompt/Terminal logs (if existing)

```bash
source/PlayState.hx:1508: characters 3-8 : Unknown identifier : video
source/PlayState.hx:1509: characters 3-8 : Unknown identifier : video
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i edited freeplaystate and some options-states and even added a new state i guess

**Comment by nennneko5787** [comment]
Please show me the source code of PlayState.hx.

**Comment by 2JENO** [comment]
add this code on playstate.hx

``var video;``

but this is not stable solution.
need more infomations
