### ISSUE TITLE
I need help on this problem i just downloaded some mods and then appears this

### ISSUE THREAD

**Issue by ian82758** [ShadowMario/FNF-PsychEngine#14085]
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/158504639/08b39fa3-4ede-46e6-b80d-584c87c5f355)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i dont know

**Comment by ian82758** [comment]
helppp

**Comment by 2JENO** [comment]
bf.json is null, check that file
