### ISSUE TITLE
I got some error while compiling

### ISSUE THREAD

**Issue by BillyLOLwkwk** [ShadowMario/FNF-PsychEngine#14080]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/98211637/d12a985b-4b81-4982-abf9-e9ef57ea1649)

can someone try to help me out of this error :?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't edit anything yet

**Comment by mcagabe19** [comment]
haxelin install hxdiscord_rpc

**Comment by BillyLOLwkwk** [comment]
> haxelib install hxdiscord_rpc

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/98211637/bab09096-0ffa-4fca-a838-dce83da6210e)
Then i got this error. is there something that i miss ?

**Comment by 2JENO** [comment]
delete your build, and retry compile.
if not solved, check your vs code msvc

**Comment by 2JENO** [comment]
did you using x64?
