### ISSUE TITLE
Music Player BPM Incompatibility (0.7.3)

### ISSUE THREAD

**Issue by TH3L0AD3R** [ShadowMario/FNF-PsychEngine#14099]
### Describe your bug here.

When playing songs with non-integer BPMs (e.g. Nightmare Run, which has a BPM of 166.666) with the Music Player in the Freeplay menu, the instrumental stutters heavily and the vocals don't play at all (although this might be because I was using Voices-Player.ogg and Voices-Opponent.ogg, which the Music Player wouldn't recognize). In gameplay, the song plays normally with no issues.

https://github.com/ShadowMario/FNF-PsychEngine/assets/138751882/bf5b7acd-e368-4719-a6d1-08e3fd776a6b

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I've only imported a few character, song, and data files. Nothing code-wise has been changed.

**Comment by ShadowMario** [comment]
Fixed on the newest commits of experimental
