### ISSUE TITLE
Just transported to 7.0, how do I fix this problem?

### ISSUE THREAD

**Issue by HaydenGamingBack** [ShadowMario/FNF-PsychEngine#14096]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/158530872/dd4433e4-d078-42a6-a2f7-2c6572da6ce5)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by 2JENO** [comment]
did you update lib versions?
