### ISSUE TITLE
Lua's makeGraphic display is wrong

### ISSUE THREAD

**Issue by miyadora** [ShadowMario/FNF-PsychEngine#14093]
### Describe your problem here.

I am using the FNF PsychEngine source code, and the colors do not change even if I change the makeGraphic color in Lua.
Also, the transparency is not correct.
Is this due to a different version of Haxe?
FNF PsychEngine is 0.6.3.

https://github.com/ShadowMario/FNF-PsychEngine/assets/158581478/37d25a53-ab3f-4218-8ce7-cd21ccd1ef9f

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by miyadora** [comment]
As a postscript, makeGraphic is used for this flash process.
The same process is used for both, but the built one does not change color.

**Comment by Vortex2Oblivion** [comment]
You might need git hxcpp
```haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp```
If it complains about something not being built or something just say yes.

**Comment by miyadora** [comment]
Resolved!
Thank you!
