### ISSUE TITLE
entering freeplay menu gives null object reference

### ISSUE THREAD

**Issue by skidxml** [ShadowMario/FNF-PsychEngine#14090]
### Describe your problem here.

i compiled the engine from source, and got this error when entering freeplay:
![the image](https://github.com/ShadowMario/FNF-PsychEngine/assets/85322671/a7def8f3-f6be-4e9e-9426-c578c8e83b09)

i have made changes to the engine, but even when reverting them, it still happens

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

modified fpscounter.hx (seen in the image)

**Comment by Raltyro** [comment]
Do you have mods that have an character that doesnt have an icon

**Comment by skidxml** [comment]
> Do you have mods that have an character that doesnt have an icon

nope, no mods installed
