### ISSUE TITLE
I can't install this line "haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git"

### ISSUE THREAD

**Issue by BillyLOLwkwk** [ShadowMario/FNF-PsychEngine#14092]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/98211637/e058e594-3e59-4d9d-a674-597e9e400f40)

When i tried to run that command that thing just appear. Idk how to fix it but i have tried to do it many times but the result is still the same

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

NO

**Comment by ZanderRivera** [comment]
The same just happened for me today. The only work-around I did was NOT to install the git version of hxCodec. like
`haxelib install hxCodec`. Just that simple.
