### ISSUE TITLE
Dialogue Switches Sprite/"emotion" Randomly

### ISSUE THREAD

**Issue by DaGhostyDude** [ShadowMario/FNF-PsychEngine#1410]
### Describe your bug here.

When playing a Dialogue (in song/game) the order of the frames/Emotions becomes random.

Not sure if this happens to anyone else.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

only the mod folder...obviously

**Comment by SrtHero278** [comment]
This happens when the animation is set to something your character doesn't have. If your dialogue uses the talk animation (That's the default) but your character doesn't have an animation called talk, it will simply pick a random animation. I think it's for crash prevention.

**Comment by Orionkidgaming** [comment]
> This happens when the animation is set to something your character doesn't have. If your dialogue uses the talk animation (That's the default) but your character doesn't have an animation called talk, it will simply pick a random animation. I think it's for crash prevention.

true but you think he renamed the folder?

**Comment by ShadowMario** [comment]
Well, it is meant to be random, yeah.
