### ISSUE TITLE
(SOLVED!) Can't run "haxelib run lime test windows -64" because of hxCodec missing library

### ISSUE THREAD

**Issue by Stefan2008Git** [ShadowMario/FNF-PsychEngine#14102]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/308dbdc8-90c7-4af9-abd8-dd7a353d8306)
Title says (Ignore the latest hxCodec because i trought if i install the latest hxCodec it should fix this shit, but no, it's an same thing)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No?

**Comment by Stefan2008Git** [comment]
Someone said it can be the [hxCodec shit bug if you use hmm library](https://github.com/ShadowMario/FNF-PsychEngine/issues/12770), but uhhh, i tried that and it's an same thing

**Comment by mcagabe19** [comment]
downgrade haxe to 4.3.3 ot 4.3.2

**Comment by mcagabe19** [comment]
actually wait try `haxelib install --global hxCodec`

**Comment by Stefan2008Git** [comment]
> downgrade haxe to 4.3.3 or 4.3.2

I will try that method, but let me try the second method using the "haxelib --global"

**Comment by Stefan2008Git** [comment]
> haxelib install --global hxCodec

Already
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/ca7124e2-ab4e-4e88-af8d-9fde14aa168c)

**Comment by Stefan2008Git** [comment]
> > downgrade haxe to 4.3.3 or 4.3.2
> 
> I will try that method, but let me try the second method using the "haxelib --global"

Me when i got the same shit
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/4e4534a3-0f34-4768-80c0-fe43a405bb2d)
@mcagabe19

**Comment by Stefan2008Git** [comment]
> > > downgrade haxe to 4.3.3 or 4.3.2
> > 
> > 
> > I will try that method, but let me try the second method using the "haxelib --global"
> 
> Me when i got the same shit ![image](https://private-user-images.githubusercontent.com/126715034/302105862-4e4534a3-0f34-4768-80c0-fe43a405bb2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNTQ3NzQsIm5iZiI6MTcwNzA1NDQ3NCwicGF0aCI6Ii8xMjY3MTUwMzQvMzAyMTA1ODYyLTRlNDUzNGEzLTBmMzQtNDc2OC04MGMwLWZlNDNhNDA1YmIyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQxMzQ3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDFiYzVjNDgwOGE4ODQ4MWMwZTEwZDZmZmFjYmMyZDg1NWM0YTg3MGM5YmQxYjNkZWJhN2VhYTdjYzhmNmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XAd-k2NA8UEefZP4wg6hU3aznU2xDSDQvubiMv49-U0) @mcagabe19

Update: It's seems like i didn't added the correct libraries on correct path :skull:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/44416c72-64e6-42a2-b058-9ef1b5c01b04)
Thanks for help anyways @mcagabe19. I am gonna close this issue
