### ISSUE TITLE
compliling error

### ISSUE THREAD

**Issue by Miuthoi123** [ShadowMario/FNF-PsychEngine#14107]
### Describe your bug here.

help the bug

### Command Prompt/Terminal logs (if existing)

```bash
yes

source/states/PlayState.hx:1332: characters 3-50 : (?ignoreNoteOffset : Null<Bool>) -> Void should be () -> Void
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes

**Comment by KELOTOMU** [comment]
Can i see the code

**Comment by Miuthoi123** [comment]
> Can I see the code that u edited that could've made that error

here: 
![0001](https://github.com/ShadowMario/FNF-PsychEngine/assets/117433468/089a5d09-8479-4016-836f-ccf2a57a82a4)
![0002](https://github.com/ShadowMario/FNF-PsychEngine/assets/117433468/ee5fc63f-05af-41c6-92d3-89a5f2d838a0)

img 1 is from startSong()
img 1 is from finishSong() because startSong() having this FlxG.sound.music.onComplete = finishSong.bind();

**Comment by KELOTOMU** [comment]
`FlxG.sound.music.onComplete = finishSong(_)` Ignored optional arguments in a binded function should be replaced with a "_" depends on wat I saw in the wiki.

**Comment by mcagabe19** [comment]
the fix is `FlxG.sound.music.onComplete = () -> finishSong();`

**Comment by Miuthoi123** [comment]
> the fix is `FlxG.sound.music.onComplete = () -> finishSong();`

fuck the real fix is: FlxG.sound.music.onComplete = () -> finishSong.bind(true);
