### ISSUE TITLE
Character image wont work.

### ISSUE THREAD

**Issue by BBJAKABucketBoyJay** [ShadowMario/FNF-PsychEngine#14111]
### Describe your problem here.

When i compile my mod, this happens

49d10c9b_OES_stencil1.obj : error LNK2011: precompiled object not linked in; image may not run
  Hint on symbols that are defined and could potentially match:
    __@@_PchSym_@00@UfhvihUtqfhgUwldmolzwhUumuRkhbxsvmtrmvRnzrmUumuRkhbxsvmtrmvRnzrmUvckligUivovzhvUdrmwldhUlyqUlyqUnhexBJGERmxUPPkxsUifmgrnvUscxkkOlyq@link43c6d4f657a5b6a51de68b4e485915d9
    __@@_PchSym_@00@UfhvihUtqfhgUwvhpglkUumuRkhbxsvmtrmvRnzrmUumuRkhbxsvmtrmvRnzrmUvckligUivovzhvUdrmwldhUlyqUlyqUnhexBJGERmxUPPkxsUszcvUscxkkOlyq@linkbc5602acfc0388c25eb7b5b05b7836b0
ApplicationMain.exe : fatal error LNK1120: 1 unresolved externals

My character is in FNF-PsychEngine-main\FNF-PsychEngine-main\assets\shared\images\characters

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by therealhrzn** [comment]
try deleting the export folder

**Comment by therealhrzn** [comment]
and compile again
