### ISSUE TITLE
Could not load module lime@lime_application_create__prime

### ISSUE THREAD

**Issue by StjepanGamer** [ShadowMario/FNF-PsychEngine#14118]
### Describe your bug here.

Hey guys! As you can see. After I downloaded the new update of Psych Engine, I decided it will be best to extract all of files into the screen. And... it doesnt go well...
Preview of this error:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/109145730/81d03e1e-8ba0-4490-8f6d-bb9f32544508)
Any questions?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didnt

**Comment by mcagabe19** [comment]
corrupted ndll or install 64-bit version if u have 64-bit windows

**Comment by StjepanGamer** [comment]
> corrupted ndll or install 64-bit version if u have 64-bit windows

It works a lot. Thanks!
