### ISSUE TITLE
I cant get the notes to load

### ISSUE THREAD

**Issue by StellR06** [ShadowMario/FNF-PsychEngine#14113]
### Describe your bug here.

options/NotesSubState.hx (line 630)
options/NotesSubState.hx (line 143)
options/OptionsState.hx (line 17)
options/OptionsState.hx (line 97)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

so, like, whenever the game tries to load the notes (even from the options menu) it just gives this crash. I cant for the life of me figure out why this is happening or why it only happens with 0.7 builds. 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I didnt modify anything. this is from a fresh download

**Comment by KELOTOMU** [comment]
0.7 is buggy, use 0.7.1h or later versions

**Comment by StellR06** [comment]
> 0.7 is buggy, use 0.7.1h or later versions

i tried that, but every version past 0.7 has the same problem

**Comment by 2JENO** [comment]
check suffix or check assets dir
