### ISSUE TITLE
non playable characters turn into playable characters when saved

### ISSUE THREAD

**Issue by baja-snick** [ShadowMario/FNF-PsychEngine#14116]
### Describe your bug here.

I'm trying to save a character as a nonplayable character but it keeps reverting to a playable character.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
That checkbox is only visual and it does not impact gameplay.
