### ISSUE TITLE
Game wont open

### ISSUE THREAD

**Issue by Confuddled** [ShadowMario/FNF-PsychEngine#14115]
### Describe your bug here.

every time i open the game it crashes (64x)
This happens on any psych engine ive tried to delete the game and its appdata and reinstall it

### Command Prompt/Terminal logs (if existing)

```bash
backend/Paths.hx (line 275)
backend/Paths.hx (line 247)
states/TitleState.hx (line 209)
states/TitleState.hx (line 170)
flixel/util/FlxTimer.hx (line 205)
flixel/util/FlxTimer.hx (line 295)
flixel/FlxGame.hx (line 750)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.
Yes I added a new week but the week had no songs

**Comment by 2JENO** [comment]
check lib versions

**Comment by 2JENO** [comment]
example: haxe, flixel, flixel-addons

**Comment by Confuddled** [comment]
flixel addons = 3.2.1   flixel = 5.6.1 and haxe = it said no such project

**Comment by Confuddled** [comment]
also i was able to launch the game before but now any time i launch any fnf psych mod it also crashes

**Comment by Confuddled** [comment]
ive deleted all of my builds of psych and im tryna play marios madness and it crashes too

**Comment by Confuddled** [comment]
All i had to do was extract psych in a new folder
thanks tho
