### ISSUE TITLE
How can I freeze the timer??

### ISSUE THREAD

**Issue by AnotherPlayer8** [ShadowMario/FNF-PsychEngine#14114]
### Describe your problem here.

I want to make a script that stops the timer in a section of the song (I am making this for fun, but also learning in case I make a mod in the future)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

_No_

**Comment by Jamextreme140** [comment]
As far as I know, you can't freeze (pause) the timer, either in Lua or Haxe.

**Comment by AnotherPlayer8** [comment]
> As far as I know, you can't freeze (pause) the timer, either in Lua or Haxe.

Then how was the end of demise (from mario's madness v2) made??
If you have not seen it, the timer stops and shakes at 3 seconds left
