### ISSUE TITLE
Windows Build Error

### ISSUE THREAD

**Issue by NotSomeBlox** [ShadowMario/FNF-PsychEngine#14129]
### Describe your bug here.

Unable to build Psych 0.7.3 due to haxelib "not being an external program file"

### Command Prompt/Terminal logs (if existing)

```bash
haxelib is not an external or program batch file
"my best remeberance"
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by cursedUs64-git** [comment]
Duh, install Haxe, dingus

**Comment by Stefan2008Git** [comment]
> Duh, install Haxe, dingus

Or just reinstall the entire Haxe?

**Comment by Hackx2** [comment]
bro didnt install haxe
