### ISSUE TITLE
Character XML Error

### ISSUE THREAD

**Issue by KirbG0** [ShadowMario/FNF-PsychEngine#14120]
### Describe your bug here.

Whenever i was finished making a spritesheet. I added it to my mod and it just crashed with the error below. please help!

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 217)
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 117)
C:\HaxeToolkit\haxe\std/Xml.hx (line 122)
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
editors/CharacterEditorState.hx (line 840)
editors/CharacterEditorState.hx (line 520)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: haxe.xml.XmlParserException: Expected node name at line 2 char 2
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Jamextreme140** [comment]
How it is your Spritesheet XML file?

Just asking to confirm.
