### ISSUE TITLE
fatal error LNK1120: 1 unresolved externals

### ISSUE THREAD

**Issue by mahikotahi** [ShadowMario/FNF-PsychEngine#14128]
### Describe your bug here.

It happens when i compiled and i honestly do not know what to do about it, its not very descriptive

### Command Prompt/Terminal logs (if existing)

```bash
Link: ApplicationMain.exe
   Creating library ApplicationMain.lib and object ApplicationMain.exp
0404b287_PixelSplashShader.obj : error LNK2011: precompiled object not linked in; image may not run
  Hint on symbols that are defined and could potentially match:
    __@@_PchSym_@00@UfhvihUkligrUwldmolzwhUumuRehtfbivylimRhlfixvUvckligUivovzhvUdrmwldhUlyqUlyqUnhexBJGERmxUPPkxsUszcvUscxkkOlyq@linkf3886a9e7db8e041acff8161de3191df
    __@@_PchSym_@00@UfhvihUkligrUwldmolzwhUumuRkhbxsvmtrmvRAOHODUvckligUivovzhvUdrmwldhUlyqUlyqUnhexBJGERmxUPPkxsUifmgrnvUscxkkOlyq@link9abc84824ad6086598f9418c37eef0d8
ApplicationMain.exe : fatal error LNK1120: 1 unresolved externals
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not Much, Just added a Version Display for the mod

**Comment by mahikotahi** [comment]
just needed to recompile

**Comment by WolfyTail** [comment]
I tried to compile again and didn't work
