### ISSUE TITLE
BF can't jump. :(

### ISSUE THREAD

**Issue by Your-Local-LordXSimp** [ShadowMario/FNF-PsychEngine#14123]
### Describe your problem here.

I'm doing my own thing for Powerdown V2 and BF won't jump when I press space.

`function onCreate()
	makeAnimatedLuaSprite('BFjump', 'MX/MM_Boyfriend_Assets_jump', 796, 220)
    setProperty('BFjump.visible', false)
    addLuaSprite('BFjump', true)

	if getPropertyFromClass('flixel.FlxG', 'keys.pressed.SPACE') then
		setProperty('BFjump.visible', true)
		addAnimationByPrefix('BFjump', 'heJump', 'JUMP0', 24, true)
		doTweenY('BFjumpA', 'BFjump', 230, 1, 'linear')
		setTimer('land', 1)
	end
end

function onTimerCompleted(tag)
	if tag == 'land' then
		setProperty('BFjump.visible', false)
		addAnimationByPrefix('BFjump', 'heJump', 'JUMPLAND0', 24, true)
		doTweenY('BFjumpA', 'BFjump', 220, 1, 'linear')
	end
end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I'm doing my own thing for Powerdown V2 and I'm doing it in the mods folder

**Comment by Meme1079** [comment]
Put it on `onUpdate()` callback, duh

```lua
function onUpdate(elapsed)
     if getPropertyFromClass('flixel.FlxG', 'keys.pressed.SPACE') then
          setProperty('BFjump.visible', true)
          addAnimationByPrefix('BFjump', 'heJump', 'JUMP0', 24, true)
          doTweenY('BFjumpA', 'BFjump', 230, 1, 'linear')
          setTimer('land', 1)
     end
end
```
