### ISSUE TITLE
HELP IN ON MAC: The application “PsychEngine” can’t be opened. 

### ISSUE THREAD

**Issue by kenshinuno** [ShadowMario/FNF-PsychEngine#14134]
### Describe your problem here.

when i try to open the app, "The application “PsychEngine” can’t be opened." comes up

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

nope, just trying to open the engine

**Comment by mcagabe19** [comment]
build psych in ur mac actions only builds for 12

**Comment by AFKenny** [comment]
can you explain in further detail? this might help me, thank you
