### ISSUE TITLE
TitleState Alphabet creates null error sometimes after Restart

### ISSUE THREAD

**Issue by KirbyKid256** [ShadowMario/FNF-PsychEngine#14139]
### Describe your bug here.

On my own fork of Psych Engine, I've been testing a remake of Psych 0.7.3 Menus in Lua. For that pack, I've set it to restart the game when changed. However, sometimes I get an Null Object Reference when resetting the game rooting to `Alphabet.hx` and `FlxAtlasFrames.hx`. I thought it was something I broke or I had the wrong library versions, until I tested this bug in Psych Engine v0.7.3 with [3 Hour Plumber](https://gamebanana.com/mods/407751) which also resets the game. Turning the mod on and off multiple times and resetting the game, I have gotten the same error with this as well.

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/frames/FlxAtlasFrames.hx (line 401)
flixel/graphics/frames/FlxAtlasFrames.hx (line 247)
objects/Alphabet.hx (line 420)
objects/Alphabet.hx (line 348)
C:\HaxeToolkit\haxe\std/cpp/_std/Type.hx (line 90)
flixel/group/FlxGroup.hx (line 338)
objects/Alphabet.hx (line 218)
objects/Alphabet.hx (line 85)
objects/Alphabet.hx (line 37)
states/TitleState.hx (line 495)
states/TitleState.hx (line 552)
backend/MusicBeatState.hx (line 177)
backend/MusicBeatState.hx (line 64)
states/TitleState.hx (line 488)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Stefan2008Git** [comment]
That's an engine issue during the broken alphabet code
