### ISSUE TITLE
Lua doesnt update in real time

### ISSUE THREAD

**Issue by PersonNanoexe** [ShadowMario/FNF-PsychEngine#1413]
### Describe your problem here.

The game doesnt update bg elements in real time. I have to compile every time if i want the bg to change, which makes it annoying and tedious to change offsets and add new elements

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited the source code originally to add a new stage, later on decided to make it in lua so i can put everything in the mods folder, i put the stage code in comments, and then started working on the lua stage

**Comment by ShadowMario** [comment]
??????
Lua doesn't require compiling, you're changing the wrong .lua file (Probably the one inside main folder instead of export.
