### ISSUE TITLE
FlxAnimate importing problem

### ISSUE THREAD

**Issue by Stefan2008Git** [ShadowMario/FNF-PsychEngine#14136]
### Describe your bug here.

I imported everything from latest release of PE, but i am still getting this "Type not found" every single time
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/00a220e2-ea0b-4769-89e7-80f80be2246f)

### Command Prompt/Terminal logs (if existing)

```bash
`source/psychlua/ModchartSprite.hx:4: characters 30-40 : Type not found : FlxAnimate`
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Just importing new shits from latest release to my modifed PE 0.7.1h fork

**Comment by Chidubemmo** [comment]
How did you fix it

**Comment by Stefan2008Git** [comment]
> How did you fix it

I dunno. It fixed by self?

**Comment by Chidubemmo** [comment]
I hav ethe same problem. I'm going to kill muself
