### ISSUE TITLE
Add a setting for sound (exclusively for *NIX based systems)

### ISSUE THREAD

**Issue by cursedUs64-git** [ShadowMario/FNF-PsychEngine#14133]
### What feature do you want to get added on the **base** engine?

I use (arch) linux, (btw) and there should be some options for choosing which audio helper should you use. For example, ALSA, PipeWire, Pulseaudio, etc. These three are the main that alot of people use. I use ALSA,
This should be implemented or else if people use pulse and ALSA together, it might be a conflict and no sound at last.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by mcagabe19** [comment]
not releated to psych engine open issue to lime

**Comment by Average-FNF-Modder** [comment]
Bruh really put 'proper credit that was forgotten.'
