### ISSUE TITLE
HScript not found / 0.7.1

### ISSUE THREAD

**Issue by Edugamen** [ShadowMario/FNF-PsychEngine#14135]
### Describe your bug here.

When I compiled I got an error saying type not found but I already have everything about the Haxe extensions installed

### Command Prompt/Terminal logs (if existing)

```bash
source/states/PlayState.hx:107: characters 32-39 : Type not found : HScript
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by qbocat** [comment]
could you fix it?
