### ISSUE TITLE
Psych "Type not found : TeaCall" Building Issue

### ISSUE THREAD

**Issue by TheDovah10** [ShadowMario/FNF-PsychEngine#14147]
### Describe your problem here.

When building from source, I run into the issue "source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall", which prematurely ends the compiler. I can't find anything about this online, so any help help would be appreciated.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Hackx2** [comment]
I haven't worked with this version of psych engine, but this might help.
```haxe
haxelib install SScript 8.1.6
```
or
```haxe
haxelib install SScript 10.0.618
```

**Comment by miao1916** [comment]
i also had this issue you gotta change all the instances of TeaCall with Tea in the HScript.hx

**Comment by Hackx2** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by davydpetrov** [comment]
> i also had this issue you gotta change all the instances of TeaCall with Tea in the HScript.hx

this helped me please pin as answer

**Comment by lemonie1** [comment]
What instances do i delete?

**Comment by TheModsMan** [comment]
But how do you change instances to tea call for tea on HScript.hx?

**Comment by chrisdoesstuff69** [comment]
i also had this issue you gotta change all the instances of TeaCall with Tea in the HScript.hx how tf do you do that

**Comment by miao1916** [comment]
> i also had this issue you gotta change all the instances of TeaCall with Tea in the HScript.hx how tf do you do that

you search for the file inside your game folder, you open it with a software like visual studio code, you use the built in search tool in vs code to look for all the instances of TeaCall and you simply replace them with the search tool u just used remember to replace TeaCall with Tea

**Comment by TheSpiralOfPowah** [comment]
> i also had this issue you gotta change all the instances of TeaCall with Tea in the HScript.hx

That somewhat worked, but now it's giving me this error:
```
source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
```

**Comment by AbyssalRuv** [comment]
> ###
> [Feb 14, 2024](#issuecomment-1944134393)

what does this mean, do i change tea to teacall?

**Comment by megalives717** [comment]
not working please help
