### ISSUE TITLE
Issue with custom backgrounds

### ISSUE THREAD

**Issue by miao1916** [ShadowMario/FNF-PsychEngine#14143]
### Describe your problem here.

so i added some new backgrounds to the game and it all looks fine since i get 0 errors when compiling the game and 0 inside (even when i put my backgrounds) but when i change the background to one of mines it becomes fully black (i tried recompiling the game alot of times but it always appears black) 
![Screenshot 2024-02-13 223952](https://github.com/ShadowMario/FNF-PsychEngine/assets/159768550/e6b297d7-1e1b-4b41-8260-3c32754647b4)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i edited the playstate to add my backgrounds and added the hx and json files for my backgrounds and i added the folders with the backgrounds in \assets\week_assets\ i also modified the credits hx file to put some custom credits

**Comment by Hackx2** [comment]
where did you put the image?

**Comment by miao1916** [comment]
as i said i put the images in the \assets\week_assets\ in some new folders i made
