### ISSUE TITLE
source/psychlua/HScript.hx:295: characters 89-96 : Type not found : TeaCall

### ISSUE THREAD

**Issue by Miuthoi123** [ShadowMario/FNF-PsychEngine#14142]
### Describe your problem here.

i compiling game and error appers:

`source/psychlua/HScript.hx:295: characters 89-96 : Type not found : TeaCall`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by boynfrienddv** [comment]
same

**Comment by KirbyKid256** [comment]
You need to use `haxelib install SScript 8.1.6` because SScript got an update recently that breaks Psych Engine at the moment. And it's not just `Type not found : TeaCall`, it seems to affect HScript mods too

**Comment by Miuthoi123** [comment]
> You need to use `haxelib install SScript 8.1.6` because SScript got an update recently that breaks Psych Engine at the moment. And it's not just `Type not found : TeaCall`, it seems to affect HScript mods too

no, i fix this complete by replace `TeaCall` to `Tea` in `HScript.hx`
