### ISSUE TITLE
(Another) compiling error

### ISSUE THREAD

**Issue by Fellegend** [ShadowMario/FNF-PsychEngine#14149]
### Describe your problem here.

I tried to compile the game and I got this error message:
C:/haxelib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat should be declared with 'override' since it is inherited from superclass flixel.graphics.frames.FlxAtlasFrames
C:/haxelib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat overrides parent
class with different or incomplete type
C:/haxelib/flixel/5,5,0/flixel/graphics/frames/FlxAtlasFrames.hx:457: characters 18-24 : ... Base field is defined here
C:/haxelib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : ... Different number of function arguments
source/backend/Paths.hx:605: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)
source/objects/Character.hx:304: characters 87-101 : flxanimate.animate.FlxAnim has no field lastPlayedAnim
source/objects/Character.hx:335: characters 20-26 : flxanimate.animate.FlxAnim has no field resume

What should I do?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Only the folder name

**Comment by Stefan2008Git** [comment]
Use the @ShadowMario's git of FlxAnimate

**Comment by Fellegend** [comment]
wdym?

**Comment by CobaltBar** [comment]
run `haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev`

**Comment by Fellegend** [comment]
it worked!! thanks :>
