### ISSUE TITLE
Differentiation for if a note starts off a sustain or not. 'isParent', type thing.

### ISSUE THREAD

**Issue by Average-FNF-Modder** [ShadowMario/FNF-PsychEngine#14146]
### What feature do you want to get added on the **base** engine?

For 'function opponentNoteHit()' and 'goodNoteHit()' You have a variable to tell you if it's a sustain note or not, right? But the parent note hit isn't a sustain note so there are certain scenario's you can't account for when making code based on if note is a sustain or not, so that you can change if you want the parent note to be a part of the effect or not. So, I suggest either an 'isParent' variable or another tier in the 'isSustain' variable so that it can either be 1, 2, or 3, something like that, that allows the engine to differentiate notes that start a hold.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Noobz4Life** [comment]
`local isParent = (getPropertyFromGroup("notes", noteID, "tail.length") ~= 0)`

**Comment by Average-FNF-Modder** [comment]
Oh shit really? Thanks. Now I'm thinking tail.length being a thing could do with some documentation, but cool that it exists.)
