### ISSUE TITLE
Psych Engine has A Virus?

### ISSUE THREAD

**Issue by Lunista** [ShadowMario/FNF-PsychEngine#14151]
### Describe your problem here.

I think that this engine of Friday Night Funkin has a virus. Because when I try to open it, it says:

Windows Protected Your PC 
If you run this program, It could occur problems in your PC.

What should I do??? :(  

Or if you have a safe way to install it, please share with me.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not changed anything in this build.

**Comment by ParaMattKoopa** [comment]
click more then 'run anyway'
and no, it isn't a virus.

**Comment by CobaltBar** [comment]
This ain't a virus its FOSS software

and the popup is because it isn't by microsoft
