### ISSUE TITLE
Lua Tweening

### ISSUE THREAD

**Issue by KELOTOMU** [ShadowMario/FNF-PsychEngine#14153]
### What feature do you want to get added on the **base** engine?

Can you add a new Lua function called `doTweenScale()` since scale tweens are pretty common. This function will just be like the doTweenX or doTweenY. There will be a new parameter called "axis", its value(String) can either be "X", "Y", or "XY"(default). If you don't want axis parameter to be added, then I guess you could do `doTweenScaleX, doTweenScaleY`

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
[It's in the wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers#dotweenxtagstring-varsstring-valuedynamic-durationfloat-easestring)
