### ISSUE TITLE
Question about XY Positioning

### ISSUE THREAD

**Issue by MightyTheArmiddilo** [ShadowMario/FNF-PsychEngine#14155]
### What is your question?

I'm trying to make a thing with moving the notes and it's really frustrating considering I don't know the exact XY positioning for the HUD, like for example, I'm used to 0,0 being in the middle, but here, 0,0 is basically above the top, and it feels like when I try to do a negative X value, it goes to the right, I'm used to it going to the left, same happens with Y positioning, so I'd like a bit of an explanation about how the XY positioning works.

**Comment by mcagabe19** [comment]
https://en.m.wikipedia.org/wiki/Coordinate_system

**Comment by MightyTheArmiddilo** [comment]
Found out the XY coordinate plane by tweening a note to 0, 0. Thanks for your help anyway.
