### ISSUE TITLE
Is there a way i can play a cutscene video when the game first opens

### ISSUE THREAD

**Issue by ThatXS1Guy** [ShadowMario/FNF-PsychEngine#14163]
### What is your question?

For the mod i am making i want to have it where when you open the game, the first thing it does is play the cutscene, then it continues on with the game, anyone know how to do this?

### Source or LUA

source

**Comment by WolfyTail** [comment]
@ShadowMario WHY DO YOU CLOSE THE ISSUES WITHOUT SAYING ANYTHING 😭😭😭
