### ISSUE TITLE
I keep getting this null error

### ISSUE THREAD

**Issue by RosiePetals** [ShadowMario/FNF-PsychEngine#14160]
### Describe your problem here.

Hello! So I was on my way to do a doki doki takeover cover and put a psych port of one in the mods file (this port here to be exact https://www.youtube.com/watch?v=MBJJ-1eag74) and for whatever reason I keep receiving this error:

flixel/animation/FlxAnimationController.hx (line 739)
states/TitleState.hx (line 264)
states/TitleState.hx (line 170)
flixel/util/FlxTimer.hx (line 205)
flixel/util/FlxTimer.hx (line 295)
flixel/FlxGame.hx (line 750)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

I did the exact same thing with an older port and got no error, so I'm kinda confused. I also tried going into the ports 'mods' folder and taking that and putting it into psychengine>mods>modtemplate>my mod but instead it just loaded in all glitchy. I'm using version 7.3 btw and I extracted everything.

also sorry if this makes no sense i'm not the best at explaining stuff  

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by meowgoober** [comment]
@RosiePetals DID YOU EDIT TE BUIO- i meant did you edit the build. caps lock sorry
