### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by VIRUSnik00** [ShadowMario/FNF-PsychEngine#14166]
### Describe your bug here.

The background is not displayed, although everything is written as it should
![2024-02-18_15-51-55](https://github.com/ShadowMario/FNF-PsychEngine/assets/156318515/ddeb0d4f-59b1-44f2-a5a8-7885e9e5ba7a)
![2024-02-18_15-54-35](https://github.com/ShadowMario/FNF-PsychEngine/assets/156318515/36041835-3440-4931-b577-837174837c62)

### Are you modding a build from source or with Lua?
Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Draconic-Hybrid** [comment]
Did you fiddle with the position of the sprites in `makeLuaSprite`? At `0, 0`, they're in the far top left. It could also be that the size of the sprite is too small to see.

**Comment by Draconic-Hybrid** [comment]
What're the file types of the bgs?
