### ISSUE TITLE
I can't compile because of something about the states

### ISSUE THREAD

**Issue by Felixelpapu25** [ShadowMario/FNF-PsychEngine#14169]
### Describe your problem here.   
source/editors/MasterEditorMenu.hx:132: characters 4-17 : Type not found : FreeplayState
source/MainMenuState.hx:169: characters 7-20 : Type not found : FreeplayState
source/MainMenuState.hx:237: characters 42-55 : Type not found : FreeplayState
source/ModsMenuState.hx:489: characters 8-21 : Type not found : FreeplayState
source/StoryMenuState.hx:373: characters 5-18 : Type not found : FreeplayState
source/PlayState.hx:4047: characters 36-49 : Type not found : FreeplayState
source/FunkinLua.hx:1574: characters 36-49 : Type not found : FreeplayState
source/PauseSubState.hx:307: characters 38-51 : Type not found : FreeplayState
source/GameOverSubstate.hx:101: characters 36-49 : Type not found : FreeplayState

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by InfinityAX** [comment]
It looks like you deleted FreeplayState.hx

**Comment by Stefan2008Git** [comment]
Missing imported class name from your edited source code
