### ISSUE TITLE
BF Turns black whenever i use "Change Character" event.

### ISSUE THREAD

**Issue by TommykairaXVI** [ShadowMario/FNF-PsychEngine#14165]
### Describe your bug here.

whenever i use this event, even if i choose the opponent or gf to change, it always end up bf being black. Nothing is changing except bf.

![2024-02-18_09-54-20](https://github.com/ShadowMario/FNF-PsychEngine/assets/135838252/1bc39592-e05d-46cd-a225-938c823e97c8)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
This means the character you changed to is invalid.
