### ISSUE TITLE
how do you make it so a song never ends

### ISSUE THREAD

**Issue by SlushieDrawzCoolDrawingX480** [ShadowMario/FNF-PsychEngine#14162]
### What is your question?

im making a custom menu and i need it so a song never ends, also i need something that disables the pause screen

**Comment by MightyTheArmiddilo** [comment]
I’m pretty sure the Main Menu State file could help with the music, and I’m pretty sure with lua you can stop pausing. It’s something close to this but I’m not at a computer right now:

function onPause()
        function_stop
end

I’m pretty sure that’s how it goes, but I may be wrong.

**Comment by MightyTheArmiddilo** [comment]
Just looked at code that I made myself that works, it’s actually:

function onPause()
return Function_Stop
end
