### ISSUE TITLE
Cheems and Friends isn't credited correctly (no not the icon)

### ISSUE THREAD

**Issue by cyberaspect** [ShadowMario/FNF-PsychEngine#14168]
### Describe your bug here.

The link for Cheems and Friends (creator of FlxAnimate) leads to a [twitter page](https://twitter.com/CheemsnFriendos) that just doesn't exist. Not suspended, but gone... poof! Judging by the lack of icon I guess whoever did this was in a rush and it was just an oversight... just wanted to let you know :)

PS: Is this considered a bug report of missing documentation?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by ShadowMario** [comment]
The account works for me 
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/6790e95b-debf-482f-9555-c04d381e5a52)
