### ISSUE TITLE
version 0.6.3 has no sound

### ISSUE THREAD

**Issue by randomslovakguy** [ShadowMario/FNF-PsychEngine#14167]
### Describe your bug here.

when i try to play in any of older builds of psych engine, it has no sound! please help :(

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
Version 0.6.3 is not supported anymore
