### ISSUE TITLE
Unable to access debug menu in latest version of psych engine 

### ISSUE THREAD

**Issue by CraftyIsHere** [ShadowMario/FNF-PsychEngine#14174]
### Describe your problem here.

I'm not sure if the button has changed but neither 7 nor 8 do anything on any menu. is this a bug or has a new key been assigned to the debug menus? 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Completely untouched fresh download

**Comment by mcagabe19** [comment]
these are only at debug builds use Character Editor from Editors instead

**Comment by CraftyIsHere** [comment]
Oh ok. Thanks for the help!
