### ISSUE TITLE
[0.7.3] The Add Camera Zoom event is inconsistent

### ISSUE THREAD

**Issue by Draconic-Hybrid** [ShadowMario/FNF-PsychEngine#14171]
### Describe your bug here.

The `Add Camera Zoom` has varying effects. When used on a song I made with this update, the camera zooms, and gets stuck. It will keep zooming in and not returning to normal.

However, when used on a song I made when the engine was still just in 0.6.x, the effect works fine, it zooms, and returns to normal. 

Both the Chart Editor and using a `script.lua` have this effect.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just pure Lua

**Comment by ShadowMario** [comment]
If it gets stuck, it's because `camZooming` has been set to false or the opponent didn't sing a note yet
