### ISSUE TITLE
Lag spikes

### ISSUE THREAD

**Issue by Shadowhyper4925** [ShadowMario/FNF-PsychEngine#14176]
### Describe your problem here.

I had been having random lag spikes on version 0.7h, i did not had them before when using it, but they somehow appeared out of nowhere, older compiled versions are working fine.
The drops were from 240 to 220-228 or even lower.

Tried porting onto newer version (0.7.3), same result.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, made some optimizations and added/removed some things, that's it.

**Comment by Stefan2008Git** [comment]
Is your device with bad specifications or engine reason. I don't had any lag spikes in my modified Psych 0.7.1h fork

**Comment by Shadowhyper4925** [comment]
Fixed
Some libraries were too new for my engine, which had been making those lag spikes.
Will close this issue.

**Comment by Stefan2008Git** [comment]
> Fixed Some libraries were too new for my engine, which had been making those lag spikes. Will close this issue.

Probably
