### ISSUE TITLE
dialogue script missing

### ISSUE THREAD

**Issue by MikeBisasam** [ShadowMario/FNF-PsychEngine#14179]
### What needs to be documented?

You cannot download the dialogue script anymore, please fix, thanks.
![psych1](https://github.com/ShadowMario/FNF-PsychEngine/assets/160781418/f2f13447-caae-4f18-b4b3-99755d753e67)

**Comment by JHOSEPEMC** [comment]
local allowCountdown = false
function onStartCountdown()
	-- Block the first countdown and start a timer of 0.8 seconds to play the dialogue
	if not allowCountdown and isStoryMode and not seenCutscene then
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('dialogue', 'breakfast');
	end
end

-- Dialogue (When a dialogue is finished, it calls startCountdown again)
function onNextDialogue(count)
	-- triggered when the next dialogue line starts, 'line' starts with 1
end

function onSkipDialogue(count)
	-- triggered when you press Enter and skip a dialogue line that was still being typed, dialogue line starts with 1
end


Aqui ta?

no ce , lo encontré en los archivos de un mod que hice hace tiempo :v
