### ISSUE TITLE
Could not load module lime@lime_application_create__prime

### ISSUE THREAD

**Issue by LKenedy12** [ShadowMario/FNF-PsychEngine#14175]
### Describe your bug here.

I wanted to play a mod but wanted to play the game first. BUT it said the message instead of the game 
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/160553261/2581b892-8943-485b-aab5-e4bcc0949b4e)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I got it and it said the message when opened

**Comment by mcagabe19** [comment]
corrupted `lime.ndll` or if you installed 32-bit install 64-bit

**Comment by LKenedy12** [comment]
> corrupted `lime.ndll` or if you installed 32-bit install 64-bit

I installed 64-bit.
