### ISSUE TITLE
Building Error (source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall)

### ISSUE THREAD

**Issue by DawidEnderman** [ShadowMario/FNF-PsychEngine#14187]
### Describe your problem here.

So I got this error:

source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by TheoDevelops** [comment]
add this before class

typedef TeaCall = tea.Sscript.Tea;
