### ISSUE TITLE
Credits dont work in newest psych version

### ISSUE THREAD

**Issue by MikeBisasam** [ShadowMario/FNF-PsychEngine#14180]
### Describe your problem here.

Idk what to do, i changed the credits.txt file so so many times and everything i did didnt work. Its probably the new version causing this (0.7.3) because on my old version (something 0.6) it still works. Thanks for the help in Advance

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MikeBisasam** [comment]
Oh, thats my bad, i thought Source meant base psych engine without coding. Im using normal psych engine, and there is just a Credits.txt file and no CreditsState. Can i only change it with Source now?

**Comment by Stefan2008Git** [comment]
> Oh, thats my bad, i thought Source meant base psych engine without coding. Im using normal psych engine, and there is just a Credits.txt file and no CreditsState. Can i only change it with Source now?

Well, uh. When i said "CreditState is broken", that means the state is little bit broken

**Comment by Porcupine2009** [comment]
> Oh, thats my bad, i thought Source meant base psych engine without coding. Im using normal psych engine, and there is just a Credits.txt file and no CreditsState. Can i only change it with Source now?

Make sure you unzip the modExample.zip file and drop the credits.txt file in the data folder

mods/modnamehere/data/credits.rxt

**Comment by MikeBisasam** [comment]
It worked! My main Problem was i just extracted the modtemplate before and then i had psychengine/mods/data/credits.txt but now i have psychengine/mods/mymod/data/credits.txt (so basically i HAVE to use another folder after mods or else it breaks)
Thanks for helping!

**Comment by Porcupine2009** [comment]
No problem :)
