### ISSUE TITLE
How do i stop the transitions

### ISSUE THREAD

**Issue by mahikotahi** [ShadowMario/FNF-PsychEngine#14182]
### Describe your problem here.

I just want to stop the transitions and have it be instant

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

New Main Menu, Modified Title State, New Credits Menu, Technically New Options Menu, and removed most of the vanilla stuff. Along with adding the stuff my mod will need.

**Comment by Stefan2008Git** [comment]
You can only remove CustomFadeTransition and edit MusicBeatState for that and please use the FlxG method during the latest HaxeFlixel changes
