### ISSUE TITLE
Can't install hxCodec

### ISSUE THREAD

**Issue by therealhrzn** [ShadowMario/FNF-PsychEngine#14199]
### Describe your bug here.

In the Library versions page, it says that I have to install hxCodec to compile the game, but whenever I try to do so it doesnt work.

### Command Prompt/Terminal logs (if existing)

```bash
*Runs haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git in C:\Users\<myusername>*

You already have hxCodec version git installed.
Updating hxCodec version git ...
Reset changes to hxCodec Git repo so we can pull latest version [y/n/a] ? y
fatal: not a git repository (or any of the parent directories): .git
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not modify any of the code

**Comment by Zoe096423** [comment]
Got the same problem T-T
Don't mind me, just waiting for an answer here too
