### ISSUE TITLE
Error building psych from source

### ISSUE THREAD

**Issue by Aweseome245** [ShadowMario/FNF-PsychEngine#1419]
### Describe your bug here.

Got a clean copy of the source code and tried to build it using both the bat file in the art folder and through lime test windows. Gives me the error shown below. Literally nothing was touched or edited whatsoever, and I've followed the build guide on the original Funkin repo to the letter, installing every library and VS 2019 components. What's the issue here?

### Command Prompt/Terminal logs (if existing)

```bash
source/ModsMenuState.hx:387: characters 6-28 : {+ length : Int } should be String
source/ModsMenuState.hx:391: characters 6-42 : {+ length : Int } should be String
source/ModsMenuState.hx:395: characters 36-47 : Array access is not allowed on {+ length : Int }
source/ModsMenuState.hx:395: characters 36-47 : For function argument 'Red'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing was edited.

**Comment by zdtbeats** [comment]
same

**Comment by zdtbeats** [comment]
![image](https://user-images.githubusercontent.com/85814378/143720190-162f4169-7059-4b89-873e-11f8aabc5623.png)

**Comment by KutikiPlayz** [comment]
ModsMenuState is unfinished rn I think, you can probably get rid of that file until it's complete, and then in MainMenuState put /* and */ around any code that refers to ModsMenuState

**Comment by Aweseome245** [comment]
this worked, thanks!

**Comment by foxygood** [comment]
KutikiPlayz I don't understand can you record showing how you do it?

**Comment by Idontknowhowtocode333** [comment]
do you know what files have code that refers to ModsMenuState so I can easily comment out the code?

**Comment by Aeryn1023** [comment]
The file that references ModsMenuState is MainMenuState.hx, you can comment out the code that references the file like so:
![ModsMenuStateCommentOut](https://user-images.githubusercontent.com/95365759/144261778-f83e345f-563c-4713-9606-af7ba10c128d.PNG)

**Comment by foxygood** [comment]
I still don't understand
