### ISSUE TITLE
How do I put this hold from Kade to Psych?

### ISSUE THREAD

**Issue by pablowolfgamerbr** [ShadowMario/FNF-PsychEngine#14193]
### Describe your problem here.

![Captura de Tela (83)](https://github.com/ShadowMario/FNF-PsychEngine/assets/96152533/01e28e3d-e7c9-4227-982d-e7eac32eb63b)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Stefan2008Git** [comment]
That happens on original vanilla game with strum note position

**Comment by ShadowMario** [comment]
thats a bug
