### ISSUE TITLE
Error in debug mod

### ISSUE THREAD

**Issue by C8tdan** [ShadowMario/FNF-PsychEngine#14190]
### Describe your bug here.

every time i run the game it gives me this error costantly. What can i do about it?
![immagine_2024-02-23_155127113](https://github.com/ShadowMario/FNF-PsychEngine/assets/105670497/53eb909f-de59-4e93-9490-485a359015f7)

### Command Prompt/Terminal logs (if existing)

```bash
[WARNING] Could not parse frame number of " instance 10000" in frame named "k bold instance 10000"
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheGaloXx** [comment]
can someone give a fix to this pls?
i know its not an error and more like a warning but its really annoying

**Comment by ShadowMario** [comment]
This happens in newest versions of flixel, go back to version 5.6.1 and it should stop
