### ISSUE TITLE
Crashes on adjusting certain animations

### ISSUE THREAD

**Issue by aflacc** [ShadowMario/FNF-PsychEngine#142]
so I tried adjusting animations, about half the animtions work without an issue.
I went out of my way to create a GIF that showcases all the animations with a label that describes if I had problems with it at all

https://media.discordapp.net/attachments/811669657094193252/891505196855877702/RECOVER_SHINGLES_assets.gif?width=728&height=701

(hopefully that worked)

Edit: I just want to clarify, it's not like Psych engine has anything against tweened animations, because I actually went out of my way to convert the tween into seperate frames)

**Comment by aflacc** [comment]
I've been asking in DMs if you have any ideas whats going on @ShadowMario and you haven't said anything

**Comment by FuseIsHere813** [comment]
> I've been asking in DMs if you have any ideas whats going on @ShadowMario and you haven't said anything

He responds here sometimes often, please, be patient.

**Comment by aflacc** [comment]
> He responds here sometimes often, please, be patient.

Sorry.

**Comment by ShadowMario** [comment]
The issue might have been on your .xml file's encoding actually,
Also, i've not been answering 100% of the DMs lately because of the massive amount of DMs i'm getting (I'm tired).

**Comment by aflacc** [comment]
> The issue might have been on your .xml file's encoding actually,
> Also, i've not been answering 100% of the DMs lately because of the massive amount of DMs i'm getting (I'm tired).

Sorry about that. I'm not sure whats going on because I can load the animation without issue and play it but it crashes when I try to adjust its offsets

**Comment by aflacc** [comment]
Hello? I don't know why its doing this still.

**Comment by aflacc** [comment]
I never got my question fixed
