### ISSUE TITLE
game bugs out if you unplug headphones

### ISSUE THREAD

**Issue by BroClub50** [ShadowMario/FNF-PsychEngine#14204]
### Describe your bug here.

When you unplug headphones during gameplay or on menus, most of the game will break temporality until you restart the game.  Sprites will freeze and songs too. It's weird. Even if you plug the headphones back in, the game will not fix itself.
**_very weird bug lmao_**

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by biomseed** [comment]
This has been an issue for a while. It's really funny seeing the song start up and then both the characters just do nothing.

**Comment by SrBagel** [comment]
I think this is more of a Haxe issue rather than a Psych Engine issue. This bug is in Kade Engine and other engines as well.

**Comment by 2JENO** [comment]
that is haxe flixel problem

**Comment by ender69funk** [comment]
Haha, thats true.

**Comment by TheoDevelops** [comment]
CODENAME FIX IT LOOOL

but with c++ bc yes, its a lime && openfl problem
