### ISSUE TITLE
Psych| Type not found: TeaCall

### ISSUE THREAD

**Issue by Weasl4** [ShadowMario/FNF-PsychEngine#14205]
### Describe your problem here.

When I run lime test windows an error shows and tells me: "source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall" Don't know what to do or type and can't find solutions online, help would be mu, thanks

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Draconic-Hybrid** [comment]
#14142
