### ISSUE TITLE
Song aren't loading in chart editor

### ISSUE THREAD

**Issue by CoolGuyNamedMax** [ShadowMario/FNF-PsychEngine#14206]
### Describe your bug here.

I'm trying to chart my mod and when i put the song name and press reload audio it gives me this
![Screenshot 2024-02-24 152548](https://github.com/ShadowMario/FNF-PsychEngine/assets/161169806/6c9b7437-4649-4b80-b346-d37b30c0859a)

https://github.com/ShadowMario/FNF-PsychEngine/assets/161169806/354afa43-3705-40ff-a77d-c2428323bb9c

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Just the song and some sprites

**Comment by CoolGuyNamedMax** [comment]
It's not even just my song I had some other mods and I tried those songs and they didn't work either

**Comment by ender69funk** [comment]
Its ogg?
