### ISSUE TITLE
Linux Flatpak distribution

### ISSUE THREAD

**Issue by fpiesche** [ShadowMario/FNF-PsychEngine#14209]
### What is your question?

Heyo,

I've been putting together [Flathub](https://flathub.org/) distributions for free game projects for a bit and a friend asked if I could have a go at doing this for PsychEngine so it's a bit easier to get to work on a Steam Deck. I've spent today putting all that together and have a working setup now that I'd love to submit to Flathub - would you be okay with me doing so? Their [submission guidelines](https://github.com/flathub/flathub/wiki/App-Submission) require that apps be submitted either by someone who's a contributor to the application, or with express permission by the developers.

tl;dr, this would get PsychEngine listed on FlatHub (similar to [this distribution for The Force Engine I've put together](https://flathub.org/apps/io.github.theforceengine.tfe) and easily installed on Linux systems (eg. the Steam Deck), with no need for users to compile their own.

As a bonus: any new release tags (in the pattern of `x.y.z`) created on this Github repo would cause Flathub to automatically build and deploy the new version on their infrastructure, and existing users will get an update notification (which they can choose to ignore, e.g. if an update were to break compatibility with any of their mods). By default, the latest version will be installed on new installations, but users can downgrade to older versions manually if needed.

If you're okay with me setting up this distribution, I'd be happy to maintain it as a service to the general community.

**Comment by ender69funk** [comment]
YOOO MAN

**Comment by sunroll1** [comment]
how do I put mods on this one

**Comment by fpiesche** [comment]
You can install mods by copying them to the directory `/home/[your username]/.var/app/io.github.shadowmario.fnf-psychengine/data/mods/` in your user's home directory (the `.var` directory is hidden by default; most Linux file managers will allow you to press Ctrl+H to show hidden files so you can see it).

**Comment by fpiesche** [comment]
This is now done, with ShadowMario giving permission via Discord. https://flathub.org/apps/io.github.shadowmario.fnf-psychengine

**Comment by Stefan2008Git** [comment]
> You can install mods by copying them to the directory `/home/[your username]/.var/app/io.github.shadowmario.fnf-psychengine/data/mods/` in your user's home directory (the `.var` directory is hidden by default; most Linux file managers will allow you to press Ctrl+H to show hidden files so you can see it).

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/b5619015-fe15-4dba-b67e-e193ca62c0aa)
Ye, but how to access to assets folder then?

**Comment by fpiesche** [comment]
The assets folder is inside the Flatpak sandbox and intentionally read-only; the Flatpak distribution is intended for use with mods that use PsychEngine's modding functionality rather than modifying the base engine data. What mod are you trying to install that requires messing with the engine assets folder?

**Comment by Stefan2008Git** [comment]
> The assets folder is inside the Flatpak sandbox and intentionally read-only; the Flatpak distribution is intended for use with mods that use PsychEngine's modding functionality rather than modifying the base engine data. What mod are you trying to install that requires messing with the engine assets folder?

I don't want to install mod that required the assets folder, just asking the normal question, but alright

**Comment by Twig6943** [comment]
/home/$USER/.var/app/io.github.shadowmario.fnf-psychengine/data/mods/
