### ISSUE TITLE
Can't make new characters

### ISSUE THREAD

**Issue by JergamerGamer11** [ShadowMario/FNF-PsychEngine#14202]
### Describe your problem here.

Every time I press reload image, I get this.
![Screenshot 2024-02-24 081719](https://github.com/ShadowMario/FNF-PsychEngine/assets/102003755/9a650546-8faf-44d0-97e0-104a79ddaa6e)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no.

**Comment by ShadowMario** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/14895665-fc57-4b44-b43a-b8207c1d96f3)
You have to add them
