### ISSUE TITLE
Notes Randomly appear in the song but not in the Chart Editor

### ISSUE THREAD

**Issue by SumGhostDevelops** [ShadowMario/FNF-PsychEngine#14217]
### Describe your problem here.

I was charting a song, but when I got to around 16s into the song, it started randomly appearing notes.  Because I was new to fnf modding (I usually mod for pjsk), I thought it was a feature (like an auto charter).  As of right now, I think this is either a bug or I'm just plain stupid, and its a feature.  
Thanks! 
-Vivi
![asdfasdfsdfasdf](https://github.com/ShadowMario/FNF-PsychEngine/assets/69370002/e355e44c-5804-4018-8810-e6c42a212640)
![wefefwasefsaef](https://github.com/ShadowMario/FNF-PsychEngine/assets/69370002/d5471e48-b474-4f7f-8729-ccea6ec4171a)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by SumGhostDevelops** [comment]
it appears to stop around 109s into the song-- I don't think it's another chart considering the mapping doesn't feel human-generated nor part of another song.  It could be like data from something else messing with it but I don't know.

**Comment by ender69funk** [comment]
Bpm problem ig

**Comment by ender69funk** [comment]
Looks like u just placed notes and trolling us
If u trolling us to nice work dude

**Comment by KostyaKindaluk** [comment]
I too have this issue. In last section where I have no single notes(only double), for some reason two notes appear - up and then down. I'm using Psych Engine v0.7.3 so this bug is something new
