### ISSUE TITLE
cant even run "lime test windows"

### ISSUE THREAD

**Issue by Vobasan** [ShadowMario/FNF-PsychEngine#14219]
### Describe your problem here.

I followed the tutorial and ran the setup batch file but whenever i go to run "lime test windows" in the CMD it says "'lime' is not recognized as an internal or external command, operable program or batch file."

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Vortex2Oblivion** [comment]
```haxelib run lime setup```

**Comment by Vobasan** [comment]
thanks so much!
