### ISSUE TITLE
Something lost in PE0.6.3

### ISSUE THREAD

**Issue by xiaochenhao576** [ShadowMario/FNF-PsychEngine#14214]
### What needs to be documented?

when I complied the 0.6.3,it can't use color,such as I set camera flash event color to 44ffff,it has no change,it must miss some code  in 0.6.3 source code,also I haven't change any code,and in the MainMenuState.hx,the psychengineVersion is = 0.6.2

**Comment by xiaochenhao576** [comment]
I think you upload a wrong source code,you've uploaded the 0.6.2,but it was 0.6.3,wrong version
![屏幕截图 2024-02-25 190128](https://github.com/ShadowMario/FNF-PsychEngine/assets/87370213/34e07ede-f95c-4973-abc0-4cd1e2d105ac)
![屏幕截图 2024-02-25 190201](https://github.com/ShadowMario/FNF-PsychEngine/assets/87370213/1648753b-0652-489e-946a-0fe672f78ad4)

**Comment by Vortex2Oblivion** [comment]
psych 0.6.3 is almost a year and a half old hes not gonna fix it now

**Comment by ShadowMario** [comment]
Psych 0.6.3 is not supported anymore
