### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by Fellegend** [ShadowMario/FNF-PsychEngine#14215]
### Describe your problem here.

I got this error compiling:
Creating C:/Users/User/Downloads/FNF-PsychEngine-main/export/release/windows/
obj/obj/msvc1964-nc/__pch/haxe/hxcpp.pch...
hxcpp.cpp

Compiling group: haxe
cl.exe -Iinclude -IC:/haxelib/hxdiscord_rpc/git/project/discord-rpc/include -DDISCORD_DISABLE_IO_THREAD -IC:/haxelib/lin
c_luajit/git//linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\User\Downloads\FNF-PsychEngine-main\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(
debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/haxelib/hxcpp/4,3,2/include -DHXCPP_M64 -DHXCPP_VISIT_ALL
OCS(haxe) -DHXCPP_CHECK_POINTER(haxe) -DHXCPP_STACK_TRACE(haxe) -DHXCPP_STACK_LINE(haxe) -DHX_SMART_STRINGS(haxe) -DHXCP
P_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_W
IN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/ApplicationMain.cpp
 - src/lime/utils/AssetCache.cpp  [haxe,release]
Link: ApplicationMain.exe
   Creating library ApplicationMain.lib and object ApplicationMain.exp
27c37d3c_TextFunctions.obj : error LNK2011: precompiled object not linked in; image may not run
  Hint on symbols that are defined and could potentially match:
    __@@_PchSym_@00@UfhvihUfhviUwvhpglkUnbLhgfuuUtznvhUumuLzmwLhgfuuUnlwwrmtUumuLgOgUumuRkhbxsvmtrmvRnzrmUvckligUivovzhv
UdrmwldhUlyqUlyqUnhexBJGERmxUPPkxsUszcvUscxkkOlyq@link41b98d27518634c2616f593fa5b8a2f2
    __@@_PchSym_@00@UfhvihUfhviUwvhpglkUnbLhgfuuUtznvhUumuLzmwLhgfuuUumuLgOgUumuRkhbxsvmtrmvRnzrmUvckligUivovzhvUdrmwldh
UlyqUlyqUnhexBJGERmxUPPkxsUifmgrnvUscxkkOlyq@link1d35b58168a7c00bd3d09db0289b2e20
ApplicationMain.exe : fatal error LNK1120: 1 unresolved externals

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Just freakyMenu.ogg song in example-mods\My-Mod\music

**Comment by Vortex2Oblivion** [comment]
delete the export folder and try again. 
this error means something got corrupted while compiling

**Comment by Fellegend** [comment]
tnk
