### ISSUE TITLE
Issues in the Web version of psych engine

### ISSUE THREAD

**Issue by Chromebookgamerwastaken** [ShadowMario/FNF-PsychEngine#1421]
### Describe your bug here.

There is a lot of errors in the web version, let me explain:

1. The mods folder doesnt compile, meaning that i cannot use .lua scripts even though if I installed lua on my pc.
2. Pressing 7 in the main menu does nothing, it doesnt bring me to the week editor, dialogue editor, etc
3. Blammed lights and screen shake (or camera shake) makes the game crash for no reason (resulting in blammed crashing mid-song)

Im an itch.io porter and these things are necessary for my ports, if you can please fix this, thank you

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
1. HTML5 SUCKS.
2. HTML5 doesn't support modded files, nothing i can do about it so don't even ask for it, just get a good PC or something.

**Comment by ShadowMario** [comment]
Also eww an Itch.io porter
