### ISSUE TITLE
(0.6.3/0.7.1h and 0.7.3) the game crashes when y try to load a image on Menu Character Editor and Potrait Editor

### ISSUE THREAD

**Issue by MateOxigeno** [ShadowMario/FNF-PsychEngine#14220]
### Describe your problem here.

My friend made some sprites for our mod and when i go to menucharacter editor and put the sprites into it, the game crashes, same with potrait editor (sobre by my bad english)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't editado absolutley nothing

**Comment by ShadowMario** [comment]
Does it show any error log?

**Comment by Stefan2008Git** [comment]
> Does it show any error log?

Close it because he is not replying

**Comment by MateOxigeno** [comment]
> Does it show any error log?

Sorry, i realized that isn't the engine, is the xml, i solved it, sorry for bothering
