### ISSUE TITLE
Lime path library error (0.7.3 Ex Latest)

### ISSUE THREAD

**Issue by lazyremixmanordummyplayinggmod** [ShadowMario/FNF-PsychEngine#14227]
### Describe your bug here.

this error on compile
![grrrerorr](https://github.com/ShadowMario/FNF-PsychEngine/assets/97311877/3e9f1acb-15c0-4715-82d7-7944f7cc5936)

### Command Prompt/Terminal logs (if existing)

```bash
Called from lime.app.Promise::error lime/app/Promise.hx line 149
Called from lime.app.Promise::error lime/app/Promise.hx line 149
Called from lime.utils.Assets::loadLibrary lime/utils/Assets.hx line 480
Called from lime.app.Promise_lime_utils_AssetLibrary::error lime/app/Promise.hx line 149
Called from lime.utils.Preloader::updateProgress lime/utils/Preloader.hx line 293
Called from lime.utils.Log::error lime/utils/Log.hx line 37
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

only moved crap around but not paths

**Comment by ender69funk** [comment]
Use lime 8.0.1

**Comment by lazyremixmanordummyplayinggmod** [comment]
> Use lime 8.0.1

but why i used it on 0.7.1h why is it not working for 8.1.1

**Comment by lazyremixmanordummyplayinggmod** [comment]
Im going to look into this deeper bc im wanting to use this version of lime

**Comment by lazyremixmanordummyplayinggmod** [comment]
also doesn't 0.7.2x use 8.1.1?

**Comment by lazyremixmanordummyplayinggmod** [comment]
or did he revert it

**Comment by lazyremixmanordummyplayinggmod** [comment]
![Screenshot 2024-02-27 11 01 23 PM](https://github.com/ShadowMario/FNF-PsychEngine/assets/97311877/53804a3f-3ffd-46fd-b8c5-e54ae6fd7c1d)
could it be this commit to cause the error
