### ISSUE TITLE
Psych crashes on startup, displays this message.

### ISSUE THREAD

**Issue by luigiman0** [ShadowMario/FNF-PsychEngine#14228]
### Describe your problem here.

backend/Paths.hx (line 275)
backend/Paths.hx (line 247)
states/TitleState.hx (line 209)
states/TitleState.hx (line 170)
flixel/util/FlxTimer.hx (line 205)
flixel/util/FlxTimer.hx (line 295)
flixel/FlxGame.hx (line 750)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

I haven't seen this message ever until today, does anyone know what the issue might be?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I've only added some songs, characters, stages, and events using Lua.

**Comment by luigiman0** [comment]
update: this appears to be happening with both my version 0.6.3 and 0.7.3 engines.

**Comment by ender69funk** [comment]
you put a check mark on PU Caching?

**Comment by luigiman0** [comment]
> you put a check mark on PU Caching?

yeah

**Comment by luigiman0** [comment]
went into appdata to change the setting, fixed the issue!
