### ISSUE TITLE
Help me please :(

### ISSUE THREAD

**Issue by GioTheXDL** [ShadowMario/FNF-PsychEngine#14224]
### Describe your bug here.

I was to enter to bopeebo chartingmode and i got a window some weird
![2024-02-26](https://github.com/ShadowMario/FNF-PsychEngine/assets/161370713/336c2ae3-c418-45ba-849e-2ea04a37e82a)
help me shadowmario please 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope, only i added mods

**Comment by ender69funk** [comment]
Miising chart or chart diff
