### ISSUE TITLE
song files are crashing the game

### ISSUE THREAD

**Issue by avangere4r** [ShadowMario/FNF-PsychEngine#14231]
### Describe your bug here.

(VER 0.7.3) (64 BIT)

I'm trying to open the chart editor and the game crashes, showing me same crash og over and over again. (Both Inst and Voices files are .ogg)

### Command Prompt/Terminal logs (if existing)

```bash
openfl/media/Sound.hx (line 407)
backend/Paths.hx (line 442)
states/editors/ChartingState.hx (line 1438)
states/editors/ChartingState.hx (line 270)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Error loading sound from file: mods/twesla/songs//undertu/Voices.ogg
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing, just adding chart, week, and song files

**Comment by DaKidWize** [comment]
I Had this problem and the way I fixed it was by using a file convertor I converted my original Voices.ogg and Isnt.ogg files and put them in and it worked
