### ISSUE TITLE
How to use this script in version 0.7.3 of the engine

### ISSUE THREAD

**Issue by VeritonR** [ShadowMario/FNF-PsychEngine#14232]
### Describe your problem here.

There is a mod that makes a video become a background but in the most updated version of the engine the game gives the error
" ERROR ON LOADING (mods/scripts/script.lua): SScript: 000: Tried to access a null variable bitmapDATA"

I wanted to know if any code was changed or something
The script works perfectly in version 0.6.3 of the engine

https://gamebanana.com/mods/426880 (script link)

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/67881127/2654b665-0ba7-48a9-ac76-a9c570af2d5c)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by lazyremixmanordummyplayinggmod** [comment]
get the updated version on psych discord server

**Comment by VeritonR** [comment]
> get the updated version on psych discord server

I have the latest version of psych but I wanted to know how to port the script using the new versions of HaxeCode
