### ISSUE TITLE
Static refuses to tween and just becomes visible

### ISSUE THREAD

**Issue by Your-Local-LordXSimp** [ShadowMario/FNF-PsychEngine#14230]
### Describe your problem here.

`function onEvent(name, value1, value2)
	if name == 'staticAAAsoScaryTween' then
		makeAnimatedLuaSprite('static', 'static', 0, 0)
		setObjectCamera('static', 'camOther')
		scaleObject('static', 1, 1)
		addAnimationByPrefix('static', 'anim', 'static idle0', 24, true)
		playAnim('static', 'anim', true)
		doTweenAlpha('staticA', 'static', 0, 0.000000000000000000001, 'linear')
		addLuaSprite('static', true)

		if value1 == 'onTween' then
			doTweenAlpha('staticA', 'static', 1, value2, 'linear')
		end
		if value1 == 'offTween' then
			doTweenAlpha('staticA', 'static', 0, value2, 'linear')
		end
	end
end`

Value2 is just the time it takes to tween the visibility.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I'm doing something with Johnny Ringo but it's The Fallout version for fun.

**Comment by frantastic24** [comment]
`value2` is a string, it has to be converted into a number

```lua
tonumber(value2)
```

**Comment by Your-Local-LordXSimp** [comment]
Oh ok, thanks.

**Comment by Your-Local-LordXSimp** [comment]
It still refuses to tween.

`function onEvent(name, value1, value2)
	local var duration = tonumber(value2)
	if name == 'staticAAAsoScaryTween' then
		makeAnimatedLuaSprite('static', 'static', 0, 0)
		setObjectCamera('static', 'camOther')
		scaleObject('static', 1, 1)
		addAnimationByPrefix('static', 'anim', 'static idle0', 24, true)
		playAnim('static', 'anim', true)
		doTweenAlpha('staticA', 'static', 0, 0.000000000000000000001, 'linear')
		addLuaSprite('static', true)

		if value1 == 'onTween' then
			doTweenAlpha('staticA', 'static', 1, value2, 'linear')
		end
		if value1 == 'offTween' then
			doTweenAlpha('staticA', 'static', 0, value2, 'linear')
		end
	end
end`
