### ISSUE TITLE
"Attempting to resetState while current state is destroyed"

### ISSUE THREAD

**Issue by Steve35117** [ShadowMario/FNF-PsychEngine#14241]
### Describe your problem here.

I dont know what happened
Version: 0.5.1
![Error 3_1_2024 2_45_43 PM](https://github.com/ShadowMario/FNF-PsychEngine/assets/95169213/dd78fe0a-964e-4475-aa46-e64da432d93f)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Everything

**Comment by Vortex2Oblivion** [comment]
0.5.1 is not supported but you need to downgrade your flixel to 5.5.0 or update the code to work with latest

**Comment by Steve35117** [comment]
> 0.5.1 is not supported but you need to downgrade your flixel to 5.5.0 or update the code to work with latest

How do i downgrade?

**Comment by ShadowMario** [comment]
> 0.5.1 is not supported

^

**Comment by Steve35117** [comment]
> > 0.5.1 is not supported
> 
> ^

Actually i figured it out i just uh updated haxeflixel and all others to their latest version
