### ISSUE TITLE
Error: Could not find haxelib "linc_luajit", does it need to be installed?

### ISSUE THREAD

**Issue by rafaelHenrique99** [ShadowMario/FNF-PsychEngine#14245]
### Describe your bug here.

this error appears when i try to build the game

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by GuineaPigUuhh** [comment]
Yes, here the command to install linc_luajit
```bash
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
```
