### ISSUE TITLE
FLXAnimate Error When Compiling

### ISSUE THREAD

**Issue by NotSomeBlox** [ShadowMario/FNF-PsychEngine#14254]
### Describe your bug here.

When compiling, FLXAnimate had errors and I do not know how to fix it. Can anyone help me?
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/104321099/3579dc5b-c7a4-4a54-a7f6-3f09b8d8facf)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by GuineaPigUuhh** [comment]
see if the Lib is not in the wrong version.

Here the Wiki: [Here!](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)

**Comment by YouDevsYoupikmin** [comment]
I think you got the wrong flxAnimate, use 
haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev
and
haxelib set flxanimate git
I hope this is gonna help you.
