### ISSUE TITLE
Error while trying to play my mod.

### ISSUE THREAD

**Issue by MellTj** [ShadowMario/FNF-PsychEngine#14258]
### Describe your problem here.

Hello. I was making my mod for friends, but I ran into an error, the description of which is below.
---
states/PlayState.hx (line 355)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
---
I ran into this error when tried to play my week/song in the free play.
And I apologise for my bad english, because I'm using the translator.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by GuineaPigUuhh** [comment]
Maybe it's a bug related to an objec.
