### ISSUE TITLE
how do u set a text to the dad's health bar color?

### ISSUE THREAD

**Issue by SlushieDrawzCoolDrawingX480** [ShadowMario/FNF-PsychEngine#14251]
### What is your question?

how do u set a text to the dad's health bar color in lua?

**Comment by GuineaPigUuhh** [comment]
Use this code, This code was only tested on [Psych 0.7.2h](https://github.com/ShadowMario/FNF-PsychEngine/releases/tag/0.7.2h)
```lua
-- To parse the RGB to Hex
function rgbToHex(rgb)
    local rgb = (rgb[1] * 0x10000) + (rgb[2] * 0x100) + rgb[3]
    return string.format("%x", rgb)
end

function onCreatePost()
    -- Save the Boyfriend Icon Color
    local ogBoyfriendColor = rgbToHex(getProperty('boyfriend.healthColorArray'))

    -- Save the Dad Icon Color, if you want to use
    local ogDadColor = rgbToHex(getProperty('dad.healthColorArray'))

    -- to Set the Colors on The Health Bar
    setHealthBarColors('#0036FF', ogBoyfriendColor)
end
```

**Comment by SrBagel** [comment]
> Use this code, This code was only tested on [Psych 0.7.2h](https://github.com/ShadowMario/FNF-PsychEngine/releases/tag/0.7.2h)
> 
> ```lua
> -- To parse the RGB to Hex
> function rgbToHex(rgb)
>     local rgb = (rgb[1] * 0x10000) + (rgb[2] * 0x100) + rgb[3]
>     return string.format("%x", rgb)
> end
> 
> function onCreatePost()
>     -- Save the Boyfriend Icon Color
>     local ogBoyfriendColor = rgbToHex(getProperty('boyfriend.healthColorArray'))
> 
>     -- Save the Dad Icon Color, if you want to use
>     local ogDadColor = rgbToHex(getProperty('dad.healthColorArray'))
> 
>     -- to Set the Colors on The Health Bar
>     setHealthBarColors('#0036FF', ogBoyfriendColor)
> end
> ```

for setting text you would do `setTextColor("TextTag", ogDadColor)`

**Comment by mcagabe19** [comment]
fuck you

**Comment by mcagabe19** [comment]
pornhub

**Comment by mcagabe19** [comment]
fuck me

**Comment by ender69funk** [comment]
Kill yourse-
