### ISSUE TITLE
Animation Error Keeps Happening

### ISSUE THREAD

**Issue by danellerAM** [ShadowMario/FNF-PsychEngine#14268]
### Describe your problem here.

So, I keep importing the same .xml and spritesheet, but it just says: "0 / 0 frames", it shows the first frame of the animation but doesn't play fully. I already confirmed that the name of the animation is the same as the one in the .xml too, and I tried the same with other spritesheets and they worked just fine. Not sure what's wrong with mine...

![trueeeee](https://github.com/ShadowMario/FNF-PsychEngine/assets/112587136/f7649ebb-379b-4e05-9ed6-c52be2df132e)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment]
Remove `0000` at the end of the animation name in the editor

**Comment by danellerAM** [comment]
That actually worked! I feel kind of stupid now :)
