### ISSUE TITLE
Ability to edit object skew.

### ISSUE THREAD

**Issue by Average-FNF-Modder** [ShadowMario/FNF-PsychEngine#14266]
### What feature do you want to get added on the **base** engine?

So you know how we can change a sprite's color, opacity, scale and shit? Well all that's cool, but similar to like, Adobe Animate, I think would be cool if you could also edit an object's skew. In my case it would be a script that leans the player farther back on longer hold notes, but I'm sure it has other uses. I don't even know if this is possible on a technical end, but if it is, this would be really cool.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Vortex2Oblivion** [comment]
FlxSkewedSprite does exist so ig it would be possible

**Comment by ShadowMario** [comment]
Use FlxSkewedSprite, for performance reasons it's better not to do that for every sprite
