### ISSUE TITLE
(Iv fixed the problem) I keep getting this error when i try to load the audio of my custome song

### ISSUE THREAD

**Issue by DJalex1111YT** [ShadowMario/FNF-PsychEngine#14267]
### Describe your problem here.

(Iv fixed the problem)  when I go to create chart and type the name of the custom song and then when I click on reload audio an error pops up
![20240306_172844](https://github.com/ShadowMario/FNF-PsychEngine/assets/162491984/fa5c9a2a-0e15-4879-92c1-6ed0434ecd9b)
( It's my first mod because im getting into creating mods )

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ender69funk** [comment]
Change ur audio like:
Inst
Voices
