### ISSUE TITLE
Linux build can't be open if you had "Allow executing file as program" check option enabled on permission

### ISSUE THREAD

**Issue by Stefan2008Git** [ShadowMario/FNF-PsychEngine#14261]
### Describe your bug here.

For some reason, i can't even open the Psych Engine to Linux because of unknown reason. I don't know it's a me or it's engine issue, but i will definily say it can be the engine issue with Linux opening. Even if i check/uncheck the option, it will not open the game. This video can expalin
https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/24a1f194-5a22-4183-b007-20d63c9e6bf4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No?

**Comment by Stefan2008Git** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/126715034/de64175f-ee59-4b68-bd20-0f1a9e73f491)
EDIT: It seems like it's crashing during the latest Lime version with UTF16

**Comment by mcagabe19** [comment]
yeah a lime issue so fun

**Comment by Stefan2008Git** [comment]
> yeah a lime issue so fun

Fr
