### ISSUE TITLE
click-crash bug

### ISSUE THREAD

**Issue by rafaelHenrique99** [ShadowMario/FNF-PsychEngine#14260]
### Describe your bug here.

the game crashes when i click in the window

version:0.7.0

i didnt compile the game so only some custom scripts are added
![Captura de tela 2024-03-04 152241](https://github.com/ShadowMario/FNF-PsychEngine/assets/131487172/94c4dd54-3d68-4319-a4a4-cb29b2a308ea)
![Captura de tela 2024-03-04 152315](https://github.com/ShadowMario/FNF-PsychEngine/assets/131487172/34c45187-5a5b-4c15-9053-df5db7d84529)
edit: the script 1 and 2 are: 1: cutscene from wiki page. 2: video plays when 7 is pressed

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes but only added scripts in the game file and didnt compiled the game so the problem probably isnt in the source code

**Comment by rafaelHenrique99** [comment]
here are the links for the scripts. im not good at this so if anyone find something, comment here!

https://www.mediafire.com/folder/anbctf22whco5/flippy-roll

https://www.mediafire.com/folder/7r5x912n509li/scripts

**Comment by GuineaPigUuhh** [comment]
I don't know what it could be but I think it could be one of these cases:
- Video not found by Psych Engine
- the Chart may be causing some conflict with the game
- Some image not found

I fixed one of the Scripts the ```nome da janela.lua```:
```lua
function onCreatePost(elapsed)
    local title = "Friday Night funkin VS. Rafa"
    setPropertyFromClass("openfl.Lib", title, title)
end
```
I hope I was helpfull.

**Comment by rafaelHenrique99** [comment]
thanks! im really giving up for changing the window name, but,I think you understand it like this: when I click to enter a level or game, the game crashes. But, what I wanted to say was: when I click on the game window, for example: using the editors, the game gives an error text: InvalidField:ClickCount, and when I press the ok button, the game crashes

**Comment by rafaelHenrique99** [comment]
note: after moving the scripts to a separated folder called quarantine and the results are: without ANY scripts the game has this error! moving to 7.2 source code now! (7.3 do not work because misbehave vocals)

**Comment by rafaelHenrique99** [comment]
but now This happens:
![Captura de tela 2024-03-06 101934](https://github.com/ShadowMario/FNF-PsychEngine/assets/131487172/5cad788a-8898-450b-a924-9740e972e2c7)
when i launch the game

**Comment by GuineaPigUuhh** [comment]
While I'm trying to see what's going on, see if it's not the wrong version of some lib
**[Libraries Versions](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)**

**Comment by GuineaPigUuhh** [comment]
I took a look and it's working, try testing it on the already compiled Psych Engine, it could be your Libs that might be in the wrong versions

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/93527295/ffb4ce91-b03f-41b9-9c66-5908ce9e8e03)

**Comment by GuineaPigUuhh** [comment]
I really don't know, try testing on an already compiled build, did you put all the libs in the right version that is on the Wiki?

**Comment by rafaelHenrique99** [comment]
sorry about my delay, but after a while, i dowloaded a release build of psych engine 0.7.2h and... Bug solved! thanks for your patience helping me! i will close this issue in your next reply (i certainly will put you and a mention of the bug in the credits in the final version of the mod!) another thing: infortunately your changes to nome da janela.lua doesnt seem to work :(

**Comment by GuineaPigUuhh** [comment]
wow, what a shame the `nome da janela.lua` doesn't work anymore, but I'm very happy to help, and I'll be very happy if I'm notified when the mod comes out, but when it comes out, just DM me on discord, my nickname is `guineapiguuhh7841`

**Comment by rafaelHenrique99** [comment]
ok, but the mod itself is personal, and im not publishing it. But i can send you some footage when i finnish it
