### ISSUE TITLE
TimeBar's color

### ISSUE THREAD

**Issue by JVgradiz** [ShadowMario/FNF-PsychEngine#14273]
### Describe your problem here.

I need help in the conversion of a 6.3 to 7.3 lua mod, i need to change the healthBar's color.
setProperty('timeBar.color', getColorFromHex('D416E3')) doesn't work, as it changes the bg of the bar too.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Draconic-Hybrid** [comment]
It's `setTimeBarColors('[hex code for foreground]', '[hex code for background, or just 000000 if you wanna keep it black]')`

**Comment by JVgradiz** [comment]
Thanks @Draconic-Hybrid , it worked

Btw if anyone is curious im doing too slow d-sides
