### ISSUE TITLE
Gradient Underlay On Note Hit

### ISSUE THREAD

**Issue by Average-FNF-Modder** [ShadowMario/FNF-PsychEngine#14272]
### What feature do you want to get added on the **base** engine?

You know that lane underlay option? Would be cool if you could have gradient on hit as an option, so when you sit a note, that note section on the underlay could flash a soft gradient in the background which fades out, maybe custom notes could even have their own settable hit colors. Would just be a neat lil' effect.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Lorekeeper49** [comment]
I think this is actually codable with hscript or even lua, not entirely sure how though
