### ISSUE TITLE
Custom week crashing game

### ISSUE THREAD

**Issue by HourOfEternity** [ShadowMario/FNF-PsychEngine#14274]
### Describe your bug here.

For some reason, whenever I start my custom week, the game crashes. I can play every song in freeplay and it works fine; its just when I try to start a week. The weird part is that it only stopped working after i restarted the game.

### Command Prompt/Terminal logs (if existing)

```bash
states/PlayState.hx (line 1520)
states/PlayState.hx (line 954)
backend/BaseStage.hx (line 120)
states/stages/School.hx (line 117)
states/stages/School.hx (line 87)
backend/BaseStage.hx (line 60)
states/stages/School.hx (line 9)
states/PlayState.hx (line 389)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I'm trying to port a mod into the build, but it is unrelated to this bug.

**Comment by ender69funk** [comment]
Ur stage invalid

**Comment by Frakif91** [comment]
> Ur stage invalid

No way !


Null Object Reference mean that a object that was referenced in source code that wasn't found

In this case that your modding, i'll need to know where did you put you week files and other thing that you modify to understand and maybe help you but i can sense (in a way) that you used `/assets/week6 or 7` instead of `/mods/<yourmod>/weeks`
