### ISSUE TITLE
where do i find the variable of the sprite of unspawn notes

### ISSUE THREAD

**Issue by CanonicHub** [ShadowMario/FNF-PsychEngine#14275]
### Describe your problem here.

im trying to make trail code for the unspawnnotes, but i cant figure out which variable i should use.

this is the code i have, but its incorrect:

![image_2024-03-08_175110920](https://github.com/ShadowMario/FNF-PsychEngine/assets/141660931/05f16cb5-02b9-494d-b7cd-f1d1a5a24c88)

and these are the error messages i got:

![Screenshot 2024-03-08 175154](https://github.com/ShadowMario/FNF-PsychEngine/assets/141660931/40fc8512-4a35-42f5-8895-5cf912282b1b)

my idea was to have the notes to have a sick trail effect whilst going up, but i cant really figure out where the sprite information for the unspawnnotes' sprite is.

ive tried everything i saw in Playstate.hx, i really tried to find it, but i cant.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ender69funk** [comment]
It's ig *null*
