### ISSUE TITLE
Custom note types not working?

### ISSUE THREAD

**Issue by EggisThe2nd** [ShadowMario/FNF-PsychEngine#14279]
### Describe your bug here.

As of 0.7 and above custom note types don't seem to work past the very first one in a chart. I've tested a couple mods such as Angelic Atrocities and Bob's Onslaught, neither work. Build 0.6.3 does still work with the notes however.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by frantastic24** [comment]
Not a bug
Some Lua functions have been changed so your scripts need to be updated

**Comment by EggisThe2nd** [comment]
I think some mods just need to be updated
