### ISSUE TITLE
Compiling MainMenuState issue

### ISSUE THREAD

**Issue by Dakigex** [ShadowMario/FNF-PsychEngine#14283]
### Describe your problem here.

Im making my own mod, and i edited almost the full MainMenuState.hx code, but when trying to compile, it gives me errors, like "source/states/MainMenuState.hx:#: characters #-# : Unknown identifier : nameButton", when the identifier is defined, can someone explain what happens?? and give me a solution?? if someone is generous enough and gives me a code, i will give credits respectively.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Edited MainMenuState.hx, building a menu with working mouse

**Comment by Stefan2008Git** [comment]
You don't have "nameButton" added. Use "var nameButton:FlxButton;"

**Comment by Dakigex** [comment]
> You don't have "nameButton" added. Use "var nameButton:FlxButton;"

did it, but then it gives me this errors:
source/states/MainMenuState.hx:283: characters 24-33 : Type not found : FlxButton
source/states/MainMenuState.hx:287: characters 37-52 : Unknown identifier : storymodeButton
source/states/MainMenuState.hx:287: characters 37-52 : ... For function argument 'ObjectOrGroup'
source/states/MainMenuState.hx:299: characters 45-59 : Unknown identifier : freeplayButton
source/states/MainMenuState.hx:299: characters 45-59 : ... For function argument 'ObjectOrGroup'
source/states/MainMenuState.hx:312: characters 61-74 : Unknown identifier : optionsButton
source/states/MainMenuState.hx:312: characters 61-74 : ... For function argument 'ObjectOrGroup'
source/states/MainMenuState.hx:325: characters 14-29 : Unknown identifier : storymodeButton
source/states/MainMenuState.hx:360: characters 17-31 : Unknown identifier : freeplayButton
source/states/MainMenuState.hx:398: characters 17-30 : Unknown identifier : optionsButton
