### ISSUE TITLE
hxdiscord support only c++ targets error in haxe language server

### ISSUE THREAD

**Issue by anderbauYT** [ShadowMario/FNF-PsychEngine#14286]
### Describe your problem here.

![imagen_2024-03-09_230005111](https://github.com/ShadowMario/FNF-PsychEngine/assets/121905992/8f9f6896-9d8d-4b8a-8933-ff5ec785edbc)
I have never had this error before and I don't know how to fix it.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by TheoDevelops** [comment]
this is weird bcs windows actually is a c++ target, try updating the lib

**Comment by Quielxd** [comment]
Same error for me

**Comment by anderbauYT** [comment]
i dont remember what i do but i solved, think reinstaling all the libs works
