### ISSUE TITLE
dialogue??

### ISSUE THREAD

**Issue by danellerAM** [ShadowMario/FNF-PsychEngine#14285]
### Describe your problem here.

It's a simple problem, I can't figure out how to get dialogue working in custom weeks. If there's an in-depth tutorial on how to set it up than that would be helpful. (also the "script_dialogue.lua" download link is down for some reason sooo)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by YouDevsYoupikmin** [comment]
If you want to make default dialogues go to main menu, press "7" and choose dialogue editor.
here's a tutorial if you needs it https://www.youtube.com/watch?v=6zKIB1Ov66M
