### ISSUE TITLE
Freeplay Menu Portraits

### ISSUE THREAD

**Issue by Komorie6** [ShadowMario/FNF-PsychEngine#14289]
### What is your question?

Is ther a way to add freeplay portraits like in impostor or analog funkin if somebody could provide me with code or like a tutorial that would help a lot!

**Comment by ender69funk** [comment]
Use code from vs impostor v4, it's public

**Comment by Frakif91** [comment]
is Impostor v4 can be used with lua ? is it made with PsychEngine ? i think it was made from source

**Comment by Komorie6** [comment]
How do i do it without giving me an error because eerytime i do it just gives me a long error

**Comment by Komorie6** [comment]
Do i just take  the file from the folder? or do i copy certain parts of the code?

**Comment by Percossi283** [comment]
This is good :>
