### ISSUE TITLE
opponent notes in camGame

### ISSUE THREAD

**Issue by Shiho-cmd** [ShadowMario/FNF-PsychEngine#14293]
### Describe your problem here.

i'm trying to do something similar to this video
https://youtu.be/1c_x9JSkcqs?si=gn_cVTsNGWZq8Bmo

is possible to this in lua or haxe outside of source code?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Vortex2Oblivion** [comment]
```hx
function onCreatePost(){
for(note in game.unspawnNotes){
if(!note.mustPress){
note.cameras = [FlxG.camera]
}
}
}
```
I think?

**Comment by Shiho-cmd** [comment]
> ```hx
> function onCreatePost(){
> for(note in game.unspawnNotes){
> if(!note.mustPress){
> note.cameras = [FlxG.camera]
> }
> }
> }
> ```
> 
> I think?

it's giving me this error:
![Screenshot_28](https://github.com/ShadowMario/FNF-PsychEngine/assets/146484710/89347716-3310-4be1-b274-7ce273e92ae0)

**Comment by Vortex2Oblivion** [comment]
> > ```hx
> 
> > function onCreatePost(){
> 
> > for(note in game.unspawnNotes){
> 
> > if(!note.mustPress){
> 
> > note.cameras = [FlxG.camera]
> 
> > }
> 
> > }
> 
> > }
> 
> > ```
> 
> > 
> 
> > I think?
> 
> 
> 
> it's giving me this error:
> 
> ![Screenshot_28](https://github.com/ShadowMario/FNF-PsychEngine/assets/146484710/89347716-3310-4be1-b274-7ce273e92ae0)
> 
> 

```hx

function onCreatePost(){
for(note in game.unspawnNotes){
if(!note.mustPress){
note.cameras = [FlxG.camera];
}
}
}```

**Comment by Vortex2Oblivion** [comment]
Sorry forgot the ;

**Comment by Shiho-cmd** [comment]
> Sorry forgot the ;

it worked! 
but the strums (i think that's what is called) are still in the hud
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/146484710/43714873-917a-40fe-831c-e9701639c885)

**Comment by Shiho-cmd** [comment]
> ```hx
> function onCreatePost(){
>      for(note in game.unspawnNotes){
>           if(!note.mustPress){
>                note.cameras = [FlxG.camera]
>           }
>      }
> 
>      for(strum in game.opponetStrums.members){
>           strum.cameras = [FlxG.camera];
>      }
> 
> }
> ```
> 
> Try this

this happend
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/146484710/85dd5f78-4c39-4f86-9971-e05dcd83acfa)

**Comment by Vortex2Oblivion** [comment]
Try and delete the .members

**Comment by Shiho-cmd** [comment]
> Try and delete the .members

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/146484710/9c6c62e6-83a0-41c8-a783-6153c385f064)

**Comment by Vortex2Oblivion** [comment]
> 
> 
> Is it because you misspelled `opponetStrums`?
> 
> 

oops

**Comment by Shiho-cmd** [comment]
> > Is it because you misspelled `opponetStrums`?
> 
> oops

it works now but not the way i want i made this video to show what is happening:
https://github.com/ShadowMario/FNF-PsychEngine/assets/146484710/f96f3ef1-b92a-41f6-9b8e-b4de1da63627
basically, when I zoom in, the notes get too big and they also remain still in place
(sorry for the delay!!)

**Comment by Vortex2Oblivion** [comment]
```hx
function onCreatePost(){
     for(note in game.unspawnNotes){
          if(!note.mustPress){
               note.cameras = [FlxG.camera];
             note.scrollFactor.set(1, 1);
          }
     }

     for(strum in game.opponetStrums.members){
          strum.cameras = [FlxG.camera];
          strum.scrollFactor.set(1, 1);
     }

}
```

**Comment by Shiho-cmd** [comment]
> ```hx
> function onCreatePost(){
>      for(note in game.unspawnNotes){
>           if(!note.mustPress){
>                note.cameras = [FlxG.camera];
>              note.scrollFactor.set(1, 1);
>           }
>      }
> 
>      for(strum in game.opponetStrums.members){
>           strum.cameras = [FlxG.camera];
>           strum.scrollFactor.set(1, 1);
>      }
> 
> }
> ```

now it works the way i want thank you!!
btw if that's not much to ask i was trying to put them behind dad by my own but i don't really know how to lol can you help me just one more time please?

**Comment by Shiho-cmd** [comment]
I guess nobody will responde me so i will just close this thanks anyways helped me a lot!!!
