### ISSUE TITLE
FlxPoint problem with runHaxeCode()

### ISSUE THREAD

**Issue by VoidedBattery** [ShadowMario/FNF-PsychEngine#14296]
### Describe your problem here.

Is there a library that I'm missing or what? I even tried to import `flixel.math.FlxPoint` but this kept throwing an error:

`debugPrint(runHaxeCode([[return FlxPoint.get(2.0, 3.0);]]))`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by VoidedBattery** [comment]
UPDATE: I put in `addHaxeLibrary("FlxPoint", "flixel.math")` but it the script still registered "FlxPoint" as an unknown variable.

**Comment by ShadowMario** [comment]
![Screenshot_2024-05-06-18-48-00-293_com android chrome-edit](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/9cc87f93-30ce-4d02-828a-92bb6278b17f)
FlxPoint is an abstract class, it means it stops existing once the game compiles, if you want to use something similar to points in lua just do this:

```lua
local point = {x = 2, y = 3}
```
