### ISSUE TITLE
error when compiling 

### ISSUE THREAD

**Issue by swobodac** [ShadowMario/FNF-PsychEngine#14291]
### Describe your problem here.

i get this error when compiling the game
source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall
I am using psych engine 0.7.3
also this is my first time using the fnf source code

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no I have not

**Comment by swobodac** [comment]
nevermind

**Comment by YouDevsYoupikmin** [comment]
I think it's due to librairies, can you send them?
