### ISSUE TITLE
FNF World

### ISSUE THREAD

**Issue by CuppyMugs** [ShadowMario/FNF-PsychEngine#14297]
### Describe your bug here.

Uncaught Error: [file_contents,assets/characters/bf.json]
That's the error that popped up when I tried playing any of the songs in freeplay and when I tried to go into storymode.

![image_2024-03-13_120613711](https://github.com/ShadowMario/FNF-PsychEngine/assets/163328539/9e358500-1384-4655-86d3-ef2f078495b0)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SrBagel** [comment]
Bf doesn't exist. Also this is FNF World's problem, so go tell them instead.
