### ISSUE TITLE
How to hide the game like NMI in lua

### ISSUE THREAD

**Issue by Cee-Jay0900** [ShadowMario/FNF-PsychEngine#14298]
### What is your question?

How do i hide the game from the taskbar and the screen like in the NMI phase 2 where it hides the game

LUA

**Comment by Cee-Jay0900** [comment]
LUA ONLY

**Comment by blackinposterandlawsuit12345** [comment]
`local fs, mx = false, false
local ffi = require("ffi")

function onEvent(v1, v2)
    if V1 == 'Phase2New' then
        Phase2New(v2)
    end
end

function Phase2New(v2)
    if v2 = 'true' then
        onCreatePost()
    elseif v2 = 'false' then
        onDestroyPost()
    end
end

function onCreatePost()
    if buildTarget ~= 'windows' then
        onDestroy = function () end
        ffi, fs, mx = nil, nil, nil
        return
    end
    ffi.cdef([[
        typedef void* HWND;
        typedef int BOOL;
        typedef unsigned char BYTE;
        typedef unsigned long DWORD;
        HWND GetActiveWindow();
        long SetWindowLongA(HWND hWnd, int nIndex, long dwNewLong);
        BOOL SetLayeredWindowAttributes(HWND hwnd, DWORD crKey, BYTE bAlpha, DWORD dwFlags);
    ]])
    local hwnd = ffi.C.GetActiveWindow()
    ffi.C.SetWindowLongA(hwnd, -20, 0x00080000)
    ffi.C.SetLayeredWindowAttributes(hwnd, 0x131313, 0, 0x00000001)
    addHaxeLibrary('Lib', 'openfl')
    fs = getPropertyFromClass('openfl.Lib', 'application.window.fullscreen')
    mx = getPropertyFromClass('openfl.Lib', 'application.window.maximized')
    runHaxeCode([[
        Lib.application.window.borderless = true;
        Lib.application.window.maximized = false;
        Lib.application.window.fullscreen = false;
    ]])
end
function onDestroyPost()
    ffi.C.SetWindowLongA(ffi.C.GetActiveWindow(), -20, 0x00000000)
    setPropertyFromClass('openfl.Lib', 'application.window.borderless', false)
    setPropertyFromClass('openfl.Lib', 'application.window.fullscreen', fs)
    setPropertyFromClass('openfl.Lib', 'application.window.maximized', mx)
end`

**Comment by YanniZ06** [comment]
LUA ONLY

**Comment by blackinposterandlawsuit12345** [comment]
not possable
you need some haxe in there

**Comment by TheoDevelops** [comment]
this type of code is not implemented in either Haxe or Lua, you can only do it with C++ in this case
