### ISSUE TITLE
Note Splash Debug

### ISSUE THREAD

**Issue by SrBagel** [ShadowMario/FNF-PsychEngine#14290]
### What is your question?

The note splash debug is not working like it used to. In older versions the editor would load what ever note splash you had selected in the options menu. Now it only loads the default note splash and I can't find a way to change it. This might be missing documentation or a bug but I'm not sure.

**Comment by Frakif91** [comment]
What are you using ? A mod or Source

if it's a mod then :

put images of notes here:  `PsychEngine/mods/<yourmod>/images/<notes>`

and in chart editor (for your song)
![image_2024-03-12_170942022](https://github.com/ShadowMario/FNF-PsychEngine/assets/158631597/0d0461d3-c401-4631-983a-199758bdd25d)

Put the name of the image in `Note texture` for it to work

**Comment by SrBagel** [comment]
> What are you using ? A mod or Source
> 
> if it's a mod then :
> 
> put images of notes here: `PsychEngine/mods/<yourmod>/images/<notes>`
> 
> and in chart editor (for your song) ![image_2024-03-12_170942022](https://private-user-images.githubusercontent.com/158631597/312153655-0d0461d3-c401-4631-983a-199758bdd25d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNTg5ODUsIm5iZiI6MTcxMDM1ODY4NSwicGF0aCI6Ii8xNTg2MzE1OTcvMzEyMTUzNjU1LTBkMDQ2MWQzLWM0MDEtNDYzMS05ODNhLTE5OTc1OGJkZDI1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxOTM4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWZkMGNkNDJmNGRmMDUwMDMwZTI0NDJlYzIwNjFmOTg1MjJmNmI0ZGY3YTQxYmZmNzg2NTIzNDk1ZjM2NmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mr1hRRDWsXLrChyqHLfuWIaSylO2L2xlaL8Mnc2b9tQ)
> 
> Put the name of the image in `Note texture` for it to work

That's not exactly what I'm looking for I meant the note splash debug in the master editor menu
![Screenshot 2024-03-13 134005](https://github.com/ShadowMario/FNF-PsychEngine/assets/128989598/9173cc92-d07a-428a-834b-d4e09be3620c)
(This thing)

I have my custom note splashes selected in the options menu
![Screenshot 2024-03-13 134245](https://github.com/ShadowMario/FNF-PsychEngine/assets/128989598/ec34fafe-bf46-4145-9645-22a0fb3ff91c)

and they load like the should in game
![image_2024-03-13_134627547](https://github.com/ShadowMario/FNF-PsychEngine/assets/128989598/697b9a10-a5ff-4b1e-9c95-087bf38a659c)

But in the debug menu it loads the default notes which didn't happen in the other versions in other versions it would load the custom splash selected in the options menu
![Screenshot 2024-03-13 134024](https://github.com/ShadowMario/FNF-PsychEngine/assets/128989598/d0c20ff2-0b8a-4bf7-8d75-0965c0b584c3)
Sorry for the misunderstanding I should have been more descriptive with my problem

**Comment by SrBagel** [comment]
I figured out what I was doing wrong I'm just stupid

**Comment by PotheadPat** [comment]
What exactly did you do wrong? Im having a simmaler problem, I have my XML, and my Image, I added the prefix to the list, and it eithier bugs out or doesent work, Ill drop down my assets below, Please let me know what im possibly doing wrong and what needs to be fixed (ive been stumped for days)

![noteSplashes-HappySplash](https://github.com/ShadowMario/FNF-PsychEngine/assets/167371672/125bdb2f-d21f-47f7-b1c6-7769de9c5aba)

The XML Reads:

<?xml version='1.0' encoding='utf-8'?>
<TextureAtlas imagePath="noteSplashes-HappySplash.png">
<SubTexture name="HappySplash red0000" x="91" y="232" width="92" height="55" frameX="-42" frameY="-53" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash red0001" x="0" y="232" width="91" height="56" frameX="-43" frameY="-52" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash red0002" x="184" y="135" width="85" height="64" frameX="-45" frameY="-48" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash red0003" x="95" y="135" width="89" height="83" frameX="-41" frameY="-42" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash red0004" x="240" y="0" width="99" height="109" frameX="-34" frameY="-19" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash red0005" x="0" y="135" width="95" height="97" frameX="-38" frameY="-35" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash red0006" x="125" y="0" width="115" height="119" frameX="-29" frameY="-26" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash red0007" x="0" y="0" width="125" height="135" frameX="-24" frameY="-19" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash blue 0000" x="91" y="232" width="92" height="55" frameX="-42" frameY="-53" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash blue 0001" x="0" y="232" width="91" height="56" frameX="-43" frameY="-52" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash blue 0002" x="184" y="135" width="85" height="64" frameX="-45" frameY="-48" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash blue 0003" x="95" y="135" width="89" height="83" frameX="-41" frameY="-42" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash blue 0004" x="240" y="0" width="99" height="109" frameX="-34" frameY="-19" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash blue 0005" x="0" y="135" width="95" height="97" frameX="-38" frameY="-35" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash blue 0006" x="125" y="0" width="115" height="119" frameX="-29" frameY="-26" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash blue 0007" x="0" y="0" width="125" height="135" frameX="-24" frameY="-19" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash green 0000" x="91" y="232" width="92" height="55" frameX="-42" frameY="-53" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash green 0001" x="0" y="232" width="91" height="56" frameX="-43" frameY="-52" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash green 0002" x="184" y="135" width="85" height="64" frameX="-45" frameY="-48" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash green 0003" x="95" y="135" width="89" height="83" frameX="-41" frameY="-42" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash green 0004" x="240" y="0" width="99" height="109" frameX="-34" frameY="-19" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash green 0005" x="0" y="135" width="95" height="97" frameX="-38" frameY="-35" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash green 0006" x="125" y="0" width="115" height="119" frameX="-29" frameY="-26" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash green 0007" x="0" y="0" width="125" height="135" frameX="-24" frameY="-19" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash purple0000" x="91" y="232" width="92" height="55" frameX="-42" frameY="-53" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash purple0001" x="0" y="232" width="91" height="56" frameX="-43" frameY="-52" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash purple0002" x="184" y="135" width="85" height="64" frameX="-45" frameY="-48" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash purple0003" x="95" y="135" width="89" height="83" frameX="-41" frameY="-42" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash purple0004" x="240" y="0" width="99" height="109" frameX="-34" frameY="-19" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash purple0005" x="0" y="135" width="95" height="97" frameX="-38" frameY="-35" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash purple0006" x="125" y="0" width="115" height="119" frameX="-29" frameY="-26" frameWidth="175" frameHeight="161" />
<SubTexture name="HappySplash purple0007" x="0" y="0" width="125" height="135" frameX="-24" frameY="-19" frameWidth="175" frameHeight="161" />
</TextureAtlas>


List - [list.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/15017652/list.txt)

**Comment by SrBagel** [comment]
> What exactly did you do wrong? Im having a simmaler problem, I have my XML, and my Image, I added the prefix to the list, and it eithier bugs out or doesent work, Ill drop down my assets below, Please let me know what im possibly doing wrong and what needs to be fixed (ive been stumped for days)
> 
> ![noteSplashes-HappySplash](https://private-user-images.githubusercontent.com/167371672/323394653-125bdb2f-d21f-47f7-b1c6-7769de9c5aba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3OTI2NzQsIm5iZiI6MTcxNDc5MjM3NCwicGF0aCI6Ii8xNjczNzE2NzIvMzIzMzk0NjUzLTEyNWJkYjJmLWQyMWYtNDdmNy1iMWM2LTc3NjlkZTljNWFiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQwMzEyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzQ0ZjU3NTgxNjI3N2RkNzE3NDdhYmE2Yzk1MDVkMDJiZWQ1MTk1Y2NmMzA2NGJkM2QwZDhmMTE2Yzc4NTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z4VGBLDrK7j91WGrn_NtNThGc7zjol-t5pYpUWGnGnw)
> 
> The XML (saved as an XML in game)- [noteSplashes-HappySplash.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/15017669/noteSplashes-HappySplash.txt)
> 
> List - [list.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/15017652/list.txt)

You wanna write the image name of the note splash (noteSplashes-HappySplash in your case) here: 
![Screenshot 2024-03-13 134024](https://github.com/ShadowMario/FNF-PsychEngine/assets/128989598/0d6aecbe-8c26-4497-a75d-3fc4eb1aa03f)
Then press enter _once_ to reload the image (I'm gonna make an issue requesting that they add that to the list of controls)
That should load your image.
Also I'm gonna borrow those splashes cause I love them (just for personal use).

**Comment by mattye-owo** [comment]
> > What exactly did you do wrong? Im having a simmaler problem, I have my XML, and my Image, I added the prefix to the list, and it eithier bugs out or doesent work, Ill drop down my assets below, Please let me know what im possibly doing wrong and what needs to be fixed (ive been stumped for days)
> > ![noteSplashes-HappySplash](https://private-user-images.githubusercontent.com/167371672/323394653-125bdb2f-d21f-47f7-b1c6-7769de9c5aba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3OTI2NzQsIm5iZiI6MTcxNDc5MjM3NCwicGF0aCI6Ii8xNjczNzE2NzIvMzIzMzk0NjUzLTEyNWJkYjJmLWQyMWYtNDdmNy1iMWM2LTc3NjlkZTljNWFiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQwMzEyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzQ0ZjU3NTgxNjI3N2RkNzE3NDdhYmE2Yzk1MDVkMDJiZWQ1MTk1Y2NmMzA2NGJkM2QwZDhmMTE2Yzc4NTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z4VGBLDrK7j91WGrn_NtNThGc7zjol-t5pYpUWGnGnw)
> > The XML (saved as an XML in game)- [noteSplashes-HappySplash.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/15017669/noteSplashes-HappySplash.txt)
> > List - [list.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/15017652/list.txt)
> 
> You wanna write the image name of the note splash (noteSplashes-HappySplash in your case) here: ![Screenshot 2024-03-13 134024](https://private-user-images.githubusercontent.com/128989598/327914961-0d6aecbe-8c26-4497-a75d-3fc4eb1aa03f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NjY3OTMsIm5iZiI6MTcyMjU2NjQ5MywicGF0aCI6Ii8xMjg5ODk1OTgvMzI3OTE0OTYxLTBkNmFlY2JlLThjMjYtNDQ5Ny1hNzVkLTNmYzRlYjFhYTAzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQwMjQxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzE3NDUyZDY1ZDU2NDhiNDhkNjI4ZTBiODE3N2I1NDI5NzI0ZTFmMDAyNDEwNTRmNjhkOTgwYjg0NGFlN2VmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rPZbuuQe5X5L0nyKvln-xhStXcEiqP0MoM4M8XEufCA) Then press enter _once_ to reload the image (I'm gonna make an issue requesting that they add that to the list of controls) That should load your image. Also I'm gonna borrow those splashes cause I love them (just for personal use).

idk what im doing wrong, every time i put my sprites in it just shows "invalid animation name", do u have any idea why it isnt working?

animation:
![noteSplashes-hit](https://github.com/user-attachments/assets/f6c3bea5-773f-472d-bc47-850efed4e306)
xml:
[noteSplashes-hit.txt](https://github.com/user-attachments/files/16464670/noteSplashes-hit.txt)
list:
[hit list.txt](https://github.com/user-attachments/files/16464671/hit.list.txt)
(its named hit list cuz i cant have both in txt with the same name but it is originally the same name as the others)
