### ISSUE TITLE
Game keeps crashing while playing Blammed

### ISSUE THREAD

**Issue by caelio7** [ShadowMario/FNF-PsychEngine#143]
Alright, so I compiled Psych Engine for Mac but when I get like halfway through Blammed it randomly crashes. Idk what to do lol

**Comment by ShadowMario** [comment]
Mac is not supported as i don't have one/have no insterest in buying one for myself.
I'm sorry but i can't help with that.

**Comment by caelio7** [comment]
Understandable! Macs are shit!
