### ISSUE TITLE
Compiling error : "source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall"

### ISSUE THREAD

**Issue by Ehiokn** [ShadowMario/FNF-PsychEngine#14303]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/142696059/455469db-aadd-4a68-89eb-669fade59ff5)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No I haven't editted anything yet

**Comment by Magman03k7** [comment]
open file source/psychlua/HScript.hx and replace all text "TeaCall" to "Tea", then I think you are good to go

**Comment by Ehiokn** [comment]
I tried that but now instead of not being able to find type "TeaCall" it can't find type "Tea"
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/142696059/b9bd1d7a-0977-4f95-956c-738ab6e2ab58)

**Comment by Magman03k7** [comment]
could be because SScript is not installed or right version, type "haxelib install SScript" in terminal and type "y" to update it

**Comment by Ehiokn** [comment]
So the Teacall error is fixed but now I get this 
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/142696059/2afbbee9-8ab3-4fc5-815f-296970233250)

**Comment by Magman03k7** [comment]
did you install libraries through "setup/setup-windows.bat"?

**Comment by Ehiokn** [comment]
Nope I have no idea what "setup/setup-windows.bat" is ._.'

**Comment by Magman03k7** [comment]
open it, and it will install required library

**Comment by Ehiokn** [comment]
how do I open it?

**Comment by Magman03k7** [comment]
double click to open

**Comment by Ehiokn** [comment]
Everything works now!!! :D
Thanks for all the help! :P

**Comment by Magman03k7** [comment]
> > open file source/psychlua/HScript.hx and replace all text "TeaCall" to "Tea", then I think you are good to go
> 
> hi, I'm a begginer , can you tell me how do I open the "hx" file?

need text editor stuff like Visual Studio Code, but other thing will be much stuff
I recommended to watch tutorial like this:
https://github.com/ShadowMario/FNF-PsychEngine/blob/main/BUILDING.md

**Comment by Odudz** [comment]
> > > open file source/psychlua/HScript.hx and replace all text "TeaCall" to "Tea", then I think you are good to go
> > 
> > 
> > hi, I'm a begginer , can you tell me how do I open the "hx" file?
> 
> need text editor stuff like Visual Studio Code, but other thing will be much stuff I recommended to watch tutorial like this: https://github.com/ShadowMario/FNF-PsychEngine/blob/main/BUILDING.md

I followed de instructions but whem i put the "lime test windows" says that "lime" isnt a valid term

"lime : O termo 'lime' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável. Verifique
a grafia do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto e tente novamente.
No linha:1 caractere:1
+ lime test windows
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (lime:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException"
    
    (you can translate to english if you want to see better whats it is)

**Comment by Magman03k7** [comment]
did you setup folder directory `haxelib setup <haxelib repository path, default (C:/haxelib)>` ex:`haxelib setup C:/haxelib` and run `setup-windows.bat` ?

**Comment by Odudz** [comment]
> did you setup folder directory `haxelib setup <haxelib repository path, default (C:/haxelib)>` ex:`haxelib setup C:/haxelib` and run `setup-windows.bat` ?
> 
> 

I think so, later I will try again and show you what happend

**Comment by Odudz** [comment]
> did you setup folder directory `haxelib setup <haxelib repository path, default (C:/haxelib)>` ex:`haxelib setup C:/haxelib` and run `setup-windows.bat` ?

yes, still with the same error

**Comment by Aykkon** [comment]
> double click to open

double click where?

**Comment by Chance92281** [comment]
source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
source/psychlua/CallbackHandler.hx:55: characters 41-46 : Class<llua.LuaL> has no field error
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
source/psychlua/FunkinLua.hx:280: lines 280-283 : Int should be Bool
source/psychlua/FunkinLua.hx:280: lines 280-283 : ... For function argument 'f' what is this and how do i fix it?

**Comment by JaVTuber** [comment]
> I tried that but now instead of not being able to find type "TeaCall" it can't find type "Tea" ![image](https://private-user-images.githubusercontent.com/142696059/313403175-b9bd1d7a-0977-4f95-956c-738ab6e2ab58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MDk2OTAsIm5iZiI6MTcxNjUwOTM5MCwicGF0aCI6Ii8xNDI2OTYwNTkvMzEzNDAzMTc1LWI5YmQxZDdhLTA5NzctNGY5NS05NTZjLTczOGFiNmUyYWI1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwMDA5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03M2I3M2E2NzZmZGQ1MDg1NWVjYzI0N2VlODNlYTlmMDMwNzhiNGQ2ZmVlN2IyZmNhN2JjODFjMTM4YzNiZWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5lIptZ5x6TjngfT3LlG0h8fKOJP6i23mNBxrGGqVqyA)

I got the same problem + this:
`source/psychlua/HScript.hx:13: characters 8-11 : Type not found : Tea
source/psychlua/HScript.hx:14: characters 23-30 : Type not found : SScript` , I tried `haxelib install SScript` but it says that I already got it, I also tried uninstalling it and reinstalling it, but still I get the same error. 
What do I do? :/

**Comment by Easternx1** [comment]
I need help please i have the same error 
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/149325053/46807ef1-6e58-4638-88c6-905735fd952a)

**Comment by B0BIT1** [comment]
> open file source/psychlua/HScript.hx and replace all text "TeaCall" to "Tea", then I think you are good to go

How do i do that

**Comment by RiskyDevs2** [comment]
> I tried that but now instead of not being able to find type "TeaCall" it can't find type "Tea" ![image](https://private-user-images.githubusercontent.com/142696059/313403175-b9bd1d7a-0977-4f95-956c-738ab6e2ab58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMjg5NDIsIm5iZiI6MTcxNzMyODY0MiwicGF0aCI6Ii8xNDI2OTYwNTkvMzEzNDAzMTc1LWI5YmQxZDdhLTA5NzctNGY5NS05NTZjLTczOGFiNmUyYWI1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxMTQ0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGVjNmEzOWUxYTEyN2QzYTkzNDRiZDQwYmQ3N2M2NjM1ZTM3ZjI5NjdhODA4NTQ5NGFjNGE4ZDA5ZDc1NjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3gxm-f1m2LER0VqO6cgonbLSJsD0sKx4cn5K7xi7t8M)

Hey man, can you send me the Hscript.hx on discord? I tried to use the same fix but it didn't work for me

**Comment by SomeAxolotlGuy** [comment]
when i type in "lime test window" it says "type not found : TeaCall"

**Comment by max4th** [comment]
> could be because SScript is not installed or right version, type "haxelib install SScript" in terminal and type "y" to update it also you can setup required library on setup/setup-windows.bat

i did but still the same error

**Comment by thebiggestofchunguses** [comment]
when I try it returns
Warning: Ignoring unknown fps=""
source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall
I have replaced all of the TeaCall's in Hscript already what do I do?

**Comment by Wanv12** [comment]
![Screenshot (9)](https://github.com/user-attachments/assets/a4cb3c3a-2fda-4725-91cd-0cb1d735bd3b)

TeaCall problem solved, but I found a new problem

**Comment by jet1888** [comment]
![Capture](https://github.com/user-attachments/assets/48529c2b-f88d-47f8-96a0-7ceefdfdecd5)
idk if this can be related but dose anyone know how to fix this?
