### ISSUE TITLE
Im shit at this pls help me (Error: Could not find haxelib "hxdiscord_rpc", does it need to be installed?)

### ISSUE THREAD

**Issue by noubtub** [ShadowMario/FNF-PsychEngine#14302]
### Describe your problem here.

i tried running half a dozen commands from the internet that make sense but none of them work. This is on psych engine 0.7.2.
sorry if this seems hilarious and dumb to yall but im just a nooby

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing that i know of

**Comment by Ehiokn** [comment]
Yes it does need to be installed

**Comment by noubtub** [comment]
I tried installing it again but i get this message

You already have discord_rpc version 1.0.0 installed
is it maybe the wrong version?
Because I wouldnt know what version would be correct!
But thanks alot for your help I really appreciate it!

**Comment by noubtub** [comment]
I AM SO DUMB I FORGOT THE HX TYSM
