### ISSUE TITLE
How to flip the camera horizontally and vertically ?

### ISSUE THREAD

**Issue by BillyLOLwkwk** [ShadowMario/FNF-PsychEngine#14310]
### What is your question?

I tried this line of code here:
`setProeperty("camGame.scaleX", -1) // Horizontally
setProperty("camGame.scaleY", -1) // Vertically`
but it doesn't work

please help, i'm doing it in lua source

**Comment by Vortex2Oblivion** [comment]
camGame.flipX 
camGame.flipY

**Comment by BillyLOLwkwk** [comment]
> camGame.flipX camGame.flipY

When i tried it, it does nothing. when i tried to print it, it also returns nothing means there's no flipX variable inside of the camGame

**Comment by cabfile** [comment]
you could use a shader to do the job

**Comment by Vortex2Oblivion** [comment]
> ### What is your question?
> 
> I tried this line of code here:
> 
> `setProeperty("camGame.scaleX", -1) // Horizontally
> 
> setProperty("camGame.scaleY", -1) // Vertically`
> 
> but it doesn't work

try
```lua
setProperty("camGame.scale.x", -1)

setProperty("camGame.scale.y", -1)
```

**Comment by BillyLOLwkwk** [comment]
> > ### What is your question?
> > I tried this line of code here:
> > `setProeperty("camGame.scaleX", -1) // Horizontally
> > setProperty("camGame.scaleY", -1) // Vertically`
> > but it doesn't work
> 
> try
> 
> ```lua
> setProperty("camGame.scale.x", -1)
> 
> setProperty("camGame.scale.y", -1)
> ```

Nothing really change, yoo why it so hard to really do this man ?

**Comment by BillyLOLwkwk** [comment]
> you could use a shader to do the job

Could you teach me how to do it bro ?

**Comment by cabfile** [comment]
here's a basic shadertoy shader that flips the screen horizontally:
```glsl
void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
    vec2 uv = fragCoord/iResolution.xy;
    uv.x = 1. - uv.x; // replace uv.x with uv.y to flip vertically 
    fragColor = texture(iChannel0,uv);
}
```
just follow a tutorial how to use shadertoy shaders with psych
