### ISSUE TITLE
Type not found : HScript

### ISSUE THREAD

**Issue by xxyuee** [ShadowMario/FNF-PsychEngine#14313]
### Describe your bug here.

⠀

### Command Prompt/Terminal logs (if existing)

```bash
source/states/PlayState.hx:103: characters 32-39 : Type not found : HScript
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Ant643backup2** [comment]
u installed HScript?
