### ISSUE TITLE
"Could not find haxelib 'linc_luajit', does it need to be installed?"

### ISSUE THREAD

**Issue by B1ueRabb1t7** [ShadowMario/FNF-PsychEngine#14317]
### Describe your problem here.

I tried adding shaders but since I'm very new to coding and adding shaders, it resulted in me updating the flixel version because I was told that often times when somethings not right like "source/PlayState.hx - characters 8 - 23: Type not found VCRShaders" even though the file was clearly there. That would result in you not properly not installing whatever is properly not installed, so tried that and got errors about "C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/system/macros/FlxDefines.hx:104: characters 61-65 : Unsupported Haxe version! Supported versions are 4.2.5 or newer (found 4.204).". Not sure what all of this means but any help?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Changed a lot of stuff, like:
Base Scale mode (For the 4:3),
Stages for the songs,
PiracyState (So sites like Gamaverse can't upload it),
Hidden songs, pixelated songs, mechanics (Like dodging), flipping the player's health
2nd Opponent, 2nd Opponent Note, 2nd Oppo X and Y axis, the visibility of 2nd Oppo, Ect.

**Comment by Vortex2Oblivion** [comment]
```haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git```

> Unsupported Haxe version! Supported versions are 4.2.5 or newer (found 4.204).".

Update your haxe version 

> PiracyState (So sites like Gamaverse can't upload it),

They can just remove this so it's kinda useless??

**Comment by B1ueRabb1t7** [comment]
1: I want to but I don't think I can because I'm working with 0.5.2h because I like to work with older builds since I think they're a lot more simpler and not more complicated with the newer builds but that's just my opinion

2: I only added that in because I'll make a site version of it for those who can't download the mod and can play it on the site instead of playing on a site that has thousands of ads popping up in your face

3: How do I update my haxe version?

**Comment by B1ueRabb1t7** [comment]
> 1: I want to but I don't think I can because I'm working with 0.5.2h because I like to work with older builds since I think they're a lot more simpler and not more complicated with the newer builds but that's just my opinion
> 
> 2: I only added that in because I'll make a site version of it for those who can't download the mod and can play it on the site instead of playing on a site that has thousands of ads popping up in your face
> 
> 3: How do I update my haxe version?

1: I want to but I don't think I can because I'm working with 0.5.2h because I like to work with older builds since I think they're a lot more simpler and not more complicated with the newer builds but that's just my opinion

2: I only added that in because I'll make a site version of it for those who can't download the mod and can play it on the site instead of playing on a site that has thousands of ads popping up in your face

3: How do I update my haxe version?

**Comment by B1ueRabb1t7** [comment]
> `haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git`
> 
> > Unsupported Haxe version! Supported versions are 4.2.5 or newer (found 4.204).".
> 
> Update your haxe version
> 
> > PiracyState (So sites like Gamaverse can't upload it),
> 
> They can just remove this so it's kinda useless??

1: I want to but I don't think I can because I'm working with 0.5.2h because I like to work with older builds since I think they're a lot more simpler and not more complicated with the newer builds but that's just my opinion

2: I only added that in because I'll make a site version of it for those who can't download the mod and can play it on the site instead of playing on a site that has thousands of ads popping up in your face

3: How do I update my haxe version?

**Comment by Vortex2Oblivion** [comment]
0.5.2h is not supported any more

**Comment by B1ueRabb1t7** [comment]
> 0.5.2h is not supported any more

Ouch, that really hurts but can you list the versions below 0.7 that are supported? Like is 0.6.3 still supported?
