### ISSUE TITLE
How to open another program through Lua?

### ISSUE THREAD

**Issue by pac2005** [ShadowMario/FNF-PsychEngine#14321]
### What is your question?

How would I open another program through Lua mid-song?

**Comment by Vortex2Oblivion** [comment]
Why on earth would you need to do that??

**Comment by cabfile** [comment]
simple: `os.execute()`

to open notepad you would write `os.execute("notepad")`

**Comment by pac2005** [comment]
> Why on earth would you need to do that??

Fatality Psych port.

**Comment by pac2005** [comment]
> simple: `os.execute()`
> 
> to open notepad you would write `os.execute("notepad")`
