### ISSUE TITLE
How do i add icons into psych engine source

### ISSUE THREAD

**Issue by DxrkPxwer** [ShadowMario/FNF-PsychEngine#14322]
### Describe your problem here.

I recompiled my game after deleting the export folder (bcs of an Goddamn error) and then decided to make most stuff at source
i was using the [Source code Guide](https://gamebanana.com/tuts/13798#H2_3), so it was using the [Funkin-master](https://github.com/FunkinCrew/Funkin) / [Kade Engine](https://github.com/kadedev/Kade-Engine) Source, Making it complicated to add the icons, since i can't do shit in `HealthIcon.hx` bcs there's nothing to add icons

I REALLY need help, since in my other issues, NOBODY comments on there.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nah, just added a characater goddamit

**Comment by KhaiKien** [comment]
you just need to put your character icon to mods/your_mod/images/icons name it icon-your_character  and make sure your icon res is 300 x 150 . i hope this help you

**Comment by Ant643backup2** [comment]
if you want it to be part of /assets just go to assets/shared/images/icons

**Comment by DxrkPxwer** [comment]
> you just need to put your character icon to mods/your_mod/images/icons name it icon-your_character and make sure your icon res is 300 x 150 . i hope this help you

man this ain't helpful
i'm using source
