### ISSUE TITLE
source/ModCore.hx:69: characters 15-28 : You can't iterate on a Dynamic value, please specify Iterator or Iterable

### ISSUE THREAD

**Issue by KhaiKien** [ShadowMario/FNF-PsychEngine#14324]
### Describe your problem here.

![Ảnh chụp màn hình 2024-03-20 160948](https://github.com/ShadowMario/FNF-PsychEngine/assets/163157682/09b565f6-1e68-48e2-9528-379cb6cd48c6)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by mcagabe19** [comment]
there's no named `ModCore` class so that's not og psych engine
