### ISSUE TITLE
'possessRate = possessRate +/- 1;' doesn't work (0 doesn't go up to 1 or something I have no idea how to explain this)

### ISSUE THREAD

**Issue by Your-Local-LordXSimp** [ShadowMario/FNF-PsychEngine#14339]
### Describe your problem here.

`local possessRate = 0;

function onCreate()
    makeLuaText('poss', 'POSSESSION RATE: '..possessRate..'%', 900, -240, 570)
    setObjectCamera('poss', 'HUD')
    setTextFont('poss', 'Stressed.otf')
    setTextColor('poss', 'FF190C')
    setTextSize('poss', 45)
    addLuaText('poss')
end

function onUpdate(elapsed)
    setTextString('poss', ..possessRate)
    health = getProperty('health')
    if getProperty('health') - 1 then
        possessRate = possessRate + 1;
    elseif getProperty('health') + 1 then
        possessRate = possessRate - 1;
    end
end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by SmallSquareStudios** [comment]
```
if getProperty('health') < 1 then
    possessRate += 1
elseif getProperty('health') > 1 then
    possessRate -= 1
```

**Comment by Your-Local-LordXSimp** [comment]
`'=' expected near '+'`

**Comment by xxyuee** [comment]
`function onUpdate()
    setTextString('poss', ''..possessRate..'%')
    health = getProperty('health')
    if getProperty('health') < 1 then
        possessRate = possessRate + 1
    elseif getProperty('health') > 1 then
        possessRate = possessRate - 1
    end
end`
is this what u meant ??

**Comment by Your-Local-LordXSimp** [comment]
Yeah, I just realized it wouldn't work if it's +/-= lol. It still doesn't work though, but I appreciate you trying. :)
