### ISSUE TITLE
Cant compile it

### ISSUE THREAD

**Issue by MisterOficerPL** [ShadowMario/FNF-PsychEngine#1433]
### Describe your problem here.

i tried to compile psych engine with and without modification and this crap comes up
obj\msvc1964-nc\70dda274_pcre_exec.obj : fatal error LNK1136: invalid or corrupt file

![SharedScreenshot](https://user-images.githubusercontent.com/95174349/143769886-12d62d2f-c605-4095-bc35-01296131c5d4.jpg)

i have installed vsc 2019 with tools and i compiled kade engine already

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes I edited coolutil.hx adding new difficulty

**Comment by Collabvmisgood** [comment]
might be 
corrupted

**Comment by MisterOficerPL** [comment]
but what might be corrupted

**Comment by Collabvmisgood** [comment]
obj\msvc1964-nc\70dda274_pcre_exec.obj file.

**Comment by Collabvmisgood** [comment]
or in export\debug\obj\msvc1964-nc\70dda274_pcre_exec.obj

**Comment by Collabvmisgood** [comment]
or export\release\obj\msvc1964-nc\70dda274_pcre_exec.obj

**Comment by MisterOficerPL** [comment]
gonna check it

**Comment by MisterOficerPL** [comment]
i uncompressed source code and now im compiling it at now no errors gonna post an update if it compiles and launches

**Comment by MisterOficerPL** [comment]
it compiled thanks for help

**Comment by MisterOficerPL** [comment]
really thankd

**Comment by Collabvmisgood** [comment]
your welcome.
