### ISSUE TITLE
What is this????

### ISSUE THREAD

**Issue by KitKatLikeToCode** [ShadowMario/FNF-PsychEngine#14330]
### Describe your bug here.

I think it says I am missing a file but I'm not

![Screenshot (96)](https://github.com/ShadowMario/FNF-PsychEngine/assets/104602024/9d5dd899-11da-42b3-b555-d440a3ffdc6f)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added songs, sprites, and a week, but this is targeted to the song

**Comment by Ant643backup2** [comment]
somethings wrong with your .ogg file probably
