### ISSUE TITLE
how can I disable ghostTapping using lua?

### ISSUE THREAD

**Issue by EstufaVoladora3000** [ShadowMario/FNF-PsychEngine#14334]
### What is your question?

in previous versions it was using "setProperty('ClientPrefs', 'ghostTapping', false)"
but in the latest version that doesn't work

**Comment by Stefan2008Git** [comment]
`setProperty('backend.ClientPrefs', 'data.ghostTapping', false)`

**Comment by Stefan2008Git** [comment]
Better to know is PE 0.7+ has some changes for ClientPrefs. More explained info in [Transitioning page](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7)
