### ISSUE TITLE
Run vbs file from lua

### ISSUE THREAD

**Issue by Surepart** [ShadowMario/FNF-PsychEngine#14333]
### What is your question?

how to run .vbs file with lua??

**Comment by TheoDevelops** [comment]
lol

**Comment by TheoDevelops** [comment]
it is impossible natively, what you can do is run it from cmd with a Process from sys.io.Process

**Comment by Surepart** [comment]
damn,
 not for lua

**Comment by xxyuee** [comment]
os.execute("[path]/[filename].vbs")
