### ISSUE TITLE
problem while trying to compile/export the build of psych 0.6.3

### ISSUE THREAD

**Issue by Adamusique** [ShadowMario/FNF-PsychEngine#14335]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/162884957/f7819b58-fea2-4687-884a-e9136a7d8b6d)
Basically when i make lime test windows it make this error 
i'm asking how i can fix that

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i changed nothing

**Comment by Ant643backup2** [comment]
lib versions? (just run haxelib list and send me what it outputs)
