### ISSUE TITLE
Stage not importing

### ISSUE THREAD

**Issue by Saulgoodmanondrugs** [ShadowMario/FNF-PsychEngine#14345]
### Describe your problem here.

![problem](https://github.com/ShadowMario/FNF-PsychEngine/assets/134774324/345f941d-bc8b-4ed3-b0e3-8d3d71e08a75)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i tried to add a new background

**Comment by ender69funk** [comment]
Bro forgor to use `end` for real 💀

**Comment by Saulgoodmanondrugs** [comment]
i added "end" it just doesn't want to work
