### ISSUE TITLE
How to make a week unlock only if you beat the previous one on a certain difficulty?

### ISSUE THREAD

**Issue by NicklGames** [ShadowMario/FNF-PsychEngine#1434]
### What is your question?

I mean, for example: you need to beat week 1 on hard to unlock week 2, week 2 on hard to unlock week 3 and so on

**Comment by XtraXD1** [comment]
I guess it's not possible in LUA version, and you have to download the Source Code and edit it.

**Comment by NicklGames** [comment]
> I guess it's not possible in LUA version. You must download the Source Code and edit it.

i AM already using sauce code

**Comment by MayoALT** [comment]
> > I guess it's not possible in LUA version. You must download the Source Code and edit it.
> 
> i AM already using sauce code

USE THE HELP WANTED TEMPLATE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! also you can look at the way achievements are unlocked to help you (look up achievements.hx in playstate.hx)

**Comment by ShadowMario** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/44785097/144627232-0b1f99a5-1c99-4ec5-88db-ee5031f92023.png)
On Week Editor, duh
