### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by niopoooooooooooooooooooooooo** [ShadowMario/FNF-PsychEngine#14344]
### Describe your bug here.

When trying to compile the main psychological engine it tells me source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall

### Command Prompt/Terminal logs (if existing)

```bash
visual studio code
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ender69funk** [comment]
Update ur SScript
