### ISSUE TITLE
song speed

### ISSUE THREAD

**Issue by GreenCalebGaming** [ShadowMario/FNF-PsychEngine#14343]
### Describe your bug here.

I don't know how I did it but my game is stuck at a scroll speed of 1 and it stays the same through every song, and I have no idea how it happened

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, I added a few assets and added a few songs

**Comment by niopoooooooooooooooooooooooo** [comment]
Presione el boton ctrl en freeplay

**Comment by SmallSquareStudios** [comment]
Press ctrl on the story mode or freeplay menu to check the scroll speed modifier. If it's set to constant, it will only play at that speed. Set it to multiply instead.
