### ISSUE TITLE
Genuinely, camera motion on note hit.

### ISSUE THREAD

**Issue by Average-FNF-Modder** [ShadowMario/FNF-PsychEngine#14347]
### What feature do you want to get added on the **base** engine?

Almost every mod has this in there, it is so cool and so universally excepted to be cool at this point I think you should just make it a built in feature the player can change the intensity/velocity of in Options. I'm not even kidding.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
ain't happening

**Comment by Average-FNF-Modder** [comment]
*Insert crying emoji dying meme*
