### ISSUE TITLE
MIDSONG CUTSCENE

### ISSUE THREAD

**Issue by Komorie6** [ShadowMario/FNF-PsychEngine#14353]
### Describe your problem here.

could i please have some help as of how to play a midsong cutscene

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by JHAM25** [comment]
Pues yo había echo esto en un mod:
function onStepHit()
    if curStep == 1180 then
        setProperty('inCutscene', true)
        startVideo('videoAqui')

    end
    if curStep == 1440 then
        setProperty('inCutscene', false)--------esto lo tiene que poner cuando termine el video
    end
end

**Comment by JHAM25** [comment]
Te funciono?
