### ISSUE TITLE
Compiling problem psychsource

### ISSUE THREAD

**Issue by Linekr** [ShadowMario/FNF-PsychEngine#14356]
### Describe your bug here.

Hi i just wanted to compile the source and than after tiping lime test windows this appeared "C:\Users\Admin\Downloads\FNF-PsychEngine-main\FNF-PsychEngine-main>lime test windows
source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall" HOW DO I SOLVE THIS?

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\Admin\Downloads\FNF-PsychEngine-main\FNF-PsychEngine-main>lime test windows
source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No i did not.

**Comment by LarryFrosty** [comment]
replace all instances of TeaCall to Tea

**Comment by Linekr** [comment]
> replace all instances of TeaCall to Tea

thx
