### ISSUE TITLE
Compliling issues

### ISSUE THREAD

**Issue by St4rlo** [ShadowMario/FNF-PsychEngine#14354]
### Describe your problem here.

everytime i fix one thing a new problem arises and no body else can help!!
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/134467111/51c25f4d-15bb-4061-9338-c5da3d4e1fec)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

fixed teacall to tea

**Comment by St4rlo** [comment]
SORRY NVM FIGURED IT OUT

**Comment by ShadowMario** [comment]
When you figure out your issue, please close your thread.
