### ISSUE TITLE
Trouble fading out the HUD/arrows with a script using 'i'

### ISSUE THREAD

**Issue by Average-FNF-Modder** [ShadowMario/FNF-PsychEngine#14351]
### Describe your problem here.

I'm trying to have your HUD go away and then fade back in at the start of a song, and I know I could do all the items manually, but I've been meaning to learn to use 'for i = whatev' to clean up my coding and not have giant blocks of code for multiple of the same action. Unfortunately, I can't seem to get it to work properly.

Here is some code:
```
function onCreatePost()
	makeLuaSprite('blackbg', '', 0, 0)
	setScrollFactor('blackbg', 0, 0)
	makeGraphic('blackbg', 3840, 2160, '000000')
	addLuaSprite('blackbg', false)
	setProperty('blackbg.alpha', 0)
	screenCenter('blackbg', 'xy')
	setObjectOrder('blackbg', 50)
	doTweenAlpha('uigone', camHUD, 0, 0.1, 'quadOut')
	setObjectCamera('blackbg', 'camGame')
	local hudItems = {'scoreTxt','timeBar','timeTxt','timeBarBG','healthBar','healthBarBG','iconP1','iconP2','helpBar'}

--'timeBar',
--'timeBarBG',
--'healthBar',
--'healthBarBG',
--'iconP1',
--'iconP2',
--'timeTxt',
--'scoreTxt'
end

function onCountdownTick(counter)
	if counter == 3 then
		--cameraFlash(game, '000000', 13, true)
		--cameraFlash(hud, '000000', 13, true)
		setProperty('blackbg.alpha', 1)
		for i = 0,8 do
			doTweenAlpha('hudItemsAlpha'..i, huditems[i], 0, 0.01, 'expoOut')
		end
		for i = 0,7 do
			noteTweenAlpha('noteAlpha'..i, i, 0, 0.1, 'linear')
		end
	elseif counter == 4 then
		--cameraFlash(game, '000000', 11, true)
		--cameraFlash(hud, '000000', 11, true)	
	end
end
```
This is a relatively large block of my code with attempts to use i to fade things out, and I'm looking for help with problems this code might have or something, cause it genuinely just doesn't do anything at the moment. Thanks!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, sure didn't.

**Comment by frantastic24** [comment]
`hudItems` being declared as `local` means it only exists inside `onCreatePost`

**Comment by Average-FNF-Modder** [comment]
Fuck I'm stupid, thanks. I'll try it tmmr.
