### ISSUE TITLE
Compiling Problem (HELP ME)

### ISSUE THREAD

**Issue by Linekr** [ShadowMario/FNF-PsychEngine#14359]
### Describe your problem here.

i tried to compile typing lime test windows after 2 seconds this appeared "source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat should be declared with 'override' since it is inherited from superclass flixel.graphics.frames.FlxAtlasFrames
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat overrides parent class with different or incomplete type
C:/HaxeToolkit/haxe/lib/flixel/5,6,2/flixel/graphics/frames/FlxAtlasFrames.hx:454: characters 18-24 : ... Base field is defined here
C:/HaxeToolkit/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : ... Different number of function arguments
source/backend/Paths.hx:605: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)
source/objects/Character.hx:304: characters 87-101 : flxanimate.animate.FlxAnim has no field lastPlayedAnim
source/objects/Character.hx:335: characters 20-26 : flxanimate.animate.FlxAnim has no field resume" Help. How do i Fix this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes I did all instances of TeaCall in the file source psychlua Hscript.hx  to Tea.

**Comment by LarryFrosty** [comment]
assuming you're using 0.7.2 or higher, you should look at this
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by Realmzer** [comment]
Update your Libs and try using haxe 4.3.2 as recommended
Also you will want to set SScript to 7.7.0 since later versions break the Hscript and then TeaCall will work make sure to revert it back to TeaCall.
You can also use the BAT included. 

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/120264700/18f4a252-d6ee-4c79-9025-4a52981b9ed6)

Use the setup-windows.bat for the libraries

**Comment by Linekr** [comment]
after I did as you said i compieled and showed me this:  ------------------------SScript 7.7.0 Macro------------------------
Special Thanks:
- CrowPlexus

Checking version...
There was an error getting the latest version info, you may not have internet connection.
Continuing...
-------------------------------------------------------------------

source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID);   PLEASE HELP ME

**Comment by Realmzer** [comment]
you might want to completely reinstall haxe it fixed it for me

**Comment by Realmzer** [comment]
I also made a better setup-windows.bat

[setup-windows.bat](https://www.mediafire.com/file/ssbh7qkh0w9vgdy/setup-windows.bat/file)

**Comment by LarryFrosty** [comment]
> you might want to completely reinstall haxe too. It fixed it for me
> 
> C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID); Ignore this error its nothing. 
> 
> source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
> For this you can delete this part
> 
> ![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/120264700/f3a58da0-0422-41e6-8eb9-dfe10393be12)
> 
> 
> export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
> For this delete settings.cocoa, its the SScript settings. Its located in this folder 
> 
> ![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/120264700/7df87ba8-5d45-4704-9910-aa6d73328c6a)
> after users its your username for your computer.
> 
> When it asks you to enable macros for SScript press (n) and press and enter and the others is what you want.
> 
> ![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/120264700/22a51d6b-bf4f-4570-b509-8b9ba1553bae)
> 
> Would recommend following this
> 

or you can just
```
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
```

**Comment by Linekr** [comment]
THX SO MUCH GUYS I THINK ITS WORKING!!!

**Comment by Realmzer** [comment]
> THX SO MUCH GUYS I THINK ITS WORKING!!!

no problem just close your issue
