### ISSUE TITLE
Ingrainedv2 mod crashed upon hitting first note

### ISSUE THREAD

**Issue by TeeJay125Z** [ShadowMario/FNF-PsychEngine#14361]
### Describe your bug here.

![crash report](https://github.com/ShadowMario/FNF-PsychEngine/assets/165101417/bac9ade1-d10e-4793-a08d-3a582fe2ec1e)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

.

**Comment by ender69funk** [comment]
Mod folder problem
