### ISSUE TITLE
what the gear in mods section do?

### ISSUE THREAD

**Issue by Shiho-cmd** [ShadowMario/FNF-PsychEngine#14360]
### What is your question?

i'm talking about that gear that was added in 0.7
![Screenshot_29](https://github.com/ShadowMario/FNF-PsychEngine/assets/146484710/0171e98a-6f03-49ce-a919-7620edc2eeaa)
what is it for?

**Comment by sofyisstupid** [comment]
It's settings

**Comment by Average-FNF-Modder** [comment]
You can make a mod settings Json that will appear to mod users there.

**Comment by Average-FNF-Modder** [comment]
It's on the wiki FAQ, but I've grabbed the code.
```
[
	// All types:
	// bool - Has a checkbox only, meaning it can only be 'true' or 'false'.
	// int - Numbers with no decimals (ex. 1, 3, 9, -1)
	// float - Similar to int, but numbers can have decimals (ex. 1.5, 2.75)
	// percent - Similar to float, but the displayed value is multiplied by 100 (ex. 1.1 will be displayed as "110%")
	// string - A text instead of numbers/false and true, you gotta set up "options" variable to it
	// key - TO BE IMPLEMENTED
	{
		"save": "testbool",
		"name": "Test Bool Option", //Name shown on the mod settings menu
		"type": "bool",
		"description": "This is a test bool option", //Description shown on the mod settings menu
		"value": true //This is the default value
	},
	{
		"save": "testnumber",
		"name": "Test Number Option",
		"type": "float", //
		"description": "This is a test number option",
		"value": 5,
	
		// Int/Float/Percent only variables
		"min": 0, //How low can the value be
		"max": 10, //How high can the value be
		"step": 1, //How much is changed at once when you press left/right

		// Float/Percent only variables
		"decimals": 1, //If your option is type 'float' or 'percent', you should probably make it have atleast 1 decimal places
		"scroll": 5 //How fast you scroll while holding left/right (in this case, it changes 5 per second)
	},
	{
		"save": "teststring",
		"name": "Test String Option",
		"type": "string",
		"description": "This is a test string option",
		"value": "Sun",
		"format": "%vday", //Text formatting, '%v' means 'current value', so if my current value is 'Fri', it wil be shown as 'Friday'. You can also use '%d' to represent the default value

		// String only variables
		"options": ["Sun", "Mon", "Tues", "Wednes", "Thurs", "Fri", "Satur"] //Available options to choose
	},
	{
		"save": "testkey",
		"name": "Test Custom Key",
		"type": "keybind",
		"keyboard": "T",
		"gamepad": "RIGHT_TRIGGER"
	}
]
```
Paste that it to mods/data as settings.json and modify it your mods needs. To use it with Lua, use the function getModSetting("The settings name here").

**Comment by Shiho-cmd** [comment]
> It's on the wiki FAQ, but I've grabbed the code.
> ```
> [
> 	// All types:
> 	// bool - Has a checkbox only, meaning it can only be 'true' or 'false'.
> 	// int - Numbers with no decimals (ex. 1, 3, 9, -1)
> 	// float - Similar to int, but numbers can have decimals (ex. 1.5, 2.75)
> 	// percent - Similar to float, but the displayed value is multiplied by 100 (ex. 1.1 will be displayed as "110%")
> 	// string - A text instead of numbers/false and true, you gotta set up "options" variable to it
> 	// key - TO BE IMPLEMENTED
> 	{
> 		"save": "testbool",
> 		"name": "Test Bool Option", //Name shown on the mod settings menu
> 		"type": "bool",
> 		"description": "This is a test bool option", //Description shown on the mod settings menu
> 		"value": true //This is the default value
> 	},
> 	{
> 		"save": "testnumber",
> 		"name": "Test Number Option",
> 		"type": "float", //
> 		"description": "This is a test number option",
> 		"value": 5,
> 	
> 		// Int/Float/Percent only variables
> 		"min": 0, //How low can the value be
> 		"max": 10, //How high can the value be
> 		"step": 1, //How much is changed at once when you press left/right
> 
> 		// Float/Percent only variables
> 		"decimals": 1, //If your option is type 'float' or 'percent', you should probably make it have atleast 1 decimal places
> 		"scroll": 5 //How fast you scroll while holding left/right (in this case, it changes 5 per second)
> 	},
> 	{
> 		"save": "teststring",
> 		"name": "Test String Option",
> 		"type": "string",
> 		"description": "This is a test string option",
> 		"value": "Sun",
> 		"format": "%vday", //Text formatting, '%v' means 'current value', so if my current value is 'Fri', it wil be shown as 'Friday'. You can also use '%d' to represent the default value
> 
> 		// String only variables
> 		"options": ["Sun", "Mon", "Tues", "Wednes", "Thurs", "Fri", "Satur"] //Available options to choose
> 	},
> 	{
> 		"save": "testkey",
> 		"name": "Test Custom Key",
> 		"type": "keybind",
> 		"keyboard": "T",
> 		"gamepad": "RIGHT_TRIGGER"
> 	}
> ]
> ```
> Paste that it to mods/data as settings.json and modify it your mods needs. To use it with Lua, use the function getModSetting("The settings name here").

Thank you helped a lot!!!

**Comment by Average-FNF-Modder** [comment]
Yup, anytime.
