### ISSUE TITLE
Note Strums not having the RGB shader disabled with the Notes

### ISSUE THREAD

**Issue by HourOfEternity** [ShadowMario/FNF-PsychEngine#14365]
### Describe your bug here.

So I'm trying to make a song where the note strums, the note splashes and the notes themselves go B&W at a certain point, but not at the beginning, so I can't disable note RGB in the chart editor.
![Screenshot 2024-03-27 103921](https://github.com/ShadowMario/FNF-PsychEngine/assets/161889439/4b984831-8261-45b0-aa3e-3e0ad6ae14e5)
I have this code in it, and as expected, it only disables the RGB shader for the unspawned notes, while leaving the splashes and the strums normal.
![Screenshot 2024-03-18 071636](https://github.com/ShadowMario/FNF-PsychEngine/assets/161889439/78bdb411-50dc-4689-8d7c-25c68a74d2d5)
I have no idea how to disable the RGB shader for the noteStrums and the noteSplashes; I have tried many different scripts and none of them work.
Any ideas?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed the NOTE_assets.png and NOTE_assetsENDS.png in the pixelUI (assets folder, not mods) to be a black and white version, then changed the Note Colors in the RGB menu to be normal colored notes.

**Comment by HourOfEternity** [comment]
> You need to also change strumline, grpSplashNotes and notes as well, unspawnNotes are not enough

Could you give me a quick example of how to do the strumline? I can do the grpSplashNotes easily enough. Anyway, thank you! You saved me so much time; I spent around a month trying to get this to work. I didn't even know about grpSplashNotes.

**Comment by HourOfEternity** [comment]
I've got code that SHOULD work, but it still doesn't
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/161889439/7acb2c79-a96f-4d7e-88a7-61db32c792bb)
I have no idea why.

**Comment by LarryFrosty** [comment]
> I've got code that SHOULD work, but it still doesn't
> ![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/161889439/7acb2c79-a96f-4d7e-88a7-61db32c792bb)
> I have no idea why.

Disable `useRGBShader` instead of `rgbShader.enabled`.

`rgbShader.enabled` does not work because the shader constantly gets disabled and enabled depending on the strum's animation.

**Comment by HourOfEternity** [comment]
> Disable `useRGBShader` instead of `rgbShader.enabled` for strums.
> 
> `rgbShader.enabled` does not work because the shader constantly gets disabled and enabled depending on the strum's animation.

This worked amazingly for the strumline, but now the notesplashes do not change. Any idea why? If there's no solution, I'll turn them off. Thank you!

**Comment by LarryFrosty** [comment]
> > Disable `useRGBShader` instead of `rgbShader.enabled` for strums.
> > 
> > `rgbShader.enabled` does not work because the shader constantly gets disabled and enabled depending on the strum's animation.
> 
> This worked amazingly for the strumline, but now the notesplashes do not change. Any idea why? If there's no solution, I'll turn them off. Thank you!

Disable `noteSplashData.useRGBShader` on the notes.

**Comment by HourOfEternity** [comment]
> Disable `noteSplashData.useRGBShader` on the notes.

Thank you SO MUCH! It worked! I cannot express how long I've been at this.

Just for anyone who wants to know what the event looks like:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/161889439/1aafc44f-7759-41cf-9ca1-8df68a3d0690)
