### ISSUE TITLE
game crashes everytime i open controls

### ISSUE THREAD

**Issue by Veloi3** [ShadowMario/FNF-PsychEngine#14369]
### Describe your bug here.

basically i downloaded psyche completely fresh, and whenever i go into the controls to set my keybinds it immediately crashes
[PsychEngine_2024-03-28_01'01'14.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/14784165/PsychEngine_2024-03-28_01.01.14.txt)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i just downloaded it

**Comment by ender69funk** [comment]
you didn't change anything in the code?

**Comment by Veloi3** [comment]
nope, i just downloaded it from the gamebanana page
