### ISSUE TITLE
doesn't compile video folder and idk why

### ISSUE THREAD

**Issue by Robert124l** [ShadowMario/FNF-PsychEngine#14374]
### Describe your problem here.

I compiled psych in version 7.3 and it works perfectly... except that it doesn't compile the videos folder and therefore, it doesn't compile the cutscenes. I don't understand why this happens if I literally have the same library that the engine recommends... LOOK!!
![Captura de pantalla (676)](https://github.com/ShadowMario/FNF-PsychEngine/assets/102814421/ebe4b1ec-eae2-41f6-b85b-92a1050002d0)
![Captura de pantalla (677)](https://github.com/ShadowMario/FNF-PsychEngine/assets/102814421/d81219fe-ed9b-4147-95a3-e6e59dcaef8f)

![Captura de pantalla (678)](https://github.com/ShadowMario/FNF-PsychEngine/assets/102814421/25c0b7af-234d-43cc-8cc9-ac468458c114)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Filip55561** [comment]
Isn't it In shared?
