### ISSUE TITLE
Compiling issue PLEASE HELP

### ISSUE THREAD

**Issue by Linekr** [ShadowMario/FNF-PsychEngine#14387]
### Describe your problem here.

i tried compiling after i installed some things, and GAVE ME THIS!: ------------------------SScript 7.7.0 Macro------------------------
Special Thanks:

CrowPlexus
Checking version...
There was an error getting the latest version info, you may not have internet connection.
Continuing...
source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID); PLEASE HELP ME

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No i did not.

**Comment by henrique-gabrieil** [comment]
deu o mesmo problema comigo
