### ISSUE TITLE
how do i fix this?

### ISSUE THREAD

**Issue by My-Honest-Reaction** [ShadowMario/FNF-PsychEngine#14381]
### Describe your problem here.

openfl/media/Sound.hx (line 407)
backend/Paths.hx (line 442)
states/editors/ChartingState.hx (line 1438)
states/editors/ChartingState.hx (line 418)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Error loading sound from file: mods/Battle/songs//beat-battle/Voices.ogg
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Filip55561** [comment]
/songs// why are there two  //? there should be only one buddy

**Comment by DaKidWize** [comment]
I Had this problem and the way I fixed it was by using a file convertor I converted my original Voices.ogg and Isnt.ogg files and put them in and it worked
