### ISSUE TITLE
Character Change Event Changes BF No Matter What

### ISSUE THREAD

**Issue by BL0KYBL0K** [ShadowMario/FNF-PsychEngine#1439]
### Describe your problem here.

I have been using the lua based downloaded build since psych engine came out and only now am i having trouble
when using the character change event it changes only bf weather i have dad or gf selected
examples :
![image](https://user-images.githubusercontent.com/88749184/143775132-496b3598-69e3-4474-957d-44ac8ec8ace5.png)

![image](https://user-images.githubusercontent.com/88749184/143775142-15ba8eb9-a7ed-4680-a391-a509a985f11a.png)

its changine bf when i have dad selected

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

all i did was add a character and a stage threw lua and every thing else works fine i have tried reinstalling psych engine to. so not much

**Comment by BL0KYBL0K** [comment]
Update i tried changing characters on a brand new psych with no edits at all and its still happing

**Comment by SrtHero278** [comment]
They're numbers. They haven't gotten to changing it yet.
0 is bf, 1 is dad, and 2 is gf.

**Comment by BL0KYBL0K** [comment]
thanks
