### ISSUE TITLE
how can i make a custom transition?

### ISSUE THREAD

**Issue by SlushieDrawzCoolDrawingX480** [ShadowMario/FNF-PsychEngine#14394]
### Describe your problem here.

how can i make a custom song transition

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JVgradiz** [comment]
if it is on the start of the song:
1 - call return Function_Stop on the onStartCountdown()
2 - Do your custom transition
3 - call startCountdown()

if it is on the end of the song
1 - call return Function_Stop on the onEndSong()
2 - Do your custom transition
3 - call endSong();
