### ISSUE TITLE
Vocals not playing properly on 0.7.3

### ISSUE THREAD

**Issue by Daboss7173** [ShadowMario/FNF-PsychEngine#14397]
### Describe your bug here.

Pretty much sometimes whenever playing a song the vocals can act up and play... well just watch the video and see for yourself.

https://streamable.com/7rgvx5

I'm not all that sure what causes this but I'm pretty sure it has something to do with the voices getting split into two tracks, as this bug didn't occur prior to me updating to 0.7.3, so that just makes the most logical sense.

Anyway best of luck fixing this, it's definitely a weird one.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Pretty much just ported VsMatt and Wiik3 to Lua. This meant remaking the stages and characters. Not really anything that would affect this.

**Comment by HourOfEternity** [comment]
What exactly is the problem? I watched the video and nothing seemed wrong.

**Comment by Daboss7173** [comment]
> What exactly is the problem? I watched the video and nothing seemed wrong.

Listen to the audio and listen closely. During the first time playing the song you can hear a bunch of audio cutting in the vocal track. If you want a direct comparison you can just skip between 0:34 and 1:20 in the video.

**Comment by HourOfEternity** [comment]
Ah. I've also been having that. Its not a bug, per se, but more of how fnf handles headphones. I've found no real way to fix it other than just restarting the song after getting into it.

**Comment by Luscious77** [comment]
but that wasn't happening in previous versions, what exactly changed to cause it so that maybe rolling back is an option

**Comment by HourOfEternity** [comment]
I've found something that might affect it, as it is the only update relating to the vocals in around 2 years, so it _might_ be the problem:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/161889439/a2f3f8c7-5f76-4294-8c16-427209685d13)
I would see if the bug still occurs on 0.7.2h myself, but my pc is crappy and can only handle one version of psych. Hope this helps, if even a bit!
