### ISSUE TITLE
Change Characters default camera_position in Lua

### ISSUE THREAD

**Issue by Surepart** [ShadowMario/FNF-PsychEngine#14398]
### Describe your problem here.

How to Change Default character Camera_position without modify character json file in lua?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by xxyuee** [comment]
function onUpdate()
    if boyfriendName == "" then --or dadName
        setProperty('boyfriend.cameraPosition[0]',) --x pos
        setProperty('boyfriend.cameraPosition[1]',) --y pos
    end
end
