### ISSUE TITLE
Add something like getKeyJustPressed

### ISSUE THREAD

**Issue by LionKrono** [ShadowMario/FNF-PsychEngine#14392]
### What feature do you want to get added on the **base** engine?

something similar to that, a function just like keyboardJustPressed('key') but instead of specifying what key does it need to check, it checks what's the first key pressed after the command was activated.

Something like:

GetKeyPressed("keyboardThing")
makeLuaText("keyJustPressed", "you just pressed".. keyboardThing,  100, x, y)
addLuaText("keyJustPressed")

Using the space inside the "GetKeyPressed" to name it as a variable or something like that, it would improve a fouple of things

**Comment by Average-FNF-Modder** [comment]
Lil' bro you failed the easiest test, how do people keep messing that up? Your issue will probably be ignored if you don't fix the dropdown answer you put. It's not asking what type of request this is, it's asking you what kind of thing to **_NOT_** request.

**Comment by ShadowMario** [comment]
Failed the test
