### ISSUE TITLE
something happened to my mod

### ISSUE THREAD

**Issue by Baconyy33** [ShadowMario/FNF-PsychEngine#14396]
### Describe your bug here.

so i go in, and then it says error

### Command Prompt/Terminal logs (if existing)

```bash
Paths.hx (line 352)
MainMenuState.hx (line 77)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

NO

**Comment by JHAM25** [comment]
O manda el link del mod
