### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Lanks78** [ShadowMario/FNF-PsychEngine#14391]
### Describe your bug here.

i am in a rush so i need help on fixing this, i was trying to compile psych engine 0.6.2 but this shows up. I don't know what i did to mess with something or idk but i need help fixing this, i tried looking up some issues about it and i couldn't find anything about it

### Command Prompt/Terminal logs (if existing)

```bash
C:/HaxeToolkit/haxe/lib/linc_luajit/git/llua/Convert.hx:92: characters 11-12 : Missing type declaration
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i didn't edit anything

**Comment by xxyuee** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/12876 u checked this already?

**Comment by Lanks78** [comment]
yeah i already did that but it didn’t work but, i recompiled the build by delete all the haxe files i have and reinstalling them and compile them again so uh, we’re all good
