### ISSUE TITLE
Blammed lights issue - Windows not lighting up

### ISSUE THREAD

**Issue by KindOfASpork** [ShadowMario/FNF-PsychEngine#144]
pretty standard stuff. the lights event in Blammed doesn't show the windows.

it worked in 0.4 and older, but it broke in 0.4.1.

this is what it was like before - https://streamable.com/vt3nx8

and this is what it looks like now - https://streamable.com/bf2jpt

**Comment by ShadowMario** [comment]
Fixed it on main repo now
