### ISSUE TITLE
BUILDING ISSUE

### ISSUE THREAD

**Issue by KxleyStudios** [ShadowMario/FNF-PsychEngine#14406]
### Describe your problem here.

When I build the game... It shows this

source/states/PlayState.hx:36: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
source/psychlua/FunkinLua.hx:16: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall

this is for the recent build... what do I do?

### Are you modding a build from source or with Lua?

HX

### What is your build target?

Windows x64

**Comment by xxyuee** [comment]
replace TeaCall with Tea or set your SScript to 7.7.0, [check ur library versions](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)

**Comment by KxleyStudios** [comment]
> replace TeaCall with Tea or set your SScript to 7.7.0, [check ur library versions](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)

How??? I did and it still wont work!
