### ISSUE TITLE
Psych Engine is Broken

### ISSUE THREAD

**Issue by ii-haso** [ShadowMario/FNF-PsychEngine#14407]
### Describe your bug here.

Psych Engine is broken, girlfriend isn't moving, songs only play the 1st note, there is no audio, and the intro text was gone, not only was this problem in a fresh copy, it was also on older versions too.
![Screenshot 2024-04-04 114143](https://github.com/ShadowMario/FNF-PsychEngine/assets/166004620/f1a6e3a7-2565-488f-9b98-79e8a22ac867)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I had an edited build where the problem happened (i edited it to add credits) but then when the problem started, Psych Engine was basically unplayable, even on older versions.

**Comment by SrBagel** [comment]
Are you using headphones? If so unplug them, close the game, plug your headphones back in, and load the game again. That should fix the game if you were using headphones. Otherwise I'm not sure.
