### ISSUE TITLE
Splashes and effects on sustains.

### ISSUE THREAD

**Issue by Average-FNF-Modder** [ShadowMario/FNF-PsychEngine#14405]
### What feature do you want to get added on the **base** engine?

You know how in the newest FNF charting teaser there is an effect for holding down sustains and an extra little splash at the end of the hold? You can probably do this with Lua, but I feel like this should be a base feature. You could also add getting extra points for timing your release of the sustain or sum', idk.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
No, I'm not going to copy stuff from teasers, that's disrespectful to the devs.

**Comment by Average-FNF-Modder** [comment]
Fair enough ig.
