### ISSUE TITLE
Variant Custom Note Type Textures Based On Note Skin

### ISSUE THREAD

**Issue by Average-FNF-Modder** [ShadowMario/FNF-PsychEngine#14402]
### What feature do you want to get added on the **base** engine?

I think there should be a built in feature where custom note types can have different skins based in the note skin the player has selected so it doesn't look weird. I'm pretty sure there is no note skin variable currently, though I could be wrong, but even if there is this feels like it shouldn't require Lua at all, I think you should just be able to tack a dash on the end of the assets and put which skin it corresponds to.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by DetectiveBaldi** [comment]
the variable is literally called `noteSkin` 😭
