### ISSUE TITLE
Just got one question.

### ISSUE THREAD

**Issue by mycreationisitreal** [ShadowMario/FNF-PsychEngine#14400]
### What is your question?

What the heck is a "TeaCall"

Cuz i have an error saying: source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall

but I have no idea what a TeaCall is

**Comment by xxyuee** [comment]
idk what it is 🙁 js replace TeaCall with Tea

**Comment by Unhearlydemisiom** [comment]
How do you replace Teacall with Tea?
