### ISSUE TITLE
somethings wrong AGAIN

### ISSUE THREAD

**Issue by MisterOficerPL** [ShadowMario/FNF-PsychEngine#1440]
### Describe your problem here.

i can normally compile the game from source but when i add a new difficulty them i get this shit:
![image](https://user-images.githubusercontent.com/95174349/143775488-bb3a5ba5-9e5e-4427-8fb0-f3ab7745af19.png)
source/CoolUtil.hx:24: characters 13-14 : Expected ]

this is my coolutil.hx screenshot :
![image](https://user-images.githubusercontent.com/95174349/143775529-ee494664-b22c-44ce-8ffe-b3cc7ba24dd0.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes I edited coolutil.hx adding new difficulty

**Comment by BL0KYBL0K** [comment]
you need to add a , after hard to seperate your difficulty from the hard one 
![image](https://user-images.githubusercontent.com/88749184/143775738-0c8e56d5-ee21-41ca-9cf0-45cb944b0a66.png)

**Comment by MisterOficerPL** [comment]
thanks for help

**Comment by BL0KYBL0K** [comment]
no problem
