### ISSUE TITLE
change pausemenu song in psych engine 0.7 above

### ISSUE THREAD

**Issue by Surepart** [ShadowMario/FNF-PsychEngine#14415]
### Describe your problem here.

i'm trying using this 
setPropertyFromClass('PauseSubState', 'songName', '')
but it doesn't work in newer psych engine version

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
`substates.PauseSubState`
