### ISSUE TITLE
Compiling for one platform from another

### ISSUE THREAD

**Issue by sodapopzz** [ShadowMario/FNF-PsychEngine#14421]
### What is your question?

Windows user. I'm using Psych to make a sort of joke mod to distribute to a friend group, but we're all on different platforms. A few of us daily drive windows, a few of us daily drive mac, and a one of us daily drives linux(debian based, I believe?). The others don't know anything about compiling or how any of this works, and for the sake of their simplicity, I was wondering if it was possible to compile for other platforms off one. As far as I'm aware, "lime test <platform>" is for building FROM said platform, not for. If need be, I suppose I could just compile each version inside an emulator, I just didn't want to, install and troubleshoot everything thrice haha.

**Comment by crowplexus** [comment]
not possible, if you wanna compile to a specific platform, you have to be using that platform, that is a limitation within haxe and lime itself

**Comment by sodapopzz** [comment]
Yeahh, that's what I thought, lol. I was just wondering if anyone more experienced with the programs knew otherwise. Emulator it is, then. Thanks for the clarification, though!
