### ISSUE TITLE
The Song Bug

### ISSUE THREAD

**Issue by Crazyhrk256** [ShadowMario/FNF-PsychEngine#14428]
### Describe your bug here.

can you fix the bug where I can't load this song called "Portal Mayhem v2" please.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

it was a mod that I added in file "C:\Users\jlavi\Downloads\psychengine-windows64_d7181\PsychEngine\mods\VSDAIRE2-0"

**Comment by Stefan2008Git** [comment]
We need a logs where is showing for your mod folder or else we can't help you
