### ISSUE TITLE
i need a hide HUD script

### ISSUE THREAD

**Issue by Flubbedsoda6010** [ShadowMario/FNF-PsychEngine#14427]
### Describe your problem here.

how do i hide the HUD on countdown without hiding the countdown 
engine is on 0.7.3

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by xxyuee** [comment]
function onStartCountdown()
    setProperty('healthBar.visible',false)
    setProperty('scoreTxt.visible',false)
    setProperty('iconP1.visible', false)
    setProperty('iconP2.visible', false)
    setProperty('timeTxt.visible',false)
    setProperty("timeBar.visible", false)
end

**Comment by Flubbedsoda6010** [comment]
no, including the strum lines, and it has to return visible
