### ISSUE TITLE
Everytime I try to chart the song and reload the audio it shows a blank state :|

### ISSUE THREAD

**Issue by yourPTSD** [ShadowMario/FNF-PsychEngine#14422]
### Describe your bug here.

I feel like this has been said before, but as the title says, i'm having issues charting some songs,and yes i have changed both the tracks to Voices.ogg and Inst.ogg. But either way, it still won't seem to work everytime i reload the song, and everytime i do it will show a blank state saying: Uncaught Error:Error loading sound from file: mods/Testing lol/songs//cory/Voices.ogg. Does anyone know how to fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Stefan2008Git** [comment]
Ig it's a Psych issue itself or you are definitely did something wrong

**Comment by HuntyBaconYT** [comment]
I can't play the song "Test" for the secret. It is just the song I used with the notes, But still, The Song works well, Not the .JSON file tho. I don't think It's in the mod (O.7.3v btw). tell me how I do it? I wanna have the secret badge: "Play The Secret Test Song on hard with No Misses." and all that. Pls
