### ISSUE TITLE
Compiling Issue. 

### ISSUE THREAD

**Issue by DaBanana64** [ShadowMario/FNF-PsychEngine#1442]
### Describe your bug here.

Well self-explanatory, got the latest commits and it won't compile.
![image](https://user-images.githubusercontent.com/82652849/143780734-b4d23475-97c4-4ec2-94ca-61ad99b4c8dc.png)
 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by SrtHero278** [comment]
Some problem here. I think it's another typo.

**Comment by DeweyPointJr** [comment]
I have the same problem

**Comment by Collabvmisgood** [comment]
You are missing a ; at line 410.

**Comment by Collabvmisgood** [comment]
@DaBanana64

**Comment by DaBanana64** [comment]
> You are missing a ; at line 410.

I replace that with a ";" but it gives me this error.
https://media.discordapp.net/attachments/888391371206033409/914564166289862666/unknown.png

**Comment by Collabvmisgood** [comment]
Now a } is missing..
Show me the code for FreeplayState.hx.

**Comment by DaBanana64** [comment]
> Now a } is missing.. Show me the code for FreeplayState.hx.

![image](https://user-images.githubusercontent.com/82652849/143784659-0f2a0151-d8d3-4446-8f41-66aae9c46060.png)

**Comment by Collabvmisgood** [comment]
There is two ]
Do this
```haxe
CoolUtil.difficultyStuff = [
     ['Easy', '-easy'],
     ['Normal', ''],
     ['Hard', '-hard']
];
```

**Comment by Collabvmisgood** [comment]
@DaBanana64

**Comment by DaBanana64** [comment]
> There is two ] Do this
> 
> ```hx
> CoolUtil.difficultyStuff = [
>      ['Easy', '-easy'],
>      ['Normal', ''],
>      ['Hard', '-hard']
> ];
> ```

![image](https://user-images.githubusercontent.com/82652849/143784914-1ef16373-5ccd-4163-a412-8168929bf9b2.png)
Well it gave me this error.

**Comment by Collabvmisgood** [comment]
I got that error to.
https://github.com/ShadowMario/FNF-PsychEngine/issues/1430
This is how i fixed with someone

**Comment by Collabvmisgood** [comment]
@DaBanana64

**Comment by DaBanana64** [comment]
> I got that error to. #1430 This is how someone help me [#1430 (comment)](https://github.com/ShadowMario/FNF-PsychEngine/issues/1430#issuecomment-981052224)
I'll eventually wait for a fix for this, because that seems to disable the functionality of mods folder.  Gonna close this issue for now, though thank you for looking into the issue.

**Comment by DaBanana64** [comment]
It is fixed on the latest commit!
