### ISSUE TITLE
string should be flash.media.sound

### ISSUE THREAD

**Issue by luciocraft** [ShadowMario/FNF-PsychEngine#14437]
### Describe your problem here.

source/editors/ChartingState.hx:1443: characters 27-54 : String should be flash.media.Sound
source/editors/ChartingState.hx:1461: characters 27-56 : String should be flash.media.Sound
source/editors/ChartingState.hx:946: characters 22-51 : String should be flash.media.Sound
source/editors/ChartingState.hx:959: characters 24-51 : String should be flash.media.Sound
source/editors/EditorPlayState.hx:89: characters 41-74 : String should be flash.media.Sound
source/editors/EditorPlayState.hx:153: characters 24-55 : String should be flash.media.Sound
source/LoadingState.hx:140: characters 10-41 : String should be flash.media.Sound
source/LoadingState.hx:145: characters 10-43 : String should be flash.media.Sound
source/PlayState.hx:1478: characters 41-74 : String should be flash.media.Sound
source/PlayState.hx:1483: characters 51-82 : String should be flash.media.Sound
source/FreeplayState.hx:258: characters 42-75 : String should be flash.media.Sound
source/FreeplayState.hx:263: characters 25-56 : String should be flash.media.Sound
source/PlayState.hx:1441: characters 24-55 : String should be flash.media.Sound

i got this since 2023 bruh
on 0.4.2

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no , just normal 0.4.2

**Comment by mcagabe19** [comment]
bro's compiling 0.4.x on 2024 it's impossible and will be laggy as fuck

**Comment by CobaltBar** [comment]
why the fuck are you using 0.4.2

do you have a mental illness

**Comment by Stefan2008Git** [comment]
Are you kidding me dude? 0.4.2? Man, the version is outdated like 2-3 years since Shadow Mario did a lot of changes of Psych, so please use the latest stable build
