### ISSUE TITLE
VS Tabi restored v2 crashes when i try to play a song 

### ISSUE THREAD

**Issue by SpexifyZ** [ShadowMario/FNF-PsychEngine#14438]
### Describe your bug here.

Whenever I click a song to play it, this appears and the game crashes, I had Haxe installed and I uninstalled it and that still appears even though the file does not exist:

C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
StoryMenuState.hx (line 321)
StoryMenuState.hx (line 260)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/last-memories/last-memories-hard.json]

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just installed it normally

**Comment by crowplexus** [comment]
this is not the repository for this, talk to the devs of the mod, not here.

**Comment by SpexifyZ** [comment]
oh my bad, it said to report here whenever the crash happened.

**Comment by crowplexus** [comment]
> oh my bad, it said to report here whenever the crash happened.

yeah, often mods forget to remove that warning
