### ISSUE TITLE
cant add new events

### ISSUE THREAD

**Issue by whyiseveryusernametaked** [ShadowMario/FNF-PsychEngine#1443]
### Describe your bug here.

so I put the event (opponent fade) in the mods/custom_events folder but when i go to check it out in the events menu it doesn't show up. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by barbbarain** [comment]
did you add the event's description file?

**Comment by SrtHero278** [comment]
> did you add the event's description file?

I'm also thinking that what they didn't do. You need to add in both an lua file and an txt file.
![image](https://user-images.githubusercontent.com/93018286/143782432-5c8d8a96-5179-442a-b9be-0bf7b9201168.png)

**Comment by whyiseveryusernametaked** [comment]
I did

**Comment by NotEpik** [comment]
> 

but as I know you can only add .txt file and it will show in the events menu

**Comment by NotEpik** [comment]
> I did and it still didn't work

try download psych engine again

**Comment by whyiseveryusernametaked** [comment]
> > I did and it still didn't work
> 
> try download psych engine again

Did that too

**Comment by Collabvmisgood** [comment]
Lua scripts are broken right because the mod menu is not done.

**Comment by Collabvmisgood** [comment]
But you try source code. Here https://haxeflixel.com/documentation/getting-started/ is a good way to get started same with this:
https://www.youtube.com/watch?v=Ydh4N22WcBI&list=PLS9MbmO_ssyBcgdfrd4beEUeQtsdvM2st&ab_channel=Gamefromscratch

**Comment by gaminbottomtext** [comment]
Reinstall linc_luajit and build again

**Comment by whyiseveryusernametaked** [comment]
it probably has to do with the fact that I am on mac

**Comment by gaminbottomtext** [comment]
i code events on mac just fine on lua and it works
