### ISSUE TITLE
Problems Compiling/not found teacall

### ISSUE THREAD

**Issue by EmperorPalps** [ShadowMario/FNF-PsychEngine#14439]
### Describe your problem here.

source/states/PlayState.hx:36: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
source/psychlua/FunkinLua.hx:16: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
C:/HaxeToolkit/haxe/lib/flixel-addons/2,5,0/flixel/addons/transition/FlxTransitionableState.hx:82: lines 82-91 : Warning : switchTo is deprecated, use startOutro
source/states/PlayState.hx:3479: characters 51-67 : Type not found : FlxRuntimeShader

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Tried to fix versions, nothing else.

**Comment by Orsonster** [comment]
Just change it to "Tea", newer versions of the library use Tea instead of TeaCall, and if you haven't already, I suggest running the setup batch file for windows.

**Comment by drpaper1p1** [comment]
> Just change it to "Tea", newer versions of the library use Tea instead of TeaCall, and if you haven't already, I suggest running the setup batch file for windows.

Im currently having this issue and I've seen this mentioned but how do I change it to tea instead of teacall?

**Comment by SSwampy** [comment]
> Just change it to "Tea", newer versions of the library use Tea instead of TeaCall, and if you haven't already, I suggest running the setup batch file for windows.

what do you mean change it to tea?
