### ISSUE TITLE
compiling problem

### ISSUE THREAD

**Issue by barbbarain** [ShadowMario/FNF-PsychEngine#1444]
### Describe your problem here.

So I downloaded all Haxe libraries and I alrady installed VS Code in a month ago. I typed lime test windows, then this is what I got.

C:\Users\amax5\Documents\VSBowy\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
Duplicate of #1466
