### ISSUE TITLE
Discord RPC supports only C++ target platforms error building haxe completion

### ISSUE THREAD

**Issue by alexlolxp** [ShadowMario/FNF-PsychEngine#14448]
### Describe your problem here.

C:/HaxeToolkit/haxe/lib/hxdiscord_rpc/git/hxdiscord_rpc/Discord.hx:4: characters 8-57 : Discord RPC supports only C++ target platforms.

receiving this error which is stopping haxe from building

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by mcagabe19** [comment]
discord_rpc being used macro find and add #if !macro
