### ISSUE TITLE
Crash in Wiik Deluxe "every matt spam moment ever"

### ISSUE THREAD

**Issue by Tidoto** [ShadowMario/FNF-PsychEngine#14445]
### Describe your bug here.

idk what happens here i just got this error and was told by it to report it here, good luck
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/53945683/7325c41d-6804-4209-a945-eb402543c04e)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i didnt make this, its this here: https://gamebanana.com/mods/368696

**Comment by Tidoto** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/53945683/de1dfab9-61d1-4c7b-af53-36364cf6226c)
this happens if i load the chart into the editor lol

**Comment by ducky325** [comment]
go to your psych engine and it should be a crash folder get the txt from here and paste the name and whats in it here

**Comment by Tidoto** [comment]
Uhm yea.... The thing in the files is the same as the screenshots. I went
to the newest version of psych engine and there it doesn't crash.... So yea
I don't know what's going on with that json I really don't know
