### ISSUE TITLE
How do i skip StoryMenuState?

### ISSUE THREAD

**Issue by ArtwKiwo** [ShadowMario/FNF-PsychEngine#14458]
I think the title already explain it, I want to load my song from the main menu, I found this code but it doens't work with me, probably because it's pretty old.

```
PlayState.SONG = Song.loadFromJson('testname-hard', 'testname');
LoadingState.loadAndSwitchState(new PlayState());
```

It just says "source/states/MainMenuState.hx:161: characters 26-30 : Type not found : Song" when I start the build, and i can't find anywhere how to fix this.

**Comment by crowplexus** [comment]
change `Song` to `backend.Song`

**Comment by Stefan2008Git** [comment]
> change `Song` to `backend.Song`

Or import it. Really simple

**Comment by ArtwKiwo** [comment]
it works now, thanks!
