### ISSUE TITLE
Menu music playing when i play a song

### ISSUE THREAD

**Issue by ArtwKiwo** [ShadowMario/FNF-PsychEngine#14453]
### What is your question?

So, i'm trying to add my own week to the engine, but everytime i play the song it just plays the menu music instead of the actual song.

I'm using 0.7.3, it works fine when i put the files in the a mods folder, but i'm using the source code, all i did was add the song in assets/songs, the week in assets/shared/weeks and chart at assets/shared/data, i don't what else i have to do, i'm pretty new using the source code :P

**Comment by ArtwKiwo** [comment]
nvm i fixed

**Comment by Josephjr05** [comment]
How did you fix it? I'm having this problem currently but i can't find a solution anywhere.

**Comment by goobera** [comment]
how did you fix it
