### ISSUE TITLE
How to stop buttons and background from moving

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#14459]
### Describe your problem here.

![2024-04-11_19-22-28](https://github.com/ShadowMario/FNF-PsychEngine/assets/114620759/b8eb541e-2b72-4828-91ff-f04653f9e9a8)
I have two problems. The first one at the beginning when I go to the menu everything seems to be fine, but there is no settings button
![2024-04-11_19-25-05](https://github.com/ShadowMario/FNF-PsychEngine/assets/114620759/cbef45c0-bc84-44dd-8fb6-d2338b7377d6)
But when I select the buttons below, everything is fine and the settings button is visible

Second problem: I would like the buttons and background to not move when I press up or down
That is, I want them to be static.. Please help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

A little

**Comment by xxyuee** [comment]
im not sure whats wrong with the settings button but for the scroll part,
find bg.scrollFactor.set(0, yScroll) and replace 'yScroll' with 0, do the same with the menu items. also remove bg.setGraphicSize and bg.updateHitbox()

**Comment by MaksPRO12667** [comment]
> im not sure whats wrong with the settings button but for the scroll part,
> find bg.scrollFactor.set(0, yScroll) and replace 'yScroll' with 0, do the same with the menu items. also remove bg.setGraphicSize and bg.updateHitbox()

I replaced bg.scrollFactor.set(0, yScroll) from "yScroll" to "0". Removed bg.setGraphicSize and bg.updateHitbox(). The background doesn't move, but the buttons do.
