### ISSUE TITLE
 How do I change my character's idle animation speed? 

### ISSUE THREAD

**Issue by Aceolu** [ShadowMario/FNF-PsychEngine#14450]
### What is your question?

To preface, I am not refering to the framerate option. I know there is a character framerate option in the character editor, but that's not what I'm looking for. I apologize if "speed" is not the right word for this, but I couldn't think of a better one.

I am adding a character to Psyche Engine (0.7.3) and I'm noticing they only play their idle animation every OTHER beat, while BF's idle animation plays on every beat. Is there a way I can make it so my character's idle plays on every beat rather than every other beat?

EDIT: 
I was looking around and found the variable "danceEveryNumBeats" however I'm going to assume I'm either using it wrong, or it's deprecated, as every attempt to use it just crashes the game. Does anyone have insight on this?

**Comment by LIGHT4477** [comment]
Where is dance danceEveryNumBeats
