### ISSUE TITLE
Popup ads like Bob

### ISSUE THREAD

**Issue by MapidsFanAnimator** [ShadowMario/FNF-PsychEngine#14460]
### Describe your problem here.

how do you make the ad pop up like bob in psych engine, making the ad image randomly appear, and making it select a random image? 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by JVgradiz** [comment]
-- Used to keep track of the popup number
local popupId = 0;
-- Put all of the image names in this array
local images = {'image1', 'image2', 'image3', 'moreImages'}

local positions = {
	x = {20,1000}, -- popup min and max X position
	y = {20,600} -- popup min and max Y position
}

-- The amount of seconds a popup stays on screen
local popupTimes = 10;

function spawnPopup()
	-- Create the sprite
	makeLuaSprite('Popup'..popupId, 'popupPath/'..images[getRandomInt(1, #images)], getRandomInt(positions['x'][1], positions['x'][2]),getRandomInt(positions['y'][1], positions['y'][2]));
	-- Set it to the hud
	setObjectCamera('Popup'..popupId, 'camHud');
	-- Go in front of EVERYTHING
	setObjectOrder('Popup'..popupId, 99999);
	-- Adds it to the game
	addLuaSprite('Popup'..popupId, true);
	runTimer('DissapearPopup,' .. popupId, popupTimes); -- Runs a timer to delete the popup
	popupId = popupId+1;
end

function onTimerCompleted(tag, loops, loopsLeft)
	local splitTag = stringSplit(tag, ',');
	if splitTag[1] == 'DissapearPopup' then
		removeLuaSprite('Popup' .. splitTag[2], true);
	end
end

function onEvent(eventName, value1, value2, strumTime)
	if eventName == 'popupEventName' then
		spawnPopup()
	end
end

**Comment by MapidsFanAnimator** [comment]
thanks, but how do i use it in events and where do I put the popup images in the file?

**Comment by JVgradiz** [comment]
> thanks, but how do i use it in events and where do I put the popup images in the file?

on line 35 change the 'popupEventName' to ' (your event's name) ' to select the trigger

on line 16, on the second value of the function change the 'popupPath' to your popup image's path
and change the variable at line 4 to include all your images names ( Example:  local images = {'PopupImage1', 'PopupImage2'} and etc... )

and if you didn't understand this research more the basics of lua coding

Hope this helps :)

**Comment by JVgradiz** [comment]
Btw, may i know what'ya working on to need the popups?
