### ISSUE TITLE
Background Crowd not appearing

### ISSUE THREAD

**Issue by SammuSucksAtCode** [ShadowMario/FNF-PsychEngine#14463]
### Describe your problem here.

I'm trying to add an animated crowd to the background of a new stage in source, loading it as a BGSprite doesn't have it animated, and loading it as a FlxSprite just has the spritesheet itself be placed, or if I call the frames, the asset doesnt load at all. Since the mod actually compiles I don't get any errors, and even when the sprites don't spawn in, they don't return null, meaning they're loaded. The fix is probably simple for most people, but I'm an idiot and need some help. 
[This is under override function create() ]

```
        var backcrowd = new FlxSprite(0, 0).loadGraphic(Paths.image('dumb/bg_bop_two'));
        backcrowd.frames = Paths.getPackerAtlas('dumb/bg_bop_two');
        backcrowd.animation.add('bg bop two', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 24, true);
        backcrowd.animation.play('bg bop two');
        backcrowd.updateHitbox();
        add(backcrowd);
```
is it just me misformatting it? or am I just stupid? I'm usually a lua user but I want to learn Source better so I have more options.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by xxyuee** [comment]
try this, 

var backcrowd:FlxSprite = new FlxSprite(0, 0).loadGraphic(Paths.image('dumb/bg_bop_two'));
        backcrowd.frames = Paths.getSparrowAtlas('dumb/bg_bop_two');
		backcrowd.animation.add('bg bop two', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 24, true);
		backcrowd.animation.play('bg bop two');
		add(backcrowd);

**Comment by SammuSucksAtCode** [comment]
That absolutely fixed it thank you so much, I appreciate it
