### ISSUE TITLE
Characters in source

### ISSUE THREAD

**Issue by DxrkPxwer** [ShadowMario/FNF-PsychEngine#14461]
### What is your question?

Look, I know this is way too far, we literally basically just use Lua to make shit real, but i'm a tryhard type person. 
Sooo you already guessed it.

People would say that source stuff would be better done in discord servers, but i don't use discord **YET.**
ShadowMario already added something to hardcode characters, but i honestly don't like it, its pretty werid.

So the main question: 
## How do i add characters in source on psych like psych coders?

i'd like to people answer this quickly

**Comment by crowplexus** [comment]
simple: you don't, psych coders DON'T hardcode their characters

just do it "the base game way" and tuck your character data inside the switch case in Character.hx

**Comment by crowplexus** [comment]
[here, to be exact](https://github.com/ShadowMario/FNF-PsychEngine/blob/65494a3375fbceb5d74cfd2231ba668790842a4f/source/objects/Character.hx#L92)

**Comment by crowplexus** [comment]
example
```jaxe
case 'character-name-here':
	// ANIMATION LOADING CODE
	frames = Paths.getSparrowAtlas('characters/character_spritesheet_here');
	quickAnimAdd('idle', 'Dad idle dance');
	quickAnimAdd('singUP', 'Dad Sing Note UP');
	quickAnimAdd('singRIGHT', 'Dad Sing Note RIGHT');
	quickAnimAdd('singDOWN', 'Dad Sing Note DOWN');
	quickAnimAdd('singLEFT', 'Dad Sing Note LEFT');

	addOffset("idle", 0, 0);
	addOffset("singLEFT", 10, 50);
	dance();
```

**Comment by DxrkPxwer** [comment]
> example
> 
> ```
> case 'character-name-here':
> 	// ANIMATION LOADING CODE
> 	frames = Paths.getSparrowAtlas('characters/character_spritesheet_here');
> 	quickAnimAdd('idle', 'Dad idle dance');
> 	quickAnimAdd('singUP', 'Dad Sing Note UP');
> 	quickAnimAdd('singRIGHT', 'Dad Sing Note RIGHT');
> 	quickAnimAdd('singDOWN', 'Dad Sing Note DOWN');
> 	quickAnimAdd('singLEFT', 'Dad Sing Note LEFT');
> 
> 	addOffset("idle", 0, 0);
> 	addOffset("singLEFT", 10, 50);
> 	playAnim("idle", true);
> ```

my brother in christ
i already gave up on trying to do different
i TRIED doing smth different
but i guess i have to go to the right direction

**Comment by DxrkPxwer** [comment]
> example
> 
> ```
> case 'character-name-here':
> 	// ANIMATION LOADING CODE
> 	frames = Paths.getSparrowAtlas('characters/character_spritesheet_here');
> 	quickAnimAdd('idle', 'Dad idle dance');
> 	quickAnimAdd('singUP', 'Dad Sing Note UP');
> 	quickAnimAdd('singRIGHT', 'Dad Sing Note RIGHT');
> 	quickAnimAdd('singDOWN', 'Dad Sing Note DOWN');
> 	quickAnimAdd('singLEFT', 'Dad Sing Note LEFT');
> 
> 	addOffset("idle", 0, 0);
> 	addOffset("singLEFT", 10, 50);
> 	playAnim("idle", true);
> ```

my brother in christ
i already gave up on trying to do different
i TRIED doing smth different
but i guess i have to go to the right direction
