### ISSUE TITLE
How can i make an animated menuBG?

### ISSUE THREAD

**Issue by mister6k** [ShadowMario/FNF-PsychEngine#14465]
### Describe your problem here.

I want to add an animated menuBG (the bg in the menu with story mode, freeplay etc) with a spritesheet xml. How can i do this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Stefan2008Git** [comment]
On Lua you can't do it for main menu, freeplay and story mode

**Comment by xxyuee** [comment]
yea if u really need it, go to MainMenuState/FreeplayState in source and find 'bg = new FlxSprite()' and put these below that line,

bg.frames = Paths.getSparrowAtlas('[file name]');
bg.animation.addByPrefix('menubg', "[prefix in xml]", 24, true);
bg.animation.play('menubg');
