### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by CoxGitX** [ShadowMario/FNF-PsychEngine#14473]
### Describe your bug here.

It just stops there

### Command Prompt/Terminal logs (if existing)

```bash
source/FunkinLua.hx:507: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:525: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:531: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:581: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:587: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:627: lines 627-631 : Int should be Bool
source/FunkinLua.hx:627: lines 627-631 : ... For function argument 'f'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nuh uh

**Comment by xxyuee** [comment]
`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit`

**Comment by CoxGitX** [comment]
> xxyuee

I have it installed already

**Comment by xxyuee** [comment]
thats the only fix 😭 try reinstalling
