### ISSUE TITLE
Compiling stops there

### ISSUE THREAD

**Issue by CoxGitX** [ShadowMario/FNF-PsychEngine#14478]
### Describe your problem here.

It just stops there idk what to do, its with every psych version

source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
C:/haxelib/flixel/5,5,0/flixel/animation/FlxAnimation.hx:239: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
source/PlayState.hx:76: characters 8-22 : Type not found : vlc.MP4Handler
C:/haxelib/flixel-addons/git/flixel/addons/effects/chainable/FlxEffectSprite.hx:143: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/flixel/system/FlxSound.hx:597: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/system/FlxSound.hx:601: characters 19-27 : flash.media.SoundChannel has no field __source
source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'basic'
source/PlayState.hx:1619: characters 13-23 : Type not found : MP4Handler
source/FunkinLua.hx:2225: lines 2225-2228 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2225: lines 2225-2228 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'basic'
source/PlayState.hx:582: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:582: characters 25-35 : ... For function argument 'basic'
source/PlayState.hx:2446: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2446: characters 23-29 : ... For function argument 'basic'
source/PlayState.hx:2447: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2447: characters 23-83 : ... For function argument 'basic'
source/PlayState.hx:1825: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1825: characters 25-37 : ... For function argument 'basic'
source/PlayState.hx:1872: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1872: characters 25-34 : ... For function argument 'basic'
source/PlayState.hx:1943: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1943: characters 25-36 : ... For function argument 'basic'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1383: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1383: characters 24-30 : ... For function argument 'basic'
source/editors/ChartingState.hx:2270: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/haxelib/flixel/5,5,0/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
source/TitleState.hx:766: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:768: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:772: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound

C:\Users\PC\OneDrive\Počítač\FNF-PsychEngine-extra-keys>haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

A new version (4.1.0) of haxelib is available.
Do `haxelib --global update haxelib` to get the latest version.

You already have linc_luajit version git installed.
Updating linc_luajit version git ...
linc_luajit was updated
Library linc_luajit current version is now git

C:\Users\PC\OneDrive\Počítač\FNF-PsychEngine-extra-keys>haxelib install hxCodec

A new version (4.1.0) of haxelib is available.
Do `haxelib --global update haxelib` to get the latest version.

You already have hxCodec version 3.0.2 installed
Set hxCodec to version 3.0.2 [y/n/a] ? y
Library hxCodec current version is now 3.0.2

C:\Users\PC\OneDrive\Počítač\FNF-PsychEngine-extra-keys>lime test windows
source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
C:/haxelib/flixel/5,5,0/flixel/animation/FlxAnimation.hx:239: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
source/PlayState.hx:76: characters 8-22 : Type not found : vlc.MP4Handler
C:/haxelib/flixel-addons/git/flixel/addons/effects/chainable/FlxEffectSprite.hx:143: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/flixel/system/FlxSound.hx:597: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/system/FlxSound.hx:601: characters 19-27 : flash.media.SoundChannel has no field __source
source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'basic'
source/PlayState.hx:1619: characters 13-23 : Type not found : MP4Handler
source/FunkinLua.hx:2225: lines 2225-2228 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2225: lines 2225-2228 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'basic'
source/PlayState.hx:582: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:582: characters 25-35 : ... For function argument 'basic'
source/PlayState.hx:2446: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2446: characters 23-29 : ... For function argument 'basic'
source/PlayState.hx:2447: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2447: characters 23-83 : ... For function argument 'basic'
source/PlayState.hx:1825: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1825: characters 25-37 : ... For function argument 'basic'
source/PlayState.hx:1872: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1872: characters 25-34 : ... For function argument 'basic'
source/PlayState.hx:1943: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1943: characters 25-36 : ... For function argument 'basic'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1383: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1383: characters 24-30 : ... For function argument 'basic'
source/editors/ChartingState.hx:2270: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/haxelib/flixel/5,5,0/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
source/TitleState.hx:766: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:768: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:772: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by xxyuee** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by Stefan2008Git** [comment]
I cannot help about this anymore...

**Comment by CoxGitX** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

That Doesnt work too
