### ISSUE TITLE
how do i fix this icon bop? (i1 = iconP1)

### ISSUE THREAD

**Issue by SlushieDrawzCoolDrawingX480** [ShadowMario/FNF-PsychEngine#14472]
### What is your question?

function onBeatHit()
   if curBeat % 2 == 0 then
   setProperty('i1.angle', angle * 15)
   setProperty('i2.angle', angle / 15)
   doTweenAngle('hr', 'i1', 1, 0.5, 'elasticOut')
   doTweenAngle('jt', 'i2', 1, 0.5, 'elasticOut')
   end
end

**Comment by JVgradiz** [comment]
Is this what you wanted?
```
function onBeatHit()
	if curBeat % 2 == 0 then
		setProperty('iconP1.angle', getProperty('iconP1.angle') * 15)
		setProperty('iconP2.angle', getProperty('iconP2.angle') * -15)
		doTweenAngle('hr', 'iconP1', 1, 0.5, 'elasticOut')
		doTweenAngle('jt', 'iconP2', 1, 0.5, 'elasticOut')
	end
end
```

**Comment by SlushieDrawzCoolDrawingX480** [comment]
its it's own sprite btw, so it crashes when ever i use this script
