### ISSUE TITLE
Compiling errors! 0.7.1 with 0.7.2+ libraries

### ISSUE THREAD

**Issue by SuxxorState** [ShadowMario/FNF-PsychEngine#14470]
### Describe your problem here.

I'm trying to compile a new mod in 0.7.1 and for some reason it just doesnt want to work.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/55562463/eab759fc-3de9-4ebd-811a-c10f51905363)
It starts complaining about HScript, so i thought, hey! Maybe the libraries are too up to date! Ill grab them from an older mod of mine.
So I did, and...
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/55562463/90736c55-a200-40ad-924a-e51cee3a166d)
not a pretty site, lemme tell ya.
I've tried basically everything i know, and i still cant get it to work. Worst part about it is it's now affected my other mods, too!
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/55562463/ede0a06e-dc88-4c78-96fe-7773880d9fb8)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/55562463/44ceeca9-cf76-4068-80c6-57601c5bb562)
This is a major issue since most of the mods I worked on in the last year are in 0.7.1, and updating all of them is just not worth the time.
Does anyone know how to help?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by WolfyTail** [comment]
How did you fix it?
