### ISSUE TITLE
Tweens.

### ISSUE THREAD

**Issue by Meziaki** [ShadowMario/FNF-PsychEngine#14484]
### What is your question?

Is there a function for a numberTween? 
So I don't have to do something like 
`onUpdate(elapsed) number = number + 1 / 25 end` 
instead: 
``tweenNumber('t',25,1,'linear')`
I've been trying to do something similar

**Comment by JVgradiz** [comment]
Unfortunately no, however here's a little trick
1 - make an invisible lua sprite
2 - onUpdate set your variable to the sprite's x value
3 - do a tweenX on the sprite
4 - profit
