### ISSUE TITLE
Why my onTweenCompleted isn't working?

### ISSUE THREAD

**Issue by Yandurva08** [ShadowMario/FNF-PsychEngine#14482]
### Describe your problem here.

I'm trying to make gf go up and down while rotating 180 degrees but it says that have a error at line 6 with the name
![Screenshot_20240415-184151](https://github.com/ShadowMario/FNF-PsychEngine/assets/94998555/63982776-5c6d-4969-8fd9-34c5da2447df)

If you want to me send the text code

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

**Comment by JHAM25** [comment]
En la forma que lo estas haciendo esta mal. debe de ser asi:
![Screenshot_2024-04-15-20-36-20-074_com rhmsoft code](https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/2689d79a-afa0-4135-a3e4-78a8a5b5e4ad)

**Comment by JHAM25** [comment]
function doTweenCompleted(tag)
    if tag == 'down' then
        doTweenY('down', 'gf', -400, 5, 'quartOut')
        doTweenAngle('rota', 'gf', 180, 5, 'quartOut')
    end
if tag == 'up' then
--- resto del codigo
end
end

**Comment by Yandurva08** [comment]
> function doTweenCompleted(tag) if tag == 'down' then doTweenY('down', 'gf', -400, 5, 'quartOut') doTweenAngle('rota', 'gf', 180, 5, 'quartOut') end if tag == 'up' then --- resto del codigo end end

Isn't working, gf just goes down and does nothing

**Comment by JHAM25** [comment]
Aqui ya esta solucionado:
function onTweenCompleted(tag)
if tag == 'down' then
doTweenY('up', 'gf', 400, 5, 'quartOut')
doTweenAngle('rota', 'gf', 180, 5, 'quartOut')
end
if tag == 'up' then
doTweenY('down', 'gf', -400, 5, 'quartOut')
doTweenAngle('rota', 'gf', 180, 5, 'quartOut')
end
end

Aunque aqui solo estara subiendo y bajando por que  doTweenAngle la posición esta en 180 y cada que ejecute un tween se va quedar en ese número. Nose si me explique bien

**Comment by Yandurva08** [comment]
> Aqui ya esta solucionado: function onTweenCompleted(tag) if tag == 'down' then doTweenY('up', 'gf', 400, 5, 'quartOut') doTweenAngle('rota', 'gf', 180, 5, 'quartOut') end if tag == 'up' then doTweenY('down', 'gf', -400, 5, 'quartOut') doTweenAngle('rota', 'gf', 180, 5, 'quartOut') end end
> 
> Aunque aqui solo estara subiendo y bajando por que al iniciar se ejecuta el ángulo a 180 y cada que se acabe va estar ejecutando el mismo ángulo

Entiendes mi problema pero funciona (traducido por google tradutor)
