### ISSUE TITLE
Custom note splashes on note type

### ISSUE THREAD

**Issue by OlitoLol** [ShadowMario/FNF-PsychEngine#14483]
### Describe your problem here.

Any way to have specific note splashes on a specific note type? i tried stealing this line 

setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'NOTE_splashes_EYE');

but it makes it so only the first note of the type is a special note, all the others are normal, please help!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by xxyuee** [comment]
for i = 0, getProperty("unspawnNotes.length") do
setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'NOTE_splashes_EYE');
end

**Comment by OlitoLol** [comment]
now the splashes dont get changed :/
