### ISSUE TITLE
camera lua function and kind array

### ISSUE THREAD

**Issue by khuonghoanghuy** [ShadowMario/FNF-PsychEngine#14489]
### What feature do you want to get added on the **base** engine?

uhhhh

can ur team add the cam lua function and some kind like camArray:Array<String> = ["camGame", "camHUD", "camOther"] :)))

this request would be cool :>>

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
what?

**Comment by Lycranok** [comment]
@khuonghoanghuy just make the array yourself, it isn't difficult to do at all
