### ISSUE TITLE
Psych Engine 0.6.3 Compiling Error

### ISSUE THREAD

**Issue by thespatrtaremixer10** [ShadowMario/FNF-PsychEngine#14485]
### Describe your problem here.

I get this error on Psych Engine 0.6.3:
source/Main.hx:7: characters 8-24 : Type not found : debug.FPSCounter
source/Main.hx:19: characters 8-25 : Type not found : states.TitleState
source/Main.hx:51: characters 27-37 : Type not found : FPSCounter

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes. I replaced the Main.hx file.

**Comment by Stefan2008Git** [comment]
> I'm making a V.S Starecrown Remastered Full Week, With Some COMING SOON Songs finished.

First thing first, you need to use ``openfl.display.FPS`` import and you can remove ``states.TitleState`` import from Main

**Comment by thespatrtaremixer10** [comment]
> > I'm making a V.S Starecrown Remastered Full Week, With Some COMING SOON Songs finished.
> 
> First thing first, you need to use `openfl.display.FPS` import and you can remove `states.TitleState` import from Main

I can't find states.Titlestate.

**Comment by Stefan2008Git** [comment]
> > > I'm making a V.S Starecrown Remastered Full Week, With Some COMING SOON Songs finished.
> > 
> > 
> > First thing first, you need to use `openfl.display.FPS` import and you can remove `states.TitleState` import from Main
> 
> I can't find states.Titlestate.

Just remove ``import states.TitleState`` from Main file

**Comment by ShadowMario** [comment]
0.6.3 is not supported anymore since December 2023
