### ISSUE TITLE
How do I make credits currently?

### ISSUE THREAD

**Issue by SonhanGamer** [ShadowMario/FNF-PsychEngine#14488]
### What is your question?

Hello! I know it's a stupid question but I have a doubt, since I don't know if it is a bug or a change that I don't know about. In previous versions I think the credits format worked in 0.6.1, but now in recent versions it does not work. I've tried different ways but nothing... I don't know if it's a bug or a change that I haven't noticed. Please help.
![1](https://github.com/ShadowMario/FNF-PsychEngine/assets/167268339/713d0025-7070-4073-b32a-1b93838cbea2)
![2](https://github.com/ShadowMario/FNF-PsychEngine/assets/167268339/68ff07cd-bc18-4a1a-ba46-c43f2cd9d544)

**Comment by JHAM25** [comment]
Lo probe en las version 7.2h y funciona

**Comment by JHAM25** [comment]
Mira si tu archivo es .txt o nose que sucede

**Comment by SonhanGamer** [comment]
Okey, thanks!
