### ISSUE TITLE
how do i scale something up every beat?

### ISSUE THREAD

**Issue by SlushieDrawzCoolDrawingX480** [ShadowMario/FNF-PsychEngine#14480]
### What is your question?

how do i scale a custom sprite up every beat?

**Comment by HourOfEternity** [comment]
`scaleObject('name', sizeX, sizeY)` should work onCreate, just make sure that you set the name, sizeX and sizeY on what you want it to be.

**Comment by SlushieDrawzCoolDrawingX480** [comment]
i want it to tween size every beat

**Comment by SlushieDrawzCoolDrawingX480** [comment]
2nd one

**Comment by SlushieDrawzCoolDrawingX480** [comment]
> Do you mean you want it to get larger continuously, or it to go back to original size after a tiny bit?

hello?

**Comment by JHAM25** [comment]
Puedes hacer esto para que vuelva a su estado normal:
function onUpdate()
    if getProperty('nombre.scale.x') > 1 then-----aqui el número ajustalo a tu preferencia
        setProperty('nombre.scale.x', getProperty('nombre.scale.x') - elapsed)
        setProperty('nombre.scale.y', getProperty('nombre.scale.y') - elapsed)
    end
end
