### ISSUE TITLE
controller on lua

### ISSUE THREAD

**Issue by Surepart** [ShadowMario/FNF-PsychEngine#14499]
### Describe your problem here.

i'm trying using this
getPropertyFromClass("flixel.FlxG", "keys.justPressed.ENTER")
but for controller

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by JHAM25** [comment]
Puedes explicar mas de lo que quieres hacer es que al traducir esto a mi idioma no se entiende claramente lo que escribiste

**Comment by Surepart** [comment]
applying this getPropertyFromClass("flixel.FlxG", "keys.justPressed.ENTER") code but for controller! psych engine 0.6.3!

**Comment by JHAM25** [comment]
Creo que ya entiendo digamos quieres que un botón para tu control que actue como Enter.

**Comment by Surepart** [comment]
yes

**Comment by ShadowMario** [comment]
`keyboardJustPressed('ENTER')` should work for keyboard
`anyGamepadJustPressed('START')` should work for controller

you can do this in lua to check for both buttons:
```lua
if keyboardJustPressed('ENTER') or anyGamepadJustPressed('START') then
    --insert code for what happens when you press Enter/Start here
end
```
