### ISSUE TITLE
I Have Another Psych Engine 0.6.3 Error

### ISSUE THREAD

**Issue by thespatrtaremixer10** [ShadowMario/FNF-PsychEngine#14498]
### Describe your problem here.

I was trying to compile the source code, but this happened:

source/Main.hx:72: characters 12-23 : Class<CoolUtil> has no field setDarkMode
source/Main.hx:110: characters 3-20 : Type not found : online.Downloader
source/Main.hx:112: characters 16-28 : Type not found : online.Alert
source/Main.hx:113: characters 16-51 : Type not found : online.DownloadAlert
source/Main.hx:114: characters 16-36 : Type not found : online.LoadingScreen
source/Main.hx:116: characters 24-37 : Type not found : online.Waiter
source/Main.hx:120: characters 4-21 : Type not found : online.Downloader
source/Main.hx:121: characters 4-21 : Type not found : online.Downloader
C:/haxelib/flixel-addons/3,0,2/flixel/addons/display/FlxExtendedSprite.hx:11: characters 8-37 : Type not found : flixel.util.FlxDirectionFlags
C:/haxelib/flixel-addons/3,0,2/flixel/addons/display/FlxExtendedSprite.hx:484: characters 21-25 : Unknown identifier : WALL
C:/haxelib/flixel-addons/3,0,2/flixel/addons/display/FlxExtendedSprite.hx:504: characters 21-25 : Unknown identifier : WALL
C:/haxelib/flixel-addons/3,0,2/flixel/addons/display/FlxExtendedSprite.hx:530: characters 21-28 : Unknown identifier : CEILING
C:/haxelib/flixel-addons/3,0,2/flixel/addons/display/FlxExtendedSprite.hx:550: characters 21-26 : Unknown identifier : FLOOR
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:7: characters 8-37 : Type not found : flixel.util.FlxDirectionFlags
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:24: characters 34-51 : Type not found : FlxDirectionFlags
source/editors/ChartingState.hx:61: lines 61-3061 : Defined in this class
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:23: characters 2-39 : Method set_angle required by property angle is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field get_height needed by flixel.addons.ui.interfaces.IFlxUIWidget is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field get_width needed by flixel.addons.ui.interfaces.IFlxUIWidget is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field height needed by flixel.addons.ui.interfaces.IFlxUIWidget is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field set_height needed by flixel.addons.ui.interfaces.IFlxUIWidget is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field set_width needed by flixel.addons.ui.interfaces.IFlxUIWidget is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field width needed by flixel.addons.ui.interfaces.IFlxUIWidget is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field acceleration needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field alpha needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field drag needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field facing needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field maxVelocity needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field moves needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field offset needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field origin needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field reset needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field scale needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field scrollFactor needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field setPosition needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field set_alpha needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field set_angle needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field set_facing needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field set_moves needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field set_x needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field set_y needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field velocity needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field x needed by flixel.IFlxSprite is missing
C:/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUIPopup.hx:9: characters 7-17 : Field y needed by flixel.IFlxSprite is missing

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Idk

**Comment by ShadowMario** [comment]
0.6.3 is not supported anymore since December 2023
