### ISSUE TITLE
add lua sprites in gameover screen

### ISSUE THREAD

**Issue by Surepart** [ShadowMario/FNF-PsychEngine#14494]
### Describe your problem here.

how to add lua sprites on Gameover screen?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

NO!

**Comment by JHAM25** [comment]
Intenta con esto:
function onGameOverStart()
    makeLuaSprite('imagen', 'imagen', 0, 0)
    setObjectCamera('imagen', 'hud')
    addLuaSprite('imagen', false)


end
