### ISSUE TITLE
Game crashed when playing Ferocious on a golden apple port

### ISSUE THREAD

**Issue by RedImpostorsSon** [ShadowMario/FNF-PsychEngine#14490]
### Describe your problem here.

i was playing a psych engine port of golden apple 1.2 on the song, "Ferocious" and the game crashed on the Wizard part. here is the error:
StrumNote.hx (line 139)
flixel/group/FlxGroup.hx (line 175)
flixel/group/FlxGroup.hx (line 175)
flixel/addons/ui/FlxUIState.hx (line 212)
MusicBeatState.hx (line 70)
PlayState.hx (line 3025)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

im on 0.6.3

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Added a golden apple 1.2 port

**Comment by ShadowMario** [comment]
0.6.3 is not supported anymore since December 2023
