### ISSUE TITLE
Note deubug menu "INVALID ANIMATION NAME"

### ISSUE THREAD

**Issue by PotheadPat** [ShadowMario/FNF-PsychEngine#14493]
### Describe your problem here.

So im working on trying to add custom note splashes to the Funkin psych engine, through the mods folder in Lua, I keep recieving the error "INVALID ANIMATION NAME" , Even though the prefixes should be setup correctly, I dont possibly know what this error could be, Ill provide images and files of what im using, Ive been stumped on this for days.
![Capture](https://github.com/ShadowMario/FNF-PsychEngine/assets/167371672/f574fc38-95a2-46c6-953d-315d4551c486)
![noteSplashes-HappySplash](https://github.com/ShadowMario/FNF-PsychEngine/assets/167371672/9503b75c-c6f7-4f68-9ab2-6c0c2664980e)
[noteSplashes-HappySplash.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/15019856/noteSplashes-HappySplash.txt)

[noteSplashes-HappySplash.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/15019870/noteSplashes-HappySplash.txt) I have the XML put into a text file so github can read it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by HourOfEternity** [comment]
In the textbox "Image Name:", try changing "noteSplashes-HappySplash" to just "HappySplash". Also rename the three files to "HappySplash.txt", "HappySplash.png", and "HappySplash.xml".
