### ISSUE TITLE
Vocals from Freeplay preview persist into Week Editor.

### ISSUE THREAD

**Issue by SirHans15** [ShadowMario/FNF-PsychEngine#145]
When previewing a song in Freeplay with SPACE, then going to the Week Editor, the instrumental track of the song will be muted, but the vocal track will keep playing. When exiting back into the Main Menu, the vocals will still play, overlapping the standard menu music.
Example Video:
https://streamable.com/zn404n

**Comment by ShadowMario** [comment]
Fixed it on main repo now
