### ISSUE TITLE
I have to press both "right" or "left" and "enter" at the same time.

### ISSUE THREAD

**Issue by Your-Local-LordXSimp** [ShadowMario/FNF-PsychEngine#14505]
### Describe your problem here.

I have to press both keys for the song to start, but I'm trying to make it so that you just have to press "enter".
Here's the code snippet:

`function onUpdate(elapsed)

    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.LEFT') then

        doTweenAlpha('yesA', 'yes', 1, 0.3, 'linear')

        doTweenAlpha('noA', 'no', 0.5, 0.3, 'linear')

        if keyJustPressed('accept') then

        	doTweenAlpha('yesA', 'yes', 0, 0.5, 'linear')

        	doTweenAlpha('noA', 'no', 0, 0.5, 'linear')

        	startCountdown()

        	if startCountdown() == true then

        		removeLuaSprite('time')

        		cancelTimer('timeScale1')

        		cancelTimer('timeScale2')

        		cancelTimer('timeRunOut1')

        		cancelTimer('timeRunOut2')

        		cancelTimer('timeScale3')

        		cancelTimer('timeScale4')

        		cancelTimer('timeRunOut3')

        		cancelTimer('timeRunOut4')

        		cancelTimer('timeScale5')

        		cancelTimer('timeScale6')

        		cancelTimer('timeRunOut5')

        		cancelTimer('timeRunOut6')

        		cancelTimer('out')

    		end

    	end

	end

	if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.RIGHT') then

        doTweenAlpha('yesA', 'yes', 0.5, 0.3, 'linear')

        doTweenAlpha('noA', 'no', 1, 0.3, 'linear')

        if keyJustPressed('accept') then

        	doTweenAlpha('yesA', 'yes', 0, 0.5, 'linear')

        	doTweenAlpha('noA', 'no', 0, 0.5, 'linear')

        	runTimer('out', 1)

    	end

    end

end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by HourOfEternity** [comment]
In your code, you have it set so that the `keys.justPressed.RIGHT` and `keys.justPressed.LEFT` don't end before `keys.justPressed.ENTER`

In order to make it work, you need to do something like this (for the left key)

`if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.LEFT') then

    doTweenAlpha('yesA', 'yes', 1, 0.3, 'linear')

    doTweenAlpha('noA', 'no', 0.5, 0.3, 'linear')
end
if keyJustPressed('accept') then

    	doTweenAlpha('yesA', 'yes', 0, 0.5, 'linear')

    	doTweenAlpha('noA', 'no', 0, 0.5, 'linear')

    	startCountdown()
end`
(I DO NOT KNOW IF THIS WILL WORK. I'm using what I know of lua, and also looking at the similarities to see if this will work. Hopefully it does!)

**Comment by Your-Local-LordXSimp** [comment]
It makes sense that it would work, since it's closing the `keys.justPressed.RIGHT/LEFT` before `keys.justPressed.ENTER`. I never looked at it and never realized that it didn't close before the ENTER one lol.

**Comment by HourOfEternity** [comment]
Try This:
`
function onUpdate(elapsed)
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.LEFT') then
        doTweenAlpha('yesA', 'yes', 1, 0.3, 'linear')
        doTweenAlpha('noA', 'no', 0.5, 0.3, 'linear')
    end
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.RIGHT') then
        doTweenAlpha('yesA', 'yes', 0.5, 0.3, 'linear')
        doTweenAlpha('noA', 'no', 1, 0.3, 'linear')
    end
    if keyJustPressed('accept') then
        doTweenAlpha('yesA', 'yes', 0, 0.5, 'linear')
        doTweenAlpha('noA', 'no', 0, 0.5, 'linear')
        startCountdown()
    end
    if startCountdown() == true then
        removeLuaSprite('time')
        cancelTimer('timeScale1')
        cancelTimer('timeScale2')
        cancelTimer('timeRunOut1')
        cancelTimer('timeRunOut2')
        cancelTimer('timeScale3')
        cancelTimer('timeScale4')
        cancelTimer('timeRunOut3')
        cancelTimer('timeRunOut4')
        cancelTimer('timeScale5')
        cancelTimer('timeScale6')
        cancelTimer('timeRunOut5')
        cancelTimer('timeRunOut6')
        cancelTimer('out')
    end
end
`

**Comment by HourOfEternity** [comment]
Try this:
`function onUpdate(elapsed)
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.LEFT') then
        doTweenAlpha('yesA', 'yes', 1, 0.3, 'linear')
        doTweenAlpha('noA', 'no', 0.5, 0.3, 'linear')
    end
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.RIGHT') then
        doTweenAlpha('yesA', 'yes', 0.5, 0.3, 'linear')
        doTweenAlpha('noA', 'no', 1, 0.3, 'linear')
    end
    if keyJustPressed('accept') then
        doTweenAlpha('yesA', 'yes', 0, 0.5, 'linear')
        doTweenAlpha('noA', 'no', 0, 0.5, 'linear')
        startCountdown()
    end
    if startCountdown() == true then
        removeLuaSprite('time')
        cancelTimer('timeScale1')
        cancelTimer('timeScale2')
        cancelTimer('timeRunOut1')
        cancelTimer('timeRunOut2')
        cancelTimer('timeScale3')
        cancelTimer('timeScale4')
        cancelTimer('timeRunOut3')
        cancelTimer('timeRunOut4')
        cancelTimer('timeScale5')
        cancelTimer('timeScale6')
        cancelTimer('timeRunOut5')
        cancelTimer('timeRunOut6')
        cancelTimer('out')
    end
end`

**Comment by HourOfEternity** [comment]
Try this (School internet hates me, so the code will look a bit weird):
`function onUpdate(elapsed)`
`    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.LEFT') then`
`        doTweenAlpha('yesA', 'yes', 1, 0.3, 'linear')`
`        doTweenAlpha('noA', 'no', 0.5, 0.3, 'linear')`
`    end`

**Comment by HourOfEternity** [comment]
`function onUpdate(elapsed)
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.LEFT') then
        doTweenAlpha('yesA', 'yes', 1, 0.3, 'linear')
        doTweenAlpha('noA', 'no', 0.5, 0.3, 'linear')
    end`

**Comment by HourOfEternity** [comment]
`function onUpdate(elapsed)
   if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.LEFT') then
        doTweenAlpha('yesA', 'yes', 1, 0.3, 'linear')
        doTweenAlpha('noA', 'no', 0.5, 0.3, 'linear')
    end`

**Comment by HourOfEternity** [comment]
function onUpdate(elapsed)
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.LEFT') then
        doTweenAlpha('yesA', 'yes', 1, 0.3, 'linear')
        doTweenAlpha('noA', 'no', 0.5, 0.3, 'linear')
    end
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.RIGHT') then
        doTweenAlpha('yesA', 'yes', 0.5, 0.3, 'linear')
        doTweenAlpha('noA', 'no', 1, 0.3, 'linear')
    end
    if keyJustPressed('accept') then
        doTweenAlpha('yesA', 'yes', 0, 0.5, 'linear')
        doTweenAlpha('noA', 'no', 0, 0.5, 'linear')
        startCountdown()
    end
    if startCountdown() == true then
        removeLuaSprite('time')
        cancelTimer('timeScale1')
        cancelTimer('timeScale2')
        cancelTimer('timeRunOut1')
        cancelTimer('timeRunOut2')
        cancelTimer('timeScale3')
        cancelTimer('timeScale4')
        cancelTimer('timeRunOut3')
        cancelTimer('timeRunOut4')
        cancelTimer('timeScale5')
        cancelTimer('timeScale6')
        cancelTimer('timeRunOut5')
        cancelTimer('timeRunOut6')
        cancelTimer('out')
    end
end

**Comment by HourOfEternity** [comment]
I have terrible school internet rn, but here is code that might work:

function onUpdate(elapsed)
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.LEFT') then
        doTweenAlpha('yesA', 'yes', 1, 0.3, 'linear')
        doTweenAlpha('noA', 'no', 0.5, 0.3, 'linear')
    end
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.RIGHT') then
        doTweenAlpha('yesA', 'yes', 0.5, 0.3, 'linear')
        doTweenAlpha('noA', 'no', 1, 0.3, 'linear')
    end
    if keyJustPressed('accept') then
        doTweenAlpha('yesA', 'yes', 0, 0.5, 'linear')
        doTweenAlpha('noA', 'no', 0, 0.5, 'linear')
        startCountdown()
    end
    if startCountdown() == true then
        removeLuaSprite('time')
        cancelTimer('timeScale1')
        cancelTimer('timeScale2')
        cancelTimer('timeRunOut1')
        cancelTimer('timeRunOut2')
        cancelTimer('timeScale3')
        cancelTimer('timeScale4')
        cancelTimer('timeRunOut3')
        cancelTimer('timeRunOut4')
        cancelTimer('timeScale5')
        cancelTimer('timeScale6')
        cancelTimer('timeRunOut5')
        cancelTimer('timeRunOut6')
        cancelTimer('out')
    end
end

Hope this helps, enjoy!

**Comment by Your-Local-LordXSimp** [comment]
Now I can't go into the pause menu (I did a LUA pause menu) and when I press LEFT and then then press ACCEPT it doesn't close the game.

**Comment by HourOfEternity** [comment]
Oops, I missed a bit of code that starts a timer. Put this in the `keyjustpressed('accept')`
`    	runTimer('out', 1)`

**Comment by Your-Local-LordXSimp** [comment]
Ok, I didn't see that part of the code wasn't there lol. I'll test it out later. :)

**Comment by Your-Local-LordXSimp** [comment]
I did some changes so that it could work, but now the countdown starts even when the choice thing is on screen, it's not supposed to. Also the `runTimer('out', 1)` part doesn't close the game.

`local allowCountdown = false;

function onStartCountdown()

    if not allowCountdown then

        allowCountdown = true;

        return Function_Stop;

    end

    return Function_Continue;

end

function onUpdate(elapsed)

	if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.LEFT') then

    	doTweenAlpha('yesA', 'yes', 1, 0.3, 'linear')

    	doTweenAlpha('noA', 'no', 0.5, 0.3, 'linear')

	end

    if getProperty('yes.alpha', 1) and keyJustPressed('space') then

    	doTweenAlpha('yesA', 'yes', 0, 0.5, 'linear')

    	doTweenAlpha('noA', 'no', 0, 0.5, 'linear')

    	startCountdown()

    end

    if startCountdown() == true then

    	removeLuaSprite('time')

    	removeLuaSprite('yes')

    	removeLuaSprite('no')

    	cancelTimer('timeScale1')

   	cancelTimer('timeScale2')

    	cancelTimer('timeRunOut1')

    	cancelTimer('timeRunOut2')

    	cancelTimer('timeScale3')

    	cancelTimer('timeScale4')

    	cancelTimer('timeRunOut3')

    	cancelTimer('timeRunOut4')

    	cancelTimer('timeScale5')

    	cancelTimer('timeScale6')

    	cancelTimer('timeRunOut5')

    	cancelTimer('timeRunOut6')

    	cancelTimer('out')

	end

	if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.RIGHT') then

    	doTweenAlpha('yesA', 'yes', 0.5, 0.3, 'linear')

    	doTweenAlpha('noA', 'no', 1, 0.3, 'linear')

	end

	if getProperty('no.alpha', 1) and keyJustPressed('space') then

    	doTweenAlpha('yesA', 'yes', 0, 0.5, 'linear')

   	doTweenAlpha('noA', 'no', 0, 0.5, 'linear')

        runTimer('out', 1)

    end

end

function onTimerCompleted(tag)

	-- TIMER --

	if tag == 'out' then

		os.exit()

	end

end
`
