### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by BBG56789** [ShadowMario/FNF-PsychEngine#14503]
### Describe your problem here.

when i run lime test windows, pretty much everything says "... referenced here"
[e.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/15042865/e.txt)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by BBG56789** [comment]
forgot to mention, im trying to build the source code for 0.6.3

**Comment by ShadowMario** [comment]
0.6.3 is not supported anymore since December 2023
