### ISSUE TITLE
Question about adding images.

### ISSUE THREAD

**Issue by StinkTheStinker** [ShadowMario/FNF-PsychEngine#14504]
### Describe your problem here.

How do I add images to the pause menu?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JHAM25** [comment]
Creo que no se puede, pero se puede crear un pausa desde creo y hacerlo a tu gusto

**Comment by StinkTheStinker** [comment]
Esta es la cuestión, no sé cómo codificar.
También utilicé el traductor de Google para esto.

**Comment by JHAM25** [comment]
Quieres que te envié un ejemplo de un menu de pausa? O tienes una idea de como quiere que se vea para ayudarte

**Comment by StinkTheStinker** [comment]
Es como una imagen renderizada en el menú de pausa, como el mod 1.5 vs elegido.
Si quieres, puedes ponerlo en lua.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/145304742/69cd507e-6931-4cdf-a924-488118dbaaa4)
Usé paint.net para esta mierda.

**Comment by JHAM25** [comment]
Mira si esto te funciona:
luaDebugMode = true

function onCreate()
addHaxeLibrary('FlxCamera', 'flixel')

    makeLuaSprite('aaa', 'logo')
    --setObjectCamera('aaa', 'camOther')
    --setObjectOrder('aaa', 1000)
    addLuaSprite('aaa', true)
    
    runHaxeCode([[
    var camaraNueva = new FlxCamera();
    
    camaraNueva.bgColor = 123456;
    FlxG.cameras.add(camaraNueva, false);
    
    
    game.getLuaObject("aaa").cameras = [camaraNueva]
    ]])
end

function onPause()

    --return Function_Stop
end
function onSongStart()
end

**Comment by StinkTheStinker** [comment]
heres one thats on pause/resume
```
--og script made by JHAM25
-- fixed up script made by stink
luaDebugMode = true
function onPause()
addHaxeLibrary('FlxCamera', 'flixel')
makeLuaSprite('aaa', 'image',670,100)--set the "image" to the image you want it to be, i reccomend keeping the offset like this
addLuaSprite('aaa', true)
runHaxeCode([[
var camaraNueva = new FlxCamera();
camaraNueva.bgColor = 123456;
FlxG.cameras.add(camaraNueva, false);
game.getLuaObject("aaa").cameras = [camaraNueva]
]])
end

function onResume()
	removeLuaSprite('aaa', true)-- never knew the removeLuaSprite was a thing
end

```

**Comment by StinkTheStinker** [comment]
heres an resolution i reccomend

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/145304742/51402f0e-ad73-4b4a-bb20-640865cef43d)
