### ISSUE TITLE
My addAnimationByPrefix isn't working

### ISSUE THREAD

**Issue by Yandurva08** [ShadowMario/FNF-PsychEngine#14507]
### Describe your problem here.

I have trying to make people looking at characters sings at background but isn't working it shows nothing
![Screenshot_20240420-095131](https://github.com/ShadowMario/FNF-PsychEngine/assets/94998555/6750958e-6c14-4387-b69d-814a6df30abe)
If you want to me send a specific image i can

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

Nop

**Comment by JHAM25** [comment]
Te falto añadir el addLuaSprite('fuckers')

**Comment by Yandurva08** [comment]
> Te falto añadir el addLuaSprite('fuckers')

Still nothing 
![Screenshot_20240420-113400](https://github.com/ShadowMario/FNF-PsychEngine/assets/94998555/7f39d263-6a9a-498e-bbb4-6fff374677b8)

**Comment by JHAM25** [comment]
Puedes verificar si el nombre de la animación esta correcto o la posición De objeto o también puedes poner esto
doTweenZoom('prueba', 'camGame', 0.5, 1)

**Comment by Yandurva08** [comment]
Thank you is here now :)
![Screenshot_20240420-115200](https://github.com/ShadowMario/FNF-PsychEngine/assets/94998555/ad09bcdd-141b-437b-adb9-0c9d3b351fd2)
