### ISSUE TITLE
luaSpriteMakeGraphic error in 0.6.2

### ISSUE THREAD

**Issue by Gla90l** [ShadowMario/FNF-PsychEngine#14502]
### Describe your problem here.

Soo, i used lua script that says "**luaSpriteMakeGraphic**". I made it black, but why does this is white and transparent?

![Снимок экрана 2024-04-19 182859](https://github.com/ShadowMario/FNF-PsychEngine/assets/164686246/f2eef75a-ce62-4985-85fe-86ce9cdfe0db)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited only main menu state for remove some buttons and credit state to make it looks like a gallery

**Comment by LarryFrosty** [comment]
hxcpp issue, use git
`haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp/`

Also, please, use `makeGraphic`
if you need to know more lua functions, you can look at this wiki: https://github.com/Meme1079/PsychWiki/wiki/Lua-Script-API

**Comment by ShadowMario** [comment]
luaSpriteMakeGraphic is deprecated and you're using an unsupported version of Psych Engine.
