### ISSUE TITLE
Changing BPM fucks up chart editor.

### ISSUE THREAD

**Issue by Average-FNF-Modder** [ShadowMario/FNF-PsychEngine#14517]
### Describe your bug here.

When I attempted to change the BPM of my song, all sections afterwards either had no notes or their notes compressed above the top of the section, even though they play back perfectly fine in level. You can even still place more notes in those sections as normal, but no matter how many times I reloaded, the screwed notes wouldn't fix unless I undid the BPM change.

Pretty sure this is a bug, I have attached a video of the phenomenon below.

https://github.com/ShadowMario/FNF-PsychEngine/assets/157259571/001447b6-efdf-46db-b42d-5e04b23f7b82

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I have changed nothing in this build.

**Comment by HourOfEternity** [comment]
when you change the bpm, it changes the amount of strums that can hold a note. 

Lets say you have a bpm of 100 with notes at steps 20, 40, and 60. If you were to change the bpm to 120, there is suddenly a 20% increase in the beats per second. The notes are still at steps 20, 40, and 60, but if the section the notes were in happened to change (if step 20 was in section 2, then after the bpm change it might become section 1), then it results in what happened with you: being that the notes are only visible in the section they were originally placed in.

FIX: You need to change the bpm back, and find a way to note what step the notes are in. You basically have to clear the chart, change the bpm, then place the notes in the same step, in the correct section.

**Comment by Average-FNF-Modder** [comment]
Damn, thanks dude, that's super annoying when you already have 100's of notes placed lmao. In that case Shadow should add a fix where you can reload the arrows to whatever step they are assigned to fix it. It's still kind of an issue, so I'll leave dis open for now.

> when you change the bpm, it changes the amount of strums that can hold a note.
> 
> Lets say you have a bpm of 100 with notes at steps 20, 40, and 60. If you were to change the bpm to 120, there is suddenly a 20% increase in the beats per second. The notes are still at steps 20, 40, and 60, but if the section the notes were in happened to change (if step 20 was in section 2, then after the bpm change it might become section 1), then it results in what happened with you: being that the notes are only visible in the section they were originally placed in.
> 
> FIX: You need to change the bpm back, and find a way to note what step the notes are in. You basically have to clear the chart, change the bpm, then place the notes in the same step, in the correct section.

**Comment by tposejank** [comment]
> when you change the bpm, it changes the amount of strums that can hold a note.
> 
> Lets say you have a bpm of 100 with notes at steps 20, 40, and 60. If you were to change the bpm to 120, there is suddenly a 20% increase in the beats per second. The notes are still at steps 20, 40, and 60, but if the section the notes were in happened to change (if step 20 was in section 2, then after the bpm change it might become section 1), then it results in what happened with you: being that the notes are only visible in the section they were originally placed in.
> 
> FIX: You need to change the bpm back, and find a way to note what step the notes are in. You basically have to clear the chart, change the bpm, then place the notes in the same step, in the correct section.

Correction: If you change the BPM, the notes won't be at the same step. The notes are all measured by time, grouped by 4 beat sections. If a section has notes and those notes have times corresponding to another section, they will all chill at the top or at the bottom. There are ways to fix this but you have to get technical (aka, do some coding)

**Comment by GarfieldGlitch** [comment]
bruh i had this issue today it's so annoying. im going to have to either clear my chart or try and do it with my previous notes which is kinda bad

**Comment by LarryFrosty** [comment]
> bruh i had this issue today it's so annoying. im going to have to either clear my chart or try and do it with my previous notes which is kinda bad
> i'd also like to point out shadow mario saw this but didn't put a fix to this?

Because it's already implemented in the 1.0 chart editor rewrite.

**Comment by PossiblyPix** [comment]
BETTER FIX: open the json file in notepad, scroll down to the very bottom, and change the bpm, works just fine after that

**Comment by Average-FNF-Modder** [comment]
> BETTER FIX: open the json file in notepad, scroll down to the very bottom, and change the bpm, works just fine after that

There shouldn't be an option to change the bpm if it doesn't work.
