### ISSUE TITLE
freeplay crashes when opened

### ISSUE THREAD

**Issue by LucaPanellas** [ShadowMario/FNF-PsychEngine#14510]
### Describe your bug here.

freeplay just crashes whenever i try to open it

### Command Prompt/Terminal logs (if existing)

```bash
states/FreeplayState.hx (line 72)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i didnt, this started happening after i tried to change the bf death animation

**Comment by LucaPanellas** [comment]
im on version 0.7.3 btw

**Comment by trainershawn** [comment]
i’ve been having the same issue :(
if anyone can find a fix please reply!
this started happening around 2 days ago same as you

**Comment by Neckrozma** [comment]
im having it too.
anyone please help.

**Comment by LucaPanellas** [comment]
i figured out that i saved it in the wrong folder, causing freeplay to try reading the character file

**Comment by willow-tree902** [comment]
i was messing around with scripts from joner (17boos, multi-player-chars), and freeplay just suddenly stopped working
