### ISSUE TITLE
How do I make a random menu in Source Code in FNF on Psych Engine?

### ISSUE THREAD

**Issue by SuperYagoFNF** [ShadowMario/FNF-PsychEngine#14512]
Como Faz um menu aleatório em Source Code no FNF na Psych Engine?
How do I make a random menu in Source Code in FNF on Psych Engine?

**Comment by WolfyTail** [comment]
Use **FlxG.random.int(0, theAmountOfMenusYouWantToCreate - 1)**
Then with a **switch**, you can "make a random menu appear" when you enter the Main Menu State.
Something like:

` var menuNumber:Int = FlxG.random.int(0, 4) //That means you have FIVE menus.

switch(menuNumber)
   case 0:
      //Insert your code here.
   case 1:
     //Insert your code here.
//Repeat for each case from 0 to 4 in this case.
`

Hope it helps :)
