### ISSUE TITLE
Character tied Lua scripts

### ISSUE THREAD

**Issue by Average-FNF-Modder** [ShadowMario/FNF-PsychEngine#14516]
### What feature do you want to get added on the **base** engine?

There are song specific scripts, full mod scripts, stage specific scripts, but no option if you want to have a script run when a certain character is in use, and I think that would be a cool feature. Would make custom game overs simpler to, cause you wouldn't have to drag the game over script into each song that character is used in.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
Characters lua scripts already exists

**Comment by Average-FNF-Modder** [comment]
On god if they do, I can't get them to work. I've tried.
@ShadowMario 

> Characters lua scripts already exists
