### ISSUE TITLE
"source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall" (Mac)

### ISSUE THREAD

**Issue by papopelo** [ShadowMario/FNF-PsychEngine#14515]
### Describe your bug here.

Im trying to build the decomp on Mac, but I always get this error:
![Screenshot 2024-04-21 at 11 43 10](https://github.com/ShadowMario/FNF-PsychEngine/assets/81886823/2652e8d7-ee05-4f05-a0ec-29568b33ec45)

I don't know what to do T-T

### Command Prompt/Terminal logs (if existing)

```bash
source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just download it (and the dependences)

**Comment by JadeSneko** [comment]
same thing is happening to me on windows and im desperately trying to find a fix

**Comment by LarryFrosty** [comment]
Replace every TeaCall with Tea in the HScript.hx file

**Comment by papopelo** [comment]
ok so now I have this:
![Screenshot 2024-04-22 at 21 26 29](https://github.com/ShadowMario/FNF-PsychEngine/assets/81886823/5cb428f8-e1ca-4d99-90bb-1bf3fac56e8c)

:p

**Comment by JadeSneko** [comment]
same thing happened to me too lmao

**Comment by LarryFrosty** [comment]
I suggest reading
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by papopelo** [comment]
ok so now it works perfectly, thanks :)
