### ISSUE TITLE
I got a source compile error

### ISSUE THREAD

**Issue by MaximumX64** [ShadowMario/FNF-PsychEngine#14519]
### Describe your problem here.

before i got that teacall error now i got this error
![help2](https://github.com/ShadowMario/FNF-PsychEngine/assets/167785527/6e85e06e-70c7-4350-a95e-9da097f9f52c)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes i edited HScript.hx

**Comment by MaximumX64** [comment]
Please help

**Comment by Vortex2Oblivion** [comment]
You forgot a }

**Comment by MaximumX64** [comment]
I dont understand

**Comment by richTrash21** [comment]
you forgot to close a function/expression at line 490

**Comment by MaximumX64** [comment]
ok im going to try it

**Comment by MaximumX64** [comment]
Now i got this
![help3](https://github.com/ShadowMario/FNF-PsychEngine/assets/167785527/8851f371-3c33-441c-8ef8-22e52fcb3620)

**Comment by Vortex2Oblivion** [comment]
That's good
It means it's working
