### ISSUE TITLE
Changing pause screen text.

### ISSUE THREAD

**Issue by Average-FNF-Modder** [ShadowMario/FNF-PsychEngine#14518]
### What is your question?

I want to change the pause screen to display more information, such as accuracy, score, and the author of the song + other contributors to the level you're playing. Is their some variable I can change or function I can use for this?

**Comment by ac-phoenix-yt** [comment]
Not in lua, but if it is in the source code then you can go and edit the file named "PauseSubState" or smt like that, and the blueballed text variable and yk you copy it and adjust offsets and all, you can look maybe at the playstate to see what are the variable names you wanna add
