### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by WolfyTail** [ShadowMario/FNF-PsychEngine#14513]
### Describe your problem here.

Hello. I'm trying to compile the 0.7.3 version, but I get this error. I've already installed "hxdiscord_rpc". What can I do?
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/95707370/d69ba9c8-3072-4a86-9946-73140a5f3d19)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ac-phoenix-yt** [comment]
try reinstalling  :c

**Comment by WolfyTail** [comment]
I have reinstalled all the Visual Studio Build Tools, every library from Haxelib, and I even tried to compile every version from 0.7.0 to 0.7.3. And nothing.

**Comment by ac-phoenix-yt** [comment]
maybe try instead of "lime test windows" try "crl+shift+b" and before that rename to any random name the folder named "export"

**Comment by WolfyTail** [comment]
Didn't work.
