### ISSUE TITLE
SOURCE CODE COMPILING ERROR [7.3.0h]

### ISSUE THREAD

**Issue by ac-phoenix-yt** [ShadowMario/FNF-PsychEngine#14528]
### Describe your problem here.

I have every neccesary haxe libs installed and when i do the "lime test windows" thing i get an error that says:

source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/168007939/52fde051-ebdf-4fb3-8412-2c83bbde2343)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

just edited the credits [to add my dev team] and removed mods and donate from the menu: 	var optionShit:Array<String> = [ 		'story_mode', 		'freeplay', 		//#if MODS_ALLOWED 'mods', #end 		#if ACHIEVEMENTS_ALLOWED 'awards', #end 		'credits', 		//#if !switch 'donate', #end 		'options' 	];

also the exit thing says this every time i try to compile:

[Error - 18:04:56] Request textDocument/codeLens failed.
  Message: source/backend/Discord.hx:36: characters 42-74 : You cannot access the cpp package while targeting js (for cpp.RawConstPointer)
  Code: -32603 

![Uploading image.png…]()

**Comment by SammyXDDD** [comment]
Replace every TeaCall with Tea in the HScript.hx file
