### ISSUE TITLE
Compiling error(SendErrorsToLua)

### ISSUE THREAD

**Issue by GIDRO32** [ShadowMario/FNF-PsychEngine#14526]
### Describe your problem here.

source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, not at all

**Comment by HellBeater** [comment]
Did you compile with [This link]?(https://cdn.discordapp.com/attachments/1000603105265733749/1097573978631045290/setup.bat)

**Comment by HellBeater** [comment]
If so.

all of these need a terminal / command prompt open, so get ready to type stuff

Press Windows+R and type "cmd"
if you are on Linux, just refer to your Desktop Environment's keybinds to open a new terminal (usually Ctrl+Shift+T)

...or launch it from your start menu

"Library not found: hxCodec" | "Invalid Class: MP4Handler" / "VideoHandler" FIX

type the following commands
haxelib remove hxCodec
haxelib install hxCodec

LUA RELATED ERRORS (mainly FunkinLua.hx returning errors)

type the following
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit

HXCPP_MSVC_CUSTOM ERROR (This is WINDOWS only error)

NOTICE: you need git installed in order for the next commands to work

type the following

curl -# -O https://download.visualstudio.microsoft.com/download/pr/3105fcfe-e771-41d6-9a1c-fc971e7d03a7/8eb13958dc429a6e6f7e0d6704d43a55f18d02a253608351b6bf6723ffdaf24e/vs_Community.exe

vs_Community.exe --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.19041 -p

del vs_Community.exe

NOTICE: if del vs_Community.exe returns an error, simply delete the file manually
