### ISSUE TITLE
No Inst or Voices after compiling

### ISSUE THREAD

**Issue by Levente423le** [ShadowMario/FNF-PsychEngine#14527]
### Describe your problem here.

I compiled a couple times, fixing issues and new ones appearing. In this time, there are all the song's Inst and Voices in the assets, but when i start the week or a song from freeplay, the title song starts playing. In week 7 the animation starts normal, but after no Inst or Voices starts playing, not even the title song.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by ac-phoenix-yt** [comment]
Hmmmmm  maybe it might me songs folder and datas folder haves names wrong, you should check that

**Comment by Levente423le** [comment]
> Hmmmmm maybe it might me songs folder and datas folder haves names wrong, you should check that

ok
