### ISSUE TITLE
Note isn't spinning on beat

### ISSUE THREAD

**Issue by Yandurva08** [ShadowMario/FNF-PsychEngine#14530]
### Describe your problem here.

I'm trying to make the note spin until a event is triggered but it only spin two time and never more what is the problem here?

Here's code btw:
```beOn = true
turn = 0
time = crochet/500

function onBeatHit()
if beOn == true then
if turn == 0 then

noteTweenAngle('n1', 4, 360, time, 'backInOut')
noteTweenAngle('n2', 5, 360, time, 'backInOut')
turn = 1

else

noteTweenAngle('n3', 6, -360, time, 'backInOut')
noteTweenAngle('n4', 7, -360, time, 'backInOut')
turn = 0

end
end
end


function onEvent(n, v1, v2)
if n == 'epic moment' then
if v1 == '1' then
beOn = false
end
end
end```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
This is because the angle stays at 360/-360 after the tween
You can set the angle back to 0 before the tween starts to fix this

**Comment by Yandurva08** [comment]
> This is because the angle stays at 360/-360 after the tween You can set the angle back to 0 before the tween starts to fix this

How i didn't notice that?
Btw it works now thanks!
