### ISSUE TITLE
Easy way to change custom lua sprite's position

### ISSUE THREAD

**Issue by mayo78** [ShadowMario/FNF-PsychEngine#1453]
### What feature do you want to get added on the base engine?

why cant you do this already

**Comment by Doritojoey** [comment]
They're planning to make a stage editor but it requires a lot of work so definitely be patient

**Comment by MayoALT** [comment]
i mean like a way to just set a sprites position in a song script (ex: awesomesprite.x = 1234)

**Comment by ShadowMario** [comment]
`setProperty('luaSpriteNameHere.x', value);`

![image](https://user-images.githubusercontent.com/44785097/144555047-83551f07-e7f7-49d4-ac80-34a4fb6b895b.png)
