### ISSUE TITLE
Compiling issues need help

### ISSUE THREAD

**Issue by HaileyTheCartoonist** [ShadowMario/FNF-PsychEngine#14533]
### Describe your problem here.

source/states/PlayState.hx:36: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
C:/HaxeToolkit/haxe/lib/flixel-addons/2,10,0/flixel/addons/transition/FlxTransitionableState.hx:81: lines 81-90 : Warning : switchTo is deprecated, use startOutro
source/states/PlayState.hx:3479: characters 51-67 : Type not found : FlxRuntimeShader

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by Stefan2008Git** [comment]
Buddyy, why are you using the older version of Flixel addons?

**Comment by HaileyTheCartoonist** [comment]
> Buddyy, why are you using the older version of Flixel addons?

Im usings 3.2.1 what verion do i use?

**Comment by Stefan2008Git** [comment]
> > Buddyy, why are you using the older version of Flixel addons?
> 
> Im usings 3.2.1 what verion do i use?

The latest one with bugfixes. Not the broken one
