### ISSUE TITLE
Error of OS engine!

### ISSUE THREAD

**Issue by TheBamber** [ShadowMario/FNF-PsychEngine#14535]
### Describe your bug here.

every time I try to go to freeplay for my mods, the game closes.
This message appears here:
![25 04 2024_11 21 08_REC](https://github.com/ShadowMario/FNF-PsychEngine/assets/168106140/02b73858-e288-478e-b1c3-dfca01f4528c)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no.

**Comment by JHAM25** [comment]
Creo que tienes que poner tu error en la página de os engine

**Comment by TheBamber** [comment]
ok JHAM25

**Comment by Stefan2008Git** [comment]
...
What the fuck 💀

**Comment by CobaltBar** [comment]
OS Engine is a psych fork

not only is os engine dead
you shouldn't put bug reports here for other engines

**Comment by Stefan2008Git** [comment]
> OS Engine is a psych fork
> 
> not only is os engine dead you shouldn't put bug reports here for other engines

Blud is talking the truth. Actually the official OS Engine repository is archived, so he cannot report issue or make a new PL

**Comment by ShadowMario** [comment]
> > OS Engine is a psych fork
> > not only is os engine dead you shouldn't put bug reports here for other engines
> 
> Blud is talking the truth. Actually the official OS Engine repository is archived, so he cannot report issue or make a new PL

Too fucking bad lol!
