### ISSUE TITLE
camGame

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#1454]
### What needs to be documented?

you can use `camGame.angle` and `camHUD.angle` to do stuff like this:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/93293747/143788469-987510b3-0591-41b5-8732-b3367fade72f.gif)
I think this should be documented somewhere, also there's probably other stuff with `camGame` that you could put there too, maybe there's scale, position and opacity stuff there too

**Comment by Small-talking** [comment]
I agree with this Post, i use a bit of the camGame Function, and it took some time to figure out, lol

**Comment by ShadowMario** [comment]
Both.
camGame is the camera used for characters/stage.
camHUD is the camera used for... HUD.
