### ISSUE TITLE
My character editor aint character editing

### ISSUE THREAD

**Issue by OlitoLol** [ShadowMario/FNF-PsychEngine#14540]
### Describe your bug here.

uhhh its all black except the ui
![image_2024-04-25_230355748](https://github.com/ShadowMario/FNF-PsychEngine/assets/167153560/4cff02f9-ce56-41f1-9e83-e6705dff375e)
every other editor is fine

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yea i only changed the game icon and name on project.xml tho

**Comment by Realmzer** [comment]
bro i got this too only when im building from source

**Comment by Realmzer** [comment]
you just have to update your libs [Libs required](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions)

**Comment by Stefan2008Git** [comment]
You need to remove the cross cursor graphic code and change to something different during the Flixel 5.7.0+ changes
