### ISSUE TITLE
No asset library for "songs"

### ISSUE THREAD

**Issue by maooni5** [ShadowMario/FNF-PsychEngine#14549]
### Describe your bug here.

So everything went perfect until i did the lime test windows, after it opened it showed me this message
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/95535696/62fb7947-8a1a-42be-b997-e9baf5855663)

### Command Prompt/Terminal logs (if existing)

```bash
[lime.utils.Preloader] ERROR: there is no asset library of an id of "songs"
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by maooni5** [comment]
update: i reopened setup.windows.bat and now it shows this


Compiling group: haxe
cl.exe -Iinclude -IC:/Users/mhz255/haxelib install actuate/hxdiscord_rpc/git/project/discord-rpc/include -DDISCORD_DISABLE_IO_THREAD -IC:/Users/mhz255/haxelib install actuate/linc_luajit/git//linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\ع┌غ\Artificial Wooden Cat\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/Users/mhz255/haxelib install actuate/hxcpp/4,3,2/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_CHECK_POINTER(haxe) -DHXCPP_STACK_TRACE(haxe) -DHXCPP_STACK_LINE(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=430(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/ApplicationMain.cpp
 - src/lime/utils/AssetCache.cpp  [haxe,release]
Link: ApplicationMain.exe
   Creating library ApplicationMain.lib and object ApplicationMain.exp
49d10c9b_OES_stencil1.obj : error LNK2011: precompiled object not linked in; image may not run
  Hint on symbols that are defined and could potentially match:
    __@@_PchSym_@00@UKmqKruKmrKoqKmqKrtUumuRkhbxsvmtrmvRnzrmUvckligUivovzhvUdrmwldhUlyqUlyqUnhexBJGERmxUPPkxsUifmgrnvUscxkkOlyq@link9b42fce1b7dcee2a3b3ccd2e270c41b9
    __@@_PchSym_@00@UKmqKruKmrKoqKmqKrtUzigrurxrzoLdllwvmLxzgUvckligUivovzhvUdrmwldhUlyqUlyqUnhexBJGERmxUPPkxsUszcvUscxkkOlyq@link8d425a60fd2dcd6a010d68a430d8dd15
ApplicationMain.exe : fatal error LNK1120: 1 unresolved externals

**Comment by Stefan2008Git** [comment]
I still have this issue because of latest Lime version, so i prefer to switch on 8.0.2 for best

**Comment by choripan8989** [comment]
> I still have this issue because of latest Lime version, so i prefer to switch on 8.0.2 for best

How to switch on 8.0.2?

**Comment by Stefan2008Git** [comment]
> > I still have this issue because of latest Lime version, so i prefer to switch on 8.0.2 for best
> 
> How to switch on 8.0.2?

This requires a source code for that,  so
`haxelib remove lime
 haxelib install lime 8.0.2
 haxelib set lime 8.0.2`
