### ISSUE TITLE
So, I'm not good at coding and don't even know what to do about this crash

### ISSUE THREAD

**Issue by D-3VEVO** [ShadowMario/FNF-PsychEngine#14544]
### What is your question?

![Friday Night Funkin'_ Psych Engine 4_26_2024 8_38_39 AM](https://github.com/ShadowMario/FNF-PsychEngine/assets/115375821/e39698f0-1e61-49cd-bf05-c8e23271581c)

What the fuck do I even do about this, I hit enter to open a song (as you do) then this shit pops up.

**Comment by Stefan2008Git** [comment]
Are you using the latest Flixel version? If it is, you need to change `MusicBeatState.switchState `to `FlxG.switchState(() -> new File());`. More information to this pr
https://github.com/ShadowMario/FNF-PsychEngine/pull/14362
