### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Trianityy** [ShadowMario/FNF-PsychEngine#14547]
### Describe your problem here.

hscript/Interp.hx (line 263)
hscript/Interp.hx (line 457)
StageConstructor.hx (line 114)
PlayState.hx (line 4546)
MusicBeatState.hx (line 58)
PlayState.hx (line 2517)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: assets/stages/treehouse/stage.hxs:688: Invalid access to field alpha
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by maooni5** [comment]
first delete the export file then write this in terminal or powershell
haxelib install lime 8.0.2
the latest lime version is broken
