### ISSUE TITLE
Encountering a crash while on full screen (ALT+Enter version). will make basic ways to close out of the game impossible. (or even to use it)

### ISSUE THREAD

**Issue by SpiritualGo78** [ShadowMario/FNF-PsychEngine#14552]
### Describe your bug here.

I don't particularly appreciate viewing games in windowed mode, and since F11 doesn't work for Psych Engine, I use ALT+Enter instead to make it full screen. But as an FNF coder and modder, I have experienced many crashes before, and most of these times, I was on full screen. Whenever it happens on full screen, the message pops up like normal. However, clicking on the game will cause the entire window to disappear. It makes me unable to press the OK button and continue the game like normal. Also closing the game is impossible. Whenever I however over the icon on the desktop bar, clicking X won't close it at all and even ALT+F4 doesn't work either. Also pressing ALT+Enter again won't fix it. It just stays in full screen.

The only way I was able to close it is by restarting my computer or ending the application in Task Manager. But it comes at a huge cost of clearing most progress and it takes too much time. Shadow, please just take note of this, this annoys me and it's really bugging me out.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Lorekeeper49** [comment]
This actually happens for lua modders too, the best way to close the game in this case is to end the task from the task manager.
This is a problem with errors that's been happening since 0.6 and it still hasn't been fixed

**Comment by Stefan2008Git** [comment]
> This actually happens for lua modders too, the best way to close the game in this case is to end the task from the task manager. This is a problem with errors that's been happening since 0.6 and it still hasn't been fixed

 Maybe it's a Flixel thing bugthat makes this shit unstable, so probably the latest version fixed that
