### ISSUE TITLE
Anti-Aliasing for Menu Characters

### ISSUE THREAD

**Issue by kentongus** [ShadowMario/FNF-PsychEngine#14561]
### What feature do you want to get added on the **base** engine?

Hi Psych Engine developers, I'll make this quick and short

So currently, there's no option to modify the anti-aliasing of a Menu Character, can you add it please? because uhhhh
![uhhh](https://github.com/ShadowMario/FNF-PsychEngine/assets/158790335/83ef36cb-dc2a-4daa-926c-42618a8ee84e)

Thank you!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Stefan2008Git** [comment]
This should be added already, but it's on to-do list if i am not wrong
