### ISSUE TITLE
CHARACTER EDITER BUG THING IDK

### ISSUE THREAD

**Issue by MrPogYT** [ShadowMario/FNF-PsychEngine#14569]
### Describe your bug here.

![image_2024-05-01_070336583](https://github.com/ShadowMario/FNF-PsychEngine/assets/168594873/bcdca415-0b9f-4ce2-942f-30dfc4b26a9f)
 My physic engine crashes everytime i try to load in my character in the character editor.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Stefan2008Git** [comment]
Maybe you are missing the character spritesheet from folder or it's your .xml file corrupted
