### ISSUE TITLE
COMPILATION PROCESS STOPS RANDOMLY [0.6.3, since i'm just used to it xd]

### ISSUE THREAD

**Issue by SmokeyRabbit** [ShadowMario/FNF-PsychEngine#14567]
### Describe your problem here.

CMD prompt just stops at this step for me while compiling:
"Creating library ApplicationMain.lib and object ApplicationMain.exp"

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nuh uh

**Comment by ShadowMario** [comment]
0.6.3 is not supported anymore since December 2023, this doesn't mean it can't be compiled anymore, it just means you're on your own to figure out how to fix this issue (might have tutorials online for this though)
