### ISSUE TITLE
Song bug!

### ISSUE THREAD

**Issue by AronGamer890** [ShadowMario/FNF-PsychEngine#14568]
### Describe your problem here.

Im currently making a mod, and i made that mod with the build psych engine until now bcuz i got the source code and i want to continue the modding with that. I imported my mod to the source code and theres a bug, when i play one of my custom songs, the chart is working, but my song is replaced by the menu theme. somebody please help! thanks!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by AronGamer890** [comment]
nevermind i got it

**Comment by TheKAPtain313** [comment]
> nevermind i got it

WAIT HOW I NEED TO KNOW TOO
