### ISSUE TITLE
Can u Help me?

### ISSUE THREAD

**Issue by PedroNiccola** [ShadowMario/FNF-PsychEngine#14560]
### Describe your problem here.

I am trying to compile Psych Engine Source Code Edition, but powershell always tells me to Replace "SCall" with "TeaCall", even if the HxScript.hx file already has TeaCall, can you solve it?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by PedroNiccola** [comment]
can you solve the problem?

**Comment by SilverT4** [comment]
Is this message a warning or an error? If it's a warning and the game compiles, it's probably something you can ignore.

**Comment by PedroNiccola** [comment]
it's an error
