### ISSUE TITLE
separate voices files crashed the game

### ISSUE THREAD

**Issue by MitchTOM1409** [ShadowMario/FNF-PsychEngine#14563]
### Describe your bug here.

i was updating one of the mods i have to take advantage of 0.7.3's Voices-Player/Voices-Opponent thing and this error happened

![error message](https://github.com/ShadowMario/FNF-PsychEngine/assets/77859036/6f51cb91-b045-4738-af8d-e0823909eee1)

edit: something tells me this was a skill issue but if there's another box you need to check to enable that, i can't see it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i only use the mod folder

**Comment by MitchTOM1409** [comment]
**the** [REDACTED] **file was corrupted**

**Comment by MitchTOM1409** [comment]
**the** [REDACTED] **file was corrupted**

**Comment by MitchTOM1409** [comment]
the file was not corrupted

**Comment by Hirlin13** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/168676075/c0351e47-602d-497e-8fb4-d2dd95056927)
In the file name, its trying to load (songs//endless/) instead of (songs/endless/), maybe update the file location
Idk this was worded poorly
