### ISSUE TITLE
Cool base game uppdate shiz!

### ISSUE THREAD

**Issue by Average-FNF-Modder** [ShadowMario/FNF-PsychEngine#14572]
### What feature do you want to get added on the **base** engine?

I know this'll probably happen anyways, but things like the zooming on songs, hold note splashes, cool freeplay, new hey animation on Bf for Spookez, results screen, AND WEEK MOTHERFUCKING 8!!
Yeah, all of that, pls. NEW UPDATE ROCKS!!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
Fuck off the update barely dropped
