### ISSUE TITLE
TeaCall Error

### ISSUE THREAD

**Issue by PedroNiccola** [ShadowMario/FNF-PsychEngine#14576]
### Describe your problem here.

I am trying to compile Psych Engine Source Code Edition, but powershell always tells me to Replace "SCall" with "TeaCall", even if the HxScript.hx file already has TeaCall, can you solve it?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by 2JENO** [comment]
check SScript version

**Comment by PedroNiccola** [comment]
How?

**Comment by 2JENO** [comment]
> How?

haxelib set SScript 7.7.0

**Comment by ManjihafYT** [comment]
Go to C:\Users\Your User\Where ever you keep your source code\Psych Engine\source\psychlua and open HScript And Change All The TeaCall To Tea. it worked for me

**Comment by 2JENO** [comment]
> Go to C:\Users\Your User\Where ever you keep your source code\Psych Engine\source\psychlua and open HScript And Change All The TeaCall To Tea. it worked for me

uh... uh?

**Comment by Fletchunter** [comment]
> Go to C:\Users\Your User\Where ever you keep your source code\Psych Engine\source\psychlua and open HScript And Change All The TeaCall To Tea. it worked for me

it actually works thxx..

**Comment by PedroNiccola** [comment]
I meant:
source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here

**Comment by 2JENO** [comment]
check lua version

**Comment by 2JENO** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions

**Comment by 2JENO** [comment]
> I meant:
> source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
> export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here

linc_luajit: git, to install, use: haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git

**Comment by PedroNiccola** [comment]
still same error

**Comment by PedroNiccola** [comment]
Hello?

**Comment by PedroNiccola** [comment]
will you guys answer?????????????
