### ISSUE TITLE
idk i cant play it i have a error

### ISSUE THREAD

**Issue by Coolman12662726266** [ShadowMario/FNF-PsychEngine#14570]
### Describe your bug here.

![image_2024-04-30_170426272](https://github.com/ShadowMario/FNF-PsychEngine/assets/140287530/b213f8e8-da7d-446d-8ed1-f3e5f2dbbee4)

### Command Prompt/Terminal logs (if existing)

```bash
nope
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Stefan2008Git** [comment]
You are probably have the corrupted .dll file for Lime
