### ISSUE TITLE
Reference save data for intro text.

### ISSUE THREAD

**Issue by Average-FNF-Modder** [ShadowMario/FNF-PsychEngine#14588]
### What feature do you want to get added on the **base** engine?

So like you could have a intro text that pulls from a setup .Txt save file that clowns you for however many times you've died for example, something that you could save with a Lua script.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
What?

**Comment by Average-FNF-Modder** [comment]
What kind of info you need man?
I know you can make a .Txt that sets custom intro texts, and that there is a function to create your own save data files that you can save to via Lua scripts. If I could pull a number from that save data to use in an intro texts, like:

54 deaths?
Dude do better

Tell me what's unclear and I'll try to explain.

**Comment by ShadowMario** [comment]
I understand now what you meant, that's not gonna happen though.

**Comment by Average-FNF-Modder** [comment]
Aww damn...
