### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by douglikesrugs** [ShadowMario/FNF-PsychEngine#14582]
### Describe your bug here.

Tried playing Jeffy's Endless Aethos using Crossover, crached and gave me this crash report.

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
FreeplayState.hx (line 363)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 550)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: [file_contents,assets/songs/aethos/aethos-hard.json]
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Stefan2008Git** [comment]
You are missing the chart file with orrect difficulty and song name
