### ISSUE TITLE
there is a bug

### ISSUE THREAD

**Issue by MaximumX64** [ShadowMario/FNF-PsychEngine#14585]
### Describe your bug here.

when i compile the source code  i go to the character editor and it only showes black  not even the stage is shown

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes but only for that type not found: teacall

**Comment by Stefan2008Git** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/pull/14495

**Comment by MaximumX64** [comment]
i dont understand

**Comment by biomseed** [comment]
> i dont understand

That's a pull request. It has changes to the engine, that being the fix to that bug. If ShadowMario decides to merge it, the issue will be fixed

**Comment by MaximumX64** [comment]
oh ok

**Comment by MaximumX64** [comment]
now i fixed the problem
