### ISSUE TITLE
Fading problems

### ISSUE THREAD

**Issue by SpiffyisntCool** [ShadowMario/FNF-PsychEngine#14580]
### Describe your problem here.

so i tried fading in the game back in with "cameraFade('camGame', '000000', 3, true)" but it only fades it to black, does the newest engine have a different command?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JHAM25** [comment]
Intenta con doTweenAlpha('camara', 'camGame', 0.5, 3)
Creo que cameraFade es para un color

**Comment by SpiffyisntCool** [comment]
> Intenta con doTweenAlpha('camara', 'camGame', 0.5, 3) Creo que cameraFade es para un color

it kind of only fades in half of the game instead of all of it

**Comment by JHAM25** [comment]
Nose si eso era lo que querías hacer o explica que resultado querías

**Comment by SpiffyisntCool** [comment]
> Nose si eso era lo que querías hacer o explica que resultado querías

so the song starts off as a black screen and i wanted to fade all the colors back in which it only fades in halfway

**Comment by SpiffyisntCool** [comment]
im trying to put aethos on the latest version of psych engine but the first event is cameraFade('camGame', '000000', 3, true) which tries to fade in the game when it started off as a black screen but in this version it just fades it for a bit and fades out

**Comment by JHAM25** [comment]
Algo asi?

https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/76f7b77d-b30b-4174-a02e-404c7ea12c4c

**Comment by SpiffyisntCool** [comment]
yeah i need something like that but heres what happends at my end

https://github.com/ShadowMario/FNF-PsychEngine/assets/107529060/a8f2c9c3-8b86-4081-8370-5061a40e6821

**Comment by SpiffyisntCool** [comment]
heres the json if you want to look at it 
[aethos.json](https://github.com/ShadowMario/FNF-PsychEngine/files/15196613/aethos.json)

**Comment by JHAM25** [comment]
Pon este:
doTweenAlpha('camara', 'camGame', 1, 3)

**Comment by SpiffyisntCool** [comment]
just makes the game black

**Comment by JHAM25** [comment]
No entiendo por qué se pone negro intenta recargar la canción

**Comment by JHAM25** [comment]
O prueba con esto:
function onCreate()
    makeLuaSprite('efecto', '', -10, -10)
    makeGraphic('efecto', 1400, 800, '000000')
    addLuaSprite('efecto', false)
    setObjectCamera('efecto', 'camOther')
end
function onStepHit()
    if curStep == 96 then
    doTweenAlpha('efecto', 'efecto', 0, 3)
    end
end

**Comment by SpiffyisntCool** [comment]
would i just put all of this on one event or multiple?

**Comment by JHAM25** [comment]
Supongo que en un evento

**Comment by SpiffyisntCool** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/107529060/15ba9c6a-6d4c-4ad0-8c76-b9530380defe)
i tried doing this and nothing happen, im not really good at this coding stuff :/

**Comment by JHAM25** [comment]
a perdon por no explicar bien tienes que crear un archivo.lua y pegar el código hay

**Comment by JHAM25** [comment]
a perdon por no explicar bien tienes que crear un archivo.lua y pegar el código hay 
![Screenshot_2024-05-03-20-47-27-896_com rhmsoft code](https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/aa9dbb84-5e86-4d7d-b134-5503a7258305)

**Comment by SpiffyisntCool** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/107529060/20ea17f4-1a3c-4c66-a811-9e351a87e14f)
ok ive pasted the code in here i just dont know how to export it to a lua file

**Comment by JHAM25** [comment]
Puedes importar tu carpeta a visual code,  vas a data/'tu canción" presionas click derecho, presionas new file y pones tu nombre y al final .lua
