### ISSUE TITLE
How do I load the song??

### ISSUE THREAD

**Issue by Shelbert-wastaken** [ShadowMario/FNF-PsychEngine#14599]
### Describe your problem here.

When I'm in the chart editor, it doesn't load the audio, no matter how many times I reload the audio. I named the song the same as the chart, and I named the audio files correctly, what am I doing wrong??

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SilverT4** [comment]
What does your directory structure look like? Does it look similar to this? I'm using House (from vs. Dave and Bambi) as an example song:

```
mods
| data
| | house
| | | house.json
- - - any additional difficulties and/or any lua script files
| songs
| | house
| | | Inst.ogg
- - - Vocals.ogg
```

If the game can't find the instrumental and vocals in the `songs/songName` folder, it won't be able to load them.
