### ISSUE TITLE
How to update mod?

### ISSUE THREAD

**Issue by Seledka1MC** [ShadowMario/FNF-PsychEngine#14595]
### Describe your problem here.

I do not know what to do to update the mod to 0.7.3, I currently have 0.6.2, please help! Explain what and how to do to update everything and robotalo, as the information in youtube and the Internet I have not found. I hope to help me.
I am the first to face this problem, and not particularly good at English, so I ask for help.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by JHAM25** [comment]
Puedes importar el mod a la vercion mas reciente escribe en un archivo.lua lo siguiente luaDebugMode = true 
Y si al jugarlo da errores mandalos para actualizar unas partes
