### ISSUE TITLE
Arrow thing

### ISSUE THREAD

**Issue by LucaGoku** [ShadowMario/FNF-PsychEngine#1459]
### Describe your problem here.

How do I do the Disruption arrow thing? Here is a video: 
https://www.youtube.com/watch?v=9RM48cXVj4k&t=8s

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't

**Comment by DEV-idiotXD** [comment]
use the tween stuff

**Comment by LucaGoku** [comment]
What's that? Idk how to code.

**Comment by DEV-idiotXD** [comment]
> What's that? Idk how to code.

in the wiki go to the tweens and timers thing

**Comment by LucaGoku** [comment]
I read it but I still don't understand.

**Comment by DEV-idiotXD** [comment]
come back when you learn how to code lua

**Comment by NS-Unfair** [comment]
There isn't a function in Lua to do this, you'll have to edit some stuff in the code to do this. I am working on adding these functions to Lua scripting.

**Comment by NS-Unfair** [comment]
I don't know how to do this in Haxe completely yet

**Comment by LucaGoku** [comment]
Oh, ok

**Comment by LucaGoku** [comment]
Oh, ok.

**Comment by DEV-idiotXD** [comment]
there is

> There isn't a function in Lua to do this, you'll have to edit some stuff in the code to do this. I am working on adding these functions to Lua scripting.

there is ya doughnut XD tweens and timers
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers
just put a 0.00001 duration and linear tweening method thing then in will be instantanious
