### ISSUE TITLE
How to add multiple opponents?

### ISSUE THREAD

**Issue by cometaj2** [ShadowMario/FNF-PsychEngine#14608]
### Describe your problem here.

I want to try and add multiple opponents to one side of the game, with different charts so they sing different things at the same time. For example five opponents against BF or vice versa

I’ve tried a few things, but none of them seem to work!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a few characters and a song with an edited JSON file

**Comment by Chidubemmo** [comment]
In lua you can do it by making the extra characters part of the background and make a note type to play it's sing animations
