### ISSUE TITLE
Trying To Chart Song Got Error Instead.

### ISSUE THREAD

**Issue by Neckrozma** [ShadowMario/FNF-PsychEngine#14601]
### Describe your problem here.

![image_2024-05-04_204132988](https://github.com/ShadowMario/FNF-PsychEngine/assets/118855206/df3b3680-dc27-4aa2-9151-5959ce118aab)
got this error

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by sofyisstupid** [comment]
did you change anything that has something to do with the ChartingState?
