### ISSUE TITLE
Trouble importing character

### ISSUE THREAD

**Issue by Squidd0** [ShadowMario/FNF-PsychEngine#14604]
### Describe your bug here.

When trying to import a character in the character editor, an error appears reading: "Error: No Animation Found".
I do have the accompanying .xml file along with the sritesheet, and even still it simply will not import into the editor. No character or anything visible. (I am using the engine through Wine with linux, I'd doubt that'd affect anything though).
![Screenshot from 2024-05-04 16-00-20](https://github.com/ShadowMario/FNF-PsychEngine/assets/168942458/8aa3f95d-fb3a-4d63-9af0-dfcc58742ffa)

### Command Prompt/Terminal logs (if existing)

Nope, nothing

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, placing the character spritesheet and .xml (mods/ModTemplate/My-Mod/images/characters)

**Comment by JamAxo** [comment]
same issue here, older builds work fine, but anything not made in adobe wont work for some reason in this newer version

**Comment by SilverT4** [comment]
Try going under the animations tab. If you either have the xml open in another window, or already know what animations go to the ones that'll be used in the json, try typing the names in for each animation.

**Comment by Squidd0** [comment]
> Try going under the animations tab. If you either have the xml open in another window, or already know what animations go to the ones that'll be used in the json, try typing the names in for each animation.

From there would I need to use the character editor?

**Comment by Squidd0** [comment]
> Try going under the animations tab. If you either have the xml open in another window, or already know what animations go to the ones that'll be used in the json, try typing the names in for each animation.

I configured all of the animations, disregarding the lack of the character in the editor. I added the .json's name to the character list, and when attempting to use the chart editor, there was still no character in sight. Just a transparent Boyfriend as the opponent.
