### ISSUE TITLE
Songs not loading

### ISSUE THREAD

**Issue by KadePleaseHelpMe** [ShadowMario/FNF-PsychEngine#14602]
### Describe your problem here.

I'm tryna make a mod, and I refuse to use the mods folder (so please don't recommend that because I tried, ok?). Basically, I made a new folder under "songs" and I inserted my Inst and Voices into my song folder (songs/[my song (no name 4u)/Inst 'n Vlcaoksca]). Anyway, I tried loading them and they just kinda wouldn't. So, I found out that they were mp3s. I re-exported them from FL Studio as OGG files. Same result: the song refuses to load inside and outside of the chart editor. I tried overwriting the Tutorial level. Nothing. I'm kinda out of options.
![whatintarnations](https://github.com/ShadowMario/FNF-PsychEngine/assets/89645987/e8d8145d-3f8e-4402-9faa-95d034b85798)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by skdooboomer** [comment]
use the mods folder and it'll work
