### ISSUE TITLE
update on keypressed functions : it just returns keys.pressed.space when i set it to a variable

### ISSUE THREAD

**Issue by DEV-idiotXD** [ShadowMario/FNF-PsychEngine#1460]
### Describe your problem here.

so in https://github.com/ShadowMario/FNF-PsychEngine/issues/1246 @ShadowMario said just to use getPropertyFromClass('flixel.FlxG', 'keys.pressed.space') to select a specific key it just returns keys.pressed.space instead of ytrue of false

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by SrtHero278** [comment]
I think you have to make `space` capital. Like this:
`getPropertyFromClass('flixel.FlxG', 'keys.pressed.SPACE')`

**Comment by DEV-idiotXD** [comment]
### > I think you have to make `space` capital. Like this: `getPropertyFromClass('flixel.FlxG', 'keys.pressed.SPACE')`

thx!
