### ISSUE TITLE
sound issue

### ISSUE THREAD

**Issue by HowToFix12342** [ShadowMario/FNF-PsychEngine#14606]
### Describe your bug here.

i cant here anything when playing pls fix

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by SilverT4** [comment]
by default you can press the + key to increase the game volume. if that doesn't work here's some other things to try:

1. Increase the volume of your computer sound.
2. A bit more complex:
    i. Open the start menu and type `sndvol`. Press enter on the first result.
    ii. Scroll until you find Psych Engine in the list. Drag the slider up to the little line. This will make the application volume match your system volume
3. _Have you tried turning it off and on again?_ Restart your computer.

**Comment by HowToFix12342** [comment]
the sndvol thing work thx so much!
