### ISSUE TITLE
I have problem with source/psychlua/HScript.hx:13: characters 8-11 : Type not found : Tea and source/psychlua/HScript.hx:14: characters 23-30 : Type not found : SScript

### ISSUE THREAD

**Issue by Ricord1** [ShadowMario/FNF-PsychEngine#14618]
### Describe your problem here.

![Снимок экрана (6)](https://github.com/ShadowMario/FNF-PsychEngine/assets/169198749/8aa7900d-7544-43b6-b232-02f66107fea4)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

im edit HScript.hx change CallTea on Tea

**Comment by OMGTVguess** [comment]
how did you fix it
