### ISSUE TITLE
Fnf Weekend 1 Update onto Psych Engine

### ISSUE THREAD

**Issue by Andrew2o0** [ShadowMario/FNF-PsychEngine#14616]
### What feature do you want to get added on the **base** engine?

Add the weekend 1 update and loads of new content to Psych engine, probably a new Freeplay menu from the update, even a new chart editor. take as much time as you want, it's going to be a long ride. (Oh, and please don't upgrade animation editor.) don't believe me? check the itch.io page or newgrounds.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Thing that would not cause problems

**Comment by Meme1079** [comment]
Good News: He'll add the weekend 1 content and maybe the result screen.

Bad News:
<img width="820" alt="Screen Shot 2024-05-07 at 10 17 42 PM" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/101881784/1a8179cc-4038-4c9e-ae07-1ad3751dd1e4">

**Comment by Stefan2008Git** [comment]
> Good News: He'll add the weekend 1 content and maybe the result screen.
> 
> Bad News: <img alt="Screen Shot 2024-05-07 at 10 17 42 PM" width="820" src="https://private-user-images.githubusercontent.com/101881784/328560555-1a8179cc-4038-4c9e-ae07-1ad3751dd1e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMTYyOTIsIm5iZiI6MTcxNTExNTk5MiwicGF0aCI6Ii8xMDE4ODE3ODQvMzI4NTYwNTU1LTFhODE3OWNjLTQwMzgtNGM5ZS1hZTA3LTFhZDM3NTFkZDFlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QyMTA2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWExMjExZTU1ODEzM2JjZTE5ODc0YTk3YzFlZDkzNGM1YjEyOGVlMmRjYjdhMzczMzU3Y2NiZGNlMzc1NWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3wFXLdlMLNDMZT0m6fd946EVDHO1amR9L7Gn2i4mCdQ">

I am already doing weekend 1 port to my modified Psych fork, but with source code method

**Comment by Stefan2008Git** [comment]
Actually, i should wait to Shadow Mario add weekend 1 stuff to game and i will update them
