### ISSUE TITLE
Type not found : SScript

### ISSUE THREAD

**Issue by mochabutter** [ShadowMario/FNF-PsychEngine#14614]
### Describe your problem here.

i dont know whats going on
but everytime i try to compile it gives me that

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

**Comment by coltenthefirst** [comment]
Anymore info that could help?

**Comment by CrusherNotDrip** [comment]
Try setting the version of SScript to `7.7.0`

idk how to do it on Mac but it might be the same

```powershell
haxelib set SScript 7.7.0
```
