### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jamaldequaviusiii** [ShadowMario/FNF-PsychEngine#14619]
### Describe your bug here.

mid fight masses error

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
StoryMenuState.hx (line 321)
StoryMenuState.hx (line 260)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/bazinga/bazinga.json]
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Stefan2008Git** [comment]
You don't have the correct json file name or you are missing it
