### ISSUE TITLE
Mod that crashes when I miss.

### ISSUE THREAD

**Issue by InkScarlet1996** [ShadowMario/FNF-PsychEngine#14611]
### Describe your bug here.

![Capture d’écran 2024-05-05 222432](https://github.com/ShadowMario/FNF-PsychEngine/assets/153747365/c5540711-80a1-4369-83bd-382530cde001)

Every time I miss an arrow, the mod crashes immediately and it's the third mod that does this.

Update:
I usually play with Ghost Tapping disabled and I just enabled it to test and it works even if I miss an arrow.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Stefan2008Git** [comment]
That's a Psych itself

**Comment by Squidd0** [comment]
The new update caused this, for now go back to an older version
