### ISSUE TITLE
Game crashes when i enter a song that has a cutscene script.

### ISSUE THREAD

**Issue by shootingcake** [ShadowMario/FNF-PsychEngine#14612]
### Describe your bug here.

if a song has a cutscene script, it crashes. it only happens on psych 0.7.3.

heres the script:

`function onStartCountdown()`
	`    if not allowEnd and not seenCutscene then`
		`        startVideo('cutscene1');`
		`        allowEnd = true;`
		`        return Function_Stop;`
	`    end`
	`    return Function_Continue;`
`end`

video is in mp4 and 1280x720 resolution

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by shootingcake** [comment]
nvw i figured it out

**Comment by Finny4566** [comment]
can u pls tell me what did you do to solve?

**Comment by shootingcake** [comment]
just changed from 0.7.2 to 0.6.3
