### ISSUE TITLE
Change Character breaks doTweenColor()

### ISSUE THREAD

**Issue by thegreatskep** [ShadowMario/FNF-PsychEngine#14621]
### Describe your bug here.

so i wanted to use a different character for a specific part of a song after changing said character's color, but in doing so, it resets the color of the character. and then when i change the character BACK, the color i set that character to is the same as it was before i changed it. (sorry i cant explain it very well)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope.

**Comment by frantastic24** [comment]
It does not break tweens
Every character you load is a separate object with its own properties
You can tween the character group instead
