### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by AstroV-N** [ShadowMario/FNF-PsychEngine#14627]
### Describe your bug here.

So im tryna play some pibby apocalypse, really fun but it keeps crashing on one part of the song, its really annoying and needs to be fixed 

![YERRRR](https://github.com/ShadowMario/FNF-PsychEngine/assets/169357244/7781a039-f3dd-4fff-a56f-297d92d4f798)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope, its like that when i play a song and it goes at the end

**Comment by CrusherNotDrip** [comment]
That probably has something to do with the mod itself

**Comment by AstroV-N** [comment]
damn, so i cant do anything about it?
