### ISSUE TITLE
im having a problem with compilin psych engine 0.7.3

### ISSUE THREAD

**Issue by gorging937** [ShadowMario/FNF-PsychEngine#14620]
### Describe your problem here.

![hel me ,,](https://github.com/ShadowMario/FNF-PsychEngine/assets/169219294/e1ed9ad9-dd5c-4f35-88a7-dc22cad3d84c)
so, basically ive been following this tutorial: https://www.youtube.com/watch?v=pLDGAYvBjUY&t=38s which was pretty good but im having troubles with the saaaame error over and over, this has happened alot, im pretty sure i do have a good internet connection, otherwise my pc would be tweaking.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i only edited the app icon image things, not much

**Comment by Stefan2008Git** [comment]
Install MSVC from Visual Studio. Ot can be 2019 or 2022 version of it

**Comment by gorging937** [comment]
> Install MSVC from Visual Studio. Ot can be 2019 or 2022 version of it

ill try this and see if it works

**Comment by gorging937** [comment]
> Install MSVC from Visual Studio. It can be 2019 or 2022 version of it

yeah, but where can i install it, is it just from the components of the installer or is it seperate? (im on 2019 btw)

**Comment by Stefan2008Git** [comment]
> > Install MSVC from Visual Studio. It can be 2019 or 2022 version of it
> 
> yeah, but where can i install it, is it just from the components of the installer or is it seperate? (im on 2019 btw) plus theres like a bunch of msvc components and idk which one it is exactly

You need to select MSVC and Windows SDK. These two components are definitely needed for HaxeFlixel building and compiling to get it working or else without them it will not gonna work

**Comment by gorging937** [comment]
> > > Install MSVC from Visual Studio. It can be 2019 or 2022 version of it
> > 
> > 
> > yeah, but where can i install it, is it just from the components of the installer or is it seperate? (im on 2019 btw) plus theres like a bunch of msvc components and idk which one it is exactly
> 
> You need to select MSVC and Windows SDK. These two components are definitely needed for HaxeFlixel building and compiling to get it working or else without them it will not gonna work

thanks alot man, i finally got it working, apparently it was because i didint select msvc build tools lool

**Comment by Stefan2008Git** [comment]
> > > > Install MSVC from Visual Studio. It can be 2019 or 2022 version of it
> > > 
> > > 
> > > yeah, but where can i install it, is it just from the components of the installer or is it seperate? (im on 2019 btw) plus theres like a bunch of msvc components and idk which one it is exactly
> > 
> > 
> > You need to select MSVC and Windows SDK. These two components are definitely needed for HaxeFlixel building and compiling to get it working or else without them it will not gonna work
> 
> thanks alot man, i finally got it working, apparently it was because i didint select msvc build tools lool

Yw. I hope i helped
