### ISSUE TITLE
How to tween/lerp a number in source code

### ISSUE THREAD

**Issue by FrancescosToon** [ShadowMario/FNF-PsychEngine#14629]
### Describe your problem here.

So I'm trying to code a custom result screen in source code (v 0.6.3) and I want to make the score number go from 0 to its intended value while showing the result to the player.

I've tried using the built in number tween function:

FlxTween.num(0, songScore, 2, {ease: FlxEase.quartInOut, startDelay: 1}, updateScore);

function updateScore(v:Float){
        scoreText.text += Highscore.floorDecimal(v, 0);
}

But all it does is display a bunch of zeros as the end result and I've no idea what went wrong
![____HELP](https://github.com/ShadowMario/FNF-PsychEngine/assets/106826854/ad26c4ed-2912-4590-975c-a6a004dee97a)

Ps: the songScore number given to the tween is correct, I've tested before

I've also tried doing easy methods like score = score + 1 but it didn't work and just lagged the game after 2 seconds...

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I've edited PlayState & added a new ResultsState

**Comment by FrancescosToon** [comment]
To calrify, I want the text to do the same thing it does in the freeplay score, but I'm failing to figure out what actually happens with it

**Comment by CrusherNotDrip** [comment]
Fun Fact: They actually lerp the score in FreeplayState
the only things tweened in there is the BG Color and the volume upon exiting if a different song was being played before hand

**Comment by FrancescosToon** [comment]
I have tried copying the lerp method... still shows me ridiculos numbers
