### ISSUE TITLE
How to despawn loaded notes

### ISSUE THREAD

**Issue by GMan2006i** [ShadowMario/FNF-PsychEngine#14624]
### Describe your problem here.

From both unspawnNotes group and the Notes group. Is there a way to unload them during a song?

Current remedy is to hide them and make them ignore notes but it’s not super effective unfortunately 

also I’m using 0.6.3 btw

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
0.6.3 is not supported anymore since December 2023
