### ISSUE TITLE
how can i fix this 

### ISSUE THREAD

**Issue by thegamenig** [ShadowMario/FNF-PsychEngine#14632]
source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall

btw it psych engine 0.7.2

[x] Windows
[ ] Linux
[ ] Mac

**Comment by aziznahali01** [comment]
I learned from someone else that you are supposed to change anything called TeaCall to just Tea (source/psychlua/HScript.hx). it worked for me but i am having a little bit of issues with the engine so be careful.

**Comment by YouDevsYoupikmin** [comment]
You need SSCript 7.7.0

**Comment by thegamenig** [comment]
i got another error 

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/142361218/9c34eb5d-85d2-4130-9a56-2e10d5fa57ad)

**Comment by YouDevsYoupikmin** [comment]
Why you reopened it?

**Comment by YouDevsYoupikmin** [comment]
If you still have a problem try SScript 20.8.618

**Comment by thegamenig** [comment]
don't work

**Comment by YouDevsYoupikmin** [comment]
try with
haxelib install SScript 8.1.6
or

haxelib install SScript 10.0.618

**Comment by thegamenig** [comment]
don't work

**Comment by YouDevsYoupikmin** [comment]
Disable temporary sscript on project.xml, maybe it's gonna be fixed..

**Comment by thegamenig** [comment]
i don't see the temporary sscript on the project.xml

**Comment by YouDevsYoupikmin** [comment]
try delete 	
<define name="HSCRIPT_ALLOWED" if="desktop" />

**Comment by YouDevsYoupikmin** [comment]
try delete 	<define name="HSCRIPT_ALLOWED" if="desktop" />  on project.xml
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/132922421/493bc498-8c1f-48d1-a279-1afab26c2ea2)

**Comment by thegamenig** [comment]
i got source/states/PlayState.hx:418: characters 6-17 : Unknown identifier : initHScript
source/states/PlayState.hx:603: characters 6-17 : Unknown identifier : initHScrip

**Comment by YouDevsYoupikmin** [comment]
or try compile a new build with sscript 7.7.0 it works for me soo idk

**Comment by thegamenig** [comment]
don't work
