### ISSUE TITLE
How to make just an image in Story Mode

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#14630]
### Describe your problem here.

I would like to make an image so that it appears in Story Mode
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/114620759/ba4c954f-6726-412d-8ed0-a78b3ee9d55d)
There

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

A little, and I’m also learning to code, sorry for the many questions

**Comment by M4st3rG4m4** [comment]
Can you explain to me what you mean by an image appearing?

**Comment by MaksPRO12667** [comment]
> Can you explain to me what you mean by an image appearing?

I want the image to be displayed in Story Mode. I don't know the code well, that's why I ask this question

**Comment by M4st3rG4m4** [comment]
> I want the image to be displayed in Story Mode. I don't know the code well, that's why I ask this question

Okay I understand that, but do you want it to appear on a specific song or on all of them?

**Comment by MaksPRO12667** [comment]
> > I want the image to be displayed in Story Mode. I don't know the code well, that's why I ask this question
> 
> Okay I understand that, but do you want it to appear on a specific song or on all of them?

![NotepadSelecter](https://github.com/ShadowMario/FNF-PsychEngine/assets/114620759/f9f73299-44c3-4b9a-a53c-85b9b36bb567)

I want to do it like this. I need the names of the songs to be at the top of the notebook, and the week sheet at the bottom

**Comment by MaksPRO12667** [comment]
> > > I want the image to be displayed in Story Mode. I don't know the code well, that's why I ask this question
> > 
> > 
> > Okay I understand that, but do you want it to appear on a specific song or on all of them?
> 
> ![NotepadSelecter](https://private-user-images.githubusercontent.com/114620759/331209547-f9f73299-44c3-4b9a-a53c-85b9b36bb567.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5Njg5NTQsIm5iZiI6MTcxNTk2ODY1NCwicGF0aCI6Ii8xMTQ2MjA3NTkvMzMxMjA5NTQ3LWY5ZjczMjk5LTQ0YzMtNGI5YS1hNTNjLTg1YjliMzZiYjU2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxNzU3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjkxNTljN2VlNGNhN2RhZDRkZDU0Y2E0MWFkYmVlZDcyMTcxNzI3NmMxYzMzZGE3MDg1N2NkZmUyZmFkYjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.doCyfLRJlSRIXFFmzl1ZE8jJoUXXwmTkNM9KqQyjvzE)
> 
> I want to do it like this. I need the names of the songs to be at the top of the notebook, and the week sheet at the bottom
> 
> I want this to be the background for a list of weeks, something like that

![32935афафыыф](https://github.com/ShadowMario/FNF-PsychEngine/assets/114620759/1a560588-7622-429d-b6e4-55476935e656)
like this (montage)

**Comment by M4st3rG4m4** [comment]
Unfortunately, I'm not very good at HaxeFlixel to help you do that, since the only way to do what you want is from the Source.

Seriously, excuse me.

**Comment by MaksPRO12667** [comment]
> Unfortunately, I'm not very good at HaxeFlixel to help you do that, since the only way to do what you want is from the Source.
> 
> Seriously, excuse me.

It's okay, no need to apologize!
