### ISSUE TITLE
Botplay stuck on

### ISSUE THREAD

**Issue by mahikotahi** [ShadowMario/FNF-PsychEngine#14638]
### Describe your bug here.

i keep opening my psych engine and botplay in stuck enabled

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by u0-a63** [comment]
Try deleting the AppData folder. It should be something like %APPDATA%\ShadowMario.
