### ISSUE TITLE
Help me plees! I am lerning to porting / modding, but my skills (and english) bad.

### ISSUE THREAD

**Issue by Recsill** [ShadowMario/FNF-PsychEngine#14634]
### Describe your problem here.

I am trying to port Silly Billy to Psych Engin. At the moment when Billy turns from a small version back into a big one, my game gives me a error:

states/PlayState.hx (line 2190)
states/PlayState.hx (line 1962)
states/PlayState.hx (line 1791)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

i dont know, how fix that. Plees help me.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I am trying to port Silly Billy to Psych Engin.

**Comment by YouDevsYoupikmin** [comment]
Did you used a event for this song or smth else?

**Comment by M4st3rG4m4** [comment]
As I see the problem is an event in the chart, also, can you tell me what language you speak?

**Comment by Recsill** [comment]
Я говорю на русском языке :)

**Comment by M4st3rG4m4** [comment]
> Я говорю на русском языке :)

Хорошо, давайте лучше поговорим на английском (я написал это с помощью Google Translate, извините, если есть ошибки xD)

**Comment by M4st3rG4m4** [comment]
Hey, a question that just came to mind:

By any chance you didn't copy and paste the original chart into Psych Engine did you?

**Comment by Recsill** [comment]
> Привет, вопрос, который только что пришел на ум:
> 
> Вы случайно не скопировали и не вставили исходную диаграмму в Psych Engine?

Отвечаю: да, я так и поступил. Проблема в этом?

**Comment by M4st3rG4m4** [comment]
Ну правда получается, что если взять график с другого движка такое обычно и происходит, дело не в том, что Psych Engine не умеет читать графики, на самом деле вы сами видели, что они работают, но, по своему опыту Я могу вам сказать, что двигатели Most читают диаграммы очень похожим образом, но с другими переменными; Имея разные переменные, Psych Engine не знает, как их читать.

**Comment by M4st3rG4m4** [comment]
На самом деле, впервые это случилось со мной, когда я портировал Lullaby v2 от Hypno и понятия не имел, как работают диаграммы, поэтому я просто скопировал и вставил их и попытался открыть. Ну, некоторые из них запустились. и разбился на полпути, а другие разбились при запуске или просто разбили двигатель.

**Comment by M4st3rG4m4** [comment]
Мое решение такое, плохо то, что это раздражает:

Воссоздайте диаграммы, но не используйте исходные диаграммы в качестве основы, поскольку Psych Engine, не зная этих переменных, не показывает их в редакторе диаграмм, и они видны только в формате JSON.

**Comment by Recsill** [comment]
> Мое решение такое, плохо то, что это раздражает:
> 
> Воссоздайте диаграммы, но не используйте исходные диаграммы в качестве основы, поскольку Psych Engine, не зная этих переменных, не показывает их в редакторе диаграмм, и они видны только в формате JSON.

Спасибо огромное! Я обязательно воспользуюсь вашим советом.

**Comment by M4st3rG4m4** [comment]
Спасибо огромное! Я обязательно воспользуюсь вашим советом.

**Comment by M4st3rG4m4** [comment]
Не нужно благодарить, сделайте тест и сообщите, если вам нужно что-то еще
