### ISSUE TITLE
i got a source compiling error again

### ISSUE THREAD

**Issue by MaximumX64** [ShadowMario/FNF-PsychEngine#14633]
### Describe your problem here.

i want to just compile the source code for android and i got this
![help](https://github.com/ShadowMario/FNF-PsychEngine/assets/167785527/24ce35bc-9058-4d80-a63c-89f1afd95365)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, but only for that teacall error

**Comment by MaximumX64** [comment]
plz help

**Comment by Stefan2008Git** [comment]
You are missing the class on your source code

**Comment by MaximumX64** [comment]
what class?

**Comment by MaximumX64** [comment]
i don't understand

**Comment by Stefan2008Git** [comment]
> what class?

You are missing the Context.hx on your source code or you didn't installed the library for Android simply

**Comment by MaximumX64** [comment]
thanks, but where do i have to put context.hx

**Comment by MaximumX64** [comment]
and where to install it

**Comment by MaximumX64** [comment]
oh nevermind
