### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Qwertcool54** [ShadowMario/FNF-PsychEngine#14641]
### Describe your bug here.

when i tryed compile psychengine i got this error

### Command Prompt/Terminal logs (if existing)

```bash
source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Late-Is-Cool** [comment]
find and replace all instances of TeaCall to Tea in HScript.hx

**Comment by Qwertcool54** [comment]
> find and replace all instances of TeaCall to Tea in HScript.hx

thank, there fixes
