### ISSUE TITLE
character custom event

### ISSUE THREAD

**Issue by PreachVoid** [ShadowMario/FNF-PsychEngine#14640]
### Describe your problem here.

How to make a custom event that make the 3rd character and sing(bf team)?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by M4st3rG4m4** [comment]
Does your song have a Girlfriend?

**Comment by PreachVoid** [comment]
> Does your song have a Girlfriend?

yes

**Comment by M4st3rG4m4** [comment]
Forget what I said, it's just that I got the issue confused.

**Comment by M4st3rG4m4** [comment]
Unfortunately, I'm not very good at HaxeFlixel to help you do that, since the only way to do what you want is from the Source.


Seriously, excuse me.

**Comment by M4st3rG4m4** [comment]
Forget what I said, it's just that I got the issue confused.

**Comment by M4st3rG4m4** [comment]
The only way I know to do this without modifying the Source is to create a custom noteType and add the notes of the third character to the chart as that noteType and then create a script that adds that character as part of the background, the only bad thing is that the part of the chart and/or creation of the script for the character is somewhat annoying, but the good thing is that apart from the fact that it does not ask much of the hardware, if you specified the noteType it will only sing when you press those notes.

P.D: Sorry for my bad English.

**Comment by M4st3rG4m4** [comment]
To make your work easier, here is a script for Custom NoteType (Psych Engine v0.7.3):

function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'PlayerTeammate' then --Check if the note on the chart is a Bullet Note
			--setPropertyFromGroup('unspawnNotes', i, 'texture', 'notetexture'); --Change notetexture
			--setPropertyFromGroup('unspawnNotes', i, 'noteSplashHue', 0);
			--setPropertyFromGroup('unspawnNotes', i, 'noteSplashSat', -20);
			--setPropertyFromGroup('unspawnNotes', i, 'noteSplashBrt', 1);

			setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true); --[[make it so original character doesn't sing these notes, if you want to BF or original character sing these notes too set it false]]

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true); --Miss has penalties
			end
		end
	end
end

**Comment by M4st3rG4m4** [comment]
place that script in "Mods/Custom_NoteTypes" and then go to the Chart Editor and add that Custom Note in the sections that the third character sings

**Comment by M4st3rG4m4** [comment]
Here I leave you a script for the third character:

-- script base by ItsCapp (modded by Gama for PE v0.7.3)
----------------------------- Char Offsets -----------------------------
--These appear on the side in the Character Editor
--or in the character's JSON (if it exists)
idleoffsets = {'0', '0'} -- Normally the idle offsets are 0
leftoffsets = {'0', '0'}
downoffsets = {'0', '0'}
upoffsets = {'0', '0'}
rightoffsets = {'0', '0'}

missleftoffsets = {'50', '0'}
missdownoffsets = {'-0', '0'}
missupoffsets = {'10', '50'}
missrightoffsets = {'-50', '0'}

----------------------------- Char Anim Names -----------------------------
-- change all of these to the name of the animation in your character's xml file
idle_xml_name = 'Teammate_Idle'
left_xml_name = 'Teammate_Left'
down_xml_name = 'Teammate_Down'
up_xml_name = 'Teammate_Up'
right_xml_name = 'Teammate_Right'

left_miss_xml_name = 'Teammate_LeftMiss'
down_miss_xml_name = 'Teammate_DownMiss
up_miss_xml_name = 'Teammate_UpMiss'
right_miss_xml_name = 'Teammate_RightMiss'

----------------------------- Char Pos -----------------------------
-- basically horizontal and vertical positions
x_position = 0
y_position = 0

----------------------------- Char Size -----------------------------
-- scales your character (set to 1 by default)
xScale = 1
yScale = 1

----------------------------- Char Visibility -----------------------------
-- invisible character (so basically if you wanna use the change character event, you need to make the second character invisible first)
invisible = false

----------------------------- Char Assets -----------------------------
-- pretty self-explanitory
name_of_character_xml = 'Teammate_Assets'
name_of_character = 'teammate'
name_of_notetype = 'PlayerTeammate'
name_of_notetype2 = 'PlayerAndTeammate'

----------------------------- Char Behind -----------------------------
-- if it's set to true the character appears behind the default characters, including gf, watch out for that
foreground = false

----------------------------- Char Face Pos -----------------------------
playablecharacter = false -- change to 'true' if you want to flipX

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

doIdle = true

function onCreate()
	makeAnimatedLuaSprite(name_of_character, 'characters/Teammates/' .. name_of_character_xml, x_position, y_position);
	addAnimationByPrefix(name_of_character, 'idle', idle_xml_name, 24, false);
	addAnimationByPrefix(name_of_character, 'singLEFT', left_xml_name, 24, false);
	addAnimationByPrefix(name_of_character, 'singDOWN', down_xml_name, 24, false);
	addAnimationByPrefix(name_of_character, 'singUP', up_xml_name, 24, false);
	addAnimationByPrefix(name_of_character, 'singRIGHT', right_xml_name, 24, false);

	addAnimationByPrefix(name_of_character, 'singLEFTmiss', left_miss_xml_name, 24, false);
    addAnimationByPrefix(name_of_character, 'singDOWNmiss', down_miss_xml_name, 24, false);
    addAnimationByPrefix(name_of_character, 'singUPmiss', up_miss_xml_name, 24, false);
    addAnimationByPrefix(name_of_character, 'singRIGHTmiss', right_miss_xml_name, 24, false);

----------------------------- Char Force Antialiasing -----------------------------
	setProperty(name_of_character .. '.antialiasing', false);
----------------------------------------------------------------------------------
	if playablecharacter == true then
		setPropertyLuaSprite(name_of_character, 'flipX', true);
	else
		setPropertyLuaSprite(name_of_character, 'flipX', false);
	end

	scaleObject(name_of_character, xScale, yScale);


	playAnim(name_of_character, 'idle');
	addLuaSprite(name_of_character, foreground);

	if invisible == true then
		setPropertyLuaSprite(name_of_character, 'alpha', 0)
	end
end

-- I know this is messy, but it's the only way I know to make it work on both sides.
local singAnims = {"singLEFT", "singDOWN", "singUP", "singRIGHT"}
function goodNoteHit(id, direction, noteType, isSustainNote)
	if noteType == name_of_notetype or noteType == name_of_notetype2 then
		doIdle = false
		playAnim(name_of_character, singAnims[direction + 1], true);

		if direction == 0 then
			setProperty(name_of_character .. '.offset.x', leftoffsets[1]);
			setProperty(name_of_character .. '.offset.y', leftoffsets[2]);
		elseif direction == 1 then
			setProperty(name_of_character .. '.offset.x', downoffsets[1]);
			setProperty(name_of_character .. '.offset.y', downoffsets[2]);
		elseif direction == 2 then
			setProperty(name_of_character .. '.offset.x', upoffsets[1]);
			setProperty(name_of_character .. '.offset.y', upoffsets[2]);
		elseif direction == 3 then
			setProperty(name_of_character .. '.offset.x', rightoffsets[1]);
			setProperty(name_of_character .. '.offset.y', rightoffsets[2]);
		end
	end
    end
end

local missAnims = {"singLEFTmiss", "singDOWNmiss", "singUPmiss", "singRIGHTmiss"}
function noteMiss(id, direction, noteType, isSustainNote)
    if noteType == name_of_notetype or noteType == name_of_notetype2 then
        doIdle = false
        playAnim(name_of_character, missAnims[direction + 1], true);
        if direction == 0 then
            setProperty(name_of_character .. '.offset.x', leftMissoffsets[1]);
            setProperty(name_of_character .. '.offset.y', leftMissoffsets[2]);
            if isSustainNote then
                playAnim(name_of_character, missAnims[direction + 1], true);
            end
        elseif direction == 1 then
            setProperty(name_of_character .. '.offset.x', downMissoffsets[1]);
            setProperty(name_of_character .. '.offset.y', downMissoffsets[2]);
            if isSustainNote then
                playAnim(name_of_characterMissigno, missAnims[direction + 1], true);
            end
        elseif direction == 2 then
            setProperty(name_of_character .. '.offset.x', upMissoffsets[1]);
            setProperty(name_of_character .. '.offset.y', upMissoffsets[2]);
            if isSustainNote then
                playAnim(name_of_character, missAnims[direction + 1], true);
            end
        elseif direction == 3 then
            setProperty(name_of_character .. '.offset.x', rightMissoffsets[1]);
            setProperty(name_of_character .. '.offset.y', rightMissoffsets[2]);
            if isSustainNote then
                playAnim(name_of_character, missAnims[direction + 1], true);
            end
        end
    end
end

function onBeatHit()
	-- triggered 4 times per section
	if curBeat % 2 == 0  and doIdle then
		playAnim(name_of_character, 'idle');
		setProperty(name_of_character .. '.offset.x', idleoffsets[1]);
		setProperty(name_of_character .. '.offset.y', idleoffsets[2]);
	end
	doIdle = true
end

**Comment by M4st3rG4m4** [comment]
Here I leave you a script for the third character:

-- script base by ItsCapp (modded by M4st3rG4m4 for PE v0.7.3)
----------------------------- Char Offsets -----------------------------
--These appear on the side in the Character Editor
--or in the character's JSON (if it exists)
idleoffsets = {'0', '0'} -- Normally the idle offsets are 0
leftoffsets = {'0', '0'}
downoffsets = {'0', '0'}
upoffsets = {'0', '0'}
rightoffsets = {'0', '0'}

missleftoffsets = {'50', '0'}
missdownoffsets = {'-0', '0'}
missupoffsets = {'10', '50'}
missrightoffsets = {'-50', '0'}

----------------------------- Char Anim Names -----------------------------
-- change all of these to the name of the animation in your character's xml file
idle_xml_name = 'Teammate_Idle'
left_xml_name = 'Teammate_Left'
down_xml_name = 'Teammate_Down'
up_xml_name = 'Teammate_Up'
right_xml_name = 'Teammate_Right'

left_miss_xml_name = 'Teammate_LeftMiss'
down_miss_xml_name = 'Teammate_DownMiss'
up_miss_xml_name = 'Teammate_UpMiss'
right_miss_xml_name = 'Teammate_RightMiss'

----------------------------- Char Pos -----------------------------
-- basically horizontal and vertical positions
x_position = 0
y_position = 0

----------------------------- Char Size -----------------------------
-- scales your character (set to 1 by default)
xScale = 1
yScale = 1

----------------------------- Char Visibility -----------------------------
-- invisible character (so basically if you wanna use the change character event, you need to make the second character invisible first)
invisible = false

----------------------------- Char Assets -----------------------------
-- pretty self-explanitory
name_of_character_xml = 'Teammate_Assets'
name_of_character = 'teammate'
name_of_notetype = 'PlayerTeammate'
name_of_notetype2 = 'PlayerAndTeammate'

----------------------------- Char Behind -----------------------------
-- if it's set to true the character appears behind the default characters, including gf, watch out for that
foreground = false

----------------------------- Char Face Pos -----------------------------
playablecharacter = false -- change to 'true' if you want to flipX

doIdle = true

function onCreate()
	makeAnimatedLuaSprite(name_of_character, 'characters/Teammates/' .. name_of_character_xml, x_position, y_position);
	addAnimationByPrefix(name_of_character, 'idle', idle_xml_name, 24, false);
	addAnimationByPrefix(name_of_character, 'singLEFT', left_xml_name, 24, false);
	addAnimationByPrefix(name_of_character, 'singDOWN', down_xml_name, 24, false);
	addAnimationByPrefix(name_of_character, 'singUP', up_xml_name, 24, false);
	addAnimationByPrefix(name_of_character, 'singRIGHT', right_xml_name, 24, false);

	addAnimationByPrefix(name_of_character, 'singLEFTmiss', left_miss_xml_name, 24, false);
	addAnimationByPrefix(name_of_character, 'singDOWNmiss', down_miss_xml_name, 24, false);
	addAnimationByPrefix(name_of_character, 'singUPmiss', up_miss_xml_name, 24, false);
	addAnimationByPrefix(name_of_character, 'singRIGHTmiss', right_miss_xml_name, 24, false);

----------------------------- Char Force Antialiasing -----------------------------
	--setProperty(name_of_character .. '.antialiasing', false);
-----------------------------------------------------------------------------------

	if playablecharacter == true then
		setPropertyLuaSprite(name_of_character, 'flipX', true);
	else
		setPropertyLuaSprite(name_of_character, 'flipX', false);
	end

	scaleObject(name_of_character, xScale, yScale);


	playAnim(name_of_character, 'idle');
	addLuaSprite(name_of_character, foreground);

	if invisible == true then
		setPropertyLuaSprite(name_of_character, 'alpha', 0)
	end

end

-- I know this is messy, but it's the only way I know to make it work on both sides.
local singAnims = {"singLEFT", "singDOWN", "singUP", "singRIGHT"}

function goodNoteHit(id, direction, noteType, isSustainNote)
	if noteType == name_of_notetype or noteType == name_of_notetype2 then
		doIdle = false
		playAnim(name_of_character, singAnims[direction + 1], true);

		if direction == 0 then
			setProperty(name_of_character .. '.offset.x', leftoffsets[1]);
			setProperty(name_of_character .. '.offset.y', leftoffsets[2]);
		elseif direction == 1 then
			setProperty(name_of_character .. '.offset.x', downoffsets[1]);
			setProperty(name_of_character .. '.offset.y', downoffsets[2]);
		elseif direction == 2 then
			setProperty(name_of_character .. '.offset.x', upoffsets[1]);
			setProperty(name_of_character .. '.offset.y', upoffsets[2]);
		elseif direction == 3 then
			setProperty(name_of_character .. '.offset.x', rightoffsets[1]);
			setProperty(name_of_character .. '.offset.y', rightoffsets[2]);
		end
	end
end

local missAnims = {"singLEFTmiss", "singDOWNmiss", "singUPmiss", "singRIGHTmiss"}

function noteMiss(id, direction, noteType, isSustainNote)
	if noteType == name_of_notetype or noteType == name_of_notetype2 then
		doIdle = false
		playAnim(name_of_character, missAnims[direction + 1], true);
		if direction == 0 then
			setProperty(name_of_character .. '.offset.x', leftMissoffsets[1]);
			setProperty(name_of_character .. '.offset.y', leftMissoffsets[2]);
			if isSustainNote then
				playAnim(name_of_character, missAnims[direction + 1], true);
			end
		elseif direction == 1 then
			setProperty(name_of_character .. '.offset.x', downMissoffsets[1]);
			setProperty(name_of_character .. '.offset.y', downMissoffsets[2]);
			if isSustainNote then
				playAnim(name_of_characterMissigno, missAnims[direction + 1], true);
			end
		elseif direction == 2 then
			setProperty(name_of_character .. '.offset.x', upMissoffsets[1]);
			setProperty(name_of_character .. '.offset.y', upMissoffsets[2]);
			if isSustainNote then
				playAnim(name_of_character, missAnims[direction + 1], true);
			end
		elseif direction == 3 then
			setProperty(name_of_character .. '.offset.x', rightMissoffsets[1]);
			setProperty(name_of_character .. '.offset.y', rightMissoffsets[2]);
			if isSustainNote then
				playAnim(name_of_character, missAnims[direction + 1], true);
			end
		end
	end
end

function onBeatHit()
-- triggered 4 times per section
	if curBeat % 2 == 0 and doIdle then
		playAnim(name_of_character, 'idle');
		setProperty(name_of_character .. '.offset.x', idleoffsets[1]);
		setProperty(name_of_character .. '.offset.y', idleoffsets[2]);
	end
	doIdle = true
end

**Comment by M4st3rG4m4** [comment]
Follow the instructions that I left you there, the only thing you must change afterwards is in the line after function onCreate() and that is that after name_of_character you must change that location to the png and xml of your character; Also, a few lines below is the Force Antialiasing section which if you want to force it, just uncomment and set true, and if you want to force it without antialiasing, set false.

**Comment by M4st3rG4m4** [comment]
please let me know when you read
