### ISSUE TITLE
ModsMenuState.hx errors in the lastest version of PsychEngine

### ISSUE THREAD

**Issue by NS-Unfair** [ShadowMario/FNF-PsychEngine#1464]
### Describe your bug here.

Basically, while I was trying to update my pull request. I added my changes to the charting editor. Then I got four errors in a file I didn't make changes to. So I reverted all of my changes and tried building the game. I still got the same for errors.

### Command Prompt/Terminal logs (if existing)

```bash
source/ModsMenuState.hx:388: characters 6-28 : {+ length : Int } should be String
source/ModsMenuState.hx:392: characters 6-42 : {+ length : Int } should be String
source/ModsMenuState.hx:396: characters 36-47 : Array access is not allowed on {+ length : Int }
source/ModsMenuState.hx:396: characters 36-47 : For function argument 'Red'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I have made no changes to the build. If the changes I reverted count, then yes

**Comment by HiroOfc** [comment]
check #1419

**Comment by NS-Unfair** [comment]
I guess I have to wait to make my pull request

**Comment by NS-Unfair** [comment]
I'm closing this issue
