### ISSUE TITLE
custom notes bug

### ISSUE THREAD

**Issue by ximingindehong** [ShadowMario/FNF-PsychEngine#14645]
### Describe your bug here.

When I put a custom note lua into mod file, and run 0.7.3 engine. The custom note that I made will turn into a color that the note was set. For example, normal down note is in a bluish color, my custom note is in a bluish color too, which it should not. When I put this custom note into 0.6.3 psych engine, it worked properly with no strange color stuff. So it must be some problems during updating the engine. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by HourOfEternity** [comment]
It's not a bug, you need to turn off rgb shader for your custom notes.

**Comment by ShadowMario** [comment]
You have to set the note's `rgbShader.enabled` property to false
