### ISSUE TITLE
I had this problem for a long time can somebody help pls.

### ISSUE THREAD

**Issue by CoxGitX** [ShadowMario/FNF-PsychEngine#14642]
### Describe your problem here.

C:/haxelib/discord_rpc/git/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/haxelib/flixel-addons/3,0,2/flixel/addons/transition/FlxTransitionSprite.hx:135: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/haxelib/flixel-addons/3,0,2/flixel/addons/transition/TransitionData.hx:11: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/haxelib/flixel-addons/3,0,2/flixel/addons/transition/FlxTransitionableState.hx:81: lines 81-90 : Warning : switchTo is deprecated, use startOutro
source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : (WDeprecated) flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : (WDeprecated) flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : (WDeprecated) flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
C:/haxelib/flixel/5,5,0/flixel/animation/FlxAnimation.hx:239: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
source/PlayState.hx:74: characters 8-22 : Type not found : vlc.MP4Handler
source/flixel/system/FlxSound.hx:597: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/system/FlxSound.hx:601: characters 19-27 : flash.media.SoundChannel has no field __source
source/FreeplayState.hx:494: characters 26-32 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:494: characters 26-32 : ... For function argument 'basic'
source/PauseSubState.hx:75: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:75: characters 23-33 : ... For function argument 'basic'
source/DialogueBox.hx:144: characters 26-72 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/haxelib/flixel-addons/3,0,2/flixel/addons/text/FlxTypeText.hx:545: characters 3-44 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/PlayState.hx:662: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:662: characters 25-35 : ... For function argument 'basic'
source/PlayState.hx:1861: characters 13-23 : Type not found : MP4Handler
source/FunkinLua.hx:2389: lines 2389-2392 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2389: lines 2389-2392 : ... For function argument 'value'
source/PlayState.hx:2718: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2718: characters 23-29 : ... For function argument 'basic'
source/PlayState.hx:2719: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2719: characters 23-83 : ... For function argument 'basic'
source/PlayState.hx:2081: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2081: characters 25-37 : ... For function argument 'basic'
source/PlayState.hx:2128: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2128: characters 25-34 : ... For function argument 'basic'
source/PlayState.hx:2199: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2199: characters 25-36 : ... For function argument 'basic'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : (WDeprecated) flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1556: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1556: characters 24-30 : ... For function argument 'basic'
source/editors/ChartingState.hx:2419: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/haxelib/flixel/5,5,0/flixel/ui/FlxButton.hx:259: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
source/TitleState.hx:801: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:803: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:807: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/haxelib/flixel/5,5,0/flixel/graphics/FlxGraphic.hx:15: characters 8-32 : Type not found : openfl.display.Tilesheet
C:/haxelib/flixel/5,5,0/flixel/graphics/tile/FlxDrawBaseItem.hx:9: characters 8-32 : Type not found : openfl.display.Tilesheet
C:/haxelib/flixel/5,5,0/flixel/graphics/tile/FlxDrawTilesItem.hx:10: characters 8-32 : Type not found : openfl.display.Tilesheet
source/Paths.hx:24: characters 8-25 : You cannot access the flash package while in a macro (for flash.media.Sound)
C:\Users\PC\Downloads\FNF-ScrewedEngine-0.1.0\source\import.hx:1: characters 8-13 : ... referenced here
C:/haxelib/lime/8,1,2/src/lime/media/AudioSource.hx:138: characters 53-100 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/media/Sound.hx:23: characters 8-30 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/utils/Assets.hx:9: characters 8-26 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/text/_internal/TextEngine.hx:10: characters 8-24 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/display/_internal/CairoTextField.hx:4: characters 8-40 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/display/_internal/CairoGraphics.hx:7: characters 8-36 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/display/_internal/Context3DGraphics.hx:4: characters 8-46 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/filters/BitmapFilter.hx:6: characters 8-44 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/display/BitmapData.hx:14: characters 8-35 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/desktop/Icon.hx:4: characters 8-33 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/filesystem/File.hx:6: characters 8-27 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/events/InvokeEvent.hx:5: characters 8-30 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/display/Application.hx:15: characters 8-33 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/utils/_internal/Lib.hx:6: characters 8-34 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/display/DisplayObject.hx:6: characters 8-34 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
C:/haxelib/openfl/9,3,3/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
C:/haxelib/lime/8,1,2/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
C:/haxelib/lime/8,1,2/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
C:/haxelib/lime/8,1,2/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
C:/haxelib/lime/8,1,2/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
C:/haxelib/lime/8,1,2/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
C:/haxelib/lime/8,1,2/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
C:/haxelib/lime/8,1,2/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
C:/haxelib/lime/8,1,2/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
C:/haxelib/lime/8,1,2/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
C:/haxelib/lime/8,1,2/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
C:/haxelib/lime/8,1,2/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
C:/haxelib/lime/8,1,2/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here

I have everything installed, its with every engine, do i not have smth installed or some?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by M4st3rG4m4** [comment]
first of all wtf, second what are you trying to do exactly to give you such an error, if it weren't so long I would review the source code myself to help you but something like that...
