### ISSUE TITLE
Bug!

### ISSUE THREAD

**Issue by SnowerHDrar** [ShadowMario/FNF-PsychEngine#14649]
### Describe your bug here.

When i was playing my chart, the game crashed and this appeared (Sorry for my bad english, i'm brazillian)

### Command Prompt/Terminal logs (if existing)

```bash
objects/Note.hx (line 464)
states/PlayState.hx (line 1758)
flixel/group/FlxGroup.hx (line 787)
states/PlayState.hx (line 1752)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes

**Comment by Limey123** [comment]
If you used custom note types in your chart, make sure the file is still present, or replace the note with a default one. Not sure what changes were made since you didn't specify so I'm not sure if that is your issue or not.
