### ISSUE TITLE
How do I change the game over music? (I am not trying to make a mod, I just want to change the game over music)

### ISSUE THREAD

**Issue by u0-a63** [ShadowMario/FNF-PsychEngine#14657]
### Describe your problem here.

I want to change the game over music, instead of it being the default. How do I do this?

My OS is Windows 10, so don't ask what my OS is.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just want to change the game over music.

**Comment by HourOfEternity** [comment]
You just need to go to the Data tab in the chart editor, and change the Game Over Loop Music to your music.

**Comment by M4st3rG4m4** [comment]
If what you want is to change the Game Over music for all the songs you can do two things:

1 - This solution is very shitty but if you want to do it effort lessly you can go to the "Mods/Music/" folder and there change the "GameOver.ogg" for another music, but remember that the format must be ogg and that this is a Loop.

2 - This option is more professional but varies from the version of Psych Engine you use, it involves creating a script that contains the following:

*For Psych Engine 0.7.x*

function onCreate()
setPropertyFromClass('substates.GameOverSubstate', 'loopSoundName', 'GameOverCustomMusic'); --put in mods/music/
end

*For Psych Engine 0.6.3*

function onCreate()
setPropertyFromClass('GameOverSubstate', 'loopSoundName', 'GameOverCustomMusic'); --put in mods/music/
end

-If you want it to play in all the songs, place it in "Mods/Scripts", or if you want the music to play only in some songs you can place the script in the "Mods/Data/-YourSongName/" folder.

**Comment by M4st3rG4m4** [comment]
If it works for you or if you need something else, let me know.
