### ISSUE TITLE
adskajsnmg,h

### ISSUE THREAD

**Issue by waterdrinkr2000** [ShadowMario/FNF-PsychEngine#14656]
### Describe your problem here.

i dont know what modding a build from source or with lua is im just trying to download mods helpp
im just gonna copy and paste what i already typed on youtube
this is with the colors & mayhem mod btw if that matters

im so confused and pretty frustrated this mod wont work whenever i go to the second song on the first troll week it gives me an error message then i have to exit out the game and theres a message saying my stuff is outdated and im on the 0.6.3 version of psych engine and it says to upgrade to 0.7.3 so i downloaded 0.7.3 of psych engine and it did nothing maybe i have to do some weird file moving stuff but i dont know theres no filedaddy download option and i opened the mod with both filedaddy and just opened it up within the files of the mod itself it still doesnt work the 3rd song doesnt work either it says
C:\HaxeToolKit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
StoryMenuState.hx (line 321)
StoryMenuState.hx (line 260)
flix el/FlxState.hx (line 202)
flix el/FlxGame (line 747)
flix el/FlxGame (line 677)
flix el/FlxGame (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/megid0/megid0-easy.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by YouDevsYoupikmin** [comment]
Try put the songs json in mods/data

**Comment by M4st3rG4m4** [comment]
Your problem is quite confusing but recurring, first of all search YouTube for the video of the mods and check which version of Psych Engine they are for, this is because not all mods work in all versions of Psych Engine, for example, the Psych Engine v0.6.3 mods have problems/glitches/bugs or simply do not work on Psych Engine v0.7.x
