### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ohight** [ShadowMario/FNF-PsychEngine#14650]
### Describe your bug here.

does anyone know what happened

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/frames/FlxAtlasFrames.hx (line 253)
states/MainMenuState.hx (line 78)
flixel/FlxGame.hx (line 640)
flixel/FlxGame.hx (line 727)
flixel/FlxGame.hx (line 680)
flixel/FlxGame.hx (line 559)
openfl/events/EventDispatcher.hx (line 426)
openfl/display/DisplayObject.hx (line 1398)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yeah, I'm trying to add a gallery

**Comment by Gearybeer** [comment]
Well for one
# Please spell “Help” correctly
and for two, its seem either some files are missing via you trying to add files, and in turn, accidentally deleting files.
or maybe the source code is being dumb and its genuinely bugged atm.

**Comment by ohight** [comment]
I'm a fucking idiot. There was just a comma where it shouldn't be in the JSON
