### ISSUE TITLE
Note error stuff

### ISSUE THREAD

**Issue by YoshiBoii** [ShadowMario/FNF-PsychEngine#1465]
### Describe your problem here.

I'm making a note where if you miss it, you die. When I try to compile the game, I get

source/PlayState.hx:3519: characters 4-8 : Expected }

Around that area, I have

		case 'Hardcore Note': 
				health -= 100
				}

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by guizinhomartinez** [comment]
because you didn't added a { before the health -= 100 or just remove the }, should fix it

**Comment by SrtHero278** [comment]
> because you didn't added a { before the health -= 100 or just remove the }, should fix it

I think it would be better to remove it actually. The error is talking about the `}` instead of a `{`. I haven't seen any case lines use `{}`.

**Comment by NS-Unfair** [comment]
You would be correct, remove the `}`
