### ISSUE TITLE
not being able to compile the main repository

### ISSUE THREAD

**Issue by guizinhomartinez** [ShadowMario/FNF-PsychEngine#1466]
### Describe your bug here.

for some reason on modmenustate there is a code problem that doesn't allow me to compile

### Command Prompt/Terminal logs (if existing)

```bash
source/ModsMenuState.hx:396: characters 36-47 : Array access is not allowed on {+ length : Int }
source/ModsMenuState.hx:396: characters 36-47 : For function argument 'Red'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, there was 2 more errors but i was able to fix them

**Comment by SrtHero278** [comment]
A lot of people are having that issue right now. I think someone said it was because the mods menu is unfinished.
