### ISSUE TITLE
error on lua script

### ISSUE THREAD

**Issue by GwilynDev** [ShadowMario/FNF-PsychEngine#14668]
### Describe your problem here.

![Capturar](https://github.com/ShadowMario/FNF-PsychEngine/assets/169847281/ff661fee-a55b-42b6-a801-27d0b57f2019)
this error appears when i start a custom song and a LUA file is active, like the stage, an script in the data folder and even when there are chart events. the background isn´t loading, and the scripts won´t work. the game was normal some days ago, and i literally didn´t touched in it. detail: i already even tried to reinstall Psych engine 0.7.3

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nah, i didn´t

**Comment by M4st3rG4m4** [comment]
Are you sure you didn't touch anything?, that shouldn't happen unless there is a modification in a Lua script.
Recently, in fact about two hours ago I had the same problem as you, but I need you to tell me what version of Psych Engine you are using.

**Comment by M4st3rG4m4** [comment]
Anyway I found the solution to the problem in Psych Engine v0.7.3, it turns out that no script can contain the letter ñ, otherwise this Lua script will not work

**Comment by GwilynDev** [comment]
> Anyway I found the solution to the problem in Psych Engine v0.7.3, it turns out that no script can contain the letter ñ, otherwise this Lua script will not work
Then when i get home, i'll try to search for something like this

**Comment by GwilynDev** [comment]
i checked and there´s no ñ in the stage script, i´m using this one:

--Hello! This is your script, you may be confused but its really easy
--First, you need to have your image ready, read the tutorial about the thing here:
--Next, replace the word "Test", with the name of your image (capitalization matters).
--Open up the game and press 7 in any song, after that 

function onCreate()
	-- background
	
	makeLuaSprite('floresta', 'floresta', -650, -460);
	setScrollFactor('floresta', 0.9, 0.9);
	scaleObject('floresta', 1.1, 1.1);


	addLuaSprite('floresta', false);
	
	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end

**Comment by M4st3rG4m4** [comment]
*that script is too simple*

**Comment by M4st3rG4m4** [comment]
There may also be something in a custom_event

**Comment by M4st3rG4m4** [comment]
In my case I was porting "Brimstone" by FNF Lullaby and I added an event called "AddZoomCamera" and that started to appear, but I didn't know why it happened since I had made many changes before testing. It wasn't until later that I realized the error and changed the name of the event to "AddCamaraZoom" and also changed everything about it within that same LUA script

**Comment by GwilynDev** [comment]
then i tried to make a custom note, but the custom note was glitched. i even tried to solve that, but i just erased it in the end

**Comment by M4st3rG4m4** [comment]
You can try two things.
1 - Extract Psych Engine v0.7.3 again in another separate folder and just pass the chart and Inst/Voices and try the Chart Editor.
2 - Download a more recent version of lime.ndl either x86 or x64, that will depend on whether you are using PEx86 or x64

**Comment by M4st3rG4m4** [comment]
Please do it as soon as possible and let me know so I can see what can be done.

**Comment by GwilynDev** [comment]
i´ll try it now

**Comment by GwilynDev** [comment]
result 1: i extracted Psych Engine again, the error screen is gone, but the background still doesn´t loads

**Comment by GwilynDev** [comment]
Wait, nevermind. i think it´s fixed

**Comment by GwilynDev** [comment]
earlier i changed the background´s name in the lua file, because i was doing the mod in portuguese, but i forgot to change the image name. in the lua file was "forest" and the image was named "floresta"

**Comment by GwilynDev** [comment]
yeah, it´s fixed. thanks for your patience

**Comment by M4st3rG4m4** [comment]
It was nothing, I'm glad you were the first person I helped here, if you don't have any more problems you can proceed to close the post.

**Comment by GwilynDev** [comment]
ok
