### ISSUE TITLE
I don't know what to do!

### ISSUE THREAD

**Issue by DevelSan** [ShadowMario/FNF-PsychEngine#14662]
### Describe your problem here.

i tried to compile the psych engine 0.7.3, it should be noted that i am new to this source thing, well,iI followed the steps in the guide, but it doesn't work, and i don't know what to do, if I have installed what it asks me there or I do not know
![Captura de pantalla 2024-05-13 211552](https://github.com/ShadowMario/FNF-PsychEngine/assets/98663429/c5832fe9-ca6a-43a3-b1c9-5ffec60ebe49)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

no, I'm just testing to gain experience

**Comment by YouDevsYoupikmin** [comment]
Did you installed visual studio? You need 2019 not 2022

**Comment by YouDevsYoupikmin** [comment]
Unistall and try reinstall visual studio from here
https://github.com/ShadowMario/FNF-PsychEngine/blob/main/setup/setup-msvc-win.bat

**Comment by MaximumX64** [comment]
and install hxcpp

**Comment by DevelSan** [comment]
that worked! thank you!

**Comment by MaximumX64** [comment]
no problem
