### ISSUE TITLE
Restart song

### ISSUE THREAD

**Issue by PineappleGoob** [ShadowMario/FNF-PsychEngine#14660]
### Describe your problem here.

Describe your bug here.
when I restart a song in psych engine it gives me this error. I am using haxeflixel in psych engine.

Command Prompt/Terminal logs (if existing)
flixel/FlxState.hx (line 176)

flixel/util/typeLimit/NextState.hx (line 69)

flixel/FlxGame.hx (line 631)

flixel/FlxGame.hx (line 727)

flixel/FlxGame.hx (line 680)

flixel/FlxGame.hx (line 559)

openfl/events/EventDispatcher.hx (line 426)

openfl/display/DisplayObject.hx (line 1398)

Uncaught Error: Attempting to resetState while the current state is destroyed

Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Freeplay, stages, characters, songs

**Comment by M4st3rG4m4** [comment]
Does that happen to you with a specific song or with all of them?

**Comment by Sadcubelol** [comment]
I had and have the same problem, I could solve it but now I don't remember how I did it lmao. Btw in my case it happens in all songs.

**Comment by M4st3rG4m4** [comment]
> I had and have the same problem, I could solved it but now I don't remember how I did it lmao. Btw in my case it happens in all songs.

wtf

**Comment by M4st3rG4m4** [comment]
Ok, try extracting a clean copy of Psych Engine into another separate folder and try that version

**Comment by M4st3rG4m4** [comment]
By the way, if you have mods you should know that many mods lower than Psych Engine v0.7.3 usually cause errors/bugs/glitches or simply do not work in engine versions higher than v0.7.x

**Comment by M4st3rG4m4** [comment]
> By the way, if you have mods you should know that many mods lower than Psych Engine v0.7.3 usually cause errors/bugs/glitches or simply do not work in engine versions higher than v0.7.x

Seriously, they can even make the songs themselves not work LOL

**Comment by PineappleGoob** [comment]
alrighty sorry for the late response. I am the programmer for the mod and it is being developed in with haxe and a little bit of lua with psych engine 7.2h. Will this mean I have to move all of my code to the new version of psych engine?

**Comment by M4st3rG4m4** [comment]
really not, i only think that maybe a lua script may be causing that 'cause resetState is being called but the playstate is destroyed wtf

**Comment by M4st3rG4m4** [comment]
> alrighty sorry for the late response. I am the programmer for the mod and it is being developed in with haxe and a little bit of lua with psych engine 7.2h. Will this mean I have to move all of my code to the new version of psych engine?

I really don't think it's necessary to move to v0.7.3, in fact this is just small additions and some bugfixes (but it brings with it some very annoying little problems in my experience :V)

**Comment by MightyTheArmiddilo** [comment]
I'm here to say that it's most likely your FlxState.hx file in your flixel library, for some reason it throws that error and closes no matter what. just find
`
_constructor = function():FlxState
{
throw "Attempting to resetState while the current state is destroyed";
};
`
and either comment it out or delete it. If that doesn't work, then I don't know.
