### ISSUE TITLE
Friend was playtesting my mod and got this error

### ISSUE THREAD

**Issue by WindowsGod2** [ShadowMario/FNF-PsychEngine#14663]
### Describe your bug here.

I haven't seen this error before, and I have no clue what might've caused this. Not sure if it has something to do with the mod itself or if it's an engine bug.
![image-8](https://github.com/ShadowMario/FNF-PsychEngine/assets/102393943/b0fcc081-86df-4605-a48d-750b982195e0)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I mostly changed crap in the assets folder, only to remove or edit content to fit the theming of my mod.

**Comment by WindowsGod2** [comment]
Starting to think it's just an issue with my friend's computer itself and not the actual mod, but I'd still like confirmation just in case.

**Comment by MaximumX64** [comment]
it says that jit must be enabled
