### ISSUE TITLE
Character Editor not working (Black Screen)

### ISSUE THREAD

**Issue by aziznahali01** [ShadowMario/FNF-PsychEngine#14661]
### Describe your problem here.

I am pretty new to the modding community but still know the basics of how to use the engine. I tried the new version of Psych Engine 0.7.3 and when i tried checking out the character editor it was not functional. i tried almost everything i could think of from redownloading all the requirements to getting old versions of the game untouched and when compiling still getting the same problem. i have searched everywhere online and no one else is having the same problem as me at all so im worried i messed something up on something im not supposed to touch. someone please guide me on how or where this came from.

![CharacterEditorBug](https://github.com/ShadowMario/FNF-PsychEngine/assets/99096903/b6e87d45-400a-41f9-a2ef-86664225166d)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i fixed some lines of code in source\psychlua\HScript.hx because when compiling i kept getting an error about TeaCall so i replaced all those by Tea

**Comment by LarryFrosty** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/pull/14495

**Comment by MaximumX64** [comment]
the teacall error is not the problem
i have the same problem
the first comment is refering to a pull request that fixes that error

**Comment by aziznahali01** [comment]
ugh thank you so much took a while to understand but it works thank you
