### ISSUE TITLE
Adding character strum line behind said character?

### ISSUE THREAD

**Issue by HourOfEternity** [ShadowMario/FNF-PsychEngine#14665]
### What is your question?

     I want to make a script that specifically puts the opponents notes behind the opponent, but using `setObjectOrder('opponentNotes')` or `setObjectOrder('strumLineNotes')` with `setObjectOrder('dad')` or `setObjectOrder('dadGroup')` does nothing at all.

     To clarify a few things: I've made a haxe script that puts the opponent's strumline in camGame, and nothing I've tried so far changes the object order of the opponent or the opponent strumline, not even to be over/under anything else.

     I would appreciate either an hscript or a lua script and/or an example of how to make this work. Thank you.

**Comment by HourOfEternity** [comment]
Why the hell did the question format like that

**Comment by BigSillyOrangeCat** [comment]
How did you do this?

**Comment by HourOfEternity** [comment]
So there are actually 2 parts to this, the first one being that you need to put the opponent's (or bf's) notes on camGame. Here's some code to help with that:
`function onCountdownStarted()
	runHaxeCode([[
		for (strum in game.opponentStrums)
		{
			strum.cameras = [game.camGame];
			strum.scrollFactor.set(1, 1);
			strum.scale.x = 0.9;
            strum.scale.y = 0.9;
		}
		for (note in game.unspawnNotes) 
		{
			if (!note.mustPress) {
				note.cameras = [game.camGame];
				note.scrollFactor.set(1, 1);
				note.scale.x = 0.9;
				note.scale.y = 0.9;
			if (note.isSustainNote) {
				note.scale.y = 2.5;
			} 
		}
		};
	]])
	end`
Along with that, there is this bit of code I used to make sure that the notes are behind both the opponent, gf, and bf:
`function onUpdatePost(elapsed)
    setObjectOrder('floor', getObjectOrder('opponentStrums.members[1]') + 23)
    setObjectOrder('dadGroup', getObjectOrder('floor') + 12)
    setObjectOrder('gfGroup', getObjectOrder('floor') + 12)
    setObjectOrder('boyfriendGroup', getObjectOrder('floor') + 14)
end`
Sorry if the code looks a bit wonky, I'm on a school laptop that doesn't like to format things correctly.

**Comment by Bssez** [comment]
does this code only work for 0.7+ or does it work for 0.6.3 as well?

**Comment by NikoDoritos** [comment]
https://github.com/user-attachments/assets/38b24c9f-aa40-49e9-8402-1f332be0d56f
How to make that working on bf side ( i changed game.opponentStrums on game.playerStrums but notes still spawns on wrong position)
