### ISSUE TITLE
how do I fix this ?

### ISSUE THREAD

**Issue by alexandrucn** [ShadowMario/FNF-PsychEngine#14673]
### Describe your problem here.

<img width="541" alt="Screenshot 2024-05-15 at 10 34 15 AM" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/104576909/9230da21-4699-4578-ab29-7ccd0e9ece22">

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by HourOfEternity** [comment]
Replace every instance of TeaCall with Tea
