### ISSUE TITLE
My game Crushes

### ISSUE THREAD

**Issue by SkiN1x** [ShadowMario/FNF-PsychEngine#14672]
### Describe your bug here.

Please help, I want to add my own music, I select it in the chart editor and click reload, after which it crashes. (I have everything with a capital letter, etc.)
![Friday Night Funkin'_ Psych Engine 15 05 2024 17_35_10](https://github.com/ShadowMario/FNF-PsychEngine/assets/169918477/0a32ddf7-7d54-47a2-8cba-6a99b8f276c4)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I just add me own song and a new week((

**Comment by Limey123** [comment]
The game can't find the song file or it's corrupted. If it was a different file format and plays with a music player, it wasn't converted properly. Make sure you are within the mod directory and that the files are named properly if the audio was exported as OGG.

**Comment by UltraFatBoi** [comment]
*crashes
