### ISSUE TITLE
wtf?

### ISSUE THREAD

**Issue by SpareEnderboy** [ShadowMario/FNF-PsychEngine#14676]
### Describe your bug here.

game wont compile on linux

### Command Prompt/Terminal logs (if existing)

```bash
[ender@archlinux FNF-PsychEngine]$ haxelib run lime test linux
source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Blitzedzz** [comment]
womp womp

**Comment by LarryFrosty** [comment]
Replace TeaCall with Tea

**Comment by SpareEnderboy** [comment]
close notes: if linux then replace all TeaCall with Tea

**Comment by FaultyWindows** [comment]
> womp womp

Instead of being helpful, you are just replying to other people's messages with "womp womp". What has this society become with "Womp Womp"? Be helpful for once.
