### ISSUE TITLE
Video below hud

### ISSUE THREAD

**Issue by SpiffyisntCool** [ShadowMario/FNF-PsychEngine#14679]
### What is your question?

I was just wondering if their is an event that could put a video below the hud

**Comment by HourOfEternity** [comment]
This first script goes in events, and you can change it however you want to, just make sure to put it in a .lua script:

function onEvent(name, value1, value2)
     if name == 'Your-Video-Event-Name' then -- Change the name to your choice
         makeVideoSprite('videoStart', value1, 0, 0, 'cam'..value2, false) -- value1 is the name of your video in mods/videos, value2 can be 'Game', 'HUD', or 'Other'
         setObjectOrder('videoStart_video', 0) -- Do NOT remove the '_video', as it is necessary using the second script
         setProperty('videoStart_video.alpha', 1) -- Once again, do NOT remove the '_video'
     end
end

The second script must be named 'VideoSpriteHandler.hx' and it MUST be in your mods/scripts:

import psychlua.LuaUtils;

import hxcodec.flixel.FlxVideo;

var globalData:Array<Array<Dynamic>> = [];

createGlobalCallback('makeVideoSprite', function(tag:String, videoFile:String, ?x:Float, ?y:Float, ?camera:String, ?shouldLoop:Bool)
{
	var videoData:Array<Dynamic> = [];
	
	if (game.modchartSprites.exists(tag + '_video'))
	{
		debugPrint('makeVideoSprite: This tag is not available! Use a different tag.', FlxColor.RED);
		return;
	}
	
	if (!FileSystem.exists(Paths.video(videoFile)))
	{
		debugPrint('makeVideoSprite: The video file "' + videoFile + '" cannot be found!', FlxColor.RED);
		return;
	}
	
	var sprite:FlxSprite = new FlxSprite(x, y).makeGraphic(1, 1, FlxColor.TRANSPARENT);
	sprite.camera = LuaUtils.cameraFromString(camera);
	game.modchartSprites.set(tag + '_video', sprite);
	add(sprite);
	
	var video:FlxVideo = new FlxVideo();
	
	video.alpha = 0;
	
	video.onTextureSetup.add(function()
	{
		sprite.loadGraphic(video.bitmapData);
	});
	
	video.play(Paths.video(videoFile), shouldLoop);
	
	video.onEndReached.add(function()
	{
		video.dispose();
		
		if (FlxG.game.contains(video))
			FlxG.game.removeChild(video);
		
		if (globalData.indexOf(videoData) >= 0)
			globalData.remove(videoData);
		
		if (game.modchartSprites.exists(tag + '_video'))
		{
			game.modchartSprites.get(tag + '_video').destroy();
			game.modchartSprites.remove(tag + '_video');
		}
			
		game.callOnLuas('onVideoFinished', [tag]);
		
		return;
	}, true);
	
	FlxG.game.addChild(video);
	
	videoData.push(video);
	videoData.push(sprite);
	
	globalData.push(videoData);
});

function onPause()
{
	for (video in globalData)
	{
		if (video[0] != null)
		{
			video[0].pause();
			
			if (FlxG.autoPause)
			{
				if (FlxG.signals.focusGained.has(video[0].resume))
					FlxG.signals.focusGained.remove(video[0].resume);

				if (FlxG.signals.focusLost.has(video[0].pause))
					FlxG.signals.focusLost.remove(video[0].pause);
			}
		}
	}
}

function onResume()
{
	for (video in globalData)
	{
		if (video[0] != null)
			video[0].resume();
			
		if (FlxG.autoPause)
		{
			if (!FlxG.signals.focusGained.has(video[0].resume))
				FlxG.signals.focusGained.add(video[0].resume);

			if (!FlxG.signals.focusLost.has(video[0].pause))
				FlxG.signals.focusLost.add(video[0].pause);
		}
	}
}

function onDestroy()
{
	for (video in globalData)
	{
		if (video[0] != null)
			video[0].stop();
	}
}

var cache:Array<String> = ['open','SO_STAY_FINAL'];

function precacheVideos()
{
	for (i in 0 ... cache.length)
	{
		var video:FlxVideo = new FlxVideo();
		video.play(Paths.video(cache[i]));
		video.stop();
	}
}

precacheVideos();

Hope this works for you!

**Comment by HourOfEternity** [comment]
Sorry for the weird formatting, my school messes things up like this.

**Comment by Frankitoo2** [comment]
how can you change the

> This first script goes in events, and you can change it however you want to, just make sure to put it in a .lua script:
> 
> function onEvent(name, value1, value2) if name == 'Your-Video-Event-Name' then -- Change the name to your choice makeVideoSprite('videoStart', value1, 0, 0, 'cam'..value2, false) -- value1 is the name of your video in mods/videos, value2 can be 'Game', 'HUD', or 'Other' setObjectOrder('videoStart_video', 0) -- Do NOT remove the '_video', as it is necessary using the second script setProperty('videoStart_video.alpha', 1) -- Once again, do NOT remove the '_video' end end
> 
> The second script must be named 'VideoSpriteHandler.hx' and it MUST be in your mods/scripts:
> 
> import psychlua.LuaUtils;
> 
> import hxcodec.flixel.FlxVideo;
> 
> var globalData:Array<Array> = [];
> 
> createGlobalCallback('makeVideoSprite', function(tag:String, videoFile:String, ?x:Float, ?y:Float, ?camera:String, ?shouldLoop:Bool) { var videoData:Array = [];
> 
> ```
> if (game.modchartSprites.exists(tag + '_video'))
> {
> 	debugPrint('makeVideoSprite: This tag is not available! Use a different tag.', FlxColor.RED);
> 	return;
> }
> 
> if (!FileSystem.exists(Paths.video(videoFile)))
> {
> 	debugPrint('makeVideoSprite: The video file "' + videoFile + '" cannot be found!', FlxColor.RED);
> 	return;
> }
> 
> var sprite:FlxSprite = new FlxSprite(x, y).makeGraphic(1, 1, FlxColor.TRANSPARENT);
> sprite.camera = LuaUtils.cameraFromString(camera);
> game.modchartSprites.set(tag + '_video', sprite);
> add(sprite);
> 
> var video:FlxVideo = new FlxVideo();
> 
> video.alpha = 0;
> 
> video.onTextureSetup.add(function()
> {
> 	sprite.loadGraphic(video.bitmapData);
> });
> 
> video.play(Paths.video(videoFile), shouldLoop);
> 
> video.onEndReached.add(function()
> {
> 	video.dispose();
> 	
> 	if (FlxG.game.contains(video))
> 		FlxG.game.removeChild(video);
> 	
> 	if (globalData.indexOf(videoData) >= 0)
> 		globalData.remove(videoData);
> 	
> 	if (game.modchartSprites.exists(tag + '_video'))
> 	{
> 		game.modchartSprites.get(tag + '_video').destroy();
> 		game.modchartSprites.remove(tag + '_video');
> 	}
> 		
> 	game.callOnLuas('onVideoFinished', [tag]);
> 	
> 	return;
> }, true);
> 
> FlxG.game.addChild(video);
> 
> videoData.push(video);
> videoData.push(sprite);
> 
> globalData.push(videoData);
> ```
> 
> });
> 
> function onPause() { for (video in globalData) { if (video[0] != null) { video[0].pause();
> 
> ```
> 		if (FlxG.autoPause)
> 		{
> 			if (FlxG.signals.focusGained.has(video[0].resume))
> 				FlxG.signals.focusGained.remove(video[0].resume);
> 
> 			if (FlxG.signals.focusLost.has(video[0].pause))
> 				FlxG.signals.focusLost.remove(video[0].pause);
> 		}
> 	}
> }
> ```
> 
> }
> 
> function onResume() { for (video in globalData) { if (video[0] != null) video[0].resume();
> 
> ```
> 	if (FlxG.autoPause)
> 	{
> 		if (!FlxG.signals.focusGained.has(video[0].resume))
> 			FlxG.signals.focusGained.add(video[0].resume);
> 
> 		if (!FlxG.signals.focusLost.has(video[0].pause))
> 			FlxG.signals.focusLost.add(video[0].pause);
> 	}
> }
> ```
> 
> }
> 
> function onDestroy() { for (video in globalData) { if (video[0] != null) video[0].stop(); } }
> 
> var cache:Array = ['open','SO_STAY_FINAL'];
> 
> function precacheVideos() { for (i in 0 ... cache.length) { var video:FlxVideo = new FlxVideo(); video.play(Paths.video(cache[i])); video.stop(); } }
> 
> precacheVideos();
> 
> Hope this works for you!

hey, i was testing this because i been searching a script like this for like 3 months, and it works! but uhh how can i scale the video? it is small

**Comment by NiftyAC** [comment]
> This first script goes in events, and you can change it however you want to, just make sure to put it in a .lua script:
> 
> function onEvent(name, value1, value2) if name == 'Your-Video-Event-Name' then -- Change the name to your choice makeVideoSprite('videoStart', value1, 0, 0, 'cam'..value2, false) -- value1 is the name of your video in mods/videos, value2 can be 'Game', 'HUD', or 'Other' setObjectOrder('videoStart_video', 0) -- Do NOT remove the '_video', as it is necessary using the second script setProperty('videoStart_video.alpha', 1) -- Once again, do NOT remove the '_video' end end
> 
> The second script must be named 'VideoSpriteHandler.hx' and it MUST be in your mods/scripts:
> 
> import psychlua.LuaUtils;
> 
> import hxcodec.flixel.FlxVideo;
> 
> var globalData:Array<Array> = [];
> 
> createGlobalCallback('makeVideoSprite', function(tag:String, videoFile:String, ?x:Float, ?y:Float, ?camera:String, ?shouldLoop:Bool) { var videoData:Array = [];
> 
> ```
> if (game.modchartSprites.exists(tag + '_video'))
> {
> 	debugPrint('makeVideoSprite: This tag is not available! Use a different tag.', FlxColor.RED);
> 	return;
> }
> 
> if (!FileSystem.exists(Paths.video(videoFile)))
> {
> 	debugPrint('makeVideoSprite: The video file "' + videoFile + '" cannot be found!', FlxColor.RED);
> 	return;
> }
> 
> var sprite:FlxSprite = new FlxSprite(x, y).makeGraphic(1, 1, FlxColor.TRANSPARENT);
> sprite.camera = LuaUtils.cameraFromString(camera);
> game.modchartSprites.set(tag + '_video', sprite);
> add(sprite);
> 
> var video:FlxVideo = new FlxVideo();
> 
> video.alpha = 0;
> 
> video.onTextureSetup.add(function()
> {
> 	sprite.loadGraphic(video.bitmapData);
> });
> 
> video.play(Paths.video(videoFile), shouldLoop);
> 
> video.onEndReached.add(function()
> {
> 	video.dispose();
> 	
> 	if (FlxG.game.contains(video))
> 		FlxG.game.removeChild(video);
> 	
> 	if (globalData.indexOf(videoData) >= 0)
> 		globalData.remove(videoData);
> 	
> 	if (game.modchartSprites.exists(tag + '_video'))
> 	{
> 		game.modchartSprites.get(tag + '_video').destroy();
> 		game.modchartSprites.remove(tag + '_video');
> 	}
> 		
> 	game.callOnLuas('onVideoFinished', [tag]);
> 	
> 	return;
> }, true);
> 
> FlxG.game.addChild(video);
> 
> videoData.push(video);
> videoData.push(sprite);
> 
> globalData.push(videoData);
> ```
> 
> });
> 
> function onPause() { for (video in globalData) { if (video[0] != null) { video[0].pause();
> 
> ```
> 		if (FlxG.autoPause)
> 		{
> 			if (FlxG.signals.focusGained.has(video[0].resume))
> 				FlxG.signals.focusGained.remove(video[0].resume);
> 
> 			if (FlxG.signals.focusLost.has(video[0].pause))
> 				FlxG.signals.focusLost.remove(video[0].pause);
> 		}
> 	}
> }
> ```
> 
> }
> 
> function onResume() { for (video in globalData) { if (video[0] != null) video[0].resume();
> 
> ```
> 	if (FlxG.autoPause)
> 	{
> 		if (!FlxG.signals.focusGained.has(video[0].resume))
> 			FlxG.signals.focusGained.add(video[0].resume);
> 
> 		if (!FlxG.signals.focusLost.has(video[0].pause))
> 			FlxG.signals.focusLost.add(video[0].pause);
> 	}
> }
> ```
> 
> }
> 
> function onDestroy() { for (video in globalData) { if (video[0] != null) video[0].stop(); } }
> 
> var cache:Array = ['open','SO_STAY_FINAL'];
> 
> function precacheVideos() { for (i in 0 ... cache.length) { var video:FlxVideo = new FlxVideo(); video.play(Paths.video(cache[i])); video.stop(); } }
> 
> precacheVideos();
> 
> Hope this works for you!

this helped me alot. thank you.
