### ISSUE TITLE
Icon bounce using PlayState.hx

### ISSUE THREAD

**Issue by FinderFromMac** [ShadowMario/FNF-PsychEngine#14685]
### What is your question?

im trying to make my own engine using the source code, but how do i add icon bounce animations only using playstate.hx?

**Comment by FinderFromMac** [comment]
it sounds stupid but its for my engine

**Comment by Gearybeer** [comment]
You are making your own engine. Out of an engine.
Seems legit. 
Small answer, you can’t
Long answer, y'all'd'nt've'd'd'I'd'nt've'd'y'all't've'd

**Comment by FinderFromMac** [comment]
Thanks

**Comment by FinderFromMac** [comment]
Sorry if this is not a real issue

**Comment by Gearybeer** [comment]
> Sorry if this is not a real issue

Ur fine, no problems here

**Comment by FinderFromMac** [comment]
Ok, I was curious if there was a way to do so
