### ISSUE TITLE
it keeps saying this when i try to run "lime test windows"

### ISSUE THREAD

**Issue by jack-dutchie** [ShadowMario/FNF-PsychEngine#14684]
### Describe your problem here.

it says 

------------------------SScript 7.7.0 Macro------------------------
Special Thanks:
- CrowPlexus

Checking version...
There was an error getting the latest version info, you may not have internet connection.
Continuing...
-------------------------------------------------------------------

C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
C:\Users\----\Downloads\FNF-PsychEngine-0.7.2\FNF-PsychEngine-0.7.2\export\release\windows\obj>setlocal enabledelayedexpansion
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by jack-dutchie** [comment]
fixed it

**Comment by WolfyTail** [comment]
how did you fix it? i have the same problem
