### ISSUE TITLE
note color change question

### ISSUE THREAD

**Issue by nintendofan44** [ShadowMario/FNF-PsychEngine#1468]
### What is your question?

how do i make it so like the arrowHSV of the opponent's notes stay the same
like,
bf's arrow colors still can change but the opponent's doesn't

**Comment by nintendofan44** [comment]
and yes,
its on the source code

**Comment by nintendofan44** [comment]
@ShadowMario pls help

**Comment by ShadowMario** [comment]
`note.colorSwap.hue`, `note.colorSwap.saturation`, `note.colorSwap.brightness`
