### ISSUE TITLE
Character using multiple files

### ISSUE THREAD

**Issue by NavaGaming** [ShadowMario/FNF-PsychEngine#14687]
### Describe your problem here.

How do i make a character out of multiple files? like there's up.png and up.png and etc
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/105751462/dd6c1a87-a928-4eeb-82ce-a19782b73e44)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TFLTV** [comment]
I do not recommend this, but, if you wish so, then my advice is you probably can.
Use a Lua script to change the poses in some way, not completely sure on how, but I'm sure it's possible.
You should probably just make a character comprising of one file, not several.

**Comment by NavaGaming** [comment]
> I do not recommend this, but, if you wish so, then my advice is you probably can. Use a Lua script to change the poses in some way, not completely sure on how, but I'm sure it's possible. You should probably just make a character comprising of one file, not several.

I mean yea, that could work, but this one specific character is MASSIVE, im not even sure if image that big is allowed to exist

**Comment by TheAmongUsDC2Guy** [comment]
Vs tricky done it
