### ISSUE TITLE
Big Engine Brawl FNF Error

### ISSUE THREAD

**Issue by TroubleOntheTracks** [ShadowMario/FNF-PsychEngine#14680]
### Describe your bug here.

When the mod loads it gives me a error and when i click okay then the game closes
![Zrzut ekranu 2024-05-16 120942](https://github.com/ShadowMario/FNF-PsychEngine/assets/169993151/041d3802-d7b2-426e-b47c-909878b5eafc)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I Didn'r Edit anything

**Comment by ShadowMario** [comment]
Report this to the mod's owners

**Comment by TroubleOntheTracks** [comment]
Ok ShadowMario
