### ISSUE TITLE
how do i access the accuracy shit for lua?

### ISSUE THREAD

**Issue by SlushieDrawzCoolDrawingX480** [ShadowMario/FNF-PsychEngine#14696]
### What is your question?

how do i access the accuracy shit for lua?

**Comment by TFLTV** [comment]
Look at the Wiki, it has tons of useful information for Lua modding and stuff.
[Here is the page for score and accuracy functions.](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#scoreaccuracy-functions)
