### ISSUE TITLE
I can't build or install vs 2019

### ISSUE THREAD

**Issue by MeektyGames** [ShadowMario/FNF-PsychEngine#14692]
### Describe your problem here.

I followed the tutorial got all the right versions but i keep getting

Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

when I try to build I googled it and the answer was vs 2019 but I can't install it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Novatooos** [comment]
Its the same for me, microsoft apparently made them unobtainaible.
if you go into the older versions page, you will see Visual Studio 2019 Community isn't avaible,

**Comment by MeektyGames** [comment]
If you click the setup-msvc-win.bat file in the setup folder you get vs 2019

**Comment by Novatooos** [comment]
Where can I find it exactly?

**Comment by MeektyGames** [comment]
the setup folder

**Comment by Novatooos** [comment]
What setup folder?
