### ISSUE TITLE
Building latest development doesn't include basegame assets?

### ISSUE THREAD

**Issue by RowanSkie** [ShadowMario/FNF-PsychEngine#14695]
### Describe your problem here.

I don't know what I'm doing wrong.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by DetectiveBaldi** [comment]
compile with `-D officialBuild`, there's also a Project.xml flag for it
