### ISSUE TITLE
More ways to edit the ratings and combo numbers (or the unused combo.png being toggleable)

### ISSUE THREAD

**Issue by UltraFatBoi** [ShadowMario/FNF-PsychEngine#14698]
### What feature do you want to get added on the **base** engine?

1. Move Ratings and Combo Numbers to where the GF is.
2. Replace assets for ratings and combo numbers (and combo.png) from in-game without opening the assets/shared folders
You can add this if you were to make v0.7.4 or something above that.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by TFLTV** [comment]
You can already do two with the ratings.
Example:
```lua
setProperty('ratingsData[0].image', 'custom_rating_image') --change "Sick" image to "custom_rating_image" image
setProperty('ratingsData[1].image', 'custom_rating_good') --change "Good" image to "custom_rating_good" image
```

**Comment by crowplexus** [comment]
```lua
setObjectCamera("comboGroup", "camGame")
```
for the first request
