### ISSUE TITLE
Suggestion; in-depth guide on coding .mp4s in-game

### ISSUE THREAD

**Issue by TrustVVorthy** [ShadowMario/FNF-PsychEngine#147]
I've been looking for a way for to make an .mp4 occur when i start the week, although i dont know how to execute it.

wondering the specific variable used to code it in

**Comment by ShadowMario** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/44785097/135358566-98f474e9-ff85-4dab-a4f9-a30684b10ec6.png)

Basically this, but instead of `startDialogue(dialogueJson)`, you use `startVideo('songCutscene')`, it will load the file in `assets/videos/songCutscene.mp4`
