### ISSUE TITLE
How make Freeplay menu like Ourple Guy?

### ISSUE THREAD

**Issue by BonnieDeRobot20** [ShadowMario/FNF-PsychEngine#14705]
### Describe your problem here.

So like, the freeplay menu from Ourple Guy is really cool and i want to replicate it but idk how. I can use both Source and Lua if i need to but I just can't find anything to help me. I do also plan to have only one difficulty for each song making this way easier to do the side scrolling stuff Ourple Guy did (sorry Ourple guy was the first mod that came to mind when i think of the freeplay menu i want and every menu in general)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Mokona5901** [comment]
Check mod source code here : https://github.com/FixedData/ourpleV3SourceCodePUBLIC
