### ISSUE TITLE
Character Editor Screen Blacked Out

### ISSUE THREAD

**Issue by Tapsiphone** [ShadowMario/FNF-PsychEngine#14703]
### Describe your problem here.

<img width="1470" alt="Screenshot 2024-05-19 at 1 47 22 pm" src="https://github.com/ShadowMario/FNF-PsychEngine/assets/170215783/2422165c-0775-4c65-b8ba-e916dc26da28">
Not exactly sure whats going on with it, everything else works fine but just this. I saw one other post but I couldn't figure out what was wrong or if its even possible on mac!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

**Comment by DoctorOPlays** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/pull/14495#issuecomment-2117432754
