### ISSUE TITLE
How to fix custom notes in Psych Engine 0.7.3

### ISSUE THREAD

**Issue by GwilynDev** [ShadowMario/FNF-PsychEngine#14701]
### Describe your problem here.

Whenever i create an custom note, its colors are the colors of the default notes from fnf, and the custom notes are out of place. A bit to the left, to be more specific.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nah

**Comment by HourOfEternity** [comment]
To fix the notecolor, use:
`setPropertyFromGroup('unspawnNotes', i, 'rgbShader.enabled', value1);`
Idk about the displacement one tho

**Comment by HourOfEternity** [comment]
change the value1 to false

**Comment by GwilynDev** [comment]
i´ll test it

**Comment by GwilynDev** [comment]
It worked, and i even figured out how to fix the notes out of place

**Comment by GwilynDev** [comment]
i just had to mess with the offset

**Comment by GwilynDev** [comment]
"setPropertyFromGroup('unspawnNotes', i, 'offsetX', -160); --Changes the offset X"

**Comment by GwilynDev** [comment]
the custom notes were like this
![Uploading Capturar.PNG…]()

**Comment by GwilynDev** [comment]
![Capturar](https://github.com/ShadowMario/FNF-PsychEngine/assets/169847281/7f8de060-87ac-4ee2-8234-9fa594acf971)

the custom notes were like this
