### ISSUE TITLE
add weekend1

### ISSUE THREAD

**Issue by Funkypupo** [ShadowMario/FNF-PsychEngine#14700]
### What feature do you want to get added on the **base** engine?

hey i dont know if youre working on this or something else. if youre already working on it great if you're not thats ok too

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by HourOfEternity** [comment]
1. You failed the test

2. He's already working on it.

**Comment by Funkypupo** [comment]
> 1. You failed the test
> 2. He's already working on it.

thanks but what test

**Comment by HourOfEternity** [comment]
#To test your sight, and reliability, please select the option of what should NOT be requested.
#Proper credit that was forgotten
This test ^

**Comment by HourOfEternity** [comment]
> To test your sight, and reliability, please select the option of what should NOT be requested.

> Proper credit that was forgotten
(:

**Comment by HourOfEternity** [comment]
>To test your sight, and reliability, please select the option of what should NOT be requested.
>Proper credit that was forgotten
