### ISSUE TITLE
doTwenAngle does not work repeatedly

### ISSUE THREAD

**Issue by KoiderXD** [ShadowMario/FNF-PsychEngine#14711]
### Describe your problem here.

doTweenAngle does not work after the first call. I've already changed tags and other data, all in vain. Here's the code:

```
function onStepHit()
    if curStep == 152 then
        doTweenAngle('angle', 'camHUD', 360, 1.7, 'circInOut')
    end
    if curStep == 216 then
        doTweenAngle('angle2', 'camHUD', 360, 1.7, 'circInOut')
    end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by DetectiveBaldi** [comment]
You're tweening the angle to 360, when it is already 360. Set the angle back to 0 and then tween the object again

**Comment by KoiderXD** [comment]
Thank you, it really worked!
