### ISSUE TITLE
Im stuck

### ISSUE THREAD

**Issue by Baskanguish** [ShadowMario/FNF-PsychEngine#14726]
### Describe your problem here.

I had everything installed, but it says "source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall" what should I do? what step did I miss?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by YouDevsYoupikmin** [comment]
try SSCript 7.7.0 or 20.8.618

**Comment by Baskanguish** [comment]
I downloaded it, what should I do next?

**Comment by Baskanguish** [comment]
The issue is gone, but another issue has arisen. when I tried it again it says "Library lime is not installed"
