### ISSUE TITLE
How to fix "hxcodec/vlc/VLCBitmap.hx:144: characters 23-38 : Type not found : LibVLC_Instance"

### ISSUE THREAD

**Issue by YuananimationChannel** [ShadowMario/FNF-PsychEngine#14722]
### Describe your problem here.

I need help how can i fix this error? : hxcodec/vlc/VLCBitmap.hx:144: characters 23-38 : Type not found : LibVLC_Instance
I'm using Psych Engine 0.6.3

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
0.6.3 is not supported anymore since December 2023
