### ISSUE TITLE
Force disable shaders of a mod

### ISSUE THREAD

**Issue by OrigamingWasTaken** [ShadowMario/FNF-PsychEngine#14728]
### Describe your problem here.

Hi, i'm on MacOS and using GPTK (Wine) to run PsychEngine mods. Is there some sort of program argument (mod.exe --args) I can use to force disable the shaders? Because of the outdated OpenGL version on Mac, they make the game unable to launch.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by OrigamingWasTaken** [comment]
Why has this been closed as completed when it isn't?

**Comment by FuseIsHere813** [comment]
> Why has this been closed as completed when it isn't?

the issue was stale
