### ISSUE TITLE
Function onNextLine()

### ISSUE THREAD

**Issue by Gla90l** [ShadowMario/FNF-PsychEngine#14737]
### What feature do you want to get added on the **base** engine?

How about an lua function called OnNextLine that will be used when player reads another lines in the dialogue? It's can helps to make some voice acting using some local thingy

### To test your sight, and reliability, please select the option of what should NOT be requested.

Better LUA mod support idea

**Comment by Gla90l** [comment]
Sorry for my English ehhh, btw im from Russia

**Comment by Gla90l** [comment]
.

**Comment by DetectiveBaldi** [comment]
this already exists `onNextDialogue`
