### ISSUE TITLE
how do you fix "source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall"

### ISSUE THREAD

**Issue by superarell** [ShadowMario/FNF-PsychEngine#14735]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/88277674/53ac443b-3bc1-4145-9cfe-1f782a795b92)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by HourOfEternity** [comment]
Replace all instances of TeaCall with Tea

**Comment by sofyisstupid** [comment]
haxelib install SScript 8.1.6

**Comment by kpsm485** [comment]
none of those worked
