### ISSUE TITLE
hold notes zoom

### ISSUE THREAD

**Issue by joxu13v** [ShadowMario/FNF-PsychEngine#14738]
### Describe your problem here.

How can I make sure that when holding a long note, both the opponent and bf are zoomed in while they are making the note, and then return to the default zoom of the stage?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by JHAM25** [comment]
Pues lo hice de esta forma:

activado = true
function onCreatePost()
    debugPrint(getProperty('defaultCamZoom'))
    zoomNormal = getProperty('defaultCamZoom')
    zoom = getProperty('defaultCamZoom')
end
function onMoveCamera(focus)
    if focus == 'boyfriend' then
        bf = true 
        dad = false
    elseif focus == 'dad' then
        bf = false 
        dad = true
    end
end
function goodNoteHit(id, noteData, noteType, isSustainNote)
    if bf == true then
    if isSustainNote then
        if activado then
        zoom = zoom + getRandomFloat(0.01,0.1)
        setProperty('defaultCamZoom', zoom)
        end
    end
    if not isSustainNote then
        setProperty('defaultCamZoom', zoomNormal)
        zoom = zoomNormal
    end
    end
end
function opponentNoteHit(id, noteData, noteType, isSustainNote)
    if dad == true then
    if isSustainNote then
        if activado then
        zoom = zoom + getRandomFloat(0.01,0.1)
        setProperty('defaultCamZoom', zoom)
        end
    end
    if not isSustainNote then
        setProperty('defaultCamZoom', zoomNormal)
        zoom = zoomNormal
    end
    end
end
function onUpdate()
if getProperty('boyfriend.animation.curAnim.name') == 'idle' and getProperty('dad.animation.curAnim.name') == 'idle' then
    if getProperty('boyfriend.animation.curAnim.finished') then
        if getProperty('dad.animation.curAnim.finished') then
        --runTimer('normalidad', 0.5)
        setProperty('defaultCamZoom', zoomNormal)
        zoom = zoomNormal
        end
    end

        
    
end
    if zoom >= 1.2 then
        activado = false

    else
        activado = true
    end
end

**Comment by JHAM25** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/7b118b12-4563-4817-bf56-cbf77e541506

**Comment by joxu13v** [comment]
thx

**Comment by joxu13v** [comment]
> 
> https://github.com/ShadowMario/FNF-PsychEngine/assets/108441263/7b118b12-4563-4817-bf56-cbf77e541506
> 
> 

thanks
