### ISSUE TITLE
my stage isn't showing up in the chart editor 

### ISSUE THREAD

**Issue by MikExpungedMoment** [ShadowMario/FNF-PsychEngine#14732]
I added the line of code for it into PlayState.hx, and i made it's own file thingy using the template, but it isn't showing up. The only thing i really did that might be causing this was editing "override function countdownTick(count: BaseStage.Countdown, num:Int)" to "override function countdownTick(count:Countdown, num:Int)", and i did that because it was showing me an error with it still there
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/170558135/ba61b399-8ec4-475b-bb0d-420c8c8733cb)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/170558135/98f47bd7-b517-4a6f-b407-54e6cef72ccf)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/170558135/bec9ec4d-cad3-464d-a238-27a9f8d1d7e5)
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/170558135/11961f6b-a680-4a97-8ed0-b9afbbfb1020)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i edited TeaCall to just Tea, and changed some of the fonts, i also added the line of code for my stage into playstate and it's own source

**Comment by sofyisstupid** [comment]
did you put it on the stage list?

**Comment by sofyisstupid** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/143369993/7c6328d4-f1c6-4aee-a517-c9fea0303215)

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/143369993/e348ab7a-7e89-4095-ba50-bd1d5aa272d6)

**Comment by MikExpungedMoment** [comment]
> did you put it on the stage list?

i'm an idiot, thank you for telling me this
