### ISSUE TITLE
keeps kicking me out smh 

### ISSUE THREAD

**Issue by umora909** [ShadowMario/FNF-PsychEngine#14731]
### Describe your problem here.

i was playing a mod using this engine and whenever i get to a certain point like minute 3:00 
it says:        

states/PlayState.hx (line 2658)
states/PlayState.hx (line 2601)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

so i ask u to help me with that??

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope.

**Comment by YouDevsYoupikmin** [comment]
Try delete every events on the song and retry
