### ISSUE TITLE
how use changePresence

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#14733]
### Describe your problem here.

yeah i wanna know how to use it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by potatex2** [comment]
For reasons I don't really know nor understand yet, the Lua call to it is apparently `changeDiscordPresence()` when I tried it previously, not sure how the timestamp for the timers/time elapsed works much, but based on the source file --
`public static function changePresence(?details:String = 'Just Vibing', ?state:Null<String>, ?smallImageKey : String, ?hasStartTimestamp : Bool, ?endTimestamp: Float)`
-- it works similarly to this -
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/96308850/6fec5364-196a-48f8-9705-5ca897f46349)
