### ISSUE TITLE
Why does it keep saying Animation not found?

### ISSUE THREAD

**Issue by DaBrazillianBoi** [ShadowMario/FNF-PsychEngine#14740]
### Describe your problem here.

i made a character (png) and a xml file but when im put it into mods/modtemplate/my mods/images/characters and then when i go into psych engine character editor and then type the name of my character it says animation not found

i used psych engine 7.3

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by AUTISTICFNF** [comment]
SAMEE
EE








E

E

E
E
E

**Comment by kpsm485** [comment]
prolly you didnt add the names on the xml file to the character editor or vice versa

**Comment by Justmodmaker** [comment]
i have same problem but i have png and xml on my mod template sameeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
