### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by DEV-idiotXD** [ShadowMario/FNF-PsychEngine#1474]
### Describe your bug here.

i keep getting this error when compiling :/

### Command Prompt/Terminal logs (if existing)

```bash
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i just wanted to test if it would compile

**Comment by NotEpik** [comment]
i guess 64bit is not automatically supported for VC version idk
