### ISSUE TITLE
Hello, I need help, this error keeps appearing over and over again :(

### ISSUE THREAD

**Issue by VanySubnormal** [ShadowMario/FNF-PsychEngine#14743]
### Describe your bug here.

Before you tell me to check the other posts, YES I SAW MANY WAYS TO FIX IT, and even installed others and until now this error still appears, I have installed haxelib install hxCodec 2.5.1 and visual studio community 2017, a Despite everything , this error keeps appearing to me every time. AAAAAAAAAAAAAAAAA HELP

### Command Prompt/Terminal logs (if existing)

```bash
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\Manuel\Desktop\FNF-PsychEngine-0.6.3\export\release\windows\obj>setlocal enabledelayedexpansion 
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, install only what is necessary

**Comment by ShadowMario** [comment]
0.6.3 is not supported anymore since December 2023
