### ISSUE TITLE
In-Game-HP.

### ISSUE THREAD

**Issue by Meziaki** [ShadowMario/FNF-PsychEngine#14744]
### What is your question?

Is there a way I can make it so a script outright stops you from gaining HP on note-press?

**Comment by Draconic-Hybrid** [comment]
Not tested, but in theory should work.

```lua
for i = 0, getProperty('unspawnNotes.length')-1 do
	setPropertyFromGroup('unspawnNotes', i, 'hitHealth', 0)
end
```

**Comment by TFLTV** [comment]
This might be less flexible, but, in theory should work (i have not tested)
```lua
function onUpdatePost()
setProperty("health",1) -- Set value from 0 to 2. 0 is no health and 2 is full health. you can set this to any value but might not work properly
end

**Comment by Draconic-Hybrid** [comment]
> This might be less flexible, but, in theory should work (i have not tested)
> 
> ```lua
> function onUpdatePost()
> setProperty("health",1) -- Set value from 0 to 2. 0 is no health and 2 is full health. you can set this to any value but might not work properly
> end
> ```

This one also prevents losing HP on miss.

**Comment by M4st3rG4m4** [comment]
> > This might be less flexible, but, in theory should work (i have not tested)
> > ```lua
> > function onUpdatePost()
> > setProperty("health",1) -- Set value from 0 to 2. 0 is no health and 2 is full health. you can set this to any value but might not work properly
> > end
> > ```
> 
> This one also prevents losing HP on miss.

@Draconic-Hybrid You are absolutely right, in theory healthBar would always be static (unless the opponent has a script that affects health I think).

@Meziaki Also try this one:

function goodNoteHit(membersIndex, noteData, noteType, isSustainNote)
for i = 0, getProperty('unspawnNotes.length')-1 do
	setPropertyFromGroup('unspawnNotes', i, 'hitHealth', 0)
end
end

I will test it later :v

**Comment by TFLTV** [comment]
> > This might be less flexible, but, in theory should work (i have not tested)
> > ```lua
> > function onUpdatePost()
> > setProperty("health",1) -- Set value from 0 to 2. 0 is no health and 2 is full health. you can set this to any value but might not work properly
> > end
> > ```
> 
> This one also prevents losing HP on miss.

ohh yea, true, i was thinking they wanted something like Defeat from Imposter v4 (The health stays still in Defeat)

**Comment by M4st3rG4m4** [comment]
> ohh yea, true, i was thinking they wanted something like Defeat from Imposter v4 (The health stays still in Defeat) i guess i read it wrong

Don't worry, I understand

**Comment by M4st3rG4m4** [comment]
@Meziaki If you don't need anymore please close this issue

**Comment by Meziaki** [comment]
Thank you for the help. I kind of forgot of the fact that I posted this. And yes, it was something like Defeat's mechanic. Ty for the help.
