### ISSUE TITLE
error HELP pretty please with a cherry on top

### ISSUE THREAD

**Issue by Kubarika** [ShadowMario/FNF-PsychEngine#14749]
### Describe your bug here.

error pops up when loading character
![bug](https://github.com/ShadowMario/FNF-PsychEngine/assets/170886056/8b1a5ea4-6b85-4e78-9019-59094b7c90e3)

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/frames/FlxAtlasFrames.hx (line 256)
states/editors/CharacterEditorState.hx (line 802)
states/editors/CharacterEditorState.hx (line 625)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 444) 
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by stupidkade** [comment]
happened to me also :/ can i see the code you have for the character animations? or just tell me what you used for the sprites?

**Comment by ShadowMario** [comment]
This is a bit uncertain but your .XML file might be broken/exported wrong

**Comment by TFLTV** [comment]
could you send the contents of your XML file?
