### ISSUE TITLE
oh no its returning null NOOOO-

### ISSUE THREAD

**Issue by alternate2757** [ShadowMario/FNF-PsychEngine#14741]
### Describe your problem here.

![Screenshot 2024-05-25 173257](https://github.com/ShadowMario/FNF-PsychEngine/assets/118006859/d5daa006-1927-466b-a95a-579b158612e0)

well that happened. i was making new ratings/judgements for the game while messing with psych engine.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i edited HealthIcon.hx, Note.hx, PlayState.hx, etc.

**Comment by ThomazBrasil** [comment]
Well, that means you accidentally deleted the image file.

**Comment by alternate2757** [comment]
weird, its still here.
![Screenshot 2024-05-25 211314](https://github.com/ShadowMario/FNF-PsychEngine/assets/118006859/ae34f9e5-b680-4a74-9df3-e759bff3e552)

**Comment by TFLTV** [comment]
Please show your code.

**Comment by alternate2757** [comment]
![Screenshot 2024-05-25 215600](https://github.com/ShadowMario/FNF-PsychEngine/assets/118006859/911dda41-d7a1-4075-a342-46e869d4d237)
^ Note.hx

![Screenshot 2024-05-25 215659](https://github.com/ShadowMario/FNF-PsychEngine/assets/118006859/cf3fdced-a656-41b9-ba6f-4d1668417e18)
PlayState.hx

![Screenshot 2024-05-25 215730](https://github.com/ShadowMario/FNF-PsychEngine/assets/118006859/8618b616-9057-40de-9247-a7413b88cbe1)
Rating.hx

**Comment by ThomazBrasil** [comment]
You could also try to put it in the mods folder

**Comment by gameygu-0213** [comment]
you're putting the ratings in the wrong folder

ratings go under
assets/shared/images

**Comment by ThomazBrasil** [comment]
And check if its in assets/shared/images.

**Comment by ShadowMario** [comment]
If you are not compiling the game, then put your images inside your mod folder, like this:
`(main Psych Engine folder)/mods/My_Mod/images/epic.png`
