### ISSUE TITLE
why...

### ISSUE THREAD

**Issue by skorovodka** [ShadowMario/FNF-PsychEngine#14756]
### Describe your bug here.

I added a character to the game, but he is not in the song, or rather his sprite is not.

What should I do?
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/170819703/639f8d28-ec44-40ff-80f6-8fb3d8de026d)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i create a mod

**Comment by MonkyRr** [comment]
this isnt exactly a bug but here are 2 things that might work:
Changing the characters Stage Position
See if the spritesheet loads in editor

**Comment by TFLTV** [comment]
Another day, another unanswered issue to never be seen by people again
![6ile3r](https://github.com/ShadowMario/FNF-PsychEngine/assets/105890618/b7d6eabe-c01a-48f3-bcfd-aae185a3d346)
