### ISSUE TITLE
How to get animation offsets from characters

### ISSUE THREAD

**Issue by Unbekannnt0** [ShadowMario/FNF-PsychEngine#14750]
### Describe your problem here.

Boyfriend has multiple singing animations: left, down, up, right... 
All of these animation have a X-offset and a Y-offset, that's in the .json of boyfriend. 

**Is there a way to specifically get the offset of an animation?** 

Something like "getProperty('boyfriend.animation.curAnim.offset.x)" or "boyfriend.leftSING.offset.x" or somthing like that to get the offset seen in the character editor?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by DetectiveBaldi** [comment]
```lua
function onCreatePost()
    debugPrint(getProperty("boyfriend.animOffsets.singLEFT", true)[1]) -- X
    debugPrint(getProperty("boyfriend.animOffsets.singLEFT", true)[2]) -- Y
end
```

**Comment by Unbekannnt0** [comment]
Oh neat! Thanks!

Is there also a way to get the name of the animation in the xml as well?
