### ISSUE TITLE
CAN YOU CHANGE THE MENU WITH ALL THE STORY MODE AND FREEPLAY IN THE COMPILED VERSION

### ISSUE THREAD

**Issue by AUTISTICFNF** [ShadowMario/FNF-PsychEngine#14755]
### Describe your problem here.

I WANT TO REMASTER IT LIKE VS IMPOSTER V5

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TFLTV** [comment]
You cannot with the pre-compiled version, you need the source version so you can edit the source code.

**Comment by AUTISTICFNF** [comment]
Basically in psych engine compiled I have the folder with my inst and
voices with all the correct names and stuff but when I go to charting and
type in the song name it doesn't work it just plays the test song and I've
tried putting it in mods>mod template>My-Mod>songs
And I have also tried putting it into assets>songs
Hope u can get back to me

**Comment by TFLTV** [comment]
> Basically in psych engine compiled I have the folder with my inst and voices with all the correct names and stuff but when I go to charting and type in the song name it doesn't work it just plays the test song and I've tried putting it in mods>mod template>My-Mod>songs And I have also tried putting it into assets>songs Hope u can get back to me

Have you unzipped mod template?

**Comment by TFLTV** [comment]
Make sure you put My-Mod inside the mods folder.

**Comment by AUTISTICFNF** [comment]
Also on a side note can you atleast change the music on the main menu with
compile

**Comment by TheSquiggle** [comment]
yes, it's in assets/shared/music/freakyMenu.ogg
