### ISSUE TITLE
Character Plays All Frames

### ISSUE THREAD

**Issue by TheSquiggle** [ShadowMario/FNF-PsychEngine#14763]
### Describe your problem here.

Every time I try to add a character, no matter what I do, when I try to add an animation, it plays all the frames at once, even though the .xml and the .png are matched up and the .xml specifically says which animations are which.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by YouDevsYoupikmin** [comment]
Add it by indices instead of prefix


like on the xml file it's "NAME SINGUP 0000" -> "NAME SINGUP 0010" the indices are 0,1,2,3,4,5,6,7,8,9,10

**Comment by YouDevsYoupikmin** [comment]
Also if possible can you show the xml file?

**Comment by TheSquiggle** [comment]
<?xml version='1.0' encoding='utf-8'?>
<TextureAtlas imagePath="Orion.png">
<SubTexture name="SingUP0000" x="0" y="0" width="354" height="607" frameX="0" frameY="0" frameWidth="354" frameHeight="607" />
<SubTexture name="SingDOWN0000" x="354" y="0" width="354" height="568" frameX="0" frameY="0" frameWidth="354" frameHeight="568" />
<SubTexture name="SingDOWN0001" x="708" y="0" width="354" height="622" frameX="0" frameY="0" frameWidth="354" frameHeight="622" />
<SubTexture name="SingUP0001" x="0" y="622" width="354" height="658" frameX="0" frameY="0" frameWidth="354" frameHeight="658" />
<SubTexture name="SingLEFT0000" x="354" y="622" width="554" height="606" frameX="0" frameY="0" frameWidth="554" frameHeight="606" />
<SubTexture name="SingLEFT0001" x="908" y="622" width="538" height="634" frameX="0" frameY="0" frameWidth="538" frameHeight="634" />
<SubTexture name="SingRIGHT0000" x="0" y="1280" width="538" height="634" frameX="0" frameY="0" frameWidth="538" frameHeight="634" />
<SubTexture name="SingRIGHT0001" x="538" y="1280" width="474" height="677" frameX="0" frameY="0" frameWidth="474" frameHeight="677" />
<SubTexture name="idle0000" x="1012" y="1280" width="482" height="594" frameX="0" frameY="0" frameWidth="482" frameHeight="594" />
<SubTexture name="idle0001" x="0" y="1957" width="482" height="631" frameX="0" frameY="0" frameWidth="482" frameHeight="631" />
</TextureAtlas>

**Comment by TheSquiggle** [comment]
`<?xml version='1.0' encoding='utf-8'?>
<TextureAtlas imagePath="Orion.png">
<SubTexture name="SingUP0000" x="0" y="0" width="354" height="607" frameX="0" frameY="0" frameWidth="354" frameHeight="607" />
<SubTexture name="SingDOWN0000" x="354" y="0" width="354" height="568" frameX="0" frameY="0" frameWidth="354" frameHeight="568" />
<SubTexture name="SingDOWN0001" x="708" y="0" width="354" height="622" frameX="0" frameY="0" frameWidth="354" frameHeight="622" />
<SubTexture name="SingUP0001" x="0" y="622" width="354" height="658" frameX="0" frameY="0" frameWidth="354" frameHeight="658" />
<SubTexture name="SingLEFT0000" x="354" y="622" width="554" height="606" frameX="0" frameY="0" frameWidth="554" frameHeight="606" />
<SubTexture name="SingLEFT0001" x="908" y="622" width="538" height="634" frameX="0" frameY="0" frameWidth="538" frameHeight="634" />
<SubTexture name="SingRIGHT0000" x="0" y="1280" width="538" height="634" frameX="0" frameY="0" frameWidth="538" frameHeight="634" />
<SubTexture name="SingRIGHT0001" x="538" y="1280" width="474" height="677" frameX="0" frameY="0" frameWidth="474" frameHeight="677" />
<SubTexture name="idle0000" x="1012" y="1280" width="482" height="594" frameX="0" frameY="0" frameWidth="482" frameHeight="594" />
<SubTexture name="idle0001" x="0" y="1957" width="482" height="631" frameX="0" frameY="0" frameWidth="482" frameHeight="631" />
</TextureAtlas>
`

**Comment by YouDevsYoupikmin** [comment]
Go to animations section, choose one like SINGUP and enter the name of the animation on XML File
If it still doesn't work add a prefix before animation on xml like "BF SINGUP0000" instead of just SINGUP0000

**Comment by YouDevsYoupikmin** [comment]
Also try remake the xml file and save it as "UTF-8" instead of "UTF-16"
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/132922421/a2bd7afe-dfbd-4fbe-83d8-dd24f4c4b521)
sorry windows is set to french
