### ISSUE TITLE
(for the love of god) change source back to 0.6.3 and older

### ISSUE THREAD

**Issue by BlueAnd** [ShadowMario/FNF-PsychEngine#14769]
### What feature do you want to get added on the **base** engine?

Please change the source back to 0.6.3 old older because 0.7.X is bullshit that is fucking hard to use and a lot of us hate it!!! so please change it back!!!!!!!!!!!!!!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Cyachao** [comment]
nobody stops you from using 0.6.3

**Comment by Equinoxtic** [comment]
saying hi from the psych engine server

**Comment by GuliGobolPro** [comment]
shadow mario is stubborn. even if you answer the test correctly, you cant force him switch to old version. the source code of old version is still accessible, why not just use it instead of complaining why the latest version is so hard to use

**Comment by DetectiveBaldi** [comment]
> > shadow mario is stubborn. even if you answer the test correctly, you cant force him switch to old version. the source code of old version is still accessible, why not just use it instead of complaining why the latest version is so hard to use
> 
> I know, but there is good stuff on 0.7.X that is not on 0.6.3!

then port those features yourself, there are many people who like organized source code and there's literally no reason to revert it

**Comment by CrusherNotDrip** [comment]
> saying hi from the psych engine server

I just looked in it and this was the first thing I saw 😃

**Comment by ShadowMario** [comment]
> I know, but there is good stuff on 0.7.X that is not on 0.6.3!

Then use 0.7.x lmao, I know your ass is angry just cuz you can't steal old scripts and run them

> shadow mario is stubborn. even if you answer the test correctly, you cant force him switch to old version.

It's not even me being stubborn, it's just that it's a matter of fact that 0.7.x is much better organized, hell I've been working in mods that run on older versions of psych and it's just a visible issue between me and other homies, just check PlayState.hx alone in 0.6 and you'd understand why

**Comment by idkwhattonamethisimnevergoingtousethis** [comment]
> > shadow mario is stubborn. even if you answer the test correctly, you cant force him switch to old version. the source code of old version is still accessible, why not just use it instead of complaining why the latest version is so hard to use
> 
> I know, but there is good stuff on 0.7.X that is not on 0.6.3!

Yes that's what updating is called

**Comment by TFLTV** [comment]
> > I know, but there is good stuff on 0.7.X that is not on 0.6.3!
> 
> Then use 0.7.x lmao, I know your ass is angry just cuz you can't steal old scripts and run them
> 
> > shadow mario is stubborn. even if you answer the test correctly, you cant force him switch to old version.
> 
> It's not even me being stubborn, it's just that it's a matter of fact that 0.7.x is much better organized, hell I've been working in mods that run on older versions of psych and it's just a visible issue between me and other homies, just check PlayState.hx alone in 0.6 and you'd understand why

bro made a whole new tag for this issue LMAOOOO 😭😭💀

**Comment by ThomazBrasil** [comment]
BRO WHAT IS THAT TAG 😭

**Comment by tposejank** [comment]
> BRO WHAT IS THAT TAG 😭

Most accurate depiction of OP, isn't it?

**Comment by JordanSantiagoYT** [comment]
i love how making this issue was so dumb that shadowmario had to make a whole new tag just for this :sob:

**Comment by JordanSantiagoYT** [comment]
> > shadow mario is stubborn. even if you answer the test correctly, you cant force him switch to old version. the source code of old version is still accessible, why not just use it instead of complaining why the latest version is so hard to use
> 
> I know, but there is good stuff on 0.7.X that is not on 0.6.3!

also, if you see good stuff on 0.7.x that isn't on 0.6.3 and you want that 0.7.x stuff on 0.6.3 then.. port it, nobody's really stopping you lmao

**Comment by FinderFromMac** [comment]
lmfao the tag

**Comment by BlueAnd** [comment]
> > I know, but there is good stuff on 0.7.X that is not on 0.6.3!
> 
> Then use 0.7.x lmao, I know your ass is angry just cuz you can't steal old scripts and run them
> 
> > shadow mario is stubborn. even if you answer the test correctly, you cant force him switch to old version.
> 
> It's not even me being stubborn, it's just that it's a matter of fact that 0.7.x is much better organized, hell I've been working in mods that run on older versions of psych and it's just a visible issue between me and other homies, just check PlayState.hx alone in 0.6 and you'd understand why

I cant use it on source because you gave the source birth control since it cant give birth to the game

**Comment by CrusherNotDrip** [comment]
> I cant use it on source because you gave the source birth control since it cant give birth to the game

what is that even meant to mean 😭😭😭

**Comment by BlueAnd** [comment]
> > I cant use it on source because you gave the source birth control since it cant give birth to the game
> 
> what is that even meant to mean 😭😭😭

I’m saying that I am unable to compile it and I have tried everything to fix it but it won’t.

**Comment by CrusherNotDrip** [comment]
> I’m saying that I am unable to compile it and I have tried everything to fix it but it won’t.

oh

well i can compile it 🤑🤑🤑
