### ISSUE TITLE
PLS HELP WITH ANIMATION NOT FOUND

### ISSUE THREAD

**Issue by Justmodmaker** [ShadowMario/FNF-PsychEngine#14766]
### Describe your problem here.

i have the xml and png file on my mod template mods\My-Mod\images\characters
my psych engine shows me the same stupid error
![imagem_2024-05-27_211622538](https://github.com/ShadowMario/FNF-PsychEngine/assets/170988394/f3335b79-f913-43c2-b104-82a0c9ad0c5c)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

NOOOOOOOO

**Comment by TFLTV** [comment]
Are you sure you set the animations?
Watch a Youtube tutorial.

**Comment by Justmodmaker** [comment]
how?????????????????????????????????

**Comment by Justmodmaker** [comment]
i'm criying

**Comment by Justmodmaker** [comment]
i set the animations

**Comment by Justmodmaker** [comment]
don't work

**Comment by Justmodmaker** [comment]
i made work

**Comment by CoakyorCookie** [comment]
How? ;-;

**Comment by inneroil3** [comment]
**BRO HOW**

**Comment by CoakyorCookie** [comment]
> **BRO HOW**
If you have all your files in a folder within the mods directory, you can access it through the in-game menu. Here's how you can navigate to your mod folder:

**Open the Game Menu:**

Launch the game and navigate to the main menu where you see options like Week Editor, Chart Editor, and others.

**Navigate to Your Mod Folder:**

Look at the bottom of your screen. You should see navigation prompts indicating that you can use the left and right arrow keys.
Press the left or right arrow keys to cycle through the available mod folders.

**Select Your Mod Folder:**

Continue pressing the left or right arrow keys until you see the name of your mod folder displayed at the bottom of the screen.
Once your mod folder is selected, you can access and edit its contents using the available tools in the menu.
These steps should help you easily find and manage your mod files within the game.

This is what the navigation prompt looks like:
![Screenshot 2024-07-09 172653](https://github.com/ShadowMario/FNF-PsychEngine/assets/167979946/e375a668-94a8-46cd-a429-a2a8af8777bd)
Also it's at the bottom of the screen. Hope this helps!
