### ISSUE TITLE
Is there any form to add a luasprite in a specific part of the song

### ISSUE THREAD

**Issue by Sebasyn0se** [ShadowMario/FNF-PsychEngine#1476]
### What is your question?

I wanna change the stage to a completely black one in a specific part (for example in the 145 beat idk) is there a function to do that in lua code? Basically adding a black lua sprite in a specific part lol

**Comment by NotEpik** [comment]
What do you mean by that?

Do you mean making a stage gone like invisible?

**Comment by Ordinary3** [comment]
you can try doing this

function onCreate()
	makeLuaSprite('whitebg', 'white', 0, 0);
	addLuaSprite('whitebg', false);

	makeLuaSprite('blackbg', 'blackbg', 0, 0);
	addLuaSprite('blackbg', false);

	setProperty('whitebg.visible',true);
	setProperty('blackbg.visible',false);
end

function onStepHit()
	if curBeat == 145 then
		setProperty('whitebg.visible',false);
		setProperty('blackbg.visible',true);
	end
end

**Comment by SrtHero278** [comment]
You can detect beats with `onBeatHit` and add the lua sprite in that function.
