### ISSUE TITLE
Girlfriend incorrect layering in Week 4 !!

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#14772]
### Describe your bug here.

Girlfriend seems to be above the car in Week 4...
Not much to explain here.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/105890618/9efa0398-0ec8-4402-921e-11d1f3c02a59)

### Command Prompt/Terminal logs (if existing)

```bash
Non-existing.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Just added a character and stage in the default mods folder.

**Comment by DetectiveBaldi** [comment]
This isn't a bug, it's intentional

**Comment by ShadowMario** [comment]
We've been over that a shit load of times, I just prefer it like this

**Comment by TFLTV** [comment]
Ah hell nah, my bad guys.
