### ISSUE TITLE
How Can I Add Custom Note Types With Their Own Textures?

### ISSUE THREAD

**Issue by VideoVocoding** [ShadowMario/FNF-PsychEngine#14779]
### What is your question?

I am coding on source code currently, and i want to add a custom note type, with it's own texture, but i don't know if i did it correctly or not.

I edited Note.hx and added this:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/96500096/d717cdca-20c7-4ea1-9485-7591c54c62b1)
I have a png and an xml for my note, 
the png looks like this:
![CHEESENOTE_assets](https://github.com/ShadowMario/FNF-PsychEngine/assets/96500096/da41e536-d45f-4b29-b405-44e730c35c17)
but when i place it in the code, and then compile my game, the notes just look like this:
![Screenshot 2024-05-29 174345](https://github.com/ShadowMario/FNF-PsychEngine/assets/96500096/e9ae20fd-6dfa-4790-81be-b32137257642)
Is There a way to actually get it working?

**Comment by TFLTV** [comment]
Heres a possible lead for the RGB change . . . In the new Psych versions the RGB of notes are changed . . . it's hard to explain but it modifies the RGB of each note to the corresponding arrow/strum.

That's what's happening to your "Cheese Note" . . . Maybe there is a variable to disable this in the note type?

**Comment by LarryFrosty** [comment]
in the code add `rgbShader.enabled = false;`

**Comment by VideoVocoding** [comment]
> in the code add `rgbShader.enabled = false;`

It Worked! Thank You So Much! It Really Helps Alot!
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/96500096/deffc7c9-58d2-4aac-aef5-2b13398c64f7)
