### ISSUE TITLE
How to Change note skin with Lua!

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#14778]
### Describe your problem here.

How do you change the note skin with Lua . . . I've been looking in the source code for a while and can't really get anything...  Maybe I'm not looking hard enough 💀

Sort of just like this:
```lua
setProperty("noteStrums.image","noteSkin1");
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I'm using the compiled version from github.

**Comment by M4st3rG4m4** [comment]
function onUpdate()
	for i = 0, getProperty('unspawnNotes.length')-1 do
		setPropertyFromGroup('unspawnNotes', i, 'texture', 'noteSkins/myNOTE'); --Change texture
		setPropertyFromGroup('unspawnNotes', i, 'rgbShader.enabled', false); --RGB Shader off, set true if you want
	end
	for i = 0, getProperty('opponentStrums.length')-1 do
		setPropertyFromGroup('opponentStrums', i, 'texture', 'noteSkins/myNOTE'); --Change texture
		setPropertyFromGroup('opponentStrums', i, 'rgbShader.enabled', false); --RGB Shader off, set true if you want
	end
	for i = 0, getProperty('playerStrums.length')-1 do
		setPropertyFromGroup('playerStrums', i, 'texture', 'noteSkins/myNOTE'); --Change texture
		setPropertyFromGroup('playerStrums', i, 'rgbShader.enabled', false); --RGB Shader off, set true if you want
	end
end

I know this is shitty but is the only way i know lmao

**Comment by TFLTV** [comment]
> function onUpdate() for i = 0, getProperty('unspawnNotes.length')-1 do setPropertyFromGroup('unspawnNotes', i, 'texture', 'noteSkins/myNOTE'); --Change texture setPropertyFromGroup('unspawnNotes', i, 'rgbShader.enabled', false); --RGB Shader off, set true if you want end for i = 0, getProperty('opponentStrums.length')-1 do setPropertyFromGroup('opponentStrums', i, 'texture', 'noteSkins/myNOTE'); --Change texture setPropertyFromGroup('opponentStrums', i, 'rgbShader.enabled', false); --RGB Shader off, set true if you want end for i = 0, getProperty('playerStrums.length')-1 do setPropertyFromGroup('playerStrums', i, 'texture', 'noteSkins/myNOTE'); --Change texture setPropertyFromGroup('playerStrums', i, 'rgbShader.enabled', false); --RGB Shader off, set true if you want end end
> 
> I know this is shitty but is the only way i know lmao

I tried this, and got an error. . . Is this made for 0.7.3?
ALSO, the note texture path I set it to is "pixelUI/noteSkins/NOTE_assets"
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/105890618/85f75012-ccca-44f5-9a4d-63a3d531e773)

**Comment by TFLTV** [comment]
New info: It crashes whenever I press a note
I've looked in the source of PlayState.hx (line 2601, line 2658) and they seem to be about animations...
