### ISSUE TITLE
Songs not loading properly

### ISSUE THREAD

**Issue by OOF-PRODUCTIONS** [ShadowMario/FNF-PsychEngine#14776]
### Describe your bug here.

Whenever I load a song through the chart editor or play one that isnt base game, rather than loading the actual song it loads the previous audio file that played. I have tried looking at the charts for capitalization errors or spelling errors in the song but nothing is wrong.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not yet

**Comment by OOF-PRODUCTIONS** [comment]
The chart loads properly by the way

**Comment by OOF-PRODUCTIONS** [comment]
And along with that my stage directories wont work either no matter what I set it to. the sprites never end up loading in

**Comment by bbouldd** [comment]
hey ive actually been having a very similar problem myself for a bit! would you mind showing how you fixed the issue?
