### ISSUE TITLE
Help me!

### ISSUE THREAD

**Issue by snewwslay** [ShadowMario/FNF-PsychEngine#14774]
### Describe your bug here.

When I try to add sound in dialogue, it says:
openfl/media/Sound.hx (line 407)
backend/Paths.hx (line 442)
backend/Paths.hx (line 186)
objects/TypedAlphabet.hx (line 39)
flixel/group/FlxGroup.hx (line 144)
flixel/addons/ui/FlxUIState.hx (line 212)
backend/MusicBeatState.hx (line 81)
states/editors/DialogueEditorState.hx (line 375)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Error loading sound from file: mods/SnowandNaurey/sounds/pastelplacee.ogg
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
![Friday Night Funkin'_ Psych Engine 5_29_2024 3_32_51 PM](https://github.com/ShadowMario/FNF-PsychEngine/assets/170800572/abea9a87-8fee-496f-acf3-f40e752250a0)

### Command Prompt/Terminal logs (if existing)

```bash
...
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

**Comment by YouDevsYoupikmin** [comment]
Are you sure the mod folder is loaded?
Try replace the sound with something else in the same folder maybe it's due to the sound

**Comment by snewwslay** [comment]
> Are you sure the mod folder is loaded? Try replace the sound with something else in the same folder maybe it's due to the sound

Oh thanks, I fixed this issue
