### ISSUE TITLE
How do i change the menu?

### ISSUE THREAD

**Issue by P1nKLemonz** [ShadowMario/FNF-PsychEngine#14770]
### Describe your problem here.

I would like to change the menu to were "Story mode" "Awards" "Credits" and "Donate" Don't pop up on the main menu. I would like to keep Options, Mods, and Freeplay. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by sofyisstupid** [comment]
you can't, you would either have to code using source code or you'll have to recreate the menu in a song.

**Comment by TFLTV** [comment]
Please close this issue.
