### ISSUE TITLE
Dialogue 

### ISSUE THREAD

**Issue by Enois213** [ShadowMario/FNF-PsychEngine#14785]
### Describe your bug here.

So when I open "Playing your Dialogue (on LUA/Downloaded Build)" (This https://cdn.discordapp.com/attachments/866856727621795850/890335034786062336/script.lua)
It says "This content is no longer available."
SO HOW AM I PLAY MY DIALOGUE?!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No?

**Comment by TFLTV** [comment]
Huh, that's weird, it seems that discord has deleted the file.  I don't appear to have a copy of it, unfortunately.

**Comment by JHOSEPEMC** [comment]
local allowCountdown = false
function onStartCountdown()
	-- Block the first countdown and start a timer of 0.8 seconds to play the dialogue
	if not allowCountdown and isStoryMode and not seenCutscene then
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('dialogue', 'breakfast');
	end
end

-- Dialogue (When a dialogue is finished, it calls startCountdown again)
function onNextDialogue(count)
	-- triggered when the next dialogue line starts, 'line' starts with 1
end

function onSkipDialogue(count)
	-- triggered when you press Enter and skip a dialogue line that was still being typed, dialogue line starts with 1
end

Buscas este codigo?

**Comment by Enois213** [comment]
THANK YOU SO MUCH!!!
