### ISSUE TITLE
So i'm Having a problem with a playable character that I made

### ISSUE THREAD

**Issue by Epicfun109** [ShadowMario/FNF-PsychEngine#14781]
### Describe your problem here.

Im trying to make a simple mod and i wanted someone to take bf's place as a new main character but when i use the character file it gives me this error message and crashes 
states/editors/CharacterEditorState.hx (line 237)
states/editors/CharacterEditorState.hx (line 463)
flixel/addons/ui/FlxUIDropDownMenu.hx (line 499)
flixel/addons/ui/FlxUIDropDownMenu.hx (line 359)
flixel/ui/FlxButton.hx (line 521)
flixel/addons/ui/FlxUITypedButton.hx (line 1172)
flixel/addons/ui/FlxUIButton.hx (line 362)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)
If anyone could help it would be much appreciated
Thank you so much -Epicfun109

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by M4st3rG4m4** [comment]
> ### Describe your problem here.
> 
> Im trying to make a simple mod and i wanted someone to take bf's place as a new main character but when i use the character file it gives me this error message and crashes states/editors/CharacterEditorState.hx (line 237) states/editors/CharacterEditorState.hx (line 463) flixel/addons/ui/FlxUIDropDownMenu.hx (line 499) flixel/addons/ui/FlxUIDropDownMenu.hx (line 359) flixel/ui/FlxButton.hx (line 521) flixel/addons/ui/FlxUITypedButton.hx (line 1172) flixel/addons/ui/FlxUIButton.hx (line 362) flixel/ui/FlxButton.hx (line 507) openfl/events/EventDispatcher.hx (line 444) openfl/display/DisplayObject.hx (line 1400) If anyone could help it would be much appreciated Thank you so much -Epicfun109
> ### Are you modding a build from source or with Lua?
> 
> Source
> ### What is your build target?
> 
> Windows x64
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> 
> _No response_

I don't have much experience with Source, in other words, I'm not very good with it lol, but at least I know (from stupid things I did) that it apparently can't load character positions and some character variables.
Maybe you made a mistake about some variable or simply overlooked some important function because this:
> states/editors/CharacterEditorState.hx (line 237)
implies that this failure was loading function updateCharacterPositions()

and this:
> states/editors/CharacterEditorState.hx (line 463)
implies that this failure was loading function addCharacter()

**Comment by M4st3rG4m4** [comment]
By the way, I work with Lua and sorry for my bad English xD

**Comment by Epicfun109** [comment]
> By the way, I work with Lua and sorry for my bad English xD

It's fine thank you for the help!:D
