### ISSUE TITLE
how to make timebar on source code like this (0.4.2)

### ISSUE THREAD

**Issue by DendyGG** [ShadowMario/FNF-PsychEngine#14782]
### What is your question?

![IMG_20221203_135020](https://github.com/ShadowMario/FNF-PsychEngine/assets/90975531/759f8f20-2bfd-4c56-83e1-c696835002ed)

**Comment by Surepart** [comment]
i wanna make my timebar like that to! but on lua.

**Comment by YouDevsYoupikmin** [comment]
It's not on settings? I never used 0.4.2
You can copy the code of "timeBar" on PlayState from newer PsychEngine to your build.

**Comment by DendyGG** [comment]
> i wanna make my timebar like that to! but on lua.

function formatTime(millisecond)
    local seconds = math.floor(millisecond / 1000)

    return string.format("%01d:%02d", (seconds / 60) % 60, seconds % 60)  
end

function onUpdatePost(elapsed)
    setTextString('timeTxt', formatTime(getSongPosition() - noteOffset) .. ' / ' .. formatTime(songLength))
end

Try this
