### ISSUE TITLE
im trying to put in my charecter but it keep getting this error screen that says;

### ISSUE THREAD

**Issue by ISAAC12345672423** [ShadowMario/FNF-PsychEngine#14789]
### Describe your problem here.

why does this keep happening

![Friday Night Funkin'_ Psych Engine 5_31_2024 3_04_03 AM](https://github.com/ShadowMario/FNF-PsychEngine/assets/171326153/f69e8c60-0e00-4299-b8c7-04fd405f02da)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ISAAC12345672423** [comment]
> Can you show the png and xml?

![psychengine-windows64_d7181 zip (evaluation copy) 5_31_2024 8_51_42 AM](https://github.com/ShadowMario/FNF-PsychEngine/assets/171326153/c1b71f8c-0bca-4d6e-a1c5-b15045ec8fa3)

**Comment by TFLTV** [comment]
Are you sure you're putting the name of the XML file in the text field when pressing the "Reload Character Image" button?
Alternatively, edit the XML and make sure the image file it's referring to is correct.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/105890618/d495f9e8-866d-48d2-bd81-4ba086f30b19)

**Comment by TFLTV** [comment]
I don't know if you need to, but you should probably have the XML and PNG have the same name.

**Comment by YouDevsYoupikmin** [comment]
The xml and png should have the same name
