### ISSUE TITLE
How to add dialogues in Psych Engine version 0.7.2?

### ISSUE THREAD

**Issue by JHOSEPEMC** [ShadowMario/FNF-PsychEngine#14786]
### What is your question?

How to add dialogues in Psych Engine version 0.7.2? 

in the source code! :v

**Comment by YouDevsYoupikmin** [comment]
about dialogues it's on dialogues editor
I recommand you to use it and generate a file instead of add it to the source code it's better

**Comment by JHOSEPEMC** [comment]
I mean, how do I add the dialogue, without the .lua dialogue, that is, from the source code, how to activate the dialogue in a song?

**Comment by JHOSEPEMC** [comment]
ya descubri un modo, es un poco acojonante pero bueno,..

**Comment by LemoniadoPAPA** [comment]
como lo hiciste?

**Comment by JHOSEPEMC** [comment]
> como lo hiciste?

Aún lo quieres saber como o ya solucionaste...
para mandarte un link de block de notas para explicarte.

**Comment by LemoniadoPAPA** [comment]
Todavía no lo soluciono. Estoy usando la 1.0 pero creo que el sistema de diálogos es el mismo

**Comment by JHOSEPEMC** [comment]
> Todavía no lo soluciono. Estoy usando la 1.0 pero creo que el sistema de diálogos es el mismo

Bueno vi que no cambio el codigo del dialogo asi que:
Paso 1: Pon estas variables en tu codigo, en donde estan las variables del principio ahi.

var semendialogo:Bool = true;
var activarsemendialogo:Bool = false;

luego busca: "function startAndEnd()", y reemplaza todo eso con:
function startAndEnd()
	{
		if(!activarsemendialogo){

			activarsemendialogo = true;
		}
		if(endingSong)
			endSong();
		else
			startCountdown();
	}
	
paso 2: luego busca "public function startCountdown()" y dentro del codigo al principio pones:

if(PlayState.SONG.song == 'aqui pon el nombre de tu song' && isStoryMode && !seenCutscene){

			if(semendialogo){
				semendialogo = false;
			    
				startDialogue(DialogueBoxPsych.parseDialogue(Paths.json(songName + '/dialogue'))); /* <-- esto dejalo tal como esta.*/
				return false;
			}
		}
		if(activarsemendialogo){
		return true;}
		
		y con eso deberia funcionar, creo... , si en tu mod es de una sola cancion pues solo usa los "if" pero si son varias entonces deberias usar switch con sus cases, pero aunque igual sigue funcionando si usas los "if".

**Comment by JHOSEPEMC** [comment]
> > Todavía no lo soluciono. Estoy usando la 1.0 pero creo que el sistema de diálogos es el mismo
> 
> Bueno vi que no cambio el codigo del dialogo asi que: Paso 1: Pon estas variables en tu codigo, en donde estan las variables del principio ahi.
> 
> var semendialogo:Bool = true; var activarsemendialogo:Bool = false;
> 
> luego busca: "function startAndEnd()", y reemplaza todo eso con: function startAndEnd() { if(!activarsemendialogo){
> 
> ```
> 		activarsemendialogo = true;
> 	}
> 	if(endingSong)
> 		endSong();
> 	else
> 		startCountdown();
> }
> ```
> 
> paso 2: luego busca "public function startCountdown()" y dentro del codigo al principio pones:
> 
> if(PlayState.SONG.song == 'aqui pon el nombre de tu song' && isStoryMode && !seenCutscene){
> 
> ```
> 		if(semendialogo){
> 			semendialogo = false;
> 		    
> 			startDialogue(DialogueBoxPsych.parseDialogue(Paths.json(songName + '/dialogue'))); /* <-- esto dejalo tal como esta.*/
> 			return false;
> 		}
> 	}
> 	if(activarsemendialogo){
> 	return true;}
> 	
> 	y con eso deberia funcionar, creo... , si en tu mod es de una sola cancion pues solo usa los "if" pero si son varias entonces deberias usar switch con sus cases, pero aunque igual sigue funcionando si usas los "if".
> ```

A si y no olvides poner tu "dialogue.json" en la carpeta data de tu cancion bro.

**Comment by LemoniadoPAPA** [comment]
Graciass!
