### ISSUE TITLE
An Weird error

### ISSUE THREAD

**Issue by TheAmongUsDC2Guy** [ShadowMario/FNF-PsychEngine#14787]
### Describe your problem here.

What happened was I was making a charted song that was five mins long and then 1 hour later into the chart this happened

Uploading Friday Night Funkin'_ Psych Engine 2024-05-30 19-42-00.mp4…

so yeah uhh idk what happened

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

the only things ive done was add instrumentals and vocals to tutorial for a chart thats not released, and then 1 hour later i got an error.

**Comment by TheAmongUsDC2Guy** [comment]
oh and im not good at open source stuff soo

**Comment by TheAmongUsDC2Guy** [comment]
well i have what the file says and...

backend/MusicBeatSubstate.hx (line 121)
backend/MusicBeatSubstate.hx (line 56)
backend/MusicBeatSubstate.hx (line 45)
backend/CustomFadeTransition.hx (line 47)
flixel/FlxState.hx (line 222)
flixel/FlxState.hx (line 231)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

**Comment by TheAmongUsDC2Guy** [comment]
this is all i got from the crash message

**Comment by YouDevsYoupikmin** [comment]
Try delete every events and finish the song
Did you added events from source?

**Comment by TheAmongUsDC2Guy** [comment]
okay, so just realized 

all i had to do was change a difficulty and rechart almost half the song. otherwise, if i had saved the old chart to all the difficulties then...boom

**Comment by TheAmongUsDC2Guy** [comment]
so yea
