### ISSUE TITLE
keybind changing

### ISSUE THREAD

**Issue by fnffreaklol** [ShadowMario/FNF-PsychEngine#14784]
### Describe your problem here.

i can only change the left keybind and i cant go further down to change the other keybinds im pressing s and it doesnt work. is there another way to scroll? pls help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by HourOfEternity** [comment]
Have you tried pressing the down arrow?

**Comment by TFLTV** [comment]
S key doesn't work in options.
Have you tried pressing the down arrow?

**Comment by fnffreaklol** [comment]
> S key doesn't work in options. Have you tried pressing the down arrow?

thanks that helped me

**Comment by TFLTV** [comment]
> > S key doesn't work in options. Have you tried pressing the down arrow?
> 
> thanks that helped me

Cool.
IF your problem has been solved, please, close this issue.
