### ISSUE TITLE
Compatibility Issue with Windows 7

### ISSUE THREAD

**Issue by WindowsGod2** [ShadowMario/FNF-PsychEngine#14783]
### Describe your bug here.

I was testing my mod on previous versions of Windows to check for reverse compatibility. Upon opening the executable, I was given an error message that crashed the game. It was able to boot up briefly, but a few seconds after changing framerate, it would fail. It boots up fine on Windows 8 to 11 (64-bit).
I'm not sure where I'd have to go to fix this issue.
![vsWG2 - Win7 FAIL](https://github.com/ShadowMario/FNF-PsychEngine/assets/102393943/7d8a5db5-41cb-407c-867f-93f25851b510)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I mostly changed crap in the assets folder, only to remove or edit content to fit the theming of my mod.

**Comment by KillerAvecRage** [comment]
Why would you want to check this far? The only computers that have Windows 7 are school computers, you just have to check for Windows 11 and Windows 10

**Comment by TFLTV** [comment]
Is this version 0.7.3?  If so, I've noticed line 209 in TitleState.hx being `logoBl.frames = Paths.getSparrowAtlas('logoBumpin');`.  Does that image exist in the assets folder?  If it does not, I recommend placing something proper with that name in there.

I do not know why this error would ONLY occur on Windows 7, BUT -- it's a lead.

**Comment by TFLTV** [comment]
I don't think the line of the error saying something about line 170 in TitleState.hx means anything.  Because the line 209 is code that's in the `startIntro()` function.  Which, just for extra context, line 170 is just `startIntro();` (It triggers the function.)

**Comment by TFLTV** [comment]
Line 170 ALSO explains why it's briefly able to run for some moments ...  The application waits a few moments before triggering `startIntro()`.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/105890618/0c27a1c4-d76f-43fa-94ad-bd4783fb5164)
((I assume) the random FPS changes are the application loading the needed images, BTW.)

**Comment by DetectiveBaldi** [comment]
i don't think it's psych's responsibility to support a 14 year operating system that a very small portion of fnf's audience even uses

**Comment by TFLTV** [comment]
> i don't think it's psych's responsibility to support a 14 year operating system that a very small portion of fnf's audience even uses

Very true.

**Comment by WindowsGod2** [comment]
My plan was try port my mod on all versions of Microsoft Windows (mainly for fun).
For now I can only try out 64-bit systems (XP-11) since the 32-bit port doesn't work, and a 16-bit port would be a nightmare.
I know this bug isn't something that'd normally be asked about due to everyone using systems that are still in support.
To my understanding, this is the only place I can ask for stuff like this, so I apologize for bringing up something like this.

**Comment by TFLTV** [comment]
> My plan was try port my mod on all versions of Microsoft Windows (mainly for fun). For now I can only try out 64-bit systems (XP-11) since the 32-bit port doesn't work, and a 16-bit port would be a nightmare. I know this bug isn't something that'd normally be asked about due to everyone using systems that are still in support. To my understanding, this is the only place I can ask for stuff like this, so I apologize for bringing up something like this.

HONESTLY, I don't think anyone actually uses 32-bit, but if it's for fun you can try to port it, I guess.

**Comment by Surepart** [comment]
> Why would you want to check this far? The only computers that have Windows 7 are school computers, you just have to check for Windows 11 and Windows 10

I'm Still using win7 by the way

**Comment by M4st3rG4m4** [comment]
> > Why would you want to check this far? The only computers that have Windows 7 are school computers, you just have to check for Windows 11 and Windows 10
> 
> I'm Still using win7 by the way

I find it quite sad that Windows 7 is such an underrated system today without considering that this was by far the most important Windows for Microsoft. For my part, I have Windows 10 and Windows 7 in Dual-Boot and many times I prefer to use Windows 7 for many things

> HONESTLY, I don't think anyone actually uses 32-bit, but if it's for fun you can try to port it, I guess.

The version of Windows 7 I use is 32-bit and Psych Engine works perfectly, this is even the first time I have seen that it does not work on this system for "school computers" according to @KillerAvecRage.

By the way, before anyone comes and says anything, I have used Psych Engine v0.4.2, v0.6.3 and I am currently using and developing a mod on Psych Engine v0.7.3

**Comment by M4st3rG4m4** [comment]
It really could be a bug but to me it doesn't seem like a compatibility problem with Windows 7 (since I use 32-bit Psych Engine there and that never happened to me with a mod :v), as I see either some files are missing or it's a Graphic Drivers problem.

Note that:

>backend/Paths.hx (line 275)

That line is used when you activate Cache on GPU, do you have updated graphics drivers? And if so, does your PC support OpenGL 2.0 at least? have you tried emulating OpenGL?

>states/TitleState.hx (line 209)

That line is used when starting the intro, assuming you haven't changed TitleState you have "logoBumpin" in "assets\shared\images", try adding and also check that "gfDanceTitle" is there because if I remember correctly that thing gave me problems when modified Psych Engine v0.6.3

**Comment by WindowsGod2** [comment]
Fixed; got it to work by using an earlier version of Psych.
![vsWG2_-_Win7](https://github.com/ShadowMario/FNF-PsychEngine/assets/102393943/a633c7bb-a27d-46b1-a0dc-de2550f0ce0e)
