### ISSUE TITLE
Attempting to resetState while the current state is destroyed!!!?!?!?!?!??!?!?!?!?!

### ISSUE THREAD

**Issue by ADHD-Multiverse** [ShadowMario/FNF-PsychEngine#14797]
### Describe your bug here.

So, I always get this bug with Psych Engine 0.6.2, and I don't know how to fix it.

### Command Prompt/Terminal logs (if existing)

```bash
flixel/FlxState.hx (line 176)
flixel/util/typeLimit/NextState.hx (line 69)
flixel/FlxGame.hx (line 631)
flixel/FlxGame.hx (line 727)
flixel/FlxGame.hx (line 680)
flixel/FlxGame.hx (line 559)
openfl/events/EventDispatcher.hx (line 426)
openfl/display/DisplayObject.hx (line 1398)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, but only the images and tracks.

**Comment by RomanBear7** [comment]
You need to go to the Art file in source, and click "build_x64.bat", cause it technically wasn't fully built yet
