### ISSUE TITLE
Custom Character

### ISSUE THREAD

**Issue by Epicfun109** [ShadowMario/FNF-PsychEngine#14793]
### Describe your problem here.

im making a character with psych engine and when i put the character into the character editor its loads then when i try to load the animations it says "ERROR: No Animation Found" how do i fix this and get my character's animation to load?
any help appreciated thank you :D

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by FranciscoPlay32** [comment]
have you checked the xml of the character?. and check if the animation name is there

**Comment by bblyse001** [comment]
i'm also having this problem.
