### ISSUE TITLE
7.x (any version of the 7's) crashes when attempting to do anything

### ISSUE THREAD

**Issue by dxpperwoke** [ShadowMario/FNF-PsychEngine#14794]
### Describe your bug here.

whenever i try to open settings or i try to play a song, the game gives me a null object reference. this happens on every 7.x psych build regardless of how many mods are enabled.

when opening settings:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/85380214/425e7666-f8b8-4153-8c06-c452ab052ad1)

when starting a song:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/85380214/0dd99090-d468-417b-a7aa-9ac5d2988fe9)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope, completely fresh install.

**Comment by ShadowMario** [comment]
Some Mod you've played might've messed up your save data, try deleting the save at `%appdata%/ShadowMario/PsychEngine/`

**Comment by dxpperwoke** [comment]
i ended up deleting everything in the shadowmario folder, seems like it worked. thanks a lot!
