### ISSUE TITLE
Advanced/Better Chart Editor

### ISSUE THREAD

**Issue by TimelessPC1678** [ShadowMario/FNF-PsychEngine#14799]
### What feature do you want to get added on the **base** engine?

Alright, hear me out. Warning though, I am not good at explaning this so just stick with me ight? Ight. So the charting is fine and good and all but like, really? I feel like using your MOUSE to place the notes is really hard and i feel like that It could be better. That is why I think you should there should be an option to draft the chart by using the arrow keys (and keybinds) to chart it while the song is going. Hope I did a good explanation of doing this.

**Comment by DetectiveBaldi** [comment]
i'm pretty sure you can already do this

**Comment by TimelessPC1678** [comment]
> i'm pretty sure you can already do this

No you can't

**Comment by Average-FNF-Modder** [comment]
Yes you can actually. Go into chart editor, then go Edit>Live Input Mode, and select your preferred method (It's not turned on by default). Then whenever you press play and use these keys arrows will be placed where ever on your screen you've put the playhead (You can move it to be lower on the screen if that's useful by dragging the red part). Arrow's will be as precise as the snapping you've set your placements to at the time. Hope this helps!

**Comment by DetectiveBaldi** [comment]
> > i'm pretty sure you can already do this
> 
> No you can't

Charting > Vortex Editor (BETA) -> Press 1 - 8

**Comment by JordanSantiagoYT** [comment]
> ### What feature do you want to get added on the **base** engine?
> Alright, hear me out. Warning though, I am not good at explaning this so just stick with me ight? Ight. So the charting is fine and good and all but like, really? I feel like using your MOUSE to place the notes is really hard and i feel like that It could be better. That is why I think you should there should be an option to draft the chart by using the arrow keys (and keybinds) to chart it while the song is going. Hope I did a good explanation of doing this.

me when Vortex Editor (BETA) exists

**Comment by TimelessPC1678** [comment]
whats that?

**Comment by Average-FNF-Modder** [comment]
> whats that? Edit: I am so dumb.

In chart editor on the charting tab click the button shown. Some arrows will appear on screen and active note placing with the 1-8 keys will become active. I keep it on just cause the notes on screen help me visualize chart, and it should also help with your issue.

Hope this helps!

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/157259571/02b74102-a8cb-4cc5-b002-900ea3a7fdb6)

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/157259571/117edd0b-654b-4b82-8f08-353ff9075b3a)
