### ISSUE TITLE
Animated Menu BG

### ISSUE THREAD

**Issue by theonetruefunnismile** [ShadowMario/FNF-PsychEngine#14790]
### Describe your problem here.

I want to make an animated menu (where the story, freeplay, credits, etc etc), but I kind of suck at coding. It's like a scrolling image.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by YouDevsYoupikmin** [comment]
Due to title, Add a animation to the bg?

**Comment by theonetruefunnismile** [comment]
Uhhh how do i do that lol

**Comment by theonetruefunnismile** [comment]
> Due to title, Add a animation to the bg?

How do i do that lol

**Comment by YouDevsYoupikmin** [comment]
> > Due to title, Add a animation to the bg?
> 
> How do i do that lol

Add
		//e
		var renamethis:FlxSprite = new FlxSprite(-80);
		renamethis.frames = Paths.getSparrowAtlas('imageName', 'shared'); // shared is the folder (assets/shared/images/) remove it if it's on preload folder.
		renamethis.antialiasing = ClientPrefs.data.antialiasing;

		renamethis.animation.addByPrefix('wanim', 'anim name on xml', 24);
		renamethis.animation.play('wanim', true);
		renamethis.updateHitbox();
		add(renamethis);

to titleState.hx on "override function create()"
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/132922421/effc5dc0-691c-483f-953b-26e2385642c5)

**Comment by YouDevsYoupikmin** [comment]
Oh damn i fargot it's lua, idk if it's possible to edit mainmenu with lua
