### ISSUE TITLE
Error when going out of the Main Menu

### ISSUE THREAD

**Issue by NullGang** [ShadowMario/FNF-PsychEngine#14796]
### Describe your bug here.

When I go to some other state like optionState or FreeplayState this happens.

### Command Prompt/Terminal logs (if existing)

```bash
flixel/effects/FlxFlicker.hx (line 171)
flixel/util/FlxTimer.hx (line 205)
flixel/util/FlxTimer.hx (line 295)
flixel/FlxGame.hx (line 750)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 550)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes. I edited the main menu and a lot of files

**Comment by YouDevsYoupikmin** [comment]
Can you show the mainmenu file? At least switch states lines

**Comment by NullGang** [comment]
I think i found the error, it was some random line with a flicker that it was there for no reason lol.

> Can you show the mainmenu file? At least switch states lines
