### ISSUE TITLE
this is not a Issues but how do i add/make custom week into Psych engine and put music into it?

### ISSUE THREAD

**Issue by SaVia01** [ShadowMario/FNF-PsychEngine#148]
i just wanna make a short mod for fun but i make a New Week and put song and chart into mods now but it still didn't work did i do something wrong or i need to code too? if i need to code you can put a code down here and i will use it thank you!

**Comment by ShadowMario** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Adding-a-New-Week
