### ISSUE TITLE
My game isn't working perfectly

### ISSUE THREAD

**Issue by ItsMu-risaki** [ShadowMario/FNF-PsychEngine#14809]
### Describe your bug here.

I was playing Psych Engine - Lost My Mind but when the first event put on work it crashed the game
![Screenshot 2024-06-02 142645](https://github.com/ShadowMario/FNF-PsychEngine/assets/171506812/fba0c165-9000-4a15-85f9-0de2dc62a01a)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by TFLTV** [comment]
why did you report it here

this is a bug of the mod, not psych engine

**Comment by TabTray** [comment]
> why did you report it here
> 
> this is a bug of the mod, not psych engine

they took the "report this bug to the psych engine github" too seriously lol

**Comment by TFLTV** [comment]
> > why did you report it here
> > this is a bug of the mod, not psych engine
> 
> they took the "report this bug to the psych engine github" too seriously lol

a little _too_ seriously 💀
