### ISSUE TITLE
okay one thing

### ISSUE THREAD

**Issue by TheAmongUsDC2Guy** [ShadowMario/FNF-PsychEngine#14802]
### Describe your problem here.

so im trying to add a cutscene in the middle of a song but i keep trying and trying in chart menu but can really find a way to put a cutscene.

oh. and im trying a put a character in but all i got is the sprites and the character name. i dont know how to make an http or xml lol

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

same as last issue, put songs. and tryin to figure out how to put cutscenes in the middle of my song

**Comment by TabTray** [comment]
for cutscenes, [the wiki has a page on them](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Functions-for-Dialogues-and-Cutscenes) and [heres a video that might help](https://www.youtube.com/watch?v=hRt7oJyD5YU)

for the character, if you dont have adobe animate, you can check out the [official fnf resources github page](https://github.com/FunkinCrew/awesome-funkin-resources) for some websites you can use to automatically create a sprite sheet for you. if that isnt your style, then you can create them yourself. xmls can be opened in notepad, create a xml file with the same name and in the same location as your character's sprite sheet, right click and choose "open with...", then notepad, and put the following lines in it:
```
<?xml version="1.0" encoding="utf-8"?>
<TextureAtlas imagePath="[CHARACTER SPRITE SHEET NAME HERE].png" width="[CHARACTER SPRITE SHEET WIDTH]" height="[CHARACTER SPRITE SHEET HEIGHT]">
[in this space put the frames of your animations with the last four numbers representing a frame of the animation, as an example:
  <SubTexture name="Idle0000" x="8" y="8" width="400" height="800"/>
every frame must have the same name besides the last four numbers, incrementing by one for each frame.
you can use a selection box tool to get the x, y, width, and height.]
</TextureAtlas>
```
