### ISSUE TITLE
Uncaught Error crash

### ISSUE THREAD

**Issue by koonsun12** [ShadowMario/FNF-PsychEngine#14800]
### Describe your bug here.

DDLC vs Eddsworld
Once I reach Tom's scence its crashed immediately for literally no reason and its only happens on Tom's scence
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/171446749/490ef4c2-786f-4923-9c9b-cce885088587)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by DevonMKatYT** [comment]
I have this error too, I just added the Cuphead Sings Phantasm mod 
[PsychEngine_2024-06-01_13'15'31.txt](https://github.com/user-attachments/files/15523192/PsychEngine_2024-06-01_13.15.31.txt)
This is the crash.
