### ISSUE TITLE
compliting problem

### ISSUE THREAD

**Issue by ender69funk** [ShadowMario/FNF-PsychEngine#14807]
### Describe your bug here.

the terminal say error with file hxcpp.pch

### Command Prompt/Terminal logs (if existing)

```bash
Creating C:/Users/Lenovo/Documents/Source Codes/OTSOSONIK FUNKIN/export/release/windows/obj/obj/msvc1964-nc/__pch/haxe/hxcpp.pch...
Error: Could not create PCH
hxcpp.cpp
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TFLTV** [comment]
#10756
