### ISSUE TITLE
Crashed 3 Minutes into Delet-Edd Friends: Four Way Fracture

### ISSUE THREAD

**Issue by Hydorin** [ShadowMario/FNF-PsychEngine#14803]
### What is your question?

I have been getting this issue while playing through a song called Fandom Fracture and would like to figure out what is causing my game to crash. After passing through Sayori and Monika's phases and entering Natsuki and Tom's, the moment you press a key, the following report shows:

states/PlayState.hx (line 2658)
states/PlayState.hx (line 2601)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

I've played the mod a year or two prior, but there were no issues then. I have the exact mod link I used below as well as the current issue of Psych Engine. Please help as I just want to play this modded song again.

DDLC vs. EDDSWORLD: Fandom Fracture: https://www.mediafire.com/file/6exz76kwhcajatl/Delet-Edd+Friends.rar/file

Psych Engine GameBanana Page: https://gamebanana.com/mods/309789

Time of occurrence: 8:33-8:32
![image_2024-06-02_021917335](https://github.com/ShadowMario/FNF-PsychEngine/assets/140474176/48e5ad71-837e-42aa-b1a0-9849e24641f4)

After pressing a key, the crash report shows and the audio still plays until you click 'Ok' on the crash report which closes the app.
![image_2024-06-02_022129539](https://github.com/ShadowMario/FNF-PsychEngine/assets/140474176/5edd4530-0f10-4b4d-bb7b-cec12be1482d)

**Comment by JordanSantiagoYT** [comment]
which version of PE is this?

**Comment by Hydorin** [comment]
> which version of PE is this?

0.7.3

**Comment by JordanSantiagoYT** [comment]
your strum's noteskin xml might be invalid according to what the crashing line is

**Comment by Hydorin** [comment]
> your strum's noteskin xml might be invalid according to what the crashing line is

Sorry, I'm not familiar with FNF files or anything similar, how do I check which files are invalid and how do I replace them so that they are viable to use again?

**Comment by ShadowMario** [comment]
Old mods tend to not work properly in Psych Engine 0.7+, update the mod if there's an update available
