### ISSUE TITLE
How can I TELEPORT the camera in Psych Engine?

### ISSUE THREAD

**Issue by SuperYagoFNF** [ShadowMario/FNF-PsychEngine#14805]
### Describe your problem here.

---------English---------

Teleporting means going to the opponent's part and the player doesn't have the animation to go to the correct part.
I hope you understood.

---------Português---------

Teleportar eu to dizendo ir para a parte do oponente e do player ele não ter a animação para ir até a parte correta.
Espero que tenha intendido.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

NO - NÃO

**Comment by TFLTV** [comment]
`setProperty('camGame.scroll.x',your_new_x_cam_pos - (screenWidth / 2));` should do the trick

**Comment by TFLTV** [comment]
If you want to teleport the camera to dad then do:
```lua
setProperty('camGame.scroll.x',getProperty("dad.x")-(screenWidth / 2));
setProperty('camGame.scroll.x',getProperty("dad.y")-(screenHeight / 2));
```
should work
