### ISSUE TITLE
Lime Test Windows doesn't work

### ISSUE THREAD

**Issue by AmaroGod2** [ShadowMario/FNF-PsychEngine#14801]
### Describe your problem here.

Does somebody know how to fix it?
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/171443707/04a2ed57-2ff7-4e22-99fa-c86a38ba53c7)
Most people will just say tha i need to get visual studio 2019 and i do have it i got whatever the page said and doesn't work
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/171443707/805412c1-184d-4775-a58d-7eff006735ba)
I have three because the first one din't work so i got just all 3 but i still get the error.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by YouDevsYoupikmin** [comment]
Try unistall everything and reinstall here
https://github.com/ShadowMario/FNF-PsychEngine/blob/experimental/setup/setup-msvc-win.bat

**Comment by JosueCr4ft** [comment]
Same here. I also try the setup-msvc-win.bat but it's still.
