### ISSUE TITLE
problemas com versão

### ISSUE THREAD

**Issue by Alhoson** [ShadowMario/FNF-PsychEngine#14808]
### Describe your problem here.

ultimamente eu baixei o mod do Jason porém assim que fui jogá-lo ele disse que eu estava usando a versão 0.7.1h da psych engine. Após isso eu instalei a versão mais recente e executei para ver se ela substituía a versão antiga. porém quando eu entro no mod novamente ele continua dizendo que eu estou com a versão 0.7.1h. ai eu queria saber se tenho que excluir uma pasta especifica ou algo assim. alguém pode me ajudar? 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by DavidHyena28** [comment]
Eu acho que não tem como. a unica forma de você jogar é re-instalando o mod e carregar na tecla ESC para não atualizar


Espero que tenha ajudado!

**Comment by Alhoson** [comment]
@DavidHyena28 mas aí é paia porque fica com aquela logo lá, acho que é haxe sla.

**Comment by DavidHyena28** [comment]
@Alhoson eu sei que é.. mas acho q tem que ser assim.. se não acho que n dá

mas qualquer coisa eu procuro

**Comment by Alhoson** [comment]
@DavidHyena28 seria de grande ajuda, eu tenho procurado alguma coisa na Net sobre mas não tava achando e pensei que tinha que excluir alguma pasta específica da psych engine no meu Pc mas deu uma caçada e nada, no máximo que achei era as confirmações de tecla e tals
