### ISSUE TITLE
TeaCall not found

### ISSUE THREAD

**Issue by AcedGit** [ShadowMario/FNF-PsychEngine#14813]
### Describe your bug here.

It's saying "source/psychlua/hscript.hx:317 characters 89-96 : Type not found : TeaCall" when I run "lime test windows"

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Draconic-Hybrid** [comment]
#14303

**Comment by AcedGit** [comment]
> #14303

I know now and fixed it.

**Comment by Kwimab** [comment]
I have still problem even if i run setup-windows.bat
