### ISSUE TITLE
help i cant load a character

### ISSUE THREAD

**Issue by Dmitriiiiiiiiiii** [ShadowMario/FNF-PsychEngine#14815]
### Describe your problem here.

i am working on getting a character into the game. the icon works just fine but when it tries to load the "character" itself it just crashes

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Dmitriiiiiiiiiii** [comment]
error says

C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (Line 217)
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (Line 117)
C:\HaxeToolkit\haxe\std/haxe/Xml.hx (Line 122)
flixel/graphics/frames/FlxAtlasFrames.hx (Line 246)
Character.hx (Line 164)
PlayState.hx (Line 940)
flixel/FlxGame.hx (Line 637)
flixel/FlxGame.hx (Line 724)
flixel/FlxGame.hx (Line 677)
flixel/FlxGame.hx (Line 551)
openfl/events/EventDispatcher.hx (Line 402)
openfl/display/DisplayObject.hx (Line 1399)

Uncaught error: haxe.xml.XmlParserException: Expected node name at line 2 char 2.
Please report this error to the Github page: (link)

**Comment by YouDevsYoupikmin** [comment]
Certainly due to XML file, can you show it ?

**Comment by Dmitriiiiiiiiiii** [comment]
here it is

<?xml version="1.0" encoding="UTF-16"?>
<TextureAtlas imagePath="dmitri_Assets.png">
	<SubTexture name="down0000" x="0" y="0" width="86" height="90" frameX="-1" frameY="0" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0001" x="86" y="0" width="85" height="90" frameX="0" frameY="0" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0002" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0003" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0004" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0005" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0006" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0007" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0008" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0009" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0010" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0011" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0012" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0013" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="idle0000" x="254" y="0" width="58" height="93" frameX="0" frameY="-2" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0001" x="312" y="0" width="56" height="94" frameX="-2" frameY="-1" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0002" x="368" y="0" width="57" height="95" frameX="-2" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0003" x="425" y="0" width="55" height="94" frameX="-3" frameY="-1" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0004" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0005" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0006" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0007" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0008" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0009" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0010" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0011" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0012" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0013" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="left0000" x="54" y="95" width="68" height="94" frameX="0" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0001" x="122" y="95" width="67" height="94" frameX="-3" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0002" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0003" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0004" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0005" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0006" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0007" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0008" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0009" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0010" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0011" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0012" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0013" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="right0000" x="255" y="95" width="70" height="93" frameX="-4" frameY="-2" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0001" x="325" y="95" width="69" height="95" frameX="-2" frameY="0" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0002" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0003" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0004" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0005" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0006" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0007" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0008" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0009" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0010" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0011" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0012" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0013" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="up0000" x="0" y="190" width="83" height="93" frameX="-2" frameY="-3" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0001" x="83" y="190" width="86" height="94" frameX="-1" frameY="-1" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0002" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0003" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0004" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0005" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0006" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0007" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0008" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0009" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0010" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0011" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0012" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0013" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
</TextureAtlas>

**Comment by Dmitriiiiiiiiiii** [comment]
<?xml version="1.0" encoding="UTF-16"?>
<TextureAtlas imagePath="dmitri_Assets.png">
	<SubTexture name="down0000" x="0" y="0" width="86" height="90" frameX="-1" frameY="0" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0001" x="86" y="0" width="85" height="90" frameX="0" frameY="0" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0002" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0003" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0004" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0005" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0006" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0007" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0008" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0009" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0010" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0011" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0012" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="down0013" x="171" y="0" width="83" height="89" frameX="-1" frameY="-1" frameWidth="87" frameHeight="90"/>
	<SubTexture name="idle0000" x="254" y="0" width="58" height="93" frameX="0" frameY="-2" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0001" x="312" y="0" width="56" height="94" frameX="-2" frameY="-1" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0002" x="368" y="0" width="57" height="95" frameX="-2" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0003" x="425" y="0" width="55" height="94" frameX="-3" frameY="-1" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0004" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0005" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0006" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0007" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0008" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0009" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0010" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0011" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0012" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="idle0013" x="0" y="95" width="54" height="95" frameX="-4" frameY="0" frameWidth="59" frameHeight="95"/>
	<SubTexture name="left0000" x="54" y="95" width="68" height="94" frameX="0" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0001" x="122" y="95" width="67" height="94" frameX="-3" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0002" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0003" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0004" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0005" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0006" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0007" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0008" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0009" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0010" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0011" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0012" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="left0013" x="189" y="95" width="66" height="94" frameX="-4" frameY="0" frameWidth="70" frameHeight="94"/>
	<SubTexture name="right0000" x="255" y="95" width="70" height="93" frameX="-4" frameY="-2" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0001" x="325" y="95" width="69" height="95" frameX="-2" frameY="0" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0002" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0003" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0004" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0005" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0006" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0007" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0008" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0009" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0010" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0011" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0012" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="right0013" x="394" y="95" width="70" height="94" frameX="0" frameY="-1" frameWidth="74" frameHeight="95"/>
	<SubTexture name="up0000" x="0" y="190" width="83" height="93" frameX="-2" frameY="-3" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0001" x="83" y="190" width="86" height="94" frameX="-1" frameY="-1" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0002" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0003" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0004" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0005" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0006" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0007" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0008" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0009" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0010" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0011" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0012" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
	<SubTexture name="up0013" x="169" y="190" width="88" height="95" frameX="0" frameY="0" frameWidth="88" frameHeight="96"/>
</TextureAtlas>

**Comment by Dmitriiiiiiiiiii** [comment]
![Screenshot 2024-06-03 063832](https://github.com/ShadowMario/FNF-PsychEngine/assets/171529259/2f85c036-238d-40e1-a9a7-374c504fa47c)
![Screenshot 2024-06-03 063851](https://github.com/ShadowMario/FNF-PsychEngine/assets/171529259/f99036af-2b6d-42ff-9992-a59f9ac9b94f)

**Comment by YouDevsYoupikmin** [comment]
Try add a prefix before animation name like "BF up0000"

**Comment by YouDevsYoupikmin** [comment]
I found the problem
Edit the first line to change "UTF-16" by "UTF-8"
And when you save, choose UTF-8 instead of UTF-16

**Comment by Dmitriiiiiiiiiii** [comment]
THANK YOU it works (i spent a long time on this lol)
