### ISSUE TITLE
Why don't the rating values ​​change in the side info?

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#14819]
### Describe your problem here.

Lua Mod: https://gamebanana.com/tools/9400
Sorry i am very dumb... I can't understand why this values don't change..
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/114620759/06bd8bbe-3f7f-4747-8c5e-f760a3479a38)
I mean ratings

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TFLTV** [comment]
Could you send the script code?

**Comment by MaksPRO12667** [comment]
> Could you send the script code?

Uhhhh..... Yeaaaaah...



--Made by Acap09
--Note Hit Sidebar for OS Engine
--Branch 2 Version 2: Equalization of Both Branches
--Last updated on: 9th November 2022 3:32PM (UTC+8)

--settings
local settings = {
  --text size
  ['txt.size'] = 20,
  ['txt.basex'] = 22,
  ['txt.basey'] = 300,
  ['txt.font'] = 'VCR OSD Mono.ttf',
  ['txt.transition'] = 0.35
}

local totnotes = 0;
local tni = 0;
local tnh = 0;
local tnhp = 0;
local tsh = 0;
local sicks = 0;
local sickp = 0;
local goods = 0;
local goodp = 0;
local bads = 0;
local badp = 0;
local shits = 0;
local shitp = 0;
local perfects = 0;
local perfectp = 0;
heh = {'perc', 'tnh', 'perfect', 'sick', 'good', 'bad', 'shit', 'miss'}
heh2 = {'', 'Total Notes Hit', 'Perfects!', 'Sicks', 'Goods', 'Bads', 'Shits', 'Misses'}

--custom functions
function setColorProperty(obj, hex)
    setProperty(obj..'.color', getColorFromHex(hex))
end

--important functions, dont delete D:(
function onCreate()
	
    for n = 0,7 do
		makeLuaText(heh[n+1]..'Txt', heh2[n+1]..': 0', width, settings['txt.basex'], settings['txt.basey']+(settings['txt.size']*n))
		setTextSize(heh[n+1]..'Txt', settings['txt.size'])
		addLuaText(heh[n+1]..'Txt')
		setTextFont(heh[n+1]..'Txt', settings['txt.font'])
		setColorProperty(heh[n+1]..'Txt', heh[n+1] == 'miss' and '81FF30' or 'FFFFFF')
	end
	debugPrint(getTextFont('perfectTxt'))
end

function onCreatePost()
	for n = 0,getProperty('unspawnNotes.length') do
		if getPropertyFromGroup('unspawnNotes', n, 'mustPress') then
			totnotes = totnotes + 1;
		end
	end
end

function goodNoteHit(id, dir, type, sustain)
	tnh = tnh + 1;
	tni = tni + 1;
	if not sustain then
		if getPropertyFromGroup('notes', id, 'rating') == 'perfect' then
			perfects = perfects + 1;
			
			setColorProperty('perfectTxt', '8DFF8C')
			doTweenColor('perfectTransitionXD', 'perfectTxt', 'FFFFFF', settings['txt.transition'], 'linear')
			
			setColorProperty('tnhTxt', '8DFF8C')
			doTweenColor('tnhTransitionXD', 'tnhTxt', 'FFFFFF', settings['txt.transition'], 'linear')
		elseif getPropertyFromGroup('notes', id, 'rating') == 'sick' then
			sicks = sicks + 1;
			
			setColorProperty('sickTxt', '069420')
			doTweenColor('sickTransitionXD', 'sickTxt', 'FFFFFF', settings['txt.transition'], 'linear')
			
			setColorProperty('tnhTxt', '69F000')
			doTweenColor('tnhTransitionXD', 'tnhTxt', 'FFFFFF', settings['txt.transition'], 'linear')
		elseif getPropertyFromGroup('notes', id, 'rating') == 'good' then
			goods = goods + 1;
			
			setColorProperty('goodTxt', '00FF00')
			doTweenColor('goodTransitionXD', 'goodTxt', 'FFFFFF', settings['txt.transition'], 'linear')
			
			setColorProperty('tnhTxt', 'A6F400')
			doTweenColor('tnhTransitionXD', 'tnhTxt', 'FFFFFF', settings['txt.transition'], 'linear')
		elseif getPropertyFromGroup('notes', id, 'rating') == 'bad' then
			bads = bads + 1;
			
			setColorProperty('badTxt', 'FACE00')
			doTweenColor('badTransitionXD', 'badTxt', 'FFFFFF', settings['txt.transition'], 'linear')
			
			setColorProperty('tnhTxt', 'F5BD00')
			doTweenColor('tnhTransitionXD', 'tnhTxt', 'FFFFFF', settings['txt.transition'], 'linear')
		elseif getPropertyFromGroup('notes', id, 'rating') == 'shit' then
			shits = shits + 1;
			
			setColorProperty('shitTxt', 'FFA069')
			doTweenColor('shitTransitionXD', 'shitTxt', 'FFFFFF', settings['txt.transition'], 'linear')
			
			setColorProperty('tnhTxt', 'F52700')
			doTweenColor('tnhTransitionXD', 'tnhTxt', 'FFFFFF', settings['txt.transition'], 'linear')
		end
	end
end

function noteMiss(id, dir, type, sustain)
	tni = tni + 1;
	if not sustain then
		setColorProperty('missTxt', 'FF0000')
		doTweenColor('missTransitionXD', 'missTxt', 'FFFFFF', settings['txt.transition'], 'linear')
	end
end

function onUpdatePost(fuckThisVariable)
	--[[
	tnhp = math.floor((tnh/totnotes)*100000)/1000;
	perfectp = math.floor((perfects/tnh)*100000)/1000;
	sickp = math.floor((sicks/tnh)*100000)/1000;
	goodp = math.floor((goods/tnh)*100000)/1000;
	badp = math.floor((bads/tnh)*100000)/1000;
	shitp = math.floor((shits/tnh)*100000)/1000;
	]]
	
	setTextString('percTxt', math.floor((tni/totnotes)*100000)/1000 ..'%')
    setTextString('tnhTxt', heh2[2]..': '..tnh..'/'..totnotes--[[..' ('.. tnhp ..'%)']])
    --setTextString('tshTxt', heh2[2]..': '..tsh)
    setTextString('perfectTxt', heh2[3]..': '..perfects--[[..' ('..perfectp..'%)']])
    setTextString('sickTxt', heh2[4]..': '..sicks--[[..' ('..sickp..'%)']])
    setTextString('goodTxt', heh2[5]..': '..goods--[[..' ('..goodp..'%)']])
    setTextString('badTxt', heh2[6]..': '..bads--[[..' ('..badp..'%)']])
    setTextString('shitTxt', heh2[7]..': '..shits--[[..' ('.. shitp*100 ..'%)']])
    setTextString('missTxt', misses == 0 and (getProperty('ratingFC') ~= '' and getProperty('ratingFC') or '?') or heh2[8]..': '..misses..' ('..getProperty('ratingFC')..')')
end

**Comment by TFLTV** [comment]
> > Could you send the script code?
> 
> Uhhhh..... Yeaaaaah...
> 
> --Made by Acap09 --Note Hit Sidebar for OS Engine --Branch 2 Version 2: Equalization of Both Branches --Last updated on: 9th November 2022 3:32PM (UTC+8)
> 
> --settings local settings = { --text size ['txt.size'] = 20, ['txt.basex'] = 22, ['txt.basey'] = 300, ['txt.font'] = 'VCR OSD Mono.ttf', ['txt.transition'] = 0.35 }
> 
> local totnotes = 0; local tni = 0; local tnh = 0; local tnhp = 0; local tsh = 0; local sicks = 0; local sickp = 0; local goods = 0; local goodp = 0; local bads = 0; local badp = 0; local shits = 0; local shitp = 0; local perfects = 0; local perfectp = 0; heh = {'perc', 'tnh', 'perfect', 'sick', 'good', 'bad', 'shit', 'miss'} heh2 = {'', 'Total Notes Hit', 'Perfects!', 'Sicks', 'Goods', 'Bads', 'Shits', 'Misses'}
> 
> --custom functions function setColorProperty(obj, hex) setProperty(obj..'.color', getColorFromHex(hex)) end
> 
> --important functions, dont delete D:( function onCreate()
> 
> ```
> for n = 0,7 do
> 	makeLuaText(heh[n+1]..'Txt', heh2[n+1]..': 0', width, settings['txt.basex'], settings['txt.basey']+(settings['txt.size']*n))
> 	setTextSize(heh[n+1]..'Txt', settings['txt.size'])
> 	addLuaText(heh[n+1]..'Txt')
> 	setTextFont(heh[n+1]..'Txt', settings['txt.font'])
> 	setColorProperty(heh[n+1]..'Txt', heh[n+1] == 'miss' and '81FF30' or 'FFFFFF')
> end
> debugPrint(getTextFont('perfectTxt'))
> ```
> 
> end
> 
> function onCreatePost() for n = 0,getProperty('unspawnNotes.length') do if getPropertyFromGroup('unspawnNotes', n, 'mustPress') then totnotes = totnotes + 1; end end end
> 
> function goodNoteHit(id, dir, type, sustain) tnh = tnh + 1; tni = tni + 1; if not sustain then if getPropertyFromGroup('notes', id, 'rating') == 'perfect' then perfects = perfects + 1;
> 
> ```
> 		setColorProperty('perfectTxt', '8DFF8C')
> 		doTweenColor('perfectTransitionXD', 'perfectTxt', 'FFFFFF', settings['txt.transition'], 'linear')
> 		
> 		setColorProperty('tnhTxt', '8DFF8C')
> 		doTweenColor('tnhTransitionXD', 'tnhTxt', 'FFFFFF', settings['txt.transition'], 'linear')
> 	elseif getPropertyFromGroup('notes', id, 'rating') == 'sick' then
> 		sicks = sicks + 1;
> 		
> 		setColorProperty('sickTxt', '069420')
> 		doTweenColor('sickTransitionXD', 'sickTxt', 'FFFFFF', settings['txt.transition'], 'linear')
> 		
> 		setColorProperty('tnhTxt', '69F000')
> 		doTweenColor('tnhTransitionXD', 'tnhTxt', 'FFFFFF', settings['txt.transition'], 'linear')
> 	elseif getPropertyFromGroup('notes', id, 'rating') == 'good' then
> 		goods = goods + 1;
> 		
> 		setColorProperty('goodTxt', '00FF00')
> 		doTweenColor('goodTransitionXD', 'goodTxt', 'FFFFFF', settings['txt.transition'], 'linear')
> 		
> 		setColorProperty('tnhTxt', 'A6F400')
> 		doTweenColor('tnhTransitionXD', 'tnhTxt', 'FFFFFF', settings['txt.transition'], 'linear')
> 	elseif getPropertyFromGroup('notes', id, 'rating') == 'bad' then
> 		bads = bads + 1;
> 		
> 		setColorProperty('badTxt', 'FACE00')
> 		doTweenColor('badTransitionXD', 'badTxt', 'FFFFFF', settings['txt.transition'], 'linear')
> 		
> 		setColorProperty('tnhTxt', 'F5BD00')
> 		doTweenColor('tnhTransitionXD', 'tnhTxt', 'FFFFFF', settings['txt.transition'], 'linear')
> 	elseif getPropertyFromGroup('notes', id, 'rating') == 'shit' then
> 		shits = shits + 1;
> 		
> 		setColorProperty('shitTxt', 'FFA069')
> 		doTweenColor('shitTransitionXD', 'shitTxt', 'FFFFFF', settings['txt.transition'], 'linear')
> 		
> 		setColorProperty('tnhTxt', 'F52700')
> 		doTweenColor('tnhTransitionXD', 'tnhTxt', 'FFFFFF', settings['txt.transition'], 'linear')
> 	end
> end
> ```
> 
> end
> 
> function noteMiss(id, dir, type, sustain) tni = tni + 1; if not sustain then setColorProperty('missTxt', 'FF0000') doTweenColor('missTransitionXD', 'missTxt', 'FFFFFF', settings['txt.transition'], 'linear') end end
> 
> function onUpdatePost(fuckThisVariable) --[[ tnhp = math.floor((tnh/totnotes)*100000)/1000; perfectp = math.floor((perfects/tnh)*100000)/1000; sickp = math.floor((sicks/tnh)*100000)/1000; goodp = math.floor((goods/tnh)*100000)/1000; badp = math.floor((bads/tnh)*100000)/1000; shitp = math.floor((shits/tnh)*100000)/1000; ]]
> 
> ```
> setTextString('percTxt', math.floor((tni/totnotes)*100000)/1000 ..'%')
> setTextString('tnhTxt', heh2[2]..': '..tnh..'/'..totnotes--[[..' ('.. tnhp ..'%)']])
> --setTextString('tshTxt', heh2[2]..': '..tsh)
> setTextString('perfectTxt', heh2[3]..': '..perfects--[[..' ('..perfectp..'%)']])
> setTextString('sickTxt', heh2[4]..': '..sicks--[[..' ('..sickp..'%)']])
> setTextString('goodTxt', heh2[5]..': '..goods--[[..' ('..goodp..'%)']])
> setTextString('badTxt', heh2[6]..': '..bads--[[..' ('..badp..'%)']])
> setTextString('shitTxt', heh2[7]..': '..shits--[[..' ('.. shitp*100 ..'%)']])
> setTextString('missTxt', misses == 0 and (getProperty('ratingFC') ~= '' and getProperty('ratingFC') or '?') or heh2[8]..': '..misses..' ('..getProperty('ratingFC')..')')
> ```
> 
> end
> 
> You can view this code in this mod: https://gamebanana.com/tools/9400 I use Note Hit Sidebar b2v2

Seems to be working for me.  Could you describe your issue in detail?

**Comment by TFLTV** [comment]
OOHHHHHH i think i see ur problem, the judgement counters are not getting updated, the rating is working tho.

**Comment by TFLTV** [comment]
Try replacing the last few lines with:
```lua
setTextString('perfectTxt', tostring(getProperty("ratingsData[0].hits"))) -- I'm NOT using OS engine so just hopefully it works
setTextString('sickTxt', tostring(getProperty("ratingsData[1].hits")));
setTextString('goodTxt', tostring(getProperty("ratingsData[2].hits")))
setTextString('badTxt', tostring(getProperty("ratingsData[3].hits")))
setTextString('shitTxt',tostring(getProperty("ratingsData[4].hits")) )

**Comment by MaksPRO12667** [comment]
> Try replacing the last few lines with:
> 
> ```lua
> setTextString('perfectTxt', tostring(getProperty("ratingsData[0].hits"))) -- I'm NOT using OS engine so just hopefully it works
> setTextString('sickTxt', tostring(getProperty("ratingsData[1].hits")));
> setTextString('goodTxt', tostring(getProperty("ratingsData[2].hits")))
> setTextString('badTxt', tostring(getProperty("ratingsData[3].hits")))
> setTextString('shitTxt',tostring(getProperty("ratingsData[4].hits")) )
> ```

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/114620759/bfc7d624-3e07-4ecd-961a-eda2e6ccf951)

uhhhh....

**Comment by TFLTV** [comment]
ohhh crap my bad
```lua
setTextString('perfectTxt', heh[3]..": "..tostring(getProperty("ratingsData[0].hits"))) -- I'm NOT using OS engine so just hopefully it works
setTextString('sickTxt', heh[4]..": "..tostring(getProperty("ratingsData[1].hits")));
setTextString('goodTxt', heh[5]..":"..tostring(getProperty("ratingsData[2].hits")))
setTextString('badTxt', heh[6]..": "..tostring(getProperty("ratingsData[3].hits")))
setTextString('shitTxt',heh[7]..": "..tostring(getProperty("ratingsData[4].hits")) )
```
try that

**Comment by MaksPRO12667** [comment]
> ohhh crap my bad
> 
> ```lua
> setTextString('perfectTxt', heh2[3]..": "..tostring(getProperty("ratingsData[0].hits"))) -- I'm NOT using OS engine so just hopefully it works
> setTextString('sickTxt', heh2[4]..": "..tostring(getProperty("ratingsData[1].hits")));
> setTextString('goodTxt', heh2[5]..":"..tostring(getProperty("ratingsData[2].hits")))
> setTextString('badTxt', heh2[6]..": "..tostring(getProperty("ratingsData[3].hits")))
> setTextString('shitTxt',heh2[7]..": "..tostring(getProperty("ratingsData[4].hits")) )
> ```
> 
> try that

I just removed the 'perfect' line and it worked. Thank you very much

**Comment by TFLTV** [comment]
> > ohhh crap my bad
> > ```lua
> > setTextString('perfectTxt', heh2[3]..": "..tostring(getProperty("ratingsData[0].hits"))) -- I'm NOT using OS engine so just hopefully it works
> > setTextString('sickTxt', heh2[4]..": "..tostring(getProperty("ratingsData[1].hits")));
> > setTextString('goodTxt', heh2[5]..":"..tostring(getProperty("ratingsData[2].hits")))
> > setTextString('badTxt', heh2[6]..": "..tostring(getProperty("ratingsData[3].hits")))
> > setTextString('shitTxt',heh2[7]..": "..tostring(getProperty("ratingsData[4].hits")) )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > try that
> 
> I just removed the 'perfect' line and it worked. Thank you very much

Glad it worked!
