### ISSUE TITLE
How do I load OUTSIDE shaders using lua (or hxs)

### ISSUE THREAD

**Issue by An-Untitled-Developer** [ShadowMario/FNF-PsychEngine#14812]
### What is your question?

Self Explanatory

mmm abananannanananna

**Comment by An-Untitled-Developer** [comment]
Note that I'm using OS Engine.

**Comment by frantastic24** [comment]
This is not os engine

**Comment by An-Untitled-Developer** [comment]
OS Engine is based on Psych everything is the same (besides how it handles images)

**Comment by TFLTV** [comment]
This is not os engine

**Comment by LarryFrosty** [comment]
This is not os engine

**Comment by Vortex2Oblivion** [comment]
This is not os engine

**Comment by ShadowMario** [comment]
> OS Engine is based on Psych everything is the same (besides how it handles images)

This is not the OS Engine github, I have no responsability to help you with an outdated modification of my engine.
