### ISSUE TITLE
Stop bop object

### ISSUE THREAD

**Issue by SakraEnty** [ShadowMario/FNF-PsychEngine#14817]
### Describe your problem here.

how to stop bopping object in a certain time?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TFLTV** [comment]
`setProperty('camZoomingMult', 0);`

**Comment by TFLTV** [comment]
wym??  I don't get it.

**Comment by SakraEnty** [comment]
> wym?? I don't get it.

so, my background stage have a bopping/loop animation object in it, it's always bopping in entire song, but i want to make it stop a few second before the song end, how to do that?

**Comment by TFLTV** [comment]
> > wym?? I don't get it.
> 
> so, my background stage have a bopping/loop animation object in it, it's always bopping in entire song, but i want to make it stop a few second before the song end, how to do that?

Uhhh, try adding an animation where the object is still, and then try to do something like this:
```lua
function onStepHit()
if(curStep>=1000)then
objectPlayAnimation("animated_object","idle");
end
end
```

**Comment by TFLTV** [comment]
change `1000` to whatever the step it is you want the object animation to stop at.
