### ISSUE TITLE
You cannot access the cpp package while targeting js (for cpp.RawConstPointer)

### ISSUE THREAD

**Issue by SomeGDPerson123** [ShadowMario/FNF-PsychEngine#14814]
### Describe your problem here.

So, uh, I'm trying to compile the raw source code of Psych Engine v0.7.3 into an HTML file using lime test html5, right? I tried doing that and it ended up with this. I'm not a programmer of any sort, I don't know anything about Haxe or command prompt like at all.
![image_2024-06-02_172853097](https://github.com/ShadowMario/FNF-PsychEngine/assets/134952617/abc5d0e7-1d68-4f5a-8f5b-2b48974a49fb)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by DetectiveBaldi** [comment]
0.7 does not support HTML5

**Comment by SomeGDPerson123** [comment]
Oh... ok.
