### ISSUE TITLE
bigger splashes

### ISSUE THREAD

**Issue by shikecool64amongus69** [ShadowMario/FNF-PsychEngine#14827]
### Describe your problem here.

the splashes on all note splashes are big but the normal psych splashes it size changed its way smaller then all of the splashes is it something meant or because in old psych versions like 0.6.3 it was normal size?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

kind of but not with any scripts

**Comment by ShadowMario** [comment]
Note splashes have been slightly reduced to be less distracting in newer versions

**Comment by shikecool64amongus69** [comment]
Note splashes have been slightly reduced to be less distracting in newer versions
yeah but the new splashes are big? im trying to import the old note splashes for a flashback in a mod thats not mine but the offsets are wrong and i cant fix it
