### ISSUE TITLE
No Animation Error

### ISSUE THREAD

**Issue by seph-lol** [ShadowMario/FNF-PsychEngine#14826]
### Describe your problem here.

![Screenshot_2024-06-04_230048](https://github.com/ShadowMario/FNF-PsychEngine/assets/70780096/d8e2871d-65b4-4a32-b341-c3f5cc79ef8e)
Anytime I try to add my character it would show a Animation Not Found error. Then after awhile it just started to crash after typing the name of the sprite sheet into the image file name space
![imamnge](https://github.com/ShadowMario/FNF-PsychEngine/assets/70780096/6008f63f-2abd-43d6-80a4-694baa7c7a24)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by xxyuee** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/14815

**Comment by shikecool64amongus69** [comment]
check the xml and see if it is the characters name is not the characters name change it if it is then if you see utp-16 to utp-8

**Comment by seph-lol** [comment]
> check the xml and see if it is the characters name is not the characters name change it if it is then if you see utp-16 to utp-8

you are a savior
