### ISSUE TITLE
How to hide Misses and Rating info

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#14825]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/114620759/03014159-b124-40b6-8476-f17817672c78)
i mean how to hide this

### Are you modding a build from source or with Lua?

Source or Lua whatever

### What is your build target?

Windows x64

**Comment by xxyuee** [comment]
function onUpdate()
    setProperty("scoreTxt.visible", false)
end

**Comment by MaksPRO12667** [comment]
> function onUpdate()
> setProperty("scoreTxt.visible", false)
> end

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/114620759/bdc1278c-8d9c-40ff-8a3f-0d6d5e96c12d)
Thx but I want to be visible only 'Score'

**Comment by xxyuee** [comment]
function onUpdate()
    setTextString('scoreTxt', 'Score: '..score)
end

**Comment by MaksPRO12667** [comment]
> function onUpdate()
> setTextString('scoreTxt', 'Score: '..score)
> end

I'm glad it works thx
