### ISSUE TITLE
Access external API

### ISSUE THREAD

**Issue by Adumbidea** [ShadowMario/FNF-PsychEngine#14828]
### Describe your problem here.

Ok, so let’s say I had gone completely mad, and wanted to access and external online api via psych engine. How would I do that.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Vortex2Oblivion** [comment]
what

**Comment by Adumbidea** [comment]
an external api thing

**Comment by Vortex2Oblivion** [comment]
What does this even mean
What external api???
