### ISSUE TITLE
source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall when compiling

### ISSUE THREAD

**Issue by IdkWhatAmIDoin** [ShadowMario/FNF-PsychEngine#14829]
### Describe your bug here.

Just started using source code instead of the lua version, and when compiling first try got this error: `Type not found : TeaCall`. Can anyone help me?

### Command Prompt/Terminal logs (if existing)

```bash
PS C:\Users\miron\Documents\PsychEngineSourceCode\FNF-PsychEngine> lime test windows
source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't.

**Comment by xxyuee** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/14303

**Comment by IdkWhatAmIDoin** [comment]
Thanks

**Comment by FoolishisFoolish** [comment]
Im having the same problem is it okay if i can get help aswell

**Comment by IdkWhatAmIDoin** [comment]
in source/psychlua/HScript.hx replace all teacall with tea
