### ISSUE TITLE
help !! LUA functions not being called !!

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#14822]
### Describe your problem here.

Basically (SOME (i forgot to add this)) the LUA functions aint getting called
`function keyboardJustPressed(key)`
It don't get called.  I've also done this with a couple other functions related to the keyboard . . . they ALSO don't get called.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Haven't edited source, this is GitHub release build.

**Comment by xxyuee** [comment]
try using 
function onUpdate()
    if keyboardJustPressed('key') then
        
    end
end

**Comment by TFLTV** [comment]
> try using function onUpdate() if keyboardJustPressed('key') then -- code end end

this got me surprised bruh
