### ISSUE TITLE
Does anyone have an example of making a Pixel Stage?

### ISSUE THREAD

**Issue by FanKid** [ShadowMario/FNF-PsychEngine#1482]
### Describe your problem here.

I need help on how to how to make a Pixel Stage, but I cannot seem to understand on how to do it. Yes, the BGs I'm trying to do are basically skins from other mods. And it seems like there is nothing on the wiki on how to do it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, just trying to copy on what's in the Source Code with the default stage example.

**Comment by WaldenMD** [comment]
To make a pixel stage you have to increase the scale

scaleObject ('image', 6.0, 6.0);

and put him

setProperty('image.antialiasing', false);    #1467

A copy in lua of school that I made, in case you are interested (not exact but it works)

https://gamebanana.com/mods/336220

**Comment by FanKid** [comment]
@WaldenMD Yo, thanks! I'll be closing this issue right now. You've helped a ton!
