### ISSUE TITLE
Error with renaming a thing in the character editing.

### ISSUE THREAD

**Issue by TimRedGamerYT** [ShadowMario/FNF-PsychEngine#14821]
### Describe your bug here.

I tried switching a sprite with another, it has the same xml and sprite sheet size, there should've been no issue.

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 264)
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 117)
C:\HaxeToolkit\haxe\std/Xml.hx (line 122)
flixel/system/FlxAssets.hx (line 59)
flixel/graphics/frames/FlxAtlasFrames.hx (line 256)
states/editors/CharacterEditorState.hx (line 802)
states/editors/CharacterEditorState.hx (line 625)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: haxe.xml.XmlParserException: Expected " at line 2 char 24
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only used the most recent version, and used a sprite sheet that was already coded in from another psych copy.

**Comment by TimRedGamerYT** [comment]
btw i physically cannot do ANYTHING until this is fixed

**Comment by xxyuee** [comment]
can you send the xml file?

**Comment by TimRedGamerYT** [comment]
yeah here 
https://drive.google.com/drive/folders/1ebAY_57HDNyjlDyy8DAtdvMXnMLKR8DO?usp=sharing

**Comment by TimRedGamerYT** [comment]
i did try renaming it a bunch, the only issue is when i loaded it as the proper thing, it broke. I'm using 0.7.3

**Comment by xxyuee** [comment]
i cant access it.

**Comment by TimRedGamerYT** [comment]
Try now

**Comment by Vortex2Oblivion** [comment]
This error means there is something wrong with your xml file, did you modify it?

**Comment by TimRedGamerYT** [comment]
No, all i did was change the name in the xml from sarvente_sheet to
sarvente_xd
That is all I did.

But it wouldn't work even when i changed it to like sarvente_sheet1

**Comment by xxyuee** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/163758938/9b31b756-1ae2-4696-b2a3-23932287cc2d)
the error says you forgot a quote mark here.

**Comment by TimRedGamerYT** [comment]
HHHH THAT WAS THE WHOLE PROBLEM???? HSJSHHS IM STUPID

**Comment by xxyuee** [comment]
its okay 😭 js close the issue now

**Comment by TimRedGamerYT** [comment]
I will when i log back in on my pc later

**Comment by Vortex2Oblivion** [comment]
Btw you don't actually need to change the imagePath in an xml file since the game doesn't read that part of the xml
