### ISSUE TITLE
I can't get my lua Bullet notes to not change colors in 0.7.3.

### ISSUE THREAD

**Issue by ZaneFlynt01** [ShadowMario/FNF-PsychEngine#14820]
### Describe your problem here.

I'm working on a modpack that remixes songs, similar to B-Side or Neo, and wanted to add some bullet notes to blammed, just for a bit of extra challenge, but my keep changing to whatever color I have for the border is (RGB value B) for my notes!

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/71738041/b87ed4cb-6006-4346-9be8-12494891b10f)

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/71738041/ee3cbbad-35cb-49ef-887b-8254446dc1c5)

I've tried to do alters with the code (using ChatGPT for help because I don't know how to program as of now) but nothing I do works. How do I fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I did some small edits to the code just to change the name of the application and a few other miniscule changes like different fonts in different menus.

**Comment by TFLTV** [comment]
If this is coded in LUA, could you send the Script?

**Comment by HourOfEternity** [comment]
In your note, you need to put this code:

`for i = 0, getProperty('unspawnNotes.length')-1 do
if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'YourNoteName' then
setPropertyFromGroup('unspawnNotes', i, 'rgbShader.enabled', false);`

Hope this works for you! (If you already have the first 2 lines for the texture, just add the third line after the texture line).

**Comment by ZaneFlynt01** [comment]
> If this is coded in LUA, could you send the Script?

https://drive.google.com/file/d/1BPp5685K8KH9rwMohnhWU5dgNWnqxslH/view?usp=sharing

**Comment by ZaneFlynt01** [comment]
I figured the script out.
