### ISSUE TITLE
Error: The object does not have the property "zoom"

### ISSUE THREAD

**Issue by meandherreality** [ShadowMario/FNF-PsychEngine#14833]
### Describe your bug here.

i was playing https://gamebanana.com/mods/368674 
than it pops 
The Revenge intro crashes the game with an error.

flixel/tweens/misc/VarTween.hx (line 99)

flixel/tweens/misc/VarTween.hx (line 55)

flixel/tweens/FlxTween.hx (line 1263)

flixel/FlxGame.hx (line 750)

flixel/FlxGame.hx (line682)

flixel/FlxGame.hx (line556)

openfl/events/EventDispatcher.hx (line 402)

openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: The object does not have the property "zoom"
man wtf
somehow i really want to play this mod
help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by meandherreality** [comment]
ps : im chinese so dont hope that i can understand some deep words
im still learing!

**Comment by TFLTV** [comment]
Dude this is a mod bug not a psych engine bug.

**Comment by meandherreality** [comment]
> Dude this is a mod bug not a psych engine bug.

 k thanks
