### ISSUE TITLE
hey this is a cool feature could you add it

### ISSUE THREAD

**Issue by shikecool64amongus69** [ShadowMario/FNF-PsychEngine#14839]
### What feature do you want to get added on the **base** engine?

look could you add a system where you could convert kade engine modcharts into psych? this could really help me

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by TFLTV** [comment]
Shadow Mario is very unlikely to do this.

He gonna put the "I swear to god" tag on this if he sees it💀💀

**Comment by shikecool64amongus69** [comment]
Shadow Mario is very unlikely to do this.

He gonna put the "I swear to god" tag on this if he sees this💀💀

welp there goes this idea.
