### ISSUE TITLE
Im having some problems with the most famous error..

### ISSUE THREAD

**Issue by DavidHyena28** [ShadowMario/FNF-PsychEngine#14838]
### Describe your problem here.

Im having the same problems as other people that are:

source/psychlua/HScript.hx:291: characters 89-96 : Type not found : TeaCall

now i am on 0.7.2.. what can i do?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Just changed the TeaCall to Tea and it didnt work so i put on TeaCall again... so basiclly no

**Comment by xxyuee** [comment]
`haxelib set SScript 7.7.0`

**Comment by DavidHyena28** [comment]
> `haxelib set SScript 7.7.0`

It did not work, AT FIRST! but then i made more things and it worked... soooo thx!

**Comment by DavidHyena28** [comment]
CASEEEEEEE                       CLOSSSSSSSEEEEEEEEEEEEEEED!
