### ISSUE TITLE
FOR THE LOVE OF GOD PLEASE HELP ME

### ISSUE THREAD

**Issue by IdkWhatAmIDoin** [ShadowMario/FNF-PsychEngine#14831]
### Describe your problem here.

i just exported my psych engine source mod to normal, but WHY DOESNT IT SEE THE GOD DAMN SONGS FOLDER?! it exists. simply exists. why doesnt it FUCKING RECOGNIZE IT?!
images: ![that goddamn songs folder](https://github.com/ShadowMario/FNF-PsychEngine/assets/171820170/854f5739-7acb-4b35-a07a-e042e15e880d) with ![that goddamn error.](https://github.com/ShadowMario/FNF-PsychEngine/assets/171820170/5d7a70d9-d48d-4d65-8ddb-ec47a5043b4e)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Didnt edit anything in the songs folder, just the .hx files. The TitleState.hx, and the MainMenuState.hx.

**Comment by Vortex2Oblivion** [comment]
```haxelib set lime 8.0.2```

**Comment by IdkWhatAmIDoin** [comment]
Thanks!
