### ISSUE TITLE
Where are the Judgement/Hit Window Offsets in the FILES. (Not ingame)

### ISSUE THREAD

**Issue by An-Untitled-Developer** [ShadowMario/FNF-PsychEngine#14834]
Where in the files are the Judgement offsets (lo)
![Screenshot 2024-06-05 152829](https://github.com/FunkinCrew/Funkin/assets/118121445/d4d7fab9-3baf-455b-9323-b196aceff9f9)

(I'm too lazy to open Psych but you get the point.)

**Comment by TFLTV** [comment]
In your save file.

**Comment by An-Untitled-Developer** [comment]
Where is the save file.
