### ISSUE TITLE
How to remove week 6 and 7 dialouge/cutscene?

### ISSUE THREAD

**Issue by Randomonus** [ShadowMario/FNF-PsychEngine#14835]
### What is your question?

I'm making a mod that replaces several vanilla weeks with an edited version of said week. (playable fnf musical if someones wondering) However, during weeks 6 & 7, there is no way (as far as i'm aware) to automatically skip the cutscene/remove the starting cutscene, as even if you remove the file, it still plays. (in the case of week 6 specifically)
Is there a script/setting I could use to combat this?

**Comment by YadernyjPocoPingvin** [comment]
if you're using psych engine, then make a lua script and paste this code thingy
```
function onCreate()
	setProperty('inCutscene', false)
end
```

**Comment by Randomonus** [comment]
i already tried to do that, but it didnt work (both the original cutscene and the new one played)
