### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ruv2976** [ShadowMario/FNF-PsychEngine#14836]
### Describe your bug here.

I do not know what this is related to, but game crashes

### Command Prompt/Terminal logs (if existing)

```bash
[flixel/graphics/tile/FlxDrawQuadsItem.hx] (line 119)
[flixel/FlxCamera.hx] (line 772)
[flixel/FlxGame.hx] (line 872)
[flixel/FlxGame.hx] (line 565)
[openfl/events/EventDispatcher.hx] (line 426)
[openfl/display/DisplayObject.hx] (line 1398)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I've changed a lot of things in the code

**Comment by seegerg** [comment]
Maybe you just put a file in the wrong folder in Psych Engine. I solved this problem first by deleting one folder, then re-entering the ira and if the error remains, then I insert the one and do the same with the next one.

**Comment by Ruv2976** [comment]
> Maybe you just put a file in the wrong folder in Psych Engine. I solved this problem first by deleting one folder, then re-entering the game and if the error remains, then I insert the one and do the same with the next one.

What folders are you talking about?

**Comment by seegerg** [comment]
> > Maybe you just put a file in the wrong folder in Psych Engine. I solved this problem first by deleting one folder, then re-entering the game and if the error remains, then I insert the one and do the same with the next one.
> 
> What folders are you talking about?

the mod folders
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/168298196/a450580e-c802-4073-946c-18aea2a3931f)

**Comment by Ruv2976** [comment]
> > > Maybe you just put a file in the wrong folder in Psych Engine. I solved this problem first by deleting one folder, then re-entering the game and if the error remains, then I insert the one and do the same with the next one.
> > 
> > 
> > What folders are you talking about?
> 
> the mod folders ![image](https://private-user-images.githubusercontent.com/168298196/338100672-a450580e-c802-4073-946c-18aea2a3931f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzOTg3NDUsIm5iZiI6MTcxODM5ODQ0NSwicGF0aCI6Ii8xNjgyOTgxOTYvMzM4MTAwNjcyLWE0NTA1ODBlLWM4MDItNDA3My05NDZjLTE4YWVhMmEzOTMxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQyMDU0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWIyMjg2YTc1NzE1NGFlMmJjZWJlMjBmYzMyNmFkMjRmMGE0MTQ3NWYwMzljZWYwMmNiZTE4OTQxYjg3MDQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.va0colOFSh0DZq1jztN8HnR6Zig9mXQvBqXgmciTeJY)

the error I described above occurs in the Chart Editor (modified or raw)
