### ISSUE TITLE
Original fnf got updated

### ISSUE THREAD

**Issue by Foxy-621** [ShadowMario/FNF-PsychEngine#14840]
### What feature do you want to get added on the **base** engine?

Well, fnf original game and engine got updated, new week, new codification, new free play system, new chart system, but i beg to the creators that upgrade the engine, or will get a little obsolete, thanks for reading if the creators read this :) (I don't know so much english so.. sorry if you found ortographic errors)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by TFLTV** [comment]
Shadow Mario is already working on it.

also, you failed the test.

**Comment by Swapper1** [comment]
Good news: He will do the new Charting Editor such as Focus Camera and Camera Bop, probably the results screen and sticker transition like in the base game.
But the bad news is...
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/67173708/d63522a4-4e44-47a6-b295-a1765188e7aa)
Luckily, Rozebud is working on the new freeplay menu and other contents from the base game for FPS Plus.

**Comment by joshiayaansh** [comment]
i'm sad that now my mod will be outdated with the new everything in psych

**Comment by ShadowMario** [comment]
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/14572 and many other posts
