### ISSUE TITLE
Dialogue not working

### ISSUE THREAD

**Issue by CreepaTate** [ShadowMario/FNF-PsychEngine#14849]
### Describe your problem here.

I added dialogue, followed the entire wiki, but it doesn't load. I put it in "mods/data/<song_name>/dialogue/dialogue.json", was I supposed to put it somewhere else?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by IdkWhatAmIDoin** [comment]
Hello! Did you put the .lua script there? If no, then put it in there. Here is the link: [Click on me!](https://drive.google.com/file/d/15SMMmz5xpNompGne6S7GgEjfqEOu48xx/view?usp=sharing). I also see you created a folder called "dialogue" inside of the song folder. You need to put it with the chart files, like this: "mods/data/YOUR_SONG_NAME/dialogue.json, dialogue.lua".

**Comment by CreepaTate** [comment]
When I did that, it plays that music from the chart editor when you don't put in the name of the song in the Song tab instead of my music, and doesn't play the dialougue on top of that.
