### ISSUE TITLE
compiling issue

### ISSUE THREAD

**Issue by RedWindower** [ShadowMario/FNF-PsychEngine#14846]
### Describe your bug here.

Error: Cannot copy to "export/release/windows/bin/assets/shared/images/characters/picoSpeaker.png", is the file in use?

what do in do?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TabTray** [comment]
are you trying to overwrite the file while still having the image software or the game open? if so try closing the programs and trying again
