### ISSUE TITLE
Arrows move with background instead of HUD

### ISSUE THREAD

**Issue by MarkAwesomeness** [ShadowMario/FNF-PsychEngine#14847]
### What is your question?

I'm curious if there is any way to have the opponent or player strums move separately from the rest of the HUD and move with the background and the players. I'm using LUA

(E.X. Opponent Strums in the Silly Billy song from Hit Single - [Silly Billy Gameplay](https://www.youtube.com/watch?v=jwhSUmN5zTk))

**Comment by SrBagel** [comment]
You'd need a way to change the scroll factor of the strum line group. I'm not sure if you can change the scroll factor of groups though.

**Comment by HourOfEternity** [comment]
Here's code from a silly billy mod I just have on my psych:
function onCountdownStarted()
	runHaxeCode([[
		for (strum in game.opponentStrums)
		{
			strum.cameras = [game.camGame];
			strum.scrollFactor.set(1, 1);
			strum.scale.x = 0.9;
            strum.scale.y = 0.9;
		}
		for (note in game.unspawnNotes) 
		{
			if (!note.mustPress) {
				note.cameras = [game.camGame];
				note.scrollFactor.set(1, 1);
				note.scale.x = 0.9;
				note.scale.y = 0.9;
			if (note.isSustainNote) {
				note.scale.y = 2.5;
			} 
		}
		};
	]])
	end
Hope this works for you!

**Comment by MarkAwesomeness** [comment]
It does work, but do you know how you would move the arrows around, I tried fiddling with some things and they either didn't do anything or they just reverted all of the changes.

**Comment by HourOfEternity** [comment]
Just so happens, I have a script that modifies the opponent's arrows to show up behind the opponent. For some reason, you can just set the object order of something that doesn't exist (floor) and it will work:

function onUpdatePost(elapsed)
    setObjectOrder('floor', getObjectOrder('opponentStrums.members[1]') + 23)
    setObjectOrder('dadGroup', getObjectOrder('floor') + 12)
    setObjectOrder('gfGroup', getObjectOrder('floor') + 12)
    setObjectOrder('boyfriendGroup', getObjectOrder('floor') + 14)
end

This will set the object order of every character, not just the opponent. You should be able to put this in the same script, just put it after everything.

**Comment by Skyliner5678160** [comment]
wait so what about the position for all notes?
