### ISSUE TITLE
adding note types in 0.4.2 / 0.5 wip / github main branch version via the source code?

### ISSUE THREAD

**Issue by pakieFNF** [ShadowMario/FNF-PsychEngine#1484]
### Describe your problem here.

i cant seem to find the note type switch case in goodNoteHit for damage values, effects, etc. etc. in playstate as easily as i could in 0.4.1, dont get me wrong, the switch case is still, THERE per say, but the damage value seems like it went the way of the dodo, btw for context i generated my repro using the template feature around [this commit](https://github.com/ShadowMario/FNF-PsychEngine/commit/a26f087b074dae95ce5aa9ed993365d66582050f), i've tried looking in note.hx and chartingstate as well, but even if i search the exact damage value (0.26) it comes up with no results, so. where do i look, is it in a different .hx file? am i just dumb?

here's a comparison

0.4.1
![image](https://user-images.githubusercontent.com/30850366/143879699-8065dc2f-c2d4-4676-a1af-5e7636570c52.png)
![image](https://user-images.githubusercontent.com/30850366/143879782-f0eee70f-0510-4f42-8903-cc1d6c4a7a26.png)

0.4.2 / 0.5 WIP
![image](https://user-images.githubusercontent.com/30850366/143879905-7bca224b-d57f-4110-887c-0b8d72ee69ee.png)
![image](https://user-images.githubusercontent.com/30850366/143880015-f67e95e3-04ff-4396-b060-02e86a7164f5.png)

if this issue is confusing feel free to mark it as invalid. thank you for reading
  

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i've edited playstate, clientprefs, the option menus, and the title screen, as well as adding a new bf variant

**Comment by PDL2CGamejolt** [comment]
wait...... 0.5 WIP?!?!??!?!?!??

**Comment by pakieFNF** [comment]
> wait...... 0.5 WIP?!?!??!?!?!??

version number got changed to that recently in the gitversion.txt file lol

**Comment by KutikiPlayz** [comment]
The stuff for that is in Note.hx now I assume.  
![Screenshot (972)](https://user-images.githubusercontent.com/73810550/144102454-70b05d99-cce0-446b-b646-9eeb2b2701ba.png)
You're looking for this stuff right?

**Comment by pakieFNF** [comment]
> The stuff for that is in Note.hx now I assume. ![Screenshot (972)](https://user-images.githubusercontent.com/73810550/144102454-70b05d99-cce0-446b-b646-9eeb2b2701ba.png) You're looking for this stuff right? They probably updated the damage from 0.26 to 0.3
oh, im just dumb, thank you
