### ISSUE TITLE
Icons under health bar

### ISSUE THREAD

**Issue by AcedGit** [ShadowMario/FNF-PsychEngine#14845]
### Describe your problem here.

for some reason, some custom character icons are under the health bar. Anyone know how to fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, but I tried to edit each of the players' icon's z coords.

**Comment by AcedGit** [comment]
A couple photos of what I mean
![Screenshot 2024-06-06 184106](https://github.com/ShadowMario/FNF-PsychEngine/assets/169859564/012de8e8-46b1-43f9-b84c-7eee3205ed22)
![Screenshot 2024-06-06 184129](https://github.com/ShadowMario/FNF-PsychEngine/assets/169859564/f2e2d9b0-bd2c-41d9-8df8-4111840bd4e4)

**Comment by AcedGit** [comment]
> A couple photos of what I mean ![Screenshot 2024-06-06 184106](https://private-user-images.githubusercontent.com/169859564/337458372-012de8e8-46b1-43f9-b84c-7eee3205ed22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MTQxMzgsIm5iZiI6MTcxNzcxMzgzOCwicGF0aCI6Ii8xNjk4NTk1NjQvMzM3NDU4MzcyLTAxMmRlOGU4LTQ2YjEtNDNmOS1iODRjLTdlZWUzMjA1ZWQyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQyMjQzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDlhZmVmZTNkOTE5OWJhMmIwZGQwN2FlYjZhNjg4ZTEwZjQxODFhZDViYzk1OWE4YzI1OGEzOWQ5M2E5NTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c1YznnkVdg12POFpx936OTLPh2KpHos_DghwWZLkpf4) ![Screenshot 2024-06-06 184129](https://private-user-images.githubusercontent.com/169859564/337458376-f2e2d9b0-bd2c-41d9-8df8-4111840bd4e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MTQxMzgsIm5iZiI6MTcxNzcxMzgzOCwicGF0aCI6Ii8xNjk4NTk1NjQvMzM3NDU4Mzc2LWYyZTJkOWIwLWJkMmMtNDFkOS04ZGY4LTQxMTE4NDBiZDRlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQyMjQzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzBkNzM0OTk0NTlhMTRlNDhmNGNiZjEyMWMwNTc5OGMxODY5N2VhYjJhMDBiMDA5MWFjY2JhN2Y3NjA5MGNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nCPU63O_5cnCA3rxPnbBsxDlroM7HID-Cij6HWHIyP4)

(yes ik the mod is not mine. I'm working on fixing the jank build for the owner of the mod)

**Comment by shikecool64amongus69** [comment]
are the icons behind the healthbar or under the health bar if under open the icon png and drag it up.

**Comment by TFLTV** [comment]
> are the icons behind the healthbar or under the health bar if under open the icon png and drag it up.

behind the healthbar

**Comment by Twallis10** [comment]
switching to 0.6.3 fixes it for some weird reason

**Comment by shikecool64amongus69** [comment]
well it must be something with the healthbar
