### ISSUE TITLE
Video bitmapData unable to be loaded

### ISSUE THREAD

**Issue by Bumper3241** [ShadowMario/FNF-PsychEngine#14844]
### Describe your bug here.

Heya, trying to play a video at the start of a song. I borrowed Pink_Lemonade's script that he used in "Ski Sings the Entire Undertale Soundtrack", the script works just fine in release 0.6.3, but when updated to 0.7.3, I get an error about the game trying to "Access a null variable bitmapData".

This might be an issue with SScript updating since it does give an SScript line, so that could be a cause.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/35423009/57bba593-6759-4265-98e7-730a16fa323e)

Attached is the script in question, with its extension changed to .txt since I can't upload LUA files to Github.

[intro.txt](https://github.com/user-attachments/files/15686396/intro.txt)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No. Aside from song and character data, I've touched nothing.

**Comment by TFLTV** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/105890618/1a4f8950-15a5-4acb-9a25-f517cdc9b89c)

**Comment by Bumper3241** [comment]
> ![image](https://private-user-images.githubusercontent.com/105890618/337440327-1a4f8950-15a5-4acb-9a25-f517cdc9b89c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MDg2MTIsIm5iZiI6MTcxNzcwODMxMiwicGF0aCI6Ii8xMDU4OTA2MTgvMzM3NDQwMzI3LTFhNGY4OTUwLTE1YTUtNGFjYi05YTI1LWY1MTdjZGM5Yjg5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQyMTExNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjYyNDc4MmJkZWM3YjljOWJiOTJjODRiNDg3NDFlNjkwODk0ZGMyZWNmN2NkZmNhYzQxODE0NDExOWMzNmIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UWaoxIwLvPQPWmhUYK0aB2muC5P1rxqMHLp09SwsZ34)

Looking more for a solution, I guess "Looking for help" might've been a better category, my bad.
