### ISSUE TITLE
How do i hide only the notes?

### ISSUE THREAD

**Issue by MooseJayraffe** [ShadowMario/FNF-PsychEngine#14857]
### Describe your problem here.

Basically, im making a song that in the middle of it, it triggers a video event that is on the hud layer. at certain points of the video the notes would show and at other points the notes would hide again. I need it to have a smooth animation too, basically a tween. I've tried to hide the HUD but obviously, that also hides the video which i dont want.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by disProblematik** [comment]
local Tag = 0
function onEvent(name, v1) --Calls once event is triggered.
    if name == "your-event-name-here" then --Checks if the event = This event.
        noteTweenAlpha(Tag, 0,  0, v1, "sineInOut")
        Tag = Tag + 1
        noteTweenAlpha(Tag, 1,  0, v1, "sineInOut")
        Tag = Tag + 1
        noteTweenAlpha(Tag, 2,  0, v1, "sineInOut")
        Tag = Tag + 1
        noteTweenAlpha(Tag, 3,  0, v1, "sineInOut")
        Tag = Tag + 1
        noteTweenAlpha(Tag, 4,  0, v1, "sineInOut")
        Tag = Tag + 1
        noteTweenAlpha(Tag, 5,  0, v1, "sineInOut")
        Tag = Tag + 1
        noteTweenAlpha(Tag, 6,  0, v1, "sineInOut")
        Tag = Tag + 1
        noteTweenAlpha(Tag, 7,  0, v1, "sineInOut")
        Tag = Tag + 1

       -- the second value on noteTweenAlpha() is the note to hide. 0 - 3 are opponent's notes. 4 - 7 are player's notes.
       -- value1 of event is the duration of hiding.
       -- to show them again, change the third value of noteTweenAlpha() to 1. i hope this helps


end
end

**Comment by frantastic24** [comment]
`v1` is a string
Also `for` loop??
