### ISSUE TITLE
Uh-oh 

### ISSUE THREAD

**Issue by Dzmitry1234** [ShadowMario/FNF-PsychEngine#14851]
### Describe your bug here.

![IMG_20240526_212526](https://github.com/ShadowMario/FNF-PsychEngine/assets/171375849/a4a63456-e012-463a-b921-5b668ab2373c)

### Command Prompt/Terminal logs (if existing)

```bash
openfl/media/Sound.hx (line 407)
backend/Paths.hx (line 442)
states/editors/ChartingState.hx (line 1438)
states/editors/ChartingState.hx (line 418)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Error loading sound from file: mods/DomashneeZadanie/songs//kolhoz/Voices.ogg
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-Psych…

> Crash Handler written by: sqirra-rng

Hi hello. I've tried to chart, but every time I write a song title, I always get this error.

What to do? Take off pants and run?


I hope this message went to you and not to the twitter admin, for example. Because I'm the first time use this)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Like mod... You know?

**Comment by TFLTV** [comment]
uhh thats a weird path in the uncaught error part ("mods/DomashneeZadanie/songs//kolhoz/Voices.ogg")

wait did you put a / in the song name 💀

**Comment by Dzmitry1234** [comment]
No I didn't put /.


God fucking keyboard... This is the fifth time my phone has stopped being a stove, I can now write normally.....

So that's it, what's wrong?

**Comment by Dzmitry1234** [comment]
Well I guess that's it. I found the impossible glitch/hack or something.

And probably everyone forget about me lol.

![xGNXRmgrZkM.jpg](https://github.com/ShadowMario/FNF-PsychEngine/assets/171375849/2a43bac1-226a-47cb-a0cb-92da58863116)


Time to get back to work

**Comment by TFLTV** [comment]
> Well I guess that's it. I found the impossible glitch/hack or something.
> 
> And probably everyone forget about me lol.
> 
> Time to get back to work

You got it to work?

**Comment by TFLTV** [comment]
Oh, i see, you didn't

**Comment by Dzmitry1234** [comment]
I experimented and I think I found the cause.

The engine itself add /. No matter what I write, the result is the same.

And what to do about it I have no idea. I can at most![IMG_20240609_211209.jpg](https://github.com/ShadowMario/FNF-PsychEngine/assets/171375849/e902d2fa-93c0-4545-b836-c7f32fc15543)

![IMG_20240610_211736.jpg](https://github.com/ShadowMario/FNF-PsychEngine/assets/171375849/8c45bb12-b833-49fb-819e-ff70cf1d69d1)

**Comment by TFLTV** [comment]
> I experimented and I think I found the cause.
> 
> The engine itself add /. No matter what I write, the result is the same.
> 
> And what to do about it I have no idea. I can at most cry about it
> 
> ![IMG_20240609_211209.jpg](https://private-user-images.githubusercontent.com/171375849/338314606-e902d2fa-93c0-4545-b836-c7f32fc15543.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNDkxMzMsIm5iZiI6MTcxODA0ODgzMywicGF0aCI6Ii8xNzEzNzU4NDkvMzM4MzE0NjA2LWU5MDJkMmZhLTkzYzAtNDU0NS1iODM2LWM3ZjMyZmMxNTU0My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxOTQ3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTlkNjI1MWVlODIyNDM3NmU4Yzc2YTk0MzVmNzhjNWU2Njc4Nzc2M2NhOGM4Yzk0NzRjOGVmMzE4MTQzZDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3T-WlWfiDY5tcCSZskVZiivVHckKe__Q-XGY41XCwDg)
> 
> ![IMG_20240610_211736.jpg](https://private-user-images.githubusercontent.com/171375849/338314607-8c45bb12-b833-49fb-819e-ff70cf1d69d1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNDkxMzMsIm5iZiI6MTcxODA0ODgzMywicGF0aCI6Ii8xNzEzNzU4NDkvMzM4MzE0NjA3LThjNDViYjEyLWI4MzMtNDlmYi04MTllLWZmNzBjZjFkNjlkMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxOTQ3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODMwODdmYmZjZWVkMDZlYzEyNDc5MDM3MGQ1ODQ5NWFhM2Y1NjI1NDMwZjBjZjE0MTM3Mjc0Yzc2NTQ2YzAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sTzudnaeXCTH9wdLTWCuHAA1NGPZdbOVEbP2v_Nb8jg)

Honestly i have no idea why this is happening

**Comment by Dzmitry1234** [comment]
@![wUdTyYTSFfI.jpg](https://github.com/ShadowMario/FNF-PsychEngine/assets/171375849/1403c241-2a0f-4fdb-a31b-fa7360dea16e)

 Well, then let's summon the others almighty gods (the creators of this engine) and find out

**Comment by Dzmitry1234** [comment]
@ShadowMario MEDIC!

**Comment by TFLTV** [comment]
> @ShadowMario MEDIC!

ShadowMario has mention notifs off.

**Comment by Dzmitry1234** [comment]
So what should I do? Forget about fnf mod?(

Sad

![cbQ3_zOD8eo.jpg](https://github.com/ShadowMario/FNF-PsychEngine/assets/171375849/8e7e0f25-1c6a-46f3-ba53-a2ffd380335f)

**Comment by FinderFromMac** [comment]
The .ogg file might be corrupted.

**Comment by FinderFromMac** [comment]
@Dzmitry1234 The .ogg file might be corrupted

**Comment by Dzmitry1234** [comment]
> @Dzmitry1234 The .ogg file might be corrupted

Is it?

Have you ever read all? For some reason file make second /

It probably means I need recode engine)

**Comment by FinderFromMac** [comment]
> > @Dzmitry1234 The .ogg file might be corrupted
> 
> Is it?
> 
> Have you ever read all? For some reason file make second /
> 
> It probably means I need recode engine)

It's normal that it makes a second "/"

The engine doesn't read it as "mod//song/Voices.ogg" but in the crash handler it writes it with an extra "/"

**Comment by Dzmitry1234** [comment]
> > > @Dzmitry1234 The .ogg file might be corrupted
> > 
> > Is it?
> > 
> > Have you ever read all? For some reason file make second /
> > 
> > It probably means I need recode engine)
> 
> It's normal that it makes a second "/"
> 
> The engine doesn't read it as "mod/songs//songname/Voices.ogg" but in the crash handler it writes it with an extra "/"

I'm back, had some business.

So... What should I do with it? Recode or use new engine?

**Comment by FinderFromMac** [comment]
I think it's best if you send me the mod zip file to test it?

**Comment by FinderFromMac** [comment]
Also, @Dzmitry1234  if you are modding, use a clean version of the engine

**Comment by Dzmitry1234** [comment]
[DomashneeZadanie.zip](https://github.com/user-attachments/files/16114885/DomashneeZadanie.zip)

If I also need show engie(psych), pls say.

**Comment by Dzmitry1234** [comment]
> Also, @Dzmitry1234 if you are modding, use a clean version of the engine

Here...?

**Comment by FinderFromMac** [comment]
> > Also, @Dzmitry1234 if you are modding, use a clean version of the engine
> 
> 
> 
> Here...?

Oh ok

**Comment by FinderFromMac** [comment]
> [DomashneeZadanie.zip](https://github.com/user-attachments/files/16114885/DomashneeZadanie.zip)
> 
> 
> 
> If I also need show engie(psych), pls say.

Show it.

**Comment by FinderFromMac** [comment]
"It appears that the song doesn't have any inst.ogg or voices.ogg! Try fixing its name in weeks/week 9"
This has been popped up by the JS engine's anti-crash tool in free play, even in Story mode, it crashes

**Comment by FinderFromMac** [comment]
#14982 is also having a similar issue, but with the vocals

**Comment by Dzmitry1234** [comment]
> "It appears that the song doesn't have any inst.ogg or voices.ogg! Try fixing its name in weeks/week 9"
> This has been popped up by the JS engine's anti-crash tool in free play, even in Story mode, it crashes
> EDIT: I forgot to add the crash.txt file
> 
> C:\hostedtoolcache\windows\haxe\4.2.5\x64\std/cpp/_std/sys/io/File.hx (Line 30)
> Song.hx (Line 137)
> StoryMenuState.hx (Line 326)
> StoryMenuState.hx (Line 255)
> flixel/FlxState.hx (Line 239)
> flixel/FlxGame.hx (Line 749)
> flixel/FlxGame.hx (Line 679)
> flixel/FlxGame.hx (Line 558)
> openfl/events/EventDispatcher.hx (Line 426)
> openfl/display/DisplayObject.hx (Line 1398)
> 
> Uncaught Error: [file_contents,assets/data/glory-hole/glory-hole-hard.json]

Uh-huh.

But I added "z"(without song) & "v"(with song) in folder songs. And what do you mean "Try fixing its name in weeks/week 9"?
I'm must put songs in the "weeks" folder?

**Comment by FinderFromMac** [comment]
I re-exported both of the songs in Audacity, then replaced the old .ogg files with the new ones and it loaded the audio without crashing

**Comment by FinderFromMac** [comment]
the json file was broken

**Comment by FinderFromMac** [comment]
SEVERAL ISSUES
- in data folder, The json is named "cocoa-hard" this is causing a major   conflict between the actual cocoa song and the mod's data folder, (I renamed it "kolhoz", took out of its folder that was inside, it's not data)
- testing it in JS engine, when entering the song name "kolhoz" and clicking the reload json button, the anti-crash tool says that it's not detected (possibly broken)
- also, the kolhoz.json file is only 1 line, this causes the engine might not to read properly the data inside the JSON (rarely but not 100% always)
-Glory hole, I ate grandad, recursion and dolboed DO NOT EXITST!

I re-exported the Inst.ogg and voices.ogg files in Audacity, then replaced the old ogg files with the re exported ones, it actually worked!

Sadly, the json file was invalid, I had to delete it

**Comment by Dzmitry1234** [comment]
> In the data folder, the JSON is named "cocoa-hard" This is causing a major conflict between the actual cocoa song and the mod's data folder, (I renamed it "kolhoz")
> 
> I re-exported the Inst.ogg and voices.ogg files in Audacity, then replaced the old Ogg files with the re exported ones and it fixed the issue

I have an idea.

I'll just delete all weeks(1-7) and will be happy end :D


And yes, do I copy whole code(that you wrote) in Haxe or another program?

**Comment by FinderFromMac** [comment]
The code, no

**Comment by Dzmitry1234** [comment]
> The code, no

Okai

Thanks for help :D

**Comment by FinderFromMac** [comment]
> > The code, no
> 
> Okai
> 
> Thanks for help :D

Np
