### ISSUE TITLE
Help !! I don’t know what this mean

### ISSUE THREAD

**Issue by fnfresprited** [ShadowMario/FNF-PsychEngine#14855]
### Describe your bug here.

Im making a mod and this random haxe icon showed up on my story mode so when I scrolled to it it crashed my game and said 

states/StoryMenuState.hx (line 439)
states/StoryMenuState.hx (line 427)
states/StoryMenuState.hx (line 209)
flixel/FIxState.hx (line 222)
flixel/FIxGame.hx (line 752)
flixel/FIxGame.hx (line 682)
flixel/FixGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444) openfl/display/DisplayObject.hx (line 1400)
Uncaught Error: Null Object Referencer
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine.
≥ Crash Handler written by: squra-rng

### Command Prompt/Terminal logs (if existing)

```bash
states/StoryMenuState.hx (line 439)
states/StoryMenuState.hx (line 427)
states/StoryMenuState.hx (line 209)
flixel/FIxState.hx (line 222)
flixel/FIxGame.hx (line 752)
flixel/FIxGame.hx (line 682)
flixel/FixGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444) openfl/display/DisplayObject.hx (line 1400)
Uncaught Error: Null Object Referencer
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine.
≥ Crash Handler written by: squra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I think I saved a week and it showed up .

**Comment by DoingYourGirl5** [comment]
show your week file
