### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by szepim** [ShadowMario/FNF-PsychEngine#14852]
### Describe your problem here.

![error](https://github.com/ShadowMario/FNF-PsychEngine/assets/172045732/1054d02e-36af-4ff5-bdd4-c5fc6fa7cae9)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Only in the HScript.hx the TeaCall to Tea

**Comment by xxyuee** [comment]
`haxelib remove linc_luajit`
`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit`

**Comment by szepim** [comment]
> `haxelib remove linc_luajit` `haxelib git linc_luajit https://github.com/superpowers04/linc_luajit`
It worked thanks!
