### ISSUE TITLE
Trying to make if health is 30 then set it to 60

### ISSUE THREAD

**Issue by IdkWhatAmIDoin** [ShadowMario/FNF-PsychEngine#14856]
### Describe your problem here.

Hello. I am trying to do a script that if the player's health is 30, it sets it to 60. But it doesnt work. Can someone help me?

`function opponentNoteHit()
    health = getProperty('health')
    if health == 30 then
        setProperty(health, 60);
    end
end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by xxyuee** [comment]
function onUpdate()
    -- health ranges from 0 to 2.
    if getProperty('health') <= 0.6 then 
        setProperty('health', 1.2); 
    end
end

**Comment by IdkWhatAmIDoin** [comment]
THANKS
