### ISSUE TITLE
Animation error

### ISSUE THREAD

**Issue by Tartiroom** [ShadowMario/FNF-PsychEngine#14867]
### Describe your problem here.

So i've been using psych engine and wanted to add my custom chracter, so, like any normal being, i pasted my xml file and my spritesheet into: My-Mod - images - characters.

for the .json file i pasted a dad.json file in characters and renamed it with my custom character.

then i go to character editor in psych engine and add the name of the character but it give an error.

Please help me fixing this.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by YadernyjPocoPingvin** [comment]
try to use psych engine 0.6.3

**Comment by Tartiroom** [comment]
> try to use psych engine 0.6.3

i tried it and it and it actually kinda worked on the character editor, now i still didn't tested it in game but i'll update you on it, thanks!
