### ISSUE TITLE
outlines in blammed

### ISSUE THREAD

**Issue by ObjectShowAnimations** [ShadowMario/FNF-PsychEngine#14865]
### What feature do you want to get added on the **base** engine?

Add outlines for Pico, BF, and GF in Blammed.
![bfBlammed](https://github.com/ShadowMario/FNF-PsychEngine/assets/101996767/5e2cc752-a92c-495b-a588-fe55972130b7)
![gfBlammed](https://github.com/ShadowMario/FNF-PsychEngine/assets/101996767/43b247a5-6aed-419b-92a2-996cf2a41a89)
![picoBlammed](https://github.com/ShadowMario/FNF-PsychEngine/assets/101996767/b6610af0-7620-4d85-ba4b-3f71651eb9e4)
![blammed characters](https://github.com/ShadowMario/FNF-PsychEngine/assets/101996767/e261ee2b-2d59-4a24-a59f-63a6353e4deb)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by Vortex2Oblivion** [comment]
This isn't Yoshicrafter engine

**Comment by CrusherNotDrip** [comment]
Failed the test

**Comment by CrusherNotDrip** [comment]
> what does the outline even do

its just an effect that makes it look a little cooler

**Comment by ShadowMario** [comment]
I'm not interested in this
