### ISSUE TITLE
Fix compiling psych engine 0.7.2

### ISSUE THREAD

**Issue by YadernyjPocoPingvin** [ShadowMario/FNF-PsychEngine#14868]
### Describe your problem here.

when typing lime test windows in command prompt, it gives me this error:

```
source/states/PlayState.hx:36: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
source/psychlua/FunkinLua.hx:15: characters 8-46 : Type not found : flixel.addons.display.FlxRuntimeShader
H:/haxelib/flixel-addons/2,11,0/flixel/addons/transition/FlxTransitionableState.hx:81: lines 81-90 : Warning : switchTo is deprecated, use startOutro
source/states/PlayState.hx:3472: characters 51-67 : Type not found : FlxRuntimeShader
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by YadernyjPocoPingvin** [comment]
i forgot to mention that i installed all haxe libraries and i set correct versions

**Comment by Vortex2Oblivion** [comment]
You have very outdated libraries update them with ```haxelib update```

**Comment by ShadowMario** [comment]
Your flixel-addons seems to be out of date
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/44785097/9c11db44-529a-462a-be7a-d5de101e2baf)
