### ISSUE TITLE
song doesn't work

### ISSUE THREAD

**Issue by Tartiroom** [ShadowMario/FNF-PsychEngine#14869]
### Describe your problem here.

i added my inst and voices in my folder and when i load it in chart it doesn't work, i also tried to reload the .json file but it makes my game crash, by the way i'm using an older version of psych engine

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by CoakyorCookie** [comment]
which version of psych engine did you use?

**Comment by Tartiroom** [comment]
> which version of psych engine did you use?

1.6.3
