### ISSUE TITLE
Can't add credits

### ISSUE THREAD

**Issue by Leanzd** [ShadowMario/FNF-PsychEngine#14862]
### Describe your problem here.

I created the .txt file in mods/data and put the icons in mods/images/credits but credits won't appear (yes, I also tried on Windows)
![Captura de pantalla de 2024-06-08 19-28-35](https://github.com/ShadowMario/FNF-PsychEngine/assets/142759188/993d6b37-e196-4df0-87ec-4851d772db03)
![Captura de pantalla de 2024-06-08 19-26-19](https://github.com/ShadowMario/FNF-PsychEngine/assets/142759188/10945247-469a-41c2-85d5-ab81c1124c83)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by DoingYourGirl5** [comment]
homie it must got something to do wit your file location

**Comment by frantastic24** [comment]
Credits only work in modpacks
