### ISSUE TITLE
hxCodec - LibVLC Causing compiling error - Steam Deck

### ISSUE THREAD

**Issue by gameygu-0213** [ShadowMario/FNF-PsychEngine#14870]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/73309364/85350058-dbe2-49cd-82fe-0158439da259)
so basically trying to compile causes it to give me this error upon it attempting to make the executable.

i don't know why VLC is giving this error, nor do i know any fixes for this use case.

if it helps at all, im using Psych 0.7.1h.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i added/changed several states. but it compiles in windows just fine

**Comment by brusakas** [comment]
set hxcodec to 2.5.1
