### ISSUE TITLE
i cant compile psych 0.5.2h :(

### ISSUE THREAD

**Issue by miss-thavel** [ShadowMario/FNF-PsychEngine#14875]
### Describe your problem here.

it gives me this warning : 
C:/HaxeToolkit/haxe/lib/discord_rpc/1,0,0/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
source/Alphabet.hx:200: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:143: characters 13-21 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/Main.hx:78: characters 61-65 : Float should be Int
source/Main.hx:78: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:78: characters 61-65 : ... For function argument 'child'
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
source/PlayState.hx:84: characters 40-48 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:122: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:200: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:242: characters 28-36 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:27: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:84: characters 68-76 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:1370: characters 18-26 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:1404: characters 18-26 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:64: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:339: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:341: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:498: characters 22-30 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1787: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1789: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1792: characters 27-35 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:1275: characters 16-24 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:39: characters 13-21 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:109: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:111: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/TitleState.hx:653: characters 15-23 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CrusherNotDrip** [comment]
0.5.2h isnt support no more

**Comment by ShadowMario** [comment]
0.5.2h is way too old and isn't supported since july 2023

**Comment by miss-thavel** [comment]
i'll compile 0.6.3 then
