### ISSUE TITLE
Cant start a song in psych engine 0.6.3

### ISSUE THREAD

**Issue by IdkWhatAmIDoin** [ShadowMario/FNF-PsychEngine#14876]
### Describe your problem here.

Hello everyone, im writing this to get help. I just replaced the notes in psych engine, but when launching a song it crashes. Here are the logs: `C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 318)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 96)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
StageData.hx (line 91)
StageData.hx (line 63)
Song.hx (line 133)
FreeplayState.hx (line 371)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid char 34 at position 47
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng`
Can someone help me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

edited note images & xmls (starling)

**Comment by ShadowMario** [comment]
0.6.3 is not supported anymore since December 2023
