### ISSUE TITLE
Menu.json 

### ISSUE THREAD

**Issue by Hhhxdjejjd** [ShadowMario/FNF-PsychEngine#14871]
### What feature do you want to get added on the **base** engine?

If possible could you add a menu.json file i feel like it would make the non source version more modable i understand if you dont want to or cant do this

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by TFLTV** [comment]
I think I know what you mean . . . A custom menu layout by a json file?
I mean, that would be cool, should work, BUT also wont be too surprised if this is rejected
i kinda like this idea, kinda unnecessary tho but sure

**Comment by ShadowMario** [comment]
I've been saying this since 2022 but I'm not going to add custom menus, it makes the workflow much worse for Source mods
