### ISSUE TITLE
Null Object Reference Confusion

### ISSUE THREAD

**Issue by crafty453** [ShadowMario/FNF-PsychEngine#14887]
### Describe your bug here.

I don't exactly know what causes this to trigger, but it's starting to annoy me. You can also check my changes to know more about what I'm trying to do.

### Command Prompt/Terminal logs (if existing)

```bash
objects/Note.hx (line 464)
states/PlayState.hx (line 1758)
flixel/group/FlxGroup.hx (line 787)
states/PlayState.hx (line 1752)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I'm making covers of a few songs from other mods. Whenever I try doing UNBEATABLE (Mario's Madness V2, and yes, there is a Psych Engine port of it), this crash report always appears whenever I go to playtest it.

**Comment by M4st3rG4m4** [comment]
parece ser que no identificaste en que carpeta esta la imagen de las notas correctamente
