### ISSUE TITLE
Psych Engine crashes when I try to load music

### ISSUE THREAD

**Issue by inzzomnia** [ShadowMario/FNF-PsychEngine#14884]
### Describe your bug here.

Been through something, I was trying to import my song through Psych Engine. I have the Inst.ogg and Voices.ogg files in the folder, but it just doesn't seem to work. The game crashes the moment I try to load the song. I've tried to disable my voice track, but it still doesn't do anything.

![Screenshot 2024-06-12 125759](https://github.com/ShadowMario/FNF-PsychEngine/assets/165946076/8523e47d-7de7-4fe6-b106-5405e2acd415)
![Screenshot 2024-06-12 125814](https://github.com/ShadowMario/FNF-PsychEngine/assets/165946076/48ac5193-032f-4558-a25a-befe089fa2d3)

The audio files are 4 minutes long.

### Command Prompt/Terminal logs (if existing)

Second Screenshot.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Tartiroom** [comment]
maybe try to add a .json of an existing chart and add it in a folder inside of data with the name of your song

**Comment by VaNdraRat** [comment]
Im also trying to fix this but i think it Maybe (Just maybe) might be to do with the inst.ogg itself. i think you have to use fl sudio and convert your song from there. im not sure?
