### ISSUE TITLE
Long notes are broken (0.6.3)

### ISSUE THREAD

**Issue by FZ-Green** [ShadowMario/FNF-PsychEngine#14881]
### When I change the direction of the notes, they break.

**Code:**

```
function onCreatePost()
    noteTweenDirection("NoteAngle1", 0, -180, 0.1, "linear")
    noteTweenDirection("NoteAngle2", 1, -180, 0.1, "linear")
    noteTweenDirection("NoteAngle3", 2, -180, 0.1, "linear")
    noteTweenDirection("NoteAngle4", 3, -180, 0.1, "linear")
end
function onSpawnNote()
    for a = 0, getProperty('notes.length') - 1 do
        if not getPropertyFromGroup('notes', a, 'mustPress') then    
            setPropertyFromGroup('notes', a, 'angle', 90)
        end
    end
end
```
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/157249853/6e02846a-9aab-42fe-be13-cd5ada9d7bfc)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't change anything.

**Comment by ShadowMario** [comment]
0.6.3 is not supported anymore since december of 2023
