### ISSUE TITLE
Forcing Off Ghost Tapping

### ISSUE THREAD

**Issue by ColdlordXRepositories** [ShadowMario/FNF-PsychEngine#14889]
### Describe your problem here.

Is there any way to force off ghost tapping when entering a song?
I already tried setPropertyFromClass('ClientPrefs', 'ghostTapping', false); but it doesn't work (no error, ghost tapping just stays on)
Is there any other way to disable ghost tapping? am I entering something wrong on the above line?

The entire script:

```
function onSongStart()

    setPropertyFromClass('ClientPrefs', 'ghostTapping', false);
    
    end

function onEndSong()
        
    
    setPropertyFromClass('ClientPrefs', 'ghostTapping', true);

    
    end

```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by xxyuee** [comment]
setPropertyFromClass("backend.ClientPrefs", "data.ghostTapping", false)

**Comment by ColdlordXRepositories** [comment]
> setPropertyFromClass("backend.ClientPrefs", "data.ghostTapping", false)

exactly what i needed, thank you!
