### ISSUE TITLE
Is there a way to get the name of an animation from an xml of a character

### ISSUE THREAD

**Issue by Unbekannnt0** [ShadowMario/FNF-PsychEngine#14886]
### Describe your problem here.

Is it possible to grab the string of the animation name used in the Xml of a character with the json? 
Something like "Bf Right Anim" for his "singRight" animation

So you can then use "Bf Right Anim" automatically in the rest of the script?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Tartiroom** [comment]
try to rename your .json file with .txt instead
