### ISSUE TITLE
Disable botplay fade

### ISSUE THREAD

**Issue by 1928821929** [ShadowMario/FNF-PsychEngine#14883]
### What is your question?

I need to disable the botplay fade effect but i dont know how. Any answer?

**Comment by 1928821929** [comment]
and im experienced in lua only a little

**Comment by JordanSantiagoYT** [comment]
you could try 
`setProperty('botplayTxt.alpha', 1)`

i think

**Comment by gameygu-0213** [comment]
to add to this, you gotta make sure in your script, you make it always update the alpha


`function onUpdate(elapsed)`
`setProperty('botplayTxt.alpha', 1)`
`end`

**Comment by 1928821929** [comment]
tried these both scripts, they dont give errors but doesnt work aswell

**Comment by 1928821929** [comment]
function onUpdate(elapsed)
setProperty('botplayTxt', 'alpha', 1)
end
this one gives me a null object crash

**Comment by 1928821929** [comment]
im on 0.6.3

**Comment by ShadowMario** [comment]
0.6.3 is not supported anymore since December 2023
