### ISSUE TITLE
Trouble Using Custom Character

### ISSUE THREAD

**Issue by MarkkarM123** [ShadowMario/FNF-PsychEngine#14880]
### Describe your problem here.

I created a custom character with the character editor in psych engine, but after saving and trying to load the character in as an opponent on a default song, the option to select it doesn't show up at all.  When loading the JSON file back into the character editor it works correctly and all the animations / icon and bar color remain the same as when I saved them, so I'm a little confused on what's happening.  I did try putting the JSON file in the assets/shared/characters folder, and it actually gives me the option to select the character in the menu, however when the level loads the icon is gone, there is a strange multicolored box in place of the character (floating way too high in the air), and the bar color is the only thing that looks like how I saved it

Any suggestions?

(I put my JSON file in the Mods/Characters folder, and I put my PNG and XML files in the mods/images/characters folder)
(Im not sure what LUA and Source means in the drop down menu on here so ill leave it as source)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MarkkarM123** [comment]
I actually just figured it out, go into the pack JSON for your mod and change the value for runsGlobally to true

**Comment by JackGaming14** [comment]
MarkkarM123, how did you do this? So, I made this character called "bf-fake." (i just swapped his hit notes with the miss notes) Then, I tried to do the same thing with the "bf-holding-gf" sprite. It didn't work. Why I'm confused is because I didn't open the "bf-fake" .json file and change the runsGlobally value at all. Did the same thing with "bf-holding-gf," and it wouldn't appear in the character nor chart editor. (Version 0.4.2)

**Comment by Tartiroom** [comment]
> I actually just figured it out, go into the pack JSON for your mod and change the value for runsGlobally to true

i had kind of the same issue as you, my character animations worked perfectly in the character editor but when i added it to an existing song my character was static in the air, i tried changing the value for runsGlobally to true but it doesn't change anything.

**Comment by chrisdoesstuff69** [comment]
> I actually just figured it out, go into the pack JSON for your mod and change the value for runsGlobally to true

ok how do you do this? i cant find runsglobally in the .json file
