### ISSUE TITLE
icon bounce

### ISSUE THREAD

**Issue by ViceNiLL** [ShadowMario/FNF-PsychEngine#14896]
### What is your question?

How to make Icon bounce like in "Nonsensical Friday Night" using a Lua script? I just looked for the script everywhere I could, but I couldn’t find anything.

**Comment by Nol-IsntUse** [comment]
https://gamebanana.com/tools/9703 idk if this works but check it out

**Comment by ViceNiLL** [comment]
> https://gamebanana.com/tools/9703 idk if this works but check it out

Man, this is DnB icon bounce

**Comment by ViceNiLL** [comment]
> https://gamebanana.com/tools/9703 idk if this works but check it out

Man, this is DnB icon bounce

**Comment by Nol-IsntUse** [comment]
man, I'm just trying to help, I just said to check it out. not trying to be rude but edit it or find it yourself
