### ISSUE TITLE
How do i add ANY mod characters?

### ISSUE THREAD

**Issue by TTRICKYTHECAR** [ShadowMario/FNF-PsychEngine#1489]
### What is your question?
How do i add a character that has a different sprite sheet from daddy dearest and any other fnf original characters? (if i try to, it bugs really hard and at the end of the names from the animations it says (ERROR!) For some reason.)

**Comment by DaBanana64** [comment]
Press 8 on the main menu and add your characters through the character editor... 
Also copy and paste the animation name for each animation from the .XML file that the character has.

**Comment by TTRICKYTHECAR** [comment]
> Press 8 on the main menu and add your characters through the character editor... Also copy and paste the animation name for each animation from the .XML file that the character has.

Thank you **SO** much! i added dave and it worked perfectly fine!

**Comment by DaBanana64** [comment]
> > Press 8 on the main menu and add your characters through the character editor... Also copy and paste the animation name for each animation from the .XML file that the character has.
> 
> Thank you **SO** much! i added dave and it worked perfectly fine!

No problem.

**Comment by MayoALT** [comment]
i wish more mod devs would name their symbols stuff like "idle" "up" "down"
