### ISSUE TITLE
Question: How do I register my custom note

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#149]
Hi,
So I added new notes but I don't know how to add them to the note type option in the charting menu.
In earlier versions there was  chartingstate file or something like that but it isnt there anymore.
Is there a new way to add them.

**Comment by BoloVEVO** [comment]
Go to chartingstate.hx and add your note type string in noteTypelist array var (it is at the beginning btw). It need the same string name you designed to note.hx and playstate.hx.
![image](https://user-images.githubusercontent.com/88955176/134843890-7042f2c3-14b1-4c70-8288-42953eccc882.png)

**Comment by lemz1** [comment]
I don't have a file named chartingstate.hx.
I had it in version 3.2 but in version 4.1 There wasn't the file

**Comment by TheBuilderXD** [comment]
look in the editors folder

**Comment by lemz1** [comment]
ooh my bad
