### ISSUE TITLE
I'm not Sure, can someone help im kinda new in modding.

### ISSUE THREAD

**Issue by Drixxytec** [ShadowMario/FNF-PsychEngine#14903]
### Describe your bug here.

So this happened when i tried you know, scrolling down in the story menu, i've created jsons for the weeks and stuff but this just happens:
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/132640189/5303a68a-cb3a-4991-90bd-4f512c383bc5)

### Command Prompt/Terminal logs (if existing)

```bash
states/StoryMenuState.hx (line 439)
states/StoryMenuState.hx (line 427)
states/StoryMenuState.hx (line 209)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, at least don't think so all i did was create my full mod folder.

**Comment by DoingYourGirl5** [comment]
yo homie show me your week file, cause im pretty sure theirs something up wit your week file
