### ISSUE TITLE
Crashing when i try to use the sprite editor

### ISSUE THREAD

**Issue by Nol-IsntUse** [ShadowMario/FNF-PsychEngine#14902]
### Describe your bug here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/166926831/ff0317de-5d1c-47dd-8f7c-e15af5c03ce5)
uh i dont know what this means so i dont really know what else to say

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Drixxytec** [comment]
Same error im having, but its when i try going to the weeks i created.
