### ISSUE TITLE
lime test windows not working after compiling

### ISSUE THREAD

**Issue by mikaelrokkaa** [ShadowMario/FNF-PsychEngine#14908]
### Describe your bug here.

i changed the application name and (tried to) change the icons, and after that i tried to compile so it works
but then it hits me with a error PLEASE HELP
![Näyttökuva 2024-06-16 175418](https://github.com/ShadowMario/FNF-PsychEngine/assets/170237820/e09c76ba-3a4b-4656-8301-20ba89efd87e)

### Command Prompt/Terminal logs (if existing)

```bash
look at linked file
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i edited project.xml so i could change the application name

**Comment by Vortex2Oblivion** [comment]
Delete the export folder and try again

**Comment by mikaelrokkaa** [comment]
> Delete the export folder and try again

are you sure?

**Comment by Vortex2Oblivion** [comment]
Yea
That error happens when something got corrupted when compiling (usually if you close the terminal while it's compiling a file) and just building from scratch fixes it
