### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by Nol-IsntUse** [ShadowMario/FNF-PsychEngine#14907]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/166926831/fac4d624-6be3-4843-9ca7-35cb3fa938c6)
not sure what this means :sob:

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i replaced all TeaCalls with Tea because i found it in another help wanted thingy

**Comment by giannydeez** [comment]
how did you replace the teacalls??? i keep having that issue i'm stuck

**Comment by Nol-IsntUse** [comment]
basically in Hscript.hx (search for it) you might find TeaCall, just replace it with Tea
