### ISSUE TITLE
Note Splashes And Note Assets reverting to normal!

### ISSUE THREAD

**Issue by shikecool64amongus69** [ShadowMario/FNF-PsychEngine#14906]
### Describe your bug here.

This is stupid i have a png file txt and xml i put it on the list then i go to settings put it on my splash and it uses normal splashes!
Same with note skin!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope nothing edited

**Comment by xxyuee** [comment]
does the noteskin name in the txt have any typo?

**Comment by shikecool64amongus69** [comment]
> ###
> **[xxyuee](/xxyuee) ** commented [Jun 16, 2024](#issuecomment-2171798145)

what do you mean noteskin has a typo?
