### ISSUE TITLE
stage code problems?

### ISSUE THREAD

**Issue by Saulgoodmanondrugs** [ShadowMario/FNF-PsychEngine#14900]
### Describe your problem here.

i don't get what's wrong?
![Desktop Screenshot 2024 06 15 - 14 14 42 88](https://github.com/ShadowMario/FNF-PsychEngine/assets/134774324/45dcc05f-68e1-4e33-a808-8a7496f3db74)
![Desktop Screenshot 2024 06 15 - 14 16 32 35](https://github.com/ShadowMario/FNF-PsychEngine/assets/134774324/e7b04ce7-b3a9-44f5-880c-d1615a528b21)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yeah, i tried to add a new bg

**Comment by frantastic24** [comment]
You only need 1 `end`

**Comment by Saulgoodmanondrugs** [comment]
already did that and it doesn't work

**Comment by frantastic24** [comment]
You need it at the end of the function

**Comment by Saulgoodmanondrugs** [comment]
i alr did it

**Comment by Saulgoodmanondrugs** [comment]
i did it nvm
