### ISSUE TITLE
how do you download visual studio 2019 i need it for fnf mod

### ISSUE THREAD

**Issue by chrisdoesstuff69** [ShadowMario/FNF-PsychEngine#14914]
### Describe your problem here.

i cant download visual studio 2019 without it saying setup failed

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed HScript from teacall to tea

**Comment by DendyGG** [comment]
Try this https://visualstudio.microsoft.com/ru/thank-you-downloading-visual-studio/?sku=community&rel=16&utm_medium=microsoft&utm_campaign=download+from+relnotes&utm_content=vs2019ga+button

**Comment by chrisdoesstuff69** [comment]
> Try this https://visualstudio.microsoft.com/ru/thank-you-downloading-visual-studio/?sku=community&rel=16&utm_medium=microsoft&utm_campaign=download+from+relnotes&utm_content=vs2019ga+button

alr thanks
