### ISSUE TITLE
Source/psychlua/HScript.hx:317: characters 89-96 : type not found : TeaCall

### ISSUE THREAD

**Issue by fearsyeah** [ShadowMario/FNF-PsychEngine#14923]
### Describe your bug here.

When i try to use  ,, Lime test windows " Source/psychlua/HScript.hx:317: characters 89-96 : type not found : TeaCall pops up and doesnt let me finish how could i repair it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by DoingYourGirl5** [comment]
a lot of people getting that, just go to Hscript and change TeaCall to Tea

**Comment by fearsyeah** [comment]
> a lot of people getting that, just go to Hscript and change TeaCall to Tea

how can i do that?
sorry Its my first time doing  mods

**Comment by DoingYourGirl5** [comment]
i got you homie
so open your code editor
and go to the mod folder and find HScript
and search for TeaCall and just make it Tea

**Comment by fearsyeah** [comment]
> i got you homie so open your code editor and go to the mod folder and find HScript and search for TeaCall and just make it Tea

yeah so my code editor is Visual Studio Code but still no shi idk where to find Hscript, really no idea

**Comment by DoingYourGirl5** [comment]
so go on visual studio and go to file and press open folder and find the folder wit your stuff
and then go to the lil search icon and find Hscript and change TeaCall into Tea

**Comment by fearsyeah** [comment]
> so go on visual studio and go to file and press open folder and find the folder wit your stuff and then go to the lil search icon and find Hscript and change TeaCall into Tea

yeah so there is a problem. I dont have a folder with MY STUFF I was following a tutorial on youtube and just downloaded some stuff for psych engine from Windows powershell, I only have a folder called PSYSH where I have psych engine and thats all.

**Comment by fearsyeah** [comment]
> > so go on visual studio and go to file and press open folder and find the folder wit your stuff and then go to the lil search icon and find Hscript and change TeaCall into Tea
> 
> yeah so there is a problem. I dont have a folder with MY STUFF I was following a tutorial on youtube and just downloaded some stuff for psych engine from Windows powershell, I only have a folder called PSYSH where I have psych engine and thats all.
I can give you the link to the tutorial if needed

**Comment by DoingYourGirl5** [comment]
go to your "PSYCH" folder on visual studio and then search for Hscript and change TeaCall Tea

**Comment by DoingYourGirl5** [comment]
if you still need help then i can guide you on discord or som

**Comment by fearsyeah** [comment]
> if you still need help then i can guide you on discord or som

you can drop me ur discord so I can lyk if worked or i need help, Thanks man

**Comment by DoingYourGirl5** [comment]
look on my github profile
