### ISSUE TITLE
No asset library with ID of 'songs'

### ISSUE THREAD

**Issue by Is-Foxo** [ShadowMario/FNF-PsychEngine#14925]
### Describe your bug here.

Every time I try to compile Psych Engine 0.7.3 I get the same error, where it states:

> [lime.utils.Preloader] ERROR: There is no asset library with an ID of "songs"

The folder isn't missing so I don't know what could be happening. Does anybody know how to fix this? 
![Screenshot 2024-06-18 205749](https://github.com/ShadowMario/FNF-PsychEngine/assets/140968065/5b222f96-0de8-4436-ba0f-aebe413ab922)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No changes

**Comment by xxyuee** [comment]
is 'songs.json' somehow missing in the manifest folder?

**Comment by Is-Foxo** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/140968065/36d424b5-0905-4b9e-80a5-f90b8247cd3f)
no, it's definitely there.

**Comment by Limakoko** [comment]
I have the same problem

**Comment by Benlik89** [comment]
just launch it with administrator
i had the same bug and it got fixed

**Comment by Is-Foxo** [comment]
That didn't work for me.

**Comment by Limakoko** [comment]
me too

**Comment by cooswagger** [comment]
try "haxelib set lime 8.0.2" (took from another issue)
