### ISSUE TITLE
Can't reload character spritesheet (made with Flash CS6)

### ISSUE THREAD

**Issue by NoToeHavingFreak** [ShadowMario/FNF-PsychEngine#14927]
### Describe your bug here.

I have no idea what the hell's happening, and I don't know how this is always happening, I keep trying different versions, but nothing works.
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/173212908/8540e04a-b2b1-4cee-94e0-2a34a43e9dac)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

The only thing I replaced was the menu music, which has no relation to this bug.

**Comment by NoToeHavingFreak** [comment]
Does this on the latest build too.

**Comment by xxyuee** [comment]
it means theres something wrong with the xml. can you show the xml?

**Comment by NoToeHavingFreak** [comment]
<?xml version="1.0" encoding="UTF-16"?>
<TextureAtlas imagePath="Fap_Chap.png">
	
	
	<SubTexture name="down0000" x="0" y="0" width="368" height="244" frameX="0" frameY="-13" frameWidth="368" frameHeight="257"/>
	<SubTexture name="down0001" x="368" y="0" width="368" height="244" frameX="0" frameY="-13" frameWidth="368" frameHeight="257"/>
	<SubTexture name="down0002" x="736" y="0" width="347" height="257" frameX="-14" frameY="0" frameWidth="368" frameHeight="257"/>
	<SubTexture name="down0003" x="1083" y="0" width="347" height="257" frameX="-14" frameY="0" frameWidth="368" frameHeight="257"/>
	<SubTexture name="down0004" x="1430" y="0" width="347" height="257" frameX="-14" frameY="0" frameWidth="368" frameHeight="257"/>
	<SubTexture name="down0005" x="0" y="257" width="347" height="257" frameX="-14" frameY="0" frameWidth="368" frameHeight="257"/>
	<SubTexture name="down0006" x="347" y="257" width="347" height="257" frameX="-14" frameY="0" frameWidth="368" frameHeight="257"/>
	<SubTexture name="down0007" x="694" y="257" width="347" height="257" frameX="-14" frameY="0" frameWidth="368" frameHeight="257"/>
	<SubTexture name="down0008" x="1041" y="257" width="347" height="257" frameX="-14" frameY="0" frameWidth="368" frameHeight="257"/>
	<SubTexture name="down0009" x="1388" y="257" width="347" height="257" frameX="-14" frameY="0" frameWidth="368" frameHeight="257"/>
	<SubTexture name="down0010" x="0" y="514" width="347" height="257" frameX="-14" frameY="0" frameWidth="368" frameHeight="257"/>
	<SubTexture name="down0011" x="347" y="514" width="347" height="257" frameX="-14" frameY="0" frameWidth="368" frameHeight="257"/>
	<SubTexture name="down0012" x="694" y="514" width="347" height="257" frameX="-14" frameY="0" frameWidth="368" frameHeight="257"/>
	<SubTexture name="down0013" x="1041" y="514" width="347" height="257" frameX="-14" frameY="0" frameWidth="368" frameHeight="257"/>
	<SubTexture name="idle0000" x="1388" y="514" width="349" height="230" frameX="0" frameY="-14" frameWidth="352" frameHeight="244"/>
	<SubTexture name="idle0001" x="0" y="771" width="346" height="236" frameX="-5" frameY="-8" frameWidth="352" frameHeight="244"/>
	<SubTexture name="idle0002" x="346" y="771" width="344" height="239" frameX="-7" frameY="-5" frameWidth="352" frameHeight="244"/>
	<SubTexture name="idle0003" x="690" y="771" width="342" height="240" frameX="-9" frameY="-4" frameWidth="352" frameHeight="244"/>
	<SubTexture name="idle0004" x="1032" y="771" width="342" height="241" frameX="-10" frameY="-3" frameWidth="352" frameHeight="244"/>
	<SubTexture name="idle0005" x="1374" y="771" width="342" height="242" frameX="-10" frameY="-2" frameWidth="352" frameHeight="244"/>
	<SubTexture name="idle0006" x="0" y="1013" width="341" height="243" frameX="-11" frameY="-1" frameWidth="352" frameHeight="244"/>
	<SubTexture name="idle0007" x="341" y="1013" width="341" height="244" frameX="-11" frameY="0" frameWidth="352" frameHeight="244"/>
	<SubTexture name="idle0008" x="682" y="1013" width="340" height="244" frameX="-12" frameY="0" frameWidth="352" frameHeight="244"/>
	<SubTexture name="idle0009" x="1022" y="1013" width="340" height="244" frameX="-12" frameY="0" frameWidth="352" frameHeight="244"/>
	<SubTexture name="idle0010" x="1362" y="1013" width="340" height="244" frameX="-12" frameY="0" frameWidth="352" frameHeight="244"/>
	<SubTexture name="idle0011" x="1702" y="1013" width="340" height="244" frameX="-12" frameY="0" frameWidth="352" frameHeight="244"/>
	<SubTexture name="idle0012" x="0" y="1257" width="340" height="244" frameX="-12" frameY="0" frameWidth="352" frameHeight="244"/>
	<SubTexture name="idle0013" x="340" y="1257" width="340" height="244" frameX="-12" frameY="0" frameWidth="352" frameHeight="244"/>
	<SubTexture name="left0000" x="680" y="1257" width="337" height="254" frameX="0" frameY="0" frameWidth="353" frameHeight="254"/>
	<SubTexture name="left0001" x="1017" y="1257" width="337" height="254" frameX="0" frameY="0" frameWidth="353" frameHeight="254"/>
	<SubTexture name="left0002" x="1354" y="1257" width="338" height="243" frameX="-15" frameY="-11" frameWidth="353" frameHeight="254"/>
	<SubTexture name="left0003" x="1692" y="1257" width="338" height="243" frameX="-15" frameY="-11" frameWidth="353" frameHeight="254"/>
	<SubTexture name="left0004" x="0" y="1511" width="338" height="243" frameX="-15" frameY="-11" frameWidth="353" frameHeight="254"/>
	<SubTexture name="left0005" x="338" y="1511" width="338" height="243" frameX="-15" frameY="-11" frameWidth="353" frameHeight="254"/>
	<SubTexture name="left0006" x="676" y="1511" width="338" height="243" frameX="-15" frameY="-11" frameWidth="353" frameHeight="254"/>
	<SubTexture name="left0007" x="1014" y="1511" width="338" height="243" frameX="-15" frameY="-11" frameWidth="353" frameHeight="254"/>
	<SubTexture name="left0008" x="1352" y="1511" width="338" height="243" frameX="-15" frameY="-11" frameWidth="353" frameHeight="254"/>
	<SubTexture name="left0009" x="1690" y="1511" width="338" height="243" frameX="-15" frameY="-11" frameWidth="353" frameHeight="254"/>
	<SubTexture name="left0010" x="0" y="1754" width="338" height="243" frameX="-15" frameY="-11" frameWidth="353" frameHeight="254"/>
	<SubTexture name="left0011" x="338" y="1754" width="338" height="243" frameX="-15" frameY="-11" frameWidth="353" frameHeight="254"/>
	<SubTexture name="left0012" x="676" y="1754" width="338" height="243" frameX="-15" frameY="-11" frameWidth="353" frameHeight="254"/>
	<SubTexture name="left0013" x="1014" y="1754" width="338" height="243" frameX="-15" frameY="-11" frameWidth="353" frameHeight="254"/>
	<SubTexture name="right0000" x="1352" y="1754" width="348" height="254" frameX="-6" frameY="-6" frameWidth="354" frameHeight="260"/>
	<SubTexture name="right0001" x="1700" y="1754" width="348" height="254" frameX="-6" frameY="-6" frameWidth="354" frameHeight="260"/>
	<SubTexture name="right0002" x="0" y="2008" width="344" height="259" frameX="0" frameY="0" frameWidth="354" frameHeight="260"/>
	<SubTexture name="right0003" x="344" y="2008" width="344" height="259" frameX="0" frameY="0" frameWidth="354" frameHeight="260"/>
	<SubTexture name="right0004" x="688" y="2008" width="344" height="259" frameX="0" frameY="0" frameWidth="354" frameHeight="260"/>
	<SubTexture name="right0005" x="1032" y="2008" width="344" height="259" frameX="0" frameY="0" frameWidth="354" frameHeight="260"/>
	<SubTexture name="right0006" x="1376" y="2008" width="344" height="259" frameX="0" frameY="0" frameWidth="354" frameHeight="260"/>
	<SubTexture name="right0007" x="0" y="2267" width="344" height="259" frameX="0" frameY="0" frameWidth="354" frameHeight="260"/>
	<SubTexture name="right0008" x="344" y="2267" width="344" height="259" frameX="0" frameY="0" frameWidth="354" frameHeight="260"/>
	<SubTexture name="right0009" x="688" y="2267" width="344" height="259" frameX="0" frameY="0" frameWidth="354" frameHeight="260"/>
	<SubTexture name="right0010" x="1032" y="2267" width="344" height="259" frameX="0" frameY="0" frameWidth="354" frameHeight="260"/>
	<SubTexture name="right0011" x="1376" y="2267" width="344" height="259" frameX="0" frameY="0" frameWidth="354" frameHeight="260"/>
	<SubTexture name="right0012" x="0" y="2526" width="344" height="259" frameX="0" frameY="0" frameWidth="354" frameHeight="260"/>
	<SubTexture name="right0013" x="344" y="2526" width="344" height="259" frameX="0" frameY="0" frameWidth="354" frameHeight="260"/>
	<SubTexture name="up0000" x="688" y="2526" width="326" height="283" frameX="-8" frameY="0" frameWidth="342" frameHeight="283"/>
	<SubTexture name="up0001" x="1014" y="2526" width="326" height="283" frameX="-8" frameY="0" frameWidth="342" frameHeight="283"/>
	<SubTexture name="up0002" x="1340" y="2526" width="342" height="263" frameX="0" frameY="-20" frameWidth="342" frameHeight="283"/>
	<SubTexture name="up0003" x="1682" y="2526" width="342" height="263" frameX="0" frameY="-20" frameWidth="342" frameHeight="283"/>
	<SubTexture name="up0004" x="0" y="2809" width="342" height="263" frameX="0" frameY="-20" frameWidth="342" frameHeight="283"/>
	<SubTexture name="up0005" x="342" y="2809" width="342" height="263" frameX="0" frameY="-20" frameWidth="342" frameHeight="283"/>
	<SubTexture name="up0006" x="684" y="2809" width="342" height="263" frameX="0" frameY="-20" frameWidth="342" frameHeight="283"/>
	<SubTexture name="up0007" x="1026" y="2809" width="342" height="263" frameX="0" frameY="-20" frameWidth="342" frameHeight="283"/>
	<SubTexture name="up0008" x="1368" y="2809" width="342" height="263" frameX="0" frameY="-20" frameWidth="342" frameHeight="283"/>
	<SubTexture name="up0009" x="0" y="3072" width="342" height="263" frameX="0" frameY="-20" frameWidth="342" frameHeight="283"/>
	<SubTexture name="up0010" x="342" y="3072" width="342" height="263" frameX="0" frameY="-20" frameWidth="342" frameHeight="283"/>
	<SubTexture name="up0011" x="684" y="3072" width="342" height="263" frameX="0" frameY="-20" frameWidth="342" frameHeight="283"/>
	<SubTexture name="up0012" x="1026" y="3072" width="342" height="263" frameX="0" frameY="-20" frameWidth="342" frameHeight="283"/>
	<SubTexture name="up0013" x="1368" y="3072" width="342" height="263" frameX="0" frameY="-20" frameWidth="342" frameHeight="283"/>
</TextureAtlas>

**Comment by NoToeHavingFreak** [comment]
[Fap_Chap.txt](https://github.com/user-attachments/files/15903138/Fap_Chap.txt)

**Comment by NoToeHavingFreak** [comment]
Note: Converted from XML to TXT.

**Comment by xxyuee** [comment]
on the first line, set UTF-16 to utf-8.

**Comment by NoToeHavingFreak** [comment]
Didn't work.

**Comment by BernardoGP4504** [comment]
Open the xml in notepad
Click "save as"
Override the xml, make sure to pick encoding as `utf-8` or `utf-8 with BOM`

**Comment by NoToeHavingFreak** [comment]
This worked! Thank you :)
