### ISSUE TITLE
Application icon via source code

### ISSUE THREAD

**Issue by Your-Local-LordXSimp** [ShadowMario/FNF-PsychEngine#14931]
### What is your question?

Where do I put this in source? Does it have to be in a specific .hx file?

`Application.current.window.setIcon( Image.fromBitmapData( BitmapData.fromFile( Paths.modImage( 'myIcon.png' ) ) ) );`

**Comment by Vortex2Oblivion** [comment]
Why would you want to do it like that? Can't you just change the icon image?

**Comment by Your-Local-LordXSimp** [comment]
the .ico? No. It'll most likely (from my knowledge) display the HaxeFlixel logo, I think. I've heard it somewhere before on here.

**Comment by baobab121** [comment]
you can replace the icons in the art folder
![icons](https://github.com/ShadowMario/FNF-PsychEngine/assets/173479950/abd84195-178d-474a-89e6-ff30df0ac77b)
