### ISSUE TITLE
How do i disable custom note colors?

### ISSUE THREAD

**Issue by IdkWhatAmIDoin** [ShadowMario/FNF-PsychEngine#14930]
### Describe your problem here.

Hello. I want my notes to be colored only a specific color, but it needs to be RGB. I want to use my own notes, not RGB. How do i disable it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by xxyuee** [comment]
function onUpdate()
    for i = 0,3 do
            setPropertyFromGroup("playerStrums", i, 'useRGBShader', false)
            setPropertyFromGroup("opponentStrums", i, 'useRGBShader', false)
    end
    for i = 0,getProperty('unspawnNotes.length')-1 do
            setPropertyFromGroup("unspawnNotes", i, 'rgbShader.enabled', false)
            setPropertyFromGroup("unspawnNotes", i, "noteSplashData.useRGBShader", false)
    end
end

**Comment by frantastic24** [comment]
> onUpdate()

Why

**Comment by IdkWhatAmIDoin** [comment]
i meant source
