### ISSUE TITLE
MUST Ignore Note

### ISSUE THREAD

**Issue by SomeGDPerson123** [ShadowMario/FNF-PsychEngine#14939]
### What is your question?

I'm wondering if there is a note that can be made in LUA that follows this criteria:
- Opponent completely ignores the note
- Botplay completely ignores the note
- It is impossible to hit the note when normally playing
- No punishment is made for missing the note in normal play

**Comment by Lorekeeper49** [comment]
Points 1, 2, and 4 are possible with the ignoreNote variable, not sure about point 3 though

**Comment by LarryFrosty** [comment]
Enable the `ignoreNote` and the `blockHit` variable on the note

**Comment by SomeGDPerson123** [comment]
k, thanks!

**Comment by Lorekeeper49** [comment]
> so uh how do i close this now

It should either be in the 3 dots at the top of this page or an option at the bottom depending if you're on phone or pc

**Comment by SomeGDPerson123** [comment]
thanks
