### ISSUE TITLE
Hold notes are way too long

### ISSUE THREAD

**Issue by i-winxd** [ShadowMario/FNF-PsychEngine#1493]
### Describe your bug here.

Psych engine build
![image](https://user-images.githubusercontent.com/31808925/143955268-3e675aa9-d4d0-4409-814d-470d7e04ca11.png)
Non-psych engine build
![image](https://user-images.githubusercontent.com/31808925/143955309-fb28afc3-453d-4691-88a4-5bf3336aa482.png)
These notes have the exact same hold times, which are often seem to be longer than they are programmed to be. I chart using an external program, so if these issues do not occur in psych engine's editor, then sorry about that. However, when porting songs from different engines to psych engine, hold notes become a lot longer, meaning you have less time to comfortably switch between notes.

I do not know if this is a visual bug or if it actually requires that the notes be held longer. The fix is to interpret all notes in a chart as being ever-so-slightly shorter than they are.

Example where a problem could rise:
![image](https://user-images.githubusercontent.com/31808925/143955511-cf63f5ce-edf1-4949-b650-7f2503b24b93.png)

Notice that I have a very small time window between lifting up <- and pressing down.

### Command Prompt/Terminal logs (if existing)

```bash
-
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No source code changes.

**Comment by KutikiPlayz** [comment]
idk exactly how the game puts the sprites, whether it's accurate to the actual length or not, idk. I did actually port some kade charts over to psych and the hold notes we're a little longer than expected. You can probably just go into the editor and easily fix all the elongated hold notes.

**Comment by i-winxd** [comment]
That is VERY tedious as you'll have to do that for every note, unless you make an external program that shortens all sustain notes.

**Comment by KutikiPlayz** [comment]
either way, I don't think this is a bug, it's just the fact that psych uses a different charting system than whatever you use

**Comment by ShadowMario** [comment]
No way! DIfferent engines work differently and charts from another engine might not be ported fully properly?? Wow!
