### ISSUE TITLE
Psych Engine source/Achievements 0.6.3 error

### ISSUE THREAD

**Issue by AMDKSDMKLADJKLA** [ShadowMario/FNF-PsychEngine#14933]
### Describe your problem here.

I got this error when compiling psych engine 0.6.3: source/Achievements.hx:132: characters 3-64 : (camera : flixel.FlxCamera, value : Bool) -> Void should be Array<flixel.FlxCamera>

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't change that much in the build, all I did was change the fps thing in the options

**Comment by AMDKSDMKLADJKLA** [comment]
nvm its fixed

**Comment by Ustayim** [comment]
how...
