### ISSUE TITLE
My character doesnt show up in chart editor

### ISSUE THREAD

**Issue by chrisdoesstuff69** [ShadowMario/FNF-PsychEngine#14945]
### Describe your problem here.

i went to blammed and pressed 7 and then i tried to find my character named "chris" in the opponent section and it didnt show up even though i put it in the character editor and got the .json file and idk what do to like do i need to put it somewhere?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I removed "my mod" folder from mod template

**Comment by xxyuee** [comment]
if you put your character in the mods folder, it wont look there unless you go to chart editor through main menu.

**Comment by chrisdoesstuff69** [comment]
alrighty then thank you very much
