### ISSUE TITLE
Pausing for a long time causes the game to glitch out.

### ISSUE THREAD

**Issue by DoctorOPlays** [ShadowMario/FNF-PsychEngine#14941]
### Describe your bug here.

so basically I was just pausing the game and walked away for awhile to eat, and when i came back and unpaused it, it started glitching out.

![BUUUG REPORT](https://github.com/ShadowMario/FNF-PsychEngine/assets/78882862/5501fe06-f4dd-4afc-b192-1922a6929d6a)

also the way it looks windowed, is not part of the glitch. its just the screen recorder  being weird

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i replaced all of "TeaCall" with "Tea" in HScript.hx so i could compile it.

**Comment by Vortex2Oblivion** [comment]
This can happen if your computer goes to sleep or you change sound devices iirc

**Comment by DoctorOPlays** [comment]
> This can happen if your computer goes to sleep or you change sound devices iirc

I didn't put my computer on sleep mode, I just left it running normally.
