### ISSUE TITLE
Mouse in Main Menu 0.7.3

### ISSUE THREAD

**Issue by baobab121** [ShadowMario/FNF-PsychEngine#14942]
### Describe your problem here.

I'm not good at coding, but I tried several times and nothing worked. I wanted to make the menu like in VS Impostor V4 with mouse.
i want to be able to highlight the buttons in menu with the mouse and click on them (depending on which one is highlighted)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I worked at MainMenuState.hx. I was only able to make the buttons click through the mouse and if mouse overlaps them.

**Comment by baobab121** [comment]
> ### Describe your problem here.
> I'm not good at coding, but I tried several times and nothing worked. I wanted to make the menu like in VS Impostor V4.
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> I worked at MainMenuState.hx. I was only able to make the buttons click through the mouse and if mouse overlaps it.

**Comment by xxyuee** [comment]
sry i dont understand, do you want the mouse visible or?

**Comment by baobab121** [comment]
> sry i dont understand, do you want the mouse visible or?

i want to be able to highlight the buttons in menu with the mouse and click on them (depending on which one is highlighted)

**Comment by BernardoGP4504** [comment]
> > sry i dont understand, do you want the mouse visible or?
> 
> i want to be able to highlight the buttons in menu with the mouse and click on them (depending on which one is highlighted)

Copy how VS Impostor V4 did it, it's literally a for loop and some curSelected updating

**Comment by baobab121** [comment]
nvm, i did it myself somehow.
