### ISSUE TITLE
how do add a menu bar

### ISSUE THREAD

**Issue by rackyrblx** [ShadowMario/FNF-PsychEngine#14943]
### Describe your problem here.

![menubar](https://github.com/ShadowMario/FNF-PsychEngine/assets/148754902/473c9c8b-2bcc-488c-8cde-f6c36c6719a0)
to be on the menu bg so it can hold the story menu and other stuff
also how do I remove Donate and Awards

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by rackyrblx** [comment]
accidental close

**Comment by baobab121** [comment]
you cant do that on lua

**Comment by rackyrblx** [comment]
> you cant do that on lua

im doing Lua and hx and xml

**Comment by WolfyTail** [comment]
But you can't edit the game BG with lua. You need to use source code for that, and to move the menu items if you need it.

**Comment by rackyrblx** [comment]
> But you can't edit the game BG with lua. You need to use source code for that, and to move the menu items if you need it.
ok I've managed to do it now, last thing how do I change the title menu bg into a image because the source code is just color

**Comment by baobab121** [comment]
> ok I've managed to do it now, last thing how do I change the title menu bg into a image because the source code is just color

there is a gfDanceTitle.json file in assets/shared/images. 
add your bg there.
`"backgroundSprite":"bg",`
