### ISSUE TITLE
How to hide freeplay from menu?

### ISSUE THREAD

**Issue by IdkWhatAmIDoin** [ShadowMario/FNF-PsychEngine#14940]
### Describe your problem here.

Hello. I want to hide freeplay from menu, keeping story mode only. How do i do it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by xxyuee** [comment]
you can only do it in source.

**Comment by baobab121** [comment]
in the MainMenuState.hx if you only need to hide freeplay then

        var optionShit:Array<String> = [
        	'story_mode',
		'freeplay',  //remove this line
		#if MODS_ALLOWED 'mods', #end
		#if ACHIEVEMENTS_ALLOWED 'awards', #end
		'credits',
		#if !switch 'donate', #end
		'options'
	];

if you need to remove other buttons (for example, donate), then also remove the line where donate is located.
