### ISSUE TITLE
Error compiling source!

### ISSUE THREAD

**Issue by JulianGeckoWasp** [ShadowMario/FNF-PsychEngine#14950]
### Describe your problem here.

Hello. When running 'lime test windows', I get the following error:

libucrt.lib(checkcfg.obj) : error LNK2001: unresolved external symbol _guard_check_icall_$fo$
ApplicationMain.exe : fatal error LNK1120: 1 unresolved externals

Help would be appreciated. Thanks.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing has been changed.

**Comment by NN---** [comment]
Either build with Visual Studio 2022 toolset or use older SDK 10.0.17763.0.
See: https://github.com/dotnet/corert/issues/7451
