### ISSUE TITLE
Detect practice mode by LUA?

### ISSUE THREAD

**Issue by SomeGDPerson123** [ShadowMario/FNF-PsychEngine#14957]
### What is your question?

Hey, so I'm making a HUD mod for Psych Engine 0.6.3, and I want different things to display when you are in normal play, botplay, practice mode, and instakill on miss. I was able to get normal play and botplay HUDs working fine, but I don't know how to detect practice mode and instakill on miss using an `if` or `elseif` statement. This is part of the script I'm making:
`function onUpdatePost()`
`    local sicks = getProperty('sicks')`
`    local goods = getProperty('goods')`
`    local bads = getProperty('bads')`
`    local shits = getProperty('shits')`
`    local hits = sicks + goods + bads + shits`
`    local sickScore = sicks*350`
`    local goodScore = goods*200 -- other code to make exceptions if your computer is garbage enough to get something other than sicks`
`    local badScore = bads*100 -- other code to make exceptions if your computer is garbage enough to get something other than sicks`
`    local shitScore = shits*50 -- other code to make exceptions if your computer is garbage enough to get something other than sicks`
`    local missScore = misses*10 -- other code to make exceptions if your computer is garbage enough to get something other than sicks`
`    local totalFakeScore = sickScore+goodScore+badScore+shitScore-missScore`
`    if botPlay and misses < 1 then`
`        setProperty('scoreTxt.text', 'Score: ' .. totalFakeScore .. ' | Hits: ' .. hits .. ' | Botplay') -- shows hits and score when botplay is on`
`    elseif botPlay then`
`        setProperty('scoreTxt.text', 'Score: ' .. totalFakeScore .. ' | Misses: ' .. misses .. ' | Hits: ' .. hits .. ' | Botplay') -- shows hits, score and misses if your garbage computer somehow made botplay miss a note`
`    elseif hits < 1 then`
`        setProperty('scoreTxt.text', 'Score: 0 | Misses: 0 | Accuracy: 0% [?]') -- text for not hitting anything yet`
`    elseif misses < 1 then`
`        setProperty('scoreTxt.text', 'Score: ' .. score .. ' | Misses: ' .. misses .. ' | Accuracy: ' ..  round(rating * 100, 2) .. '% [' .. ratingFC .. ']') -- text for a fc`
`    else`
`        setProperty('scoreTxt.text', 'Score: ' .. score .. ' | Misses: ' .. misses .. ' | Accuracy: ' ..  round(rating * 100, 2) .. '%') -- text for not a fc`
`    end`
`    setProperty('botplayTxt.visible', false)`
`end`

**Comment by baobab121** [comment]
getProperty('practiceMode')

**Comment by SomeGDPerson123** [comment]
Two questions:
1. Is there one for instakill on miss? 
2. Does it output the value as words (true or false) or numbers (0 or 1)?

**Comment by baobab121** [comment]
> One question: Is there one for instakill on miss?

getProperty('instaKillOnMiss')
btw, they are all in PlayState.hx

**Comment by SomeGDPerson123** [comment]
thx!!!

**Comment by SomeGDPerson123** [comment]
I tried to import a variable to show getProperty('practiceMode') by doing this:
local practiceMode = getProperty('practiceMode')

However, whenever I want to make the score text display this variable, it just resets back to the default score text.

**Comment by baobab121** [comment]
> I tried to import a variable to show getProperty('practiceMode') by doing this: local practiceMode = getProperty('practiceMode')
> 
> However, whenever I want to make the score text display this variable, it just resets back to the default score text.

it works fine for me.
can i see your code?

**Comment by SomeGDPerson123** [comment]
Here:
[hud thing.txt](https://github.com/user-attachments/files/16022262/hud.thing.txt)

(i put it in .txt because github doesn't support .lua)

**Comment by SomeGDPerson123** [comment]
Here's the project I'm working on, if you want that too:
https://gamebanana.com/mods/523232

**Comment by baobab121** [comment]
do you want Debug Value to show true or false?
then you can do this:

`local practiceMode = 0  --or anything else`
`if getProperty('practiceMode') then`
`    practiceMode = 'true'`
`else`
`    practiceMode = 'false'`
` end`

I think it resets the score text to default because it can't show the bool variable in the text.

**Comment by SomeGDPerson123** [comment]
Same goes for instakill on miss, I'm guessing. Thanks!
