### ISSUE TITLE
inexplicable zoom

### ISSUE THREAD

**Issue by bryanbros170** [ShadowMario/FNF-PsychEngine#14961]
### Describe your problem here.

This "inexplicable zoom" consists of the following: When I set any stage to a certain song in my mod, it appears with a zoom effect. Even the words **"READY? SET!? GO!"** appear larger than normal. However, if I switch to another song in my mod, this zoom effect simply disappears and the entire **UI** appears normally. Therefore, the zoom issue does not seem to lie in the **"Json"** and **"Lua"** files of the stages, so I thought the problem might be in the **"data"** folder. I compared both songs with their **"Json"** files, but unfortunately, I didn't find anything related to the zoom issue. So if the problem isn't in the stage files and it's not in the song's data either, where could the problem be and how can it be solved? **Thank you very much for your attention.**

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by bryanbros170** [comment]
Zoom problem:
![problema con zoom](https://github.com/ShadowMario/FNF-PsychEngine/assets/173642417/93a79e09-cabc-4db2-8e6d-04d6c5aa6b7d)

Without the zoom problem: 
![sin problema de zoom](https://github.com/ShadowMario/FNF-PsychEngine/assets/173642417/29b84538-88d1-4667-8712-d71a7e16d167)

**Comment by BernardoGP4504** [comment]
Might be a script

**Comment by bryanbros170** [comment]
> Might be a script

I forgot to mention that the problem is not due to the script either, I only have one activated and it is midscroll, but I already verified that that was not the problem. So I still have no solution at the moment.

**Comment by bryanbros170** [comment]
I solved it, it was all due to the "Hit section" box that appears in the chart menu. Apparently the problem was due to the fact that from the beginning of the song to the end the box was unchecked
