### ISSUE TITLE
Error on lua script "c" in fnf Psych Engine

### ISSUE THREAD

**Issue by KMZ-BF** [ShadowMario/FNF-PsychEngine#14960]
### Describe your problem here.

I was making an fnf mod on Psych Engine 0.6.3 and everything was going well, but out of nowhere it started giving an error that said "error on lua script" and followed by a text box with the letter c. I didn't do anything that could have caused this error, it just happened out of nowhere, the mod was working and without me changing anything this error appeared. I already searched the internet for what I could do to solve this but nothing I found helped. I've also tried reinstalling Psych Engine twice and even using version 0.7.3 and nothing helped, the error continued to appear even when changing versions. However, I sent my mod file to my tablet to see if it worked in the Psych Engine that is downloaded there, which is exactly the same version that I was trying to make on the PC and it worked there (I emphasize that I didn't make any changes to the file, the The error started to appear on its own and on my tablet it worked without me doing anything). If anyone can help me, I would be very gratefull #
![Captura de tela 2024-06-23 214110](https://github.com/ShadowMario/FNF-PsychEngine/assets/173642873/ec3a1502-529c-49be-b501-a17c650c7610)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by KMZ-BF** [comment]
So.....I managed to solve the problem myself, apparently the problem was that my mod folder had a letter with an acute accent and for some reason this causes fnf to not read the mod correctly. I don't know if that was really the problem, but I know that eliminating that acute accent made the problem go away.

**Comment by Lorekeeper49** [comment]
Normally I'd tell you to close this, but since I've never seen an error that just contains a single letter before, I'd like an explanation as to what it means and why it happens before you close it

**Comment by M4st3rG4m4** [comment]
> So.....I managed to solve the problem myself, apparently the problem was that my mod folder had a letter with an acute accent and for some reason this causes fnf to not read the mod correctly. I don't know if that was really the problem, but I know that eliminating that acute accent made the problem go away.

Yeah, if your mod folder or in any script is an accent or letters like "ñ" script don't work lmao
