### ISSUE TITLE
I want to be given a second chance to the psych engine discord server

### ISSUE THREAD

**Issue by JacksonTheSkylanderDude67** [ShadowMario/FNF-PsychEngine#14970]
### Describe your bug here.

I was banned probably a year ago or years ago. I already consulted the error of my ways and I have matured and I would like to have a second chance to the server.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by raxyd** [comment]
put the question label instead of bug. If you have matured, they might let you in.
