### ISSUE TITLE
Vocals stuttering when playing week with dialogue

### ISSUE THREAD

**Issue by DamianBossPL** [ShadowMario/FNF-PsychEngine#14976]
### Describe your bug here.

After loading the game if you proceed to play a week with dialogue (in this instance week 6), the first song's vocals track will stutter. After the song ending, restarting or exiting it doesn't seem to stutter again for the rest of the session (in my testing, correct me if I'm wrong).

### Command Prompt/Terminal logs (if existing)

```bash
gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
source/backend/Discord.hx:63: Discord Client initialized
source/backend/Discord.hx:42: (Discord) Connected to User (damianbosspl)
source/backend/Paths.hx:251: oh no its returning null NOOOO (assets/shared/images/storymenu/friendWeek.png)
source/states/LoadingState.hx:159: Setting asset folder to week6
source/backend/Conductor.hx:124: new BPM map BUDDY []
gamemodeauto: dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by IdkWhatAmIDoin** [comment]
Youre missing libgamemode.so, as i see. Also, you dont have your image of the week in assets/shared/images/storymenu/friendWeek.png. Based on the name of the file (libgamemode.so) it may be is a library that youre missing. Make sure youve installed every library from Haxe.

**Comment by IdkWhatAmIDoin** [comment]
I used Windows only, so my answer could be wrong.

**Comment by IdkWhatAmIDoin** [comment]
Im gonna test this on a Linux VM.

**Comment by IdkWhatAmIDoin** [comment]
Nevermind, im switching to linux now

**Comment by ColdlordXRepositories** [comment]
more info
this bug happens on both story mode and freeplay, and only occurs if its the first song you play of the session.
this only happens on songs with dialogue.
its fucking insufferable for people like me
