### ISSUE TITLE
You cannot access the cpp package while targeting neko

### ISSUE THREAD

**Issue by IdkWhatAmIDoin** [ShadowMario/FNF-PsychEngine#14979]
### Describe your problem here.

Hello. I installed Ubuntu yesterday, and i was trying to compile my mod until it gave me this error:

`source/backend/Discord.hx:36: characters 42-74 : You cannot access the cpp package while targeting neko (for cpp.RawConstPointer)`

Is this some kind of code error? After some looking, i think it cannot access a certain package while running through Linux. How do i fix this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by CrusherNotDrip** [comment]
Psych might not even support neko
