### ISSUE TITLE
Botplay in options

### ISSUE THREAD

**Issue by XS09-dev** [ShadowMario/FNF-PsychEngine#1497]
### What feature do you want to get added on the base engine?

Hey I was wondering if you will add botplay in options menu eventually I ask this for one reason: Content. SO alot of mods have cutscenes or dialogue and for cutscenes you top recording when the screen is black pause turn botplay on un pause and start recording. For dialogue you need to record the dialogue stop recording then quickly press pause then turn botplay on. After that you have to unpause and quickly record. I'm just saying this'd be a good feature for content creators

**Comment by HiroOfc** [comment]
there's already botplay at pause menu bruh

**Comment by XS09-dev** [comment]
> there's already botplay at pause menu bruh
> 
> no wait, i think i didn't read everything

> Yea I mean content wise for content creators so they don't have to edit their videos if it's just fnf gameplay

**Comment by Collabvmisgood** [comment]
can't they code it in?

**Comment by Collabvmisgood** [comment]
Is easy all you got to do is set the `PlayState.cpucontrolled` var

**Comment by XS09-dev** [comment]
That's what I am asking for

**Comment by XS09-dev** [comment]
Not really I tried that a new version of psych it didn't work for me.

**Comment by Collabvmisgood** [comment]
Found the code that turns it on 
```
PlayState.cpuControlled = !PlayState.cpuControlled;
PlayState.usedPractice = true;
botplayText.visible = PlayState.cpuControlled;
```

**Comment by Collabvmisgood** [comment]
i think

**Comment by XS09-dev** [comment]
I tried this already it didn't work

**Comment by Collabvmisgood** [comment]
yea I can't
