### ISSUE TITLE
HUD elements in camGame

### ISSUE THREAD

**Issue by JuanSebas1247** [ShadowMario/FNF-PsychEngine#14971]
### What is your question?

I want you to put the arrows of the opponent and the player in the game camera (in the camGame ) by lua In Psych Engine 0.7.3
How do I do it or if you can make a code
 It's for a mod Please

**Comment by StickEXTReal** [comment]
function onCountdownStarted()
runHaxeCode([[
for (strum in game.playerStrums)
{
strum.cameras = [game.camGame];
strum.scrollFactor.set(1, 1);
strum.scale.x = 0.8;
strum.scale.y = 0.8;
}

for (opponent in game.opponentStrums)
{
opponent.cameras = [game.camGame];
opponent.scrollFactor.set(1, 1);
opponent.scale.x = 0.8;
opponent.scale.y = 0.8;
}
for (note in game.unspawnNotes)
{
if (!note.unspawnNotes) {
note.cameras = [game.camGame];
note.scrollFactor.set(1, 1);
note.scale.x = 0.9;
note.scale.y = 0.9;
if (note.isSustainNote) {
note.scale.y = 2.7;
}
}

};
]])
end
