### ISSUE TITLE
Vocals crashed the game

### ISSUE THREAD

**Issue by Typicalperson486** [ShadowMario/FNF-PsychEngine#14982]
### Describe your bug here.

I placed my songs voices and instrumental into PsychEngine\mods\songs\salted (the songs name)
I made sure everything is right, the names are Voices.ogg and Inst.ogg
I booted up psych engine, got to the chart editor, entered 'salted', clicked reload audio and it crashed entirely.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't do anything to the build

**Comment by FinderFromMac** [comment]
#14851 is also having the same issue
