### ISSUE TITLE
Image returning Null / Haxe Logo even though everything seems to be correct

### ISSUE THREAD

**Issue by HJacet** [ShadowMario/FNF-PsychEngine#14989]
### Describe your problem here.

Error message via CMD 
source/backend/Paths.hx:253: oh no its returning null NOOOO (assets/shared/images/BIGFATWATERMARK.png)

Here's the code inside TitleState.hx that I edited (var hjSpr:FlxSprite is included in the hx file, but not in the image)
![sdeffees](https://github.com/ShadowMario/FNF-PsychEngine/assets/106554377/644b2a8f-533a-4fd9-ad01-708fa4844c08)
hjSpr.visible gets set to true later in the code, but only a Haxe Logo appears

Any help appreciated !!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Edited TitleState.hx

**Comment by CrusherNotDrip** [comment]
where is the image located?

**Comment by HJacet** [comment]
> where is the image located?

It’s located in “assets/shared/images”

**Comment by BernardoGP4504** [comment]
> > where is the image located?
> 
> It’s located in “assets/shared/images”

You sure it's called "BIGFATWATERMARK"?

**Comment by HJacet** [comment]
> > > where is the image located?
> > 
> > 
> > It’s located in “assets/shared/images”
> 
> You sure it's called "BIGFATWATERMARK"?

Yes I am 100% sure
![image_2024-06-28_115827644](https://github.com/ShadowMario/FNF-PsychEngine/assets/106554377/3930c34d-50e8-4434-b847-f9851ab097ff)
