### ISSUE TITLE
How to learn how to *code*

### ISSUE THREAD

**Issue by ghost** [ShadowMario/FNF-PsychEngine#14984]
### What is your question?

Ok so, i want to ask how did y´all learn how to code in haxe, and basically modify the psych engine without viewing any tutorials or finding any tutorials. How did y´all learn it ?

**Comment by nguyenkiet1234d** [comment]
Actually, the question is quite simple, first try to memorize the functions and classes and their uses. The second thing you have to do is code and practice it yourself continuously 
That will make it easier for you to memorize functions and classes and how to write correct code that at least works
Hope it helps you a little
