### ISSUE TITLE
.exe file not exporting!!! womp womp!! :(

### ISSUE THREAD

**Issue by splootyaxolotl** [ShadowMario/FNF-PsychEngine#14998]
### Describe your problem here.

Attempting to compile using <path> lime test windows and getting this error (path is an actual path im not just typing path in lmfao)

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/79873517/e218b88c-70b0-4762-b1a2-e5e31be9a3cc)
And it exports along with the files, but no .exe file is created

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes. I edited MainMenuState.hx and changed "donate" to my Discord. I changed PlayState.hx to add my own accuracy notes (e.g. "You Suck!, Bad, Good, Sick!". I changed OutdatedState.hx to add my own note saying that people don't need to update to the newer version (if there will be) to play my mod. No code changes. I changed CreditsState.hx to add me there. And finally (oh thank god) I changed HScript.hx to change all "TeaCall"s to "Tea"

**Comment by xxyuee** [comment]
haxelib set flixel-addons 3.2.1
