### ISSUE TITLE
Will you fix the 0.6.3 src?

### ISSUE THREAD

**Issue by PandamanAF** [ShadowMario/FNF-PsychEngine#14996]
### Will you fix the 0.6.3's src?

Oh,hi there,actually,the src of 0.6.3,0.7,0.7.2 have some problems,but except 0.7.2,other versions' problem is hard to fix,such as 0.6.3-You can't make color by lua,0.7-always the "SHIT" response in the song,0.7.2-have trouble in DadbattleSpotlight event and "Tea" is "TeaCall" in the src so the complie will have error.
The most important thing,0.6.3 is the most famous version of psychengine,but because of its src,the players or new developers may have some trouble in it,so I don't know if you can fix 0.6.3 src only,it's very important.
I've been used this engine for some years,I really like this engine.
If you can't fix the 0.6.3 src,I can understand you,I don't know how many people ask this question,if you are bored about this question,you can actually ignore,I really hope the 0.6.3's src will be fixed,so will the 0.6.3 src be fixed or not?I think if 0.6.3 src is normal,more players will use this engine

**Comment by LarryFrosty** [comment]
No.

Stop using outdated versions.

**Comment by PandamanAF** [comment]
> No.
> 
> Stop using outdated versions.

Yeah,I know,but the biggest problem is src,I don't know why every src have problem,you know that

**Comment by CrusherNotDrip** [comment]
you cant update an outdated version

**Comment by Benlik89** [comment]
just get 0.7.3

**Comment by Arolox666** [comment]
It's not problem with the src but with the libraries versions. BTW IDK the versions I'm just saying tis the problem with that.

**Comment by PandamanAF** [comment]
> It's not problem with the src but with the libraries versions. BTW IDK the versions I'm just saying tis the problem with that.

Oh,you give me the idea,now I know how to solve it,thanks.
