### ISSUE TITLE
(REQUEST) Unlock songs for Free Play after completing a week

### ISSUE THREAD

**Issue by CrimsonRed01** [ShadowMario/FNF-PsychEngine#15]
I don't know a thing about coding so this engine is honestly a big help with how simple and easy everything is.
But do you think it would be possible to include a feature that unlocks songs after finishing a week? Let's say I finish Week 1, a message or something similar will appear at the end saying I've unlocked a song (I could be 1 or more, who knows).

Another thing I thought of, though it isn't necessary, is to lock the following weeks until you clear the current one. So until I clear Week 1, I won't be able to do Week 2 and so on.
**Edit:** I should also say the ability to lock weeks should be optional.

**Comment by ShadowMario** [comment]
Please, read the Wiki before making a request.
