### ISSUE TITLE
Adding freeplay only songs is confusing

### ISSUE THREAD

**Issue by PersonNanoexe** [ShadowMario/FNF-PsychEngine#150]
Nothing is explained in the wiki, and adding them is just genuinely confusing
I suggest updating the wiki with this

**Comment by ShadowMario** [comment]
It's not confusing, you literally just have to add a Week but hide the Week from Story Mode
![Screenshot_1](https://user-images.githubusercontent.com/44785097/134830206-5061cfef-5b8b-4422-b5cb-a8ea7f8b89c5.png)
