### ISSUE TITLE
remove difficulty in freeplay

### ISSUE THREAD

**Issue by DendyGG** [ShadowMario/FNF-PsychEngine#15009]
### What is your question?

how to remove difficulties in freeplay so that “normal” always starts?

I'm making on source code

**Comment by brusakas** [comment]
search this in freeplaystate.hx:
```
if (controls.UI_LEFT_P)
			changeDiff(-1);
		else if (controls.UI_RIGHT_P)
			changeDiff(1);
		else if (upP || downP) changeDiff();
```
add a /* on top of 'if (controls.UI_LEFT_UP), then a */ at the bottom of else if (upP || downP) changeDiff();

then compile




voila

**Comment by DendyGG** [comment]
> search this in freeplaystate.hx:
> 
> ```
> if (controls.UI_LEFT_P)
> 			changeDiff(-1);
> 		else if (controls.UI_RIGHT_P)
> 			changeDiff(1);
> 		else if (upP || downP) changeDiff();
> ```
> 
> add a /* on top of 'if (controls.UI_LEFT_UP), then a */ at the bottom of 'else if (upP || downP) changeDiff();'
> 
> your basically getting rid of it even tho it stays in the source code
> 
> VOILA :)
> 
> i also forgot, search `'changeDiff();'` make sure to comment it but putting // beside that code

does it only run "normal"?

**Comment by brusakas** [comment]
> > search this in freeplaystate.hx:
> > ```
> > if (controls.UI_LEFT_P)
> > 			changeDiff(-1);
> > 		else if (controls.UI_RIGHT_P)
> > 			changeDiff(1);
> > 		else if (upP || downP) changeDiff();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > add a /* on top of 'if (controls.UI_LEFT_UP), then a */ at the bottom of 'else if (upP || downP) changeDiff();'
> > your basically getting rid of it even tho it stays in the source code
> > VOILA :)
> > i also forgot, search `'changeDiff();'` make sure to comment it but putting // beside that code
> 
> does it only run "normal"?

yep

**Comment by DendyGG** [comment]
> > > search this in freeplaystate.hx:
> > > ```
> > > if (controls.UI_LEFT_P)
> > > 			changeDiff(-1);
> > > 		else if (controls.UI_RIGHT_P)
> > > 			changeDiff(1);
> > > 		else if (upP || downP) changeDiff();
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > add a /* on top of 'if (controls.UI_LEFT_UP), then a */ at the bottom of 'else if (upP || downP) changeDiff();'
> > > your basically getting rid of it even tho it stays in the source code
> > > VOILA :)
> > > i also forgot, search `'changeDiff();'` make sure to comment it but putting // beside that code
> > 
> > 
> > does it only run "normal"?
> 
> yep

OK, the question is resolved
