### ISSUE TITLE
Run 'skipCountdown' after things are loaded/after a set time?

### ISSUE THREAD

**Issue by Kirsenal** [ShadowMario/FNF-PsychEngine#15000]
### Describe your problem here.

I've noticed there's a weird bug where using skipCountdown causes delay and issues with the inputs and the chart (arrows will be considered "Sick!" when they are hit later than should be). I was thinking that maybe this is an issue with loading all the assets and/or chart and grabbing skipCountdown at the same moment, causing discrepancy and breaking it. What do I add into the lua script to grab skipCountdown AFTER assets and stuff are actually loaded in, or otherwise what do I type to run skipCountdown after like maybe a few miliseconds (which might be enough)? I'm still new to lua so

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Kirsenal** [comment]
Okay so basically I fixed the issue by putting skipCountdown on function onStartCountdown instead of onCreate :D

**Comment by SomeGDPerson123** [comment]
its issue #15000!!
