### ISSUE TITLE
How do i remove the difficulty arrows?

### ISSUE THREAD

**Issue by toppat-lol** [ShadowMario/FNF-PsychEngine#15004]
### What is your question?

Im making a mod (wow) and i only have one difficulty, how do i remove it?
im using source

**Comment by DendyGG** [comment]
https://youtu.be/k9LPGIeLWcE?feature=shared

**Comment by toppat-lol** [comment]
> https://youtu.be/k9LPGIeLWcE?feature=shared

in the current version
