### ISSUE TITLE
1 keep getting errors while using a specific lua script

### ISSUE THREAD

**Issue by randomcharter** [ShadowMario/FNF-PsychEngine#15008]
### Describe your problem here.

it always says "ERROR: (onCooldownStarted!) mods/(mod name)/custom_events/(lua script) lua 26 attempt to index local 'nextEvent' (a nil value)" please help me fix this problem

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I'm only using the base PE

**Comment by TechnikTil** [comment]
can you send the script?
