### ISSUE TITLE
my .ogg files are drunk

### ISSUE THREAD

**Issue by Benlik89** [ShadowMario/FNF-PsychEngine#15006]
### Describe your bug here.

for some reason when i press reload audio in the chart editor i get an error 

### Command Prompt/Terminal logs (if existing)

```bash
openfl/media/Sound.hx (line 407)
backend/Paths.hx (line 442)
states/editors/ChartingState.hx (line 1508)
states/editors/ChartingState.hx (line 1452)
states/editors/ChartingState.hx (line 418)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Error loading sound from file: mods/BullSHIT!/songs//23mp3/Inst.ogg
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by xxyuee** [comment]
did you change the file extension?

**Comment by Benlik89** [comment]
yes

**Comment by xxyuee** [comment]
use a file converter instead

**Comment by Benlik89** [comment]
it actually fixed the problem

**Comment by Benlik89** [comment]
file converter used, xxyuee saved my day!
