### ISSUE TITLE
when im opening freeplay or leaving from song i see this, how to fix that?? help please faster i need do an chart

### ISSUE THREAD

**Issue by WakiN13** [ShadowMario/FNF-PsychEngine#15005]
### Describe your problem here.

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/173832072/4be40ef0-ef92-49df-a59e-9b25b6529142)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by xxyuee** [comment]
you probably saved a song's chart in the weeks folder.
