### ISSUE TITLE
mi cancion personalizada ubicada en mods/spx-mod/songs/philly-re no carga

### ISSUE THREAD

**Issue by SimonplaygamerX** [ShadowMario/FNF-PsychEngine#15010]
### Describe your problem here.

Estoy creando un mod, el va añadir un remix de la cancion de philly y muchisimas cosas mas.
Pero por mas que si carga el archivo de _mods/spx-mod/data/philly-re_ no carga el de _mods/spx-mod/songs/philly-re_
ya verifique que en la carpeta este el archivo _Inst_ (como la cancion esta descargada de youtube no tiene _Voices_)
Uso ´Psych Engine 0.6.2

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Del juego base edite a la cancion del menu y de mi mod añadi 2 weeks, 41 personajes y 4 songs (no todas las songs y weeks son de mi mod, provienen de otros mods) tambien agrege muchos events

### soy nuevo creando mods pero ya tengo experiencia mediana

**Comment by crisjonas7** [comment]
¿La canción es OGG?
Por cierto, recomiendo que hables en Inglés aquí

**Comment by SimonplaygamerX** [comment]
Si, le cambie el formato de mp3 a ogg

**Comment by SimonplaygamerX** [comment]
Estoy bien pendejo, solo le cambié el nombre a inst.ogg pero el archivo seguía siendo .mp3 xD
En fin, ya lo solucione
