### ISSUE TITLE
How to make a not not miss when you CLEARLY miss it???

### ISSUE THREAD

**Issue by BlockySlicerReal** [ShadowMario/FNF-PsychEngine#15019]
### What is your question?

https://github.com/ShadowMario/FNF-PsychEngine/assets/72654405/64c5b33d-4adf-4d71-856b-da6a99c3c4ce

skip to like 0:25 for the question

so basically, caveman need make note not miss when miss, because hit note=die, but when miss note, miss, me need note
 to have no miss :3

[EX_Noteluafilebutitsactuallya.txt](https://github.com/user-attachments/files/16061250/EX_Noteluafilebutitsactuallya.txt)

**Comment by Lorekeeper49** [comment]
Something weird is going on here, it seems like the only note that's getting correctly iterated is the one on lane 0.  Looking at the code there doesn't seem to be anything within it that would cause that

**Comment by SomeGDPerson123** [comment]
add the "ignoreNote" attribute
