### ISSUE TITLE
"could not load lime@lime_application_create_prime" 

### ISSUE THREAD

**Issue by chezzyboy21** [ShadowMario/FNF-PsychEngine#15014]
### Describe your bug here.

it says this everytime i open the newest port of the engine, this string of code idk anything about and i cant even play the newest version cause of it 

### Command Prompt/Terminal logs (if existing)

```bash
"could not load lime@lime_application_create_prime"
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by LavaBiteYT** [comment]
Same! Try reinstalling it.

**Comment by chezzyboy21** [comment]
i have reinstalled it, same problem
