### ISSUE TITLE
Compiling Vs. Sonic.exe source code problem

### ISSUE THREAD

**Issue by Rolee0707** [ShadowMario/FNF-PsychEngine#15024]
### Describe your problem here.

I'm trying to compile the source code of the Vs. Sonic.exe 2.5, but I keep getting the same error:

C:/HaxeToolkit/haxe/lib/discord_rpc/git/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
source/flixel/addons/transition/FlxTransitionableState.hx:67: lines 67-77 : Warning : switchTo is deprecated, use startOutro
source/Main.hx:78: characters 61-65 : Float should be Int
source/Main.hx:78: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:78: characters 61-65 : ... For function argument 'child'
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
source/Alphabet.hx:198: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:162: characters 13-21 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:8854: lines 8854-8869 : Warning : switchTo is deprecated, use startOutro
source/PlayState.hx:117: characters 40-48 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:165: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:1017: characters 16-24 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:60: characters 28-36 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:952: characters 18-26 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:986: characters 18-26 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:78: characters 57-58 : Int should be flixel.util.FlxAxes
source/FreeplayState.hx:78: characters 57-58 : ... For optional function argument 'repeatAxes'
source/PlayState.hx:1552: lines 1552-1585 : Warning : (WUnusedPattern) This case is unused
source/PlayState.hx:1667: characters 78-84 : Warning : (WUnusedPattern) This pattern is unused
source/PlayState.hx:3339: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:3341: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:3344: characters 27-35 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:34: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:84: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PracticeSubState.hx:34: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:7956: characters 78-81 : Warning : (WUnusedPattern) This pattern is unused
source/editors/EditorPlayState.hx:37: characters 13-21 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:92: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:94: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound

I tried commands from compiling tutorials, but still the same error. I don't know if this source code needs specific commands, but if someone has already compiled it, I would appreciate it if you can send it here what the commands are or what is the solution to this error message.

Here is the source code:
https://github.com/duckiewhy/exe-2.5-code

And yes, this is a psych engine

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Im using the source code of the Vs. Sonic.exe 2.5 source code so it's edited

**Comment by brusakas** [comment]
update your flixel or smth

**Comment by Rolee0707** [comment]
> update your flixel or smth (why are you commenting on psych engine issues)

Because that one source code is kinda outdated, nobody is active there. Also, which version should I use? (recently I used haxelib set flixel 4.11.0 the command)

**Comment by brusakas** [comment]
> > update your flixel or smth (why are you commenting on psych engine issues)
> 
> Because that one source code github page is kinda outdated, nobody is active there. Also, which version should I use? (recently I used haxelib set flixel 4.11.0 the command)

thats why u have that error, u r using outdated flixel

**Comment by Rolee0707** [comment]
> > > update your flixel or smth (why are you commenting on psych engine issues)
> > 
> > 
> > Because that one source code github page is kinda outdated, nobody is active there. Also, which version should I use? (recently I used haxelib set flixel 4.11.0 the command)
> 
> thats why u have that error, u r using outdated flixel, just do haxelib install flixel

I solved it, and it needed flixel 4.11.0
