### ISSUE TITLE
Compiling Error In (0.7.1h)

### ISSUE THREAD

**Issue by ALIASKEV** [ShadowMario/FNF-PsychEngine#15020]
_i have this problem compiling in 0.7.1h_
_"source/states/PlayState.hx:107: characters 32-39 : Type not found : HScript"_
-
**My Libraries:** "actuate: [1.9.0]
box2d: [1.2.3]
BrewScript: [6.1.80]
discord_rpc: [git]
flixel-addons: 3.2.3 [git]
flixel-demos: [3.2.0]
flixel-templates: [2.7.0]
flixel-tools: [1.5.1]
flixel-ui: [2.6.1]
flixel: [5.8.0]
flxanimate: [git]
haxelib: [4.1.0]
hscript: [2.5.0] (i tried 2.4.0 too)
hxCodec: 3.0.2 [git]
hxcpp: [4.3.2]
layout: [1.2.1]
lime-samples: [7.0.0]
lime: [8.1.2]
linc_luajit: [git]
newgrounds: [2.0.3]
openfl-samples: [8.7.0]
openfl: [9.3.3]
polymod: [git]
SScript: [21.0.0]
systools: [1.1.0]
thx.semver: [0.2.2]
tjson: [1.4.0]"

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Base Game

**Comment by LarryFrosty** [comment]
Downgrade your SScript version to 8.1.6

**Comment by ALIASKEV** [comment]
I had tried this but it didn't work either, now I'm on 0.7.3 since it doesn't give me problems like 0.7.1h.
