### ISSUE TITLE
how to hide misses score and rating in a song (Not all just some)

### ISSUE THREAD

**Issue by DarkSeryunox** [ShadowMario/FNF-PsychEngine#15021]
### Describe your problem here.

i want to hide the misses score and rating below the health bar in a few songs because yes, but idk how to do it because i am dumb, pls help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by xxyuee** [comment]
function onCreatePost()
    if songName == 'song1' or songName == 'song2' then
        setProperty("scoreTxt.visible", false)
    end
end

**Comment by DarkSeryunox** [comment]
Tysm broo
