### ISSUE TITLE
Type not found : TeaCall

### ISSUE THREAD

**Issue by MiguelMinha** [ShadowMario/FNF-PsychEngine#15026]
### Describe your bug here.

source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i just replaced original fonts to my fonts

**Comment by Shadow06735** [comment]
replace everything called "TeaCall" in the HScript to "Tea"

**Comment by MiguelMinha** [comment]
i

**Comment by DuskDragonNight75** [comment]
doesnt work
