### ISSUE TITLE
How to hide timebar in a song (not all only a few selected ones)

### ISSUE THREAD

**Issue by DarkSeryunox** [ShadowMario/FNF-PsychEngine#15022]
### Describe your problem here.

i want hide timebar in a song, a few of them actually, and i am too dumb to actually know how to do it, pls help (with source code if can because cool)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by nguyenkiet1234d** [comment]
If it's lua then I can but the source I'm quite vague about it
