### ISSUE TITLE
Story mode and week editor crashes the game

### ISSUE THREAD

**Issue by CalebBLS** [ShadowMario/FNF-PsychEngine#15034]
### Describe your bug here.

Don't know why, but whenever I try to open the story menu or week editor it throws an error at me and crashes. I don't have access to any of the files listed, it's not the source version I have.

Included is copy-pasted from the crash log file.

### Command Prompt/Terminal logs (if existing)

```bash
Paths.hx (line 356)
MenuItem.hx (line 17)
StoryMenuState.hx (line 105)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Deleted all the song folders from assets/data and assets/songs and added new songs, but didn't touch the files.

**Comment by ColdlordXRepositories** [comment]
you're not supposed to delete the base game songs
you are supposed to add new songs through the mods folder, not assets

**Comment by SomeGDPerson123** [comment]
I think it's trying to load songs that don't exist, but idk tbh
