### ISSUE TITLE
There is smth wrong with my song

### ISSUE THREAD

**Issue by ProZaycrazy** [ShadowMario/FNF-PsychEngine#15039]
### Describe your problem here.

![FNF MOD Problem](https://github.com/ShadowMario/FNF-PsychEngine/assets/174764798/337ca6da-c8e2-4d4a-8145-0c5e41b2bce5)

I am trying to add my song to the chart but it keeps saying this!!!!
my file is the name of the song
i have the Inst.ogg and the Voices.ogg but it says that there is something wrong with the vocals.

can you help?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ProZaycrazy** [comment]
NVM ITS FIXED NOW!

**Comment by SomeGDPerson123** [comment]
then close the issue lol
