### ISSUE TITLE
source/CreditsState.hx:110: characters 51-58 : Expected , or ]

### ISSUE THREAD

**Issue by BBJAKABucketBoyJay** [ShadowMario/FNF-PsychEngine#15035]
### Describe your problem here.

i dont know whats going on but when i try compiling it gives me this : 
source/CreditsState.hx:110: characters 51-58 : Expected , or ]

if anyone has a fix please tell me

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by xxyuee** [comment]
can you show the code at line 110

**Comment by BBJAKABucketBoyJay** [comment]
> can you show the code at line 110

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/152812636/c90d0f83-f5c7-4d5a-b4ac-c40607942d34)

**Comment by xxyuee** [comment]
thats line 101

**Comment by BBJAKABucketBoyJay** [comment]
ooh

**Comment by BBJAKABucketBoyJay** [comment]
right sorry
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/152812636/08c4f7c0-3a6a-417d-96ad-3a782fca0661)

**Comment by BBJAKABucketBoyJay** [comment]
WAIT IM SO DUMB 😭  thats line 111
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/152812636/8fd24a24-730b-4c23-ae7f-cdf0eb7bc24d)

**Comment by BBJAKABucketBoyJay** [comment]
> thats line 101
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/152812636/f13fa0ca-5c30-4809-90de-042a592ef751)
heres 110

**Comment by BBJAKABucketBoyJay** [comment]
im just gonna change files
