### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Andorid8493002** [ShadowMario/FNF-PsychEngine#15031]
### Describe your problem here.

![Immagine 2024-07-03 214450](https://github.com/ShadowMario/FNF-PsychEngine/assets/174650819/99017d4f-a7ec-4234-baa4-b14e6f17decf)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i changed the song and the notes display

**Comment by HourOfEternity** [comment]
It says "Uncaught Error: Invalid char 91 at position 127". The game cannot read special characters like ñ or ć. You just need to replace it to fix the error.

**Comment by Andorid8493002** [comment]
i'm not very practical with these kinds of things, if i send the files to you can you help me fix it?
[capaproject.json](https://github.com/user-attachments/files/16228983/capaproject.json)
[capaproject-hard.json](https://github.com/user-attachments/files/16228984/capaproject-hard.json)
[events.json](https://github.com/user-attachments/files/16228985/events.json)

**Comment by HourOfEternity** [comment]
I found a simple mistake happens to the best of us. In events.json, you are missing an open bracket on line 6. Hope this helps!

Also, if you don't already have it, I highly recommend downloading Visual Studio Code, as it highlights easily missed errors.
