### ISSUE TITLE
I'm getting an error when building a game with lime test windows -debug

### ISSUE THREAD

**Issue by Darkness-apl** [ShadowMario/FNF-PsychEngine#15048]

**Comment by Darkness-apl** [comment]
> ### 如何解决???
> `source/Prebuild.hx:15: Building... E:/My-document/funkin/.haxelib/flxanimate/3,0,4/flxanimate/animate/FlxAnim.hx:26: characters 9-17 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound E:/My-document/funkin/.haxelib/funkin,vis/git/src/funkin/vis/dsp/SpectralAnalyzer.hx:7: characters 8-22 : Type not found : grig.audio.FFT`
> 
> ![微信screenshot_20240706171927]（https://github.com/ShadowMario/FNF-PsychEngine/assets/132057301/3d7638d5-eef8-4f16-98b8-72a3a002306d)

**Comment by Darkness-apl** [comment]
1. [ ] # # #15047

**Comment by FinderFromMac** [comment]
erm, what?
