### ISSUE TITLE
I want to know how to change the color brightness for lua while changing the character color

### ISSUE THREAD

**Issue by longge90** [ShadowMario/FNF-PsychEngine#15044]
### What is your question?

I want to know how to change the color brightness for lua while changing the character color

**Comment by nguyenkiet1234d** [comment]
What do you mean by changing the color of the timebar text, botplay and score, right?

**Comment by longge90** [comment]
To be precise, it is a depth adjustment for the changed color, but I don't know how to do it. I want to ask
