### ISSUE TITLE
I'm stuck, again

### ISSUE THREAD

**Issue by Baskanguish** [ShadowMario/FNF-PsychEngine#15045]
### Describe your problem here.

when I typed in "lime test windows" it says "Library lime is not installed" what should I do?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by xxyuee** [comment]
haxelib install lime
haxelib set lime 8.0.1
