### ISSUE TITLE
Invaild field:volume

### ISSUE THREAD

**Issue by chazbtw55** [ShadowMario/FNF-PsychEngine#15043]
### Describe your bug here.

When i try to play a certain song it crashes

### Command Prompt/Terminal logs (if existing)

```bash
states/stages/Kitchen.hx (line 336)
backend/MusicBeatState.hx (line 173)
backend/MusicBeatState.hx (line 204)
backend/MusicBeatState.hx (line 170)
states/PlayState.hx (line 3254)
backend/MusicBeatState.hx (line 64)
states/PlayState.hx (line 1716)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 426)
openfl/display/DisplayObject.hx (line 1398)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i didnt

**Comment by sigma993240** [comment]
hmm i think you're playing rotten smoothie?
