### ISSUE TITLE
I FIXED IT

### ISSUE THREAD

**Issue by guywhodoesstufforsomethin** [ShadowMario/FNF-PsychEngine#15046]
### Describe your bug here.

Whenever i try to open Psych engine it says "could not load lime@lime_application_create_prime" how do i fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

all i did was unzip the mod example folder.

**Comment by baobab121** [comment]
close the issue then

**Comment by FuseIsHere813** [comment]
@guywhodoesstufforsomethin close
