### ISSUE TITLE
My note spashes playing in 1 fps

### ISSUE THREAD

**Issue by Ilya02273** [ShadowMario/FNF-PsychEngine#15041]
### Describe your bug here.

I maked a port of indie cross splashes, in note splash debug splashes works fine, but in game he playing in 1 fps, Android

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by inky03** [comment]
did you save the notesplash config?? you're supposed to press Enter twice (or the A button in some (unofficial) mobile ports, iirc) to save the config

**Comment by Ilya02273** [comment]
Да

**Comment by Ilya02273** [comment]
[Uploading noteSplashes.zip…]()

**Comment by Ilya02273** [comment]
Sorry about my ignore, im busy
