### ISSUE TITLE
I really need help with this

### ISSUE THREAD

**Issue by Blue567Epic** [ShadowMario/FNF-PsychEngine#15055]
### Describe your bug here.

![Screenshot 2024-07-07 102217](https://github.com/ShadowMario/FNF-PsychEngine/assets/174790241/ed80030e-2b93-4295-8cba-f2b69e3cb168)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by CrusherNotDrip** [comment]
It looks like the notes aren't being loaded correctly

**Comment by Blue567Epic** [comment]
> what’s the null object reference even pointing to

idk

**Comment by Blue567Epic** [comment]
> It looks like the notes aren't being loaded correctly

when i pressed the notes it crashed
also the bf sprite didnt play

**Comment by Blue567Epic** [comment]
why close it
