### ISSUE TITLE
The program run but it instantly crashes

### ISSUE THREAD

**Issue by marlnunz** [ShadowMario/FNF-PsychEngine#15057]
### Describe your bug here.

Hi. I downloaded Psych engine and set it up (set my keybinds and settings) and tested it on a song, It crashed and when i opened the game again it crashed. I tried opening it about 6 times and it crashed too. I trried reinstalling and it still crashes

### Command Prompt/Terminal logs (if existing)

```bash
backend/Paths.hx (line 275)
backend/Paths.hx (line 247)
states/TitleState.hx (line 209)
states/TitleState.hx (line 170)
flixel/util/FlxTimer.hx (line 205)
flixel/util/FlxTimer.hx (line 295)
flixel/FlxGame.hx (line 750)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CrusherNotDrip** [comment]
Taking a wild guess that logoBumpin is broken or missing or something
