### ISSUE TITLE
Psych Engine doesn't run on x64 Windows 11.

### ISSUE THREAD

**Issue by 1928821929** [ShadowMario/FNF-PsychEngine#15056]
### Describe your bug here.

I downloaded Psych Engine 0.6.3 on my x64 Windows 11 laptop because i need old version for a mod. When i try to launch the .exe file, it runs the proccess but doesnt launch the program itself. What can i do?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by 1928821929** [comment]
nvm i just needed to install a newer version

**Comment by ColdlordXRepositories** [comment]
try redownloading the game

**Comment by ShadowMario** [comment]
0.6.3 is not supported anymore
