### ISSUE TITLE
song not loading

### ISSUE THREAD

**Issue by NBWgamer2012** [ShadowMario/FNF-PsychEngine#15051]
### Describe your bug here.

my songs Inst.ogg is not loading correctly

### Command Prompt/Terminal logs (if existing)

```bash
openfl/media/Sound.hx (line 407)
backend/Paths.hx (line 442)
states/editors/ChartingState.hx (line 1508)
states/editors/ChartingState.hx (Line 1452)
states/editors/ChartingState.hx (line 418)
flixel/ui/FlxButton.hx (Line 521)
flixel/ui/FlxButton.hx (Line 507)
openfl/events/EventDispatcher.hx (line 444)
openfl/dispay/DisplayObject.hx (line 1400)

Uncaught Error: Error loading sound file: mods/My-Mod/song//mario-why/inst.ogg
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not change anything cause IDK how to read .hx

**Comment by CrusherNotDrip** [comment]
> is the second slash intentional for the file path?

and if that wasn't the case did you just rename the mp3 to an ogg?
