### ISSUE TITLE
How to add cutscenes in psych engine 0.7.3

### ISSUE THREAD

**Issue by IdkWhatAmIDoin** [ShadowMario/FNF-PsychEngine#15058]
### Describe your problem here.

Hello. I already know how to play cutscenes in lua, but i recently switched to source code and cannot understand how i play a cutscene. Can anyone help me out?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't.

**Comment by DarylDixonFR** [comment]
did you make it?

**Comment by DarylDixonFR** [comment]
i did it, after a lil bit of research. give me your discord name and ill help you if u want to hehe
