### ISSUE TITLE
My custom week do not work

### ISSUE THREAD

**Issue by brenozuh** [ShadowMario/FNF-PsychEngine#15050]
### Describe your bug here.

I made the file .json, put it in the weeks folder with the name of week1 and it didn't show up the week in story mode, also when I put the week icon in the file name .json it says that there is no png file with that name

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by FinderFromMac** [comment]
you might have the same problem with this 
#14851

**Comment by FinderFromMac** [comment]
Also where did you put the week? If it's on the mods folder then it's making a conflict since you named the custom .json week file "week1" and it's breaking the assets folder

**Comment by ColdlordXRepositories** [comment]
you can't name your week any of the existing weeks, otherwise it will not show up
