### ISSUE TITLE
Psych Engine doesn't recognize my charts inside the mods folder

### ISSUE THREAD

**Issue by DarkerFalcon** [ShadowMario/FNF-PsychEngine#15052]
### Describe your problem here.

![1720289809464](https://github.com/ShadowMario/FNF-PsychEngine/assets/111909940/e744453c-f013-4873-a1c1-4c801e79e9df)
Hey there. I have a problem with Psych Engine. Whenever i put my charts into the mods folder, Psych engine doesn't recognize it and it gives me this annoying error. It seems that it wants that i put my charts in the assets/shared/data folder. But i want to put my custom charts into the mods folder, like this: mods/data. Is there a way to fix this? Any help will be appreciated!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by baobab121** [comment]
What's wrong with that? just add to mods/data/its-complicated/its-complicated-hard.json

**Comment by CrusherNotDrip** [comment]
looks like a complicated issue (guys im so funny)
