### ISSUE TITLE
Can't build also with Visual Studio components

### ISSUE THREAD

**Issue by JosueCr4ft** [ShadowMario/FNF-PsychEngine#15060]
### Describe your bug here.

I can't build Psych Engine 0.7.3.
I installed Visual Studio 2019 with the components. I also tried "setup-msvc-win.bat".

Haxe list:
flixel-addons: [3.2.1]
flixel-tools: [1.5.1]
flixel-ui: [2.5.0]
flixel: [5.5.0]
flxanimate: [git]
hxCodec: [git]
hxcpp: [4.3.2]
hxdiscord_rpc: [git]
lime: [8.0.1]
linc_luajit: [git]
openfl: [9.3.2]
SScript: [7.7.0]
tjson: [1.4.0]

### Command Prompt/Terminal logs (if existing)

```bash
BUILDING GAME
------------------------SScript 7.7.0 Macro------------------------
Special Thanks:
- CrowPlexus

Checking version...
You are using the 4.2.5 version of Haxe, SScript works best with Haxe 4.3.2 or newer. Update your Haxe version.
Continuing...
-------------------------------------------------------------------

D:\JOSUE\fnf mod\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by JosueCr4ft** [comment]
#14890 I solved it.
Apart of MSVC v142 - VS 2019 C++ x64/x86 build tools and Windows SDK (10.0.17763.0) I installed these components:

- C++ Profiling tools
- C++ CMake tools for windows
- C++ ATL for v142 build tools (x86 & x64)
- C++ MFC for v142 build tools (x86 & x64)
- C++/CLI support for v142 build tools (14.21)
- C++ Modules for v142 build tools (x64/x86)
- Clang Compiler for Windows

**Comment by PumpkinSheee** [comment]
> #14890 I solved it. Apart of MSVC v142 - VS 2019 C++ x64/x86 build tools and Windows SDK (10.0.17763.0) I installed these components:
> 
> * C++ Profiling tools
> * C++ CMake tools for windows
> * C++ ATL for v142 build tools (x86 & x64)
> * C++ MFC for v142 build tools (x86 & x64)
> * C++/CLI support for v142 build tools (14.21)
> * C++ Modules for v142 build tools (x64/x86)
> * Clang Compiler for Windows

nah this still didnt work for me 😭
