### ISSUE TITLE
How to get High Score from a song using lua (0.7.3)

### ISSUE THREAD

**Issue by KillerAvecRage** [ShadowMario/FNF-PsychEngine#15062]
### Describe your problem here.

Same question as I asked last year, but I need it for 0.7.3 this time, as the code I used for 0.6.3 no longer works

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by potatex2** [comment]
![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/96308850/eb4b328d-0627-4376-af3f-1f3117265521)
it's likely still going to be ```lua getScore()```

**Comment by KillerAvecRage** [comment]
> ![image](https://private-user-images.githubusercontent.com/96308850/347195553-eb4b328d-0627-4376-af3f-1f3117265521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NzIzNDEsIm5iZiI6MTcyMDU3MjA0MSwicGF0aCI6Ii85NjMwODg1MC8zNDcxOTU1NTMtZWI0YjMyOGQtMDYyNy00Mzc2LWFmM2YtMWYzMTE3MjY1NTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDAwNDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZmZhODYzNTQ1NTFmODU0MDY1M2Q3ZGVmN2U4ZDRmNGYzYTU0Y2I1MDVmNjUwZDM5NTcxNGIzNDM2NmU1NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4fabZRmN5_rXs2nhP1zItiV8Bq8TWZCqooGIrTbgfps) it's likely still going to be `getScore()`

doesn't `getScore()` show the current score in the song? What I want to know is how to get the Highscore, the one that shows in Freeplay

**Comment by TechnikTil** [comment]
runHaxeCode([[
 	import backend.Paths;
	import backend.Highscore;
	return Highscore.getScore(Paths.formatToPath(game.SONG.song), game.storyDifficulty);
]])

should give you the high score, probably a better way to do this
