### ISSUE TITLE
Error compilling fragment shader

### ISSUE THREAD

**Issue by Mordeez** [ShadowMario/FNF-PsychEngine#15068]
### Describe your bug here.

So i tried playing the Angry luigi mod, but on the lyric part some popup show up it says: “Error!

[openfl.display.Shader] ERROR: Error compiling

fragment shader

0:68: S0012: Global variable initializer must be a constant expression

#ifdef GL_ES

#ifdef GL_FRAGMENT_PRECISION_HIGH

precision highp float;

#else

precision mediump float;

#endif

#endif

ANGRY LUIG

varying float openfl_Alphav; varying vec4 openfl_ColorMultiplierv; varying vec4 openfl_ColorOffsetv; varying vec2 openfl_TextureCoordv;”

### Command Prompt/Terminal logs (if existing)

```bash
None
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
Report this issue to the mod creators, not here.
