### ISSUE TITLE
Change the menu layout

### ISSUE THREAD

**Issue by Sahzwi** [ShadowMario/FNF-PsychEngine#15063]
### Describe your problem here.

Hello, i'm a new developer and i'm making a mod with a few friends.

We're struggling to change the menu layout, and the tutorial we've seen so far have only worked on earlier versions of Psych Engine.

We only want to move the menu buttons to the side and also change the scale of them.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by baobab121** [comment]
```haxe
//in this code
for (i in 0...optionShit.length)
{
	var offset:Float = 108 - (Math.max(optionShit.length, 4) - 4) * 80;
	var menuItem:FlxSprite = new FlxSprite(0, (i * 140) + offset);
	menuItem.antialiasing = ClientPrefs.data.antialiasing;
	menuItem.frames = Paths.getSparrowAtlas('mainmenu/menu_' + optionShit[i]);
	menuItem.animation.addByPrefix('idle', optionShit[i] + " basic", 24);
	menuItem.animation.addByPrefix('selected', optionShit[i] + " white", 24);
	menuItem.animation.play('idle');
	menuItems.add(menuItem);
	var scr:Float = (optionShit.length - 4) * 0.135;
	if (optionShit.length < 6)
		scr = 0;
	menuItem.scrollFactor.set(0, scr);
        // changing scale (all buttons)
        menuItem.scale = (scaleX, scaleY) // your values instead of scaleX and scaleY (1.5, 1.5 for example)
        // moving buttons (all buttons. and btw if you do this with Y, then all the buttons will be in the same place on Y)
        menuItem.x(value) // your X value
	menuItem.updateHitbox();
	menuItem.screenCenter(X);
        // move buttons code (separately). add so if you need to
        switch [i]
        {
                case 0: // story_mode
                        menuItem.x = 0
                        menuItem.y = 0
                        // you can change the scale also here with 'menuItem.scale' but separately for each button
                case 1: // freeplay
                        menuItem.x = 0
                        menuItem.y = 0
               // with the rest also up to 6 (0 - 6)
               // you can do for example 0, 2 and not write other values
               // 0 - story_mode, 1 - freeplay, 2 - mods, 3 - awards, 4 - credits, 5 - donate, 6 - options
         }
}
```

**Comment by Sahzwi** [comment]
THANK YOU SO MUCH

I've been struggling to find help anywhere, but yeah this helps a lot

Appreciate you wanting to help, but the mod's supposed to be an inside joke between my group of friends, so yeah lol

Thanks again!

**Comment by Sahzwi** [comment]
Reopening this again, because it didn't work, i managed to make the positions of the menu buttons work. but not to scale it.

**Comment by xxyuee** [comment]
try menuItem.scale.set(x, y)

**Comment by Sahzwi** [comment]
Thank you!

**Comment by Kdiggisskvssjgsisivsizivsisv** [comment]
> ```hx
> //in this code
> for (i in 0...optionShit.length)
> {
> 	var offset:Float = 108 - (Math.max(optionShit.length, 4) - 4) * 80;
> 	var menuItem:FlxSprite = new FlxSprite(0, (i * 140) + offset);
> 	menuItem.antialiasing = ClientPrefs.data.antialiasing;
> 	menuItem.frames = Paths.getSparrowAtlas('mainmenu/menu_' + optionShit[i]);
> 	menuItem.animation.addByPrefix('idle', optionShit[i] + " basic", 24);
> 	menuItem.animation.addByPrefix('selected', optionShit[i] + " white", 24);
> 	menuItem.animation.play('idle');
> 	menuItems.add(menuItem);
> 	var scr:Float = (optionShit.length - 4) * 0.135;
> 	if (optionShit.length < 6)
> 		scr = 0;
> 	menuItem.scrollFactor.set(0, scr);
>         // changing scale (all buttons)
>         menuItem.scale = (scaleX, scaleY) // your values instead of scaleX and scaleY (1.5, 1.5 for example)
>         // moving buttons (all buttons. and btw if you do this with Y, then all the buttons will be in the same place on Y)
>         menuItem.x(value) // your X value
> 	menuItem.updateHitbox();
> 	menuItem.screenCenter(X);
>         // move buttons code (separately). add so if you need to
>         switch [i]
>         {
>                 case 0: // story_mode
>                         menuItem.x = 0
>                         menuItem.y = 0
>                         // you can change the scale also here with 'menuItem.scale' but separately for each button
>                 case 1: // freeplay
>                         menuItem.x = 0
>                         menuItem.y = 0
>                // with the rest also up to 6 (0 - 6)
>                // you can do for example 0, 2 and not write other values
>                // 0 - story_mode, 1 - freeplay, 2 - mods, 3 - awards, 4 - credits, 5 - donate, 6 - options
>          }
> }
> ```
> 
> just add the code you need. btw I am an new developer too and I can help if I can.

what do i do with this? where do i put it.
