### ISSUE TITLE
Hanks Redemption Mod

### ISSUE THREAD

**Issue by Deyv420** [ShadowMario/FNF-PsychEngine#15069]
### Describe your bug here.

so i downloaded Hank's Redemption mod and i got an error, theres 3 track in the new version every track works except "Revenge" when i try to play the track i get an error please help me fix this

### Command Prompt/Terminal logs (if existing)

```bash
flixel/tweens/misc/VarTween.hx (line 99)
flixel/tweens/misc/VarTween.hx (line 55)
flixel/tweens/FlxTween.hx (line 1263)
flixel/FlxGame.hx (line 750)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: The object does not have the property "zoom"
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I mean, i just got the mod into the game

**Comment by KillerAvecRage** [comment]
Not a Psych Engine related issue, post your issue on the page of the mod

**Comment by Deyv420** [comment]
it said to post issue here so i did it pls get me help or smth

czw., 25 lip 2024, 21:00 użytkownik ShadowMario ***@***.***>
napisał:
