### ISSUE TITLE
Detect charting mode in 0.6.3?

### ISSUE THREAD

**Issue by SomeGDPerson123** [ShadowMario/FNF-PsychEngine#15067]
### What is your question?

Hi, I'm making a LUA script for Psych Engine 0.6.3 and am wondering how to detect charting mode using a LUA script.

**Comment by potatex2** [comment]
Not sure if this will help much for whatever you want to do with it, but it's mentioned in [the wiki itself](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Variables) in the third listing

**Comment by SomeGDPerson123** [comment]
I figured it out myself and forgot to close this 🤣
