### ISSUE TITLE
compilation problems

### ISSUE THREAD

**Issue by LaCuevaDeipeLol** [ShadowMario/FNF-PsychEngine#1506]
### Describe your bug here.

When I tried to compile the latest version of the source code of 11/29 I got this error
![image](https://user-images.githubusercontent.com/88949308/143975705-de2b9ad1-10c5-4a89-aa60-7c9470020e0a.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, nothing

**Comment by SrtHero278** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/1419#issuecomment-980794707
