### ISSUE TITLE
Psych Engine crashes when loading story mode (Pluto's Reprisal V2)

### ISSUE THREAD

**Issue by pro-introvert** [ShadowMario/FNF-PsychEngine#15064]
### Describe your bug here.

I downloaded Psych Engine and put the mod i wanted to play in the "mods" folder, the mod in question is Pluto's Reprisal V2. When i try to go into story mode, the game crashes and gives me this error popup.
![Screenshot 2024-07-09 155003](https://github.com/ShadowMario/FNF-PsychEngine/assets/175130273/0dce6818-c289-480f-9ec2-9fb6c3b8b981)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not edit anything in the folder for the mod.

**Comment by zyntaxStar** [comment]
Use psych engine v0.5.2 for it.
