### ISSUE TITLE
Engine looping after playing a song

### ISSUE THREAD

**Issue by wizdeck31** [ShadowMario/FNF-PsychEngine#15076]
### Describe your problem here.

I just downloaded the Accelerant psych engine port but then i didnt do anything song used to work fine but it looped so i restarded the engine but it locks into a black screen with nothing but an fps counter how do i fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by wizdeck31** [comment]
> ### Describe your problem here.
> 
> I just downloaded the Accelerant psych engine port but then i didnt do anything song used to work fine but it looped so i restarded the engine but it locks into a black screen with nothing but an fps counter how do i fix this?
> ### Are you modding a build from source or with Lua?
> 
> Lua
> ### What is your build target?
> 
> Windows x64
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> 
> No

my version is 0.6.3 btw

**Comment by TechnikTil** [comment]
> > ### Describe your problem here.
> > I just downloaded the Accelerant psych engine port but then i didnt do anything song used to work fine but it looped so i restarded the engine but it locks into a black screen with nothing but an fps counter how do i fix this?
> > ### Are you modding a build from source or with Lua?
> > Lua
> > ### What is your build target?
> > Windows x64
> > ### Did you edit anything in this build? If so, mention or summarize your changes.
> > No
> 
> my version is 0.6.3 btw

some mods broke after 0.7, thats why

**Comment by nguyenkiet1234d** [comment]
After the 0.7.3 update, almost all command lines that are related or work on 0.6.3 cannot run or do not run as expected.
