### ISSUE TITLE
flying logo

### ISSUE THREAD

**Issue by Velikiycho** [ShadowMario/FNF-PsychEngine#15074]
### Describe your problem here.

Let's say, uh, I need the logo (in the title) to move smoothly up and down, how do I do this? I can use lua and source
v7.3.0

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TechnikTil** [comment]
kind of like the ludum dare title screen?

**Comment by Velikiycho** [comment]
> kind of like the ludum dare title screen?

yes

**Comment by Velikiycho** [comment]
ok, looks like I don't need this anymore, anyone who wants can leave a reply
