### ISSUE TITLE
Compiling error with pysch engine 0.6.3

### ISSUE THREAD

**Issue by MateoG1211** [ShadowMario/FNF-PsychEngine#15071]
### Describe your bug here.

when i type lime test windows
it shows this

'lime' is not recognized as an internal or external command,
operable program or batch file.

before you say "oh you didnt install it right" eventually i somehow fix it, then the next day it comes up again and i eventually fix it, it repeats this over and over again and its getting really annoying, i followed a tutorial compiling tutorial carefully and it still shows this up everyday

can someone help?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i only edited PlayState.hx to edit the timer

**Comment by CrusherNotDrip** [comment]
`haxelib run lime setup`
