### ISSUE TITLE
custom character doesnt work

### ISSUE THREAD

**Issue by zomehz** [ShadowMario/FNF-PsychEngine#15073]
![image_2024-07-10_075942396](https://github.com/ShadowMario/FNF-PsychEngine/assets/150028648/d573a61c-da89-43d6-985f-61b847947e4a)
### Describe your bug here.

I've been trying to make a fnf mod and when i try to add my custom character it says "ERROR: No Animation Found"
and I've been looking on how to fix it and nothings worked yet.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by zomehz** [comment]
[fnfxml.zip](https://github.com/user-attachments/files/16164040/fnfxml.zip)
heres the xml if needed

**Comment by CrusherNotDrip** [comment]
stupid question but did you even make a image for it?

**Comment by zomehz** [comment]
I forgot to close this because i found how
