### ISSUE TITLE
Original pre-0.7 compilation

### ISSUE THREAD

**Issue by SomeGDPerson123** [ShadowMario/FNF-PsychEngine#15078]
### What is your question?

Hi, I was wondering if there would be any point in the future where you could possibly add back or just make the original source code pre-0.7 optional? I think some of the changes are cool, but the removal of stuff like getProperty and setProperty just feel foolish to do. Issues like these with the current compilation are the reason why I only use 0.6.3. Like, [MY mod](https://gamebanana.com/mods/523232) can't work because of removals like this?! I put work into this! _(I'm not mad, I'm just asking a question: will it come back at any point in time? its a yes or no question)_

**Comment by CrusherNotDrip** [comment]
getProperty and setProperty still exist???

[also you can use this](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7)

**Comment by SomeGDPerson123** [comment]
ok yea I can use that but I use a lot of normal get/setProperty instead of get/setPropertyFromClass, is there any way to deal with that? sry if it's obvious bc I'm not on my computer rn

**Comment by LarryFrosty** [comment]
No.
Who would ever want to go to the hell that is pre-0.7 source.

**Comment by ShadowMario** [comment]
setProperty and getProperty did NOT get removed, and I can't make the source "optional", that's not how coding works.
