### ISSUE TITLE
I Need help Right Now (BG CHANGE 7.0.2)

### ISSUE THREAD

**Issue by CollabTheDeveloper** [ShadowMario/FNF-PsychEngine#15070]
### What is your question?

soo, there is a stage change bg in 7.0.2??? i need it soo much, anyone have it?
if dont, can you make a script event to change bg to "Sadbackground"?????

**Comment by TechnikTil** [comment]
that is basically impossible using lua, but if you hid the sprites for the second bg, then make an event where it hides the original sprites, and showed the other sprites, that should basically be it
