### ISSUE TITLE
Invalid acces to field x

### ISSUE THREAD

**Issue by Leo9556** [ShadowMario/FNF-PsychEngine#15077]
### Describe your problem here.

I used a code to put some icons over other icons but it keep me saying this:
![error](https://github.com/ShadowMario/FNF-PsychEngine/assets/175265417/10005005-420b-4568-9b1b-d23fd46c8a8c)
but when i tried this on a version that i dont compiled its working well.
I tried this on Psych engine 0.7.3

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TechnikTil** [comment]
can you send the code?

**Comment by CrusherNotDrip** [comment]
can you send the code?

**Comment by Leo9556** [comment]
its not necesary, i solved it

**Comment by CrusherNotDrip** [comment]
> its not necesary, i solved it

close issue then
