### ISSUE TITLE
I have a problem with a Friday Night Funkin mod error. [Lime.Utils.Preloader] ERROR there is no asset library named "Videos".

### ISSUE THREAD

**Issue by SquidRoblox** [ShadowMario/FNF-PsychEngine#15080]
### What is your question?

I have a problem with a Friday Night Funkin mod error. [Lime.Utils.Preloader] ERROR there is no asset library named "Videos".
Can somebody help me with it i'm unable to do anything..
I have the folder in the files but it still does the same thing.
Im also not good at coding or making anything thats why im asking...

PLEASE SOMEBODY HELP

![image](https://github.com/ShadowMario/FNF-PsychEngine/assets/175327727/32b5f61e-d599-41ba-9a2d-7cd64604d73d)

**Comment by FuseIsHere813** [comment]
Possibly missing the videos.json file in the manifest folder.
