### ISSUE TITLE
cutscene hot working (psych engine lastest version source code)

### ISSUE THREAD

**Issue by oyuncuhanl** [ShadowMario/FNF-PsychEngine#15085]
### Describe your problem here.

I am just workin on my mod and I was finding this process with the source code, but the moment I added the cutscene, the game crashed after opening the week and this was true for every cutscene, I could not do this problem for 2 days.
actually I used to be able to add it to version 6.3 but it crashes for some reason in 7.3 source code?

maybe there's something I'm missing.

**Comment by LarryFrosty** [comment]
In Project.xml, go to line 32 and move the "VIDEOS _ALLOWED" define outside the of the officialBuild section.![Screenshot_2024-07-12-19-46-57-79.jpg](https://github.com/user-attachments/assets/f714d966-31cb-4b18-99d2-d4a4f30ad862)

**Comment by oyuncuhanl** [comment]
worked but won't start the song

**Comment by oyuncuhanl** [comment]
> In Project.xml, go to line 32 and move the "VIDEOS _ALLOWED" define outside of the officialBuild section.![Screenshot_2024-07-12-19-46-57-79.jpg](https://private-user-images.githubusercontent.com/80482125/348251120-f714d966-31cb-4b18-99d2-d4a4f30ad862.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzc3NzMsIm5iZiI6MTcyMTM3NzQ3MywicGF0aCI6Ii84MDQ4MjEyNS8zNDgyNTExMjAtZjcxNGQ5NjYtMzFjYi00YjE4LTk5ZDItZDRhNGYzMGFkODYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA4MjQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNDAxZjRjNjc5MmYwYTk4OTdkZjE2MGIxMTI5YTU4NGYyOWM2YjJmZGMwNjk4NjdiYTAzYWM4MmY1YmJmYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dpHtLhla-CxteWY4f1iHEU_GKeMg77-sHh5-GiF2hyE)

worked but won't starting the song

**Comment by oyuncuhanl** [comment]
worked but won't starting the song
