### ISSUE TITLE
Winning Icons In 0.7.3

### ISSUE THREAD

**Issue by BunfriendNinja2007** [ShadowMario/FNF-PsychEngine#15083]
### What feature do you want to get added on the **base** engine?

How To Add Winning Icons In Psych Engine 0.7.3 Source Code

winning icons.

Source

Windows x32/x86

**Comment by FinderFromMac** [comment]
This is actually a question

**Comment by FinderFromMac** [comment]
please change the issue

**Comment by BunfriendNinja2007** [comment]
Why?
