### ISSUE TITLE
help me i'm new in this game

### ISSUE THREAD

**Issue by Chicaga3310** [ShadowMario/FNF-PsychEngine#15082]
### Describe your problem here.

while playing mfm deluxe mod i got this:

C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
StoryMenuState.hx (line 321)
StoryMenuState.hx (line 260)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/too-clergy/too-clergy.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't edit anything

**Comment by Chicaga3310** [comment]
here's the link where i got this mod https://gamebanana.com/mods/452699

**Comment by SPC-JustARandomImpostor** [comment]
it appeares the file too-clergy.json doesnt exist. so thats probably why its crashing.
maybe try it on a different difficulty if you can.
