### ISSUE TITLE
how to upload or publish my mod

### ISSUE THREAD

**Issue by zomehz** [ShadowMario/FNF-PsychEngine#15081]
### Describe your problem here.

I need help to publish my mod so my friends can play it or upload it to gamebanana or gamejolt

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CrusherNotDrip** [comment]
this is not the place to ask

**Comment by zomehz** [comment]
Where should i ask

**Comment by CrusherNotDrip** [comment]
> Where should i ask

idk but heres where you should start
https://gamebanana.com/add?gameid=8694
