### ISSUE TITLE
NoteSplash effect doesn't use antialiasing in the gameplay

### ISSUE THREAD

**Issue by Osmaci123** [ShadowMario/FNF-PsychEngine#15086]
### Describe your bug here.

NoteSplashes does not use antialiasing when I am inside a song/level. Does anyone know why this happens if it is enabled in the source code/hx files?

Pd: if you play without rgb of the noteSplash.hx file, it not happens

![Captura de pantalla 2024-07-12 142725](https://github.com/user-attachments/assets/11a1e569-41dc-4fa9-9ac4-7d5c6cea5bc7)
![Captura de pantalla 2024-07-12 144318](https://github.com/user-attachments/assets/3a16d223-991a-4820-8bfa-04f04d70cb73)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
Fixed on the latest commit https://github.com/ShadowMario/FNF-PsychEngine/commit/174fed8c32f4071d9fb3509fed141980dbfaf805

**Comment by Osmaci123** [comment]
I don't know if it is only me that the NoteSplashes they are still without antialiasing in the last or this (https://github.com/ShadowMario/FNF-PsychEngine/commit/174fed8c32f4071d9fb3509fed141980dbfaf805)
commit
