### ISSUE TITLE
Maybe a Spanish version?

### ISSUE THREAD

**Issue by LionKrono** [ShadowMario/FNF-PsychEngine#15093]
### What feature do you want to get added on the **base** engine?

The Experimental branch already has an Portuguese translation, I could help with the spanish one!

It would be cool!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by crowplexus** [comment]
there's upcoming mods with a spanish translation, everyone is just waiting for 1.0 to release

**Comment by ShadowMario** [comment]
https://github.com/user-attachments/assets/590434eb-f72a-473f-86bd-140f6e7e57a6

**Comment by PaodeMelYTBR** [comment]
mas que po-

**Comment by SantiagoCalebe** [comment]
Use .lang file.

**Comment by ShadowMario** [comment]
Languages are more properly softcodable now
