### ISSUE TITLE
FlxSoundTray's sound loops when changing the volume inside of a song

### ISSUE THREAD

**Issue by NickMGC** [ShadowMario/FNF-PsychEngine#15095]
### Describe your bug here.

I am using the latest version of Psych Engine, specifically the main branch. When changing the volume, the sound that indicates volume change doesn't stop playing like it should and instead loops on stepHit(). I'm guessing this is somehow related to the resyncVocals function and I suspect that it is due to FlxG.sound.music.play(), not sure though.

Here's how to replicate this issue: 
Change the volume rapidly until it starts looping. Although you might not get it first try, it's kinda inconsistent.

Here's the bug in action:
https://github.com/user-attachments/assets/a8349e53-f048-42a3-9d5a-28ef59011d24

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited minor things in PlayState.hx that do not affect sound.

**Comment by superpowers04** [comment]
This issue only happens with the main branch. The experimental branch seems to already have this fixed. The bug is related to the game trying to play and/or edit the time of an empty FlxSound. Flixel gets really fucky with empty sounds

**Comment by NickMGC** [comment]
oh ok
