### ISSUE TITLE
custom animation mid song

### ISSUE THREAD

**Issue by BrokeHrt** [ShadowMario/FNF-PsychEngine#15091]
### Describe your problem here.

so i have this custom animation file that is supposed to be a transition animation for my character. the problem is i have no clue how to code it into the game. i have the files as png and xml files and idk how to code it into the game. tried youtube tutorials but nothing is helpful with what i need

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, coded new story menu and menu music

**Comment by nguyenkiet1234d** [comment]
If you want the character to perform animation, you can use event. If it's animation for the stage, you should use it
function onUpdate()
if curStep ==  Enter the number of steps in the chart editor then
luaSpritePlayAnimation('name tag sprites', 'Name the animation you want', true);
end 
end
If you want the stages to play the animation continuously, change == to >=
it's over
