### ISSUE TITLE
Crash???

### ISSUE THREAD

**Issue by yippeeman** [ShadowMario/FNF-PsychEngine#15094]
### Describe your bug here.

it crashed once i saved an edited version of Fresh

### Command Prompt/Terminal logs (if existing)

```bash
states/PlayState.hx (line 1520)
states/PlayState.hx (line 954)
backend/BaseStage.hx (line 120)
states/stages/SchoolEvil.hx (line 94)
states/stages/SchoolEvil.hx (line 37)
backend/BaseStage.hx (line 60)
states/stages/SchoolEvil.hx (line 9)
states/PlayState.hx (line 390)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i tried to use the debug menu to make sure i dont bang my head on the table trying to get She Calls Me Daddy Too

**Comment by CrusherNotDrip** [comment]
That edited version of fresh seems to use schoolEvil as the stage

**Comment by yippeeman** [comment]
> That edited version of fresh seems to use schoolEvil as the stage

i tried to make it schoolEvil for the stage for fun
