### ISSUE TITLE
change stage

### ISSUE THREAD

**Issue by huhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuhuh** [ShadowMario/FNF-PsychEngine#15090]
### What feature do you want to get added on the **base** engine?

i think there should be a event where you can change the stage from one to another

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by CrusherNotDrip** [comment]
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> 
> Proper credit that was forgotten

fail

**Comment by nguyenkiet1234d** [comment]
You can use commands instead of events to change the stage

**Comment by nguyenkiet1234d** [comment]
first set up and create sprites, here is an example;
function onCreate() =>>> start 
-- stages 1
makeLuaSprite('Name the tag as you like', 'The address is in the images folder',  Fill in the starting position x (x is horizontal, as the x value increases, the image increases from left to right), y(similar to x but the vertical value increases, the height down and down increases);
setProperty("(your given name).scale.x", x(Fill in the x value you want to zoom the image);
setProperty("(your given name).scale.y", y(Fill in the y value you want to zoom the image);
addLuaSprite('(your given name)', false)

--stages 2
Similar to stage 1
end 
end
And if sprites are created first, they will be the first stages. If you do as above, stages 2 will appear and stages will cover stage 1. If you want stages 1 to appear first, hide stages 2there is a lot of code for this but you should use setProperty('(the name you give to stages 2).visible', false)
when you want stages 2 to show again just write down that code and turn it on true .for example
function onUpdate()
if curStep >=  Fill in the step number, please check in the chart then
setProperty('your name stages 2', true)
end 
end
That's all, I hope it helps bro

**Comment by nguyenkiet1234d** [comment]
If you want to make more adjustments, go to mairio shadow's AIP lua document
