### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Hopka-fnf** [ShadowMario/FNF-PsychEngine#1509]
### Describe your problem here.

when I downloaded all the necessary libraries and after installing vscode 2019, then after the "warning" nothing else happens. I waited for over 6 hours, but nothing changes ...
![image](https://user-images.githubusercontent.com/69728441/143980226-e3121083-a6f5-49a0-b311-035b6851441c.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Jonnycatmeow** [comment]
you should use the newer haxe

**Comment by HafimieForever** [comment]
well, warnings can be ignored

**Comment by HafimieForever** [comment]
but this thing is kinda weird

**Comment by Hopka-fnf** [comment]
> you should use the newer haxe

installed a new version, but ... still can't build. 
![image](https://user-images.githubusercontent.com/69728441/144040321-73c56f1e-2feb-42c0-92a3-b4b85f0cc1a5.png)

**Comment by Collabvmisgood** [comment]
it might be taking a long time to build wait

**Comment by Hopka-fnf** [comment]
> 
this is VERY unlikely. before that, I installed libraries and everything was fine. after installing 64 bits (I had 32 bits), now I am suffering with this problem.
