### ISSUE TITLE
Perfect Rating In Psych Engine

### ISSUE THREAD

**Issue by BunfriendNinja2007** [ShadowMario/FNF-PsychEngine#15097]
### What is your question?

Can I Set The Perfect Rating For The Full Sick Combo On Psych Engine As Forever Engine?

**Comment by gameygu-0213** [comment]
this question is a LITTLE confusing

but if you're softmodding (as in with LUA/HScript) i couldn't tell you if you are able to, im assuming, add a perfect rating

However, you can add it with hardmodding [Rating.hx](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/backend/Rating.hx) by adding a little bit of extra code 

example

replace `var ratingsData:Array<Rating> = [new Rating('sick')]; //highest rating goes first` with `var ratingsData:Array<Rating> = [new Rating('perfect')]; //highest rating goes first`

and add below it:

`var rating:Rating = new Rating('sick');`
		`rating.ratingMod = 1;`
		`rating.score = 350;`
		`rating.noteSplash = true;`
		`ratingsData.push(rating);`

below it


then go into [ClientPrefs](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/backend/ClientPrefs.hx) and under ratingOffset but above sickWindow add:
`public var perfectWindow:Int = 15;`

then finally head into [PlayState](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/states/PlayState.hx) and search for "fullComboUpdate"
under that function it should look like this:
`var sicks:Int = ratingsData[0].hits;`
			`var goods:Int = ratingsData[1].hits;`
			`var bads:Int = ratingsData[2].hits;`
			`var shits:Int = ratingsData[3].hits;`

change it to
`var perfects:Int = ratingsData[0].hits;`
			`var sicks:Int = ratingsData[1].hits;`
			`var goods:Int = ratingsData[2].hits;`
			`var bads:Int = ratingsData[3].hits;`
			`var shits:Int = ratingsData[4].hits;`

and make sure that below there where it says `else if (sicks > 0)`
change it to `else if (sicks > 0 || perfects > 0)` to allow the perfects to count toward the SFC counter

then finally you should be able to place an image named `perfect.png` where the other rating images like `sick.png` are and it SHOULD show up
