### ISSUE TITLE
I want to make notes fade out once they hit a certain point

### ISSUE THREAD

**Issue by Zombie7z** [ShadowMario/FNF-PsychEngine#15101]
### Describe your problem here.

Very similar to osu mania hidden modifier, I don't know where to begin besides probably needing to use setProperty to change something in the source

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by nguyenkiet1234d** [comment]
you can use it as event
This is my opponent's note
function onEvent(name, value1, value2) --start

	Time = tonumber(value1)
	Alpha = tonumber(value2)
	
    if name == 'OpponentNotesFade' then
	
for i=0,3 do
    noteTweenAlpha(i+16, i, Alpha, Time, 'QuadOut')

    end
end
end
this is player notes
function onEvent(name, value1, value2) --start

	Time = tonumber(value1)
	Alpha = tonumber(value2)
	
    if name == 'PlayerNotesFade' then
	
for i=4,7 do
    noteTweenAlpha(i+16, i, Alpha, Time, 'QuadOut')

    end
end
end
Paste it into the event and name it properly PlayerNotesFade and OpponentNotesFade

**Comment by nguyenkiet1234d** [comment]
Oh I remember there is a code for that, wait for me for a few days haha

**Comment by Zombie7z** [comment]
> Oh I remember there is a code for that, wait for me for a few days haha

ok tysm for your help 🙏

**Comment by Zombie7z** [comment]
> Oh I remember there is a code for that, wait for me for a few days haha

Hey did you ever find the code?

**Comment by nguyenkiet1234d** [comment]
I remember there was a video or website for that code but I haven't found it yet because it's been a long time since I last saw that code, sorry

**Comment by Zombie7z** [comment]
> I remember there was a video or website for that code but I haven't found it yet because it's been a long time since I last saw that code, sorry

Ok appreciate you trying, if you ever come across it, or someone who would know how to make it please come back to this post, because I'm really struggling to code this

**Comment by nguyenkiet1234d** [comment]
ok, I will try to find that code

**Comment by Zombie7z** [comment]
I found the answer if anyone ever needs it
`local FadePosition = 500
luaDebugMode = true

function onEvent(name, value1, value2)
    if name == 'DisapearingNotesEvent' then
        FadePosition = value1
    end
end

function onCreate()
    copyAlpha = false
    FadePosition = 500
end

function onUpdatePost()
    for i = 0, getProperty('notes.length')-1 do
        if getSongPosition() >= getProperty('notes.members['..i..'].strumTime') - FadePosition then
            setProperty('notes.members['..i..'].alpha', 0)
        end
    end
end`
put this in a lua event named DisapearingNotesEvent and it should work
