### ISSUE TITLE
i have no idea why the backround isnt working, ive set everything up even putting the "White" in the images

### ISSUE THREAD

**Issue by redtheredisred** [ShadowMario/FNF-PsychEngine#15103]
### Describe your bug here.

null object reference despite it has everything it needs to load

https://github.com/user-attachments/assets/7161da58-75cf-4790-be11-133ebe7763a7

 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by xxyuee** [comment]
can you send the stage json

**Comment by redtheredisred** [comment]
> can you send the stage json

s
