### ISSUE TITLE
how to make a modchart script in which the notes jump?

### ISSUE THREAD

**Issue by RedexZR** [ShadowMario/FNF-PsychEngine#15106]
### Describe your problem here.

example:
![5be4e721add641408d1e6db1c3d2cb8a](https://github.com/user-attachments/assets/7ac2f048-efc4-4cc8-b3f5-a7489f418211)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Sure-I-will-help** [comment]
you could try note tweening

for example you make make it go 100 100 (top right)
50 0 (bottom middle) 0 100 (top left)

[plugging in those numbers wont work]
