### ISSUE TITLE
Change Hit Windows/Arrows Hitboxes values w/ Lua

### ISSUE THREAD

**Issue by YamiDarkness64** [ShadowMario/FNF-PsychEngine#15111]
### Describe your problem here.

Hey, I wanted to ask if anyone knows how to change the Sick/Good/Bad Hit Windows and Safe Frames values (From the Gameplay Settings) with some .lua stuff for a Song in PE's latest version

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by YamiDarkness64** [comment]
> Could you please be more specific?

Okay, let's say I want to make a troll song where the arrow hitbox is small af so you gotta be even more precise to hit the notes
Isn't there anything like setProperty or setPropertyFromClass to change the Arrow Hitboxes?

**Comment by frantastic24** [comment]
#13418

**Comment by YamiDarkness64** [comment]
> #13418

I meant the values in
https://github.com/ShadowMario/FNF-PsychEngine/blob/65494a3375fbceb5d74cfd2231ba668790842a4f/source/backend/ClientPrefs.hx#L72

Like is there a way to change the sickWindow, goodWindow, ect?

**Comment by YamiDarkness64** [comment]
Okay I'm going to close because I just found out
