### ISSUE TITLE
The chart just stops when i do startVideo("video") and I cant press 7

### ISSUE THREAD

**Issue by Realmzer** [ShadowMario/FNF-PsychEngine#15114]
### Describe your problem here.

So right after a video is dont playing the chart just stops playing and it only happens when i call startVideo(""), the video plays but after, the chart just stops entirely and cant press anything.

### Code I used

function onStepHit()
	if curStep == 3360 then
		startVideo('video')
	end
`end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not edit the source code.

**Comment by nguyenkiet1234d** [comment]
i don't know how to put command into a specific frame in github sorry try to copy my command and you can use it to prevent cheating ;)

**Comment by nguyenkiet1234d** [comment]
If it works as you want, close the question bro ;)

**Comment by Realmzer** [comment]
> If it works as you want, close the question bro ;)

i think found out how to just use video sprites
