### ISSUE TITLE
credits not working

### ISSUE THREAD

**Issue by oragne2eletricboogaloo** [ShadowMario/FNF-PsychEngine#15115]
### Describe your problem here.

im trying to add credits to my mod, the file is called 'credits.txt' and it doesnt work.
i used an example line (name::iconname::description::link::0xFFcolor) then modified it (bluebunnyguy::kommit::The guy that made the mod! wowie!::https://x.com/bbsub3::F3F3F3, everything is placeholder), the icons, links and color code exist, but it doesnt appear in-game, any help?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CrusherNotDrip** [comment]
did u put it in `data/`?

**Comment by Suslagreally** [comment]
You have to put the mod into a modpack
![image](https://github.com/user-attachments/assets/912dc70a-08de-4bc3-8376-fd08d0c4489a)

**Comment by oragne2eletricboogaloo** [comment]
> did u put it in `data/`?

yes

**Comment by oragne2eletricboogaloo** [comment]
> You have to put the mod into a modpack ![image](https://private-user-images.githubusercontent.com/153198257/349428049-912dc70a-08de-4bc3-8376-fd08d0c4489a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNTM1NTgsIm5iZiI6MTcyMTI1MzI1OCwicGF0aCI6Ii8xNTMxOTgyNTcvMzQ5NDI4MDQ5LTkxMmRjNzBhLTA4ZGUtNGJjMy04Mzc2LWZkMDhkMGM0NDg5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QyMTU0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWI2MmZjNGRmOTQ0MWQxN2FhY2UzNDI2ZDJlMmQ4MDkwZmFmNDUyYzhmZjM0YThhNGM0MzhiNzM4MTk0NTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AzFfwbykAwz1rbDK3J4onZ3s-FHPhiWpJWzjlyDVYTg)

oh
