### ISSUE TITLE
Da Psych Engine SITCHEEATEEON

### ISSUE THREAD

**Issue by TheWretched08** [ShadowMario/FNF-PsychEngine#15116]
### What is your question?

Are you gonna do a newer version (if you are, what is a rough estimate of how close you are to completing it) of the Psych Engine for the Pit Stop update (i kinda want that shiz rn)

**Comment by NickMGC** [comment]
![image](https://github.com/user-attachments/assets/746f0b2b-7101-4f76-a793-59e519cd89b5)

**Comment by NickMGC** [comment]
I'd recommend closing this issue because Shadow Mario already addressed this question on the [Psych Engine](<https://discord.gg/psychengine>) server.

**Comment by TheWretched08** [comment]
ok not sigma b ut respect it, makes sense bc the updates basically made it a whole new game.
