### ISSUE TITLE
HTML5 not working when I try to play a song on it

### ISSUE THREAD

**Issue by BlueAnd** [ShadowMario/FNF-PsychEngine#15119]
### Describe your problem here.

I compile the game to HTML5 and everything works perfectly but when I enter any song, it stops working. here is what it shows on the inspect element console
![image_2024-07-17_135603436](https://github.com/user-attachments/assets/faaf1363-85f7-49e3-b795-a988e7743649)
im on 0.6.3

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5/Browser

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
0.6.3 is not supported anymore, don't report issues about it.

**Comment by BlueAnd** [comment]
> 0.6.3 is not supported anymore, don't report issues about it.

Why the fuck do versions not be supported?!!!!??!?!
