### ISSUE TITLE
How to create a command line that can rewind time on timeBar and timeBarBG

### ISSUE THREAD

**Issue by nguyenkiet1234d** [ShadowMario/FNF-PsychEngine#15110]
### Describe your problem here.

I want to create a command line that can create a fake time bar and at a certain time it will rewind back to the correct time of that song, like the time rewind scene in pibby apocalypse mod in song (Childs-Play)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by potatex2** [comment]
_i don't know which pe version you're using_, but you can basically use runHaxeCode() to tween the timeLeft value (this script is derived from Nonsense V2 "Old Funk":
```lua
function onStepHit()
	if curStep == 744 then 
	    addHaxeLibrary('flixel.FlxG')
            addHaxeLibrary('flixel.system.FlxSound')
            runHaxeCode([[
            game.updateTime = true;
              FlxTween.tween(game, {songLength: FlxG.sound.music.length}, 2, {ease: FlxEase.cubeIn});
            ]])
    end
    if curStep == 991 then 
        runHaxeCode([[
            FlxTween.tween(game, {songLength: (1000 * 1000)}, 1, {ease: FlxEase.cubeIn})
        ]])
    end
    if curStep == 1001 then 
        runHaxeCode([[
            FlxTween.tween(game, {songLength: FlxG.sound.music.length}, 1.5, {ease: FlxEase.cubeIn})
        ]])
	end
end
```
_obviously just change the values_

**Comment by nguyenkiet1234d** [comment]
Thank you very much
