### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by pxcdesu** [ShadowMario/FNF-PsychEngine#15113]
### Describe your bug here.

[PsychEngine_2024-07-16_15'26'12.txt](https://github.com/user-attachments/files/16244014/PsychEngine_2024-07-16_15.26.12.txt)

### Command Prompt/Terminal logs (if existing)

```bash
objects/Note.hx (line 464)
states/PlayState.hx (line 1758)
flixel/group/FlxGroup.hx (line 787)
states/PlayState.hx (line 1752)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

When I tried to edit the chart and open it, this happened.

**Comment by potatex2** [comment]
are you using any custom noteskins
