### ISSUE TITLE
null object reference in version swapping

### ISSUE THREAD

**Issue by Nkill68** [ShadowMario/FNF-PsychEngine#15118]
### Describe your problem here.

3 years ago I finished a private mod but with the arrival of the shaders without the source code, I started developing it again.
but I don't know why the error comes out in some songs. on the old version of fnf psych engine lua this error did not appear, with the new version it does.
why, please help

old version: 0.4.2

new version: 0.7.3

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Nkill68** [comment]
here the error:

objects/Note.hx (line 464)
states/PlayState.hx (line 1758)
flixel/group/FlxGroup.hx (line 787)
states/PlayState.hx (line 1752)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

**Comment by nguyenkiet1234d** [comment]
Wtf from 0.4.2? hmmm basically the codes and classes are outdated so your old mod script files might conflict with the game

**Comment by nguyenkiet1234d** [comment]
you should rewrite the code from scratch

**Comment by ShadowMario** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Transitioning-Lua-Mods-from-0.6.x-to-0.7
Also works for older versions but your code is so old that you might just rewrite it in case it doesn't help
