### ISSUE TITLE
My-Mod file has crashed my game and i can not play the game

### ISSUE THREAD

**Issue by goobera** [ShadowMario/FNF-PsychEngine#15128]
### Describe your bug here.

![image_2024-07-18_174701144](https://github.com/user-attachments/assets/4e470345-3083-45f9-8d9d-f05d97f8f568)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes i changed the name from my mod to HuckerdooV1 and changed it back

**Comment by MythicalF1uffy** [comment]
your not supposed to keep the my mod folder in the mods folder, you have to take out the stuff in the my mod folder and then put it in the mods folder (my mod folder is in the modTemplate folder in mods btw)
