### ISSUE TITLE
 Is there a way to disable psych enigne error messages without fixing the error?

### ISSUE THREAD

**Issue by Leo9556** [ShadowMario/FNF-PsychEngine#15123]
### What is your question?

Because I'm making a mod and I'm getting error messages that don't affect the game or the gameplay and only the message bothers me.

**Comment by nguyenkiet1234d** [comment]
Normally, if there is an error message from the game, there will be 2 cases
Case 1: your lua script file mod is coded incorrectly
case 2: The game file itself has problems in the asset files

**Comment by nguyenkiet1234d** [comment]
and you can't turn off that notification

**Comment by FNF-fan979** [comment]
![chipi-chipi-chapa-chapa](https://github.com/user-attachments/assets/441a07cc-973a-46bd-aafd-76e3d18b4c23)
chipi chipi chapa chapa!!

**Comment by HourOfEternity** [comment]
> chipi chipi chapa chapa!!

_It follows me everywhere._

**Comment by FNF-fan979** [comment]
the chipi chipi chapa chapa cat _sees_ **you.**

**Comment by ShadowMario** [comment]
luaDebugMode = false, alternatively just fix the errors, shouldn't even be hard at all
