### ISSUE TITLE
Centering difficulty and score text via source

### ISSUE THREAD

**Issue by Your-Local-LordXSimp** [ShadowMario/FNF-PsychEngine#15127]
### Describe your problem here.

I have 0 knowledge of Haxe and I wanna know how to center the difficulty and score text in the freeplay menu via source code. I also wanna know how to make the song select thing go left and right instead of up and down.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I changed the score and difficulty text font and color.

**Comment by FJRODDUR** [comment]
For the score text, search on line 140 of the FreeplayState.hx this line of code: "scoreText.setFormat(Paths.font("vcr.ttf"), 32, FlxColor.WHITE, RIGHT);"

Once you have located it, add this line of code below: scoreText.screenCenter(X);

This should fix your problem
