### ISSUE TITLE
What would you use to check if an arrow is hit?

### ISSUE THREAD

**Issue by MarkAwesomeness** [ShadowMario/FNF-PsychEngine#15120]
### What is your question?

I want something in my stage (coded in LUA) that would react to the opponent or player hitting a specific arrow. It is currently based on whether the opponent or player is playing their left/down/up/right animations, but there will be a situation where I want this to react solely based on the key presses and to work differently depending on the arrow that is hit.

If anyone also knows a way to have the opponent or player NOT play their animation when hitting a (visually) normal arrow, that would be much appreciated.

**Comment by nguyenkiet1234d** [comment]
It's already there in the game's default notes, bro

**Comment by MarkAwesomeness** [comment]
I ended up figuring out how to do both things in the way I needed, I remembered that the NoAnimation note was a default note after I made the post, so I didn't think to elaborate that I didn't want to use that because I wanted the different arrow types along with the lack of animation
