### ISSUE TITLE
Psych Engine 0.6.3 FlxSound Error?

### ISSUE THREAD

**Issue by MythicalF1uffy** [ShadowMario/FNF-PsychEngine#15126]
### Describe your problem here.

While trying to compile 0.6.3 i had gotten the following error: 

source/flixel/system/FlxSound.hx:117: characters 33-46 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 42-55 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:712: characters 27-40 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
C:/Users/download/flixel/5,8,0/flixel/animation/FlxAnimation.hx:239: characters 35-51 : flixel.animation.FlxAnimationController has no field getFrameDuration
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
C:/Users/download/flixel-addons/3,2,3/flixel/addons/effects/chainable/FlxEffectSprite.hx:143: characters 49-58 : flixel.animation.FlxAnimationController has no field numFrames
source/flixel/system/FlxSound.hx:597: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/system/FlxSound.hx:601: characters 19-27 : flash.media.SoundChannel has no field __source
source/FreeplayState.hx:344: characters 25-31 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/FreeplayState.hx:344: characters 25-31 : ... For function argument 'basic'
source/FunkinLua.hx:2221: lines 2221-2224 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/FunkinLua.hx:2221: lines 2221-2224 : ... For function argument 'value'
source/PauseSubState.hx:73: characters 23-33 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PauseSubState.hx:73: characters 23-33 : ... For function argument 'basic'
source/PlayState.hx:582: characters 25-35 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:582: characters 25-35 : ... For function argument 'basic'
source/PlayState.hx:2433: characters 23-29 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2433: characters 23-29 : ... For function argument 'basic'
source/PlayState.hx:2434: characters 23-83 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:2434: characters 23-83 : ... For function argument 'basic'
source/PlayState.hx:1826: characters 25-37 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1826: characters 25-37 : ... For function argument 'basic'
source/PlayState.hx:1873: characters 25-34 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1873: characters 25-34 : ... For function argument 'basic'
source/PlayState.hx:1944: characters 25-36 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/PlayState.hx:1944: characters 25-36 : ... For function argument 'basic'
source/flixel/system/FlxSound.hx:716: characters 17-30 : Warning : flixel.system.FlxSoundGroup was moved to flixel.sound.FlxSoundGroup
source/flixel/system/FlxSound.hx:722: characters 21-25 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:722: characters 21-25 : ... For function argument 'sound'
source/flixel/system/FlxSound.hx:725: characters 15-19 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/flixel/system/FlxSound.hx:725: characters 15-19 : ... For function argument 'sound'
source/editors/ChartingState.hx:1359: characters 24-30 : flixel.system.FlxSound should be flixel.sound.FlxSound
source/editors/ChartingState.hx:1359: characters 24-30 : ... For function argument 'basic'
source/editors/ChartingState.hx:2193: characters 4-42 : flixel.sound.FlxSound should be flixel.system.FlxSound
C:/Users/download/flixel/5,8,0/flixel/ui/FlxButton.hx:288: characters 55-64 : flixel.animation.FlxAnimationController has no field numFrames
source/TitleState.hx:723: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:725: characters 7-58 : flixel.sound.FlxSound should be flixel.system.FlxSound
source/TitleState.hx:729: characters 7-55 : flixel.sound.FlxSound should be flixel.system.FlxSound

can someone please help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i changed fps.hx

**Comment by brusakas** [comment]
1. for main.hx, replace the addChild code with this:
``
addChild(new FlxGame(gameWidth, gameHeight, initialState,
#if (flixel < "5.0.0") zoom, #end
framerate, framerate, skipSplash, startFullscreen));

``

**Comment by brusakas** [comment]
then for the flxsound, delete the system folder and see if it works, and also make sure to replace every instance of flixel.system.flxsound with flixel.sound.flxsound

**Comment by brusakas** [comment]
and for the final one, replace the contents of flxbutton with this https://gist.githubusercontent.com/superpowers04/0b01e40e0f272d134f87c5c30712cb66/raw/2366ea0b8d34b08c74119e22f7690d29e63e7f43/FlxAnimationController.hx
