### ISSUE TITLE
Help me compile the engine!

### ISSUE THREAD

**Issue by woksio1** [ShadowMario/FNF-PsychEngine#15139]
### Describe your problem here.

I'm trying to compile the engine but I kept having this error:
![Zrzut ekranu 2024-07-20 122714](https://github.com/user-attachments/assets/5653c0d8-2d35-487f-b565-21484c511225)

Is there any way to fix it?
And I use lua and sometimes source to mod my build

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No. I was trying to change the icon for the build

**Comment by brusakas** [comment]
replace every instance of teacall with tea in hscript.hx

**Comment by brusakas** [comment]
plus there are also other issues regarding about that error so maybe look at them perhaps
