### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by ChrisIsGood1000** [ShadowMario/FNF-PsychEngine#15131]
### Describe your problem here.

Im trying to make a mod of max design pros brother but whenever i do the sprite name for the sprite and click add/update, it plays all the animations instead of one, and when you try and use it ingame, it just stays on the idle.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ChrisIsGood1000** [comment]
> try using indices=""

I already tried it didn’t play any animation

**Comment by Damir1239** [comment]
you gave the name of the animation example anim="BF dies"

**Comment by ChrisIsGood1000** [comment]
I did, the anim names were “JimmyIdle” “JimmyLeft” “JimmyRight” etc

**Comment by nguyenkiet1234d** [comment]
function onCreate()
makeAnimatedLuaSprite('nametag', 'image file address', x, y); --  Fill in x and y positions

	addLuaSprite('rain', true or false);
	addAnimationByPrefix('name tag', 'loop', 'name animation', 15, true); -- true or fales . true is it will repeat that animation false is only once
  end

**Comment by nguyenkiet1234d** [comment]
'singLEFT' 
  'singRIGHT' 
   'singUP' 
  'singDOWN'
   'singLEFT-alt' 
                'singRIGHT-alt'
     
   'singUP-alt' 
    'singDOWN-alt' 
   'idle-alt' 
   'idle' 
          🙃🙃🙃

**Comment by ChrisIsGood1000** [comment]
> 'singLEFT' 'singRIGHT' 'singUP' 'singDOWN' 'singLEFT-alt' 'singRIGHT-alt'
> 
> 'singUP-alt' 'singDOWN-alt' 'idle-alt' 'idle' 🙃🙃🙃

Already tried that

**Comment by ChrisIsGood1000** [comment]
> 'singLEFT' 'singRIGHT' 'singUP' 'singDOWN' 'singLEFT-alt' 'singRIGHT-alt'
> 
> 'singUP-alt' 'singDOWN-alt' 'idle-alt' 'idle' 🙃🙃🙃

Where would I put these
