### ISSUE TITLE
How do I go from the alt idle animation to the normal idle animation 

### ISSUE THREAD

**Issue by LDcode17** [ShadowMario/FNF-PsychEngine#15132]
### What is your question?

So The event "Alt Idle Animation" let's you go from the normal to the alt idle animation but how do I revert it? (btw I'm using this for a lua script that makes the idle animations toggleable)

**Comment by LarryFrosty** [comment]
![Screenshot_2024-07-19-21-01-07-61.jpg](https://github.com/user-attachments/assets/d9a474bf-0163-4cef-841a-6ac1ee7ab9c6)

**Comment by nguyenkiet1234d** [comment]
function onUpdate()
if curStep ==  Enter the step number then
setProperty('enter bf or dad .specialAnim', true);
characterPlayAnim('enter bf or dad', 'idle', true);
end
end

**Comment by LDcode17** [comment]
> function onUpdate() if curStep == Enter the step number then setProperty('enter bf or dad .specialAnim', true); characterPlayAnim('enter bf or dad', 'idle', true); end end

Ok but the thing I wanna do is switch to the alt and normal idle's by pressing left shift

**Comment by LarryFrosty** [comment]
> function onUpdate()
> if curStep ==  Enter the step number then
> setProperty('enter bf or dad .specialAnim', true);
> characterPlayAnim('enter bf or dad', 'idle', true);
> end
> end
> 

what the hell

**Comment by LarryFrosty** [comment]
> > ![Screenshot_2024-07-19-21-01-07-61.jpg](https://private-user-images.githubusercontent.com/80482125/350397248-d9a474bf-0163-4cef-841a-6ac1ee7ab9c6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzOTQzOTcsIm5iZiI6MTcyMTM5NDA5NywicGF0aCI6Ii84MDQ4MjEyNS8zNTAzOTcyNDgtZDlhNDc0YmYtMDE2My00Y2VmLTg0MWEtNmFjMWVlN2FiOWM2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDEzMDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MmMyM2ZlYTdlYjYwMzYzYTQ4ZjJjNTEyNDI5NmQwZTgzYjE1MmUyODZhNjAyMjk3Mzc1ZDE3ODZmNWJjNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jhsEt3jLQ0PCOzfTyJ3dQ4MjLbxX2Y43isZoktpOwMo)
> 
> Ok now how do I do it in lua?

`triggerEvent('Alt Idle Animation', 'character name', '')`

or you could also do the easier way and change idleSuffix
`setProperty('dad.idleSuffix', '')`

**Comment by woksio1** [comment]
local animsA = {'singLEFT-alt', 'singDOWN-alt', 'singUP-alt', 'singRIGHT-alt'}
local animsB = {'singLEFT', 'singDOWN', 'singUP', 'singRIGHT'}
local hitCombo = 0

function onUpdate()
	if keyboardJustPressed("SPACE") then -- space button
		hitCombo = (hitCombo + 1)
	elseif hitCombo == 2 then
		hitCombo = 0
	end
end

function goodNoteHit(i, d, t, s)
	if hitCombo == 0 then -- normal notes
		triggerEvent('Alt Idle Animation', 'bf','');
		characterPlayAnim('bf', animsB[d + 1]);
	elseif hitCombo == 1 then -- alt notes
		triggerEvent('Alt Idle Animation', 'bf', '-alt');
		characterPlayAnim('bf', animsA[d + 1]);
	end
end






I found this script on yt so you could change space to left shift

**Comment by LDcode17** [comment]
> local animsA = {'singLEFT-alt', 'singDOWN-alt', 'singUP-alt', 'singRIGHT-alt'} local animsB = {'singLEFT', 'singDOWN', 'singUP', 'singRIGHT'} local hitCombo = 0
> 
> function onUpdate() if keyboardJustPressed("SPACE") then -- space button hitCombo = (hitCombo + 1) elseif hitCombo == 2 then hitCombo = 0 end end
> 
> function goodNoteHit(i, d, t, s) if hitCombo == 0 then -- normal notes triggerEvent('Alt Idle Animation', 'bf',''); characterPlayAnim('bf', animsB[d + 1]); elseif hitCombo == 1 then -- alt notes triggerEvent('Alt Idle Animation', 'bf', '-alt'); characterPlayAnim('bf', animsA[d + 1]); end end
> 
> I found this script on yt so you could change space to left shift

Thx but how do I do that? I'm using JS engine (I know very weird and might get me banned) and space makes you taunt.. so what are the keys that can be used for lua

**Comment by woksio1** [comment]
Maybe do uh not space but try writing smth like SLASH or smth

**Comment by LDcode17** [comment]
> Maybe do uh not space but try writing smth like SLASH or smth

Wait I tried it but my mod has judgement based anims scripts so those scripts stopped working. what I REALLY wanna do is what aleon bf does with the changeAleonBF.lua script but for idle animations.
