### ISSUE TITLE
Can you possibly bring back the ability to use lua?

### ISSUE THREAD

**Issue by KxleyStudios** [ShadowMario/FNF-PsychEngine#15138]
### What feature do you want to get added on the **base** engine?

Can you possibly bring back the ability to use lua? Multiple of my friends are disappointed that they learned lua for this engine and now cant use it on newer versions. Can you possibly add back the functionality?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by RodneyAnImaginativePerson** [comment]
tf, this is not true

**Comment by Lorekeeper49** [comment]
He didn't remove it, the latest version works perfectly fine with my lua mod

**Comment by RodneyAnImaginativePerson** [comment]
frfr sm, frfr

**Comment by CrusherNotDrip** [comment]
smart
