### ISSUE TITLE
Mods Don't work "as is" on Linux

### ISSUE THREAD

**Issue by Drago-Cuven** [ShadowMario/FNF-PsychEngine#15136]
### Describe your bug here.

![image](https://github.com/user-attachments/assets/46b2af4b-659b-4b93-b521-9bc07276d43a) 

it expects the charts of the mods to be in assets/shared/data as if they were part of psych engine naturally.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no. i added the mods without any modification.

**Comment by Drago-Cuven** [comment]
i got it from flathub and am using the  linux container for ChromeOS

**Comment by CrusherNotDrip** [comment]
> it expects the charts of the mods to be in assets/shared/data as if they were part of psych engine naturally.


it only shows that path on error as its the final one it checks for if one wasnt found beforehand

**Comment by Drago-Cuven** [comment]
well the files ARE there. so what could possibly be the matter?

**Comment by CrusherNotDrip** [comment]
are you sure gallery-gallery.json is in mods/yourmod/data/gallery/

**Comment by Drago-Cuven** [comment]
> are you sure gallery-gallery.json is in mods/yourmod/data/gallery/

I guarantee it.
