### ISSUE TITLE
error loading sound from file psych engine

### ISSUE THREAD

**Issue by 7-7what** [ShadowMario/FNF-PsychEngine#15133]
### Describe your problem here.

I CANT FIX THISSSS 
![Screenshot 2024-07-19 084736](https://github.com/user-attachments/assets/3704e9bf-6dfc-4c0a-9772-232a5a2c9e1a)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by nguyenkiet1234d** [comment]
Are you sure you put the song in the correct position and the song is exactly ogg and not from mp3 and renamed to ogg?

**Comment by nguyenkiet1234d** [comment]
And if that song doesn't work, just delete that song and download another link of the song and remember that the song must be ogg, and if it is mp3, go to the web to convert mp3 to ogg.
