### ISSUE TITLE
Fix The Character editor

### ISSUE THREAD

**Issue by TragicMagneta** [ShadowMario/FNF-PsychEngine#15144]
### Describe your bug here.

![캡처_2024_07_21_01_58_32_398](https://github.com/user-attachments/assets/615894f1-297a-4432-bf1e-91cb19577de1)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

3404

**Comment by potatex2** [comment]
[try this and see if it at least shows the characters](https://github.com/ShadowMario/FNF-PsychEngine/pull/14495)
