### ISSUE TITLE
Free play Menu Crashing

### ISSUE THREAD

**Issue by KxleyStudios** [ShadowMario/FNF-PsychEngine#15149]
### Describe your bug here.

Sometimes i create a week for my mod, simply opening the free play will result in a crash screen, i will send a screenshot once asked :)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CrusherNotDrip** [comment]
We are probably gonna need the screenshot for more information

**Comment by serik-oof** [comment]
well i do had this experience, you need to put your stages in folder **stage**, not folder **weeks**
