### ISSUE TITLE
note rgb shader thing

### ISSUE THREAD

**Issue by NullObjectRef** [ShadowMario/FNF-PsychEngine#15148]
### Describe your problem here.

nobody answered when i asked this in a question, and it's been multiple weeks since, so the following is directly pasted from my question: is there any way i can make it so if the note rgb shader is set to a specific color, something happens?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by serik-oof** [comment]
well, i dont think anyone ever made that, considering that fact that you want it to be rgb. i am pretty sure that it can be on source code on the mod, but i cant remember what mod tho.
