### ISSUE TITLE
Character Editor Black (Source Code 7.3)

### ISSUE THREAD

**Issue by oyuncuhanl** [ShadowMario/FNF-PsychEngine#15143]
its just black 

İDK 
![Ekran görüntüsü 2024-07-20 194102](https://github.com/user-attachments/assets/dac65c9c-124b-4d5f-8904-a2c464c41ab9)

**Comment by FazbearMods027** [comment]
There are Specific files in assets/shared/images of the default stage which are used in the character editor... If these are missing it just shows this... if the character itself is missing then either the camera is too far away or the character editor state is missing... I'm not fully sure of this but hope some of this helps...

**Comment by potatex2** [comment]
Assuming F1 doesn't work either, [just tweak the CharacterEditorState file with the stuff here.](https://github.com/ShadowMario/FNF-PsychEngine/pull/14495)
