### ISSUE TITLE
Error compiling Psych 0.7.3

### ISSUE THREAD

**Issue by JoshiiOfficial** [ShadowMario/FNF-PsychEngine#15145]
### Describe your bug here.

Whenever I try and compile Psych Engine, I get the following error (see logs)

![Screenshot 2024-07-20 204148](https://github.com/user-attachments/assets/4702b401-a15f-41d1-a19a-52cb223df267)

I have edited TitleState.hx. **However,** after editing I tried replacing TitleState.hx with the original file I got from the source code download, but the issue still persisted.
I haven't edited any of the images the paths shown in the logs lead to.

Sometimes, when I click OK on the error prompt, the game still runs as normal, but other times the game doesn't run.

Any help would be greatly appreciated.

### Command Prompt/Terminal logs (if existing)

```bash
Link: ApplicationMain.exe
   Creating library ApplicationMain.lib and object ApplicationMain.exp
source/backend/Paths.hx:251: oh no its returning null NOOOO (assets/shared/images/menuBG.png)
source/backend/Paths.hx:251: oh no its returning null NOOOO (assets/shared/images/menuBG.png)
source/backend/Paths.hx:251: oh no its returning null NOOOO (assets/shared/images/logoBumpin.png)
source/backend/Paths.hx:251: oh no its returning null NOOOO (assets/shared/images/logoBumpin.png)
source/backend/Paths.hx:251: oh no its returning null NOOOO (assets/shared/images/gfDanceTitle.png)
source/backend/Paths.hx:251: oh no its returning null NOOOO (assets/shared/images/titleEnter.png)
flixel/animation/FlxAnimationController.hx (line 739)
states/TitleState.hx (line 300)
states/TitleState.hx (line 170)
flixel/util/FlxTimer.hx (line 205)
flixel/util/FlxTimer.hx (line 295)
flixel/FlxGame.hx (line 750)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I have edited TitleState (see explanation above). I also have one mod in the bin/mods folder.

**Comment by brusakas** [comment]
did u delete the images for titlestate.hx?

**Comment by JoshiiOfficial** [comment]
> did u delete the images for titlestate.hx?

Nah, the original images are still in assets/shared/images. I even tried building a fresh Psych 0.7.2 folder, but it gave me the same error. Not sure what's going on.

**Comment by JoshiiOfficial** [comment]
Ok, turns out AVG (my anti-virus) was the problem. All I had to do was whitelist the mod's folder, and everything works fine.
