### ISSUE TITLE
psych engine compile code errror  HELP MEEE

### ISSUE THREAD

**Issue by jhebux** [ShadowMario/FNF-PsychEngine#15146]
### Describe your problem here.

FNF-PsychEngine-0.7.3\source\import.hx:10: characters 8-16 : Type not found : llua.Lua
FNF-PsychEngine-0.7.3\source\import.hx:10: characters 8-16 : Type not found : llua.Lua
FNF-PsychEngine-0.7.3\source\import.hx:10: characters 8-16 : Type not found : llua.Lua
FNF-PsychEngine-0.7.3\source\import.hx:10: characters 8-16 : Type not found : llua.Lua
FNF-PsychEngine-0.7.3\source\import.hx:10: characters 8-16 : Type not found : llua.Lua
FNF-PsychEngine-0.7.3\source\import.hx:10: characters 8-16 : Type not found : llua.Lua
FNF-PsychEngine-0.7.3\source\import.hx:10: characters 8-16 : Type not found : llua.Lua
FNF-PsychEngine-0.7.3\source\import.hx:10: characters 8-16 : Type not found : llua.Lua
FNF-PsychEngine-0.7.3\source\import.hx:10: characters 8-16 : Type not found : llua.Lua

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CrusherNotDrip** [comment]
`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git`

**Comment by bart0914** [comment]
> `haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git`

It still doesnt work ._.

**Comment by ShadowMario** [comment]
> > `haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git`
> 
> It still doesnt work ._.

Try running `haxelib remove linc_luajit` then try the haxelib git command again

**Comment by jhebux** [comment]
> > > `haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git`
> > 
> > 
> > It still doesnt work ._.
> 
> Try running `haxelib remove linc_luajit` then try the haxelib git command again

Thank you all it worked 👌

**Comment by CrusherNotDrip** [comment]
close issue then
