### ISSUE TITLE
something wrong with the charting menu

### ISSUE THREAD

**Issue by BloxyPlayzYT** [ShadowMario/FNF-PsychEngine#15156]
### Describe your bug here.

im trying to make a chart for a song and this error keeps showing up when i try to go to a specific section of the chart

### Command Prompt/Terminal logs (if existing)

```bash
states/editors/ChartingState.hx (line 2870)
states/editors/ChartingState.hx (line 2837)
states/editors/ChartingState.hx (line 2792)
states/editors/ChartingState.hx (line 2307)
states/editors/ChartingState.hx (line 2589)
states/editors/ChartingState.hx (line 2091)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by HourOfEternity** [comment]
From what I can tell, it looks like something to do with custom note types possibly not being found. Have you added any custom notes into your chart/psych? Hope this helps!
