### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by Sure-I-will-help** [ShadowMario/FNF-PsychEngine#15158]
### Describe your problem here.

i tried compiling then this came up

![image](https://github.com/user-attachments/assets/ae633e1b-7847-4aed-93cb-88dedbf07138)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

changed teacall to tea

**Comment by Sure-I-will-help** [comment]
nevermind it fixed itself

**Comment by CrusherNotDrip** [comment]
> nevermind it fixed itself

close issue then
