### ISSUE TITLE
Changing the object camera of the opponent's strumlines

### ISSUE THREAD

**Issue by MekoGithub** [ShadowMario/FNF-PsychEngine#15150]
### Describe your problem here.

I'm trying to make it so that the opponent's strumlines are set to camGame, as opposed to camHUD. I've tried just doing `setObjectCamera('opponentStrums', 'camGame')` since I remembered seeing opponentStrums used in a script once, but i'm not having much luck. Is there anything I can use in a situation like the following??
```
for i = 0,3 do
	setPropertyFromGroup('strumLineNotes', i, -- would i put the camGame junk here?)
end
```
Any help is much appreciated! I haven't really spent much time learning 0.7-era lua, since none of my scripts have required it, but I feel like this might need some knowledge about it (that or im a bit stupid lol)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by HourOfEternity** [comment]
I've helped a couple people with this; I'll direct you to #14847
