### ISSUE TITLE
it says to report this crash to the github page sooo

### ISSUE THREAD

**Issue by yteeware** [ShadowMario/FNF-PsychEngine#15153]
### Describe your bug here.

states/editors/CharacterEditorState.hx (line 237)
states/editors/CharacterEditorState.hx (line 463)
flixel/addons/ui/FlxUIDropDownMenu.hx (line 499)
flixel/addons/ui/FlxUIDropDownMenu.hx (line 359)
flixel/ui/FlxButton.hx (line 521)
flixel/addons/ui/FlxUITypedButton.hx (line 1172)
flixel/addons/ui/FlxUIButton.hx (line 362)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 426)
openfl/display/DisplayObject.hx (line 1398)

when i tried using the character editor and chose daddy dearest, this happens.
it may be my fault tho cuz i was pissing about with it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

the json files

**Comment by HourOfEternity** [comment]
Can I see the .json file you edited? I can see what you changed that might've had this result.
