### ISSUE TITLE
how would I adjust individual notes instead of the whole entire collumn (recepetor + all notes in the lane)?

### ISSUE THREAD

**Issue by Zombie7z** [ShadowMario/FNF-PsychEngine#15168]
### Describe your problem here.

I want to change a value on individual notes once they pass a certain point on the screen does anyone know how I would do that rather than the whole lane?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Unbroke50** [comment]
What value are you trying to change?
because without that i wont be able to help.
