### ISSUE TITLE
Change iconP1 or iconP2 in mid song

### ISSUE THREAD

**Issue by FinderFromMac** [ShadowMario/FNF-PsychEngine#15164]
### Describe your problem here.

is there any script to change the iconP1 or iconP2 image in the middle of a song?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by HourOfEternity** [comment]
Whenever I needed to change icons, I would just duplicate the character files that I wanted to change, then edit the icon of the duplicated character to the new icon in the .json, then add the change character event into the song when you want to change it.

**Comment by potatex2** [comment]
```lua
runHaxeCode([[
   iconP1.changeIcon("icon-gf");
]])
-- just change iconP# and the icon-gf to icon-(name)
```
