### ISSUE TITLE
There is no asset library with an ID of "videos"

### ISSUE THREAD

**Issue by Bigbabybomber** [ShadowMario/FNF-PsychEngine#15163]
### Describe your problem here.

when i go to start up the game it shows, There is no asset library with an ID of "videos". ive even tried deleting it and downloading a new copy of the game but it still shows that text and i dont know what to do about it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by FuseIsHere813** [comment]
Check the "manifest" folder, the game probably crashed because it is missing a videos.json file in the manifest folder, hard to recreate.

You may have to do a reinstall of Psych Engine.
