### ISSUE TITLE
Custom Achievements In Lua Issue

### ISSUE THREAD

**Issue by GkdBoi** [ShadowMario/FNF-PsychEngine#15166]
### Describe your problem here.

So right now I have this code for a custom achievement I want to add the Psych Engine 0.7.3, which is supposed to make it so that when I get to pass a certain song I get the achievement in Lua. 
```
[
    {
        "save": "Weekend1_complete", // Will load images/achievements/Weekend1_complete.png
        "name": "2hot Completed",
        "description": "Complete the song '2hot'.",
        "hidden": false
    }
]
```
The thing is, it shows in the awards section but when I beat the certain song which was 2hot, I didn't get the achievement, am I missing something.
![Screenshot 2024-07-23 171500](https://github.com/user-attachments/assets/23fce268-de83-47af-af07-2ee01f947bf3)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
Yes you are doing something wrong, you did not code the achievement, use `unlockAchievement('Weekend1_complete')` in lua or `Achievements.unlock('Weekend1_complete')`

**Comment by GkdBoi** [comment]
> Yes you are doing something wrong, you did not code the achievement, use `unlockAchievement('Weekend1_complete')` in lua or `Achievements.unlock('Weekend1_complete')`

So i made a new lua and called it "AchievementUnlock" i would add this code inside it "unlockAchievement('Weekend1_complete')"
