### ISSUE TITLE
pls help anyone i just started modding

### ISSUE THREAD

**Issue by Teaslehero6969** [ShadowMario/FNF-PsychEngine#15165]
### Describe your problem here.

i was making a video play before title screen and i was following a tutorial and it says when i do lime test windows source/states/TitleState.hx:489: characters 1-7 : Expected } and its annoying
pls help
![Screenshot 2024-07-23 220417](https://github.com/user-attachments/assets/27cc6654-6c48-49ef-887e-8b844550e3d9)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I tried editing TitleState.hx

**Comment by Teaslehero6969** [comment]
ok i fixed that one but ive got a diff one. pls help 
![Screenshot 2024-07-23 223105](https://github.com/user-attachments/assets/e8b75fec-ff90-46a9-84d6-1f1d79aa4a0e)

**Comment by xxyuee** [comment]
like your comment said, remove the space in onEndReached

**Comment by Teaslehero6969** [comment]
ok that fixed that but theres ANOTHER issue
![Screenshot 2024-07-24 114344](https://github.com/user-attachments/assets/d17eca1e-418e-4571-a5ed-041e96b40d7c)
