### ISSUE TITLE
Changing sizes of opponents and players notes 

### ISSUE THREAD

**Issue by Bssez** [ShadowMario/FNF-PsychEngine#15177]
### Describe your problem here.

![Ekran görüntüsü 2024-07-25 171949](https://github.com/user-attachments/assets/57c4ab38-d33f-42d7-8f45-02b2a4707333)

What im trying to do is change the size of the opponents notes and make them  appear behind the opponent while Bf's notes are a regular size towards the right side of the screen that appear regularly in front of him rather than behind him. How do İ go about this exactly? 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Regular build of Psych Engine

**Comment by potatex2** [comment]
You're going to have to elaborate on how exactly you want the notes to be and when exactly, but for now here's the same thing somewhat streamlined/fixed (you'll need to figure out the scale of the notes though because they're not the same...
i.e.
- align the actual notes in camGame directly behind opponent?
- is it going to be throughout the song or during opponent's turns only?
- regularly pertaining to when exactly?
```lua
function opponentNoteHit()
    for i = 0,7 do
        setPropertyFromGroup('opponentStrums', i, 'scale.x', 0.35)
        setPropertyFromGroup('opponentStrums', i, 'scale.y', 0.35)
        setPropertyFromGroup('playerStrums', i, 'scale.x', 0.55)
        setPropertyFromGroup('playerStrums', i, 'scale.y', 0.55)

        setPropertyFromGroup('unspawnNotes', i, 'scale.x', 0.35)
        setPropertyFromGroup('unspawnNotes', i, 'scale.y', 0.35)
        for i1 = 0,3 do
            noteTweenX('floof'..i1, i1, 100 + (65 * i1), 0.05, "linear")
        end
        for i2 = 4,7 do
            noteTweenX("bloop"..i2, i2, 600 --[[ -50 from original to test/align]] + (80 * i2), 0.05, "linear")
        end
    end
end
--There's still going to be a few notes not set to the scale expected throughout the song,
--but not sure if you're going to do vice versa though
```

**Comment by Bssez** [comment]
Thanks! What my vision is, is to have the opponents notes and strum behind them so it doesn't obstruct their animations while the players notes are completely normal.

-throughout the entire song
- only the opponents notes should be behind them

**Comment by HourOfEternity** [comment]
I'm guessing you want the notes to be behind the opponent like Silly Billy from Hit Single Real, in which I have you covered in issue #14847.

Hope this works for you!
