### ISSUE TITLE
achievements issue

### ISSUE THREAD

**Issue by Teaslehero6969** [ShadowMario/FNF-PsychEngine#15170]
### Describe your problem here.

im trying to make a custom achievement so when you beat the song empathy it give you achievement but this is happen
![Screenshot 2024-07-24 121713](https://github.com/user-attachments/assets/a8854ef6-320e-4675-a215-a9b1b3ebbb4b)
ing:

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I tried editing Achievements.hx

**Comment by potatex2** [comment]
One, _please get the language support 😭_
Two, make sure the double quotes are escape characters by doing `\"` on them.

**Comment by ShadowMario** [comment]
![image](https://github.com/user-attachments/assets/f5df6d57-f0d7-445e-9743-62e4fbc4add5)
Please change formatting to Haxe so we can see better the issue, if you can't find Haxe, install the Haxe VSC extension
