### ISSUE TITLE
How to add an achievement for FCing a week

### ISSUE THREAD

**Issue by AntiPlayzz** [ShadowMario/FNF-PsychEngine#1517]
### Describe your problem here.

Hey, I'm trying to add an achivement for FCing my custom week, but when i beat it, it didn't give me my achievement.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited PlayState.hx and added win icons

**Comment by HafimieForever** [comment]
lua? arent you suppose to add achievements with source code

**Comment by AntiPlayzz** [comment]
> 

My bad, didn’t know the difference. Newbie coder.

**Comment by HafimieForever** [comment]
> > 
> 
> My bad, didn’t know the difference. Newbie coder. Fixed it.

Ohh btw i dont know tho

**Comment by KutikiPlayz** [comment]
you wanna search up "achievementobj !" (without the quotes) in PlayState.hx and make sure to add your custom achievement in that list so that the game can actually give it to you when you complete it

**Comment by AntiPlayzz** [comment]
> I am going to remove all the other FC achievements besides week 1 and week 2. Where do i put the file name of my week into the file (it worked like that in the older versions)

**Comment by KutikiPlayz** [comment]
> > I am going to remove all the other FC achievements besides week 1 and week 2. Where do i put the file name of my week into the file (it worked like that in the older versions)

you can either name the week something like week3 where the achievement code already exists for that week, or you can just change the case name from week(randomnumber) to whatever your week file is. I would assume that's how it works but Idk, since in my mod I only have 1 week so I didn't need to specify.

**Comment by AntiPlayzz** [comment]
The new psych update has the code that i understood before. Will be closing.
