### ISSUE TITLE
How to add custom achievements???

### ISSUE THREAD

**Issue by TTRICKYTHECAR** [ShadowMario/FNF-PsychEngine#1518]
### Describe your problem here.

How do i add custom achievements?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't edit anything. I have a fresh copy of PH

**Comment by HafimieForever** [comment]
you need a source code for this

**Comment by HafimieForever** [comment]
look at this https://youtu.be/Gf9y0PNOrqk
