### ISSUE TITLE
Null Object Reference when trying to access Freeplay

### ISSUE THREAD

**Issue by IDK-whatnametocall** [ShadowMario/FNF-PsychEngine#15185]
### Describe your bug here.

After I made a Spritesheet for my FNF mod and going to freeplay, I get this "Null Object Reference" error. I don't know why it happened but it just did, here is the error:
FreeplayState.hx (line 74)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

### Command Prompt/Terminal logs (if existing)

```bash
No response
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by potatex2** [comment]
![image](https://github.com/user-attachments/assets/11b2e741-6050-4470-9830-5367422d2592)
This might have something to do with the week content/songs and not an actual spritesheet
