### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by nayell-xd** [ShadowMario/FNF-PsychEngine#15189]
### Describe your bug here.

Today I wanted to enter my psych engine but when I tried I got this error
!
![Anotación 2024-07-26 171701](https://github.com/user-attachments/assets/9647cad7-fd1a-49d7-864b-e544fb41b120)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by CoakyorCookie** [comment]
Is it a mod's song?
