### ISSUE TITLE
ApplicationMain.exe?

### ISSUE THREAD

**Issue by ilyes-4747** [ShadowMario/FNF-PsychEngine#15180]
### Describe your bug here.

i was waiting for it to compile then this error came out

### Command Prompt/Terminal logs (if existing)

```bash
libucrt.lib(checkcfg.obj) : error LNK2001: unresolved external symbol _guard_check_icall_$fo$ ApplicationMain.exe : fatal error LNK1120: 1 unresolved externals
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by theRealCox** [comment]
Delete the export folder, and compile it back. I had this issue also. (It can repeat multiple times)
