### ISSUE TITLE
Custom notes texture goofing after change note skin event

### ISSUE THREAD

**Issue by lovodiska** [ShadowMario/FNF-PsychEngine#15183]
### Describe your problem here.

after changing notes skin via event every custom note is turning into one grey note. Custom long notes doesn't render properly, its just one big grey note that gives me NullObjectReference jumpscare. I put NOTE_assets in mods/images so i could reset note skin to "default", but i keep getting same problem

https://github.com/user-attachments/assets/707d9caf-145b-4a11-a74b-e6c7e14809ba

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by HourOfEternity** [comment]
I've had this happen to me (minus the Null Object Reference), the notes I were using didn't have a hold note sprite, so you might be missing a sprite for a hold note, or the game cannot recognize it. Hope this helps!

**Comment by lovodiska** [comment]
> I've had this happen to me (minus the Null Object Reference), the notes I were using didn't have a hold note sprite, so you might be missing a sprite for a hold note, or the game cannot recognize it. Hope this helps!

everything works before changing note skin event. after changing it and even setting skin to default this shi happens

**Comment by FazbearMods027** [comment]
According to the NoteSkin Change event that I have it mentions Custom Notes May Most likely Break the game... That error sometimes acts as a fail-safe to avoid file corruptions... But it looks from the recording that the hold part is replica's of the note base which could be what HourOfEternity said of there being no hold sprites... I'm not fully sure of this but I hope this helps...
