### ISSUE TITLE
Null Object Reference?

### ISSUE THREAD

**Issue by MooseDebris** [ShadowMario/FNF-PsychEngine#15184]
### Describe your bug here.

Gives me this bug whenever it tries to do the first event (Set Cam Zoom)
![image](https://github.com/user-attachments/assets/d44c31e3-b0a5-4838-92de-c8393c05f21d)

### Command Prompt/Terminal logs (if existing)

```bash
Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by potatex2** [comment]
all the errors are pointing to note hits / ghost taps, also when is the first event triggered anyway?
