### ISSUE TITLE
Freeplay song preview broken with separated vocals

### ISSUE THREAD

**Issue by Skymanta414** [ShadowMario/FNF-PsychEngine#15193]
### Describe your bug here.

When listening to songs with separated player and opponent vocals in Freeplay, it bugs out and plays neither characters track, and glitches out the instrumental.

https://github.com/user-attachments/assets/fa7968f9-b2fa-4417-9d8f-3491509c60cb

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
0.7.3 or 1.0b?

**Comment by Skymanta414** [comment]
0.7.3

**Comment by ShadowMario** [comment]
This was already fixed on 1.0b
