### ISSUE TITLE
How to create a code do players to exit the game and log in to that website

### ISSUE THREAD

**Issue by nguyenkiet1234d** [ShadowMario/FNF-PsychEngine#15194]
### Describe your problem here.

I need a piece of code that can cause the player to crash the game and automatically log in to that website
Looking forward to help, for me, using source or lua is fine as long as it works, by the way I use 0.7.3

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nopeee

**Comment by HourOfEternity** [comment]
I have absolutely no idea on how to make someone log into a website (if it's even possible) but here is some code to close the game when you press the number 9:
```
function onUpdate()
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.NINE') then        
        os.exit();
    end
end
```

**Comment by nguyenkiet1234d** [comment]
Well I know about that code but it only causes the game to crash and not be able to access a certain website. Anyway, thank you for your contribution.
