### ISSUE TITLE
i really dont know how to fix this psych engine experimental build

### ISSUE THREAD

**Issue by dogsuscool** [ShadowMario/FNF-PsychEngine#15197]
### Describe your bug here.

every time I use lime test windows it gives me this error and I can't find how to fix it
![image](https://github.com/user-attachments/assets/8abc1422-726b-444c-bc8a-b6fe08a8aac4)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

not yet

**Comment by ShadowMario** [comment]
Should be fixed in the latest commits
