### ISSUE TITLE
How to mute instrumental? [Lua]

### ISSUE THREAD

**Issue by luigiman0** [ShadowMario/FNF-PsychEngine#15207]
### What is your question?

I'm currently making a results screen script for a mod, but there's a few bugs I'm trying to figure out.
https://github.com/user-attachments/assets/8bd4d656-f9e4-4155-9d67-9cfb92632717

The two main things I can't figure out are how to mute the voices & instrumental for the normal song, and how to let the player exit the song after the results appear.

If anyone could help me figure out how to solve these, it would be very much appreciated.

**Comment by luigiman0** [comment]
`function onEndSong()
if rank then
	runTimer('Start', 1)
	return Function_Stop;
end
end

function onTimerCompleted(name)
        if name == 'Start' then	
	ranking = true
	playMusic('result',1)
	doTweenAlpha('resultsReal', 'awesome', 1, 1, 'quadOut')
	doTweenY('barRhi', 'bar_r', barH + 520, 1, 'quadOut')
	doTweenY('barLhi', 'bar_l', barH - 520, 1, 'quadOut')
end
end

function onUpdatePost()
if ranking then
        if keyboardJustPressed('flixel.FlxG', 'keys.justPressed.SPACE') then
		endSong()
	end
end
end`
Here's the part of the script that currently fails at exiting the song.

**Comment by Lorekeeper49** [comment]
> ```
> function onEndSong()
> if rank then
> 	runTimer('Start', 1)
> 	return Function_Stop;
> end
> end
> 
> function onTimerCompleted(name)
>         if name == 'Start' then	
> 	ranking = true
> 	playMusic('result',1)
> 	doTweenAlpha('resultsReal', 'awesome', 1, 1, 'quadOut')
> 	doTweenY('barRhi', 'bar_r', barH + 520, 1, 'quadOut')
> 	doTweenY('barLhi', 'bar_l', barH - 520, 1, 'quadOut')
> end
> end
> 
> function onUpdatePost()
> if ranking then
>         if keyboardJustPressed('flixel.FlxG', 'keys.justPressed.SPACE') then
> 		endSong()
> 	end
> end
> end
> ```
> Here's the part of the script that currently fails at exiting the song.
> 

I think `onUpdatePost()` should just be `onUpdate()`.  In my experience, keyboardJustPressed doesn't like to work post update

**Comment by luigiman0** [comment]
Just figured it out! Was using `keyboardJustPressed` instead of `getPropertyFromClass('flixel.FlxG', 'keys.justPressed.ENTER')` 

Now working on figuring out how to mute Voices and Inst (To stop them from playing during results, as shown in video above)

**Comment by luigiman0** [comment]
Managed to get voices muted, still working on inst
