### ISSUE TITLE
what does this error mean?

### ISSUE THREAD

**Issue by Nitro509** [ShadowMario/FNF-PsychEngine#15208]
### Describe your bug here.

![Screenshot 2024-07-30 134543](https://github.com/user-attachments/assets/285bed1d-9f0d-462a-87d9-1e5211e16a76)

i was playing dad battle as a test to see my custom character and it worked well until it came to boyfriends arrows then this error came and it crashed.

Does somoene know what this error means?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

?

**Comment by baobab121** [comment]
maybe something wrong with your character icon
