### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by ziopero11** [ShadowMario/FNF-PsychEngine#15209]
### Describe your problem here.

what does this mean?
![image](https://github.com/user-attachments/assets/bf4d342e-c29c-4b0d-ae28-921bf535d8fe)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by corakit** [comment]
I'm not an expert at all but you could try running this in the command prompt 
`haxelib install newgrounds`
if you haven't already

**Comment by CrusherNotDrip** [comment]
This is not Psych Engine related. You shouldn't put make an issue here
[Also heres how to compile base fnf](https://github.com/FunkinCrew/Funkin/blob/main/docs/COMPILING.md)

**Comment by ShadowMario** [comment]
Invalid: Not Psych Engine
