### ISSUE TITLE
how to adjust the position of multiple animated sprites 

### ISSUE THREAD

**Issue by nguyenkiet1234d** [ShadowMario/FNF-PsychEngine#15202]
### Describe your problem here.

I need to adjust the position of many animations, I only know there is addoffset command but it works in 0.6.3 but I use 0.7.3.
To make it easier to understand, my animation 1 is at position 0,0 but when animation 2 plays, it plays at position 3,4.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by potatex2** [comment]
have you tried using the character editor

**Comment by nguyenkiet1234d** [comment]
oh well thanks
