### ISSUE TITLE
This is BAD.

### ISSUE THREAD

**Issue by oliverggg123ggg** [ShadowMario/FNF-PsychEngine#15201]
### Describe your bug here.

source/TitleState.hx:31: characters 8-29 : Type not found : flixel.sound.FlxSound
source/editors/ChartingState.hx:33: characters 8-29 : Type not found : flixel.sound.FlxSound
source/editors/ChartingState.hx:150: characters 13-21 : Type not found : FlxSound

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheRealJake12** [comment]
update flixel

**Comment by oliverggg123ggg** [comment]
> update flixel

What Version? :\

**Comment by TheRealJake12** [comment]
> > update flixel
> 
> What Version? :\

just run the updater thing in the setup folder

**Comment by oliverggg123ggg** [comment]
> > > update flixel
> > 
> > 
> > What Version? :\
> 
> just run the updater thing in the setup folder

Ok! 👍

**Comment by oliverggg123ggg** [comment]
> > > > update flixel
> > > 
> > > 
> > > What Version? :\
> > 
> > 
> > just run the updater thing in the setup folder
> 
> Ok! 👍

i can't find it
