### ISSUE TITLE
If anyone know how to fix this please tell me

### ISSUE THREAD

**Issue by Sans101YT** [ShadowMario/FNF-PsychEngine#15200]
### Describe your bug here.

Its a bug when i try to launch a song from the P:A EyefanBuild
![image_2024-07-28_192148398](https://github.com/user-attachments/assets/411a5164-2a2e-4a6f-a53c-c9f854348cf3)
If anyone know how to fix this please tell me

### Command Prompt/Terminal logs (if existing)

```bash
flixel/sound/FlxSound.hx (line 595)
flixel/sound/FlxSound.hx (line 739)
flixel/system/frontEnds/SoundFrontEnd.hx (line 183)
flixel/system/frontEnds/SoundFrontEnd.hx (line 241)
states/PlayState.hx (line 1003)
flixel/util/FlxTimer.hx (line 205)
flixel/util/FlxTimer.hx (line 295)
flixel/FlxGame.hx (line 750)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

just added the mod file from the PA Eyefanbuild

**Comment by FazbearMods027** [comment]
Ah Yes... The most common error for Psych Engine... Normally if you attempt to do the thing that caused the error after restarting it works properly... It is Normal for people to get this error while modding Psych Engine with Lua (Although there is a rare possibility for the game to force close on error without the error prompt...) Simply Reopening the Game will fix it for now... Like I mentioned this is a common error and most people get it in Psych engine (Even without mods) HaxeFlixel (The Program Used to make FNF) Sometimes can't handle certain things... Or at least that's what I think... Hope this helps... (Also the part that reads 'Did you edit anything in this build? If so, mention or summarize your changes.' is supposed to be for if the build was modified in source code and not for if Lua mods were added... I think...)

**Comment by CrusherNotDrip** [comment]
The error has something to do with the countdown sounds

**Comment by FazbearMods027** [comment]
> The error has something to do with the countdown sounds

It could also be an error related to the countdown animation in Pibby Apocalypse... Unlike most mods which have static images for the countdown... Pibby Apocalypse uses an animated countdown... So likely it's an error with the animation while associated with the sound... (It also adds the 3 Part which most mods don't have it...)
