### ISSUE TITLE
game crashed

### ISSUE THREAD

**Issue by melon2212** [ShadowMario/FNF-PsychEngine#15206]
### Describe your problem here.

tryna make a mod but this occurred
[PsychEngine_2024-07-29_20'43'35.txt](https://github.com/user-attachments/files/16420471/PsychEngine_2024-07-29_20.43.35.txt)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I was trying to make a custom week in my mod.

**Comment by CrusherNotDrip** [comment]
it expects a `]` somewhere

**Comment by melon2212** [comment]
Where?

**Comment by melon2212** [comment]
![image](https://github.com/user-attachments/assets/54ed4ff2-f651-4d62-aa47-2c879761b575)
![image](https://github.com/user-attachments/assets/a10291e6-540c-46de-a4f0-16a16f738c16)
![image](https://github.com/user-attachments/assets/b6378fa6-3391-4fe3-a2b2-79ea62dbc061)
the only jsons in my mod

**Comment by melon2212** [comment]
![image](https://github.com/user-attachments/assets/63057696-e174-4d50-bea6-4b875e9735e4)
![image](https://github.com/user-attachments/assets/b7623df0-820a-4b54-b5c2-0ee512334a89)
![image](https://github.com/user-attachments/assets/afdecfcf-4ca8-4c58-838a-de7ac47ee124)
every line 39

**Comment by melon2212** [comment]
> it expects a `]` somewhere

![image](https://github.com/user-attachments/assets/e158da13-9c5c-4090-a032-5a85ee15da4e) week yes
![image](https://github.com/user-attachments/assets/54091b0b-aa0a-4951-9262-388dd9dd83fb) other song
![image](https://github.com/user-attachments/assets/9e62c364-3b23-4a74-b727-691f52c7ef74) test

**Comment by melon2212** [comment]
fixed it (slightly)
![image](https://github.com/user-attachments/assets/233f6f1d-f95b-4f54-9d92-c8e0949422b7) after the songs in my week

**Comment by melon2212** [comment]
story mode crash

**Comment by melon2212** [comment]
got it working
