### ISSUE TITLE
anti chart editor

### ISSUE THREAD

**Issue by Remkich** [ShadowMario/FNF-PsychEngine#15203]
### What is your question?

i wanna make anti chart editor.

Like when you press 7, error appears saying "Nuh uh".

How to make it?

**Comment by nguyenkiet1234d** [comment]
If it's a source, it can be done, but lua can't do it, but lua can cause the game to crash
start 
function onUpdate()
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then        
        os.exit();
    end
end

**Comment by xxyuee** [comment]
in lua you could do

addHaxeLibrary("Application','lime.app")
function onUpdate()
    setProperty("allowDebugKeys", false)
    if keyboardJustPressed("SEVEN") then
        runHaxeCode("Application.current.window.alert('nuh uh.');")
    end
end
