### ISSUE TITLE
Experimental Branch - Issue with compiling due to ABotSpeaker

### ISSUE THREAD

**Issue by PumpkinSheee** [ShadowMario/FNF-PsychEngine#15204]
### Describe your bug here.

so when compiling the new changes on the experimental branch, i get this error

Warning: Ignoring unknown fps=""
source/backend/SpectralAnalyzerEx.hx:3: characters 8-47 : Type not found : funkin.vis._internal.html5.AnalyzerNode
                                                                                                                  source/backend/SpectralAnalyzerEx.hx:4: characters 8-52 : Type not found : funkin.vis.audioclip.frontends.LimeAudioClip
                                                                                                                 source/backend/SpectralAnalyzerEx.hx:5: characters 8-39 : Type not found : funkin.vis.dsp.SpectralAnalyzer
                                                                                                   source/backend/SpectralAnalyzerEx.hx:6: characters 8-39 : Type not found : funkin.vis.dsp.RecentPeakFinder
                                                                                     source/backend/SpectralAnalyzerEx.hx:7: characters 8-22 : Type not found : grig.audio.FFT
                                                      source/backend/SpectralAnalyzerEx.hx:8: characters 8-35 : Type not found : grig.audio.FFTVisualization
                                    source/backend/SpectralAnalyzerEx.hx:11: characters 1-39 : Type not found : grig.audio.lime.UInt8ArrayTools
                       source/states/stages/objects/ABotSpeaker.hx:4: characters 8-39 : Type not found : funkin.vis.dsp.SpectralAnalyzer
                source/states/stages/objects/ABotSpeaker.hx:18: characters 15-33 : Type not found : SpectralAnalyzerEx
                                                                                                                      source/states/stages/PhillyBlazin.hx:153: characters 8-11 : states.stages.objects.ABotSpeaker has no field snd
                                                                                                            source/states/stages/PhillyStreets.hx:352: characters 9-18 : states.stages.objects.ABotSpeaker has no field lookRight
                                                                                                         source/states/stages/PhillyStreets.hx:354: characters 9-17 : states.stages.objects.ABotSpeaker has no field lookLeft
                                                                                                     source/states/stages/PhillyStreets.hx:361: characters 8-11 : states.stages.objects.ABotSpeaker has no field snd

im assuming ShadowMario is adding in weekend1, since ABotSpeaker is nene's speaker in weekend1, although i have no idea if this is a general issue or just something on my end, so if anyone knows a fix lmk - ill update this if i figure it out

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by ShadowMario** [comment]
Should be fixed
