### ISSUE TITLE
LAUNCH ERROR!

### ISSUE THREAD

**Issue by 121-b1** [ShadowMario/FNF-PsychEngine#15214]
### Describe your bug here.

I launched the psych engine,and it got errors

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes,i added False Hero from Mario's Monday Night Massacre and the XML with Mario from Vs. Mario Rebooted including the XML of him (Vs. Mario Rebooted)

**Comment by CoakyorCookie** [comment]
what version is your psych engine?
if 7.3, please switch to lower psych engine (6.3 or 5.1 is good I think)
what are the errors?

**Comment by 121-b1** [comment]
launch

**Comment by FuseIsHere813** [comment]
The crash log!

**Comment by FuseIsHere813** [comment]
The crash log? (Located in /crash/ in the engine folder)
