### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by HowdySigma** [ShadowMario/FNF-PsychEngine#15216]
### Describe your bug here.

bug occurs on launch
![bopcitycrash](https://github.com/user-attachments/assets/a4eb5a6e-a315-4f6a-b8da-46b2c0ba2580)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by FuseIsHere813** [comment]
a mod must have fucked up something with the title screen (Alphabet.png/xml, gfDanceTitle.json...etc)

**Comment by FuseIsHere813** [comment]
I think you accidentally reopened, @HowdySigma

**Comment by HowdySigma** [comment]
i just closed it because i gave up but now i'm still waiting

**Comment by HowdySigma** [comment]
i've been searching in the mods files, but no result so if you can help please contact me the issue

**Comment by FuseIsHere813** [comment]
try deleting/moving the mods folder away from this engine, and try adding a fresh one, without anything for now

**Comment by HowdySigma** [comment]
nope, no result.
i'll close down the issue because i already gave up from it so yeah bye
quick reminder that im not using the actual engine itself, im using another .exe file that uses psych engine
