### ISSUE TITLE
Please Help!

### ISSUE THREAD

**Issue by derpy369** [ShadowMario/FNF-PsychEngine#15219]
### Describe your problem here.

This is my first time compiling the source code and I don't know how to run lime test windows...
Can someone please help?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SPC-JustARandomImpostor** [comment]
did you run lime test windows in the command prompt in your psych engine source folder?

**Comment by derpy369** [comment]
> did you run lime test windows in the command prompt in your psych engine source folder?

i dont know how to do that..

**Comment by AdrianGaming0** [comment]
are you getting the "TeaCall" Error?

**Comment by CoakyorCookie** [comment]
click on the file path and type cmd, make sure you have haxe installed and did setup (if setup is there)
then type lime test windows
![Screenshot 2024-08-01 181834](https://github.com/user-attachments/assets/8f296995-7c93-4511-85d2-191346a9ff53)
make sure your screen is like the screenshot

**Comment by derpy369** [comment]
> click on the file path and type cmd, make sure you have haxe installed and did setup (if setup is there) then type lime test windows ![Screenshot 2024-08-01 181834](https://private-user-images.githubusercontent.com/167979946/354184301-8f296995-7c93-4511-85d2-191346a9ff53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NDYxNjMsIm5iZiI6MTcyMjU0NTg2MywicGF0aCI6Ii8xNjc5Nzk5NDYvMzU0MTg0MzAxLThmMjk2OTk1LTdjOTMtNDUxMS04NWQyLTE5MTM0NmE5ZmY1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQyMDU3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTIyYjFmOWEwYzBmN2ZkYzBlOTIxY2E0NTEzNDBkN2YxYjY2OTFhMTQyNTBiZDY5MDdiYzg3NTZkYzVkNzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ahcA7fGkBawEL0xC5KECN6tkv3T2lQ6HybdDvWGb-mk) make sure your screen is like the screenshot

ok thank you so much!
