### ISSUE TITLE
Something with sounds

### ISSUE THREAD

**Issue by EthanMG228** [ShadowMario/FNF-PsychEngine#15210]
### Describe your bug here.

i was just making a mod and deleted sounds but when i tested this happened: 
![Снимок](https://github.com/user-attachments/assets/0b15b557-3b7c-4613-99cc-d188b952ceef)

### Command Prompt/Terminal logs (if existing)

```bash
flixel/sound/FlxSound.hx (line 595)
flixel/sound/FlxSound.hx (line 739)
flixel/system/frontEnds/SoundFrontEnd.hx (line 183)
flixel/system/frontEnds/SoundFrontEnd.hx (line 241)
states/PlayState.hx (line 1003)
flixel/util/FlxTimer.hx (line 205)
flixel/util/FlxTimer.hx (line 295)
flixel/FlxGame.hx (line 750)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes. I deleted all weeks that are original. deleted sounds

**Comment by xxyuee** [comment]
did you delete the countdown sounds too?
