### ISSUE TITLE
Menu Error

### ISSUE THREAD

**Issue by StormzYT** [ShadowMario/FNF-PsychEngine#15213]
### Describe your bug here.

I'm trying to open the menu but this keeps happening, please help me on what to edit or change!
![Screenshot 2024-07-24 204653](https://github.com/user-attachments/assets/87f4858b-c005-4882-86e5-1fe0bd22c395)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, added my own mod

**Comment by xxyuee** [comment]
check the xmls you added if theres a missing =

**Comment by StormzYT** [comment]
> check the xmls you added if theres a missing =

i'll check
