### ISSUE TITLE
invalid char 47 at position 172

### ISSUE THREAD

**Issue by corakit** [ShadowMario/FNF-PsychEngine#15211]
### Describe your problem here.

i was doing some changes to the menu, everything normal. until out of nowhere, when i try to compile or just open normally, this appears
![image](https://github.com/user-attachments/assets/b39ea5e2-0428-4607-a09a-a9347c9761a7)
i tried the revert the changes i made, reinstall haxe, but nothing worked
i have to clarify that i compiled the game like 3 times minutes before that happened, it has nothing to do with the changes i made 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, MainMenuState.hx and gfDanceTitle.json

**Comment by FuseIsHere813** [comment]
Something's probably wrong with the modified gfDanceTitle.json file you have.

**Comment by corakit** [comment]
i realized that i was using an outdated version (0.7.2), so i downloaded the last, and compiled
my game did open this time, thank you for mentioning that
