### ISSUE TITLE
Hold notes bug after changing a note's direction

### ISSUE THREAD

**Issue by AnotherPlayer8** [ShadowMario/FNF-PsychEngine#15217]
### What is your question?

is there a way of fixing this?? it's just visual, doesn't affect gameplay in the slightest
![Captura de pantalla 2024-07-31 223324](https://github.com/user-attachments/assets/ac65a63f-1178-487a-a722-11196efa44e0)

**Comment by potatex2** [comment]
maybe try 
```lua
function onUpdatePost(elapsed)
    for note = 0, getProperty("unspawnNotes.length") - 1 do
        setPropertyFromGroup("unspawnNotes",i,"angle",0)
    end
end
```
I'm not sure if any offsets are needed depending on what angle it's at yet

**Comment by AnotherPlayer8** [comment]
> maybe try
> 
> ```lua
> function onUpdatePost(elapsed)
>     for note = 0, getProperty("unspawnNotes.length") - 1 do
>         setPropertyFromGroup("unspawnNotes",note,"angle",0)
>     end
> end
> ```
> 
> I'm not sure if any offsets are needed depending on what angle it's at yet

thanks, i just had to change the last 0 to the note angle
