### ISSUE TITLE
Problems with getProperty on 1.7.3

### ISSUE THREAD

**Issue by Arolox666** [ShadowMario/FNF-PsychEngine#15221]
### Describe your problem here.

So I was trying to get my note ratings counter to work you know the one that shows sicks, goods, bads, shits, misses etc. and I can't get the values using getProperty.

this is the code that changes the values
```lua
function onUpdate(elapsed)
    setTextString('cm', 'Combo: ' .. getProperty('combo'))
    setTextString('sick', 'Sicks!: ' .. getProperty('sicks'))
    setTextString('good', 'Goods: ' .. getProperty('goods'))
    setTextString('bad', 'Bads: ' .. getProperty('bads'))
    setTextString('shit', 'Shits: ' .. getProperty('shits'))
    setTextString('miss', 'Misses: ' .. getProperty('songMisses'))
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by xxyuee** [comment]
it changed to getProperty('ratingsData[n].hits'), n being 0 for sicks, 1 for goods and so on.

**Comment by Arolox666** [comment]
> it changed to getProperty('ratingsData[n].hits'), n being 0 for sicks, 1 for goods and so on.

OMG!!!! Thank you so much!!!! I would never figure this out.
