### ISSUE TITLE
Skip StoryMode Menu straight into a custom week

### ISSUE THREAD

**Issue by MaIfunctional** [ShadowMario/FNF-PsychEngine#15223]
### Describe your problem here.

How can I make it so that when a player presses the story mode menu, instead of bringing them to the story mode menu, it will instead load in a custom week, skipping the story mode menu altogether and bringing the player into a custom week?

I am modifying Psych Engine 0.6.2, and I do not plan to update it to the newest version.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I have only imported everything from my previous Psych Engine (Which was only lua) straight into custommods.

**Comment by ShadowMario** [comment]
0.6.2 is not supported anymore
