### ISSUE TITLE
"Type not found : TeaCall" Error

### ISSUE THREAD

**Issue by AdrianGaming0** [ShadowMario/FNF-PsychEngine#15220]
### Describe your bug here.

When im running "lime test windows" it always comes back with "Warning: Ignoring unknown fps" And Type not found : TeaCall
and im struggling to find the issue the full error is **source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall**

### Command Prompt/Terminal logs (if existing)

```bash
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\WINDOWS\system32> cd E:\StarlightFNF\FNF-PsychEngine-main
PS E:\StarlightFNF\FNF-PsychEngine-main> lime test windows
Warning: Ignoring unknown fps=""
source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No Everything Is untouched

**Comment by CoakyorCookie** [comment]
Go to hscript and edit the lines line 317, 349, and 359 and change TeaCall to Tea (if you don't know where hscript is, just search in file explorer.)

**Comment by AdrianGaming0** [comment]
It worked Thank you!

**Comment by CoakyorCookie** [comment]
> It worked Thank you!

No problem!

**Comment by DuskDragonNight75** [comment]
I tried the same thing and it just says Type not found : Tea
