### ISSUE TITLE
How can i change the menu options and move them?

### ISSUE THREAD

**Issue by eslendercarl1** [ShadowMario/FNF-PsychEngine#15222]
### Describe your problem here.

I am new to this source code and I don't know much about it, I would like to move the menu options freely and change them, 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by baobab121** [comment]
move buttons
```haxe
//in MainMenuState.hx
for (i in 0...optionShit.length)
{
	var offset:Float = 108 - (Math.max(optionShit.length, 4) - 4) * 80;
	var menuItem:FlxSprite = new FlxSprite(0, (i * 140) + offset);
	menuItem.antialiasing = ClientPrefs.data.antialiasing;
	menuItem.frames = Paths.getSparrowAtlas('mainmenu/menu_' + optionShit[i]);
	menuItem.animation.addByPrefix('idle', optionShit[i] + " basic", 24);
	menuItem.animation.addByPrefix('selected', optionShit[i] + " white", 24);
	menuItem.animation.play('idle');
	menuItems.add(menuItem);
	var scr:Float = (optionShit.length - 4) * 0.135;
	if (optionShit.length < 6)
		scr = 0;
	menuItem.scrollFactor.set(0, scr);
        menuItem.x(x) // for all buttons
	menuItem.updateHitbox();
	menuItem.screenCenter(X);
        // move buttons (separately). add it if you need to
        switch [i]
        {
                case 0:
                        menuItem.x = x
                        menuItem.y = y
                case 1:
                        menuItem.x = x
                        menuItem.y = y
               // 0 - story_mode, 1 - freeplay, 2 - mods, 3 - awards, 4 - credits, 5 - donate, 6 - options
         }
}

**Comment by eslendercarl1** [comment]
source/states/MainMenuState.hx:93: characters 3-11 : Missing ;
i got this error

**Comment by baobab121** [comment]
just put ; at the end of all these lines:
menuItem.x();
menuItem.y();

i just sometimes forget about them

**Comment by eslendercarl1** [comment]
source/states/MainMenuState.hx:92: characters 14-15 : Unknown identifier : x
source/states/MainMenuState.hx:98: characters 11-12 : Int should be Int -> -Tuple
source/states/MainMenuState.hx:99: characters 21-22 : ... For function argument 'value'
source/states/MainMenuState.hx:100: characters 21-22 : Unknown identifier : y
source/states/MainMenuState.hx:100: characters 21-22 : ... For function argument 'value'
source/states/MainMenuState.hx:101: characters 11-12 : Int should be Int -> -Tuple
source/states/MainMenuState.hx:102: characters 21-22 : Unknown identifier : x
source/states/MainMenuState.hx:102: characters 21-22 : ... For function argument 'value'
source/states/MainMenuState.hx:103: characters 21-22 : Unknown identifier : y
source/states/MainMenuState.hx:103: characters 21-22 : ... For function argument 'value'
got this error
