### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by renanivx** [ShadowMario/FNF-PsychEngine#15226]
### Describe your bug here.

Whenever I try to use this command "lime test windows" this keeps happening, how do I fix this? (version 0.7.2)

### Command Prompt/Terminal logs (if existing)

```bash
------------------------SScript 7.7.0 Macro------------------------
Special Thanks:
- CrowPlexus

Checking version...
There was an error getting the latest version info, you may not have internet connection.
Continuing...
-------------------------------------------------------------------

source/psychlua/CallbackHandler.hx:54: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
source/psychlua/CallbackHandler.hx:54: characters 41-46 : Class<llua.LuaL> has no field error
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
source/psychlua/FunkinLua.hx:280: lines 280-283 : Int should be Bool
source/psychlua/FunkinLua.hx:280: lines 280-283 : ... For function argument 'f'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CoakyorCookie** [comment]
Uninstall the source code and download a new one, if your psych engine version 7.2 source has setup. Click on that and then click on the file that says windows (I forgot the file name but it has Windows on it). Then click on the file path and type cmd, make sure this is your screen.
![Screenshot 2024-08-01 181834](https://github.com/user-attachments/assets/515ef858-e28e-4b27-8c57-0d762bde729c)
When you are in cmd, type lime test windows and let it do its magic. Hope this helps!

**Comment by renanivx** [comment]
I'm getting this error now:

Warning: Ignoring unknown fps=""
source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall

**Comment by renanivx** [comment]
Nevermind I downloaded a new source verison of the game

Thanks for helping!

**Comment by CoakyorCookie** [comment]
> I'm getting this error now:
> 
> Warning: Ignoring unknown fps="" source/psychlua/HScript.hx:317: characters 89-96 : Type not found : TeaCall
> 
> any ways to solve

Congratulations on solving the problem! Sorry if I am very late to reply because I'm modifying psych engine, there is another way.  I helped someone in issue #15220 the solution in the issue can help you!
