### ISSUE TITLE
My custom week doesn't load in Story mode or Freeplay

### ISSUE THREAD

**Issue by Chidubemmo** [ShadowMario/FNF-PsychEngine#15238]
### Describe your bug here.

The only way to make it show up is by editing a base game .json.
Jesus Christ on a hockey stick

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by butternyke** [comment]
Same thing's happening to me. No one knows the issue.

**Comment by Chidubemmo** [comment]
It works now.
I first forgot to add it in the weekList but it still didn't work so I had to change the name of the json for some reason???
