### ISSUE TITLE
Is there a way to make cutscenes in the source instead using videos?

### ISSUE THREAD

**Issue by Collabvmisgood** [ShadowMario/FNF-PsychEngine#1523]
### What is your question?

# Is there a way to make cutscenes in the source instead using videos.
**I want to use FlxTween to fade in the UI and the countdown plays when the cutscenes ends. Instead using videos.**
Thanks for reading!
@ShadowMario

**Comment by ShadowMario** [comment]
Yeah its possible, just replace the video function with your cutscene code.
