### ISSUE TITLE
Custom week isn't appearing in story mode menu OR freeplay.

### ISSUE THREAD

**Issue by butternyke** [ShadowMario/FNF-PsychEngine#15236]
### Describe your problem here.

No matter what I do, I can't seem to get my week to appear in any way. I'm still new to making my own mods, so I'll take all the help I can get.
The songs themselves work just fine in the chart editor.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Chidubemmo** [comment]
I have the same problem.
My only guess is either the version of Psych used or library conflicts.
If you find out can you tell me?

**Comment by butternyke** [comment]
Might be version. I'll go back to 0.7.1 (since 0.7.2 was a mess).

**Comment by butternyke** [comment]
I figured it out. The json files aren't supposed to be in folders within the weeks folder.

**Comment by ShadowMario** [comment]
Close the issue when you resolve it by yourself.
