### ISSUE TITLE
Player char is flipping??? 

### ISSUE THREAD

**Issue by Kitsuism** [ShadowMario/FNF-PsychEngine#15233]
### Describe your problem here.

i don't know why or how but custom chars are being forced to face to the right. how can i fix this??

https://github.com/user-attachments/assets/2fcda40d-7c66-49f1-bf41-7ec0a6041677

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CrusherNotDrip** [comment]
toggle this in character editor
![image](https://github.com/user-attachments/assets/1883942e-e964-486f-b1fa-39071d60e3d4)

**Comment by Kitsuism** [comment]
flip X just makes them face right all the way

**Comment by CoakyorCookie** [comment]
**Fixing Your Player and Icon:**

**Player is Facing Left:**
Check if "Flip X" is on. If it is, turn it off.

**Icon is Facing Wrong Way:**
Open the icon sheet in paint.NET.
Make the icon face the right direction.

**Still need help?**
Let me know, and I'll figure it out.
(im changing on how I reply or comment to people in GitHub or I will not do it lol)

**Comment by ShadowMario** [comment]
Check if any other mod might be causing a conflict, also try checking if you're messing with any sprite's flipX on your stage/lua scripts
