### ISSUE TITLE
How do I make floating characters in source code

### ISSUE THREAD

**Issue by AdrianPCman** [ShadowMario/FNF-PsychEngine#15232]
### Describe your problem here.

I’m trying to add floating characters
Like vs Dave and Bambi, vs shaggy etc in 0.5.2h DON’T ASK WHY

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
![fucktard](https://github.com/user-attachments/assets/1841cb31-98dc-4bab-a2a5-79267da0b50d)

**Comment by Chidubemmo** [comment]
Mess with FlxTween I assume???[ Shaggy's source code](https://github.com/GithubSPerez/the-shaggy-mod) is public but I personally can't find the code used
