### ISSUE TITLE
Listening to Song in Freeplay is weird

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#15248]
### Describe your bug here.

I don't know if that is fixed alredy, or will be kinda obsolete in the next update-
I'm listening to a long song ( 20:32 ) and it has split vocals. When I press space to listen to it, the entire audio sounds compressed
I can also only hear the instrumental, and no voices. So I don't know what exactly the cause is

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no source changes

**Comment by Shadow06735** [comment]
same thing happened to me, its probably because the split vocals thing wasn't made/fixed to sound clear in freeplay like when the vocals are both combined.

**Comment by Arolox666** [comment]
it might be that the audio file for instrumental is too long and flixel (The game engine FNF runs on) can't play it normaly
and as for the vocals IDK why aren't they playing probably just a bug that'll be fixed in next update.

**Comment by xxyuee** [comment]
vocals arent split in freeplay, its fixed in experimental though.
