### ISSUE TITLE
mod

### ISSUE THREAD

**Issue by downloader999** [ShadowMario/FNF-PsychEngine#15247]
### Describe your bug here.

i was putting a mod in mods folder and I opened the mod and it crashed

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
states/ModsMenuState.hx (line 829)
states/ModsMenuState.hx (line 85)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: [file_contents,mods/
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Arolox666** [comment]
What did the mod do? Did you add pack.json file into the mod folder?
Because the error ```bat
Uncaught Error: [file_contents,mods/
``` indicates that the mod folder is not being found by the engine. Maybe try renaming the folder.
