### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by zuzumi-f** [ShadowMario/FNF-PsychEngine#1524]
### Describe your problem here.

I'm having this error
i don't know what to do
![cmd_qs8mbIz8pm](https://user-images.githubusercontent.com/79029257/144053107-16098df4-ef62-41d8-b993-2ade01147418.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by HafimieForever** [comment]
ModsMenuState?? I never saw that on the source code

**Comment by zuzumi-f** [comment]
ModsMenuState was added 3 days ago
i downloaded the engine yesterdey

**Comment by SrtHero278** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/1419#issuecomment-980794707 Everyone has this problem

**Comment by Gui-iago** [comment]
temporary fix:

go to line 236 on MainMenuState.hx, and delete this

`									case 'mods':
										MusicBeatState.switchState(new ModsMenuState());`
										

then, delete the "ModsMenuState.hx" file, the game should compile just fine

**Comment by zuzumi-f** [comment]
thank you ^^
