### ISSUE TITLE
Load week with Lua

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#15243]
### Describe your problem here.

I need to keyJustPressed and this is work

function onUpdate(elapsed)

	if keyJustPressed('accept') then
		[week code load]
	end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Arolox666** [comment]
What exactly are you trying to achieve. From what I get you want to load week when accept is pressed but lua scripts work only in PlayState or the actual song.

**Comment by MaksPRO12667** [comment]
> What exactly are you trying to achieve. From what I get you want to load week when accept is pressed but lua scripts work only in PlayState or the actual song.

so sad....

**Comment by MaksPRO12667** [comment]
> > What exactly are you trying to achieve. From what I get you want to load week when accept is pressed but lua scripts work only in PlayState or the actual song.
> 
> so sad....
