### ISSUE TITLE
How can i add text in game over screen ?

### ISSUE THREAD

**Issue by TheShade250** [ShadowMario/FNF-PsychEngine#15249]
### Describe your problem here.

This is screenshots for the example i want (from QT mod).

First - Pressing the Reset Button

![Screenshot 2024-08-05 21-55-03](https://github.com/user-attachments/assets/73b60f9e-2945-4b52-a18d-05ab5f28cc2d)

Second - Dying by a sawblade.

![Screenshot 2024-08-05 21-55-24](https://github.com/user-attachments/assets/f74d2197-1b0a-43e9-b5e9-72803f5abb62)

How can add death text like in the QT mod please ? i want to add it in Psych Engine 0.7.3 !

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No. i search how to recreate this script in the QT mod.

**Comment by potatex2** [comment]
alright, i don't think shadow can help you there (someone else might because i don't know either) 
![image](https://github.com/user-attachments/assets/e5e8bdfc-1a9e-43f4-a92d-8df63b059f15)
