### ISSUE TITLE
can't find how to draw luasprite over notes

### ISSUE THREAD

**Issue by C64CassetteDrive** [ShadowMario/FNF-PsychEngine#15242]
### Describe your problem here.

i'm trying to make a sprite draw overtop the notes, and "setobjectorder('blahblah', getobjectorder('noteGroup') + 1)" "setobjectcamera('blahblah', 'hud') arent drawing it overtop of the notes, what else is there i could try ?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by baobab121** [comment]
try to setObjectOrder in onUpdate function

**Comment by C64CassetteDrive** [comment]
> try to setObjectOrder in onUpdate function

didnt work

**Comment by ShadowMario** [comment]
`setObjectCamera('yourObjectNameHere', 'hud')`

**Comment by C64CassetteDrive** [comment]
> setObjectCamera('yourObjectNameHere', 'camHUD')
i tried this already, but i tried both, and it worked, thank you ♥
