### ISSUE TITLE
cutscene wont work in source build (0.7.3)

### ISSUE THREAD

**Issue by Shadow06735** [ShadowMario/FNF-PsychEngine#15240]
### Describe your bug here.

every time I make a source build with 0.7.3 and implement the cutscene script then run the game, the game crashes every time. EVERY. SINGLE. TIME. how do i fix this?

heres the cutscene script i used:
local allowCountdown = false
function onStartCountdown()
        if not allowCountdown and isStoryMode and not seenCutscene then --Block the first countdown
                startVideo('cutscenenamehere');
                allowCountdown = true;
                return Function_Stop;
        end
        return Function_Continue;
end

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i only edited the health gain, icon bounce, intro text, rating text, and engine name

**Comment by CoakyorCookie** [comment]
Try doing it at the clean build (not source) and implement your script. There, it will help you see if the problem occurs in the clean build.

**Comment by Shadow06735** [comment]
> Try doing it at the clean build (not source) and implement your script. There, it will help you see if the problem occurs in the clean build.

it works perfectly fine in the clean build, idk why it wont work in the source build

**Comment by Shadow06735** [comment]
nvm i found out how to fix it #15085
