### ISSUE TITLE
Stage Editor Crashes When Scrolling Down To Nothing

### ISSUE THREAD

**Issue by verecundius** [ShadowMario/FNF-PsychEngine#15251]
### Describe your bug here.

In the stage editor, if you use W/S (S in this case) to scroll down in the layers to the bottom, it will crash. The crash report is

"states/editors/StageEditorState.hx (line 1420)
flixel/FlxGame.hx (line 868)
flixel/FlxGame.hx (line 565)
openfl/events/EventDispatcher.hx (line 426)
openfl/display/DisplayObject.hx (line 1398)

Uncaught Error: Null Object Reference"

Hope this helps!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing other than removing the check for updates

**Comment by FuseIsHere813** [comment]
issue is invalid, stage editor state file wasn't found in repo.

**Comment by FuseIsHere813** [comment]
+ shadow did say the stage editor is low priority
