### ISSUE TITLE
How do I fix this or does anyone know what this means

### ISSUE THREAD

**Issue by GD202nevercominout** [ShadowMario/FNF-PsychEngine#15252]
### What is your question?

How do I fix this
![IMG_2624](https://github.com/user-attachments/assets/5a8ef732-2144-49e1-9472-32d0b089b35b)

**Comment by GD202nevercominout** [comment]
Please any one

**Comment by Arolox666** [comment]
What were you doing when this error occured?

I see you have VS Code open were you making a lua mod or source code?

**Comment by GD202nevercominout** [comment]
> What were you doing when this error occured?
> 
> I see you have VS Code open were you making a lua mod or source code?

**Comment by GD202nevercominout** [comment]
> What were you doing when this error occured?
> 
> I see you have VS Code open were you making a lua mod or source code?

I was coding an all stars remake and I tried to transition to omega and the game keeps crashing

**Comment by Arolox666** [comment]
And when you delete the script the game works, right?

Also could you send me the script so I can look if there's any problem with it?

And one more question which version are you running?

**Comment by GD202nevercominout** [comment]
> And when you delete the script the game works, right?
> 
> Also could you send me the script so I can look if there's any problem with it?
> 
> And one more question which version are you running?

1. No because the script needed and it works for another song but not mine

2. how do I send

3. most recent update I think 0.7.3

**Comment by Arolox666** [comment]
You can add attachments so just add the script as attachment. Or just copy/paste it.

**Comment by GD202nevercominout** [comment]
> You can add attachments so just add the script as attachment. Or just copy/paste it.

this is the script that crashes 

        elseif v1 == '2' then
            if v2 == '1' then
                if getSongPosition() < 223910 then --Used to not load the sprites if you are not in their stage, useful if you are using Skip Time on charting mode
                    triggerEvent('Change Character','bf','bf_behind')
                    triggerEvent('Change Character','dad','omega')
                    triggerEvent('Change Character','gf','lg2')


                    removeFromMemory('bfnew',true)
                    removeFromMemory('gfplayable',true)
                    removeFromMemory('mario_ultra1',true)

                    removeExtraIcon('gfIcon',true)
                    addExtraIcon('gfIcon','LG',false)
                    extraIcon('setIconAsPrincipal','gfIcon')
                    extraIcon('setIconProperty',{'gfIcon','followAlpha',false})
               end

**Comment by Arolox666** [comment]
IDK what is before the elseif but it might check if you are on a specific stage/song and if not it just crashes. The error "Null Object Reference" happens to me all the time and if restarting the engine didn't help then it has to be issue with the script.
