### ISSUE TITLE
Can I make "Rendered Notes" counter using lua?

### ISSUE THREAD

**Issue by Arolox666** [ShadowMario/FNF-PsychEngine#15260]
### What is your question?

Hi I just wanna ask how to make a "Rendered Notes" counter if possible in Psych. BTW I'm using 0.7.3

I even tried it using lua but it counts opponent notes too I want just bf's notes to be counted.
Here is my code:
```lua
function onCreate()
    makeLuaText("renderedNotes", "Rendered Notes: 0", 0, 0, 0.0)
    screenCenter("renderedNotes", 'y')
    setTextSize("renderedNotes", 69)
    addLuaText("renderedNotes")
end

---
--- @param elapsed float
---
function onUpdate(elapsed)
    setTextString("renderedNotes", "Rendered Notes: " ..getProperty("notes.length"))
end
```

**Comment by Cyachao** [comment]
you just iterate over notes and check their `mustPress` property, it's true for bf's notes

**Comment by Arolox666** [comment]
> you just iterate over notes and check their `mustPress` property, it's true for bf's notes

I'm no professional so how do I do this?

**Comment by Cyachao** [comment]
there is no professional stuff involved, it's just basics
```local noteCount = 0
for i = 0, getProperty('notes.length')-1 do
    if getPropertyFromGroup('notes', i, 'mustPress') then
        noteCount = noteCount + 1
    end
end
setTextString('renderedNotes', 'Rendered Notes: '..noteCount)
```
having "rendered notes" only count player notes is also kind of misleading
