### ISSUE TITLE
hold note animation

### ISSUE THREAD

**Issue by AlexTheGuy73** [ShadowMario/FNF-PsychEngine#15269]
### What feature do you want to get added on the **base** engine?

can you add the fnf 0.4.1 hold strum note animation? and that long note splash, pretty please
i tried add it but idk how to code lol'nt
please i will be very happy if you add it.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
Character -hold animations are already available on Experimental, I will not add hold note splashes.

**Comment by AlexTheGuy73** [comment]
I mean, the weekend 1 update new splash notes of the long notes (when you
end a long note the splash animation start)
