### ISSUE TITLE
When playing some songs the note splashes dont look right

### ISSUE THREAD

**Issue by FandomFikz** [ShadowMario/FNF-PsychEngine#15262]
### Describe your bug here.

on some songs i play, the note splashes sort of bug out and turn red and green.. 
![image](https://github.com/user-attachments/assets/73569675-37ff-4589-acc9-7df32b0615b6)
 i dont really get how the note/note splash coloring system works at all but i know its not really supposed to do this..
it happens even with other note splashes aswell
![image](https://github.com/user-attachments/assets/953ef7b5-0769-4593-9c85-ada257bdb105)
its not a game breaking bug but id like for my note splashes to actually look right.. any help??

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by HourOfEternity** [comment]
It looks like the noteSplash rgb shader is turned off.
Try using this:

function onCreate()		
		for i = 0, getProperty('unspawnNotes.length')-1 do
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashData.useRGBShader', true);
			end
		end
end

Hope this helps!
