### ISSUE TITLE
The plugins folder and 2 .dll files are missing. What am I doing wrong?

### ISSUE THREAD

**Issue by ByBinti** [ShadowMario/FNF-PsychEngine#15261]
### What is your question?

When I compile the game in the export folder I am missing the plugins folder and 2 .dll files (libvlc.dll, libvlccore.dll). Because of this my mod is not working properly. Older versions of Psych have these files when I compile them, but not the new one. 
![0-7-2](https://github.com/user-attachments/assets/17e85213-7711-4d0c-b8c5-03f16aeee3ea)
![0-7-2h](https://github.com/user-attachments/assets/85aaea0b-6759-4cc1-989e-09e55fe4f415)
![0-7-3](https://github.com/user-attachments/assets/27afa627-9f3d-4363-bd70-d9d7bf91958d)

**Comment by Arolox666** [comment]
check project.xml for something like "VIDEOS_ALLOWED" and change it to true. And if it is not there then IDK

**Comment by ByBinti** [comment]
> check project.xml for something like "VIDEOS_ALLOWED" and change it to true. And if it is not there then IDK

thank u i just had to do this:
![ehhh](https://github.com/user-attachments/assets/971589e6-f777-4c25-a4f5-82a33bd5cb75)
