### ISSUE TITLE
Change Character with lua

### ISSUE THREAD

**Issue by SuperScratchSpyro** [ShadowMario/FNF-PsychEngine#15263]
### Describe your problem here.

Hi. I'm wondering if there's a way to change the player character with lua coding midsong. I need it for a script I'm working on.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by butternyke** [comment]
Just find a character change event file. I know lots of Dave and Bambi mods have them. My mod borrowed that script from Nullified. Remember to find both the .json and the .txt files and place them in the custom events folder.

**Comment by xxyuee** [comment]
function onUpdate()
    if curBeat == number then
        triggerEvent('Change Character', 'bf', '')
    end
end

**Comment by SuperScratchSpyro** [comment]
Thanks!
