### ISSUE TITLE
Sections refuse to load or work after a specific number.

### ISSUE THREAD

**Issue by butternyke** [ShadowMario/FNF-PsychEngine#15277]
### Describe your bug here.

I was in the middle of charting, and I saw that when I hit section 202 in this song and ONLY this song, and try to load 203, it brings me back to section 0.
![2024-08-0903-27-34-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/a1eeb696-3557-45d1-b382-0786f0deb16b)
Even when I play the song both in-game AND in the chart editor, the song keeps playing until it ends (song is over 3:40). When I load other songs in the editor, even a 9 minute long placeholder song, I can load every section with no issue. Just this ONE song is bugged.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only freakyMenu.ogg, which wouldn't affect this.

**Comment by butternyke** [comment]
I also tried porting the song to another copy of the engine and the same thing happened.

**Comment by butternyke** [comment]
... oh
thanks

**Comment by ShadowMario** [comment]
Fixed in prelease 1.0
