### ISSUE TITLE
html5 is broken

### ISSUE THREAD

**Issue by SpareEnderboy** [ShadowMario/FNF-PsychEngine#15279]
### Describe your bug here.

i compiled psych engine for html5 and it didn't come with psychengine.js

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by tposejank** [comment]
??????

**Comment by mll-enh** [comment]
0.7.x isn't supported for HTML5.

**Comment by ShadowMario** [comment]
HTML5 is not supported anymore because it sucks
