### ISSUE TITLE
Help me pls

### ISSUE THREAD

**Issue by Erik333222** [ShadowMario/FNF-PsychEngine#15272]
### Describe your bug here.

what should i do if i import a character on fnf psych engine and it says "ERROR: No animation found"?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Magniill** [comment]
add the animations

**Comment by ShadowMario** [comment]
You have to add the Animations, there's literally a tab named "Animation" inside the Character Editor
