### ISSUE TITLE
how do i compile psych source code

### ISSUE THREAD

**Issue by st0lent0aster** [ShadowMario/FNF-PsychEngine#15276]
### Describe your problem here.

how

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by st0lent0aster** [comment]
it says i need a proj xml file
i already inserted a blank xml so idk

**Comment by FuseIsHere813** [comment]
why 💀 

just download the source, from here, extract it, open it, run a cmd to that folder and THEN follow the instructions [here.](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/BUILDING.md)
