### ISSUE TITLE
On Ghost Tap Just Doesn't Work

### ISSUE THREAD

**Issue by Average-FNF-Modder** [ShadowMario/FNF-PsychEngine#15274]
### Describe your bug here.

The function onGhostTap(key) does litterally nothing. I wanted to make a system to take waway the players HP on a ghost tap, but still with the setting on so it doesn't hurt your accuracy, so I was sad to learn that on ghost tap just nothing. I can't even get it to debug print a message! This should be fixed.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, sure didn't.

**Comment by FuseIsHere813** [comment]
this is just how 0 ghost tapping would work in the base game, without the miss animations and score reduction

**Comment by Average-FNF-Modder** [comment]
> this is just how 0 ghost tapping would work in the base game, without the miss animations and score reduction

Precisely, and I was also thinking of having it remove some score as well. I like the way base game does it so was trying to recreate that in Psych. Unfortunately...

**Comment by FuseIsHere813** [comment]
You could just force ghostTapping off for that song by running a `setPropertyFromClass('backend.ClientPrefs', 'ghostTapping', false)` variable.

**Comment by Average-FNF-Modder** [comment]
> You could just force ghostTapping off for that song by running a `setPropertyFromClass('backend.ClientPrefs', 'ghostTapping', false)` variable.
> 
> Not sure why you would want to disable the ghost tapping, tho.

That wouldn't do what I want it to, because then it would affect accuracy, while I just want the player to get hurt for it. The bug report would still stand anyways 😭
