### ISSUE TITLE
how to make the incoming notes stutter for modcharts

### ISSUE THREAD

**Issue by inkyerik** [ShadowMario/FNF-PsychEngine#15270]
### Describe your problem here.

i can't explain it so here is a gif (basically the incoming notes stop after and then move quickly to a further pos):
(using 0.6.3)
![how-make-note-stutter](https://github.com/user-attachments/assets/3bf6fe52-bf51-41c8-80c4-f4a81257bda6)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by FuseIsHere813** [comment]
you may be on your own with this one buckaroo

0.6.3 wasn't supported anymore since december 2023

**Comment by inkyerik** [comment]
> you may be on your own with this one buckaroo
> 
> 0.6.3 wasn't supported anymore since december 2023

ah i see
