### ISSUE TITLE
Psych Engine : Opening and closing when you open it

### ISSUE THREAD

**Issue by SyncGit12** [ShadowMario/FNF-PsychEngine#15283]
### Describe your bug here.

After compiling, the game launches automatically

Common right?

Except it crashes right away.
Even if launching from FNF-PsychEngine-main/export/release/windows/bin/PsychEngine.exe!! (in my case, its unknown.exe)

### Command Prompt/Terminal logs (if existing)

```bash
Warning: Ignoring unknown fps=""
Creating C:/Users/<not going to show username>/Desktop/FNF-PsychEngine-main/export/release/windows/obj/obj/msvc1964-nc/__pch/haxe/hxcpp.pch...
hxcpp.cpp

Compiling group: haxe
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/hxdiscord_rpc/git/project/discord-rpc/include -DDISCORD_DISABLE_IO_THREAD -IC:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\Noah\Desktop\FNF-PsychEngine-main\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,3,2/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_CHECK_POINTER(haxe) -DHXCPP_STACK_TRACE(haxe) -DHXCPP_STACK_LINE(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=430(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/ApplicationMain.cpp
 - src/states/TitleState.cpp
 - src/lime/utils/AssetCache.cpp  [haxe,release]
Link: ApplicationMain.exe
   Creating library ApplicationMain.lib and object ApplicationMain.exp
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited Project.xml a little bit

**Comment by SyncGit12** [comment]
also i edited TeaCall to Tea

**Comment by ShadowMario** [comment]
![image](https://github.com/user-attachments/assets/4e75e065-aa86-48b5-91f9-6a102d62a05f)
Your Project.xml is configured incorrectly

**Comment by tposejank** [comment]
> ![image](https://private-user-images.githubusercontent.com/44785097/367622866-4e75e065-aa86-48b5-91f9-6a102d62a05f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NDI5NDcsIm5iZiI6MTcyNjQ0MjY0NywicGF0aCI6Ii80NDc4NTA5Ny8zNjc2MjI4NjYtNGU3NWUwNjUtYWE4Ni00OGI1LTkxZjktNmExMDJkNjJhMDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDIzMjQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZjY4NjBhZmMzNDllZTE3NDVhODE3MTUxM2U4YjZmOWJlYzU0NGNiMmEzNjM5ODNkMmU5MjYxMzcxOTc0MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ouLn9zGcOIdUHqXt7KSJJCm5b8XNduh7nffgVApmxJs) Your Project.xml is configured incorrectly

Unrelated note but that will not cause errors
