### ISSUE TITLE
Compiling issue like 2 billion at this point

### ISSUE THREAD

**Issue by thebiggestofchunguses** [ShadowMario/FNF-PsychEngine#15287]
### What is your question?

------------------------SScript 7.7.0 Macro------------------------
Special Thanks:
- CrowPlexus

Checking version...
There was an error getting the latest version info, you may not have internet connection.
Continuing...
-------------------------------------------------------------------

source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here

I have no clue on how to fix it I've been trying to fix it for the past 3 days

**Comment by FJRODDUR** [comment]
Try to either:
1. Add a _sendErrorsToLua_ field to the Lua_helper class, or
2. Remove the reference to _sendErrorsToLua_ from the **CallbackHandler.hx** file

or try to use the original code from the psych engine repository, hope this helps

**Comment by thebiggestofchunguses** [comment]
Thanks but how can I do that? Sorry I'm not that good at this Kinda stuff

**Comment by FJRODDUR** [comment]
In VSCode, or whatever IDE you have, search for the CallbackHandler file and open it.
On line 55, inside of the "catch(e:Dynamic)" thing, add this code (between line 55 and 57), this should work
![imagen](https://github.com/user-attachments/assets/7d26c380-5aab-4c77-9c48-024f30854c34)

If this doesn't work, just download the file and reemplaze it:
https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/psychlua/CallbackHandler.hx

**Comment by LarryFrosty** [comment]
you just need to use the git library
```
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
```

**Comment by thebiggestofchunguses** [comment]
Thanks for all of this but this is what I got back
------------------------SScript 7.7.0 Macro------------------------
Special Thanks:
- CrowPlexus

Checking version...
There was an error getting the latest version info, you may not have internet connection.
Continuing...
-------------------------------------------------------------------

C:\Users\buttu\Downloads\PSYCH\FNF-PsychEngine-main\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by FJRODDUR** [comment]
You don't have installed the MSVC thing, open the setup-msvc-win.bat on the setup folder of your source mod

**Comment by ShadowMario** [comment]
There are 73 duplicates to this issue.
https://github.com/ShadowMario/FNF-PsychEngine/issues/14526
