### ISSUE TITLE
How can i change alpha in Lua Text?

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#15286]
### Describe your problem here.

I want to change alpha in Lua Text... Can i do it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by xxyuee** [comment]
you can use either setProperty("[text name].alpha", number) or doTweenAlpha()

**Comment by MaksPRO12667** [comment]
Oh, sweet honey... doTweenAlpha work, i'm sorry
Thank you very much
