### ISSUE TITLE
uhh a i am pretty stuck here

### ISSUE THREAD

**Issue by waleedbug** [ShadowMario/FNF-PsychEngine#15280]
### Describe your bug here.

<img width="584" alt="image" src="https://github.com/user-attachments/assets/5455e38b-c331-458b-b6be-ef264bdf4759">

### Command Prompt/Terminal logs (if existing)

```bash
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/hxdiscord_rpc/git/project/discord-rpc/include -DDISCORD_DISABLE_IO_THREAD -IC:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\wals\Documents\fnf\FNF-PsychEngine-main\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,3,2/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_CHECK_POINTER(haxe) -DHXCPP_STACK_TRACE(haxe) -DHXCPP_STACK_LINE(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=430(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i edited HScript.hx from teaCall to tea

**Comment by Arolox666** [comment]
If it worked before delete export folder that should fix the issue. This happens if you moved the folder as the files are still tied to the original location.

**Comment by waleedbug** [comment]
No it's the first time and it didn't work
