### ISSUE TITLE
First Frame only? ERROR: No Animation Found

### ISSUE THREAD

**Issue by YoshiUUMagic** [ShadowMario/FNF-PsychEngine#15285]
### Describe your problem here.

https://github.com/user-attachments/assets/9564dcec-04e4-429c-b005-5229d2a05fdb

the video shows what's happening lol, but I have a problem where I put in all the png and xml files into the PsychEngine-Windows64\PsychEngine\mods\mod-template\images\characters and the json into the /mod-template/characters. But when I load the character file it only shows the first frame and state error: no animation found. What do I do? If you don't understand anything I said I can go into depth. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by FuseIsHere813** [comment]
This has got to be the most simple issue I have EVER seen.

Just go to Animations > go to the animation name: (idle, singLEFT, etc.) and _**SET the animation on xml/txt file to your specific sprite's character animation.**_
![image](https://github.com/user-attachments/assets/30627187-584b-4c6e-bdd2-52d1c5eae223)

**Comment by YoshiUUMagic** [comment]
> This has got to be the most simple issue I have EVER seen.
> 
> Just go to Animations > go to the animation name: (idle, singLEFT, etc.) and _**SET the animation on xml/txt file to your specific sprite's character animation.**_ ![image](https://private-user-images.githubusercontent.com/77396398/356843939-30627187-584b-4c6e-bdd2-52d1c5eae223.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNDAxNzMsIm5iZiI6MTcyMzMzOTg3MywicGF0aCI6Ii83NzM5NjM5OC8zNTY4NDM5MzktMzA2MjcxODctNTg0Yi00YzZlLWJkZDItNTJkMWM1ZWFlMjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDAxMzExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYjU2OGFiZjYzM2RkNjQ2Mjk3YjQ4ZjBjN2E3OTQ2NjhhZGQxMjJjZTIzZDYxNzc3YzgzZjk5NzQ4OWZmMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xy3kkvd5BZUJvq7nWF93TtNKvxvKewWM86dsSXvPW9M)

Thanks bro :)
