### ISSUE TITLE
0 FPS and black screen, then it closes

### ISSUE THREAD

**Issue by Ballerguywhat** [ShadowMario/FNF-PsychEngine#15282]
### Describe your problem here.

haven't been able to use Psych Engine for a while now because of this issue, I've had to put my mod on hold because of this, no other engines work either. I've tried everything. PLEASE HELP ME I WANNA PLAY FNF AGAIN

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Ballerguywhat** [comment]
Think i found an issue, my, the .dll files aren't in the portable executable format.
![1](https://github.com/user-attachments/assets/55322f52-e0c5-459b-ae2a-e582a4c542da)

**Comment by ShadowMario** [comment]
Try deleting your save files at %appdata%

**Comment by Ballerguywhat** [comment]
> Try deleting your save files at %appdata%

Didn't work, still the same issue
  I'll send a video of the error.

**Comment by Ballerguywhat** [comment]
https://github.com/user-attachments/assets/43894dd9-4a8c-4a46-886f-3f421fdc6f08

This is what happens

**Comment by FuseIsHere813** [comment]
"PP Engine" definitely a modified psych, i suggest you contact the main owner of the modded engine about this issue.

**Comment by Ballerguywhat** [comment]
> "PP Engine" definitely a modified psych, i suggest you contact the main owner of the modded engine about this issue.

Bro psych engine does the same error
😭

**Comment by FuseIsHere813** [comment]
afraid that I can't help sadly, psych works fine for everyone else, so it might be some sort of pc related issue or smth i am unaware of.

**Comment by Ballerguywhat** [comment]
> afraid that I can't help sadly, psych works fine for everyone else, so it might be some sort of pc related issue or smth i am unaware of.

Bruh, i cant find a pc problem, Psych worked beforehand, so this shouldn't be happening

**Comment by Ballerguywhat** [comment]
I swear im actually about to just play the HTML ports and rofnf

**Comment by ShadowMario** [comment]
Try moving the main folder to C:\Program Files\

**Comment by Ballerguywhat** [comment]
> Try moving the main folder to C:\Program Files, that's all help we can offer here since this sounds like a problem with your PC

![Screenshot 2024-09-15 191922](https://github.com/user-attachments/assets/29ef29dd-c55b-409e-b609-e7c52c31b0db)
LETS FUCKING GO!!!! THANK YOU SO MUCH, YOU'RE A LIFESAVER

**Comment by Ballerguywhat** [comment]
Shadow Mario, thank you so much for helping me. Even though i was difficult you still pushed through. I am forever grateful.
