### ISSUE TITLE
How to resize Window with OnStepHit?

### ISSUE THREAD

**Issue by MaximusMax09** [ShadowMario/FNF-PsychEngine#15281]
### What is your question?

Hello, I am making an FNF Mod with 4th Wall breaks
In one song the window moves around on it's own but to make it work, the Window needs to change size mid song
I tried to make a script but it just doesn't work.

Here is the script I made:

local windowWidth = 960

local windowHeight = 720

local curstep

function onStepHit()
    if curstep = 368 then
    setPropertyFromClass("openfl.Lib", "application.window.width", windowWidth)

    setPropertyFromClass("openfl.Lib", "application.window.height", windowHeight)
end

Can someone help me?

**Comment by FuseIsHere813** [comment]
windowWidth or windowHeight must be a value (i.e numbers).

**Comment by xxyuee** [comment]
no need to make a new curstep variable, curStep already exists

**Comment by FuseIsHere813** [comment]
stale
