### ISSUE TITLE
I had this problem trying to compile 0.7.3

### ISSUE THREAD

**Issue by DaDinoGuy** [ShadowMario/FNF-PsychEngine#15284]
### What needs to be documented?

Called from ? line 1
Called from CommandLineTools.hx line 1400
Called from CommandLineTools.hx line 25
Called from a C function
Called from CommandLineTools.hx line 125
Called from CommandLineTools.hx line 1279
Called from lime/project/ProjectXMLParser.hx line 21
Called from a C function
Called from lime/project/ProjectXMLParser.hx line 54
Called from lime/project/ProjectXMLParser.hx line 1802
Called from lime/project/ProjectXMLParser.hx line 1267
Called from /usr/lib/haxe/std/haxe/xml/Fast.hx line 56
Uncaught exception - library is missing attribute path

**Comment by FJRODDUR** [comment]
I think the haxeflixel libraries aren't added to your PATH directory, try reinstalling them with the bat setup inside "setup folder" on your source code and restart your PC, this should fix the problem
