### ISSUE TITLE
Menu BG

### ISSUE THREAD

**Issue by YoshiUUMagic** [ShadowMario/FNF-PsychEngine#15289]
### What is your question?

Ayo! I would like to know how to change the background in the main menu. That yellow thing with BF and GF in it. If it contains code I'll take it. :>

**Comment by potatex2** [comment]
![image](https://github.com/user-attachments/assets/8fbbff22-3961-465e-82eb-dcb799f150ed)
set the custom image with the resolutions, and the characters in images/menucharacters if applicable. you can do this in the main debug menu in menu character editor and/or week editor

**Comment by YoshiUUMagic** [comment]
> ![image](https://private-user-images.githubusercontent.com/96308850/356933625-8fbbff22-3961-465e-82eb-dcb799f150ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTkzOTcsIm5iZiI6MTcyMzQ5OTA5NywicGF0aCI6Ii85NjMwODg1MC8zNTY5MzM2MjUtOGZiYmZmMjItMzk2MS00NjVlLTgyZWItZGNiNzk5ZjE1MGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDIxNDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMzQ5ZTFkMzA2MDA4MDUwY2Y4Y2M1OGUxM2U5MTUzMjJjOWVjMzViN2JiNTg1MGE2YzgzNWZlY2MxMDhkNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oVK5c4f35wEAuq39CffPZVPOd9VFyZ4qx12T7VSo3_U) set the custom image with the resolutions, and the characters in images/menucharacters if applicable. you can do this in the main debug menu in menu character editor and/or week editor

Does it have to be a certain length cause it's not working.

**Comment by YoshiUUMagic** [comment]
is there another way <:) oof...

**Comment by SamuXDD** [comment]
You mean the menuBG an the variants ?
if yes, then you can just modify the images only remember that it needs to be the same resolution as the original images :D

**Comment by YoshiUUMagic** [comment]
in variants?? okay! Ill try! :)

**Comment by YoshiUUMagic** [comment]
okay ill try! :3

**Comment by YoshiUUMagic** [comment]
wait what images??? <:/

**Comment by YoshiUUMagic** [comment]
> You mean the menuBG an the variants ? if yes, then you can just modify the images only remember that it needs to be the same resolution as the original images :D

I really can't find the images :( Does it go along the source code?

**Comment by SamuXDD** [comment]
are you talkin about the main menu or story menu ?

**Comment by YoshiUUMagic** [comment]
> are you talking about the main menu or story menu ?

its whenever the game firsts loads and you click enter then you see all the stuff like story mode, awards, freeplay, credits, that background

**Comment by SamuXDD** [comment]
go to the images folder ("assets/shared/images" in 0.7.3) and look for "menuBG" and there you can edit the image and all the other variants like : menuBGBlue, menuBGMagenta, menuDesat.

**Comment by YoshiUUMagic** [comment]
Thank You!!! :D
