### ISSUE TITLE
shaders

### ISSUE THREAD

**Issue by IKVITS** [ShadowMario/FNF-PsychEngine#15298]
### Describe your problem here.

Hello, does anyone know how to make an opoonentNoteHit function that makes a shader appear and when you stop playing the note it disappears?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MaksPRO12667** [comment]
I came up with something like shit, but it seems work

write it in onCreate() : 
	function opponentNoteHit(id, direction, noteType, isSustainNote)
		if cameraSetTarget("dad") then
			runHaxeCode([[
				var shaderName = "]] .. shaderName .. [[";
					
				game.initLuaShader(shaderName);
					
				var shader0 = game.createRuntimeShader(shaderName);
				game.camGame.setFilters([new ShaderFilter(shader0)]);
				game.getLuaObject("yourshader").shader = shader0;
				game.camHUD.setFilters([new ShaderFilter(game.getLuaObject("yourshader").shader)]);
				return;
			]])
		end
	end
	function onMoveCamera(focus)
		if focus == 'boyfriend' then
			runHaxeCode([[
				game.camGame.setFilters([]);
				game.camHUD.setFilters([]);
			]])
		end
	end

**Comment by MaksPRO12667** [comment]
if you don't understand shaders well, then a video from a Russian YouTuber will help (There is a little more detail on how shaders work.):
https://youtu.be/9fG45AYNkgY?si=69EeF88TVZL9qTiT
