### ISSUE TITLE
null reference bruh

### ISSUE THREAD

**Issue by serik-oof** [ShadowMario/FNF-PsychEngine#15297]
### Describe your bug here.

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

### Command Prompt/Terminal logs (if existing)

```bash
states/FreeplayState.hx (line 72)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 426)
openfl/display/DisplayObject.hx (line 1398)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i just compiled it and when i open freeplay he immediately gives me this error

**Comment by FuseIsHere813** [comment]
one of the week jsons could possibly be invalid

**Comment by serik-oof** [comment]
nvm, i found the bug

**Comment by ISamwise4** [comment]
WHAT IS THE BUG PLEASE HELP ME
