### ISSUE TITLE
how to make lua sprite layer bigger than notes and etc

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#15294]
### Describe your problem here.

I want the sprite to cover everything, even the notes, etc

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by FuseIsHere813** [comment]
```
addLuaSprite('yoursprite', true)
scaleObject('yoursprite', value, value)
```

**Comment by MaksPRO12667** [comment]
> ```
> addLuaSprite('yoursprite', true)
> scaleObject('yoursprite', value, value)
> ```

No, i'm talking about LAYER not scale

**Comment by FuseIsHere813** [comment]
`addLuaSprite('yoursprite', true)` is only necessary then

**Comment by MaksPRO12667** [comment]
> `addLuaSprite('yoursprite', true)` is only necessary then

but how can i make lua sprite on which you can't even see the notes? Or i can't do it?

**Comment by xxyuee** [comment]
setObjectCamera('sprite', 'other')

**Comment by MaksPRO12667** [comment]
> setObjectCamera('sprite', 'other')

You again? Thank you very much!
