### ISSUE TITLE
Stuck on creating the application.

### ISSUE THREAD

**Issue by ThreeLittleNinjas** [ShadowMario/FNF-PsychEngine#15296]
### Describe your bug here.

Whenever I compile the game, it gets stuck at Link: ApplicationMain.exe, Creating library ApplicationMain.lib and object ApplicationMain.exp

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I just edited Project.xml, StoryMenuState.hx, and FreeplayState.hx.

**Comment by WolfyTail** [comment]
If you wrote "lime BUILD windows" instead of TEST, the game compiles but doesn't open automatically. Idk if that's what you did.

**Comment by ThreeLittleNinjas** [comment]
The application doesn't show up either, so idk

**Comment by ThreeLittleNinjas** [comment]
Here's some pics for some info:

![image](https://github.com/user-attachments/assets/d259a47d-9051-4943-aa11-7df9a085a9a3)
![image](https://github.com/user-attachments/assets/9a0ff92b-081c-4d2e-a0c8-ef98f6c94041)

**Comment by Lumi1323** [comment]
i have the same problem. :(
