### ISSUE TITLE
TeaCall Issue

### ISSUE THREAD

**Issue by GatoMagoXD** [ShadowMario/FNF-PsychEngine#15292]
### Describe your problem here.

`source/psychlua/HScript.hx:317: Characters 89-96 : Type not found : Teacall`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I dont edit anything

**Comment by NightmaresPlayz** [comment]
You need to go to source/states/playstate.hx, and replace every TeaCall with Tea, i think thats what you do

**Comment by MadLuck-20** [comment]
you need to go to source/psychlua/HScript.hx and replace "TeaCall" with "Tea", but u could have issues with any other hxscript outside of the source code. I don't know how to fix these issues

**Comment by FJRODDUR** [comment]
In the source/psychlua/HScript.hx, replace "TeaCall" with "Tea".

This should fix the problem

If this doesn't work, try using this command on your terminal:
haxelib set SScript 7.7.0

**Comment by WolfyTail** [comment]
Go to the wiki, and Libraries versions. Set every lib to the SPECIFIC VERSION it's in the wiki. Idk if it'll work
