### ISSUE TITLE
Another bug pls help

### ISSUE THREAD

**Issue by thebiggestofchunguses** [ShadowMario/FNF-PsychEngine#15306]
### Describe your bug here.

I uh just need help with this

### Command Prompt/Terminal logs (if existing)

```bash
------------------------SScript 7.7.0 Macro------------------------
Special Thanks:

CrowPlexus
Checking version...
There was an error getting the latest version info, you may not have internet connection.
Continuing...
C:\Users\buttu\Downloads\PSYCH\FNF-PsychEngine-main\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

None, I think

**Comment by xxyuee** [comment]
its not a bug, you mightve forgot to install visual studio or its build tools.

**Comment by thebiggestofchunguses** [comment]
oh uh witch ones do I need to install tho?

**Comment by MaksPRO12667** [comment]
> oh uh witch ones do I need to install tho?

yes

**Comment by thebiggestofchunguses** [comment]
can you be more specific?

**Comment by MaksPRO12667** [comment]
> oh uh witch ones do I need to install tho?



> can you be more specific?

Ohh.... hahahah, i'm sorry
If I'm not mistaken, then you need install Visual Studio 2019, run the visual studio installer setup file and go to the individual components tab
and select these two for install:

MSVC v142 - VS 2019 C++ x64/x86 build tools
Windows SDK(10.0.17763.0)

Click install and wait until it's done

And also you can install Visual Studio Code
This is so you can edit code later for modding

**Comment by thebiggestofchunguses** [comment]
Okay I installed both but It still failed

**Comment by MaksPRO12667** [comment]
> Okay I installed both but It still failed

idk maybe this help:
https://www.youtube.com/watch?v=7ms9U9Wfmac

**Comment by thebiggestofchunguses** [comment]
I already tried those

**Comment by MaksPRO12667** [comment]
> I already tried those

well... fuck
I can't help you here, sorry... Try to do everything again and in order, maybe you missed something

**Comment by thebiggestofchunguses** [comment]
ok ):
