### ISSUE TITLE
How to check runHaxeCode in lua?

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#15308]
### Describe your problem here.

Can I make it so that when the haxelib code is triggered, local shittext = 1?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
Use `setVar('shittext', 1)` inside the runHaxeCode, then in the lua script you can use `getVar('shittext')`
