### ISSUE TITLE
Psych Haxe not allowing pre-set variables to be edited.

### ISSUE THREAD

**Issue by Sonicgamer2000** [ShadowMario/FNF-PsychEngine#15307]
### Describe your bug here.

I'm trying to make it so that the botplay text is replaced by something else via Psych Haxe but I've ran into a few problems while working on it. 
1.  It's saying that FlxTextBorderStyle is an "Unknown variable"
![Screenshot 2024-08-14 6 20 29 PM](https://github.com/user-attachments/assets/5a43b750-7ad9-4c32-8892-446043da94ab)
2. Whilst trying to make another botplaytxt variable, I attempted to remove the old one via haxe but it doesn't work at all. It leaves both text on top of each other.
![Screenshot 2024-08-14 6 21 51 PM](https://github.com/user-attachments/assets/1218e4e6-0c05-41da-b4a2-cd3a6555a1a5)
![Screenshot 2024-08-14 6 23 25 PM](https://github.com/user-attachments/assets/45e893b2-bdcd-4922-9a9f-dccbd37997c4)
3. Continuing from problem two, I also tried setting the string for potplaytext to blank but it still shows up. I even tried setting the visibility to false and it still appears. 
![Screenshot 2024-08-14 6 25 26 PM](https://github.com/user-attachments/assets/10be92f3-1032-4329-ba0b-a81f24a84e7d)

Also the secondary botplaytxt doesn't work when you toggle it in the pause-menu but it works via gameplay changer.

If anyone knows how to fix this please explain what I did wrong.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

Tried adding a Haxe script, didn't go so well.

**Comment by MaksPRO12667** [comment]
I don't know what you're talking about, but in my opinion, to change the text in the botplay, it's enough to write:
function onCreatePost()
setTextString("botplayTxt", "yourcoolfuckingtext");
end

(I hope the lua version of windows and linux are the same)

**Comment by xxyuee** [comment]
for 1), import FlxTextBorderStyle
and for 2-3, use game.(variable) when editing anything from PlayState.

**Comment by Sonicgamer2000** [comment]
I'm not sure this is supposed to happen
I tried importing but it says it doesn't know what flixel is, basically saying that flixel is unexpected.
![Screenshot 2024-08-15 6 21 57 PM](https://github.com/user-attachments/assets/f655508c-580f-4553-b44f-8357bbfa5feb)

**Comment by Sonicgamer2000** [comment]
> for 1), import FlxTextBorderStyle and for 2-3, use game.(variable) when editing anything from PlayState.

trying to use "import FlxTextBorderStyle" results in it not functioning at all. It just says unexpected flixel which isn't supposed to happen.

**Comment by Sonicgamer2000** [comment]
Also this happens when I put it in function onCreatePost
![Screenshot 2024-08-15 6 39 12 PM](https://github.com/user-attachments/assets/85793bf3-1c57-4196-87f3-c5f1a5b149f2)

**Comment by Sonicgamer2000** [comment]
Alright found the problem. Marking this as closed now.
