### ISSUE TITLE
SUPER COOL CAMERA EVENTS!!!!

### ISSUE THREAD

**Issue by AlexTheGuy73** [ShadowMario/FNF-PsychEngine#15301]
### What feature do you want to get added on the **base** engine?

i got this idea when i was pooping lol
THE... FOCUS CAMERA EVENTS!!!
i mean the focus camera events like: out, in, expoOut, elasticIn, etc.
PLEASEEEE ADD ALL THE ZOOMING CAMERA EFFECTS FOR MAKE COOL TRANSITIONS :DDD
or serious moments lol
i dont know how the modders make that camera movements, like in the first song of the peanuts mod (snoopy mod)_

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by FuseIsHere813** [comment]
1. Congrats! You failed the test.

**Comment by FuseIsHere813** [comment]
Congrats!

You failed the test.

**Comment by Swapper1** [comment]
What kind of stupid feature is this? This is Psych Engine, not V-Slice stuff.

**Comment by ShadowMario** [comment]
You can do that with a custom event if you need it
