### ISSUE TITLE
Extra Values For Events

### ISSUE THREAD

**Issue by AnotherPlayer8** [ShadowMario/FNF-PsychEngine#15309]
### What feature do you want to get added on the **base** engine?

I feel like in some cases, only 2 values aren't enough, so maybe you could make it up to 4 or 5 values

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
Ain't happening because it would require reworking what I've finished already
