### ISSUE TITLE
can i use winndows 11?

### ISSUE THREAD

**Issue by taggytheargperson** [ShadowMario/FNF-PsychEngine#15312]
### What is your question?

can i

**Comment by SamuXDD** [comment]
si

**Comment by CrusherNotDrip** [comment]
no you have to use windows 14

**Comment by MaksPRO12667** [comment]
No, you have to use PlayStation 1

**Comment by Gabopogi01** [comment]
idk but maybe yes

**Comment by taggytheargperson** [comment]
so was the answer ever yes or...

**Comment by MaksPRO12667** [comment]
> so was the answer ever yes or...

You won't be able to believe it and you will be in a complete state of shock that your chair or armchair will shake, but yes... You can use windows 11

**Comment by taggytheargperson** [comment]
> > so was the answer ever yes or...
> 
> You won't be able to believe it and you will be in a complete state of shock that your chair or armchair will shake, but yes... You can use windows 11

my god! YAY

**Comment by CrusherNotDrip** [comment]
> > so was the answer ever yes or...
> 
> You won't be able to believe it and you will be in a complete state of shock that your chair or armchair will shake, but yes... You can use windows 11

MY CHAIR IS SHAKING RIUGHT NOW

**Comment by MaksPRO12667** [comment]
> > > so was the answer ever yes or...
> > 
> > 
> > You won't be able to believe it and you will be in a complete state of shock that your chair or armchair will shake, but yes... You can use windows 11
> 
> MY CHAIR IS SHAKING RIUGHT NOW

holy fuck... Scotch tape will help you
you need to stick with tape your chair to the floor! It helped me

**Comment by MaksPRO12667** [comment]
> > > so was the answer ever yes or...
> > 
> > 
> > You won't be able to believe it and you will be in a complete state of shock that your chair or armchair will shake, but yes... You can use windows 11
> 
> my god! YAY

ohh.. this bro is so happy, as if it is his **the best day ever**
