### ISSUE TITLE
this happens

### ISSUE THREAD

**Issue by BambiGaming2022** [ShadowMario/FNF-PsychEngine#15310]
### Describe your bug here.

C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 322)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 145)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 117)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 90)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
StageData.hx (line 91)
StageData.hx (line 63)
Song.hx (line 133)
FreeplayState.hx (line 371)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid number at position 144: 03
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

i used 0.6.3 and put WELL DONE mid effort mod and this happens

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i didn't edit anything

**Comment by BambiGaming2022** [comment]
what does that means?

**Comment by Stefan2008Git** [comment]
> what does that means?

That means the stageName.json file is probably having a unexpected position

**Comment by FuseIsHere813** [comment]
0.6.3 isn't supported anymore

**Comment by BambiGaming2022** [comment]
> 0.6.3 isn't supported anymore

thanks for telling me that but i already know it
