### ISSUE TITLE
Playtesting Smash in the chart editor crashes the game

### ISSUE THREAD

**Issue by GingyMobile** [ShadowMario/FNF-PsychEngine#15313]
### Describe your bug here.

I was testing the new chart editor and loaded up Smash and after i playtested it in the chart editor, the game crashed
![image_2024-08-15_151619098](https://github.com/user-attachments/assets/7b864c43-f4b1-420b-aba8-e42cd4cd0bc1)

### Command Prompt/Terminal logs (if existing)

```bash
Null Object Reference
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I changed project.xml to include base game files, secrets, and videos

**Comment by ShadowMario** [comment]
You need to add the .ogg file separately, I didn't because it's copyrighted material
https://www.youtube.com/watch?v=4rK0t4tScxc
