### ISSUE TITLE
My game crashes when i open freeplay and story

### ISSUE THREAD

**Issue by ChrisIsGood1000** [ShadowMario/FNF-PsychEngine#15319]
### Describe your problem here.

all i did was add a character in thats it and delete the front part of my bg (shuck front)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i edited the characters and added a gf sprite in, i didnt save it tho, i deleted (shuckfront) from the bg

**Comment by ChrisIsGood1000** [comment]
oh and also it says null object reference

**Comment by Gabopogi01** [comment]
maybe a week.json is not there. me if i off the mod and freeplay then my game crashes

**Comment by ChrisIsGood1000** [comment]
> maybe a week.json is not there. me if i off the mod and freeplay then my game crashes

there is a week file tho

**Comment by SantiagoCalebe** [comment]
the game can't load if isn't a week.json file in the PsychEngine/assets/shared/weeks or PsychEngine/Mods/Weeks

try to create a week and see what happens.

**Comment by ISamwise4** [comment]
I'm having the same problem and it doesn't work still

**Comment by SantiagoCalebe** [comment]
> I'm having the same problem and it doesn't work still

then idk what to do, what version are you using?
