### ISSUE TITLE
Engine Auto-Updating

### ISSUE THREAD

**Issue by WolfyTail** [ShadowMario/FNF-PsychEngine#15314]
### What feature do you want to get added on the **base** engine?

It may sound dumb, but Psych Engine includes an OutdatedState that sends the player to the engine's github. Wouldn't it be better if the new files from the newest update were directly installed into the game folder?

It shouldn't be that hard, I mean, I kinda replicated that system on my mod.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
This is not necessary as Psych Engine will stop updating soon
