### ISSUE TITLE
Debug Key #3 (QOL Feature)

### ISSUE THREAD

**Issue by ClicheAveri** [ShadowMario/FNF-PsychEngine#15329]
### What feature do you want to get added on the **base** engine?

Maybe it is a little too late to ask for this, but it would be a nice QOL feature to have the Stage Editor have it's own configurable key.

I think it should be turned off by default, but having the option for those who need it to rebind it in settings.
![fdgdfhgf](https://github.com/user-attachments/assets/5434db8a-0901-4f42-9012-d7bb3a91e483)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by WolfyTail** [comment]
They said that thay won't be creating a stage editor for PE. If you are capable to create it, good luck. Also, you can add new keybinds by adding them on the controla file.

**Comment by ClicheAveri** [comment]
This feature request was for the pre-release build of Psych Engine, which DOES add a stage editor.

Thanks for the tip anyways.
