### ISSUE TITLE
Chart issues (1 of 2 for my responses here)

### ISSUE THREAD

**Issue by RachRach696** [ShadowMario/FNF-PsychEngine#15325]
### Describe your bug here.

Ok, so when I tested out some 0.7.3 charts in the experimental build, there were issues with the notes, it kept saying null object reference even though the chart was working fine, and also, when there is a GF section, the main enemy sings instead of the GF, could you fix that issue?
![Screenshot 2024-08-16 195309](https://github.com/user-attachments/assets/3035ef12-130b-4849-a370-fe61d464ad8d)

![Screenshot 2024-08-16 195035](https://github.com/user-attachments/assets/1ce74f04-72e4-4bc2-bf7c-44667aefc7a5)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not, I just popped some 0.7.3 charts into my build in the mods folder

**Comment by ShadowMario** [comment]
Is this an HScript error? If so, the HScript library I use has been reverted temporarily because of an issue, which might have caused this

**Comment by RachRach696** [comment]
I don't know, it may be (Not too familiar with coding)

**Comment by ShadowMario** [comment]
stale
