### ISSUE TITLE
Help with changing the main menu screen keybinds

### ISSUE THREAD

**Issue by Nice-Sky** [ShadowMario/FNF-PsychEngine#15324]
### What is your question?

Hello, I want to change the keybinds for the main menu since I'm trying to create a clone of the Undertale menu. So far, all I've done is change the sprites of the menu into position. Instead of pressing up and down to navigate the menu, I want to be able to press left or right to do so.

**Comment by Nice-Sky** [comment]
Btw, this is in source code

**Comment by CrusherNotDrip** [comment]
```haxe
if (controls.UI_UP_P)
	changeItem(-1);

if (controls.UI_DOWN_P)
	changeItem(1);
```

should be

```haxe
if (controls.UI_LEFT_P)
	changeItem(-1);

if (controls.UI_RIGHT_P)
	changeItem(1);
```

**Comment by Nice-Sky** [comment]
welp that makes me feel stupid, thank you very much
