### ISSUE TITLE
Black Sky In WeekEnd 1

### ISSUE THREAD

**Issue by IPepperMintZ** [ShadowMario/FNF-PsychEngine#15321]
### Describe your bug here.

In The Latest Action, The Sky Is Black In WeekEND 1 
![image](https://github.com/user-attachments/assets/57192620-65fa-427a-bda3-a73d318fff7d)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
Low Quality is turned on
