### ISSUE TITLE
Warning: Ignoring unknown fps=""

### ISSUE THREAD

**Issue by Impulse101f** [ShadowMario/FNF-PsychEngine#15323]
### Describe your bug here.

Having an issue when i'm compiling, whenever i try using lime test windows, it just writes "Warning: Ignoring unknown fps="" then does nothing for a good 2 minutes and gives me the prompt back.
This is the newest version, just downloaded it, already ran setup-windows.bat, installed all the needed libraries,
Any idea on how to fix this?

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\blank\Documents\FNF psych engine>lime test windows
Warning: Ignoring unknown fps=""

C:\Users\blank\Documents\FNF psych engine>
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, fresh install.

**Comment by FuseIsHere813** [comment]
"Ignoring unknown fps" is normal, but I really don't understand why lime isn't doing much when compiling

**Comment by megalives717** [comment]
how to fix it?
