### ISSUE TITLE
Texture for stages are not working 

### ISSUE THREAD

**Issue by EddyEddyEd** [ShadowMario/FNF-PsychEngine#1533]
### Describe your bug here.

I did 2 stages, and both worked but after these 2 it simply doenst work anymore  :(
![Desktop Screenshot 2021 11 30 - 17 09 51 40](https://user-images.githubusercontent.com/94937926/144120818-22f73500-0ab0-48d0-a3fe-bb9baa5d8a5e.png)

![Desktop Screenshot 2021 11 30 - 17 12 33 01](https://user-images.githubusercontent.com/94937926/144120838-1fc917f7-c345-4a72-bba0-1548e8c5be7a.png)
![Desktop Screenshot 2021 11 30 - 16 36 24 68](https://user-images.githubusercontent.com/94937926/144120846-d4811bbd-36a4-43b2-9184-4282943dc791.png)

praca and quarto are the ones that are working

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

added stages, changes in the credits and changes to the GUI

**Comment by MayoALT** [comment]
in preload/stages make a copy of the stage.json and rename it to your stage name and set the directory to whatever folder you want it in (leave it blank for it to be in shared)

**Comment by EddyEddyEd** [comment]
since the directory is for week 6 because I wanted to use the pixel notes and stuff, I placed the stage in the week 6 folder and it still didnt work. I dont think u read it all but, I've done this before and it worked, I just dont know why, after doing the exact same process, it just doesnt work anymore

**Comment by EddyEddyEd** [comment]
pls help :(

**Comment by ShadowMario** [comment]
You don't need to move to week 6 folder for the pixel hud to work.
