### ISSUE TITLE
fnf psychengine

### ISSUE THREAD

**Issue by fredbear123456** [ShadowMario/FNF-PsychEngine#15339]
### Describe your bug here.

flixel/graphics/frames/FlxAtlasFrames.hx (line 256)
states/MainMenuState.hx (line 50)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

mainmenustate.hx

**Comment by SantiagoCalebe** [comment]
I didn't understand your problem.

What were you trying to do?
