### ISSUE TITLE
Videos reset volume in Volume Mixer.

### ISSUE THREAD

**Issue by ThatRozebudDude** [ShadowMario/FNF-PsychEngine#15330]
### Describe your bug here.

When a video is played it resets the programs volume in the Volume Mixer. It also changes the program's name in the Volume Mixer. While the video is playing you can't change the program's volume in the Volume Mixer as it will automatically be set to max after tabbing back in to the program. After the video plays the volume goes back to how it was before but the Volume Mixer isn't updated and keeps the same name and volume level. If you manually move the volume slider back up to where it was when the video was playing it will get louder so the volume slider not going back is just a visual thing.
Before playing the video: ![image](https://github.com/user-attachments/assets/e686cd77-c738-40f7-b21b-8ab48699c1e3) After playing the video: ![image](https://github.com/user-attachments/assets/589459ce-66d4-4350-a15b-eb864c33c684)
This is in the new 1.0 pre-release. Probably related to changing to hxvlc. I tested this on Weekend 1 and it happens in every video cutscene.

AFTER FURTHER TESTING I have found that the program's volume gets set to the in-game volume while a video is playing. So if you had the in-game volume at max the program's volume would be set at max while the video is playing and if you have the volume set really low the program's volume would be set really low. It's basically assuming that the user will always have their volume at max in the mixer and the volume will only be set by using the in-game volume setting and not the mixer.

### What is your build target?

Windows

**Comment by tposejank** [comment]
Stop using goofy ahh old Volume Mixer. The program changes because hxvlc uses .DLLs and those interfere with the window

**Comment by tposejank** [comment]
> Stop using goofy ahh old Volume Mixer. The program changes because hxvlc uses .DLLs and those interfere with the window

This issue isn't possible to fix, it's up to MAJigsaw (Creator of hxvlc) or if in 0.7.3 hxCodec's creator

**Comment by ShadowMario** [comment]
> This issue isn't possible to fix, it's up to MAJigsaw (Creator of hxvlc) or if in 0.7.3 hxCodec's creator

If it's not something I can fix, will have to close the issue then.
