### ISSUE TITLE
Psych Engine 1.0 Prerelease Bug

### ISSUE THREAD

**Issue by obscuryth** [ShadowMario/FNF-PsychEngine#15335]
### Describe your bug here.

Opening the Story Menu after compiling the Source Code crashes the game with the following error.

### Command Prompt/Terminal logs (if existing)

```bash
states/StoryMenuState.hx (line 199)
flixel/FlxState.hx (line 239)
flixel/FlxGame.hx (line 749)
flixel/FlxGame.hx (line 679)
flixel/FlxGame.hx (line 558)
openfl/events/EventsDispatcher.hx (line 426)
openfl/display/DisplayObject.hx (line 1398)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No. It's a fresh compilation of the 1.0 prerelease Source Code.

**Comment by ShadowMario** [comment]
You have to add weeks for it to work
