### ISSUE TITLE
Black BG

### ISSUE THREAD

**Issue by goobera** [ShadowMario/FNF-PsychEngine#15334]
### Describe your problem here.

every custom background i add don't work it just turns black

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i added the custom BG

**Comment by Circuitella** [comment]
lua wasnt updated, most likely cause, for now stick to Half-Life 17 and other pure H-Script Mods
