### ISSUE TITLE
Botplay Message Under Notes

### ISSUE THREAD

**Issue by Memelord111** [ShadowMario/FNF-PsychEngine#15341]
### Describe your bug here.

So With The New 1.0 Prerelease Im Assuming Since The Hud Goes Behind the notes now that also went with botplay message accidently

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
Fixed this on the latest commit 👍
