### ISSUE TITLE
fnf psychengine

### ISSUE THREAD

**Issue by fredbear123456** [ShadowMario/FNF-PsychEngine#15349]
### Describe your bug here.

flixel/graphics/frames/FlxAtlasFrames.hx (line 253)
objects/MenuCharacter.hx (line 77)
states/StoryMenuState.hx (line 461)
states/StoryMenuState.hx (line 449)
states/StoryMenuState.hx (line 242)
flixel/FlxState.hx (line 239)
flixel/FlxGame.hx (line 749)
flixel/FlxGame.hx (line 679)
flixel/FlxGame.hx (line 558)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference

### Command Prompt/Terminal logs (if existing)

```bash
source
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by liamp0924** [comment]
there most likely something wrong with your menu characters \ difficulties
