### ISSUE TITLE
Trying to figure out how this stupid checkFileExists thing works

### ISSUE THREAD

**Issue by iampauleps** [ShadowMario/FNF-PsychEngine#15340]
### Describe your problem here.

For some reason the damm thing always comes up as true
I don't really know how to describe it
I'll just place some screenshots and pray someone can help

![fuckthis1](https://github.com/user-attachments/assets/8d018ec0-3383-4c8f-9a87-f85d1a312cc3)
![fuckthis2](https://github.com/user-attachments/assets/c934c2a6-8ee1-472d-89f9-1e40148d6b04)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope base psych

**Comment by Thiago821** [comment]
`if checkFileExists ('locationhere') then`
