### ISSUE TITLE
The Stage Assets wont load

### ISSUE THREAD

**Issue by KxleyStudios** [ShadowMario/FNF-PsychEngine#15343]
### Describe your bug here.

The stage assets wont load in the latest release.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by FuseIsHere813** [comment]
need to provide more information / SS for how this is happening

**Comment by ShadowMario** [comment]
Need more information on your problem.

**Comment by ShadowMario** [comment]
Stale.
