### ISSUE TITLE
Removing the game's intro

### ISSUE THREAD

**Issue by Nice-Sky** [ShadowMario/FNF-PsychEngine#15344]
### What is your question?

how can i remove the intro (the whole text thingy) that plays before the title screen

**Comment by potatex2** [comment]
In the
```hx
override function stepHit() {
  super.stepHit();
    if(!closedState) {
	introStep++;
	switch (introStep) {
            ...
            case whatever:
              	skipIntro();
```
remove any text functions and keep the FlxG.sound and skipIntro() functions, you can change the step number for the switch-case

**Comment by Nice-Sky** [comment]
im not sure ik how to do that
