### ISSUE TITLE
Compiled version of engine crashing due to "There is not asset library with an ID of "song""

### ISSUE THREAD

**Issue by iampauleps** [ShadowMario/FNF-PsychEngine#15348]
### Describe your problem here.

Whenever i try to launch the game it just gives me that error. I've been able to recreate it on the precompiled version via removing the manifest. But it's in the folder in the version i compiled and it's just ignoring this. I have no idea what's causing this can you please help me (and please for the love of god don't ignore this)

![Screenshot_52](https://github.com/user-attachments/assets/1c3d5ad8-616d-42e7-bff8-b3218970e471)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Removed the stuff that made the loading screen not appear and also tried to make it an animated sprite. Changed window icons. Changed the window name. Also Changed that company name thing

**Comment by ShadowMario** [comment]
Put it in C:/Program Files/ and if needed, run as administrator aswell

**Comment by iampauleps** [comment]
> n

uhhhhhh
Put what extactly?
The compiled mod?

**Comment by iampauleps** [comment]
> Put it in C:/Program Files/ and if needed, run as administrator aswell

This has caused a different problem of it just closing immediately closing upon opening even when running as administrator

Also the whole "how am i gonna to release this mod if that happens" issue
