### ISSUE TITLE
Making it so you can have an actual loading screen

### ISSUE THREAD

**Issue by iampauleps** [ShadowMario/FNF-PsychEngine#15356]
### What feature do you want to get added on the **base** engine?

Making it so you can have an actual loading screen for whatever mod you're making. Doing it via lua is impossible cause theres a different between a loading screen and a png that flashs up for a couple of seconds and preloads nothing. And doing it via source is a nightmare with how much of a nightmare working with it is. I don't care how. Just please make it so it's not this softlocky mess

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CrusherNotDrip** [comment]
there is a loading screen
but 1.0 isn't out yet

**Comment by crowplexus** [comment]
there is one, it will come with the next release

https://github.com/user-attachments/assets/a66996da-4516-4fcd-b4b3-7bf435d452fa
