### ISSUE TITLE
(Experimental Branch) Selecting an image in the stage editor breaks when the path contains a period 

### ISSUE THREAD

**Issue by silkycell** [ShadowMario/FNF-PsychEngine#15350]
### Describe your bug here.

When selecting an image from the stage editor, if your path has a period in it (in my case, C:\Users\user\Documents\.Games\FNF\PsychEngine Pre-Release\mods\red lobster\images\ena) it will incorrectly trim the path to where the period is.

When inside of a path with a period:
![image](https://github.com/user-attachments/assets/680f07d8-8db7-4882-ad11-89354ee73d6b)

When not in a path with a period (In this case, I moved the build to my desktop):
![image](https://github.com/user-attachments/assets/9f68065d-e9a5-4884-a7fc-6a07f9ac5dcf)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No (It wont let me make this part blank)

**Comment by ShadowMario** [comment]
Fixed on the latest commit
