### ISSUE TITLE
1.0 compiling error

### ISSUE THREAD

**Issue by bf244** [ShadowMario/FNF-PsychEngine#15355]
### Describe your problem here.

![image](https://github.com/user-attachments/assets/b798e611-b315-449d-a0be-b15b3f9ea4f1)
any ideas of what this is caused?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i did not

**Comment by LillianaPresent** [comment]
Did you figure this out?
