### ISSUE TITLE
how to use shader setShaderArray using lua or source

### ISSUE THREAD

**Issue by nguyenkiet1234d** [ShadowMario/FNF-PsychEngine#15352]
### Describe your problem here.

 i want to use shader array using lua or source but i don't know how to make it work i used lua as setShaderArray but it doesn't work please help 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by Cyachao** [comment]
`setShaderFloatArray`/`someshader.setFloatArray`is mostly used to edit `vec2`, `vec3` and etc vectors 
`setShaderFloatArray('spriteTag', 'uniformname', {values})`
in source it's like `someshader.setFloatArray('uniformname', [somevalue, othervalue]);`

**Comment by nguyenkiet1234d** [comment]
thankkkkk
