### ISSUE TITLE
Cyrillic doesn't show up in Story Mode

### ISSUE THREAD

**Issue by Novikond** [ShadowMario/FNF-PsychEngine#15353]
### Describe your bug here.

Working on Russian localization, Cyrillic doesn't appear in story mode
Problem is not with the font, I tried several of them, problem remains

Issue: Text on score text, option descriptions etc etc works, it is displayed as intended. But on week score and story names, it doesn't. Instead it shows a blank space. If I put English letters in there, it shows up as it should.

All the translation keys that have this issue:
- week_score
- storyname_tutorial
- storyname_week1
- storyname_week2
- storyname_week3
- storyname_week4
- storyname_week5
- storyname_week6
- storyname_week7
- storyname_weekend1

In the first screenshot I put some English letters with Russian, you can see the gap, this gap is Cyrillic. In the second screenshot it's just Cyrillic. I'll also attach the font I used, it's a normal vcr font but with the addition of Cyrillic characters.

(Tested on 1.0 Pre-Release and 1.0 Action builds)

Screenshot 1. week_score: "notice the space >СЧЕТ УРОВНЯ: {1}"
Screenshot 2. week_score: "СЧЕТ УРОВНЯ: {1}"
Font (rename to vcr.ttf): https://files.catbox.moe/5uzdyw.ttf

![image](https://github.com/user-attachments/assets/ee4abdbb-076f-4015-b7b9-7d2df315ebc6)
![image1](https://github.com/user-attachments/assets/987bbf35-14c3-41a1-b9cc-05fbd87187e7)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No changes were made

**Comment by crowplexus** [comment]
to make it clear, it doesn't work because the game doesn't look for mod fonts and instead uses hardcoded ones, this should be fixed when my pr gets completed and merged
