### ISSUE TITLE
Multiple Spritesheet for a character 

### ISSUE THREAD

**Issue by JuanSebas1247** [ShadowMario/FNF-PsychEngine#15364]
### What is your question?

I want to use multiple Spritesheet For a character in PsychEngine 1.0, how can I do that?

Please :(

**Comment by CrusherNotDrip** [comment]
I think you have to do it like this
![image](https://github.com/user-attachments/assets/9bb6fc4c-f083-4709-b243-07581759cb15)

**Comment by crowplexus** [comment]
close issue
