### ISSUE TITLE
yes, its me again.... im sorry for requesting soo much, but this is important for the new mods

### ISSUE THREAD

**Issue by AlexTheGuy73** [ShadowMario/FNF-PsychEngine#15369]
### What feature do you want to get added on the **base** engine?

this is the thing.
in the 1.0 update i was soooooooo exited for play, BUT.. i needed a change stage event
and i didnt find any events for that on gamebanana, please, if you will make a hotfix or something add that event
DO IT FOR THE COMMUNITY :D
pleaaaseeeeee shadow mario
i love this engine

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
Duplicate of other rejected posts.

**Comment by AlexTheGuy73** [comment]
im never requesting again 💀
