### ISSUE TITLE
v1.0-pre small problems

### ISSUE THREAD

**Issue by M4st3rG4m4** [ShadowMario/FNF-PsychEngine#15362]
### Describe your bug here.

I'm just going to highlight two issues that appeared in prerelease that didn't exist in 0.7.3.

1 - SScript Problems:

-The main problem with the SScript is that now you cannot call runHaxeCode in onUpdate / onUpdatePost / goodNoteHit / goodNoteHitPre when in 0.7.3 there were no problems with this, Plus it doesn't show crash-handler but instead the engine freezes and crashes.

2- HScript Problems:

-With hscript the only problem is that doing anything in goodNoteHit / goodNoteHitPre freezes and crashes the engine without a crash-handler, Also for some reason now you can't call onUpdate / onUpdatePost without elapsed, otherwise the script will not work and the engine will spam the debugText "Too Many Arguments".

These small problems really affect backward compatibility with 0.7.3 scripts, breaking many of them since most are based on SScript

btw there is a little lag when spawning note splash for the first time for each different note splash in the engine, whether the default / pixel or some mod, if it is the first time that a note splash different from the previous one is used, that little lag appears (actually this problem comes from 0.7 but it is strange that it has not been solved yet).

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by crowplexus** [comment]
we're working to fix these before 1.0 releases, by the time it does, most 0.7.3 scripts should work again with the addition of new features, if you have any requests, just head over to the [HScript Iris](https://github.com/crowplexus/hscript-iris/) since that's the thing currently being used for hscript in psych

**Comment by M4st3rG4m4** [comment]
> we're working to fix these before 1.0 releases, by the time it does, most 0.7.3 scripts should work again with the addition of new features, if you have any requests, just head over to the [HScript Iris](https://github.com/crowplexus/hscript-iris/) since that's the thing currently being used for hscript in psych

Ty I just wanted to let you know that, and sorry for the delay.
