### ISSUE TITLE
How to make visible true or false for FlxSprite in source code

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#15367]
### Describe your problem here.

Yes, this is a stupid question, but I did not find normal tutorials on source code

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by FuseIsHere813** [comment]
`spr.alpha = 0` = false
`spr.alpha = 1` = true

**Comment by MaksPRO12667** [comment]
> spr.alpha = 0



> `spr.alpha = 0` = false `spr.alpha = 1` = true

thank you very much
