### ISSUE TITLE
"Character Change" event not working.

### ISSUE THREAD

**Issue by NesDoesGithub** [ShadowMario/FNF-PsychEngine#1536]
### Describe your bug here.

I am currently making a Sonic.EXE Psych Engine port, and I am currently trying to change characters mid-song.
The character change from "bf" to "bfprespective" works just fine, while "tailsexe" to "beast" does not work.
(Yes I am using the 0-2 system)
![fdhfdhuidfiuhdfsuih](https://user-images.githubusercontent.com/95316430/144128657-af6ce1d1-443f-4e5b-aea4-3af7ca3ef99d.png)

Here's what it looks like after the event.
![jbhfdsjhfdskfdjskh](https://user-images.githubusercontent.com/95316430/144129208-74bb92dd-5106-48ae-b75e-90c0b54948f7.png)

### Command Prompt/Terminal logs (if existing)

```bash
Nothing.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not change anything.

**Comment by KutikiPlayz** [comment]
Did you happen to misspell anything?
idk what else it could be

**Comment by NotEpik** [comment]
> ### Describe your bug here.
> I am currently making a Sonic.EXE Psych Engine port, and I am currently trying to change characters mid-song. The character change from "bf" to "bfprespective" works just fine, while "tailsexe" to "beast" does not work. (Yes I am using the 0-2 system) ![fdhfdhuidfiuhdfsuih](https://user-images.githubusercontent.com/95316430/144128657-af6ce1d1-443f-4e5b-aea4-3af7ca3ef99d.png)
> 
> Here's what it looks like after the event. ![jbhfdsjhfdskfdjskh](https://user-images.githubusercontent.com/95316430/144129208-74bb92dd-5106-48ae-b75e-90c0b54948f7.png)
> 
> ### Command Prompt/Terminal logs (if existing)
> ```shell
> Nothing.
> ```
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> I did not change anything.

```
Event: Change Character (106849 ms)
Value 1: 
Value 2: bfprespective
Event:      (106952 ms)
Value 1: 1
Value 2: beat
```
me: why is that event type is empty make sure it "Change Character" even bruh

**Comment by NesDoesGithub** [comment]
> > ### Describe your bug here.
> > I am currently making a Sonic.EXE Psych Engine port, and I am currently trying to change characters mid-song. The character change from "bf" to "bfprespective" works just fine, while "tailsexe" to "beast" does not work. (Yes I am using the 0-2 system) ![fdhfdhuidfiuhdfsuih](https://user-images.githubusercontent.com/95316430/144128657-af6ce1d1-443f-4e5b-aea4-3af7ca3ef99d.png)
> > Here's what it looks like after the event. ![jbhfdsjhfdskfdjskh](https://user-images.githubusercontent.com/95316430/144129208-74bb92dd-5106-48ae-b75e-90c0b54948f7.png)
> > ### Command Prompt/Terminal logs (if existing)
> > ```shell
> > Nothing.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Are you modding a build from source or with Lua?
> > Source
> > ### What is your build target?
> > Windows
> > ### Did you edit anything in this build? If so, mention or summarize your changes.
> > I did not change anything.
> 
> ```
> Event: Change Character (106849 ms)
> Value 1: 
> Value 2: bfprespective
> Event:      (106952 ms)
> Value 1: 1
> Value 2: beast
> ```
> 
> me: why is that event type is empty make sure it "Change Character" event bruh

i am legit stupid ;-; im sorry for wasting your time ;-;
