### ISSUE TITLE
1.0 pre problem SScript

### ISSUE THREAD

**Issue by GoShadowS** [ShadowMario/FNF-PsychEngine#15363]
### Describe your problem here.

[30;41m ERROR [0m C:/HaxeToolkit/haxe/lib/SScript/19,0,618/src/macro/Macro.hx:10: characters 96-100

 10 | [2m  Context.fatalError('SScript is not available, thanks to everyone for their support.', (macro [0m[1mnull[0m[2m).pos);[0m
    |                                                                                                [31m^^^^[0m
    | SScript is not available, thanks to everyone for their support.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by crowplexus** [comment]
fixed, use latest branch https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental

**Comment by GoShadowS** [comment]
thanks
