### ISSUE TITLE
some error thing on someone's mod

### ISSUE THREAD

**Issue by Pavern7** [ShadowMario/FNF-PsychEngine#15371]
### Describe your bug here.

states/TitleState.hx (line 125)
states/TitleState.hx (line 100)
flixel/util/FlxTimer.hx (line 230)
flixel/util/FlxTimer.hx (line 320)
flixel/FlxGame.hx (line 748)
flixel/FlxGame.hx (line 680)
flixel/FlxGame.hx (line 559)
openfl/events/EventDispatcher.hx (line 426)
openfl/display/DisplayObject.hx (line 1398)

Uncaught Error: Null Object Reference

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no. just putting some scripts

**Comment by Cyachao** [comment]
would you mind telling me what version it is
can't help you otherwise

**Comment by Pavern7** [comment]
0.7.3 sorry the problem fixed because i delete the save file
