### ISSUE TITLE
Stage change (EVENT)

### ISSUE THREAD

**Issue by AlexTheGuy73** [ShadowMario/FNF-PsychEngine#15379]
### What feature do you want to get added on the **base** engine?

Im making a obituary cover and i cant change the bg on the exe part bc i need a change bg event
And since Psych Engine changed its way of doing stages (from putting a .lua and a json, to just a json) I can't change the stage anymore, so could you add an event to change the background in the middle of the song, please?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by PaodeMelYTBR** [comment]
I'm having this problem too lol

**Comment by PDL2CGamejolt** [comment]
Can you please stop requesting this? This is prolly why he's been ignoring it.

**Comment by ADA-Funni** [comment]
The method to access stage objects is `game.getLuaObject('objName')` in HScript, and `'objName'` in Lua.

**Comment by ShadowMario** [comment]
Duplicate of a bunch of other posts.
