### ISSUE TITLE
Ideas (Part 2 of 2)

### ISSUE THREAD

**Issue by RachRach696** [ShadowMario/FNF-PsychEngine#15373]
### What feature do you want to get added on the **base** engine?

Ok, so I was wondering if you could add some features

**_Difficulty Exclusive instrumental and voices:_** This will not replace adding a different song for a difficulty, but a new feature, it would work with erect remixes, obviously (Example: Voices-Opponent-Easy, Voices-Player-Easy, Inst-Easy), if it is the basic files (Inst, Voices-Player, Voices-Opponent), it will be for all difficulties, so no matter the difficulty, they will all have the same audio file

**_Difficulty Exclusive events:_** This would be really good for a hypothetical Challeng-EDD Psych port, so you will not need to bake the events into the chart (you still can, my idea for psych will just be a more convenient alternative), like my voices and inst idea, if there is no -(difficulty name) at the end of your events .JSON, it will affect every difficulty

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stop asking for stage editor y'all

**Comment by Lorekeeper49** [comment]
Both are already a thing;

For your first idea, you just need to go into the chart editor of the difficulty selected and change the song name, the file name might change but just rename the file to the right thing and place it in the right folder.

For your second idea, the events can just be in the chart file itself, it doesn't need to be a separate file

**Comment by ShadowMario** [comment]
Both are already possible.
