### ISSUE TITLE
Inst volume not saving

### ISSUE THREAD

**Issue by goobera** [ShadowMario/FNF-PsychEngine#15374]
### Describe your problem here.

Every time i save the Inst volume nothing works 
https://github.com/user-attachments/assets/e8eadd48-8abb-43d5-8133-689f86c366c3

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

**Comment by CrusherNotDrip** [comment]
I don't think it's supposed to save.
just a guess though and for once I'm not being sarcastic

**Comment by ShadowMario** [comment]
It is not supposed to save
