### ISSUE TITLE
Source error (0.6.3)

### ISSUE THREAD

**Issue by Your-Local-LordXSimp** [ShadowMario/FNF-PsychEngine#15375]
### Describe your problem here.

source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Cyachao** [comment]
you need to downgrade hxCodec to 2.5.1 with `haxelib set hxCodec 2.5.1`
