### ISSUE TITLE
Add feature to save charts in the format of legacy versions of psych

### ISSUE THREAD

**Issue by Judipie** [ShadowMario/FNF-PsychEngine#15388]
### What feature do you want to get added on the **base** engine?

Maybe add an extra save option that saves charts in the 0.7.3 format (maybe even 0.6.3)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
I purposely did not make this because people who still use 0.6.3 already gave me enough trouble for me to give them any support.
