### ISSUE TITLE
Character Editor black screen

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#15382]
### Describe your bug here.

I'm making a source code mod of Psych Engine and the Character Editor is mostly a black screen. only the UI elements remained. please help. Yes, I'm still using 0.7.3 even tho the 1.0 prerelease is out.
![Screenshot 2024-08-21 194501](https://github.com/user-attachments/assets/f5b46d48-dd4d-416c-96dd-5082141fcfb8)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes.

**Comment by PDL2CGamejolt** [comment]
oh nvm

**Comment by WoodsSilent05** [comment]
how did you fix it? my shit still broke lmao
