### ISSUE TITLE
source/psychlua/HScript.hx:317: characters 89-92 : Type not found : Tea

### ISSUE THREAD

**Issue by BLUE-GAMING** [ShadowMario/FNF-PsychEngine#15383]
### Describe your problem here.

i have this problem where i couldnt figure out how to stop the "Sscript is not available. thanks to everyone for their support.", so i used this sscript reupload: [https://github.com/SScript-Guy/SScript-new/](url), and when i tried running the build, the command prompt said source/psychlua/HScript.hx:317: characters 89-92 : Type not found : TeaCall.
So i looked through the solved issues, and saw to just replace teacall with tea, and i did, and now its giving me source/psychlua/HScript.hx:317: characters 89-92 : Type not found : Tea

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by BLUE-GAMING** [comment]
btw this is the .bat file error for my OS
![image_2024-08-21_213622363](https://github.com/user-attachments/assets/1625e24c-68cc-4262-9670-88a3ec7bda8e)

**Comment by BLUE-GAMING** [comment]
nvm gonna use experimental branch

**Comment by SyncGit12** [comment]
0.7.2 is for you

or 0.2.4 versions of FunkinCrew/Funkin
