### ISSUE TITLE
SScript no longer avaliable.

### ISSUE THREAD

**Issue by Saturday-Night-Sillyness** [ShadowMario/FNF-PsychEngine#15389]
### Describe your bug here.

I think SScript no longer will work. Is this good?

### Command Prompt/Terminal logs (if existing)

```bash
BUILDING GAME
C:/Users/emine/Documents/SATURDAY NIGHT SILLYNESS MOD SUPER IMPORTANT O MY GOD/Source Code/FNF-PsychEngine-0.7.3/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.

done.
Press any key to continue . . .
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No. I am trying to build source code to make sure nothing is broken.

**Comment by ziran-awa** [comment]
me too🥸

**Comment by crowplexus** [comment]
fixed, use latest https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental
