### ISSUE TITLE
Psych engine keeps crashing

### ISSUE THREAD

**Issue by mikuleek39** [ShadowMario/FNF-PsychEngine#15394]
### Describe your bug here.

It keeps crashing when i open up a mod song. I was trying to play Silly Stars (silly billy but all stars) and it crashed a few seconds later. Same with other mods

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

N/A

**Comment by FuseIsHere813** [comment]
delete the save/controls data (leave it in the bin for now) and see if that helps
