### ISSUE TITLE
The confirm animation for the up strumnote in pixel stages is different from the rest

### ISSUE THREAD

**Issue by kornelbut** [ShadowMario/FNF-PsychEngine#15398]
### Describe your bug here.

StrumNote.hx has the up arrow's confirm animation at 12 fps while the rest are at 24. This is also present in 1.0

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by crowplexus** [comment]
this is more of an oversight than a bug, all pixel note animation should be 12 fps
