### ISSUE TITLE
什么？大佬请帮帮我

### ISSUE THREAD

**Issue by ziran-awa** [ShadowMario/FNF-PsychEngine#15391]
### What is your question?

在编译的时候出现了：SScript is not available, thanks to everyone for their support.

**Comment by crowplexus** [comment]
already fixed, make sure to update

**Comment by ziran-awa** [comment]
> 已修复，请务必更新

怎么更新，我是小白

**Comment by crowplexus** [comment]
> 怎么更新，我是小白

if you're modifying source, you can use [this branch](https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental)

it is also highly recommended for you to run the setup script inside the `setup` folder, so you can have all the correct libraries installed

![image](https://github.com/user-attachments/assets/6f1d674f-96bf-4d09-85cb-dcf503d0a9c6)

**Comment by crowplexus** [comment]
请不要忘记在问题解决后关闭您的问题信息，谢谢您的耐心等待。
