### ISSUE TITLE
Mp4 cutscenes dont work

### ISSUE THREAD

**Issue by BL0KYBL0K** [ShadowMario/FNF-PsychEngine#154]
Maybe its just me but my mp4 cutscenes dont work it cant even build i get this error

source/Paths.hx:166: characters 32-37 : Duplicate class field declaration : Paths.video
source/StoryMenuState.hx:304: lines 304-307 : Void -> Void should be flixel.FlxState
source/StoryMenuState.hx:304: lines 304-307 : For function argument 'callback'

maybe i did something wrong but i dont know what

**Comment by BL0KYBL0K** [comment]
i messed around and now i only have two errors here they are   :


source/StoryMenuState.hx:305: lines 305-308 : Void -> Void should be flixel.FlxState
source/StoryMenuState.hx:305: lines 305-308 : For function argument 'callback'

**Comment by ShadowMario** [comment]
Aaaand... you didn't show any of the code at all

**Comment by BL0KYBL0K** [comment]
> Aaaand... you didn't show any of the code at all

 sorry here is the code
 
 
 			var isCutscene:Bool = false;


			if (curWeek == 3 && !isCutscene) // Checks if the current week is Tutorial.
			{
				video.playMP4(Paths.video('pico'), function()
				{
				FlxG.switchState(new PlayState());
				});
			
				isCutscene = true;
			}
			else
			{
				new FlxTimer().start(1, function(tmr:FlxTimer)
				{
					if (isCutscene)
						video.onVLCComplete();
			
					LoadingState.loadAndSwitchState(new PlayState(), true);
				});
			}

**Comment by BL0KYBL0K** [comment]
i tried with webm and that never worked either

**Comment by BL0KYBL0K** [comment]
> Aaaand... you didn't show any of the code at all

Are you gonna respond?

**Comment by ShadowMario** [comment]
> Are you gonna respond?

Chill, i don't have all time of the world for responding to Github issues.
That's not how you use MP4, just copy the way MP4 is used from PlayState's startVideo()

**Comment by BL0KYBL0K** [comment]
oh sorry

**Comment by BL0KYBL0K** [comment]
> > Are you gonna respond?
> 
> Chill, i don't have all time of the world for responding to Github issues.
> That's not how you use MP4, just copy the way MP4 is used from PlayState's startVideo()

like this
![image](https://user-images.githubusercontent.com/88749184/135012682-bc88acd7-e928-4ea6-9524-52c4e82b0eb1.png)
