### ISSUE TITLE
source/psychlua/HScript.hx:317: characters 89-92 : Type not found : Tea

### ISSUE THREAD

**Issue by joseplayer675** [ShadowMario/FNF-PsychEngine#15403]
### Describe your problem here.

I replaced TeaCall in the file with Tea, but now it doesn't work, can someone help me?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by crowplexus** [comment]
the main branch is not able to be compiled anymore, please use [experimental](https://github.com/ShadowMario/FNF-PsychEngine/tree/experimental)
