### ISSUE TITLE
Can't open the mod

### ISSUE THREAD

**Issue by TopSasha12435** [ShadowMario/FNF-PsychEngine#15408]
### Describe your bug here.

iam opening Hymns of Hallownest and getting: Uncaught error [file_open,modsList.txt]

### Command Prompt/Terminal logs (if existing)

```bash
C:HaxeToolkit\haxe\std/cpp\_std/sys/io/File.hx (line 59)
C:HaxeToolkit\haxe\std/cpp\_std/sys/io/File.hx (line 39)
backend/native/File.hx (line 34)
backend/Mods.hx (line 198)
states/MainMenuState.hx (line 42)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (1400)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
This mod seems to be wrongly configured, but you should be able to workaround this issue by creating a `modsList.txt` file in the same folder as the executable file
