### ISSUE TITLE
Russian Language

### ISSUE THREAD

**Issue by Kalail** [ShadowMario/FNF-PsychEngine#15402]
### What feature do you want to get added on the **base** engine?

![изображение_2024-08-23_234733392](https://github.com/user-attachments/assets/0d53d408-f154-4ec8-a721-ebb270f088c1)
![изображение_2024-08-23_234744186](https://github.com/user-attachments/assets/b1d0113b-b18e-4f6d-a864-08f2c85c31fd)
I've already started the translation, but I think it's worth adding this to the built-in Psych Engine

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by GoShadowS** [comment]
hi my russian friend blyat ya iskal tebya

**Comment by Kalail** [comment]
> hi my russian friend blyat ya iskal tebya

о привет

**Comment by GoShadowS** [comment]
@Kalail привет

**Comment by GoShadowS** [comment]
а ты выкладывать будешь я просто тоже сделала русский язык

**Comment by GoShadowS** [comment]
> а ты выкладывать будешь я просто тоже сделал русский язык

**Comment by MaksPRO12667** [comment]
Опа нихуя себе, любопытненько

**Comment by crowplexus** [comment]
new translations aren't gonna be added, American English and Brazilian Portuguese are the only 2 languages that will exist by default, and you can add more with mods

**Comment by MaksPRO12667** [comment]
> You can do that now with .lang files!

yeah but i can't make new symbols in alphabet.xml. Only source code can do this maybe (Or maybe cyrillic doesn't work)
