### ISSUE TITLE
什么？

### ISSUE THREAD

**Issue by ziran-awa** [ShadowMario/FNF-PsychEngine#15401]
### Describe your problem here.

请看下图
![Uploading 屏幕截图 2024-08-23 205944.png…]()

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by crowplexus** [comment]
your image hasn't uploaded properly, can you edit the issue so it uploads? thank's in advance

**Comment by ziran-awa** [comment]
> 您的图片没有正确上传，您可以编辑问题以使其上传吗？提前致谢 图片没有正确上传，您可以编辑信息上传吗？

![屏幕截图 2024-08-23 205944](https://github.com/user-attachments/assets/cc1c00e6-df01-4558-9324-b1f699f16f38)

**Comment by crowplexus** [comment]
I'm talking with ShadowMario to see how this can be solved, I will get back to you when I have the solution

我正在与 ShadowMario 联系，看看如何解决这个问题，一旦有了解决方案，我会给您回复。

**Comment by ziran-awa** [comment]
> 我正在与ShadowMario交谈，看看如何解决这个问题，当我有解决方案时，我会回复你
> 
> 我正在与 ShadowMario 联系，看看如何解决这个问题，一旦有了解决方案，我会给您回复。

谢了

**Comment by ziran-awa** [comment]
> 我正在与ShadowMario交谈，看看如何解决这个问题，当我有解决方案时，我会回复你
> 
> 我正在与 ShadowMario 联系，看看如何解决这个问题，一旦有了解决方案，我会给您回复。

现在好了吗

**Comment by crowplexus** [comment]
try executing these commands on a command prompt
尝试在命令提示符下执行以下命令

```
haxelib remove flxanimate
haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate 05a3e4d1c9b31ae5fc3f394bb5c9c3c477d7e506
```

**Comment by ziran-awa** [comment]
> ```
> haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate 05a3e4d1c9b31ae5fc3f394bb5c9c3c477d7e506
> ```

谢谢已经好了

**Comment by ziran-awa** [comment]
> 尝试在命令提示符上执行这些命令尝试在命令提示符下执行以下命令
> 
> ```
> haxelib remove flxanimate
> haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate 05a3e4d1c9b31ae5fc3f394bb5c9c3c477d7e506
> ```

![屏幕截图 2024-08-24 170736](https://github.com/user-attachments/assets/797e7b49-739d-4314-9082-0c5febe6ed7d)
预发布版出现的错误，进入故事模式弹出的

**Comment by crowplexus** [comment]
this happens due to missing levels.
if you want or need the default levels, you can use this command

出现这种情况的原因是缺少电平。
如果您想要或需要默认级别，可以使用此命令

`lime test cpp -D officialBuild`

**Comment by ziran-awa** [comment]
> 这是由于缺少级别而发生的。如果您想要或需要默认级别，可以使用此命令
> 
> 出现这种情况的原因是缺少电平。 如果您想要或需要默认级别，可以使用此命令
> 
> `lime test cpp -D officialBuild`

![Uploading 屏幕截图 2024-08-24 171614.png…]()

**Comment by ziran-awa** [comment]
> 这是由于缺少级别而发生的。如果您想要或需要默认级别，可以使用此命令
> 
> 出现这种情况的原因是缺少电平。 如果您想要或需要默认级别，可以使用此命令
> 
> `lime test cpp -D officialBuild`

![屏幕截图 2024-08-24 171614](https://github.com/user-attachments/assets/c206ff8a-fb25-4697-a766-d9115ba29cfd)

**Comment by crowplexus** [comment]
oh that's weird, try this?
哦，真奇怪，试试这个？
```
haxelib remove hxvlc
haxelib install hxvlc 1.8.0
```

**Comment by ziran-awa** [comment]
> haxelib install hxvlc 1.8.0

![屏幕截图 2024-08-24 172642](https://github.com/user-attachments/assets/fc24fc12-63fe-4ddb-8e9b-a0e8e4e77119)

**Comment by crowplexus** [comment]
```
haxelib remove funkin.vis
haxelib git funkin.vis https://github.com/FunkinCrew/funkVis 1f7e2858e06f2b231e2f291248fd6f45b337b4b5
```

the last error message you received is an issue with Psych Engine itself, I'm going to contact ShadowMario to fix it, running these commands should work for now.

你遇到的最后一条错误信息是心理引擎本身的问题，我正准备联系 ShadowMario 来修复它，运行这些命令目前应该可以解决。

**Comment by ShadowMario** [comment]
I don't speak chinese but it should be fixed ig?
