### ISSUE TITLE
SScript not avaible while compiling problem

### ISSUE THREAD

**Issue by Aonicsrup** [ShadowMario/FNF-PsychEngine#15406]
### Describe your problem here.

everytime i put "lime test windows" it says: C:/HaxeToolkit/haxe/lib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support. do i need to do something to stop it..
![a](https://github.com/user-attachments/assets/4289ce1c-80f6-4cee-bb93-fe2670f1f1a9)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no i didn't

**Comment by BRI189** [comment]
Install the experimental branch

**Comment by tposejank** [comment]
https://github.com/CobaltBar/SScript-Archive?tab=readme-ov-file#install-manually

**Comment by Aonicsrup** [comment]
thanks! it got solved :)
