### ISSUE TITLE
i can only play 1.0 version on the dowloands folder

### ISSUE THREAD

**Issue by isatsou** [ShadowMario/FNF-PsychEngine#15407]
### Describe your bug here.

that's it when in 0.7.3 i can play it anywhere
![Στιγμιότυπο οθόνης 2024-08-24 161333](https://github.com/user-attachments/assets/d2cd4676-a1ca-4990-aee9-e395696755dd)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Hackx2** [comment]
Make sure all files inside the .zip are in the same folder before running.

**Comment by isatsou** [comment]
@Hackx2 it still does it
