### ISSUE TITLE
Quant Notes

### ISSUE THREAD

**Issue by Pairos13** [ShadowMario/FNF-PsychEngine#15412]
### What feature do you want to get added on the **base** engine?

i fucking love quant notes
i fucking love when the colors are defined by their position and not their rail
its asimetric and at the same time colorfull
why cant you guys add that?
its so cool
and i NEED IT!!!!!!!!!!!!!!!11!!!11

it can be like this
![copy](https://github.com/user-attachments/assets/4a658a54-0870-463f-899d-8aa2f4014651)
![Sin título](https://github.com/user-attachments/assets/ad70630a-18cc-4ba1-8bf5-87301247faca)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by crowplexus** [comment]
this was rejected 3 years ago, https://github.com/ShadowMario/FNF-PsychEngine/issues/60

**Comment by Pairos13** [comment]
FuckShitCrap

**Comment by Pairos13** [comment]
it was so sick

**Comment by ShadowMario** [comment]
Not happening

**Comment by Pairos13** [comment]
>:_(

**Comment by TheWretched08** [comment]
not skibidi... not skibidi
