### ISSUE TITLE
the visual studio installation keep failing

### ISSUE THREAD

**Issue by abod-ev** [ShadowMario/FNF-PsychEngine#15419]
### Describe your problem here.

when i try the step that make me install vs studio it start and before the download start it just disappear every time i try it and when compiling the game it says
Warning: Ignoring unknown fps=""
Error: Could not find haxelib "tjson", does it need to be installed?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by bf244** [comment]
install tjson

**Comment by BRI189** [comment]
Run the windows.bat to install all the dependencies, if you are having problems with visual studio run the msvcwindows.bat yo install visual studio dependencies, and finally compile the game

**Comment by abod-ev** [comment]
the problem git don't want to download anything it always says

Installing discord_rpc from https://github.com/Aidan63/linc_discord-rpc
Error: Could not clone Git repository.
