### ISSUE TITLE
Alternate Countdown for pixel stages

### ISSUE THREAD

**Issue by CrunchBar41** [ShadowMario/FNF-PsychEngine#1541]
### Describe your problem here.

I'm working with the Lua build, and want to use the pixel arrows, but I am wondering if it is possible to use the default countdown instead of the pixel countdown on it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Made a Neco-Arc mod in it

**Comment by ShadowMario** [comment]
you can mess with countdownGo, countdownSet and countdownReady on Psych 0.5b

**Comment by CrunchBar41** [comment]
Oh, okay thanks
