### ISSUE TITLE
Could you add ModPack Option Changeable in-game/song pause?

### ISSUE THREAD

**Issue by Pairos13** [ShadowMario/FNF-PsychEngine#15411]
### What feature do you want to get added on the **base** engine?

When Im Doing a ModPack With Options, its kinda annoying to test the diferent option variants, cause i have to leave the song, get out of freeplay, go to the mod selector, search between all the modpacks, go to the modpack options, change the options, get out the modpack selector, go back to the freeplay, and then finally test it in a song. This Issue its especially goffy since theres already one for the Base Game/Engine options, so, why wont add a ModPack Options Menu in-game Pause?

It can only display the active modpacks, or at least the ones in the current song (not only the song modpack but also the "runsGlobally" ones aka huds, scripts and all that stuff) something like
![ModPackOptions](https://github.com/user-attachments/assets/e04c077b-e3c7-4aa5-b57c-3fa12e6663a5)

It can be accessed by the pause menu itself:
![InPauseMenu](https://github.com/user-attachments/assets/4ff2ee0c-6c0f-4964-aab8-984b6313d7bf)

or by the Options, but only at Pause menu:
![InPauseOptions](https://github.com/user-attachments/assets/00c775bc-585a-4451-9e94-97381a58f794)

any modification would act as a regular option in pause menu (restarts the song with the new configurations)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by ShadowMario** [comment]
Failed reliability test

**Comment by Pairos13** [comment]
ok what do you mean with "reliability test", did i was mean to you or something before?

**Comment by Pairos13** [comment]
ok sorry i understand the meaning of "reliability test"
if it was beacuse the whole thing looks like a "joke request", i really sorry for that
i SWEAR that i going serious with this petition, all the goffy writting and orthography its because im not so good at english and wrost at communicate with it, and the ugly looking concept image its because: 25% on comedy purpose, 15% because of my bad art skill and 60% because i dont wanted to go deep and profesional with a litteral "concept art"
it may look like goofy but i really want this on the engine and i would really apreciate that you add it
if its down because of something else, so yeah, sorry about that.

**Comment by Pairos13** [comment]
> Failed reliability test

i think i fucked up this
