### ISSUE TITLE
Could You Make a Splash Skin Visualiser/Preview on the menu options like its already with the Note Skin Visualiser/Preview?

### ISSUE THREAD

**Issue by Pairos13** [ShadowMario/FNF-PsychEngine#15410]
### What feature do you want to get added on the **base** engine?

At least for me, searching between all the splashes only guiding by the name is very annoying and tiring, so some kind of splash visualiser/preview like theres already one for the noteskins aka the notes above the noteSkin selector that shows the current selected noteSkin Strums, same but with the (up note) splash at the side, something like
![Spash](https://github.com/user-attachments/assets/1aa8846e-8290-48f7-89ed-2584966fd0f1)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by ShadowMario** [comment]
Done in the latest commit!
