### ISSUE TITLE
how do i remove the achievements and options on the sides?

### ISSUE THREAD

**Issue by bf244** [ShadowMario/FNF-PsychEngine#15416]
### Describe your problem here.

![image](https://github.com/user-attachments/assets/7e8b3565-34c1-4902-b150-4cef60db0315)
how do i remove the achievements and options on the sides without breaking the game?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

not anything that can break the game

**Comment by Hackx2** [comment]
Set these two to null.

```haxe
var leftOption:String = null;
var rightOption:String = null;		
```
