### ISSUE TITLE
how to build eninge for android

### ISSUE THREAD

**Issue by nguyenkiet1234d** [ShadowMario/FNF-PsychEngine#15417]
### What is your question?

 i'm looking to build eninge android to make a big mod

**Comment by nguyenkiet1234d** [comment]
So can you help me :_)

**Comment by nguyenkiet1234d** [comment]
I mean create eninge build on pc but this version is for phone

**Comment by PetscopF** [comment]
In terms of compiling, it's not really as simple as compiling for, say, Windows. [Compiling to Android requires the Android SDK and some more dependencies.](https://lime.openfl.org/docs/advanced-setup/android/)

**Comment by nguyenkiet1234d** [comment]
Thank you
