### ISSUE TITLE
Type not found : TeaCall and Type not found : Tea -- Build Error

### ISSUE THREAD

**Issue by jvan1234** [ShadowMario/FNF-PsychEngine#15429]
## Issue
I attempt to build [Psych Engine 0.7.2](https://github.com/ShadowMario/FNF-PsychEngine) using [SScript-new](https://github.com/SScript-Guy/SScript-new), but this error occurs
`source/psychlua/HScript.hx:291: characters 89-96 : Type not found : TeaCall`
I followed [this guide](https://github.com/ShadowMario/FNF-PsychEngine/issues/14147), but a similar error occurs
`source/psychlua/HScript.hx:291: characters 89-96 : Type not found : Tea`

## System specs
Raspberry Pi 4 Model B Rev 1.4
Debian/Linux
8 GB memory

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I attempted to change TeaCall in HScript.hx, but changed it back. I also used SScript-new

**Comment by Buiboy19** [comment]
why did shadowmario close this as completed? nobody even gave an answer

**Comment by jvan1234** [comment]
I'm not sure. Maybe he thought that this wasn't an issue that could be resolved by themselves? (SScript-new isn't maintained by ShadowMario)
