### ISSUE TITLE
Can't create a custom week

### ISSUE THREAD

**Issue by kittycat95** [ShadowMario/FNF-PsychEngine#15420]
### Describe your problem here.

i don't know how to create a custom week no but really i don't

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No,all i did was go to mods made my custom week and it didn't load

**Comment by Guest2621** [comment]
I can guide you
1.open Psych Engine
2.Press 7
3.week editor
4.edit anything you want
5.after editing, you can save the week json file in either in the mods file(you have to create the file named "weeks" in the mods folder first) then save or just save it in the original weeks folder in assets
