### ISSUE TITLE
when i try building psych engine i recieve this error

### ISSUE THREAD

**Issue by Lillofrost2010** [ShadowMario/FNF-PsychEngine#15426]
### Describe your bug here.

when i try to build psych engine i get this error:

### Command Prompt/Terminal logs (if existing)

```bash
C:/HaxeToolkit/haxe/lib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by tposejank** [comment]
https://github.com/CobaltBar/SScript-Archive?tab=readme-ov-file#install-manually

**Comment by Lillofrost2010** [comment]
> https://github.com/CobaltBar/SScript-Archive?tab=readme-ov-file#install-manually

Yo thx it worked

**Comment by CobaltBar** [comment]
gwa gwa

**Comment by Lillofrost2010** [comment]
> gwa gwa

?
