### ISSUE TITLE
Compile error: CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua

### ISSUE THREAD

**Issue by GIDRO32** [ShadowMario/FNF-PsychEngine#15432]
### Describe your problem here.

source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
                                                                                                             export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, not at all

**Comment by Hackx2** [comment]
`haxelib git linc_luajit https://github.com/superpowers04/linc_luajit 633fcc051399afed6781dd60cbf30ed8c3fe2c5a`

**Comment by ErmWhatthesigma-sigma** [comment]
linc luajit didnt work for me
:( (i still have the error)
