### ISSUE TITLE
Many errors when compiling

### ISSUE THREAD

**Issue by LillianaPresent** [ShadowMario/FNF-PsychEngine#15431]
### Describe your problem here.

First I wanna say sorry ahead of time, because I do not use GitHub myself too often.

Now, when compiling after fixing SScript, I receive a few errors that seem to all be of the same type, like so:

```
source/flxanimate/PsychFlxAnimate.hx:92: characters 11-21

  92 |  function _removeBOM(str:String) //Removes BOM byte order indicator
     |           ^^^^^^^^^^
     | Field _removeBOM should be declared with 'override' since it is inherited from superclass flxanimate.FlxAnimate
```

Or this one:

```
source/states/stages/Tank.hx:332: characters 24-27

 332 |   pico.anim.onComplete.add(picoStressCycle);
     |                        ^^^
     | () -> Void has no field add
```
     
There are a few more, though I don't know if posting them all here would be very efficient or not. Though I can. (I am not sure if this helps, but I am compiling in Visual Studio Code)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Hackx2** [comment]
`haxelib remove flxanimate`

then:
`haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate 768740a56b26aa0c072720e0d1236b94afe68e3e`
