### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by KernelTech11** [ShadowMario/FNF-PsychEngine#15435]
### Describe your problem here.

Does someone know How to fix this when compiling? (Sorry if the image is bad, I took this image from my phone)

![17248868268834484051073007302044](https://github.com/user-attachments/assets/a0e069d1-c273-44f5-962b-de056ce44641)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by CrusherNotDrip** [comment]
![image](https://github.com/user-attachments/assets/0c1feca7-5056-4c0a-8b47-aef0df5befa2)

**Comment by KernelTech11** [comment]
> ![image](https://private-user-images.githubusercontent.com/90648119/362506428-0c1feca7-5056-4c0a-8b47-aef0df5befa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTczNTUsIm5iZiI6MTcyNDg5NzA1NSwicGF0aCI6Ii85MDY0ODExOS8zNjI1MDY0MjgtMGMxZmVjYTctNTA1Ni00YzBhLThiNDctYWVmMGRmNWJlZmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAyMDQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YjcyYmFkYjUzYTA5NDI0MTQ3OTc3MzllNzk2NTdlMWVlYjNlNGExZjRkZDkzNTQxYWVjZWQzZWM3MmIwZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O7rxGZM_fzk4BEOgxA8JoQZDNATC3dYGdoiPysgE0Gw)

OH NO

**Comment by FuseIsHere813** [comment]
for main.hx, replace the addChild code with this:

``
addChild(new FlxGame(gameWidth, gameHeight, initialState,
#if (flixel < "5.0.0") zoom, #end
framerate, framerate, skipSplash, startFullscreen));``

flixel 5.0.0 removed "zoom" from FlxGame, here's a replacement which fixes it.
