### ISSUE TITLE
When ever I chart a song with out vocals it crashes is there to get it working

### ISSUE THREAD

**Issue by Jeffmccool** [ShadowMario/FNF-PsychEngine#15438]
### Describe your problem here.
When ever I chart a song with out vocals it crashes is there to get it working JUST WHYYYYYY

![Screenshot 2024-08-29 025231](https://github.com/user-attachments/assets/3ef59c4b-dd90-46cd-a9ee-5ea454b22fa6)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by kittycat95** [comment]
it's up to you.

**Comment by ShadowMario** [comment]
Chart Editor got completely rewritten in 1.0 so this issue is very likely already solved, if it's not, then open a new issue in 1.0
