### ISSUE TITLE
This may sound like a stupid question, and not on the topic of coding but

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#15433]
### Describe your problem here.

for example how to make this sprite
![image](https://github.com/user-attachments/assets/183e4b6b-a8a3-4a4b-8e1e-69eabbe518f1)

like this
![image](https://github.com/user-attachments/assets/5b6a3e5d-47d9-4ad6-81b1-0d45121bee77)

(I wanna make rgb shader mask like notes)

### What is your build target?

Windows x64

**Comment by Hackx2** [comment]
Look at Note.hx

**Comment by MaksPRO12667** [comment]
> Look at Note.hx it handles rgb note data

ok but how i make sprite for color mask?

**Comment by MaksPRO12667** [comment]
> ### Describe your problem here.
> for example how to make this sprite ![image](https://private-user-images.githubusercontent.com/114620759/362404797-183e4b6b-a8a3-4a4b-8e1e-69eabbe518f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTE3OTYsIm5iZiI6MTcyNDkxMTQ5NiwicGF0aCI6Ii8xMTQ2MjA3NTkvMzYyNDA0Nzk3LTE4M2U0YjZiLWE4YTMtNGE0Yi04ZTFlLTY5ZWFiYmU1MThmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNjA0NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Mjk0OGJjNDk1ZTk3ZjEyOTA5MjI5ZThmZjlhZTBhMzEyZmMwZjUzN2FmZTMwODUzZWJlMmNhOWIxMjE3YmFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F-BhtAMJdJshI-l_ixTu8YZKsZ-Z6CvCt4L9VIScGPY)
> 
> like this ![image](https://private-user-images.githubusercontent.com/114620759/362404856-5b6a3e5d-47d9-4ad6-81b1-0d45121bee77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTE3OTYsIm5iZiI6MTcyNDkxMTQ5NiwicGF0aCI6Ii8xMTQ2MjA3NTkvMzYyNDA0ODU2LTViNmEzZTVkLTQ3ZDktNGFkNi04MWIxLTBkNDUxMjFiZWU3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNjA0NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2FmODVjNzBkMDhiNDZhZGMyZmQ0NTExYTFmYTFjOTgxOGYyOTE4MDNkNjBmNzE4ZWVlY2Y0YWJlOTcwMjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EHtjDwvUrkjlNpJtNc4cFIo6-gV63RW6HOzKkTWN8DI)
> 
> (I wanna make rgb shader mask like notes)
> 
> ### Are you modding a build from source or with Lua?
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> _No response_

ok, but how i make sprite for color mask if i have colored sprie and i need to make them like this

**Comment by Hackx2** [comment]
If your trying to color a sprite like the NOTE_ASSSTS, create a new RGBPalette shader.
