### ISSUE TITLE
ScoreTxt and TimerTxt cannot be edited or gotten in lua (Pre-Release)

### ISSUE THREAD

**Issue by WowItsOnlyConnor** [ShadowMario/FNF-PsychEngine#15444]
### Describe your bug here.

I'm trying to change the font of the texts but it won't allow me because seemingly it is no longer possible to get them in lua.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by LarryFrosty** [comment]
Lua text functions are currently a bit broken and only work for lua texts as they only check for lua texts

I do have a pull request that fixes this which I'm hoping gets accepted

For now though, use `setProperty` and `getProperty`

**Comment by ShadowMario** [comment]
Approved a PR that should fix this issue
