### ISSUE TITLE
Error During Build

### ISSUE THREAD

**Issue by Idontknowhowtocode333** [ShadowMario/FNF-PsychEngine#1544]
### Describe your problem here.

I keep getting this when I try to build
`source/ModsMenuState.hx:388: characters 6-28 : {+ length : Int } should be String
source/ModsMenuState.hx:392: characters 6-42 : {+ length : Int } should be String
source/ModsMenuState.hx:396: characters 36-47 : Array access is not allowed on {+ length : Int }
source/ModsMenuState.hx:396: characters 36-47 : For function argument 'Red'
`
Does anyone know what to do?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

**Comment by SrtHero278** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/1419#issuecomment-980794707
