### ISSUE TITLE
[BUG] Psych Engine apparently adds extra frames

### ISSUE THREAD

**Issue by ExcodeFNF** [ShadowMario/FNF-PsychEngine#15446]
### Describe your bug here.

So, when I was porting a character to Psych Engine, when I did all the offsetting to the character, I noticed extra frames were being added to the character (the frames in question were miss frames for each note.)

So, then I checked the xml file to see if it was broken, and it only has the 13 frames it had before. (Note: I did not edit the xml in anyway, I got it from a janky port by someone)

Animation Indices also don't work properly, because when I added each frame, the animation freezes with no frames at all.

### PHOTOGRAPHIC PROOF

![Screenshot 2024-08-30 132556](https://github.com/user-attachments/assets/f897ee7f-c7d3-41fc-9859-41a83e669afd)

### XML PROOF

**DOWN**
![image](https://github.com/user-attachments/assets/4ee77160-30cd-49fb-bc71-4785ee6d4b42)

**LEFT**
![image](https://github.com/user-attachments/assets/6d1b614b-91c8-4d31-b031-90702a672f21)

**RIGHT**
![image](https://github.com/user-attachments/assets/198c1586-5778-456c-af40-6f3f7fe0ac38)

**UP**
![image](https://github.com/user-attachments/assets/2f786986-02bb-4a09-9c49-e7d33a22f107)

### VIDEO PROOF

Please watch the YouTube videos below in order to get enough context, GitHub does not support videos above 10MB.
https://youtu.be/IXPAuul2Uzk
https://youtu.be/zkbO6u5uJ0k

Please leave a comment if you know how to resolve this problem, Much help would be appreciated!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CrusherNotDrip** [comment]
u have to put a 0 at the end in the prefix to prevent that from happening on the normal singLEFT/DOWN/UP/RIGHT

**Comment by ExcodeFNF** [comment]
Thanks for the help, It works! @CrusherNotDrip. I also got clarification from @JVN-Pixels to help me with this error!

**Comment by FailedToLoad-Atom** [comment]
@CrusherNotDrip what prefix

**Comment by CrusherNotDrip** [comment]
> @CrusherNotDrip what prefix

![image](https://github.com/user-attachments/assets/ba6d6084-29f7-44d5-b3f9-864cf78442d7)

**Comment by FailedToLoad-Atom** [comment]
> > @CrusherNotDrip what prefix
> 
> ![image](https://private-user-images.githubusercontent.com/90648119/372616314-ba6d6084-29f7-44d5-b3f9-864cf78442d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MTA0MjYsIm5iZiI6MTcyNzgxMDEyNiwicGF0aCI6Ii85MDY0ODExOS8zNzI2MTYzMTQtYmE2ZDYwODQtMjlmNy00NGQ1LWIzZjktODY0Y2Y3ODQ0MmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE5MTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3OTk5NjJmMWQwOGFhYzAwYjFlYzY5ODA0MGM4NDg3ODA0ZWRmYjg0ZGU5MGNjZmQ1MDExYzY1OTdiZDNmNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3vL2B6hSyD4iOWp9dFoD1-U2hT1HG8yiBpS1p0Hn-JI)

thanks, it helped

**Comment by FailedToLoad-Atom** [comment]
> > @CrusherNotDrip what prefix
> 
> ![image](https://private-user-images.githubusercontent.com/90648119/372616314-ba6d6084-29f7-44d5-b3f9-864cf78442d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MTMxNDksIm5iZiI6MTcyNzgxMjg0OSwicGF0aCI6Ii85MDY0ODExOS8zNzI2MTYzMTQtYmE2ZDYwODQtMjlmNy00NGQ1LWIzZjktODY0Y2Y3ODQ0MmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDIwMDA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiODZkNGQ5ZjMyM2NhOWJkNWUxZmE0NDlkYzkzYzUzOTFkMmE4Yzc2ZDMyNjJiZjFjNzVlODcyNmZmOTcyZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DOVqvWOng6Q70uBmG9MsdKJNnMITfBNuwniZtx0-rHk)

nah now it just takes animation of the one i was on before, in game he is just frozen
