### ISSUE TITLE
icon error

### ISSUE THREAD

**Issue by efe-cpu** [ShadowMario/FNF-PsychEngine#15450]
### Describe your problem here.

objects/HealthIcon.hx (line 35)
objects/HealthIcon.hx (line 15)
states/PlayState.hx (line 547)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

i added an icon of my character to mod files, but it errors.  (sorry for my bad english)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by SantiagoCalebe** [comment]
your character icon have to be 'icon-charactername.png', have to be PNG and have to be 300x150
