### ISSUE TITLE
Weekend 1 Achievement icon

### ISSUE THREAD

**Issue by Andrew2o0** [ShadowMario/FNF-PsychEngine#15454]
### What needs to be documented?

To be honest, I feel like you all were missing something. The 'Weekend 1 no miss" achievement.
Don't even bother creating the image, i did it for you:
![weekend1_nomiss](https://github.com/user-attachments/assets/8029ee7c-9eb3-4f61-bae0-ce8f2c7ef47e)

**Comment by ShadowMario** [comment]
This was already fixed a few weeks ago
