### ISSUE TITLE
how do I get the color of the player's or opponent's icon?

### ISSUE THREAD

**Issue by FlintYotube1** [ShadowMario/FNF-PsychEngine#15456]
### Describe your problem here.

I need to get the color of the player icon in HEX for use in scripts, and I dont know how.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Lillofrost2010** [comment]
![Screenshot_20240901-221243 (1) (1).png](https://github.com/user-attachments/assets/c028c723-8724-4052-a64a-b60b1caac00a)

**Comment by maxxvoiid** [comment]
look, this is for bf (player)
```
local bfColR = getProperty('boyfriend.healthColorArray[0]')
local bfColG = getProperty('boyfriend.healthColorArray[1]')
local bfColB = getProperty('boyfriend.healthColorArray[2]')
	
local bfColFinal = string.format('%02x%02x%02x', bfColR, bfColG, bfColB)
```

and for dad (opponent)
```
local dadColR = getProperty('dad.healthColorArray[0]')
local dadColG = getProperty('dad.healthColorArray[1]')
local dadColB = getProperty('dad.healthColorArray[2]')

local dadColFinal = string.format('%02x%02x%02x', dadColR, dadColG, dadColB)
```

**Comment by FlintYotube1** [comment]
Thanks!

**Comment by FlintYotube1** [comment]
I used this script and for some reason the healthbar turned white:<
![Снимок экрана 2024-09-13 172821](https://github.com/user-attachments/assets/11fa5d4a-03c0-49f7-b99f-6444950730de)
![Снимок экрана 2024-09-13 172913](https://github.com/user-attachments/assets/caf449d1-3397-478a-bcb1-9406816ce579)


> Смотри, это для парня (игрока)
> 
> ```
> local bfColR = getProperty('boyfriend.healthColorArray[0]')
> local bfColG = getProperty('boyfriend.healthColorArray[1]')
> local bfColB = getProperty('boyfriend.healthColorArray[2]')
> 	
> local bfColFinal = string.format('%02x%02x%02x', bfColR, bfColG, bfColB)
> ```
> 
> и для папы (оппонента)
> 
> ```
> local dadColR = getProperty('dad.healthColorArray[0]')
> local dadColG = getProperty('dad.healthColorArray[1]')
> local dadColB = getProperty('dad.healthColorArray[2]')
> 
> local dadColFinal = string.format('%02x%02x%02x', dadColR, dadColG, dadColB)
> ```

**Comment by FlintYotube1** [comment]
I removed the quotes, and it helped

**Comment by maxxvoiid** [comment]
you could try something like this `doTweenColor('tweenColorObject', 'objectName', dadColFinal, 0.01)`

> but if I want to change the color of any object, then the object turns black ![Снимок экрана 2024-09-13 173743](https://private-user-images.githubusercontent.com/86910344/367337811-3995b820-f5a1-4c78-bf42-a09ac9bdd5cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNTE3NjYsIm5iZiI6MTcyNjM1MTQ2NiwicGF0aCI6Ii84NjkxMDM0NC8zNjczMzc4MTEtMzk5NWI4MjAtZjVhMS00Yzc4LWJmNDItYTA5YWM5YmRkNWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDIyMDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMGQzZTk4MzNjMTE0Zjg4YmVlZmE4ZGY4MjNhNzEwMmZkYjYxMDdmOGFhZWNkZTU0ZDllMWEyZjU3NDU4ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JvviNlgpBqWiW1nSdO_yb2K0w6ds9kZrq6ipCLmujpU)

**Comment by FlintYotube1** [comment]
> you could try something like this `doTweenColor('tweenColorObject', 'objectName', dadColFinal, 0.01)`
> 
> > but if I want to change the color of any object, then the object turns black ![Снимок экрана 2024-09-13 173743](https://private-user-images.githubusercontent.com/86910344/367337811-3995b820-f5a1-4c78-bf42-a09ac9bdd5cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNTE3NjYsIm5iZiI6MTcyNjM1MTQ2NiwicGF0aCI6Ii84NjkxMDM0NC8zNjczMzc4MTEtMzk5NWI4MjAtZjVhMS00Yzc4LWJmNDItYTA5YWM5YmRkNWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDIyMDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMGQzZTk4MzNjMTE0Zjg4YmVlZmE4ZGY4MjNhNzEwMmZkYjYxMDdmOGFhZWNkZTU0ZDllMWEyZjU3NDU4ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JvviNlgpBqWiW1nSdO_yb2K0w6ds9kZrq6ipCLmujpU)

Okay, I'll try

**Comment by FlintYotube1** [comment]
> you could try something like this `doTweenColor('tweenColorObject', 'objectName', dadColFinal, 0.01)`
> 
> > but if I want to change the color of any object, then the object turns black ![Снимок экрана 2024-09-13 173743](https://private-user-images.githubusercontent.com/86910344/367337811-3995b820-f5a1-4c78-bf42-a09ac9bdd5cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNTE3NjYsIm5iZiI6MTcyNjM1MTQ2NiwicGF0aCI6Ii84NjkxMDM0NC8zNjczMzc4MTEtMzk5NWI4MjAtZjVhMS00Yzc4LWJmNDItYTA5YWM5YmRkNWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDIyMDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMGQzZTk4MzNjMTE0Zjg4YmVlZmE4ZGY4MjNhNzEwMmZkYjYxMDdmOGFhZWNkZTU0ZDllMWEyZjU3NDU4ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JvviNlgpBqWiW1nSdO_yb2K0w6ds9kZrq6ipCLmujpU)

Yep! It's working! Thx bro!
