### ISSUE TITLE
SScript error Psych engine

### ISSUE THREAD

**Issue by Drplague6510** [ShadowMario/FNF-PsychEngine#15451]
### Describe your problem here.

![image_2024-08-31_143549208](https://github.com/user-attachments/assets/3cc8874e-ca07-4df9-9110-bd4c83b76b61)
how do i fix this?

### Are you modding a build from source or with Lua?

source

### What is your build target?

Windows x64

**Comment by Lillofrost2010** [comment]
https://github.com/CobaltBar/SScript-Archive?tab=readme-ov-file#install-manually

i also had this problem before but this fixed it for me

**Comment by efe-cpu** [comment]
use this https://github.com/CobaltBar/SScript-Archive

**Comment by Drplague6510** [comment]
![image_2024-08-31_155652494](https://github.com/user-attachments/assets/38ce357f-3291-4824-b06e-64915c741c0a)

now its showing this...
im fairly new to this kind of stuff

**Comment by Lillofrost2010** [comment]
> ![image_2024-08-31_155652494](https://github.com/user-attachments/assets/38ce357f-3291-4824-b06e-64915c741c0a)
> 
> now its showing this...
> im fairly new to this kind of stuff

Did you use the .bat files from the source code to install all the stuff needed for psych engine or did you use a tutorial?

**Comment by ShadowMario** [comment]
SScript is deprecated and was replaced by HScript-Iris on newest commits

**Comment by Lillofrost2010** [comment]
> SScript is deprecated and was replaced by HScript-Iris on newest commits

Oh ok thx, when i get home i will install it and see if it fixes the error
