### ISSUE TITLE
ABotSpeaker error

### ISSUE THREAD

**Issue by polswert1** [ShadowMario/FNF-PsychEngine#15455]
### Describe your bug here.

Basically the same error as https://github.com/ShadowMario/FNF-PsychEngine/issues/15414 , i tried to reinstall these libs but it still doesnt work, any ideas how to fix it?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
fixed
