### ISSUE TITLE
how to make a custom background please help!!

### ISSUE THREAD

**Issue by kittycat95** [ShadowMario/FNF-PsychEngine#15459]
### Describe your problem here.

I DON'T KNOW HOW TO CREATE A CUSTOM BACKGROUND
AND I DON'T KNOW HOW TO DO IT IN ANY WAY
PLEASE HELP!!!!!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No i didn't edit any thing but the my mod

**Comment by Lillofrost2010** [comment]
Use a tutorial on youtube, its not that hard and btw if you are trying to make one with the stage editor then thats only for the character position json, for the actual bg you have to create a lua file in the stages folder named the same as the stage json file and in the lua file put what the youtube tutorial says

**Comment by Lillofrost2010** [comment]
> > Use a tutorial on youtube, its not that hard and btw if you are trying to make one with the stage editor then thats only for the character position json, for the actual bg you have to create a lua file in the stages folder named the same as the stage json file and in the lua file put what the youtube tutorial says
> 
> i have done that but theres no tutorial for 7.3

Most are for older versions but they still work

**Comment by kittycat95** [comment]
> > > Use a tutorial on youtube, its not that hard and btw if you are trying to make one with the stage editor then thats only for the character position json, for the actual bg you have to create a lua file in the stages folder named the same as the stage json file and in the lua file put what the youtube tutorial says
> > 
> > 
> > i have done that but theres no tutorial for 7.3
> 
> Most are for older versions but they still work(just dont go ro too old versions)

moust of them are 4.0 or like 5.0

**Comment by Lillofrost2010** [comment]
> > > > Use a tutorial on youtube, its not that hard and btw if you are trying to make one with the stage editor then thats only for the character position json, for the actual bg you have to create a lua file in the stages folder named the same as the stage json file and in the lua file put what the youtube tutorial says
> > > 
> > > 
> > > i have done that but theres no tutorial for 7.3
> > 
> > Most are for older versions but they still work(just dont go ro too old versions)
> 
> moust of them are 4.0 or like 5.0

Use the 5.0 ones, the lua script format dosent change for the stuff thats been made for 5.0 psych engine
