### ISSUE TITLE
How do i make it where it removes a shader?

### ISSUE THREAD

**Issue by StinkTheStinker** [ShadowMario/FNF-PsychEngine#15457]
### Describe your problem here.

![image](https://github.com/user-attachments/assets/251c676f-92f5-4837-a96b-de4d59adef19)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

buzzer sound

**Comment by FuseIsHere813** [comment]
Not a Psych Engine issue.

Another thing too, OS 1.5.1 is discontinued, so the owner won't respond to any more issues related to the repo since it's archived.

**Comment by StinkTheStinker** [comment]
> Not a Psych Engine issue.
> 
> 0.5 is unsupported.
> 
> Another thing too, OS 1.5.1 is discontinued, so the owner won't respond to any more issues related to the repo since it's archived.

i wasnt even talking about os engine

**Comment by FuseIsHere813** [comment]
oh,

still tho, it's a custom function, if you were using the 0.5 shader build, that is unsupported, i can't help much.
