### ISSUE TITLE
Mods Menu Problem

### ISSUE THREAD

**Issue by booeoff** [ShadowMario/FNF-PsychEngine#15453]
### Describe your bug here.

1.0 PRE RELEASE BUG BTW

so uh i was going to the mods menu when i got this error:
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
states/ModsMenuState.hx (line 821)
states/ModsMenuState.hx (line 85)
flixel/FlxGame.hx (line 639)
flixel/FlxGame.hx (line 726)
flixel/FlxGame.hx (line 679)
flixel/FlxGame.hx (line 558)
openfl/events/EventDispatcher.hx (line 426)
openfl/display/DisplayObject.hx (line 1398)

Uncaught Error: [file_contents,mods/                                                                                 /data/settings.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

i even deleted the settings.json and it still kept happening, i have no idea why it's doing this i need help please.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

tried to test out the mod settings thing and got this error, i even deleted it like i said.

**Comment by Djotta11** [comment]
try renaming the mods folder to something else and then back to mods
