### ISSUE TITLE
please fix this!:

### ISSUE THREAD

**Issue by Kuro2423** [ShadowMario/FNF-PsychEngine#15468]
### Describe your bug here.

states/PlayState.hx (line 3081)
states/PlayState.hx (line 3065)
states/PlayState.hx (line 2927)
states/PlayState.hx (line 2879)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
every time i press w a s d i get this error and the game crashes(mod Hymns of hollownest)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

**Comment by ShadowMario** [comment]
Looks like it's a mod specific issue, report to the mod's authors
