### ISSUE TITLE
loadSong function not working

### ISSUE THREAD

**Issue by Charaster-Official** [ShadowMario/FNF-PsychEngine#15467]
### Describe your problem here.

Im probably just missing something really obvious but it seems that load song doesnt work at all, i made sure that the code that checks for your key press does work and it does. once again i think its just something super obvious that im just missing

engine version is 0.7.3

```
function onUpdate()
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.FIVE') then
    loadSong("bopeebo", 2)
    end
    
end 
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by SantiagoCalebe** [comment]
use Function onCreate

`function onUpdate()
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.FIVE') then
    loadSong("bopeebo", 2)
    end
    
end`
