### ISSUE TITLE
Songs with a space in their name

### ISSUE THREAD

**Issue by sleepysinfulkittycat** [ShadowMario/FNF-PsychEngine#15464]
### What is your question?

How do a load a song with a space in it's name in the chart editor? I try to just type the name normally (with the space) and when I try to reload audio nothing happens. What the sigma is going on?

**Comment by Arolox666** [comment]
try using dash not space.

**Comment by biomseed** [comment]
Songs with spaces in their name was a kade engine thing that psych didn't carry over

**Comment by GatoMagoXD** [comment]
Try to name the folder of the song with a dash in the space part, like "The-Song".
After that, in the Chart editor remove the dash and put a space.
