### ISSUE TITLE
Help Me, i dont know what to do

### ISSUE THREAD

**Issue by CollabTheDeveloper** [ShadowMario/FNF-PsychEngine#15465]
### Describe your problem here.

always that
![image](https://github.com/user-attachments/assets/cdc17e55-ebfd-496c-a7b7-a51d05c97caa)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by SantiagoCalebe** [comment]
Install git.

Git.com
