### ISSUE TITLE
How to add credits in 0.7.3

### ISSUE THREAD

**Issue by JesusfanTheImpostor** [ShadowMario/FNF-PsychEngine#15463]
### Describe your problem here.

So I tried to add in credits in the new Psych Engine update, but when I added this in mods/data:
Jesusfan::Jesusfan::Coder::https://www.youtube.com/JesusfanImpostorGuy::0x228B22
It showed nothing. 
![Screenshot 2024-09-02 160506](https://github.com/user-attachments/assets/22f6ce4c-8ede-463e-a7f4-fffe6092c6e4)
Can someone tell me how to fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by angelarv-fnf** [comment]
According to the information on the webpage, it looks like the functionality to add credits might not be supported in the latest version. You can try using an older version where the functionality was supported. 

The only version where the functionality was supported is 0.6.3 

You can download it here: https://github.com/ShadowMario/FNF-PsychEngine/releases/tag/0.6.3

**Comment by angelarv-fnf** [comment]
Hope this helps! :3

**Comment by FarizGD** [comment]
hey mine's works on 0.7.3

**Comment by ShadowMario** [comment]
> According to the information on the webpage, it looks like the functionality to add credits might not be supported in the latest version. You can try using an older version where the functionality was supported.
> 
> The only version where the functionality was supported is 0.6.3
> 
> You can download it here: https://github.com/ShadowMario/FNF-PsychEngine/releases/tag/0.6.3

This is false, the setup did not change between versions.
