### ISSUE TITLE
Load v-slice Chart into PsychEngine

### ISSUE THREAD

**Issue by JuanSebas1247** [ShadowMario/FNF-PsychEngine#15469]
### Describe your problem here.

In the engine source code there is a file that says vSlide and it is to load the charts of that engine, how can I load the charts because I have tried and I have not been able to

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by CrusherNotDrip** [comment]
![image](https://github.com/user-attachments/assets/2a905980-95c4-4746-8c81-9619a8241d7a)

**Comment by biomseed** [comment]
I think you just open the chart and it'll detect

**Comment by XenonHedgehog** [comment]
> ![image](https://private-user-images.githubusercontent.com/90648119/364182616-2a905980-95c4-4746-8c81-9619a8241d7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDc2NzksIm5iZiI6MTcyNjA0NzM3OSwicGF0aCI6Ii85MDY0ODExOS8zNjQxODI2MTYtMmE5MDU5ODAtOTVjNC00NzQ2LThjODEtOTYxOWE4MjQxZDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA5MzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYjRkNzJmZDFkOGE1YjRkZjE4NzlkOWY5ODg2OWQyYzkzYTFjZDNiZTU5NTcyMjcyM2E0OWE1NGIzMDFlZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gt5mE4tY6iZk5LZCxy3H1JM1dZB5hfdvZOsx9CSx6dY)

correction: it saves a psych engine chart into V-Slice

**Comment by CrusherNotDrip** [comment]
> correction: it saves a psych engine chart into V-Slice

correction: thats the button above + the button im hovering over saves a vslice chart into psych
