### ISSUE TITLE
(Prerelease 1.0.0) Combo animations behaving incorrectly

### ISSUE THREAD

**Issue by biomseed** [ShadowMario/FNF-PsychEngine#15460]
### Describe your bug here.

Nene's combo animations (that being `combo50` and `combo100`) only SOMETIMES occur. It's rare.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added Nene's `laughCutscene` animation as `sad` so that she laughs when I miss. This is expected behavior for the upcoming update to base game presumably. Nene's character json was saved over in the mods/characters folder with this change using the character editor. The combo animations still exist. `laughCutscene` was not removed.

**Comment by ShadowMario** [comment]
![image](https://github.com/user-attachments/assets/355f80f8-f1ab-42ff-9036-8676ed71efa3)
It's not a bug
