### ISSUE TITLE
Problem with lua script video (Psych Engine 1.0 Prerelease)

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#15473]
### Describe your problem here.

I have a standard simple lua script to start a video on a timer, but when the video ends, I can't pause game

 function onStepHit()
	if curStep == 10 then
		startVideo('video');
	end
 end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by UltraKrillex** [comment]
How did you fix this? I'm having the same problem.

**Comment by MaksPRO12667** [comment]
How did you fix this? I'm having the same problem.

Maybe bad optimization, but i split the video into screenshots and make xml sprite using spritesheet XML generator for fnf (warning, if the video is large, then you need to make a lot of xml sprites, since the program has a limitation on the size of the png format).
And in lua i just make animated lua sprite with 0 alpha. And i add function OnStepHit() and if curStep == 0 -- time, video became 1 alpha, and just play animation again. 
If it's difficult for you, I can record a video to make it clearer.

**Comment by NiftyAC** [comment]
> > How did you fix this? I'm having the same problem.
> 
> Maybe bad optimization, but i split the video into screenshots and make xml sprite using spritesheet XML generator for fnf (warning, if the video is large, then you need to make a lot of xml sprites, since the program has a limitation on the size of the png format). And in lua i just make animated lua sprite with 0 alpha. And i add function OnStepHit() and if curStep == 0 -- time then, video became 1 alpha, and just play animation again. If it's difficult for you, I can record a video to make it clearer.

I'm a different person but can you still make a video? i need the same thing

**Comment by MaksPRO12667** [comment]
> > > How did you fix this? I'm having the same problem.
> > 
> > 
> > Maybe bad optimization, but i split the video into screenshots and make xml sprite using spritesheet XML generator for fnf (warning, if the video is large, then you need to make a lot of xml sprites, since the program has a limitation on the size of the png format). And in lua i just make animated lua sprite with 0 alpha. And i add function OnStepHit() and if curStep == 0 -- time then, video became 1 alpha, and just play animation again. If it's difficult for you, I can record a video to make it clearer.
> 
> I'm a different person but can you still make a video? i need the same thing

Yes, you can with startVideo('path') in midSong but when video ends you can't pause. There are no other options to make a video in 1.0 in MidSong... But if you have 0.7.3(or 0.7.2h, 0.7.2) you can use this script there:
#14679

**Comment by NiftyAC** [comment]
> > > > How did you fix this? I'm having the same problem.
> 
> > > 
> 
> > > 
> 
> > > Maybe bad optimization, but i split the video into screenshots and make xml sprite using spritesheet XML generator for fnf (warning, if the video is large, then you need to make a lot of xml sprites, since the program has a limitation on the size of the png format). And in lua i just make animated lua sprite with 0 alpha. And i add function OnStepHit() and if curStep == 0 -- time then, video became 1 alpha, and just play animation again. If it's difficult for you, I can record a video to make it clearer.
> 
> > 
> 
> > I'm a different person but can you still make a video? i need the same thing
> 
> 
> 
> Yes, you can with startVideo('path') in midSong but when video ends you can't pause. There are no other options to make a video in 1.0 in MidSong... But if you have 0.7.3(or 0.7.2h, 0.7.2) you can use this script there: #14679

The thing about my song is the whole song is a video. It works on 0.7.3 and I can chart it there but I like the 1.0 chart editor better.

**Comment by MaksPRO12667** [comment]
> > > > > How did you fix this? I'm having the same problem.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Maybe bad optimization, but i split the video into screenshots and make xml sprite using spritesheet XML generator for fnf (warning, if the video is large, then you need to make a lot of xml sprites, since the program has a limitation on the size of the png format). And in lua i just make animated lua sprite with 0 alpha. And i add function OnStepHit() and if curStep == 0 -- time then, video became 1 alpha, and just play animation again. If it's difficult for you, I can record a video to make it clearer.
> > 
> > 
> > > 
> > 
> > 
> > > I'm a different person but can you still make a video? i need the same thing
> > 
> > 
> > Yes, you can with startVideo('path') in midSong but when video ends you can't pause. There are no other options to make a video in 1.0 in MidSong... But if you have 0.7.3(or 0.7.2h, 0.7.2) you can use this script there: #14679
> 
> The thing about my song is the whole song is a video. It works on 0.7.3 and I can chart it there but I like the 1.0 chart editor better. Is there a way to have the video start immediately after the countdown or does that work for it?

Xml sprites. No other way

**Comment by NiftyAC** [comment]
> > > > > > How did you fix this? I'm having the same problem.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > Maybe bad optimization, but i split the video into screenshots and make xml sprite using spritesheet XML generator for fnf (warning, if the video is large, then you need to make a lot of xml sprites, since the program has a limitation on the size of the png format). And in lua i just make animated lua sprite with 0 alpha. And i add function OnStepHit() and if curStep == 0 -- time then, video became 1 alpha, and just play animation again. If it's difficult for you, I can record a video to make it clearer.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I'm a different person but can you still make a video? i need the same thing
> 
> > > 
> 
> > > 
> 
> > > Yes, you can with startVideo('path') in midSong but when video ends you can't pause. There are no other options to make a video in 1.0 in MidSong... But if you have 0.7.3(or 0.7.2h, 0.7.2) you can use this script there: #14679
> 
> > 
> 
> > The thing about my song is the whole song is a video. It works on 0.7.3 and I can chart it there but I like the 1.0 chart editor better. Is there a way to have the video start immediately after the countdown or does that work for it?
> 
> 
> 
> Xml sprites. No other way

Dang okay. I couldn't make mine into xml sprites because it's over 4000 frames. Thanks for your help though.

**Comment by MaksPRO12667** [comment]
> Dang okay. I couldn't make mine into xml sprites because it's over 4000 frames. Thanks for your help though.

Hahahah... Bro, to avoid this, make more xml sprites for each frame, 104 sprites of a 1280x720 screenshots

**Comment by MaksPRO12667** [comment]
> > Dang okay. I couldn't make mine into xml sprites because it's over 4000 frames. Thanks for your help though.
> 
> Hahahah... Bro, to avoid this, make more xml sprites for each image, 104 sprites of a 1280x720 screenshots

'Cuz it's hard to make cutscenes in midsong now because the version is constantly changing, as are the files for compilation, as is the code. Be content with what you have

**Comment by NiftyAC** [comment]
> > Dang okay. I couldn't make mine into xml sprites because it's over 4000 frames. Thanks for your help though.
> 
> 
> 
> Hahahah... Bro, to avoid this, make more xml sprites for each image, 104 sprites of a 1280x720 screenshots

Is there anything that could do this for me or help me do that? I don't exactly know much about spritesheets and the spritesheet xml generator put everything to idle after

**Comment by MaksPRO12667** [comment]
> Is there anything that could do this for me or help me do that? I don't exactly know much about spritesheets and the spritesheet xml generator put everything to idle after

Hm... I can make a video and post it on youtube with access via link

**Comment by NiftyAC** [comment]
> > > Dang okay. I couldn't make mine into xml sprites because it's over 4000 frames. Thanks for your help though.
> 
> > 
> 
> > Hahahah... Bro, to avoid this, make more xml sprites for each image, 104 sprites of a 1280x720 screenshots
> 
> 
> 
> 'Cuz it's hard to make cutscenes in midsong now because the version is constantly changing, as are the files for compilation, as is the code. Be content with what you have

Are they gonna add a video event or script function if you know?

**Comment by NiftyAC** [comment]
> > Is there anything that could do this for me or help me do that? I don't exactly know much about spritesheets and the spritesheet xml generator put everything to idle after
> 
> 
> 
> Hm... I can make a video and post it on youtube with access via link

You can if you'd like but you don't have to

**Comment by MaksPRO12667** [comment]
> Are they gonna add a video event or script function if you know?

I don't know, ask Shadow Mario lol

**Comment by MaksPRO12667** [comment]
> You can if you'd like but you don't have to

I know but I'm bored, I wanna make something

**Comment by MaksPRO12667** [comment]
> > > You can if you'd like but you don't have to
> > 
> > 
> > I know but I'm bored, I wanna make something
> 
> Okay then you can if you want to. I'm bored too.

https://www.youtube.com/watch?v=GGmkVWd-bF8
Here you are (Very bad optimization for this and also very bad tutorial)

**Comment by NiftyAC** [comment]
> > > > You can if you'd like but you don't have to
> 
> > > 
> 
> > > 
> 
> > > I know but I'm bored, I wanna make something
> 
> > 
> 
> > Okay then you can if you want to. I'm bored too.
> 
> 
> 
> https://www.youtube.com/watch?v=GGmkVWd-bF8
> 
> Here you are (Very bad optimization for this and also very bad tutorial)

I'll try it in just a minute but thank you.
