### ISSUE TITLE
Weird Chart Editor Event Behavior (Latest Experimental Commit)

### ISSUE THREAD

**Issue by glowsoony** [ShadowMario/FNF-PsychEngine#15478]
### Describe your bug here.

When adding an event, the event works completely fine. But when clicking or doing an action in the 0 noteData (1 note for BF side) the event disappears as if the event was being the note. And when locking the event section, the note makes a new one over the old and and this behavior can also be done with event notes, both end up stacking up a lot.

https://github.com/user-attachments/assets/eedd600e-8b0a-459c-9fa0-2742ad2e783a

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No. All code from PE experimental.

**Comment by glowsoony** [comment]
I've noticed that indeed the chart editor is not completed, there is still few things that are not complete, and I suppose that's why this bug happened.

**Comment by ShadowMario** [comment]
Fixed!
