### ISSUE TITLE
How to check .xml sprite animation end

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#15474]
### Describe your problem here.

I want to make when the animation ends, it remove

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by theRealCox** [comment]
Remove what exactly?

**Comment by MaksPRO12667** [comment]
> Remove what exactly?

Animated lua sprite
I need when the sprite has finished animating, it should be remove
