### ISSUE TITLE
"Error: Could not process argument Warning: Ignoring unknown fps=""" when building

### ISSUE THREAD

**Issue by Carlosxd56** [ShadowMario/FNF-PsychEngine#15479]
### Describe your problem here.

i´m trying to build the default source code to test and edit later, but it says this
![image](https://github.com/user-attachments/assets/38fed860-2130-40d9-be96-7346a00408da)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by FuseIsHere813** [comment]
warning: ignoring unknown fps is normal

**Comment by Carlosxd56** [comment]
thank you, it fixed my issue :D
