### ISSUE TITLE
[1.0.0] 2 possible problems; chart/events and chart with older versions

### ISSUE THREAD

**Issue by iDaseka** [ShadowMario/FNF-PsychEngine#15470]
### Describe your bug here.

Hi, I don't know if this has been reported before, but I found 2 possible problems:
1 - If you save both the chart and the events, the variables that are incremented when calling a certain event are multiplied.
2 - If I save a chart in version 1.0.0 and then try to use it in version 0.7.3, the notes aren't displayed along with the respective character.  If I had to explain why, I would say it is because of how the “must hit section” has changed.

As this is my first bug report, I'm sorry if I shouldn't have put more than one bug.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
None of the two mentioned are actual bugs
