### ISSUE TITLE
Need help with dialouge

### ISSUE THREAD

**Issue by Tigedraglon10** [ShadowMario/FNF-PsychEngine#1547]
### Describe your problem here.

I need help with the dialogue, ive seen tutorials but it doesnt play 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

**Comment by DEV-idiotXD** [comment]
just code with source code

**Comment by Tigedraglon10** [comment]
> just code with source code

Well i cant, im on mac.

**Comment by DEV-idiotXD** [comment]
> > just code with source code
> 
> Well i cant, im on mac.

why do u have a apple device

**Comment by Tigedraglon10** [comment]
Anyways, Im going to get a windows 11 for christmas, so ill just start doing it later.

**Comment by DEV-idiotXD** [comment]
> Anyways, Im going to get a windows 11 for christmas, so ill just start doing it later.

just install a cracked version of win10....

**Comment by lunarcleint** [comment]
Can I see your Code?

**Comment by DEV-idiotXD** [comment]
> Can I see your Code?

for?

**Comment by Tigedraglon10** [comment]
local allowCountdown = false
function onStartCountdown()
	-- Block the first countdown and start a timer of 0.8 seconds to play the dialogue
	if not allowCountdown and isStoryMode and not seenCutscene then
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('dialogue', 'roses-tylenol');
	end
end

-- Dialogue (When a dialogue is finished, it calls startCountdown again)
function onNextDialogue(count)
	-- triggered when the next dialogue line starts, 'line' starts with 1
end

function onSkipDialogue(count)
	-- triggered when you press Enter and skip a dialogue line that was still being typed, dialogue line starts with 1
end
