### ISSUE TITLE
How can I change the hitboxes for custom notes?

### ISSUE THREAD

**Issue by KutikiPlayz** [ShadowMario/FNF-PsychEngine#1548]
### What is your question?

I added the acid notes from the retrospecter mod and when I ported the chart over, I was hitting a lot of acid notes I shouldn't be, I replaced those notes with hurt notes and it was just fine. Is it based on the size of the sprite? If so how can I change that without changing the actual file? This was happening with the tricky fire notes and halo notes as well.

I'm using source code.

**Comment by ShadowMario** [comment]
note.earlyHitMult
