### ISSUE TITLE
Video below hud for Psych Engine Pre release 1.0

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#15489]
### Describe your problem here.

Can possibly make?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by FarizGD** [comment]
no until ShadowMario fixes his LUA

**Comment by MaksPRO12667** [comment]
> no until ShadowMario fixes his LUA to 0.6.3 LUA

How do you think in what century this will happen?

**Comment by ShadowMario** [comment]
> no until ShadowMario fixes his LUA to 0.6.3 LUA

That's literally not true at all you baboon.

> Can possibly make?

On 1.0 you should be able to do this on lua:
`setObjectCamera('videoCutscene', 'game')`

If you're on HScript it should look like:
`game.videoCutscene.cameras = [game.camGame];`

**Comment by Pairos13** [comment]
guess what, boss
it DOESN'T WORK
we have to use <<setProperty('ObjectName.camera', instanceArg(<'camGame'º'camHUD'º'camOther'>), false, true);>>
im not fucking kidding 8_(

**Comment by Pairos13** [comment]
And even with that, Veriton's videoscript.lua script doesn't work
