### ISSUE TITLE
i got this error while compiling this, how do i fix it?

### ISSUE THREAD

**Issue by alexandrucn** [ShadowMario/FNF-PsychEngine#15486]
### Describe your problem here.

How do i fix this? i'm using SScript-19,0,618.zip

<img width="557" alt="Screenshot 2024-09-06 at 10 06 03 PM" src="https://github.com/user-attachments/assets/e0cac2e8-c332-4044-b190-7889fe813aa3">

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

**Comment by a-random441** [comment]
Rename Tea to TeaCall
