### ISSUE TITLE
Mod Directory not working

### ISSUE THREAD

**Issue by TheBloodyBerry** [ShadowMario/FNF-PsychEngine#15499]
### Describe your bug here.

When I enter the character editor on a mod directory and try to open something, it doesn't work. there's everything for a character sprite to work. it also worked last night. if anyone knows the problem, please help me fix it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by SantiagoCalebe** [comment]
Explain.
