### ISSUE TITLE
DanceTitle 

### ISSUE THREAD

**Issue by YoshiUUMagic** [ShadowMario/FNF-PsychEngine#15493]
### Describe your problem here.

![Screenshot 2024-09-08 003324](https://github.com/user-attachments/assets/1967ecb6-ffcf-432a-aadd-72b3361f74ca)
Do any of you guys know how to start the animation at the title screen, I can take any code if necessary. :)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by YoshiUUMagic** [comment]
Its the demon guy btw, he won't play animation :(

**Comment by PaodeMelYTBR** [comment]
Go to Assets/shared/images/gftitledance.xml and look at the name of the animation prefix, if you used AN, rename the symbol in the animation to the prefix in the gf xml.
(sorry if you couldn't understand)

**Comment by YoshiUUMagic** [comment]
> Go to Assets/shared/images/gftitledance.xml and look at the name of the animation prefix, if you used AN, rename the symbol in the animation to the prefix in the gf xml. (sorry if you couldn't understand)

Okay so is this for the source code? and whats an AN. I'm stupid :(

**Comment by CharGoldenYT** [comment]
im assuming they mean Adobe Animate

> > Go to Assets/shared/images/gftitledance.xml and look at the name of the animation prefix, if you used AN, rename the symbol in the animation to the prefix in the gf xml. (sorry if you couldn't understand)
> 
> Okay so is this for the source code? and whats an AN. I'm stupid :(

**Comment by YoshiUUMagic** [comment]
> im assuming they mean Adobe Animate
> 
> But basically if the animation you exported isnt named gfDance, you need to rename it as such
> 
> > > Go to Assets/shared/images/gftitledance.xml and look at the name of the animation prefix, if you used AN, rename the symbol in the animation to the prefix in the gf xml. (sorry if you couldn't understand)
> > 
> > 
> > Okay so is this for the source code? and whats an AN. I'm stupid :(

I don't have Abode Animate 😭

**Comment by YoshiUUMagic** [comment]
![Screenshot 2024-09-15 182435](https://github.com/user-attachments/assets/d6efee04-bc22-4ddb-9622-2c6f46360f37)


> im assuming they mean Adobe Animate
> 
> But basically if the animation you exported isnt named gfDance, you need to rename it as such
> 
> > > Go to Assets/shared/images/gftitledance.xml and look at the name of the animation prefix, if you used AN, rename the symbol in the animation to the prefix in the gf xml. (sorry if you couldn't understand)
> > 
> > 
> > Okay so is this for the source code? and whats an AN. I'm stupid :(

I change it but it is still not playing

**Comment by CharGoldenYT** [comment]
because you have idle after it
when done correctly it should look like
"gfDance0XXX" where the x's are the last 3 numbers before the end quote

**Comment by YoshiUUMagic** [comment]
> because you have idle after it when done correctly it should look like "gfDance0XXX" where the x's are the last 3 numbers before the end quote

OMG THANK YOU SO MUCH! It worked!!
