### ISSUE TITLE
( IT'S SERIOUS I SWEAR TOT) Could you add ModPack Option Changeable in-game/song pause? (i probaly be banned because of this but i was going insane if i didn't repost it)

### ISSUE THREAD

**Issue by Pairos13** [ShadowMario/FNF-PsychEngine#15492]
### WARNING: Im a little sure that im getting banned because of this, because i already post it and the boss ShadowMario close it as "Invalid" (i think) because he thought that it was a joke, or something, so i make this repost to tell him that GOD, I SWEAR IT'S SERIOUS I SWEAR TO GOD, IT'S THAT IM REALLY BAD AT ENGLISH AND BAD AT DRAWING (well, not so, it's just that those are more like concepts and NOT how exacly it must look like, the concept still here).

in case the problem it's another thing, tell me more specifically, im fucking stupid at catching that kind of jokes 
:)

When im programing or using a mod pack with options (aka, SaraHud, Util Peaks, Its A Me but There's Too Many Mechanics, etc), its really annoying to look at the different option variants.
Because i have to leave the song - get out from freeplay/storymode (in this last one i lose all the progress) - go to the mod pack selector - search between all the modpacks - go to the mod pack options - change the options - get out the modpack selector - go back to freeplay - and then finally test it in a song.
This Issue its especially fucked up when theres a lot of oprions to look and prove, plus, theres already one for the Base Game/Engine options.
so, why won't just add a mod pack options menu in-pause?

It can only display the active modpacks, or at least the ones in the current song (not only the song modpack but also the "runsGlobally" ones aka huds, scripts and all that stuff) like this:

![361174265-e04c077b-e3c7-4aa5-b57c-3fa12e6663a5](https://github.com/user-attachments/assets/461925fe-9db4-483d-b4db-5a0e6e180e26)

It can be accessed by the pause menu itself

![361174278-4ff2ee0c-6c0f-4964-aab8-984b6313d7bf](https://github.com/user-attachments/assets/f02cc978-89e6-4cf9-9606-985bd61897df)

or by the Options, but only at Pause menu

![361174317-00c775bc-585a-4451-9e94-97381a58f794](https://github.com/user-attachments/assets/a9448fb9-0934-4c64-aa8f-48c5c418123d)

any modification would act as a regular option in pause menu (restarts the song with the new configurations)

**Comment by Pairos13** [comment]
im scared

**Comment by FuseIsHere813** [comment]
Deleted the sight-reliability test. Instantly invalid.

**Comment by Pairos13** [comment]
what do you mean?
i have to delete the images?

**Comment by Pairos13** [comment]
im gonna delete it just in case

**Comment by Lorekeeper49** [comment]
> what do you mean?
> i have to delete the images?

That's not what he means, when you open an enhancement type issue, there is a second field which is a sight readability test that you must pass in order to make the request valid.  Since you have deleted that test, you have failed it, deeming this issue is invalid.

**Comment by Pairos13** [comment]
til i can understad (because as i said, im sh1ty at comunicating in inglish) im suposed to first pass a "sight readability test" which is on the enchancement type issue menu before even start to make the issue itself?
that means that this issue post is now a "failed sight-reliability test" FOREVER?
or im just dumb and i can pass it thoug this issue post?
im really a beginner dumbass here :_/
