### ISSUE TITLE
ANIMATION NOT FOUND Errror with my sprite

### ISSUE THREAD

**Issue by LumoTV** [ShadowMario/FNF-PsychEngine#15490]
### Describe your problem here.

i want to create a fnf mod but there are always a animation not found error in my sprite

Here's my sprites files
[slime.json](https://github.com/user-attachments/files/16918946/slime.json)
![slime_assets](https://github.com/user-attachments/assets/ab45a75c-66e1-4bd4-9e14-3e8eff46acfe)
the xml file : [http://slimesoftware.atspace.eu/files/slime_assets.xml](url)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

idk

**Comment by CharGoldenYT** [comment]
the json puts the anims as "kirby <anim>"
the xml says "Slime <anim>"

**Comment by LumoTV** [comment]
not working :/
![image](https://github.com/user-attachments/assets/6c1fae67-f440-4575-9e56-de9cef7745e6)

**Comment by frantastic24** [comment]
case sensitivity
![imagen](https://github.com/user-attachments/assets/5374ae4f-b21a-4d44-9131-1b2bef4460d1)
![imagen](https://github.com/user-attachments/assets/6bbec966-e0b3-4836-b09f-1354782cb561)
