### ISSUE TITLE
Why not add startVideo('tag', 'file') resumeVideo('tag') pauseVideo('tag') stopVideo('tag') in lua? (Srry for this really)

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#15496]
### What feature do you want to get added on the **base** engine?

Please forgive me if this shouldn't have been asked.

After all, it will be convenient for people who want to make a cutscene on lua in Midsong
startVideo('tag', 'file') -- start video u know
pauseVideo('tag') -- pause video
resumeVideo('tag') -- resume video
stopVideo('tag') -- stop video
And also make setObjectCamera() for video

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Lorekeeper49** [comment]
This is more of something for video sprites and video sprites are exactly native things, the only real implementation I could find of them would be an Hscript that can be placed in your mod folder

**Comment by MaksPRO12667** [comment]
> This is more of something for video sprites and video sprites aren't exactly native things, the only real implementation I could find of them would be an Hscript that can be placed in your mod folder

yea but no guide for Pre-release 1.0
