### ISSUE TITLE
the new hold animation shit isn't kinda working for player characters I n the new prerelease

### ISSUE THREAD

**Issue by ujeene1001** [ShadowMario/FNF-PsychEngine#15491]
### Describe your bug here.

I have submitted a video showcasing what the bug is in detail

https://github.com/user-attachments/assets/46303f82-7d4d-4576-9d56-326256aca621

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I have edited the mom and bf files in the car stage and that was it And also added some hud Scripts

**Comment by ShadowMario** [comment]
Your recording is too laggy, I can't understand what's happening, so I'm closing this due to extremely low quality
