### ISSUE TITLE
how do i make a max combo?

### ISSUE THREAD

**Issue by Flubbedsoda6010** [ShadowMario/FNF-PsychEngine#15501]
### Describe your problem here.

just need the line to make it, have everything else done

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Pairos13** [comment]
local MaxComb = 0

function onRecalculateRating()

**Comment by Pairos13** [comment]
local MaxComb = 0

function onUpdatePost(elapsed)

 if combo > MaxComb then MaxComb = combo end

setTextString('##texttag##', 'Top Combo: ' ..MaxCombo)
end

--Note: make sure that the "ecuation" and the text string are in the same callback function, it also can work with similar like onRecalculateRating()
