### ISSUE TITLE
Add Feature from JS Engine

### ISSUE THREAD

**Issue by einbuis07** [ShadowMario/FNF-PsychEngine#15508]
### What feature do you want to get added on the **base** engine?

Add Spam Tab in Chart Editor Like in js engine cuz everyone like making fansongs of bambi spam songs

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by CobaltBar** [comment]
No

**Comment by CrusherNotDrip** [comment]
No

**Comment by FuseIsHere813** [comment]
No

**Comment by FuseIsHere813** [comment]
You failed the test too lil bro... 🤦‍♂️

**Comment by JordanSantiagoYT** [comment]
failed the test + why?

**Comment by ShadowMario** [comment]
"Everyone likes that" is a really poor generalization ngl

**Comment by FuseIsHere813** [comment]
> "Everyone likes that" is a really poor generalization ngl

W ShadowMario.
