### ISSUE TITLE
building game issue (psych engine 0.7.3)

### ISSUE THREAD

**Issue by youyou1603** [ShadowMario/FNF-PsychEngine#15500]
### Describe your bug here.

i was building the **psych engine 0.7.3** i follow the steps in this page: **https://github.com/ShadowMario/FNF-PsychEngine/wiki/Libraries-versions** 
and i run **setup-windows.bat** and go into **art** folder ,run  **build_x64.bat** and he give me this : 

### Command Prompt/Terminal logs (if existing)

```bash
fnf-psychEngine-0.7.3/lime/sscript/7.7.0/src/macro/macro.hx:10: characters 96-100:sscript is not available, thanks to everyone for their support
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by PetscopF** [comment]
I've seen that this issue is becoming prominent; there's a general-use repository [specifically to address this issue.](https://github.com/CobaltBar/SScript-Archive)

**Comment by youyou1603** [comment]
it work! ,but you have to update lime (**support lime 8.0.2 or higher**) so thanks I appreciate that
issue solved!
