### ISSUE TITLE
How to add extra button

### ISSUE THREAD

**Issue by DEV-idiotXD** [ShadowMario/FNF-PsychEngine#1550]
### Describe your problem here.

How do i make extra keys soi can make custom binds for example a dodge buton (like in vs aflac)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, but the sc from fnf psych with extra keys

**Comment by HafimieForever** [comment]
like shaggy??

**Comment by CrusherMods** [comment]
they have a repository there you know

**Comment by DEV-idiotXD** [comment]
> they have a repository there you know

where?
