### ISSUE TITLE
Scroll Speed Tween With LUA

### ISSUE THREAD

**Issue by FarizGD** [ShadowMario/FNF-PsychEngine#15517]
### Describe your problem here.

how to change the song's scroll speed with LUA? (not with the "Change Scroll Speed" event)

can you make it tweening?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no. its just my mod.

**Comment by Thiago821** [comment]
put this on script folder
intead of .lua at the end put .hx and it bugs when something dont have aliasing

```
function onSongStart(){
    
}
function onSpawnNote(dunceNote){
	if(dunceNote.mustPress != true){
        FlxTween.num(0.5, 1.6, 1.8, {ease: FlxEase.cubeIn, onUpdate:(t) -> {
                dunceNote.multSpeed = t.value;
            }
        });
    }
}

//quartTween,quintTween,cubeTween is good
```

**Comment by LarryFrosty** [comment]
Yes, with `startTween`.

```lua
-- startTween template
startTween('tweenTag', 'objectTag', {property = value}, duration, options)

-- Tweening the scroll speed to 3.5 with a duration of 5 seconds by using `game` as the object tag
startTween('scrollTween', 'game', {songSpeed = 3.5}, 5, {ease = 'linear'})
```

More information about startTween like the `options` argument can be found here: https://github.com/Meme1079/PsychWiki/wiki/Lua-Script-API:-Tweens-&-Timers-Functions#starttweentagstring-varsstring-valuesany--null-durationfloat-optionsany--null

Note: The page says you can tween the game's variables by using `this` whilst the example above is showing `game`.
This just means that there are 3 different name which all lead to the same thing (The 3rd one being `instance`)
