### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by 8odi** [ShadowMario/FNF-PsychEngine#15519]
### Describe your bug here.

Whenever I try compiling the game I get this error (In the Command Prompt)
I dont know why this problem happens. I tried so long and so much trying to fix this. I read how to setup compiling, I watched tutorials, I used the setup thingy in the source code, I read the "read_this_if_you_cant_compile.txt" file, and did the stuff i needed to do from there. I tried reinstalling everything. I even tried getting help from a programmer friend! Infact, that friend got this exact thing in the Command Prompt, but it just kept compiling for him! For some reason, for me when I got this, it just stopped compiling!!! I even tried removing the source code from my computer and downloading it again.

### Command Prompt/Terminal logs (if existing)

```bash
source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by FuseIsHere813** [comment]
Reinstall "linc_luajit" 

`haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit`

**Comment by 8odi** [comment]
I LVOE YOU SO MUCH YHASF BNMMMMBV
