### ISSUE TITLE
Trouble compiling

### ISSUE THREAD

**Issue by jesseydeanimator** [ShadowMario/FNF-PsychEngine#15511]
### Describe your bug here.

every time i try to build psych engine, it shows this error, i tried deleting the export folder many times and it didn't work. any help?

### Command Prompt/Terminal logs (if existing)

```bash
Link: ApplicationMain.exe
   Creating library ApplicationMain.lib and object ApplicationMain.exp

Failed to update resources
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i changed the project.xml, i removed the psych engine credits thing

**Comment by CharGoldenYT** [comment]
ok, first things first, this is typically a non fatal issue, and entirely a not related to psych engine.

second does it not open the game when this error occurs?
