### ISSUE TITLE
Is there a way to display text from Alphabet in LUA?

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#15518]
### Describe your problem here.

Can I do it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by kentongus** [comment]
I don't think it's possible

**Comment by MaksPRO12667** [comment]
> I don't think it's possible

But what about monochrome? There was this...

I think it's possible, if make:

local yourcooltext {
'ass',
'shit'
}

but what i need to do next i don't know

**Comment by ShadowMario** [comment]
```lua
function onCreatePost()
	createInstance('alphabetTest', 'objects.Alphabet', {500, 500, 'This is a Text', true})
	setObjectCamera('alphabetTest', 'hud')
	addLuaSprite('alphabetTest', true)
end
```
This works for 0.7.3+

**Comment by MaksPRO12667** [comment]
> ```lua
> function onCreatePost()
> 	createInstance('alphabetTest', 'objects.Alphabet', {500, 500, 'This is a Text', true})
> 	setObjectCamera('alphabetTest', 'hud')
> 	addLuaSprite('alphabetTest', true)
> end
> ```

thank you very much
