### ISSUE TITLE
Error when compiling 0.7.3

### ISSUE THREAD

**Issue by prockscac** [ShadowMario/FNF-PsychEngine#15512]
### Describe your problem here.

Everytime I compile psych engine 0.7.3 I get this error

source/psychlua/HScript.hx:436: characters 9-16 : tea.SScript has no field destroy
source/psychlua/HScript.hx:431: characters 27-34 : Field destroy is declared 'override' but doesn't override any field
source/psychlua/HScript.hx:39: characters 7-15 : psychlua.HScript has no field doString (Suggestion: toString)

I'm not sure if I have to download something

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by FarizGD** [comment]
hmm maybe change the ver of ur sscript lib.

**Comment by ShadowMario** [comment]
SScript got replaced with HScript-Iris in 1.0 so I will have to close this
