### ISSUE TITLE
Every time i want to do the lime test windows in cmd from my folder that bugs and saying:

### ISSUE THREAD

**Issue by DuckkFnF** [ShadowMario/FNF-PsychEngine#15513]
### Describe your bug here.

But i have a SScript installed.

### Command Prompt/Terminal logs (if existing)

```bash
C:/HaxeToolkit/haxe/lib/SScript/21,0,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes

**Comment by FuseIsHere813** [comment]
should already be fixed, use this https://github.com/CobaltBar/SScript-Archive

**Comment by DuckkFnF** [comment]
Thx
