### ISSUE TITLE
Custom songs are all FreakyMenu

### ISSUE THREAD

**Issue by drakobloxxer** [ShadowMario/FNF-PsychEngine#15528]
### Describe your bug here.

i tried to add a custom song to psych engine, i tried a lot of things but whenever i go to the chart editor or actually play the song it's just freakymenu
i do not know how to fix this

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i edited the songs

**Comment by kittycat95** [comment]
if you're typing them correct it may work, if you want an example just type
the song you're looking for like `pico` `milf` and other's. try this yourself

**Comment by drakobloxxer** [comment]
> if you're typing them correct it may work, if you want an example just type the song you're looking for like `pico` `milf` and other's. try this yourself

i typed them correctly, i checked multiple times

**Comment by SantiagoCalebe** [comment]
Check if your song is really OGG and if isn't corrupted.
