### ISSUE TITLE
how do i code in a secret menu where you have to input a code to get a song?

### ISSUE THREAD

**Issue by tlaguepoons** [ShadowMario/FNF-PsychEngine#15523]
### What is your question?

how do i code in a secret menu where you have to input a code to get a song? like regular friday night

**Comment by TechnikTil** [comment]
you figure it out
easy fix

**Comment by FuseIsHere813** [comment]
> you figure it out
> 
> easy fix

Unhelpful.

**Comment by TechnikTil** [comment]
> > you figure it out
> > easy fix
> 
> Unhelpful.

What? Help me!

**Comment by FuseIsHere813** [comment]
AFTER ALL 🗣️🔥

**Comment by MrRainbowCoding** [comment]
If you want source:

https://github.com/ShadowMario/FNF-PsychEngine/issues/8643

If you want lua:

https://gamebanana.com/tuts/15313
