### ISSUE TITLE
Bop city won't open (I deleted and reinstalled the game multiple times)

### ISSUE THREAD

**Issue by dvrrkie** [ShadowMario/FNF-PsychEngine#15527]
### Describe your problem here.

states/TitleState.hx (line 125)
states/Title.hx (line 100)
flixel/util/FlxTimer.hx (line 230)
flixel/util/FlxTimer.hx (line 320)
flixel/util/FlxTimer.hx (line 748)
flixel/util/FlxTimer.hx (line 680)
flixel/util/FlxTimer.hx (line 559)
openfl/events/EventDispatcher.hx (line 426)
openfl/display/DisplayObject.hx (line 1398)

Uncaught Error: Null Object Reference

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TechnikTil** [comment]
**Bop city:**
**Psych Engine:**
looks like that adds up
