### ISSUE TITLE
THE FUCKING DIALOGUE CODE WON'T WORK

### ISSUE THREAD

**Issue by JimMeta-belike** [ShadowMario/FNF-PsychEngine#15524]
### Describe your bug here.

"flixel/sound/FlxSound.hx (line 595)
flixel/sound/FlxSound.hx (line 739)
flixel/system/frontEnds/SoundFrontEnd.hx (line 183)
flixel/system/frontEnds/SoundFrontEnd.hx (line 241)
objects/TypedAlphabet.hx (line 39)
flixel/group/FlxGroup.hx (line 144)
flixel/group/FlxSpriteGroup.hx (line 209)
cutscenes/DialogueBoxPsych.hx (line 305)
flixel/group/FlxGroup.hx (line 144)
flixel/addons/ui/FlxUIState.hx (line 212)
backend/MusicBeatState.hx (line 81)
states/PlayState.hx (line 1643)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)"

WHAT THE FUCK IS THIS SUPPOSED TO MEAN?

### Command Prompt/Terminal logs (if existing)

```bash
flixel/sound/FlxSound.hx (line 595)
flixel/sound/FlxSound.hx (line 739)
flixel/system/frontEnds/SoundFrontEnd.hx (line 183)
flixel/system/frontEnds/SoundFrontEnd.hx (line 241)
objects/TypedAlphabet.hx (line 39)
flixel/group/FlxGroup.hx (line 144)
flixel/group/FlxSpriteGroup.hx (line 209)
cutscenes/DialogueBoxPsych.hx (line 305)
flixel/group/FlxGroup.hx (line 144)
flixel/addons/ui/FlxUIState.hx (line 212)
backend/MusicBeatState.hx (line 81)
states/PlayState.hx (line 1643)
flixel/FlxState.hx (line 222)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I dont know tbh

**Comment by TechnikTil** [comment]
related to the actual dialogue text sfx. anything you changed about that?

**Comment by JimMeta-belike** [comment]
> related to the actual dialogue text sfx. anything you changed about that?

I fixed it, it's alr now
