### ISSUE TITLE
Why is this showing up?

### ISSUE THREAD

**Issue by toppat-lol** [ShadowMario/FNF-PsychEngine#15521]
### Describe your bug here.

I was trying to compile psych engine 1.0.0 prerelease and kept on getting this error even tho i fixed it

### Command Prompt/Terminal logs (if existing)

```bash
keeps on saying:
source/backend/ui/PsychUIInputText.hx:224: characters 3-9 : Expected }
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not yet

**Comment by TechnikTil** [comment]
what haxe version are you on?

**Comment by WahMaker** [comment]
im having the same issue
