### ISSUE TITLE
Playable pico thing and other stuff (but other stuff and FREEPLAY from your post on discord) from v0.5.0 base game.

### ISSUE THREAD

**Issue by Andrew2o0** [ShadowMario/FNF-PsychEngine#15532]
### What feature do you want to get added on the **base** engine?

They Og devs added winning icon support to their game, why can't you? They also added playable Pico to their game. You wanna add them or is it Unfamiliar with you because you like the 0.2.X/legacy one better? dude, please. i am on my knees. You can still add the *other* Freeplay thing. Just as an optional so mods won't act like bullshit. What about erect songs and other character remixes. I am on my knees please. just give them a chance, please!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Actual feedback

**Comment by Andrew2o0** [comment]
oh yeah, fix your game compiling thing, it keeps failing as I could see in the actions tab.

**Comment by CrusherNotDrip** [comment]
> Actual feedback

Failed reliability test

**Comment by kentongus** [comment]
> ### What feature do you want to get added on the **base** engine?
> They Og devs added winning icon support to their game, why can't you? They also added playable Pico to their game. You wanna add them or is it Unfamiliar with you because you like the 0.2.X/legacy one better? dude, please. i am on my knees. You can still add the _other_ Freeplay thing. Just as an optional so mods won't act like bullshit. What about erect songs and other character remixes. I am on my knees please. just give them a chance, please!
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Actual feedback

if u want them so bad, add them urself

**Comment by FuseIsHere813** [comment]
> ### What feature do you want to get added on the **base** engine?
> They Og devs added winning icon support to their game, why can't you? They also added playable Pico to their game. You wanna add them or is it Unfamiliar with you because you like the 0.2.X/legacy one better? dude, please. i am on my knees. You can still add the _other_ Freeplay thing. Just as an optional so mods won't act like bullshit. What about erect songs and other character remixes. I am on my knees please. just give them a chance, please!
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Actual feedback

Oh my god not only did you FAIL the test, you're asking for stuff that's NOT fully released to the public (the source code is not available)

**Comment by ShadowMario** [comment]
"I am almost done working on 1.0, the project is almost 100% completed"
"Ummmm but can you add this completely optional thing from a version that just dropped and doesn't even have its source open"
