### ISSUE TITLE
the game just crashes on opening (1.0)

### ISSUE THREAD

**Issue by expungeddotdat** [ShadowMario/FNF-PsychEngine#15530]
### Describe your bug here.

when i open the game it just black screen and this little error. 
![image](https://github.com/user-attachments/assets/b8166134-ece4-49a4-829f-df0405cbf886)
i cant just play the game, it will crash immideatly. how to fix that? i didnt touch anything, just unpacked from zip and this is the first thing when i open exe.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
I've seen that issue before but I don't know what's causing it, is there any crash log related to it? (Check the crash folder inside psych engine, *if* it exists)

**Comment by crowplexus** [comment]
drag lime.ndll into the game's executable and see what happens

i've had this error before

**Comment by expungeddotdat** [comment]
> drag lime.ndll into the game's executable and see what happens
> 
> i've had this error before

not working

**Comment by isatsou** [comment]
Put psych engine 1.0 in the dowloands folder that worked for me

**Comment by ShadowMario** [comment]
1.0 is out now, try it out, make a new issue if it is still not working please
