### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by Beuhnoice** [ShadowMario/FNF-PsychEngine#15531]
### Describe your bug here.

When I either press/miss a note as bf, the game gives me a error and crashes.

### Command Prompt/Terminal logs (if existing)

```bash
states/PlayState.hx (line 1847)
states/PlayState.hx (line 2989)
states/PlayState.hx (line 2642)
states/PlayState.hx (line 2601)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I am using a custom bf skin and custom note skin, but that's about it

**Comment by TechnikTil** [comment]
the crash is about the opponents health icon. is there anything wrong with that?
