### ISSUE TITLE
(1.0 Pre-Release) Cursor hiding in the Character Editor Menu

### ISSUE THREAD

**Issue by kentongus** [ShadowMario/FNF-PsychEngine#15534]
### Describe your bug here.

Whenever you try to exit the Character Editor without changes saved, the prompt that asks you to save the changes appears and hides the cursor from your sight.

Before:
![image](https://github.com/user-attachments/assets/17b5f38b-d3a7-490b-b412-3856f0651ee4)

After:
![image](https://github.com/user-attachments/assets/67a327a3-2c29-4d18-ae0d-dbc0608152c6)

There's no way of making the cursor visible again inside the editor (to my knowledge).
I'm not sure if the same happens in the other debug menus, or in any other menu for that matter.
This obviously gets fixed whenever you re-enter the Character Editor or go to any other state, substate, event or whatever thing that activates the cursor.

Still, it's annoying trying to navigate a menu with an invisible cursor.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by KernelTech11** [comment]
Press the windows key, try to put your mouse cursor under the exit button without seeing the button, count the applications until you count to the FNF icon, press windows+ the number you counted to and click the exit button really fast and done!

**Comment by kentongus** [comment]
bruh

**Comment by Stefan2008Git** [comment]
@ShadowMario forgot to move the code when you trying to exit from editor on unsaved state

**Comment by ShadowMario** [comment]
Fixed in a previous commit
