### ISSUE TITLE
Character (Idle animation) on the Main Menu

### ISSUE THREAD

**Issue by kiritinhokirigaya** [ShadowMario/FNF-PsychEngine#15539]
### Describe your problem here.

I want to add a character on the left side of the screen in main menu, but i not found nothing in internet of how to do this thing. Someone help me?
![Screenshot_20240916-155114](https://github.com/user-attachments/assets/22e59285-7ea4-4728-87a0-dab1f631b819)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i am trying to make this with Mods Folder.

**Comment by kiritinhokirigaya** [comment]
I am making this on Android System.

**Comment by kentongus** [comment]
it's impossible, the only way to do it is through source code

**Comment by kiritinhokirigaya** [comment]
ok, thanks for helping me anyway.
