### ISSUE TITLE
I can't even open the engine.

### ISSUE THREAD

**Issue by LukaYG03** [ShadowMario/FNF-PsychEngine#15538]
### Describe your bug here.

I was change with the game's arrow options, so I ended up pressing it to change the skin or something. But when I did that, the game crashed and showed what I pasted below. I try to open the game, but this keeps appearing and it closes.

### Command Prompt/Terminal logs (if existing)

```bash
backend/Paths.hx (line 275)
backend/Paths.hx (line 247)
states/TitleState.hx (line 209)
states/TitleState.hx (line 170)
flixel/util/FlxTimer.hx (line 205)
flixel/util/FlxTimer.hx (line 295)
flixel/FlxGame.hx (line 750)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I just modified/added some ".Lua and .Json" files. No ".hx"

**Comment by LukaYG03** [comment]
Forget it, I managed to fix it myself. I just went into the Funkin files, and changed a number in the "Vanillay" area.

**Comment by LukaYG03** [comment]
Forget it, I managed to fix it myself. I just went into the Funkin files, and changed a number in the "Vanillay" area.

**Comment by TBFAPCreator** [comment]
> Forget it, I managed to fix it myself. I just went into the Funkin files, and changed a number in the "Vanillay" area.

where is the funkin files, i am having that error too

**Comment by mourabra04** [comment]
I did this a while ago, so I don't remember exactly how I did it. I typed %appdata% in the search bar, then went to a folder called "roaming", then ShadowMario, Psych Engine and you'll find this file. I modified a random number in the text file and the game went back to normal.

Paths: AppData\Roaming\ShadowMario\PsychEngine

**Comment by TBFAPCreator** [comment]
> I did this a while ago, so I don't remember exactly how I did it. I typed %appdata% in the search bar, then went to a folder called "roaming", then ShadowMario, Psych Engine and you'll find this file. I modified the "Vanillay" in the text file and the game went back to normal.
> 
> Paths: AppData\Roaming\ShadowMario\PsychEngine

i am in the files rn, but i cant seem to find the "Vanillay" you mentioned, is it in the "psychengine.sol" file or is it in the "psychengine" folder?

**Comment by mourabra04** [comment]
It's in the Psych Engine folder, inside it there should be a text file called "funkin" with the SOL format. That's where I modified it.

**Comment by TBFAPCreator** [comment]
> It's in the Psych Engine folder, inside it there should be a text file called "funkin" with the SOL format. That's where I modified it.

strange, i am in the funkin.sol file but didnt find the "Vanillay"

**Comment by mourabra04** [comment]
The file has many words together that have to do with game information. Can you use a tool inside the text file that can locate specific text? They are divided by 2 ":", one at the beginning of the word and one at the end.

If you don't find it, you might be able to modify a random number, but I can't guarantee that it will work.
