### ISSUE TITLE
Adding character to Psych

### ISSUE THREAD

**Issue by NotFurryGirlKapiXD** [ShadowMario/FNF-PsychEngine#15547]
### Describe your bug here.

![image_2024-09-17_190333727](https://github.com/user-attachments/assets/e921cda4-cf40-407b-83c4-d622c8eaaed0)
I added the character into the Character editor, and it was successful. But, I add it into a song, it greets me with this error message.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
Version?

**Comment by NotFurryGirlKapiXD** [comment]
> Version?

0.6.3, since 0.7.1 character editor didn't work
