### ISSUE TITLE
Compile.. come back.. (SOLVED)

### ISSUE THREAD

**Issue by VojtaBubela11** [ShadowMario/FNF-PsychEngine#15543]
### What feature do you want to get added on the **base** engine?

I want SScript to be replaced in the next update of the 1.0.0 Prerelease.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CrusherNotDrip** [comment]
It already is replaced in the experimental branch.

**Comment by crowplexus** [comment]
[it did](https://github.com/ShadowMario/FNF-PsychEngine/commit/8c66d1d98b9e808c78b66fcbfa562ab0e0f68730

**Comment by crowplexus** [comment]
close the issue, don't re-label it
