### ISSUE TITLE
Trying to add characters to engine but keeps saying "ERORR - NO ANIMATION"

### ISSUE THREAD

**Issue by ChristianAnimations** [ShadowMario/FNF-PsychEngine#15548]
### Describe your bug here.

I have been trying to enter my character into a mod I am making with this engine and I type the image file name, and look at other issues, but have yet to fix the problem due to how confused I got reading the different issues people had and on how to fix this engine problem.

Do you have any tips or help I could get?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added my own sprite sheet for my FNF mod

**Comment by liamp0924** [comment]
send a vid of you trying to add the character

**Comment by ChristianAnimations** [comment]
![Notepad 9_17_2024 8_55_35 PM](https://github.com/user-attachments/assets/0ae6fc44-8654-4863-bcb4-bed4ff4be735)

Couldn't send a video due to GitHub's file size limit but I do have a screenshot.

![Friday Night Funkin'_ Psych Engine 9_17_2024 8_59_45 PM](https://github.com/user-attachments/assets/9b013e0d-9050-4e2d-92d6-6af63c9fdd5f)

**Comment by liamp0924** [comment]
use [streamable.com](url) to host your video and send the link

**Comment by ChristianAnimations** [comment]
https://drive.google.com/file/d/1zAwhouREtHPKCaOs0aLyIope2ZeHpTOb/view?usp=sharing

**Comment by liamp0924** [comment]
did you put your file in the mods folder?

**Comment by ChristianAnimations** [comment]
Yes! It is in the mod files!
![characters 9_20_2024 9_41_10 PM](https://github.com/user-attachments/assets/44d2b22b-a03d-4f01-b7e1-db980c5b8d56)

P.S. I edited the sprites a bit. The name might be different but I put it exactly how the image name is written.

**Comment by ShadowMario** [comment]
Open the Character Editor through Main Menu (by pressing 7 on Main Menu), then check if the Mod Folder loaded is "My-Mod", if not, then press Left/Right to scroll through Mod folders
![image](https://github.com/user-attachments/assets/8ff73184-f560-4715-aa2e-a1a38b888a36)
