### ISSUE TITLE
Problema al ejecutar PsychEngine en Arch Linux (entorno gráfico LXQt) con flatpak

### ISSUE THREAD

**Issue by Utaqui** [ShadowMario/FNF-PsychEngine#15545]
### Describe your bug here.

Cuando intento jugar alguna semana, la PsychEngine se rompe. y ademas cuando voy a la opcion de graficos tambien se rompe.
![screen01](https://github.com/user-attachments/assets/8b44ec55-8d8a-4c92-a5a5-67769cb5db25)

### Command Prompt/Terminal logs (if existing)

```bash
(flatpak run:1233): flatpak-DEBUG: 15:23:23.034:     XDG_DATA_HOME
(flatpak run:1233): flatpak-DEBUG: 15:23/etc/egl/egl_external_platform.d:/usr/lib/x86_64-linux-gnu/GL/egl/egl_external_platform.d:/usr/share/egl/egl_external_platform.d
flatpak-INFO: 15:23:23.034: Running 'bwrap --args 43 -- io.github.shadowmario.fnf-psychengine.sh'
sh: línea 1: xdg-mime: orden no encontrada
source/backend/Discord.hx:63: Discord Client initialized
source/states/LoadingState.hx:159: Setting asset folder to week1
source/backend/Conductor.hx:124: new BPM map BUDDY []
/app/bin/io.github.shadowmario.fnf-psychengine.sh: línea 4:     3 Instrucción ilegal     (`core' generado) ./PsychEngine
[koi@archlinux ~]$
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by crowplexus** [comment]
parece que el juego esta intentando cargar los archivos que necesita pero no puede, podrias probar la version github actions, la version flatpak la gestiona otra persona, y no sabemos si es exactamente estable.

https://github.com/ShadowMario/FNF-PsychEngine/actions/runs/10905419145
