### ISSUE TITLE
How to use this credits.txt

### ISSUE THREAD

**Issue by DavesTheBone** [ShadowMario/FNF-PsychEngine#15559]
### Describe your problem here.

I tried to add credits to make a mod, but I don't know how to do it.
The youtube tutorial says “use this file”
But when I opened that .txt file, the contents were blank, nothing.
How do I add credits using this file?
![スクリーンショット 2024-09-21 131058](https://github.com/user-attachments/assets/bd0eb904-8304-4015-8df1-6bfaebf9fee3)
If possible, please also tell me how to add an icon for the credits.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I use "mods" file
![スクリーンショット 2024-09-21 132147](https://github.com/user-attachments/assets/be984fba-df66-4c14-95ef-7b65cbfe7edb)

**Comment by SantiagoCalebe** [comment]
Name::Image::Credits::Website::[Hex Color]

**Comment by DavesTheBone** [comment]
k
