### ISSUE TITLE
ICON COLOR BUTTON CRASHES THE GAME

### ISSUE THREAD

**Issue by Rom4chek** [ShadowMario/FNF-PsychEngine#15550]
### Describe your bug here.

So if you go to CharacterEditor from playstate and getting color from icon it giving you this error
However it doesnt happen when you going from EditorMenu instead
![изображение_2024-09-18_181119665](https://github.com/user-attachments/assets/ad7ce49f-944c-49d7-ba5a-ec46b823f753)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, last action build

**Comment by ShadowMario** [comment]
Should be fixed
