### ISSUE TITLE
Possible make gradient makegraphic()?

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#15557]
### Describe your problem here.

can i make this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Stefan2008Git** [comment]
No until if you modfiy FunkinLua.hx on source code for that

**Comment by MaksPRO12667** [comment]
> No until if you modfiy FunkinLua.hx on source code for that

fuk... ok
