### ISSUE TITLE
How do I make the zoom change depending on the character that focuses after a specific moment in the song? 

### ISSUE THREAD

**Issue by Mrmandarina253** [ShadowMario/FNF-PsychEngine#15554]
### Describe your problem here.

I've looked everywhere and I only got a code that works perfectly but I need it to activate at a specific time and I don't know how

this is btw

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by HourOfEternity** [comment]
From what I've seen done, you can use something like:
function onMoveCamera(focus)
     runHaxeCode([[
          {
               if(focus  == 'yourCharacter' && curBeat == 'currentBeat')
               game.defaultCamZoom = 0.625;
               elseif(focus =='yourCharacter' && curBeat != 'currentBeat')
               game.defaultCamZoom = 0.6;
               else
               game.defaultCamZoom = 0.5;
          }
     ]])
end

Hope this helps!
