### ISSUE TITLE
How to solve problem in command prompt?

### ISSUE THREAD

**Issue by ItzEpicstickman** [ShadowMario/FNF-PsychEngine#1555]
### Describe your problem here.

whenever i start to compile the game it says "source/MainMenuState.hx:57: characters 27-34 : Class<ClientPrefs> has no field copyKey
source/MainMenuState.hx:237: characters 42-55 : Type not found : ModsMenuState
source/MainMenuState.hx:243: characters 42-62 : Type not found : options.OptionsState"
I Even tried to replace the problem by deleting the code in 'mainmenustate' and paste the code again (copied from the source code) in the hx file.
please help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by DaBanana64** [comment]
It has been fixed.
