### ISSUE TITLE
script to read the contents of a json file

### ISSUE THREAD

**Issue by Shiho-cmd** [ShadowMario/FNF-PsychEngine#15565]
### Describe your problem here.

basically i want to make a script in haxe to create a global callback to get a content of a json file and use this callback in lua scripts (not using the source code just a psych mod pack)
something like: "getJsonContent('path of the json file', 'content to get')"

i tried myself sometimes but i really don't know what i'm doing i suck at haxe XD
so if that is even possible i would really appreciate the help thanks!!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by LarryFrosty** [comment]
You can do this with callMethodFromClass.
```lua
function parseJson(file)
    return callMethodFromClass('tjson.TJSON', 'parse', {getTextFromFile(file)})
end

local parsed = parseJson('file.json')
```

**Comment by Shiho-cmd** [comment]
> You can do this with callMethodFromClass.
> 
> ```lua
> function parseJson(file)
>     return callMethodFromClass('tjson.TJSON', 'parse', {getTextFromFile(file)})
> end
> 
> local parsed = parseJson('file.json')
> -- returns a table dictionary containing
> -- the variable names and values
> -- parsed.var
> ```

i tried and it gives me this error:
![image](https://github.com/user-attachments/assets/2f5cf8c6-3723-4b01-8739-1020734b1b05)

**Comment by Shiho-cmd** [comment]
> > You can do this with callMethodFromClass.
> > ```lua
> > function parseJson(file)
> >     return callMethodFromClass('tjson.TJSON', 'parse', {getTextFromFile(file)})
> > end
> > 
> > local parsed = parseJson('file.json')
> > -- returns a table dictionary containing
> > -- the variable names and values
> > -- parsed.var
> > ```
> 
> i tried and it gives me this error: ![image](https://private-user-images.githubusercontent.com/146484710/369735797-2f5cf8c6-3723-4b01-8739-1020734b1b05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMjMyNzcsIm5iZiI6MTcyNzIyMjk3NywicGF0aCI6Ii8xNDY0ODQ3MTAvMzY5NzM1Nzk3LTJmNWNmOGM2LTM3MjMtNGIwMS04NzM5LTEwMjA3MzRiMWIwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwMDA5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjgzYTE2OGNiNzYyOGI2YTUxNGNlMWZkNDk3YzczYTIxNjgzYTIwZmNhNjdhODQ4MDI5NmYwYzc5Njk0MDA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D6uq9q5Ml6bI_PdgL06bV6W3fJPjPFy3YO561loVIzU) the erro is coming from the "local parsed = parseJson('file.json')" btw

I finally understood what i was doing wrong sorry lol i will close this issue now anyways thank you mate!!!!
