### ISSUE TITLE
How to make custom logo

### ISSUE THREAD

**Issue by DavesTheBone** [ShadowMario/FNF-PsychEngine#15563]
### how to make main menu custum logo animation like this.

![logoBumpin](https://github.com/user-attachments/assets/2ff2552d-de66-4d55-aceb-f6b7980037d6)

### i use this [XML sprite generator](https://github.com/UncertainProd/FnF-Spritesheet-and-XML-Maker)

![XML Generator 2024_09_22 12_45_04](https://github.com/user-attachments/assets/3e75c1e9-de4e-436e-abf2-66dfc8533050)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MrRainbowCoding** [comment]
Can you send me your XML and Spritesheet so I can fix it for you?

**Comment by DavesTheBone** [comment]
ok
(sorry my google drive broken)
![000](https://github.com/user-attachments/assets/37bf7d74-d9f7-46c6-a1fe-e7e7db9acf11)
![001](https://github.com/user-attachments/assets/ea45e82f-96bb-45c4-8cb3-f2b6cf46d2ee)
![002](https://github.com/user-attachments/assets/6e6b0146-17ac-4b63-9ac7-890c3b4aeff7)
![003](https://github.com/user-attachments/assets/3ebba641-10b3-4970-b00f-99974ad63497)
