### ISSUE TITLE
Built in mod downloader

### ISSUE THREAD

**Issue by Jejear** [ShadowMario/FNF-PsychEngine#15567]
### What feature do you want to get added on the **base** engine?

So I really want the built in mod downloader from psych engine online to normal psych engine people say it’s in the source code but I don’t know what to do with the source code.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by CrusherNotDrip** [comment]
> Proper credit that was forgotten

Failed reliability test
