### ISSUE TITLE
0.6.3 Expression problem

### ISSUE THREAD

**Issue by Arthur12YT** [ShadowMario/FNF-PsychEngine#15570]
### Describe your bug here.

i was trying to compile the source, some errors appeared and i could fix them, until i got to the one where
source/Achievements.hx:132: characters 3-71 : (camera : flixel.FlxCamera, value : Bool) -> Void should be Array<flixel.FlxCamera>
i did what they mean, but then another error appeared: "Expected expression"

heres the line: var cam;Array<flixel.FlxCamera> = FlxG.cameras.setDefaultDrawTarget;
the = is the problem

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i only changed FlxG.cameras.defaultCameras; to FlxG.cameras.setDefaultDrawTarget;  thats it

**Comment by CrusherNotDrip** [comment]
0.6.3 isn't supported anymore

**Comment by Arthur12YT** [comment]
oh.
