### ISSUE TITLE
Problem while bulding Psych Engine 0.7.3: C:/HaxeToolkit/haxe/lib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available.

### ISSUE THREAD

**Issue by Lsupergame** [ShadowMario/FNF-PsychEngine#15574]
### Describe your problem here.

I was trying to build psych engine for the first time, but wasnt able to, after instaling everything, i still get the error message of "C:/HaxeToolkit/haxe/lib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available" and i dont know why it happens since i do have SScript.
I tried running "build_x64.bat" in the art folder, but it just gives me a psych engine folder without PsychEngine.exe.
What do i do?
![Screenshot 2024-09-23 181542](https://github.com/user-attachments/assets/99929267-dc57-4e4b-bc04-d77977cad954)
![Screenshot 2024-09-23 181556](https://github.com/user-attachments/assets/fb68810f-b62f-4fbf-9c6f-67a703299b4b)
![Screenshot 2024-09-23 181613](https://github.com/user-attachments/assets/1616eeb2-c239-490d-8156-c504ec518b28)
![Screenshot 2024-09-23 181639](https://github.com/user-attachments/assets/1bd30733-bec5-472d-8f30-bdae75c265d2)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i havent edited anything

**Comment by a-random441** [comment]
https://github.com/CobaltBar/SScript-Archive

look at the instructions

**Comment by Lsupergame** [comment]
> https://github.com/CobaltBar/SScript-Archive
> 
> look at the instructions (use sscript 7.7.0 ur using pe 0.7.3)

I tried going to the site and specifically downloading that version, then i took the files and put them in the "HaxeToolkit\haxe\lib\SScript\7,7,0" directory, and i also tried to look at other people having my same problem, and now the error is different, it says "Error: Could not find haxelib "SScript", does it need to be installed?" and also i dont understand whats worng with my version since it says i have the "SScript: 7.7.0 [21.0.0] git"
![Screenshot 2024-09-24 143731](https://github.com/user-attachments/assets/232490bc-fa36-4ad2-b0c9-ecbb5c560ae0)
![Screenshot 2024-09-24 143844](https://github.com/user-attachments/assets/98f1c1ff-e539-48d5-b2e6-77a9d39e2c3d)

**Comment by a-random441** [comment]
Remove SScript, I think you're doing the process wrong.
put the zip in the same path your in.

input this in cmd:
haxelib install "replace-this-with-zip-name.zip"

**Comment by Lsupergame** [comment]
> Remove SScript, I think you're doing the process wrong. put the zip in the same path your in.
> 
> input this in cmd:
> 
> ```batchfile
> haxelib install "SScript-7,7,0.zip"
> ```
> 
> and the reason why u got
> 
> ```batchfile
> Error: Failed with error: No such Project: SScript-7,7,0.zip
> ```
> 
> is because you didn't add the " " around the file name.

As you can see in the screenshot, i did what you said and it technically worked, but when i did the lime test it still says the same thing, i dont know what im doing wrong.
![Screenshot 2024-09-25 130106](https://github.com/user-attachments/assets/b31af07e-c4c6-4bb3-9f7d-f071d862f847)
![Screenshot 2024-09-25 130210](https://github.com/user-attachments/assets/366dd7ce-3912-4689-b63a-76555e0f171a)

**Comment by a-random441** [comment]
Remove SScript Again and do it again

**Comment by ShadowMario** [comment]
Already fixed in Experimental build

**Comment by dreup** [comment]
does anyone know how to install this?
![Image](https://github.com/user-attachments/assets/1d24053e-062a-41bb-bd0d-47393c471766)
