### ISSUE TITLE
Stage Editor "Duplicate" button results in a crash

### ISSUE THREAD

**Issue by verecundius** [ShadowMario/FNF-PsychEngine#15578]
### Describe your bug here.

Title is pretty telling already, wouldnt you say?

Simply put, each time I press the "Duplicate" button in the stage editor, it results in a crash.

### Command Prompt/Terminal logs (if existing)

```bash
states/editors/StageEditorState.hx (line 395)
backend/ui/PsychUIButton.hx (line 93)
flixel/group/FlxGroup.hx (line 151)
flixel/group/FlxSpriteGroup.hx (line 209)
backend/ui/PsychUITab.hx (line 48)
backend/ui/PsychUIBox.hx (line 166)
flixel/group/FlxGroup.hx (line 151)
backend/MusicBeatState.hx (line 83)
states/editors/StageEditorState.hx (line 1335)
flixel/FlxState.hx (line 239)
flixel/FlxGame.hx (line 749)
flixel/FlxGame.hx (line 679)
flixel/FlxGame.hx (line 558)
openfl/events/EventDispatcher.hx (line 426)
openfl/display/DisplayObject.hx (line 1398)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I allowed video functionality and added base game files

**Comment by ShadowMario** [comment]
Should be fixed in the latest commit
