### ISSUE TITLE
last section's notes getting put into the next section's

### ISSUE THREAD

**Issue by GarfieldGlitch** [ShadowMario/FNF-PsychEngine#15577]
### Describe your bug here.

![image](https://github.com/user-attachments/assets/84d3b9e7-df95-40aa-98f3-5e8c8f3b7688)
as you can see, the last sections notes are being put into the next section. you can remove them by clicking on it but then you have to put it back where it previously was, which is quite tedious. if anybody has a fix to this that'd be greatly appreciated
i'm using the latest version of psych engine*

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

charting and song files

**Comment by ShadowMario** [comment]
Very unlikely an issue now because the Chart Editor got completely rewritten in 1.0-prerelease, if it is still an issue however, please make a new issue
