### ISSUE TITLE
how do i fix this???

### ISSUE THREAD

**Issue by anunusualname** [ShadowMario/FNF-PsychEngine#15571]
### Describe your bug here.

states/FreeplayState.hx (line 72)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 444)
openfl/display/DisplayObject.hx (line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by SantiagoCalebe** [comment]
Explain what you did before the bug.
