### ISSUE TITLE
Can you use (FlxTrail) with LUA?

### ISSUE THREAD

**Issue by GMan2006i** [ShadowMario/FNF-PsychEngine#1558]
### Describe your problem here.

pretty self explanatory

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by ShadowMario** [comment]
No.

**Comment by GMan2006i** [comment]
:( sad

**Comment by GMan2006i** [comment]
@ShadowMario could this be a possible feature in a future update?
