### ISSUE TITLE
how to randomize menu backgrounds in psych engine 0.7.3

### ISSUE THREAD

**Issue by Lillofrost2010** [ShadowMario/FNF-PsychEngine#15586]
### Describe your problem here.

how do i randomize menu backgrounds like in dave and bambi in psych engine 0.7.3 source code?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by youyou1603** [comment]
1- Create music in **Ogg format** (if it is **MP3**, change it from the program or from the Internet)
2- Then name it to **freakyMenu.ogg** (it is recommended to do it **outside the engine files**)
3- Copy the target music and go to **FNF-PsychEngine-0.7.3\export\debug or release or X32\windows\bin\assets\shared\music**
4- Paste and replace the file
5- Test the game
Note:
If there is **no music** and you see that the intro has a bug, this means that the music was not **converted to OGG format in the required way.**
Enjoy.

**Comment by Lillofrost2010** [comment]
> That might not be something using Lua or JSON. It could be that they modified the actual Haxe code. IDK because I haven't played it. You could check out GameBanana for some resources. They have tools and scripts you can use that are available for free. Some creators of popular mods even link their source code in the mod's page that goes to a GitHub repo.

Yes there is one but its for psych engine 0.4.0, i tried it and it doesnt work with psych engine 0.7.3 so idk what to do now

**Comment by Lillofrost2010** [comment]
> Do you have to use the latest version? You can still compile 0.4 source code still. If you'd like to know I can tell you.

No i think that 0.4 is too outdated, but i could use strident crisis or bambis purgatory engine , its not that outdated, but for the mod i wanted to make (its gonna be a mod about all the scrapped golden apple songs) i could just not modify the menu that much tbh.

**Comment by Lillofrost2010** [comment]
> > > Do you have to use the latest version? You can still compile 0.4 source code still. If you'd like to know I can tell you.
> > 
> > No i think that 0.4 is too outdated, but i could use strident crisis or bambis purgatory engine , its not that outdated, but for the mod i wanted to make (its gonna be a mod about all the scrapped golden apple songs) i could just not modify the menu that much tbh.
> 
> Wow didn't expect that fast of a reply 😅. You could use GameBanana to create discussions to find other people who have found solutions to this.

Ok, i will see what to do then by asking on gamebanana
