### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by chicken-nugget1104** [ShadowMario/FNF-PsychEngine#15584]
### Describe your problem here.

CANT BUILD SOURCE CUZ MAIN IS GIVE ERROR
LINE AT 85
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'

HERE IS LINE 85
		addChild(new FlxGame(gameWidth, gameHeight, initialState, zoom, framerate, skipSplash, startFullscreen));
		
I AM USE 0.6.2 PLEASE HELP

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by SamuXDD** [comment]
haxelib remove flixel
haxelib install flixel 4.11.0
haxelib remove flixel-addons
haxelib install flixel-addons 2.11.0
haxelib remove flixel-ui
haxelib install flixel-ui 2.4.0
