### ISSUE TITLE
A spanish file

### ISSUE THREAD

**Issue by User79372893** [ShadowMario/FNF-PsychEngine#15597]
### What feature do you want to get added on the **base** engine?

[es-ES.zip](https://github.com/user-attachments/files/17172684/es-ES.zip)
I am Hispanic, I use the translator to write this, I had the idea of ​​translating the entire game into Spanish, it took me approximately 30 minutes, I hope you take my idea into account and translate the game for Hispanics who do not speak the gringo language 😅

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by M4st3rG4m4** [comment]
oye tu! primero que nada me imagino que creaste ese lang para la 1.0-pre cierto?, debes saber que hay un grupo de personas que se estan encargando de hacer un lang mejor trabajado que el que has hecho (del cual no me puedo quejar sabiendo que fue hecho con un traductor).

De cualquier manera en la v1.0 habra forma de importar langs como el que hiciste al juego (que ya se puede hacer en la 1.0-pre) pero prefiero esperar a que la build oficial este lista

**Comment by User79372893** [comment]
Oh, ya veo, gracias por la información 😅

**Comment by M4st3rG4m4** [comment]
> Oh, ya veo, gracias por la información 😅

De nada, si eso era todo por favor cierra este issue
