### ISSUE TITLE
How can i make it so an image flashes on the screen when i miss a note?

### ISSUE THREAD

**Issue by MugMiles** [ShadowMario/FNF-PsychEngine#15593]
### Describe your problem here.

As the title says. I want to make it so a vignette surrounds the screen when you miss a note so appreciateit looks like you're taking damage. However, I don't know how I would code that, but I would apprciate it if someone could walk me through it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by BoomLingReady** [comment]
Image Must Be 1280x720px
Image Must Be In Your Mods Image Folder
LUA Code Must Be In Your Song's Chart Folder (Data > Your Song)
`function ImageFlash()
cancelTween('Flash')
makeLuaSprite('thecoolsprite', 'yourcustompnglol', 0, 0)
setObjectCamera('thecoolsprite', 'other')
addLuaSprite('thecoolsprite', true)
doTweenAlpha('Flash', 'thecoolsprite', 0, 0.5)
end

function noteMiss()
ImageFlash()
end

function noteMissPress()
ImageFlash()
end`
