### ISSUE TITLE
Some useful things that yall could add the game

### ISSUE THREAD

**Issue by Lillofrost2010** [ShadowMario/FNF-PsychEngine#15594]
### What feature do you want to get added on the **base** engine?

Now these ideas are kinda unoriginal but it would be useful if yall added a change stage event, a change notes event, a modchart editor, and lastly a menu editor(not really because idk if yall can make lua work with the main menu)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons

**Comment by M4st3rG4m4** [comment]
Almost all the things you said can be done in lua/hscript without modding source, and menus can be modded via source so...

**Comment by ShadowMario** [comment]
Absurd lazyness with all those editors, plus everything you just said (Except "Change Notes" event, whatever it means) was already requested and rejected
