### ISSUE TITLE
Help TeaCall error

### ISSUE THREAD

**Issue by Cistooo0** [ShadowMario/FNF-PsychEngine#15595]
### Describe your problem here.

I have all the latest versions of the scripts and i keep getting teacall error, when i change all instances of it to Tea it just replaces the error with tea and i can find a solution to it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by SantiagoCalebe** [comment]
Change 'TeaCall' to 'Tea'

**Comment by Cistooo0** [comment]
> Change 'TeaCall' to 'Tea'

i said that didnt work

**Comment by SantiagoCalebe** [comment]
What's the version of the Psych Engine's Source Code?

**Comment by SantiagoCalebe** [comment]
Close the issue
