### ISSUE TITLE
How Add Rating If Have Botplay On

### ISSUE THREAD

**Issue by X1solovssquad1** [ShadowMario/FNF-PsychEngine#15592]
### Describe your bug here.

How Add Rating If Have Botplay On
![142177505-54e64985-2ff4-4e9d-b3fc-24b8e6084bc3](https://github.com/user-attachments/assets/a8387d40-c7fe-4f81-b345-478d923aeeec)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by M4st3rG4m4** [comment]
first of all this isn't a bug and second you wanna cheat right?

**Comment by X1solovssquad1** [comment]
[M4st3rG4m4](https://github.com/M4st3rG4m4) I would like to know how to do it

**Comment by SantiagoCalebe** [comment]
I know that you wanna cheat, go play, don't cheat.

https://gamebanana.com/tools/13669

**Comment by X1solovssquad1** [comment]
I wanted a mod that looks more normal
