### ISSUE TITLE
If i try to do lime test thay say that i have do sscript installed how to fix that?

### ISSUE THREAD

**Issue by DuckkFnF** [ShadowMario/FNF-PsychEngine#15599]
### Describe your problem here.

 ERROR  C:/HaxeToolkit/haxe/lib/SScript/19,0,618/src/macro/Macro.hx:10: characters 96-100

 10 |   Context.fatalError('SScript is not available, thanks to everyone for their support.', (macro null).pos);
    |                                                                                                ^^^^
    | SScript is not available, thanks to everyone for their support.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes

**Comment by LarryFrosty** [comment]
The SScript library has pretty much been deleted, replacing every version with a macro that throws an error

To still compile, you can use this SScript archive with working libraries: https://github.com/CobaltBar/SScript-Archive
