### ISSUE TITLE
How to make playable animations?

### ISSUE THREAD

**Issue by ZeroZen0410** [ShadowMario/FNF-PsychEngine#15608]
### Describe your problem here.

Hello, I know you can make videos appear in-game over the HUD, but it makes the game unplayable unless you've already memorized the notes. How do you play a video in-game while being able to see the notes and HUD at the same time?
(also, yes, I know [this](https://gamebanana.com/mods/426880) exists, it doesn't work in 0.7.1h as of now) and yes, this was copy and pasted since the answer was hidden later

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JHAM25** [comment]
Pues yo hago esto no se si te sirve:

function onCreate()

startVideo('gunsCutscene')
    runHaxeCode([[
        FlxG.cameras.add(game.camHUD, false);
		FlxG.cameras.add(game.camOther, false);
    ]])
setProperty('inCutscene', false)
end
function onUpdate()
    

end


https://github.com/user-attachments/assets/1edc2f8a-fec4-4021-a0b5-7980bffcb2ae
