### ISSUE TITLE
wallpaper changing in lua

### ISSUE THREAD

**Issue by Cee-Jay0900** [ShadowMario/FNF-PsychEngine#15605]
### What is your question?

How to hange wallpaper in lua like in paranoia or NMI

**Comment by SantiagoCalebe** [comment]
bruh stop trying to create malware

**Comment by SantiagoCalebe** [comment]
But now being serious, i don't see a way for doing that on Lua, just in Source.

**Comment by SantiagoCalebe** [comment]
or rob Paranoia's code
