### ISSUE TITLE
Why is my script not working???

### ISSUE THREAD

**Issue by m4ttzzzz** [ShadowMario/FNF-PsychEngine#15606]
### Describe your problem here.

This script isn't working, what did I do wrong?

```
local delimiter = " | "
local totalOfNotes = 0


function hideTime()
   setProperty('timeBarBG.visible', false)
   setProperty('timeBar.visible', false)
   setProperty('timeTxt.visible', false)
end

function onCreatePost()
   setProperty('scoreTxt.visible', false)
   hideTime() -- hides the timebar
   local x = getProperty('scoreTxt.x')
   local y = getProperty('scoreTxt.y')
   makeLuaText("scoreText", "", 1280, x, y)
   setTextSize("scoreText", 18)
   addLuaText("scoreText")
   for i=0, getProperty('unspawnNotes.length')-1 do
       if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
           if not getPropertyFromGroup('unspawnNotes', i, 'isSustainNote') then
              totalOfNotes = totalOfNotes + 1
           end
       end
   end
end


function onBeatHit()
   scaleObject('iconP1', 1, 1)
   scaleObject('iconP2', 1, 1)
end


function goodNoteHitPre(isSustainNote)
   if isSustainNote then
      addScore(35) -- Ignore this, I was trying to replicate the base game's scoring system
   end
end

function onUpdate()
   local Hitsperc = (hits / totalOfNotes) * 100
   local txt = "Score: " .. score .. delimiter .. "Misses: " .. noteMisses .. delimiter .. "Hits: " ..hits .. " / " .. totalOfNotes .. " (" .. Hitsperc.. "%)"
   setTextString("scoreText", "test")
end
```
Edit: The text is created successfully, but it doesnt update???

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't edit anything.

**Comment by LarryFrosty** [comment]
> You're not using global variables. I don't know how this works in lua but I'm pretty sure the functions are trying to use local variables instead, which don't exist giving them the value of nil.

That only applies to local variables declared INSIDE of blocks.
The variables here are declared outside which means any function can use them

**Comment by LarryFrosty** [comment]
Btw, the object is "scoreTxt", not "scoreText".

**Comment by LarryFrosty** [comment]
Change "noteMisses" to "misses"

**Comment by m4ttzzzz** [comment]
> Change "noteMisses" to "misses" Probably doesn't update because you are trying to concate a null variable You can see errors by having
> 
> ```lua
> luaDebugMode = true
> ```
> 
> at the top of your script

Ahh thanks, didn't see it :D
