### ISSUE TITLE
my custom chart wont load

### ISSUE THREAD

**Issue by zomehz** [ShadowMario/FNF-PsychEngine#15603]
### Describe your bug here.

I've been trying to make a fnf mod and made a chart but when ever I try to load the chart into chart editor, it says "assets/data/shared/____/____.json.
I've searched up what to do but couldn't find anything. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SantiagoCalebe** [comment]
The name of the folder and the name of the chart have to be the same.

**Comment by zomehz** [comment]
K ill see

**Comment by zomehz** [comment]
> The name of the folder and the name of the chart have to be the same.
> 
> Songname/Songname-hard.json

I check and its already like that

**Comment by SantiagoCalebe** [comment]
Is the error: Assets/Shared/Songname.json

or

Mods/Data/Songname.json

?

**Comment by zomehz** [comment]
Its okay i found out how to tix ot
