### ISSUE TITLE
Stages in HScript 

### ISSUE THREAD

**Issue by JuanSebas1247** [ShadowMario/FNF-PsychEngine#15602]
### Describe your problem here.

It's my first code in hx (HScript) and I haven't been able to add an animated image,
(ignore the white box, it is being loaded by a Lua)
![Screenshot_20240928-084058](https://github.com/user-attachments/assets/de9b5873-191f-4a3a-b501-3c5a5b87743e)
![Screenshot_20240928-084111](https://github.com/user-attachments/assets/5e269876-73fd-401f-9224-3fe5ac65206a)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JuanSebas1247** [comment]
In the hx I didn't change the value of add but I just tried fixing it and it still doesn't work

**Comment by TheRealJake12** [comment]
you're adding a bad variable (santa doesn't exist!)
you gotta like, define the variables THEN add them
so like
```haxe
var sprite1 = new BGSprite('Stages/Think/Phase1/Assets', -840, 0);
add(sprite1);
```
I don't know how BGSprite works but I think that's how it works

**Comment by CrusherNotDrip** [comment]
you dont use package and class in psych hscript

**Comment by JuanSebas1247** [comment]
![Screenshot_20240930-115038.jpg](https://github.com/user-attachments/assets/26832881-04e5-40e9-b847-3cb5a8af2229)

![Screenshot_20240930-114943.jpg](https://github.com/user-attachments/assets/6cabc943-6993-4658-96c4-a4c31b3e60ea)

Igual sale el mismo error

**Comment by JuanSebas1247** [comment]
The same error still appears

**Comment by CrusherNotDrip** [comment]
> you dont use package and class in psych hscript

:0

**Comment by KELOTOMU** [comment]
Use the Template.hx as ur template

**Comment by JuanSebas1247** [comment]
I was able to do it thanks

**Comment by JuanSebas1247** [comment]
I was able to do it thanks
