### ISSUE TITLE
Lime has nodejs, webassembly, and npm support now. Web build pls?

### ISSUE THREAD

**Issue by TooManyFactoryResets** [ShadowMario/FNF-PsychEngine#15612]
### What feature do you want to get added on the **base** engine?

I want to build a website that hosts this engine. I know html5 itself is not supported but I was wondering if these platforms could be supported:
```bash
lime build nodejs
lime build emscripten
lime build html5 -npm
```
I hope that these platforms could create more support for a web build. The emscripten build requires [Emscripten SDK](https://emscripten.org/docs/getting_started/downloads.html) to be installed and on path using `lime build emscripten -DEMSCRIPTEN_SDK=/path/to/folder/`.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
No intention on adding Browser support again as it tends to hinder the Desktop build.
