### ISSUE TITLE
Type not found: Teacall

### ISSUE THREAD

**Issue by Undecillion0** [ShadowMario/FNF-PsychEngine#15617]
### Describe your bug here.

Okay so I have installed all dependecies correct including SScript and every time I try to build it will say Hscript:317 Type not found: Teacall. I have already tried installing either SScript versions and tried changing Teacall to Tea multiple times.

![image](https://github.com/user-attachments/assets/46dc6861-7cbc-4f0e-9b13-4e1428981f16)

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\undec\OneDrive\Desktop\nf\my-shit\FNF-PsychEngine-main>lime test windows
source/psychlua/HScript.hx:317: characters 89-92 : Type not found : Tea

C:\Users\undec\OneDrive\Desktop\nf\my-shit\FNF-PsychEngine-main>
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by SantiagoCalebe** [comment]
Change 'tea' to teacall

**Comment by Undecillion0** [comment]
> Change 'tea' to teacall

Ive tried both and they do not work
