### ISSUE TITLE
removeHScript crashing game when song ends

### ISSUE THREAD

**Issue by BobbyDrawz** [ShadowMario/FNF-PsychEngine#15611]
### Describe your bug here.

shit keeps crashing my game when a song ends, i want it to work the way it did in 0.7.3.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I went into mods folder and added 2 complicated hx scripts, tryna choose one to remove based on character, but never works.

**Comment by ShadowMario** [comment]
Send code for me to test

**Comment by BobbyDrawz** [comment]
> Send code for me to test

this shit is old, u can close this
