### ISSUE TITLE
New to using source code. How do I make this main menu idea?

### ISSUE THREAD

**Issue by ClvrrCleaver** [ShadowMario/FNF-PsychEngine#15614]
### Describe your problem here.

Me and my friend are making a mod and I decided to start trying to learn a bit of code for it and so far I've got something pretty good but I wanted to make it so that story mode is in the middle and the others aren't on screen so when you press up or down story mode will scroll up or down and the next option would come from the opposite side. I don't know how complex this is and honestly I don't even know where to begin so if anyone could help me with this I'd really appreciate it!
I attached some images to try to better describe what we want and what I've made so far.
![fnf](https://github.com/user-attachments/assets/57be8adb-ecd1-494c-ad6d-49ef1500c81b)

and here is a concept I made for how I want it to work:

![gif](https://github.com/user-attachments/assets/8394f4d3-3c4c-4217-95bc-3dbb90193001)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I replaced the menu and game over music and have edited the menu as what you can see in the attached image as well as adding my own week, songs and characters.

**Comment by baobab121** [comment]
change positions of buttons and move them with FlxTween

**Comment by ClvrrCleaver** [comment]
> change positions of buttons and move them with FlxTween

how do I do that I still don't really understand most of this code

**Comment by liamp0924** [comment]
to do this menu concept go into the main menu state in the source code and change the order of the buttons, but first we need to remove the c
![hhsthszdh](https://github.com/user-attachments/assets/3e94ccdb-b9ce-4e8d-b737-fb234de3eeeb)
redits option (this is not required im just assuming that you need to) to do this just comment the line 40 in main menu state or delete it, now, to change the order of the buttons just look at this image that shows how the code should look

**Comment by ClvrrCleaver** [comment]
> to do this menu concept go into the main menu state in the source code and change the order of the buttons, but first we need to remove the credits option (this is not required im just assuming that you need to) to do this just comment the line 40 in main menu state or delete it, now, to change the order of the buttons just look at this image that shows how the code should look

I'm sorry but I think you may not have understood what my problem is since the order isn't what I wanted to change... I updated the image with a gif to attempt to better explain what I'm trying to make, thank you anyway
