### ISSUE TITLE
how to make custom stage?

### ISSUE THREAD

**Issue by DavesTheBone** [ShadowMario/FNF-PsychEngine#15616]
### What is your question?

The image itself is ready.
It says to put lua and json in `my-mods/stages`, but what code do I need to write?
I'm using the Downloaded Build

**Comment by baobab121** [comment]
just use lua script api for .lua file and you can take the dad stage json file (assets/shared/stages/stage.json) and just edit it as you need. also name the .lua and .json files the same (yourstage.json, yourstage.lua)

**Comment by SantiagoCalebe** [comment]
Use LuaScript API

or

LUA

```
function onCreate()
	makeLuaSprite('Asset Name', 'File Name', −700, −150); 
	setScrollFactor('Asset Name', 1, 1); 
	scaleObject('Asset Name', 1, 1); 

	addLuaSprite('Asset Name', false); 
	close(true);
end

```
JSON

```
{
	"directory": "",
	"defaultZoom": 1,
	"stageUI": "",

	"boyfriend": [1150, 250],
	"girlfriend": [40, 10],
	"opponent": [200, 250],
	"hide_girlfriend": false,
}
```

**Comment by DavesTheBone** [comment]
> Use LuaScript API
> 
> or
> 
> LUA
> 
> ```
> function onCreate()
> 	makeLuaSprite('Asset Name', 'File Name', −700, −150); 
> 	setScrollFactor('Asset Name', 1, 1); 
> 	scaleObject('Asset Name', 1, 1); 
> 
> 	addLuaSprite('Asset Name', false); 
> 	close(true);
> end
> ```
> 
> JSON
> 
> ```
> {
> 	"directory": "",
> 	"defaultZoom": 1,
> 	"stageUI": "",
> 
> 	"boyfriend": [1150, 250],
> 	"girlfriend": [40, 10],
> 	"opponent": [200, 250],
> 	"hide_girlfriend": false,
> }
> ```

YOOOOOO THANK YOUUUUUUU

**Comment by DavesTheBone** [comment]
> Use LuaScript API
> 
> or
> 
> LUA
> 
> ```
> function onCreate()
> 	makeLuaSprite('Asset Name', 'File Name', −700, −150); 
> 	setScrollFactor('Asset Name', 1, 1); 
> 	scaleObject('Asset Name', 1, 1); 
> 
> 	addLuaSprite('Asset Name', false); 
> 	close(true);
> end
> ```
> 
> JSON
> 
> ```
> {
> 	"directory": "",
> 	"defaultZoom": 1,
> 	"stageUI": "",
> 
> 	"boyfriend": [1150, 250],
> 	"girlfriend": [40, 10],
> 	"opponent": [200, 250],
> 	"hide_girlfriend": false,
> }
> ```

YOOOO THX BRO
Sure! Here's your sentence translated into English:
I'm sorry, I forgot, but could you teach me how to make background animations?

**Comment by baobab121** [comment]
if you have spritesheet and .xml file then
```
function onCreate() 	
        makeAnimatedLuaSprite('Asset Name', 'File Name', −700, −150);
        addAnimationByPrefix('Asset Name', 'Animation Name', 'Animation Prefix in .xml file', 24, true)
        setScrollFactor('Asset Name', 1, 1); 
        scaleObject('Asset Name', 1, 1); 	

        addLuaSprite('Asset Name', false); 	
        close(true); 
end 

```

**Comment by SantiagoCalebe** [comment]
> if you have spritesheet and .xml file then
> 
> ```
> function onCreate() 	
>         makeAnimatedLuaSprite('Asset Name', 'File Name', −700, −150);
>         addAnimationByPrefix('Asset Name', 'Animation Name', 'Animation Prefix in .xml file', 24, true)
>         setScrollFactor('Asset Name', 1, 1); 
>         scaleObject('Asset Name', 1, 1); 	
> 
>         addLuaSprite('Asset Name', false); 	
>         close(true); 
> end 
> ```

Is this, you use XML and Spritesheet generator and give the name of BG, in the asset name, you put 'BG' and in the file name, your file name, and in the animation name, put the animation name, use bg. @baobab121

**Comment by SantiagoCalebe** [comment]
> > Use LuaScript API
> > or
> > LUA
> > ```
> > function onCreate()
> > 	makeLuaSprite('Asset Name', 'File Name', −700, −150); 
> > 	setScrollFactor('Asset Name', 1, 1); 
> > 	scaleObject('Asset Name', 1, 1); 
> > 
> > 	addLuaSprite('Asset Name', false); 
> > 	close(true);
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > JSON
> > ```
> > {
> > 	"directory": "",
> > 	"defaultZoom": 1,
> > 	"stageUI": "",
> > 
> > 	"boyfriend": [1150, 250],
> > 	"girlfriend": [40, 10],
> > 	"opponent": [200, 250],
> > 	"hide_girlfriend": false,
> > }
> > ```
> 
> YOOOO THX BRO I'm sorry, I forgot, but could you teach me how to make background animations?

You are welcome <3
