### ISSUE TITLE
1.0 prerelease compile error with SScript

### ISSUE THREAD

**Issue by vmakzfmak** [ShadowMario/FNF-PsychEngine#15618]
### Describe your bug here.

Refer to the Terminal log. How should I fix that?

### Command Prompt/Terminal logs (if existing)

```bash
BUILDING GAME
 ERROR  C:/Users/nam-c/haxelib/SScript/19,0,618/src/macro/Macro.hx:10: characters 96-100

 10 |   Context.fatalError('SScript is not available, thanks to everyone for their support.', (macro null).pos);
    |                                                                                                ^^^^
    | SScript is not available, thanks to everyone for their support.


done.
계속하려면 아무 키나 누르십시오 . . .
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Undecillion0** [comment]
This is an easy fix just do `haxelib git SScript https://github.com/SScript-Guy/SScript-new`

**Comment by vmakzfmak** [comment]
Well... Same error occurs.

**Comment by vmakzfmak** [comment]
> 이것은 그냥 쉽게 고칠 수 있습니다. `haxelib git SScript https://github.com/SScript-Guy/SScript-new`

Well... Same error occurs.

**Comment by vmakzfmak** [comment]
> This is an easy fix just do `haxelib git SScript https://github.com/SScript-Guy/SScript-new`

Well... Same error occurs.

**Comment by ShadowMario** [comment]
Use the newest commits

**Comment by imamario** [comment]
NEWEST COMMISTS FROM WHATT!???
