### ISSUE TITLE
Vocal weird buggy tremolo effect

### ISSUE THREAD

**Issue by legacy4j** [ShadowMario/FNF-PsychEngine#15629]
### Describe your problem here.

You can hear what I mean here in this file (audio only, video not needed):
https://github.com/user-attachments/assets/3cc89984-12a4-4039-a930-caf8aea7a557
I believe it's always just the first thing I play after I launch the game, it always fixes itself after restarting song
I don't know if this is an engine error, or something I did
No other mods installed, just my one

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
Is this in 0.7.3?

**Comment by M4st3rG4m4** [comment]
It happened to me sometimes with the music player in 0.7.3

**Comment by legacy4j** [comment]
Yes im on 0.7.3

**Comment by legacy4j** [comment]
Using a single vocal track btw, not sure if that's important to know

**Comment by Shadow06735** [comment]
are they split vocals? if so then ur gonna hear the sound glitchy cuz 0.7.3's song player was only designed for one vocal file. switching to 1.0 should fix the audio

**Comment by M4st3rG4m4** [comment]
> are they split vocals? if so then ur gonna hear the sound glitchy cuz 0.7.3's song player was only designed for one vocal file. switching to 1.0 should fix the audio

nope all my songs have one inst & one vocal idk why happens
