### ISSUE TITLE
Web build as a separate branch or repo

### ISSUE THREAD

**Issue by TooManyFactoryResets** [ShadowMario/FNF-PsychEngine#15626]
### What feature do you want to get added on the **base** engine?

Could you make a separate branch or repo for a web build such that it does not interfere with the desktop build. It's doesn't even have to be a part of the releases, I would just like to have a version to compile for a web server.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
> No intention on adding Browser support again as it tends to hinder the Desktop build.

Not only does it hinder the Desktop builds, I have no interest in going back to work on browser builds.
