### ISSUE TITLE
making cutscene below hud in song time

### ISSUE THREAD

**Issue by F1mpoPE** [ShadowMario/FNF-PsychEngine#15623]
### Describe your problem here.

so, im making mod and i need make cutscene that plays below hud at specific time (like in 2:00 video starts playing below hud but on top of bf, gf, and opponent) (note: i can't make specific character as cutscene Because this is will be too much frames) (Note2: Psych Engine Version is: FNF-PsychEngine-1.0-prerelease)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by SantiagoCalebe** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/14679

**Comment by F1mpoPE** [comment]
huh 
[2024-10-09 10-43-58.zip](https://github.com/user-attachments/files/17311876/2024-10-09.10-43-58.zip)

**Comment by SantiagoCalebe** [comment]
It doesn't work with 1.0 Pre-release. use 0.7.3.

**Comment by bebrenok** [comment]
FOR 1.0

import hxvlc.flixel.FlxVideoSprite;

var video:FlxVideoSprite;
function onCreate(){
    video= new FlxVideoSprite();
        video.cameras = [game.camHUD];
    video.load(Paths.video('video'));
    add(video);
}
function onStepHit()
    {
    if (curStep == 8){
        video.play();
}
    }

**Comment by F1mpoPE** [comment]
[nah_bro_i_guess_ill_just_use_PE_0_7_3.zip](https://github.com/user-attachments/files/17318329/nah_bro_i_guess_ill_just_use_PE_0_7_3.zip)

**Comment by F1mpoPE** [comment]
close

**Comment by F1mpoPE** [comment]
close

**Comment by F1mpoPE** [comment]
i just forgot how to close

**Comment by SantiagoCalebe** [comment]
lol
