### ISSUE TITLE
property "y" things

### ISSUE THREAD

**Issue by s-h-i-f-t-y-z** [ShadowMario/FNF-PsychEngine#15620]
### Describe your bug here.

i edited deleteCoolText in the title state so that instead of just spontaniously disappearing i made it so that it tweens to y 750, and compilation works but idk whenever it got to the part of the text disappearing it hit me with the error "The object does not have to property "y"". 

heres part of the code i edited:

	function deleteCoolText()
	{
		while (textGroup.members.length > 0)
		{
			FlxTween.tween(credGroup, {y: 750}, 0.8, {ease: FlxEase.circOut});
			FlxTween.tween(textGroup, {y: 750}, 0.8, {ease: FlxEase.circOut});
			textGroup.remove(textGroup.members[0], true);
			credGroup.remove(textGroup.members[0], true);
		}
	}

### Command Prompt/Terminal logs (if existing)

```bash
flixel/tweens/misc/VarTween.hx (line 99)
flixel/tweens/misc/VarTween.hx (line 55)
flixel/tweens/FlxTween.hx (line 1099)
flixel/FlxGame.hx (line 745)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

imagine getting: The object does not have the property "y"
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i edited titlestate and added a new bg that replaces blackScreen, and edited the deleteCoolText so that it tweens instead

**Comment by M4st3rG4m4** [comment]
why are you removing text before tween is completed?

**Comment by s-h-i-f-t-y-z** [comment]
oh-

**Comment by M4st3rG4m4** [comment]
> oh-

have you tried it again?

**Comment by s-h-i-f-t-y-z** [comment]
it still has that bug/error no matter what

**Comment by KELOTOMU** [comment]
textGroup.forEachExists(function (text:FlxBasic) {})
credGroup.forEachExists(function (cred:FlxBasic) {})

Try only using the textGroup forEachExists bc its the one that has all text, no other things unlike credGroup

**Comment by s-h-i-f-t-y-z** [comment]
> textGroup.forEachExists(function (text:FlxBasic) {}) credGroup.forEachExists(function (cred:FlxBasic) {})
> 
> Try only using the textGroup forEachExists bc its the one that has all text, no other things unlike credGroup

where should i put that/those lines of code in

like in the delete text function or addmore text or createcooltext

**Comment by KELOTOMU** [comment]
> > textGroup.forEachExists(function (text:FlxBasic) {}) credGroup.forEachExists(function (cred:FlxBasic) {})
> > 
> > Try only using the textGroup forEachExists bc its the one that has all text, no other things unlike credGroup
> 
> where should i put that/those lines of code in
> 
> like in the delete text function or addmore text or createcooltext

deleteCoolText

**Comment by s-h-i-f-t-y-z** [comment]
> > > textGroup.forEachExists(function (text:FlxBasic) {}) credGroup.forEachExists(function (cred:FlxBasic) {})
> > > Try only using the textGroup forEachExists bc its the one that has all text, no other things unlike credGroup
> > 
> > 
> > where should i put that/those lines of code in
> > like in the delete text function or addmore text or createcooltext
> 
> deleteCoolText

what would this do/help with

**Comment by KELOTOMU** [comment]
> > > > textGroup.forEachExists(function (text:FlxBasic) {}) credGroup.forEachExists(function (cred:FlxBasic) {})
> > > > Try only using the textGroup forEachExists bc its the one that has all text, no other things unlike credGroup
> > > 
> > > 
> > > where should i put that/those lines of code in
> > > like in the delete text function or addmore text or createcooltext
> > 
> > deleteCoolText
> 
> what would this do/help with

inside the function for the foreach iteration u will add the tweens that u wanna do

**Comment by s-h-i-f-t-y-z** [comment]
so credGroup is basically useless in the context of tweening the text out

**Comment by KELOTOMU** [comment]
> so credGroup is basically useless in the context of tweening the text out

credGroup stores all stuff which is not only the text. u are trying to edit the text so when it disappears, it will do a tween instead of it getting destroyed, so its best to use textGroup instead of the credGroup to not mess up other stuff

**Comment by s-h-i-f-t-y-z** [comment]
> > so credGroup is basically useless in the context of tweening the text out
> 
> credGroup stores all stuff which is not only the text. u are trying to edit the text so when it disappears, it will do a tween instead of it getting destroyed, so its best to use textGroup instead of the credGroup to not mess up other stuff

so would it be
`	function createCoolText(textArray:Array<String>, ?offset:Float = 0)
	{
		for (i in 0...textArray.length)
		{
			var money:Alphabet = new Alphabet(0, 0, textArray[i], true);
			money.screenCenter(X);
			money.y += (i * 60) + 200 + offset;
			if(credGroup != null && textGroup != null) {
				credGroup.add(money);
				textGroup.add(money);
			}
			textGroup.forEachExists(function (text:FlxBasic) {})
			lxTween.tween(textGroup, {y: 0}, 0.8, {onComplete: onTweenFinished, ease: FlxEase.circOut});
		}
	}

	function addMoreText(text:String, ?offset:Float = 0)
	{
		if(textGroup != null && credGroup != null) {
			var coolText:Alphabet = new Alphabet(0, 0, text, true);
			coolText.screenCenter(X);
			coolText.y == (textGroup.length * 60) + 200 + offset;
			credGroup.add(coolText);
			textGroup.add(coolText);
		}
	}

	function deleteCoolText()
	{
		while (textGroup.members.length > 0)
		{
			textGroup.forEachExists(function (text:FlxBasic) {})
			FlxTween.tween(textGroup, {y: 750}, 0.8, {, ease: FlxEase.circOut});
		}
	}`

the reason i added the tween for `onCreateText` is so that it reappears
