### ISSUE TITLE
Uh I cant compile the 64 bit FNF psych engine

### ISSUE THREAD

**Issue by JimMeta-belike** [ShadowMario/FNF-PsychEngine#15632]
### Describe your bug here.

It won't let me compile the actual application to open the mod

### Command Prompt/Terminal logs (if existing)

```bash
ApplicationMain.exe : fatal error LNK1120: 1 unresolved externals
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by megalives717** [comment]
how to fix?

**Comment by inky03** [comment]
try deleting the export folder or build using the `-clean` flag (ex. `lime test windows -clean`). sometimes it goes awry while compiling
