### ISSUE TITLE
GF doesn't sing when selected in the chart editor.

### ISSUE THREAD

**Issue by teamtrioinc** [ShadowMario/FNF-PsychEngine#15634]
### Describe your bug here.

I'm using Psych Engine 1.0b-prerelease and in the chart editor, when you select gf section the person whose supposed to sing in gfs spot doesn't.

### Command Prompt/Terminal logs (if existing)

```bash
nah
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Undecillion0** [comment]
do u mean that she wont play an animation or she wont sing with audio

**Comment by teamtrioinc** [comment]
when you do gf section and add notes she doesn’t sing (or whoever’s selected as gf)
