### ISSUE TITLE
Make Dialogue start at the end of the song

### ISSUE THREAD

**Issue by Godofbacon1** [ShadowMario/FNF-PsychEngine#1563]
### What is your question?

I was wondering how to make the dialogue plays when the song ends i mean before it goes to the another song like if i have a week i have 2 songs like nugget and pro i made dialogue but i want to play it when the nugget song ends without teleport to the pro song?(I am using Lua program btw)

**Comment by NotEpik** [comment]
for the start dialogue and end song dialogue:

```
local allowCountdown = false
local startedFirstDialogue = false
local startedEndDialogue = false
function onStartCountdown()
	if not allowCountdown and isStoryMode and not startedFirstDialogue then
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		startedFirstDialogue = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onEndSong()
	if not allowCountdown and isStoryMode and not startedEndDialogue then
		setProperty('inCutscene', true);
		runTimer('startDialogueEnd', 0.8);
		startedEndDialogue = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then
		startDialogue('dialogue', 'breakfast');
	elseif tag == 'startDialogueEnd' then
		startDialogue('dialogueEnd', 'breakfast');
	end
end
```

if only for end song just change the `onStartCountdown()` to `onEndSong()`

**Comment by Godofbacon1** [comment]
But look if i have 2 dialogues in 1 song file like 2 dialogues in nugget' chart folder and i want one of them plays at the start and one at the end what do i do?

**Comment by Godofbacon1** [comment]
OMG THX
