### ISSUE TITLE
SScript is not available, thanks to everyone for their support error

### ISSUE THREAD

**Issue by megalives717** [ShadowMario/FNF-PsychEngine#15631]
### Describe your problem here.

![error](https://github.com/user-attachments/assets/192841de-77c0-4c19-b2f4-c6f38bdc67fa)
how to fix this error?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by megalives717** [comment]
please help

**Comment by Icefellow28** [comment]
I’m here to lend a hand!

This issue is popping up quite a bit, but no need to worry because it’s a simple fix!

All you need to do is download the previous version of SScript. If you’re using PE0.7.3, you’ll want to grab SScript 7,7,0 You can find the older versions right here!

[](https://github.com/CobaltBar/SScript-Archive/tree/main/archives)

Once you downloaded what version you wanted, move the file to the source code (don't extract) and leave it there then open CMD or Windows PowerShell and type:

> haxelib install SScript 7,7,0.zip

or what version you downloaded
and there you have it!
 
if you have any problems feel free to reply back :D

**Comment by matias565** [comment]
![image](https://github.com/user-attachments/assets/037b6598-b4c0-4697-aba3-1838cbd7537e)
mmmmm. how

**Comment by matias565** [comment]
oh nvm I had to manage to fix the problem without windows powershell thank you

**Comment by megalives717** [comment]
![error2](https://github.com/user-attachments/assets/3554f072-0ddd-4fb2-9b91-717edfa7d8f7)
not working

**Comment by Icefellow28** [comment]
Hi again!

It looks like you may need to reinstall hxdiscord_rpc.

And it's a fast process

> haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc.git

Just enter this in CMD or Windows PowerShell 
and that's all you need to do to install it!

**Comment by bbbb033020** [comment]
> oh nvm I had to manage to fix the problem without windows powershell thank you

how

**Comment by bbbb033020** [comment]
> I’m here to lend a hand!
> 
> This issue is popping up quite a bit, but no need to worry because it’s a simple fix!
> 
> All you need to do is download the previous version of SScript. If you’re using PE0.7.3, you’ll want to grab SScript 7,7,0 You can find the older versions right here too!
> 
> https://github.com/CobaltBar/SScript-Archive/tree/main/archives
> 
> Once you downloaded what version you wanted, move the file to the source code (don't extract) and leave it there then click on File on the top left of file explorer and open Windows PowerShell and type:
> 
> > haxelib install SScript 7,7,0.zip
> 
> or what version you downloaded and there you have it!
> 
> if you have any problems feel free to reply back :D

still not working

**Comment by Gabopogi01** [comment]
source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
                                                                                                             export/debug/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
                                                                                   source/psychlua/CallbackHandler.hx:55: characters 41-46 : Class<llua.LuaL> has no field error
                                                        export/debug/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
                              E:/Downloads in E/HaxeFlixel/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat should be declared with 'override' since it is inherited from superclass flixel.graphics.frames.FlxAtlasFrames
                              E:/Downloads in E/HaxeFlixel/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : Field concat overrides parent class with different or incomplete type
                                                                                                E:/Downloads in E/HaxeFlixel/haxe/lib/flixel/5,8,0/flixel/graphics/frames/FlxAtlasFrames.hx:472: characters 18-24 : ... Base field is defined here
  E:/Downloads in E/HaxeFlixel/haxe/lib/flxanimate/3,0,4/flxanimate/frames/FlxAnimateFrames.hx:142: characters 21-27 : ... Different number of function arguments
                                         source/backend/Paths.hx:605: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)
                                      source/objects/Character.hx:304: characters 87-101 : flxanimate.animate.FlxAnim has no field lastPlayedAnim
                         source/objects/Character.hx:335: characters 20-26 : flxanimate.animate.FlxAnim has no field resume
   source/psychlua/FunkinLua.hx:280: lines 280-283 : Int should be Bool
                                                                       source/psychlua/FunkinLua.hx:280: lines 280-283 : ... For function argument 'f'

**Comment by megalives717** [comment]
![ERROR3](https://github.com/user-attachments/assets/8e8070b1-b855-4ddb-983c-e533fc34c8e6)
error please help

**Comment by WoodsSilent05** [comment]
>` source/psychlua/CallbackHandler.hx:55: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua export/debug/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here `

I had that same problem, all i did to fix it was fuck with the code by replacing` if(Lua_helper.sendErrorsToLua)` with` if(1==1)`, it didnt throw errors after that, so even though i had just changed something to be true all the time, it still helped.
