### ISSUE TITLE
TRANSLATE TEXTS IN LUA

### ISSUE THREAD

**Issue by JuanSebas1247** [ShadowMario/FNF-PsychEngine#15635]
### Describe your problem here.

How do I translate a text that is in Lua, using "getTranslationPhrase" in 3 ways?
I use Portuguese to test and nothing, the translated text does not load

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by sunkydunky31** [comment]
Did you go into the language settings and select "Português (Brasil)" again? When you start the game, it only reloads the language file if you go into the settings and select it again, or clicking in "RELOAD" button on Mods Menu.

**Comment by JuanSebas1247** [comment]
Worse, how do I add it to the lang file? To test what you told me earlier

**Comment by JuanSebas1247** [comment]
But, how do I add it to the lang file? To test what you told me earlier

**Comment by sunkydunky31** [comment]
Firstly, the file name is a language code, for example: `es-US` for Spanish (United States), `en-UK` for English (United Kingdom), etc.
This file should be placed inside the `YourMod/data/` folder

Within the file, the first line will ALWAYS be the name of the language, and after skipping this line, the sentences you want to include will come, they must be formatted like this:

```
English (UK)

your_phrase_code: "Your Custom Phrase"
```

To use this custom phrase, use this function:
`getTranslationPhrase(phrase:String, defaultPhrase:String, args:Dynamic)`

EXAMPLE:
```lua
function onStartCountdown()
    debugPrint(getTranslationPhrase(your_phrase_code, "Phrase in English (US)\nScore: {1}", score)
end
```
