### ISSUE TITLE
how do i add combo hud middle of hud score and misses

### ISSUE THREAD

**Issue by samikhuska57** [ShadowMario/FNF-PsychEngine#15638]
### What is your question?

how do i add combo hud middle of hud score and misses

**Comment by GatoMorado621** [comment]
Are you using lua or source?

**Comment by SantiagoCalebe** [comment]
Change the order in Source/States/PlayState.hx

**Comment by samikhuska57** [comment]
[GatoMorado621](https://github.com/GatoMorado621) i using both of them [im bad at coding]
