### ISSUE TITLE
Prerelease 1.0 chart editor bugs

### ISSUE THREAD

**Issue by nicollebungas** [ShadowMario/FNF-PsychEngine#15633]
### Describe your bug here.

When you click the "Swap section" it doesnt swap in the chart preview (f12), only when you playtest the chart and go back that it changes it.
Also when you copy and paste, swap section, mirror notes, the Disable Note RGB has to be updated because the notes get their rgb again.

Those are the bugs, but I have a few suggestions in features that would help with charting:
Would be awesome if you could swap the oponent and the player in the editor, its really confusing to have to chart the player in the left side and the oponent in the right;
"Mirror Notes" if there are notes selected, it would only mirror the selected ones;
Add an option in viewing of the waveform where you could make it so it is split so each side shows their respective waveform, so you dont need to me switching in the options all the time;

### Command Prompt/Terminal logs (if existing)

```bash
nuh uh
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, but nothing in the code, just adding songs and characters.

**Comment by SantiagoCalebe** [comment]
It's because that is Pre-Release.

Close the issue, 1.0 is out

**Comment by nicollebungas** [comment]
Every single bug in this thread is still in the 1.0 release...
