### ISSUE TITLE
where is the executable

### ISSUE THREAD

**Issue by bbbb033020** [ShadowMario/FNF-PsychEngine#15637]
### Describe your problem here.

I'm trying to find an executable in the files which runs the game. Checked every file. Not even a single executable of the game showed up.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited MainMenuState.hx to remove Story Mode.

**Comment by baobab121** [comment]
PsychEngine/export/release/windows/bin
