### ISSUE TITLE
how do i hide fps counter in lua

### ISSUE THREAD

**Issue by Gabopogi01** [ShadowMario/FNF-PsychEngine#15639]
### Describe your problem here.

idk how do i hide it so plz how 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by nicollebungas** [comment]
you can hide it in Options/Visuals/FPS Counter In game, idk how to do it in code tho

**Comment by Gabopogi01** [comment]
setPropertyFromClass('Main','fpsVar.visible',false);
by https://gamebanana.com/members/3275784
