### ISSUE TITLE
Stage Editor not accurate to In-Game

### ISSUE THREAD

**Issue by MugMiles** [ShadowMario/FNF-PsychEngine#15649]
### Describe your problem here.

I'm trying to set up a background using the stage editor in the prerelease, and I thought I did everything correctly until I actually loaded up the background in the game. All the offsets were completely different to what the editor made it look like. Am I doing something wrong in the editor?

![Screenshot (288)](https://github.com/user-attachments/assets/c17c7b92-f08e-407d-80da-633a4e29ee9f)
![Screenshot (290)](https://github.com/user-attachments/assets/83f5422a-94a8-4c01-b0e9-49449187e6ce)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
Is the stage sprite animated?

**Comment by MugMiles** [comment]
I actually figured it out, it was an issue on my end. I had a leftover lua file I was using that overrode the json. Editor works great!
