### ISSUE TITLE
A Soundtrack Menu.

### ISSUE THREAD

**Issue by SantiagoCalebe** [ShadowMario/FNF-PsychEngine#15643]
### What feature do you want to get added on the **base** engine?

A menu that includes all the soundtracks.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Swapper1** [comment]
![seriously-laugh](https://github.com/user-attachments/assets/b19e44f4-0523-483f-8d76-782cbd23639b)
