### ISSUE TITLE
lime test windows not functioning correctly

### ISSUE THREAD

**Issue by yourlocalfemboi** [ShadowMario/FNF-PsychEngine#15659]
### Describe your problem here.

I followed all the instructions in the building section correctly, but when I went to type in lime test windows after changing my current directory to psychengine main it gave me this error:

lime : The term 'lime' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ lime test windows
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (lime:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I don't know what to do

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CrusherNotDrip** [comment]
```poweshell
haxelib run lime setup
```
