### ISSUE TITLE
Game not starting

### ISSUE THREAD

**Issue by Maxi2022gt** [ShadowMario/FNF-PsychEngine#15658]
### Describe your bug here.

I am just installing this because of fun, but then i encountered an error with SScript and then looking thru issues i found an archive of it. I tried it and it worked but when i did `lime test windows` the game doesn't start and instead throws an error with HScript.hx.

### Command Prompt/Terminal logs (if existing)

```bash
source/psychlua/HScript.hx:291: characters 89-96 : Type not found : TeaCall
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Maxi2022gt** [comment]
Btw source version is 0.7.2.

**Comment by Maxi2022gt** [comment]
wait i just fixed it but theres another error
```
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by SantiagoCalebe** [comment]
The most obvious error.

Change 'Teacall' to 'Tea'

**Comment by Shadow06735** [comment]
> wait i just fixed it but theres another error
> 
> ```
> Warning: Could not find Visual Studio VsDevCmd
> Missing HXCPP_VARS
> Error: Could not automatically setup MSVC
> ```

you need to download visual studio

**Comment by Maxi2022gt** [comment]
i did
also i fixed it so i can close it ig
