### ISSUE TITLE
custom NOTE_assets export help

### ISSUE THREAD

**Issue by StinkTheStinker** [ShadowMario/FNF-PsychEngine#15669]
### Describe your problem here.

![image](https://github.com/user-attachments/assets/8d93b6c1-8380-4a36-900d-56c87c1b3d31)
the frame is being cutoff
shape and border padding is at 57

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by JordanSantiagoYT** [comment]
ive figured it out and fixed it, this issue can be closed now
