### ISSUE TITLE
It doesn't detect anything from my mod

### ISSUE THREAD

**Issue by Drew1972-1972** [ShadowMario/FNF-PsychEngine#15660]
### Describe your problem here.

For some reason, when I start the game, it detects that there is a mod, since it appears in the mods sector that there is a new one. But when I try to add a song, some credit, sprites, or whatever, it's like it doesn't detect them, but it doesn't crash or anything, it just sets things by default so as not to cause errors and it doesn't put what I did

Post-Data: I am using 0.7.3, not the Source code ZIP because it was making it impossible for me to compile the engine, I am using the common version

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i'dont edit nothing

**Comment by SantiagoCalebe** [comment]
Alright, lemme understand, first you said that you aren't using source but in the question 'Are you modding a build from source or with Lua?' you put 'Source' (???)

Compile it using 'Build-x64' or 'Build-x32' for the mods work.

**Comment by Drew1972-1972** [comment]
> Alright, lemme understand, first you said that you aren't using source but in the question 'Are you modding a build from source or with Lua?' you put 'Source' (???)
> 
> Compile it using 'Build-x64' or 'Build-x32' for the mods work.

First, I'm sorry if something in my translation goes wrong, because I don't speak English and I use a translator for this, so I'm sorry if there was a mistake in the translation of my message and it made it difficult to understand exactly what it said. Second, I am using the source code [that is, touch the "Source Code" when downloading Psych Engine], and although I followed the steps, I touched the Setup folder and put the windows setup, and then I went to Build-x64 but I kept getting that error, so I don't understand exactly what's happening...

**Comment by SantiagoCalebe** [comment]
The mod was to be in a folder, and inside of it, have to be 'data, songs..' stuff

**Comment by Drew1972-1972** [comment]
> The mod was to be in a folder, and inside of it, have to be 'data, songs..' stuff

Thank you very much man, and by the way, it turns out that I had answered you wrong, since apart from this Issue, I had opened a similar one for another problem, that's why I was wrong when answering your previous question

**Comment by SantiagoCalebe** [comment]
> > The mod was to be in a folder, and inside of it, have to be 'data, songs..' stuff
> 
> Thank you very much man, and by the way, it turns out that I had answered you wrong, since apart from this Issue, I had opened a similar one for another problem, that's why I was wrong when answering your previous question

You're welcome!

**Comment by SantiagoCalebe** [comment]
Close the issue.

**Comment by Drew1972-1972** [comment]
al fin pude hacer que funcione, resulta q habia una carpeta extra que hacia que no detecte nada de mi mod
