### ISSUE TITLE
Was rewriting from mods to assets and i get this error

### ISSUE THREAD

**Issue by RasoLdev** [ShadowMario/FNF-PsychEngine#15665]
### Describe your bug here.

So while i was doing this stuff i was keeping getting the error, I have everything as png the error:
objects/HealthIcon.hx (line 35)
objects/HealthIcon.hx (line 15)
states/FreeplayState.hx (line 109)
flixel/FlxGame.hx (line 640)
flixel/FlxGame.hx (line 727)
flixel/FlxGame.hx (line 680)
flixel/FlxGame.hx (line 559)
openfl/events/EventDispatcher.hx (line 426)
openfl/display/DisplayObject.hx (line 1398)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I removed original assets, and replaced them with the mod assets

**Comment by SantiagoCalebe** [comment]
It's something with Icon.

Check if your file of the icon of your character is Icon-<chr name> and if is 300x150 and if IS A PNG!!
