### ISSUE TITLE
lua question

### ISSUE THREAD

**Issue by StinkTheStinker** [ShadowMario/FNF-PsychEngine#15679]
### What is your question?

is there anyway to make a working and live waveform in lua?

**Comment by JHAM25** [comment]
Puedes explicar más de lo quieres hacer con la onda es que al traducir no se entiende muy bien.

**Comment by StinkTheStinker** [comment]
Me refiero a una forma de onda similar a esta.
![image](https://github.com/user-attachments/assets/161bc108-18c9-4e34-aacf-2c82380a1b7a)

**Comment by JHAM25** [comment]
> Me refiero a una forma de onda similar a esta. ![imagen](https://private-user-images.githubusercontent.com/145304742/376444812-161bc108-18c9-4e34-aacf-2c82380a1b7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMjM2ODYsIm5iZiI6MTcyOTEyMzM4NiwicGF0aCI6Ii8xNDUzMDQ3NDIvMzc2NDQ0ODEyLTE2MWJjMTA4LTE4YzktNGUzNC1hYWNmLTJjODIzODBhMWI3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwMDAzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODhjOTllODkxOGMxNjVhZGIwMjhlZjA3ZmNkMzliYTQyMzlmNjc2ZWJlOTgxYjZhY2UzZWM1ZGFkMDY5NDczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._eL7bBROHBY1nIl4z4IAp7R9ExxUH3hWH6Gc-fxMuF8)

Puede se algo asi?:

https://github.com/user-attachments/assets/b8f6eb2e-c9fb-4e2d-9a71-e0b9a2f73b1c

**Comment by StinkTheStinker** [comment]
¿Pueden las líneas ser un poco más delgadas? Además, ¿puede cambiar el color?

**Comment by JHAM25** [comment]
> ¿Pueden las líneas ser un poco más delgadas? Además, ¿puede cambiar el color?

Asi? 

https://github.com/user-attachments/assets/8fbc7040-9143-41de-9bc6-e6bada70ac4a

**Comment by StinkTheStinker** [comment]
si, se ve bien

**Comment by JHAM25** [comment]
Modifícalo si no te gusta algo

**Comment by StinkTheStinker** [comment]
¿Te parece bien traducir eso al inglés?

**Comment by JHAM25** [comment]
> ¿Te parece bien traducir eso al inglés?

Here I tried to translate it:


luaDebugMode = true
number = 0
function onCreate()
end
function onUpdate()
    wave()
    for i = 0, number do
        if luaSpriteExists('wave'..i) and getProperty('wave'..i..'.x') < -10 then
            removeLuaSprite('wave'..number, true)
            --debugPrint('It was removed'..'wave'..number)
        end
    end
end
function wave()
    makeLuaSprite('wave'..number, '', screenWidth + 10, 500)
    makeGraphic('wave'..number, 2, 1, '0000FF')
    setProperty('wave'..number..'.scale.y', getRandomInt(1, 600))
    setObjectCamera('wave'..number, 'camHUD')
    addLuaSprite('wave'..number)
    doTweenX('wave'..number, 'wave'..number, -20, 5)
    number = number + 1
    setProperty('camGame.visible', false)
end
function onTweenCompleted(tag)
    if tag == 'wave'..number then

    end
end
