### ISSUE TITLE
"SScript is not available" in the prerealease 1.0, HELP ME PLEASE

### ISSUE THREAD

**Issue by Drew1972-1972** [ShadowMario/FNF-PsychEngine#15677]
### Describe your problem here.

C:/HaxeToolkit/haxe/lib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support."

This error appears in the last part of the compilation, when I use Build_x63.bat, when reading that someone else had that problem, I saw that the solution was to go to pre-release 1.0, but it didn't work (and if you ask me, yes, I have SScript)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i'dont edit anything

**Comment by Drew1972-1972** [comment]
> I believe the temporary solution to this before its replacement in 1.0 is using https://github.com/CobaltBar/SScript-Archive instead of normal SScript

okay, I'll try, thanks for the help

**Comment by Drew1972-1972** [comment]
[I DO NOT TAKE THIS AS DONE, I WILL SAY WHAT HAPPENS IN THE END WITH THE ENGINE BEFORE SAYING THAT THIS PROBLEM WAS SOLVED]

**Comment by Drew1972-1972** [comment]
> I believe the temporary solution to this before its replacement in 1.0 is using https://github.com/CobaltBar/SScript-Archive instead of normal SScript

No, for some reason it didn't work, I have the correct version of SScript, just the one that Psyche Engine asks for, and it won't let me do anything, nor can I use previous versions...

**Comment by ShadowMario** [comment]
Use 1.0 now
