### ISSUE TITLE
I cant chart

### ISSUE THREAD

**Issue by JackAnimateZ** [ShadowMario/FNF-PsychEngine#15676]
### Describe your bug here.

this happens #
![Screenshot 2024-10-13 141901](https://github.com/user-attachments/assets/19582277-0ad9-44bb-9866-ef2e3da0affd)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by DavesTheBone** [comment]
Could you explain a bit more in detail?

**Comment by JackAnimateZ** [comment]
if you scroll down it doesn't show the rest of the chart editor, it wont let you see the rest of the chart.

**Comment by DavesTheBone** [comment]
Have you tried downloading it again?
