### ISSUE TITLE
type not found: SScript, tea,SScript

### ISSUE THREAD

**Issue by bbbb033020** [ShadowMario/FNF-PsychEngine#15673]
### Describe your problem here.

source/states/PlayState.hx:59: characters 8-19 : Type not found : tea.SScript
source/psychlua/HScript.hx:13: characters 8-19 : Type not found : tea.SScript
source/psychlua/HScript.hx:14: characters 23-30 : Type not found : SScript
how can i fix this

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I put the SScript 7,7,0 zip file into the source folder

**Comment by mrchaoss1** [comment]
Version of Psych Engine?

**Comment by tposejank** [comment]
Open an issue at [this place](https://github.com/CobaltBar/SScript-Archive)
there are instructions, you haven't finished them

**Comment by mrchaoss1** [comment]
> Open an issue at [this place](https://github.com/CobaltBar/SScript-Archive) there are instructions, you haven't finished them

that was too fast-
