### ISSUE TITLE
Turned "TeaCall" into "Tea" and now it's gotten worse

### ISSUE THREAD

**Issue by StatusZer0** [ShadowMario/FNF-PsychEngine#15685]
### Describe your problem here.

Fixed the classic "TeaCall" error in the most recent source build, then I ran `lime test windows` to see if it was working.
It wasn't, and I've got no idea what I was given.
![image](https://github.com/user-attachments/assets/6ba790f2-e0bf-467d-9e67-504bf13b7d91)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I went into source/psychlua/HScript.hx and changed all instances of "TeaCall" to "Tea"

**Comment by a-random441** [comment]
```cmd
haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git
haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev
```
