### ISSUE TITLE
V-Slice Port Issue + Crashing Chart on Older Version

### ISSUE THREAD

**Issue by fffdsfdsfds** [ShadowMario/FNF-PsychEngine#15686]
### Describe your bug here.

![image](https://github.com/user-attachments/assets/156ed03a-5f1c-41a4-955f-b6f403694247)
Whenever i try and port this song to V-Slice, It doesnt port, and it crashes my game. However, Whenever i try and put this chart, (still psych engine, just the newest beta) into 0.73, it says 
![quuartemaysaveus](https://github.com/user-attachments/assets/f55ba3b1-9a2d-4020-a374-6d0b89aff548)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SantiagoCalebe** [comment]
```
import backend.Difficulty;
import tjson.TJSON;

function onCreate() {
    // Remove the "//" on the convertToOld lines to use it

    // Converting json, path starts in mods
    //convertToOld('jsonName');

    // Converting current song and difficulty
    // convertToOld('data/'+game.songName+'/'+game.songName+Difficulty.getFilePath());

    // Converting events.json on current song
    // Must be named events.json to be able to convert it as event
    // Alternatively, you can set the second argument to true,
    // which will force it to convert as event regardless of the name
    //convertToOld('data/'+game.songName+'/events');
    return;
}

function convertToOld(path:String, ?convertAsEvent, ?printMessage:Bool) {
    if (!StringTools.endsWith(path, '.json')) path += '.json';
    if (StringTools.endsWith(path, 'events.json')) convertAsEvent = true;
    else if (convertAsEvent == null) convertAsEvent = false;
    printMessage ??= true;
    try {
        var _song:Dynamic = TJSON.parse(File.getContent(Paths.modFolders(path)));

        if (!convertAsEvent) {
            for (section in _song.notes) {
                if (section.sectionNotes != null && section.sectionNotes.length != 0) {
                    for (notes in section.sectionNotes) {
                        if (!section.mustHitSection) {
                            if (notes[1] > 3) {
                                notes[1] = notes[1] % 4;
                            }
                            else {
                                notes[1] += 4;
                            }
                        }
                    }
                }
            }
        }

        if (_song.format == null || _song.format != 'psych_legacy_convert') _song.format = 'psych_legacy_convert';
        _song = {song: _song};

        var saveToFolder = 'converted_charts/';
        var savePath = saveToFolder+path.substring(path.lastIndexOf('/')+1);
        if (!FileSystem.exists(saveToFolder) || !FileSystem.isDirectory(saveToFolder)) FileSystem.createDirectory(saveToFolder);
        _song = TJSON.encode(_song, 'fancy');
        File.saveContent(savePath, _song);
        if (printMessage) debugPrint('File '+(FileSystem.exists(savePath) ? 'overwritten' : 'saved')+' at '+savePath, FlxColor.LIME);
    }
    catch(e:Dynamic) {
        var msg = e.toString();
        if (StringTools.startsWith(e.toString(), '[file_contents')) msg = 'Missing file: '+e.toString().substring(15, e.toString().length-1);
        debugPrint('Error converting chart: '+msg, FlxColor.RED);
    }
}
```

paste it as **PsychConverter.hx**

**Comment by SantiagoCalebe** [comment]
Also, Psych Engine 1.0 changed the chart format.

**Comment by fffdsfdsfds** [comment]
> ```
> import backend.Difficulty;
> import tjson.TJSON;
> 
> function onCreate() {
>     return;
> }
> 
> function convertToOld(path:String, ?convertAsEvent, ?printMessage:Bool) {
>     if (!StringTools.endsWith(path, '.json')) path += '.json';
>     if (StringTools.endsWith(path, 'events.json')) convertAsEvent = true;
>     else if (convertAsEvent == null) convertAsEvent = false;
>     printMessage ??= true;
>     try {
>         var _song:Dynamic = TJSON.parse(File.getContent(Paths.modFolders(path)));
> 
>         if (!convertAsEvent) {
>             for (section in _song.notes) {
>                 if (section.sectionNotes != null && section.sectionNotes.length != 0) {
>                     for (notes in section.sectionNotes) {
>                         if (!section.mustHitSection) {
>                             if (notes[1] > 3) {
>                                 notes[1] = notes[1] % 4;
>                             }
>                             else {
>                                 notes[1] += 4;
>                             }
>                         }
>                     }
>                 }
>             }
>         }
> 
>         if (_song.format == null || _song.format != 'psych_legacy_convert') _song.format = 'psych_legacy_convert';
>         _song = {song: _song};
> 
>         var saveToFolder = 'converted_charts/';
>         var savePath = saveToFolder+path.substring(path.lastIndexOf('/')+1);
>         if (!FileSystem.exists(saveToFolder) || !FileSystem.isDirectory(saveToFolder)) FileSystem.createDirectory(saveToFolder);
>         _song = TJSON.encode(_song, 'fancy');
>         File.saveContent(savePath, _song);
>         if (printMessage) debugPrint('File '+(FileSystem.exists(savePath) ? 'overwritten' : 'saved')+' at '+savePath, FlxColor.LIME);
>     }
>     catch(e:Dynamic) {
>         var msg = e.toString();
>         if (StringTools.startsWith(e.toString(), '[file_contents')) msg = 'Missing file: '+e.toString().substring(15, e.toString().length-1);
>         debugPrint('Error converting chart: '+msg, FlxColor.RED);
>     }
> }
> ```
> 
> paste it as **PsychConverter.hx**

I quote replied because i dont know how to actually reply.. shocker. Where do i put the "PsychConverter.hx"?

**Comment by SantiagoCalebe** [comment]
Mods/Scripts.

**Comment by fffdsfdsfds** [comment]
thank you so much,

**Comment by SantiagoCalebe** [comment]
> thank you so much,

You're welcome!

**Comment by fffdsfdsfds** [comment]
> > thank you so much,
> 
> You're welcome!

gee, i feel very annoying right now
just did it.. and it still says "invalid field:gfversion"

**Comment by SantiagoCalebe** [comment]
hm..

```
import tjson.TJSON;

function onCreate() {
    convertToOld('jsonName'); // the path starts in mods folder
    return;
}

function convertToOld(path:String) {
    if (!StringTools.endsWith(path, '.json')) path += '.json';
    try {
        var _song:Dynamic = TJSON.parse(File.getContent(Paths.modFolders(path)));

        for (section in _song.notes) {
            if (section.sectionNotes != null && section.sectionNotes.length != 0) {
                for (notes in section.sectionNotes) {
                    if (!section.mustHitSection) {
                        if (notes[1] > 3) {
                            notes[1] = notes[1] % 4;
                        }
                        else {
                            notes[1] += 3;
                        }
                    }
                }
            }
        }

        _song = {song: _song};

        var saveToFolder = 'converted_charts';
        var savePath = saveToFolder+'/'+path.substring(path.lastIndexOf('/')+1);
        if (!FileSystem.exists(saveToFolder) || !FileSystem.isDirectory(saveToFolder)) FileSystem.createDirectory(saveToFolder);
        _song = TJSON.encode(_song, 'fancy');
        debugPrint('File '+(FileSystem.exists(savePath) ? 'overwritten' : 'saved')+' at '+savePath, FlxColor.LIME);
        File.saveContent(savePath, _song);
    }
    catch(e:Dynamic) {
        var msg = e.toString();
        if (StringTools.startsWith(e.toString(), '[file_contents')) msg = 'Missing file: '+e.toString().substring(15, e.toString().length-1);
        debugPrint('Error converting chart: '+msg, FlxColor.RED);
    }
}
```
try this

**Comment by fffdsfdsfds** [comment]
still happening.. are my files tweaking or is it smthin else

**Comment by SantiagoCalebe** [comment]
> still happening.. are my files tweaking or is it smthin else

Are you using 1.0 release or pre-release?

**Comment by fffdsfdsfds** [comment]
> > still happening.. are my files tweaking or is it smthin else
> 
> Are you using 1.0 release or pre-release?

The said chart was made in the pre-release. I tested it on 1.0, the stage was gone, which, i mean, fine, the pause menu, also fine, but as soon, as this chart touched my 0.73 Psych Engine mods folder.. "invalid field gf:version"

I am terribly sorry if you said something earlier and i just didnt pick it up, I'm running on low sleep

**Comment by SantiagoCalebe** [comment]
Alright, but it worked?

**Comment by fffdsfdsfds** [comment]
> Alright, but it worked?

yes, on the pre-release and 1.0, it worked. Cant find out why it doesnt work on 0.73.. I mean.. I know it uses a brand new format for charts, but i don't understand why its telling me something went wrong with gf

**Comment by SantiagoCalebe** [comment]
> > Alright, but it worked?
> 
> yes, on the pre-release and 1.0, it worked. Cant find out why it doesnt work on 0.73.. I mean.. I know it uses a brand new format for charts, but i don't understand why its telling me something went wrong with gf

it's because the fomart changed, so 0.7.3 doesn't officially read

**Comment by SantiagoCalebe** [comment]
Hope i helped.

**Comment by fffdsfdsfds** [comment]
You did my man. Thank you

**Comment by ADA-Funni** [comment]
I figured out how to fix the issue.

The reason why Psych v1 charts don't work in 0.7.3 is because charts were formatted like this before v1:
```
{
    "song": //everything in your chart here
}
```

v1 changed it to be formatted like this:
```
{
    // everything in your chart here
}
```

So, to port a 1.0 chart to older versions, you need to add "song": after the first curly bracket in the JSON, and add a new line at the **end of the JSON file**, and put a curly bracket in it.

**Comment by fffdsfdsfds** [comment]
this was so long ago, but thank you so friggin much man, i really did need to port this chart

**Comment by ADA-Funni** [comment]
You will have to fix the sections manually, but Psych v1 is just like that ig.
They really need to add a way to port the charts over without much of a hassle.
