### ISSUE TITLE
This keeps happening every time i try to run "lime test windows"

### ISSUE THREAD

**Issue by JackAnimateZ** [ShadowMario/FNF-PsychEngine#15687]
### Describe your problem here.

![Screenshot 2024-10-14 165723](https://github.com/user-attachments/assets/ba711a6d-d477-4de4-8cc7-47811e488147)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SantiagoCalebe** [comment]
Delete the **Export** Folder.
