### ISSUE TITLE
Stage Change event

### ISSUE THREAD

**Issue by teamtrioinc** [ShadowMario/FNF-PsychEngine#15689]
### What feature do you want to get added on the **base** engine?

I wish there was a stage change event added, it is a big hassle coding or attempting to code in a script for it to happen with lua. Previously, it was able to be coded in with the lua stages but now that there is a stage editor and it’s not lua anymore, it would make sense to add one maybe in 1.1 or a hotfix. (since psych engine won’t have major updates anymore)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by teamtrioinc** [comment]
and before you say this is a duplicate complaint i have a valid reason. With the newly added stage editor, you can’t change it with lua now, which makes it even harder now for new modders to add what they want, which lessens the quality of life for the update. You would need to use source which isn’t plausible for new modders since most of them don’t know haxe. This can be a genuine problem for the new update and I hope you actually consider it now that it can grow to an actual problem in the Psych Engine modding scene.

**Comment by teamtrioinc** [comment]
proves my point

**Comment by SantiagoCalebe** [comment]
i swear to god

**Comment by CrusherNotDrip** [comment]
i swear to god

**Comment by LarryFrosty** [comment]
> With the newly added stage editor, you can’t change it with lua now

![Screenshot_2024-10-16-21-25-13-19.jpg](https://github.com/user-attachments/assets/6fc31132-461e-4de5-9aeb-bb301c22077d)

**Comment by teamtrioinc** [comment]
exactly
