### ISSUE TITLE
setProperty and setObjectCamera won't work properly

### ISSUE THREAD

**Issue by Bopple-McNuggets** [ShadowMario/FNF-PsychEngine#15696]
### Describe your bug here.

When I ported my mod over to the 1.0 update, pretty much every instance of the 'setProperty' and 'setObjectCamera' commands stopped working. Attached is an example of parts of the script I'm using, what the song is supposed to look like, and what it looks like right now. Additionally, the black graphic labelled 'dark' is supposed to be on camHUD and covering the screen, though invisible at the moment.

![Screenshot 2024-10-15 081931](https://github.com/user-attachments/assets/2ae2c784-9035-436b-8405-f099ee33560a)
![Screenshot 2024-10-15 081943](https://github.com/user-attachments/assets/472d2b02-b1c4-4c22-9fac-0a366494bd34)
![Screenshot 2024-10-15 082313](https://github.com/user-attachments/assets/98d76714-0156-446d-9559-01667677ac97)
![Screenshot 2024-10-15 081718](https://github.com/user-attachments/assets/6c7d7176-82e8-4e24-8285-f80c0f30c97b)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SantiagoCalebe** [comment]
https://shadowmario.github.io/psychengine.lua/

New Lua Script API.

**Comment by Bopple-McNuggets** [comment]
i've been reading through that a lot, but i haven't yet found anything that could inform me of what's wrong with the code i already have

**Comment by SantiagoCalebe** [comment]
The LUA API changed, so everything you need should be there.

If it isn't, join Psych's Discord Server for help.
https://www.discord.gg/psychengine

**Comment by a-random441** [comment]
It broke

**Comment by SantiagoCalebe** [comment]
join Psych's Discord Server for help.
https://www.discord.gg/psychengine

> setObjectCamera is broken for Lua Sprites, for setProperty idfk, basically setObjectCamera and setProperty won't work for now

**Comment by a-random441** [comment]
> join Psych's Discord Server for help. https://www.discord.gg/psychengine
> 
> > setObjectCamera is broken for Lua Sprites, for setProperty idfk, basically setObjectCamera and setProperty won't work for now

Bro I'm telling you it's literally broken. setObjectCameras is at fault bc of getLuaObject

**Comment by SantiagoCalebe** [comment]
> > join Psych's Discord Server for help. https://www.discord.gg/psychengine
> > > setObjectCamera is broken for Lua Sprites, for setProperty idfk, basically setObjectCamera and setProperty won't work for now
> 
> Bro I'm telling you it's actually broken. setObjectCameras is at fault

i cannot do anything about it, join Psych's Discord Server for more help.
https://www.discord.gg/psychengine

**Comment by XxBromanFunkinxX** [comment]
here i came try this out

`setProperty('object.camera', instanceArg('cameraName'), false, true)`

**Comment by DARKTORTA** [comment]
![Screenshot_2024-10-15-08-21-09-017_com discord-edit](https://github.com/user-attachments/assets/c50c6a3c-99f1-42ca-9a50-feaf673f968b)
A dev told me this, basically psych 1.0 it's broken (for now)

**Comment by SantiagoCalebe** [comment]
Yeah, so mark as solved
