### ISSUE TITLE
Can't play whitty

### ISSUE THREAD

**Issue by ITZDAULTIMATEG** [ShadowMario/FNF-PsychEngine#15710]
### Describe your bug here.

I tried playing the Whitty mod, and yet it was telling me that I'm using an outdated engine and should upgrade to the latest engine (I'm currently using 1.0) i'm not sure why this is happening, but it is.
![Screenshot (92)](https://github.com/user-attachments/assets/16c6538d-e1e0-46c0-8906-322701b0274f)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Shadow06735** [comment]
the Whitt mod probably created a separate character for bf, as u can see from the text like what @SantiagoCalebe mentioned. U gotta port over the custom bf character from the whitty build to the 1.0 build

**Comment by SantiagoCalebe** [comment]
Close the issue.
