### ISSUE TITLE
discord_rpc was not found, does it need to be installed?

### ISSUE THREAD

**Issue by erasedcardsx** [ShadowMario/FNF-PsychEngine#1571]
### Describe your problem here.

every time i type lime test windows to compile, i get that error. i have everything installed, but it's just not working. is there a solution, or do i just gotta wait it out?
![Screenshot (85)](https://user-images.githubusercontent.com/95380260/144303939-59ffb82a-fa47-4195-864c-c4161261f30e.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

all i've done is add a new character so far, to test if it works.

**Comment by HiroOfc** [comment]
did u followed all FNF's original repo? U need to install discord_rpc with the code `haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc`

**Comment by erasedcardsx** [comment]
i have. the exact command will not work. it says it's installing and already installed, but when i run lime test windows, i get the error

**Comment by HiroOfc** [comment]
> i have. the exact command will not work. it says it's installing and already installed, but when i run lime test windows, i get the error
> […](#)
> Sent from my iPhone
> On Dec 1, 2021, at 15:54, HiroMizukiOFC ***@***.***> wrote: ﻿ did u followed all FNF's original repo? U need to install discord_rpc with the code haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

ok, i think you will need to uninstall and install it again

1 - Use the command `haxelib remove discord_rpc`
2 - The same command i have written before, `haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc`

**Comment by erasedcardsx** [comment]
> > i have. the exact command will not work. it says it's installing and already installed, but when i run lime test windows, i get the error
> > […](#)
> > Sent from my iPhone
> > On Dec 1, 2021, at 15:54, HiroMizukiOFC _**@**_.***> wrote: ﻿ did u followed all FNF's original repo? U need to install discord_rpc with the code haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> ok, i think you will need to uninstall and install it again
> 
> 1 - Use the command `haxelib remove discord_rpc` 2 - The same command i have written before, `haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc`

this is the new error. source/ModsMenuState.hx:388: characters 6-28 : {+ length : Int } should be String
source/ModsMenuState.hx:392: characters 6-42 : {+ length : Int } should be String
source/ModsMenuState.hx:396: characters 36-47 : Array access is not allowed on {+ length : Int }
source/ModsMenuState.hx:396: characters 36-47 : For function argument 'Red'

what do i do now

**Comment by HiroOfc** [comment]
now, read the issue #1524, people have fully answered here

**Comment by erasedcardsx** [comment]
> now, read the issue #1524, people have fully answered here

i'll try it once i get back home. i'm getting starbucks atm.

**Comment by HiroOfc** [comment]
> > now, read the issue #1524, people have fully answered here
> 
> i'll try it once i get back home. i'm getting starbucks atm.

ok. Oh wait, i've found a better answer, it is from #1430

**Comment by erasedcardsx** [comment]
> > > now, read the issue #1524, people have fully answered here
> > 
> > 
> > i'll try it once i get back home. i'm getting starbucks atm.
> 
> ok. Oh wait, i've found a better answer, it is from #1430

i don't exactly understand that one. i need in depth explaining because i can't comprehend stuff lolz

**Comment by HiroOfc** [comment]
> > > > now, read the issue #1524, people have fully answered here
> > > 
> > > 
> > > i'll try it once i get back home. i'm getting starbucks atm.
> > 
> > 
> > ok. Oh wait, i've found a better answer, it is from #1430
> 
> i don't exactly understand that one. i need in depth explaining because i can't comprehend stuff lolz

lmao. Basically, u will need to deactivate the codes with the word "mods" at MainMenuState (lines 38 and 235-236)

**Comment by erasedcardsx** [comment]
> > > > > now, read the issue #1524, people have fully answered here
> > > > 
> > > > 
> > > > i'll try it once i get back home. i'm getting starbucks atm.
> > > 
> > > 
> > > ok. Oh wait, i've found a better answer, it is from #1430
> > 
> > 
> > i don't exactly understand that one. i need in depth explaining because i can't comprehend stuff lolz
> 
> lmao. Basically, u will need to deactivate the codes with the word "mods" at MainMenuState (lines 38 and 235-236)

OH shit i get it now, i'll try this and see if it works. if it doesn't, i probs will leave the question open for a bit

**Comment by HiroOfc** [comment]
> > > > > > now, read the issue #1524, people have fully answered here
> > > > > 
> > > > > 
> > > > > i'll try it once i get back home. i'm getting starbucks atm.
> > > > 
> > > > 
> > > > ok. Oh wait, i've found a better answer, it is from #1430
> > > 
> > > 
> > > i don't exactly understand that one. i need in depth explaining because i can't comprehend stuff lolz
> > 
> > 
> > lmao. Basically, u will need to deactivate the codes with the word "mods" at MainMenuState (lines 38 and 235-236)
> 
> OH shit i get it now, i'll try this and see if it works. if it doesn't, i probs will leave the question open for a bit

ok bro lol

**Comment by erasedcardsx** [comment]
> > > > > > > now, read the issue #1524, people have fully answered here
> > > > > > 
> > > > > > 
> > > > > > i'll try it once i get back home. i'm getting starbucks atm.
> > > > > 
> > > > > 
> > > > > ok. Oh wait, i've found a better answer, it is from #1430
> > > > 
> > > > 
> > > > i don't exactly understand that one. i need in depth explaining because i can't comprehend stuff lolz
> > > 
> > > 
> > > lmao. Basically, u will need to deactivate the codes with the word "mods" at MainMenuState (lines 38 and 235-236)
> > 
> > 
> > OH shit i get it now, i'll try this and see if it works. if it doesn't, i probs will leave the question open for a bit
> 
> ok bro lol

it ran for about 10 min, then froze. just started back up, idk if its working tho

**Comment by erasedcardsx** [comment]
> > > > > > > now, read the issue #1524, people have fully answered here
> > > > > > 
> > > > > > 
> > > > > > i'll try it once i get back home. i'm getting starbucks atm.
> > > > > 
> > > > > 
> > > > > ok. Oh wait, i've found a better answer, it is from #1430
> > > > 
> > > > 
> > > > i don't exactly understand that one. i need in depth explaining because i can't comprehend stuff lolz
> > > 
> > > 
> > > lmao. Basically, u will need to deactivate the codes with the word "mods" at MainMenuState (lines 38 and 235-236)
> > 
> > 
> > OH shit i get it now, i'll try this and see if it works. if it doesn't, i probs will leave the question open for a bit
> 
> ok bro lol

hey, could you help with a different thing? if so, email me at erasedcardsx@icloud.com
