### ISSUE TITLE
skipping cutscenes

### ISSUE THREAD

**Issue by isatsou** [ShadowMario/FNF-PsychEngine#15717]
### What feature do you want to get added on the **base** engine?

pls

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by Shadow06735** [comment]
that’s already a thing in the engine, read the changelog

“ - Cutscenes are now skippable
- Dialogues are now skippable”

**Comment by isatsou** [comment]
I see it
But why there isn't on mp4 files?
Like the weekend 1 vid thing

**Comment by ShadowMario** [comment]
You can literally hold enter to skip
