### ISSUE TITLE
how do i set it to camHUD in 1.0

### ISSUE THREAD

**Issue by Gabopogi01** [ShadowMario/FNF-PsychEngine#15719]
### Describe your problem here.

setObjectCamera('vignette', 'camHUD')
like this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Contra-Sakar** [comment]
`setObjectCamera` doesn't work in version 1.0. Temporarily, you can use this:
`setProperty('Object.camera', instanceArg('NameCamera'), false, true)`
Use that until it's fixed.

**Comment by Gabopogi01** [comment]
like this?
setProperty('vignette.camera', 'other', false, true)

**Comment by Contra-Sakar** [comment]
`setProperty('vignette.camera', instanceArg('camOther'), false, true)`

**Comment by Gabopogi01** [comment]
thx-

**Comment by PoekmasterLegendsv2** [comment]
> `setProperty('vignette.camera', instanceArg('camOther'), false, true)`

Wait but what do i put in camOther?
