### ISSUE TITLE
Is someone else having problem with setObjectCamera()?

### ISSUE THREAD

**Issue by Tiphy03** [ShadowMario/FNF-PsychEngine#15728]
### Describe your bug here.

![image](https://github.com/user-attachments/assets/ccb9ee25-7e8a-4c1f-94a0-011016e5ac01)
And yes, this happens to every single time i use setObjectCamera, and yes the object tag exists, it even checks if it actually exists before calling the function
Note this doesn't happens on 1.0 pre-release

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope that's Psych Engine 1.0

**Comment by SantiagoCalebe** [comment]
Psych Engine 1.0 changed the LUA Script API, so bunch of LUA scripts won't work.

**Comment by Tiphy03** [comment]
Yes, but how do i fix this error? setObjectCamera() doesn't work anymore
Is there any other functions that do the same thing?

Or we'll have to wait for an hotfix update?

**Comment by SantiagoCalebe** [comment]
You and everyone will have to wait for the hotfix update, that maybe will come soon, idk

**Comment by underscoreBon** [comment]
Had this bug too, the game says "hud" and "other" are invalid cameras

**Comment by Contra-Sakar** [comment]
`setObjectCamera` doesn't work in version 1.0. Temporarily, you can use this:
`setProperty('Object.camera', instanceArg('NameCamera'), false, true)`
 Use that until it's fixed.

**Comment by Tiphy03** [comment]
> `setObjectCamera` doesn't work in version 1.0. Temporarily, you can use this: `setProperty('Object.camera', instanceArg('NameCamera'), false, true)` Use that until it's fixed.

That works, thank you very much

**Comment by Tiphy03** [comment]
Using this method i made this:
```lua
local actualSetObjectCamera = setObjectCamera

function setObjectCamera(object,camera)
	if stringStartsWith(version, '1.0') then
		if string.lower(camera) == "game" then camera = "camGame" end
		if string.lower(camera) == "camgame" then camera = "camGame" end
	
		if string.lower(camera) == "hud" then camera = "camHUD" end
		if string.lower(camera) == "camhud" then camera = "camHUD" end

		if string.lower(camera) == "other" then camera = "camOther" end
		if string.lower(camera) == "camother" then camera = "camOther" end

		if (camera == "camGame") or (camera == "camHUD") or (camera == "camOther") then
			setProperty(object..'.camera',instanceArg(camera),false,true)
		end
	else
		actualSetObjectCamera(object,camera)
	end
end
```
Which replaces setObjectCamera function with this method for v1.0

**Comment by AziziPGM** [comment]
and with your code @LizSparkle i made this:

`local actualSetObjectCamera = setObjectCamera function setObjectCamera(object,camera) if stringStartsWith(version, '1.0') then if string.lower(camera) == "game" then camera = "camGame" end if string.lower(camera) == "camgame" then camera = "camGame" end if string.lower(camera) == "hud" then camera = "camHUD" end if string.lower(camera) == "camhud" then camera = "camHUD" end if string.lower(camera) == "other" then camera = "camOther" end if string.lower(camera) == "camother" then camera = "camOther" end if (camera == "camGame") or (camera == "camHUD") or (camera == "camOther") then setProperty(object..'.camera',instanceArg(camera),false,true) end else actualSetObjectCamera(object,camera) end end`

this is all your code in **_[1](https://en.wikipedia.org/wiki/1)_** line
