### ISSUE TITLE
Built-in mod browser OR an API to load, unload, and refresh mods for the engine.

### ISSUE THREAD

**Issue by TooManyFactoryResets** [ShadowMario/FNF-PsychEngine#15720]
### What feature do you want to get added on the **base** engine?

I'm curious if there's some way to have a mod browser inside the game itself. Like changing the mods section to have a download button for downloading mods. This could use Gamebanana's API or maybe integrate FileDaddy into the base engine somehow.

If putting a mod browser inside the game is not possible, could there be an API to change the mod's states inside the engine.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
Not happening at this point
