### ISSUE TITLE
How can I change noteSplash to Lua in 1.0

### ISSUE THREAD

**Issue by JuanSebas1247** [ShadowMario/FNF-PsychEngine#15738]
### What is your question?

There is no need to explain what I asked for., If you need more information let me know

**Comment by FrailMods** [comment]
Well with the amount of Context you've given it's difficult what you mean... If you are directly meaning to force a certain NoteSplash in a song that's simple enough as Inputting the name of the file into 'Note Splashes Texture' in the 'Data' category in the Song's chart... But doing so with Lua Is out of my Knowledge... Still I hope this provides some help...

**Comment by JuanSebas1247** [comment]
Well, it's through Lua, but I don't know if I have to use "SetPropertyFromGroup""

**Comment by JuanSebas1247** [comment]
setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'noteSplashes/noteSplashes-diamond')

I tried this but it doesn't even load as if it didn't exist

**Comment by JuanSebas1247** [comment]
I already did it, I changed the variable 'noteSplashTexture' to "noteSplashData.texture". and it worked, I still appreciate you helping me.
