### ISSUE TITLE
Support for older mods in the newer version

### ISSUE THREAD

**Issue by isatsou** [ShadowMario/FNF-PsychEngine#15731]
### What feature do you want to get added on the **base** engine?

So having a button that let's you choose a different api or something

### To test your sight, and reliability, please select the option of what should NOT be requested.

Better LUA mod support idea

**Comment by CreamAlphaWolfram** [comment]
Hmmmmm...

I think there is already a document in the wiki saying that you should make a compatibility version of the lua for the higher version and the ways to do it...

**Comment by ShadowMario** [comment]
That's not how coding works
