### ISSUE TITLE
How do I do a Lua Time Skip?

### ISSUE THREAD

**Issue by CreamAlphaWolfram** [ShadowMario/FNF-PsychEngine#15748]
### Describe your problem here.

I'm dealing with my pause script and found out a problem with lua manual pausing, when using the lua pause the notes goes nowhere (It's not a bug, my script messed with `playbackRate`!), so I'm taking Phira's solution - putting back the song's progression by several seconds and resuming the song.

*HOWEVER*

I found out I'm too dumb to write a time-skip function.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Actually, I'm dealing with the Extra Keys version of this engine, but the things I'm asking here *will* do the same thing in PE 0.7.3. So... I'm considering this as a PE 0.7.3 help wanted.

**Comment by JHAM25** [comment]
Entonces estas haciendo un script  de pausa y quieres que al reanudar la canción se devuelva unos segundos?

**Comment by CreamAlphaWolfram** [comment]
> Entonces estas haciendo un script de pausa y quieres que al reanudar la canción se devuelva unos segundos?

Err, I cannot understand the language you're speaking, sorry...

**Comment by JHAM25** [comment]
So you're making a pause script and you want to skip back a few seconds when you resume the song?

**Comment by JHAM25** [comment]
> > Entonces estás haciendo un guión de pausa y quieres que al reanudar la canción se devuelva unos segundos?
> 
> Err, no entiendo qué quieres decir aquí, lo siento...

So you're making a pause script and you want to skip back a few seconds when you resume the song? or what do you want to do?

**Comment by CreamAlphaWolfram** [comment]
> > > Entonces estás haciendo un guión de pausa y quieres que al reanudar la canción se devuelva unos segundos?
> > 
> > 
> > Err, no entiendo qué quieres decir aquí, lo siento...
> 
> So you're making a pause script and you want to skip back a few seconds when you resume the song? or what do you want to do?

Yup, exactly! I want it to work like: every time you resume, it jump back a few seconds just for you to catch the rhythm again so you can perform just as normal without abruptly continuing and getting misses/shits/bads

**Comment by JHAM25** [comment]
> > > > Entonces ¿estás haciendo un guión de pausa y quieres que al reanudar la canción se devuelva unos segundos?
> > > 
> > > 
> > > Err, no entiendo qué quieres decir aquí, lo siento...
> > 
> > 
> > Entonces, ¿estás haciendo un script de pausa y quieres retroceder unos segundos cuando reanudas la canción? ¿O qué quieres hacer?
> 
> ¡Sí, exactamente! Quiero que funcione así: cada vez que reanudes la ejecución, retroceda unos segundos solo para que puedas retomar el ritmo y puedas realizar la ejecución con normalidad sin continuar de manera abrupta y tener errores, errores o errores.

Pues lo hice de esta manera:

https://github.com/user-attachments/assets/357c6a1d-13cc-4227-8e68-edaab42fe709

**Comment by CreamAlphaWolfram** [comment]
Yup, this is!

**Comment by CreamAlphaWolfram** [comment]
So... How do I get the effect then? (I only need essential code snippets lol)

**Comment by JHAM25** [comment]
Es este:
function onResume()
    setPropertyFromClass('flixel.FlxG', 'sound.music.time', getPropertyFromClass('flixel.FlxG', 'sound.music.time') - 1000)
    setProperty('vocals.time', getProperty('vocals') - 1000)
end

**Comment by CreamAlphaWolfram** [comment]
oh oh oh, thanks for your help!!
This is solved lol
