### ISSUE TITLE
Better Audio Quality Output

### ISSUE THREAD

**Issue by VoidedBattery** [ShadowMario/FNF-PsychEngine#15744]
### What feature do you want to get added on the **base** engine?

Whenever I use the Psych Engine playback feature in the freeplay menu, I always notice that there's something that's a little different compared to the file that it uses.

The only difference is that the audio file is in a really high quality, but then the engine kind of roughs it up a bit. It's not noticeable to much, so I don't mind if this gets rejected, but I'd appreciate it if an upcoming hotfix update preserves even more the audio quality during gameplay.

Again, if high audio quality conflicts with optimization, then I'm alright if this isn't the best idea. Just wanted to give a heads up.

If you want to see it for yourself, listen to a song using the playback feature in the freeplay menu, then compare it to what you listen to when you open a different audio listening software like Media Player, Audacity, etc.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
This might have solved it https://github.com/ShadowMario/FNF-PsychEngine/pull/15536
