### ISSUE TITLE
Downscroll for chart editor

### ISSUE THREAD

**Issue by Megood1114** [ShadowMario/FNF-PsychEngine#15741]
### What feature do you want to get added on the **base** engine?

Me want downscroll for chart editor cause upscroll sucks.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by SantiagoCalebe** [comment]
You mean, test chart menu?

**Comment by Megood1114** [comment]
![image](https://github.com/user-attachments/assets/3cb64baa-9a9f-4945-b085-e742a9ab44d0)
this

**Comment by Megood1114** [comment]
> You mean, test chart menu?

i meant this 
![image](https://github.com/user-attachments/assets/253377b0-4f8d-4a4e-affe-331558fd4f81)

**Comment by SantiagoCalebe** [comment]
I don't think he will add this

**Comment by MaksPRO12667** [comment]
Why is this necessary?

**Comment by NimiPvPGamer** [comment]
> Why is this necessary?

Because it is a basic feature that is more of a preference type of setting. I’d really like it to be ingame because as a mania charter, on osu! its downscroll anyways, so yeah

**Comment by ShadowMario** [comment]
I am not doing it because I did not make the editor with that in mind so it would take a lot of rework to do that

**Comment by Josephjr05** [comment]
If every rhythm game including the Vortex editor (ArrowVortex), it might as well have downscroll tbh. Alot of rhythm game mappers would love to try charting on here if it were to exist but sadly it won't be a thing.
