### ISSUE TITLE
Wtf does this mean at all?

### ISSUE THREAD

**Issue by ChargerDoinDaCode** [ShadowMario/FNF-PsychEngine#1574]
### Describe your bug here.

Ok so im tryna build psych engine so i pull up command prompt and i type: cd (file location for psych engine) and then i put down Lime test windows and then this error pops up saying:

source/ModsMenuState.hx:388: characters 6-28 : {+ length : Int } should be String
source/ModsMenuState.hx:392: characters 6-42 : {+ length : Int } should be String
source/ModsMenuState.hx:396: characters 36-47 : Array access is not allowed on {+ length : Int }
source/ModsMenuState.hx:396: characters 36-47 : For function argument 'Red'

Can you tell me whats going on?

### Command Prompt/Terminal logs (if existing)

```bash
source/ModsMenuState.hx:388: characters 6-28 : {+ length : Int } should be String
source/ModsMenuState.hx:392: characters 6-42 : {+ length : Int } should be String
source/ModsMenuState.hx:396: characters 36-47 : Array access is not allowed on {+ length : Int }
source/ModsMenuState.hx:396: characters 36-47 : For function argument 'Red'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I haven't.

**Comment by CrusherMods** [comment]
look at my pull request in the github to fix the problem I found a solution

**Comment by HiroOfc** [comment]
duplicate of #1524

**Comment by ChargerDoinDaCode** [comment]
> duplicate of #1524

that didn't help either in fact made the error worse

**Comment by ChargerDoinDaCode** [comment]
> look at my pull request in the github to fix the problem I found a solution

Didn't work it just bugged it out more

**Comment by HiroOfc** [comment]
> > look at my pull request in the github to fix the problem I found a solution
> 
> Didn't work it just bugged it out more

#1430 then, a person has answered better about it

**Comment by DaBanana64** [comment]
It got fixed in the latest commit. Try doing a git pull.
