### ISSUE TITLE
Authorization/permission to change the license of my Psych Engine fork 

### ISSUE THREAD

**Issue by Renan2010** [ShadowMario/FNF-PsychEngine#15752]
### What is your question?

Can I change the Apache license to GPLv3? I'm kindly asking Shadow Mario or some project representative  for permission to change the license. 
My fork [here](https://github.com/Renan2010/RL-ENGINE)
If they deny the exchange, I will continue with Apache without any problems.

**Comment by ShadowMario** [comment]
Why would you want to change the license?

**Comment by Renan2010** [comment]
For my project to be completely free and transparent Shadow Mario :)

**Comment by Renan2010** [comment]
But if you refuse I will install Apache without any problems

**Comment by crowplexus** [comment]
I would highly recommend keeping Apache 2 around, while said license is compatible with GPL 3, Psych Engine is a fork of the otiginal Friday Night Funkin' (V0.2.7.1) - and for a multitude of reasons, I'd say you should check what licenses are compatible with Apache 2, and then make your decision from there

hope this helps <3

**Comment by Renan2010** [comment]
So I went for Apache 2.0 same thanks guys :)

**Comment by Renan2010** [comment]
I have already changed my project to Apache 2.0

**Comment by Renan2010** [comment]
Thank you guys, you are the best developers
