### ISSUE TITLE
I can't install lime

### ISSUE THREAD

**Issue by RedexDev** [ShadowMario/FNF-PsychEngine#15757]
### Describe your problem here.

![Captura de pantalla (1)](https://github.com/user-attachments/assets/2d4aff68-5a87-4411-a097-2acab36a7f5d)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by megalives717** [comment]
use command haxelib install lime

**Comment by RedexDev** [comment]
> use command haxelib install lime

that's what I did and I got that error

**Comment by RedexDev** [comment]
> use command haxelib install lime

I even tried if it was the driver check but it didn't work either

**Comment by a-random441** [comment]
Install certificate to https://lib.haxe.org/
Or check your time settings
Or install it manually by
```cmd
haxelib install "zip-name.zip"
```

**Comment by RedexDev** [comment]
> Install certificate to https://lib.haxe.org/ (Search Google for how to install certificate) Or check your time settings Or install it manually by
> 
> ```batchfile
> haxelib install "zip-name.zip"
> ```

thank you very much, but I still ended up using a workaround which is with this haxe command to block the http or ssl:

haxelib install libName -R http://lib.haxe.org/

that what I leave there in case someone had the same error that happened to me, well thanks for your help I also tried it to see how it worked but it did not work in my case but I thank you anyway. 👍
