### ISSUE TITLE
setObjectCamera doesn't work on sprites

### ISSUE THREAD

**Issue by CappyHef** [ShadowMario/FNF-PsychEngine#15756]
### Describe your bug here.

so I was about to show the owner of the mod what progress had been done when the custom hud broke, after a few mins I found out it was `setObjectCamera`, it only works on graphics and not sprites for some reason,

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by acap09** [comment]
just do
```lua
callMethod('spritenamehere.set_camera', {instanceArg('camGame'/'camHUD'/'camOther')})
```

**Comment by ShadowMario** [comment]
Fixed at https://github.com/ShadowMario/FNF-PsychEngine/commit/f100b63d95508295d36e06baf39fefe69f1e3fd5

**Comment by PoekmasterLegendsv2** [comment]
> just do (assuming your using 1.0)
> 
> ```lua
> callMethod('spritenamehere.set_camera', {instanceArg('camGame'/'camHUD'/'camOther')})
> ```

so where do i put this so far i have only this
function onCreate()

   setProperty('healthBarBG.visible', false)

   makeLuaSprite('healthBarBGNEW', 'Healthcover', 0, 0)
   setObjectCamera('healthBarBGNEW', 'camHUD')
   addLuaSprite('healthBarBGNEW')
end
