### ISSUE TITLE
Engine Running in the Background

### ISSUE THREAD

**Issue by TofpFL** [ShadowMario/FNF-PsychEngine#15758]
### What feature do you want to get added on the **base** engine?

I want an option to let the Engine run on its own if you let it meaning you could do charts and wait for the right section while doing something else. (IDK, it just seems more fun)

I just wanted to type for shit so... If you do decide that it would be useful, then have fun trying to implement it in 1.27 lmao

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by TofpFL** [comment]
Also, can't you take a Lua script and add winning icons from there? (I used to have a Lua Script that would tell me the current time and it'd be useful as a UI prop for rendering videos. It was mainly there to track time.

**Comment by Stefan2008Git** [comment]
Just disable auto pause option?

**Comment by Shadow06735** [comment]
There’s something called auto-pause in options. Disable that

**Comment by ShadowMario** [comment]
Disable auto pause in Gameplay settings
