### ISSUE TITLE
How to make scrolling bg in main menu

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#15761]
### Describe your problem here.

how

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by KELOTOMU** [comment]
You need to use the `flixel.addons.display.FlxBackdrop` module to create a infinitely scrolling background.
To actually make it move/scroll, you gotta set its velocity which you can do so by `obj.velocity.set(x, y)`

[https://api.haxeflixel.com/flixel/addons/display/FlxBackdrop.html](url)

**Comment by MaksPRO12667** [comment]
> You need to use the `flixel.addons.display.FlxBackdrop` module to create a infinitely scrolling background. To actually make it move/scroll, you gotta set its velocity which you can do so by `obj.velocity.set(x, y)`
> 
> [https://api.haxeflixel.com/flixel/addons/display/FlxBackdrop.html](url)

Thank you very much

**Comment by MaksPRO12667** [comment]
> You need to use the `flixel.addons.display.FlxBackdrop` module to create a infinitely scrolling background. To actually make it move/scroll, you gotta set its velocity which you can do so by `obj.velocity.set(x, y)`
> 
> [https://api.haxeflixel.com/flixel/addons/display/FlxBackdrop.html](url)

Uhhh... i did 'import flixel.addons.display.FlxBackdrop;' and 'space.velocity.set(20, 0);' but bg doesn't infinitely, bg just scroll right and it's all

**Comment by MaksPRO12667** [comment]
> > You need to use the `flixel.addons.display.FlxBackdrop` module to create a infinitely scrolling background. To actually make it move/scroll, you gotta set its velocity which you can do so by `obj.velocity.set(x, y)`
> > [https://api.haxeflixel.com/flixel/addons/display/FlxBackdrop.html](url)
> 
> Uhhh... i did 'import flixel.addons.display.FlxBackdrop;' and 'bg.velocity.set(20, 0);' but bg doesn't infinitely, bg just scroll right and it's all (I am on 0.7.2h)

![image](https://github.com/user-attachments/assets/5b539b87-010b-4b24-8373-a1f64e579dad)
This is bg

**Comment by KELOTOMU** [comment]
> > > You need to use the `flixel.addons.display.FlxBackdrop` module to create a infinitely scrolling background. To actually make it move/scroll, you gotta set its velocity which you can do so by `obj.velocity.set(x, y)`
> > > [https://api.haxeflixel.com/flixel/addons/display/FlxBackdrop.html](url)
> > 
> > 
> > Uhhh... i did 'import flixel.addons.display.FlxBackdrop;' and 'bg.velocity.set(20, 0);' but bg doesn't infinitely, bg just scroll right and it's all (I am on 0.7.2h)
> 
> ![image](https://private-user-images.githubusercontent.com/114620759/379849057-5b539b87-010b-4b24-8373-a1f64e579dad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MjIzMTIsIm5iZiI6MTcyOTgyMjAxMiwicGF0aCI6Ii8xMTQ2MjA3NTkvMzc5ODQ5MDU3LTViNTM5Yjg3LTAxMGItNGIyNC04MzczLWExZjY0ZTU3OWRhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwMjA2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWUyNmU0ZGEzZTEwYmRhYmY5MWRlZGRlZWFlZTc0MzVjMjJiNTBlZmQ3YzFjOGYwYWYyOWMzMmYzNzY4ZGE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.L8evGO0vF3BGK63C4JwXK9bAFqKHkAUSHtoGEz8OvbM) This is bg

`var space:FlxBackdrop = new FlxBackdrop(Paths.image('Space_sus'), X)`
replace it with this and it should work

**Comment by MaksPRO12667** [comment]
> var space:FlxBackdrop = new FlxBackdrop(Paths.image('Space_sus'), X)

Thank you very much, it worked
