### ISSUE TITLE
i cant add more than 1 sprite in stage editor

### ISSUE THREAD

**Issue by SimonJeez** [ShadowMario/FNF-PsychEngine#15768]
### Describe your bug here.

so i went to stage editor and i wanted to make a bg, but when i try to add the second sprite, it just doesnt open the selecting sprite window. and if you delete the first sprite and try adding another, it still doesnt work.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i edited nothing except for adding sprites for bg in my modpack

**Comment by PSI3x** [comment]
For adding sprites into the stage, it must be outside of the /mods/images folder to work. There's a bug that makes certain buttons unresponsive when the asset is already in the images folder.
They SERIOUSLY need to make a hotfix for this...

**Comment by FailedToLoad-Atom** [comment]
> For adding sprites into the stage, it must be outside of the /mods/images folder to work. There's a bug that makes certain buttons unresponsive when the asset is already in the images folder. They SERIOUSLY need to make a hotfix for this...

its not really that big problem if you just dont put it in images before

**Comment by PSI3x** [comment]
> its not really that big problem if you just dont put it in images before
The problem is that it's impossible to save a stage if you add an animated object: Since the animations will only work if both the image and xml file are in the images folder.

**Comment by PSI3x** [comment]
Perfect! I  hope the fixed version comes out soon, I'm excited to try out the stage editor in its full potential :)
