### ISSUE TITLE
I Failed Build Source Code

### ISSUE THREAD

**Issue by megalives717** [ShadowMario/FNF-PsychEngine#15778]
### Describe your problem here.

https://github.com/user-attachments/assets/c2b3e1c5-371a-4ad0-a8c6-afa848ed2342

plsase help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

1.0

**Comment by Shadow06735** [comment]
replace line 329 with this:
pico.anim.onComplete = null;

and replace line 332 with this:
pico.anim.onComplete = picoStressCycle;

**Comment by megalives717** [comment]
i can't find file

**Comment by megalives717** [comment]
not working

**Comment by Shadow06735** [comment]
> not working

Still gives the same issue?

**Comment by KELOTOMU** [comment]
pico.anim.onComplete = function to remove/add pico

**Comment by megalives717** [comment]
is no longer work

**Comment by megalives717** [comment]
ApplicationMain.exe Is Work
