### ISSUE TITLE
change character event question

### ISSUE THREAD

**Issue by StinkTheStinker** [ShadowMario/FNF-PsychEngine#15776]
### What is your question?

is it possible to fix the change character event not working properly while doTweenColor is happening

https://github.com/user-attachments/assets/c8ee2e5a-9534-4f7f-8460-a502ab51f085

**Comment by MaksPRO12667** [comment]
can you please show code?

**Comment by StinkTheStinker** [comment]
note: this is a forked psych engine im using, don't think the event, nor the tweencolor has been changed

**Comment by StinkTheStinker** [comment]
> can you please show code?

i did not see that reply for some reason, hold on

**Comment by StinkTheStinker** [comment]
```
function onUpdate()
	if curBeat == 96 then
		doTweenColor('dfgsdfgsd52fgs', 'dad', 'FFAAAA', 574.04)
		doTweenColor('dfgsdfgsdfgs', 'boyfriend', 'FFAAAA', 574.04)

	end
end
```

**Comment by MaksPRO12667** [comment]
> i did not see that reply for some reason, hold on



> function onUpdate()
> 	if curBeat == 96 then
> 		doTweenColor('dfgsdfgsd52fgs', 'dad', 'FFAAAA', 574.04)
> 		doTweenColor('dfgsdfgsdfgs', 'boyfriend', 'FFAAAA', 574.04)
> 
> 	end
> end

Try count Step where is your event located (for example 384 Step)

function onUpdate()
	if curStep == 385 then -- Step plus 1(don't ask, for some reason it works this way)
		doTweenColor('dfgsdfgsd52fgs', 'dad', 'FFAAAA', 574.04)
		doTweenColor('dfgsdfgsdfgs', 'boyfriend', 'FFAAAA', 574.04)

	end
end

And for me it worked

**Comment by StinkTheStinker** [comment]
i ment that when the character change event happens while the tween color is happening on the opponent, the old opponent does not disapear, the offset doesnt change as well

**Comment by StinkTheStinker** [comment]
https://github.com/user-attachments/assets/3534110c-cbb0-4dd1-8529-232ce800f3af

**Comment by MaksPRO12667** [comment]
> 2024-10-22.18-54-54.mp4

Try 'curStep == 3999'

**Comment by StinkTheStinker** [comment]
thats the step where the piano started, which was a couple seconds before recording the thing

**Comment by StinkTheStinker** [comment]
well, couple steps after

**Comment by MaksPRO12667** [comment]
Ok, so what's version of engine? I trying to check this

**Comment by StinkTheStinker** [comment]
this fork of psych engine uses v0.6.3

**Comment by nguyenkiet1234d** [comment]
Wtf


> > vì lý do nào đó tôi không thấy câu trả lời đó, hãy đợi đã
> 
> > hàm onUpdate() 
> > nếu curBeat == 96 thì 
> > doTweenColor('dfgsdfgsd52fgs', 'bố', 'FFAAAA', 574.04) 
> > doTweenColor('dfgsdfgsdfgs', 'bạn trai', 'FFAAAA', 574.04)
> > kết thúc kết 
> > thúc
> 
> Hãy thử đếm Bước sự kiện của bạn nằm ở đâu (ví dụ: Bước 384)
> 
> hàm onUpdate() nếu curStep == 385 thì -- Bước cộng thêm 1 (đừng hỏi, vì lý do nào đó nó hoạt động theo cách này) doTweenColor('dfgsdfgsd52fgs', 'dad', 'FFAAAA', 574.04) doTweenColor('dfgsdfgsdfgs', 'boyfriend', 'FFAAAA', 574.04)
> 
> ```
> end
> ```
> 
> kết thúc
> 
> Và đối với tôi thì nó hoạt động Tại sao lại là các bước? Ờ... Màu sắc thay đổi nhanh hơn. Nếu bạn viết 'curBeat == 97 thì' thì sẽ mất hơn một giây để thay đổi màu sắc

Wtf 
You just need to doTweenClorl back to the original before executing the command to change the character, that is, turn off the color, then execute the command to change the character and then change the color.

**Comment by nguyenkiet1234d** [comment]
> Cái quái gì thế này
> 
> > > bởi vì lý do nào mà tôi không tìm thấy câu trả lời, hãy chờ đợi
> > 
> > 
> > > hàm onUpdate() 
> > > if curBeat == 96 thì 
> > > doTweenColor('dfgsdfgsd52fgs', 'bố', 'FFAAAA', 574.04) 
> > > doTweenColor('dfgsdfgsdfgs', 'bạn trai', 'FFAAAA', 574.04) 
> > > end end 
> > > end
> > 
> > 
> > Hãy thử đếm sự kiện Bước của bạn ở đâu (Ví dụ: Bước 384)
> > hàm onUpdate() if curStep == 385 thì -- Bước cộng thêm 1 (đừng hỏi, vì lý do nào nó hoạt động theo cách này) doTweenColor('dfgsdfgsd52fgs', 'dad', 'FFAAAA', 574.04) doTweenColor( 'dfgsdfgsdfgs', 'bạn trai', 'FFAAAA', 574.04)
> > ```
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > kết thúc
> > Và đối với tôi thì nó hoạt động tại sao lại là các bước? Ờ... Màu sắc thay đổi nhanh hơn. Nếu bạn viết 'curBeat == 97 thì' sẽ mất hơn một giây để thay đổi màu sắc
> 
> Wtf Bạn chỉ cần doTweenClorl trở về ban đầu trước khi thực hiện lệnh đổi ký tự, tức là tắt màu đi, sau đó thực hiện lệnh đổi ký tự rồi mới đổi màu.

And I once encountered this error and fixed it. 
For example
function onUpdate()
doTweenColor('dfgsdfgsd52fgs1', 'dad', '', 0.1, 'linear')
doTweenColor( 'dfgsdfgsdfgs1', 'boyfriend', '', 0.1,'linear')
if curStep == 385 then
triggerEvent('change character', '','')--Fill in yourself
end
if curStep == 386 then
doTweenColor('dfgsdfgsd52fgs2', 'dad', 'FFAAAA', 0.1, 'linear')
doTweenColor( 'dfgsdfgsdfgs2', 'boyfriend', 'FFAAAA', 0.1,'linear')
end
end

**Comment by StinkTheStinker** [comment]
forget it, just not going to use the script

**Comment by MaksPRO12667** [comment]
> > Cái quái gì thế này
> > > > bởi vì lý do nào mà tôi không tìm thấy câu trả lời, hãy chờ đợi
> > > 
> > > 
> > > > hàm onUpdate()
> > > > if curBeat == 96 thì
> > > > doTweenColor('dfgsdfgsd52fgs', 'bố', 'FFAAAA', 574.04)
> > > > doTweenColor('dfgsdfgsdfgs', 'bạn trai', 'FFAAAA', 574.04)
> > > > end end
> > > > end
> > > 
> > > 
> > > Hãy thử đếm sự kiện Bước của bạn ở đâu (Ví dụ: Bước 384)
> > > hàm onUpdate() if curStep == 385 thì -- Bước cộng thêm 1 (đừng hỏi, vì lý do nào nó hoạt động theo cách này) doTweenColor('dfgsdfgsd52fgs', 'dad', 'FFAAAA', 574.04) doTweenColor( 'dfgsdfgsdfgs', 'bạn trai', 'FFAAAA', 574.04)
> > > ```
> > > end
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > kết thúc
> > > Và đối với tôi thì nó hoạt động tại sao lại là các bước? Ờ... Màu sắc thay đổi nhanh hơn. Nếu bạn viết 'curBeat == 97 thì' sẽ mất hơn một giây để thay đổi màu sắc
> > 
> > 
> > Wtf Bạn chỉ cần doTweenClorl trở về ban đầu trước khi thực hiện lệnh đổi ký tự, tức là tắt màu đi, sau đó thực hiện lệnh đổi ký tự rồi mới đổi màu.
> 
> And I once encountered this error and fixed it. For example if curStep == 384 then function onUpdate() doTweenColor('dfgsdfgsd52fgs1', 'dad', '', 0.1, 'linear') doTweenColor( 'dfgsdfgsdfgs1', 'boyfriend', '', 0.1,'linear') end if curStep == 385 then triggerEvent('change character', '','')--Fill in yourself end if curStep == 386 then doTweenColor('dfgsdfgsd52fgs2', 'dad', 'FFAAAA', 0.1, 'linear') doTweenColor( 'dfgsdfgsdfgs2', 'boyfriend', 'FFAAAA', 0.1,'linear') end end

Oh, my apologies. I just used Pre-release 1.0
