### ISSUE TITLE
Low Health Indicator Bug on 1.0

### ISSUE THREAD

**Issue by jankespro12** [ShadowMario/FNF-PsychEngine#15777]
### Describe your bug here.

For some reason, when i downloaded the Low Health Indicator mod from GameBanana, on 0.6.3 to 0.7.3, low health image is working correctly, but on 1.0, for some reason, low health image is not positioned to the hud, instead to the stage.

Here's a image.
![Friday Night Funkin'_ Psych Engine 22 10 2024 00_39_19](https://github.com/user-attachments/assets/c2b86c7c-db83-47a6-956a-0e29831ec5a4)

### Command Prompt/Terminal logs (if existing)

```bash
function onUpdate(elapsed)
	CurHP = getProperty('health')
	cameraShake('hud', 2 / 256 - CurHP / 256, 0.025)
	setProperty('dyingeffect.alpha', 1 - CurHP)
	if CurHP < 0.5 then
		setProperty('playbackRate', 1)
	end
	if CurHP > 1.5 then
		setProperty('playbackRate', 1)
	end
end

function onGameOver()
	setProperty('playbackRate', 1)
end

function onBeatHit()
	playSound('heartbeat', 1 - CurHP)
end

function onCreate()
	makeLuaSprite('dyingeffect', 'overlay', 0, 0)
	addLuaSprite('dyingeffect', true)
	setObjectCamera('dyingeffect', 'other')
	setBlendMode('dyingeffect', 'normal')
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, it was just a image and sfx edit. and removed the slow down

**Comment by JHAM25** [comment]
Puede ser por esto:
setObjectCamera('dyingeffect', 'camOther')

**Comment by jankespro12** [comment]
> Puede ser por esto: setObjectCamera('dyingeffect', 'camOther')

I don't know spanish, but thanks anyway.

**Comment by JordanSantiagoYT** [comment]
setObjectCamera is currently broken on 1.0.

a temporary workaround could be to use this:
setProperty('dyingeffect.camera', instanceArg('camOther'), false, true)

**Comment by jankespro12** [comment]
> setObjectCamera is currently broken on 1.0.
> 
> a temporary workaround could be to use this: setProperty('dyingeffect.camera', instanceArg('camOther'), false, true)

![Base Profile Screenshot 2024 10 22 - 05 51 44 10](https://github.com/user-attachments/assets/35ae21e9-807f-4850-aff5-4270ccdbb9a1)
Now it actually works as intended! Thanks jordan!

**Comment by JordanSantiagoYT** [comment]
> > setObjectCamera is currently broken on 1.0.
> > a temporary workaround could be to use this: setProperty('dyingeffect.camera', instanceArg('camOther'), false, true)
> 
> Thanks jordan!

well, i actually found the fix [here](https://github.com/ShadowMario/FNF-PsychEngine/issues/15703#issuecomment-2418275285)
