### ISSUE TITLE
Hxcpp error when I try to compile

### ISSUE THREAD

**Issue by NeoStudios** [ShadowMario/FNF-PsychEngine#1577]
### Describe your problem here.

hello i'm having an error during the windows test of the source code
every time i try to boot to windows it never starts and when i see the build.xml file appears
´´Hxcpp is out of date - please update´´
but I've tried to update everything and this error continues

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Jonnycatmeow** [comment]
use haxelib remove hxcpp then do haxelib install hxcpp or just remove haxe and install the lastest verion of haxe

**Comment by NeoStudios** [comment]
> use haxelib remove hxcpp then do haxelib install hxcpp or just remove haxe and install the lastest verion of haxe

keeps giving this error in build.xml
but this text is always left when it stops
´´C:\Users\Nesto\Downloads\FNF Psych Main>lime test windows
source/Achievements.hx:141: characters 30-54 : Warning : `FlxCamera.defaultCamer
as` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/MainMenuState.hx:54: characters 3-39 : Warning : `FlxCamera.defaultCamera
s` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:275: characters 3-39 : Warning : `FlxCamera.defaultCameras`
is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/CharacterEditorState.hx:93: characters 3-41 : Warning : `FlxCamer
a.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

source/editors/DialogueCharacterEditorState.hx:82: characters 3-40 : Warning : `
FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget`
 instead
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:145: characters 8-18 : W
arning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:180: characters 8-18 : W
arning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:221: characters 8-18 : W
arning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:515: characters 8-18 : W
arning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:483: characters 37-56 :
Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:484: characters 31-47 :
Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:646: characters 10-42 :
Warning : Std.is is deprecated. Use Std.isOfType instead.´´

**Comment by Jonnycatmeow** [comment]
It’s building it

**Comment by NeoStudios** [comment]
> It’s building it

yes but when it appears nothing else happens
and when I see the files, it has already exported the images and almost everything, but it doesn't continue, the executable, icon and manifests of the weeks are missing.
