### ISSUE TITLE
Uncaught Error: Null object reference in the character editor

### ISSUE THREAD

**Issue by EpcLnn** [ShadowMario/FNF-PsychEngine#15774]
### Describe your bug here.

![Friday Night Funkin'_ Psych Engine 21 10 2024 18_45_39](https://github.com/user-attachments/assets/a0e09920-3719-4531-8d89-088355678dfc)
Can someone please help me fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only added xml, png and json files for characters

**Comment by KELOTOMU** [comment]
It's not aa bug, must've been a mistype of the character file path or a corrupted file(most of the time xml)

**Comment by EpcLnn** [comment]
Oh well okay... I used the FNF xml generator program that everyone suggests in tutorials etc.
