### ISSUE TITLE
how to make animated background

### ISSUE THREAD

**Issue by Cistooo0** [ShadowMario/FNF-PsychEngine#15789]
### Describe your problem here.

ive recently tried adding an animated backgriund and it wont work

giving me an uncaught error null object. i cant pin point what the problem is 
this is the script

function onCreate()

makeAnimatedLuaSprite('glitch', 'bg', -315, -300)
AddAnimationByPrefix('glitch', 'idle', 'idle', 24, true);
setLuaSpriteScrollFactor('glitch', 0.9, 0.9)
addLuaSprite('glitch', false)

close(true);

end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by KELOTOMU** [comment]
u forgot to play the animation, here's the syntax for it
objectPlayAnimation(obj:String, name:String, forced:Bool = false, ?startFrame:Int = 0)

**Comment by Cistooo0** [comment]
> u forgot to play the animation, here's the syntax for it objectPlayAnimation(obj:String, name:String, forced:Bool = false, ?startFrame:Int = 0)

still giving me a null object reference

**Comment by KELOTOMU** [comment]
> > u forgot to play the animation, here's the syntax for it objectPlayAnimation(obj:String, name:String, forced:Bool = false, ?startFrame:Int = 0)
> 
> still giving me a null object reference
> 
ohhh then it must be the image path, where is it located and what is it named?

**Comment by Cistooo0** [comment]
> > > u forgot to play the animation, here's the syntax for it objectPlayAnimation(obj:String, name:String, forced:Bool = false, ?startFrame:Int = 0)
> > 
> > 
> > still giving me a null object reference
> 
> ohhh then it must be the image path, where is it located and what is it named?

The image for the sprite is in the image folder in mods named bg along with the xml file

**Comment by KELOTOMU** [comment]
> > > > u forgot to play the animation, here's the syntax for it objectPlayAnimation(obj:String, name:String, forced:Bool = false, ?startFrame:Int = 0)
> > > 
> > > 
> > > still giving me a null object reference
> > 
> > 
> > ohhh then it must be the image path, where is it located and what is it named?
> 
> The image for the sprite is in the image folder in mods named bg along with the xml file

OHHHH I SEEE, change the `AddAnimationByPrefix` to `addAnimationByPrefix` its a capital letter typo

**Comment by Cistooo0** [comment]
> > > > > u forgot to play the animation, here's the syntax for it objectPlayAnimation(obj:String, name:String, forced:Bool = false, ?startFrame:Int = 0)
> > > > 
> > > > 
> > > > still giving me a null object reference
> > > 
> > > 
> > > ohhh then it must be the image path, where is it located and what is it named?
> > 
> > 
> > The image for the sprite is in the image folder in mods named bg along with the xml file
> 
> OHHHH I SEEE, change the `AddAnimationByPrefix` to `addAnimationByPrefix` its a capital letter typo

sadly still giving me null object refrence

**Comment by Cistooo0** [comment]
ok i got it to load but the objectPlayAnimation(obj:String, name:String, forced:Bool = false, ?startFrame:Int = 0); is making it break though

**Comment by Cistooo0** [comment]
fixed
