### ISSUE TITLE
Build with Android

### ISSUE THREAD

**Issue by Pandinhaa11** [ShadowMario/FNF-PsychEngine#15783]
### Describe your bug here.

when i try to build with Android, with sdk, jdk and ndk ok, it have an bug with 2 .hx files:
Main.hx and ApplicationMain.hx

### Command Prompt/Terminal logs (if existing)

```bash
PS C:\psych> lime build android
 ERROR  source/Main.hx:4: characters 8-31

  4 | import android.content.Context;
    |        ^^^^^^^^^^^^^^^^^^^^^^^
    | Type not found : android.content.Context

 ERROR  source/Main.hx:68: characters 36-43

 68 |   Sys.setCwd(Path.addTrailingSlash(Context.getExternalFilesDir()));
    |                                    ^^^^^^^
    | Type not found : Context

     ->  export/release/android/haxe/ApplicationMain.hx:153: characters 5-36

     153 |     ApplicationMain.getEntryPoint();
         |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         | Called from macro here
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
Android is not supported officially
