### ISSUE TITLE
Chart editor R key resetting playing back Inst but not Voices

### ISSUE THREAD

**Issue by wackyflurry** [ShadowMario/FNF-PsychEngine#15788]
### Describe your bug here.

When messing with the new chart editor, I noticed that when playing the song (with space), if I press R while it's playing, it resets the Inst back to the beginning of the section, but not the Voices.

This might have to do with the fact that I'm using Voices-Player and Voices-Opponent, though I doubt this is intentional

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No. I'm using the release build without compiling it myself.

**Comment by wackyflurry** [comment]
https://github.com/user-attachments/assets/fe5651b9-22f3-4aae-87dc-a68faedfe5d1

**Comment by ShadowMario** [comment]
Fixed at https://github.com/ShadowMario/FNF-PsychEngine/commit/f100b63d95508295d36e06baf39fefe69f1e3fd5
