### ISSUE TITLE
Buttons No Longer Work Atfer Importing An Image In

### ISSUE THREAD

**Issue by Skyliner5678160** [ShadowMario/FNF-PsychEngine#15784]
### Describe your bug here.

https://github.com/user-attachments/assets/ea5196a2-60b6-4991-ae12-d132a04252a3

ITS NOT WORKING 😭😭😭
so uhh its in the title and the video so uhh

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
Fixed at https://github.com/ShadowMario/FNF-PsychEngine/commit/f100b63d95508295d36e06baf39fefe69f1e3fd5
