### ISSUE TITLE
runHaxeCode() problem with LUA (*StrumGroups*)

### ISSUE THREAD

**Issue by AndrewMiner100** [ShadowMario/FNF-PsychEngine#15780]
### Describe your bug here.

I am trying to make a song where the scroll type(middle and side scroll) change and hopefully adding left and right scroll-types as well, but right now, even though the scroll types are changing (from middle to side), there are is an error that keeps appearing that says the Strum group is an unknown variable.

The page says it is either source or lua, but my mod contains and uses both, source is working just fine at the moment

![Friday Night Funkin'_ Vs Sonic MEX V1 10_22_2024 5_07_41 PM](https://github.com/user-attachments/assets/b96b8f19-e44b-4f4a-9075-e45c6d61e608)

here is also the script I am using for the change scroll type

![Change Scrolltype lua - FNF-Sonic MEX-Version 1 source - Visual Studio Code 10_22_2024 5_14_47 PM](https://github.com/user-attachments/assets/c3fed14d-fe91-4397-8c39-d14096b65ca7)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, menu, songs, nothing that has truly affected the scroll (besides the lua script right now)

**Comment by 2JENO** [comment]
hscript api is changed to iris so maybe need class idk

**Comment by AndrewMiner100** [comment]
I don't remember exactly what version of psych engine this mod was made in, but I am thinking that it is like 0.6.3 if I recall correctly, but I'll look more into iris and see if that helps at all

**Comment by KELOTOMU** [comment]
strumGroup doesn't exist in PlayState. You should do this instead if you wanna keep a strumGroup that can either be playerStrums or opponentStrums.

`var strumGroup = game.playerStrums;`
`if(!daNote.mustPress) strumGroup = game.opponentStrums;`

**Comment by AndrewMiner100** [comment]
I'm looking through the playstate and found this in it

![PlayState hx - FNF-Sonic MEX-Version 1 source - Visual Studio Code 11_11_2024 3_50_37 PM](https://github.com/user-attachments/assets/bf742374-55e4-46f5-a0cb-6de6bcc11f35)

Do I just remove it and place the variable at the top of playstate, since I'm am sure the strum groups variable is out of scope for the lua

**Comment by AndrewMiner100** [comment]
Just had to change some of the code to add Var to them, thanks [KELOTOMU](https://github.com/KELOTOMU)

**Comment by AndrewMiner100** [comment]
the error is gone, but the scroll type is only switching from middle to side, not flipping the player strums
