### ISSUE TITLE
Can't pause when video stops in MidSong

### ISSUE THREAD

**Issue by MaksPRO12667** [ShadowMario/FNF-PsychEngine#15782]
### Describe your bug here.

When i trying startVideo in Midsong and video ends, i can't pause song

For example:
function onStepHit()
if == 30 then
startVideo('video', false)
end
end

Video starts, i can pause but when video stops, i can't pause

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by KELOTOMU** [comment]
That's normal because if you paused, the song will stop but the video will keep playing. if you want it to be able to pause, you need a animated scene with xml(not any kinds of video format) if it has a sound, it will be placed on the sounds folder and be played at the same time when the animated scene plays.

**Comment by MaksPRO12667** [comment]
> That's normal because if you paused, the song will stop but the video will keep playing. if you want it to be able to pause, you need a animated scene with xml(not any kinds of video format) if it has a sound, it will be placed on the sounds folder and be played at the same time when the animated scene plays.

Split the video into screenshots and make xml... It's
1) Bad optimized
2) If the video is longer than 50 seconds, you need to make more xml sprites and what happening? You right, check 1)
For second you need make more xml sprites because xml sprite sheet has pixel limitations

If you try test it in computer it's not gonna be a problem but if you using Android there may be lags

**Comment by KELOTOMU** [comment]
> > That's normal because if you paused, the song will stop but the video will keep playing. if you want it to be able to pause, you need a animated scene with xml(not any kinds of video format) if it has a sound, it will be placed on the sounds folder and be played at the same time when the animated scene plays.
> 
> Split the video into screenshots and make xml... It's
> 1) Bad optimized
> 2) If the video is longer than 50 seconds, you need to make more xml sprites and what happening? You right, check 1)
> For second you need make more xml sprites because xml sprite sheet has pixel limitations
> 
> If you try test it in computer it's not gonna be a problem but if you using Android there may be lags

thats basically how animated shows are made, they are just converted to vid format instead of sparrowatlas, and also this is more optimized as long as the frames dont get past beyond 24 fps bc mp4 needs lots of space to run, u just need to preload the animation for no lagspikes

**Comment by MaksPRO12667** [comment]
> > > That's normal because if you paused, the song will stop but the video will keep playing. if you want it to be able to pause, you need a animated scene with xml(not any kinds of video format) if it has a sound, it will be placed on the sounds folder and be played at the same time when the animated scene plays.
> > 
> > 
> > Split the video into screenshots and make xml... It's
> > 
> > 1. Bad optimized
> > 2. If the video is longer than 50 seconds, you need to make more xml sprites and what happening? You right, check 1)
> >    For second you need make more xml sprites because xml sprite sheet has pixel limitations
> > 
> > If you try test it in computer it's not gonna be a problem but if you using Android there may be lags
> 
> thats basically how animated shows are made, they are just converted to vid format instead of sparrowatlas, and also this is more optimized as long as the frames dont get past beyond 24 fps bc mp4 needs lots of space to run, u just need to preload the animation for no lagspikes
> 
> u can change the resolution of the animation if it still lags rlly badly

Yeah, I was thinking about that. Thanks
