### ISSUE TITLE
HOW TD DO YOU EDIT Y POS AND SIZE OF NOTES

### ISSUE THREAD

**Issue by Gavman69** [ShadowMario/FNF-PsychEngine#1579]
### Describe your problem here.

how tf do you edit the y pos and the size of notes
as a setting of course

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

made a new setting so it lets you see the opponent's notes with middle scroll.

**Comment by Mastercopper2346** [comment]
my man closed it in you
