### ISSUE TITLE
whats the problem in my flash script

### ISSUE THREAD

**Issue by Cistooo0** [ShadowMario/FNF-PsychEngine#15798]
### Describe your problem here.

The script is not taking value2 and using it as the color for some reason A little help?

function onEvent(name, value1, value2)

	if name == 'Flash Camera' then

	   makeLuaSprite('flash', '', 0, 0);
        makeGraphic('flash',1280,720,'value2')
	      addLuaSprite('flash', true);
	      setLuaSpriteScrollFactor('flash',0,0)
	      setProperty('flash.scale.x',2)
	      setProperty('flash.scale.y',2)
	      setProperty('flash.alpha',0)
		setProperty('flash.alpha',1)
		doTweenAlpha('flTw','flash',0,value1,'linear')
	end

end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Dexedus** [comment]
You should make sure that value2 is initialised BEFORE the main block and make sure it contains a valid color string. 

if value2 then
       makeGraphic (-- your valid color string.) 
else
      -- default it to white if value2 is not defined.
end

**Comment by Cistooo0** [comment]
> You should make sure that value2 is initialised BEFORE the main block and make sure it contains a valid color string.
> 
> if value2 then makeGraphic (-- your valid color string.) else -- default it to white if value2 is not defined. end

seems like im too dumb to figure out what to do with this

**Comment by Cistooo0** [comment]
nvm i just had to remove the '' next to the value2

**Comment by Cistooo0** [comment]
> my bad, try removing the single quotes around value2, see if that does the trick

hey since the other guy hasent responded yet do you know whats wrong with this script

function onCreate()

makeAnimatedLuaSprite('glitch', 'bg', -315, -300);
addAnimationByPrefix('glitch', 'idle', 'idle', 24, true);
setLuaSpriteScrollFactor('glitch', 0.9, 0.9);
addLuaSprite('glitch', false);
objectPlayAnimation(obj:String, name:String, forced:Bool = false, ?startFrame:Int = 0);

close(true);

end

the objectPlayAnimation(obj:String, name:String, forced:Bool = false, ?startFrame:Int = 0); keeps giving me an error saying
"unexpected arguments near ",""

**Comment by Dexedus** [comment]
The syntax you're using appears to be influenced by TypeScript or a similar language, but Lua doesn't use type annotations like that.

`function onCreate()

    makeAnimatedLuaSprite('glitch', 'bg', -315, -300)
    addAnimationByPrefix('glitch', 'idle', 'idle', 24, true)
    setLuaSpriteScrollFactor('glitch', 0.9, 0.9)
    addLuaSprite('glitch', false)
    
    -- Corrected objectPlayAnimation call
    objectPlayAnimation('glitch', 'idle', false, 0)

    close(true)

end`

try that.

**Comment by Cistooo0** [comment]
> The syntax you're using appears to be influenced by TypeScript or a similar language, but Lua doesn't use type annotations like that.
> 
> `function onCreate()
> 
> ```
> makeAnimatedLuaSprite('glitch', 'bg', -315, -300)
> addAnimationByPrefix('glitch', 'idle', 'idle', 24, true)
> setLuaSpriteScrollFactor('glitch', 0.9, 0.9)
> addLuaSprite('glitch', false)
> 
> -- Corrected objectPlayAnimation call
> objectPlayAnimation('glitch', 'idle', false, 0)
> 
> close(true)
> ```
> 
> end`
> 
> try that.

nope still not playing the anim

**Comment by Cistooo0** [comment]
nvm i fixed it Thanks man
