### ISSUE TITLE
Color tweens question

### ISSUE THREAD

**Issue by ChickenSwimmer2020** [ShadowMario/FNF-PsychEngine#15790]
### What is your question?

so im trying to make a cool little remake of a song from the base game, but when i do a color tween for an effect, it makes the characters go fully black, and when i try to run `cancelTween('mytagname')` it doesnt do anything, is there a way to remove a color tween after its finished?

**Comment by JHAM25** [comment]
Puedes usar doTweenColor('tag', 'tu_objeto', 'ffffff', 0.5)

**Comment by ChickenSwimmer2020** [comment]
thank you so much
