### ISSUE TITLE
[macOS] FIXING ISSUES WITH MAC

### ISSUE THREAD

**Issue by TahirToprakKarabekiroglu** [ShadowMario/FNF-PsychEngine#15792]
# "PsychEngine.app" Not Opened
![resim](https://github.com/user-attachments/assets/3355d4b9-90c5-4a01-9239-ab20da7e236f)
To fix this issue, go to **System Settings** > **Privacy & Security** > **Security**. 
Then, press on **Open Anyway** button.
![resim](https://github.com/user-attachments/assets/2ef549cc-213e-4e43-9162-bb01ffe4f8dc)
Press **Open Anyway** again then enter your password.
![resim](https://github.com/user-attachments/assets/4221125f-d087-47fe-beb3-2b603b772a16)
The game will now open and you won't need to do this again.

# Game closing immediately after opening

```diff
+ This issue will not occur if you are compiling the game yourself!
```

To fix this issue, you need to move the app to anywhere else from its current location.
For example; if the game is in your Downloads folder, you can move the game to Desktop and the game will start.
Moving the game back to its original location will not make it so it closes again.

**Comment by CrusherNotDrip** [comment]
i agree

**Comment by SantiagoCalebe** [comment]
I agree 2, the final Issue Rating is `invalid`

**Comment by CrusherNotDrip** [comment]
> I agree 2, the final Issue Rating is `invalid`

not anymore
