### ISSUE TITLE
Suggestion: Adjustable snaps in charting menu

### ISSUE THREAD

**Issue by ArfieCat** [ShadowMario/FNF-PsychEngine#158]
Similar to Kade Engine. Currently, Psych Engine's charting menu only has 1/16 snaps. To chart off-grid, one would have to disable snapping, which would lead to slight imprecisions in the chart. I think adding options for 1/24 and 1/32 snaps would be extremely helpful for charting conplex songs.

**Comment by ShadowMario** [comment]
Sounds unnecessary to be honest, 1/16 is already very precise

**Comment by Steviegt6** [comment]
> Sounds unnecessary to be honest, 1/16 is already very precise

Just because it sounds unnecessary doesn't really mean there's no use-case for it. May as well just ask for a PR if you don't want to implement it yourself.

**Comment by lemz1** [comment]
You can use the strumtime option if i am not wrong 100 is one square so you just need to adjust the number

**Comment by ShadowMario** [comment]
Added new snaps
