### ISSUE TITLE
How to make an image take up the whole camera on a miss

### ISSUE THREAD

**Issue by MugMiles** [ShadowMario/FNF-PsychEngine#15805]
### Describe your problem here.

On previous versions and even the pre-release of 1.0 I was able to use this code to make an image flash on the screen whenever I miss. With the final 1.0 however, the image continues to linger no matter what and is not scaled to the camera size. Help me fix the code pls

function noteMiss()
        makeLuaSprite('image', 'hurt', 0, 0);
        addLuaSprite('image', true);
        scaleObject('image', 0.5, 0.52);
        doTweenColor('hello', 'image', 'FFFFFFFF', 0.1, 'quartIn');
        setObjectCamera('image', 'other');
        runTimer('wait', 0.05);
        
        function onTimerCompleted(tag, loops, loopsleft)
            if tag == 'wait' then
                removeLuaSprite('image',true)
            end
        end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by a-random441** [comment]
replace
```lua
setObjectCamera('image', 'other');
```
to this:
```lua
setProperty('image.camera', instanceArg('other'), false, true)
```

**Comment by MugMiles** [comment]
Crashes the game

**Comment by a-random441** [comment]
you could do with callmethod but i forgor how

**Comment by a-random441** [comment]
> Crashes the game

replace other with camOther

**Comment by MugMiles** [comment]
This works, thanks!
