### ISSUE TITLE
Compilling error

### ISSUE THREAD

**Issue by Gaster123987** [ShadowMario/FNF-PsychEngine#15803]
### Describe your problem here.

I have no idea how to fix this, and I haven't tried compilling before

`Warning: Ignoring unknown fps=""
C:/HaxeToolkit/haxe/lib/discord_rpc/git/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
source/editors/ChartingState.hx:150: characters 13-21 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
source/PlayState.hx:109: characters 40-48 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:152: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:237: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:236: characters 27-35 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:340: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:342: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:27: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:109: characters 68-76 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:2266: characters 18-26 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:2300: characters 18-26 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:64: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:581: characters 22-30 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2428: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2430: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2434: characters 27-35 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1825: characters 22-30 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1825: characters 37-45 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1872: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1872: characters 34-42 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1943: characters 21-29 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1943: characters 36-44 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:1356: characters 16-24 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:2195: characters 14-22 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:2212: characters 14-22 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:39: characters 13-21 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:110: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:112: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/TitleState.hx:719: characters 15-23 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I removed FlxSound.hx (Since apparently it could help one of the issues I had before?) and I edited ChartingState.hx (I tried to add  @:privateAccess { )

**Comment by Poggers1Studios** [comment]
did this happen after you removed the .hx?

**Comment by Gaster123987** [comment]
Update: After some irritation and searching on the internet, it now looks like this:
`Warning: Ignoring unknown fps=""
C:/HaxeToolkit/haxe/lib/discord_rpc/git/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
source/editors/ChartingState.hx:150: characters 13-21 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:109: characters 40-48 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:152: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:237: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:236: characters 27-35 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:340: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:342: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:27: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:109: characters 68-76 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:2266: characters 18-26 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:2300: characters 18-26 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:64: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:581: characters 22-30 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2428: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2430: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2434: characters 27-35 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1825: characters 22-30 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1825: characters 37-45 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1872: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1872: characters 34-42 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1943: characters 21-29 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1943: characters 36-44 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:1356: characters 16-24 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:2195: characters 14-22 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:2212: characters 14-22 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:39: characters 13-21 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:110: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:112: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/TitleState.hx:719: characters 15-23 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/Achievements.hx:132: characters 30-54 : Warning : (WDeprecated) `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/FlxUIDropDownMenuCustom.hx:367: characters 18-35 : Warning : (WDeprecated) FlxButton.PRESSED is deprecated, use FlxButtonState.PRESSED
source/flixel/animation/FlxAnimationController.hx:691: characters 8-33 : Warning : (WDeprecated) `framesHash` is deprecated, use `getByName()` or `exists()`
source/flixel/animation/FlxAnimationController.hx:693: characters 31-56 : Warning : (WDeprecated) `framesHash` is deprecated, use `getByName()` or `exists()`
source/flixel/animation/FlxAnimationController.hx:704: characters 8-33 : Warning : (WDeprecated) `framesHash` is deprecated, use `getByName()` or `exists()`
source/flixel/animation/FlxAnimationController.hx:706: characters 31-56 : Warning : (WDeprecated) `framesHash` is deprecated, use `getByName()` or `exists()`
source/flixel/animation/FlxAnimationController.hx:768: characters 33-58 : Warning : (WDeprecated) `framesHash` is deprecated, use `getByName()` or `exists()`
source/flixel/animation/FlxAnimationController.hx:776: characters 16-41 : Warning : (WDeprecated) `framesHash` is deprecated, use `getByName()` or `exists()`
C:\Users\pekin\Desktop\FNF-PsychEngine-0.6.3\export\release\windows\obj>setlocal enabledelayedexpansion
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths`

**Comment by Shadow06735** [comment]
what version are you using?

**Comment by a-random441** [comment]
> Update: After some irritation and searching on the internet, it now looks like this: `Warning: Ignoring unknown fps="" C:/HaxeToolkit/haxe/lib/discord_rpc/git/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract`is deprecated in favor of`enum abstract`source/editors/ChartingState.hx:150: characters 13-21 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/PlayState.hx:109: characters 40-48 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/PlayState.hx:152: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/PlayState.hx:237: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/FreeplayState.hx:236: characters 27-35 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/FreeplayState.hx:340: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/FreeplayState.hx:342: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/PauseSubState.hx:27: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/PlayState.hx:109: characters 68-76 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/FunkinLua.hx:2266: characters 18-26 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/FunkinLua.hx:2300: characters 18-26 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/PauseSubState.hx:64: characters 20-28 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/PlayState.hx:581: characters 22-30 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/PlayState.hx:2428: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/PlayState.hx:2430: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/PlayState.hx:2434: characters 27-35 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/PlayState.hx:1825: characters 22-30 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/PlayState.hx:1825: characters 37-45 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/PlayState.hx:1872: characters 19-27 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/PlayState.hx:1872: characters 34-42 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/PlayState.hx:1943: characters 21-29 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/PlayState.hx:1943: characters 36-44 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/editors/ChartingState.hx:1356: characters 16-24 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/editors/ChartingState.hx:2195: characters 14-22 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/editors/ChartingState.hx:2212: characters 14-22 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/editors/EditorPlayState.hx:39: characters 13-21 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/editors/EditorPlayState.hx:110: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/editors/EditorPlayState.hx:112: characters 17-25 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/TitleState.hx:719: characters 15-23 : Warning : (WDeprecated) flixel.system.FlxSound was moved to flixel.sound.FlxSound source/Achievements.hx:132: characters 30-54 : Warning : (WDeprecated)`FlxCamera.defaultCameras`is deprecated, use`FlxG.cameras.setDefaultDrawTarget`instead source/FlxUIDropDownMenuCustom.hx:367: characters 18-35 : Warning : (WDeprecated) FlxButton.PRESSED is deprecated, use FlxButtonState.PRESSED source/flixel/animation/FlxAnimationController.hx:691: characters 8-33 : Warning : (WDeprecated)`framesHash`is deprecated, use`getByName()`or`exists()`source/flixel/animation/FlxAnimationController.hx:693: characters 31-56 : Warning : (WDeprecated)`framesHash`is deprecated, use`getByName()`or`exists()`source/flixel/animation/FlxAnimationController.hx:704: characters 8-33 : Warning : (WDeprecated)`framesHash`is deprecated, use`getByName()`or`exists()`source/flixel/animation/FlxAnimationController.hx:706: characters 31-56 : Warning : (WDeprecated)`framesHash`is deprecated, use`getByName()`or`exists()`source/flixel/animation/FlxAnimationController.hx:768: characters 33-58 : Warning : (WDeprecated)`framesHash`is deprecated, use`getByName()`or`exists()`source/flixel/animation/FlxAnimationController.hx:776: characters 16-41 : Warning : (WDeprecated)`framesHash`is deprecated, use`getByName()`or`exists()` C:\Users\pekin\Desktop\FNF-PsychEngine-0.6.3\export\release\windows\obj>setlocal enabledelayedexpansion Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths`

bro just do
```cmd
lime test windows
```
not
```
setlocal enabledelayedexpansion
```

**Comment by Gaster123987** [comment]
> what version are you using? it ur using 0.6.3 and lower (which it looks like so since this error happens if ur using those versions), then you gotta compile a newer version as 0.6.3 is no longer supported

Oh- okay, thanks

**Comment by a-random441** [comment]
> what version are you using? it ur using 0.6.3 and lower (which it looks like so since this error happens if ur using those versions), then you gotta compile a newer version as 0.6.3 is no longer supported

They can still compile by doing
```cmd
lime test windows
```
not whatever what command they're using to compile

**Comment by Shadow06735** [comment]
> > what version are you using? it ur using 0.6.3 and lower (which it looks like so since this error happens if ur using those versions), then you gotta compile a newer version as 0.6.3 is no longer supported
> 
> They can still compile by doing
> 
> ```batchfile
> lime test windows
> ```
> 
> not whatever what command they're using to compile

they would still get the same error

**Comment by a-random441** [comment]
you know they could setup Visual Studio (Code)

**Comment by Gaster123987** [comment]
I forgot to say that this has been solved already-
