### ISSUE TITLE
Freeplay Revamp? 

### ISSUE THREAD

**Issue by PhoenixDoesStuff** [ShadowMario/FNF-PsychEngine#15817]
### What feature do you want to get added on the **base** engine?

The Freeplay menu looks a bit too old. How about a enhancement? 

Just add the base Freeplay menu into the engine if you want, I don't expect it to happen. But like keep the Freeplay week editor thing as the old menu. It's more simpler ig. 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CrusherNotDrip** [comment]
ShadowMario has already said he will not add the new base game stuff other than weekend 1 to psych engine

**Comment by PhoenixDoesStuff** [comment]
> ShadowMario has already said he will not add the new base game stuff other than weekend 1 to psych engine

Oh... My Bad.

**Comment by PhoenixDoesStuff** [comment]
Comment for closing issue

**Comment by Lorekeeper49** [comment]
> Comment for closing issue

It's not closed

**Comment by PhoenixDoesStuff** [comment]
> > Comment for closing issue
> 
> It's not closed

O
