### ISSUE TITLE
Why is the Stage Editor's Save button not working?

### ISSUE THREAD

**Issue by JiuxuXX** [ShadowMario/FNF-PsychEngine#15824]
### What is your question?

So I want to know why I can't use the save button after creating a new sprite using the stage editor?
I created a sprite without animation.
My English is not good, so I used a translation software. Maybe what I say will be a bit strange. If this happens, I'm sorry.
![idk](https://github.com/user-attachments/assets/b15c887f-9032-4227-b7e3-b758481a9b8c)

**Comment by Wh4pzkxdd** [comment]
i think its a bug but what i did was just change the json file to delete or add objects and stuff, if you dont delete any objects (or add) and just move things or change some values then you will be able to save

**Comment by PhoenixDoesStuff** [comment]
You Need To Have Your Images In A Completely Different File Location. Like For Example: Downloads, Documents, ect. Once You Load It, You'll Get A Pop-Up Saying That You Need To Put It Into The Images Folder, Blah Blah Blah. After Clicking Ok Or Something Like That, You'll Be Able To Save.
