### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by MIDISIDI** [ShadowMario/FNF-PsychEngine#15822]
### Describe your bug here.

My engine doesnt see the mods folder at all, and because of this i cant work normally, Fix this bug, it`s annoying!
![FUCKINGBUG](https://github.com/user-attachments/assets/650f7d20-a462-48d7-82f7-2e140fc5b11e)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i don`t think

**Comment by Reycko** [comment]
What are the contents of the folder?

**Comment by PhoenixDoesStuff** [comment]
If your going into the menus, just select the directory mod folder at the bottom. Then you'll be able to edit it.

**Comment by 2JENO** [comment]
close engine first

**Comment by WoodsSilent05** [comment]
> close engine first

itll update automatically if you go in and out of freeplay

**Comment by WoodsSilent05** [comment]
make sure that there isnt another single folder inside of that folder, usually when unzipping a mod, itll have a folder inside that other folder, so just move the contents into the first folder.
