### ISSUE TITLE
How To Change Textures?

### ISSUE THREAD

**Issue by megalives717** [ShadowMario/FNF-PsychEngine#15821]
### What is your question?

How I do change textures?

**Comment by Shadow06735** [comment]
what textures are you talking abt

**Comment by MaksPRO12667** [comment]
what...? Just go in mods/images and change textures, minecraft guy

**Comment by PhoenixDoesStuff** [comment]
Navigate to the "Textures" folder.
Find a texture category that you want to edit and open its folder.
Open a texture in an image editing program.
Edit your texture. 
Save over the image file.
Edit any other textures that you want to change.
Go back to the folder with the version number.
Simple Minecraft Modding. Idk Why Your Asking On An FNF Based Page Though.
