### ISSUE TITLE
Secret Bumps & Another Problem

### ISSUE THREAD

**Issue by NiftyAC** [ShadowMario/FNF-PsychEngine#15823]
### What is your question?

i wanted to add my own secret bump to the title screen but not even the normal ones work on 1.0. is that a glitch or was it removed because the code is still there.

**Comment by NiftyAC** [comment]
> ### What is your question?
> 
> i wanted to add my own secret bump to the title screen but not even the normal ones work on 1.0. is that a glitch or was it removed because the code is still there.

- Update: that's actually one issue in the compiled version. I've had two issues with the compiled version but the normal one works fine. My two issues are that the secret bumps don't happen on compiled but do on normal 1.0. And my second issue is that in my mod which I put in the mods folder, has a messed up script in compiled but not normal 1.0. These issues are pretty minor but I wanted to change the "Blueballs" text for every time you lose to something related to my mod.

**Comment by Shadow06735** [comment]
> > ### What is your question?
> > i wanted to add my own secret bump to the title screen but not even the normal ones work on 1.0. is that a glitch or was it removed because the code is still there.
> 
> * Update: that's actually one issue in the compiled version. I've had two issues with the compiled version but the normal one works fine. My two issues are that the secret bumps don't happen on compiled but do on normal 1.0. And my second issue is that in my mod which I put in the mods folder, has a messed up script in compiled but not normal 1.0. These issues are pretty minor but I wanted to change the "Blueballs" text for every time you lose to something related to my mod.

are you trying to changed the "blueballed" text with source or lua? if with source find this line shown in the image and change the part i highlighted to whatever u want
![image](https://github.com/user-attachments/assets/94139590-dd92-41e5-8d09-f922235b700f)

**Comment by Shadow06735** [comment]
> > > ### What is your question?
> > > i wanted to add my own secret bump to the title screen but not even the normal ones work on 1.0. is that a glitch or was it removed because the code is still there.
> > 
> > 
> > 
> > * Update: that's actually one issue in the compiled version. I've had two issues with the compiled version but the normal one works fine. My two issues are that the secret bumps don't happen on compiled but do on normal 1.0. And my second issue is that in my mod which I put in the mods folder, has a messed up script in compiled but not normal 1.0. These issues are pretty minor but I wanted to change the "Blueballs" text for every time you lose to something related to my mod.
> 
> are you trying to changed the "blueballed" text with source or lua? if with source find this line shown in the image in "pausesubstate.hx" and change the part i highlighted (the lighter white shade) to whatever u want ![image](https://private-user-images.githubusercontent.com/172072731/381763135-94139590-dd92-41e5-8d09-f922235b700f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMjg1MTAsIm5iZiI6MTczMDMyODIxMCwicGF0aCI6Ii8xNzIwNzI3MzEvMzgxNzYzMTM1LTk0MTM5NTkwLWRkOTItNDFlNS04ZDA5LWY5MjIyMzViNzAwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQyMjQzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmM2YThhYjE2NTY5ZWNhYjRjMjJjMDc0MWM3YzFhNDY0NGYzN2JkODY2NzFhNGNmYWU1NDA5OGUyMzA4NGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.idgH8FLBv5diP5171nKN5vesvHtOLL8MXBxTx3do084)

**Comment by NiftyAC** [comment]
> > > ### What is your question?
> 
> > > i wanted to add my own secret bump to the title screen but not even the normal ones work on 1.0. is that a glitch or was it removed because the code is still there.
> 
> > 
> 
> > * Update: that's actually one issue in the compiled version. I've had two issues with the compiled version but the normal one works fine. My two issues are that the secret bumps don't happen on compiled but do on normal 1.0. And my second issue is that in my mod which I put in the mods folder, has a messed up script in compiled but not normal 1.0. These issues are pretty minor but I wanted to change the "Blueballs" text for every time you lose to something related to my mod.
> 
> 
> 
> are you trying to changed the "blueballed" text with source or lua? if with source find this line shown in the image in "pausesubstate.hx" and change the part i highlighted (the lighter white shade) to whatever u want
> 
> ![image](https://github.com/user-attachments/assets/94139590-dd92-41e5-8d09-f922235b700f)

I got it changed with source code and it worked but when I compile the game the secret bumps don't work and a script I have doesn't work correctly. It works on psych engine 1.0 normally but on the source code compiled version it breaks the script even if it's in the mods folder. I'm not having a problem with the blueballed text because it works fine now it's just the secret bumps and my mods folder script.

**Comment by Shadow06735** [comment]
try moving the "TITLE_SCREEN_EASTER_EGG" thingy outside the official build group:
![image](https://github.com/user-attachments/assets/5068b6d2-91a3-4192-822f-f9790cd1544f)

**Comment by NiftyAC** [comment]
> try moving the "TITLE_SCREEN_EASTER_EGG" thingy outside the official build group (like where the videos thingy is):
> 
> ![image](https://github.com/user-attachments/assets/5068b6d2-91a3-4192-822f-f9790cd1544f)

I apologize but I'm horrible with code. Is that in the titlestate.hx?

**Comment by Shadow06735** [comment]
> > try moving the "TITLE_SCREEN_EASTER_EGG" thingy outside the official build group (like where the videos thingy is):
> > ![image](https://private-user-images.githubusercontent.com/172072731/382116906-5068b6d2-91a3-4192-822f-f9790cd1544f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NzQ1MjQsIm5iZiI6MTczMDQ3NDIyNCwicGF0aCI6Ii8xNzIwNzI3MzEvMzgyMTE2OTA2LTUwNjhiNmQyLTkxYTMtNDE5Mi04MjJmLWY5NzkwY2QxNTQ0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxNTE3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmM5MTE5MmFlMmUyNzFmN2E2NzdlMWY2NGNjZTE2MjMyZTY2MjdmYmQ5Yzc4ZWVlMDBlOWE4Nzg3YmE2ODc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DvySlqQPNnejqlK7cBHb33vNoCPDO56ybVkq2biJ1XA)
> 
> I apologize but I'm horrible with code. Is that in the titlestate.hx? And if so what line. I'm on 1.0 source code so it's new and it's my first time ever compiling a game. Nevermind it can't be titlestate it doesn't show up when I search it in VS code. I just need to know what .hx file or whatever it's in.

its in project.xml
