### ISSUE TITLE
Is it possible to compile old versions at all?

### ISSUE THREAD

**Issue by NiftyAC** [ShadowMario/FNF-PsychEngine#15839]
### What is your question?

I would like to use 0.7.3 on source code but I don’t know how because no matter what I get an sscript error and don’t know what to try now.

**Comment by MaksPRO12667** [comment]
Each version has its own files for compilation

**Comment by NiftyAC** [comment]
> Each version has its own files(i mean versions files) for compilation

I've went through the 0.7.3 compilation tutorial in the build.md and I get an sscript error. I've verified that sscript is downloaded but nothing works. I just need that version because my mod breaks on 1.0

**Comment by MaksPRO12667** [comment]
> > Each version has its own files(i mean versions files) for compilation
> 
> I've went through the 0.7.3 compilation tutorial in the build.md and I get an sscript error. I've verified that sscript is downloaded but nothing works. I just need that version because my mod breaks on 1.0

https://www.youtube.com/watch?v=7ms9U9Wfmac
Try this

**Comment by NiftyAC** [comment]
> > > Each version has its own files(i mean versions files) for compilation
> > 
> > 
> > I've went through the 0.7.3 compilation tutorial in the build.md and I get an sscript error. I've verified that sscript is downloaded but nothing works. I just need that version because my mod breaks on 1.0
> 
> https://www.youtube.com/watch?v=7ms9U9Wfmac Try this

Warning: Ignoring unknown fps=""
C:/Haxe/haxelib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.


I still get this error and the people in the comments saying they fixed it aren't replying to the comments that ask how

**Comment by Shadow06735** [comment]
> > > > Each version has its own files(i mean versions files) for compilation
> > > 
> > > 
> > > I've went through the 0.7.3 compilation tutorial in the build.md and I get an sscript error. I've verified that sscript is downloaded but nothing works. I just need that version because my mod breaks on 1.0
> > 
> > 
> > https://www.youtube.com/watch?v=7ms9U9Wfmac Try this
> 
> Warning: Ignoring unknown fps="" C:/Haxe/haxelib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
> 
> I still get this error and the people in the comments saying they fixed it aren't replying to the comments that ask how

you have to download the sscript from the link they put (make sure to download the right version)

then, run "haxelib remove SScript" to remove the current SScript

after that run "haxelib install ZIPNAME.zip" (ZIPNAME.zip is the name of your SScript zip file)

**Comment by NiftyAC** [comment]
> > > > > Each version has its own files(i mean versions files) for compilation
> > > > 
> > > > 
> > > > I've went through the 0.7.3 compilation tutorial in the build.md and I get an sscript error. I've verified that sscript is downloaded but nothing works. I just need that version because my mod breaks on 1.0
> > > 
> > > 
> > > https://www.youtube.com/watch?v=7ms9U9Wfmac Try this
> > 
> > 
> > Warning: Ignoring unknown fps="" C:/Haxe/haxelib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
> > I still get this error and the people in the comments saying they fixed it aren't replying to the comments that ask how
> 
> you have to download the sscript from the link they put (make sure to download the right version)
> 
> then, run "haxelib remove SScript" to remove the current SScript
> 
> after that run "haxelib install ZIPNAME.zip" (ZIPNAME.zip is the name of your SScript zip file)

BUILDING GAME
Warning: Ignoring unknown fps=""
C:/Haxe/haxelib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.

done.
Press any key to continue . . .



I'm getting that everytime I try and there's no sscript link that I saw anywhere.

**Comment by Shadow06735** [comment]
> > > > > > Each version has its own files(i mean versions files) for compilation
> > > > > 
> > > > > 
> > > > > I've went through the 0.7.3 compilation tutorial in the build.md and I get an sscript error. I've verified that sscript is downloaded but nothing works. I just need that version because my mod breaks on 1.0
> > > > 
> > > > 
> > > > https://www.youtube.com/watch?v=7ms9U9Wfmac Try this
> > > 
> > > 
> > > Warning: Ignoring unknown fps="" C:/Haxe/haxelib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
> > > I still get this error and the people in the comments saying they fixed it aren't replying to the comments that ask how
> > 
> > 
> > you have to download the sscript from the link they put (make sure to download the right version)
> > then, run "haxelib remove SScript" to remove the current SScript
> > after that run "haxelib install ZIPNAME.zip" (ZIPNAME.zip is the name of your SScript zip file)
> 
> BUILDING GAME Warning: Ignoring unknown fps="" C:/Haxe/haxelib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
> 
> done. Press any key to continue . . .
> 
> I'm getting that everytime I try and there's no sscript link that I saw anywhere.

Get it from this link:
[S](https://github.com/CobaltBar/SScript-Archive)

**Comment by NiftyAC** [comment]
> > > > > > > Each version has its own files(i mean versions files) for compilation
> > > > > > 
> > > > > > 
> > > > > > I've went through the 0.7.3 compilation tutorial in the build.md and I get an sscript error. I've verified that sscript is downloaded but nothing works. I just need that version because my mod breaks on 1.0
> > > > > 
> > > > > 
> > > > > https://www.youtube.com/watch?v=7ms9U9Wfmac Try this
> > > > 
> > > > 
> > > > Warning: Ignoring unknown fps="" C:/Haxe/haxelib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
> > > > I still get this error and the people in the comments saying they fixed it aren't replying to the comments that ask how
> > > 
> > > 
> > > you have to download the sscript from the link they put (make sure to download the right version)
> > > then, run "haxelib remove SScript" to remove the current SScript
> > > after that run "haxelib install ZIPNAME.zip" (ZIPNAME.zip is the name of your SScript zip file)
> > 
> > 
> > BUILDING GAME Warning: Ignoring unknown fps="" C:/Haxe/haxelib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
> > done. Press any key to continue . . .
> > I'm getting that everytime I try and there's no sscript link that I saw anywhere.
> 
> Get it from this link: https://github.com/CobaltBar/SScript-Archive

BUILDING GAME
C:/Haxe/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
source/backend/Paths.hx:605: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)
source/objects/Character.hx:304: characters 87-101 : flxanimate.animate.FlxAnim has no field lastPlayedAnim
source/states/stages/Tank.hx:310: lines 310-315 : () -> Void should be flixel.util.FlxSignal
source/states/stages/Tank.hx:310: lines 310-315 : ... For function argument 'func'

done.
Press any key to continue . . .



got past the sscript thing but now this is happening. thank you for the sscript thing

**Comment by Shadow06735** [comment]
> > > > > > > > Each version has its own files(i mean versions files) for compilation
> > > > > > > 
> > > > > > > 
> > > > > > > I've went through the 0.7.3 compilation tutorial in the build.md and I get an sscript error. I've verified that sscript is downloaded but nothing works. I just need that version because my mod breaks on 1.0
> > > > > > 
> > > > > > 
> > > > > > https://www.youtube.com/watch?v=7ms9U9Wfmac Try this
> > > > > 
> > > > > 
> > > > > Warning: Ignoring unknown fps="" C:/Haxe/haxelib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
> > > > > I still get this error and the people in the comments saying they fixed it aren't replying to the comments that ask how
> > > > 
> > > > 
> > > > you have to download the sscript from the link they put (make sure to download the right version)
> > > > then, run "haxelib remove SScript" to remove the current SScript
> > > > after that run "haxelib install ZIPNAME.zip" (ZIPNAME.zip is the name of your SScript zip file)
> > > 
> > > 
> > > BUILDING GAME Warning: Ignoring unknown fps="" C:/Haxe/haxelib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
> > > done. Press any key to continue . . .
> > > I'm getting that everytime I try and there's no sscript link that I saw anywhere.
> > 
> > 
> > Get it from this link: https://github.com/CobaltBar/SScript-Archive
> 
> BUILDING GAME C:/Haxe/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID) source/backend/Paths.hx:605: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas) source/objects/Character.hx:304: characters 87-101 : flxanimate.animate.FlxAnim has no field lastPlayedAnim source/states/stages/Tank.hx:310: lines 310-315 : () -> Void should be flixel.util.FlxSignal source/states/stages/Tank.hx:310: lines 310-315 : ... For function argument 'func'
> 
> done. Press any key to continue . . .
> 
> got past the sscript thing but now this is happening. thank you for the sscript thing

For the tank idk

for the flxanimate do this:
haxelib remove flxanimate

then put this altogether:
haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev

**Comment by NiftyAC** [comment]
> > > > > > > > > Each version has its own files(i mean versions files) for compilation
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I've went through the 0.7.3 compilation tutorial in the build.md and I get an sscript error. I've verified that sscript is downloaded but nothing works. I just need that version because my mod breaks on 1.0
> > > > > > > 
> > > > > > > 
> > > > > > > https://www.youtube.com/watch?v=7ms9U9Wfmac Try this
> > > > > > 
> > > > > > 
> > > > > > Warning: Ignoring unknown fps="" C:/Haxe/haxelib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
> > > > > > I still get this error and the people in the comments saying they fixed it aren't replying to the comments that ask how
> > > > > 
> > > > > 
> > > > > you have to download the sscript from the link they put (make sure to download the right version)
> > > > > then, run "haxelib remove SScript" to remove the current SScript
> > > > > after that run "haxelib install ZIPNAME.zip" (ZIPNAME.zip is the name of your SScript zip file)
> > > > 
> > > > 
> > > > BUILDING GAME Warning: Ignoring unknown fps="" C:/Haxe/haxelib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
> > > > done. Press any key to continue . . .
> > > > I'm getting that everytime I try and there's no sscript link that I saw anywhere.
> > > 
> > > 
> > > Get it from this link: https://github.com/CobaltBar/SScript-Archive
> > 
> > 
> > BUILDING GAME C:/Haxe/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID) source/backend/Paths.hx:605: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas) source/objects/Character.hx:304: characters 87-101 : flxanimate.animate.FlxAnim has no field lastPlayedAnim source/states/stages/Tank.hx:310: lines 310-315 : () -> Void should be flixel.util.FlxSignal source/states/stages/Tank.hx:310: lines 310-315 : ... For function argument 'func'
> > done. Press any key to continue . . .
> > got past the sscript thing but now this is happening. thank you for the sscript thing
> 
> For the tank idk
> 
> for the flxanimate do this: haxelib remove flxanimate
> 
> then put this altogether: haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev

I'm sorry for making this take so long but it finally worked. thank you so much. you cant even believe how happy I am because I've been trying this daily for a while with no tutorials.

**Comment by Shadow06735** [comment]
> > > > > > > > > > Each version has its own files(i mean versions files) for compilation
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > I've went through the 0.7.3 compilation tutorial in the build.md and I get an sscript error. I've verified that sscript is downloaded but nothing works. I just need that version because my mod breaks on 1.0
> > > > > > > > 
> > > > > > > > 
> > > > > > > > https://www.youtube.com/watch?v=7ms9U9Wfmac Try this
> > > > > > > 
> > > > > > > 
> > > > > > > Warning: Ignoring unknown fps="" C:/Haxe/haxelib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
> > > > > > > I still get this error and the people in the comments saying they fixed it aren't replying to the comments that ask how
> > > > > > 
> > > > > > 
> > > > > > you have to download the sscript from the link they put (make sure to download the right version)
> > > > > > then, run "haxelib remove SScript" to remove the current SScript
> > > > > > after that run "haxelib install ZIPNAME.zip" (ZIPNAME.zip is the name of your SScript zip file)
> > > > > 
> > > > > 
> > > > > BUILDING GAME Warning: Ignoring unknown fps="" C:/Haxe/haxelib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
> > > > > done. Press any key to continue . . .
> > > > > I'm getting that everytime I try and there's no sscript link that I saw anywhere.
> > > > 
> > > > 
> > > > Get it from this link: https://github.com/CobaltBar/SScript-Archive
> > > 
> > > 
> > > BUILDING GAME C:/Haxe/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID) source/backend/Paths.hx:605: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas) source/objects/Character.hx:304: characters 87-101 : flxanimate.animate.FlxAnim has no field lastPlayedAnim source/states/stages/Tank.hx:310: lines 310-315 : () -> Void should be flixel.util.FlxSignal source/states/stages/Tank.hx:310: lines 310-315 : ... For function argument 'func'
> > > done. Press any key to continue . . .
> > > got past the sscript thing but now this is happening. thank you for the sscript thing
> > 
> > 
> > For the tank idk
> > for the flxanimate do this: haxelib remove flxanimate
> > then put this altogether: haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev
> 
> I'm sorry for making this take so long but it finally worked. thank you so much. you cant even believe how happy I am because I've been trying this daily for a while with no tutorials.

for some reason i didnt get a notification about ur response but np

**Comment by NiftyAC** [comment]
> > > > > > > > > > > Each version has its own files(i mean versions files) for compilation
> 
> > > > > > > > > > 
> 
> > > > > > > > > > 
> 
> > > > > > > > > > I've went through the 0.7.3 compilation tutorial in the build.md and I get an sscript error. I've verified that sscript is downloaded but nothing works. I just need that version because my mod breaks on 1.0
> 
> > > > > > > > > 
> 
> > > > > > > > > 
> 
> > > > > > > > > https://www.youtube.com/watch?v=7ms9U9Wfmac Try this
> 
> > > > > > > > 
> 
> > > > > > > > 
> 
> > > > > > > > Warning: Ignoring unknown fps="" C:/Haxe/haxelib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
> 
> > > > > > > > I still get this error and the people in the comments saying they fixed it aren't replying to the comments that ask how
> 
> > > > > > > 
> 
> > > > > > > 
> 
> > > > > > > you have to download the sscript from the link they put (make sure to download the right version)
> 
> > > > > > > then, run "haxelib remove SScript" to remove the current SScript
> 
> > > > > > > after that run "haxelib install ZIPNAME.zip" (ZIPNAME.zip is the name of your SScript zip file)
> 
> > > > > > 
> 
> > > > > > 
> 
> > > > > > BUILDING GAME Warning: Ignoring unknown fps="" C:/Haxe/haxelib/SScript/7,7,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.
> 
> > > > > > done. Press any key to continue . . .
> 
> > > > > > I'm getting that everytime I try and there's no sscript link that I saw anywhere.
> 
> > > > > 
> 
> > > > > 
> 
> > > > > Get it from this link: https://github.com/CobaltBar/SScript-Archive
> 
> > > > 
> 
> > > > 
> 
> > > > BUILDING GAME C:/Haxe/haxelib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID) source/backend/Paths.hx:605: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas) source/objects/Character.hx:304: characters 87-101 : flxanimate.animate.FlxAnim has no field lastPlayedAnim source/states/stages/Tank.hx:310: lines 310-315 : () -> Void should be flixel.util.FlxSignal source/states/stages/Tank.hx:310: lines 310-315 : ... For function argument 'func'
> 
> > > > done. Press any key to continue . . .
> 
> > > > got past the sscript thing but now this is happening. thank you for the sscript thing
> 
> > > 
> 
> > > 
> 
> > > For the tank idk
> 
> > > for the flxanimate do this: haxelib remove flxanimate
> 
> > > then put this altogether: haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev
> 
> > 
> 
> > I'm sorry for making this take so long but it finally worked. thank you so much. you cant even believe how happy I am because I've been trying this daily for a while with no tutorials.
> 
> 
> 
> for some reason i didnt get a notification about ur response but np

Sorry im not used to closing things on GitHub since I've never really used it except for downloading.
