### ISSUE TITLE
LuaText does not appear on screen.

### ISSUE THREAD

**Issue by Porcupine2009** [ShadowMario/FNF-PsychEngine#15847]
### Describe your problem here.

Before reading, please note that I am using the V.1.0 **prerelease** build, mostly because a lot of the scripts I'm using on my modpack break on the current version (most likely thanks to the cameraX and cameraY values dying)

Moving on,
I am attempting to make a song title script similar to the Mario's Madness mod using LuaText and onStepHit/if curStep == x
Whenever it is called on that step, however, the text doesn't appear. Am I doing something wrong, or is it a problem with my build?

Code:
`function onStepHit() --triggers the opening.
    if curStep == 32 then --Change this to when you want it to start. Go to the chart editor and look for "step." You can also change it to "curBeat" if you want but I don't reccomend it.
    makeLuaText('SongName', 'Test', 400, 500, 500)
    setTextSize('SongName', 50)
    setTextFont('SongName', 'sonic-roco.ttf')
    addLuaText('SongName')
    end
end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I have a mod folder with a whole ton of shit in it

**Comment by DetectiveZ5** [comment]
Seeing the code that you made, it is correct but isn't correct. The text must be created first using `function onCreatePost`, then declaring or showing it in `function onStepHit`

Here's your code again but fixed:
```haxe
-- This function runs after the initial creation of the scene and elements.
-- It sets up the song title text but keeps it hidden until triggered in `onStepHit`.
function onCreatePost()
    -- Create the text object with ID 'SongName', display text 'Test', the width (400), and coordinates (500, 500).
    makeLuaText('SongName', 'Test', 400, 500, 500)
    
    -- Set the text size to 50 for better visibility.
    setTextSize('SongName', 50)
    
    -- Set the font for the text. Ensure 'sonic-roco.ttf' is in the mods/fonts directory.
    setTextFont('SongName', 'sonic-roco.ttf')
    
    -- Add the text to the screen. Initially, it will be invisible.
    addLuaText('SongName')
    
    -- Set the alpha (opacity) of 'SongName' to 0 so it remains hidden until triggered.
    setProperty('SongName.alpha', 0)
end

-- This function monitors the current step in the song and triggers events when specific steps are reached.
function onStepHit()
    -- Check if the current step is 32, which is when we want to reveal the text.
    if curStep == 32 then
        -- Create a tween to smoothly fade in the text from alpha 0 to 1 over 2 seconds.
        -- 'fadeInText' is the tween ID, 'SongName' is the target, 1 is the target alpha, 
        -- 2 is the duration, and 'smootherStepOut' defines the easing for a smooth transition.
        doTweenAlpha('fadeInText', 'SongName', 1, 2, 'smootherStepOut')
    end
end
```

**Comment by Porcupine2009** [comment]
Thank you, this fixed it :)
