### ISSUE TITLE
will my video .hx script work in 0.7.3 source code?

### ISSUE THREAD

**Issue by NiftyAC** [ShadowMario/FNF-PsychEngine#15848]
### What is your question?

im trying to use my 0.7.3 mods folder script in the compiled version of the game but I get an error everytime that says 

"ERROR ON LOADING: mods/'mymod'scripts/VideoSpriteHandler.hx: 130: Tried to access null variable FlxVideo"
this is the .hx script

forgot to say this but it works fine on the downloaded version of 0.7.3 but when I compile from the source code myself it doesn't work.

import psychlua.LuaUtils;
import hxcodec.flixel.FlxVideo;

var globalData:Array<Array> = [];

createGlobalCallback('makeVideoSprite', function(tag:String, videoFile:String, ?x:Float, ?y:Float, ?camera:String, ?shouldLoop:Bool)
{
    var videoData:Array = [];

    // Check if the tag already exists and return without showing an error message
    if (game.modchartSprites.exists(tag + '_video'))
    {
        return; // Simply return if the tag already exists
    }

    if (!FileSystem.exists(Paths.video(videoFile)))
    {
        debugPrint('makeVideoSprite: The video file "' + videoFile + '" cannot be found!', FlxColor.RED);
        return;
    }

    var sprite:FlxSprite = new FlxSprite(x, y).makeGraphic(1, 1, FlxColor.TRANSPARENT);
    sprite.camera = LuaUtils.cameraFromString(camera);
    game.modchartSprites.set(tag + '_video', sprite);
    add(sprite);

    var video:FlxVideo = new FlxVideo();

    video.alpha = 0;

    video.onTextureSetup.add(function()
    {
        sprite.loadGraphic(video.bitmapData);
    });

    video.play(Paths.video(videoFile), shouldLoop);

    video.onEndReached.add(function()
    {
        video.dispose();
        
        if (FlxG.game.contains(video))
            FlxG.game.removeChild(video);
        
        if (globalData.indexOf(videoData) >= 0)
            globalData.remove(videoData);
        
        if (game.modchartSprites.exists(tag + '_video'))
        {
            game.modchartSprites.get(tag + '_video').destroy();
            game.modchartSprites.remove(tag + '_video');
        }
            
        game.callOnLuas('onVideoFinished', [tag]);
        
        return;
    }, true);

    FlxG.game.addChild(video);

    videoData.push(video);
    videoData.push(sprite);

    globalData.push(videoData);
});

function onPause()
{
    for (video in globalData)
    {
        if (video[0] != null)
        {
            video[0].pause();

            if (FlxG.autoPause)
            {
                if (FlxG.signals.focusGained.has(video[0].resume))
                    FlxG.signals.focusGained.remove(video[0].resume);

                if (FlxG.signals.focusLost.has(video[0].pause))
                    FlxG.signals.focusLost.remove(video[0].pause);
            }
        }
    }
}

function onResume()
{
    for (video in globalData)
    {
        if (video[0] != null)
            video[0].resume();

        if (FlxG.autoPause)
        {
            if (!FlxG.signals.focusGained.has(video[0].resume))
                FlxG.signals.focusGained.add(video[0].resume);

            if (!FlxG.signals.focusLost.has(video[0].pause))
                FlxG.signals.focusLost.add(video[0].pause);
        }
    }
}

function onDestroy()
{
    for (video in globalData)
    {
        if (video[0] != null)
            video[0].stop();
    }
}

var cache:Array = ['open', 'SO_STAY_FINAL'];

function precacheVideos()
{
    for (i in 0 ... cache.length)
    {
        var video:FlxVideo = new FlxVideo();
        video.play(Paths.video(cache[i]));
        video.stop();
    }
}

precacheVideos();

**Comment by DetectiveZ5** [comment]
In the code below:
```haxe 
video.onEndReached.add(function()
{
    video.dispose();
    
    if (FlxG.game.contains(video))
        FlxG.game.removeChild(video);

    if (globalData.indexOf(videoData) >= 0)
        globalData.remove(videoData);
    
    if (game.modchartSprites.exists(tag + '_video'))
    {
        game.modchartSprites.get(tag + '_video').destroy();
        game.modchartSprites.remove(tag + '_video');
    }
        
    game.callOnLuas('onVideoFinished', [tag]);
    
    return;
}, true);
``` 

Anything other than `video.dispose();` will just throw an error because it's trying to access the already DISPOSED video. But if you think that the stuff below `video.dispose();` is important, try to put the `video.dispose();` below the `game.callOnLuas('onVideoFinished', [tag]);`. If that doesn't solve your issue, come back to me.

**Comment by NiftyAC** [comment]
> In the code below:
> 
> ```haxe 
> 
> video.onEndReached.add(function()
> 
> {
> 
>     video.dispose();
> 
>     
> 
>     if (FlxG.game.contains(video))
> 
>         FlxG.game.removeChild(video);
> 
> 
> 
>     if (globalData.indexOf(videoData) >= 0)
> 
>         globalData.remove(videoData);
> 
>     
> 
>     if (game.modchartSprites.exists(tag + '_video'))
> 
>     {
> 
>         game.modchartSprites.get(tag + '_video').destroy();
> 
>         game.modchartSprites.remove(tag + '_video');
> 
>     }
> 
>         
> 
>     game.callOnLuas('onVideoFinished', [tag]);
> 
>     
> 
>     return;
> 
> }, true);
> 
> ``` 
> 
> 
> 
> Anything other than `video.dispose();` will just throw an error because it's trying to access the already DISPOSED video. But if you think that the stuff below `video.dispose();` is important, try to put the `video.dispose();` below the `game.callOnLuas('onVideoFinished', [tag]);`. If that doesn't solve your issue, come back to me.

I know almost nothing about code so I'll just say this and ask what you think. My entire song is just a video played in the background of it since I'm trying to chart stronger than you. Do I need to change the video dispose for that and how? If you reply please make it in baby terms because I'm absolutely horrible when it comes to code.

**Comment by DetectiveZ5** [comment]
Sheesh, sorry but I already don't speak like that, and I'm not roasting you because of that. Instead, just use this that I asked from chatgpt:
To make the video play in the background for the entire song, you’ll want to make sure the video doesn’t “dispose” itself or disappear until the song is completely finished. Here's how to adjust the code for that:

### Step-by-Step Adjustments

1. **Remove the Disposal Step Temporarily**: Since the video disappearing is likely due to the `dispose` function being called too soon, you can try removing the `dispose` step in the code. This way, the video will stay around for the full duration of the song.

   Here’s how to adjust that part of the code:
   
   - Find the section that says:
     ```haxe
     video.onEndReached.add(function()
     {
         video.dispose();
         // (rest of the code here)
     }, true);
     ```
   - And change it to:
     ```haxe
     video.onEndReached.add(function()
     {
         // Keep the rest of the code, but REMOVE or comment out the line that says "video.dispose();"
         // Now the video will not disappear as soon as it reaches the end
     }, true);
     ```

2. **Set the Video to Loop if Needed**: If the song is longer than the video and you want the video to keep playing, set the `shouldLoop` option to `true` when the video starts. This means that when the video ends, it will automatically start over instead of stopping.

   Look for where the video is being set up in the function:
   ```haxe
   video.play(Paths.video(videoFile), true); // Set `true` here if you want the video to loop
   ```

3. **Make Sure It Matches the Song Length**: If the song and the video are exactly the same length, you don’t need to loop it. But if the song is longer, adding that `true` for looping will keep it in the background for the whole time.

### Summary
Removing `video.dispose()` and setting the `shouldLoop` to `true` should keep your video running smoothly in the background while you work on charting your song! 

If you’re not sure how to edit this in your code or need help finding these sections, let me know, and I can walk you through it further.

**Comment by NiftyAC** [comment]
> Sheesh, sorry but I already don't speak like that, and I'm not roasting you because of that. Instead, just use this that I asked from chatgpt:
> 
> To make the video play in the background for the entire song, you’ll want to make sure the video doesn’t “dispose” itself or disappear until the song is completely finished. Here's how to adjust the code for that:
> 
> ### Step-by-Step Adjustments
> 1. **Remove the Disposal Step Temporarily**: Since the video disappearing is likely due to the `dispose` function being called too soon, you can try removing the `dispose` step in the code. This way, the video will stay around for the full duration of the song.
>    Here’s how to adjust that part of the code:
>    
>    * Find the section that says:
>      ```hx
>      video.onEndReached.add(function()
>      {
>          video.dispose();
>          // (rest of the code here)
>      }, true);
>      ```
>    * And change it to:
>      ```hx
>      video.onEndReached.add(function()
>      {
>          // Keep the rest of the code, but REMOVE or comment out the line that says "video.dispose();"
>          // Now the video will not disappear as soon as it reaches the end
>      }, true);
>      ```
> 2. **Set the Video to Loop if Needed**: If the song is longer than the video and you want the video to keep playing, set the `shouldLoop` option to `true` when the video starts. This means that when the video ends, it will automatically start over instead of stopping.
>    Look for where the video is being set up in the function:
>    ```hx
>    video.play(Paths.video(videoFile), true); // Set `true` here if you want the video to loop
>    ```
> 3. **Make Sure It Matches the Song Length**: If the song and the video are exactly the same length, you don’t need to loop it. But if the song is longer, adding that `true` for looping will keep it in the background for the whole time.
> 
> ### Summary
> Removing `video.dispose()` and setting the `shouldLoop` to `true` should keep your video running smoothly in the background while you work on charting your song!
> 
> If you’re not sure how to edit this in your code or need help finding these sections, let me know, and I can walk you through it further.

it didn't work so I don't know what to do. I'm not trying to keep this going forever so I think ill just install 0.7.3 again and use the normal one instead of compiling it myself. thank you for your help though.

**Comment by DetectiveZ5** [comment]
Your welcome. Also don't forget to close this

**Comment by NiftyAC** [comment]
> Your welcome. Also don't forget to close this issue

I'm mad at myself. I was looking and I didn't take the videos allowed out of the section in project.xml. IN MY DEFENSE THOUGH, I didn't know it existed. You cannot believe how mad that made me. Anyway thank you.
