### ISSUE TITLE
How do you use the newly added mod loader/unloader on the latest commit?

### ISSUE THREAD

**Issue by DaBanana64** [ShadowMario/FNF-PsychEngine#1585]
### What is your question?

![SPOILER_unknown](https://user-images.githubusercontent.com/82652849/144401018-fe6abdd1-1d44-43d2-920f-15af634786ab.png)
So I'm on the latest commit and how do I use this thing? Does it work at all or it is not finished yet?

**Comment by CrusherMods** [comment]
probably not finished yet

**Comment by DaBanana64** [comment]
> probably not finished yet

Damn.

**Comment by Doritojoey** [comment]
Mod toggle isnt functional but there is an example json, can be put anywhere in the mods folder but i'm pretty sure there's going to be a specified folder for packs once the feature is complete

**Comment by DaBanana64** [comment]
> Mod toggle isnt functional but there is an example json, can be put anywhere in the mods folder but i'm pretty sure there's going to be a specified folder for packs once the feature is complete

Wow ok.
