### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by derpy369** [ShadowMario/FNF-PsychEngine#15852]
### Describe your bug here.

Whenever I try to compile the game using BUILDING.md, this error always shows up and the exe file is not there! Can someone help please??

### Command Prompt/Terminal logs (if existing)

```bash
Warning: Could not find Visual Studio VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Shadow06735** [comment]
did you download visual studio?

**Comment by derpy369** [comment]
> did you download visual studio?

oh shoot i forgot
