### ISSUE TITLE
add an achievement that is unlocked when playing a certain week with botplay

### ISSUE THREAD

**Issue by L044washere** [ShadowMario/FNF-PsychEngine#15869]
### Describe your problem here.

as it says on the issue title, i'm trying to do that if the game detects a week is completed with botplay (and also practice mode cuz why not), it unlocks an achievement. i already added it into Achievements.hx and PlayState.hx.

this is how i wrote the code to unlock it, but it won't work because the weekData is an unknown identifier.

`case 'botplay_achievement':
						unlock = (ClientPrefs.getGameplaySetting('botplay') && usedPractice && weekData.getCurrentWeek('weekplaceholder'));`

any kind of help is appreciated.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

mostly modified the PlayState.hx and the Achievements.hx files.

**Comment by CrusherNotDrip** [comment]
you forgot to uppercase the W in `weekData`

**Comment by L044washere** [comment]
it works now. i also modified the WeekData thing to `WeekData.getCurrentWeek().weekName == 'weekplaceholder'` since i placed too many arguments in `getCurrentWeek`. thanks.
