### ISSUE TITLE
Add cutscene in the start of the song

### ISSUE THREAD

**Issue by Wh4pzkxdd** [ShadowMario/FNF-PsychEngine#15867]
### Describe your problem here.

help me

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Shadow06735** [comment]
local allowCountdown = false
function onStartCountdown()
        if not allowCountdown and isStoryMode and not seenCutscene then
                startVideo('your_cutscene_name_here');
                allowCountdown = true;
                return Function_Stop;
        end
