### ISSUE TITLE
How to change opponent note in PsychEngine 1.0?

### ISSUE THREAD

**Issue by DavesTheBone** [ShadowMario/FNF-PsychEngine#15862]
### Describe your problem here.

uhhhhhh.
how to change opponent note in PE 1.0?
i want use lua.
here is note and xml.

note
![polynote](https://github.com/user-attachments/assets/542e50b1-dcfa-41ad-8773-a8ef37de2f1e)

xml
```
<TextureAtlas imagePath="polynote.png">
<!--  Created with Adobe Animate version 21.0.0.35450  -->
<!--  http://www.adobe.com/products/animate.html  -->
<SubTexture name="arrowLEFT0000" x="488" y="238" width="155" height="158"/>
<SubTexture name="arrowDOWN0000" x="647" y="238" width="157" height="155"/>
<SubTexture name="arrowRIGHT0000" x="808" y="238" width="155" height="157"/>
<SubTexture name="arrowUP0000" x="323" y="240" width="157" height="154"/>
<SubTexture name="blue hold end0000" x="1062" y="452" width="51" height="64"/>
<SubTexture name="blue hold piece0000" x="1282" y="457" width="51" height="44"/>
<SubTexture name="blue0000" x="0" y="240" width="158" height="154"/>
<SubTexture name="down confirm0000" x="0" y="0" width="240" height="236" frameX="-6" frameY="0" frameWidth="240" frameHeight="236"/>
<SubTexture name="down confirm0001" x="244" y="0" width="240" height="236" frameX="-6" frameY="0" frameWidth="240" frameHeight="236"/>
<SubTexture name="down confirm0002" x="1206" y="235" width="221" height="218" frameX="-12" frameY="-12" frameWidth="240" frameHeight="236"/>
<SubTexture name="down confirm0003" x="1206" y="235" width="221" height="218" frameX="-12" frameY="-12" frameWidth="240" frameHeight="236"/>
<SubTexture name="down press0000" x="805" y="399" width="143" height="139" frameX="-4" frameY="-3" frameWidth="150" frameHeight="146"/>
<SubTexture name="down press0001" x="805" y="399" width="143" height="139" frameX="-4" frameY="-3" frameWidth="150" frameHeight="146"/>
<SubTexture name="down press0002" x="1898" y="0" width="150" height="146"/>
<SubTexture name="down press0003" x="1898" y="0" width="150" height="146"/>
<SubTexture name="green hold end0000" x="1007" y="452" width="51" height="64"/>
<SubTexture name="green hold piece0000" x="1227" y="457" width="51" height="44"/>
<SubTexture name="green0000" x="162" y="240" width="157" height="154"/>
<SubTexture name="left confirm0000" x="972" y="0" width="230" height="232"/>
<SubTexture name="left confirm0001" x="1438" y="233" width="220" height="222" frameX="-5" frameY="-5" frameWidth="230" frameHeight="232"/>
<SubTexture name="left confirm0002" x="1438" y="0" width="227" height="229" frameX="-2" frameY="-1" frameWidth="230" frameHeight="232"/>
<SubTexture name="left confirm0003" x="1438" y="0" width="227" height="229" frameX="-2" frameY="-1" frameWidth="230" frameHeight="232"/>
<SubTexture name="left press0000" x="1898" y="449" width="139" height="142" frameX="-4" frameY="-3" frameWidth="146" frameHeight="149"/>
<SubTexture name="left press0001" x="1898" y="449" width="139" height="142" frameX="-4" frameY="-3" frameWidth="146" frameHeight="149"/>
<SubTexture name="left press0002" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0003" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0004" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0005" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0006" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0007" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0008" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0009" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0010" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0011" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0012" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0013" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0014" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0015" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0016" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0017" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0018" x="1898" y="150" width="146" height="149"/>
<SubTexture name="left press0019" x="1898" y="150" width="146" height="149"/>
<SubTexture name="pruple end hold0000" x="1117" y="452" width="51" height="64"/>
<SubTexture name="purple hold piece0000" x="1337" y="457" width="51" height="44"/>
<SubTexture name="purple0000" x="0" y="398" width="154" height="157"/>
<SubTexture name="red hold end0000" x="952" y="452" width="51" height="64"/>
<SubTexture name="red hold piece0000" x="1172" y="457" width="51" height="44"/>
<SubTexture name="red0000" x="647" y="397" width="154" height="157"/>
<SubTexture name="right confirm0000" x="1669" y="0" width="225" height="228" frameX="-1" frameY="-2" frameWidth="228" frameHeight="231"/>
<SubTexture name="right confirm0001" x="1669" y="232" width="225" height="228" frameX="-1" frameY="-2" frameWidth="228" frameHeight="231"/>
<SubTexture name="right confirm0002" x="1206" y="0" width="228" height="231"/>
<SubTexture name="right confirm0003" x="1206" y="0" width="228" height="231"/>
<SubTexture name="right press0000" x="469" y="400" width="139" height="142" frameX="-3" frameY="-7" frameWidth="149" frameHeight="152"/>
<SubTexture name="right press0001" x="469" y="400" width="139" height="142" frameX="-3" frameY="-7" frameWidth="149" frameHeight="152"/>
<SubTexture name="right press0002" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0003" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0004" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0005" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0006" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0007" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0008" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0009" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0010" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0011" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0012" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0013" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0014" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0015" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0016" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0017" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0018" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0019" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0020" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0021" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0022" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0023" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0024" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0025" x="316" y="398" width="149" height="152"/>
<SubTexture name="right press0026" x="316" y="398" width="149" height="152"/>
<SubTexture name="up confirm0000" x="488" y="0" width="238" height="234"/>
<SubTexture name="up confirm0001" x="730" y="0" width="238" height="234"/>
<SubTexture name="up confirm0002" x="972" y="236" width="216" height="212" frameX="-11" frameY="-11" frameWidth="238" frameHeight="234"/>
<SubTexture name="up confirm0003" x="972" y="236" width="216" height="212" frameX="-11" frameY="-11" frameWidth="238" frameHeight="234"/>
<SubTexture name="up press0000" x="1898" y="303" width="144" height="142" frameX="-6" frameY="-4" frameWidth="154" frameHeight="151"/>
<SubTexture name="up press0001" x="1898" y="303" width="144" height="142" frameX="-6" frameY="-4" frameWidth="154" frameHeight="151"/>
<SubTexture name="up press0002" x="158" y="398" width="154" height="151"/>
<SubTexture name="up press0003" x="158" y="398" width="154" height="151"/>
</TextureAtlas>
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by DetectiveZ5** [comment]
The problem is, you can't. The game just automatically colors the notes and the notes image should look like this:
![NOTE_assets](https://github.com/user-attachments/assets/1c6cdc5c-cd43-45fd-82b9-8546d4e790ca)

You'll need @ShadowMario 's direct help if you want to make this on your notes

**Comment by DavesTheBone** [comment]
hmmm ok

**Comment by Shadow06735** [comment]
function onCreatePost()
	setProperty('wiggle.scale.y', 0.5)
	setProperty('wiggle.y', -700)
	scaleObject('wiggle', 1.8, 1.8)
	p1pos = getProperty('iconP1.y')
	p2pos = getProperty('iconP2.y')


	for i=0,4,1 do
		setPropertyFromGroup('opponentStrums', i, 'texture', 'your_note_assets_here')
        end
        
        for i = 0, getProperty('unspawnNotes.length')-1 do
		if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'your_note_assets_here'); --Change texture 
        end
end
end

**Comment by DetectiveZ5** [comment]
> function onCreatePost() setProperty('wiggle.scale.y', 0.5) setProperty('wiggle.y', -700) scaleObject('wiggle', 1.8, 1.8) p1pos = getProperty('iconP1.y') p2pos = getProperty('iconP2.y')
> 
> ```
> for i=0,4,1 do
> 	setPropertyFromGroup('opponentStrums', i, 'texture', 'your_note_assets_here')
>     end
>     
>     for i = 0, getProperty('unspawnNotes.length')-1 do
> 	if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
> 		setPropertyFromGroup('unspawnNotes', i, 'texture', 'your_note_assets_here'); --Change texture 
>     end
> ```
> 
> end end
> 
> i have no idea why one section became like that, but you can just copy everything and paste it like normal

I mean yea sure use this without configuring the notes first (If you want the notes to look like shii).

**Comment by DavesTheBone** [comment]
> for i=0,4,1 do
> 	setPropertyFromGroup('opponentStrums', i, 'texture', 'your_note_assets_here')
>     end
>     
>     for i = 0, getProperty('unspawnNotes.length')-1 do
> 	if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
> 		setPropertyFromGroup('unspawnNotes', i, 'texture', 'your_note_assets_here'); --Change texture 
>     end

![image](https://github.com/user-attachments/assets/fd1eec29-9200-4868-abbe-051bbdff9954)

i got error

**Comment by DetectiveZ5** [comment]
```lua
function onCreatePost()
    for i=0,4,1 do
	setPropertyFromGroup('opponentStrums', i, 'texture', 'your_note_assets_here')
    end
    
    for i = 0, getProperty('unspawnNotes.length')-1 do
	if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
		setPropertyFromGroup('unspawnNotes', i, 'texture', 'your_note_assets_here'); --Change texture 
    end
end
end
```

In the picture and the code that you copied, It says that you removed an `end` in the code, probably guessing the last `end` that you probably saw and removed since it's misaligned and that you thoght that may not be actually needed.

**Comment by Shadow06735** [comment]
> ```lua
> function onCreatePost()
>     -- Change texture for opponent notes
>     for i = 0, 3 do
>         setPropertyFromGroup('opponentStrums', i, 'texture', 'noteSkins/polynote')
>     end
> 
>     -- Change texture for player notes
>     for i = 0, 3 do
>         setPropertyFromGroup('playerStrums', i, 'texture', 'noteSkins/polynote')
>     end
> 
>     -- Change texture for unspawned notes (both opponent and player)
>     for i = 0, getProperty('unspawnNotes.length') - 1 do
>         setPropertyFromGroup('unspawnNotes', i, 'texture', 'noteSkins/polynote')
>     end
> end
> -- All of the code that you see here is what I edited so you can test it yourself
> ```
> 
> In the picture and the code that you copied, It says that you removed an `end` in the code, probably guessing the last `end` that you probably saw and removed since it's misaligned and that you thoght that may not be actually needed. But, you can use the code that I made myself since the original code that I saw is somewhat not good enough and of course, may provide confusion.

idk why my code became misaligned when I put it in the GitHub, and I’m also not sure how I’m suppose to make it aligned

**Comment by DetectiveZ5** [comment]
Yeah just use these lines and it will just align itself
'
```lua
```
'

**Comment by DetectiveZ5** [comment]
Yeah you can use triple backticks to show your code and it will align itself like this:
````
Code goes here
````

**Comment by DavesTheBone** [comment]
> > ```lua
> > function onCreatePost()
> >     -- Change texture for opponent notes
> >     for i = 0, 3 do
> >         setPropertyFromGroup('opponentStrums', i, 'texture', 'noteSkins/polynote')
> >     end
> > 
> >     -- Change texture for player notes
> >     for i = 0, 3 do
> >         setPropertyFromGroup('playerStrums', i, 'texture', 'noteSkins/polynote')
> >     end
> > 
> >     -- Change texture for unspawned notes (both opponent and player)
> >     for i = 0, getProperty('unspawnNotes.length') - 1 do
> >         setPropertyFromGroup('unspawnNotes', i, 'texture', 'noteSkins/polynote')
> >     end
> > end
> > -- All of the code that you see here is what I edited so you can test it yourself
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the picture and the code that you copied, It says that you removed an `end` in the code, probably guessing the last `end` that you probably saw and removed since it's misaligned and that you thoght that may not be actually needed. But, you can use the code that I made myself since the original code that I saw is somewhat not good enough and of course, may provide confusion.
> 
> idk why my code became misaligned when I put it in the GitHub, and I’m also not sure how I’m suppose to make it aligned

ok
