### ISSUE TITLE
Fps Issues

### ISSUE THREAD

**Issue by N0m0ph0bia** [ShadowMario/FNF-PsychEngine#15864]
### Describe your bug here.

With the new pshyc engine update the FPS keeps on dropping due to the new Menu screens!
alongside that the game rederes to a gigabite after loading a song

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I have no edited anything in the build

**Comment by DetectiveZ5** [comment]
It sounds like the new update might be pushing your system's limits, as the recent changes may require higher performance than before. I’d recommend adjusting some settings in the Graphics menu to improve performance—try lowering or turning off options like Shaders, GPU Caching, FPS Cap, and Anti-Aliasing, and be sure to enable Low-Quality mode if it isn’t already on. These adjustments should help reduce FPS drops and memory usage.

If you still experience issues, consider visiting a local repair center to see if upgrading your RAM or storage could give your system the boost it needs to handle the game more smoothly.

Also, @ShadowMario, if you’re reading this, it might be helpful to pin this information for other PC users who may encounter similar issues.

**Comment by N0m0ph0bia** [comment]
Ok ill try that and get back to you if that dosent work
