### ISSUE TITLE
CHARACTER CREATOR

### ISSUE THREAD

**Issue by gamerz75799** [ShadowMario/FNF-PsychEngine#15879]
### What feature do you want to get added on the **base** engine?

Can you add character creator creator, I really want to make a mod but I don't know how to make a character. After making making the mod I promise to add u in credits. And also long notes are so annoying you literally have to complete or you will get a miss.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by acap09** [comment]
is this a joke?

**Comment by Lorekeeper49** [comment]
First of all, the character creator is already there just press 7 on the main menu and you'll find it.  And secondly, long notes wouldn't be much of a proper note if you didn't have to complete it to avoid missing.
