### ISSUE TITLE
I have absolutely no clue whats happening (when i try to compile)

### ISSUE THREAD

**Issue by piggytoonvr** [ShadowMario/FNF-PsychEngine#15870]
### Describe your problem here.

![image](https://github.com/user-attachments/assets/bf9f5ce0-a05a-4b6c-bf47-59c958eeb484)
I'm trying to compile and it wont work 😭 
I don't know what it is.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by L044washere** [comment]
try to reinstall FlxAnimate using `haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev`.

**Comment by piggytoonvr** [comment]
thanks!
