### ISSUE TITLE
How to put a video underneath the UI in psych engine 5.2

### ISSUE THREAD

**Issue by Eugeniocrazy** [ShadowMario/FNF-PsychEngine#15875]
### Describe your problem here.

Can someone give me an event that can help me put a video cutscene into a little lyric section? (it's for an aethos mod btw) and also, it's for the build 5.2.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

**Comment by ShadowMario** [comment]
0.5.2 is not maintained anymore, please don't report issues with it.
