### ISSUE TITLE
webm support

### ISSUE THREAD

**Issue by ILuvGemz** [ShadowMario/FNF-PsychEngine#1587]
### What feature do you want to get added on the base engine?

I'd love to see you implement webm support for Psych as an alternative to people who are used to using it.

Two of the benefits is that you can skip videos with webm, as well as porting mods to Mac and Linux, as mp4 is now only working in Windows.

**Comment by NotEpik** [comment]
maybe someone will say "BRO MP4 IS ALREADY THERE IS AT BETTER" but as I read you want cutscene to work in mac/linux, good idea

**Comment by ShadowMario** [comment]
This was already requested before, Webms suck.
