### ISSUE TITLE
Unexpected token "run" haxelib

### ISSUE THREAD

**Issue by Mcknight231** [ShadowMario/FNF-PsychEngine#15886]
### Describe your problem here.

I'm tying to run lime setup, but this error keeps popping up

At line:1 char:35
+ "C:\HaxeToolkit\haxe\haxelib.exe" run lime setup
+                                   ~~~
Unexpected token 'run' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
    
    Any help is appreciated)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by KELOTOMU** [comment]
just do 'lime setup' in cmd, u dint need to go to the haxelibtoolkit directory

**Comment by Mcknight231** [comment]
Now it says "lime' is not recognized as an internal or external command,
operable program or batch file." ughhh idk what 2 do anymooore
