### ISSUE TITLE
vanilla features

### ISSUE THREAD

**Issue by bysisigma45** [ShadowMario/FNF-PsychEngine#15885]
### What feature do you want to get added on the **base** engine?

Can you add vanilla features on version 0.5.2? like change characters, erect mode, ect.

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by Lorekeeper49** [comment]
Can you look at 1.0 please?

**Comment by bysisigma45** [comment]
i didn't mean weekend 1, i mean the remixes

**Comment by ShadowMario** [comment]
0.5.2 fucking sucks
