### ISSUE TITLE
Icons dissappearing

### ISSUE THREAD

**Issue by endi962** [ShadowMario/FNF-PsychEngine#15889]
### Describe your bug here.

I don't know why, but after the 1.0 update all my characters Icons dissappeared, the icons are attached with the characters btw.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I did, but nothing related to my problem.

**Comment by Shadow06735** [comment]
are the icons named "icon-charactername" and in the icons folder in images?

**Comment by endi962** [comment]
> are the icons named "icon-charactername" and in the icons folder in images?

Yes

**Comment by Shadow06735** [comment]
> > are the icons named "icon-charactername" and in the icons folder in images?
> 
> Yes

is there any script that you use to modify the icons?

**Comment by endi962** [comment]
> > > are the icons named "icon-charactername" and in the icons folder in images?
> > 
> > 
> > Yes
> 
> is there any script that you use to modify the icons?

No

**Comment by Shadow06735** [comment]
> > > > are the icons named "icon-charactername" and in the icons folder in images?
> > > 
> > > 
> > > Yes
> > 
> > 
> > is there any script that you use to modify the icons?
> 
> No

maybe try removing and adding the icons to the character again?

**Comment by endi962** [comment]
Nvm, i just took a health thing script, it just got fixed, thanks and sorry.

**Comment by Shadow06735** [comment]
> Nvm, i just took a health thing script, it just got fixed, thanks and sorry.

it k. you can close this now
