### ISSUE TITLE
lime : The term 'lime' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again

### ISSUE THREAD

**Issue by Mcknight231** [ShadowMario/FNF-PsychEngine#15881]
### Describe your problem here.

lime : The term 'lime' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by CrusherNotDrip** [comment]
`haxelib run lime setup`
