### ISSUE TITLE
idk what's the name

### ISSUE THREAD

**Issue by bysisigma45** [ShadowMario/FNF-PsychEngine#15893]
### What is your question?

what's the name that making icons up and down?

**Comment by Shadow06735** [comment]
what are you talking abt?

**Comment by Lorekeeper49** [comment]
Could you be a little more clear about that?  Like, show us a picture or something?

**Comment by Shadow06735** [comment]
> Like on the Dave and Bambi : Grapple mod

oh it’s those rotating icons.

There’s a lot scripts related to it, just search up that type of icon bounce and you’ll find it easily.
