### ISSUE TITLE
I have an error when compiling the game

### ISSUE THREAD

**Issue by protoelconejo** [ShadowMario/FNF-PsychEngine#15896]
### Describe your problem here.

C:/HaxeToolkit/haxe/lib/discord_rpc/git/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
source/editors/ChartingState.hx:1402: characters 27-54 : String should be flash.media.Sound
source/editors/ChartingState.hx:1417: characters 27-56 : String should be flash.media.Sound
source/editors/ChartingState.hx:914: characters 22-51 : String should be flash.media.Sound
source/editors/ChartingState.hx:927: characters 24-51 : String should be flash.media.Sound
source/LoadingState.hx:140: characters 10-41 : String should be flash.media.Sound
source/LoadingState.hx:145: characters 10-43 : String should be flash.media.Sound
source/FreeplayState.hx:250: characters 42-75 : String should be flash.media.Sound
source/FreeplayState.hx:255: characters 25-56 : String should be flash.media.Sound
source/PlayState.hx:1422: characters 41-74 : String should be flash.media.Sound
source/PlayState.hx:1427: characters 51-82 : String should be flash.media.Sound
source/PlayState.hx:1384: characters 24-55 : String should be flash.media.Sound

is psych engine 0.4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Shadow06735** [comment]
0.4 is outdated, just use the newer versions.

**Comment by protoelconejo** [comment]
The newer versions give me more errors and are not as well optimized.

**Comment by Shadow06735** [comment]
> The newer versions give me more errors and are not as well optimized.

yeah but 0.4's libraries are outdated, which you would have to use at your own risk.

i recommend you use newer versions and if u get errors, try asking for help in the github or find closed issues related to it.
