### ISSUE TITLE
Making .json scripts for easily modding the intro text

### ISSUE THREAD

**Issue by SlickFromMars** [ShadowMario/FNF-PsychEngine#1590]
### What feature do you want to get added on the base engine?

An extra addition to the editor master menu that would be extremely useful is an intro text editor, where it can be stored in a .json

This would also be useable as you can decide to make it a mod json file in which you can pick whether it appends or replaces.

I could attempt to make this via forking and a pull request, if wanted.

**Comment by CrusherMods** [comment]
couldn't this be done in assets/data/introText.txt

**Comment by SlickFromMars** [comment]
Yes it can, but with the introText.txt in the mod folder, if I remember correctly it will ONLY append, and with the .json files, they can not only be saved and deleted separately for ease, as well as being more easily modded and decide to replace and or append

**Comment by SlickFromMars** [comment]
which would be a lot more convenient for some people.

**Comment by bbpanzu** [comment]
nope. if you add an introText.txt in the mod's folder it'll replace, not append

**Comment by SlickFromMars** [comment]
ah good to know. I really thing an appending feature would be pretty useful tho
