### ISSUE TITLE
Mod Enable/Disable in options

### ISSUE THREAD

**Issue by SlickFromMars** [ShadowMario/FNF-PsychEngine#1591]
### What feature do you want to get added on the base engine?

Maybe a settings area where you can enable and disable separate moddable sections (sprites, sounds, songs, ect.)

**Comment by DaBanana64** [comment]
![SPOILER_unknown](https://user-images.githubusercontent.com/82652849/144467918-b1c197c1-9ec4-43df-8887-801ee79f1c95.png)
This is being worked on as seen in the latest version.

**Comment by SlickFromMars** [comment]
ooh alright that works
