### ISSUE TITLE
icons and weeks doesnt change, doesnt importing

### ISSUE THREAD

**Issue by parallelogradus** [ShadowMario/FNF-PsychEngine#15923]
### Describe your problem here.

I put the icons in the folder that you can see in the photo. the size and "-" should meet the requirements. but when i enter the file name after "-" in the field nothing happens.

help please
![image](https://github.com/user-attachments/assets/ebaca2ef-d562-4801-9990-89d93bbfe390)

 also,the custom weeks are not visible in the story mode

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Shadow06735** [comment]
you gotta take "My-Mod" OUTSIDE the modtemplate, as modtemplate is a zip file so therefore the game can't get the files inside your modpack unless its a normal file.

**Comment by parallelogradus** [comment]
> you gotta take "My-Mod" OUTSIDE the modtemplate, as modtemplate is a zip file so therefore the game can't get the files inside your modpack unless its a normal file.

even if it's not zip anymore? i have unarchived that

**Comment by Shadow06735** [comment]
> > you gotta take "My-Mod" OUTSIDE the modtemplate, as modtemplate is a zip file so therefore the game can't get the files inside your modpack unless its a normal file.
> 
> even if it's not zip anymore? i have unarchived that

still, the my-mod has to be outside the modtemplate (in the mods folder) as the game can't reach the modpack assets by digging through 2 files.

**Comment by parallelogradus** [comment]
> > > you gotta take "My-Mod" OUTSIDE the modtemplate, as modtemplate is a zip file so therefore the game can't get the files inside your modpack unless its a normal file.
> > 
> > even if it's not zip anymore? i have unarchived that
> 
> still, the my-mod has to be outside the modtemplate (in the mods folder) as the game can't reach the modpack assets by digging through 2 files.

thank you a lot! it was so obvious problem

**Comment by Shadow06735** [comment]
> > > > you gotta take "My-Mod" OUTSIDE the modtemplate, as modtemplate is a zip file so therefore the game can't get the files inside your modpack unless its a normal file.
> > > 
> > > 
> > > even if it's not zip anymore? i have unarchived that
> > 
> > 
> > still, the my-mod has to be outside the modtemplate (in the mods folder) as the game can't reach the modpack assets by digging through 2 files.
> 
> thank you a lot! it was so obvious problem

np, you can close this issue now
