### ISSUE TITLE
Moddable settings

### ISSUE THREAD

**Issue by SlickFromMars** [ShadowMario/FNF-PsychEngine#1592]
### What feature do you want to get added on the base engine?

Ways to mod the settings in the mods folder, maybe storing the settings in seperate json files with an editor?

**Comment by Doritojoey** [comment]
This seems pretty unnecessary the entire game would also have to be unhardcoded for this to have any actual effect in gameplay unless it was for a stage, in which case wtf is the point of that

**Comment by SlickFromMars** [comment]
fair point I didn't think of that lmao. I dunno why or how I came up with that.
