### ISSUE TITLE
Vocal file issue

### ISSUE THREAD

**Issue by SandoMC** [ShadowMario/FNF-PsychEngine#15939]
### Describe your bug here.

So, im making a collab with my vocals and the inst of termination. The INST is working perfectly but when I put the vocals in the Termination folder, it won't work. 

READ BEFORE COMMENTING
-I checked "has voice track"
-I made sure it was a .ogg
-It is in the MOD folder, not Assets
-I tried multiple times

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Shadow06735** [comment]
What did you name the vocals file?

**Comment by SandoMC** [comment]
> What did you name the vocals file?

I named the file "Vocals"

**Comment by SandoMC** [comment]
> What did you name the vocals file?

![Uploading 20241119_195407.jpg…]()

**Comment by SandoMC** [comment]
> What did you name the vocals file?

![20241119_195407](https://github.com/user-attachments/assets/25a23c31-bcdc-44db-86ba-d4848e3886f2)

**Comment by Shadow06735** [comment]
> > What did you name the vocals file?
> 
> ![20241119_195407](https://private-user-images.githubusercontent.com/189057252/387887062-25a23c31-bcdc-44db-86ba-d4848e3886f2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjY2OTYsIm5iZiI6MTczMjA2NjM5NiwicGF0aCI6Ii8xODkwNTcyNTIvMzg3ODg3MDYyLTI1YTIzYzMxLWJjZGMtNDRkYi04NmJhLWQ0ODQ4ZTM4ODZmMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQwMTMzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmZjNzQ4YjI2MTZkMDdhYjMwOTdkMmM3NjgwYjA1ZDhlYjRiZTk2OGYyNmVkYTU2NjE4ODBiMDY4Nzg3YzU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K3bKxWKHXgOIqyKd1E8fEKOAbCTR2Ze2_PDX-srm90M)

It needs to be named Voices, otherwise the game can’t get the vocal file.

**Comment by SandoMC** [comment]
> > > What did you name the vocals file?
> > 
> > 
> > ![20241119_195407](https://private-user-images.githubusercontent.com/189057252/387887062-25a23c31-bcdc-44db-86ba-d4848e3886f2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjY2OTYsIm5iZiI6MTczMjA2NjM5NiwicGF0aCI6Ii8xODkwNTcyNTIvMzg3ODg3MDYyLTI1YTIzYzMxLWJjZGMtNDRkYi04NmJhLWQ0ODQ4ZTM4ODZmMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQwMTMzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmZjNzQ4YjI2MTZkMDdhYjMwOTdkMmM3NjgwYjA1ZDhlYjRiZTk2OGYyNmVkYTU2NjE4ODBiMDY4Nzg3YzU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K3bKxWKHXgOIqyKd1E8fEKOAbCTR2Ze2_PDX-srm90M)
> 
> It needs to be named Voices, otherwise the game can’t get the vocal file.

Thank you!

**Comment by Shadow06735** [comment]
> > > > What did you name the vocals file?
> > > 
> > > 
> > > ![20241119_195407](https://private-user-images.githubusercontent.com/189057252/387887062-25a23c31-bcdc-44db-86ba-d4848e3886f2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjY2OTYsIm5iZiI6MTczMjA2NjM5NiwicGF0aCI6Ii8xODkwNTcyNTIvMzg3ODg3MDYyLTI1YTIzYzMxLWJjZGMtNDRkYi04NmJhLWQ0ODQ4ZTM4ODZmMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQwMTMzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmZjNzQ4YjI2MTZkMDdhYjMwOTdkMmM3NjgwYjA1ZDhlYjRiZTk2OGYyNmVkYTU2NjE4ODBiMDY4Nzg3YzU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K3bKxWKHXgOIqyKd1E8fEKOAbCTR2Ze2_PDX-srm90M)
> > 
> > 
> > It needs to be named Voices, otherwise the game can’t get the vocal file.
> 
> Thank you!

np
