### ISSUE TITLE
LogoBumpin Tween up when loaded

### ISSUE THREAD

**Issue by QEX-DE3** [ShadowMario/FNF-PsychEngine#15936]
### Describe your problem here.

I want my logo when loaded in titlestate  to tween upwards smoothly

Kinda like Mexifloors but instead of going down it goes up 

(using psych 0.7.2 btw)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Too much stuff to list

**Comment by Shadow06735** [comment]
first, you want to replace the logo Bl = new flxsprite line with this:
logoBl = new FlxSprite(-150, 1500);

then, add this line between the flxg.camera.flash and the var easteregg thingy:
FlxTween.tween(logoBl, {y: 10}, 1.4, {ease: FlxEase.expoInOut});

that should look something like this:
```haxe
FlxG.camera.flash(FlxColor.WHITE, 1);

FlxTween.tween(logoBl, {y: 10}, 1.4, {ease: FlxEase.expoInOut});

var easteregg:String = FlxG.save.data.psychDevsEasterEgg;
```

**Comment by QEX-DE3** [comment]
> first, you want to replace the logo Bl = new flxsprite line with this: logoBl = new FlxSprite(-150, 1500);
> 
> then, add this line between the flxg.camera.flash and the var easteregg thingy: FlxTween.tween(logoBl, {y: 10}, 1.4, {ease: FlxEase.expoInOut});
> 
> that should look something like this:
> 
> ```hx
> FlxG.camera.flash(FlxColor.WHITE, 1);
> 
> FlxTween.tween(logoBl, {y: 10}, 1.4, {ease: FlxEase.expoInOut});
> 
> var easteregg:String = FlxG.save.data.psychDevsEasterEgg;
> ```

So it works but how do i make it work with screen center cause right now its too the left?

**Comment by Shadow06735** [comment]
> > first, you want to replace the logo Bl = new flxsprite line with this: logoBl = new FlxSprite(-150, 1500);
> > then, add this line between the flxg.camera.flash and the var easteregg thingy: FlxTween.tween(logoBl, {y: 10}, 1.4, {ease: FlxEase.expoInOut});
> > that should look something like this:
> > ```hx
> > FlxG.camera.flash(FlxColor.WHITE, 1);
> > 
> > FlxTween.tween(logoBl, {y: 10}, 1.4, {ease: FlxEase.expoInOut});
> > 
> > var easteregg:String = FlxG.save.data.psychDevsEasterEgg;
> > ```
> 
> So it works but how do i make it work with screen center cause right now its too the left?
> 
> UPDATE: I made it work never mind thank you so much tho for the help fr.
> 
> (Sorry for late reply)

np, you can close this issue now
