### ISSUE TITLE
FlxSounds replacement fail?

### ISSUE THREAD

**Issue by IvanDruzya** [ShadowMario/FNF-PsychEngine#15935]
### Describe your problem here.

I encountered this
C:/HaxeToolkit/haxe/lib/flixel/5,8,0/flixel/system/frontEnds/SoundFrontEnd.hx:9: character 8 : `package flixel.system;` in source/flixel/sound/FlxSound.hx should be `package flixel.sound;`
source/flixel/sound/FlxSound.hx:597: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/sound/FlxSound.hx:601: characters 19-27 : flash.media.SoundChannel has no field __source
C:/HaxeToolkit/haxe/lib/flixel/5,8,0/flixel/sound/FlxSoundGroup.hx:92: characters 10-25 : Cannot access private field updateTransform
C:/HaxeToolkit/haxe/lib/flixel/5,8,0/flixel/sound/FlxSoundGroup.hx:43: characters 10-25 : Cannot access private field updateTransform
source/editors/ChartingState.hx:150: characters 13-21 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/Main.hx:85: characters 61-65 : Float should be Int
source/Main.hx:85: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:85: characters 61-65 : ... For function argument 'child'
source/PlayState.hx:75: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:109: characters 40-48 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:152: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:237: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:236: characters 27-35 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:340: characters 19-27 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:342: characters 19-27 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:491: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:509: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:515: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:567: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:573: characters 10-15 : Class<llua.LuaL> has no field error
source/FunkinLua.hx:613: lines 613-617 : Int should be Bool
source/FunkinLua.hx:613: lines 613-617 : ... For function argument 'f'
source/PauseSubState.hx:27: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:109: characters 68-76 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1620: characters 13-23 : Type not found : MP4Handler
source/FunkinLua.hx:2266: characters 18-26 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FunkinLua.hx:2300: characters 18-26 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PauseSubState.hx:64: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:581: characters 22-30 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2428: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2430: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:2434: characters 27-35 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1825: characters 22-30 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1825: characters 37-45 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1872: characters 19-27 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1872: characters 34-42 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1943: characters 21-29 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:1943: characters 36-44 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:1356: characters 16-24 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:2193: characters 14-22 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:2194: characters 14-20 : Cannot access private field _sound
source/editors/ChartingState.hx:2194: characters 38-44 : Cannot access private field _sound
source/editors/ChartingState.hx:2195: characters 29-35 : Cannot access private field _sound
source/editors/ChartingState.hx:2198: characters 12-18 : Cannot access private field _sound
source/editors/ChartingState.hx:2210: characters 14-22 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/ChartingState.hx:2211: characters 14-20 : Cannot access private field _sound
source/editors/ChartingState.hx:2211: characters 38-44 : Cannot access private field _sound
source/editors/ChartingState.hx:2212: characters 29-35 : Cannot access private field _sound
source/editors/ChartingState.hx:2215: characters 12-18 : Cannot access private field _sound
source/editors/EditorPlayState.hx:39: characters 13-21 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:110: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/editors/EditorPlayState.hx:112: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/TitleState.hx:719: characters 15-23 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
C:/HaxeToolkit/haxe/lib/flixel/5,8,0/flixel/sound/FlxSoundGroup.hx:61: characters 10-25 : Cannot access private field updateTransform
Please Help I have no Idea what to do!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I don't know what I edited sorry :<

**Comment by Shadow06735** [comment]
are you using 0.6.3? any version 0.6.3 and lower would give that error.

**Comment by IvanDruzya** [comment]
I want to create an mod in 0.6.3, why I can't?

**Comment by IvanDruzya** [comment]
Ok It's fixed now. I'm closing as solved.

**Comment by caramelcupcakes842** [comment]
how did you fix it? i'm facing the same error

**Comment by caramelcupcakes842** [comment]
> > how did you fix it? i'm facing the same error
> 
> It won't work in 0.6.3 or older so update the engine

i'm trying to build a specific build of a mod that's in that version that has been lost for three years now, if it was any other case i would other than me generally not liking the engine.
