### ISSUE TITLE
import problem

### ISSUE THREAD

**Issue by parallelogradus** [ShadowMario/FNF-PsychEngine#15947]
### Describe your problem here.

![image](https://github.com/user-attachments/assets/27c603e7-4970-4b6b-b353-65931cae3d65)

 i can to compilate so im sure i have these libraries but how can i import that then? 
 also, it's not right code for scrolling background, id want to know how can i do that, please..

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Shadow06735** [comment]
I think this can only be done with source (correct me if I’m wrong), as haxe and lua and 2 complete different programming languages
