### ISSUE TITLE
I Can't Find Countdown/Combo Messages In hx files

### ISSUE THREAD

**Issue by megalives717** [ShadowMario/FNF-PsychEngine#15954]
### What needs to be documented?

![messages](https://github.com/user-attachments/assets/b70c0b70-529e-41dd-b07c-900ccf738219)
How I Do Find Code In [source folder](https://github.com/ShadowMario/FNF-PsychEngine/tree/523cb3478c57efac66fad1580b50a5ee61a6d9bc/source)

**Comment by Shadow06735** [comment]
it might be in playstate.hx

**Comment by megalives717** [comment]
found thank you
