### ISSUE TITLE
Lime Test Cqq not working when trying to compile the game again

### ISSUE THREAD

**Issue by SamAlphaTheEpik** [ShadowMario/FNF-PsychEngine#15959]
### Describe your problem here.

Yesterday i just did the Pysch Engine Source Code for the first time ever and today **i tried to change the app's title, file, version and company on Project.XML.**
**I also tried to change the game's app icon.**
After i changed, i tried to compile the game but the lime test cqq code didn't not worked.
What i can do to fix this problem?
![Screenshot 2024-11-23 110811](https://github.com/user-attachments/assets/b8f926a0-c8c7-469a-a8bb-94994b24c156)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Project.XML and App Icon

**Comment by Shadow06735** [comment]
since your build target is windows x64, you should put "lime test windows" (correct me if im wrong)

**Comment by SamAlphaTheEpik** [comment]
> since your build target is windows x64, you should put "lime test windows" (correct me if im wrong)

Ok thank you.

**Comment by SamAlphaTheEpik** [comment]
> since your build target is windows x64, you should put "lime test windows" (correct me if im wrong)

So it worked.
But i also had this error which isn't from the situation of this issue.
![Screenshot 2024-11-23 174053](https://github.com/user-attachments/assets/89b8981c-f7ef-4bea-93b4-3a7d70fc5072)

**Comment by SamAlphaTheEpik** [comment]
> > since your build target is windows x64, you should put "lime test windows" (correct me if im wrong)
> 
> So it worked. But i also had this error which isn't from the situation of this issue. ![Screenshot 2024-11-23 174053](https://private-user-images.githubusercontent.com/182260232/389212542-89b8981c-f7ef-4bea-93b4-3a7d70fc5072.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODA3MTAsIm5iZiI6MTczMjM4MDQxMCwicGF0aCI6Ii8xODIyNjAyMzIvMzg5MjEyNTQyLTg5Yjg5ODFjLWY3ZWYtNGJlYS05M2I0LTNhN2Q3MGZjNTA3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxNjQ2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjA3NzZlMTJmZjFiMTAxZDRiNzQ2M2EyZjBhYTgzODYxZGZjN2Q4ZGU5MWY0MTgzM2YyMzJiMzkwYWE5NjUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KAKJkcu3AucW9g8K9_DzH1HmE69yzEmFs52Gj7W9aGc)

Nevermind i just had to do the windows setup again.
I guess everything it's fine.
How do i close this argument now.

**Comment by SamAlphaTheEpik** [comment]
> > > since your build target is windows x64, you should put "lime test windows" (correct me if im wrong)
> > 
> > 
> > So it worked. But i also had this error which isn't from the situation of this issue. ![Screenshot 2024-11-23 174053](https://private-user-images.githubusercontent.com/182260232/389212542-89b8981c-f7ef-4bea-93b4-3a7d70fc5072.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODA3MTAsIm5iZiI6MTczMjM4MDQxMCwicGF0aCI6Ii8xODIyNjAyMzIvMzg5MjEyNTQyLTg5Yjg5ODFjLWY3ZWYtNGJlYS05M2I0LTNhN2Q3MGZjNTA3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxNjQ2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjA3NzZlMTJmZjFiMTAxZDRiNzQ2M2EyZjBhYTgzODYxZGZjN2Q4ZGU5MWY0MTgzM2YyMzJiMzkwYWE5NjUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KAKJkcu3AucW9g8K9_DzH1HmE69yzEmFs52Gj7W9aGc)
> 
> Nevermind i just had to do the windows setup again. I guess everything it's fine. How do i close this argument now.
