### ISSUE TITLE
How to change the menu layout in 1.0-prerelease

### ISSUE THREAD

**Issue by Porcupine2009** [ShadowMario/FNF-PsychEngine#15962]
### Describe your problem here.

Hi there, I'm working on a mod with my brother and we're trying to move all of the main menu buttons to the left of the screen. When we tried, the options clipped off of the screen. We couldn't find the x values, and all tutorials we tried to find were outdated.

We are modding on 1.0-prerelease, mostly because a lot of scripts broke on the current (likely due to a lot of functions and values being removed or changed).
Any help is appreciated!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, added a shit ton of assets and scripts in the assest folder (duh)

**Comment by Shadow06735** [comment]
put this below the item.y += in the for (num) thingy:

```haxe
item.x = (FlxG.width / 2) + -550;
```

**Comment by Porcupine2009** [comment]
This worked, thanks :)

**Comment by Shadow06735** [comment]
> This worked, thanks :)

np
