### ISSUE TITLE
bro why this is happened

### ISSUE THREAD

**Issue by bysisigma45** [ShadowMario/FNF-PsychEngine#15967]
### Describe your problem here.

i compile 0.7.3 version and this error comed
Warning: Ignoring unknown fps=""
D:/MY GAMES/FNF/PHYCH ENGUNE/0.7.3(compiled)/compiled results/FNF-PsychEngine-0.7.3/.haxelib/SScript/21,0,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Shadow06735** [comment]
Try this: https://github.com/CobaltBar/SScript-Archive

**Comment by bysisigma45** [comment]
it works, but the character editor is full with black

**Comment by Shadow06735** [comment]
> it works, but the character editor is full with black

Try https://github.com/ShadowMario/FNF-PsychEngine/pull/14495

**Comment by bysisigma45** [comment]
source/states/editors/CharacterEditorState.hx:1069: characters 27-52 : Type not found : ConfirmationPopupSubstate

**Comment by bysisigma45** [comment]
nvm. I fix it, Thanks!
