### ISSUE TITLE
Help with Compling Psych Engine 1.0

### ISSUE THREAD

**Issue by HiverUwU** [ShadowMario/FNF-PsychEngine#15963]
### Describe your problem here.

I tried to complie the game, and I would get this.
`C:\Users\Hiver\Downloads\FNF-PsychEngine-1.0\FNF-PsychEngine-1.0>lime test windows`
`C:/HaxeToolkit/haxe/lib/flxanimate/git/flxanimate/animate/FlxElement.hx:156: characters 39-40 : Unexpected ?`

I used the flxanimate version listed in the 1.0 Psych Engine Library versions
`"haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate 768740a56b26aa0c072720e0d1236b94afe68e3e"`

I tried to use other versions and I would get this (I don't know why I did this)
`"source/backend/ui/PsychUIInputText.hx:224: characters 3-9 : Expected }"`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No changes were made

**Comment by CrusherNotDrip** [comment]
try updating haxe

**Comment by HiverUwU** [comment]
I realised that I was on HAXE 4.2.5 and I installed HAXE 4.3.2, and now I get this
![image](https://github.com/user-attachments/assets/0f71ffb0-ce0f-4921-a48d-104bb974248f)`
I tried to reinstall HAXE and download all of the haxelibs again and I still get that.

**Comment by HiverUwU** [comment]
nevermind I put the all files from neko into HAXE folder and somehow that worked
