### ISSUE TITLE
Engine

### ISSUE THREAD

**Issue by RareBeeCodez** [ShadowMario/FNF-PsychEngine#1597]
### What is your question?

Is it possible to make an fnf mod on psych engine without compiling the code?

**Comment by DaBanana64** [comment]
Literally the whole main point of this Engine.

**Comment by CrusherMods** [comment]
Mods folder go look at it

**Comment by Doritojoey** [comment]
> ### What is your question?
> 
> Is it possible to make an fnf mod on psych engine without compiling the code?

Literally how is your username RareBeeCodez if you can't see the name of a fucking folder

**Comment by DEV-idiotXD** [comment]
> > ### What is your question?
> > Is it possible to make an fnf mod on psych engine without compiling the code?
> 
> Literally how is your username RareBeeCodez if you can't see the name of a fucking folder

#LMAO

**Comment by ShadowMario** [comment]
Ouch the roasts lmao
