### ISSUE TITLE
DOUBLE TEXT OF THE SONG

### ISSUE THREAD

**Issue by JuanSebas1247** [ShadowMario/FNF-PsychEngine#15971]
### Describe your problem here.

Technically, that's how I do it, no need to explain. 

Is it possible to do this in Psych Engine 1.0?

And does it really work?
![Screenshot_20241126-200531](https://github.com/user-attachments/assets/71ca92c5-2750-4416-85cd-ecd4fd130756)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JuanSebas1247** [comment]
If anyone has already asked and was told, let me know so I can look.

**Comment by AnotherPlayer8** [comment]
`local timeElapsed = 0 --left side of the text
local totalTime = 0 --right side of the text

function minutesAndSeconds(number)
    local minutes = math.floor(number / 60) --converts the seconds to minutes
    local seconds = number % 60 --amount of seconds looping from 0 to 59
    if seconds < 10 then
        fixedSeconds = 0 .. seconds --adds an extra 0 to always have two digits
    else
        fixedSeconds = seconds
    end
    return  minutes .. ":" .. fixedSeconds --displays the time as 0:00
end

function onUpdatePost()
    timeElapsed = math.floor(getSongPosition() / 1000) --time elapsed in seconds
    totalTime = math.floor(songLength / 1000) --total song time in seconds
    setProperty("timeTxt.text", minutesAndSeconds(timeElapsed) .. " - " .. minutesAndSeconds(totalTime)) --that's it! :)
end`
this is the best thing i could come up with, should work perfectly fine

**Comment by JuanSebas1247** [comment]
Yes it works, thanksCargando lv_0_20241213124733.mp4 …
