### ISSUE TITLE
im trying to compile 1.0 but keep getting an error

### ISSUE THREAD

**Issue by NiftyAC** [ShadowMario/FNF-PsychEngine#15974]
### Describe your problem here.

hxcpp/debug/jsonrpc/Server.hx:86: Debug Server Started:
hxcpp/debug/jsonrpc/Server.hx:592: Failed to connect to vsc debugger server at 127.0.0.1:6972
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 26
Called from ApplicationMain::create ApplicationMain.hx line 137
Called from openfl.display.Application::exec openfl/display/Application.hx line 130
Called from lime.app.Application::exec lime/app/Application.hx line 150
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 146
Called from lime._internal.backend.native.NativeApplication::handleApplicationEvent lime/_internal/backend/native/NativeApplication.hx line 175
Called from lime.app._Event_Int_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from lime.system.ThreadPool::__update lime/system/ThreadPool.hx line 203
Called from lime.app._Event_Dynamic_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from lime._internal.backend.native.NativeHTTPRequest::localThreadPool_onError lime/_internal/backend/native/NativeHTTPRequest.hx line 468
Called from lime.app.Promise_haxe_io_Bytes::error lime/app/Promise.hx line 149
Called from lime.net._HTTPRequest_Bytes::load lime/net/HTTPRequest.hx line 112
Called from lime.app.Promise::error lime/app/Promise.hx line 149
Called from lime.app.Promise::error lime/app/Promise.hx line 149
Called from lime.utils.Assets::loadLibrary lime/utils/Assets.hx line 480
Called from lime.app.Promise_lime_utils_AssetLibrary::error lime/app/Promise.hx line 149
Called from lime.utils.Preloader::updateProgress lime/utils/Preloader.hx line 293
Called from lime.utils.Log::error lime/utils/Log.hx line 37
Critical Error: Uncatchable Throw: [lime.utils.Preloader] ERROR: There is no asset library with an ID of "default"

I get that every single time I try to build the game and I don't know what to do now. I've tried to download a new copy of the source code too and still nothing.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Shadow06735** [comment]
did you download all the required libraries?

**Comment by NiftyAC** [comment]
> did you download all the required libraries?

I used the windows.bat and I think that installs them all.  would it be easier to compile prerelease? both will work for my mod I think.

**Comment by Shadow06735** [comment]
try this: https://github.com/CobaltBar/SScript-Archive

**Comment by NiftyAC** [comment]
> try this: https://github.com/CobaltBar/SScript-Archive

i did it and I'm getting this now 

\Desktop\Folder Games\FNF STUFF\engines\fnf\Psych Engine\FNF-PsychEngine-1.0-prerelease\FNF-PsychEngine-1.0-prerelease\export\debug\windows\obj\include\backend/DiscordClient.h(11): fatal error C1083: Cannot open include file: 'discord_rpc.h': No such file or directory

I did cut it off so it doesn't say my name.
