### ISSUE TITLE
Credit issues stop from compiling

### ISSUE THREAD

**Issue by TeenageProdigy** [ShadowMario/FNF-PsychEngine#15977]
### Describe your bug here.

Despite using the exact formula (literally copy and pasted) to write my names into the credits using CreditsStates, when compiling I continue getting this same message over and over no matter what I do. It should work fine but it won't, any ideas?

![image](https://github.com/user-attachments/assets/3cd158b5-1e26-4e43-a304-5f743737d278)

### Command Prompt/Terminal logs (if existing)

```bash
BUILDING GAME
 ERROR  source/states/CreditsState.hx:42: characters 19-20

 42 |    ["Socko Gaming",  "sockogaming",  "Lead concept and programmer of Suburban night funkin",  "https://linktr.ee/TeenageProdigy", "FDA4CE"],
    |                                       ^
    | Expected ]


done.
Press any key to continue . . .
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited CreditsState.hx to put my name in the credits

**Comment by CrusherNotDrip** [comment]
ur missing some `,`'s
