### ISSUE TITLE
quick title screen help

### ISSUE THREAD

**Issue by NiftyAC** [ShadowMario/FNF-PsychEngine#15988]
### Describe your problem here.

i just wanna remove gfDanceTitle and make the fnf logo be directly in the middle of the screen on the title screen. I'm making a mo that does have any original fnf characters in it and it doesn't make much sense for her to be there. i don't think its a hard fix but I've tried doing it in titlestate.hx but I'm being really cautious as to not break anything so I probably haven't done it right.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes but only the things that wouldn't mess with the title screen.

**Comment by Shadow06735** [comment]
in titlestate.hx, go to the lines that handle adding the logo, and add the screenCenter line u see in the code:
```haxe
logoBl = new FlxSprite(titleJSON.titlex, titleJSON.titley);
logoBl.frames = Paths.getSparrowAtlas('logoBumpin');
logoBl.antialiasing = ClientPrefs.data.antialiasing;
logoBl.screenCenter();
logoBl.animation.addByPrefix('bump', 'logo bumpin', 24, false);
logoBl.animation.play('bump');
logoBl.updateHitbox();
``` 

for removing the gfdance, go to the line that adds the gfdance and cancel it out like this:
```haxe
// add(gfDance);
```

**Comment by NiftyAC** [comment]
> in titlestate.hx, go to the lines that handle adding the logo, and add the screenCenter line u see in the code:
> 
> ```hx
> logoBl = new FlxSprite(titleJSON.titlex, titleJSON.titley);
> logoBl.frames = Paths.getSparrowAtlas('logoBumpin');
> logoBl.antialiasing = ClientPrefs.data.antialiasing;
> logoBl.screenCenter();
> logoBl.animation.addByPrefix('bump', 'logo bumpin', 24, false);
> logoBl.animation.play('bump');
> logoBl.updateHitbox();
> ```
> 
> for removing the gfdance, go to the line that adds the gfdance and cancel it out like this:
> 
> ```hx
> // add(gfDance);
> ```

thank you very much. i was using ctrl + f and going through keywords so I didn't see that.

**Comment by Shadow06735** [comment]
> > in titlestate.hx, go to the lines that handle adding the logo, and add the screenCenter line u see in the code:
> > ```hx
> > logoBl = new FlxSprite(titleJSON.titlex, titleJSON.titley);
> > logoBl.frames = Paths.getSparrowAtlas('logoBumpin');
> > logoBl.antialiasing = ClientPrefs.data.antialiasing;
> > logoBl.screenCenter();
> > logoBl.animation.addByPrefix('bump', 'logo bumpin', 24, false);
> > logoBl.animation.play('bump');
> > logoBl.updateHitbox();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > for removing the gfdance, go to the line that adds the gfdance and cancel it out like this:
> > ```hx
> > // add(gfDance);
> > ```
> 
> thank you very much. i was using ctrl + f and going through keywords so I didn't see that.

np
