### ISSUE TITLE
Is there a way to change the diffuculty images position?

### ISSUE THREAD

**Issue by SamAlphaTheEpik** [ShadowMario/FNF-PsychEngine#15983]
### What is your question?

![Screenshot 2024-11-29 194000](https://github.com/user-attachments/assets/d590b440-b5be-4adf-aab5-8018b3a33d2a)
let me know please.

**Comment by Shadow06735** [comment]
you most likely have to adjust the positions with source. also why tf is your difficulty image so big

**Comment by SamAlphaTheEpik** [comment]
> you most likely have to adjust the positions with source. also why tf is your difficulty image so big

so i have to make the images smaller?

**Comment by Shadow06735** [comment]
> > you most likely have to adjust the positions with source. also why tf is your difficulty image so big
> 
> so i have to make the images smaller?

most likely

**Comment by SamAlphaTheEpik** [comment]
> > > you most likely have to adjust the positions with source. also why tf is your difficulty image so big
> > 
> > 
> > so i have to make the images smaller?
> 
> most likely

I tried change the images size to 150x 150x but it looks so bad.
It's supposed to be like Gapple.
![Screenshot 2024-11-30 093429](https://github.com/user-attachments/assets/d45367ca-01e0-4024-9e2c-6cc0650a8d44)

**Comment by Shadow06735** [comment]
> > > > you most likely have to adjust the positions with source. also why tf is your difficulty image so big
> > > 
> > > 
> > > so i have to make the images smaller?
> > 
> > 
> > most likely
> 
> I tried change the images size to 150x 150x but it looks so bad. It's supposed to be like Gapple. ![Screenshot 2024-11-30 093429](https://private-user-images.githubusercontent.com/182260232/391223418-d45367ca-01e0-4024-9e2c-6cc0650a8d44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzQ2NjIsIm5iZiI6MTczMjk3NDM2MiwicGF0aCI6Ii8xODIyNjAyMzIvMzkxMjIzNDE4LWQ0NTM2N2NhLTAxZTAtNDAyNC05ZTJjLTZjYzA2NTBhOGQ0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxMzQ2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWQ2NzIzNWFhNDI2OGI4NTNiZDk5M2VkMGFkZDlmNGJlNjI0Nzg2YjAxN2NhOTFlMmUzMzkxZDAxMDk2OTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Hg0llJjmyLwQLFyWaJnmBj0jCUvwWBdhXB3kR7yStwk)

yeah but psych engine's default difficulty position was made for like the small images u currently see. making big ones would require you to modify the source code

**Comment by SamAlphaTheEpik** [comment]
> > > > > you most likely have to adjust the positions with source. also why tf is your difficulty image so big
> > > > 
> > > > 
> > > > so i have to make the images smaller?
> > > 
> > > 
> > > most likely
> > 
> > 
> > I tried change the images size to 150x 150x but it looks so bad. It's supposed to be like Gapple. ![Screenshot 2024-11-30 093429](https://private-user-images.githubusercontent.com/182260232/391223418-d45367ca-01e0-4024-9e2c-6cc0650a8d44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzQ2NjIsIm5iZiI6MTczMjk3NDM2MiwicGF0aCI6Ii8xODIyNjAyMzIvMzkxMjIzNDE4LWQ0NTM2N2NhLTAxZTAtNDAyNC05ZTJjLTZjYzA2NTBhOGQ0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxMzQ2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWQ2NzIzNWFhNDI2OGI4NTNiZDk5M2VkMGFkZDlmNGJlNjI0Nzg2YjAxN2NhOTFlMmUzMzkxZDAxMDk2OTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Hg0llJjmyLwQLFyWaJnmBj0jCUvwWBdhXB3kR7yStwk)
> 
> yeah but psych engine's default difficulty position was made for like the small images u currently see. making big ones would require you to modify the source code

My mod is made with Pysch Engine's source code.

**Comment by SamAlphaTheEpik** [comment]
> > > > > you most likely have to adjust the positions with source. also why tf is your difficulty image so big
> > > > 
> > > > 
> > > > so i have to make the images smaller?
> > > 
> > > 
> > > most likely
> > 
> > 
> > I tried change the images size to 150x 150x but it looks so bad. It's supposed to be like Gapple. ![Screenshot 2024-11-30 093429](https://private-user-images.githubusercontent.com/182260232/391223418-d45367ca-01e0-4024-9e2c-6cc0650a8d44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzQ2NjIsIm5iZiI6MTczMjk3NDM2MiwicGF0aCI6Ii8xODIyNjAyMzIvMzkxMjIzNDE4LWQ0NTM2N2NhLTAxZTAtNDAyNC05ZTJjLTZjYzA2NTBhOGQ0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxMzQ2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWQ2NzIzNWFhNDI2OGI4NTNiZDk5M2VkMGFkZDlmNGJlNjI0Nzg2YjAxN2NhOTFlMmUzMzkxZDAxMDk2OTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Hg0llJjmyLwQLFyWaJnmBj0jCUvwWBdhXB3kR7yStwk)
> 
> yeah but psych engine's default difficulty position was made for like the small images u currently see. making big ones would require you to modify the source code

Oh ok

**Comment by SamAlphaTheEpik** [comment]
> > > > > > you most likely have to adjust the positions with source. also why tf is your difficulty image so big
> > > > > 
> > > > > 
> > > > > so i have to make the images smaller?
> > > > 
> > > > 
> > > > most likely
> > > 
> > > 
> > > I tried change the images size to 150x 150x but it looks so bad. It's supposed to be like Gapple. ![Screenshot 2024-11-30 093429](https://private-user-images.githubusercontent.com/182260232/391223418-d45367ca-01e0-4024-9e2c-6cc0650a8d44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzQ2NjIsIm5iZiI6MTczMjk3NDM2MiwicGF0aCI6Ii8xODIyNjAyMzIvMzkxMjIzNDE4LWQ0NTM2N2NhLTAxZTAtNDAyNC05ZTJjLTZjYzA2NTBhOGQ0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxMzQ2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWQ2NzIzNWFhNDI2OGI4NTNiZDk5M2VkMGFkZDlmNGJlNjI0Nzg2YjAxN2NhOTFlMmUzMzkxZDAxMDk2OTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Hg0llJjmyLwQLFyWaJnmBj0jCUvwWBdhXB3kR7yStwk)
> > 
> > 
> > yeah but psych engine's default difficulty position was made for like the small images u currently see. making big ones would require you to modify the source code
> 
> Oh ok but which files i have to edit?

nevermind it's difficulty.hx

**Comment by Shadow06735** [comment]
> > > > > > > you most likely have to adjust the positions with source. also why tf is your difficulty image so big
> > > > > > 
> > > > > > 
> > > > > > so i have to make the images smaller?
> > > > > 
> > > > > 
> > > > > most likely
> > > > 
> > > > 
> > > > I tried change the images size to 150x 150x but it looks so bad. It's supposed to be like Gapple. ![Screenshot 2024-11-30 093429](https://private-user-images.githubusercontent.com/182260232/391223418-d45367ca-01e0-4024-9e2c-6cc0650a8d44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzQ2NjIsIm5iZiI6MTczMjk3NDM2MiwicGF0aCI6Ii8xODIyNjAyMzIvMzkxMjIzNDE4LWQ0NTM2N2NhLTAxZTAtNDAyNC05ZTJjLTZjYzA2NTBhOGQ0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxMzQ2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWQ2NzIzNWFhNDI2OGI4NTNiZDk5M2VkMGFkZDlmNGJlNjI0Nzg2YjAxN2NhOTFlMmUzMzkxZDAxMDk2OTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Hg0llJjmyLwQLFyWaJnmBj0jCUvwWBdhXB3kR7yStwk)
> > > 
> > > 
> > > yeah but psych engine's default difficulty position was made for like the small images u currently see. making big ones would require you to modify the source code
> > 
> > 
> > Oh ok but which files i have to edit?
> 
> nevermind it's difficulty.hx i think

its in storymenustate.hx

**Comment by SamAlphaTheEpik** [comment]
> > > > > > > > you most likely have to adjust the positions with source. also why tf is your difficulty image so big
> > > > > > > 
> > > > > > > 
> > > > > > > so i have to make the images smaller?
> > > > > > 
> > > > > > 
> > > > > > most likely
> > > > > 
> > > > > 
> > > > > I tried change the images size to 150x 150x but it looks so bad. It's supposed to be like Gapple. ![Screenshot 2024-11-30 093429](https://private-user-images.githubusercontent.com/182260232/391223418-d45367ca-01e0-4024-9e2c-6cc0650a8d44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzQ2NjIsIm5iZiI6MTczMjk3NDM2MiwicGF0aCI6Ii8xODIyNjAyMzIvMzkxMjIzNDE4LWQ0NTM2N2NhLTAxZTAtNDAyNC05ZTJjLTZjYzA2NTBhOGQ0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxMzQ2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWQ2NzIzNWFhNDI2OGI4NTNiZDk5M2VkMGFkZDlmNGJlNjI0Nzg2YjAxN2NhOTFlMmUzMzkxZDAxMDk2OTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Hg0llJjmyLwQLFyWaJnmBj0jCUvwWBdhXB3kR7yStwk)
> > > > 
> > > > 
> > > > yeah but psych engine's default difficulty position was made for like the small images u currently see. making big ones would require you to modify the source code
> > > 
> > > 
> > > Oh ok but which files i have to edit?
> > 
> > 
> > nevermind it's difficulty.hx i think
> 
> its in storymenustate.hx

ok thank youuuuuuuuuuuuuuuu :3

**Comment by Shadow06735** [comment]
> > > > > > > > > you most likely have to adjust the positions with source. also why tf is your difficulty image so big
> > > > > > > > 
> > > > > > > > 
> > > > > > > > so i have to make the images smaller?
> > > > > > > 
> > > > > > > 
> > > > > > > most likely
> > > > > > 
> > > > > > 
> > > > > > I tried change the images size to 150x 150x but it looks so bad. It's supposed to be like Gapple. ![Screenshot 2024-11-30 093429](https://private-user-images.githubusercontent.com/182260232/391223418-d45367ca-01e0-4024-9e2c-6cc0650a8d44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzQ2NjIsIm5iZiI6MTczMjk3NDM2MiwicGF0aCI6Ii8xODIyNjAyMzIvMzkxMjIzNDE4LWQ0NTM2N2NhLTAxZTAtNDAyNC05ZTJjLTZjYzA2NTBhOGQ0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxMzQ2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWQ2NzIzNWFhNDI2OGI4NTNiZDk5M2VkMGFkZDlmNGJlNjI0Nzg2YjAxN2NhOTFlMmUzMzkxZDAxMDk2OTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Hg0llJjmyLwQLFyWaJnmBj0jCUvwWBdhXB3kR7yStwk)
> > > > > 
> > > > > 
> > > > > yeah but psych engine's default difficulty position was made for like the small images u currently see. making big ones would require you to modify the source code
> > > > 
> > > > 
> > > > Oh ok but which files i have to edit?
> > > 
> > > 
> > > nevermind it's difficulty.hx i think
> > 
> > 
> > its in storymenustate.hx
> 
> ok thank youuuuuuuuuuuuuuuu :3

np, i think this can be closed now

**Comment by SamAlphaTheEpik** [comment]
> > > > > > > > > > you most likely have to adjust the positions with source. also why tf is your difficulty image so big
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > so i have to make the images smaller?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > most likely
> > > > > > > 
> > > > > > > 
> > > > > > > I tried change the images size to 150x 150x but it looks so bad. It's supposed to be like Gapple. ![Screenshot 2024-11-30 093429](https://private-user-images.githubusercontent.com/182260232/391223418-d45367ca-01e0-4024-9e2c-6cc0650a8d44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzQ2NjIsIm5iZiI6MTczMjk3NDM2MiwicGF0aCI6Ii8xODIyNjAyMzIvMzkxMjIzNDE4LWQ0NTM2N2NhLTAxZTAtNDAyNC05ZTJjLTZjYzA2NTBhOGQ0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxMzQ2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWQ2NzIzNWFhNDI2OGI4NTNiZDk5M2VkMGFkZDlmNGJlNjI0Nzg2YjAxN2NhOTFlMmUzMzkxZDAxMDk2OTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Hg0llJjmyLwQLFyWaJnmBj0jCUvwWBdhXB3kR7yStwk)
> > > > > > 
> > > > > > 
> > > > > > yeah but psych engine's default difficulty position was made for like the small images u currently see. making big ones would require you to modify the source code
> > > > > 
> > > > > 
> > > > > Oh ok but which files i have to edit?
> > > > 
> > > > 
> > > > nevermind it's difficulty.hx i think
> > > 
> > > 
> > > its in storymenustate.hx
> > 
> > 
> > ok thank youuuuuuuuuuuuuuuu :3
> 
> np, i think this can be closed now
