### ISSUE TITLE
Animated Notes

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#1599]
### What is your question?

Is it possible to make some animated (custom) notes?

### hi

**Comment by Adrian47roblox** [comment]
yes

**Comment by SrtHero278** [comment]
> yes

The xml can make frames.
```
red0000
red0001
```

**Comment by acap09** [comment]
> > yes
> 
> The xml can make frames.
> 
> ```
> red0000
> red0001
> ```

okay
