### ISSUE TITLE
I can make a build of mode only in source?

### ISSUE THREAD

**Issue by parallelogradus** [ShadowMario/FNF-PsychEngine#15991]
### Describe your problem here.

Should lua scripts work in source? They worked, but usually in source people use only .hx. 
Also i have a problem with sprites. In lua its shows just fine, but in source in very other way.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Shadow06735** [comment]
im pretty sure lua scripts only like change certain things of the game

haxe files change the entirety of a certain state or thing

**Comment by parallelogradus** [comment]
> im pretty sure lua scripts only like change certain things of the game
> 
> haxe files change the entirety of a certain state or thing

oh okay. but could i put together a mod made through lua for others?

**Comment by Shadow06735** [comment]
> > im pretty sure lua scripts only like change certain things of the game
> > haxe files change the entirety of a certain state or thing
> 
> oh okay. but could i put together a mod made through lua for others?

if your talking about aking a mod, then u can use lua. however if you really want to change stuff in psych engines build then u need haxe

**Comment by Sox-Git** [comment]
Friday Night Funkin' is a game built off Haxe. Lua should obviously not work in this case. If you would like to build a mod off lua Funkin Love iirc uses just lua.
