### ISSUE TITLE
custom menuBG for all four of them

### ISSUE THREAD

**Issue by NiftyAC** [ShadowMario/FNF-PsychEngine#15992]
### Describe your problem here.

i changed the menuBG file for the main menu screen with story mode and freeplay and stuff but when I enter the freeplay menu after replacing the menuBGBlue file it stays as the original menuBGBlue even after recompiling the game. if its possible to make it use a different file name then that would be nice but I just need help getting it changed.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i edited mostly everything but nothing about the backgrounds.

**Comment by Shadow06735** [comment]
go to this line here and change the image to your image file name:
```haxe
bg = new FlxSprite().loadGraphic(Paths.image('your_image_name_here'));
bg.antialiasing = ClientPrefs.data.antialiasing;
add(bg);
bg.screenCenter();
```

**Comment by NiftyAC** [comment]
> go to this line here and change the image to your image file name:
> 
> ```haxe
> 
> bg = new FlxSprite().loadGraphic(Paths.image('your_image_name_here'));
> 
> bg.antialiasing = ClientPrefs.data.antialiasing;
> 
> add(bg);
> 
> bg.screenCenter();
> 
> ``` 

Do I do that in freeplaystate.hx? If so it's still using menuBGBlue for some reason.

**Comment by NiftyAC** [comment]
> go to this line here and change the image to your image file name:
> 
> ```haxe
> 
> bg = new FlxSprite().loadGraphic(Paths.image('your_image_name_here'));
> 
> bg.antialiasing = ClientPrefs.data.antialiasing;
> 
> add(bg);
> 
> bg.screenCenter();
> 
> ``` 

I got it thank you. Disregard what I said a minute ago because I'm dumb and used the wrong line.

**Comment by Shadow06735** [comment]
> > go to this line here and change the image to your image file name:
> > ```hx
> > bg = new FlxSprite().loadGraphic(Paths.image('your_image_name_here'));
> > 
> > bg.antialiasing = ClientPrefs.data.antialiasing;
> > 
> > add(bg);
> > 
> > bg.screenCenter();
> > ```
> 
> I got it thank you. Disregard what I said a minute ago because I'm dumb and used the wrong line.

np
