### ISSUE TITLE
No custom characters in the in game editor work, they crash the game.

### ISSUE THREAD

**Issue by SarahDrewington** [ShadowMario/FNF-PsychEngine#160]
No custom character in the game is running on the current version of psych engine, even with all their animations, xml animation names, labels for the anims, and their name CORRECTLY added into the characterlist.txt file.

I plan to try adding one on an older version I have, screenshots below. of the game crashing when said character is loading in. (censored for a project I'm planning.)
![image](https://user-images.githubusercontent.com/84744056/134957303-6e00e21f-cd0f-44b8-99c2-7c88b925b40a.png)
![image](https://user-images.githubusercontent.com/84744056/134957551-bfec2b92-4105-4f6b-813b-09fe5e644ff8.png)

**Comment by TheMicroondas** [comment]
Maybe you are not configuring the character correctly as in the github guide, the names of the animations are correct? are you putting the .json files in the mods folder?

**Comment by SarahDrewington** [comment]
I have named them properly, maybe the use of capital letters in the json files is kinda fucking it over, I'll rename the animation labels to see if something will change.


though in the old version, the song played for a bit before crashing.

**Comment by SarahDrewington** [comment]
Nope, didn't even work on the old version, WITH me fixing the animations.


i think this is a sprite sheet problem.
