### ISSUE TITLE
i wanna remove the botplay text

### ISSUE THREAD

**Issue by NiftyAC** [ShadowMario/FNF-PsychEngine#16005]
### Describe your problem here.

How do I remove botplay text with source code I'm trying to upload a video of the mod but want it gone so it doesn't obstruct the view or anything.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i edited mostly everything.

**Comment by Shadow06735** [comment]
I think it has to do with the uigroup.add lines. check if there is smth called uigroup.add(botplaytxt) and cancel it out or remove it

**Comment by NiftyAC** [comment]
> I think it has to do with the uigroup.add lines. check if there is smth called uigroup.add(botplaytxt) and cancel it out or remove it

Sorry for the extremely late reply, my computers cpu kept overheating so I had to add better thermal paste and it's good now. That worked and everything so thank you so much.

**Comment by Shadow06735** [comment]
> > I think it has to do with the uigroup.add lines. check if there is smth called uigroup.add(botplaytxt) and cancel it out or remove it
> 
> Sorry for the extremely late reply, my computers cpu kept overheating so I had to add better thermal paste and it's good now. That worked and everything so thank you so much.

np
