### ISSUE TITLE
Attack

### ISSUE THREAD

**Issue by L0llFNF** [ShadowMario/FNF-PsychEngine#16013]
### What is your question?

I finally compiled Psych Engine's source code, and I want to add the attack UI for the opponent. Since I'm not very skilled with this (and couldn't find any tutorials or anything about it), I wanted to ask if anyone knows exactly where to put the code I’m going to make. Thanks! <3

**Comment by Shadow06735** [comment]
wdym “attack ui”?

**Comment by L0llFNF** [comment]
> wdym “attack ui”

Maybe I wrote it wrong lol.
Take as an example the attack mechanic in the QT mod (the saws) or the Graffiti Groovin one in the "Freakpunk" song.
I thought it'd be nice to add that to my project too and wanted to know some things.
(also sorry, english isn't my first language so tell me if something isn't correct and I'll explain again)

**Comment by Shadow06735** [comment]
> > wdym “attack ui”
> 
> Maybe I wrote it wrong lol. Take as an example the attack mechanic in the QT mod (the saws) or the Graffiti Groovin one in the "Freakpunk" song. I thought it'd be nice to add that to my project too and wanted to know some things. (also sorry, english isn't my first language so tell me if something isn't correct and I'll explain again)

u can do this without source too. search up dodge mechanics and you'll get plenty of similar ones

**Comment by L0llFNF** [comment]
> > > wdym “attack ui”
> > 
> > 
> > Maybe I wrote it wrong lol. Take as an example the attack mechanic in the QT mod (the saws) or the Graffiti Groovin one in the "Freakpunk" song. I thought it'd be nice to add that to my project too and wanted to know some things. (also sorry, english isn't my first language so tell me if something isn't correct and I'll explain again)
> 
> u can do this without source too. search up dodge mechanics and you'll get plenty of similar ones

I tried but I haven't found anything yet. I'll keep searching and I'll leave this issue open for now.
If you have something to recommend me you can post it here if you want
thanks a lot :D

**Comment by Shadow06735** [comment]
> > > > wdym “attack ui”
> > > 
> > > 
> > > Maybe I wrote it wrong lol. Take as an example the attack mechanic in the QT mod (the saws) or the Graffiti Groovin one in the "Freakpunk" song. I thought it'd be nice to add that to my project too and wanted to know some things. (also sorry, english isn't my first language so tell me if something isn't correct and I'll explain again)
> > 
> > 
> > u can do this without source too. search up dodge mechanics and you'll get plenty of similar ones
> 
> I tried but I haven't found anything yet. I'll keep searching and I'll leave this issue open for now. If you have something to recommend me you can post it here if you want thanks a lot :D

i forgot which one i personally used before, but i think its this:

https://gamebanana.com/tools/11543

**Comment by L0llFNF** [comment]
> > > > > wdym “attack ui”
> > > > 
> > > > 
> > > > Maybe I wrote it wrong lol. Take as an example the attack mechanic in the QT mod (the saws) or the Graffiti Groovin one in the "Freakpunk" song. I thought it'd be nice to add that to my project too and wanted to know some things. (also sorry, english isn't my first language so tell me if something isn't correct and I'll explain again)
> > > 
> > > 
> > > u can do this without source too. search up dodge mechanics and you'll get plenty of similar ones
> > 
> > 
> > I tried but I haven't found anything yet. I'll keep searching and I'll leave this issue open for now. If you have something to recommend me you can post it here if you want thanks a lot :D
> 
> i forgot which one i personally used before, but i think its this:
> 
> https://gamebanana.com/tools/11543

I just checked your link and that was exactly what I was looking for! Thank you so much :DDDD

**Comment by Shadow06735** [comment]
> > > > > > wdym “attack ui”
> > > > > 
> > > > > 
> > > > > Maybe I wrote it wrong lol. Take as an example the attack mechanic in the QT mod (the saws) or the Graffiti Groovin one in the "Freakpunk" song. I thought it'd be nice to add that to my project too and wanted to know some things. (also sorry, english isn't my first language so tell me if something isn't correct and I'll explain again)
> > > > 
> > > > 
> > > > u can do this without source too. search up dodge mechanics and you'll get plenty of similar ones
> > > 
> > > 
> > > I tried but I haven't found anything yet. I'll keep searching and I'll leave this issue open for now. If you have something to recommend me you can post it here if you want thanks a lot :D
> > 
> > 
> > i forgot which one i personally used before, but i think its this:
> > https://gamebanana.com/tools/11543
> 
> I just checked your link and that was exactly what I was looking for! Thank you so much :DDDD

np!
