### ISSUE TITLE
How to refer to certain base-game objects (ui and stuff) in v0.7.3?

### ISSUE THREAD

**Issue by Slimquickhunt** [ShadowMario/FNF-PsychEngine#16025]
### Describe your problem here.

I'm using v0.7.3, I think the title explains it pretty well? Anyway I have no idea how to refer to like a thousand things (UI stuff ect.) things in code is there like a list somewhere? I'm mostly needing this so I can turn off the note hit text that appears when you hit a note. (I have extensively googled this, and I am not finding anything.)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Shiho-cmd** [comment]
the name of that text is "comboGroup" to make them disappear just use
setProperty("comboGroup.visible", false)

and also idk if there's a list of names to that but here the ui elements names i know:
timeBar, timeTxt, healthBar, iconP1, iconP2, scoreTxt, botplayTxt, comboGroup, grpNoteSplashes, playerStrums, opponentStrums, unspawnNotes, notes (you have to use setPropertyFromGroup to edit the things related to notes btw)

**Comment by Slimquickhunt** [comment]
> the name of that text is "comboGroup" to make them disappear just use setProperty("comboGroup.visible", false)
> 
> and also idk if there's a list of names to that but here the ui elements names i know: timeBar, timeTxt, healthBar, iconP1, iconP2, scoreTxt, botplayTxt, comboGroup, grpNoteSplashes, playerStrums, opponentStrums, unspawnNotes, notes (you have to use setPropertyFromGroup to edit the things related to notes btw)

thanks vro.
