### ISSUE TITLE
IMAGES NOT APPEARING

### ISSUE THREAD

**Issue by RoubertY** [ShadowMario/FNF-PsychEngine#1602]
### Describe your bug here.

so umm, a friend of mine whats using psych engine then it results that the images wont appear on the game, neither in the editor
they need to hotfix that

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no nothing in it

**Comment by DaBanana64** [comment]
What image?

**Comment by NotEpik** [comment]
yea what image? stage image?

**Comment by ShadowMario** [comment]
Need more information.

**Comment by RoubertY** [comment]
Like the characters, they dont appear, theyre just like... gone

**Comment by RoubertY** [comment]
he tried everything, re-extracting, changing the things in the json characters but nothing worked

**Comment by NotEpik** [comment]
like in the tutorial or no

**Comment by NotEpik** [comment]
what
