### ISSUE TITLE
Using Custom Spirit Character crashes when loaded

### ISSUE THREAD

**Issue by RiloTheFox** [ShadowMario/FNF-PsychEngine#1603]
### Describe your bug here.

I was adding [Gariwald](https://fridaynightfunking.fandom.com/wiki/SiIvaGunner_Rips#Gariwald) from the SiIvaGunner Thorns Rip, but when I load the character into a custom song, the game crashes.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I was adding stuff into mods\

**Comment by titopops** [comment]
I'm having this bug too, it's probably because it uses a txt file instead of xml, which crashes it for some reason

**Comment by ShadowMario** [comment]
Should be fixed now
