### ISSUE TITLE
How to add cutscenes (with notes visible) to psych engine 0.73

### ISSUE THREAD

**Issue by aitherka** [ShadowMario/FNF-PsychEngine#16045]
### Describe your problem here.

as the title said, i need help making a cutscene that works with notes visible because all other stuff i tried makes it invisible, so can anyone help me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Average-FNF-Modder** [comment]
What is your regular process of playing a cutscene? That would be useful to know how to help you.

**Comment by aitherka** [comment]
> What is your regular process of playing a cutscene? That would be useful to know how to help you.

i used a custom event, the lua file had this 

function onEvent(name, value1, value2)
     if name == 'playVideo' then
          startVideo(value1)
          setProperty('inCutscene', false);
     end
     return Function_Continue
end

i need a way that shows the notes with it, but i can't find it at all

**Comment by aitherka** [comment]
any idea about it?

**Comment by Average-FNF-Modder** [comment]
First order of business, trying using `setObjectOrder(VIDEO NAME, ORDER)` with your video file after it's been made to put it behind things. I don't know if this will work, but it's worth a shot. Question, does your script pause the song it's playing?- or does it keep going in the background.

If that doesn't work, trying using `setObjectCamera(VIDEO NAME, CAMERA)` to set it's game to "camGame" which is inherently below the UI. If none of these work, check back to me.

**Comment by aitherka** [comment]
first of all where do i put the setobjectorder stuff, and second of all when i pause the song the cutscene does not pause with it

**Comment by Average-FNF-Modder** [comment]
> first of all where do i put the setobjectorder stuff, and second of all when i pause the song the cutscene does not pause with it

I think you could use it directly the line down from `startVideo()`? I'm a little iffy on this, but give it a shot. And I wasn't asking if *you* pausing the song did anything, I was asking if the video itself playing paused the song in the background.

**Comment by aitherka** [comment]
ok i will try doing it below startvideo, also if you meant it paused the song if the cutscene started no it did not pause the song

**Comment by aitherka** [comment]
also what do i put in order? like the beat or what

**Comment by aitherka** [comment]
check one: setobjectcamera does not work, for setobjectorder i haven't tried it because idk what to put in order

**Comment by Average-FNF-Modder** [comment]
> check one: setobjectcamera does not work, for setobjectorder i haven't tried it because idk what to put in order

Try putting a really large negative number to start to put it back as far as possible, if it goes behind to much, then make the number higher up till it's where you wanted.

**Comment by aitherka** [comment]
i am back and i will test it now

**Comment by Average-FNF-Modder** [comment]
> i put this below startvideo: setObjectOrder(TRANSITION, -50000) this did not work, any more ideas?

Sorry, I largely had to go away for a while. Unfortunately, that was all I had at the time. I'll keep thinking and tell you if I think of anything. Wish I could help more!

**Comment by aitherka** [comment]
its ok, thanks for trying tho

**Comment by aitherka** [comment]
update: i found a better script that doesn't crash at all but it only supports one video

**Comment by Average-FNF-Modder** [comment]
> update: i found a better script that doesn't crash at all but it only supports one video

Pass it over? Maybe it's different enough to work.

**Comment by aitherka** [comment]
i will but its too scripts: here https://drive.google.com/drive/u/3/folders/1aY0aKnbDV8weTGehN_X08-CKZdTd-JmY

**Comment by aitherka** [comment]
> > i will but its two scripts: here https://drive.google.com/drive/u/3/folders/1aY0aKnbDV8weTGehN_X08-CKZdTd-JmY
> 
> I ain't got access to the drive folder lmao 😭

done

**Comment by Average-FNF-Modder** [comment]
> > > i will but its two scripts: here https://drive.google.com/drive/u/3/folders/1aY0aKnbDV8weTGehN_X08-CKZdTd-JmY
> > 
> > 
> > I ain't got access to the drive folder lmao 😭
> 
> done

Sorry my dude. I don't know nun about coding in haxe. I tried, but imma have to throw in the towel. Hope you find someone else who can help you!

**Comment by aitherka** [comment]
> > > > i will but its two scripts: here https://drive.google.com/drive/u/3/folders/1aY0aKnbDV8weTGehN_X08-CKZdTd-JmY
> > > 
> > > 
> > > I ain't got access to the drive folder lmao 😭
> > 
> > 
> > done
> 
> Sorry my dude. I don't know nun about coding in haxe. I tried, but imma have to throw in the towel. Hope you find someone else who can help you!

ok, bye and thanks!
