### ISSUE TITLE
Philly not working in source code

### ISSUE THREAD

**Issue by SovereignGameDev** [ShadowMario/FNF-PsychEngine#16053]
### Describe your problem here.

![Screenshot 2024-12-17 144716](https://github.com/user-attachments/assets/d58c0efe-5bf2-40ec-b9ab-38a0a2f54573)

I'm trying to use the built-in assets, but its not working.
My guess is that its not reading the week3 folder, but other than that I have no idea why it is not working.

These are the errors:
source/backend/Paths.hx:199: oh no its returning null NOOOO (assets/shared/images/philly/sky.png)
source/backend/Paths.hx:199: oh no its returning null NOOOO (assets/shared/images/philly/city.png)
source/backend/Paths.hx:199: oh no its returning null NOOOO (assets/shared/images/philly/window.png)
source/backend/Paths.hx:199: oh no its returning null NOOOO (assets/shared/images/philly/behindTrain.png)
source/backend/Paths.hx:199: oh no its returning null NOOOO (assets/shared/images/philly/train.png)
source/backend/Paths.hx:384: SOUND NOT FOUND: sounds/train_passes, PATH: null
source/backend/Paths.hx:199: oh no its returning null NOOOO (assets/shared/images/philly/street.png)
source/psychlua/FunkinLua.hx:1590: lua file loaded succesfully:mods/scripts/trailDoubleNote.lua

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I have edited MainMenuState, and StoryMenuState to have custom layouts

**Comment by SantiagoCalebe** [comment]
Most part of the errors are **Oh no it's return a NULL NOOOO** or **Thing not found**

Check if the images/sounds exist in their locations. Ex.: 

Sky = assets/shared/images/philly/
Train_Passes = sounds/

**Comment by SovereignGameDev** [comment]
I've managed to fix it already.

**Comment by SovereignGameDev** [comment]
fixed the problem
