### ISSUE TITLE
How to remove the awards/achievements in source code for 1.0

### ISSUE THREAD

**Issue by Kdiggisskvssjgsisivsizivsisv** [ShadowMario/FNF-PsychEngine#16055]
### Describe your problem here.

Since the new update the problem is that some of has changed and every time i try to remove achievements, it would say a system error in my powershell. 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by SantiagoCalebe** [comment]
What error?

**Comment by SantiagoCalebe** [comment]
MainMenuState.hx, line 34
![image](https://github.com/user-attachments/assets/93d5b2ef-aa57-4039-bc27-703af26e1058)
Remove the line, or go to Project.xml and remove the line 26
![image](https://github.com/user-attachments/assets/955e2ead-848d-4d18-a6a7-aa89517c4027)

**Comment by Kdiggisskvssjgsisivsizivsisv** [comment]
thank you

> MainMenuState.hx, line 34 ![image](https://private-user-images.githubusercontent.com/173545965/397083929-93d5b2ef-aa57-4039-bc27-703af26e1058.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NTUwMDksIm5iZiI6MTczNDU1NDcwOSwicGF0aCI6Ii8xNzM1NDU5NjUvMzk3MDgzOTI5LTkzZDViMmVmLWFhNTctNDAzOS1iYzI3LTcwM2FmMjZlMTA1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQyMDQ1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjhhMTAxMDE3ZWJkNjkwODJhMzZlZTU2OGVhMTAyYWRjY2NiOTAyYzJhYTBiODNjOTA1ZGNkMjY1MWUxMjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RC6BPfbxVaZ-Aj5OX1melNkGag-LTo34DIPg-LohR9E) Remove the line, or go to Project.xml and remove the line 26 ![image](https://private-user-images.githubusercontent.com/173545965/397084094-955e2ead-848d-4d18-a6a7-aa89517c4027.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NTUwMDksIm5iZiI6MTczNDU1NDcwOSwicGF0aCI6Ii8xNzM1NDU5NjUvMzk3MDg0MDk0LTk1NWUyZWFkLTg0OGQtNGQxOC1hNmE3LWFhODk1MTdjNDAyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQyMDQ1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjBkMDBiYWJiYjY1MjVhMDk0NzE1YjE4NGEzNzg1NGVkZWVmYWNmZmQ1MGYyYzA1MWE0OTM2MGVmNGFjODZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4K6TSJcBwJXQTv7u2IFPhtWn3PKbF-2CMXnsZv1jKko)

thanks
