### ISSUE TITLE
Where and How do i edit the menu layout in fnf 1.0

### ISSUE THREAD

**Issue by Kdiggisskvssjgsisivsizivsisv** [ShadowMario/FNF-PsychEngine#16057]
### Describe your problem here.

I want to make a new layout and change the position of storymode and freeplay but i don't know anything due to me being new

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by SantiagoCalebe** [comment]
MainMenuState.hx

**Comment by Kdiggisskvssjgsisivsizivsisv** [comment]
> MainMenuState.hx

yeah but where?
