### ISSUE TITLE
custom gf character not working

### ISSUE THREAD

**Issue by L044washere** [ShadowMario/FNF-PsychEngine#16062]
### Describe your problem here.

so i implemented a custom character, replacing gf in a few songs. the thing is, the animation for both danceLEFT and danceRIGHT is called idleAnimDance, which is repeated 2 times to make the animation indices. those are the only animations in the sprite, and it doesn't even move in a song. can someone help me?

here's the json:
`{
	"animations": [
		{
			"offsets": [0, 0],
			"indices": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
			"fps": 24,
			"anim": "danceLEFT",
			"loop": false,
			"name": "idleAnimDance"
		},
		{
			"offsets": [0, 0],
			"indices": [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
			"fps": 24,
			"anim": "danceRIGHT",
			"loop": false,
			"name": "idleAnimDance"
		},
		{
			"offsets": [1, 3],
			"indices": [],
			"fps": 24,
			"anim": "sad",
			"loop": false,
			"name": "loseCombo"
		}
	],
	"vocals_file": "",
	"no_antialiasing": false,
	"image": "characters/l044SpeakerAssets",
	"position": [300, 120],
	"healthicon": "face",
	"flip_x": false,
	"healthbar_colors": [161, 161, 161],
	"camera_position": [-150, -100],
	"sing_duration": 4,
	"scale": 1,
	"_editor_isPlayer": false
}`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

modified MainMenuState.hx, CreditsState.hx, and a couple more States that probably don't matter with the issue.

**Comment by SantiagoCalebe** [comment]
It's idle, not IdleAnimDance

**Comment by L044washere** [comment]
found the issue. the animations were named danceLEFT and danceRIGHT instead of **danceLeft** and **danceRight**, which are named like that in gf's character json. thanks for the help.
