### ISSUE TITLE
can't compile PsychEngine 0.7.3 haxe 4.2.5

### ISSUE THREAD

**Issue by Enchantedbooz** [ShadowMario/FNF-PsychEngine#16084]
### Describe your problem here.

SScript/21,0,0/src/macro/Macro.hx:10: characters 96-100 : SScript is not available, thanks to everyone for their support.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

someone help me

**Comment by Shadow06735** [comment]
https://github.com/CobaltBar/SScript-Archive

**Comment by Enchantedbooz** [comment]
do i add haxelib git Script https://github.com/CobaltBar/SScript-Archive

**Comment by Enchantedbooz** [comment]
i  got source/states/PlayState.hx:59: characters 8-19 : Type not found : tea.SScript
                                                                             source/psychlua/HScript.hx:317: characters 93-94 : Unexpected {

**Comment by Enchantedbooz** [comment]
don't work
