### ISSUE TITLE
Scripts (and song names) not taken correctly

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#1611]
### Describe your bug here.

I made a song with a charted variation. So like, "SONG A" And "SONG A VARIANT"
And there is the charting and characters different/replaced, even with it's own data folder and the charts.
But both use only 1 Audio file. "SONG A"
And so, it does get stated as "SONG A" in the oause screen in any of the songs. But my problem is, that it takes the script from the first one, as the second one does not have one.

**So, if I play "SONG A", I'll get my health drain script to work.
But, if I play "SONG A VARIANT" I'll get the health drain script as well.**

And only in the data folder of "SONG A" is a script.
Guess that it is an error because of the song name I took it from

(I made it take the same song, by editing the .json at the "Song" aspect)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Made a script.lua in two songs

**Comment by ShadowMario** [comment]
It uses the same name as the audio file that you've typed on Chart Editor.
