### ISSUE TITLE
I need help with dialouge

### ISSUE THREAD

**Issue by Tigedraglon10** [ShadowMario/FNF-PsychEngine#1615]
### Describe your problem here.

I've been looking at tutorials and i used the script.lua and still didnt work, may someone help me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

**Comment by Gui-iago** [comment]
lua doesn't work on mac with the stable build, you need to get the source code and compile it yourself, the current source code build supports Mac lua scripts

**Comment by NotEpik** [comment]
bro, you already open this question here: #1547

**Comment by Tigedraglon10** [comment]
> bro, you already open this question here: #1547

No one told me anything.

**Comment by Tigedraglon10** [comment]
> lua doesn't work on mac with the stable build, you need to get the source code and compile it yourself, the current source code build supports Mac lua scripts

Is there a tutorial cuz i cant find any

**Comment by NotEpik** [comment]
> > lua doesn't work on mac with the stable build, you need to get the source code and compile it yourself, the current source code build supports Mac lua scripts
> 
> Is there a tutorial cuz i cant find any

https://www.youtube.com/watch?v=mrT7pB9lAo8 idk if this work but I'm sure you can follow this guy

**Comment by Tigedraglon10** [comment]
> > > lua doesn't work on mac with the stable build, you need to get the source code and compile it yourself, the current source code build supports Mac lua scripts
> > 
> > 
> > Is there a tutorial cuz i cant find any
> 
> https://www.youtube.com/watch?v=mrT7pB9lAo8 idk if this work but I'm sure you can follow this guy

LOL THATS THE PERSON I JUST SAW BUT THANKS

**Comment by gaminbottomtext** [comment]
> lua doesn't work on mac with the stable build, you need to get the source code and compile it yourself, the current source code build supports Mac lua scripts

yes it does im literally programming a script rn

**Comment by Tigedraglon10** [comment]
> > lua doesn't work on mac with the stable build, you need to get the source code and compile it yourself, the current source code build supports Mac lua scripts
> 
> yes it does im literally programming a script rn

Eh it still worked lol
