### ISSUE TITLE
Story Mode Colors

### ISSUE THREAD

**Issue by Gui-iago** [ShadowMario/FNF-PsychEngine#1616]
### What feature do you want to get added on the base engine?

y'know? like freeplay except it colors the entire story mode menu? here's an example (taken from ProjectFNF)

https://user-images.githubusercontent.com/45212377/144519419-9ae91b84-7f79-4211-b6e2-3b1d47bb27d0.mp4

**Comment by tposejank** [comment]
shadow mario is gonna come and say
"No."

**Comment by DEV-idiotXD** [comment]
this is actuall very good!

**Comment by SrtHero278** [comment]
It would be simple. In fact you don't even have to modify the source code! Just modify the picture! Sure, it won't have some cool color tween but it will still look cool!

**Comment by HiroOfc** [comment]
bruh, i think this is not so interesting for shadowmario

**Comment by ShadowMario** [comment]
No.

**Comment by DEV-idiotXD** [comment]
> No.

THERES THE LINE THER EVERYONE LOOK HE SAID IT!!!
