### ISSUE TITLE
The character it doesn't load

### ISSUE THREAD

**Issue by cfunes401** [ShadowMario/FNF-PsychEngine#1617]
### Describe your problem here.

I have been trying to add my character but it usually closes or I get an error message that says: 
haxe.xml.XmlParserException: Expected node at line 2 char 2

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No response

**Comment by NotEpik** [comment]
XML error bro

**Comment by DEV-idiotXD** [comment]
didnt u put ur coding lua.... how is there a terminal log did you try making a json on ur own?

**Comment by cfunes401** [comment]
how is there a terminal log? : No it appears a message

did you try making a json on ur own?: No, i use the character editor

**Comment by NotEpik** [comment]
"No it appears a message" where is the message

**Comment by cfunes401** [comment]
![image](https://user-images.githubusercontent.com/95454919/144533882-ec3428ef-7201-4d3d-a0c1-ccfd466d2248.png)

**Comment by DEV-idiotXD** [comment]
in the xml's thing <TextureAtlas imagePath="image.png">
either image doest exist or isnt irn the right path

**Comment by cfunes401** [comment]
Sorry I was uploading the image and I did not see the new messages

**Comment by DEV-idiotXD** [comment]
> Sorry I was uploading the image and I did not see the new messages

# O K A Y

**Comment by cfunes401** [comment]
This is the entire xml:

<?xml version="1.0" encoding="utf-8"?>
<TextureAtlas imagePath="MICRO_assets.png">
	
	
	<SubTexture name="DOWN0000" x="0" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0001" x="88" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0002" x="176" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0003" x="264" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0004" x="352" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0005" x="440" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0006" x="528" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0007" x="616" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0008" x="704" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0009" x="792" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0010" x="880" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0011" x="0" y="157" width="88" height="157"/>
	<SubTexture name="DOWN0012" x="88" y="157" width="88" height="157"/>
	<SubTexture name="DOWN0013" x="176" y="157" width="88" height="157"/>
	<SubTexture name="DOWN0014" x="264" y="157" width="88" height="157"/>
	<SubTexture name="IDLE0000" x="352" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0001" x="459" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0002" x="566" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0003" x="673" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0004" x="780" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0005" x="887" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0006" x="0" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0007" x="107" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0008" x="214" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0009" x="321" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0010" x="428" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0011" x="535" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0012" x="642" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0013" x="749" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0014" x="856" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0015" x="0" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0016" x="107" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0017" x="214" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0018" x="321" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0019" x="428" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0020" x="535" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0021" x="642" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0022" x="749" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0023" x="856" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0024" x="0" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0025" x="107" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0026" x="214" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0027" x="321" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0028" x="428" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0029" x="535" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0030" x="642" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0031" x="749" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0032" x="856" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0033" x="0" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0034" x="107" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0035" x="214" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0036" x="321" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0037" x="428" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0038" x="535" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0039" x="642" y="797" width="107" height="160"/>
	<SubTexture name="LEFT0000" x="749" y="797" width="131" height="158"/>
	<SubTexture name="LEFT0001" x="880" y="797" width="131" height="158"/>
	<SubTexture name="LEFT0002" x="0" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0003" x="131" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0004" x="262" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0005" x="393" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0006" x="524" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0007" x="655" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0008" x="786" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0009" x="0" y="1115" width="131" height="158"/>
	<SubTexture name="RIGHT0000" x="131" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0001" x="255" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0002" x="379" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0003" x="503" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0004" x="627" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0005" x="751" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0006" x="875" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0007" x="0" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0008" x="124" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0009" x="248" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0010" x="372" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0011" x="496" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0012" x="620" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0013" x="744" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0014" x="868" y="1274" width="124" height="159"/>
	<SubTexture name="UP0000" x="0" y="1433" width="88" height="181"/>
	<SubTexture name="UP0001" x="88" y="1433" width="88" height="181"/>
	<SubTexture name="UP0002" x="176" y="1433" width="88" height="181"/>
	<SubTexture name="UP0003" x="264" y="1433" width="88" height="181"/>
	<SubTexture name="UP0004" x="352" y="1433" width="88" height="181"/>
	<SubTexture name="UP0005" x="440" y="1433" width="88" height="181"/>
	<SubTexture name="UP0006" x="528" y="1433" width="88" height="181"/>
	<SubTexture name="UP0007" x="616" y="1433" width="88" height="181"/>
	<SubTexture name="UP0008" x="704" y="1433" width="88" height="181"/>
	<SubTexture name="UP0009" x="792" y="1433" width="88" height="181"/>
	<SubTexture name="UP0010" x="880" y="1433" width="88" height="181"/>
	<SubTexture name="UP0011" x="0" y="1614" width="88" height="181"/>
	<SubTexture name="UP0012" x="88" y="1614" width="88" height="181"/>
	<SubTexture name="UP0013" x="176" y="1614" width="88" height="181"/>
	<SubTexture name="UP0014" x="264" y="1614" width="88" height="181"/>
</TextureAtlas>

**Comment by DEV-idiotXD** [comment]
> This is the entire xml:

# its empty.....

**Comment by cfunes401** [comment]
<?xml version="1.0" encoding="utf-8"?>
<TextureAtlas imagePath="MICRO_assets.png">
	
	
	<SubTexture name="DOWN0000" x="0" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0001" x="88" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0002" x="176" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0003" x="264" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0004" x="352" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0005" x="440" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0006" x="528" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0007" x="616" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0008" x="704" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0009" x="792" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0010" x="880" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0011" x="0" y="157" width="88" height="157"/>
	<SubTexture name="DOWN0012" x="88" y="157" width="88" height="157"/>
	<SubTexture name="DOWN0013" x="176" y="157" width="88" height="157"/>
	<SubTexture name="DOWN0014" x="264" y="157" width="88" height="157"/>
	<SubTexture name="IDLE0000" x="352" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0001" x="459" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0002" x="566" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0003" x="673" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0004" x="780" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0005" x="887" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0006" x="0" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0007" x="107" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0008" x="214" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0009" x="321" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0010" x="428" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0011" x="535" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0012" x="642" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0013" x="749" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0014" x="856" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0015" x="0" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0016" x="107" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0017" x="214" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0018" x="321" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0019" x="428" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0020" x="535" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0021" x="642" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0022" x="749" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0023" x="856" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0024" x="0" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0025" x="107" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0026" x="214" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0027" x="321" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0028" x="428" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0029" x="535" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0030" x="642" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0031" x="749" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0032" x="856" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0033" x="0" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0034" x="107" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0035" x="214" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0036" x="321" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0037" x="428" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0038" x="535" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0039" x="642" y="797" width="107" height="160"/>
	<SubTexture name="LEFT0000" x="749" y="797" width="131" height="158"/>
	<SubTexture name="LEFT0001" x="880" y="797" width="131" height="158"/>
	<SubTexture name="LEFT0002" x="0" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0003" x="131" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0004" x="262" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0005" x="393" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0006" x="524" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0007" x="655" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0008" x="786" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0009" x="0" y="1115" width="131" height="158"/>
	<SubTexture name="RIGHT0000" x="131" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0001" x="255" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0002" x="379" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0003" x="503" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0004" x="627" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0005" x="751" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0006" x="875" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0007" x="0" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0008" x="124" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0009" x="248" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0010" x="372" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0011" x="496" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0012" x="620" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0013" x="744" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0014" x="868" y="1274" width="124" height="159"/>
	<SubTexture name="UP0000" x="0" y="1433" width="88" height="181"/>
	<SubTexture name="UP0001" x="88" y="1433" width="88" height="181"/>
	<SubTexture name="UP0002" x="176" y="1433" width="88" height="181"/>
	<SubTexture name="UP0003" x="264" y="1433" width="88" height="181"/>
	<SubTexture name="UP0004" x="352" y="1433" width="88" height="181"/>
	<SubTexture name="UP0005" x="440" y="1433" width="88" height="181"/>
	<SubTexture name="UP0006" x="528" y="1433" width="88" height="181"/>
	<SubTexture name="UP0007" x="616" y="1433" width="88" height="181"/>
	<SubTexture name="UP0008" x="704" y="1433" width="88" height="181"/>
	<SubTexture name="UP0009" x="792" y="1433" width="88" height="181"/>
	<SubTexture name="UP0010" x="880" y="1433" width="88" height="181"/>
	<SubTexture name="UP0011" x="0" y="1614" width="88" height="181"/>
	<SubTexture name="UP0012" x="88" y="1614" width="88" height="181"/>
	<SubTexture name="UP0013" x="176" y="1614" width="88" height="181"/>
	<SubTexture name="UP0014" x="264" y="1614" width="88" height="181"/>
</TextureAtlas>

**Comment by NotEpik** [comment]
lol

**Comment by NotEpik** [comment]
also did it fix?

**Comment by DEV-idiotXD** [comment]
> _No description provided._

# _ XD

**Comment by cfunes401** [comment]
Sorry github does not allow me to send all the xml

**Comment by DEV-idiotXD** [comment]
> Sorry github does not allow me to send all the xml

it hide it if there is a > < around it for some reason

**Comment by DEV-idiotXD** [comment]
<>

**Comment by NotEpik** [comment]
> in the xml's thing TextureAtlas imagePath="image.png" either image doest exist or isnt irn the right path

did this thing fix the error?

**Comment by cfunes401** [comment]
?xml version="1.0" encoding="utf-8"?
TextureAtlas imagePath="MICRO_assets.png"
	
	
	<SubTexture name="DOWN0000" x="0" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0001" x="88" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0002" x="176" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0003" x="264" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0004" x="352" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0005" x="440" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0006" x="528" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0007" x="616" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0008" x="704" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0009" x="792" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0010" x="880" y="0" width="88" height="157"/>
	<SubTexture name="DOWN0011" x="0" y="157" width="88" height="157"/>
	<SubTexture name="DOWN0012" x="88" y="157" width="88" height="157"/>
	<SubTexture name="DOWN0013" x="176" y="157" width="88" height="157"/>
	<SubTexture name="DOWN0014" x="264" y="157" width="88" height="157"/>
	<SubTexture name="IDLE0000" x="352" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0001" x="459" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0002" x="566" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0003" x="673" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0004" x="780" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0005" x="887" y="157" width="107" height="160"/>
	<SubTexture name="IDLE0006" x="0" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0007" x="107" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0008" x="214" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0009" x="321" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0010" x="428" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0011" x="535" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0012" x="642" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0013" x="749" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0014" x="856" y="317" width="107" height="160"/>
	<SubTexture name="IDLE0015" x="0" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0016" x="107" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0017" x="214" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0018" x="321" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0019" x="428" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0020" x="535" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0021" x="642" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0022" x="749" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0023" x="856" y="477" width="107" height="160"/>
	<SubTexture name="IDLE0024" x="0" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0025" x="107" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0026" x="214" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0027" x="321" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0028" x="428" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0029" x="535" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0030" x="642" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0031" x="749" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0032" x="856" y="637" width="107" height="160"/>
	<SubTexture name="IDLE0033" x="0" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0034" x="107" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0035" x="214" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0036" x="321" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0037" x="428" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0038" x="535" y="797" width="107" height="160"/>
	<SubTexture name="IDLE0039" x="642" y="797" width="107" height="160"/>
	<SubTexture name="LEFT0000" x="749" y="797" width="131" height="158"/>
	<SubTexture name="LEFT0001" x="880" y="797" width="131" height="158"/>
	<SubTexture name="LEFT0002" x="0" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0003" x="131" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0004" x="262" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0005" x="393" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0006" x="524" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0007" x="655" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0008" x="786" y="957" width="131" height="158"/>
	<SubTexture name="LEFT0009" x="0" y="1115" width="131" height="158"/>
	<SubTexture name="RIGHT0000" x="131" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0001" x="255" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0002" x="379" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0003" x="503" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0004" x="627" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0005" x="751" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0006" x="875" y="1115" width="124" height="159"/>
	<SubTexture name="RIGHT0007" x="0" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0008" x="124" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0009" x="248" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0010" x="372" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0011" x="496" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0012" x="620" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0013" x="744" y="1274" width="124" height="159"/>
	<SubTexture name="RIGHT0014" x="868" y="1274" width="124" height="159"/>
	<SubTexture name="UP0000" x="0" y="1433" width="88" height="181"/>
	<SubTexture name="UP0001" x="88" y="1433" width="88" height="181"/>
	<SubTexture name="UP0002" x="176" y="1433" width="88" height="181"/>
	<SubTexture name="UP0003" x="264" y="1433" width="88" height="181"/>
	<SubTexture name="UP0004" x="352" y="1433" width="88" height="181"/>
	<SubTexture name="UP0005" x="440" y="1433" width="88" height="181"/>
	<SubTexture name="UP0006" x="528" y="1433" width="88" height="181"/>
	<SubTexture name="UP0007" x="616" y="1433" width="88" height="181"/>
	<SubTexture name="UP0008" x="704" y="1433" width="88" height="181"/>
	<SubTexture name="UP0009" x="792" y="1433" width="88" height="181"/>
	<SubTexture name="UP0010" x="880" y="1433" width="88" height="181"/>
	<SubTexture name="UP0011" x="0" y="1614" width="88" height="181"/>
	<SubTexture name="UP0012" x="88" y="1614" width="88" height="181"/>
	<SubTexture name="UP0013" x="176" y="1614" width="88" height="181"/>
	<SubTexture name="UP0014" x="264" y="1614" width="88" height="181"/>
</TextureAtlas>

**Comment by DEV-idiotXD** [comment]
> ?xml version="1.0" encoding="utf-8"? TextureAtlas imagePath="MICRO_assets.png"

just send it as a txt file and send  the image...

**Comment by NotEpik** [comment]
a lot of < >

**Comment by DEV-idiotXD** [comment]
> a lot of < >

yeee

**Comment by cfunes401** [comment]
[MICRO_assets.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7646418/MICRO_assets.txt)

**Comment by NotEpik** [comment]
but did it fix

**Comment by DEV-idiotXD** [comment]
# [MICRO_assets.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7646418/MICRO_assets.txt)

the image?

**Comment by cfunes401** [comment]
> but did it fix

No

**Comment by NotEpik** [comment]
line 2 char 2: it is "T" why is that an error

**Comment by cfunes401** [comment]
I don't know because I get the error right there

**Comment by DEV-idiotXD** [comment]
> I don't know because I get the error right there

is the xml and image in the same folder

**Comment by cfunes401** [comment]
> is the xml and image in the same folder

Yes

**Comment by DEV-idiotXD** [comment]
> > is the xml and image in the same folder
> 
> Yes
[
# this error seems to only happen to you](https://github.com/ShadowMario/FNF-PsychEngine/issues/877#issuecomment-963699129)

**Comment by cfunes401** [comment]
But Is there a way to repair it?

**Comment by DEV-idiotXD** [comment]
> But Is there a way to repair it?

show me the .json file

**Comment by cfunes401** [comment]
I dont have a json file

**Comment by DEV-idiotXD** [comment]
> I dont have a json file

# W   H   A   T

**Comment by DEV-idiotXD** [comment]
> I dont have a json file

ye need a .json file for a character.....

**Comment by DEV-idiotXD** [comment]
> I dont have a json file

# THAT MAKES SENSE NOW U DONT HEV THE .JSON FILE FOR UR CHARACTER

**Comment by NotEpik** [comment]
true

**Comment by cfunes401** [comment]
but how I create the .json file

**Comment by NotEpik** [comment]
character editor in the main menu click 7

**Comment by DEV-idiotXD** [comment]
> but how I create the .json file

friking doughnut XD

**Comment by cfunes401** [comment]
But that's where I get the error message with my character



> character editor in the main menu click 7

**Comment by NotEpik** [comment]
how

**Comment by DEV-idiotXD** [comment]
> But that's where I get the error message with my character
> 
> > character editor in the main menu click 7

oh god that means ur character isnt in the right folder put it i /mods and put the assets in mods/images

**Comment by DEV-idiotXD** [comment]
then the characters icon in mods/images/icons

**Comment by NotEpik** [comment]
> > But that's where I get the error message with my character
> > > character editor in the main menu click 7
> 
> oh god that means ur character isnt in the right folder put it i /mods and put the assets in mods/images

/mods/images/characters

**Comment by DEV-idiotXD** [comment]
> > > But that's where I get the error message with my character
> > > > character editor in the main menu click 7
> > 
> > 
> > oh god that means ur character isnt in the right folder put it i /mods and put the assets in mods/images
> 
> /mods/images/characters

both work

**Comment by NotEpik** [comment]
let me make character for you lol

**Comment by cfunes401** [comment]
> > > oh god that means ur character isnt in the right folder put it i /mods and put the assets in mods/images

That's where I put the assets

**Comment by cfunes401** [comment]
I mean the image and the xml are in the mentioned directories

**Comment by DEV-idiotXD** [comment]
> > > > oh god that means ur character isnt in the right folder put it i /mods and put the assets in mods/images
> 
> That's where I put the assets

in the part where it asks for your files location put mods/images/characters

**Comment by NotEpik** [comment]
> haxe.xml.XmlParserException: Expected node at line 2 char 2

did the error popup when you open game or where the error popup

**Comment by cfunes401** [comment]
> > haxe.xml.XmlParserException: Expected node at line 2 char 2
> 
> did the error popup when you open game or where the error popup

When I try to reload assets for my character

**Comment by NotEpik** [comment]
give me the image of a character I will try make JSON if i got the error that mean your character file is sus and must get voted out of the spaceship

**Comment by cfunes401** [comment]
I just want to say something before passing the character to you, and that is that it is a character test

**Comment by NotEpik** [comment]
ok character test

**Comment by NotEpik** [comment]
you can remove all post/original image and make some copy of it

**Comment by cfunes401** [comment]
this is the image:

![MICRO_assets](https://user-images.githubusercontent.com/95454919/144542009-25871462-48e3-4d1a-9594-9a91f9d62e62.png)

And the xml
[MICRO_assets.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7646682/MICRO_assets.txt)
:

Also I will only use the character as a template, of course it works

**Comment by cfunes401** [comment]
And yes is a Microphone

**Comment by DEV-idiotXD** [comment]
> And yes is a Microphone

the xml and image has to be the same name

**Comment by NotEpik** [comment]
the asset is big noice

**Comment by cfunes401** [comment]
what does it mean?

**Comment by NotEpik** [comment]
i mean it bigger than other character i ever see

**Comment by cfunes401** [comment]
> > And yes is a Microphone
> 
> the xml and image has to be the same name

They have the same name

**Comment by cfunes401** [comment]
> i mean it bigger than other character i ever see

But does that affect something?

**Comment by NotEpik** [comment]
no

**Comment by NotEpik** [comment]
also, I can reload assets for character

put this in the file name box: [if in mods/images/characters] characters/MICRO_assets [if in mods/images] MICRO_assets

if you put them and still got error try download psych engine if you downloaded psych engine again and it still didn't work then sad

**Comment by cfunes401** [comment]
And is there any to be able to put the character?

**Comment by NotEpik** [comment]
wot

**Comment by cfunes401** [comment]
I mean, can the .json file be made?

**Comment by NotEpik** [comment]
yes i can make for you

**Comment by NotEpik** [comment]
or if you mean can you make it you can if you don't got the error

**Comment by cfunes401** [comment]
And by the way, can you test if the file works for you?

**Comment by NotEpik** [comment]
????????

**Comment by cfunes401** [comment]
I mean, check if the same error message happens to you

**Comment by NotEpik** [comment]
I did JSON yay

**Comment by cfunes401** [comment]
What was the mistake?

**Comment by NotEpik** [comment]
> 

idk what happen to you that make you cant do character

**Comment by NotEpik** [comment]
json thing

[microjson.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7646769/microjson.txt)

**Comment by cfunes401** [comment]
thank you very much for helping me you and Dev-idiotXD

**Comment by cfunes401** [comment]
I have another error

**Comment by NotEpik** [comment]
wat

**Comment by cfunes401** [comment]
![image](https://user-images.githubusercontent.com/95454919/144545947-506934b0-279a-442f-925c-6742992f6a2a.png)

**Comment by NotEpik** [comment]
i didnt test character in song yet imma test it

**Comment by NotEpik** [comment]
> ![image](https://user-images.githubusercontent.com/95454919/144545947-506934b0-279a-442f-925c-6742992f6a2a.png)

well I got no error probably only happen to you

**Comment by cfunes401** [comment]
Then it would be some error of my computer or the build'

**Comment by cfunes401** [comment]
No, there is no case I cannot open the .json file

**Comment by cfunes401** [comment]
It doesn't work

**Comment by ShadowMario** [comment]
Your xml file is broken, i can't help you with that
