### ISSUE TITLE
Charting is completely broken past the 15 second mark. 

### ISSUE THREAD

**Issue by Slyceth** [ShadowMario/FNF-PsychEngine#162]
Fresh copy of the latest version of PsychEngine, in the video I replaced the dad texture with a green square and the background stage textures with green textures as well (I want to use this for a video)

The charting is completely busted after I spent a long time on it, notes after 15 seconds disappear, and reappear 30 seconds in? They look completely fine in the chart editor though!

Video:
https://www.reddit.com/r/Streamers/comments/pwo2la/test/

Chart:
https://cdn.discordapp.com/attachments/892092901687951431/892120429588799559/bopeebo.json

**Comment by DJDogster1384** [comment]
I'm not an expert on the matter, but it works perfectly fine for me, I think you should try reinstalling the mod, if that doesn't work, it may be an issue with your antivirus. Just a suggestion for what you should do I don't actually know the solution, but I hope it works out well for you!

**Comment by Slyceth** [comment]
> 
> 
> I'm not an expert on the matter, but it works perfectly fine for me, I think you should try reinstalling the mod, if that doesn't work, it may be an issue with your antivirus. Just a suggestion for what you should do I don't actually know the solution, but I hope it works out well for you!

I do not have an antivirus, and I reinstalled the mod twice. Did you try the chart I've linked? Does the issue not happen to you with this chart?

**Comment by ShadowMario** [comment]
Copy Section is bugged on the Gamebanana/Gamejolt/Github release.
It was already fixed on the main github repo.
