### ISSUE TITLE
 Could not find haxelib "linc_luajit", does it need to be installed? Problem on mac

### ISSUE THREAD

**Issue by Tigedraglon10** [ShadowMario/FNF-PsychEngine#1620]
### Describe your problem here.

And now im a dummy. so i ran lime test linux -debug and it said  Could not find haxelib "linc_luajit", does it need to be installed?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

**Comment by Tigedraglon10** [comment]
I literally don't know how to make a fi
![Screen Shot 2021-12-02 at 7 50 24 PM](https://user-images.githubusercontent.com/67351087/144536884-834107b7-c583-4eb9-84be-4aa981d23e59.png)
le

**Comment by CrusherMods** [comment]
Open cmd and put this in:
`haxelib install linc_luajit`

**Comment by Tigedraglon10** [comment]
> Open cmd and put this in: `haxelib install linc_luajit`

Okay thx

**Comment by Tigedraglon10** [comment]
> haxelib install linc_luajit

`Failed. Triggering retry due to HTTP timeout` Didn't work

**Comment by Tigedraglon10** [comment]
> Open cmd and put this in: `haxelib install linc_luajit`

Nvm brb

**Comment by Tigedraglon10** [comment]
Whoops it didnt work `/user/local/lib/haxe/lib/discord_rpc/git/discord_rpc/DiscordRpc.hx:4: characters 8-20 : You cannot access the cpp package while targeting neko (for cpp.Function)
source/Discord.hx:4: characters 8-30 :     referenced here
source/TitleState.hx:4: characters 8-15 :     referenced here
source/Main.hx:16: characters 37-47 :     referenced here
manueliyoalvarez1@iMac-de-manueliyo1 FNF-PsychEngine-main %`

**Comment by NotEpik** [comment]
ok

**Comment by gaminbottomtext** [comment]
you cant build linux on mac

**Comment by ShadowMario** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/44785097/144552764-bb8b342e-4cf2-40ca-b171-fff150016fb3.png)
