### ISSUE TITLE
Need help using `lime test linux -debug`

### ISSUE THREAD

**Issue by Tigedraglon10** [ShadowMario/FNF-PsychEngine#1623]
### Describe your problem here.

I put it and then it uses neko, does it need that? I need help solving this

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by NotEpik** [comment]
this guy literally make issue every 1-6 hour

**Comment by Tigedraglon10** [comment]
> this guy literally make issue every 1-6 hour

Lol I do need help bro

**Comment by ShadowMario** [comment]
Yeah Mac needs neko

**Comment by Tigedraglon10** [comment]
> Yeah Mac needs neko

Thx bro it worked Shadow
