### ISSUE TITLE
Input Selection

### ISSUE THREAD

**Issue by Rudyrue** [ShadowMario/FNF-PsychEngine#1625]
### What feature do you want to get added on the base engine?

You could add an option where you can select between Psych Engine's input system and inputs that are similar to Kade's/Kade Engine's input system.

Just a thought.

**Comment by DaBanana64** [comment]
No. Psych's input system is already good to begin with so I have no idea why you want another Kade Engine/Original Inputs.

**Comment by ShadowMario** [comment]
Nah i don't wanna shit my code for useless options
