### ISSUE TITLE
modcharts?

### ISSUE THREAD

**Issue by Androphonomania** [ShadowMario/FNF-PsychEngine#1626]
if you do add modcharts, please add kade engine modchart support thanks

**Comment by DEV-idiotXD** [comment]
> if you do add modcharts, please add kade engine modchart support thanks

cant wait for him to come here and just say

# no.

**Comment by DaBanana64** [comment]
Why you want another Kade Engine?

**Comment by kittstone** [comment]
we already have modcharts

they're script files

**Comment by Tigedraglon10** [comment]
> we already have modcharts
> 
> they're script files

Lol true 🟦  
              🟥 
               Sus
