### ISSUE TITLE
Main Menu Got Crashed

### ISSUE THREAD

**Issue by afeefflox** [ShadowMario/FNF-PsychEngine#1630]
### Describe your bug here.

So, when I press title screen the game Got crashed for no reason

### Command Prompt/Terminal logs (if existing)

```bash
there is no zero Error
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

It Nothing but fixed Main Menu State

**Comment by DaBanana64** [comment]
Do a git reset --hard and recompile again?
