### ISSUE TITLE
Turning off Anti-aliasing crashes the game

### ISSUE THREAD

**Issue by Aikoyori** [ShadowMario/FNF-PsychEngine#1631]
### Describe your bug here.

When you turn off anti-aliasing in Graphics option, it crashes the game.

https://user-images.githubusercontent.com/12034280/144587799-7b1ae968-44ea-4dcf-acc4-c5540c5bf022.mp4

### Command Prompt/Terminal logs (if existing)

```bash
source/TitleState.hx:77: checking for update
source/TitleState.hx:84: version online: 0.5b, your version: 0.5b
source/Discord.hx:17: Discord Client starting...
source/Discord.hx:67: Discord Client initialized
source/Discord.hx:24: Discord Client started.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I downloaded the build from the Pre-release tab.

**Comment by DaBanana64** [comment]
I think this problem has to do with 0.5b is a pre-release thing and that's why it crashes when turning that on.

**Comment by ShadowMario** [comment]
Fixed
