### ISSUE TITLE
Chart's Editor Playtest but outside Chart Editor

### ISSUE THREAD

**Issue by AetherLynx** [ShadowMario/FNF-PsychEngine#1633]
### What feature do you want to get added on the base engine?

_(I'll try my best to explain this i don't speak english very well lol)_

Basically just like the **Chart Editor** has as playtest function to test the chart from an exact position, but what i suggest is adding that same feature but in base game.

This could be useful for viewing events or functionality of custom notetypes, because this can't be viewed in the Chart Editor's playtest.

For example, let's say your song lasts 5 minutes, and at the end you have some sort of event, Character Change, Custom Event, Arrows Move, etc. Or you have a custom notetype you want to check if it works, but you'll have to wait 5 minutes.

This could be solved by adding support for playtesting in-game, i think it would be a really nice time-saving feature!

**Comment by 4wdthinks** [comment]
the annoying thing about the playtest feature is that it puts you in a seperate state from playstate where the only thing you can see is the notes/

**Comment by MayoALT** [comment]
just put the event at the start of the song

**Comment by ShadowMario** [comment]
I have a different plan for that.
