### ISSUE TITLE
How do you use the credits.txt (0.5 Prerelease)

### ISSUE THREAD

**Issue by CrusherMods** [ShadowMario/FNF-PsychEngine#1640]
### What is your question?

I'm just wondering I saw in the files that credits.txt are a thing and in the 0.5 prerelease notes on github and Im wondering how to use it? It's not important since I'm just wondering so you don't need to reply If you don't want to

**Comment by bbpanzu** [comment]
check the wiki FAQ

**Comment by CrusherMods** [comment]
Oh thanks
