### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by duckyduck1q** [ShadowMario/FNF-PsychEngine#1643]
### Describe your problem here.

the error is HAXE STD PATH

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheShapeShifterYT** [comment]
I also had a problem with discord-rpc

**Comment by duckyduck1q** [comment]
how do I solve it

**Comment by IAMEC123** [comment]
well did you install it?

**Comment by duckyduck1q** [comment]
yes

**Comment by ShadowMario** [comment]
Not a psych engine issue, use Google to find your answer.

**Comment by duckyduck1q** [comment]
I can't find anything about that
