### ISSUE TITLE
How do I add an animated background in the source code?

### ISSUE THREAD

**Issue by FrancoGD476** [ShadowMario/FNF-PsychEngine#1645]
### What is your question?

I've been trying to add the animated backgrounds for weeks and I don't know how to do it.
by the way I use version 0.4.1

**Comment by Alt-Reality** [comment]
First make a var like this:
![image](https://user-images.githubusercontent.com/88809517/144661541-7386617b-6a34-4f29-a511-dfd8a076fa27.png)
Then put the animation stuff like this: 
![image](https://user-images.githubusercontent.com/88809517/144661633-552955ba-ad1a-4804-b9bd-2baffd03a8a4.png)
For the animation.addByPrefix part, replace bounce with whatever animation you want, and replace bounce6 with the animation name in your xml.

Now find a switch (curStage) and put your playanim code there, like this:
![image](https://user-images.githubusercontent.com/88809517/144661837-845fd624-735c-4db8-aee4-cf3b962609db.png)
Replace the rockbgbounce with your var you did at the very beginning, replace the bounce with the animation name you did back in the stage code, and replace case 'cave' with the name of your stage.
