### ISSUE TITLE
dialogueCount variable acting weirdly.

### ISSUE THREAD

**Issue by Alt-Reality** [ShadowMario/FNF-PsychEngine#1647]
### Describe your problem here.

the dialogueCount variable has always been above the startDialogue function.
![image](https://user-images.githubusercontent.com/88809517/144662424-0dd0fa90-32dc-443a-80dd-f585f1626980.png)
 But recently, i added some code for a cutscene after a ending song dialogue. when i tried to compile the game, i kept getting this error 
![image](https://user-images.githubusercontent.com/88809517/144662481-70e7b58e-bf6d-430e-9f39-623f8dbf03c0.png)
I've never had this error before, and i didnt edit the variable at all, so i dont know what the problem is. I asked a lot of people and they all said they didnt know what was happening.
I made a lot of changes to my playstate file, so if you want to see it here it is: https://cdn.discordapp.com/attachments/557655474951159828/916412674466775081/PlayState.hx
_**Had to send it as a discordapp attachment since github doesnt allow hx files to be sent in comments lol**_
_**No it isnt a virus**_

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

PlayState.hx for stage code, and the post song dialogue code + cutscene after that dialogue code, FreeplayState, StoryMenuState, and Cool Util to remove a difficulty.

**Comment by ShadowMario** [comment]
That's not the issue, it doesn't matter where the variable is positioned. The issue is on what happens before it, you've left some brackets unclosed.
[PlayState.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/7669450/PlayState.zip)
