### ISSUE TITLE
Song not loading

### ISSUE THREAD

**Issue by LeGoldenBoots** [ShadowMario/FNF-PsychEngine#1649]
### Describe your problem here.

Whenever I load a song or make a new one, it crashes. I've tried checking the characters, The characters are fine, I've tried trying to fix the stages but it doesn't seem to work. And I have the JSON files and Audio files for the song. And whenever I try to load the song, I get "Null Object Reference".

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added new difficulties, and new characters, But I did add a new stage, which was working earlier but doesn't now.  I tried adding a stage file, But to no avail.

**Comment by bbpanzu** [comment]
compile with -debug

what does the terminal say

**Comment by LeGoldenBoots** [comment]
it says it fine, but it isn't

**Comment by bbpanzu** [comment]
screenshot your terminal at the crash and send it

**Comment by LeGoldenBoots** [comment]
The terminal gave me no information that seemed useful
![not](https://user-images.githubusercontent.com/45889414/144698768-3d83db2b-561d-4291-a79e-86fd4ae4fc21.png)
.

**Comment by bbpanzu** [comment]
is you stage.lua name the same as your stage.json name?

**Comment by LeGoldenBoots** [comment]
Yes.
