### ISSUE TITLE
help bruh

### ISSUE THREAD

**Issue by HiroOfc** [ShadowMario/FNF-PsychEngine#1653]
### Describe your problem here.

i want to put the song names on freeplay at the center, but idk how
could someone explain me?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i edited FreeplayState.hx, adding a songText.screenCenter(X);, deleted some shit and edited the numbers to 0, 0 at var songText:Alphabet

**Comment by bbpanzu** [comment]
alphabet.hx 
update function.

thats where the letter offsetting is. you can screenCenter there

**Comment by HiroOfc** [comment]
> alphabet.hx update function.
> 
> thats where the letter offsetting is. you can screenCenter there

broo thank u panzu
