### ISSUE TITLE
Extending MainMenuState to FlxSubState

### ISSUE THREAD

**Issue by Santikun** [ShadowMario/FNF-PsychEngine#1654]
I'm trying to extend MainMenuState to `FlxSubState` (currently extending `MusicBeatState`), but when I try to change it, I get Type not found errors.

```source/MainMenuState.hx:194: characters 8-24 : Type not found : controls.UI_UP_P  
source/MainMenuState.hx:199: characters 8-26 : Type not found : controls.UI_DOWN_P  
source/MainMenuState.hx:204: characters 8-21 : Type not found : controls.BACK  
source/MainMenuState.hx:210: characters 8-23 : Type not found : controls.ACCEPT
```

I managed to fix it by importing `Controls` and setting a variable to it, but when trying to call from TitleState it still says it's missing flixel.SubState (even after importing `flixel.FlxSubState`). I've been trying to modify MusicBeatState to include substates but haven't got it working so far.

How can I fix it? I'm willing to change anything in the code just to have a smooth transition on my title screen.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I modified the code to suit my needs, but this happens on a clean version of the build as well.

**Comment by Santikun** [comment]
Okay, I noticed I was importing flixel.SubState instead of flixel.FlxSubState, now it doesn't give any errors but straight up crashes the program.

**Comment by bbpanzu** [comment]
Mainmenustate needs to extend musicbeatstate. thats where the controls variables are.

**Comment by Santikun** [comment]
Yes, but I need to turn MainMenuState into a substate in order to make a smooth transition between screens. Is there no way to still make it work?

**Comment by bbpanzu** [comment]
you can use FlxG.switchState instead of MusicBeatState.switchState
