### ISSUE TITLE
I cant compile the game

### ISSUE THREAD

**Issue by BL0KYBL0K** [ShadowMario/FNF-PsychEngine#1656]
### Describe your bug here.

when i compiled the game i got this error
 {+ length : Int } should be String

### Command Prompt/Terminal logs (if existing)

```bash
source/ModsMenuState.hx:611: characters 6-28 : {+ length : Int } should be String
source/ModsMenuState.hx:615: characters 6-42 : {+ length : Int } should be String
source/ModsMenuState.hx:619: characters 36-47 : Array access is not allowed on {+ length : Int }
source/ModsMenuState.hx:619: characters 36-47 : For function argument 'Red'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by bbpanzu** [comment]
fixing it rn.

**Comment by Tigedraglon10** [comment]
How did you compile it?

**Comment by bbpanzu** [comment]
it's a haxe issue when dealing with JSON loaded Dynamics.
instead of json.data i did Reflect.getProperty(json,"data")

not the prettiest but it works. pull the latest vers
