### ISSUE TITLE
Crash when enemy sings

### ISSUE THREAD

**Issue by bangthe1st** [ShadowMario/FNF-PsychEngine#1660]
### Describe your bug here.

This should be simple to describe. When I try to go to a song and the opponent sings a note, it instantly crashes.

### Command Prompt/Terminal logs (if existing)

```bash
Error : Null Object Reference
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

I don't recall changing anything.

**Comment by ShadowMario** [comment]
i need the crash trace...

**Comment by bangthe1st** [comment]
> i need the crash trace...

I have no idea what a crash trace is, since i'm a beginner at being a tech geek lol. But heres what the whole terminal says when it crashes:

Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 25
Called from ApplicationMain::create ApplicationMain.hx line 130
Called from lime.app.Application::exec lime/app/Application.hx line 150
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 146
Called from lime._internal.backend.native.NativeApplication::handleRenderEvent lime/_internal/backend/native/NativeApplication.hx line 370
Called from lime.app._Event_lime_graphics_RenderContext_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from openfl.display.Stage::__onLimeRender openfl/display/Stage.hx line 1950
Called from openfl.display.Stage::__broadcastEvent openfl/display/Stage.hx line 1166
Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 1399
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 551
Called from flixel.FlxGame::step flixel/FlxGame.hx line 677
Called from flixel.FlxGame::update flixel/FlxGame.hx line 747
Called from flixel.FlxState::tryUpdate flixel/FlxState.hx line 202
Called from PlayState::update PlayState.hx line 2353
Called from flixel.group.FlxTypedGroup::forEachAlive flixel/group/FlxGroup.hx line 769
Called from PlayState::update PlayState.hx line 2452
Called from PlayState::opponentNoteHit PlayState.hx line 3698
Error : Null Object Reference

**Comment by ShadowMario** [comment]
> Called from PlayState::opponentNoteHit PlayState.hx line 3698

Could you show me what is on line 3698 of PlayState.hx on your source code?

**Comment by bangthe1st** [comment]
> > Called from PlayState::opponentNoteHit PlayState.hx line 3698
> 
> Could you show me what is on line 3698 of PlayState.hx on your source code?

![image](https://user-images.githubusercontent.com/87505454/144773751-05212b93-1b88-4e7e-887b-085da863e53a.png)

**Comment by bangthe1st** [comment]
<img width="354" alt="Screen Shot 2021-12-06 at 6 32 33 AM" src="https://user-images.githubusercontent.com/87505454/144839070-f02d19e4-0f50-4024-8dd1-a0feb3bbad07.png">

**Comment by bangthe1st** [comment]
> > Called from PlayState::opponentNoteHit PlayState.hx line 3698![image](https://user-images.githubusercontent.com/87505454/144931556-3b5d294a-3565-4ac6-b78b-840a9994abc2.png)> 
> Could you show me what is on line 3698 of PlayState.hx on your source code?

**Comment by bangthe1st** [comment]
> > Called from PlayState::opponentNoteHit PlayState.hx line 3698
> 
> Could you show me what is on line 3698 of PlayState.hx on your source code?

![image](https://user-images.githubusercontent.com/87505454/144931592-844979ff-71c2-4793-9f6a-459a8bad4929.png)

**Comment by bangthe1st** [comment]
> > > Called from PlayState::opponentNoteHit PlayState.hx line 3698
> > 
> > 
> > Could you show me what is on line 3698 of PlayState.hx on your source code?
> 
> ![image](https://user-images.githubusercontent.com/87505454/144931592-844979ff-71c2-4793-9f6a-459a8bad4929.png)

has this been fixed?

**Comment by ShadowMario** [comment]
Most likely???
