### ISSUE TITLE
lua curBeat issue

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#1661]
### Describe your bug here.

so i was porting my psych mod to the newest update. and i noticed that background dance characters (like week 4) are only playing their right anims. like thi
![BUGGY](https://user-images.githubusercontent.com/81887418/144689991-300b2406-1c1f-4c7c-9ef1-3fb4475769e1.gif)
s 

heres the code i used 

        objectPlayAnimation('boy1','danceRight')
	if curBeat % 2 == 0 then --if even beat
	objectPlayAnimation('boy1','danceLeft')

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by bbpanzu** [comment]
```
objectPlayAnimation('boy1','danceRight')
if curBeat % 2 == 0 then --if even beat
objectPlayAnimation('boy1','danceLeft')
end--pssst you forgot the end
```

or if that wasn't the issue, you might've forgot to register the dance left anim properly

**Comment by crispyboi24** [comment]
> ```
> objectPlayAnimation('boy1','danceRight')
> if curBeat % 2 == 0 then --if even beat
> objectPlayAnimation('boy1','danceLeft')
> end--pssst you forgot the end
> ```
> 
> or if that wasn't the issue, you might've forgot to register the dance left anim properly

the end was in the code, i just didnt send it, and i did register the left anim properly. the code worked perfectly in 0.4. but when i ported it to 0.5b, it was buggy like how i described.

**Comment by crispyboi24** [comment]
> > ```
> > objectPlayAnimation('boy1','danceRight')
> > if curBeat % 2 == 0 then --if even beat
> > objectPlayAnimation('boy1','danceLeft')
> > end--pssst you forgot the end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or if that wasn't the issue, you might've forgot to register the dance left anim properly
> 
> the end was in the code, i just didnt send it, and i did register the left anim properly. the code worked perfectly in 0.4. but when i ported it to 0.5b, it was buggy like how i described.

like it works on countdown but not after it

**Comment by crispyboi24** [comment]
> ```
> objectPlayAnimation('boy1','danceRight')
> if curBeat % 2 == 0 then --if even beat
> objectPlayAnimation('boy1','danceLeft')
> end--pssst you forgot the end
> ```
> 
> or if that wasn't the issue, you might've forgot to register the dance left anim properly



> > > ```
> > > objectPlayAnimation('boy1','danceRight')
> > > if curBeat % 2 == 0 then --if even beat
> > > objectPlayAnimation('boy1','danceLeft')
> > > end--pssst you forgot the end
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > or if that wasn't the issue, you might've forgot to register the dance left anim properly
> > 
> > 
> > the end was in the code, i just didnt send it, and i did register the left anim properly. the code worked perfectly in 0.4. but when i ported it to 0.5b, it was buggy like how i described.
> 
> like it works on countdown but not after it

yep, works perfectly in 0.4.

**Comment by bbpanzu** [comment]
send mod pack. i'll take a look at it maybe

**Comment by crispyboi24** [comment]
> send mod pack. i'll take a look at it maybe

Alright, here it is (request access since I don’t want it to leak out) https://drive.google.com/drive/folders/1MBlIvEluodP5KsC-CfYMpwAM7jDIEz_9?usp=sharing

**Comment by crispyboi24** [comment]
> > send mod pack. i'll take a look at it maybe
> 
> Alright, here it is (request access since I don’t want it to leak out) https://drive.google.com/drive/folders/1MBlIvEluodP5KsC-CfYMpwAM7jDIEz_9?usp=sharing

still an issue in 0.5 :(

**Comment by crispyboi24** [comment]
ITS FIXED THANK YOU BB
