### ISSUE TITLE
mod folder file replacment 

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#1663]
### Describe your problem here.

so you know how you can add files into the mod folder, that have the same name as ones in the base game. and they load in game? well if i use the new mod menu way (making an individual folder with the same name as the mod) it only loads files that dont have the same name as ones from the base game. is this a bug or is it intentional? thanks

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by bbpanzu** [comment]
what asset did you expect to be replaced

**Comment by crispyboi24** [comment]
> what asset did you expect to be replaced

all the menu colors, menu characters, and week jsons.

**Comment by bbpanzu** [comment]
if you get the latest source, the game will load the top mod you put in the mod menu.

**Comment by crispyboi24** [comment]
> 

but its the only mod that i have in the mod menu. also the title screen stuff loads in, but it doesnt load in the week jsons, menu BGs, or anything thats supposed to be a file replacement. 

i have it all in a separate folder in the mod folder itself, but if i just put it in the main mod loader, it loads everything in, but doesnt appear on the mod menu. im not sure if im just being dumb and not understanding, or if this is a bug

**Comment by crispyboi24** [comment]
another thing is that sometimes when i go back to the title screen, it uses the xml for the mod versions of the logo and gf, but loads the png files for the base game ones. so its a clipping mess sometimes.

**Comment by bbpanzu** [comment]
fixed it

**Comment by crispyboi24** [comment]
> fixed it

So the title screen is fixed, but the menu BGs and week characters and jsons don’t load. But I can access all the songs through the menu editor, and changing the directory by pressing right. Sorry if I’m bothering you btw.

**Comment by bbpanzu** [comment]
you not dw. we need to know every tiny bug to fix. i'll take a look at that in a few
