### ISSUE TITLE
Combo Bug

### ISSUE THREAD

**Issue by MarkAwesomeness** [ShadowMario/FNF-PsychEngine#1665]
### Describe your bug here.

There is an issue with the combo counting. The initial value is 0 when it should be 1. It causes the combo count to be one less than its supposed to be. The prerelease build was tested by a friend of mine, an the same issue seemed to occur. And it happens regardless of modding changes, as I tested it on an unmodded version and it doesn't change

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by bbpanzu** [comment]
fixed.
