### ISSUE TITLE
Game Creashes when pressing a note in bf turn on the chart editor 

### ISSUE THREAD

**Issue by star-fran** [ShadowMario/FNF-PsychEngine#1668]
### Describe your bug here.

I went to the new charting option on the mod making menu, i was charting a song and when i tried to test it, it crashed when i pressed a note (it was a normal note) 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by bbpanzu** [comment]
it should be fixed now. it had something to do with notesplash skins
