### ISSUE TITLE
This might be my last issue.

### ISSUE THREAD

**Issue by Normalhuman1475** [ShadowMario/FNF-PsychEngine#167]
Ok, I fixed most of the problems in my last issue here, But as soon as i save, ALL OF THESE POP UP.
![image](https://user-images.githubusercontent.com/89854107/135111182-b2de8bdb-a7c6-4a16-b550-bc659586ac88.png)
I've tried to fix some of them like "Unknown identifier : b" but i think you can see it didnt work. Im gonna post where the problems are, and i will be REALLY HAPPY if someone helped me with this since im new to coding.
"Map<String, Bool> has no field clear"
![image](https://user-images.githubusercontent.com/89854107/135111760-431f84cc-3da5-4338-b789-515613eb77b9.png)
"Map<String, Bool> has no field clear"
![image](https://user-images.githubusercontent.com/89854107/135111933-989e3fd9-a162-4b9d-a2bf-52e60839bd93.png)
"Class<Paths> has no field modsJson"
![image](https://user-images.githubusercontent.com/89854107/135112083-ac668b6f-3c3a-444b-bf74-e73fe8fc7fb4.png)
"Class<Std> has no field isOfType"
![Screenshot 2021-09-28 10 55 06 AM](https://user-images.githubusercontent.com/89854107/135112310-9098ad86-08b8-40d1-956d-554b0ebaf6c5.png)
"Array<Bool> has no field contains"
![image](https://user-images.githubusercontent.com/89854107/135112499-bf6442a4-d3f7-41f1-9244-f2d21088029f.png)
"Array<Bool> has no field contains"
![image](https://user-images.githubusercontent.com/89854107/135112591-f9a05075-1ebd-4c5f-97aa-7cff66e3af0e.png)
"Array<Bool> has no field contains"
![image](https://user-images.githubusercontent.com/89854107/135112697-d94d439e-e3c9-435f-9e48-b1ad3a6a9310.png)
"Cannot access this or other member field in variable initialization"
![image](https://user-images.githubusercontent.com/89854107/135123269-933e4835-518a-4894-aad5-dbbcf70be499.png)
I will be updating this so be ready

what
![Screenshot 2021-09-28 2 21 30 PM](https://user-images.githubusercontent.com/89854107/135144191-b6e96545-670b-4d2a-b7ab-fcb06988e6c8.png)
how do fix
![image](https://user-images.githubusercontent.com/89854107/135147868-468c1673-c119-40a7-969d-a8574af4a648.png)
![image](https://user-images.githubusercontent.com/89854107/135147912-af48f57c-ed0b-454e-a947-dbf73a30e6b9.png)

**Comment by ShadowMario** [comment]
https://gamebanana.com/tuts/13653
