### ISSUE TITLE
Changing the Week Order on the Downloadable Version of Psych Engine (Lua Only, No Source Code)

### ISSUE THREAD

**Issue by RiloTheFox** [ShadowMario/FNF-PsychEngine#1670]
### What is your question?

Is it possible to change the week order for custom weeks?
It should be possible for the Downloadable Version of the Engine.
I know it is possible on the source code version, but I want to do this on the Downloadable Version.

**Comment by mayo78** [comment]
its in alphabetical order so you could name a week "cool" and then the next one "zawesome"

**Comment by HiroOfc** [comment]
i think u need to order 'em at a weekList.txt

**Comment by ShadowMario** [comment]
Done.
