### ISSUE TITLE
Panzu said something on twt and I'm confused..

### ISSUE THREAD

**Issue by WizardMantis441** [ShadowMario/FNF-PsychEngine#1671]
### What is your question?

i made a joke on **_twitter dot com_** at the release of 0.5 psych engine, but panzu said:

![image](https://user-images.githubusercontent.com/77557487/144699253-dc4e4692-a567-410e-bc9c-998019334a48.png)

maybe i asked wrong, but im refering to opponent / player offsets in 1 json, so when the character is in the dad's side, it will use X offsets, but will use Y offsets on the bf's side.
i wanna learn this because this would cut down like half of my storage cuz i hold a lot of characters (coded betadcsi shit)

if you know anything about this, please either answer here or dm me on discord cuz i dont use github much, someone just told me to ask here: **WizardMantis#8325**

**Comment by DaBanana64** [comment]
![image](https://user-images.githubusercontent.com/82652849/144699976-6a1960cb-115d-4ece-bd6d-1cc5913c7f6c.png)
I think he was referring to this.

**Comment by jayden8923** [comment]
so stage jsons?

**Comment by DaBanana64** [comment]
> so stage jsons?

No. The characters and stages .jsons are separate from eachother.

**Comment by bbpanzu** [comment]
Ohh I understand what you mean now. yea no data for flipped offsets. best you can do is flip the character, offset them, then flip it back and save

**Comment by WizardMantis441** [comment]
aight thanks man was just curious :)
