### ISSUE TITLE
Question about icons

### ISSUE THREAD

**Issue by MisterOficerPL** [ShadowMario/FNF-PsychEngine#1681]
### What is your question?

hi can i make icons bounce like in dave and bambi or cheeky v3 i animated some templates to see if its possible in psych engine
![bounce1](https://user-images.githubusercontent.com/95174349/144705220-1a8db219-e0bd-4c7a-b944-fd91fa60a71a.gif)

![bounce2](https://user-images.githubusercontent.com/95174349/144705228-e13fad95-9a2f-40bc-9bfb-2b87ef9bb8fa.gif)

**Comment by SrtHero278** [comment]
Tweens

**Comment by MisterOficerPL** [comment]
but how i use them i dont where to put them

**Comment by ShadowMario** [comment]
Isn't dave & bambi source code open? Just go check it.
