### ISSUE TITLE
How do i make the camera move with the opponent?

### ISSUE THREAD

**Issue by TobiManingding** [ShadowMario/FNF-PsychEngine#1683]
### Describe your problem here.

You know how the camera moves when the opponent sings in the sonic exe mod? How do we do that on Psych Engine?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

New week, 3 Characters, New stage, That's it

**Comment by bbpanzu** [comment]
look in Madness Vandalization stage lua code

**Comment by Doritojoey** [comment]
`local u = false;
local r = 0;
local xx = 550;
local yy = 500;
local xx2 = 850;
local yy2 = 500;
local ofs = 50;
local followchars = true;
local del = 0;
local del2 = 0;

function onUpdate()
	if del > 0 then
		del = del - 1
	end
	if del2 > 0 then
		del2 = del2 - 1
	end
    if followchars == true then
        if mustHitSection == false then
            if getProperty('dad.animation.curAnim.name') == 'singLEFT' then
                triggerEvent('Camera Follow Pos',xx-ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singRIGHT' then
                triggerEvent('Camera Follow Pos',xx+ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singUP' then
                triggerEvent('Camera Follow Pos',xx,yy-ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singDOWN' then
                triggerEvent('Camera Follow Pos',xx,yy+ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singLEFT-alt' then
                triggerEvent('Camera Follow Pos',xx-ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singRIGHT-alt' then
                triggerEvent('Camera Follow Pos',xx+ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singUP-alt' then
                triggerEvent('Camera Follow Pos',xx,yy-ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singDOWN-alt' then
                triggerEvent('Camera Follow Pos',xx,yy+ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'idle-alt' then
                triggerEvent('Camera Follow Pos',xx,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'idle' then
                triggerEvent('Camera Follow Pos',xx,yy)
            end
        else
            if getProperty('boyfriend.animation.curAnim.name') == 'singLEFT' then
                triggerEvent('Camera Follow Pos',xx2-ofs,yy2)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT' then
                triggerEvent('Camera Follow Pos',xx2+ofs,yy2)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singUP' then
                triggerEvent('Camera Follow Pos',xx2,yy2-ofs)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN' then
                triggerEvent('Camera Follow Pos',xx2,yy2+ofs)
            end
            if getProperty('boyfriend.curAnim.name') == 'idle-alt' then
                triggerEvent('Camera Follow Pos',xx2,yy2)
            end
            if getProperty('boyfriend.curAnim.name') == 'idle' then
                triggerEvent('Camera Follow Pos',xx2,yy2)
            end
        end
    else
        triggerEvent('Camera Follow Pos','','')
    end
    
end`

**Comment by Doritojoey** [comment]
yanderedev code

**Comment by Fablisothebottle** [comment]
where do i even put that in?

**Comment by Doritojoey** [comment]
custom event

**Comment by NickPlayzGITHUB** [comment]
Tried it for fun. But uhhh. Doesn't work
![image](https://user-images.githubusercontent.com/87223282/144739265-212914e7-bd41-43c7-ba20-f1a856af0566.png)

**Comment by BL0KYBL0K** [comment]
> 

you placed a ` at the begging and end

**Comment by Fablisothebottle** [comment]
> custom event

like lua?

**Comment by Fablisothebottle** [comment]
for like source code? can source code use lua?

**Comment by Adrian47roblox** [comment]
> Tried it for fun. But uhhh. Doesn't work ![image](https://user-images.githubusercontent.com/87223282/144739265-212914e7-bd41-43c7-ba20-f1a856af0566.png)
 
remove the ` in the last end

**Comment by BernardoGP4504** [comment]
> local u = false; local r = 0; local xx = 550; local yy = 500; local xx2 = 850; local yy2 = 500; local ofs = 50; local followchars = true; local del = 0; local del2 = 0;
> 
> function onUpdate() if del > 0 then del = del - 1 end if del2 > 0 then del2 = del2 - 1 end if followchars == true then if mustHitSection == false then if getProperty('dad.animation.curAnim.name') == 'singLEFT' then triggerEvent('Camera Follow Pos',xx-ofs,yy) end if getProperty('dad.animation.curAnim.name') == 'singRIGHT' then triggerEvent('Camera Follow Pos',xx+ofs,yy) end if getProperty('dad.animation.curAnim.name') == 'singUP' then triggerEvent('Camera Follow Pos',xx,yy-ofs) end if getProperty('dad.animation.curAnim.name') == 'singDOWN' then triggerEvent('Camera Follow Pos',xx,yy+ofs) end if getProperty('dad.animation.curAnim.name') == 'singLEFT-alt' then triggerEvent('Camera Follow Pos',xx-ofs,yy) end if getProperty('dad.animation.curAnim.name') == 'singRIGHT-alt' then triggerEvent('Camera Follow Pos',xx+ofs,yy) end if getProperty('dad.animation.curAnim.name') == 'singUP-alt' then triggerEvent('Camera Follow Pos',xx,yy-ofs) end if getProperty('dad.animation.curAnim.name') == 'singDOWN-alt' then triggerEvent('Camera Follow Pos',xx,yy+ofs) end if getProperty('dad.animation.curAnim.name') == 'idle-alt' then triggerEvent('Camera Follow Pos',xx,yy) end if getProperty('dad.animation.curAnim.name') == 'idle' then triggerEvent('Camera Follow Pos',xx,yy) end else if getProperty('boyfriend.animation.curAnim.name') == 'singLEFT' then triggerEvent('Camera Follow Pos',xx2-ofs,yy2) end if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT' then triggerEvent('Camera Follow Pos',xx2+ofs,yy2) end if getProperty('boyfriend.animation.curAnim.name') == 'singUP' then triggerEvent('Camera Follow Pos',xx2,yy2-ofs) end if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN' then triggerEvent('Camera Follow Pos',xx2,yy2+ofs) end if getProperty('boyfriend.curAnim.name') == 'idle-alt' then triggerEvent('Camera Follow Pos',xx2,yy2) end if getProperty('boyfriend.curAnim.name') == 'idle' then triggerEvent('Camera Follow Pos',xx2,yy2) end end else triggerEvent('Camera Follow Pos','','') end
> 
> end

then is there a way/event to stop the cam. follow?
