### ISSUE TITLE
A Error with MainMenuState.hx and ModsMenuState.hx?

### ISSUE THREAD

**Issue by Fablisothebottle** [ShadowMario/FNF-PsychEngine#1687]
### Describe your problem here.

So as the title says.
I'm having trouble running the source.
as I type in "lime test windows" I get this weird output.
**source/ModsMenuState.hx:388: characters 6-28 : {+ length : Int } should be String

source/ModsMenuState.hx:392: characters 6-42 : {+ length : Int } should be String

source/ModsMenuState.hx:396: characters 36-47 : Array access is not allowed on {+ length : Int }

source/ModsMenuState.hx:396: characters 36-47 : For function argument 'Red'**
has anybody encountered this? please help! am I missing anything?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I cant even the source.

**Comment by SrtHero278** [comment]
Old release. Now one fixes it. panzu said his haxe wasn't cooperating.

**Comment by Fablisothebottle** [comment]
wait so the old release of the source fixes this?

**Comment by SrtHero278** [comment]
> wait so the old release of the source fixes this?

Sorry typo. No, the new one fixes it,

**Comment by Fablisothebottle** [comment]
ok so your saying the one I get from the front page fixes this problem?

**Comment by Fablisothebottle** [comment]
from the code tab.

**Comment by Fablisothebottle** [comment]
like where do I get the new source code? I see that psych has been updated but where is the location of this?

**Comment by Fablisothebottle** [comment]
oh. I found it. I'm stupid.
