### ISSUE TITLE
Game Crashes while turning on anti-aliasing

### ISSUE THREAD

**Issue by JP1619** [ShadowMario/FNF-PsychEngine#1688]
### Describe your bug here.

When i try turning it on due to i turning it off for no lag to test chart
The game crashes.
Help please i want to port my old version mod to the new one

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited mods & some story mode week image files

**Comment by ShadowMario** [comment]
This was fixed after the Pre-release build already.
