### ISSUE TITLE
i wanna put my dialogue first then i want the song to play and then i want the cutscene to play on the song

### ISSUE THREAD

**Issue by wooq-droid** [ShadowMario/FNF-PsychEngine#1689]
### Describe your problem here.

ive been trying to get the game to load the dialogue first and then the cutscene but it wont work and im using the lua ver of psych engine this is the code so please tell me the issue with it @ShadowMario
[script.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7654057/script.txt)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Tigedraglon10** [comment]
Its not supposed to be .txt its .lua

**Comment by wooq-droid** [comment]
@Tigedraglon10 yeah i know i jut converted it to txt to show it

**Comment by Tigedraglon10** [comment]
> @Tigedraglon10 yeah i know i jut converted it to txt to show it

Oh okay but you can read it and copy it and then do "text in here" to show its code

**Comment by wooq-droid** [comment]
heres the code then i still dont know how to make it play the dialogue and song and then the cutscen


local allowCountdown = false
function onStartCountdown()
local allowCountdown = false;
local playDialogue = false;
function onStartCountdown()
	-- Block the first countdown and start a timer of 0.8 seconds to play the video
	if not allowCountdown and isStoryMode and not seenCutscene then
		playDialogue = true;
		allowCountdown = true;
		playDialogue = true;
		return Function_Stop;
	elseif playDialogue then
		setProperty('inDialogue', true);
		runTimer('startvideo', 0.8);
		playDialogue = false;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('dialogue', 'breakfast');
	end
end

**Comment by Tigedraglon10** [comment]
Lua Works On Source Code, Thats what worked for me try watching a tutorial

**Comment by wooq-droid** [comment]
ok
