### ISSUE TITLE
Week editor not opening

### ISSUE THREAD

**Issue by ToBAYT** [ShadowMario/FNF-PsychEngine#169]
On 0.4.1, the week editor doesn't open. Can you help me? I don't want to code it in.

**Comment by Alexis412** [comment]
When I press 7, nothing happens. The best way of saying it

**Comment by ToBAYT** [comment]
NVM. The latest release just has the wrong files. I'm a goddamn idiot

**Comment by Mastercopper2346** [comment]
Issue #169
