### ISSUE TITLE
How do you modchart on Psych engine?

### ISSUE THREAD

**Issue by maooni5** [ShadowMario/FNF-PsychEngine#1690]
### What is your question?

How do you modchart on psych engine like agoti and those mods?

**Comment by SrtHero278** [comment]
There are Four Functions for this:

noteTweenX(**tag**:String, **note**:Int, **value**:Dynamic, **duration**:Float, **ease**:String)
noteTweenY(**tag**:String, **note**:Int, **value**:Dynamic, **duration**:Float, **ease**:String)
noteTweenAngle(**tag**:String, **note**:Int, **value**:Dynamic, **duration**:Float, **ease**:String)
and noteTweenAlpha(**tag**:String, **note**:Int, **value**:Dynamic, **duration**:Float, **ease**:String)

**tag** is a random string for if you want to do something else after the tween has finished. (use function onTweenCompleted([whatever tag you used]))

**note** is the direction of notes. 
Opponent's notes:
0- Left
1- Down
2-Up
3-Right
BF's notes:
4-Left
5-Down
6-Up
7-Right 

**value** is the result of the tween (if you do noteTweenX('example', 0, 50, 1, 'linear'), the opponent's left arrow's x value will be 50.)

**duration** is how long it takes for the tween to finish.

and **ease** is the tweening method. (for example, 'linear' and 'quartIn')

**Comment by ShadowMario** [comment]
![](https://user-images.githubusercontent.com/44785097/145054587-44e0d414-ab80-48a4-9698-f730a89b7bf5.png)
