### ISSUE TITLE
How do I make a file for the source code version

### ISSUE THREAD

**Issue by TheShapeShifterYT** [ShadowMario/FNF-PsychEngine#1691]
### Describe your problem here.

I want to use the source code to make certain stuff but it's quite difficult to compile the game using CMD, so I heard you could create a *.exe file to run the game but can't find any help to do it.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by CrusherMods** [comment]
it goes into export/windows/release/bin AFTER you compile it

**Comment by ShadowMario** [comment]
https://www.google.com/search?q=compiling+friday+night+funkin&oq=compiling+friday+night+funkin&aqs=chrome..69i57j69i60l2j69i65l3j69i60l2.4304j0j7&sourceid=chrome&ie=UTF-8
