### ISSUE TITLE
setProperty('gf.alpha', 0) doesnt work, help

### ISSUE THREAD

**Issue by kittstone** [ShadowMario/FNF-PsychEngine#1692]
### Describe your problem here.

im literally just trying to set girlfriend's alpha to 0 this should not be hard

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no, if youre talking about source

**Comment by 4wdthinks** [comment]
girlfriend, not gf

**Comment by bbpanzu** [comment]
girlfriend, not gf

also if you're putting it on a onCreate callback, put it on a onCreatePost callback instead

**Comment by ShadowMario** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/44785097/144772399-f5ea20c6-3383-42c8-bf8c-4d166fd41865.png)
Actually, it's `gf` yeah.

Put it in onCreatePost as bbpanzu said

```lua
function onCreatePost()
    setProperty('gf.alpha', 0);
end
```
