### ISSUE TITLE
How to code at '#if desktop'

### ISSUE THREAD

**Issue by BlackREDf4** [ShadowMario/FNF-PsychEngine#1693]
### Describe your problem here.

if I try to code at '#if desktop' block, then there's code's color's are turn to gray and can't coding at there.

so If I put the mouse in the letter '#if desktop', the message 'not defined' appears there. and if I put the mouse in the code in the block of #if desktop, the message 'Inactive conditional compilation blockdiagnostics(6)' appears.

How I coding at '#if desktop' block?

*I used a translator. I hope it didn't seem rude.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by mayo78** [comment]
```
#if desktop
//do desktop only thing
#end
```

**Comment by BlackREDf4** [comment]
I can't

**Comment by BlackREDf4** [comment]
In it, Ctrl + Space and Ctrl +. does not work properly, making coding virtually impossible.

**Comment by MayoALT** [comment]
what are you using to code?
