### ISSUE TITLE
bug-report/feature request once again

### ISSUE THREAD

**Issue by Rottyy** [ShadowMario/FNF-PsychEngine#17]
hey, wanted to do both a bug-report (?), and feature request since the bug is what actually prompted the idea

so, as of now in the chart editor, if you copy-paste a section onto the same section, the game crashes, and it sucks to see

i was charting a duet, where both characters had the same notes, but i wanted to ensure the chart's accuracy and therefore tried to paste the left side's section over to the right as well (hopefully all of that makes sense?)

so, i figured, why not add a way to place notes on both sides at once? maybe holding a key or something? it'd help a ton with duets even though you've already done a bunch to help with them already

**Comment by ShadowMario** [comment]
Understood, i've fixed it now, should be up in the next update.

**Comment by ShadowMario** [comment]
Forgot to add this on 0.3.2, i will delay it until the next big update is out (soon), sorry for the delay.
