### ISSUE TITLE
in game menu running at a turtles pace

### ISSUE THREAD

**Issue by Gabetheman12** [ShadowMario/FNF-PsychEngine#1700]
the in game menu in the latest update runs like if it were on a windows 95 machine.
please fix this once you get to it!
ill also show my specs too
![Screenshot (57)](https://user-images.githubusercontent.com/93617330/144719645-2d6cd93a-34c4-44a5-bd06-cc521e9e2ea4.png)
![Screenshot (58)](https://user-images.githubusercontent.com/93617330/144719646-14aceba8-bc93-43be-9bba-61ee18819cfb.png)
.

### Are you modding a build from source or with Lua?
no modding active on it.

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i did not edit anything

**Comment by bbpanzu** [comment]
which menu?

**Comment by Fablisothebottle** [comment]
take a look at your fps is it set too max? if so then drop it down to sixty.

**Comment by ShadowMario** [comment]
Decrease your framerate up to the number of FPS your screen's refresh rate is.
