### ISSUE TITLE
How can I spin the arrows like in the song 'Endless' from VS. Sonic.EXE? (SOURCE CODE)

### ISSUE THREAD

**Issue by NesDoesGithub** [ShadowMario/FNF-PsychEngine#1703]
### Describe your problem here.

I am trying to make a Psych Engine port of VS Sonic.EXE, and i'm currently trying to recreate Endless. How can I make the arrows spin?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not change anything.

**Comment by Tigedraglon10** [comment]
Look at Psych engine tutorials idk.

**Comment by Tigedraglon10** [comment]
What version you using?

**Comment by SrtHero278** [comment]
![image](https://user-images.githubusercontent.com/93018286/144723783-54dd487e-3a9f-41e6-9102-5464e5e98912.png)

**Comment by FuseIsHere813** [comment]
Do not make issues like "How can I do X like in Y?"

**Comment by KGAMERDEV** [comment]
Use the tween spin events

**Comment by ShadowMario** [comment]
Use noteTweenAngle.

Also don't post your ports publicly, i hate when people do this.
