### ISSUE TITLE
freeplay song voices overlaps delay and combo music and menu music

### ISSUE THREAD

**Issue by Gui-iago** [ShadowMario/FNF-PsychEngine#1708]
### Describe your bug here.

this is just a simple bug that I felt like reporting, I guess the video can speak for itself

https://user-images.githubusercontent.com/45212377/144723697-8d058357-1fb0-4f38-8b91-09ea63694871.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing, all modifications are actually from the Mods folder-

edit: if it feels like a bug too, Space still plays the music on freeplay while also opening the gameplay changers menu

**Comment by bbpanzu** [comment]
fixed
