### ISSUE TITLE
Im trying to change the original fnf characters to optimized characters but 0.5b version makes them the original characters

### ISSUE THREAD

**Issue by Tigedraglon10** [ShadowMario/FNF-PsychEngine#1709]
### Describe your problem here.

I need help with this

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

**Comment by Tigedraglon10** [comment]
I tried changing them to optimized characters because my computer cant handle alot
![BOYFRIEND](https://user-images.githubusercontent.com/67351087/144726010-0061000c-5d8c-4ae7-8db1-96053fab7fa6.png)

**Comment by bbpanzu** [comment]
are you replacing the assets or putting them in the mod folder?

**Comment by Tigedraglon10** [comment]
> are you replacing the assets or putting them in the mod folder?

Im replacing it

**Comment by bbpanzu** [comment]
did you replace the assets/images/characters/BOYFRIEND.png?

**Comment by Tigedraglon10** [comment]
> did you replace the assets/images/characters/BOYFRIEND.png?

Yeah

**Comment by Tigedraglon10** [comment]
_=)
wdwadwa_

**Comment by Tigedraglon10** [comment]
And also it gives me this when i do lime test macos: `source/Achievements.hx:155: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/MainMenuState.hx:66: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:317: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/CharacterEditorState.hx:93: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/DialogueCharacterEditorState.hx:82: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead`

**Comment by bbpanzu** [comment]
are you replacing the assets in the exported build asset folder or the source assets folder?

cause those aren't errors those are warnings. they don't affect the game at all

**Comment by Tigedraglon10** [comment]
> Referen



> are you replacing the assets in the exported build asset folder or the source assets folder?
> 
> cause those aren't errors those are warnings. they don't affect the game at all

Source assets

**Comment by Tigedraglon10** [comment]
The Export build Assets

**Comment by Tigedraglon10** [comment]
Source asset folder

**Comment by Tigedraglon10** [comment]
> are you replacing the assets in the exported build asset folder or the source assets folder?
> 
> cause those aren't errors those are warnings. they don't affect the game at all

So bbpanzu, i just found out that Girlfriend lagged my game so can i replace her?

**Comment by Tigedraglon10** [comment]
I changed it so im fine now
