### ISSUE TITLE
i need help making a passcode

### ISSUE THREAD

**Issue by Real-Pog** [ShadowMario/FNF-PsychEngine#1716]
### Describe your problem here.

i want to make a passcode song for my friday night funkin mod and i need help 0.4.2 psych engine

### Are you modding a build from source or with Lua?

Source and lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i edited playstate and funkinlua and creditstate

**Comment by PoleyMagik** [comment]
Summarize your changes to the following files.

**Comment by Real-Pog** [comment]
what do you mean?

**Comment by PoleyMagik** [comment]
> playstate and funkinlua

What did you change in the playstate and funkinlua files.

**Comment by Real-Pog** [comment]
i added around 11 backgrounds and 3 cutscenes and i added the ability to use script.lua in funkinLua so i can make the scripts for song to work -psych engine 0.4.2-

**Comment by Real-Pog** [comment]
and i edited creditstate.hx and added 5 credits to people that worked on that mod

**Comment by Itz-Miles** [comment]
If you need password code, you can reuse Psych Engine's easter egg code in title.hx; an easter egg that switches title GF out with Psyka when you type "bb" in the title screen.

**Comment by Real-Pog** [comment]
where is that

**Comment by Itz-Miles** [comment]
titleState.hx. You can find the code by opening it and ctrl-f (finding) it.

**Comment by Real-Pog** [comment]
> 

i meant a passcode song is that what your talking about because im confused

**Comment by Itz-Miles** [comment]
When you type "bb" in the title screen, the game does something. The game checks if you typed Flxkey B, and Flxkey B, in that order. Instead of it being bb, and instead of it unlocking an easter egg, you can make it check for your password, and load up your song instead.

**Comment by Real-Pog** [comment]
> When you type "bb" in the title screen, the game does something. The game checks if you typed Flxkey B, and Flxkey B, in that order. Instead of it being bb, and instead of it unlocking an easter egg, you can make it check for your password, and load up your song instead.

i dont understand how to do it i got it when you press 6969 it changes to the easter egg but how do i do the song stuff?
