### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by KFC-Chicken-1212** [ShadowMario/FNF-PsychEngine#1727]
### Describe your bug here.

the game just won't compile 
![image](https://user-images.githubusercontent.com/89538185/144736618-58ab68ee-0ff7-4713-9d70-9c9891befedd.png)

### Command Prompt/Terminal logs (if existing)

```bash
lime test html5 -release
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

i edited main.hx and credits 

(edit)
added a character

**Comment by bbpanzu** [comment]
fixing it rn
