### ISSUE TITLE
How do I add a loading screen on desktop builds?

### ISSUE THREAD

**Issue by NickPlayzGITHUB** [ShadowMario/FNF-PsychEngine#1728]
### What is your question?

How do I make it so that desktop builds of psych engine have a loading screen? Because only web builds have loading screens.

Mods like FNF: Entity have loading screens for desktop but the source code isn't available yet

**Comment by bbpanzu** [comment]
check Tricky source code

**Comment by kaysancoder** [comment]
ust delete no_preload_all on loadingstate.hx
is easy tho
but unfortunately it will be useless, since load a song wont take so much time

also if you get any error of like this, delete #end line

ERROR 1: source/loadingstate.hx:171: characters 3-7 : Expected }
![error2](https://user-images.githubusercontent.com/89194591/144768617-bdca7a5b-6c9a-4a82-ac21-7ad20df5dbde.png)

ERROR 2: source/loadingstate.hx:186: characters 2-6 : Expected }
![error1](https://user-images.githubusercontent.com/89194591/144768683-ba3e3a25-2d90-4e78-a016-3bd05ed30d87.png)

And make sure replace funkay.png with the custom one you make (the size must be 1675 x 1083)

If you have any question, go dm me in discord! (Kaysan#3035)

**Comment by Adriangamer1246** [comment]
didnt he say without the source code?

**Comment by PDL2CGamejolt** [comment]
can i do it in lua/downloaded build

**Comment by HiroMizuki** [comment]
> can i do it in lua/downloaded build

welp, actually u can't cuz u need to edit a state

**Comment by kittstone** [comment]
> just delete no_preload_all on loadingstate.hx is easy tho but unfortunately it will be useless, since load a song wont take so much time
> 
> also if you get any error of like this, delete #end line
> 
> ERROR 1: source/loadingstate.hx:171: characters 3-7 : Expected } ![error2](https://user-images.githubusercontent.com/89194591/144768617-bdca7a5b-6c9a-4a82-ac21-7ad20df5dbde.png)
> 
> ERROR 2: source/loadingstate.hx:186: characters 2-6 : Expected } ![error1](https://user-images.githubusercontent.com/89194591/144768683-ba3e3a25-2d90-4e78-a016-3bd05ed30d87.png)
> 
> And make sure replace funkay.png with the custom one you make (the size must be 1675 x 1083)
> 
> If you have any question, go dm me in discord! (Kaysan#3035)

i did what you said and it works but it just stops loading
![image](https://user-images.githubusercontent.com/85509162/147865954-9f34a211-4f7a-4cfe-bf93-28c898fe7f21.png)

**Comment by kittstone** [comment]
also it doesnt work on songs specifically

**Comment by perry389** [comment]
Bouncing when entering a preplay song

**Comment by HiroMizuki** [comment]
> Bouncing when entering a free play song "missing libraray: week 1"

check if project.xml mentions the library, cuz, in psych engine, the week 1 library doesn't exist

**Comment by SonicProYT** [comment]
> can i do it in lua/downloaded build

you cant do that, you have to edit the state

**Comment by JVGamerzbz** [comment]
> just delete no_preload_all on loadingstate.hx is easy tho but unfortunately it will be useless, since load a song wont take so much time
> 
> also if you get any error of like this, delete #end line
> 
> ERROR 1: source/loadingstate.hx:171: characters 3-7 : Expected } ![error2](https://user-images.githubusercontent.com/89194591/144768617-bdca7a5b-6c9a-4a82-ac21-7ad20df5dbde.png)
> 
> ERROR 2: source/loadingstate.hx:186: characters 2-6 : Expected } ![error1](https://user-images.githubusercontent.com/89194591/144768683-ba3e3a25-2d90-4e78-a016-3bd05ed30d87.png)
> 
> And make sure replace funkay.png with the custom one you make (the size must be 1675 x 1083)
> 
> If you have any question, go dm me in discord! (Kaysan#3035)

what line? 164 or 179?

**Comment by HiroMizuki** [comment]
> > just delete no_preload_all on loadingstate.hx is easy tho but unfortunately it will be useless, since load a song wont take so much time
> > also if you get any error of like this, delete #end line
> > ERROR 1: source/loadingstate.hx:171: characters 3-7 : Expected } ![error2](https://user-images.githubusercontent.com/89194591/144768617-bdca7a5b-6c9a-4a82-ac21-7ad20df5dbde.png)
> > ERROR 2: source/loadingstate.hx:186: characters 2-6 : Expected } ![error1](https://user-images.githubusercontent.com/89194591/144768683-ba3e3a25-2d90-4e78-a016-3bd05ed30d87.png)
> > And make sure replace funkay.png with the custom one you make (the size must be 1675 x 1083)
> > If you have any question, go dm me in discord! (Kaysan#3035)
> 
> what line? 164 or 179?

just search for #if NO_PRELOAD_ALL and #end at Loading State

**Comment by SmashingGoomba** [comment]
> > > just delete no_preload_all on loadingstate.hx is easy tho but unfortunately it will be useless, since load a song wont take so much time
> > > also if you get any error of like this, delete #end line
> > > ERROR 1: source/loadingstate.hx:171: characters 3-7 : Expected } ![error2](https://user-images.githubusercontent.com/89194591/144768617-bdca7a5b-6c9a-4a82-ac21-7ad20df5dbde.png)
> > > ERROR 2: source/loadingstate.hx:186: characters 2-6 : Expected } ![error1](https://user-images.githubusercontent.com/89194591/144768683-ba3e3a25-2d90-4e78-a016-3bd05ed30d87.png)
> > > And make sure replace funkay.png with the custom one you make (the size must be 1675 x 1083)
> > > If you have any question, go dm me in discord! (Kaysan#3035)
> > 
> > 
> > what line? 164 or 179?
> 
> just search for #if NO_PRELOAD_ALL and #end at Loading State

"just search" extremely helpful thank you

alright to not cause any more confusion, remove all of the "#if NO_PRELOAD_ALL" and "#end" lines in the script.  just get rid of both of them.

**Comment by vaasans** [comment]
give me download leak please

**Comment by HiroMizuki** [comment]
> Reference in new is

Ctrl+F exists 💀

**Comment by PrismLight** [comment]
> > Reference in new is
> 
> Ctrl+F exists 💀

THIS
IS
OLD

**Comment by HiroMizuki** [comment]
> > > Reference in new is
> > 
> > 
> > Ctrl+F exists 💀
> 
> THIS IS OLD

ik i just wanted to joke a little

**Comment by WolfyTail** [comment]
> > > > just delete no_preload_all on loadingstate.hx is easy tho but unfortunately it will be useless, since load a song wont take so much time
> > > > also if you get any error of like this, delete #end line
> > > > ERROR 1: source/loadingstate.hx:171: characters 3-7 : Expected } ![error2](https://user-images.githubusercontent.com/89194591/144768617-bdca7a5b-6c9a-4a82-ac21-7ad20df5dbde.png)
> > > > ERROR 2: source/loadingstate.hx:186: characters 2-6 : Expected } ![error1](https://user-images.githubusercontent.com/89194591/144768683-ba3e3a25-2d90-4e78-a016-3bd05ed30d87.png)
> > > > And make sure replace funkay.png with the custom one you make (the size must be 1675 x 1083)
> > > > If you have any question, go dm me in discord! (Kaysan#3035)
> > > 
> > > 
> > > what line? 164 or 179?
> > 
> > 
> > just search for #if NO_PRELOAD_ALL and #end at Loading State
> 
> "just search" extremely helpful thank you
> 
> alright to not cause any more confusion, remove all of the "#if NO_PRELOAD_ALL" and "#end" lines in the script. just get rid of both of them.

It doesn't work in 0.5.2h

**Comment by JackDoesMalwares** [comment]
> can i do it in lua/downloaded build

Yea try to search on gamebanana and paste the script
