### ISSUE TITLE
I dont know how to move multiple arrows at once

### ISSUE THREAD

**Issue by BL0KYBL0K** [ShadowMario/FNF-PsychEngine#1729]
### Describe your problem here.

im trying to make all the notes spin at the same time link in sonic .exe
but only one of the arrows spin how do i make multiple move at the same curstep
heres the code :
`function onStepHit()

    if curStep == 14 then
 
        noteTweenAngle('NoteSpin', 4, 360, 0.5, "circInOut");
        
    end

    if curStep == 14 then
 
        noteTweenAngle('NoteSpin', 5, 360, 0.5, "circInOut");
        
    end

    if curStep == 14 then
 
        noteTweenAngle('NoteSpin', 6, -360, 0.5, "circInOut");
        
    end

    if curStep == 14 then
 
        noteTweenAngle('NoteSpin', 7, -360, 0.5, "circInOut");
        
    end`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a extra difficulty changed credits added weeks songs characters alot of stuff

**Comment by BL0KYBL0K** [comment]
only the right one rotates 
![image](https://user-images.githubusercontent.com/88749184/144739703-947050f6-f3b8-4c96-ab34-3816cfd3cb12.png)

**Comment by TaoTheBlock** [comment]
Use this:

function onStepHit()
     if curStep == 14 then
          noteTweenAngle('1', 4, 360, 0.5, "circInOut");
          noteTweenAngle('2', 5, 360, 0.5, "circInOut");
          noteTweenAngle('3', 6, 360, 0.5, "circInOut");
          noteTweenAngle('4', 7, 360, 0.5, "circInOut");
     end
end

**Comment by SrtHero278** [comment]
> 

I'd say the same thing. If two tweens with the same tag executes at the same time, the more recent one cancels out the other ones,

**Comment by BL0KYBL0K** [comment]
> > Use this:
> > function onStepHit() if curStep == 14 then noteTweenAngle('1', 4, 360, 0.5, "circInOut"); noteTweenAngle('2', 5, 360, 0.5, "circInOut"); noteTweenAngle('3', 6, 360, 0.5, "circInOut"); noteTweenAngle('4', 7, 360, 0.5, "circInOut"); end end
> 
> I'd say the same thing. If two tweens with the same tag executes at the same time, the more recent one cancels out the other ones,

yea that worked thanks
