### ISSUE TITLE
Boyfriend

### ISSUE THREAD

**Issue by 4wdthinks** [ShadowMario/FNF-PsychEngine#1732]
### What is your question?

Why is the boyfriend sprites seperated from the rest of the characters?

**Comment by Mokona5901** [comment]
Maybe because it's the only "official" playable character

**Comment by meeptey2** [comment]
> Maybe because it's the only "official" playable character

What about Pico though? Sure he has no death sprites, but he and BF are the only characters with miss sprites.

**Comment by BTABray** [comment]
if i had to guess it's because he's in every song (with the exceptions of week 4, 5, and 6 boyfriend)

**Comment by bbpanzu** [comment]
it's preloaded because he appears in the options menu

**Comment by ShadowMario** [comment]
> it's preloaded because he appears in the options menu

^
I've made it separate so that HTML5 wouldn't need to go to a loading screen for loading the options, although at this point it's now an outdated thing considering that i've removed week#_high folders a long time ago.
