### ISSUE TITLE
How to make space to dodge

### ISSUE THREAD

**Issue by KGAMERDEV** [ShadowMario/FNF-PsychEngine#1735]
### What is your question?

i need make my mod, how to make space to dodge!!! with source or no source!!!

**Comment by meeptey2** [comment]
# Source Code
I recommend you use the accept code with a bit of modification in Controls, CoolUtil, and OptionsState.hx
Then check if the player is dodging in PlayState.hx
# Lua
Check if the space key is pressed with `getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SPACE');`

**Comment by KGAMERDEV** [comment]
i dont understand

**Comment by KGAMERDEV** [comment]
pls give me a complete code!!!

**Comment by bbpanzu** [comment]
```
if keyJustPressed('space') then
     characterPlayAnimation('bf','dodge')
end
```

**Comment by ShadowMario** [comment]
> pls give me a complete code!!!

No.
