### ISSUE TITLE
sometimes the anti-mash hits in when im using the new input (ghost tapping)

### ISSUE THREAD

**Issue by Luchen10** [ShadowMario/FNF-PsychEngine#1738]
### Describe your bug here.

i was playing a mod in the psych engine (tricky mod) and i got a miss for pressing the notes too fast but there wasn't any notes coming, then i saw that the anti-mash still works with ghost tapping turned on, its just sometimes that happens but still it messes my full combo

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

not really

**Comment by JadenMudge** [comment]
that's....

suppose to happen...
