### ISSUE TITLE
Can someone explain pack.json to me?

### ISSUE THREAD

**Issue by WizardMantis441** [ShadowMario/FNF-PsychEngine#1742]
### Describe your problem here.

In Psych Engine 0.5 (Prerelease) there was a huge modloader system, but I can't seem to add a description (and i haven't started with the png)

![image](https://user-images.githubusercontent.com/77557487/144756932-b43686bc-d454-4a9a-bcac-19fd5bb56fca.png)

Is there a tutorial somewhere on setting up the pack.json/png?
or can someone explain what to put where and what i'm missing?
(also I have this in my modsList.txt)
![image](https://user-images.githubusercontent.com/77557487/144756956-9208f47b-d691-4edf-a905-c757a016dd3c.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

wouldnt even call it lua

**Comment by WizardMantis441** [comment]
file locations:

modsList.txt : next to the EXE file.
pack.json : Psych/mods/mod-name/**here**

**Comment by mayo78** [comment]
it doesnt work yet, it should be fixed in the full release, putting pack.png in the mod directory works though

**Comment by ShadowMario** [comment]
I've stated before that pack.json is bugged on the prerelease build.
