### ISSUE TITLE
150 x 150 character icons do not work as they should (0.5b)

### ISSUE THREAD

**Issue by WaldenMD** [ShadowMario/FNF-PsychEngine#1745]
### I was passing a mod to the new version 0.5b but I saw that the icons of the characters that are 150 x 150 do not work well

**here the deferences between version 0.4.2 and 0.5b**

![PsychEngine 2021-12-05 14-16-27-808](https://user-images.githubusercontent.com/95152456/144759295-fab3421e-ec5c-4f2a-9b7e-a95cac3caf3a.png)
![PsychEngine 2021-12-05 14-24-18-049](https://user-images.githubusercontent.com/95152456/144759293-7c80f4f2-c53e-4dea-96ed-a460a77367af.png)

**Playing in version 0.4.2**

![PsychEngine 2021-12-05 14-22-20-580](https://user-images.githubusercontent.com/95152456/144759326-e72b55b7-350b-464b-8ee1-c67ef6f19a0c.png)

**Playing in version 0.5b**

![PsychEngine 2021-12-05 14-25-16-879](https://user-images.githubusercontent.com/95152456/144759332-fb1c694d-24da-40ab-aed1-dbbd9b46f351.png)
![PsychEngine 2021-12-05 14-24-36-920](https://user-images.githubusercontent.com/95152456/144759336-103cfc7c-0c60-40c6-93c6-bca8a6bdbe66.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

do not change anything just pass a mod to version 0.5b of P E.

**Comment by SrtHero278** [comment]
I think it's the new split system.

**Comment by ShadowMario** [comment]
This is not a bug, that's how it is supposed to work, there's a losing icon on the right and a normal icon on left.
Stop being lazy and just duplicate your own icon.
If you tried to load a 150x150 icon on older versions, your game would have crashed.

> I think it's the new split system.

It's nothing new.

**Comment by THOBY555** [comment]
Lmao its should be 300x150
