### ISSUE TITLE
Bpm change crashes for me.

### ISSUE THREAD

**Issue by CHIP-YT** [ShadowMario/FNF-PsychEngine#1746]
### Describe your bug here.

When I put in a bpm change in my song, the game would crash after hitting a note after the bpm change.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, all i did so far was add a new character and a song.

**Comment by ShadowMario** [comment]
It is most likely that it's an issue with your chart, but i will need more information.
