### ISSUE TITLE
Note Colors menu scrolls down to 9

### ISSUE THREAD

**Issue by Gui-iago** [ShadowMario/FNF-PsychEngine#1747]
### Describe your bug here.

https://user-images.githubusercontent.com/45212377/144760207-ad6c28a8-8c56-4fe5-85b1-f30d29480f78.mp4

another bug that I simply felt like reporting

EDIT: I only tested that on linux since I don't own a Mac myself, or have a Windows PC laying around, but as far as I can tell, this bug doesn't exist on Windows

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by bbpanzu** [comment]
will fix

**Comment by ShadowMario** [comment]
I couldn't recreate this bug on Windows/HTML5.

**Comment by ShadowMario** [comment]
Does it still happen in the newest source build?

**Comment by Gui-iago** [comment]
> Does it still happen in the newest source build? 

@ShadowMario 
yes, I only tested that on linux since I don't own a Mac myself, or have a Windows PC laying around, but as far as I can tell, this bug doesn't exist on Windows

**Comment by ShadowMario** [comment]
Did you use any external program to open the .exe file or you compiled it yourself?

**Comment by Gui-iago** [comment]
> Did you use any external program to open the .exe file or you compiled it yourself?

I compiled it myself, Haxel version is 4.2.4 (latest at the time)

**Comment by FuroYT** [comment]
@ShadowMario he is using extra keys maybe

**Comment by ShadowMario** [comment]
If he's using extra keys then i have nothing to do with this.

**Comment by Gui-iago** [comment]
> @ShadowMario he is using extra keys maybe

no, extra keys actually has this (fixed even), for some reason after the latest update, this issue just fixed itself, so I'm closing this
