### ISSUE TITLE
Is there a way I could change the background with custom events?

### ISSUE THREAD

**Issue by TonyRonii** [ShadowMario/FNF-PsychEngine#1752]
### What is your question?

I want to do epic stuff so can someone help me make a event wherre the background changes and some base stuff to make other cool events thanks!

**Comment by TonyRonii** [comment]
Also offtopic the creator do you have a discord sever if you see this? If so is there a help thing in there?

**Comment by Stilic** [comment]
Why you don't use [the good issue template](https://github.com/ShadowMario/FNF-PsychEngine/issues/new?assignees=&labels=help+wanted&template=help.yml)?

**Comment by TonyRonii** [comment]
oops sorry i will do that know thank you!
