### ISSUE TITLE
Is there a way I could change the background with custom events?

### ISSUE THREAD

**Issue by TonyRonii** [ShadowMario/FNF-PsychEngine#1753]
### Describe your problem here.

I want to do epic stuff so can someone help me make a event wherre the background changes and some base stuff to make other cool events thanks!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no nothing this is kinda a question you could say

**Comment by Stilic** [comment]
Check [this custom event template](https://cdn.discordapp.com/attachments/840678333602857040/888568125413552168/CustomEvent.zip) maybe? (Check also the repo's wiki)

**Comment by PoleyMagik** [comment]
There is no mid song stage changes unless you like have the 2nd stage preloaded in the lua file.

**Comment by TonyRonii** [comment]
how i do that?

**Comment by TonyRonii** [comment]
i'm making a custom background for the mod soon so I need to know in advance

**Comment by bbpanzu** [comment]
code in the second background in the same lua but keep the second bg sprites invisible until you set them on

**Comment by TonyRonii** [comment]
thank you! I will try that

**Comment by DEV-idiotXD** [comment]
https://github.com/DEV-idiotXD/Psychscripts-
i made a repo with just that here take it

**Comment by TonyRonii** [comment]
it didnt work it said <eof> expected near 'end'

**Comment by DEV-idiotXD** [comment]
> it didnt work it said eof expected near 'end'

hmm imma fix it in awhile
