### ISSUE TITLE
Why an random guy show on this GitHub repository as Bbpanzu?

### ISSUE THREAD

**Issue by Stilic** [ShadowMario/FNF-PsychEngine#1754]
### What is your question?

IDK why this happen for me...
Here below some proofs if you think this is a joke:

![image](https://user-images.githubusercontent.com/63605602/144763894-1e341feb-b2ea-4e23-b8b4-dbf5a19e5324.png)
![image](https://user-images.githubusercontent.com/63605602/144764046-462dee66-ab28-4653-98ac-d7d17736bd5e.png)

**Comment by CrusherMods** [comment]
prob main/alt or something

**Comment by bbpanzu** [comment]
github desktop does it automatically

**Comment by Stilic** [comment]
> github desktop does it automatically

What do you mean by that?

**Comment by bbpanzu** [comment]
when i use github desktop it makes a bot user alanyao commit the changes

**Comment by Stilic** [comment]
> when i use github desktop it makes a bot user alanyao commit the changes

Bruh why

**Comment by WaldenMD** [comment]
alanyao best modder

**Comment by Stilic** [comment]
Fixed now bruh...

![image](https://user-images.githubusercontent.com/63605602/144886838-3022365d-4ef9-434c-a6ac-745449bddcf2.png)

**Comment by CrusherMods** [comment]
> Fixed now bruh...
> 
> ![image](https://user-images.githubusercontent.com/63605602/144886838-3022365d-4ef9-434c-a6ac-745449bddcf2.png)

thats him using github not github desktop

**Comment by Stilic** [comment]
Also @bbpanzu you may try [Visual Studio Code](https://code.visualstudio.com/). It has Git (and GitHub) integration, so you can stop using GitHub Desktop.
