### ISSUE TITLE
How i can change the gf in the title screen?

### ISSUE THREAD

**Issue by ElBendy1** [ShadowMario/FNF-PsychEngine#1755]
### Describe your problem here.

when I try to change gf with new animation and a new json file in the game I get an error window and it's says: Error invalid char 65279 at position 0
how i can fix that?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i edit CreditState.hx for the mod i'm making

**Comment by bbpanzu** [comment]
make sure you're saving the json as a UTF-8 without BOM

**Comment by PDL2CGamejolt** [comment]
> make sure you're saving the json as a UTF-8 without BOM

bbpanzu! see my latest issue

**Comment by meme286565** [comment]
how do i do so without source
