### ISSUE TITLE
botplay and practice mode removed from pause

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#1757]
### What is your question?

so in the latest update, botplay and pracitce have been moved from pause to the freeplay menu. why was this done? and if you can, could you move it back? its kinda a hassle to go back and forth, rather than just pausing and turning it on.

**Comment by MasterDirector99** [comment]
Botplay and Practice Mode is in the Freeplay Menu, just press space and you'll see it.

**Comment by ShadowMario** [comment]
I always found it silly/off that it was on the Pause menu, so i moved it to Freeplay

**Comment by MayoALT** [comment]
press space and in that menu you can toggle it
