### ISSUE TITLE
How i make a Main Menu But animated

### ISSUE THREAD

**Issue by CarptP** [ShadowMario/FNF-PsychEngine#1758]
### Describe your problem here.

So im working in a mod and i want a help with the main menu to be animated
Example : BG : Selection (Story Mode - FreePlay etc)
and nothing more

MainMenuState.hx

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes The MainMenuState.hx And PlayState.hx

**Comment by MayoALT** [comment]
add frames to the bg object

**Comment by CarptP** [comment]
> add frames to the bg object

how??

**Comment by HiroOfc** [comment]
maybe u can see at fnf lullaby's repo
but is not that hard, u just need to make a code that adds a animation to your bg
it's just a example, the code setGraphicSize is not necessary if the size of the image is 1280x720 or something close to it

you should make it at MainMenuState.hx

```
var menuBG:FlxSprite = new FlxSprite();
		menuBG.frames = Paths.getSparrowAtlas('xml and png name');
		menuBG.animation.addByPrefix('prefix', 'anim name at xml', 24, true);
		menuBG.animation.play('prefix');
		menuBG.setGraphicSize(Std.int(menuBG.width * any number if needed));
		menuBG.updateHitbox();
		add(menuBG);
```

**Comment by HiroOfc** [comment]
and for freeplay u make the same thing,

> maybe u can see at fnf lullaby's repo but is not that hard, u just need to make a code that adds a animation to your bg it's just a example, the code setGraphicSize is not necessary if the size of the image is 1280x720 or something close to it
> 
> you should make it at MainMenuState.hx
> 
> ```
> var menuBG:FlxSprite = new FlxSprite();
> menuBG.frames = Paths.getSparrowAtlas('xml and png name');
> menuBG.animation.addByPrefix('prefix', 'anim name at xml', 24, true);
> menuBG.animation.play('prefix');
> menuBG.setGraphicSize(Std.int(menuBG.width * any number if needed));
> menuBG.updateHitbox();
> add(menuBG);
> ```

and for freeplay u can make the same thing
you can make some changes if u want, like add other image or smth
if u want a color change for freeplay, is recommended that u use a desaturated bg anim
