### ISSUE TITLE
Html5 0.5 bugs

### ISSUE THREAD

**Issue by Chromebookgamerwastaken** [ShadowMario/FNF-PsychEngine#1759]
### Describe your bug here.

Ok, so i know its a pre release but its supper buggy in the html5 version, there is no mods menu at all (because it doesnt compile with the mods folder), some options menus just crash, freeplay doesnt display song names, and idk if its just my testing pc (i use this pc for testing the html5 builds) but the debug menu crashes, can somebody fix these issues plz? Its for porting reasons

### Command Prompt/Terminal logs (if existing)

```bash
Nope
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

I didnt change anything

**Comment by KFC-Chicken-1212** [comment]
i keep on getting issues on compile html5

**Comment by bbpanzu** [comment]
since you can't really mod html period, mod folders aren't compiled. but yea some crashes are just due to forgetting to compensate for the lack of a mod folder. which menus and states crash for you?

**Comment by Chromebookgamerwastaken** [comment]
Sorry if i replied late but here are the menus that crash: notes, ui and
visuals, also, blammed lights and camera shake events crash on html5,
leading to a mid song crash on blammed

**Comment by ShadowMario** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/44785097/145054147-858a2a1f-42c0-41d7-8b2a-98b3e4bff5c9.png)
Fixed.

**Comment by Chromebookgamerwastaken** [comment]
Is the camera shake also fixed? Btw the effect looks cool
