### ISSUE TITLE
Gamepad inputs are very buggy

### ISSUE THREAD

**Issue by Stilic** [ShadowMario/FNF-PsychEngine#1761]
### Describe your bug here.

On the latest source code build, the gamepad inputs are very buggy: i can only hit visible notes and can't miss when there are not notes.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by ShadowMario** [comment]
That's probably due to inputs now using OpenFL inputs for reducing input lag

**Comment by Stilic** [comment]
I have fixed it on my fork of this repo. I will do a PR later.
