### ISSUE TITLE
what

### ISSUE THREAD

**Issue by HiroOfc** [ShadowMario/FNF-PsychEngine#1765]
### Describe your bug here.

what i got is a strange error with haxe while compiling, but it seems like some new commits errors

### Command Prompt/Terminal logs (if existing)

```bash
PS C:\Users\66666\Downloads\FNF-PsychEngine-main (1)\FNF-PsychEngine-main>  lime test windows
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:11: characters 8-37 : Type not found : flixel.util.FlxDirectionFlags
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:484: characters 21-25 : Unknown identifier : WALL
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:504: characters 21-25 : Unknown identifier : WALL
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:530: characters 21-28 : Unknown identifier : CEILING
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:550: characters 21-26 : Unknown identifier : FLOOR
source/StoryMenuState.hx:323: characters 12-17 : Warning : Dynamic
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MayoALT** [comment]
use the source code from the pre-release

**Comment by HiroOfc** [comment]
> use the source code from the pre-release

but i'm using it

**Comment by HiroOfc** [comment]
wait i think i'm using main, i'll try 0.5b

**Comment by Stilic** [comment]
You can still use the code from main. Just make sure to have the latest version of HaxeFlixel (because the FlxDirections thing is really new as I see):
```bash
# run this in the game folder with cmd
haxelib update flixel
```

**Comment by HiroOfc** [comment]
> You can still use the code from main. Just make sure to have the latest version of HaxeFlixel (because the FlxDirections thing is really new as I see):
> 
> ```shell
> # run these commands in the game folder with cmd
> haxelib update flixel
> haxelib update flixel-addons
> ```

oh yea boi
thanks
