### ISSUE TITLE
Background Events stop justPressed bf Animation

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#177]
Hi,
So as stated in the title, Background events stop the Boyfriend Animations when I pressed a key to play the animation.
Here's an example
![EventBug](https://user-images.githubusercontent.com/87707926/135275583-27511f02-f8eb-44b3-8549-612d9ed5a8ae.gif)

As you can see even the lights in the buildings stop the animation.
Is there anyway to fix this?
Thanks in Advance.

**Comment by ShadowMario** [comment]
boyfriend.specialAnim = true;
