### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by IAMEC123** [ShadowMario/FNF-PsychEngine#1770]
### Describe your bug here.

when i put my char into a song and play the actual song it just crashes each time. its starting to get annoying.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i added my own character into the engine

**Comment by SrtHero278** [comment]
Make sure you added it into `mods`. Also make sure your character image path is going the right direction.

**Comment by ShadowMario** [comment]
You might've put it in the wrong folders or your XML file is broken, we will need more information.

**Comment by IAMEC123** [comment]
![image_2021-12-08_192016](https://user-images.githubusercontent.com/95647250/145317016-4d7a1b3b-4f1b-48f2-8d66-16a7d07aab09.png)
im using the correct files from a different mod and they are working fine. i also switched the character out with pico and it works fine but with the dude it doesnt. this is all i can really give you rn

**Comment by NotEpik** [comment]
this probably about JSON of the character

**Comment by IAMEC123** [comment]
well it worked just fine in the character editor so i dont think its that

**Comment by ShadowMario** [comment]
Sounds like this issue is too specific for you, so i'd say you should pack the files and send me it.

**Comment by IAMEC123** [comment]
it only works when i use the change character event sorry everyone 😅
