### ISSUE TITLE
Icons in Freeplay work like they do in-game if you can listen to it

### ISSUE THREAD

**Issue by CrusherMods** [ShadowMario/FNF-PsychEngine#1773]
### What feature do you want to get added on the base engine?

If just listening to a song in freeplay comes back you should add a feature while listening to a song the icons will bump (I dont know how to put this lmao) to the way it is in-game, Like literally every request this is optional

(I bet your gonna come and say no ShadowMario lmao)

**Comment by bbpanzu** [comment]
no ShadowMario lmao

i might. seems cool

**Comment by IdioticLuke** [comment]
no way bbpanzu real???!?!?
im big fan!!1111111111111
