### ISSUE TITLE
Input issue

### ISSUE THREAD

**Issue by PhxR3d** [ShadowMario/FNF-PsychEngine#1774]
### Describe your bug here.

If you miss a note and press another direction (with ghost tapping enabled) it will count as 2 misses for some reason.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't edit anything. I was using the 0.5 prerelease build.

**Comment by CrusherMods** [comment]
If you press 2 note at the same time?

**Comment by PhxR3d** [comment]
> 

If you miss a note and press another button right after.

**Comment by PhxR3d** [comment]
So say you miss an up note and press left right after. It'll count as two misses even though you only missed one note.

**Comment by ShadowMario** [comment]
???
Isn't that how Psych's ghost tapping is supposed to work? You are able to miss ONLY when there's notes near the strum arrows.

**Comment by PhxR3d** [comment]
Wait really? I didn't know it worked like that. I thought it only allowed you to miss if you didn't hit a note.
