### ISSUE TITLE
Different note-confirm animation

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#1778]
### What needs to be documented?

Hi,
so I would appreciate it if  "how to add  a new note-confirm animation" will be documented.
Since it isn't that much to code (12 lines of code) it would probably not take much time to add the documentation correct me if I'm wrong.
The code would be
StrumNote.hx:
```
case 0:
        animation.addByPrefix('static', 'arrowLEFT');
	animation.addByPrefix('pressed', 'left press', 24, false);
	animation.addByPrefix('confirm', 'left confirm', 24, false);
        animation.addByPrefix('confirm2', 'right confirm', 24, false);
```
This would just need to be done with every case and the pixel note.

`
if(animation.curAnim.name == 'confirm' || animation.curAnim.name == 'confirm2' && !PlayState.isPixelStage) {`

PlayState.hx:
`if(spr != null && spr.animation.curAnim.name != 'confirm' && spr.animation.curAnim.name != 'confirm2')`

```
if (Math.abs(note.noteData) == spr.ID)
					{
						spr.playAnim('confirm', true);
						if (note.noteType == 'Hey!') spr.playAnim('confirm2', true);
					}
				});
```

**Comment by ShadowMario** [comment]
I'm not gonna document this.
