### ISSUE TITLE
fixed

### ISSUE THREAD

**Issue by Adriangamer1246** [ShadowMario/FNF-PsychEngine#1779]
### Describe your bug here.

some songs have dads icons and do not want to change even if your in-game (playing the song) character has a different icon

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added the songs, and i added the "freeplaysonglist.txt" or something like that

**Comment by CrusherMods** [comment]
You have to go change the icon yourself in your json file

**Comment by Adriangamer1246** [comment]
the char

> You have to go change the icon yourself in your json file

the characters im using have their own icons in-game but in the freeplay list it shows the dad icon wich i deleted

**Comment by Adriangamer1246** [comment]
![Screenshot (46)](https://user-images.githubusercontent.com/58314609/144934178-6ac4c374-468f-4ac7-830c-7a8028aa1285.png)
![Screenshot (47)](https://user-images.githubusercontent.com/58314609/144934208-bec96830-4e5c-4af0-9cb1-b4cd8271c029.png)
