### ISSUE TITLE
game crashes on selection of my modded character

### ISSUE THREAD

**Issue by ceruuphi** [ShadowMario/FNF-PsychEngine#178]
i don't know why this happens, i just select my character in the chart editor and the game closes, maybe because i don't have an icon for my character, i don't know

**Comment by ShadowMario** [comment]
Need more information: What's the last thing you see when it crashes?

**Comment by ceruuphi** [comment]
> 
> 
> Need more information: What's the last thing you see when it crashes?

the last thing i see is the black screen that shows after you press enter to test the chart to signify loading, then it either freezes there or crashes, but nothing ever happens after that

**Comment by TheMicroondas** [comment]
Maybe you're not configuring correctly your character, check if the animations names in the json file of your character are correct

**Comment by ceruuphi** [comment]
> 
> 
> Maybe you're not configuring correctly your character, check if the animations names in the json file of your character are correct

turns out i was right and it was the fact that i added no icon, since i used a placeholder icon and then it started working, so that's neat

alright bye guys
