### ISSUE TITLE
credits document

### ISSUE THREAD

**Issue by Adriangamer1246** [ShadowMario/FNF-PsychEngine#1785]
### What is your question?

where do i put the credits.txt file?
example: psychengine\assets\

**Comment by CrusherMods** [comment]
mods/data

**Comment by Adriangamer1246** [comment]
not working

**Comment by bbpanzu** [comment]
did you format the credits correctly?

**Comment by Adriangamer1246** [comment]
yeah

**Comment by Adriangamer1246** [comment]
i put:
mod
schwifty::schwifty::coder, charter and animator::my twitter page::0xFFFFDD33

**Comment by bbpanzu** [comment]
did you make sure your mod was loaded first

**Comment by Adriangamer1246** [comment]
wdym

**Comment by bbpanzu** [comment]
if it's not showing up, your mod directory probably isn't loaded in yet. in your mod's pack.json set "restart" to true

**Comment by Adriangamer1246** [comment]
what json

**Comment by Adriangamer1246** [comment]
well im not using 0.5 cuz its really buggy for me the mod doesnt even want to load

**Comment by Adriangamer1246** [comment]
even if i set restart to true
