### ISSUE TITLE
Game Crash when I press Title Screen By NEW Updates

### ISSUE THREAD

**Issue by afeefflox** [ShadowMario/FNF-PsychEngine#1789]
### Describe your bug here.

So, Idk What to do :/ I cannot play latest Updates because its SAME BUG 

### Command Prompt/Terminal logs (if existing)

Nothing

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

**Comment by ShadowMario** [comment]
You will have to show the code for what exactly did you change or show me the crash log on the command prompt/terminal.

**Comment by afeefflox** [comment]
I think this On
![Sort](https://user-images.githubusercontent.com/83808420/145114724-072cfe51-a20a-46e1-882d-1f2f6cacff7a.PNG)

**Comment by Collabvmisgood** [comment]
that's just ram error

**Comment by afeefflox** [comment]
:/ I know But IDK How Fixed

**Comment by bbpanzu** [comment]
allocate more memory on your PC

**Comment by afeefflox** [comment]
:/ I did already but still the game is Crash

**Comment by ShadowMario** [comment]
Should be fixed now, if not, your PC still lacks memory for FNF.
