### ISSUE TITLE
Psych Engine Crashed

### ISSUE THREAD

**Issue by barbbarain** [ShadowMario/FNF-PsychEngine#1791]
### Describe your bug here.

After I added my new character then I went to Freeplay, then it crashes, why this happens everytime?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added my new character in mod\characters, and other

**Comment by ShadowMario** [comment]
Need more information: Where did you drop your files? Can you screenshot how your mods/characters/ and mods/images/characters/ folders look like?

**Comment by barbbarain** [comment]
> Need more information: Where did you drop your files? Can you screenshot how your mods/characters/ and mods/images/characters/ folders look like?

![image](https://user-images.githubusercontent.com/68548511/145071942-aa3907c9-ef7b-4936-a731-1ea6bc88859e.png)
![image](https://user-images.githubusercontent.com/68548511/145072042-abb91521-0e15-4b9d-9b16-0a171ca06077.png)

**Comment by NotEpik** [comment]
did you add a new stage if yes please check because I did it and the game crash like 10 times and then I think why did my song crashed, after checking for a while. I know that the stage has a big error because I add the camera following the note. if you didn't add it. Idk either

**Comment by ShadowMario** [comment]
Could you send the json files for the characters?

**Comment by barbbarain** [comment]
@ShadowMario my new character is just the red ball, but ok. am I going to send it as a zip or what?

**Comment by ShadowMario** [comment]
Yeah

**Comment by barbbarain** [comment]
[weirdboi404.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/7711002/weirdboi404.zip)
it's here.

**Comment by ShadowMario** [comment]
Forgot about this, still having this issue?

**Comment by barbbarain** [comment]
Yup, still having this kind of issue

**Comment by ShadowMario** [comment]
Rename "staring" animation to "idle".

If it still crashes, then your .XML file is the issue.
