### ISSUE TITLE
Remove achievements

### ISSUE THREAD

**Issue by WolfyTail** [ShadowMario/FNF-PsychEngine#1794]
### What is your question?

Hello, I'm building a mod and I would like to remove the default achievements. I tried to simply delete them from Achievements.hx but they still appearing.  How could I remove them?

**Comment by MayoALT** [comment]
in project.xml theres an option for that

**Comment by WolfyTail** [comment]
> in project.xml theres an option for that

No, I wanna delete only the default ones, because I want to add **my own** achievements.

**Comment by ShadowMario** [comment]
Uhh editing Achievements.hx is literally the way you change which achievements should pop up though? Check if you've opened the correct recompiled build.
