### ISSUE TITLE
I wanna add a jumpscare

### ISSUE THREAD

**Issue by CaulHere** [ShadowMario/FNF-PsychEngine#1795]
### Describe your problem here.

I wanna add a mid song jumpscare and I don't know how

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by FartMaster57** [comment]
You would probably need to make a custom event like how in week 6 there's the girls in the background that appear

**Comment by CaulHere** [comment]
I'll try

**Comment by NotEpik** [comment]
add a new image that you want to use for jumpscare in the custom stage[you need it] and use this change 'curStep' to anything you want and another 'curStep' to the first 'curStep + 1' and set 'filename' to the image you want to use
```
function onStepHit()
	if curStep == 10 then
		setProperty('filename.visible', true);
	elseif curStep == 11 then
		setProperty('filename.visible', true);
	end
end
```
I recommended using an animated image like when you want jumpscare to show use the play function and then after it plays at the end of the animation frame it disappears like this but you also need an XML
```
function onCreate()
	makeAnimatedLuaSprite('scare', 'jumpscarethinganimated', -600, -300);
	luaSpriteAddAnimationByPrefix('scare', 'jumpscare', 'jumpscarelol', 24, false);
	setLuaSpriteScrollFactor('scare', 1, 1);
end

function onStepHit()
	if curStep == 10 then
		luaSpritePlayAnimation('scare', 'jumpscare', true);
	end
end
```

**Comment by CaulHere** [comment]
Thank you so much man
