### ISSUE TITLE
Idk if this is a bug or not

### ISSUE THREAD

**Issue by haha-username-go-brrrrrrr** [ShadowMario/FNF-PsychEngine#1800]
### Describe your bug here.

So the achievement hold a note for 20 seconds won't work, on a earlier version (v0.4.1) It just gave me the achievement and idk how bc I hold a note for more than 20 seconds in other songs but on this one song (forgot what is was) it just gave me it, but since my achievements restarted for some reason and now I gotta do it again and Idk how, please fix or someone help me  

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by lemz1** [comment]
It isn't really a bug but it is weird.
with holding down a note isn't meant hitting the long notes
it means not letting go of the button that you used to hit the note, so it stays in the hit animation but if your character switches to any other animation it will not be counted.
So to get the achievment fast- just clear all notes in a chart (I suggest pico) and add a note then play the chart and hold down the button (boyfriend should then be in his sing position) after 20 seconds you should get the achivement
I don't know if this was changed in the pre-release 0.5 version.

**Comment by ShadowMario** [comment]
The time holding it was decreased to 10s.
The issue is that i changed how note missing works so that it would also play the missing animations, which would reset the timer for the achievement.

I've tested it and the achievement is now possible again (Dad Battle, Hard)
