### ISSUE TITLE
Changing the Hurt Note's texture in Source crashes the game when the note's pressed.

### ISSUE THREAD

**Issue by Itz-Miles** [ShadowMario/FNF-PsychEngine#1801]
### Describe your problem here.

I wanted to make a custom note over the Hurt Note, but only hitting a sustain note will remove health; hitting the note itself will crash the engine.

Hurt code that pertains to this:

                                                 Note.hx

                                        case 'Wither Note':
					ignoreNote = mustPress;
					reloadNote('WITHER');
					noteSplashTexture = 'WITHERnoteSplashes';
					colorSwap.hue = 0;
					colorSwap.saturation = 0;
					colorSwap.brightness = 0;
					if(isSustainNote) {
						missHealth = 0.1;
					} else {
						missHealth = 0.1;
					}

                                              PlayState.hx

				switch(note.noteType) {
					case 'Wither Note': //Hurt note
						if(boyfriend.animation.getByName('hurt') != null) {
							boyfriend.playAnim('hurt', true);
							boyfriend.specialAnim = true;
						}
				}
				
				note.wasGoodHit = true;
				if (!note.isSustainNote)
				{
					note.kill();
					notes.remove(note, true);
					note.destroy();
				}
				return;

                                     ChartingState.hx

                                     'Wither Note',

Assets for Wither Notes are in the same location as the Hurt Notes.

https://user-images.githubusercontent.com/95124554/145084362-ba596b17-ad61-45fe-b26c-901b8f0c88da.mp4

			

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited code pertaining to the note's texture location and properties

**Comment by Itz-Miles** [comment]
From what I've seen debugging it's not able to read a location pertaining to the note. (Unhandled exception at 0x00007FF73AA2BD65 in PsychEngine.exe: 0xC0000005: Access violation reading location 0x0000000000000008.)

**Comment by Itz-Miles** [comment]
I forgot to change HURTnoteSplashes to WITHERnoteSplashes LOLLLLLLL

**Comment by lemz1** [comment]
maybe you used wrong names in the xml for the noteSplashes.
This results in a crash.
