### ISSUE TITLE
Some errors in export

### ISSUE THREAD

**Issue by KGAMERDEV** [ShadowMario/FNF-PsychEngine#1803]
### Describe your problem here.

I when I export, it always gives a lot of errors. But if I solve them in another error and so on

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MayoALT** [comment]
what are the errors

**Comment by KGAMERDEV** [comment]
301 errors

**Comment by KGAMERDEV** [comment]
some errors have disappeared, only one:source/StoryMenuState.hx:36: characters 3-7 : Expected , or
