### ISSUE TITLE
source/StoryMenuState.hx:36: characters 3-7 : Expected , or

### ISSUE THREAD

**Issue by KGAMERDEV** [ShadowMario/FNF-PsychEngine#1807]
### Describe your problem here.

some errors have disappeared, only one:source/StoryMenuState.hx:36: characters 3-7 : Expected , or

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by SrtHero278** [comment]
Can we see line 36 of StoryMenuState?
I think it's modified code bc it works for me.

**Comment by KGAMERDEV** [comment]
i dont understand

**Comment by MayoALT** [comment]
show the code

**Comment by KGAMERDEV** [comment]
what code

**Comment by ShadowMario** [comment]
> Can we see line 36 of StoryMenuState?

This code.
Show the lines 30 to 40 of StoryMenuState.hx
