### ISSUE TITLE
How do I make a warning note?

### ISSUE THREAD

**Issue by FartMaster57** [ShadowMario/FNF-PsychEngine#1808]
### Describe your problem here.

I wanna make a warning note where bf does the dodge animation when you hit it, and you die if you miss it, how would I do this? 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I've added a few custom characters and some songs

**Comment by IdioticLuke** [comment]
use hank accelerant notes from psych engine port

**Comment by FartMaster57** [comment]
how do I make the notes bigger?

**Comment by NotEpik** [comment]
draw the image and note get bigger or if you know how to use XML make the X and the Y bigger number
