### ISSUE TITLE
How to create custom notes?

### ISSUE THREAD

**Issue by BrightEyesFox** [ShadowMario/FNF-PsychEngine#181]
How do I create new notes? I want to create a note type that damages for more if missed.

**Comment by lemz1** [comment]
So you need to add this in the code

Note.hx:
![Screenshot (70)](https://user-images.githubusercontent.com/87707926/135495459-5a5cd948-cadb-4967-a2ad-61db8b4ebd41.png)
the = 0.1 is the damage you take when you miss

![Screenshot (73)](https://user-images.githubusercontent.com/87707926/135495547-d3f1da4a-3f45-4a42-869b-37e53f49f9a1.png)

you need to add this after the Hurt Note Statement

Playstate.hx:

![Screenshot (68)](https://user-images.githubusercontent.com/87707926/135495716-9bd8d40c-1851-4b6c-bfac-33d05933b978.png)

replace this with:

								if(!daNote.ignoreNote) {
									health -= daNote.missHealth; //For testing purposes
									songMisses++;
									vocals.volume = 0;
									RecalculateRating();

									switch (daNote.noteData % 4)
									{
										case 0:
											boyfriend.playAnim('singLEFTmiss', true);
										case 1:
											boyfriend.playAnim('singDOWNmiss', true);
										case 2:
											boyfriend.playAnim('singUPmiss', true);
										case 3:
											boyfriend.playAnim('singRIGHTmiss', true);
									}
									callOnLuas('noteMiss', [notes.members.indexOf(daNote), daNote.noteData, daNote.noteType, daNote.isSustainNote]);
								}

								if(daNote.noignoreNote) {
									health -= daNote.oofmissHealth; 
									vocals.volume = 0;
									RecalculateRating();

									switch (daNote.noteData % 4)
									{
										case 0:
											boyfriend.playAnim('singLEFTmiss', true);
										case 1:
											boyfriend.playAnim('singDOWNmiss', true);
										case 2:
											boyfriend.playAnim('singUPmiss', true);
										case 3:
											boyfriend.playAnim('singRIGHTmiss', true);
									}
									callOnLuas('noteMiss', [notes.members.indexOf(daNote), daNote.noteData, daNote.noteType, daNote.isSustainNote]);
								}
							
						
					
								if(daNote.noignoreNote) {
									health -= daNote.hitHealth; 
									vocals.volume = 0;
									RecalculateRating();

									switch (daNote.noteData % 4)
									{
										case 0:
											boyfriend.playAnim('singLEFT', true);
										case 1:
											boyfriend.playAnim('singDOWN', true);
										case 2:
											boyfriend.playAnim('singUP', true);
										case 3:
											boyfriend.playAnim('singRIGHT', true);
									}
									callOnLuas('goodNoteHit', [notes.members.indexOf(daNote), daNote.noteData, daNote.noteType, daNote.isSustainNote]);
								}
							}
						}
					}

ChartingState.hx:

![Screenshot (74)](https://user-images.githubusercontent.com/87707926/135496284-993c048e-92c8-4a0d-93cd-af24b5dabaff.png)

don't forget to put a "," after 'Hurt Note'

also if you don't have assets for the notes, you can download these note assets and put them in the shared folder.

https://drive.google.com/file/d/1HaB1TLAyObddcKEXwfpKdlmLvmr9sv65/view?usp=sharing

![Screenshot (72)](https://user-images.githubusercontent.com/87707926/135496604-cc2cce70-a651-4f5a-9f4e-e16bb852152a.png)

**Comment by lemz1** [comment]
So you need to add this in the code

Note.hx:
![Screenshot (70)](https://user-images.githubusercontent.com/87707926/135495459-5a5cd948-cadb-4967-a2ad-61db8b4ebd41.png)
the = 0.1 is the damage you take when you miss

![Screenshot (73)](https://user-images.githubusercontent.com/87707926/135495547-d3f1da4a-3f45-4a42-869b-37e53f49f9a1.png)

you need to add this after the Hurt Note Statement

Playstate.hx:

![Screenshot (68)](https://user-images.githubusercontent.com/87707926/135495716-9bd8d40c-1851-4b6c-bfac-33d05933b978.png)

replace this with:

                                                                if(!daNote.ignoreNote && !daNote.noignoreNote) {
								health -= daNote.missHealth; //For testing purposes
								songMisses++;
								vocals.volume = 0;
								RecalculateRating();

								switch (daNote.noteData % 4)
								{
									case 0:
										boyfriend.playAnim('singLEFTmiss', true);
									case 1:
										boyfriend.playAnim('singDOWNmiss', true);
									case 2:
										boyfriend.playAnim('singUPmiss', true);
									case 3:
										boyfriend.playAnim('singRIGHTmiss', true);
								}
								callOnLuas('noteMiss', [notes.members.indexOf(daNote), daNote.noteData, daNote.noteType, daNote.isSustainNote]);
							}

								if(daNote.noignoreNote) {
								health -= daNote.oofmissHealth; 
								songMisses++;
								vocals.volume = 0;
								RecalculateRating();

								switch (daNote.noteData % 4)
								{
									case 0:
										boyfriend.playAnim('singLEFTmiss', true);
									case 1:
										boyfriend.playAnim('singDOWNmiss', true);
									case 2:
										boyfriend.playAnim('singUPmiss', true);
									case 3:
										boyfriend.playAnim('singRIGHTmiss', true);		
								}
								callOnLuas('noteMiss', [notes.members.indexOf(daNote), daNote.noteData, daNote.noteType, daNote.isSustainNote]);
							}
						}
					}
				}					

ChartingState.hx:

![Screenshot (74)](https://user-images.githubusercontent.com/87707926/135496284-993c048e-92c8-4a0d-93cd-af24b5dabaff.png)

don't forget to put a "," after 'Hurt Note'

also if you don't have assets for the notes, you can download these note assets and put them in the shared folder.

https://drive.google.com/file/d/1HaB1TLAyObddcKEXwfpKdlmLvmr9sv65/view?usp=sharing

![Screenshot (72)](https://user-images.githubusercontent.com/87707926/135496604-cc2cce70-a651-4f5a-9f4e-e16bb852152a.png)

**Comment by BrightEyesFox** [comment]
Everything seems to work, except for the assets. They work, it's just that in-game they become tiny for some reason.
![image](https://user-images.githubusercontent.com/91453227/135650762-4b2bee3e-2bb2-4156-97e6-db6bd9bb427e.png)

**Comment by BrightEyesFox** [comment]
OK, nvm, it gets fixed after saving the chart, thank you so much for helping me with this! You saved my mod!

**Comment by lemz1** [comment]
Can you show me the note assets you use and code where they are loaded

**Comment by lemz1** [comment]
Also in the code with the if(daNote.noignore thingy you have to remove ++songmisses and vocalsvolume 0

**Comment by lemz1** [comment]
if you read the message i posted after you closed the issue (the one with add ++songMisses)don't worry about this got the persons mixed up
