### ISSUE TITLE
How to hide hud and then renable it in a mid song

### ISSUE THREAD

**Issue by IdioticLuke** [ShadowMario/FNF-PsychEngine#1811]
### Describe your problem here.

so you can do one of those cool mid animation songs
like here

https://user-images.githubusercontent.com/94558103/145112990-caf344ec-d71c-4d7e-a725-6750ae7fd309.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by PDL2CGamejolt** [comment]
idk

**Comment by SrtHero278** [comment]
try using `setPropety('camHUD.visible', true or false);`

**Comment by IdioticLuke** [comment]
Will do.

**Comment by NotEpik** [comment]
guess you need source because idk about lua

**Comment by THOBY555** [comment]
Go to chart menu to know what is the right step to  use it on then Add Lua Script on Chart Folder 
```
function onStepHit()
if curStep == 300 then - - here you should press 7 mid song and search for ur moment step and put the steps number
try using setProperty('camHUD.visible', false);

if curStep == 400 then - - idk what is the steps lmao
 setProperty('camHUD.visible', true) ;
end

**Comment by THOBY555** [comment]
> guess you need source because idk about lua

Fuckkdv uhh fjjrhfhjfjfjtk
U dont need fucking source code its sooooo fucking simple lmao lol idfk what im doing but i think cuz im gud at this Lua api

**Comment by IdioticLuke** [comment]
Ok I will try it

**Comment by IdioticLuke** [comment]
![image](https://user-images.githubusercontent.com/94558103/145232853-6200a88c-d0cd-4e3d-b952-a3bbaf0a6185.png)

**Comment by IdioticLuke** [comment]
When I remove the comments I then get this error; 
![image](https://user-images.githubusercontent.com/94558103/145233153-345b0a87-a620-4983-acfd-6a0a7f337fb8.png)

**Comment by CrusherMods** [comment]
> When I remove the comments I then get this error; ![image](https://user-images.githubusercontent.com/94558103/145233153-345b0a87-a620-4983-acfd-6a0a7f337fb8.png)

you need to put an "end" somewhere

**Comment by IdioticLuke** [comment]
Just did that

**Comment by IdioticLuke** [comment]
Added end to line 1 and 2 and now this happens
![image](https://user-images.githubusercontent.com/94558103/145233569-f0d5a552-4935-44b6-b97d-478815048661.png)

**Comment by IdioticLuke** [comment]
**help**

**Comment by PDL2CGamejolt** [comment]
uh

**Comment by IdioticLuke** [comment]
don't just comment "uh" or "idk" it contributes nothing to this

**Comment by PDL2CGamejolt** [comment]
> don't just comment "uh" or "idk" it contributes nothing to this

ok

**Comment by IdioticLuke** [comment]
I have tried everything, followed all errors and the code simply doesn't work. I seriously have no idea how to fix it, and I don't know how to code lua.

**Comment by IdioticLuke** [comment]
I got help from the discord server of fnf and It actually works now.
Use

function onStepHit()
if curStep == 10 then
setProperty('camHUD.visible', false);
elseif curStep == 20 then
setProperty('camHUD.visible', true) ;
end
end

and replace the curstep (20 and 10) with the ones you want to use. (use 7 in charting and look at step) Anyway THANK YOU for giving me fixed code 
![image](https://user-images.githubusercontent.com/94558103/145286914-96c7b17a-938b-43f7-98bf-34c9fb690704.png)
