### ISSUE TITLE
Sound for custom notes

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#1812]
### Describe your problem here.

How do i make custom notes make a sound like HD Blammed note?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by SrtHero278** [comment]
try using the `playSound` command in where you use your `goodNoteHit` function happens.

**Comment by PDL2CGamejolt** [comment]
> try using the `playSound` command in where your `goodNoteHit` function happens.

i just used the script from the bullet notes from the hank challengee
