### ISSUE TITLE
Custom Hitboxes for custom notes with LUA

### ISSUE THREAD

**Issue by frantastic24** [ShadowMario/FNF-PsychEngine#1814]
### Describe your problem here.

Is there any way to change hitboxes for certain notes (mostly entire notetypes) through Lua? Or is this only possible through source code?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No edits

**Comment by IdioticLuke** [comment]
I don't think so. Pretty sure you need source code for that, but I'm not too experienced so take my statement with a grain of salt.

**Comment by ShadowMario** [comment]
Nope
