### ISSUE TITLE
Putting dialogue after a cutscene

### ISSUE THREAD

**Issue by BrandonTheGoose** [ShadowMario/FNF-PsychEngine#1821]
### What is your question?

So I recently was using psych engine and I learnt how to both do dialogue and a cutscene in songs. Although I was wondering if there was a way to have dialogue appear after a cutscene? and also if there was a way to put dialogue at the end of a song like Dave and bambi? (even though it was made in kade engine)

**Comment by IdioticLuke** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/1276
(this has already been solved)
