### ISSUE TITLE
Key input problem

### ISSUE THREAD

**Issue by MrSomethingoridk** [ShadowMario/FNF-PsychEngine#1822]
### Describe your problem here.

no basically, the function keyJustPressed is supposed to do so,something when the specifised key is pressed, but when I put this
function keyJustPressed(name)
if name == 'up' then
setProperty('health', -1);
end
end

and when I press up, nothing happens, pls help :(

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by bbpanzu** [comment]
keypressed isn't a callback. it's a function

```
if keyJustPressed('up') then
   --do a thing
end
```
