### ISSUE TITLE
removeLuaSprite doesn't clean up the image from memory?

### ISSUE THREAD

**Issue by Templarfreak** [ShadowMario/FNF-PsychEngine#1825]
### What is your question?

With `destroy` set to true, it appears something about the Lua Sprite, probably the image loaded, stays in memory, based off of the memory usage. Is this intentional?

Basically, when entering my custom stage, the memory usage, reasonably, climbs from ~300MBs to ~2GBs, but when exiting the stage, even though I destroy the Lua Sprites, the memory stays at about ~2GBs. 

Just to confirm that it's not just the sprites not being properly removed through `onDestroy`, I also tested out immediately destroying the sprites after they're created, and it does still stay at ~2GBs.

**Comment by ShadowMario** [comment]
the image file itself stays loaded in memory until you restart the song, or if you have Persistent Cached Data on, until you close your game.
