### ISSUE TITLE
lua works but dialogue dosnt

### ISSUE THREAD

**Issue by whiteninja1** [ShadowMario/FNF-PsychEngine#183]
i added the dialogue and the lua file but the dialogue dosnt appear

**Comment by ShadowMario** [comment]
Show your code and your files placement.

**Comment by FuseIsHere813** [comment]
Try adding the LUA and Dialogue JSON into **mods/data/your-song-name**

**Comment by whiteninja1** [comment]
I have done that but it didn't work 
my version is 0.4.1

**Comment by ShadowMario** [comment]
> Show your code and your files placement.

**Comment by BL0KYBL0K** [comment]
im having same error

**Comment by whiteninja1** [comment]
sorry for the late reply
my Lua file and the dialogue file are in
preload/data/songname
when I open the song in the story menu the command prompt says dialogue loaded

**Comment by whiteninja1** [comment]
![image](https://user-images.githubusercontent.com/83502458/135711890-e43fc073-e71e-4ae6-a8bf-7ade042892a1.png)
![image](https://user-images.githubusercontent.com/83502458/135712139-9c270893-0d86-4598-92d4-dde35d9708ba.png)
![image](https://user-images.githubusercontent.com/83502458/135712254-8934b249-07e9-4c50-bd0a-5fc1462dda66.png)

**Comment by whiteninja1** [comment]
i also tried this
![image](https://user-images.githubusercontent.com/83502458/135718364-47830a05-578c-4bb5-a655-ab8d93c6cecd.png)

**Comment by whiteninja1** [comment]
I'm trying to finish my mod but the dialogue didn't work

**Comment by ShadowMario** [comment]
Lua files are only loaded in mods/ folder.
On Haxe, you should make the song names lowercase, "goinslow", "speedup", "infiltration"
