### ISSUE TITLE
What directory does the stage images/pngs go??

### ISSUE THREAD

**Issue by jaekyle122** [ShadowMario/FNF-PsychEngine#184]

**Comment by ShadowMario** [comment]
On mods/ folder, use mods/images/, on assets/ folder it depends on where you want to use the image file.

If you're using the downloaded build, go to mods/ folder, if not:

If you want to use it in the main menu/before a song loads, put it in assets/preload/images/

If you want to use it in a song or something, i'd suggest assets/shared/images/
