### ISSUE TITLE
how do i make an mouse clickable menu

### ISSUE THREAD

**Issue by crashok20185** [ShadowMario/FNF-PsychEngine#1843]
### Describe your problem here.

so i wanna make an menu that with the mouse you can move with the options like when we click an option with the mouse, and yeah i know i need to use FlxG.mouse.visible = true; 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by FuseIsHere813** [comment]
Do not create issues about "How can i do X like in Y".

**Comment by crashok20185** [comment]
alr

**Comment by Emeninja** [comment]
how do you make the menu stuff mouse clickable

**Comment by DEV-idiotXD** [comment]
Just esit main menu state lmao and search up a vid on clickable buttons in haxeflixel
