### ISSUE TITLE
Looping Animated Lua Sprite?

### ISSUE THREAD

**Issue by FoxyGamer1980** [ShadowMario/FNF-PsychEngine#1845]
### Describe your problem here.

how can i make an animated lua sprite loop throughout the song or replay when a beat happens?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i'm using the official build of the mod, 0.4.2 to be exact

**Comment by ShadowMario** [comment]
https://cdn.discordapp.com/attachments/866856727621795850/900523260180049940/AnimatedLuaSpriteScript.lua

This will spawn a Dad sprite that does nothing other than bopping his head on beat to the song.
