### ISSUE TITLE
Alpha Tween

### ISSUE THREAD

**Issue by IAmAHumanToo** [ShadowMario/FNF-PsychEngine#1846]
### Describe your problem here.

I want to do an arrow alpha tween but it doesn't work.
I've tried:

0
255
#00

Help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added a new event

**Comment by ShadowMario** [comment]
Show your code.

**Comment by IAmAHumanToo** [comment]
noteTweenAlpha(tag, 6, #00, 0.5, 'circinout')

**Comment by ShadowMario** [comment]
what even is "notecomplete"?

**Comment by IAmAHumanToo** [comment]
idk it's meant to be a tag?

**Comment by IAmAHumanToo** [comment]
IDK how tags work I'm not good with lua

**Comment by ShadowMario** [comment]
The tag is meant to be a string, so for example:
`noteTweenAlpha('note0alphatween', 0, 0.5, 1, 'linear')`
^ This will call a linear moving Alpha Tween on Dad's note zero (Left note).
The tween will take 1 second to be completed, when the tween ends, the note's alpha will be 0.5 (50%)

Once the tween is concluded, it will call the function `onTweenCompleted('note0alphatween')`

**Comment by IAmAHumanToo** [comment]
So the note should be half invisible?
