### ISSUE TITLE
How to make a menu character

### ISSUE THREAD

**Issue by bf244** [ShadowMario/FNF-PsychEngine#1856]
### Describe your problem here.

How to make a menu character

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CrusherMods** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Adding-a-New-Week 😐
