### ISSUE TITLE
Lua Chart Difficulty

### ISSUE THREAD

**Issue by LeGoldenBoots** [ShadowMario/FNF-PsychEngine#1859]
### Describe your problem here.

I wanna make it so the LUA script works on only specific difficulties, but it doesn't seem to change no matter how much I edit the source code. Help?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

**Comment by ShadowMario** [comment]
You can use this inside your lua script:
```lua
if difficulty == 2 then --Hard
    -- Put your code that should work run in Hard difficulty here!
end
```
0 = Easy, 1 = Normal, 2 = Hard.
