### ISSUE TITLE
Camera Follow for Source?

### ISSUE THREAD

**Issue by NickPlayzGITHUB** [ShadowMario/FNF-PsychEngine#1864]
### What is your question?

On this github people have made Camera following lua scripts. The scripts that make it so that the camera moves when a note is pressed. Like Sonic.exe and Ritz High effort. But the problem with the lua script versions is that it doesn't bother to use the camera offset in the character json. So is there a way to add the Camera follow in source? that accounts for a characters camera position?

**Comment by MayoALT** [comment]
look at the source code for sonic.exe or dave and bambi

**Comment by Collabvmisgood** [comment]
> Sonic.exe code isn't public. And Dave and Bambi dosn't have the camera movement on each note

.. Look at the 1.5 source code dude.
And yes is public
https://github.com/CryBitDev/Sonic.exe-source-1.5-and-2
