### ISSUE TITLE
Controller Support Update breaks inputs on Songs

### ISSUE THREAD

**Issue by Gui-iago** [ShadowMario/FNF-PsychEngine#1866]
### Describe your bug here.

after updating the source and adding my own changes, I noticed my keybinds didn't work when playing a song

https://streamable.com/q5g8dv (video is too large to send)

EDIT: the gamepad itself is also not working properly, i'm using a Xbox Series X controller, and usually it just works with Vanilla FNF, but here

https://user-images.githubusercontent.com/45212377/145317767-db35aed1-17dc-47b4-a4d9-320642cf975f.mp4

the controller is connected via bluetooth, and I pressed start multiple times, tried to hit notes, nothing works expect for the menus

EDIT²: they work on holds(????)

https://user-images.githubusercontent.com/45212377/145318823-0fa2afb4-94f0-4c7b-afb0-d3bd829a39fb.mp4

I'm using the default configs, the only exception for those are Downscroll Enabled and Rating Offset at -2ms

### Command Prompt/Terminal logs (if existing)

```bash
source/FreeplayState.hx:314: CURRENT WEEK: week5
source/LoadingState.hx:162: Setting asset folder to week5
source/Conductor.hx:75: new BPM map BUDDY []
source/Conductor.hx:75: new BPM map BUDDY []
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

HealthIcon.hx, PlayState.hx (lines 2236-2250)

what I wrote on PlayState.hx

```
		if (health > 2)
			health = 2;
		if (healthBar.percent < 20){
			iconP1.animation.curAnim.curFrame = 1;
			iconP2.animation.curAnim.curFrame = 2;
			}
		else
		if (healthBar.percent > 80){
			iconP2.animation.curAnim.curFrame = 1;
			iconP1.animation.curAnim.curFrame = 2;
		}
		else{
			iconP2.animation.curAnim.curFrame = 0;
			iconP1.animation.curAnim.curFrame = 0;
		}
```

**Comment by ShadowMario** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/44785097/145323509-9bf07d47-43c6-4edd-961f-62fd11fa872b.png)
You have to check this on Gameplay Settings...
