### ISSUE TITLE
problem in extract

### ISSUE THREAD

**Issue by HAMOYTHEWOLF** [ShadowMario/FNF-PsychEngine#1871]
### Describe your bug here.

Hello, I have a problem in source code extracting . It tells me the archive is corrupt. Try to extract it in other programs other than this program Winrar , but the same problem, I have deleted it and downloaded it from you many times but the same problem occurs , please reply :(
![Capture](https://user-images.githubusercontent.com/95828036/145386613-9e79956f-0271-4829-a477-8464fa2e878b.JPG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CrusherMods** [comment]
It's happened to me before but I just waited a lil bit then came back and try to download, try to wait a day or if you haven't restart your laptop/pc

**Comment by ShadowMario** [comment]
Clone the github repo with Github Desktop.
