### ISSUE TITLE
Black screen when loading small character?

### ISSUE THREAD

**Issue by Fablisothebottle** [ShadowMario/FNF-PsychEngine#1876]
### Describe your bug here.

I'm trying to make a mod with a small character like little man.
and for some reason he makes the screen black but the game still runs. even when quitting the song the screen remains black. anybody had this problem and have you fixed it?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Main Menu, Achievement's, Credits, New Weeks a nd New Songs

**Comment by FuseIsHere813** [comment]
I did have this problem before, it may be your memory or something smh, try closing a few programs and try again.

**Comment by Supersteven72** [comment]
> I did have this problem before, it may be your memory or something smh, try closing a few programs and try again.

I have the same problem with a character that just when i place the character the game just goes black and after the song plays, its still black screen. im able to leave the song by pausing and trying to remember how to exit and when i do it still blackscreen and the engine still runs its just black screen.
