### ISSUE TITLE
How do I add a Stage?

### ISSUE THREAD

**Issue by ItsTGsis** [ShadowMario/FNF-PsychEngine#188]

**Comment by ShadowMario** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API

Check the second last link, it has an example of a copy of Week 1's stage made in Lua (If you're using the downloaded build), drop in mods/stages/ and it should be good to go.

If you're on source code, copy the stage.json file in assets/preload/stages/ and rename it to whatever is your stage name, then you add the stage objects in PlayState.hx
