### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by cheemynugget2** [ShadowMario/FNF-PsychEngine#1885]
### Describe your problem here.

is there a way i can change the bpm of the gf and logo on the title screen

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

so far ive added characters and changed stage lua codes and a bit more but not much

**Comment by CrusherMods** [comment]
assets/images and look for the json they have, if there isn't its probably not supported in your build
