### ISSUE TITLE
How do i add arrow movement?

### ISSUE THREAD

**Issue by Cr0s5H34D** [ShadowMario/FNF-PsychEngine#1887]
### Describe your problem here.

I always  wanted to make my arrows move for the songs (like unfairness/cheating) but i cant always find the right answer
I tried looking at a gamebanana post but that didn't work out.
So I'm just wondering if I can get some LUA or code that can let me move the arrows

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
![](https://user-images.githubusercontent.com/44785097/145748600-b7e72a7f-3ee7-47c2-9960-207e9a20fee8.png)

**Comment by x8c8r** [comment]
here you go bro - https://gamebanana.com/tools/7980
