### ISSUE TITLE
Change Character Event changes both opponent and bf

### ISSUE THREAD

**Issue by CrunchBar41** [ShadowMario/FNF-PsychEngine#1888]
### Describe your bug here.

I am on the 0.5b lua build, and trying to test out the change character event, and I set value 1 to Dad and put value 2 to the new character, but it changes both the opponent and bf.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

**Comment by DaGhostyDude** [comment]
value 1 should be "1" not dad

**Comment by CrunchBar41** [comment]
Ah, alright, thank you
