### ISSUE TITLE
unkown variable "startVideo"

### ISSUE THREAD

**Issue by TrustVVorthy** [ShadowMario/FNF-PsychEngine#189]
it does not exist.

i have the 0.4 build, was this made in 0.4.1?

![silly](https://user-images.githubusercontent.com/86798861/135526224-b2eea9ad-a1a1-4114-bf7d-0852fb2f80af.PNG)
![no way](https://user-images.githubusercontent.com/86798861/135526257-d2c6277c-ab91-494a-b739-1599f736bc39.PNG)

**Comment by ShadowMario** [comment]
On 0.4 it was named "videoIntro"
