### ISSUE TITLE
Hide HUD

### ISSUE THREAD

**Issue by Sebasyn0se** [ShadowMario/FNF-PsychEngine#1892]
### What is your question?

Is there any way to hide the full hud in the middle of a song?

**Comment by CaulHere** [comment]
--put this in a stage lua

function onCreate()

        function onStepHit()
            if curStep ==5 then --The number is when you want the thing to happen, you can view the curSteps in the chart editer
            setProperty('camHUD.visible', false); --set the thing to false if you wanna hide the hud ,and true for it to appear   
            end
            if curStep ==7 then
            setProperty('camHUD.visible', true);  
            end
        end
    end

**Comment by prokube** [comment]
> ```
>     function onStepHit()
>         if curStep ==5 then --The number is when you want the thing to happen, you can view the curSteps in the chart editer
>         setProperty('camHUD.visible', false); --set the thing to false if you wanna hide the hud ,and true for it to appear   
>         end
>         if curStep ==7 then
>         setProperty('camHUD.visible', true);  
>         end
>     end
> ```

lua booooooooo

```haxe
/*
    Put this at the end of PlayState.hx, before the last curly bracket:
*/
override function stepHit()
{
    if (song.SONG.toLowerCase() == "SONG NAME IN LOWERCASE")
    {
        switch (curStep)
        {
            case 5:
                camHud.visible = false;
            case 7:
                camHud.visible = true;
        }
    }
    super.stepHit();
}

**Comment by DEV-idiotXD** [comment]
> > ```
> >     function onStepHit()
> >         if curStep ==5 then --The number is when you want the thing to happen, you can view the curSteps in the chart editer
> >         setProperty('camHUD.visible', false); --set the thing to false if you wanna hide the hud ,and true for it to appear   
> >         end
> >         if curStep ==7 then
> >         setProperty('camHUD.visible', true);  
> >         end
> >     end
> > ```
> 
> lua booooooooo
> 
> ```hx
> /*
>     Put this at the end of PlayState.hx, before the last curly bracket:
> */
> override function stepHit()
> {
>     if (song.SONG.toLowerCase() == "SONG NAME IN LOWERCASE")
>     {
>         switch (curStep)
>         {
>             case 5:
>                 camHud.visible = false;
>             case 7:
>                 camHud.visible = true;
>         }
>     }
>     super.stepHit();
> }
> ```

Theres nothing wrong with lua

**Comment by NathanDarkson984** [comment]
> > ```
> >     function onStepHit()
> >         if curStep ==5 then --The number is when you want the thing to happen, you can view the curSteps in the chart editer
> >         setProperty('camHUD.visible', false); --set the thing to false if you wanna hide the hud ,and true for it to appear   
> >         end
> >         if curStep ==7 then
> >         setProperty('camHUD.visible', true);  
> >         end
> >     end
> > ```
> 
> lua booooooooo
> 
> ```hx
> /*
>     Put this at the end of PlayState.hx, before the last curly bracket:
> */
> override function stepHit()
> {
>     if (song.SONG.toLowerCase() == "SONG NAME IN LOWERCASE")
>     {
>         switch (curStep)
>         {
>             case 5:
>                 camHud.visible = false;
>             case 7:
>                 camHud.visible = true;
>         }
>     }
>     super.stepHit();
> }
> ```

Ain't nobody got time for dat

**Comment by GenaroYT** [comment]
> > ```
> >     function onStepHit()
> >         if curStep ==5 then --The number is when you want the thing to happen, you can view the curSteps in the chart editer
> >         setProperty('camHUD.visible', false); --set the thing to false if you wanna hide the hud ,and true for it to appear   
> >         end
> >         if curStep ==7 then
> >         setProperty('camHUD.visible', true);  
> >         end
> >     end
> > ```
> 
> lua booooooooo
> 
> ```hx
> /*
>     Put this at the end of PlayState.hx, before the last curly bracket:
> */
> override function stepHit()
> {
>     if (song.SONG.toLowerCase() == "SONG NAME IN LOWERCASE")
>     {
>         switch (curStep)
>         {
>             case 5:
>                 camHud.visible = false;
>             case 7:
>                 camHud.visible = true;
>         }
>     }
>     super.stepHit();
> }
> ```

Well, hello there Prokube. It seems our paths have crossed again in this singular GitHub Forum Question...

(i sound like an anime villain lmfao)
