### ISSUE TITLE
Broken Mac Support for 0.5 (MacOS Sur Version 11.6)

### ISSUE THREAD

**Issue by osogames24fanosogames** [ShadowMario/FNF-PsychEngine#1895]
### Describe your bug here.

When I try to build the game using the source code, at the end, it gives me an error about something to do with a linker command failing with it's first exit code.

### Command Prompt/Terminal logs (if existing)

```bash
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by osogames24fanosogames** [comment]
Nevermind I figured it out

I forgot one step of buliding
thats it

**Comment by fireredfan7** [comment]
> Nevermind I figured it out
> 
> I forgot one step of buliding thats it

Can you tell me please?
