### ISSUE TITLE
Help with stage.lua's

### ISSUE THREAD

**Issue by Androphonomania** [ShadowMario/FNF-PsychEngine#1898]
### Describe your problem here.

So I've added an animated lua sprite in one of my stage luas, but I'm not sure how to remove the sprite after it ends.

`addLuaSprite('static', true);`
`objectPlayAnimation('static', 'dothing', false);`
`--check to see if animation has ended goes here`
`removeLuaSprite('static');`

Someone, please tell me how to do this, that would be appreciated.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SrtHero278** [comment]
You need to make an Animated Lua Sprite then Add An Animation to it. It doesn't locate the animations on its own.

**Comment by ShadowMario** [comment]
`removeLuaSprite` works, the problem must be on the `if` condition check you made for running this line of code being invalid
