### ISSUE TITLE
in art/flashfiles you can found note splash assets

### ISSUE THREAD

**Issue by MR-FNF** [ShadowMario/FNF-PsychEngine#1899]
in art/flashfiles you can found note splash assets

if you about code

if(!note.noteSplashDisabled) {
    spawnNoteSplashOnNote(note);
}

in lua idk sorry

_Originally posted by @dolpshy in https://github.com/ShadowMario/FNF-PsychEngine/discussions/911#discussioncomment-1611417_

Is it a source code version or the downloaded build version?

**Comment by IAMEC123** [comment]
what

**Comment by MayoALT** [comment]
what

**Comment by SrtHero278** [comment]
what

**Comment by MR-FNF** [comment]
ummm… I am new to github, I think this will just reply the owner message, sr

**Comment by PoleyMagik** [comment]
> in art/flashfiles you can found note splash assets
> 
> if you about code
> 
> if(!note.noteSplashDisabled) { spawnNoteSplashOnNote(note); }
> 
> in lua idk sorry
> 
> _Originally posted by @dolpshy in [#911 (comment)](https://github.com/ShadowMario/FNF-PsychEngine/discussions/911#discussioncomment-1611417)_
> 
> Is it a source code version or the downloaded build version?

technically both can use that code but Lua would be most useful on a downloaded build.

**Comment by MR-FNF** [comment]
what did shadow mario did to me?

**Comment by NokioPyro** [comment]
I think you might be a bit too young for github.

**Comment by PDL2CGamejolt** [comment]
> I think you might be a bit too young for github.

i agree

**Comment by bobNewYear** [comment]
i agree with you guys
