### ISSUE TITLE
Can you please edit middle scroll?

### ISSUE THREAD

**Issue by supajimmy** [ShadowMario/FNF-PsychEngine#1904]
### What feature do you want to get added on the base engine?

FOR 5.0+
Okay so I was testing out 5.0 and using middle scroll then I realized that you can see the other notes which I found okay if only if it was okay to see the notes like that, having the notes to each side just gets confusing and well in best terms is a tat bit worse then the old one. I mean seeing the notes is fine but I was expecting something like a funky friday approach to this where the note area is a tat bit smaller and to the left not have the notes spit in half side to side. this can be fixed if you have the thing that can make notes smaller in the scrip.lua or just .lua features. I also have a idea, if middle scroll is on then you will have a option to turn on the mini player / whatever you want to call it to have that mini set of notes on the right. 

The image down bellow shows the funky friday middle scroll 
![image_2021-12-10_102752](https://user-images.githubusercontent.com/76269429/145607699-fab6eaee-6135-46af-849b-0b9d4a3495be.png)

**Comment by ShadowMario** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/44785097/145628596-849511f1-ffc5-4426-be4b-937320afc5cc.png)
