### ISSUE TITLE
Enhancement: Unique Event Icons

### ISSUE THREAD

**Issue by prokube** [ShadowMario/FNF-PsychEngine#1906]
### What feature do you want to get added on the base engine?

# Unique Event Icons
1. Add a third value to the `eventStuff` entries in `ChartingState` (like a path to the custom icon):

```haxe
var eventStuff:Array<Dynamic> =
	[
		['Show Text On Screen', "1: The Text\n2: How long the text will be on the screen","shared/images/eventIcons/showText.png"],
		['Play Animation', "This tooltip is way too long normally", "shared/images/eventIcons/playAnim.png"],
...
```

2. Do some fancy stuff to load the graphic if specified, otherwise load the default one.

## "Hey!"
Just take BF's peace sign from the .fla I guess?? Rotate it and scale to whatever fits in 128x128

## "Set GF Speed"
![Set GF Speed Icon](https://user-images.githubusercontent.com/68293280/145629160-f4a3c393-0c70-4afd-94b7-28a7b7b907ac.png)

GF's icon, with a fast-forward symbol and "x1" in the corner (this isn't supposed to update based on the input just btw)
I know a bigger number slows the bopping down, and this is technically kinda misleading, but it's whatever rn

## "Blammed Lights"
A few miniature Philly buildings, all the windows different colors.

## "Kill Henchmen"
The achievement graphic for killing the henchmen, but without the achievement frame.

## "Add Camera Zoom"
don't know yet

## "BG Freaks Expression"
One of the Roses BG Freaks's faces in normal FNF style.

## "Trigger BG Ghouls
won't have a good idea for a while

## "Play Animation"
I had an idea for this but forgot it

## "Camera Follow Pos"
A tiny camera (Like in the Screen Shake icon) that's offset from a crosshair in the center.

## "Alt Idle Animation"
don't know yet

## "Screen Shake"
A camera, with several pasted, translucent (25% opacity?) copies closely scattered to make it look like the camera is shaking.

## "Change Character" Icon?
![Change Character Icon](https://user-images.githubusercontent.com/68293280/145616223-e38d6662-b6b6-4631-b19e-c37dffb054a0.png)
This is meant to be the Daddy Dearest icon morphing into the Spirit icon. Because, you know, Change Character. The arrows were added for (hopefully) clarification. I removed the eyes and stuff because it looked kinda weird and I didn't wanna try to make facial features that are halfway through a transformation

#### This is the most effort I've ever put into an issue please consider this

**Comment by ShadowMario** [comment]
That's a cool suggestion but i don't want to implement it.

**Comment by prokube** [comment]
> That's a cool suggestion but i don't want to implement it.

sure
