### ISSUE TITLE
IDE error preventing me to build

### ISSUE THREAD

**Issue by Reycko** [ShadowMario/FNF-PsychEngine#1907]
### Describe your problem here.

So i can't build beacuse of this ide error bugging me

![image](https://user-images.githubusercontent.com/78082869/145632875-fef8bd7d-2d85-4611-9d10-8964a79dde60.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

It's vs herobrine i just made a copy of PlayState.hx

**Comment by prokube** [comment]
add another bracket on line 4019

**Comment by Reycko** [comment]
> add another bracket on line 4019

![image](https://user-images.githubusercontent.com/78082869/145635774-a07a9f88-ae1f-428c-823f-9dd84e2398da.png)

**Comment by HamsterExclusive** [comment]
> > add another bracket on line 4019
> 
> ![image](https://user-images.githubusercontent.com/78082869/145635774-a07a9f88-ae1f-428c-823f-9dd84e2398da.png) ![image](https://user-images.githubusercontent.com/78082869/145635854-11979de1-0ee6-4b10-840d-29dc58e168ad.png)

you put a semi colon after the bracket but you dont need to
