### ISSUE TITLE
Loading screen implementation

### ISSUE THREAD

**Issue by Manupro97** [ShadowMario/FNF-PsychEngine#1912]
### What feature do you want to get added on the base engine?

I would like to know if there's a way to add a loading screen like on the week 7, that way people can feature there own art or the mod's logo just to give it more identity, or making cool stuff with it.

**Comment by PlugBoyOfficial** [comment]
feature is available in html5 version

**Comment by ShadowMario** [comment]
Only the browser version needs it, Desktop doesn't need a loading screen, but if you still want to enable it for no reason, go into the source code's Project.xml and enable NO_PRELOAD_ALL to desktop. (Plus remove PRELOAD_ALL)
