### ISSUE TITLE
"Play here" button

### ISSUE THREAD

**Issue by antoineelcrak** [ShadowMario/FNF-PsychEngine#1913]
### What feature do you want to get added on the base engine?

It'd be nice to have a "play here" button on the chart editor, kinda like what osu!mania does, to test events and stuff, kinda like what the esc button does currently on the chart editor but for the whole song

**Comment by Illuwumi** [comment]
Y E S  P L S

**Comment by DEV-idiotXD** [comment]
There is press esc then it will put u in the testing mode thing

@ShadowMario ya knw wut to do

**Comment by antoineelcrak** [comment]
> There is press esc then it will put u in the testing mode thing
yeah but that only tests the chart, I wanna test the whole song for testing events or animations etc

**Comment by DEV-idiotXD** [comment]
> > There is press esc then it will put u in the testing mode thing
> 
> yeah but that only tests the chart, I wanna test the whole song for testing events or animations etc

why would u need that? Just test it unless ur charting 10+ songs then ye ur gonna need it

**Comment by DEV-idiotXD** [comment]
> > why would u need that? Just test it unless ur charting 10+ songs then ye ur gonna need it
> 
> Just for convinience really, I'm just a lazy fuck and I don't wanna sit through 1 min of a song just to see if an animation is correctly timed LOL

What mario should just do is make the whole stage (thats translucent) on the chart editor whenever u press space so u can see the characters and objects play theyre animations
