### ISSUE TITLE
source/StoryMenuState.hx:323: characters 12-14 : Expected )

### ISSUE THREAD

**Issue by FireKoopaX** [ShadowMario/FNF-PsychEngine#1916]
### Describe your problem here.

When i try to test the game, I get an error saying "source/StoryMenuState.hx:323: characters 12-14 : Expected )" 
![Screenshot 2021-12-10 174126](https://user-images.githubusercontent.com/95194411/145654349-afae363f-8164-45b2-93d0-f0d5402dbe42.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i just downloaded the Source Code

**Comment by CrusherMods** [comment]
Psych Engine uses the latest version of haxe not 4.1.5 now

**Comment by FireKoopaX** [comment]
> 
oh, thanks!
