### ISSUE TITLE
how do i add bg's like the evil school?

### ISSUE THREAD

**Issue by Fablisothebottle** [ShadowMario/FNF-PsychEngine#1917]
### Describe your problem here.

So I'm making a Mod where the final song the opponent glitches the game and the BG has glitchy visuals.
how do i have it animating? not like the BG freaks.. how the stage itself moves.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Main Menu, Achievement's, Credits, New Weeks, New Songs And a new Playable Character.

**Comment by Fablisothebottle** [comment]
i mean i could use evilschool source itself but where is it located?

**Comment by CrusherMods** [comment]
> i mean i could use evilschool source itself but where is it located?
PlayState.hx literally where every hardcoded stages go

**Comment by Fablisothebottle** [comment]
so i have to hard code it in?

**Comment by Fablisothebottle** [comment]
im seeing thing of if (curstage blahdakdha);
add babahsjaaaa
is that related?

**Comment by KutikiPlayz** [comment]
you just need to make an animated bg and then copy and paste some of the code from school evil, and then change some variables to fit your bg

**Comment by ShadowMario** [comment]
This isn't a psych engine issue.
