### ISSUE TITLE
Modifier: Opponent Play and Dual Mode

### ISSUE THREAD

**Issue by SteveeWasTaken** [ShadowMario/FNF-PsychEngine#1918]
### What feature do you want to get added on the base engine?

There's two modifiers that I think would make the engine great. "Opponent Play" would make you hit the Opponent's notes instead of BF's notes. And the "Dual Mode" means you press the Opponent's notes with WASD and press BF's notes with the arrow keys. It's just a small idea I had.

**Comment by ShadowMario** [comment]
This was already requested before
