### ISSUE TITLE
Custom Game Over Screen

### ISSUE THREAD

**Issue by StickDeveloper** [ShadowMario/FNF-PsychEngine#1921]
### Describe your bug here.

I need help making a custom game over screen when a note is hit/missed. Anyone have a clue on how to do this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by SrtHero278** [comment]
https://cdn.discordapp.com/attachments/889357899015540736/901470021652447233/script.lua
Add this to your `goodNoteHit` or `noteMiss` callback.
