### ISSUE TITLE
Vortex Editor Arrow

### ISSUE THREAD

**Issue by SteveeWasTaken** [ShadowMario/FNF-PsychEngine#1924]
### What is your question?

In the chart editor, when Vortex Editor is enabled, there's a small "arrow" that changes color when the arrow keys are pressed. It doesn't do anything, so I wanted to know, what does it actually do?
![image](https://user-images.githubusercontent.com/77215030/145661689-08735153-d2fa-4282-b427-1e8f2ca56eb0.png)

**Comment by PDL2CGamejolt** [comment]
it finds out where the lien ther

**Comment by SteveeWasTaken** [comment]
> it finds out where the lien ther

Sorry, could you explain what you mean?

**Comment by ShadowMario** [comment]
You can change snap by pressing Left/Right arrow keys
