### ISSUE TITLE
Change Character Event doesn't work at certain points. (0.4.2)

### ISSUE THREAD

**Issue by NoNamesInStock** [ShadowMario/FNF-PsychEngine#1926]
### Describe your bug here.

Not really sure how to explain this, since I really have no clue why this happens. The song is from another mod, I'm trying to put it in Psych Engine for testing since I have never tried actually making a mod before. But at certain points, the event just doesn't work as expected. **(The Song is No Villains from the Tails Gets Trolled Mod)**

When used in Section 1
Fine, perfect, characters changed to another.

When used in sections 52, 54, 72, 88, 104 **(The song length is 2:45)**
The opponent and Girlfriend change into another character, which is basically impossible since you can only input one player. After 3-4 character changes, Girlfriend disappears from the stage.

Changing Value 1 to 2 or 3 does the same, but only to Girlfriend.

2/3:
![image](https://user-images.githubusercontent.com/85188550/145662565-ef31f396-86fe-45bc-b946-4e79eeefb273.png)

After 3-4 character changes (Girlfriend disappears)
![image](https://user-images.githubusercontent.com/85188550/145662709-df3f6c6f-679c-480e-b7b8-537b3ed36935.png)

Debug Menu character names just in case
`sonictgt` (Can be seen in the first image)
`sonictgt_mad` (Can be seen in the first and second image)
`sonictgt_forced` (Has the same Icon as `sonictgt`, could be the problem but not sure how it could be)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Adding Characters, Adding Weeks and Songs, Adding NoteTypes and Events.

**Comment by ShadowMario** [comment]
0.4.2 isn't supported anymore.
