### ISSUE TITLE
freeplay broke

### ISSUE THREAD

**Issue by Cyber1983** [ShadowMario/FNF-PsychEngine#1927]
### Describe your bug here.

after trying a song and then exiting it my entire game crashed
and now whenever i open freeplay it just breaks

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing litteraly

**Comment by prokube** [comment]
not enough info

**Comment by ShadowMario** [comment]
I need more information because this issue isn't explanative enough.

**Comment by Cyber1983** [comment]
i dont know what caused it i just remember exiting one song and then it crashed

**Comment by Cyber1983** [comment]
nevermind i found out i had accidentally putted a character's json file in mods/week so since it wasnt a week file the game would crash

**Comment by cheemynugget2** [comment]
> I need more information because this issue isn't explanative enough.

yo i think he means he added a song and now he cant go into freeplay from the main menu

**Comment by ShadowMario** [comment]
> nevermind i found out i had accidentally putted a character's json file in mods/week so since it wasnt a week file the game would crash so yes your allowed to close this i fixed it on my own lol somehow

You know you can close issues on your own right?
