### ISSUE TITLE
Where does the "pack.json" for the description and stuff goes?

### ISSUE THREAD

**Issue by FuseIsHere813** [ShadowMario/FNF-PsychEngine#1929]
### What is your question?

I tried different locations but said "No description provided.", I know I am doing something wrong, so that's why I am asking where does the location for the JSON goes.

**Comment by crashok20185** [comment]
try in mods/your mod name and dont put in no folder just put on mods and your mod

**Comment by crashok20185** [comment]
![image](https://user-images.githubusercontent.com/91495721/145670303-67bbeb56-1e51-4292-bc11-2cfb43aa5448.png)

**Comment by crashok20185** [comment]
like this

**Comment by crashok20185** [comment]
ignore portugues

**Comment by FuseIsHere813** [comment]
got it!
