### ISSUE TITLE
when changing splash notes in the chart editor it crashes (i check the xml)

### ISSUE THREAD

**Issue by BL0KYBL0K** [ShadowMario/FNF-PsychEngine#193]
- [What Version ] 
I used the Latest Version
- [correct xml names]
yes i used the correct xml names
- [ Splash File]
![pixelsplashes](https://user-images.githubusercontent.com/88749184/135647830-2800e791-ef25-429d-b7ce-70ff2eab12f8.png)

**Comment by ShadowMario** [comment]
Crashes only happens when the names are wrong in the .xml or your xml is not encoded in UTF-8 with BOM
