### ISSUE TITLE
0.5 small things to be fixed now

### ISSUE THREAD

**Issue by Chromebookgamerwastaken** [ShadowMario/FNF-PsychEngine#1930]
### Describe your bug here.

Screen shake still crashes, and turning off anti aliasing crashes, nothing big this time

### Command Prompt/Terminal logs (if existing)

```bash
Nothing
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

**Comment by CrusherMods** [comment]
I think they fixed anti aliasing but idk about screenshakes but I think I did use screenshakes so

**Comment by ShadowMario** [comment]
HTML5 sucks ass.

**Comment by Chromebookgamerwastaken** [comment]
Aight, imma check out the official release
