### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by SomethingWasError** [ShadowMario/FNF-PsychEngine#1931]
### Describe your bug here.

Load New Week's Song Crash(And Sorry i cannot send video)

### Command Prompt/Terminal logs (if existing)

```bash
source/FreeplayState.hx:300: racing-hard
source/FreeplayState.hx:307: CURRENT WEEK: week134
source/LoadingState.hx:162: Setting asset folder to shared
source/Conductor.hx:75: new BPM map BUDDY []
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i don't know

**Comment by ShadowMario** [comment]
> ### **Did you edit anything in this build? If so, mention or summarize your changes.**
> i don't know

Answer this.
