### ISSUE TITLE
Idea for future version

### ISSUE THREAD

**Issue by Chromebookgamerwastaken** [ShadowMario/FNF-PsychEngine#1933]
### What feature do you want to get added on the base engine?

There should be a toggable option on the character editor, to be able to edit character's offsets by each indice (or frame depending on the xml)

**Comment by ShadowMario** [comment]
No, just fix your animation in Adobe Animate it ain't that hard.

**Comment by Chromebookgamerwastaken** [comment]
I meant for other people, not myself but ok
