### ISSUE TITLE
❗🔴⚠🔴❗ I want to make a Change Song Speed Event. ❗🔴⚠🔴❗

### ISSUE THREAD

**Issue by IAmAHumanToo** [ShadowMario/FNF-PsychEngine#1934]
### Describe your problem here.

I want to make a note speed event in Lua.

I have not coded ANYTHING so far.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by SrtHero278** [comment]
`setProperty('SONG.speed', [ANYNUMBER])` You know how to use the `onEvent` callback right?

**Comment by ShadowMario** [comment]
There's a scroll speed change event on 0.5 already...

**Comment by IAmAHumanToo** [comment]
wow

**Comment by IAmAHumanToo** [comment]
cool
I think I have 0.4
