### ISSUE TITLE
events change Background

### ISSUE THREAD

**Issue by xfoxstrot** [ShadowMario/FNF-PsychEngine#1937]
### What is your question?

Hello. 

We have event  changeCharacters at FNF. 
Tell me please how to make events change background?

**Comment by CrusherMods** [comment]
its not an event

**Comment by xfoxstrot** [comment]
I mean, I want to change background during song, how do I make it?

**Comment by CrusherMods** [comment]
> I mean, I want to change background during song, how do I make it?

oh Idk but there may be duplicates of this issue so you can go look for them someone may of gave the way

**Comment by PDL2CGamejolt** [comment]
i wanna have the event

**Comment by xfoxstrot** [comment]
> > I mean, I want to change background during song, how do I make it?
> 
> oh Idk but there may be duplicates of this issue so you can go look for them someone may of gave the way

I don't found something.

**Comment by xfoxstrot** [comment]
> i wanna have the event

Sorry, I don't understand what do you mean

**Comment by ShadowMario** [comment]
Duplicate of multiple issues.
