### ISSUE TITLE
PLES GIVE ME SOLUTION OF THE CUTSCENES PROBLEM

### ISSUE THREAD

**Issue by Illuwumi** [ShadowMario/FNF-PsychEngine#1942]
### Describe your bug here.

Helo i have a problem that is very annoying aight si when i add cutscenes in VIDEOS FOLDER don't tell me that i put it wrong and it was on 1280×720 and it didn't work bf and mom just sitting there doing nothing
![Screenshot_20211211_162952](https://user-images.githubusercontent.com/94763556/145682379-356512c1-b8d8-495b-8e5b-752b5104bfc7.png)

### Command Prompt/Terminal logs (if existing)

```bash
Joe mama (means nothing)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes i added my video to mods and then videos but it didn't work so i moved it to assets and then videos wich is ALSO didn't work

**Comment by Adriangamer1246** [comment]
did you put the cutscene on the mods folder?
and did you put the lua script for the cutscene?

**Comment by Illuwumi** [comment]
> 

I put it in mods folder and it didn't work
And yes i have put the lua script in the song folder

**Comment by Adriangamer1246** [comment]
put the video in the videos folder of /assets

**Comment by Illuwumi** [comment]
> put the video in the videos folder of /assets

I already did and it didn't work

**Comment by Adriangamer1246** [comment]
one question

**Comment by Adriangamer1246** [comment]
did you put the name of your cutscene in the lua script?

**Comment by ShadowMario** [comment]
Show me your lua script, duh.

**Comment by Illuwumi** [comment]
> Show me your lua script, duh.

local allowCountdown = false
function onStartCountdown()
	if not allowCountdown and isStoryMode and not seenCutscene then --Block the first countdown
		startVideo('coolcutscene');
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

**Comment by Illuwumi** [comment]
> did you put the name of your cutscene in the lua script?

Yes

**Comment by ShadowMario** [comment]
Where did you put your lua script?

**Comment by DEV-idiotXD** [comment]
> Where did you put your lua script?

He said in the song folder

**Comment by Illuwumi** [comment]
> > Where did you put your lua script?
> 
> He said in the song folder

No i said in assets and then videos

**Comment by Illuwumi** [comment]
> > Where did you put your lua script?
> 
> He said in the song folder

Yes

**Comment by sonicfan888** [comment]
You should've put it on data I think

**Comment by Illuwumi** [comment]
> You should've put it on data I think

No i didn't

**Comment by Illuwumi** [comment]
Im gonna try the new update and see

**Comment by Illuwumi** [comment]
Ok guys its fixed thank you very much for ya help i appreciate it
