### ISSUE TITLE
pack.json

### ISSUE THREAD

**Issue by Adriangamer1246** [ShadowMario/FNF-PsychEngine#1943]
### What is your question?

where do i get the pack.json

**Comment by CrusherMods** [comment]
in the source code for now

**Comment by Adriangamer1246** [comment]
then why do i see ppl with the pack.json with lua?

**Comment by CrusherMods** [comment]
> then why do i see ppl with the pack.json with lua?

When you extract the game there is a bin folder with psych engine then they can just mod it from there then unless its actually with lua

**Comment by CrusherMods** [comment]
either way it'll come out with the next release with 0.5

**Comment by Adriangamer1246** [comment]
> > then why do i see ppl with the pack.json with lua?
> 
> When you extract the game there is a bin folder with psych engine then they can just mod it from there then unless its actually with lua

then how do i mod it from there?

**Comment by ShadowMario** [comment]
docs/ folder of source code has a template pack.json file you can use on your mod.
