### ISSUE TITLE
How do i even make a effect?

### ISSUE THREAD

**Issue by ByronisJoan** [ShadowMario/FNF-PsychEngine#1948]
### Describe your problem here.

How do i make this Effect from You Cant Run, The red Image that appears, i Have no Idea how to make that
![RedVG](https://user-images.githubusercontent.com/93352980/145685519-3e331667-96f9-4ebc-b3ee-b18b39cc9611.png)
?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not Edit anything In my build

**Comment by ShadowMario** [comment]
Add a FlxSprite/BGSprite on screen using this image.
