### ISSUE TITLE
Suggestion: Play chart from current position

### ISSUE THREAD

**Issue by aflacc** [ShadowMario/FNF-PsychEngine#195]
I think it would be cool that if you pressed shift + enter in the charting menu. You can test the song out at any point, so you can test a part far into the song without needing to replay the entire thing. You would also be able to temporarily skip a section if something is bugged that you don't want to fix yet, and would generally be helpful

Basically, it would just play the chart, but the chart is fast forwarded to the point you set.

**Comment by ShadowMario** [comment]
this will *technically* be added in the next update as i'm adding a feature to play charts inside the Chart Editor

**Comment by aflacc** [comment]
> ...i'm adding a feature to play charts inside the Chart Editor
What do you mean by this? Do you mean like a preview?
