### ISSUE TITLE
mod

### ISSUE THREAD

**Issue by Adriangamer1246** [ShadowMario/FNF-PsychEngine#1953]
### Describe your bug here.

so i was using v0.5 and the pack.json, the mod folder and modlist.txt was in the bin folder
when i entered the game, i clicked the mod option and it said no description provided, and i couldnt play the songs.

### Command Prompt/Terminal logs (if existing)

```bash
nope
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by ShadowMario** [comment]
Prerelease has issues, that's why it's a pre-release.
