### ISSUE TITLE
my last issue got closed

### ISSUE THREAD

**Issue by BL0KYBL0K** [ShadowMario/FNF-PsychEngine#196]
so i made a issue about splashes and you said they need to be made with utf8 
when that is what i used 
![image](https://user-images.githubusercontent.com/88749184/135674528-5d6251de-53a8-4e45-aded-c505cedd5797.png)
so please help me

**Comment by lemz1** [comment]
what is the problem with the notesplashes are they not shown or what is the problem?

**Comment by BL0KYBL0K** [comment]
> what is the problem with the notesplashes are they not shown or what is the problem?

game crashes when i load them in chart editor

**Comment by lemz1** [comment]
i think the problem could be that the name doesn't fit with the normal notesplash name 
instead of note splash blue0000
use note splash blue 10000 maybe this is the problem

**Comment by BL0KYBL0K** [comment]
OK

**Comment by ShadowMario** [comment]
And as i said before, your XML is wrong.
Note splashes have two variations, one that starts with "1" and another one that starts with "2" (Example: `note splash blue 2`, `note splash purple 1`, you can just do a copy of your variation and name it properly.
Don't do another issue if you aren't atleast trying to follow my instruction.

**Comment by BL0KYBL0K** [comment]
ok
