### ISSUE TITLE
New 0.5 Update ISsue.

### ISSUE THREAD

**Issue by MonkeFunke** [ShadowMario/FNF-PsychEngine#1963]
### Describe your bug here.

When I try to compile the newest update for Psych Engine, this message appears. 

![image](https://user-images.githubusercontent.com/86891981/145690489-6310a4a9-c809-4893-95d9-2660c521c2a3.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added character.json files in preload, added images, changed spooky and stage stages, added new character sprites and stage and character coding.

**Comment by MrGrape0** [comment]
I'm with that problem too.

**Comment by KutikiPlayz** [comment]
Make sure your haxe version is 4.2.4 and not 4.1.5
I just updated and I no longer have the error
