### ISSUE TITLE
StoryMenuState not working in 0.5

### ISSUE THREAD

**Issue by SanLLL** [ShadowMario/FNF-PsychEngine#1964]
### Describe your bug here.

Why StoryMenuState not working in 0.5

### Command Prompt/Terminal logs (if existing)

```bash
source/StoryMenuState.hx:323: characters 12-14 : Expected )
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didnt change anything

**Comment by SansFont99** [comment]
I also have this issue

**Comment by Pizzadough671** [comment]
I have a fix, download the latest [Haxe](https://haxe.org/download/)

**Comment by Pizzadough671** [comment]
I have a fix, first download the latest version of [Haxe](https://haxe.org/download/)

If that doesn't help, replace  if(image is FlxGraphic) with f($type(image) == 'FlxGraphic') on source/StoryMenuState.hx:323.

Code provided by [SrtHero278](https://github.com/SrtHero278) go follow em

**Comment by SanLLL** [comment]
ok
