### ISSUE TITLE
BUG song.hx

### ISSUE THREAD

**Issue by min89xd** [ShadowMario/FNF-PsychEngine#1966]
### Describe your bug here.

I have this bug

### Command Prompt/Terminal logs (if existing)

```bash
source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by KutikiPlayz** [comment]
Make sure your haxe version is 4.2.4 and not 4.1.5
I just updated and I no longer have the error
