### ISSUE TITLE
Song broken

### ISSUE THREAD

**Issue by Alberto20108** [ShadowMario/FNF-PsychEngine#1967]
### Describe your problem here.

I got a song for my mod, but when I try to play it pressing space from freeplay, the game crashes, and in the chart editor it says that the length of the song is **0 / 0**, my week has the same song name as the one i'm using, the song has a voices track and I checked the _"song has a voice track"_ checkbox and everything seems to be fine, please help.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I tried to put the song on the assets folder but it still didn't work.

**Comment by PDL2CGamejolt** [comment]
I think you put it in the wrong area

**Comment by Alberto20108** [comment]
No, it was on /Psych engine/mods/mymod/songs. I also tried to put it in the assets folder.

**Comment by Alberto20108** [comment]
Nothing seems to work.

**Comment by NotEpik** [comment]
is it "Ogg" file type? if not CHANGE TO OGG NOWWWWWWWWWWW

**Comment by NotEpik** [comment]
> @PDL2CGamejolt No, it was on /Psych engine/mods/mymod/songs. I also tried to put it in the assets folder.

also putting it in assets folder never work

**Comment by Alberto20108** [comment]
> > @PDL2CGamejolt No, it was on /Psych engine/mods/mymod/songs. I also tried to put it in the assets folder.
> 
> also putting it in assets folder never work

Yeah, but i did it 'cause other mods on Psych engine do that.

**Comment by Alberto20108** [comment]
Also, they are .ogg file type songs.
