### ISSUE TITLE
Fucky 0.5 still dont work yay

### ISSUE THREAD

**Issue by FwostyX3** [ShadowMario/FNF-PsychEngine#1968]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/87388604/145693354-90da6dc7-de78-4ca2-b4cc-5b33002dd906.png)

This is the 0.5 release source bruh 

was there no tests?

### Command Prompt/Terminal logs (if existing)

```bash
source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I cant even make a build :|

**Comment by HiroMizuki** [comment]
everyone's getting this error bud

**Comment by HiroMizuki** [comment]
but for this error, we'll need to temporarily use the 0.5 tag

**Comment by Adriangamer1246** [comment]
its bugged shadowmario said this.
its a pre-release not a full release

**Comment by Adriangamer1246** [comment]
close this please

**Comment by FwostyX3** [comment]
i know

**Comment by FwostyX3** [comment]
just very impatient and thats my fault

**Comment by KutikiPlayz** [comment]
Make sure your haxe version is 4.2.4 and not 4.1.5
I just updated and I no longer have the error

**Comment by DaRealDotZ** [comment]
Update Your Haxe To 4.2.4
