### ISSUE TITLE
Charts not saving when I save them

### ISSUE THREAD

**Issue by ToBAYT** [ShadowMario/FNF-PsychEngine#197]
Im working on a mod with the engine but when I save the charts and I go to the week selector/freeplay, and I load up the song, it isn't saved. This is really important so please help fix this. I also got video proof (Yes I did save it but I forgot to show the screen because I used OBS studio

https://user-images.githubusercontent.com/73630363/135698239-e1da2150-6031-4f43-a7dc-55fcd310b198.mp4

**Comment by lemz1** [comment]
You have to replace the saved json with the old json if you didn't do that

**Comment by ToBAYT** [comment]
I did

**Comment by ToBAYT** [comment]
> You have to replace the saved json with the old json if you didn't do that

**Comment by lemz1** [comment]
have you also added the "-hard" to the file if not then it replaces the normal difficulty chart, but if you did replace the hard difficulty json, then I'm not sure what to do.
(maybe you could go to \export\release\windows\bin and delete the assets folder and just do lime test windows so the assets folder will be reinstalled.)

**Comment by ToBAYT** [comment]
I did

**Comment by ToBAYT** [comment]
But I will try again
\

**Comment by ToBAYT** [comment]
Ok. Ill rechart the hard mode and save it and delete assets and restart the game. I fit works, this issue should be closed then

**Comment by ToBAYT** [comment]
So I found out it did save but I had to reboot the game. Sorry for wasting your time. I feel bad so you can get early access to the mod!
