### ISSUE TITLE
week 6 bug

### ISSUE THREAD

**Issue by Adriangamer1246** [ShadowMario/FNF-PsychEngine#1970]
### Describe your bug here.

so if you remove the dialogue from week 6 on story mode the screen will turn white
for me ( in every single version, not just in v0.5

### Command Prompt/Terminal logs (if existing)

```bash
nope
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i deleted week 6 dialogue lol

**Comment by ShadowMario** [comment]
Then don't delete week 6 dialogue???
