### ISSUE TITLE
credits not showing

### ISSUE THREAD

**Issue by skid15** [ShadowMario/FNF-PsychEngine#1974]
### Describe your problem here.

the credits i made aren't showing in the game, even with the credits.txt in mods/data.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
Show your credits.txt file.

**Comment by skid15** [comment]
> Show your credits.txt file.

![Screenshot 2021-12-17 6 46 26 PM](https://user-images.githubusercontent.com/85322671/146623051-ace13257-c9bb-485b-a7da-2755ad64ab0a.png)
