### ISSUE TITLE
0 or Negative scroll speed

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#1977]
### Describe your bug here.

![2021-12-11 (5)](https://user-images.githubusercontent.com/94698464/145698259-ba7f36ca-dc8c-4984-b4b2-8efe1fc3a0cf.png)
when i made change scroll speed event go to 0 or negative scroll speed,it breaks the notes.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no response

**Comment by PDL2CGamejolt** [comment]
but dont fix it, i like it

**Comment by PDL2CGamejolt** [comment]
And when you put a note speed beyond 10 it will break the notes as well
![2021-12-11 (6)](https://user-images.githubusercontent.com/94698464/145698365-2307125f-a508-4780-b197-fe1f351655fa.png)
and sometimes the opponent (or the bot) does nothing

**Comment by KutikiPlayz** [comment]
That's not a bug, that's just what happens when you multiply something by 0. You get 0.

**Comment by PDL2CGamejolt** [comment]
but how?

**Comment by ShadowMario** [comment]
That's not a bug, that's how scroll speed works like in FNF.
