### ISSUE TITLE
Mod Crashes whenever a song ends.

### ISSUE THREAD

**Issue by QuagFire101** [ShadowMario/FNF-PsychEngine#1981]
### Describe your problem here.

So for months, the mod I'm currently working on has been working fine, but as soon as I coded in the third song, the mod crashes whenever ANY song is finished. The only two major things to change were the script and the bg lua files, but I am not sure how either of those would cause the mod to have ANY of the songs crash. 

Truth be told I have no clue what the source of this problem might be, so if I at least can get that, then I'd greatly appreciate it. 

**Script.lua**
![image](https://user-images.githubusercontent.com/90576570/145698719-fe9d86d4-59be-412e-8af7-52f48abc8f03.png)

**Stage lua file**

![image](https://user-images.githubusercontent.com/90576570/145698728-348b2ef4-b58c-4ffb-b13a-930fb8d936bd.png)

Any help I get would be greatly appreciated!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited the credits to add the icons of my team, I added 3 songs, two of which worked in full originally and a third (listed in the description) that has some additional coding involved (in the script file) and songs crash immediately after they're finished because of this.

**Comment by i-winxd** [comment]
The game will crash if the chart is shorter than the song. This may not be the case.

**Comment by QuagFire101** [comment]
> The game will crash if the chart is shorter than the song. This may not be the case.

I do not think this is a problem, as this is a sudden problem affecting all three songs, when the first two ended just fine before.

**Comment by bbpanzu** [comment]
do the charts have the same difficulties?
