### ISSUE TITLE
mod folder file shit (more explained)

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#1983]
### Describe your bug here.

ive said this before but i wanted to explain it in more detail. so i have a mod, that replaces the menu bg, week jsons, and other things. when just placing it all in the mods folder, it works fine. replaces the assets that have the same name as the base game ones (like if i have a file named "week1.json", it loads that instead of the OG week1.json). but when making it an Indivisual folder in the mod folder itself (like "fightmod.zip"), it only loads files with original names. not replacment ones. if so, could this be fixed? thank you!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
You have to put it here: `mods/Your-Mod-Name/weeks/week1.json`
Modpacks can't be used if they're zipped.

**Comment by crispyboi24** [comment]
> You have to put it here: `mods/Your-Mod-Name/weeks/week1.json` Modpacks can't be used if they're zipped.

nope, still not workin. ive turned the mod on and off 3 times. and it still doesnt load it in. and no, its not zipped.
