### ISSUE TITLE
Bruh Peep this one

### ISSUE THREAD

**Issue by FwostyX3** [ShadowMario/FNF-PsychEngine#1984]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/87388604/145699336-6e3e5f53-c3e8-47bd-b7a0-a6c8f237ad62.png)
i just hope that when i download the next release it works right 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
????

Give some explanation or something??

**Comment by DEV-idiotXD** [comment]
His issue is the note splash is messed up lmao close it
