### ISSUE TITLE
I can't compile the game!

### ISSUE THREAD

**Issue by Spookandscare** [ShadowMario/FNF-PsychEngine#1985]
### Describe your bug here.

Whenever I try to compile the newest version, it doesn't work

### Command Prompt/Terminal logs (if existing)

```bash
"source/Song.hx:65: characters 24-41 : Array access is not allowed on {+ length : Int }
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I downloaded the build, compiled it, and was greeted with this issue

**Comment by HiroMizuki** [comment]
did u updated your Haxe to 4.2.4? (Not by prompt, by manual installer)
