### ISSUE TITLE
how do you make a clickable menu

### ISSUE THREAD

**Issue by Emeninja** [ShadowMario/FNF-PsychEngine#1986]
### Describe your problem here.

I'm trying to make my menu clickable i know you use FlxG.mouse.visible = true; but how do make the stuff able to be clicked

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
`FlxG.mouse.overlaps`
For more info: https://api.haxeflixel.com/flixel/input/FlxPointer.html

This isn't something exactly easy to do.
