### ISSUE TITLE
How do I fix this?

### ISSUE THREAD

**Issue by SonikLikesPsychEngine** [ShadowMario/FNF-PsychEngine#1988]
### Describe your problem here.

When I go into command prompt, and add lime test windows, it says source/StoryMenuState.hx:323: characters 12-14 : Expected ), how do I fix this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by TheGamer2007gaming** [comment]
Did you add anything into the game? or does it just do that when you try to compile the game?

**Comment by Spookandscare** [comment]
I got the same error a while ago. Maybe update your Haxe? It is working for me after I did

**Comment by koko123tutorial** [comment]
I get error like this too

**Comment by SonikLikesPsychEngine** [comment]
It's when I try to compile the game.

**Comment by SonikLikesPsychEngine** [comment]
> It's when I try to compile the game.
