### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by HiroMizuki** [ShadowMario/FNF-PsychEngine#1991]
### Describe your bug here.

well, i was charting a song, and the game has closed by selecting change scroll speed at events
now, when i click to load autosave the chart, the game crashes
wtf is going on dude

### Command Prompt/Terminal logs (if existing)

```bash
Null Object Reference
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by HiroMizuki** [comment]
don't need help
i think the autosave just corrupted lmao

**Comment by MayoALT** [comment]
autosave just kinda sucks, ive had two charts corrupt because of it
