### ISSUE TITLE
can't to build

### ISSUE THREAD

**Issue by koko123tutorial** [ShadowMario/FNF-PsychEngine#1999]
### Describe your problem here.

ok so, I was wanna to build the Psych Engine but is error when I write in Commands Prompt like this, "lime test windows" output=("source/Song.hx:65: characters 24-41 : Array access is not allowed on {+ length : Int }"), then is back to normal Commands Prompt

PLZZZZZZ HELPPP MEEEEEE

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by Stilic** [comment]
You should use the latest version of Haxe, downloable [here](https://haxe.org/download).

**Comment by koko123tutorial** [comment]
> 

I already download it

**Comment by Stilic** [comment]
Yes but you need the latest version of Haxe, the 4.2.4 (not the 4.1.5 recommended by [this popular guide](https://gamebanana.com/tuts/13798)).

**Comment by koko123tutorial** [comment]
ok my haxe is 4.2.4 but my haxelib version 4.0.2

**Comment by Stilic** [comment]
Ok, it's should work anyways. But before, you should also update HaxeFlixel:
```
haxelib update flixel
haxelib update openfl
```

**Comment by ShadowMario** [comment]
This was already fixed on the main github repo.
