### ISSUE TITLE
Cannot load Charting State

### ISSUE THREAD

**Issue by huma139** [ShadowMario/FNF-PsychEngine#2]
Hi. So I was trying to mess around in your engine, when I try to go to the chart state it crashed. 

Running in windows `-debug` mod, it says _"null object reference"_.
![image](https://user-images.githubusercontent.com/70441025/128176691-c34803e9-b08f-4ba0-a3a4-9bf8e75bafd2.png)

Running in HTML5, it says _"Cannot read property 'x' of null"_
![image](https://user-images.githubusercontent.com/70441025/128176963-c6a2e080-0efe-4023-89e6-6a5ac27357c2.png)

I thought I did something wrong cuz I did modify few stuff so I decided to re-extract a copy from the zip file (which is completely new) and test it, and... it still doesn't work either :(

I'm guessing there might be something wrong with the ChartingState.hx, but i'm dumb at code (sorry), so I hope you can fix this. I really like your engine because it's really convenient for mod and the additional stuffs is really nice. And if this gets fixed, I might make a mod on it. Also the Mind Game mod is epic.

**Comment by ShadowMario** [comment]
![](https://user-images.githubusercontent.com/44785097/128215827-dae00c8b-95d6-4d19-bf24-e9cf10afd4a8.png)
Please, check if you're using the current main github repository, it's working on my side.

**Comment by huma139** [comment]
oh shit it worked with the git respo one, i downloaded the one in the releases lul
