### ISSUE TITLE
New feature ideas. (Long post)

### ISSUE THREAD

**Issue by ScrubRTA** [ShadowMario/FNF-PsychEngine#20]
### 1. Custom judgement timings

Kade Engine has Safe Frames, which control judgement timings. The default value is 10, which results in a 45ms window of error to hit a "Sick" note, but the variable can be customized between 20 (90ms, twice as lenient) and 1 (4.5ms, comparable to Stepmania Justice). Very few people actually tamper with Safe Frames, as most FNF players don't even care to do better than full combo any song, but for people with actual rhythm game experience this is a nice way to push yourself on charts that would otherwise be too easy to care for.

### 2. More sophisticated accuracy mode

Kade Engine (again) has a type of accuracy system known as Complex (actually just WIFE from Etterna). A "Complex" accuracy system, generally, more or less ignores judgements and instead gauges your accuracy down to the millisecond, making true "100%" impossible even for bots. Much like Safe Frames, this allows players to push themselves as far as they can, well beyond what would otherwise be a perfect score. (Note: Kade Engine's Complex accuracy broke around version 1.5.3, and started to say "100%" for every note that was hit late.)

### 3. Modifiers

Depending on the direction this engine is intended to go, this could be worth considering.
This could include:
- Chart flip (left/right swapped, down/up swapped)
- Randomizer (each note has a random direction)
- One button (lol)
- Playback speed (this might be very hard to implement)
etc. Kade Engine 1.7 has the playback speed modifier, Mic'd Up has the other things I mentioned.

### 4. Practice mode

Similar to Clone Hero, this would allow you to select a specific section(s) of a song and play through that part in isolation. As far as I know, no publicly available engine does this.

**Comment by KlutchDj** [comment]
i really don't know how to feel about this suggesstions . it just feels like you want another kade engine in my eyes. excpet for the modifiers one . but thats just my opinion

**Comment by Spel0** [comment]
> Similar to Clone Hero, this would allow you to select a specific section(s) of a song and play through that part in isolation. As far as I know, no publicly available engine does this.

Mic'd up has one, you press a button in pause menu to record a segment and then when you want it to end you press it again. After that this recorded segment gets repeated until you stop it(they called it AB recording afaik)

**Comment by ScrubRTA** [comment]
> it just feels like you want another kade engine in my eyes

complex accuracy broke in later versions of kade engine, if kade wont fix it someone else should

**Comment by Slyceth** [comment]
OMG I was about to suggest a similar thing, a new accuracy system that penalizes you less if you hit the correct notes in the correct order, but all too soon, while still having the same delay between the notes itself.
