### ISSUE TITLE
VORTEX EDITOR in the charter menu.

### ISSUE THREAD

**Issue by kitinho** [ShadowMario/FNF-PsychEngine#2008]
### What is your question?

i want to know all about this setting on charter editor
![image](https://user-images.githubusercontent.com/69540352/145712730-dc5cda0f-a484-4bc0-b830-e304a8d11ade.png)

and this 
![image](https://user-images.githubusercontent.com/69540352/145712746-9808bf44-88dd-4774-9410-d6ad9a2495a3.png)
if theres no problem

**Comment by AToska21** [comment]
yeah me too ima keep this open

**Comment by ShadowMario** [comment]
Duplicate of https://github.com/ShadowMario/FNF-PsychEngine/issues/1924
