### ISSUE TITLE
add a keybind or just a bind to choose what different notes you want

### ISSUE THREAD

**Issue by kitinho** [ShadowMario/FNF-PsychEngine#2009]
### What feature do you want to get added on the base engine?

ENG
hello, my sugestion is make a keybind to choose different types of notes just pressing a botton 
![image](https://user-images.githubusercontent.com/69540352/145712901-b3d2693a-0f6c-44ec-9ae4-7d5742692639.png)

example: 
if you press like alt + 1, you choose the Alt Animation note.
alt + 2, Hey! note, etc

BR (pro shadow)
minha sugestão  é fazer uma tecla bindavel ou uma padrão no chart editor para poder trocar facilmente estre as setas customizadas, como mostrei no exemplo acima, acharia uma mecânica útil e de mais fácil acesso pro pessoal.

**Comment by ShadowMario** [comment]
I don't plan in adding that.
