### ISSUE TITLE
Hurt notes have really shitty hitboxes

### ISSUE THREAD

**Issue by PersonNanoexe** [ShadowMario/FNF-PsychEngine#2014]
### Describe your bug here.

Placing a hurt note before or after a normal note will cause you to hit the hurt note about 84% of the time. Can easily be recreated

### Command Prompt/Terminal logs (if existing)

```bash
none
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing gameplay wise, this issue has always been a problem, even in normal versions of the engine

**Comment by KutikiPlayz** [comment]
I think that's just your accuracy. I have no issues with this

**Comment by TBiscuit1** [comment]
Would expect that the code make negative notes have a smaller hitbox and have less priority then normal notes

If this isn't the case, then yeah it can be a bit legitimate to think that the hitbox are a bit rough

**Comment by ShadowMario** [comment]
Hurt notes have the same priority as normal notes, simply don't put them behind normal notes and don't hit normal notes too early.
