### ISSUE TITLE
Week 7

### ISSUE THREAD

**Issue by endergames231** [ShadowMario/FNF-PsychEngine#2015]
### What feature do you want to get added on the base engine?

will week 7 be added?

**Comment by DaBanana64** [comment]
Port it by yourself.

**Comment by endergames231** [comment]
thank you

**Comment by kitinho** [comment]
the week 7 release when the official source code of week 7 an 8 come public

**Comment by DEV-idiotXD** [comment]
Its actually in the fnf psych extra keys thing so ya just get tht

**Comment by ShadowMario** [comment]
Stupid issue to be honest
