### ISSUE TITLE
Need help with note colors

### ISSUE THREAD

**Issue by CR1T1Cal-labs** [ShadowMario/FNF-PsychEngine#2016]
### Describe your problem here.

Yeah, so I'm making a mod and I need to change the note default color. Does somebody know how to make this? Thanks

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64 and HTML5

**Comment by HiroMizuki** [comment]
you'll need to edit the image yourself at animate/flash or at another program of editing image

**Comment by CR1T1Cal-labs** [comment]
> you'll need to edit the image yourself at animate/flash or at another program of editing image

thanks bro
