### ISSUE TITLE
Copying a Section will result in crash.

### ISSUE THREAD

**Issue by nbonnie2** [ShadowMario/FNF-PsychEngine#2023]
### Describe your bug here.

I was working on my mod, and trying to copy a section in 0.5.0 and the game crashed, any devs please help fix this bug :(
(Chart editor)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing, using a modfolder.

**Comment by ShadowMario** [comment]
Looking into it right now 👍

**Comment by ShadowMario** [comment]
Issue was the following: I forgot to update the events syntax mid-development.
Should be fixed on the main github repo now.
