### ISSUE TITLE
Can't build the game

### ISSUE THREAD

**Issue by YoshiPL12** [ShadowMario/FNF-PsychEngine#2024]
### Describe your bug here.

Hi, When i build psych engine it pop's up an error saying source/StoryMenuState.hx:323: characters 12-14 : Expected )

can you help me why this is happening, any way's thank's

### Command Prompt/Terminal logs (if existing)

```bash
lime test windows -debug
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't do anything, new and fresh source code

**Comment by ArcticAgent** [comment]
I installed Haxe 4.2.4 and it worked fine

**Comment by ArcticAgent** [comment]
https://haxe.org/download/

**Comment by ShadowMario** [comment]
This was already fixed on the main repo
