### ISSUE TITLE
Remotely modifying the source code with the base game

### ISSUE THREAD

**Issue by Coolboy0516** [ShadowMario/FNF-PsychEngine#2025]
### What feature do you want to get added on the base engine?

I want a feature that lets you remotely modify the source code in the base game like adding 6k, new difficulties, winning icons, and modifying the whole menu without the need for downloading the source code.

**Comment by KutikiPlayz** [comment]
I don't even think that's possible

**Comment by nintendofan44** [comment]
> I don't even think that's possible

i think the same

**Comment by ShadowMario** [comment]
No LOL, i'm a coder, not a magician.

**Comment by Coolboy0516** [comment]
Understandible
