### ISSUE TITLE
Compiling Problem

### ISSUE THREAD

**Issue by MatteoNobler** [ShadowMario/FNF-PsychEngine#2028]
### Describe your bug here.

C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:11: characters 8-37 : Type not found : flixel.util.FlxDirectionFlags
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:484: characters 21-25 : Unknown identifier : WALL
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:504: characters 21-25 : Unknown identifier : WALL
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:530: characters 21-28 : Unknown identifier : CEILING
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:550: characters 21-26 : Unknown identifier : FLOOR

I did not modify anything; the only thing i did was updating Haxe from 4.1.5 to 4.2.4 (as ShadowMario suggest to use the latest Haxe version to build the engine)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't

**Comment by ShadowMario** [comment]
You forgot to install something (Most likely related to the flixel packages)
