### ISSUE TITLE
Cutscene crashes the game and was ran in a very questionable way

### ISSUE THREAD

**Issue by Zero-dev333** [ShadowMario/FNF-PsychEngine#2030]
### Describe your bug here.

So I tried to run the cutscene lua script exactly downloaded from the wiki and put the lua file in the /data folder and the video in the /videos folder. And it had apparently crashed my game and showed that the video path was ran very weirdly.

![video test fail](https://user-images.githubusercontent.com/96021541/145725870-4f7dd2b1-d12b-4161-b75c-750fe16bf349.png)
![code](https://user-images.githubusercontent.com/96021541/145726299-989e67d2-b667-4b50-a831-f6dc3948214b.png)
![file](https://user-images.githubusercontent.com/96021541/145726301-79e0d011-6bb4-461d-814a-bd65669e0e53.png)

I looked at youtube videos, the discord server, and the wiki itself to see if there are any similar problems but there's 0.
I also took a look at the source code it was definitely suppose to just say "Couldnt find video file: testVideo".
I tried to also start the cutscene by doing it in the source code but the same thing just happened so it's leaving me with no clues on how to fix this

### Command Prompt/Terminal logs (if existing)

```bash
settin' path: file:///C:\Users\*redacted*\Documents\Funkin-master\export\release\windows\bin//mods/videos/testVideo.mp4
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't

**Comment by ShadowMario** [comment]
If you're on Windows x32, videos are not supported.
If you're on Windows x64, are you sure the lua script is running?

And how exactly is it running "in a questionable way"???

**Comment by Zero-dev333** [comment]
> If you're on Windows x32, videos are not supported. If you're on Windows x64, are you sure the lua script is running?
> 
> And how exactly is it running "in a questionable way"???

i'm running on Windows x64 and yes it's said in the command prompt that the lua script is running.
and the "questionable way" of it being ran was in the command prompt setting path: "mods\bin//mods/videos", unless if it was really suppose to be like that?

**Comment by ShadowMario** [comment]
> setting path: "mods\bin//mods/videos", unless if it was really suppose to be like that?

Yeah that's what it's supposed to do.

Try `debugPrint('test');` below `startVideo` and tell me if it prints test on the left upper corner of the screen.

**Comment by Zero-dev333** [comment]
> > setting path: "mods\bin//mods/videos", unless if it was really suppose to be like that?
> 
> Yeah that's what it's supposed to do.
> 
> Try `debugPrint('test');` below `startVideo` and tell me if it prints test on the left upper corner of the screen.

nope, same result. It crashed before anything else happens

**Comment by ShadowMario** [comment]
Since you're on source code anyway:

![Screenshot_3](https://user-images.githubusercontent.com/44785097/145877531-beb12e82-f5ae-4139-9cae-522c87e95c7c.png)

Do this, but change the startDialogue to startVideo

**Comment by Zero-dev333** [comment]
> Since you're on source code anyway:
> 
> ![Screenshot_3](https://user-images.githubusercontent.com/44785097/145877531-beb12e82-f5ae-4139-9cae-522c87e95c7c.png)
> 
> Do this, but change the startDialogue to startVideo

![image](https://user-images.githubusercontent.com/96021541/145878919-f02ab91f-a4a8-4b0b-b0dc-baa1a7e7eb6d.png)

yeahh sadly I also tried this, and also had the same result.

**Comment by Zero-dev333** [comment]
okay I've probably wasted enough of your time, I decided to try Kade Engine's way of playing the cutscenes which have worked for me, but took me 10x longer than it should've with just a simple code in Pysch Engine. Thank you for your assistance though
