### ISSUE TITLE
Source Code Won't Build (No Changes Made)

### ISSUE THREAD

**Issue by xLinkmain** [ShadowMario/FNF-PsychEngine#2037]
### Describe your bug here.

I downloaded a fresh psych engine 0.5 source, then tried to build it and it says there's an error in StoryMenuState.hx

![Screenshot 2021-12-12 122234](https://user-images.githubusercontent.com/96023844/145728259-914f8d0c-f963-498f-93c3-cdbf4b2d1830.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by KutikiPlayz** [comment]
Make sure your haxe version is 4.2.4 and not 4.1.5
https://haxe.org/download/

**Comment by xLinkmain** [comment]
Thanks!
