### ISSUE TITLE
Refuses to build

### ISSUE THREAD

**Issue by SlickFromMars** [ShadowMario/FNF-PsychEngine#2038]
### Describe your bug here.

Refuses to build due to an issue. I have NOT modified the source code.

### Command Prompt/Terminal logs (if existing)

```bash
source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by CrusherMods** [comment]
You gotta update Haxe

**Comment by ShadowMario** [comment]
This was already fixed on the main repo.
