### ISSUE TITLE
Play On Opponents Side (like .exe)

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#2043]
### Describe your problem here.

can someone give me a code for playing on a opponent's side, like in vs .exe triple trouble

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

idk

**Comment by AetherLynx** [comment]
You can use this custom event #893 and move player's arrows to opponent side, and opponent's arrows to player's side, etc.

**Comment by ShadowMario** [comment]
This is not the place for requesting code from other people.
