### ISSUE TITLE
Game crashes when loading into a song

### ISSUE THREAD

**Issue by KutikiPlayz** [ShadowMario/FNF-PsychEngine#2044]
### Describe your problem here.

For some reason, whenever I load into a song, the game will crash. I've done some testing and figured out at least that it only crashes if the stage isn't a specific one.

https://user-images.githubusercontent.com/73810550/145733590-e6106d4c-bb5e-48fb-8e3e-a286f9301e7b.mp4

Here's a vid of me opening a song with that stage, and then me opening a song without that stage. If I go into the chart editor and change the stage to the working one, then it'll play any song just fine.
I've been digging through all my commits trying to figure out when and where I went wrong in my code but I can't find anything, this only started happening, or at least I only noticed it right after I added a new song. I've tried getting rid of all the code for that stage but the game still crashes if it isn't that stage.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added some stages, note types, and songs

**Comment by ShadowMario** [comment]
Run `lime test windows -debug`

**Comment by KutikiPlayz** [comment]
When I load into a song it gives me a popup saying "Null Object Reference"

**Comment by tposejank** [comment]
What does the terminal say

**Comment by ShadowMario** [comment]
> When I load into a song it gives me a popup saying "Null Object Reference"

Yeah but what does the command prompt/terminal says???

**Comment by KutikiPlayz** [comment]
> Yeah but what does the command prompt/terminal says???

Nothing

**Comment by KutikiPlayz** [comment]
oh shit wait I'm blind
it says this:

Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 25
Called from ApplicationMain::create ApplicationMain.hx line 130
Called from lime.app.Application::exec lime/app/Application.hx line 150
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 146
Called from lime._internal.backend.native.NativeApplication::handleRenderEvent lime/_internal/backend/native/NativeApplication.hx line 370
Called from lime.app._Event_lime_graphics_RenderContext_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from openfl.display.Stage::__onLimeRender openfl/display/Stage.hx line 1950
Called from openfl.display.Stage::__broadcastEvent openfl/display/Stage.hx line 1166
Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 1399
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 551
Called from flixel.FlxGame::step flixel/FlxGame.hx line 677
Called from flixel.FlxGame::update flixel/FlxGame.hx line 745
Called from flixel.util.FlxTimerManager::update flixel/util/FlxTimer.hx line 285
Called from flixel.util.FlxTimer::onLoopFinished flixel/util/FlxTimer.hx line 195
Called from PlayState::startCountdown PlayState.hx line 1980

and then the game crashes

**Comment by KutikiPlayz** [comment]
I figured it out

**Comment by CosmicKris** [comment]
that keeps happening to me on the Dusk Till Dawn mod, but the song itself crashes, idk if its for coding or for the files

**Comment by ericbadly** [comment]
help

**Comment by CPPxfnfmodsmaker** [comment]
tell me then

**Comment by Noel3454565FNF** [comment]
sam, crashing on ALL song in 6.3 but not on 5.2
