### ISSUE TITLE
Songs get softlocked and won't play

### ISSUE THREAD

**Issue by JavoniCraft** [ShadowMario/FNF-PsychEngine#2045]
### Describe your problem here.

When I try to import my own songs, (usually .mp3 format) they won't start playing. The song timeline at the top is set to 0:00 immediately, and the arrows stay in their position. There also isn't any Terminal log for this. Is there anything I can do about it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Added my own music and charting

**Comment by KutikiPlayz** [comment]
The game wont read mp3 you have to use ogg

**Comment by JavoniCraft** [comment]
> The game wont read mp3 you have to use ogg

I used mp3 too.

**Comment by AetherLynx** [comment]
Check the following:

- in the song's .JSON (chart) check the "song: " field is the same name as your song in the songs folder
- That you have an Inst and Voices with the .ogg extension in your song folder
- If your song doesn't have a voice track make sure that in the .JSON the field "needsVoices: " is set to false.
- That the data and song folder have the same name
- If it has a space in it, try changing the space to a dash. " - "

**Comment by JavoniCraft** [comment]
> Check the following:
> 
> * in the song's .JSON (chart) check the "song: " field is the same name as your song in the songs folder
> * That you have an Inst and Voices with the .ogg extension in your song folder
> * If your song doesn't have a voice track make sure that in the .JSON the field "needsVoices: " is set to false.
> * That the data and song folder have the same name
> * If it has a space in it, try changing the space to a dash. " - "

Checked, and unfortunately nothing changed.

**Comment by nintendofan44** [comment]
maybe you disconnected your audio source without knowing???
that happens when you take of your earphones or headphones off your computer

**Comment by JavoniCraft** [comment]
> maybe you disconnected your audio source without knowing??? that happens when you take of your earphones or headphones off your computer

No, it has nothing to do with that.

**Comment by AetherLynx** [comment]
Can you send the mod in a zip so i or someone can check what's wrong?

**Comment by ShadowMario** [comment]
Missing audio file.
Be sure your chart includes this file: `mods/songs/your-song-name/Inst.ogg`
It's very important that you put it inside `songs` folder, not `music`
