### ISSUE TITLE
Engine will not build.

### ISSUE THREAD

**Issue by QuagFire101** [ShadowMario/FNF-PsychEngine#2049]
### Describe your bug here.

I downloaded the 0.5 version of PsychEngine, and tried to build it for the first time. 

I got this as an error 
![image](https://user-images.githubusercontent.com/90576570/145740029-b34c9c6c-1716-4a05-b998-7b9f289cb151.png)

As a note, I did not TOUCH the storymenustate for the mod, so I just got a random error that is keeping me from building the engine.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope. Nothing.

**Comment by CrusherMods** [comment]
Update Haxe

**Comment by QuagFire101** [comment]
> Update Haxe

Do I do it through command prompt commands or just from the website?

**Comment by CrusherMods** [comment]
> > Update Haxe
> 
> Do I do it through command prompt commands or just from the website?

I recommend the website

**Comment by QuagFire101** [comment]
> > > Update Haxe
> > 
> > 
> > Do I do it through command prompt commands or just from the website?
> 
> I recommend the website

![image](https://user-images.githubusercontent.com/90576570/145741427-5d53ef11-9397-4f22-a4f2-2ce9447eb7ba.png)
Uhhhhhhhhhhh don't think that really fixed anything

**Comment by ShadowMario** [comment]
Was already fixed on main repo.
