### ISSUE TITLE
literally just selected the blammed lights event and the entire engine crashed

### ISSUE THREAD

**Issue by blblblsdlbsdbs** [ShadowMario/FNF-PsychEngine#2050]
### Describe your bug here.

lmao i didnt even place it and the game just imploded

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope, just downloaded precompiled V5 build from GB

**Comment by ShadowMario** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/44785097/145744492-b04a2702-3209-4725-b026-5ff0609df4db.png)
![Screenshot_1](https://user-images.githubusercontent.com/44785097/145744489-17e86098-e72a-4e5f-824c-efb135ed0453.png)

uhhh

**Comment by titopops** [comment]
it probably has something to do with the stage, are you playing a base game stage or a custom stage?
