### ISSUE TITLE
Major Lag Spikes

### ISSUE THREAD

**Issue by tuntor689** [ShadowMario/FNF-PsychEngine#2054]
### Describe your bug here.

I had ported over Chaos to Psych Engine 0.4 because I didn't like the fact it was in Kade Engine 1.5. I went through it all and it all seemed fine. Psych Engine 0.5b releases and I put it on there and everything still works as intended. I put it on Psych Engine 0.5 and now the game freezes temporarily whenever I try to change character. And some other songs just don't work.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i just ported over some stuff and mods and it worked fine until I put it on the latest release.

**Comment by crispyboi24** [comment]
I think kade engine charts lag on other engines. Dunno for sure tho

**Comment by tuntor689** [comment]
> 

i still don't understand why it's freezing, i put in the change character in there and it was working fine before this update

**Comment by ShadowMario** [comment]
The Events.json files format changed on the last update, try opening your events and saving again on Chart Editor.
