### ISSUE TITLE
can't to build again

### ISSUE THREAD

**Issue by koko123tutorial** [ShadowMario/FNF-PsychEngine#2058]
### Describe your problem here.

what happend?
![image](https://user-images.githubusercontent.com/87571249/145761437-c8076b0b-295c-474b-8f9a-64698f822fb3.png)

help me PLZZZ

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by tposejank** [comment]
You must install Visual Studio Community and all the components for compilation. It is specified in the README.md of the FNF original repo.
