### ISSUE TITLE
Note Size & Scroll Speed

### ISSUE THREAD

**Issue by Gui-iago** [ShadowMario/FNF-PsychEngine#2059]
### What feature do you want to get added on the base engine?

previously (on https://github.com/ShadowMario/FNF-PsychEngine/commit/48337f6abbafb94206c88e1fcda9ccf0650007c2), 
alanyao added Note Size and Scroll Speed, what happened for the removal of it, and could we get it back?

**Comment by ShadowMario** [comment]
Note size was removed because it caused too many issues.
Scroll Speed can already be changed, PLEASE, check the engine fully before making an issue here.
