### ISSUE TITLE
Soft code the UI skins

### ISSUE THREAD

**Issue by ProgramerGamerZone** [ShadowMario/FNF-PsychEngine#2062]
### What feature do you want to get added on the base engine?

Basically making us able to add a UI type for a song, so instead of just arrow skins and splash, the entire UI (Ratings, Countdown (cuz I am trying to make the countdown invisible), etc).

**Comment by Ordinary3** [comment]
this feature is already in the game

**Comment by Templarfreak** [comment]
you can probably change a lot about the UI Lua-side using `setProperty`, `setPropertyFromClass`, and `setPropertyFromGroup`, just make sure what you're trying to set isn't read-only or private, if it is you'll have to go into the code to change that

**Comment by ShadowMario** [comment]
You can already do that if you're good enough with Lua.
