### ISSUE TITLE
Visual Studio Compilation Error

### ISSUE THREAD

**Issue by LightUnreal-Alt** [ShadowMario/FNF-PsychEngine#2063]
### Describe your problem here.

I tried to build source code of Psych Engine. I typed 'lime test windows' and go this
`C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\yvals.h(12): fatal error C1083: Не удается открыть файл включение: crtdbg.h: No such file or directory` 
Yeah, i'm Russian . That Russian thing means: 'Cannot open include file'

I need to solve this problem, but i can't . Please help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No,i didn't edit anything

**Comment by ShadowMario** [comment]
You're missing some library/SDK, try checking a tutorial online for building FNF and follow the instructions.
