### ISSUE TITLE
Custom note the opponent doesnt hit

### ISSUE THREAD

**Issue by DrebDaDev** [ShadowMario/FNF-PsychEngine#2064]
### What is your question?

the name says it all, i want to make a custom note that the opponent cpu completely ignores, i know how to do normal custom notes but not ones the cpu ignores, i dont even know if its possible, any help?

**Comment by tposejank** [comment]
for lua:
`
if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
       setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true)
end
`

for the source code, its simpler.

**Comment by DrebDaDev** [comment]
im using source code

**Comment by ShadowMario** [comment]
> im using source code
![Screenshot_2](https://user-images.githubusercontent.com/44785097/145866790-1de318e5-133f-4b78-84f5-e39ab9ea0e12.png)

Inside Note.hx

**Comment by DrebDaDev** [comment]
thanks mr shadow mario
