### ISSUE TITLE
Death Quotes

### ISSUE THREAD

**Issue by BrightEyesFox** [ShadowMario/FNF-PsychEngine#2068]
### Describe your problem here.

How do I add in death lines/quotes into the mod? I have multiple lines for each song and I want there to be different lines for different songs.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I have not yet edited the source, only added a single song.

**Comment by Templarfreak** [comment]
you can use Lua scripting, by either making a character or stage Lua script, using the `onGameOver` callback and getting the current song you're in via the built-in `songName` Lua variable or via the Lua function `getProperty('SONG.song')`

**Comment by ShadowMario** [comment]
you can use onGameOverStart() callback on Lua and use playSound() for playing the quotes.
It isn't something very easy and it might require you to have some minor knowledge on Lua so i can't elaborate here.

**Comment by MayoALT** [comment]
1000th issue closed pog

**Comment by CrusherMods** [comment]
> 1000th issue closed pog

I was about to say lol

**Comment by PDL2CGamejolt** [comment]
can you send a code

**Comment by ThePsychEngineFan** [comment]
> 1000th issue closed pog

pogr
