### ISSUE TITLE
Lua stage crashes

### ISSUE THREAD

**Issue by fireredfan7** [ShadowMario/FNF-PsychEngine#2072]
### Describe your bug here.

I can’t get my Mac build from actions to load the example stage from the wiki. It always crashes. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
Open the stage in a debug build and tell me what the terminal says.

**Comment by ShadowMario** [comment]
Soooooo...?

**Comment by fireredfan7** [comment]
> Soooooo...?

sorry

**Comment by fireredfan7** [comment]
I updated it

**Comment by fireredfan7** [comment]
yoooooooooooo I fixed it 
I just had to replace "haxelib install linc_luajit" to "haxelib git linc_luajit https://github.com/AndreiRudenko/linc_luajit" in my own fork.
