### ISSUE TITLE
More Events/Notetypes

### ISSUE THREAD

**Issue by TEKBot101** [ShadowMario/FNF-PsychEngine#2073]
### What is your question?

I've been meaning to ask you this, can you add more events/notetypes? Like a danger notetype, a Change Stage event, possibly Modchart events (plural for arrow transparency moving arrows etc...) and maybe... More?

**Comment by DaBanana64** [comment]
> ### What is your question?
> I've been meaning to ask you this, can you add more events/notetypes? Like a danger notetype, a Change Stage event, possibly Modchart events (plural for arrow transparency moving arrows etc...) and maybe... More?

Yes, you can add a danger notetype that has a same function as a hurtnote.
But a change stage event is not possible.
And modcharts are basically done with .Lua.

**Comment by tposejank** [comment]
stop requesting this
just learn how to do the thing itself with code omfg
hhhh

**Comment by TEKBot101** [comment]
No, not that, like add them to OFFICIAL psych engine

**Comment by Eric-R-Malice** [comment]
> > ### What is your question?
> > I've been meaning to ask you this, can you add more events/notetypes? Like a danger notetype, a Change Stage event, possibly Modchart events (plural for arrow transparency moving arrows etc...) and maybe... More?
> 
> Yes, you can add a danger notetype that has a same function as a hurtnote. But a change stage event is not possible. And modcharts are basically done with .Lua.

erm, actually.
