### ISSUE TITLE
Miss animations playing over normal animations

### ISSUE THREAD

**Issue by BrightEyesFox** [ShadowMario/FNF-PsychEngine#2075]
### Describe your bug here.

this happens every single time when i try to create a new playable character and ive never gotten a fix for it. whenever i make a character the regular sing animations always get replaced by the miss animations and i can never seem to get this fixed

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I have not yet edited the source, only added a single song.

**Comment by BrightEyesFox** [comment]
also, it refuses to scale at all.

**Comment by MayoALT** [comment]
add a 0 at the end of the non-miss animations and edit the scale within the json

**Comment by BrightEyesFox** [comment]
where am i supposed to put a 0?

**Comment by CrusherMods** [comment]
> where am i supposed to put a 0?

at the end of the xml name in the character editor

**Comment by ShadowMario** [comment]
> at the end of the xml name in the character editor

^
Check how Boyfriend's sing animations work in Character Editor and you will understand it.
