### ISSUE TITLE
not adding lua sprites?

### ISSUE THREAD

**Issue by FoxyGamer1980** [ShadowMario/FNF-PsychEngine#2078]
### Describe your problem here.

i'm trying to add a lua sprite to the game when playing, but for some reason, when i make it and try to add it in a step, it doesn't do it? any help on how to fix this? 

this is what i did:
function onCreate()
    makeLuaSprite('tag', 'image', -400, -200)
    setScrollFactor('tag', 0, 0)
    scaleObject('tag', 1.2, 1.2)
end

function onBeatHit()
    AddLuaSprite('tag', true)
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by bbpanzu** [comment]
change the sprite's x and y to like 400 and 200. maybe it's there but not in camera

**Comment by tposejank** [comment]
WHEN THE A
IS UPPER CASE

**Comment by FoxyGamer1980** [comment]
> change the sprite's x and y to like 400 and 200. maybe it's there but not in camera

i tried it in the OnCreate() thing, and it works there

**Comment by FoxyGamer1980** [comment]
actually wait no it's not working on oncreate too
