### ISSUE TITLE
how to add cutscenes?

### ISSUE THREAD

**Issue by ityaboisnowy** [ShadowMario/FNF-PsychEngine#208]
i animated a video for my mod but dont know how to add cutscenes

**Comment by ShadowMario** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API
Check the examples

**Comment by 12th90ongithub** [comment]
local allowCountdown=false
function onStartCountdown()
    if not allowCountdown and isStoryMode and not seenCutscene then --Block the first countdown
        startVideo('');
        allowCountdown = true;
        return Function_Stop;
    end
    return Function_Continue
    end
