### ISSUE TITLE
source/StoryMenuState.hx:323: characters 12-14 : Expected

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#2080]
### Describe your problem here.

It keeps saying source/StoryMenuState.hx:323: characters 12-14 : Expected
I have the latest Haxe version. I don't know what I'm doing wrong can you help me please

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by CrusherMods** [comment]
You sure its not Haxe 4.1.5

**Comment by tposejank** [comment]
type haxe --version in your cmd and tell us what it says

**Comment by NotEpik** [comment]
"I have the latest Haxe version."
me: bruh

**Comment by SonicXFire1987** [comment]
I have 4.2.4 but it still doesn't work

**Comment by SonicXFire1987** [comment]
I also have Git 2.34.1 Does that have anything to do with it?

**Comment by ShadowMario** [comment]
`It keeps saying source/StoryMenuState.hx:323: characters 12-14 : Expected`
Post the full error

**Comment by festtt** [comment]
since i got it too  here it is (its one line btw) : source/StoryMenuState.hx:323: characters 12-14 : Expected )

**Comment by SonicXFire1987** [comment]
I already took care of this error but i have another error 
https://github.com/ShadowMario/FNF-PsychEngine/issues/2190
Info is in this one
