### ISSUE TITLE
how to make a cutscene before a dialogue and then a ending cutscene

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#2081]
### Describe your problem here.

idk how to do that

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MrClogsworthYT** [comment]
make a song 0 seconds long lol

**Comment by PDL2CGamejolt** [comment]
uh

**Comment by PDL2CGamejolt** [comment]
no

**Comment by MrClogsworthYT** [comment]
k

**Comment by XRocketBoiX** [comment]
Here,

-- Dialogue shit
local playDialogue = false;
local playedVideo = false;
function onStartCountdown()
	if not playedVideo and isStoryMode and not seenCutscene then -- Block the first countdown and play video cutscene
		startVideo('Cutscene');
		playDialogue = true;
		playedVideo = true;
		return Function_Stop;
	elseif playDialogue then -- Block the second countdown and start a timer of 0.8 seconds to play the dialogue
		playedVideo = true;
		playDialogue = false;
		playMusic('DaveDialogue', 0, true);
		setProperty('inCutscene', true);

		runTimer('startDialogue', 2.75);

		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('dialogue', 'dialoguemusic');
	end
end

-- Dialogue (When a dialogue is finished, it calls startCountdown again)
function onNextDialogue(count)
	-- triggered when the next dialogue line starts, 'line' starts with 1
end

function onSkipDialogue(count)
	-- triggered when you press Enter and skip a dialogue line that was still being typed, dialogue line starts with 1
end


This should help.
