### ISSUE TITLE
Bug: Lag with HUD

### ISSUE THREAD

**Issue by VMGuy23** [ShadowMario/FNF-PsychEngine#2083]
On Lower end CPUs, where FNF can run fine but maybe goes a little under at 251fps, ha in the HUD on and Persistent Cached Data off causes considerable lag during the player's turn. Even though I don't have a perfect reason, I guess that it gets the font every time a number that isnt already there and that lags, it, which is why Persistent cached data fixes it. But that's just a guess.

**Comment by tposejank** [comment]
lerp values

**Comment by VMGuy23** [comment]
What

**Comment by ShadowMario** [comment]
Never seen this issue before, i can't replicate it.

**Comment by VMGuy23** [comment]
You need  pc that can funk OK but fps isn't Stable at 120
