### ISSUE TITLE
Note strum

### ISSUE THREAD

**Issue by RareBeeCodez** [ShadowMario/FNF-PsychEngine#2084]
### What is your question?

Is it possible to disable the enemy note strum glow and note splashes for the engine? 

Edit: I mean like for the entire mod

**Comment by CrusherMods** [comment]
note splashes can be turn off in settings and enemy note strums WHY WOULD YOU WANNA TURN THAT OFF

**Comment by RareBeeCodez** [comment]
I don't like it

**Comment by RareBeeCodez** [comment]
I mean like for the entire mod

**Comment by CrusherMods** [comment]
> I mean like for the entire mod

oh idk sorry

**Comment by KutikiPlayz** [comment]
just remove the code that adds that stuff

**Comment by ShadowMario** [comment]
Note splashes can be turned off, but the glow cannot.

**Comment by RareBeeCodez** [comment]
I mean, like in the source code @ShadowMario

**Comment by Gui-iago** [comment]
> I mean, like in the source code @ShadowMario

@RareBeeCodez 
search for this on PlayState.hx
`StrumPlayAnim(true, Std.int(Math.abs(note.noteData)) % 4, time)`
delete that, and `note.hitByOpponent = true;` too
I'd recommend making this into a toggle, like this

![image](https://user-images.githubusercontent.com/45212377/148343314-b8a32ac2-b693-4137-a18e-c0194b590aa3.png)

then just set it up on ClientPrefs.hx, so you can enable and disable when you want to
