### ISSUE TITLE
Chart won't load in-game, how do I overcome it? (0.5b)

### ISSUE THREAD

**Issue by osogames24fanosogames** [ShadowMario/FNF-PsychEngine#2104]
### Describe your problem here.

So I was working on a port of V.S. Dave and Bambi into Psych Engine with some extra stuff (even though it's already been done), but I couldn't help but notice this issue. Whenever I try to chart dave's songs, I can't press enter. If I do, it crashes the game. I was doing it on a song that at least has a .json file for the chart. Now, I'm gonna say something. This never happened on the older versions on Psych Engine (mainly 0.4.2). Also, the charts are fine in debug mode for the most part, so I don't understand why I have this issue, especially because it doesn't happen in other songs. And I want to get around it. How do I do that?

And I think it might be because i'm using source assets instead of mod assets, but doing it like that also worked fine on older versions.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added dave, added dave stage on PlayState.hx, and also added house and insanity, as well as change the week order

**Comment by bbpanzu** [comment]
compile with -debug and see what the terminal says. most likely a null object ref

**Comment by osogames24fanosogames** [comment]
it gives me this:

`Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 545
Called from flixel.FlxGame::step flixel/FlxGame.hx line 677
Called from flixel.FlxGame::update flixel/FlxGame.hx line 747
Called from flixel.FlxState::tryUpdate flixel/FlxState.hx line 202
Called from FreeplayState::update FreeplayState.hx line 269
Called from Song::loadFromJson Song.hx line 70
Called from sys.io.File::getContent /usr/local/lib/haxe/std/cpp/_std/sys/io/File.hx line 30
Error : [file_contents,assets/data/house/house-hard.json]`

**Comment by tposejank** [comment]
what does the terminal/cmd/powershell say after the another edit

**Comment by bbpanzu** [comment]
make sure the files exist both in the source assets file and the export assets filea

**Comment by osogames24fanosogames** [comment]
> make sure the files exist both in the source assets file and the export assets filea

i checked, the files exist inside of the app. So I'm starting to believe it's that I put it in the wrong place
