### ISSUE TITLE
Is it possible to tint a sprite using Lua?

### ISSUE THREAD

**Issue by FuseIsHere813** [ShadowMario/FNF-PsychEngine#2107]
### What is your question?

You read the title, so, I wonder if there is a variable for tinting a sprite on LUA? If not, I will close this. If so, what is that variable?

**Comment by tposejank** [comment]
setProperty('spr.color', getColorFromHex('012345'))
that might work

**Comment by PoleyMagik** [comment]
> setProperty('spr.color', getColorFromHex('012345')) that might work

yes, that's roughly correct. Input an RGBA hex code for color (alpha is important, it determines how potent the tint is).
