### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by MatteoNobler** [ShadowMario/FNF-PsychEngine#2108]
### Describe your bug here.

Cannot compile the game; am I missing some libraries?
(For the one who is asking: yes,I have the latest Haxe Version: 4.2.4)

### Command Prompt/Terminal logs (if existing)

```bash
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:11: characters 8-37 : Type not found : flixel.util.FlxDirectionFlags
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:484: characters 21-25 : Unknown identifier : WALL
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:504: characters 21-25 : Unknown identifier : WALL
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:530: characters 21-28 : Unknown identifier : CEILING
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:550: characters 21-26 : Unknown identifier : FLOOR
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, fresh build

**Comment by CrusherMods** [comment]
I think this was answered in another issue, something when you were installing haxe for fnf is missing

**Comment by MatteoNobler** [comment]
> I think this was answered in another issue, something when you were installing haxe for fnf is missing

Do you have any suggest on what is missing? Anyway, thank you, I will try to search the answer in the other issues

**Comment by CrusherMods** [comment]
> > > I think this was answered in another issue, something when you were installing haxe for fnf is missing
> > 
> > 
> > Do you have any suggest on what is missing? Anyway, thank you, I will try to search the answer in the other issues
> 
> Just redo to the part where you install with commands

and you do find it can you put it here, my friend is also having this problem
