### ISSUE TITLE
add background  on character editor

### ISSUE THREAD

**Issue by foxcool119** [ShadowMario/FNF-PsychEngine#211]

**Comment by foxcool119** [comment]
![image](https://user-images.githubusercontent.com/89747510/135748509-53fd561d-8798-470f-8b7a-c9eddc8be0a1.png)
 hey creator of pe can you add changing background while adding character just like changing stage spooky  and limo stage any stage like adding your own background    (sorry for my bad language )

**Comment by foxcool119** [comment]
![image](https://user-images.githubusercontent.com/89747510/135748742-373ec056-b03b-477c-9fb8-9adfcd4fc42a.png)

**Comment by ShadowMario** [comment]
That would require duplicating code for the stages that are hardcoded, plus it's not really necessary
