### ISSUE TITLE
Alt Idle Animation Event is spelled "Speciied" instead of "Specified"

### ISSUE THREAD

**Issue by SoobGorl** [ShadowMario/FNF-PsychEngine#2110]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/72813628/145989934-b8000230-82d6-4eca-89bb-1fa4e45694ca.png)

engine is **RUINED**

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No edits made.

**Comment by tposejank** [comment]
lmfao

**Comment by SoobGorl** [comment]
Fixed in #2130
