### ISSUE TITLE
I want to put a dialog at the beginning and end of a song!!

### ISSUE THREAD

**Issue by Guranlikesblue** [ShadowMario/FNF-PsychEngine#2111]
### Describe your problem here.

I want to put Dialogue at the beginning and end of the 'Tutorial' song.
I tried various methods but couldn't.
I use both Lua and Source Code.
If you know how to do it, please let me know.
(I'm sorry for my bad English)
![1639481868199](https://user-images.githubusercontent.com/89185139/145991390-d81cf959-5801-4066-a3cf-d7b711309a5c.jpg)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Add character. Add stages and winning icons in PlayState.hx. Add Custom Note in Lua.

**Comment by bbpanzu** [comment]
wiki

**Comment by Guranlikesblue** [comment]
I looked at the wiki and tried to build it, but the Dialogue wasn't played at the end of the song, only at the beginning of the song.

**Comment by Guranlikesblue** [comment]
Maybe there wasn't much information to present
I built it this way but the Dialogue played only at the beginning of the song and not at the end of it
Do you know what to do?
![1639558786201](https://user-images.githubusercontent.com/89185139/146155560-e999fea4-da61-4a85-822f-d90894d10764.jpg)
![1639558765623](https://user-images.githubusercontent.com/89185139/146155577-90205240-8306-4165-be0c-9483a5d7ce21.jpg)

**Comment by Maxstar13** [comment]
in script.lua
local allowCountdown = false
local startedFirstDialogue = false
local startedEndDialogue = false
function onStartCountdown()
	if not allowCountdown and isStoryMode and not startedFirstDialogue then
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		startedFirstDialogue = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onEndSong()
	if not allowCountdown and isStoryMode and not startedEndDialogue then
		setProperty('inCutscene', true);
		runTimer('startDialogueEnd', 0.8);
		startedEndDialogue = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then
		startDialogue('dialogue', 'tutorial');
	elseif tag == 'startDialogueEnd' then
		startDialogue('dialogueEnd', 'tutorial');
	end
end

**Comment by Guranlikesblue** [comment]
> in script.lua local allowCountdown = false local startedFirstDialogue = false local startedEndDialogue = false function onStartCountdown() if not allowCountdown and isStoryMode and not startedFirstDialogue then setProperty('inCutscene', true); runTimer('startDialogue', 0.8); startedFirstDialogue = true; return Function_Stop; end return Function_Continue; end
> 
> function onEndSong() if not allowCountdown and isStoryMode and not startedEndDialogue then setProperty('inCutscene', true); runTimer('startDialogueEnd', 0.8); startedEndDialogue = true; return Function_Stop; end return Function_Continue; end
> 
> function onTimerCompleted(tag, loops, loopsLeft) if tag == 'startDialogue' then startDialogue('dialogue', 'tutorial'); elseif tag == 'startDialogueEnd' then startDialogue('dialogueEnd', 'tutorial'); end end

I tried to build it, but I couldn't ...

**Comment by FanKid** [comment]
I actually found two posts about this, try this! If it's Story Mode, copy and paste NotEpik's script on #1563

If it's for Freeplay, I tried this with my Sussus-Toogus 6 key rechart, go to post #2223

That's it! Hope it helps.

**Comment by Guranlikesblue** [comment]
> I actually found two posts about this, try this! If it's Story Mode, copy and paste NotEpik's script on #1563
> 
> If it's for Freeplay, I tried this with my Sussus-Toogus 6 key rechart, go to post #2223
> 
> That's it! Hope it helps.

it is complete!!
Thank you!!

But there are still a few problems.
Dialogue plays twice at the beginning of the song.
I don't know what's causing it

**Comment by FanKid** [comment]
Ok I'll send the file to you. Oh, also I was wrong. If you remove 'and isStoryMode', it makes the dialogue play both story mode and freeplay

[dialogue_scripts.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/7737882/dialogue_scripts.zip)

Oh yeah, don't credit me. It's the other people that helped.

**Comment by Guranlikesblue** [comment]
solved!!
Thank you to everyone who gave us comments
