### ISSUE TITLE
custom Spirit based characters crash

### ISSUE THREAD

**Issue by Sanic9999** [ShadowMario/FNF-PsychEngine#2113]
### Describe your bug here.

characters that are based off of Spirit crash. no error message shows up, it just stays black for a bit and closes. it's not a problem with my files, because when i replace Spirit's files with mine my characters works completely fine.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i added a custom character that uses Spirit's json.

**Comment by bbpanzu** [comment]
spirit uses a txt texture atlas while others look for a xml texture atlas.

**Comment by Supersteven72** [comment]
I have a similar issue where i put a sprite in character editor and it worked fine but when i launch it on a song like dad battle and replace the bf player with them and launch it, it just turns black screen for a while till the song played but it still became dark. I thought it was the Sprite but the other sprite i made worked fine and normal. Do you know how I can fix it??

**Comment by Sanic9999** [comment]
> spirit uses a txt texture atlas while others look for a xml texture atlas.

i kind of figured that's what the crash was from.

**Comment by Supersteven72** [comment]
What is it for??

**Comment by Supersteven72** [comment]
> > spirit uses a txt texture atlas while others look for a xml texture atlas.
> 
> i kind of figured that's what the crash was from.

What is it for??
