### ISSUE TITLE
CurBeat always being 0 (Lua)

### ISSUE THREAD

**Issue by SilkyIncorprated** [ShadowMario/FNF-PsychEngine#2117]
### Describe your bug here.

Porting a mod pack from 0.4.2 to 0.5 but the curBeat var is broken

(I could use curStep but thats more time just trying to figure out where the beat is in steps)

Also using DebugPrint shows curBeat is only printing 0

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, it was purely made from lua due to the engine having a pretty cool lua handler

**Comment by crispyboi24** [comment]
> SO now we have to use the set/getProperty function now
> 
> very cool

This was fixed in the latest commit. Go to the actions tab and download on of the latest windows builds. Should work then.
