### ISSUE TITLE
Is botplay gone?

### ISSUE THREAD

**Issue by antoineelcrak** [ShadowMario/FNF-PsychEngine#2118]
### What is your question?

I can't seem to find the botplay button anymore in this update
![psych0 5](https://user-images.githubusercontent.com/86988951/146022191-81e81841-3a6c-4752-8a1b-3a1c9dab9242.PNG)

compared to 0.4.2
![psych0 4 2](https://user-images.githubusercontent.com/86988951/146022224-8cbc9de2-5dff-412f-a6f7-51e53c309787.PNG)

**Comment by DaBanana64** [comment]
No, just press CTRL on your keyboard (either on Storymode or Freeplay) and it's there.
