### ISSUE TITLE
charting state strums

### ISSUE THREAD

**Issue by nintendofan44** [ShadowMario/FNF-PsychEngine#2119]
### Describe your bug here.

when there are hold notes and i think normal ones too
basically in a duet
the strums of the both sections don't light up correctly

https://user-images.githubusercontent.com/85742902/146037727-11056f1c-546e-4c1e-8861-7bc99d33e2d8.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothin

**Comment by tposejank** [comment]
Why is this important tho? The game just doesn't know what data the sustain is, it isn't a note.

**Comment by nintendofan44** [comment]
what about playstate?
this does not happen there

**Comment by nintendofan44** [comment]
oh
ik what is doing that
its the hitsounds
when enabled they do the funny bug

**Comment by nintendofan44** [comment]
https://user-images.githubusercontent.com/85742902/146041403-679e8f85-aeec-41c1-aed2-95b58f5ef463.mp4

**Comment by bbpanzu** [comment]
I'll check it out l8r. thxx

**Comment by nintendofan44** [comment]
> I'll check it out l8r. thxx

👍

**Comment by ShadowMario** [comment]
Update to 0.5

**Comment by nintendofan44** [comment]
but it is

**Comment by nintendofan44** [comment]
downloaded build

**Comment by nintendofan44** [comment]
yay it got fixed
