### ISSUE TITLE
How to use 'goodNoteHit' via Lua script?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#2120]
### What is your question?

There is a sentence in `PlayState.hx`, as follow:
```
callOnLuas('goodNoteHit', [notes.members.indexOf(note), leData, leType, isSus]);
```
How to use `goodNoteHit` via Lua script?

**Comment by ShadowMario** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/blob/main/docs/TemplateScript.lua
