### ISSUE TITLE
A bit of lag with Lua (0.5)

### ISSUE THREAD

**Issue by Maxstar13** [ShadowMario/FNF-PsychEngine#2121]
### Describe your bug here.

I was using 0.5 and im using Lua and when a custom event note anything the game lags so hard

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
Must be your event's fault, you didn't show any code.

**Comment by Maxstar13** [comment]
> Must be your event's fault, you didn't show any code.

note code 
function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is an desviation note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Shot note' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'Shot note'); --Change texture
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', false); --Miss has no penalties
		end
	end
	--debugPrint('Script started!')
	function noteMiss(id, i, noteType, isSustainNote)
		if noteType == 'Shot note' then
			playSound('gotshot', 1)
			setProperty('health', -500);
		characterPlayAnim('boyfriend', 'hurt', true);
		characterPlayAnim('pico', 'down', true);

	end
end
end

function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'Shot note' then
		playSound('gotshot', 1)
		characterPlayAnim('boyfriend', 'dodge', true);
		characterPlayAnim('pico', 'down', true);
	end
end
Note when touched lags also when i use the change character event

**Comment by tposejank** [comment]
* 1: `pico` isn't a valid parameter for `characterPlayAnim`
* 2: The sound `gotshot` might be the problem

**Comment by SrtHero278** [comment]
> * 1: `pico` isn't a valid parameter for `characterPlayAnim`
> * 2: The sound `gotshot` might be the problem

Have to agree. If you want your enemy to play the animation, set the first parameter to `'dad'` and if you're trying to use the singing down animation, use `singDOWN` instead of just `down`.

**Comment by Maxstar13** [comment]
> > * 1: `pico` isn't a valid parameter for `characterPlayAnim`
> > * 2: The sound `gotshot` might be the problem
> 
> Have to agree. If you want your enemy to play the animation, set the first parameter to `'dad'` and if you're trying to use the singing down animation, use `singDOWN` instead of just `down`.

Okay that may be the case but that doesn't explain the lag with the character change event

**Comment by Maxstar13** [comment]
my code is ok all what im reporting is with any event/note makes the game lag

**Comment by ShadowMario** [comment]
Must be your PC then because i never saw anyone else (or atleast don't remember) reporting this issue or anything similar, for god's sake tell me you're not trying to run FNF in a chromebook

**Comment by Maxstar13** [comment]
> Must be your PC then because i never saw anyone else (or atleast don't remember) reporting this issue or anything similar, for god's sake tell me you're not trying to run FNF in a chromebook

Im not in a chromebook my pc runs fine on the other versions of the engine apart from 0.5

**Comment by Maxstar13** [comment]
I figured out the lag
