### ISSUE TITLE
Death spam bug

### ISSUE THREAD

**Issue by sonicfan888** [ShadowMario/FNF-PsychEngine#2122]
### Describe your bug here.

An incredible amount of spam while trying to survive and dying ingame causes the game to crash. Also i just ported my mod from 0.4.2 to 0.5

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Was just porting my psych 0.4.2 mod to psych 0.5

**Comment by sonicfan888** [comment]
Also i meant note spam that caused the game to lag and crash

**Comment by ShadowMario** [comment]
Something could have gone wrong if you merged versions via Github.

**Comment by sonicfan888** [comment]
actually, It is not caused by the note spam, it is caused if you lose all your hp, so it must be an issue with porting older to newer
