### ISSUE TITLE
Porting 0.4.2 to 0.5 issue

### ISSUE THREAD

**Issue by sonicfan888** [ShadowMario/FNF-PsychEngine#2123]
### Describe your bug here.

Some characters have lost their poses causing the game to crash. At first i thought this was something up with the lua scripts but no. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Was just porting my psych 0.4.2 mod to psych 0.5 (same thing as before)

**Comment by ShadowMario** [comment]
"Lost their poses"???

**Comment by sonicfan888** [comment]
i meant that the character had an xml bug thing in which instead of having the normal animation behavior (in the 0.4.2 version of the mod), in 0.5, i think the character had shared the animation names in the xml file with another character, causing the game to crash. (But the idle loaded correctly, the other poses didn't)

**Comment by sonicfan888** [comment]
nevermind, it is an Song issue
