### ISSUE TITLE
Song.hx

### ISSUE THREAD

**Issue by Lite6G** [ShadowMario/FNF-PsychEngine#2134]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/96150137/146087449-65ef05be-5a43-4335-af3b-a64dc89238ec.png)
So i was trying to compile the 0.5 not the 0.5b and this erros just jump into my face

### Command Prompt/Terminal logs (if existing)

```bash
source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by HiroMizuki** [comment]
duplicate of #2022

**Comment by Lite6G** [comment]
> duplicate of #2022
i didn't see that one

**Comment by HiroMizuki** [comment]
> > duplicate of #2022
> > i didn't see that one

well, it is the same error, you'll need to install haxe 4.2.4

**Comment by Lite6G** [comment]
i

**Comment by Lite6G** [comment]
> > > duplicate of #2022
> > > i didn't see that one
> 
> well, it is the same error, you'll need to install haxe 4.2.4

yesterday i install haxe but well

**Comment by Lite6G** [comment]
> > > duplicado de [# 2022](https://github.com/ShadowMario/FNF-PsychEngine/issues/2022) 
> > > no vi ese
> 
> bueno, es el mismo error, necesitará instalar haxe 4.2.4

Uhhh it works now
