### ISSUE TITLE
Can´t enter the game because of something i don´t know

### ISSUE THREAD

**Issue by BlazeGod88** [ShadowMario/FNF-PsychEngine#2136]
### Describe your bug here.

i do all things to do for start the game and it appears this text

C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : Expected TypeDefinition but got {name: _Event_Void_Void, params: [{name: T}], pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47), fields: [{name: canceled, doc:
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : Whether the event was canceled during the previous dispatch
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : , pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:31: characters 2-42), access: [APublic], kind: FProp(default,null,TPath({name: <...>, params: <...>, pos: <...>, pack: <...>}),null), meta: [], name_pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:31: characters 13-21)},{name: __repeat, doc: null,
pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:34: characters 29-61), access: [APublic], kind: FVar(TPath({name: <...>, params: <...>, pos: <...>, pack: <...>}),null), meta: [{name: :noCompletion, params: [], pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:34: characters 2-16)},{name: :dox, params: [<...>], pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:34: characters 17-22)}], name_pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:34: characters 40-48)},{name: __priorities, doc: null, pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:36: characters 17-53), access: [APrivate], kind: FVar(TPath({name: <...>, params: <...>, pos: <...>, pack: <...>}),null), meta: [{name: :noCompletion, params: [], pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:36: characters 2-16)}], name_pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:36: characters 29-41)},{name: new, doc:
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : Creates a new Event instance
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : , pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:41: lines 41-49), access: [APublic], kind: FFun({ret: null, params: [], expr: {pos: <...>, expr: <...>}, args: []}), meta:
[], name_pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:41: characters 18-21)},{name: add, doc:
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : Adds a new event listener
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : @param listener A callback that
matches the signature of the event
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : @param once Whether to receive an event dispatch only once, or each time it is fired
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : @param priority The priority for this listener, a higher priority will be dispatched sooner
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : , pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:57: lines 57-75), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: [<...>,<...>,<...>]}), meta: [], name_pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:57: characters 18-21)},{name: cancel, doc:
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : Marks the event as canceled, and stops the current event dispatch
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : , pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:80: lines 80-83), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: []}), meta: [], name_pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:80: characters 18-24)},{name: has, doc:
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : Checks whether a callback is a listener
to this event
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : @param listener A callback that
matches the signature of the event
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : @return Whether the callback is a listener
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : , pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:126: lines 126-136), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: [<...>]}), meta: [], name_pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:126: characters 18-21)},{name: remove, doc:
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : Removes an event listener
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : @param listener A callback that
matches the signature of the event
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : , pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:142: lines 142-157), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: [<...>]}), meta: [], name_pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:142: characters 18-24)},{name: removeAll, doc:
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : Removes all event listeners
C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47 : , pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/app/Event.hx:162: lines 162-171), access: [APublic], kind: FFun({ret: TPath(<...>), params: [], expr: {pos: <...>, expr: <...>}, args: [rc/lime/media/AudioSource.hx:14: characters 30-47)},{name: :no,0/src/lime/app/Event.hx:162: characters 18-27)},{name: __listeners, pos: #pos(C:/Completion, pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/l14: characters 30-47), access: [APublic], kind: FVar(TPath({name: <...>, params: <ime/media/AudioSource.hx:14: characters 30-47)},{name: :fileXmoolkit/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47), acl, params: [{pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/pr: {pos: <...>, expr: <...>}, args: []})}], pack: [lime,app], kind: TDClass(null,lime/_internal/macros/EventMacro.hx:153: characters 48-69), exC:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/_internal/macros/EventMacro.hx:148: chpr: EConst(<...>)}], pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,it/haxe/lib/lime/7,9,0/src/lime/media/AudioSource.hx:14: characters 30-47)},{name:9,0/src/lime/media/AudioSource.hx:14: characters 30-47)},{namerc/lime/media/AudioSource.hx:14: characters 30-47)},{name: :fileXml, params: [{pos: :noDebug, pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lacros/EventMacro.hx:153: characters 48-69), expr: EConst(<...>)}], pos: #pos(C:/Haime/media/AudioSource.hx:14: characters 30-47)}]} (see dump/de: characters 30-47)},{name: :noDebug, pos: #pos(C:/HaxeToolkit/haxe/lib/lime/7,9,0coding_error.txt for details)

I really don´t know what this is

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i changed one "is" to "!=" because it says is a error.

**Comment by Keoiki** [comment]
Most likely you have to update your Haxe to 4.2.4
