### ISSUE TITLE
Henchman Kill event has a noticeable delay (0.5)

### ISSUE THREAD

**Issue by KindOfASpork** [ShadowMario/FNF-PsychEngine#2151]
### Describe your bug here.

The Henchman Kill event (including the sound) is noticeably delayed, causing them to go slightly off-beat in Week 4's tracks.

0.4.2 - https://streamable.com/cj2prm

0.5 - https://streamable.com/tl39gc

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

While I did have mods installed in the recording for 0.5, I did test it without mods and got the same effect.

**Comment by ShadowMario** [comment]
Might have broken when i rewrote the events system
