### ISSUE TITLE
Forced upscroll

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#2152]
### Describe your problem here.

does someone have code for this

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

scam scam!

**Comment by PDL2CGamejolt** [comment]
[[[](url)](url)](url)

**Comment by tposejank** [comment]
setPropertyFromClass('ClientPrefs', 'downScroll', false)

**Comment by ShadowMario** [comment]
This is not the place for *asking* for people to code for you.

**Comment by PDL2CGamejolt** [comment]
i know,

**Comment by CrusherMods** [comment]
Ask for code in discussions after, people help them all the time

**Comment by PDL2CGamejolt** [comment]
ok
