### ISSUE TITLE
events.json

### ISSUE THREAD

**Issue by card100rac4** [ShadowMario/FNF-PsychEngine#2154]
### What is your question?

I just wanna know if events.json is meant to load with the source code, since I moved a bunch of stuff from the mods folder to the source code preloads. Everything works except for the events not loading.

**Comment by ShadowMario** [comment]
Yeah it also loads in source code, so its kinda weird that it isn't working for you...

**Comment by card100rac4** [comment]
i tried redoing the events and it still didn't work so im kinda confused
there isn't anything showing up in command prompt either

**Comment by card100rac4** [comment]
Nevermind it suddenly works again??
