### ISSUE TITLE
Stage Question

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#2161]
### What is your question?

Is it possible to change the stage mid-song (with lua)? If so/yes, then how?

**Comment by tposejank** [comment]
this might be similar to those others asking for a stage change event, *"ShadowMario has ALREADY stated he wont do it**, but you can use setProperty("spr.visible", true)

**Comment by ShadowMario** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/1753
