### ISSUE TITLE
Problem.

### ISSUE THREAD

**Issue by CBa08** [ShadowMario/FNF-PsychEngine#2167]
### Describe your bug here.

So, I was trying to compile the game. I fixed almost everything wrong.
But now I keep getting this specific error, says there is a missing ';' somewhere.

### Command Prompt/Terminal logs (if existing)

```bash
source/Achievements.hx:155: characters 12-13 : Missing ;
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited MainMenuState.hx, Achievements.hx, PlayState.hx, CharacterEditorState.hx and DialogueCharacterEditorState.hx and fixed the FlxCamera.defaultCameras

**Comment by denumu07** [comment]
I have an Idea. Maybe Update your Haxe. (When i did that it worked)

**Comment by ShadowMario** [comment]
Show me line 155 and what's around it in Achievements.hx

**Comment by CrusherMods** [comment]
> I have an Idea. Maybe Update your Haxe. (When i did that it worked)

Thats not it this time

**Comment by CrusherMods** [comment]
> ### Describe your bug here.
> So, I was trying to compile the game. I fixed almost everything wrong. But now I keep getting this specific error, says there is a missing ';' somewhere.
> 
> ### Command Prompt/Terminal logs (if existing)
> ```shell
> source/Achievements.hx:155: characters 12-13 : Missing ;
> ```
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> Yes, I edited MainMenuState.hx, Achievements.hx, PlayState.hx, CharacterEditorState.hx and DialogueCharacterEditorState.hx and fixed the FlxCamera.defaultCameras

Check for a line usually at the end of a line you need a ";" somewhere

**Comment by CBa08** [comment]
var Array<flixel.FlxCamera> = FlxG.cameras.setDefaultDrawTarget;
		if(camera != null) {
			cam = [camera];
		}
		alpha = 0;
		achievementBG.cameras = cam;
		achievementName.cameras = cam;
		achievementText.cameras = cam;
		achievementIcon.cameras = cam;
		alphaTween = FlxTween.tween(this, {alpha: 1}, 0.5, {onComplete: function (twn:FlxTween) {
			alphaTween = FlxTween.tween(this, {alpha: 0}, 0.5, {
				startDelay: 2.5,
				onComplete: function(twn:FlxTween) {
					alphaTween = null;
					remove(this);
					if(onFinish != null) onFinish();
				}
			});
		}});
	}

	override function destroy() {
		if(alphaTween != null) {
			alphaTween.cancel();
		}
		super.destroy();
	}
}
Here's the code around 155
