### ISSUE TITLE
0.5 Compiling Error

### ISSUE THREAD

**Issue by denumu07** [ShadowMario/FNF-PsychEngine#2169]
### Describe your bug here.

When i write " Lime Test Windows " to Compile The Engine This Message Appears: " source/StoryMenuState.hx:323: characters 13-15 : Expected ) ".

Can someone Help Me?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I tried to move The Line (323) In StoryMenuState.

**Comment by DaBanana64** [comment]
UPDATE. YOUR. [HAXE!](url)

**Comment by denumu07** [comment]
THANK. YOU.
