### ISSUE TITLE
Suggestion: Stage Creator

### ISSUE THREAD

**Issue by Charion75X** [ShadowMario/FNF-PsychEngine#217]
I'm not sure how it'll work but I personally think that if there was a stage creator like a character creator that's already in Psych Engine, that would be really beneficial.

An example would be like if, we see Boyfriend, Girlfriend, and Daddy Dearest (or any other chosen character) appear on a blank background or an existing one where you can add an image as a background, stage prop, or so like how it worked on Fighter Factory with M.U.G.E.N/Ikemen creations and adjust the offsets of the characters. If there were animated stuff, it would help out too to drag around the parts and characters in places on where the modders want it to be.

I'm not entirely sure if this is possible, but if it can then that could be sweet for mod makers.

**Comment by ShadowMario** [comment]
Are you aware of how difficult and time consuming it is to create a stage editor? It was in my plans but it's just too time consuming for me to do it at the moment.

**Comment by Charion75X** [comment]
I'm aware that it can be such thing, it was just a suggestion. Sorry about that.
