### ISSUE TITLE
More Dialouge Lua stuff.

### ISSUE THREAD

**Issue by WaluigiBestGirl** [ShadowMario/FNF-PsychEngine#2170]
### What feature do you want to get added on the base engine?

Just more dialogue lua stuff in general, mainly stuff like checking which part of the dialogue is in, how long the player has been in a dialogue. Ability to see when a dialogue ends. That kinda stuff.

**Comment by ShadowMario** [comment]
Everything you just said is already possible.
Please check the engine on its fullest before making an issue.
