### ISSUE TITLE
Character makes my Engine crash and/or black screen and still run the game

### ISSUE THREAD

**Issue by Supersteven72** [ShadowMario/FNF-PsychEngine#2171]
### Describe your bug here.

I have a problem where a character that I made I put into Psych Engine normally using bbpanzu's tutorial and hearing him eat a croissant and i did it just like he did and it did well. But when i place the character in like the dad battle or any week 1-2 songs, It just goes black for like a minute or two, sometimes the game just crashes other times the song plays, but its black screen. Im able to leave the song by pausing and trying to remember how to exit and when i do it still blackscreen and the engine still runs its just black screen. And i made a different sprite and did the same thing but it works completely fine so idk whats the issue if its my sprite or the engine or my computer. Plz someone explain how im able to fix this and plz explain in detail so that its not like, "Oh you just gotta fix the thing" like WHAT THING?? Sorry im just sooooo close to finish the sprite it just does this.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

only placing my character just like bbpanzu did in his Psych Engine tutorial video

**Comment by ShadowMario** [comment]
Where you saved all of your character's files?

**Comment by Supersteven72** [comment]
> Where you saved all of your character's files?

I put my character in the mods/images/characters folder

**Comment by Supersteven72** [comment]
If you want, ill send you the file itself where you can test it if you can and see if it works for you or not you can test if my character (SuperSteven72) still work normally when playing it on like dadbattle or something, and see for the main issue of the other character of my friend (MasterLeah) crashes your engine or turns the screen black and no visuals only audio of the game. are you fine with that??

**Comment by Supersteven72** [comment]
actually i fixed it i just redid the Spritesheet on the character to MaxRects and also resized the image dimensions and now it works. thank you ShadowMario anyways for at least responding
