### ISSUE TITLE
How to use Lua example [Play with your Mouse instead of Arrow Keys]

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#2172]
### What is your question?

There is a Lua example named [Play with your Mouse instead of Arrow Keys](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API) , I download it and then I put it in `assets\data\song-name`, then I run the game, and move mouse over the fixed arrows  at the top of the window, but it does not work.
What should I do?

**Comment by ShadowMario** [comment]
The script probably broke over time due to me changing stuff

**Comment by bbpanzu** [comment]
the script works fine for me. you sure you have the most recent build

**Comment by BombasticTom** [comment]
i just replaced onUpdatePost() to onUpdate()

**Comment by Noel3454565FNF** [comment]
can i have the script please?
