### ISSUE TITLE
Hex color codes

### ISSUE THREAD

**Issue by Activon777** [ShadowMario/FNF-PsychEngine#2173]
### Describe your problem here.

Yeah so uhm, i was putting the credits in the game and when i put the hex color codes it just doesn't work like i wanted to, here's an example of what happens, the color was meant to be a white thing but it's gray for some reason.
![image](https://user-images.githubusercontent.com/76783222/146195616-5a66ccce-9ad0-4e22-8d39-6302a1e2c25c.png)
![image](https://user-images.githubusercontent.com/76783222/146195731-433cdd0c-7eb5-4dfe-bfef-bebe62e87c06.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i edited CreditState.hx just to add the credits

**Comment by ShadowMario** [comment]
Hex codes must have 8 digits after `0x`, yours only have 7 digits

**Comment by Activon777** [comment]
> Hex codes must have 8 digits after `0x`, yours only have 7 digits

Yeah i'm stupid i forgot to put another F lol
