### ISSUE TITLE
Pin an issue that are like guidelines or something (Isn't base engine request) (also leave in the fact that you need to update haxe)

### ISSUE THREAD

**Issue by CrusherMods** [ShadowMario/FNF-PsychEngine#2176]
### What feature do you want to get added on the base engine?

In the Kade Github In Issues he had pinned his own issue but it was guidelines and crap, I think that would be excellent for this or pin one about PEOPLE HAVING TO UPDATE THEIR HAXE LIKE THERE ARE MORE DUPLICITES ABOUT THAT THEN MY SUS METER

anyways I think this would be great
(I suck at typing sometimes tell me if this makes sense)

**Comment by CrusherMods** [comment]
like in the title this isn't a base engine request, I dunno how to add a label without a template im dumb

**Comment by KutikiPlayz** [comment]
Definitely would be nice

**Comment by tposejank** [comment]
sus meter.

**Comment by ShadowMario** [comment]
People wouldn't read anyway.
