### ISSUE TITLE
How to move mouse via Lua script?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#2179]
### What is your question?

I want to move mouse via Lua script?   
How to do it?

**Comment by DEV-idiotXD** [comment]
U cant lmao

**Comment by bbpanzu** [comment]
u cant lmao.

lua only goes as far as the game lets it. we won't let you move mouses anytime soon.

**Comment by PoleyMagik** [comment]
People have already said it how it is, but if you are absolutely deadset, create a fake mouse, and make it follow the actual mouse, then when you need it, you can hijack that fake mouse.

**Comment by zwl1619** [comment]
@PoleyMagik How to create a fake mouse?
