### ISSUE TITLE
curBeat is always 0 (v0.5)

### ISSUE THREAD

**Issue by Grape-Boy** [ShadowMario/FNF-PsychEngine#2180]
### Describe your bug here.

When I use debugPrint(curBeat), it always prints "0".

Here's the code :
```lua
function onBeatHit()
    debugPrint(curBeat)
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only added a script.lua that prints curBeat since I've had this problem in another script.

**Comment by Itz-Miles** [comment]
I dunno. I'd assume it should update every BeatHit, but It might be grabbing the Curbeat from when it was first loaded.
You could try to use onUpdate(elapsed) though.





function onUpdate(elapsed)
	-- your code here or smth
end

**Comment by bbpanzu** [comment]
repull from the source. that issue's been fixed
