### ISSUE TITLE
HTML5 Compile issue [Current Version]

### ISSUE THREAD

**Issue by ninjaninja140** [ShadowMario/FNF-PsychEngine#2182]
### Describe your bug here.

Basically the source version cant compile to HTML5 due to a weekdata error at like 188?
Im unsure of what the problem is but can someone help me fix it?

### Command Prompt/Terminal logs (if existing)

```bash
source/WeekData.hx:188: characters 50-54 : Class<Paths> has no field mods
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing has been edited.

**Comment by CrusherMods** [comment]
Haxe version Just in-case

**Comment by ninjaninja140** [comment]
> Haxe version Just in-case

4.2.4 - Newest version

**Comment by CrusherMods** [comment]
> > Haxe version Just in-case
> 
> 4.2.4 - Newest version

oh then idk sorry

**Comment by bbpanzu** [comment]
on line 188 in the WeekData.hx
put #MODS_ALLOWED tag around it. like so
```

					#MODS_ALLOWED
					weekFile.folder = directory.substring(Paths.mods().length, directory.length-1);
					#end

```
