### ISSUE TITLE
Test windows error

### ISSUE THREAD

**Issue by Godofbacon1** [ShadowMario/FNF-PsychEngine#2187]
### Describe your bug here.

I downloaded the new psych engine update 0.5 but when i do lime test windows -debug to the command promot to open friday night funkin on the new update it shows me this

### Command Prompt/Terminal logs (if existing)

```bash
source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by CrusherMods** [comment]
Haxe Version??

**Comment by KutikiPlayz** [comment]
update haxe

**Comment by Godofbacon1** [comment]
Working thx!
