### ISSUE TITLE
Error MSVC, HXCPP_VARS

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#2190]
### Describe your problem here.

Warning: Could not find Visual Studio 2017 VsDavCmd
Missing: HXCPP_VARS
Error Could not automatically setup MSVC
What does this mean? Did I do something wrong? its been like that for about an hour. should leave the command to run or do something

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by CrusherMods** [comment]
Something is missing from Visual Studio or the main Haxe Itself

**Comment by SonicXFire1987** [comment]
What exactly would it be?

**Comment by ShadowMario** [comment]
Not a psych engine specific issue

**Comment by VRfunkin** [comment]
same

**Comment by VRfunkin** [comment]
wtf i did the same too
