### ISSUE TITLE
Error in source 'Song.hx' from unedited fresh download (0.5)

### ISSUE THREAD

**Issue by GDThetax** [ShadowMario/FNF-PsychEngine#2210]
### Describe your bug here.

I got a fresh version of the source code and when I went to compile it gave me an error on source code section ; 
**var sec:SwagSection = songJson.notes[secNum];**
The error makes no sense to me and exists in the Song.hx file in the source code. It tells me when I hover over the error that; 
**Array access is not allowed on {+ length : Int }diagnostics(2)**
And I don't know how to fix this or if this is a general bug in the current version.

### Command Prompt/Terminal logs (if existing)

```bash
source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, it's a fresh download with zero edits.

**Comment by iptory** [comment]
update haxe

**Comment by GDThetax** [comment]
Thanks, I worked with Kade engine in the past so I have an older version installed. 

> update haxe

**Comment by iptory** [comment]
no problem!
