### ISSUE TITLE
mod folder credits

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#2211]
### Describe your bug here.

so when i put the credits txt in the mod folder (NOT INDIVISUAL MOD FOLDER, just the mod folder itself), it doesnt load the credits. could this be fixed? thank youu

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by tposejank** [comment]
you need to make the current mod directory to the folder for it to appear i think (press 7 on main menu)

**Comment by bbpanzu** [comment]
fixed

**Comment by crispyboi24** [comment]
> fixed

thank you!
