### ISSUE TITLE
Fort LUA

### ISSUE THREAD

**Issue by endergames231** [ShadowMario/FNF-PsychEngine#2220]
### Describe your problem here.

need lua fort

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by bbpanzu** [comment]
a what?

**Comment by PoleyMagik** [comment]
bro u mean font?

If so here's the code
setTextFont("LUATEXTNAME", "FONTNAME.ttf");

**Comment by skid15** [comment]
> bro u mean font?
> 
> If so here's the code setTextFont("LUATEXTNAME", "FONTNAME.ttf");

what does the " luaTextName" mean?
