### ISSUE TITLE
curBeat doesn't seem to work anymore. (0.5)

### ISSUE THREAD

**Issue by NateTD0M** [ShadowMario/FNF-PsychEngine#2221]
### Describe your bug here.

I moved a mod I am working on into a newer version of psych and i was trying to use curBeat to track events, but it wasn't working. I went the check another song I had previously made on an older build of psych where several events were scheduled using curBeat and they also don't work anymore. 

I put a debugPrint that would tell me the beat on beat hit and it says 0 on each one
![image](https://user-images.githubusercontent.com/88478421/146363519-cff379a7-f1eb-4700-b08f-f495e80579ab.png)

Uhh yeah idk what's up here. Thanks

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by crispyboi24** [comment]
This is fixed. Go to actions and download the newest windows build.

**Comment by bbpanzu** [comment]
*source. get the newest source
