### ISSUE TITLE
help

### ISSUE THREAD

**Issue by sototso** [ShadowMario/FNF-PsychEngine#223]
I want to play with FNFBOT manually?  I know there is BOTPLAY option in Psych Engine

**Comment by aflacc** [comment]
ok but why

**Comment by sototso** [comment]
are you a coder? can I edit the source code but idk which file

**Comment by ShadowMario** [comment]
If you know there is a botplay option then why even playing with fnfbot???

**Comment by sototso** [comment]
some engines works with fnfbot

**Comment by Idkidkjwo** [comment]
"> If you know there is a botplay option then why even playing with fnfbot???"

FNFBOT is working on PE just redact json file on **_Like Prizmatex_**
