### ISSUE TITLE
add lua script for characters

### ISSUE THREAD

**Issue by BombasticTom** [ShadowMario/FNF-PsychEngine#2231]
### What feature do you want to get added on the base engine?

I know it might sound like a silly idea that is useless, but it kinda is useful. I can't replicate Shaggy's movement in God Eater without 2 separate sprites (body and legs) since in the new Shaggy version the legs move with the body, they're not static. Or I can't replicate Sonic's running animation from FNF' HD mod.

I know I can just use luascript in charts, but this is also useful, since you don't need to copypaste the code into 500 different charts. I did notice that there is a new lua command addLuaScript, but it's also unnecessary to make 500 copies of a same script having a line to load another lua script.

**Comment by bbpanzu** [comment]
you already can

**Comment by BombasticTom** [comment]
?

**Comment by crispyboi24** [comment]
> ?

Just make a lua script in mods/images/characters and have it titled the same name as a character json.

**Comment by ShadowMario** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/44785097/146705453-3ff09703-49be-4cbd-a40b-9c369cf2cca6.png)
