### ISSUE TITLE
Disabling Anti-aliasing To Make A Pixel Stage?

### ISSUE THREAD

**Issue by goofeeSquared** [ShadowMario/FNF-PsychEngine#2236]
### Describe your problem here.

Is there a way for me to force stages to be pixelated to help me create a pixel stage, if there is I would enjoy your help greatly.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by goofeeSquared** [comment]
figured it out!

**Comment by TechnikTil** [comment]
how?
