### ISSUE TITLE
How to make Character Lua?

### ISSUE THREAD

**Issue by afeefflox** [ShadowMario/FNF-PsychEngine#2239]
### Describe your problem here.

idk its Character Lua Same As Stage Lua?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Gato-chistoso** [comment]
u cant do a character in lua bro, you have to make it in the game (pressing 7 in start menu)

**Comment by Templarfreak** [comment]
character lua files are only available in 0.5 right now. when you add a character, it has a *name*.json file, and it should go in the characters folder (either in mods, in your specific mod, or in assets). to add Lua scripting to a character, add a *name*.lua file in the same directory as the json file and script it like you would a stage lua script, everything should work normally like a stage lua file from there

**Comment by ShadowMario** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/44785097/146705490-399676cd-5b4f-4bd6-8248-0b96fea2c700.png)
It works the same as any other lua script in Psych Engine.
There are variables you can use for checking which character is the current one, `gfName`, `boyfriendName`, `dadName`, then you can use this for example:

`if dadName == 'violastro' then`
