### ISSUE TITLE
The engine won't compile 

### ISSUE THREAD

**Issue by Lucifer-TM** [ShadowMario/FNF-PsychEngine#2241]
### Describe your bug here.

I downloaded the latest update of Psych engine moments ago and tried to compile it, but it gives me this error: 
![Capture](https://user-images.githubusercontent.com/51889426/146472709-9f855536-b78a-4f1b-8a24-58fe0405b5fd.PNG)

### Command Prompt/Terminal logs (if existing)

```bash
D:\Users\****** ****** ****\Desktop\FNF-PsychEngine-main>lime test windows
source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't edit anything.

**Comment by SrtHero278** [comment]
Update haxe. You might be using 4.1.5 instead of the latest.

**Comment by Lucifer-TM** [comment]
> Update haxe. You might be using 4.1.5 instead of the latest.

Which version do you reccomend?

**Comment by KutikiPlayz** [comment]
> Which version do you reccomend?
Use the latest

**Comment by Lucifer-TM** [comment]
> > Which version do you reccomend?
> 
> Use the latest

It works, thanks.

**Comment by Tigedraglon10** [comment]
> > Which version do you reccomend?
> 
> Use the latest

Didnt it say only 4.1.5?

**Comment by SrtHero278** [comment]
> > > Which version do you reccomend?
> > 
> > 
> > Use the latest
> 
> Didnt it say only 4.1.5?

For other engines, yes. Not here though.
![image](https://user-images.githubusercontent.com/93018286/146492705-30f52076-7f8b-4d5e-9333-72b1093a5a78.png)

**Comment by PersonNanoexe** [comment]
i love it when people cant read the wiki

**Comment by SrtHero278** [comment]
> i love it when people cant read the wiki

me too.

**Comment by KutikiPlayz** [comment]
> Didnt it say only 4.1.5?

Kade engine says that, not psych
