### ISSUE TITLE
function onUpdate() no longer works in 0.5!!

### ISSUE THREAD

**Issue by ZartaxDerg** [ShadowMario/FNF-PsychEngine#2245]
### Describe your bug here.

if you have a "function onUpdate" active in game, when you reset or die, the game CRASH, but it dosent happen in the version 0.4.2, just 0.5

Example: if you have a script.lua in your song, inside the data folder, and have this:

```
local spin = true;
local arrowMoveX = 20;
local arrowMoveY = 20;
local defaultNotePos = {};

function onSongStart()

    for i = 0,7 do 

        x = getPropertyFromGroup('strumLineNotes', i, 'x')

        y = getPropertyFromGroup('strumLineNotes', i, 'y')

        table.insert(defaultNotePos, {x,y})

    end

end


function onUpdate()

    songPos = getPropertyFromClass('Conductor', 'songPosition');

    currentBeat = (songPos / 1000) * (bpm / 60)

    if spin == true then 

        for i = 0,7 do 

            setPropertyFromGroup('strumLineNotes', i, 'x', defaultNotePos[i + 1][1] + arrowMoveX * math.sin((currentBeat + i*0.25) * math.pi))

            setPropertyFromGroup('strumLineNotes', i, 'y', defaultNotePos[i + 1][2] + arrowMoveY * math.cos((currentBeat + i*0.25) * math.pi))

       end

    end
end
```

The function works but if you die or reset the song, the game CRASH just in the version 0.5!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just added a script.lua in a song.

**Comment by bbpanzu** [comment]
have you tried removing everything from your trace, adding each one by one and seeing maybe if one of your lines might've crashed it. cuz lua doesn't crash.

**Comment by ZartaxDerg** [comment]
yes, and this happened
[https://youtu.be/Eg0wO7Ja_9U](url)

**Comment by bbpanzu** [comment]
try running it with an empty update function and see if that crashes anything?

**Comment by ZartaxDerg** [comment]
with an empty update dont crash, only if the update have a active code

**Comment by bbpanzu** [comment]
then your code might be the problem

**Comment by ZartaxDerg** [comment]
But this doesnt happen in the psych engine 0.4.2
