### ISSUE TITLE
how to make difficulties

### ISSUE THREAD

**Issue by duckyduck1q** [ShadowMario/FNF-PsychEngine#2246]
### Describe your problem here.

I don't know how to put the images of the difficulty

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by SrtHero278** [comment]
images/menudifficulties
You have to make the folder yourself.

**Comment by DEV-idiotXD** [comment]
U can add difficultys from lua now?

**Comment by bbpanzu** [comment]
yea

**Comment by duckyduck1q** [comment]
ok

**Comment by DEV-idiotXD** [comment]
> yea

How??!!!

**Comment by SrtHero278** [comment]
> > yea
> 
> How??!!!
make a difficulty png in `images/menudifficulties`, (Make the folder yourself) then in the week editor, go to the "Other" tab and type in your difficulties like how you would type in your songs.

**Comment by DEV-idiotXD** [comment]
> > > yea
> > 
> > 
> > How??!!!
> 
> make a difficulty png in `images/menudifficulties`, (Make the folder yourself) then in the week editor, go to the "Other" tab and type in your difficulties like how you would type in your songs.

Ah looks like source is useless now jk

**Comment by ShadowMario** [comment]
You can add difficulties on Week Editor's "Other" tab

You can add the difficulty image in mods/images/menudifficulties/
