### ISSUE TITLE
skip cutcenes

### ISSUE THREAD

**Issue by loogchin** [ShadowMario/FNF-PsychEngine#2247]
### What feature do you want to get added on the base engine?

Can you add skip video cutscenes?

**Comment by DEV-idiotXD** [comment]
No.

**Comment by bbpanzu** [comment]
ok

**Comment by HiroMizuki** [comment]
it would be good for some people (like me lmao)

**Comment by MasterDirector99** [comment]
Yeah, just like you can skip WEBM cutscenes in Kade Engine!

**Comment by IAmDazen** [comment]
or just add it in load cutscene? im pretty sure you can use lua so if enter is pressed it intervenes with a cutscene
