### ISSUE TITLE
Uhh What...

### ISSUE THREAD

**Issue by Tigedraglon10** [ShadowMario/FNF-PsychEngine#2252]
### Describe your problem here.

I typed in lime test macos and it said `source/StoryMenuState.hx:323: characters 12-14 : Expected )
` What do i do?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by bbpanzu** [comment]
update haxe

**Comment by SrtHero278** [comment]
> update haxe

yes.

**Comment by Reycko** [comment]
update haxe

**Comment by denumu07** [comment]
You have to Update your Haxe: https://haxe.org/

**Comment by juanroman74454811** [comment]
bbpanzu update haxe
