### ISSUE TITLE
Gameover black BG removal using lua

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#2255]
### What feature do you want to get added on the base engine?

Maybe there can be a feature where you can remove the black BG in gameover, using lua. Where you can turn it on and off with true and false stuff. Not sure if this is complicated to make, but if you can make it, that would be really cool.

**Comment by Templarfreak** [comment]
im not 100% sure, but if you create a sprite using `makeLuaSprite` and then `makeGraphic` you can change that to whatever color you want and use that as the background instead, but from there i dont know when you should create this sprite, like during `onGameOver` at some point? there does appear to be some special case handling for creating sprites during the game over state built-in to the Lua functions, but im not completely sure how it works

**Comment by ShadowMario** [comment]
There is no "Black BG", it literally just stops rendering the objects from PlayState when Game Over is active

**Comment by WoodsSilent05** [comment]
that does not work lol
