### ISSUE TITLE
Add dealy when press resume and more

### ISSUE THREAD

**Issue by Sanscode1937** [ShadowMario/FNF-PsychEngine#2258]
### What feature do you want to get added on the base engine?

This thing i want it to be in base engine

1.Add delays when press resume on the just like osu.

2.Add split character animation editor like tricky phase 3(can make it small and resize it on game but it's must low quality so i want split character animation editor.)

**Comment by Doritojoey** [comment]
Custom character framerate has existed since the character creator has

**Comment by ShadowMario** [comment]
1. ew osu
2. No
