### ISSUE TITLE
Problem while compiling

### ISSUE THREAD

**Issue by FuroYT** [ShadowMario/FNF-PsychEngine#2261]
### Describe your problem here.

``source/OptionsState.hx:157: characters 44-50 : Class<Note> has no field frameN``
and
``source/editors/ChartingState.hx:219: lines 219-232 : Object requires field mania
source/editors/ChartingState.hx:219: lines 219-232 : { validScore : Bool, stage : String, splashSkin : String, speed : Float, song : String, player3 : String, player2 : String, player1 : String, notes : Array<SwagSection>, needsVoices : Bool, bpm : Float, arrowSkin : String } should be SwagSong
source/editors/ChartingState.hx:219: lines 219-232 : ... { validScore : Bool, stage : String, splashSkin : String, speed : Float, song : String, player3 : String, player2 : String, player1 : String, notes... has no field mania
source/editors/ChartingState.hx:2113: lines 2113-2127 : Object requires field mania
source/editors/ChartingState.hx:2113: lines 2113-2127 : { validScore : Bool, stage : String, splashSkin : String, speed : Float, song : String, player3 : String, player2 : String, player1 : String, notes : Array<SwagSection>, needsVoices : Bool, bpm : Float, arrowSkin : String } should be SwagSong
source/editors/ChartingState.hx:2113: lines 2113-2127 : ... { validScore : Bool, stage : String, splashSkin : String, speed : Float, song : String, player3 : String, player2 : String, player1 : String, notes... has no field mania``
apear while i compile Psych 0.4.2

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't modify ChartingSate.hx and OptionState.hx

**Comment by tposejank** [comment]
bruh what did you download

**Comment by tposejank** [comment]
@ShadowMario hes trying to compile some extra key thing, so this is invalid

**Comment by Reycko** [comment]
1. Install latest haxe version
2. This is extra key mod so this is invalid like @tposejank said
