### ISSUE TITLE
Psych Engine 0.5 refuses to launch on MacOS

### ISSUE THREAD

**Issue by ItzGreenForever** [ShadowMario/FNF-PsychEngine#2264]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/85078030/146579036-9831a7be-4f3b-450e-829d-c9173f164a26.png)
When I try compiling Psych Engine, I get this error, "clang: error: linker command failed with exit code 1 (use -v to see invocation" and when I try running the compiled app, it gives me an error saying the game may be damaged or incomplete. 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not make any modifications.

**Comment by Jonnycatmeow** [comment]
here use my [linc_luajit](https://github.com/Jonnycatmeow/linc_luajit) 
commands: 
haxelib remove linc_luajit 
haxelib git linc_luajit https://github.com/Jonnycatmeow/linc_luajit  
if it gives you warnings don't worry about that it will still build it all the way through

**Comment by Jonnycatmeow** [comment]
im not trying to self promo or anything just trying to help

**Comment by Reycko** [comment]
Update haxe if it's in 4.1.5

**Comment by ItzGreenForever** [comment]
> here use my [linc_luajit](https://github.com/Jonnycatmeow/linc_luajit) commands: haxelib remove linc_luajit haxelib git linc_luajit https://github.com/Jonnycatmeow/linc_luajit if it gives you warnings don't worry about that it will still build it all the way through

Thank you! Doing this worked.
