### ISSUE TITLE
Seperate mod folders

### ISSUE THREAD

**Issue by bbpanzu** [ShadowMario/FNF-PsychEngine#227]
instead of having mods/ be a alternate assets folder,
ex:
mods/
----∟images/
----∟characters/
----∟data/

you should have mods be whole folders for easy distribution
ex:
mods/
----∟example_mod/
--------∟images/
--------∟characters/
--------∟data/
----∟funnymod/
-------- ∟images
--------∟characters
--------∟data

**Comment by ShadowMario** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/44785097/135955162-2afa812c-835e-4673-8af2-83ae30cf6b72.png)
![Screenshot_2](https://user-images.githubusercontent.com/44785097/135955164-b3fe2cb5-d423-47fb-a449-07bd4c9bad4f.png)
I mean, there's this, which is pretty much the same thing as what you've mentioned

**Comment by ShadowMario** [comment]
Nvm i had read it wrong, so yeah, basically it works the exact same way as what you've mentioned, my bad.
This was added on 0.4.1
