### ISSUE TITLE
How do I add an animated BG in LUA code if possible?

### ISSUE THREAD

**Issue by BreadMuncher** [ShadowMario/FNF-PsychEngine#2275]
### Describe your problem here.

Need help adding an animated BG with LUA code if its even possible, I also need help changing backgrounds mid-song with LUA (if possible).

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by crispyboi24** [comment]
the wiki has the animated shit lol. dunno abt the changing backgrounds tho

**Comment by KutikiPlayz** [comment]
just put everything into one stage, and when you wanna switch just hide the other shit so that the other stage items appear

**Comment by SrtHero278** [comment]
`makeAnimatedLuaSprite` for the animation part.
