### ISSUE TITLE
source/Song.hx:65: characters 27-41 : Array access is not allowed on (+ length : Int )

### ISSUE THREAD

**Issue by Kurtis-Combine** [ShadowMario/FNF-PsychEngine#2277]
It shows up on CMD when I try to "lime test windows". Idk how to fix it, **please help.**

Source

Windows

I didn't edit anything

**Comment by CrusherMods** [comment]
DOES NO ONE READ THE README.md AT ALL UPDATE YOUR HAXE

**Comment by Reycko** [comment]
UPDATE. HAXE.
I SWEAR THEY SHOULD BAN PEOPLE WHO SENDS THIS TYPE OF DUMB SHIT

**Comment by ShadowMario** [comment]
Duplicate of literally over 10 threads.
