### ISSUE TITLE
Cannot build game

### ISSUE THREAD

**Issue by snazzyostrich** [ShadowMario/FNF-PsychEngine#2280]
### Describe your bug here.

If I try to build psych 1.5, it will result in a message stating source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by CrusherMods** [comment]
im almost about to lose it, UPDATE YOUR HAXE AND STOP MAKING DUPLICATES

**Comment by snazzyostrich** [comment]
> 

wdym, im not resending anything
and do i just install haxe 4.2.4 and be done with it?

**Comment by CrusherMods** [comment]
> > 
> 
> wdym, im not resending anything and do i just install haxe 4.2.4 and be done with it?

By duplicates I mean people already made issues about this and have been answered
and yes install 4.2.4

**Comment by snazzyostrich** [comment]
> > > 
> > 
> > 
> > wdym, im not resending anything and do i just install haxe 4.2.4 and be done with it?
> 
> By duplicates I mean people already made issues about this and have been answered and yes install 4.2.4

now it's just telling me that lime test windows isn't a command

**Comment by CrusherMods** [comment]
> > > > 
> > > 
> > > 
> > > wdym, im not resending anything and do i just install haxe 4.2.4 and be done with it?
> > 
> > 
> > By duplicates I mean people already made issues about this and have been answered and yes install 4.2.4
> 
> now it's just telling me that lime test windows isn't a command

try reinstalling everything you need for fnf then

**Comment by snazzyostrich** [comment]
> > > > > 
> > > > 
> > > > 
> > > > wdym, im not resending anything and do i just install haxe 4.2.4 and be done with it?
> > > 
> > > 
> > > By duplicates I mean people already made issues about this and have been answered and yes install 4.2.4
> > 
> > 
> > now it's just telling me that lime test windows isn't a command
> 
> try reinstalling everything you need for fnf then

Error: Could not find haxelib "linc_luajit", does it need to be installed?

**Comment by tposejank** [comment]
do you know how to read the README.md

**Comment by snazzyostrich** [comment]
> do you know how to read the README.md

i have a 2 pixel wide brain lmao

**Comment by Reycko** [comment]
do the following commands on the cmd:

```
haxelib install flixel
haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons
haxelib install flixel-ui
haxelib install hscript
haxelib install newgrounds
haxelib install polymod
haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc

```
if it says haxelib is invalid, open cmd on the haxe directory

**Comment by Fablisothebottle** [comment]
none of this helped me it just says the same thing /:

**Comment by CrusherMods** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > wdym, im not resending anything and do i just install haxe 4.2.4 and be done with it?
> > > > 
> > > > 
> > > > By duplicates I mean people already made issues about this and have been answered and yes install 4.2.4
> > > 
> > > 
> > > now it's just telling me that lime test windows isn't a command
> > 
> > 
> > try reinstalling everything you need for fnf then
> 
> Error: Could not find haxelib "linc_luajit", does it need to be installed?

Use `haxelib install linc_luajit`
