### ISSUE TITLE
Character note animations do not play.

### ISSUE THREAD

**Issue by SarahDrewington** [ShadowMario/FNF-PsychEngine#2283]
### Describe your bug here.

The character note animations are not playing even though they ARE in the game AND in the .json file, it seems the game is having a hard time loading these for no reason, and causes the character to teleport to the spot, even though the idle animation works. 
![image](https://user-images.githubusercontent.com/84744056/146625166-d0abea7d-7de1-4dae-93e8-4fd65ab6c4bc.png)
and here is the JSON file. 
![image](https://user-images.githubusercontent.com/84744056/146625191-77645d94-06d0-4f92-af24-83e41af96595.png)

please help, on 0.4.2 it used to just crash but now its loading in, something with the code is preventing this from working.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by SrtHero278** [comment]
`singDIRECTION`. not `direction`.

**Comment by CrusherMods** [comment]
its singUP, singDOWN, singLEFT, singRIGHT
