### ISSUE TITLE
Custom UI Skins and Noteskins

### ISSUE THREAD

**Issue by Gui-iago** [ShadowMario/FNF-PsychEngine#2286]
### What feature do you want to get added on the base engine?

I was thinking about the engine having Noteskins and Custom UI Skin support

I made some in game concepts
![image](https://user-images.githubusercontent.com/45212377/146630021-4a747c2d-7113-412a-afd4-f8670b5992f4.png)
![image](https://user-images.githubusercontent.com/45212377/146630023-a4bda375-779f-4bcd-b827-aca334dfe291.png)

this is a very simple concept, but I was thinking of using the Note Colors menu for the noteskins at least

**Comment by afeefflox** [comment]
I have new idea for Note skin give  by opponent and boyfriend with different noteskin like amor is Keybind arrows

**Comment by Reycko** [comment]
> I have new idea for Note skin give by opponent and boyfriend with different noteskin like amor is Keybind arrows

For people who don't understand people with a stroke: I have a new idea for Note skins: Opponent only note skin e.g. amor has keybind arrows but boyfriend has normal

**Comment by DEV-idiotXD** [comment]
I can code customizable arrows just add a option then in note.hx at the part that sets the assetss name make it 'NOTE_assets' + VARIABLENAME and same for note splash.hx
