### ISSUE TITLE
freeplaysong list is empty

### ISSUE THREAD

**Issue by foxcool119** [ShadowMario/FNF-PsychEngine#229]

**Comment by foxcool119** [comment]
![image](https://user-images.githubusercontent.com/89747510/135968236-ed60fd07-ba74-4c3a-b86f-33c92f4bab82.png)

**Comment by lemz1** [comment]
The songs should still be in Freeplay if not maybe you need to beat them first.
But other than that it is normal that the freeplaysonglist file is empty

**Comment by PersonNanoexe** [comment]
you have to create a new week, name all the songs according to your freeplay songs, and then click this
![Uploading image.png…]()

**Comment by ShadowMario** [comment]
The songs are added in Weeks now, this still works but it's pretty much useless at the point i'm considering removing it.
