### ISSUE TITLE
How to add a new Strum

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#2299]
### What is your question?

Hi,
So as stated in the title I would like to know how to add a new Strum, so that in the end there are 3.
In version 0.5 and source code

**Comment by tposejank** [comment]
what?

**Comment by lemz1** [comment]
what do you mean with what?

**Comment by SrtHero278** [comment]
I think he's talking about a new set of arrows. Like this:
![image](https://user-images.githubusercontent.com/93018286/146645915-5cb7d552-c69b-4cdb-9d97-83145b94834d.png)

**Comment by lemz1** [comment]
> I think he's talking about a new set of arrows. Like this: ![image](https://user-images.githubusercontent.com/93018286/146645915-5cb7d552-c69b-4cdb-9d97-83145b94834d.png)

Yeah something like that

**Comment by mayo78** [comment]
[golden apple is open source](https://github.com/loolman101/VsEvilCorruptedDaveDay3Final)

**Comment by lemz1** [comment]
> [golden apple is open source](https://github.com/loolman101/VsEvilCorruptedDaveDay3Final)
It isn't made with Psych Engine so the code is completly different

**Comment by PoleyMagik** [comment]
> > [golden apple is open source](https://github.com/loolman101/VsEvilCorruptedDaveDay3Final)
> 
> it isn't made with Psych Engine so the code is completly different

It's the same language, figure it out.

**Comment by ShadowMario** [comment]
I won't help in mod ports.

**Comment by PDL2CGamejolt** [comment]
> I think he's talking about a new set of arrows. Like this: ![image](https://user-images.githubusercontent.com/93018286/146645915-5cb7d552-c69b-4cdb-9d97-83145b94834d.png)

i wanna do t in lua

**Comment by ByronisJoan** [comment]
> > [golden apple is open source](https://github.com/loolman101/VsEvilCorruptedDaveDay3Final)
> 
> it isn't made with Psych Engine so the code is completly different

BRUH JUST BECAUSE THERE THE TIME THINGY DOESENT MEAN ITS PSYCH ENIGINE, IT'S JUST ONE THE DEVS OF GOLDEN APPLE OR SOMETHING ADDING THE TIME THINGY
