### ISSUE TITLE
I attempted to make a new character, haxeflixel icon shows up.

### ISSUE THREAD

**Issue by jaekyle122** [ShadowMario/FNF-PsychEngine#23]
![Screenshot 2021-09-01 102952](https://user-images.githubusercontent.com/88638460/131716920-133f7556-9e9d-463c-a3ff-9fec4bccc88a.png)

**Comment by ShadowMario** [comment]
where did you put Tank_assets.png and Tank_assets.xml?

**Comment by jaekyle122** [comment]
images/characters
and shared/images/characters

**Comment by jaekyle122** [comment]
Wait are you supposed to compile?

**Comment by haya3218** [comment]
> Wait are you supposed to compile?

Yes

**Comment by ShadowMario** [comment]
If you're placing character images on assets/, then you should compile.
Otherwise, you can put them in mods/characters/

**Comment by ShadowMario** [comment]
No answers in 6 days, i will assume he got it right now.
