### ISSUE TITLE
Post Song Cutscene

### ISSUE THREAD

**Issue by BrightEyesFox** [ShadowMario/FNF-PsychEngine#230]
How would I make a video cutscene play after the end of a song? I know how to make a video cutscene play BEFORE the song, but I want to know how to make it play AFTER.

**Comment by ShadowMario** [comment]
Same way as the pre-song cutscene, but instead of onStartCountdown(), you use onEndSong()

**Comment by ToBAYT** [comment]
@BrightEyesFox Here is the code
`local allowCountdown = false
function onEndSong()
	if not allowCountdown and isStoryMode then --Block the first countdown
		startVideo('cokecutsceneend');
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end`
Hope this helps

**Comment by PDL2CGamejolt** [comment]
> @BrightEyesFox Here is the code Hope this helps
> 
> <img alt="I helped" width="960" src="https://user-images.githubusercontent.com/73630363/141373652-25e1e0ae-b493-4b05-aa92-09154ce27baa.png">

can you send me the code
