### ISSUE TITLE
Storymenustate is being more problematic

### ISSUE THREAD

**Issue by Fablisothebottle** [ShadowMario/FNF-PsychEngine#2307]
### Describe your bug here.

i just downloaded 0.5 it worked before but now it works ass and gives me this ugly ass error source/StoryMenuState.hx:144: characters 26-41 : Class<CoolUtil> has no field difficultyStuff (Suggestion: difficultyString)
source/StoryMenuState.hx:145: characters 134-149 : Class<CoolUtil> has no field difficultyStuff (Suggestion: difficultyString)
source/StoryMenuState.hx:312: characters 29-44 : Class<CoolUtil> has no field difficultyStuff (Suggestion: difficultyString)
source/StoryMenuState.hx:313: characters 33-48 : Class<CoolUtil> has no field difficultyStuff (Suggestion: difficultyString)
source/StoryMenuState.hx:288: characters 26-41 : Class<CoolUtil> has no field difficultyStuff (Suggestion: difficultyString)

### Command Prompt/Terminal logs (if existing)

```bash
source/StoryMenuState.hx:144: characters 26-41 : Class<CoolUtil> has no field difficultyStuff (Suggestion: difficultyString)
source/StoryMenuState.hx:145: characters 134-149 : Class<CoolUtil> has no field difficultyStuff (Suggestion: difficultyString)
source/StoryMenuState.hx:312: characters 29-44 : Class<CoolUtil> has no field difficultyStuff (Suggestion: difficultyString)
source/StoryMenuState.hx:313: characters 33-48 : Class<CoolUtil> has no field difficultyStuff (Suggestion: difficultyString)
source/StoryMenuState.hx:288: characters 26-41 : Class<CoolUtil> has no field difficultyStuff (Suggestion: difficultyString)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i cant even run it

**Comment by Fablisothebottle** [comment]
also i did what people said to fix but nope this still shows up

**Comment by Fablisothebottle** [comment]
EVEN MY HAXE IS AT THE CORRECT VERSION

**Comment by ShadowMario** [comment]
Update your github repository to the newest version of Psych.
