### ISSUE TITLE
custom difficulty using lua

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#2308]
### Describe your problem here.

how do i make a custom difficulty?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Fablisothebottle** [comment]
you need source i dont think theres a lua for custom difficulties. but adding it is ez on source

**Comment by crispyboi24** [comment]
> you need source i dont think theres a lua for custom difficulties. but adding it is ez on source

i saw on one issue that bb said you can do custom difficulties without source. but i dunno how to do it.

**Comment by crispyboi24** [comment]
nvm, found out how

**Comment by PDL2CGamejolt** [comment]
> nvm, found out how

I WANNA KNOW HOWWWWW

**Comment by crispyboi24** [comment]
> > nvm, found out how
> 
> I WANNA KNOW HOWWWWW

make a difficulty png in images/menudifficulties, (Make the folder yourself) then in the week editor, go to the "Other" tab and type in your difficulties like how you would type in your songs.

**Comment by PDL2CGamejolt** [comment]
uhm

**Comment by PDL2CGamejolt** [comment]
oh
