### ISSUE TITLE
remove(dad); doesn't work

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#231]
Hi,
So as stated in the title when I want to remove the dad character at the Step 16 it won't work
Everything else works. For example : add(dad); works

Here's the code:
```
		if (curSong == 'Milf')
		{
			switch (curStep)
			{
				case 16:
				remove(dad);
				dad = new Character(100, 100, 'dad');
				add(dad);
			}
		}
```

**Comment by bbpanzu** [comment]
define "doesn't work". what is it doing?

**Comment by lemz1** [comment]
I mean with doesn't work that instead of removing the dad character it just stays
It is supposed to remove the older dad character and create the new one but, it just stays and the new one is created which means that the older dad character is still in the background.

**Comment by ShadowMario** [comment]
`dadGroup.remove(dad);`, i had to put characters in a Sprite group for the "Change Character" event to be handled properly.
Speaking of, why don't you just use this event instead?
`triggerEventNote('Change Character', 'dad', 'dad');`
