### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by LucaGoku** [ShadowMario/FNF-PsychEngine#2313]
### Describe your problem here.

I'm compiling but this message comes up.
![help](https://user-images.githubusercontent.com/92657248/146655144-180d70ca-32de-411f-adde-437674cb7028.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by CrusherMods** [comment]
My amount of disappointment of people not being able to read the README.md or that txt file...

**Comment by NoobyWasTaken** [comment]
literally just [update haxe](https://haxe.org/download/)
