### ISSUE TITLE
Why does windows defender detect psych engine 0.5 as a unrecognized program

### ISSUE THREAD

**Issue by RealMhin** [ShadowMario/FNF-PsychEngine#2317]
### What is your question?

i recently downloaded psych engine 0.5 then after i tried to open it windows defender pop up it says its a unrecognized program and I'm just scared its not safe here's a preview

https://user-images.githubusercontent.com/91032986/146658460-96a7a519-fd0b-488f-9d87-d49691c7ace5.mp4

**Comment by tposejank** [comment]
This is windows that is dumb and thinks haxeflixel programs are virus. However you can ignore it by pressing More info >> Run anyway.
It is safe

**Comment by RealMhin** [comment]
@tposejank thanks

**Comment by juanroman74454811** [comment]
Yeah! Windows defender is a stupid little bitch who is 0 IQ
