### ISSUE TITLE
Game Crash upon Event Select (v0.5)

### ISSUE THREAD

**Issue by NoobyWasTaken** [ShadowMario/FNF-PsychEngine#2325]
### Describe your bug here.

When the chart is empty, events work as normal. But when there is even a single note in the chart, trying to do anything with events crashes the game.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by bbpanzu** [comment]
record and try to recreate this issue

**Comment by NoobyWasTaken** [comment]
https://user-images.githubusercontent.com/88544062/146666460-8bcd5a40-47ca-4b15-867e-3131e528dbd0.mp4

**Comment by bbpanzu** [comment]
kk fixed
