### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by VRfunkin** [ShadowMario/FNF-PsychEngine#2330]
### Describe your problem here.

Warning: Could not find Visual Studio 2017 VsDavCmd
Missing: HXCPP_VARS
Error Could not automatically setup MSVC
What does this mean? Did I do something wrong? its been like that for about an hour. should leave the command to run or do something

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by bbpanzu** [comment]
haxe issue. not a psych issue
