### ISSUE TITLE
How to fix song not loading

### ISSUE THREAD

**Issue by Unkn0wnGamin** [ShadowMario/FNF-PsychEngine#2338]
### Describe your problem here.

When I make the song and put into fnf to chart, it wont let me, the song would not load at all. 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
Give more details, how exactly does it not load?

**Comment by Unkn0wnGamin** [comment]
![image](https://user-images.githubusercontent.com/91464340/146708691-3d27cf0e-ee3e-4135-adbc-556b38154f8e.png)
I cannot play song

**Comment by titopops** [comment]
> ![image](https://user-images.githubusercontent.com/91464340/146708691-3d27cf0e-ee3e-4135-adbc-556b38154f8e.png) I cannot play song

If the song name doesn't exist, then the song does not start, put the song name in here.
![image](https://user-images.githubusercontent.com/93490646/146722519-c3f7cf15-2c0f-4200-87ba-026ca5410c73.png)

if you already did that, there might be a spelling error

also it should be in assets (or mods)/songs if you didnt do that.

**Comment by Unkn0wnGamin** [comment]
> > ![image](https://user-images.githubusercontent.com/91464340/146708691-3d27cf0e-ee3e-4135-adbc-556b38154f8e.png) I cannot play song
> 
> If the song name doesn't exist, then the song does not start, put the song name in here. ![image](https://user-images.githubusercontent.com/93490646/146722519-c3f7cf15-2c0f-4200-87ba-026ca5410c73.png)
> 
> if you already did that, there might be a spelling error
> 
> also it should be in assets/songs if you didnt do that.

![image](https://user-images.githubusercontent.com/91464340/146727582-cc09d18c-4b88-4a26-a59e-ef9e798144a6.png)
I did what you said but it didnt work

**Comment by cherryiguess** [comment]
> > > ![image](https://user-images.githubusercontent.com/91464340/146708691-3d27cf0e-ee3e-4135-adbc-556b38154f8e.png) I cannot play song
> > 
> > 
> > If the song name doesn't exist, then the song does not start, put the song name in here. ![image](https://user-images.githubusercontent.com/93490646/146722519-c3f7cf15-2c0f-4200-87ba-026ca5410c73.png)
> > if you already did that, there might be a spelling error
> > also it should be in assets/songs if you didnt do that.
> 
> ![image](https://user-images.githubusercontent.com/91464340/146727582-cc09d18c-4b88-4a26-a59e-ef9e798144a6.png) I did what you said but it didnt work

if your song name is "y3llow idol" in the files, it has to be "y3llow-idol", you dont have to do this for the song name in game, just the files

**Comment by osc-omb** [comment]
one common thing i see: The audio HAS to be .ogg files. NOT .mp3 or .wav files.

**Comment by Likemea** [comment]
everytime i try to load my song/chart, it loads, but it's a zero second song, and i can't press space, and if i press enter the notes glitch and bf and gf play the first idle animation forever, please help.
