### ISSUE TITLE
when changing a character using the character change event the game lags

### ISSUE THREAD

**Issue by DeceptedPar** [ShadowMario/FNF-PsychEngine#2339]
### Describe your bug here.

it didn't use to do this, it's just has a lag spike.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Gingerbreadman12456** [comment]
that's just your game loading the character

**Comment by DeceptedPar** [comment]
that's the thing though, on older versions of psych it never used to do this

**Comment by DeceptedPar** [comment]
for example, you can try it out on version 0.4.2, it doesn't lag at all

**Comment by TheLeerName** [comment]
idk why, but try type in lua file `precacheImage('characters/your_character');` in `function onCreate()`. Engine will preload character in song start

**Comment by DeceptedPar** [comment]
I would make it (source code wise) so when you load the engine everything pre-loads
but that would make loading up the engine so much pain
