### ISSUE TITLE
"Warning: UPDATE HAXE TO 4.2.4" still appears after i updated haxe

### ISSUE THREAD

**Issue by fnaffan29** [ShadowMario/FNF-PsychEngine#2344]
### Describe your problem here.

i updated haxe to 4.2.4 and the message saying "Warning: UPDATE HAXE TO 4.2.4" still appears after i try to compile the game

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by SrtHero278** [comment]
They don't check if you're using 4.2.4. They're just reminding you.

**Comment by fnaffan29** [comment]
> They don't check if you're using 4.2.4. They're just reminding you.

oh thanks

**Comment by Reycko** [comment]
close the issue :/
