### ISSUE TITLE
How to delete the song name in the menu?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#2345]
### What is your question?

I add some other songs, I want to add them into the menu below and delete existing ones, how to do it?

![image](https://user-images.githubusercontent.com/13177997/146683486-4c6e8652-187e-43d7-9a60-bb506863be55.png)

**Comment by TheLeerName** [comment]
To delete OG songs: delete week files from `assets/weeks`, or type in it `hideFreeplay: true,`
To add new songs: add week file in `mods/weeks` (you can add it in assets anyway), take template from any OG week file
> OG = Original Game (FNF)

**Comment by Templarfreak** [comment]
iirc You can also use the weekList.txt file to reorganize the weeks. By default, the weeks are sorted alpha-numerically, but the base PsychEngine weekList.txt file sorts the tutorial week to the top.
