### ISSUE TITLE
Custom weeks stay on the storymenu even after deletion

### ISSUE THREAD

**Issue by PersonNanoexe** [ShadowMario/FNF-PsychEngine#235]
Added "week7 (json name, not the actual week)" as a new week, while removing the other ones. 

First off, after deleting the other week jsons, the week7 one couldnt be edited anymore. Adding or removing stuff from the json also didnt work.

I deleted the week7 json and removed it from weekList. But it still stayed up. The original json isnt anywhere, mods, preload, nowhere, but it still shows up

**Comment by ShadowMario** [comment]
Look out for duplicates of your files, the engine can't just simply create copies of it automatically so it's not an engine issue.
