### ISSUE TITLE
LUA Random Number ?

### ISSUE THREAD

**Issue by Reycko** [ShadowMario/FNF-PsychEngine#2351]
### Describe your problem here.

idk like self explainatory i just want to know if there is a random number thing on lua

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by bbpanzu** [comment]
there is

**Comment by Reycko** [comment]
what is the "command" ?

**Comment by Templarfreak** [comment]
Lua has its own manual. It's a little daunting at first, but nothing doing some quick google searches doesn't fix:

https://www.lua.org/manual/5.1/
https://letmegooglethat.com/?q=lua+math.random

**Comment by Reycko** [comment]
nice
