### ISSUE TITLE
Game freezes when changing character mid-song with a precache script

### ISSUE THREAD

**Issue by Zer0PXL** [ShadowMario/FNF-PsychEngine#2352]
### Describe your bug here.

The title is pretty self explanatory. The problem is the game didn't freeze in the previous version...

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not.

**Comment by bbpanzu** [comment]
add the character sprite sheet onto the stage but add it behind everything else. that should cache the character well

**Comment by Zer0PXL** [comment]
I would've never thought of that, thank you!
