### ISSUE TITLE
Left Hold Custom note Crashing the game 0.5 Release Build

### ISSUE THREAD

**Issue by RealReal334** [ShadowMario/FNF-PsychEngine#2353]
### Lua Custom Notes

**after Enemy/Boyfriend Finish Custom left Held note The Game Crashed** 

the problem isn't with the xml iv'e tripple checked and the Assets works fine

The Problem is with the source i think

that's it pretty straight to the point

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I didn't editted the source file since it's a Build

**Comment by RealReal334** [comment]
The Problem is still occur in 0.51

**Comment by ShadowMario** [comment]
You didn't tell me if you changed something in the song, if you changed Note asets, some hold note animation is named wrong on the XML file.
