### ISSUE TITLE
Game crashing with vs dave and bambi charts

### ISSUE THREAD

**Issue by Reycko** [ShadowMario/FNF-PsychEngine#2359]
### Describe your bug here.

look at the title because it's self explainatory

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i just ported vs dave and bambi to psych engine (using the mods folder)

**Comment by SrtHero278** [comment]
I have this problem too. I feel like it's because it's litterally one section.
![image](https://user-images.githubusercontent.com/93018286/146693614-c1b6027c-5774-4305-ab6c-a5a7e4d98f83.png)
I mean, what other reason would you have for this?

**Comment by tposejank** [comment]
no

**Comment by SkyanUltra** [comment]
> no

the mod port worked in 0.4.2. some change in 0.5 probably causes charts that are only built on a single section like that to break.

either way, it's an issue the person who made the port is gonna have to fix themselves cause those charts are fucked anyways

**Comment by ShadowMario** [comment]
I can't help on charts from other mods, and i dislike helping on mod ports.

**Comment by Reycko** [comment]
Wait a minute, Why porting to Psych 0.4.2 then to 0.5 works ?

**Comment by Reycko** [comment]
Nevermind
