### ISSUE TITLE
Null Object Reference even though I added the png

### ISSUE THREAD

**Issue by YeehawPeppinoGuy** [ShadowMario/FNF-PsychEngine#236]
I'm trying to add more custom characters to Psych Engine. The first time I made one, It worked. However, when I type in the image file, it just crashes and says "Uncatchable Throw, Null Object Reference" even though there are the pngs and xmls of the character in assets/images/characters. I'm using Mommy Mearest as a base, if that helps

**Comment by YeehawPeppinoGuy** [comment]
Nevermind, I put it in the wrong path.

**Comment by Steviegt6** [comment]
Close the issue, then.

**Comment by ShadowMario** [comment]
> Close the issue, then.

^
Close your issues bruh
