### ISSUE TITLE
Offscreen "strum notes" are not detected by the engine.

### ISSUE THREAD

**Issue by Reycko** [ShadowMario/FNF-PsychEngine#2386]
### Describe your bug here.

So if a "strum note" is offscreen, The notes are weird:

- Missing and Hitting does nothing
- Scripts with the function opponentNoteHit, noteMiss and goodNoteHit does not work.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, Just a M.I.L.F script

**Comment by ShadowMario** [comment]
More information about your issue is needed.

**Comment by Reycko** [comment]
> offscreen in what axis? Y or X?

Both
