### ISSUE TITLE
modchart bug

### ISSUE THREAD

**Issue by Adriangamer1246** [ShadowMario/FNF-PsychEngine#2387]
### Describe your bug here.

the modchart lua doesnt work idk whats wrongs
![Screenshot (58)](https://user-images.githubusercontent.com/58314609/146779635-32a6b610-a17e-49e9-aefa-84f1706d9a08.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by tposejank** [comment]
Thats a kade engine modchart. Do you know  this is a D I F F E R E N T Engine?

**Comment by Adriangamer1246** [comment]
how the fuck am i supposed to know its from kade engine

**Comment by tposejank** [comment]
Dude, the wiki exists

**Comment by Adriangamer1246** [comment]
i just need the one that i need

**Comment by Adriangamer1246** [comment]
and i never even see the kade engine wiki

**Comment by SkyanUltra** [comment]
> how the fuck am i supposed to know its from kade engine

as we all know the words kade and psych are exactly the same with no differences meaning this also applies to code entirely
