### ISSUE TITLE
Can you tween a character in both x and y?

### ISSUE THREAD

**Issue by FartMaster57** [ShadowMario/FNF-PsychEngine#2397]
### Describe your problem here.

I wanna make a character move in sort of a circular motion, when it tweens up in the y axis I want the character to go left on the x axis, and vice versa. But if I add a tween for X and Y in the same script, it only executes one of those tweens. Is there a way to do this or is it impossible?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I've added a few custom characters and songs

**Comment by RealReal334** [comment]
try Changing Tween Tag

Example 

function onCreate()

doTweenX('tween1','dad',500, 3, 'linear') -- Tween X tag is **tween1**
doTweenY('tween2','dad',500, 3, 'linear') -- Tween Y tag is **tween2**

end
