### ISSUE TITLE
event playing even tho EventJSon doesnt exist.

### ISSUE THREAD

**Issue by DaGhostyDude** [ShadowMario/FNF-PsychEngine#2398]
### Describe your problem here.

so I made a song in which the character changes once. I put in the change character event with the value one as DAD and the second as the character. of course, it didn't work. then I fixed it by changing the value one to 1. then it worked. I saved it. but each time I restart the game the old event JSON plays. this happened like. one and a half weeks ago. I am trying to fix it since then. I tried everything. redoing the whole data folder, changing the event JSON manually. I tried literary everything, and the event even plays when no event JSON exists. it also appears in the chart editor, but when I press load events the new one pops up which does work. the old event even appeared after I ported it to version 0.5. XD I'm laughing at this point. it's haunting me. the file is no longer on my computer. I don't get it. (it happens both on 64x and 32x)

ever happened to you before? please help-- 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by tposejank** [comment]
events can also play from the song chart

**Comment by DaGhostyDude** [comment]
> events can also play from the song chart

I'll make sure to check that as soon as I get access to my PC again asap

**Comment by ShadowMario** [comment]
Events are loaded from two files:
mods/data/your-song-name/events.json
mods/data/your-song-name/your-song-name.json (or whatever difficulty you're in)

Check those two files.
