### ISSUE TITLE
How do you make a custom menu character?

### ISSUE THREAD

**Issue by fxjisaki** [ShadowMario/FNF-PsychEngine#24]
Theres no tutorial for it and i cant rlly figure it out, any help?

**Comment by ShadowMario** [comment]
I'd suggest copying a character on MenuCharacter.hx and editting it.
Menu Characters are still hardcoded (You need the source code to change it), but it won't be like this in the next update.

**Comment by fxjisaki** [comment]
wow i completly forgor that menucharacter.hx existed, im stupid, thanks anyways!
