### ISSUE TITLE
How to Adjust LuaSpriteAnimation Offsets 

### ISSUE THREAD

**Issue by RealReal334** [ShadowMario/FNF-PsychEngine#2402]
### Describe your problem here.

it should be done by using SetProperty()
but I don't know How

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No I didn't editted the source file

**Comment by bbpanzu** [comment]
setProperty("sprite.offset.x",offsetnumber)
