### ISSUE TITLE
BF suddenly appearing twice.

### ISSUE THREAD

**Issue by Zer0PXL** [ShadowMario/FNF-PsychEngine#2405]
### Describe your bug here.

I recently changed PCs and after moving everything over this happened. The game would put another boyfriend behind the opponent... Even with no script, it still happens.
![fuck](https://user-images.githubusercontent.com/84981290/146826905-63f20ec6-115c-4303-a37c-88f556809de5.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by cherryiguess** [comment]
thats the gf character, its set to bf
