### ISSUE TITLE
Sound not working?

### ISSUE THREAD

**Issue by supahsta** [ShadowMario/FNF-PsychEngine#2407]
### Describe your bug here.

I opened Psych Engine 0.5 after using 0.4.2 for playing Psych Engine mods and making my own.
After I downloaded the compiled version from GameBanana, I extracted the file, opened it and the sound is not working at all. I made sure my volume wasn't muted or very low, I tested with headphones, and even compated it to 0.4.2. The sound doesn't show up.
I downloaded the 64-bit version, by the way. I tried with the 32-bit version and the same thing happens. I don't know if it happens with a manually compiled version though.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I tried putting other mods in such as Holiday Part I and some upcomming mods I'm making. I've also installed the 32-bit version.

**Comment by chilleryzz** [comment]
Are you sure the volume is all the way up? Click +

**Comment by supahsta** [comment]
huh, it worked
I dunno why it started mute.
