### ISSUE TITLE
Change the health value from 0-2 to 0-100

### ISSUE THREAD

**Issue by TBiscuit1** [ShadowMario/FNF-PsychEngine#2408]
### What feature do you want to get added on the base engine?

Something that always bothered me is that the FNF devs for some god damn reason decided to have the health value be a value in between 0 and 2...

It aight much, but is it possible to make the health value go in between 0 and 100 instead? (and so tweak every value to match the old behavior)

This would break most codes since we got used to a value in between 0 and 2, but it would just make things clearer for new people Potentially, to avoid people accidentally inputing the wrong value, maybe add a small "warning" in the customevent files so people that are unaware of the new change can see it

**Comment by ShadowMario** [comment]
I don't want to change it.

**Comment by tposejank** [comment]
learn math
