### ISSUE TITLE
How to change it from 0-2 to 0-4 like Tabi

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#2409]
### Describe your problem here.

Idk how to do it, is it possible

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CrusherMods** [comment]
What do you mean?

**Comment by PDL2CGamejolt** [comment]
> What do you mean?

![image](https://user-images.githubusercontent.com/94698464/146836502-59ebfb32-3be8-4f8c-8551-198e0e41f3be.png)
like this

**Comment by ShadowMario** [comment]
![](https://user-images.githubusercontent.com/44785097/146858815-a10554ba-2d77-4386-9969-85b950e94401.png)
Your question also makes no sense.
