### ISSUE TITLE
Changing BPM on song charting

### ISSUE THREAD

**Issue by CarptP** [ShadowMario/FNF-PsychEngine#2411]
### Describe your bug here.

So i charted a part with 180 bpm and its bugged
All its frozen
how i fix that

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

**Comment by CarptP** [comment]
help ;-;

**Comment by osc-omb** [comment]
Change bpm is bugged. i recommend you change the song bpm to chart that part, then change the song bpm back to normal.
