### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by Blockyyy** [ShadowMario/FNF-PsychEngine#2413]
### Describe your bug here.

i was compilling the game with the recent update when i got an error when "source/StoryMenuState.hx:323: characters 12-14 : Expected )"

and couldnt compile the engine this was the very first line of the compilling thing
![Capture](https://user-images.githubusercontent.com/88585273/146842250-5c31c719-15eb-4e62-9701-4174b8cdd176.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by chilleryzz** [comment]
Update Haxe. Here's the link: https://haxe.org/
