### ISSUE TITLE
How do I code in death quotes in psych engine?

### ISSUE THREAD

**Issue by ToBAYT** [ShadowMario/FNF-PsychEngine#2414]
### Describe your problem here.

Something like week 7. When you die, tankman says something

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by DEV-idiotXD** [comment]
I only knw lua lol

**Comment by DEV-idiotXD** [comment]
But i knw how to do it in lua

**Comment by MasterDirector99** [comment]
Copy the Game Over Lines from the Week 7 Stage LUA

**Comment by ShadowMario** [comment]
GameOverSubstate.hx, make it play a sound on function create().
```haxe
new FlxTimer().start(4.0, function(tmr:FlxTimer)
{
	FlxG.sound.play(Paths.sound('gameOverQuotes/quote-') + FlxG.random.int(1, 5));
});
```
![Screenshot_2](https://user-images.githubusercontent.com/44785097/146850262-ad987361-f569-4026-a78c-c8782f9b9c7f.png)

Then create these files:
```
sounds/gameOverQuotes/quote-1.ogg
sounds/gameOverQuotes/quote-2.ogg
sounds/gameOverQuotes/quote-3.ogg
sounds/gameOverQuotes/quote-4.ogg
sounds/gameOverQuotes/quote-5.ogg
```

If you want to add more death quotes, change the `FlxG.random.int(1, 5)` to `FlxG.random.int(1, Whatever is the max number of quotes)`

**Comment by DEV-idiotXD** [comment]
also lua


function onGameOver()
    createtable(deathsounds)
    local random = math.random(1 , 10)
    playSound(deathsounds[random], 1,)

	return Function_Continue;
end


local function createtable(a)
    a = {}
    a[1] = 'death_sound1'
    a[2] = 'death_sound2'
end

**Comment by ToBAYT** [comment]
@ShadowMario Aint working

**Comment by realShanDev** [comment]
Hey, ShadowMario, any chance that you'll help here again?

**Comment by HeyItsUT** [comment]
@ShadowMario know you got stuff to do, but where would I put this exactly?

**Comment by MemeHovy** [comment]
will you dumbasses stop pinging him? he has his notifications off

**Comment by realShanDev** [comment]
I can agree–we shouldn't have pinged, but can you blame us? ShadowMario suggested a fix/implementation of code that didn't even work. So I think it was only natural that we try and ask for further assistance.

**Comment by MemeHovy** [comment]
> I can agree–we shouldn't have pinged, but can you blame us? ShadowMario suggested a fix/implementation of code that didn't even work. So I think it was only natural that we try and ask for further assistance.

he has his notifications off, pinging him will do nothing
