### ISSUE TITLE
Need help to fix

### ISSUE THREAD

**Issue by ByronisJoan** [ShadowMario/FNF-PsychEngine#2429]
### Describe your bug here.

I was trying to build the game it says source/StoryMenuState.hx:185: characters 4-6 : Expected } 
I see nothing wrong with if (controls.UI_DOWN_P)

### Command Prompt/Terminal logs (if existing)

```bash
Windows Powershell
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not Edit anything In my build

**Comment by tposejank** [comment]
Update haxe

**Comment by ByronisJoan** [comment]
> Update haxe

did not work
