### ISSUE TITLE
Building game

### ISSUE THREAD

**Issue by Maxstar13** [ShadowMario/FNF-PsychEngine#2436]
### Describe your problem here.

When i try to do lime test windows i have this error " source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int } "(0.5 Btw) 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by KutikiPlayz** [comment]
*cough cough*
![Screenshot (1001)](https://user-images.githubusercontent.com/73810550/146886520-f3e7140a-ce21-44c8-bd52-a96828e38173.png)

**Comment by Maxstar13** [comment]
> _cough cough_ ![Screenshot (1001)](https://user-images.githubusercontent.com/73810550/146886520-f3e7140a-ce21-44c8-bd52-a96828e38173.png)

![image](https://user-images.githubusercontent.com/95436428/146965795-5a895318-a9dd-41d8-bb65-c3fb74a1d28d.png)
 I have installed it now I have this error

**Comment by KutikiPlayz** [comment]
try reinstalling lime I guess

**Comment by Maxstar13** [comment]
> try reinstalling lime I guess

can you give me a link?

**Comment by ElVideoFanXd10** [comment]
> > try reinstalling lime I guess
> 
> can you give me a link?

No

**Comment by ZebVince** [comment]
Type These In CMD You Might Need It

haxelib install lime 7.9.0
haxelib install openfl
haxelib install flixel
haxelib run lime setup
haxelib run lime setup flixel
haxelib install flixel-tools
haxelib run flixel-tools setup
haxelib install flixel-addons
haxelib install flixel-ui
haxelib install hscript
haxelib install newgrounds
haxelib install linc_luajit
haxelib git faxe https://github.com/uhrobots/faxe
haxelib git polymod https://github.com/larsiusprime/polymod.git
haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc

**Comment by Maxstar13** [comment]
> haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc

I had this error 
source/Achievements.hx:157: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/MainMenuState.hx:65: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:312: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/CharacterEditorState.hx:93: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/DialogueCharacterEditorState.hx:82: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:145: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:180: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:221: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:515: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:483: characters 37-56 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:484: characters 31-47 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:646: characters 10-42 : Warning : Std.is is deprecated. Use Std.isOfType instead.
source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
D:\FNF\pyshicstuff\newsource\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by KutikiPlayz** [comment]
you need to get visual studio 2017
I think brightfyre's kade engine tutorial should help with that

**Comment by Maxstar13** [comment]
> you need to get visual studio 2017 I think brightfyre's kade engine tutorial should help with that

I already have both visual installed

**Comment by KutikiPlayz** [comment]
did you get the right addons and such for it?

**Comment by Maxstar13** [comment]
> did you get the right addons and such for it?

Yes im pretty sure

**Comment by Maxstar13** [comment]
Oh it finally worked

**Comment by ZebVince** [comment]
Maxstar13 i forget to do this one to git clone discord_rpc https://github.com/Aidan63/linc_discord-rpc

**Comment by ZebVince** [comment]
> > haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
> 
> I had this error source/Achievements.hx:157: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead source/MainMenuState.hx:65: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead source/PlayState.hx:312: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead source/editors/CharacterEditorState.hx:93: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead source/editors/DialogueCharacterEditorState.hx:82: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:145: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:180: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:221: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:515: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:483: characters 37-56 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:484: characters 31-47 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:646: characters 10-42 : Warning : Std.is is deprecated. Use Std.isOfType instead. source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead D:\FNF\pyshicstuff\newsource\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion Warning: Could not find Visual Studio 2017 VsDevCmd Missing HXCPP_VARS Error: Could not automatically setup MSVC

Sorry Not Replaying Yesterday

**Comment by Maxstar13** [comment]
> > > haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
> > 
> > 
> > I had this error source/Achievements.hx:157: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead source/MainMenuState.hx:65: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead source/PlayState.hx:312: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead source/editors/CharacterEditorState.hx:93: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead source/editors/DialogueCharacterEditorState.hx:82: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:145: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:180: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:221: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:515: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:483: characters 37-56 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:484: characters 31-47 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/FNF/pyshicstuff/programs/haaaxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:646: characters 10-42 : Warning : Std.is is deprecated. Use Std.isOfType instead. source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead D:\FNF\pyshicstuff\newsource\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion Warning: Could not find Visual Studio 2017 VsDevCmd Missing HXCPP_VARS Error: Could not automatically setup MSVC
> 
> Sorry Not Replaying Yesterday

Don't worry I got it finally working
