### ISSUE TITLE
Voice Acting Dialogue

### ISSUE THREAD

**Issue by StrangeSpyder** [ShadowMario/FNF-PsychEngine#2441]
### What is your question?

I would love to attempt to code in audio clips for each set of dialogue, but I'm unsure where to begin. Is there something I can do to begin or what would be a good way to set up audio clips for dialogue?

**Comment by juanroman74454811** [comment]
you may need to ask the ghost twins devs to help you on how to replicate this

**Comment by StrangeSpyder** [comment]
> you may need to ask the ghost twins devs to help you on how to replicate this

Dont they have the code specificallty for the Kade Engine and could it seamlessly code towards the Psych Engine?

**Comment by DEV-idiotXD** [comment]
I knw how to do it in lua

**Comment by StrangeSpyder** [comment]
> I knw how to do it in lua

Could you show me how, would be appreciated!

**Comment by DEV-idiotXD** [comment]
Im not currently on my pc rn so i cant code it sry ill just dm it to u on discord when i get onto my pc

My dis : dev!#3592

**Comment by StrangeSpyder** [comment]
> 

Sounds good, Thank you so much!

**Comment by ArezalGame89** [comment]
Didn't just bbpanzu make something like that in holiday part II?

**Comment by StrangeSpyder** [comment]
> Didn't just bbpanzu make something like that in holiday part II?

Indeed, but I am using the Source Code to run almost everything and unsure how to use a script along with source code if that is even possible.
