### ISSUE TITLE
Bug report psych engine keeps crashing

### ISSUE THREAD

**Issue by Coolgaymerboi** [ShadowMario/FNF-PsychEngine#2443]
### Describe your bug here.

When I was making my mod I was trying to import the mods from chaos import but then it worked! It was running for a while after making the week but after a few seconds before a second animation started playing in the week it freezed a few seconds and after that the game crashed... 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes I tried to make a mod but it keeps crashing after making the events and the arrows and trying to open the game

**Comment by RealReal334** [comment]
Does it Crash after the Left Hold note finished?
if yes
I'm trying to report this problem too

**Comment by LiterallyJustKate** [comment]
Yo uhhhh Psych Engine keeps crashing when I try to go to credits.

**Comment by Mastercopper2346** [comment]
It’s unfortunately a pc issue
