### ISSUE TITLE
Cannot compile the Engine

### ISSUE THREAD

**Issue by MatteoNobler** [ShadowMario/FNF-PsychEngine#2446]
### Describe your problem here.

C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:11: characters 8-37 : Type not found : flixel.util.FlxDirectionFlags
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:484: characters 21-25 : Unknown identifier : WALL
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:504: characters 21-25 : Unknown identifier : WALL
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:530: characters 21-28 : Unknown identifier : CEILING
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:550: characters 21-26 : Unknown identifier : FLOOR

Probably I am missing some package,but I don't know which one; can someone help me? (Yes,I am using Haxe 4.2.4)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No I didn't; It's a fresh build I wanted to compile

**Comment by Reycko** [comment]
Update / Reinstall flixel addons:

Update: `haxelib update flixel-addons`

Reinstall:
`haxelib remove flixel-addons && haxelib install flixel-addons`

**Comment by MatteoNobler** [comment]
Thank you for the suggest,but I tried it (both 'Update' and 'Remove and Reinstall') and it didn't work; I always got the same error
