### ISSUE TITLE
Middle Scroll Opponent strum opacity

### ISSUE THREAD

**Issue by Reycko** [ShadowMario/FNF-PsychEngine#2449]
### What feature do you want to get added on the base engine?

I think the title is self explainatory but i'll explain better:
An option to change the opacity of the opponent strums with middle scroll.

**Comment by bbpanzu** [comment]
might

**Comment by DEV-idiotXD** [comment]
Someones already did this but its for 4.2.0

**Comment by Mastercopper2346** [comment]
LOL, HE STILL DID IT THOUGH

**Comment by DEV-idiotXD** [comment]
> LOL, HE STILL DID IT THOUGH

lmao yeh
