### ISSUE TITLE
Song not playing.

### ISSUE THREAD

**Issue by AsiaDoesStuff** [ShadowMario/FNF-PsychEngine#2451]
### Describe your bug here.

All I did was I replaced the Audio File with another one, (I made sure it was 'Inst' with a capital I & Made sure it was an .OGG File), and now whenever I go into the Week, it does the '3, 2, 1, go' thing but after that, all of the characters on screen just freeze in place, the Song doesn't play, and there are no arrows whatsoever. When I go to the  Chart Editor, (I clicked 7 when playing the week), none of the buttons work, it won't let me scroll through the arrow chart, it's just frozen me in place. 
What do I do?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I don't know.

**Comment by Reycko** [comment]
Does the song have a chart ?

**Comment by bbpanzu** [comment]
convert the song ogg to an ogg again. it should be a encoding issue

**Comment by AsiaDoesStuff** [comment]
> Does the song have a chart ?

Yes, It does. I clicked 'Reload .JSON' just now and now it shows the arrows, but they just stop on the screen before the song can start, and they jitter up and down on the spot too.

**Comment by AsiaDoesStuff** [comment]
Maybe it's because I changed the Song name? But I did change all the song's files to the new song name, so I don't know what else could be the problem.

**Comment by ShadowMario** [comment]
You have to show where you saved the files.
