### ISSUE TITLE
Exiting the charting menu and going to a song will still have charting mode activated

### ISSUE THREAD

**Issue by dum-du-m** [ShadowMario/FNF-PsychEngine#2454]
### Describe your bug here.

Charting mode is on if you exit the charting menu by pressing ESC and go to a song.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by RedstoneRuler** [comment]
You need to press enter. Backspace is playtest.

**Comment by dum-du-m** [comment]
> You need to press enter. Backspace is playtest.

oh right i meant escape

**Comment by ShadowMario** [comment]
That's not a bug, that's what Charting Mode is.

**Comment by dum-du-m** [comment]
> That's not a bug, that's what Charting Mode is.

??????? so you not being able to leave the charting mode is not a bug okay i guess
