### ISSUE TITLE
A image showing

### ISSUE THREAD

**Issue by juanroman74454811** [ShadowMario/FNF-PsychEngine#2459]
### What feature do you want to get added on the base engine?

Tanrie in your screen when booting game in 1/200
![Tanner](https://user-images.githubusercontent.com/92176733/146969948-8b075108-2004-414c-b7fc-21e58cd3960b.png)
![Marie](https://user-images.githubusercontent.com/92176733/146969994-688cd517-20d7-4d1f-b12d-05f3af2c98d5.png)

**Comment by crispyboi24** [comment]
What

**Comment by SrtHero278** [comment]
They aren't associated with Mind Games, Psych engine, or the Base Game at all. Please stop.

**Comment by tposejank** [comment]
shut the fuck up

**Comment by juanroman74454811** [comment]
i can code this by just bloating the heck out of haxeflixel and see what happens

**Comment by ByronisJoan** [comment]
> shut the fuck up

People Who Cuss, i Hope For them To....You Don't Wanna Know....
