### ISSUE TITLE
Why does my char even put error

### ISSUE THREAD

**Issue by juanroman74454811** [ShadowMario/FNF-PsychEngine#2462]
### Describe your problem here.

Why does my char says (ERROR!)?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by bbpanzu** [comment]
animation xml name is wrong

**Comment by juanroman74454811** [comment]
Thanks bbpanzu, have a good day

**Comment by dum-du-m** [comment]
> Thanks bbpanzu, have a good day

the issue is solved pls close the issue
