### ISSUE TITLE
Black square around down note

### ISSUE THREAD

**Issue by Nightkniyt** [ShadowMario/FNF-PsychEngine#2463]
### Describe your bug here.

Recently compiled the newest version and loaded in Bopeebo, works normal except whenever it’s the opponents turn the left note has a black square behind it, plus a smaller square shows up next to it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only PlayState.hx for the stages

**Comment by tposejank** [comment]
your computer is running low on ram
