### ISSUE TITLE
why it ain't building

### ISSUE THREAD

**Issue by SanLLL** [ShadowMario/FNF-PsychEngine#2464]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/88852249/146983155-781734b3-6e4b-42e6-b486-cd29c12e662e.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by Rorthgamer2XD** [comment]
did you build it in `C:\Users\sgape\onedrive\documents\dfnf`

Also To fix it You need the files `Controls.hx` It's should be on the `DFNF\source`
if it's isn't there then you might have to redownload a new one and put your old stuff in the new redownloaded folder

**Comment by SanLLL** [comment]
ok, thx
