### ISSUE TITLE
> Updated Flashing Event

### ISSUE THREAD

**Issue by denisyss** [ShadowMario/FNF-PsychEngine#2475]
> Updated Flashing Event
> 
> Fixed lua And Added Color Cyan And Purple!
> 
> here dowload : https://www.mediafire.com/file/eobk5lg3a2horj3/Flashing_Event.rar/file

_Originally posted by @denisyss in https://github.com/ShadowMario/FNF-PsychEngine/discussions/2468#discussioncomment-1854933_

**Comment by FuseIsHere813** [comment]
Put this in discussions.
