### ISSUE TITLE
mod folder bug

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#2476]
### Describe your bug here.

so i have a mod that has a custom menu BG, intro text, and week jsons that replace in game ones, but whenever i enable the mod, the intro text, menu bg, and week jsons dont load. and it turns off the mod once i go into the mod menu again. (this mod pack restarts the game btw.) i could record it if needed. 

the mod does work when its all inn the mod folder itself though, instead of a mod pack folder. so im a bit confused on why it doesnt work once its turned into a mod pack.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by bbpanzu** [comment]
modpack folder is just like the mod folder except they need to be loaded as opposed to the mods/ folder which is loaded by default. is you mod at the top of the list in the mod folder?

**Comment by DaBanana64** [comment]
I think the mod loader can't be used for replacing the base game assets sadly.
I tries my best to replace them but it didn't work.

**Comment by crispyboi24** [comment]
> modpack folder is just like the mod folder except they need to be loaded as opposed to the mods/ folder which is loaded by default. is you mod at the top of the list in the mod folder?

yep. it is at the top. it loads the title screen, menu bg, and menu music. but if i press freeplay or storymode, it only loads the base game assets. and changes the menu bg back to the OG one. but it does keep the credits, title screen, and menu music.
