### ISSUE TITLE
A continuation

### ISSUE THREAD

**Issue by ToBAYT** [ShadowMario/FNF-PsychEngine#2480]
### Describe your problem here.

So basically, #2414 the code ain't working

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I puted the code in gameoversubstate between line 74 & 77 with a empty line at 73

**Comment by DEV-idiotXD** [comment]
I have code for lua do u want it?

**Comment by ShadowMario** [comment]
Yes and you didn't show me any errors or whatever in console.
