### ISSUE TITLE
Need permission

### ISSUE THREAD

**Issue by Pokeyboy2017** [ShadowMario/FNF-PsychEngine#2481]
### Describe your bug here.

I need permission in order to even use Psych engine for some reason. I was just working with 5.0 then with 5.1 It just stopped working and the actual game uninstalled itself.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes I am currently changing characters.

**Comment by ShadowMario** [comment]
Was there any errors on the console while compiling? Show me the command prompt/whatever you used `lime test windows` on.

**Comment by tposejank** [comment]
Windows defender moment

**Comment by Pokeyboy2017** [comment]
Fixed it! Just had to restart computer!

**Comment by FuseIsHere813** [comment]
Then close the issue lol.
