### ISSUE TITLE
Moving Background Characters Horizontally

### ISSUE THREAD

**Issue by bestuff44** [ShadowMario/FNF-PsychEngine#2483]
### Describe your problem here.

How do I get background characters to move, and how do I do it at a specific time?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
```lua
if getSongPosition() > 30000 then  --over 30000 miliseconds of the song, aka30s
    setProperty('objectname.x', value);
end
```
