### ISSUE TITLE
renaming the program

### ISSUE THREAD

**Issue by Adriangamer1246** [ShadowMario/FNF-PsychEngine#2484]
### What is your question?

how the hell do i rename the program?
an example is if you rename the program in a file explorer and you open the game it says Friday Night Funkin': Psych Engine at the upper left corner
any way to rename that without souce code?

**Comment by cherryiguess** [comment]
its a source code thing, its in project.xml

**Comment by Adriangamer1246** [comment]
oh

**Comment by tposejank** [comment]
i think you can do
`
setPropertyFromClass('lime.app.Application', 'current.window.title', 'The window name')
` for lua however it wont change on startup
