### ISSUE TITLE
Updated Flashing Event v2

### ISSUE THREAD

**Issue by denisyss** [ShadowMario/FNF-PsychEngine#2487]
Updated Flashing Event v2
 
________________________________________________

Fixed lua And Added Color Cyan And Purple!

________________________________________________

Its Back!!! Dowload :  https://www.mediafire.com/file/33xmirqzc7zyghz/Flashing_Event.rar/file

________________________________________________

you can add colors by flashing if dosent tell me

_Originally posted by @denisyss in https://github.com/ShadowMario/FNF-PsychEngine/discussions/2486_

**Comment by tposejank** [comment]
Bruh put this in discussions
