### ISSUE TITLE
Arrow keys crash game

### ISSUE THREAD

**Issue by NekoDev-cyber** [ShadowMario/FNF-PsychEngine#249]
On the "Funkin" application pressing any keys will crash the game
it may be events or something else. I'm not sure all the available info 
I have

**Comment by NekoDev-cyber** [comment]
> > Funkin application??? Wdym
> 
> I may have changed it to Funkin on the source build :/

I'm used to kade so that's why I did it

**Comment by ShadowMario** [comment]
It is trying to load another engine's save file and so resulting in a crash.

**Comment by NekoDev-cyber** [comment]
ok nevermind it's happening to the real engine
