### ISSUE TITLE
Crete a Stage Editor / Creator and Menu editor

### ISSUE THREAD

**Issue by SundayAEA** [ShadowMario/FNF-PsychEngine#2497]
### What feature do you want to get added on the base engine?

wut

**Comment by KutikiPlayz** [comment]
![Screenshot (1003)](https://user-images.githubusercontent.com/73810550/147023042-6a5dcafa-c309-494d-8fc6-8a3a2a35075c.png)

**Comment by crispyboi24** [comment]
U BOTTA GET BANNED LMAOOO

**Comment by tposejank** [comment]
lmfaooooooo

**Comment by SomeRobloxPlayer** [comment]
Banned soon lmao

**Comment by DaBanana64** [comment]
"Crete"
Create*
![minor_spelling_mistake](https://user-images.githubusercontent.com/82652849/147088692-1108623a-c901-4219-a152-fa2d4704b882.png)
