### ISSUE TITLE
song port + note freezing

### ISSUE THREAD

**Issue by juanroman74454811** [ShadowMario/FNF-PsychEngine#2504]
### Describe your problem here.

When i port a song it like freezes the notes-

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

N O Y O U M O T H E R F U C K E R * dies *

**Comment by tposejank** [comment]
What did you edit
if you **ported** a song then you must have edited something

**Comment by lemz1** [comment]
is the json file name the same as the name of the song

**Comment by juanroman74454811** [comment]
yes, i was trying to port Exanimation (from the fnf x red mod)

**Comment by ShadowMario** [comment]
You're missing the Instrumental file.
Put it inside mods/songs/your-song-name/Inst.ogg

**Comment by juanroman74454811** [comment]
*cough cough* Im recharting Exanimation

**Comment by juanroman74454811** [comment]
e
