### ISSUE TITLE
Adding Difficulties Updated 

### ISSUE THREAD

**Issue by Yeet-18** [ShadowMario/FNF-PsychEngine#2507]
### Describe your problem here.

Hi I'm trying to see how to add custom difficulties to psych engine and the source seems to be different can you help me add it?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited CoolUtil.hx and made changes.

**Comment by SirBluberryDev** [comment]
This might help you.
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Adding-a-New-Difficulty

**Comment by Yeet-18** [comment]
I did not help.

**Comment by SirBluberryDev** [comment]
i sorry and idk then

**Comment by SirBluberryDev** [comment]
did you do it correctly?

**Comment by HiroMizuki** [comment]
if u did all the steps from the Adding a New Difficulty correctly, check if u got mistakes with commas at CoolUtil.hx or anything, it is really important

**Comment by KutikiPlayz** [comment]
That tutorial is outdated now, all you should need to do is go to coolutil, and add your difficulty.  
![Screenshot (1007)](https://user-images.githubusercontent.com/73810550/147140022-a2980d7d-25d4-45b1-a55b-fa24cf48be34.png)
Should look something like that. **Remember to put the comma after hard**
