### ISSUE TITLE
individual defeat animation

### ISSUE THREAD

**Issue by endergames231** [ShadowMario/FNF-PsychEngine#2513]
### Describe your problem here.

how to make individual defeat animations

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by dum-du-m** [comment]
what you mean

**Comment by tposejank** [comment]
wdym

**Comment by ShadowMario** [comment]
???

**Comment by AtaKanK4467** [comment]
its a special death animation as an example in vsaccelerant hank mod when you get shot to death it shows you a special death animation

**Comment by dum-du-m** [comment]
> its a special death animation as an example in vsaccelerant hank mod when you get shot to death it shows you a special death animation

in this case, on lua there's literally a script in the Lua Script API page on the wiki for this
