### ISSUE TITLE
for the love of god...

### ISSUE THREAD

**Issue by kittstone** [ShadowMario/FNF-PsychEngine#2519]
### What feature do you want to get added on the base engine?

please add a lua function that checks if an object is touching another object

i know we have isColliding BUT the problem with that is that the first time you use it, it works fine. but when you use it the second time, it just pushes the second object listed in the function (if you had it like isColliding('objectOne', 'objectTwo'), objectTwo would get pushed).

**Comment by tposejank** [comment]
this would be really good. you cant call functions in set property

**Comment by ShadowMario** [comment]
`objectsOverlap` now exists
