### ISSUE TITLE
MY GOD I GOT 2 BUGS

### ISSUE THREAD

**Issue by RoubertY** [ShadowMario/FNF-PsychEngine#2520]
### Describe your bug here.

first is the change difficulty selector, if i choose back then it will load null difficulty (which doesnt exist)
second, the engine a automatically puts me in botplay and i need to go to the chart editor and play the song ONLY on charting mode to play it normally

fix those two pls

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no nothing in it

**Comment by tposejank** [comment]
for the first one it might be fixed soon
for the second one... press ctrl on freeplay

**Comment by RoubertY** [comment]
oh thank u for the second one i didnt know

**Comment by ShadowMario** [comment]
First one was already fixed on the main repo...
Second one, press Ctrl on Freeplay or Story Mode, you should have read the tip on bottom of Freeplay.
