### ISSUE TITLE
How does it know which strumnotes to move?

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#2530]
### What is your question?
Windows 64bit Psych version 0.5
Hi,
I would like to know how it knows when I use **opponentStrums** that it needs to move the notes of the opponent.

![Unbenann2t](https://user-images.githubusercontent.com/87707926/147129588-93e2fc56-c1ef-4fce-9618-ed397b1b8f45.PNG)

The reason I want to know that is because I added a new strum that is literally just called opponentStrums2 and when I try the code with opponentStrums2 it doesn't work.

![Unbenannt](https://user-images.githubusercontent.com/87707926/147129603-a47e2a4d-4152-4857-8cc7-a714765a968d.PNG)

Thanks in advance.

**Comment by ShadowMario** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/44785097/147295769-5f996b62-727b-4b21-a2a8-2c86b98d3ee7.png)
Did you add the variables here?

**Comment by lemz1** [comment]
![Unbenannt](https://user-images.githubusercontent.com/87707926/147300256-135ada18-dbdc-48f2-aa33-adbd439477c7.PNG)

yes
