### ISSUE TITLE
Checking if the player presses space

### ISSUE THREAD

**Issue by kingyomoma** [ShadowMario/FNF-PsychEngine#2534]
### What is your question?

hello
im using psych engine 4.2

im trying to make it so that if I press space, then it will increase your health

here's what I have:
function onCreate()
    if keyJustPressed("space":String) == true then
        setProperty('health', getProperty('health')+0.05);
    end
end

when I open the song it says this:
![image](https://user-images.githubusercontent.com/96543290/147133716-8e95f335-c9c9-4c9d-8e39-acf09a3d01bf.png)

I would appreciate some help since I'm a lua noob

**Comment by kingyomoma** [comment]
i mean to say 0.4.2

**Comment by DaBanana64** [comment]
Delete `:Sting` in the second line maybe?
Also update your Psych the latest version is 0.5.1.

**Comment by Adrian47roblox** [comment]
delete :Sting and ready

**Comment by Reycko** [comment]
use:
```
function onUpdate(elapsed)
      if keyJustPressed("space") == true then
           setProperty('health', getProperty('health')+0.05);
      end
end
```

**Comment by kingyomoma** [comment]
ok its working now, thanks everyone 👍
