### ISSUE TITLE
Moving stage background

### ISSUE THREAD

**Issue by SirBluberryDev** [ShadowMario/FNF-PsychEngine#2538]
### Describe your problem here.

I finished my stage background and now I'm wondering how to move it left and right.
![image](https://user-images.githubusercontent.com/91642654/147138502-6aeb24ea-4ce4-41f4-aa10-84df15b0f2f8.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by KutikiPlayz** [comment]
FlxTween

**Comment by SirBluberryDev** [comment]
> FlxTween

ik but i need spesific istructions
or I just want to learn how to make a wavy background like in the dave and bambi mod
