### ISSUE TITLE
Won't Load Custom Characters

### ISSUE THREAD

**Issue by Indyboy2009** [ShadowMario/FNF-PsychEngine#254]
I have been trying to add a custom character for almost 5 hours now and it always crashes on the character creator thing. I have my custom character and .XML file in the right place. Why does it always crash when I type in the file directory? I also tried putting it in mods and it still crashed even then.

I cannot make a character .json file because of this bug.
It does this even when I just use the .PNG file so I don't know what the problem is. Please Help Me.

**Comment by ShadowMario** [comment]
Seems to be an issue on your .xml file.
