### ISSUE TITLE
how to make a wavy background like in the dave and bambi mod

### ISSUE THREAD

**Issue by SirBluberryDev** [ShadowMario/FNF-PsychEngine#2540]
### Describe your problem here.

so you know the dave and bambi mod, right? and do you know those wavy and moving backgrounds?
i want to do the same thing for my mod's backgrounds.

the code:

```
case 'srbBg':
				{
					var bg:BGSprite = new BGSprite('srbBg', -600, -200, 0.9, 0.9);
					add(bg);
					
				}
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by crispyboi24** [comment]
look at dave and bambis code??

**Comment by SirBluberryDev** [comment]
i cant find the source code version

**Comment by PDL2CGamejolt** [comment]
i want to do it in lua

**Comment by PDL2CGamejolt** [comment]
how do you make animated stages to make the wavy effect

**Comment by SirBluberryDev** [comment]
I just copied the dave and bambi source code

**Comment by PDL2CGamejolt** [comment]
> I just copied the dave and bambi source code

is it possible to make wavy stages in lua or animated stages

**Comment by SirBluberryDev** [comment]
probably...

**Comment by PDL2CGamejolt** [comment]
> probably...

can you find out

**Comment by SirBluberryDev** [comment]
> > probably...
> 
> can you find out

I'll try after I'm done with my mod

**Comment by PDL2CGamejolt** [comment]
ok

**Comment by tposejank** [comment]
THIS ISNT POSSIBLE IN LUA

**Comment by SirBluberryDev** [comment]
ayo calm down

**Comment by ByronisJoan** [comment]
> THIS ISNT POSSIBLE IN LUA

Ayo chill
