### ISSUE TITLE
A "Play Here" option in the chart editor.

### ISSUE THREAD

**Issue by bruh-guy** [ShadowMario/FNF-PsychEngine#2543]
### What feature do you want to get added on the base engine?

Can you add a "play here" feature like in Kade Engine's chart editor? It'd be really useful when using events to check if they're working properly.

**Comment by Gui-iago** [comment]
the Engine alreafy hás that, Just press ESC anywhere on the chart editor to play that specific section

**Comment by PDL2CGamejolt** [comment]
> the Engine alreafy hás that, Just press ESC anywhere on the chart editor to play that specific section

but the events dont do anything with that

**Comment by PersonNanoexe** [comment]
> but the events dont do anything
You do know you can just. Play the song. Or put the events at the start of the song, modify them until it looks good, and then put them where they should be, waiting 3 minutes isnt that hard

**Comment by bbpanzu** [comment]
then again. not waiting 3 minutes is easier. if possible, i might add that as a feature

**Comment by Ninjatintin** [comment]
Just press esc lol

**Comment by ShadowMario** [comment]
Kind of possible now, just not via the chart editor but in Charting mode
