### ISSUE TITLE
Weeklist

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#2549]
### Describe your bug here.

So whenever I put the weeklist in the mod folder, it doesn’t work. Well it doesn’t work when I remove a week from the list. It still has the week in story mode.  

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
weekList is there for ordering weeks, not for removing them.
If you want to remove a week, you can either delete the file or hide the week from freeplay/story mode with the checkboxes on Week Editor.
