### ISSUE TITLE
It's my psych engine, ok?

### ISSUE THREAD

**Issue by FellowDesert** [ShadowMario/FNF-PsychEngine#2551]
### Describe your bug here.

Recently, psych engine had been acting weird these days, 
![image](https://user-images.githubusercontent.com/95321047/147161451-56594855-feed-42b0-ac57-bbe97ae0a1c9.png)
It doesn't look clearly, but it has been appearing some dead pixels when i play
![image](https://user-images.githubusercontent.com/95321047/147161565-dad06e65-e395-4e4d-9d10-52503dbe75d2.png)
![image](https://user-images.githubusercontent.com/95321047/147161699-2cac083c-4d86-4045-93e6-451f373a78ef.png)
But, the most impressive thing to me is that when I was playing, it appeared a message and the game crashed
![image](https://user-images.githubusercontent.com/95321047/147161771-c7a5fca7-5191-48a1-ad0a-bacc6b7fc642.png)
Shadow Mario, if this is one of your jokes, it wasn't funny, it legit scared me!, lol!
I'm free to answer any question.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i deleted some of the things, but just to make the build less heavy.

**Comment by tposejank** [comment]
This isn't real
Bro this is gonna lead you to a ban

**Comment by HiroMizuki** [comment]
bro, why shadow mario would make it? It looks like u are faking, he would never make this thing of crash joke to something that many people use yknow, it would cause some confusion or fight

and about the dead pixels, or u made some shit at files, **or u made some overlay animation or smth to make fake dead pixels**, but well, if the dead pixels are not any of this, it may be technical issues, normal things from the monitor, not the engine i think

**Comment by FellowDesert** [comment]
> This isn't real Bro this is gonna lead you to a ban

Do i pass you the records? I actually recorded this because i was supposed to send the dead pixels

**Comment by FellowDesert** [comment]
> bro, why shadow mario would make it? It looks like u are faking, he would never make this thing of crash joke to something that many people use yknow, it would cause some confusion or fight
> 
> and about the dead pixels, or u made some shit at files, **or u made some overlay animation or smth to make fake dead pixels**, but well, if the dead pixels are not any of this, it may be technical issues, normal things from the monitor, not the engine i think

No, this hasn't happened because i did something weird to the build, because dead pixels appeared when i was playing Wednesday infidelity.
https://user-images.githubusercontent.com/95321047/147170708-c1aea7e7-4442-45b3-ae5b-59c0a6c3f6ca.mp4

**Comment by PDL2CGamejolt** [comment]
how do i make a message that crashes the game

**Comment by FellowDesert** [comment]
> how do i make a message that crashes the game

I would like to know it too

**Comment by HiroMizuki** [comment]
> > bro, why shadow mario would make it? It looks like u are faking, he would never make this thing of crash joke to something that many people use yknow, it would cause some confusion or fight
> > and about the dead pixels, or u made some shit at files, **or u made some overlay animation or smth to make fake dead pixels**, but well, if the dead pixels are not any of this, it may be technical issues, normal things from the monitor, not the engine i think
> 
> No, this hasn't happened because i did something weird to the build, because dead pixels appeared when i was playing Wednesday infidelity. https://user-images.githubusercontent.com/95321047/147170708-c1aea7e7-4442-45b3-ae5b-59c0a6c3f6ca.mp4

bro but this crash i'm still suspecting, we'll need to talk with Shadow Mario if this is a feature, i'll mention him here
@ShadowMario help here

**Comment by FellowDesert** [comment]
> > > bro, why shadow mario would make it? It looks like u are faking, he would never make this thing of crash joke to something that many people use yknow, it would cause some confusion or fight
> > > and about the dead pixels, or u made some shit at files, **or u made some overlay animation or smth to make fake dead pixels**, but well, if the dead pixels are not any of this, it may be technical issues, normal things from the monitor, not the engine i think
> > 
> > 
> > No, this hasn't happened because i did something weird to the build, because dead pixels appeared when i was playing Wednesday infidelity. https://user-images.githubusercontent.com/95321047/147170708-c1aea7e7-4442-45b3-ae5b-59c0a6c3f6ca.mp4
> 
> bro but this crash i'm still suspecting, we'll need to talk with Shadow Mario if this is a feature, i'll mention him here @ShadowMario help here

https://drive.google.com/file/d/1qtKqoc63kQzBumwpO7nN711VYeXgLwDl/view?usp=sharing
This is a .RAR file with 2 videos about the some of the glitches, you can contact me on discord here FellowDesert51#5850

**Comment by HiroMizuki** [comment]
> > > > bro, why shadow mario would make it? It looks like u are faking, he would never make this thing of crash joke to something that many people use yknow, it would cause some confusion or fight
> > > > and about the dead pixels, or u made some shit at files, **or u made some overlay animation or smth to make fake dead pixels**, but well, if the dead pixels are not any of this, it may be technical issues, normal things from the monitor, not the engine i think
> > > 
> > > 
> > > No, this hasn't happened because i did something weird to the build, because dead pixels appeared when i was playing Wednesday infidelity. https://user-images.githubusercontent.com/95321047/147170708-c1aea7e7-4442-45b3-ae5b-59c0a6c3f6ca.mp4
> > 
> > 
> > bro but this crash i'm still suspecting, we'll need to talk with Shadow Mario if this is a feature, i'll mention him here @ShadowMario help here
> 
> https://drive.google.com/file/d/1qtKqoc63kQzBumwpO7nN711VYeXgLwDl/view?usp=sharing This is a .RAR file with 2 videos about the some of the glitches, you can contact me on discord here FellowDesert51#5850

i think it's better wait Shadow Mario, cuz he has programmed the engine, and he possibly knows what it is
and oh, i searched for the text at the crash, and it said 0 results, i'm still not concluded with this

**Comment by FellowDesert** [comment]
> >


> > > > > bro, why shadow mario would make it? It looks like u are faking, he would never make this thing of crash joke to something that many people use yknow, it would cause some confusion or fight
> > > > > and about the dead pixels, or u made some shit at files, **or u made some overlay animation or smth to make fake dead pixels**, but well, if the dead pixels are not any of this, it may be technical issues, normal things from the monitor, not the engine i think
> > > > 
> > > > 
> > > > No, this hasn't happened because i did something weird to the build, because dead pixels appeared when i was playing Wednesday infidelity. https://user-images.githubusercontent.com/95321047/147170708-c1aea7e7-4442-45b3-ae5b-59c0a6c3f6ca.mp4
> > > 
> > > 
> > > bro but this crash i'm still suspecting, we'll need to talk with Shadow Mario if this is a feature, i'll mention him here @ShadowMario help here
> > 
> > 
> > https://drive.google.com/file/d/1qtKqoc63kQzBumwpO7nN711VYeXgLwDl/view?usp=sharing This is a .RAR file with 2 videos about the some of the glitches, you can contact me on discord here FellowDesert51#5850
> 
> i think it's better wait Shadow Mario, cuz he has programmed the engine, and he possibly knows what it is and oh, i searched for the text at the crash, and it said 0 results, i'm still not concluded with this

At the moment i think i'm just going to record more, if you are really thinking that i'm lying.

**Comment by HiroMizuki** [comment]
welp, i tested something better
i played the engine myself
i've got nothing of these

**Comment by HiroMizuki** [comment]
https://user-images.githubusercontent.com/72695242/147183623-df30c620-2abf-4615-b6ad-83936e3eb425.mp4

here's the video

**Comment by HiroMizuki** [comment]
> Friday.Night.Funkin._.Psych.Engine.2021-12-23.00-22-30.mp4 
> here's the video

and i'm sorry by quality lmao

**Comment by FellowDesert** [comment]
> > Friday.Night.Funkin._.Psych.Engine.2021-12-23.00-22-30.mp4
> > here's the video
> 
> and i'm sorry by quality lmao

Oook, i might discovered some things.
First of all, the popup messsage is a thing for the build, that it appears if you die.
(Buuut i still can't explain the dead pixels thing since it has been happened in other psych engine versions ¯\_(ツ)_/¯)
So.... sorry for making all this mess, i can live with dead pixels and lag, i was just concerned by the popup message

**Comment by ShadowMario** [comment]
Damn comedy man

**Comment by tposejank** [comment]
lmfao
