### ISSUE TITLE
How can I make one animation bigger than the other animations on a character?

### ISSUE THREAD

**Issue by FartMaster57** [ShadowMario/FNF-PsychEngine#2552]
### Describe your problem here.

No matter how I export my spritesheet, there's one sprite that is way smaller than the others. Is there a way I can make it appear larger in psych engine?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I've added a few custom characters

**Comment by CrusherMods** [comment]
use the scale in the character editor

**Comment by FartMaster57** [comment]
But that scales all the animations along with it, I wanna change the scale of one animation

**Comment by JustinSolstice** [comment]
Just make it bigger when you're making the spritesheet then

**Comment by Rorthgamer2XD** [comment]
Here a video of it showing how to make 1 big animation while the others are small
                                  [Tutorial.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/7773843/Tutorial.zip)
                                  Enjoy your thingy and take time to watch it
