### ISSUE TITLE
run a oppent animation with the custom note

### ISSUE THREAD

**Issue by Ahmedkiller1912** [ShadowMario/FNF-PsychEngine#2555]
### Describe your problem here.

i have tried to change custom character when i run a characterPlayAnim when the player hit the custom note but it didn't work when i tried to run it in bf it worked please help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by FartMaster57** [comment]
can you explain this in more detail?

**Comment by Ahmedkiller1912** [comment]
> 

when i use characterPlayAnim in any character it worked but when i use it in my custom character it doesn't worked

**Comment by Ahmedkiller1912** [comment]
do you want the code

**Comment by ShadowMario** [comment]
Then your character is missing the animation on the ,json file.

**Comment by Ahmedkiller1912** [comment]
No the json file works because i tested with event it worked but in characterPlayAnim it doesn't

**Comment by ShadowMario** [comment]
did you set character's specialAnim prop to true after playing the animation?? It gets really hard to do anything when you don't show any code.

`setProperty('boyfriend.specialAnim', true);`

**Comment by Ahmedkiller1912** [comment]
there is the code function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Bullet_Note' then --Check if the note on the chart is a Bullet Note
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'Bullet_Note'); --Change texture
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashHue', 0); --custom notesplash color, why not
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashSat', -20);
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashBrt', 1);

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', false); --Miss has penalties
			end
		end
	end
end

local shootAnims = {"LEFTshoot", "DOWNshoot", "UPshoot", "RIGHTshoot"}
function goodNoteHit(id, direction, noteType, isSustainNote)
	if noteType == 'Bullet_Note' then
		if difficulty == 2 then
			playSound('hankshoot', 0.5);
		end
		characterPlayAnim('dad', shootAnims[direction + 1], false);
		characterPlayAnim('boyfriend', 'dodge', true);
		setProperty('boyfriend.specialAnim', true);
		setProperty('dad.specialAnim', true);
		cameraShake('camGame', 0.01, 0.2)
    end
end

function noteMiss(id, direction, noteType, isSustainNote)
	if noteType == 'Bullet_Note' and difficulty == 2 then
		setProperty('health', -1);
		playSound('hankshoot', 0.5);
	elseif noteType == 'Bullet_Note' and difficulty == 1 then
		setProperty('health', getProperty('health')-0.8);
		runTimer('bleed', 0.2, 20);
		playSound('hankded', 0.6);
		characterPlayAnim('boyfriend', 'hurt', true);
	end
end

function onTimerCompleted(tag, loops, loopsLeft)
	-- A loop from a timer you called has been completed, value "tag" is it's tag
	-- loops = how many loops it will have done when it ends completely
	-- loopsLeft = how many are remaining
	if loopsLeft >= 1 then
		setProperty('health', getProperty('health')-0.001);
	end
end

**Comment by Ahmedkiller1912** [comment]
nevermind i fix it
