### ISSUE TITLE
Lua message box

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#2557]
### Describe your problem here.

how do i make it so that a message box shows mid-song?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by HiroMizuki** [comment]
like, the message that appears when game crashes?

**Comment by ShadowMario** [comment]
There's no way to do a panic handler/message box that looks like an error or something.
