### ISSUE TITLE
error trying to run with source code

### ISSUE THREAD

**Issue by Adriangamer1246** [ShadowMario/FNF-PsychEngine#2558]
### Describe your bug here.

everytime i try to run it, it says ccould not find haxelib "linc_luajit", does it need to be installed?

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\lol\Downloads\FNF-PsychEngine-0.5.1\FNF-PsychEngine-0.5.1> Could not find haxelib "linc_luajit", does it need to be installed?
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by CrusherNotDrip** [comment]
![image](https://user-images.githubusercontent.com/95889625/147172199-30331c21-9807-4de5-8b44-46d5a81c263c.jpeg)

**Comment by Adriangamer1246** [comment]
thanks
