### ISSUE TITLE
Please fix sustains, for the love of god

### ISSUE THREAD

**Issue by Rudyrue** [ShadowMario/FNF-PsychEngine#2559]
### Describe your bug here.

https://user-images.githubusercontent.com/73214127/147174110-528912a4-7dea-4b49-bb32-1aef2ea1ad20.mp4

Barely tried mashing on sustains/holds and I FC'ed a part. Shouldn't even be possible to FC while mashing, but apparently it is

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Didn't compile, used most recent build (atm 0.5.1)

**Comment by Rudyrue** [comment]
Forgot to mention that sustains also shouldn't give me like 5 misses for one hold.
Played High and missed 4 holds.
19 misses.

**Comment by tposejank** [comment]
bro thats a skill issue because you are mashing

**Comment by Rudyrue** [comment]
1. i can play ghost just fine, tf you on about lol
2. im mashing to show that the sustains are fucked

**Comment by HiroMizuki** [comment]
> 1. i can play ghost just fine, tf you on about lol
> 2. im mashing to show that the sustains are fucked

psych input is different from kade input, it's not the same thing bro

**Comment by Rudyrue** [comment]
when
did i ever say i was saying anything about kade

what are you on

**Comment by tposejank** [comment]
youre used to kade input, we can tell

**Comment by HiroMizuki** [comment]
> when did i ever say i was saying anything about kade
> 
> what are you on

i'm not talking about what u said, i'm saying that vs camellia was made at kade engine, and it gives another thing at input with sustain, so it will not be the same thing as the original vs camellia if u mash the sustains. Understood?

and Shadow Mario decides if he wants to make as kade or not, maybe he wants originality

**Comment by Rudyrue** [comment]
those sustains shouldn't even happen in the first place???

**Comment by MarkimusZer0** [comment]
I believe it the issue that Rudy is trying to show is the fact that the notes don't give you misses even if you spam

**Comment by MarkimusZer0** [comment]
The issue being that well that literally shouldn't happen, it does sometimes happen with Kade but it's fairly rare

**Comment by HiroMizuki** [comment]
> The issue being that well that literally shouldn't happen, it does sometimes happen with Kade but it's fairly rare

yeah true
but well, maybe Shadow Mario will decide it, or he'll just let the same thing so the input will not be almost the same as Kade one yknow

**Comment by MarkimusZer0** [comment]
Not saying that Psych should copy Kade's input in case any of you end up misunderstanding me, the issue here is that you shouldn't be able to just getting away with spamming when holding an LN (Long Note)

**Comment by HiroMizuki** [comment]
> Not saying that Psych should copy Kade's input in case any of you end up misunderstanding me, the issue here is that you shouldn't be able to just getting away with spamming when holding an LN (Long Note)

yeah yeah, i think i understand now lmao

**Comment by ShadowMario** [comment]
Nice mashing dumbo

**Comment by MarkimusZer0** [comment]
what's the issue with mashing on Long Notes to show the issue?
Long Notes are supposed to penalize you if you let go of them when you're supposed to hit them, his concerns seem pretty justified

**Comment by MarkimusZer0** [comment]
> Nice mashing dumbo

if what you mean is that Mashing making long notes will make them not punish you then that's an engine side issue, the antimash (or whatever tells the game that long notes have been unpressed) should be actively punishing the player for the mashing

**Comment by Rudyrue** [comment]
> Nice mashing dumbo

that's the point of the issue???
how can you not tell that your antimash is obviously fucked

**Comment by tposejank** [comment]
> > Nice mashing dumbo
> 
> that's the point of the issue???
> how can you not tell that your antimash is obviously fucked

he wants it like that, now stop crying about it

**Comment by MarkimusZer0** [comment]
> > > Nice mashing dumbo
> > 
> > 
> > that's the point of the issue???
> > how can you not tell that your antimash is obviously fucked
> 
> he wants it like that, now stop crying about it

So essentially you're saying he actually wants a broken antimash?

I don't think anyone would want that, unless you actually just want people to be able to spam to their heart's content to win a chart, like, we're on the same page here, right?
The antimash is clearly broken, it should be fixed or at least looked on
