### ISSUE TITLE
ModPack

### ISSUE THREAD

**Issue by SeriouslyAnimations** [ShadowMario/FNF-PsychEngine#2560]
### What is your question?

How do i use the mod packs? And why are they there

**Comment by Rudyrue** [comment]
what

**Comment by SeriouslyAnimations** [comment]
bruh

**Comment by SeriouslyAnimations** [comment]
read it again

**Comment by Keoiki** [comment]
What is this question even?
You put the mod packs in mods/ and toggle them ON in-game
as for your second question: Seriously?

**Comment by SeriouslyAnimations** [comment]
yeah but nothing really happens

**Comment by SeriouslyAnimations** [comment]
hello

**Comment by Reycko** [comment]
> yeah but nothing really happens

It literally enables the mods, is that nothing ?

**Comment by ShadowMario** [comment]
I lost an iq
