### ISSUE TITLE
loading screen with source

### ISSUE THREAD

**Issue by Adriangamer1246** [ShadowMario/FNF-PsychEngine#2567]
### What is your question?

how can i use the loading screen with source code?
like a video on how to it, cuz explaning without a video is pretty hard to understand

**Comment by HiroMizuki** [comment]
#1441

**Comment by Adriangamer1246** [comment]
i have seen that

**Comment by Adriangamer1246** [comment]
but i dont know wich no_preload_all to delete

**Comment by HiroMizuki** [comment]
u need to delete all of them

**Comment by HiroMizuki** [comment]
at LoadingState.hx

**Comment by trayfellow** [comment]
while the loading screen is used for html5 only cause it needs to download the assets and shit on demand, i think they should make it appear on desktop too just cause it looks cool lol

**Comment by Adriangamer1246** [comment]
> u need to delete all of them


so just the word?

**Comment by HiroMizuki** [comment]
> while the loading screen is used for html5 only cause it needs to download the assets and shit on demand, i think they should make it appear on desktop too just cause it looks cool lol

welp, i think not, cuz is just a little thingie
but it is easy to make

**Comment by HiroMizuki** [comment]
> > u need to delete all of them
> 
> so just the word?

well, i recommend to delete the whole line that contains the #if_NO_PRELOAD_ALL

**Comment by Adriangamer1246** [comment]
k

**Comment by Adriangamer1246** [comment]
and if it does word what #end line do i need to delete?

**Comment by HiroMizuki** [comment]
> and if it does word what #end line do i need to delete?

yes
