### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Thepipisman** [ShadowMario/FNF-PsychEngine#2569]
### Describe your bug here.

If you click paste section in the chart editor, (if nothing has been copied) the game fucking shits itself 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by HiroMizuki** [comment]
it happens cuz there's literally nothing at clipboard and the game tries to pick a null object reference, maybe Shadow Mario will see about it futurely
