### ISSUE TITLE
FNF Dialogue not loading in a song

### ISSUE THREAD

**Issue by YukiRoboGaming** [ShadowMario/FNF-PsychEngine#2579]
### What is your question?

when I try to play dialogue, for my mod in a week, the dialogue does not load in and it skips to the song, can i receive a answer for this?

**Comment by spaceshuttle03** [comment]
Do you have a script that activates the dialogue?

**Comment by YukiRoboGaming** [comment]
> Do you have a script that activates the dialogue? (In the source code or a script.lua)

i have install the script that i forgot to place, thanks for asking about the scripts since im new to modding
