### ISSUE TITLE
Lives System on LUA

### ISSUE THREAD

**Issue by Reycko** [ShadowMario/FNF-PsychEngine#2583]
### Describe your problem here.

code:
```
function onUpdate(elapsed)

local lives = 3
local health = getProperty('health')
if health < 0.002 and lives > 0 then
	playSound('secretSound', 1)
	setProperty('health', 1)
	lives = lives - 1
	debugPrint(lives)
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No edits, only the bancuz mod

**Comment by Starmapo** [comment]
The "lives" variable is being created inside the function, so it will just be discarded and reset back to 3 every time its done. Move the `local lives = 3` outside, before the function code.
Also i'm not sure if you just didn't give the whole code, but you have to have 2 `end`s closing the expressions, one for
`if health < 0.002 and lives > 0 then`
and one for `function onUpdate(elapsed)`

**Comment by Reycko** [comment]
> The "lives" variable is being created inside the function, so it will just be discarded and reset back to 3 every time its done. Move the `local lives = 3` outside, before the function code. Also i'm not sure if you just didn't give the whole code, but you have to have 2 `end`s closing the expressions, one for `if health < 0.002 and lives > 0 then` and one for `function onUpdate(elapsed)`

There is 1 one because i just put the lives system and not the full script because it has note tweens & health drain stuff

**Comment by Reycko** [comment]
and it's not working.

**Comment by Reycko** [comment]
Full code (with the fix you said):
[modchart.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7769440/modchart.txt)
(note: it's a .lua file, not a .txt file, github dosent accept lua stuff)

**Comment by Starmapo** [comment]
[script.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7769627/script.txt)
Everything should be fixed. Also remember song modcharts must be named "script.lua".

**Comment by Reycko** [comment]
> [script.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7769627/script.txt) Everything should be fixed. Also remember song modcharts must be named "script.lua".

you can name then whatever you want, as long it's a lua file extension
