### ISSUE TITLE
Back button in difficulty select doesnt work

### ISSUE THREAD

**Issue by DumbAccountThing** [ShadowMario/FNF-PsychEngine#2586]
### Describe your bug here.

The back button in version 0.5.1's difficulty select will try to load a null difficulty instead of go back to the pause menu
![image](https://user-images.githubusercontent.com/89667422/147250478-a1c68a1a-de7c-4925-bf9a-64755178f845.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by DumbAccountThing** [comment]
also wanted to point out another thing, adding a [songname]-null.json to the songs data folder will make it load that instead
trick your friends while you can

**Comment by DumbAccountThing** [comment]
update: apparently source has fixed this lol

**Comment by ShadowMario** [comment]
Duplicate
