### ISSUE TITLE
How to move the arrows to the bottom via Lua script?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#2587]
### What is your question?

How to move the arrows to the bottom and move the bar to the top via Lua script?
![Snipaste_2021-12-23_22-51-50](https://user-images.githubusercontent.com/13177997/147256887-b06dab7b-6a7d-4ea9-bf1e-2b88d446606b.png)

**Comment by dum-du-m** [comment]
it's downscroll.
		setPropertyFromClass('ClientPrefs', 'downScroll', true)
but if you want to use it, you shoud probably keep a check to make it so it doesn't stay like this after the song is done
