### ISSUE TITLE
Crashing when using any Event

### ISSUE THREAD

**Issue by LukasRainbow** [ShadowMario/FNF-PsychEngine#2588]
### Describe your bug here.

If you go to the Debug Menu and try to make an Event, it works just fine. However, if you restart the game, when you try to enter literally anything in one of the Values, the Game just crashes. When trying it again, it works just fine as if nothing has ever happened.

This happenes weather you're using a previously used event or when you choose one you haven't touched in months. All that matters, when the Game gets closed and doesn't open in a while or something, the Game thinks "Aye so you remember how we should prevent me from crashing when we write something in that Value there? Yea forget that."
It doesn't really matter if i mod certain files or just mess with the game. It just does that.

### Are you modding a build from source or with Lua?

Source (Technically also Lua since i'm using a Custom Event with it)

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i just added regular Files to the Game. All other Files haven't been thouched.

**Comment by ShadowMario** [comment]
Couldn't replicate this bug.

**Comment by LukasRainbow** [comment]
Wait, wait what? I'll get footage of it.

**Comment by LukasRainbow** [comment]
Ok fine you win
