### ISSUE TITLE
How to change characters via lua script?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#2589]
### What is your question?

During playing  the game, I want to change bf when I press key "p", and change dad when I press key "o".How to do it via lua script?

**Comment by ShadowMario** [comment]
triggerEvent function
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#triggereventnamestring-arg1string-arg2string
