### ISSUE TITLE
How do i make it so when i press 7 it restarts my computer?

### ISSUE THREAD

**Issue by juanroman74454811** [ShadowMario/FNF-PsychEngine#2591]
### Describe your problem here.

I wanna make it in Unfairness 2.1/2.5 beta style so like if you press 7 in a unfair song it restarts your PC

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by PDL2CGamejolt** [comment]
Correction: Unfairness 2.1/2.5 beta style, and technically if you do this the mod you will make will become a virus.

**Comment by juanroman74454811** [comment]
gamejolt is down too

**Comment by ByronisJoan** [comment]
Do you want a Virus then?

**Comment by juanroman74454811** [comment]
yeah

**Comment by juanroman74454811** [comment]
i want one

**Comment by PDL2CGamejolt** [comment]
NO! I DONT WANT A VIRAL MOD

**Comment by juanroman74454811** [comment]
yes

**Comment by juanroman74454811** [comment]
![die tanenr](https://user-images.githubusercontent.com/92176733/147415844-29294bdd-358a-4b0b-9e6f-013b6463d3d9.jpg)
my meme was this lol

**Comment by PDL2CGamejolt** [comment]
> NO! I DONT WANT A VIRAL MOD

Me almost a year later: Makes a song “Universe Breaker” over exaggerated

**Comment by PDL2CGamejolt** [comment]
Also I meant “Viral” as in “Virus”

**Comment by PDL2CGamejolt** [comment]
Me a year later: Trying to make a script which restarts your computer upon pressing 7.

**Comment by juanroman74454811** [comment]
> Me a year later: Trying to make a script which restarts your computer upon pressing 7.

*insert summoning music*
WWWHHHOOO DDDAAARRREEE SSSUUUMMMOOONNN MMMEEE!!!

**Comment by PDL2CGamejolt** [comment]
Well, that was strange. This was an old issue that has been long since closed.
