### ISSUE TITLE
(CRITICAL BUG) the Custom note type Left Held Note with texture Crashing the game 

### ISSUE THREAD

**Issue by RealReal334** [ShadowMario/FNF-PsychEngine#2592]
### Describe your bug here.

Whenever Enemy finished Hitting Left Held note 
with Changed Texture it crashed the game
the others 3 note works fine

VIDEO
https://streamable.com/5c6012

Things before asking
1. no the problem isn't with xml
https://imgur.com/hBFiOF1
2. no the problem isn't with png
https://imgur.com/Vuw4aCV
3. no the problem isn't with the directory
https://imgur.com/uGpanUb
4. no the problem isn't with the Code

```
function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is a Bullet Note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Haato Note' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'LUAcharacters/notes/NOTE_haato'); -- Change texture
			setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true); -- Custom Sprite will only play animation
			
			
			
		end
	end
	--debugPrint('Script started!')	
	
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I didn't editted the source file

**Comment by RealReal334** [comment]
Dang it i Knew the Problem it's not mine but the Original Note_assets Xml and Sources
Still Needed to fix tho

![image](https://user-images.githubusercontent.com/84943693/147275769-79a47fce-ee44-4bb8-aebc-4045a864a26b.png)


change pruple end hold to purple end hold

pls fix Cus it's Very Stupid

**Comment by ShadowMario** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/44785097/147294921-1c8e9429-cb33-4e65-83f6-40915dd8ec92.png)
