### ISSUE TITLE
anti-mash

### ISSUE THREAD

**Issue by Beginner-codi** [ShadowMario/FNF-PsychEngine#2593]
### What feature do you want to get added on the base engine?

im not a bad rhythm gamer, but i genuinely request you to make anti-mash togglable, thanks.

**Comment by Gui-iago** [comment]
just go to Options, then Gameplay, then Disablr Ghost Tapping

**Comment by tposejank** [comment]
> just go to Options, then Gameplay, then Disablr Ghost Tapping

That makes it so that when there is no note to hit, you miss.
Antimash is hardcoded.
