### ISSUE TITLE
0.5.2 ideas

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#2594]
### What feature do you want to get added on the base engine?

Animated Icons
Ability to add Panic Handlers mid-song
Soft-coded Achievements and Ratings
Song Maker like Modding Plus.
Mic'd up Difficulties (Noob, Expert, Insane)
Ability to Move Windows like in Strident Crisis
Ability to change the Text Fonts
New Notes: Warning Note, Instakill Note, Slow Scroll Speed Note, Fast Scroll Speed Note
Optional Danger Icons (Not winning icons)
Ability to change note asset looks (Like in Kade Engine 1.8)
Ability to add new judgements
New Options: Sidescroll, Play on opponents side.

**Comment by DatGamerYoloYT** [comment]
"Mic'd up Difficulties (Noob, Expert, Insane)"
this is really easy to do and you don't need to ask shadowmario to add it into the engine.

here is the code: "difficulties": "Noob, Easy, Normal, Hard, Expert, Insane"

"Optional Danger Icons (Not winning icons)"
do you mean icons that have the same image for the defeat version?
you can just copy-paste the normal icon over to the danger icon's space.

**Comment by SrtHero278** [comment]
"Ability to change the Text Fonts"
**_YOU CAN ALREADY DO THAT._**
![image](https://user-images.githubusercontent.com/93018286/147282027-4ee2e7dd-9b40-4d8a-892d-e6af71e6a636.png)

**Comment by tposejank** [comment]
Ability to add Panic Handlers mid-song
- What?

Soft-coded Achievements and Ratings
- I might help on Achievements, but Ratings are not neccesary.

Song Maker like Modding Plus.
- You expect FNF to be a DAW?

Mic'd up Difficulties (Noob, Expert, Insane)
- It's in the week maker.

Ability to Move Windows like in Strident Crisis
- It is possible, even in lua.

Ability to change the Text Fonts
- It is possible.

New Notes: Warning Note, Instakill Note, Slow Scroll Speed Note, Fast Scroll Speed Note
Make them yourself. Fast Scroll Speed isn't possible.

Optional Danger Icons (Not winning icons)
- No.

Ability to change note asset looks (Like in Kade Engine 1.8)
- You can change them on the chart editor.

Ability to add new judgements
- No.

New Options: Sidescroll, Play on opponents side.
- This needs a lot of work to get it done.

I don't feel like anything you said is important

**Comment by PDL2CGamejolt** [comment]
> "Ability to change the Text Fonts" **_YOU CAN ALREADY DO THAT._** ![image](https://user-images.githubusercontent.com/93018286/147282027-4ee2e7dd-9b40-4d8a-892d-e6af71e6a636.png)

how

**Comment by PDL2CGamejolt** [comment]
> Ability to add Panic Handlers mid-song
> 
> * What?
> 
> Soft-coded Achievements and Ratings
> 
> * I might help on Achievements, but Ratings are not neccesary.
> 
> Song Maker like Modding Plus.
> 
> * You expect FNF to be a DAW?
> 
> Mic'd up Difficulties (Noob, Expert, Insane)
> 
> * It's in the week maker.
> 
> Ability to Move Windows like in Strident Crisis
> 
> * It is possible, even in lua.
> 
> Ability to change the Text Fonts
> 
> * It is possible.
> 
> New Notes: Warning Note, Instakill Note, Slow Scroll Speed Note, Fast Scroll Speed Note Make them yourself. Fast Scroll Speed isn't possible.
> 
> Optional Danger Icons (Not winning icons)
> 
> * No.
> 
> Ability to change note asset looks (Like in Kade Engine 1.8)
> 
> * You can change them on the chart editor.
> 
> Ability to add new judgements
> 
> * No.
> 
> New Options: Sidescroll, Play on opponents side.
> 
> * This needs a lot of work to get it done.
> 
> I don't feel like anything you said is important

how do i make the windows move like in strident crisis then

**Comment by DatGamerYoloYT** [comment]
step 1. learn lua
step 2. share your lua file

**Comment by PDL2CGamejolt** [comment]
and i mean softcoded ability

**Comment by PDL2CGamejolt** [comment]
ok

**Comment by PDL2CGamejolt** [comment]
> step 1. learn lua step 2. share your lua file

how

**Comment by tposejank** [comment]
we wont help you then

**Comment by PDL2CGamejolt** [comment]
tposejank! i found out how to make the fast and slow speed notes! "it isnt possible" it is now!
[](https://drive.google.com/file/d/16IIilYKiLoEHDhKiCz5RpZt4b9iE5UwD/view?usp=sharing)

**Comment by SrtHero278** [comment]
> > "Ability to change the Text Fonts" **_YOU CAN ALREADY DO THAT._** ![image](https://user-images.githubusercontent.com/93018286/147282027-4ee2e7dd-9b40-4d8a-892d-e6af71e6a636.png)
> 
> how

I LITERALLY SHOWED YOU HOW.

**Comment by tposejank** [comment]
> tposejank! i found out how to make the fast and slow speed notes! "it isnt possible" it is now!
> 
> [Press here to see this video](https://drive.google.com/file/d/16IIilYKiLoEHDhKiCz5RpZt4b9iE5UwD/view?usp=sharing)

the notes are literally st the same speed

**Comment by SonicProYT** [comment]
Animated Icons | Source code.
Ability to add Panic Handlers mid-song | I don't think that's possible
Soft-coded Achievements and Ratings | It exists now.
Song Maker like Modding Plus. | You can just get to the chart editor to make one.
Mic'd up Difficulties (Noob, Expert, Insane) | You can make these diffiiculties with or without source code .
Ability to Move Windows like in Strident Crisis | There is an event of it.
Ability to change the Text Fonts | Already exists.
New Notes: Warning Note, Instakill Note, Slow Scroll Speed Note, Fast Scroll Speed Note | Instakil Note is the example event script.
Optional Danger Icons (Not winning icons) | Lua.
Ability to change note asset looks (Like in Kade Engine 1.8) | You can just replace the note assets and badaboom, note asset look has be changed.
Ability to add new judgements | Barely Possible.

**Comment by ImaginationSuperHero528** [comment]
> Animated Icons | Source code. Ability to add Panic Handlers mid-song | I don't think that's possible Soft-coded Achievements and Ratings | It exists now. Song Maker like Modding Plus. | You can just get to the chart editor to make one. Mic'd up Difficulties (Noob, Expert, Insane) | You can make these diffiiculties with or without source code . Ability to Move Windows like in Strident Crisis | There is an event of it. Ability to change the Text Fonts | Already exists. New Notes: Warning Note, Instakill Note, Slow Scroll Speed Note, Fast Scroll Speed Note | Instakil Note is the example event script. Optional Danger Icons (Not winning icons) | Lua. Ability to change note asset looks (Like in Kade Engine 1.8) | You can just replace the note assets and badaboom, note asset look has be changed. Ability to add new judgements | Barely Possible.

Where's the event to move the window?

**Comment by Cristobal653** [comment]
> Animated Icons | Source code. Ability to add Panic Handlers mid-song | I don't think that's possible Soft-coded Achievements and Ratings | It exists now. Song Maker like Modding Plus. | You can just get to the chart editor to make one. Mic'd up Difficulties (Noob, Expert, Insane) | You can make these diffiiculties with or without source code . Ability to Move Windows like in Strident Crisis | There is an event of it. Ability to change the Text Fonts | Already exists. New Notes: Warning Note, Instakill Note, Slow Scroll Speed Note, Fast Scroll Speed Note | Instakil Note is the example event script. Optional Danger Icons (Not winning icons) | Lua. Ability to change note asset looks (Like in Kade Engine 1.8) | You can just replace the note assets and badaboom, note asset look has be changed. Ability to add new judgements | Barely Possible.

That already exists in Delirium. Look in the script file.

**Comment by PDL2CGamejolt** [comment]
> > tposejank! i found out how to make the fast and slow speed notes! "it isnt possible" it is now!
> > [Press here to see this video](https://drive.google.com/file/d/16IIilYKiLoEHDhKiCz5RpZt4b9iE5UwD/view?usp=sharing)
> 
> the notes are literally st the same speed

Are you blind

**Comment by PDL2CGamejolt** [comment]
> 

?
