### ISSUE TITLE
note skins for a specific character

### ISSUE THREAD

**Issue by EddyEddyEd** [ShadowMario/FNF-PsychEngine#2606]
### What is your question?

I wanna know how to do note skins for specific characters just like in bob and bosip :)

**Comment by bangthe1st** [comment]
so first off you need your note assets,

 rename it or else the note skin finder would have trouble finding it and would classify it as the normal note skin,
 
  then type your note asset's name in the Note Texture thing in the chart editor, and ur done!

**Comment by tposejank** [comment]
`
function onCreate()
for i=0,3 do
setPropertyFromGroup('opponentStrums', i, 'texture', 'yourimage')
end
end
`

**Comment by EddyEddyEd** [comment]
> so first off you need your note assets,
> 
> rename it or else the note skin finder would have trouble finding it and would classify it as the normal note skin,
> 
> then type your note asset's name in the Note Texture thing in the chart editor, and ur done!

ye that doesnt work for only one character but thanks for commenting :)

**Comment by EddyEddyEd** [comment]
> `function onCreate() for i=0,3 do setPropertyFromGroup('opponentStrums', i, 'texture', 'yourimage') end end`

sooooo, i gotta use that on a lua file right? If so, do u know how to "stack functions" in only one lua script?

**Comment by Templarfreak** [comment]
> sooooo, i gotta use that on a lua file right? If so, do u know how to "stack functions" in only one lua script?

it would make the most sense if you added this in a _character_ Lua Script, which you can do by making a lua script file in the same folder and with the same name as the character json file.

if you want to segment the `onCreate` function into more easily-readable chunks, you can put things in their own function and then call them in `onCreate` like:

```
function my_func()
... function code here ...
end

...

function onCreate()
... stuff ...
myfunc()
... more stuff ...
end```

**Comment by Grape-Boy** [comment]
> you'll want to use either `require` or `loadfile` or `dofile` or whatever.

The module needs to be in a folder called "lua" inside `PsychEngine/`, where PsychEngine.exe is located, or `bin/`, if you compiled it yourself.

**Comment by EddyEddyEd** [comment]
> it would make the most sense if you added this in a _character_ Lua Script, which you can do by making a lua script file in the same folder and with the same name as the character json file.

> it would make the most sense if you added this in a _character_ Lua Script, which you can do by making a lua script file in the same folder and with the same name as the character json file.

so, I did it but something is off because it chashes every time I try loading the song 
![Desktop Screenshot 2022 01 06 - 11 15 31 27](https://user-images.githubusercontent.com/94937926/148396424-10775bb5-5ffb-4a2d-bec5-f58016ad1d7c.png)
I probably did something that I just cant tell because I suck at any form of coding
