### ISSUE TITLE
0.5.2 Suggestions

### ISSUE THREAD

**Issue by RiloTheFox** [ShadowMario/FNF-PsychEngine#2608]
### What feature do you want to get added on the base engine?

- A Settings Option where you can change the Maximum size of the icons when they zoom in, change the speed of the icons, or change the icon's offset for the zooming in
- Mic'd Up's Settings such as: Hue, Brightness, Gamma, Filters, Hitsounds (Can be customized to use a custom Hitsound)
- New Modifier for the Song Modifier Menu: Song Speed (Will adjust the speed and pitch of the song)

**Comment by tposejank** [comment]
1. No
2. Filters exist for your notes, and hitsounds you can literally make them with lua
3. No
