### ISSUE TITLE
mod folder storymod bug

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#2614]
### Describe your bug here.

when i hide weeks, and place the file in the mod folder, it still shows the week in storymode. but only if it has the same name as the current offical weeks.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
Where did you save your weeks?

**Comment by crispyboi24** [comment]
> Where did you save your weeks?
Mods/weeks. I replaced week 5 and 6 with versions where they are hidden from storymode and freeplay. But they still appear on both

**Comment by crispyboi24** [comment]
> Where did you save your weeks?

Mods/weeks. I replaced week 5 and 6 with versions where they are hidden from storymode and freeplay. But they still appear on both
