### ISSUE TITLE
Moving Objects/Characters

### ISSUE THREAD

**Issue by bestuff44** [ShadowMario/FNF-PsychEngine#2615]
### What is your question?

I meant, like, moving constantly, as if they were walking. Sorry, I don't really know how to code

**Comment by Templarfreak** [comment]
`setCharacterX/Y`
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#setcharacterxtypestring

honestly, depending on how complex you want the scene to be, you're probably better off animating it externally, converting the animation to MP4, and then playing it
