### ISSUE TITLE
Short Hold Notes 

### ISSUE THREAD

**Issue by Fluffmpie** [ShadowMario/FNF-PsychEngine#2616]
### Describe your bug here.

When making short hold notes in the chart editor, ones where it's just a simple E press, when the song is actually played, the notes display as normal notes, no hold notes, as shown in the video below (no audio is intentional) 

https://user-images.githubusercontent.com/96599581/147298665-2c94ff9e-38b0-4097-b78c-c3613226c87c.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Templarfreak** [comment]
the sustain length that matches with 1 16th varies from BPM to BPM and making the sustain length 1 longer always makes the sustain visible, but that's about the full extent of my understanding of this bug.

**Comment by Fluffmpie** [comment]
I got a solution to it for now until it's fixed, here

https://user-images.githubusercontent.com/96599581/147372554-df65428c-9efb-49b3-8bcd-f8bbb27b67eb.mp4

**Comment by Templarfreak** [comment]
keep in mind if your have a note that is approximately exactly 1 16th away from these short sustain notes, then _technically_ by making the sustain length 1 longer makes the sustain and that note are just barely overlapping. i have never been able to feel this myself personally when i do this, but its just something to keep in mind.
