### ISSUE TITLE
Freeplay Text Highlight

### ISSUE THREAD

**Issue by Gui-iago** [ShadowMario/FNF-PsychEngine#2621]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/45212377/147302086-77fa9232-8e6c-4874-b76c-188fc70cab7b.png)
(Screenshot by nintendofan44 on https://github.com/ShadowMario/FNF-PsychEngine/pull/386)

sorry if I'm posting on the wrong section of the github, how do I make this change on the Freeplay Menu?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

**Comment by ArezalGame89** [comment]
Ask the guy who made that, I'm even looking too
