### ISSUE TITLE
Dialog before and after a song

### ISSUE THREAD

**Issue by keanu64github** [ShadowMario/FNF-PsychEngine#2622]
### What is your question?

I already used the lua script for the beginning dialog, i cant figure out how to also add some at the end. Plz help

**Comment by ShadowMario** [comment]
Copy the script, then open the copied script, rename `onStartCountdown` to `onEndSong` and remove `not seenCutscene` from the script.

**Comment by keanu64github** [comment]
That did add an end dialog, but it loops after the end dialog.

**Comment by keanu64github** [comment]
That did add an end dialog, but it loops after the end dialog.

**Comment by keanu64github** [comment]
That did add an end dialog, but it loops after the end dialog.

**Comment by keanu64github** [comment]
Sorry for the spam my internet sent multiple requests
