### ISSUE TITLE
Video cutscenes do not work and dialogue has issues on MacOS

### ISSUE THREAD

**Issue by ItzGreenForever** [ShadowMario/FNF-PsychEngine#2626]
### Describe your bug here.

When trying to load a mod on MacOS that has video cutscenes, the game crashes. It seems it's only a problem with cutscenes and not dialogue. However, when playing a song that has dialogue, the song starts while the dialogue is still going and when the dialogue has ended it's impossible to control the game without restarting and the instrumental just disappears.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not edit anything in the build.

**Comment by tposejank** [comment]
1. macos doesnt support cutscenes
2. you messed up your dialogue

**Comment by SonicProYT** [comment]
thats because macOS cant handle cutscenes

**Comment by ShadowMario** [comment]
MacOS is not currently supported as i don't own/plan to own a Mac machine and i don't have enough space on my PC for a Mac VM.
About your dialogue issue, that's not the engine's fault, [follow the instructions on the Wiki.](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Dialogues)
