### ISSUE TITLE
Charting Broke

### ISSUE THREAD

**Issue by Cacx101** [ShadowMario/FNF-PsychEngine#263]
Currently using the latest version of Psych Engine, tried to import a chart over tutorial and while it reads the chart just fine, the notes are completely broken in the editor. Important to note, I charted the song in Arrow Vortex, used Kade Engine to convert to .json, and fixed a few issues there, where I then brought it into Psych Engine. Was it the path I took, or is there something actually wrong with the Editor?

**Comment by ShadowMario** [comment]
Looks like a badly ported chart from another engine with issues
