### ISSUE TITLE
how do i use the mod menu?

### ISSUE THREAD

**Issue by travisgamemaker** [ShadowMario/FNF-PsychEngine#2630]
### What is your question?

when i open the mod menu it gives me an error
[file_open,modsList.txt]
is there anything that i have to put in modsList.txt to get it to work?

**Comment by Reycko** [comment]
Close any programs with modsList.txt open / edited.

**Comment by travisgamemaker** [comment]
problem still occurs

https://user-images.githubusercontent.com/81720456/147419266-df1da223-f2ea-4855-a178-308e9393e148.mp4

**Comment by travisgamemaker** [comment]
it was avast. just add your psych engine folder as an exception if you have the same issue.
