### ISSUE TITLE
Background These Nuts

### ISSUE THREAD

**Issue by Rorthgamer2XD** [ShadowMario/FNF-PsychEngine#2639]
### Describe your problem here.

So i was have background trouble and i didn't know what i didn't wrong it just say null
![stages](https://user-images.githubusercontent.com/86710598/147343636-a0f4b6ac-fc8b-413d-a878-be3fdb48fd42.png)
![images](https://user-images.githubusercontent.com/86710598/147343643-9640eda7-07c6-4d61-81bf-f8a13a761fa0.png)
![null](https://user-images.githubusercontent.com/86710598/147343645-fd848ca5-3461-4af1-8532-6a508295f21b.png)
Please Help me i need solutions

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I Added new Difficulty , New Song ,New Character ,New Week while they were working.the background didn't work

**Comment by Reycko** [comment]
Try this:

```

function onCreate()
	-- background shit
	makeLuaSprite('littlehomeworld', 'littlehomeworld', -600, -300);
	setScrollFactor('littlehomeworld', 0.9, 0.9);


	addLuaSprite('littlehomeworld', false);

	
	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end

```

**Comment by Reycko** [comment]
Replace the LUA file.

**Comment by Rorthgamer2XD** [comment]
> Replace the LUA file by this.

It's working but it's turn to a just black background what do i do?

**Comment by ShadowMario** [comment]
the background might be there but offscreen.
