### ISSUE TITLE
Moving Window in LUA ?

### ISSUE THREAD

**Issue by Reycko** [ShadowMario/FNF-PsychEngine#2641]
### Describe your problem here.

Is there a way to move the game window in LUA ? Kade Engine does that I think but it may be different on Psych ?
If you know how, Please send the "command".

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by KevinKuntz255** [comment]
https://twitter.com/bbsub3/status/1474232824442109955?t=rxHP8-YZDcev-SIS1qAQew&s=09
