### ISSUE TITLE
custom character bug

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#2652]
### Describe your bug here.

Whenever i make a custom character, it turns into just a file

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

....

**Comment by crispyboi24** [comment]
T-that’s whats supposed to happen? What?

**Comment by PDL2CGamejolt** [comment]
it turns into just a file, not a json file, just a file

**Comment by CrusherMods** [comment]
> it turns into just a file, not a json file, just a file

Rename it and put .json at the end

**Comment by PDL2CGamejolt** [comment]
kk
