### ISSUE TITLE
ok so my character is just the no texture cube

### ISSUE THREAD

**Issue by EnderPurrson** [ShadowMario/FNF-PsychEngine#2653]
### Describe your problem here.

ok so when i go to my character in the character editor he is just the textureless cub
![nega_assets](https://user-images.githubusercontent.com/96633985/147370542-4175432c-190e-4ab2-93b8-0ea75958e1e4.png)

btw i used daddy dearest as a template. that might be the issue. 
XML:
?xml version="1.0" encoding="utf-8"?>
<TextureAtlas imagePath="negaDY_DEAREST.png">
	
	
	<SubTexture name="nega Sing Note DOWN0000" x="5" y="5" width="470" height="730" frameX="0" frameY="-5" frameWidth="470" frameHeight="735"/>
	<SubTexture name="nega Sing Note DOWN0001" x="5" y="5" width="470" height="730" frameX="0" frameY="-5" frameWidth="470" frameHeight="735"/>
	<SubTexture name="nega Sing Note DOWN0002" x="480" y="5" width="463" height="735" frameX="-3" frameY="0" frameWidth="470" frameHeight="735"/>
	<SubTexture name="nega Sing Note DOWN0003" x="480" y="5" width="463" height="735" frameX="-3" frameY="0" frameWidth="470" frameHeight="735"/>
	<SubTexture name="nega Sing Note DOWN0004" x="480" y="5" width="463" height="735" frameX="-3" frameY="0" frameWidth="470" frameHeight="735"/>
	<SubTexture name="nega Sing Note DOWN0005" x="480" y="5" width="463" height="735" frameX="-3" frameY="0" frameWidth="470" frameHeight="735"/>
	<SubTexture name="nega Sing Note DOWN0006" x="480" y="5" width="463" height="735" frameX="-3" frameY="0" frameWidth="470" frameHeight="735"/>
	<SubTexture name="nega Sing Note DOWN0007" x="480" y="5" width="463" height="735" frameX="-3" frameY="0" frameWidth="470" frameHeight="735"/>
	<SubTexture name="nega Sing Note DOWN0008" x="480" y="5" width="463" height="735" frameX="-3" frameY="0" frameWidth="470" frameHeight="735"/>
	<SubTexture name="nega Sing Note DOWN0009" x="480" y="5" width="463" height="735" frameX="-3" frameY="0" frameWidth="470" frameHeight="735"/>
	<SubTexture name="nega Sing Note DOWN0010" x="480" y="5" width="463" height="735" frameX="-3" frameY="0" frameWidth="470" frameHeight="735"/>
	<SubTexture name="nega Sing Note DOWN0011" x="480" y="5" width="463" height="735" frameX="-3" frameY="0" frameWidth="470" frameHeight="735"/>
	<SubTexture name="nega Sing Note DOWN0012" x="480" y="5" width="463" height="735" frameX="-3" frameY="0" frameWidth="470" frameHeight="735"/>
	<SubTexture name="nega Sing Note DOWN0013" x="480" y="5" width="463" height="735" frameX="-3" frameY="0" frameWidth="470" frameHeight="735"/>
	<SubTexture name="nega Sing Note DOWN0014" x="480" y="5" width="463" height="735" frameX="-3" frameY="0" frameWidth="470" frameHeight="735"/>
	<SubTexture name="nega Sing Note DOWN0015" x="480" y="5" width="463" height="735" frameX="-3" frameY="0" frameWidth="470" frameHeight="735"/>
	<SubTexture name="nega Sing Note LEFT0000" x="948" y="5" width="371" height="777" frameX="0" frameY="0" frameWidth="383" frameHeight="777"/>
	<SubTexture name="nega Sing Note LEFT0001" x="948" y="5" width="371" height="777" frameX="0" frameY="0" frameWidth="383" frameHeight="777"/>
	<SubTexture name="nega Sing Note LEFT0002" x="1324" y="5" width="383" height="777"/>
	<SubTexture name="nega Sing Note LEFT0003" x="1324" y="5" width="383" height="777"/>
	<SubTexture name="nega Sing Note LEFT0004" x="1712" y="5" width="383" height="777"/>
	<SubTexture name="nega Sing Note LEFT0005" x="1712" y="5" width="383" height="777"/>
	<SubTexture name="nega Sing Note LEFT0006" x="1324" y="5" width="383" height="777"/>
	<SubTexture name="nega Sing Note LEFT0007" x="1324" y="5" width="383" height="777"/>
	<SubTexture name="nega Sing Note LEFT0008" x="1712" y="5" width="383" height="777"/>
	<SubTexture name="nega Sing Note LEFT0009" x="1712" y="5" width="383" height="777"/>
	<SubTexture name="nega Sing Note LEFT0010" x="1324" y="5" width="383" height="777"/>
	<SubTexture name="nega Sing Note LEFT0011" x="1324" y="5" width="383" height="777"/>
	<SubTexture name="nega Sing Note LEFT0012" x="1712" y="5" width="383" height="777"/>
	<SubTexture name="nega Sing Note LEFT0013" x="1712" y="5" width="383" height="777"/>
	<SubTexture name="nega Sing Note LEFT0014" x="1324" y="5" width="383" height="777"/>
	<SubTexture name="nega Sing Note LEFT0015" x="1324" y="5" width="383" height="777"/>
	<SubTexture name="nega Sing Note RIGHT0000" x="2100" y="5" width="465" height="792" frameX="0" frameY="-1" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0001" x="2100" y="5" width="465" height="792" frameX="0" frameY="-1" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0002" x="2570" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0003" x="2570" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0004" x="3027" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0005" x="3027" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0006" x="2570" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0007" x="2570" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0008" x="3027" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0009" x="3027" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0010" x="2570" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0011" x="2570" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0012" x="3027" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0013" x="3027" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0014" x="2570" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0015" x="2570" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0016" x="3027" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0017" x="3027" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note RIGHT0018" x="2570" y="5" width="452" height="793" frameX="0" frameY="0" frameWidth="465" frameHeight="793"/>
	<SubTexture name="nega Sing Note UP0000" x="3484" y="5" width="408" height="818" frameX="-1" frameY="0" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0001" x="3484" y="5" width="408" height="818" frameX="-1" frameY="0" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0002" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0003" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0004" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0005" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0006" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0007" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0008" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0009" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0010" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0011" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0012" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0013" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0014" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0015" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0016" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0017" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0018" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0019" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0020" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0021" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0022" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0023" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0024" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0025" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0026" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0027" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0028" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0029" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0030" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0031" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0032" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0033" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0034" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0035" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0036" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0037" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0038" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0039" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0040" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0041" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0042" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0043" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0044" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0045" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0046" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0047" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0048" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0049" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0050" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0051" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0052" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0053" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0054" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0055" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0056" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0057" x="418" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0058" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega Sing Note UP0059" x="5" y="828" width="408" height="809" frameX="0" frameY="-8" frameWidth="409" frameHeight="818"/>
	<SubTexture name="nega idle dance0000" x="831" y="828" width="419" height="767" frameX="-6" frameY="0" frameWidth="429" frameHeight="767"/>
	<SubTexture name="nega idle dance0001" x="831" y="828" width="419" height="767" frameX="-6" frameY="0" frameWidth="429" frameHeight="767"/>
	<SubTexture name="nega idle dance0002" x="1255" y="828" width="429" height="759" frameX="0" frameY="-8" frameWidth="429" frameHeight="767"/>
	<SubTexture name="nega idle dance0003" x="1255" y="828" width="429" height="759" frameX="0" frameY="-8" frameWidth="429" frameHeight="767"/>
	<SubTexture name="nega idle dance0004" x="1689" y="828" width="424" height="757" frameX="-2" frameY="-10" frameWidth="429" frameHeight="767"/>
	<SubTexture name="nega idle dance0005" x="1689" y="828" width="424" height="757" frameX="-2" frameY="-10" frameWidth="429" frameHeight="767"/>
	<SubTexture name="nega idle dance0006" x="2118" y="828" width="423" height="759" frameX="-3" frameY="-8" frameWidth="429" frameHeight="767"/>
	<SubTexture name="nega idle dance0007" x="2118" y="828" width="423" height="759" frameX="-3" frameY="-8" frameWidth="429" frameHeight="767"/>
	<SubTexture name="nega idle dance0008" x="2546" y="828" width="419" height="766" frameX="-5" frameY="-1" frameWidth="429" frameHeight="767"/>
	<SubTexture name="nega idle dance0009" x="2546" y="828" width="419" height="766" frameX="-5" frameY="-1" frameWidth="429" frameHeight="767"/>
	<SubTexture name="nega idle dance0010" x="2970" y="828" width="419" height="767" frameX="-6" frameY="0" frameWidth="429" frameHeight="767"/>
	<SubTexture name="nega idle dance0011" x="2970" y="828" width="419" height="767" frameX="-6" frameY="0" frameWidth="429" frameHeight="767"/>
	<SubTexture name="nega idle dance0012" x="831" y="828" width="419" height="767" frameX="-6" frameY="0" frameWidth="429" frameHeight="767"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0000" x="3394" y="828" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0001" x="3394" y="828" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0002" x="5" y="1642" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0003" x="5" y="1642" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0004" x="522" y="1642" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0005" x="522" y="1642" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0006" x="1039" y="1642" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0007" x="1039" y="1642" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0008" x="1556" y="1642" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0009" x="1556" y="1642" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0010" x="2073" y="1642" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0011" x="2073" y="1642" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0012" x="2590" y="1642" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0013" x="2590" y="1642" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0014" x="3107" y="1642" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0015" x="3107" y="1642" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0016" x="5" y="2304" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0017" x="5" y="2304" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0018" x="522" y="2304" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0019" x="522" y="2304" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0020" x="1039" y="2304" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0021" x="1039" y="2304" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0022" x="522" y="2304" width="512" height="657"/>
	<SubTexture name="WhatYouKnowAboutRollingDownInTheDeep0023" x="522" y="2304" width="512" height="657"/>
</TextureAtlas>

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by KutikiPlayz** [comment]
why is there nothing in your xml
you need shit in your xml

**Comment by ShadowMario** [comment]
Make a proper xml file.
