### ISSUE TITLE
Updating Haxe

### ISSUE THREAD

**Issue by NoobyWasTaken** [ShadowMario/FNF-PsychEngine#2657]
### What is your question?

If I update Haxe to 4.2.4 for Psych Source 0.5 and further, will I still be able to compile past versions of Psych (0.4.2 and below)?

**Comment by tposejank** [comment]
yes

**Comment by trayfellow** [comment]
yeah i use haxe 4.2.4 and i can still compile the other versions of psych just fine

**Comment by NoobyWasTaken** [comment]
Ok, thank you.
