### ISSUE TITLE
How do i change the texture of the opponent's arrows?

### ISSUE THREAD

**Issue by Gavman69** [ShadowMario/FNF-PsychEngine#2660]
### Describe your problem here.

I want to change the texture of the opponent's arrows, but I'm stupid.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

made a new setting.

**Comment by KutikiPlayz** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/discussions/995
