### ISSUE TITLE
Song.hx Problem

### ISSUE THREAD

**Issue by SergioIlSayan666** [ShadowMario/FNF-PsychEngine#2661]
### Describe your problem here.

How to fix Song.hx65: characters 27-41 : Array access is not allowed on { + lenght : Int }

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No for now.

**Comment by tposejank** [comment]
uodate haxe, @ShadowMario
