### ISSUE TITLE
Softcoded custom difficulties not working in menu

### ISSUE THREAD

**Issue by Salted-Beef** [ShadowMario/FNF-PsychEngine#2669]
### Describe your bug here.

I'm trying to make two softcoded difficulties:
CharOne
CharTwo
both have identical charts but different characters, both being just the Hard chart, no other difficulties.
They both load their respective .json chart, but in the menu, they don't work at all, either using the default menu assets or just the last one selected (switch from CharTwo to CharOne, loads CharOne json but shows CharTwo difficulty image)

### Command Prompt/Terminal logs (if existing)

```bash
None.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by ArezalGame89** [comment]
Are you sure it's in /mods? Then, make sure there's a menudiffculties in the /image of your mod and put your difficulty image there, also, be make sure that all the charts are the same name
