### ISSUE TITLE
Suggestion: Add unused bf-pixel 'hey' animation

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#267]
Hi guys,
So as stated in the title I would think it would be cool to add the unused **hey** sprite from pixel bf.
I think it would  be a good idea since there is already a noteType that makes the **hey** animation play.
If you want to add it I have already made the spritesheet, the xml and the json.
(Also it isn't from a random person. It is from Moawling himself)
I got the sprite from [**here**](https://moawling.gumroad.com/l/fnf-sprites)

[Bf Pixel.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/7314220/Bf.Pixel.zip)

**Comment by lemz1** [comment]
Sure, you can have the assets. Just click on Bf Pixel.zip

**Comment by ShadowMario** [comment]
There's no place in the week 6 where this could be used.
On Roses you can hear "Hey"s, but they happen *during* Boyfriend sections and so the animation would have been cut by a note sing
