### ISSUE TITLE
Make a white flash event

### ISSUE THREAD

**Issue by FartMaster57** [ShadowMario/FNF-PsychEngine#2672]
### Describe your problem here.

I wanna make an event that makes a white flash appear and fade away, the duration depending on value 1.
I wanted to use the example Opponent Fade event as a base. I don't really know Lua so I was wondering if I'm doing this correctly, and if I am, how do I make the alpha tween for the flash and not the opponent
Here's my edited code so far
> function onEvent(name, value1, value2)
	makeLuaSprite('stagefront', 'flash', -50, -150);
	if name == 'Opponent Fade' then
		duration = tonumber(value1);
		if duration < 0 then
			duration = 0;
		end
		addLuaSprite('stagefront');
		wait(0.5)
			doTweenAlpha('dadFadeEventTween', 'dad', targetAlpha, duration, 'linear');
			doTweenAlpha('iconDadFadeEventTween', 'iconP2', targetAlpha, duration, 'linear');
		end
		--debugPrint('Event triggered: ', name, duration, targetAlpha);
	end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I've added a few custom characters

**Comment by bbpanzu** [comment]
cameraFlash()

check the wiki

**Comment by FartMaster57** [comment]
Where on the wiki?
Are you saying there's something on the wiki specifically about "cameraflash()" or are you just saying to check the wiki?

**Comment by FartMaster57** [comment]
Wait nvm I found it

**Comment by FartMaster57** [comment]
Ok so I found it but once again I don’t really know how Lua works, so I don’t know how to make the color white

**Comment by Unholywanderer** [comment]
Incase you or anyone is having this still havin trouble
0xFFFFFF in color string
                                             
cameraFlash('game', '0xFFFFFF', 0.5, true)
