### ISSUE TITLE
Disable Cpu Strums [Source Code]

### ISSUE THREAD

**Issue by neighborduck** [ShadowMario/FNF-PsychEngine#2674]
### What is your question?

Is there anyway to disable the CPU Strums from lighting up upon hitting notes and if so how would I disable them?

**Comment by lemz1** [comment]
search 
**callOnLuas('opponentNoteHit', [notes.members.indexOf(note), Math.abs(note.noteData), note.noteType, note.isSustainNote]);**
and remove the strumplayanim function
