### ISSUE TITLE
how do i make a note type play a video?

### ISSUE THREAD

**Issue by arybaryan** [ShadowMario/FNF-PsychEngine#2675]
### Describe your problem here.

i'm trying to make a note type that makes it so it plays a static short video but its not working. help?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Rorthgamer2XD** [comment]
Sorry i have no idea how to make that,,,

**Comment by PDL2CGamejolt** [comment]
maybe Use the same cutscene script and put it in the note script

**Comment by PDL2CGamejolt** [comment]
![2021-12-25 (2)](https://user-images.githubusercontent.com/94698464/147387163-844af97c-1619-4265-837c-d7b338d9b59d.png)
Heres proof that this worked! this plays whenever you miss a note
