### ISSUE TITLE
How can i add Zoom on Enemy (not for the whole round)

### ISSUE THREAD

**Issue by asdvtx** [ShadowMario/FNF-PsychEngine#2676]
### Describe your problem here.

Please help is there a custom event wehre i can add enemy zoom off and on? - i have only enemy zoom but the zoom is for whole round and i need it just for a Second. Its should be like suicide mouse in Track happy 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by tposejank** [comment]
setProperty('dad.scale.x', 1.1)
setProperty('dad.scale.y', 1.1)

**Comment by asdvtx** [comment]
@tposejank how can i use this. How can i activate and the deactivate.
We apologize for any uncomfortable questions.
i am new
