### ISSUE TITLE
Expanded Lua documentation

### ISSUE THREAD

**Issue by TeeBeeX86** [ShadowMario/FNF-PsychEngine#2679]
### What needs to be documented?

Yea, it exists, but lua animations arent well documented, the only thing that exists about animation is how to make an animated lua sprite, and the rest you have to figure out through the stage example

**Comment by tposejank** [comment]
you will eventually find out

**Comment by RealReal334** [comment]
it's already Enough You just need to keep testing out all the function ( i hope they add LuaspriteAnimation each Anims Offset Function Tho)
so i don't have to use UpdatePost()

**Comment by bbpanzu** [comment]
animation offsets only exist on character objects tho.

**Comment by RealReal334** [comment]
> animation offsets only exist on character objects tho.

I figured out from your answer! thank you bbpanzu

Function onUpdatePost ()
If getProperty(‘sprite.animation.curAnim.name’) == ‘singLEFT’ then
setProperty(‘sprite.offset.x’, 20)
setProperty(‘sprite.offser.y’, 50)

end

end
