### ISSUE TITLE
How to add a stage?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#2686]
### What is your question?

I have an image, I want to set this image as stage, how to do it?

**Comment by bbpanzu** [comment]
read the wiki

**Comment by zwl1619** [comment]
@bbpanzu I don't find something on it.

**Comment by AlejoFunk** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API on this page there is an example with the lua
