### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by K1ZANA** [ShadowMario/FNF-PsychEngine#2689]
### Describe your bug here.

In the Discord RPC, when you edit a Week. Instead of it saying "Editing {weekname}", it says "Edit**t**ting {weekname}". This isnt a huge error, but its just not really nice looking at it.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

The person edited the weeks.

**Comment by ShadowMario** [comment]
Chill with the nitpicks man people hardly cares about RPC anyway
