### ISSUE TITLE
graphics in lua dont work

### ISSUE THREAD

**Issue by AlyssonRo** [ShadowMario/FNF-PsychEngine#2690]
### Describe your bug here.

the code makeGraphic dont work for me on the new version. here is the code maybe something is wrong or something
```
    makeGraphic('testBlackSquare', 1000, 1000, '220707')
    addLuaSprite('testBlackSquare', true)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

added some shit like characters, stages, songs

**Comment by bbpanzu** [comment]
you need to makeLuaSprite THEN makeGraphic

**Comment by ShadowMario** [comment]
```lua
makeLuaSprite('testBlackSquare', nil, X POSITION HERE, Y POSITION HERE);
makeGraphic('testBlackSquare', 1000, 1000, '220707')
addLuaSprite('testBlackSquare', true)
