### ISSUE TITLE
can you make the difficultys made in lua

### ISSUE THREAD

**Issue by TheDisabledKid** [ShadowMario/FNF-PsychEngine#2692]
### What feature do you want to get added on the base engine?

i think the difficultys can be lua made as well like what i mean is lets just say for example someone made a custom difficult into the mods folder  
can you make it the difficulty lua coded as well?  
so whatever difficulty it does it has to do that difficulty only 
like if there is only one difficulty it will only use that one diffculty 
and you can enable and disable the difficulty 5

**Comment by PoleyMagik** [comment]
The week editor already allows you to force only 1 difficulty. Simply specify the weeks and it will only use them.
