### ISSUE TITLE
Multi-player 1/2

### ISSUE THREAD

**Issue by Doritojoey** [ShadowMario/FNF-PsychEngine#2699]
### What feature do you want to get added on the base engine?

Not multiplayer but an easier way of like how bbpanzu did Skid in Santa. You can pinpoint which notes are one characters which are another, or another way of doing this would just make there be more grids or something. In the chart menu the song tab would have a plus and a minus button next to the Player 1 and player 2 like how you would select multiple events. So for example lets say I wanna add another dad. I press plus and in my stage json I would put "opponent-2": [fat, nuts] 
I also think this would be a good time to improve some charting features like must hit section, so instead of "must hit section" there could be 'Focus: dad, dad2, bf, gf' that you can put for each section. Tedious but I can't think of anything much better right now at 1:30 but yeah I can't code horse shit but from what I've seen with lua and how you have to pull teeth with it to get a 3rd player working seems hard enough already so this seems difficult to put in working form in Haxe including chart stuff but would be great.

**Comment by Doritojoey** [comment]
:(

**Comment by MaybeMaru** [comment]
that would be kinda cool ngl, but i get why it won't be added
