### ISSUE TITLE
cannot add dialogue/

### ISSUE THREAD

**Issue by megakeh** [ShadowMario/FNF-PsychEngine#27]
ive followed the dialogue wiki but, it doesnt really tell you where to put the assets,like, the character on the dialogue scene,the wiki simply tells you how to activate a dialogue and add the text.

**Comment by ShadowMario** [comment]
Check out DialogueCharacter.hx

**Comment by megakeh** [comment]
> Check out DialogueBoxPsych.hx

Thank you! It worked, kind of, i got it working for the first two songs, but not the third one, its called "ruff-it",it just crashes, is it because of the space?

**Comment by megakeh** [comment]
> Check out DialogueBoxPsych.hx

thank you!
