### ISSUE TITLE
Can you change menu positions but for each menu selection?

### ISSUE THREAD

**Issue by Fablisothebottle** [ShadowMario/FNF-PsychEngine#2700]
### What is your question?

So I want to make something like the Sonic.exe mod in the 2.0 update where they start from left then end at right. I'm noy sure if I can just use the source and copy over since they made the mod on Kade Engine. Can anybody help?
Here's a image of the menu from Sonic.exe
![Screenshot 2021-12-26 014043](https://user-images.githubusercontent.com/95256692/147400982-db650e01-388b-45d2-a00c-5e791ceb0d71.png)

**Comment by denumu07** [comment]
Do you want it Exactly like in VS EXE?

**Comment by denumu07** [comment]
i only know how to change the Position of ALL Menu Selection buttons or Remove Buttons

**Comment by Fablisothebottle** [comment]
oh k thanks for sharing your knowing's! :D

**Comment by GhazYT** [comment]
> i only know how to change the Position of ALL Menu Selection buttons or Remove Buttons

how to remove the button?
