### ISSUE TITLE
Opponent Mode (as a Gameplay Changer)

### ISSUE THREAD

**Issue by Gui-iago** [ShadowMario/FNF-PsychEngine#2701]
### What feature do you want to get added on the base engine?

kinda self explanatory, but like this

https://user-images.githubusercontent.com/45212377/147401954-fd53683d-9d53-4356-aa89-ef66d5766edd.mp4

**Comment by Collabvmisgood** [comment]
So you want the player to play the opponent side?

**Comment by PDL2CGamejolt** [comment]
yes i do with him

**Comment by Gui-iago** [comment]
> So you want the player to play the opponent side?

yeah

**Comment by bbpanzu** [comment]
here's how you would do it in lua with some pseudo-code

```
for each i in unspawnedNotes
if note #i is a mustHit note then
 setPropFromGroup(unspawnedNotes, i , mustHit, false)
else
 setPropFromGroup(unspawnedNotes, i , mustHit, true)
end

end

setPropFromGroup(playerstrums, 0 , x, enemyStrumX0)
setPropFromGroup(playerstrums, 1 , x, enemyStrumX1)
setPropFromGroup(playerstrums, 2 , x, enemyStrumX2)
setPropFromGroup(playerstrums, 3 , x, enemyStrumX3)

setPropFromGroup(enemystrums, 0 , x, playerStrumX0)
setPropFromGroup(enemystrums, 1 , x, playerStrumX1)
setPropFromGroup(enemystrums, 2 , x, playerStrumX2)
setPropFromGroup(enemystrums, 3 , x, playerStrumX3)

```

**Comment by Gui-iago** [comment]
bbpanzu's lua code didn't work (unfortunately), but it's now solved thanks to this pull request https://github.com/ShadowMario/FNF-PsychEngine/pull/2770
