### ISSUE TITLE
how do i turn off charting mode

### ISSUE THREAD

**Issue by ethaxo99** [ShadowMario/FNF-PsychEngine#2702]
### Describe your problem here.

i don't know how turn turn off charting mode so i can quit out of a song normally. how do i do that

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Gui-iago** [comment]
Exit to the Menus and select the song again

**Comment by ethaxo99** [comment]
k thx :)

**Comment by Gui-iago** [comment]
> k thx :)

@ethaxo99 don't forget to close this
