### ISSUE TITLE
Pressing back on the change difficulty menu crash

### ISSUE THREAD

**Issue by Superyoshi94** [ShadowMario/FNF-PsychEngine#2703]
### Describe your bug here.

In Psych Engine 0.5.1, if you go into the change difficulty menu from the pause menu and press back, it will tell you that there is no null difficulty. This is on a non-modded version of the game from Github, no source code edits.

### Command Prompt/Terminal logs (if existing)

```bash
source/TitleState.hx:139: version online: 0.5.1, your version: 0.5.1
source/Discord.hx:17: Discord Client starting...
source/Discord.hx:67: Discord Client initialized
source/Discord.hx:24: Discord Client started.
source/FreeplayState.hx:323: thorns-hard
source/FreeplayState.hx:329: CURRENT WEEK: week6
source/LoadingState.hx:162: Setting asset folder to week6
source/Conductor.hx:75: new BPM map BUDDY []

[file_contents,assets/data/thorns/thorns-null.json]

(Still no source edits, just ran it from cmd)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Gui-iago** [comment]
already fixed, update your source
