### ISSUE TITLE
Play video behind the UI (The arrow, health bar and stuff)

### ISSUE THREAD

**Issue by and1558** [ShadowMario/FNF-PsychEngine#2708]
### Describe your problem here.

i dont know how to play a video behind the fnf UI (The arrow, health bar and stuff)
can anyone help me or show me how to do it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i removed all weeks (except week 2) incl all of the songs (except for south which is modified)

**Comment by RinZleR121** [comment]
it's useless, video plays at the start of the countdown, so it's means that it plays BEFORE the UI loads

**Comment by and1558** [comment]
well i wanted it after ui loads

**Comment by RinZleR121** [comment]
there's no feature to play video during song so like i said it's useless

**Comment by RinZleR121** [comment]
[There is a proof](https://github.com/ShadowMario/FNF-PsychEngine/issues/3032)

**Comment by and1558** [comment]
like what?

**Comment by ThePsychEngineFan** [comment]
bro he literally just sent proof
