### ISSUE TITLE
Ghosttapping during dialogue

### ISSUE THREAD

**Issue by Salted-Beef** [ShadowMario/FNF-PsychEngine#2710]
### Describe your bug here.

I've used the template dialogue lua script, but during the dialogue, it's still possible to ghost tap and die, thus crashing the game.

### Command Prompt/Terminal logs (if existing)

```bash
None available
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing has been changed.

**Comment by ShadowMario** [comment]
`setProperty('inCutscene', true);` before starting the dialogue.
