### ISSUE TITLE
changing oponets midsong

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#2719]
### Describe your problem here.

I tried it before with Pico but it only changed bf wat do I do btw I don't use Lua I chose it cuz I have to

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i am trying to make my own mod without code

**Comment by lemz1** [comment]
go to the charting menu and use the change character event
