### ISSUE TITLE
There is a cutscene at the beginning of the song, dialogue at the end of the song.

### ISSUE THREAD

**Issue by CHEEKIFORTRESS** [ShadowMario/FNF-PsychEngine#2722]
### What is your question?

I'm wondering if it's possible to make the cutscene play at the beginning of the song and the dialogue play at the end of the song using Lua? If so, how?

Sorry if the question is too stupid.

**Comment by Coolgaymerboi** [comment]
I think you need to put the cutscene on the second song in order for it to work lol
