### ISSUE TITLE
new versions not compiling

### ISSUE THREAD

**Issue by Captainfinnster** [ShadowMario/FNF-PsychEngine#2723]
### Describe your bug here.

when i run lime test windows it says something about the song.hx having characters in the wrong spots and when that stops it says the characters are broken

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i did nothing to the code and didnt even add a file

**Comment by loogchin** [comment]
UPDATE HAXE 4.2.4

**Comment by tposejank** [comment]
@ShadowMario

**Comment by Captainfinnster** [comment]
> 

will still be able to use 04.2?

**Comment by tposejank** [comment]
> > 
> 
> will still be able to use 04.2?

yes

**Comment by DragShot** [comment]
See my answer in #2724.

**Comment by denumu07** [comment]
Update your Haxe[https://haxe.org/](url) to 4.2.4!
