### ISSUE TITLE
Psych Engine will not compile.

### ISSUE THREAD

**Issue by TKEFNFAR420** [ShadowMario/FNF-PsychEngine#2724]
### Describe your bug here.

**I just hate psych engine sometimes.  When i try to compile the game, it just tells me this:** 

![fix your shit psycg](https://user-images.githubusercontent.com/96694531/147414071-5dfa9759-7fc9-408d-8bac-996d29d528e8.PNG)

_**please fix yo stuff psych engine, i am begging you**_

### Command Prompt/Terminal logs (if existing)

```bash
source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not edit anything.

**Comment by SrtHero278** [comment]
haxe 4.2.4

**Comment by tposejank** [comment]
@ShadowMario

**Comment by DragShot** [comment]
Here's an actual fix: go to `Song.hx` and in line 52, change the code from this:
```
private static function onLoadJson(songJson) // Convert old charts to newest format
```
... to this:
```
private static function onLoadJson(songJson:Dynamic) // Convert old charts to newest format
```
The game should now compile without that error getting in the way, no annoying reinstalls or upgrades needed.

**Comment by KutikiPlayz** [comment]
> Here's an actual fix: go to `Song.hx` and in line 52, change the code from this:
> 
> ```
> private static function onLoadJson(songJson) // Convert old charts to newest format
> ```
> 
> ... to this:
> 
> ```
> private static function onLoadJson(songJson:Dynamic) // Convert old charts to newest format
> ```
> 
> The game should now compile without that error getting in the way, no annoying reinstalls or upgrades needed.

why would you do that when you can just
***update your goddamn haxe***

**Comment by bbpanzu** [comment]
> > Here's an actual fix: go to `Song.hx` and in line 52, change the code from this:
> > ```
> > private static function onLoadJson(songJson) // Convert old charts to newest format
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ... to this:
> > ```
> > private static function onLoadJson(songJson:Dynamic) // Convert old charts to newest format
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The game should now compile without that error getting in the way, no annoying reinstalls or upgrades needed.
> 
> why would you do that when you can just _**update your goddamn haxe**_

faster honestly

**Comment by DragShot** [comment]
> why would you do that when you can just _**update your goddamn haxe**_

Why Download yet another 5GB of dependencies when I can just write a word? Man, I dunno.

At least have the decency of replacing the deprecated calls in your codebase before asking me to do such thing. I don't want to see yet another dozen of deprecation warnings lol.

**Comment by ShadowMario** [comment]
I updated the source code with @DragShot's fix yesterday, could you check?

**Comment by drawboooyy** [comment]
source/Main.hx:91: characters 30-32 : Missing ; help pls
