### ISSUE TITLE
Song's .JSON not loading correctly.

### ISSUE THREAD

**Issue by TechnicTom22** [ShadowMario/FNF-PsychEngine#2728]
### Describe your bug here.

My song's charting is not loading once it is selected in the freeplay menu.
I go to choose it and instead it plays Bopeebo's charting on top of my song's instrumental and voices.
I have double checked that my song's charting is in assets/preload/data and also that it is in fact, not bopeebo's chart.
My song does not contain any spaces so a spacing issue should be ruled out.

### Command Prompt/Terminal logs (if existing)

```bash
Creating library ApplicationMain.lib and object ApplicationMain.exp
source/Discord.hx:17: Discord Client starting...
source/Discord.hx:67: Discord Client initialized
source/Discord.hx:24: Discord Client started.
source/FreeplayState.hx:323: grudge
source/FreeplayState.hx:329: CURRENT WEEK: week7
source/LoadingState.hx:162: Setting asset folder to shared
source/Conductor.hx:75: new BPM map BUDDY []
source/Conductor.hx:75: new BPM map BUDDY []
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added new song, character, and week.

**Comment by blueDev2** [comment]
Did you name a folder inside preload/data with your song's name and did you name the chart with your song's name?

**Comment by ShadowMario** [comment]
You have to change the song name on the Chart Editor...
