### ISSUE TITLE
Scrolling Down Custom Credits Make Background Black

### ISSUE THREAD

**Issue by JP1619** [ShadowMario/FNF-PsychEngine#2731]
### Describe your bug here.

So, i did everything normally but when i added 1 more person(it was only 1 so i added another one) and when i scrolled down to see it the background goes black being unable to read names.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, just added a credits folder in mods/images and a credits.txt in mods/data

**Comment by Gui-iago** [comment]
remove the "0x" on the color code

**Comment by SrtHero278** [comment]
> remove the "0x" on the color code

No. The "0x" is essential.

did you do `0xFF+HexColor`?

**Comment by JP1619** [comment]
> > remove the "0x" on the color code
> 
> No. The "0x" is essential.
> 
> did you do `0xFF+HexColor`?

i did "0x(hexcolor with no ())

**Comment by SrtHero278** [comment]
> > > remove the "0x" on the color code
> > 
> > 
> > No. The "0x" is essential.
> > did you do `0xFF+HexColor`?
> 
> i did "0x(hexcolor with no ())

If your color code is 8 characters, add an `FF` after the `0x`.

**Comment by JP1619** [comment]
> > > > remove the "0x" on the color code
> > > 
> > > 
> > > No. The "0x" is essential.
> > > did you do `0xFF+HexColor`?
> > 
> > 
> > i did "0x(hexcolor with no ())
> 
> If your color code is 8 characters, add an `FF` after the `0x`.

oh! ty
