### ISSUE TITLE
compiling old versions

### ISSUE THREAD

**Issue by Captainfinnster** [ShadowMario/FNF-PsychEngine#2735]
### Describe your bug here.

when i compile 4.2 it doesnt run and its just a black screen... is this because I updated haxe?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i did nothing to the code and didnt even add a file

**Comment by tposejank** [comment]
no

**Comment by ShadowMario** [comment]
1. It's not
2. Older versions aren't supported anymore.
