### ISSUE TITLE
more support for custom key functions/keys using lua KeyJustPressed() or KeyPressed()

### ISSUE THREAD

**Issue by Salted-Beef** [ShadowMario/FNF-PsychEngine#2742]
### What feature do you want to get added on the base engine?

I really want to see the function KeyJustPressed() get more available keys to be pressed, as currently the only keys we can use are left, down, right, up, space, accept, pause, reset, and back. For example:

function onUpdate()
    if keyJustPressed('v') then --Taunt by pressing V
        characterPlayAnim('boyfriend', 'hey', true);
    end
end

Also, can you make it possible for all keys to proceed to the next line of dialogue like in other engines?

**Comment by PoleyMagik** [comment]
You already can do this. Using LUA you can grab the state of any button supported by HaxeFlixel.
`getPropertyFromClass('flixel.FlxG', 'keys.justPressed.V')` lets you grab V's state, and if you want to know if it was just pressed rather then down, it's still rather easy. Put this in an OnUpdate function and it will give you a local called vJustPressed to track it for you.
```
local vJustPressed = false;
if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.V') and not vJustPressed then
	vJustPressed = true;
else
	vJustPressed = false;
end
```
