### ISSUE TITLE
Changing BPM does not change Sustain Length step

### ISSUE THREAD

**Issue by Galaxy621** [ShadowMario/FNF-PsychEngine#2744]
### Describe your bug here.

If you are to change your songs BPM in the 'song' tab, the length of new sustain notes is linked to the previous BPM. This stops happening after you leave and re-enter the chart editor.

For example, if you start with a song with 150 BPM, and decrease it to 142 BPM, the sustain length will still go up in 50's. When you leave and re-enter, it will correct itself and start going up in 53's

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, this build is heavily modified, with things such as new menu layouts, added menus, and end-screens. I however, have not touched the charting editor.

**Comment by bbpanzu** [comment]
holds are based on bpm thats why

**Comment by Galaxy621** [comment]
The issue is that it doesn't work until you leave and re-enter the charting editor.

https://user-images.githubusercontent.com/59318029/147477697-cab4b79d-6c94-4236-9786-f255c977dd3b.mp4
