### ISSUE TITLE
Duo character?

### ISSUE THREAD

**Issue by pakieFNF** [ShadowMario/FNF-PsychEngine#2747]
### Describe your problem here.

i need to know to make a character that has another one alongside them that only sings with the alt animation note type while the other does their idle animation or vise versa, so im wondering because iirc characters can use lua scripts, is it possible is there one out there that allows me to do a duo character?

e.g
![mod shown: shaggy x matt](https://user-images.githubusercontent.com/30850366/147432475-00a2e3b2-2093-4ab5-a653-b9b8edd51dbf.gif)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i've edited playstate, clientprefs, the option menus, the title screen, the story mode menu, along with adding a few characters, adding character noteskins, changing some of the UI sounds, the menu music, and adding 2 stages

**Comment by bbpanzu** [comment]
check holiday mod code

**Comment by pakieFNF** [comment]
aight

**Comment by ByronisJoan** [comment]
> holiday mod code

Theres no Source, Its Actually For the Mod Folder
