### ISSUE TITLE
All Judgements Give The Same Score

### ISSUE THREAD

**Issue by SussyFellow** [ShadowMario/FNF-PsychEngine#2751]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/88362641/147435408-e7f9ee99-ce33-42bd-adc6-ee49056e42f1.png)
To put it as simply as possible, when playing on Psych Engine 0.5.1, on a fresh download with no mods of any kind downloaded, hitting notes ALWAYS gives you 350 points regardless of if you hit a Sick, or a GOOD, or a BAD, or even a SHIT. This is a clear discrepancy with the base game, where points are awarded in descending amounts based on how accurately you hit the notes, and I can't imagine it was an intended feature for Psych Engine.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, this build is completely unedited.

**Comment by tposejank** [comment]
Why is that important? I mean, nobody cares about the score. In anyway, I feel like it was intended because shadow Mario hasnt done anything bout it

**Comment by SussyFellow** [comment]
I _highly_ doubt this was intended. Why on earth would you intentionally make the scoring system both worse and less accurate to the base game?

**Comment by ShadowMario** [comment]
Fixed a while ago
