### ISSUE TITLE
Difficulty null

### ISSUE THREAD

**Issue by pepe10-gpu** [ShadowMario/FNF-PsychEngine#2752]
### Describe your bug here.

Base build, any song -> change difficulty -> back -> songname-null.json not found

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by cherryiguess** [comment]
It's fixed, just not in a release build

**Comment by Superyoshi94** [comment]
Yeah, just get 0.5 or build the newest source code. (they really should put this fix in the release though)
