### ISSUE TITLE
which version of openfl should i use of andromeda-engine

### ISSUE THREAD

**Issue by JonnyboyTheboy** [ShadowMario/FNF-PsychEngine#2755]
### What is your question?

im sorry to talk about another engine but im trying to compile for it on macos and it crashes every i try to play a week for something because of the shaders so please help me im going insaine

**Comment by JonnyboyTheboy** [comment]
and i asked them on there engine but no one has responed

**Comment by crispyboi24** [comment]
Wrong place buddy.

**Comment by JonnyboyTheboy** [comment]
nevermind i fixed it
