### ISSUE TITLE
No audio for me.

### ISSUE THREAD

**Issue by CrazyCookiesOFFICIAL** [ShadowMario/FNF-PsychEngine#2758]
### Describe your bug here.

I. DO NOT. SEE ANYONE. ELSE HAVING. THIS PROBLEM.

WHY THE HELL IS THERE NO AUDIO OUTPUT WHEN I TRY TO USE PSYCH ENGINE

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

NO I JUST BOOTED IT UP FOR THE FIRST TIME PLEASE

**Comment by CrazyCookiesOFFICIAL** [comment]
To elaborate more, All that happens is when I boot up the game, there's no audio, whatsoever. No sound effects, no music, just dead silent.

I did not modify the game in any way, I seriously am creeped out by this...

**Comment by tposejank** [comment]
Long time ago, I had an issue with Kade Engine and it would not play audio, it warned me of something in the terminal, but I couldnt play audio from anything, turns out it was a driver issue.

**Comment by CrazyCookiesOFFICIAL** [comment]
> Long time ago, I had an issue with Kade Engine and it would not play audio, it warned me of something in the terminal, but I couldnt play audio from anything, turns out it was a driver issue.

How do I fix this? I just got this computer, sorta new to how they work LMAO

**Comment by FuroYT** [comment]
Press `+` or `0` twice on the num pad

**Comment by Iryn-e** [comment]
I had a similar problem, I realized that my antivirus (AVG) was causing the problem, so I put (C:\(Where you placed the folders)\Kade-Engine) in the list of exceptions so that my antivirus doesn't bother it on startup
