### ISSUE TITLE
How do I play a cutscene after a song?

### ISSUE THREAD

**Issue by chimoks** [ShadowMario/FNF-PsychEngine#2760]
### Describe your problem here.

I'm pretty bad at coding so I mostly just stick to the compiled build.
How do I play a mp4 cutscene after a song ends?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by denumu07** [comment]
I don't know. But you could Play The Cutscene in the Next Song. That's almost the Same
