### ISSUE TITLE
Discovered Something (PSYCH ENGINE 0.5.1 THING)

### ISSUE THREAD

**Issue by RoubertY** [ShadowMario/FNF-PsychEngine#2771]
### Describe your problem here.

So i was curious how in the holiday part 2 mod there's a song with custom difficulties and i figured out that u can put custom difficulties on psych engine on a week, simply go to week editor -> others -> and there u have it, the difficulties thing, i tried to do an asset for the difficulty for story mode, the game just puts the hard asset instead of the difficulty asset i made (im very bad at explaining lol)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no nothing in it

**Comment by DaBanana64** [comment]
Put your custom difficulty images in `mods/images/difficulties (You have to create this folder by yourself)`

**Comment by Doritojoey** [comment]
Uh yeah thats a feature. I believe it was a 0.42 or 0.5 thing

**Comment by DaBanana64** [comment]
> Uh yeah thats a feature. I believe it was a 0.42 or 0.5 thing

It was for 0.5

**Comment by Superyoshi94** [comment]
Go to mods/images and open menudifficulties
![image](https://user-images.githubusercontent.com/82662993/147517330-2a65d137-4e7f-4909-8326-b5d655852f4b.png)

**Comment by Superyoshi94** [comment]
then put the difficulty file png inside of the folder (not case sensitive)
![image](https://user-images.githubusercontent.com/82662993/147517390-45b40a53-b797-4de3-8562-6671fcee6a5b.png)

**Comment by Superyoshi94** [comment]
Be sure that when you do this, you use one of the actual difficulties (assets/images/menudifficulties) according to the size of your difficulty. As long as its not too small, you should be able to use it. (Big ones are fine because psych engine will resize it to fit.)

**Comment by Superyoshi94** [comment]
example:
![image](https://user-images.githubusercontent.com/82662993/147517647-ab77f9d6-e48f-4ba8-808f-4e8a3c11d82d.png)
If you dont have a texture for it, it will load as a hard texture.

**Comment by RoubertY** [comment]
Thanks to everyone!
