### ISSUE TITLE
Dialogue after cutscene

### ISSUE THREAD

**Issue by RareBeeCodez** [ShadowMario/FNF-PsychEngine#2773]
### What is your question?

Hello, is it possible to make a dialogue play after the cutscene without the source code?

**Comment by blueDev2** [comment]
[DialogueAndCutscene.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7783365/DialogueAndCutscene.txt)
Here is some code structure, please ask any questions you may have

**Comment by WinV-Bros** [comment]
> [DialogueAndCutscene.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7783365/DialogueAndCutscene.txt) Here is some code structure, please ask any questions you may have It uses the structure from the dialogue and video example scripts from [here](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API)

it just loops the video. any help?

**Comment by WinV-Bros** [comment]
just loops any help?
