### ISSUE TITLE
Invalid Char 93 at Position 71

### ISSUE THREAD

**Issue by tapacid** [ShadowMario/FNF-PsychEngine#2779]
### Describe your problem here.

How can i fix the error?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited The Week1 File and created 2 new song files

**Comment by SrtHero278** [comment]
It's a JSON error. There are actually websites to detect these. I use JSON Lint.
