### ISSUE TITLE
how can i add my own song 

### ISSUE THREAD

**Issue by tapacid** [ShadowMario/FNF-PsychEngine#2782]
### Describe your problem here.

ok so i have my own song in the files and in the week but for some reason it plays bopeebo instead of the song i want

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by SrtHero278** [comment]
![image](https://user-images.githubusercontent.com/93018286/147506454-9de4628b-e42f-498a-8eb5-cf287ce22b25.png)
Did you modify this box on the top left and save it? It's in the song tab.

**Comment by tapacid** [comment]
> 

no i didnt ill try it and get back to you

**Comment by tapacid** [comment]
![image](https://user-images.githubusercontent.com/96747491/147506708-a861afa8-c7da-45f8-b582-9bb039df229d.png)
soo what do i do now

**Comment by SrtHero278** [comment]
I think this happens when the game can't find the song. Did you type it in correctly? (Not case sensitive btw)
![image](https://user-images.githubusercontent.com/93018286/147507589-c940758d-6fb3-4922-b3fd-57c7ff7cabca.png)
![image](https://user-images.githubusercontent.com/93018286/147507604-160480e0-cbe4-40a7-8f3a-10d16b98ca02.png)

**Comment by tapacid** [comment]
> I think this happens when the game can't find the song. Did you type it in correctly? (Not case sensitive btw) ![image](https://user-images.githubusercontent.com/93018286/147507589-c940758d-6fb3-4922-b3fd-57c7ff7cabca.png) ![image](https://user-images.githubusercontent.com/93018286/147507604-160480e0-cbe4-40a7-8f3a-10d16b98ca02.png) (The folder is in `songs` fyi)

so i spelt it correctly and its in the files

**Comment by tapacid** [comment]
![image](https://user-images.githubusercontent.com/96747491/147507962-23afb5a7-2540-4127-b73a-be0512d6ac27.png)
![Screenshot 2021-12-27 161958](https://user-images.githubusercontent.com/96747491/147507976-e3ef8f82-8b3f-44ac-a9bb-6f97f000899c.png)

**Comment by tapacid** [comment]
and btw the song is 8 minutes long so maybe thats why

**Comment by tapacid** [comment]
and they arent ogg files

**Comment by tposejank** [comment]
the length of the files doesnt matter
however they need to be ogg

**Comment by tapacid** [comment]
> the length of the files doesnt matter however they need to be ogg

i fixed them they are now ogg files but it still wont work

**Comment by lemz1** [comment]
in the song folder needs to be mp3 and ogg if im not wrong. They get compiled to ogg in the export folder

**Comment by MayoALT** [comment]
mp3 is only for html5

**Comment by MayoALT** [comment]
> > the length of the files doesnt matter however they need to be ogg
> 
> i fixed them they are now ogg files but it still wont work

are the two channels named "Inst" and "Voices" ? (its case sensitive)
