### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#2785]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/94698464/147505922-d2b88c40-c7e9-4d27-b994-fb60abaa9153.png)
how do i do this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by tposejank** [comment]
modify alphabet.hx

**Comment by blueDev2** [comment]
I don't think it would be possible to use Lua scripts to affect menu items
See [this](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API)

**Comment by PDL2CGamejolt** [comment]
how do i change all of the text's font with lua
