### ISSUE TITLE
asset loading issue

### ISSUE THREAD

**Issue by DOGZ1234** [ShadowMario/FNF-PsychEngine#2788]
### Describe your bug here.

On mac the asset loading system is bugged in such a way that the normal and lua mods work fine but actually adding things to the build like custom characters the character file works right but it can't load the png or xml of the character.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
Mac has no official support due to me lacking a Mac VM/Computer
