### ISSUE TITLE
Custom note

### ISSUE THREAD

**Issue by WaFl-XIV** [ShadowMario/FNF-PsychEngine#2793]
### Describe your problem here.

How do I make custom notes in the current version? (0.5.1)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yeah, I edited some stuff, but none of the changes has anything to do with my question.

**Comment by tposejank** [comment]
wiki

**Comment by KutikiPlayz** [comment]
this video should help
https://youtu.be/_-VVrDpL-8Q
