### ISSUE TITLE
Does Psych support animated icons?

### ISSUE THREAD

**Issue by cheemynugget3** [ShadowMario/FNF-PsychEngine#2796]
### What is your question?

So, I want to make it so in my mod a certain character has an animated icon

Lets say i make an xml. do i just type in the name of the icon and boom? or is there something else i gotta do?

LUA
didnt know if i should put this with the help label or question label

**Comment by ShadowMario** [comment]
No, you can create an animated lua sprite, hide the original icon and put the custom sprite over them though but it's kinda complicated.

**Comment by WaldenMD** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/discussions/2435
