### ISSUE TITLE
How do I use the "cameraflash()" function?

### ISSUE THREAD

**Issue by FartMaster57** [ShadowMario/FNF-PsychEngine#2798]
### Describe your problem here.

I wanna make an event where the screen flashes white, I'm still confused on how to do this even after reading the wiki.
Am I doing this right?

```
function onEvent(name, value1, value2)
	if name == 'Flash' then
		
		duration = tonumber(value1);
		if duration < 0 then
			duration = 0;
		end
		cameraFlash(game, white, 'duration', false)
		end
	end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by blueDev2** [comment]
Why is duration (the argument in cameraFlash) in quotes?

**Comment by FartMaster57** [comment]
idk, i'll change that. But how do I make the flash work? Like what am I doing wrong?

**Comment by blueDev2** [comment]
What are you trying to do exactly?
Cover the front of the screen with white light?

**Comment by FartMaster57** [comment]
Yes, I want it to flash white and have the white fade away

**Comment by FartMaster57** [comment]
I feel like I'm doing everything correct except for the first string (unless I'm not and I'm just doing everything incorrect). On the wiki it just says "camera - 'game', 'hud' or 'other' " and I don't know what that means
```
function onEvent(name, value1, value2)
	if name == 'Flash' then
		cameraFlash("game", '255, 255, 255', 0.7, false)
		end
	end
```

**Comment by blueDev2** [comment]
So in FunkinLua.hx, this is what happens when "cameraFlash" is called
So you have to put in a String
Lua_helper.add_callback(lua, "cameraFlash", function(camera:String, color:String, duration:Float,forced:Bool) {
	var colorNum:Int = Std.parseInt(color);
	if(!color.startsWith('0x')) colorNum = Std.parseInt('0xff' + color);
	cameraFromString(camera).flash(colorNum, duration,null,forced);
ColorNum has to be in the RGB form in Hexadecimal
For white, it is "FFFFFF" or "0xFFFFFFFF" (The first 2 'F's are for opacity)

**Comment by FartMaster57** [comment]
for the camera string do I just put "game"

**Comment by blueDev2** [comment]
I'm gonna be honest and say IDK
There's only 3 options, just try them all

**Comment by FartMaster57** [comment]
none of them work
why is there absolutely no explanation for how to do this? It's getting on my nerves

**Comment by blueDev2** [comment]
Actually, I think you might be making the Lua code wrong
I think you have 1 too many "end" statements
The first end statement

**Comment by blueDev2** [comment]
Wait no, Function also has an end statement, nvm

**Comment by blueDev2** [comment]
Did you name the lua script correctly?

**Comment by FartMaster57** [comment]
Yeah I just tried deleting one and it crashes the game

**Comment by FartMaster57** [comment]
Yeah the script is called "Flash.lua"

**Comment by FartMaster57** [comment]
This is my code rn
```
function onEvent(name)
	if name == 'Flash' then
		cameraFlash('game', "FFFFFF", 0.7, true)
		end
	end
```

**Comment by blueDev2** [comment]
Oh I know the problem then
You have to name the script the same name as your stage

**Comment by FartMaster57** [comment]
wait really?

**Comment by FartMaster57** [comment]
why?

**Comment by blueDev2** [comment]
If you look at Playstate.hx
Near the begining is something that will add a lua script if it has the same stage name

**Comment by FartMaster57** [comment]
This is a custom event in lua, I don't have the source code

**Comment by blueDev2** [comment]
Well actually, you could make it a global script, but then you would have to add it to the scripts folder
Which you could do

**Comment by blueDev2** [comment]
You could always just look at the data file for the song to see the stage name.

**Comment by FartMaster57** [comment]
Ok actually I probably should've specified that this is a custom event in the custom_events folder and not just a script
![image](https://user-images.githubusercontent.com/58342249/147529992-258af74e-0639-4ff6-96a2-0b792fc0728c.png)

**Comment by blueDev2** [comment]
Did you add a Flash.TXT as well?

**Comment by tposejank** [comment]
cameraFlash('game', 'ffffff', 1, true)
