### ISSUE TITLE
Need mod folder directory

### ISSUE THREAD

**Issue by snazzyostrich** [ShadowMario/FNF-PsychEngine#2804]
### Describe your problem here.

The game cannot find my mod folder. Neither can it find a song from it in the chart editor.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
Need more information about where you put everything.

**Comment by snazzyostrich** [comment]
> Need more information about where you put everything.

i solved it nvm

**Comment by Coolgaymerboi** [comment]
I think your using an old version of psych engine that's why it doesn't work try to update using the version 5.1

**Comment by ThePsychEngineFan** [comment]
> > Need more information about where you put everything.
> 
> i solved it nvm

then... close the fucking issue?
