### ISSUE TITLE
Character idle won't play

### ISSUE THREAD

**Issue by BoltDT** [ShadowMario/FNF-PsychEngine#2806]
### Describe your problem here.

When starting a song, my custom character, Tankman, won't play his idle dispite the animation existing in the json. His offsets don't work either.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't do any source code modification. I did modify the character list.

**Comment by ShadowMario** [comment]
Missing idle animation, check the Character Editor.

**Comment by RedstoneRuler** [comment]
You may have named it "Idle" instead of "idle".
