### ISSUE TITLE
Modded playable character death screen doesn't work

### ISSUE THREAD

**Issue by Filename99** [ShadowMario/FNF-PsychEngine#2812]
### Describe your bug here.

The engine ignores the death sprites of any playable character if it is not the Boyfriend's reskin (a completely another) and when I die in the game, I am shown "Boyfriend Death Screen" instead of "My Character's Death Screen". I'll show you what that looks like in a moment:
![image](https://user-images.githubusercontent.com/71535927/147564521-63b8c0ac-7f3e-40c4-a377-284db8a2d554.png)
![image](https://user-images.githubusercontent.com/71535927/147563987-720fa8ec-658a-4496-8274-473597bba885.png)
![image](https://user-images.githubusercontent.com/71535927/147564566-29344e93-e6b0-4ea8-ac70-7d550a116133.png)
![image](https://user-images.githubusercontent.com/71535927/147564900-fe7a4990-829a-45f1-86b6-3cbd1835e069.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added Sonic. Just look at the images in the "Describe your bug here." section.

**Comment by Collabvmisgood** [comment]
did you add the code

**Comment by Collabvmisgood** [comment]
from the wiki

**Comment by cherryiguess** [comment]
its always bf by default, use the code from the wiki, you could also just use character lua files to make it so its used when the character is used

**Comment by ShadowMario** [comment]
Your pants will be shittened when you check the lua script api wiki's examples
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API
