### ISSUE TITLE
Sustains heal even if base note missed

### ISSUE THREAD

**Issue by ItzFireable** [ShadowMario/FNF-PsychEngine#2813]
### Describe your bug here.

The sustains heal you even after missing the original note, letting you to just hold down the key to heal.
This should not be intended behaviour as it lets you just hold down keys to pass anything that includes long notes.

In the example below, I just held down the keys. Pressed a few times but other than that I just held them down and passed it by healing from that mechanic.

Example:

https://user-images.githubusercontent.com/38793386/147571131-0a7dff83-db59-4e88-a8a7-b761b00a964e.mp4

 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by tposejank** [comment]
there is possibily no way to detect the parent note (normal note, not sustain) note from the sustains.
also, why do you care about the input so much do you want fnf to become fucking osu ? its not written in c# idiot

**Comment by ItzFireable** [comment]
> there is possibily no way to detect the parent note (normal note, not sustain) note from the sustains. also, why do you care about the input so much do you want fnf to become fucking osu ? its not written in c# idiot

there is. check kade engine, andromeda, or any other engine for example. 
i don't want the engine to "become osu", i want the engine to be playable and viable for players all around.

**Comment by Rudyrue** [comment]
> there is possibily no way to detect the parent note (normal note, not sustain) note from the sustains.
> also, why do you care about the input so much do you want fnf to become fucking osu ? its not written in c# idiot

the input system is completely fucking broken

you saw on my issue that the so called "anti-mash" was in the game, EVEN THOUGH i could literally just barely try to slam my fingers on the keyboard and hit sustains perfectly

there should be no reason to defend this input system, unless you pull the "he wants it that way" card out of your ass again

**Comment by MarkimusZer0** [comment]
> there is possibily no way to detect the parent note (normal note, not sustain) note from the sustains. also, why do you care about the input so much do you want fnf to become fucking osu ? its not written in c# idiot

I don't think you get the point of the issue, the point of the issue is to report that long notes aren't working properly, they care about the input because they want the game to be playable and literally not cause issues with charts, for example, look at Rudyrue's issue from a while back with the whack ass inputs on long notes, they're reporting the issue for it to get fixed not to have fnf become osu, plus why does it being written in c# have to do with anything? if anything it helps because haxe has basically the same syntax as that iirc

**Comment by MarkimusZer0** [comment]
> > there is possibily no way to detect the parent note (normal note, not sustain) note from the sustains.
> > also, why do you care about the input so much do you want fnf to become fucking osu ? its not written in c# idiot
> 
> the input system is completely fucking broken
> 
> you saw on my issue that the so called "anti-mash" was in the game, EVEN THOUGH i could literally just barely try to slam my fingers on the keyboard and hit sustains perfectly
> 
> there should be no reason to defend this input system, unless you pull the "he wants it that way" card out of your ass again

i wouldn't say completely broken but the long notes certainly are broken, normal notes are fine

**Comment by tposejank** [comment]
incase thats true, i barely doubt shadow mario will do anything about it
in previous kade engine versions you could still do the same

**Comment by ItzFireable** [comment]
> incase thats true, i barely doubt shadow mario will do anything about it in previous kade engine versions you could still do the same

and it was fixed for obvious reasons

**Comment by tposejank** [comment]
i still highly doubt he will do anything about it
kades antimash is shit the only thing it does is give you a miss when you hit a shit
however spamming psych engine is literally the opposite and makes you miss when you press a key it wasnt the notes data

**Comment by tposejank** [comment]
mostly when you spam in psych the only you get are goods and sicks

**Comment by tposejank** [comment]
and with that thing i mean that shadow mario wont even remove the antimash and he probably doesnt even care about "missing sustain notes if parent note missed" at all

**Comment by ItzFireable** [comment]
> mostly when you spam in psych the only you get are goods and sicks

which shouldn't be the case at all. it should prevent you from doing that. instead it prevents any basic ghost tapping right now.

**Comment by tposejank** [comment]
oh fuck i meant kade

**Comment by ItzFireable** [comment]
it doesn't do that in KE? lol

**Comment by MarkimusZer0** [comment]
> i still highly doubt he will do anything about it kades antimash is shit the only thing it does is give you a miss when you hit a shit
It gives you a miss when you hit a shit to break your combo, kade largely bases it's input system on etterna, which i have heard is a good rhythm game (i prefer quaver tho lol)

**Comment by Rudyrue** [comment]
> i still highly doubt he will do anything about it
> kades antimash is shit the only thing it does is give you a miss when you hit a shit
> however spamming psych engine is literally the opposite and makes you miss when you press a key it wasnt the notes data

it's almost like kade's based off of etterna and etterna does the exact same thing when you hit a bad

**Comment by tposejank** [comment]
![image](https://user-images.githubusercontent.com/81495861/147591810-1309aa1b-b933-4182-8d21-02d0cc8debec.png)
ok get real now

**Comment by Rudyrue** [comment]
> ![image](https://user-images.githubusercontent.com/81495861/147591810-1309aa1b-b933-4182-8d21-02d0cc8debec.png)
> ok get real now

and what are you trying to prove

because that's just psych sustain notes and the whole point of this issue is fixing those

**Comment by tposejank** [comment]
https://user-images.githubusercontent.com/81495861/147592182-3af3bce3-ab55-472b-8a42-a1931c2442d3.mp4

**Comment by Rudyrue** [comment]
> Friday.Night.Funkin._.Psych.Engine.2021-12-28.12-34-23_Trim.mp4

now make it so it doesn't give you 11 misses on 2 notes

**Comment by tposejank** [comment]
so basically no missing sustain notes?

**Comment by Rudyrue** [comment]
> so basically no missing sustain notes?

no, make it so it just misses the parent note and not the child notes, because that literally makes no sense, competitive or not

**Comment by MarkimusZer0** [comment]
> so basically no missing sustain notes?

no, just giving 1 miss per loing note

**Comment by tposejank** [comment]
![image](https://user-images.githubusercontent.com/81495861/147592601-cdc01d7c-957a-43ff-8d28-15c816d2f73c.png)
this?
(noteMiss function)

**Comment by tposejank** [comment]
#2817

**Comment by ItzFireable** [comment]
they should count as a single miss, not as multiple, other than that, its way better than how it was before

**Comment by gaminbottomtext** [comment]
GitHub argument 😎

**Comment by tposejank** [comment]
https://user-images.githubusercontent.com/81495861/147592950-2913e355-5ad8-454e-a506-ebf77a54d64f.mp4

is this result good

**Comment by ItzFireable** [comment]
yep, that is the way they should work.

**Comment by MarkimusZer0** [comment]
yeah that looks like about how it should work

**Comment by Rudyrue** [comment]
> Friday.Night.Funkin._.Psych.Engine.2021-12-28.12-45-06.mp4 
> is this result good

you fixed it
good job

**Comment by ItzFireable** [comment]
gonna close this issue after the pr gets updated with the commit, as there is a pull request with a fix available.

**Comment by tposejank** [comment]
#2817 2817

**Comment by ItzFireable** [comment]
pr was updated, closing the issue, check #2817 for a fix.

**Comment by ShadowMario** [comment]
That's not a bug.

**Comment by ItzFireable** [comment]
Shouldn't be intended either.

**Comment by tposejank** [comment]
Stop ranting
go back with your loved engine if you want
![image](https://user-images.githubusercontent.com/81495861/147621740-c48ad11d-6dba-4277-ad98-a67b00ecc9d6.png)

**Comment by tposejank** [comment]
I already gave you a fix if you want pull the PR and build the engine
there you have a ***working kade engine copy***

**Comment by Rudyrue** [comment]
> I already gave you a fix if you want pull the PR and build the engine
> there you have a _**working kade engine copy**_
dude this thread's been dead for a while, leave it alone
