### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by cheemynugget3** [ShadowMario/FNF-PsychEngine#2815]
### Describe your problem here.

Alright I got this

function onUpdate(elapsed)
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.FOUR') then
        endSong();
    end
end

Now what do i do so that instead of ending the song it takes me to a diffrent song?         for example pressing 4 on ___ will take the player to ___

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

added alot of stuff

**Comment by craftersshaft** [comment]
i dont think a function exists right now for swapping to a song, but if you have the most recent source code adding this to FunkinLua works, but plays a transition so don't call it too much at one time:
`		Lua_helper.add_callback(lua, "loadNewSong", function(jsonInput:String, folder:String) {
			trace("trying to load new song " + jsonInput + " from folder " + folder);
			PlayState.SONG = Song.loadFromJson(jsonInput, folder);
			FlxG.sound.music.stop();
			PlayState.cancelMusicFadeTween();
			LoadingState.loadAndSwitchState(new PlayState());
		});`

to use, use a command like `loadNewSong('tutorial-hard', 'tutorial');` . the first parameter is the .json file's name, the second parameter is the folder it's contained in.

**Comment by PDL2CGamejolt** [comment]
> i dont think a function exists right now for swapping to a song, but if you have the most recent source code adding this to FunkinLua works, but plays a transition so don't call it too much at one time:
> 
> ```
> 		Lua_helper.add_callback(lua, "loadNewSong", function(jsonInput:String, folder:String) {
> 			trace("trying to load new song " + jsonInput + " from folder " + folder);
> 			PlayState.SONG = Song.loadFromJson(jsonInput, folder);
> 			FlxG.sound.music.stop();
> 			PlayState.cancelMusicFadeTween();
> 			LoadingState.loadAndSwitchState(new PlayState());
> 		});
> ```
> 
> to use, use a command like `loadNewSong('tutorial-hard', 'tutorial');` . the first parameter is the .json file's name, the second parameter is the folder it's contained in.

is this Lua? or source?

**Comment by craftersshaft** [comment]
it's for source code, might make a pull request or something to add it

**Comment by PDL2CGamejolt** [comment]
> it's for source code, might make a pull request or something to add it

IDK SOURCE CODE

**Comment by SrtHero278** [comment]
> > it's for source code, might make a pull request or something to add it
> 
> IDK SOURCE CODE

JUST COPY PASTE IT INTO `FunkinLua.hx`!

**Comment by cheemynugget3** [comment]
> it's for source code, might make a pull request or something to add it

i need lua
