### ISSUE TITLE
Alt Animation Note now bugs frequently

### ISSUE THREAD

**Issue by ThxSeeYaL8er** [ShadowMario/FNF-PsychEngine#2825]
### Describe your bug here.

I've noticed that since I've moved from v0.4 to v0.5, Alt Animation notes now only work 4/10 times. It varies, but It's also a little annoying.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only tried to use the Alt Animation note

**Comment by ShadowMario** [comment]
Literally your chart's fault cuz it works fine with me
