### ISSUE TITLE
Why doesn't camera zoom work???

### ISSUE THREAD

**Issue by ThxSeeYaL8er** [ShadowMario/FNF-PsychEngine#2826]
### Describe your problem here.

Camera Zooms don't work. The one that is provided with the engine and a different lua I found both don't work with v0.5

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I tried to zoom in the camera in certain parts of the songs

**Comment by ShadowMario** [comment]
Do you have this option turned off?
![Screenshot_5](https://user-images.githubusercontent.com/44785097/147609486-be2995fc-ac0f-4b3d-8e29-bd4e5496db67.png)

**Comment by ThxSeeYaL8er** [comment]
No, I had it checked on.

**Comment by tposejank** [comment]
> Do you have this option turned off? ![Screenshot_5](https://user-images.githubusercontent.com/44785097/147609486-be2995fc-ac0f-4b3d-8e29-bd4e5496db67.png)

you should change "on a beat hit" to "every 4 beats hit" or something like that

**Comment by ShadowMario** [comment]
> you should change "on a beat hit" to "every 4 beats hit" or something like that

No, that's already obvious enough.

**Comment by ShadowMario** [comment]
> No, I had it checked on.

So, are you going to show me how were you using the Camera Zoom event or not?

**Comment by ThxSeeYaL8er** [comment]
> > No, I had it checked on.
> 
> So, are you going to show me how were you using the Camera Zoom event or not?

Apologies, I wasn't home.
![image](https://user-images.githubusercontent.com/79891052/147616476-a280ebc6-cb07-4236-8147-c20289b3f64c.png)

**Comment by tposejank** [comment]
dont put anything in value 2 😐

**Comment by blueDev2** [comment]
Why do you have a comma and 2 values in each box?
I just checked how "Add Camera Zoom" works and it only accepts 1 float value for each box.
This should be the relevant block of code

```
case 'Add Camera Zoom':
if(ClientPrefs.camZooms && FlxG.camera.zoom < 1.35) {
	var camZoom:Float = Std.parseFloat(value1);
	var hudZoom:Float = Std.parseFloat(value2);
	if(Math.isNaN(camZoom)) camZoom = 0.015;
	if(Math.isNaN(hudZoom)) hudZoom = 0.03;

	FlxG.camera.zoom += camZoom;
	camHUD.zoom += hudZoom;
}
```
