### ISSUE TITLE
Mods Not Appearing in HTML5 Build

### ISSUE THREAD

**Issue by TechnicTom22** [ShadowMario/FNF-PsychEngine#2827]
### Describe your bug here.

I made a Psych Engine FNF mod, and everything works fine when I compile to Windows, but when I compile to HTML5, nothing I added shows up in-game.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added new songs, characters, and week.

**Comment by cherryiguess** [comment]
html5 doesn't support lua, also it sucks
