### ISSUE TITLE
discord_rpc when doing lime test windows

### ISSUE THREAD

**Issue by harisshaukat96** [ShadowMario/FNF-PsychEngine#283]
every time i do lime test windows on the physch engine source code on cmd (command prompt) it gives me a error

ERROR: could not find haxelib "discord_rpc", would you like to install it? i try doing lime install discord_rpc or haxelib install discord_rpc it doesnt work, i have tried downloading the source code and installing it from there but it gives me a error and says there is no file called "project.xml" in the files. does anybody have a solution?

**Comment by ShadowMario** [comment]
`haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc`
Next time read FNF's Readme 😐
