### ISSUE TITLE
Allow Mods to be Cross-Compatible With Each Other

### ISSUE THREAD

**Issue by viccycakes** [ShadowMario/FNF-PsychEngine#2835]
### What feature do you want to get added on the base engine?

When two mods are enabled, and a song from one of the two mods is loaded and the debug menu is entered, the second mod's assets (characters) will not be available to choose in the player, gf, and opponent selection menus. The same happens in songs from the base game--no matter what mods are enabled, none of the mods' characters will be available to choose in the debug menu. Although I did not yet test it, this may apply to songs as well.

I discovered this because I am attempting to create a toggleable reskin mod to put over Boyfriend. While I have not yet written scripts for the game to automatically use the assets when loading any song (mod or base game) like I want the mod to do, I wanted to make sure the sprites worked when used. I planned to use the debug menu for this but, as described, the sprites were not available to choose in the dropdown menus.

Since creating these new toggleable mods and their own folders will soon become the norm for most/all Psych Engine mods, I suggest that cross-compatibility between enabled mods and between mods & the base game should be implemented into the engine. Additionally, this feature was already available in pre-0.5 versions of Psych due to the nature of the engine's mod file organization, meaning that restoring this feature would return some currently-missing features to this new version of Psych.

**Comment by ProgramerGamerZone** [comment]
That is what's supposed to happen

**Comment by viccycakes** [comment]
> That is what's supposed to happen

Do you mean that cross-compatibility is supposed to work and this is a bug, or that cross-compatibility is purposely nonexistent?

**Comment by ProgramerGamerZone** [comment]
> 

The latter

**Comment by viccycakes** [comment]
> The latter

What? That's weird. Seems pretty counterintuitive.

**Comment by ProgramerGamerZone** [comment]
> > The latter
> 
> What? That's weird. Seems pretty counterintuitive.

They did it because some mods may have same song names and same character names

**Comment by viccycakes** [comment]
> They did it because some mods may have same song names and same character names

I don't see why that couldn't be avoided by having users rename the files or programming something to recognize the distinction between assets from different mods (while still letting them coexist).
Shutting down the possibility of cross-compatibility feels like a lazy and opportunity-killing way to solve this.

**Comment by ShadowMario** [comment]
Could cause multiple issues due to how Addons/Modpacks work.
