### ISSUE TITLE
Custom Achivements 0.5

### ISSUE THREAD

**Issue by Maxstar13** [ShadowMario/FNF-PsychEngine#2836]
### Describe your problem here.

Im new to code and i cant find any tutorial on how to code achivements in 0.5 so yeah help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Sussyboyamogus** [comment]
This a same as 4.2
