### ISSUE TITLE
How to Add A White Flash Event?

### ISSUE THREAD

**Issue by ItzEpicstickman** [ShadowMario/FNF-PsychEngine#2837]
### Describe your problem here.

I want to know how to add a white flash in psych engine by source code or by build if we can

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by zQ86X** [comment]
With Lua, use the cameraFlash() function
To create a white flash event you would do `cameraFlash("game", "0xFFFFFFFF", 1, true)`, "game" being the camera (camGame) which you could change to hud or other, "1" being the duration of the flash, and "true" being if it's forced

**Comment by ItzEpicstickman** [comment]
> With Lua, use the cameraFlash() function To create a white flash event you would do `cameraFlash("game", "0xFFFFFFFF", 1, true)`, "game" being the camera (camGame) which you could change to hud or other, "1" being the duration of the flash, and "true" being if it's forced

thanks

**Comment by ItzEpicstickman** [comment]
but we have to write the code in the stage's lua?

**Comment by ItzEpicstickman** [comment]
or in custom events?

**Comment by blueDev2** [comment]
custom events
