### ISSUE TITLE
Characters such as Mom or GF with large spritesheets turn into black boxes.

### ISSUE THREAD

**Issue by SpookLad** [ShadowMario/FNF-PsychEngine#2845]
### Describe your bug here.

For some reason this issue isn't happening with anyone else (that I've heard)
It's not a memory issue, nor is it an FNF issue, this is specifically happening with psych engine.
The character still functions as per usual, and the frames are the size they should be. It doesn't crash the game either.
If you do know a way to fix this, or if you realize I'm being dumb, please let me know.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added a song and a week at the time of the glitch.

**Comment by tposejank** [comment]
you have no ram.

**Comment by ShadowMario** [comment]
Your PC sucks.
