### ISSUE TITLE
How can i change Notes style in midsong?????

### ISSUE THREAD

**Issue by Den198888** [ShadowMario/FNF-PsychEngine#2846]
### Describe your problem here.

how can i change notesstyle using script.lua because I've tried this

       function onStepHit()

    if curStep == 904 then
               for i = 1, getProperty('unspawnNotes.length')-1 do
		setPropertyFromGroup('unspawnNotes', i, 'noteStyle', 'newnote');
    end
end

and i got an  error at line 1 'function' (on lua error)
help :(

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by Soufon** [comment]
```
function onStepHit()
    if curStep == 904 then
           for i = 0, getProperty('unspawnNotes.length')-1 do
	   setPropertyFromGroup('notes', i, 'noteStyle', 'newnote');
           end
    end
end
```
Try this.

**Comment by ProgramerGamerZone** [comment]
HE IS MAKING ENDLESS
I can tell by the curStep you put in am I right?

**Comment by RinZleR121** [comment]
Try this one, it is working for me.
```
function onStepHit()
	if curStep >= 904 then
		for i = 0, getProperty('unspawnNotes,length')-1 do
			if getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' then
				setPropertyFromGroup('unspawnNotes', i, 'texture', 'newnote', 'newnote');
			end
		end
	end
end
```
