### ISSUE TITLE
merging mod difficulties into a chart

### ISSUE THREAD

**Issue by BombasticTom** [ShadowMario/FNF-PsychEngine#2861]
### What feature do you want to get added on the base engine?

What about making a feature that merges 2 charts into one as a new difficulty (example: blammed and blammed neo version)? Imagine adding blammed neo's chart and music into mods folder, and then for the game to automatically merge it into one song (if it's neo difficulty, it will add it into a seperate difficulty and give it it's song that would need to include Inst-neo.ogg and Voices-neo.ogg)

**Comment by BombasticTom** [comment]
also can I overwrite charts and week json files? I can't seem to do it.

**Comment by PDL2CGamejolt** [comment]
you can

**Comment by PDL2CGamejolt** [comment]
idk how to explain it

**Comment by BombasticTom** [comment]
> you can

I did something similar, but now in the freeplay menu there are 2 versions of the same song with different instrumentals, vocals and charting.

**Comment by PDL2CGamejolt** [comment]
make a custom difficulty and make a separate song out of it

**Comment by tposejank** [comment]
edit jsons
im not gonna explain
