### ISSUE TITLE
Botplay and practice mode aren't on the pause menu in 0.5.1

### ISSUE THREAD

**Issue by Snans101** [ShadowMario/FNF-PsychEngine#2866]
### Describe your bug here.

in the changelog on gamebanana it said botplay and practice mode were added back but they are still not there

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by BombasticTom** [comment]
it's only when you enter charting state

**Comment by BombasticTom** [comment]
https://user-images.githubusercontent.com/85838311/147697233-8a1ed2ed-054e-4816-92d4-eded140cc53d.mp4

**Comment by Gui-iago** [comment]
it's not a bug, it's an anti cheat basically, you can't enable those things on normal mode anymore

git gud lol

**Comment by tposejank** [comment]
they also made it so you can't get achievements when you enter the charting editor

git gud lol x2
