### ISSUE TITLE
something's aren't working

### ISSUE THREAD

**Issue by WayneSmith64** [ShadowMario/FNF-PsychEngine#2871]
### Describe your bug here.

Week 1 stagecurtains & stage_light are gone, Week 3 sky & behindTrain are gone, Week 4 bgLimo, limoDancer & the entire gore folder are gone, Week 5 bgEscalator & upperBop are gone, and Week 6 bgFreaks & bgGhouls are gone.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by tposejank** [comment]
you have low quality on, idiot

**Comment by WayneSmith64** [comment]
ok
