### ISSUE TITLE
Can't Compile - Type not found : flixel.util.FlxDirectionFlags and other stuff

### ISSUE THREAD

**Issue by Idunno1** [ShadowMario/FNF-PsychEngine#2874]
### Describe your bug here.

It's quite simple, even in Admin command prompt, I just can't build the latest source code. I have Haxe version 4.2.4 and luajit 0.0.4 installed, along with the rest of the dependencies, but can't build this version for some reason. I can build my other project just fine, though.

To be clear, this is an issue with the main branch.

Edit: it happens with source code 0.5.1 as well

### Command Prompt/Terminal logs (if existing)

```bash
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:11: characters 8-37 : Type not found : flixel.util.FlxDirectionFlags
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:484: characters 21-25 : Unknown identifier : WALL
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:504: characters 21-25 : Unknown identifier : WALL
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:530: characters 21-28 : Unknown identifier : CEILING
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:550: characters 21-26 : Unknown identifier : FLOOR
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I have not made any changes, I just downloaded the current source code.

**Comment by tposejank** [comment]
you might have not installed a library

**Comment by blueDev2** [comment]
Since the error message indicates that "addons" were not found, you may need to use the command 
`haxelib install flixel-addons` in the command prompt

**Comment by Idunno1** [comment]
> Since the error message indicates that "addons" were not found, you may need to use the command `haxelib install flixel-addons` in the command prompt

That did not work, unfortunately. I don't see how missing a library changes things, but I am stupid, so I dunno.

**Comment by GrimSigma** [comment]
I'm having the exact same issue as Idunno and i know i have flixel-addons installed, i've uninstalled and reinstalled everything multiple times and have had no problem using other engines but can't seem to get past this and would prefer to use Psyche Engine
