### ISSUE TITLE
Scripts Problem

### ISSUE THREAD

**Issue by TheHalfBunnyLXKD** [ShadowMario/FNF-PsychEngine#2876]
### Describe your bug here.

i've deleted a script from the mods folder, but the script is still being loaded

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited alot of stuff.

**Comment by tposejank** [comment]
restart the game

**Comment by ShadowMario** [comment]
You probably have a duplicate of the lua script somewhere.
