### ISSUE TITLE
different Note style for opponent

### ISSUE THREAD

**Issue by Trenton0** [ShadowMario/FNF-PsychEngine#2883]
### Describe your problem here.

I know another person asked the same question but how do you make the opponent notes different from bf's

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no i didn't however i am using the extrakeys mod

**Comment by ShadowMario** [comment]
Change `texture` property from opponent strums and notes.
For more information check the Lua Script API's "Custom Note Type" example.
The opponent Strum group variable name is called `opponentStrums`, you can change it with setPropertyFromGroup
