### ISSUE TITLE
My credit doubled itself

### ISSUE THREAD

**Issue by TamirPlaysYoutube** [ShadowMario/FNF-PsychEngine#2886]
### Describe your bug here.

My credit doubled itself in game

in credits.txt: Creator Of Ultra64 Funkin'
TamirPlays YT::tamirplaysyt::Creator, Artist, Animator and more::https://www.youtube.com/channel/UCgQ584rWJCsvjk26EBR1Rgw::0xFFFFFB00, I SWEAR

how to make it only one?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added my credit

**Comment by ShadowMario** [comment]
You might have saved it in multiple folders.
