### ISSUE TITLE
I need help with compiling.

### ISSUE THREAD

**Issue by echoxlerbite** [ShadowMario/FNF-PsychEngine#2889]
### What is your question?

Hello, I'm new to psych engine coding, I've done everything correctly up to this point, and everytime i try to compile this error shows up, what am i doing wrong, help would be appriciated.
![Screenshot 2021-12-30 113550](https://user-images.githubusercontent.com/79811444/147749765-41f0473d-ef39-4727-94e1-53da0b0f48af.png)

**Comment by tposejank** [comment]
not an error

**Comment by tposejank** [comment]
https://twitter.com/bbsub3/status/1475872689160085509

**Comment by echoxlerbite** [comment]
@tposejank Thank you for the advice, but it seems to be making more errors.
![Screenshot 2021-12-30 130147](https://user-images.githubusercontent.com/79811444/147754434-2b14292b-1377-49ab-810b-c7c6bfd1d556.png)

**Comment by ShadowMario** [comment]
The lime test command is written wrong.

Use this: `lime test html5 -debug`

Also HTML5 sucks and you probably shouldn't use it.
