### ISSUE TITLE
Lua code wont work despite seeming completely finished

### ISSUE THREAD

**Issue by Lemonemy** [ShadowMario/FNF-PsychEngine#2890]
### Describe your problem here.

im trying to recreate the expurgation tricky stop signs as a lua event, im pretty sure everything is correct, but im obviously wrong since the stop signs wont show up in game. offsets are correct too

![image](https://user-images.githubusercontent.com/88488095/147750513-540ea61f-5b7e-4f31-94e4-4ce217dd3313.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by blueDev2** [comment]
Is it making the "confirmMenu" sound?

**Comment by ShadowMario** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/44785097/147897671-68683618-db20-44fa-b86a-517f7f6cc61d.png)
precache, not preCache
