### ISSUE TITLE
Random misses constantly

### ISSUE THREAD

**Issue by KadeDev** [ShadowMario/FNF-PsychEngine#29]
Looks like when ever you hit a note slightly late, it counts as a miss for some reason (probably because of note.tooLate? also when looking closer at note.hx I realized the early hit window is like vanilla, which doesn't exist.)

anyways i'll be trying to fix this later today, but I just wanted to make this post to let you know.

it really makes scores impossible to grind for, really hard to play.

(getting a random miss looks like this, the note gets judged but noteMiss is still called)
![image](https://user-images.githubusercontent.com/26305836/132410252-49096f3b-2688-4af5-9b51-18985d333de9.png)

**Comment by Slyceth** [comment]
When you hit such a note too late which doesn't count, do you still visually get a note splash along with the "sick!"?

**Comment by ShadowMario** [comment]
Didn't saw that issue earlier, try out the Main repo.

**Comment by KadeDev** [comment]
> When you hit such a note too late which doesn't count, do you still visually get a note splash along with the "sick!"?

I think that might be the issue, since the late window isn't as big as the early window it would obviously fuck people up. This is a vanilla bug as well, though it doesn't show up as a judgement. which leads me to believe the judging of notes is fucked. (Probably a missNote being called even when the note gets judged, aka a call to popUpScore)

**Comment by KadeDev** [comment]
> Didn't saw that issue earlier, try out the Main repo, i've done some input changes lately.

fixed but no early hit window, unplayable.

i'm jokin lol.

https://github.com/ShadowMario/FNF-PsychEngine/pull/33 -> early hit window PR.
