### ISSUE TITLE
Handle chart difficulties that do not exist

### ISSUE THREAD

**Issue by i-winxd** [ShadowMario/FNF-PsychEngine#2902]
### What feature do you want to get added on the base engine?

As of right now (assuming this hasn't been fixed), if you select a difficulty that doesn't exist, an error message like this pops up, then the game crashes (likely due to unhandled exceptions).
![image](https://user-images.githubusercontent.com/31808925/147770770-96e42bad-9ac5-4133-8eda-4f8582d9b30b.png)
It may be necessary for this error to be handled - as of right now, if a charter is too lazy to make all three difficulties, they'll have to copy existing charts three times and name them. While this isn't too time consuming, it is a bit annoying if someone is making multiple mods, which could make the entire mod take up additional space.

Right now, the best method is to search for the hardest of easy / normal / hard jsons that exist within a song(I don't know the quirks of dealing with additional custom-coded difficulties). For example, if looking for SONGNAME-easy.json fails, check for SONGNAME-hard.json then SONGNAME.json. Make sure any exceptions from these are handled should they arise.

**Comment by Soufon** [comment]
This was actually a thing pre-0.5, I assume it got changed due to the new softcoded extra difficulty system.
