### ISSUE TITLE
Getting a game over crashes the game

### ISSUE THREAD

**Issue by JustinSolstice** [ShadowMario/FNF-PsychEngine#2906]
### Describe your bug here.

When doDeathCheck is called the game freezes for a few seconds and then crashes

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added health loss when enemy hits a note

**Comment by blueDev2** [comment]
Is there any specific error pop up that comes after the crash?
