### ISSUE TITLE
Oh no!

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#2907]
### Describe your bug here.

Idk how to describe it!
![2021-12-30 (4)](https://user-images.githubusercontent.com/94698464/147777916-802f0654-b162-4349-baed-21130732b83a.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no response

**Comment by tposejank** [comment]
song is null :trollface:

**Comment by PDL2CGamejolt** [comment]
i messed around with tutorial and i tried to type 339 pm but it glitched the bpm
