### ISSUE TITLE
problem with "linc_luajit" when i put "lime test windows" #2931

### ISSUE THREAD

**Issue by AlejoFunk** [ShadowMario/FNF-PsychEngine#2932]
### Describe your problem here.

when i put "lime test windows" says this and cant compile the game
![Sin título](https://user-images.githubusercontent.com/95886942/147800359-8a6d5b2a-1efc-4059-9ff1-4068706bf5a3.jpg)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I only edited MainMenuState.hx

**Comment by cherryiguess** [comment]
if im correct, thats for when you need lua installed, use "haxelib install linc_luajit"

**Comment by ShadowMario** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/44785097/147897341-142fc803-0e17-4ee2-8370-0a03b67f3398.png)
deadass
