### ISSUE TITLE
What does the vortex editor colors do?

### ISSUE THREAD

**Issue by JavoniCraft** [ShadowMario/FNF-PsychEngine#2933]
### What is your question?

When I have the vortex editor mode on, it's has the ability to change color when I press the arrow keys, what does this mean?

**Comment by tposejank** [comment]
press up and down arrow keys.

**Comment by 4wdthinks** [comment]
he asked what does this mean not how

**Comment by JordanSantiagoYT** [comment]
the vortex editor allows you to skip in various step amounts when the up arrow or down arrow key is pressed.

Default (Red) - 4 steps
Blue - 2 steps
Purple - 1.33 steps
Yellow - 1 step
Orange - 0.5 steps
