### ISSUE TITLE
How do you make it so when you press 7 it brings you to a different song?

### ISSUE THREAD

**Issue by NeverNoodle** [ShadowMario/FNF-PsychEngine#2934]
### Describe your problem here.

I'm trying to make it so when you press 7 to try and go into debug mode, it will just load up a different song, let's say for example you want to make Tutorial make you load into Dadbattle upon pressing 7 trying to go to debug.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added a mod folder with songs and just basic mod stuff.

**Comment by Rorutop** [comment]
pretty sure to load chart of song, it could be `PlayState.SONG = Song.loadFromJson('songname', 'library folder');`

**Comment by Rorutop** [comment]
wait no you're using lua so IDK

**Comment by NeverNoodle** [comment]
man

**Comment by NeverNoodle** [comment]
i found this code from an earlier question
function onUpdate(elapsed)
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
        endSong();
    end
end

but i wanna know if i can change the endSong(); to just load a different song instead

**Comment by Ninjatintin** [comment]
So do you mean like when you press 7 on supernovae or glitch it will just bring you to cheating?

**Comment by NeverNoodle** [comment]
@Ninjatintin yes, exactly

**Comment by Peeyos1** [comment]
if (FlxG.keys.justPressed.SEVEN)
		{
			switch (curSong.toLowerCase())
			{
				case 'cheating':
					PlayState.SONG = Song.loadFromJson("[songname]", "[songname]"); //
					FlxG.save.data.[songname]Found = true;
					FlxG.switchState(new PlayState());
					return;

**Comment by NeverNoodle** [comment]
@Peeyos1 im doing this with lua

**Comment by SonxaiDev** [comment]
> ```
> 	if (FlxG.keys.justPressed.SEVEN)
> 	{
> 		switch (curSong.toLowerCase())
> 		{
> 			case 'cheating':
> 				PlayState.SONG = Song.loadFromJson("[songname]", "[songname]");
> 				FlxG.save.data.[songname]Found = true;
> 				FlxG.switchState(new PlayState());
> 				return;
> ```
> 
> Paste between [lines 2555-2565](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/PlayState.hx#L2555-L2565).

ok so after if i change the name of the song cheating to my own song name, it will make the press 7 thingy work on my song right?

**Comment by NeverNoodle** [comment]
turns out i cant do it with lua

damn

**Comment by Thedumbdude** [comment]
you can by copying this into you .lua file

function onUpdate()
        if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
	      loadSong('the name of the song you want' 'the difficulty you want for the song')
        end
end

**Comment by sonicfan888** [comment]
Hey. This is for 0.5.1 so idk about 0.5.2 yet (it added new lines)
however your code should look like this in 0.5.1
function openChartEditor()
	```
{
		persistentUpdate = false;
		paused = true;
		cancelMusicFadeTween();
		CustomFadeTransition.nextCamera = camOther;
		if (FlxG.keys.justPressed.SEVEN)
			{
				switch (curSong.toLowerCase())
				{
					case 'polyphone':
						PlayState.SONG = Song.loadFromJson("epitome", "epitome");
						FlxG.switchState(new PlayState());
						return;
		MusicBeatState.switchState(new ChartingState());
		chartingMode = true;

		#if desktop
		DiscordClient.changePresence("Chart Editor", null, null, true);
		#end
	}

}

	}
```

**Comment by envypaw** [comment]
> > turns out i cant do it with lua
> > damn
> 
> maybe im gonna do a function that work with lua ;> just need to figure out how can i make a song load when you already in a song (in haxe)

noel this post has been dead for so long 
the thing's been updated and people have done it with lua themselves,

check https://github.com/ShadowMario/FNF-PsychEngine/issues/5912
