### ISSUE TITLE
Link Character Config files into one

### ISSUE THREAD

**Issue by BeastlyGhost** [ShadowMario/FNF-PsychEngine#2944]
### What feature do you want to get added on the base engine?

Linking two config files into one would be useful if, for example, you wanted to make a character that has an opponent variant and a player variant, but at the same time you don't want to have 2 files of that same character in your mods (or assets) directory

could be something like this
```

{
	"animations": [
		{
			stuff
			],
			... ... ...
			
{
	"animations-opponent": [
		{
			stuff
			],
			"no_antialiasing": bool,
	"image": "path/to/image",
	"position": [
		stuff
	],
	... ... ...
```

would this make the file bigger? it would, but honestly would make things easier
there could be a checkbox on the character editor for that, and along with it, if it wasn't checked, it would just use the old config method which just works without any issues whatsoever

**Comment by ImaginationSuperHero528** [comment]
No for making player and opponent stuff it just needs 4 offsets for all animations cause 2 of them would be for when a player and opponent would use the other 2 but for like having a death animation linked would be cool including sprites that Adobe says is too big this be useful for people who can't get the timing down on play animation and change character.
