### ISSUE TITLE
Change a song by difficulty

### ISSUE THREAD

**Issue by TEKBot101** [ShadowMario/FNF-PsychEngine#2950]
### What is your question?

Is it possible to make a song that changes by difficulty? (like bnb mod, in jump-out EX the song changes)

**Comment by glitchygmr** [comment]
go to the difficulty json you want a different song to play on, where it says "song": "jump out",
write something like "jump out ex".
go to the songs folder and make a folder called jump-out-ex and add the inst and vocal files there.

**Comment by TEKBot101** [comment]
thanks, CadencetheSmart

**Comment by TEKBot101** [comment]
Hello, when i go to Change Difficulty and choose my new difficulty it
crashes, also the difficulty image won't be shown instead it shows a
duplicate image of hard or easy.
