### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by echoxlerbite** [ShadowMario/FNF-PsychEngine#2953]
### What is your question?

so, I'm compiling from a new build, the previous build that i was (using same build of the engine I was compiling from)worked and compiled just fine but this one is giving me this, i do not get this, help or answers  would be helpful!
![Screenshot 2021-12-31 145344](https://user-images.githubusercontent.com/79811444/147837548-73608ebf-db10-4b18-89d6-ab44280123be.png)

l

**Comment by Collabvmisgood** [comment]
use the terminal tasks don't work right

**Comment by echoxlerbite** [comment]
@Collabvmisgood, thank you for the suggestion , it worked!
your a life saver.
