### ISSUE TITLE
Error help

### ISSUE THREAD

**Issue by FoxyGamer1980** [ShadowMario/FNF-PsychEngine#2955]
### Describe your problem here.

when i try to build the game by doing lime test windows, it always keeps saying: source/PlayState.hx:2247: characters 3-7 : Expected }

is there a way to fix it?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i'm trying to code in winning icons by editing HealthIcon.hx and PlayState.hx

**Comment by Collabvmisgood** [comment]
you are missing this } put in a line down

**Comment by FoxyGamer1980** [comment]
where at in this? if (health > 2)
			health = 2;

		if (healthBar.percent < 20)
			iconP1.animation.curAnim.curFrame = 1;
			iconP2.animation.curAnim.curFrame = 2;
		else
			iconP1.animation.curAnim.curFrame = 0;
			iconP2.animation.curAnim.curFrame = 0;

		if (healthBar.percent > 80)
		    iconP1.animation.curAnim.curFrame = 2;
			iconP2.animation.curAnim.curFrame = 1;
		else
		    iconP1.animation.curAnim.curFrame = 0;
			iconP2.animation.curAnim.curFrame = 0;

**Comment by Collabvmisgood** [comment]
```
	if (healthBar.percent < 20)
		iconP1.animation.curAnim.curFrame = 1;
		iconP2.animation.curAnim.curFrame = 2;
	else {
		iconP1.animation.curAnim.curFrame = 0;
		iconP2.animation.curAnim.curFrame = 0;
    }
	if (healthBar.percent > 80) {
	    iconP1.animation.curAnim.curFrame = 2;
		iconP2.animation.curAnim.curFrame = 1;
    }
	else {
	    iconP1.animation.curAnim.curFrame = 0;
		iconP2.animation.curAnim.curFrame = 0;
    }
            
```

**Comment by FoxyGamer1980** [comment]
now the icons are stuck, they won't change

**Comment by SharkSonic45** [comment]
> ```
> 	if (healthBar.percent < 20) {
> 		iconP1.animation.curAnim.curFrame = 1;
> 		iconP2.animation.curAnim.curFrame = 2;
>            }
> 	else {
> 		iconP1.animation.curAnim.curFrame = 0;
> 		iconP2.animation.curAnim.curFrame = 0;
>     }
> 	if (healthBar.percent > 80) {
> 	    iconP1.animation.curAnim.curFrame = 2;
> 		iconP2.animation.curAnim.curFrame = 1;
>     }
> 	else {
> 	    iconP1.animation.curAnim.curFrame = 0;
> 		iconP2.animation.curAnim.curFrame = 0;
>     }
>             
> ```
 
Can you please help me with my problem please.
