### ISSUE TITLE
Does mp3 work?

### ISSUE THREAD

**Issue by Collabvmisgood** [ShadowMario/FNF-PsychEngine#2956]
### What is your question?

I don't want to convert an mp3 file to Ogg. So I want to know.

**Comment by CrusherMods** [comment]
I dont think so no

**Comment by Collabvmisgood** [comment]
Found out 
![image](https://user-images.githubusercontent.com/76410593/147839216-1724edcf-b589-4017-bb0d-d659229243ce.png)
