### ISSUE TITLE
Fading out Lua Sprites

### ISSUE THREAD

**Issue by DummyPointPog** [ShadowMario/FNF-PsychEngine#2958]
### Describe your problem here.

Hey! Would there be a Way to Fade out the Lua Sprites, I'm Trying it out right now and it isn't Doing Anything

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

The Mod Team is Only Using Lua, I Dunno Why

**Comment by BeansCool54** [comment]
``function onEvent(name, value1, value2)
	if name == 'Event name' then
		duration = tonumber(value1);
		if duration < 0 then
			duration = 0;
		end

		targetAlpha = tonumber(value2);
		if duration == 0 then
			setProperty('objectname.alpha', targetAlpha);
		else
			doTweenAlpha('amogusnotfunni', 'objectname', targetAlpha, duration, 'linear');
		end
	end
end

**Comment by BeansCool54** [comment]
function onEvent(name, value1, value2) 
	if name == 'Event name' then
		duration = tonumber(value1);
		if duration < 0 then
			duration = 0;
		end

		targetAlpha = tonumber(value2);
		if duration == 0 then
			setProperty('objectname.alpha', targetAlpha);
		else
			doTweenAlpha('amogusnotfunni', 'objectname', targetAlpha, duration, 'linear');
		end
	end
end 
This might help

**Comment by BeansCool54** [comment]
`function onEvent(name, value1, value2)
	if name == 'Event name' then
		duration = tonumber(value1);
		if duration < 0 then
			duration = 0;
		end

		targetAlpha = tonumber(value2);
		if duration == 0 then
			setProperty('objectname.alpha', targetAlpha);
		else
			doTweenAlpha('name', 'objectname', targetAlpha, duration, 'linear');
		end
	end
end`

**Comment by XS09-dev** [comment]
Probs a custom event. Also I recommend getting a source coder and keeping your main coder and label him as the lua coder. The source coder is good to get incase you wanna change the main menu, title screen, story menu, or freeplay menu in any way that isn't possible in lua like moving the logo in the middle and removing gf or adding a sprite in main menu, story menu, or freeplay menu. But most importantly dialogue or a cutscene. So make the dialogue in game than add it to the data and go into play state and add the code for starting the dialogue there. Same with cutscene besides making it and and putting it in data. Lua coders are good for the main focus of the engine. Characters, charting, events, notetypes, stages, and etc.

**Comment by KutikiPlayz** [comment]
doTweenAlpha
