### ISSUE TITLE
Tweens Only Working Once

### ISSUE THREAD

**Issue by TristonShaw** [ShadowMario/FNF-PsychEngine#2961]
### Describe your bug here.

I'm pretty sure this is a bug with the engine. Any time I try to use tweens to change the angle of an object (doTweenAngle(), noteTweenAngle) more than once, the object is only tweened once and remains static for the rest of the song.
Like in endless, during the double note spins, using the MoveArrow event by @itscapp, when I put 2 events, each identical, for each note, the notes only spin once.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by ShadowMario** [comment]
You're using tweens improperly, that's not an engine issue.
