### ISSUE TITLE
Back As Difficulty / Cant Change Bf Strums?

### ISSUE THREAD

**Issue by B01Coding** [ShadowMario/FNF-PsychEngine#2962]
### Describe your bug here.

1.Error in menu
2.Idk someone said this in discord i need if is real or not

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, EX BF(Bob a Bullshit) and Tails (Triple Trouble ñ)

**Comment by Gui-iago** [comment]
Back was fixed, update your source
Press 7, go to the chart editor, and change the note assets file there
