### ISSUE TITLE
system error

### ISSUE THREAD

**Issue by endergames231** [ShadowMario/FNF-PsychEngine#2977]
### Describe your bug here.

![ij41abdUmB](https://user-images.githubusercontent.com/78095941/147847608-100fc66d-e7a6-4fb7-9db4-dde2c9f33a88.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

...

**Comment by endergames231** [comment]
And BBPanzy you help me that this mistake and not what, why. Answer I am the first to use this engine

**Comment by endergames231** [comment]
And BBPanzy you help me that this mistake and not what, why. Answer I'm using this engine for the first time

**Comment by tposejank** [comment]
disable the antivirus, also spell bbpanzu's name right thats very disrespectful

**Comment by endergames231** [comment]
нету у меня антивирус
