### ISSUE TITLE
adding second weeks appear above the first week

### ISSUE THREAD

**Issue by TwyLikesMakingFNFmods** [ShadowMario/FNF-PsychEngine#2981]
### Describe your problem here.

when I try to add a second week for my mod, it always goes above the first week. please tell me how to fix this problem because idk how to fix this.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I removed all the weeks from the original game and added a week

**Comment by TwyLikesMakingFNFmods** [comment]
nvm I found out how to fix it literally 30 seconds after i wrote this

**Comment by Gui-iago** [comment]
close the issue @TwyLikesMakingFNFmods

**Comment by PDL2CGamejolt** [comment]
CLOSE IT
