### ISSUE TITLE
Is there any way to make a character fly other than vertically?

### ISSUE THREAD

**Issue by cheemynugget3** [ShadowMario/FNF-PsychEngine#2983]
### Describe your problem here.

I mean is there a way to make the character fly but not follow the vertical path

what i mean is there any way a character can fly horizontally or like any sorta path?

I want to make my character fly in this motion

https://user-images.githubusercontent.com/96754156/147855441-15dd8a4f-afbd-44e9-8a1a-f85e98d75121.mp4

I have these lines of code right here

function onUpdate()
songPos = getSongPosition()
local currentBeat = (songPos/5000)*(curBpm/60)
setCharacterY('dad', getCharacterY('dad') + (math.sin(currentBeat) * 2))
end

but im not sure i can change it to make it go any other way

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

added alot of stuff

**Comment by tposejank** [comment]
you do the same thing but on the x.
