### ISSUE TITLE
addLuaSprite by curStep Isn't Working For Some Reason

### ISSUE THREAD

**Issue by bestuff44** [ShadowMario/FNF-PsychEngine#2990]
### Describe your problem here.

I am trying to make a character appear in the middle of the song, and nothing I do is working.

What I'm trying:
![Screenshot 2022-01-01 135910](https://user-images.githubusercontent.com/92215752/147858097-b2525051-1c5f-4602-a2a0-8cf0ad312c7b.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Starmapo** [comment]
'curStep' is a number, not a string. You have to remove the quotation marks. Like this:
`if curStep == 10 then`

**Comment by bestuff44** [comment]
I removed the quotation marks, and it's still not working. Any ideas?

**Comment by AetherLynx** [comment]
3 things, remove the quotations marks in "10".
Also remember that after a comma ( , ) you must put a space.
Do: ```'freddy', 500, 25);'```
Don't ```'freddy',500,25);```

next, it seems the animated lua sprite is incomplete, remake the sprite following this format. (

```
makeAnimatedLuaSprite('sprite tag', 'sprite path', x, y);
addAnimationByPrefix('sprite tag', 'animation tag', 'animation name in xml file', 24, false); --true if you want the animation to loop // false if you don't want it to loop
objectPlayAnimation('sprite tag', 'animation tag');
```

**Comment by bestuff44** [comment]
I've been trying it, but it's still not making the animated sprite appear.  

Here's what it looks like
![image](https://user-images.githubusercontent.com/92215752/147861066-e65484ac-2364-403b-9abc-2c7dc39ea8b1.png)

**Comment by Punkinator7** [comment]
could be that the animation tag and the sprite tag are the same-

**Comment by frantastic24** [comment]
the tags being the same isn't an issue, neither are the commas, have you tried spawning any other sprite on the same coordinates? or maybe just moving it around the stage in case it's out of view?

**Comment by bbpanzu** [comment]
show the entire code

**Comment by bestuff44** [comment]
This is just all of the other objects and characters in the background.



function onCreate()
	-- background shit
    
	

	makeLuaSprite('background','bg',-750,-250)
	addLuaSprite('background',false)

	makeLuaSprite('fence','fence',-1000,340)
	addLuaSprite('fence',false)

	makeAnimatedLuaSprite('zardy','zardy',-200,-100)
    addAnimationByPrefix('zardy','zardy','zary')
	addLuaSprite('zardy',false)
	objectPlayAnimation('zardy','zary',false)

	makeAnimatedLuaSprite('retrospecter','retrospecter',300,100)
    addAnimationByPrefix('retrospecter','retrospecter','retrospecter')
	addLuaSprite('retrospecter',false)
	objectPlayAnimation('retrospecter','retrospecter',false)
	close(true)

	makeAnimatedLuaSprite('blantados','blantados',800,150)
    addAnimationByPrefix('blantados','blantados','blantados')
	addLuaSprite('blantados',false)
	objectPlayAnimation('blantados','blantados',false)
	close(true)

	makeAnimatedLuaSprite('shaggy','shaggy',600,150)
    addAnimationByPrefix('shaggy','shaggy','shaggy')
	addLuaSprite('shaggy',false)
	objectPlayAnimation('shaggy','shaggy',false)
	close(true)

	

	makeAnimatedLuaSprite('flippy','flippy',1200,-100)
    addAnimationByPrefix('flippy','flippy','flip')
	addLuaSprite('flippy',false)
	objectPlayAnimation('flippy','flip',false)

makeAnimatedLuaSprite('amongus','amongus',1050,200)
    addAnimationByPrefix('amongus','amongus','amongus')
	addLuaSprite('amongus',false)
	objectPlayAnimation('amongus','amongus',false)
	close(true)

	makeLuaSprite('lights','light',-100,150)
	addLuaSprite('lights',false)
	scaleObject('lights', 0.5, 0.5)

	makeAnimatedLuaSprite('Pat','Pat',-400,0)
    addAnimationByPrefix('Pat','Pat','Pat')
	addLuaSprite('Pat',false)
	objectPlayAnimation('Pat','Pat',false)
	
	makeAnimatedLuaSprite('maya','maya',-200,-50)
    addAnimationByPrefix('maya','maya','maya')
	addLuaSprite('maya',false)
	objectPlayAnimation('maya','maya',false)
	close(true)

	makeAnimatedLuaSprite('James','James',-600,-50)
    addAnimationByPrefix('James','James','James')
	addLuaSprite('James',false)
	objectPlayAnimation('James','James',false)
	close(true)
	
	makeAnimatedLuaSprite('josh','josh',1300,0)
    addAnimationByPrefix('josh','josh','josh')
	addLuaSprite('josh',false)
	objectPlayAnimation('josh','josh',false)
	close(true)

	makeAnimatedLuaSprite('jenna','jenna',1500,25)
    addAnimationByPrefix('jenna','jenna','jenna')
	addLuaSprite('jenna',false)
	objectPlayAnimation('jenna','jenna',false)
	close(true)

	makeAnimatedLuaSprite('alex','alex',1650,25)
    addAnimationByPrefix('alex','alex','alex')
	addLuaSprite('alex',false)
	objectPlayAnimation('alex','alex',false)
	
	makeAnimatedLuaSprite('freddy', 'freddy', 500, 25);
    addAnimationByPrefix('freddy', 'freddy', 'freddy', 24, true);
	addLuaSprite('freddy', true)
	objectPlayAnimation('freddy', 'freddy', false);
    setProperty('freddy.visible', false);

end

function onStepHit()
	
	if curStep == 10 then
		setProperty('freddy.visible', true);
		end
end

**Comment by frantastic24** [comment]
remove all the 'close(true)', by adding this you're closing the script and preventing any mid-song event from triggering

**Comment by bestuff44** [comment]
> remove all the `close(true)`, by adding this you're closing the script and preventing any mid-song event from triggering

Yo thank you so much bro it worked!!!

**Comment by frantastic24** [comment]
great to hear dude, remember to close this btw
