### ISSUE TITLE
can you create an main menu whits a .lua file "please dont ban me..."

### ISSUE THREAD

**Issue by choctid** [ShadowMario/FNF-PsychEngine#2993]
### What feature do you want to get added on the **base** engine?
édit whits lua the main menu...
the same thing for the stage but for the main menu...
I hope you have understood...

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by tposejank** [comment]
no

**Comment by MeowcaTheoRange** [comment]
basically, edit MainMenuState/StoryMenuState with lua files? That seems possible, to move around the indexes and do stuff without having to touch the source.

Also, you got the sight question wrong. Submit this again with the correct selection please :)
