### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Trenton0** [ShadowMario/FNF-PsychEngine#2994]
### Describe your bug here.

Help

### Command Prompt/Terminal logs (if existing)

```bash
Error: Could not find include file "4.2.1/build-tool/BuildCommon.xml"
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited project.xml and funkin.lua to include .cpp files cause i got bored

**Comment by MeowcaTheoRange** [comment]
Change the include folder to your Haxe version, perhaps.
![image](https://user-images.githubusercontent.com/58280776/147860525-fec81a4c-31e2-4062-b318-39b3b4f2b5d9.png)
