### ISSUE TITLE
highscore doesnt behave properly

### ISSUE THREAD

**Issue by trayfellow** [ShadowMario/FNF-PsychEngine#3]
as you can see in this vid, my highscore in week 3 is 179507, but when i enter and then exit out of the stage, it suddenly changes to 179510

https://user-images.githubusercontent.com/48515908/128623179-e066d14d-597c-44b2-bad7-09dc839359c6.mp4

**Comment by trayfellow** [comment]
update : found another way of doing this, so i scrolled to week 3, and then week 4, and then week 3 again, and the week 3 score wasnt the same as before i scrolled to week 4

https://user-images.githubusercontent.com/48515908/128665782-1463fe39-c3df-4afb-a5f8-9dd9a3e49e93.mp4

**Comment by ShadowMario** [comment]
Fixed on release 0.3: https://github.com/ShadowMario/FNF-PsychEngine/commit/560b66e2f7fff01d2668138ef0e8e72340bd5b03

Thank you for reporting this issue.
