### ISSUE TITLE
custom note snap values

### ISSUE THREAD

**Issue by naether** [ShadowMario/FNF-PsychEngine#3005]
### What feature do you want to get added on the **base** engine?

a number you can change to for example 3 or 7 to make your grid snap to triplets or septuplets of the zoom value
i just want a way to create perfect triplets without having to use 12x zoom

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by bbpanzu** [comment]
you can already kinda with the vortex editor. if you use left and right arrow keys, you can snap to triplets, quarter, 32nd

**Comment by Joanarr** [comment]
I did not know the vortex editor could do that, and that's super helpful. However, it only allows you to chart Eighth triplets, and not Sixteenth triplets, having the option to chart 16th triplets with the vortex editor would, in my opinion, make the Psych engine chart editor the best ever chart editor
