### ISSUE TITLE
custom enemy notes

### ISSUE THREAD

**Issue by pln2009** [ShadowMario/FNF-PsychEngine#3006]
### Describe your problem here.

i was following a tutorial for making custom enemy (link https://github.com/ShadowMario/FNF-PsychEngine/discussions/995) and i got this problem:
source/Note.hx:160: characters 3-5 : Expected }
how do i fix it?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes. note.hx, playstate.hx, strumnote.hx
[Note.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7799014/Note.txt)
[PlayState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7799015/PlayState.txt)
[StrumNote.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7799016/StrumNote.txt)

**Comment by tposejank** [comment]
We won't be able to help you if you don't provide us the code.

**Comment by Luisinhi010** [comment]
Wait? you post the MF "build target", but you didnt post the code? in this way no one can help you :c

**Comment by Luisinhi010** [comment]
Wait? you post the MF build target, but you didnt post the code? in that way no one can help you :c

**Comment by pln2009** [comment]
> We won't be able to help you if you don't provide us the code.

now?

**Comment by ShadowMario** [comment]
[Note.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7800239/Note.txt)

**Comment by pln2009** [comment]
> [Note.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7800239/Note.txt)
thank you

**Comment by pln2009** [comment]
![Immagine 2022-01-03 140216](https://user-images.githubusercontent.com/76397093/147933534-112945b4-421a-42bd-a138-3f9de58ed7b3.png)
well, now there is another problem

**Comment by pln2009** [comment]
> ![Immagine 2022-01-03 140216](https://user-images.githubusercontent.com/76397093/147933534-112945b4-421a-42bd-a138-3f9de58ed7b3.png) well, now there is another problem

i just needed to delete the line that didn't work. now it works
