### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by HapJim** [ShadowMario/FNF-PsychEngine#3010]
### Describe your problem here.

These errors appear in groups or separate when I try to compile the game:
"Error: Context3DElementType.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: Stdout.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: FlxSteamControllerMetadata.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory"

I've followed a tutorial on compiling but still get these errors.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I've added files into the mods folder, but I haven't done any source editing.

**Comment by HapJim** [comment]
Someone also told me that I didn't have Visual Studio 2019 installed, and that's why this error occurs, but I do, so I don't know why this appears.

**Comment by Luisinhi010** [comment]
you need a older version of Visual Studio 2019

**Comment by HapJim** [comment]
how do i get an older version

**Comment by HapJim** [comment]
HOW DO I GET AN OLDER VERSION

**Comment by SrtHero278** [comment]
> Someone also told me that I didn't have Visual Studio 2019 installed, and that's why these errors occur, but I do, so I don't know why this appears.

That's for msvc.

**Comment by ShadowMario** [comment]
You're missing MSVC 2019 libraries. Follow a friday night funkin compiling tutorial from the internet and you should find your answer there.
