### ISSUE TITLE
An error occurred in discord-rpc:Could not clone Git repository

### ISSUE THREAD

**Issue by XueSenXXD** [ShadowMario/FNF-PsychEngine#3012]
### Describe your problem here.

When I installed discord-rpc, an error occurred, and I have uninstalled and installed it many times and still can’t clone
C:\Users\UsersName\Desktop\FNF-PsychEngine-main>haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
Installing discord_rpc from https://github.com/Aidan63/linc_discord-rpc
Error: Could not clone Git repository.
How should i fix it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by HiroMizuki** [comment]
have u downloaded git?

**Comment by XueSenXXD** [comment]
> 

Yes i installed it many times

**Comment by XueSenXXD** [comment]
> 你安装了git吗？
Yes i installed

**Comment by XueSenXXD** [comment]
> did u installed git?

yes i install

**Comment by ShadowMario** [comment]
`haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git`
You had forgotten the ".git" at the end.
