### ISSUE TITLE
I changed a noteskin via lua, Hey and Camera Zoom crash the game

### ISSUE THREAD

**Issue by Punkinator7** [ShadowMario/FNF-PsychEngine#3014]
### Describe your bug here.

I was working on stuff and I tried to do this script as an Event:
`
 function onEvent(name, value1, value2) 
	for i = 0, getProperty('playerStrums.length')-1 do
	
	setPropertyFromGroup('playerStrums', i, 'texture', value1);
	end
end 
`
The texture I had used for Value1 was a noteskin made for the vanilla game, with the xml and everything. after setting up this file I went to test it out on the tutorial, I opened the chart editor and placed the event down, typed in the name of the file in value1, hit enter, and when the event did the thing it worked as intended. but I was only able to get through to the first Hey! as it crashed as the animation played. There are two possibilities, it  was the Hey or the Camera Zoom that crashed it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by Punkinator7** [comment]
oh and I'm using Psych Engine 0.5.1

**Comment by Punkinator7** [comment]
update: I did some further testing and it was the Hey! Event, and also the Note Splashes don't have a public variable for their texture, so I can't change it with lua.

**Comment by tposejank** [comment]
> update: I did some further testing and it was both of them 
> and the Note Splashes don't have a public variable for their texture, so I can't change it with lua.

they do, they are handled by notes. so you can iterate all over them and change their variable `noteSplashTexture`

**Comment by ShadowMario** [comment]
Might be an issue with the note texture actually.

**Comment by Punkinator7** [comment]
alright I'll get a note asset from this github and try it

**Comment by Punkinator7** [comment]
Ok so I got the note texture directly from this github, I got the xml for it too, it shows up fine in-game, but it just crashes still.

**Comment by Punkinator7** [comment]
Even more Update: LinearSpin, which is another event of mine, crashed the game when the noteskin change event was present in the chart...I'm willing to bet the LinearAlpha events also do this too. basically these events spin / change the alpha of  the notes and their receptors, using a tween for both o dem. they didn't do this by themselves so I think the mere presence of that event is crashing the game

**Comment by Punkinator7** [comment]
okay I figured it out. Apparently because I didn't check the events name in any of my events, which in hindsight was really stupid actually, it crashes because it runs the code everytime onEvent is called, and without the check it's basically like slamming your keyboard, everything tries to happen at once. but it works perfectly now that I added the check to all of them, with no problems so I'm gonna close this-
