### ISSUE TITLE
Undo & Redo 

### ISSUE THREAD

**Issue by Ninjatintin** [ShadowMario/FNF-PsychEngine#3016]
### What feature do you want to get added on the **base** engine?

Maybe like a list that saves changes you have made in the chart so in case you make a mistake or something so you can undo or redo (and also something to make it so the game won't crash when there is nothing to undo or redo)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by bbpanzu** [comment]
cool idea. finna add now

**Comment by Ninjatintin** [comment]
> cool idea. finna add now

cool thanks
