### ISSUE TITLE
Quicker Offsetting in character editor

### ISSUE THREAD

**Issue by BeansCool54** [ShadowMario/FNF-PsychEngine#3017]
### What feature do you want to get added on the **base** engine?

The idea is pretty simple. Making it so that when you hold arrow keys it moves automatically and you dont have to mash them.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by HiroMizuki** [comment]
there's already something at the char editor that moves the character 10x faster if u hold it

**Comment by BeansCool54** [comment]
> there's already something at the char editor that moves the character 10x faster if u hold it

I know. What I was trying to say is that it's automatic and you dont need to press the button every time to make the sprite move. You can just hold the arrow keys and it will move

**Comment by HiroMizuki** [comment]
> > there's already something at the char editor that moves the character 10x faster if u hold it
> 
> I know. What I was trying to say is that it's automatic and you dont need to press the button every time to make the sprite move. You can just hold the arrow keys and it will move

ok
well, maybe that's a good idea
