### ISSUE TITLE
Ingame script editor

### ISSUE THREAD

**Issue by NekoDev-cyber** [ShadowMario/FNF-PsychEngine#302]
this may be a bad idea but how about an **ingame script editor** takes the scripts you recently compiled and puts it in a list. pressing enter on one could open notepad or something. and maybe could detect errors within each one. by pressing a certain key within the menu. No expectations though just a thing I wanted to share :3

**Comment by ShadowMario** [comment]
Scripts are compiled on run time, they aren't stored or anything.
I'm trying to figure out how to make it print errors properly but at the moment you can use `debugPrint('test')` to see if the script stopped at some point.
This sounds a bit awkward and not as useful as it would probably end up being.
