### ISSUE TITLE
characters sliding when camera changes

### ISSUE THREAD

**Issue by BrightEyesFox** [ShadowMario/FNF-PsychEngine#3024]
### Describe your problem here.

the characters are sliding whenever the camera switches and it doesnt look very good. this is only happening with the new stage i created, how would i fix this issue?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

just added a custom stage

**Comment by HiroMizuki** [comment]
that's from the main game, maybe you'll need source to fix

**Comment by BrightEyesFox** [comment]
i managed to solve it, i had to change the sprite scrolling to 1 on the ground sprite
