### ISSUE TITLE
I Have Found A Very Annoying Custom Events Bug

### ISSUE THREAD

**Issue by CC-J4xon** [ShadowMario/FNF-PsychEngine#3025]
### Describe your bug here.

I Use The "Change Character" Event, I Do This:

Value 1: Dad
Value 2: amogus-hell

(The Character Is Not Daddy Dearest, But They Are On The Opponent's Side)
It Changes BF To "amogus-hell" Instead Of The Opponent.

So I Try This:

Value 1: amogus
Value 2: amogus-hell

(The Character's Name Is Amogus (The Opponent (The One I Want To Change)))
It **_STILL_** Changes BF To "amogus-hell"

**HELP**

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I Added A Couple Of Custom Events And New Characters

**Comment by Starmapo** [comment]
You have to make value 1 lowercase. Like this:
```
Value 1: dad
Value 2: amogus-hell
```

**Comment by CC-J4xon** [comment]
> You have to make value 1 lowercase. Like this:
> 
> ```
> Value 1: dad
> Value 2: amogus-hell
> ```

Thank You :D
