### ISSUE TITLE
Texture Atlas Crash

### ISSUE THREAD

**Issue by Hunter13n** [ShadowMario/FNF-PsychEngine#3036]
### What is your question?

so i saw that you added 'animateatlas' an dont know how to use it an so i added doxxie as a test an compiled the game an went to a random song an, chart editor an selected doxxie an reloaded the song an crashed did i do something wrong?

![atlas_crash](https://user-images.githubusercontent.com/66497511/147887323-9782a538-f8a0-4964-bcc5-ea7b4b7494c3.png)

i did what BB did but is it different?

**Comment by bbpanzu** [comment]
just fixed. turns out the texture atlas stuff only worked in the mods folder
