### ISSUE TITLE
Character isn't showing up in the Chart Editor.

### ISSUE THREAD

**Issue by MrDucc** [ShadowMario/FNF-PsychEngine#3038]
### Describe your bug here.

I'm trying to make a skin for Boyfriend, but he refuses to appear in the in-game chart editor. He works in the chart editor when I hit 7 on the menu screen, but as soon as I try to use him in-game (like in Blammed), he doesn't show up in the character lists. Even when I tried removing all other mods from the mods folder (they were previously disabled, of course), he still doesn't show up. 

info on my game version:
using the prebuilt version of 0.51 from the releases

### Command Prompt/Terminal logs (if existing)

```bash
N/A
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

N/A

**Comment by tposejank** [comment]
change the mod directory in master editor menu

**Comment by MrDucc** [comment]
not to sound rude, but i specifically said in the post it works when i press 7 on the menu and go chart editor, but not when i play blammed.

**Comment by tposejank** [comment]
THE MOD DIRECTORY (LEFT OR RIGHT)

**Comment by bbpanzu** [comment]
it's cause the bf skin is in a mod directory. when loading base game songs, mods from mod directories won't show up

**Comment by MrDucc** [comment]
oohhh i see. thanks!

**Comment by chrisdoesstuff69** [comment]
> it's cause the bf skin is in a mod directory. when loading base game songs, mods from mod directories won't show up

ok so what do i do
