### ISSUE TITLE
F7 And F8 Dont work

### ISSUE THREAD

**Issue by Diamantitos2** [ShadowMario/FNF-PsychEngine#3049]
### Describe your bug here.

Im actually press F7 And F8 And dont do nothing.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by tposejank** [comment]
not the F keys 💀💀

**Comment by tposejank** [comment]
its 7 and 8 not F7💀💀💀💀💀😬
