### ISSUE TITLE
need help with loading screen

### ISSUE THREAD

**Issue by Bludye** [ShadowMario/FNF-PsychEngine#3052]
### Describe your problem here.

i did some shit to enable the loading screen and now songs refuse to load and are just stuck in the first line of the loading screen

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i did the things people said on issues such as deleting NO_PRELOAD_ALL and #end's

**Comment by ShadowMario** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/1912
That's literally it.

Also the loading screen has no use on Desktop builds.
