### ISSUE TITLE
Randomizing the health with lua

### ISSUE THREAD

**Issue by FoxyGamer1980** [ShadowMario/FNF-PsychEngine#3054]
### Describe your problem here.

Context: i'm making a quick test mod, and i want to have a mechanic in it where when a opponent hits a note, it would randomize the health between 2 and 0.1

is there a way to do so?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i edited the playstate creditsstate, etc

**Comment by ShadowMario** [comment]
```lua
function opponentNoteHit(id, direction, noteType, isSustainNote)
	setHealth(getRandomFloat(0.1, 2));
end
```
There you go
