### ISSUE TITLE
make things appear over the hud without hiding it

### ISSUE THREAD

**Issue by glitchygmr** [ShadowMario/FNF-PsychEngine#3055]
### Describe your problem here.

self explanatory. i want to make sprites appear over the hud without hiding it. how would i do this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing in the base game, just added assets and scripts in the mods/(my mod) folders

**Comment by ShadowMario** [comment]
[setObjectCamera](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#setobjectcameraobjstring-camerastring)

**Comment by glitchygmr** [comment]
thank you! ^^
