### ISSUE TITLE
Sprite Animation

### ISSUE THREAD

**Issue by MarkAwesomeness** [ShadowMario/FNF-PsychEngine#3056]
### Describe your problem here.

I have a sprite in a background using lua, but it will not animate. It has worked for other stages and other images, but not this specific image.

**Heres the lua code:**

`function onCreate()
    --for normal images and sprites.
    makeLuaSprite('yes','layer0', -200, -100)
    addLuaSprite('yes',false) --Do you want your image to be infront of the characters?
    setLuaSpriteScrollFactor('yes', 1, 1)
    --copy this and make changes to add other things.
    
   --for animated things.
   makeAnimatedLuaSprite('SPEAKERS','spookers', -100, 500)
   addAnimationByPrefix('SPEAKERS','SPEAKERS','spookers',24,true) --do you want the animation to loop?
   addLuaSprite('SPEAKERS', false)

    --for normal images and sprites.
    makeLuaSprite('pretty lit','layer1', -200, -125)
    addLuaSprite('pretty lit',false) --Do you want your image to be infront of the characters?
    setLuaSpriteScrollFactor('pretty lit', 1, 1)
    --copy this and make changes to add other things

    makeLuaSprite('bg1', 'dancefloor0', -200, -100);
    makeLuaSprite('bg2', 'dancefloor1', -200, -100);
    makeLuaSprite('bg3', 'dancefloor2', -200, -100);
    makeLuaSprite('bg4', 'dancefloor3', -200, -100);
    makeLuaSprite('bg5', 'dancefloor4', -200, -100);        

end

local images = {
    [0] = function()
       addLuaSprite('bg1', false);
    end,
    [1] = function()
       addLuaSprite('bg2', false);
    end,
    [2] = function()
       addLuaSprite('bg3', false);
    end,
    [3] = function()
       addLuaSprite('bg4', false);
    end,
    [4] = function()
       addLuaSprite('bg5', false);
    end
}

function onBeatHit()
   objectPlayAnimation('SPEAKERS','SPEAKERS',true)--Do you want this animation to be forced?

   random = math.random(0, 4);
   images[random](); 
   
end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MarkAwesomeness** [comment]
Here is the xml

`
<?xml version="1.0" encoding="utf-8"?>
<TextureAtlas imagePath="spookers.png">
	
	
	<SubTexture name="SPEAKERS0000" x="0" y="0" width="2755" height="1001" frameX="0" frameY="0" frameWidth="2756" frameHeight="1001"/>
	<SubTexture name="SPEAKERS0001" x="0" y="1003" width="2751" height="1001" frameX="0" frameY="0" frameWidth="2756" frameHeight="1001"/>
	<SubTexture name="SPEAKERS0002" x="0" y="1003" width="2751" height="1001" frameX="0" frameY="0" frameWidth="2756" frameHeight="1001"/>
	<SubTexture name="SPEAKERS0003" x="0" y="2006" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0004" x="0" y="2006" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0005" x="0" y="3009" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0006" x="0" y="3009" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0007" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0008" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0009" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0010" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0011" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0012" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0013" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0014" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0015" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0016" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0017" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0018" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0019" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0020" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0021" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0022" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0023" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0024" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0025" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0026" x="0" y="4012" width="2756" height="1001"/>
	<SubTexture name="SPEAKERS0027" x="0" y="4012" width="2756" height="1001"/>
</TextureAtlas>
`

**Comment by MarkAwesomeness** [comment]
The issue refuses to put the entire thing into code, so imma just put it here

`function onCreate()
    --for normal images and sprites.
    makeLuaSprite('yes','layer0', -200, -100)
    addLuaSprite('yes',false) --Do you want your image to be infront of the characters?
    setLuaSpriteScrollFactor('yes', 1, 1)
    --copy this and make changes to add other things.
    
   --for animated things.
   makeAnimatedLuaSprite('SPEAKERS','spookers', -100, 500)
   addAnimationByPrefix('SPEAKERS','SPEAKERS','spookers',24,true) --do you want the animation to loop?
   addLuaSprite('SPEAKERS', false)

    --for normal images and sprites.
    makeLuaSprite('pretty lit','layer1', -200, -125)
    addLuaSprite('pretty lit',false) --Do you want your image to be infront of the characters?
    setLuaSpriteScrollFactor('pretty lit', 1, 1)
    --copy this and make changes to add other things


    makeLuaSprite('bg1', 'dancefloor0', -200, -100);
    makeLuaSprite('bg2', 'dancefloor1', -200, -100);
    makeLuaSprite('bg3', 'dancefloor2', -200, -100);
    makeLuaSprite('bg4', 'dancefloor3', -200, -100);
    makeLuaSprite('bg5', 'dancefloor4', -200, -100);        

end

local images = {
    [0] = function()
       addLuaSprite('bg1', false);
    end,
    [1] = function()
       addLuaSprite('bg2', false);
    end,
    [2] = function()
       addLuaSprite('bg3', false);
    end,
    [3] = function()
       addLuaSprite('bg4', false);
    end,
    [4] = function()
       addLuaSprite('bg5', false);
    end
}

function onBeatHit()
   objectPlayAnimation('SPEAKERS','SPEAKERS',true)--Do you want this animation to be forced?

   random = math.random(0, 4);
   images[random](); 
   
end`

**Comment by glitchygmr** [comment]
the 'function onBeatHit()' means that the animation will only play when a note is hit, if thats not whats wanted then that could be the problem

**Comment by glitchygmr** [comment]
> addAnimationByPrefix('SPEAKERS','SPEAKERS','spookers',24,true) --do you want the animation to loop?
this should be `addAnimationByPrefix('SPEAKERS','SPEAKERS','SPEAKERS',24,true) --do you want the animation to loop?`

**Comment by MarkAwesomeness** [comment]
The name of the image is "spookers.png", if that clarifies anything.
