### ISSUE TITLE
Sex mode

### ISSUE THREAD

**Issue by Quement902** [ShadowMario/FNF-PsychEngine#3057]
### What feature do you want to get added on the **base** engine?

Sex mode please bro
would make it way better br0!!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by CrusherMods** [comment]
what the fuck

**Comment by lemz1** [comment]
even if it would have been added you wouldn't be able to get it

**Comment by FoxyGamer1980** [comment]
bro get your mind out of the gutter lol XD

**Comment by MaxlionButMyNameIsTakenSoThisIsmyName** [comment]
shadowmario why did you close this issue this was such an intellectual conversation smh
