### ISSUE TITLE
Maybe add the ability to run lua scripts on the menu?

### ISSUE THREAD

**Issue by FBI-Donut** [ShadowMario/FNF-PsychEngine#3060]
### What feature do you want to get added on the **base** engine?

I wouldn't actually know since I don't work with haxe but I'd imagine that this shouldn't be too difficult to do (assuming it hasn't been already implemented and I'm not just a stupid idiot) but I feel like being able to run lua scripts on the menu so you can add neat menu stuff without using source code would be cool

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by schwiftified** [comment]
they will add a stage editor, but 6K+ or winning icons are a no for them

**Comment by ShadowMario** [comment]
I don't have plans for that at the moment.
