### ISSUE TITLE
discord thing continuation

### ISSUE THREAD

**Issue by schwiftified** [ShadowMario/FNF-PsychEngine#3061]
### What is your question?

how do i create the fnf application?
continuation from #3042

**Comment by trayfellow** [comment]
https://www.youtube.com/watch?v=M57nL_PJxnI you can follow the steps on this tutorial 

btw make sure to wait for like 30 - 60 minutes after uploading ur images and stuff cause when u upload ur images and then refresh it might be gone but just wait for that amount of time and refresh and ur images should be there

(and yes this tutorial works fine with psych engine)
