### ISSUE TITLE
Can you add the ability that allows there to be different note colors per person

### ISSUE THREAD

**Issue by PsychEngineIsPOG** [ShadowMario/FNF-PsychEngine#3063]
### What feature do you want to get added on the **base** engine?

Like… the Bob and Bosip Mod!
Dad has his own color or note type for him and bf has his own color of notes
![B2295BA4-AE61-4361-BA46-56486FEA969F](https://user-images.githubusercontent.com/97011835/147901835-c4e04806-386b-4a49-8e85-965d44143955.png)

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by ShadowMario** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/44785097/147901931-0e9f10f9-5709-4350-9cf6-f02bccaf8ade.png)
🗿
