### ISSUE TITLE
i cant run the latest psych engine 

### ISSUE THREAD

**Issue by anonybean** [ShadowMario/FNF-PsychEngine#3069]
### Describe your problem here.

i didn't even work on psych engine  and this happened to me 

![image](https://user-images.githubusercontent.com/94534428/147923902-8138b5a8-c24b-4c51-9e37-da1836275cca.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MeowcaTheoRange** [comment]
update haxe
