### ISSUE TITLE
how to get rid of 'boyfriend' songs?

### ISSUE THREAD

**Issue by NicklGames** [ShadowMario/FNF-PsychEngine#3072]
### What is your question?

How do i get rid of 'boyfriend' songs in freeplay?
![image](https://user-images.githubusercontent.com/60806448/147939627-3492b96a-c797-4163-aec1-d30728fb37c4.png)

**Comment by SrtHero278** [comment]
find the week and hide it from freeplay.
`assets/weeks`
`mods/weeks`

**Comment by ethannn123** [comment]
he probably just added the song to the FreeplayList.txt file instead of using master

**Comment by NicklGames** [comment]
i did just that

> find the week and hide it from freeplay. `assets/weeks` `mods/weeks`

**Comment by NicklGames** [comment]
> he probably just added the song to the FreeplayList.txt file instead of using master

never used it.

**Comment by NicklGames** [comment]
> find the week and hide it from freeplay. `assets/weeks` `mods/weeks`

oh and also i use sauce code

**Comment by NicklGames** [comment]
ok i actually messed around with weekList.txt and freeplaySongList.txt and theyre gone
