### ISSUE TITLE
Any way to delay the countdown to a certain step in the song?

### ISSUE THREAD

**Issue by AndrewIdot** [ShadowMario/FNF-PsychEngine#3077]
### Describe your problem here.

I'm trying to make the countdown not appear at the start of the song, and then make it appear later at a certain step in the song with modcharts (For context, you can see steps in the chart editor), however I failed. Is it even possible?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, no changes lua related from what I know.

**Comment by i-winxd** [comment]
If it is possible to destroy any sprite that isn't a lua sprite, then the 3, 2, 1, go can be removed from the start. To delay 3, 2, 1, go, you'll have to reconstruct it.
