### ISSUE TITLE
Adding a new difficulty page is outdated

### ISSUE THREAD

**Issue by MayoALT** [ShadowMario/FNF-PsychEngine#3078]
### What needs to be documented?

The page for adding a new difficulty says its only possible on source code when its not anymore

**Comment by ThePsychEngineFan** [comment]
either youre lying, or youre dumb. difficulty is ONLY available on source

**Comment by JVGamerzbz** [comment]
> either youre lying, or youre dumb. difficulty is ONLY available on source

well its true. the adding diff page is outdated. i tested it, then it says

source/CoolUtil.hx:19: lines 19-25 : Array<String> should be String
source/CoolUtil.hx:19: lines 19-25 : Array<String> should be String
source/CoolUtil.hx:19: lines 19-25 : Array<String> should be String
source/CoolUtil.hx:19: lines 19-25 : Array<String> should be String
source/CoolUtil.hx:19: lines 19-25 : Array<String> should be String

fuck adding diff page

**Comment by Lsoissus** [comment]
> either youre lying, or youre dumb. difficulty is ONLY available on source

basically its possible in the week editor, its not available only on source anymore, but you can only add 4 difficulties in the week editor

**Comment by ShadowMario** [comment]
Boop, updated.
