### ISSUE TITLE
Changing health gain and health drain for each note hit and miss?

### ISSUE THREAD

**Issue by FoxyGamer1980** [ShadowMario/FNF-PsychEngine#3079]
### Describe your problem here.

is there a way to change how to change the health gain and health drain in the source code? here's an example i need

Note Hit Sick adds 0.04 to health
Note Hit Good adds 0.03 to health
Note Hit Bad adds 0.02 to health
Note Hit Shit adds 0.01 to health
and a miss subtracts 0.02 to health

this will help for my test mod since in a certain part of the mod, it requires spamming

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i edited the playstate creditsstate, etc

**Comment by KutikiPlayz** [comment]
Just find the code that adds the score and add "health -=/+= whatever the health is"
![Screenshot (1022)](https://user-images.githubusercontent.com/73810550/147970201-a410385f-c711-47d9-8aec-5d7307205433.png)
Here's what I did as an example

**Comment by FoxyGamer1980** [comment]
thanks for the help!, however i already figured it out myself, thanks for the help
