### ISSUE TITLE
Difficulty menu bug

### ISSUE THREAD

**Issue by KacperOSM** [ShadowMario/FNF-PsychEngine#3084]
### Describe your bug here.

When i try to go back to the pause menu when changing difficulties, it'll just say that there is no [SONG]-null.json
![image](https://user-images.githubusercontent.com/81757134/147962350-04dfdd03-f0be-45d4-989d-e6bbb787050b.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No. It is there on Normal build as well

**Comment by tposejank** [comment]
ALREADY FIXED
