### ISSUE TITLE
Help with Tweens

### ISSUE THREAD

**Issue by MaybeMaru** [ShadowMario/FNF-PsychEngine#3087]
### Describe your problem here.

I have a small problem with tweens in Lua. 
The problem is that when I do for example a note Tween it only does it once.
How could I fix this?

`			noteTweenAngle('1', 0, 360, 0.5, "circInOut");
			noteTweenAngle('2', 1, 360, 0.5, "circInOut");
			noteTweenAngle('3', 2, 360, 0.5, "circInOut");
			noteTweenAngle('4', 3, 360, 0.5, "circInOut");`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by tposejank** [comment]
it only works once because the second time you trigger it the note is already in 360

**Comment by MaybeMaru** [comment]
> it only works once because the second time you trigger it the note is already in 360

oh I get it. Now I feel so dumb lmao

**Comment by MaybeMaru** [comment]
To anyone whatching this that also has my problem here is the fix:
Create a local variable to store the spin (like for example 360)
And everytime the note spins at the end make the variable gain 360 degrees.

`local Spin = 360`
`
		noteTweenAngle('1', 0, Spin, value2, "circInOut");
		noteTweenAngle('2', 1, Spin, value2, "circInOut");
		noteTweenAngle('3', 2, Spin, value2, "circInOut");
		noteTweenAngle('4', 3, Spin, value2, "circInOut");
		Spin = Spin + 360;
`

**Comment by MaybeMaru** [comment]
New fix, basically when the spin is finished in the finished tweens thing then just make another tween to 0 degrees in 0 seconds.
This helps for modchart events n stuff so arrows dont go fucking crazy with the bad variable solution
