### ISSUE TITLE
Modcharting question 

### ISSUE THREAD

**Issue by dkoea** [ShadowMario/FNF-PsychEngine#3090]
### What is your question?

I am currently making a modchart of a song and I was wondering if there was a way to make the middle notes in the image attached have a different scroll direction to the arrows on the outside, and if so, how would I go about doing this?
![image](https://user-images.githubusercontent.com/85266666/147970976-8b620d22-e176-4e67-bf48-c52de9866443.png)

**Comment by bbpanzu** [comment]
k i finna

**Comment by dkoea** [comment]
thank you bbpanzu lol
