### ISSUE TITLE
LUA

### ISSUE THREAD

**Issue by endorblue** [ShadowMario/FNF-PsychEngine#3091]
### Describe your bug here.

when i added week 7  (stress to be exact) on 4.2 when i updated it to 5.1 pico stopped shooting and no tankmen were running i tested it back on 4.2 and i worked

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
You downloaded a stolen Week 7 port, congratulations.
