### ISSUE TITLE
Image changing

### ISSUE THREAD

**Issue by MarkAwesomeness** [ShadowMario/FNF-PsychEngine#3093]
### Describe your problem here.

I have an image in my background that changes like the blammed lights do in game, but it only cycles through all of them once, then it stops.

Here is the lua

```
function onCreate()
   num = 0
   --for normal images and sprites.
    makeLuaSprite('yes','layer0', -200, -100)
    addLuaSprite('yes',false) --Do you want your image to be infront of the characters?
    setLuaSpriteScrollFactor('yes', 1, 1)
    --copy this and make changes to add other things.
    
   --for animated things.
   makeAnimatedLuaSprite('SPEAKERS','spookers', -100, 500)
   addAnimationByPrefix('SPEAKERS','SPEAKERS','SPEAKERS',24,true) --do you want the animation to loop?
   addLuaSprite('SPEAKERS', false)

    --for normal images and sprites.
    makeLuaSprite('pretty lit','layer1', -200, -125)
    addLuaSprite('pretty lit',false) --Do you want your image to be infront of the characters?
    setLuaSpriteScrollFactor('pretty lit', 1, 1)
    --copy this and make changes to add other things


    makeLuaSprite('bg1', 'dancefloor0', -200, -100);
    makeLuaSprite('bg2', 'dancefloor1', -200, -100);
    makeLuaSprite('bg3', 'dancefloor2', -200, -100);
    makeLuaSprite('bg4', 'dancefloor3', -200, -100);
    makeLuaSprite('bg5', 'dancefloor4', -200, -100);        

end

local images = {
    [0] = function()
       addLuaSprite('bg1', false);
    end,
    [1] = function()
       addLuaSprite('bg2', false);
    end,
    [2] = function()
       addLuaSprite('bg3', false);
    end,
    [3] = function()
       addLuaSprite('bg4', false);
    end,
    [4] = function()
       addLuaSprite('bg5', false);
    end
}

function onBeatHit()
   
   objectPlayAnimation('SPEAKERS','SPEAKERS',true)--Do you want this animation to be forced?


   images[num](); 
   if num < 4 then num = num + 1 end 
   if num > 4 then num = num - num end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MarkAwesomeness** [comment]
`    makeLuaSprite('bg1', 'dancefloor0', -200, -100);
    makeLuaSprite('bg2', 'dancefloor1', -200, -100);
    makeLuaSprite('bg3', 'dancefloor2', -200, -100);
    makeLuaSprite('bg4', 'dancefloor3', -200, -100);
    makeLuaSprite('bg5', 'dancefloor4', -200, -100);        

end

local images = {
    [0] = function()
       addLuaSprite('bg1', false);
    end,
    [1] = function()
       addLuaSprite('bg2', false);
    end,
    [2] = function()
       addLuaSprite('bg3', false);
    end,
    [3] = function()
       addLuaSprite('bg4', false);
    end,
    [4] = function()
       addLuaSprite('bg5', false);
    end
}`

**Comment by SrtHero278** [comment]
Maybe because you're not removing them as they go and Psych doesn't add duplicates.

**Comment by bbpanzu** [comment]
try  images[curBeat%5]();

**Comment by ShadowMario** [comment]
That's because you're adding the images, but you're never removing them.

I'd suggest just adding the images at the start and making them invisible with setProperty.
Then on `local images = {}` you can make the specific ones visible
