### ISSUE TITLE
DefaultPlayerStrumY isn't set up correctly 

### ISSUE THREAD

**Issue by JustinSolstice** [ShadowMario/FNF-PsychEngine#3095]
### Describe your bug here.

DefaultPlayerStrumY is set slightly higher than the actual strum Y, I need to manually set the variable when the song starts

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by tposejank** [comment]
do it + 10
