### ISSUE TITLE
Moving note strum code won't work

### ISSUE THREAD

**Issue by KutikiPlayz** [ShadowMario/FNF-PsychEngine#3098]
### Describe your problem here.

Basically, I'm re-creating the Ectospasm modchart with source code, and there's a part in it where the strum notes will move back and forth.
Here's a video for reference as to what I'm trying to do:
https://user-images.githubusercontent.com/73810550/147987067-d99ddbbe-ae98-4293-948c-3bb7f4c61335.mp4
Here's the code I have:
![Screenshot (1023)](https://user-images.githubusercontent.com/73810550/147987240-3a483c4c-9ab3-4d99-82de-f6312c1adaaa.png)
And here's the modchart code for it:
![Screenshot (1024)](https://user-images.githubusercontent.com/73810550/147987291-4a493697-541a-4b38-81a5-11a73ad299e2.png)
What's wrong with my code? I'm assuming that I didn't reference the strum notes properly but if that is the case idk what I would put there.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by KutikiPlayz** [comment]
Update: I think I am referencing the right thing, just I might need something before it.
Here's some code I just added that makes the notes spin at certain points in the song, the tween works.
![Screenshot (1025)](https://user-images.githubusercontent.com/73810550/147991969-493f5eb3-c323-4d56-8ba6-6e8b646ec4dc.png)

**Comment by KutikiPlayz** [comment]
I figured out what was wrong, this is my current code now:
![Screenshot (1026)](https://user-images.githubusercontent.com/73810550/147995813-2e970522-a231-4d13-b1bb-ba5843218311.png)
It works now however the notes go way farther than they are supposed to

**Comment by bbpanzu** [comment]
we don't have a setActor function lol. that's a KadeEngine thing

**Comment by bbpanzu** [comment]
we got setProperty()

**Comment by KutikiPlayz** [comment]
> we don't have a setActor function lol. that's a KadeEngine thing

that's why I was remaking it with source since I don't know lua for shit
but I figured it out anyways
