### ISSUE TITLE
How do I make stages easily?

### ISSUE THREAD

**Issue by Doritojoey** [ShadowMario/FNF-PsychEngine#3099]
### Describe your problem here.

Basically i'm tryna make a stage so i assembled everything first in adobe animate in 1280x720 res but when i put the same coordinates in the game they are the same, is there like a setting i need to put on animate to convert to a different coordinate thing or what

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I put in a modpack and that's where I'm working on the stage

**Comment by KutikiPlayz** [comment]
What you could do is instead of making everything a small image, and then lining it up manually, just make every piece the same resolution, and have the parts already aligned to where they need to be so that you can just throw everything on the same x and y in the code

**Comment by Doritojoey** [comment]
![image](https://user-images.githubusercontent.com/92836381/147988225-5d2b3a25-d840-4453-a869-3a6becf67b2f.png)
I did that

**Comment by Doritojoey** [comment]
![image](https://user-images.githubusercontent.com/92836381/147988543-4e349221-1d97-4e1e-b55d-a96693781b24.png)
Looks like this LMFAO

**Comment by crispyboi24** [comment]
export a png of the entire stage and put it in the center, then move the assets in game till they are right

**Comment by Doritojoey** [comment]
Nevermind, figured out I was using the raw assets from adobe animate and putting those coordinates in when i was supposed to use the png stuff I exported
