### ISSUE TITLE
how do i

### ISSUE THREAD

**Issue by Bammmmmmmmmmmmm** [ShadowMario/FNF-PsychEngine#3108]
### What is your question?

how do i move the window in lua shit

**Comment by ShadowMario** [comment]
@bbpanzu send them your code cuz i forgot (i'm sure you said you had made windows move in lua on twitter)

**Comment by proguzoyunda** [comment]
setPropertyFromClass('openfl.Lib','application.window.x',writevalue)
setPropertyFromClass('openfl.Lib','application.window.y',writevalue)
lol
