### ISSUE TITLE
more dialogue stuffs

### ISSUE THREAD

**Issue by skid15** [ShadowMario/FNF-PsychEngine#3113]
### What feature do you want to get added on the **base** engine?

more customization in the dialogue editor, like font type/size/color, and different sounds

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MaybeMaru** [comment]
You can already do that with Lua lmao

**Comment by skid15** [comment]
> You can already do that with Lua lmao

my bad lol, didn't know that before
