### ISSUE TITLE
easter egg window title

### ISSUE THREAD

**Issue by lag3ad0** [ShadowMario/FNF-PsychEngine#3114]
### What feature do you want to get added on the **base** engine?

put a easter egg that changes the title of the window being sike engine instead psych engine

that would be cool

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by HiroMizuki** [comment]
what

**Comment by lag3ad0** [comment]
> what

yes

**Comment by AlansGames** [comment]
but why

**Comment by lag3ad0** [comment]
> but why

its funny

**Comment by HiroMizuki** [comment]
we don't really need it

**Comment by MayoALT** [comment]
your wish got granted in the source code lol
