### ISSUE TITLE
be able to use the modcharts of other mods

### ISSUE THREAD

**Issue by XxjuandisxX** [ShadowMario/FNF-PsychEngine#3117]
### What feature do you want to get added on the **base** engine?

You can add the function of adding modcharts like those of friday night fever that the arrows move up and down pls

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by naether** [comment]
![image](https://user-images.githubusercontent.com/60763676/148008340-d46bd3d7-bd71-440b-bf90-a6e0c67e5496.png)
who needs good ideas anyways

**Comment by Gui-iago** [comment]
> ![image](https://user-images.githubusercontent.com/60763676/148008340-d46bd3d7-bd71-440b-bf90-a6e0c67e5496.png) who needs good ideas anyways
^

also learn to modchart on Psych bro, there **is** a way to move the arrows like in FNFE
people even made events for godsake https://github.com/ShadowMario/FNF-PsychEngine/discussions/893

**Comment by PoleyMagik** [comment]
A: Fails the basic sight check
B: Already exists i stg nobody checks the wiki
