### ISSUE TITLE
Change Opponent Strums Separately Players Ones (IN LUA) 

### ISSUE THREAD

**Issue by Rexuadoz12** [ShadowMario/FNF-PsychEngine#3118]
### What is your question?

Well, with the new psych engine update that is probably coming.
I really wanna know if we will be able to change separately strums in Lua like:
Opponent Strums is different to the player strums.

**Comment by ProgramerGamerZone** [comment]
Ok so you will want to make 2 scripts in the scripts folder
one to change the notes if you character is the opponent and one to check if it's a player
for script 1 (change arrows if character is opponent):
```
function onUpdate(elapsed)
	if dadName == 'YOURCHARACTERNAME' then
		for i=0,4,1 do
			setPropertyFromGroup('opponentStrums', i, 'texture', 'NOTETEXTUREHERE')
		end
		for i = 0, getProperty('unspawnNotes.length')-1 do
			if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
				setPropertyFromGroup('unspawnNotes', i, 'texture', 'NOTETEXTUREHERE'); --Change texture
			end
		end
	end
end
```
for script 2 (if it is a player)
```
function onUpdate(elapsed)
	if boyfriendName == 'YOURCHARACTERNAME' then
		for i=0,4,1 do
			setPropertyFromGroup('playerStrums', i, 'texture', 'NOTETEXTUREHERE')
		end
		for i = 0, getProperty('unspawnNotes.length')-1 do
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
				setPropertyFromGroup('unspawnNotes', i, 'texture', 'NOTETEXTUREHERE'); --Change texture
				setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'NOTESPLASHHERE'); --Change texture 

			end
		end
	end
end
```

**Comment by Rexuadoz12** [comment]
> Ok so you will want to make 2 scripts in the scripts folder one to change the notes if you character is the opponent and one to check if it's a player for script 1 (change arrows if character is opponent):
> 
> ```
> function onUpdate(elapsed)
> 	if dadName == 'YOURCHARACTERNAME' then
> 		for i=0,4,1 do
> 			setPropertyFromGroup('opponentStrums', i, 'texture', 'NOTETEXTUREHERE')
> 		end
> 		for i = 0, getProperty('unspawnNotes.length')-1 do
> 			if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
> 				setPropertyFromGroup('unspawnNotes', i, 'texture', 'NOTETEXTUREHERE'); --Change texture
> 			end
> 		end
> 	end
> end
> ```
> 
> for script 2 (if it is a player)
> 
> ```
> function onUpdate(elapsed)
> 	if boyfriendName == 'YOURCHARACTERNAME' then
> 		for i=0,4,1 do
> 			setPropertyFromGroup('playerStrums', i, 'texture', 'NOTETEXTUREHERE')
> 		end
> 		for i = 0, getProperty('unspawnNotes.length')-1 do
> 			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
> 				setPropertyFromGroup('unspawnNotes', i, 'texture', 'NOTETEXTUREHERE'); --Change texture
> 				setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'NOTESPLASHHERE'); --Change texture 
> 
> 			end
> 		end
> 	

> 

Thanks bro, i will try that
