### ISSUE TITLE
song

### ISSUE THREAD

**Issue by xDItsTej** [ShadowMario/FNF-PsychEngine#3120]
### Describe your problem here.

So, I'm trying to chart a song, but I'm not sure how I can make my song & vocals into the charting menu. Like, I chart part of the song, but when I test it, there is no music. Can someone help me fix this

https://user-images.githubusercontent.com/97074458/148003319-f207abc7-2ce3-43af-9af7-324dd59c8393.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed some textures and got rid of the default songs in the assets/ directory

**Comment by BocaIoachim** [comment]
Its cuz the song does not have a audio file loaded, have you tried pressing reload audio after putting the songs name?
and you also need a json made like you can literally just go on tutorial's json file and loading the audio with that json and
charting the song on that json(make all the changes you need and clear all notes and events) and done

**Comment by BocaIoachim** [comment]
and i want to also say that it shows 0 sections so it obviously does not have the audio loaded

**Comment by xDItsTej** [comment]
For some reason, that didn't work. This is all it did:
(the video file was too big)
https://youtu.be/6PIFCUR-ZY4
Do you know why it's making the audio and charting "Test" 
Also, yes, I tried changing the name of the song in the Charting Menu to the name of the song I made and it didn't work.

**Comment by xDItsTej** [comment]
Update: The charting I saved is loading, it's just the song Inst. and Voices aren't loading so it's just stuck.
