### ISSUE TITLE
File won't unzip 

### ISSUE THREAD

**Issue by AToonzOnGit** [ShadowMario/FNF-PsychEngine#3121]
### Describe your bug here.

Ok so, every single time i download the psych engine source, it always says ''The compressed zip folder is empty'' even though i downloaded all of the files correctly, any ideas on how to fix this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MayoALT** [comment]
download winrar or 7zip
