### ISSUE TITLE
Character wont show up in charactere editor

### ISSUE THREAD

**Issue by AJJAMES17** [ShadowMario/FNF-PsychEngine#3122]
### Describe your problem here.

My characters XML File has his xs and ys as numbers in the thosands. so when i go to the character editor i cant see him. How can i change the xml? i already changed the spritesheet dimensions.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by aflacc** [comment]
Well, xmls don't define position. They just contain data that can be read by code to display frames in a .png

Try seeing if you can find the character by using the ijkl movement controls in that menu to pan the camera
