### ISSUE TITLE
Change Judgment Text

### ISSUE THREAD

**Issue by WeldedFlap** [ShadowMario/FNF-PsychEngine#3123]
### What is your question?

How Would I Change The Rating Text On The HUD Using Lua?? 

Ex: Changing Sick! To Awesome!

![image](https://user-images.githubusercontent.com/90015471/148008816-2d495174-d840-42ba-af30-0a38a4e1df49.png)

**Comment by tposejank** [comment]
you can't

**Comment by WeldedFlap** [comment]
> you can't

oh thanks for letting me know

**Comment by mayo78** [comment]
[actually, you can](https://github.com/ShadowMario/FNF-PsychEngine/discussions/3164)

**Comment by WeldedFlap** [comment]
> [actually, you can](https://github.com/ShadowMario/FNF-PsychEngine/discussions/3164)

i made that discussion lol. my friend showed me how.
