### ISSUE TITLE
Shaders.hx not letting me compile

### ISSUE THREAD

**Issue by TheHalfBunnyLXKD** [ShadowMario/FNF-PsychEngine#3129]
### Describe your bug here.

This is annoying me.

### Command Prompt/Terminal logs (if existing)

![image](https://user-images.githubusercontent.com/96796578/148017834-460e643e-a3f9-45b4-8ada-a5f4c36e1020.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

ALOT.

**Comment by naether** [comment]
@bbpanzu im soryr

**Comment by lemz1** [comment]
this has been fixxed. Download the code again

**Comment by Gui-iago** [comment]
fixed, update source, and close the issue
