### ISSUE TITLE
the game plays but the dialoge don't come first 

### ISSUE THREAD

**Issue by ThatDisabledKid** [ShadowMario/FNF-PsychEngine#3133]
### Describe your bug here.

when i add mods on the mods folder it wont start the dialoge  
[video if you don't understand](https://kapwi.ng/c/u9v5BwjIPL)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

 no

**Comment by JonnyboyTheboy** [comment]
sorry for shitty video but thats the best i can do
