### ISSUE TITLE
Cant Die

### ISSUE THREAD

**Issue by UnknownSkid** [ShadowMario/FNF-PsychEngine#3135]
### Describe your bug here.

i Cant Die (This Happens Even When The Health Bar is Normal Size)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

health bar

**Comment by GeorgeFNF** [comment]
What did you edit about the health bar, you might have practice mode on.

**Comment by UnknownSkid** [comment]
Size
And no i dont have practice mode on

wt., 4 sty 2022, 12:25 użytkownik GeorgeFNF ***@***.***>
napisał:
