### ISSUE TITLE
Identifier to identify song names when selected (FreeplayState.hx)

### ISSUE THREAD

**Issue by NickPlayzGITHUB** [ShadowMario/FNF-PsychEngine#3145]
### Describe your problem here.

I need to know what the identifier for a song name is when hovering over it in freeplay
![image](https://user-images.githubusercontent.com/87223282/148081978-f15ca957-34dc-4f2e-807a-c211d6fbae0f.png)
Right where it say switch(song) Song needs to be replaced with the proper identifier for the name of songs for freeplay.

Very complicated to explain. But bassically I am trying to code it so that when hovering over a song in freeplay it will say who the composer is.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

FreeplayState.hx

**Comment by AlyssonRo** [comment]
i use this code on kade engine so might not work on psych `if (songs[curSelected].songName.toLowerCase() == 'yoursongname')`

**Comment by NickPlayzGITHUB** [comment]
it didn't work
