### ISSUE TITLE
Stage Editor

### ISSUE THREAD

**Issue by JeffersonThePro68** [ShadowMario/FNF-PsychEngine#3146]
### What is your question?

If there will be an editor stage, in my mind this editor stage you can use your mouse and move the ground, the sky, among other things.

**Comment by DaBanana64** [comment]
**I don't think that's gonna be possible.**

**Comment by crispyboi24** [comment]
U botta get banned LMAOO!

**Comment by lemz1** [comment]
Dude is about to come back as JeffersonThePro69

**Comment by DaBanana64** [comment]
> Dude is about to come back as JeffersonThePro69

**LMFAO**

**Comment by PDL2CGamejolt** [comment]
uh, havent you read the thing

**Comment by tposejank** [comment]
me when i purposely get banned 🤭🤭🤣🤣

**Comment by JeffersonThePro68** [comment]
![image](https://user-images.githubusercontent.com/86690128/148143175-96557e34-cd41-46fe-9737-a1ea9356fa68.png)

**Comment by ByronisJoan** [comment]
> ![image](https://user-images.githubusercontent.com/86690128/148143175-96557e34-cd41-46fe-9737-a1ea9356fa68.png) lol

Bruh He Is Gonna Do It Later
