### ISSUE TITLE
Color in Lua

### ISSUE THREAD

**Issue by lag3ad0** [ShadowMario/FNF-PsychEngine#3149]
### Describe your problem here.

well i was doing some modcharts and try "cameraFlash"

i put the color 
![Notepad_Hh4fLmJHAw](https://user-images.githubusercontent.com/70418371/148091792-84d703e7-bc04-4b4f-9f6c-2b535bbef9c1.png)

and always appears blue
![PsychEngine_SpqyAjuvIi](https://user-images.githubusercontent.com/70418371/148091785-8fcc5aa6-08ba-49ec-afc6-06f0b519af66.png)

what are the color tags or smth?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by crispyboi24** [comment]
I think u gotta use numbers for that. Or color values

**Comment by lag3ad0** [comment]
well it says "color:string" and hex values dont work

**Comment by naether** [comment]
did you put the color and camera between quotation marks? if you didn't it just thinks it's a variable and not a string

try 'FF0000' or smth

**Comment by lag3ad0** [comment]
yo it works

thanks!
