### ISSUE TITLE
How to disable the spamming penalty through the code when ghost tapping is on

### ISSUE THREAD

**Issue by FoxyGamer1980** [ShadowMario/FNF-PsychEngine#3150]
### Describe your problem here.

I tried to remove the spam penalty by putting the health loss for that to 0, however, that also conflicts with when ghost tapping is off, since if ghost tapping is off, pressing the arrow keys when there's no notes will reduce the score, but won't lose your health, completely breaking the health system, is there a way to restrict it to that you won't lose health when ghost tapping, but lose health when ghost tapping is off when spamming

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not yet, i'm pretty confused on this

**Comment by Ninjatintin** [comment]
get good
