### ISSUE TITLE
sustain length

### ISSUE THREAD

**Issue by anonybean** [ShadowMario/FNF-PsychEngine#3151]
### What feature do you want to get added on the **base** engine?

can you make sustain length that long like 5000 or sum

![image](https://user-images.githubusercontent.com/94534428/148094868-3022a960-062b-4b78-9e8f-3ea93f135b96.png)

### To test your sight, and reliability, please select the option of what should NOT be requested.

.

**Comment by MeowcaTheoRange** [comment]
How the FUCK did you get a PERIOD in there
![image](https://user-images.githubusercontent.com/58280776/148235212-475c886b-ab42-4c86-831e-d85fa8e6075e.png)

**Comment by anonybean** [comment]
lol ez  just edit the massage

> How the FUCK did you get a PERIOD in there ![image](https://user-images.githubusercontent.com/58280776/148235212-475c886b-ab42-4c86-831e-d85fa8e6075e.png)

**Comment by anonybean** [comment]
![image](https://user-images.githubusercontent.com/94534428/148418425-d6aa98fe-0c7f-4592-b59e-01b55735b90c.png)
