### ISSUE TITLE
dialogue issue

### ISSUE THREAD

**Issue by starygalaxy** [ShadowMario/FNF-PsychEngine#3153]
### Describe your problem here.

I used the script.lua for my cutscenes in an old mod and it works! i try it again for dialogue and nothing happens it just plays the song

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by RinZleR121** [comment]
Check [this](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API#example-scripts)
