### ISSUE TITLE
Biggest Enemy on FNF

### ISSUE THREAD

**Issue by TheHalfBunnyLXKD** [ShadowMario/FNF-PsychEngine#3161]
### Describe your bug here.

I CANT TAKE THIS DUDE ANYMORE AAAAAAAAAAAA
![image](https://user-images.githubusercontent.com/96796578/148113324-c73a60b8-855a-4a9a-8cdb-2230d18ba7ad.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Plenty of stuff

**Comment by MaybeMaru** [comment]
bruh

**Comment by SrtHero278** [comment]
Json error. There's actually websites to detect these. I use JSON Lint. Try to find out the json that gives an error, post it here, and I can check it for you.
