### ISSUE TITLE
What happened to the secret song Hot Dilf?

### ISSUE THREAD

**Issue by RowanSkie** [ShadowMario/FNF-PsychEngine#3168]
### What is your question?

What happened to the secret song Hot Dilf? After I upgraded to 0.5.1, it vanished. Last I saw it is with 0.4 versions.

**Comment by HiroMizuki** [comment]
it was removed

**Comment by lag3ad0** [comment]
im so sad right now

**Comment by TheiLusion** [comment]
:(
