### ISSUE TITLE
How does StrumNote.hx work?

### ISSUE THREAD

**Issue by BeansCool54** [ShadowMario/FNF-PsychEngine#3169]
### What is your question?

I was wondering how does StrumNote.hx work. Pretty self explain.

**Comment by HiroMizuki** [comment]
it's the source file that manages the strum notes animations and movements

**Comment by HiroMizuki** [comment]
> it's the source file that manages the strum notes animations and movements

and directions too

**Comment by BeansCool54** [comment]
> > it's the source file that manages the strum notes animations and movements
> 
> and directions too

Thx
