### ISSUE TITLE
Background changing event

### ISSUE THREAD

**Issue by Coolgaymerboi** [ShadowMario/FNF-PsychEngine#3170]
### What feature do you want to get added on the **base** engine?

Kade engine I think already has that feature that was used for the Sonic exe 2.0 I was wondering if you can add that feature @ShadowMario it could be useful for new mods

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by tposejank** [comment]
@everyone HE FINNA GET BANNED

**Comment by Gui-iago** [comment]
I see a ban coming

**Comment by MeowcaTheoRange** [comment]
![image](https://user-images.githubusercontent.com/58280776/148234924-75710936-79c1-4b1f-b921-59546b03e847.png)
🗿🗿🗿🗿🗿

**Comment by ImaginationSuperHero528** [comment]
> ### What feature do you want to get added on the **base** engine?
> Kade engine I think already has that feature that was used for the Sonic exe 2.0 I was wondering if you can add that feature @ShadowMario it could be useful for new mods
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Useful featureSh

> ### What feature do you want to get added on the **base** engine?
> Kade engine I think already has that feature that was used for the Sonic exe 2.0 I was wondering if you can add that feature @ShadowMario it could be useful for new mods
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Useful feature

Shadow Mario lit said he will never do this cause then hill have to redo the code for stages
