### ISSUE TITLE
achievements

### ISSUE THREAD

**Issue by ethannn123** [ShadowMario/FNF-PsychEngine#3174]
### What feature do you want to get added on the **base** engine?

Could we be able to add/edit achievements later update?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by HiroMizuki** [comment]
already possible at source

**Comment by PDL2CGamejolt** [comment]
> already possible at source

He means softcoded

**Comment by HiroMizuki** [comment]
> > already possible at source
> 
> He means softcoded

i think it can be updated, idk
