### ISSUE TITLE
Window Freaking out

### ISSUE THREAD

**Issue by ATOMICFAZBEAR** [ShadowMario/FNF-PsychEngine#3177]
### Describe your bug here.

in the latest actions build when you full screen the game using the full screen option on the top right after going to a new menu/new state the window size changes.
i find it pretty annoying honestly.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing because i don't use source

**Comment by tposejank** [comment]
yes its pretty buggy ngl.
![image](https://user-images.githubusercontent.com/81495861/148159351-3a2c2dec-ceb2-4b3e-99b1-ce94a6891a5b.png)
i find it this buggy though.

**Comment by Doritojoey** [comment]
![image](https://user-images.githubusercontent.com/92836381/148187619-13473688-95e7-4b59-8189-69fb8ae66aef.png)
please reverse this

**Comment by tposejank** [comment]
@bbpanzu what have you done

**Comment by bbpanzu** [comment]
toggle fullscreen through the options

**Comment by Doritojoey** [comment]
![image](https://user-images.githubusercontent.com/92836381/148342973-b2043007-513c-4387-b80e-b78ee544d6c9.png)
i set it to fullscreen
