### ISSUE TITLE
Making custom Splash effects for Damage notes in lua.

### ISSUE THREAD

**Issue by Playtime1607** [ShadowMario/FNF-PsychEngine#3178]
### Describe your problem here.

I'm in the process of adding these fire notes and I want to add a custom splash effect as a way to communicate with the player that they hit it. It's similar to the base game hurt notes but with a heath drain aspect. For the life of me I can't find a proper tutorial on it pls help

![code](https://user-images.githubusercontent.com/97142331/148156917-f35a1149-60af-40ad-9c7b-fcb6b110a689.jpg)
.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Itz-Miles** [comment]
It also took me a while to find this out. I'd agree there isn't much documentation on this, you can look into FunkinLua.hx to find what you're looking for though.
(Oh yeah, `setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'your splash texture here');`)
