### ISSUE TITLE
Change Character doesn't change characters correctly Bug

### ISSUE THREAD

**Issue by ElLeandroDev** [ShadowMario/FNF-PsychEngine#3181]
### Describe your bug here.

I put the "Change Character" Event like this:

Value 1: dad
Value 2: bambi

and it changes bf instead of the opponent

i tried with saving the chart or save it in events.json but it doesn't works

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited the source carpet and added custom notes and events.

**Comment by anonybean** [comment]
try putting the Value 1: 1

like this

https://user-images.githubusercontent.com/94534428/148175429-ad067c31-de7f-413c-a5ca-0257d1028dc9.mp4

**Comment by ElLeandroDev** [comment]
thanks
