### ISSUE TITLE
Custom dialogue boxes with oua

### ISSUE THREAD

**Issue by Demopantf** [ShadowMario/FNF-PsychEngine#3187]
### Describe your problem here.

How can you create custom dialogue box sprites with in scripting lua? Shadow mario did said it's possible with lua,so it's definitely possible

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by tposejank** [comment]
replace  the box image

**Comment by WaldenMD** [comment]
look at the code of this mod it brings its own dialog box, exactly the Lua 'handlerTextBox' from the custom_events folder.

"I didn't understand much of the code"

https://gamebanana.com/mods/345103
