### ISSUE TITLE
How to make these elements not display?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#3200]
### What is your question?

How to make these elements not display? There are 4 in total. as follow:

![Snipaste_2022-01-06_03-02-58](https://user-images.githubusercontent.com/13177997/148274131-4ddaeaed-6e20-4373-b73c-ba8f2376e400.png)

**Comment by BombasticTom** [comment]
I only know for the health bar and score text
healthBar is the Health Bar
it also has a variable healthBarBG
iconP1 is the protagonist i think
iconP2 is the antagonist
scoreTxt is score text

**Comment by tposejank** [comment]
setProperty('camHUD.alpha', 0)
