### ISSUE TITLE
FlxTrail used in LUA

### ISSUE THREAD

**Issue by GMan2006i** [ShadowMario/FNF-PsychEngine#3207]
### What feature do you want to get added on the **base** engine?

FlxTrail as either a event or being able to use FlxTrail as a variable in LUA or sum idk lol
I'm honestly suprised this hasn't already been added but whatever. But I'd love to see this as an addition

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by RonHereLMAO** [comment]
NO stage editor is gud i dont wanna keep re compiling over and over just to get the right x and y

**Comment by Itz-Miles** [comment]
> NO stage editor is gud i dont wanna keep re compiling over and over just to get the right x and y

I'd recommend editing the stage json in export and restarting the song to see the changes. Once you're satisfied with the changes, just overwrite the preload stage json with the export one.

**Comment by aflacc** [comment]
If your referring to the thing that Spirit uses, yes absolutely we need this.
