### ISSUE TITLE
Death Quotes In Lua.

### ISSUE THREAD

**Issue by dkoea** [ShadowMario/FNF-PsychEngine#3212]
### Describe your problem here.

How would I go about putting random death quotes into lua

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by i-winxd** [comment]
Play an audio file the moment a character dies. The file can be random.

**Comment by RinZleR121** [comment]
I'm not so good at code but anyway.
First of all make your death quotes(for me it's from 1 to 11) and place it in sounds folder.
After that you can place this code in [place your stage name].lua
`function onGameOver()
	math.randomseed(os.time())
	math.random(); math.random(); math.random() --warmup
	
	for x = 1, 1 do --to not make chaos
		value = math.random(11)
		playSound(value)
	end
end`
And after you've done it correctly random death quotes will be played.
If you can make this code effictiently or if i didn't understand you well please tell me.

**Comment by RinZleR121** [comment]
I'm not so good at code but anyway.
First of all make your death quotes(for me it's from 1 to 11) and place it in sounds folder.
After that you can place this code in [place your stage name].lua
` `function onGameOver()
math.randomseed(os.time())
math.random(); math.random(); math.random() --warmup

for x = 1, 1 do --to not make chaos
	value = math.random(11)
	playSound(value)
end
end
``
And after you've done it correctly random death quotes will be played.
If you can make this code effictiently or if i didn't understand you well please tell me.

**Comment by RinZleR121** [comment]
I'm not so good at code but anyway.
First of all make your death quotes(for me it's from 1 to 11) and place it in sounds folder.
After that you can place this code in [place your stage name].lua
` function onGameOver()
math.randomseed(os.time())
math.random(); math.random(); math.random() --warmup

for x = 1, 1 do --to not make chaos
	value = math.random(11)
	playSound(value)
end
end `
And after you've done it correctly random death quotes will be played.
If you can make this code effictiently or if i didn't understand you well please tell me.

**Comment by RinZleR121** [comment]
I'm not so good at code but while I was doing full Psych Engine port of Chaos I made this.

So first of all you need to make death quotes like 3 or 4 in my example I will use 11.
Name it with numbers and put them in sounds mods/sounds or if you did everything in another folder and doesn't have sounds folder basically create it.
And after that paste this code at the end of stage lua
`function onGameOver()
	math.randomseed(os.time())
	math.random(); math.random(); math.random()
	
		for x = 1, 1 do
			value = math.random(11)
			playSound(value)
		end
end`
If you know how to make it efficiently or if I didn't understand you well please tell me.

**Comment by dkoea** [comment]
this helps! thank you so much!
