### ISSUE TITLE
Trying to make pressing storymode on the main menu open up a week on a difficulty, but game is crashing.

### ISSUE THREAD

**Issue by Alt-Reality** [ShadowMario/FNF-PsychEngine#3213]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/88809517/148299312-0fcf6cf5-f068-4e74-a2fa-07965f6cf315.png)
I have a mod with one week and one difficulty. What I'm trying to do is open the week on the only difficulty when you press the storymode button on the main menu. I took this code from the Cassette Girl mod, and modified it to match the difficulty. But, whenever I pressed enter while hovering over storymode on the main menu, the game would just crash.

Here are the files if needed. I included MainMenuState.hx, CoolUtil.hx, and the weekJson.
[menustate + playstate.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/7818216/menustate.%2B.playstate.zip)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Coolutil+storymenustate+freeplaystate to lock to one difficulty, Playstate for Custom note code + events + stages, Note.hx for custom note stuff again, Chartingstate.hx for events and notes in charting menu, Playstate for stages, mechanics, images, a LOT OF THINGS

**Comment by Starmapo** [comment]
I can't be 100% sure since this is an old version of the engine but I think I found the issue.
`var diffic = CoolUtil.difficultyStuff[0];`
It's using the whole array of the difficulty (`['Clipped', '']`), instead of just the chart suffix (in this case, `''`, which is empty). Replace it with:
`var diffic = CoolUtil.difficultyStuff[0][1];`
Also, you should change PlayState.storyDifficulty to 0, since setting it at 1 would refer to the second difficulty in the list, which doesn't exist.
`PlayState.storyDifficulty = 0;`

**Comment by Alt-Reality** [comment]
> I can't be 100% sure since this is an old version of the engine but I think I found the issue. `var diffic = CoolUtil.difficultyStuff[0];` It's using the whole array of the difficulty (`['Clipped', '']`), instead of just the chart suffix (in this case, `''`, which is empty). Replace it with: `var diffic = CoolUtil.difficultyStuff[0][1];` Also, you should change PlayState.storyDifficulty to 0, since setting it at 1 would refer to the second difficulty in the list, which doesn't exist. `PlayState.storyDifficulty = 0;`

changed everything and it was still crashing

**Comment by Starmapo** [comment]
Add this in the first line (before 'var songArray'): `WeekData.reloadWeekFiles(true);`

**Comment by Alt-Reality** [comment]
> Add this in the first line (before 'var songArray'): `WeekData.reloadWeekFiles(true);`

![image](https://user-images.githubusercontent.com/88809517/148315691-98705daf-259b-4905-86a3-0c3e0a706488.png)
![image](https://user-images.githubusercontent.com/88809517/148315737-803c9255-3689-4609-9c91-972a8aeb63fe.png)
I have no clue, friend told me it could be because 0.4.1 doesnt have this function in weekdata, but i found it here
![image](https://user-images.githubusercontent.com/88809517/148315790-658ef79b-412b-40a6-be0f-93aed89ed2a6.png)

**Comment by Alt-Reality** [comment]
just realised i sent the wrong image when i was trying to show the function being in WeekData.hx 💀 
but just know that 0.4.1 **DOES** have it

**Comment by Starmapo** [comment]
It worked fine for me, I have no clue. Maybe there was a problem with the code I sent or when you pasted it to your source code. Try searching online what "Invalid character 0x200B" is

**Comment by 4wdthinks** [comment]
Playstate.SONG.loadFromJson() i think??

**Comment by Alt-Reality** [comment]
> Playstate.SONG.loadFromJson() i think??

how would i use it to ope the week though? i know you can open one song with this but a week?

**Comment by Alt-Reality** [comment]
i got it to work by typing WeekData.reloadWeekFiles(); in weekdata.hx and pasting it into MainMenustate

**Comment by dkoea** [comment]
> i got it to work by typing WeekData.reloadWeekFiles(); in weekdata.hx and pasting it into MainMenustate

could you maybe upload the files for this? I am also attempting something like this and have no clue where to start
