### ISSUE TITLE
Characters Are Opponents an Players

### ISSUE THREAD

**Issue by Hunter13n** [ShadowMario/FNF-PsychEngine#3214]
### What feature do you want to get added on the **base** engine?

You should make the characters a folder an put 2 .jsons one as 'mom' an 'bf-mom' an put the sprites in there, something like FNF Multiplayer

example:
https://user-images.githubusercontent.com/66497511/148302763-5f9d4aa2-bed5-4eea-9287-2dd1cf32f329.mp4

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by MeowcaTheoRange** [comment]
![image](https://user-images.githubusercontent.com/58280776/148306475-a41a2b56-7078-4bec-8a9c-21554b0e1a0d.png)
🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿

**Comment by 4wdthinks** [comment]
useful feature moment
