### ISSUE TITLE
How Do I Add An End Screen To The End Of A Week?

### ISSUE THREAD

**Issue by FrailBubby0706** [ShadowMario/FNF-PsychEngine#3229]
### Describe your problem here.

Hey, How Do I Add An End Screen To The End Of A Week Without The Source Code?

### Are you modding a build from source or with Lua?

Not the source code.

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

_No_

**Comment by RonHereLMAO** [comment]
[Vs.Sky-Style.Endings.For.LUA.Build.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/7831996/Vs.Sky-Style.Endings.For.LUA.Build.zip)

this isnt mine 
TristonShaw made this *i think*
