### ISSUE TITLE
Events in a certain difficulty

### ISSUE THREAD

**Issue by WolfyTail** [ShadowMario/FNF-PsychEngine#3230]
### Describe your problem here.

Hello. I'm building the charts in my mod, but I would like to use events (like _health drain_) only on a certain difficulty (Hard). Is there a way to do this? Thanks.

PD: I'm not using .lua for the events, I'm using the events in the Charting Editor.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by tposejank** [comment]
if difficulty == 2 then
