### ISSUE TITLE
How to let gf not display?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#3231]
### What is your question?

How to let gf not display?

**Comment by Alt-Reality** [comment]
in playstate, press control+f and search for gf = new Character. you should find this gf code.
![image](https://user-images.githubusercontent.com/88809517/148452671-acb1fe06-e893-4346-bc26-c4e6c8767b35.png)
under gfGroup.add(gf);, add
if(curStage == 'your stage'){
			gf.visible = false;
		}

**Comment by RinZleR121** [comment]
if you want to make this in stage lua just type `setProperty('gf.visible', false)` during function onCreate

**Comment by bbpanzu** [comment]
> if you want to make this in stage lua just type `setProperty('gf.visible', false)` during function onCreate

*onCreatePost

**Comment by RinZleR121** [comment]
oh sorry

**Comment by zwl1619** [comment]
@RinZleR121   @bbpanzu

it doesn't work.
I put `script.lua` in `bin\assets\data\tutorial`.
```
function onCreatePost()
    setProperty('gf.visible', false)
end
```

**Comment by blaidev** [comment]
> @RinZleR121 @bbpanzu
> 
> it doesn't work. I put `script.lua` in `bin\assets\data\tutorial`.
> 
> ```
> function onCreatePost()
>     setProperty('gf.visible', false)
> end
> ```

ITS IN STAGE CODE I think or u can just.... ERASE ASSET but idk im bad at lua

**Comment by ShadowMario** [comment]
Put it in mods/ folder then

**Comment by mayo78** [comment]
> @RinZleR121 @bbpanzu
> 
> it doesn't work. I put `script.lua` in `bin\assets\data\tutorial`.
> 
> ```
> function onCreatePost()
>     setProperty('gf.visible', false)
> end
> ```
thats because the opponent gf overlays the normal gf in tutorial i believe (so also do `setProperty('dad.visible', false)`)

**Comment by zwl1619** [comment]
@mayo78 it works. thanks!
