### ISSUE TITLE
how do i remove spam punishments 

### ISSUE THREAD

**Issue by guywhodoesntknowhowtocompile** [ShadowMario/FNF-PsychEngine#3239]
### Describe your problem here.

i want to remove spam punishments when ghost tapping is on
im going to sleep

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by tposejank** [comment]
remove the canMiss = true in "onKeyPress" where it checks if a note can be hit

**Comment by guywhodoesntknowhowtocompile** [comment]
> 

No this isnt the case, if you mash you will lose a little bit of health

**Comment by guywhodoesntknowhowtocompile** [comment]
> remove the canMiss = true in "onKeyPress" where it checks if a note can be hit

so i need to copy this and paste it in a lua?

**Comment by tposejank** [comment]
no its only possible with source code

**Comment by guywhodoesntknowhowtocompile** [comment]
> no its only possible with source code

i dont know how to compile and half of the  thing that werent possible with lua exist in lua so it might exist

**Comment by guywhodoesntknowhowtocompile** [comment]
> no its only possible with source code

get trolled i made the script

**Comment by guywhodoesntknowhowtocompile** [comment]
today

**Comment by bobNewYear** [comment]
when the script doesn't work
