### ISSUE TITLE
Menu editor

### ISSUE THREAD

**Issue by bozata** [ShadowMario/FNF-PsychEngine#3246]
### What feature do you want to get added on the **base** engine?

I was thinking you could add a menu editor, like a way to customize the layout, positions of buttons and how they move when you select them. Like a way to customize the main menu, freeplay menu, and the story menu, or just the main menu is great too.If it could be done i feel like it will let people who know fuck all about coding (like myself) get more creative with the finer details of their mods to make them even more unique

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tposejank** [comment]
no.

**Comment by bbpanzu** [comment]
maybe i'll make menu's have jsons or sum.

**Comment by RonHereLMAO** [comment]
> maybe i'll make menu's have jsons or sum.

Lets goo
