### ISSUE TITLE
I need custom notes to play an animation for the opponent

### ISSUE THREAD

**Issue by Ace5542** [ShadowMario/FNF-PsychEngine#3254]
How would I add the animations to the opponent character???

**Comment by tposejank** [comment]
you ARE stupid

**Comment by MayoALT** [comment]
you ARE stupid

**Comment by CrunchBar41** [comment]
![image](https://user-images.githubusercontent.com/95093250/148667017-2e0361cd-c2b7-4b05-a156-d5ebe7259f35.png)
You would use a code similar to what is shown in the image.
