### ISSUE TITLE
Texture atlas for lua

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#3263]
### What is your question?

Hey can we use texture atlas on lua objects? Just wondering

**Comment by tposejank** [comment]
yes

**Comment by crispyboi24** [comment]
> yes

How do you use it?

**Comment by Starmapo** [comment]
> How do you use it?

Something like this:
`makeAnimatedLuaSprite('spriteName', 'atlasImagePath', x, y, 'texture')`
"texture" being what makes it use the Texture Atlas. After that you can use 'addAnimationByIndices' to add animations.

**Comment by bbpanzu** [comment]
you can also use Prefix btw. Smokey's atlas thingy is smart.
