### ISSUE TITLE
Song plays when dialogue is on screen.

### ISSUE THREAD

**Issue by JuniorNovoa1** [ShadowMario/FNF-PsychEngine#3267]
### Describe your bug here.

So basically the song plays when there is dialogue on the screen
Example:
<img width="1271" alt="Screen Shot 2022-01-07 at 1 00 17 AM" src="https://user-images.githubusercontent.com/87715171/148499452-6bd20f2b-844a-4aad-b0d2-d99e53616780.png">
n

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by tposejank** [comment]
did you add return Function_Stop

**Comment by JuniorNovoa1** [comment]
fixed it.
