### ISSUE TITLE
arrows and notesplashes changes mid song

### ISSUE THREAD

**Issue by MrSomethingoridk** [ShadowMario/FNF-PsychEngine#3271]
### Describe your problem here.

something like in endless

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Itz-Miles** [comment]
This is an event that sets the note skins and splashes.




`function onCreate()`
`for i = 0, getProperty('unspawnNotes.length')-1 do`
`if getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' then`
`setPropertyFromGroup('unspawnNotes', i, 'texture', 'your note here', 'your note here');`
`setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'your splash here');`		
`end`
`end`
`end`

If you want to send more than one:

`function onUpdate(elapsed)`
`if curStep >= (your number here) then`
`setPropertyFromGroup('unspawnNotes', i, 'texture', 'your note here', 'your note here');`
`setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'your splash here');`	
(repeat as many times as you want)
