### ISSUE TITLE
Custom Animation

### ISSUE THREAD

**Issue by xDItsTej** [ShadowMario/FNF-PsychEngine#3279]
### Describe your problem here.

My friend made a custom character that I put into the game. It works perfectly fine, but I added an animation of him falling over and going to sleep. That animation results as an error in the character creator menu. Is there a way i can fix it

https://user-images.githubusercontent.com/97074458/148573766-7b907ae8-b379-4cef-9417-af429daf2612.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed some textures and got rid of the default songs in the assets/ directory

**Comment by RinZleR121** [comment]
Can i have xml file of this character?

**Comment by xDItsTej** [comment]
Yeah, sorry it took me so long.

[neoxml.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/7832050/neoxml.zip)

**Comment by xDItsTej** [comment]
Also, for some reason, the "up animation" on another character I made is invisible. 
![image](https://user-images.githubusercontent.com/97074458/148624670-4b847574-a048-4895-ba82-74baa45bf29d.png)
![image](https://user-images.githubusercontent.com/97074458/148624677-e087e1c2-313e-4557-a1f6-eaa71eb13dc1.png)
![image](https://user-images.githubusercontent.com/97074458/148624683-379935e8-5ea8-4da2-978a-f125dde2eeb7.png)
Do you know how to fix that?

**Comment by RinZleR121** [comment]
it's not so critical but try adding 0 after sleep so it becomes sleep0 it helped me while i was doing a ton of a characters
Also maybe there was no sleep animation in this image?
Try removing animation indices just in case.
If nothing helped let me fastly do .json of your character and if i gonna meet this problem too i will tell you.
(if you decided go let me try you just need to include animation image)
