### ISSUE TITLE
I'm unable to remove a luasprite after adding it.

### ISSUE THREAD

**Issue by Itz-Miles** [ShadowMario/FNF-PsychEngine#3280]
### Describe your problem here.

I was making an event that removes the sprite it added, but I can't figure out why it isn't being removed. Any ideas?

Code:

`function onCreate()`
        `makeAnimatedLuaSprite('fallend2', 'fallend2', -325, -185);`
        `addAnimationByPrefix('fallend2', 'fallend2', 'fallendTwo fallend', 24, false);`
        `scaleObject('fallend2', 1.5, 1.5);`
        `updateHitbox('fallend2');`
`end`

`function onEvent(name,value1,value2)`
        `if name == 'fallend2' then`
        `bool = tostring(value1);`
                `if bool == 'add' then` 
                `addLuaSprite('fallend2', false);`
                `objectPlayAnimation('fallend2', 'fallend2', true);`
                        `if bool == 'delete' then`
                        `removeLuaSprite('fallend2', true);`   
                        `end`
                `end`
       ` end`
`end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I have unrelated edits in source and other luascripts.

**Comment by RinZleR121** [comment]
you need to type `removeLuaSprite('fallend2')`
without true
and it would be better if you put end to their required places

**Comment by Itz-Miles** [comment]
> you need to type `removeLuaSprite('fallend2')` without true and it would be better if you put end to their required places

Umm... `true` in line 14 clears a 5136x4344 (22310784/.35sec) `APNG` (Animated PNG) from memory.

`end` refers to a `_Return;` statement that doesn't alter the function's state, allowing the block of code to end.
I want the block of code to read a `if` `then` statement before reading the next `if` `then` statement.
Variable `'bool'` should only equal `value2` `if`(event)`name == 'fallend2'` (If not, `'bool'` will be in every event)

..This means it should only check if `'bool'` is `'add'`, or `'delete'`, when an event `'fallend2'` occurs.
With, your premise, This means that the `onEvent()` function cannot get and set Varables and `values` on each new event, even though it states it was capable of that before. This is a new bug.

**Comment by Itz-Miles** [comment]
This variant stops a crash from occurring if something was expected in an event, but the same two values will have the same bug if they get called again.

`function onCreate()`
        `makeAnimatedLuaSprite('fallend2', 'fallend2', -325, -185);`
        `addAnimationByPrefix('fallend2', 'fallend2', 'fallendTwo fallend', 24, false);`
        `scaleObject('fallend2', 1.5, 1.5);`
        `updateHitbox('fallend2');`
`end`

`function onEvent(name,value1,value2)`
`if name == 'fallend2' then`
         `boolAdd = tostring(value1);`
        `boolDel = tostring(value2);`
        `addLuaSprite('fallend2', false);`
                `if boolAdd == 'add' then`
                `objectPlayAnimation('fallend2', 'fallend2', true);`
                `end`
                `if boolDel == 'delete' then`
                `removeLuaSprite('fallend2', false);`   
                `end`
        `end`
`end`

**Comment by Itz-Miles** [comment]
issue negated, superseded with `elseif` and `onEvent() end`
