### ISSUE TITLE
Problems with Source Code

### ISSUE THREAD

**Issue by coffeebaron** [ShadowMario/FNF-PsychEngine#3288]
### Describe your problem here.

So uh,I changed the CoolUtil.hx to add a new difficulty but it won't work.
When I enter the game,the difficulty does NOT appear besides the code and files for it all being in the right place.
I think this has to do with the .exe fie being in a different folder than the source code folder,but I'm not sure.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yeah,I edited CoolUtil.hx

**Comment by denumu07** [comment]
Did you do it Exactly like this?
![Screenshot 2022-01-13 182245](https://user-images.githubusercontent.com/89101366/149378484-5bd047e4-8f6c-4ed2-b77b-1e7bbd30304c.png)

**Comment by Theoyeah** [comment]
Go to the main Menu, and press 7.
You need to go to week editor and select your custom week, then go to others tab and put "Easy,Normal,Hard,(the name of your custom difficulty) then save the change.
(note that you need to make a chart for 4 differents difficulties
