### ISSUE TITLE
texture atlas shit

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#3290]
### Describe your bug here.

i exported a texture atlas USING ADOBE ANIMATE 2018.0.1.115 and it just gave me the "invalid char at position blah blah" thingy. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by bbpanzu** [comment]
make sure to make the json isn't a UTF-8 with BOM.

**Comment by crispyboi24** [comment]
> UTF-8 with BOM.

how can i change that? is it just in the output settings?

**Comment by bbpanzu** [comment]
just open it in notepad and change the encoding during export
