### ISSUE TITLE
Boyfriend doesn't play special animation

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#330]
Hi,
so I wanted to make boyfriend play an animation when he hit a note but he's not playing it

Here's the code for a hit:

![Screenshot (82)](https://user-images.githubusercontent.com/87707926/136943909-6ae8f2c6-d58e-412f-98b4-df0b1d8df0f4.png)

Here's the code for a miss: (boyfriend doesn't need to play an animation but I added it here if it has anything to do with it)

![Screenshot (83)](https://user-images.githubusercontent.com/87707926/136943972-2b5ed94c-2e8f-43d1-b27a-e2844a395ee8.png)

Here's the code for the note itself:

![Screenshot (84)](https://user-images.githubusercontent.com/87707926/136944048-b790db47-53db-428a-9251-e77221ae6a9b.png)

The dad character can play the animation. It is just boyfriend that can't play the animation.

**Comment by ShadowMario** [comment]
Where is this code at?

**Comment by lemz1** [comment]
I forgot to mention that it does play the normal animations.
With that i mean it plays the singLeft animation when a left arrow was hit

**Comment by ShadowMario** [comment]
You're triggering the dodge animation before the normal singing animations, which cancels the dodge animation,
Move it to here:
![Screenshot_3](https://user-images.githubusercontent.com/44785097/137042605-4a435c3e-88c2-4844-9d2c-57a0880a468a.png)
