### ISSUE TITLE
MODCHARTS

### ISSUE THREAD

**Issue by RonHereLMAO** [ShadowMario/FNF-PsychEngine#3302]
### What feature do you want to get added on the **base** engine?

modcharts.

ik basicly you can but not like from KE
ik their working on it but i think it will be a good thing cause i am tired of using noteTweenX/noteTweenY
i am not sure if this actually gonna be confirmed as a feature but i will like to see this :)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Thing that would not cause problems

**Comment by Gui-iago** [comment]
lmao
![image](https://user-images.githubusercontent.com/45212377/148633907-9638829c-88bc-408f-ab5f-6479aace33c1.png)

you can already modchart dawg, just read the wiki or the discussions page, people already did some cool shit with Psych's Lua API

**Comment by lemz1** [comment]
you don't need to use notetweenX
Just use 
`setPropertyFromGroup('playerstrums', 0, 'x', [movement])`

**Comment by RonHereLMAO** [comment]
> you can already modchart dawg, just read the wiki or the discussions page, people already did some cool shit with Psych's Lua API

im saying like tables and stuff like in KE

**Comment by RonHereLMAO** [comment]
> you don't need to use notetweenX Just use `setPropertyFromGroup('playerstrums', 0, 'x', [movement])`

does this work on 0.5.1

**Comment by lemz1** [comment]
Yes it works on 0.5.1

**Comment by matt-sudo-jpg** [comment]
nvm i found out kik
