### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by xDItsTej** [ShadowMario/FNF-PsychEngine#3305]
### Describe your problem here.

I made a custom animation that isn't Up, Down, Left, Right, or idle, but it gives me an error when I use it in the character creator menu. Do you know how to fix it?
[neoxml.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/7832420/neoxml.zip)
![image](https://user-images.githubusercontent.com/97074458/148627779-f9ea6490-230e-4f5d-a90b-349c86f9407a.png)

 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not anything that affects this.

**Comment by xzh3r** [comment]
you misspelled the animation name in the xml

**Comment by xDItsTej** [comment]
The animation name is "neo sleep." How did I misspell that?

**Comment by frantastic24** [comment]
You forgot to close the multiple issues you opened for whatever reason
