### ISSUE TITLE
awards

### ISSUE THREAD

**Issue by cyborghenrystickmin** [ShadowMario/FNF-PsychEngine#331]
this isnt a issue, its just i dont know how to add custom awards

**Comment by MayoALT** [comment]
awards are really easy to add now so you can close this issue

**Comment by acap09** [comment]
this is probably the oldest open issue with no pull requests linked. also i guess close this issue since i dont see the point of it being open now?

**Comment by Mastercopper2346** [comment]
Yes

**Comment by cinnadust** [comment]
olde

**Comment by tylerandari12** [comment]
Ye Olde Issue

**Comment by Minalog** [comment]
> olde

olde

**Comment by someonewhoexsits** [comment]
funny how people haven't asked to take this down but other people do with other things
