### ISSUE TITLE
make image spin?

### ISSUE THREAD

**Issue by xzh3r** [ShadowMario/FNF-PsychEngine#3314]
### Describe your problem here.

how do you make an image spin forever through the song, like in gospel? i need to

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by RinZleR121** [comment]
```
local timeshit = 0
function onUpdate()
	doTweenAngle('imageSPIIIN', 'YOURIMAGENAME', timeshit, 0.001, 'linear')
	timeshit = timeshit+'HOWMUCHDOYOUWANNAROTATE(place 1 0.5 or other number)'
end
```

**Comment by RinZleR121** [comment]
in `timeshit = timeshit+'this monstrosity'` change 'this monstrosity' to a number WITHOUT quotes

**Comment by xzh3r** [comment]
thanks

**Comment by xzh3r** [comment]
it doesnt work
