### ISSUE TITLE
Custom Noteskins Addition :)

### ISSUE THREAD

**Issue by CC-J4xon** [ShadowMario/FNF-PsychEngine#3316]
### What feature do you want to get added on the **base** engine?

Like The Bob And Bosip Mod, Can Each Character Have A Different Noteskin?

You Could Give Them All The Same Noteskin, Or You Could Make Them All Seperate Ones :)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
This is already possible with lua. (Change `texture` property.)

**Comment by CC-J4xon** [comment]
> This is already possible with lua. (Change `texture` property.)

Can You Send The Link To It?
