### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by xDItsTej** [ShadowMario/FNF-PsychEngine#3322]
### Describe your problem here.

This is the 3rd time I'm posting this because the 1st and 2nd times, people didn't help. (no offence)
But I have an animation on one of my characters that isn't "↓,→,↑, or←" It's a custom animation called "sleep" and I can't get it to work. Does anyone know why? 
![image](https://user-images.githubusercontent.com/97074458/148648139-1b9e0582-2ecc-4078-aa70-45e23e7648a3.png)
[neoxml.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/7833382/neoxml.zip)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not anything that affects this.

**Comment by RonHereLMAO** [comment]
look at the xml, see the up,down,left,right.idle words or i can do it for you

**Comment by blaidev** [comment]
i can do it

**Comment by xDItsTej** [comment]
Okay, if you do it I will put you in the credits! If you don't want to, just tell me if there is a way to fix it. 
(you may need to put it in a .zip file)

**Comment by RonHereLMAO** [comment]
> 

alr

**Comment by frantastic24** [comment]
from what i saw in one of your previous posts you have animation indices that don't exist, giving you an error

**Comment by xDItsTej** [comment]
> from what i saw in one of your previous posts you have animation indices that don't exist, giving you an error

Okay, I'm kinda dumb so I don't really know what you mean. But yes, the animation works fine. It's just the "sleep" animation.

**Comment by frantastic24** [comment]
leave this blank for that animation and it should fix the issue
![image](https://user-images.githubusercontent.com/95725102/148664084-1856e75e-a9aa-4c3c-a704-baff1040a9a0.png)

**Comment by xDItsTej** [comment]
> leave this blank for that animation and it should fix the issue, in the .xml file you sent the sleep animation only has 12 frames while you're assigning frame 50+ to this animation, which don't exist ![image](https://user-images.githubusercontent.com/95725102/148664084-1856e75e-a9aa-4c3c-a704-baff1040a9a0.png)

Oh my god thank you so much.
