### ISSUE TITLE
How to add a stage?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#3323]
### What is your question?

I try adding a stage following the steps below:

1、There is  a `stage02.png` file, I put it into `mods\images` folder.
2、Copy stage.json, and put it into `mods\stages`, and rename it to stage02.json.

after loading the game, press 7, and chosing stage02, but it fail.

![image](https://user-images.githubusercontent.com/13177997/148650511-fadbe483-0f75-4fb9-84e1-b215101f71b9.png)

What should I do?

**Comment by Fire220Creep** [comment]
Can You Give Me A Copy Of The .json And .lua Files?

**Comment by zwl1619** [comment]
I fix it.
