### ISSUE TITLE
Using the noteTween functions

### ISSUE THREAD

**Issue by OrangeHairr** [ShadowMario/FNF-PsychEngine#3324]
### Describe your problem here.

WHAT AM I DOING WRONG?!
<img width="488" alt="‏‏WRONG" src="https://user-images.githubusercontent.com/95587502/148652775-cc852613-b2ff-4204-ac67-c34aed6704e4.PNG">

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by blaidev** [comment]
![01fc74776459cb79b0b0d2199aaaab4d](https://user-images.githubusercontent.com/85421187/148653348-557dea94-f171-4df5-93bb-ba053886362c.jpg)
idk noob

**Comment by SrtHero278** [comment]
ok so variables have a certain way to define it. you need to put local in front of it.
```
local Move = 7;
local Dur = 1;
```

**Comment by OrangeHairr** [comment]
the variables don't need to be local to work, but i still tried it, and it didn't work. thanks though!

**Comment by OrangeHairr** [comment]
HECK! I tried to do everything without variables and IT STILL DOESN'T WORK!!!
WHAT THE FRICK IS WRONG IN HERE?!?!
<img width="520" alt="‏‏WRONG" src="https://user-images.githubusercontent.com/95587502/148656858-87009eca-6fd8-43df-85d7-70a67fb627aa.PNG">

**Comment by XxjuandisxX** [comment]
you already tried removing those 2
![image](https://user-images.githubusercontent.com/95830200/148658327-81e47d33-b23a-48bf-8ab4-41e4ec682dc4.png)

**Comment by mayo78** [comment]
> ok so variables have a certain way to define it. you need to put local in front of it.
> 
> ```
> local Move = 7;
> local Dur = 1;
> ```

no you dont??? that makes it so only those values are only changeable in the lua file its in

**Comment by OrangeHairr** [comment]
yea, but is it necessary? not really. the thing doesn't work even if I don't use these variables, but I guess making them local won't hurt anyone, right? actually, i initially had them set up like this:
<img width="509" alt="‏‏WRONG" src="https://user-images.githubusercontent.com/95587502/148671921-4e40a661-4eaa-40f6-978f-421a1d6c462b.PNG">
