### ISSUE TITLE
Spin in lua

### ISSUE THREAD

**Issue by XxjuandisxX** [ShadowMario/FNF-PsychEngine#3327]
### Describe your problem here.

How do I make an object object rotate in the Lua file?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by mayo78** [comment]
[doTweenAngle](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers)

**Comment by XxjuandisxX** [comment]
> 

love you

**Comment by XxjuandisxX** [comment]
> [doTweenAngle](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers)

You did not understand me, I mean, what object is rolling in a loop

**Comment by Grape-Boy** [comment]
```lua
function onUpdate()
    setProperty('boyfriend.angle', getProperty('boyfriend.angle') + 1)
end
```

**Comment by XxjuandisxX** [comment]
> ```lua
> function onUpdate()
>     setProperty('boyfriend.angle', getProperty('boyfriend.angle') + 1) -- change 1 to a higher value to make him spin faster
> end
> ```

when I put that text the object moves but it doesn't start to spin in loop
