### ISSUE TITLE
the opponent is suppose to change

### ISSUE THREAD

**Issue by GithubBonnie420** [ShadowMario/FNF-PsychEngine#3328]
### Describe your bug here.

i was testing out of the change character event is changed but it hasn't been fixed, i need it fixed (not beging)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes

**Comment by Stilic** [comment]
What files you have edited exactly?

**Comment by frantastic24** [comment]
AT LEAST show the code before labeling as a bug
