### ISSUE TITLE
The Game Crashes When I Die

### ISSUE THREAD

**Issue by OOF-PRODUCTIONS** [ShadowMario/FNF-PsychEngine#3334]
### Describe your bug here.

Every Time I Die Or Reset Crashes The Game And Idk Why Or How To Fix It

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i added an extra week a loading screen a custom title screen a secret song with a code in the main menu cpu notes events and a custom main menu so far

**Comment by maxisepYT1** [comment]
That happens when you make too **many changes in a short period of time**.

I don't know how to fix it with code, but the solution that worked for me is to reinstall all the source code from 0.

I hope I've helped!
