### ISSUE TITLE
Files remain active in build, even after removal

### ISSUE THREAD

**Issue by snazzyostrich** [ShadowMario/FNF-PsychEngine#3335]
### Describe your bug here.

read the title. this happens with scripts as well as weeks. i need them removed but they wont leave

### Command Prompt/Terminal logs (if existing)

```bash
none
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by mayo78** [comment]
when you compile, it only ADDS files, never removes. you have to remove the assets file in the bin itself for the file to be gone

**Comment by MeowcaTheoRange** [comment]
This is a HaxeFlixel problem. You have to delete the files you need removed manually.

**Comment by skedgyedgy** [comment]
-- it's not even a haxeflixel probelm this is just how building is handled by most things. you can do "lime clean windows" or "lime clean windows -debug" for whatever your build target is to clean up the folder, or just delete them yourself
