### ISSUE TITLE
Easter Egg (Beta icon)

### ISSUE THREAD

**Issue by xDItsTej** [ShadowMario/FNF-PsychEngine#3337]
### What feature do you want to get added on the **base** engine?

When you press the "9" key on normal Friday Night Funkin' it makes BF's icon the beta version. I kinda just wanted this for my mod as an easter egg to another mod I made.

**And no, this is not a winning icons request**

![image](https://user-images.githubusercontent.com/97074458/148664761-73980ca0-8120-4862-a74d-50c75f152ebe.png)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Gui-iago** [comment]
go to PlayState.hx, search for
`override public function update(elapsed:Float)`

remove these /* */ from this text

![image](https://user-images.githubusercontent.com/45212377/148664805-b6d8ed77-3fc1-4065-87f1-4782ba9d39d5.png)

**Comment by xDItsTej** [comment]
Uhh, how do I get to PlayState.hx?

**Comment by Gui-iago** [comment]
> Uhh, how do I get to PlayState.hx?

you need the source code

**Comment by xDItsTej** [comment]
> 

Okay, I'll try to figure out how to get there.
I'm gunna close this now.
