### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by Trenton0** [ShadowMario/FNF-PsychEngine#3338]
### Describe your problem here.

how do I make the Freeplay screen scroll down?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

edited freeplaystate.hx to center the song texts

**Comment by aflacc** [comment]
1st of all, don't name your issue "help!". The name should explain what help you need. In this case, something like "How do I scroll the Freeplay screen down".

2nd of all, I'm not exactly sure what you need help with, because the up and down controls should already do that?

**Comment by Trenton0** [comment]
Nevermind i figured it out
