### ISSUE TITLE
Game name changing based on what mod you have enabled 

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#3340]
### What feature do you want to get added on the **base** engine?

When you have a mod loaded, it changed the discord RPC icon and name. And also the window name to the mods name. The mod name would be the name of the mod that’s at the top of the list, or if your playing a mod song, the songs mod name.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by 4wdthinks** [comment]
i have seen mods do this  with songs but im not sure how.

**Comment by tposejank** [comment]
> i have seen mods do this  with songs but im not sure how.

Application.current.window.title

**Comment by bbpanzu** [comment]
setPropertyFromClass('lime.app','Application.current.window.title', 'NEW TITLE')

**Comment by crispyboi24** [comment]
> setPropertyFromClass('lime.app','Application.current.window.title', 'NEW TITLE')

HO!Y SHIT THANK YOU
