### ISSUE TITLE
runTimer doesn't work on lua

### ISSUE THREAD

**Issue by Dinoturto** [ShadowMario/FNF-PsychEngine#3342]
### Describe your bug here.

I've had some issues with timers in the lua api, I tried using runTimer but it just errors everytime and I can't find any way to fix it

### Command Prompt/Terminal logs (if existing)

```bash
None
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by bbpanzu** [comment]
what errors?

**Comment by aflacc** [comment]
> what errors?

Theres a few different things I'm assuming he could be referring to:
1) maybe he thinks runTimer should pause the code?? (if this is what is being referred to in the issue, it doesn't.)
2) maybe he doesnt understand the way that runTimer works,
basically you assign a tag to the timer, and then when the timer ends, the `onTimerEnded` function is called, it has a variable for the tags. Just check if that variable == the tag you want.

**Comment by MayoALT** [comment]
its actually `onTimerCompleted` not `onTimerEnded`

**Comment by aflacc** [comment]
> its actually `onTimerCompleted` not `onTimerEnded`

Yes, sorry.

**Comment by Dinoturto** [comment]
> what errors?

it thinks that "runTimer" isn't a function, and yes I am using onTimerCompleted. do i need to send a code snippet

**Comment by Dinoturto** [comment]
> > what errors?
> 
> Theres a few different things I'm assuming he could be referring to:
> 
> 1. maybe he thinks runTimer should pause the code?? (if this is what is being referred to in the issue, it doesn't.)
> 2. maybe he doesnt understand the way that runTimer works,
>    basically you assign a tag to the timer, and then when the timer ends, the `onTimerEnded` function is called, it has a variable for the tags. Just check if that variable == the tag you want.

i know that runTimer doesn't instantly pause the code, and I know you're supposed to assign a tag, the amount of time, and the number of loops, and I also use onTimerCompleted with the correct tag, it just thinks that runTimer isn't a function for some reason
