### ISSUE TITLE
custom cpu note bug

### ISSUE THREAD

**Issue by Benby3** [ShadowMario/FNF-PsychEngine#3343]
### Describe your bug here.

i trying this code:

`
function onUpdate()
	if dadName == 'name' then --replace the name for your character name and you can replace dadName as boyfriendName or gfName.
		for i=0,4,1 do
			setPropertyFromGroup('opponentStrums', i, 'texture', 'notetexturename') --Put opponentStrums for opponent or playerStrums for bf.
		end
		for i = 0, getProperty('unspawnNotes.length')-1 do
			if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') and getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' then --Put a not before the first getPropertyFromGroup to opponent change texture.
				setPropertyFromGroup('unspawnNotes', i, 'texture', 'notetexturename'); --Change texture
			end
		end
	end
end
`

but just happen this error
![image](https://user-images.githubusercontent.com/96499074/148666112-efeae2e0-8865-45db-8695-0fd2638d2f67.png)

dont care what i make in the code, all i make just give more than this error. 
i think this totally a bug, not about the code.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i edited all thing haves in source and somes in the rest, like assets and example_mods.

**Comment by tarp2020** [comment]
if your note texture name is not called notetexturename no wonder it would be null because it doesn't exist. I recommend changing notetexturename to your note texture name

**Comment by Benby3** [comment]
> if your note texture name is not called notetexturename no wonder it would be null because it doesn't exist. I recommend changing notetexturename to your note texture name

i know it, i changed. but dont works again, look this:

`function onUpdate()
	if dadName == 'bambi_angryboy' then --replace the name for your character name and you can replace dadName as boyfriendName or gfName.
		for i=0,4,1 do
			setPropertyFromGroup('opponentStrums', i, 'texture', 'NOTE_assets_3D') --Put opponentStrums for opponent or playerStrums for bf.
		end
		for i = 0, getProperty('unspawnNotes.length')-1 do
			if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') and getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' then --Put a not before the first getPropertyFromGroup to opponent change texture.
				setPropertyFromGroup('unspawnNotes', i, 'texture', 'NOTE_assets_3D'); --Change texture
			end
		end
	end
end`

**Comment by Benby3** [comment]
sorry for all guys
i forget the xml of the arrow
and because this the arrow dont changes, so sorry.
