### ISSUE TITLE
VCR Shaders Bug

### ISSUE THREAD

**Issue by MorenoTheCappuccinoChugger** [ShadowMario/FNF-PsychEngine#3344]
### Describe your bug here.

When I try to use the VCR shaders, the game shows a error message, when I continue the game crashes (I used mac and windows but am listing mac here)

<img width="610" alt="Screen Shot 2022-01-09 at 11 29 59 AM" src="https://user-images.githubusercontent.com/97181979/148691334-42c650fb-0001-4cc4-81ef-ba3c9ac0fdc4.png">

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No I didn't change, its completely lua

**Comment by Benby3** [comment]
> ### Describe your bug here.
> When I try to use the VCR shaders, the game shows a error message, when I continue the game crashes (I used mac and windows but am listing mac here)
> 
> ### Command Prompt/Terminal logs (if existing)
> _No response_
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Mac
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No I didn't change, its completely lua

what's the error? i can't help if you don't say whats happening lol

**Comment by bbpanzu** [comment]
what's ya lua lookin like

**Comment by MorenoTheCappuccinoChugger** [comment]
> what's ya lua lookin like
function onCreatePost()
	addVCREffect('game')
end
