### ISSUE TITLE
Background boppers showing up as an error

### ISSUE THREAD

**Issue by CrunchBar41** [ShadowMario/FNF-PsychEngine#3345]
### Describe your problem here.

I'm trying to add extra background boppers similar to week 5 with the latest build and am using code similar to what I had previously used. This is what it looks like in game:
![image](https://user-images.githubusercontent.com/95093250/148667101-ab31f75a-aea5-4153-ae56-1edeabfb9ede.png)

And this is the code for it:
![image](https://user-images.githubusercontent.com/95093250/148667145-9a184302-d141-4388-b1c9-ff677399e6d4.png)

Using that code for pretty much all the background entities and works fine for everything else except the ones I'm trying to add now.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by tposejank** [comment]
make sure the image is called "eh(.png/.xml)" and that it is in mods/images

**Comment by CrunchBar41** [comment]
Ah thanks, I forgot that the second variable was supposed to be the name of the files. Thank you!
