### ISSUE TITLE
custom gameovers

### ISSUE THREAD

**Issue by ethannn123** [ShadowMario/FNF-PsychEngine#3346]
### What feature do you want to get added on the **base** engine?

I have many playable characters, but they all have bfs gameover, is there a way that we could do custom gameovers in LUA?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tposejank** [comment]
setPropertyFromClass('GameOverSubstate', 'characterName', 'eiwnrinsiwtbbksnsn')

**Comment by ethannn123** [comment]
thx!!!

**Comment by ethannn123** [comment]
> setPropertyFromClass('GameOverSubstate', 'characterName', 'eiwnrinsiwtbbksnsn')

Is "eiwnrinsiwtbbksnsn" the sound file?

**Comment by NotEpik** [comment]
> > setPropertyFromClass('GameOverSubstate', 'characterName', 'eiwnrinsiwtbbksnsn')
> 
> Is "eiwnrinsiwtbbksnsn" the sound file?

the example script -> https://cdn.discordapp.com/attachments/889357899015540736/901470021652447233/script.lua

you should check in https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API before doing question, bruh :|
