### ISSUE TITLE
Characters won't Idle | Null Error 

### ISSUE THREAD

**Issue by ItsLJcool** [ShadowMario/FNF-PsychEngine#3348]
### I added Some character from Bob mod, and the characters will not idle at all, sometimes it gives me an error at a line of code:
if(curBeat % 2 == 0) {
			if (boyfriend.animation.curAnim.name != null && !boyfriend.animation.curAnim.name.startsWith("sing"))
			{
				boyfriend.dance();
			}
          		if (dad.animation.curAnim.name != null && !dad.animation.curAnim.name.startsWith("sing") && !dad.stunned)
		        {
			         dad.dance();
		        }
		} else if(dad.danceIdle && dad.animation.curAnim.name != null && !dad.curCharacter.startsWith('gf') && !dad.animation.curAnim.name.startsWith("sing") && !dad.stunned) {
			dad.dance();
		}
![image](https://user-images.githubusercontent.com/54383469/148669629-4ace1acb-2b6f-4de8-b996-761197f96e63.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited some MainMenuState.hx, added stuff in PlayState

![image](https://user-images.githubusercontent.com/54383469/148669730-3366e0ed-93e8-47dd-9e87-642d82301910.png)
![image](https://user-images.githubusercontent.com/54383469/148669740-887ef85f-c6ca-4f7d-89ed-64b620c64ef3.png)

**Comment by tposejank** [comment]
make sure you added the correct animation xml names

**Comment by ItsLJcool** [comment]
> make sure you added the correct animation xml names

I did, and it still crashes the game
