### ISSUE TITLE
Downloading

### ISSUE THREAD

**Issue by BananaSwitch** [ShadowMario/FNF-PsychEngine#3352]
### Describe your problem here.

Is it me or does downloading the psych engine code take forever for me to download and never works?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by tposejank** [comment]
skill issue

**Comment by bbpanzu** [comment]
skill issue

**Comment by BananaSwitch** [comment]
Damn 💀 I’ll fix it though

**Comment by denumu07** [comment]
Bro 💀 The 0.5x Version of the Engine is WITHOUT Mods around 800MB, what did you expect.

**Comment by Theoyeah** [comment]
Money skill issue :/
