### ISSUE TITLE
stage swicharoo

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#3353]
### What feature do you want to get added on the **base** engine?

idk if this counts as asking for stage editor if so please don't ban me I didn't know i just think that there could be a new event called "change stage" and as you probably know by now... it changes the stage to a different one just an idea

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by 4wdthinks** [comment]
it would cause lag though. it probably won't happen

**Comment by creeperkidking** [comment]
thats ok a little bummed but ok

**Comment by tposejank** [comment]
NO FUCK OFF

**Comment by 4wdthinks** [comment]
> NO FUCK OFF

the agression

**Comment by HiroMizuki** [comment]
welpp, shadow mario already said that don't want it cuz it will become harder to code stages, so, probably he'll close it

**Comment by creeperkidking** [comment]
btw when i first asked for it it was cuz of the return of hex and how the stage changes at sometimes in glitcher

**Comment by Uniimations** [comment]
add more lua sprites on an event yourself or change the alpha of already loaded sprites in a stage script on a beat hit

**Comment by creeperkidking** [comment]
I don't use Lua or code

**Comment by aflacc** [comment]
Actually, I have done this *technically*. Check it out [here](https://www.youtube.com/watch?v=dGK3v1WTjcQ). only thing is that the stages used here were specifically made for the song. Basically the song has a modchart, and inside it theres a function called something like `switchStage(id)` or something like that i forgot

basically, it accepts numbers `1`,`2`, `3` and `4` for the 4 different stages I used.

A lot of the code abuses the way the lua tags are handled, meaning that if you create a new lua object that has a tag that was already used, it replaces it.

I do think it would be neat to have a way to just swap out stages, but it would probably cause a lot of issues.

I'd show you the code but I am not at my computer at the moment. Sorry about that!
