### ISSUE TITLE
song

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#3355]
### What is your question?

not really a question idk if I can get banned for this but I made a song for my mod and put it on my channel and would like to know what you think of it here's the link: https://www.youtube.com/watch?v=wRg5de9SXOg 
btw I'm not I master at music so I'm surprised is sounded that good

**Comment by Stilic** [comment]
You should show that in [the repository's discussion section](https://github.com/ShadowMario/FNF-PsychEngine/discussions).

**Comment by bbpanzu** [comment]
this is for psych engine questions only. share that on a fnf general chat no github

**Comment by creeperkidking** [comment]
oh ok
