### ISSUE TITLE
How can I disable enemy's strum note glowing thingy?

### ISSUE THREAD

**Issue by TahirArch** [ShadowMario/FNF-PsychEngine#3358]
### What is your question?

I want classic FNF style but when I remove skin codes from StrumNote.hx, player's notes do not glow too.
How can I disable it?

**Comment by BeansCool54** [comment]
Find the line StrumPlayAnim(true, Std.int(Math.abs(note.noteData)) % 4, time);
note.hitByOpponent = true;
Then remove the StrumPlayAnim(true, Std.int(Math.abs(note.noteData)) % 4, time);
I think it works

**Comment by TahirArch** [comment]
> Find the line StrumPlayAnim(true, Std.int(Math.abs(note.noteData)) % 4, time); note.hitByOpponent = true; in PlayState.hx Then remove the StrumPlayAnim(true, Std.int(Math.abs(note.noteData)) % 4, time); I think it works

It worked, thank you!

**Comment by TahirArch** [comment]
> Find the line StrumPlayAnim(true, Std.int(Math.abs(note.noteData)) % 4, time); note.hitByOpponent = true; in PlayState.hx Then remove the StrumPlayAnim(true, Std.int(Math.abs(note.noteData)) % 4, time); I think it works

It worked, thank you!
