### ISSUE TITLE
How do I add animated (bopping) object to background

### ISSUE THREAD

**Issue by notpingo** [ShadowMario/FNF-PsychEngine#3359]
### Describe your problem here.

I managed to get the sprite loaded but the animation simply doesn't play.
Looked for BB's tutorial and even then it didn't work

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
show the code and the .xml of the sprite

**Comment by CrunchBar41** [comment]
Are you doing something like this?
![image](https://user-images.githubusercontent.com/95093250/148700657-3713d5c6-2152-420a-85c6-396f198c7f13.png)

And to get it to bop afterwards with code like that, you use this code:
![image](https://user-images.githubusercontent.com/95093250/148700682-667bf0ff-cd3c-44a9-a4dc-d39887a8c8bb.png)

**Comment by swordcube** [comment]
i know why it doesn't play, remove `close(true)` if you have animated sprites in your lua script, for some reason `close(true)` breaks everything

**Comment by ImaginationSuperHero528** [comment]
curBeat % 2 == 1

**Comment by notpingo** [comment]
> i know why it doesn't play, remove `close(true)` if you have animated sprites in your lua script, for some reason `close(true)` breaks everything

thank you, this took me way longer than it should have
