### ISSUE TITLE
 impossible to use event change character in 0.5.1

### ISSUE THREAD

**Issue by bf244** [ShadowMario/FNF-PsychEngine#3360]
### Describe your bug here.

when i try to use the event change character it crashes

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by PersonNanoexe** [comment]
Never had an issue with this, youre probably using the event wrong

**Comment by LukasRainbow** [comment]
I actually had the Same Problem.
I entered the Event in multiple Ways and just couldn't get it to work.

**Comment by ImaginationSuperHero528** [comment]
value1: dad, BF or GF (for some reason I have to have the casing like like idk why)
value2: New Character (Example: pico-player)

**Comment by MayoALT** [comment]
actually in value one you put a number 0-2,
0 - bf
1 - dad
2 - gf

**Comment by ImaginationSuperHero528** [comment]
> actually in value one you put a number 0-2, 0 - bf 1 - dad 2 - gf

Yeah data old way in newer versions it says the way I did
