### ISSUE TITLE
How to skip straight to a week when you hit story mode.

### ISSUE THREAD

**Issue by WeldedFlap** [ShadowMario/FNF-PsychEngine#3367]
### Describe your problem here.

I'm trying to make it so that when you hit story mode it sends you directly to a certain week. I've tried with the Cassette Girl source code but that doesnt work. I just left the thing on MainMenuState as `MusicBeatState.switchState(new StoryMenuState());`

![image](https://user-images.githubusercontent.com/90015471/148691225-6063b8f3-86d8-40fb-85aa-014a2b1ace16.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Removed Easy And Hard Difficulties, Added Some Stuff To The Main Menu, Added A Week, And Removed The GF Part On The Title Screen

**Comment by HiroMizuki** [comment]
about a week, i rlly don't know, but for a song, u use loadFromJson

**Comment by dkoea** [comment]
> about a week, i rlly don't know, but for a song, u use loadFromJson

how do you do that exactly?
![image](https://user-images.githubusercontent.com/85266666/148697871-46557dfe-3ea7-419c-b03f-003ae5523349.png)
something like this?

**Comment by HiroMizuki** [comment]
> > about a week, i rlly don't know, but for a song, u use loadFromJson
> 
> how do you do that exactly? ![image](https://user-images.githubusercontent.com/85266666/148697871-46557dfe-3ea7-419c-b03f-003ae5523349.png) something like this? or would I just leave the brackets, im quite new to source coding

nope, it's like this
![image](https://user-images.githubusercontent.com/72695242/148698145-461bb5d8-28d1-4de0-bbe7-3d6a90d622c2.png)

**Comment by HiroMizuki** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/85266666/148785989-c664c8fb-1196-4a3d-904e-8d868ce70ce6.png) ![image](https://user-images.githubusercontent.com/85266666/148786140-10e2b729-542e-478d-88e5-a0180259cf85.png)
> 
> I did that but it just gives me this error everytime, I do have the tutorial folder in there

welp, this happened to me too, i rlly don't know how to fix it
maybe that's a haxe issue
