### ISSUE TITLE
How to Add More Freeplay Sections

### ISSUE THREAD

**Issue by ByronisJoan** [ShadowMario/FNF-PsychEngine#3368]
### Describe your problem here.

It's Not a Port or Anything, But How Do i Add More Freeplay Sections From The Dave & Bambi Mod?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No I did not Edit anything In my build

**Comment by HiroMizuki** [comment]
maybe try to get it from dave and bambi source

**Comment by PDL2CGamejolt** [comment]
lua

**Comment by ByronisJoan** [comment]
> lua

I never Said Anything For Lua For this Issue

**Comment by ByronisJoan** [comment]
> > lua
> 
> I never Said Anything About Lua For this Issue

**Comment by Uniimations** [comment]
you gotta learn how to code from scratch fool

**Comment by ByronisJoan** [comment]
> you gotta learn how to code from scratch fool

Who said You can Call me A fool?

**Comment by imdoingthisfortheprofile** [comment]
> maybe try to get it from dave and bambi source

dave and bambi uses kade engine, not sure if you could port it over

**Comment by HiroMizuki** [comment]
> > maybe try to get it from dave and bambi source
> 
> dave and bambi uses kade engine, not sure if you could port it over

yeah, maybe there's a way

**Comment by ByronisJoan** [comment]
Ok I just FIgured it Out, If You Wanna Know, Whatsdown Uploaded The Source code https://github.com/WhatsDownYT/VDAB-DefinitiveEdition

**Comment by ByronisJoan** [comment]
> Ok I just FIgured it Out, If You Wanna Know, Whatsdown Uploaded The Source code https://github.com/WhatsDownYT/VDAB-DefinitiveEdition

**Comment by PDL2CGamejolt** [comment]
> Ok I just FIgured it Out, If You Wanna Know, Whatsdown Uploaded The Source code https://github.com/WhatsDownYT/VDAB-DefinitiveEdition

It’s deleted now l
