### ISSUE TITLE
i changed some idea i had in the past lmao

### ISSUE THREAD

**Issue by HiroOfc** [ShadowMario/FNF-PsychEngine#337]
i had questioned how to make a stage change without events, but it looks harder than using events
so, how can i make a event with stage change?

**Comment by ShadowMario** [comment]
I'm pretty sure i've already told you how to make this on source code, but not on Lua. So i will just say both again
Haxe (The easiest way i can think of):
1. Make 2 FlxSpriteGroups, one for Stage 1 (`stage1Group`) and the other for Stage 2 (`stage2Group`)
2. Add the sprites to their respective groups with `stage1Group.add(sprite);` and `stage2Group.add(sprite);`
3. Hide stage2Group with `stage2Group.visible = false;`
4. When the event for changing bg is called, do this:
```
stage1Group.visible = false;
stage2Group.visible = true;
```

Lua:
1. Create all objects from Stage 1 and Stage 2
2. Make it hide the objects from Stage 2
3. When the custom event is called for changing BG, make it hide Stage 1 sprites and show Stage 2 sprites
