### ISSUE TITLE
Bug: fullscreen mode doesn't work

### ISSUE THREAD

**Issue by m-obeid** [ShadowMario/FNF-PsychEngine#3370]
### Describe your bug here.

When you enter fullscreen with F it works on TitleState but when you get to MainMenuState.hx it goes back

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not yet

**Comment by skedgyedgy** [comment]
-- someone put in a questionable update recently that changes the resolution to a default every time you switch menus. fixed in #3374 but until then you'll have to go into the game settings > graphics > resolution to enable it

**Comment by ImaginationSuperHero528** [comment]
That's a weird bug it never really happened to me but if you get it again press Alt + Enter it works on every app I believe it's a shortcut fullscreen key for anything on windows

**Comment by skedgyedgy** [comment]
> That's a weird bug it never really happened to me but if you get it again press Alt + Enter it works on every app I believe it's a shortcut fullscreen key for anything on windows

![image](https://user-images.githubusercontent.com/96351114/148848310-94d6053d-df14-4cd6-b1f8-88645946508b.png)

**Comment by ImaginationSuperHero528** [comment]
> > That's a weird bug it never really happened to me but if you get it again press Alt + Enter it works on every app I believe it's a shortcut fullscreen key for anything on windows
> 
> ![image](https://user-images.githubusercontent.com/96351114/148848310-94d6053d-df14-4cd6-b1f8-88645946508b.png)
> 
> -- it was a thing and it wasn't a bug, it was hardcoded into the engine to act that way for a few days

Uh yeah never knew til yesterday
