### ISSUE TITLE
Difficulty Back Button 

### ISSUE THREAD

**Issue by PumpTutorials** [ShadowMario/FNF-PsychEngine#3372]
### Describe your bug here.

So I was testing a bob and bosip port (before the drama) in psych engine in the newest version, I clicked change difficulty by accident and I wanted to get out of it so I clicked the back button under hard and it said couldn't find jump-in-null so I am guessing it thought the back button was a difficulty and the "difficulty" for the back button is named null so I got that error.

![Screenshot 2022-01-09 121645](https://user-images.githubusercontent.com/84157253/148692989-517989e8-1ae9-4055-adff-1789130f4fbc.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added songs, a difficulty, and a few characters the only thing that I edited that could possible make this happen is adding the EX difficulty

**Comment by DarkMinerULTRA** [comment]
It's not your bug, it's from the engine itself; i got it too. Guess it'll be patched in the next version.

**Comment by bbpanzu** [comment]
fixed in source. you can wait till the next update

**Comment by aflacc** [comment]
> fixed in source. you can wait till the next update

thank you good sir

**Comment by DarkMinerULTRA** [comment]
> fixed in source. you can wait till the next update

epic, thank you gamer

**Comment by BombasticTom** [comment]
you've guys noticed the bug just now?

**Comment by BombasticTom** [comment]
oh wait this page is 25 days long.. sorry
