### ISSUE TITLE
Error reloading image - Please Help Me :'c

### ISSUE THREAD

**Issue by SixGodXD** [ShadowMario/FNF-PsychEngine#3379]
### What is your question?

Sorry for my bad english.

I have a problem and that is that I already have the .xml and the spritesheet in "mods\My Mod\images\characters" 
![image](https://user-images.githubusercontent.com/97413418/148704491-6ba81e63-563d-4718-9209-fede447120f3.png)

And when I put the name of the .xml and I click in reload image gives me this error
![image](https://user-images.githubusercontent.com/97413418/148704592-e711750f-15f0-4b2f-ad75-8c4986303be1.png)

I'm on the Directory of the mod
![image](https://user-images.githubusercontent.com/97413418/148704713-2bea7197-fc3d-4ff4-8263-bcfbd910d1c3.png)

If I put the icon if I put it, but it does not let me load the image
![image](https://user-images.githubusercontent.com/97413418/148704760-c4d75580-cf95-4161-9ee0-97ce924d245a.png)

I tried my best, but couldn't fix it

**Comment by PumpTutorials** [comment]
I'm pretty sure you could've gotten a build that was broken so try reinstalling psych engine and add back what you did and see if that works because I'm using the un-edited build without source and it works completely fine.

**Comment by SixGodXD** [comment]
Keep crashing :/

**Comment by Playertrip777** [comment]
What's your psych engine version?

**Comment by SixGodXD** [comment]
> What's your psych engine version?

0.5.2

**Comment by Playertrip777** [comment]
Use the stable release. 0.5.1 Sent from Mail for Windows From: SixGodXDSent: Monday, 10 January, 2022 11:54 AMTo: ShadowMario/FNF-PsychEngineCc: Playertrip777; CommentSubject: Re: [ShadowMario/FNF-PsychEngine] Error reloading image - Please Help Me :'c (Issue #3379) What's your psych engine version?0.5.2—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by Playertrip777** [comment]
Use the stable release, 0.5.1

**Comment by SixGodXD** [comment]
> Use the stable release, 0.5.1

I also Brought whit 0.5.1, 0.5.0 and 0.4.2

**Comment by Playertrip777** [comment]
Then use version 0.5.1

**Comment by SixGodXD** [comment]
> Then use version 0.5.1

Already, still crashing

**Comment by Playertrip777** [comment]
Send me your spritsheet and xml

**Comment by SixGodXD** [comment]
> Send me your spritsheet and xml

https://drive.google.com/drive/folders/1ppJ0DrNSTdj89DV6PDqIFA4hnm0ilPqG?usp=sharing

**Comment by Playertrip777** [comment]
Try to reduce the amount of frames each sprite have.

**Comment by SixGodXD** [comment]
> Try to reduce the amount of frames each sprite has.

Ok, I'll try it
