### ISSUE TITLE
Custom credits not working and cant be seen.

### ISSUE THREAD

**Issue by DarkMinerULTRA** [ShadowMario/FNF-PsychEngine#3387]
### Describe your bug here.

The credits scrolls off screen immediately, and it doesn't even write the lines properly. I have put the credits.txt into mods/nabs (my mod folder)/data. and put the icons in mods/nabs/images/credits. Here is an image of it before it scrolled off screen:
![Screen Shot 2022-01-10 at 12 25 31 pm](https://user-images.githubusercontent.com/78901200/148710591-fc3413f7-23a4-45a8-98f7-4ab13a8c6376.png)
And here is the credits.txt file:
"Creators of NPCs are becoming smart!

GroovyDominoes52:groovy:Main developer of 'NPCs are becoming smart!':https://www.youtube.com/channel/UC4vnHZVLYKUvRTMTun8y3cw:F3F340
GamingKittyCath:cath:Groovy's moral support!:https://www.youtube.com/c/gamingkittycath:F0A6EE
LuaBaseScript:lua:Main programmer of NPCs are becoming smart.:https://www.roblox.com/users/931954455/profile:0091FF

Mod developers

DarkMinerULTRA:dark:the one programmer of the mod. did literally everything.:gamejolt.com/@DarkMinerULTRA:44009E"

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes. I added the mod and credits, but nothing else.

**Comment by swordcube** [comment]
name::iconname::description::link::color

you put one colon, not two colons
2 = ::
1 = :

**Comment by DarkMinerULTRA** [comment]
I have put one colon! It's the full stops that you think are colons.
