### ISSUE TITLE
How can i fade the hud

### ISSUE THREAD

**Issue by Sebasyn0se** [ShadowMario/FNF-PsychEngine#3388]
### Describe your problem here.

I want to do two things, fade the hud and make the enemy's hud invisible. How can i do it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Uniimations** [comment]
bro just
doTweenAlpha(tag:String, 'camHUD', alpha, duration, 'circIn')

Make the tag what you want the tween to be called in a string
Make the alpha 0 to fade out and 1 to fade back in
And make the duration a number from 0.1 and up, the higher the number the longer it is
