### ISSUE TITLE
Crash after adding character/Icon not showing up

### ISSUE THREAD

**Issue by GuestFake** [ShadowMario/FNF-PsychEngine#3391]
So, im making a mod called 'Get Fake' and there seems to be a problem with adding the characters when i reload the character 

![Screenshot (19)](https://user-images.githubusercontent.com/97422984/148718156-716382fc-1389-4db1-b0d9-febb307d6605.png) 
(^seconds before it crashes....)
guest's .json is located in Get Fake/images/characters 
guest's icon is located in Get Fake/images/icons 
if you know what im doing wrong feel free to point it out as soon as possible.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by bbpanzu** [comment]
themod/images/characters are where the spritesheet goes

the jsons go in the themod/characters/ folder

**Comment by GuestFake** [comment]
No luck
