### ISSUE TITLE
SWITCH STATEMENTS

### ISSUE THREAD

**Issue by Uniimations** [ShadowMario/FNF-PsychEngine#3394]
### What feature do you want to get added on the **base** engine?

Can ya'll add switch statements to the lua API or do they already exist?
![image](https://user-images.githubusercontent.com/89238832/148721131-e61a427e-eceb-4594-a646-c07ac7169ab6.png)

I'm making a difficulty with custom vocals and I want a new vocal sound to play but since it's different for each song this seems pretty unoptimized and I wanna know if I can

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by bbpanzu** [comment]
lua is an entire new coding language lol

**Comment by bbpanzu** [comment]
but yea lua doesn't have switch cases

**Comment by cyn-8** [comment]
lua doesnt have switch statements, but here is something that works similarly

```lua
local cases = {
    ['Tutorial.key'] = function() playSound('sticky-covers/Tutorial.key', 1 , soundTag) end,
    ['Faker.key'] = function() playSound('sticky-covers/Faker.key', 1 , soundTag) end,
    ['Black_Sun.key'] = function() playSound('sticky-covers/Black_Sun.key', 1 , soundTag) end
}

if cases[songName] then
    cases[songName]()
else
    debugPrint('error, no sticky cover for clover difficulty')
end
```

**Comment by cyn-8** [comment]
assuming the song name always will be the same as its corresponding sound you could also do this

```lua
local cases = {'Tutorial.key', 'Faker.key', 'Black_Sun.key'}

if cases[songName] then
    playSound('sticky-covers/' .. songName, 1 , soundTag) 
else
    debugPrint('error, no sticky cover for clover difficulty')
end
```

**Comment by Uniimations** [comment]
thanks, I think I should've put this on help category instead sorry, thank you so much! ^^
