### ISSUE TITLE
"Install Mod" and "Delete Selected Mod" buttons on the Mod Menu

### ISSUE THREAD

**Issue by SteveeWasTaken** [ShadowMario/FNF-PsychEngine#3395]
### What is your question?

while looking through the code, these buttons are mentioned, but i have never seen them actually in-game. how can i make these appear?

**Comment by bbpanzu** [comment]
they don't work so ..

**Comment by aflacc** [comment]
I could understand delete selected mod, but I don't understand how Installing a mod would work.

**Comment by SteveeWasTaken** [comment]
> I could understand delete selected mod, but I don't understand how Installing a mod would work.

maybe there could be like a website or something to download mods and you can download them directly from the game if you want? i don't know

**Comment by ShadowMario** [comment]
They weren't made functional due to haxe limitations (or maybe just me not understanding how it works properly).
