### ISSUE TITLE
camera tint

### ISSUE THREAD

**Issue by cyn-8** [ShadowMario/FNF-PsychEngine#3397]
### Describe your problem here.

flxcamera has a color property for tinting the camera
if possible, i would like to know how i can change this property for the game and hud cameras in lua
(to flxcolor blue and white in my case)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no changes

**Comment by 4wdthinks** [comment]
setProperty('camGame.color')?

**Comment by cyn-8** [comment]
> setProperty('camGame.color')?

ive already tried this; setting it to `getPropertyFromClass("flixel.util.FlxColor", "BLUE")` or `getColorFromHex("0000ff")` or just `"0x0000ff"` doesnt seem to work

ive also tried using `setPropertyFromClass("PlayState", "camGame.color")` but this doesnt work either

**Comment by Goontron** [comment]
Lua source?
