### ISSUE TITLE
Can we get the option to disable anti-aliasing on in game portraits?

### ISSUE THREAD

**Issue by SquidBowl** [ShadowMario/FNF-PsychEngine#3399]
### What feature do you want to get added on the **base** engine?

Could we get a thing we can use to turn off anti-aliasing on portraits? You can do it on everything but portraits. I notice this is only an issue on sharp, pixel items, but the rest of my mod is a pixel and doesn't have this issue once anti-aliasing is turned off.

![Untitled-1](https://user-images.githubusercontent.com/97431838/148731108-4a543805-37f7-4349-aa9a-7e5b0a32b9f9.png)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Thing that would not cause problems

**Comment by crispyboi24** [comment]
You failed the test

**Comment by SquidBowl** [comment]
> You failed the test

k
