### ISSUE TITLE
No early hit window

### ISSUE THREAD

**Issue by KadeDev** [ShadowMario/FNF-PsychEngine#34]
i'm super confused here, I made a PR adding a early hit window and it was closed. for literally no reason.

Currently you have a very small early hit window instead of the FULL early hit window you should have.
https://github.com/ShadowMario/FNF-PsychEngine/pull/33

Please re-consider this PR.

**Comment by ShadowMario** [comment]
I'm still a pensive about doubling the hit window, i need time to think while finishing other stuff

**Comment by s-zenmode** [comment]
if you think about it if all the engines use similar hit windows it is more convenient for the player as there wont be significant differences that screw up the gameplay somewhat because the player might be used to certain hit windows on one engine and it might screw em up while playing on another engine


apologies in advance if you had a stroke reading that

**Comment by KadeDev** [comment]
> I'm still a pensive about doubling the hit window, i need time to think while finishing other stuff (And trying to figure out if there's any other way to fix it that doesn't involve making hits too easy)

You can't add an early hit window without doubling the hit window. 

Take a page out of other rhythm games, every game does this.
Osu,
Stepmania,
Quaver,
even fucking Rhythm Doctor.

A window goes 2 ways, early and late.

thats what rhythm games do

**Comment by Steviegt6** [comment]
> 
> 
> if you think about it if all the engines use similar hit windows it is more convenient for the player as there wont be significant differences that screw up the gameplay somewhat because the player might be used to certain hit windows on one engine and it might screw em up while playing on another engine
> 
> apologies in advance if you had a stroke reading that

It's debatably bad that they're getting screwed over by changes in hit windows - shouldn't you aim for actual accuracy?

**Comment by arceuss** [comment]
> 
> 
> i'm super confused here, I made a PR adding a early hit window and it was closed. for literally no reason.
> 
> Currently you have a very small early hit window instead of the FULL early hit window you should have.
> #33
> 
> Please re-consider this PR.

i tried it and it works fine
it should be reconsidered

**Comment by Steviegt6** [comment]
> 
> 
> > i'm super confused here, I made a PR adding a early hit window and it was closed. for literally no reason.
> > Currently you have a very small early hit window instead of the FULL early hit window you should have.
> > #33
> > Please re-consider this PR.
> 
> i tried it and it works fine
> it should be reconsidered

Whether it functioned or not wasn't the issue. @ShadowMario's just being generally indecisive about the whole idea.

**Comment by ShadowMario** [comment]
Shubs added it on his PR #38
River and shubs made me reconsider it tbh
