### ISSUE TITLE
How do i change icon effect

### ISSUE THREAD

**Issue by crashok20185** [ShadowMario/FNF-PsychEngine#3405]
### Describe your problem here.

so i want to change the icon effect, because im tired of icon bumping effect, so i know its in healthicon but i dont find the code for it, someone help me please

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by tposejank** [comment]
no

**Comment by crashok20185** [comment]
y e s >:))))

**Comment by crashok20185** [comment]
nvm i discovered how
