### ISSUE TITLE
Engine Crashes when using a Custom Left Sustain

### ISSUE THREAD

**Issue by XxJRushxX** [ShadowMario/FNF-PsychEngine#3408]
### Describe your bug here.

Yes, I have tested this for a while in order to get one of my charts to work, I didnt want to just give up so I tested this extensively for like 40 minutes.

There is no problem with my code or anything. If you use a custom note0 of any length greater than 0 (at the time of testing, only on the opponents side not sure if it happens for the player as qell) the game will close when it hits the tail end. So far this only happened using the games mod packs but I'm not sure. If needed, I can send the code for my note after my classes are over. Thank you!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not at all. Only used the mod folder.

**Comment by ShadowMario** [comment]
Wrong animation name for the left note end on the .XML file of your note asset.

**Comment by XxJRushxX** [comment]
@ShadowMario 
`<?xml version="1.0" encoding="utf-8"?>
<TextureAtlas imagePath="NOTE_rushia.png">
	
	
	<SubTexture name="blue hold end0000" x="48" y="454" width="60" height="58"/>
	<SubTexture name="blue hold piece0000" x="54" y="0" width="62" height="82"/>
	<SubTexture name="blue0000" x="0" y="82" width="158" height="180"/>
	<SubTexture name="green hold end0000" x="164" y="454" width="60" height="58"/>
	<SubTexture name="green hold piece0000" x="170" y="0" width="62" height="82"/>
	<SubTexture name="green0000" x="158" y="82" width="158" height="180"/>
	<SubTexture name="purple0000" x="316" y="82" width="180" height="158"/>
	<SubTexture name="purple hold end0000" x="280" y="454" width="60" height="58"/>
	<SubTexture name="purple hold piece0000" x="286" y="0" width="62" height="82"/>
	<SubTexture name="red hold end0000" x="396" y="454" width="60" height="59"/>
	<SubTexture name="red hold piece0000" x="402" y="0" width="62" height="82"/>
	<SubTexture name="red0000" x="0" y="262" width="180" height="158"/>
</TextureAtlas>`

Does this have any errors?
