### ISSUE TITLE
Trying to load Null Difficulty & About Charting Mode

### ISSUE THREAD

**Issue by LukasRainbow** [ShadowMario/FNF-PsychEngine#3410]
### Describe your bug here.

**Trying to load Null Difficulty**
Going to the Menu and choosing "Change Difficulty" works fine, but when selecting Back the Game tried to load Difficulty Null. that's why the Error "File data/song-null.json is Missing" pops up.
![bug](https://user-images.githubusercontent.com/89423600/148793569-ade82eb3-7afb-49f7-a4ba-758a98b0d9f4.png)

**About Charting Mode**
Usually when going to the Charting Mode my pessing 7 on the Menu, you can always go back with Backspace. When i choose a Song in Freeplay or Story Mode and go into the Debug Menu that way, httign Backspace will also send me back to the Menu that _would_ apper when hitting 7 while on the Menu.
(Not really a Bug but if you press Exit in the Pause Menu you also get sent back to the Freeplay Menu if you entered the Song via Charting Mode)

(If someone can't recreate this bug again i will send a Video file. If I myself can't recreate it i'm gonna explode.)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheKitBoi** [comment]
Probably just add chart-null.json on it that will prob fix

**Comment by frantastic24** [comment]
Difficulty error was fixed on source code

**Comment by ShadowMario** [comment]
This was already fixed on source code.

**Comment by LukasRainbow** [comment]
> Probably just add chart-null.json on it that will prob fix

How would that fix the Issue?
It would just load that Chart instead of backing be actually go back to the Pause Menu
