### ISSUE TITLE
Video plays mid song

### ISSUE THREAD

**Issue by TheKitBoi** [ShadowMario/FNF-PsychEngine#3414]
### What is your question?

Idk if it’s true or not but I’ve been thinking about playing a video mid song but i can’t find the code to startvideo in a song so if anyone have the code that plays mid song ill be really grateful if someone has it or just send a code that starts video mid song

**Comment by ImaginationSuperHero528** [comment]
I remember someone asking on discord and someone replied showing a built in function but when they tried it the game crashed so I don't think it's possible yet...

**Comment by TheKitBoi** [comment]
> 

Ok thanks for the info

**Comment by denumu07** [comment]
I don't think it's Possible, because you can't cut off a Chart during it's playing.
