### ISSUE TITLE
still cant compile the game

### ISSUE THREAD

**Issue by HapJim** [ShadowMario/FNF-PsychEngine#3422]
### Describe your problem here.

I get something along the line of this every time I compile:
"Error: Stdout.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: Context3DElementType.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory"

I've tried installing visual studio 2017 and 2022 and literally nothing will work.
Im using windows 10 64 bit

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I've added files into the mods folder, but I haven't done any source editing.

**Comment by Itz-Miles** [comment]
A question. What SDK are you using in Visual Studio? I'm using kit 10.0.19041.0 for compilation, and a nightly build of haxe 4.2.4.

**Comment by HapJim** [comment]
sorry for late reply, i have the same kit you have installed, but im not using a nightly build of haxe

**Comment by HapJim** [comment]
i think maybe its the version of msvc im using. what msvc do you have installed with visual studio
