### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by OrangeHairr** [ShadowMario/FNF-PsychEngine#3423]
### What is your question?

What does this error mean?
<img width="237" alt="Error" src="https://user-images.githubusercontent.com/95587502/148827272-03207848-fae5-420c-8884-3c2de44f57d3.png">

**Comment by Vicdragon** [comment]
can u print what the .lua looks like?

**Comment by OrangeHairr** [comment]
oops. i already solved that. thanks!
