### ISSUE TITLE
Image Directory

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [ShadowMario/FNF-PsychEngine#3424]
### Describe your problem here.

Basically, due to some help, I know how to change the strums of opponent and player separately and I'm trying to make it into an event for people who can't script (I got your back homies) and I don't know how to add directories to the value thing

`setPropertyFromGroup('playerStrums', i, 'texture', 'notes/value2-notes')`

IDK how to do it since for player ya know there are splashes so I wanted to make it simple for others to use and Idk how to add the value prompt thing to an image directory someone please help ;(

Also if you want to know the code here

```
function onCreatePost()
    if dadName == 'Dad Name' then --replace the name for your character name
        for i=0,4,1 do
            setPropertyFromGroup('opponentStrums', i, 'texture', 'texture')
        end
        for i = 0, getProperty('unspawnNotes.length')-1 do
            if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
                setPropertyFromGroup('unspawnNotes', i, 'texture', 'texture'); --Change texture
            end
        end
    end
end
```
```
function onCreatePost()
    if boyfriendName == 'BF Name' then --replace the name for your character name
        for i=0,4,1 do
            setPropertyFromGroup('playerStrums', i, 'texture', 'texture')
        end
        for i = 0, getProperty('unspawnNotes.length')-1 do
            if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
                setPropertyFromGroup('unspawnNotes', i, 'texture', 'texture'); --Change texture
                setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'texture'); --Change texture
            end
        end
    end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No... it's Lua.

**Comment by MayoALT** [comment]
instead of putting `'notes/value2-notes'`, put `value2` (no quotes)

**Comment by ImaginationSuperHero528** [comment]
cause I want it to look in a folder when you put the image name so you don't have to put notes/image and whatever

**Comment by ImaginationSuperHero528** [comment]
> instead of putting `'notes/value2-notes'`, put `value2` (no quotes)

That's not what I'm looking for but uh I figured it out thanks (not really) anyway!
