### ISSUE TITLE
Changed bpm in title screen

### ISSUE THREAD

**Issue by FoxyGamer1980** [ShadowMario/FNF-PsychEngine#3427]
### Describe your problem here.

like for example, if i want to use a new track for the title screen, and i want the bpm to match the music, is there a way to change the bpm for the title screen?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i edited the playstate creditsstate, etc

**Comment by ImaginationSuperHero528** [comment]
look in assets images and find gfDanceTitle.json

**Comment by nintendofan44** [comment]
its source bro

search for changebpm in the title state file

**Comment by nintendofan44** [comment]
> ### Describe your problem here.
> like for example, if i want to use a new track for the title screen, and i want the bpm to match the music, is there a way to change the bpm for the title screen?
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> Yes, i edited the playstate creditsstate, etc

search for changebpm in the title state file

**Comment by Doritojoey** [comment]
Change "bpm":102 in images/gfDanceTitle.json to the bpm you want

**Comment by MayoALT** [comment]
> > look in assets images and find gfDanceTitle.json
> 
> its source bro

look inside gfDanceTitle.json :trollface:

**Comment by nintendofan44** [comment]
> > > look in assets images and find gfDanceTitle.json
> > 
> > 
> > its source bro
> 
> look inside gfDanceTitle.json :trollface:

im dumb :trollface:

**Comment by ImaginationSuperHero528** [comment]
> > > > look in assets images and find gfDanceTitle.json
> > > 
> > > 
> > > its source bro
> > 
> > 
> > look inside gfDanceTitle.json :trollface:
> 
> im dumb :trollface:

I even said that before you XD

**Comment by s-h-i-f-t-y-z** [comment]
quick qeustion related here

is changing the bpm inside the gf json file gonna change the bpm universally like the title logo?

**Comment by RodneyAnImaginativePerson** [comment]
> quick qeustion related here
> 
> is changing the bpm inside the gf json file gonna change the bpm universally like the title logo?
> 

It changes the bpm of every menu that uses the freakyMenu song.
