### ISSUE TITLE
shaders wont work

### ISSUE THREAD

**Issue by OOF-PRODUCTIONS** [ShadowMario/FNF-PsychEngine#3436]
### Describe your bug here.

i tried adding a glitch shader to a song by putting the script.lua in the song data folder it doesnt work when i open the song

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i added a week and tried adding shaders (obviously)

**Comment by OOF-PRODUCTIONS** [comment]
![image](https://user-images.githubusercontent.com/93954547/148874101-463a4415-7259-4338-96b8-cd62daa144ea.png)

**Comment by frantastic24** [comment]
I tried this myself and it worked fine so there's need for more info

**Comment by sonicfan888** [comment]
i think it needs to be on the lua background script

**Comment by sonicfan888** [comment]
or if it still doesnt work try [this compiled version someone made](https://www.mediafire.com/file/38ojzfmkr599as3/FNF-PsychEngine-0.5.1_%25281%2529.rar/file) and put it on the lua background script

**Comment by cherryiguess** [comment]
> ![image](https://user-images.githubusercontent.com/93954547/148874101-463a4415-7259-4338-96b8-cd62daa144ea.png)

instead of just "game", do camGame for the game, and do camHUD for the hud

**Comment by OOF-PRODUCTIONS** [comment]
doesnt work

**Comment by bbpanzu** [comment]
increase the value. maybe it's there and you can't see it

**Comment by OOF-PRODUCTIONS** [comment]
nah it just doesnt work

**Comment by OOF-PRODUCTIONS** [comment]
i increased it to 0.500 and still no

**Comment by OOF-PRODUCTIONS** [comment]
> i think it needs to be on the lua background script

i dont have a bg yet, im porting whitty to psych engine and idk how to add the animated ballistic bg
thats what song im adding the shader to

**Comment by frantastic24** [comment]
are you using 0.5.1 or a build from source

**Comment by OOF-PRODUCTIONS** [comment]
0.5.1 source code

**Comment by frantastic24** [comment]
you can't use shaders then

**Comment by OOF-PRODUCTIONS** [comment]
No the build with shaders

**Comment by frantastic24** [comment]
so it's not 0.5.1, then you have to be doing something wrong because it works jsut fine

**Comment by ShadowMario** [comment]
Only works in the latest builds.
