### ISSUE TITLE
Dialogue script not working with base game songs

### ISSUE THREAD

**Issue by wafffle-iron** [ShadowMario/FNF-PsychEngine#3438]
### Describe your problem here.

I'm trying to add dialogue to the base game songs using the lua script but it's not working as intended.
I put some test dialogue and the script into Bopeebo's chart folder to try and see how it worked. I'll start up week 1 and the game will pause for a second as if it's waiting for the dialogue to start, but then it'll just start the song as normal. Does the lua script just not work with base game songs for some reason or am I doing something wrong?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I replaced most of the character sprite sheets, .xmls, and .jsons, as well as some background assets. Everything I've changed is strictly art-related.

**Comment by Bludye** [comment]
i think .lua scripts only work on the mods folder

**Comment by wafffle-iron** [comment]
Nvm I figured it out
