### ISSUE TITLE
Saving notes

### ISSUE THREAD

**Issue by TahirArch** [ShadowMario/FNF-PsychEngine#3441]
### What feature do you want to get added on the **base** engine?

It would be cool to be able to save notes as png and xml files. Like, for example I've made a mod and changed my note colors, it would be useful to save and replace the note colors. So this way other people could use the note colors i've changed.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Grape-Boy** [comment]
I don't know if this is possible with Haxe.

**Comment by tposejank** [comment]
> I don't know if this is possible with Haxe.

For you save data doesn't exist.

**Comment by MayoALT** [comment]
this is ALREADY in the game dude, its called note skins
