### ISSUE TITLE
custom character not loading

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#3444]
### Describe your sublong here.

every time I try to change the enemy to my custom character it crashes
btw I don't use coding or Lua

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Not much info to go on so you're probably just using the event wrong, or you messed up the custom character

**Comment by creeperkidking** [comment]
no not the event just changing the opponent out right in the song tab and trying to start the song crashes the game

**Comment by creeperkidking** [comment]
ill send a pic of my .json .xml and my .png

**Comment by creeperkidking** [comment]
the stuff is in the folder

**Comment by creeperkidking** [comment]
all the pics for the sprite sheet are in there to but it was an accident

**Comment by frantastic24** [comment]
Character doesn't have an icon, that's the problem

**Comment by creeperkidking** [comment]
> Character doesn't have an icon, that's the problem

it works now thank you

**Comment by frantastic24** [comment]
Cool, remember to close this

**Comment by creeperkidking** [comment]
oh right sorry
