### ISSUE TITLE
mod loader crashing

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#3450]
### Describe your bug here.

after i exit when i enable or disable a mod that restarts the game, it crashes.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ImaginationSuperHero528** [comment]
I don't really think you should care about this bug too much cause personally it doesn't fully REstart your game. You can tell when you get to the main menu you should be over the mods tab. Normally after closing the game it should be on Story Mode.
