### ISSUE TITLE
menu mod stuffs

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#3452]
### What feature do you want to get added on the **base** engine?

when you are selecting a mod song in freeplay that has a custom menu BG, it switches from the base game menu BG, to the mods one. same with the mod menu. 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ImaginationSuperHero528** [comment]
Dat sounds nice
