### ISSUE TITLE
GhostTrail Code

### ISSUE THREAD

**Issue by asdvtx** [ShadowMario/FNF-PsychEngine#3454]
### What feature do you want to get added on the **base** engine?

Add GhostTrail (FlxTrail) like in Mid Masses or Week 6 Thorns

Code for Playstate.hx

case 'Toggle Ghost Trail': //Selever Crossfadevar target = value1.split(',');var enabled = value2 == 'on' || value2 == '1' || value2 == 'true';if (target.length == 0 || (!enabled && !(value2 == 'off' || value2 == '0' || value2 == 'false'))) {//break; //tf you mean breaks don't work here?} else {if (target.contains('bf')) {flxTrlBf.visible = enabled;trace('bf trail ' + (enabled ? 'enabled' : 'disabled'));} if (target.contains('dad')) {flxTrlDad.visible = enabled;trace('dad trail ' + (enabled ? 'enabled' : 'disabled'));}
}

Code for ChangeState.hx

['Toggle Ghost Trail', 'Enables or disables a trail in the same fashion seen\nin Mid-Fight Masses and Week 6.\n\nValue 1: "bf", "dad" or a mixture of them, separated\nby commas.\nValue 2: "on"/"1"/"true" to enable the effect,\n"off"/"0"/"false" to disable it.'] //Selever crossfade

as Event

@RuvStyle, DragShot

English is not my language 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MayoALT** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/pulls

**Comment by Den198888** [comment]
do FlxTrail works on, lua?

**Comment by asdvtx** [comment]
Yep you can add ghost trail ad. Lua

**Comment by Den198888** [comment]
how? can i be like destroy or stop

**Comment by asdvtx** [comment]
But its called toggle trail, but ita the same

**Comment by Den198888** [comment]
like setProperty('toggleTrail', true);
