### ISSUE TITLE
How to make the screen shake when the character sings

### ISSUE THREAD

**Issue by XxjuandisxX** [ShadowMario/FNF-PsychEngine#3459]
### Describe your problem here.

How to make the screen shake when the character sings pls

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by sussyboireal** [comment]
Now how?

**Comment by tposejank** [comment]
FlxG.camera.shake(0.01, 0.1)

**Comment by BeansCool54** [comment]
find `function opponentNoteHit(note:Note):Void` then add `FlxG.camera.shake(0.01, 0.1)` in the code maybe?
