### ISSUE TITLE
back on difficulty select screen crashes game

### ISSUE THREAD

**Issue by imdoingthisfortheprofile** [ShadowMario/FNF-PsychEngine#3462]
### Describe your bug here.

im making a mod, and i went into one of the songs, accidentally pressed change difficulty instead of botplay, and when i pressed back it said it couldnt find "[song name]-null.json"
why does it think pressing back means load the null difficulty?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

im using the recent release

**Comment by cherryiguess** [comment]
lmao its already fixed in the source code, just wait for it to release

**Comment by Gui-iago** [comment]
already fixed, compile the source yourself or wait for release

**Comment by imdoingthisfortheprofile** [comment]
oh ok
