### ISSUE TITLE
week 3 issue

### ISSUE THREAD

**Issue by thedeveloper112206** [ShadowMario/FNF-PsychEngine#3464]
### Describe your bug here.

sometimes the train sound when the train passes doesnt play

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Luisinhi010** [comment]
this has in all builds, engines and versions of friday night funkin, it's probably something/limitation of haxe (which can be very unlikely)
