### ISSUE TITLE
Character animation offsets don't work on a specific song

### ISSUE THREAD

**Issue by KutikiPlayz** [ShadowMario/FNF-PsychEngine#3467]
### Describe your problem here.

The title describes it all. There are no errors, nothing in the command prompt, just no matter what character I use for the opponent, the offsets won't work. I have literally no idea why this is happening, and I can't check what I added that's making it do this since my character sprites back then didn't need offsets.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by JorgeMiguel22** [comment]
yeah im having this issue too, idk how to fix it

**Comment by Bludye** [comment]
have you checked stage offsets

**Comment by KutikiPlayz** [comment]
> have you checked stage offsets

I mean animation specific offsets
