### ISSUE TITLE
Game Crashes when you use the play animation event twice.

### ISSUE THREAD

**Issue by blowers69** [ShadowMario/FNF-PsychEngine#3469]
### Describe your bug here.

I don't know if anyone has gotten this issue, but. if you use the character event animation, then later on use it again. the game freezes for about 2-3 seconds and then crashes. this could cause people to lose their charting progress if they haven't saved prior.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no.

**Comment by tposejank** [comment]
load auto save

**Comment by blowers69** [comment]
ok

**Comment by trayfellow** [comment]
since ur using lua i think u gotta precache ur funy character assets first 

https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Precaching-Functions
