### ISSUE TITLE
How to add achivements?

### ISSUE THREAD

**Issue by TahirArch** [ShadowMario/FNF-PsychEngine#3470]
### What is your question?

I see we can add achivements now, how do we code an achivement json file?

**Comment by asdvtx** [comment]
Not jet

**Comment by tposejank** [comment]
Join the [Psych Engine Discord](https://discord.gg/2ka77eMXDv) and then go to #help and read the pinned messages

**Comment by TahirArch** [comment]
> Join the [Psych Engine Discord](https://discord.gg/2ka77eMXDv) and then go to #help and read the pinned messages
Thanks!
