### ISSUE TITLE
My Screen goes black when I play a song that I put Custom Characters

### ISSUE THREAD

**Issue by Supersteven72** [ShadowMario/FNF-PsychEngine#3485]
### Describe your problem here.

So I have like a mod of the Sonic.exe but in Psych Engine and i use it to import my custom characters better than the Kade Engine and I put like multiple characters in there and I tried to test it out but it either goes to black but i hear the audio of the song OR it crashes but its mostly the goes to black with only audio and i can exit the song by pausing it and remembering how to exit the song and the whole menu is just black with only audio. I mostly believe its my computer not being able to render the character cause it usually works with my friends computer. If you want me to send you the link of the file i have I can so that you can see if it does it for you too but idk how to fix it.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

only used the mod folder to edit the stuff to add my characters to the songs.

**Comment by frantastic24** [comment]
Sounds like a PC issue but send the files anyways just in case

**Comment by Supersteven72** [comment]
It runs well for my friends but not me, so I think it’s me mostly having the problem
