### ISSUE TITLE
blammed lights suggestion

### ISSUE THREAD

**Issue by thedeveloper112206** [ShadowMario/FNF-PsychEngine#3486]
### What feature do you want to get added on the **base** engine?

i think the train should have neon lights when blammed lights are active in week 3. it still passes by because gf hair still blows from the pressure by the train an i think neon lights on the train would look cool AF.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by HiroMizuki** [comment]
idk if shadow mario would make it, cuz it's not really a important thing to the engine yknow

**Comment by ShadowMario** [comment]
Blammed lights ‼️
