### ISSUE TITLE
Dialogue .XML

### ISSUE THREAD

**Issue by KyleOliverDeveloper** [ShadowMario/FNF-PsychEngine#3487]
### What is your question?

I'm currently trying to code dialogues for the FNF mods i'm working on, but i don't have the .XML file and i don't know how to create a dialogue .XML, nor my team does so. I would aprecciate if someone could help me.

Thanks,

_coconut7_

**Comment by Fronekowy** [comment]
You mean likw dialouge character xml or dialouge .jaon

**Comment by KyleOliverDeveloper** [comment]
> You mean likw dialouge character xml or dialouge .jaon

i mean dialogue character .xml

**Comment by Fronekowy** [comment]
> > You mean likw dialouge character xml or dialouge .jaon
> 
> i mean dialogue character .xml
And do you want them to be animated

**Comment by ShadowMario** [comment]
Adobe Animate/Flash.
