### ISSUE TITLE
How do you make the icons bop like this when the screen zooms in on every beat?

### ISSUE THREAD

**Issue by RiloTheFox** [ShadowMario/FNF-PsychEngine#3488]
### What is your question?

Apparently, there's a mod called Tails.exe, and there's something unique with the icon bopping, whenever the camera zooms in on a beat, the icons move like this:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/85717307/149206075-64e3b5d3-4f29-433e-8f22-c1595fa50be1.gif)
Is it possible to do this on Psych Engine? Either Source Code or LUA?

**Comment by tposejank** [comment]
literally adjust the angle

**Comment by cyn-8** [comment]
> literally adjust the angle

yeah pretty much

you can use this code here
(it uses lerp instead of tween because tweening the angle crashes the game for some reason)
```lua
local function icon_bop()
	setProperty("iconP1.angle", -30)
	setProperty("iconP2.angle", 30)
end

function onSongStart()
	icon_bop()
end

local section_beat = 0
function onBeatHit()
	section_beat = section_beat + 1
	
	if section_beat >= 4 then
		section_beat = 0
		
		icon_bop()
	end
end

local lerp_alpha = 0.1
local function lerp(start, goal, alpha)
	return (start + ((goal - start) * alpha))
end

function onUpdate()
	setProperty("iconP1.angle", lerp(getProperty("iconP1.angle"), 0, lerp_alpha))
	setProperty("iconP2.angle", lerp(getProperty("iconP2.angle"), 0, lerp_alpha))
end
```
