### ISSUE TITLE
Botplay text changed with lua

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#3491]
### Describe your problem here.

How do i do that (If its Possible)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MaybeMaru** [comment]
I dont know if you can change it but I know you can like hide the text and replace it with a LuaSprite

**Comment by PDL2CGamejolt** [comment]
> I dont know if you can change it but I know you can like hide the text and replace it with a LuaSprite

how

**Comment by PDL2CGamejolt** [comment]
> > I dont know if you can change it but I know you can like hide the text and replace it with a LuaSprite
> 
> how

how

**Comment by i-winxd** [comment]
Any variable (that is public) in ``playstate.hx`` can be altered at any time.
The botplay text value you are looking for is:
``botplayTxt.Text``

Check the wiki variable section to see how you might be able to change this value.

**Comment by ShadowMario** [comment]
you can change variables from `botplayTxt`

**Comment by PDL2CGamejolt** [comment]
> you can change variables from `botplayTxt`

but idk source
