### ISSUE TITLE
Mechanics (similar to events)

### ISSUE THREAD

**Issue by te-agma-at** [ShadowMario/FNF-PsychEngine#3497]
### What feature do you want to get added on the **base** engine?

Remember Events?
Well I would suggest Mechanics be added to the game, that can be divided into four categories:
1. Obstructors (Sub-Types: Tweened, Animated, Pop-Ups)
2. Spacebar Press (Sub-Types: Dodge, Mashing)
3. Window Movement (Sub-Types: Linear, Smooth)
4. Custom

Example Obstructor, Spacebar Press, and Window Movement Mechanics can be found in the Mechanics tab, where you can adjust the offsets of the obstructor(s) and from which side they will appear, how many times you have to press the spacebar (once for Dodge, more than once for Mashing) for Spacebar Press, and how far in pixels will the window move in Window Movement.

You can also create custom Mechanics, too, using LUA! How you ask?
First - Add a LUA and TXT file in "mods/custom_mechanics/"
Secondly - Code in LUA scripting on the LUA file to whatever you want (some categories are restricted to only some functions but the Custom category can allow anything)
Finally - Just edit the TXT file and you're ready to test your custom Mechanic!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Thing that would not cause problems

**Comment by creeperkidking** [comment]
YES

**Comment by i-winxd** [comment]
Mechanics can done in stage or song specific lua files.

**Comment by Gui-iago** [comment]
psych engine users when they actually have to write code themselves
![148586977-b70e99af-5910-4fdc-938e-c377e35c9a5f](https://user-images.githubusercontent.com/45212377/149297028-20b0a48d-e918-4eb9-bb47-92cfd6e117ba.png)
