### ISSUE TITLE
applecore chart crashing

### ISSUE THREAD

**Issue by mayo78** [ShadowMario/FNF-PsychEngine#3503]
### Describe your bug here.

im making a rechart of applecore (not releasing) and around 70 seconds the game crashes (this happened before and after recharting that section)
https://youtu.be/VFDeZotvWNY

[also heres golden apple so you can test the chart urself](https://gamebanana.com/mods/343129)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i have code that changes the strumnote and notes of the opponent to 3d versions

**Comment by tposejank** [comment]
no

**Comment by cyn-8** [comment]
golden apple is using a modified kade engine so there may be things in the chart json that make it incompatible

**Comment by MayoALT** [comment]
i made a whole new chart and its still crashing

**Comment by MayoALT** [comment]
solved ,the issue was the debug text in the top left
