### ISSUE TITLE
more then one difficulty

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#3506]
### Describe your problem here.

I know how to add a new difficulty but when I try to add more then one it doesn't work. How do I add more than one difficulty? Btw I use the compiled version. 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added new credits

**Comment by ActualMandM** [comment]
It's explained on the Wiki, it requires a source code edit
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Adding-a-New-Difficulty

**Comment by Gui-iago** [comment]
open the week editor, go to the "other" tab, type this

`easy, normal, hard, your-difficulty`

save it as a week, done

**Comment by creeperkidking** [comment]
nvm it already works its just my custom difficulty icons wont show :[

**Comment by Gui-iago** [comment]
close the issue

**Comment by creeperkidking** [comment]
ok
