### ISSUE TITLE
difficulty wont show

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#3515]
### Describe your problem here.

I have more than one custom difficulty but only one of the difficulty icons show even if I'm on one of the other ones how do I fix this also I am modding from the compiled version

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Theoyeah** [comment]
try to make a folder "menudifficulties" in mods/images (after the game have been compilied) and put your difficulty images
(it can be just the wrong format or the name is wrong)

**Comment by creeperkidking** [comment]
i did that

**Comment by creeperkidking** [comment]
![proof1](https://user-images.githubusercontent.com/83985038/149683140-c06ffcd1-522e-475d-a354-8e1aae7103d6.PNG)
![proof2](https://user-images.githubusercontent.com/83985038/149683141-0d295da0-7312-4029-9beb-661bf0455827.PNG)

**Comment by creeperkidking** [comment]
my custom easy is noob my custom normal is creeper and my custom hard is herobrine
