### ISSUE TITLE
how to add custom gfdancetitle without source code

### ISSUE THREAD

**Issue by robtiptop** [ShadowMario/FNF-PsychEngine#3518]
### What is your question?

how to add custom gfdancetitle without source code

**Comment by Alt-Reality** [comment]
get ur own sprite sheet and xml and just rename the animations to whatever the original one has

**Comment by KyleOliverDeveloper** [comment]
> ### What is your question?
> how to add custom gfdancetitle without source code

dude just make your own spritesheet over GF. If it is moving to other places like it isnt used to be moving to, just create your own spritesheet. https://gamebanana.com/tools/7136
