### ISSUE TITLE
the offsets of a character dont work

### ISSUE THREAD

**Issue by JorgeMiguel22** [ShadowMario/FNF-PsychEngine#3521]
### Describe your bug here.

 when i added a character, and i tested it, the offsets was totally messed up, in every song. i looked in the .json file and nothing is diferent

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by denumu07** [comment]
was the Camera Offset messed up too?
