### ISSUE TITLE
Dying in an cutscene crashes the game

### ISSUE THREAD

**Issue by Coolboy0516** [ShadowMario/FNF-PsychEngine#3523]
### Describe your bug here.

I was playing Mind Games and I wanted to skip the cutscene so I mashed arrow keys, but ghost tapping is off and I died.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I was playing Mind Games and I wanted to skip the cutscene so I mashed arrow keys, but ghost tapping is off and I died.

**Comment by denumu07** [comment]
**You can't Skip The Cutcsene**. And you can just turn on Ghost Tapping again.

**Comment by ShadowMario** [comment]
Mind games issue, not Psych Engine itself.
