### ISSUE TITLE
How To Add achievements

### ISSUE THREAD

**Issue by bf244** [ShadowMario/FNF-PsychEngine#3525]
### Describe your problem here.

![Windows PowerShell 13_01_2022 18_22_13](https://user-images.githubusercontent.com/84717235/149378697-26f03ea0-0d92-42bb-a30e-d2dc7eceeed9.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No,Just Trying To add A new achievements

**Comment by cyn-8** [comment]
you probably are doing it right, but from the screenshot it looks like you forgot to close an array and caused a syntax error
