### ISSUE TITLE
Animations are broken

### ISSUE THREAD

**Issue by Epicman836** [ShadowMario/FNF-PsychEngine#3535]
### Describe your bug here.

tried to make a custom character, i added all the files and animations, but in the songs all the notes just move them down

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i added basically everything you need for an fnf mod

**Comment by frantastic24** [comment]
Videos? Files? Literally anything that would either help fix this or help reproduce the bug?

**Comment by ShadowMario** [comment]
Missing song files.
