### ISSUE TITLE
Section Length remains untouched from vanilla.

### ISSUE THREAD

**Issue by Bloopsdoob** [ShadowMario/FNF-PsychEngine#3538]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/77730957/149428760-cb50406c-c008-4053-8d31-46a4f208ed94.png)
There's a 'section length' modifier in the chart editor which remains unusable as the chart is unaffected by it, this has been the case since Vanilla 0.2.5.

Are there any plans to resolve this in the near future?
Thanks.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No changes were made, out of the box Psych.

**Comment by ShadowMario** [comment]
Yeah, it's just a really annoying thing to code though.
