### ISSUE TITLE
How to let the camara not move?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#3546]
### What is your question?

How to let the camara not move when playing the game?

**Comment by WolfyTail** [comment]
If you want that the camera points to Boyfriend, activate "Must Hit Section".
If you wanna focus to an specific point, use the "Camera Follow Pos" event.

**Comment by zwl1619** [comment]
@WolfyTail
How to use the "Camera Follow Pos" event?
