### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ChetIsNotGoodAtGames** [ShadowMario/FNF-PsychEngine#3552]
### Describe your problem here.

lime : The term 'lime' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ lime test windows -debug
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (lime:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    
    whatr the did i do wrong??

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by MrClogsworthYT** [comment]
use haxelib run lime test windows
