### ISSUE TITLE
No animation notes

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#3561]
### Describe your problem here.

when the opponent presses this note they don't have a sing animation
is there some kinda thing for this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
```setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true);```

**Comment by ItsCapp** [comment]
> setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true);

👍
