### ISSUE TITLE
Excuse me WHAT!?

### ISSUE THREAD

**Issue by Trenton0** [ShadowMario/FNF-PsychEngine#3566]
### Describe your bug here.

![Friday Night Funkin'_ Psych Engine 1_14_2022 3_36_04 PM](https://user-images.githubusercontent.com/94765454/149588636-d2f3d8eb-e915-4132-a076-058a3d508d43.png)
HOW!?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, but after just SoftLocked itself

**Comment by MrClogsworthYT** [comment]
the arrows truly say you didnt edit anything
