### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by frenchbulldoggamer7** [ShadowMario/FNF-PsychEngine#3570]
### What feature do you want to get added on the **base** engine?

im new to git hub im stupid and you add change map and arrows as a effect and win icons i guess idk bye lol

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
🗿🗿🗿

**Comment by cherryiguess** [comment]
![image](https://user-images.githubusercontent.com/93490646/149606296-6f1e39ab-7b81-4f14-9d48-93fd0e6277ec.png)
bro what??

**Comment by HiroMizuki** [comment]
no

**Comment by frenchbulldoggamer7** [comment]
im blind lol

**Comment by Fablisothebottle** [comment]
didn't Shadow Mario say no winning icons?

**Comment by HiroMizuki** [comment]
> didn't Shadow Mario say no winning icons?

yes, he said it

**Comment by KutikiPlayz** [comment]
> 
![Screenshot (1054)](https://user-images.githubusercontent.com/73810550/149649875-48c485a5-e4e6-46ea-9a38-942d1a0e7d8d.png)
***how?***

**Comment by Stilic** [comment]
close this so
