### ISSUE TITLE
Pressing 9 doesn't make the bf icon switch old bf icon

### ISSUE THREAD

**Issue by CasualCypress** [ShadowMario/FNF-PsychEngine#3571]
### What is your question?

so i idk if its a bug or you just took it out? an if so why did you take it out?

**Comment by bbpanzu** [comment]
it's useless

**Comment by crispyboi24** [comment]
> it's useless

It’s a cool Easter egg. If this is useless then why not remove the rare pause screen

**Comment by ActualMandM** [comment]
> then why not remove the rare pause screen

gitaroo easter egg was removed too so lol
https://github.com/ShadowMario/FNF-PsychEngine/blob/acd1b54286943331e15d1c135c9c866c0b7e917c/source/PlayState.hx#L2344-L2351
