### ISSUE TITLE
Is there a way to change the arrow hud sprites mid song?

### ISSUE THREAD

**Issue by YerayBB** [ShadowMario/FNF-PsychEngine#3573]
### What is your question?

I'm trying to change the visuals, in the middle of a song, from normal to pixel style and the other way arround.
I can change all the sprites in the current stage to some preloaded pixel style ones, and all the characters and notes to spawn, but i havent found a way to change the hud for the arrows. Is there a way to do that using lua? i've been trying to find a way for days but found nothing.

**Comment by ImaginationSuperHero528** [comment]
I've been wanting to find out to

**Comment by NotEpik** [comment]
i think Lua is not possible

**Comment by BombasticTom** [comment]
idk if it's possible but you can instead make it as a different character with different hp icons

**Comment by ImaginationSuperHero528** [comment]
> idk if it's possible but you can instead make it as a different character with different hp icons

They want to know how to change hud style between normal and pixel icons aren't tied to that

**Comment by main-thing** [comment]
Try making 2 seperate stages. One of them use pixel hud in the stages json. Then just switch the stage? I'll try this to see if it works and Ill notify you.

**Comment by main-thing** [comment]
I FOUND A WAY TO DO IT.
This line of code allows you to change the "isPixelStage" variable via lua `-- if last value set to true the game will use the pixel hud. Else, it will not use the pixel hud.
setPropertyFromClass('PlayState', 'isPixelStage', true);
`

**Comment by main-thing** [comment]
> I FOUND A WAY TO DO IT. This line of code allows you to change the "isPixelStage" variable via lua `-- if last value set to true the game will use the pixel hud. Else, it will not use the pixel hud. setPropertyFromClass('PlayState', 'isPixelStage', true); `

I realised that after making it an on resume it no longer changes the arrows. I'll experiment further.

**Comment by main-thing** [comment]
Found a way: https://gamebanana.com/questions/22595

**Comment by YerayBB** [comment]
> I FOUND A WAY TO DO IT. This line of code allows you to change the "isPixelStage" variable via lua `-- if last value set to true the game will use the pixel hud. Else, it will not use the pixel hud. setPropertyFromClass('PlayState', 'isPixelStage', true); `
You know,, that exact line was not working for me when i was trying, i tried all the different ways i could find to change that via lua and none worked.
So at the end i did it on source

> Found a way: https://gamebanana.com/questions/22595

and after quite some testing that works but for pixel mode unless you manae to change the ispixelstage variable before canging the texture, the strus seem off
its the way to change the strumms in lua, and works great

to be honest i gave up on finding an answer here after 10 days or so and was gonna comment my discoveries once i success, but main-thing, you are the hero of this post
