### ISSUE TITLE
i was wondering if i can work for you?

### ISSUE THREAD

**Issue by TheDisabledKid** [ShadowMario/FNF-PsychEngine#3580]
### What is your question?

i can make mac ports for you and see if certain pull request work

**Comment by TheDisabledKid** [comment]
also here is my discord Jonnycat#8275

**Comment by BushsHaxs** [comment]
I work with him
Bushtrain460615#0001

**Comment by HiroMizuki** [comment]
i think u could open a discussion for this, not an issue
