### ISSUE TITLE
Alpha Notes Help

### ISSUE THREAD

**Issue by Androphonomania** [ShadowMario/FNF-PsychEngine#3586]
### Describe your problem here.

I'm trying to make some notes invisible but it does not work. Really nothing else to say. Here's the code for reference:
```
function onStepHit()
    if curStep == 2016 then
        doTweenAlpha('byebyenote1', 0, 0, 5, 'linear');
        doTweenAlpha('byebyenote2', 1, 0, 5, 'linear');
        doTweenAlpha('byebyenote3', 2, 0, 5, 'linear');
        doTweenAlpha('byebyenote4', 3, 0, 5, 'linear');
    end
    if curStep == 2320 then
        doTweenAlpha('welcomebacknote1', 0, 1, 0.01, 'linear');
        doTweenAlpha('welcomebacknote2', 1, 1, 0.01, 'linear');
        doTweenAlpha('welcomebacknote3', 2, 1, 0.01, 'linear');
        doTweenAlpha('welcomebacknote4', 3, 1, 0.01, 'linear');
    end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't edit anything that would effect modcharts

**Comment by Adrian47roblox** [comment]
notetweenalpha()

**Comment by Androphonomania** [comment]
> NoteTweenAlpha()

How do I use this command?

**Comment by Manu614** [comment]
function onStepHit()
    if curStep == 2016  then
        noteTweenAlpha("NoteAlpha1", 0, 0, 0.5, circInOut)
        noteTweenAlpha("NoteAlpha2", 1, 0, 0.5, circInOut)
        noteTweenAlpha("NoteAlpha3", 2, 0, 0.5, circInOut)
        noteTweenAlpha("NoteAlpha4", 3, 0, 0.5, circInOut)
    end
    if curStep == 2320 then
        noteTweenAlpha("NoteAlpha1", 0, 1, 0.1, linear)
        noteTweenAlpha("NoteAlpha2", 1, 1, 0.1, linear)
        noteTweenAlpha("NoteAlpha3", 2, 1, 0.1, linear)
        noteTweenAlpha("NoteAlpha4", 3, 1, 0.1, linear)
    end
end

**Comment by Manu614** [comment]
function onStepHit()
    if curStep == 2016  then
        noteTweenAlpha("NoteAlpha1", 0, 0, 0.5, circInOut)
        noteTweenAlpha("NoteAlpha2", 1, 0, 0.5, circInOut)
        noteTweenAlpha("NoteAlpha3", 2, 0, 0.5, circInOut)
        noteTweenAlpha("NoteAlpha4", 3, 0, 0.5, circInOut)
    end
    if curStep == 2320 then
        noteTweenAlpha("NoteAlpha1", 0, 1, 0.1, linear)
        noteTweenAlpha("NoteAlpha2", 1, 1, 0.1, linear)
        noteTweenAlpha("NoteAlpha3", 2, 1, 0.1, linear)
        noteTweenAlpha("NoteAlpha4", 3, 1, 0.1, linear)
    end
end

**Comment by Adrian47roblox** [comment]
> > NoteTweenAlpha()
> 
> How do I use this command?

noteTweenAlpha("NoteAlpha1", 0, 0, 0.5, circInOut)
noteTweenAlpha("NoteAlpha2", 1, 0, 0.5, circInOut)
noteTweenAlpha("NoteAlpha3", 2, 0, 0.5, circInOut)
noteTweenAlpha("NoteAlpha4", 3, 0, 0.5, circInOut)

**Comment by Manu614** [comment]
the correct order is 0,1,2 and 3 of the opponent

**Comment by MR-FNF** [comment]
Easy! If you want to make it transparent, just make the note texture image completely in PNG (I mean invisible like go to the image, then control + A and press delete)!
