### ISSUE TITLE
Dialogue .JSON and songs

### ISSUE THREAD

**Issue by KyleOliverDeveloper** [ShadowMario/FNF-PsychEngine#3588]
### Describe your problem here.

So, i've tried to make a dialogue appear in my fnf mod, and it doesnt work. Any help on how to load the dialogue?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i coded the songs in-game

**Comment by Theoyeah** [comment]
put the chart in the data folder

**Comment by Theoyeah** [comment]
https://www.youtube.com/watch?v=MU4JHnIALPk&ab_channel=catbrothereverything
It sould help but look at all the video to understand how it works

**Comment by KyleOliverDeveloper** [comment]
> 

thanks man
