### ISSUE TITLE
Discord problem

### ISSUE THREAD

**Issue by Megalonumber0ne** [ShadowMario/FNF-PsychEngine#3590]
### Describe your problem here.

I tried to build 0.5.1 and I got these errors
`
source/Discord.hx:4: characters 8-30 : Type not found : discord_rpc.DiscordRpc
source/Discord.hx:79: characters 3-13 : Type not found : DiscordRpc
source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }
source/Discord.hx:18: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:28: characters 4-14 : Type not found : DiscordRpc
source/Discord.hx:33: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:38: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:43: characters 3-13 : Type not found : DiscordRpc
`
If it's to do with my Haxe version, I'm not sure how to update to 4.2.4 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by HiroMizuki** [comment]
update to 4.2.4, just install the latest version at https://haxe.org/download/ and instal haxeflixel in a prompt, following steps at https://haxeflixel.com/documentation/install-haxeflixel/

that's maybe with discord_rpc too, have u installed it at prompt?

**Comment by Megalonumber0ne** [comment]
I have installed it at prompt, I'll try what you've linked and report back

**Comment by Megalonumber0ne** [comment]
alright I followed all of the steps and my Haxe version went from 4.1.0 to 4.1.5, I tried updating it again to be sure but got the same results

**Comment by HiroMizuki** [comment]
> alright I followed all of the steps and my Haxe version went from 4.1.0 to 4.1.5, I tried updating it again to be sure but got the same results Edit: I just checked my Haxeflixel version and its 4.0.2, is that good?

the haxeflixel doesn't matter, u just need to care about the haxe version
if u already have any previous haxe's version installed, run the unistall setup at HaxeToolKit folder, located at ur local disk directory

**Comment by Megalonumber0ne** [comment]
Alright I'll try that thanks

**Comment by Megalonumber0ne** [comment]
The uninstalling part went fine but the reinstalling part didn't work, I followed all of your steps (I might just be an idiot here) and I got an error saying
` 'haxelib' is not recognized as an internal or external command,
operable program or batch file.
`

**Comment by Megalonumber0ne** [comment]
so, i did what you said and reinstalled everything and i've ended up back at stage 1
![image](https://user-images.githubusercontent.com/87905744/149639325-75b3137a-8785-48b1-83f4-3a73e9004649.png)

**Comment by HiroMizuki** [comment]
did u installed discord_rpc?

**Comment by Megalonumber0ne** [comment]
yeah

**Comment by Megalonumber0ne** [comment]
i'm trying to reinstall it

**Comment by Megalonumber0ne** [comment]
Okay its working, thank you so much for helping me with this
