### ISSUE TITLE
mods category in the menu

### ISSUE THREAD

**Issue by Idontknow44** [ShadowMario/FNF-PsychEngine#3591]
### Describe your problem here.

how can I add the name, picture and the description into my mod - that in the mods category in the menu?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no, I didn't edit anything

**Comment by Pico8430** [comment]
Open the pack.json file in your mod, in there you can modify it to have a name and a description. 
![Captura de pantalla 2022-01-15 124901](https://user-images.githubusercontent.com/91833725/149632299-8dda9ef8-b15b-4434-a737-31bdda636dfa.png)
For an icon, you will need to make it 150x150 and name it "pack.png". (I'm not 100% sure if this works)

**Comment by Idontknow44** [comment]
> 

thanks!
