### ISSUE TITLE
how do i make sprites flip

### ISSUE THREAD

**Issue by Ninjatintin** [ShadowMario/FNF-PsychEngine#3595]
### Describe your problem here.

i have 4 characters on a song and the 4th character is on bf's side but hes pointing the wrong side how do i flip the sprite

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Theoyeah** [comment]
try the Flip-X option in the character editor.
To open it, press 8 while playing a song

**Comment by BombasticTom** [comment]
you can also enter it using debug menu, which you can enter by pressing 7 in all game modes section.
