### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by bgm145632** [ShadowMario/FNF-PsychEngine#3598]
### What is your question?

How to automatically run the exe program when the character dies.👀

**Comment by MrClogsworthYT** [comment]
huhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh? more info please

**Comment by bgm145632** [comment]
I just want to open the web page when the third stage of bob mod dies, I want to change it to open exe

**Comment by MrClogsworthYT** [comment]
you know you could just make a new state right?

**Comment by Collabvmisgood** [comment]
`CoolUtil.browserLoad('the website');`
Put it in where it checks for a gameover

**Comment by Collabvmisgood** [comment]
![image](https://user-images.githubusercontent.com/76410593/149657675-ed1fe11a-99f5-4858-9391-347b5cc4473f.png)
https://youtu.be/RKwQ07SGYfs
