### ISSUE TITLE
layering shit under gf

### ISSUE THREAD

**Issue by PumpTutorials** [ShadowMario/FNF-PsychEngine#3604]
### Describe your problem here.

im making a bg and some specific parts of it wont go under girlfriend and i have no idea how to fix that

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i made a mod in it

**Comment by ImaginationSuperHero528** [comment]
`addLuaSprite('obj', false)`

true for over
