### ISSUE TITLE
How to move dad to the center of the stage?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#3605]
### What is your question?

How to move dad to the center of the stage?

**Comment by Theoyeah** [comment]
you need to create a scene
Look at some youtube tutorials for making a scene

**Comment by mayo78** [comment]
what are you on??? just use `setProperty('dad.x', number)` and `setProperty('dad.y', number)`

**Comment by frantastic24** [comment]
```setCharacterX``` and ```setCharacterY```

**Comment by HiroMizuki** [comment]
are u using lua or source?

**Comment by zwl1619** [comment]
@HiroMizuki Lua
