### ISSUE TITLE
Intro text  support on mod folder

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#3606]
### What feature do you want to get added on the **base** engine?

let us add custom introtext with mod packs n shit.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Theoyeah** [comment]
You can do it on the data folder in assets, just write your texts and it will work

**Comment by Stilic** [comment]
I made this [possible](https://github.com/ShadowMario/FNF-PsychEngine/pull/1809).

**Comment by crispyboi24** [comment]
> I made this [possible](https://github.com/ShadowMario/FNF-PsychEngine/pull/1809).

Thank you!
