### ISSUE TITLE
Portrait gone???

### ISSUE THREAD

**Issue by StormTheMoth** [ShadowMario/FNF-PsychEngine#3617]
### Describe your problem here.

Every time I try to add a dialogue portrait and import the json it won't show up
I tried dave's fun psych engine tutorial but won't work still
WHAT IS GOING ON

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Idk what's going on okay

**Comment by Pico8430** [comment]
Make sure you have a .lua script in your song folder that runs the dialogue, if you do not have one, i'll give it to you.
