### ISSUE TITLE
using icon grid and not icons

### ISSUE THREAD

**Issue by RonHereLMAO** [ShadowMario/FNF-PsychEngine#3620]
### What feature do you want to get added on the **base** engine?

Like in KE a icon grid will look nice and it will give it a vanilla engine feel

EDIT:

alr dont get mad i did this as a joke i was bored and didnt wanna wait till april 1st and yes i agree the grid is a pain in the ass

### To test your sight, and reliability, please select the option of what should NOT be requested.

Thing that would not cause problems

**Comment by mayo78** [comment]
this is the worst suggestion ever

**Comment by Alt-Reality** [comment]
literally its easier for ppl to add icons in the current way than it is to add them into an icon grid

**Comment by crispyboi24** [comment]
Why do you want life to be harder

**Comment by HiroMizuki** [comment]
F U C K I N G  **N O**

**Comment by HiroMizuki** [comment]
in week 7 update, they made it like psych engine icons style, so it's already vanilla

**Comment by RonHereLMAO** [comment]
> Why do you want life to be harder

well like you can edit either like in mic'd up

**Comment by frantastic24** [comment]
A grid is already a pain in the ass to begin with on top of making any mod not made as a pack just as painful

Also
🤡🤡
![Screenshot_2022-01-16-03-19-12-293.jpg](https://user-images.githubusercontent.com/95725102/149649752-fdc44c5f-92fd-49d4-8892-aed77837370d.jpg)

**Comment by Theoyeah** [comment]
YOU STUPID RONHERELMAO IT IS HORRIBLE AND DID YOU HAVE A BRAIN

**Comment by Doritojoey** [comment]
I think he means like in mods/images the regular iconGrid style could be easier to use, so like in the icon type box put like bruhGrid/1,2 or 3,4 so on and so forth

Would make KE porting easier and could better manage icons so it isn't a bad idea

**Comment by Stilic** [comment]
no

**Comment by Doritojoey** [comment]
What
It's not a bad idea at all

**Comment by Stilic** [comment]
bruh yeah im stupid

**Comment by HiroMizuki** [comment]
> I think he means like in mods/images the regular iconGrid style could be easier to use, so like in the icon type box put like bruhGrid/1,2 or 3,4 so on and so forth
> 
> Would make KE porting easier and could better manage icons so it isn't a bad idea

in KE, they're using the system of separate icons too

**Comment by HiroMizuki** [comment]
everyone is making things easier like the week 7 update, that did the separate icons thingies

**Comment by Doritojoey** [comment]
> > I think he means like in mods/images the regular iconGrid style could be easier to use, so like in the icon type box put like bruhGrid/1,2 or 3,4 so on and so forth
> > Would make KE porting easier and could better manage icons so it isn't a bad idea
> 
> in KE, they're using the system of separate icons too

Nobody uses newer KE

**Comment by HiroMizuki** [comment]
> > > I think he means like in mods/images the regular iconGrid style could be easier to use, so like in the icon type box put like bruhGrid/1,2 or 3,4 so on and so forth
> > > Would make KE porting easier and could better manage icons so it isn't a bad idea
> > 
> > 
> > in KE, they're using the system of separate icons too
> 
> Nobody uses newer KE

yeah. But i still think it's not a good idea for the main psych engine yknow, cuz the separate icons makes it easier to code characters for the game, and the objective of Psych is to make everything easier for modders

maybe he could code the grid himself, or just wait till someone makes it, idk

**Comment by RonHereLMAO** [comment]
> I think he means like in mods/images the regular iconGrid style could be easier to use, so like in the icon type box put like bruhGrid/1,2 or 3,4 so on and so forth
> 
> Would make KE porting easier and could better manage icons so it isn't a bad idea

now i think of it yeah this may not be a bad idea maybe a option for icongrid but eh this was all a joke

**Comment by frantastic24** [comment]
the way it works now is already easier and actually straightforward, we don't need a grid

**Comment by Doritojoey** [comment]
> > I think he means like in mods/images the regular iconGrid style could be easier to use, so like in the icon type box put like bruhGrid/1,2 or 3,4 so on and so forth
> > Would make KE porting easier and could better manage icons so it isn't a bad idea
> 
> now i think of it yeah this may not be a bad idea maybe a option for icongrid but eh this was all a joke

I mean in mods. This can be used in mods especially cuz all char icons can be packed in one file and it'd be more convenient

**Comment by doom699** [comment]
no
