### ISSUE TITLE
How can I make the opponent (for example; Dad) have a custom note skin?

### ISSUE THREAD

**Issue by doggogit** [ShadowMario/FNF-PsychEngine#3623]
### What is your question?

As it says on the tin, how would I go about implementing a custom note skin for the opponent?

I had nowhere else to ask, except here, any help would be appreciated.

**Comment by BeansCool54** [comment]
[here](https://github.com/ShadowMario/FNF-PsychEngine/discussions/995)

**Comment by Gui-iago** [comment]
this is an event, no source required, throw those files into mods/custom_events

https://cdn.discordapp.com/attachments/922851578996744252/931810893359091742/noteskinchangeOPPT.lua
https://cdn.discordapp.com/attachments/922851578996744252/931810892780285982/noteskinchangeOPPT.txt

**Comment by Gui-iago** [comment]
> this is an event, no source required, throw those files into mods/custom_events
> 
> *da links*

bf variant
https://cdn.discordapp.com/attachments/922851578996744252/931810892985802752/noteskinchangeBF.lua
https://cdn.discordapp.com/attachments/922851578996744252/931810893170376744/noteskinchangeBF.txt

**Comment by Gui-iago** [comment]
in case the events don't work, use these instead

https://cdn.discordapp.com/attachments/922851578996744252/931007855404908614/opponent.lua -- edit this and set the Opponent's name
https://cdn.discordapp.com/attachments/922851578996744252/931007855681749033/crash.lua -- prevents crash when dying

**Comment by doggogit** [comment]
Oh my God, thank you!!

I woke up an hour or so ago and I *have* to try these!

I'll close this once I try these.

**Comment by doggogit** [comment]
Tested out both the Lua mod event and the source code solution.

They work well without any issues!

I'll be sure to credit you guys, just 'cause this was a tremendous issue for the mod team and we finally solved it.

Thanks again!
