### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by Kitsuism** [ShadowMario/FNF-PsychEngine#3627]
### Describe your bug here.

I left the game loading a song for about 5 mins by mistake, and the game ended up taking up **9GB** of memory
[leak proof ](https://pbs.twimg.com/media/FJNQrJEVcAEFqYs?format=png&name=small)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing, using base v0.5.1 build

**Comment by HiroMizuki** [comment]
it normally happens when the game is offscreen while loading something
but i've never seen 9GB, kinda weird

**Comment by Kitsuism** [comment]
my only guess for the size is since i use psych to make BETADCIU's, it's holding every character there for way longer than it should need to
