### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by KyleOliverDeveloper** [ShadowMario/FNF-PsychEngine#3631]
### Describe your problem here.

So, i wanted to replace the menu screen (menuBG) without replacing it in the assets folder. But i cant find any archive to put the image in, so could someone explain it to me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by denumu07** [comment]
It's only Possible in Source i think. 

So im just gonna tell how to do it for Source:
1. Go to MainMenuState.hx
2. then scroll down until you find this:
![Screenshot 2022-01-16 130056](https://user-images.githubusercontent.com/89101366/149659099-6e9d2a41-99e7-40aa-9ffc-ce526478312a.png)
3. Change the "menuBG", "menuDesat" to your imagine.
That Should Work.

Maybe there is a Way to make it in Lua but i don't know.

**Comment by KyleOliverDeveloper** [comment]
> It's only Possible in Source i think.
> 
> So im just gonna tell how to do it Without Doing something in Mods/images:
> 
> 1. Go to MainMenuState.hx
> 2. then scroll down until you find this:
>    ![Screenshot 2022-01-16 130056](https://user-images.githubusercontent.com/89101366/149659099-6e9d2a41-99e7-40aa-9ffc-ce526478312a.png)
> 3. Change the "menuBG", "menuDesat" to your
>    image.
>    That Should Work.
> 
> Maybe there is a Way to make it in Lua but i don't know.

Thanks, that really helped alot for when i learn how to compile the engine

**Comment by BombasticTom** [comment]
you don't need source code, you can just put the background into images of your mod folder and name it as the background name

**Comment by frantastic24** [comment]
As the person above said you can replace assets by just putting them in ```mods/images``` but if you want to edit any menu further than that you'll need to edit the source code

**Comment by KyleOliverDeveloper** [comment]
> you don't need source code, you can just put the background into images of your mod folder and name it as the background name

Thanks!!
