### ISSUE TITLE
bf wrong sprite note thing (how the hell do i call this)

### ISSUE THREAD

**Issue by Klanker** [ShadowMario/FNF-PsychEngine#3635]
### Describe your bug here.

if you hit a note you can start holding another one (assuming ghost tapping is on) n then release the note that you hit and boyfriend will still stay on its animation instead of like idlin or smth
no idea if this is intentional, doesnt seem so though
this is the [default psych engine from gamebanana](https://gamebanana.com/mods/309789)
[here's a video](https://drive.google.com/file/d/1sezW4gyTEoKKUB2Y94DrJYEdPxAV0fQ0/view?usp=sharing) (i do it at 0:20)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

it is literally the version from gamebanana 🤡

**Comment by Theoyeah** [comment]
It is normal.

**Comment by Klanker** [comment]
> It is normal.

how would you know?

**Comment by BombasticTom** [comment]
it's a literal thing in vanilla game too, the devs are also aware

**Comment by Klanker** [comment]
> it's a literal thing in vanilla game too, the devs are also aware

the vanilla game doesn't have ghost tapping

**Comment by 0-skid** [comment]
> > it's a literal thing in vanilla game too, the devs are also aware
> 
> the vanilla game doesn't have ghost tapping

yes, but it still does that in the base game. i'm pretty sure it's not even a bug

**Comment by ShadowMario** [comment]
Not a bug.
