### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by perngjiafu** [ShadowMario/FNF-PsychEngine#3636]
### Describe your bug here.

crashes midway the song. idk why. even in zanta taiko, it crashes when its at tom's turn

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes but it also crashes when i put it without edited

**Comment by Theoyeah** [comment]
This is to look at the creator, not here

**Comment by frantastic24** [comment]
Can you actually describe how and when this "bug" is happening because just saying "it crashes" doesn't help at all

**Comment by perngjiafu** [comment]
https://user-images.githubusercontent.com/54176781/149769208-33adf223-d729-4b38-9b58-8482754237f3.mp4

btw didnt edit anything

> Can you actually describe how and when this "bug" is happening because just saying "it crashes" doesn't help at all

**Comment by frantastic24** [comment]
Isn't that a problem with the mod
Why are you reporting it here

**Comment by perngjiafu** [comment]
> Isn't that a problem with the mod Why are you reporting it here

then how does people play with the mod?
i dont understand
its on all the mods i play

**Comment by Theoyeah** [comment]
Yes but it is the creator problem, not the engine.

**Comment by bbpanzu** [comment]
> > Isn't that a problem with the mod Why are you reporting it here
> 
> then how does people play with the mod? i dont understand its on all the mods i play on psych engine 0.5.1

the taiko script is by me and it's buggy. only ask questions pertaining to BASE psych engine itself on here.
