### ISSUE TITLE
Week 2 background is gone.

### ISSUE THREAD

**Issue by RedstoneGuyLol** [ShadowMario/FNF-PsychEngine#3654]
### Describe your bug here.

I'm making a FNF with covers and stuff. I only changed the assets of the characters and the charts and now the background is black and only works once
![pyschbug](https://user-images.githubusercontent.com/63218795/149677961-b4042eea-3f2b-43d5-bc48-bbb40f64e4cd.PNG)
.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only changed the assets of the characters and the charts.

**Comment by RedstoneGuyLol** [comment]
I'm also using it on Psych 5.1

**Comment by MrClogsworthYT** [comment]
> I'm also using it on Psych 5.1

week 2 bg is a spritesheet lmfao u probs had a broken xml or smth

**Comment by RedstoneGuyLol** [comment]
> 

Nothings wrong with the xml, I said I only changed the characters and chart.

**Comment by cherryiguess** [comment]
if you ported charts from, lets say kade engine 1.2 or something, it doesnt use softcoded stage choice, or something, so it creates a dummy stage if no stage is found in the json file, just go to the debug menu and change the stage if thats the problem

**Comment by RedstoneGuyLol** [comment]
> if you ported charts from, lets say kade engine 1.2 or something, it doesnt use softcoded stage choice, or something, so it creates a dummy stage if no stage is found in the json file, just go to the debug menu and change the stage if thats the problem

I never ported the charts i made them on psych engine. I tried doing that anyways to no avail.

**Comment by main-thing** [comment]
Black background means you have low ram. I guess that you have 4 gigs of ram and the background is 8k res. I suggest to turn on low detail in options as this will only show for you.

**Comment by RedstoneGuyLol** [comment]
> Black background means you have low ram. I guess that you have 4 gigs of ram and the background is 8k res. I suggest to turn on low detail in options as this will only show for you.

I didn't change it at all. Its the same background from the game.

**Comment by main-thing** [comment]
> > Black background means you have low ram. I guess that you have 4 gigs of ram and the background is 8k res. I suggest to turn on low detail in options as this will only show for you.
> 
> I didn't change it at all. Its the same background from the game.

i mean that even if you did not change it. It will not show due to low ram. (check how much ram your pc/laptop has)

**Comment by main-thing** [comment]
just go to options and enable low quality to fix it.
