### ISSUE TITLE
Removing Weeks

### ISSUE THREAD

**Issue by KyleOliverDeveloper** [ShadowMario/FNF-PsychEngine#3656]
### What is your question?

So i want to remove the weeks from the main menu without source code, and idk how to do that. Hope someone could help!

**Comment by frantastic24** [comment]
Remove them from `assets/weeks`

**Comment by KyleOliverDeveloper** [comment]
> Remove them from `assets/weeks`

The thing is that there’s only the weeks folder separated and if I delete them, they won’t disappear. I tried removing it in the manifest folder but the game crashed so I cannot do like that.

**Comment by frantastic24** [comment]
I literally did this myself and it worked, just remove their .json and remove them from weekList

**Comment by KyleOliverDeveloper** [comment]
> I literally did this myself and it worked, just remove their .json and remove them from weekList

ok
