### ISSUE TITLE
Lua Animation Not Playing on curStep

### ISSUE THREAD

**Issue by NesDoesGithub** [ShadowMario/FNF-PsychEngine#3657]
### Animation not playing on curStep.

I am trying to make an animation play mid song and it will not work, the sprite for the animation is in the stage code. The animation plays on the countdown but it won't play on curStep.

![gfdgfdy8ughsf8](https://user-images.githubusercontent.com/95316430/149681294-8936c6f9-097a-4437-8646-d1041267121f.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by frantastic24** [comment]
`curStep`, it's case sensitive

**Comment by NesDoesGithub** [comment]
> `curStep`, it's case sensitive

thanks
