### ISSUE TITLE
How can i make screen wave like on Sunshine sonic.exe 

### ISSUE THREAD

**Issue by Den198888** [ShadowMario/FNF-PsychEngine#3658]
### Describe your problem here.

i am trying to port but it was my first time doing it, LUA is what i am using i already did the lights out but idk how to make screen wave and floating opponent in circle help plssss
![Screenshot_2022-01-17-06-54-19-49_e4b17b709a49379a0b207d2e3e43882a](https://user-images.githubusercontent.com/96397208/149681682-4050d2a2-7398-4723-a9f2-a994840d101b.jpg)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

Just winning icon

**Comment by frantastic24** [comment]
you can create a vcr effect with `addVCREffect()` and for the floating effect
```
local floaty = 41.82
local tailscircle = '' -- you'll use this to make the opponent hover up/down or in circles

function onUpdate()
	floaty = floaty+0.03

	if tailscircle == 'hovering' or tailscircle == 'circling' then
		setCharacterY('dad', getCharacterY('dad')+math.sin(floaty) * 1.3);
	end
	if tailscircle == 'circling' then
		setCharacterX('dad', getCharacterX('dad')+math.cos(floaty) * 1.3);
	end
end
```

**Comment by Den198888** [comment]
Thank you so much ♥️♥️

**Comment by Den198888** [comment]
can i ask 1 amm, where i gonna put the 'addVCREffect()' on stage or lua on
data tnxx

**Comment by frantastic24** [comment]
if you are planning to just use it in one stage just put it in your stage .lua under `onCreate()`

**Comment by Den198888** [comment]
![Screenshot_2022-01-18-09-11-13-72_87c2225eebc34d2513fa0e7ad5b93cfc](https://user-images.githubusercontent.com/96397208/149853769-497d5c9f-3907-46da-b5fc-4860599f663b.jpg)


Like this, i run the game and the stage is gone

**Comment by frantastic24** [comment]
you have to specify which camera to add the effect on, like `addVCREffect('camHUD')` for example

**Comment by Den198888** [comment]
ohh, okay imma try it

**Comment by Den198888** [comment]
for some reason, if i put it in the TDStage.lua the TailsBG is gone but it doesn't say error on lua

**Comment by frantastic24** [comment]
then you're doing something wrong

**Comment by Den198888** [comment]
![Screenshot_2022-01-18-10-35-03-02_87c2225eebc34d2513fa0e7ad5b93cfc](https://user-images.githubusercontent.com/96397208/149861118-df83dfdc-81cb-44a6-9836-d771930cd9dc.jpg)

but i placed it on under the function onCreate()

**Comment by frantastic24** [comment]
you didn't close the line with `;`

**Comment by Den198888** [comment]
im sorrryyy, i am not good at lua's

**Comment by Den198888** [comment]
![Screenshot_2022-01-18-10-54-39-85_87c2225eebc34d2513fa0e7ad5b93cfc](https://user-images.githubusercontent.com/96397208/149862908-05e14a84-ec5e-4938-a606-f7c09b665a30.jpg)

i did it but, i doesn't apply the effects and bg still gone

**Comment by Den198888** [comment]
!
![Uploading Screenshot_2022-01-18-10-57-02-99_99c04817c0de5652397fc8b56c3b3817.jpg…]()

**Comment by Den198888** [comment]
![Screenshot_2022-01-18-10-57-02-99_99c04817c0de5652397fc8b56c3b3817](https://user-images.githubusercontent.com/96397208/149863073-ab23b19d-f9ae-4a3e-a6d7-f3f0516667ca.jpg)

**Comment by frantastic24** [comment]
you probably have an outdated version that doesn't support shaders then

**Comment by Den198888** [comment]
I am at 0.5, but still thank you for your help :)

**Comment by frantastic24** [comment]
i'm pretty sure 0.5 doesn't have shader support so yeah

**Comment by Den198888** [comment]
maybe, i will wait for 0.5.1 port 😄

**Comment by frantastic24** [comment]
You're doing everything through the mods folder right? If so you can just get the latest version and just copy the folder
I recommend updating to 0.5.1 anyways since some Lua variables (namely `curBeat` I think) were broken in 0.5

**Comment by Den198888** [comment]
Ok, I'll do that. thanks, im using android ports soo i gonna need to wait
till, someone or the porter update it😄

**Comment by frantastic24** [comment]
I see, probably gonna take a good while then unfortunately

**Comment by Den198888** [comment]
Ok, no problem. but can i have an 1 question again 😅 it is possible to
change the 3, 2, 1, GO  to ready, set, go using the onStartCountdown i saw
it on the source of sonic with crochet i think, but how can i stop the song
while playing the ready, set, go

**Comment by Den198888** [comment]
![Screenshot_2022-01-18-23-22-56-19_87c2225eebc34d2513fa0e7ad5b93cfc](https://user-images.githubusercontent.com/96397208/149966334-79bee4fb-8c4c-4b41-8f62-484a80bcfa44.jpg)

i did mine like this

**Comment by frantastic24** [comment]
You should use `function onStartCountdown()` and `if counter == (number)` for that, I think
I'm doing my own port of this song so I can let you know if this works in a bit

**Comment by Den198888** [comment]
like this? or i will put the counter on up
(sorry i didn't notice your comment i sleep)

function onStartCoundown()
    if counter == 0 then
        setProperty('ready1.visible', true);
        playSound('intro2')
   end

**Comment by Den198888** [comment]
i will try it

**Comment by frantastic24** [comment]
Well I did kinda manage to replicate it by skipping the countdown and just doing it manually but in doing that it messed up the spawning strums and the opponent's left strum behaves weirdly, so I just decided not to include it

**Comment by Den198888** [comment]
maybe the best way is just like
on sounds
make no sound intro3
'ready' the intro1 (will be intro2)
'set' intro2 (intro1)
'go' introGo

then
ready, set, go assets

**Comment by Den198888** [comment]
is the 

var is local? and

spr.alpha like when tdoll-alt hits note will hide the hud

**Comment by frantastic24** [comment]
Unfortunately you can't use different countdown assets with a folder, although you _can_ if you include the song in a different pack but that's just inconvenient
I can send you the code I made for the lights out segment if you want
[Here's the finished product if you're interested](https://youtu.be/ZTeY4YI93S8)

**Comment by Den198888** [comment]
wait, how do you keep the hud fade when long notes, i alrdy did the off lights

**Comment by frantastic24** [comment]
`if curStep > 588 and curStep < 860 and isSustainNote == false then`

**Comment by Den198888** [comment]
the if curStep on function onStepHit

function opponentNoteHit
the isSustainNote == false then 
       doTweenAlpha('hudAlpha', 'camHUD', 1, 0.1, 'linear');

**Comment by frantastic24** [comment]
this doesn't go in curStep, the entire line (yes, the ANDs are part of it) goes under `onOpponentHit`

**Comment by Den198888** [comment]
ohh sorry, i thought curStep only will be on onStepHit thnx


(i will credits you 😄)

**Comment by Den198888** [comment]
![Screenshot_2022-01-19-10-57-58-20_87c2225eebc34d2513fa0e7ad5b93cfc](https://user-images.githubusercontent.com/96397208/150055605-f5a11cea-ad73-401c-9657-1f718eb1c09a.jpg)

like this or doNoteAlpha is what i need i cant send videos here for soem reason

**Comment by frantastic24** [comment]
first you need to set the alpha to 0.7, then do an alpha tween that lowers it to 0
```
setProperty('camHUD.alpha', 0.7);
doTweenAlpha('hudAlpha', 'camHUD', 0, 0.4, 'linear')
```
that's pretty much what i did except i individually got rid of each UI object so i can just brighten the strums and nothing else, but this works if you prefer the simpler solution

**Comment by Den198888** [comment]
id, direction, noteType, isSustainNote  iforgot to put this, but it fade fast then back to normal again

**Comment by frantastic24** [comment]
it's supposed to fade quickly, that's how it works in the original song
what do you mean by "back to normal" though, because it's working fine for me

**Comment by Den198888** [comment]
how can i send vids here, wait i will show ti

**Comment by frantastic24** [comment]
you could upload it to google drive or something if it's too big

**Comment by Den198888** [comment]
https://user-images.githubusercontent.com/96397208/150059009-9b3089bc-39b1-46ac-82a9-32de5d3775cf.mp4

this

**Comment by frantastic24** [comment]
> ![Screenshot_2022-01-19-10-57-58-20_87c2225eebc34d2513fa0e7ad5b93cfc](https://user-images.githubusercontent.com/96397208/150055605-f5a11cea-ad73-401c-9657-1f718eb1c09a.jpg)
> 
> like this or doNoteAlpha is what i need i cant send videos here for soem reason

did you delete the tween on this screenshot

**Comment by Den198888** [comment]
yes and replaced it like this 

setProperty('camHUD.alpha', 0.7);
doTweenAlpha('hudAlpha', 'camHUD', 0, 0.4, 'linear')

**Comment by Den198888** [comment]
![Screenshot_2022-01-19-11-26-24-63_87c2225eebc34d2513fa0e7ad5b93cfc](https://user-images.githubusercontent.com/96397208/150059613-681df878-ed64-45e4-b35f-542c02e73301.jpg)

**Comment by frantastic24** [comment]
no you did it the other way around

**Comment by Den198888** [comment]
https://user-images.githubusercontent.com/96397208/150060406-a1fc1666-ab38-4f39-ac57-f79064edb1cc.mp4



still keeps coming back to normal it doesn't want to stay faded

**Comment by frantastic24** [comment]
send a screenshot of the code, i already tested it twice and it works fine

**Comment by Den198888** [comment]
![Uploading Screenshot_2022-01-19-11-51-13-30_87c2225eebc34d2513fa0e7ad5b93cfc.jpg…]()

**Comment by Den198888** [comment]
![Screenshot_2022-01-19-11-51-13-30_87c2225eebc34d2513fa0e7ad5b93cfc](https://user-images.githubusercontent.com/96397208/150060888-ab52b4c1-3096-426f-aac7-3c975962e3f6.jpg)

**Comment by frantastic24** [comment]
hmm do you mind sending me the entire script file? the code is correct so there's no reason for the alpha to return to 1, on this piece of code anyways

**Comment by Den198888** [comment]
okay but hide it fast

**Comment by frantastic24** [comment]
k

**Comment by frantastic24** [comment]
i don't see it

**Comment by Den198888** [comment]
what you cant see

**Comment by frantastic24** [comment]
where's the file, i don't have much time to go through it right now

**Comment by Den198888** [comment]
how cna i send file

**Comment by frantastic24** [comment]
change the extension to .txt and send it as you would with any other file

**Comment by Den198888** [comment]
https://www.mediafire.com/file/7ux24xcs7t7lnf3/lol.lua/file

this i am not using windows i cant put txt

**Comment by frantastic24** [comment]
any file explorer can do that but it's fine

**Comment by Den198888** [comment]
did you already downloaded it i will hide it now

**Comment by frantastic24** [comment]
it's still working fine for me so i guess it could either be a source code problem or one of the other scripts you're running

**Comment by Den198888** [comment]
wait, the addLuaScript('hudshe') i deleted it and its now working, i forgot that i used addLuaScript with hidehud  on it

**Comment by Den198888** [comment]
the problem is, i will vid it when it hits 860 step it doesn't back the hud

**Comment by frantastic24** [comment]
Again sounds like an issue with one of the scripts you're loading, you didn't send me those and I don't have access to the main one right now so I can't help much

**Comment by Den198888** [comment]
can i do both like if curStep 860 already have one

if curStep == 860
      setProperty('camHUD.alpha', 1);

**Comment by Den198888** [comment]
- I did it i remove some of it 
![Screenshot_2022-01-19-14-11-24-99_87c2225eebc34d2513fa0e7ad5b93cfc](https://user-images.githubusercontent.com/96397208/150074265-97deac5b-86eb-4644-b998-13e8f542ef23.jpg)
but is there anyway to make thing  go back to normal the playerstrum at curStep 860?

**Comment by frantastic24** [comment]
just do the same thing but with their original X value
i figured out a way to do a custom countdown without having to include the song in a separate pack, just make the intro sounds blank and hide countdown assets when it ticks, then do the custom stuff

**Comment by frantastic24** [comment]
```
function onCountdownTick(counter)
	if counter == 0 then
			addLuaSprite('ready', true);
			playSound('ready');
			doTweenX('readyx', 'ready.scale', 0.9, crochet/500);
			doTweenY('readyy', 'ready.scale', 0.9, crochet/500);
	end
	if counter == 1 then
			addLuaSprite('set', true);
			removeLuaSprite('ready');
			playSound('set');
			doTweenX('setx', 'set.scale', 0.9, crochet/500);
			doTweenY('sety', 'set.scale', 0.9, crochet/500);
	end
	if counter == 2 then
			addLuaSprite('go', true);
			removeLuaSprite('set');
			playSound('go');
			doTweenX('gox', 'go.scale', 1.1, crochet/500);
			doTweenY('goy', 'go.scale', 1.1, crochet/500);
	end
	if counter == 3 then
			removeLuaSprite('go');
	end
		setProperty('countdownReady.visible', false)
		setProperty('countdownSet.visible', false)
		setProperty('countdownGo.visible', false)
end
```
intro sounds in modpack are blank, this code can also be edited to play this custom countdown if this song is playing and you can do something similar but only play the vanilla sounds instead (so you restore the original countdown)
https://user-images.githubusercontent.com/95725102/150222618-b8b2168b-402a-4e57-856c-c7b6bc6695e8.mp4

**Comment by Den198888** [comment]
can it be delay like 3,,2,,1,,GO i think its also wait i will

**Comment by Den198888** [comment]
it can, also i tried to add the TdollStart not that visible because of the blacks

**Comment by Den198888** [comment]
![Screenshot_2022-01-20-07-09-14-54](https://user-images.githubusercontent.com/96397208/150233039-fdc64741-6c1b-4c53-bd0d-127af1788cd7.jpg)

i did is like this

**Comment by Den198888** [comment]
idk if the startCountdown work i just maked it (start.visible', true)

**Comment by Den198888** [comment]
https://user-images.githubusercontent.com/96397208/150236283-8e0fea4c-d815-4a9d-9887-e4add8afc549.mp4

like this, my phone is lagging when to many assets

**Comment by Den198888** [comment]
https://user-images.githubusercontent.com/96397208/150237377-96fbc912-ac93-49a1-914d-08d2540f49ce.mp4

and the thing where, tdoll will back to his original position

**Comment by Den198888** [comment]
i did like this this is from the source code 
![Screenshot_2022-01-19-19-59-08-12_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/96397208/150238354-4c778b2f-db11-4447-94b4-90ae305f5421.jpg)

and lua
![Screenshot_2022-01-20-08-05-50-71_87c2225eebc34d2513fa0e7ad5b93cfc](https://user-images.githubusercontent.com/96397208/150238359-b868f6a8-6d33-47fb-8796-6cd9bfbcfe89.jpg)
