### ISSUE TITLE
Error with compiling 

### ISSUE THREAD

**Issue by erasedcardsx** [ShadowMario/FNF-PsychEngine#3659]
### Describe your problem here.

I had asked this in the Psych discord server, no one knew (so far at least lol)
anyways. this is my error. before you ask no i havnt tampered with stuff.

icrosoft Windows [Version 10.0.19043.1466]
(c) Microsoft Corporation. All rights reserved.

C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:11: characters 8-37 : Type not found : flixel.util.FlxDirectionFlags
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:484: characters 21-25 : Unknown identifier : WALL
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:504: characters 21-25 : Unknown identifier : WALL
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:530: characters 21-28 : Unknown identifier : CEILING
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:550: characters 21-26 : Unknown identifier : FLOOR

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

all i've done is add a new character so far, to test if it works.

**Comment by glitchygmr** [comment]
@erasedcardsx did you fix the error? if you did could you please tell me how, ive been having the same issues

**Comment by erasedcardsx** [comment]
> @erasedcardsx did you fix the error? if you did could you please tell me how, ive been having the same issues

yeah! i had to install haxe 4.2.4, then remove Haxe from my library and install it again ^~^

**Comment by glitchygmr** [comment]
tried that before, didnt work :( thanks anyway!!!
