### ISSUE TITLE
override function openSubState(SubState:FlxSubState)

### ISSUE THREAD

**Issue by BlazeGod88** [ShadowMario/FNF-PsychEngine#3660]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/96097475/149683127-f796000c-3534-4ed6-9ac6-b2885d4ef6da.png)
i dont know how to fix it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by BombasticTom** [comment]
the function is maybe unexpected because line 1902 doesn't have ;?
