### ISSUE TITLE
GenerateStaticArrows callback and generateStaticArrows function in LUA.

### ISSUE THREAD

**Issue by BoloVEVO** [ShadowMario/FNF-PsychEngine#3679]
### What feature do you want to get added on the **base** engine?

I'm not that experienced (I'm dumb iow) to make my own pull request so I'm making a feature request instead lol.

GenerateStaticArrows callback in LUA called "onGenerateStaticArrows(player)".  To make your custom arrows intro.

generateStaticArrows(player) LUA function.

Here are some examples if you didn't understand.
**LUA example of only appearing arrows on BF's side**
```
function onGenerateStaticArrows(player) -- 0 (Opponent), 1 (Boyfriend)
    return Function_Stop; -- This will make arrows to not appear at the start of the song
    generateStaticArrows(1) -- This will make only BF arrows appear and not the opponent ones.
end

```
**LUA example of only arrows appearing on Opponent's side**
```
function onGenerateStaticArrows(player) -- 0 (Opponent), 1 (Boyfriend)
    return Function_Stop; -- This will make arrows to not appear at the start of the song
    generateStaticArrows(0) -- This will make only Opponent arrows appear and not BF ones
end

```
**LUA example of Termination intro**

```
function onGenerateStaticArrows(player) -- 0 (Opponent), 1 (Boyfriend)
    return Function_Stop; -- This will make arrows to not appear at the start of the song
end

function onStepHit()
	if curStep == 1 then
		noteTweenAlpha('defaultOpponentStrumX0', 0, 1, 0.4)
		noteTweenAlpha('defaultPlayerStrumX3', 7, 1, 0.4)
	end
	if curStep == 32 then
		noteTweenAlpha('defaultOpponentStrumX1', 1, 1, 0.4)
		noteTweenAlpha('defaultPlayerStrumX2', 6, 1, 0.4)
	end
	if curStep == 64 then
		noteTweenAlpha('defaultOpponentStrumX2', 2, 1, 0.4)
		noteTweenAlpha('defaultPlayerStrumX1', 5, 1, 0.4)
	end
	if curStep == 96 then
		noteTweenAlpha('defaultOpponentStrumX3', 3, 1, 0.4)
		noteTweenAlpha('defaultPlayerStrumX0', 4, 1, 0.4)
	end
end
```
Sorry for my bad english :C

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tposejank** [comment]
make them invisible

**Comment by BoloVEVO** [comment]
> make them invisible

When notes appear it makes a short animation when they go slightly down and their alpha turns to 1 so, if you even put your alpha notes to 0 when you create the script it will always appear so it's kinda a problem.

**Comment by LeanDapper** [comment]
> 

this is true

even if you did put it in postcreate or update it always tweens their alpha no matter

**Comment by ShadowMario** [comment]
Would cause Null Object References, we don't have to add `onGenerateStaticArrows` because `onCreatePost` can already do the job.

**Comment by BoloVEVO** [comment]
> Would cause Null Object References, we don't have to add `onGenerateStaticArrows` because `onCreatePost` can already do the job.

How? I've already tried with doTweenAlpha, noteTweenAlpha in onCreatePost and same problem.
