### ISSUE TITLE
MODCHART HELP

### ISSUE THREAD

**Issue by DybaTubeYT1** [ShadowMario/FNF-PsychEngine#3683]
### Describe your problem here.

How i change window position?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Ummm yes and no, i just putted 3 songs on the game

**Comment by frantastic24** [comment]
#3473

**Comment by DybaTubeYT1** [comment]
HOLY SHIT THANK YOU!

**Comment by DybaTubeYT1** [comment]
wait its not working

**Comment by frantastic24** [comment]
You have to merge it to your source code first

**Comment by DybaTubeYT1** [comment]
K

Em seg, 17 de jan de 2022 3:38 PM, frantastic24 ***@***.***>
escreveu:

**Comment by DybaTubeYT1** [comment]
WHEN I COMPILE IT I RECEIVE THIS

`source/PlayState.hx:92: characters 34-46 : Type not found : ShaderEffect
source/CoolUtil.hx:17: lines 17-182 : Defined in this class
source/Note.hx:279: characters 21-25 : Class<PlayState> has no field SONG
source/Note.hx:295: characters 16-28 : Class<PlayState> has no field isPixelStage
source/Note.hx:310: characters 45-56 : Class<PlayState> has no field daPixelZoom
source/Note.hx:116: characters 33-37 : Class<PlayState> has no field SONG
source/StrumNote.hx:54: characters 16-20 : Class<PlayState> has no field SONG
source/StrumNote.hx:54: characters 52-56 : Class<PlayState> has no field SONG
source/StrumNote.hx:54: characters 96-100 : Class<PlayState> has no field SONG
source/StrumNote.hx:56: characters 16-28 : Class<PlayState> has no field isPixelStage
source/StrumNote.hx:126: characters 45-56 : Class<PlayState> has no field daPixelZoom
source/StrumNote.hx:227: characters 18-30 : Class<PlayState> has no field isPixelStage
source/Note.hx:155: characters 17-21 : Class<PlayState> has no field SONG
source/Note.hx:157: characters 22-26 : Class<PlayState> has no field SONG
source/Note.hx:211: characters 17-29 : Class<PlayState> has no field isPixelStage
source/Note.hx:246: characters 18-30 : Class<PlayState> has no field isPixelStage
source/Note.hx:254: characters 72-76 : Class<PlayState> has no field SONG
source/Note.hx:255: characters 18-30 : Class<PlayState> has no field isPixelStage
source/Note.hx:262: characters 17-29 : Class<PlayState> has no field isPixelStage
source/Note.hx:263: characters 26-37 : Class<PlayState> has no field daPixelZoom
source/editors/ChartingState.hx:178: characters 78-82 : Class<PlayState> has no field SONG
source/editors/ChartingState.hx:217: characters 17-21 : Class<PlayState> has no field SONG
source/editors/ChartingState.hx:218: characters 22-26 : Class<PlayState> has no field SONG
source/editors/ChartingState.hx:2066: characters 13-17 : Class<PlayState> has no field SONG
source/editors/ChartingState.hx:376: characters 14-18 : Class<PlayState> has no field SONG
source/editors/ChartingState.hx:538: characters 24-28 : Class<PlayState> has no field SONG
source/editors/ChartingState.hx:1253: characters 15-19 : Class<PlayState> has no field SONG
source/NoteSplash.hx:17: characters 16-20 : Class<PlayState> has no field SONG
source/NoteSplash.hx:17: characters 53-57 : Class<PlayState> has no field SONG
source/NoteSplash.hx:17: characters 98-102 : Class<PlayState> has no field SONG
source/NoteSplash.hx:34: characters 17-21 : Class<PlayState> has no field SONG
source/NoteSplash.hx:34: characters 54-58 : Class<PlayState> has no field SONG
source/NoteSplash.hx:34: characters 102-106 : Class<PlayState> has no field SONG
source/editors/EditorPlayState.hx:92: characters 17-21 : Class<PlayState> has no field SONG
source/editors/EditorPlayState.hx:93: characters 64-68 : Class<PlayState> has no field SONG
source/editors/EditorPlayState.hx:171: characters 45-49 : Class<PlayState> has no field SONG
source/editors/EditorPlayState.hx:177: characters 28-32 : Class<PlayState> has no field SONG
source/editors/EditorPlayState.hx:232: characters 147-151 : Class<PlayState> has no field SONG
source/editors/EditorPlayState.hx:97: characters 26-30 : Class<PlayState> has no field SONG
source/editors/EditorLua.hx:70: characters 24-28 : Class<PlayState> has no field SONG
source/editors/EditorLua.hx:71: characters 32-36 : Class<PlayState> has no field SONG
source/editors/EditorLua.hx:75: characters 29-33 : Class<PlayState> has no field SONG
source/editors/EditorPlayState.hx:139: characters 21-25 : Class<PlayState> has no field SONG
source/editors/EditorPlayState.hx:302: characters 59-63 : Class<PlayState> has no field SONG
source/editors/EditorPlayState.hx:320: characters 44-48 : Class<PlayState> has no field SONG
source/editors/EditorPlayState.hx:365: characters 22-34 : Class<PlayState> has no field isPixelStage
source/editors/EditorPlayState.hx:372: characters 39-43 : Class<PlayState> has no field SONG
source/editors/EditorPlayState.hx:408: characters 20-24 : Class<PlayState> has no field SONG
source/editors/EditorPlayState.hx:875: characters 16-20 : Class<PlayState> has no field SONG
source/editors/EditorPlayState.hx:875: characters 53-57 : Class<PlayState> has no field SONG
source/editors/EditorPlayState.hx:875: characters 98-102 : Class<PlayState> has no field SONG
source/editors/EditorPlayState.hx:712: characters 17-29 : Class<PlayState> has no field isPixelStage
source/editors/EditorPlayState.hx:737: characters 18-30 : Class<PlayState> has no field isPixelStage
source/editors/EditorPlayState.hx:746: characters 59-70 : Class<PlayState> has no field daPixelZoom
source/editors/EditorPlayState.hx:747: characters 63-74 : Class<PlayState> has no field daPixelZoom
source/editors/EditorPlayState.hx:770: characters 19-31 : Class<PlayState> has no field isPixelStage
source/editors/EditorPlayState.hx:777: characters 64-75 : Class<PlayState> has no field daPixelZoom
source/LoadingState.hx:68: characters 19-23 : Class<PlayState> has no field SONG
source/LoadingState.hx:140: characters 31-35 : Class<PlayState> has no field SONG
source/LoadingState.hx:70: characters 20-24 : Class<PlayState> has no field SONG
source/LoadingState.hx:145: characters 33-37 : Class<PlayState> has no field SONG
source/FunkinLua.hx:84: characters 24-28 : Class<PlayState> has no field SONG
source/FunkinLua.hx:85: characters 32-36 : Class<PlayState> has no field SONG
source/FunkinLua.hx:89: characters 29-33 : Class<PlayState> has no field SONG
source/FunkinLua.hx:92: characters 32-43 : Class<PlayState> has no field isStoryMode
source/FunkinLua.hx:93: characters 31-46 : Class<PlayState> has no field storyDifficulty
source/FunkinLua.hx:94: characters 28-37 : Class<PlayState> has no field storyWeek
source/FunkinLua.hx:95: characters 44-53 : Class<PlayState> has no field storyWeek
source/FunkinLua.hx:96: characters 33-45 : Class<PlayState> has no field seenCutscene
source/FunkinLua.hx:106: characters 28-36 : Class<PlayState> has no field instance
source/FunkinLua.hx:107: characters 28-36 : Class<PlayState> has no field instance
source/FunkinLua.hx:108: characters 28-36 : Class<PlayState> has no field instance
source/FunkinLua.hx:109: characters 28-36 : Class<PlayState> has no field instance
source/FunkinLua.hx:125: characters 28-41 : Class<PlayState> has no field cpuControlled
source/FunkinLua.hx:135: characters 40-44 : PlayState has no field BF_X
source/FunkinLua.hx:136: characters 40-44 : PlayState has no field BF_Y
source/FunkinLua.hx:137: characters 39-44 : PlayState has no field DAD_X
source/FunkinLua.hx:138: characters 39-44 : PlayState has no field DAD_Y
source/FunkinLua.hx:139: characters 41-45 : PlayState has no field GF_X
source/FunkinLua.hx:140: characters 41-45 : PlayState has no field GF_Y
source/FunkinLua.hx:1271: characters 16-30 : PlayState has no field addTextToDebug
source/FunkinLua.hx:307: characters 19-29 : PlayState has no field callOnLuas
source/FunkinLua.hx:320: characters 19-29 : PlayState has no field callOnLuas
source/FunkinLua.hx:333: characters 19-29 : PlayState has no field callOnLuas
source/FunkinLua.hx:346: characters 19-29 : PlayState has no field callOnLuas
source/FunkinLua.hx:359: characters 19-29 : PlayState has no field callOnLuas
source/FunkinLua.hx:376: characters 19-29 : PlayState has no field callOnLuas
source/FunkinLua.hx:388: characters 41-55 : PlayState has no field strumLineNotes
source/FunkinLua.hx:388: characters 83-97 : PlayState has no field strumLineNotes
source/FunkinLua.hx:393: characters 19-29 : PlayState has no field callOnLuas
source/FunkinLua.hx:402: characters 41-55 : PlayState has no field strumLineNotes
source/FunkinLua.hx:402: characters 83-97 : PlayState has no field strumLineNotes
source/FunkinLua.hx:407: characters 19-29 : PlayState has no field callOnLuas
source/FunkinLua.hx:416: characters 41-55 : PlayState has no field strumLineNotes
source/FunkinLua.hx:416: characters 83-97 : PlayState has no field strumLineNotes
source/FunkinLua.hx:421: characters 19-29 : PlayState has no field callOnLuas
source/FunkinLua.hx:430: characters 41-55 : PlayState has no field strumLineNotes
source/FunkinLua.hx:430: characters 83-97 : PlayState has no field strumLineNotes
source/FunkinLua.hx:435: characters 19-29 : PlayState has no field callOnLuas
source/FunkinLua.hx:452: characters 17-27 : PlayState has no field callOnLuas
source/FunkinLua.hx:452: characters 54-63 : Arrays of mixed types are only allowed if the type is forced to Array<Dynamic>
source/FunkinLua.hx:452: characters 54-63 : Int should be String
source/FunkinLua.hx:494: characters 16-25 : PlayState has no field songScore
source/FunkinLua.hx:494: characters 16-25 : PlayState has no field songScore
source/FunkinLua.hx:495: characters 16-33 : PlayState has no field RecalculateRating
source/FunkinLua.hx:498: characters 16-26 : PlayState has no field songMisses
source/FunkinLua.hx:498: characters 16-26 : PlayState has no field songMisses
source/FunkinLua.hx:499: characters 16-33 : PlayState has no field RecalculateRating
source/FunkinLua.hx:502: characters 16-24 : PlayState has no field songHits
source/FunkinLua.hx:502: characters 16-24 : PlayState has no field songHits
source/FunkinLua.hx:503: characters 16-33 : PlayState has no field RecalculateRating
source/FunkinLua.hx:506: characters 16-25 : PlayState has no field songScore
source/FunkinLua.hx:507: characters 16-33 : PlayState has no field RecalculateRating
source/FunkinLua.hx:510: characters 16-26 : PlayState has no field songMisses
source/FunkinLua.hx:511: characters 16-33 : PlayState has no field RecalculateRating
source/FunkinLua.hx:514: characters 16-24 : PlayState has no field songHits
source/FunkinLua.hx:515: characters 16-33 : PlayState has no field RecalculateRating
source/FunkinLua.hx:525: characters 36-46 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:526: characters 36-46 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:527: characters 34-44 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:528: characters 37-47 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:529: characters 38-48 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:530: characters 36-46 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:531: characters 37-47 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:532: characters 37-47 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:539: characters 36-46 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:540: characters 36-46 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:541: characters 34-44 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:542: characters 37-47 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:549: characters 36-46 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:550: characters 36-46 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:551: characters 34-44 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:552: characters 37-47 : PlayState has no field getControl (Suggestion: get_controls)
source/FunkinLua.hx:562: characters 16-34 : PlayState has no field addCharacterToList
source/FunkinLua.hx:573: characters 16-32 : PlayState has no field triggerEventNote
source/FunkinLua.hx:578: characters 16-30 : PlayState has no field startCountdown
source/FunkinLua.hx:581: characters 16-25 : PlayState has no field KillNotes
source/FunkinLua.hx:582: characters 16-23 : PlayState has no field endSong
source/FunkinLua.hx:591: characters 25-33 : PlayState has no field dadGroup
source/FunkinLua.hx:593: characters 25-32 : PlayState has no field gfGroup
source/FunkinLua.hx:595: characters 25-39 : PlayState has no field boyfriendGroup
source/FunkinLua.hx:601: characters 18-26 : PlayState has no field dadGroup
source/FunkinLua.hx:603: characters 18-25 : PlayState has no field gfGroup
source/FunkinLua.hx:605: characters 18-32 : PlayState has no field boyfriendGroup
source/FunkinLua.hx:611: characters 25-33 : PlayState has no field dadGroup
source/FunkinLua.hx:613: characters 25-32 : PlayState has no field gfGroup
source/FunkinLua.hx:615: characters 25-39 : PlayState has no field boyfriendGroup
source/FunkinLua.hx:621: characters 18-26 : PlayState has no field dadGroup
source/FunkinLua.hx:623: characters 18-25 : PlayState has no field gfGroup
source/FunkinLua.hx:625: characters 18-32 : PlayState has no field boyfriendGroup
source/FunkinLua.hx:633: characters 16-26 : PlayState has no field moveCamera
source/FunkinLua.hx:1259: characters 46-52 : PlayState has no field camHUD
source/FunkinLua.hx:1260: characters 50-58 : PlayState has no field camOther
source/FunkinLua.hx:1262: characters 22-29 : PlayState has no field camGame
source/FunkinLua.hx:639: characters 16-29 : PlayState has no field ratingPercent
source/FunkinLua.hx:642: characters 16-28 : PlayState has no field ratingString
source/FunkinLua.hx:655: characters 21-24 : PlayState has no field dad
source/FunkinLua.hx:656: characters 19-22 : PlayState has no field dad
source/FunkinLua.hx:658: characters 21-23 : PlayState has no field gf
source/FunkinLua.hx:659: characters 19-21 : PlayState has no field gf
source/FunkinLua.hx:661: characters 21-30 : PlayState has no field boyfriend
source/FunkinLua.hx:662: characters 19-28 : PlayState has no field boyfriend
source/FunkinLua.hx:667: characters 29-32 : PlayState has no field dad
source/FunkinLua.hx:668: characters 43-45 : PlayState has no field gf
source/FunkinLua.hx:669: characters 26-35 : PlayState has no field boyfriend
source/FunkinLua.hx:779: characters 66-73 : PlayState has no field gfGroup
source/FunkinLua.hx:780: characters 50-64 : PlayState has no field boyfriendGroup
source/FunkinLua.hx:781: characters 59-73 : PlayState has no field boyfriendGroup
source/FunkinLua.hx:782: characters 57-65 : PlayState has no field dadGroup
source/FunkinLua.hx:783: characters 59-67 : PlayState has no field dadGroup
source/FunkinLua.hx:887: characters 70-74 : Class<PlayState> has no field SONG
source/FunkinLua.hx:893: characters 18-31 : PlayState has no field startDialogue
source/FunkinLua.hx:900: characters 20-30 : PlayState has no field endingSong
source/FunkinLua.hx:901: characters 18-25 : PlayState has no field endSong
source/FunkinLua.hx:903: characters 18-32 : PlayState has no field startCountdown
source/FunkinLua.hx:910: characters 17-27 : PlayState has no field startVideo
source/FunkinLua.hx:934: characters 18-28 : PlayState has no field callOnLuas
source/FunkinLua.hx:934: characters 18-28 : PlayState has no field callOnLuas
source/FunkinLua.hx:934: characters 18-28 : PlayState has no field callOnLuas
source/FunkinLua.hx:1356: characters 15-24 : PlayState has no field removeLua
source/FunkinLua.hx:1362: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1362: characters 48-56 : Class<PlayState> has no field instance
source/FunkinLua.hx:1363: characters 14-22 : Class<PlayState> has no field instance
source/FunkinLua.hx:1363: characters 49-57 : Class<PlayState> has no field instance
source/WeekData.hx:172: characters 30-39 : Class<PlayState> has no field storyWeek
source/WeekData.hx:177: characters 46-55 : Class<PlayState> has no field storyWeek
source/CoolUtil.hx:92: characters 19-32 : Class<PlayState> has no field maniaToChange
source/CoolUtil.hx:94: characters 24-37 : Class<PlayState> has no field maniaToChange
source/CoolUtil.hx:143: characters 20-33 : Class<PlayState> has no field maniaToChange
source/CoolUtil.hx:145: characters 25-38 : Class<PlayState> has no field maniaToChange
source/FreeplayState.hx:330: characters 13-28 : Class<PlayState> has no field storyDifficulty
source/FreeplayState.hx:256: characters 14-18 : Class<PlayState> has no field SONG
source/FreeplayState.hx:257: characters 18-22 : Class<PlayState> has no field SONG
source/FreeplayState.hx:258: characters 65-69 : Class<PlayState> has no field SONG
source/FreeplayState.hx:263: characters 46-50 : Class<PlayState> has no field SONG
source/FreeplayState.hx:285: characters 14-18 : Class<PlayState> has no field SONG
source/FreeplayState.hx:286: characters 14-25 : Class<PlayState> has no field isStoryMode
source/FreeplayState.hx:287: characters 14-29 : Class<PlayState> has no field storyDifficulty
source/FreeplayState.hx:289: characters 14-23 : Class<PlayState> has no field storyWeek
source/StoryMenuState.hx:284: characters 14-27 : Class<PlayState> has no field storyPlaylist
source/StoryMenuState.hx:285: characters 14-25 : Class<PlayState> has no field isStoryMode
source/StoryMenuState.hx:291: characters 14-29 : Class<PlayState> has no field storyDifficulty
source/StoryMenuState.hx:293: characters 14-18 : Class<PlayState> has no field SONG
source/StoryMenuState.hx:293: characters 49-62 : Class<PlayState> has no field storyPlaylist
source/StoryMenuState.hx:293: characters 100-113 : Class<PlayState> has no field storyPlaylist
source/StoryMenuState.hx:294: characters 14-23 : Class<PlayState> has no field storyWeek
source/StoryMenuState.hx:295: characters 14-27 : Class<PlayState> has no field campaignScore
source/StoryMenuState.hx:296: characters 14-28 : Class<PlayState> has no field campaignMisses`

**Comment by frantastic24** [comment]
Did you add the code or did you just replace the entirety of Playstate

**Comment by DybaTubeYT1** [comment]
Added the code

Em seg, 17 de jan de 2022 3:55 PM, frantastic24 ***@***.***>
escreveu:

**Comment by DybaTubeYT1** [comment]
Oh shit shadowmario was here
