### ISSUE TITLE
How can I change the default zoom on a mustHitSection?

### ISSUE THREAD

**Issue by NesDoesGithub** [ShadowMario/FNF-PsychEngine#3686]
### Describe your problem here.

I am trying to change the defaultZoom mid song during a mustHitSection like the attached gif.

This is my code. (The rest of the code is out of frame on the picture)
![fdsdfhfdsiufh](https://user-images.githubusercontent.com/95316430/149806256-14356f5f-6649-47f2-bfec-08929bbe9afc.png)

This is what I am trying to make in Psych Engine.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/95316430/149806279-a3ff2579-6bc1-41ed-b34d-49ec34be95ed.gif)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by frantastic24** [comment]
```
function on update()

if mustHitSection == true then
     setProperty('defaultCamZoom', 0.9);
else
     setProperty('defaultCamZoom', x); -- put the zoom for the opponent here
```

**Comment by NesDoesGithub** [comment]
> ```
> function onUpdate()
> 
>      if mustHitSection == true then
>           setProperty('defaultCamZoom', 0.9);
>      else
>           setProperty('defaultCamZoom', x); -- put the zoom for the opponent here
>      end
> end
> ```

thx
