### ISSUE TITLE
Mods >Stages Folder 

### ISSUE THREAD

**Issue by MarquisArtuis** [ShadowMario/FNF-PsychEngine#3689]
### What feature do you want to get added on the **base** engine?

I don't like how disorganized and messy things can get by just dropping the images into the mods images folder.
Adding a Stage Folder and another Folder with the stages assets inside, would be a nice update.

A stages folder in mods to make things more organized. A kin to Leather Engine

Leather Engine Example 1
![stages organized within a folder within leather engine](https://user-images.githubusercontent.com/87309091/149820925-eb499d24-3da8-4ec9-9d9d-02dc21ec42e2.png)

Leather Engine Example 2
![stage folder like within leather engine](https://user-images.githubusercontent.com/87309091/149820897-c8b34c40-3ebd-4203-a679-cea5f2ab02e8.png)

How Psych Engine Handle
![Mods Stages Images folder request](https://user-images.githubusercontent.com/87309091/149819967-04530c31-779a-4720-8998-77039c7b1582.png)

To elaborate further i am stating that i would like to see a stages folder or have a directory that reads a "stages" folder in images to make it more organized.

as we know from a previous screenshot the normal way to add stages in psych engine is fine and convenient and works. however, my complaint is that it would be good to see the stages assets be read within a stages folder without hard coding if its possible, if not then thats fine but ye 
.
What happens Normally when adding stage assets (without stages folder)
l![what happens normally](https://user-images.githubusercontent.com/87309091/149827783-3a86991b-436b-438b-9536-a2966e646975.png)

What happens when i add my own stages folder
![what happens when i add my own stages folder](https://user-images.githubusercontent.com/87309091/149827979-e2d44676-5c33-4ccd-ae28-d9ae7431447d.png)

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by frantastic24** [comment]
Or just make Stages folder in images, it's not that hard
You also failed the test

**Comment by MarquisArtuis** [comment]
> Or just make Stages folder in images, it's not that hard You also failed the test

what test?

**Comment by frantastic24** [comment]
![Screenshot_2022-01-17-15-52-27-317.jpg](https://user-images.githubusercontent.com/95725102/149824028-52fd6dd2-7a27-4721-9588-f3221c052323.jpg)

**Comment by MarquisArtuis** [comment]
> ![Screenshot_2022-01-17-15-52-27-317.jpg](https://user-images.githubusercontent.com/95725102/149824028-52fd6dd2-7a27-4721-9588-f3221c052323.jpg)

To be fair adding a stage folder in images does not work when loading stages in the chart editor for the newest psych engine

**Comment by frantastic24** [comment]
I have a separate folder in /images for stages and never had any issues so idk what you're doing

**Comment by BombasticTom** [comment]
I have a way better idea
How about having a stages folder, and to separate stages, you separate them by folders
(ignore nevada files, i was just testing something)
![image](https://user-images.githubusercontent.com/85838311/149827534-8a8b747b-1717-4088-92aa-ad21ddc004fc.png)
And inside of the folder of your stage, there could be images (where you store images duh), stage lua and json files, and pack.json
![image](https://user-images.githubusercontent.com/85838311/149827799-5485fd2f-c014-4ac2-89c8-0a9b99c15c81.png)
Now why would we need pack.json?
pack.json could contain stage name, and file names (names of files to read in order to implement lua and json code)
![image](https://user-images.githubusercontent.com/85838311/149827953-98117fbe-239b-49ae-94cb-638f4b22e691.png)

**Comment by MarquisArtuis** [comment]
> I have a way better idea How about having a stages folder, and to separate stages, you separate them by folders (ignore nevada files, i was just testing something) ![image](https://user-images.githubusercontent.com/85838311/149827534-8a8b747b-1717-4088-92aa-ad21ddc004fc.png) And inside of the folder of your stage, there could be images (where you store images duh), stage lua and json files, and pack.json ![image](https://user-images.githubusercontent.com/85838311/149827799-5485fd2f-c014-4ac2-89c8-0a9b99c15c81.png) Now why would we need pack.json? pack.json could contain stage name, and file names (names of files to read in order to implement lua and json code) ![image](https://user-images.githubusercontent.com/85838311/149827953-98117fbe-239b-49ae-94cb-638f4b22e691.png)

this is an interesting solution did you get it to work cause i didnt

**Comment by BombasticTom** [comment]
i didn't make it work this is just a concept

**Comment by tposejank** [comment]
dude just do makeLuaSprite('tag', 'folderInModsImages/imageInFolder' its that easy

**Comment by MarquisArtuis** [comment]
> ik but still it's a cool little concept i made

it didn't work for me

**Comment by BombasticTom** [comment]
because I didn't make it work it's just a little idea I had for actual devs to make it

**Comment by anonybean** [comment]
that's what I've been thinking about it for like 2 month idk
