### ISSUE TITLE
Missing Notes In Wrong Spot?

### ISSUE THREAD

**Issue by WebsiteDude64** [ShadowMario/FNF-PsychEngine#3693]
### Describe your bug here.

Using a custom event to move notes around, I tried moving them above the top of the screen, but when the notes go past the area where the notes are originally, it counts the miss way earlier than it should, and I can't hit the notes afterwards. (video 1 is me trying to press notes, 2 is botplay.)

https://user-images.githubusercontent.com/85528982/149840180-3c9145c1-afda-48ea-99db-b393676d2224.mp4

https://user-images.githubusercontent.com/85528982/149840296-616fa3aa-4490-4e08-a556-57f21bd1dd76.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by perngjiafu** [comment]
cause the part when the note is destroyed aka. the missing area, is not moved. moving event doesnt move that
