### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by thedeveloper112206** [ShadowMario/FNF-PsychEngine#3699]
### What feature do you want to get added on the **base** engine?

i think playable characters would be cool to see added. plus it would also help with modders who dont know how to add playable characters

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
this was already declined, they're not hard to add anyways

**Comment by HiroMizuki** [comment]
we don't want it here
