### ISSUE TITLE
Lua Question

### ISSUE THREAD

**Issue by Luciano686** [ShadowMario/FNF-PsychEngine#3700]
### What is your question?

Hi, im making a mod, and i wanna make a custom note that when you press it, your strums disable for 3 seconds, how can i make that? thanks

**Comment by BoloVEVO** [comment]
You can set safe frames to 0 making notes impossible to hit and set strums alpha to 0.5 or smth.

**Comment by BoloVEVO** [comment]
You can use a timer to do this, so when the timer ends (3 seconds in your case) your safe frames will turn to normal and strums alpha is set to 1 again.
