### ISSUE TITLE
public function new

### ISSUE THREAD

**Issue by BlazeGod88** [ShadowMario/FNF-PsychEngine#3704]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/96097475/149854467-caf70f08-784b-4515-8853-b82de3ff9c08.png)
i do not know how to fix it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i changed some things to do a note but that is all

**Comment by BeansCool54** [comment]
There's an unexpected bracket up there maybe?
