### ISSUE TITLE
How to make a cutscene after the last song? 

### ISSUE THREAD

**Issue by anonybean** [ShadowMario/FNF-PsychEngine#3708]
### Describe your problem here.

I really want to make an ending cutscene but I can't add one. If you know how to do that please tell me how. Or, if that is possible by just using a script.Lua file, 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Ninjatintin** [comment]
maybe do the same thing you do in onStartCountdown() but with onEndSong() instead

**Comment by anonybean** [comment]
oh ok thx
