### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by Wither362** [ShadowMario/FNF-PsychEngine#3712]
### What needs to be documented?

This is for the `Readme.md` archive

You didn’t say how to do the `lime test` thing!

I think it would be better if where it says what to install you write: **and when you have all that installed you do:**

- `lime test windows` if you are in windows,
- `lime test mac` if you are in mac
- `lime test linux` if you are in linux

Please, do this for new people please

**Comment by tposejank** [comment]
![image](https://user-images.githubusercontent.com/81495861/149948700-10b705b3-930a-485b-b885-1cf524b29aff.png)
This is redundant, I guess.

**Comment by Wither362** [comment]
Ah, ok, in that case
