### ISSUE TITLE
How do I add shaders in Lua

### ISSUE THREAD

**Issue by Ninjatintin** [ShadowMario/FNF-PsychEngine#3718]
### Describe your problem here.

I want to replicate this (note: this piece of code is pulled out of the VS Dave & Bambi Source Code)
`sprites.add(bg);`
`add(bg);`
`var testshader:Shaders.GlitchEffect = new Shaders.GlitchEffect();`
`testshader.waveAmplitude = 0.1;`
`testshader.waveFrequency = 5;`
`testshader.waveSpeed = 2;`
`bg.shader = testshader.shader;`
`curbg = bg;`
In Lua

Note: Before you say to change something in the source code, I'm trying to do this WITHOUT editing the source code.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

how am i supposed to edit anything in the build if im not using the source code

**Comment by frantastic24** [comment]
Get a source code build from Actions and use `addGlitchEffect('your camera here')`, you can see more variables you can set in FunkinLua.hx

**Comment by mayo78** [comment]
you grabbed code from a completely different programming language? why?

**Comment by frantastic24** [comment]
> you grabbed code from a completely different programming language? why?

For reference

**Comment by ByronisJoan** [comment]
If You are On Lua And On the Latest Update

Copy and Paste This Under function onCreate()

copy and Paste this to the
function onCreatePost()
addGlitchEffect('name', 2, 2);
end

**Comment by Ninjatintin** [comment]
> Get a source code build from Actions and use `addGlitchEffect('your camera here')`, you can see more variables you can set in FunkinLua.hx

does it also work with just lua sprites

**Comment by frantastic24** [comment]
Yes

**Comment by Ninjatintin** [comment]
> If You are On Lua And On the Latest Update
> 
> Copy and Paste This Under function onCreate()
> 
> copy and Paste this to the function onCreatePost() addGlitchEffect('name', 2, 2); end

im on the latest version and it still doesn't work

**Comment by frantastic24** [comment]
Show the code, and make sure you're on the latest _source_ build and not using a build from Releases
