### ISSUE TITLE
Song stops at 2:47 

### ISSUE THREAD

**Issue by Joejioboi** [ShadowMario/FNF-PsychEngine#3724]
### Describe your bug here.

Pretty self explanatory, my song always stops at 2:47 and I don’t know why, it’s a 4 minute song btw

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope nothing at all

**Comment by ItsCapp** [comment]
what file is the song?
if it's any other `.ogg` it won't work

**Comment by Joejioboi** [comment]
> what file is the song?
> if it's any other `.ogg` it won't work

It is a .ogg file, the file is 4 minutes long but the game just stops the song at 2:47

**Comment by frantastic24** [comment]
what do you mean by "stops"? does it boot you back to the menu? crash? just stop playing the song? give as many details as possible when reporting a bug

**Comment by Joejioboi** [comment]
> what do you mean by "stops"? does it boot you back to the menu? crash? just stop playing the song? give as many details as possible when reporting a bug
Yea it just stops the song and I have no idea why, at first I thought it was because I accidentally made the Inst file too short but no it just stops the song and even when I'm charting it.

**Comment by frantastic24** [comment]
have you tried just listening to it with a media player and see if it's fine? tried it on another engine? maybe a memory issue? and if you don't mind you could send the file and i could test it, i've used triple trouble and it never had any issues
