### ISSUE TITLE
Title screen and week screen changes

### ISSUE THREAD

**Issue by facundomax** [ShadowMario/FNF-PsychEngine#3727]
### Describe your problem here.

 1.In the title screen, how do I put a cinematic before the logo starts (something like friday night fever)

 2. on the screen where gf appears, how do I place 3 more sprites and remove the gf?

 3.On the weeks screen, how do I change the position of the letters, instead of being at the bottom I put them up to the left (the same with that wide black background, but instead of width I would like to make it high in the same location where I want to put the name of the week, I think you understand me).

 I have the source of psych so they can answer complex but understandable things

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i don't edit this biuld

**Comment by zLightc** [comment]
making custom menu and week stuff (i.e title, menu, transitions)
i think in the _MainMenuState.hx_ and _TitleState.hx_

here is a tutorial about the main menu (ex. story mode, options etc) : **_https://www.youtube.com/watch?v=eTC8lv19m_o_**
and this is about a custom story mode/week screen : **_https://www.youtube.com/watch?v=k9LPGIeLWcE_**
i also found this : **_https://www.youtube.com/watch?v=aTNKkCAJiDg_**

I hope this helps!

Cheers!

**_~zLightc_**

**Comment by facundomax** [comment]
thank you very much, this helped me a lot
