### ISSUE TITLE
Soft-coded/Detectable Alt Music 

### ISSUE THREAD

**Issue by AdrianCD5** [ShadowMario/FNF-PsychEngine#3730]
### What feature do you want to get added on the **base** engine?

This one's a little hard to explain, but I wanted the ability to soft-code remixes that **don't require a separate song**, but are rather **a difficulty selected in Freeplay** (or the week itself!) Examples of this come down to EX in BNB, ALT in Martian Mixtape and Erect remixes in the upcoming base game.
How I thought this could be implemented is for any custom difficulties (for this example Erect), the engine would load the voices/inst files by first searching for "Voices-Erect" and "Inst-Erect", and if those files come up Null (i.e in a situation where only the chart is changed), then default to "Voices" and "Inst". This would be a really nice feature to have so that creating Remix difficulties for mods can be a lot easier and even soft-coded in lua mod-packs.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tposejank** [comment]
change "song": in json

**Comment by AdrianCD5** [comment]
> change "song": in json
While this is a good workaround, it's still technically loading a seperate song and therefore the high score won't be saved properly.

**Comment by Fablisothebottle** [comment]
> change "song": in json

uh.. i tried that and the chart just looped on its first note.

**Comment by ShadowMario** [comment]
I will fix the Highscore issue, but i don't plan in adding Alt songs.
