### ISSUE TITLE
My script does not work

### ISSUE THREAD

**Issue by MarkToonsHD** [ShadowMario/FNF-PsychEngine#3732]
### Describe your problem here.

I've been trying to make a script that'll change the arrow skin for a certain song, but it just doesn't work. It looks like this:
![image](https://user-images.githubusercontent.com/77655973/150044673-5a2ab0c8-b2ce-4478-b4ae-577397b1bf30.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Added erect remixes to the songs & data folder and shit

**Comment by MarkToonsHD** [comment]
UPDATE:
I replaced `onCreate()` with `onUpdate` . It works, but the static notes did not change.

**Comment by frantastic24** [comment]
static notes are `playerStrums` and `opponentStrums`

**Comment by frantastic24** [comment]
You may also want to use `onStepHit()` instead of `onUpdate()`

**Comment by MayoALT** [comment]
also remove the else part its not needed

**Comment by MarkToonsHD** [comment]
> function onUpdate(elasped)
>         if curStep >= 1024
> 	        for i=0,7 do
> 		        setPropertyFromGroup('StrumLineNotes', i, 'texture', 'GUITAR_HERO_NOTES') -- StrumLine 
> 			setPropertyFromGroup('unspawnNotes', i, 'texture', 'GUITAR_HERO_NOTES') -- Notes to be hit
> 	        end
>         end
> end
crashes the game lol

**Comment by Stilic** [comment]
> > function onUpdate(elasped)
> > if curStep >= 1024
> > for i=0,7 do
> > setPropertyFromGroup('StrumLineNotes', i, 'texture', 'GUITAR_HERO_NOTES') -- StrumLine
> > setPropertyFromGroup('unspawnNotes', i, 'texture', 'GUITAR_HERO_NOTES') -- Notes to be hit
> > end
> > end
> > end
> 
> This crashes the game

It's because you don't changed the textures paths.

**Comment by MarkToonsHD** [comment]
> You may also want to use `onStepHit()` instead of `onUpdate()`

This didn't work
![image](https://user-images.githubusercontent.com/77655973/150290457-d7920324-1c16-4a4a-8d90-fcb57e85a050.png)

**Comment by MarkToonsHD** [comment]
> > > function onUpdate(elasped)
> > > if curStep >= 1024
> > > for i=0,7 do
> > > setPropertyFromGroup('StrumLineNotes', i, 'texture', 'GUITAR_HERO_NOTES') -- StrumLine
> > > setPropertyFromGroup('unspawnNotes', i, 'texture', 'GUITAR_HERO_NOTES') -- Notes to be hit
> > > end
> > > end
> > > end
> > 
> > 
> > This crashes the game
> 
> It's because you don't changed the textures paths.

Should it be 'images/GUITAR_HERO_NOTES' (because i put the guitar hero notes in images) or smth?

**Comment by frantastic24** [comment]
> > You may also want to use `onStepHit()` instead of `onUpdate()`
> 
> This didn't work ![image](https://user-images.githubusercontent.com/77655973/150290551-d88ec3cf-ccd5-4791-b10a-008274062bc3.png)

Because you're using `note.length` with opponentStrums

**Comment by NesDoesGithub** [comment]
> > > function onUpdate(elasped)
> > > if curStep >= 1024
> > > for i=0,7 do
> > > setPropertyFromGroup('StrumLineNotes', i, 'texture', 'GUITAR_HERO_NOTES') -- StrumLine
> > > setPropertyFromGroup('unspawnNotes', i, 'texture', 'GUITAR_HERO_NOTES') -- Notes to be hit
> > > end
> > > end
> > > end
> > 
> > 
> > This crashes the game
> 
> It's because you don't changed the textures paths.

no it crashes the game bc of "StrumLineNotes"

**Comment by MarkToonsHD** [comment]
Okay it works, thanks guys.
