### ISSUE TITLE
when i select a week in every fnf i download, the first not goes and game crashes

### ISSUE THREAD

**Issue by BitchL** [ShadowMario/FNF-PsychEngine#3743]
### Describe your bug here.

how can i fix that??

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

a

**Comment by ItsCapp** [comment]
needs a bit more information

**Comment by MayoALT** [comment]
me when the first not goes 
![image](https://user-images.githubusercontent.com/94536972/150182321-2424fa28-9640-4a5a-8089-9bded892e940.png)

**Comment by frantastic24** [comment]
Get a better PC
