### ISSUE TITLE
Code Input

### ISSUE THREAD

**Issue by KyleOliverDeveloper** [ShadowMario/FNF-PsychEngine#3746]
### What is your question?

So, i am working for a mod and i want to see if someone could help me out!

So, basically i want to make a input bar (like those roblox promocodes thingy) that would unlock a specific week, but idk how to do that. If someone could help me i would me more than grateful! Also, the weeks unlock with the code 1987.

I code with .LUA. If i get a source code response, i will ignore it since it is useless to me.
![astrobgfront](https://user-images.githubusercontent.com/94708825/150198168-3f067a67-9f27-455e-96a2-3dc69a6e879b.png)

**Comment by frantastic24** [comment]
You can't use Lua outside of songs so an input prompt might not be a good idea, what you could do instead is just have a global (or song-specific) script that checks if the right keys are pressed
`getPropertyFromClass('flixel.FlxG', 'keys.justPressed.INSERTKEYNAMEHERE')`
