### ISSUE TITLE
code

### ISSUE THREAD

**Issue by adadadaaa** [ShadowMario/FNF-PsychEngine#3750]
### Describe your bug here.

i try ed to bulid the engine but this code says it wong
64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths 
what did i do wong??

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by perngjiafu** [comment]
[here](https://community.haxe.org/t/how-to-fix-error-set-hxcpp-msvc-custom-manually/2934
)
