### ISSUE TITLE
Adding Early Custom Note Trigger

### ISSUE THREAD

**Issue by LeanDapper** [ShadowMario/FNF-PsychEngine#3751]
### What is your question?

I wanted to see if you guys could implement a early custom note trigger to both haxe and lua.

It could help make animations play automatically early so it syncs (ex: unknown suffering mickeys throw animation before the note and boyfriend dodging on the note position)

this is just so you dont have to constantly put event notes to play animations in the chart so you can just place one note and then the rest would be handled by the notes coding.

i hope yall consider adding this because it would be really helpful!!

**Comment by ShadowMario** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/44785097/151066866-d61f4126-754f-4032-a798-307c43cee33f.png)
![Screenshot_6](https://user-images.githubusercontent.com/44785097/151066788-e8954bc9-415a-4bbb-b8b1-714ebac0fbdd.png)
Dude.
