### ISSUE TITLE
VCR effects crash the game

### ISSUE THREAD

**Issue by ZackOui** [ShadowMario/FNF-PsychEngine#3752]
### Describe your problem here.

I was gonna add VCR effect until it crashes the game when I play a song.

And in the terminal logs, it shows a shitty ass error that is so long I can't show the rest of it.
<img width="904" alt="Screen Shot 2022-01-19 at 4 08 44 PM" src="https://user-images.githubusercontent.com/92494313/150238736-76d0daec-ff5e-4a4a-8e58-8307b9abd243.png">

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

I made a script to make a VCR effect in Thorns because I thought it was cool.

**Comment by tposejank** [comment]
some shaders dont work on some platforms.

I dont really know what the issue is but it might be openfl being a dumbass

**Comment by ZackOui** [comment]
thanks a lot!
