### ISSUE TITLE
How do you put the dialogs with code at the beginning and at the end?

### ISSUE THREAD

**Issue by LeorDillex** [ShadowMario/FNF-PsychEngine#3756]
### Describe your problem here.

I know how to do this with scripts, but I want to do it in a more professional way and it would be very helpful if you could explain me how to do both with code.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing related to this

**Comment by zLightc** [comment]
Read **this**[](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Dialogues)
