### ISSUE TITLE
Event Notes aren't effected by note delay

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#376]
I am not sure if this is a bug, but I wanted to make an event to happen at a note.

![Screenshot (99)](https://user-images.githubusercontent.com/87707926/137470059-b8f3abb4-9696-4da4-942a-ee79bb0a4c38.png)

The event happens earlier and I guess it's because I play with a 150ms note delay.
Is there something I can do?

**Comment by ShadowMario** [comment]
Fixed on last build
