### ISSUE TITLE
Better Transitions?

### ISSUE THREAD

**Issue by MaxlionButMyNameIsTakenSoThisIsmyName** [ShadowMario/FNF-PsychEngine#3761]
### What feature do you want to get added on the **base** engine?

Make some better transitions between states, Most of them are already pretty good but when pressing escape in the menus the current transition is just plain boring. Mostly just a preference thing n if you'd like to keep the engine simple then you can.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tposejank** [comment]
no

**Comment by HiroMizuki** [comment]
no
