### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Swarmed2674** [ShadowMario/FNF-PsychEngine#3763]
### Describe your bug here.

can't compile html

### Command Prompt/Terminal logs (if existing)

```bash
source/animateatlas/AtlasFrameMaker.hx:80: characters 39-42 : Unknown identifier : paf
source/animateatlas/AtlasFrameMaker.hx:80: characters 39-42 : ... For function argument 'id'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by tposejank** [comment]
don't build to html

**Comment by THOBY555** [comment]
go to like the lube 50 where there`s somethings called `var name:shit;` something like that and type `var paf:FlxSprite;` idnoo if it a sprite or something , can i see the code from 75-85
