### ISSUE TITLE
Game crashes when selecting a mod in the Mods menu

### ISSUE THREAD

**Issue by SimoneStarace** [ShadowMario/FNF-PsychEngine#3764]
### Describe your bug here.

I was making a simple mod and I have found a bug that closes the game each time I only select, not even enabling, a mod that has the `"restart":true` set in the _pack.json_ file.

Taking in count the [Holiday Mods](https://gamebanana.com/mods/344364) as a test for show this bug, I have putted the mods inside the _mods_ folder. When I select my mod, which it' doesn't have anything inside, nothing happens and the game returns to the main menu, but when I select one of the Holiday mods the game doesn't return to the main, remains in a black screen and then crashes like in the following gif:
![Crash](https://user-images.githubusercontent.com/52276600/150348997-6bc2f6b2-8d91-40e1-9fb7-99e009ec76ca.gif)
 
I have checked the error message and the problem happens specifically in this line of code https://github.com/ShadowMario/FNF-PsychEngine/blob/23d16e82a75fcd8fd045b12f6cd0e56f7fd9e621/source/Alphabet.hx#L376 The game seems not be able to find the characters of the alphabet to be displayed correctly.

I hope all I have written is clear.

### Command Prompt/Terminal logs (if existing)

```bash
source/Discord.hx:17: Discord Client starting...
source/Discord.hx:67: Discord Client initialized
source/Discord.hx:24: Discord Client started.
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 25
Called from ApplicationMain::create ApplicationMain.hx line 130
Called from lime.app.Application::exec lime/app/Application.hx line 150
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 146
Called from lime._internal.backend.native.NativeApplication::handleRenderEvent lime/_internal/backend/native/NativeApplication.hx line 370
Called from lime.app._Event_lime_graphics_RenderContext_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from openfl.display.Stage::__onLimeRender openfl/display/Stage.hx line 1950
Called from openfl.display.Stage::__broadcastEvent openfl/display/Stage.hx line 1166
Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 1399
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 545
Called from flixel.FlxGame::step flixel/FlxGame.hx line 677
Called from flixel.FlxGame::update flixel/FlxGame.hx line 747
Called from flixel.FlxState::tryUpdate flixel/FlxState.hx line 202
Called from TitleState::update TitleState.hx line 524
Called from MusicBeatState::update MusicBeatState.hx line 82
Called from MusicBeatState::stepHit MusicBeatState.hx line 177
Called from TitleState::beatHit TitleState.hx line 585
Called from TitleState::createCoolText TitleState.hx line 531
Called from Alphabet::new Alphabet.hx line 68
Called from Alphabet::addText Alphabet.hx line 148
Called from AlphaCharacter::new Alphabet.hx line 375
Called from flixel.graphics.frames.FlxAtlasFrames::fromSparrow flixel/graphics/frames/FlxAtlasFrames.hx line 238
Called from flixel.graphics.frames.FlxAtlasFrames::findFrame flixel/graphics/frames/FlxAtlasFrames.hx line 399
Critical Error: Uncatchable Throw: Null Object Reference
Segmentation fault
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

I haven't changed a single line of code.

**Comment by tposejank** [comment]
"Segmentation fault" probably your pc shitting itself.

**Comment by SimoneStarace** [comment]
> "Segmentation fault" probably your pc shitting itself.

It's very strange imo. It only happens on mods that have the restart option enabled.
