### ISSUE TITLE
a new lua stuff

### ISSUE THREAD

**Issue by zLightc** [ShadowMario/FNF-PsychEngine#3766]
### What feature do you want to get added on the **base** engine?

**hey there whoever is reading! I would like from you to add a simple variable called showOnlyStrums to the lua song script. if you don't know what it means, it means that if this var is true, then it will hide everything except for the strum notes.**

cheers!
**_-zLightc_**

### To test your sight, and reliability, please select the option of what should NOT be requested.

6k and stage EDITOR PLEASE STOP ASKIJKASJDKLSAJDKLSA JKLDAS

**Comment by BoloVEVO** [comment]
I think it's unnecesary cuz you can set health bar, score, and timer alpha to 0 and have only the strums.

**Comment by zLightc** [comment]
do you know how? + its a nice shortcut

**Comment by MayoALT** [comment]
`setProperty('object.visible', false)`

**Comment by ShadowMario** [comment]
Already possible to hide strums in lua, i won't add a lua variable similar to how Kade Engine modcharts do it due to how different Psych Lua works.
