### ISSUE TITLE
tween angle issue!

### ISSUE THREAD

**Issue by zLightc** [ShadowMario/FNF-PsychEngine#3773]
### Describe your problem here.

Hi, ive found a problem while making my **LUA script:**
![psych issue](https://user-images.githubusercontent.com/96623600/150387349-ea0bd2e4-874a-42fa-8d95-5ee5b04d4be1.PNG)
when I run it it repeats rotating the HUD around and idk how to fix this

cheers!
**_~zLightc_**

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope cuz im not using source

**Comment by ItsCapp** [comment]
why don't you use this?
#1452
it's a custom event I made that rotates the camera
I've added an "only rotate camera" and "only rotate HUD" to it too.
have fun :3

**Comment by zLightc** [comment]
well i fixed the problem but thanks ill try it anyway!

**Comment by frantastic24** [comment]
Then close this

**Comment by zLightc** [comment]
oh yea
