### ISSUE TITLE
I need help with building again

### ISSUE THREAD

**Issue by RedMik52** [ShadowMario/FNF-PsychEngine#3774]
### Describe your problem here.

I just downloaded the source code of version 0.5.1 and it keeps giving me this error:

source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:11: characters 8-37 : Type not found : flixel.util.FlxDirectionFlags
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:484: characters 21-25 : Unknown identifier : WALL
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:504: characters 21-25 : Unknown identifier : WALL
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:530: characters 21-28 : Unknown identifier : CEILING
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:550: characters 21-26 : Unknown identifier : FLOOR

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by jmxamongusmodder** [comment]
you need to download more stuff i bet

**Comment by SrtHero278** [comment]
If you're on haxe 4.1.5, update to the latest version. - > (https://haxe.org/download/)

**Comment by RedMik52** [comment]
thx @jmxamongusmodder and @SrtHero278
