### ISSUE TITLE
Is there any way to change the normal build to source code?

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#3777]
### Describe your problem here.

Is there any way to change the normal build to source code?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, mods folder and music

**Comment by MrClogsworthYT** [comment]
what... you should just download a normal source code and drop the mod folder contents in example_mods

**Comment by tposejank** [comment]
> what... you should just download a normal source code and drop the mod folder contents in example_mods
Hes asking to transfer an exe, default build to source code. Not a mod folder, which is yet not possible

**Comment by MrClogsworthYT** [comment]
> > what... you should just download a normal source code and drop the mod folder contents in example_mods
> 
> Hes asking to transfer an exe, default build to source code. Not a mod folder, which is yet not possible

bruh

**Comment by CheesecakeForever** [comment]
Nvm found out just copied the mod folders to the assets, thanks tho

**Comment by CheesecakeForever** [comment]
> > what... you should just download a normal source code and drop the mod folder contents in example_mods
> 
> Hes asking to transfer an exe, default build to source code. Not a mod folder, which is yet not possible

Hi thanks for nice reply I used your extra notes with credit
