### ISSUE TITLE
A Bug with the wiki

### ISSUE THREAD

**Issue by ArezalGame89** [ShadowMario/FNF-PsychEngine#3778]
### What needs to be documented?

If i could i would make a PR and fix this but i can't.
So you see in [HERE](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Variables#preferences-variables).
The `middlescroll` thing is still wroten as Downscroll. This should be `Middlescroll`

**Comment by Collabvmisgood** [comment]
Do you mean a mistype?

**Comment by ArezalGame89** [comment]
> Do you mean a mistype?

Yes

**Comment by PrismLight** [comment]
#4024
