### ISSUE TITLE
Is there portable Kade Engine to Psych Engine for Mod charts

### ISSUE THREAD

**Issue by afeefflox** [ShadowMario/FNF-PsychEngine#3797]
### What is your question?

:/ Idk i'm wondering about

**Comment by MrClogsworthYT** [comment]
maybe becuz a modchart is a lua file

**Comment by MrClogsworthYT** [comment]
nvm shadowmarioo said psych lua and kade lua works diffrent

**Comment by ShadowMario** [comment]
No.
