### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Trenton0** [ShadowMario/FNF-PsychEngine#3798]
### Describe your bug here.

was importing the note skin option from mind games (because yes) and it gave me this

source/options/BaseOptionsMenu.hx:61: characters 89-97 : Class<options.OptionsState> has no field desatNum

here code
`var bg:FlxSprite = new FlxSprite().loadGraphic(Paths.image('menuDesat' + OptionsState.desatNum));` 
sorry if am not explaining this clearly

### Command Prompt/Terminal logs (if existing)

```bash
source/options/BaseOptionsMenu.hx:61: characters 89-97 : Class<options.OptionsState> has no field desatNum
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

baseoptionsmenu: package options;  #if desktop import Discord.DiscordClient; #end import flash.text.TextField; import flixel.FlxG; import flixel.FlxSprite; import flixel.addons.display.FlxGridOverlay; import flixel.group.FlxGroup.FlxTypedGroup; import flixel.math.FlxMath; import flixel.text.FlxText; import flixel.util.FlxColor; import lime.utils.Assets; import flixel.FlxSubState; import flash.text.TextField; import flixel.FlxG; import flixel.FlxSprite; import flixel.util.FlxSave; import haxe.Json; import flixel.tweens.FlxEase; import flixel.tweens.FlxTween; import flixel.util.FlxTimer; import flixel.input.keyboard.FlxKey; import flixel.graphics.FlxGraphic; import Controls;  using StringTools;  class BaseOptionsMenu extends MusicBeatSubstate { 	private var curOption:Option = null; 	private var curSelected:Int = 0; 	private var optionsArray:Array<Option>;  	private var grpOptions:FlxTypedGroup<Alphabet>; 	private var checkboxGroup:FlxTypedGroup<CheckboxThingie>; 	private var grpTexts:FlxTypedGroup<AttachedText>;  	private var boyfriend:Character = null; 	private var previewNotes:AttachedSprite; 	private var descBox:FlxSprite; 	private var descText:FlxText; 	 	private var previewNoteOption:Option;  	public var title:String; 	public var rpcTitle:String;  	public function new() 	{ 		super();  		if(title == null) title = 'Options'; 		if(rpcTitle == null) rpcTitle = 'Options Menu'; 		 		#if desktop 		DiscordClient.changePresence(rpcTitle, null); 		#end 		 		var bg:FlxSprite = new FlxSprite().loadGraphic(Paths.image('menuDesat' + OptionsState.desatNum)); 		bg.color = 0xFFea71fd; 		bg.setGraphicSize(Std.int(bg.width * 1.1)); 		bg.updateHitbox(); 		bg.screenCenter(); 		bg.antialiasing = ClientPrefs.globalAntialiasing; 		add(bg);  		// avoids lagspikes while scrolling through menus! 		grpOptions = new FlxTypedGroup<Alphabet>(); 		add(grpOptions);  		grpTexts = new FlxTypedGroup<AttachedText>(); 		add(grpTexts);  		checkboxGroup = new FlxTypedGroup<CheckboxThingie>(); 		add(checkboxGroup);  		descBox = new FlxSprite().makeGraphic(1, 1, FlxColor.BLACK); 		descBox.alpha = 0.6; 		add(descBox);  		var titleText:Alphabet = new Alphabet(0, 0, title, true, false, 0, 0.6); 		titleText.x += 60; 		titleText.y += 40; 		titleText.alpha = 0.4; 		add(titleText);  		descText = new FlxText(50, 600, 1180, "", 32); 		descText.setFormat(Paths.font("vcr.ttf"), 32, FlxColor.WHITE, CENTER, FlxTextBorderStyle.OUTLINE, FlxColor.BLACK); 		descText.scrollFactor.set(); 		descText.borderSize = 2.4; 		add(descText);  		for (i in 0...optionsArray.length) 		{ 			var optionText:Alphabet = new Alphabet(0, 70 * i, optionsArray[i].name, false, false); 			optionText.isMenuItem = true; 			optionText.x += 300; 			/*optionText.forceX = 300; 			optionText.yMult = 90;*/ 			optionText.xAdd = 200; 			optionText.targetY = i; 			grpOptions.add(optionText);  			var textChild:AttachedText = null; 			if(optionsArray[i].type == 'bool') { 				var checkbox:CheckboxThingie = new CheckboxThingie(optionText.x - 105, optionText.y, optionsArray[i].getValue() == true); 				checkbox.sprTracker = optionText; 				checkbox.ID = i; 				checkboxGroup.add(checkbox); 			} else { 				optionText.x -= 80; 				optionText.xAdd -= 80; 				textChild = new AttachedText('' + optionsArray[i].getValue(), optionText.width + 80); 				textChild.sprTracker = optionText; 				textChild.copyAlpha = true; 				textChild.ID = i; 				grpTexts.add(textChild); 				optionsArray[i].setChild(textChild); 			}  			if(optionsArray[i].showBoyfriend && boyfriend == null) 			{ 				reloadBoyfriend(); 			} 			if(optionsArray[i].showNotes && previewNotes == null) 			{ 				var colorSwap:ColorSwap = new ColorSwap(); 				colorSwap.hue = ClientPrefs.arrowHSV[2][0] / 360; 				colorSwap.saturation = ClientPrefs.arrowHSV[2][1] / 100; 				colorSwap.brightness = ClientPrefs.arrowHSV[2][2] / 100;  				previewNotes = new AttachedSprite(); 				previewNotes.loadGraphic(Paths.image('previewNotes'), true, 164, 164); 				previewNotes.shader = colorSwap.shader; 				previewNotes.animation.add('frames', [0, 1, 2], 0); 				previewNotes.animation.play('frames'); 				previewNotes.sprTracker = textChild; 				previewNoteOption = optionsArray[i]; 				previewNotes.setGraphicSize(Std.int(previewNotes.width * 0.7)); 				previewNotes.updateHitbox(); 				previewNotes.yAdd = 20; 				add(previewNotes); 				updateNotes(); 			} 			updateTextFrom(optionsArray[i]); 		}  		changeSelection(); 		reloadCheckboxes(); 	}  	public function updateNotes() 	{ 		previewNotes.animation.curAnim.curFrame = previewNoteOption.curOption; 		previewNotes.xAdd = previewNotes.sprTracker.width + 20; 	}  	public function addOption(option:Option) { 		if(optionsArray == null || optionsArray.length < 1) optionsArray = []; 		optionsArray.push(option); 	}  	var nextAccept:Int = 5; 	var holdTime:Float = 0; 	var holdValue:Float = 0; 	override function update(elapsed:Float) 	{ 		if (controls.UI_UP_P) 		{ 			changeSelection(-1); 		} 		if (controls.UI_DOWN_P) 		{ 			changeSelection(1); 		}  		if (controls.BACK) { 			close(); 			FlxG.sound.play(Paths.sound('cancelMenu')); 		}  		if(nextAccept <= 0) 		{ 			var usesCheckbox = true; 			if(curOption.type != 'bool') 			{ 				usesCheckbox = false; 			}  			if(usesCheckbox) 			{ 				if(controls.ACCEPT) 				{ 					FlxG.sound.play(Paths.sound('scrollMenu')); 					curOption.setValue((curOption.getValue() == true) ? false : true); 					curOption.change(); 					reloadCheckboxes(); 				} 			} else { 				if(controls.UI_LEFT || controls.UI_RIGHT) { 					var pressed = (controls.UI_LEFT_P || controls.UI_RIGHT_P); 					if(holdTime > 0.5 || pressed) { 						if(pressed) { 							var add:Dynamic = null; 							if(curOption.type != 'string') { 								add = controls.UI_LEFT ? -curOption.changeValue : curOption.changeValue; 							}  							switch(curOption.type) 							{ 								case 'int' | 'float' | 'percent': 									holdValue = curOption.getValue() + add; 									if(holdValue < curOption.minValue) holdValue = curOption.minValue; 									else if (holdValue > curOption.maxValue) holdValue = curOption.maxValue;  									switch(curOption.type) 									{ 										case 'int': 											holdValue = Math.round(holdValue); 											curOption.setValue(holdValue);  										case 'float' | 'percent': 											holdValue = FlxMath.roundDecimal(holdValue, curOption.decimals); 											curOption.setValue(holdValue); 									}  								case 'string': 									var num:Int = curOption.curOption; //lol 									if(controls.UI_LEFT_P) --num; 									else num++;  									if(num < 0) { 										num = curOption.options.length - 1; 									} else if(num >= curOption.options.length) { 										num = 0; 									}  									curOption.curOption = num; 									curOption.setValue(curOption.options[num]); //lol 									//trace(curOption.options[num]); 							} 							updateTextFrom(curOption); 							curOption.change(); 							FlxG.sound.play(Paths.sound('scrollMenu')); 						} else if(curOption.type != 'string') { 							holdValue += curOption.scrollSpeed * elapsed * (controls.UI_LEFT ? -1 : 1); 							if(holdValue < curOption.minValue) holdValue = curOption.minValue; 							else if (holdValue > curOption.maxValue) holdValue = curOption.maxValue;  							switch(curOption.type) 							{ 								case 'int': 									curOption.setValue(Math.round(holdValue)); 								 								case 'float' | 'percent': 									curOption.setValue(FlxMath.roundDecimal(holdValue, curOption.decimals)); 							} 							updateTextFrom(curOption); 							curOption.change(); 						} 					}  					if(curOption.type != 'string') { 						holdTime += elapsed; 					} 				} else if(controls.UI_LEFT_R || controls.UI_RIGHT_R) { 					clearHold(); 				} 			}  			if(controls.RESET) 			{ 				for (i in 0...optionsArray.length) 				{ 					var leOption:Option = optionsArray[i]; 					leOption.setValue(leOption.defaultValue); 					if(leOption.type != 'bool') 					{ 						if(leOption.type == 'string') 						{ 							leOption.curOption = leOption.options.indexOf(leOption.getValue()); 						} 						updateTextFrom(leOption); 					} 					leOption.change(); 				} 				FlxG.sound.play(Paths.sound('cancelMenu')); 				reloadCheckboxes(); 			} 		}  		if(boyfriend != null && boyfriend.animation.curAnim.finished) { 			boyfriend.dance(); 		}  		if(nextAccept > 0) { 			nextAccept -= 1; 		} 		super.update(elapsed); 	}  	function updateTextFrom(option:Option) { 		var text:String = option.displayFormat; 		var val:Dynamic = option.getValue(); 		if(option.type == 'percent') val *= 100; 		var def:Dynamic = option.defaultValue; 		option.text = text.replace('%v', val).replace('%d', def); 	}  	function clearHold() 	{ 		if(holdTime > 0.5) { 			FlxG.sound.play(Paths.sound('scrollMenu')); 		} 		holdTime = 0; 	} 	 	function changeSelection(change:Int = 0) 	{ 		curSelected += change; 		if (curSelected < 0) 			curSelected = optionsArray.length - 1; 		if (curSelected >= optionsArray.length) 			curSelected = 0;  		descText.text = optionsArray[curSelected].description; 		descText.screenCenter(Y); 		descText.y += 270;  		var bullShit:Int = 0;  		for (item in grpOptions.members) { 			item.targetY = bullShit - curSelected; 			bullShit++;  			item.alpha = 0.6; 			if (item.targetY == 0) { 				item.alpha = 1; 			} 		} 		for (text in grpTexts) { 			text.alpha = 0.6; 			if(text.ID == curSelected) { 				text.alpha = 1; 			} 		}  		descBox.setPosition(descText.x - 10, descText.y - 10); 		descBox.setGraphicSize(Std.int(descText.width + 20), Std.int(descText.height + 25)); 		descBox.updateHitbox();  		if(boyfriend != null) 		{ 			boyfriend.visible = optionsArray[curSelected].showBoyfriend; 		} 		curOption = optionsArray[curSelected]; //shorter lol 		FlxG.sound.play(Paths.sound('scrollMenu')); 	}  	public function reloadBoyfriend() 	{ 		var wasVisible:Bool = false; 		if(boyfriend != null) { 			wasVisible = boyfriend.visible; 			boyfriend.kill(); 			remove(boyfriend); 			boyfriend.destroy(); 		}  		boyfriend = new Character(840, 170, 'bf', true); 		boyfriend.setGraphicSize(Std.int(boyfriend.width * 0.75)); 		boyfriend.updateHitbox(); 		boyfriend.dance(); 		insert(1, boyfriend); 		boyfriend.visible = wasVisible; 	}  	function reloadCheckboxes() { 		for (checkbox in checkboxGroup) { 			checkbox.daValue = (optionsArray[checkbox.ID].getValue() == true); 		} 	} } , visualuisubstate: package options;  #if desktop import Discord.DiscordClient; #end import flash.text.TextField; import flixel.FlxG; import flixel.FlxSprite; import flixel.addons.display.FlxGridOverlay; import flixel.group.FlxGroup.FlxTypedGroup; import flixel.math.FlxMath; import flixel.text.FlxText; import flixel.util.FlxColor; import lime.utils.Assets; import flixel.FlxSubState; import flash.text.TextField; import flixel.FlxG; import flixel.FlxSprite; import flixel.util.FlxSave; import haxe.Json; import flixel.tweens.FlxEase; import flixel.tweens.FlxTween; import flixel.util.FlxTimer; import flixel.input.keyboard.FlxKey; import flixel.graphics.FlxGraphic; import Controls;  using StringTools;  class VisualsUISubState extends BaseOptionsMenu { 	public function new() 	{ 		title = 'Visuals and UI'; 		rpcTitle = 'Visuals & UI Settings Menu'; //for Discord Rich Presence  		var option:Option = new Option('Note Skin:', 			"Funny notes dropping down, how should they look like?", 			'noteSkin', 			'string', 			'Default', 			['Default', 'Circles']); 		option.showNotes = true; 		option.onChange = onChangeNoteSkin; 		addOption(option);  		var option:Option = new Option('Note Splashes', 			"If unchecked, hitting \"Sick!\" notes won't show particles.", 			'noteSplashes', 			'bool', 			true); 		addOption(option);  		var option:Option = new Option('Hide HUD', 			'If checked, hides most HUD elements.', 			'hideHud', 			'bool', 			false); 		addOption(option); 		 		var option:Option = new Option('Time Bar:', 			"What should the Time Bar display?", 			'timeBarType', 			'string', 			'Time Left', 			['Time Left', 'Time Elapsed', 'Song Name', 'Disabled']); 		addOption(option);  		var option:Option = new Option('Flashing Lights', 			"Uncheck this if you're sensitive to flashing lights!", 			'flashing', 			'bool', 			true); 		addOption(option);  		var option:Option = new Option('Camera Zooms', 			"If unchecked, the camera won't zoom in on a beat hit.", 			'camZooms', 			'bool', 			true); 		addOption(option);  		var option:Option = new Option('Score Text Zoom on Hit', 			"If unchecked, disables the Score text zooming\neverytime you hit a note.", 			'scoreZoom', 			'bool', 			true); 		addOption(option);  		var option:Option = new Option('Health Bar Transparency', 			'How much transparent should the health bar and icons be.', 			'healthBarAlpha', 			'percent', 			1); 		option.scrollSpeed = 1.6; 		option.minValue = 0.0; 		option.maxValue = 1; 		option.changeValue = 0.1; 		option.decimals = 1; 		addOption(option); 		 		#if !mobile 		var option:Option = new Option('FPS Counter', 			'If unchecked, hides FPS Counter.', 			'showFPS', 			'bool', 			true); 		addOption(option); 		option.onChange = onChangeFPSCounter; 		#end  		super(); 	}  	function onChangeNoteSkin() 	{ 		updateNotes(); 	}  	#if !mobile 	function onChangeFPSCounter() 	{ 		if(Main.fpsVar != null) 			Main.fpsVar.visible = ClientPrefs.showFPS; 	} 	#end } , option.hx:package options;  import flash.text.TextField; import flixel.FlxG; import flixel.FlxSprite; import flixel.addons.display.FlxGridOverlay; import flixel.group.FlxGroup.FlxTypedGroup; import flixel.math.FlxMath; import flixel.text.FlxText; import flixel.util.FlxColor; import lime.utils.Assets; import flixel.FlxSubState; import flash.text.TextField; import flixel.FlxG; import flixel.FlxSprite; import flixel.util.FlxSave; import flixel.tweens.FlxEase; import flixel.tweens.FlxTween; import flixel.util.FlxTimer; import flixel.input.keyboard.FlxKey; import flixel.graphics.FlxGraphic; import Controls;  using StringTools;  class Option { 	private var child:Alphabet; 	public var text(get, set):String; 	public var onChange:Void->Void = null; //Pressed enter (on Bool type options) or pressed/held left/right (on other types)  	public var type(get, default):String = 'bool'; //bool, int (or integer), float (or fl), percent, string (or str) 	// Bool will use checkboxes 	// Everything else will use a text  	public var showBoyfriend:Bool = false; 	public var showNotes:Bool = false; 	public var scrollSpeed:Float = 50; //Only works on int/float, defines how fast it scrolls per second while holding left/right  	private var variable:String = null; //Variable from ClientPrefs.hx 	public var defaultValue:Dynamic = null;  	public var curOption:Int = 0; //Don't change this 	public var options:Array<String> = null; //Only used in string type 	public var changeValue:Dynamic = 1; //Only used in int/float/percent type, how much is changed when you PRESS 	public var minValue:Dynamic = null; //Only used in int/float/percent type 	public var maxValue:Dynamic = null; //Only used in int/float/percent type 	public var decimals:Int = 1; //Only used in float/percent type  	public var displayFormat:String = '%v'; //How String/Float/Percent/Int values are shown, %v = Current value, %d = Default value 	public var description:String = ''; 	public var name:String = 'Unknown';  	public function new(name:String, description:String = '', variable:String, type:String = 'bool', defaultValue:Dynamic = 'null variable value', ?options:Array<String> = null) 	{ 		this.name = name; 		this.description = description; 		this.variable = variable; 		this.type = type; 		this.defaultValue = defaultValue; 		this.options = options;  		if(defaultValue == 'null variable value') 		{ 			switch(type) 			{ 				case 'bool': 					defaultValue = false; 				case 'int' | 'float': 					defaultValue = 0; 				case 'percent': 					defaultValue = 1; 				case 'string': 					defaultValue = ''; 					if(options.length > 0) { 						defaultValue = options[0]; 					} 			} 		}  		if(getValue() == null) { 			setValue(defaultValue); 		}  		switch(type) 		{ 			case 'string': 				var num:Int = options.indexOf(getValue()); 				if(num > -1) { 					curOption = num; 				} 	 			case 'percent': 				displayFormat = '%v%'; 				changeValue = 0.01; 				minValue = 0; 				maxValue = 1; 				scrollSpeed = 0.5; 				decimals = 2; 		} 	}  	public function change() 	{ 		//nothing lol 		if(onChange != null) { 			onChange(); 		} 	}  	public function getValue():Dynamic 	{ 		return Reflect.getProperty(ClientPrefs, variable); 	} 	public function setValue(value:Dynamic) 	{ 		Reflect.setProperty(ClientPrefs, variable, value); 	}  	public function setChild(child:Alphabet) 	{ 		this.child = child; 	}  	private function get_text() 	{ 		if(child != null) { 			return child.text; 		} 		return null; 	} 	private function set_text(newValue:String = '') 	{ 		if(child != null) { 			child.changeText(newValue); 		} 		return null; 	}  	private function get_type() 	{ 		var newValue:String = 'bool'; 		switch(type.toLowerCase().trim()) 		{ 			case 'int' | 'float' | 'percent' | 'string': newValue = type; 			case 'integer': newValue = 'int'; 			case 'str': newValue = 'string'; 			case 'fl': newValue = 'float'; 		} 		type = newValue; 		return type; 	} }

**Comment by frantastic24** [comment]
This isn't a bug. It seems like you just didn't port all of the code
