### ISSUE TITLE
Screen effect

### ISSUE THREAD

**Issue by schwiftified** [ShadowMario/FNF-PsychEngine#3799]
### What is your question?

How can I add a screen effect in a song?

**Comment by tposejank** [comment]
idk man, I WOULD KNOW IF YOU GAVE ME YOUR FUCKING IDEAS MF IDIOT

**Comment by schwiftified** [comment]
This isn't a idea

**Comment by ThePsychEngineFan** [comment]
> This isn't a idea

you have to say what you mean, not just say "screen effect" because that is vague as hell and you arent telling us anything

**Comment by schwiftified** [comment]
> > This isn't a idea
> 
> you have to say what you mean, not just say "screen effect" because that is vague as hell and you arent telling us anything

That's the title not the question
