### ISSUE TITLE
how to move/hide botplay text with lua?

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#3805]
### What is your question?

the title says it all! (and please dont answer with `setProperty('cpuControlled', false);` or something)

**Comment by jmxamongusmodder** [comment]
> ### What is your question?
> the title says it all! (and please dont answer with `setProperty('cpuControlled', false);` or something)

i can help i have a hole way of making botplay look like your playing with ratings score and everything. also its source code i use for this. but uhhh if you want it i can give you it?

**Comment by acap09** [comment]
> > ### What is your question?
> > the title says it all! (and please dont answer with `setProperty('cpuControlled', false);` or something)
> 
> i can help i have a hole way of making botplay look like your playing with ratings score and everything. also its source code i use for this. but uhhh if you want it i can give you it?

i just want to move/hide the botplay.

**Comment by tposejank** [comment]
setProperty('botplayTxt.visible', false)

**Comment by Gui-iago** [comment]
setProperty('botplayTxt.visible', false)

skill issue B)

**Comment by AetherLynx** [comment]
For hiding: `setProperty('botplayTxt.visible', false)`
For moving: `setProperty('botplayTxt.x', <value>)`  /  `setProperty('botplayTxt.y', <value>)`

**Comment by acap09** [comment]
> setProperty('botplayTxt.visible', false)
> 
> skill issue B)

i dont have a skill isue lol, its just for my mod. :/

**Comment by acap09** [comment]
issue closed
