### ISSUE TITLE
how to use the new function?

### ISSUE THREAD

**Issue by zLightc** [ShadowMario/FNF-PsychEngine#3806]
### What is your question?

**hey there tricky guy or whatever!**
in your recent update you guys added _**cameraFlash**_ but I don't know how to code it in Lua am I supposed to type **_cameraFlash()_**? it doesn't work tho so can you please send me the code on how to do it _**(LUA)**_

Cheers!
**_~zLightc_**

**Comment by frantastic24** [comment]
`cameraFlash('camera', 'color', duration)`
camera can be: `'camHUD'`, `'camGame'`, `'other'`
color is a hex color number: `'0xFF0000'` for a red flash for example
duration: should be obvious
