### ISSUE TITLE
change note skin event

### ISSUE THREAD

**Issue by thedeveloper112206** [ShadowMario/FNF-PsychEngine#3808]
### What feature do you want to get added on the **base** engine?

i think i change note skin event would be cool to have the note skin change mid song. idk if anyone else has asked for this?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
You can already do this, and yes many people have asked
