### ISSUE TITLE
lua help

### ISSUE THREAD

**Issue by 0-skid** [ShadowMario/FNF-PsychEngine#3811]
### Describe your problem here.

i'm not sure if i'm doing this right but i'm trying to change a variable at a certain step in the song (i'm still fairly new to lua)
![Screenshot 2022-01-21 1 30 52 PM](https://user-images.githubusercontent.com/85322671/150590128-4165c086-55cb-4fae-8bcc-795e9a452487.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
If the variable already exists then don't use `local` in that line
