### ISSUE TITLE
How to make a note damage you overtime

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#382]
Hi,
I know how to make a note damage the player but I don't know how to make it damage overtime.
For example: I want the note when I hit it to hurt the player for the rest of the song for 0.01 damage, how do I do that.

**Comment by ShadowMario** [comment]
Make a variable that store how much damage it should deal.
When you get the note to damage the player, change the value of this variable.
On function `update`, you make it decrease the health and the value of this variable, if the value is over 0
