### ISSUE TITLE
how to move the judgement text and the combo counter above it (with lua)?

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#3821]
### Describe your problem here.

the title says it all! its in the way of the character in the mod, and i want to move it somewhere else. -question-?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

too much to explain

**Comment by 0-skid** [comment]
you don't need this. in the options you can change the position of it already

**Comment by craftersshaft** [comment]
you probably do need it if you wanna hide it for a song for some reason
