### ISSUE TITLE
Costum Fort (no coding)

### ISSUE THREAD

**Issue by endergames231** [ShadowMario/FNF-PsychEngine#3824]
### Describe your problem here.

help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by acap09** [comment]
you mean custom font? in lua code, its setTextFont('textTag', 'font');. how you do it is
download any font online (that is in .ttf) and put it in mods/fonts (example: youSussyBakaAmogus.tff), in lua code, put setTextFont('luaTextTag', 'file.tff'); (in this case, setTextFont('luaTextTag', 'youSussyBakaAmogus.ttf');.

**Comment by acap09** [comment]
i havent used that yet, but im pretty sure thats the answer
