### ISSUE TITLE
Main menu editable shits

### ISSUE THREAD

**Issue by crispyboi24** [ShadowMario/FNF-PsychEngine#3827]
### What feature do you want to get added on the **base** engine?

Some form of json similar to the gftitle json where you can change the positions of the main menu assets. Like the story mode and freeplay text shits. And maybe something where you can set a different main menu background. But that may be too much 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Gui-iago** [comment]
this PR may close this https://github.com/ShadowMario/FNF-PsychEngine/pull/3891
