### ISSUE TITLE
Botplay somewhat working with 6 & 9 keys

### ISSUE THREAD

**Issue by LogicalRegression** [ShadowMario/FNF-PsychEngine#383]
So botplay works fine with 4 keys, however with 6 and 9 keys only the 4 notes on the left side get lit up but at the wrong time and the remaining ones on the right side dont get lit up at all when a note is being hit. 

Here's an example for 6 keys:

https://www.youtube.com/watch?v=ZOamvO7DeBQ

Here's one for 9 keys: 

https://www.youtube.com/watch?v=KiP9V48PYhc

As far as i know theres no option to disable notes from being lit up upon being hit. Also the botplay text kinda spills over to the arrows on 6 keys and even more on 9 keys

**Comment by ShadowMario** [comment]
This isn't Shaggy's repo.
