### ISSUE TITLE
How to hide the entire GUI/HUD in a song except for the notes?

### ISSUE THREAD

**Issue by BrightEyesFox** [ShadowMario/FNF-PsychEngine#3834]
### Describe your problem here.

Title sums it up.

I'm modcharting for a song and at the beginning of the song I want to hide the entire HUD/GUI except for the arrows. I'm sorry if this is a duplicate or something because I tried looking but I couldn't find a solution anywhere.

If possible please show me the code to do this.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Edited MainMenuState.hx to not display the Awards button.

**Comment by acap09** [comment]
setProperty('healthBar.alpha',  0);
setProperty('healthBarBG.alpha', 0);
setProperty('iconP1.alpha', 0);
setProperty('iconP2.alpha', 0);
setProperty('scoreTxt.alpha', 0);

put this anywhere
also this is another way of doing it:

setProperty('healthBar.visible',  false);
setProperty('healthBarBG.visible', false);
setProperty('iconP1.visible', false);
setProperty('iconP2.visible', false);
setProperty('scoreTxt.visible', false);

put this anywhere

**Comment by BrightEyesFox** [comment]
holy shit thank you

**Comment by BrightEyesFox** [comment]
yep it worked, thanks so much
