### ISSUE TITLE
How to rotate the menu text (Story mode, freeplay ...)

### ISSUE THREAD

**Issue by Nekoiroshi** [ShadowMario/FNF-PsychEngine#3843]
### Describe your problem here.

i want to rotate the menu text and i don't know to do it .
i tried with tweenAngle and it not works pls help me

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MrClogsworthYT** [comment]
make new sprite sheet

**Comment by frantastic24** [comment]
Lua scripts aren't loaded in menus, use source

**Comment by MR-FNF** [comment]
> Lua scripts aren't loaded in menus, use source

Yea

**Comment by Nekoiroshi** [comment]
> Lua scripts aren't loaded in menus, use source

how i can do that ?

**Comment by Nekoiroshi** [comment]
> 



> There are thousands of source code menu tutorials online

i don't find any tuto that help me
