### ISSUE TITLE
Help: Botplay

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#3844]
### Describe your problem here.

So the botplay can only be turned on with opening the chart editor and then going to the menu and its really annoying. Can i change that? Do i need to edit some code?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes source and assets

**Comment by tposejank** [comment]
oh no someone that didn't read the patch notes💀💀💀💀

**Comment by CheesecakeForever** [comment]
> oh no someone that didn't read the patch notes💀💀💀💀

link? im stupid

**Comment by Itz-Miles** [comment]
> > oh no someone that didn't read the patch notes💀💀💀💀
> 
> link? im stupid

https://github.com/ShadowMario/FNF-PsychEngine/releases/tag/0.5.1

**Comment by ShadowMario** [comment]
Press Ctrl on Freeplay/Story Mode menus
