### ISSUE TITLE
Blammed lights crash!

### ISSUE THREAD

**Issue by Ifmations** [ShadowMario/FNF-PsychEngine#3847]
### Describe your bug here.

when I use Blammed lights in the engine, it crashes!!! I don't know why! and before you say that I am using them incorrectly, it happens with the original Blammed lights in Blammed! and I didn't even mess with them! im on Mac and I literally don't know what to do! I am using 0.4.1,

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, but I didn't change anything with the Blammed lights event,

**Comment by Theoyeah** [comment]
try to update to 0.5.1 maybe it can fix it

**Comment by dum-du-m** [comment]
why are you reporting a bug on not the latest version

**Comment by Playertrip777** [comment]
If you still want to use the old version, go to project.xml, look for the  
<define name="LUA_ALLOWED" if="windows" />
and change windows to desktop

**Comment by ShadowMario** [comment]
0.4.1 and Mac are not supported.
