### ISSUE TITLE
custom things??

### ISSUE THREAD

**Issue by RonHereLMAO** [ShadowMario/FNF-PsychEngine#3854]
### What is your question?

Im wondering how do you make custom transitons like in the miku mod or dave and bambi

### IM USING SOURCE

**Comment by adambrooks38882** [comment]
like what

**Comment by jmxamongusmodder** [comment]
> ring how do you make custom transitons like in the miku mod or dave and bambi
> 
> ### IM USING SOURCE

custom transitions

**Comment by jmxamongusmodder** [comment]
> like what

custom transitions

**Comment by ThePsychEngineFan** [comment]
you have to specify what you mean, show examples, not just say "like X mod"
