### ISSUE TITLE
hurt note skins

### ISSUE THREAD

**Issue by thedeveloper112206** [ShadowMario/FNF-PsychEngine#3855]
### What feature do you want to get added on the **base** engine?

would be like normal note skins and note splash skins but would be for hurt notes.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tposejank** [comment]
stupid

**Comment by frantastic24** [comment]
No, you can already do this with a simple script
Of which you can easily find a tutorial for

**Comment by ThePsychEngineFan** [comment]
you can literally just replace the existing sprite or just duplicate the note logic and add a new sprite onto it, you idiot
