### ISSUE TITLE
Warning: Could not find Visual Studio 2017 VsDevCmd Missing HXCPP_VARS Error: Could not automatically setup MSVC probem

### ISSUE THREAD

**Issue by adambrooks38882** [ShadowMario/FNF-PsychEngine#3856]
### Describe your bug here.

so i compiled Psych engine  but this Happend 

Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC 

did i do something wong? help me

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

hell no

**Comment by LemoniadoPAPA** [comment]
Are you Missing Visual Studio commponents 😎👊

**Comment by adambrooks38882** [comment]
oh yea it works now

**Comment by ShohaBoom** [comment]
Is the compile works on windows 7,
