### ISSUE TITLE
How do I stop the game from crashing if there isn't an easy/normal/hard chart file?

### ISSUE THREAD

**Issue by KutikiPlayz** [ShadowMario/FNF-PsychEngine#3865]
### What is your question?

The title explains it all. I've got some custom difficulties and some songs only use said difficulties. I don't want there to be useless easy/normal/hard charts in the folder when there's only hell/true hell for example.

What shit do I need to change to make that work? I only need to make it work for the freeplay menu.

Using source obviously.
I'm also on 0.4.2 so if this is already a thing in a newer update then let me know.

**Comment by frantastic24** [comment]
Week editor has a field for difficulties

**Comment by cherryiguess** [comment]
this is a thing in 0.5 and later updates, go to the week editor and select other, type your custom difficultes in there, and all songs must have the chart files, of course
![image](https://user-images.githubusercontent.com/93490646/150660751-40c0e4a2-cc95-46c9-8e29-a8045edc5fd4.png)

**Comment by cherryiguess** [comment]
> 

also for difficulties, just do Hell,True Hell, the - doesnt matter in the game but it does in files so its song(thechart)-true-hell

**Comment by CheesecakeForever** [comment]
I think hes talking about the error showing up. Copy the charts and add the needed prefix

**Comment by MayoALT** [comment]
> I think hes talking about the error showing up. Copy the charts and add the needed prefix

Instead just limit the week to one difficulty (put `Normal` in the difficulty array)

also its suffix not prefix
