### ISSUE TITLE
No custom note section in the wiki

### ISSUE THREAD

**Issue by b-0-x-3-d** [ShadowMario/FNF-PsychEngine#387]
There is no section explaining how to create a custom note type on the wiki page. Could you add one?

**Comment by PoleyMagik** [comment]
> There is no section explaining how to create a custom note type on the wiki page. Could you add one?

At this point I believe there is only an example script for custom notes, and their related LUA functions are not currently documented on the wiki. The example script can be found here near the bottom if it is any help. https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API

**Comment by Mastercopper2346** [comment]
Ohhhh so that’s why mine got the “duplicate ” label
