### ISSUE TITLE
Story-Mode, Freeplay, Everything

### ISSUE THREAD

**Issue by KyleOliverDeveloper** [ShadowMario/FNF-PsychEngine#3873]
### Describe your problem here.

Basically, i was casually opening my psych engine, to start working on a mod, and this popped up when i tried to select anything
![image](https://user-images.githubusercontent.com/94708825/150672915-6073864b-4761-491b-8a4f-9d960934ea33.png)
Please help me.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i coded the songs in-game, charts and dialogues, sprites. Also the portraits, menu screen, and logo bumpin'

**Comment by KyleOliverDeveloper** [comment]
please someone help me, im more than grateful for who can help

**Comment by Gui-iago** [comment]
there's something wrong with your json or xml files, try to move them to somewhere outside your mods folder and see if the same thing happens, if it does, then it's probably the images

**Comment by KyleOliverDeveloper** [comment]
> there's something wrong with your json or xml files, try to move them to somewhere outside your mods folder and see if the same thing happens, if it does, then it's probably the images

The question is: What .XML and .Json?? My friends said the same but idk if its all or not

**Comment by KyleOliverDeveloper** [comment]
Nevermind, i found the root of the bug. The week .Json has some errors that i'll try to fix. Thanks
