### ISSUE TITLE
:/ Added the character List for mods

### ISSUE THREAD

**Issue by afeefflox** [ShadowMario/FNF-PsychEngine#3874]
### What feature do you want to get added on the **base** engine?

I need character list for line character Place without going on up (Only mods)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by acap09** [comment]
**Congratulations!**

You failed the test!

**Comment by crispyboi24** [comment]
Character list is useless

**Comment by afeefflox** [comment]
:/ I know i'm dumb

**Comment by acap09** [comment]
> :/ I know i'm dumb Then why there is Week list That Also useless Right? and modlist

week list isnt useless, you use it to organize which week goes where, e.g.

this is the week list:

week1
week2
week4
week3
week7
week6
randomweekhaha69420thisweektitleissolongmanwhyisitsolongomgitswaytoolong

itll organize that way

**Comment by ThePsychEngineFan** [comment]
> :/ I know i'm dumb Then why there is Week list That Also useless Right? and modlist

week list is not useless it organises the weeks to be sorted in a specific order, for example:

week3
week2
week4
week1

in the game itll sort the weeks in the order you put them, so if i did this in weeklist it would set the weeks to be in this order.

secondly, modlist is also not useless, as it does the same with mods as what weeklist does with weeks.

dumbass.
