### ISSUE TITLE
Song audio not loading on HTML

### ISSUE THREAD

**Issue by Starmapo** [ShadowMario/FNF-PsychEngine#3877]
### Describe your bug here.

I know I shouldn't really compile to HTML5 at this point, but I was just curious to see if it worked. Fixed all the bugs in the source code preventing compilation. However when trying to play any song, the page throws out an error and freezes.
![image](https://user-images.githubusercontent.com/85134252/150680626-938071c8-96f9-4104-896f-db0394b808f8.png)
The instrumental file is indeed there and in MP3 form. All my haxelibs are up to date as well. I am using debug mode if that helps.

### Command Prompt/Terminal logs (if existing)

```bash
[lime.utils.Assets] ERROR: There is no SOUND asset with an ID of "assets/songs/tutorial/Inst.mp3"
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, but nothing that should cause this error [Same build as my 'time signatures' fork]

**Comment by HiroMizuki** [comment]
maybe check the encoding of the audio, it happens sometimes
if the error is the audio's encoding, u can simply convert it or export it to MP3 in some audio editing software

or else if it's not that, idk what's happening

**Comment by Starmapo** [comment]
Figured it out, LoadingState looks for the song paths but due to the new cache system it returns the audio files instead of the actual paths. After fixing it still gives this error though:
`"[lime.utils.Assets] ERROR: SOUND asset "songs:assets/songs/tutorial/Inst.mp3" exists, but only asynchronously"`
Seems to just be a bigger problem

**Comment by Spongeyboi** [comment]
> Figured it out, LoadingState looks for the song paths but due to the new cache system it returns the audio files instead of the actual paths. After fixing it still gives this error though: `"[lime.utils.Assets] ERROR: SOUND asset "songs:assets/songs/tutorial/Inst.mp3" exists, but only asynchronously"` Seems to just be a bigger problem

Yeah that error is because the audio isn't cached
(seen here: https://community.openfl.org/t/error-sound-asset-exists-but-only-asynchronously/11987)

**Comment by jbmagination** [comment]
Post-discussion on the other repo, are you willing to PR your fixes into the main engine?
