### ISSUE TITLE
Engine translation

### ISSUE THREAD

**Issue by MateusX02** [ShadowMario/FNF-PsychEngine#3878]
### What feature do you want to get added on the **base** engine?

I wanted to give the idea of ​​translating the engine, since there are people who do NOT understand English. I refer to the translation of images and texts.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by HiroMizuki** [comment]
already planned by shadow mario

**Comment by MateusX02** [comment]
Thanks.

**Comment by MateusX02** [comment]
hiro eu sei que tu é brasileiro
é pq a maioria aq é inglês

**Comment by HiroMizuki** [comment]
> hiro eu sei que tu é brasileiro é pq a maioria aq é inglês

ta kjk

**Comment by nintendofan44** [comment]
> hiro eu sei que tu é brasileiro é pq a maioria aq é inglês

eu sou outro

**Comment by nintendofan44** [comment]
mais sou praticamente deboas no ingles

**Comment by MateusX02** [comment]
eu sei o basico man

**Comment by ShadowMario** [comment]
This was already planned.
