### ISSUE TITLE
Can anyone send me the link of Patch Notes?

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#3883]
### What is your question?

Can anyone send me the link of Patch Notes for Psych engine bc im an idiot and cant find those?

**Comment by tposejank** [comment]
releases / gb

**Comment by CheesecakeForever** [comment]
> releases / gb

Oh, thanks. I thought that was only the release. Btw love your extra keys addition, extremely useful.
