### ISSUE TITLE
Game Crashes when getting a game over

### ISSUE THREAD

**Issue by AntiPlayzz** [ShadowMario/FNF-PsychEngine#3884]
### Describe your problem here.

So this modchart crashes my game when i get a game over and i cant seem to find the problem with it, someone please help.

The script is the cause of the problem
[aaronmode.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/7920816/aaronmode.zip)
.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Added a few songs, Win icons, New diff,etc

**Comment by AntiPlayzz** [comment]
Fixed it!

**Comment by LuckyMist8** [comment]
> Fixed it!

I'm Having The Same Issue, How Did You Fix It?
