### ISSUE TITLE
SOUNDS NOT PLAY

### ISSUE THREAD

**Issue by RayArmahedgehog** [ShadowMario/FNF-PsychEngine#3896]
### Describe your bug here.

I downloaded the latest version of psych engine (to play the holiday mod) and nothing is heard, not even the songs

### Command Prompt/Terminal logs (if existing)

```bash
idk
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Is this happening with the mod
If so the report is invalid
If not then give actual details

**Comment by HiroMizuki** [comment]
needs more information. What else happens, just this?

**Comment by RayArmahedgehog** [comment]
> Is this happening with the mod If so the report is invalid If not then give actual details

I mean, with or without a mod, just downloaded the psych engine, without mods, the totally vanilla psych engine, you can't hear it, with mods either

**Comment by RayArmahedgehog** [comment]
> needs more information. What else happens, just this?

just this

**Comment by HiroMizuki** [comment]
> > needs more information. What else happens, just this?
> 
> just this

bro just press 0 or +, maybe that's ur game volume

**Comment by RayArmahedgehog** [comment]
> > > needs more information. What else happens, just this?
> > 
> > 
> > just this
> 
> bro just press 0 or +, maybe that's ur game volume

oh wow definitely didn't think of that (sarcasm)

**Comment by HiroMizuki** [comment]
> > > > needs more information. What else happens, just this?
> > > 
> > > 
> > > just this
> > 
> > 
> > bro just press 0 or +, maybe that's ur game volume
> 
> oh wow definitely didn't think of that (sarcasm)

so it is ur audio client or smth bro, cuz i've never got audio error and i used psych since last year september. The only error i get sometimes is the game freezing without sound, and that's just a proxy error lmao
so, idk how to help ya

**Comment by frantastic24** [comment]
Could be a driver issue, or something else with your PC
We really can't do much with the little information we have
