### ISSUE TITLE
Difficulties with custom songs

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [ShadowMario/FNF-PsychEngine#3904]
### What feature do you want to get added on the **base** engine?

Basically what the bnb mod did with EX diff (also sorry this is the only mod I knew that I could reference from)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by HiroMizuki** [comment]
u already can do this yourself, no need to add for the main engine

**Comment by ThePsychEngineFan** [comment]
you can literally just create a new difficulty in source, have that difficulty be available, and then either change the chart to load different audio OR make a modchart which will change the audio if you selected the difficulty

**Comment by HiroMizuki** [comment]
> you can literally just create a new difficulty in source, have that difficulty be available, and then either change the chart to load different audio OR make a modchart which will change the audio if you selected the difficulty

bro, modchart is not the only way to set a changed audio, it is possible to code in source files too lmao

**Comment by ShadowMario** [comment]
This can already be done in the Week Editor 🗿

**Comment by ImaginationSuperHero528** [comment]
> This can already be done in the Week Editor 🗿 

WHAT IT CAN?

**Comment by HiroMizuki** [comment]
> > This can already be done in the Week Editor 🗿
> 
> WHAT IT CAN? WHAT VERSION?

latest one

**Comment by ImaginationSuperHero528** [comment]
> This can already be done in the Week Editor 🗿

I looked in week editor I don't see it!

**Comment by ThePsychEngineFan** [comment]
> > you can literally just create a new difficulty in source, have that difficulty be available, and then either change the chart to load different audio OR make a modchart which will change the audio if you selected the difficulty
> 
> bro, modchart is not the only way to set a changed audio, it is possible to code in source files too lmao

ah, my mistake then

**Comment by ThePsychEngineFan** [comment]
> > This can already be done in the Week Editor 🗿
> 
> I looked in week editor I don't see it!

you have to create the difficulty and then you can add it in the week editor
