### ISSUE TITLE
different noteskin on bf's side than the opponent's side

### ISSUE THREAD

**Issue by 0-skid** [ShadowMario/FNF-PsychEngine#3907]
### Describe your problem here.

![Screenshot_20220123-221733_Sublime Text](https://user-images.githubusercontent.com/85322671/150721309-4fd2b761-139d-4fb5-a746-dd034da0c928.png)
i don't know what i did wrong but when i open the song with the script it crashes

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

ported disruption

**Comment by frantastic24** [comment]
Try using `playerStrums` and `opponentStrums` instead of strumLineNotes, they both go from 0 to 3 iirc

**Comment by SonicXFire1987** [comment]
whats the full code?

**Comment by 0-skid** [comment]
> whats the full code?

this issue is closed
