### ISSUE TITLE
not reponding

### ISSUE THREAD

**Issue by jounor123456** [ShadowMario/FNF-PsychEngine#3909]
### Describe your problem here.

<img width="960" alt="not responding" src="https://user-images.githubusercontent.com/92073498/150724329-17dc91f0-f200-4147-80b0-118ee8b4f829.PNG">
its not responding some one help me please

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

idk

**Comment by acap09** [comment]
more info pls. we dont know how to fix your issue if info is insufficient

**Comment by jounor123456** [comment]
0.5.1 is not responding for some reason

**Comment by jounor123456** [comment]
on 64bit

**Comment by frantastic24** [comment]
That's barely any info, what are your specs, where does it freeze, is it consistent or only sometimes, literally describe what's actually happening. you also didn't answer if this build has any modifications
