### ISSUE TITLE
can someone explain makeLuaText width? i dont understand it

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#3910]
### What is your question?

the title says it all! the width one (makeLuaText(-tag-, -text-, **-width-**, -x-, -y-);)

**Comment by BeansCool54** [comment]
I don't use Lua that often but from what the description, I think it like this:
`makeLuaText('the tag', 'the text', x and y are the width and the height of the the text`?

**Comment by 0-skid** [comment]
it either means the spacing or how stretched out the text is i'm pretty sure
