### ISSUE TITLE
Visible Strum, Invisible Notes [Help]

### ISSUE THREAD

**Issue by IICoffyII** [ShadowMario/FNF-PsychEngine#3912]
### Describe your problem here.

I want the Notes to fade, but not the Strumlines. If that makes any sense... Can anyone spare some knowledge?
Also this is just for Mod Charts.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by IICoffyII** [comment]
Target Build maybe a lie. I am just doing it on mobile. If ya can believe me.

**Comment by blueDev2** [comment]
The variable to use is "copyAngle" from the note class
You probably have to change every note to copyAngle = false at onCompletePost()
copyAngle tells playstate to make the note instance copy the alpha of the strum line notes

**Comment by ShadowMario** [comment]
set the note individual note's `multAlpha` property to 0
