### ISSUE TITLE
Soundtest in psych

### ISSUE THREAD

**Issue by Trenton0** [ShadowMario/FNF-PsychEngine#3915]
### What is your question?

Has anyone recreated the soundtest from vs exe in psych?

as far as I know KE's code is compatible with psych

but it has 3 states (menu, soundtest, and a collectables state) and I'm pretty sure it also gets some of its data from playstate, and in psych lua is same way
so please help me

**Comment by BeansCool54** [comment]
It's actually really easy actually. Basically the sound test menu is a state of its own. The only data it extracts from Playstate is the songs and the difficulty based on the code you entered.

**Comment by Trenton0** [comment]
oh thx
