### ISSUE TITLE
Persistent Cached Data removed ?

### ISSUE THREAD

**Issue by DrKrazy** [ShadowMario/FNF-PsychEngine#3920]
### What is your question?

Hi, i was wondering why the persistent cached data was commented out in the latest patch, did it screw with the shaders or something else ?

(i didn't keep track of the early change logs and i haven't seen anynone talking about it)

**Comment by HiroMizuki** [comment]
by what i know, that option was removed from options menu and is now active everytime in-game

**Comment by trayfellow** [comment]
it was removed cause theres an overhauled asset loading system now which has caching but it doesnt destroy ur pc (better memory management)

**Comment by ShadowMario** [comment]
It's now enabled permanently by default
