### ISSUE TITLE
repeat infinitely

### ISSUE THREAD

**Issue by Murilo3127** [ShadowMario/FNF-PsychEngine#3923]
### Describe your problem here.

Hi, I wanted to know how to make an action repeat itself infinitely
For example: I want a note to rotate infinitely
Then I use noteTweenAngle
But how do I make it repeat infinitely?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

**Comment by BeansCool54** [comment]
Use the function onUpdate i think

**Comment by frantastic24** [comment]
Do it under onUpdate() or use a timer that loops indefinitely

**Comment by Murilo3127** [comment]
> 



> Faça isso em Update() ou use um tempo que

**Comment by Murilo3127** [comment]
> Do it under onUpdate() or use a timer that loops indefinitely

I tried using onUptade(elapsed) and the normal and it was not, how do I create a timer?

**Comment by acap09** [comment]
> > Do it under onUpdate() or use a timer that loops indefinitely
> 
> I tried using onUptade(elapsed) and the normal and it was not, how do I create a timer?

runTimer(-lua tag-, -seconds-, -loops);

**Comment by acap09** [comment]
put the loops to 0 to repeat infinitely

**Comment by acap09** [comment]
it will call 

function onTimerCompleted(tag, loops, loopsLeft)

end

**Comment by Murilo3127** [comment]
ok i will try to use this command

**Comment by Murilo3127** [comment]
> it will call
> 
> function onTimerCompleted(tag, loops, loopsLeft)
> 
> end
> 
> after its done

![Uploading Screenshot_20220125-113442.png…]()

**Comment by Murilo3127** [comment]
> it will call
> 
> function onTimerCompleted(tag, loops, loopsLeft)
> 
> end
> 
> after its done

it didn't work (I put noteTweenAngle) in the onTimerCompleted function

**Comment by frantastic24** [comment]
Show the code, both the runTimer and the onTimerCompleted function

**Comment by Murilo3127** [comment]
> Mostre o código, tanto a função runTimer quanto a função onTimerCompleted

![Screenshot_20220125-113448](https://user-images.githubusercontent.com/97374126/151002074-9c1775b5-4fdb-4f0e-80d2-98838f2cc769.png)
![Screenshot_20220125-113442](https://user-images.githubusercontent.com/97374126/151002082-39e30303-f3c5-49a5-bfdc-79f8c92730f7.png)

**Comment by frantastic24** [comment]
I don't see the issue so what's not working exactly?

**Comment by Murilo3127** [comment]
> I don't see the issue so what's not working exactly?

I also don't know exactly what happened, the action didn't repeat itself, it only did it once and stopped, is it because I set the timer to 10 seconds?

**Comment by Murilo3127** [comment]
> I don't see the issue so what's not working exactly?

I decreased the timer time and the error did not resolve

**Comment by frantastic24** [comment]
i think i know what the problem is, the tween is just setting the angle to 100, not adding 100 to the current angle
it is technically working, just isn't coded to do what you want it to do

**Comment by Murilo3127** [comment]
> i think i know what the problem is, the tween is just setting the angle to 100, not adding 100 to the current angle it is technically working, just isn't coded to do what you want it to do

hmmm ok how do i do that?

**Comment by frantastic24** [comment]
```
function onSongStart()
	for i=0,7 do
		noteTweenAngle('noteangle' .. i, i, 360, 1, 'cubeInOut');
	end
end

function onTweenCompleted(tag)
	for i=0,3 do
		setPropertyFromGroup('playerStrums', i, 'angle', 0);
	end
	for i=0,3 do
		setPropertyFromGroup('opponentStrums', i, 'angle', 0);
	end
	for i=0,7 do
		noteTweenAngle('noteangle' .. i, i, 360, 1, 'cubeInOut');
	end
end
```
