### ISSUE TITLE
changing parts in song 

### ISSUE THREAD

**Issue by icyboi223** [ShadowMario/FNF-PsychEngine#3926]
### Describe your problem here.

I already have my song, but I wanted to edit the vocals. When i did it and replaced the voices.ogg it still plays the old one before I edited it and doesnt change. Any way to fix this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by cherryiguess** [comment]
just reopen the game lol

**Comment by ThePsychEngineFan** [comment]
have you rebuilt the game?
