### ISSUE TITLE
I Was Compiling The Game But, There Is An Error In Discord.hx

### ISSUE THREAD

**Issue by RandomGuy987** [ShadowMario/FNF-PsychEngine#3932]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/98375372/150914895-bc29cbc6-15b0-481f-9d09-ccc2e24a1b07.png)

It Says: 
source/Discord.hx:4: characters 8-30 : Type not found : discord_rpc.DiscordRpc
source/Discord.hx:79: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:18: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:28: characters 4-14 : Type not found : DiscordRpc
source/Discord.hx:33: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:38: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:43: characters 3-13 : Type not found : DiscordRpc

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I Edited The Application's Name.

**Comment by ImYousuf123** [comment]
I Don't Know How To Fix It Because I'm A Newbie

**Comment by BeansCool54** [comment]
What exactly did you edit? The name in Project.xml or the build's name?

**Comment by HafimieForever** [comment]
Did you run this on your command prompt?
`haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc`

**Comment by RandomGuy987** [comment]
First I Only Changed The Application Name
And Second Yes I Did

**Comment by RandomGuy987** [comment]
![image](https://user-images.githubusercontent.com/98375372/151376594-0ec663f6-c883-4e76-9c0e-8ea1584758c4.png)

**Comment by RandomGuy987** [comment]
> What exactly did you edit? The name in Project.xml or the build's name?

In The Project.xml
