### ISSUE TITLE
:/ How to fix for complied games

### ISSUE THREAD

**Issue by afeefflox** [ShadowMario/FNF-PsychEngine#3935]
### Describe your bug here.

so when I'm going to compile the game it got bug but this time is diffrent

### Command Prompt/Terminal logs (if existing)

```bash
export/release/windows/haxe/ApplicationMain.hx:298: characters 1-8 : Build failure
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I just made portable mod

**Comment by ThePsychEngineFan** [comment]
did you edit the source code?

**Comment by afeefflox** [comment]
:/ yeah

**Comment by ThePsychEngineFan** [comment]
> 

what changes did you make to the source?

and one thing, try getting a clean slate of the source code and building it then, if there are no issues with the clean build, then you did something wrong.
