### ISSUE TITLE
Text appear in bottom left corner of screen

### ISSUE THREAD

**Issue by BrightEyesFox** [ShadowMario/FNF-PsychEngine#3937]
### Describe your problem here.

Basically, how do I make text appear in the bottom left corner of the screen in a modchart, I tried using the wiki but it doesn't seem to appear at all

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

removed awards, hid awards and story mode on menu

**Comment by Gui-iago** [comment]
like this

https://github.com/ShadowMario/FNF-PsychEngine/discussions/2947
you can make it so it changes on a specific song

**Comment by ThePsychEngineFan** [comment]
ehh i never got to adding it, i ended up not even doing it, closing issue
