### ISSUE TITLE
only one times use tween x/y

### ISSUE THREAD

**Issue by WortwL** [ShadowMario/FNF-PsychEngine#3941]
### Describe your bug here.

so when i use any tween x/y it wont tweening again after using tween

idk if this a bug or anything else

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by ThePsychEngineFan** [comment]
you have to specify what the problem is, would you mind showing the modchart code?

**Comment by frantastic24** [comment]
Note that tweens don't *add* to the original value, but set it to the value given instead so unless you give it a formula it will stay at the value given

**Comment by ShadowMario** [comment]
> Note that tweens don't _add_ to the original value, but set it to the value given instead so unless you give it a formula it will stay at the value given

^

**Comment by WortwL** [comment]
ah i see so the modchart is limited anyways thanks

**Comment by MayoALT** [comment]
you CAN do this: `getProperty('fakeobject.x') + 50` and put that where the target variable is

**Comment by WortwL** [comment]
> you CAN do this: `getProperty('fakeobject.x') + 50` and put that where the target variable is

like how?

**Comment by frantastic24** [comment]
`doTweenX('tweenX', 'object', getProperty('object.x')+50, 1);`
this makes the tween read the current value and add 50 to it, rather than just setting it to 50

**Comment by WortwL** [comment]
how do i exactly use that function?

**Comment by frantastic24** [comment]
same way you were using it already, just replace `object` with your object tag

**Comment by WortwL** [comment]
> same way you were using it already, just replace `object` with your object tag

how ? i want to use this for the note/modchart

**Comment by frantastic24** [comment]
I really can't make it any simpler than that, you'll have to figure it out on your own
It is not that hard
