### ISSUE TITLE
Alt Anims don't make play the "-loop" counterpart

### ISSUE THREAD

**Issue by KapsLockCh** [ShadowMario/FNF-PsychEngine#3942]
### Describe your bug here.

Alt Anims don't use the "-loop" counterparts that are used for the parents' eye glow and the car stages.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I made some code that changes BF's animations in lua when under a certain amount of health, but it uses triggerEvent for the idle change.

**Comment by ShadowMario** [comment]
They do, you've set it wrong on the character editor.
