### ISSUE TITLE
Wait function

### ISSUE THREAD

**Issue by GMan2006i** [ShadowMario/FNF-PsychEngine#3946]
### What feature do you want to get added on the **base** engine?

instead of having to use a 'runTimer' function everytime i want to delay something, could you add like a wait function so instead it will delay in just that line of code

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by BrightEyesFox** [comment]
that would only be useful in specific occasions, and even then, just use a onStepHit loop

**Comment by GMan2006i** [comment]
> that would only be useful in specific occasions, and even then, just use a onStepHit loop

what part of da wiki is that under

**Comment by ThePsychEngineFan** [comment]
> > that would only be useful in specific occasions, and even then, just use a onStepHit loop
> 
> what part of da wiki is that under

its not in the wiki, but its very easy to implement. just bear with me i forgot what the code was, also same person, this is an alt

**Comment by ThePsychEngineFan** [comment]
`function onStepHit()
    stepthinge = curStep % 16; --random step stuff, it goes from 0-15 not 1-16
    --you can change the number to be larger if you want to have something that happens every few sections
    --for example if you want something to happen every 2 sections, you would change it from 16 to 32
    --and then make an if statement checking for 15 and 31, since one section is 16 steps
    
    if stepthinge == 0 then --resets the counter to go back to 0 at the end of the section
        section = curStep / 16;
    end
    
    if stepthinge == 7 then --checks if its halfway through the section and then does a thingie
        --do something
        --you can do as much as you want with these, they are very useful for modcharts
    end
end`

here is the code, have fun

**Comment by ThePsychEngineFan** [comment]
`function onStepHit()
    stepthinge = curStep % 16; --random step stuff, it goes from 0-15 not 1-16
    --you can change the number to be larger if you want to have something that happens every few sections
    --for example if you want something to happen every 2 sections, you would change it from 16 to 32
    --and then make an if statement checking for 15 and 31, since one section is 16 steps
    
    if stepthinge == 0 then --resets the counter to go back to 0 at the end of the section
        section = curStep / 16;
    end
    
    if stepthinge == 7 then --checks if its halfway through the section and then does a thingie
        --do something
        --you can do as much as you want with these, they are very useful for modcharts
    end
end`

**Comment by ThePsychEngineFan** [comment]
```
function onStepHit()
    stepthinge = curStep % 16; --random step stuff, it goes from 0-15 not 1-16
    --you can change the number to be larger if you want to have something that happens every few sections
    --for example if you want something to happen every 2 sections, you would change it from 16 to 32
    --and then make an if statement checking for 15 and 31, since one section is 16 steps
    
    if stepthinge == 0 then --resets the counter to go back to 0 at the end of the section
        section = curStep / 16;
    end
    
    if stepthinge == 7 then --checks if its halfway through the section and then does a thingie
        --do something
        --you can do as much as you want with these, they are very useful for modcharts
    end
end
```

youre welome, have fun, you can close this now

**Comment by ShadowMario** [comment]
No idea how to do that.
