### ISSUE TITLE
main menu without coding>mods folder

### ISSUE THREAD

**Issue by anonybean** [ShadowMario/FNF-PsychEngine#3949]
### What feature do you want to get added on the **base** engine?

is it possible to add the main menu on Lua without coding

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by frantastic24** [comment]
It's not possible, and it won't be possible, and you failed the test

**Comment by WolfyTail** [comment]
It's impossible, you need the source code.

**Comment by anonybean** [comment]
damn
