### ISSUE TITLE
Add DadNoteStyle/BFNoteStyle and DadSplashStyle/BFSplashStyle

### ISSUE THREAD

**Issue by THOBY555** [ShadowMario/FNF-PsychEngine#3950]
### What feature do you want to get added on the **base** engine?

cuz this is great just go to Playstate.hx/SONG.hx/Chartingstate.hx and you done 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by HiroMizuki** [comment]
there's a discussion about that, but i would say it is a good idea

**Comment by Gui-iago** [comment]
![image](https://user-images.githubusercontent.com/45212377/151052995-df003777-9263-4349-9d3f-55bf84d2621d.png)
oh shit oh fuck

joke aside, yeah, it's a good idea
