### ISSUE TITLE
Compile error pls help

### ISSUE THREAD

**Issue by glitchygmr** [ShadowMario/FNF-PsychEngine#3955]
### Describe your bug here.

trying to build the source, getting error messages i dont know how to fix, please help if you can!

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\Home\Downloads\FNF-PsychEngine-0.5.1>lime test windows -debug
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/group/FlxGroup.hx:473: characters 80-91 : Type not found : ObjectClass
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:11: characters 8-37 : Type not found : flixel.util.FlxDirectionFlags
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/system/frontEnds/PluginFrontEnd.hx:47: characters 19-28 : Type not found : ClassType
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:484: characters 21-25 : Unknown identifier : WALL
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:504: characters 21-25 : Unknown identifier : WALL
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:530: characters 21-28 : Unknown identifier : CEILING
C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:550: characters 21-26 : Unknown identifier : FLOOR
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/group/FlxGroup.hx:852: characters 19-30 : Type not found : ObjectClass
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/system/frontEnds/PluginFrontEnd.hx:94: characters 20-29 : Type not found : ClassType
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, created ModeSelectState.hx in the source folder and edited MainMenuState.hx to have a menu option for it

**Comment by CrusherMods** [comment]
Haxe wasnt installed right I'm guessing, Try reinstalling it

**Comment by LemoniadoPAPA** [comment]
You wrote the code wrong, rewrite it 😎👊

**Comment by glitchygmr** [comment]
> Haxe wasnt installed right I'm guessing, Try reinstalling it

I have uninstalled and reinstalled haxe several times, still shows the error

> You wrote the code wrong, rewrite it 😎👊

i fixed all of the errors from my psych build before making this post, and its clear by looking at the error that its from the haxe files and addons, not my build

**Comment by MrClogsworthYT** [comment]
> ### Describe your bug here.
> trying to build the source, getting error messages i dont know how to fix, please help if you can!
> 
> ### Command Prompt/Terminal logs (if existing)
> ```shell
> C:\Users\Home\Downloads\FNF-PsychEngine-0.5.1>lime test windows -debug
> C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/group/FlxGroup.hx:473: characters 80-91 : Type not found : ObjectClass
> C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:11: characters 8-37 : Type not found : flixel.util.FlxDirectionFlags
> C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/system/frontEnds/PluginFrontEnd.hx:47: characters 19-28 : Type not found : ClassType
> C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:484: characters 21-25 : Unknown identifier : WALL
> C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:504: characters 21-25 : Unknown identifier : WALL
> C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:530: characters 21-28 : Unknown identifier : CEILING
> C:/HaxeToolkit/haxe/lib/flixel-addons/git/flixel/addons/display/FlxExtendedSprite.hx:550: characters 21-26 : Unknown identifier : FLOOR
> C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/group/FlxGroup.hx:852: characters 19-30 : Type not found : ObjectClass
> C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/system/frontEnds/PluginFrontEnd.hx:94: characters 20-29 : Type not found : ClassType
> ```
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> Yes, created ModeSelectState.hx in the source folder and edited MainMenuState.hx to have a menu option for it

install haxe flixel 4.9.0

**Comment by glitchygmr** [comment]
still shows the errors, but thanks anyway :)
![image](https://user-images.githubusercontent.com/92896412/151273702-7ab24731-8d25-4127-ac9d-b9bfa65e9429.png)

**Comment by MrClogsworthYT** [comment]
> still shows the errors, but thanks anyway :) ![image](https://user-images.githubusercontent.com/92896412/151273702-7ab24731-8d25-4127-ac9d-b9bfa65e9429.png)

it isnt the same error the first error was about flixel now its about lime have you tried to use lime 7.9.0?

**Comment by glitchygmr** [comment]
> it isnt the same error the first error was about flixel now its about lime have you tried to use lime 7.9.0?

i didnt think of that, im.busy rn but ill try that later!

**Comment by glitchygmr** [comment]
ok, so that fixed most of it but theres still these errors for flixel addons, im assuming i have to update it so which version is best?
![image](https://user-images.githubusercontent.com/92896412/151370751-1bde0d4c-84b6-482a-8278-94eb8d5da030.png)

**Comment by MrClogsworthYT** [comment]
yeah lmao

**Comment by MrClogsworthYT** [comment]
> ok, so that fixed most of it but theres still these errors for flixel addons, im assuming i have to update it so which version is best? ![image](https://user-images.githubusercontent.com/92896412/151370751-1bde0d4c-84b6-482a-8278-94eb8d5da030.png)

use 2.10

**Comment by MrClogsworthYT** [comment]
> alright, its finally building. Thank you so much for the help!! ^^

np
