### ISSUE TITLE
Static Note (SOURCE ONLY)

### ISSUE THREAD

**Issue by Trenton0** [ShadowMario/FNF-PsychEngine#3959]
### Describe your problem here.

Gave me static note code pls i need it for a triple trouble remake

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Ported some of the mod's code And  etc.

**Comment by afeefflox** [comment]
:/ Bruh go to Sonic.exe Source codes
https://github.com/CryBitDev/Sonic.exe-source-1.5-and-2

**Comment by Trenton0** [comment]
it didn't work :/

**Comment by BeansCool54** [comment]
do it yourself lol

**Comment by ThePsychEngineFan** [comment]
learn to code

- [ ] learn to code
