### ISSUE TITLE
Repository Error

### ISSUE THREAD

**Issue by duckyduck1q** [ShadowMario/FNF-PsychEngine#3960]
### Describe your problem here.

Cloning into 'D:\FNF-PsychEngine-main\git'...
POST git-upload-pack (185 bytes)
POST git-upload-pack (1012 bytes)
Remote: Enumerating objects: 3504, done.
Error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054
Error: 5553 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
An error occurred while cloning the remote repository: Git failed with a fatal error.
early EOF
fetch-pack: invalid index-pack output

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MrClogsworthYT** [comment]
git problem not repo problem

**Comment by duckyduck1q** [comment]
ok

**Comment by MrClogsworthYT** [comment]
close this
