### ISSUE TITLE
added Difficulty events

### ISSUE THREAD

**Issue by afeefflox** [ShadowMario/FNF-PsychEngine#3961]
### What feature do you want to get added on the **base** engine?

:/ I just wanted change each difficulty events had different event (Like Accelerant Hank for FUCKED) 
 
example: 
normal  = events
easy = events-easy (if you want the easy version events)
hard = events-hard
custom = events-your-custom-difficulty

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by DEV-idiotXD** [comment]
here take this now close this

```lua
function onEvent(name, value1, value2)
	if name == 'example_name' then
		if difficulty == 2 then --if difficulty is hard
			--code only for hard
		elseif difficulty == 1 then --if difficulty is normal
			--code for normal
		elseif difficulty == 0 then --if difficulty is easy
			--code for easy
		end
	end
end
```

**Comment by HiroMizuki** [comment]
i think it would be a good idea. I'll try to code it at source

**Comment by DEV-idiotXD** [comment]
```hx
switch(varname) {

    case 1:
        //normal code

        case 2:
            //hard code

            case 0:
                //easy code
            

}
```

**Comment by DEV-idiotXD** [comment]
i literally have no life XD

**Comment by DEV-idiotXD** [comment]
```hx
switch(eventname) {


    case 'YOUREVENTNAME':
        switch(difficulty_varname_idk)
        {
            case (2): // hard
            // hard mode code

            case (1): // normal
            // normal mode code

            case (0): // easy
            // easy mode code


        }


}
```

**Comment by DEV-idiotXD** [comment]
idk the name of the difficulty var so just find it

**Comment by cherryiguess** [comment]
you can already do that, just dont save the events as events.json, its saved in the json file if has events

**Comment by ImaginationSuperHero528** [comment]
One I somewhat want this but more like events then a second one that only works on curtain difficulties

**Comment by HiroMizuki** [comment]
> you can already do that, just dont save the events as events.json, its saved in the json file if has events

true

**Comment by ShadowMario** [comment]
1. You can already load difficulty specific events by saving the events on the same chart as the notes chart. (Simply don't clear your events).

2. You failed the test, congratulations.
![Screenshot_1](https://user-images.githubusercontent.com/44785097/152281444-63213316-6c7f-4c2d-a18b-3e713c04e050.png)
