### ISSUE TITLE
Fade Image event not working on 5.1 but works on 4.2

### ISSUE THREAD

**Issue by neighborduck** [ShadowMario/FNF-PsychEngine#3970]
### What is your question?

so on psych 0.4.2 I used a event where an image would fade in and then fade out but when I moved the event over to version 5.1 the image flashes on the screen for the fade in portion and the image fade out portion works fine any way to fix this? this is the event im using
![Screenshot_100](https://user-images.githubusercontent.com/91151439/151044027-83830f00-ea21-4625-b8bb-d655dacdb16c.png)

This is how the event is on 0.4.2: https://www.youtube.com/watch?v=bbzB2_ULcBM

 This is how the event is on 0.5.1: https://www.youtube.com/watch?v=_fRb6T1KDvg

**Comment by MrClogsworthYT** [comment]
> ### What is your question?
> so on psych 0.4.2 I used a event where an image would fade in and then fade out but when I moved the event over to version 5.1 the image flashes on the screen for the fade in portion and the image fade out portion works fine any way to fix this? this is the event im using ![Screenshot_100](https://user-images.githubusercontent.com/91151439/151044027-83830f00-ea21-4625-b8bb-d655dacdb16c.png)
> 
> This is how the event is on 0.4.2: https://www.youtube.com/watch?v=bbzB2_ULcBM
> 
> This is how the event is on 0.5.1: https://www.youtube.com/watch?v=_fRb6T1KDvg

vids are private mate

**Comment by frantastic24** [comment]
Set alpha to 0 then tween when it's created
Also videos are private

**Comment by neighborduck** [comment]
The videos should be unlisted now*

**Comment by Fridox-lol** [comment]
idk how
