### ISSUE TITLE
cannot add song to week

### ISSUE THREAD

**Issue by TwyLikesMakingFNFmods** [ShadowMario/FNF-PsychEngine#3974]
### Describe your problem here.

when I add a song to my week, it gives me an error and crashes the game when I play the week, anyone know how to fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I removed all the weeks from the original game and added a week

**Comment by SrtHero278** [comment]
are you using the week editor?

**Comment by TwyLikesMakingFNFmods** [comment]
> are you using the week editor?

yes I am
