### ISSUE TITLE
Is iconP1 and iconP2 is part of an object?

### ISSUE THREAD

**Issue by Den198888** [ShadowMario/FNF-PsychEngine#3976]
### Describe your problem here.

i am doing a doTweenAngle on icon but idk if it will work and idk is its also part of OBJECT variable (iconP1 - iconP2) like it will spin on beat hits

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i edited the HealthIcon.hx and PlayState.hx for winning icons

**Comment by SrtHero278** [comment]
They're not really part of a group. They're their own object variable.
```
setProperty('iconP1.angle', -25);
setProperty('iconP2.angle', -25);
doTweenAngle('bopP1', 'iconP1', 0, 0.3)
doTweenAngle('bopP2', 'iconP2', 0, 0.3)
```

**Comment by Den198888** [comment]
https://user-images.githubusercontent.com/96397208/151275615-3dc56330-7283-4006-b5e5-962e52355140.mp4

Thank you, its working :D its bopping now on beat thank you♥️

**Comment by MayoALT** [comment]
close the issue

**Comment by Den198888** [comment]
how

**Comment by Den198888** [comment]
ow wait

**Comment by Den198888** [comment]
sorry
