### ISSUE TITLE
Psych Engine doesnt Let me Add Characters!!!

### ISSUE THREAD

**Issue by deco1212** [ShadowMario/FNF-PsychEngine#3977]
### Describe your problem here.

Proof is here:
https://www.youtube.com/watch?v=nsAj-Ra_6k8&feature=youtu.be

Anyone please help me, i really hope someone helps me!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by FNFpro689** [comment]
You need to put the characters sprite sheet and xml file in mods/images/characters if  your using the compiled version.

**Comment by deco1212** [comment]
I ALREADY DID!

**Comment by AlansGames** [comment]
You need to change the animation name to the one in the .xml

**Comment by main-thing** [comment]
To do this open the character template in the character editor and change the source image to the name of the character that you are tryibg to mod in. Then, go to the animations tab and add the charater anim names one by one and click save character.

**Comment by deco1212** [comment]
It is the correct one, and main thing, i already did all of that stuff.

**Comment by deco1212** [comment]
WAIT! i copied and pasted my characters to it to be another one, i went into character editor and it worked well? lemme try with the ones im trying to add.

**Comment by deco1212** [comment]
Wtf?? not working

**Comment by deco1212** [comment]
I tried template and i used some random pose on the dads up pose, not "dad up" or smth, AND IT WORKED FINE????

**Comment by main-thing** [comment]
if you are still confused I'll link you this video on character adding: https://youtu.be/ihM3VEJPHuA?t=173 (this help me out alot)

**Comment by deco1212** [comment]
THANK YOU SO MUCH AAAAAAAAAAAAAAA

**Comment by frantastic24** [comment]
Close this then
