### ISSUE TITLE
FPS locked while playing

### ISSUE THREAD

**Issue by drakonieyah** [ShadowMario/FNF-PsychEngine#3981]
### Describe your bug here.

Literally what the title says. If I am playing a song currently, my FPS is locked to 61 (basically 60) - with, and without using the precache in the options - even though my fps cap is twice that (120). I have no idea what causes this issue, I was playing with middlescroll, no hud, downscroll, ghost tapping, and there are about 3 events that happen frequently - one or two which are custom, but I doubt that's the issue, as the bad framerate appears before any events trigger.
There is a custom stage that is nothing special, it's made up of 3-4 solid images. The characters are precached to brace lag when the character change event is called.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by ThePsychEngineFan** [comment]
hardware issue maybe?? idk
