### ISSUE TITLE
How to add event?

### ISSUE THREAD

**Issue by Blaste-xd** [ShadowMario/FNF-PsychEngine#3984]
### What is your question?

because when i try to create an event it says source/editors/ChartingState.hx:87: characters 16-17 : Expected ] please help me :(

**Comment by flooferwhoosh** [comment]
try without source code in mods>custom_events>*code your own event lua*

if you want an example of event code: https://gamebanana.com/tools/7714

**Comment by ImaginationSuperHero528** [comment]
> try without source code in mods>custom_events>_code your own event lua_
> 
> if you want an example of event code: https://gamebanana.com/tools/7714

Does this guy do or know lua?

**Comment by ImaginationSuperHero528** [comment]
People who know how should answer I know this is a solution but still

**Comment by SrtHero278** [comment]
can we see this chunk of code?
![image](https://user-images.githubusercontent.com/93018286/151267107-99e41cc3-807c-4f56-a765-5968696bb12a.png)

**Comment by Blaste-xd** [comment]
what I wanted to do was copy an event from the starlight mayhem mod but I get this error
![-](https://user-images.githubusercontent.com/96892750/151282895-46ae342d-fbe5-4aa7-bc7a-585e3976ad73.png)

**Comment by frantastic24** [comment]
I believe your event shouldn't have a comma at the end while the one above it must have one

**Comment by BeansCool54** [comment]
It's because of the comma at the end of the last event. Remove it
