### ISSUE TITLE
Instant death?

### ISSUE THREAD

**Issue by Carss1235** [ShadowMario/FNF-PsychEngine#3990]
### Describe your bug here.

hello! whenever i boot up a song in the psych engine and i miss 1 note i seem to die instantly? i do not know what has happened (i have reinstalled psych many times with both 32bit and 64bit versions so i don't think it's an issue on my end) i hope this can be fixed soon!

video showing my problem: (i did NOT press the r button)
https://youtu.be/GVLLILaJUqc

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no this is a fresh version of psych

**Comment by CrusherMods** [comment]
you literally have the gameplay changer on... 
hit ctrl before entering a song to disable it
