### ISSUE TITLE
Modchart Creator/Editor

### ISSUE THREAD

**Issue by ThePsychEngineFan** [ShadowMario/FNF-PsychEngine#4017]
### What feature do you want to get added on the **base** engine?

So here's my idea in a nutshell. When you press 7 on the menu and go to the editor menu, there could be another selection called "Modchart Editor". Basically what this would do, it would let you easily create a modchart for a song. I don't have a lot of knowledge of coding, especially Haxe, but I'll try my best to try and create a pull request.

Here's some ideas for the editor.

Some basic stuff like step and beat specific stuff, a loop, basically making something happen every so often, setting things to be difficulty specific, the generic modchart functions, playing sounds and making images and text appear more easily, and that's all I can really think of now.

This is probably too much to ask for, so I'm gonna try to make it myself with a pull request, but I'm gonna have to learn how to code to do that.

Anyways, hope you liked reading this.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by cherryiguess** [comment]
even though this clearly wouldnt be added in, it would be ridiculous making a modchart editor

**Comment by ThePsychEngineFan** [comment]
> even though this clearly wouldnt be added in, it would be ridiculous making a modchart editor, it sounds like a cool feature but i dont think shadow mario would add it in

ah, fair enough then, ill close this then
