### ISSUE TITLE
How do i make a loading screen when entering a song in desktop (not HTML5)

### ISSUE THREAD

**Issue by Theoyeah** [ShadowMario/FNF-PsychEngine#4022]
### Describe your problem here.

The title says everything.
Im AWARE that even the loading screen will last 3 seconds, i want it 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, just modified some thing but not much

**Comment by Theoyeah** [comment]
i've seen this but i can't find getnextstate

**Comment by CrusherMods** [comment]
> i've seen this but i can't find getnextstate

oh but I dont think you need to do that though...

**Comment by Theoyeah** [comment]
so what do i do ?

**Comment by KutikiPlayz** [comment]
pretty sure all you gotta do is search for #NO_PRELOAD_ALL in LoadingState.hx and get rid of them
remember to get rid of the #end after then as well otherwise you'll get an error

**Comment by Bludye** [comment]
this adds the loading screen but songs dont actually load

> pretty sure all you gotta do is search for #NO_PRELOAD_ALL in LoadingState.hx and get rid of them remember to get rid of the #end after them as well otherwise you'll get an error

this adds the loading screen but songs refuse to load
