### ISSUE TITLE
Did you notice the typo in the wiki?

### ISSUE THREAD

**Issue by PrismLight** [ShadowMario/FNF-PsychEngine#4024]
### What is your question?

Does anyone notice the typo in the wiki? It's in "Lua Script API: Variables." Not a bug or Missing Documentation. It's just a typo when it explains the variable for middlescroll. It says "Downscroll is enabled," instead of, "Middlescroll is enabled." I'm sure nobody gets confused from this, but you should still change it just in case.
@ShadowMario @bbpanzu

**Comment by ShadowMario** [comment]
Minor spelling mistake, i win.

This was already fixed MULTIPLE days ago.
