### ISSUE TITLE
Custom second title credit bug

### ISSUE THREAD

**Issue by MrPurpleWhoLikesSpaghetti** [ShadowMario/FNF-PsychEngine#4025]
### Describe your bug here.

i was about to make second title in the mod credit and it has a black background.
![image](https://user-images.githubusercontent.com/98546734/151409750-ea01677b-00af-4d8a-a88a-6f20b8263e50.png)
i used one of the comments of https://github.com/ShadowMario/FNF-PsychEngine/issues/2731
but it didnt work

### Command Prompt/Terminal logs (if existing)

```bash
epic
epic::MrPurple::epic::https://www.youtube.com/watch?v=dQw4w9WgXcQ::0xFF125925
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows64

### Did you edit anything in this build? If so, mention or summarize your changes.

i added credits to mods/data

**Comment by CrusherMods** [comment]
remove the 0xFF maybe

**Comment by MrPurpleWhoLikesSpaghetti** [comment]
> remove the 0xFF maybe

it works! thank you

**Comment by ImaginationSuperHero528** [comment]
> remove the 0xFF maybe

> > remove the 0xFF maybe
> 
> it works! thank you

THE HELL?! You removed it? But it only works with is there?

**Comment by MrPurpleWhoLikesSpaghetti** [comment]
i dunno how it works

> > remove the 0xFF maybe
> 
> > > remove the 0xFF maybe
> > 
> > 
> > it works! thank you
> 
> THE HELL?! You removed it? But it only works with is there?

i dunno how it works, i removed it at somehow works
