### ISSUE TITLE
the intro doesnt go on the beat

### ISSUE THREAD

**Issue by MrPurpleWhoLikesSpaghetti** [ShadowMario/FNF-PsychEngine#4028]
### Describe your bug here.

same as here: https://github.com/ShadowMario/FNF-PsychEngine/issues/4005
but how to do it with a lua build?
![image](https://user-images.githubusercontent.com/98546734/151416398-d164e445-0ced-4785-b74e-5d5e6b31c939.png)
the video from this issue https://user-images.githubusercontent.com/48515908/151290853-ec07138a-dfc4-4e3e-a3f9-8f1f39a78133.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Steviegt6** [comment]
What is the point of this issue?

**Comment by PrismLight** [comment]
Yea... The engine sometimes displays the cases by one extra and leads to desync in the intro text. This can't be fixed on the build, but on the source, just go to the very end and change every case to whatever it is -1.

**Comment by MrPurpleWhoLikesSpaghetti** [comment]
> What is the point of this issue?

play https://user-images.githubusercontent.com/48515908/151290755-ac4f3f6e-29dc-4876-a527-a7c5a1ce58c9.mp4
then https://user-images.githubusercontent.com/48515908/151290853-ec07138a-dfc4-4e3e-a3f9-8f1f39a78133.mp4
and you will see the difference

**Comment by frantastic24** [comment]
Okay so you consciously made a duplicate issue?? And what does Lua have to do with this
