### ISSUE TITLE
Scripts to change specific lines of code?

### ISSUE THREAD

**Issue by PrismLight** [ShadowMario/FNF-PsychEngine#4029]
### What feature do you want to get added on the **base** engine?

A possible system to replace/add lines of code found in the HX files. So you add a LUA file in a new folder in mods called, "baseScripts" and add some lines like these.
```
replaceLine("HX file name", "Line of code to replace")
addLine("HX file name", "Line to add code after
```
You can make it only work on specific states like MainMenuState or StoryModeState?
This would seem like a really good feature to add to the engine, and it could really revolutionize softcode modding.
If it's too hard, then it's fine. But I'm really looking forward to seeing this in the engine if so!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Stilic** [comment]
lol its technically impossible.

**Comment by blue3212** [comment]
I don't think there is a way to adjust the source code that is already compiled.
There is such thing as "Self-modifying code" but I don't believe Haxe supports it

**Comment by frantastic24** [comment]
at that point you might as well use the source directly
