### ISSUE TITLE
error while loading shared libraries: libluajit-5.1.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by DaInfLoop** [ShadowMario/FNF-PsychEngine#4030]
### Describe your problem here.

After building from source using the GitHub Actions Workflow, I can't seem to open the Psych Engine file.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

Not much, you can view at https://github.com/DaInfLoop/Funkin-x-House-Vibe

**Comment by DaInfLoop** [comment]
I've also checked the field that allows you to run as an executable.

**Comment by Playertrip777** [comment]
Open the terminal in your game directory and type ./PsychEngine

**Comment by DaInfLoop** [comment]
That works, but now I'm getting this error:

"./PsychEngine: error while loading shared libraries: libluajit-5.1.so.2: cannot open shared object file: No such file or directory"

**Comment by Stilic** [comment]
> 

see https://stackoverflow.com/a/36684271

**Comment by Playertrip777** [comment]
In short, apt install luajit

**Comment by DaInfLoop** [comment]
Goddamn it-

```
./PsychEngine: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./PsychEngine)
```

**Comment by Playertrip777** [comment]
What version of Ubuntu are you using?
