### ISSUE TITLE
Custom Songs when choosed Gamemode

### ISSUE THREAD

**Issue by KyleOliverDeveloper** [ShadowMario/FNF-PsychEngine#4032]
### Describe your problem here.

So, i wanna make a song change when i select a certain gamemode. Ex.:
I have B-SIDES difficulty on my week, and when i choose B-SIDES,  it changes to the B-SIDES remix. While normal, hard and easy will stay the normal song.
How do i do that? 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Put the chart file in the base song's folder using the custom difficulty suffix and just change the song inside the .json

**Comment by KyleOliverDeveloper** [comment]
> Put the chart file in the base song's folder using the custom difficulty suffix and just change the song inside the .json

could you give me a image? i dont really know how to change .json files

**Comment by KyleOliverDeveloper** [comment]
Found how to do it, nevermind

**Comment by frantastic24** [comment]
basically copy the chart you're gonna use for your custom song and put it in the base song's data folder, name it the same as the base song and add your custom difficulty suffix, then open the .json and search for the song field and type your custom song there
![image](https://user-images.githubusercontent.com/95725102/151453590-abc523e6-4a52-47c4-b028-b28a3f55d23d.png)
![image](https://user-images.githubusercontent.com/95725102/151453722-1730048b-6d0d-4984-8f92-8fe0f639744c.png)
![image](https://user-images.githubusercontent.com/95725102/151454039-1dafa4ab-06dd-42c5-9cda-267c0f066bdc.png)

**Comment by KyleOliverDeveloper** [comment]
> basically copy the chart you're gonna use for your custom song and put it in the base song's data folder, name it the same as the base song and add your custom difficulty suffix, then open the .json and search for the song field and type your custom song there
> ![image](https://user-images.githubusercontent.com/95725102/151453590-abc523e6-4a52-47c4-b028-b28a3f55d23d.png)
> ![image](https://user-images.githubusercontent.com/95725102/151453722-1730048b-6d0d-4984-8f92-8fe0f639744c.png)
> ![image](https://user-images.githubusercontent.com/95725102/151454039-1dafa4ab-06dd-42c5-9cda-267c0f066bdc.png)

Holy Shit Thanks!
