### ISSUE TITLE
How to change the healthbar (and maybe other asset's) position? 

### ISSUE THREAD

**Issue by IntellectualPotato** [ShadowMario/FNF-PsychEngine#4033]
### Describe your problem here.

For example. if i want to have the healthbar on the left side of the screen or right side and not in the middle, how would i accomplish this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
`setProperty('healthBar.x', yourvalue);`

you can check [PlayState.hx](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/PlayState.hx) for other object names

**Comment by IntellectualPotato** [comment]
Thank you! is there also a way to set the scale? its just a teeny bit too big

**Comment by frantastic24** [comment]
```
scaleObject('healthBar', xscale, yscale);
scaleObject('healthBarBG', xscale, yscale);
```

**Comment by IntellectualPotato** [comment]
thank you so much!
you are very helpful to dumb people like me

**Comment by Rifemall** [comment]
Hi, I'm one who is building a mod based on the pibby glitch, I wanted to know how to do animation to the icons on the health bar in a script.
Thank you for anyone who will reply to your message.
