### ISSUE TITLE
Difficulty Remixes (like EX)

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [ShadowMario/FNF-PsychEngine#4034]
### What feature do you want to get added on the **base** engine?

I made an Issue "Difficulties with custom songs #3904" and I lit don't think understood what I was getting at! I know adding custom diffs is super easy now but I to make it so it can play a different song! Even @ShadowMario commented saying it's already possible but I don't see it in the week editor!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by CrusherMods** [comment]
in the json you can change it

**Comment by Murilo3127** [comment]
this is very easy to do (if you are not using source) create a folder with the name of the song example: Glitch, and drag its Json, then you create the Json file as glitch-hard, glitch-easy, glitch, In the custom difficulty music glitch you enter the file and change the name of the song (inside the Json) example: glitch-remix, and create the remix music folder with the difficulties (hard-easy-normal) And do the chart remix

**Comment by frantastic24** [comment]
if you were already told (multiple times, even) that this was possible, you did not need to create another issue, or at least ask for help and use the right tag

**Comment by crispyboi24** [comment]
use your eyes

**Comment by ImaginationSuperHero528** [comment]
> in the json you can change it like of the song
> this is very easy to do (if you are not using source) create a folder with the name of the song example: Glitch, and drag its Json, then you create the Json file as glitch-hard, glitch-easy, glitch, In the custom difficulty music glitch you enter the file and change the name of the song (inside the Json) example: glitch-remix, and create the remix music folder with the difficulties (hard-easy-normal) And do the chart remix
> if you were already told (multiple times, even) that this was possible, you did not need to create another issue, or at least ask for help and use the right tag
> use your eyes

Well, there's a bug where you have to have two versions of all the charts or it breaks and I don't want that! Plus for triggering it would be as easy as InstDiff and VocalsDiff

**Comment by frantastic24** [comment]
what bug? it works fine

**Comment by AdrianCD5** [comment]
I've already made this enhancement request before with #3730. The method of changing 'song' at the bottom of the json file is the best way of doing it, and if done correctly the only bug is that the high score for the difficulty will not show up (which is being fixed, I hope soon).
You were told before that it was possible, InstDiff has been denied as a feature already, this is a duplicate post.

**Comment by ImaginationSuperHero528** [comment]
> I've already made this enhancement request before with #3730. The method of changing 'song' at the bottom of the json file is the best way of doing it, and if done correctly the only bug is that the high score for the difficulty will not show up (which is being fixed, I hope soon). You were told before that it was possible, InstDiff has been denied as a feature already, this is a duplicate post.

Yeah, I only really wanted this to be a part of the base engine cause of an annoying bug with the charts. When it goes into that other song then you go to hard it crashes saying it doesn't see a hard chart. It's also the same with other difficulties you put for the week.json.
