### ISSUE TITLE
character editor crash

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#4041]
### Describe your bug here.

whenever I go into the character editor and try to load my png to make a json file I press reload image, it freezes, then it crashes. Please help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
don't label this as a bug if you're not going to provide details, either your png is wrong or you typed the png directory incorrectly

**Comment by creeperkidking** [comment]
if it helps my sprite sheet is 1 frame poses cuz I wanted to test them
also it worked before and then just stopped working
hope this help

**Comment by frantastic24** [comment]
Character .json and texture .XML files would help more

**Comment by creeperkidking** [comment]
i cant make the json file cuz the png wont load but i can send the xml

**Comment by creeperkidking** [comment]
[chchchchchchchchchch.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/7962267/chchchchchchchchchch.zip)
here

**Comment by frantastic24** [comment]
it's working fine here so this is probably something you did wrong when loading the image, or the image is too big for your PC
![image](https://user-images.githubusercontent.com/95725102/151635261-ac1e1e4d-19ff-47b9-a959-0453f2c7da40.png)

**Comment by creeperkidking** [comment]
How did you do caps it the image file name
it wont let me do that 
if your pasting it it wont let me do that ether

**Comment by creeperkidking** [comment]
well just found out i have to hold shift but thank you anyway
