### ISSUE TITLE
Hold notes disappearing outside of chart editor

### ISSUE THREAD

**Issue by StarSreak** [ShadowMario/FNF-PsychEngine#4042]
### Describe your bug here.

Whenever I try to chart my song, my hold notes disappear. I loaded into Fresh using freeplay, then switched to the name of my song. I charted the song, and saved the .json to the song's folder. When I exited the chart editor and played the song, all of the hold notes turned into normal notes, except the down notes for some reason. I have no idea why this is happening. I am using the latest gamebanana build, and the issue tab there told me to come over here. Also, can I still get the source code for my mod and post it on github, or will i need to compile the Psych Engine source code for that? I'm very new to modding.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a new mod folder and songs, made a new week but nothing else.

**Comment by ImaginationSuperHero528** [comment]
If the holds are too short it does that and I hate it but if there long then idk why that's happening.

**Comment by StarSreak** [comment]
> If the holds are too short it does that and I hate it but if there long then idk why that's happening.

wait, so all of my SHORT hold notes just disappear? that's actually just a really shitty bug. They need to fix that if that's the case.

**Comment by ImaginationSuperHero528** [comment]
> > If the holds are too short it does that and I hate it but if there long then idk why that's happening.
> 
> wait, so all of my SHORT hold notes just disappear? that's actually just a really shitty bug. They need to fix that if that's the case.

Yeah I found this out when I was charting for someone.

**Comment by StarSreak** [comment]
> > > If the holds are too short it does that and I hate it but if there long then idk why that's happening.
> > 
> > 
> > wait, so all of my SHORT hold notes just disappear? that's actually just a really shitty bug. They need to fix that if that's the case.
> 
> Yeah I found this out when I was charting for someone.

god damn, i'm gonna tell someone abt this on the discord. thanks for the heads up.
