### ISSUE TITLE
Deactivate and activate all the mods button

### ISSUE THREAD

**Issue by Wither362** [ShadowMario/FNF-PsychEngine#4046]
### What feature do you want to get added on the **base** engine?

I think, if you can make a button that deactivate the mods, would be possible to make a button that deactivates **ALL** the mods? And another that activates **ALL** the mods?

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by MrClogsworthYT** [comment]
u failed the test so no u lazy monke
