### ISSUE TITLE
Charater moving in a circle

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#4048]
### Describe your problem here.

how do i make the character fly in a circle?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MrPurpleWhoLikesSpaghetti** [comment]
you mean that character moving in a loop?

**Comment by frantastic24** [comment]
Vague description, explain

**Comment by ImaginationSuperHero528** [comment]
Like flying around in a circle?

**Comment by PDL2CGamejolt** [comment]
yes

**Comment by frantastic24** [comment]
i have a lua script that makes the opponent float like tails doll in sonic.exe if that's what you're looking for

**Comment by ImaginationSuperHero528** [comment]
and if I'm correct that should be a circle

> i have a lua script that makes the opponent float like tails doll in sonic.exe if that's what you're looking for

**Comment by frantastic24** [comment]
a circle, or just up and down if you prefer

**Comment by PDL2CGamejolt** [comment]
> i have a lua script that makes the opponent float like tails doll in sonic.exe if that's what you're looking for

yes

**Comment by frantastic24** [comment]
```
local floaty = 41.82;
local tailscircle = '';

function onUpdate()
	floaty = floaty+0.03

	if tailscircle == 'hovering' or tailscircle == 'circle' then
		setCharacterY('dad', getCharacterY('dad')+math.sin(floaty) * 1.3);
	end
	if tailscircle == 'circle' then
		setCharacterX('dad', getCharacterX('dad')+math.cos(floaty) * 1.3);
	end
end
```

**Comment by PDL2CGamejolt** [comment]
> ```
> local floaty = 41.82;
> local tailscircle = '';
> 
> function onUpdate()
> 	floaty = floaty+0.03
> 
> 	if tailscircle == 'hovering' or tailscircle == 'circle' then
> 		setCharacterY('dad', getCharacterY('dad')+math.sin(floaty) * 1.3);
> 	end
> 	if tailscircle == 'circle' then
> 		setCharacterX('dad', getCharacterX('dad')+math.cos(floaty) * 1.3);
> 	end
> end
> ```

it didnt work, i think this was source code

**Comment by PDL2CGamejolt** [comment]
> > ```
> > local floaty = 41.82;
> > local tailscircle = '';
> > 
> > function onUpdate()
> > 	floaty = floaty+0.03
> > 
> > 	if tailscircle == 'hovering' or tailscircle == 'circle' then
> > 		setCharacterY('dad', getCharacterY('dad')+math.sin(floaty) * 1.3);
> > 	end
> > 	if tailscircle == 'circle' then
> > 		setCharacterX('dad', getCharacterX('dad')+math.cos(floaty) * 1.3);
> > 	end
> > end
> > ```
> 
> it didnt work, i think this was source code

OHHHHHHHH! I UNDERSTAND NOW

**Comment by PDL2CGamejolt** [comment]
> ```
> local floaty = 41.82;
> local tailscircle = '';
> 
> function onUpdate()
> 	floaty = floaty+0.03
> 
> 	if tailscircle == 'hovering' or tailscircle == 'circle' then
> 		setCharacterY('dad', getCharacterY('dad')+math.sin(floaty) * 1.3);
> 	end
> 	if tailscircle == 'circle' then
> 		setCharacterX('dad', getCharacterX('dad')+math.cos(floaty) * 1.3);
> 	end
> end
> ```

how do i use this

**Comment by PDL2CGamejolt** [comment]
It worked!
