### ISSUE TITLE
A way to add/change difficulties through Downloaded/LUA

### ISSUE THREAD

**Issue by GMDBrandon** [ShadowMario/FNF-PsychEngine#405]
As a person who _somehow_ did the steps wrong and now I can't recompile anything relating to Friday Night Funkin', this would be very useful. It was done on Modding Plus, so it can be done on Pysch Engine.
This doesn't have to be in the next minor or major update, and no this isn't an order or command. It would just be helpful to do for me since, again, I can't recompile.

## ways you could even do it like i know you're asking how shadowmario
Maybe through a .json file with the same code as the source code.

## example crap
Let's say I want to add "Lunatic" difficulty (from V.S. Cirno)
I'd find "difficulties.json" (example) and open it.
There, I'd see the same code as in the source code and I'd put the new difficulty code in "difficulties.json".

{
	// [Difficulty name, Chart file suffix]
	public static var difficultyStuff:Array<Dynamic> = [
		['Easy', '-easy'],
		['Normal', ''],
		['Hard', '-hard']
                ['Lunatic', '-lunatic'] //cool new difficulty
	]
}

The rest would be in the tutorial of adding a difficulty.

**Comment by bdidk235** [comment]
you for got the ,

**Comment by bdidk235** [comment]
Here's the fix (hopefully)

{
// [Difficulty name, Chart file suffix]
public static var difficultyStuff:Array = [
['Easy', '-easy'],
['Normal', ''],
['Hard', '-hard'],
['Lunatic', '-lunatic'] //cool new difficulty
]
}

**Comment by ShadowMario** [comment]
oh god more jsons lmao

**Comment by GMDBrandon** [comment]
you could also do it thorigh .jsonc but normal .json is fine too

**Comment by GMDBrandon** [comment]
> > you could also do it through .jsonc but normal .json is fine too
> 
> Why would you ever explicitly use JSONC?

used it on modding plus and it used .jsonc for some things

**Comment by drakonieyah** [comment]
> > > you could also do it through .jsonc but normal .json is fine too
> > 
> > 
> > Why would you ever explicitly use JSONC?
> 
> used it on modding plus and it used .jsonc for some things

Modding plus is the same engine that uses vanilla input system. That should be enough to not use it.

**Comment by FuseIsHere813** [comment]
> > > > you could also do it through .jsonc but normal .json is fine too
> > > 
> > > 
> > > Why would you ever explicitly use JSONC?
> > 
> > 
> > used it on modding plus and it used .jsonc for some things
> 
> Modding plus is the same engine that uses vanilla input system. That should be enough reason to not use it.

In 4.0.0 Modding Plus, they had the kade engine input if you're wondering.

**Comment by Spongeyboi** [comment]
> > > > you could also do it through .jsonc but normal .json is fine too
> > > 
> > > 
> > > Why would you ever explicitly use JSONC?
> > 
> > 
> > used it on modding plus and it used .jsonc for some things
> 
> Modding plus is the same engine that uses vanilla input system. That should be enough reason to not use it.

Thank goodness for the other engines

**Comment by SupaFromSupasShow** [comment]
> {
> // [Difficulty name, Chart file suffix]
> public static var difficultyStuff:Array = [
> ['Easy', '-easy'],
> ['Normal', ''],
> ['Hard', '-hard']
> ['Lunatic', '-lunatic'] //cool new difficulty
> ]
> }

imma use this

**Comment by Steviegt6** [comment]
> > > you could also do it through .jsonc but normal .json is fine too
> > 
> > 
> > Why would you ever explicitly use JSONC?
> 
> used it on modding plus and it used .jsonc for some things
`.jsonc` is the reject child to `.json`. Literally syntax sugar, there is no reason to have a special file format for what should be core functionality.
