### ISSUE TITLE
It crashed for no reason! (Only in the Un-Released Build)

### ISSUE THREAD

**Issue by MasterDirector99** [ShadowMario/FNF-PsychEngine#4050]
### Describe your bug here.

How did it crash when I press enter for me? I really don't know why, but you'll figure it out!
**(I am using the latest actions build which is the latest commit)**
https://user-images.githubusercontent.com/74268152/151588856-ebdbbf3c-e37a-4a8f-a13d-d5c6d4abc5d0.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't edit anything

**Comment by frantastic24** [comment]
Seems like some asset(s) may have failed to load, maybe try with another fresh build

**Comment by MasterDirector99** [comment]
I tried reinstalling it but it didn't work, It only crashed in the latest actions build, but not older versions!

**Comment by bdidk235** [comment]
I think it's because of the freaky on a friday night achievement, I was trying also trying to get in the game, but it also crashed!

**Comment by bdidk235** [comment]
I thought I messed something up, but it was from psych engine itself.

**Comment by frantastic24** [comment]
Action builds are more so for testing and aren't guaranteed to work properly, just get another one

**Comment by MasterDirector99** [comment]
@ShadowMario (Sorry that I pinged you, But you need to fix the crash)

**Comment by ShadowMario** [comment]
Should be fixed on the latest push
