### ISSUE TITLE
Crash on achievement menu

### ISSUE THREAD

**Issue by superpowers04** [ShadowMario/FNF-PsychEngine#4052]
### Describe your bug here.

The game instantly crashes upon going into the Achievement menu, apparently it also crashes at night on a friday, maybe these are linked somehow?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by MasterDirector99** [comment]
It's now fixed

**Comment by superpowers04** [comment]
Closed due to https://github.com/ShadowMario/FNF-PsychEngine/commit/ffb67efcf83ac1d857a6c8cdb2e90522e6f2b944
