### ISSUE TITLE
how to add png cutscenes

### ISSUE THREAD

**Issue by WhittyButHuman** [ShadowMario/FNF-PsychEngine#4053]
### Describe your problem here.

i dont how to add png cutscenes like the garcello or whitty mod

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ImaginationSuperHero528** [comment]
-_- just look it up on youtube

**Comment by Pico8430** [comment]
Making png cutscenes it's maybe possible, but i don't really know too much about PNG cutscenes, and other mods use the source code for that. I recommend you to make a .mp4 video on lua.

**Comment by XS09-dev** [comment]
Actually I find the source code way to adding as cutscene way easier lol.
