### ISSUE TITLE
How to add trios

### ISSUE THREAD

**Issue by SonicFNaF** [ShadowMario/FNF-PsychEngine#4054]
### What is your question?

How do I add trios in latest source code update?

**Comment by ImaginationSuperHero528** [comment]
da hell are trios?

**Comment by AlansGames** [comment]
i think they mean like 3 opponents in one song

**Comment by Pico8430** [comment]
You can try with putting an opponent replaced with GF and then 2 characters with idle and an alt idle, im not pretty sure on how it really works tho. It maybe would have another way to do so.

**Comment by ImaginationSuperHero528** [comment]
[Click here](https://discord.com/channels/922849922175340586/922851578996744252/931544771195985940) for a link to download a script.

**Comment by frantastic24** [comment]
that's a discord channel

**Comment by ImaginationSuperHero528** [comment]
> that's a discord channel

Where you can find what your asking for...

**Comment by frantastic24** [comment]
Not only does it sound sketchy as hell, but you could also just send the damn file
