### ISSUE TITLE
Psych Engine Fucking Compiling Error

### ISSUE THREAD

**Issue by OHsit** [ShadowMario/FNF-PsychEngine#4055]
### What is your question?

When I compile this error is shown to me
source/MainMenuState.hx:126: characters 121-124 : Float should be Int
source/MainMenuState.hx:126: characters 121-124 : For optional function argument 'Size'
How repier This???

**Comment by blue3212** [comment]
Going to need more information on what you changed, cause in the current version , 126 has
`FlxG.camera.follow(camFollowPos, null, 1);`
Which does not make sense given the error codes.
