### ISSUE TITLE
"Null Object Reference"

### ISSUE THREAD

**Issue by Fridox-lol** [ShadowMario/FNF-PsychEngine#4057]
### Describe your bug here.

I don't know why, instead of going in the main menu (the one with story mode, freeplay, mods, awards, credits, donate and options) it says "Null Object Reference" and crash the game (i'm using the last version)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't edit anything.

**Comment by ShadowMario** [comment]
Send the crash trace from the command prompt/terminal

**Comment by ImaginationSuperHero528** [comment]
Last version? Do you mean oldest?

**Comment by ShadowMario** [comment]
Should be fixed on the latest push

**Comment by Fridox-lol** [comment]
> Last version? Do you mean oldest?

No, the latest version (0.5.1)

**Comment by Fridox-lol** [comment]
fixed it

**Comment by ihatethisprocess** [comment]
how do you fix it? i changed the color of the notes from the files (changing the hue of the note assets) and didn't mess with the code but it started crashing and doing that. is it like a value that makes it to where if it has a different color from base game it crashes????

**Comment by ihatethisprocess** [comment]
![NOTE_assets](https://user-images.githubusercontent.com/119077877/204050840-a05bb9de-059a-4cc3-8613-b9d276993b21.png)
![image](https://user-images.githubusercontent.com/119077877/204050895-f32975b2-c5b5-4cd9-88bc-0c6d7e7cc880.png)

**Comment by Fridox-lol** [comment]
i don't remember this was almost a year ago
