### ISSUE TITLE
custom discord rich presence for the mods folder

### ISSUE THREAD

**Issue by impostor5875** [ShadowMario/FNF-PsychEngine#4059]
### What feature do you want to get added on the **base** engine?

maybe add custom discord rich presence support for the mods folder, if possible. it's kind of annoying when making a mod and the rich presence always says "psych engine" with no work arounds

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
That's because the Application icon can only be changed when you start up the Discord API, which only happens when you open the game.

**Comment by impostor5875** [comment]
> That's because the Application icon can only be changed when you start up the Discord API, which only happens when you open the game.

oh ok
