### ISSUE TITLE
need some help a stage ShadowMario

### ISSUE THREAD

**Issue by lox333c** [ShadowMario/FNF-PsychEngine#406]
I want to create a tankman stage for the mod and I have
assets/stages/tankstage.lua:16: '='expected near'<eof>'

here is what is written in lua:

function onCreate()
	-- background shit
		makeLuaSprite('tank back', 'tank back', -600, -300);
	setLuaSpriteScrollFactor('tankback', 0.9, 0.9);
	
	makeLuaSprite('tankfront', 'tankfront', -650, 600);
	setLuaSpriteScrollFactor('tankfront', 0.9, 0.9);
		scale Object('stagefront', 1.1, 1.1);

	end

	addLuaSprite('tankback', false);
	addLuaSprite('tankfront', false);
	
	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage

eof

please help ShadowMario (p.s: i russian)

**Comment by ShadowMario** [comment]
Post the full script
