### ISSUE TITLE
Is it possible to add winning icons with .lua?

### ISSUE THREAD

**Issue by supajimmy** [ShadowMario/FNF-PsychEngine#4063]
### What is your question?

So what I had been thinking is that when the heath is over a X amount or under a X amount you can switch the .png file to show that a icon is winning like a switch .png script that is being applied to the icons also put the prelode script to both of the winning .pngs so a computer does not have a stroke trying to lode them. also no this is not asking to add winning icons to the base engine I am just saying is this possible with the way script.lua is set up currently?

**Comment by frantastic24** [comment]
there are scripts in discussions

**Comment by ImaginationSuperHero528** [comment]
Yes there are
