### ISSUE TITLE
Hold notes come out shorter when I put json in

### ISSUE THREAD

**Issue by Shammal** [ShadowMario/FNF-PsychEngine#4070]
### Describe your bug here.

Hold notes come out shorter than usual when on certain bpms. When I make a hold note in the chart editor then play the chart, it comes out normal. When I actually put the json of the chart in the files, though, the hold notes come out shorter. This has been an issue with both kade and psych engine.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by cherryiguess** [comment]
if you converted a kade engine chart to a pysch engine (dragging it into the folder), they have different charting system sort of, which is why this happens

**Comment by Pico8430** [comment]
Well i already had this problem before when making charts, but since it's not a problem at all im fine with it.
Don't know if there's any solution to it.
