### ISSUE TITLE
Null object

### ISSUE THREAD

**Issue by HaxLua** [ShadowMario/FNF-PsychEngine#4072]
### Describe your problem here.

It goes to line 145 it looks like an achievement error. From softcoded achievements?

![image](https://user-images.githubusercontent.com/76410593/151641001-a430a6d1-33dd-43e4-bf8c-a5107edba18c.png)

# Log

![image](https://user-images.githubusercontent.com/76410593/151641043-5b59d039-d2b3-477f-bea5-0a6038f82962.png)

# Line

![image](https://user-images.githubusercontent.com/76410593/151641107-7124751e-3c12-440e-af76-17ebb54367a8.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited TitleState

**Comment by ShadowMario** [comment]
Should be fixed on the latest push
