### ISSUE TITLE
time bar in pshych ( yes i have alredy the source)

### ISSUE THREAD

**Issue by facundomax** [ShadowMario/FNF-PsychEngine#4079]
### Describe your problem here.

in the psych engine there is a time bar (dhu) I would like to know how to modify it in the middle of a song, I would like to know how to extend the time bar in the middle of the song and with sudden movements (something like bob & bosip ex but with movements ).

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i don't edit this biuld

**Comment by PrismLight** [comment]
I think it's better you put this in discussions instead of issues. Most people only look at discussion posts.
Also, it's impossible to extend the time because it would have to refresh the whole play state all over again and possibly lead to a crash. Idk I haven't tried or figured out the code to this.

**Comment by facundomax** [comment]
I think you misunderstood me, by extending the time bar I meant that the progress bar goes backwards like in bob and bosip AND EXTEND THE TIME, not the time bar because that is impossible

**Comment by facundomax** [comment]
a friend told me that you can make a fake time bar for that and he didn't tell me how to do it and so far he doesn't want to do it xd

**Comment by facundomax** [comment]
Why you close my question?

**Comment by MINCREFAT** [comment]
Why is this closed + What properties are in time bar?
