### ISSUE TITLE
Game crashes on custom character death & song restart

### ISSUE THREAD

**Issue by aflacc** [ShadowMario/FNF-PsychEngine#4081]
### Describe your bug here.

The game crashes when you die while using a custom character for the player, even tho I have a death animation it just crashes. I am running on latest build no code

Its crashing when i restart the song on base built in songs

Weird thing is is that I'm not even using any lua files. It just crashes

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only added a custom character

**Comment by keanu64github** [comment]
make sure its firstDeath - start of death. deathLoop - loop anim. and deathConfirm - enter clicked. also if i can get some credit for helping that would be cool lmao :D
