### ISSUE TITLE
Game crashes when tried to do flxObject commands to bf in lua psych setproperty like maxvelocity and drag

### ISSUE THREAD

**Issue by Rorutop** [ShadowMario/FNF-PsychEngine#4082]
### Describe your bug here.

I tried to make platformer mechanics in lua, but when i tried these commands it crashes except the velocity and acceleration
any way to fix this?
```
setProperty('boyfriend.maxVelocity', speed, 420)
    setProperty('boyfriend.drag', speed * 4, speed * 4)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by flashintv** [comment]
that's easy to answer, you're just inputing 2 values instead of one, heres the fix
```
setProperty('boyfriend.maxVelocity.x', speed)
setProperty('boyfriend.maxVelocity.y', 420)
setProperty('boyfriend.drag.x', speed * 4)
setProperty('boyfriend.drag.y', speed * 4)
```
