### ISSUE TITLE
custom stage problem

### ISSUE THREAD

**Issue by pln2009** [ShadowMario/FNF-PsychEngine#4085]
### Describe your problem here.

i've been trying to make a mod on some unused songs in the ylyl mod but when i try to load in the song i get this error:
![Immagine 2022-01-29 132308](https://user-images.githubusercontent.com/76397093/151660895-5bd4af6d-d157-4386-983d-6c8b2b9e0b0c.png)
 
[jimmyroom.lua.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7963650/jimmyroom.lua.txt)
[jimmyroom.json.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7963651/jimmyroom.json.txt)
 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by HaxLua** [comment]
two ends. 
![image](https://user-images.githubusercontent.com/76410593/151662111-a3ae100b-7ec3-4075-8f4c-ed192a696181.png)

**Comment by HaxLua** [comment]
```
function onCreate()
	-- background shit
	makeLuaSprite('daRoom', 'daRoom', -600, -300);
	setScrollFactor('daRoom', 0.9, 0.9);

	addLuaSprite('daRoom', false);
	
	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end 
```

**Comment by pln2009** [comment]
1. why didn't it work before
2. thank you
