### ISSUE TITLE
stage with shaders

### ISSUE THREAD

**Issue by nintendofan44** [ShadowMario/FNF-PsychEngine#4091]
### What is your question?

how do i make a stage that has some sort of shader in it with the shader system that psych engine has rn

**Comment by nintendofan44** [comment]
i tried doing it with the dave and bambi stuff but it looks bad
![image](https://user-images.githubusercontent.com/85742902/151665024-31481d5e-abc9-4b61-b38a-fc32bcf198d7.png)

**Comment by ByronisJoan** [comment]
If You are On Lua And On the Latest Update

Copy and Paste This Under function onCreate()

copy and Paste this to the 
function onCreatePost()
	addGlitchEffect('name', 2, 2);
end
