### ISSUE TITLE
Awards 

### ISSUE THREAD

**Issue by KyleOliverDeveloper** [ShadowMario/FNF-PsychEngine#4093]
### What is your question?

How do i make a custom award without source code? Do i need to change anything in the file pack.json??

![image](https://user-images.githubusercontent.com/94708825/151666779-a9889936-ac18-43bc-94e0-69583f712438.png)

![image](https://user-images.githubusercontent.com/94708825/151666785-3e140063-b5fc-4326-910c-10ae5df70fd8.png)

**Comment by Gui-iago** [comment]
you can't

**Comment by KyleOliverDeveloper** [comment]
> you can't

bru

**Comment by KyleOliverDeveloper** [comment]
then how do ppl do it

**Comment by Gui-iago** [comment]
on source

**Comment by OHsit** [comment]
You can add  custom award O N L Y a source. Without source you can't

**Comment by KyleOliverDeveloper** [comment]
> You can add custom award O N L Y a source. Without source you can't

shit

**Comment by ImaginationSuperHero528** [comment]
> > You can add custom award O N L Y a source. Without source you can't
> 
> shit

There used to be custom achievements but they broke so there removed temporarily
