### ISSUE TITLE
Big bug in the 'Events'

### ISSUE THREAD

**Issue by Dolari27** [ShadowMario/FNF-PsychEngine#4097]
### Describe your bug here.

Hi,
When I try to use the 'Change Character' in 'Events' it crashes when i try to do an input. this happens on the others except 'nothing'.
To fix this, I just used 'Nothing' and then did what I needed, then just changed it to what i need, there is also a lot of crashes
e.g closing the debug menu.
Thank you.

-Dolari27

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added some songs, and partway of a chart. this happens for all my mods on psych engine. please fix lol.

**Comment by ShadowMario** [comment]
It sounds like an issue on YOUR character, not the engine itself.
Your character is probably missing an idle animation.
