### ISSUE TITLE
WebM Player for Better Cross Compatibility

### ISSUE THREAD

**Issue by KirbyKid256** [ShadowMario/FNF-PsychEngine#4098]
### What feature do you want to get added on the **base** engine?

Hi, I've been trying to make a macOS Port of Psych Engine, and one of the things that I think would help with cross-compatibility would be a way to use a WebM player in the mod as another option instead of the MP4 player. I've been trying to do it myself by merging some source code from the Imposter mod since I was able to successfully port that to Mac with little bugs, however, I don't think I'm getting anywhere with that. I've also been trying to make a new function that would play a WebM video via a Lua script. So in short, some more code should be added to play either an MP4 video, a WebM video, or both in the same mod.

I also found some other weird bugs while porting the engine to mac, but I think that should go in a separate post. I'm currently focused on the WebM player, and/or optimizing VLC to work with Mac as well.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by keanu64github** [comment]
i literally used mp4 on webm, webm works bad on mac
