### ISSUE TITLE
Awards Creator

### ISSUE THREAD

**Issue by KyleOliverDeveloper** [ShadowMario/FNF-PsychEngine#4103]
### What feature do you want to get added on the **base** engine?

I wanted the creators to make a awards creator, for the people who cannot code in source code.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ByronisJoan** [comment]
Stage Editor 

> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Stage Editor, 6K+ support, and winning icons.

Bruh He Will Make Stage editor Later

**Comment by KyleOliverDeveloper** [comment]
> Stage Editor
> 
> > ### To test your sight, and reliability, please select the option of what should NOT be requested.
> > Stage Editor, 6K+ support, and winning icons.
> 
> Bruh He Will Make Stage editor Later

dude you are so dumb. Read what it requests. It asks for what should NOT be added. You dumb

**Comment by MaxlionButMyNameIsTakenSoThisIsmyName** [comment]
> Stage Editor
> 
> > ### To test your sight, and reliability, please select the option of what should NOT be requested.
> > Stage Editor, 6K+ support, and winning icons.
> 
> Bruh He Will Make Stage editor Later

Not
/nɒt/
Adverb
1.
used with an auxiliary verb or ‘be’ to form the negative.
"he would not say"
2.
used as a short substitute for a negative clause.
"maybe I'll regret it, but I hope not"
