### ISSUE TITLE
Replacing gf in tutorial with another character (no hard-coding please)

### ISSUE THREAD

**Issue by Kasey-py** [ShadowMario/FNF-PsychEngine#4105]
### Describe your problem here.

Is it possible to replace gf in tutorial (i'm using naenae-speaker) without replacing the actual tutorial assets? Any help appreciated.

Please keep in mind I am a beginner when it comes to soft-coded modding, and have very little experience.

![image](https://user-images.githubusercontent.com/92189435/151678037-80c6f304-49d2-455e-af7a-784d7e4b798b.png)
![image](https://user-images.githubusercontent.com/92189435/151678047-4264dd52-6c15-4de0-923f-8a7c5f738fea.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by frantastic24** [comment]
Your character's name must start with `gf-` iirc

**Comment by Kasey-py** [comment]
Worked, thank you.

**Comment by frantastic24** [comment]
Yes

**Comment by Xenolinks** [comment]
> Yes, it's a prefix you use for all gf characters if you need them as opponents
And if i want to use him as a gf i should just change the "gf" in the debug menu?
