### ISSUE TITLE
MakeLuaSprite on HUD Layer?

### ISSUE THREAD

**Issue by trippinreal** [ShadowMario/FNF-PsychEngine#4107]
### What is your question?

i'm trying to make a feature similar to the 'Advertisement' mechanic from Bob's Onslaught, in which ads appear infront of the notes, presumably on the HUD layer of the game, however, I can't seem to find a way to add sprites to the HUD layer. is there a way to do this? 

Working on LUA code, i'd rather not use the source if possible to keep the mod size low. 

thankyou ^^

**Comment by frantastic24** [comment]
`setObjectCamera('tag', 'camHUD');`
If `camHUD` doesn't work try `other`

**Comment by trippinreal** [comment]
thank you so much man, setting it to 'other' does the trick :)

**Comment by DacroyleYT** [comment]
i know this is closed but if you want it to zoom with the hud use `setObjectCamera('tag', 'HUD')`
If "HUD" doesnt work try using "hud"

**Comment by TheKitBoi** [comment]
the make it camHUD
