### ISSUE TITLE
That one tabi thing

### ISSUE THREAD

**Issue by matt-sudo-jpg** [ShadowMario/FNF-PsychEngine#4109]
### What is your question?

basicly how do i do [this?](https://youtube.com/clip/UgkxL2x_iUibHxASK1dpsap-CmGJoRj9MPLm)

or is it only for KE

### MORE BETTER DESCRIPTION:

So in the tabi mod if you have low health a vignett will be more and more visible, like 100% Health you cant see but like in 50% visible but not that much , and a 1/0% its visible

I wanna stop using the lua form and use sc to do it

**Comment by KutikiPlayz** [comment]
you mean the moving health bar or the health drain?

health drain is super easy and you can find thousands of threads for how to do that, the moving health bar I'd suggest you just look in the tabi source and find the code for it, and then just copy paste to your mod

**Comment by PoleyMagik** [comment]
I think he means the minor shader effect. It's chromatic aberration. I think it's in the latest commit with lua.

**Comment by matt-sudo-jpg** [comment]
> you mean the moving health bar or the health drain?
> 
> health drain is super easy and you can find thousands of threads for how to do that, the moving health bar I'd suggest you just look in the tabi source and find the code for it, and then just copy paste to your mod

i just updated it for a better description and yes i do know how to do health drain, maybe ill look into moving the health bar

**Comment by matt-sudo-jpg** [comment]
> I think they mean the minor shader effect. It's chromatic aberration. I think it's present in the latest commit with lua support.

no not chromatics
