### ISSUE TITLE
Help! I've literally screwed myself! :( please add a feature where you can't set things as they same keybind!

### ISSUE THREAD

**Issue by SadIndianhecker** [ShadowMario/FNF-PsychEngine#4111]
### Describe your bug here.

So on the main menu, I've set all my keybinds to A and left, and now I'm just stuck. I can't add characters, nothing :( https://www.youtube.com/watch?v=XAxl_0mcZjA

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
type `%appdata%` into your windows search bar and hit enter, then go to `ShadowMario/PsychEngine/ninjamuffin99` and delete `controls_v2.sol`, it will restore controls to default

**Comment by SadIndianhecker** [comment]
thx!
