### ISSUE TITLE
problem!

### ISSUE THREAD

**Issue by cameronthekibryya** [ShadowMario/FNF-PsychEngine#4113]
### Describe your problem here.

I'm having problems with my port
![Screenshot 2022-01-29 181152](https://user-images.githubusercontent.com/92703353/151681827-41d7f41d-6885-4e33-9106-6ae068e65d4a.png)
t

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a new .hx file here's the code

**Comment by cameronthekibryya** [comment]
default:
									var poop:String = Highscore.formatSong(daChoice, 1);

									trace(poop);
						
									PlayState.SONG = Song.loadFromJson(poop, daChoice);
// I think the storyDiff is wrong
									PlayState.isStoryMode = true;
									PlayState.storyDifficulty = 2;
						
									PlayState.storyWeek = 1;
									LoadingState.loadAndSwitchState(new PlayState());

**Comment by keanu64github** [comment]
uhhh psych doesn't support hx

**Comment by keanu64github** [comment]
only if ur using source code

**Comment by cameronthekibryya** [comment]
I'm am using source code

**Comment by MaxlionButMyNameIsTakenSoThisIsmyName** [comment]
You just set the difficulty to a null value.

**Comment by cameronthekibryya** [comment]
> You just set the difficulty to a null value.

source/PlayMenuState.hx:238: characters 38-42 : On static platforms, null can't be used as basic type Int
source/PlayMenuState.hx:238: characters 38-42 : On static platforms, null can't be used as basic type Int

**Comment by cameronthekibryya** [comment]
or maybe I'm doing something wrong

**Comment by cameronthekibryya** [comment]
now it says
![Screenshot 2022-01-31 114535](https://user-images.githubusercontent.com/92703353/151845509-1e771435-b904-48b3-9c5e-5435aa19b7f3.png)
