### ISSUE TITLE
Add Camera Zoom event doesn't zoom out

### ISSUE THREAD

**Issue by BombasticTom** [ShadowMario/FNF-PsychEngine#4114]
### Describe your bug here.

The Camera stays static when zoomed until you press a note in 0.5.1 (current stabile build)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing.

**Comment by BombasticTom** [comment]
also could you please fix the issue when you can't exit from the game the moment you get an error in lua code (issue for fullscreen players only)

**Comment by tposejank** [comment]
> also could you please fix the issue when you can't exit from the game the moment you get an error in lua code (issue for fullscreen players only)

they can't fix that

**Comment by BombasticTom** [comment]
> > also could you please fix the issue when you can't exit from the game the moment you get an error in lua code (issue for fullscreen players only)
> 
> they can't fix that

what about the Camera zoom though?

**Comment by cherryiguess** [comment]
> The Camera stays static when zoomed until you press a note in 0.5.1 (current stabile build)

im pretty sure this is intentional

**Comment by BombasticTom** [comment]
> > The Camera stays static when zoomed until you press a note in 0.5.1 (current stabile build)
> 
> im pretty sure this is intentional

what i'm trying to say is that the camera zooms and doesn't zoom out until you press a note.

**Comment by BombasticTom** [comment]
that's stupid now i have to do it complicated way by making the bf press a note while stunned

**Comment by frantastic24** [comment]
Or you can use defaultCamZoom like you're supposed to

**Comment by BombasticTom** [comment]
lmao no i got ratiod 😭😭
