### ISSUE TITLE
Sys_error("export/debug/windows/obj/include//MainMenuState.h: Permission denied")

### ISSUE THREAD

**Issue by Scorpion105951** [ShadowMario/FNF-PsychEngine#4118]
### Describe your problem here.

I make psych engine modded and got this error:
Sys_error("export/debug/windows/obj/include//MainMenuState.h: Permission denied")
I turn off Avast and try again, but this no help 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i edited Healthicon.hx and add winning icons and edited main menu,

**Comment by maxisepYT1** [comment]
It usually happens when the build **bugs** when it tries to compile the game, it's rare, it also happened to me, the only thing I did was download the source code again and compile it before making any changes.
I suggest that every time you make a **big change** you compile it.

**Comment by Scorpion105951** [comment]
> It usually happens when the build **bugs** when it tries to compile the game, it's rare, it also happened to me, the only thing I did was download the source code again and compile it before making any changes. I suggest that every time you make a **big change** you compile it.

Thx u its works
