### ISSUE TITLE
Weird error when trying to compile

### ISSUE THREAD

**Issue by TrafficKid** [ShadowMario/FNF-PsychEngine#4119]
### Describe your problem here.

Everytime I try compiling regardless of which version I pick I get this strange error, It's hard to describe It since I don't know what triggered It and It's there everytime
![image](https://user-images.githubusercontent.com/84630346/151689835-6003b2de-ba57-4a75-ab9c-bc0cce279d20.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ThatDisabledKid** [comment]
you need to install visual studio 2019 and the tools here look at this for [more info](https://github.com/KadeDev/Kade-Engine/blob/stable/docs/troubleshooting.md) [building](https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md)
