### ISSUE TITLE
Problem "NOT HTML5"

### ISSUE THREAD

**Issue by Theoyeah** [ShadowMario/FNF-PsychEngine#4122]
### Describe your problem here.

I have added the loading screen by deleting #NO_PRELOAD_ALL and #end in LoadingState.hx.
But there the problem:
The loading screen will work for any device "desktop and etc" but when the loading screen is appear, but a  song in mods donesn't load at all but with like week 1 it works
How to i fix that ?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i edited MainMenuState.hx and deleted #NO_PRELOAD_ALL and #end  in LoadingState.hx

**Comment by ShadowMario** [comment]
The loading screen is NOT meant to be used on Desktop, there's no real use for it on Desktop, the loading screen is there for DOWNLOADING the assets from the central server on Browser builds of the game.
