### ISSUE TITLE
instrumental song error

### ISSUE THREAD

**Issue by CyberProd235** [ShadowMario/FNF-PsychEngine#4127]
### Describe your bug here.

When I have an instrumental song, and load it, it dosen't load the chart, or the song. Instead, it lags the chart and it repeats every second, but dosent work. The timer also just says 0:00
![Friday Night Funkin'_ Psych Engine 1_30_2022 9_06_25 AM](https://user-images.githubusercontent.com/95111275/151703313-95fcbb3d-5bb2-4764-879f-27f804f7f733.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Instrumental not found

**Comment by trollgeman** [comment]
you probably made the inst a mp3

**Comment by yahya9912** [comment]
make sure the inst is .ogg and not .mp3 and make sure the inst is in mods/songs/your song name

**Comment by frantastic24** [comment]
Also make sure it was converted/exported properly, there's been a bunch of "bug reports" where the issue was a bad file

**Comment by Pico8430** [comment]
Common problem, audio file has to be .ogg to work and named "Inst".
