### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by Masterlittlejoe** [ShadowMario/FNF-PsychEngine#4134]
### Describe your bug here.

When I compile the game, in powershell, it gives an error. I have no idea what it means, but I did not edit anything. The only thing I added was a character spritesheet, json, and xml. Deleting those assets does nothing. I don't get what's happening, but if this is happening to only me then I need some help. If it's happening to other people, this is a bug. Thanks.
![image](https://user-images.githubusercontent.com/61671529/151709071-5d4378c1-63cf-452c-9043-433a631ab096.png)

### Command Prompt/Terminal logs (if existing)

```bash
PS C:\Users\maste\Downloads\bread pie r source code\FNF-PsychEngine-0.5.1> lime test windows
source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only added a character spritesheet, json and xml.

**Comment by SrtHero278** [comment]
In case you haven't found out, you need to get the latest version instead of 4.1.5.
https://haxe.org/download/

**Comment by Masterlittlejoe** [comment]
> In case you haven't found out, you need to get the latest version instead of 4.1.5. https://haxe.org/download/

Oh, I didn't know that actually. Thanks!
