### ISSUE TITLE
VLC should be a submodule

### ISSUE THREAD

**Issue by pjalsGit** [ShadowMario/FNF-PsychEngine#4136]
### Describe your bug here.

VLC should be a submodule in this repository. I'm not sure if this is a bug or a feature request.

### Command Prompt/Terminal logs (if existing)

```bash
oh lol this is for bugs about the game
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Stilic** [comment]
no

**Comment by pjalsGit** [comment]
why

**Comment by Stilic** [comment]
its just work now
