### ISSUE TITLE
Error with title

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#4140]
### Describe your bug here.

this glitch happens when im using a loading screen it was used for the game not to lag but it crashes when i select story mode or freeplay saying 
![image](https://user-images.githubusercontent.com/56323671/151706153-4a2486b8-b2cc-49b9-b7e9-2e563e8caaf8.png)
![image](https://user-images.githubusercontent.com/56323671/151706222-790dfe45-0752-4ac5-a66b-275a7ed55203.png)
![image](https://user-images.githubusercontent.com/56323671/151706231-efefe5c2-1496-4899-acf3-41add1e51366.png)
then this error happens when i select those buttons

### Command Prompt/Terminal logs (if existing)

```bash
it does all this properly (above)
 Creating library ApplicationMain.lib and object ApplicationMain.exp
source/Cache.hx:107: bfCar.png
source/Cache.hx:107: bfChristmas.png
source/Cache.hx:107: bfPixel.png
source/Cache.hx:107: bfPixelsDEAD.png
source/Cache.hx:107: DADDY_DEAREST.png
source/Cache.hx:107: gfCar.png
source/Cache.hx:107: gfChristmas.png
source/Cache.hx:107: gfPixel.png
source/Cache.hx:107: GF_assets.png
source/Cache.hx:107: momCar.png
source/Cache.hx:107: Mom_Assets.png
source/Cache.hx:107: mom_dad_christmas_assets.png
source/Cache.hx:107: monsterChristmas.png
source/Cache.hx:107: Monster_Assets.png
source/Cache.hx:107: Pico_FNF_assetss.png
source/Cache.hx:107: senpai.png
source/Cache.hx:107: spirit.png
source/Cache.hx:107: spooky_kids_assets.png
source/Cache.hx:114: blammed
source/Cache.hx:114: bopeebo
source/Cache.hx:114: cocoa
source/Cache.hx:114: dad-battle
source/Cache.hx:114: eggnog
source/Cache.hx:114: fresh
source/Cache.hx:114: high
source/Cache.hx:114: milf
source/Cache.hx:114: monster
source/Cache.hx:114: philly-nice
source/Cache.hx:114: pico
source/Cache.hx:114: roses
source/Cache.hx:114: satin-panties
source/Cache.hx:114: senpai
source/Cache.hx:114: south
source/Cache.hx:114: spookeez
source/Cache.hx:114: test
source/Cache.hx:114: thorns
source/Cache.hx:114: tutorial
source/Cache.hx:114: winter-horrorland
source/Discord.hx:17: Discord Client starting...
source/Discord.hx:67: Discord Client initialized
source/Discord.hx:24: Discord Client started.

Invalid char 65279 at position 0
```

### Are you modding a build from source or with Lua?

Lua AND Source
Lua for cool song things
source for other things like editing menus and loading screens

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by SpookyMan16** [comment]
the github version is broken, use the current latest source for now that hasn't been released

**Comment by SrtHero278** [comment]
there could be something wrong with your json files since that looks like a json error.
i recommend checking them here since json are hard to debug: https://jsonlint.com/

**Comment by machonessiebaby** [comment]
> the github version is broken, use the current latest source for now that hasn't been released

this is 5.1

**Comment by machonessiebaby** [comment]
nothing to do with loading scren apparently
