### ISSUE TITLE
How do I generate random numbers using Lua?

### ISSUE THREAD

**Issue by BombasticTom** [ShadowMario/FNF-PsychEngine#4143]
### What is your question?

I wanted to try and recreate the storm mechanic in week 2 using lua but i don't know how to get random numbers in lua

**Comment by SrtHero278** [comment]
math.random([MINIMUM], [MAXIMUM]);

**Comment by BombasticTom** [comment]
thanks

**Comment by MayoALT** [comment]
actually use `getRandomInt((min), (max), true)` because `math.random` will no longer be random in the next update

**Comment by BombasticTom** [comment]
thankss

**Comment by IhavenotComeToCompete** [comment]
try this 

https://github.com/IhavenotComeToCompete/Pure-Random-Number-Generator-Love2D-LUA
