### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by Ninjatintin** [ShadowMario/FNF-PsychEngine#4144]
### Describe your bug here.

Every time bf hits a note, the game just crashes, but it keeps happening on only one song (The song name is "Sharpen" if thats the issue), is something wrong? (note, I'm using version 0.4.2, and im not going to update it)
Chart:
[sharpen - Copy.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7966757/sharpen.-.Copy.txt)

Idk whats wrong

### Command Prompt/Terminal logs (if existing)

```bash
source/Discord.hx:12: Discord Client starting...
source/Discord.hx:62: Discord Client initialized
source/Discord.hx:19: Discord Client started.
source/Discord.hx:12: Discord Client starting...
source/Discord.hx:62: Discord Client initialized
source/Discord.hx:19: Discord Client started.
source/FreeplayState.hx:283: sharpen-hard
source/FreeplayState.hx:290: CURRENT WEEK: week10
source/LoadingState.hx:162: Setting asset folder to week9
source/Conductor.hx:59: new BPM map BUDDY []
source/PlayState.hx:306: stage is: worldTwo

no error shown :(
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, different icon bopping, renamed rankings.

**Comment by MaxlionButMyNameIsTakenSoThisIsmyName** [comment]
Did you put everything that the "worldTwo" stage has in the "week9" folder?
If you don't have a week9 folder, in the stage json for worldTwo make sure to leave it blank to use the default assets

**Comment by Ninjatintin** [comment]
i have a week9 folder

**Comment by Ninjatintin** [comment]
and i made sure to edit the xml
