### ISSUE TITLE
Can you use Lua in the source code?

### ISSUE THREAD

**Issue by Masterlittlejoe** [ShadowMario/FNF-PsychEngine#4145]
### Describe your problem here.

I want the source code so that I can do things like add custom difficulties, but I don't know haxeflixel as well as I know Lua, and I would prefer to make a stage in Lua rather than source. Can I still do that?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Changed menu assets, added character, added song and chart, added bg assets, json and lua file.

**Comment by ZackOui** [comment]
Yep! You can still add lua files in source code! Just go to your source code folder, and then go to example_mods and put some stuff in there and put scripts in there too with the scripts folder (Your Source Code Folder/example_mods/scripts)

This is my Source Code Folder.
<img width="920" alt="Screen Shot 2022-01-30 at 12 00 20 PM" src="https://user-images.githubusercontent.com/92494313/151715602-81562a2c-d6e7-4327-9ab4-774cb70fc71e.png">

And this is the example_mods folder.
<img width="919" alt="Screen Shot 2022-01-30 at 12 00 35 PM" src="https://user-images.githubusercontent.com/92494313/151715625-47d3675f-77eb-4c38-a8f3-c3ad149195ec.png">

and then put stages and songs here!
<img width="924" alt="Screen Shot 2022-01-30 at 12 02 35 PM" src="https://user-images.githubusercontent.com/92494313/151715639-878d8e08-0e53-45e9-98fe-a43a9e2a3af5.png">

**Comment by Masterlittlejoe** [comment]
Oh, thanks!
