### ISSUE TITLE
Is there a way to have only one difficulty in a week?

### ISSUE THREAD

**Issue by LucaGoku** [ShadowMario/FNF-PsychEngine#415]
I'm porting V.S. Dave and Bambi into Pysch Engine but there's a week with only 1 difficulty, what do I do?

**Comment by HiroOfc** [comment]
**yo i want to know this too**

**Comment by ShadowMario** [comment]
Delete all difficulties from CoolUtil.hx **EXCEPT** your difficulty.
Then go into FreeplayState.hx and StoryMenuState.hx and change `curSelected = 1;` to `curSelected = 0;`

**Comment by LucaGoku** [comment]
So, what do I do?
