### ISSUE TITLE
Death Loop animation doesn't work

### ISSUE THREAD

**Issue by Jotamer** [ShadowMario/FNF-PsychEngine#4157]
### Describe your problem here.

I'm Trying to Make the Death Loop animation to play but it doesn't and i don't know why

The animation not playing
https://user-images.githubusercontent.com/43319586/151741436-bc10a138-89eb-4eda-a97c-8fb38d2ba144.mp4

![image](https://user-images.githubusercontent.com/43319586/151741471-e4abb242-5b1a-4b86-bc80-7ff0ef964713.png)

![image](https://user-images.githubusercontent.com/43319586/151741510-d6468f2c-0a6c-4b0b-a137-ca75cbb66fac.png)

![image](https://user-images.githubusercontent.com/43319586/151741554-4f5d6253-f552-4007-a34d-2ff5cad133d7.png)

Please if someone knows how to fix it please tell me

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

added a song, three characters, the chart, some events, custom notetypes etc...

**Comment by trayfellow** [comment]
you forgot to add 'sonic ' at the beginning of the death loop animation name like the xml did

**Comment by Jotamer** [comment]
i didn't notice that, thank you

**Comment by frantastic24** [comment]
Close this
