### ISSUE TITLE
me cant hit a note

### ISSUE THREAD

**Issue by lime360** [ShadowMario/FNF-PsychEngine#4160]
### Describe your bug here.

basically when i go to the random song, i can't hit every single note

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i didn't do anything

**Comment by frantastic24** [comment]
Skill issue
Report a bug by actually giving details or don't report at all

**Comment by main-thing** [comment]
Re bind your keys?

**Comment by lime360** [comment]
@main-thing i tired, still has a bug

**Comment by lime360** [comment]
@frantastic24 it's not a skill issue
basically i pick any song in freeplay and it tried pressing notes, but they didn't splash/dissappear

**Comment by frantastic24** [comment]
Try actually describing the bug because you haven't given any information

**Comment by lime360** [comment]
sorry i put the "play with mouse instead of keyboard" script in the scripts folder but now i deleted it
this was the reason why i couldn't hit a note with keyboard
