### ISSUE TITLE
how to port reskins onto other mods?

### ISSUE THREAD

**Issue by BombasticTom** [ShadowMario/FNF-PsychEngine#4161]
### Describe your problem here.

basically what I want to do is make a mod folder that has character reskins and images all around the game (including other mods, normal game), not just the mod itself. is that possible?

![image](https://user-images.githubusercontent.com/85838311/151786402-419f5449-67e2-489f-9e74-7c32f1d1bef3.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by cameronthekibryya** [comment]
you put you're note skin in images
![Screenshot 2022-01-31 115144](https://user-images.githubusercontent.com/92703353/151847072-e4b684f7-0393-4446-a96e-d3f74e8c63fe.png)
then you the chart editor on the song tab you put you're note skin name in
![Screenshot 2022-01-31 115438](https://user-images.githubusercontent.com/92703353/151847233-06339630-1794-4dbe-ac67-f117f5a77b39.png)

**Comment by cameronthekibryya** [comment]
do this in the mod folder

**Comment by BombasticTom** [comment]
but I don't need the note texture? I am trying to swap a character trough different mods but in a mod folder. Idk how to do that, so I had to put images and characters folders into mods folder

**Comment by Pico8430** [comment]
You can try putting the spritesheets with the .xml into the images/characters folder and the .json on the characters folder. However, making a custom folder for all the characters it's not possible on Lua (i think), you have to make a new mod with the images and characters folder.

**Comment by BombasticTom** [comment]
rip so then it's impossible?

**Comment by Pico8430** [comment]
Making a mods folder for the characters its possible, but making custom folders for the characters its impossible on lua.

**Comment by ShadowMario** [comment]
Simply put the images inside `mods/images/characters/` instead of the usual method of `mods/Mod Folder Name/images/characters/`

**Comment by BombasticTom** [comment]
I know, that's what I did, but imagine you want to upload the reskin/rechart/new difficulty to gamebanana. The mods folder would be messy. Maybe like make an update in which you can make a folder called "public" which is literally mods/images/characters (and other public stuff), but more organized.
