### ISSUE TITLE
how texture atlas help

### ISSUE THREAD

**Issue by Uniimations** [ShadowMario/FNF-PsychEngine#4166]
### Describe your problem here.

we got a HUGE woman and we NEED a texture atlas because we CANT make a spritesheet or have a good workaround for storage, how do i use texture atlases?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added songs and sprites by the team, just coding and charting, no huge modifications

**Comment by BombasticTom** [comment]
there's a tutorial on the official psych engine wiki page: https://github.com/Smokey555/Flixel-TextureAtlas/blob/main/README.md
