### ISSUE TITLE
Enabling mods with Restart set to 'true' crashes.

### ISSUE THREAD

**Issue by AdrianCD5** [ShadowMario/FNF-PsychEngine#4174]
### Describe your bug here.

When attempting to enable or disable a modpack with the restart flag set to 'true', the engine will begin restarting before the main menu music stutters and the game crashes. The mod loads in when opening the engine again.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

There is no edits to the build itself, only the modpack.

**Comment by ShadowMario** [comment]
Fixed
