### ISSUE TITLE
auto charting

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#4181]
### What feature do you want to get added on the **base** engine?
auto charting
for the people who are too lazy
also might need a midi of the voices

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by creeperkidking** [comment]
it would work like each pitch is assigned to a different note

**Comment by Stilic** [comment]
its impossible. but if you have the song fl studio file, you can use something like [SNIFF](https://github.com/PrincessMtH/SNIFF).

**Comment by MayoALT** [comment]
that would make for the most awful shit charting ever

**Comment by creeperkidking** [comment]
ye yur right :)

**Comment by creeperkidking** [comment]
sadly i use lmms so i dont think i can use that :(

**Comment by ShadowMario** [comment]
Oh, you're lazy? Too bad!
