### ISSUE TITLE
Invalid char 65279 at position 0 error

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#4184]
### Describe your bug here.

Invalid char 65279 at position 0
idk what this is it was not the loading screen apparently there is somthing wrong with story and freeplay sadly idk what happend

### Command Prompt/Terminal logs (if existing)

```bash
Invalid char 65279 at position 0
```

### Are you modding a build from source or with Lua?

Lua Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by ShadowMario** [comment]
Looks like you manually edited a .json/.xml file

**Comment by machonessiebaby** [comment]
like idk what happened but like it randomly happened a week ago so ill just do the long way and do 1 week of charting character file fixing and other stuff lol
