### ISSUE TITLE
I can't compile

### ISSUE THREAD

**Issue by Racso09** [ShadowMario/FNF-PsychEngine#4185]
### Describe your problem here.

i want compile the engine but it show this issue
![image](https://user-images.githubusercontent.com/78282357/151887433-00c0d907-c4f6-4c69-921c-bed76741be65.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I have changed the states (optionstate, freeplaystate, etc.) to put my own images

**Comment by Gui-iago** [comment]
fixed
