### ISSUE TITLE
setTextPosition for lua

### ISSUE THREAD

**Issue by Ninjatintin** [ShadowMario/FNF-PsychEngine#4197]
### What feature do you want to get added on the **base** engine?

i want to be able to change a lua text's position but i cant find the function and i have a feeling there isn't one, can you add it to the base engine?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
already possible
`setProperty('texttag.x', value);`
