### ISSUE TITLE
More lua features for new modders

### ISSUE THREAD

**Issue by lolbruhfart** [ShadowMario/FNF-PsychEngine#4203]
### What feature do you want to get added on the **base** engine?

I've been looking everywhere for ways to to certain things in lua but can't find anything. Things like make it so for a specific character they do something like make the the screenshake or change the bottom text on the rating bar like the misses, you can only change the ratings on lua

### To test your sight, and reliability, please select the option of what should NOT be requested.

Better LUA mod support idea

**Comment by MayoALT** [comment]
![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)

![image](https://user-images.githubusercontent.com/94536972/151976054-c130e062-4e3d-423f-99e6-61d498299fd3.png)
