### ISSUE TITLE
You can see events with the chart editor (like when you press esc you can play your chart)

### ISSUE THREAD

**Issue by matt-sudo-jpg** [ShadowMario/FNF-PsychEngine#4204]
### What feature do you want to get added on the **base** engine?

I am wondering if this can be possible, like when your charting and you place a event. but you want to see like custom or built in events  to see if it works or if its in the right place

### To test your sight, and reliability, please select the option of what should NOT be requested.

Thing that would not cause problems

**Comment by SrtHero278** [comment]
![image](https://user-images.githubusercontent.com/93018286/152255214-760eaed3-fea8-47f3-a366-d40052c02839.png)
A lot of people care about this test so you might wanna fix it.
