### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by ItzDoggoDev** [ShadowMario/FNF-PsychEngine#4205]
### Describe your bug here.

Sound completely doesn't work, I've had to use old versions for sound to work.
I've tried 32 bit and 64 bit, just nothing.

Edit: thanks plus button, you fixed everything.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just was testing a mod by a friend. I've tested without the mod installd and it still does not work with sound.

**Comment by dum-du-m** [comment]
close if its fixed
