### ISSUE TITLE
Enhancement/Suggestion: Adding achievements though mod folders/lua scripting

### ISSUE THREAD

**Issue by ItsJayPM** [ShadowMario/FNF-PsychEngine#421]
Hello! I was wondering, do you have intent to allow drag and drop mods to create their own achievements in the future? You mentioned reworking of the achievements system in a separate issue but I dunno if your refactoring will include this or not. Thank you, and keep up the good work, so far, you have made an excellent engine!

(edit: Same thing for difficulties. Wanted to know if you intend to make those possible to add without compiling aswell)

**Comment by Mastercopper2346** [comment]
ITS GETTING ADDED

**Comment by JokeBambi** [comment]
close this please its ADDED NOW
