### ISSUE TITLE
Game Crashing On Game Over

### ISSUE THREAD

**Issue by LuckyMist8** [ShadowMario/FNF-PsychEngine#4218]
### Describe your problem here.

My Script Crashes The Game When In The Song And Game Over Happens.

In The Script, I Already Have This : 

	setPropertyFromClass('GameOverSubstate', 'characterName', 'bf-wrath'); --Character json file for the death animation
	setPropertyFromClass('GameOverSubstate', 'deathSoundName', 'fnf_loss_sfx'); --put in mods/sounds/
	setPropertyFromClass('GameOverSubstate', 'loopSoundName', 'gameOver'); --put in mods/music/
	setPropertyFromClass('GameOverSubstate', 'endSoundName', 'gameOverEnd'); --put in mods/music/

The Character .json Is Set To The Right Name Across All Files.
For The Death Animations In The .json I Have: 

		{
			"offsets": [
				37,
				11
			],
			"indices": [],
			"fps": 24,
			"anim": "firstDeath",
			"loop": false,
			"name": "BF NOTE DOWN MISS0"
		},
		{
			"offsets": [
				37,
				5
			],
			"loop": true,
			"fps": 24,
			"anim": "deathLoop",
			"indices": [],
			"name": "BF idle dance"
		},
		{
			"offsets": [
				37,
				69
			],
			"loop": false,
			"fps": 24,
			"anim": "deathConfirm",
			"indices": [],
			"name": "BF HEY!!"
		}

All Names For This Pointing To The .xml Are Correct, I Have Tested With The Built-In character Editor And The Animations Play Just Fine. But Once I Get Into The Song And Die It Crashes, I Can Hear The Sound Effects Begin To Play Though So It Shouldn't Be A Problem With The Script?

Using The "GameOverSubState" Script I Can't Even Seem To Get The Original BF's Game Over To Play Instead, even When All The OG BF Files Are Still In The Assets Folder.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I Didn't Touch Source Code At All, Via Lua I've Added A New Song With Custom Note Types, Custom Events, And A New Difficulty.

**Comment by Draconic-Hybrid** [comment]
Is that your entire JSON file? If so, it's missing a few things. I know from experience that broken JSON files crash the game, so it could be that.

**Comment by LuckyMist8** [comment]
`{
	"animations": [
		{
			"offsets": [
				7,
				19
			],
			"loop": false,
			"fps": 24,
			"anim": "singLEFTmiss",
			"indices": [],
			"name": "BF NOTE LEFT MISS"
		},
		{
			"offsets": [
				-15,
				-19
			],
			"loop": false,
			"fps": 24,
			"anim": "singDOWNmiss",
			"indices": [],
			"name": "BF NOTE DOWN MISS"
		},
		{
			"offsets": [
				-36,
				27
			],
			"loop": false,
			"fps": 24,
			"anim": "singUPmiss",
			"indices": [],
			"name": "BF NOTE UP MISS"
		},
		{
			"offsets": [
				-44,
				22
			],
			"loop": false,
			"fps": 24,
			"anim": "singRIGHTmiss",
			"indices": [],
			"name": "BF NOTE RIGHT MISS"
		},
		{
			"offsets": [
				-3,
				5
			],
			"loop": false,
			"fps": 24,
			"anim": "hey",
			"indices": [],
			"name": "BF HEY!!"
		},
		{
			"offsets": [
				15,
				18
			],
			"loop": false,
			"fps": 24,
			"anim": "hurt",
			"indices": [],
			"name": "BF hit"
		},
		{
			"offsets": [
				-4,
				0
			],
			"loop": true,
			"fps": 24,
			"anim": "scared",
			"indices": [],
			"name": "BF idle shaking"
		},
		{
			"offsets": [
				37,
				5
			],
			"loop": true,
			"fps": 24,
			"anim": "deathLoop",
			"indices": [],
			"name": "BF idle dance"
		},
		{
			"offsets": [
				37,
				69
			],
			"loop": false,
			"fps": 24,
			"anim": "deathConfirm",
			"indices": [],
			"name": "BF HEY!!"
		},
		{
			"offsets": [
				-10,
				-16
			],
			"loop": false,
			"fps": 24,
			"anim": "dodge",
			"indices": [],
			"name": "boyfriend dodge"
		},
		{
			"offsets": [
				294,
				267
			],
			"loop": false,
			"fps": 24,
			"anim": "attack",
			"indices": [],
			"name": "boyfriend attack"
		},
		{
			"offsets": [
				-40,
				-40
			],
			"loop": false,
			"fps": 24,
			"anim": "pre-attack",
			"indices": [],
			"name": "bf pre attack"
		},
		{
			"offsets": [
				0,
				0
			],
			"loop": true,
			"fps": 24,
			"anim": "",
			"indices": [],
			"name": ""
		},
		{
			"offsets": [
				-5,
				0
			],
			"loop": true,
			"fps": 24,
			"anim": "idle",
			"indices": [],
			"name": "BF idle dance"
		},
		{
			"offsets": [
				5,
				-6
			],
			"loop": true,
			"fps": 24,
			"anim": "singLEFT",
			"indices": [],
			"name": "BF NOTE LEFT0"
		},
		{
			"offsets": [
				-10,
				-50
			],
			"loop": true,
			"fps": 24,
			"anim": "singDOWN",
			"indices": [],
			"name": "BF NOTE DOWN0"
		},
		{
			"offsets": [
				-29,
				27
			],
			"loop": true,
			"fps": 24,
			"anim": "singUP",
			"indices": [],
			"name": "BF NOTE UP0"
		},
		{
			"offsets": [
				-48,
				-7
			],
			"loop": true,
			"fps": 24,
			"anim": "singRIGHT",
			"indices": [],
			"name": "BF NOTE RIGHT0"
		},
		{
			"offsets": [
				37,
				11
			],
			"loop": false,
			"fps": 24,
			"anim": "firstDeath",
			"indices": [],
			"name": "BF NOTE DOWN MISS0"
		}
	],
	"no_antialiasing": false,
	"image": "characters/bf-wrath",
	"position": [
		0,
		350
	],
	"healthicon": "bf-wrath",
	"flip_x": true,
	"healthbar_colors": [
		0,
		255,
		60
	],
	"camera_position": [
		0,
		0
	],
	"sing_duration": 4,
	"scale": 1
}`

**Comment by LuckyMist8** [comment]
@Draconic-Hybrid 
That Is Only A Small Section Of The .json Showing The Game Over Anims
Here Is The Entire .json For The Character : 
https://drive.google.com/file/d/1s7Drb1kkxblH4mrcOivPa6Jd5yMji-G8/view?usp=sharing

**Comment by Draconic-Hybrid** [comment]
That's strange. The only culprit I can think of is that animation without a name or a xml directory.

**Comment by frantastic24** [comment]
If you have any code running under onUpdate, try adding an `inGameOver` check, otherwise it tends to crash when switching states

**Comment by LuckyMist8** [comment]
How Do I Write A inGameOver Check?

**Comment by LuckyMist8** [comment]
@frantastic24 
The Only Code I Have With The "onUpdate" Function Is For The Winning Icons,
Which Doesn't Have Anything Under It For "InGameOver"

**Comment by frantastic24** [comment]
It's a simple `if` statement

**Comment by LuckyMist8** [comment]
So

function onUpdate()
     if inGameOver then
     setPropertyFromClass('GameOverSubstate', 'characterName', 'bf-wrath'); --Character json file for the death animation
    setPropertyFromClass('GameOverSubstate', 'deathSoundName', 'fnf_loss_sfx'); --put in mods/sounds/
    setPropertyFromClass('GameOverSubstate', 'loopSoundName', 'gameOver'); --put in mods/music/
    setPropertyFromClass('GameOverSubstate', 'endSoundName', 'gameOverEnd'); --put in mods/music/
    end
end

?

**Comment by frantastic24** [comment]
I never said to move your code under onUpdate, I said to add the check for the code you already have under it

**Comment by LuckyMist8** [comment]
Oh Ok Thanks :p
