### ISSUE TITLE
Vocals play in chart but not actual gameplay?

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#4220]
### Describe your bug here.

https://user-images.githubusercontent.com/93293747/152036724-8d0aac92-37c5-497e-8b7f-95c0d7695407.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by MayoALT** [comment]
are you SURE that has vocals is turned on?

**Comment by ItsCapp** [comment]
> 

🤦‍♂️ 
![image](https://user-images.githubusercontent.com/93293747/152037261-70868fea-e401-4e39-b02f-c8dbea1486bc.png)
