### ISSUE TITLE
The game is not working

### ISSUE THREAD

**Issue by SupaFromSupasShow** [ShadowMario/FNF-PsychEngine#4222]
### Describe your bug here.

the start text wont show, the animations don't loop, Even worst, the songs won't load but they show everything else (no singing tho) and my custom char's xmls are right, but an error comes up. I'm using the mods folder

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, but im making bambi's assets

**Comment by mapleeeeeeeeeeeeee** [comment]
did u cancel the extracting game files while extracting?? maybe re-extract

**Comment by SupaFromSupasShow** [comment]
No, i extracted it normally

**Comment by frantastic24** [comment]
So is this just a thing with your mod or is it general, be specific

**Comment by SupaFromSupasShow** [comment]
its general. i have 4 gigs of ram. how much does psych engine require?
