### ISSUE TITLE
Event values 

### ISSUE THREAD

**Issue by mapleeeeeeeeeeeeee** [ShadowMario/FNF-PsychEngine#4223]
### Describe your bug here.

my game crashes when i sometimes change event values

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
Couldn't find any way to replicate this issue, so i will need more information/possibly a consistent way to replicate this bug.

**Comment by mapleeeeeeeeeeeeee** [comment]
i dunno what causes this tho the game has no errors or stuff it just closes

**Comment by frantastic24** [comment]
Just trace step by step what you did before the game closes

**Comment by mapleeeeeeeeeeeeee** [comment]
was making a applecore port for fun, adding events i changed the event and  pressed **backspace** to clear the box then the game just closed (custom events btw)
