### ISSUE TITLE
I wanted to learn how to make really good modcharts and I wanted to learn about it

### ISSUE THREAD

**Issue by Murilo3127** [ShadowMario/FNF-PsychEngine#4232]
### What is your question?

I already did it in the title xD, for those who make a tutorial send your YouTube channel link (if you have)

**Comment by PoleyMagik** [comment]
Binge the documentation, that's all that threre really is to be said, maybe look at other modcharts for inspiration

**Comment by Murilo3127** [comment]
> Binge the documentation, that's all that threre really is to be said, maybe look at other modcharts for inspiration

The documentation didn't help me at all, there's never an example to use (and very rare to have) I had to see a tutorial on YouTube and the script was wrong (I use Android) I tried to make a script manually To try to repeat an action and it didn't work :(
