### ISSUE TITLE
stages

### ISSUE THREAD

**Issue by ItsRandom7121** [ShadowMario/FNF-PsychEngine#4235]
### Describe your bug here.

I really don't know if it's a Mac thing (I don't have Windows as of right now to test it) but the lua stages, from various mod packs I put in the mods folder, doesn't seem to load the song. Upon loading the song, the game crashes... I'm thinking it's the stage lua files. 

### Command Prompt/Terminal logs (if existing)

```bash
N/A
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No changes

**Comment by frantastic24** [comment]
If you think it's the Lua then show the Lua at least

**Comment by ShadowMario** [comment]
Due to Haxe and my own limitations, Lua support on Mac is currently on an unknown state

**Comment by tposejank** [comment]
@gaminbottomtext

**Comment by gaminbottomtext** [comment]
what

**Comment by gaminbottomtext** [comment]
oh 
yeah i cant do anything with mac lua anymore i got a windows pc
