### ISSUE TITLE
PLEASE HEAR ME OUT

### ISSUE THREAD

**Issue by Hunter13n** [ShadowMario/FNF-PsychEngine#4242]
### What feature do you want to get added on the **base** engine?

what if @ShadowMario added a thing when you creating your character an doing the offsets an shit, but when you click on the box that says "Playable Character" an do the offsets for that, an save it, an you look in the .json file an says this lol

![6341BDD1-22B9-40F1-A2D9-67320B73C216](https://user-images.githubusercontent.com/66497511/152090547-e7a5126f-8289-40a3-b0a5-7955ff25efa7.jpeg)

I think its stupid an Creative LOL

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by matt-sudo-jpg** [comment]
like in modding +??

**Comment by tposejank** [comment]
you failed the test

**Comment by Hunter13n** [comment]
> like in modding +??

No, I looked at blantados betadciu JSON files an saw that an I thought it would be a good idea for psych

**Comment by MayoALT** [comment]
![image](https://user-images.githubusercontent.com/94536972/152163283-8e8267ad-6a9f-4700-9d8d-0bd103927dec.png)
why are psych engine users so dumb

**Comment by Pico8430** [comment]
This guy just failed the test, bruh.

**Comment by frantastic24** [comment]
How lazy are you

**Comment by Hunter13n** [comment]
> How lazy are you

Lazy

**Comment by Hunter13n** [comment]
> you failed the test

Wait.. wat test?
