### ISSUE TITLE
compiling(?) help

### ISSUE THREAD

**Issue by 0-skid** [ShadowMario/FNF-PsychEngine#4243]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/85322671/152093430-ea8aab01-e646-4acc-9f41-8cd12da4be12.png)
i got this when i ran the "lime test linux -debug" command, i've already checked Song.hx in the place it said but this is what it is: 
![image](https://user-images.githubusercontent.com/85322671/152093690-9cb524d1-148d-47d2-b122-19751d7d3551.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by SrtHero278** [comment]
In case you haven't found out, you need to get the latest version instead of 4.1.5.
https://haxe.org/download/

**Comment by 0-skid** [comment]
> In case you haven't found out, you need to get the latest version instead of 4.1.5.
> https://haxe.org/download/

i did

**Comment by 0-skid** [comment]
> > In case you haven't found out, you need to get the latest version instead of 4.1.5.
> > https://haxe.org/download/
> 
> i did

at least i'm pretty sure i did,??

**Comment by 0-skid** [comment]
> In case you haven't found out, you need to get the latest version instead of 4.1.5.
> https://haxe.org/download/

is it the latest unstable build? if so then i can't install it

**Comment by SrtHero278** [comment]
huh. then maybe try this.
https://github.com/ShadowMario/FNF-PsychEngine/issues/2724#issuecomment-1001257639
