### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sebby09559** [ShadowMario/FNF-PsychEngine#4247]
### Describe your problem here.

How do I make a cutscenes play before and after a song and before the next song also have dialogue play after the first video cut scene  also how do I make a doge not that when player taps on the note the player plays a doge animation and if the play missed not the players death animation is different ?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by zLightc** [comment]
I'm gonna assume you've put the video and made the .json and portraits and stuff.

go to the song's folder in mods and make a file named **script.lua**.

then put this code:

```
local allowCountdown = false
function onStartCountdown()
	if not allowCountdown and isStoryMode and not seenCutscene then --Block the first countdown
		startVideo('testVideo');
		allowCountdown = true;
		return Function_Stop;
	end
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('dialogue', 'breakfast');
	end
end

```

**NOTE : IN THE** `startVideo('testVideo')` **CHANGE THE NAME OF THE STRING TO THE NAME OF YOUR MP4**

im not sure if this works but this is all i have i hope it works!

**Comment by zLightc** [comment]
also there is an invention called wiki! you might find some tutorials there : **https://github.com/ShadowMario/FNF-PsychEngine/wiki**
