### ISSUE TITLE
Why black BG

### ISSUE THREAD

**Issue by barbbarain** [ShadowMario/FNF-PsychEngine#425]
i made a bg, and their Bg file (json and png) are already in `mods/`, when i selected my BG in chart editor, it turns to black BG
![Capture](https://user-images.githubusercontent.com/68548511/137636363-fe9883ee-b1ce-4392-8bd4-753e717b2f5c.PNG)
and also i even edited PlayState.hx
their code i added was ` case 'SunnyDay': //weekfun
			    var  SunnyDaybg:BGSprite = new BGSprite('SunnyDaybg';, -200, -100, 0.9, 0.9)`
yes i dont know how to code TwT

**Comment by ShadowMario** [comment]
Put a `add(SunnyDaybg);` **BELOW** the `var SunnyDaybg` line.
