### ISSUE TITLE
change character does not work

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#4250]
### Describe your bug here.

when I try to use the change character event on the opponent it always changes bf instead.
and I am typing the works correctly.
i use the compiled version and I don't use the code.

### Command Prompt/Terminal logs (if existing)

```bash
none as of now
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Reycko** [comment]
1 - Dad
0 - BF
2 - GF

**Comment by frantastic24** [comment]
Not a bug, you're using the event wrong

**Comment by Pico8430** [comment]
You are using the event wrong, it's not used like that, here's how it works.

*blank* = BF (Basically dont put anything on here to change bf)
1 = Dad
2 = GF
3 = Nothing happens

**Comment by SrtHero278** [comment]
Actually,
1 - Opponent
2 - GF
Anything else - BF

**Comment by ShadowMario** [comment]
Thank you for providing no information on how you're using it :+1:

**Comment by creeperkidking** [comment]
i found out already forgot to closed thank you
