### ISSUE TITLE
Custom note not working

### ISSUE THREAD

**Issue by xzh3r** [ShadowMario/FNF-PsychEngine#4251]
### Describe your problem here.

When I try to make a custom note, it doesn't work. Things like changing how much health it gives you and stuff like that works, but the thing I programmed it to do when you hit the note doesn't work. Here's the code of it:

function noteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'Paintball Note' then
		makeLuaSprite('image', 'onScreenPaint', 200, -200);
		setScrollFactor('image', 0, 0);
		addLuaSprite('image', true);
		doTweenColor('hello', 'image', 'FFFFFFFF', 0.5, 'quartIn');
		setObjectCamera('image', 'other');
		runTimer('wait', 2);
	end
end

I took some of that code from a Lua script I found, so it should work.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by xzh3r** [comment]
The formatting of the code screwed up when I posted this, here it is with the actual formatting:

`function noteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'Paintball Note' then
		makeLuaSprite('image', 'onScreenPaint', 200, -200);
		setScrollFactor('image', 0, 0)
		addLuaSprite('image', true);
		doTweenColor('hello', 'image', 'FFFFFFFF', 0.5, 'quartIn');
		setObjectCamera('image', 'other');
		runTimer('wait', 2);
	end
end`

**Comment by xzh3r** [comment]
And it's even worse

**Comment by frantastic24** [comment]
`goodNoteHit` instead of `noteHit`

**Comment by xzh3r** [comment]
It still doesn't work

**Comment by frantastic24** [comment]
show the full code and tell me what the lua is called

**Comment by xzh3r** [comment]
https://easyupload.io/sn02el

**Comment by frantastic24** [comment]
what's not working exactly? the one issue i see is you're constantly creating a sprite when you could just create it on load and play with it's alpha or visibility when the note is hit

**Comment by xzh3r** [comment]
i know creating a new sprite is pretty unoptimized but it works fine enough for now, the thing that isnt working is the image appearing and fading

**Comment by frantastic24** [comment]
you didn't set the alpha for the sprite so it will start fully visible

**Comment by xzh3r** [comment]
how do i set it again

**Comment by frantastic24** [comment]
`setProperty('image.alpha', 0);`

**Comment by xzh3r** [comment]
bruh it still doesnt work

**Comment by frantastic24** [comment]
At least show me what the new code looks like
