### ISSUE TITLE
yo psych engine has a bad input

### ISSUE THREAD

**Issue by anonybean** [ShadowMario/FNF-PsychEngine#4253]
### Describe your bug here.

https://user-images.githubusercontent.com/94534428/152156439-ef44a175-769b-48a2-b1bf-ea7bc11cb927.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by anonybean** [comment]
or maybe i suck at it

**Comment by MayoALT** [comment]
skill issue
