### ISSUE TITLE
Background won't load

### ISSUE THREAD

**Issue by DiegoRob** [ShadowMario/FNF-PsychEngine#426]
so, I was trying to add my stage to the game and I did all the coding right and for some reason the background only appears as the Haxe symbol, does anyone know why is this happening? 
![image](https://user-images.githubusercontent.com/31390335/137637120-2dcd5669-ac02-459a-bfb5-2125174a934a.png)

**Comment by ShadowMario** [comment]
Missing sprite.

**Comment by DiegoRob** [comment]
> Missing sprite.

yeah apparently I put it in the wrong folder, works perfectly now haha
