### ISSUE TITLE
Cutscene feature idea

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#4277]
### What feature do you want to get added on the **base** engine?

So maybe you didn't know, but in normal FNF week 7 there are animated cutscenes that are not videos. They are characters just split into parts on a sprite. Or maybe i am just stupid and they are actually videos. Anyways, it would, in my opinion, be a cool addition.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ItsCapp** [comment]
I think you can emulate this by disabling the song countdown and then playing the character's animations

**Comment by frantastic24** [comment]
You can already do this.
