### ISSUE TITLE
Note sustain strums look a bit ugly at high BPMs. This is how to fix it.

### ISSUE THREAD

**Issue by i-winxd** [ShadowMario/FNF-PsychEngine#4283]
## What's going on?

The following seems to be affected by the tempo/BPM of the song:
* How often the note strums' light-up loop seem to be tied to the BPM of the song.

https://user-images.githubusercontent.com/31808925/148288717-3ae00f0d-829b-471b-83bc-91e587d20681.mp4

This may be due to how sustains are created in the first place. It makes sustain notes "blink" at high BPM levels, which makes it less satisfying to look at. Perhaps how strum sustains are animated may have to change a bit, from reacting to sustain pieces to just looping whenever a key is held down.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
The quality of this video is too low for understanding but i think i got what you mean, this is just how note glow animations play when you hit a note.
