### ISSUE TITLE
Fonts and menus.

### ISSUE THREAD

**Issue by Coolboy0516** [ShadowMario/FNF-PsychEngine#4290]
### What is your question?

Where the frick is this font download?
![image](https://user-images.githubusercontent.com/84407770/152264518-6facf577-6c2a-45d0-ad13-3dd5b86573a4.png)
...and can you modify the menus with the scripts folder in the mods folder?
![image](https://user-images.githubusercontent.com/84407770/152264709-f61c230d-4495-4cc6-9c6b-a002d4328e7e.png)

**Comment by frantastic24** [comment]
1) just use Google
2) no

**Comment by Coolboy0516** [comment]
1. that didn't work
2. ok

**Comment by frantastic24** [comment]
Literally the first result
![Screenshot_2022-02-02-22-55-43-941.jpg](https://user-images.githubusercontent.com/95725102/152268528-268ffaec-8bdf-49c7-8419-9515cacd7bce.jpg)

**Comment by Coolboy0516** [comment]
no it isn't

**Comment by frantastic24** [comment]
Either your search engine is shit or you don't know how to use Google
Either way your answer is there

**Comment by mayo78** [comment]
it was drawn by hand pretty sure

**Comment by frantastic24** [comment]
It is hand drawn, but people have compiled it into an actual font

**Comment by Coolboy0516** [comment]
Where is the font?

**Comment by PoleyMagik** [comment]
> ### What is your question?
> Where the frick is this font download? ![image](https://user-images.githubusercontent.com/84407770/152264518-6facf577-6c2a-45d0-ad13-3dd5b86573a4.png) ...and can you modify the menus with the scripts folder in the mods folder? ![image](https://user-images.githubusercontent.com/84407770/152264709-f61c230d-4495-4cc6-9c6b-a002d4328e7e.png)

drawn manually, sorry friend.

**Comment by ShadowMario** [comment]
This isn't a font, it's an image, located at `assets/images/menudifficulties/`
