### ISSUE TITLE
bug with playing the game on html5

### ISSUE THREAD

**Issue by ThatDisabledKid** [ShadowMario/FNF-PsychEngine#4296]
### Describe your bug here.

when I try to play a song on story mode or freeplay it freezes and it won't let me play 

### Command Prompt/Terminal logs (if existing)

```bash
[lime.utils.Assets] Error: there is no sound asset with an ID of "assets/songs/senpai/Inst.mp3"
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Theoyeah** [comment]
ogg songs need to be replaced with mp3 songs
