### ISSUE TITLE
custom 3 2 1 check box

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#4297]
### What feature do you want to get added on the **base** engine?

it can be a check box that when clicked you have to select 4 file each being the different parts of the start up. when your done and play the song it will play the custom start up. Could help make future mods a little bit unique

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MayoALT** [comment]
already do-able in lua
