### ISSUE TITLE
How to unlock mouse ?

### ISSUE THREAD

**Issue by Theoyeah** [ShadowMario/FNF-PsychEngine#4301]
### Describe your problem here.

I wanna use a cursor and make make it interactive with the menu. 
How do i do that ?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by zLightc** [comment]
Read [this.](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#mouse-click-functions)
and to show the mouse use setPropertyFromClass('flixel.FlxG', 'mouse.visible', true); --true means show the mouse false means hide it
