### ISSUE TITLE
Now how to add animation on different arrows (Instant note example)

### ISSUE THREAD

**Issue by Agent307** [ShadowMario/FNF-PsychEngine#4304]
### What is your question?

now i was wondering how to add a script of lua or something that make the animation possible. (EX. when instant note reach to the arrows the opponent start using his attacks animation and some effects like shake a little bit) if you got any idea how to do it will be much appreciated! if you dont know what is script for use dont sweat it i thought you may knew! thx!

**Comment by zLightc** [comment]
I dont know about the script but it is possible with the custom notetypes folder in mods _(if you are modding in lua)_ but you can just search for a tutorial. _**However**_ if you are modding source its a little more complicated, you hwve to add thenotetype in the note state or something hx folder, you can also search for a tutorial about that.

**_I hope this helps!_**
