### ISSUE TITLE
Now you should add this on the Charting Menu

### ISSUE THREAD

**Issue by Agent307** [ShadowMario/FNF-PsychEngine#4305]
### What feature do you want to get added on the **base** engine?

Now here is my idea: when you were charting you cant know if you are dead or not (like a healthdrain that making it issue) if that boyfriend died it can detect where he dies (if he dies the rest of the boxes(where all of the arrows put) turn red) so the modding will be more advanced and easier!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by MayoALT** [comment]
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)
HOW
![image](https://user-images.githubusercontent.com/94536972/152400082-433834b6-8441-4207-b4b0-c0862ad0233a.png)

**Comment by PoleyMagik** [comment]
> ### What feature do you want to get added on the **base** engine?
> Now here is my idea: when you were charting you cant know if you are dead or not (like a healthdrain that making it issue) if that boyfriend died it can detect where he dies (if he dies the rest of the boxes(where all of the arrows put) turn red) so the modding will be more advanced and easier!
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Useful feature

...What?

Also sight test fail, lol.

**Comment by ImaginationSuperHero528** [comment]
Toggle practice mode

**Comment by ImaginationSuperHero528** [comment]
> ### What feature do you want to get added on the **base** engine?
> 
> Now here is my idea: when you were charting you cant know if you are dead or not (like a healthdrain that making it issue) if that boyfriend died it can detect where he dies (if he dies the rest of the boxes(where all of the arrows put) turn red) so the modding will be more advanced and easier!
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> 
> Useful feature

You toggle practice mode. If you die with it on you can't heal.
