### ISSUE TITLE
Cutscene help

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#4308]
### Describe your problem here.

so maybe you've seen this: https://github.com/ShadowMario/FNF-PsychEngine/issues/4277
and apparently you can do this already. How? any tutorial?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes source and assets

**Comment by ShadowMario** [comment]
Hide the characters, spawn the cutscene sprites.
