### ISSUE TITLE
Countdown after pressing enter

### ISSUE THREAD

**Issue by Larnny** [ShadowMario/FNF-PsychEngine#4310]
### What feature do you want to get added on the **base** engine?

Little "3 2 1" countdown after exiting pause menu, 
useful in situations like this:
![изображение](https://user-images.githubusercontent.com/67014977/152335570-d6195a72-ea36-4016-a7cb-cec90f6af8e9.png)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by BombasticTom** [comment]
use lua
