### ISSUE TITLE
HELP ME WITH THIS Expected }

### ISSUE THREAD

**Issue by SAB236YT** [ShadowMario/FNF-PsychEngine#4314]
### What is your question?

Why is this always saying
**source/MainMenuState.hx:360: characters 2-11 : Expected }** 
Please help me THIS IS FREAKING ME OUT 
**BEFORE YOU SAY ANITHYNG I ALREADY TRIED TO PUT A { BEFORE THE** _menuItems.forEach(function(spr:FlxSprite)_
**BUT IT DOES NOT WORK** 

HELP MEEEEEEEEEEEEEEEEEE

**Comment by SAB236YT** [comment]
HELP ME

**Comment by ShadowMario** [comment]
Show code on MainMenuState.hx line 350 to 370.

**Comment by SAB236YT** [comment]
{menuItems.forEach(function(spr:FlxSprite)
		{
			spr.animation.play('idle');

			if (spr.ID == curSelected && finishedFunnyMove)
			{
				spr.animation.play('selected');
				//camFollow.setPosition(spr.getGraphicMidpoint().x, spr.getGraphicMidpoint().y);
			}

			spr.updateHitbox();
		});
	}
}

**Comment by ShadowMario** [comment]
Please show an screenshot instead or just send the entire code

**Comment by SAB236YT** [comment]
k

**Comment by SAB236YT** [comment]
![Cattura](https://user-images.githubusercontent.com/98963514/152364837-93f86a03-55e6-4a9b-b77a-4e66060a7269.PNG)

**Comment by SAB236YT** [comment]
here

**Comment by ShadowMario** [comment]
Can you just send MainMenuState.hx as i said before?

**Comment by SAB236YT** [comment]
[MainMenuState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7995688/MainMenuState.txt)
in txt bc github does not support HXs

**Comment by ShadowMario** [comment]
[MainMenuState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7995780/MainMenuState.txt)
If this fixes the issue, please close this post

**Comment by SAB236YT** [comment]
it still gives me the error

**Comment by ShadowMario** [comment]
[MainMenuState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7995921/MainMenuState.txt)
Confirmed that it's working now.
