### ISSUE TITLE
Cannot go into freeplay ore story mode when I export mod as html5

### ISSUE THREAD

**Issue by SaltedSporks** [ShadowMario/FNF-PsychEngine#4315]
### Describe your bug here.

Hello!
I'm trying to export into html5 but when it's exported I am unable to go into Freeplay and StoryMode . (I get a black screen when I enter Freeplayand StoryMode ).

I tried to change the things that the command prompt pointed out ,however, it breaks the html5 build even more and doesn't allow an export at all when I do change these .hx files into the recommended code

This error only occurs when I export as "lime test html5", everything works fine when I use "lime test windows" 
Currently building with source but there is a lot of LUA used because of how many midevents there are in the first stage. 

**Bug Showcase:** (I chose StoryMode option, but this also happens with Freeplay)

![ezgif com-gif-maker (24)](https://user-images.githubusercontent.com/97844433/152366415-dfe8bb07-71e9-4624-b123-8999347b959c.gif)

The only buttons that do work are: Credits and Options right now. 
Not sure if this is important but the Programming languages are: C 50% , Haxe 45.6%, C++ 3.8%, Other 0.1% ! 
Engine ver: v0.4.2 

Another thing is that when I do enter into freeplay/storymode the music continues to play, however, everything else visually is not interactable. (Can't exit the area either)

### Command Prompt/Terminal logs (if existing)

```bash
PS D:\Active\FNF MODS\Messwith\Dont-Get-Spooked-DevCode-main\Dont-Get-Spooked-DevCode-main> lime test html5
source/Achievements.hx:146: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

source/MainMenuState.hx:53: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

source/PlayState.hx:247: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

source/editors/CharacterEditorState.hx:93: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

source/editors/DialogueCharacterEditorState.hx:82: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

We overhauled the PlayState.hx (Adding a week in ), hid the Achievements.hx in the build (Made it invisible in main menu but didn't delete the .hx)

**Comment by Theoyeah** [comment]
PS D:\Active\FNF MODS\Messwith\Dont-Get-Spooked-DevCode-main\Dont-Get-Spooked-DevCode-main> lime test html5
source/Achievements.hx:146: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

source/MainMenuState.hx:53: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

source/PlayState.hx:247: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

source/editors/CharacterEditorState.hx:93: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

source/editors/DialogueCharacterEditorState.hx:82: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead






It is normal if these logs appears

**Comment by SaltedSporks** [comment]
I see, I'll keep note of that! 
I'll see if something else is the case then since this issue still occurs even when  everything is normal.

**Comment by SaltedSporks** [comment]
> PS D:\Active\FNF MODS\Messwith\Dont-Get-Spooked-DevCode-main\Dont-Get-Spooked-DevCode-main> lime test html5 source/Achievements.hx:146: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
> 
> source/MainMenuState.hx:53: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
> 
> source/PlayState.hx:247: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
> 
> source/editors/CharacterEditorState.hx:93: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
> 
> source/editors/DialogueCharacterEditorState.hx:82: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
> 
> It is normal if these logs appears

I see, I'll keep note of that!
I'll see if something else is the case then since this issue still occurs even when everything is normal.
