### ISSUE TITLE
compiling issue

### ISSUE THREAD

**Issue by zLightc** [ShadowMario/FNF-PsychEngine#4316]
### Describe your problem here.

basically I get this error when using `lime test windows -debug` :

![compile issue psycheee](https://user-images.githubusercontent.com/96623600/152372403-b328e92c-e548-4876-b940-1b9a15c049b3.PNG)

I tried checking the applicationMain.hx but idk what to do idk how to code lol.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Carlitosmorecom** [comment]
if you still have this issue, delete the export folder and recompile

**Comment by zLightc** [comment]
I already tried with and without debug export, and i think the problem is that my zip corrupted while downloading from github but i just used a repair tool but it still doesnt work. Can anyone provide a full clean version of the source in google drive or something.
I would appreciate it!
