### ISSUE TITLE
@ShadowMario please help please

### ISSUE THREAD

**Issue by Theoyeah** [ShadowMario/FNF-PsychEngine#4317]
### Describe your problem here.

I need to know how do i unlock the mouse and make it work with the menus.

And how to i add a loading screen like in html5 for desktop (fully working with the mods folder)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by main-thing** [comment]
Read  [this.](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#mouse-click-functions) 
and to show the mouse use `setPropertyFromClass('flixel.FlxG', 'mouse.visible', true); --true means show the mouse false means hide it`

**Comment by main-thing** [comment]
Oh wait you're usin source oops.

> Read [this.](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#mouse-click-functions) and to show the mouse use `setPropertyFromClass('flixel.FlxG', 'mouse.visible', true); --true means show the mouse false means hide it`

**Comment by Theoyeah** [comment]
so how do i fix that
