### ISSUE TITLE
I CANT PLAY FNF MODS HEEELP

### ISSUE THREAD

**Issue by Sebasyn0se** [ShadowMario/FNF-PsychEngine#4319]
### Describe your bug here.

Ok I'll tell you the full story:

I did a cover of a song of 4 minutes and the characters wouldn't load, I restarted the game and it was fixed, but when I tried to play it a second time, the game froze, I tried to close it with classic alt+f4, opening the task manager and nothing worked, I had to restart my pc.
Now every time I enter the mod the game goes to 10 fps, and not only the mod or the psych engine ALL THE MODS go like that, I already restarted my pc like 3 times and nothing happens.
I know that the problem is not performance because my pc runs games like Valorant or Fortnite without problems. I guess it's because some fnf file was corrupted or something like that, if you know how to fix it please tell me how because I can't play any fnf mod

(Sorry for the bad english, im using a translator)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I just deleted some options from the menu, and easy and normal difficult

**Comment by Theoyeah** [comment]
ummm
Try to delete the shadowmario folder in %appdata%

**Comment by Sebasyn0se** [comment]
Ok i just needed to update my Windows version
