### ISSUE TITLE
getProperty and setProperty do not work properly for classes in playstate

### ISSUE THREAD

**Issue by i-winxd** [ShadowMario/FNF-PsychEngine#4330]
### Describe your bug here.

``getProperty`` and ``setProperty``do not work for classes within playstate. While this works for non-classes, it may not work for classes. Here's an example:

![image](https://user-images.githubusercontent.com/31808925/152429005-b4c6793d-c560-4bf0-9f5e-a1b0660640df.png)
![image](https://user-images.githubusercontent.com/31808925/152429168-d6cd5d26-1e86-45d6-8ece-a794e760f066.png)

**Getter callbacks for these two variables are called** __**AT THE SAME TIME**__. Expected is that both return the same value, but they actually return different values.
According to the wiki, ``cameraX`` is an alias to ``getProperty(camFollowPos.x)``.
Note: in debug print, the latest messages are printed on the top.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No modifications. Done in psych engine 0.5.1

**Comment by frantastic24** [comment]
it does work, but onCreate happens before the camera is properly loaded
onCreate
![image](https://user-images.githubusercontent.com/95725102/152442823-96dfa4df-41af-4172-bfca-5b93f4c2d7c0.png)
onSongStart
![image](https://user-images.githubusercontent.com/95725102/152442875-94b3fcd5-9f78-4340-a456-751d985aabbe.png)

**Comment by flashintv** [comment]
> `getProperty` and `setProperty`do not work for classes within playstate. While this works for non-classes, it may not work for classes.

You're just not inputing the variable names as a string, that's all.

**Comment by i-winxd** [comment]
Oh right
except for ``scoreTxt.text``, it doesn't seem to work at all

**Comment by frantastic24** [comment]
scoreTxt is a bit of a bitch because it's under onUpdate, so you pretty much have to set it back every time it updates through the whole song

**Comment by frantastic24** [comment]
Anyways this is not a bug so you should close this

**Comment by i-winxd** [comment]
***DISPUTE***
Whether ``onCreate`` and ``onSongStart`` was called first **has nothing to do with this issue.** I've updated this issue for increased clarification.

**Comment by frantastic24** [comment]
What?? It's literally the reason you're not getting the value you want, because there is no value
Getters and setters work as they're supposed to, this is an error from your part

**Comment by i-winxd** [comment]
oop, found the problem. has to be done on ``onUpdatePost``. my bad.
