### ISSUE TITLE
Add Option hit sound

### ISSUE THREAD

**Issue by UnderFellSansRed** [ShadowMario/FNF-PsychEngine#4347]
### What feature do you want to get added on the **base** engine?

That they add a hit sound option in gameplay and configure its volume

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by maxisepYT1** [comment]
Honestly for me it is a good idea to implement it, **I support you** :)

**Comment by MayoALT** [comment]
Honestly for me it is a good idea to implement it, **I support you** :)

**Comment by PoleyMagik** [comment]
> ### What feature do you want to get added on the **base** engine?
> That they add a hit sound option in gameplay and configure its volume
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> A good idea

Hmm, failed sight test. Uhh anyways it's a fine enough idea.

**Comment by tposejank** [comment]
YOu can do this on lua
