### ISSUE TITLE
Character Editor Crash

### ISSUE THREAD

**Issue by RamRomGuy** [ShadowMario/FNF-PsychEngine#435]
I am not sure if this is a bug or a glitch, but, I was watching bbpanzu's tutorial on this engine and wanted to try it. When I was reloading the images with my character's name on it, the game crashed, I checked directories, the name and everything seemed to be fine, it keeps happening, the image is in mods/images/characters but it still crashes! I would rlly appreciate some help

**Comment by ShadowMario** [comment]
Your .xml file is fucked up

**Comment by RamRomGuy** [comment]
> Your .xml file is fucked up

thx bro
