### ISSUE TITLE
How does the "Note Texture" work?

### ISSUE THREAD

**Issue by GamingFan3926** [ShadowMario/FNF-PsychEngine#4351]
### Describe your problem here.

I recently got into Psych Engine Modding, but I can't figure out how to use the Note Texture feature in the Song tab of the chart editor. I want to change the note's texture to the pixel one, and I assume it's possible through Note Texture because of the name.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by Stilic** [comment]
It is for use custom note sprites.

**Comment by GamingFan3926** [comment]
Oh. Okay. Thanks for the help!
