### ISSUE TITLE
How to unlock mouse on fnf menus (NO LUA PLEASE)

### ISSUE THREAD

**Issue by Theoyeah** [ShadowMario/FNF-PsychEngine#4352]
### Describe your problem here.

the title say everything
@ShadowMario help me plz if you can (no lua)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by trayfellow** [comment]
pretty sure you can just add

FlxG.mouse.visible = true;

on the 'override function create()' part of the main menu code

**Comment by Theoyeah** [comment]
ok, i gonna try this

**Comment by facundomax** [comment]
It dosen't work, i try it

**Comment by Theoyeah** [comment]
Can it interact with the boutons like store mode ?

**Comment by Theoyeah** [comment]
OK thanks

**Comment by Theoyeah** [comment]
0.5.1

**Comment by NokioPyro** [comment]
It should be #if windows.

**Comment by Theoyeah** [comment]
ok

**Comment by Theoyeah** [comment]
there where no #if windows but i added and it compiles correctly

**Comment by Theoyeah** [comment]
I will pick up some cloud full week code so so i can use my mouse
