### ISSUE TITLE
chart mode menu

### ISSUE THREAD

**Issue by thedeveloper112206** [ShadowMario/FNF-PsychEngine#4361]
### What feature do you want to get added on the **base** engine?

after you clear a song in charting mode right now it just takes you back to the chart menu. i would like an option to just quit the song after clearing it in charting mode. maybe a menu asking if you want to go back you chart editor or exit song.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by PersonNanoexe** [comment]
woah you spend 10 more seconds in the charter, thats crazy. Unnecessary change tbh

**Comment by ShadowMario** [comment]
Lazyness is a burden
