### ISSUE TITLE
Offsets for Animated Lua Sprites

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#4365]
### What is your question?

So I made a script a week or so ago which makes multiple characters able to sing at the same time without replacing girlfriend
here it is #3567

I'm wondering if there's anyway to add offsets to a lua animation so that it isn't all jittery
`addAnimationByPrefix('gray', 'singLEFT', 'left', 24, false);`
so here I would be able to put the x offset of the animation and the y offset of the animation

is this possible in any way?

**Comment by tposejank** [comment]
setProperty('gray.offset.x', 10)
