### ISSUE TITLE
reload audio not working?

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#4367]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/93293747/152572247-47808f7c-a555-4092-9fcd-acbb18a18bf2.png)
I have the instrumental in the correct folder

the name of the song is "striketheearth", when I press reload audio the song length goes to 0 as if the song doesn't exist
I've tried restarting the game and renaming the folder in case that's the problem.

### Command Prompt/Terminal logs (if existing)

```bash
no
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nuh uh

**Comment by frantastic24** [comment]
Likely a bad file, if not give more information
