### ISSUE TITLE
How to change "local yy + xx" for camera movment.

### ISSUE THREAD

**Issue by NesDoesGithub** [ShadowMario/FNF-PsychEngine#4368]
### Describe your problem here.

I am making the camera move when you press a note, and there is a point in the song where my characters change positions, but the camera just stays in the same spot. How can I change the "local xx + yy" .

Here is my code.

local xx = 550;
local yy = 500;
local xx2 = 900;
local yy2 = 550;
local ofs = 50;
local followchars = true;
local del = 0;
local del2 = 0;

function onUpdate()

    if del > 0 then
		del = del - 1
	end
	if del2 > 0 then
		del2 = del2 - 1
	end
    if followchars == true then
        if mustHitSection == false then
            if getProperty('dad.animation.curAnim.name') == 'singLEFT' then
                triggerEvent('Camera Follow Pos',xx-ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singRIGHT' then
                triggerEvent('Camera Follow Pos',xx+ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singUP' then
                triggerEvent('Camera Follow Pos',xx,yy-ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singDOWN' then
                triggerEvent('Camera Follow Pos',xx,yy+ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singLEFT-alt' then
                triggerEvent('Camera Follow Pos',xx-ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singRIGHT-alt' then
                triggerEvent('Camera Follow Pos',xx+ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singUP-alt' then
                triggerEvent('Camera Follow Pos',xx,yy-ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singDOWN-alt' then
                triggerEvent('Camera Follow Pos',xx,yy+ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'idle-alt' then
                triggerEvent('Camera Follow Pos',xx,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'idle' or getProperty('dad.animation.curAnim.name') == 'danceLeft' then
                triggerEvent('Camera Follow Pos',xx,yy)
            end
        else

            if getProperty('boyfriend.animation.curAnim.name') == 'singLEFT' then
                triggerEvent('Camera Follow Pos',xx2-ofs,yy2)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT' then
                triggerEvent('Camera Follow Pos',xx2+ofs,yy2)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singUP' then
                triggerEvent('Camera Follow Pos',xx2,yy2-ofs)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN' then
                triggerEvent('Camera Follow Pos',xx2,yy2+ofs)
            end
	    if getProperty('boyfriend.animation.curAnim.name') == 'idle' then
                triggerEvent('Camera Follow Pos',xx2,yy2)
          end
        end
    end

function onStepHit()

    if curStep == 4 then
        local yy = 1000;
    end 

(There is more code down below but it's unrelated)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by MayoALT** [comment]
use [this](https://github.com/ShadowMario/FNF-PsychEngine/discussions/4321) version of the code, its automatic

**Comment by frantastic24** [comment]
For future reference, `local` is only used when you first create the variable, every other time you can just use the variable name to set its value

**Comment by MayoALT** [comment]
> For future reference, `local` is only used when you first create the variable, every other time you can just use the variable name to set its value

no its not

**Comment by frantastic24** [comment]
you're a week late, and yes it is lol

**Comment by mayo78** [comment]
> you're a week late, and yes it is lol

[bro](https://www.lua.org/pil/4.2.html)

**Comment by frantastic24** [comment]
That literally proves my point but ok

**Comment by mayo78** [comment]
if you run [this script](https://github.com/ShadowMario/FNF-PsychEngine/discussions/4787) it will work and the variable `noteTex` will read correctly because you dont fucking need local before a variable its just used for functions and if statements and shit

**Comment by frantastic24** [comment]
When did I say you need it

**Comment by frantastic24** [comment]
point where "need" is, if you can
what i said was that it's used when setting up a variable, there is no "need" to have it, but it's only used there
what i said is true, you just didn't read
