### ISSUE TITLE
pixel dialogues

### ISSUE THREAD

**Issue by ukraineman345** [ShadowMario/FNF-PsychEngine#4370]
### What feature do you want to get added on the **base** engine?

Pixel dialogues work for custom songs, like
corruption dead pixel in physch engine with a dialogue where it shows senpai mad saying something with that pixel dialogue thing and pixel bf typing commands with that pixel dialogue thing and also this angry sound play where senpai becomes mad in roses and same with thorns thingy but with different char dialogue thing texture and senpai dying cutscene play.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by NokioPyro** [comment]
So pixel dialogue Antianialising Switch?

**Comment by frantastic24** [comment]
readability has left the chat

**Comment by ukraineman345** [comment]
> readability has left the chat

wdym

**Comment by ukraineman345** [comment]
I mean I need scripts that make a pixel dialogue with pixel text boxes play

**Comment by frantastic24** [comment]
The text was unnecessarily long

**Comment by ukraineman345** [comment]
> The text was unnecessarily long

funny

**Comment by frantastic24** [comment]
no

**Comment by ukraineman345** [comment]
> no

ok
so how

**Comment by NokioPyro** [comment]
deez nuts

**Comment by ukraineman345** [comment]
will someone fucking explain
