### ISSUE TITLE
Delay on title screen,

### ISSUE THREAD

**Issue by NokioPyro** [ShadowMario/FNF-PsychEngine#4372]
### Describe your bug here.

So no matter what on The action builds of pysch engine If I have it open or not, The title screen is delayed by about 2 seconds, It may be my laptop, But even if i use Just a normally built action build or whatever, It is delayed, I dont even have a mod installed, Thats the thing.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope,

**Comment by endorblue** [comment]
you can change the BPM if you go into the assets/images/gfDanceTitle

**Comment by NokioPyro** [comment]
Ive tried that, still doesnt work, Its because theres an extra case and more text, delaying it,

**Comment by AdmiralKirby** [comment]
> you can change the BPM if you go into the assets/images/gfDanceTitle

Thats only for the BPM of the sprites not the song.

I just started having this problem too, I dont know what caused it.

**Comment by NokioPyro** [comment]
What i mean is the text,
Where it says Something like
"coolswag suck my nuts"
And then
"Friday night funkin"
Then the white flash
