### ISSUE TITLE
chart speed

### ISSUE THREAD

**Issue by pln2009** [ShadowMario/FNF-PsychEngine#4377]
### Describe your bug here.

i don't know why, but somehow my chart speed is always the same. i didn't change anything, I didn't mod anything, but it happens. like, look at this: it's m.i.l.f. on hard mod
![Immagine 2022-02-04 220101](https://user-images.githubusercontent.com/76397093/152602587-c7fb0bc9-49bb-4764-96d2-639c1c51a8ef.png)
e
game source:
(https://www.mediafire.com/file/jgsnvjd3smupsz2/FNF-PsychEngine-main.zip/file)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by lemz1** [comment]
when you are in freeplay go to any song and press ctrl and change constant to multiplicative. Atleast I think this is the problem

**Comment by pln2009** [comment]
thank you
