### ISSUE TITLE
Compile not Working!

### ISSUE THREAD

**Issue by 6160mas** [ShadowMario/FNF-PsychEngine#438]
when it's almost done compiling it says this:

Error: VlcBitmap.cpp
D:/fnf-psychengine-042_f4393/FNF-PsychEngine-0.4.2/source/vlc/cpp/src/LibVLC.cpp(5): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory

I don't know what to do help me.

**Comment by ShadowMario** [comment]
https://gamebanana.com/tuts/13653
You've missed something
