### ISSUE TITLE
Game closes when you get game over

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#4383]
### Describe your problem here.

how can i make it so the game closes when you get game over (if its possible)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by juanroman74454811** [comment]
this line of code close() (only closes automatticly

**Comment by PDL2CGamejolt** [comment]
> this line of code close() (only closes automatticly

what do you mean?

**Comment by juanroman74454811** [comment]
> > this line of code close() (only closes automatticly
> 
> what do you mean?

the line of code called close() only closes the game

**Comment by PDL2CGamejolt** [comment]
> > > this line of code close() (only closes automatticly
> > 
> > 
> > what do you mean?
> 
> the line of code called close() only closes the game

Exactly! how do i use it

**Comment by PDL2CGamejolt** [comment]
how do i use the code? and is there a wait code

**Comment by juanroman74454811** [comment]
> how do i use the code? and is there a wait code

type close() on script.lua

**Comment by juanroman74454811** [comment]
> > > > this line of code close() (only closes automatticly
> > > 
> > > 
> > > what do you mean?
> > 
> > 
> > the line of code called close() only closes the game
> 
> Exactly! how do i use it

type close() on script.lua

**Comment by PDL2CGamejolt** [comment]
> 

is there a wait code?

**Comment by juanroman74454811** [comment]
> > 
> 
> is there a wait code?

no.

**Comment by PDL2CGamejolt** [comment]
How do i use it, with a Function code as in--

**Comment by PDL2CGamejolt** [comment]
I think that close code is for the SCRIPT
