### ISSUE TITLE
BeatHit Editor

### ISSUE THREAD

**Issue by juanroman74454811** [ShadowMario/FNF-PsychEngine#4394]
### What feature do you want to get added on the **base** engine?

I would like a BeatHit Editor

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by mayo78** [comment]
![image](https://user-images.githubusercontent.com/75394229/152627937-f25d072c-5600-49cf-9893-10c6ce0dbb26.png)
why did you pick that, what went through your mind as you picked the obviously wrong answer what is wrong with you why are you like this

**Comment by juanroman74454811** [comment]
> ![image](https://user-images.githubusercontent.com/75394229/152627937-f25d072c-5600-49cf-9893-10c6ce0dbb26.png) why did you pick that, what went through your mind as you picked the obviously wrong answer what is wrong with you why are you like this

fuck you

**Comment by lemz1** [comment]
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> 
> Useful feature

Yeah a useful feature shouldn't be requested.

**Comment by juanroman74454811** [comment]
FUCK YOU GUYS FUCK YOU

**Comment by supajimmy** [comment]
> FUCK YOU GUYS FUCK YOU

Yo chill tf out man

**Comment by mayo78** [comment]
> FUCK YOU GUYS FUCK YOU

![diamond_sex_2000k](https://user-images.githubusercontent.com/75394229/152705310-2aab18f9-48a3-4f27-83c3-81dda2beb52d.gif)

**Comment by juanroman74454811** [comment]
> > FUCK YOU GUYS FUCK YOU
> 
> ![diamond_sex_2000k](https://user-images.githubusercontent.com/75394229/152705310-2aab18f9-48a3-4f27-83c3-81dda2beb52d.gif)

![Quote_o](https://user-images.githubusercontent.com/92176733/152797566-27c4c752-0fdc-4b65-a57e-e4bc7d2aa152.png)

**Comment by juanroman74454811** [comment]
> > FUCK YOU GUYS FUCK YOU
> 
> ![diamond_sex_2000k](https://user-images.githubusercontent.com/75394229/152705310-2aab18f9-48a3-4f27-83c3-81dda2beb52d.gif)

![Quote](https://user-images.githubusercontent.com/92176733/152797652-bc0fb291-8a0c-4bb3-b25e-28bb5e979350.png)

**Comment by MayoALT** [comment]
> > > FUCK YOU GUYS FUCK YOU
> > 
> > 
> > ![diamond_sex_2000k](https://user-images.githubusercontent.com/75394229/152705310-2aab18f9-48a3-4f27-83c3-81dda2beb52d.gif)
> 
> ![Quote](https://user-images.githubusercontent.com/92176733/152797652-bc0fb291-8a0c-4bb3-b25e-28bb5e979350.png)

### ratio
![diamond_sex_2000k](https://user-images.githubusercontent.com/75394229/152705310-2aab18f9-48a3-4f27-83c3-81dda2beb52d.gif)

**Comment by mayo78** [comment]
> > > > > FUCK YOU GUYS FUCK YOU
> > > > 
> > > > 
> > > > ![diamond_sex_2000k](https://user-images.githubusercontent.com/75394229/152705310-2aab18f9-48a3-4f27-83c3-81dda2beb52d.gif)
> > > 
> > > 
> > > ![Quote](https://user-images.githubusercontent.com/92176733/152797652-bc0fb291-8a0c-4bb3-b25e-28bb5e979350.png)
> > 
> > 
> > ### ratio
> > ![diamond_sex_2000k](https://user-images.githubusercontent.com/75394229/152705310-2aab18f9-48a3-4f27-83c3-81dda2beb52d.gif)
> 
> i hope quote shooted you for no reason

![diamond_sex_2000k](https://user-images.githubusercontent.com/75394229/152705310-2aab18f9-48a3-4f27-83c3-81dda2beb52d.gif)

### ratio

**Comment by juanroman74454811** [comment]
> > > > > > FUCK YOU GUYS FUCK YOU
> > > > > 
> > > > > 
> > > > > ![diamond_sex_2000k](https://user-images.githubusercontent.com/75394229/152705310-2aab18f9-48a3-4f27-83c3-81dda2beb52d.gif)
> > > > 
> > > > 
> > > > ![Quote](https://user-images.githubusercontent.com/92176733/152797652-bc0fb291-8a0c-4bb3-b25e-28bb5e979350.png)
> > > 
> > > 
> > > ### ratio
> > > ![diamond_sex_2000k](https://user-images.githubusercontent.com/75394229/152705310-2aab18f9-48a3-4f27-83c3-81dda2beb52d.gif)
> > 
> > 
> > i hope quote shooted you for no reason
> 
> ![diamond_sex_2000k](https://user-images.githubusercontent.com/75394229/152705310-2aab18f9-48a3-4f27-83c3-81dda2beb52d.gif)
> ### ratio

![a](https://user-images.githubusercontent.com/92176733/153726695-60929379-958c-49f1-8cb2-736fcca5391d.jpg)

**Comment by juanroman74454811** [comment]
> > > > > > FUCK YOU GUYS FUCK YOU
> > > > > 
> > > > > 
> > > > > ![diamond_sex_2000k](https://user-images.githubusercontent.com/75394229/152705310-2aab18f9-48a3-4f27-83c3-81dda2beb52d.gif)
> > > > 
> > > > 
> > > > ![Quote](https://user-images.githubusercontent.com/92176733/152797652-bc0fb291-8a0c-4bb3-b25e-28bb5e979350.png)
> > > 
> > > 
> > > ### ratio
> > > ![diamond_sex_2000k](https://user-images.githubusercontent.com/75394229/152705310-2aab18f9-48a3-4f27-83c3-81dda2beb52d.gif)
> > 
> > 
> > i hope quote shooted you for no reason
> 
> ![diamond_sex_2000k](https://user-images.githubusercontent.com/75394229/152705310-2aab18f9-48a3-4f27-83c3-81dda2beb52d.gif)
> ### ratio

![fuck you](https://user-images.githubusercontent.com/92176733/153729024-4abd6bed-6056-47a2-a317-046b3bc82c9e.png)
