### ISSUE TITLE
apk convertion

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#4396]
### What feature do you want to get added on the **base** engine?

idk how but i think it would be cool if you were somehow able the make it able to be converted to apk for android or something

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Pico8430** [comment]
Might actually seems like a good idea, but i don't think thats possible. Also, fnf it's made on pcs, and you can encounter ports made by the community.

**Comment by frantastic24** [comment]
Android is not officially supported
