### ISSUE TITLE
menu editor 

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#4397]
### What feature do you want to get added on the **base** engine?

basically you know the place were you can go to the other editors?
I think there should be an editor for the selector screen itself
....ye that's it

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by supajimmy** [comment]
Tbh I think how this would work is that there is a screen where you have the options and storymode freeplay est and like it will be like the week editor or the other one where it will be like when you click on a thing like the mod thing it will bring up info on the thing and then it will be like Blah Blah blah storymode.png and stuff like the size and transparency but before this can be added they need to soft code menus witch yeah they kinda did but no way to edit things like the move the things. also neat thing that I thought of is to add .lua script into this so you can do things like on beat hit and stuff like that.

**Comment by creeperkidking** [comment]
k

**Comment by ShadowMario** [comment]
This is the stupidest idea i've heard this entire afternoon
