### ISSUE TITLE
LUA

### ISSUE THREAD

**Issue by SeriouslyAnimations** [ShadowMario/FNF-PsychEngine#4399]
### What is your question?

Hi, can someone write me or help me write a code for lua to play a sound as an event please the sound name is shoot.ogg

**Comment by mayo78** [comment]
the holiday mod has that event

**Comment by matt-sudo-jpg** [comment]
```
function onEvent(n)
if n == play shoot sound then
playSound('shoot', 1)
end
end
```

**Comment by tylerandari12** [comment]
Its Lua not LUA
The Lua devs are very sensitive about that.
