### ISSUE TITLE
Time bar in one song (this is other think)

### ISSUE THREAD

**Issue by facundomax** [ShadowMario/FNF-PsychEngine#4403]
### Describe your problem here.

(ok shadowmario, please don't close the unanswered questions, thanks) 

I have a code that creates a tween of the time bar, that is, it makes a backward movement in the middle of the song, in short, the bob and bosip time bar. the only thing I would like to do is... how do I make that code ONLY APPEAR IN ONE SINGLE SONG!!! ( NO SCRIPT) Thank you :)

### Are you modding a build from source or with Lua?

Source or lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Help this poor guy :,(

**Comment by main-thing** [comment]
Instead of putting it in scripts. Put it in the songs data folder. Example `data/yoursong/`

**Comment by SrtHero278** [comment]
![image](https://user-images.githubusercontent.com/93018286/152652882-7370a40c-eee9-40a0-a1a0-c1d5c060927e.png)
put the script in a data folder

**Comment by facundomax** [comment]
And i just put it in one song no in all songs

**Comment by KutikiPlayz** [comment]
just do 
if (curSong == "Your Song Name") {
	your code for tweening it and shit
}

**Comment by facundomax** [comment]
can i send it to you the code?

**Comment by facundomax** [comment]
i know then is in playstate but i don't know where xd
send me your discord to show you the code
