### ISSUE TITLE
How to change dialogue font

### ISSUE THREAD

**Issue by main-thing** [ShadowMario/FNF-PsychEngine#4407]
### Describe your problem here.

I know i can change lua text fonts, but how do I change the dialogue font? (using a .tff instead of a 
.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope. Just a pre-built version.

**Comment by bbpanzu** [comment]
dialogue doesn't use fonts. it uses the in. game alphabet.

you could edit the alphabet.fla in the art folder and rexport a new fontsheet

**Comment by main-thing** [comment]
thx
