### ISSUE TITLE
Dialogue after video cutsence

### ISSUE THREAD

**Issue by ArtiTheArtist** [ShadowMario/FNF-PsychEngine#4412]
### Describe your problem here.

Trying to figure out how to get dialogue to work after video

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Pico8430** [comment]
Put a script that plays a video onto your song chart and another script that runs the dialogue, each one will be named how you want to. It's kinda more easy that what it seems.
