### ISSUE TITLE
now how to remove the '3, 2, 1, GO!' on the start of a song?

### ISSUE THREAD

**Issue by Agent307** [ShadowMario/FNF-PsychEngine#4413]
### Describe your problem here.

now i was trying to find how to find a lua script that can remove the '3, 2, 1, GO!' vocals of a start of a song. do you have any idea???

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, didn't even check it.

**Comment by FanKid** [comment]
There is actually! The thing is that, you need the LATEST commit, not the downloaded version.

Here's a post that works - https://github.com/ShadowMario/FNF-PsychEngine/discussions/3532

Download tposejank's EK build that's has the variable working (warning, broken window bug) - https://gamebanana.com/mods/333373

**Comment by frantastic24** [comment]
If you just need to get rid of the sounds you can use `setProperty('introSoundsSuffix', -blank')` (-blank can be just about any string, if there isn't a countdown file with that suffix it will simply play nothing)
