### ISSUE TITLE
there was a bug where in 5.1 in the change game over screen on lua.

### ISSUE THREAD

**Issue by Agent307** [ShadowMario/FNF-PsychEngine#4414]
### Describe your bug here.

while I was trying to add some Lua when I check something when I died the song play perfectly fine but the death animations/sprites were normal (my sprite was different than the normal version of bf) it kinda looks like its either the engine or the lua. IDK actually what is the problem? do I have to change my engine? or get a new one? IDK what is the chose so I had to ask if this bug's still up.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, didn't even check it.

**Comment by frantastic24** [comment]
Show the Lua and the character, you're supposed to give information

**Comment by Agent307** [comment]
sorry i cant send it because its either not supported or too big

**Comment by frantastic24** [comment]
You can upload it to somewhere else (MediaFire, mega, etc)

**Comment by Agent307** [comment]
ok ill try hold on

**Comment by Agent307** [comment]
ok nvm i found out what is the problem and I fix it. the problem was neither the engine or the image itself. its actually the script itself come from the music (one of them at least) I deleted the script and I enter a new one and it fixes I actually found that because the script repeating itself (even if I deleted the text) its still repeating so I deleted and enter a new one and the problem is solved. thx for the help!

**Comment by Agent307** [comment]
and that script is broken that it affects the images of boyfriend

**Comment by frantastic24** [comment]
You can close this then

**Comment by Agent307** [comment]
wait how???

**Comment by Agent307** [comment]
sorry if im a dumb because first time using github

**Comment by Agent307** [comment]
The Issue was Closed
The Solution Was :
'ok nvm i found out what is the problem and I fix it. the problem was neither the engine or the image itself. its actually the script itself come from the music (one of them at least) I deleted the script and I enter a new one and it fixes I actually found that because the script repeating itself (even if I deleted the text) its still repeating so I deleted and enter a new one and the problem is solved, and that script is broken that it affects the images of boyfriend'
