### ISSUE TITLE
Game got crash during select in Freeplay or Story Mode 

### ISSUE THREAD

**Issue by afeefflox** [ShadowMario/FNF-PsychEngine#4415]
### Describe your bug here.

so, after the compiled game when I go to the Freeplay or Story Mode  (whatever) the game crash it...

### Command Prompt/Terminal logs (if existing)

```bash
idk It "Null Object Reference"
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I made Change Stage (it worked)

**Comment by BombasticTom** [comment]
you probably removed all the week jsons from the weeks folder. if you didn't idk then

**Comment by afeefflox** [comment]
nope :/

**Comment by frantastic24** [comment]
not enough information
