### ISSUE TITLE
no looping animations during a hold note

### ISSUE THREAD

**Issue by FoxyGamer1980** [ShadowMario/FNF-PsychEngine#4435]
### Describe your problem here.

as the title says, i want to figure out how to have the opponent to not loop it's sing animation while doing a hold note, simple as that

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i mainly edited playstate.hx

**Comment by bbpanzu** [comment]
psuedo code:

for every unspawnNote{
     if note is sus{
          note.noAnimation = true
      }
}

**Comment by FoxyGamer1980** [comment]
sorry bb, but i'm kinda confused on what you sent, like, do i add in the code into the playstate, or what?
