### ISSUE TITLE
Not Needing to Compile the game

### ISSUE THREAD

**Issue by SaltEFry69** [ShadowMario/FNF-PsychEngine#4444]
### What feature do you want to get added on the **base** engine?

not needing to compile the game

**Comment by supajimmy** [comment]
like step mania modchart stuff and a modchart editor

**Comment by XS09-dev** [comment]
You can't compile a source code without compiling. If you can't code and don't need to change any of the source code I suggest making whatever using the mods folder which is the pre-compiled version of the engine where you use lua and sometimes json to put a custom character, event, achievement, note type, data, fonts, images, music, scripts, songs, sounds, stages, videos, and finally weeks

**Comment by mayo78** [comment]
thats not how that works

**Comment by frantastic24** [comment]
I want this one to be hung up on my wall, it's great

**Comment by PoleyMagik** [comment]
> ### What feature do you want to get added on the **base** engine?
> not needing to compile the game

No. If you want to change something without compiling, use lua.

**Comment by ShadowMario** [comment]
That's how games work bozo
