### ISSUE TITLE
Offsets/PlayerOffsets

### ISSUE THREAD

**Issue by Hunter13n** [ShadowMario/FNF-PsychEngine#4447]
### What feature do you want to get added on the **base** engine?

okay so i added playerOffsets in the jsons an when your playing as that character it detects that your playing as that character switches offsets to playerOffsets, so when your offsetting your character n'shit, then click the box that says playable character, then do the offsets for that side, save it, then go back to that character an uncheck 'playable character' an click 'reload Char' an the numbers switchs offsets

https://user-images.githubusercontent.com/66497511/152661383-6107ac57-ca7e-4f21-ad2a-23f0d7f2efd2.mp4

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Hunter13n** [comment]
Last Chance for Me

**Comment by afeefflox** [comment]
It's a good idea but.... there is a problem about it because mostly dad and bf Anims are different
they were opposite Anims for singLEFT and singRIGHT

**Comment by Hunter13n** [comment]
> It's a good idea but.... there is a problem about it because mostly dad and bf Anims are different
> 
> they were opposite Anims for singLEFT and singRIGHT

I know an I made it where they don't have to change it

**Comment by ImaginationSuperHero528** [comment]
You failed the test

**Comment by ImaginationSuperHero528** [comment]
look where you put "a good idea" but this is a thing I've really been wanting

**Comment by Den198888** [comment]
i hope they see this this is a great idea

**Comment by supajimmy** [comment]
yoo this is sick

**Comment by Hunter13n** [comment]
> yoo this is sick

Thank you but theres a problem... im trying to put playerPositions an playerCamera an trying to figure out how to do that

**Comment by mayo78** [comment]
### WHY DID YOU PICK THIS

![image](https://user-images.githubusercontent.com/75394229/152705334-fe705748-92ce-4367-90f2-47cfb4af98e3.png)

**Comment by Hunter13n** [comment]
> ### WHY DID YOU PICK THIS
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/75394229/152705334-fe705748-92ce-4367-90f2-47cfb4af98e3.png)
> 
> 

Now look at it

**Comment by Hunter13n** [comment]
> ###

THERE I FIXED IT LOL

**Comment by ShadowMario** [comment]
Duplicate.

**Comment by ImaginationSuperHero528** [comment]
> Duplicate.

Gonna be honest you did this with fnf Multi... wth?
