### ISSUE TITLE
dont continue anything about mr fnf, delete this post

### ISSUE THREAD

**Issue by eRobLex** [ShadowMario/FNF-PsychEngine#4451]
dont continue anything about mr fnf, delete this post

_Originally posted by @NotBax in https://github.com/ShadowMario/FNF-PsychEngine/discussions/4449#discussioncomment-2118199_

we will have big issues.

**Comment by ImaginationSuperHero528** [comment]
> dont continue anything about mr fnf, delete this post
> 
> _Originally posted by @NotBax in [#4449 (comment)](https://github.com/ShadowMario/FNF-PsychEngine/discussions/4449#discussioncomment-2118199)_
> 
> we will have big issues.

Just delete it yourself... @eRobLex if I don't do this then you will probably never notice

**Comment by mayo78** [comment]
dont bring mr-fnf into the issues page

**Comment by NotBax** [comment]
what

**Comment by NotBax** [comment]
tf u mean by we will have issues

**Comment by NotBax** [comment]
fucking clown, learn to elaborate
