### ISSUE TITLE
now how to use the attack animation on the opponent?

### ISSUE THREAD

**Issue by Agent307** [ShadowMario/FNF-PsychEngine#4456]
### Describe your problem here.

I was trying to find on the internet how to use the attack animation (of the enemy) on a .Lua Script. does anyone have any idea to make him start using the animation??

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, didn't even check it.

**Comment by main-thing** [comment]
```
function onCreate()
--the middle value attack is nit the anim name in xml but the anim name in json like singUP
characterPlayAnim('dad', 'attack', true);
--this code makes it so the idle anim will not override the attack anim
setProperty('dad.specialAnim', true);
end
```
