### ISSUE TITLE
Is there a way to activate botplay with Lua?

### ISSUE THREAD

**Issue by Sebasyn0se** [ShadowMario/FNF-PsychEngine#4463]
### What is your question?

Is there a way to activate botplay with Lua?

If there is, can you tell me how?

**Comment by Itz-Miles** [comment]
You can set botplay to true by setting its bool in playstate to true. (ex. setProperty('cpuControlled', true))

**Comment by zLightc** [comment]
he said in lua @Itz-Miles

**Comment by lemz1** [comment]
> he said in lua @Itz-Miles

That is in lua

**Comment by Thedumbdude** [comment]
`function onEvent(name)
    if name == 'Turn on botplay' then
        setProperty('cpuControlled', true);
	setProperty('botplayTxt.visible', true);
    end
end`
