### ISSUE TITLE
Custom Stages appear black.

### ISSUE THREAD

**Issue by Swagwhisperer10** [ShadowMario/FNF-PsychEngine#4466]
### Describe your problem here.

I have the lua and json files in example_mods/stages and json in assets/preload/stages and the images come off of a week folder in assets/

But when I try to load them in-game the background is black but i can select the background in 7.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Ive added new difficulties and changed camera zooming to a stonger setting.

**Comment by main-thing** [comment]
Please provide the stages lua file. If it does not exist it will not show. Tutorial on making custom stages [here.](https://youtu.be/836rLdeW6GY)

**Comment by Swagwhisperer10** [comment]
[example_mods.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8010944/example_mods.zip)
[Assets.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8010945/Assets.zip)

**Comment by Swagwhisperer10** [comment]
The stages' images come off of a week folder instead of images folder. All the images are in a week folder like week3 and stuff. There are directories and lua's to make this work but it doesn't.

**Comment by main-thing** [comment]
The problem is that the lua files that make the stages dont even make sprites... You need to remake the stage in lua. [Stage template here.](https://cdn.discordapp.com/attachments/866856727621795850/900523259345371177/ExampleStage.zip)

**Comment by main-thing** [comment]
You need to put the images in mods/example_mods/images and then try.

**Comment by main-thing** [comment]
Show the source code for the stages "case:"

**Comment by Swagwhisperer10** [comment]
[source.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8019108/source.zip)

**Comment by Swagwhisperer10** [comment]
> Show the source code for the stages "case:"

I'm supposed to have a "case:" code somewhere in playstate? I thought This was handled by the game itself?

**Comment by main-thing** [comment]
Yes. If you go through the playstate you can see for example `case 'spooky': ` for week 2's background. Check if you have the sourcecode for the mod so that you can find the stages case.

**Comment by main-thing** [comment]
And copy it into the source

**Comment by main-thing** [comment]
You need to re add the case. Here's an example of a case in playstate. 
```case 'philly': //Week 3
				if(!ClientPrefs.lowQuality) {
					var bg:BGSprite = new BGSprite('philly/sky', -100, 0, 0.1, 0.1);
					add(bg);
				}
				
				//addShaderToCamera('game', chromAb);
				//chromAb.setChrome(0.01);

				var city:BGSprite = new BGSprite('philly/city', -10, 0, 0.3, 0.3);
				city.setGraphicSize(Std.int(city.width * 0.85));
				city.updateHitbox();
				add(city);

				phillyCityLights = new FlxTypedGroup<BGSprite>();
				add(phillyCityLights);

				for (i in 0...5)
				{
					var light:BGSprite = new BGSprite('philly/win' + i, city.x, city.y, 0.3, 0.3);
					light.visible = false;
					light.setGraphicSize(Std.int(light.width * 0.85));
					light.updateHitbox();
					phillyCityLights.add(light);
				}

				if(!ClientPrefs.lowQuality) {
					var streetBehind:BGSprite = new BGSprite('philly/behindTrain', -40, 50);
					add(streetBehind);
				}

				phillyTrain = new BGSprite('philly/train', 2000, 360);
				add(phillyTrain);

				trainSound = new FlxSound().loadEmbedded(Paths.sound('train_passes'));
				CoolUtil.precacheSound('train_passes');
				FlxG.sound.list.add(trainSound);

				var street:BGSprite = new BGSprite('philly/street', -40, 50);
				add(street);
```
Week3 stage so if you have the source for the mod just copy its case into the playstate.

**Comment by Swagwhisperer10** [comment]
They have not uploaded their source code yet, so I'm trying to add it alone myself.
I'm having issues like some sprites not actually loading. Can we screen share this it will be easier to do it!
Swagwhisperer10#9357

**Comment by main-thing** [comment]
oh then heres a tutorial on how to remake it.  https://gamebanana.com/tuts/14454

**Comment by Swagwhisperer10** [comment]
issue though
There are multiple sprites for layers and some are animated

**Comment by main-thing** [comment]
> They have not uploaded their source code yet, so I'm trying to add it alone myself. I'm having issues like some sprites not actually loading. Can we screen share this it will be easier to do it! Swagwhisperer10#9357

sure
