### ISSUE TITLE
a very big bug

### ISSUE THREAD

**Issue by choctid** [ShadowMario/FNF-PsychEngine#4485]
### Describe your bug here.

there is a bug that does not activate the Game over...

https://user-images.githubusercontent.com/93372605/152691826-38087b03-8ae3-4aa7-9465-9eb2a33ff72a.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

non

**Comment by frantastic24** [comment]
You didn't give any information, report a bug properly or don't report

**Comment by blueDev2** [comment]
If you did touch anything in Lua, It specifically says to not touch the variable "isdead" using Lua.
Obviously, though, you did do something since that's not the base psych engine.

**Comment by endorblue** [comment]
if you are using a custom death screen and the engine cant find it it will not do the gameover state or are you in practise mode

**Comment by SwiftRasin** [comment]
what if practice mode is on?
