### ISSUE TITLE
How to layer custom stage images?

### ISSUE THREAD

**Issue by JavoniCraft** [ShadowMario/FNF-PsychEngine#4487]
### Describe your problem here.

How do I layer custom stage elements/images? The characters are overlapping the curtains
![Screenshot 2022-02-06 12 06 21 PM](https://user-images.githubusercontent.com/90878766/152692212-23f04dd9-e231-4e6b-9307-c015b0c16bec.png)
.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I made a mod and custom stage.

**Comment by frantastic24** [comment]
If you want a sprite to be on top of the characters do `addLuaSprite('tag', true)`, the `true` tells the game to add the sprite on top of other objects in the same camera (it's set to false by default)

**Comment by JavoniCraft** [comment]
> If you want a sprite to be on top of the characters do `addLuaSprite('tag', true)`, the `true` tells the game to add the sprite on top of other objects in the same camera (it's set to false by default)

Thx
