### ISSUE TITLE
playSound command not working on lua

### ISSUE THREAD

**Issue by ukraineman345** [ShadowMario/FNF-PsychEngine#4489]
### Describe your problem here.

pls help!!!!!!!!!! I coded everything right!!!
playSound('gunshot:String', 0.5);

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I made a complete mod but I need to fix that thing.

**Comment by CyndaquilDAC** [comment]
remove the :String

**Comment by ukraineman345** [comment]
> remove the :String

doesn't work either

**Comment by frantastic24** [comment]
You didn't code it right, and make sure it's inside mods/sounds or inside your mod's sound folder

**Comment by ukraineman345** [comment]
> You didn't code it right, and make sure it's inside mods/sounds or inside your mod's sound folder

send the right code then, and also it is located in mods/sounds

**Comment by frantastic24** [comment]
Someone already told you to remove :String, if that doesn't work for some reason then you must have messed up some other part of your code, but you didn't show what the rest looks like

**Comment by ukraineman345** [comment]
> Someone already told you to remove :String, if that doesn't work for some reason then you must have messed up some other part of your code, but you didn't show what the rest looks like

what do you mean

**Comment by frantastic24** [comment]
Code, show the whole thing

**Comment by ukraineman345** [comment]
> Code, show the whole thing

k

**Comment by ukraineman345** [comment]
> Code, show the whole thing

function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Bullet_Note' then --Check if the note on the chart is a Bullet Note
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'Bullet_Note'); --Change texture
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashHue', 0); --custom notesplash color, why not
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashSat', -20);
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashBrt', 1);

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', false); --Miss has penalties
			end
		end
	end
end

local shootAnims = {"singDOWN"}
function goodNoteHit(id, direction, noteType, isSustainNote)
	if noteType == 'Bullet_Note' then
		if difficulty == 2 then
			playSound('gunshot':String, 0.5);
		end
		characterPlayAnim('dad', shootAnims[direction + 1], true);
		characterPlayAnim('boyfriend', 'dodge', true);
		setProperty('boyfriend.specialAnim', true);
		setProperty('dad.specialAnim', true);
		cameraShake('camGame', 0.01, 0.2)
    end
end

function noteMiss(id, direction, noteType, isSustainNote)
	if noteType == 'Bullet_Note' and difficulty == 2 then
		setProperty('health', -1);
		playSound('gunshot', 0.5);
	elseif noteType == 'Bullet_Note' and difficulty == 1 then
		setProperty('health', getProperty('health')-0.8);
		runTimer('bleed', 0.2, 20);
		playSound('hankded', 0.6);
		characterPlayAnim('boyfriend', 'hurt', false);
	end
end

function onTimerCompleted(tag, loops, loopsLeft)
	-- A loop from a timer you called has been completed, value "tag" is it's tag
	-- loops = how many loops it will have done when it ends completely
	-- loopsLeft = how many are remaining
	if loopsLeft >= 1 then
		setProperty('health', getProperty('health')-0.001);
	end
end

**Comment by ukraineman345** [comment]
hello?

**Comment by frantastic24** [comment]
are you getting an error or is it just not working because
1) you still have :String in goodNoteHit
2) this looks like it should work, so either your sound file is wrong or it's something else

**Comment by main-thing** [comment]
Just send your script and we can tell the problem

**Comment by ukraineman345** [comment]
> are you getting an error or is it just not working because
> 
> 1. you still have :String in goodNoteHit
> 2. this looks like it should work, so either your sound file is wrong or it's something else

but the file name is right
and the sound didn't play even without the :String

**Comment by Friskzips** [comment]
Try to make the sound file ogg and mp3

**Comment by ukraineman345** [comment]
> Try to make the sound file ogg and mp3

man it is already ogg bruh

**Comment by frantastic24** [comment]
Still don't see why this isn't working when the same code is working for me so we need more info
-Does it not play regardless of hit or miss?
-Does everything else in the code trigger properly?
-Are you playing in the right difficulty?
-If you made the sound yourself, have you tried re-exporting/reconverting?
-Does it also not work with other sounds?
-Have you tested this on another engine version?

**Comment by ukraineman345** [comment]
> Still don't see why this isn't working when the same code is working for me so we need more info -Does it not play regardless of hit or miss? -Does everything else in the code trigger properly? -Are you playing in the right difficulty? -If you made the sound yourself, have you tried re-exporting/reconverting? -Does it also not work with other sounds? -Have you tested this on another engine version?

I can only say that it worked on 0.4.2 but It is not working in 0.5.1

**Comment by frantastic24** [comment]
What about the other 5 questions, need more info

**Comment by ukraineman345** [comment]
> Still don't see why this isn't working when the same code is working for me so we need more info -Does it not play regardless of hit or miss? -Does everything else in the code trigger properly? -Are you playing in the right difficulty? -If you made the sound yourself, have you tried re-exporting/reconverting? -Does it also not work with other sounds? -Have you tested this on another engine version?

I can also say that this doesnt work with other sounds too

**Comment by ukraineman345** [comment]
> Still don't see why this isn't working when the same code is working for me so we need more info -Does it not play regardless of hit or miss? -Does everything else in the code trigger properly? -Are you playing in the right difficulty? -If you made the sound yourself, have you tried re-exporting/reconverting? -Does it also not work with other sounds? -Have you tested this on another engine version?
also I am playing on hard but I don't really know if its the right difficulty. The sound just doesnt play.

**Comment by ukraineman345** [comment]
> Still don't see why this isn't working when the same code is working for me so we need more info -Does it not play regardless of hit or miss? -Does everything else in the code trigger properly? -Are you playing in the right difficulty? -If you made the sound yourself, have you tried re-exporting/reconverting? -Does it also not work with other sounds? -Have you tested this on another engine version?

every other thing in the code does work
