### ISSUE TITLE
I can't get the library to work properly for the life of me.

### ISSUE THREAD

**Issue by cursedsherryl** [ShadowMario/FNF-PsychEngine#4520]
### Describe your problem here.

Attempting to build a modified version for Linux, and this is one of the main issues.

After exporting in any way, attempting to run the file returns the error:
Error : [lime.utils.Preloader] ERROR: There is no asset library with an ID of "songs"

I've attempted completely redoing the code for that multiple times, taking it back from this git, etc

	<library name="videos"        preload="true" />
	<section if="PRELOAD_ALL">
		<library name="songs"         preload="true" />
		<library name="shared"        preload="true" />
	</section>
	
	<section if="NO_PRELOAD_ALL">
		<library name="songs"         preload="false" />
		<library name="shared"        preload="false" />
	</section>
	
	<assets path="plugins/"             rename=''               if="VIDEOS_ALLOWED windows" />
	<assets path="dlls/"                rename=''               if="VIDEOS_ALLOWED windows" />
	<assets path="assets/videos"        library="videos"        if="VIDEOS_ALLOWED"/>
	<assets path="assets/songs/"         library="songs"         exclude="*.ogg" if="web"/>
	<assets path="assets/songs/"         library="songs"         exclude="*.mp3" unless="web"/>
	<assets path="assets/shared"        library="shared"        exclude="*.ogg" if="web"/>
	<assets path="assets/shared"        library="shared"        exclude="*.mp3" unless="web"/>
	
	<assets path='example_mods' rename='mods' embed='false' if="MODS_ALLOWED"/>
	<assets path='art/readme.txt' rename='do NOT readme.txt' />
	
there's only one week in the mod so far, which is why all the week folders are erased.
I've been reaching out to people in discord servers to little success as well, I'm just hoping this is a mistake that I or the team is making and not lime being a shit with me

A weird part is that if I do it with lime test linux it runs completely fine, just trying to run it outside of the test (dragging the file into terminal and pressing enter)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

I'm not sure about absolutely every file changed, I'm simply trying to port it to linux

**Comment by Steve35117** [comment]
> nah I'm stupid

what did you do pls help me im stuck too
