### ISSUE TITLE
chart editor bug

### ISSUE THREAD

**Issue by thedeveloper112206** [ShadowMario/FNF-PsychEngine#4521]
### Describe your bug here.

pressing backspace to exit chart editor doesnt turn off charting mode.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by KyleOliverDeveloper** [comment]
press enter

**Comment by Pico8430** [comment]
The "bug" has already a way to fix it. Go to freeplay and enable Botplay in the gameplay changers menu and enter the song, exit and disable botplay. Done.

**Comment by Thedumbdude** [comment]
im pretty sure all you have to do is when you enter the song and charting mode is still on click on change difficulty and click on the difficulty you are currently playing on (EXAMPLE: hard) and it should be off

**Comment by thedeveloper112206** [comment]
the only way i knew how to disable the bug was just enter, exit, then re enter a song then the chart mode bug is fixed. i still think it should be fixed because i doubt that chart mode is meant to be left on after pressing backspace.
