### ISSUE TITLE
Health bar icons starts at the right instead of the middle when starting song

### ISSUE THREAD

**Issue by XT4RXML** [ShadowMario/FNF-PsychEngine#4522]
### Describe your bug here.

When started any song, my icons will always start at the left instead of being in the middle. Someone help?
![Capture](https://user-images.githubusercontent.com/96375286/152723652-05e63e22-02a7-459e-ac15-d8e12be317ad.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited the PlayState.hx to add winning icons although I already coded the winning icon code in HealthIcon.hx

**Comment by frantastic24** [comment]
You fucked up the health bar

**Comment by BombasticTom** [comment]
> You fucked up the health bar

forreal
