### ISSUE TITLE
Im not sure why my code wont work.

### ISSUE THREAD

**Issue by BL0KYBL0K** [ShadowMario/FNF-PsychEngine#4525]
### Describe your problem here.

I was trying to make it so when the dad character plays the down animation it makes my character dodge im not sure why but this wont work does anyone know what im doing wrong???

![image](https://user-images.githubusercontent.com/88749184/152767412-6008efe7-bc70-47ed-a60e-89229fa786cd.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a stage in lua and added two characters. THE PLAYER HAS A DODGE

**Comment by BombasticTom** [comment]
Need more info. What are you trying to create with lua? And is that all of the code?

**Comment by MayoALT** [comment]
variables dont carry throughout different files, you need to re-add the dodge code in the lua file in the image

**Comment by BL0KYBL0K** [comment]
> Need more info. What are you trying to create with lua? And is that all of the code?

i litteraly said that in my problem discription

**Comment by BL0KYBL0K** [comment]
> variables dont carry throughout different files, you need to re-add the dodge code in the lua file in the image

thats not a variable??? the dodge animation is a animation in the charactes json

**Comment by lemz1** [comment]
> > variables dont carry throughout different files, you need to re-add the dodge code in the lua file in the image
> 
> thats not a variable??? the dodge animation is a animation in the charactes json

He means the if "Dodge" == true.
Dodge hasn't been defined

**Comment by BL0KYBL0K** [comment]
> > > variables dont carry throughout different files, you need to re-add the dodge code in the lua file in the image
> > 
> > 
> > thats not a variable??? the dodge animation is a animation in the charactes json
> 
> He means the if "Dodge" == true. Dodge hasn't been defined

ohhh

**Comment by BL0KYBL0K** [comment]
> > > variables dont carry throughout different files, you need to re-add the dodge code in the lua file in the image
> > 
> > 
> > thats not a variable??? the dodge animation is a animation in the charactes json
> 
> He means the if "Dodge" == true. Dodge hasn't been defined

it worked
