### ISSUE TITLE
3 requests.

### ISSUE THREAD

**Issue by snazzyostrich** [ShadowMario/FNF-PsychEngine#4547]
### What feature do you want to get added on the **base** engine?

1. A stage switching event. Much needed.
2. CPU noteskins.
3. A modchart editor. You can test it on an existing chart. You can select one or more notes and drag it to wherever wanted. A graph on the side determines the smoothing. Another determines if it moves in a curve. It can be either bpm or timer based. You also have the option to loop it. 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
1- already possible
2- already possible
3- idk sounds like you don't want to learn how to code or look at other people's modcharts

**Comment by snazzyostrich** [comment]
1. in the base engine?
2. in the base engine?
3. that’s kinda the point of having it as an editor

**Comment by frantastic24** [comment]
1- yes
2- yes
3- learn

**Comment by snazzyostrich** [comment]
1. where
2. where
3. k

**Comment by frantastic24** [comment]
look in discussions, there are at least 3 or 4 different posts about it

**Comment by snazzyostrich** [comment]
i mean in vanilla psych engine
neither a stage switch event or cpu noteskins are anywhere in the *base* engine

**Comment by frantastic24** [comment]
because they aren't neccesary

**Comment by snazzyostrich** [comment]
you just said they were in base psych
and when was the last time you’ve used a no animation note for exactly that purpose

**Comment by frantastic24** [comment]
> you just said they were in base psych

because it is, use lua if you are too scared to use source, or too lazy or whatever
there is no need to add something that is already fully possible, and if you took two seconds to look at other suggestions you'll see they aren't adding it as a hardcoded feature

**Comment by snazzyostrich** [comment]
geez fine

**Comment by frantastic24** [comment]
ratio
