### ISSUE TITLE
cant compile game xd

### ISSUE THREAD

**Issue by Orminie** [ShadowMario/FNF-PsychEngine#4551]
### Describe your bug here.

ok so like
![image](https://user-images.githubusercontent.com/98986775/152906490-9c14f97e-1565-4eb5-a72a-49e8a03c3a30.png)
and
like
![image](https://user-images.githubusercontent.com/98986775/152906513-4272c5e3-0cb7-438f-8588-0131c7ac79bb.png)
so yeah

im building on mfufikcuigmng linux because im cool,.,.,.,,./,/../,./,/.,m,m./,m,m,./

im using the source and not the lua

and like im using haxe 4.2.4 and such 

i did the kade engine compiling guide + the pysch engine thing that shadowmario man said

so like i dunno what im doing wrong lmao

so yeah bye

### Command Prompt/Terminal logs (if existing)

```bash
[orm@Archie-House FNF-PsychEngine-main]$ lime test linux
source/animateatlas/AtlasFrameMaker.hx:11: characters 8-57 : Type not found : animateatlas.displayobject.SpriteAnimationLibrary
source/animateatlas/AtlasFrameMaker.hx:12: characters 8-50 : Type not found : animateatlas.displayobject.SpriteMovieClip
source/animateatlas/AtlasFrameMaker.hx:83: characters 50-65 : Type not found : SpriteMovieClip
[orm@Archie-House FNF-PsychEngine-main]$
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

i added apistuff like the original ninjamuffin99 guide said lmao

**Comment by Stilic** [comment]
uPdAtE yOuR hAxE

**Comment by frantastic24** [comment]
Is this a custom build, because there isn't an AtlasFrameMaker.hx on base that I can find
And type like a normal person jesus christ

**Comment by frantastic24** [comment]
Linux compiles just fine on my end

**Comment by Orminie** [comment]
haxe is updated.
![image](https://user-images.githubusercontent.com/98986775/153772879-be09aaa4-e659-44c8-a408-b70d0f67a00d.png)
and frantastic what distro are you using? and what commands did you put in to do it?
