### ISSUE TITLE
Shaders in release build

### ISSUE THREAD

**Issue by Ninjatintin** [ShadowMario/FNF-PsychEngine#4555]
### What feature do you want to get added on the **base** engine?

Can you add shaders to the release build and not just the latest source code build from actions

Note:
If shaders are already planned to be in the release build I'm very sorry I didn't know (at the time I posted this) if its already going to be in the release build and if so then go ahead and put the i swear to god tag if this is annoying

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
they're not on release builds because they're **experimental** and unstable
