### ISSUE TITLE
BUG | Notes over other notes cause lag when charting

### ISSUE THREAD

**Issue by AmySpark-NG** [ShadowMario/FNF-PsychEngine#4556]
### Describe your bug here.

Im not actually charting the engine, it's just a bug that i've seen while charting, im not sure if someone has already written about this but feel free to close it ig

If when you're charting you copy a section and paste it over another section that already has notes the notes from the recently pasted section will get over the already existing notes, becoming duplicates which actually lags the game when entering that section in charting mode and actually playing the song

Sorry if this sounded confusing lol  

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I actually didn't compile the game, this was on a release

**Comment by ThePsychEngineFan** [comment]
then just... clear the section?

**Comment by amySpark-ng** [comment]
> then just... clear the section?
that would delete the section that was there first, what if i wanted them both?
