### ISSUE TITLE
random crashes in specific song

### ISSUE THREAD

**Issue by smalnj** [ShadowMario/FNF-PsychEngine#4559]
### Describe your bug here.

basically making a triple trouble port and in this specific point in the song, lets say halfway through, the game just abruptly crashes, there isnt anything special in that point in the song, chart editor doesnt crash when getting to that part of the song, this basically makes the song unplayable

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Just added a few characters, events and notetypes and Triple Trouble.

**Comment by ThePsychEngineFan** [comment]
are you sure that nothing happens at that point?

**Comment by frantastic24** [comment]
someone said this happened after changing FPS settings (#4477) so probably try that
