### ISSUE TITLE
Sometime, bf make his clone, it will stay there for a while or the whole song!

### ISSUE THREAD

**Issue by MR-FNF** [ShadowMario/FNF-PsychEngine#4562]
### Describe your bug here.

Sometime, bf make his clone, it will stay there for a while or the whole song!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I just put some luas, but nothing will clone bf

**Comment by ThePsychEngineFan** [comment]
can you explain more about whats happening? i dont really understand

**Comment by tposejank** [comment]
omg not the 11 year old being dumb💀💀🙄

**Comment by MR-FNF** [comment]
> can you explain more about whats happening? i dont really understand

![image](https://user-images.githubusercontent.com/95696270/152994743-7ff5cbab-79ba-4d05-8a17-a528d5312c60.png)
Something like this

**Comment by Reycko** [comment]
remove blammed lights event

**Comment by NokioPyro** [comment]
HES BACK

**Comment by Stilic** [comment]
> > can you explain more about whats happening? i dont really understand
> 
> ![image](https://user-images.githubusercontent.com/95696270/152994743-7ff5cbab-79ba-4d05-8a17-a528d5312c60.png) Something like this

blammed lights be like:

**Comment by ShadowMario** [comment]
Blammed Lights.

**Comment by NokioPyro** [comment]
Holy shit shadowmario and mr fnf on the same issue holy fucking shit

**Comment by MR-FNF** [comment]
> Blammed Lights.

Then please fix it!

**Comment by DaviGamerDias12** [comment]
> omg not the 11 year old being dumb💀💀🙄

his name is kaden
