### ISSUE TITLE
pixel dialogues

### ISSUE THREAD

**Issue by ukraineman345** [ShadowMario/FNF-PsychEngine#4577]
### What feature do you want to get added on the **base** engine?

requesting for it the 2nd time.
I need a script that makes a pixel dialogue with senpai mad senpai and spirit play.
example:
I type in dialogue.txt
:dad:So, youre back to destroy me again?
:bf:beep bep
:dad:Let's start the battle then.
and
it works like dialogue from senpai, roses, or thorns. 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by zLightc** [comment]
you can just change the images and font?

also congrats on the test.

**Comment by ukraineman345** [comment]
> you can just change the images and font?
> 
> also congrats on the test.

I can't change the images and font because the game will just break
