### ISSUE TITLE
Error with lua stage

### ISSUE THREAD

**Issue by RedMik52** [ShadowMario/FNF-PsychEngine#4578]
### Describe your problem here.

when i try to load the stage it gives this error:
![immagine_2022-02-08_211429](https://user-images.githubusercontent.com/89082441/153068179-91b0585a-dc06-49b7-a1ad-58977961d55a.png)

this is my lua file:
![office lua - Blocco note 08_02_2022 21_16_52](https://user-images.githubusercontent.com/89082441/153068664-e3ffadb2-bebc-4f04-8afb-9919a09661e2.png)
pls help me

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

added bg sprites, song and song data

**Comment by frantastic24** [comment]
that's not how you use lua or how you add a stage either

**Comment by CrusherMods** [comment]
that's a json file not lua...

**Comment by RedMik52** [comment]
i solved the problem,  i fell stupid now.
(i followed a crappy tutorial)
