### ISSUE TITLE
Stop the crashing!

### ISSUE THREAD

**Issue by MrGarchompeyy** [ShadowMario/FNF-PsychEngine#4592]
### What feature do you want to get added on the **base** engine?

When one of the files are missing or one of the code isn't working the thing will crash. Don't let it crash! Just make it say error or something.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by KutikiPlayz** [comment]
that's what debug mode is for

**Comment by frantastic24** [comment]
Failed the test. L

**Comment by Stilic** [comment]
sussy baka maybe?? idk
