### ISSUE TITLE
Opening engine through Windows search bar comes up with error

### ISSUE THREAD

**Issue by GloriousCashew** [ShadowMario/FNF-PsychEngine#4597]
### Describe your bug here.

The engine launches fine when opening from within the folder. When trying to launch from Windows search bar, it shows '[lime.utils.Preloader] ERROR: There is no asset library with an ID of "videos"' This may be because I screwed something up, because the only other people that have experienced it are people I've shared my mod with, but I wanted to report it just in case :)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added mod folder with custom assets, moved around/deleted some original game assets

**Comment by BombasticTom** [comment]
that's normal because the engine probably searches for a relative position of data
it's not just psych engine, all fnf engines have the same problem.

**Comment by Steviegt6** [comment]
The working directory of programs is set to the currently-opened folder if launched from File Explorer. This is normal behavior, as such data is stored within the local folder the executable is in.
