### ISSUE TITLE
Disable all mods button

### ISSUE THREAD

**Issue by Wither362** [ShadowMario/FNF-PsychEngine#4605]
### What feature do you want to get added on the **base** engine?

Well, I say this because I have a **_lot_** of mods, and I want a button that deactivates all the mods at once, instead of deactivating the mods one by one.

Please, add this, I _**really**_ need it

if this change the stage editor, please don’t do this, I need the stage editor

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by trayfellow** [comment]
![image](https://user-images.githubusercontent.com/48515908/153211195-e2073e88-fca5-48ca-9d14-395ff9048e0e.png)

that already exists

**Comment by frantastic24** [comment]
Blind

**Comment by BombasticTom** [comment]
lmao

**Comment by Wither362** [comment]
Ok, sorry for being blind
