### ISSUE TITLE
No animation called "i" and another issue

### ISSUE THREAD

**Issue by neondev27** [ShadowMario/FNF-PsychEngine#4606]
### Describe your problem here.

i am compiled this engine at LİNUX, but i have some issues. Firstly i have this issue:
[WARNING] No animation called "i"   and
/src/FunkinLua.cpp: In member function ‘Float FunkinLua_obj::__construct(String)::_hx_Closure_59::_hx_run(String)’:

how i can solve it?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by BombasticTom** [comment]
for the first issue, you had to have changed something in the source code
for the second one, what code did you implement using Lua?

**Comment by neondev27** [comment]
i am just compiled on linux at using lime test linux -debug and i am not changed any code at Lua or source

**Comment by BombasticTom** [comment]
idk then
