### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by KyleOliverDeveloper** [ShadowMario/FNF-PsychEngine#4611]
### What is your question?

![image](https://user-images.githubusercontent.com/94708825/153230697-1244d823-f0f0-4c1a-94b9-2c0b573b91cf.png)
HELP

**Comment by FuseIsHere813** [comment]
Not really a Psych Engine related question, but you might be missing some VSC2019 libraries.

**Comment by KyleOliverDeveloper** [comment]
I have it installed, dumbass

**Comment by BombasticTom** [comment]
> I have it installed, dumbass

no, dumbass, you need to install VISUAL STUDIO. NOT VISUAL STUDIO CODE. READ THE FUNKIN-MASTER TUTORIAL FFS

**Comment by BombasticTom** [comment]
(https://github.com/ninjamuffin99/Funkin)

**Comment by BombasticTom** [comment]
actually this is more accurate for your search https://github.com/ninjamuffin99/Funkin#build-instructions

**Comment by BombasticTom** [comment]
What version of visual studio community do you have?

**Comment by KyleOliverDeveloper** [comment]
2019

**Comment by BombasticTom** [comment]
idk what libraries have you installed?

**Comment by KyleOliverDeveloper** [comment]
like, the components?

**Comment by KyleOliverDeveloper** [comment]
if yes, the build tools, and the windows SDK

**Comment by KyleOliverDeveloper** [comment]
@BombasticTom

**Comment by KyleOliverDeveloper** [comment]
different message, hmmh??
![image](https://user-images.githubusercontent.com/94708825/153271409-256f6648-e1ec-4bd5-a7fb-768212cadd02.png)

**Comment by KyleOliverDeveloper** [comment]
found a way to compile it, just need to type in lime test html5 -debug

**Comment by KyleOliverDeveloper** [comment]
NEVERMIND

**Comment by KyleOliverDeveloper** [comment]
someone pls help me, ive been tryng this for the past 2 weeks, i still cant, i need it, someone, help me do this, i cant stand all my failure anymore

**Comment by KyleOliverDeveloper** [comment]
FUCK this shit, this will never get anywhere. No one is replying again, this is pointless.

**Comment by BombasticTom** [comment]
> FUCK this shit, this will never get anywhere. No one is replying again, this is pointless.

check your system arch
is it 32bits
or 64bits?
