### ISSUE TITLE
Arrow customization

### ISSUE THREAD

**Issue by Theoyeah** [ShadowMario/FNF-PsychEngine#4614]
### What feature do you want to get added on the **base** engine?

In psych engine, it would be cool to make an option were you can switch differents noteskin like circles and etc  (like Kade engine but with more skins)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by BombasticTom** [comment]
they probably won't you can just use lua to do it
