### ISSUE TITLE
LUA Text not working.

### ISSUE THREAD

**Issue by Reycko** [ShadowMario/FNF-PsychEngine#4625]
### Describe your bug here.

My LUA text is not showing in it. I don't really know what to put here so i'll put the code now:

```
function onCreate()
	makeLuaText('acc', '0', (screenWidth / 2), (screenWidth / 4), (screenHeight / 1.125))
end

function onUpdate(elapsed)
	(some coding)
	 curAccuracy = curTotalNotesHit / counterUpdated (the variables exists)
	(some more coding)
	setLuaText('acc', curAccuracy * 100)
end
```

### Command Prompt/Terminal logs (if existing)

```bash
None.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't.

**Comment by frantastic24** [comment]
`addLuaText`

**Comment by ItsCapp** [comment]
> `addLuaText`

to build upon this,
you gotta add `addLuaText` if you want the text to **actually show up**, you're just making the text but not telling the game to display it

**Comment by zLightc** [comment]
You can close this issue now.

**Comment by acap09** [comment]
Please close this issue.
