### ISSUE TITLE
Song won't load

### ISSUE THREAD

**Issue by ExoticExan** [ShadowMario/FNF-PsychEngine#4629]
### Describe your problem here.

Hi there. So I added my custom song and the song won't load. I have all json files correct and both the inst and voices Ogg files are in the song folder. I compiled the game and it still would not load.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ItsCapp** [comment]
it's probably a bad file, try putting the file into audacity and re-exporting it.

**Comment by ExoticExan** [comment]
> it's probably a bad file, try putting the file into audacity and re-exporting it. it works for me when I have a bad file

This fixed my issue. Thank you for the help.

**Comment by zLightc** [comment]
You can close this issue now.
