### ISSUE TITLE
Stages (damn they are hard)

### ISSUE THREAD

**Issue by SeriouslyAnimations** [ShadowMario/FNF-PsychEngine#4638]
### What is your question?

What would the lua files be for each bg, these bgs are funkin' hard

**Comment by maxilamano** [comment]
try editing [this](https://cdn.discordapp.com/attachments/866856727621795850/900523259345371177/ExampleStage.zip). An example stage made in lua (a recreation of week 1 stage). or if you have another question, try being more specific about your issue.

**Comment by SeriouslyAnimations** [comment]
So, I am tryng to copy the bgs of every week to replace them with a different, edited one as the songs go on. Halloween and Stage are the stages that im good with but the ones like Philly, Limo, and School.

**Comment by frantastic24** [comment]
base stages don't come in .lua, they're hardcoded, check PlayState.hx to see how they're rendered

**Comment by SeriouslyAnimations** [comment]
isnt that code in haxe?]

**Comment by frantastic24** [comment]
yes, you'll need it if you want to recreate stages easily

**Comment by frantastic24** [comment]
> check PlayState.hx
