### ISSUE TITLE
Starting a music in the function onSongStart() crashes the game

### ISSUE THREAD

**Issue by Lila-Rogers** [ShadowMario/FNF-PsychEngine#4659]
### Describe your bug here.

Self Explanatory

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I just tried playing music on the start of an song

**Comment by main-thing** [comment]
[This?](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Sound-and-Music-Functions#playmusicsoundstring-volumefloat--1-loopbool--false)
