### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by Paulfunkgit** [ShadowMario/FNF-PsychEngine#4674]
### Describe your problem here.

So i was going to compile my game after editing some things of the engine like the botplay text and the fonts but it didnt work because of this error: source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }
I downloaded the source code again with a diffrent folder name and i edited absolutely nothing and the error still pops up no joke

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Playstate.hx thats it

**Comment by beeanie** [comment]
use the updated haxe https://haxe.org/

**Comment by Paulfunkgit** [comment]
Ok i finally got all of the shit installed it works now

**Comment by beeanie** [comment]
yay

**Comment by Paulfunkgit** [comment]
I got it all installed but it was just pain and everytime i remember installing every single component i want to die
