### ISSUE TITLE
The "BACK" in the difficulty didn't work

### ISSUE THREAD

**Issue by MR-FNF** [ShadowMario/FNF-PsychEngine#4697]
### Describe your bug here.

When I change the difficulty in the pause menu, if I press "BACK" in the change difficulty, it will say the difficulty called "null" not found, and then crash the game

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added some mods and some luas

**Comment by frantastic24** [comment]
Duplicate, already fixed on source

**Comment by MR-FNF** [comment]
> Duplicate, already fixed on source

Ok, I will wait for downloaded build...

**Comment by frantastic24** [comment]
Or get a build from Actions, either way close this
