### ISSUE TITLE
Adding modifiers like the Mic'd Up mod and having stuff breaking the 4th wall.

### ISSUE THREAD

**Issue by Coolboy0516** [ShadowMario/FNF-PsychEngine#4698]
### What feature do you want to get added on the **base** engine?

It would be pretty nice to have modifiers, (in a separate menu) and having the window move and it opening windows, closing it's self, and more.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by main-thing** [comment]
You can already do this with lua?

**Comment by MaybeMaru** [comment]
you can already do that lmao

**Comment by Coolboy0516** [comment]
ok.
