### ISSUE TITLE
note coloring is a bit weird with the receptor pressing stuff

### ISSUE THREAD

**Issue by arceuss** [ShadowMario/FNF-PsychEngine#47]
![image](https://user-images.githubusercontent.com/28229451/132926355-28da576d-ac33-46df-a0a2-eef74bb988a7.png)
could possibly be fixed if you grayscale them first

**Comment by haya3218** [comment]
The colors are adjusted using a shader, not FlxColor since that be too limited
so using grayscale arrows won't really change anything since it relies on existing colors that are changed using hues as a shader

**Comment by arceuss** [comment]
oh

**Comment by ShadowMario** [comment]
U sure that isn't an issue with Cirno mod?

**Comment by ShadowMario** [comment]
Nothing new has been said, it is very possible that the issue is on the mod itself, and not in the engine.
