### ISSUE TITLE
it wont compile

### ISSUE THREAD

**Issue by jmxamongusmodder** [ShadowMario/FNF-PsychEngine#4704]
### Describe your problem here.

Called from ? line 1
Called from CommandLineTools.hx line 1895
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 125
Called from CommandLineTools.hx line 1703
Called from lime/tools/ProjectXMLParser.hx line 21
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 50
Called from lime/tools/ProjectXMLParser.hx line 2043
Called from lime/tools/ProjectXMLParser.hx line 1528
Called from lime/tools/ProjectXMLParser.hx line 608
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 709
Called from /Users/runner/hostedtoolcache/haxe/4.2.1/x64/std/neko/_std/sys/FileSystem.hx line 69
Called from /Users/runner/hostedtoolcache/haxe/4.2.1/x64/std/neko/_std/sys/FileSystem.hx line 60
Uncaught exception - std@sys_file_type

it happened today and idk how to fix i tried adding bf skins then that happened it wont go away help i do not wanna upgrade.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i edited client prefs notes playstate alot of stuff

**Comment by rttrtrtrtrtrtrtrtrygtr** [comment]
you souldent mess around the notes playstate

**Comment by rttrtrtrtrtrtrtrtrygtr** [comment]
- [ ]
