### ISSUE TITLE
everytime i load a json in chart, it crashes

### ISSUE THREAD

**Issue by im557** [ShadowMario/FNF-PsychEngine#4706]
### Describe your bug here.

everytime i load a json, it puts an error message saying `[file_contents,assets/data/project-wtf/project-wtf-null.json]`

why does it do that

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i did not edit any .hx file

**Comment by frantastic24** [comment]
Missing .json
