### ISSUE TITLE
Where is the freeplaySong.txt?!

### ISSUE THREAD

**Issue by MR-FNF** [ShadowMario/FNF-PsychEngine#4713]
### Describe your problem here.

Where is the freeplaySong.txt?! I NEED IT!!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Playertrip777** [comment]
lmao why did you need it when you can just hide story mode weeks and display freeplay only.

**Comment by Playertrip777** [comment]
Why did you gave me a thumbs-down? I already gave you the answer.

**Comment by MR-FNF** [comment]
> Why did you gave me a thumbs-down? I already gave you the answer.

But I like the freeplaySongList! Hope ShadowMario add this back :(

**Comment by Playertrip777** [comment]
![image](https://user-images.githubusercontent.com/90383277/153536233-7c6dfd2f-9602-4448-92a6-cd6eb2d65bf9.png)
You can just do that????

**Comment by SrtHero278** [comment]
![image](https://user-images.githubusercontent.com/93018286/153538915-51e36b08-34c2-4a8a-8a21-90583eb95333.png)
Yea as of rn, it's removed.

**Comment by Stilic** [comment]
useless. just create a week bruh.

**Comment by Pico8430** [comment]
The file it's totally useless on Psych Engine, just create a week and hide it on story mode.

**Comment by ImaginationSuperHero528** [comment]
weekList.txt it's in the weeks folder and you can add one to your mod

**Comment by Playertrip777** [comment]
@MR-FNF you might wanna close this issue
