### ISSUE TITLE
Issue with the pause menu

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#4716]
### Describe your bug here.

You see, if you go into the song pause menu and go into change difficulties, and you press Back, it just searches for "songname-null.json" when it's not supposed to do that and its frustrating when you accidentally go into it and are not meant to change difficulties

### Command Prompt/Terminal logs (if existing)

```bash
none
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Yet another duplicate, already fixed in source
