### ISSUE TITLE
what is new BPM map BUDDY

### ISSUE THREAD

**Issue by AnimaX27** [ShadowMario/FNF-PsychEngine#4722]
### Describe your problem here.

so while a compiled and play in the game and play in Freeplay 
or story mode it got crashed and but in the terminal says  `new BPM map BUDDY [{ stepTime => 2832, bpm => 166, songTime => 290958.904109589 }]` 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

maybe but I forget (i am not the one who edit some coder of my edit it)

**Comment by coolfren** [comment]
It has something to do with BPM changes in songs.

The crash you're getting is not related to that trace at all.

**Comment by AnimaX27** [comment]
so what I have to do then?
