### ISSUE TITLE
can you add this note shit i added lol

### ISSUE THREAD

**Issue by THOBY555** [ShadowMario/FNF-PsychEngine#4724]
### What feature do you want to get added on the **base** engine?

https://user-images.githubusercontent.com/71563419/153557863-1ef023ac-7fcd-488c-a50c-b9ee168e78aa.mp4

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ProgramerGamerZone** [comment]
Can you tell me how you did it? I want it in source (or Lua if you made it in Lua) please

**Comment by ProgramerGamerZone** [comment]
Ok can you like make a fork for it or something lol

**Comment by frantastic24** [comment]
This should be a PR and not an issue but I'm pretty sure shadow already said this won't be a thing, you can even do this with Lua already

**Comment by Stilic** [comment]
no, keep it to your fork.
also @ShadowMario can you close this useless issue please.

**Comment by ItsCapp** [comment]
> no, keep it to your fork. also @ShadowMario can you close this useless issue please.

it's not an issue it's an enhancement,
and he's asking for different note textures on either side

**Comment by frantastic24** [comment]
> it's not an issue it's an enhancement

Check what tab you're on

> and he's asking for different note textures on either side

Duplicate of several other issues, which have already been declined
This should be closed

**Comment by HIGGAMEON** [comment]
this can easily be done in lua, it's not needed.
