### ISSUE TITLE
dialogue sprites and XML

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#4727]
### Describe your problem here.

idk how to do ether of those things please help.
i use the precompiled version, I use krita, and I don't (know how to) code

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

N O

**Comment by trippinreal** [comment]
Dialogue sprites probably have a good tutorial on YouTube, XML literally is a file that lists the co-ordinates of each frame on your spritesheet. Exporting with Adobe animate should automatically do that for you.

**Comment by WolfyTail** [comment]
The sprites are just all the frames from every animation. The XML will appear automatically if you do it with Adobe Animate. Just move them to `assets/shared/dialogue`. Here's an example of the sprite sheet if you don't know how it looks.
![Yuki_Dialogue](https://user-images.githubusercontent.com/95707370/157513334-1ccb315e-d6bd-42ba-a45c-7b9be4387578.png)

**Comment by creeperkidking** [comment]
thx! :)
