### ISSUE TITLE
death animation input failed

### ISSUE THREAD

**Issue by cocos-yz** [ShadowMario/FNF-PsychEngine#4742]
### Describe your bug here.

I put death animation frames in xml and sprites, and it works in character editor is ok, but in song when my character dead, it still show bf's death animation, idk how to solve it

### Command Prompt/Terminal logs (if existing)

```bash
none
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Either you forgot to change death screen characters or animation names are wrong

**Comment by cocos-yz** [comment]
> Either you forgot to change death screen characters or animation names are wrong

what is death screen characters?

**Comment by frantastic24** [comment]
If your death screen sprites are in another character, you need to set the game over screen to use that character first

**Comment by frantastic24** [comment]
There is an example on the [wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API)
