### ISSUE TITLE
Help doing a BF alpha tween because im dumb

### ISSUE THREAD

**Issue by MaybeMaru** [ShadowMario/FNF-PsychEngine#4752]
### Describe your problem here.

Ok, so I've been trying to do a tween in BF's alpha with lua but for some reason it doesnt work
Here is my stinky code:
`getPropertyFromObject('boyfriend', 'alpha');`
`doTweenAlpha('BFalpha', 'boyfriend.alpha', 50, 3, 'circInOut');`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by frantastic24** [comment]
Okay multiple things:
1) you don't need `getProperty` unless you need it for some formula, or to store it in a variable for simplicity
2) you don't need `.alpha`, since the function already uses the property
3) alpha is a float value from 0 to 1 (ex: 0.5 is 50% visible, 0% is invisible)

**Comment by MaybeMaru** [comment]
> Okay multiple things:
> 
> 1. you don't need `getProperty` unless you need it for some formula, or to store it in a variable for simplicity
> 2. `getPropertyFromObject` isn't a function
> 3. you don't need `.alpha`, since the function already uses the property
> 4. alpha is a float value from 0 to 1 (ex: 0.5 is 50% visible, 0 is invisible)

Damn, now I feel so dumb
Tahnk you!
