### ISSUE TITLE
mysong-hard.json

### ISSUE THREAD

**Issue by MarshmelloMusicerXD** [ShadowMario/FNF-PsychEngine#4758]
### Describe your problem here.

I made my custom chart and I wanna put a hard.json how I can put it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by tposejank** [comment]
dumb

**Comment by frantastic24** [comment]
rename it...

**Comment by AdmiralUsername** [comment]
copy and paste it into the mod's data folder and add    -hard    at the end

**Comment by Pico8430** [comment]
Does this guy even know about charting and modding?

**Comment by Wither362** [comment]
If you want to make a hard difficulty for your song and your song’s name is “mysong”, when you have the .json, rename it to `mysong-hard.json`, and put it in `mods/yourmodname/data/mysong`, if you have questions look the folders of other mods or things like that, also you can ask more questions

**Comment by MarshmelloMusicerXD** [comment]
> If you want to make a hard difficulty for your song and your song’s name is `mysong`, when you have the .json, rename it to `mysong-hard.json`, and put it in `mods/yourmodname/data/mysong`, if you have questions look the folders of other mods or things like that, also you can ask more questions

Thanks you so much
