### ISSUE TITLE
How to make the game detect a difficulty being played

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#4761]
### What is your question?

how do i make a sound play at the start of a song on a difficulty
here is the difficulty's i have easy, medium, hard, insane, crazy, crazy+
now for crazy and c+ i want to make it so a sound is played when you start the level in those difficulty's

**Comment by frantastic24** [comment]
if you're on lua you can just do `if difficulty == x then`
x is the difficulty number, goes in order set in week data

**Comment by machonessiebaby** [comment]
> if you're on lua you can just do `if difficulty == x then` x is the difficulty number, goes in order set in week data

tysm
i just needa know the playsound script for lua too

**Comment by machonessiebaby** [comment]
ill ask that in a new thread
