### ISSUE TITLE
how to play sound in lua

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#4762]
### What is your question?

how to play sound in lua lol

**Comment by machonessiebaby** [comment]
i use lua for cool stuff and source for other stuff

**Comment by machonessiebaby** [comment]
i would like the playsound just for lua though

**Comment by frantastic24** [comment]
[it's on the wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Sound-and-Music-Functions)

**Comment by machonessiebaby** [comment]
ah me stupid
