### ISSUE TITLE
add loadSong(name);

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#4776]
### What feature do you want to get added on the **base** engine?

the title says it nearly all! it would be useful for a secret song that won't appear on the week's song list, but will be there after you play the song previously from it. basically the structure is like this:

loadSong(songName)

(even though its already in the title)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ProgramerGamerZone** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/pull/3663
yes
