### ISSUE TITLE
How to Change Botplay Text using only lua and no source code???

### ISSUE THREAD

**Issue by Dommiie** [ShadowMario/FNF-PsychEngine#4795]
### What is your question?

How do I do this because I have seen some people do it with only lua

**Comment by frantastic24** [comment]
There are posts in discussions about this already
```lua
function onCreatePost()
     setTextString('botplayTxt', 'text')
end
```

**Comment by nintendodsonatable** [comment]
is i possible on kade?

**Comment by MemeHoovy** [comment]
> is i possible on kade?

no
