### ISSUE TITLE
really bad bug

### ISSUE THREAD

**Issue by HiroOfc** [ShadowMario/FNF-PsychEngine#48]
title is with gf freezed and there is no song. Like, in the entire game

**Comment by NadekoJr** [comment]
I never got that bug so that might just be you?

**Comment by HiroOfc** [comment]
> I never got that bug so that might just be you?

idk, but i think i need to reinstall all haxe libraries cuz i've followed kade engine build instructions

**Comment by HiroOfc** [comment]
i'll try to reinstall and close it for now, if the bug continues, i'll reopen

**Comment by HiroOfc** [comment]
well, i think it is a problem from bf image and xml
cuz i changed it into other bf version and the error still continues

and i found out wtf is that, the error is:
```
AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to check format support: 0x80040154
AL lib: (EE) ALCwasapiPlayback_resetProxy: Failed to initialize audio client: 0x80070006
```

i need help

**Comment by HiroOfc** [comment]
i'll close again cuz i know now how to solve. But this is something that i suggest the dev should take a look
