### ISSUE TITLE
Help getting "dad.cameraPosition"

### ISSUE THREAD

**Issue by Grape-Boy** [ShadowMario/FNF-PsychEngine#4808]
### Describe your problem here.

I can't figure out how to get the `cameraPosition` for the opponent and Boyfriend,
here's my code:
```lua
debugPrint(getPropertyFromGroup('dad', 1, 'cameraPosition'))
```
It prints **"cameraPosition"**.

I also tried
```lua
debugPrint(getProperty('dad.cameraPosition[1]'))
```
before, but it didn't work, it only prints **"dad.cameraPosition[1]"**.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by SrtHero278** [comment]
`debugPrint(getProperty('dad.cameraPosition')[1])`
for some reason, you need to get table values outside the function.

**Comment by Grape-Boy** [comment]
Didn't work, it gave me nothing. :/

**Comment by frantastic24** [comment]
it does work
```lua
function onCreatePost()
	debugPrint(getProperty('dad.cameraPosition')[1])
	debugPrint(getProperty('dad.cameraPosition')[2])
end
```
![image](https://user-images.githubusercontent.com/95725102/153728230-eba346dc-843e-435c-95de-cad5fdc3c7a2.png)

**Comment by Grape-Boy** [comment]
Forgot to close this, yes it does actually work.
