### ISSUE TITLE
How do I make a sound effect play when the opponent hits the left arrow?

### ISSUE THREAD

**Issue by NesDoesGithub** [ShadowMario/FNF-PsychEngine#4820]
### Describe your problem here.

I'm trying to make a song in Psych Engine where a sound plays when the opponent hits the left arrow, although my code isn't working.

function opponentNoteHit(id, left, noteType)
    if opponentNoteHit == left then   
        playSound('vineboom')
    end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by frantastic24** [comment]
```lua
function opponentNoteHit (id, direction, type, sus)
     if direction == 1 then
          playSound('sound')
     end
end
```
