### ISSUE TITLE
How to change noteskin mid song. My script crashes the game.

### ISSUE THREAD

**Issue by NesDoesGithub** [ShadowMario/FNF-PsychEngine#4824]
### Describe your problem here.

I'm trying to get the notes to change midsong and it crashes the game upon getting to the curStep.

```
function onUpdate(elasped)
        if curStep >= 4
	        for i=0,7 do
		        setPropertyFromGroup('StrumLineNotes', i, 'texture', 'Majin_Notes')
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'Majin_Notes')
	        end
        end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by lemz1** [comment]
do you have the note assets in mods/images?
For some reason you **_need_** to have them in mods/images

**Comment by frantastic24** [comment]
First, don't use onUpdate
Second, `strumLineNotes`, case sensitivity

**Comment by lemz1** [comment]
also you need to add "then" after `curstep >= 4`
so in the end it is `if curstep >= 4 then`

**Comment by NesDoesGithub** [comment]
> frantastic24

if i don't use onUpdate() then the notes will only be majin's for one section then go back to normal but you are correct about the strumLineNotes

**Comment by frantastic24** [comment]
> if i use function onStepHit() then the notes will only be majin's for one section

because you're only telling the code to change the first few notes here: 
```lua
	        for i=0,7 do
		        setPropertyFromGroup('StrumLineNotes', i, 'texture', 'Majin_Notes')
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'Majin_Notes')
```
these two lines should be under different `for` statements
```lua
for i=0,7 do
	setPropertyFromGroup('strumLineNotes', i, 'texture', 'Majin_Notes')
end

for i=0, getProperty('unspawnNotes.length')-1 do

	setPropertyFromGroup('unspawnNotes', i, 'texture', 'Majin_Notes')
end
```

**Comment by NesDoesGithub** [comment]
> > if i use function onStepHit() then the notes will only be majin's for one section
> 
> because you're only telling the code to change the first few notes here:
> 
> ```lua
> 	        for i=0,7 do
> 		        setPropertyFromGroup('StrumLineNotes', i, 'texture', 'Majin_Notes')
> 			setPropertyFromGroup('unspawnNotes', i, 'texture', 'Majin_Notes')
> ```
> 
> these two lines should be under different `for` statements
> 
> ```lua
> for i=0,7 do
> 	setPropertyFromGroup('strumLineNotes', i, 'texture', 'Majin_Notes')
> end
> 
> for i=0, getProperty('unspawnNotes.length')-1 do
> 
> 	setPropertyFromGroup('unspawnNotes', i, 'texture', 'Majin_Notes')
> end
> ```

sorry i was wrong thank you for telling me
