### ISSUE TITLE
sory ummm again

### ISSUE THREAD

**Issue by SAB236YT** [ShadowMario/FNF-PsychEngine#4828]
### What is your question?

expected } again pausesubstate flile here
[PauseSubState (2).txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8054314/PauseSubState.2.txt)
:

**Comment by SAB236YT** [comment]
sory here correc
[PauseSubState (2).txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8054314/PauseSubState.2.txt)
t

**Comment by lemz1** [comment]
```
pausesprite = new FlxSprite();
	pausesprite.frames = Paths.getSparrowAtlas('i did not steal this from beepie definetly O SHI-/pause');
	pausesprite.animation.addByPrefix('idle','cuby menu',24);
	pausesprite.animation.play('idle');
	pausesprite.x -= 50;
	pausesprite.y -= 200;
	pausesprite.visible = true;
	pausesprite.scale.set(0.9,0.9);
	add(pausesprite);
```
this needs to be in a function.
you can't define this outside a function

**Comment by SAB236YT** [comment]
thx

**Comment by SAB236YT** [comment]
> ```
> pausesprite = new FlxSprite();
> 	pausesprite.frames = Paths.getSparrowAtlas('i did not steal this from beepie definetly O SHI-/pause');
> 	pausesprite.animation.addByPrefix('idle','cuby menu',24);
> 	pausesprite.animation.play('idle');
> 	pausesprite.x -= 50;
> 	pausesprite.y -= 200;
> 	pausesprite.visible = true;
> 	pausesprite.scale.set(0.9,0.9);
> 	add(pausesprite);
> ```
> 
> this needs to be in a function. you can't define things outside a function

has this needs to be in
override function create() ?

**Comment by SAB236YT** [comment]
switch (curSelected)
	    {
		    case 0:
			    pausesprite.visible = true;
			case 1:
			    pausesprite.visible = true;
			case 2:
			    pausesprite.visible = true;
		    case 3:
			    pausesprite.visible = true;
			case 4:
			    pausesprite.visible = true;
		else
		
		    if(PlayState.chartingMode)
			{
			    case 0:
			        pausesprite.visible = true;
			    case 1:
			        pausesprite.visible = true;
			    case 2:
			        pausesprite.visible = true;
		        case 3:
			        pausesprite.visible = true;
			    case 4:
			        pausesprite.visible = true;
			    case 5:
			        pausesprite.visible = true;
		        case 6:
			        pausesprite.visible = true;
			}
		}
can you even fix me this one pls?

**Comment by SAB236YT** [comment]
in `else` is where i have the problem

**Comment by lemz1** [comment]
remove else

**Comment by SAB236YT** [comment]
it does not work btw is always about the `}` in 265 line

**Comment by lemz1** [comment]
can you give me the code or is it still the pausesubstate.hx file

**Comment by SAB236YT** [comment]
still the pause sub stat file 
but here is now code
[PauseSubState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8054416/PauseSubState.txt)

**Comment by lemz1** [comment]
like publish the source to github or upload it to drive

**Comment by SAB236YT** [comment]
ok

**Comment by SAB236YT** [comment]
it would take a bit of time

**Comment by SAB236YT** [comment]
im taking it on drive

**Comment by lemz1** [comment]
ok

**Comment by SAB236YT** [comment]
wait do you just want the source hx.(s) or the whole source?

**Comment by lemz1** [comment]
whole source would be the best but you can also just give me the source folder

**Comment by SAB236YT** [comment]
im just gonna give the whole source then now its in 1000 files there are like 7000 file

**Comment by SAB236YT** [comment]
when u'r gonna give me the source just give me the hx do not compile it

**Comment by lemz1** [comment]
> when u'r gonna give me the source just give me the hx do not compile it

ok

**Comment by SAB236YT** [comment]
https://drive.google.com/drive/folders/1N-k1ryBcL89HmHa9HIekkpotdF3blDLp sorry if it taked a whole day @lemz1

**Comment by lemz1** [comment]
you need to make the drive public

**Comment by SAB236YT** [comment]
what's your email?

**Comment by SAB236YT** [comment]
https://drive.google.com/drive/folders/1N-k1ryBcL89HmHa9HIekkpotdF3blDLp?usp=sharing is this now ok?

**Comment by lemz1** [comment]
it still needs to ask for permission

**Comment by lemz1** [comment]
works now. ok I'll look at the code now and try to fix the stuff

**Comment by lemz1** [comment]
[PauseSubState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8055219/PauseSubState.txt)

**Comment by lemz1** [comment]
just change this to .hx

**Comment by SAB236YT** [comment]
thx bro im gonna close this
