### ISSUE TITLE
Game crashing mid-song

### ISSUE THREAD

**Issue by XRocketBoiX** [ShadowMario/FNF-PsychEngine#4848]
### Describe your bug here.

Ok, so I am trying to make a Splitathon port for FNF Psych Engine. I am using latest source version, but I am not using source, I am just using the version, I am using Lua, anyways, after half of the Splitathon song, the game crashes suddenly showing me this text.
![Screenshot 2022-02-12 172830](https://user-images.githubusercontent.com/87047754/153732147-135bd506-9a8d-4aad-86b8-ea65312c6116.png) Is it because of how long the song is since it's 10 minutes long? Or is it the .json file? Because again, I am using Lua. So ShadowMario, if you see this, can you please fix it on your source please?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, not the source, but I did a whole lot for the Lua.

**Comment by facundomax** [comment]
I think it's because your pc can't stand it or something like that, it also happened to me when there was an overload of things and my memory couldn't read them.

**Comment by XRocketBoiX** [comment]
Well, I am using a $1,000 dollar computer, so I don't think it's that.

**Comment by XRocketBoiX** [comment]
This started happening when I downloaded the latest source code pull request.

**Comment by frantastic24** [comment]
latest commit is working fine here even with 8 minute long songs, needs more info probably

**Comment by XRocketBoiX** [comment]
Hmmm... Well, I'm gonna play the song again, and see if the error is coming up again, if it stops, then I will close this bug report. But Idk, that would be the most info I got, I also have a script that I could post that may be the cause of the problem, and changing characters events.

**Comment by XRocketBoiX** [comment]
Here is the script:


function onEvent(n,v1,v2)
if n == 'Change Character' and v2 == 'bambi-splitathon' then

        cameraFlash('hud', 'ffffff', 0.3, true)

        makeAnimatedLuaSprite('dave-splitathon', 'characters/Splitathon_Dave', -100, 250);
	addAnimationByPrefix('dave-splitathon', 'Mad', 'Mad', 24, false);
	objectPlayAnimation('dave-splitathon', 'Mad');
	addLuaSprite('dave-splitathon', true);
        end

if n == 'Change Character' and v2 == 'dave-splitathon' then

        cameraFlash('hud', 'ffffff', 0.3, true)

        makeAnimatedLuaSprite('bambi-splitathon', 'characters/Bambi_WaitWhatNow', -100, 550);
	addAnimationByPrefix('bambi-splitathon', 'what', 'what', 24, false);
	objectPlayAnimation('bambi-splitathon', 'what');
	addLuaSprite('bambi-splitathon', true);
        removeLuaSprite('dave-splitathon', true);
        end

if n == 'Change Character' and v2 == 'bambi-splitathon-2' then

        cameraFlash('hud', 'ffffff', 0.3, true)

        makeAnimatedLuaSprite('dave-splitathon', 'characters/Splitathon_Dave', -100, 250);
	addAnimationByPrefix('dave-splitathon', 'Happy', 'Happy', 24, false);
	objectPlayAnimation('dave-splitathon', 'Happy');
	addLuaSprite('dave-splitathon', true);
        removeLuaSprite('bambi-splitathon', true);
        end
end

function onBeatHit()
	-- triggered 4 times per section
	if curBeat % 2 == 0 then
		objectPlayAnimation('dave-splitathon', 'Mad');
	end

	if curBeat % 2 == 0 then
		objectPlayAnimation('bambi-splitathon', 'what');
	end

	if curBeat % 2 == 0 then
		objectPlayAnimation('dave-splitathon', 'Happy');
	end
end
