### ISSUE TITLE
Game crashing if section to copy hasn't been copied

### ISSUE THREAD

**Issue by vidyagirl** [ShadowMario/FNF-PsychEngine#4862]
### Describe your bug here.

My friend's game crashes when he tried pasting a note section without originally copying it, I didn't first hand experience it nor do I have any logs for it so I might not be able to give much information, so sorry.

I believe it may be an issue with the sectionToCopy, etc being null if nothing has been copied before, making a null error occur on paste.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, my friend was just charting

**Comment by frantastic24** [comment]
what version is your friend using
needs more information, the point of reporting a bug is explaining how to replicate it so it can be fixed
