### ISSUE TITLE
Change song on death

### ISSUE THREAD

**Issue by main-thing** [ShadowMario/FNF-PsychEngine#4866]
### Describe your problem here.

I'm trying to change the current song after you die. I tried looking througb the source to see if I can change some varibles im playstate but I had no luck. 
As it just goes back to the original song after restart.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope just lua

**Comment by frantastic24** [comment]
You can't load songs through Lua

**Comment by main-thing** [comment]
Maybe if I was able to find a way to change the current song I'll post it here. If it is possible. Which is highly unlikely.
