### ISSUE TITLE
Trying to add a 2nd Opponent character (a dad2 if you will) however, i broke it

### ISSUE THREAD

**Issue by SammuSucksAtCode** [ShadowMario/FNF-PsychEngine#4870]
### Describe your problem here.

I set out to add a 2nd Opponent* character on dad side in without having to replace GF as the character and use GF Sing notes, unfortunately, like every coding project I do, well upon going in and testing out the code, the song its set to have a 2nd dad on gives off an error that reads `[file_contents,assets/data//no-villains.json]` I've tried changing the variable to state something else, and a few other things to tryto fix it, but it didn't work, so I reversed it all to the original set I had, I'm attaching a link to imgur with the code and error I get. If you can shed any light on how to fix it _(or just call me a dumbass your call)_ I would greatly appreciate any and all help

Imgur post with all the screenshots of code I added and the error: https://imgur.com/a/JDpkmrH

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

other than whats in the imgur post no

**Comment by Starmapo** [comment]
`SONG = Song.loadFromJson('no-villains', 'no-villains');`

You forgot to add the second value which indicates the folder

**Comment by SammuSucksAtCode** [comment]
oh ok yeah so it turns out I am just a dumbass however that causes a new problem, now it forces the characters (both opponent and player) to bf and will not change and also the second character doesn't exist. I'm gonna assume that it's cause my coding skills are shit. 
![image](https://user-images.githubusercontent.com/88601365/153772364-155e1147-cc5f-497e-b2bb-56c0c1299493.png)
