### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by rttrtrtrtrtrtrtrtrygtr** [ShadowMario/FNF-PsychEngine#4871]
### Describe your problem here.

when i uploaded my model to the charter editer when i did it it just show the png look 
![Screenshot 2022-02-12 225305](https://user-images.githubusercontent.com/99575565/153739314-2ad669c8-277a-4695-a23a-081bd3aa505d.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by lsoissus** [comment]
did you reskin another spritesheet? if yes, then make your own sprite sheet by using adobe animate or using this https://gamebanana.com/tools/7136

**Comment by Pico8430** [comment]
This is a common problem to new modders. Try downloading a high quality version of the spritesheet and it will work.

**Comment by rttrtrtrtrtrtrtrtrygtr** [comment]
BUT IM ER3 MAKEING A MOD THO

**Comment by rttrtrtrtrtrtrtrtrygtr** [comment]
IM HELPING ER3

**Comment by Pico8430** [comment]
If you don't find anything related to the spritesheet quality, then maybe it's the size of it. Try making your own spritesheet.
