### ISSUE TITLE
custom notes not displaying correctly

### ISSUE THREAD

**Issue by TakiForver** [ShadowMario/FNF-PsychEngine#4873]
### Describe your problem here.

i cant any custom notes to look right and they just look like big blob
![Screenshot_763](https://user-images.githubusercontent.com/63443768/153739623-6ee98618-a8f4-44dc-8d34-a0e8ebe03493.png)
s

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TakiForver** [comment]
> 

im pretty sure i did

**Comment by TakiForver** [comment]
> 

yeah it is

**Comment by frantastic24** [comment]
Either your texture path is wrong, or your .XML file is, or the texture itself
Send all of these so we can see what the issue is

**Comment by TakiForver** [comment]
> Either your texture path is wrong, or your .XML file is, or the texture itself Send all of these so we can see what the issue is
https://drive.google.com/drive/folders/1k8XPyZrSBFRaCjzpAmnIxZdUabBuZT0z?usp=sharing

**Comment by frantastic24** [comment]
You didn't change the image path in .xml

**Comment by TakiForver** [comment]
> 
i changed the path and the problem is still occurring

**Comment by frantastic24** [comment]
works fine here, are you sure you did it correctly
![image](https://user-images.githubusercontent.com/95725102/153767660-1e0a36bf-2943-4760-9e1c-cef843e18715.png)

**Comment by TakiForver** [comment]
> works fine here, are you sure you did it correctly ![image](https://user-images.githubusercontent.com/95725102/153767660-1e0a36bf-2943-4760-9e1c-cef843e18715.png)

yeah im sure

**Comment by frantastic24** [comment]
What does your .XML look like now, just send the file here
