### ISSUE TITLE
chart autosave

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#4874]
### What feature do you want to get added on the **base** engine?

So you know how your like charting something and you close the game on accident and then when you open it again you have to rechart back to the point you where at before?
I think there should be an auto save feature or tell you like "You did not save your last chart. It has auto saved. Would you like to continue?" And if you say yes it will bring you to the chart.
Or auto save it and just leave it at that.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by creeperkidking** [comment]
oh ok thanks

**Comment by MayoALT** [comment]
> there already is an auto save feature just go to song tab and click on load auto save it was made exactly for things like crashs and leaving accidentally (the auto save saves everytime you passes an section)

it saves every time you press enter
