### ISSUE TITLE
whenever i try to save songs, shit fucks up

### ISSUE THREAD

**Issue by mayo78** [ShadowMario/FNF-PsychEngine#4910]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/75394229/153765690-c1723c4b-6569-4c1c-a9fd-0eba1dff21f0.png)

might be a windows issue cause this only started happening after i installed the new update
it happens after i try to create a new folder (the error pops up whenever i try to do anything)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope, this is unmodified psych engine and bf.json has never been altered or changed

**Comment by Theoyeah** [comment]
maybe bf.json is corrupted or the json file for your song

**Comment by MayoALT** [comment]
this has happened with multiple songs
