### ISSUE TITLE
How to make an option who change fnf noteskin

### ISSUE THREAD

**Issue by Theoyeah** [ShadowMario/FNF-PsychEngine#4912]
### Describe your problem here.

I wanna add an option were you can choose 2 noteskin (one the default and an other that is circles) 
How can i do that ?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by maxisepYT1** [comment]
**ShadowMario** did it in [Mind Games Mod](https://gamebanana.com/mods/301107), maybe you can check his [source code](https://github.com/ShadowMario/NewVeryCoolPsychic). Although I tried it, and it didn't work for me.
