### ISSUE TITLE
update the docs please

### ISSUE THREAD

**Issue by Murilo3127** [ShadowMario/FNF-PsychEngine#4958]
### What needs to be documented?

please

**Comment by zLightc** [comment]
Can you specify? I don't understand what do you mean. _(i'm a normal user btw)_

**Comment by Murilo3127** [comment]
> Você pode especificar? Eu não entendo o que você quer dizer. _(eu sou um usuário normal btw)_



> Can you specify? I don't understand what do you mean. _(i'm a normal user btw)_

I'm asking them to update lua's documentation

**Comment by PersonNanoexe** [comment]
what about the lua documentation?

**Comment by Murilo3127** [comment]
> e a documentação da lua?

Yes
