### ISSUE TITLE
This is my last chance pls help me

### ISSUE THREAD

**Issue by facundomax** [ShadowMario/FNF-PsychEngine#4961]
### Describe your problem here.

this is my last time asking about the time bar event, seriously please but please I need help on this. I have everything programmed but for some reason the game crashes when playing a level (the event is that when the time bar is about to reach the end, the time bar goes back like bob and bosip)
, seriously please I need someone to help me with this, I've been trying to program this garbage for about a month, can someone help me with this please?
![20220214_005225](https://user-images.githubusercontent.com/92205752/153797733-e15d4006-7957-44fc-8a8e-a5f3ec42269d.jpg)
![20220214_005251](https://user-images.githubusercontent.com/92205752/153797844-9840a607-e1ab-4a4b-8615-5a6da7f1c7f3.jpg)

![Uploading 20220214_005251.jpg…]()

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by facundomax** [comment]
Okay fine, i will find a way to do this myself

**Comment by main-thing** [comment]
Change this var instead "songPercent"

**Comment by main-thing** [comment]
replace songbar with  this songPercent. Works with source and lua.

**Comment by facundomax** [comment]
> replace songPosBar with songPercent. Works with source and lua.

no, because the codes are made for source, I just want to know d where do I put them as an event

**Comment by KutikiPlayz** [comment]
well first of all, you can't just throw it anywhere in stephit, otherwise it'll do it every step
you gotta put all that code in an if statement
something like
```
if(curStep == 100) {//100 is an example number
	the code you got
}
```
if you want it to be an actual event that you can place in the chart editor you wanna find where the events are, make a new case, call it whatever you want the event to be called, and then put the code below that
example
```
case Time Bar Tween:
	your code
```
and then to be able to use that event you gotta go to ChartingState,hx and add that event to the events list with the exact name you used in playstate

**Comment by facundomax** [comment]
> well first of all, you can't just throw it anywhere in stephit, otherwise it'll do it every step you gotta put all that code in an if statement something like
> 
> ```
> if(curStep == 100) {//100 is an example number
> 	the code you got
> }
> ```
> 
> if you want it to be an actual event that you can place in the chart editor you wanna find where the events are, make a new case, call it whatever you want the event to be called, and then put the code below that example
> 
> ```
> case Time Bar Tween:
> 	your code
> ```
> 
> and then to be able to use that event you gotta go to ChartingState.hx and add that event to the events list with the exact name you used in playstate

I don't have the pc at the moment but I think it will work, in any case I thank you so much :)
