### ISSUE TITLE
Compiling issue (third time)

### ISSUE THREAD

**Issue by zLightc** [ShadowMario/FNF-PsychEngine#4965]
### Describe your problem here.

I get this error when I do lime test windows (with or without debug its the same error) :

https://user-images.githubusercontent.com/96623600/153225694-8c509a04-4a47-40fa-9185-be272d240de4.PNG

tried deleting the export folder and try again and it still doesn't work.

here's the [ApplicationMain.hx](https://pastebin.com/nuzkekK5) file in pastebin.

This will be the third and last time im asking for help on this.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by maxisepYT1** [comment]
Something you **deleted or does not work** in ApplicationMain.hx, check line **299** or reinstall the source code and try again.
