### ISSUE TITLE
Playing button to play at a specific time

### ISSUE THREAD

**Issue by matt-sudo-jpg** [ShadowMario/FNF-PsychEngine#4984]
### What feature do you want to get added on the **base** engine?

this may be the last time imma use the issue tab but what if the engine added where you can play at a specific time like in Kade Engine

EXAMPLE FOR BETTER UNDERSTANDING 
[https://youtube.com/clip/UgkxHUBCfDeNhP-pe0MYiWm0qt86y3ytKztd](https://youtube.com/clip/UgkxHUBCfDeNhP-pe0MYiWm0qt86y3ytKztd)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
Duplicate
