### ISSUE TITLE
GF won't stop being scared when I set an event that scares her

### ISSUE THREAD

**Issue by Silvery2Actual** [ShadowMario/FNF-PsychEngine#5]
It's a simple issue I can't fix:
-I set an event note that sets GF to her "scared" animation
-I've tried everything to unscare her with an event ("idle", "dancing beat", blank)
-She won't stop being scared

**Comment by ShadowMario** [comment]
That's not really 100% a bug, special animations end automatically if the animation is a Looping animation (GF's scared animation is looping, for example)
You can end her scared animation at any time by playing "danceLeft" or "danceRight".

**Comment by ShadowMario** [comment]
No answer in 3 days, i will assume this solves your issue.
