### ISSUE TITLE
its not a questions but I found something cool

### ISSUE THREAD

**Issue by Maskaraid** [ShadowMario/FNF-PsychEngine#5021]
### What is your question?

so the animated icon script its ok even if you change the script name so you can make more character with icons

script i use:
    function onCreate()
        if dadName == 'your character in the characters file' then
            makeAnimatedLuaSprite('animatedicon', 'icons/icon name', getProperty('iconP2.x'), getProperty('iconP2.y'))
            addAnimationByPrefix('animatedicon', 'normal', 'normal icon name', 24, true)
            addAnimationByPrefix('animatedicon', 'losing', 'losing icon here', 24, true)
            --addAnimationByPrefix('animatedicon', 'winning', 'winning icon here', 24, true) in case you want a winning animation
            setScrollFactor('animatedicon', 0, 0)
            setObjectCamera('animatedicon', 'other') -- either is under the health bar or nothing
            addLuaSprite('animatedicon', true)
            objectPlayAnimation('animatedicon', 'normal', false)
        end
    end
    
    function onUpdate(elapsed)
        if dadName == 'character name here again' then
            setProperty('iconP2.visible', false)
            setProperty('animatedicon.alpha',  getPropertyFromClass('ClientPrefs', 'healthBarAlpha'))
            if getProperty('health') > 1.6 then
                objectPlayAnimation('animatedicon', 'losing', false)
            elseif getProperty('health') < 0.4 then
                objectPlayAnimation('animatedicon', 'winning', false)
            else
                objectPlayAnimation('animatedicon', 'normal', false)
            end
        end
        setProperty('camOther.zoom', getProperty('camHUD.zoom'))
        setProperty('animatedicon.x', getProperty('iconP2.x'))
        setProperty('animatedicon.angle', getProperty('iconP2.angle'))
        setProperty('animatedicon.y', getProperty('iconP2.y') + 15)
        setProperty('animatedicon.scale.x', getProperty('iconP2.scale.x'))
        setProperty('animatedicon.scale.y', getProperty('iconP2.scale.y'))
    end

![bandicam 2022-02-15 10-46-34-133](https://user-images.githubusercontent.com/99702778/153983243-166d11ce-2e1f-4681-bddc-7dda003f5794.png)

**Comment by Stilic** [comment]
wtf this should be closed

**Comment by main-thing** [comment]
This should've been in discussions.
