### ISSUE TITLE
My character has a seizure instead of playing notes.

### ISSUE THREAD

**Issue by PotatoKing0419** [ShadowMario/FNF-PsychEngine#5029]
### Describe your problem here.

It looks normal in editor, but not in gameplay. [(Visuals)](https://youtu.be/2-1au40djaM)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Video is private

**Comment by PotatoKing0419** [comment]
> Video is private Also files would be very helpful

I cant attach files because they're not supported, and i made it unlisted instead of private now, so oops on that :|

**Comment by frantastic24** [comment]
All your sing animation names are wrong
They're supposed to be "singLEFT", "singRIGHT", and so on

**Comment by frantastic24** [comment]
Also you can attach files if you just change their extension to .txt

**Comment by frantastic24** [comment]
you can close this then
