### ISSUE TITLE
Chart editor frezze

### ISSUE THREAD

**Issue by Theoyeah** [ShadowMario/FNF-PsychEngine#5044]
### Describe your bug here.

Sometime, when in chart editor, there can be some frezze for 3-10 seconds. (even on 5.0)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, but nothing with chart editor or smt who make lag

**Comment by frantastic24** [comment]
You provided absolutely no info whatsoever, report properly or don't report

**Comment by NokioPyro** [comment]
Frezz?

**Comment by MayoALT** [comment]
when the chart editor frezze 
![image](https://user-images.githubusercontent.com/94536972/154133974-e1530e23-bc0c-48f4-89ff-7c273f07bf6a.png)

**Comment by ImaginationSuperHero528** [comment]
> You provided absolutely no info whatsoever, report properly or don't report

He did what you mean? Cause I get this problem too but when it freezes it... crashes.

**Comment by frantastic24** [comment]
"sometimes it freezes" is not information, either report properly or get a good PC

**Comment by NokioPyro** [comment]
dude ive got an i5 and a gtx 1050 ti and look at me my pc isnt peter griffin eating a rice cake now is it
