### ISSUE TITLE
How do I disable camera bopping mid-song?

### ISSUE THREAD

**Issue by BombasticTom** [ShadowMario/FNF-PsychEngine#5046]
### Describe your problem here.

Example: I want to make my custom camera bop while playing. Is it possible to disable the bop on every 4th beat? And if it is, how can I do that?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing.

**Comment by BombasticTom** [comment]
But I added the help wanted label. This isn't an issue?

**Comment by NokioPyro** [comment]
An issue is something you have wrong with the game, shouldnt you really should have it on the discussions page

**Comment by BombasticTom** [comment]
Other people do it, so I will do it too. The description of this label clearly says "If you need help using the engine".
And if you really want to complain, go and paste the same message on other 128 opened help wanted posts.

**Comment by frantastic24** [comment]
`setProperty('camZooming', false)` works I believe

**Comment by BombasticTom** [comment]
Thanks!
I've just realized that I called the variable `camZoom` not `camZooming`, so tysm for pointing me that out!

**Comment by BombasticTom** [comment]
> `setProperty('camZooming', false)` works I believe

actually that just stops the camera from returning to it's `defaultCamZoom`

**Comment by frantastic24** [comment]
`setPropertyFromClass('ClientPrefs', 'camZooms', false)`
Remember to restore it to the user's preference when closing

**Comment by BombasticTom** [comment]
Thanks!
Do I restore it by using the function `onEndSong`?

**Comment by frantastic24** [comment]
I can't remember the code exactly off the top of my head but I think it was something like
```lua
function onCreatePost()
     camZoomPref = camZoomOnBeat --store if preference is on/off
end

function onDestroy() --script is killed
     setPropertyFromClass('ClientPrefs', 'camZooms', camZoomPref) --restore to user's pref
end
```

**Comment by Steve35117** [comment]
> Go to discussions and qna, Not issues.

there is no discussions

**Comment by BombasticTom** [comment]
this post was made BEFORE discussions were deleted
