### ISSUE TITLE
is it possible to change discord presence name

### ISSUE THREAD

**Issue by MisterOficerDevv** [ShadowMario/FNF-PsychEngine#5051]
### What is your question?

i want to change name of discord presence for psych ive seen some mods do that 
i making my mod in source

**Comment by BombasticTom** [comment]
you could examine all mentions of discord presence 
If you are on Visual Studio Code, simply press `Ctrl + F` (Control + Find), put the term you want to search in code and understand it that way.
But the best approach is to read the official Discord Presence library wiki page, which you can access trough here: https://github.com/Aidan63/linc_discord-rpc

**Comment by KutikiPlayz** [comment]
https://youtu.be/M57nL_PJxnI

**Comment by BombasticTom** [comment]
I didn't even know that released lol!

**Comment by MisterOficerDevv** [comment]
after 4 days im gonna say its working
