### ISSUE TITLE
Hide HUD Event?

### ISSUE THREAD

**Issue by SAB236YT** [ShadowMario/FNF-PsychEngine#5060]
### What is your question?

does somone hae a hide hud event? (notes,health bar,score, misses etc.) pls

**Comment by PrismLight** [comment]
On source code It's simple. Just use ```camHUD.visible = false```
On lua tho, wrap a ```setProperty``` around it. Like this.
```setProperty('camHUD.visible', false)```

**Comment by SAB236YT** [comment]
thx a lot
