### ISSUE TITLE
Flip X or Y For Lua Sprites?

### ISSUE THREAD

**Issue by Honton129** [ShadowMario/FNF-PsychEngine#5077]
### What is your question?

Is There a way of flip the x or y of the lua sprites like animated ones or static graphics?

**Comment by frantastic24** [comment]
`setProperty('tag.flipX', true)`

**Comment by BombasticTom** [comment]
> `setProperty('tag.flipX', true)`

bro I managed to make the lua text opacity using this method thank you so much

**Comment by melocotonwaztaken** [comment]
ty
