### ISSUE TITLE
how can i stop the long notes from giving health when holding them

### ISSUE THREAD

**Issue by Thedumbdude** [ShadowMario/FNF-PsychEngine#5080]
### What is your question?

how can i stop the long notes from giving health when holding them in source

**Comment by frantastic24** [comment]
The title doesn't say what you're using

**Comment by Thedumbdude** [comment]
> The title doesn't say what you're using

in source

**Comment by BombasticTom** [comment]
find the part of the code which gives health, and before giving it, put an if statement
it should look like this:
`
if !isSustainNote {
     your script here
}
`
basically !isSustainNote asks if it's NOT part of a held note

**Comment by BombasticTom** [comment]
go to line 3948
you should see this code:
```
if (!note.isSustainNote)
			{
				combo += 1;
				popUpScore(note);
				if(combo > 9999) combo = 9999;
			}
			health += note.hitHealth * healthGain;
```

just add the health increase into that statement

**Comment by Thedumbdude** [comment]
> go to line 3948 you should see this code:
> 
> ```
> if (!note.isSustainNote)
> 			{
> 				combo += 1;
> 				popUpScore(note);
> 				if(combo > 9999) combo = 9999;
> 			}
> 			health += note.hitHealth * healthGain;
> ```
> 
> just add the health increase into that statement

This is what i was looking for thanks

**Comment by ShadowMario** [comment]
Notes have a hitHealth variable, set it to zero.

**Comment by BombasticTom** [comment]
> Notes have a hitHealth variable, set it to zero.

but he asked how to stop sustained note parts from healing you?

**Comment by frantastic24** [comment]
Sustains are still notes, hitHealth also applies to them

**Comment by BombasticTom** [comment]
But won't it heal you nothing then? I'm sorry but I don't really know how it works.

**Comment by BombasticTom** [comment]
ok! thanks for explaining 👍
