### ISSUE TITLE
Splash effects

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#5084]
### Describe your problem here.

How do I give custom notes their own splash effects? If there's a way to do it without the source code and to do it in the Lua file. please let me know. i couldn't find a youtube tutorial for it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I just added new characters and Notes and changed some sprites

**Comment by SonicXFire1987** [comment]
what line do i put that on?

**Comment by frantastic24** [comment]
How should I know, I don't have your file
Just put the `setPropertyFromGroup` line right under the line you used to change note textures

**Comment by SonicXFire1987** [comment]
its not working

**Comment by frantastic24** [comment]
It's tested and it works
Again, I don't have your file so I can't help you much

**Comment by SonicXFire1987** [comment]
nevermind i got it to work thanks!

**Comment by frantastic24** [comment]
You can close this then
