### ISSUE TITLE
custom game over screen

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#5086]
### Describe your problem here.

How do I add a game over screen for a curtain song? I was trying to do a custom game over screen with sprite sheets that had a game over screen, i even put in as death start, death loop and death confirm but they still came up as bf. What do I do? Please let me know soon. :)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I just added new characters and Notes and changed some sprites

**Comment by SonicXFire1987** [comment]
is there a way to do it without the source code?

**Comment by frantastic24** [comment]
yes, read the wiki, again

**Comment by SonicXFire1987** [comment]
I looked up a tutorial on how to do it but it didn't say on how to do it on just one song is there something I need to add

**Comment by frantastic24** [comment]
You just put the file in your song's data folder

**Comment by KyleOliverDeveloper** [comment]
https://cdn.discordapp.com/attachments/889357899015540736/901470021652447233/script.lua

**Comment by KyleOliverDeveloper** [comment]
Done

**Comment by KyleOliverDeveloper** [comment]
Go to the WIKI page and search for this
![21E30B23-7544-4A7F-8949-A99C915B224A](https://user-images.githubusercontent.com/94708825/154458101-e8c12c12-f5aa-4de8-b6d7-6cda7ef9b1d9.jpeg)
