### ISSUE TITLE
Lua Cutscenes don't work on MacOS

### ISSUE THREAD

**Issue by KirbyKid256** [ShadowMario/FNF-PsychEngine#5088]
### Describe your bug here.

I've been trying to figure out what this bug is with the cutscenes made in Lua, but I can't seem to find what the problem is. I am using my own Mac build, and I haven't seen this bug on Windows systems, so this seems to be a Mac-specific bug.

https://user-images.githubusercontent.com/70983335/154178713-9dbba233-b5c7-4a1a-905d-7db6f6c0d358.mp4

I'm using the Holiday II mod to use as an example, but this has happened with any mod I use that has a cutscene or dialogue in it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added two new public variables in Paths and one new variable in PauseSubState, however these problems existed before I made those changes.

**Comment by beeanie** [comment]
i made a [video](https://www.youtube.com/watch?v=fkP2wANCrOw) about this i hope this helps  
and no i am not trying to self promo i am just trying to help someone

**Comment by CoolingTool** [comment]
i get the same thing on linux

**Comment by KirbyKid256** [comment]
> i made a [video](https://www.youtube.com/watch?v=fkP2wANCrOw) about this i hope this helps and no i am not trying to self promo i am just trying to help someone

It works! Thank you! Also, quick question, would this change still work with Windows users? If so, you or I should probably pitch it as a pull request.

**Comment by frantastic24** [comment]
Someone already made a PR and it was rejected

**Comment by beeanie** [comment]
> > i made a [video](https://www.youtube.com/watch?v=fkP2wANCrOw) about this i hope this helps and no i am not trying to self promo i am just trying to help someone
> 
> It works! Thank you! Also, quick question, would this change still work with Windows users? If so, you or I should probably pitch it as a pull request.

i whould think so

**Comment by Mosnar23** [comment]
> i made a [video](https://www.youtube.com/watch?v=fkP2wANCrOw) about this i hope this helps and no i am not trying to self promo i am just trying to help someone

The video has been taken down. Can you send the file or reupload the video?
