### ISSUE TITLE
Opponent Splashes

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#5096]
### Describe your problem here.

Is there a way for the opponent to display a splash effect when they hit the arrows? someone let me know if thats possible

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I just added new characters and Notes and changed some sprites

**Comment by frantastic24** [comment]
yes
[opponentNoteSplash](https://github.com/ShadowMario/FNF-PsychEngine/files/8076699/opponentNoteSplash.txt)

https://user-images.githubusercontent.com/95725102/154194961-38e425aa-2576-47c9-a93a-0338f43ef287.mp4

**Comment by SonicXFire1987** [comment]
can you do it through Lua?

**Comment by frantastic24** [comment]
it's... literally lua my guy

**Comment by frantastic24** [comment]
a quick fix for sustains: [opponentNoteSplash](https://github.com/ShadowMario/FNF-PsychEngine/files/8076753/opponentNoteSplash.txt)

**Comment by SonicXFire1987** [comment]
oh ok thanks

**Comment by SonicXFire1987** [comment]
what folder do i insert it in?

**Comment by frantastic24** [comment]
mods/scripts if you just want it in all songs

**Comment by SonicXFire1987** [comment]
how do i do it for one song?

**Comment by SonicXFire1987** [comment]
how do do it for one song and also how can i display the hurt ones too

**Comment by Theoyeah** [comment]
i think you need to go to mods/data/Yoursongnamefolder/and put the script.lua there

**Comment by Itz-Miles** [comment]
> but how do i change the texture of the spashes on the lua file, I already tried to change the texture but it didn't work. it just shows the original splash how do i do it one the hurt notes?
> 
> ```
> --made by frantastic24, credit or i disembowel you.
> 
> local texture = 'HURTNoteSplashes' --image path goes here
> 
> function onCreate()
> 
> end
> ```
> 
> Can you tell me what im doing wrong @frantastic24

 @SonicXFire1987  From what I've seen, you can edit any valid component of playState by getting and setting properties.
(e.g.  `setPropertyFromGroup('unspawnNotes', i, 'texture', 'your note name', 'your note name');`
	`setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', ' your splash name');`  )

**Comment by frantastic24** [comment]
That's only for player notes

**Comment by DrebDaDev** [comment]
Is there a way to do it with source
