### ISSUE TITLE
my song wont work?

### ISSUE THREAD

**Issue by jixpy** [ShadowMario/FNF-PsychEngine#5101]
### Describe your problem here.

I've been working on a little parody mod and whatever and I have a week, character, and song. but when I try to use it in chart editor it doesn't work, I put in my song name and it doesn't seem to understand that the song exists, the song length is "0/0" although the real song is minutes long. I have the files in both mods and legit assets and it still won't work, I've tried other default jsons and it worked fine but when I try to use my own it doesn't work, I've tried it with and without a Json file and it won't work, they files are names Insta.ogg and Voices.ogg but it still won't work "I have them both at Ogg the names don't include .Ogg" I've been trying to fix this for days but everyone just says "make sure it's a Ogg files" please help, 
I've put them in this directory: assets>songs>"song name">Inst.ogg=Voices.ogg.
and directory: mods>songs>"song name"> Inst.ogg=Voices.ogg.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

i only changed sprites and added a week, and changed the main music

**Comment by frantastic24** [comment]
Probably bad files, try re-exporting or reconverting them

**Comment by BombasticTom** [comment]
maybe it's because the game is case sensitive?

**Comment by SrtHero278** [comment]
![image](https://user-images.githubusercontent.com/93018286/154379301-35883961-2fa0-42e9-aa82-24d8d29ededb.png)
For Inst and Voices, yes. For the folder, not really.

**Comment by trippinreal** [comment]
It’s possibly bad files. If they were originally .mp3 (or any other file type that isn’t .ogg), simply renaming them isn’t enough, and will cause that error. An easy workaround is to download audacity (it’s free), insert your mp3 into it, and export as an ogg, hope this helps

**Comment by BombasticTom** [comment]
better solution is to convert the audio trough vocalremover.org
