### ISSUE TITLE
How do you change the size of the in-game Alphabet

### ISSUE THREAD

**Issue by djawesomeyt** [ShadowMario/FNF-PsychEngine#5104]
### What is your question?

So I want to edit the size of the Alphabet in the freeplay menu to be a little bit smaller through the source code. I know that it isn't a normal font and I have a feeling that I'm gonna have to edit the flas(although I just want to edit the size for one menu). I I'm just curious if it's even possible tbh.

**Comment by BombasticTom** [comment]
i think you need some haxe code
but I'm not a pro so someone else has to give you an awnser
maybe like find the letter sprite in the code and use "yourspritehere.width = float" and "yourspritehere.height = float"

float is a type of number that has decimal digits don't let that confuse you
