### ISSUE TITLE
Lock icon appears in the top bar of story mode

### ISSUE THREAD

**Issue by MlLulu** [ShadowMario/FNF-PsychEngine#5105]
### Describe your bug here.

If you load in a bunch of mods with the mods menu, and one of the top ones has a locked week, scrolling down will cause the lock icon to show up where the week name is.

![image](https://user-images.githubusercontent.com/94130048/154206285-9449043e-4562-4b44-81af-64faee587c68.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by AlansGames** [comment]
This has now been fixed in the latest action build.
