### ISSUE TITLE
Collisions

### ISSUE THREAD

**Issue by main-thing** [ShadowMario/FNF-PsychEngine#5116]
### Describe your problem here.

How do I detect if a Lua sprite is touching another Lua sprite?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope just using lua.

**Comment by lemz1** [comment]
use `isColliding('object', 'object2')`

**Comment by main-thing** [comment]
> 

Thank you
