### ISSUE TITLE
Too much lag when I try to make characters switch in a song

### ISSUE THREAD

**Issue by sky-93** [ShadowMario/FNF-PsychEngine#5121]
### Describe your bug here.

I'm trying to make a betadciu and I use events to change the characters in the middle of the music, but every time I use more than 8 characters, the level starts to lag a lot. Even with the Persistent Cached Data option disabled, the game consumes more than 5,000 of memory... am I doing something wrong? plz help!

https://www.youtube.com/watch?v=1IWVCvxi_ZA&feature=youtu.be

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
PC issue

**Comment by main-thing** [comment]
You forgot to preload the characters in lua. [Look here.](You forgot to preload the characters in lua. )

**Comment by sky-93** [comment]
how is the script exactly? sorry, I couldn't get it to work

**Comment by main-thing** [comment]
> how is the script exactly? sorry, I couldn't get it to work

function onCreate()
 addCharacterToList('your custom character here', 'dad') -- dad can be boyfriend or gf.
end

**Comment by main-thing** [comment]
Just put this in a lua script called script.lua and put it in the data/`YOURSONGNAME` so it will run the script before the song starts and would stop the game from lagging.
