### ISSUE TITLE
Menu Edit

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#5125]
### Describe your problem here.

Is there a way to edit the Menu without the source code? Reason why im asking is because the source code doesn't work for me. if there is a way, how do i do it? and do i need a lua file for it and where do i insert the file in my mod?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I just added new characters and Notes and changed some sprites and a few lua files

**Comment by frantastic24** [comment]
you can only edit assets and move their around by changing their frame sizes, but that's all you can do without source

**Comment by SonicXFire1987** [comment]
how do I do that exactly? and What lua file do I use?

**Comment by WolfyTail** [comment]
You can't use lua to change the menu. You must use the source code.
