### ISSUE TITLE
Loading Screens

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#5126]
### Describe your problem here.

Is there a way to add Loading Screens? if so can i do it through a lua file

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I just added new characters and Notes and changed some sprites and a few lua files

**Comment by frantastic24** [comment]
Not with Lua

**Comment by SonicXFire1987** [comment]
oh ok well then how do i do it in the source code?

**Comment by frantastic24** [comment]
You don't, because desktop doesn't need it
But if for some reason you want a useless feature, read: #1912
