### ISSUE TITLE
I want to change scroll speed using notes.

### ISSUE THREAD

**Issue by Slimquickhunt** [ShadowMario/FNF-PsychEngine#5144]
### Describe your problem here.

I want to make a mod with a note That increases scroll speed by 0.1 but I can't figure out what function to use if there is one please help.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by BombasticTom** [comment]
You could:
1. Use events (the lazy way)
OR
2. Make a custom note that does the thing specified (the cool way)

**Comment by BombasticTom** [comment]
idk if it works but try to set property called "songSpeed" to your desired speed

**Comment by BombasticTom** [comment]
Tested it out, works.

Make a custom note called example: "changeSpeed" and put this code:

```
function goodNoteHit(id, direction, noteType, isSustainNote)
	if noteType == 'changeSpeed' then
		setProperty('songSpeed', getProperty('songSpeed') + 0.1)
    	end
end
```

**Comment by Slimquickhunt** [comment]
thank you

**Comment by BombasticTom** [comment]
before you close this issue, try this code:

```
function goodNoteHit(id, direction, noteType, isSustainNote)
	if noteType == 'changeSpeed' then
		setProperty('SONG.speed', scrollSpeed + 0.1)
    	end
end
```

**Comment by Slimquickhunt** [comment]
changespeed works

**Comment by BombasticTom** [comment]
gj 👍
now close this issue
