### ISSUE TITLE
FlipX/FlipY on Objects in LUA

### ISSUE THREAD

**Issue by GMan2006i** [ShadowMario/FNF-PsychEngine#5201]
### Describe your problem here.

is there a piece of code that lets me flip the x or the y on a lua sprite/object?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by frantastic24** [comment]
`setProperty('tag.flipX', true)`
