### ISSUE TITLE
sprites bug

### ISSUE THREAD

**Issue by AzardeauxHTF** [ShadowMario/FNF-PsychEngine#5203]
### Describe your bug here.

Hi ShadowMarioi need your help. Wheni generating a sprites sheet and i export in on Mod-Image-character and i epon the sprites its say "it seems that we do not support this file format". I change user i delete and re-install adobe animate (cracked) but its still not work :(
![Capture d’écran 2022-02-17 165802](https://user-images.githubusercontent.com/99895577/154520171-629f8694-e84f-4822-bb3d-5ed6c0867c26.png)

### Command Prompt/Terminal logs (if existing)

```bash
idk how to use commad prompt bc im a loser
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i just creat sprites and i delete (mod list) and (DONT READ ME!)

**Comment by frantastic24** [comment]
Just close this and look up an Adobe animate tutorial.

**Comment by AzardeauxHTF** [comment]
ok
thx

**Comment by AzardeauxHTF** [comment]
uh how to close :/
