### ISSUE TITLE
Q: Is the hit timing window not centered or am I just stupid?

### ISSUE THREAD

**Issue by daisukidaisy** [ShadowMario/FNF-PsychEngine#5213]
### What is your question?

I've observed the visual hit window may be more biased towards late than early, for both upscroll and downscroll.
However, this could just be me having what the boys would call skill issue, so I think I should get a second opinion.

**Comment by BombasticTom** [comment]
you can adjust hit timing windows

**Comment by ShadowMario** [comment]
There's multiple options to adjust the hit windows, including window offset.
