### ISSUE TITLE
Game is crashing

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#5215]
### Describe your bug here.

I have no idea why it's crashing,
but at this specific point in this song it **always** crashes, it wasn't doing this before.
![image](https://user-images.githubusercontent.com/93293747/154551542-2b63d516-e175-4105-a034-de523e25d141.png)

https://user-images.githubusercontent.com/93293747/154551682-e6718418-f780-4a50-849c-920c521ee998.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Info is needed

**Comment by ItsCapp** [comment]
> Info is needed

I don't know what info to add, because I don't know why it happens

**Comment by frantastic24** [comment]
- when it happens specifically
- does it happen without any scripts
- does it happen in another version
- does it happen to anyone else testing the song/script/whatever
When you report a bug you're supposed to explain how to recreate said bug, which people don't seem to understand

**Comment by ItsCapp** [comment]
> * when it happens specifically

at the end of the up sustain, as shown in the video
> * does it happen without any scripts

the scripts don't seem to be the problem
it crashes regardless
> * does it happen in another version

yes, I installed a separate version of psych engine to see if it was the build I was using, it wasn't
> * does it happen to anyone else testing the song/script/whatever

haven't tested this but I'm pretty sure it would crash regardless
>   When you report a bug you're supposed to explain how to recreate said bug, which people don't seem to understand

the problem is I don't know how it happened in the first place

**Comment by ItsCapp** [comment]
it's one of my custom events

**Comment by frantastic24** [comment]
It's not about knowing how it happened, it's about tracing your steps to recreate it
A few more questions/things you can try
- does it happen with another character
- does the same song crash in another state or with another chart
- does it crash if the chart is used in another song

Also uploading files is helpful, even if not always convenient

**Comment by ItsCapp** [comment]
I give up lol
