### ISSUE TITLE
Mods List major bug

### ISSUE THREAD

**Issue by WolfSteelpaw** [ShadowMario/FNF-PsychEngine#5216]
### Describe your bug here.

Does not come with the required modsList.txt file.
![image](https://user-images.githubusercontent.com/69872319/154551906-a363f9ad-1198-41ef-a0aa-43cf14c42dda.png)

### Command Prompt/Terminal logs (if existing)

"file_open,modsList.txt"

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I was attempting to play mods that are loaded when put into the mods folder, so it was mainly unedited.

**Comment by BombasticTom** [comment]
did you accidentally delete the modsList txt file?

**Comment by BombasticTom** [comment]
![image](https://user-images.githubusercontent.com/85838311/155018190-af64361c-33dd-4d36-8f3a-84470b39e5c6.png)

**Comment by frantastic24** [comment]
it's created once you enter the mod menu, it will say there's nothing first but entering again will load everything
