### ISSUE TITLE
Can you make a lua object always stay static?

### ISSUE THREAD

**Issue by BombasticTom** [ShadowMario/FNF-PsychEngine#5231]
### Describe your problem here.

Example: I want a lua object always to be on the center of the camera. Do I need to use setProperty('LuaObject.x', number) or can I use something else?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing.

**Comment by frantastic24** [comment]
attach it to the hud

**Comment by BombasticTom** [comment]
OH MAKES SENSE THANKS

**Comment by BombasticTom** [comment]
btw does this look pro?
![image](https://user-images.githubusercontent.com/85838311/154590976-55fa825c-8150-4edb-85d3-632e41cef3a4.png)
