### ISSUE TITLE
how do i add ui to pysch engine?

### ISSUE THREAD

**Issue by rttrtrtrtrtrtrtrtrygtr** [ShadowMario/FNF-PsychEngine#5232]
### Describe your problem here.

how do i make a ui for pysch engine for the menu?

### Are you modding a build from source or with Lua?

source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
be more specific

**Comment by BombasticTom** [comment]
> be more specific

he's probably asking how to make custom menu just like from the holiday mod

**Comment by frantastic24** [comment]
that's still not specific at all

**Comment by rttrtrtrtrtrtrtrtrygtr** [comment]
like how do i put the logobumpin in to the menu?

**Comment by frantastic24** [comment]
you can't without source

**Comment by BombasticTom** [comment]
> you can't without source

can't you change the image of logobumpin by putting it into the images directory of your lua made mod?

**Comment by rttrtrtrtrtrtrtrtrygtr** [comment]
what do you mean by sourse

**Comment by frantastic24** [comment]
> can't you change the image of logobumpin by putting it into the images directory of your lua made mod?

they wanted to copy it to the menu, or they explained it wrong

**Comment by frantastic24** [comment]
> what do you mean by sourse

source code

**Comment by rttrtrtrtrtrtrtrtrygtr** [comment]
wait i use visual studio code is that a source code or a lua?

**Comment by frantastic24** [comment]
probably source then, but you marked lua here
![image](https://user-images.githubusercontent.com/95725102/154596751-4a478d41-f535-4437-ae37-7612dc2eeb35.png)

**Comment by rttrtrtrtrtrtrtrtrygtr** [comment]
oh i thought visual studio code is a lua thing i did a mistake with that sorry about that

**Comment by rttrtrtrtrtrtrtrtrygtr** [comment]
i fucked up

**Comment by rttrtrtrtrtrtrtrtrygtr** [comment]
i really thought that visual studio code is a luA

**Comment by rttrtrtrtrtrtrtrtrygtr** [comment]
i change it from Are you modding a build from source or with Lua? to source

**Comment by rttrtrtrtrtrtrtrtrygtr** [comment]
so can you help me?

**Comment by rttrtrtrtrtrtrtrtrygtr** [comment]
with that?

**Comment by BombasticTom** [comment]
> with that?

![image](https://user-images.githubusercontent.com/85838311/154709792-199c87fe-7481-4cc4-88ec-9035f81df09b.png)
are you trying to modify the start screen just like this mod did with Lua?

**Comment by BombasticTom** [comment]
> oh i thought visual studio code is a lua thing i did a mistake with that sorry about that

Visual studio code is a text editor which you can use to code with literally any language. You just gotta have some plugins installed for some specific languages. It can support haxe (aka. source code) and lua too

**Comment by trippinreal** [comment]
You can change logoBumpin by putting your png and xml (named logoBumpin) into your /images/ folder in your mod folder
