### ISSUE TITLE
is there a already compiled source code so i can use shaders?

### ISSUE THREAD

**Issue by PikrlRealForReal** [ShadowMario/FNF-PsychEngine#5254]
### Describe your problem here.

i need help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Murilo3127** [comment]
Are these the shaders that the "Bambi and Dave" mod uses?

**Comment by MayoALT** [comment]
download a build from the main branch https://github.com/ShadowMario/FNF-PsychEngine/actions
