### ISSUE TITLE
Global lua and custom options

### ISSUE THREAD

**Issue by SpookyMan16** [ShadowMario/FNF-PsychEngine#5267]
### What feature do you want to get added on the **base** engine?

Custom options could make mods better like a mod could add a remove event option and stuff, Global lua would be in a folder called "GlobalLua" and you could add as many lua scripts as you like and they would run on every song.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Stilic** [comment]
> what is already a thing @MayoALT

global lua scripts, see the wiki

**Comment by SpookyMan16** [comment]
@frantastic24  I was meaning like a person could create custom options.

**Comment by SpookyMan16** [comment]
@Stilic  Cant find it.

**Comment by frantastic24** [comment]
Then just create those options in your Lua? Even if there was a menu for this (there won't be) you still have to code these options into your Lua so there's literally no point

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API

**Comment by frantastic24** [comment]
Now close this

**Comment by BombasticTom** [comment]
![image](https://user-images.githubusercontent.com/85838311/154724835-d7e544fc-8efe-47ea-aab8-2ffc17d06df3.png)
I made this using lua been working on this until 3am since last night
