### ISSUE TITLE
Skin mods seem to simply not work?

### ISSUE THREAD

**Issue by bruh-guy** [ShadowMario/FNF-PsychEngine#53]
At first, I simply replaced the images, xmls, and such in the assets folder, and then the game crashed when I tried any song. I then, tried using the 3.2 hotpatch, and the game crashed again. I then tried using the mod folder and tried the images folder. The game read the icons just fine, but I couldn't see if the actual pngs and xmls were because the game still kept crashing. Do I need custom json files for each skin and need to put them into the character folder?

**Comment by ShadowMario** [comment]
There might be an issue with your xml/png files, this post isn't very informative
