### ISSUE TITLE
STILL Not hiding score text

### ISSUE THREAD

**Issue by SpookyMan16** [ShadowMario/FNF-PsychEngine#5301]
### Describe your problem here.

I tried to hide the score text using lua and it didnt work, my script is:

setProperty("scoreTxt.visible", false);

(https://user-images.githubusercontent.com/89250852/154766780-d5f3374e-b18d-47c9-9017-20622cb4463b.PNG)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
`setProperty`, not `get`

**Comment by SpookyMan16** [comment]
> `setProperty`, not `get` And score text is called `scoreTxt`

still doesn't work

**Comment by kingyomoma** [comment]
`setProperty('scoreTxt.alpha', 0);`
