### ISSUE TITLE
mustHitSection is null and getPropertyFromGroup crashes the game

### ISSUE THREAD

**Issue by BendyGaming0** [ShadowMario/FNF-PsychEngine#5317]
### Describe your bug here.

the mustHitSection variable can be null which can mess up scripts which normally when the song hasn't started yet and it tries to access an array item that doesn't exist, I've tried to fix this in the Lua scripts by grabbing the first item in the SONG.notes array using getPropertyFromGroup but that crashes the game for some reason. please fix this

the code : 
`function getMustHitSection()
    if not mustHitSection == nil then
        return mustHitSection
    else
        return getPropertyFromGroup('SONG.notes', 0, 'mustHitSection')
    end
end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

messed with icons and the camera in Lua but it's not related

**Comment by frantastic24** [comment]
First, you use `notes`, not `SONG.notes`
Second, you should probably use `unspawnNotes` instead
Third, how is this a bug

**Comment by SrtHero278** [comment]
> First, you use `notes`, not `SONG.notes` 
> Second, you should probably use `unspawnNotes` instead 
> Third, how is this a bug
he wants sections. not the notes themselves.
![image](https://user-images.githubusercontent.com/93018286/154806484-82f85a31-e78c-4207-a0b9-a8da5a7f4520.png)

**Comment by frantastic24** [comment]
What does that have to do with my reply
