### ISSUE TITLE
Renaming Ratings via accuracy number.

### ISSUE THREAD

**Issue by IICoffyII** [ShadowMario/FNF-PsychEngine#5321]
### Describe your problem here.

Is this the right command for renaming percentages?
setRatingString()

If so, or not... What can I use to rename the rating using the accuracy percentage?

Like (for example) if the accuracy is 85.66% or lower it'd say something like "C-" or "You suck"...

How would I do that with an LUA script?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Pico8430** [comment]
You can try with a **stage** to put custom acurracy, or if you only want to change the **name of the ratings**, i'll give you an example of what the code would look like.

![accuracyRatingChange](https://user-images.githubusercontent.com/91833725/154801195-92fa1197-a270-4bc7-aa3a-03f9004af73b.png)

You can put this lua script onto your song data folder or on `mods/scripts` for it to execute every time.

**Comment by IICoffyII** [comment]
I've already done that.
I kinda just wanted to do it with specific accuracy numbers instead.

**Comment by main-thing** [comment]
getProperty('ratingPercent')
