### ISSUE TITLE
Video Cutscene for beginning and after song

### ISSUE THREAD

**Issue by MegaCookie** [ShadowMario/FNF-PsychEngine#5322]
### Describe your problem here.

I've been trying to find out a way to play two video cutscenes at the beginning and end of a song. I cannot find any solutions that are for source code. Any ideas on what to do?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I've edited playstate to play a video cutscene at the beginning of a song.

**Comment by DEV-idiotXD** [comment]
```lua
function onEndSong()

	return Function_Stop;
	cutscene_code_1();
end

function cutscene_code_1()

--oooh special codeeee

end

function cutscene_code_2()

-- oooh more code

end

function onStartCountdown()

	return Function_Stop;
end
```
