### ISSUE TITLE
How to add new values to the chart editor?

### ISSUE THREAD

**Issue by DannybotDev** [ShadowMario/FNF-PsychEngine#5324]
### Describe your problem here.

Hello! I've been following Psych Engine for quite some time now! Anyways. I have a stepper that I have created for the chart editor that displays a "Remaining Misses" counter in game. Currently the value is able to be modified by the chart editor, but when I go to save the chart, the value is not present in the JSON. However, if i manually specify the value in the JSON file, the chart editor is able to read this value and display it properly on the stepper. But, this value is not saving when I save the chart. As far as I'm aware all of my code is in line. But I just wanted to see if anyone had any possible solutions to my issue.

![image](https://user-images.githubusercontent.com/84817144/154785899-b470552d-7889-40a6-8a9c-4c85246d6496.png)
![image](https://user-images.githubusercontent.com/84817144/154785921-114dabb8-501b-43e3-9f67-9294197d9e21.png)
![image](https://user-images.githubusercontent.com/84817144/154785935-12e31bf1-1ac2-4cd7-b9be-119e01180636.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited both ChartingState and Song to accomodate a new value.

**Comment by BeansCool54** [comment]
I'm guessing it has something to do with the template song at the beginning of ChartingState

**Comment by Starmapo** [comment]
Did you add the function in "getEvent"? Like one of these:
![image](https://user-images.githubusercontent.com/85134252/154805756-11233554-fc80-42be-bb4f-3ce6530ffb29.png)

If not then that is probably the cause.

**Comment by DannybotDev** [comment]
> Did you add the function in "getEvent"? Like one of these: ![image](https://user-images.githubusercontent.com/85134252/154805756-11233554-fc80-42be-bb4f-3ce6530ffb29.png)
> 
> If not then that is probably the cause.

Ah, I haven't tried that yet, I'm going to do that now.

**Comment by DannybotDev** [comment]
Well now it's saving as null, regardless of what I put as the value.
