### ISSUE TITLE
linux?

### ISSUE THREAD

**Issue by AllMesi** [ShadowMario/FNF-PsychEngine#5338]
### What feature do you want to get added on the **base** engine?

# will there ever be a build for linux?
just wondering

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Playertrip777** [comment]
You can get the build in the Actions tab or compile yourself

**Comment by AllMesi** [comment]
ok thank you
