### ISSUE TITLE
Zoom In / Out LUA Event

### ISSUE THREAD

**Issue by ZachToonz** [ShadowMario/FNF-PsychEngine#5346]
### Describe your problem here.

I've been wanting to make a zoom in/zoom out LUA event feature, but I'm new and don't know how. Can anybody help?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yeah, couple events, 1 song with it's week, a background and a character with icons.

**Comment by BombasticTom** [comment]
well
I made an event for my mod that changes the defaultCamZoom value
it goes like this
```
function onEvent(n, v1)
	if n == "zoomy" then
		setProperty('defaultCamZoom', v1)
	end
end
```
But I am not sure if you want the zoom to instantly zoom in or if you want to use a tween to zoom in
