### ISSUE TITLE
idle (error!)

### ISSUE THREAD

**Issue by Sazzria** [ShadowMario/FNF-PsychEngine#535]
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Source Code

### Show an screenshot/video of your problem.

![Screenshot (263)](https://user-images.githubusercontent.com/89056986/138466094-b11d8e2e-73b9-4f75-8373-9676e1d9bc16.png)

it keeps appearing this and i just don't know how to fix it

**Comment by ShadowMario** [comment]
> But you have to change the Animation name for the idle, go to the Animation tab, select the animation and change its "Animation name on XML" to the idle animation named on your spritesheet's XML.

^
