### ISSUE TITLE
bruh moment please help

### ISSUE THREAD

**Issue by RyanPLayz2000** [ShadowMario/FNF-PsychEngine#5358]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/98992499/154808658-d1f6ebba-58f7-47db-873f-6b449890d044.png)
i keep getting this error while using "lime test windows" with the app not even opened. please help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i tried to add a randomized loading screen

**Comment by BombasticTom** [comment]
Close psych engine

**Comment by main-thing** [comment]
try [this.](https://www.dariawan.com/tutorials/windows/how-know-which-process-using-file-or-folder-windows/) It might help you.

**Comment by MinecraftBoy2038** [comment]
Bro just close psych engine
