### ISSUE TITLE
How would I make part of the background move with the camera?

### ISSUE THREAD

**Issue by CrunchBar41** [ShadowMario/FNF-PsychEngine#5360]
### Describe your problem here.

So I have something like a recording overlay on top of bf and opponent, as well as having the camera move depending on what arrow is being hit. I would like for the recording overlay to also follow the camera, because it looks weird as just a static image. Example below
![image](https://user-images.githubusercontent.com/95093250/154808937-320c076b-9bac-4e3d-86b4-7172bbe72595.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Neco-Arc mod lol

**Comment by frantastic24** [comment]
`setObjectCamera('object', 'camHUD')`

**Comment by CrunchBar41** [comment]
Thanks!
