### ISSUE TITLE
Modded Credits

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [ShadowMario/FNF-PsychEngine#5382]
### Describe your bug here.

I don't know if this is a full-on bug but even when mods are off all of your mods will show up in the credits menu and it's really weird

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No (Action) Base download

**Comment by main-thing** [comment]
That's supposed to happen. Mod creators can add their own credits for their mod. Many mods will lead to alot of people in the credits.

**Comment by ImaginationSuperHero528** [comment]
> That's supposed to happen. Mod creators can add their own credits for their mod. Many mods will lead to alot of people in the credits.

Did even read it? Even when that mod if OFF it still shows!

**Comment by main-thing** [comment]
Sorry i read it wrongly. Hmm yea you are correct the bug happens with me too.

**Comment by ShadowMario** [comment]
Not a bug to be honest

**Comment by ImaginationSuperHero528** [comment]
> Not a bug to be honest

It never did this before. Mostly why I said it. Plus it's annoying to add credits and have to scroll through including if your a youtuber or you have a mod your keeping secret and your live streaming or something.
