### ISSUE TITLE
Custom Death Characters

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [ShadowMario/FNF-PsychEngine#5383]
### Describe your bug here.

Custom Deaths will crash the game and idk if I'm going anything wrong but I don't think I am...
```lua
function onCreate()
    if boyfriendName == 'bftroll3' then
        if dadName == 'shadow' or dadName == 'shadow-crazy' then
            setPropertyFromClass('GameOverSubstate', 'characterName', 'bftroll3-deadgun');
            setPropertyFromClass('GameOverSubstate', 'deathSoundName', 'GunDeath');
        end
        setPropertyFromClass('GameOverSubstate', 'characterName', 'bftroll3-deadstring');
        setPropertyFromClass('GameOverSubstate', 'deathSoundName', 'BFDeathNormal');
    end
end
```
And yes I'm porting this mod... pray for me.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No Base download idk if an Action Download is the problem

**Comment by frantastic24** [comment]
Show your character files at least

**Comment by ImaginationSuperHero528** [comment]
> Show your character files at least

I will send a vid soon

**Comment by frantastic24** [comment]
I guess a video works? But character files would definitely be more useful

**Comment by ImaginationSuperHero528** [comment]
[Here's the video](https://www.youtube.com/watch?v=lAxIBToCdYU)

**Comment by ImaginationSuperHero528** [comment]
Also has files to download in desc

**Comment by frantastic24** [comment]
well i just tested both of bf's animations (mediafire blocked shadow's lmao??) and both are working fine?

**Comment by ImaginationSuperHero528** [comment]
> well i just tested both of bf's animations (mediafire blocked shadow's lmao??) and both are working fine?

Are you using an Action Build?

**Comment by frantastic24** [comment]
tested in updated source and 0.5.1, both work

**Comment by ImaginationSuperHero528** [comment]
Da hell is up with my PC then?!

**Comment by WolfyTail** [comment]
`function onCreate()
	if boyfriendName == 'old-wolfy' then
		setPropertyFromClass('GameOverSubstate', 'characterName', 'old-wolfy'); --Character json file for the death animation
		setPropertyFromClass('GameOverSubstate', 'deathSoundName', 'fnf_loss_sfx'); --put in mods/sounds/
		setPropertyFromClass('GameOverSubstate', 'loopSoundName', 'gameOver'); --put in mods/music/
		setPropertyFromClass('GameOverSubstate', 'endSoundName', 'gameOverEnd'); --put in mods/music/
	end
end`

Just change the "old-wolfy" by your BF's name.

**Comment by frantastic24** [comment]
This is over 2 weeks old and that's not even the issue

**Comment by ImaginationSuperHero528** [comment]
> This is over 2 weeks old and that's not even the issue

It still crashes your wrong
