### ISSUE TITLE
GF Section Addition

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [ShadowMario/FNF-PsychEngine#5386]
### What feature do you want to get added on the **base** engine?

When you enable a GF Section can the gf icon that appears show the icon of the selected gf?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ImaginationSuperHero528** [comment]
How do I change the label to suggtion?

**Comment by BombasticTom** [comment]
that's pretty useless tho

**Comment by cherryiguess** [comment]
you can do that with your own mod, plus it would be kind of useless, like BombasticTom said

**Comment by ImaginationSuperHero528** [comment]
> that's pretty useless tho

I mostly said cause, come on the base game used to do only bf and dad for the icons are you sure?

**Comment by BombasticTom** [comment]
still not a good enough reason to do it
Imagine the girlfriend is the boyfriend and the player is also the boyfriend

**Comment by ImaginationSuperHero528** [comment]
I'm it just feels off to me.

**Comment by ShadowMario** [comment]
Do it yourself cuz i ain't doing this.
