### ISSUE TITLE
Title screen editing

### ISSUE THREAD

**Issue by PersonNanoexe** [ShadowMario/FNF-PsychEngine#5388]
### What is your question?

How the hell does it work?

**Comment by maxisepYT1** [comment]
Let's see, I'll summarize it. The title screen loads **different texts** that are in the FNF alphabet depending on the **author/engine if they modify the titles**, and if you're talking about modifying it look it up on yt. I hope you understand :)

**Comment by PersonNanoexe** [comment]
I meant like how to add assets to it, how to move shit it in, etc. etc.

**Comment by WolfyTail** [comment]
You need **source code** to change the text, the logo and GF position, add a BG, etc.

**Comment by MaybeMaru** [comment]
if you want to move and add shit then use source
