### ISSUE TITLE
Combo.texture

### ISSUE THREAD

**Issue by Cherif107** [ShadowMario/FNF-PsychEngine#5389]
### What feature do you want to get added on the **base** engine?

put a new option that can make you change combo texture in lua

**Comment by mayo78** [comment]
WHY
![image](https://user-images.githubusercontent.com/75394229/154820085-3dde5c79-e64f-485e-a628-57b9fa1728eb.png)

**Comment by Cherif107** [comment]
> WHY ![image](https://user-images.githubusercontent.com/75394229/154820085-3dde5c79-e64f-485e-a628-57b9fa1728eb.png)

my bad im new to issues

**Comment by BombasticTom** [comment]
i think you can already do that
