### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by Mykuullwave** [ShadowMario/FNF-PsychEngine#54]
I have followed all of the tutorials on how to build the fnf source code that I can find, to no avail. I was hoping that this could be explained? Since everything I found didn't work and made no sense what so ever.

**Comment by ShadowMario** [comment]
[I followed this tutorial when i first compiled Friday Night Funkin'](https://gamebanana.com/tuts/13653)

**Comment by Mykuullwave** [comment]
oh tysm
