### ISSUE TITLE
Stage maker

### ISSUE THREAD

**Issue by Piratefoxy216** [ShadowMario/FNF-PsychEngine#540]
### What feature do you want to get added on the base engine?

I know you can do it with lua but that's just not practical because imagine making the entire pokemon game map with lua/code yeah kinda a dumb thing to compare but making a map/stage with code is just time consuming

**Comment by ShadowMario** [comment]
Stop doing duplicates. https://github.com/ShadowMario/FNF-PsychEngine/issues/480 https://github.com/ShadowMario/FNF-PsychEngine/issues/217 https://github.com/ShadowMario/FNF-PsychEngine/issues/269
