### ISSUE TITLE
Video Sprites

### ISSUE THREAD

**Issue by BendyGaming0** [ShadowMario/FNF-PsychEngine#5401]
### What feature do you want to get added on the **base** engine?

sprites having the image source from a video for things that would take up too much space as a sprite sheet (or even a texture atlas), for example a very complex and long series of dances, a real life area.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
what

**Comment by bbpanzu** [comment]
> what

thingy KE has where you can have a video background or a video "sprite" rather than it just being a cutscene

**Comment by MaybeMaru** [comment]
https://discordapp.com/channels/922849922175340586/984011824267677766/1011033865126674502
I know this issue is old but bb and cherry made a script for video sprites

**Comment by TheKitBoi** [comment]
late to say but we’ll wait till this issue is closed

**Comment by tylerandari12** [comment]
> That was too late to say but we’ll wait till this issue is closed

Ye Olde Issue
