### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by GWRRailway** [ShadowMario/FNF-PsychEngine#5407]
### What is your question?

How do achievements work exactly? Basically, in the mods folder is another folder called achievements, but I dont seem to know how to use/code it in. And no, I dont use source code.
![whenIsaythenamesussusamogus](https://user-images.githubusercontent.com/100065407/154833844-bc69385e-6d88-430d-b4a7-56aaaac9fac2.png)

**Comment by Pico8430** [comment]
Custom achievements are only possible on Source Code.

**Comment by ImaginationSuperHero528** [comment]
> ### What is your question?
> How do achievements work exactly? Basically, in the mods folder is another folder called achievements, but I dont seem to know how to use/code it in. And no, I dont use source code. ![whenIsaythenamesussusamogus](https://user-images.githubusercontent.com/100065407/154833844-bc69385e-6d88-430d-b4a7-56aaaac9fac2.png)

They used to be lua to but they had a lot of bugs so they removed it. For how long? idk...

**Comment by ImaginationSuperHero528** [comment]
> Custom achievements are only possible on Source Code.

They used too be lua.
