### ISSUE TITLE
FNF Logo

### ISSUE THREAD

**Issue by xDItsTej** [ShadowMario/FNF-PsychEngine#5415]
### Describe your problem here.

In the main menu, the logo that says "Friday Night Funkin" Is off to the side. Is there any way I can move it?
![image](https://user-images.githubusercontent.com/97074458/154846128-9af01611-57a9-425d-891b-4dbf798759a4.png)
![logoBumpin](https://user-images.githubusercontent.com/97074458/154846143-ec173bea-a673-4817-8397-fbd6af962d4b.png)
[logoBumpin.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8104124/logoBumpin.txt)
(Yes I know the .txt file should be a .xml I just make it a .txt so I could put it on Github)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not anything that affects this.

**Comment by Pico8430** [comment]
Try editing the `gfDanceTitle.json` file.

**Comment by BombasticTom** [comment]
and when you edit it be sure to put it into your mod folder (NOT MODS/YOURMOD/DATA, JUST MODS/YOURMOD)

**Comment by xDItsTej** [comment]
Alright thank you. :D
