### ISSUE TITLE
Put an image over black background of blammed lights

### ISSUE THREAD

**Issue by KirbyKid256** [ShadowMario/FNF-PsychEngine#5420]
### Describe your problem here.

Hi, I wanted to do something a little different during the "blammed lights" event by having the black background halfway through turn into red static for my mod, but I don't know how to overwrite it with Lua currently. Is there any way I can overwrite this just using Lua? Or will I need to edit the source code? And if so, how would I do that?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, and those changes were put in a pull request, however I haven't changed the code since.

**Comment by ImaginationSuperHero528** [comment]
I know the tag for the box give me a sec

**Comment by ImaginationSuperHero528** [comment]
'blammedLightsBlack' is the tag so...
```
function onUpdate()
	setProperty('blammedLightsBlack.visible', false)
end
```
Should have it be gone!

**Comment by frantastic24** [comment]
> function onUpdate()

🗿

**Comment by ImaginationSuperHero528** [comment]
> I don't want it necessarily gone, just overlayed by something else. Although I looked further at your code and found that the blammedLightsBlack is actually a separate sprite just behind all the characters. So I was able to set the static to fade in between them.

oh sorry

**Comment by main-thing** [comment]
> 'blammedLightsBlack' is the tag so...
> 
> ```
> function onUpdate()
> 	setProperty('blammedLightsBlack.visible', false)
> end
> ```
> 
> should have it be gone!

To make it fade it just use doTweenAlpha('bgtween', 'blammedLightsBlack', 0, 1)
