### ISSUE TITLE
Noteskin option

### ISSUE THREAD

**Issue by Theoyeah** [ShadowMario/FNF-PsychEngine#5427]
### What feature do you want to get added on the **base** engine?

For a future version, there sould be a noteskin option like in mind games

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by BombasticTom** [comment]
Shadow already said no. Read issue #3316

**Comment by ImaginationSuperHero528** [comment]
> Shadow already said no. Read issue #3316

What that issue says is different plus Shadow Mario was a person working on Mind Games.

**Comment by ShadowMario** [comment]
Might do it but it's still in doubt because of how weird the code was in mind games

**Comment by Theoyeah** [comment]
Yo shadowmario !!

**Comment by BombasticTom** [comment]
> 

Well the issue is similar to your search and ShadowMario isn't just the coder of Mind Games, coder of Psych Engine too.
