### ISSUE TITLE
dialogue overlaps on song and doesnt have accurate arrow pressing

### ISSUE THREAD

**Issue by the-funky-lad** [ShadowMario/FNF-PsychEngine#5436]
### Describe your bug here.

just watch the [video](https://youtu.be/Bc2hV8Wzz7U)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I fucking didn't, I didn't even modify anything in the script.lua

**Comment by frantastic24** [comment]
mac issue, it has been reported multiple times already so this is a duplicate

**Comment by the-funky-lad** [comment]
Oh, ok

**Comment by frantastic24** [comment]
Now close this

**Comment by the-funky-lad** [comment]
ok
