### ISSUE TITLE
Vhs filter script

### ISSUE THREAD

**Issue by Bibloboom** [ShadowMario/FNF-PsychEngine#5442]
### What is your question?

Does anyone know a VHS filter for a specific song in either lua or source?

**Comment by main-thing** [comment]
Make a sprite that looks like a vhs filter and layer it ontop of the game. (I'm assuming you are talking about the holiday mod.)

**Comment by trippinreal** [comment]
In lua: AddVHSEffect(‘other’)

**Comment by Bibloboom** [comment]
> In lua: AddVHSEffect(‘other’)
> 
> Gotta be on version 5.1.0+

wait so what would i put in ('other')?

**Comment by ShadowMario** [comment]
VHS was removed due to the code not being authorized to be used.
