### ISSUE TITLE
Game crashing Mid-song

### ISSUE THREAD

**Issue by XRocketBoiX** [ShadowMario/FNF-PsychEngine#5443]
### Describe your bug here.

So for some reason, the game keeps crashing on every song in the middle of it, and I need help on how to fix it. Can someone please fix it, or something please?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, not the source, but I did a whole lot for the Lua.

**Comment by frantastic24** [comment]
sounds like a pc issue since you provided no info

**Comment by XRocketBoiX** [comment]
Well, I think it's the framerate option, I had it all the way up to 240 fps, and then brought it down to 100, it kind of fixed the problem, but it still crashed later during a song.

**Comment by XRocketBoiX** [comment]
But, I really don't have much info besides that.

**Comment by XRocketBoiX** [comment]
Also, I was looking at the task manager, and it was taking up over 400 mb of my... "private bytes"? I'm using a different task manager so yeah, that is what it said.

**Comment by frantastic24** [comment]
i've heard of some songs crashing whenever the fps were higher than 60, so probably try that

**Comment by XRocketBoiX** [comment]
Process Hacker is what it's called.

**Comment by XRocketBoiX** [comment]
Ok.

**Comment by BombasticTom** [comment]
> So for some reason, the game keeps crashing on every song in

he mentioned he changed lua stuff, it might be that some stuff incorrectly loaded. That happens to me all the time because I write wrong name of the asset directory or something else.
