### ISSUE TITLE
Bullet note in source code

### ISSUE THREAD

**Issue by Luk9as** [ShadowMario/FNF-PsychEngine#5449]
### Describe your problem here.

Idk how to do it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by BombasticTom** [comment]
I did it once before, but Lua is a better solution as it's more optimized.

**Comment by ImaginationSuperHero528** [comment]
> I did it once before, but Lua is a better solution as it's more optimized.

Agreed.

**Comment by Luk9as** [comment]
Basically all you have to do is create a hurt note and put the damage in 2 and where says "ignoreNote = mustPress;" you change it to "mustPress;" then you're ready
