### ISSUE TITLE
Game Crashes when earning multiple achievements once. (only at the end of the song.)

### ISSUE THREAD

**Issue by AlexBW145** [ShadowMario/FNF-PsychEngine#547]
### Bug report

So someone said that the game crashes at the end of the song, i had to find out and then..
![image](https://user-images.githubusercontent.com/92541723/138530232-204ee28e-60b8-4940-abb9-efa4945058bf.png)
**i beat the hat week and get 90% or more accuracy of the song, i get those achievements at the same time.**

But if there was a way to prevent having two achievements earned at once, then the crash wouldn't happen.

If you know how achievements work and you made a custom one, tell me if this happened to you before?

### Did you edit anything? If so, mention or summarize your changes.

Two Achievements, the one that you need to beat the week and the second one that  you need to have 90% Accuracy or More for the song. (which i did that in story mode) Playstate.hx has achievements string in tho..

**Comment by MayoALT** [comment]
shadow mario said that they were reworking the achievement system, just wait until then

**Comment by MayoALT** [comment]
i think this is fixed now?? i got two achievements at once in my mod and it worked perfectly fine

**Comment by AlexBW145** [comment]
i forgot i left this open.

I kinda know why it crashes.
It's the wrong name for the achievement to get.
i accidently spelt it **hat_week** instead of **hatweek**

Anyways, i now know you can get multiple achievements at once
Closing this useless thread!
