### ISSUE TITLE
Auto Pre-events (Or something like that)

### ISSUE THREAD

**Issue by GMan2006i** [ShadowMario/FNF-PsychEngine#5483]
### Describe your problem here.

Can an event be triggered automatically as a precursor to another?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ImaginationSuperHero528** [comment]
Explain more please my brain is confused.

**Comment by GMan2006i** [comment]
like if it sees an event coming up, itll wait until a certain amount of time before said event, and do other script or event shid

**Comment by frantastic24** [comment]
Just use curStep

**Comment by GMan2006i** [comment]
Yes but I’m lazy, also give an example lmao
