### ISSUE TITLE
Adding a new Logo

### ISSUE THREAD

**Issue by PersonNanoexe** [ShadowMario/FNF-PsychEngine#5492]
### What is your question?

Theres no documentation about it. How do i add it?

**Comment by Playertrip777** [comment]
What do you mean?

**Comment by KirbyKid256** [comment]
You would have to edit the "logoBumpin" sprite sheet and XML to get it to show up in your game.

**Comment by trippinreal** [comment]
Create an animation, get your spritesheet and .json file and put it in /yourmod/images folder 👍
