### ISSUE TITLE
character adjustment menu crashes + other

### ISSUE THREAD

**Issue by heyitsnooby** [ShadowMario/FNF-PsychEngine#55]
Basically, I'm making a custom character.

I've already added his icon, sprite sheet and XML, and I just need to do some offset making.
The offset menu crashes with this custom character only.
Icon doesn't show (however idk how to fix that.)

How his name appears on the debug menu:
![image](https://user-images.githubusercontent.com/82396658/132977664-d8b26dc7-30bc-4099-bc43-7c6b50332876.png)

and yet in the offset menu it is:
![image](https://user-images.githubusercontent.com/82396658/132977706-d1d5def2-c21e-43c2-949c-6ae5f4848027.png)

Then, when you select him, it just crashes.
dunno what to do, i may be a bit stupid, a bit dimwitted, quite a bit dimmer than the others

**Comment by ShadowMario** [comment]
[Did you follow the tutorial?](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Creating-a-Character)
