### ISSUE TITLE
Cloning characters(bf, gf, and dad) in LUA?

### ISSUE THREAD

**Issue by ThermiteFe8** [ShadowMario/FNF-PsychEngine#5501]
### What feature do you want to get added on the **base** engine?

Is it possible to add a LUA callback that lets you copy the current character's animations into an animated Lua sprite? Or even better, let you copy any given character (possibly by directly reading the character.json file) into an animated Lua sprite?

This would let players have more than three characters singing at once without having hella scuffed/bloated LUA scripts. I thought of this when I tried writing a script that generates shadows/reflections of the character sprites in real time - having a callback like this would help a lot and let the script work with *any* given Psych engine mod. 

It'd look something like this
cloneCharacter(spriteTag: String, characterName:String, x: float, y: float);
then you could call the sprite anytime using whatever spriteTag you used, like with other animated Lua sprites, and call the animations using the names defined on the character.json files. 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ImaginationSuperHero528** [comment]
[Click this this is a Lua script in the discord server](https://discord.com/channels/922849922175340586/922851578996744252/931544771195985940)

**Comment by frantastic24** [comment]
This would only save you like 10 lines at most
If you don't want "messy" scripts, you use source

**Comment by ThermiteFe8** [comment]
Oooo - thank you @ImaginationSuperHero528  for the script

**Comment by qvilligan** [comment]
> [Click this this is a Lua script in the discord server](https://discord.com/channels/922849922175340586/922851578996744252/931544771195985940)

nothings showing

**Comment by ImaginationSuperHero528** [comment]
> > [Click this this is a Lua script in the discord server](https://discord.com/channels/922849922175340586/922851578996744252/931544771195985940)
> 
> nothings showing

Then your not in the server @qvilligan!

**Comment by qvilligan** [comment]
> > > [Click this this is a Lua script in the discord server](https://discord.com/channels/922849922175340586/922851578996744252/931544771195985940)
> > 
> > 
> > nothings showing
> 
> Then you aren't in the server @qvilligan!

the psyche engine server right?

**Comment by TheKitBoi** [comment]
> the psyche engine server right?

Yes
