### ISSUE TITLE
Fade to black and then fade back, like in Tails.exe

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#5520]
### Describe your problem here.

how do i make it so it fades to black mid-song and then fade back in, like in Tails.exe!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by megasssdev** [comment]
ask that on https://github.com/ShadowMario/FNF-PsychEngine/discussions lmao
