### ISSUE TITLE
Unknown identifier

### ISSUE THREAD

**Issue by SAB236YT** [ShadowMario/FNF-PsychEngine#5522]
### What is your question?

`source/StoryMenuState.hx:321: characters 4-15 : Unknown identifier : description`
it's telling me that is not a valid command just because
`description.visible = true;`
How to fix?

**Comment by lemz1** [comment]
did you make description a variable

**Comment by SAB236YT** [comment]
k
[StoryMenuState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8116667/StoryMenuState.txt)

**Comment by lemz1** [comment]
[StoryMenuState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8117095/StoryMenuState.txt)
this should be fixed now
you needed to create the variable outside a function
