### ISSUE TITLE
Don't Know how to make foregrounds layer above characters

### ISSUE THREAD

**Issue by Slimquickhunt** [ShadowMario/FNF-PsychEngine#5541]
### Describe your problem here.

I Don't Know how to make foregrounds layer above characters

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mayo78** [comment]
addLuaSprite('foregroundtag', true)

the true at the end makes it so the sprite will spawn on top of the characters
