### ISSUE TITLE
how to make a animated object appear behind an object in psych engine

### ISSUE THREAD

**Issue by Slimquickhunt** [ShadowMario/FNF-PsychEngine#5547]
### Describe your problem here.

I need to make a animated object appear behind an object in psych engine

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Just change the order in which you add the sprites, and this should go in discussions, not here

**Comment by Slimquickhunt** [comment]
that's how I did it

**Comment by Slimquickhunt** [comment]
animated object

**Comment by frantastic24** [comment]
```
addLuaSprite('testicles') -- this will be in the back
addLuaSprite('penis') -- this will be in the front
```
There's your answer

**Comment by Slimquickhunt** [comment]
thats not animated

**Comment by frantastic24** [comment]
It works for animated and static my guy
Close this already
