### ISSUE TITLE
Add Buttons To Delete ALL Special Notes In A Song

### ISSUE THREAD

**Issue by lolbruhfart** [ShadowMario/FNF-PsychEngine#5548]
### What feature do you want to get added on the **base** engine?

Add Buttons To Delete ALL Special Notes In A Song Because I HATE WHEN KIDS THINK ITS 'Charting' AND ADDS 500 HURT NOTES

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by ImaginationSuperHero528** [comment]
Practice Mode

**Comment by frantastic24** [comment]
Skill issue

**Comment by ImaginationSuperHero528** [comment]
> Skill issue

Or botplay- NO rechart it.
