### ISSUE TITLE
Mod folder loading with Loading screens on Desktop

### ISSUE THREAD

**Issue by NickPlayzGITHUB** [ShadowMario/FNF-PsychEngine#5552]
### Describe your problem here.

I enabled Loading screens for my mod on Desktop but whenever I load something from the mods folder it locks up on the loading screen, Is there any code I can add to loadingstate that can load the mods folder?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Loading State.hx

**Comment by Theoyeah** [comment]
Same, but i think that when loading screen is enabled, it seaches on assets folders but never on the mods folder
You need something who force the game to search in the mods folder

**Comment by pasta870** [comment]
> 

so add funkay.png on the mods folder
