### ISSUE TITLE
chart editor suggestion

### ISSUE THREAD

**Issue by blowers69** [ShadowMario/FNF-PsychEngine#5558]
### What feature do you want to get added on the **base** engine?

in the chart editor, if you select the week 6 map. could you make it so that there's a extra option to toggle between the 2 variants of the background freaks. the first variant is the "Senpai" variant, and the second one is the "Roses" variant.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
![image](https://user-images.githubusercontent.com/95725102/155072167-4c8147bb-7120-4b16-a30d-f2acfe040741.png)

**Comment by blowers69** [comment]
shit I forgot about that
