### ISSUE TITLE
How to make that you can open the source code with an app

### ISSUE THREAD

**Issue by bigasschubby** [ShadowMario/FNF-PsychEngine#5587]
### What is your question?

Hi i wanna ask how to make that you can open the game by not typing "lime test windows" Because i want to remove botplay And i want to open the game by Psych Engine.exe and i want to post the mod to gamebanana.

**Comment by TheRealJake12** [comment]
you mean a batch file?

**Comment by bigasschubby** [comment]
> you mean a batch file?

yes

**Comment by ItsCapitalGaming** [comment]
[](https://user-images.githubusercontent.com/93661920/155256703-2fc3ab7c-a05d-48b6-81c8-960a78f1ac17.mp4)
