### ISSUE TITLE
LUA Script

### ISSUE THREAD

**Issue by KFC-Chicken-1212** [ShadowMario/FNF-PsychEngine#5597]
### Describe your problem here.

there is a "end" at the end of the lua script
![image](https://user-images.githubusercontent.com/89538185/155234775-30a9603a-e8c2-4a73-8e1a-66e7c99d7cb2.png)

if its too blurry it says "mods/data/unfairness/script.lua:5: 'end' expected (to close 'function' at line 1) near '<eof>'

the script is here
```
function opponentNoteHit()
	curHealth = getProperty('health')
	if curHealth >= 0.1 then
		addHealth(-0.01)
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by kingyomoma** [comment]
you need to end your `if` statement with an end
Like this:
`function opponentNoteHit()
	curHealth = getProperty('health')
	if curHealth >= 0.1 then
		addHealth(-0.01)
        end
end
`

**Comment by KFC-Chicken-1212** [comment]
> you need to end your `if` statement with an `end` Like this: `function opponentNoteHit() curHealth = getProperty('health')` `ㅤㅤif curHealth >= 0.1 then` `ㅤㅤㅤㅤaddHealth(-0.01)` `ㅤㅤend` `end`

![image](https://user-images.githubusercontent.com/89538185/155239742-242f27c7-c544-4520-b33a-8790d994a7fd.png)

**Comment by frantastic24** [comment]
You missed a line break

**Comment by KFC-Chicken-1212** [comment]
> You missed a line break

https://user-images.githubusercontent.com/89538185/155240024-8671ffcb-d855-4810-bed9-76db646d26a7.mp4

now it just does this
