### ISSUE TITLE
Bit of a Problem

### ISSUE THREAD

**Issue by SuperEvanAlmighty** [ShadowMario/FNF-PsychEngine#5613]
### Describe your problem here.

I have been trying to make a Mod folder, but whenever I add a character it doesn't show up on the debug menu. How could I fix this.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
If you're using a separate folder for the mod (`mods/modName`) then make sure you're in a song from the same pack

**Comment by SuperEvanAlmighty** [comment]
I don't have songs currently just characters and bgs

**Comment by SuperEvanAlmighty** [comment]
I think thats the problem

**Comment by ImaginationSuperHero528** [comment]
In the debug menu have you noticed the directory thing at the bottom? Select the folder that you put your character (or whatever) in and now it should show up.
