### ISSUE TITLE
BG Offsets

### ISSUE THREAD

**Issue by snooze789** [ShadowMario/FNF-PsychEngine#5617]
### Describe your problem here.

When i try to change the offsets of my background it just does not move 
![image](https://user-images.githubusercontent.com/89538185/155259758-075064ec-b7dc-461a-8e43-4b9e0503138c.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ImaginationSuperHero528** [comment]
Show the script
