### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by bigasschubby** [ShadowMario/FNF-PsychEngine#5625]
### Describe your problem here.

when i type lime test windows it says : source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Reycko** [comment]
Invalid, you are using a non psych / Psych Engine Mod with a modified executable, Put the issue into the mod source code.

**Comment by bigasschubby** [comment]
> source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }

i dont actually understand

**Comment by Reycko** [comment]
for the second time, you are using a non psych / Psych Engine Mod with a modified executable, Put the issue into the mod source code.

**Comment by bigasschubby** [comment]
> for the second time, you are using a non psych / Psych Engine Mod with a modified executable, Put the issue into the mod source code.

you just copied the last comment

**Comment by Reycko** [comment]
> > for the second time, you are using a non psych / Psych Engine Mod with a modified executable, Put the issue into the mod source code.
> 
> you just copied the last comment

:/
What mod are you using ?

**Comment by Reycko** [comment]
If you use psych engine EK, create an issue on [this github repo](https://github.com/TheZoroForce240/FNF-PsychEngine-EK-Port)

**Comment by Reycko** [comment]
(ek = extra keys)

**Comment by bigasschubby** [comment]
> (ek = extra keys)

im using the normal
