### ISSUE TITLE
Videos not playing properly

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#5627]
### Describe your bug here.

For some reason, **videos/cutscenes** won't play properly on my computer. They simply get **skipped**.
I even played a song, which seems to make you **play while video** or similar **plays**, and each time, the **gameplay/video** gets **paused** (e.g. pressing pause or changing the active window) the **game** simply **crashed/closes**.

Though I do not know, if the source code or lua has been used to modify.
_(There even are existing gameplays of those mods I played)_

_I do have x64 bit and probably enough RAM with 16 to run them. Worked out on fnf before_

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I played other mods

**Comment by Theoyeah** [comment]
You dont need to make a cutscenes folder in the videos folder

**Comment by BombasticTom** [comment]
and if you have a cutscenes folder, change directory of the video to "cutscenes/YOURVIDEOHERE"
