### ISSUE TITLE
Lua scripting help

### ISSUE THREAD

**Issue by main-thing** [ShadowMario/FNF-PsychEngine#5628]
### Describe your problem here.

Basically im trying to detect if the current player character has invalid animation named "doesnotexist". I've tried to do it and here's what I tried.
 ```
function onCreate()
local placeholder = 'doesnotexist'
if not getProperty('boyfriend.animOffsets.exists', placeholder) then
debugPrint('animation:'+ placeholder + 'does not exist!')
end
end
```
After running the code nothing happens!
I know that this is the wrong way to use getproperty. I also getPropertyFromGroup and getPropertyFromClass to help me but it gave me no luck(or I used them wrong aswell). 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No. Just the base engine compiled with lua stuff.

**Comment by Stilic** [comment]
u can't call functions lol

**Comment by main-thing** [comment]
Is there a way to create a lua function with thoseconditions above?

**Comment by DEV-idiotXD** [comment]
> Is there a way to create a lua function with thoseconditions above?

yes

```lua
function doesnotexist()
local placeholder = 'doesnotexist'
if not getProperty('boyfriend.animOffsets.exists', placeholder) then
debugPrint('animation:'+ placeholder + 'does not exist!')
end
end
```

**Comment by DEV-idiotXD** [comment]
like put it in its own function then call it like this

``` lua
function onUpdate(elapsed)
doesnotexist();
end
```

**Comment by main-thing** [comment]
The problem is that this line getProperty('boyfriend.animOffsets.exists', placeholder) is not valid. Im trying to find a way to make this line into a function. So i can check if a animation exists in the character sprite. The script i put above is just a debug script whoch I don't know how to write properly. (sorry if I sound mean or anythin.)

**Comment by Stilic** [comment]
i mean, you can't call `exists` like that because this is a haxe function. you can't call haxe functions in lua.

**Comment by main-thing** [comment]
> i mean, you can't call `exists` like that because this is a haxe function. you can't call haxe functions in lua.

Yes you're correct. I tried to play around with the variable with true and false ad it just deleted the object I set false to. I'll just remove this from my script as its only used for convenience purposes. As its a script that adds miss sprites to sprites which don't have them.
