### ISSUE TITLE
game crashes when i die

### ISSUE THREAD

**Issue by mapleeeeeeeeeeeeee** [ShadowMario/FNF-PsychEngine#5629]
### Describe your bug here.

basically i was playing zanta from the holiday mod part two [taiko difficulty] and when i died the game just closed

[there is a script where there is a bug when u die it crashes but i wasent using that script]

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
If it's from a mod why are you reporting it here

**Comment by Wither362** [comment]
Yeah, it crash because there are two characters with different die animations, I had the same bug, delete one of the characters and it will work
