### ISSUE TITLE
FunkinLua.hx - noteTweenAngle duplicate

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#5631]
### What is your question?

I just found out, that the lua method **_"noteTweenAngle"_** is documented **twice** in the file _**"FunkinLua.hx"**_. That could confuse some.
Or is there a specific reason for that?

_I don't know if to report it as a bug or question tho-_

**Comment by Wither362** [comment]
You are right, it’s duplicated, the lines `515` to the line `528`, and the line `575` to the line `588`, I think it’s duplicated because they didn’t know it
