### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by AdmiralUsername** [ShadowMario/FNF-PsychEngine#5651]
### Describe your problem here.

Source Code compilation. Everyone says it's easy, but I've found all of the tutorials are outdated and I have no idea how.

Version is 0.5.2

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by MijaeLio** [comment]
?, wdym with that, there is an explanation about installing the source in README.md
![image](https://user-images.githubusercontent.com/87155057/155450281-968dd074-97a7-417d-9805-617cb1e757dc.png)

**Comment by Wither362** [comment]
> ?, wdym with that, there is an explanation about installing the source in README.md
> ![image](https://user-images.githubusercontent.com/87155057/155450281-968dd074-97a7-417d-9805-617cb1e757dc.png)

And then you select the folder of the code, select the `open with git bash`, and then write if you are in windows write this: `lime test windows`, if you are in Mac type: `lime test mac`, and if you are with linux write: `lime test linux`
