### ISSUE TITLE
Were thicc Daddy Dearest and Psyka controversial?

### ISSUE THREAD

**Issue by KirbyKid256** [ShadowMario/FNF-PsychEngine#5696]
### What is your question?

I wanted to ask why those two were removed from Psych Engine because I wanted to add them back in as easter eggs in my fork. I don't want to accidentally get into any past drama or controversy, so I wanted to know if they were removed for a specific reason

**Comment by cherryiguess** [comment]
Psyka was removed due to controversial drama with an old team member, I don't know why "thicc" dd was removed but yeah

**Comment by HiroMizuki** [comment]
> Psyka was removed due to controversial drama with an old team member, I don't know why "thicc" dd was removed but yeah

hot dilf was removed cuz Psych is now a full prerelease
