### ISSUE TITLE
Custom Options With Build

### ISSUE THREAD

**Issue by B01Coding** [ShadowMario/FNF-PsychEngine#5701]
### What feature do you want to get added on the **base** engine?

Like 

Spanish ✔️ = Spanish Custom Dialog

only aviable when mods on

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by Pico8430** [comment]
![bruuuuuuuuh](https://user-images.githubusercontent.com/91833725/155579462-99e429de-9b62-4550-a489-a7d6e38c04c4.png)

**You failed the test**, great.

**Comment by Theoyeah** [comment]
@B01Coding you **fucking** idiot

**Comment by ImaginationSuperHero528** [comment]
> @B01Coding you **fucking** idiot

That's... rude like what the hell?!

**Comment by ImaginationSuperHero528** [comment]
> ### What feature do you want to get added on the **base** engine?
> Like
> 
> Spanish ✔️ = Spanish Custom Dialog
> 
> only aviable when mods on
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> A good idea

This is a good idea but I feel like this would be able to able and disable Lua scripts at the same time if you could make certain note type only appear with said setting on.

**Comment by B01Coding** [comment]
Like Dialoge
Custom
Like
Dialoge-Spanish.json

**Comment by BombasticTom** [comment]
> ### What feature do you want to get added on the **base** engine?
> Like
> 
> Spanish ✔️ = Spanish Custom Dialog
> 
> only aviable when mods on
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> A good idea

i think it's better to make a setting containing list of languages called "language"

**Comment by ImaginationSuperHero528** [comment]
Check psych someone made custom lua options

**Comment by BombasticTom** [comment]
?

**Comment by BombasticTom** [comment]
oh cool cool i thought the person just reused my code lol
