### ISSUE TITLE
LUA Scripts

### ISSUE THREAD

**Issue by DoomSlayer-cm** [ShadowMario/FNF-PsychEngine#5713]
### What is your question?

why don't you have the lua scripts be direct download links like to google drive instead of discord?

**Comment by ImaginationSuperHero528** [comment]
Cause it's faster.

**Comment by DoomSlayer-cm** [comment]
isn't accessability key for everyone to find modding easier? sure, google drive/mega.nz/etc. are slower, but then everyone will be able to download and use the scripts, instead of only those who have the ability to use discord.

**Comment by ImaginationSuperHero528** [comment]
Yeah I'd say that was the right choice.
