### ISSUE TITLE
LUA Difficulty specific

### ISSUE THREAD

**Issue by Bibloboom** [ShadowMario/FNF-PsychEngine#5719]
### What is your question?

How do i make a part of the script only activate on a specific difficulty? (Ex: Easy, Normal, Hard, etc.)

**Comment by frantastic24** [comment]
`if difficulty == X then`, check discussions before posting because this has already been asked and answered, and post questions like this in discussions as well

**Comment by trippinreal** [comment]
like frantastic said, but it’s important to note that X will change depending on how many difficulties you have.

for example, if you’ve got easy, normal and hard, easy would be 0, normal would be 1 and hard would be 2
however, say you’ve got custom difficulties, like hard and fucked (a la online VS), hard would be 0 and fucked would be 1.
it’s about the number of difficulties and their order. Hope this helps
