### ISSUE TITLE
How Can I Make A FreePlay Song Go In A Specific Part Of FreePlay?

### ISSUE THREAD

**Issue by lolbruhfart** [ShadowMario/FNF-PsychEngine#5721]
### What is your question?

The Title

**Comment by BombasticTom** [comment]
you can't
but what you can do to skip songs is to hold shift + direction you wanna head to

**Comment by AlansGames** [comment]
If you mean change the order just change the order in the week editor

**Comment by WolfyTail** [comment]
Do you mean the song order in freeplay?

If it's that, just go to **assets/weeks/weekList.txt** and change it.
