### ISSUE TITLE
How to bob shake

### ISSUE THREAD

**Issue by JVGamerzbz** [ShadowMario/FNF-PsychEngine#5727]
### Describe your problem here.

ok so, i tried to do bobmadshake but its unknown identifier. pls HOWWW

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, just need more features.

**Comment by main-thing** [comment]
Please explain the effect.
