### ISSUE TITLE
HELP Me

### ISSUE THREAD

**Issue by fnfbuttomanybugs** [ShadowMario/FNF-PsychEngine#5730]
### Describe your problem here.

HOW TO FIX Could not automatically setup MSVC EROR MESSEAG pls help me

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i change mainstagesmenu.hx for delete mods menu

**Comment by BombasticTom** [comment]
revert the code of `mainstagesmenu.hx`
find the `optionShit` array
and remove line `#if MODS_ALLOWED 'mods', #end`
