### ISSUE TITLE
Random images

### ISSUE THREAD

**Issue by facundomax** [ShadowMario/FNF-PsychEngine#5731]
### Describe your problem here.

How do I add images in a certain part of the song, example: in a part of the song, I would like the images to appear behind or in front of the characters to accompany the music (I will also include animations with xml)

### Are you modding a build from source or with Lua?

Source and lua

### What is your build target?

Windows x64

**Comment by trippinreal** [comment]
Take a look at the LUA API for psych engine, it should have the functions you’re looking for. Additionally, bbpanzu makes a good psych engine tutorial, and he demonstrates how to add images. 
if you’re wondering how to add it at a certain time, go into the chart editor, find when you want your image to appear during the song and make a note of the Step: value.
Then, in a lua script, you can put

if curStep == [Your Step Value] then
     — add your code here

**Comment by facundomax** [comment]
Thanks :)

**Comment by facundomax** [comment]
Solved
