### ISSUE TITLE
FreePlay

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#5750]
### Describe your problem here.

How do I make a freeplay song unlockable after beating a curtain week. I already have the week and the freeplay song ready I just don't know how to make it appear after the week is beaten. can you give me a step by step guild on how to do it. Please respond soon. thank you.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I just added new characters and Notes and changed some sprites and a few lua scripts

**Comment by frantastic24** [comment]
This is an option in the week editor

**Comment by SonicXFire1987** [comment]
wait really? Sorry im still new to fnf moding and Im a little confused with how some things work. Ik now how to insert a song and a week and I know how to make it free play only but after that idk how i guess ill try to experiment with it more

**Comment by SonicXFire1987** [comment]
ok nevermind i still don't know what im doing
**Basically what im trying to do**
1. When the mod opens the freeplay song isnt there
2. once the week is beaten the freeplay song will now be in freeplay

Can you tell me how to do that, do i need a script for it?

**Comment by Pico8430** [comment]
You nearly can't on lua.

**Comment by SonicXFire1987** [comment]
> > ok nevermind i still don't know what im doing **Basically what im trying to do**
> > 
> > 1. When the mod opens the freeplay song isnt there
> > 2. once the week is beaten the freeplay song will now be in freeplay
> > 
> > Can you tell me how to do that, do i need a script for it?
> 
> read everything in the wiki page [here](https://github.com/ShadowMario/FNF-PsychEngine/wiki) also if there is no term that you wanted to find, simply press number 8 in the main menu of psych engine you will get a prompt for all stuff you can modify with lua

8 didn't work at all TwT. all i can do is press 7 and select whats on screen. ill take a look at the wiki though and i'll let you know if i dont find what im looking for

**Comment by SonicXFire1987** [comment]
> you gotta press 8 on the menu screen (with all options)

Im still confused which menu are you talking about?

**Comment by SonicXFire1987** [comment]
I need you to be more spicific

**Comment by BombasticTom** [comment]
![image](https://user-images.githubusercontent.com/85838311/156784251-7dd15f22-e121-475c-bd1f-90950da9da08.png)
press 8 here :/

**Comment by SonicXFire1987** [comment]
I did and it didn't do anything

**Comment by BombasticTom** [comment]
then you probably have an outdated psych engine version
don't press 8 on story mode menu
press 8 on THIS SPECIFIC PART OF THE GAME

**Comment by frantastic24** [comment]
You press 7 not 8

**Comment by BombasticTom** [comment]
OH OOPS

**Comment by SonicXFire1987** [comment]
TwT but what do I do now?

**Comment by BombasticTom** [comment]
follow a proper tutorial maybe.

**Comment by SonicXFire1987** [comment]
ok
