### ISSUE TITLE
How to give the FPS Counter an outline

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#5753]
### What is your question?

(Source)
Hi,
I wanted to know how to make the FPS Counter have an outline (black). I don't know how to do it with TextField. 
With FlxText it would work easily since it already has a borderstyle function

**Comment by Stilic** [comment]
see how ke done that.

**Comment by lemz1** [comment]
> see how ke done that.
I tried doing that but it just kept crashing

**Comment by Stilic** [comment]
> > see how ke done that.
> 
> I tried doing that but it just kept crashing

you dumb so
