### ISSUE TITLE
BG stuff

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#5762]
### Describe your problem here.

How do I add stuff to the background like we can in Week 5 or Week 6. and can you do it through Lua
let me know please

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I just added new characters and Notes and changed some sprites and a few lua scripts

**Comment by BombasticTom** [comment]
what do you mean by 

> like we can in Week 5 or Week 6

**Comment by SonicXFire1987** [comment]
> what do you mean by
> 
> > like we can in Week 5 or Week 6

I mean add background sprites like the school girls in week 6 or the crowd of people in week 5. how do I do that?

**Comment by ManMaster707** [comment]
makeAnimatedLuaSprite('tag', 'name of .png and .xml', x, y);
addAnimationByPrefix('tag', 'tag of the anim.', 'name of anim. in .xml', fps, true);
        objectPlayAnimation('tag', 'tag of the anim', false);
        setScrollFactor('tag', x, y);
        addLuaSprite('tag', false);

for extra information look on the wiki

**Comment by SonicXFire1987** [comment]
```
makeAnimatedLuaSprite('stagefront', 'snow', 590, -180);
addAnimationByPrefix('stagefront', 'snowing', 'snow', 3, true);
objectPlayAnimation('stagefront', 'snowing', false);
setScrollFactor('stagefront', 590, -180);
addLuaSprite('stagefront', false);
```

I did this but it didn't show up. did I do something wrong?

**Comment by BombasticTom** [comment]
your animation has 3 frames
scrollfactor is a number between 0 and 1

**Comment by SonicXFire1987** [comment]
i figured it out but thanks
