### ISSUE TITLE
how to make botplay hit notetype

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#5778]
### What is your question?

what do I need to add to my notetype script to make botplay hit the note

**Comment by BombasticTom** [comment]
there's a property for notes in lua
i think you gotta set it like this:

if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then -- Doesn't let Dad/Opponent notes get ignored
       setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true) --Miss has no penalties
end

1. This is from the official wiki page of Psych Engine;
2. You should put this into your unspawned notes loop.

**Comment by BombasticTom** [comment]
wait i didn't read the question lmao
put `ignoreNote` to `false`
