### ISSUE TITLE
(REPOST!) how to add randomized loading screens or bug fix them

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#5781]
### Describe your problem here.

Soooo im trying to make randomizeed loading screens i have 3 and when i use the cache.hx file thats provided by tutorials it gives me this error in the screenshot
https://user-images.githubusercontent.com/56323671/155807394-eee5219f-5940-483a-a751-60dafc91e70f.png
idk why it does it i really wana add a loading screen due to main things like the mods using a lot of files that take a long while to load Thanks! -Macho

btw if anyone knows how to make a custom message when you use botplay please tell me :)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by RyanPLayz2000** [comment]
same here

**Comment by machonessiebaby** [comment]
> same here

youve gotta comment out every single line with the work sound for it to work
