### ISSUE TITLE
modchart.lua does not working on windows

### ISSUE THREAD

**Issue by MuGunMG** [ShadowMario/FNF-PsychEngine#58]
function start(song)
    spinLength = 0
end

function update(elapsed)

    if difficulty == 2 and curStep > 400 then
        if spinLength < 32 then
            spinLength = spinLength + 0.2
        end

        local currentBeat = (songPos / 1000)*(bpm/60)
	for i=0,7,1 do
            local receptor = _G['receptor_'..i]
            receptor.angle = (spinLength / 7) * -math.sin((currentBeat + i*0.25) * math.pi)
	    receptor.x = receptor.defaultX + spinLength * math.sin((currentBeat + i*0.25) * math.pi)
	    receptor.y = receptor.defaultY + spinLength * math.cos((currentBeat + i*0.25) * math.pi)
        end
    end
end

how can i solve this issue?

**Comment by ShadowMario** [comment]
Modcharts from KE =/= Modcharts from Psych Engine

**Comment by MuGunMG** [comment]
can you help me?

**Comment by MuGunMG** [comment]
> Modcharts from KE =/= Modcharts from Psych Engine

I don't know how to write lua script in psych engine. can you help me??

**Comment by ShadowMario** [comment]
I'm talking with Nebula, currently planning in adding Tables to lua
