### ISSUE TITLE
Is it possible to have a video as the stage via shaders?

### ISSUE THREAD

**Issue by Kasey-py** [ShadowMario/FNF-PsychEngine#5801]
### Describe your problem here.

I'm running on a version of psych that has shaders, yes. I was wondering if I could import a video as the stage bg to play throughout the song. (Please provide example script if you can, thanks!)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not that I'm aware of.

**Comment by BendyGaming0** [comment]
currently, no. videos are just for cutscenes right now, you would have to modify some of the FlxVideo code in haxe to have it work as a sprite
