### ISSUE TITLE
Dialogue Delay

### ISSUE THREAD

**Issue by Joe-Pizza-Emmett** [ShadowMario/FNF-PsychEngine#5807]
### Describe your problem here.

So I am putting dialogue in a mac version of Psych, and it loads correctly. But the issue is that when the countdown says  'Go!' thats when the dialogue is loaded, and the dialogue is played out after the song starts, thus you die immediately. I didn't screw with the .lua or anything, so I'm extremely confused.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by Joe-Pizza-Emmett** [comment]
I'm already using the script.lua from the wiki. How would I edit it to work if I need to edit it at all?

**Comment by frantastic24** [comment]
It's an issue with Mac, I believe a recent source commit fixed it so I'd suggest trying that

**Comment by BombasticTom** [comment]
oh yeah i forgot about that
