### ISSUE TITLE
A way to have freeplay play dialogue or a cutscene.

### ISSUE THREAD

**Issue by XS09-dev** [ShadowMario/FNF-PsychEngine#5811]
### What feature do you want to get added on the **base** engine?

An option where it allows you to play a cutscene or dialogue by going into freeplay and selecting a song. Similar to Friday Night Funkin' Modding Plus's option. Just so modders can look at there dialogue and cutscene to see how it looks.  Another edit: I am not using LUA

### To test your sight, and reliability, please select the option of what should NOT be requested.

The 6k support and stage editor thing.  edit because I forgor Also winning icons

**Comment by BombasticTom** [comment]
use lua
literally instead of putting the check `if isStoryMode and not seenCutscene` then just put `if not seenCutscense then`

**Comment by XS09-dev** [comment]
No I don't like lua. I only use it for certain things. I can code using HX I am familiar with it. but Lua is not something I like nor want to do.

**Comment by BombasticTom** [comment]
pull a request for the feature then

**Comment by BombasticTom** [comment]
i can quickly write the code rn if you want

**Comment by XS09-dev** [comment]
Ok how do I do a pull req

**Comment by BombasticTom** [comment]
go to pull requests section of this git repository

**Comment by Reycko** [comment]
> No I don't like lua. I only use it for certain things. I can code using HX I am familiar with it. but Lua is not something I like nor want to do.

ur so stubborn lol

**Comment by BombasticTom** [comment]
fr lua is so underrated

**Comment by machonessiebaby** [comment]
> fr lua is so underrated

so true i used it for so many cool things

**Comment by DragShot** [comment]
> No I don't like lua. I only use it for certain things. I can code using HX I am familiar with it. but Lua is not something I like nor want to do.

Then just code it yourself lol. I did it and it doesn't take that long.

**Comment by BombasticTom** [comment]
> > No I don't like lua. I only use it for certain things. I can code using HX I am familiar with it. but Lua is not something I like nor want to do.
> 
> Then just code it yourself lol. I did it and it doesn't take that long.

also did it you just gotta add 7 new lines maybe

**Comment by XS09-dev** [comment]
> fr lua is so underrated

Sorry I don't like nor know how to use LUA I'm not going to put my 3 years of programming to waste just to use lua 24/7

**Comment by DragShot** [comment]
> Sorry I don't like nor know how to use LUA I'm not going to put my 3 years of programming to waste just to use lua 24/7

Programming?... or coding?

**Comment by XS09-dev** [comment]
> > Sorry I don't like nor know how to use LUA I'm not going to put my 3 years of programming to waste just to use lua 24/7
> 
> Programming?... or coding?

Programming and coding are the same thing.

**Comment by DragShot** [comment]
> Programming and coding are the same thing.

I see those three years have been for naught then.

**Comment by XS09-dev** [comment]
> > Programming and coding are the same thing.
> 
> I see those three years have been for naught then.

How 💀 This could've been avoided if people weren't so pushy with LUA I don't like it and I never will.

**Comment by DragShot** [comment]
> How skull This could've been avoided if people weren't so pushy with LUA I don't like it and I never will.

You being unable to deal with a pitiful script kiddie language is a you problem, not theirs.

**Comment by XS09-dev** [comment]
> > How skull This could've been avoided if people weren't so pushy with LUA I don't like it and I never will.
> 
> You being unable to deal with a pitiful script kiddie language is a you problem, not theirs.

My dude how tf do I code in lua when I only learnt C# and C++. HX is similar to them. Lua is like coding in java drunk as fuck on a Monday.

**Comment by XS09-dev** [comment]
> > How skull This could've been avoided if people weren't so pushy with LUA I don't like it and I never will.
> 
> You being unable to deal with a pitiful script kiddie language is a you problem, not theirs.

Also why the fuck do you care if it's a me problem and not theirs anyway? I like how I'm always the fucking enemy in every conversation. I simply don't like Lua and that makes me the bad guy. People always get to talk shit about other things but when I fucking talk shit about something I get fucking blasted by hate. I always tried to keep calm in any situation but with 2022 getting even worse for me I'm starting to lose it.

**Comment by DragShot** [comment]
> People always get to talk shit about other things but when I fucking talk shit about something I get fucking blasted by hate. I always tried to keep calm in any situation but with 2022 getting even worse for me I'm starting to lose it.

Alright, alright, let's go down a few revolutions here, buddy. Look, there's nothing wrong with disliking a language in particular, but that doesn't mean you can blame others for agreeing to use that one tool you hate; that would be just a waste of effort.

Lua simply works here as the embedded language it is, that's why it is the preferred approach for this kind of stuff, and it doesn't look like the staff running this engine is willing to change their minds about it. So, as a few replies already suggested, all you can do is to implement that feature on your own end via Haxe if you feel more comfortable with that. I wouldn't expect it to be accepted as a pull request however, since other people have tried to add similar extra features before and they have been rejected, so it's best to simply run with your own fork of Psych like plenty of people do, including myself.

**Comment by XS09-dev** [comment]
> > People always get to talk shit about other things but when I fucking talk shit about something I get fucking blasted by hate. I always tried to keep calm in any situation but with 2022 getting even worse for me I'm starting to lose it.
> 
> Alright, alright, let's go down a few revolutions here, buddy. Look, there's nothing wrong with disliking a language in particular, but that doesn't mean you can blame others for agreeing to use that one tool you hate; that would be just a waste of effort.
> 
> Lua simply works here as the embedded language it is, that's why it is the preferred approach for this kind of stuff, and it doesn't look like the staff running this engine is willing to change their minds about it. So, as a few replies already suggested, all you can do is to implement that feature on your own end via Haxe if you feel more comfortable with that. I wouldn't expect it to be accepted as a pull request however, since other people have tried to add similar extra features before and they have been rejected, so it's best to simply run with your own fork of Psych like plenty of people do, including myself.

I already am.
