### ISSUE TITLE
loading screens (again) sorry :(

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#5816]
### Describe your bug here.

So i fixed the 4 errors that the powershell gave me now its giving me this error

source/Cache.hx:1 0 0: characters 3-6 : Unexpected for
![image](https://user-images.githubusercontent.com/56323671/155844645-2f42cba9-e79b-46e2-8988-b9a9c07f6ce0.png)
if you can help please do! 

this is my Cache file 
[Cache.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8146661/Cache.zip)
also im not on 5.1 im on the version with shaders

### Command Prompt/Terminal logs (if existing)

```bash
source/Cache.hx:100: characters 3-6 : Unexpected for
```

had to make the 1 0 0 spaced so it wont be an emoji
### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by frantastic24** [comment]
Why would you label this as a bug

**Comment by machonessiebaby** [comment]
> Why would you label this as a bug

dont know but i fixed it

**Comment by JacksRobotics** [comment]
hey what is the custom build with shaders?

**Comment by machonessiebaby** [comment]
> hey what is the custom build with shaders?

its in psych engine runs
