### ISSUE TITLE
KIll notes into source code?

### ISSUE THREAD

**Issue by ImadriPlays** [ShadowMario/FNF-PsychEngine#5825]
### Describe your problem here.

I want to add a function to custom notes that kills you if you don't press them in the source code instead of mods\custom_notetypes, is there a way to do this?
![vscode](https://user-images.githubusercontent.com/86454963/155852905-0fe72be9-eee5-4a9a-8035-f9f3f1757ed9.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited Note.hx to add a new note but no function

**Comment by KutikiPlayz** [comment]
it's simple, remove the isSustainnote shit, replace that with `missHealth = 2;` and then remove `hitCausesMiss = true;`
and then also you'll wanna put `= true;` after `ignoreNote` if that's what you're trying to do.

**Comment by ImadriPlays** [comment]
> it's simple, remove the isSustainnote shit, replace that with `missHealth = 2;` and then remove `hitCausesMiss = true;` and then also you'll wanna put `= true;` after `ignoreNote` if that's what you're trying to do.

Thanks, that helped a lot
