### ISSUE TITLE
custom fonts per weeks

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#5829]
### Describe your problem here.

So im making an fnf mod with 4 weeks and im planning for week 1 to use Russel square font and week 2 to use pusab font is there anyway to do this? (with or without lua idc what works i really wana do this lel)

### Are you modding a build from source or with Lua?

Source & lua
pref: lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by BombasticTom** [comment]
wdym by different weeks using different fonts? Like score texts?

**Comment by DragShot** [comment]
Don't weeks use .png images to display "Week #" by default? You're free to use whatever fonts are available in your image editor to create them.

**Comment by machonessiebaby** [comment]
> Don't weeks use .png images to display "Week #" by default? You're free to use whatever fonts are available in your image editor to create them.

im talking about like you know what indie cross used or whatever do i have to code it into playstate to display the game with dif fonts?

**Comment by machonessiebaby** [comment]
lets say 
![image](https://user-images.githubusercontent.com/56323671/156073702-a04007ac-e1c8-4f93-9247-e19339797e85.png)
this song uses this font
and the other uses for say Russel square

**Comment by Grape-Boy** [comment]
`setTextFont("scoreTxt", "Russel square.ttf")`

**Comment by machonessiebaby** [comment]
Thanks grape boy it worked!
