### ISSUE TITLE
A Way To Have Your Own Intro Text With Lua (NOT THE LITTLE JOKE MESSAGES, BUT THE PART WHERE IT SAYS THE GAME TITLE SPACED OUT)

### ISSUE THREAD

**Issue by TheRedperson** [ShadowMario/FNF-PsychEngine#5860]
### What feature do you want to get added on the **base** engine?

I would like a feature where you could have your own intro text, (not the ones on introText.txt, but the splash things.)
For Ex:
When It states Psych engine By:
ShadowMario and people
After That It Could Say Something Like
VS. GitHub Team:
some random dude

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
pretty sure shadowmario said no (#1234)

**Comment by TheRedperson** [comment]
oh
