### ISSUE TITLE
playSound timer thing

### ISSUE THREAD

**Issue by WortwL** [ShadowMario/FNF-PsychEngine#5863]
### Describe your problem here.

is there any script that do something after the sound playing is done?

what i mean is if the sound is done it will do something like

nut = false to nut = true

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

didnt

**Comment by frantastic24** [comment]
```lua
function onSoundFinished(tag)
     if tag == 'soundTag' then

     end
end
```

**Comment by WortwL** [comment]
> ```lua
> function onSoundFinished(tag)
>      if tag == 'soundTag' then
> 
>      end
> end
> ```

didnt know that anyways thanks
