### ISSUE TITLE
How do I fixed this?

### ISSUE THREAD

**Issue by JVGamerzbz** [ShadowMario/FNF-PsychEngine#5870]
### Describe your problem here.

Just look at the picture
![Screenshot (102)](https://user-images.githubusercontent.com/94219634/155873955-e3976b83-c923-4b74-aee3-7b245d19c8ce.png)
.

I'm source and lua

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, just need more features.

**Comment by Pico8430** [comment]
Fix the .xml of your spritesheet, that's all.
