### ISSUE TITLE
character animation in dialogue problem

### ISSUE THREAD

**Issue by cocos-yz** [ShadowMario/FNF-PsychEngine#5875]
### Describe your problem here.

I put all character animations in dialogue, but when I change animation, the animation about character is just show "normal" in game, it didn't show "pissed" or "excited".

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by djnbeeman** [comment]
![image](https://user-images.githubusercontent.com/88124585/155903080-6b16f90a-9c2f-4828-806d-bc1c78a74d95.png)
there's this feature in the dialogue portraits editor.
