### ISSUE TITLE
FreePlay songs lock

### ISSUE THREAD

**Issue by An-undertale-fan** [ShadowMario/FNF-PsychEngine#5887]
### What feature do you want to get added on the **base** engine?

Jus add a button in week editor that allows you to lock the song in freePlay

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by An-undertale-fan** [comment]
Plz

**Comment by frantastic24** [comment]
I don't know what you mean by "lock" but you can already lock a week untill you beat another specified week and even hide the locked week from Freeplay/story
You also failed the test, congratulations

**Comment by djnbeeman** [comment]
I think he means like lock the song and if you beat a week you'll unlock the Freeplay song and be able to play it.

**Comment by frantastic24** [comment]
that's literally what i explained lmao

**Comment by Pico8430** [comment]
![theykeepfailingthetest](https://user-images.githubusercontent.com/91833725/155903554-f7267ff9-e0df-46dc-b377-5084fe1b3f64.png)
This again, you failed the test, and you can already hide the songs of a week on freeplay.

**Comment by An-undertale-fan** [comment]
> ![theykeepfailingthetest](https://user-images.githubusercontent.com/91833725/155903554-f7267ff9-e0df-46dc-b377-5084fe1b3f64.png) This again, you failed the test, and you can already hide the songs of a week on freeplay.

Not hide the song in freeplay
I mean if you lock the week in story mod you still access the songs in freeplay
I don't want it i want to lock the songs with the week.

**Comment by An-undertale-fan** [comment]
> I think he means like lock the song and if you beat a week you'll unlock the Freeplay song and be able to play it.

Not hide the song in freeplay
I mean if you lock the week in story mod you still access the songs in freeplay
I don't want it i want to lock the songs with the week.

**Comment by frantastic24** [comment]
That just makes the lock pointless then, there's no use for a feature like this

**Comment by frantastic24** [comment]
And again again, you failed the test so this is getting closed anyways lol
