### ISSUE TITLE
weird freeplay thing

### ISSUE THREAD

**Issue by nintendofan44** [ShadowMario/FNF-PsychEngine#5898]
### Describe your bug here.

freeplay doesn't save your score when the song is played in a custom difficulty

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
It's a known "bug" and it's already planned to be fixed

**Comment by nintendofan44** [comment]
ok then
i'll wait

**Comment by frantastic24** [comment]
Close this then

**Comment by nintendofan44** [comment]
k
