### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by fox-64** [ShadowMario/FNF-PsychEngine#5901]
### Describe your bug here.

in random moments (debug mode, a gameplay etc.) the game crashes pls fix it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i edit nothing

**Comment by frantastic24** [comment]
No

**Comment by fox-64** [comment]
> No
Oh, the problem is fixed, i fix my computer and now is not crashing, sorry for that
