### ISSUE TITLE
dialogue problem

### ISSUE THREAD

**Issue by Lorekeeper49** [ShadowMario/FNF-PsychEngine#5911]
### Describe your bug here.

here's the problem
https://drive.google.com/file/d/1tzVRLRU7jOasaaViz7hi7smHWh8MIgu4/view?usp=sharing

here's what I have in the lua script
local allowCountdown = false
function onStartCountdown()
	-- Block the first countdown and start a timer of 0.8 seconds to play the dialogue
	if not allowCountdown and isStoryMode and not seenCutscene then
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		triggerEvent('startDia')
		startDialogue('dialogue', '');
	end
end

-- Dialogue (When a dialogue is finished, it calls startCountdown again)
function onNextDialogue(count)
	-- triggered when the next dialogue line starts, 'line' starts with 1
end

function onSkipDialogue(count)
	-- triggered when you press Enter and skip a dialogue line that was still being typed, dialogue line starts with 1
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by djnbeeman** [comment]
did you put anything scripts that do something when you load into a song? if you did then remove it.

**Comment by Lorekeeper49** [comment]
https://drive.google.com/file/d/1nooW0qoa7yNOfwUGMHQlKXKUuPGzWXy7/view?usp=sharing
