### ISSUE TITLE
how to make that if you press 7 in song something happens

### ISSUE THREAD

**Issue by bigasschubby** [ShadowMario/FNF-PsychEngine#5912]
### What is your question?

how to make that if you press 7 in song it would crash the game

**Comment by Pico8430** [comment]
![pressedseven](https://user-images.githubusercontent.com/91833725/155903449-9ac05e0e-4ecd-4101-8e23-c38b75e42bb9.png)
This works on a lua script.

**Comment by ytboogy** [comment]
> ![pressedseven](https://user-images.githubusercontent.com/91833725/155903449-9ac05e0e-4ecd-4101-8e23-c38b75e42bb9.png) This works on a lua script.

more detail

**Comment by Shadyyam** [comment]
> > ![pressedseven](https://user-images.githubusercontent.com/91833725/155903449-9ac05e0e-4ecd-4101-8e23-c38b75e42bb9.png) This works on a lua script.
> 
> more detail

when you press 7, song ends. i don't think there's a command to crash built into lua at the moment, unless you want to overload the game or make a script conflict or somethin

**Comment by Grape-Boy** [comment]
> i don't think there's a command to crash built into lua at the moment

There's no function built into Psych Engine LUA to close the game, but I think you can do `os.exit()`, it might work only on Windows, though.

**Comment by randomaccount20** [comment]
@Grape-Boy 

`function onUpdate()
	if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.7') then
             makeAnimatedLuaSprite('crashgame','num0', -1000, -1000) --this crashes the game because theres no xml file with the image 'num0'
	end
end`

**Comment by alvaroxddd** [comment]
to make psych engine crash do os.exit();

**Comment by MemeHoovy** [comment]
> to make psych engine crash do os.exit();

but not on older versions though

**Comment by funniperson1122** [comment]
how do you make it so it crashes then it opens stuff like links, videos, etc.
