### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by fnfbuttomanybugs** [ShadowMario/FNF-PsychEngine#5933]
### Describe your problem here.

when i compile psych engine 0.4.2 this is error code: obj\msvc1964-nc\0c47ba23_FlxUICursor.obj : fatal error LNK1136: invalid or corrupt file      

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no i dont editing files

**Comment by Stilic** [comment]
delete da file inside export/obj and recompile
