### ISSUE TITLE
How to change note skin mid-song?

### ISSUE THREAD

**Issue by NicklGames** [ShadowMario/FNF-PsychEngine#5940]
### Describe your problem here.

What i mean is - song starts with default note skin, but at some point it changes to week 6 note skin?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Spongeyboi** [comment]
Probably hardcoding in playState.hx and notes.hx

**Comment by NicklGames** [comment]
> Probably by hardcoding in playState.hx and notes.hx

can you clarify please?

**Comment by NicklGames** [comment]
lemme actually try something

**Comment by machonessiebaby** [comment]
[noteskinchange.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8157587/noteskinchange.zip)
this should work this has a script for only bf notes and the other player or both
