### ISSUE TITLE
How to replace base game note textures with lua

### ISSUE THREAD

**Issue by djawesomeyt** [ShadowMario/FNF-PsychEngine#5941]
### Describe your problem here.

Alright so, I'm using the glorious GF sings arrow BUT I want to change the texture of those arrows specifically by using some lua magic If that's not possible can someone pass me a custom_arrowtype script that's the equivalent of the GF Sings note.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
It's the same as if you were creating a new one, just name it GF Sings

**Comment by djawesomeyt** [comment]
Oh...
Thanks lol
