### ISSUE TITLE
Position Stage Editor :/ (THIS IS NOT STAGE EDITOR)

### ISSUE THREAD

**Issue by afeefflox** [ShadowMario/FNF-PsychEngine#5946]
### What feature do you want to get added on the **base** engine?

Basically, I really need a position stage because I cannot understand how character position using adobe animate still does don't work same as so idk it will ban this

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by trippinreal** [comment]
Are you referring to changing character positions (bf, dad, and gf)?

**Comment by Spongeyboi** [comment]
Offsets tbh

**Comment by afeefflox** [comment]
> Are you referring to changing character positions (bf, dad, and gf)?
No, it will use positions stage for each Character 
Example:
Stage: Stage
Dad [100, 100]
Boyfriend [770, 100]
Girlfriend [400, 130]

**Comment by frantastic24** [comment]
Look at the stage json

**Comment by facundomax** [comment]
Go to the json of the stage and change the possition of the characters wathever you want
