### ISSUE TITLE
How do i move the menu options?

### ISSUE THREAD

**Issue by jaekyle122** [ShadowMario/FNF-PsychEngine#595]
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Source Code

### Show an screenshot/video of your problem.

![Screenshot 2021-10-24 060924](https://user-images.githubusercontent.com/88638460/138595687-257826c7-3fec-4b92-b61a-498eae833339.png)
how the heck do i move the menu options

**Comment by MeowcaTheoRange** [comment]
Go to `line 91` of `MainMenuState.hx`
```haxe
...0, (i * 140)  +...
```
then change the `140` to whatever you want.
Then go to `line 99`
```haxe
...optionShit.length - 4) * 0.135...
```
and change the `0.135` to your previous number typed, but -5.

Also go to `line 100`
```haxe
...optionShit.length < 6)...
```
and set `6` to `3`.
This should work, except for very long lists, where the current selection will be out of view. Yours only has 3 indexes, so you should be fine.
