### ISSUE TITLE
How can i (Actually) port Kade Engine Chart into Psych Engine Chart?

### ISSUE THREAD

**Issue by issaralengEZ** [ShadowMario/FNF-PsychEngine#5956]
### Describe your problem here.

i was just making some modding port, everything was going good but when i tried to play kade engine chart its just crashed the game, i follow everyting in youtube tutorial but it still didn't work 
help.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Spongeyboi** [comment]
Just copy the chart over. Kade Engine charts and Psych Engine charts are compatible with pretty much every engine out there. psych engine charts can run on kade engine and kade engine charts can run on psych engine.

**Comment by Spongeyboi** [comment]
It's probably not Kade engine charts that's crashing the game. I ported mine over and they worked fine.

**Comment by ImaginationSuperHero528** [comment]
The only thing that I had for an error is that vs imposter charts worked but in the chart editor they broke idk why but normal kade charts from latest version should port fine.
