### ISSUE TITLE
How do I make my screen flip and the opponent drain heath from the player?

### ISSUE THREAD

**Issue by AToska21** [ShadowMario/FNF-PsychEngine#596]
### What is your question?

The title explains it all. Here's some context: I'm working on a mod, and I want to implement these features. I am using the source code and I plan on using LUA, but anything will work. Thank you in advance, - AToska21

**Comment by ShadowMario** [comment]
Yes...

**Comment by ShadowMario** [comment]
Closing this because of no replies (I will assume op figured it out)

**Comment by UnknownSkid** [comment]
> 

can you show this in lua
not in source code
