### ISSUE TITLE
Character editor completly crashing the engine when changing the offset of an animation.

### ISSUE THREAD

**Issue by FloofyWoo** [ShadowMario/FNF-PsychEngine#599]
### Bug report

So at randoms, changing the offset of an animation of a custom character crashes the engine completly for some reason. it's very problematic when i try to fix some offsets and it just crashes, loosing any progress on fixing the offset

https://user-images.githubusercontent.com/52764294/138612333-1d3178b4-bd10-415d-a7dc-cb89481278fa.mp4

### Did you edit anything? If so, mention or summarize your changes.

No, i did not change anything.

**Comment by Owen-sys** [comment]
if it helps, when I tried adding an idle animation to pico-speaker even though he had danceLeft and danceRight already, The moment I tried moving the offset it made the engine crash as well.

**Comment by ShadowMario** [comment]
Is it fixed now?
