### ISSUE TITLE
how to swap the opponent note location and the players

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#5994]
### What is your question?

so i have a song in my mod this song bf and the opponent are swapped sides like this:
![image](https://user-images.githubusercontent.com/56323671/156074316-a656af58-35df-4c3a-a89c-d39422c1e00d.png)
i wana make it so that the players notes and opponent notes are swapped to make it fit better with how bf is on the left instead of right

**Comment by Grape-Boy** [comment]
```lua
function onCreatePost()
	
    local notePositions = {
		defaultPlayerStrumX0,
		defaultPlayerStrumX1,
		defaultPlayerStrumX2,
		defaultPlayerStrumX3,
		defaultOpponentStrumX0,
		defaultOpponentStrumX1,
		defaultOpponentStrumX2,
		defaultOpponentStrumX3,
	}
	
	for i = 0, 3, 1 do
		noteTweenX('noteTween'..i, i, notePositions[i], 1, 'linear')
	end
	
	for i = 4, 7, 1 do
		noteTweenX('noteTween'..i, i, notePositions[i], 1, 'linear')
	end
    
    end
end
```

This should work, but I don't know if it does because my computer doesn't want to execute the code for some reason.

**Comment by Grape-Boy** [comment]
```lua

local notePositions = {}

function onCreatePost()
    notePositions = {
        defaultPlayerStrumX0,
        defaultPlayerStrumX1,
        defaultPlayerStrumX2,
        defaultPlayerStrumX3,
        defaultOpponentStrumX0,
        defaultOpponentStrumX1,
        defaultOpponentStrumX2,
        defaultOpponentStrumX3
    }
    
    for i = 1, 8, 1 do
        noteTweenX('noteTween'..i, i-1, notePositions[i], 0.01, 'sine')
    end
    
end

```

Fixed the code, it should work now.

**Comment by machonessiebaby** [comment]
> ```lua
> local notePositions = {}
> 
> function onCreatePost()
>     notePositions = {
>         defaultPlayerStrumX0,
>         defaultPlayerStrumX1,
>         defaultPlayerStrumX2,
>         defaultPlayerStrumX3,
>         defaultOpponentStrumX0,
>         defaultOpponentStrumX1,
>         defaultOpponentStrumX2,
>         defaultOpponentStrumX3
>     }
>     
>     for i = 1, 8, 1 do
>         noteTweenX('noteTween'..i, i-1, notePositions[i], 0.01, 'linear')
>     end
>     
> end
> ```
> 
> Fixed the code, it should work now.

kay thanks!

**Comment by machonessiebaby** [comment]
> ```lua
> local notePositions = {}
> 
> function onCreatePost()
>     notePositions = {
>         defaultPlayerStrumX0,
>         defaultPlayerStrumX1,
>         defaultPlayerStrumX2,
>         defaultPlayerStrumX3,
>         defaultOpponentStrumX0,
>         defaultOpponentStrumX1,
>         defaultOpponentStrumX2,
>         defaultOpponentStrumX3
>     }
>     
>     for i = 1, 8, 1 do
>         noteTweenX('noteTween'..i, i-1, notePositions[i], 0.01, 'linear')
>     end
>     
> end
> ```

also is it like this? 
![image](https://user-images.githubusercontent.com/56323671/156251551-96568f58-4b43-4dd5-9391-a910b39bc6ad.png)

**Comment by Grape-Boy** [comment]
Yeah it's correct.

**Comment by machonessiebaby** [comment]
> Yeah it's correct.

how do i get it to work properly? it wont swap the notes let me double check tho

**Comment by machonessiebaby** [comment]
it works thank you so much grape boy
