### ISSUE TITLE
3 New Features ? (options)

### ISSUE THREAD

**Issue by NadekoJr** [ShadowMario/FNF-PsychEngine#6]
Hey I just wanna say that I love this engine and I hope it gets more updates and gets better over time, same with The Mind Games Mod (It's a good mod) **OKAY ENOUGH OF ME BEING A FAN GIRL** let's get down to Business. So I was wondering if u can add **Controller support, Moving arrows, and Middle scroll** (if yk what I'm sayin) now let me explain why. 

**One Controller support**, Controller support was added in week 7 on Newgrounds and I loved it because of how comfortable it is and it was a lil challenging. There's some people that play on Controller AND it would be comfortable for people who plays on controller on FNF (just like me). It would be fantastic if there was controller support in this engine. 

**Number 2 moving arrows**, Now uh what do I say. It makes the gameplay more cool. That's all I gotta say CASE CLOSED lol.
 
**Number 3 Middle scroll**, now I believe a lot of rhythm gamers have middle scroll while playing whatever song they are playing plus it feels comfortable and it's a great option to have. (I would use middle scroll a lot if it was added) 

(Side note: Now I know coding is hard because I code too but I'm a newbie at it lol so if u don't know how to add these then it's okay and it's understandable also do you mind making a tutorial on how to add songs in freeplay and How to add Bg's in stages in the folder.)

**Comment by NadekoJr** [comment]
oooooooo LETS GET IT

**Comment by ShadowMario** [comment]
Middlescroll is out, i won't close this until i finish Number 1

**Comment by NadekoJr** [comment]
bet
