### ISSUE TITLE
How to do health drain notes?

### ISSUE THREAD

**Issue by JVGamerzbz** [ShadowMario/FNF-PsychEngine#6018]
### Describe your problem here.

Well I got error. It says 
"source/PlayState.hx:4048: characters 9-13 : Expected }".

The script of my custom note:

                                      case 'Verted Note':	    
					    if noteType == 'Verted Note' then {
						    playSound('BoomCloud')
						    triggerEvent('Play Animation', 'hit', 'bf')
						    healthDrain = healthDrain + 0.6;
						}	    
					
				// Health drains while pressing verted notes
				function onUpdate(elapsed) 
					if healthDrain > 0 then {
						healthDrain = healthDrain - 0.2 * elapsed;
						setProperty('health', getProperty('health') - 0.2 * elapsed);
						if healthDrain < 0 then
							healthDrain = 0;
				        }		

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes

**Comment by KutikiPlayz** [comment]
you can't just simply copy paste lua into source, those are 2 completely different coding languages

**Comment by JVGamerzbz** [comment]
> you can't just simply copy paste lua into source, those are 2 completely different coding languages 
oh ok, so what is example of health drain note in source

**Comment by frantastic24** [comment]
You can take it from sonic.exe

**Comment by KutikiPlayz** [comment]
well there are a couple ways of doing it, there are the poison notes in the retrospecter mod, which are more complex but they stay the same no matter what framerate people use, and there's the phantom note from sonic exe where it's simpler but will fuck people over if their framerate is 240 or anything higher than 60 really (just 2 examples I could come up with)
I'll give you the phantom note for now and if need be I can give you the poison note

assuming you've already added the notetype in note.hx
find the hurt note shit where it detects if you hit the note but if it counts as a miss and just copy paste this shit under it 
make sure it isn't under the actual hurt note case, but like make it on the same level kinda thing
like make sure it's like this
```
case 'Hurt Note':
	bla bla bla
case 'Your Note':
	bla bla bla
```
and not like this
```
case 'Hurt Note':
	bla bla bla
	case 'Your Note':
		bla bla bla
```
so basically you copy-paste this shit under there
```
					case 'Your Note Name':
						var fuckyou:Int = 0;
						healthDrop += 0.00025;
						if (healthDrop == 0.00025)
						{
							new FlxTimer().start(0.1, function(sex:FlxTimer)
							{
								fuckyou += 1;
			
								if (fuckyou >= 100)
									healthDrop = 0;
			
								if (!paused && fuckyou < 100)
									sex.reset();
							});
						}
						else
							fuckyou = 0;
```
and then you wanna add `var healthDrop:Float = 0;` somewhere above function create
then  you wanna find `funtion update` and put this in it
```
		switch (curSong)
		{
			default:
				health -= healthDrop;
		}
```
the switch is basically so that in case you only wanted to make the healthdrain work on a specific song(s) you can add `case 'yoursongname':` and then put `health -= healthDrop;` under it, if you don't care tho you can just put `health -= healthDrop;` alone in function update

I think that should be it
lmk if it works or not

**Comment by JVGamerzbz** [comment]
> You can take it from sonic.exe

well thats kade engine...

**Comment by JVGamerzbz** [comment]
> well there are a couple ways of doing it, there are the poison notes in the retrospecter mod, which are more complex but they stay the same no matter what framerate people use, and there's the phantom note from sonic exe where it's simpler but will fuck people over if their framerate is 240 or anything higher than 60 really (just 2 examples I could come up with)
> I'll give you the phantom note for now and if need be I can give you the poison note
> 
> assuming you've already added the notetype in note.hx
> find the hurt note shit where it detects if you hit the note but if it counts as a miss and just copy paste this shit under it 
> make sure it isn't under the actual hurt note case, but like make it on the same level kinda thing
> like make sure it's like this
> ```
> case 'Hurt Note':
> 	bla bla bla
> case 'Your Note':
> 	bla bla bla
> ```
> and not like this
> ```
> case 'Hurt Note':
> 	bla bla bla
> 	case 'Your Note':
> 		bla bla bla
> ```
> so basically you copy-paste this shit under there
> ```
> 					case 'Your Note Name':
> 						var fuckyou:Int = 0;
> 						healthDrop += 0.00025;
> 						if (healthDrop == 0.00025)
> 						{
> 							new FlxTimer().start(0.1, function(sex:FlxTimer)
> 							{
> 								fuckyou += 1;
> 			
> 								if (fuckyou >= 100)
> 									healthDrop = 0;
> 			
> 								if (!paused && fuckyou < 100)
> 									sex.reset();
> 							});
> 						}
> 						else
> 							fuckyou = 0;
> ```
> and then you wanna add `var healthDrop:Float = 0;` somewhere above function create
> then  you wanna find `funtion update` and put this in it
> ```
> 		switch (curSong)
> 		{
> 			default:
> 				health -= healthDrop;
> 		}
> ```
> the switch is basically so that in case you only wanted to make the healthdrain work on a specific song(s) you can add `case 'yoursongname':` and then put `health -= healthDrop;` under it, if you don't care tho you can just put `health -= healthDrop;` alone in function update
> 
> I think that should be it
> lmk if it works or not

Wow thanks for example! I'll try tommorow. (UTC +8)

**Comment by KutikiPlayz** [comment]
> Wow thanks for example! I'll try tommorow (UTC +8). But how do I add sound like Bob Notes (Verted Notes)?

you just put `FlxG.sound.play(Paths.sound('soundfilename'));` under the case with your note name

**Comment by JVGamerzbz** [comment]
when i compile it says this:

source/PlayState.hx:4050: characters 9-13 : Expected }

**Comment by JVGamerzbz** [comment]
> well there are a couple ways of doing it, there are the poison notes in the retrospecter mod, which are more complex but they stay the same no matter what framerate people use, and there's the phantom note from sonic exe where it's simpler but will fuck people over if their framerate is 240 or anything higher than 60 really (just 2 examples I could come up with) I'll give you the phantom note for now and if need be I can give you the poison note
> 
> assuming you've already added the notetype in note.hx and/or chartingstate.hx find the hurt note shit where it detects if you hit the note but if it counts as a miss and just copy paste this shit under it make sure it isn't under the actual hurt note case, but like make it on the same level kinda thing like make sure it's like this
> 
> ```
> case 'Hurt Note':
> 	bla bla bla
> case 'Your Note':
> 	bla bla bla
> ```
> 
> and not like this
> 
> ```
> case 'Hurt Note':
> 	bla bla bla
> 	case 'Your Note':
> 		bla bla bla
> ```
> 
> so basically you copy-paste this shit under there
> 
> ```
> 					case 'Your Note Name':
> 						var fuckyou:Int = 0;
> 						healthDrop += 0.00025;
> 						if (healthDrop == 0.00025)
> 						{
> 							new FlxTimer().start(0.1, function(sex:FlxTimer)
> 							{
> 								fuckyou += 1;
> 			
> 								if (fuckyou >= 100)
> 									healthDrop = 0;
> 			
> 								if (!paused && fuckyou < 100)
> 									sex.reset();
> 							});
> 						}
> 						else
> 							fuckyou = 0;
> ```
> 
> and then you wanna add `var healthDrop:Float = 0;` somewhere above function create then you wanna find `funtion update` and put this in it
> 
> ```
> 		switch (curSong)
> 		{
> 			default:
> 				health -= healthDrop;
> 		}
> ```
> 
> the switch is basically so that in case you only wanted to make the healthdrain work on a specific song(s) you can add `case 'yoursongname':` and then put `health -= healthDrop;` under it, if you don't care tho you can just put `health -= healthDrop;` alone in function update
> 
> I think that should be it lmk if it works or not

when i compile it says this:

source/PlayState.hx:4050: characters 9-13 : Expected }
