### ISSUE TITLE
HTML5 building errors.

### ISSUE THREAD

**Issue by NovaDev-8376** [ShadowMario/FNF-PsychEngine#6024]
### Describe your bug here.

I get the following errors in logs when compiling to HTML5

If this isn't bug and I messed up the source or something, sorry. :)

### Command Prompt/Terminal logs (if existing)

```bash
>lime test html5
source/WeekData.hx:11: characters 8-19 : You cannot access the sys package while targeting js (for sys.io.File)
source/editors/WeekEditorState.hx:34: characters 8-16 : ... referenced here
source/editors/MasterEditorMenu.hx:119: characters 37-52 : ... referenced here
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Grape-Boy** [comment]
Try removing `import sys.io.File;` from `source/WeekData` at line 11.

**Comment by NovaDev-8376** [comment]
> Try removing `import sys.io.File;` from `source/WeekData` at line 11.

It does remove the sys.io error! However, it still leaves the 2 other ones.

**Comment by NovaDev-8376** [comment]
> Try removing `import sys.io.File;` from `source/WeekData` at line 11.

I just figured out I wasn't saving any changes. This simply fixes it, thanks!

**Comment by jbmagination** [comment]
Here's some guidance to fix some extra stuff, such as song freezing: https://github.com/Starmapo/FNF-PsychEngine-Extra/issues/11#issuecomment-1093299756
