### ISSUE TITLE
Stage Name

### ISSUE THREAD

**Issue by Grape-Boy** [ShadowMario/FNF-PsychEngine#6032]
### Describe your problem here.

I tried to get the stage's name but I don't know how, I've tried this:
```lua
debugPrint(getProperty('curStage'))

debugPrint(getProperty('SONG.stage'))

debugPrint(getPropertyFromClass('SONG', 'stage'))
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by BombasticTom** [comment]
debugPrint outputs info to the console, you would need to use Source Code to do this i think

**Comment by Grape-Boy** [comment]
#6100 😁
