### ISSUE TITLE
Hurt Note Hitboxes

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#6053]
### What feature do you want to get added on the **base** engine?

Is it possible, to maybe either prefer regular notes a bit more, over notes, that harm the player? Or just reduce the hitbox/ hit time of them?
It would be a bit more friendly towards the player

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
Unfortunately I think this is a no #2014

**Comment by ShadowMario** [comment]
Done
