### ISSUE TITLE
I can't seem to get the startVideo function to work

### ISSUE THREAD

**Issue by Idunno1** [ShadowMario/FNF-PsychEngine#607]
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Source Code

### Show an screenshot/video of your problem.

I downloaded the example script for playing a video, made no alterations to it, and placed it in the correct directories. `script.lua` is in `assets/preload/data/bopeebo`, and `testVideo` is in `assets/videos`. The script loads, but it hangs when the video tries to load, before the countdown. I genuinely don't know what I'm doing wrong.

![image](https://user-images.githubusercontent.com/8219159/138634273-75a6bcfa-5136-4741-bf64-42d05a80b215.png)
![image](https://user-images.githubusercontent.com/8219159/138634302-428279b7-3737-4ac0-bdd2-e376c48c7ac9.png)
![image](https://user-images.githubusercontent.com/8219159/138634368-90baca47-e935-4f39-9d70-733d370ad3eb.png)

**Comment by ShadowMario** [comment]
Yes, but did you compile it to x32 or x64???

**Comment by ShadowMario** [comment]
No reply, i will assume op figured it out.
