### ISSUE TITLE
Custom GF graphics become a black box or crash to desktop and picking Restart Song also causes a crash to desktop

### ISSUE THREAD

**Issue by JtheDuelist** [ShadowMario/FNF-PsychEngine#6072]
### Describe your bug here.

When using the build that is current as of me typing this (0.5.1), when changing the GF's graphics and XML files in "mods/images/characters" and then picking a song, she will spawn as a black box in the game, but if you exit back to the menu and pick another song, the game will just crash to desktop after a split second of freezing and saying "(Not Responding)". Also, when choosing "Restart Song" from the pause menu of a song, the game just immediately crashes to desktop of a little bit of the freezing mentioned previously.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only made a custom GF graphic and xml that were placed into "mods/images/characters"- nothing else was modified.

**Comment by frantastic24** [comment]
Show the character files before reporting, this sounds like a PC issue anyways

**Comment by frantastic24** [comment]
Again
Show the files

**Comment by Grape-Boy** [comment]
> she will spawn as a black

I'm pretty sure that like frantastic said, this is an issue with your PC, the game probably needs more allocated RAM.
Happens to me too sometimes.
