### ISSUE TITLE
WHY DIS ALYWAYS COMING

### ISSUE THREAD

**Issue by fnfbuttomanybugs** [ShadowMario/FNF-PsychEngine#6073]
### Describe your bug here.

when i done compile 0.5.1 i see da fps counter is big and a memory on da top, after i in why their is add -git overther this da name version : "Pysch Engine 0.5.1-git" 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i dont editing files

**Comment by Grape-Boy** [comment]
You can disable it in the options. You can close this issue too, now.
