### ISSUE TITLE
GUYS HELP ME I CANT MODDING

### ISSUE THREAD

**Issue by GhazYT** [ShadowMario/FNF-PsychEngine#6074]
### Describe your bug here.

every time i open the freeplay, a message comes, invalid char 93 at position 96

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i just add some event

**Comment by frantastic24** [comment]
this isn't a bug, one of your files is wrong

**Comment by mayo78** [comment]
> Do you have any scripts in your mods folder?
> 
> The error is stating that your have an error on your script. Could you share the code please?

lua files cant run in menus, its an issue with one of the week files

**Comment by PoleyMagik** [comment]
Did you by chance put quotes in your week json anywhere?

**Comment by cyn-8** [comment]
misconfigured json file
theres an extra `]` somewhere
