### ISSUE TITLE
How do I make a modchart start at a specific point in a song

### ISSUE THREAD

**Issue by FartMaster57** [ShadowMario/FNF-PsychEngine#6110]
### Describe your problem here.

I want to make the arrows move for the rest of a song after the beat drops but I can't figure out what function makes it start at a specific point 
Here's my code:
`function onUpdate(elapsed)
songPos = getSongPosition()
local currentBeat = (songPos/5000)*(curBpm/60)
noteTweenY('defaultOpponentStrumY0', 0, defaultOpponentStrumY0 - 50*math.sin((currentBeat+0*0.15)*math.pi), 0.2)
noteTweenY('defaultOpponentStrumY1', 1, defaultOpponentStrumY1 - 50*math.sin((currentBeat+1*0.15)*math.pi), 0.2)
noteTweenY('defaultOpponentStrumY2', 2, defaultOpponentStrumY2 - 50*math.sin((currentBeat+2*0.15)*math.pi), 0.2)
noteTweenY('defaultOpponentStrumY3', 3, defaultOpponentStrumY3 - 50*math.sin((currentBeat+3*0.15)*math.pi), 0.2)
noteTweenY('defaultPlayerStrumY0', 4, defaultPlayerStrumY0 - 50*math.sin((currentBeat+4*0.15)*math.pi), 0.2)
noteTweenY('defaultPlayerStrumY1', 5, defaultPlayerStrumY1 - 50*math.sin((currentBeat+5*0.15)*math.pi), 0.2)
noteTweenY('defaultPlayerStrumY2', 6, defaultPlayerStrumY2 - 50*math.sin((currentBeat+6*0.15)*math.pi), 0.2)
noteTweenY('defaultPlayerStrumY3', 7, defaultPlayerStrumY3 - 50*math.sin((currentBeat+7*0.15)*math.pi), 0.2)
noteTweenX('defaultOpponentStrumX0', 0, defaultOpponentStrumX0 - 50*math.sin((currentBeat+0*0.25)*math.pi), 0.2)
noteTweenX('defaultOpponentStrumX1', 1, defaultOpponentStrumX1 - 50*math.sin((currentBeat+1*0.25)*math.pi), 0.2)
noteTweenX('defaultOpponentStrumX2', 2, defaultOpponentStrumX2 - 50*math.sin((currentBeat+2*0.25)*math.pi), 0.2)
noteTweenX('defaultOpponentStrumX3', 3, defaultOpponentStrumX3 - 50*math.sin((currentBeat+3*0.25)*math.pi), 0.2)
noteTweenX('defaultPlayerStrumX0', 4, defaultPlayerStrumX0 - 50*math.sin((currentBeat+4*0.25)*math.pi), 0.2)
noteTweenX('defaultPlayerStrumX1', 5, defaultPlayerStrumX1 - 50*math.sin((currentBeat+5*0.25)*math.pi), 0.2)
noteTweenX('defaultPlayerStrumX2', 6, defaultPlayerStrumX2 - 50*math.sin((currentBeat+6*0.25)*math.pi), 0.2)
noteTweenX('defaultPlayerStrumX3', 7, defaultPlayerStrumX3 - 50*math.sin((currentBeat+7*0.25)*math.pi), 0.2)
end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
`if curStep == step then` or `if curBeat == beat then`

**Comment by Reycko** [comment]
> `if curStep == step then` or `if curBeat == beat then`

hes right, close this issue

**Comment by FartMaster57** [comment]
Nevermind I think I got it working

**Comment by FartMaster57** [comment]
It was not actually fixed it still only tweens once

**Comment by frantastic24** [comment]
nah it works fine

**Comment by FartMaster57** [comment]
I should’ve clarified too that this isn’t like a full song modchart, it’s just a script that makes the arrows float in a wave pattern.
Before I put the “if curStep ==“ it played for the whole song. And now it doesn’t.

**Comment by frantastic24** [comment]
because you're telling it to only play in one step

**Comment by FartMaster57** [comment]
So how do I tell it to play from step 100 onwards and not just step 100

**Comment by frantastic24** [comment]
>=

**Comment by FartMaster57** [comment]
Thanks
