### ISSUE TITLE
Custom note health gain

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#6113]
### Describe your problem here.

How do I have a custom note gain more health than a regular note. my code wont work it keeps giving me an error saying the plus shouldnt be there
```
function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'Knife Note' then
		setProperty('health', + 3);
	end
end
```

ill post the whole code if you want me to

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I just added new characters and Notes and changed some sprites and a few lua files

**Comment by Reycko** [comment]
"+ 3" isn't a number.
here is how to fix
function goodNoteHit(id, noteData, noteType, isSustainNote)
```
	if noteType == 'Knife Note' then
                local health = getHealth()
		setProperty('health', health + 0.5) -- (1 = half health)
	end
end
```

**Comment by SonicXFire1987** [comment]
THANK YOU IT WORKED!!
