### ISSUE TITLE
School and SchoolEvil 

### ISSUE THREAD

**Issue by SeriouslyAnimations** [ShadowMario/FNF-PsychEngine#6120]
### Describe your problem here.

I need a carbon copy or something of the school and schoolEvil please, i have been struggling to find one. I did find one but i want one that is exact or close to it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

stage assets for school and schoolEvil

**Comment by ShadowMarioFake** [comment]
This is in Spanish but I hope it helps you :)

https://youtu.be/LAY2j4QJKII

Ñ(yes i'm a troll)

**Comment by SeriouslyAnimations** [comment]
i just need a copy of week 6 damn

**Comment by cyn-8** [comment]
you dont need copies of hardcoded stages since you can just use their playstate variables
