### ISSUE TITLE
help me with a background

### ISSUE THREAD

**Issue by ShadowMarioFake** [ShadowMario/FNF-PsychEngine#6123]
### Describe your problem here.

Does anyone know how to make bf go through a stage object but the opponent and gf don't, help me

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ManMaster707** [comment]
What do you mean by "bf going trough a stage object"? because I think I have a solution

**Comment by ShadowMarioFake** [comment]
> What do you mean by "bf going trough a stage object"? because I think I have a solution

If something like that means that bf passes through a specific object of the bg and the others do not

**Comment by main-thing** [comment]
The easiest way is to make a fake bf. Unless if you wanna make the other characters fake
