### ISSUE TITLE
i have 3 lua questions

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#6126]
### Describe your problem here.

I have 3 questions about lua and how to do some things

1: How do i make the notes move around in lua
2: how do i make ghost tapping disable on a song
3: how do i tween move the window

if you can help me Please tell me i wana do this cool thing for an experiment

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by Blaze248570** [comment]
1: Use `noteTweenX(tag:String, note:Int, value:Dynamic, duration:Float, ease:String)` or 
`noteTweenY(tag:String, note:Int, value:Dynamic, duration:Float, ease:String)`

2: Use `setPropertyFromClass('ClientPrefs', 'ghostTapping', false);`

3: Use `setPropertyFromClass('openfl.Lib','application.window.x', --[[Whatever value]]);` or
`setPropertyFromClass('openfl.Lib','application.window.y', --[[Whatever value]]);`

**Comment by machonessiebaby** [comment]
> setPropertyFromClass('openfl.Lib','application.window.x', --[[Whatever value]]);

hey uh i added the window move but im getting 
![image](https://user-images.githubusercontent.com/56323671/156653316-d1e88c22-33e6-4c51-8c9f-102b7f78ec7d.png)
 this error

**Comment by Blaze248570** [comment]
Can you show me the code you used?

**Comment by machonessiebaby** [comment]
is it like this or did i do a stupid 
![image](https://user-images.githubusercontent.com/56323671/156653449-0f45a692-32e3-4b2c-8066-0ac8210fd811.png)

**Comment by machonessiebaby** [comment]
> Can you show me the code you used?

let me send the lua file code rq

**Comment by machonessiebaby** [comment]
`local xx = 520;
local yy = 450;
local xx2 = 820;
local yy2 = 450;
local ofs = 60;
local followchars = true;
local del = 0;
local del2 = 0;

local notePositions = {}

function onCreatePost()
    notePositions = {
        defaultPlayerStrumX0,
        defaultPlayerStrumX1,
        defaultPlayerStrumX2,
        defaultPlayerStrumX3,
        defaultOpponentStrumX0,
        defaultOpponentStrumX1,
        defaultOpponentStrumX2,
        defaultOpponentStrumX3
    }
    
    for i = 1, 8, 1 do
        noteTweenX('noteTween'..i, i-1, notePositions[i], 100, 'linear')
    end
    
end



function onCreate()
	setPropertyFromClass('ClientPrefs', 'middleScroll', true);
	setPropertyFromClass('ClientPrefs', 'ghosttapping', false);

	setPropertyFromClass('openfl.Lib','application.window.x', --[[Whatever value]]);
	setPropertyFromClass('openfl.Lib','application.window.y', --[[Whatever value]]);
end

function onUpdatePost()


if middlescroll and not inGameOver then
	setPropertyFromGroup('opponentStrums',0,'alpha',0)
	setPropertyFromGroup('opponentStrums',1,'alpha',0)
	setPropertyFromGroup('opponentStrums',2,'alpha',0)
	setPropertyFromGroup('opponentStrums',3,'alpha',0)
end


end

function onUpdate()
	if del > 0 then
		del = del - 1
	end
	if del2 > 0 then
		del2 = del2 - 1
	end
    if followchars == true then
        if mustHitSection == false then
            if getProperty('dad.animation.curAnim.name') == 'singLEFT' then
                triggerEvent('Camera Follow Pos',xx-ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singRIGHT' then
                triggerEvent('Camera Follow Pos',xx+ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singUP' then
                triggerEvent('Camera Follow Pos',xx,yy-ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singDOWN' then
                triggerEvent('Camera Follow Pos',xx,yy+ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singLEFT-alt' then
                triggerEvent('Camera Follow Pos',xx-ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singRIGHT-alt' then
                triggerEvent('Camera Follow Pos',xx+ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singUP-alt' then
                triggerEvent('Camera Follow Pos',xx,yy-ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singDOWN-alt' then
                triggerEvent('Camera Follow Pos',xx,yy+ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'idle-alt' then
                triggerEvent('Camera Follow Pos',xx,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'idle' then
                triggerEvent('Camera Follow Pos',xx,yy)
            end
        else

            if getProperty('boyfriend.animation.curAnim.name') == 'singLEFT' then
                triggerEvent('Camera Follow Pos',xx2-ofs,yy2)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT' then
                triggerEvent('Camera Follow Pos',xx2+ofs,yy2)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singUP' then
                triggerEvent('Camera Follow Pos',xx2,yy2-ofs)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN' then
                triggerEvent('Camera Follow Pos',xx2,yy2+ofs)
            end
	    if getProperty('boyfriend.animation.curAnim.name') == 'idle' then
                triggerEvent('Camera Follow Pos',xx2,yy2)
            end
        end
    else
        triggerEvent('Camera Follow Pos','','')
    end
    
end
function opponentNoteHit()
    health = getProperty('health')
    if getProperty('health') > 0.4 then
        setProperty('health', health- 0.017);
    end
end`

**Comment by machonessiebaby** [comment]
local xx = 520;
local yy = 450;
local xx2 = 820;
local yy2 = 450;
local ofs = 60;
local followchars = true;
local del = 0;
local del2 = 0;

local notePositions = {}

function onCreatePost()
    notePositions = {
        defaultPlayerStrumX0,
        defaultPlayerStrumX1,
        defaultPlayerStrumX2,
        defaultPlayerStrumX3,
        defaultOpponentStrumX0,
        defaultOpponentStrumX1,
        defaultOpponentStrumX2,
        defaultOpponentStrumX3
    }
    
    for i = 1, 8, 1 do
        noteTweenX('noteTween'..i, i-1, notePositions[i], 100, 'linear')
    end
    
end



function onCreate()
	setPropertyFromClass('ClientPrefs', 'middleScroll', true);
	setPropertyFromClass('ClientPrefs', 'ghosttapping', false);

	setPropertyFromClass('openfl.Lib','application.window.x', --[[Whatever value]]);
	setPropertyFromClass('openfl.Lib','application.window.y', --[[Whatever value]]);
end

function onUpdatePost()


if middlescroll and not inGameOver then
	setPropertyFromGroup('opponentStrums',0,'alpha',0)
	setPropertyFromGroup('opponentStrums',1,'alpha',0)
	setPropertyFromGroup('opponentStrums',2,'alpha',0)
	setPropertyFromGroup('opponentStrums',3,'alpha',0)
end


end

function onUpdate()
	if del > 0 then
		del = del - 1
	end
	if del2 > 0 then
		del2 = del2 - 1
	end
    if followchars == true then
        if mustHitSection == false then
            if getProperty('dad.animation.curAnim.name') == 'singLEFT' then
                triggerEvent('Camera Follow Pos',xx-ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singRIGHT' then
                triggerEvent('Camera Follow Pos',xx+ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singUP' then
                triggerEvent('Camera Follow Pos',xx,yy-ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singDOWN' then
                triggerEvent('Camera Follow Pos',xx,yy+ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singLEFT-alt' then
                triggerEvent('Camera Follow Pos',xx-ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singRIGHT-alt' then
                triggerEvent('Camera Follow Pos',xx+ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singUP-alt' then
                triggerEvent('Camera Follow Pos',xx,yy-ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singDOWN-alt' then
                triggerEvent('Camera Follow Pos',xx,yy+ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'idle-alt' then
                triggerEvent('Camera Follow Pos',xx,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'idle' then
                triggerEvent('Camera Follow Pos',xx,yy)
            end
        else

            if getProperty('boyfriend.animation.curAnim.name') == 'singLEFT' then
                triggerEvent('Camera Follow Pos',xx2-ofs,yy2)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT' then
                triggerEvent('Camera Follow Pos',xx2+ofs,yy2)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singUP' then
                triggerEvent('Camera Follow Pos',xx2,yy2-ofs)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN' then
                triggerEvent('Camera Follow Pos',xx2,yy2+ofs)
            end
	    if getProperty('boyfriend.animation.curAnim.name') == 'idle' then
                triggerEvent('Camera Follow Pos',xx2,yy2)
            end
        end
    else
        triggerEvent('Camera Follow Pos','','')
    end
    
end
function opponentNoteHit()
    health = getProperty('health')
    if getProperty('health') > 0.4 then
        setProperty('health', health- 0.017);
    end
end

**Comment by machonessiebaby** [comment]
wait i think i know what to do

**Comment by frantastic24** [comment]
You're supposed to type in your values in `--[[Whatever value]]` bruh

**Comment by Blaze248570** [comment]
Yeah

**Comment by machonessiebaby** [comment]
> You're supposed to type in your values in `--[[Whatever value]]` bruh

ah ok

**Comment by machonessiebaby** [comment]
i fixed it but its now saying line 35 error

**Comment by Blaze248570** [comment]
It’s not a comment anymore, right?

It’s just a number?

**Comment by frantastic24** [comment]
Kinda hard to tell which line is 35 with a screenshot and a messed up code block

**Comment by Blaze248570** [comment]
Indeed

**Comment by machonessiebaby** [comment]
> Kinda hard to tell which line is 35 with a screenshot and a messed up code block

here so 
![image](https://user-images.githubusercontent.com/56323671/156654688-bd735bf1-b6a7-4108-887f-371d9c75d6e0.png)
i made it only 4 lines and the error was line 4
![image](https://user-images.githubusercontent.com/56323671/156654728-b306735b-96e7-41be-916b-3382531c2449.png)

**Comment by frantastic24** [comment]
It's supposed to just be the numbers

**Comment by Blaze248570** [comment]
That’s still a comment

**Comment by machonessiebaby** [comment]
> 

so uncomment it?

**Comment by Blaze248570** [comment]
Take off the hyphens and brackets

**Comment by machonessiebaby** [comment]
> Take off the hyphens and brackets

ok

**Comment by machonessiebaby** [comment]
> Take off the hyphens and brackets

ok so it moves but how would you make it smoothly move?

**Comment by frantastic24** [comment]
Start reading the Lua script examples from the wiki to understand basic Lua syntax

**Comment by machonessiebaby** [comment]
otherwise ill just use what you gave lol

**Comment by machonessiebaby** [comment]
ok

**Comment by frantastic24** [comment]
You'll need an entirely different and way more complex script to make it move smoothly, pretty sure it's in discussions

**Comment by machonessiebaby** [comment]
> You'll need an entirely different and way more complex script to make it move smoothly, pretty sure it's in discussions

k
