### ISSUE TITLE
help with the "os" in lua

### ISSUE THREAD

**Issue by Murilo3127** [ShadowMario/FNF-PsychEngine#6130]
### Describe your problem here.

I made a note, that when you press it, it executes a Gif, but the code didn't work (a photo)
![Screenshot_20220302-211730](https://user-images.githubusercontent.com/97374126/156472057-a40ea584-fc81-46b1-a2c2-eb8386b517e5.png)
I use cell phone and I'm really bad at lua

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
execute runs a command line, not a file directly

**Comment by Murilo3127** [comment]
> execute executa uma linha de comando, não um arquivo diretamente

in the Sonic cyclops mod, it executes a Gif at a time of the song using "os.execute", but if not, how do I do it?

**Comment by frantastic24** [comment]
Look up how to use the command line idk

**Comment by Murilo3127** [comment]
> Procure como usar a linha de comando idk

good it helps me a lot

**Comment by frantastic24** [comment]
true, always helps to learn

**Comment by kingyomoma** [comment]
It might be because of the special character (the á) in the folder name
Try changing it?

**Comment by mayo78** [comment]
you used it correctly, its just that you're on android
