### ISSUE TITLE
Event Stuff

### ISSUE THREAD

**Issue by SeriouslyAnimations** [ShadowMario/FNF-PsychEngine#6132]
### What is your question?

Where is the event data in the source?

**Comment by SeriouslyAnimations** [comment]
found it

**Comment by frantastic24** [comment]
PlayState for the actual code, ChartingState for chart editor descriptions

**Comment by SeriouslyAnimations** [comment]
which line

**Comment by frantastic24** [comment]
You can just look up one of their names and you should find them
