### ISSUE TITLE
logo bumpin

### ISSUE THREAD

**Issue by poopkit** [ShadowMario/FNF-PsychEngine#6137]
### Describe your bug here.

so when i started the game it came up like this
![Capture](https://user-images.githubusercontent.com/100816386/156482228-4de1c65c-c713-4383-9e1a-1d843c25cf5c.PNG)
 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

noo

**Comment by Pico8430** [comment]
Edit the `gfDanceTitle.json` file to fix the logo, this happens when a custom logoBumpin is added.

**Comment by ManMaster707** [comment]
First, go to 'assets/images' and find the file he mentioned, open it and you'll see this:

{	
	"titlex":-150, -- the horizontal position of the logo
	"titley":-100, -- the vertical position of the logo
	"startx":100, -- the horizontal position of the 'Press Enter to Begin' text
	"starty":576, -- the vertical position of the 'Press Enter to Begin' text
	"gfx":512, -- the horizontal position of girlfriend
	"gfy":40, -- the vertical position of girlfriend
	"backgroundSprite":"", -- the .png you want to put as background instead of the black
	"bpm":102 -- the speed you want gf and the logo to bop, if you put a custom song 
}
