### ISSUE TITLE
3rd and 6th notes in chart editor

### ISSUE THREAD

**Issue by Shammal** [ShadowMario/FNF-PsychEngine#6142]
### What feature do you want to get added on the **base** engine?

I'd like to be able to chart in a swing rhythm without using shift to place notes or making the bpm weird.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by i-winxd** [comment]
As of right now, consider using external charters like SNIFF, Arrowvortex, or FPSPlus until this is implemented.
