### ISSUE TITLE
how to fix dis

### ISSUE THREAD

**Issue by fnfbuttomanybugs** [ShadowMario/FNF-PsychEngine#6156]
### Describe your problem here.

idk but when i compile psych engine dis is coming "source/Song.hx:65: characters 27-41 : Array access is not allowed on {+ length : Int }"

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no , i was start compile it

**Comment by KutikiPlayz** [comment]
update haxe
