### ISSUE TITLE
Menu Editor

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#6165]
### What feature do you want to get added on the **base** engine?

A Menu Editor would be good! We should be able to add whatever sprites we want for an animation depending on what is selected. we should be able to make a new tab and edit what it does and/or where it goes. changing the background doesn't matter we can just replace the background by adding a new background image. as long as its named to what it needs to be. we should be able to change where the menu tabs go on screen (Right, left, middle). We should change the week menu and the freeplay menu to how we want it to look. that can be decided by you guys. i just think this would be a useful feature to those who cant code and don't know how to use the source code or have a horrible pc. it would also make mod making easier and would can really help polish people's mods! Tell me what you think! @ShadowMario 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by Pico8430** [comment]
![stopfailingthetest](https://user-images.githubusercontent.com/91833725/156568595-14254444-6b25-4549-a595-3c1f880f32f4.png)

Why are people keep failing an easy test.

**Comment by frantastic24** [comment]
This is a duplicate, and you failed the test, and shadowmario already said there's no plans for it

**Comment by kingyomoma** [comment]
![image](https://user-images.githubusercontent.com/96543290/156611999-a88c1ad8-d91b-41a1-bfe6-d608e5095269.png)

**Comment by SonicXFire1987** [comment]
My bad I didn't see that. I guess I'm just an idiot lol
