### ISSUE TITLE
help

### ISSUE THREAD

**Issue by bigasschubby** [ShadowMario/FNF-PsychEngine#6166]
### Describe your problem here.

how do i fix that if i miss an single note i die

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Disable gameplay changers

**Comment by bigasschubby** [comment]
> Disable gameplay changers

but how

**Comment by frantastic24** [comment]
Press control in Freeplay/story mode menu

**Comment by bigasschubby** [comment]
> Press control in Freeplay/story mode menu

oh thanks

**Comment by frantastic24** [comment]
You can close this now
