### ISSUE TITLE
Wrong Things, not Missing Things on wiki

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#6170]
### What needs to be documented?

The getProperty in the Lua Script Variables and a lot of other stuff uses getPropertyClass, not getPropertyFromClass. This may confuse newer psych engine lua users who decided to use the getProperty thing. (which may not be a lot but who cares)

**Comment by frantastic24** [comment]
If one doesn't work, you try the other, simple

**Comment by ShadowMario** [comment]
Fixed
