### ISSUE TITLE
Ok, so the source is TOTTALY broken

### ISSUE THREAD

**Issue by Theoyeah** [ShadowMario/FNF-PsychEngine#6178]
### Describe your bug here.

Im making a mod with the lastest code, but something is wrong:
1. Where The freaky code for Weeks_nomiss in playstate, there not there anymore
2. When finishing the week 1, it will softloks the game by unlocking the week7 achivement for infinity !

@ShadowMario plz fix da game or tell what to do

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not even

**Comment by BeansCool54** [comment]
I think you should use the released build?

**Comment by Theoyeah** [comment]
Nan, because it misses many things, so it is boring

**Comment by DragShot** [comment]
> Nan, because it misses many things, so it is boring

It's boring, but it's stable. It is what is meant to be used in mods until the next version is released. So you either fix the broken mess from the code snapshot yourself or stick with the stable build.
