### ISSUE TITLE
Object Draining Health

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#6180]
### Describe your problem here.

Can I have an event code for a health draining event, I want a scythe hooking onto the health bar and pull on it kinda like the Tricky mod in expurgation. if anyone can do that, it would really help. and Ill be sure to credit you in my mod. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Ive added sprites, removed the weeks to create my own, and added a bunch of lua files such as scripts and custom notes, that's pretty much all I did

**Comment by fnfbuttomanybugs** [comment]
put da .lua file and use this code : function opponentNoteHit()
    health = getProperty('health')
    if getProperty('health') > 0.1 then
        setProperty('health', health- 0.02);
    end
end

**Comment by fnfbuttomanybugs** [comment]
> put da .lua file and use this code : function opponentNoteHit() health = getProperty('health') if getProperty('health') > 0.1 then setProperty('health', health- 0.02); end end

make sure u put psych engine 0.5.1

**Comment by fnfbuttomanybugs** [comment]
> put da .lua file and use this code : function opponentNoteHit() health = getProperty('health') if getProperty('health') > 0.1 then setProperty('health', health- 0.02); end end

function opponentNoteHit()
    health = getProperty('health')
    if getProperty('health') > 0.1 then
        setProperty('health', health- 0.1);
    end
end

**Comment by fnfbuttomanybugs** [comment]
> put da .lua file and use this code : function opponentNoteHit() health = getProperty('health') if getProperty('health') > 0.1 then setProperty('health', health- 0.02); end end

or use this  link to copy into .lua file : https://pastebin.com/0wWmhMeR

**Comment by acap09** [comment]
> put da .lua file and use this code : function opponentNoteHit() health = getProperty('health') if getProperty('health') > 0.1 then setProperty('health', health- 0.02); end end

that doesnt put the scythe

**Comment by acap09** [comment]
here is probably the better code (btw this code is untested, so hit me up if something looks/functions wrong) (note: you have to change how many health you lose in lua code itself):
```bash
function onEvent(name, val1, val2)
    pullStarted = true;
    stopPull = false;
    globEventName = name;
    --val1 = image path
    --val2 = how long for it will pull
    if name == 'Pull Health' then
        makeLuaSprite('puller', val1, getProperty('iconP2.x')+50, getProperty('iconP2.y'));
        runTimer('endPull', val2);
    end
end

function onTimerCompleted(luaTag, loops, loopsLeft)
    if luaTag == 'endPull' then
        stopPull = true;
        pullStarted = false;
    end
end

function onUpdatePost(elapsedVariableThatNoOneUses)
    health = getProperty('health');
    if globEventName == 'Pull Health' then
        if pullStarted == true and stopPull == false then
            setProperty('health', health - 0.01);
            setProperty('puller.x', getProperty('iconP2.x')+50);
        end
    end
end
```
Saying this again, this code is untested, so hit me up/reply for anything wrong

**Comment by acap09** [comment]
![Acap09](https://user-images.githubusercontent.com/74252758/156788057-d834edbd-654d-4052-b92f-6fe8d485d430.png)
here is my credit icon if you need it
