### ISSUE TITLE
Character Bug

### ISSUE THREAD

**Issue by unnamedmask3** [ShadowMario/FNF-PsychEngine#6203]
### Describe your bug here.

Hello, I am here to tell you about this bug that happens to me very often and it is very annoying when I finish creating my character and everything is fine with the png, the XML and the sprites/frames but when I finish configuring the character and I put it on the chart editor and when I give it to play for a moment it loads but then it closes

### Command Prompt/Terminal logs (if existing)

```bash
Does not exist
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

it's new

**Comment by frantastic24** [comment]
Never had any issues with any character so do you mind posting the files here so I can check them out? I doubt this is a bug but I'll test it out anyway

**Comment by thedeveloper112206** [comment]
maybe you just coded it wrong

**Comment by unnamedmask3** [comment]
> Never had any issues with any character so do you mind posting the files here so I can check them out? I doubt this is a bug but I'll test it out anyway

https://drive.google.com/file/d/1KpFHKmOAeapDpcmiWWYIwjq_L_FJV2ce/view (png)

https://drive.google.com/file/d/1ZnAIv751Ux3fPU7ST3iBJ1VOYoyZZ5dO/view (XML)

and the json works correctly

**Comment by frantastic24** [comment]
Send the json
