### ISSUE TITLE
Is it possible to get the current animation of a lua sprite?

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#6219]
### What is your question?

the title says it all!

### issue opened by @Acap09

**Comment by kingyomoma** [comment]
`getProperty('boyfriend.animation.curAnim.name')` or `getProperty('dad.animation.curAnim.name')`

**Comment by acap09** [comment]
> `getProperty('boyfriend.animation.curAnim.name')` or `getProperty('dad.animation.curAnim.name')`

i dont want the dad or boyfriend sprite, what i mean is that a lua sprite that i created with lua, not created by game

**Comment by frantastic24** [comment]
Then change it to your object tag dude

**Comment by acap09** [comment]
> Then change it to your object tag dude It's a basic flxanimation property, all animated objects have it

like ```getProperty('myLuaSprite.animation.curAnim.name');```?

**Comment by frantastic24** [comment]
Yes

**Comment by frantastic24** [comment]
close this

**Comment by acap09** [comment]
> close this

ok
