### ISSUE TITLE
Change Opponent Arrow Skin

### ISSUE THREAD

**Issue by kingyomoma** [ShadowMario/FNF-PsychEngine#6228]
### What is your question?

I wanted to know how I can change the arrow skins of the opponent (for example vs livid lycanthrope and applecore)
I would prefer for it to be in Lua, but I wouldn't really mind if it was with source code

thanks

**Comment by frantastic24** [comment]
There's multiple scripts that do this posted in discussions, and even a few tutorials for source

**Comment by lemz1** [comment]
```
function onCreatePost()

	for i=0,3 do
		setPropertyFromGroup('opponentStrums', i, 'texture', 'NOTE_assets2')
	end

end

function onUpdate()

    if getPropertyFromGroup('unspawnNotes', 0, 'mustPress') == false then
        setPropertyFromGroup('unspawnNotes', 0, 'texture', 'NOTE_assets2')
    end

end  
```

**Comment by frantastic24** [comment]
onUpdate why

**Comment by lemz1** [comment]
> onUpdate why

because the actual notes need to be updated every frame atleast when I tried it in onCreatePost() it didn't work

**Comment by frantastic24** [comment]
Change unspawnNotes under onCreate instead of every existing note every frame

**Comment by lemz1** [comment]
> Change unspawnNotes under onCreate instead of every existing note every frame

still doesn't work

**Comment by frantastic24** [comment]
yes it does lol

**Comment by lemz1** [comment]
> yes it does lol

can you show me the code

**Comment by frantastic24** [comment]
```lua
function onCreatePost()
	for i=0, getProperty('unspawnNotes.length')-1 do
		setPropertyFromGroup('unspawnNotes', i, 'texture', 'textureHere')
	end
end
```

**Comment by lemz1** [comment]
> ```lua
> function onCreatePost()
> 	for i=0, getProperty('unspawnNotes.length')-1 do
> 		setPropertyFromGroup('unspawnNotes', i, 'texture', 'textureHere')
> 	end
> end
> ```

oh yeah it does work, my bad. I think the problem was that I used notes instead of unspawnNotes

**Comment by kingyomoma** [comment]
thanks
