### ISSUE TITLE
How do I make everything on the HUD except the notes and strum line disappear?

### ISSUE THREAD

**Issue by NesDoesGithub** [ShadowMario/FNF-PsychEngine#6245]
### Describe your problem here.

I'm trying to make a part in my mod where everything on the HUD disappears except the strum line and notes in the middle of the song.
Like this:
![fddfgudfsuygsdf](https://user-images.githubusercontent.com/95316430/156856715-3263d6e5-aba8-42df-a62e-e725d47c159c.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by frantastic24** [comment]
```lua
		setPropertyFromClass('ClientPrefs', 'hideHud', true); --remember to return this to player's choice afterwards
		setProperty('scoreTxt.visible', false);
		setProperty('healthBar.visible', false);
		setProperty('healthBarBG.visible', false);
		setProperty('iconP1.visible', false);
		setProperty('iconP2.visible', false);
		setProperty('botplayTxt.visible', false);
		setProperty('timeBar.visible', false);
		setProperty('timeBarBG.visible', false);
		setProperty('timeTxt.visible', false);
```

**Comment by NesDoesGithub** [comment]
> ```lua
> 		setPropertyFromClass('ClientPrefs', 'hideHud', true); --remember to return this to player's choice afterwards
> 		setProperty('scoreTxt.visible', false);
> 		setProperty('healthBar.visible', false);
> 		setProperty('healthBarBG.visible', false);
> 		setProperty('iconP1.visible', false);
> 		setProperty('iconP2.visible', false);
> 		setProperty('botplayTxt.visible', false);
> 		setProperty('timeBar.visible', false);
> 		setProperty('timeBarBG.visible', false);
> 		setProperty('timeTxt.visible', false);
> ```

thank you, would there also be a way to make the sick text invisible aswell?

**Comment by frantastic24** [comment]
The code already does

**Comment by NesDoesGithub** [comment]
> The code already does

no i mean this
![download (1)](https://user-images.githubusercontent.com/95316430/156859832-60cf31bc-4bda-46da-bb6f-b1b9ae2c5a53.png)

**Comment by frantastic24** [comment]
Yes, it already does

**Comment by NesDoesGithub** [comment]
> Yes, it already does

I put everything except 
"setPropertyFromClass('ClientPrefs', 'hideHud', true);"
And the "sick!" text is still there

**Comment by frantastic24** [comment]
Because that's what hides it
