### ISSUE TITLE
How to add particles, HELP

### ISSUE THREAD

**Issue by JVGamerzbz** [ShadowMario/FNF-PsychEngine#6262]
### Describe your problem here.

Ok so, I'm trying the example of source modding. But how to add particles? 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yep, I added characters and a stage.

**Comment by BeansCool54** [comment]
What kind? Can you specify it?

**Comment by JVGamerzbz** [comment]
> What kind? Can you specify it?

like xevent for source coding
