### ISSUE TITLE
endless achievements

### ISSUE THREAD

**Issue by FedorVaice** [ShadowMario/FNF-PsychEngine#6272]
### Describe your bug here.

https://user-images.githubusercontent.com/100131137/156878954-3b7e3a92-666d-4354-8881-74f41c6d984f.mp4

When I finish any week, I get a window with week 7 reached, and then the same message appears again, I can't press enter to pause

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

bug

**Comment by Reycko** [comment]
so you modified bug ?

**Comment by FedorVaice** [comment]
not yet, I can throw off the code with the achievements
[source.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8190553/source.zip)

**Comment by FedorVaice** [comment]
not yet, I can throw off the code with the achievements
[source.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8190555/source.zip)

**Comment by BeastlyGhost** [comment]
fixed, try to download the actions build and see if the same happens

**Comment by Rem0l** [comment]
i think you could just go to Achievments.hx and delete this:

["You'll Pay For That...",		"Beat Week 7 on Hard with no Misses.",				'week7_nomiss',			'week7',		true],

i think that should help

**Comment by Theoyeah** [comment]
Me too i've got this
