### ISSUE TITLE
how can i do light particles things like on retrospecter??

### ISSUE THREAD

**Issue by Den198888** [ShadowMario/FNF-PsychEngine#6273]
### Describe your problem here.

how do i do particles spawning and goes up then fades like on retrospecter? in lua help plss

https://user-images.githubusercontent.com/96397208/156879752-8bbaa3ca-d5c4-4677-b37d-746d837b8280.mp4

like this

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

no, only winning icons and animated icons things more

**Comment by JVGamerzbz** [comment]
Its in this tho:
https://gamebanana.com/questions/24842

So I'm not in lua I'm in source. There is lua tutorial here.

**Comment by Den198888** [comment]
i tried that but it didnt work for me

**Comment by JVGamerzbz** [comment]
> i tried that but it didnt work for me im on 0.5

u should update it to 0.2.5h or 0.5.1 try it
