### ISSUE TITLE
setTextFont doesnt change the font

### ISSUE THREAD

**Issue by WortwL** [ShadowMario/FNF-PsychEngine#6274]
### Describe your problem here.

am trying to change the custom text with this font https://gamebanana.com/tools/7763

but it doesnt change it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by machonessiebaby** [comment]
setTextFont("scoreTxt", "fontnamehere.ttf") 
put the fonts TTF into the fonts folder in example mods 
then put the code above into a lua script like this




function onCreate(elapsed)
	setTextFont("scoreTxt", "fontnamehere.ttf")
end

yes this is lua

**Comment by WortwL** [comment]
oh my god am so stupid

anyways thanks

**Comment by machonessiebaby** [comment]
> oh my god am so stupid (because i didnt add the ttf in settextfont)
> 
> anyways thanks

im stupid too dont worry lol

**Comment by frantastic24** [comment]
Close this
