### ISSUE TITLE
error with chart

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#6277]
### Describe your bug here.

So you know how the chart switches sections as the song plays it wont do it for me and it just infinitely goes down? does anyone one how to fix?
video:

https://user-images.githubusercontent.com/56323671/156883231-5791e4da-4015-4a58-bf3b-9821ec4e43f1.mp4

i dont know if this is a engine bug or something i did after updating but it just started happening today sadly

### Are you modding a build from source or with Lua?

Lua & source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by machonessiebaby** [comment]
charting works still but it will be slower and harder to time it cuz i use the arrows in chart editor so i can see how long i made a hold note go into the next measure

**Comment by Den198888** [comment]
![Screenshot_2022-03-05-21-42-29-94_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/96397208/156885916-56e00dbe-0998-4285-93f2-919fef6f96c7.jpg)

try to uncheck Disable Autoscroll maybe?

**Comment by machonessiebaby** [comment]
> ![Screenshot_2022-03-05-21-42-29-94_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/96397208/156885916-56e00dbe-0998-4285-93f2-919fef6f96c7.jpg)
> 
> try to uncheck Disable Autoscroll maybe?

wait did i disable it? wow i never noticed Thanks!

**Comment by machonessiebaby** [comment]
> ![Screenshot_2022-03-05-21-42-29-94_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/96397208/156885916-56e00dbe-0998-4285-93f2-919fef6f96c7.jpg)
> 
> try to uncheck Disable Autoscroll maybe?

yea im a fucking dumbass

**Comment by Den198888** [comment]
Welcome ;)
