### ISSUE TITLE
Story Mode does not update difficulties upon starting

### ISSUE THREAD

**Issue by AdrianCD5** [ShadowMario/FNF-PsychEngine#6286]
### Describe your bug here.

I'm finishing off a build for a mod that has no base game weeks, and only uses weeks from the mods folder. These weeks only include Hard difficulty, however when starting up Story Mode (with the mod's first week being the first selection), it starts on Normal difficulty, and only updates to not include it when changing difficulty or changing weeks.

What I found was that this difficulty isn't actually Normal, rather it's just called 'null'. I've added '-null' charts to the first week as a workaround, however it'd be much better if this didn't happen and difficulties properly updated when the menu opened.

### Command Prompt/Terminal logs (if existing)

```bash
[file_contents,assets/data/rt-bopeebo/rt-bopeebo-null.json]
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I removed all of the week jsons from the base game, in place of the weeks in my 'mods' folder.

**Comment by machonessiebaby** [comment]
i have this same bug the best you can do is enter a week on normal mode press 7 and do the charting by loading audio and json
very very weird

**Comment by frantastic24** [comment]
Seems to be fixed in source already

**Comment by Rem0l** [comment]
i guess you should delete easy and normal from CoolUtil.hx but you need source for this 

https://github.com/ShadowMario/FNF-PsychEngine/wiki/Adding-a-New-Difficulty
you can use this as a guide, but instead of adding delete difficulties.
