### ISSUE TITLE
Why ma game crashes?

### ISSUE THREAD

**Issue by Rem0l** [ShadowMario/FNF-PsychEngine#6288]
### Describe your bug here.

when i build up my game, with dialogue code (https://github.com/ShadowMario/FNF-PsychEngine/wiki/Dialogues) my game crashes when dialouge should be loaded. could this be my computer fault, or idk?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i edited playState.hx and added dialouge from tutorial above, stage, part of new function and and in clientPrefs.hx and GameplaySettingsSubState.hx added new function.

**Comment by Rem0l** [comment]
ok i found it myself

**Comment by frantastic24** [comment]
Close it then
