### ISSUE TITLE
Change to Upscroll midsong?

### ISSUE THREAD

**Issue by NesDoesGithub** [ShadowMario/FNF-PsychEngine#6306]
### Describe your problem here.

I am trying to change it to upscroll mid-song, I just tested it and it isn't working

```
function onStepHit()
    if curStep == 4 then
        setPropertyClass('ClientPrefs', 'upScroll', true)
    end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by frantastic24** [comment]
Iirc you have to manually reposition the strums and do
```lua
for i=0, 7 do
          setPropertyFromGroup('strumLineNotes', 0, 'downScroll', false)
end
```
