### ISSUE TITLE
i know this is a computer error not a engine error, but this error is happening only on psych (sorry for my bad english)

### ISSUE THREAD

**Issue by fox-64** [ShadowMario/FNF-PsychEngine#6307]
### What is your question?

my game switches the spites to black square in mid-music and BOOM... the game crashes and the game do it in EVERY MOD WHO USES PSYCH, PLS HELP ME

**Comment by frantastic24** [comment]
Get a better PC

**Comment by fox-64** [comment]
> Get a better PC

My game is´nt making this just this moment is happening

**Comment by fox-64** [comment]
> Get a better PC

and psych is the unique who make this

**Comment by Galaxy621** [comment]
I'm pretty sure this is because you're running out of memory. As stated previously, you most likely need a new computer, or just some more RAM

**Comment by fox-64** [comment]
> I'm pretty sure this is because you're running out of memory. As stated previously, you most likely need a new computer, or just some more RAM

thanks i search how to install ram and i found tutorials for it thanks <3
