### ISSUE TITLE
Animation sound plays when hitted a note

### ISSUE THREAD

**Issue by MrPurpleWhoLikesSpaghetti** [ShadowMario/FNF-PsychEngine#6309]
### What is your question?

i used to make a warn note from this tutorial :https://www.youtube.com/watch?v=Yb2opPvAXIc&ab_channel=bandugaming
and i have a question. is it possible to when you hit a note animation of bf and sound plays?

using lua

**Comment by frantastic24** [comment]
Read the wiki or look it up in discussions, people have done it already

**Comment by Pico8430** [comment]
![putthiscodeforfreesound](https://user-images.githubusercontent.com/91833725/156901689-0d045c53-cd44-43b7-9ce3-9af60cc99188.png)
Use `playSound()` to make it work.

**Comment by kingyomoma** [comment]
`playSound('yoursoundfilehere', 1)`
file has to be in `yourmodhere/sounds` or in `assets/sounds`

**Comment by MrPurpleWhoLikesSpaghetti** [comment]
> Read the wiki or look it up in discussions, people have done it already

i tried to find but there couldnt be any discussions about it

**Comment by MrPurpleWhoLikesSpaghetti** [comment]
> Literally how, there is a search feature

how you guys call that note? maybe i can find it if i type it right
![image](https://user-images.githubusercontent.com/98546734/157293518-20729d01-f4cb-4dfc-b60f-4e5fed35da33.png)

**Comment by MrPurpleWhoLikesSpaghetti** [comment]
> > Literally how, there is a search feature
> 
> how you call that note? ![image](https://user-images.githubusercontent.com/98546734/157293518-20729d01-f4cb-4dfc-b60f-4e5fed35da33.png) maybe i can find it if i type it right

forgot to reopen it

**Comment by frantastic24** [comment]
Why
You already got your answer

**Comment by MrPurpleWhoLikesSpaghetti** [comment]
> Why You already got your answer

yea but i really have a different code

function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is an Instakill Note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'WarnNote' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'WARNNOTE_assets'); --Change texture

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored

			end
		end
	end
	--debugPrint('Script started!')
end

-- Function called when you hit a note (after note hit calculations)
-- id: The note member id, you can get whatever variable you want from this note, example: "getPropertyFromGroup('notes', id, 'strumTime')"
-- noteData: 0 = Left, 1 = Down, 2 = Up, 3 = Right
-- noteType: The note type string/tag
-- isSustainNote: If it's a hold note, can be either true or false

function noteMiss(id, direction, noteType, isSustainNote)
	if noteType == "WarnNote" then
		setProperty('health', -500)
	end
end
and i dont know where to add this code

**Comment by frantastic24** [comment]
Maybe try I dunno
Reading the code

**Comment by frantastic24** [comment]
You don't need to know how to code
It's basic reading comprehension

**Comment by MrPurpleWhoLikesSpaghetti** [comment]
alright putted here
![image](https://user-images.githubusercontent.com/98546734/157299291-0625be47-bb71-4da2-a24a-feb5075cc812.png)
and it doesnt work like it doesnt crash but doesnt play sound and animation
idk what i did wrong

**Comment by frantastic24** [comment]
Wrong note name

**Comment by MrPurpleWhoLikesSpaghetti** [comment]
![image](https://user-images.githubusercontent.com/98546734/157300353-b7de15a7-6355-482f-a1a2-a8467b785af3.png)
still nothing happens

**Comment by frantastic24** [comment]
Your function is wrong, why did you change it??
`function goodNoteHit(id, direction, noteType, isSustainNote)`

**Comment by MrPurpleWhoLikesSpaghetti** [comment]
> Your function is wrong, why did you change it?? `function goodNoteHit(id, direction, noteType, isSustainNote)`

well still doesnt work

**Comment by frantastic24** [comment]
You have `notetype` instead of `noteType`, it's case sensitive, change the function variable or the one under it so they match
Again, read the code you're using

**Comment by MrPurpleWhoLikesSpaghetti** [comment]
> You have `notetype` instead of `noteType`, it's case sensitive, change the function variable or the one under it so they match Again, read the code you're using

where is the "notetype" instead of "noteType"

**Comment by frantastic24** [comment]
In the code you added, where else
If you can't see it, there is a text search feature that's useful

**Comment by MrPurpleWhoLikesSpaghetti** [comment]
> In the code you added, where else If you can't see it, there is a text search feature that's useful

It works!! thank you so much
