### ISSUE TITLE
How do I make the sick, good, bad and combo sprites semi-transparent midsong?

### ISSUE THREAD

**Issue by NesDoesGithub** [ShadowMario/FNF-PsychEngine#6316]
### Describe your problem here.

I am making a mod and I want my sick, good, bad and combo sprites to be semi-transparent midsong, is there any way to do this in lua?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by ShadowMario** [comment]
No.
