### ISSUE TITLE
How to change scale of in-game sprite via Lua

### ISSUE THREAD

**Issue by KirbyKid256** [ShadowMario/FNF-PsychEngine#6353]
### Describe your problem here.

I've been trying to port Funkin' At Freddy's via Lua, however, I can't seem to scale the FlxSprites of the pixel countdown. It only works for "countdownReady", but the other two don't seem to scale properly. As a side note, I also don't know how to get a script to run only when the stage is a pixel stage.

https://user-images.githubusercontent.com/70983335/156927309-58e23bd6-1c84-469d-a036-046e43bb3ba5.mov

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited FunkinLua.hx and made cutscenes more compatable with mac.

**Comment by frantastic24** [comment]
```lua
function onCountdownTick(counter)
     scaleObject('countdownReady', scaleX, scaleY)
     scaleObject('countdownSet', scaleX, scaleY)
     scaleObject('countdownGo', scaleX, scaleY)
end
```
`if getPropertyFromClass('PlayState', 'isPixelStage') then`
Though I don't know why you need it specifically for pixel stages
