### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MysticFox990** [ShadowMario/FNF-PsychEngine#6370]
### Describe your problem here.

How do I make the whole script only activate on a specific difficulty?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by machonessiebaby** [comment]
easy for lua epic simple code

function onCreate(elapsed)
	if difficulty == 4 then
		Function here
	end

**Comment by frantastic24** [comment]
elapsed is only part of onUpdate

**Comment by CrusherMods** [comment]
> easy for lua epic simple code
> 
> for the number 1 = easy 2 = normal 3 = hard and so on for customs function onCreate(elapsed) if difficulty == (difficulty number) then Function here end

actually 0 = easy
1 = normal
and 2 = hard
according to the wiki I believe

**Comment by MysticFox990** [comment]
> > easy for lua epic simple code
> > for the number 1 = easy 2 = normal 3 = hard and so on for customs function onCreate(elapsed) if difficulty == (difficulty number) then Function here end
> 
> actually 0 = easy 1 = normal and 2 = hard according to the wiki I believe

ok but what about custom difficulties

**Comment by frantastic24** [comment]
It goes in order of the week's difficulties
Default is 0 easy 1 normal 2 hard
If your difficulties are Hard, Very Hard and Impossible then it's 
0-Hard
1-Very Hard
2- Impossible

**Comment by MysticFox990** [comment]
> It goes in order of the week's difficulties Default is 0 easy 1 normal 2 hard If your difficulties are Hard, Very Hard and Impossible then it's 0-Hard 1-Very Hard 2- Impossible

mine is more like four-note and five-note

**Comment by frantastic24** [comment]
It was example, the game doesn't care about the name
