### ISSUE TITLE
Upscroll and downscroll animation

### ISSUE THREAD

**Issue by facundomax** [ShadowMario/FNF-PsychEngine#6394]
### Describe your problem here.

I have 2 animations for my character, the first is for the upscroll and the second for the downscroll... how do I program those animations where they belong? that is, when I activate the downscroll option, the animation is activated for the downscroll and the same with the upscroll, how do I program that?

### Are you modding a build from source or with Lua?

Source and lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
if (ClientPrefs.downScroll)
