### ISSUE TITLE
alt animation can't fully play

### ISSUE THREAD

**Issue by AlexDrar** [ShadowMario/FNF-PsychEngine#64]
I am triying to make a week 7 port but the pretty good animation don't fully plays, there is a way so only that the pretty good animation fully plays until the next note change animation?

https://user-images.githubusercontent.com/86253780/133823956-4cbecc94-926e-4b8f-b1f6-a7c70e526dcb.mp4

https://user-images.githubusercontent.com/86253780/133824047-7fce48cb-bdc1-4e81-a8c2-6f3a1da8fb2f.mp4

**Comment by ShadowMario** [comment]
That's because Tankman uses a thing on his code that blocks dance() function from being called, this is not really an issue.

**Comment by AlexDrar** [comment]
> That's because Tankman uses a thing on his code that blocks dance() function from being called, this is not really an issue.

So how do i fix it?

**Comment by RedstoneRuler** [comment]
Add this to script.lua:
```
function onUpdate(elapsed)
	if getProperty('dad.curCharacter') == 'tankman' then
		if getProperty('dad.animation.curAnim.name') == 'singDOWN-alt' then
			setProperty('dad.holdTimer', 0);
		end
	end
end
```
