### ISSUE TITLE
how do i alpha 0.9 down to 0 but in order?

### ISSUE THREAD

**Issue by Den198888** [ShadowMario/FNF-PsychEngine#6400]
### Describe your problem here.

im trying to port it all but also the events of Afton BG Darker but i wanted it to be like 1 by 1 fade like 0.9, 0.85, 0.8 down to 0

https://user-images.githubusercontent.com/96397208/156951935-7ba48b76-7458-47d7-8d14-c8c06539ff6d.mp4

but it only do the 0 alpha

![Screenshot_2022-03-07-09-10-13-48_87c2225eebc34d2513fa0e7ad5b93cfc](https://user-images.githubusercontent.com/96397208/156951966-a2c9b733-c445-45ba-8981-a26713d3c31c.jpg)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

**Comment by frantastic24** [comment]
You can do something like:
Set up a local counter `local counter = 1`, then use
```lua
setProperty('tag.alpha', tonumber[counter])
-- the rest of the sprites
counter = counter + 1
```

**Comment by Den198888** [comment]
thank you😃♥️
