### ISSUE TITLE
video backgrounds

### ISSUE THREAD

**Issue by Swagwhisperer10** [ShadowMario/FNF-PsychEngine#6409]
### What is your question?

I want to have basically like an animated background, but instead, I want a video to play.
How can I make a video play in background?

**Comment by PersonNanoexe** [comment]
Why? Just make an animated sprite lmao.

**Comment by main-thing** [comment]
This gonna be hard to do as if the video is too long it will just be black. There is not many work arounds for this too. But you can still try to use [this.](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Custom-Sprites-Functions#makeanimatedluaspritetagstring-imagestring-xfloat-yfloat)

**Comment by Swagwhisperer10** [comment]
That only works using .png + it requires an xml witth seperate frames.
