### ISSUE TITLE
Timing window changes when minimizing the screen

### ISSUE THREAD

**Issue by BombasticTom** [ShadowMario/FNF-PsychEngine#6422]
### Describe your bug here.

Basically the hit timing window gets weirder when you minimize it more (the notes are more off when you press them)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing.

**Comment by ShadowMario** [comment]
That's expected, after all there's less pixel accuracy if the space for pixels on your screen is smaller.
