### ISSUE TITLE
possible values

### ISSUE THREAD

**Issue by MysticFox990** [ShadowMario/FNF-PsychEngine#6441]
### Describe your problem here.

how do i add possible values like 
if curStep == 1287 or curStep == 1024 or curStep == 2854 then
will that work?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by cyn-8** [comment]
yes that conditional will pass if curstep is equal to any of those

**Comment by MysticFox990** [comment]
> yes that conditional will pass if curstep is equal to any of those
no, I'm talking about if all of them in one line

**Comment by frantastic24** [comment]
They already said yes, you got your answer so you can close this

**Comment by MysticFox990** [comment]
> They already said yes, you got your answer so you can close this

you are missing the point

**Comment by frantastic24** [comment]
No that was you
