### ISSUE TITLE
Extra Keys

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#6449]
### Describe your problem here.

How do i add Extra Keys, preferably 26, using source code, without using the shaggy source code

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by IndigoDarkw0lf** [comment]
[bruh just use this](https://github.com/tposejank/FNF-PsychEngine-ExtraKeys)

**Comment by PDL2CGamejolt** [comment]
HOW DID I FIND THIS 😭

**Comment by FuseIsHere813** [comment]
You NEED shaggy's source code for extra keys. For 26, do some research 💀
