### ISSUE TITLE
How can you change a song by the Difficulty (Example: Vs Oswald)

### ISSUE THREAD

**Issue by BocaIoachim** [ShadowMario/FNF-PsychEngine#645]
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Source Code

### Show an screenshot/video of your problem.

Does some body know how to change a song by the difficulty I mean like (Example: if its easy he says that he' gonna go easy on me and on hard he is gonna transform or something)

**Comment by ShadowMario** [comment]
> If it solved the issue, please close it.

Yeah close your issue buckaroo
