### ISSUE TITLE
the engine crashes

### ISSUE THREAD

**Issue by endergames231** [ShadowMario/FNF-PsychEngine#6473]
### Describe your bug here.

when the psysh engine 0.5.2 came in, but the automatic crashes

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

...

**Comment by frantastic24** [comment]
Wow so descriptive and helpful

**Comment by endergames231** [comment]
> Wow so descriptive and helpful

Shut up kid
