### ISSUE TITLE
WTF SHADOW MARIO FIXXXX THISSSS 0.5.2

### ISSUE THREAD

**Issue by Theoyeah** [ShadowMario/FNF-PsychEngine#6475]
### Describe your bug here.

When fc week 1 ,  i get an infinity of week 7 achivement ! @ShadowMario plz fix
![image](https://user-images.githubusercontent.com/97792861/157185696-3ae4f833-cb04-4126-96d5-89732027e0d3.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not even

**Comment by thedeveloper112206** [comment]
holy funk you got the hidden week 7 achievement. /j
