### ISSUE TITLE
Add sounds to note type

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#6478]
### Describe your problem here.

So I was trying to add a slash sound when the note was pressed but a stab sound when the note is missed can you telll me how to implement it into my code (here it is btw)

```
function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is a Knife Note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Knife Note' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'knife_notes'); --Change texture
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'knife_notesSplashes')
			setPropertyFromGroup('unspawnNotes', i, 'missHealth', 0.6); --Change amount of health to take when you miss like a fucking moron
		end
	end
	--debugPrint('Script started!')
end

-- Function called when you hit a note (after note hit calculations)
-- id: The note member id, you can get whatever variable you want from this note, example: "getPropertyFromGroup('notes', id, 'strumTime')"
-- noteData: 0 = Left, 1 = Down, 2 = Up, 3 = Right
-- noteType: The note type string/tag
-- isSustainNote: If it's a hold note, can be either true or false

dodgeAnimations = {'dodgeLEFT', 'dodgeDOWN', 'dodgeUP', 'dodgeRIGHT'}
function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'Knife Note' then
		characterPlayAnim('boyfriend', 'dodge', true);
		setProperty('boyfriend.specialAnim', true);

		local animToPlay = 'dodge';
		if noteData == 0 then
			animToPlay = 'Slash';
		elseif noteData == 1 then
			animToPlay = 'Slash';
		elseif noteData == 2 then
			animToPlay = 'Slash';
		elseif noteData == 3 then
			animToPlay = 'Slash';
		end
		characterPlayAnim('dad', 'Slash', true);
		setProperty('dad.specialAnim', true);
	end
end

local healthDrain = 0;
function noteMiss(id, noteData, noteType, isSustainNote)
	if noteType == 'Knife Note' then
		-- bf anim
		characterPlayAnim('boyfriend', 'hurt', true);
		setProperty('boyfriend.specialAnim', true);

		-- dad anim
		characterPlayAnim('sad-serena', 'Slash', true);
		setProperty('dad.specialAnim', true);

		-- health loss | || || |_
		--setProperty('health', getProperty('health') - 0.6);
		healthDrain = healthDrain - 500;
	end
end

function onUpdate(elapsed)
	if healthDrain > 0 then
		healthDrain = healthDrain - 0.6;
		setProperty('health', getProperty('health') - 0.6);
		if healthDrain < 0 then
			healthDrain = 0;
		end
	end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I made sprites and i have used some scripts

**Comment by frantastic24** [comment]
```lua
playSound('soundFile', volume)
```
This belongs in discussions, and this is also on the wiki

**Comment by SonicXFire1987** [comment]
does it matter where I put it in the code? as long as the hit sound is in `function goodNoteHit` and the miss is in `function notMiss` am I correct?

**Comment by Pico8430** [comment]
If you want the note to play a sound when is touched, put `playSound()` in `function goodNoteHit`.
But if you want the note to play a miss sound, use the same thing but in `function noteMiss`.

**Comment by SonicXFire1987** [comment]
> If you want the note to play a sound when is touched, put `playSound()` in `function goodNoteHit`. But if you want the note to play a miss sound, use the same thing but in `function noteMiss`.

it didn't work did I do something wrong?

**Comment by frantastic24** [comment]
Probably, what does your code look like and what are the sound and note type named? just the name of the sound and directory if it's not inside mods/sounds, don't need to send the file

**Comment by SonicXFire1987** [comment]
thats what I did and I inserted the code like this and it didn't work and I made sure they were ogg files too
```
function goodNoteHit(id, noteData, noteType, isSustainNote)
        playSound('swipe', 0.5);
	if noteType == 'Knife Note' then
```

**Comment by frantastic24** [comment]
Send the entire note script, and you didn't tell me any of the file names like I said in my reply
Please read before replying, I can't help if I don't have information
