### ISSUE TITLE
Mod disables upon exiting the mod menu

### ISSUE THREAD

**Issue by BombasticTom** [ShadowMario/FNF-PsychEngine#6499]
### Describe your bug here.

When you have only one mod in your mods data that you can enable/disable, this happens

https://user-images.githubusercontent.com/85838311/157244471-882a2b6b-774f-42e5-ac02-c48dddbfd844.mp4

Also idk if it's because I am using a mod for an outdated version, but it seems like ~~the mod stage isn't loading for the specific song~~ (Uses an outdated function). When I imported other mods their stages were working perfectly fine.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing.

**Comment by Grape-Boy** [comment]
I think it was coded in a weird way or it wasn't coded for the button to stay on.
