### ISSUE TITLE
5.1 crashes when changing difficaulty

### ISSUE THREAD

**Issue by JacksRobotics** [ShadowMario/FNF-PsychEngine#6500]
### Describe your bug here.

i downloaded the madness ventilazation mod. added it to the mods folder in psych engine 5.1. yes i know theres 5.2 now. im just lazy to download the other one. once i beated the hard mode. i went to the song again and change difficaulty. pressed esc accidently. and it crashed. it said something null.ventilazation.json or stuff like that. i then went back and pressed change difficaulty. and pressed esc on purpose now. and nothing happend.

### Command Prompt/Terminal logs (if existing)

```bash
nothing
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

just added madness ventilazation. in mods folder lol

**Comment by JeremiahIsKing** [comment]
This is very Important pls help

https://github.com/ShadowMario/FNF-PsychEngine/discussions/6502

**Comment by frantastic24** [comment]
This is a duplicate, it was already fixed a while ago
Update to 0.5.2
