### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by KyleOliverDeveloper** [ShadowMario/FNF-PsychEngine#6511]
### Describe your problem here.

So, i noticed that Psych Engine v5.0.2 has dropped, and now we can add achievements without source. The thing is, i dont understand how to make a custom achievement. Any Help?
![image](https://user-images.githubusercontent.com/94708825/157283875-caf065ca-21f0-4303-a26e-dd66254cc701.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by KyleOliverDeveloper** [comment]
> Wait for the documentation

ok

**Comment by Starmapo** [comment]
It doesn't work, it was available before but they removed it due to being buggy, they just forgot to remove the folder.

**Comment by 3ukn** [comment]
finally, psych engine v5.0.2

**Comment by PersonNanoexe** [comment]
0.5.2*

**Comment by Cristobal653** [comment]
{
    "name": "i LOVE botplay!",
    "icon": "achievements/botplay",
    "description": "Beat the Joke week.. you must really love using botplay, don't you?",
    "unlocksAfter": "weekgoodluck",
    "hidden": false
    }
