### ISSUE TITLE
The Engine Crash

### ISSUE THREAD

**Issue by AugustoAvellanedaYT** [ShadowMario/FNF-PsychEngine#6515]
### Describe your bug here.

I Play Dusk Till Dawn but GAME Crashes

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Great report, so useful

**Comment by fox-64** [comment]
I think is you need some ran, on yt has tutorials of how u put some virtual ram, i have the same problem but with every mod, but i see some tutorials and now is working
