### ISSUE TITLE
antivirus and exe problem

### ISSUE THREAD

**Issue by chubilol** [ShadowMario/FNF-PsychEngine#6516]
### Describe your bug here.

my antivirus says the exe is a virus and now avast deleted the exe and i cant start the game

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by KyleOliverDeveloper** [comment]
> ### Describe your bug here.
> my antivirus says the exe is a virus and now avast deleted the exe and i cant start the game
> 
> ### Command Prompt/Terminal logs (if existing)
> _No response_
> 
> ### Are you modding a build from source or with Lua?
> Lua
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> no

the IDP.GENERIC "virus" is a false alarm, just, get another v5.0.2 build. Avast says theres a virus. Go to "More Options", then click it. After this click "Create Exception"
![image](https://user-images.githubusercontent.com/94708825/157292210-47cfd3b8-a66a-4a6f-bbc0-66e871873abc.png)
