### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by Abyss901** [ShadowMario/FNF-PsychEngine#6518]
### Describe your problem here.

How tf do you add achievments in the 0.5.2 update

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Only 2 Custom Events

**Comment by KyleOliverDeveloper** [comment]
wait for the documentation

**Comment by Abyss901** [comment]
wdym

**Comment by ImaginationSuperHero528** [comment]
> wdym

Wait for the wiki to be updated

**Comment by Abyss901** [comment]
ok
