### ISSUE TITLE
how to make someone not able to use the controls

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#6523]
### What is your question?

Hi,
I want to know how to make someone not able to use their controls.
I don't want to use stunned because I also don't want the strum to play an animation.

**Comment by main-thing** [comment]
Enabke bot play during that time. Then disable it. If they are already using botplay do not trigger the script.

**Comment by lemz1** [comment]
I don't want to use botplay since it will just hit the notes for the player.

**Comment by main-thing** [comment]
wait does that section contains notes? if it does make it an ignore note.

**Comment by lemz1** [comment]
I'll go more into depth:
I have an event that makes you need to fulfill a specific criteria. While the player hasn't fulfilled it, he isn't supposed to use his controls

**Comment by main-thing** [comment]
Use stunned and make fake strums during that time hiding the real one. Then show the real one and hjde the fakes after the condition is fufilled. ( this is the easiest way I could think of.)
