### ISSUE TITLE
how to add characters using atlas texture in game

### ISSUE THREAD

**Issue by Luc4s-adv** [ShadowMario/FNF-PsychEngine#6537]
### Describe your problem here.

I'm trying to add a character using atlas texture (or animateatlas if you prefer, but anyway) I've tried everything but nothing works, I've already got to base myself on the form of Fnf HD but without success, And the Psych Wiki doesn't teach much about it either, it just says how to export sprites in the form of Spritemap.

### Are you modding a build from source or with Lua?

Lua/out of source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just trying to add a character using this new tool

**Comment by An-undertale-fan** [comment]
I heard that you need to create a folder called TextureAtlas and u put inside it a folder with the charcter name and inside it bitMap.png and json
And animation.json
If im right

**Comment by keanu64github** [comment]
and spritemap.json

**Comment by ShadowMario** [comment]
https://github.com/Smokey555/Flixel-TextureAtlas
