### ISSUE TITLE
Unable to press f to fullscreen

### ISSUE THREAD

**Issue by GabeGalax** [ShadowMario/FNF-PsychEngine#6538]
### Describe your bug here.

I'm unable to press f to fullscreen on the title screen

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ImaginationSuperHero528** [comment]
alt + enter should do the trick.

**Comment by frantastic24** [comment]
Fullscreen was partially removed, not a bug
