### ISSUE TITLE
Death animation keeps reverting to boyfriend when using a different character.

### ISSUE THREAD

**Issue by AdmiralKirby** [ShadowMario/FNF-PsychEngine#654]
### Bug report

Every time I use a custom sprite other than boyfriend when I die, it goes to bf's blue ball animation. I have everything in the XML correctly but it doesn't help.

### Did you edit anything? If so, mention or summarize your changes.

I'm using the base engine, I didn't edit any code.

**Comment by ShadowMario** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API
There's an example for changing death animations/sounds
