### ISSUE TITLE
Beating week 1 on hard with no misses

### ISSUE THREAD

**Issue by Colxsy** [ShadowMario/FNF-PsychEngine#6541]
### Describe your bug here.

When I first completed week 1 on hard with no misses it said, "You'll pay for that..." "Beat week 7 on hard with no misses." and it keeps spamming it every time it disappears.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I tried retrying, but it keeps popping up.

**Comment by NotJoe0423** [comment]
This also happened to me.
