### ISSUE TITLE
secrets folder not exported

### ISSUE THREAD

**Issue by Jsa010** [ShadowMario/FNF-PsychEngine#6542]
### Describe your bug here.

the 0.5.2 have the new `secrets` but in the export file it not appears and when i write 'shadow','bb','river' or 'shubs' on the tittle screen it not happend anything,what happed?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
it's not supposed to

**Comment by ShadowMario** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/44785097/157362856-404728ff-fca1-408d-b285-34bac0325894.png)
on Project.xml

**Comment by Jsa010** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/44785097/157362856-404728ff-fca1-408d-b285-34bac0325894.png) on Project.xml

Thx
