### ISSUE TITLE
Camera starts way below stage

### ISSUE THREAD

**Issue by xzh3r** [ShadowMario/FNF-PsychEngine#6548]
### Describe your problem here.

Whenever I use this stage. the camera spawns really far under the actual stage and moves back up after a bit. It doesnt look good, so I need to fix it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Pico8430** [comment]
This is maybe because of girlfriend's x position on the json, or something related. Try fixing it.

**Comment by ShadowMario** [comment]
The camera is tied to the Girlfriend, you can adjust the camera position by changing GF's position/camera offset on the stage JSON file.
