### ISSUE TITLE
Song glitches during the last second

### ISSUE THREAD

**Issue by Al-AmeenAdewunmi** [ShadowMario/FNF-PsychEngine#6551]
### Describe your bug here.

To put it short, at the last second (when the timer says 0:00), the song "No Villains", for some reason, attempts to restart itself, repeating the first note. While this is a minor issue, this has never occurred in the previous version, so I'm wondering why it's occurring here.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited image assets, but never anything from the source.

**Comment by Theoyeah** [comment]
any footage ?

**Comment by Al-AmeenAdewunmi** [comment]
https://user-images.githubusercontent.com/53586162/157510367-65248fe0-a9af-42a3-8cb8-54dafa7982be.mp4

**Comment by ShadowMario** [comment]
Vocals length needs to be the same as music.
