### ISSUE TITLE
How to make a sick counter (like kade engine and andromeda engine) on lua?

### ISSUE THREAD

**Issue by fox-64** [ShadowMario/FNF-PsychEngine#6556]
### What is your question?

Hello, i have played some mods and i see some mods with sick counters, and i love it, i try to find a tutorial to how to make it and i don t find nothing :( anyone knows how 2 make it?

**Comment by Nuaxz** [comment]
just steal code from dave and bambi definitive edition source

**Comment by fox-64** [comment]
> just steal code from dave and bambi definitive edition source

I mean in lua, bc of vswhiity who change the game bc of a script on the mod (the mods folder one)

**Comment by frantastic24** [comment]
#3670

**Comment by BeastlyGhost** [comment]
you should probably use discussions next time

https://github.com/ShadowMario/FNF-PsychEngine/discussions/3707

**Comment by fox-64** [comment]
> #3670 

Thanks

**Comment by fox-64** [comment]
> you should probably use discussions next time
> 
> https://github.com/ShadowMario/FNF-PsychEngine/discussions/3707

Amd thanks u too and ok i will use more disscussions, Sorry for the inconvenience
