### ISSUE TITLE
IDP.ARES.Generic Virus Warning

### ISSUE THREAD

**Issue by MaybeMaru** [ShadowMario/FNF-PsychEngine#6557]
### What is your question?

Hi everyone, I dont really know what type of issue I should make this so I'll just make it a question.

Ok, so, for some reason the new version of Psych Engine keeps giving both of my antiviruses an IDP.ARES.Generic virus warning.
I know the engine ain't hiding a virus in there or anything, I just wanted the developers to know about it  and fix it if there is any way of doing it. I dont really know much about It so maybe it is just a problem with my pc lol.

Anyways thanks for reading

As a little note if it helps my antiviruses are Norton and AVG

**Comment by TheRealJake12** [comment]
Windows? Linux? what is it

**Comment by MaybeMaru** [comment]
> Windows? Linux? what is it

Windows 10 64 Bits

**Comment by MaybeMaru** [comment]
Ok, I whatched other issues and they say the way to fix it and that it is not a problem with the engine, sorry for the trouble
Imma gonna close this now

**Comment by MaybeMaru** [comment]
To anyone wondering just change your antivirus settings when scanning for viruses or make an exception for psych engine
