### ISSUE TITLE
Antivirus issue.

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#6562]
### Describe your bug here.

I'm unsure if you guys are aware but every time i try to fire up the latest psyche engine I get this alert from my antivirus.
(AVG antivirus FREE)
![Virus](https://user-images.githubusercontent.com/97060639/157347109-98a8a4db-12e4-49c0-9327-9dd4b071d50b.PNG)
Should i make an exception for this or is something seriously wrong?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Just downloaded 0.5.2. Nothing changed.

**Comment by MaybeMaru** [comment]
Hi, So I had the same issue.
It isnt an actual virus, just tell you antivirus to ignore it and you should be good!

**Comment by ShadowMario** [comment]
This is Psych
