### ISSUE TITLE
No music

### ISSUE THREAD

**Issue by AldoxL** [ShadowMario/FNF-PsychEngine#6586]
### Describe your problem here.

When the 05.2. started it have problems, i will not talk about that, but when it started i counld't hear anything in the 0.5.1 and 0.5.2. and with this latest uptade i cant please help me if this is a bug or what, because i see all the volume things in my pc and i dont found the thing

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

on 0.5.1. yes, on 5.0.2. no and on 0.5.2h. no

**Comment by XS09-dev** [comment]
Did you press 0?

**Comment by AldoxL** [comment]
Oh yeah, i dont knowed when you press 0 also all the music and sounds dissapear, thanks, but now my antivirus is telling me the version have a idp.ares.generic

**Comment by frantastic24** [comment]
False positive

**Comment by frantastic24** [comment]
It's not a virus, add the folder to the ignore list

**Comment by AldoxL** [comment]
fuck i already putted the game on the anti virus thing and i cant open again the file
