### ISSUE TITLE
Application!

### ISSUE THREAD

**Issue by Theemoldy01** [ShadowMario/FNF-PsychEngine#6593]
### Describe your problem here.

So I just compiled the game and im not tryn to sound dumb here but, how do I get the exe or application onto my compiled game since I only got the files when I exported it
![bin 3_8_2022 10_43_16 PM_LI](https://user-images.githubusercontent.com/101242627/157387017-d3275f7e-f156-4c1c-b6ca-1e3e238bd848.jpg)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Some antivirus are falsely flagging the game as malicious, add the folder to the ignore list

**Comment by Theemoldy01** [comment]
Alright, by any chance would I need some sort of program to do so? or is it just a saying since I haven't really experienced putting something in a ignore list before on my pc.

**Comment by frantastic24** [comment]
go to your antivirus settings and add the folder to its whitelist/ignore list, if you don't know what or where it is, google is free

**Comment by Theemoldy01** [comment]
I figured how to add the files out of my antivirus list but still dont know if im doing it right since I tried again but still no luck at all with the exe file, do I need to put the main psych engine file on the ignore list or every file on there (psych is kinda confusing forr meee ahhhh)

**Comment by main-thing** [comment]
Its not the antivirus. I had the same problem. Read what the console says while compiling. You gotta wait a looong time the first time you compile.

**Comment by Theemoldy01** [comment]
Ohh okay! by any chance would I need a certain thing to type in the cmd when downloading, or does it tell me a command that the exe is ready?

**Comment by main-thing** [comment]
It will show the exe in the folder after compiling. Waiting 30 mins would be ok. After that compiling takes 2 mins.
