### ISSUE TITLE
Menu UI

### ISSUE THREAD

**Issue by BlazeMainBcYes** [ShadowMario/FNF-PsychEngine#6598]
### Describe your problem here.

Can someone tell me how to add menu ui without source code plssssssss!!!!!!!!!!!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No (I think)

**Comment by sunnykapakapa** [comment]
idk

**Comment by frantastic24** [comment]
You can't

**Comment by BombasticTom** [comment]
You can only replace some image assets tho

**Comment by Theoyeah** [comment]
Lua don't work in menu

**Comment by BeastlyGhost** [comment]
You can't, the best you could do is just replacing the main assets related to the buttons
