### ISSUE TITLE
helpp

### ISSUE THREAD

**Issue by sunnykapakapa** [ShadowMario/FNF-PsychEngine#6608]
### Describe your problem here.

I went to test the easter eggs from the title screen, and now I'm not able to put the gf back, how do you do it lol? (sorry for my bad english, i'm using the translator)
![shadow mario é br](https://user-images.githubusercontent.com/94994891/157462572-1de63584-fca3-4081-acb1-b88fcd5a5f26.PNG)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
Type "shadow"

**Comment by BeastlyGhost** [comment]
funniest shit i`ve ever seen
