### ISSUE TITLE
Notesplashes.json

### ISSUE THREAD

**Issue by SpookyMan16** [ShadowMario/FNF-PsychEngine#6614]
### What feature do you want to get added on the **base** engine?

Basically a notesplashes json, the json would be called the notesplash type like "DOKINOTES_Assets.png" would be DOKINOTES_Assets.json

the json would contain

X
Y
XML NAME

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by HiroMizuki** [comment]
psych engine has a good amount of json files, idk if jsons for splashes would be cool

**Comment by HiroMizuki** [comment]
and also, making an engine with only jsons is trash, like modding plus 💀

**Comment by ShadowMario** [comment]
> and also, making an engine with only jsons is trash, like modding plus 💀

This

**Comment by SpookyMan16** [comment]
> > and also, making an engine with only jsons is trash, like modding plus 💀
> 
> This

I was just thinking so people's custom note splash offsets aren't a bit funky
