### ISSUE TITLE
can you move the menu buttons with lua?

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#6615]
### Describe your problem here.

![Np8uNro](https://user-images.githubusercontent.com/83985038/157482470-2910b530-72de-4570-860d-857141c9a41d.png)
can you move these buttons with Lua?
I use the precompiled version
I don't use source and i use a little Lua I find online

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by RinZleR121** [comment]
no you can't. lua is used inside the songs.

**Comment by WolfyTail** [comment]
No, you need the source code. Go to _MainMenuState_, and press Ctrl + F. Then search "**spr.screenCenter(X);**".
Write this line underneath:

spr.x -= 300;

And, when you export it they will be on the left. If you wanna move them to the right, change the **-=** by a **+=**, and change the value if you want.
