### ISSUE TITLE
Debug Menu Problem

### ISSUE THREAD

**Issue by TamirPlaysYoutube** [ShadowMario/FNF-PsychEngine#662]
### Debug Menu Problem

![bruhmoment](https://user-images.githubusercontent.com/89785781/139253410-4aa77e89-b2c8-43f3-9c9f-09ba43f0f2b2.png)

**Comment by ShadowMario** [comment]
The file format **Must** be .ogg if you're doing it wrong
```
Songs:
-- mods/
------ songs/
---------- your-song-name/
-------------- Inst.ogg
-------------- Voices.ogg

Charts:
------ data/
---------- your-song-name/
-------------- your-song-name-easy.json
-------------- your-song-name.json
-------------- your-song-name-hard.json
```
Check out if are there any mistakes on your end

**Comment by ShadowMario** [comment]
No reply, i will assume op figured it out.
