### ISSUE TITLE
Dialogue sounds (0.5.2h)

### ISSUE THREAD

**Issue by WolfyTail** [ShadowMario/FNF-PsychEngine#6622]
### Describe your problem here.

Hello. I wanted to test the "Dialogue sound" new function they added to 0.5.2h, but the sound repeats during ALL the lines. Is there anyway to chage the sound for each line or not?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

PlayState.hx, CoolUtil.hx, StoryMenuState.hx, MainMenuState.hx, MenuItem.hx, TitleState.hx, HealthIcon.hx and LoadingState.hx (just for customization).

**Comment by ShadowMario** [comment]
It's just like that on the Editor, should work in-game fine.
