### ISSUE TITLE
Character Editor doesn't let me click on any boxes where i can type

### ISSUE THREAD

**Issue by kiwiquest** [ShadowMario/FNF-PsychEngine#6623]
### Describe your bug here.

so I just finished making a playable character sprite sheet and I was adding it in via character editor, but when I selected the animation dropdown and  clicked on the animation I wanted to change, it doesn't let me click on the XML animation-name OR the animation-name 
(the video below shows me clicking and trying, but nothing happening, while the dropdown works just fine)
https://user-images.githubusercontent.com/93604609/157510278-e618c8ed-bc68-484d-85ea-0f2282c58662.mp4 
weird, I've never experienced this before... well, the recent 0.5.2h update

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yeah, i just transferred all my old mods from my old mods folder to this new updated build lol

**Comment by ShadowMario** [comment]
Reset the camera zoom.

**Comment by DoctorOPlays** [comment]
> Reset the camera zoom.

i am having the same problem as the other guy still.
