### ISSUE TITLE
TextureAtlas doesn't recognize animations

### ISSUE THREAD

**Issue by keanu64github** [ShadowMario/FNF-PsychEngine#6627]
### Describe your bug here.

So, I tried using a TextureAtlas file (FNF HD) and the idle animation shows up, but with (ERROR!) and it only shows the first frame, changing the name does not work.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added the FNF HD TextureAtlas folder to the mods/images folder.

**Comment by DragShot** [comment]
Just how many things did bbpanzu break before he left?

**Comment by keanu64github** [comment]
a LOT

**Comment by keanu64github** [comment]
nvm i didnt know how to check the names 💀
