### ISSUE TITLE
New variable

### ISSUE THREAD

**Issue by WolfyTail** [ShadowMario/FNF-PsychEngine#6630]
### What is your question?

Hello again. I wonder how does the **character.danceEveryNumBeats** work. I think it might be useful for me.

**Comment by frantastic24** [comment]
Replaces `curBeat % 2`, specifically the 2
It tells the game every how many beats the character should dance
1 = every beat (gf, danceLeft/Right chars)
2 = every other beat (default)
Higher values can also be used

**Comment by WolfyTail** [comment]
I'm sorry, but I don't understand where do I use it; Source or Lua?

**Comment by frantastic24** [comment]
It's part of source but can be changed with lua

**Comment by BombasticTom** [comment]
> Replaces `curBeat % 2`, specifically the 2 It tells the game every how many beats the character should dance 1 = every beat (gf, danceLeft/Right chars) 2 = every other beat (default) Higher values can also be used

that's quite good actually
