### ISSUE TITLE
Camera moves really far to the right when I replace BF in the Chart Editor.

### ISSUE THREAD

**Issue by GD-MasterA** [ShadowMario/FNF-PsychEngine#6635]
### Describe your bug here.

When I replace Boyfriend in the chart editor it moves the camera really far to the right when it's Boyfriend's turn (it does this with characters that are already in the game) (I'm using a main week song from my mod to test because I haven't made or charted the extra song also I've only made the player sprites for it anyway)
![image](https://user-images.githubusercontent.com/89449621/157528404-c1847de2-cbb9-4128-a8eb-865fd5325612.png)

### Command Prompt/Terminal logs (if existing)

```bash
None
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a new week, combined The Great Strategy & Gettin' Freaky, Added multiple new characters (the issue is with the player character in the screenshot), Made a custom background for the main menu, I'm working on a bonus week (what that character is for), and I'm going to add more bonus songs(which will be exclusive to freeplay)

**Comment by frantastic24** [comment]
Camera offsets

**Comment by GD-MasterA** [comment]
> 

How do I use camera offsets?

**Comment by frantastic24** [comment]
see the character editor, and your stage json

**Comment by GD-MasterA** [comment]
Thx for the help
