### ISSUE TITLE
Actually working custom settings

### ISSUE THREAD

**Issue by SpookyMan16** [ShadowMario/FNF-PsychEngine#6636]
### What feature do you want to get added on the **base** engine?

Custom settings for mods so they can make it better ig.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by BombasticTom** [comment]
use lua

**Comment by HiroMizuki** [comment]
> use lua

why

**Comment by HiroMizuki** [comment]
and also i think i didn't understood the issue lmao

**Comment by frantastic24** [comment]
Basically they want a hardcoded options menu but for mods/LUAs (they explained it in another issue iirc, so this is a duplicate)
It doesn't sound very beneficial let alone necessary to me but idk
