### ISSUE TITLE
Custom Awards/Achievements

### ISSUE THREAD

**Issue by JdogGamezYT** [ShadowMario/FNF-PsychEngine#6654]
### What is your question?

How do I make a custom achievement in the download build? I see an "achievements" folder in the mods folder, so it's possible, right?

**Comment by BombasticTom** [comment]
they removed the feature

**Comment by JdogGamezYT** [comment]
no, look at the patch notes for 0.5.2h, they added that code back i think

**Comment by frantastic24** [comment]
No they literally got rid of all of that code in the update lol, it wasn't even working before it either

**Comment by JdogGamezYT** [comment]
oh, dang. that sucks.
