### ISSUE TITLE
GF died

### ISSUE THREAD

**Issue by Sackbot77** [ShadowMario/FNF-PsychEngine#6664]
### Describe your bug here.

When I go into a song in PsychEngine-Windows64 0.5.2h, GF doesn't appear, but the song works normally, except that the song takes a long time to load. I know the JSON file works, but I think it's the XML. Anyone know what to do?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't0 edit anything whatsoever.

**Comment by BombasticTom** [comment]
it's not a bug since no one reported this issue
please send a json of your stage
