### ISSUE TITLE
How to put Shaders to FlxSprites?

### ISSUE THREAD

**Issue by Honton129** [ShadowMario/FNF-PsychEngine#6667]
### What is your question?

So the Title says everything
i been trying for a month so
i need to fine a way to put a glitch shader to a flxSprite

**Comment by keanu64github** [comment]
![blend modes](https://user-images.githubusercontent.com/59621417/157706103-9d37a028-00d5-4c23-b64e-7597ef11fad4.png)
Does this help

**Comment by Honton129** [comment]
> ![blend modes](https://user-images.githubusercontent.com/59621417/157706103-9d37a028-00d5-4c23-b64e-7597ef11fad4.png) Does this help

ummm i am looking a way via the source code not with lua

**Comment by keanu64github** [comment]
yeah use the blendModeFromString(‘blend mode’) function
