### ISSUE TITLE
custom achievements

### ISSUE THREAD

**Issue by multicuentadereespaldo** [ShadowMario/FNF-PsychEngine#6673]
![Captura de pantalla (68)](https://user-images.githubusercontent.com/101303887/157576718-b85c94c8-e95e-4c34-8549-d96f243fd620.png)
### Describe your problem here.

How can I add more achievements via code? Every time I put them in the hx, an error comes out
![Captura de pantalla (67)](https://user-images.githubusercontent.com/101303887/157576614-a7f7e81b-ea33-4e07-acea-6088d2d9114e.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by CrusherMods** [comment]
Your missin a **]** somewhere
