### ISSUE TITLE
Why is there no USB support? 

### ISSUE THREAD

**Issue by GamerIsNotEg** [ShadowMario/FNF-PsychEngine#6681]
### What is your question?

Whenever I open the engine while it's in my USB and go into either free play or story mode it crashes so plz add USB support 🙂

**Comment by Theoyeah** [comment]
BRUH
sorry but fnf works in usb for alredy a long time
It is not fnf issue, there something wrong with your device or re-install

**Comment by ShadowMario** [comment]
It does work though lol, i've tried it with a PS2 controller with an USB adapter and works fine

**Comment by keanu64github** [comment]
they mean USB flash drive support lol

**Comment by GamerIsNotEg** [comment]
thanks keanu64github for clearing this statment
