### ISSUE TITLE
how to i click sprite that changes the song

### ISSUE THREAD

**Issue by Den198888** [ShadowMario/FNF-PsychEngine#6682]
### Describe your problem here.

how do i do this i wanted to click a sprite to make the song change but its not working i clicked everything like from vs afton secret song help
![Screenshot_2022-03-10-12-36-23-87_87c2225eebc34d2513fa0e7ad5b93cfc](https://user-images.githubusercontent.com/96397208/157590697-40b1b557-b9c9-4a86-9f85-0b0ddc1dfb90.jpg)
![Screenshot_2022-03-10-12-36-10-52_87c2225eebc34d2513fa0e7ad5b93cfc](https://user-images.githubusercontent.com/96397208/157590700-0cdbc61b-bcb6-45fb-8630-30ebd5042a12.jpg)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

noope

**Comment by frantastic24** [comment]
instead of using the coordinates of your object, find out what coordinates your mouse should be in, and create a coordinate range otherwise the hotbox will be incredibly small

**Comment by Den198888** [comment]
> instead of using the coordinates of your object, find out what coordinates your mouse should be in, and create a coordinate range otherwise the hitbox will be incredibly small

i cant do it, just got an idea to put it in gameover thenif they resapwn it will load the song  
tank for the help again :D
