### ISSUE TITLE
setSoundTime & getSoundTime won't work on inst or vocals

### ISSUE THREAD

**Issue by greentophat** [ShadowMario/FNF-PsychEngine#6683]
### Describe your problem here.

exactly what the title says. i've tried getSoundTime('vocals'); & getSoundTime(''); and they both seem to return 0. i've tried setSoundTime('vocals', [val]); and setSoundTime('', [val]); (in conjunction with setPropertyFromClass('Conductor', 'songPosition', [val]);) and the game completely ignores it

what exactly am i doing wrong here?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
use `getProperty('vocals.time')`

**Comment by greentophat** [comment]
okay but
the setproperty version of it still doesn't work. it still completely ignores 
	setProperty('FlxG.music.time', [val])
and
	setProperty('vocals.time', [val])

**Comment by frantastic24** [comment]
`setPropertyFromClass('flixel.FlxG', 'sound.music.time', value)`

**Comment by greentophat** [comment]
this worked perfectly
thank you so so much for your patience!
