### ISSUE TITLE
flip X on portrait editor

### ISSUE THREAD

**Issue by endorblue** [ShadowMario/FNF-PsychEngine#6699]
### What feature do you want to get added on the **base** engine?

is is possible to add a Flip X button in the portrait editor?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by BombasticTom** [comment]
omg
![image](https://user-images.githubusercontent.com/85838311/157750227-e200e57d-5007-473e-8949-73f18be7e22c.png)

**Comment by GD-MasterA** [comment]
It would be cool if it was added tho.

**Comment by BombasticTom** [comment]
It wouldn't as it would be useless

**Comment by Mastercopper2346** [comment]
This will be helpful for my mod actually
