### ISSUE TITLE
Saving not Working

### ISSUE THREAD

**Issue by starseed123456** [ShadowMario/FNF-PsychEngine#6706]
### Describe your bug here.

So basically I was making events for my chart but when I saved or save anything that you can save it just doesn't save and all of my work is gone I tried doing it like 5 times and it did not even save one single time

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Raltyro** [comment]
Sounds like the issue are from the openfl backend,
also about your work being lost, have you ever tried the load autosave button in the chart editor?

**Comment by EgguMan** [comment]
Is it saving to the right place? I had my psych build located in desktop but it was saving to downloads.
