### ISSUE TITLE
achievements without source code! good but...how?

### ISSUE THREAD

**Issue by Lorigamer87** [ShadowMario/FNF-PsychEngine#6710]
### What feature do you want to get added on the **base** engine?

Hello, this feature has been requested and granted but...how? How do i do an achievement without source code? (Pysch 0.5.2)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
it was removed, do people in this site read

**Comment by BombasticTom** [comment]
> it was removed, do people in this site read

idk
