### ISSUE TITLE
Psych Engine 0.5.2h Breaking and Crashing When I Play My Chart

### ISSUE THREAD

**Issue by VideoVocoding** [ShadowMario/FNF-PsychEngine#6715]
### Describe your bug here.

after i chart my song on the game, it just shows me an error message and then closes. Please fix this.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i only added Shaders.hx and edited Playstate.hx

**Comment by BombasticTom** [comment]
What's the chart's difficulty, and what does it contain? Does it have a lua script?

**Comment by ShadowMario** [comment]
It could be literally everything in the world since you provided me no evidence or anything at all, you also said you edited PlayState.hx so it's very likely that it's your own fault that it crashes.

**Comment by VideoVocoding** [comment]
> What's the chart's difficulty, and what does it contain? Does it have a lua script?

It has 3 Lua Scripts

**Comment by VideoVocoding** [comment]
> It could be literally everything in the world since you provided me no evidence or anything at all, you also said you edited PlayState.hx so it's very likely that it's your own fault that it crashes.

I didn't have time to screenshot it

**Comment by BeastlyGhost** [comment]
> > It could be literally everything in the world since you provided me no evidence or anything at all, you also said you edited PlayState.hx so it's very likely that it's your own fault that it crashes.
> 
> I didn't have time to screenshot it
> 
> And I Placed Code In Playstate For Shaders
> 
> and the error message said about a memory thing

be more specific, what did the error message state exactly?

**Comment by VideoVocoding** [comment]
> > > It could be literally everything in the world since you provided me no evidence or anything at all, you also said you edited PlayState.hx so it's very likely that it's your own fault that it crashes.
> > 
> > 
> > I didn't have time to screenshot it
> > And I Placed Code In Playstate For Shaders
> > and the error message said about a memory thing
> 
> be more specific, what did the error message state exactly?

![inuhyi](https://user-images.githubusercontent.com/96500096/157998170-7518686c-ca61-41da-b2d9-208f049d1517.PNG)

**Comment by machonessiebaby** [comment]
> > > > It could be literally everything in the world since you provided me no evidence or anything at all, you also said you edited PlayState.hx so it's very likely that it's your own fault that it crashes.
> > > 
> > > 
> > > I didn't have time to screenshot it
> > > And I Placed Code In Playstate For Shaders
> > > and the error message said about a memory thing
> > 
> > 
> > be more specific, what did the error message state exactly?
> 
> ![inuhyi](https://user-images.githubusercontent.com/96500096/157998170-7518686c-ca61-41da-b2d9-208f049d1517.PNG)

does this script contain something that have os.
like 
os.exit
if it does delete it this was removed in 5.2
