### ISSUE TITLE
bf skins not working

### ISSUE THREAD

**Issue by FnfWeek** [ShadowMario/FNF-PsychEngine#6726]
### Describe your bug here.

when i enter a bf skin from gamebanana say for instance: erect bf reskin it dosent load and puts in normal bf. this is also with a bunch of others. what am i doing wrong??

### Command Prompt/Terminal logs (if existing)

```bash
it dosent work :(
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by FnfWeek** [comment]
please hhelp

**Comment by KutikiPlayz** [comment]
delete the asset folder in the export and then rebuild the game

**Comment by FnfWeek** [comment]
> delete the asset folder in export and then rebuild the game

i delete assets then download the version then put it back???

**Comment by FnfWeek** [comment]
im on 0.5.2h btw

**Comment by FnfWeek** [comment]
didnt work

**Comment by FnfWeek** [comment]
ill just use 0.5.2 for now until a update happens

**Comment by 3ukn** [comment]
> i delete assets then download the version then put it back???

man

**Comment by FnfWeek** [comment]
its closed because you just put them in: mods-images-characters then go to character editor and reload it.
