### ISSUE TITLE
BF health not going up when hitting note 

### ISSUE THREAD

**Issue by AcePlayzGamesYT** [ShadowMario/FNF-PsychEngine#6740]
### Describe your bug here.

So for some reason the bf health wont go up when hitting notes with botplay or without my version is 0.5.1 and a video is right here: 

https://user-images.githubusercontent.com/94937764/157792335-681e73bd-d03e-4a01-90bd-481a49fac6ae.mp4

1df-49ef-8043-b1b668c04cb7.mp4

https://user-images.githubusercontent.com/94937764/157791993-d3901ffc-afd8-4873-a2f0-559ffc725e54.mp4

 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i added song in the mods folder, added a new week, changed the botplay text and made the background move. If anyone could fix this or make a script that makes the health go up when bf hits a note it would be amazing.

**Comment by main-thing** [comment]
Did you check ganeplay changer in freeplay? (As it can stop you from gaining hp)

**Comment by AcePlayzGamesYT** [comment]
big thanks
i found the health gain multiplier was at 0
