### ISSUE TITLE
C'mon bro

### ISSUE THREAD

**Issue by macksosmart** [ShadowMario/FNF-PsychEngine#6747]
### What needs to be documented?

The wiki hasn't been edited in a hella long time, there needs to be a page explaining softcoded achievements and softcoded difficulties. It's one of the reasons people end up searching for so long only to realize you just needed a folder.

**Comment by crispyboi24** [comment]
You can’t do achievements lmao, those didn’t work but they forgot to remove the folder. But the difficulties explanation is reasonable and should be added

**Comment by tylerandari12** [comment]
You can add soft-coded difficulties? :O

**Comment by Grape-Boy** [comment]
> You can add soft-coded difficulties? :O

#8247

**Comment by ShadowMario** [comment]
You can't add softcoded achievements but i've updated difficulties page.

**Comment by Grape-Boy** [comment]
> You can't add softcoded achievements but i've updated difficulties page.

Thank you, Shadow Mario from Friday Night Funkin' : Psych Engine.

**Comment by PrismLight** [comment]
> > You can't add softcoded achievements but i've updated difficulties page.
> 
> Thank you, Shadow Mario from Friday Night Funkin' : Psych Engine.

He is from a human, actually.
