### ISSUE TITLE
HELP ACHIEVEMENTS NOT WORKING AND LOOPING AND OVER

### ISSUE THREAD

**Issue by Collabvmisgood** [ShadowMario/FNF-PsychEngine#675]
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Source Code

### Show an screenshot/video of your problem.

# Sorry that is Youtube but I can't upload the video here because it is to big for github.
https://youtu.be/xhLI4CPFkH0

**Comment by ShadowMario** [comment]
This is how you trigger an achievement properly
```haxe
#if ACHIEVEMENTS_ALLOWED
var achieve:String = checkForAchievement(['your-achievement-tag']);
if (achieve != null) {
	startAchievement(achieve);
}
#end
```
