### ISSUE TITLE
I'm rewording my previous question.

### ISSUE THREAD

**Issue by WaFl-XIV** [ShadowMario/FNF-PsychEngine#676]
### What is your question?

How do I put BOTH the start and end dialogue in the same lua file?

**Comment by ShadowMario** [comment]
Get the pre-dialogue from the example script on Lua Script API, copy it, rename `onStartCountdown` to `onEndSong`, remove the `and not seenCutscene`, rename `allowCountdown` to `allowEnd`, paste it under the original script.

**Comment by Gavman69** [comment]
![image](https://user-images.githubusercontent.com/85568813/139905561-dbe1a420-6d98-4c9e-ab6d-49d237ea6f33.png)
