### ISSUE TITLE
How do i tween my characters?

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#6766]
### Describe your problem here.

is there a way to make bf and gf tween up and down?
i already have the dad tween i dont know how to make it so then bf tweens

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

sound changes and 2 custom achievements, 4 custom credits

**Comment by machonessiebaby** [comment]
if this is on the wiki
i couldn't find it ;-;

**Comment by acap09** [comment]
i believe the object tag for bf is ``boyfriend``, im not too sure about bf tho
