### ISSUE TITLE
how do i make the opponent strum line have a different skin from the player?

### ISSUE THREAD

**Issue by Fablisothebottle** [ShadowMario/FNF-PsychEngine#6769]
### What is your question?

Im trying to make something like something like bob and bosip where the opponent has a different note skin where the player has the default skin
![unknown](https://user-images.githubusercontent.com/95256692/157890102-181e666e-0824-4cfa-bb30-d016086115f1.png)
.
heres what i mean.

**Comment by AcePlayzGamesYT** [comment]
edit the NOTES_assets file to your png you want and you will have to figure out what one is the opponent and which one is the player side

**Comment by Fablisothebottle** [comment]
uhh what

**Comment by AcePlayzGamesYT** [comment]
https://www.dotpdn.com/files/paint.net.4.3.10.install.anycpu.web.zip for editing the image and 
![image](https://user-images.githubusercontent.com/94937764/157894791-269418b8-0b6c-4559-8b72-eb0951289c3a.png)
for the location of it

**Comment by Fablisothebottle** [comment]
i already have the skin i want.

**Comment by Fablisothebottle** [comment]
i just want to know how to get it working

**Comment by AcePlayzGamesYT** [comment]
make a copy of the note assets you have name it whatever you want but it ends in _assets and then go into your song press 7 go to the songs tab now where it says note texture enter the name of your note but make sure you include the _assets in the end

**Comment by Fablisothebottle** [comment]
but that changes both of them. i only want the opponents arrows to be different

**Comment by Fablisothebottle** [comment]
and for bf's arrows to be normal

**Comment by AcePlayzGamesYT** [comment]
ill have to see
ill reply later

**Comment by Fablisothebottle** [comment]
k

**Comment by AcePlayzGamesYT** [comment]
i will see in my psych

**Comment by Fablisothebottle** [comment]
ight

**Comment by AcePlayzGamesYT** [comment]
ok so with your note assets edit it and you will have to figure out the one that is the opponent arrow and which one is bf arrows
see if that works

**Comment by Fablisothebottle** [comment]
which hx do i go for that?

**Comment by AcePlayzGamesYT** [comment]
its not
i think its still the note assets png file

**Comment by Fablisothebottle** [comment]
i dont think you understand.

**Comment by Fablisothebottle** [comment]
look at the image on my issue.

**Comment by AcePlayzGamesYT** [comment]
ok
ill look at notes hx
and ill tell you if i find anything

**Comment by Fablisothebottle** [comment]
ok.

**Comment by AcePlayzGamesYT** [comment]
yeah idk

**Comment by Fablisothebottle** [comment]
ok ):

**Comment by cherryiguess** [comment]
there are already many discussions about this, just search about it

**Comment by Fablisothebottle** [comment]
all that i found is about kade engine.

**Comment by AcePlayzGamesYT** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/search?q=different+note+skin+fnf
i found this

**Comment by AcePlayzGamesYT** [comment]
you could look at that and change it
or ctrl f in playstate and find the note textures if its in it

**Comment by Fablisothebottle** [comment]
![image](https://user-images.githubusercontent.com/95256692/157905552-e9a289aa-ab5a-4e6f-8caa-2e454ef9f1ca.png)
so replace this here?

**Comment by AcePlayzGamesYT** [comment]
i think so

**Comment by AcePlayzGamesYT** [comment]
pretty sure replace with the name of your note asset png name

**Comment by AcePlayzGamesYT** [comment]
if you need to compile and you dont know how send it to me and i will compile it

**Comment by Fablisothebottle** [comment]
i got this and idk what it means
![image](https://user-images.githubusercontent.com/95256692/157906291-dbdd2e98-b74b-48e3-b3de-9faf838f9cf1.png)

**Comment by AcePlayzGamesYT** [comment]
ok

**Comment by Fablisothebottle** [comment]
i think theres an error with this line
![image](https://user-images.githubusercontent.com/95256692/157906465-65f458a4-c3cc-47a2-9b5c-88fb8519e7fd.png)

**Comment by AcePlayzGamesYT** [comment]
for me line 3986 is 				//}else{

**Comment by Fablisothebottle** [comment]
![image](https://user-images.githubusercontent.com/95256692/157906621-287fcd1e-e629-4a51-b7ef-13e43dc997e6.png)
its maybe this?

**Comment by AcePlayzGamesYT** [comment]
is there not and end } after the {

**Comment by Fablisothebottle** [comment]
it says the same thing

**Comment by AcePlayzGamesYT** [comment]
well
is there not and end } after the {

**Comment by Fablisothebottle** [comment]
![image](https://user-images.githubusercontent.com/95256692/157907379-65b5a6e7-48fe-48c7-a45c-0d121d925079.png)
?

**Comment by AcePlayzGamesYT** [comment]
i gotta eat\
bye for now i hope you figure it out

**Comment by Fablisothebottle** [comment]
ok ):

**Comment by lemz1** [comment]
you can change the note skin via lua just do
```
function onCreatePost()

    for i=0,3 do
        setPropertyFromGroup('opponentStrums', i, 'texture', 'YourNoteAssets')
    end

    for i=0,getProperty('unspawnNotes.length')-1 do
        if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
            setPropertyFromGroup('unspawnNotes', i, 'texture', 'YourNoteAssets')
        end
    end

end
```

**Comment by MC077** [comment]
To anyone who finds this, it does still work with 0.7 onwards but the rgb doesnt apply to the notes
