### ISSUE TITLE
Adding achievements and failing miserably 

### ISSUE THREAD

**Issue by Bludye** [ShadowMario/FNF-PsychEngine#6775]
### Describe your problem here.

so basically, im trying to add hardcoded achievements but they just dont work
![image](https://user-images.githubusercontent.com/92125441/157908562-4d4fc1b4-02ad-4b93-9071-bf8922fb2926.png)
![image](https://user-images.githubusercontent.com/92125441/157908577-3e8fddf0-7e69-42cb-af61-e9343c46819a.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

well i added the things in achievements.hx and playstate

**Comment by Starmapo** [comment]
Did you add the achievement names in the 'checkForAchievement' function? 
![image](https://user-images.githubusercontent.com/85134252/157931527-05252442-81a5-4545-b470-08ef9c542025.png)

**Comment by Bludye** [comment]
im on release 0.5.2 and it changed the code i think

**Comment by Bludye** [comment]
yeah that part of the code isnt there

**Comment by machonessiebaby** [comment]
> yeah that part of the code isnt there

go to 5.2h they reverted the code
