### ISSUE TITLE
Full Screen

### ISSUE THREAD

**Issue by asdvtx** [ShadowMario/FNF-PsychEngine#6787]
### Describe your problem here.

When I press F does not full screen has it been removed?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Note nothing

**Comment by co4ekmc** [comment]
Bro, just start fnf and press alt+enter to exit fullscreen alt+enter

**Comment by asdvtx** [comment]
> Bro, just start fnf and press alt+enter to exit fullscreen alt+enter

sorry i didn't know on did it work when i pressed f this is new to me thank you worked

**Comment by co4ekmc** [comment]
> > Bro, just start fnf and press alt+enter to exit fullscreen alt+enter
> 
> sorry i didn't know on did it work when i pressed f this is new to me thank you worked

And close the issue
