### ISSUE TITLE
2 scripts in one.

### ISSUE THREAD

**Issue by co4ekmc** [ShadowMario/FNF-PsychEngine#6788]
### Describe your problem here.

I want to do cutscene (mp4 video) and when dialogue, i tried many times change code, but i have or only video or only dialogue.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited script.lua in first song.

**Comment by BombasticTom** [comment]
you can find the code on the official discord server

**Comment by Grape-Boy** [comment]
> you can find the code on the official discord server

send link 😁

**Comment by co4ekmc** [comment]
> you can find the code on the official discord server

yeah pls

**Comment by Raltyro** [comment]
I believe you can do a video and then dialogue in just 1 script

**Comment by co4ekmc** [comment]
> I believe you can do a video and then dialogue in just 1 script

But I can't do more whan 1 script lol

**Comment by BombasticTom** [comment]
> > you can find the code on the official discord server
> 
> send link 😁

https://discord.gg/2ka77eMXDv

**Comment by co4ekmc** [comment]
I have script! I find it in server (Not psych engine server) and i find the code! if you want here:
local playDialogue = false;
local playedVideo = false;
function onStartCountdown()
	if not playedVideo and isStoryMode and not seenCutscene then -- Block the first countdown and play video cutscene
		startVideo('your video name here);
		playDialogue = true;
		playedVideo = true;
		return Function_Stop;
	elseif playDialogue then -- Block the second countdown and start a timer of 0.8 seconds to play the dialogue
		playedVideo = true;
		playDialogue = false;
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);

		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('dialogue');
	end
end
