### ISSUE TITLE
Compile bug?

### ISSUE THREAD

**Issue by Fluffedcakes** [ShadowMario/FNF-PsychEngine#679]
### Bug report

I literally can't compile any build of psych engine for some reason? 
![image](https://user-images.githubusercontent.com/90431507/139373748-8ea5ccbd-3354-4ca7-bcbc-23975fab6c83.png)

### Did you edit anything? If so, mention or summarize your changes.

nope, didn't change anything. Vanilla psych engine build

**Comment by ShadowMario** [comment]
These aren't errors, these are ***Warnings***, they don't do anything at all other than tell you that the functions i've used are outdated, and wouldn't stop you from compiling.
