### ISSUE TITLE
Wavy Backgrounds

### ISSUE THREAD

**Issue by randomaccount20** [ShadowMario/FNF-PsychEngine#6798]
### What is your question?

Is there a custom `addGlitchEffect()` or a `addWavyEffect()` shader for psych engine 0.5.2h? I really need them because im putting my 3d backgrounds i made on paint 3d on the engine. please link?

**Comment by Keoiki** [comment]
No, those shaders we're removed before 0.5.2 released.

**Comment by cherryiguess** [comment]
shaders were removed cuz they didnt have permission i think, just get an action build from before they removed the shaders

**Comment by randomaccount20** [comment]
Oh well, guess i gotta switch to the strident engine.
