### ISSUE TITLE
how can I add a new Note type?

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#68]
hi,
I would like to know how I can add a note-type.
I already tried it but it didn't work.

**Comment by ShadowMario** [comment]
I've finished updating the Lua API, try downloading the example at the end of the page:
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API

**Comment by lemz1** [comment]
Oh sorry I forgot to close the issue.
I already fixed it. 
But still thank you.
