### ISSUE TITLE
Unable to change strumline textures with Lua

### ISSUE THREAD

**Issue by YKoF-CALm** [ShadowMario/FNF-PsychEngine#6805]
### Describe your bug here.

I know this is a common topic, that people tried to change the note skins for one side only (i.e. making the opponent and player have different note skins). However, it seems like this doesn't work for strums for the latest build. You can change the incoming note skins just fine, but you can't change the note strum skins with Lua.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing.

**Comment by mayo78** [comment]
ur codes probably bugged mines works just fine 
![image](https://user-images.githubusercontent.com/75394229/158002126-e8eb0160-ee7c-4b74-bf6a-2afa8fc6c42b.png)

**Comment by YKoF-CALm** [comment]
Hmm, I'm not sure where the bug is then. If you don't mind, could you show me the code you used to change the strum lines? I'm not sure if I need to update mine.

**Comment by BombasticTom** [comment]
onCreatePost 💀

**Comment by YKoF-CALm** [comment]
Sorry that I forgot to update this. I stuffed the code into onUpdate and it somehow works.

And yeah, I used onCreatePost initially, but it just doesn't work (as I said, it only works for the notes, but not the strums).

I'll close up this issue, but I'm assuming that shifting the code to onUpdate (or onUpdatePost, both work), is a temporary fix rather than a permanent one, since a new update might change this again.

**Comment by BombasticTom** [comment]
Send your scripts code

**Comment by YKoF-CALm** [comment]
`function changeNoteSkin(skin, player)
    if not (skin == 'vanilla') then -- checks if skin isn't vanilla (basic one)
	    local mustHit = true -- mustHit detects bf's notes
	    if player == 'opponent' then
		    mustHit = false -- if it's false then it's opponent's notes
	    end

	    for i = 0, getProperty(player..'Strums.length')-1 do -- strums from the player parameter (ONLY OPPONENT AND PLAYER)
            setPropertyFromGroup(player..'Strums', i, 'texture', 'notes/'..skin) -- changes the noteskin from parameter skin
        end
        for i = 0, getProperty('unspawnNotes.length')-1 do -- counts all unspawned notes
            if getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' then -- checks if the note is normal note
		        if mustHit and getPropertyFromGroup('unspawnNotes', i, 'mustPress') then -- does a check if it's a player note
                	setPropertyFromGroup('unspawnNotes', i, 'texture', 'notes/'..skin) -- sets player's noteskin
		        elseif not mustHit and not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then -- opponent note check
			        setPropertyFromGroup('unspawnNotes', i, 'texture', 'notes/'..skin) -- sets the opponent note
		        end
            end
        end
        
    end
end

function onUpdate(elapsed)
    if mustHitSection then
        triggerEvent('Camera Follow Pos', 800, 390)
    elseif not mustHitSection then
        triggerEvent('Camera Follow Pos', 500, 390)
    end
    changeNoteSkin('ludinotes', 'opponent')
end`

This is the note skin part of the script. The rest is just camera code and change character positions.
Oh, and the 'ludinotes' part is the note skin.
Lastly, I got the 'changeNoteSkin' function from another issue someone else opened before (although I forgot which one).

**Comment by YKoF-CALm** [comment]
Alright, I did a little more debugging and I found out the reason why.
I had a script that coded in a Ready button like Online VS in there. When I moved the script away, the strums change when I used 'onCreatePost'. I'll try to find a workaround for this. Sorry for the trouble though.

**Comment by BombasticTom** [comment]
> Alright, I did a little more debugging and I found out the reason why. I had a script that coded in a Ready button like Online VS in there. When I moved the script away, the strums change when I used 'onCreatePost'. I'll try to find a workaround for this. Sorry for the trouble though.

the reason the strums don't change the texture is because they aren't spawned yet, your ready script is stopping them from creating onCreatePost, instead, use onCountDownTick

**Comment by YKoF-CALm** [comment]
I see, thanks for the advice.
I've ran into multiple problems with the ready script, though, so I'm putting it aside for now. I'll keep that in mind if I re-add the script.
