### ISSUE TITLE
HOW TO MAKE DAD INFRONT OF BOYFRIEND

### ISSUE THREAD

**Issue by BillyLOLwkwk** [ShadowMario/FNF-PsychEngine#6830]
### Describe your problem here.

how to make dad infront of boyfriend using setObjectOder() ?

i actually dont know how to use this

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

nope....

**Comment by main-thing** [comment]
```
function onCreate()
 setObjectOrder('dadGroup', 2)
end
```
