### ISSUE TITLE
hwo

### ISSUE THREAD

**Issue by fnfbuttomanybugs** [ShadowMario/FNF-PsychEngine#6833]
### What is your question?

how to make when press 7  unlock secret song???????

**Comment by Raltyro** [comment]
what

**Comment by Slimquickhunt** [comment]
Not gonna give guarenteed working code but I'll try writing a script

**Comment by Slimquickhunt** [comment]
if keyPressed('7') then
Loadsong('songname')
end

don't paste this but if this doesn't work loadsong function either doesn't exist or is
a different function

**Comment by Slimquickhunt** [comment]
or
if keyPressed('7') then
loadSong('songname')
end

**Comment by BombasticTom** [comment]
> if keyPressed('7') then Loadsong('songname') end
> 
> don't paste this but if this doesn't work loadsong function either doesn't exist or is a different function

Keypressed is only for mapped keys (aka. note keys, reset key, accept key, etc.)
loadsong requires difficulty

**Comment by BombasticTom** [comment]
Go into discussions, someone already asked about this

**Comment by Slimquickhunt** [comment]
function onUpdate(elapsed)
if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
loadSong('Unfairness', 'Unfairness', true);
end
end

found it

**Comment by Slimquickhunt** [comment]
also is there a page with all functions and keywords for those functions for psych engine?

**Comment by BombasticTom** [comment]
Yeah lua script with all callbacks explained on Lua Script API wiki page

**Comment by Slimquickhunt** [comment]
ah didn't see that only saw the grouping
