### ISSUE TITLE
change downscroll to upscroll in midgame

### ISSUE THREAD

**Issue by WortwL** [ShadowMario/FNF-PsychEngine#6835]
### What is your question?

it is possible to change upscroll to downscroll in midgame/midsong?

if it is help me please

**Comment by Sp4rk1ngc0m3t** [comment]
setPropertyClass('ClientPrefs', 'downScroll', true)
Should work.
You do need to have a basic understanding of how to run it of course.
Just remember to add code to reset the players scroll to what it was before so they don't have to reset it manually!

**Comment by tylerandari12** [comment]
Wouldnt it be `setPropertyFromClass('ClientPrefs', 'downScroll', true)`?
Just curious.

**Comment by Sp4rk1ngc0m3t** [comment]
Weird that I copy pasted it and still got the wrong code and then when I went back to where I got it from it was correct
the code is indeed setPropertyFromClass('ClientPrefs', 'middleScroll', true);

**Comment by WortwL** [comment]
> setPropertyClass('ClientPrefs', 'downScroll', true) Should work. You do need to have a basic understanding of how to run it of course. Just remember to add code to reset the players scroll to what it was before so they don't have to reset it manually!

how to reset the players scroll?

**Comment by Sp4rk1ngc0m3t** [comment]
Record the players scroll type into a variable with "getPropertyFromClass('ClientPrefs', 'downScroll',);"
And set it back using "function onDestroy()" to trigger it

**Comment by WortwL** [comment]
> Record the players scroll type into a variable with "getPropertyFromClass('ClientPrefs', 'downScroll',);" And set it back using "function onDestroy()" to trigger it

like how??

**Comment by Sp4rk1ngc0m3t** [comment]
> like how?? i mean uhh like show me how it works?

I believe if you don't understand then you probably just don't know enough about lua and should go learn about that stuff
I don't think my explanation was bad after all

but here's the full script

originalscroll = getPropertyFromClass('ClientPrefs', 'downScroll',) --records the players scrolltype
setPropertyFromClass('ClientPrefs', 'downScroll', true) --changes the players scroll type


function onDestroy() -- triggers everything below it (until the "end"s) when the song ends
if originalscroll ==  false then --if the player had upscroll originally 
setPropertyFromClass('ClientPrefs', 'downScroll', true) --then set it to upscroll
end
end

**Comment by WortwL** [comment]
ehe sorry. yeah sure am still bad at lua anyways thanks

**Comment by WortwL** [comment]
its not changing the scroll its still same

**Comment by tylerandari12** [comment]
You guys are talking about changing the scroll BEFORE the game but this guys talking DURING the game.

Also optimized scroll script because why not?

`originalscroll = getPropertyFromClass('ClientPrefs', 'downScroll',) --records the players scrolltype
setPropertyFromClass('ClientPrefs', 'downScroll', true) --changes the players scroll type

function onDestroy() -- triggers everything below it (until the "end"s) when the song ends
	setPropertyFromClass('ClientPrefs', 'downScroll', originalscroll) --then set it to the original scroll
end`
