### ISSUE TITLE
Locking weeks Doesn't work

### ISSUE THREAD

**Issue by SaltEFry69** [ShadowMario/FNF-PsychEngine#6837]
### Describe your bug here.

I tried to lock my week but it didn't work

### Are you modding a build from source or with Lua?

Not Lua or Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no I did not

**Comment by SaltEFry69** [comment]
Locking Doesn't work in 0.5.2h

**Comment by BombasticTom** [comment]
Send the json of your week

**Comment by macksosmart** [comment]
if you made the week, it wont lock automatically. if you edited a pre-made week and you havent played it yet, itll be locked
