### ISSUE TITLE
note speed very slow on 0.5.2 and 0.5.2h

### ISSUE THREAD

**Issue by Flubbedsoda** [ShadowMario/FNF-PsychEngine#6841]
### Describe your bug here.

the versions 0.5.2 and 0.5.2h has slow arrows that is making any game play even more difficult i dont know is this a bug or not but its not good please fix this 
here is 0.5.2
https://user-images.githubusercontent.com/101459476/158019416-cfa2a423-2485-4016-8352-942d708da3e8.mov
its basicly the same for 0.5.2h

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i even attempted to change the speed but it didnt work

**Comment by BombasticTom** [comment]
You modified your scroll multiplier 💀

**Comment by Flubbedsoda** [comment]
sorry for the fake issue i thought it was 
but it turns out i was on consistant scroll speed

**Comment by BombasticTom** [comment]
ok now close this issue
