### ISSUE TITLE
Blammed changing color part craches the game in Linux

### ISSUE THREAD

**Issue by Playertrip777** [ShadowMario/FNF-PsychEngine#685]
### Bug report

During the color changing part of the song Blammed, the game crashes.

![blammedbug](https://user-images.githubusercontent.com/90383277/139444660-10ba74dc-1b30-4e00-9a8c-f4e933248b83.png)

### Did you edit anything? If so, mention or summarize your changes.

I did not edit most of the hx files except Main.hx

**Comment by ShadowMario** [comment]
I don't have a linux machine/vm so this sucks

**Comment by MeowcaTheoRange** [comment]
I'll see if I can test this tomorrow or something LOL, wish my Windows-11-sucking ass luck
