### ISSUE TITLE
Bug in Character Editor (after 0.5.2h update)

### ISSUE THREAD

**Issue by HemmyGaming** [ShadowMario/FNF-PsychEngine#6858]
### Describe your bug here.

After last update, when you choosing a character in Character Editor, you has to click again on the field for the character to appear.
There was no such bug before.
https://prnt.sc/83qfIehdOlR8

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

**Comment by HemmyGaming** [comment]
Also, ability to edit data in the fields has disappeared
https://prnt.sc/xzbQG5N0fidb
https://prnt.sc/wOb4Hqk-cFrs

**Comment by keanu64github** [comment]
click r to reset camera zoom it'll fix the text field bug
