### ISSUE TITLE
another compile error (html5)

### ISSUE THREAD

**Issue by snooze789** [ShadowMario/FNF-PsychEngine#6881]
### Describe your bug here.

This is what happens when compiling HTML5

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\[redacted lol]\Downloads\FNF-PsychEngine-0.5.2\FNF-PsychEngine-0.5.2>lime test html5 -release
source/WeekData.hx:11: characters 1-15 : Sys has no field or subtype io

C:\Users\[redacted lol]\Downloads\FNF-PsychEngine-0.5.2\FNF-PsychEngine-0.5.2>pause
Press any key to continue . . .
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

tried to fix WeekData.hx like 50,000 times

**Comment by trayfellow** [comment]
i did find a way to make it compile by removing this duplicate import line but

![image](https://user-images.githubusercontent.com/48515908/158041772-12867786-5550-4bc9-a022-0503973eac4e.png)

when booting up the game in html5 it immediately crashes which im assuming is cause of the easter egg thing

![image](https://user-images.githubusercontent.com/48515908/158041794-50558c91-2b46-46ec-b445-947ff48c80a9.png)

**Comment by KFC-Chicken-1212** [comment]
> 
i removed both of the sys.io things in WeekData.hx but it just freezes on this
![image](https://user-images.githubusercontent.com/89538185/158074324-ec03052d-b85c-40bd-8043-9e429584b38c.png)

**Comment by jbmagination** [comment]
https://github.com/Starmapo/FNF-PsychEngine-Extra/issues/11#issuecomment-1093299756
