### ISSUE TITLE
Full screen

### ISSUE THREAD

**Issue by sky-93** [ShadowMario/FNF-PsychEngine#6889]
### Describe your bug here.

The game is no longer fullscreen when i press f on the title screen

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by kastelpie** [comment]
alt + enter

**Comment by tylerandari12** [comment]
I didnt even kmow this existed :0
