### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by Beginner-codi** [ShadowMario/FNF-PsychEngine#6899]
### Describe your problem here.

Not being able to compile 0.5.2h on linux

![2022-03-12_22-53](https://user-images.githubusercontent.com/81601757/158041455-40ea5d59-dc54-4a14-8d37-de27503a94a1.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No, nothing edited, just wanted to play the game on the latest version

**Comment by McJonnycat** [comment]
use this linc_luajit this will fix it  
commands:  
haxelib remove linc_luajit  
haxelib git linc_luajit https://github.com/McJonnycat/linc_luajit
