### ISSUE TITLE
How do I put light ijn front of characters (making stage)

### ISSUE THREAD

**Issue by JVGamerzbz** [ShadowMario/FNF-PsychEngine#6905]
### Describe your problem here.

Sooooooo, I want light in port or my mods, but how to do light? (also after that I need to do the light that fades)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by BombasticTom** [comment]
how do i do light

**Comment by JVGamerzbz** [comment]
> how do i do light 

what the fuck man ur asking my same question

**Comment by KutikiPlayz** [comment]
find `add(dadGroup);` or one of those and put this after the bf gf and dad shit
```
if(curStage == 'yourstagename') {
	add(thethingyouwantontopofthecharacters)
}
```
