### ISSUE TITLE
Loadsong Function

### ISSUE THREAD

**Issue by Slimquickhunt** [ShadowMario/FNF-PsychEngine#6908]
### What feature do you want to get added on the **base** engine?

a function if it doesn't already exist
a loadsong function

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by lemz1** [comment]
that already exists

**Comment by BombasticTom** [comment]
Use loadSong(song, difficulty) for lua
And you can do callOnLuas in source)

**Comment by Slimquickhunt** [comment]
thank you let me answer someones issue if its not already

**Comment by raxyd** [comment]
is there a haxe function called loadsong?
