### ISSUE TITLE
[Windows] There is no SOUND asset with an ID of...

### ISSUE THREAD

**Issue by reithegoat** [ShadowMario/FNF-PsychEngine#6909]
### Describe your problem here.

After compiling the game and attempting to load the custom week, I get hit with the error message below.
![image](https://user-images.githubusercontent.com/11689362/158047717-77b89011-27c5-4d91-aefd-0826c55e3e37.png)
The Voices.ogg file **is** present in the correct directory. I am at a lost on what to do.

This is what the console outputs.
```
Link: ApplicationMain-debug.exe
source/Discord.hx:17: Discord Client starting...
source/Discord.hx:67: Discord Client initialized
source/Discord.hx:24: Discord Client started.
source/LoadingState.hx:162: Setting asset folder to shared
source/Conductor.hx:75: new BPM map BUDDY []
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 25
Called from ApplicationMain::create ApplicationMain.hx line 130
Called from lime.app.Application::exec lime/app/Application.hx line 150
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 146
Called from lime._internal.backend.native.NativeApplication::handleRenderEvent lime/_internal/backend/native/NativeApplication.hx line 370
Called from lime.app._Event_lime_graphics_RenderContext_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from openfl.display.Stage::__onLimeRender openfl/display/Stage.hx line 1950
Called from openfl.display.Stage::__broadcastEvent openfl/display/Stage.hx line 1166
Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 1399
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 545
Called from flixel.FlxGame::step flixel/FlxGame.hx line 677
Called from flixel.FlxGame::update flixel/FlxGame.hx line 724
Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 637
Called from PlayState::create PlayState.hx line 669
Called from PlayState::generateSong PlayState.hx line 1620
Called from Paths::returnSound Paths.hx line 391
Called from openfl.utils.Assets::getSound openfl/utils/Assets.hx line 266
Called from lime.utils.Assets::getAudioBuffer lime/utils/Assets.hx line 158
Called from lime.utils.Assets::getAsset lime/utils/Assets.hx line 138
Called from lime.utils.Log::error lime/utils/Log.hx line 34
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, drastically modified PlayState.hx, to add a scene for a custom week, and removed all weeks from assets then added a custom one. Project.xml was modified to use a new name for the application and to disable mods and awards.

**Comment by fnfbuttomanybugs** [comment]
update haxe to 4.2.4

**Comment by KutikiPlayz** [comment]
I think it's an issue with disabling mods
I'm currently trying to figure out how to make it work properly while mods are disabled

**Comment by KutikiPlayz** [comment]
> I think it's an issue with disabling mods I'm currently trying to figure out how to make it work properly while mods are disabled

I figured it out
you wanna go to around line 375 in paths.hx and either comment out or delete the `#if MODS_ALLOWED` the `#else` what's under the else and the `#end`
should look something like this
![Screenshot (1290)](https://user-images.githubusercontent.com/73810550/159084420-d5751d80-9ab2-4f05-a99e-420bd9a28448.png)
honestly don't know why they have a mods allowed check there if it works just fine without mods allowed
