### ISSUE TITLE
"YourSongName-Null"

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#6915]
### Describe your bug here.

I tried to load my song "Lump" which only has a normal difficulty. The game crashed saying I needed a "Lump-null.JSON'

I added a Lump-null chart and it operated normally but I dont know if thats intended or not.

### Command Prompt/Terminal logs (if existing)

```bash
None
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing changed. On 0.5.2h by the way.

**Comment by Theoyeah** [comment]
it works on my side
