### ISSUE TITLE
ChangeCharacter event not working.

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#6916]
### Describe your bug here.

The Change Character event is broken on my build (0.5.2h) and instead of changing the character does this.

https://user-images.githubusercontent.com/97060639/158050539-6af6ceac-53cb-4e7c-9f7e-86ed82eac7de.mp4

Yes I am aware my computer is garbage but that's not the point.

### Command Prompt/Terminal logs (if existing)

```bash
None
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing changed.

**Comment by BombasticTom** [comment]
More info
What did you set for changing the character
Reminder: Change character has values from 0 TO 2 (or 1 to 3 i forgor 💀) for characters

**Comment by tylerandari12** [comment]
I first thought you needed to actually type in "BF", "Dad", and "GF" which didn't work. But then I looked up a tutorial and it said what you said. The only problem is 0-3 don't work and produces the result up top. ;-;

**Comment by BombasticTom** [comment]
use 0-2 ;-;
