### ISSUE TITLE
noteSet() functions

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#6917]
### What feature do you want to get added on the **base** engine?

Ok Ill try one more time -,-

Currently, noteTween() type functions are useful but somewhat difficult as it moves relative to where the note is and not to a point on the screen.

So I would like `noteSetX()`, `noteSetY()`, `noteSetAlpha()`, and `noteSetAngle()` if possible.

I thought of this because we already have "Set" values for character and sprite stuff so why not the arrows?

I would add it myself but I don't have a way to compile the source code. ;-;

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by BombasticTom** [comment]
Ever heard of looping trough all spawned notes?

**Comment by tylerandari12** [comment]
Nope

**Comment by tylerandari12** [comment]
My first issue :0
