### ISSUE TITLE
How to make 2 event play at the same time

### ISSUE THREAD

**Issue by TBiscuit1** [ShadowMario/FNF-PsychEngine#693]
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Downloaded Build

### Show an screenshot/video of your problem.

So there isn't 10 ways to say what I want so it might be confusing,
**NO** I'm not saying that I can't place 2 note at the same place (anyway you can)

The real question is: I manage to create a code that allow draining from the opponent using an event
(Btw, the script you (ShadowMario) gave me was little to useless since I had no idea how to use it! (A little explanation on how to use it couldn't hurt next time))

Anyway, here is the script in question
```
function onEvent(name, value1, value2)
	function opponentNoteHit()
		if getProperty('health') > (value2 / 50) and getProperty('health') < (value1 / 50) then
			setProperty('health', (value2 / 50))
		else if  getProperty('health') > (value2 / 50) and getProperty('health') > (value1 / 50) then
			setProperty('health', getProperty('health')-(value1 / 50))
		end
		end
	end
end

-- Value 1 is for drain (Divided by 50 since health stat is 2-0) 
-- Value 2 is for health minimum (Also divided by 50, 0 will cause the player to die, going over 100 will do the same as 100)
```

To be short, if the health is over the minimum and the drain value, drain the player, if the health is over the minimum but lower then the drain value, insert the minimum value (To avoid getting killed because the health is set under 0 for a frame)

Anyway, when you add a new drain event, it replace the old one, which is good, but then, if you play another event it will stop the drain! (Yes you can just place another drain event right after it, but come on, I want things to be clean)

Any solution that doesn't require the Source Code?

Edit : Bonus question, what is the default value when you leave blank?

**Comment by ShadowMario** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/44785097/139520584-e006e46f-dc89-4e13-b9fa-3939d6bd5f28.png)
Are you serious that you need an explanation for this
Also this entire post is confusing as hell i didn't understand what is your exact question

**Comment by ShadowMario** [comment]
No reply, i will assume op figured it out.
