### ISSUE TITLE
No Mods But Are Mods

### ISSUE THREAD

**Issue by UnknownSkid** [ShadowMario/FNF-PsychEngine#6935]
### Describe your problem here.

it says i dont have any mods
but i have and i can play them

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by main-thing** [comment]
Are your mods inside thr mod folder with a seperate folder? Like `mods/YOURMOD` instead of putting them directly in.

**Comment by UnknownSkid** [comment]
Yes
Also it happend when i updated to 0.5.2

niedz., 13 mar 2022, 19:53 użytkownik main-thing ***@***.***>
napisał:

**Comment by main-thing** [comment]
Weird. Never seen it happen before. But do you have a modsList.txt file? In the folder with the assets folder abd mods folder? And to add them back manually in the txt add `NAMEOFTHEMODSFOLDER|1` to turn it on and `NAMEOFTHEMODSFOLDER|0` to turn it off. This may or may not work. As anoter problem is that the mod does not have a pack.json

**Comment by UnknownSkid** [comment]
> Weird. Never seen it happen before. But do you have a modsList.txt file? In the folder with the assets folder and mods folder? And to add them back manually in the txt add `NAMEOFTHEMODSFOLDER|1` to turn it on and `NAMEOFTHEMODSFOLDER|0` to turn it off. This may or may not work. As another problem is that the mod does not have a pack.json

it never said you need an modsList.txt file in the update

**Comment by thedeveloper112206** [comment]
did you try reopening the mods menu?

**Comment by main-thing** [comment]
You could test it. As everytime when my mods load the file gets made. Just try making it manually to see if they appear again in the mods section.
