### ISSUE TITLE
Change faster section 

### ISSUE THREAD

**Issue by asdvtx** [ShadowMario/FNF-PsychEngine#6939]
### What is your question?

How to change faster section (musthitsection)

**Comment by MaybeMaru** [comment]
I dont understand the question, could you add more info on what you are asking?
if you are refering to the lenght of the section then that depends on the bpm of the song

**Comment by asdvtx** [comment]
English is not my language and can explain very badly but here is a picture with my problem, I want him to show the camera to boyfriend for a moment
![Uploading 1649621360648.jpg…]()
