### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by MarsThePlanet** [ShadowMario/FNF-PsychEngine#6946]
### Describe your problem here.

Idk how to make achievements in the mods folder and I would like to know.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not edit anything in the build

> 
BombasticTom
Thank you, I just thought it looked like you can make them with lua in the folder. No need to yell.

**Comment by BombasticTom** [comment]
READ THIS:

YOU **CAN'T** EDIT THE ACHIEVEMENTS FOLDER!

**Comment by tylerandari12** [comment]
I mean technically you can but it wont do anything :>
