### ISSUE TITLE
Wrong Value in Comment on one of the Lua Script

### ISSUE THREAD

**Issue by TBiscuit1** [ShadowMario/FNF-PsychEngine#695]
### What needs to be documented?

[THERE WAS NO ISSUE TEMPLATE THAT WAS FINE SO I TOOK THE ONE THAT WAS THE MOST LOGICAL!]

![image](https://user-images.githubusercontent.com/53101126/139516272-c241e7c4-11e4-49c1-ac49-3d70617abae2.png)
In the Instant Kill Arrow Lua Script, it says 0.23 is the default health gain value, but that would mean each note give 12.5% of your health which is not true! (0.23 * 50)

Don't know the real value, but I'm expecting it's 0.**0**23

**Comment by ShadowMario** [comment]
0.023 yeah
