### ISSUE TITLE
How do you block player from pressing 7 on a certain song?

### ISSUE THREAD

**Issue by the-funky-lad** [ShadowMario/FNF-PsychEngine#6951]
### What is your question?

I want to block the player from the chart editor on a specific song in 4.2, like [this video](https://youtu.be/yNqcbi8esBk?t=10) or [this video](https://youtu.be/5tTqXTnb5qQ?t=509). And I want to do this with source code. If somebody finds a way to do it in lua then I will use it and credit you.

**Comment by BombasticTom** [comment]
remove the script that does it

but if you want to still have access over it when playtesting, just do this:

```
#if debug
		// your script here
#end
```

*took this straight from vanilla's offset editor*

and when you wanna access it, simply before compiling use `lime test windows --debug` (or any other os you use)

**Comment by BombasticTom** [comment]
oh if you wanna have the dave and bambi script just copy from it's source lmao

**Comment by the-funky-lad** [comment]
ok

**Comment by the-funky-lad** [comment]
didnt work
bruuuhhh

**Comment by KutikiPlayz** [comment]
just search for `FlxG.keys.justpressed.SEVEN` (or `FlxG.keys.anyJustPressed(debugKeysChart)` if you're on a newer version) and then copy paste that entire thing into an if statement for if it isn't the song
example:
```
		if(curSong != 'song name') {
			if (FlxG.keys.anyJustPressed(debugKeysChart) && !endingSong && !inCutscene)
			{
				openChartEditor();
			}
		}
```

**Comment by the-funky-lad** [comment]
thanks
