### ISSUE TITLE
Game crashing due to videos/cutscenes

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#6971]
### Describe your bug here.

These are actually _two_ bugs.
I saw, that cutscenes, so, videos that play **_BEFORE_** the actual song/countdown, don't really work at all (anymore).
And if the song has a cutscene assigned to it and you **change** the **window**, and then **back to** the **game**, it will simply crash.

It does not matter if the video (mp4) is in **"assets/videos"** or **"mods/videos"** or **"mods/THEMOD/videos"**. It just will not show up at all.

### **The lua code:**

`local allowCountdown = false
function onStartCountdown()
       if not allowCountdown and isStoryMode and not seenCutscene then --Block the first countdown
                 startVideo('default');
                allowCountdown = true;
		return Function_Stop;
         end
         return Function_Continue;
end`

The video to the example, if needed

https://user-images.githubusercontent.com/76132257/158076488-3df322cf-b65a-4e2c-9bda-1840bbcb4e4f.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a script I found onlkine to a song

**Comment by tylerandari12** [comment]
You need to place the video in `mods/videos` or `mods/THEMOD/videos` and the script itself needs to be in `mods/data/YourSongHere` or `mods/THEMOD/data/YourSongHere` (AKA the first song in your week.)

**Comment by ZeitHeld** [comment]
I know, I did that. But it simply did not work for me, at all.
I can even record it or similar. But then later cuz it is too late rn

**Comment by ZeitHeld** [comment]
OK, never mind, I got it fixed.
It had to do something with my path, as it does not really like a # as it seems
