### ISSUE TITLE
Pixel Dialogue

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#6977]
### What feature do you want to get added on the **base** engine?

Could there be those pixel dialogues, from week 6, get added?
It would be cool to add those, instead of the regular ones, when making a pixelized week with dialogue.

Or even custom text box sprites, which would be even better, with a drop down menu.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by keanu64github** [comment]
It would also be useful for the pixel parts in "FNF Notice Me Senpai: VS Cloud" in the pixel parts right? I mean we already have an antialiasing toggle, it only makes sense to add pixel dialogues.

**Comment by ShadowMario** [comment]
You can do them with Lua if you know what you're doing, i won't add them to the base game.
