### ISSUE TITLE
Fullscreen breaks the quality

### ISSUE THREAD

**Issue by EgguMan** [ShadowMario/FNF-PsychEngine#6985]
### Describe your bug here.

When entering fullscreen the whole game is low quality like i turned it on. This existed in the last build and it is still in 0.52. My monitor is 2560x1440p and is 16:9.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not.

**Comment by ShadowMario** [comment]
Image? I need more information about this.

**Comment by EgguMan** [comment]
> Image? I need more information about this.
@ShadowMario 
I dont know how I could get you one because nvidia doesn't like to capture psych screenshots, but someone on gamebanana suggested that it may be due to FNF being native in 720p, and blowing it up to 2k may be the root of the issue.

**Comment by ZeitHeld** [comment]
screenshot with WIN + PRINT may work?
