### ISSUE TITLE
Any LUA Variables for the Arrows? (Downloaded Build)

### ISSUE THREAD

**Issue by xXWillyPlayzXx** [ShadowMario/FNF-PsychEngine#699]
### What is your question?

I just wanted to know if there were any variables for the arrows since I want to create a custom event that would rotate/move the arrows.

**Comment by ShadowMario** [comment]
`playerStrums` and `opponentStrums`, you can mess with it using `setPropertyFromGroup` or `getPropertyFromGroup`.
There's also noteTweenX, noteTweenY, noteTweenAngle and noteTweenAlpha, check out Lua Script API for more info.
