### ISSUE TITLE
how do i change the sound that makes when pressing - or +

### ISSUE THREAD

**Issue by guizinhomartinez** [ShadowMario/FNF-PsychEngine#6995]
### Describe your problem here.

/\
 |
 |

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Stilic** [comment]
wtf

**Comment by fnfbuttomanybugs** [comment]
- and + is add volume and - is a low volome ist can be changes
-

**Comment by guizinhomartinez** [comment]
i meant like, when you press + or - it plays the scrollmenu sound but even changing it or looking into the source code couldnt find it

**Comment by keanu64github** [comment]
you have to edit HAXE source code not fnf because it's a haxe function, not specific to FNF or Psych Engine.

**Comment by tylerandari12** [comment]
So they cant remove it :0
