### ISSUE TITLE
how do i make custom icons

### ISSUE THREAD

**Issue by fxjisaki** [ShadowMario/FNF-PsychEngine#7]
please im gonna have a panic attack im stressing out so much

**Comment by NadekoJr** [comment]
Basically when making a character let’s say for an example “biro” and ofc you put the character in there. What you do is go the icon’s folder and copy and paste tank man in the icon’s folder and rename that copy of tankman icon called biro and there you go

**Comment by ShadowMario** [comment]
Let's say you've made a character with a head icon set to `bingo`
You should name your icon file `icon-bingo.png`, and it should be 300x150.
Put the file inside `assets/preload/images/icons/` (Recommended if you're going to recompile) OR `mods/images/icons/`.

**Comment by ShadowMario** [comment]
No replies, i will close this.
