### ISSUE TITLE
Cutscene not working

### ISSUE THREAD

**Issue by StablerMarmot** [ShadowMario/FNF-PsychEngine#7001]
### Describe your bug here.

The Cutscene is not working when im using this new 0.5.2 fnf folder. everytime when i put a script.lua on a mods data folder and enter the game then it crashed. i recheck the script.lua see if im miss anything or i didn't put the .mp4 on the video folder but there wasn't and it still crashed. Then my other idea is by using an old version fnf folder and it work for some reason

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i'm not using assest folder. i only used mods folder to create a story

**Comment by StablerMarmot** [comment]
(ZeitHeld)

what path folder ur talking about?

**Comment by ZeitHeld** [comment]
the path, where your Engine/Game is saved in.

Mine e.g. was saved in something like:

`user/#MyGames/FNF Mods/Psych Engine`

And the second folder named was, for some reason, the fault for videos not playing at all

**Comment by StablerMarmot** [comment]
(ZeitHeld)


ok i see. but there wasn't any special character at all. i also try download a new latest fnf folder and put the script.lua and the mp4 on it. and it didn't work. (it crashed) i was wondering if maybe i miss some letter on the script.lua here what's inside the script.lua just let me know if im miss anything or this is just a bug

local allowCountdown = false
function onStartCountdown()
	if not allowCountdown and isStoryMode and not seenCutscene then --Block the first countdown
		startVideo('cutscene1');
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

**Comment by funnypaulmodder** [comment]
im also experiencing the same issue
ive even tried changing the script name to "Videoscript" or something

**Comment by ZeitHeld** [comment]
I use the same script, or kind of code.

Maybe try to copy/"reinstall" the engine to a different folder

**Comment by StablerMarmot** [comment]
(ZeitHeld)

i already done that
