### ISSUE TITLE
Add a specific folder for replacers, instead of putting replacer assets straight to PsychEngine/mods

### ISSUE THREAD

**Issue by RowanSkie** [ShadowMario/FNF-PsychEngine#7002]
### What feature do you want to get added on the **base** engine?

So, there are two main types of mods for FNF if you think about it, **asset replacers** and **new weeks**. 

The current Psych Engine mods folder works great for the latter, but to do the former you have to overwrite it in the main assets folder, which can get tricky especially since some of the asset replacer mods are the best mods out there.

It's just adding the current functionality of replacer menus but to the characters and other UI, like base game BF, GF, DD, Pico, and so forth, without touching the asset folder.

To prevent conflicts, in the main.json file it could be a boolean if it replaces base assets or it's a new week. If it's a new week, no changes to the current modding style really.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by RowanSkie** [comment]
Went to rename the suggestion because after testing, the original idea was already there, except there was no obvious instruction to do so.

**Comment by keanu64github** [comment]
i support this

**Comment by tylerandari12** [comment]
Same

**Comment by RowanSkie** [comment]
This enhancement feature also helps mods like Portable Engine (https://gamebanana.com/mods/357857), by the way.
