### ISSUE TITLE
Shaders in Background

### ISSUE THREAD

**Issue by fnfbuttomanybugs** [ShadowMario/FNF-PsychEngine#7006]
### Describe your problem here.

idk how to make sahders is mds folder

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by keanu64github** [comment]
I am pretty sure they got rid of shaders and achievements in Lua, they just forgot to remove the 'shaders' and 'achievements' folders

**Comment by main-thing** [comment]
> No, those just got added on the new update and in the lua callbacks example that is in the wiki it shows you how to create achievements and detect them, though i dont know about shaders.

Uhhh the achievements one is actually removed. They forgot to remove it from the callbacks script.
