### ISSUE TITLE
add new hit sound

### ISSUE THREAD

**Issue by fnfbuttomanybugs** [ShadowMario/FNF-PsychEngine#7008]
### What feature do you want to get added on the **base** engine?

i need it. Use id if want a custom hit  notr

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by cherryiguess** [comment]
just replace the sound + plus you failed the test
![image](https://user-images.githubusercontent.com/93490646/158224370-ea8b61f8-0eda-4471-8d07-726d0122a53c.png)
