### ISSUE TITLE
Noise at the end of Thorns

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#7018]
### Describe your bug here.

After I played thorns from the story mode, week 6, I heard senpai/thorns noises repeating themselves over and over for a second or two, on the end of the song.

Also can you make it possible, to be able to select not Lua, nor source code?
Just to relate to the "vanilal" psych engine

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only added a health drain script

**Comment by Alberto20108** [comment]
That's normal, it also happens on the vanilla game.

**Comment by EgguMan** [comment]
This happens on my custom song too.

**Comment by PrismLight** [comment]
When the vocals rapidly repeat at the end of a song, it's because the vocals are shorter than the instrumental. If you extend it on Audacity or FL Studio, you should be fine.
