### ISSUE TITLE
Hurt notes breaking on arrow rotation

### ISSUE THREAD

**Issue by Alberto20108** [ShadowMario/FNF-PsychEngine#7028]
### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I charted a song with hurt notes and i made the script that made the arrows rotate.

**Comment by Slimquickhunt** [comment]
i don't think custom notes are supposed to rotate so they just break built in ones don't change that

**Comment by Alberto20108** [comment]
Here's what i mean, look closely

https://user-images.githubusercontent.com/95985177/158398623-0fbed8f9-5e51-4760-9c0f-02c3a98da70e.mp4

It's kinda hard to notice it in that really short video but i had to make it that short because of the 10MB file size limit of GitHub.

**Comment by Slimquickhunt** [comment]
its actully kinda hard not to notice
but psych engine is for modding so that means bugs like this may not be fixed.
because the script either wasn't coded for special notes or it was the engine
