### ISSUE TITLE
i cant hear any sound

### ISSUE THREAD

**Issue by poggrseli** [ShadowMario/FNF-PsychEngine#7030]
### Describe your bug here.

i cant hear any sound while playing

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

uh

**Comment by machonessiebaby** [comment]
press 0 or - or +
psych engine saves volume

**Comment by tylerandari12** [comment]
If its just a black screen but when you press enter a static girlfriend appears, you need to fix your external speaker.
