### ISSUE TITLE
mod not working

### ISSUE THREAD

**Issue by pidev17** [ShadowMario/FNF-PsychEngine#7035]
### Describe your bug here.

bruh why in the hell will my mod not work, i have done everything correctly but ofc it doesnt work

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I literally just added a new note type

**Comment by kingyomoma** [comment]
Does it just crash or...? some type of error pops up? it literally just doesn't appear? give some info
