### ISSUE TITLE
no cached data in 0.5.2h

### ISSUE THREAD

**Issue by thedeveloper112206** [ShadowMario/FNF-PsychEngine#7037]
### Describe your bug here.

i cant find the cached data option in 0.5.2h. idk if its a bug or if shadow mario meant to remove it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by tylerandari12** [comment]
I need to disable this feature as it causes my game to crash and I noticed it was missing too.

The only thing I could think of would be to load an older version of psyche that DOES have this feature and disable it there.

**Comment by Games-player21** [comment]
DOES ANYONE HAVE THE OLD VERSION I DELETED IT BY MISTAKE

**Comment by ShadowMario** [comment]
It is now enabled by default
