### ISSUE TITLE
can someone tell me what I did wrong in this huge block of code?

### ISSUE THREAD

**Issue by Slimquickhunt** [ShadowMario/FNF-PsychEngine#7043]
### Describe your problem here.

barvalue = 0
function onNoteHit()
	setProperty(barvalue, getProperty(barvalue)+ 0.5)
end
function onNoteMiss()
	setProperty(barvalue, getProperty(barvalue)- 0.5)
end
function onUpdate()
	if  getProperty(barvalue) > 5 and getProperty(barvalue) < 10 then
	makeLuaSprite('bar1', bar1, 600, 0);
	addLuaSprite('bar1', true);
	removeLuaSprite('bar0', true);
	removeLuaSprite('bar2', true);
	removeLuaSprite('bar3', true);
end
	if  getProperty(barvalue) > 10 and getProperty(barvalue) < 15 then
	makeLuaSprite('bar2', bar2, 600, 0);
	addLuaSprite('bar2', true);
	removeLuaSprite('bar0', true);
	removeLuaSprite('bar1', true);
	removeLuaSprite('bar3', true);
end
	if  getProperty(barvalue) > 10 and getProperty(barvalue) < 15 then
	makeLuaSprite('bar2', bar2, 600, 0);
	addLuaSprite('bar2', true);
	removeLuaSprite('bar0', true);
	removeLuaSprite('bar1', true);
	removeLuaSprite('bar2', true);
end
	if  getProperty(barvalue) > 20 then
	removeLuaSprite('bar1', true);
	removeLuaSprite('bar2', true);
	removeLuaSprite('bar3', true);
	setProperty('health', health+ 1);
	setProperty('barvalue', 0);
end
	if  getProperty(barvalue) < 0 then
	setProperty('barvalue', 0);
end
	if  getProperty(barvalue) < 5 then
	makeLuaSprite('bar0', bar0, 600, 0);
	addLuaSprite('bar0', true);
	removeLuaSprite('bar1', true);
	removeLuaSprite('bar2', true);
	removeLuaSprite('bar3', true);
	end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by PoleyMagik** [comment]
Line 9; The first if doesn't have a second value and instead uses a comma. Your code still doesn't make much sense but if it is throwing an exception that is why.

**Comment by Slimquickhunt** [comment]
here this is what the code does, it makes a bar that when filled it adds to your health i've fixed line 9 and it still doesn't work
I may not be doing something right here.

**Comment by ZeitHeld** [comment]
maybe try to remove the get&setProperty.
I don't think that you really need it.

Maybe you shoould specify, what exactly does not work. Does the bar not appear at all? Or not get filled up properly?

So, for example:

barvalue = 0
function onNoteHit()
barvalue = barvalue + 0.5
end
function onNoteMiss()
barvalue = barvalue - 0.5
end

**Comment by Slimquickhunt** [comment]
Nothing happens at all for the first answer, and I'll try your code
