### ISSUE TITLE
change character event bug fix

### ISSUE THREAD

**Issue by TamirPlaysYoutube** [ShadowMario/FNF-PsychEngine#705]
### Change Character Event Issue

i've added more than 2 change character events, and saved it, and if i open the song again, it crashes

can you fix the bug

**Comment by FuseIsHere813** [comment]
Use the format when creating a new issue, go to #395 for more Info.

**Comment by TamirPlaysYoutube** [comment]
I know but I need this bug fixed!

**Comment by MeowcaTheoRange** [comment]
> Use the format when creating a new issue, go to #395 for more Info.

The bug fix issue format is broken because of #701 (tried to fix in #704)

**Comment by ShadowMario** [comment]
#591
