### ISSUE TITLE
make the video skip if there is no cut scene

### ISSUE THREAD

**Issue by McJonnycat** [ShadowMario/FNF-PsychEngine#7056]
### What feature do you want to get added on the **base** engine?

what if there was no video and the cut scene on the mods folder or on the assets be skipped and this will be good for us mac ports and other ports as well

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by macksosmart** [comment]
what

**Comment by macksosmart** [comment]
this needs more information, i dont understand what youre talking about

**Comment by thedeveloper112206** [comment]
man failed the test.
