### ISSUE TITLE
Error on Lua Script! "Mods/Data/Splitathon/Script.Lua:30: function arguments expected near ','.

### ISSUE THREAD

**Issue by FuseIsHere813** [ShadowMario/FNF-PsychEngine#706]
### What is your question?

I used the code "removeLuaSprite(tag:String, destroy:Bool = true)" but gives me error.

Here is the screenshot providing it if you need me to anyway.

![2021-10-30](https://user-images.githubusercontent.com/77396398/139524579-66c1786c-71cb-4501-b654-a50822124619.png)

**Comment by 4wdthinks** [comment]
tag:String should be the tag of the sprite. so in your case 'sexualintercourse'
destroy:bool should be just false.

`removeLuaSprite('sexualintercourse', false)`

**Comment by FuseIsHere813** [comment]
aight
