### ISSUE TITLE
Why can I not input capital letter in character editer?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#707]
### What is your question?

Why can I not input capital letter in character editer?
![Snipaste_2021-10-30_18-06-35](https://user-images.githubusercontent.com/13177997/139528744-63fe1a99-28cb-4413-9d57-6dcca5950975.png)

**Comment by 4wdthinks** [comment]
you have to hold shift. i still dont know why they've added caps lock support.

**Comment by ShadowMario** [comment]
Haxe.
