### ISSUE TITLE
animated background(no lua)

### ISSUE THREAD

**Issue by perry389** [ShadowMario/FNF-PsychEngine#7072]
animated background (no lua)

Is there any way to add a moving background by coding? write the code and let me know

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by PrismLight** [comment]
```lua
makeAnimatedLuaSprite(tag:String, image:String, x:Float, y:Float)
addAnimationByPrefix('tag:String', 'animationName:String', 'XMLName:String', FPS:Int, AutoStart:Bool)
addLuaSprite(tag:String, front:Bool = false)
```
It's in the wiki

**Comment by Fridox-lol** [comment]
he said without lua

**Comment by PrismLight** [comment]
Just set the frames part to getsparrowatlas of your xml.
```spriteName.frames = getSparrowAtlas('XMLfile')```
