### ISSUE TITLE
I can't get my week image to work.

### ISSUE THREAD

**Issue by GameGuyOnYT** [ShadowMario/FNF-PsychEngine#7078]
### Describe your problem here.

Hello, I wanted to create a week with the image I attached below, but it always gave this error : "MISSING FILE: images/storymenu/week8.png". My week image file is in a png format and it is in that directory but the game still doesn't accept it.
I need help, I tried searching on Google but couldn't find anything.

**Images:**
1) Week Image: 

![week8](https://user-images.githubusercontent.com/81768350/158420002-ffb59aec-451b-49fa-90a6-fdef6ba42e4c.png)

2) In-game Error: 

![Screenshot (23)](https://user-images.githubusercontent.com/81768350/158420362-cf60cba4-2066-417a-b3c8-c0ea1b7f3eaa.png)
 
3) The file in the folder: 

![Screenshot (24)](https://user-images.githubusercontent.com/81768350/158420858-40fe79c3-5aee-49cc-bbf3-563c2c6da4e9.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by keanu64github** [comment]
Put it in "mods/images/storymenu"

**Comment by PrismLight** [comment]
Put it in the mods folder. Not the assets folder.
And if it still doesn't work try changing the image size to the normal one.

**Comment by GameGuyOnYT** [comment]
Ok, thanks!
