### ISSUE TITLE
Changing Difficulty Game Crash

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#7083]
### Describe your bug here.

try to change the difficulty, while in Charting Mode, will crash the game after a second or two

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ZeitHeld** [comment]
It's still a bug, and avoiding it, won't remove/solve it.
So it is **not** _"fixed"_

**Comment by PrismLight** [comment]
You can't load json files by difficulty, it has to be by song. You can't change the difficulty within charting mode. But you can save it with a custom difficulty.

**Comment by ZeitHeld** [comment]
I mean Charting Mode/Charting State
Not the debug menu.

Charting mdoe appears after you pressed enter during the debug menu, that is used for charting songs

CHOOSE SONG -> PRESS 7 -> PRESS ENTER

**Comment by PrismLight** [comment]
I KNOW IM TELLING U
