### ISSUE TITLE
Can you use .hx files with the .exe build of the engine?

### ISSUE THREAD

**Issue by JavoniCraft** [ShadowMario/FNF-PsychEngine#7086]
### What is your question?

I've been thinking of making custom GUI, but I need to know if I can truly do it.

**Comment by machonessiebaby** [comment]
i dont think you can source code contains all .hx files there is no source folder in exe so i say 90% is a no

**Comment by PrismLight** [comment]
Nope. Your gonna have to somehow edit the ndll file. (which is practically impossible)
I think you would rather learn haxe, wouldn't u.

**Comment by JavoniCraft** [comment]
yea...

**Comment by SpookyMan16** [comment]
> ### What is your question?
> I've been thinking of making custom GUI, but I need to know if I can truly do it.

I might ask for the source folders to be read off of in a source folder

**Comment by 7oltan** [comment]
you cant but you can fork them with lua its easy

**Comment by tylerandari12** [comment]
> you cant but you can fork them with lua its easy

Hold up how?
