### ISSUE TITLE
Title GF freezing, No Music Plays

### ISSUE THREAD

**Issue by TrafficKid** [ShadowMario/FNF-PsychEngine#7093]
### Describe your problem here.

Tried adding custom title music (replacing freaky or whatever the song Is called) nothing plays and GF becomes frozen

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, Replaced the music file

**Comment by thedeveloper112206** [comment]
i think you removed the title music because i did that and the title screen froze

**Comment by facundomax** [comment]
put a youtube video in the background while you run the game, believe me it happens to me too and that solves it xd

**Comment by TrafficKid** [comment]
> i think you removed the title music because i did that and the title screen froze. otherwise idk

well all I did was try replacing the title music..idk why it would freeze
