### ISSUE TITLE
github corrupts download no matter what i do

### ISSUE THREAD

**Issue by exiliph** [ShadowMario/FNF-PsychEngine#71]
everytime i download the source code something to the source code it always corrupts, ive tried different browsers, different devices, and turning off my antivirus but nothing seems to be workin
![WinRAR_ Diagnostic messages 9_17_2021 8_44_23 PM](https://user-images.githubusercontent.com/80222601/133871518-1620e3e9-c11e-47b7-b9a6-2cbd76618b0b.png)

**Comment by ShadowMario** [comment]
Try cloning it with Github Desktop

**Comment by YumDev12** [comment]
could be drive issue if cloning it didn't work
