### ISSUE TITLE
ARCHIEVEMENTS CUSTOM (SOURCE)

### ISSUE THREAD

**Issue by multicuentadereespaldo** [ShadowMario/FNF-PsychEngine#7102]
### Describe your problem here.

How do I add new achievements with source aaaaaa, I already do it but I get an error when compiling

can you explain me?!?!?!?!?!?!?!?11

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Pico8430** [comment]
Check the wiki and make sure you have a stable version of the source code, if you get an error with compiling, it's maybe because you did something wrong on the code.

![achievements hx](https://user-images.githubusercontent.com/91833725/158720193-4851f9c7-a268-4141-aa1f-5e7b70e80eb2.png)

_Achievements.hx_

**Comment by zeadd21g1233** [comment]
i know how to add achviement to psych engine 0.5.2h 

i do code by myself

Credit me

Step 1

go to achivement.hx

go to this line

		["You'll Pay For That...","Beat Week 7 on Hard with no Misses.",	'week7_nomiss',  true],

code code
and paste 
below same code

and change week7

to week8

                     ["You'll Pay For That...","Beat Week 8 on Hard with no Misses.",	'week8_nomiss',  true],

change true to false

             ["You'll Pay For That...","Beat Week 8 on Hard with no Misses.",	'week8_nomiss',  false],

go to playstate

this line

var achieve:String = checkForAchievement

add week8 to list likethis
var achieve:String = checkForAchievement(['week1_nomiss', 'week2_nomiss', 'week3_nomiss', 'week4_nomiss',
'week5_nomiss', 'week6_nomiss', 'week7_nomiss', 'week8_nomiss', 'ur_bad',
'ur_good', 'hype', 'two_keys', 'toastie', 'debugger']);

and go to this line

switch(achievementName)

in cases

add case week8 like this

case 'week1_nomiss' | 'week2_nomiss' | 'week3_nomiss' | 'week4_nomiss' | 'week5_nomiss' | 'week6_nomiss' | 'week7_nomiss' | 'week8_nomiss':

me i made achivment you need to pass crazy diffcuilty

in this tutorial pass week in hard no miss

go to week7 case

and copy

						case 'week7':
						if(achievementName == 'week7_nomiss') unlock = true;
and copy and paste below

like this

								case 'week8':
								 if(achievementName == 'week8_nomiss') unlock = true;

and go to /preload /images /storymenu

add week8 if go week8 up week6 now work  if didnt there problom in nameing

compile game

and make week

name storymenu : anything

customscore :Week 8

photo or week :Week 8

add to game

enjoy you can add more achivement like week9,week10,week11,week12,week13,week14,week15

same thing

lol im bad at tutorials

credit me please 

itake 2 hours to know the code

**Comment by zeadd21g1233** [comment]
this work to 0.5.2 

in 0.5.1

is diffrent

**Comment by zeadd21g1233** [comment]
or 0.5
