### ISSUE TITLE
setProperty('defaultCamZoom') Issues

### ISSUE THREAD

**Issue by StarryTS** [ShadowMario/FNF-PsychEngine#7105]
### Describe your problem here.

I'm trying to run a "_setProperty('defaultCamZoom')_" from Lua code, but the problem is that it never works. **I've used this function before, but it has never worked again after that. Especially after using the latest versions.**
Has there been any changes to this variable? Does it work differently now? I seriously don't know, please lend me some help here.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not applicable.

**Comment by 7oltan** [comment]
setProperty('defaultCamZoom',getProperty('defaultCamZoom')+0.5)

**Comment by StarryTS** [comment]
I know the problem now, I had an empty chart and it only started working when the song had a chart loaded.
