### ISSUE TITLE
A source code folder

### ISSUE THREAD

**Issue by SpookyMan16** [ShadowMario/FNF-PsychEngine#7110]
### What feature do you want to get added on the **base** engine?

The source code folder would have all the .hx files and could be edited without source because the folder is in your psych engine build folder, it would save 3568547686586763896564 years building the game.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.
![fe](https://user-images.githubusercontent.com/89250852/158541052-bb1a0db0-589a-4d5d-927c-542920bc9a13.PNG)

**Comment by Stilic** [comment]
u can't. this will never happen. just **no**.
