### ISSUE TITLE
Replacing Week 6 Dialogue with the Mods Folder doesn't work

### ISSUE THREAD

**Issue by Heropowerbrine** [ShadowMario/FNF-PsychEngine#7113]
### Describe your bug here.

Replacing senpaiDialogue.txt, rosesDialogue.txt and thornsDialogue.txt in the mods folder(inside copies of the song data folders of the three week 6 songs) doesn't work and plays the default dialogue, only works when you replace the txt files on the assets folder instead
I don't wish to replace the ones in the assets folder as I'm just making a copy of Week 6 with the mods folder but with changed assets and dialogues(something similar to a B Sides mods folder port), with the og weeks remaining intact

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I have only worked inside of the mods folder, copying the data folders of Senpai, Roses and Thorns into it and changing what's inside of the dialogue txt files

**Comment by thedeveloper112206** [comment]
you can edit the dialogue through the file

**Comment by ZeitHeld** [comment]
YPu can't in general really any of the OG songs. Maybe if you put it inside of a new week? Maybe then it works

**Comment by keanu64github** [comment]
try using startDialogue('senpaiDialogue', '') . It could work (might not but try it)
