### ISSUE TITLE
Caps Lock in Dialogue Editor

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#7125]
### Describe your bug here.

You are unable to use the caps Lock Button in Dialogue Editor properly. You will always write small letters.
And using shift and Enter will not make a space, but will also not make a new paragraph.
And pressing enter mid text, will make a new paragraph at the end of the String.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Dialogue, duh

**Comment by ShadowMario** [comment]
Haxe issue.
