### ISSUE TITLE
MP4 cutscenes don't work in the new update when not using source code

### ISSUE THREAD

**Issue by funnypaulmodder** [ShadowMario/FNF-PsychEngine#7141]
### Describe your bug here.

Something ive noticed in the new update is how mp4 cutscenes that use a video in the mods folder and the example script from the LUA API don't work anymore and crash the game-
Before you assume i did something wrong, i did the SAME process on an older version (preety sure it's the version exactly before this new one) and the video loaded perfectly
Ive seen one or two mods that did get a cutscene to load on this new version, but in those mods it was coded in the actual source code wich is something i don't know how to to

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added new stuff to the mods folder, changed stuff in assets (only graphics) and deleted the jsons and audio files for the og fnf songs

**Comment by official-ys** [comment]
first thing i'd suggest you do is make sure you do the following

play the week on story mode
make sure the script includes the EXACT same name as the video
make sure the video is in mods -> videos
make sure its the right resolution

for me my cutscenes work perfectly on 0.5.2h

**Comment by ShadowMario** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/44785097/158713991-78353269-979d-4b7d-8744-3fe977ae0060.png)
![Screenshot_2](https://user-images.githubusercontent.com/44785097/158714176-366a1205-e1b8-44bc-b392-45ec73d6a9c1.png)
Wrong

**Comment by official-ys** [comment]
wait are you disagreeing with me or the author of the thread
