### ISSUE TITLE
Function_Stop not working on onEndSong function

### ISSUE THREAD

**Issue by indigoUan** [ShadowMario/FNF-PsychEngine#7142]
### Describe your bug here.

When the onEndSong function is called and returns Function_Stop, the function does not in fact stop.
This is the code that I used in the script, the song still ends like usual.

```
local ended = false

function onEndSong()
    if not ended then
        return Function_Stop
        runTimer("fin", 2)
    end

    ended = true
end
```

I also tried just putting it in the function alone, outside of the if statement, it doesn't work still.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not. This is the GitHub release.

**Comment by indigoUan** [comment]
nevermind I'm fucking dumb

**Comment by poopkit** [comment]
die

**Comment by ImaginationSuperHero528** [comment]
put it in the Function onEndSong() not the if statement.

**Comment by indigoUan** [comment]
already done that, it doesn't work still lmao

**Comment by ImaginationSuperHero528** [comment]
Wait put it in the if again and are you sure it's not continue?

**Comment by indigoUan** [comment]
I'm pretty sure I can read, thank you

also no it doesn't work
