### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by poopkit** [ShadowMario/FNF-PsychEngine#7143]
### Describe your bug here.

![Capture](https://user-images.githubusercontent.com/100816386/158701605-df6ea407-4252-498d-b228-23e99252dfd3.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by kingyomoma** [comment]
Can you send the StoryMenuState.hx file or the specific snippet where the error occurs?
