### ISSUE TITLE
How to let the "score bar" not displayed?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#715]
### What is your question?

How to let the "score bar"(in the red box below) not displayed?
![Snipaste_2021-10-30_23-20-25](https://user-images.githubusercontent.com/13177997/139539273-82cb61c9-a74a-4d99-b765-8e87d2819b5e.png)

**Comment by ShadowMario** [comment]
if you meant the health bar and icons:
on Source code:
```haxe
healthbarBG.visible = false;
healthbar.visible = false;
iconP1.visible = false;
iconP2.visible = false;
```
On Downloaded build:
```lua
setProperty('healthbarBG.visible', false);
setProperty('healthbar.visible', false);
setProperty('iconP1.visible', false);
setProperty('iconP2.visible', false);
```
