### ISSUE TITLE
I don't know if this is stupid but I need to know how to hide the countdown text, or atleast know the object's names in lua.

### ISSUE THREAD

**Issue by ThatGuyOnWhosOnGithub** [ShadowMario/FNF-PsychEngine#7155]
### Describe your problem here.

I need to know how to hide the countdown text, I'm trying to make a custom countdown with lua sprites, and i need to know how to hide the original text.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I replaced the menu bg, and I deleted the vanilla weeks. But I don't think those would cause any issues with what I'm dealing with.

**Comment by BeastlyGhost** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/discussions/3532

there's a script in there for skipping it, have fun

**Comment by AetherLynx** [comment]
use this to prevent countdown from happening
```lua
function onCreate()
      setProperty('skipCountdown', true)
end
```
