### ISSUE TITLE
i can't lime test html5.

### ISSUE THREAD

**Issue by oof-plays-yt** [ShadowMario/FNF-PsychEngine#7168]
### Describe your bug here.

saetar5gyr5yhseryhrtgbrtyhg  bh bhrth

### Command Prompt/Terminal logs (if existing)

```bash
source/WeekData.hx:11: characters 8-19 : You cannot access the sys package while targeting js (for sys.io.File)
source/editors/WeekEditorState.hx:34: characters 8-16 : ... referenced here
source/editors/MasterEditorMenu.hx:119: characters 37-52 : ... referenced here
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited Achievements, AchievementsMenuState and Discord.

**Comment by jbmagination** [comment]
Here's some guidance: https://github.com/Starmapo/FNF-PsychEngine-Extra/issues/11#issuecomment-1093299756
