### ISSUE TITLE
Why does the Lua Script not run?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#717]
### What is your question?

I follow the [Lua Script API](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API) and copy the Example Script below into  `mods\custom_events`.

`Example of Triggering an Event via Lua - Change Characters on Key Press/Precaching characters`

```
function onCreate()
	-- triggered when the lua file is started
	addCharacterToList('pico-player', 'boyfriend');
	addCharacterToList('bf-christmas', 'boyfriend');
	addCharacterToList('bf', 'boyfriend');
	addCharacterToList('dad', 'dad');
	addCharacterToList('parents-christmas', 'dad');
	addCharacterToList('bf-pixel-opponent', 'dad');
end


function onUpdate(elapsed)
	-- start of "update", some variables weren't updated yet
	if keyJustPressed('left') then
		triggerEvent('Change Character', 0, 'bf-christmas');
		triggerEvent('Change Character', 1, 'parents-christmas');
	elseif keyJustPressed('down') then
		triggerEvent('Change Character', 0, 'bf');
		triggerEvent('Change Character', 1, 'dad');
	elseif keyJustPressed('up') then
		triggerEvent('Change Character', 0, 'bf-car');
		triggerEvent('Change Character', 1, 'mom-car');
	elseif keyJustPressed('right') then
		triggerEvent('Change Character', 0, 'pico-player');
		triggerEvent('Change Character', 1, 'bf-pixel-opponent');
	end
end
```
Then I load the game, and press "left/right/down/up",but the characters don't change. Why is it? 
Does any other things need to be done after putting the lua file into `mods\custom_events`?

**Comment by crispyi2** [comment]
The example script you are using is supposed to go in the folder your chart is in. the custom_events folder is used for adding custom events that are used with the events tab in the chart editor.

(hope that made since)

**Comment by zwl1619** [comment]
@crispyi2  How to use the example script? I put it in  `assets\data\song-name`, but it doesn't work.
![Snipaste_2021-10-31_17-32-12](https://user-images.githubusercontent.com/13177997/139576335-e75f19f4-ff2f-4f6b-97e5-2a282d5d010a.png)

**Comment by SrtHero278** [comment]
You want to put that script into the song folder AND rename it to 'script.lua'
