### ISSUE TITLE
My stage doesn't work.

### ISSUE THREAD

**Issue by Fridox-lol** [ShadowMario/FNF-PsychEngine#7175]
### Describe your bug here.

When I try to put my custom bg the game just crash. Here's the code: 

function onCreate()
	-- background shit
	makeLuaSprite('backgroundlol', 'mind/background', -600, -300);
	setScrollFactor('backgroundlol', 0.8, 0.8);

	makeLuaSprite('rock1', 'mind/rock1', -600, -300);
	setScrollFactor('rock1', 0.9, 0.9);

	makeLuaSprite('rock2', 'mind/rock2', -600, -300);
	setScrollFactor('rock2', 0.9, 0.9);

	makeLuaSprite('ground', 'mind/platform', -600, -300);
	setScrollFactor('ground', 1, 1);

	makeLuaSprite('overlay', 'mind/Overlay3', -600, -300);

	addLuaSprite('backgroundlol', false);
	addLuaSprite('rock1', false);
	addLuaSprite('rock2', false);
	addLuaSprite('ground', false);
	addLuaSprite('overlay', true);

	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end

and the json

{
	"directory": "",
	"defaultZoom": 0.9,
	"isPixelStage": false,

	"boyfriend": [770, 100],
	"girlfriend": [400, 130],
	"opponent": [100, 100]
}

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by keanu64github** [comment]
get rid of close(true) cuz it sometimes causes a crash

**Comment by Fridox-lol** [comment]
nvm it's just my build
