### ISSUE TITLE
How to check which arrow the opponent hits

### ISSUE THREAD

**Issue by crispyi2** [ShadowMario/FNF-PsychEngine#718]
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Source Code

### Show an screenshot/video of your problem.

I cannot for the life of me figure out which arrow the opponent hits and it is getting frustrating

If anyone could help that would be fantastic.

**Comment by SrtHero278** [comment]
_**Someone else**_ Made a tabi health drain effect on the source code.

You can go here -> https://github.com/ShadowMario/FNF-PsychEngine/discussions/397#discussioncomment-1498794, copy the code and try modifying that.

**Comment by ShadowMario** [comment]
Line 2254 of PlayState.hx, you can get the note the opponent hit with `daNote.noteData`, 0 = left, 1= down, 2 = up, 3 = right.
