### ISSUE TITLE
getScrollFactor

### ISSUE THREAD

**Issue by mayo78** [ShadowMario/FNF-PsychEngine#7180]
### What feature do you want to get added on the **base** engine?

what if you had getScrollFactor(obj) that would be crazy!!!!!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Rendurse** [comment]
you can always just do `getProperty("sprName.scrollFactor.x")`

**Comment by ShadowMario** [comment]
Lua doesn't support metatable functions for this.
