### ISSUE TITLE
Question with song name detection

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#7187]
### What is your question?

How would i detect a song name LUA
somthing similar to

if not songName = songname then
--thing
end

i dont know if its on the wiki i possibly ran through it or its not possible
Please help
(i need this cuz song alarum is buggy and hides 90% of the ui and wont go back so when its any other song it will show again)

**Comment by mayo78** [comment]
its `songName` not `songname`

**Comment by AetherLynx** [comment]
```lua
function onCreatePost()
     if songName == 'your songs name' then
          --code
     end
end
```

**Comment by machonessiebaby** [comment]
On Thu, Mar 17, 2022 at 7:57 PM Lynx ***@***.***> wrote:

> function onCreatePost()
>      if songName == 'your songs name' then
>           --code
>      endend
>
> —
>
Ok Thanks!

**Comment by keanu64github** [comment]
close the issue lol
