### ISSUE TITLE
how to add a song to freeplay?

### ISSUE THREAD

**Issue by etahb** [ShadowMario/FNF-PsychEngine#719]
### What is your question?

i wanna know how to make a song appear in freeplay

**Comment by MrGrape0** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Adding-a-New-Week#menustory-mode-characters
Read this.

**Comment by ItsCapp** [comment]
On the main menu, press 7
![image](https://user-images.githubusercontent.com/93293747/139556721-3fa57d39-7494-4e95-be0d-33e724e48a8f.png)

It'll bring up this menu, select week editor
![image](https://user-images.githubusercontent.com/93293747/139556728-53290709-509e-47cc-9d10-58fcc2d8ac61.png)

From here, type in your song's name into the box, if you want to have a week, separate songs with commas
![image](https://user-images.githubusercontent.com/93293747/139556752-9f0cbcbf-fe1b-4c72-8234-bd84c566ed59.png)

If you don't want it in story mode, aka it's not a week, check this.
![image](https://user-images.githubusercontent.com/93293747/139556762-6fb11841-adf7-49fa-8fe1-8b4b688bdf51.png)

Press the "Freeplay" button, here you can change the icon on the right and the background colour.

Once you're done, press "Save Week" and save it in the "weeks" folder
![image](https://user-images.githubusercontent.com/93293747/139556790-53f9ad46-3bae-4740-8758-750956e4b427.png)
![image](https://user-images.githubusercontent.com/93293747/139556798-461dcf9d-8288-4319-b5b9-2cc2b1429a5e.png)
