### ISSUE TITLE
Camera Follow Pos?

### ISSUE THREAD

**Issue by MJFNF** [ShadowMario/FNF-PsychEngine#7193]
### Describe your problem here.

How does this even work? any x and y number I put it literally strafes to the left
idk of that event is useless without source or what because I'm confused

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SonicXFire1987** [comment]
try doing 3 digit numbers
750 x
350 y
That was just an example

**Comment by thedeveloper112206** [comment]
i dont think you want to add the x and y to the value. just the number
