### ISSUE TITLE
missing in chart editor removes vocals completely

### ISSUE THREAD

**Issue by Blcbby** [ShadowMario/FNF-PsychEngine#7195]
### Describe your bug here.

if you miss in the chart editor it will remove the vocals completely in that playtest

video showing problem is https://cdn.discordapp.com/attachments/749661635299246182/954211522706571274/2022-03-17_22-51-19.mp4

(little added info im on latest version)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

PlayState.hx to mess around with the accuracy texts, but that's not important

**Comment by ZeitHeld** [comment]
It will probably be readded, if the opponent sings again.

**Comment by Blcbby** [comment]
ive already tested it, and the vocals get completely removed for the entire song, even when the opponent sings again

**Comment by Blcbby** [comment]
found out issue, ghost note was causing a bug
