### ISSUE TITLE
The Achievements are not hiding 

### ISSUE THREAD

**Issue by jigsaw-4277821** [ShadowMario/FNF-PsychEngine#7209]
### Describe your bug here.

The achievements the are needs to be hidden are not like the week7 one and the test song one

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ZeitHeld** [comment]
achievements*

**Comment by Steviegt6** [comment]
> achievements*

That's wild, bro.

**Comment by jigsaw-4277821** [comment]
> 

Fixed now

**Comment by jigsaw-4277821** [comment]
I mean thecalligraphy
