### ISSUE TITLE
blend modes not fully working??

### ISSUE THREAD

**Issue by SirAxolot** [ShadowMario/FNF-PsychEngine#7216]
### Describe your bug here.

I've noticed that some of the blend modes in the modcharting simply aren't working for me, and I'm not sure whether it isn't implemented, is going to be implemented, or if im just stupid.

I've tried to use the overlay blend mode using `setBlendMode('myobject', 'overlay')` but it behaves as if i set the blendmode to normal. 
## I've tested it and it does this for:
- overlay
- alpha
- difference
- erase
- invert
- layer
- hardlight

### this is what it looks like in game when i set it to overlay
![image](https://user-images.githubusercontent.com/89815386/159069827-4ece2ba0-9458-409a-9b7d-9a4c0cbb8e76.png)
### ...vs what it SHOULD look like (edited image using photoshop)
![image](https://user-images.githubusercontent.com/89815386/159070262-6d3871d9-dfd8-47ed-a70b-d7d192590e93.png)

my code below, incase im just stupid and fucked up
>	makeLuaSprite('eff','overlaylol', 0, 0)
>	setGraphicSize('eff',1280,720)
>	setObjectCamera('eff','camhud')
>	updateHitbox('eff')
>	setBlendMode('eff','hardlight')
>	addLuaSprite('eff', false);

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no just lua

**Comment by keanu64github** [comment]
do darken or add

**Comment by SirAxolot** [comment]
> do darken or add

i'm trying to do overlay

**Comment by ShadowMario** [comment]
Haxe
