### ISSUE TITLE
No hit sound in chart editor?

### ISSUE THREAD

**Issue by Zer0PXL** [ShadowMario/FNF-PsychEngine#7223]
### Describe your bug here.

Just wanted to make a chart when I realized the "Play sound (Opponent/Boyfriend)" option doesn't anything..

https://user-images.githubusercontent.com/84981290/159090774-62ae6a65-9118-4505-85cb-7c59a6b89c90.mp4

.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not.

**Comment by ImaginationSuperHero528** [comment]
Make sure the game isn't muted.

**Comment by frantastic24** [comment]
Why does the video have no sound lmao
I got the same issue, and no my game wasn't muted
Maybe check the options menu

**Comment by Zer0PXL** [comment]
> Why does the video have no sound lmao

Idk. There wasn't sound anyway so it doesn't matter.

**Comment by Zer0PXL** [comment]
> Make sure the game isn't muted.

I'm not dumb enough to mute the game while charting.

**Comment by frantastic24** [comment]
found the issue: `hitsound` is supposed to go in `assets/sounds` and not `shared/sounds`

**Comment by Zer0PXL** [comment]
> found the issue: `hitsound` is supposed to go in `assets/sounds` and not `shared/sounds`

That fixed it! Thank you!
(also it's ChartingTick)

**Comment by frantastic24** [comment]
It's hitsound for me, either way it's fixed
