### ISSUE TITLE
shared lua table

### ISSUE THREAD

**Issue by cyn-8** [ShadowMario/FNF-PsychEngine#7225]
### What feature do you want to get added on the **base** engine?

since require is disabled, there is no way to use variables from other scripts

i suggest adding a `shared` table that is synchronous for all scripts running, similar to roblox

this would also make modules like my tweening one easier to implement since you wouldnt have to paste all of the code in every script theyre needed in

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Cherif107** [comment]
they can add some stuff that can track their ips tho

**Comment by cyn-8** [comment]
> they can add some stuff that can track their ips tho

i dont see how thats possible
and if thats possible in lua this feature isnt related to it at all

**Comment by ShadowMario** [comment]
Yeah man that's not how it works
