### ISSUE TITLE
IT says my character has an error but the spritesheet and xml is fine and exported from ADOBE ANIMATE

### ISSUE THREAD

**Issue by FireGZM** [ShadowMario/FNF-PsychEngine#723]
### Describe your bug here.

How do you fix this error ?
![Capture](https://user-images.githubusercontent.com/75147273/139558105-31e6f592-25a3-4573-9a01-a02b4537a298.PNG)

### Are you modding a build from source or with Lua?

- [ ] Lua
- [X] Source

### What is your build target?

- [X] Windows
- [ ] Linux
- [ ] Mac
- [ ] HTML5
- [ ] Flash/Air-based target
- [ ] Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

Edited Credits.HX, TitleState.Hv

**Comment by MeowcaTheoRange** [comment]
Check the format of your XML file, is it in UTF-16?
