### ISSUE TITLE
ANOTHER BUG FOUND. This time with hitsounds.

### ISSUE THREAD

**Issue by Pico8430** [ShadowMario/FNF-PsychEngine#7232]
### Describe your bug here.

So first of all the bug that i founded 2 days ago about the **note colors** was already rare, but you want to know what's even more rare? **_The hitsounds don't work as expected!_**

I was playing the _Last Summer mod_ again, and i quickly got to the song, pressed a note and THIS HAPPENED:

_(WARNING: Sound might be loud.)_

https://user-images.githubusercontent.com/91833725/159098803-8cc2d272-a170-41d0-ba38-ff5d27cd300a.mp4

Now this is super strange with all the lack of bugs found on h0.5.2, this is the first one that its super annoying.

# BEFORE YOU SAY SOMETHING ABOUT MY DEVICE AND STUFF
No, i'm not playing on a shitty pc or my sound it's broken, the game isn't playing the hitsounds correctly, they are just playing over and over again.

And yes, i restarted the song, everything seems working fine now, but this was extremely weird.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by AllMesi** [comment]
are you sure you set the hitsounds to not loop?
