### ISSUE TITLE
Example custom death script doesn't seem to work at all

### ISSUE THREAD

**Issue by IntellectualPotato** [ShadowMario/FNF-PsychEngine#724]
### Describe your bug here.

The example script for a custom death seems to not work, i put it in the song's folder, edited the image paths and stuff and its just not working,
either im a complete idiot (most likely) or it is not working for some odd reason, here is the script if it helps:

function onCreate()
	setPropertyFromClass('GameOverSubstate', 'BFdeath2', 'bf'); --Character json file for the death animation
	setPropertyFromClass('GameOverSubstate', 'fnf_loss_new', 'fnf_loss_sfx'); --put in mods/sounds/
	setPropertyFromClass('GameOverSubstate', 'gameOver-alt', 'gameOver'); --put in mods/music/
	setPropertyFromClass('GameOverSubstate', 'gameOverEnd-alt', 'gameOverEnd'); --put in mods/music/
end

### Are you modding a build from source or with Lua?

- [X] Lua
- [ ] Source

### What is your build target?

- [x] Windows
- [ ] Linux
- [ ] Mac
- [ ] HTML5
- [ ] Flash/Air-based target
- [ ] Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, base version downloaded making in mods folder

**Comment by titopops** [comment]
function onCreate()
setPropertyFromClass('GameOverSubstate', 'BFdeath2'); 
setPropertyFromClass('GameOverSubstate', 'fnf_loss_new');
setPropertyFromClass('GameOverSubstate', 'gameOver-alt');
setPropertyFromClass('GameOverSubstate', 'gameOverEnd-alt'); 
end

try this, might work

**Comment by ShadowMario** [comment]
You changed the variable name instead of the value (Change the last field, not the middle one.)
