### ISSUE TITLE
compile shit 

### ISSUE THREAD

**Issue by Thepipisman** [ShadowMario/FNF-PsychEngine#7245]
### Describe your problem here.

i can compile 5.1 fine but i go to compile 5.2h and i get 
C:/HaxeToolkit/haxe/lib/flixel-ui/2,3,3/flixel/addons/ui/FlxUIPopup.hx:23: characters 13-19 : Field facing has different type than in flixel.IFlxSprite
C:/HaxeToolkit/haxe/lib/flixel/4,10,0/flixel/FlxSprite.hx:1418: characters 2-45 : ... Interface field is defined here
C:/HaxeToolkit/haxe/lib/flixel-ui/2,3,3/flixel/addons/ui/FlxUIPopup.hx:23: characters 13-19 : ... Int should be flixel.util.FlxDirectionFlags

what the fuck is wrong now?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, pure regular source code

**Comment by Theoyeah** [comment]
I've got something similar but only with html5
