### ISSUE TITLE
dialogues

### ISSUE THREAD

**Issue by xNetherex** [ShadowMario/FNF-PsychEngine#725]
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Source Code

### Show an screenshot/video of your problem.

![Captura de pantalla (121)](https://user-images.githubusercontent.com/88166586/139560681-feed8a2b-01d7-45bc-b51b-6ae5f16a4d3e.png
![Captura de pantalla (122)](https://user-images.githubusercontent.com/88166586/139560684-917768a7-cb1b-43f6-9ce2-9983a12818e2.png)

)
 game crashing when trying to load dialogues, everything worked fine until i tried to put dialogues on

**Comment by NetherexFunkin** [comment]
also see the other image linked

**Comment by GMDBrandon** [comment]
bro, you put it in the wrong order or something!

look at week 6's dialogue code, it goes: " 'senpai' | 'roses' | 'thorns'
if im not mistaken, your song order goes like this: " 'i-dont-have-time' | 'its-time' "
but you put " 'its-time' | 'i-dont-have-time' "
am i correct here?

**Comment by MeowcaTheoRange** [comment]
There are supposed to be *two* pipes, not *one* pipe. This `||` is Haxe's `OR` operator.

I suggest you learn about operators before continuing with editing switch cases and if statements.

**Comment by MeowcaTheoRange** [comment]
> bro, you put it in the wrong order or something!
> 
> look at week 6's dialogue code, it goes: " 'senpai' | 'roses' | 'thorns' if im not mistaken, your song order goes like this: " 'i-dont-have-time' | 'its-time' " but you put " 'its-time' | 'i-dont-have-time' "
> 
> am i correct here? or is it supposed to be in that order

Order doesn't matter, because these are `String` types, not `SwagSong` types.

**Comment by MeowcaTheoRange** [comment]
And I *may* have found the problem: your switch has no proper indentation. Use tabs instead of spaces when making cases.

Your case is currently
```haxe
case 'its-time' | 'i-dont.have-time':
   startDialogue(dialogueJson);
```
when it should be
```haxe
case 'its-time' | 'i-dont.have-time':
    startDialogue(dialogueJson);
```

Otherwise, it could be the `.` in between `dont.have`. Replace it with a `-` or the file extension may be mis-interpreted by `Paths` or `OpenFLAssets`.

**Comment by NetherexFunkin** [comment]
> hermano, ¡lo pones en el orden equivocado o algo así!
> 
> mira el código de diálogo de la semana 6, dice: "'senpai' | ' | de rosas 'thorns' si no me equivoco, su orden de canción dice así: " 'i-don't-have-time' | ' its-time' " pero pones " 'its-time' | ' i-don't-have-time' "
> 
> ¿estoy en lo cierto aquí? o se supone que debe estar en ese orden

no, the order is actually correct

**Comment by NetherexFunkin** [comment]
> Y es _posible_ que haya encontrado el problema: su interruptor no tiene una sangría adecuada. Use pestañas en lugar de espacios al hacer casos.
> 
> Su caso es actualmente
> 
> ```hx
> case 'its-time' | 'i-dont.have-time':
>    startDialogue(dialogueJson); // the 's' in this line is currently facing off with the 'e' in the previous line
> ```
> 
> cuando debería ser
> 
> ```hx
> case 'its-time' | 'i-dont.have-time':
>     startDialogue(dialogueJson); // see now how it's lined up with the space?
> ```
> 
> De lo contrario, podría ser el intermedio. Reemplácelo por a o el archivo puede ser malinterpretado por o .`.``dont.have``-``Paths``OpenFLAssets`

i did that, saved the PlayState.hx, and compiled again, but still doesnt working, it just crashes when i try to play the week

**Comment by ShadowMario** [comment]
Looks like it's an issue on your dialogue file or portrait portrait (If you're using any custom one).
Do them witht the Dialogue editors, don't manually edit them, if you was doing that.

**Comment by DevScyu** [comment]
Take a look at #583 and you won't need to edit the source code to add custom dialogue, just stick them in your `mods/data/SONG` folder

**Comment by NetherexFunkin** [comment]
> Take a look at #583 and you won't need to edit the source code to add custom dialogue, just stick them in your `mods/data/SONG` folder

i did that and deleted the source code line the song works fine but none of the dialogues are showing

**Comment by NetherexFunkin** [comment]
> Looks like it's an issue on your dialogue file or portrait portrait (If you're using any custom one). Do them witht the Dialogue editors, don't manually edit them, if you was doing that.

yes i did that with dialogue editor

**Comment by NetherexFunkin** [comment]
also the dialogue file is just called "dialogue"

**Comment by DevScyu** [comment]
> also the dialogue file is just named "dialogue"

dialogue.json?

**Comment by NetherexFunkin** [comment]
> > also the dialogue file is just named "dialogue"
> 
> dialogue.json?

no, just dialogue, but it is a json file

**Comment by NetherexFunkin** [comment]
I need to solve this ASAP because i'm kinda overdue on the coding thing of the mod

**Comment by ShadowMario** [comment]
You're clearly fucking something up because there's the Dialogue Example on Lua Script API and it works perfectly fine.
Again, i do think it's your portraits that are on the wrong folder, making it not get loaded when your song is loaded.

**Comment by PDL2CGamejolt** [comment]
@ShadowMario how do i make the video at the end of the song

**Comment by MeowcaTheoRange** [comment]
> @ShadowMario how do i make the video at the end of the song

@PDL2CGamejolt Please make your own thread. Someone mind closing this one?
