### ISSUE TITLE
scroll flip note

### ISSUE THREAD

**Issue by 0-skid** [ShadowMario/FNF-PsychEngine#7250]
### Describe your problem here.

i tried to make a note that flips your scroll direction when hit but it doesn't work. here's the script:
![Screenshot 2022-03-18 10 39 11 PM](https://user-images.githubusercontent.com/85322671/159105294-04f79c38-8af6-4402-9319-f84cd782cb7b.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by main-thing** [comment]
Did you try testing if changing the value in a normal lua script with `onSongStart()` to test if it even works.

**Comment by kingyomoma** [comment]
instead of doing `downScroll = true` try doing something like this:
`setPropertyFromClass('ClientPrefs', 'downScroll', true)`
same thing for making it upscroll, just make the last value to false

**Comment by kingyomoma** [comment]
> instead of doing `downScroll = true` try doing something like this: `setPropertyFromClass('ClientPrefs', 'downScroll', true)` same thing for making it upscroll, just make the last value to false

Also, use
`if getPropertyFromClass('ClientPrefs', 'downScroll') == true then` instead of `if downScroll == true then`

**Comment by 0-skid** [comment]
> > instead of doing `downScroll = true` try doing something like this: `setPropertyFromClass('ClientPrefs', 'downScroll', true)` same thing for making it upscroll, just make the last value to false
> 
> Also, use `if getPropertyFromClass('ClientPrefs', 'downScroll') == true then` instead of `if downScroll == true then`

the scroll direction flips now, but only after you restart the song, is there a way to change that?

**Comment by ImaginationSuperHero528** [comment]
You can't change between up and down scroll like that.
