### ISSUE TITLE
failed to update resource

### ISSUE THREAD

**Issue by guizinhomartinez** [ShadowMario/FNF-PsychEngine#7253]
### Describe your bug here.

so sometimes when i compile the game it says failed to update resource and the game works fine except the icon of the game doesnt show.

### Command Prompt/Terminal logs (if existing)

```bash
failed to update resource
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by guizinhomartinez** [comment]
btw i redownloaded everything that makes the game compile like haxe, haxeflixel and this stuff

**Comment by AllMesi** [comment]
it just happens its normal
