### ISSUE TITLE
Custom noteskin crashes when hitting enter in the charting menu

### ISSUE THREAD

**Issue by Person615** [ShadowMario/FNF-PsychEngine#7257]
### Describe your problem here.

The preview where the noteskin is shown on the notes in the chart editor works, but the game crashes when I try and load in.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by kingyomoma** [comment]
Can you send the lua file for your notetype

**Comment by tylerandari12** [comment]
Make sure:
1. That you spelled it correctly
2. That it exists
3. That its an actual arrow layout with the strums and not just the notes.
