### ISSUE TITLE
Make Healthbar invisible in Lua

### ISSUE THREAD

**Issue by trippinreal** [ShadowMario/FNF-PsychEngine#7258]
### Describe your problem here.

I'm 90% sure i've done this before, but i've forgotten the code to do it! Unfortunately, the psych api doesn't seem to have it :/

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by PrismLight** [comment]
```setProperty('healthBar.visible', false)```

**Comment by Cherif107** [comment]
u can go to https://github.com/ShadowMario/FNF-PsychEngine/discussions and ask this

**Comment by cherryiguess** [comment]
go to discussions and ask about this, view the source code for the tags of the health bar sprites, also not a real issue

**Comment by kingyomoma** [comment]
function onCreatePost()
	setProperty('botplayTxt.visible', false);
	setProperty('healthBar.alpha', 0);
	setProperty('healthBarBG.alpha', 0);
	setProperty('iconP1.alpha', 0);
	setProperty('iconP2.alpha', 0);
	setProperty('scoreTxt.alpha', 0);
end

**Comment by trippinreal** [comment]
> function onCreatePost() setProperty('healthBar.alpha', 0); setProperty('healthBarBG.alpha', 0); setProperty('iconP1.alpha', 0); setProperty('iconP2.alpha', 0); end

thanks, just forgot to capitalize Bar
