### ISSUE TITLE
Bro the menu adding for a character dont work

### ISSUE THREAD

**Issue by FireGZM** [ShadowMario/FNF-PsychEngine#726]
### Describe your bug here.

I make the spritesheet and da XML and it STILL crashes

### Are you modding a build from source or with Lua?

- [ ] Lua
- [X] Source

### What is your build target?

- [X] Windows
- [ ] Linux
- [ ] Mac
- [ ] HTML5
- [ ] Flash/Air-based target
- [ ] Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

Edited Credits.HX, TitleState.Hv

**Comment by MeowcaTheoRange** [comment]
Duplicate of #723
