### ISSUE TITLE
cant debugprint while dead

### ISSUE THREAD

**Issue by mayo78** [ShadowMario/FNF-PsychEngine#7266]
### Describe your bug here.

you literally cant debugprint if you are dead

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by AllMesi** [comment]
yes thats because debugPrint is coded in PlayState and when you die GameOverState overlays everything
