### ISSUE TITLE
Stage not updating while editing json and lua files

### ISSUE THREAD

**Issue by Cubism-2** [ShadowMario/FNF-PsychEngine#7278]
### Describe your problem here.

I'm working on adding the stage to the engine. From BBPanzu's tutorial, it was said that once you make an edit to the lua or json of your stage, you just restart the song and see the changes. When I did that, it didn't change. I have to recompile it every time. Does anyone know what I did wrong? Thanks.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Itz-Miles** [comment]
You have to edit the ones exported in the export folder of the build target you're using. You can then save the changes you made to the ones in source. 
(ex. `export > release > windows > bin > assets > stages > the stage you want to edit`.  Make sure to go back and save the changes you made to the one in source `assets > preload > stages > stage you edited in export`)

**Comment by tylerandari12** [comment]
> You have to edit the ones exported in the export folder of the build target you're using. You can then save the changes you made to the ones in source. (ex. `export > release > windows > bin > assets > stages > the stage you want to edit`. Make sure to go back and save the changes you made to the one in source `assets > preload > stages > stage you edited in export`)

Hes on Lua tho

**Comment by tylerandari12** [comment]
You just need to restart your game on Lua.
I know its frustrating but its the only way.

**Comment by Itz-Miles** [comment]
Same method with lua. No need to reopen the game.
