### ISSUE TITLE
this code crashes the game when you die

### ISSUE THREAD

**Issue by sethblond** [ShadowMario/FNF-PsychEngine#7282]
### Describe your bug here.

If there is a Lua script with the code.

"function onUpdate(elapsed)
    for i = 0, 4, 1 do
        setPropertyFromGroup("opponentStrums", i, "antialiasing", false)
        setPropertyFromGroup("playerStrums", i, "antialiasing", false)
    end
end"

The game just crashes when you die.
I have no idea what causes this because this code doesn't have anything to do with the game over screen at all.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

this code is in a Lua script

**Comment by kingyomoma** [comment]
try createPost()?
