### ISSUE TITLE
Change Character Event isn't working properly.

### ISSUE THREAD

**Issue by DarkBoi1987** [ShadowMario/FNF-PsychEngine#7287]
### Describe your bug here.

I was working on a mod and chose to add in You Can't Run from Vs. Sonic.EXE to it as a bonus song. To do the part where, in the original song, Boyfriend and Sonic.EXE turned into their pixelated forms, I was wanting to do that in my mod with the change character event, but it won't read what I put in for Value 1, or the character I'm changing. For example, I want to make Girlfriend change to gf-pixel, so I put GF into the Value 1 textbox and gf-pixel in the Value 2 textbox, but it was changing Boyfriend instead of Girlfriend. I did several tests yet none of them worked, so I don't know what to do. I'm running Psych Engine 0.5.2h and all the additions and stuff that I made (i.e. the static notes from Vs. Sonic.EXE) were made using Lua.

What I've tried:
Conjoining the events together to have 3 events go at once
Having each Change Character event be a separate event one after another
Used the names of the .json file that the characters use
Used the names of the characters .json files from the list to show how it works in the chart editor
Used the full names for Boyfriend and Girlfriend

The only character that's getting changed is Boyfriend.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by kingyomoma** [comment]
Try these values for the change character event:
0 - boyfriend
1 - dad
2 - gf
