### ISSUE TITLE
noteTweenDirection has an error.

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [ShadowMario/FNF-PsychEngine#7303]
### Describe your bug here.

Sorry for the duplicate but noteTweenDirection has some issues I even mentioned it in #7228 but it never got noticed by anyone or at least no one said anything. So the Issues are that the notes flying to the strums rotate to and the sustains act weird as they don't rotate causing some glitches.

Here are some videos!
[Recreation is nearly complete!](https://www.youtube.com/watch?v=gcmoFsdWCkU)
[When someone says they'll make a ITG modchart](https://www.youtube.com/watch?v=H-UjcBxG1kU)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No Action download

**Comment by Shadyyam** [comment]
I second this, would really like to do some cool scrolling stuff but the hold note stuff kinda discourages me from using it.
