### ISSUE TITLE
What does directory actually do?

### ISSUE THREAD

**Issue by afeefflox** [ShadowMario/FNF-PsychEngine#7310]
### What is your question?

so I was wondering the directory is kind of useless because idk how does it works ?

**Comment by Theoyeah** [comment]
?
what do you mean

**Comment by afeefflox** [comment]
well, you know where weeks sets that image library stuff

**Comment by leobro1106** [comment]
for example, without typing "yourweekfolder/asset.png" as the directory in the .lua file, you could just have the directory on the stage .json set to "yourweekfolder" and just have the .lua file directory as "asset.png"

**Comment by mayo78** [comment]
its a source thing
