### ISSUE TITLE
custom ending cutscene 

### ISSUE THREAD

**Issue by perry389** [ShadowMario/FNF-PsychEngine#7318]
### Describe your problem here.

Is there any way to add an ending cutscene in Psych Engine?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Fridox-lol** [comment]
h o l i d a y p a r t I I d o e s t h a t
o h y e s y o u a r e o n s o u r c e

**Comment by perry389** [comment]
> `local allowCountdown = false function onEndSong() if not allowCountdown and isStoryMode and not seenCutscene then --Block the first countdown startVideo("testVideo"); allowCountdown = true; return Function_Stop; end return Function_Continue; end`
> 
> 이 스크립트를 컷 장면이 재생될 노래에 넣고 "testVideo"를 노래 이름으로 바꾸십시오. (따옴표를 유지)

It's Lua anyway
