### ISSUE TITLE
Where do the Lua Scripts be put in?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#732]
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Source Code

### Show an screenshot/video of your problem.

I want to use the Example Lua Scripts in the [wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API), Where do they be put in when I use them?

![image](https://user-images.githubusercontent.com/13177997/139585508-53d31fea-5fcd-4f61-9f65-067781cbda4e.png)

**Comment by Collabvmisgood** [comment]
The song chart folder

**Comment by Collabvmisgood** [comment]
In the song chart folder

**Comment by zwl1619** [comment]
@Collabvmisgood Any other things need to be done? I put it in that folder, but it doesn't work.
![Snipaste_2021-10-31_17-32-12](https://user-images.githubusercontent.com/13177997/139590254-e65215d7-2495-4f06-a5bd-d12326dc7f33.png)

**Comment by Collabvmisgood** [comment]
@zwl1619 I hope that you know it but you need to name it: "script.lua"
