### ISSUE TITLE
backgroundSprite

### ISSUE THREAD

**Issue by GWRRailway** [ShadowMario/FNF-PsychEngine#7320]
### What is your question?

In the assets/images files, there's a json file called gfDanceTitle, and within it says "backgroundSprite":"". Does this have a function, a specific image selection or can it be modified with Lua?

**Comment by mayo78** [comment]
if you type an image path in there, the image will show up in the bg of the title screen

**Comment by GWRRailway** [comment]
> if you type an image path in there, the image will show up in the bg of the title screen

so something like images/{name of the bg}

**Comment by Fridox-lol** [comment]
> so something like images/{name of the bg}

no just {name of the bg}
