### ISSUE TITLE
segmentation fault, core dumped (linux)

### ISSUE THREAD

**Issue by Beginner-codi** [ShadowMario/FNF-PsychEngine#7322]
### Describe your bug here.

I have some mods that display this message on the terminal, and when i change certain character file names to non-capital words, it kinda works, but the events dont, i might have some video of what happens.

Also, in every single one of these songs, there is a tiny haxeflixel logo, sometimes as the opponent, or as something else that didnt load somehow.

### Command Prompt/Terminal logs (if existing)

```bash
1047821 segmentation fault (core dumped)  ./PsychEngine (that one stiky mod for fnf)
1061376 segmentation fault (core dumped)  ./PsychEngine (le covered funkdela mod with 2 girls)
1063380 segmentation fault (core dumped)  ./PsychEngine (for every fnf pibby corrupted song)
1065313 segmentation fault (core dumped)  ./PsychEngine (for the whitty definitive mod)

dont know if these are useful though
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No, nothing edited.

**Comment by Stilic** [comment]
your pc maybe sucks
