### ISSUE TITLE
How to add botplay and practice mode on pause menu again

### ISSUE THREAD

**Issue by Beginner-codi** [ShadowMario/FNF-PsychEngine#7323]
### Describe your problem here.

yea, i just want the botplay and practice mode buttons in the pause menu.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

**Comment by Pico8430** [comment]
I already tried it and, it only gives a compiling error, so yeah, i don't think you can.
But you can maybe look up into the **0.4.2 source code** and try to find a way to do so and avoiding errors.

**Comment by tylerandari12** [comment]
Theese two items are now debug exclusive. Press 7 on the song you want botplay for and once the new mwnu loads press enter. You should have deez values again.

**Comment by AidenKP** [comment]
> Theese two items are now debug exclusive. Press 7 on the song you want botplay for and once the new mwnu loads press enter. You should have deez values again.

man are you okay?
you have 3 spelling mistakes
