### ISSUE TITLE
How do I use dialogue boxes frome week 6 instead of the normal onse

### ISSUE THREAD

**Issue by Antony10Modder** [ShadowMario/FNF-PsychEngine#733]
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Source Code

### Show an screenshot/video of your problem.

How do I use pixel dialogue boxes instead of the other ones? I need it for my mod

**Comment by ShadowMario** [comment]
Edit DialogueBox.hx, there's multiple tutorials for this on other engines (Works with Psych too obviously) if you search on YouTube.
