### ISSUE TITLE
Typing a Value on a event Will Result in a C R A S H

### ISSUE THREAD

**Issue by nbonnie2** [ShadowMario/FNF-PsychEngine#7338]
### Describe your bug here.

when i am typing a value, on a event, ummmmm the game crashed. that's all
(V 0.5.2h, Using a built in event)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ManMaster707** [comment]
Need more information, is it an event already on the engine, or is it a custom event? In wich version of psych are you?

**Comment by nbonnie2** [comment]
0.5.2h, something already in the engine.

**Comment by nbonnie2** [comment]
might help

**Comment by blueDev2** [comment]
Is it crashing when you add the event or when the event is called when playing the chart?

**Comment by oof-plays-yt** [comment]
It's when you type in the valuee

**Comment by nbonnie2** [comment]
when i type a value on a even (specificly Blammed Lights) (sorry for late reply)

**Comment by nbonnie2** [comment]
oops, its not happening, its just my computer :P
