### ISSUE TITLE
A way to select multiple notes and change their type. 

### ISSUE THREAD

**Issue by ZGURemixer** [ShadowMario/FNF-PsychEngine#7339]
### What feature do you want to get added on the **base** engine?

A way to select multiple notes and change their type.
Ex: Making all the notes of a song bullet notes. 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by machonessiebaby** [comment]
i would love this

**Comment by ImJustAGuest** [comment]
Winning icons and 6K+ support will never be added. Stop requesting them.

**Comment by cyn-8** [comment]
> Winning icons and 6K+ support will never be added. Stop requesting them.
<img width="720" alt="image" src="https://user-images.githubusercontent.com/58795684/159187022-74e3a8e4-35f9-4f14-912f-a6a9958d6d6e.png">

**Comment by cyn-8** [comment]
also i would like to see this feature ingame
its very useful even though it has fewer use cases

**Comment by ZGURemixer** [comment]
Fewer use cases? I don't use Psych's charter to chart, I use ArrowVortex. This would definitely help a lot with mods that have more than one character on the stage.

**Comment by Mastercopper2346** [comment]
Added.
