### ISSUE TITLE
how make custom lua stage and more (source code)

### ISSUE THREAD

**Issue by alexforges** [ShadowMario/FNF-PsychEngine#7349]
### Describe your problem here.

how add my stage lua and add custom event (like in the mods folder but in source),
pls help,am started making fnf.

### Are you modding a build from source or with Lua?

Source (not withoud moding)

### What is your build target?

Windows x64

**Comment by mayo78** [comment]
https://www.youtube.com/watch?v=iMacxZQMPXs + https://github.com/ShadowMario/FNF-PsychEngine/wiki
