### ISSUE TITLE
how do you make a stage with seperated assets

### ISSUE THREAD

**Issue by olliesus11131** [ShadowMario/FNF-PsychEngine#7354]
### Describe your problem here.

like a stage that is like front.png back.png ext.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by EgguMan** [comment]
What does your stage code look like?

**Comment by Theoyeah** [comment]
like images are separated each other ?

**Comment by EgguMan** [comment]
> like images are separated each other ?

No, like (stage name).lua
