### ISSUE TITLE
The "Add Camera Zoom" event seems to mess with the game

### ISSUE THREAD

**Issue by EgguMan** [ShadowMario/FNF-PsychEngine#7356]
### Describe your bug here.

Placing an add camera zoom, then a note, then editing the event value for placing seems to crash the game

https://user-images.githubusercontent.com/100107293/159185430-ea6e1496-e892-47de-abac-25884bc600cf.mp4

.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by tylerandari12** [comment]
Just dont do those things in that order and you should be fine.

**Comment by bf244** [comment]
just use numbers and if this doesn't work try not putting anything just place the event
