### ISSUE TITLE
Psych Engine replacing sprites with big black boxes, playing the intro off-time, and crashing a ton

### ISSUE THREAD

**Issue by greentophat** [ShadowMario/FNF-PsychEngine#7369]
### Describe your bug here.

Pretty much what the title says.
Psych Engine often replaces sprites with big black boxes and usually crashes when I play a different mod week/song after playing another.
I even downloaded a fresh copy of Psych and put that in a separate folder, with JUST the mod the black-box sprite bug seems to most consistently show up in (if you're curious, it's [Mutilation](https://gamebanana.com/mods/364980))
Also, Psych seems to go through the intro sequence SIGNIFICANTLY off-time. More specifically, the first 'ayy' is heard at 'not associated with' instead of the line right after. This one specifically seems to carry over into quite a couple mods for some reason. (It happened in Vs Aflack Remastered)
So yeah, a LOT of things going wrong. These problems are occurring in a completely official and unmodified build of Psych. I'm not quite sure what happened. It MUST be on my end, cause I don't see ANYONE else with ANY of these problems.

I tried deleting my Psych Engine saves too, but that changed absolutely nothing.

Also neglected to mention that sometimes Girlfriend, or more rarely Boyfriend, are victims of this. The damn vanilla BF and GF sprites are not safe.

Also, a crash SOMETIMES happens:
when i game over while there are black boxes in existence
or
when i retry from such a game over

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by tylerandari12** [comment]
All I could think of is uninstall and reinstall your build.
Other than that its a problem on your end.

**Comment by tylerandari12** [comment]
Also the intro is supposed to be off time.
I know it gets me too.

**Comment by frantastic24** [comment]
not a bug, your pc just sucks ass

**Comment by greentophat** [comment]
> not a bug, your pc just sucks ass

it's an issue that's only been happening lately. shut the fuck up.

**Comment by greentophat** [comment]
well. as it turns out, this was all because i was using an old build by accident.
sorry for getting mad at you, frantastic.
