### ISSUE TITLE
Spinning Window

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#7374]
### Describe your problem here.

Im trying to make code where the game window is spinning in a circle. (Yes, It is possible without source.)

This is the code I havce so far:

![BrokenCode](https://user-images.githubusercontent.com/97060639/159205508-1db247aa-f29d-441b-96ea-01beb5209ac3.PNG)

Theres an empty script in the events folder to use the WindowShake event.

PROBLEM:
Instead of spinning in a circle, the window shimmies from side to side.
Did I do anything wrong?
(Everything else works by the way.)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing changed.

**Comment by mayo78** [comment]
you did the math wrong, the code is right, but the [math](https://www.desmos.com/calculator) is wrong
