### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#7377]
### Describe your problem here.

When I try to compile the source code it says:
Warning : Std.is is deprecated. Use Std.isOfType instead.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Playertrip777** [comment]
Isn't that normal?

**Comment by CrusherMods** [comment]
You can just ignore that
The game will still continue work

**Comment by Mastercopper2346** [comment]
how

**Comment by Mastercopper2346** [comment]
it doesnt give me the engine

**Comment by Playertrip777** [comment]
@Mastercopper2346 Did you find the executable in the export folder?

**Comment by Mastercopper2346** [comment]
yes, and im pretty sure...

**Comment by Playertrip777** [comment]
Show a screenshot

**Comment by Mastercopper2346** [comment]
![bin 3_25_2022 11_03_44 PM](https://user-images.githubusercontent.com/101440491/160227093-20fd138d-e88e-4a8b-afb9-b47e6ecb221d.png)

**Comment by Mastercopper2346** [comment]
It also says:
`Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths`

**Comment by Playertrip777** [comment]
Did you install Visual Studio Community 2019? Is your pc 32-bit or 64-bit?

**Comment by Mastercopper2346** [comment]
what

**Comment by Mastercopper2346** [comment]
my tutorial didnt have that

**Comment by Mastercopper2346** [comment]
link:
https://www.youtube.com/watch?v=c-H0fMSlYho

**Comment by Playertrip777** [comment]
Is your pc 32-bit or 64-bit?

**Comment by Mastercopper2346** [comment]
but my pc is 64 bit

**Comment by Playertrip777** [comment]
Did you install Visual Studio Community 2019?

**Comment by Mastercopper2346** [comment]
I didn't install visual studio, and I did edit.

**Comment by Mastercopper2346** [comment]
but i have backup .hx so its not edited now

**Comment by Mastercopper2346** [comment]
It also says:

` 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths.`

**Comment by Mastercopper2346** [comment]
i might have to go to **downloaded build**

**Comment by Playertrip777** [comment]
> I didn't install visual studio, and I did edit.

That's why psych engine isnt compiling. install it andcuts compoments

**Comment by Mastercopper2346** [comment]
ok
ill watch a different tutorial

**Comment by Playertrip777** [comment]
https://github.com/ninjamuffin99/Funkin
Just follow the instructions from here

**Comment by Mastercopper2346** [comment]
ok im almost done

**Comment by Mastercopper2346** [comment]
i need visual studio to install, run `lime test  windows` or `lime test windows -debug` and im done!

**Comment by Mastercopper2346** [comment]
God it's taking `**SO**` long

**Comment by Mastercopper2346** [comment]
HELLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLP

**Comment by Mastercopper2346** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Playertrip777** [comment]
dude just stop acting like a kid and tell me whats the problem

**Comment by Mastercopper2346** [comment]
its still loading.

**Comment by Mastercopper2346** [comment]
HELPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP

**Comment by Mastercopper2346** [comment]
is been like 40 mins

**Comment by Mastercopper2346** [comment]
ok it worked!

**Comment by Mastercopper2346** [comment]
ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777 ALL HAIL PLAYERTRIP777

**Comment by IndigoDarkw0lf** [comment]
jesus.

**Comment by hayfii** [comment]
> I didn't install visual studio, and I did edit.

![image](https://user-images.githubusercontent.com/94598301/173120446-379e5627-70bb-4f55-9ef9-1f862f906f74.png)
Soooo true, you don't even know how to compile dumbass.

**Comment by Mastercopper2346** [comment]
THAT WAS 3 MONTHS AGO BOZO

**Comment by Mastercopper2346** [comment]
@hayfii SHUT UP AND LOOK AT THE DATES BEFORE SENDING

**Comment by hayfii** [comment]
> THAT WAS 3 MONTHS AGO BOZO

So?

**Comment by Mastercopper2346** [comment]
> So? You still look like a kid imagine cant wait LMAO

Grammar error.

**Comment by hayfii** [comment]
> > So? You still look like a kid imagine cant wait LMAO
> 
> Grammar error.

There isn't any grammar error dummy, it's true that you can't even wait for a response for other people.

**Comment by Mastercopper2346** [comment]
> kid imagine cant wait

wdym by this? It makes no sense

**Comment by Mastercopper2346** [comment]
Weird question… but what’s you gamejolt?

**Comment by hayfii** [comment]
> kid imagine cant wait

Just because I forgot to put "," doesn't mean you can't read it correctly.

**Comment by Mastercopper2346** [comment]
Ok

**Comment by hayfii** [comment]
> Weird question… but what’s you gamejolt?

MasterDickCopper2346

**Comment by Mastercopper2346** [comment]
…

**Comment by Mastercopper2346** [comment]
Why must you be so toxic

**Comment by hayfii** [comment]
> …

I was just joking, I don't have a gamejolt account.

**Comment by Mastercopper2346** [comment]
![D6ADE616-018E-4FB1-A9EB-95DEA3FE7D54](https://user-images.githubusercontent.com/101440491/173192463-186266c4-2c1e-4719-86ae-a1f71be43148.png)

Is this you?

**Comment by hayfii** [comment]
> ![D6ADE616-018E-4FB1-A9EB-95DEA3FE7D54](https://user-images.githubusercontent.com/101440491/173192463-186266c4-2c1e-4719-86ae-a1f71be43148.png)
> 
> Is this you?

What? I don't remember having a gamejolt account?

**Comment by Mastercopper2346** [comment]
Oh ok

**Comment by Mastercopper2346** [comment]
WAIT I LEAKED MY ACCOUNT

**Comment by hayfii** [comment]
> WAIT I LEAKED MY ACCOUNT

?

**Comment by Mastercopper2346** [comment]
I leaked my gamejolt account.

**Comment by Mastercopper2346** [comment]
Which is bad

**Comment by hayfii** [comment]
> Which is bad

Wdym? Your username isn't even there lmao?

**Comment by Mastercopper2346** [comment]
… I mustn’t say anything else

**Comment by Mastercopper2346** [comment]
…Besides I’m leaking it on July 1st

**Comment by DabbinDude316B** [comment]
> …Besides I’m leaking it on July 1st

I meant October

**Comment by IndigoVoidigo** [comment]
what- Why is this still alive?

**Comment by DabbinDude316B** [comment]
Idk
