### ISSUE TITLE
Am i doing something wrong because I can't compile the code

### ISSUE THREAD

**Issue by NoShowMichelle** [ShadowMario/FNF-PsychEngine#7378]
### Describe your problem here.

I keep on getting this error message's when trying to compile the game

source/Achievements.hx:157: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/MainMenuState.hx:66: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:319: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/CharacterEditorState.hx:94: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/DialogueCharacterEditorState.hx:87: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\Michelle\Documents\GitHub\FNF-PsychEngine\export\release\windows\obj>setlocal enabledelayedexpansion
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by kingyomoma** [comment]
Are you using windows 10? if so, you have to download the visual studio code 2022 installer from [here](https://visualstudio.microsoft.com/downloads/), then go to individual components and get these two:
![image](https://user-images.githubusercontent.com/96543290/159293696-db883293-f953-4a30-b79e-7769b0557229.png)
![image](https://user-images.githubusercontent.com/96543290/159294290-e69398fd-a704-4e5e-9943-64f19c89c31d.png) (make sure that number in the parentheses is the same)

If u don't have windows 10 sorry I can't help you

**Comment by Theoyeah** [comment]
NO YOU STUPID DONT USE STUDIO CODE 2022 USE STUDIO 2019 OR IT WONT WORK

**Comment by Fridox-lol** [comment]
deal with it

**Comment by Fridox-lol** [comment]
it still compiles

**Comment by kingyomoma** [comment]
> it still compiles

??? The whole problem is that they **cant** compile it
If you can, good for you

**Comment by oof-plays-yt** [comment]
No, 2022 works just fine.

**Comment by Mastercopper2346** [comment]
use visual studio 2019

**Comment by Mastercopper2346** [comment]
2022 doesnt work

**Comment by Mastercopper2346** [comment]
also, it requires over 8 GB, might wanna clear up some space!
