### ISSUE TITLE
I probably should've asked this one from the beginning lol

### ISSUE THREAD

**Issue by WaFl-XIV** [ShadowMario/FNF-PsychEngine#738]
### What is your question?

How do I make my own Note textures and implement them like how week 6 does it?

**Comment by titopops** [comment]
put your notes image and xml file in mods/images, then go into the chart editor, and type the note image name in the thing, i guess

**Comment by ShadowMario** [comment]
Put your note textures inside mods/images/pixelUI/
Go to your stage .json file and `isPixelStage` to true
