### ISSUE TITLE
Scrolling Backgrounds with Lua

### ISSUE THREAD

**Issue by trippinreal** [ShadowMario/FNF-PsychEngine#7382]
### What is your question?

In its current state, is it possible to implement scrolling backgrounds into stages with only Lua? I know of a pull request that adds this, but it hasn’t been merged, and was wondering if there’s an alternative way of doing so.

**Comment by Murilo3127** [comment]
`function onCreate() --when to start the background

makeLuaSprite('yourSpriteBg', 'yourSpriteBg', -600, -300); 
setScrollFactor('yourSpriteBg', 0.9, 0.9);
	
	makeLuaSprite('yourSpriteBg2', 'yourSpriteBg2', 790, 870); 
	setScrollFactor('yourSpriteBg2', 0.7, 0.7);
	makeAnimatedLuaSprite('hell_glitch', 'hell_glitch', 790, 870) --if the sprite is animated
	luaSpriteAddAnimationByPrefix('hell_glitch', 'hell_glitch', 'hell_glitch', 24, true)--if the sprite is animated



	addLuaSprite('yourSpriteBg', false);
	addLuaSprite('yourSpriteBg2', false);
	
function onUpdate or onStepHit()
doTweenY('yourSpriteBgScroll', 'yourSpriteBg', 100, secondsShit, 'linear')

--not if this code works `

**Comment by ActualeAnEggDog** [comment]
this isnt working
