### ISSUE TITLE
Animated Lua Sprite Not Working

### ISSUE THREAD

**Issue by ExtendedCentral** [ShadowMario/FNF-PsychEngine#739]
### What is your question?

Me and my friend are trying to add an Animated lua sprite but for some reason, when we try and add it it doesn't spawn in game. I did a little testing and when I add the same image without an animation it loads. If anyone knows why this happens please let me know

(The Animation Code Looks like this)

![image](https://user-images.githubusercontent.com/38563378/139602062-f4622a8c-412d-4935-a8d4-0c518196d0d9.png)

**Comment by ShadowMario** [comment]
Looks like the animation with the prefix `thj` doesn't exist in the xml file.
