### ISSUE TITLE
Source Code on Windows 7

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#7392]
### What is your question?

Is it possible to compile the FNF source code on a windows 7 professional?

**Comment by KutikiPlayz** [comment]
I mean
if you're able to install all the haxe shit I don't see why not

**Comment by Steviegt6** [comment]
You can compile both FNF and Psych Engine on WIndows 7, yes.

**Comment by Theoyeah** [comment]
Im sure can even use windows xp

**Comment by tylerandari12** [comment]
I just keep getting error after error so I was questioning it.
