### ISSUE TITLE
(Haxe)How do I add dialouge to the start and end of a song

### ISSUE THREAD

**Issue by djawesomeyt** [ShadowMario/FNF-PsychEngine#741]
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Source Code

### Show an screenshot/video of your problem.

I have search through the threads forever and couldn't find an answer so. How do i have dialouge at the beginning and end of a song(in haxe).

**Comment by ShadowMario** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/44785097/139712304-ecc943fd-84ab-4e58-a5b5-a5ad57ff6f3c.png)
![Screenshot_2](https://user-images.githubusercontent.com/44785097/139712306-9c463845-d334-4802-9534-8fd90cc3a08c.png)

On PlayState.hx

**Comment by djawesomeyt** [comment]
where do i even put the second image like it's not working
