### ISSUE TITLE
Bugged out gf then crash

### ISSUE THREAD

**Issue by Bubby60** [ShadowMario/FNF-PsychEngine#7413]
### Describe your problem here.

for some reason whenever i mod psych engine, i go into a modded song gf shows up as a black square and when i try to do anything else it just crashes

what it shows before crashing:
https://i.imgur.com/iYVzo1O.png

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Theoyeah** [comment]
wtf is psychic ?

**Comment by Bubby60** [comment]
> wtf is psychic ?

Psych Engine, mispelled it. my bad

**Comment by Luc4s-adv** [comment]
your pc is mid range/or low range,Basically any Sprite that goes beyond 4096x4096 in size will turn into a black square,To fix you have to use a sprite with at least 4096 width and height
