### ISSUE TITLE
Make the OG weeks Hideable

### ISSUE THREAD

**Issue by HaruBaru69** [ShadowMario/FNF-PsychEngine#7444]
### What feature do you want to get added on the **base** engine?

what if you made a mod in the mods folder, and went into pack.json or something else and set ShowOGWeeks or something to false? that would be awesome! then I wouldn't have to see the og weeks in story mode and freeplay and only have my mod.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Pico8430** [comment]
Just edit the json week files on assets, bruh.

**Comment by frantastic24** [comment]
this is already possible and has been answered, delete their .json from assets/weeks

**Comment by ProgramerGamerZone** [comment]
> Just edit the json week files on assets, bruh.



> this is already possible and has been answered, delete their .json from assets/weeks

HE SAID IN MODS FOLDER

**Comment by frantastic24** [comment]
they just want to have their mod, which you can already do

**Comment by Cherif107** [comment]
![image](https://user-images.githubusercontent.com/78418245/159792416-068e6117-e467-477a-b254-901371c59954.png)
why

**Comment by HaruBaru69** [comment]
> this is already possible and has been answered, delete their .json from assets/weeks

You can? nice. Thanks for the tip

**Comment by frantastic24** [comment]
now close this
