### ISSUE TITLE
more digits in bpm decimals bruh

### ISSUE THREAD

**Issue by impostor5875** [ShadowMario/FNF-PsychEngine#7450]
### What feature do you want to get added on the **base** engine?

im trying to chart a song with 163.284 bpm but it gets rounded to 163.3 bpm

you'd think it would be fine but later in the song it starts getting offbeat so please add this lol

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by cyn-8** [comment]
i dont think there is any reason *not* to add this feature, since note times are accurate down to the picosecond

**Comment by impostor5875** [comment]
> i dont think there is any reason _not_ to add this feature, since note times are accurate down to the picosecond

bruh i forgot about that lol

**Comment by cyn-8** [comment]
> > i dont think there is any reason _not_ to add this feature, since note times are accurate down to the picosecond
> 
> bruh i forgot about that lol

i said "not" lol

try changing the bpm of the song in the json file itself
if it still rounds then you should keep this open

**Comment by impostor5875** [comment]
> > > i dont think there is any reason _not_ to add this feature, since note times are accurate down to the picosecond
> > 
> > 
> > bruh i forgot about that lol
> 
> i said "not" lol
> 
> try changing the bpm of the song in the json file itself if it still rounds then you should keep this open

sorry im late but i tried that and it still rounded, so i guess i'll keep this open

**Comment by ShadowMario** [comment]
It doesn't get rounded, the chart editor displays it rounded though.
