### ISSUE TITLE
Sprite Stuff

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#7455]
### What needs to be documented?

I keep seeing all these things around in peoples code and on the wiki like "boyfriend.scale.x", "flxl.something.ora"(not an actual value) and I'm wondering "What are these values? I know theyre used with getproperty and setproperty, and I know I can look up some flixel ones. But...

Would there be a way to know which properties/tags belonged to things like the health bar or the time at the top?

**Comment by mayo78** [comment]
https://api.haxeflixel.com/flixel/FlxSprite.html

**Comment by tylerandari12** [comment]
Thats actually good to know...
