### ISSUE TITLE
When Deleting something the engine still thinks it's there

### ISSUE THREAD

**Issue by sans400** [ShadowMario/FNF-PsychEngine#7470]
### Describe your bug here.

I Deleted A Character and character sprite but when i build the game the character is still there but it won't work

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes i edited coolutil.hx, healthicon.hx, and playstate.hx

**Comment by Theoyeah** [comment]
it is normal, the is manually created in the code

**Comment by sans400** [comment]
> it is normal, the is manually created in the code

can i delete that line of code or will an error show up?

**Comment by KutikiPlayz** [comment]
delete the assets folder in the exported game and then rebuild
