### ISSUE TITLE
How do you add dialogue after a cutscene?

### ISSUE THREAD

**Issue by AlansGames** [ShadowMario/FNF-PsychEngine#748]
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Downloaded Build

### Show an screenshot/video of your problem.

Hello, I've tried many times to edit the script in order to play like this: *video cutscene* --> *dialogue*
I've tried different ways, but they either end up in the game softlocking or looping the video infinitely or even starting the countdown while the dialogue is still showing on the screen. Any help would be appreciated. Thanks.

**Comment by ShadowMario** [comment]
```lua
local allowCountdown = false;
local playDialogue = false;
function onStartCountdown()
	-- Block the first countdown and start a timer of 0.8 seconds to play the dialogue
	if not allowCountdown and isStoryMode and not seenCutscene then
		startVideo('videoCutscene');
		allowCountdown = true;
		playDialogue = true;
		return Function_Stop;
	elseif playDialogue then
		runTimer('startDialogue', 0.8);
		playDialogue = false;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('dialogue', 'breakfast');
	end
end
```

**Comment by AlansGames** [comment]
Worked, thanks!

**Comment by Superiron12321** [comment]
> ```lua
> local allowCountdown = false;
> local playDialogue = false;
> function onStartCountdown()
> 	-- Block the first countdown and start a timer of 0.8 seconds to play the dialogue
> 	if not allowCountdown and isStoryMode and not seenCutscene then
> 		startVideo('videoCutscene');
> 		allowCountdown = true;
> 		playDialogue = true;
> 		return Function_Stop;
> 	elseif playDialogue then
> 		setProperty('inCutscene', true);
> 		runTimer('startDialogue', 0.8);
> 		playDialogue = false;
> 		return Function_Stop;
> 	end
> 	return Function_Continue;
> end
> 
> function onTimerCompleted(tag, loops, loopsLeft)
> 	if tag == 'startDialogue' then -- Timer completed, play dialogue
> 		startDialogue('dialogue', 'breakfast');
> 	end
> end
> ```

Is there a way to make dialogue then a cutscene?

**Comment by beepboopbopbep** [comment]
these scripts dont work anymore
