### ISSUE TITLE
Chart Editor Crashing

### ISSUE THREAD

**Issue by randomaccount20** [ShadowMario/FNF-PsychEngine#7485]
### Describe your bug here.

Whenever i load my custom song it sends me a error that says "secrets-null.json", the game then crashes.
Not only that, but for no reason, after a few minutes it randomly freezes and crashes. making me lose my whole process.

Also yes, "secrets" is the fucking name of the song.

### Command Prompt/Terminal logs (if existing)

```bash
i dont fucking use source code and i also dont fucking compile
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

All i did was adding a new song using tutorial charts and charting the shit out of it

**Comment by Theoyeah** [comment]
are you sure that you're using psych 0.5.2h, bc i never got the problem with the -null difficulty

**Comment by Flamgeo** [comment]
dude...THE SAME THING IS HAPPENING TO ME
ill just use a older engine

**Comment by JaceDankhover** [comment]
same thing here, the only way I can fix this is by creating a copy of the current saved chart and adding '-null' as the difficulty.

**Comment by maxilamano** [comment]
I can confirm this happens in 0.5.2h when trying to load a song in the chart editor entering from the main menu.
