### ISSUE TITLE
Question: How to add animations to custom notes

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#75]
Hi again,
I made a custom note but when I press there is no animation
I have made animations in the png.
I also wrote the animations in the xml.
Do I need to change something in the code so the note plays the animations when it is hit.

**Comment by ShadowMario** [comment]
Please elaborate, does it happens to all notes or just specific ones?

**Comment by lemz1** [comment]
if you mean by all notes the left,down,up,right arrow of my custom note-type then yes.
If you mean by all notes the note types then only the custom note-type I added

**Comment by lemz1** [comment]
These notes are supposed to have animations 

![HEALNOTE_assets](https://user-images.githubusercontent.com/87707926/133897629-9766c5be-4035-4c5b-bc9f-20b27eb12efd.png)
Here is the xml file
[HEALNOTE_assets.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/7190403/HEALNOTE_assets.txt)

**Comment by ShadowMario** [comment]
I didn't understand exactly what are you trying to do... Is that a Custom Note Type? If so, Custom Note Types can't change the Strum/Receptor texture.

**Comment by lemz1** [comment]
oh ok
