### ISSUE TITLE
Hitsounds

### ISSUE THREAD

**Issue by SpookyMan16** [ShadowMario/FNF-PsychEngine#7502]
### Describe your bug here.

Im not sure if this only happens on botplay but hurt notes still have a hitsound and its fricking annoying

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added the Hill of the void mod and the Atrocity mod.

**Comment by Theoyeah** [comment]
It is not a bug, hitsound will make a sound on any note pressed, no matter what is the notetype

**Comment by SpookyMan16** [comment]
> It is not a bug, hitsound will make a sound on any note pressed, no matter what is the notetype

even when I dont hit them?

**Comment by Theoyeah** [comment]
No
