### ISSUE TITLE
legit middle scroll

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#7505]
### What is your question?

![legit middle scroll](https://user-images.githubusercontent.com/83985038/159886460-84d57a34-d769-4571-8ee9-6b41d21cccee.PNG)
is there a way to do this ingame with Lua?

**Comment by Stilic** [comment]
yeah, just play with notes `direction` value an strum angle shit
but you must know a little of lua and how to loop through all notes (not so hard)

**Comment by Stilic** [comment]
also i will make a example code for you if you want

**Comment by creeperkidking** [comment]
yes please

**Comment by Stilic** [comment]
> yes please

will see in two days

**Comment by creeperkidking** [comment]
k

**Comment by creeperkidking** [comment]
@Stilic
you there?
its been more than two days
if its taking a long time then i get it

**Comment by Stilic** [comment]
> @Stilic you there? its been more than two days if its taking a long time then i get it

im working on some projects and i cant code that now. sorry for that.

**Comment by creeperkidking** [comment]
it k
