### ISSUE TITLE
How do I make a background that looks like its snowing?

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#7512]
How do I make a background that looks like its snowing?

Basically what i want (Top = back, Bottom = Front)

The cloudy sky and Snowy Ground
Snowy Trees
BF GF and Opponent
Snow Falling animation

Can you give me a code for it? please. i know how to make a background through Lua i don't know how to do this specifically and ive already tried to look up a tutorial and it couldn't find a good one
File names are SkyGround.png, SnowTree.png and SnowyFall.png

_Originally posted by @SonicXFire1987 in https://github.com/ShadowMario/FNF-PsychEngine/discussions/7469_

**Comment by JackoCatacomb** [comment]
this isn't an issue also just use animated sprites and adobe animate/any drawing or animation app

**Comment by cherryiguess** [comment]
not a real issue/request

**Comment by Mastercopper2346** [comment]
#8522
