### ISSUE TITLE
Can't make the week image show in the week editor, Help needed!

### ISSUE THREAD

**Issue by MarioGuyWasTaken** [ShadowMario/FNF-PsychEngine#753]
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Downloaded Build

### Show an screenshot/video of your problem.

Everytime I try to type in the png name for my custom week in the editor, It doesn't work. Do I *use only the png file* or use the image file *with the .xml file?*

**Comment by ShadowMario** [comment]
Just a .png file, put it inside mods/images/storymenu/
