### ISSUE TITLE
2 new events

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#7534]
### What feature do you want to get added on the **base** engine?

I request there be 2 new events:
1. A flash event that when used does a flash of white on the screen. There could be a setting in the settings (duh) t0 turn this off if needed.
2. The last event but instead its black and you can add how long it lasts.
Thank you for your time.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Shadyyam** [comment]
This is pretty easy with lua

cameraFlash(camera:String, color:String, duration:Float,forced:Bool)
camera - "game", "hud" or "other"
color - color of flash
duration - Time duration for it to flash
forced - restarts flash or not

**Comment by creeperkidking** [comment]
idk what that means but thank you
