### ISSUE TITLE
something to add to the chart editor

### ISSUE THREAD

**Issue by PlatinumPanda01** [ShadowMario/FNF-PsychEngine#754]
### What feature do you want to get added on the base engine?

i would like a feature where you can replace a type of note (like the gf sing note) with another type of note (like the hurt note). also i would like it to work with custom notes.

**Comment by ShadowMario** [comment]
No.

**Comment by MeowcaTheoRange** [comment]
> ### What feature do you want to get added on the base engine?
> i would like a feature where you can replace a type of note (like the gf sing note) with another type of note (like the hurt note). also i would like it to work with custom notes.

This is already supported! Just press 7, delete a couple of notes, then add the custom notes you want in their places!

**Comment by PlatinumPanda01** [comment]
No

**Comment by MeowcaTheoRange** [comment]
Please, PLEASE, let me have my account back..

> No

WAAH!

<rest of Arch plays>

**Comment by PlatinumPanda01** [comment]
> Please, PLEASE, let me have my account back..
> 
> > No
> 
> WAAH!
> 
> <rest of Arch plays
weird, i didn't remeber commenting that, but i do actually manually replace notes, but it is a freaking pain when you are porting mods like dusttale to psych engine
