### ISSUE TITLE
How do you compile Source?

### ISSUE THREAD

**Issue by AdmiralUsername** [ShadowMario/FNF-PsychEngine#7570]
### What needs to be documented?

In the Installation text it just says to "follow an FNF Source Compilation tutorial"
I don't know what that means and the YT videos are unhelpful. Can you just put in the documentation how to compile?

**Comment by Theoyeah** [comment]
Look at ninjamuffin fnf page, there a tutorial

**Comment by AdmiralUsername** [comment]
ok

**Comment by enjayar625** [comment]
you can close this now
