### ISSUE TITLE
Health drain thing

### ISSUE THREAD

**Issue by barbbarain** [ShadowMario/FNF-PsychEngine#758]
### What is your question?

So because I got tired of that engine's source code because nothing happens to psych engine after I edited and saved playstate.hx or other things, can we make health drain with Lua script or no?

**Comment by TBiscuit1** [comment]
#703 <--- A script I made for this, careful, any event will stop that one and you need to add a new Drain event

**Comment by Linkstorm-Z** [comment]
Yes, the files .lua with the name of stage (mods/stage) for example, school.lua 

Type this:

function onBeatHit()
	--for every beat
	health = getProperty('health')
	if getProperty('health') > 0.2 then
		setProperty('health', health- 0.03);
	end
    
end

the last number is the speed health

https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API

**Comment by drakonieyah** [comment]
If you want a passive health drain then the answer above is what you are looking for. If you want it to happen on opponent's note hit, then:
```lua
function opponentNoteHit(id, direction, noteType, isSustainNote)
	setProperty('health', getProperty('health')-0.01)
end
```
If you want it to not be able to kill the player, then:
```lua
function opponentNoteHit(id, direction, noteType, isSustainNote)
	if health > 0.01 then
	  setProperty('health', getProperty('health')-0.01)
       end
end
```
Furthermore, if you want it to only happen on your special note, but not kill the player, then:
```lua
function opponentNoteHit(id, direction, noteType, isSustainNote)
	if health > 0.01 and noteType == 'special_note' then
	  setProperty('health', getProperty('health')-0.2)
       end
end
```
The maximum health is 2 (100%), and you start with 1 (50%) by default.

**Comment by Gavman69** [comment]
function opponentNoteHit(id, direction, noteType, isSustainNote)
    if getProperty('health') < 0.025 then -- basically the damage number but + .02 
        setProperty('health', getProperty('health') + 0.023) -- MAKE SURE ITS THE SAME NUMBER AS THE DAMAGE NUMBER
    end -- this makes it so it does not kill bf, delete the if then statement to make it kill bf.
    setProperty('health', getProperty('health') - 0.023); -- enemy drains health, simple
end
Enemy drain made by me :D

**Comment by DEV-idiotXD** [comment]
health = getProperty('health')
	if getProperty('health') > 0.1 then
		if string.match(getProperty('dad.animation.curAnim.name'), "sing") then
			setProperty('health', getProperty(health - 0.001))
		end
	end
end

much more simple checks if the opnt is singing and health is bigger than 0.1 then reduces health


@ShadowMario  close this issue it has already gotten multiple answers

**Comment by MysticFox990** [comment]
> Yes, the files .lua with the name of stage (mods/stage) for example, school.lua
> 
> Type this:
> 
> function onBeatHit() --for every beat health = getProperty('health') if getProperty('health') > 0.2 then setProperty('health', health- 0.03); end
> 
> end
> 
> the last number is the speed health ![image](https://user-images.githubusercontent.com/81461082/139963643-ef6103ce-144f-4214-af1a-020c95fd0831.png)
> 
> https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API

what about every other beat
