### ISSUE TITLE
bug with custom note

### ISSUE THREAD

**Issue by obamacat9** [ShadowMario/FNF-PsychEngine#7586]
### Describe your bug here.

i made a custom note so where you touch it it fades out a little the strum notes and 10s later it goes back to normal but if you press it again in those 10s it fades out harder then you wait another 10s and if you press it again in those 10s it just resets the time
but sometimes the notes dont fade out correctly and sometimes it goes to not faded to faded hard skipping the little faded step
![Screenshot 2022-03-25 174440](https://user-images.githubusercontent.com/102390737/160215322-8164ccba-722d-4a7c-ad0e-9fdd0dc23e0a.png)
i made the note code work using if trues and onTimerCompleted and yes its in the scripts folder i dont see anything wrong that causes the problems from above so i think its a problem from how the functions work so thats why i labeled this as bug and not help either way i dint expect to get help that would work

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by kingyomoma** [comment]
create an if statement inside ```onTimerComplete(sorry)```:
```lua
if sorry = "sorry" then
````
(put the original code inside the if)
```lua
end
```

**Comment by obamacat9** [comment]
that did nothing either way the last part works perfectly the part that is buggy is the fading they do whatever they want they even fade notes diferently and theres nothing wrong with the tweens
