### ISSUE TITLE
Dialogue

### ISSUE THREAD

**Issue by Kaakskakwk** [ShadowMario/FNF-PsychEngine#7587]
### Describe your bug here.

startDialogue(dialogueJson); crashes the song and lua dialogue started the dialogue but also starts the song at the same time, version 0.5.2 please fix this. and yes I DID NOT modify anything in the lua script shadow give in the wiki and also exact script from wiki

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Theoyeah** [comment]
Im not sure but i think lua don't work properly in other os than Windows
