### ISSUE TITLE
My custom event doesn't work

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#759]
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Downloaded Build

### Show an screenshot/video of your problem.

![image](https://user-images.githubusercontent.com/93293747/139754048-25eea6b7-dacc-484b-b50f-28a11e4b75a6.png)

I'm trying to make a custom event that allows me to move arrows
but when I use it literally nothing happens. at all.

function mysplit (inputstr, sep)
    if sep == nil then
        sep = "%s";
    end
    local t={};
    for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
        table.insert(t, str);
    end
    return t;
end

-- Event notes hooks
function onEvent(value1, value2)
    local tableee=mysplit(value1,", ") -- Splits value1 into a table
    for num in input:gmatch("%d+") do 
        table.insert(tableee.tonumber(num)) 
    end
    noteTweenX(tableee[1], tableee[2], tableee[5], "quartIn");
    noteTweenY(tableee[1], tableee[3], tableee[5], "quartIn");
    noteTweenAngle(tableee[1], tableee[4], tableee[5], "quartIn");
    noteTweenAlpha(tableee[1], value2, tableee[5], "quartIn");
end

I've been trying to solve this for about 3 days in the discussion tab to no success.
Help please

**Comment by ItsCapp** [comment]
can someone please help with this?

**Comment by nicho01022** [comment]
Sorry I don't really know about coding but I have the same issue using the screen shake it just don't work!
