### ISSUE TITLE
Expected }

### ISSUE THREAD

**Issue by enjayar625** [ShadowMario/FNF-PsychEngine#7591]
### Describe your problem here.

source/FreeplayState.hx:429: characters 3-7 : Expected }

idk whats wrong with it but it keeps giving me the message 

heres the file 
[FreeplayState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8354417/FreeplayState.txt)

.txt cuz github doesnt support .hx files

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Project.xml, Playstate.hx, MainMenuState.hx, FreeplayState.hx

**Comment by maxisepYT1** [comment]
Replace **426 to 432** with this

 		if (controls.UI_LEFT_P){
			FlxG.sound.play(Paths.sound('scrollMenu'));
			changeDiff(-1);
		}else if (controls.UI_RIGHT_P){
			FlxG.sound.play(Paths.sound('scrollMenu'));
			changeDiff(1);
		}else if (upP || downP) changeDiff(); 

(If you get other errors, I won't be able to help you.)
Hope this can help you!

~ _maxisepYT_

**Comment by enjayar625** [comment]
> Replace **426 to 432** with this
> 
> ```
> 	if (controls.UI_LEFT_P){
> 		FlxG.sound.play(Paths.sound('scrollMenu'));
> 		changeDiff(-1);
> 	}else if (controls.UI_RIGHT_P){
> 		FlxG.sound.play(Paths.sound('scrollMenu'));
> 		changeDiff(1);
> 	}else if (upP || downP) changeDiff(); 
> ```
> 
> (If you get other errors, I won't be able to help you.) Hope this can help you!
> 
> ~ _maxisepYT_

thanks it worked
