### ISSUE TITLE
Adding a character in the base assets folder.

### ISSUE THREAD

**Issue by malipali** [ShadowMario/FNF-PsychEngine#7614]
### What is your question?

I made a player character skin. Not to replace bf, but just to be used when I want to use it. When I place sprites in the positions in the assets folder they need to be, the character .json (which does work) won't load the image and crashes the game. But when I do the exact same thing in a mod folder, it works, but only for charts in that mod folder. Any workaround? Or am I forced to replace bf?

**Comment by BombasticTom** [comment]
you can't mod in the assets folder 💀

**Comment by BombasticTom** [comment]
my god just use lua modding

**Comment by Fablisothebottle** [comment]
i mean you can use the main assets folder but that would need source code.

**Comment by malipali** [comment]
> my god just use lua modding
it's literally a player character mod I intend to use of base charts
> i mean you can use the main assets folder but that would need source code.
all characters are softcoded including base ones so not really gonna work
