### ISSUE TITLE
character slides with camera

### ISSUE THREAD

**Issue by EgguMan** [ShadowMario/FNF-PsychEngine#7622]
### Describe your bug here.

As you can see in the link video at the end, the character slides with the camera. how fix

https://www.youtube.com/watch?v=jEcUvBwrl1o

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by enjayar625** [comment]
probably a scroll factor problem

**Comment by EgguMan** [comment]
> probably a scroll factor problem

I did not mess with the scroll factor of zavok, but where would I find it? Would I edit it in the stage lua or?
