### ISSUE TITLE
image in week editor

### ISSUE THREAD

**Issue by KFC-Chicken-1212** [ShadowMario/FNF-PsychEngine#763]
### Describe your bug here.

when i put my image in the \assets\images\storymenu folder and type it in the week editor it still says not found
![image](https://user-images.githubusercontent.com/89538185/139769969-576b639e-6888-4b24-97d0-2d69fcb9a4a4.png)

### Are you modding a build from source or with Lua?

- [X] Lua
- [ ] Source

### What is your build target?

- [X] Windows
- [ ] Linux
- [ ] Mac
- [X] HTML5
- [ ] Flash/Air-based target
- [ ] Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing other than png images and a few songs

**Comment by ExtendedCentral** [comment]
I think it needs to be in the Mods Folder.

**Comment by Micasddsa** [comment]
you have to put the week image in the mods/images/storymenu folder

it's not a bug.

**Comment by ShadowMario** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/44785097/139966326-1d607e97-0a65-463e-a2f2-d15259a93a8d.png)
