### ISSUE TITLE
Putting a stage asset in front of gf, but not bf or the opponent

### ISSUE THREAD

**Issue by Cubism-2** [ShadowMario/FNF-PsychEngine#7630]
### What is your question?

I'm trying to make a stage that has a fence. I want the fence to be on top of the speakers, so the speakers are behind it, but I don't want the players to be behind the fence. Is there anyway to make it only go on top of the speakers, but not go over the players? Thanks

**Comment by cherryiguess** [comment]
something like 

```
setObjectOrder('gfGroup',1)
setObjectOrder('object',2)
setObjectOrder('dadGroup',3)
setObjectOrder('boyfriendGroup',3)
```

**Comment by Cubism-2** [comment]
It worked. Thank you
