### ISSUE TITLE
I always get this error when compiling to html5, how do I fix it?

### ISSUE THREAD

**Issue by oof-plays-yt** [ShadowMario/FNF-PsychEngine#7632]
### Describe your bug here.

Is there something i need to haxelib install?

### Command Prompt/Terminal logs (if existing)

```bash
FNF-PsychEngine>lime test html5 -release
source/WeekData.hx:11: characters 8-19 : You cannot access the sys package while targeting js (for sys.io.File)
source/editors/WeekEditorState.hx:34: characters 8-16 : ... referenced here
source/editors/MasterEditorMenu.hx:119: characters 37-52 : ... referenced here
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Theoyeah** [comment]
i dunno, it never works

**Comment by ZufengW** [comment]
I got this same error.
This workaround made it stop happening for me: Comment out the first line in the stack: `source/WeekData.hx:11`.

But then I started getting different errors.

**Comment by oof-plays-yt** [comment]
It works now, thank you!

**Comment by oof-plays-yt** [comment]
It doesnt go past the "flashing lights" screen
