### ISSUE TITLE
Different voices for each character

### ISSUE THREAD

**Issue by PDL2CGamejolt** [ShadowMario/FNF-PsychEngine#7634]
### Describe your problem here.

is it possible to have each character have different dialogue voices?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ImaginationSuperHero528** [comment]
YES WE NEED THIS

**Comment by ImaginationSuperHero528** [comment]
WE COULD MAKE IT REPEAT TO ALLOW VOICE ACTING
