### ISSUE TITLE
Replace Sound

### ISSUE THREAD

**Issue by Helisonbr** [ShadowMario/FNF-PsychEngine#7645]
### What feature do you want to get added on the **base** engine?

There maybe should have an replace sound or replace music function lua where it replaces a sound or music with the selected one.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
Already exists... You can literally just put the files over at the same folder but in mods/ instead of assets/
