### ISSUE TITLE
chart editor crashes when loading song normal difficulty with reload json

### ISSUE THREAD

**Issue by naether** [ShadowMario/FNF-PsychEngine#7646]
### Describe your bug here.

type the name of a song in the chart editor and hit reload json. instead of loading the normal difficulty it will crash, with a popup saying "file_contents,assets/data/[x song]/[x song]-null.json". i don't know if this happens with songs that have a title different that the json name but yeah
![image](https://user-images.githubusercontent.com/60763676/160261997-a4458ac2-c866-4bda-8c06-bb20652565d1.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ImJustAGuest** [comment]
if you have a normal difficulty, make sure the json does not have "normal" after it, examples can be "lickmycomputer.json" or "someonehelpme.json"

**Comment by naether** [comment]
yes it's just the name of the json

**Comment by naether** [comment]
i noticed this only happens when reloading a json from the master menu chart editor, but if you open the chart editor thru a song by pressing 7 the game doesn't crash

**Comment by bf244** [comment]
well,the way i fix it without going into a song is copying your song json file,and rename it with -null,like fresh-null and it will work

**Comment by Draconic-Hybrid** [comment]
My makeshift solution for this is to comply with the error and duplicate one of your json files, with the difficulty being `-null`. It's crude, but it works. For me at least.
