### ISSUE TITLE
Locking to one difficulty

### ISSUE THREAD

**Issue by Alt-Reality** [ShadowMario/FNF-PsychEngine#765]
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Source Code

### Show an screenshot/video of your problem.

Im trying to lock the difficulty of the game to normal mode only, so i changed some things in coolutil.hx, freeplaystate.hx, and storymenu.hx. The difficulty did lock to normal in story mode, and playing the week gave me normal charts. However, whenever I opened up freeplay, the game would crash. How do I fix this? 
Here are some screenshots of what the code looks like:
**Removing the other difficulties in CoolUtil.hx:**
![image](https://user-images.githubusercontent.com/88809517/139774508-97144d1a-f6f4-4d80-b176-791591a27af4.png)
**Changing the curDifficulty in freeplaystate and storymenustate so its only one:**
![image](https://user-images.githubusercontent.com/88809517/139774603-a7ed78c0-2d32-460c-a628-938810e84045.png)
![image](https://user-images.githubusercontent.com/88809517/139774633-5e0e74c9-0e62-4353-952e-3d9ceae46063.png)
(first is storymenu, second is freeplay)

**Comment by CrusherMods** [comment]
keep the hard and easy mode in CoolUtil.hx and make sure the code in FreeplayState.hx and StoryMenuState.hx is the same the way you put it

**Comment by ShadowMario** [comment]
Change `private static var curDifficulty:Int = 1;` to `private static var curDifficulty:Int = 0;`
