### ISSUE TITLE
Stop Camera from scrolling past a certain point

### ISSUE THREAD

**Issue by ExtendedCentral** [ShadowMario/FNF-PsychEngine#766]
### What is your question?

I was wondering if there was a way to stop the camera from scrolling past a certain pint because when the camera points towards BF you can see the black void.

**Comment by ShadowMario** [comment]
On the stage .lua script:
```lua
function onMoveCamera(focus)
	if focus == 'boyfriend' then
		setProperty('camFollow.x', getProperty('camFollow.x') - 100); -- go a bit more to left
		setProperty('camFollow.y', getProperty('camFollow.y') - 50); --go a bit more up
	end
end
```

On Haxe, just keep searching for "limo" and you will end up finding your answer (on PlayState.hx)
