### ISSUE TITLE
Haxeflixel thing

### ISSUE THREAD

**Issue by enjayar625** [ShadowMario/FNF-PsychEngine#7662]
### Describe your problem here.

Every time theres something null this happens

![Screenshot (195)](https://user-images.githubusercontent.com/102395239/160276675-302b0287-48d7-4790-b800-ef36b25cee01.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Project.xml, Playstate.hx, MainMenuState.hx, FreeplayState.hx, FlashingState.hx, ClientPrefs.hx

**Comment by Theoyeah** [comment]
you taped incorrectly the animation's name, check your xml

**Comment by CrusherMods** [comment]
missing texture or no animation inside the xml named "idle"

**Comment by enjayar625** [comment]
i did everything in the xml correctly i think it has something to do with my custom libraries in Project.xml not working
