### ISSUE TITLE
Object tweens only when pausing the game

### ISSUE THREAD

**Issue by ManMaster707** [ShadowMario/FNF-PsychEngine#7675]
### Describe your problem here.

I've made an object and an event that moves the y axis of the object, but the object only does its tween only when pausing and unpausing the game, and it doesn't even do the tween, it just snaps to the location in the tween.
Here's the object's code:

makeAnimatedLuaSprite('bgLava', 'mario/IHY/Luigi_IHY_Background_Assets_Lava', -18, 716);
  addAnimationByPrefix('bgLava', 'blub', 'Lava', 12, true);
  scaleObject('bgLava', 1.3, 1.3);
  setObjectCamera('bgLava', 'other');

and here's the event's code:

function onEvent(name,value1,value2)
    if name == "Sacar Lava" then
      doTweenY('fuckmylife', 'bgLava', value1, 'quadInOut')
   end
end

(the object does his animation just fine btw)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i just added things trough the "mods" folder.

**Comment by Draconic-Hybrid** [comment]
I can't be sure if this solves the problem, but that tween is missing a duration. The duration goes between the target and the ease. If you want the duration to be customizable to the event as well, use value2 as the duration, so it'd look something like this:

`doTweenY('fuckmylife', 'bgLava', value1, value2, 'quadInOut')`

**Comment by ManMaster707** [comment]
Thank you! it worked! i forgot to put the duration bcs i'm stupid ._.
