### ISSUE TITLE
How to make gf character play a separated chart.

### ISSUE THREAD

**Issue by Owen-sys** [ShadowMario/FNF-PsychEngine#768]
### Are you trying to code on Source Code (Haxe) or on the Downloaded Build (Lua)?

Downloaded Build

### Show an screenshot/video of your problem.

You know how week 7 pico-speaker is doing a separate chart automatically once he is loaded. How would I be able to do that using Lua scripts?

**Comment by ShadowMario** [comment]
Lua scripts can't load json files.
