### ISSUE TITLE
Psych engine source code not changing when I edit .hx files

### ISSUE THREAD

**Issue by ImJustAGuest** [ShadowMario/FNF-PsychEngine#7689]
### Describe your bug here.

**Whenever i try to use _Psych engine_ and edit it for some reason it doesn't work. Can someone helpm e?**__

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited StoryMenuState.hx to change the position of the weeks and difficulty arrows, I also edited the MainMenuState.hx file while trying to change the position of the menu and edited TitleState.hx to change the position of the title

**Comment by TheRealJake12** [comment]
you didnt save the file
thats a common issue
turn on auto saving

**Comment by vyroxhub** [comment]
do you compile or you save the file?
