### ISSUE TITLE
Keybind overrides

### ISSUE THREAD

**Issue by KutikiPlayz** [ShadowMario/FNF-PsychEngine#769]
### What is your question?

In my mod, I have a 2 player system, but I don't want people to be able to set the keybinds for both sets of notes to be the same. How would I make keybinds override so that they can't be the same?

**Comment by MeowcaTheoRange** [comment]
If your keybinds are stored in an `Array<FlxKey>`, then you could try to use this code.

<a href="https://try.haxe.org/#543A1071">Try Haxe</a>

**Comment by ShadowMario** [comment]
I will close this for now because i'm reworking the options menu for making it easier to mess with controls.
