### ISSUE TITLE
Game freezes when new dialogue character.

### ISSUE THREAD

**Issue by djawesomeyt** [ShadowMario/FNF-PsychEngine#770]
### Describe your bug here.

After 3 dialogue characters once a new one is introduced the game just freezes on that frame. I can still press buttons and hear sound effects but it just stuck on the frame with the new dialouge character coming in. All of the animations are correct and I get no errors in the terminal. Might be because of my bad computer.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yeah I added 3 new dialogue characters and kinda added a working ending dialogue system

**Comment by djawesomeyt** [comment]
[](url)

**Comment by foxcool119** [comment]
a
