### ISSUE TITLE
Source code is slow

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#7701]
### Describe your problem here.

it takes so long just for the source code to load

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i did not.

**Comment by Pico8430** [comment]
Really. The source code needs some time to compile everything for the first time, they don't work like if its super fast. Once it's done compiling, it will load the game and will take seconds/minutes to compile after doing so for the second time. Be patient.

If this is not what you really mean, then it's probably something wrong with whatever the hell your pc is.

**Comment by enjayar625** [comment]
if youre compiling the source code for that folder for the first time it will take around 5-10 minutes but if you compile it the second time etc it will take less than a minute to compile

**Comment by Mastercopper2346** [comment]
5-10 MINUTES!!?? **I EVEN FELL ASLEEP ON MY PC WAITING**

**Comment by Mastercopper2346** [comment]
![image](https://user-images.githubusercontent.com/101440491/160337445-9cb992d9-1393-406b-8f7c-8732f9d96c30.png)

**Comment by Pico8430** [comment]
> 5-10 MINUTES!!?? **I EVEN FELL ASLEEP ON MY PC WAITING**

Uh yeah those 5-10 minutes are not true lmao, it may take like 40m-1h for compiling.

**Comment by KutikiPlayz** [comment]
it all depends on your pc
there's no life hack or simple trick to make it go faster
if your PC is slow, it's slow

**Comment by Mastercopper2346** [comment]
BRUHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by Mastercopper2346** [comment]
TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS TAILS

**Comment by Mastercopper2346** [comment]
![image](https://user-images.githubusercontent.com/101440491/160338128-43d9c779-5551-43c4-a57c-00d52121b14f.png)

**Comment by Mastercopper2346** [comment]
![image](https://user-images.githubusercontent.com/101440491/160338140-68b969cb-6212-410f-a80c-4ab58065835e.png)

**Comment by Mastercopper2346** [comment]
![image](https://user-images.githubusercontent.com/101440491/160338154-aae3f5f6-16ab-4817-916b-43c4a4f92356.png)

**Comment by Pico8430** [comment]
calm down bro, you need to know that compiling isn't as easy as you think.

**Comment by Mastercopper2346** [comment]
![image](https://user-images.githubusercontent.com/101440491/160338183-d3b7ed4a-3819-4b81-ab44-ab36fb568811.png)

**Comment by Mastercopper2346** [comment]
![image](https://user-images.githubusercontent.com/101440491/160338196-3e5c48ba-0ce1-477c-a29e-bb3aba0bba89.png)

**Comment by Mastercopper2346** [comment]
![image](https://user-images.githubusercontent.com/101440491/160338215-9008ae92-e8c0-42c0-a029-bd238bb5271f.png)

**Comment by Mastercopper2346** [comment]
![image](https://user-images.githubusercontent.com/101440491/160338235-5efe4988-9760-4b16-9b2d-5a64cff57526.png)

**Comment by Mastercopper2346** [comment]
![image](https://user-images.githubusercontent.com/101440491/160338253-92d82177-83ae-4d44-b1e0-fbc467fa762f.png)

**Comment by Pico8430** [comment]
🗿

**Comment by Mastercopper2346** [comment]
![image](https://user-images.githubusercontent.com/101440491/160338326-b3dfcb68-70dd-444a-9ac9-ea810b91aedd.png)

**Comment by Mastercopper2346** [comment]
![image](https://user-images.githubusercontent.com/101440491/160338338-bb28147d-c304-4d81-a599-f5271a35bbf6.png)

**Comment by Mastercopper2346** [comment]
![image](https://user-images.githubusercontent.com/101440491/160338358-71ec02dd-f2ee-41df-87b6-bb06430e9c5d.png)

**Comment by Mastercopper2346** [comment]
![image](https://user-images.githubusercontent.com/101440491/160338375-06a4803a-1cb1-48c4-a8c5-77f07fb99a52.png)

**Comment by Mastercopper2346** [comment]
![image](https://user-images.githubusercontent.com/101440491/160338395-0aec70bf-868b-45c4-85b7-88e850658d98.png)

**Comment by Mastercopper2346** [comment]
# you need to know that compiling isn't as easy as you think.
It IS easy, I JUST NEED TO COMPILE IT.

**Comment by Mastercopper2346** [comment]
> shopmilo.com

**Comment by enjayar625** [comment]
> > 5-10 MINUTES!!?? **I EVEN FELL ASLEEP ON MY PC WAITING**
> 
> Uh yeah those 5-10 minutes are not true lmao, it may take like 40m-1h for compiling.

You have a bad pc lmfao

**Comment by Mastercopper2346** [comment]
it takes literally 4 HOURS
