### ISSUE TITLE
Achievement editor?

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#7702]
### What feature do you want to get added on the **base** engine?

Achievement editor?
Like bro you put an achievement in mods and didnt even explain how to use it
like bruh

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by Pico8430** [comment]
Test failed + The softcoded achievements were removed but forgot to get rid of the folder

**Comment by enjayar625** [comment]
ya failed the testttttt

**Comment by thedeveloper112206** [comment]
> ya failed the testttttt

to be fair they probably misclicked. that answer and the correct one are right next to each other.
