### ISSUE TITLE
Where is the discord rpc psych engine icon?

### ISSUE THREAD

**Issue by SAB236YT** [ShadowMario/FNF-PsychEngine#7708]
### What is your question?

i want to edit that but finding or typing "icon" in the search bar makes nothing: shows just enemy icons

**Comment by CrusherMods** [comment]
It's not inside the game files

**Comment by SAB236YT** [comment]
then where is it?

**Comment by CrusherMods** [comment]
> then where is it?

its in the psych engine discord developer application 
but theres no way of accessing it

**Comment by KutikiPlayz** [comment]
use this tutorial to change shit
https://youtu.be/M57nL_PJxnI
yes it's made for kade engine but it works with psych as well

**Comment by ShadowMario** [comment]
The character RPC icons are tied to the Discord Application ID, it's not something people can modify as only i have access to it.
