### ISSUE TITLE
Week 6 ?

### ISSUE THREAD

**Issue by Soeiz** [ShadowMario/FNF-PsychEngine#7711]
### What is your question?

Hello, I have a question, I'm new using Psych Engine and I want to make a mod about week 6, senpai ect. But I can't do it, when I want to do a stage, the "3 2 1 go" is the normal one, so it's kinda annoying. So I have a question, can we make a proper week 6 mod in psych engine ?

**Comment by Soeiz** [comment]
And I forgot, how do we make a dialogue of week 6 ?

**Comment by leobro1106** [comment]
that has to be done in source. The ways of old.
