### ISSUE TITLE
Something weird Is happening with my custom UI

### ISSUE THREAD

**Issue by TrafficKid** [ShadowMario/FNF-PsychEngine#7719]
### Describe your problem here.

It's hard to explain but some of the arrows (mainly down, are extremely off centered even though I did basically nothing) I'm assuming maybe the arrow's offsets are kept somewhere but I'm too fucking stupid to figure It out ngl
![image](https://user-images.githubusercontent.com/84630346/160436806-3b75f794-294b-4edc-a5c6-c52c5ce3935f.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by cherryiguess** [comment]
you should mess with the xml file a bit for it to work, also this isnt really a problem with psych so there isnt a point of asking here since the issues is for bugs with the game shit, not xml files

**Comment by TrafficKid** [comment]
> you should mess with the xml file a bit for it to work, also this isnt really a problem with psych so there isnt a point of asking here since the issues is for bugs with the game shit, not xml files

I use adobe animate I know how xmls work, was asking for help not smart comments on my Inability to fix this.
