### ISSUE TITLE
got a doubt

### ISSUE THREAD

**Issue by nintendofan44** [ShadowMario/FNF-PsychEngine#772]
### What is your question?

what is MODS_ALLOWED for exactly?
i forgor

**Comment by Gostar64** [comment]
MODS_ALLOWED makes things in the mod folder actually do stuff

**Comment by Steviegt6** [comment]
> ### What is your question?
> what is MODS_ALLOWED for exactly? i forgor

A redundant compiler flag for enabling mod loading (without Lua support, which comes in a separate flag).
