### ISSUE TITLE
stuff constantly zoomed in

### ISSUE THREAD

**Issue by Ifmations** [ShadowMario/FNF-PsychEngine#7722]
### Describe your problem here.

ok, so, when i go into a song, all the notes are zoomed in, and the pause menu ui is all screwed up, and the timebar isnt moving, 

i have no clue why!
example:
[Screenshot 2022-03-28 164127](https://user-images.githubusercontent.com/86488183/160439429-3ecc561c-bd9b-477d-9924-5092cf8f31bb.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i didnt edit anything with the timebar or the zoom/pause menu

**Comment by Ifmations** [comment]
bruh

**Comment by ShadowMario** [comment]
Your PC's fault

**Comment by Ifmations** [comment]
> Your PC's fault

no it has something to do with the character.animation.curAnim.frameRate = rate; code in the dialogue WHICH IS STUPID
