### ISSUE TITLE
How can I change the opponent sprite mid-song?

### ISSUE THREAD

**Issue by GameGuyOnYT** [ShadowMario/FNF-PsychEngine#7723]
### Describe your problem here.

Hello.
I am working on a chart where I want to change the opponent mid-song but I couldn't find a way to do this. When I use the "Change Character" event, it changes the boyfriend, not the opponent. Help would be appreciated. (I can give files [eg: charts])
Thank you for reading.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by mayo78** [comment]
in the second value of the change char event put numbers instead:
0: bf
1: dad
2: gf
