### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#7726]
### Describe your problem here.

Is there a way you could skip a part of a song in-game? I find it a bit annoying to wait for the exact part.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes source and assets

**Comment by Lupingllogi111** [comment]
You can enter the charting mode (pressing the debug key) and press enter again to get out of the chart editor.
When you are in the song, wait for the three, two, one, go! countdown to pass and when you see the time bar, press the pause button and search for 'Skip time'. Select your time and there you go.

**Comment by CheesecakeForever** [comment]
I cannot find it

**Comment by amogusgame** [comment]
in 0.5.2h or 0.5.2

**Comment by CheesecakeForever** [comment]
Thank you, can be closed
