### ISSUE TITLE
Game freezes when there is dialogue

### ISSUE THREAD

**Issue by djawesomeyt** [ShadowMario/FNF-PsychEngine#773]
### Describe your bug here.

Whenever I try playing my week it shows nothing but a black screen but it seems the game plays normally. For example: I can continue through the dialouge and even have the song start. I can also pause it and return to the main menu with it still being a black screen. I was working normally before but I don't know what's going on.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yeah I added a new function which enables dialouge to be played after a song.

**Comment by djawesomeyt** [comment]
also songs play normally when i play them on freeplay.

**Comment by djawesomeyt** [comment]
![SharedScreenshot2](https://user-images.githubusercontent.com/88963484/139851606-9cd2bc8a-0366-44d9-b53c-930991ec33d8.jpg)
![SharedScreenshot3](https://user-images.githubusercontent.com/88963484/139851607-028a7ad1-adfc-46e6-837f-b3d086c82c87.jpg)
![SharedScreenshot4](https://user-images.githubusercontent.com/88963484/139851610-040f4cde-8692-4f79-8a80-2daba31c92a3.jpg)
![SharedScreenshot](https://user-images.githubusercontent.com/88963484/139851598-f9bfb10e-a0e5-4f0a-9b88-0b361894b35e.jpg)

**Comment by djawesomeyt** [comment]
I tried following what you sent me before but it would let me 
```
function endSongDialogue() {
   true;
   true;
   false;

   startDialouge(insert-dialogue-here);
}

**Comment by DevScyu** [comment]
Take a look at #583 it seems to do what you want, with this, you only need to add your dialogue files to your `mods/data/SONGFOLDER` folder so example if you had the following files:
`mods/data/SONGNAME/dialogue.json` and `mods/data/SONGNAME/dialogueEND.json` the game would play dialogue for the start and the end of the song using the respective files.

**Comment by djawesomeyt** [comment]
So i that. but now it's starting to freeze and have the same issue as the black screen. the games still thinks it's running normally but it's stuck on the frame.

**Comment by djawesomeyt** [comment]
just had to restart my computer smh

**Comment by djawesomeyt** [comment]
oh yeah no still freezes

**Comment by djawesomeyt** [comment]
no just keep restarting the game it'll work eventually

**Comment by djawesomeyt** [comment]
reopening this for the last time, sorry. but like how do i actually fix this.

**Comment by ShadowMario** [comment]
Looks like an issue on your dialogue file

**Comment by djawesomeyt** [comment]
i don't think it is because I'm able to load it up in the dialogue editor just fine unless it has something to do with the fact it takes longer to load my character's sprites than bf and gf

**Comment by djawesomeyt** [comment]
also my character litterally has 11 different expressions

**Comment by ShadowMario** [comment]
Looks like it couldn't find your character portrait's image then.
