### ISSUE TITLE
Modchart/.lua file gives up working around 5:30 mark

### ISSUE THREAD

**Issue by naether** [ShadowMario/FNF-PsychEngine#7732]
### Describe your bug here.

i don't know what causes this, but i have a .lua for a 8 minute song i'm charting and whenever it reaches 5:30 the modchart just gives up; the arrows just stop moving. this may be an overflow of some sort

here's the lua file btw

local allowCountdown = false
local curRip = 1
local xoff = 0
local yoff = 0
local modchartLevel = 1
times = 1

function onStartCountdown()
	-- Block the first countdown and start a timer of 0.8 seconds to play the dialogue
	if not allowCountdown and not seenCutscene then
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('dialogue', 'untitled');
	end
end

function onCreate()
	setProperty("dad.scale.x", 2)
	setProperty("dad.scale.y", 2)
	setProperty("gf.alpha", 0)
	
	makeLuaSprite('decay1','decay1',0,0)
	addLuaSprite('decay1', false)
	setGraphicSize('decay1', 150, 648)
	setLuaSpriteScrollFactor('decay1',0.2,0.2)
	
	makeLuaSprite('white','white',-500,-500)
	addLuaSprite('white', false)
	setGraphicSize('white', 2048, 2048)
	setLuaSpriteScrollFactor('white',0,0)
	setProperty('white.alpha',0)
	setObjectOrder("white", "2022")
end

function onUpdatePost()
	songPos = getSongPosition()
	
	thenew = math.random(-190,-210)
	theold = math.random(-490,-510)
	
	setProperty("background.y",thenew)
	setProperty("background.x",theold)
	
	setProperty("decay"..tostring(curRip)..".y",thenew + 200 + yoff)
	setProperty("decay"..tostring(curRip)..".x",theold + 500 + xoff)
	
	for yourmom = 4,7,1 do
		if modchartLevel == 2 then
			times = math.fmod(math.sin(songPos/2000),1)
		end
		setPropertyFromGroup("strumLineNotes",yourmom,"x",math.tan( math.fmod( ( (songPos/1000 + (yourmom-4))  / (math.pi/8) * times) -90 ,180 ))*112+844 )
	end
	if getProperty("health") < -0.01 then
		setProperty("health",0.01)
	end
end

function opponentNoteHit()
	curHealth = getProperty('health')
	if curHealth >= 0.2 then
		addHealth(-0.01)
	end
	cameraShake("camGame", 0.01, 0.1)
	setPropertyFromClass("openfl.Lib", "application.window.x", tonumber(getPropertyFromClass("openfl.Lib", "application.window.x") + math.random(-5,5) ))
	setPropertyFromClass("openfl.Lib", "application.window.y", tonumber(getPropertyFromClass("openfl.Lib", "application.window.y") + math.random(-5,5) ))
end

function goodNoteHit()
	windowx = getPropertyFromClass("openfl.Lib", "application.window.x")
	windowy = getPropertyFromClass("openfl.Lib", "application.window.y")
	r = 1
	j = 1
	if windowx >= 20 then
		r = -1
	end 
	if windowy >= 20 then
		j = -1
	end
	setPropertyFromClass("openfl.Lib", "application.window.x", windowx + r )
	setPropertyFromClass("openfl.Lib", "application.window.y", windowy + j )
end

function onBeatHit()
	if curBeat == 2660 then
		doTweenAlpha('whiteTween', 'white', 1, 1, "linear")
	end
	if curBeat == 2688 then
		doTweenAlpha('whiteTween', 'white', 0, 5, "linear")
		
		removeLuaSprite("decay1")
		
		makeLuaSprite('decay2','decay2',0,0)
		xoff = -150
		yoff = -150
		curRip = 2
		addLuaSprite('decay2', false)
		setGraphicSize('decay2', 642, 1104)
		setLuaSpriteScrollFactor('decay2',0.2,0.2)
		
		modchartLevel = 2
		
		setPropertyFromClass("openfl.Lib", "application.window.x", 20)
		setPropertyFromClass("openfl.Lib", "application.window.y", 20)
	end
	if curBeat == 4176 then
		doTweenAlpha('whiteTween', 'white', 1, 2, "linear")
	end
	if curBeat == 4224 then
		doTweenAlpha('whiteTween', 'white', 0, 5, "linear")
		
		removeLuaSprite("decay2")
		
		makeLuaSprite('decay3','decay3',0,0)
		xoff = -250
		yoff = -150
		curRip = 3
		setGraphicSize('decay3', 828, 1128)
		addLuaSprite('decay3', false)
		setLuaSpriteScrollFactor('decay3',0.2,0.2)
		
		setPropertyFromClass("openfl.Lib", "application.window.x", 20)
		setPropertyFromClass("openfl.Lib", "application.window.y", 20)
	end
end

-- 4176

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by naether** [comment]
i forgot to mention: the modchart doesn't stop when i use timeskip in charting mode, it stops when 5:30 minutes passed

**Comment by CoolGuyisHere** [comment]
PC issue, you can "fix" it by turning down your FPS limit to 60 or something, but if you want to fix the issue with higher FPS, then the only option is to get a better PC however I've seen people with beefy PCs having this same issue so IDK :/

**Comment by naether** [comment]
don't know if that's the issue but gonna try

**Comment by naether** [comment]
@ShadowMario fevwbwefbwevbebbee

**Comment by ShadowMario** [comment]
Fixed long ago in the repo.
