### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by monishrules** [ShadowMario/FNF-PsychEngine#774]
### What is your question?

1. is it possible to add difficulties through mod folders

**Comment by FuseIsHere813** [comment]
I don't think it's possible to do it in mod folders, you have to edit source code for that.

**Comment by Gavman69** [comment]
They should add custom difficulties through mod folders, fnf modding plus has it so they can add it too.

**Comment by DevScyu** [comment]
This would just be like the name of the difficulties right? so you could have more than easy,normal,hard

**Comment by Steviegt6** [comment]
> They should add custom difficulties through mod folders, fnf modding plus has it so they can add it too.

There's plenty of opportunities to convert Psych to a more data-driven design. Personally, I'd like to see the engine reach a point where the entirety of vanilla FNF could be recreated through the API.

**Comment by ShadowMario** [comment]
It's not possible, i have higher priorities at the moment.
