### ISSUE TITLE
How do I add a loading screen before each song

### ISSUE THREAD

**Issue by multicuentadereespaldo** [ShadowMario/FNF-PsychEngine#7748]
### Describe your problem here.

How do I add a loading screenHow do IHow do I add a loading screenHow do I add a loading screenHow do I add a loading screenHow do I add a loading screenHow do I add a loading screenHow do I add a loading screenHow do I add a loading screenHow do I add a loading screenHow do I add a loading screenHow do I add a loading screenHow do I add a loading screenHow do I add a loading screenHow do I add a loading screenHow do I add a loading screenHow do I add a loading screenHow do I add a loading screenHow do I add a loading screenHow do I add a loading screen add a loading screenHow do I add a loading screenHow do I add a loading screenHow do I add a loading screen

 
 
 
 
 
 
 
 
 

 
 
 
 ._.xd

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Stilic** [comment]
> 

wtf you cringe + too dumb
