### ISSUE TITLE
How can i add shaders to my backround?

### ISSUE THREAD

**Issue by Villezen** [ShadowMario/FNF-PsychEngine#775]
### Describe your problem here.

Can someone tell me how to add shaders to my background like these ones in VS Dave and Bambi?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i tried editing PlayState.hx but the game refuses to load.

**Comment by ShadowMario** [comment]
I have no idea what VS Dave and Bambi looks like and how it uses shaders, i've stated multiple times for people not to ask "How can i do X thing like in mod Y???" because of me hardly even playing mods nowadays. Elaborate or close this.

**Comment by CyndaquilDAC** [comment]
You mean the background shader? just reference our code damn

**Comment by drakonieyah** [comment]
> I have no idea what VS Dave and Bambi looks like and how it uses shaders, i've stated multiple times for people not to ask "How can i do X thing like in mod Y???" because of me hardly even playing mods nowadays. Elaborate or close this.

I think he means this.
[video=youtube]https://youtu.be/hf6ZQQWTWIw?t=416[/video]

**Comment by PoleyMagik** [comment]
VS Dave's source is public, go look there https://github.com/MoldyGH/VsDave

**Comment by titopops** [comment]
to make this more easier to understand, the person wants to know how to add "shading" to the characters, certain background objects, and other stuff. by this, they want to know how to make for example, boyfriend being darker (night)/yellow orange like idk (sunset) because the stage is in the night/sunset time

**Comment by CyndaquilDAC** [comment]
> to make this more easier to understand, the person wants to know how to add "shading" to the characters, certain background objects, and other stuff. by this, they want to know how to make for example, boyfriend being darker (night)/yellow orange like idk (sunset) because the stage is in the night/sunset time (besides copy and pasting the code probably won't work due to being two different engines)

they mean the background shader

**Comment by PoleyMagik** [comment]
> to make this more easier to understand, the person wants to know how to add "shading" to the characters, certain background objects, and other stuff. by this, they want to know how to make for example, boyfriend being darker (night)/yellow orange like idk (sunset) because the stage is in the night/sunset time (besides copy and pasting the code probably won't work due to being two different engines)

Actually I think he might be referring to the wave shader in Cheating, the time of day stuff iirc wasn't done with shaders (I'm no Dave & Bambi expert tho)

**Comment by titopops** [comment]
> > to make this more easier to understand, the person wants to know how to add "shading" to the characters, certain background objects, and other stuff. by this, they want to know how to make for example, boyfriend being darker (night)/yellow orange like idk (sunset) because the stage is in the night/sunset time (besides copy and pasting the code probably won't work due to being two different engines)
> 
> Actually I think he might be referring to the wave shader in Cheating, the time of day stuff wasn't done with shaders, it uses the "color" flxSprite property.

oh, sorry i didnt realize since i posted that in like, 3 am, so i didnt really understand it quite well

**Comment by ShadowMario** [comment]
Sounds like this is solved...? idk

**Comment by crashok20185** [comment]
yeah i know how to do this, took me long time to discover
