### ISSUE TITLE
stages shows always as stage in chart editor

### ISSUE THREAD

**Issue by 4wdthinks** [ShadowMario/FNF-PsychEngine#776]
### Describe your bug here.

in the base game songs, despite the stage, the chart editor always shows it as "stage" instead of the stage its meant to be.

![image](https://user-images.githubusercontent.com/79160331/139911998-091ec871-e225-43d3-a0a5-7eac8947e082.png)
![image](https://user-images.githubusercontent.com/79160331/139912004-c6714234-acb1-42a6-9e2e-489b973010e6.png)

which doesn't happen for modded songs:
![image](https://user-images.githubusercontent.com/79160331/139912126-8369a589-0026-4a08-80e6-f9f7fe962f1c.png)
![image](https://user-images.githubusercontent.com/79160331/139912137-1a88ae78-49f4-40f7-81af-8b4a346ea508.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope, it's the base downloaded build with my lua stuff.

**Comment by ShadowMario** [comment]
Charts with no stage in their .json file (Usually vanilla charts or older versions of Psych) are listed as "stage" no matter what stage it is in.
There's a hardcoded thing for setting the stage of vanilla charts to the correct one when it is missing.
