### ISSUE TITLE
Set Character Scale in Lua

### ISSUE THREAD

**Issue by ScarabWasTaken** [ShadowMario/FNF-PsychEngine#7764]
### What feature do you want to get added on the **base** engine?

As far as I can tell there's no way to rescale a character for a partcilaur song outside of saving a new character file. 
If I can just 

setProperty('boyfriend.scaleX', 0.5);
setProperty('boyfriend.scaleY', 0.5);

Life would be a lot easier

Would also mean I can shrink/grow the character in the song.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ScarabWasTaken** [comment]
Thinking about it, I supposed the character sheet would need an anchor coordinate to set, like one of the feet so the scaling can be done from there onwards to keep the animation offsets to some degree.

**Comment by frantastic24** [comment]
[It's on the wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions)
