### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by Lupingllogi111** [ShadowMario/FNF-PsychEngine#7766]
### Describe your problem here.

I have been doing a mod, and I wanted to know if you were able to make dialogues play when you die without having to use the source code. Can someone tell me if it is possible?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TON-Games** [comment]
I think it not possible if it me I gonna use scorce code(I think becuase I nerver use lua before)

**Comment by Ninjakaiden523** [comment]
It could be, I tried to get it to work, but failed because of my incompetence with coding.
