### ISSUE TITLE
arrow hitbox delay

### ISSUE THREAD

**Issue by travisgamemaker** [ShadowMario/FNF-PsychEngine#7769]
### What feature do you want to get added on the **base** engine?

title

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Ninjakaiden523** [comment]
Just the hitbox? That would be disorienting at least.

**Comment by ShadowMario** [comment]
Note's strumTime variable, you can visually change the arrow's position with note's `offsetY` variable
