### ISSUE TITLE
How to hide other weeks?

### ISSUE THREAD

**Issue by Kiffolisk** [ShadowMario/FNF-PsychEngine#778]
### What needs to be documented?

I can't seem to be able to find a page talking about hiding/deleting the other default weeks. I also have an issue with duplicated weeks (i renamed a week and now there are two of them). I didn't make this a bug report because the docs for this are missing.

**Comment by Kiffolisk** [comment]
Nevermind, it's just a compiler issue where some files don't get deleted.

**Comment by FuseIsHere813** [comment]
To make it easy, Hide the base weeks from Story Mode in the week editor.
