### ISSUE TITLE
How to block pausing?

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#7780]
### Describe your problem here.

How do you block pausing? It would REALLY help with my mod.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i did not.

**Comment by keanu64github** [comment]
function onPause()
	return Function_Stop
end

**Comment by Mastercopper2346** [comment]
thx
