### ISSUE TITLE
Custom hit sound for custom note.

### ISSUE THREAD

**Issue by WeldedFlap** [ShadowMario/FNF-PsychEngine#779]
### Describe your problem here.

I want to make it so that when ever my custom note is hit a sound plays, how can I do this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I made a warning note (like in HD) it works but I don't know how to make the sound play.

**Comment by leobro1106** [comment]
yo whats the code for the warning note I need it

**Comment by ShadowMario** [comment]
`FlxG.sound.play` exists
