### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by DabbinDude316B** [ShadowMario/FNF-PsychEngine#7791]
### Describe your problem here.

Can you help me on my fnf mod? I need some help on the character!

Looks (Top to bottom)

PHASE 1: (Opponent)

Girl

Has Green Hair

Has Headphones gagging around neck

Has a green shirt with a black heart in the middle

Has microphone

Has black pants

Has black shoes

PHASE 2: (Opponent)

(I can just adjust the character lol but if I can’t draw this)

make the character annoyed Lol

PHASE 3)

Two characters. Ok?

(Opponent)

Make the girl’s skin red, crying, add wings and make the char flying (also reach out for bf)

Remove microphone

(Boyfriend)

Make him sonic run lol

Make him look like he’s on a hurry lol

PHASE 4)

(Same characters are last phase lol)

(Added sprites)

(Girl phase 3-4)

Attack (firey sword slash)

(Bf phase 3-4)

Dodge (dodges sword)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i did not.

**Comment by TheKitBoi** [comment]
how about stop spamming the close button + this isnt a fnf help work repo

**Comment by DabbinDude316B** [comment]
I know that know + I did it bc no one said anything so they wouldn’t get emails -_-
