### ISSUE TITLE
Fnf psychic engine sometimes exit the app

### ISSUE THREAD

**Issue by Games-player21** [ShadowMario/FNF-PsychEngine#7800]
### Describe your bug here.

when i was in the chart menu i was recharting cheating song and adding scripts it happened it closed the app

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

It's not build

**Comment by Games-player21** [comment]
somebody help fix the problem pls i don't get any notifi soo chat me in discord Dark_bangi#6506

**Comment by Ninjakaiden523** [comment]
It might be caused by some sort of sprite integer overflow, try adding the events in an empty chart and saving the events with the save events button. Also, I can't seem to find you on discord.

**Comment by Games-player21** [comment]
BRUH  I WAS IN CHART MENU AND THE APP CLOSED WHAT HAPPEN TO YOU?!
