### ISSUE TITLE
This can help a lot

### ISSUE THREAD

**Issue by DANI002428** [ShadowMario/FNF-PsychEngine#781]
### What feature do you want to get added on the base engine?

for x32 Bits versions there is a solution for the cutscenes, maybe you already know or something like that but the solution is to exchange the MP4 for Webm, that way it can be compiled and opened.

For what I wrote this is because of what was mentioned, maybe you can make another source code for the Psych Engine but with Webm to compile on 32-Bit PC's, Mac, Linux, Android, etc.

**Comment by ShadowMario** [comment]
Ehhh nah
