### ISSUE TITLE
Character Animation Dropdown

### ISSUE THREAD

**Issue by Ninjatintin** [ShadowMario/FNF-PsychEngine#7816]
### What feature do you want to get added on the **base** engine?

In the character editor, add a dropdown of all the animations in the xml when selecting what animation in the xml an animation will be set to, this way you don't need to waste your time looking in the xml file.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by cherryiguess** [comment]
this wouldnt work well cuz of xmls like bf and pico, also doesnt allow indice animations, and lazy af just do it yourself lmao
