### ISSUE TITLE
Memory optimization

### ISSUE THREAD

**Issue by HIGGAMEON** [ShadowMario/FNF-PsychEngine#7817]
### What is your question?

Is there a way to have the memory more optimized? I'd apreciate it a lot sense I've been trying to make something and when I would play test it, it would use over 3,000 memory which seems ridiculous, if you can't, can you maybe atleast give me an idea of how it sorta works maybe? Thank you.

>Love the engine btw

**Comment by ShadowMario** [comment]
The problem might be on you using a lot of large spritesheets/atlas.
In this case i'd suggest finding some way to reduce your sprites since you didn't give me any information about it.
