### ISSUE TITLE
Problem with logoBumpin.xml

### ISSUE THREAD

**Issue by LucaGoku** [ShadowMario/FNF-PsychEngine#782]
### Describe your problem here.

I'm porting V.S. Dave and Bambi and i replaced the logoBumpin thing, but when i test it, it's misaligned.
![image](https://user-images.githubusercontent.com/92657248/139968473-9d9762e7-a0bc-4910-901b-142ba5f28fce.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't

**Comment by PoleyMagik** [comment]
The mod probably changed the logo's position. Prolly have to realign yourself.

**Comment by LucaGoku** [comment]
How do i do that? Idk how to code.

**Comment by PoleyMagik** [comment]
Alter titleState.hx at around line 195, that should be where you can modify the positions.

**Comment by LucaGoku** [comment]
Idk how to do that.

**Comment by CyndaquilDAC** [comment]
The logo was x y repositioned in Vs. Dave and Bambi.

**Comment by LucaGoku** [comment]
So do i put the x y thing like the original logoBumpin?

**Comment by CyndaquilDAC** [comment]
> So do i put the x y thing like the original logoBumpin?

X: 15
Y: -25

**Comment by LucaGoku** [comment]
It worked, thanks!

**Comment by LucaGoku** [comment]
> Alter titleState.hx at around line 195, that should be where you can modify the positions.

How do i do that in Psych Engine 0.5?
