### ISSUE TITLE
How to get text come on screen?

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#7820]
### Describe your problem here.

How to get text come on screen? I need this BAD

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, of course

**Comment by vyroxhub** [comment]
go on discussions instead here bruh

**Comment by machonessiebaby** [comment]
function onCreate(elapsed)
	debugPrint("Song By Crazyblox, Remixed by Macho.")
end

thats debug print it appears in the top right corner

**Comment by Mastercopper2346** [comment]
I mean bottom-middle

**Comment by acap09** [comment]
> I mean bottom-middle

you mean the "3 2 1 GO!"?

**Comment by acap09** [comment]
> function onCreate(elapsed) debugPrint("Song By Crazyblox, Remixed by Macho.") end
> 
> thats debug print it appears in the top right corner

top left*

**Comment by Mastercopper2346** [comment]
i mean right above the health bar

**Comment by Mastercopper2346** [comment]
> go on discussions instead here bruh
WELL DISCUSSIONS IS DELETED

**Comment by hayfii** [comment]
> > go on discussions instead here bruh
> 
> WELL DISCUSSIONS IS DELETED

that was before april fools right...
