### ISSUE TITLE
I'm having problems compiling 

### ISSUE THREAD

**Issue by Bri-Guy-Glitch2** [ShadowMario/FNF-PsychEngine#7821]
### Describe your problem here.

I've gotten to the point of needing to input lime test windows but when I do it says that i need "linc_luajit" I went to install it here and try the command again, but it still says that I didn't install it. I'm wondering if anyone knows how to fix this issue

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

**Comment by Mastercopper2346** [comment]
what

**Comment by Mastercopper2346** [comment]
just follow this tutorial:
https://www.youtube.com/watch?v=c-H0fMSlYho

**Comment by ImJustAGuest** [comment]
"haxelib install luajit" on powershell/command thingy
