### ISSUE TITLE
error while naming songs

### ISSUE THREAD

**Issue by RoboticPress** [ShadowMario/FNF-PsychEngine#7824]
### Describe your bug here.

Hi hi!
while naming the week file, if a banned windows name is typed midway the engine crashes

like con, con1, etc

I suggest adding a list of these items so the engine doesn't try to load them while typing the week file

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by Ninjakaiden523** [comment]
Why is this a "bug" label?
