### ISSUE TITLE
Randomizing Note Positions and Forced Middle-Scroll

### ISSUE THREAD

**Issue by MarkToonsHD** [ShadowMario/FNF-PsychEngine#784]
### Describe your problem here.

Hello again, and sorry for the inconvenience. I need help on two events: one that will help me randomize note positions (like the event in the Hypno Lullaby mod that will mess up the note positions) and another one that will force the player's notes to become middle scroll (like defeat from Impostor v3). Sorry again for the inconvenience and I will again appreciate the help. :)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

**Comment by drakonieyah** [comment]
Hey! I am not sure if it's possible to force middlescroll with lua, but if it is then it would be this:
```lua
function onCreate()
 setPropertyClass('ClientPrefs', 'middleScroll', true)
end
```
Test to see if this works, and reply if it didn't!

**Comment by MarkToonsHD** [comment]
> Hey! I am not sure if it's possible to force middlescroll with lua, but if it is then it would be this:
> 
> ```lua
> function onCreate()
>  setPropertyClass('ClientPrefs', 'middleScroll', true)
> end
> ```
> 
> Test to see if this works, and reply if it didn't!

Didn't work, but thanks for trying :)

**Comment by drakonieyah** [comment]
> > Hey! I am not sure if it's possible to force middlescroll with lua, but if it is then it would be this:
> > ```lua
> > function onCreate()
> >  setPropertyClass('ClientPrefs', 'middleScroll', true)
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Test to see if this works, and reply if it didn't!
> 
> Didn't work, but thanks for trying :)

Seems like the engine won't let you change client preferences with lua. Well, the only thing I can tell you is, edit the source code.

**Comment by ShadowMario** [comment]
This should work for forcing middlescroll:
```lua
function onCreate()
    if not middleScroll then
        setPropertyFromGroup('opponentStrums', 0, 'x', -5000);
        setPropertyFromGroup('opponentStrums', 1, 'x', -5000);
        setPropertyFromGroup('opponentStrums', 2, 'x', -5000);
        setPropertyFromGroup('opponentStrums', 3, 'x', -5000);

        setPropertyFromGroup('playerStrums', 0, 'x', defaultPlayerStrumX0 - 320);
        setPropertyFromGroup('playerStrums', 1, 'x', defaultPlayerStrumX1 - 320);
        setPropertyFromGroup('playerStrums', 2, 'x', defaultPlayerStrumX2 - 320);
        setPropertyFromGroup('playerStrums', 3, 'x', defaultPlayerStrumX3 - 320);
    end
end
```

**Comment by MarkToonsHD** [comment]
> This should work for forcing middlescroll:
> 
> ```lua
> function onCreate()
>     if not middleScroll then
>         setPropertyFromGroup('opponentStrums', 0, 'x', -5000);
>         setPropertyFromGroup('opponentStrums', 1, 'x', -5000);
>         setPropertyFromGroup('opponentStrums', 2, 'x', -5000);
>         setPropertyFromGroup('opponentStrums', 3, 'x', -5000);
> 
>         setPropertyFromGroup('playerStrums', 0, 'x', defaultPlayerStrumX0 - 320);
>         setPropertyFromGroup('playerStrums', 1, 'x', defaultPlayerStrumX1 - 320);
>         setPropertyFromGroup('playerStrums', 2, 'x', defaultPlayerStrumX2 - 320);
>         setPropertyFromGroup('playerStrums', 3, 'x', defaultPlayerStrumX3 - 320);
>     end
> end
> ```

Doesn't seem to work :(

**Comment by ShadowMario** [comment]
Put it on `function onUpdate(elapsed)` then

**Comment by MarkToonsHD** [comment]
> Put it on `function onUpdate(elapsed)` then

Worked, thanks!

**Comment by MarkToonsHD** [comment]
Still need help on the randomizing tho...

**Comment by ShadowMario** [comment]
Still need you to explain what do you mean with randomizing it, as you might not know i've explained in countless posts that i don't play mods that much so i didn't play Lullaby's yet and have no idea what do you mean.

**Comment by titopops** [comment]
> Still need you to explain what do you mean with randomizing it, as you might not know i've explained in countless posts that i don't play mods that much so i didn't play Lullaby's yet and have no idea what do you mean.

I'm pretty sure they mean constantly moving the notes around to other places then on the top/bottom, anyways its something like this
![image](https://user-images.githubusercontent.com/93490646/141539988-03022c01-8849-4f15-b1ae-7195b398a801.png)
![image](https://user-images.githubusercontent.com/93490646/141540023-c2b576d4-5e3a-4070-8c28-8598fb36e868.png)
the reason why they want middle scroll forced is so the enemy notes arent there, so its not confusing i guess

**Comment by titopops** [comment]
> > Still need you to explain what do you mean with randomizing it, as you might not know i've explained in countless posts that i don't play mods that much so i didn't play Lullaby's yet and have no idea what do you mean.
> 
> I'm pretty sure they mean constantly moving the notes around to other places then on the top/bottom, anyways its something like this ![image](https://user-images.githubusercontent.com/93490646/141539988-03022c01-8849-4f15-b1ae-7195b398a801.png) ![image](https://user-images.githubusercontent.com/93490646/141540023-c2b576d4-5e3a-4070-8c28-8598fb36e868.png) the reason why they want middle scroll forced is so the enemy notes arent there, so its not confusing i guess

then again its not technically middle scroll if its not on, because the enemy notes might still be scrambled

**Comment by MarkToonsHD** [comment]
> Still need you to explain what do you mean with randomizing it, as you might not know i've explained in countless posts that i don't play mods that much so i didn't play Lullaby's yet and have no idea what do you mean.

Ok, I'll specify. The script should randomize each note's X and Y positions, but follow the same order from left to right (Left Down Up Right).

**Comment by MarkToonsHD** [comment]
> > Still need you to explain what do you mean with randomizing it, as you might not know i've explained in countless posts that i don't play mods that much so i didn't play Lullaby's yet and have no idea what do you mean.
> 
> I'm pretty sure they mean constantly moving the notes around to other places then on the top/bottom, anyways its something like this ![image](https://user-images.githubusercontent.com/93490646/141539988-03022c01-8849-4f15-b1ae-7195b398a801.png) ![image](https://user-images.githubusercontent.com/93490646/141540023-c2b576d4-5e3a-4070-8c28-8598fb36e868.png) the reason why they want middle scroll forced is so the enemy notes arent there, so its not confusing i guess

The first sentence is correct, but for the second one, I needed middle scroll for Defeat (from amogus) because I wanted to port multiple mods at once before the end of the year. Think of it as multiple mods in a mod.

**Comment by ShadowMario** [comment]
Dunno if this will work but i just want to close this already;
Also don't release your port publicly or i will kick your ass.
```lua
for i = 0, 4 do
    math.randomseed(os.clock() + (i + 1) * 5; --random enough i guess
    setPropertyFromGroup('playerStrums', i, 'x', _G['defaultPlayerStrumX'..i + math.random(-700, 50));
    setPropertyFromGroup('playerStrums', i, 'y', _G['defaultPlayerStrumY'..i - math.random(-400, 50));
end
```
