### ISSUE TITLE
is there a lua code for changing the players *ARROW*  color?

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#7844]
### What is your question?

title

**Comment by machonessiebaby** [comment]
> ```lua
> function onCreate()
>     setPropertyFromGroup('playerStrums', 0, 'hue', value:Int)
>     setPropertyFromGroup('playerStrums', 1, 'hue', value:Int)
>     setPropertyFromGroup('playerStrums', 2, 'hue', value:Int)
>     setPropertyFromGroup('playerStrums', 3, 'hue', value:Int)
> end
> ```
> 
> Replace `value:Int` with a whole number. (im sure u know why i used that as a placeholder)

so replace hue with the hue colors right?

**Comment by PrismLight** [comment]
> > ```lua
> > function onCreate()
> >     setPropertyFromGroup('playerStrums', 0, 'hue', value:Int)
> >     setPropertyFromGroup('playerStrums', 1, 'hue', value:Int)
> >     setPropertyFromGroup('playerStrums', 2, 'hue', value:Int)
> >     setPropertyFromGroup('playerStrums', 3, 'hue', value:Int)
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Replace `value:Int` with a whole number. (im sure u know why i used that as a placeholder)
> > NVM so replace only valu:int

Yes you replace value:Int with it not 'hue'

**Comment by Mastercopper2346** [comment]
OMG OHHHHHHHHHHHHHHHHHHH

**Comment by Mastercopper2346** [comment]
Yes, and to get the color you want, go to "note colors" in options and and enter the color. whatever ends up in "hue" replace that number from `value:Int`

**Comment by Mastercopper2346** [comment]
It doesn't work for me
