### ISSUE TITLE
Can't force note color on special note

### ISSUE THREAD

**Issue by drakonieyah** [ShadowMario/FNF-PsychEngine#785]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/18626953/140026558-5fa8ca33-590d-4b2b-a755-3b645806aeb0.png)
I am "bumping" this, since what you wrote there didn't work.
The first special note that appears, gets it's texture changed, and the following other special notes of the same type look like normal arrows, and the coloring doesn't change.
This is my code:
```lua
function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Bullet_Note' then --Check if the note on the chart is a Bullet Note
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'nevada/notes/Bullet_Note'); --Change texture
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashHue', 0); --custom notesplash color, why not
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashSat', -20);
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashBrt', 1);
			setPropertyFromGroup('unspawnNotes', i, 'colorswap.Hue', 0);
			setPropertyFromGroup('unspawnNotes', i, 'colorswap.Brt', 0);
			setPropertyFromGroup('unspawnNotes', i, 'colorswap.Sat', 0);
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', false); --Miss has penalties
			end
		end
	end
end
```

Video example: https://streamable.com/9eveq3

That part of the code you posted of the source code is also not visible on github.
![image](https://user-images.githubusercontent.com/18626953/140026881-17f5d459-bd61-4825-8b25-69b8045f37b0.png)
This is all there is, unless I've missed something.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by Micasddsa** [comment]
I think I get what you mean, I think you are trying to find a way to override the settings for custom note colors.
Sadly, don't think that's possible unless if you're making from the source and made changes to the source.

**Comment by drakonieyah** [comment]
> I think I get what you mean, I think you are trying to find a way to override the settings for custom note colors. Sadly, don't think that's possible unless if you're making from the source and made changes to the source.

Yeah I am trying to do that. I hope this will become a feature on lua too though.
