### ISSUE TITLE
play animation before note hit

### ISSUE THREAD

**Issue by Fury1012** [ShadowMario/FNF-PsychEngine#7858]
### What is your question?

Is there a way to make an animation play before playing another using a note? Or in other words, it's a sword prep animation that plays before the note gets over the note bar.

**Comment by PrismLight** [comment]
source or lua
(i will always ask this if i don't know what to do)

**Comment by Fury1012** [comment]
> source or lua (i will always ask this if i don't know what to do)

you there?

**Comment by PrismLight** [comment]
Oh I forgot...
No I don't know sorry.
Try asking in mayo's discussion repo?

**Comment by Fury1012** [comment]
> Oh I forgot...
> 
> No I don't know sorry.
> 
> Try asking in mayo's discussion repo?

ok, thank you anyways
