### ISSUE TITLE
What happened with discussions?

### ISSUE THREAD

**Issue by vyroxhub** [ShadowMario/FNF-PsychEngine#7859]
### Describe your problem here.

this got gone (ingnore the rest)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by mayo78** [comment]
gone forever (prob cause of all the spam and toxicity)

**Comment by hafimiee** [comment]
no more lua showoffs :trollface:

**Comment by ShadowMario** [comment]
Discussions is kinda garbage and annoying to moderate, so i just closed it permanently.

**Comment by PrismLight** [comment]
> Discussions is kinda garbage and annoying to moderate, so i just closed it permanently.

THANK YOU

**Comment by SonicProYT** [comment]
> Discussions is kinda garbage and annoying to moderate, so i just closed it permanently.

yeah, i guess i’m going with the issues tab instead of THAT BAMBI AND LUA HUB PACK

**Comment by SonicProYT** [comment]
> > Discussions is kinda garbage and annoying to moderate, so i just closed it permanently.
> 
> yeah, i guess i’m going with the issues tab instead of THAT BAMBI AND LUA HUB PACK

heh heh i mean, the discord or smth
