### ISSUE TITLE
Engine crashes when adding a custom character

### ISSUE THREAD

**Issue by Lizza28** [ShadowMario/FNF-PsychEngine#786]
### Describe your bug here.

I know that alot of people have this issue, but whenever I reload a custom character image, it crashes the game, I've seen other tutorials, and it works for them, I don't understand why it doesn't work for me pls fix it, but overall it's a pretty good engine ^^

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

well, I only edited the skins (i mean alot of people do that)

**Comment by drakonieyah** [comment]
Heya! Use an already existing character.json as a template. You may have swapped the animation names with the animation names in the xml. Also, pls include screenshots of your mods/characters, mods/images/characters folders.

**Comment by monishrules** [comment]
same shit is happening to me idk what to do im using a already existing sprite sheet i tried it with both camellia and cirno doesnt work

**Comment by monishrules** [comment]
> Heya! Use an already existing character.json as a template. You may have swapped the animation names with the animation names in the xml. Also, pls include screenshots of your mods/characters, mods/images/characters folders.

https://youtu.be/9GeIlata7Bs this is whats happening

**Comment by nicho01022** [comment]
If it is not source code I recommend u watch a tutorial on adding the character
If it's source code, I don't know.

**Comment by nicho01022** [comment]
If it is not source code I recommend u watch a tutorial on adding the character
If it's source code, I don't know.

**Comment by ShadowMario** [comment]
If you don't know how custom mod directories work (mods/YourModName/), it has limitations for the obvious reason that it shouldn't be looking for every single directory in your mods/ folder as that would cause issues.
Open the Character Editor inside a song of your mod.

Also Camelia dev don't like Psych Engine ports, so you shouldn't release this publicly.
