### ISSUE TITLE
Sudden Major Lag

### ISSUE THREAD

**Issue by neonvore** [ShadowMario/FNF-PsychEngine#7860]
### What is your question?

Never lagged or had issues before but suddenly, I've downloaded the newest build, and its extremely laggy for some reason? Is this an issue in general or is it just me? Just wanted to ask and see in case if it wasn't just me.

**Comment by MaybeMaru** [comment]
Ive havent had any problems with the newest build, maybe try checking if its a problem with your antivirus or something
