### ISSUE TITLE
Can someone give me the setProperty to modify the application title?

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#7862]
### Describe your problem here.

I can't find it anymore on discussions since it was removed. I rely on discussions a lot to steal some code

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i wont tell you

**Comment by lemz1** [comment]
```
function onCreate()
    setPropertyFromClass('openfl.Lib', 'application.window.title', 'hi')
end
```

**Comment by acap09** [comment]
> ```
> function onCreate()
>     setPropertyFromClass('openfl.Lib', 'application.window.title', 'hi')
> end
> ```

thanks
