### ISSUE TITLE
[Not a question, just a general discussion]: I am starting to suspect something...

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#7864]
### What is your question?

I am starting to suspect that the discussion removal is an April Fools Joke...

**Comment by ActualeAnEggDog** [comment]
me too

**Comment by IRIHAYA** [comment]
We believe that the 0.5.3b released this time is also from April Fool's Day!

**Comment by Meme1079** [comment]
What a funny joke!!

**Comment by MR-FNF** [comment]
> We believe that the 0.5.3b released this time is also from April Fool's Day!

yea

**Comment by nbonnie2** [comment]
yes

**Comment by FanKid** [comment]
If this IS an April Fools joke, this is actually the best one. So many people are being fooled, even myself! Like that is one clap for me. 👏
