### ISSUE TITLE
[General Discussion]: Seems like something happened below this issue

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#7869]
### What is your question?

Someone just made one of the spam discussions below this issue I believe. (talking about issue #7868)
(i didnt read the contents of the issue)

**Comment by im557** [comment]
omg somone made joke issue on april fols!!! that ilegal!!!😭😭😭😭😭

**Comment by Stilic** [comment]
Hello, the creator of the spam here.
I am sorry to inform you that this is the april fool day. So, I am technically allowed ONLY THIS DAY to open a shitty spam issue.
I will stop doing that tommorow.
