### ISSUE TITLE
why are children so scared?

### ISSUE THREAD

**Issue by im557** [ShadowMario/FNF-PsychEngine#7873]
### What is your question?

they are worried about a discussion tab being deleted for april fools.

so then, they post about it on issues.

**Comment by acap09** [comment]
correct grammar (no one asked + no one cares):
why are children so scared?
why are a lot of kids so scared?

**Comment by Stilic** [comment]
ok now move to https://funkinforum.com pls

**Comment by Theon08** [comment]
lots? one of these people are probably older than you

you are probably implying yourself

**Comment by Theon08** [comment]
> correct grammar (no one asked + no one cares): why are children so scared? why are a lot of kids so scared?

He changed the title.

**Comment by mayo78** [comment]
https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/1
