### ISSUE TITLE
week 7 achievement visible

### ISSUE THREAD

**Issue by BombasticTom** [ShadowMario/FNF-PsychEngine#7874]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/85838311/161280884-e866a3d6-543d-4043-a002-ced3b9890c7f.png)
i don't know if this was intended, but in 0.5.3b, you can see the week 7 achievement.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing.

**Comment by Stilic** [comment]
you shouldn't upgrade to 0.5.3b since this is a fake release.

**Comment by BombasticTom** [comment]
I just downloaded it, but reported this bug just in case because I think it was unintended

**Comment by Shadyyam** [comment]
it's also visible in 0.5.2h, so i don't think that 0.5.3b is the issue

**Comment by BombasticTom** [comment]
so it was intended?

**Comment by meeptey2** [comment]
considering week 8 is releasing on the 30th, this is probably early preparation.

**Comment by BombasticTom** [comment]
> considering week 8 is releasing on the 30th, this is probably early preparation.

this aged bad

**Comment by FunkyPikmin** [comment]
Actually, it's a bug in the code that shows hidden achievements. To fix it, find line 47 of AchievementsMenuState.hx:
if(!Achievements.achievementsStuff[i][4] || Achievements.achievementsMap.exists(Achievements.achievementsStuff[i][2])) {
and swap the 4 with a 3.

**Comment by FunkyPikmin** [comment]
> > considering week 8 is releasing on the 30th, this is probably early preparation.
> 
> this aged bad

like spoilt milk
