### ISSUE TITLE
How can i do this effect?

### ISSUE THREAD

**Issue by Robert124l** [ShadowMario/FNF-PsychEngine#7876]
### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, the description

**Comment by Robert124l** [comment]
> ?

I edit it

**Comment by BombasticTom** [comment]
![image](https://user-images.githubusercontent.com/85838311/161290037-cea595fc-ec06-42b5-b4b6-49b24d0649d4.png)

**Comment by nbonnie2** [comment]
Its just changing scroll speeds. just slow it down and then speed it up again

**Comment by BombasticTom** [comment]
> Its just changing scroll speeds. just slow it down and then speed it up again

mate the game breaks if scroll speed is 0

**Comment by Robert124l** [comment]
Ok thanks :)

**Comment by Robert124l** [comment]
> Its just changing scroll speeds. just slow it down and then speed it up again

okay i tried it and it doesn't give me the same result, it doesn't pause the arrows but it slows down the speed appearing the arrows that are going to sound

**Comment by hayfii** [comment]
> > Its just changing scroll speeds. just slow it down and then speed it up again
> 
> mate the game breaks if scroll speed is 0

then use 0.1 hhehehehe

**Comment by BombasticTom** [comment]
doesn't have the same effect hhehehehe
