### ISSUE TITLE
[Show and tell] I MADE ICON BOUNCE THING LETS GOOOO

### ISSUE THREAD

**Issue by im557** [ShadowMario/FNF-PsychEngine#7879]
### What is your question?

no discussions = nowhere to post the show and tell.

https://user-images.githubusercontent.com/96075081/161294938-b0b1f685-6397-435d-ac28-8c9a055d762e.mp4

i will be adjusting them so...

**Comment by keanu64github** [comment]
Sick!

**Comment by sakewp** [comment]
that's very cool

**Comment by ShadowMario** [comment]
"Show and Tell" isn't a thing, please don't do posts like this on github issues cuz as you can see it's already flooded with shitty posts
