### ISSUE TITLE
stage editor?

### ISSUE THREAD

**Issue by monishrules** [ShadowMario/FNF-PsychEngine#788]
### What feature do you want to get added on the base engine?

can we stage editor soon possibly?

**Comment by nicho01022** [comment]
Just wait Be patient 
Coding take time

**Comment by PoleyMagik** [comment]
#217 Duplicate issue, said to be too time consuming to add atm.

**Comment by FuseIsHere813** [comment]
Shadow said the stage editor is complex to do, and it is a duplicate of #540 and #217

**Comment by ShadowMario** [comment]
Duplicate of #217 #269 #480 #540
Fuck's sake.
