### ISSUE TITLE
how to add sick counter into psych engine in LUA

### ISSUE THREAD

**Issue by Theoyeah** [ShadowMario/FNF-PsychEngine#7883]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/97792861/161301116-cd90454a-92a6-4e6d-876c-59f928c6b0cc.png)

+ combo counter and misses counter too

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Unholywanderer** [comment]
watch yo tone mf
something like [this](https://drive.google.com/drive/folders/14hy8dIHRTrjF05rrhry4xxFDl4IcbgaI?usp=sharing)

**Comment by Theoyeah** [comment]
Nan, it dont look like Kade's one

**Comment by cmallrt** [comment]
yo smth like this?

```lua
local mCombo = 0

function onCreate()
	makeLuaText('combo', 'Combo: 0', -1, 30, 259 + 30);  
	setObjectCamera('combo', 'hud');
	setTextSize('combo', 20);
	addLuaText('combo');
	setTextFont('combo', 'vcr.ttf')
	setTextAlignment('combo', 'left')
	
	makeLuaText('sick', 'Sicks: 0', -1, getProperty('combo.x'), getProperty('combo.y') + getProperty('combo.height'));  
	setObjectCamera('sick', 'hud');
	setTextSize('sick', 20);
	addLuaText('sick');
	setTextFont('sick', 'vcr.ttf')
	setTextAlignment('sick', 'left')

	makeLuaText('good', 'Goods: 0', -1, getProperty('combo.x'), getProperty('sick.y') + getProperty('sick.height'));    
	setObjectCamera('good', 'hud');
	setTextSize('good', 20);
	addLuaText('good');
	setTextFont('good', 'vcr.ttf')
	setTextAlignment('good', 'left')

	makeLuaText('bad', 'Bads: 0', -1, getProperty('combo.x'), getProperty('good.y') + getProperty('good.height'));    
	setObjectCamera('bad', 'hud');
	setTextSize('bad', 20);
	addLuaText('bad');
	setTextFont('bad', 'vcr.ttf')
	setTextAlignment('bad', 'left')

	makeLuaText('shit', 'Shits: 0', -1, getProperty('combo.x'), getProperty('bad.y') + getProperty('bad.height'));    
	setObjectCamera('shit', 'hud');
	setTextSize('shit', 20);
	addLuaText('shit');
	setTextFont('shit', 'vcr.ttf')
	setTextAlignment('shit', 'left')
end

function onUpdate(elapsed)
	local combo = getProperty('combo')
	local sicks = getProperty('sicks')
	local goods = getProperty('goods')
	local bads = getProperty('bads')
	local shits = getProperty('shits')
	
	if combo > mCombo then
		mCombo = combo
	end
	
	setTextString('combo', 'Combo: '.. combo..' ('..mCombo..')')
	setTextString('sick', 'Sicks: '.. sicks)
	setTextString('good', 'Goods: '.. goods)
	setTextString('bad', 'Bads: '.. bads)
	setTextString('shit', 'Shits: '.. shits)
end
```

**Comment by ActualeAnEggDog** [comment]
notehitlol = 0
sadfasd = 0 -- unused
font = "vcr.ttf" -- the font that the text will use.
cmoffset = -4
cmy = 20
tnhx = -10
function onCreate()
    makeLuaText("tnh", 'Total Notes Hit: 0', 250, tnhx, 259);
    setTextFont('tnh', font)
    makeLuaText("cm", 'Combos: 0', 200, -getProperty('tnh.x') + cmoffset, getProperty('tnh.y') + cmy);
    makeLuaText("sick", 'Sicks!: 0', 200, getProperty('cm.x'), getProperty('cm.y') + 30);
    makeLuaText("good", 'Goods: 0', 200, getProperty('cm.x'), getProperty('sick.y') + 30);
    makeLuaText("bad", 'Bads: 0', 200, getProperty('cm.x'), getProperty('good.y') + 30);
    makeLuaText("shit", 'Shits: 0', 200, getProperty('cm.x'), getProperty('bad.y') + 30);
    makeLuaText("miss", 'Bruhes: 0', 200, getProperty('cm.x'), getProperty('shit.y') + 30);
    setObjectCamera("tnh", 'other');
    setTextSize('tnh', 20);
    addLuaText("tnh");

    setObjectCamera("cm", 'other');
    setTextSize('cm', 20);
    addLuaText("cm");
    setTextFont('cm', font)
    setTextAlignment('cm', 'left')
    setObjectCamera("sick", 'other');
    setTextSize('sick', 20);
    addLuaText("sick");
    setTextFont('sick', font)
    setTextAlignment('sick', 'left')
    setObjectCamera("good", 'other');
    setTextSize('good', 20);
    addLuaText("good");
    setTextFont('good', font)
    setTextAlignment('good', 'left')
    setObjectCamera("bad", 'other');
    setTextSize('bad', 20);
    addLuaText("bad");
    setTextFont('bad', font)
    setTextAlignment('bad', 'left')
    setObjectCamera("shit", 'other');
    setTextSize('shit', 20);
    addLuaText("shit");
    setTextFont('shit', font)
    setTextAlignment('shit', 'left')
    setObjectCamera("miss", 'other');
    setTextSize('miss', 20);
    setTextColor('miss', 'ff0000');
    addLuaText("miss");
    setTextFont('miss', font)
    setTextAlignment('miss', 'left')
end


function goodNoteHit(id, direction, noteType, isSustainNote)
	-- Function called when you hit a note (after note hit calculations)
	-- id: The note member id, you can get whatever variable you want from this note, example: "getPropertyFromGroup('notes', id, 'strumTime')"
	-- noteData: 0 = Left, 1 = Down, 2 = Up, 3 = Right
	-- noteType: The note type string/tag
	-- isSustainNote: If it's a hold note, can be either true or false
      if not isSustainNote then    
         notehitlol = notehitlol + 1;
         setTextString('tnh', 'Total Notes Hit: ' .. tostring(notehitlol))
     end -- NOTE I DID NOT MAKE THIS FRANTASTIC24 MADE THIS!

end


function onUpdate(elapsed)
    notehitloltosting = tostring(notehitlol)
    setTextString('cm', 'Combos: ' .. getProperty('combo'))
    setTextString('sick', 'Sick!: ' .. getProperty('sicks'))
    setTextString('good', 'Goods: ' .. getProperty('goods'))
    setTextString('bad', 'Bads: ' .. getProperty('bads'))
    setTextString('shit', 'Shits: ' .. getProperty('shits'))
    setTextString('miss', 'Bruhes: ' .. getProperty('songMisses'))
	-- start of "update", some variables weren't updated yet
    -- setTextString('tnh', 'Total Notes Hit: ' + 1)
end

here is side hud
