### ISSUE TITLE
Annoying fucking SONGNAME-null

### ISSUE THREAD

**Issue by Games-player21** [ShadowMario/FNF-PsychEngine#7884]
### Describe your bug here.

I always get fucking crash when i load JSON IT SAYS MISSING FILE OR SOMETHING BECUASE IT NEED SONGNAME-null WHY THIS HAPPENS CAN THE FUCKING SHDAOW MARIO REMOVE IT AM VERY TIRED WITH THIS SHIT REMOVE ITTTTT

### Command Prompt/Terminal logs (if existing)

```bash
FOK YOU SONGNAME_NULL
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

IT'S NOT FUCKING BUILD

**Comment by im557** [comment]
nully null



no way to delete.

**Comment by angel0020** [comment]
This update is an April fools update that is supposed to replace all the songs with blammed and add its own weeks if you deleted them before

**Comment by ShadowMario** [comment]
Chill the fuck out mf

**Comment by Jsa010** [comment]
just do 'songname-null' and its solved
