### ISSUE TITLE
Note Skins in Lua

### ISSUE THREAD

**Issue by AdmiralUsername** [ShadowMario/FNF-PsychEngine#7885]
### Describe your problem here.

Is it possible to change the current note skin with a lua script?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Ninjakaiden523** [comment]
Like, as an event? I already have some code for that. I just need to get my laptop it's on.

**Comment by Ninjakaiden523** [comment]
function onEvent(name, value1, value2)

    for i = 0, getProperty('unspawnNotes.length')-1 do

        if getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' then
            setPropertyFromGroup('unspawnNotes', i, 'texture', 'Your note's png name'); 
                    end
            end
end

This code is the best I can do with my limited coding experience. It wont replace the gray arrows (AKA Receptors) but will replace the arrows you hit.

![Bullet_notes_assets](https://user-images.githubusercontent.com/77185327/161332002-37481280-d16a-4e3e-b14e-3b5bcb6873c1.png)

.XML file: https://drive.google.com/file/d/17GLafm1UknSr1pfDyt9STVcYWrOko23l/view?usp=sharing

_**USE THESE AS A BASE FOR YOUR NOTES IF YOU CHOOSE TO USE THIS CODE**_
