### ISSUE TITLE
My brother is dancing on the floor for 5 minutes and hes not stopping

### ISSUE THREAD

**Issue by Reycko** [ShadowMario/FNF-PsychEngine#7886]
### Describe your problem here.

I showed him my game and he did this

### Are you modding a build from source or with Lua?

I'm not modding at all

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Idk i just downloaded the new version

**Comment by PrismLight** [comment]
we bouta be prepared for discussion-related issues flooding the issues tab

**Comment by im557** [comment]
> we bouta be prepared for discussion-related issues flooding the issues tab

it is april fools.

**Comment by ShadowMario** [comment]
Glad to know he loved the update!
