### ISSUE TITLE
Bring back psych discussions. (I didn't know what to put it under)

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#7888]
I personally used discussions to host my events and scripts, and it was incredibly useful.
it's incredibly disappointing to see everything gone, there was some seriously cool shit in there.
Although I understand that the discussions were being used for spam and ***literally bullying*** in some situations, I do think the discussions should come back with a bit more moderation, perhaps banning **certain individuals** from creating and commenting on discussions if it continues.

bring back the discussions, see if people have learnt their lessons, ban those who haven't learnt.

show and tell and Q&A could have their own areas alone, no general as the amount of actually *on topic* general discussions I've seen are below 3.

# please bring it back in some way.
### I think there should be a place where people can store their content like custom events and scripts, kinda like show and tell but the discussions are actually quality checked

if it's an april fools prank, ***I'm the fool***

react with a 👍 if you support this.

**Comment by NickIdk1235** [comment]
BRING IT BACKKKKKKKKKKKKKKKKKKKKKKKKKKK

**Comment by mayo78** [comment]
the beginning of the psych engine revolution (2022)

**Comment by ItsCapp** [comment]
that's kinda what I'm trying to spark up.

**Comment by mayo78** [comment]
shadow mario is about to eviscerate us all

**Comment by SammuSucksAtCode** [comment]
god I hope he does, I can finally rest in peace

**Comment by Razthefunni** [comment]
#bringbackdisscusions honsetly i was kinda sad to see it go... it was fun seeing how talented people are in the show & tell people learning in q&a people coming up with wonderful ideas

**Comment by im557** [comment]
isnt this an april fools?

**Comment by SammuSucksAtCode** [comment]
could be but just in case

**Comment by Razthefunni** [comment]
> isnt this an april fools?

god i hope so if it isnt april 2nd is gonna be bombed with people upset

**Comment by ItsCapp** [comment]
I wouldn't be suprised if it didn't come back tomorrow, the discussions became an actual pile of shit

**Comment by Lsoissus** [comment]
2nd time being here, probably tomorrow it will come back, also the psych engine discord server is blammed engine
if you think im lying check this
![Screenshot 2022-04-02 050832](https://user-images.githubusercontent.com/96982235/161347575-f3b1ebdb-6d1d-4b2e-bf0d-9aa166b8bfc9.png)

**Comment by Razthefunni** [comment]
> 2nd time being here, probably tomorrow it will come back, also the psych engine discord server is blammed engine if you think im lying check this ![Screenshot 2022-04-02 050832](https://user-images.githubusercontent.com/96982235/161347575-f3b1ebdb-6d1d-4b2e-bf0d-9aa166b8bfc9.png)

theres a psych discord? can i get a link too it??

**Comment by Razthefunni** [comment]
i thought the basment club/ mind games discord was the server 💀

**Comment by cherryiguess** [comment]
shadow mario has stated that its gone because its hard to moderate, just use the discord lmao (also the discussions are shit)

**Comment by ShadowMario** [comment]
No.

**Comment by TheShowdown** [comment]
oh well no more discussions ig





even tho if its deleted for good then yeah i can get why

**Comment by ItsCapp** [comment]
sad

**Comment by mayo78** [comment]
https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/1
