### ISSUE TITLE
Bring back discussions

### ISSUE THREAD

**Issue by Theon08** [ShadowMario/FNF-PsychEngine#7890]
### What is your question?

Bring them back. there was scripts i needed for my mod. there was someone who named all variables! i dont think this is an april fools. when you bring it back, ban the people who is making spam posts

**Comment by im557** [comment]
wait. i dont want to be banned though...

**Comment by Jsa010** [comment]
#7889

**Comment by Theon08** [comment]
> wait. i dont want to be banned though...

you LITERALLY started the weird spamming stuff and has been making joke posts that was not needed. and recently, you called people kids for being worried about the discussion thing. Of course you need to be banned.

**Comment by im557** [comment]
> > wait. i dont want to be banned though...
> 
> you LITERALLY started the weird spamming stuff and has been making joke posts that was not needed. and recently, you called people kids for being worried about the discussion thing. Of course you need to be banned.

ok! since i made those posts AND other people did too, they also were most helpful people. so that means making a q&a will be less helpful

**Comment by Theon08** [comment]
> > > wait. i dont want to be banned though...
> > 
> > 
> > you LITERALLY started the weird spamming stuff and has been making joke posts that was not needed. and recently, you called people kids for being worried about the discussion thing. Of course you need to be banned.
> 
> ok! since i made those posts AND other people did too, they also were most helpful people. so then they are banned because of you so that means making a q&a will be less helpful

There are people that can help people and never made a spam or joke post.

**Comment by ItsCapp** [comment]
> > > > wait. i dont want to be banned though...
> > > 
> > > 
> > > you LITERALLY started the weird spamming stuff and has been making joke posts that was not needed. and recently, you called people kids for being worried about the discussion thing. Of course you need to be banned.
> > 
> > 
> > ok! since i made those posts AND other people did too, they also were most helpful people. so then they are banned because of you so that means making a q&a will be less helpful
> 
> There are people that can help people and never made a spam or joke post.

for example: me.

**Comment by snazzyostrich** [comment]
> > > > > wait. i dont want to be banned though...
> > > > 
> > > > 
> > > > you LITERALLY started the weird spamming stuff and has been making joke posts that was not needed. and recently, you called people kids for being worried about the discussion thing. Of course you need to be banned.
> > > 
> > > 
> > > ok! since i made those posts AND other people did too, they also were most helpful people. so then they are banned because of you so that means making a q&a will be less helpful
> > 
> > 
> > There are people that can help people and never made a spam or joke post.
> 
> for example: me.

and me (also ur cool bc of the multiple character thing thx)

**Comment by ShadowMario** [comment]
No.

**Comment by JorosTheModderPH** [comment]
bruh

**Comment by mayo78** [comment]
https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/1
