### ISSUE TITLE
Swap Arrows (also why was discussions closed?)

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#7892]
### What is your question?

how do i swap opponent and player arrows and also
what happened to discussions

**Comment by djnbeeman** [comment]
the discussions closing 1. was probably for a april fools joke.

**Comment by mayo78** [comment]
```
if not getPropertyFromClass('ClientPrefs', 'middleScroll') then
    setPropertyFromGroup('playerStrums', 0, 'x', defaultOpponentStrumX0)
    setPropertyFromGroup('playerStrums', 1, 'x', defaultOpponentStrumX1)
    setPropertyFromGroup('playerStrums', 2, 'x', defaultOpponentStrumX2)
    setPropertyFromGroup('playerStrums', 3, 'x', defaultOpponentStrumX3)

    setPropertyFromGroup('opponentStrums', 0, 'x', defaultPlayerStrumX0)
    setPropertyFromGroup('opponentStrums', 1, 'x', defaultPlayerStrumX1)
    setPropertyFromGroup('opponentStrums', 2, 'x', defaultPlayerStrumX2)
    setPropertyFromGroup('opponentStrums', 3, 'x', defaultPlayerStrumX3)
  end
```

**Comment by im557** [comment]
> the discussions closing 1. was probably for a april fools joke.

probably because of the moderation thing.

**Comment by djnbeeman** [comment]
> > the discussions closing 1. was probably for a april fools joke.
> 
> probably because of the moderation thing.

then we are gonna have to find stuff our selfs and we are not gonna know stuff that people made.

**Comment by im557** [comment]
> > > the discussions closing 1. was probably for a april fools joke.
> > 
> > 
> > probably because of the moderation thing.
> 
> then we are gonna have to find stuff our selfs and we are not gonna know stuff that people made.

i think you can go to the discord.

**Comment by djnbeeman** [comment]
> > > > the discussions closing 1. was probably for a april fools joke.
> > > 
> > > 
> > > probably because of the moderation thing.
> > 
> > 
> > then we are gonna have to find stuff our selfs and we are not gonna know stuff that people made.
> 
> i think you can go to the discord.

not everyone in the discussions have discord and we don't even know there discord account name.

**Comment by im557** [comment]
> > > > > the discussions closing 1. was probably for a april fools joke.
> > > > 
> > > > 
> > > > probably because of the moderation thing.
> > > 
> > > 
> > > then we are gonna have to find stuff our selfs and we are not gonna know stuff that people made.
> > 
> > 
> > i think you can go to the discord.
> 
> not everyone in the discussions have discord and we don't even know there discord account name.

if they dont, they should go and ask in the issues or a good lua/source scripter like me (jk)

**Comment by djnbeeman** [comment]
> > > > > the discussions closing 1. was probably for a april fools joke.
> > > > 
> > > > 
> > > > probably because of the moderation thing.
> > > 
> > > 
> > > then we are gonna have to find stuff our selfs and we are not gonna know stuff that people made.
> > 
> > 
> > i think you can go to the discord.
> 
> not everyone in the discussions have discord and we don't even know there discord account name.

and most of the time the people want to have discord name private because it's personal and they might not even feel comfortable sharing it. and they were to freaking lazy to even hire a moderator to moderate the discussions tab.

**Comment by machonessiebaby** [comment]
sadness
welp no more help from discussions just the issues tab now


function onCreatePost(elapsed)
    	noteTweenX("NoteMove1", 0, 800, 2, cubeInOut)
	noteTweenX("NoteMove2", 1, 910, 2, cubeInOut)
	noteTweenX("NoteMove3", 2, 1020, 2, cubeInOut)
	noteTweenX("NoteMove4", 3, 1130, 2, cubeInOut)
	noteTweenX("NoteMove5", 4, 100, 2, cubeInOut)
	noteTweenX("NoteMove6", 5, 210, 2, cubeInOut)
	noteTweenX("NoteMove7", 6, 320, 2, cubeInOut)
	noteTweenX("NoteMove8", 7, 430, 2, cubeInOut)
end


this is the stuff for swap arrows thank you! for the script

**Comment by ItsCapp** [comment]
> the discussions closing 1. was probably for a april fools joke.

nope, it's gone fr

**Comment by SonicProYT** [comment]
> the discussions closing 1. was probably for a april fools joke.

so ummmm
there’s now only 2 alternatives after that
mayo78’s discussions page
or the discord server (https://discord.gg/2ka77eMXDv)
