### ISSUE TITLE
Im making pause button for mobile

### ISSUE THREAD

**Issue by BerdlyEC** [ShadowMario/FNF-PsychEngine#7895]
### Describe your problem here.

But i need the function.

Example:

Pause()

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

**Comment by ImaginationSuperHero528** [comment]
Close... this.

**Comment by BerdlyEC** [comment]
I making this

**Comment by BerdlyEC** [comment]
> Close... this.

Close()
?

**Comment by kingyomoma** [comment]
They're telling you to close this issue lmao

**Comment by Randomxdp** [comment]
I can do it but why? It wont be comfromtable

**Comment by BerdlyEC** [comment]
> I can do it but why? It wont be comfy

Thanks. :)

**Comment by ImaginationSuperHero528** [comment]
Fun Fact the buttons we're made with an xml Spritesheet I checked.
