### ISSUE TITLE
camera zoom event on beat  thru lua

### ISSUE THREAD

**Issue by mludimods** [ShadowMario/FNF-PsychEngine#7896]
### What is your question?

i was wondwering if its possible to do camere bop to beat after certain curbeat.

**Comment by PedroNinjaM** [comment]
that freak thing works?

**function onEvent(name, value1, value2)
    if name == 'CameraZoomStuff' then
        setProperty('defaultCamZoom', (value1));
        setProperty('cameraSpeed', (value2))
    end
end**

**Comment by mludimods** [comment]
> end

but do i need to put numbers in these values or not?

**Comment by PedroNinjaM** [comment]
> > end
> 
> but do i need to put numbers in these values or not?

Its a Event, just put like an event,(1:valueofcamerazoom, 2:daspeed
