### ISSUE TITLE
fail again when building for linux

### ISSUE THREAD

**Issue by Pietrodjaowjao** [ShadowMario/FNF-PsychEngine#7897]
### What is your question?

Error: In file included from include/llua/Lua_helper.h:10,
                 from ./src/__boot__.cpp:754:
/media/pietro/Jogos/lime/linc_luajit/git//linc/linc_lua.h:12:10: fatal error: ../lib/Lua/src/lua.hpp: Arquivo ou diretório inexistente
   12 | #include "../lib/Lua/src/lua.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

i forgot how to fix

**Comment by im557** [comment]
what are you trying to build?

**Comment by Pietrodjaowjao** [comment]
Psych Engine

**Comment by devin503** [comment]
Did you install Lua? Try running ```sh
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
``` in a terminal.

**Comment by ShadowMario** [comment]
Run this in a terminal `haxelib git linc_luajit https://github.com/AndreiRudenko/linc_luajit`
