### ISSUE TITLE
ADD BACK DISSCUSIONS

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#7898]
### What feature do you want to get added on the **base** engine?

BRING THE DISSCUSIONS BACK PLEASE WE NEED IT

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by mayo78** [comment]
https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/1

**Comment by Mastercopper2346** [comment]
U BANNED ME

**Comment by Mastercopper2346** [comment]
@Mayo78

**Comment by Mastercopper2346** [comment]
MAYO

**Comment by GhostCyclo6286** [comment]
skill issue
