### ISSUE TITLE
Can I disable the zoom/lights of the menu?

### ISSUE THREAD

**Issue by AlexTheCat15** [ShadowMario/FNF-PsychEngine#7899]
### What is your question?

I want to know if I can disable the new zoom and color lights of the title and menu, because it kinda annoys me. If not, I'm keeping 0.5.2 I guess

**Comment by cherryiguess** [comment]
get fooled on april first!11!1!

**Comment by AlexTheCat15** [comment]
> get fooled on april first!11!1!

...
