### ISSUE TITLE
custom note sound from mods/sounds don't play

### ISSUE THREAD

**Issue by Johferson** [ShadowMario/FNF-PsychEngine#790]
### Describe your bug here.

my custom note doesn't play its custom sound from mods/(mymodname)/sounds directory.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

None

**Comment by FuseIsHere813** [comment]
playSound('soundname');

use this in the note type lua file.

**Comment by drakonieyah** [comment]
> playSound('soundname');
> 
> use this in the note type lua file.

He did, it's literally not playing for him.

**Comment by ShadowMario** [comment]
Yes, and you didn't show your code, you didn't show where you put the files, you didn't show anything at all.

**Comment by ShadowMario** [comment]
No replies, closing this.
