### ISSUE TITLE
hey, how do i switch the music in dialouge?

### ISSUE THREAD

**Issue by im557** [ShadowMario/FNF-PsychEngine#7901]
### Describe your problem here.

i know that it has to do with two dialouges but i dont know how to do it.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yep

**Comment by devin503** [comment]
I did something like this. Here's *basically* what I did, in the DialogueBoxPsych.hx file:

```haxe
typedef DialogueFile = {
	var dialogue:Array<DialogueLine>;
	@:optional var dialogueMusic:String;
}
```

The `@:optional` tag tells the compiler that the typedef can still function *without* the dialogue music variable. This means you don't have to adjust any existing dialogue JSONs in your game files to include the dialogueMusic variable.

*You can also just place a question mark in front of the variable name and achieve the same effect.*

Further in the file, in the actual class definition, I include these lines in the the `new` function:

```haxe
if (dialogueList.dialogueMusic != null) {
			if (FileSystem.exists(dialogueList.dialogueMusic)) {
					FlxG.sound.playMusic(dialogueList.dialogueMusic, 0);
					FlxG.sound.music.fadeIn(1, 0, 0.8);
			}
		}
```

*If you're compiling for web, I strongly recommend using OpenFL's Assets class (import `openfl.utils.Assets`) instead. The exists function remains the same, you just have to add `SOUND` after the dialogueMusic argument in the if statement.*
