### ISSUE TITLE
Game Closes when i play a song

### ISSUE THREAD

**Issue by Jsa010** [ShadowMario/FNF-PsychEngine#7903]
### Describe your bug here.

I Was Testing My Song With My Script But When I Put The Song The Game

### 'just closes'

Plz Fix that

### Command Prompt/Terminal logs (if existing)

```CMD```

### Are you modding a build from source or with Lua?

Source

### Did you edit anything in this build? If so, mention or summarize your changes.

idk

### EDIT
**i see many pepole have that problem,plz fix that :(**

**Comment by im557** [comment]
did you use a setproperty?

**Comment by Jsa010** [comment]
> show me the script

the script is not the problem (and no,theres no os. in the script)

**Comment by im557** [comment]
> > show me the script
> 
> the script is not the problem (and no,theres no os. in the script)

did you put the song in the right folder?

**Comment by Jsa010** [comment]
> did you put the song in the right folder?

yes :v

**Comment by devin503** [comment]
what are the actual *logs* though? `cmd` isnt a log.
