### ISSUE TITLE
|Show And Tell| I FIGURED OUT CHROMATIC ABBERATION USE FOR HUD AND GAME LIKE TABI! U MUST JUST DO THE CAMS 'game' AND 'hud' OR IT WILL APPEAR GREEN COLORED!

### ISSUE THREAD

**Issue by amogusgame** [ShadowMario/FNF-PsychEngine#7904]
### What is your question?

CODE POGGERSSSSSSS!
function onCreate()
    if lowQuality == false then
    addChromaticAbberationEffect('game')
    addChromaticAbberationEffect('hud')
    end
end
must use this build (it has icon bop of davus lol):
[icons and shaders Build.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8401804/icons.Build.zip)
there

**Comment by briyz** [comment]
i wanna use it but idk how

**Comment by CreativeUsernameAttempt** [comment]
you also gotta put the chrome offset, i think default is 0.005.

Something like this:
`addChromaticAbberationEffect('hud', 0.005)`

**Comment by CreativeUsernameAttempt** [comment]
Also, the build only has a exe. What am i supposed to do with only a  exe?

**Comment by amogusgame** [comment]
replace normal psych engine app with this but first rename the build to 'PsychEngine.exe'

**Comment by CreativeUsernameAttempt** [comment]
Oh well, that makes sense.

**Comment by Randomxdp** [comment]
I have some code that readds shaders that i got from discussions, i can make you a build of psych engine 0.5.2h with shaders if you need it

**Comment by yt-xmati** [comment]
i like how people are turning issues to discussions

**Comment by mayo78** [comment]
https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/1
