### ISSUE TITLE
The sustain note prevents healing (Source Code)

### ISSUE THREAD

**Issue by FletchunterMC108338** [ShadowMario/FNF-PsychEngine#7906]
### Describe your problem here.

I need this thing for my mod. Also, what happened to the discussion?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited Playstate.hx to add a health system.

**Comment by Mastercopper2346** [comment]
idk

**Comment by Mastercopper2346** [comment]
mabe something in strumlinenotes.hx will help
