### ISSUE TITLE
Will the discussion ever come back?

### ISSUE THREAD

**Issue by IRIHAYA** [ShadowMario/FNF-PsychEngine#7908]
### What is your question?

I quite liked the PsychEngine discussion.

**Comment by Meme1079** [comment]
if it's not coming back then am jumping off a cliff

**Comment by MR-FNF** [comment]
> if it's not coming back then am jumping off a cliff

me too

**Comment by Pico8430** [comment]
Again, ShadowMario confirmed that the discussions are not coming back due to how hard it is to moderate.

**Comment by hayfii** [comment]
> > if it's not coming back then am jumping off a cliff
> 
> me too

miter ef en ef is beck??

**Comment by artycity** [comment]
Discussion is best place with codes
I hope that there will be people who will create discussions

**Comment by mayo78** [comment]
https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/1
