### ISSUE TITLE
How do I add a change stage event in Psych Engine SOURCE CODE?

### ISSUE THREAD

**Issue by IceTomPlayz** [ShadowMario/FNF-PsychEngine#7909]
### What is your question?

Maybe like an event or a LUA script that changes the stage at a step.

**Comment by hayfii** [comment]
OnlyHayfi#3608 I'll help you out!!!111!!

**Comment by IceTomPlayz** [comment]
Please Help me out.

Do you have the code?

**Comment by IceTomPlayz** [comment]
I friended you on discord.

**Comment by zeadd21g1233** [comment]
i want code i hate lua

**Comment by frantastic24** [comment]
just look at a mod's source, making this an event is impractical

**Comment by zeadd21g1233** [comment]
WHAT MOD HAVE STAGE CHANGE

**Comment by frantastic24** [comment]
Technically none, since it's not possible. What mods do is make assets visible and invisible, see Doki Doki Takeover, Sonic.EXE, Hex, QT

**Comment by IceTomPlayz** [comment]
wdym?

**Comment by zeadd21g1233** [comment]
lol i do doki doki  takeover port to psych engine

**Comment by keanu64github** [comment]
same @zeadd21g1233

**Comment by keanu64github** [comment]
https://user-images.githubusercontent.com/59621417/161463590-1e05d76a-aed6-4bf9-8535-64326c41f2e3.mp4

like this right?

**Comment by frantastic24** [comment]
[Are we showing off DDTO recreations](https://youtu.be/LM7TM67zoYs)
