### ISSUE TITLE
My custom options in ClientPrefs.hx are not working

### ISSUE THREAD

**Issue by enjayar625** [ShadowMario/FNF-PsychEngine#7911]
### Describe your problem here.

The title explains everything

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Project.xml, Playstate.hx, MainMenuState.hx, FreeplayState.hx, FlashingState.hx, ClientPrefs.hx

**Comment by Randomxdp** [comment]
Are you talking about the options or the saves?
ClientPrefs manages loading and saving data
The options code is in the folder options and if you want to add an option you should edit the options code too

**Comment by enjayar625** [comment]
> Are you talking about the options or the saves? ClientPrefs manages loading and saving data The options code is in the folder options and if you want to add an option you should edit the options code too

Where is the folder options

**Comment by Randomxdp** [comment]
> > Are you talking about the options or the saves? ClientPrefs manages loading and saving data The options code is in the folder options and if you want to add an option you should edit the options code too
> 
> Where is the folder options

On the source code

**Comment by enjayar625** [comment]
> > > Are you talking about the options or the saves? ClientPrefs manages loading and saving data The options code is in the folder options and if you want to add an option you should edit the options code too
> > 
> > 
> > Where is the folder options
> 
> On the source code

Which file is it

**Comment by Randomxdp** [comment]
Bruh source/options/

**Comment by enjayar625** [comment]
> Bruh source/options/

Oh
Ok
I thought it was an individual file lol
