### ISSUE TITLE
Is there a *chance* of discussions coming back?

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#7913]
### What is your question?

This is not a request to bring discussions back, this is simply a question asking whether discussions will ever come back in the future, as I found it incredibly useful up until the spam begun.

**Comment by lolbruhfart** [comment]
is it gone because of that? i heard its coming back and it was a part of the april fools

**Comment by ItsCapp** [comment]
> is it gone because of that? i heard its coming back and it was a part of the april fools

it's gone because of people like you.

**Comment by lolbruhfart** [comment]
> > is it gone because of that? i heard its coming back and it was a part of the april fools
> 
> it's gone because of people like you.

yeah but somebody messaged shadow and he said that it will comeback

**Comment by nobody23341** [comment]
shit,i just ask a question about PE Engine's complain problem,and it remove now,i will never know whats the answer,fuc-
fuck spam

**Comment by dxedpoke** [comment]
Honestly, I don’t think discussions is coming back, but there was a lot of helpful things on there, instead of the spam post

**Comment by Stilic** [comment]
A possible alternative would be [the Funkin Forum](https://www.funkinforum.com).

**Comment by artycity** [comment]
Discussions are a great place for those who don't know like me.
(pls dont spam with os scripts)

**Comment by mayo78** [comment]
https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/1

**Comment by ShadowMario** [comment]
> yeah but somebody messaged shadow and he said that it will comeback

![image](https://user-images.githubusercontent.com/44785097/161451228-a21f81fd-a98f-4226-8348-d5d56b60391f.png)

**Comment by Pico8430** [comment]
I knew they were about to close it lmao

**Comment by Theoyeah** [comment]
> > yeah but somebody messaged shadow and he said that it will comeback
> 
> ![image](https://user-images.githubusercontent.com/44785097/161451228-a21f81fd-a98f-4226-8348-d5d56b60391f.png)

Unfunni + wrong day for deleting discussions + you're swearing + Dindn't ask **lol**
