### ISSUE TITLE
Compile Issue For 0.5.2

### ISSUE THREAD

**Issue by LTZ-Knight** [ShadowMario/FNF-PsychEngine#7915]
### Describe your problem here.

When i try to compile the game in versions 0.5.1 and above, it says its creating the applicationmain.exe but then nothing happens, im wondering if someone can help? I know its only 0.5.1 and above because i downloaded the version 0.4.9 and it was just fine.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not edit anything

**Comment by hayfii** [comment]
1. Did you check the export folder?
2. Did you compile correctly?
3. Check your source code.

The game could be crashed.

**Comment by LTZ-Knight** [comment]
Turns out i have visual studio code 2021 and i downgraded to 2019 and it worked
