### ISSUE TITLE
[Archive] Character Selector, NoteSkin Selector, SideInfo, Complex Accuracy, and Watermark

### ISSUE THREAD

**Issue by Meme1079** [ShadowMario/FNF-PsychEngine#7916]
### What is your question?

not a question lol here's the download

[Archive.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8402644/Archive.zip)

**Comment by VSDaveandBambiFan900** [comment]
Omg you're the best, thank you now I have the watermark script!

**Comment by Nork1234** [comment]
This seems useful! Thanks!
