### ISSUE TITLE
Help me![complie problem]

### ISSUE THREAD

**Issue by nobody23341** [ShadowMario/FNF-PsychEngine#7917]
### Describe your problem here.

**i actually submit it before in dis but its remove so i guess i cant never see the answer**
so im trying to build the Engine but i cant download discordrpc,its just stuck,and i cant complie.
when i trying to download it,its stuck.
but i need it to complie.I try to manual download it ,but i dont know how.
i guess its the internet problem,so pls tell me how to download discordrpc without git.
p.s:
i try to manual download before and seems ok,but when i try to build,it just tell me""Error: DiscordRpc.cpp
C:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/linc_discord_rpc.h(7): fatal error C1083: Can't open files include: “../lib/discord-rpc/include/discord-rpc.h”: No such file or directory

Error: linc_discord_rpc.cpp
C:\HaxeToolkit\haxe\lib\discord_rpc\git\linc\linc_discord_rpc.h(7): fatal error C1083: Can't open files include: “../lib/discord-rpc/include/discord-rpc.h”: No such file or directory

src/haxe/iterators/ArrayIterator.cpp
src/openfl/display/Shader.cpp [haxe,release]
src/IntIterator.cpp
src/flixel/input/touch/FlxTouch.cpp
p.s:i dont know English very well so sorry for any wrong.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing.

**Comment by Mastercopper2346** [comment]
You didn't install everything

**Comment by Mastercopper2346** [comment]
try
`haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc`

**Comment by Mastercopper2346** [comment]
In the cmd.exe

**Comment by devin503** [comment]
> try `haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc`

This. Just run it from cmd or powershell.

**Comment by nobody23341** [comment]
![捕获](https://user-images.githubusercontent.com/96934698/161410829-6d3ea744-c996-4bb3-82e8-55d3deba9cd3.PNG)
i did it,damn it.

**Comment by nobody23341** [comment]
but its useless,still cant complain.

**Comment by nobody23341** [comment]
> > 尝试`haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc`
> 
> 这。只需从cmd或powershell运行它。

i tried before and its useless.
can anyone send me your discord rpc and file path?
i should try to download by myself instead of git.
i guess.

**Comment by devin503** [comment]
Try checking your Project.xml and see if the following line is commented (depicted by `<!--` in front, `-->` at the end).
```xml
<!-- vv IF THIS IS COMMENTED OUT, UNCOMMENT IT. vv -->
<haxelib name="discord_rpc" if="desktop" />
```
If that doesn't work, try setting an environment variable on your PC to point Haxe to your library.

1. Open the Start menu and type "sysdm.cpl", then press enter.
2. Click on the "Advanced" tab, then click "Environment variables"
3. Under "System variables", click New... and set it up as follows:

- Variable name: HAXE_STD_PATH
- Variable value: `C:\HaxeToolkit\haxe\std`
4. Click OK three times. Open a new powershell window and try compiling again.

**Comment by nobody23341** [comment]
> 尝试检查您的项目.xml并查看以下行是否已注释（在前面，末尾描绘）。`<!--``-->`
> 
> ```
> 
> <haxelib name="discord_rpc" if="desktop" />
> ```
> 
> 如果这不起作用，请尝试在电脑上设置一个环境变量，将 Haxe 指向你的库。
> 
> 1. 打开"开始"菜单并键入"sysdm.cpl"，然后按 Enter。
> 2. 单击"高级"选项卡，然后单击"环境变量"
> 3. 在"系统变量"下，点击新建...并按如下方式进行设置：
> 
> * 变量名称：HAXE_STD_PATH
> * 变量值：`C:\HaxeToolkit\haxe\std`
> 
> 4. 单击"确定"三次。打开一个新的 powershell 窗口，然后再次尝试编译。
![捕获](https://user-images.githubusercontent.com/96934698/161412866-97b6a0b0-4e86-43b9-ab54-67908f8e6395.PNG)

**Comment by nobody23341** [comment]
> Try checking your Project.xml and see if the following line is commented (depicted by `<!--` in front, `-->` at the end).
> 
> ```
> 
> <haxelib name="discord_rpc" if="desktop" />
> ```
> 
> If that doesn't work, try setting an environment variable on your PC to point Haxe to your library.
> 
> 1. Open the Start menu and type "sysdm.cpl", then press enter.
> 2. Click on the "Advanced" tab, then click "Environment variables"
> 3. Under "System variables", click New... and set it up as follows:
> 
> * Variable name: HAXE_STD_PATH
> * Variable value: `C:\HaxeToolkit\haxe\std`
> 
> 4. Click OK three times. Open a new powershell window and try compiling again.

`source/Achievements.hx:324: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/MainMenuState.hx:66: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:315: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/CharacterEditorState.hx:94: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/DialogueCharacterEditorState.hx:82: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:145: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:180: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:221: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:515: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:483: characters 37-56 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:484: characters 31-47 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:646: characters 10-42 : Warning : Std.is is deprecated. Use Std.isOfType instead.
source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

Compiling group: haxe
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/ -IC:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/ -I F:/PSYCH/FNF-PsychEngine-main/source/vlc/cpp/include/ -I F:/PSYCH/FNF-PsychEngine-main/source/vlc/cpp/src/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdF:\PSYCH\FNF-PsychEngine-main\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/discord_rpc/DiscordRpc.cpp
 - src/lime/_internal/macros/AssetsMacro.cpp
 - src/openfl/media/SoundTransform.cpp  [haxe,release]
 - src/lime/graphics/opengl/ext/OES_vertex_half_float.cpp
 - src/flixel/system/debug/_FlxDebugger/GraphicDrawDebug.cpp
 - src/lime/text/harfbuzz/HB.cpp
 - src/flixel/input/gamepad/id/XInputID.cpp
 - src/openfl/_Vector/FunctionVector.cpp  [haxe,release]
 - src/lime/media/openal/_ALAuxiliaryEffectSlot/ALAuxiliaryEffectSlot_Impl_.cpp
 - src/lime/utils/AssetCache.cpp  [haxe,release]
 - src/flixel/addons/ui/interfaces/ICursorPointable.cpp
 - src/lime/graphics/opengl/ext/EXT_multi_draw_arrays.cpp
 - src/lime/graphics/opengl/ext/NV_fence.cpp
 - C:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/linc_discord_rpc.cpp
 - src/flixel/input/gamepad/FlxGamepadAnalogStick.cpp
 - src/__boot__.cpp
 - src/flixel/addons/ui/interfaces/IFlxUIClickable.cpp
 - src/lime/media/openal/_ALContext/ALContext_Impl_.cpp
 - src/flixel/util/FlxUnicodeUtil.cpp
 - src/flixel/util/_FlxDirection/FlxDirection_Impl_.cpp
 - src/openfl/utils/_CompressionAlgorithm/CompressionAlgorithm_Impl_.cpp
**Error: DiscordRpc.cpp
C:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/linc_discord_rpc.h(7): fatal error C1083: Can't open files include: “../lib/discord-rpc/include/discord-rpc.h”: No such file or directory**
`
i guess there is only one error?Maybe its work but we still have one error
anyway thank you,but i still have an error,shit.

**Comment by devin503** [comment]
Hm. That's strange.

**Comment by nobody23341** [comment]
> 嗯，这很奇怪。

yes?
im going to maddddddddddddddddddddddd for it

**Comment by nobody23341** [comment]
> 嗯，这很奇怪。

can u send the discordrpc file and tell where i should put it?
i guess i should manual download it now.
