### ISSUE TITLE
Cross-Character Animation Ghosting

### ISSUE THREAD

**Issue by KindOfASpork** [ShadowMario/FNF-PsychEngine#7918]
### What feature do you want to get added on the **base** engine?

simply put, you use an animation ghost from a different character as a reference on another character.
for example, if i want to use the Change Character event to change expressions on a character (example: TGT Sonic and his expressions), being able to cross-reference each character within the editor to make sure that each expression is aligned properly would be more convenient and would require less blind guessing.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ImaginationSuperHero528** [comment]
YES PLEASE

**Comment by devin503** [comment]
that would honestly be useful as FUCK. 

~~maybe i'd finally be able to shitpost with eduardo more often if that was a thing... /j~~
