### ISSUE TITLE
Easter egg title screen overlapping with vocals

### ISSUE THREAD

**Issue by TechnikTil** [ShadowMario/FNF-PsychEngine#7920]
### Describe your bug here.

When you play a song from freeplay and then do any of the title screen secrets after this will happen:
[Click here for the video because mkv isnt supported :(](https://youtu.be/P2lfkHDV-Y0)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I think this is just a bug in the game itself, because i've not edited anything regarding with the title screen.

**Comment by ActualeAnEggDog** [comment]
lua working only in song, you need source

**Comment by TechnikTil** [comment]
OMG, THX ShadowMario!!

**Comment by Lsoissus** [comment]
> lua working only in song, you need source

bro its a bug, not a question, hes modding with lua, he didnt mention anything about editing it with lua
