### ISSUE TITLE
Stage Animation not syncing to beat of music

### ISSUE THREAD

**Issue by Cubism-2** [ShadowMario/FNF-PsychEngine#7921]
### Describe your problem here.

I added an animated asset to the stage, which is supposed to play the animation on every beat. I put in the required code, the animation works and all, but it doesn't sync. Here's the code:  

function onCreate()
	  -- background shit
  
	  makeLuaSprite('stageSky', 'outsideStage/StageSky', -800, -350);
	  setScrollFactor('stageSky', 0.2, 0.2);
	  scaleObject('stageSky', 0.7, 0.7);
	  addLuaSprite('stageSky', false);
	  
	  makeLuaSprite('stageDirt', 'outsideStage/StageDirt', -1600, -900);
	  setScrollFactor('stageDirt', 1, 1);
	  scaleObject('stageDirt', 2, 1.5);
	  addLuaSprite('stageDirt', false);
  
	  makeLuaSprite('stageFence', 'outsideStage/StageFence', -1600, -1450);
	  setScrollFactor('stageFence', 1, 1);
	  scaleObject('stageFence', 2, 2);
	  addLuaSprite('stageFence', false);
  
	  makeLuaSprite('stageConcrete', 'outsideStage/StageConcrete', -1600, -1225);
	  setScrollFactor('stageConcrete', 1, 1);	
	  scaleObject('stageConcrete', 2, 1.8);
	  addLuaSprite('stageConcrete', false);
  
	  makeLuaSprite('stageShadow', 'outsideStage/StageShadow', -1600, -1450);
	  setScrollFactor('stageShadow', 1, 1);
	  scaleObject('stageShadow', 2, 2);
	  addLuaSprite('stageShadow', false);
  
	  makeLuaSprite('stageBox', 'outsideStage/StageBox', -500, -50);
	  setScrollFactor('stageBox', 1, 1);
	  addLuaSprite('stageBox', false);
  
	  makeAnimatedLuaSprite('kyleSitting', 'outsideStage/Kyle Sitting', -500, -50);
	  addAnimationByPrefix('kyleSitting', 'first', 'Kyle Sitting idle', 24, true);
	  objectPlayAnimation('kyleSitting', 'first');
	  setScrollFactor('kyleSitting', 1, 1);
	  addLuaSprite('kyleSitting', false);
	  
  
	  setObjectOrder('stageDirt', 1);
	  setObjectOrder('gfGroup', 2);
	  setObjectOrder('stageBox', 3);
	  setObjectOrder('kyleSitting', 4);
	  setObjectOrder('stageFence', 5);
	  setObjectOrder('stageConcrete', 6);
	  setObjectOrder('stageShadow', 7);
	  setObjectOrder('boyfriendGroup', 8);
	  setObjectOrder('dadGroup', 8);
	  
	  close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
  end
  
  function onBeatHit()
  
	  if curBeat % 2 == 0 then
		  objectPlayAnimation('kyleSitting', 'first');
	  end
  end

Can someone help me out? Thanks

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Cubism-2** [comment]
Note: the first two times, the animation does sync, but it doesn't sustain. How do I fix that?

**Comment by frantastic24** [comment]
Don't use `close()` and don't make your animation loop

**Comment by Cubism-2** [comment]
I removed the close, but that didn't work. How do I make it not loop?

**Comment by Cubism-2** [comment]
I got it working. Thank you

**Comment by Cubism-2** [comment]
Nevermind. It's not working

**Comment by frantastic24** [comment]
Then you didn't fix it
[Don't make it loop](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#addanimationbyprefixtagstring-namestring-prefixstring-framerateint--24-loopbool--true)
