### ISSUE TITLE
Guys, its done ):

### ISSUE THREAD

**Issue by Theoyeah** [ShadowMario/FNF-PsychEngine#7923]
### What is your question?

discussions wont come back 
![image](https://user-images.githubusercontent.com/97792861/161395713-2c4a8b9d-0ad0-4000-912b-6d637d51492a.png)
):
):

**Comment by ImaginationSuperHero528** [comment]
Close this

**Comment by im557** [comment]
close this

**Comment by mayo78** [comment]
https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/1
