### ISSUE TITLE
pause on lost focus

### ISSUE THREAD

**Issue by mayo78** [ShadowMario/FNF-PsychEngine#7924]
### What feature do you want to get added on the **base** engine?

add an option to pause in game when you lose focus :)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by BeastlyGhost** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/pull/4446
this PR does it
