### ISSUE TITLE
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 

### ISSUE THREAD

**Issue by megasssdev** [ShadowMario/FNF-PsychEngine#7928]
### What is your question?

shadow mario removing the discussions tab not knowing that people are going to spam the issues tab
![image](https://user-images.githubusercontent.com/61982239/161400682-d789baa1-0e49-4ff0-91ae-0a92e0edb4c7.png)

**Comment by Jsa010** [comment]
### LoL

**Comment by mayo78** [comment]
https://github.com/mayo78/PSYCHDISCUSSIONS/discussions

**Comment by megasssdev** [comment]
> https://github.com/mayo78/PSYCHDISCUSSIONS/discussions

i know, i have joined
