### ISSUE TITLE
How to change application name in fnf psych engine no source code

### ISSUE THREAD

**Issue by Browniegaming1234** [ShadowMario/FNF-PsychEngine#7930]
### What feature do you want to get added on the **base** engine?

I've been trying to change the application name but there's really no tutorials so I was just asking if somebody can help me

### To test your sight, and reliability, please select the option of what should NOT be requested.

Idk

**Comment by Browniegaming1234** [comment]
Please Do not curse in Commets though.

**Comment by Lsoissus** [comment]
how did you fail the test

**Comment by mayo78** [comment]
you cant freaking do that you freaking dumb poo poo head!

**Comment by Browniegaming1234** [comment]
Ok
Thank you for telling me this, mayo78 and Lsoissus Now I know C:

**Comment by Browniegaming1234** [comment]
And I was just asking you don't have to be like poo poo head

**Comment by the-funky-lad** [comment]
its impossible without source

**Comment by poobie1** [comment]
> its impossible without source

no it isn't `setPropertyFromClass("openfl.Lib", "application.window.title", "YOUR TEXT HERE")`

**Comment by sanyachurs** [comment]
basically, you just
function onCreate()
	setPropertyFromClass("openfl.Lib", "application.window.title", "Now Playing " .. (songName))
end
function onDestroy()
	setPropertyFromClass("openfl.Lib", "application.window.title", "In The Menus")
end

**Comment by ivanchodenev** [comment]
its so easy doing it in source

**Comment by hayfii** [comment]
> its impossible without source

You never heard of setProperty/setPropertyFromClass right?
