### ISSUE TITLE
psych engine crash

### ISSUE THREAD

**Issue by lyke916** [ShadowMario/FNF-PsychEngine#7932]
### Describe your bug here.

psych engine keeps crashing whenever i load in a custom character

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

mods folder

**Comment by PrismLight** [comment]
Do you have the animations: singLEFT, singDOWN, singUP, singRIGHT, idle
Without those animations, the game will crash with that character equipped.

**Comment by Wither362** [comment]
Maybe you have a custom animation that doesn’t make _sense_, to **me** also happened, so maybe you have to **delete** that animation
