### ISSUE TITLE
Music changing in the middle of dialogue (Lua)

### ISSUE THREAD

**Issue by Draconic-Hybrid** [ShadowMario/FNF-PsychEngine#7933]
### What is your question?

Is there a way to change music in the middle of dialogue in Lua? If there isn't, that's fine. But I feel like the music switching with the mood of the conversation could really help out with the situation occurring in the story.

**Comment by devin503** [comment]
Try something like this. I don't know if it works, as I just came up with it in my head. If it doesn't, let me know or try experimenting to find something that works. I'm not the greatest with Lua.
```lua
function onCreate()
-- if you use onCreate just add the line below to it
  local switchedMusic = false
end
function onUpdatePost(elapsed)
--if you use this function already just add this to it lol
    if getProperty('dialogueCount') >= SOME_NUMBER and not switchedMusic then
        setProperty(switchedMusic, true);
        playMusic('YOUR_MUSIC_HERE');
    end
end
```

**Comment by Draconic-Hybrid** [comment]
> Try something like this. I don't know if it works, as I just came up with it in my head. If it doesn't, let me know or try experimenting to find something that works. I'm not the greatest with Lua.
> 
> ```lua
> function onCreate()
> -- if you use onCreate just add the line below to it
>   local switchedMusic = false
> end
> function onUpdatePost(elapsed)
> --if you use this function already just add this to it lol
>     if getProperty('dialogueCount') >= SOME_NUMBER and not switchedMusic then
>         setProperty(switchedMusic, true);
>         playMusic('YOUR_MUSIC_HERE');
>     end
> end
> ```

I'm afraid that'll be a "no". Thanks for trying.

**Comment by Shelvsk** [comment]
try this

```
function onCreate()
-- if you use onCreate just add the line below to it
   local musicSwitched = false
end

function onNextDialogue(count)
--if you use this function already just add this to it
    if count >= SOME_NUMBER and not musicSwitched then
        musicSwitched = true;
        playMusic('YOUR_MUSIC_HERE', 1, true);
    end
end
```

**Comment by Draconic-Hybrid** [comment]
Works! Thanks!
