### ISSUE TITLE
Custom note skin

### ISSUE THREAD

**Issue by bacondanger** [ShadowMario/FNF-PsychEngine#7934]
### Describe your problem here.

I made a Custom note skin sprite and every time I import the sprite in the song it changes the sprite locations with others. (note confirm changed to note pressed, etc). I tried fixing it by changing the sprite location in the XML file but it wasn't working. Is there any way I can fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i didn't edit any of the main files

**Comment by devin503** [comment]
Try making sure your XML animation names are correct. You can find the correct names in [Note](source/Note.hx), though there's an FLA out there with the correct names as well.

**Comment by bacondanger** [comment]
> 

thank you I will try

**Comment by bacondanger** [comment]
BRO, IT'S SO STUPID.

I made the sprite sheet with the notes named green blue red purple when I shouldn't have.

THANK YOU SO MUCH.

**Comment by bacondanger** [comment]
to anyone having this problem do not export redddd greeeen, blueeee and change pruiple to purple then export for proper results.  also, use these fla's in the comments: https://gamebanana.com/questions/13375
