### ISSUE TITLE
Skip Time appears inconsistently (0.5.2h)

### ISSUE THREAD

**Issue by Soufon** [ShadowMario/FNF-PsychEngine#7935]
### Describe your bug here.

When starting a song in Charting Mode, the Skip Time option doesn't seem to appear most of the time, might have something to do with Practice Mode or restarting the song?
![skip](https://user-images.githubusercontent.com/89232474/161407347-50fe075f-ad25-40fd-86cf-8cb882ebe1a5.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by BerdlyEC** [comment]
Is in 0.5.2h

**Comment by Soufon** [comment]
That's the version i'm using, yeah.

**Comment by cmallrt** [comment]
as far as I know, you can only skip time when the music starts playing (after the countdown)
