### ISSUE TITLE
Per-Song Pause Menu Music

### ISSUE THREAD

**Issue by Shadyyam** [ShadowMario/FNF-PsychEngine#7937]
### Describe your problem here.

I'm trying to change the pause menu music based on what song you're playing, but I'm not sure how to go about it.
Replacing the pause menu audio isn't perfect since it doesn't allow for multiple different songs in one mod folder.

I thought I could probably do something with the playMusic thing in lua, but I'm not smart enough to make it work.

If anybody could help out that'd be appreciated!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by devin503** [comment]
Hmm. I looked at the functions available in the Lua API and came up with this. Let me know if it works.

```lua
function onPause()
    playMusic('YourSound', Volume, Loop)
end
```

If it doesn't, I can attempt to find another solution.

**Comment by Shadyyam** [comment]
> If it doesn't, I can attempt to find another solution.

I tried something similar earlier, it seems like it just disables the pause button when using onPause.
Seems to be a way to not break the game when doing it judging by the description of onPause but idk

**Comment by devin503** [comment]
Hm. Try adding `return Function_Continue()` after the music line. That **should** allow you to pause the game, if the onPause description is correct.

**Comment by Shadyyam** [comment]
I've gotten in working as far as pausing and unpausing, but I think that the default pause menu song is conflicting with it.

I was planning on replacing it with an empty audio file but it seems to interfere with  the other music if it's also playing.
That or I'm going the playMusic thing wrong.

function onPause()
    playMusic('KlydePause', 1, true)
    debugPrint('Paused')
    return Function_Continue()

end

function onResume()
    debugPrint('Resumed')
    return Function_Continue()
end

**Comment by frantastic24** [comment]
```lua
function onCreate()
    setPropertyFromClass('PauseSubState', 'songName', 'music') --song must be in /music
end
```

**Comment by Shadyyam** [comment]
> ```lua
> function onCreate()
>     setPropertyFromClass('PauseSubState', 'songName', 'music') --song must be in /music
> end
> ```

Works perfectly.
Thank you both for the help!

**Comment by Winkwing** [comment]
Yo, this doesn't seem to work?
Or, well, like, where do I put this?

**Comment by zeeblox09** [comment]
> Yo, this doesn't seem to work?
> Or, well, like, where do I put this?

yeah i get the scripting but where do i put the file? like is it in mods/scripts or mods/data/song-name
