### ISSUE TITLE
I wanna add the wavy shits to psych 0.5.2h but I can't find the lua stuffs in source

### ISSUE THREAD

**Issue by GhostCyclo3999** [ShadowMario/FNF-PsychEngine#7938]
### Describe your problem here.

So I can't find it, cuz I've tried searching "addGlitchEffect" alot of times AND NOTHING POPS UP.
And I wanna add it to my engine in 0.5.2h cuz some people might use it, so please, I want the code.
(no seriously, i cant find it fr)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing, Just trying to add wavy shits but I can't and I need the wavy shits from bbpanzu's stream.

**Comment by Lsoissus** [comment]
uh they deleted the shaders in 0.5.2 because they were buggy as hell, try finding a way to add shaders back in [i suck at source so i  cant help with coding]

**Comment by hayfii** [comment]
use the action build dude -_-

**Comment by mayo78** [comment]
> uh they deleted the shaders in 0.5.2 because they were buggy as hell, try finding a way to add shaders back in [i suck at source so i cant help with coding]

they weren't buggy, its just that the devs didnt have permission to use them

**Comment by SonicProYT** [comment]
> > uh they deleted the shaders in 0.5.2 because they were buggy as hell, try finding a way to add shaders back in [i suck at source so i cant help with coding]
> 
> they weren't buggy, its just that the devs didnt have permission to use them

actuallu,  it was **bbpanzu** adding it, **he** didnt have permission to use them
