### ISSUE TITLE
A bunch of modchart problems (for loops, note tweening)

### ISSUE THREAD

**Issue by YKoF-CALm** [ShadowMario/FNF-PsychEngine#7940]
### Describe your problem here.

So I'm trying to make some arrow movements, and I wanted to use for loops, since the last time I did arrow movements, it was a pain putting 4 lines of the same tween for 8 different notes. However, as of now, only the spinning works, but the movements (noteTweenX and noteTweenY) don't.

Here's the spinning code (using noteTweenAngle):
```
if curStep == 120 or curStep == 248 or curStep == 375 or curStep == 632 or curStep == 696 or curStep == 824 or curStep == 952 or curStep == 1208 then
        for i=0,3 do
            noteTweenAngle('n5oa'..i, i, getPropertyFromGroup('opponentStrums', i, 'angle') + 360, 0.3, 'linear')
            noteTweenAngle('n5pa'..i, i+4, getPropertyFromGroup('playerStrums', i, 'angle') + 360, 0.3, 'linear')
        end
end
```

And here is one of the movements code (using both noteTweenX and noteTweenY):
```
if l1 then
        for i=0,3 do
            noteTweenX('l1ox'..i, i, defaultOpponentStrumX..i + 50 * math.sin((curBeat + i*0.32)), 0.1, 'linear')
            noteTweenY('lioy'..i, i, defaultOpponentStrumY..i + 10 * math.cos((curBeat + i*0.25) * math.pi), 0.1, 'linear')
            noteTweenX('l1px'..i, i+4, defaultPlayerStrumX..i + 50 * math.sin((curBeat + (i+4)*0.32)), 0.1, 'linear')
            noteTweenY('lipy'..i, i+4, defaultPlayerStrumY..i + 10 * math.cos((curBeat + (i+4)*0.25) * math.pi), 0.1, 'linear')
        end
end
```

(Note that l1 is set to true at step 256 and false at step 384, if you need the duration for how long this tween lasts for)
(Also, the spinning code is in onStepHit() while the movements code is from onUpdate(elapsed))

I think it might be the variables, what am I doing wrong here?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Your issue is in `defaultOpponentStrumX..i`, afaik you can't make it work like that
What you can do instead is store default strum positions in variables under `onCreatePost` and use those

**Comment by YKoF-CALm** [comment]
Hmm, I'm not sure how I would make that work. However, from what you're saying, I just have to use alternate variables that I can use i with. Maybe I could make it work with an array/list?

**Comment by frantastic24** [comment]
> Maybe I could make it work with an array/list?

that's how i do it, so yeah that works

**Comment by YKoF-CALm** [comment]
Alright, so I finally made it work, but I don't know if it's doing what I intended it to do. I'm trying to translate the modchart for Shinkyoku (Blantados' song) from Kade Engine to Psych Engine, but it doesn't seem to work well? Maybe it's because of different arrows.

How would you translate this piece of code to Psych Engine Lua for example?
```
for i=0,7 do
setActorX(_G['defaultStrum'..i..'X'] + 50 * math.sin((currentBeat + i*0.32)), i)
setActorY(_G['defaultStrum'..i..'Y'] + 10 * math.cos((currentBeat + i*0.25) * math.pi), i)
end
```

**Comment by YKoF-CALm** [comment]
I should probably change the issue name if I'm seemingly asking a different question (BTW I'm still trying to fix the modcharts, at this point, I'm not sure if for loops just don't like me in general and are FORCING me to do individual tweening, although I'm not sure individual tweens will even fix the problem).

**Comment by YKoF-CALm** [comment]
NVM, apparently I can't use curBeat for the tweens (since curBeat is usually an integer).
When doing tweens, seems like you need the following:
```
songPos = getSongPosition()
local currentBeat = (songPos/1000)*(bpm/60)
```
This returns a constant changing float, which changes more frequently than curBeat.
