### ISSUE TITLE
Custom libraries in Project.xml are not working

### ISSUE THREAD

**Issue by enjayar625** [ShadowMario/FNF-PsychEngine#7941]
### Describe your problem here.

Title explains everything

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Project.xml, Playstate.hx, MainMenuState.hx, FreeplayState.hx, FlashingState.hx, ClientPrefs.hx, CoolUtil.hx, Achievements.hx, GameplaySettingsSubState.hx, VisualsUISubState.hx

**Comment by enjayar625** [comment]
Why do people keep ignoring these issues

**Comment by frantastic24** [comment]
"title explains everything" (title explains nothing)

**Comment by enjayar625** [comment]
[Project.xml.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8440080/Project.xml.txt)

**Comment by enjayar625** [comment]
dammit why does no one care
