### ISSUE TITLE
FUNKY FRIDAY UNDERLAY SHIT IN LUA POG!!!1

### ISSUE THREAD

**Issue by amogusgame** [ShadowMario/FNF-PsychEngine#7942]
### What is your question?

**I MADE FUNKY FRIDAY BULLSHIT IN LUAAAAAAAAAAAAAA**
heres:
[ezyzip.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8404523/ezyzip.zip)

**Comment by amogusgame** [comment]
(i used ezyzip cuz my right click is broken and i cant use it anymore)

**Comment by megasssdev** [comment]
https://github.com/mayo78/PSYCHDISCUSSIONS/discussions

**Comment by kingyomoma** [comment]
yeah because funky friday invented scroll underlays ☠️

**Comment by Stilic** [comment]
no
