### ISSUE TITLE
how do i modify the menu in 0.5.2 without source code

### ISSUE THREAD

**Issue by Epiclol374** [ShadowMario/FNF-PsychEngine#7943]
### Describe your problem here.

help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by hayfii** [comment]
It's not possible bro, you can't access lua in main menu -_-

**Comment by cmallrt** [comment]
you can't do that without modifying the source :(

**Comment by frantastic24** [comment]
Close this 🤡

**Comment by vyroxhub** [comment]
holy shit even so with the discussions closed these dusts don't stop

**Comment by nbonnie2** [comment]
you cant use lua scripts outside of songs

**Comment by Epiclol374** [comment]
I managed to modify the menu without source XDDDD
