### ISSUE TITLE
BF and GF Duet (continued)

### ISSUE THREAD

**Issue by Draconic-Hybrid** [ShadowMario/FNF-PsychEngine#7944]
### Describe your problem here.

About #7936. I know I can just edit that request, but the problem changed on such a level that I might need a new issue for this.

Forcing girlfriend's offsets only breaks when there's **dialogue** involved. 
I don't know why this happens, I don't know how this happens, please help.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by frantastic24** [comment]
[You don't need to set offsets] (https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#characterplayanimcharacterstring-animstring-forcedbool--false)

**Comment by Draconic-Hybrid** [comment]
I forgot that existed. Whoops.
