### ISSUE TITLE
problem with source

### ISSUE THREAD

**Issue by meme286565** [ShadowMario/FNF-PsychEngine#7945]
### Describe your problem here.

im trying to compile the game but ive tried everything it told me to do and cmd stilll is not working plz help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no not yet

**Comment by travisgamemaker** [comment]
open powershell
type in 'cd' followed by the directory of the psych engine source folder (ex: cd C:\Users\user\Downloads\FNF-PsychEngine-0.5.2h\FNF-PsychEngine), then press enter.
next, type 'lime test' followed by your os (ex: lime test windows), then press enter.
the game should compile if everything is done correctly.
if it doesn't, respond with the error it gives you.

**Comment by meme286565** [comment]
so like cd C:\Users\user\Downloads\FNF-PsychEngine-0.5.2h\FNF-PsychEngine

**Comment by travisgamemaker** [comment]
yes but replace 'user' with your windows username

**Comment by meme286565** [comment]
'C:\Users\my user name\Downloads\FNF-PsychEngine-0.5.2h\FNF-PsychEngine' is not recognized as an internal or external command,
operable program or batch file.

**Comment by meme286565** [comment]
i keep on  getting this
