### ISSUE TITLE
image scroll event 

### ISSUE THREAD

**Issue by MuRaMiHa** [ShadowMario/FNF-PsychEngine#7948]
### What is your question?

Does such an event exist? Now I really need it, if you have it, or you know how to make it, please let me know.

**Comment by ItsCapp** [comment]
what do you mean by "image scroll"?

**Comment by MuRaMiHa** [comment]
> 

https://user-images.githubusercontent.com/58396598/161446385-681045ca-57ae-4f82-91bc-e5e7efa0a37c.mov

**Comment by Steve35117** [comment]
if lua:
doTweenY(image, 'image, 1000, 0.9, 'expoIn')
