### ISSUE TITLE
How to tie spritesheet to variable

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#7949]
### What is your question?

it sounds kinda confusing, but what I mean is if the variable `health` is 97 it would change an object's sprite to 
![image](https://user-images.githubusercontent.com/93293747/161444061-79ee0fc5-43da-4f6a-ac1c-948a260de272.png)
from this spritesheet
![HealthBar](https://user-images.githubusercontent.com/93293747/161444030-cb4270f8-54be-4354-9970-6d44fc60f07e.png)
[HealthBar.xml](https://github.com/ShadowMario/FNF-PsychEngine/files/8405304/HealthBar.txt)

so 
```
onUpdate()
   sprite = health
   changeGraphic?? to sprite
```

**Comment by frantastic24** [comment]
Multiply by 50, and it goes from 0 to 100

**Comment by ItsCapp** [comment]
it's a variable that I made for my health system, it has nothing to do with the actual health
