### ISSUE TITLE
Week 2 crashing

### ISSUE THREAD

**Issue by DrebDaDev** [ShadowMario/FNF-PsychEngine#795]
### Describe your bug here.

So i was testing week 2 for a mod im making, i added a song between south and monster, and after it ended, the game crashed before monster could load, i also changed the stage in monster if it helps

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

added a song before monster, changed the stage of monster

**Comment by FuseIsHere813** [comment]
Issue with your stage lua or json maybe.

**Comment by ShadowMario** [comment]
You can't change Monster's stage, it is needed for the Thunder sound effect to load.

**Comment by DrebDaDev** [comment]
k thanks
