### ISSUE TITLE
Do the Disscussion goes back to github site?

### ISSUE THREAD

**Issue by CoddingCat** [ShadowMario/FNF-PsychEngine#7951]
### What feature do you want to get added on the **base** engine?

I really need it back. theres was many tutorials whats help me.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Thing that would not cause problems

**Comment by Jsa010** [comment]
**[No But Take This](https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/1)**
