### ISSUE TITLE
Is There A Possible Way To code Achievements in Psych engine 0.5.1

### ISSUE THREAD

**Issue by bf244** [ShadowMario/FNF-PsychEngine#7952]
### Describe your problem here.

Is There A Possible Way To code Achievements in Psych engine 0.5.1

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Pico8430** [comment]
Check Achievements.hx.

**Comment by bf244** [comment]
I know that buy when i beat the week It doesent give me the achievement(i setter that i have ti beat a week to get the achievement
