### ISSUE TITLE
I need a event

### ISSUE THREAD

**Issue by IsThisProGamersX** [ShadowMario/FNF-PsychEngine#7954]
### What is your question?

How to change the opacity of the arrows?

**Comment by Draconic-Hybrid** [comment]
`noteTweenAlpha(tag:String, note:Int, value:Dynamic, duration:Float, ease:String)`

`tag` is whatever you want, so long as it isn't the same as another tag.

`note` is the target note to change. 0, 1, 2, 3 targets the opponent's Left, Down, Up, and Right arrows respectively, and 4, 5, 6, 7 target the player's Left, Down, Up, and Right arrows respectively.

`value` is the opacity level from 0 to 1. Self-explanatory there.

`duration` is the duration it takes to fade in or out to the stated value in seconds. Also self-explanatory.

`ease` is optional. [Here is a list of eases.](https://api.haxeflixel.com/flixel/tweens/FlxEase.html)

**Comment by cmallrt** [comment]
💀💀
