### ISSUE TITLE
can you add shaders

### ISSUE THREAD

**Issue by flaminghotpizza** [ShadowMario/FNF-PsychEngine#7955]
### What is your question?

i want you to add shaders like glitch effect and other stuff

**Comment by frantastic24** [comment]
no

**Comment by im557** [comment]
no

**Comment by kingyomoma** [comment]
no

**Comment by ActualeAnEggDog** [comment]
you need actions build

**Comment by ShadowMario** [comment]
In Lua? No.
In Source Code? Yes, but it's too lengthy for me to explain in a github issue.
