### ISSUE TITLE
Ayo what happen to discussions?

### ISSUE THREAD

**Issue by Eassah** [ShadowMario/FNF-PsychEngine#7956]
### What is your question?

I noticed that it's gone, why?

**Comment by Pico8430** [comment]
Because of how hard it is to moderate discussions, and ShadowMario already said it wont come back, it's permanently.

**Comment by Tikoulla** [comment]
> Because of how hard it is to moderate discussions, and ShadowMario already said it wont come back, it's permanently

frick how do i get the modcharts now

**Comment by meeptey2** [comment]
someone made their own discussions page for psych engine. https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/

**Comment by JDHjinxlovrr** [comment]
> > Because of how hard it is to moderate discussions, and ShadowMario already said it wont come back, it's permanently
> 
> frick how do i get the modcharts now

go to the official psych engine server? :trollface:

**Comment by hayfii** [comment]
> > Because of how hard it is to moderate discussions, and ShadowMario already said it wont come back, it's permanently
> 
> frick how do i get the modcharts now

make your own :trollface: LOL

**Comment by Pico8430** [comment]
If you want some help with lua scripts and questions, it's recommended to go to the official Psych Engine discord server. But if you don't want to enter the server or something like that, make your own code.
