### ISSUE TITLE
I can't put characters in 0.52h

### ISSUE THREAD

**Issue by squeeenoodle** [ShadowMario/FNF-PsychEngine#7957]
### Describe your bug here.

In 0.52h, I can't write character names or pose names, please help Shadow.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I made characters in it.

**Comment by keanu64github** [comment]
click r then retry

**Comment by squeeenoodle** [comment]
@keanu64github what do you mean how does that help

**Comment by keanu64github** [comment]
Click the “R” key on your keyboard, and try again.

**Comment by AlansGames** [comment]
Same, it won't let me input any text when i zoom in/out

**Comment by squeeenoodle** [comment]
@AlansGames no it wont left me type anyway

**Comment by squeeenoodle** [comment]
@keanu64github ok

**Comment by AlansGames** [comment]
It only works for me when you're character editing in the main menu

**Comment by squeeenoodle** [comment]
@keanu64github thanks
