### ISSUE TITLE
How to Get Player Input for which Note is pressed?

### ISSUE THREAD

**Issue by ohyeah388** [ShadowMario/FNF-PsychEngine#7958]
### What is your question?

I basically want to make a 'reverse' note where you have to hit the other side (Left is Right, down is up, etc.)
I know that noteData checks the actual note's direction, but how do you get the player's input?

**Comment by Soufon** [comment]
From the Wiki:
> keyJustPressed(name:String)
> Get if the key name just got pressed on the current frame.
> 
> Keys: 'left', 'down', 'up', 'right', 'accept', 'back', 'pause', 'reset', 'space'

**Comment by ohyeah388** [comment]
> From the Wiki:
> 
> > keyJustPressed(name:String)
> > Get if the key name just got pressed on the current frame.
> > Keys: 'left', 'down', 'up', 'right', 'accept', 'back', 'pause', 'reset', 'space'

Holy shit, can't believe I didn't see that before, thanks!
