### ISSUE TITLE
shaders  (custom build)

### ISSUE THREAD

**Issue by thecosmicgamer29** [ShadowMario/FNF-PsychEngine#7959]
### Describe your problem here.

so i know this is dumb but i have no idea how to use shaders i don't even know the names of the shaders

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no this is a build that works with shaders

**Comment by SonicProYT** [comment]
the most known being addGlitchEffect

**Comment by PedroNinjaM** [comment]
> 

shadow not removed?

**Comment by thecosmicgamer29** [comment]
> > 
> 
> shadow not removed?

its a custom build

**Comment by PedroNinjaM** [comment]
> > > 
> > 
> > 
> > shadow not removed?
> 
> its a custom build

ahh

**Comment by thecosmicgamer29** [comment]
me when the mario of the shadow close it
