### ISSUE TITLE
Dialogue after cutscene when?

### ISSUE THREAD

**Issue by Zogistra** [ShadowMario/FNF-PsychEngine#7960]
### What feature do you want to get added on the **base** engine?

When dude 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by enjayar625** [comment]
You can

**Comment by Stilic** [comment]
you failed the test

**Comment by KacperOSM** [comment]
https://user-images.githubusercontent.com/81757134/161582846-08eee245-16c7-4d37-946b-261c7f280efb.mov
