### ISSUE TITLE
source/TitleState.hx:400: characters 2-9 : Expected }

### ISSUE THREAD

**Issue by JVGamerzbz** [ShadowMario/FNF-PsychEngine#7961]
### Describe your problem here.

pls i need to fix this one.... everything was right and it says
source/TitleState.hx:400: characters 2-9 : Expected }

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by enjayar625** [comment]
Give the file

**Comment by Phoneguytech75** [comment]
> Expected }

put a }.

**Comment by JVGamerzbz** [comment]
> Give the file
[TitleState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8410507/TitleState.txt)

**Comment by Phoneguytech75** [comment]
I think you should change this part in Line 404 to this:
```haxe
if (FlxG.sound.music != null) {
	Conductor.songPosition = FlxG.sound.music.time;
	// FlxG.watch.addQuick('amp', FlxG.sound.music.amplitude);
}
```

**Comment by JVGamerzbz** [comment]
I see it now it's just I'm fucking dumb..... I didn't change the animation names of the custom gfdance when changing the title character...
