### ISSUE TITLE
Error When Compiled On Linux

### ISSUE THREAD

**Issue by Gibberditoslumber** [ShadowMario/FNF-PsychEngine#7962]
### Describe your bug here.

a non-exsistent SO file the exicutable

### Command Prompt/Terminal logs (if existing)

```bash
./PsychEngine: error while loading shared libraries: libluajit-5.1.so.2: cannot open shared object file: No such file or directory
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Gibberditoslumber** [comment]
this is being addresed now @ShadowMario

**Comment by Gibberditoslumber** [comment]
as since nobody has or uses linux

**Comment by Gibberditoslumber** [comment]
acept for me

**Comment by Gibberditoslumber** [comment]
i fixed my self

**Comment by TheKamboy** [comment]
If you are still having problems, I found a way to fix the bug. You have to install the libluajit-5.1-2 package if you are on Ubuntu or Debian.
