### ISSUE TITLE
how to let my own stage moved by using events

### ISSUE THREAD

**Issue by bz001** [ShadowMario/FNF-PsychEngine#7963]
### Describe your problem here.

i i want to know how to let my stage moved like the songs called "soul" in friday night fever by using events lua.
engine version:0.5.1
thanks!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
![fucktard](https://user-images.githubusercontent.com/44785097/163425241-2356ec96-dea7-40c0-bbad-709182550939.png)

**Comment by bz001** [comment]
eh,ok,i will take my free time to show you the video...




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月14日(星期四) 晚上11:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ShadowMario/FNF-PsychEngine] how to let my own stage moved by using events (Issue #7963)
