### ISSUE TITLE
Stage Change mid song

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#7964]
### Describe your problem here.

how do I Switch Stages Mid Song? I just need a code for it for the event. and I also need the Value 1 and Value 2 info so I can understand how to use it

I perfer to do this

Value 1: What stage Lua to switch to
Value 2: What stage JSON to switch to

Also give me your icon so I can credit you in my mod along with whatever social media you have. Doesn't matter what it is

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Ive added sprites, removed the weeks to create my own, and added a bunch of lua files such as scripts and custom notes, that's pretty much all I did

**Comment by frantastic24** [comment]
#3137

**Comment by SonicXFire1987** [comment]
That didn't help. what exactly am I supposed to do

**Comment by SonicXFire1987** [comment]
i wanted value 1 to switch to a lua
and value 2 to switch to a json

it didn't do anything. what exactly do i do with that information

**Comment by frantastic24** [comment]
Not possible

**Comment by SonicXFire1987** [comment]
nevermind im just dumb. my bad. sorry. but i figured it out so nevermind
