### ISSUE TITLE
Game Closes after jumpscare game over

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#7965]
### Describe your problem here.

How do I make the game close after a jumpscare plays for the game over screen?
I just need the code... nothing else

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Ive added sprites, removed the weeks to create my own, and added a bunch of lua files such as scripts and custom notes, that's pretty much all I did

**Comment by Phoneguytech75** [comment]
You need the source code

**Comment by SonicXFire1987** [comment]
what do I do in the source code to do that?

**Comment by Phoneguytech75** [comment]
Well you could add a if statement in the GameOverState like this:
```haxe
if (PlayState.SONG.song == 'scary-song') {
    playJumpscare();
    Sys.exit(0); // This will exit the game after the jumpscare is played.
}
```

**Comment by acap09** [comment]
you can check the length of the audio file then run a timer for that length of the audio file then you can exit (<0.5.1)

**Comment by SonicXFire1987** [comment]
> Well you could add a if statement in the GameOverState like this:
> 
> ```hx
> if (PlayState.SONG.song == 'scary-song') {
>     playJumpscare();
>     Sys.exit(0); // This will exit the game after the jumpscare is played.
> }
> ```

wait so I can't put this in a game over lua file?

**Comment by Phoneguytech75** [comment]
> > Well you could add a if statement in the GameOverState like this:
> > 
> > ```hx
> > if (PlayState.SONG.song == 'scary-song') {
> >     playJumpscare();
> >     Sys.exit(0); // This will exit the game after the jumpscare is played.
> > }
> > ```
> 
> wait so I can't put this in a game over lua file?

No because it's written in haxe. Unless you want to edit the FunkinLua.hx this is the only way.

**Comment by FacunMax** [comment]
> Well you could add a if statement in the GameOverState like this:
> 
> ```hx
> if (PlayState.SONG.song == 'scary-song') {
>     playJumpscare();
>     Sys.exit(0); // This will exit the game after the jumpscare is played.
> }
> ```

you saved me with this, now I can make customs game over as it should
