### ISSUE TITLE
Flash and Fade

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#7966]
### Describe your problem here.

How do I make the screen Flash and fade back to the game. I just need the code for it. and here's what i prefer the values be.

Value 1: how long the flash last
Value 2: The color (color code [9DCFED])

And i need your icon and social media so i can credit you. the social media doesn't really matter.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Ive added sprites, removed the weeks to create my own, and added a bunch of lua files such as scripts and custom notes, that's pretty much all I did

**Comment by keanu64github** [comment]
[FlashAndFadeEvents.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8432628/FlashAndFadeEvents.zip)
There you go!

**Comment by keanu64github** [comment]
Make sure to change where it says 'other' to 'game' if you want the arrows still visible.

**Comment by keanu64github** [comment]
close the issue lol
