### ISSUE TITLE
Is using the mouse buttons on freeplay and the pause menu possible on Lua?

### ISSUE THREAD

**Issue by Rudyrue** [ShadowMario/FNF-PsychEngine#7968]
### What is your question?

i've tried doing this for like 2 weeks now and im starting to question if it's even possible

no one on yt's made a script and im too dumb to continue this shit so

is it possible using the mouse on menus
and if so, has someone done it already

**Comment by kingyomoma** [comment]
.lua files cannot run on a menu (unless you edit the source of course, but that's out of the question)

**Comment by Rudyrue** [comment]
then is there a file for it working on the pause menu?

**Comment by acap09** [comment]
you can use onPause(), but there is no forever loop in pause menu, so you would have to runTimer(-tag-, 0.000001, 0);

**Comment by ActualeAnEggDog** [comment]
you cant lol, lua only in songs
