### ISSUE TITLE
How Dose Mods Work?

### ISSUE THREAD

**Issue by Gibberditoslumber** [ShadowMario/FNF-PsychEngine#7969]
### What is your question?

the title says it

**Comment by PrismLight** [comment]
It's to play mods without downloading 200mb or using source.

**Comment by Gibberditoslumber** [comment]
??

**Comment by bacondanger** [comment]
if you import your mod (or any downloadable mod and their unzipped folder) it allows you to play that mod

Example: https://gamebanana.com/mods/365489

download and unzip the file then put it in the mods folder.

also a tutorial: https://www.youtube.com/watch?v=4Ql4CqFauSY

**Comment by Pico8430** [comment]
I think you're new onto this mods thing.

Mods are obviously fnf mods that can be installed with Psych Engine 0.5 or higher, to do this you must have a mod that has only the files from the mods folder and not containing an executable and "assets".

Paste the folder that contains all the files and then put it onto your psych engine "mods" folder. Done.

**Comment by Gibberditoslumber** [comment]
it didn't work

**Comment by frantastic24** [comment]
skill issue

**Comment by Lorekeeper49** [comment]
For softcoded mods, you need to place the mod folder into mods/ and it should just load in, make sure though that you go into the mods section within the game itself and click 'enable all' on the mod you want to use as there might be assets in there that change other things besides just new songs
