### ISSUE TITLE
how to change background with lua

### ISSUE THREAD

**Issue by official-ys** [ShadowMario/FNF-PsychEngine#7970]
### What is your question?

how do i change backgrounds with lua
**i would prefer if its a custom event**

i have source and lua

**Comment by frantastic24** [comment]
Lua: #3137 
Source: look at any mod that does this effect lol, most if not all have a public repo

**Comment by zeadd21g1233** [comment]
i know go to your stage
and make another bg in stage but visble are false

and 
below
function BeatHit

if curBeat == 10 then
change visible to true in the new stage
and the normal stage visible false

and swap ciode

to get normall bg

bad tutorial

you can see monika exe mod

have the codes in stage

**Comment by zeadd21g1233** [comment]
i know go to your stage
and make another bg in stage but visble are false

and 
below
function BeatHit

if curBeat == 10 then
change visible to true in the new stage
and the normal stage visible false

and swap ciode

to get normall bg

bad tutorial

you can see monika exe mod

have the codes in stage
