### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by edwinvt** [ShadowMario/FNF-PsychEngine#7971]
### Describe your problem here.

hello there,how can i compile the source i do a lime test and i can't 
i tried other things and i fail help me please
i'm windows 10

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Phoneguytech75** [comment]
what is shown when you run lime test

**Comment by edwinvt** [comment]
It not reconize  the commandAnd i havehaxe Enviado desde Correo para Windows De: Phoneguytech75Enviado: martes, 5 de abril de 2022 4:57 a. m.Para: ShadowMario/FNF-PsychEngineCC: edwinvt; AuthorAsunto: Re: [ShadowMario/FNF-PsychEngine] compile (Issue #7971) what is shown when you run lime test—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Phoneguytech75** [comment]
could you like copy and paste what you saw instead of sending this.

**Comment by edwinvt** [comment]
Enviado desde Correo para Windows De: Phoneguytech75Enviado: miércoles, 6 de abril de 2022 3:17 a. m.Para: ShadowMario/FNF-PsychEngineCC: edwinvt; AuthorAsunto: Re: [ShadowMario/FNF-PsychEngine] compile (Issue #7971) could you like copy and paste what you saw instead of sending this.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Phoneguytech75** [comment]
> 2

I don't think you are ok

**Comment by reizoking** [comment]
Hey i need help from compiling psych

C:/HaxeToolkit/haxe/lib/flixel-ui/2,3,3/flixel/addons/ui/FlxUIPopup.hx:23: characters 13-19 : Field facing has different type than in flixel.IFlxSprite
C:/HaxeToolkit/haxe/lib/flixel/4,10,0/flixel/FlxSprite.hx:1418: characters 2-45 : ... Interface field is defined here
C:/HaxeToolkit/haxe/lib/flixel-ui/2,3,3/flixel/addons/ui/FlxUIPopup.hx:23: characters 13-19 : ... Int should be flixel.util.FlxDirectionFlags

if you dont know thats ok! :D

**Comment by Phoneguytech75** [comment]
Did you tamper with haxeflixel. Try reinstalling haxeflixel.
