### ISSUE TITLE
Extra covers Menu Problem

### ISSUE THREAD

**Issue by DrebDaDev** [ShadowMario/FNF-PsychEngine#7974]
### Describe your problem here.

Ok so basically i want to do an extra menu for all bonus songs/covers to be displayed in a separate menu, i copied the freeplay code and modified it to not show the freeplay weeks and display another list but i just cant get it to work in-game, whenever i try to access it through the main menu it shows an error related to "MusicBeatState" being linked to freeplay or something like that but i cant figure out how to make it work with the new menu can anybody help me?
im using 0.4.2 btw
[CoversMenu.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8414030/CoversMenu.zip)
[CoverData.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8414036/CoverData.zip)
![160230142-a8d65f7e-7f38-4c81-a119-622f1a286f53](https://user-images.githubusercontent.com/93683434/161658125-d3ce787b-19f8-4e47-baed-3d13a9c7cb22.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

tried to add a covers menu copying the freeplay code and changing a few things to make it display a diferent selection of songs

**Comment by EnzoMunizz0** [comment]
I think to help you, you have to show the MainMenuState.hx file

**Comment by DrebDaDev** [comment]
no yeah i already changed all i could there to make it work and it still doesnt work

**Comment by DrebDaDev** [comment]
oh wait i just understood what you mean here
[MainMenuState.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8734485/MainMenuState.zip)
