### ISSUE TITLE
how to add instead of set (lua)

### ISSUE THREAD

**Issue by obamacat9** [ShadowMario/FNF-PsychEngine#7975]
### Describe your problem here.

example
if this happens then add 50 to the value
instead of
if this happens then set the value to 100

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by cmallrt** [comment]
```
if 'this happens' then
     value = value + increment
```
idk

**Comment by acap09** [comment]
```bash
if var == 'what happened bro?' then
    setProperty('objectProperty', getProperty('objectProperty')+increment);
end
```

**Comment by kingyomoma** [comment]
maybe just.....
```lua
value = value + amount
```

**Comment by acap09** [comment]
> maybe just.....
> 
> ```lua
> value = value + amount
> ```

basically just @cmallrt's idea
