### ISSUE TITLE
Colors of Time Bar

### ISSUE THREAD

**Issue by Draconic-Hybrid** [ShadowMario/FNF-PsychEngine#7976]
### Describe your problem here.

I'm curious if there's a way to change the color of the Time Bar in Lua. If at all possible, I also want the time bar to have a gradient. On the left side, the opponent's HP bar color. On the right side, the player character's HP bar color. 

Even if the gradient isn't possible, changing the Time Bar's color would be enough for me.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by Murilo3127** [comment]
setProperty('timeBar.color', getColorFromHex('1CFF00'))
    setProperty('timeBarBG.color', getColorFromHex('00000'))

**Comment by Draconic-Hybrid** [comment]
Thanks! Is there a way to find the opponent's HP bar color with a variable?
