### ISSUE TITLE
How to make object from spritesheet

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#7977]
### What is your question?

if I want 1 individual frame of a spritesheet to made into an object, how would I do that?
say I wanted `HealthBar 120000` to be used.

**Comment by cherryiguess** [comment]
make an animated sprite with the animation being a frame of the animation name (example being BF NOTE LEFT0001), and play the animation so it plays, and make it loop i think

**Comment by Mastercopper2346** [comment]
#8522
