### ISSUE TITLE
Cant make credits in 0.5.2

### ISSUE THREAD

**Issue by KopitGithub** [ShadowMario/FNF-PsychEngine#7979]
### Describe your problem here.

Im having issues with 0.5.2, pre-built from gamebanana. I can't put credits in. I literally have no idea what I did.
![unknown-90](https://user-images.githubusercontent.com/80004391/161758263-05d720bf-eab4-4a61-933e-9a77c63ca823.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by acap09** [comment]
i think its because the 4th parameter is invalid (the link one), it should be a proper link, not some random texts

**Comment by megasssdev** [comment]
'this is the link, took it out for screenshot' what

**Comment by Theoyeah** [comment]
;

**Comment by oof-plays-yt** [comment]
name::icon::desc::link::colour (0xFFFFFFFF)
