### ISSUE TITLE
What variable is the song speed ?

### ISSUE THREAD

**Issue by ODHG1** [ShadowMario/FNF-PsychEngine#7980]
### What is your question?

Which LUA variable will let you change the audio and charting speed, like, i wanna make a notetype that accelerate the song when function goodNoteHit(id, noteData, noteType, isSustainNote) ( that  means when the note is pressed. )
i tried curBPM but it doesn't work, ( this is the final version that was wrote by a friend, i told him it's not 1 in BPM but we just decided to try.
![image](https://user-images.githubusercontent.com/72889491/161791171-b0bbb2ed-6aba-4483-8425-fef55888a2aa.png)

**Comment by ImDaeBob** [comment]
There is a way to do it with Lua Script, no need to dig in Source Code

**Comment by Lorekeeper49** [comment]
setProperty('speed', [int]);

**Comment by ZeitHeld** [comment]
BPM can be changed in the debug Menu/song Editor, and bbpanzu made/used an event to change a scroll speed for the [Holiday Part II](https://gamebanana.com/mods/344364) mod in Zanta. You chould take a look at it/take it.

**Comment by ODHG1** [comment]
Oh, thanks so uhh, do you think someone can help me do this ?

**Comment by ODHG1** [comment]
> BPM can be changed in the debug Menu/song Editor, and bbpanzu made/used an event to change a scroll speed for the [Holiday Part II](https://gamebanana.com/mods/344364) mod in Zanta. You chould take a look at it/take it.

i don't see anything related to scroll speed in part 2

**Comment by ODHG1** [comment]
well, the event is from the Engine Source code so it is no longer a LUA Script it is a Haxe Script but i need help with making the Lua Script, i can manage to turn the event into a Notetype
