### ISSUE TITLE
How do I hide the opponents notes?

### ISSUE THREAD

**Issue by DatGamerYoloYT** [ShadowMario/FNF-PsychEngine#7981]
### Describe your problem here.

There's no discussions tab anymore so I can't look through there finding out a script for this, so I have to use the issues tab. :(

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Doesn't matter if anything is edited, it's just a question that was put in here because there's no more discussions.

**Comment by cmallrt** [comment]
```lua
function onUpdate()
    for i = 0,3 do
        setPropertyFromGroup('strumLineNotes', i, 'alpha', 0)
    end
end
```

**Comment by kingyomoma** [comment]
onCreatePost() would be better to prevent it from crashing when dead

**Comment by ImDaeBob** [comment]
> onCreatePost() would be better to prevent it from crashing when dead

Or you can set an boundaries with curStep or curBeat

**Comment by DatGamerYoloYT** [comment]
> onCreatePost() would be better to prevent it from crashing when dead

that doesnt work

**Comment by DatGamerYoloYT** [comment]
heres a script i found with a bonus monochrome cover

function onCreatePost()
	for i = 0,3 do
		setPropertyFromGroup('strumLineNotes',i,'x',-330)
    end
end
