### ISSUE TITLE
macOS Assessable

### ISSUE THREAD

**Issue by Dancetrap** [ShadowMario/FNF-PsychEngine#7984]
### What is your question?

Hi there,
So I have a friend who doesn't own a Windows but a macOS, so they can't get into FNF. Is there anyway that in an update you can make it mac assessable? It would really mean a lot to my friend
Thanks so much

**Comment by Gibberditoslumber** [comment]
B R U H click on the green check find macBuild download it

**Comment by Gibberditoslumber** [comment]
if you do not know what i'm talking about then click on [this ](https://github.com/ShadowMario/FNFPsychEngine/suites/5902909942/artifacts/201003315)

**Comment by Dancetrap** [comment]
Thanks, I'll check it out.

**Comment by ShadowMario** [comment]
Mac has no official tested support due to haxe needing a Mac machine for compiling to Mac properly.

**Comment by Dancetrap** [comment]
Ok, I get it.
