### ISSUE TITLE
How do I undo the title screen easter egg??

### ISSUE THREAD

**Issue by PotatoKing0419** [ShadowMario/FNF-PsychEngine#7985]
### Describe your problem here.

read the title lol /\ /\ /\ /\

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Shadyyam** [comment]
type the same character code again

if it's on shadow for example, just type shadow again and it'll revert

**Comment by PotatoKing0419** [comment]
> type the same character code again
> 
> if it's on shadow for example, just type shadow again and it'll revert

Wow did not think it was that simple lol
