### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by RareBeeCodez** [ShadowMario/FNF-PsychEngine#7986]
### Describe your bug here.

The engine crashes when I try to add ghost animation

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not

**Comment by ImDaeBob** [comment]
Right now, there isn't a thing such as Ghost Moving Animation in Psych Engine, only hardcoded, Ghost Animation in the Character Editor is only used better visual for adjusting character position
