### ISSUE TITLE
there is no, no animation .json file

### ISSUE THREAD

**Issue by bacondanger** [ShadowMario/FNF-PsychEngine#7987]
### Describe your problem here.

I'm trying to find the no animation note so I can make custom note type copies and change their looks. But I don't know where or how to find this file without looking through the source code. If you have the .lua or know how to find the file, please let me know.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i didn't edit any of the main files

**Comment by frantastic24** [comment]
It's hardcoded, if you want to make a note play no animation use
```lua
setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true)
```

**Comment by bacondanger** [comment]
thank you

**Comment by kingyomoma** [comment]
```lua
function onCreate()
	for i = 0, getProperty('unspawnNotes.length')-1 do
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'name of lua file' then --Change this
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'pngOfYourNoteHere'); --Change texture

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
				setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true)
			end
		end
	end
	--debugPrint('Script started!')
end
```

something like this in a new .lua file

**Comment by bacondanger** [comment]
the script works but it still plays the animation, is there something I need to add?
![script thing](https://user-images.githubusercontent.com/102884958/162083164-61ba1075-4600-46cc-b61a-d16049655a33.PNG)

**Comment by bacondanger** [comment]
also, how did you learn Lua? I want to learn basic Lua sometime in the future.

**Comment by frantastic24** [comment]
Change `onCreate` to `onCreatePost`

**Comment by bacondanger** [comment]
nothing changed. is there a problem on my end? i changed the first 3 notes to the script notes, then I changed the next 3 notes to the hardcoded no animation.

https://user-images.githubusercontent.com/102884958/162112283-5ffb46a7-3f2d-4cd5-9605-f2a7de14a06f.mp4

**Comment by frantastic24** [comment]
it works on my end so idk what to tell you

**Comment by frantastic24** [comment]
you forgot an argument in the texture change line

**Comment by bacondanger** [comment]
I finally fixed it.`function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is an Instakill Note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Instakill Note' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'HURTNOTE_assets'); --Change texture
			setPropertyFromGroup('unspawnNotes', i, 'hitHealth', '0.023'); --Default value is: 0.023, health gained on hit
			setPropertyFromGroup('unspawnNotes', i, 'missHealth', '0.0475'); --Default value is: 0.0475, health lost on miss
			setPropertyFromGroup('unspawnNotes', i, 'hitCausesMiss', false);

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
                setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true)
			end
		end
	end
	--debugPrint('Script started!')
end
`

**Comment by bacondanger** [comment]
finally fixed it
`function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is an Instakill Note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Instakill Note' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'HURTNOTE_assets'); --Change texture
			setPropertyFromGroup('unspawnNotes', i, 'hitHealth', '0.023'); --Default value is: 0.023, health gained on hit
			setPropertyFromGroup('unspawnNotes', i, 'missHealth', '0.0475'); --Default value is: 0.0475, health lost on miss
			setPropertyFromGroup('unspawnNotes', i, 'hitCausesMiss', false);

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
                setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true)
			end
		end
	end
	--debugPrint('Script started!')
end
`

**Comment by bacondanger** [comment]
`function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is an Instakill Note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Instakill Note' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'HURTNOTE_assets'); --Change texture
			setPropertyFromGroup('unspawnNotes', i, 'hitHealth', '0.023'); --Default value is: 0.023, health gained on hit
			setPropertyFromGroup('unspawnNotes', i, 'missHealth', '0.0475'); --Default value is: 0.0475, health lost on miss
			setPropertyFromGroup('unspawnNotes', i, 'hitCausesMiss', false);

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
                setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true)
			end
		end
	end
	--debugPrint('Script started!')
end
`

**Comment by bacondanger** [comment]
finally got the code finished
	`function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is an Instakill Note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Instakill Note' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'HURTNOTE_assets'); --Change texture
		vvsetPropertyFromGroup('unspawnNotes', i, 'hitHealth', '0.023'); --Default value is: 0.023, health gained on hit
			setPropertyFromGroup('unspawnNotes', i, 'missHealth', '0.0475'); --Default value is: 0.0475, health lost on miss
			setPropertyFromGroup('unspawnNotes', i, 'hitCausesMiss', false);

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
                setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true)
			end
		end
	end
	--debugPrint('Script started!')
end
`

**Comment by bacondanger** [comment]
`function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is an Instakill Note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Instakill Note' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'HURTNOTE_assets'); --Change texture
			setPropertyFromGroup('unspawnNotes', i, 'hitHealth', '0.023'); --Default value is: 0.023, health gained on hit
			setPropertyFromGroup('unspawnNotes', i, 'missHealth', '0.0475'); --Default value is: 0.0475, health lost on miss
			setPropertyFromGroup('unspawnNotes', i, 'hitCausesMiss', false);

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
                setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true)
			end
		end
	end
	--debugPrint('Script started!')
end`

finished it and it works thank you every one!

**Comment by bacondanger** [comment]
function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is an Instakill Note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Instakill Note' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'HURTNOTE_assets'); --Change texture
			setPropertyFromGroup('unspawnNotes', i, 'hitHealth', '0.023'); --Default value is: 0.023, health gained on hit
			setPropertyFromGroup('unspawnNotes', i, 'missHealth', '0.0475'); --Default value is: 0.0475, health lost on miss
			setPropertyFromGroup('unspawnNotes', i, 'hitCausesMiss', false);

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
                setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true)
			end
		end
	end
	--debugPrint('Script started!')
end
``

**Comment by bacondanger** [comment]
shoot

https://drive.google.com/file/d/1rIxpD2MWSUIdQZyFnn_CJ1lzuyg0IGKp/view?usp=sharing 
here's the code thank you, everyone!
