### ISSUE TITLE
How to add function when your on low health, you get tired like fnf hd?

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#7989]
### Describe your problem here.

How to add function when your on low health, you get tired like fnf hd?
plzzzzzzzzzzzzzzzzzzzzzzz
i need a script

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, of course

**Comment by ImDaeBob** [comment]
A script i cannot give you thw script but you can code on. Just use 
function onUpdate()
health=getProperty('health')
if health < *an interger number* then
LINES OF CODES THAT DO SOMETHING
end
end

Note: maximum HEALTH is 1.99, lowest is 0

**Comment by acap09** [comment]
i kinda forgot what number should bf be in change character event, so if you know, change it to the number
```bash
function onUpdatePost(elapsed)
    health = getProperty('health')
    if health < 0.4 then
        triggerEvent('Change Character', 1, 'bf-tired');
    end
```

**Comment by acap09** [comment]
> A script i cannot give you thw script but you can code on. Just use function onUpdate() health=getProperty('health') if health < _an interger number_ then LINES OF CODES THAT DO SOMETHING end end
> 
> Note: maximum HEALTH is 1.99, lowest is 0

i think maximum health is 2
not 1.99

**Comment by Mastercopper2346** [comment]
thx

**Comment by Mastercopper2346** [comment]
Also its 0 for change character not 1

**Comment by Mastercopper2346** [comment]
0 == bf
1 == dad
2 == gf

**Comment by Mastercopper2346** [comment]
Full script
function onUpdatePost(elapsed)
    health = getProperty('health')
    if health < 1 then -- If you are editing this like a NOOB, make sure both health values are the same
        triggerEvent('Change Character', 0, 'bf-tired');
    end
end

function onUpdate(elapsed)
    health = getProperty('health')
    if health > 1 then
        triggerEvent('Change Character', 0, 'bf');
    end
end

**Comment by Mastercopper2346** [comment]
- [ ] function onUpdatePost(elapsed)
    health = getProperty('health')
    if health < 1 then -- If you are editing this like a NOOB, make sure both health values are the same
        triggerEvent('Change Character', 0, 'bf-tired');
    end
end

function onUpdate(elapsed)
    health = getProperty('health')
    if health > 1 then
        triggerEvent('Change Character', 0, 'bf');
    end
end

**Comment by Mastercopper2346** [comment]
`function onUpdatePost(elapsed)
    health = getProperty('health')
    if health < 1 then -- If you are editing this like a NOOB, make sure both health values are the same
        triggerEvent('Change Character', 0, 'bf-tired');
    end
end

function onUpdate(elapsed)
    health = getProperty('health')
    if health > 1 then
        triggerEvent('Change Character', 0, 'bf');
    end
end`

**Comment by Mastercopper2346** [comment]
function onUpdatePost(elapsed)
    health = getProperty('health')
    if health < 1 then -- If you are editing this like a NOOB, make sure both health values are the same
        triggerEvent('Change Character', 0, 'bf-tired');
    end
end

function onUpdate(elapsed)
    health = getProperty('health')
    if health > 1 then
        triggerEvent('Change Character', 0, 'bf');
    end
end

**Comment by Mastercopper2346** [comment]
function onUpdatePost(elapsed)
            health = getProperty('health')
            if health < 0.75 then -- If you are editing this like a NOOB, make sure both health values are the same
                    triggerEvent('Change Character', 0, 'bf-tired');
           end
end

function onUpdate(elapsed)
           health = getProperty('health')
           if health > 0.75 then
                     triggerEvent('Change Character', 0, 'bf');
           end
end

**Comment by Mastercopper2346** [comment]
```
function onUpdatePost(elapsed)
          health = getProperty('health')
          if health < 0.75 then -- If you are editing this like a NOOB, make sure both health values are the same
                      triggerEvent('Change Character', 0, 'bf-tired');
          end
end

function onUpdate(elapsed)
           health = getProperty('health')
          if health > 0.75 then
                   triggerEvent('Change Character', 0, 'bf');
          end
end
```
