### ISSUE TITLE
Changing modcharts via LUA

### ISSUE THREAD

**Issue by GMan2006i** [ShadowMario/FNF-PsychEngine#7991]
### Describe your problem here.

Okay so this is sorta a complex question but basically 
i want to have the chart change between the 3 different difficulty jsons using lua
the point of this is for a mechanic that requires this to be possible
if i cant do it in lua imma open another Issue cause im learning how to build the game as of recent

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, Some Minor Playstate and discord stuff, mostly the playstate, it being adding a FlxTrail event

**Comment by GMan2006i** [comment]
no no no
i want to load a different chart via lua

**Comment by Lorekeeper49** [comment]
You can just make the chart (and maybe song name if you want a different song) completely different for each json within the song data folder, just make sure the name is [data folder name]-[difficulty]

**Comment by GMan2006i** [comment]
nonononononono
can you change the current game difficulty using lua without leaving the song

**Comment by frantastic24** [comment]
No and why would you ever want to do that

**Comment by keanu64github** [comment]
function (whatever function you want example: onCreatePost())
-- if you have custom difficulties in lua, index starts with 0, example: if your difficulties are "sus, hard" sus would be difficulty 0, if you are using Easy, Normal, Hard, 0 is Easy, 1 is Normal, 2 is hard.
loadSong(songName, 0)
end
