### ISSUE TITLE
arrow keeps being pressed after un-pausing game

### ISSUE THREAD

**Issue by Iliketttturtles** [ShadowMario/FNF-PsychEngine#7993]
### Describe your bug here.

I know that this is a very small bug but it's a bug nonetheless. Sometimes when I hit a hold note and pause the game, it thinks I'm still holding that key down when I un-pause the game. I can fix it by pressing the key again but it's still annoying either way, especially when I'm playing a very hard song.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by DatGamerYoloYT** [comment]
gonna test this out on other engines to see if this is an issue for JUST pysch engine
