### ISSUE TITLE
You know in disruption how the arrows warp?

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#7994]
### What is your question?

i was wondering how to do that

**Comment by machonessiebaby** [comment]
lua if possible

**Comment by machonessiebaby** [comment]
if not i can do source

**Comment by machonessiebaby** [comment]
like this btw if needed
![image](https://user-images.githubusercontent.com/56323671/162082805-5a9e063d-5405-4cdb-b2e0-62e4f1b85290.png)

**Comment by ZeitHeld** [comment]
It may be possible with lua. Has something to do with tweening.
But I do not know either, how to make things move in a circle properly. Cause it would also help me out a lot
Also, I recommend to look in the source code for it, and translate it into lua if possible

**Comment by machonessiebaby** [comment]
> It may be possible with lua. Has something to do with tweening. But I do not know either, how to make things move in a circle properly. Cause it would also help me out a lot Also, I recommend to look in the source code for it, and translate it into lua if possible

k

**Comment by poobie1** [comment]
krunkthing = 60
playerArrowsX = {732, 844, 956, 1068}
opponentArrowsX = {92, 204, 316, 428}
names = {'opponentStrums', 'playerStrums'}

--[[
                      __________________________________
                    /                                   \
                    \                                   /
                      __________________________________
                      |                                |
                      |                                |
                      |--------------------------------|
                      |     o                   o      |
   O------------------|                                |------------------O
                      |----\----------------/----------|
                      |     ----------------           |
                      |                                |
                      ---------------------------------
                            |                 |
                            |                 |
                            |                 |
                    --------                  --------
MADE BY MAYO78!!!!!
]]
--if you steal this i will know

function onCreatePost()
  strumY = getPropertyFromClass('clientPrefs', 'downscroll') == true and 560 or 40
end
function onUpdate()
  songPos = getSongPosition()
  currentBeat = (songPos/5000)*(curBpm/60)
  if not inGameOver then
    for i=1,2,1 do
      local daName = names[i]
      local daStrums = i == 2 and playerArrowsX or opponentArrowsX
      for i=0,3,1 do
        local huh = math.fmod(i, 2) == 0 and 1 or -1
        setPropertyFromGroup(daName, i, 'x', daStrums[i+1] + math.sin(currentBeat) * huh * krunkthing)
        setPropertyFromGroup(daName, i, 'y', strumY + math.sin(currentBeat - 5) * huh * krunkthing)

        setPropertyFromGroup(daName, i, 'scale.x', math.abs(math.sin(currentBeat - 5) * huh) / 4)
        setPropertyFromGroup(daName, i, 'scale.y', math.abs(math.sin(currentBeat) * huh) / 2)

        setPropertyFromGroup(daName, i, 'scale.x', getPropertyFromGroup(daName, i, 'scale.x') + 0.2)
        setPropertyFromGroup(daName, i, 'scale.y', getPropertyFromGroup(daName, i, 'scale.y') + 0.2)

        setPropertyFromGroup(daName, i, 'scale.x', getPropertyFromGroup(daName, i, 'scale.x') * 1.5)
        setPropertyFromGroup(daName, i, 'scale.y', getPropertyFromGroup(daName, i, 'scale.y') * 1.5)
      end
    end
    for i = 0, getProperty('notes.length')-1 do
      local daName = getPropertyFromGroup('notes', i, 'mustPress') == true and names[1] or names[2]
    	setPropertyFromGroup('notes', i, 'scale.x', getPropertyFromGroup(daName, getPropertyFromGroup('notes', i, 'noteData'), 'scale.x'));
      setPropertyFromGroup('notes', i, 'scale.y', getPropertyFromGroup(daName, getPropertyFromGroup('notes', i, 'noteData'), 'scale.y'));
  	end
  end
end

**Comment by poobie1** [comment]
krunkthing = 60
playerArrowsX = {732, 844, 956, 1068}
opponentArrowsX = {92, 204, 316, 428}
names = {'opponentStrums', 'playerStrums'}

--[[
                      __________________________________
                    /                                   \
                    \                                   /
                      __________________________________
                      |                                |
                      |                                |
                      |--------------------------------|
                      |     o                   o      |
   O------------------|                                |------------------O
                      |----\----------------/----------|
                      |     ----------------           |
                      |                                |
                      ---------------------------------
                            |                 |
                            |                 |
                            |                 |
                    --------                  --------
MADE BY MAYO78!!!!!
]]
--if you steal this i will know

function onCreatePost()
  strumY = getPropertyFromClass('clientPrefs', 'downscroll') == true and 560 or 40
end
function onUpdate()
  songPos = getSongPosition()
  currentBeat = (songPos/5000)*(curBpm/60)
  if not inGameOver then
    for i=1,2,1 do
      local daName = names[i]
      local daStrums = i == 2 and playerArrowsX or opponentArrowsX
      for i=0,3,1 do
        local huh = math.fmod(i, 2) == 0 and 1 or -1
        setPropertyFromGroup(daName, i, 'x', daStrums[i+1] + math.sin(currentBeat) * huh * krunkthing)
        setPropertyFromGroup(daName, i, 'y', strumY + math.sin(currentBeat - 5) * huh * krunkthing)

        setPropertyFromGroup(daName, i, 'scale.x', math.abs(math.sin(currentBeat - 5) * huh) / 4)
        setPropertyFromGroup(daName, i, 'scale.y', math.abs(math.sin(currentBeat) * huh) / 2)

        setPropertyFromGroup(daName, i, 'scale.x', getPropertyFromGroup(daName, i, 'scale.x') + 0.2)
        setPropertyFromGroup(daName, i, 'scale.y', getPropertyFromGroup(daName, i, 'scale.y') + 0.2)

        setPropertyFromGroup(daName, i, 'scale.x', getPropertyFromGroup(daName, i, 'scale.x') * 1.5)
        setPropertyFromGroup(daName, i, 'scale.y', getPropertyFromGroup(daName, i, 'scale.y') * 1.5)
      end
    end
    for i = 0, getProperty('notes.length')-1 do
      local daName = getPropertyFromGroup('notes', i, 'mustPress') == true and names[1] or names[2]
    	setPropertyFromGroup('notes', i, 'scale.x', getPropertyFromGroup(daName, getPropertyFromGroup('notes', i, 'noteData'), 'scale.x'));
      setPropertyFromGroup('notes', i, 'scale.y', getPropertyFromGroup(daName, getPropertyFromGroup('notes', i, 'noteData'), 'scale.y'));
  	end
  end
end
