### ISSUE TITLE
2 Questions

### ISSUE THREAD

**Issue by CasualCypress** [ShadowMario/FNF-PsychEngine#7995]
### What is your question?

1st Question: How do i use the easter eggs in the source build?

2nd Question: what happened to discussions in github, does that mean you got banned or something?

**Comment by Meme1079** [comment]
1st i dont know? 
2nd he deleted because people were spamming it to death

**Comment by ZeitHeld** [comment]
The easter eggs can be accessed as followed:
You have to type in the title screen certrain key words. Those are: bbpanzu, shubs, shadow, river
Extra secret I noticed, when the shadow mario easter egg is activated, there will be no title screen music at all

**Comment by CasualCypress** [comment]
> The easter eggs can be accessed as followed: You have to type in the title screen certrain key words. Those are: bbpanzu, shubs, shadow, river Extra secret I noticed, when the shadow mario easter egg is activated, there will be no title screen music at all

i know how to do it, its just in the source version it wont do it

**Comment by frantastic24** [comment]
Read Project.xml
