### ISSUE TITLE
Added Event Copy [COPY THE EVENT ONLY, Not section]

### ISSUE THREAD

**Issue by MGDFURRY** [ShadowMario/FNF-PsychEngine#7997]
### What feature do you want to get added on the **base** engine?

Why not added like "copy event section" so when I wanna loop an event just copy and paste the last section [ONLY EVENT]

![image](https://user-images.githubusercontent.com/40258538/162152936-7f8cf92c-78fd-4830-b2a3-c92b1944dbc9.png)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by MaybeMaru** [comment]
yeah that could be kinda nice ig

**Comment by bbpanzu** [comment]
it would be useful to have some check shits
![image](https://user-images.githubusercontent.com/45317642/163229289-fb7b904e-3cf3-4d5e-bd65-976e2f5c97d9.png)
