### ISSUE TITLE
Volume buttons for instrumentals and vocals? (chart editor)

### ISSUE THREAD

**Issue by Rottyy** [ShadowMario/FNF-PsychEngine#8]
hey, i've been loving PE's chart editor, and the engine in itself, until i came to a realization that you can't really tone down the volume of a song's vocals/instrumentals in the editor, to make hit sounds more audible. was that intentional, or is it gonna be a planned addition in the future?

aside from that, fantastic work!

**Comment by ShadowMario** [comment]
Good idea, i will be adding that once i finish the Lua modchart loader

**Comment by ShadowMario** [comment]
Added on the latest update, thank you for the suggestion.
