### ISSUE TITLE
Dialogue not working source/PlayState.hx:987: characters 6-19 : Unknown identifier : dialogueIntro

### ISSUE THREAD

**Issue by ItsTGsis** [ShadowMario/FNF-PsychEngine#80]
Hi, we've tried to add dialogue, we followed all instructions perfectly, but we keep getting this error (see title) when compiling.
What are we doing wrong? Please help!

**Comment by ShadowMario** [comment]
I forgot to update that i've changed dialogueIntro to startDialogue

**Comment by ShadowMario** [comment]
Oh yeah, i re-opened this because i just noticed the entire Dialogue page is outdated

**Comment by FuseIsHere813** [comment]
Oh yeah, the old page was for 0.3 or later.

**Comment by ShadowMario** [comment]
Updated the page.
