### ISSUE TITLE
Opponent arrows invisible

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#8000]
### Describe your problem here.

How do I make the opponent arrows not visible? what script do i need for that?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Ive added sprites, removed the weeks to create my own, and added a bunch of lua files such as scripts and custom notes, that's pretty much all I did

**Comment by ZeitHeld** [comment]
```
onUpdate(elapsed)
    for i = 0,3 do
        setPropertyFromGroup('strumLineNotes', i, 'alpha', 0)
    end
end
```

credit for the bit of code goes to the Phantasm mod.

Btw this is put in the stage.lua file
But you can put it somewhere different too I think

**Comment by SonicXFire1987** [comment]
> ```
> onUpdate(elapsed)
>     for i = 0,3 do
>         setPropertyFromGroup('strumLineNotes', i, 'alpha', 0)
>     end
> end
> ```
> 
> credit for the bit of code goes to the Phantasm mod.
> 
> Btw this is put in the stage.lua file But you can put it somewhere different too I think

oh ok thanks

**Comment by SonicXFire1987** [comment]
> Don't use onUpdate Just use onCreatePost and move them out of bounds **once**

ill be sure to keep that in mind

**Comment by Mastercopper2346** [comment]
Yessir

**Comment by Mastercopper2346** [comment]
know what

**Comment by Mastercopper2346** [comment]
IMA USE THIS AS AN EVENT
