### ISSUE TITLE
my own celebi animation

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#8001]
### Describe your problem here.

how do i add my own celebi animation like in monochrome.. i made a cover for it and i have it in my mod but i don't know how to do the celebi animation. do i put it in the background lua and use the play animation event? or do i use an event for it?. im just wondering how to do it without the source code.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Ive added sprites, removed the weeks to create my own, and added a bunch of lua files such as scripts and custom notes, that's pretty much all I did

**Comment by ZeitHeld** [comment]
[here](https://gamebanana.com/mods/365509) is a softcoded/lua version of monochrome
