### ISSUE TITLE
A few ideas: thorns dia sprite, diaNormal to diaPixel, lua options

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#8002]
### What feature do you want to get added on the **base** engine?

1. Could the shadow senpai portrait maybe be removed on/during thorns? It irritates me, and (to me) it looks like a kind of bug

2. Maybe an option, since dialogues are a thing already, there could be the option to (kind of) let pixel dialogues, like in week 6, be "softcoded" by creating a .txt and naming it dialogue or smth, then recognizing the format, and putting it in.
But, this could also be done via the current format, just with the difference, if the stage is a pixel stage or something. So it will just change the frame/textbox and font. Or however they did it.

3. Softcoded options? So like, you can put it in some toggle able features, that you would otherwise have to do via source code. But they could be recognized/used "global" (for only the mod of course, and as long as it is activated) with a function like idk I give an example:
```
makeOption(tag:String, type:String, name:string, defaultValue:Dynamic, section:String)
makeOption("NoDadArrows", "Switch", "Hide Opponent Arrows", false, "Gameplay")
```
Types could be **"Switch"** _(true false)_ **"Dynamic" (idk how to call that)** _(changable, numericvalues)_
And sections are: **"Gameplay"**, **"Visuals"**, **"Graphics"** maybe **"Controls"** even. But it would also be an option, to make an own category for **"mods"**. And then sorted (alphabetically?) by the mods maybe, to keep them apart.

But I think it would be better as a json file. Or at least because of the description, you could put in there.

I hope I was being understandable with my words of choice, and how I expressed myself. If not, I could give a few (poorly) visual examples

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Theoyeah** [comment]
that pretty good

**Comment by Meme1079** [comment]
3 is soo good

**Comment by kingyomoma** [comment]
first time ive ever seen an actual good suggestion

**Comment by Shadyyam** [comment]
softcoded options would be amazing
