### ISSUE TITLE
Sorry for again

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#8005]
### What is your question?

I lost the arrow color change script i need this for a week in a mod also (is there a way for it to only be opponent

**Comment by bacondanger** [comment]
if you want to change the opponent's note to be different than bf's, look at this GitHub answer and download the links. This causes a little lag at the start of the song but works amazing.
https://github.com/ShadowMario/FNF-PsychEngine/issues/3623
