### ISSUE TITLE
Random crashes in song

### ISSUE THREAD

**Issue by lolbruhfart** [ShadowMario/FNF-PsychEngine#8006]
### Describe your bug here.

in 5.1 im playing a song in both modded and not modded psych engine and my game just randomly crashes ONLY when im playing in a song

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
0.5.1 isn't supported as this issue could have been resolved in 0.5.2h
