### ISSUE TITLE
Stupid Charting Question

### ISSUE THREAD

**Issue by JavoniCraft** [ShadowMario/FNF-PsychEngine#8007]
### What is your question?

What does the offset option in charting mode do? Does it effect the milliseconds the music starts?

**Comment by im557** [comment]
ye

**Comment by Lorekeeper49** [comment]
It's just an offset for the metronome, if you want actual offset for a song, make a file called '_meta.json' and put in what I have below (note: I typed four spaces instead of pressing tab since I typed this on phone and phone doesn't really have a way for tab to work):

{
    "offset": int
}

**Comment by JavoniCraft** [comment]
> It's just an offset for the metronome, if you want actual offset for a song, make a file called '_meta.json' and put in what I have below:
> 
> { "offset": int }

thank you!

**Comment by ShadowMario** [comment]
> It's just an offset for the metronome, if you want actual offset for a song, make a file called '_meta.json' and put in what I have below:
> 
> { "offset": int }

...This is for Kade Engine, there's nothing like this on Psych.
