### ISSUE TITLE
error 0xe24c4a05

### ISSUE THREAD

**Issue by GMan2006i** [ShadowMario/FNF-PsychEngine#8008]
### Describe your bug here.

game crashed with this error
![image](https://user-images.githubusercontent.com/64226529/162331085-73ba84f5-4709-492c-a69a-5a34f9d663ac.png)

### Command Prompt/Terminal logs (if existing)

```bash
none
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, Some Minor Playstate and discord stuff, mostly the playstate, it being adding a FlxTrail event

**Comment by GMan2006i** [comment]
this is my own custom build, but even when playing on a normal build the crashes usually occur, but without the error message; this is the first time ive gotten this message

**Comment by erykplgh** [comment]
skill issue

**Comment by GMan2006i** [comment]
> skill issue

F
