### ISSUE TITLE
Can I make a new function?

### ISSUE THREAD

**Issue by MR-FNF** [ShadowMario/FNF-PsychEngine#8009]
### What is your question?

Can I make a new function? If yes then...
1. How do I program it?

**Comment by Lorekeeper49** [comment]
If you want to make a new lua function, find FunkinLua.hx and code the new function based on what functions are already there

**Comment by MR-FNF** [comment]
> If you want to make a new lua function, find FunkinLua.hx and code the new function based on what functions are already there

Lua please... Also my friend will need this, thanks!

**Comment by zeadd21g1233** [comment]
make this  code

function anything()

your code

end

if you want to use code

in curstep 
or curBeat
or modchart 


add this

anything()

**Comment by bacondanger** [comment]
just as an explanation 'function (name of the function here, this will be the name for the function throughout the script).'
'your code (your code is anything else in the script)'
'end (ends the function)'

curstep, curbeat, and modchart. [read da wiki](https://raw.githubusercontent.com/ShadowMario/FNF-PsychEngine/main/docs/TemplateScript.lua)
