### ISSUE TITLE
How to make the notes split?

### ISSUE THREAD

**Issue by FateBreakfast** [ShadowMario/FNF-PsychEngine#8012]
### What is your question?

Basically just wondering how I can make a modchart that splits the notes, like down and left on the left and up and right on the right.

**Comment by ManMaster707** [comment]
`noteTweenX('LeftnotetweenX, 4, *coordinate here*, 0.5, 'linear');`
`noteTweenX('downtnotetweenX, 5, *coordinate here*, 0.5, 'linear');`
`noteTweenX('upnotetweenX, 6, *coordinate here*, 0.5, 'linear');`
`noteTweenX('RightnotetweenX, 7, *coordinate here*, 0.5, 'linear');`

(you can edit some values, like the coordinate, duration and tweening method, of course)

**Comment by FateBreakfast** [comment]
thank you :)

**Comment by FateBreakfast** [comment]
Ok wait now im getting an issue saying that there's a ) expected near 'linear'

**Comment by FateBreakfast** [comment]
oh nvm i fixed, 
![image](https://user-images.githubusercontent.com/92828154/162529347-21604d79-a95c-46d8-8ebd-32350c0dd19c.png)
this is my code, just gotta tweak the coordinates to make them go to the right positions
