### ISSUE TITLE
can any one fix monochrome mechanic code ? (source code)

### ISSUE THREAD

**Issue by zeadd21g1233** [ShadowMario/FNF-PsychEngine#8013]
### Describe your problem here.

ihave error

in the code

is called

source/FunkinLua.hx:1968: characters 29-35 : Cannot access private field isDead
source/FunkinLua.hx:1000: characters 29-35 : Cannot access private field isDead

idont know what i do

help pls

im in finale step

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i add unownstate and code playstate

**Comment by ShadowMario** [comment]
You didn't show anything of your code... I can't help you like that.

**Comment by zeadd21g1233** [comment]
FIXED

new problom no types or anything just idie 

iadd Unown_Alphabat and in new path

line i can see it

**Comment by zeadd21g1233** [comment]
FIXED
