### ISSUE TITLE
opponent plays note instead of bf

### ISSUE THREAD

**Issue by bacondanger** [ShadowMario/FNF-PsychEngine#8014]
### Describe your problem here.

`-- Script made by Catbrother Everything with help by NardBruh. Credit is not needed but would be nice! :)

function onCreate()
	makeAnimatedLuaSprite('dad2', 'characters/Mom_Assets', 500, 50); -- Change to characters idle in XML
	addAnimationByPrefix('dad2', 'idle', 'Mom Idle', 24, false); -- Change to characters idle in XML
    addAnimationByPrefix('dad2', '0', 'Mom Left Pose', 24, false); -- Change to characters leftnote in XML
    addAnimationByPrefix('dad2', '1', 'MOM DOWN POSE', 24, false); -- Change to characters downnote in XML
    addAnimationByPrefix('dad2', '2', 'Mom Up Pose', 24, false); -- Change to characters upnote in XML
    addAnimationByPrefix('dad2', '3', 'Mom Pose Left', 24, false); -- Change to characters rightnote in XML
	objectPlayAnimation('dad2', 'idle'); 
	addLuaSprite('dad2', true); -- false = add behind characters, true = add over characters
end
function onBeatHit()
	-- triggered 4 times per section
	if curBeat % 2 == 0 then
		objectPlayAnimation('dad2', 'idle');
	end
end

lastNote = {0, ""}

function OpponenttNoteHit(id,d,t,s)

    lastNote[1] = d
    lastNote[2] = t
    
    if lastNote[2] == "Cain note" then -- Change "No Animation" to be your note type, usually you can just keep it as no anim assuming you arent using it elsewhere
	objectPlayAnimation('dad2', lastNote[1]);
    end
end`

i need help to change this code to make it so bf plays insted of the opponent (look at function OpponentNoteHit). how do I change that to make it play a move when bf has a note hit?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i didn't edit any of the main files

**Comment by bacondanger** [comment]
why isn't the add code thing not working (on GitHub)?

**Comment by frantastic24** [comment]
[Read the wiki](https://raw.githubusercontent.com/ShadowMario/FNF-PsychEngine/main/docs/TemplateScript.lua)

**Comment by bacondanger** [comment]
ok, so I change it to goodNoteHit instead. let me test.

**Comment by bacondanger** [comment]
thank you it worked!
