### ISSUE TITLE
change the reset key

### ISSUE THREAD

**Issue by versebrik** [ShadowMario/FNF-PsychEngine#8015]
### What feature do you want to get added on the **base** engine?

In Freeplay, it says that I can reset the score and accuracy by pressing the Reset key, but I can't find the Reset key :d How about changing it to Delete key?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by KutikiPlayz** [comment]
it's literally in the controls menu

**Comment by KutikiPlayz** [comment]
also you failed the test
