### ISSUE TITLE
Blocking Arrows

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#8016]
### Describe your problem here.

How do you block the arrows like in Expurgation from the Tricky Mod or Salvage from Funkin at Freddy's? Can I have both versions. and if you can only do it in the source code can you tell me how. but i really prefer a lua file. and can you give me the txt file too for value 1 and value 2 just so i know how to use it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Ive added sprites, removed the weeks to create my own, and added a bunch of lua files such as scripts and custom notes, that's pretty much all I did

**Comment by ManMaster707** [comment]
first, you need to add an object, and then write this:

`setObjectCamera('objectname', 'other');`

it will make the object go over the arrows, but if you meant something else, tell me

**Comment by SonicXFire1987** [comment]
what do i put for 'other'? I'm still learning how to code.

**Comment by ManMaster707** [comment]
you leave it like that, it's a value that makes the object go over the hud.

**Comment by SonicXFire1987** [comment]
ok thanks

**Comment by SonicXFire1987** [comment]
is this an event?

**Comment by ManMaster707** [comment]
no, you can make it an event, but it's better if you put it in a stage script.

**Comment by SonicXFire1987** [comment]
oh ok. i was wondering because i just need it to cover the arrows at certain points

**Comment by SonicXFire1987** [comment]
also how do i attach a sprite with it?

**Comment by ManMaster707** [comment]
`makeLuaSprite('sprite', 'imagepath', x coordinate, y coordinate);-- you have to modify x and y coordinate to your liking`
`addLuaSprite('sprite', true);--false = behind characters, true = over characters`

you put this in your stage script, you can put the setObjectcamera or in an event or in the stage script

**Comment by SonicXFire1987** [comment]
ok ill test this when i'm home from school.. So i can but this in an event?

**Comment by ManMaster707** [comment]
idk, you're making the mod, it can be but it also can't, you choose

**Comment by SonicXFire1987** [comment]
alright then
