### ISSUE TITLE
jumpscare game over screen + game closes after jumpscare

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#8017]
### Describe your problem here.

is there a way to do a jumpscare for a game over screen. and how do you have the game close afterwards. please send me he code for the lua for both. i was told it is possible with lua for both but that was in discussion before it was removed. soooo yeah..

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Ive added sprites, removed the weeks to create my own, and added a bunch of lua files such as scripts and custom notes, that's pretty much all I did

**Comment by ManMaster707** [comment]
For the jumpscare, you can make the jumpscare a character and then putting this in your script:

`setPropertyFromClass('GameOverSubstate','characterName', 'namehere');`

for the game closing, I'm not sure.

**Comment by SonicXFire1987** [comment]
i guessing 'namehere' i put jumpscare

**Comment by ManMaster707** [comment]
yes.

**Comment by SonicXFire1987** [comment]
thanks im at school right now. i'll test it when i get home

**Comment by SonicXFire1987** [comment]
`setPropertyFromClass('GameOverSubstate','bf', 'jumpscare');`

im guessing this is how its done right?

**Comment by SonicXFire1987** [comment]
setPropertyFromClass('GameOverSubstate','characterName', 'jumpscare');

so like this then

**Comment by SonicXFire1987** [comment]
ok

**Comment by SonicXFire1987** [comment]
how do I attach the sprites?

**Comment by Goontron** [comment]
you could do, 
if setPropertyFromClass('GameOverSubstate','characterName', 'jumpscare');
     then makeLuaSprite('scare thing', 'ogga booga', -600, -200);
-- ogga booga being the `file name` and `scare thing` being the variable, 
end


--for animated ones im not sure about...

**Comment by MaybeMaru** [comment]
if you want to close the game you could use the os function, only in 5.1 tho, it was removed in newer versions because of some problems it caused
