### ISSUE TITLE
Song break

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#8018]
### Describe your problem here.

Is there a way for you to make a song have only a certain amount of attempts and when those attempts are over you have to play a different song and come back after playing another song. this is probably not possible without source code but let me know if it is possible with lua. my friend wants to make a mod and he wanted that so i asked for him since he didn't have the resources for it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Ive added sprites, removed the weeks to create my own, and added a bunch of lua files such as scripts and custom notes, that's pretty much all I did

**Comment by ShadowMario** [comment]
This would probably break with the Story mode songs order, but you can check `getProperty('deathCounter')` and use `loadSong('Satin Panties')` to load a different song, although i didn't test it myself.
If this doesn't work you will probably have to use source.
