### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#8019]
### What is your question?

Has anyone figured out how to do lua Achievements? I'm just wondering.

**Comment by ManMaster707** [comment]
not to be rude, but it has been told several times that you CAN'T do lua achievements (they were too broken), and the folder for it was accidentally left there.

**Comment by SonicXFire1987** [comment]
oh ok I was just wondering. Because he folder was just sitting there lmao. and you aren't being rude. you're just letting me know that its too broken. thanks anyway though.
