### ISSUE TITLE
How can I keep the zoom of UI

### ISSUE THREAD

**Issue by Youareblind** [ShadowMario/FNF-PsychEngine#8020]
### Describe your problem here.

For example, I can use
setProperty('defaultCamZoom',zoomamount)
to keep camgame zoom
But how can I keep the zoom of UI?
setProperty('camHUD.zoom',x)	
can not keep the zoom of UI.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Stilic** [comment]
`setProperty('camZooming',false)`

**Comment by Youareblind** [comment]
> `setProperty('camZooming',false)`

thanks a lot
