### ISSUE TITLE
botPlay lua variable does nothing

### ISSUE THREAD

**Issue by TheRedperson** [ShadowMario/FNF-PsychEngine#8022]
### Describe your bug here.

Pretty much when using the "botPlay" or cpuControlled variable, it does absolutely nothing when trying to use it. The engine is not telling me any errors on the script but when I use it, the game does nothing. The script I am trying to use is down below>>
local cpuControlled = false

function onCreate()
	makeLuaText('botText', 'Press P for BOTPLAY', 512, 10, 650)
	setTextAlignment('botText', 'left')
    addLuaText('botText')
	if getPropertyFromClass('ClientPrefs', 'downScroll') == false then
    setProperty('botText.y', 2)
	setProperty('botText.x', 1100)
	end
	function onUpdate(elapsed)
	if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.P') and cpuControlled then
		if getProperty('cpuControlled') then
			setProperty('cpuControlled', false)
		else
			setProperty('cpuControlled', true)
		end
	end
	if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.G') then
		setProperty('health', getProperty('health') - 0.1) 
	end
end
	if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.G') then
		setProperty('health', getProperty('health') - 0.1) 
	end
	if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.H') then
		setProperty('health', getProperty('health') + 0.1) 
	end
end'

Yet when I press the 
![2022_04_08_0gc_Kleki (1)](https://user-images.githubusercontent.com/90159750/162450149-a7dee443-0d07-4dff-b4c8-4988535d253e.png)
p 
![2022_04_08_0gi_Kleki](https://user-images.githubusercontent.com/90159750/162450143-3fdcb627-9aed-4115-91e7-678a484902b5.png)
key, botplay is not enabled.
![2022_04_08_0gc_Kleki](https://user-images.githubusercontent.com/90159750/162450131-9eb1614f-826d-46a3-98b2-94fea3236df5.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Source code wise, No, Mods folder wise, yes.

**Comment by frantastic24** [comment]
You made your variable start as false and you're checking if it's true without ever changing it, of course your code doesn't work

**Comment by ShadowMario** [comment]
^

Your code doesn't do anything at all
