### ISSUE TITLE
make health bar skin with lua

### ISSUE THREAD

**Issue by PedroNinjaM** [ShadowMario/FNF-PsychEngine#8023]
### What is your question?

**how to make health bar skin with lua like this:**
![image](https://user-images.githubusercontent.com/97981969/162456073-dfd5ee7e-bb82-457e-b52b-e62a4d2860fe.png)
if you help me...thanks :)

**Comment by ManMaster707** [comment]
I don't you think you can, but you can put the png for it in 'mods/images' and name it exactly 'healthBar', so it can probably replace the existing png.

**Comment by Mastercopper2346** [comment]
Or, go to assets/images and open healthBar.png to edit it.

**Comment by frantastic24** [comment]
The color bar is rendered on top of the health bar so editing the texture does nothing

**Comment by ShadowMario** [comment]
> I don't think you can, but you can put the png for it in 'mods/images' and name it exactly 'healthBar', so it can probably replace the existing png.

^
This
