### ISSUE TITLE
Wrong camera in song

### ISSUE THREAD

**Issue by TarnSpill** [ShadowMario/FNF-PsychEngine#8024]
### Describe your problem here.

Hi, when i started fully working with psych engine. And when make chart, i noticated for camera is "free" moving or full not moving.
When i so to files i noticed file of "chart" is different: in og fnf, other chart of mod and mine chart(sorry for my bad english).
And this prolem has in all versions: 0.42 and 0.52h(im working with out source).

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i tested in all "clear" versions

**Comment by ShadowMario** [comment]
I have no idea what you mean

**Comment by Lorekeeper49** [comment]
Do you mean that's it's moving incorrectly?

**Comment by frantastic24** [comment]
Probably check your BPM is correct and switch between player and opponent sections

**Comment by TarnSpill** [comment]
> I have no idea what you mean

I maybe I can post video this, but this post has limit for 10mb of videos

**Comment by TarnSpill** [comment]
> Probably check your BPM is correct and switch between player and opponent sections

Its no change, I trying

**Comment by frantastic24** [comment]
It would help if you at least explained what you tried, or show the chart file

**Comment by TarnSpill** [comment]
> 

Send  chart, like text? Or screenshot?

**Comment by frantastic24** [comment]
The file, not text or screenshots since they're much harder to read and you can't fit it into a screenshot anyways

**Comment by TarnSpill** [comment]
> The file, not text or screenshots since they're much harder to read and you can't fit it into a screenshot anyways

https://drive.google.com/file/d/104CRIXtfipYGbDzjW_bYVjZeQC7UZCdV/view?usp=sharing 
only like this

**Comment by frantastic24** [comment]
Have you tried changing camera offsets

**Comment by TarnSpill** [comment]
> Have you tried changing camera offsets

No, to tell the truth for the first time I hear
