### ISSUE TITLE
Bug Report: problem psych engine look's for mod's code 

### ISSUE THREAD

**Issue by Gibberditoslumber** [ShadowMario/FNF-PsychEngine#8026]
### Describe your bug here.

problem with the way Psych Engine look's for the mod's folder's in the actual game folder's resulting in a crash

### Command Prompt/Terminal logs (if existing)

```bash
file_contents,assets/data/atrocity/atrocity-hard.json
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

*i did not*

**Comment by ShadowMario** [comment]
It doesn't, i first tries to find if your chart exists in mods/YourModFolder/data/, if it doesn't then it searches for the assets folder.

TL DR: Files missing in your mod folder.

**Comment by Gibberditoslumber** [comment]
![image](https://user-images.githubusercontent.com/91945956/162569297-790b0074-0481-4d51-87f0-fc1214435bf7.png)
