### ISSUE TITLE
what happened while i was gone

### ISSUE THREAD

**Issue by SquareCatALT** [ShadowMario/FNF-PsychEngine#8028]
### What needs to be documented?

where is discussion? im not trolling

**Comment by sans400** [comment]
gone deleted extinct all i can say

**Comment by PrismLight** [comment]
It was deleted now run before shadow closes this discussion for duplicate
(he said it was annoying)

**Comment by SquareCatALT** [comment]
aw

**Comment by SonicProYT** [comment]
go get to https://github.com/mayo78/PSYCHDISCUSSIONS

**Comment by ShadowMario** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/44785097/162554078-1ab0f543-3a29-47ea-ad54-815d413607d4.png)
Very cool duplicate huh

We have a search bar you know
![Screenshot_2](https://user-images.githubusercontent.com/44785097/162554084-880b7ff9-4ef2-4d03-bb19-e155b938a7ce.png)
