### ISSUE TITLE
Problem with low res monitors

### ISSUE THREAD

**Issue by x975** [ShadowMario/FNF-PsychEngine#8031]
### Describe your bug here.

Basically, i'm in this old AOC monitor, then, the size is wrong then i cant see the score, Accuracy, Rating, Right Note. (except for healthbar) This happens everytime! Please fix this bug, Thank you.

~ Reflexx#1232

![image](https://user-images.githubusercontent.com/93215071/162535319-b178f382-8a36-4a16-9506-cc358429bdbc.png)
 This is proof, More size in the file to make the proof.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I don't know anything about programming. It's just a mod that is in gamebanana.

**Comment by ShadowMario** [comment]
Haxe bug.
