### ISSUE TITLE
Error: You cannot access the cpp package while targeting neko (Re)

### ISSUE THREAD

**Issue by DarkMinerULTRA** [ShadowMario/FNF-PsychEngine#8034]
### Describe your bug here.

the same as [the other one](https://github.com/ShadowMario/FNF-PsychEngine/issues/8033). You cant un-close issues sooooo uh
just take the same information from it

### Command Prompt/Terminal logs (if existing)

```bash
C:/HaxeToolkit/haxe/lib/discord_rpc/git/discord_rpc/DiscordRpc.hx:4: characters 8-20 : You cannot access the cpp package while targeting neko (for cpp.Function)
source/Discord.hx:4: characters 8-30 : ... referenced here
source/TitleState.hx:4: characters 8-15 : ... referenced here
source/Main.hx:18: characters 37-47 : ... referenced here
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No. This is the first time exporting the build.

**Comment by ShadowMario** [comment]
Why are you targeting neko?

**Comment by DarkMinerULTRA** [comment]
no, i typed "lime test windows" and it does that.

**Comment by machonessiebaby** [comment]
neko is macos and also android

**Comment by ShadowMario** [comment]
^
There's .bat files inside the `art/` folder of the source code, try running test_x64-debug.bat

**Comment by DarkMinerULTRA** [comment]
ok!

**Comment by DarkMinerULTRA** [comment]
ok i did it, but now it says
`Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC`
what now

**Comment by frantastic24** [comment]
Missing visual studio components

**Comment by DarkMinerULTRA** [comment]
i downloaded those...?

**Comment by frantastic24** [comment]
Clearly not since the error is there

**Comment by ShadowMario** [comment]
https://gamebanana.com/questions/8169

**Comment by DarkMinerULTRA** [comment]
oh. i read the funkin page and it said only this:
MSVC v142 - VS 2019 C++ x64/x86 build tools
Windows SDK (10.0.17763.0)

guess there was more to it. Thanks for telling me!!
