### ISSUE TITLE
events

### ISSUE THREAD

**Issue by WuffGaming** [ShadowMario/FNF-PsychEngine#8035]
### Describe your bug here.

cant add events on v5.2h no matter what

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by bacondanger** [comment]
what folder are you putting it in? make sure its correct. Also make sure your files have a .txt with them too

**Comment by TheLeerName** [comment]
if you trigger events via lua, try `addLuaScript('custom_events/event.lua')`
