### ISSUE TITLE
how to get rid of the secret bump

### ISSUE THREAD

**Issue by itzcj** [ShadowMario/FNF-PsychEngine#8038]
### What is your question?

i am trying to add a new title screen but shadow mario has taken control of my title screen HELP

**Comment by DarkMinerULTRA** [comment]
just enter the same code: "shadow". itll revert the screen back to the default one, which is your own one.

**Comment by itzcj** [comment]
> just enter the same code: "shadow". itll revert the screen back to the default one, which is your own one.

i feel dumb that it was that simple LMAO

**Comment by itzcj** [comment]
> just enter the same code: "shadow". itll revert the screen back to the default one, which is your own one.

i feel dumb that it was that simple LMAO

**Comment by ShadowMario** [comment]
I'm inside your PC.
