### ISSUE TITLE
How to Add More Freeplay Sections

### ISSUE THREAD

**Issue by MODHELP** [ShadowMario/FNF-PsychEngine#8039]
### What is your question?

I want to add freeplay sections like dave and bambi. but i use lua. Can someone help?

**Comment by frantastic24** [comment]
Source

**Comment by MODHELP** [comment]
Do you have a compiled code? didn't think so.

**Comment by frantastic24** [comment]
Cope

**Comment by MODHELP** [comment]
> Cope

Do you tho

**Comment by frantastic24** [comment]
I do lmao I'm sorry the word source scares you so much

**Comment by MODHELP** [comment]
No im fine i just am a dumb ass and i cant do it

**Comment by frantastic24** [comment]
So you can close this now

**Comment by MODHELP** [comment]
Nah, i want source

**Comment by MODHELP** [comment]
> Source
