### ISSUE TITLE
The screen flashes black and white whenever a "play animation event happens"

### ISSUE THREAD

**Issue by PotatoKing0419** [ShadowMario/FNF-PsychEngine#8040]
### Describe your bug here.

https://youtu.be/2DGnUm5qAm4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Very highly likely not a bug, one of your scripts is probably missing a check (a screen flash/fade one most likely)
Next time provide what files you're using

**Comment by PotatoKing0419** [comment]
> Very highly likely not a bug, one of your scripts is probably missing a check (a screen flash/fade one most likely) Next time provide what files you're using

@frantastic24 Do you mean I left an event there, or part of the event info is missing? If either, they're both not the reason, because I checked.
And the animations themselves do work, but I still don't know what's with the flashing.

**Comment by frantastic24** [comment]
You still didn't show your files

**Comment by PotatoKing0419** [comment]
> You still didn't show your files There is no part of play animation that causes a flash, try using the event without any of your scripts
@frantastic24 I tried playing the song without any of my scripts, and then without any events at all, and the flashing still happens.

**Comment by frantastic24** [comment]
it's supposedly triggering with an event so obviously any script that has onEvent(), i've already checked the event myself and no flashing

**Comment by PotatoKing0419** [comment]
im just gonna replace and redo the json idc anymore

**Comment by PotatoKing0419** [comment]
SO. Turns out, there was an event file that (somehow) interacted with the song and those events overlapped with the current ones, causing black and white screen flashes.
