### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8041]
### Describe your problem here.

When i try compiling, it says
`export/release/windows/haxe/ApplicationMain.hx:299: characters 48-52 : Type not found : Main`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i did not. I just added charaters and stuff

**Comment by Phoneguytech75** [comment]
You mind sending the file. This is very odd as the error is appearing in the export folder.

**Comment by ShadowMario** [comment]
Try deleting your `export` folder and compiling it again.

**Comment by Zzastroz** [comment]
i am having this same error too.
