### ISSUE TITLE
Help how can I make an animated background for the Title of my mod

### ISSUE THREAD

**Issue by TTliki** [ShadowMario/FNF-PsychEngine#8043]
### Describe your problem here.

how can I make an animated background for the Title of my mod Using the TitleState

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by bacondanger** [comment]
I think by using the gfdanceTitle.json you can put in extra animated sprites.

**Comment by vyroxhub** [comment]
> I think by using the gfdanceTitle.json you can put in extra animated sprites.

no
