### ISSUE TITLE
Change hud in song? please

### ISSUE THREAD

**Issue by GlithModder** [ShadowMario/FNF-PsychEngine#8045]
### Describe your problem here.

I need change hud in song event or script
please help me!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by tylerandari12** [comment]
You wanna know how to move the HUD camera around?

**Comment by GlithModder** [comment]
> You wanna know how to move the HUD camera around?

I mean change HP bar in song
