### ISSUE TITLE
Dialogue script crashes the game

### ISSUE THREAD

**Issue by AnFnfModmaker** [ShadowMario/FNF-PsychEngine#8048]
### Describe your bug here.

I dont know why, but the "use dialogue script (not mine)" is crashing when it was supposed to start! (when the videos ends, the game crashes)

https://user-images.githubusercontent.com/99932351/162581851-e4459635-191a-4740-8985-fd9111f1d2e6.mp4

please help :(

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
You have to show us the script 🙄

**Comment by AnFnfModmaker** [comment]
> You have to show us the script 🙄

local allowCountdown = false
function onStartCountdown()
	-- Block the first countdown and start a timer of 0.8 seconds to play the dialogue
	if not allowCountdown and isStoryMode and not seenCutscene then
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('Meeting', 'breakfast');
	end
end

-- Dialogue (When a dialogue is finished, it calls startCountdown again)
function onNextDialogue(count)
	-- triggered when the next dialogue line starts, 'line' starts with 1
end

function onSkipDialogue(count)
	-- triggered when you press Enter and skip a dialogue line that was still being typed, dialogue line starts with 1
end

i didn't maked the script so...yeah

**Comment by AnFnfModmaker** [comment]
now the dialogues are working, goodbye B)
