### ISSUE TITLE
Discussions 

### ISSUE THREAD

**Issue by randomaccount20** [ShadowMario/FNF-PsychEngine#8049]
### What is your question?

Since the discussions are removed, i just want to say that shadow mario should atleast fucking add show and tell into issues (or separate thing like actions, pull requests, code, and more) because we can't even show our showcases of stuff like custom arrow and more

**Comment by pekolol** [comment]
USE THIS https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/1

**Comment by Keoiki** [comment]
"because we can't even show our showcases of stuff like custom arrow and more"

Then use some other fucking place, why does it HAVE to be Github?

**Comment by randomaccount20** [comment]
@pekolol THANKS!!!!!!!!!!!!!!!!

**Comment by randomaccount20** [comment]
@pekolol THANK YOU SO MUCH !!!!!!!!!

**Comment by ShadowMario** [comment]
We have a Discord server, you might have Twitter/any other social media, why the fuck are you wanting to put a "Show and Tell" in a page specialized on REPORTING BUGS/ISSUES??

**Comment by randomaccount20** [comment]
@ShadowMario bro twitter has the most toxic community

no im not fucking installing it
