### ISSUE TITLE
typing con into boxes crashes the game

### ISSUE THREAD

**Issue by BaconChannel** [ShadowMario/FNF-PsychEngine#8050]
### Describe your bug here.

as the title says, typing con into textboxes crashes the game

this is probably way too minor of a bug to bother fixing but yeah

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by Phoneguytech75** [comment]
Idk if this is correct but con is one of those words that windows hates. So naming something con wouldn't work.

**Comment by ShadowMario** [comment]
^
