### ISSUE TITLE
All my new images crash Psych Engine??

### ISSUE THREAD

**Issue by 8bitjake** [ShadowMario/FNF-PsychEngine#8053]
### Describe your bug here.

Exactly as described on the tin.
Whenever I load a song with the character affected or go into the character editor with said character, the game crashes.
Weirdly enough, on the menu (which I modified to have the character on), the character is replaced with the default HaxeFlixel sprite (pictured).
![image](https://user-images.githubusercontent.com/75950907/162588193-5a4ec137-9537-4518-bb7e-275f7393f347.png)
(Character is supposed to be on the right.)
This only seems to happen with the *new* spritesheet I made.
Here's the same screenshot but with the working sheet:
![image](https://user-images.githubusercontent.com/75950907/162588265-cf97a39a-369a-421a-b503-034a11f3d19a.png)
This seems to happen on base Psych Engine as well, how do I fix this??

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added support for Erect remixes, changed the main menu, and also changed the icon's bumping pattern.

**Comment by ShadowMario** [comment]
While on the menu, characters can't be loaded, so you will always get the default haxe icon.
While in-game, it might be crashing either due to you not placing the files in the correct place or an issue with the XML file of your character.
