### ISSUE TITLE
v0.5.2h doesn't build to HTML5

### ISSUE THREAD

**Issue by oof-plays-yt** [ShadowMario/FNF-PsychEngine#8054]
### Describe your bug here.

How in God's name do I fix this?

### Command Prompt/Terminal logs (if existing)

```bash
source/WeekData.hx:11: characters 8-19 : You cannot access the sys package while targeting js (for sys.io.File)
source/editors/WeekEditorState.hx:34: characters 8-16 : ... referenced here

source/editors/MasterEditorMenu.hx:119: characters 37-52 : ... referenced here
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by TheLeerName** [comment]
delete 11 line, sys.io.File was imported in 4 line

**Comment by oof-plays-yt** [comment]
this shit's too difficult

**Comment by CPPxfnfmodsmaker** [comment]
oooo

**Comment by jbmagination** [comment]
https://github.com/Starmapo/FNF-PsychEngine-Extra/issues/11#issuecomment-1093299756

**Comment by ShadowMario** [comment]
Fixed
