### ISSUE TITLE
LoadingState.hx NO_PRELOAD_ALL not working

### ISSUE THREAD

**Issue by pasta870** [ShadowMario/FNF-PsychEngine#8055]
### Describe your bug here.

i tried removing no preload all but if i load anything on mods folder it always softlocks me on loading screen

### Command Prompt/Terminal logs (if existing)

```bash
Jssjsjz
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes

**Comment by Theoyeah** [comment]
yeah
me too...
Maybe try to find something that have a link with the loading state and the assets folder
