### ISSUE TITLE
How to force difficulty with source?

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8056]
### Describe your problem here.

How to force difficulty with source
PLEASE

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i did not. I just added charaters and stuff

**Comment by bacondanger** [comment]
if you only want one difficulty, go into the game, open your week editor, then go to the other page and put the name of the difficulty you want to force (nothing puts the normal easy, normal, hard), then save. Also just as a note, any extra added difficulties can be added by their png name (make sure that it is in the menu difficulties folder in the images folder, example "assets/images/menudifficulties/expert.png").

**Comment by Mastercopper2346** [comment]
termination gameplay:
asklklsaklsaklsaklsaklsalksaklasklsaklasklasklaklkalkaslksaklsaklsaklasklsaklsalklsaklasklaskaslkaslkaslasklasklasklasklasklasklasklasklsklasklakslsklasklasklkslaklaslksalkaslkasklsaklasklsalksalasklsakl

**Comment by Mastercopper2346** [comment]
termination gameplay:
asklklsaklsaklsaklsaklsalksaklasklsaklasklasklaklkalkaslksaklsaklsaklasklsaklsalklsaklasklaskaslkaslkaslasklasklasklasklasklasklasklasklsklasklakslsklasklasklkslaklaslksalkaslkasklsaklasklsalksalasklsakl

**Comment by Mastercopper2346** [comment]
BRUH WITH SORCE
