### ISSUE TITLE
where did tweens go

### ISSUE THREAD

**Issue by coolaydang** [ShadowMario/FNF-PsychEngine#8057]
### What needs to be documented?

the wiki page for tween are gone :(

**Comment by coolaydang** [comment]
oh never mind

**Comment by coolaydang** [comment]
plz delete

**Comment by ShadowMario** [comment]
You can close your own issues...
![Screenshot_2](https://user-images.githubusercontent.com/44785097/162595552-e20ca377-90d1-4f12-85d2-29e4ef55f931.png)
