### ISSUE TITLE
PlaySound being picky

### ISSUE THREAD

**Issue by Draconic-Hybrid** [ShadowMario/FNF-PsychEngine#8058]
### Describe your problem here.

So the playSound works in a script but for some reason doesn't work in an event? I have the exact same code for both.

`playSound('SUPERBF', 1)`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by MaybeMaru** [comment]
try using this, call the lua file and text file `playsound`
```
function onEvent(name, value1, value2)
	if name == 'playsound' then
	playSound(SUPERBF, 100)
	end
end
```
