### ISSUE TITLE
Whenever I start the program, it says there is no library with the ID "videos".

### ISSUE THREAD

**Issue by SAOarmyVID** [ShadowMario/FNF-PsychEngine#8059]
So, in trying to run Psych on a school computer (since it's the only thing I have access to) I ran the .exe through command prompt. Whenever I do this, it gives me the error 'There is no library with the ID "videos"'. What can I do to possibly fix this? Or am I just SOL?
![Screenshot (2)](https://user-images.githubusercontent.com/66288312/162596793-1e992cba-7620-45da-b5c4-5faf9fae42f4.png)

### Command Prompt

```bash
REM This is the command I used

start C:\Users\cb100004\Downloads\PsychEngine\PsychEngine.exe
```

**Comment by ShadowMario** [comment]
It looks like you deleted the assets/videos/ folder

**Comment by keanu64github** [comment]
Or, they started Psych Engine from the Start Menu, which due to the way the game is (looks for files in the folder it was started up in, which would probably be null if starting from the Start Menu), won't start.

**Comment by SAOarmyVID** [comment]
> It looks like you deleted the assets/videos/ folder, maybe by accident

This can't be the case, I checked the folder and it was there.

> Or, they started Psych Engine from the Start Menu, which due to the way the game is (looks for files in the folder it was started up in, which would probably be null if starting from the Start Menu), won't start.

Thing is, when using Command Prompt, you have to type the entire file path, so it wouldn't make sense that it doesn't know where the folders are. Especially since I can d this with other games and they work just fine.

**Comment by keanu64github** [comment]
> > It looks like you deleted the assets/videos/ folder, maybe by accident
> 
> This can't be the case, I checked the folder and it was there.
> 
> > Or, they started Psych Engine from the Start Menu, which due to the way the game is (looks for files in the folder it was started up in, which would probably be null if starting from the Start Menu), won't start.
> 
> Thing is, when using Command Prompt, you have to type the entire file path, so it wouldn't make sense that it doesn't know where the folders are. Especially since I can d this with other games and they work just fine.

cd to the directory first, it should work then.

**Comment by SAOarmyVID** [comment]
> > > It looks like you deleted the assets/videos/ folder, maybe by accident
> > 
> > 
> > This can't be the case, I checked the folder and it was there.
> > > Or, they started Psych Engine from the Start Menu, which due to the way the game is (looks for files in the folder it was started up in, which would probably be null if starting from the Start Menu), won't start.
> > 
> > 
> > Thing is, when using Command Prompt, you have to type the entire file path, so it wouldn't make sense that it doesn't know where the folders are. Especially since I can d this with other games and they work just fine.
> 
> cd to the directory first, it should work then.

Yup, it worked, thx a ton!!!

**Comment by keanu64github** [comment]
You're welcome! 😄

**Comment by TrueMcShit** [comment]
> > > It looks like you deleted the assets/videos/ folder, maybe by accident
> > 
> > 
> > This can't be the case, I checked the folder and it was there.
> > > Or, they started Psych Engine from the Start Menu, which due to the way the game is (looks for files in the folder it was started up in, which would probably be null if starting from the Start Menu), won't start.
> > 
> > 
> > Thing is, when using Command Prompt, you have to type the entire file path, so it wouldn't make sense that it doesn't know where the folders are. Especially since I can d this with other games and they work just fine.
> 
> cd to the directory first, it should work then.

what does cd mean

**Comment by MiguelNeves07** [comment]
its a command from cmd btw

**Comment by SquidRoblox** [comment]
Can sombody explain for me the whole proccess. I had the same problem but it was for one of the mods (Hit Single Real).
The folder is there but even if it wasnt i cant just create a new folder because its a .zip file. what do i do?

**Comment by sycorx92** [comment]
> Can sombody explain for me the whole proccess. I had the same problem but it was for one of the mods (Hit Single Real). The folder is there but even if it wasnt i cant just create a new folder because its a .zip file. what do i do?

I have the same problem with the same mod im searching for it for weeks now :/
![Névtelen](https://github.com/user-attachments/assets/bc73f8e9-8797-4d63-acff-7efbe47643d5)

**Comment by sycorx92** [comment]
> Can sombody explain for me the whole proccess. I had the same problem but it was for one of the mods (Hit Single Real). The folder is there but even if it wasnt i cant just create a new folder because its a .zip file. what do i do?

BRO BRO BRO I HAVE THE SOLUTION
You just need to do these things:
Locate the folder that are the assets and the exe and everything in it, it should be called 'bin' or smth
Click on 'Cut'
Go to the explorer
Press [username] (C:)
Right click and paste
Start it and there you go
If you downloaded the version I did, it may look like this:
![Névtelen](https://github.com/user-attachments/assets/df0d0bf3-411f-4130-adf2-c04d819c53fb)
