### ISSUE TITLE
(Lua) Detect lost focus 

### ISSUE THREAD

**Issue by Draconic-Hybrid** [ShadowMario/FNF-PsychEngine#8060]
### Describe your problem here.

I remember seeing code on discussions before it got bricked about having the game run in the background when the game wasn't focused, I was wondering how to recreate that (although make it exclusive to Botplay)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by AetherLynx** [comment]
if what you want is the game to be still running when the window it's unfocused and botplay is on then use this.
```lua
function onCreatePost()
    if getProperty('cpuControlled') then
        setPropertyFromClass('flixel.FlxG', 'autoPause', false)
    else
        setPropertyFromClass('flixel.FlxG', 'autoPause', true)
    end
end
```
