### ISSUE TITLE
Changing Faster Character Selection 

### ISSUE THREAD

**Issue by asdvtx** [ShadowMario/FNF-PsychEngine#8063]
### Describe your problem here.

How can i change faster charater section m? Please help
I trying to chart a custom song (not my song) and the section - DAD and BF is not correct

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by ShadowMario** [comment]
???

**Comment by jimmyjamescool** [comment]
what in the name of god is "section m"

**Comment by asdvtx** [comment]
> what in the name of god is "section m"

"m" was a Mistake

**Comment by ShadowMario** [comment]
I'm losing IQs per second

**Comment by CrusherMods** [comment]
> I'm losing IQs per second

did you mean less than a second?
