### ISSUE TITLE
how do i play anim while dad is playing a animation

### ISSUE THREAD

**Issue by Den198888** [ShadowMario/FNF-PsychEngine#8064]
### Describe your problem here.

how can i FORCED Play Animation while dad hitting notes but it will continue the animation 
setProperty('dad.specialAnim', true) is not working

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Den198888** [comment]
i already put characterPlayAnim('dad', 'hadolen', true) but its not forced

**Comment by ManMaster707** [comment]
I think you need to make the notes type 'no animation' when the animation starts, and then back to normal after the animation ends

**Comment by Den198888** [comment]
so do i need to make a custom notetype for it?

**Comment by kyo-3nomoto** [comment]
no it is already there @Den198888 
![Capture](https://user-images.githubusercontent.com/102794175/162615974-387d1545-9f37-4bfe-bbce-cd98e8a0c866.PNG)

**Comment by Den198888** [comment]
ohh tnx, but i have problem to it i have a button to play ATTACK animation
but when bf sings it stops the animation
or it is impossible

**Comment by KutikiPlayz** [comment]
`specialAnimation` only disables the idle, you need to use `stunned` if you wanna disable the note animations

**Comment by Den198888** [comment]
i did the setProperty('boyfriend.stunned', true) but idk what was it

**Comment by Den198888** [comment]
or i did it wrong
