### ISSUE TITLE
Loading Screens with .LUA

### ISSUE THREAD

**Issue by KyleOliverDeveloper** [ShadowMario/FNF-PsychEngine#8066]
### What is your question?

How do I add loading screens with .LUA? I’ve been trying for weeks now.

**Comment by AetherLynx** [comment]
Lua scripts are loaded only when the song starts, not outside songs, so it's basically imposible to load a lua script in, for example, the story menu. Closest thing you can do is add a "fake" loading screen image when the song is loaded then remove it after x seconds.

**Comment by Phoneguytech75** [comment]
You'd need to edit the LoadingState.hx file.

**Comment by ShadowMario** [comment]
You can't do a real useful loading screen.

**Comment by matt-sudo-jpg** [comment]
> You'd need to edit the LoadingState.hx file.

thats for a HTML build
