### ISSUE TITLE
Function for quitting in the middle of a song

### ISSUE THREAD

**Issue by Draconic-Hybrid** [ShadowMario/FNF-PsychEngine#8067]
### What is your question?

Is there a function that checks if the player quits in the middle of a song, whether from the pause menu, the game over screen, and hell, even restarting the song? I have onEndSong functions and I also want them to trigger when the player leaves so the player doesn't have to go back to the Settings menu to re-enable or re-disable the options I changed for the song.

**Comment by frantastic24** [comment]
Store client preferences in a variable then restore them under `function onDestroy()`
