### ISSUE TITLE
Adding Character in different new class

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#8068]
### Describe your problem here.

Basically I added a new class which extends MusicBeatState if that matters.
I wanted to add a character but it won't load the json or something.
The character gets added but it's the haxeflixel symbol.
```
class MattLoadingState extends MusicBeatState
{
	var bf:Boyfriend;
	override function create()
	{
		bf = new Boyfriend(0, 0, 'glove-boyfriend');
		bf.screenCenter();
		bf.x += 350;
		bf.y += 50;
		add(bf);
                ...
```
I tested this code in PlayState and it worked there so I'm not sure if I need to import a specific library or something.
I checked if the path was the same (it was the same).
I really don't understand the problem here.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added some mechanics and a new loadingstate

**Comment by ShadowMario** [comment]
Instead of using `MusicBeatState.switchState(new MattLoadingState());`, use `LoadingState.loadAndSwitchState(new MattLoadingState());`
