### ISSUE TITLE
How to remove/interact with offscreen notes in Chart Editor

### ISSUE THREAD

**Issue by AetherLynx** [ShadowMario/FNF-PsychEngine#8069]
### Describe your problem here.

I'm adding another mod's chart in psych engine, and that chart has custom notetypes. Sometimes the engine marks them as ? notes but sometimes they're offscreen, if so then i'm unable to remove them.

![image](https://user-images.githubusercontent.com/81195994/162638986-748fb8df-aec4-4b94-9151-ed1ca9f1e3fc.png)

If i try to select a notetype and apply it to those notes with Alt + Click the engine crashes.

Is there a way to move them into the chart so i can interact with them/remove them?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no, just a chart in the mods folder.

**Comment by BeastlyGhost** [comment]
afaik you can only clear them by clearing the entire section

**Comment by AetherLynx** [comment]
nvm i figured out how, by going to Section and clicking Mirror Notes twice they magically appear inside the editor.
