### ISSUE TITLE
HTML Mods Folder

### ISSUE THREAD

**Issue by Swagwhisperer10** [ShadowMario/FNF-PsychEngine#8071]
### Describe your bug here.

Mods folder doesn't load in using HTML only assets so how can I get custom events to work?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

Songs; Data; Weeks;

**Comment by TheKitBoi** [comment]
That's because HTML5 cant  support some mod support due to problems
