### ISSUE TITLE
No Fullscreen

### ISSUE THREAD

**Issue by BrownCatGaming** [ShadowMario/FNF-PsychEngine#8074]
### Describe your bug here.

I'm not modding psych engine but, in precompiled and in mods. there is no way to go into fullscreen on 0.5.2.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Ctrl + Alt

**Comment by frantastic24** [comment]
Alt + Enter

**Comment by BrownCatGaming** [comment]
ok thx
