### ISSUE TITLE
Game Crash. ;-;

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8075]
### Describe your problem here.

So I was working on some noice arrow movement. However...

![BrokenGame](https://user-images.githubusercontent.com/97060639/162677107-403258c4-c909-45bb-88cd-8d27c9d47d0b.png)

This code apparently breaks the game.

Is it the extensive use of tables or is the tween broken?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing changed.

**Comment by Gibberditoslumber** [comment]
OH OKAY

**Comment by Gibberditoslumber** [comment]
more broken then on Linux

**Comment by Gibberditoslumber** [comment]
![image](https://user-images.githubusercontent.com/97060639/162677107-403258c4-c909-45bb-88cd-8d27c9d47d0b.png)

**Comment by tylerandari12** [comment]
No clue what you mean but FYI theres no Lua error.

It just crashes...

**Comment by Gibberditoslumber** [comment]
i Mean Linux build works but when you play it you'll find a lot of problems

**Comment by tylerandari12** [comment]
Im on Windows x64 tho.

**Comment by tylerandari12** [comment]
Ok I found the answer...
