### ISSUE TITLE
Changable Fullscreen Keybind

### ISSUE THREAD

**Issue by BrownCatGaming** [ShadowMario/FNF-PsychEngine#8076]
### What feature do you want to get added on the **base** engine?

The Ability To Change The Fullscreen Keybind. (ALT + Enter Is Fine But This Would Be Nice)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Theoyeah** [comment]
cool
