### ISSUE TITLE
Notes Fade 

### ISSUE THREAD

**Issue by Shelvsk** [ShadowMario/FNF-PsychEngine#8079]
### What is your question?

how i can make the notes fade out in the start of song using Lua?

**Comment by MaybeMaru** [comment]
If you want to animate them fading then use the `noteTweenAlpha` function

**Comment by Shelvsk** [comment]
i used, but for some reason it don't works 😑

**Comment by MaybeMaru** [comment]
> i used, but for some reason it don't works 😑

Could you show the code you did?

**Comment by ShadowMario** [comment]
> i used, but for some reason it don't works 😑

You have to use it on `function onCountdownStarted()`

**Comment by Shelvsk** [comment]
```
function onSongStart()
    noteTweenAlpha('note1', 0, 0, 1.2, 'linear'
    noteTweenAlpha('note2', 1, 0, 1.2, 'linear'
    noteTweenAlpha('note3', 2, 0, 1.2, 'linear'
    noteTweenAlpha('note4', 3, 0, 1.2, 'linear'
end
```

**Comment by Guranlikesblue** [comment]
> ```
> function onSongStart()
>     noteTweenAlpha('note1', 0, 0, 1.2, 'linear'
>     noteTweenAlpha('note2', 1, 0, 1.2, 'linear'
>     noteTweenAlpha('note3', 2, 0, 1.2, 'linear'
>     noteTweenAlpha('note4', 3, 0, 1.2, 'linear'
> end
> ```

I edited the code you showed a bit and then tried it
```
function onSongStart()
    noteTweenAlpha('note1', 0, 0, 1.2, 'linear');
    noteTweenAlpha('note2', 1, 0, 1.2, 'linear');
    noteTweenAlpha('note3', 2, 0, 1.2, 'linear');
    noteTweenAlpha('note4', 3, 0, 1.2, 'linear');
end
```
I just closed the parentheses and it worked
However, only the right notes are delayed and fade out.
