### ISSUE TITLE
Animated Icons

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#8080]
### Describe your problem here.

So, I'm making an Indie Cross Full Ass PE Port, and I need a script for animated icons. This can REALLY help me when I port the Nightmare songs. Thanks!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by AetherLynx** [comment]
here's the code for an animated icon. (for dad's icon)
```lua
function onCreate()
		makeAnimatedLuaSprite('dadicon', 'image_file', getProperty('iconP2.x'), getProperty('iconP2.y'))
		addAnimationByPrefix('dadicon', 'default', 'animation_xml', 24, true)
		setScrollFactor('dadicon', 0, 0)
		setObjectCamera('dadicon', 'other')
		addLuaSprite('dadicon', true)
		setObjectOrder('dadicon', 99)
		objectPlayAnimation('dadicon', 'default', false)
end

function onUpdate(elapsed)
	if dadName == 'dad' then
		setProperty('camOther.zoom', getProperty('camHUD.zoom'))
		setProperty('dadicon.x', getProperty('iconP2.x'))
		setProperty('dadicon.angle', getProperty('iconP2.angle'))
		setProperty('dadicon.y', getProperty('iconP2.y') + 15)
		setProperty('dadicon.scale.x', getProperty('iconP2.scale.x'))
		setProperty('dadicon.scale.y', getProperty('iconP2.scale.y'))
	end
end
```

quick question, do you have a discord? i want to ask you something about the port, if that's okay with you.

**Comment by fnfdemonboi314159** [comment]
No, sadly. Thanks for the code btw, REALLY Appreciate it.

**Comment by fnfdemonboi314159** [comment]
>

**Comment by alum-inium-g3mer** [comment]
is this code for the source code or not?

**Comment by fnfdemonboi314159** [comment]
> is this code for the source code or not?

nope. this is Lua.

**Comment by Mastercopper2346** [comment]
#8522
