### ISSUE TITLE
Custom Arrow Editor

### ISSUE THREAD

**Issue by GD-MasterA** [ShadowMario/FNF-PsychEngine#8081]
### What feature do you want to get added on the **base** engine?

Please can an Arrow Editor get added to make it possible to add  basic custom arrows without code?
![image](https://user-images.githubusercontent.com/89449621/162781647-46650b4e-e48f-494d-9f41-2b8f2fb9591a.png)
![image](https://user-images.githubusercontent.com/89449621/162785213-d08273de-6bd1-48d5-99ef-c0f8635cbb1b.png)
![image](https://user-images.githubusercontent.com/89449621/162788652-eddc5d7f-1fb5-42ec-a9e7-93ff393c2175.png)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
What is the point of this
No one other than GitHub kids who can't do 3 lines of code is benefitted

**Comment by tylerandari12** [comment]
I mean it wouls certainly make things faster...

**Comment by frantastic24** [comment]
As if it wasn't fast already

**Comment by FluffyNotSeen** [comment]
I mean its easier
and you could make like custom arrow xml's
it would be nice to have that feature

**Comment by schwiftified** [comment]
The XML is already there, it's like a character editor.

**Comment by schwiftified** [comment]
He probably mean't PNG, without using the normal arrow template.

**Comment by GD-MasterA** [comment]
I added this because Lua is a complicated programming language. The arrow editor would make the .lua file

**Comment by schwiftified** [comment]
Exactly.

**Comment by frantastic24** [comment]
The engine doesn't write Lua for you and "Lua is complicated" is skill issue

**Comment by schwiftified** [comment]
The engine does make JSON.

**Comment by schwiftified** [comment]
And Lua is pretty complicated.

**Comment by frantastic24** [comment]
> The engine does make JSON.

Which aren't used for arrows, and that's not even the point

> And Lua is pretty complicated.

Not when all the functions are already pre baked into the engine and there's plenty of scripts going around to use as a guide, stop being lazy
