### ISSUE TITLE
Game stops rendering objects after a certain point (?)

### ISSUE THREAD

**Issue by ManMaster707** [ShadowMario/FNF-PsychEngine#8082]
### Describe your bug here.

I was making a stage script, when suddenly the game wouldn't render some objects, I tried everything, but nothing changed, and I'm pretty sure this is a bug. 
I'll show the whole stage script just in case:

`function onCreate()`

    nightStart = false;

    makeLuaSprite('bg', 'backgrounds/fright/iminyourwalls', -400, -280);
        scaleObject('bg', 1.6, 1.6);
        addLuaSprite('bg', false);

    makeLuaSprite('floor', 'backgrounds/fright/floor', -440, -255);
        scaleObject('floor', 1.6, 1.6);
        addLuaSprite('floor', false);

    makeLuaSprite('gradientSalvage', 'backgrounds/fright/gradient', -420, -255);
        scaleObject('gradientSalvage', 1.6, 1.6);
        addLuaSprite('gradientSalvage', true);

    makeAnimatedLuaSprite('puppet', 'backgrounds/fright/phantom_poopet', 0, -400);
        scaleObject('puppet', 1.5, 1.5);
        addAnimationByPrefix('puppet', 'scare', 'phantom_poopet appear', 24, false);
        objectPlayAnimation('puppet', 'scare');
        setProperty('puppet.x', getProperty('strumLine.x') + 630);
        setObjectCamera('puppet', 'other');      
        addLuaSprite('puppet', true);

    makeAnimatedLuaSprite('chica', 'backgrounds/fright/phantom_chica', 0, 0);
        addAnimationByPrefix('chica', 'scare2', 'phantom_chica scare', 16, false);
        objectPlayAnimation('chica', 'scare2');
        setProperty('chica.alpha', 0);
        setObjectCamera('chica', 'other');      
        addLuaSprite('chica', true);

    makeAnimatedLuaSprite('bb', 'backgrounds/fright/phantom_bb', 0, 0);
        addAnimationByPrefix('bb', 'scare3', 'phantom_bb idle', 20, false);
        addAnimationByPrefix('bb', 'empty', 'phantom_bb empty', 20, false);
        objectPlayAnimation('bb', 'scare3');
        setProperty('bb.alpha', 0);
        setObjectCamera('bb', 'other');      
        addLuaSprite('bb', true);`

from this point on, the sprites wouldn't load (the sprite's paths are correct).

     `makeLuaSprite('blackScrAfton', 'black', 0, 0);
        scaleObject('blackScrAfton', 10, 10);
        setObjectOrder('blackScrAfton', 'center');
        setObjectCamera('blackScrAfton', 'other');
        setProperty('blackScrAfton.alpha', 1);
        addLuaSprite('blackScrAfton', true);

    makeAnimatedLuaSprite('glitchSixAM', 'backgrounds/fright/nightBeatGlitch', 0, 0);
        scaleObject('glitchSixAM', 2, 2);
        addAnimationByPrefix('glitchSixAM', 'glitch', 'glitch', 12, false);
        objectPlayAnimation('glitchSixAM', 'glitch');
        setProperty('glitchSixAM.alpha', 1);
        setObjectOrder('glitchSixAM', 'center');
        setObjectCamera('glitchSixAM', 'other');      
        addLuaSprite('glitchSixAM', true);
`end`

### Command Prompt/Terminal logs (if existing)

```bash
No, but i'm slowly going insane over this.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i just added things trough the "mods" folder.

**Comment by frantastic24** [comment]
not a bug
the game is rendering your objects, but `'center'` isn't a valid argument for `setObjectOrder`, so their order is set to 0 (behind everything)
`center` should be an int

**Comment by ManMaster707** [comment]
Thanks, but it didn't work, you said useful stuff though

**Comment by frantastic24** [comment]
Tested it myself, and it was creating the same "issue"
Either don't use setObjectOrder or use it properly

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#object-orderremoving

**Comment by ManMaster707** [comment]
Don't worry, I resolved the problem myself
