### ISSUE TITLE
how to add extra keys (source code) please

### ISSUE THREAD

**Issue by zeadd21g1233** [ShadowMario/FNF-PsychEngine#8083]
### Describe your problem here.

help i want add more keys to my build dont call me download psych engine extra keys my own build have to many codes idont want to lose them and i want add extra keys

for some covers

plssssssssss

give me tutorial

or example

i tried to make to make it 

the game worked but the notes glitched all notes are left and no animation and crash some times then i add extra key

then i play song and crash then i pass 10 second

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i edited playstate and chartingstate and song.hx

**Comment by zeadd21g1233** [comment]
and note.hx and notesplash.hx and clientprefs and controls and controlssubstate.hx

**Comment by zeadd21g1233** [comment]
pls help i want extra keys pls

**Comment by zeadd21g1233** [comment]
my version 0.5.2h

**Comment by LTZ-Knight** [comment]
Zeadd21g1233 you do know there is a mod that supports up to 9 keys, right? if not here is the download (there is source btw)

https://gamebanana.com/mods/311713

**Comment by zeadd21g1233** [comment]
![ScreenShot_20220411231146](https://user-images.githubusercontent.com/95078441/162834467-6b07a128-a92e-467e-88f5-7ebb62d18771.png)

**Comment by zeadd21g1233** [comment]
look at this

**Comment by zeadd21g1233** [comment]
what the problom 
ow then i add more than 4 key

game crash

**Comment by zeadd21g1233** [comment]
![ScreenShot_20220412003031](https://user-images.githubusercontent.com/95078441/162844131-ffa4b577-9ad8-45e3-bf50-5f36ab92cbde.png)
fixed game crash then i add more keys

**Comment by zeadd21g1233** [comment]
what is this problom

my version support 11key

**Comment by zeadd21g1233** [comment]
to know i dont want to lose my codes

i made all mechanices

like monochrome and qt and tricky all mechanics and jumpscare and new qt mechanic made by me lol

**Comment by Stilic** [comment]
shut up
shadow mario said no
close this issue

**Comment by zeadd21g1233** [comment]
and im code extra keys 

just i need to know how to fix my problom

in the code

**Comment by zeadd21g1233** [comment]
no disscuss

**Comment by frantastic24** [comment]
Don't care, to somewhere else

**Comment by zeadd21g1233** [comment]
Stupid Github Give up
