### ISSUE TITLE
Scroll speed bugged

### ISSUE THREAD

**Issue by tsuchi0** [ShadowMario/FNF-PsychEngine#8084]
### Describe your bug here.

I've been having this extremely weird issue with scroll speed where the game will not use the correct speed in game, no matter what i change it to it's always the default slowest speed. When i play the chart in the tester though, the speed is correct. I've got no idea what causes this issue or if there is a fix but it's happened on two mods, one i made and one i downloaded. If anyone knows how to fix this, please let me know. Currently the bug is only showing up on the latest release.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, all i did was add a custom mod folder.

**Comment by MaybeMaru** [comment]
weird, check if the scroll speed is the correct one in the .json and if you are saving the chart correctly
