### ISSUE TITLE
Ability To Reset Achievements

### ISSUE THREAD

**Issue by GERShark8209** [ShadowMario/FNF-PsychEngine#8086]
### What feature do you want to get added on the **base** engine?

A button or feature that lets you reset your achievements

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by sans400** [comment]
winning icons can be done with source, 6K the creator said they're not adding that,  stage editor the creator said they were already adding that i think that's what they said

**Comment by ShadowMario** [comment]
Done on experimental branch, thank you for the suggestion
