### ISSUE TITLE
¿Can you do a week with a video?

### ISSUE THREAD

**Issue by Kreith12** [ShadowMario/FNF-PsychEngine#8087]
### What is your question?

¿does anyone know if it is possible?

**Comment by FluffyNotSeen** [comment]
Yes it is possible, paste this into your script.lua

local allowCountdown = false
function onStartCountdown()
	if not allowCountdown and isStoryMode and not seenCutscene then --Block the first countdown
		startVideo('testVideo');
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

**Comment by FluffyNotSeen** [comment]
Yes it is possible, paste this into your LUA script:

`local allowCountdown = false
function onStartCountdown()
	if not allowCountdown and isStoryMode and not seenCutscene then --Block the first countdown
		startVideo('testVideo');
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end`
