### ISSUE TITLE
Will you add opponent play?

### ISSUE THREAD

**Issue by drakonieyah** [ShadowMario/FNF-PsychEngine#809]
### What feature do you want to get added on the base engine?

Basically, there would be an option to select whether you would want to play the opponent's chart, or bf's.

**Comment by Yoappian** [comment]
there is a thing called OPPNT.PLAY , but i cannot implement it at all, idk how... i hope shadow will :D

**Comment by DEV-idiotXD** [comment]
make a difficulty with the stage obj position flipped and set ur char to te enemy and vise versa and then flip the sections save da chart make a difficulty opnt play then make the json u just made to be for the opnt play dif
