### ISSUE TITLE
Icon Change

### ISSUE THREAD

**Issue by FluffyNotSeen** [ShadowMario/FNF-PsychEngine#8092]
### What is your question?

How do i like make the opponent icon change mid song without changing the character?

**Comment by frantastic24** [comment]
source only
```haxe
iconP2.changeIcon('icon')
```

**Comment by Gibberditoslumber** [comment]
whet

**Comment by frantastic24** [comment]
maybe scroll up

**Comment by FluffyNotSeen** [comment]
where do i put it

**Comment by frantastic24** [comment]
Don't ask me, put it where you want to change the icon

**Comment by Mastercopper2346** [comment]
i think i have an event going.
