### ISSUE TITLE
Randomized Menu bgs

### ISSUE THREAD

**Issue by HowWasTheFall** [ShadowMario/FNF-PsychEngine#8093]
### What is your question?

so i wanna know if your able to have randomized menu bgs on psych, if so how?

**Comment by tylerandari12** [comment]
You'd need the source code...

Are you trying to made a Dave and Bambi port?

**Comment by HowWasTheFall** [comment]
> 

i have the source code and i have multiple menu bgs so im just trying to get them in

**Comment by HowWasTheFall** [comment]
> > 
> 
> i have the source code and i have multiple menu bgs so im just trying to get them in
