### ISSUE TITLE
Adding easter eggs (without source code)

### ISSUE THREAD

**Issue by Filename99** [ShadowMario/FNF-PsychEngine#8095]
### Describe your problem here.

Hello! I'm making a SilvaGunner mod and I have a bit of an issue. You see, they made two Gettin' Freaky and I want to make the second one a completely different code because I didn't want to disrespect the creators of the engine and replace them with... um, you know, Friday Night Fu*kin'. I'm one hell of a shitty programmer and I don't think my potato computer can handle compiling the thing, so... Is there a way to make an entirely separate easter egg (+ make another Logo Bumpin' thing) with Lua?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Replaced assets for the "GF screen". You know, the title screen?

**Comment by Filename99** [comment]
If you're wondering, here are the links for Freaky songs:

1. https://www.youtube.com/watch?v=30EEBaLBAvE
2. https://www.youtube.com/watch?v=5zePHv0vjqw

**Comment by bacondanger** [comment]
i think you would put a lua script that says 
onCreate()
code stuff here to get to music file
print (math.random (1, 2))
end stuff

sorry if that didn't help. I'm also ass at coding

**Comment by ShadowMario** [comment]
You can't do more than one title screens in Lua.
