### ISSUE TITLE
How do I switch the combo sprites?

### ISSUE THREAD

**Issue by PainChungles** [ShadowMario/FNF-PsychEngine#8096]
### What is your question?

I want to know if their is a way for me to switch the original combo sprites (Sick, Good, Bad, Shit) to a different skin of the combo sprites

**Comment by Draconic-Hybrid** [comment]
I think the easiest option is to replace the images in `assets/shared/images`

**Comment by bbpanzu** [comment]
if you name it the exact same, the game will replace it itself

og: assets/shared/images/good.png
mod: myMod/images/good.png

the game will show the mod asset.

**Comment by Lorekeeper49** [comment]
If you want it for a specific song, download the whitty mod, go to data/ballistic-(beta-mix), copy the script in there and paste it into the data folder of the song you want it for and edit the code as needed to load the images

**Comment by PainChungles** [comment]
Thank you @Lorekeeper49 that's exactly what I meant!
