### ISSUE TITLE
inputting week images in the week editor

### ISSUE THREAD

**Issue by SarahDrewington** [ShadowMario/FNF-PsychEngine#81]
The week editor keeps telling me theres no image of a certain file name when there obviously is.

**Comment by ShadowMario** [comment]
Where did you put your week image?

**Comment by SarahDrewington** [comment]
where it told me to, images/storymenu/(insert png name).png

**Comment by ShadowMario** [comment]
Yes but did you put it in mods/images/storymenu or assets/images/storymenu/? Because you should never add files in assets/

**Comment by ShadowMario** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/44785097/133909976-47477dea-3306-4502-b365-902cfa07e70c.png)

**Comment by SarahDrewington** [comment]
in assets/, but every time i search in the mod folder, theres no folder labeled "mods/images/storymenu", do i just make a folder in there??

**Comment by SarahDrewington** [comment]
creating a folder in the mods menu did the trick
