### ISSUE TITLE
why do you not allow the following

### ISSUE THREAD

**Issue by official-ys** [ShadowMario/FNF-PsychEngine#8103]
### What is your question?

why do you not allow requests for Stage editor, 6k+ support, or winning icons? lmao

**Comment by machonessiebaby** [comment]
repetitive and annoying

6k just use the shaggy source
stage editor kept being spammed
winning icons are pretty overrated in most cases

**Comment by SAB236YT** [comment]
stage editor is a really dumb quest for me but winning icons are not that bad for me and they are easy to do for yourself

**Comment by tylerandari12** [comment]
Some madlad actually found a way to do 6k, 7k, 8k, and 9k woth only lua...
https://gamebanana.com/mods/352021
Hope this helps...

**Comment by machonessiebaby** [comment]
> Some madlad actually found a way to do 6k, 7k, 8k, and 9k woth only lua... https://gamebanana.com/mods/352021 Hope this helps... (Also theres 1k support :O)

very broken doe missing crashes the game
