### ISSUE TITLE
Character load crashing the game

### ISSUE THREAD

**Issue by AnFnfModmaker** [ShadowMario/FNF-PsychEngine#8104]
### Describe your bug here.

I tryed to put a 3d character (like dave in furiosity) but when i put the name and i click "load image" the game just crashes

here's the proof that i put the png and the xml in the right folder 

https://user-images.githubusercontent.com/99932351/163293234-540f1b9c-de63-417f-b37b-d6b5293dcca8.mp4

and the proof of the crashing

and again, when the video ends, the game crashes.

https://user-images.githubusercontent.com/99932351/163072793-75bd4599-6c88-49c1-8c5c-e2693d2e306a.mp4

Idk what is going on, but the game just crashes.

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Didn't show what folder the files are in and didn't show the actual files
Recheck your files

**Comment by AnFnfModmaker** [comment]
> Didn't show what folder the files are in and didn't show the actual files Recheck your files

how about now? @frantastic24

**Comment by frantastic24** [comment]
Okay but what about the two other things I mentioned

**Comment by bbpanzu** [comment]
make sure your spritesheets are in the images/characters/ folder

**Comment by AnFnfModmaker** [comment]
> make sure your spritesheets are in the images/characters/ folder

yes the folders are in images/characters/ folder

**Comment by AnFnfModmaker** [comment]
> Okay but what about the two other things I mentioned

_JUST SEE THE VIDEO, RIGHT FOLDER_

**Comment by frantastic24** [comment]
Read again, show the file contents

**Comment by AnFnfModmaker** [comment]
> Read again, show the file contents

wdym

**Comment by frantastic24** [comment]
What's inside your damn files my god

**Comment by ShadowMario** [comment]
Just show an screenshot of where you put your images please

**Comment by AnFnfModmaker** [comment]
> ### Describe your bug here.
> I tryed to put a 3d character (like dave in furiosity) but when i put the name and i click "load image" the game just crashes
> 
> here's the proof that i put the png and the xml in the right folder https://user-images.githubusercontent.com/99932351/163080359-487ba1a2-9558-437e-b616-c75f6b941e6f.mp4
> 
> and the proof of the crashing
> 
> and again, when the video ends, the game crashes.
> 
>  Friday.Night.Funkin._.Psych.Engine.2022-04-12.20-51-54.mp4 
> Idk what is going on, but the game just crashes.
> 
> ### Command Prompt/Terminal logs (if existing)
> _No response_
> 
> ### Are you modding a build from source or with Lua?
> _No response_
> 
> ### What is your build target?
> Windows
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> no



> What's inside your damn files my god



> What's inside your damn files my god

check the fucking video

**Comment by AnFnfModmaker** [comment]
> Just show an screenshot of where you put your images please

i think the video os more visible now, u can check it

**Comment by machonessiebaby** [comment]
> > Just show an screenshot of where you put your images please
> 
> i think the video os more visible now, u can check it

did you put you 

charactername.json

into the mods/characters folder?
if you did not thats why

**Comment by machonessiebaby** [comment]
also one more thing it nay just be the amount of frames I have  a sprite sheet with 50 frames per animation or more and it really lag psych engine just to load it

**Comment by AnFnfModmaker** [comment]
> > > Just show an screenshot of where you put your images please
> > 
> > 
> > i think the video os more visible now, u can check it
> 
> did you put you
> 
> charactername.json
> 
> into the mods/characters folder? if you did not thats why

https://user-images.githubusercontent.com/99932351/163407488-37ba9113-0a99-4d49-90a9-a635d1316f04.mp4

**Comment by AnFnfModmaker** [comment]
> also one more thing it nay just be the amount of frames I have a sprite sheet with 50 frames per animation or more and it really lag psych engine just to load it

no the character dont have 50 frames per animation, the  spritesheet is the same as the others that i make and idk why, is not loading it (and if u want the full sprite heres a zip file because the sprite is too big lol https://www.mediafire.com/file/fa96491xv020fod/the_spritesheet_idk_i_hate_my_life_aaaaaaaaaaaaaaaaaaaaaaa.zip/file )

**Comment by impostor5875** [comment]
maybe because you're doing it FROM INSIDE A ZIP FILE

JUST UNZIP THE FILE

**Comment by frantastic24** [comment]
it works lol, willing to bet it's your pc shitting itself

![image](https://user-images.githubusercontent.com/95725102/163435467-bc2ae6dc-1ae0-4f85-8711-0d9b5f14376e.png)

**Comment by AnFnfModmaker** [comment]
> maybe because you're doing it FROM INSIDE A ZIP FILE
> 
> **just unzip the file**

the file is unziped, i just ziped it because the sprite is too big

**Comment by AnFnfModmaker** [comment]
**FINALLY WORKED!**
