### ISSUE TITLE
Change Characters doesn't work correctly.

### ISSUE THREAD

**Issue by Lissard-Interactive** [ShadowMario/FNF-PsychEngine#8105]
### Describe your bug here.

Example: If I use Daddy Dearest as an opponent, and I use the change character event to change dad to Pico, Pico shows up, but Daddy Dearest doesn't disappear, he just stays perfectly still while Pico takes control.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by ShadowMario** [comment]
You're probably using it next to a Blammed Lights event.
Either that or Linux sucks balls, since it works fine for everyone else...
