### ISSUE TITLE
Fake lag lua script

### ISSUE THREAD

**Issue by cubers93** [ShadowMario/FNF-PsychEngine#8106]
### Describe your problem here.

i want to have a fake lag script but i have no idea how to code on lua
the only thing i can think of is setting the fps cap to a low number

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by impostor5875** [comment]
> I know that with the `getProperty()` thing you can get a lot of variables from the game and stuff, I dont know if the fps cap is one of them tho

yeah of course you can get the fps cap
you just need `getPropertyFromClass()` instead

```
function onStepHit()
       if curStep == number then
              getPropertyFromClass('ClientPrefs.framerate', number)
       end
end
```

**Comment by tylerandari12** [comment]
> 

Set it to 2 lol.
