### ISSUE TITLE
Randomized Menu bgs 

### ISSUE THREAD

**Issue by HowWasTheFall** [ShadowMario/FNF-PsychEngine#8108]
### What is your question?

Im trying to add randomized menu bgs into my mod, i have the source code but theres no turtorials

**Comment by bbpanzu** [comment]
learn haxeflixel

there are haxeflixel tutorials

**Comment by SonicProYT** [comment]
> learn haxeflixel
> 
> there are haxeflixel tutorials

bro, vs dave and bambi source code exists

https://github.com/FuseIsHere813/VsDave

**Comment by SonicProYT** [comment]
there’s randomize bg inside
