### ISSUE TITLE
Stage.

### ISSUE THREAD

**Issue by EvcazinDeveloper** [ShadowMario/FNF-PsychEngine#8109]
### Describe your problem here.

Well, my stage isn't working. I'll send right here and right now the LUA Code.

function onCreate()
	-- background shit
	makeLuaSprite('sad', 'sad', -706, -334);
	setScrollFactor('sad', 0, 0);
	
	addLuaSprite('sad', false);
	
	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by MaybeMaru** [comment]
make sure the image is in the right folder and set the scroll factor to 1

**Comment by kingyomoma** [comment]
why is the scroll factor 0

**Comment by bbpanzu** [comment]
saying "it's not working" doesn't tell us anything. what result do you expect and what result are you getting?

**Comment by ShadowMario** [comment]
What exatly isn't working? Elaborate
