### ISSUE TITLE
"Set Cam Zoom" event doesn't work

### ISSUE THREAD

**Issue by Maxenswel** [ShadowMario/FNF-PsychEngine#8110]
### Describe your problem here.

So on the Psych Engine (5.2h), I encountered a problem while charting a song. I wanted to use the popular event "Set Cam Zoom". At my surprise, it did nothing. And I'm 99% sure I used it correctly. imagine a stage is zoomed to 0.7. On the 1st value of the event, I wrote 0.9, and NOTHING happened. Either it's a real bug, or I'm dumb. I'd appreciate if someone here could help me. Thanks !

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by FinGonz** [comment]
bruh, this only works after the player/opponent hits a note.
if that doesn't work, i'll need to see the script.

**Comment by Maxenswel** [comment]
> bruh, this only works after the player/opponent hits a note. if that doesn't work, i'll need to see the script.

Look at the whitty mod. Precisely at the very beginning of Overhead. The event works without a single note.

**Comment by bbpanzu** [comment]
not a psych issue. that might be an issue you need to take to the original scripter

**Comment by machonessiebaby** [comment]
function onCreate()
    setProperty('camGame.zoom', 3)
    doTweenZoom('begin', 'camGame', '0.3', 5, 'quadOut')
end


this works better
3 is the zoom in
5 is the speed
you ccan change the
camGame to any camera type
(not and event shove into a lua script)

**Comment by Lorekeeper49** [comment]
If you're using the one from the whitty mod then there's one problem with that event and how it's explained, here's how it should be explained:

Set the camera zoom 
Both values have to be filled for the event to work

Value 1: zoom
Value 2: time it takes for it to fully finish zooming in seconds
