### ISSUE TITLE
How to not show "three two one go"

### ISSUE THREAD

**Issue by SAB236YT** [ShadowMario/FNF-PsychEngine#8111]
### What is your question?

**NO I DONT WANNA SEE SOMONE SAYING JUST MUTE THE SOUND OR REPLACE PNGS TO TRASPARENT**

### So do you know how?
 No. So does anynone know how to? PLS RESPOND

**Comment by frantastic24** [comment]
`introSoundsSuffix` and `setProperty('sprite.visible', false)`

**Comment by machonessiebaby** [comment]
setProperty('skipCountdown', true)
    it skips only for the song
it will be disabled afterwards
