### ISSUE TITLE
Can't get into the song

### ISSUE THREAD

**Issue by ODHG1** [ShadowMario/FNF-PsychEngine#8112]
### Describe your problem here.

Hi, so uhh, i added a week in mods folder, and songs and data, basic stuff i always do on Psych Engine and it always work, but this time, when i open a song from that week, i get to Pico song, but the song's charting is still used. I tried deleting pico from the game ( the song ) but it just turns the timer into 0:00 and it's a soft crash

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

well i just added the week in the mods folder, i tried it without source code in the beginning, but i got that problem, so i just moved to source code but the same thing happens

**Comment by MaybeMaru** [comment]
Make sure everything in the chart editor and the .json is correct
Also you should totally share stuff so I can find the actual problem, doesnt help saying that it just doesnt work

**Comment by ODHG1** [comment]
[mods.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8490862/mods.zip)

**Comment by frantastic24** [comment]
why is there a rar inside a zip but anyway
![image](https://user-images.githubusercontent.com/95725102/163438627-2b7fa4e7-0da3-4065-89b8-b18700455e5d.png)

**Comment by ODHG1** [comment]
wdym song : pico ?

**Comment by ODHG1** [comment]
i didn't make the assets

**Comment by ODHG1** [comment]
i just added it

**Comment by ODHG1** [comment]
oh, i see what you mean

**Comment by ODHG1** [comment]
Thanks.
