### ISSUE TITLE
Webm background (lua) 

### ISSUE THREAD

**Issue by YokEdici02** [ShadowMario/FNF-PsychEngine#8113]
### What is your question?

Is webm background possible with lua? (0.5.2h

**Comment by MaybeMaru** [comment]
I dont think video backgrounds are compatible yet in psych

**Comment by TheKitBoi** [comment]
Also WEBM dosent exist in psych engine

**Comment by MaybeMaru** [comment]
> Also WEBM dosent exist in psych engine

yeah, there is only mp4 support
