### ISSUE TITLE
How do i change scrolls (middle of a song with lua)

### ISSUE THREAD

**Issue by Plotsh** [ShadowMario/FNF-PsychEngine#8114]
### What is your question?

idk if i can ask here, cuz the discussions got deleted :v

**Comment by Draconic-Hybrid** [comment]
If by "scrolls" you mean something like Scroll Speed, then yes, it's already there. If you mean from Side-to-middlescroll, (and vice versa) [I have a thing for that.](https://github.com/ShadowMario/FNF-PsychEngine/files/8485032/Force.Middlescroll.zip)

If you mean from Up-to-down (and vice versa), I have no idea

**Comment by Plotsh** [comment]
> 

i meant Between downscroll and Upscroll

**Comment by BocaIoachim** [comment]
function onEvent(name, value1)
                      if name == "Change to downscroll" then
for i=0,7 do
       	setPropertyFromGroup('opponentStrums',i,'downScroll',true)
       	setPropertyFromGroup('playerStrums',i,'downScroll',true)
end
end
end

**Comment by kingyomoma** [comment]
that would work, but the notes wont move (same with the healthbar) 
you would have to manually configure the y value of all the notes and the healthbar

**Comment by BocaIoachim** [comment]
function onEvent(name, value1)
if name == "Change to downscroll" then
for i=0,7 do
setPropertyFromGroup('opponentStrums',i,'downScroll',true)
setPropertyFromGroup('playerStrums',i,'downScroll',true)
setProperty('healthBar.y', <number>)
end
end
end

I dont remember how the set y was cuz im on phone rn at 22:23 for me , for the set y for strums thing just search in the promise mod song files or something, thats from where i found the change scroll thing
