### ISSUE TITLE
Help: Image removal

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#8115]
### Describe your problem here.

so i am trying to remove the time bar in a specific song and i am trying to remove it but nothing works
here's the code:
```
function onCreatePost()
	setTextFont("scoreTxt", "SFPixelate.ttf")
	setTextFont("timeTxt", "SFPixelate.ttf")
	setTextFont("botplayTxt", "SFPixelate.ttf")
	removeLuaSprite('timeBar', destroy:Bool = true)
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Mods folder

**Comment by CrusherMods** [comment]
remove the `destroy:Bool = true` part
if you plan on removing the sprite forever then just keep the `true` part

**Comment by frantastic24** [comment]
you can't remove it because it's not a lua sprite, make it invisible instead

**Comment by CheesecakeForever** [comment]
what's the variable for the time bar sprite too?

**Comment by CheesecakeForever** [comment]
thank you, but another question: how do i make a custom sprite for the health bar
