### ISSUE TITLE
Help: Sprites

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#8116]
### Describe your problem here.

i am coding a script for a song and i don't know how to replace the ui sprites with new ones, but just for that one song

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Mods folder

**Comment by machonessiebaby** [comment]
you can go into the game and replace files in  Assets but of not there should be a change sprite script for ones like 3 2 1 GO! healthbar and others

**Comment by tylerandari12** [comment]
I know you can hide the healthbar and remove the 321GO thing...
But I dont know how to change them...
Ima stay tuned for anything noice...

**Comment by CheesecakeForever** [comment]
alr then, and how do i remove the 321GO sprites in that specific song?
