### ISSUE TITLE
I want it to if you hold a certain button you can't hit notes

### ISSUE THREAD

**Issue by Slimquickhunt** [ShadowMario/FNF-PsychEngine#8117]
### Describe your problem here.

I'm trying to have it if you hold a certain button you can't hit notes

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Soufon** [comment]
```
if keyPressed('left') then
	setProperty('boyfriend.stunned', true)
end
if keyReleased('left') then
	setProperty('boyfriend.stunned', false)
end
```
Replace "left" with the key you want to use, there's more info on keyPressed, etc on the Wiki.

**Comment by Slimquickhunt** [comment]
> ```
> if keyPressed('left') then
> 	setProperty('boyfriend.stunned', true)
> end
> if keyReleased('left') then
> 	setProperty('boyfriend.stunned', false)
> end
> ```
> 
> Replace "left" with the key you want to use, there's more info on keyPressed, etc on the Wiki.

still doesn't work even with heavy editing

**Comment by Slimquickhunt** [comment]
function onUpdate(elapsed)
	if keyPressed('space') then
	setProperty('boyfriend.stunned', true)
	else
	setProperty('boyfriend.stunned', false)
end
end
got it
