### ISSUE TITLE
Weird lua bug

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#8120]
### Describe your bug here.

So you know how you move arrows in lua 5.2h
well it used to work with
Function onCreate()
Function onCreate(elapsed)
Function onUpdate()
Function onUpdate(elapsed)
etc
but from some reason for me when i try to use anything besides 
Function onCreatePost()
or
Function onCreatePost(elapsed)
the arrows wont move

does anyone know why?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

sound changes and 2 custom achievements, 4 custom credits playstate.hx titlestate.hx main.hx

**Comment by frantastic24** [comment]
Arrows don't exist when `onCreate` is called, the rest work fine

**Comment by ShadowMario** [comment]
start the tween on OnCountdownStarted

**Comment by machonessiebaby** [comment]
> start the tween on `function OnCountdownStarted()`

Thanks!

> Arrows don't exist when `onCreate` is called, the rest work fine

Thanks!
