### ISSUE TITLE
can someone list shaders here?

### ISSUE THREAD

**Issue by SquareCatALT** [ShadowMario/FNF-PsychEngine#8121]
### What is your question?

pls

**Comment by Draconic-Hybrid** [comment]
Is this for Lua?
Shader code was removed from Lua when 0.5.2 was released, they just forgot to remove the folder, same for achievements.

If this is for source, then pretend this comment never existed.

**Comment by SquareCatALT** [comment]
oh they removed shaders from lua...

**Comment by SquareCatALT** [comment]
uhh

**Comment by SquareCatALT** [comment]
guess ill just
