### ISSUE TITLE
How do i make The "Up and Right" Notes On The Left side and "Left, Down" on right

### ISSUE THREAD

**Issue by Plotsh** [ShadowMario/FNF-PsychEngine#8123]
### What is your question?

![Screenshot_20220413-215146](https://user-images.githubusercontent.com/84821153/163292819-d44cdbe3-f6dc-47c8-83cf-62596de5cf3f.png)

like that with lua, pls help me i need this urgently (and a lua for PSYCH 0.5.1 cuz the 0.5.2h dont work on my phone sadly and i have a shitty pc)

**Comment by SquareCatALT** [comment]
well well well

**Comment by Plotsh** [comment]
> well well well

Is that eduardo from friday Night Funkin'??!?!?!!

**Comment by brayantomceacgd** [comment]
> > well well well
> 
> Is that eduardo from friday Night Funkin'??!?!?!!
WELL WELL WELL

**Comment by machonessiebaby** [comment]
with theese

im assuming you ONLY want PLAYER notes 

the 5-8 is the note 5-8 is players
1-4 opt
100
210
320
430
are the x values if u need Y just change noteTweenX to noteTweenY
	noteTweenX("NoteMove5", 4, 100, 2, cubeInOut)
	noteTweenX("NoteMove6", 5, 210, 2, cubeInOut)
	noteTweenX("NoteMove7", 6, 320, 2, cubeInOut)
	noteTweenX("NoteMove8", 7, 430, 2, cubeInOut)
the 2 is wait time
make sure to note note movements are inverted
