### ISSUE TITLE
Lua Tables and tweens

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8125]
### What is your question?

Does a Lua table take a lot of memory?
How about a tween?

**Comment by machonessiebaby** [comment]
it takes up 1000 if you have a lot of lua scripts loading upon startup somtimes and the tweens are not that bad look at the wiki you can learn a bit about em

**Comment by machonessiebaby** [comment]
also here is tweens for u

https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers
