### ISSUE TITLE
Animated Arrows Testing

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8126]
### Describe your problem here.

Could I ask you to paste the code [here](https://pastebin.com/wgNYRZGE) into a script in mods/scripts and play some songs with it?..

It keeps crashing at the end of the song for me and I need to know if it crashes for anyone else...

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing changed.

**Comment by tylerandari12** [comment]
M*LF is one of my favorite songs to do but you can play around with it...

**Comment by Mastercopper2346** [comment]
#8522
