### ISSUE TITLE
So about achievements...

### ISSUE THREAD

**Issue by Draconic-Hybrid** [ShadowMario/FNF-PsychEngine#8127]
### What is your question?

So at the time of this post, achievements are only creatable with source code. But I'm curious, could a custom achievement, such as completing a week, extend into the mods folder? 

Basically, I complete a week that rests in the mods folder, and it shows the achievement, despite the latter being source code.

The answer to this question may or may not determine whether I decide to dive into source code for my one mod

**Comment by machonessiebaby** [comment]
yea its possible 

check the template script in the wiki but here is the raw code for it to trigger in lua

function onCheckForAchievement(name)
	
	--deals with achievement checks
	
	--EX:
--[[
  if name == 'sick-full-combo' and getProperty('bads') == 0 and getProperty('goods') == 0 and getProperty('shits') == 0 and getProperty('endingSong') then
    return Function_Continue
  end
  if name == 'bad-health-finish' and getProperty('health') < 0.01 and getProperty('endingSong') then
    return Function_Continue
  end
  if name == 'halfway' and getSongPosition >  getPropertyFromClass('flixel.FlxG','sound.music.length')/2 then
    return Function_Continue
  end
	
	
	]]--
end

**Comment by Draconic-Hybrid** [comment]
Wait, so the achievement itself needs to be coded with source, but can be triggered with Lua? Do you mind if you explain it a bit more? I'm a little confused

**Comment by machonessiebaby** [comment]
> Wait, so the achievement itself needs to be coded with source, but can be triggered with Lua? Do you mind if you explain it a bit more? I'm a little confused

so 
it has to be coded in the achievements.hx file then it can be triggered with lua tho thats really just the code for 3 types of achievements though i dont know how to trigger them
