### ISSUE TITLE
Psych engine won't let me play custom songs from any menu

### ISSUE THREAD

**Issue by WaiEm33** [ShadowMario/FNF-PsychEngine#8129]
### Describe your bug here.

Hi, i need help. When i add new songs into psych engines mod file /songs/ and the and charts in /data/ with its names properly it loads in game, it crashes saying Json-Normal. I've checked the chart a million times and nothing, they just crash. But the weird thing is that i can chart and play the songs if i go to any song and load it on the debug menu but nothing else because it's on chart testing mode.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't , i just pasted my things in the mod folders

**Comment by Gibberditoslumber** [comment]
(Me) (assuming they are on linux there not) O H SO PSYCH ENGINE IS JUST BROKEN
