### ISSUE TITLE
What is "offsets" in bf.json?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#813]
### What is your question?

I want to add a character, so I need create a `character-name.json` in `FNF-PsychEngine-main\export\release\windows\bin\mods\characters`.

In this file ,there is a property named "offsets", like "bf.json". as follow:
![image](https://user-images.githubusercontent.com/13177997/140374064-ef6b8807-776c-4163-ad61-3971eb942d6b.png)

Question:
What does the "offsets" mean? 
How to determine its value?

**Comment by FuseIsHere813** [comment]
It means it is the X or Y axis for the character.

**Comment by nintendofan44** [comment]
press 8 in play state to edit those

**Comment by nintendofan44** [comment]
for any character

**Comment by Joseph-stiglich** [comment]
Basically it's very common for characters to just move around and not in the way they're supposed to, they literally just fly everywhere. Offsets glue a character into the position you want them to. Press 7 on main menu go to character editor and you can make the offsets.

**Comment by ShadowMario** [comment]
Animation offset from Character Editor, duh.
Press 8 during a song or press 7 on Main Menu.
