### ISSUE TITLE
Opponent's Notes

### ISSUE THREAD

**Issue by Nork1234** [ShadowMario/FNF-PsychEngine#8133]
### What is your question?

Is there any way for the opponent to have a different note skin in lua code? Like from Bob's Onslaught

**Comment by frantastic24** [comment]
github has a search feature, use that before posting

**Comment by frantastic24** [comment]
Close this

**Comment by MaybeMaru** [comment]
aaaaaaaaaaaand they never did

**Comment by tylerandari12** [comment]
lol
