### ISSUE TITLE
wavy stage bug

### ISSUE THREAD

**Issue by Games-player21** [ShadowMario/FNF-PsychEngine#8135]
### Describe your bug here.

function onCreate()

    makeLuaSprite('your-bg', 'your-bg', -600, -300)
    addGlitchEffect('your-bg', 2,2)
    addLuaSprite('your-bg', false)
    
end

Is something wrong with it?
if it's disabled then enable
becuase poeples says shaders are disabled pls enable

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

It's not build

**Comment by Games-player21** [comment]
me no online soo much so here
my discord
Bangi#6506

**Comment by frantastic24** [comment]
Shaders aren't supported so this is invalid

**Comment by Games-player21** [comment]
Wdym?

**Comment by frantastic24** [comment]
Don't report a bug about a feature that isn't even in the engine

**Comment by Games-player21** [comment]
but bruh the wavy stage not working

**Comment by frantastic24** [comment]
Learn how to read and close this

**Comment by Games-player21** [comment]
wdym?

**Comment by Games-player21** [comment]
SHIT FINE
