### ISSUE TITLE
Any chromatic aberration effect?

### ISSUE THREAD

**Issue by AssasinShadows** [ShadowMario/FNF-PsychEngine#8136]
### What is your question?

Does anyone know how to add a chromatic aberration effect to my level? LUA/script

**Comment by meeptey2** [comment]
1. Download the artifact of [this build](https://github.com/ShadowMario/FNF-PsychEngine/actions/runs/1848504403) depending on your os. 
2. In a Lua script, add `addChromaticAbberationEffect(<object>, <offset>); -- Default for the offset is 0.005`
Replace `<object>` with the camera/object you want to add the effect to. (ex. `'camGame'`)

**Comment by AssasinShadows** [comment]
>

THAAAAAAAAAANKS
