### ISSUE TITLE
changing bf object order makes him go faster

### ISSUE THREAD

**Issue by lun29** [ShadowMario/FNF-PsychEngine#8138]
### Describe your problem here.

i don't know if this is a bug or it's intended but i changed bf object order to 31 (with `setObjectOrder('boyfriend', 31)`) and his animations are faster, maybe it sets to 60 or something. anyways i need help because i need a way to change bf's character framerate in lua, something like `setProperty('boyfriend.fps')` or something else pls :(

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
use `boyfriendGroup`

**Comment by lun29** [comment]
> use `boyfriendGroup`

THANK YOUUU IT WORKED :DD
