### ISSUE TITLE
French Keyboard Support

### ISSUE THREAD

**Issue by Makko135** [ShadowMario/FNF-PsychEngine#8140]
### What feature do you want to get added on the **base** engine?

Hey, I don't really know if I should have wrote that in the bug report but anyways, I've been learning how to use Psych engine recently (you guys did an amazing work btw) and when I went to the chart editor and tried to type a name as a song title I couldn't write down underscores. Every letters work well from A to Z because there's no differences for that between a french keyboard and an english keyboard but when I was typing special characters like - or _ or & and etc what is shown on my screen is a different character, instead of the underscore, its typing a *. On an english keyboard where the 8 is located there is also the * but on a french keyboard where the 8 is located there is the underscore and that's why when I press 8 it types * instead of _
I'm really sorry if that was not clear enough, english is not my first language and trying to explain that is a real struggle.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
Pretty sure this is a haxe issue so not much can be done

**Comment by ShadowMario** [comment]
Just as the guy above said
