### ISSUE TITLE
Oh boy, first time using source

### ISSUE THREAD

**Issue by Draconic-Hybrid** [ShadowMario/FNF-PsychEngine#8142]
### Describe your bug here.

First time compiling, got this message
Is it safe to replace the lines as requested?

### Command Prompt/Terminal logs (if existing)

```bash
source/Achievements.hx:219: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/MainMenuState.hx:66: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:319: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/CharacterEditorState.hx:94: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/DialogueCharacterEditorState.hx:87: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Achievements and PlayState to add achievements

**Comment by CoolGuyisHere** [comment]
You can replace the lines if you really want to, but it doesn't change anything in the game if you don't and in my opinion, it would be easier if you'd just leave them as is. Plus, things might break if you do change them, but it's your choice

**Comment by Draconic-Hybrid** [comment]
Update: Tried replacing them, got a different error message for them. So basically, I'll never be able to compile the game. Also because of some other errors which I'm not sure if it's related to this

**Comment by XS09-dev** [comment]
You don't need to edit them those are normal and don't effect shit.

**Comment by meeptey2** [comment]
It says "Warning" in them, which means they can safely be ignored. You should keep those lines as removing them could create problems.

**Comment by PrismLight** [comment]
It's just saying that the current camera's are deprecated and suggesting to switch to `setDefaultDrawTarget`.
Pretty sure it automatically does that for you, but there is absolutely nothing to worry about.
