### ISSUE TITLE
All songs have slow song speed for some reason

### ISSUE THREAD

**Issue by Chez106** [ShadowMario/FNF-PsychEngine#8143]
### Describe your bug here.

Is there something wrong with the note speed when playing a song in 0.5.2h? Changing the note speed only works while testing the chart inside chart editor

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
This has already been answered several times, change scroll type in gameplay modifiers

**Comment by Chez106** [comment]
> This has already been answered several times, change scroll type in gameplay modifiers

Thanks, sorry for being an idiot

**Comment by frantastic24** [comment]
You can close this now
