### ISSUE TITLE
When I try to enter story mode or freeplay, it brings up an error message say "Invalid char 46 at position 183" Please help

### ISSUE THREAD

**Issue by supermase120** [ShadowMario/FNF-PsychEngine#8144]
### Describe your problem here.

I am developing a V2 of my mod using the extra keys version of psych engine made by tposejank

And I was adding stuff from V1 and new things and when I went to test them in freeplay, it said "Invalid char 46 at position 183"
I tried story mode and the same thing came up, I tried looking for the problem and I couldn't find it.

I will accept any advice or help.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by AdmiralUsername** [comment]
check the song data json file

**Comment by machonessiebaby** [comment]
check week data
redo the week data!
cuz the week data you may have messed it up thats what you have to do otherwise you redownload
the week data can corrupt causing this
