### ISSUE TITLE
Hold Notes can cause multiple misses

### ISSUE THREAD

**Issue by SkyanUltra** [ShadowMario/FNF-PsychEngine#8145]
### Describe your bug here.

Not much of a bug but more of how the engine works, however it is annoying when it does matter and makes scoring a bit innacurrate. no clue how exactly this would be fixed, i would think it might need an entire rework of how hold notes work so i don't mind much if this gets closed lol

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by MaybeMaru** [comment]
pretty sure that's intentional
