### ISSUE TITLE
crash with images

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#8149]
### Describe your bug here.

every time you try to load an image from the `mods` folder the engine crashes also when modifying any image in `assets/images` the engine doesn't even open even if you put the edited image in `mods/images`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, the `mods` folder and `assets/images` i edited the `MenuBG` files and `LogoBumpin.png`, `LogoBumpin.xml`

**Comment by frantastic24** [comment]
Provide files

**Comment by ShadowMario** [comment]
Sounds like a problem with YOUR images.

**Comment by BernardoGP4504** [comment]
here it is
![menuBG](https://user-images.githubusercontent.com/101405920/163580630-5e37462c-fbda-4bb7-94a3-2a8bb437385f.png)
![menuBGBlue](https://user-images.githubusercontent.com/101405920/163580638-c5f4dd9e-d0ca-4538-b4d2-c6c67f71ce23.png)
![menuBGMagenta](https://user-images.githubusercontent.com/101405920/163580641-5be032cb-6fd8-4e77-bda6-ccca1b82d638.png)
![menuDesat](https://user-images.githubusercontent.com/101405920/163580643-4d3947c5-88f1-49a0-bfa9-52a2211bfed1.png)
![logo used as a base for logoBumpin](https://user-images.githubusercontent.com/101405920/163580668-7f15925a-7fa7-4d74-a0fd-ce03c8a8a4a7.png)
![logoBumpin](https://user-images.githubusercontent.com/101405920/163580673-c3ed9794-688f-4bd9-8a84-b6f298e48c49.png)

**Comment by BernardoGP4504** [comment]
used `logo.png` as a base for making `logoBumpin.png`

**Comment by BernardoGP4504** [comment]
as previous said by me, i modified the `logoBumpin.xml` file (just to make the animation work propely)

**Comment by BernardoGP4504** [comment]
oh nevermind. It was just the `titleBG.png` file acting up
