### ISSUE TITLE
Hey man, i need help with backgrounds

### ISSUE THREAD

**Issue by Sebasyn0se** [ShadowMario/FNF-PsychEngine#815]
### Describe your problem here.

i have a little problem, I wanna add characters moving to the rhythm of the music in the background, but when i write it in the lua code, the level loads, but there appears the images of the sprites not the animation

![Friday Night Funkin'_ Psych Engine 04_11_2021 17_09_29](https://user-images.githubusercontent.com/93066244/140412594-9952a812-7403-46b6-8b1b-caa38a1d29b0.png)
![test-ddlc-bg lua - Visual Studio Code 04_11_2021 17_09_37](https://user-images.githubusercontent.com/93066244/140412598-577e009b-4e64-489e-8df8-b757f84fa2d2.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

**Comment by drakonieyah** [comment]
Hey! 
You need to write "makeAnimatedLuaSprite" not makeLuaSprite. That will only create a still image, even if it has animations. Then you need to add the animations from the xml. Here, check this out:
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Custom-Sprites-Functions
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions
Check the "Animation Functions" tab on the second link.

**Comment by GrateSkata** [comment]
^^^ bless this great goddess
