### ISSUE TITLE
Switch Mechanics and noteskins trough the song

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#8150]
### What feature do you want to get added on the **base** engine?

add an event that switches the noteskins during the song and also an event where you can toggle/change mechanics during the same song

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
You can already do this
