### ISSUE TITLE
Theres an script that make the icons NOT bop?

### ISSUE THREAD

**Issue by Plotsh** [ShadowMario/FNF-PsychEngine#8151]
### What is your question?

if yes, gimme pls lol

**Comment by BernardoGP4504** [comment]
i think there is one, i saw it in some mod

**Comment by lolbruhfart** [comment]
> i think there is one, i saw it in some mod

the Mandela mod i hink

**Comment by Plotsh** [comment]
> > i think there is one, i saw it in some mod
> 
> the Mandela mod i think

sorry for the late answer but i didnt find it
