### ISSUE TITLE
I need a composer!

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8152]
### Describe your problem here.

 (Use soft girl voice for Opponent)

Song 1: Slow, Calm and nothing really happens
Song 2: Super slow, but gets suddenly fast near the end.
Song 3: A mix of Slow, Fast, And super fast
Song 4: Fast and Super fast song

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

what

**Comment by frantastic24** [comment]
????

**Comment by Mastercopper2346** [comment]
bruh
