### ISSUE TITLE
Invisible note that plays no animation.

### ISSUE THREAD

**Issue by Maxenswel** [ShadowMario/FNF-PsychEngine#8158]
### Describe your problem here.

Since my last request, I've just learned that for the custom event "Set Cam Zoom" to work, a note needs to be hit by the player or the opponent. So, I just wanted to know if I could have a lua script to make an invisible note that doesn't play any animations. Thanks !

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by machonessiebaby** [comment]
dont use invisible notes use
function onCreatePost(elapsed)
    setProperty('camGame.zoom', 5)
    doTweenZoom('begin', 'camGame', '6', 3, 'quadOut')
    setProperty('camHUD.zoom', 5)
    doTweenZoom('begin', 'camHUD', '6', 3, 'quadOut') 
end


camGame can be replaced with
camHUD
or
camOther

camGame zooms in the game
camHUD zooms in the UI
camOther is the pause menu lol

use camGame and camHUD like i put above so you can have a similar feel
number 6 is the zoom
number 3 is the zoom out or in time
number 5 is starting song zoom
i recommend just making the 6 and 5 the same if you want but this is an easy way to do that instead
