### ISSUE TITLE
How to add modcharts no source code?

### ISSUE THREAD

**Issue by lolbruhfart** [ShadowMario/FNF-PsychEngine#816]
### Describe your problem here.

Im trying to make a cheating port and i was wondering if i can do modcharts without source code like in kaboom the notes move but its on a downloaded build

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Micasddsa** [comment]
Kaboom (i assume you are referring to the Madness vandalization) makes the entire UI shake, not just the notes, I do not think it's possible to make notes move like in cheating without modifications to the source code.

**Comment by lolbruhfart** [comment]
> Kaboom (i assume you are referring to the Madness vandalization mod) makes the entire UI shake, not just the notes, I do not think it's possible to make notes move like in cheating without modifications to the source code.

Well how does it make the hud shake with no source code is it the chart because the chart is 300kb

**Comment by nicho01022** [comment]
I tried to make this too in source code but I just don't understand much bout things yet

**Comment by PoleyMagik** [comment]
Cheating's effect requires modification to source, but since it was mentioned, here's the code for Kaboom's camera shake.
```
function onStepHit()
	if curBeat < 388 then
		if curStep % 4 == 0 then
			doTweenY('rrr', 'camHUD', -12, stepCrochet*0.002, 'circOut')
			doTweenY('rtr', 'camGame.scroll', 12, stepCrochet*0.002, 'sineIn')
		end
		if curStep % 4 == 2 then
			doTweenY('rir', 'camHUD', 0, stepCrochet*0.002, 'sineIn')
			doTweenY('ryr', 'camGame.scroll', 0, stepCrochet*0.002, 'sineIn')
		end
	end
end
```

**Comment by SrtHero278** [comment]
There are Four Functions for this:

noteTweenX(tag:String, note:Int, value:Dynamic, duration:Float, ease:String)
noteTweenY(tag:String, note:Int, value:Dynamic, duration:Float, ease:String)
noteTweenAngle(tag:String, note:Int, value:Dynamic, duration:Float, ease:String)
and noteTweenAlpha(tag:String, note:Int, value:Dynamic, duration:Float, ease:String)

tag is a random string for if you want to do something else after the tween has finished. (use function onTweenCompleted([whatever tag you used]))

note is the direction of notes.
Opponent's notes:
0- Left
1- Down
2-Up
3-Right
BF's notes:
4-Left
5-Down
6-Up
7-Right

value is the result of the tween (if you do noteTweenX('example', 0, 50, 1, 'linear'), the opponent's left arrow's x value will be 50.)

duration is how long it takes for the tween to finish.

and ease is the tweening method. (for example, 'linear' and 'quartIn')

Just make a file in your song folder named "script" (make sure it's a lua file) and use these functions. Boom.

**Comment by lolbruhfart** [comment]
thx for kabooms stuff i can now do cool

**Comment by lolbruhfart** [comment]
But do you have the script that makes the notes go side to side

**Comment by lolbruhfart** [comment]
HOLY GOD.
