### ISSUE TITLE
Start Up Screens.

### ISSUE THREAD

**Issue by Nork1234** [ShadowMario/FNF-PsychEngine#8161]
### What is your question?

Is there a way to have different startup screens for different songs in Lua? Like from Indie Cross or something. I tried searching the internet. Nothing came up that I wanted.

**Comment by lun29** [comment]
what do u mean with startup screens? like in indie cross the mechanic instructions before starting?

**Comment by Nork1234** [comment]
That was probably a bad example. Like the different startup screens in different songs. The one that goes 3, 2, 1, Go! I'm just wondering if you can make that startup screen different in different songs. (in lua code)

**Comment by lun29** [comment]
oh, you mean the start countdown.
you can change the introsounds suffix with this:
```lua
function onCreate()
     setProperty('introSoundsSuffix', '-custom')
end
```
so you can have intro sounds that end with `-custom` and it will play `intro1-custom`,`intro2-custom`,`intro3-custom`,`introGo-custom` in the start countdown.
and i think that you can change the sprites using this.
```lua
function onCreate()
     setProperty('countdownReady', 'yourReadySprite')
     setProperty('countdownSet', 'yourSetSprite')
     setProperty('countdownGo', 'yourGoSprite')
end
```

**Comment by Nork1234** [comment]
Thanks!

**Comment by frantastic24** [comment]
you have to hide the real countdown assets (`setProperty('countdownReady.visible', false)`) and then create and animate your own

**Comment by tylerandari12** [comment]
HOL UP

**Comment by PumpTutorials** [comment]
i was looking for something like this and this is perfect for my mod!
