### ISSUE TITLE
remove specific notes (lua)

### ISSUE THREAD

**Issue by lun29** [ShadowMario/FNF-PsychEngine#8162]
### Describe your problem here.

how to remove a specific notetype from the chart with a lua script? i have a setting to disable mechanics so i want to know how to remove the specific notetypes with a script. thank you
### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
`removeFromGroup('unspawnNotes', i)`

**Comment by lun29** [comment]
it removes like 50% but not all of them for some reason.

![image](https://user-images.githubusercontent.com/101958916/163684742-cfd1e02c-4946-4883-be40-891dfb705a79.png)

**Comment by frantastic24** [comment]
It's glitchy if there's a lot to remove but it's the only way

**Comment by lun29** [comment]
mmm okay, thank you!

**Comment by lun29** [comment]
edit: i did this instead lol

![image](https://user-images.githubusercontent.com/101958916/163698735-3a00545d-00f6-4c20-b022-66a86da1e41b.png)
