### ISSUE TITLE
change bg event for animated stages/bg

### ISSUE THREAD

**Issue by YoshiGames64** [ShadowMario/FNF-PsychEngine#8163]
### Describe your problem here.

i only need the change bg  event for animated background or stages but i cant find the event for sprite stage.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no i dont

**Comment by frantastic24** [comment]
```lua
setProperty('object1.visible', false)

setProperty('object2.visible', true)
```

**Comment by YoshiGames64** [comment]
is it for event if yes then thats all i need

**Comment by frantastic24** [comment]
you can close this then

**Comment by AntCrem** [comment]
late to the convo but if you still need it I have a lua event for bg change

**Comment by oisintheblue** [comment]
it doesnt work it said attempt to call global Setproperty (a nil value)
