### ISSUE TITLE
Stuff i need 2 know

### ISSUE THREAD

**Issue by roaring213** [ShadowMario/FNF-PsychEngine#8165]
### Describe your problem here.

Hi. I'm making an Indie Cross Cuphead Week Psych Engine port, and I know how to add a dodge mechanic, but not an attack mechanic. Is it even possible to make one? Also, how do you spawn objects? How do you add animated pieces to the foreground? How do you make a "play sound" event? Sorry if this is too much to answer, I just am not that good at coding. If anyone can help me with this, God BLESS them. Also, since I feel like it, here are some screenshots of the before mentioned Cuphead Indie Cross port. (yes, ik GF is not supposed to be there. I'm working on it)
![Screenshot](https://user-images.githubusercontent.com/80852158/163642045-b4f5e56e-c01a-406e-ae41-a0205cd1ab85.PNG)
![Screenshot-2](https://user-images.githubusercontent.com/80852158/163642072-6a7cc1e6-91b0-4bb9-b867-04ddf6e3905e.PNG)
![Screenshot-3](https://user-images.githubusercontent.com/80852158/163642089-cec32b71-cc98-45b0-847f-a682750e9942.PNG)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I've added normal Cuphead, Indie Cross BF and normal BG.

**Comment by zeadd21g1233** [comment]
i know how to make sans mechanic

**Comment by zeadd21g1233** [comment]
Source not Lua

**Comment by roaring213** [comment]
> Source not Lua

I'm looking for cuphead mechanics, not sans mechanic.

**Comment by WilliamGaming12** [comment]
Well i can't answer all of them, i just got the sound script:
[playSound event.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8523213/playSound.event.zip) (link to the script)

And for the object thing you got 2 ways to do it

1. By adding it to the sprites of a character
2. Adding an event that makes the sprite thing appear

I think BBpanzu made kinda a script on it, here link: https://www.youtube.com/watch?v=qxMyoudrFPs&t=4989s
(1:16:45 is where more and less he starts to make the object thing or whatever)

**Comment by roaring213** [comment]
> Well i can't answer all of them, i just got the sound script: [playSound event.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8523213/playSound.event.zip) (link to the script)
> 
> And for the object thing you got 2 ways to do it
> 
> 1. By adding it to the sprites of a character
> 2. Adding an event that makes the sprite thing appear
> 
> I think BBpanzu made kinda a script on it, here link: https://www.youtube.com/watch?v=qxMyoudrFPs&t=4989s (1:16:45 is where more and less he starts to make the object thing or whatever)

Wow, he did? I'll check it out. And also, I finally got some IQ and figured out how to make sounds play. Sorry, I forgot to remove that. And I also didn't know that I did add an animated piece for the BG, I just needed to scale it up. All I'm waiting for is an attack function. But still, thanks so much!

**Comment by itsDARK768** [comment]
dodging is a little more complicated then attacking which i already have a attack script ready, but its gone sadly

**Comment by roaring213** [comment]
> dodging is a little more complicated then attacking which i already have a attack script ready, but its gone sadly

Do you have it lying around in the recycle bin? If not, do you remember the script you used?

**Comment by WilliamGaming12** [comment]
Alr i got the script of attacking and dodging from a random guy on my youtube, i don't remember his name now but here's a link to the download:

https://drive.google.com/file/d/1PyHbYT_MORFT_esrrpJqaeUYygJcGbay/view?usp=sharing

NOTE: YOU NEED TO PUT THIS IN THE MODS FOLDER
controls: shift for attack and space for dodge

The script of attacking and dodging is in the data folder (mods/data/knockout/script)...

And there's a lot of indie cross ports right now so good luck!

**Comment by roaring213** [comment]
> Alr i got the script of attacking and dodging from a random guy on my youtube, i don't remember his name now but here's a link to the download:
> 
> https://drive.google.com/file/d/1PyHbYT_MORFT_esrrpJqaeUYygJcGbay/view?usp=sharing
> 
> NOTE: YOU NEED TO PUT THIS IN THE MODS FOLDER controls: shift for attack and space for dodge
> 
> The script of attacking and dodging is in the data folder (mods/data/knockout/script)...
> 
> And there's a lot of indie cross ports right now so good luck!

Thank you! I'll see if I can replicate some code out of this!
