### ISSUE TITLE
How do I make character(s) move behind girlfriend like in applecore in expunged's part but in psych engine

### ISSUE THREAD

**Issue by supermase120** [ShadowMario/FNF-PsychEngine#8167]
### Describe your problem here.

I wanna make my character move behind girlfriend like in applecore.

but here's the problem

idk how to do that because im a dumbass and can't code.

any help can and probably will help.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#object-orderremoving

**Comment by supermase120** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#object-orderremoving

what thing do I put for position

**Comment by Draconic-Hybrid** [comment]
A number.

**Comment by tylerandari12** [comment]
> > https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#object-orderremoving
> 
> what thing do I put for position

You'd need to experiment with that...

**Comment by frantastic24** [comment]
> You'd need to experiment with that...

Well no, getObjectOrder exists
