### ISSUE TITLE
I need some chromatic aberration effect for my level

### ISSUE THREAD

**Issue by AssasinShadows** [ShadowMario/FNF-PsychEngine#8168]
### Describe your problem here.

please I need some chromatic aberration effect for a level that I am doing

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by meeptey2** [comment]
[look at this](https://github.com/ShadowMario/FNF-PsychEngine/issues/8136#issuecomment-1100912934)
