### ISSUE TITLE
Window name (source or lua)

### ISSUE THREAD

**Issue by FlintIshe** [ShadowMario/FNF-PsychEngine#8169]
### What is your question?

How can I change the Window name depending on what song played?

like indie cross

**Comment by ManMaster707** [comment]
`setPropertyFromClass("openfl.Lib", "application.window.title", "yournamehere");`

**Comment by tylerandari12** [comment]
> in Lua: `setPropertyFromClass("openfl.Lib", "application.window.title", "yournamehere");`

Where could I get a list of theese openfl.lib things?
They seem fun to mess with...

**Comment by naether** [comment]
good ol' haxeflixel api
https://api.haxeflixel.com/lime/ui/Window.html

**Comment by meeptey2** [comment]
Source is just slightly easier!
`openfl.Lib.application.window.title = <name>;`

**Comment by FlintIshe** [comment]
ok i am back thanks guys for the help

**Comment by FlintIshe** [comment]
> in Lua: `setPropertyFromClass("openfl.Lib", "application.window.title", "yournamehere");`

But how can I change the window name back when I quit the song?

**Comment by naether** [comment]
```
function onDestroy()
	setPropertyFromClass("openfl.Lib", "application.window.title", "Friday Night Funkin': Psych Engine");
end
```
