### ISSUE TITLE
I made a script that runs in the stage, but I'd like to turn it into an event.

### ISSUE THREAD

**Issue by 3ncre** [ShadowMario/FNF-PsychEngine#817]
### Describe your problem here.

So, I have a script to make the strums swing left and right, but I'd like to make it as an event:

`function onUpdate()
	cpos = cpos + 0.25;

	setPropertyFromGroup('playerStrums', 0, 'x', defaultPlayerStrumX0 + math.sin(cpos / 10)  * 30);
	setPropertyFromGroup('playerStrums', 1, 'x', defaultPlayerStrumX1 + math.sin(cpos / 10) * 30);
	setPropertyFromGroup('playerStrums', 2, 'x', defaultPlayerStrumX2 + math.sin(cpos / 10) * 30);
	setPropertyFromGroup('playerStrums', 3, 'x', defaultPlayerStrumX3 + math.sin(cpos / 10) * 30);

	setPropertyFromGroup('opponentStrums', 0, 'x', defaultOpponentStrumX0 + math.sin(cpos / 10) * 30);
	setPropertyFromGroup('opponentStrums', 1, 'x', defaultOpponentStrumX1 + math.sin(cpos / 10) * 30);
	setPropertyFromGroup('opponentStrums', 2, 'x', defaultOpponentStrumX2 + math.sin(cpos / 10) * 30);
	setPropertyFromGroup('opponentStrums', 3, 'x', defaultOpponentStrumX3 + math.sin(cpos / 10) * 30);
end`

Is it possible? If so how can I do it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not.

**Comment by 3ncre** [comment]
It doesn't work :(

**Comment by ShadowMario** [comment]
Check out the event example on Lua Script API home page
