### ISSUE TITLE
How to get the player's username? (Lua)

### ISSUE THREAD

**Issue by ManMaster707** [ShadowMario/FNF-PsychEngine#8171]
### What is your question?

Since on source it's possible (`CoolUtil.getpcUSER()`), could someone tell me if it's possible to do this but on lua?

**Comment by impostor5875** [comment]
maybe try `getPropertyFromClass('CoolUtil', 'getpcUSER')` 

no idea if it'll work tho so don't take my word for it

**Comment by frantastic24** [comment]
As far as I can tell that function doesn't exist, you can't trigger haxe functions without coding them in FunkinLua beforehand anyways

**Comment by ManMaster707** [comment]
So it seems you can't do it in lua, ok then 👍

**Comment by ROCK201888** [comment]
wait. you can do it in lua.

function onCreate()
	cmd = io.popen('whoami')
	user_name = cmd:read("*all")
end

the user_name is the name
