### ISSUE TITLE
Animated sprite by Grid size rather than XML for Lua scripts

### ISSUE THREAD

**Issue by StahlReyn** [ShadowMario/FNF-PsychEngine#8172]
### What feature do you want to get added on the **base** engine?

Basically the title, make sprites able to get animation by specifying grid size, like how in haxe you can specify the frame size in loadGraphic(). 

Would be useful for simple sprite that are done in even proportion or not made in Adobe, like pixel sprite or something similar to icon list, and also reduce file clutter from unecessary extra XML file. addAnimationByIndices() already does the indice but still require extra XML stuff.

For example this would be the haxe equivalent:
![image](https://user-images.githubusercontent.com/86341393/163672050-0280814a-4690-481a-86a3-855b58acb8f0.png)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tylerandari12** [comment]
This would be useful not gonna lie...

**Comment by tylerandari12** [comment]
> This would be useful not gonna lie...

I came here thinking there was an answer...
Ive been lied to...

**Comment by Lokamon** [comment]
do u modding a lua?

**Comment by StahlReyn** [comment]
It got accepted let’s go
