### ISSUE TITLE
Bruh This Is Getting Annoying(crashes)

### ISSUE THREAD

**Issue by lolbruhfart** [ShadowMario/FNF-PsychEngine#8174]
### Describe your bug here.

My Game Does This Randomly And Has Been Doing This For A While But Kinda Just Started(it may be the system) it only does this with psych not kade or anything else
![WHY](https://user-images.githubusercontent.com/95049285/163679945-16cbf4f6-d738-4ae7-ac6b-0985e41c93c8.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, added stuff with the menu and thats really it

**Comment by ShadowMario** [comment]
Looks like a problem with your own PC, no clue honestly.

**Comment by Theoyeah** [comment]
i think it is a memory issue when the game tried loading the files but failed
