### ISSUE TITLE
How do I add a stage (using source code)

### ISSUE THREAD

**Issue by TaviGamer44** [ShadowMario/FNF-PsychEngine#8175]
### What is your question?

So now that I have my stage .png file I need to add it to the game and IDK how (I use Psych Engine 0.5.2h source code just like I said in the title. 
( ![E](https://user-images.githubusercontent.com/103366081/163684033-dd1585da-436e-4d0a-b270-7f9e436d7075.png) that's the image if someone can code it in and send it to me. Also please remove the other stages)

Thanks for your time!

**Comment by TaviGamer44** [comment]
Yes, it does look like the LSE Gain Stage Mania bg cuz I'm bad at drawing and stuff like that so I just copied and edited.

**Comment by frantastic24** [comment]
There are tutorials and you can also just look at other stage code

**Comment by TaviGamer44** [comment]
I cant find tutorials on 0.5.2h and the code is kinda messy

**Comment by frantastic24** [comment]
You don't need it to be for 0.5.2h

**Comment by TaviGamer44** [comment]
The code is different in playstate.hx I think in every new version.

**Comment by frantastic24** [comment]
Stages aren't affected

**Comment by TaviGamer44** [comment]
How? I watched catbrother everything and the code was different.

**Comment by TaviGamer44** [comment]
I tried it, and it's just a black bg.
lol, what do I do now?

**Comment by frantastic24** [comment]
i can't see what you did so i can't help, it could be wrong image directory, insufficient memory, wrong coordinates

**Comment by TaviGamer44** [comment]
I removed something, now it works, but when try to set the coordinates the image doesn't move
