### ISSUE TITLE
How can you add a watermark with source code?

### ISSUE THREAD

**Issue by AmonguslyCrazy** [ShadowMario/FNF-PsychEngine#8176]
### Describe your problem here.

Just for a modified PE.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by SAB236YT** [comment]
i dont have source but u can use lua it's esier `makeLuaText('watermark', songName .. " | Vs Cuby Remaster 5.0.2 | PE 0.5.2", 0, 2, 695); -- You can edit the created by Prisma Text just dont change anything else
        setTextSize('watermark', 18);
	    addLuaText('watermark');`

**Comment by CrusherMods** [comment]
where exactly would you want the watermark though?

**Comment by TON-Games** [comment]
you need to type this in playstate.hx

var watermark:FlxText = new FlxText(2, 695, 0, "(your watermark)", 18);
add(watermark);

**Comment by PDL2CGamejolt** [comment]
> you need to type this in playstate.hx
> 
> ```
> var watermark:FlxText = new FlxText(2, 695, 0, "(your watermark)", 18);
> add(watermark);
> ```

Where?
