### ISSUE TITLE
Frreeplay: Random Songs & playlists

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#8177]
### What feature do you want to get added on the **base** engine?

How about a random button, that will get you a random song?
This could also be added with maybe a kind of playlist, where you are able to put songs together and then have them a bit sorted. But if you like, you can also play the whole playlist. Or play a random song, chosen from it

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tylerandari12** [comment]
Theese "playlists" can be done with weeks however i see what youre talking about and totallt agree...
