### ISSUE TITLE
How Do I Make The Window Move?

### ISSUE THREAD

**Issue by bambbuddevman** [ShadowMario/FNF-PsychEngine#8179]
### What is your question?

How Do I Make The Window Move I See Strident Crisis Do It And I Need It For My Mod

**Comment by naether** [comment]
```
setPropertyFromClass("openfl.Lib", "application.window.x", <x position>)
setPropertyFromClass("openfl.Lib", "application.window.y", <y position>)
```

**Comment by meeptey2** [comment]
It's even easier in source!
`openfl.Lib.application.window.<axis> = <value>`

**Comment by tylerandari12** [comment]
Would it be possible to scale the window?

**Comment by naether** [comment]
yeah replace application.window.x with aplication.window.width or window.height

**Comment by FlamesYTEpic** [comment]
function opponentNoteHit()
    windowShake()
  end

function windowShake()
    windowX = getPropertyFromClass('openfl.Lib', 'application.window.x')
    windowY = getPropertyFromClass('openfl.Lib', 'application.window.y')
    setPropertyFromClass('openfl.Lib','application.window.x',windowX + math.random(-10,10))
    setPropertyFromClass('openfl.Lib','application.window.y',windowY + math.random(-5,5))
 end
