### ISSUE TITLE
How do I make a difficulty only available on Freeplay?

### ISSUE THREAD

**Issue by WaFl-XIV** [ShadowMario/FNF-PsychEngine#818]
### What is your question?

.

**Comment by FuseIsHere813** [comment]
Elaborate so we can know what your saying even more.

**Comment by WaFl-XIV** [comment]
How do I disable a difficulty on Story Mode so the only way to access the difficulty is on Freeplay?

**Comment by ShadowMario** [comment]
Duplicate of #645
