### ISSUE TITLE
Animation speed

### ISSUE THREAD

**Issue by Draconic-Hybrid** [ShadowMario/FNF-PsychEngine#8180]
### Describe your problem here.

Does adjusting the FPS of an animated lua sprite's animation adjust its speed? If not, what does, if anything?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, this is my downloaded build

**Comment by Draconic-Hybrid** [comment]
It IS FPS, nevermind

**Comment by Mastercopper2346** [comment]
#8522
