### ISSUE TITLE
how to fix psych engine android error

### ISSUE THREAD

**Issue by zeadd21g1233** [ShadowMario/FNF-PsychEngine#8181]
### Describe your problem here.

then i  join any song game give me this
![Screenshot_20220417-021524](https://user-images.githubusercontent.com/95078441/163695187-9689e74f-5e9e-45eb-a804-2740eb39b03d.jpg)
in android 

help i ported mod to mobile by myself

i run it in pc and didnt get the problom

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i add mobile controls

**Comment by ShadowMario** [comment]
Android part isn't official.
