### ISSUE TITLE
i wanna do more stuff with dialogue boxes

### ISSUE THREAD

**Issue by osogames24fanosogames** [ShadowMario/FNF-PsychEngine#8182]
### What feature do you want to get added on the **base** engine?

If you wanted to, you could add an advanced button to show more stuff you could do in the dialogue editor, like playing specific sounds at specific parts, shaking the dialogue HUD, using either built-in triggers or ones made in LUA or Source Code for some more interesting stuff in the hands of people, or even adding more colors into the text other than black or white. This could take a lot of time, especially because I can relate to how hard it is to implement some stuff, and also because of compatibility issues with older versions if this ever gets made, but in the end, it would be pretty nice to have.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by naether** [comment]
yeah more dialogue box stuff like this and fonts should be added
