### ISSUE TITLE
How to Hide HUD

### ISSUE THREAD

**Issue by KlimozzZero** [ShadowMario/FNF-PsychEngine#8183]
### What is your question?

Um, hey, does anyone know how to hide HUD? (.lua specifically)

**Comment by SAB236YT** [comment]
setProperty(camHUD.visibile, false)

**Comment by tylerandari12** [comment]
> `setProperty(camHUD.visibile, false)`

Correcting a small typo...
`setProperty(camHUD.visibile, false)`
