### ISSUE TITLE
Does persistent cached data default to true?

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8184]
### What is your question?

Theres a removed feature from the engine called `Persistent Cached Data` and Ive been meaning to disable it because of how it affects my computer...

Is there a way to disable it if its still on?

(Also whered it go? :0)

**Comment by ShadowMario** [comment]
Persistent Cached Data is on by default now, HOWEVER, it works differently, which means it's more optimized than having Cached data turned off in older versions, so it's a win-win situation
