### ISSUE TITLE
How to open a cutscene when seven pressed

### ISSUE THREAD

**Issue by WinV-Bros** [ShadowMario/FNF-PsychEngine#8188]
### Describe your problem here.

i want to make this video as a cutscene when you press seven lololol: https://www.youtube.com/watch?v=5pUSX9kvARQ

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, watermark, warning screen, rating name change, botplay text change, kade engine text that shows sicks, goods, bads, and shits, plus achievements (all lua btw)

**Comment by Shelvsk** [comment]
try this
```
function onUpdate(elapsed)
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
        startVideo('YOUR_VIDEO')
    end
end
```

**Comment by WinV-Bros** [comment]
Thanks! It worked!

**Comment by WinV-Bros** [comment]
do you know how to mute sound while the cutscene plays as well?

**Comment by naether** [comment]
try adding endSong() before the startVideo

**Comment by WinV-Bros** [comment]
it just ends the song without playing the cutscene

**Comment by WinV-Bros** [comment]
(sorry for late reply lol)
