### ISSUE TITLE
i have an idea when you change the bpm, you can snap the notes

### ISSUE THREAD

**Issue by im557** [ShadowMario/FNF-PsychEngine#8189]
### What feature do you want to get added on the **base** engine?

when you change the bpm, you can snap the notes. i accidentally used the wrong bpm for charting and the whole charting messed up.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by naether** [comment]
oh my god yes bpm scaling notes is such a good idea
