### ISSUE TITLE
Animation bug?

### ISSUE THREAD

**Issue by furryChrisUSER** [ShadowMario/FNF-PsychEngine#8190]
### Describe your bug here.

So I added a character to the game with the character editor and when I try and get him to do sing animations in an actual song he won't do them. What might be the issue?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a new week, icons, character, and song into their respective folders in mods.

**Comment by frantastic24** [comment]
Wrong animation names, they should be singLEFT, singRIGHT, and so on

**Comment by furryChrisUSER** [comment]
Thanks a lot!

**Comment by frantastic24** [comment]
If it's fixed, you can close this

**Comment by furryChrisUSER** [comment]
True
