### ISSUE TITLE
while im making a engine (with src of psych engine)

### ISSUE THREAD

**Issue by sugodick** [ShadowMario/FNF-PsychEngine#8191]
### What is your question?

how do you even put watermark with src?

**Comment by sugodick** [comment]
.......

**Comment by Stilic** [comment]
no

**Comment by Mastercopper2346** [comment]
i have my own engine

**Comment by ShadowMario** [comment]
So... you want to make an FNF Engine but you don't even know how to put a watermark.

**Comment by sugodick** [comment]
the kade engine song watermark thing
