### ISSUE TITLE
Credits crash

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8192]
### Describe your bug here.

It says: 
(link of credits)
The application has failed to start because its side-by-side information is incorrect. Please
see the application event log or use the command-line sxstrace.exe tool for more information.

### Command Prompt/Terminal logs (if existing)

```bash
The application has failed to start because its side-by-side information is incorrect. Please
see the application event log or use the command-line sxstrace.exe tool for more information.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i did not.

**Comment by Mastercopper2346** [comment]
Help shadow mario

**Comment by ShadowMario** [comment]
**Provide more information.**
How did you add the credits? Through CreditsState.hx or the credits.txt file?
Show the one you edited/created.

**Comment by Mastercopper2346** [comment]
i did not add any credits

**Comment by Mastercopper2346** [comment]
HELP
