### ISSUE TITLE
how do i make the window shake

### ISSUE THREAD

**Issue by amazingikerlin3** [ShadowMario/FNF-PsychEngine#8193]
### Describe your problem here.

how do i make the window shake

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

songs, events, custom notes, and characters.

**Comment by machonessiebaby** [comment]
[WindowShake.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8502428/WindowShake.zip)
this works but bugged at song start it will shift the window over
sometimes the shake wont end im not the one who made this let me know if it works for u

**Comment by amazingikerlin3** [comment]
> [WindowShake.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8502428/WindowShake.zip) this works but bugged at song start it will shift the window over sometimes the shake wont end im not the one who made this let me know if it works for u

WORKS PERFECTLY thx
