### ISSUE TITLE
How to make player's health drain when the opponent hits an specific note.

### ISSUE THREAD

**Issue by djawesomeyt** [ShadowMario/FNF-PsychEngine#8194]
### Describe your problem here.

Hey, ngl i'm a bit of a noob when It comes to all this lua stuff.  Anyway I'm trying to have the player's health drain whenever the opponent hits an specific note. This is the code I have but it's not working...

```function onEvent(name, value1, value2)
	function opponentNoteHit(noteType)
		setProperty('noteType', 'Doof Sings')
		if getProperty('health') > (value2 / 50) and getProperty('health') < (value1 / 50) then 
			setProperty('health', (value2 / 50))
		else if  getProperty('health') > (value2 / 50) and getProperty('health') > (value1 / 50) then
			setProperty('health', getProperty('health')-(value1 / 50))
		end
		end
	end	
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nah.

**Comment by frantastic24** [comment]
#3911

**Comment by frantastic24** [comment]
```lua
function opponentNoteHit(id, direction, type, sustain)
     if type == '' then

     end
end
```

**Comment by djawesomeyt** [comment]
IT WORKS!
thanks!
