### ISSUE TITLE
songName detection

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#8196]
### Describe your problem here.

so i have a lua script inside of mods/scripts
it changes the window title to what song or menu you are in
the problem is on other lua scripts when i use songName like with addluatext if i use songName it will change to the song name
i want to know how to do that with the window instead 
here is my script

function onPause()
setPropertyFromClass("openfl.Lib", "application.window.title", " FNF Vs M.R.L.N   songName - paused");
end
function onResume()
setPropertyFromClass("openfl.Lib", "application.window.title", " FNF Vs M.R.L.N   songName - playing");
end

function onEndSong()
setPropertyFromClass("openfl.Lib", "application.window.title", " FNF Vs M.R.L.N  -  Menus");
end

function onGameOver()
setPropertyFromClass("openfl.Lib", "application.window.title", " FNF Vs M.R.L.N  songName   -  Dead");
end

function onStartCountdown()
setPropertyFromClass("openfl.Lib", "application.window.title", " FNF Vs M.R.L.N  songName  -  Countdown");
end

function onSongStart()
setPropertyFromClass("openfl.Lib", "application.window.title", " FNF Vs M.R.L.N   songName - playing");
end

function onGameOverConfirm(retry)
	setPropertyFromClass("openfl.Lib", "application.window.title", " FNF Vs M.R.L.N   songName - Retry");
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

sound changes and 2 custom achievements, 4 custom credits playstate.hx titlestate.hx main.hx healthicon.hx

**Comment by frantastic24** [comment]
`" FNF Vs M.R.L.N "..songName.. "- paused"`

**Comment by machonessiebaby** [comment]
> `" FNF Vs M.R.L.N "..songName.. "- paused"`

kk thanks
