### ISSUE TITLE
Can someone give some of the in-engine events as an lua file?

### ISSUE THREAD

**Issue by WaFl-XIV** [ShadowMario/FNF-PsychEngine#8199]
### What is your question?

The only ones I need at the moment is the Change Character event and the Blammed Lights event (don't ask why I need the latter)

**Comment by frantastic24** [comment]
change character isn't possible

**Comment by acap09** [comment]
> change character isn't possible

does ```setProperty('dad.curCharacter', character)``` work?

**Comment by frantastic24** [comment]
No

**Comment by WaFl-XIV** [comment]
Ok what about the Blammed Lights one if the Character Change isn't possible on lua?

**Comment by frantastic24** [comment]
I think it's just tweens so you should be able to do it

**Comment by ShadowMario** [comment]
Do it yourself
