### ISSUE TITLE
is there a way to change opponent note texture without changing player one?

### ISSUE THREAD

**Issue by kirilllll9999** [ShadowMario/FNF-PsychEngine#8200]
### What is your question?

is there a way to change opponent note texture without changing player one?
like in dave and bambi, 3D-Dave has 3D notes and bf still have 2D notes

**Comment by Meme1079** [comment]
this only changes the note strums
```
function onUpdate(elapsed)
    for i = 0,4,1 do
        setPropertyFromGroup('playerStrums', i, 'texture', '2D Note Texture');  
        setPropertyFromGroup('opponentStrums', i, 'texture', '3D Note Texture'); 
    end
end     
```   
but here's a Custom note just put it the Opponent section
```
function onCreate()
    for i = 0, getProperty('unspawnNotes.length')-1 do
        if getPropertyFromGroup('unspawnNotes', i, 'noteType') == '3D Note' then
            setPropertyFromGroup('notes', i, 'texture', '3D Note Texture');  
        end 
    end
end
```

**Comment by frantastic24** [comment]
> function onUpdate

Why

**Comment by Meme1079** [comment]
> Why

Because it crashes the game

**Comment by frantastic24** [comment]
No?? Use onCreatePost and stop skyrocketing memory usage

**Comment by frantastic24** [comment]
No?? Use onCreate or onCreatePost and stop running code every frame when you only need it once

**Comment by Meme1079** [comment]
> No?? Use onCreate or onCreatePost and stop running code every frame when you only need it once

`function onCreatePost` only works but `function onCreate` crashes

**Comment by frantastic24** [comment]
So use that???
