### ISSUE TITLE
more than 2 maps in character editor

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#8204]
### What feature do you want to get added on the **base** engine?

simple
i think that we should be able to choose a background other than the week 6/1 stages
could work like how you choose a stage in the chart editor

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
There is no point in doing this and read #211

**Comment by creeperkidking** [comment]
oh ok
