### ISSUE TITLE
About Custom Fonts...

### ISSUE THREAD

**Issue by Draconic-Hybrid** [ShadowMario/FNF-PsychEngine#8205]
### What is your question?

So we know that the font's .ttf files need to be put in the font folder to use them, but what about fonts that are either extremely common or come with the computer such as Times New Roman or Papyrus? Do we need .ttf files for those as well?

**Comment by AetherLynx** [comment]
yes

**Comment by Tailsic111** [comment]
Yeah, we do. Any font's .ttf file, coming packaged with the computer or not, must be in the fonts folder to use. Fortunately, you can just go into the fonts folder and copy the .ttf file of the pre-packaged font you want to use and paste it into the fonts folder. It shouldn't mess with the fonts in the fonts folder.

**Comment by Draconic-Hybrid** [comment]
Cool! Thanks.
