### ISSUE TITLE
How to doTweenAlpha on healthBar (Lua)

### ISSUE THREAD

**Issue by SAB236YT** [ShadowMario/FNF-PsychEngine#8206]
### How to doTweenAlpha on healthBar (Lua)

uh can i have healthbar lua name or just the code pls

**Comment by frantastic24** [comment]
It's in your title

**Comment by SAB236YT** [comment]
i already tried it doeas not work

**Comment by SAB236YT** [comment]
doTweenAlpha('mehthisugly','healthBar', 1, 2.2, 'linear')

**Comment by frantastic24** [comment]
An alpha of 1 means it's fully visible

**Comment by SAB236YT** [comment]
but is bc i put in a curBeat

**Comment by frantastic24** [comment]
???

**Comment by MaybeMaru** [comment]
> but is bc i put in a curBeat

tf

**Comment by SAB236YT** [comment]
1.`doTweenAlpha('WHATNOHEALTH?','healthBar', 0, 0.1, 'linear')`

2.`if curBeat == 12 then
        doTweenAlpha('mehthisugly','healthBar', 1, 2.2, 'linear')
    end`

**Comment by frantastic24** [comment]
Show the full script, preferably in proper code block

**Comment by SAB236YT** [comment]
function onBeatHit()

    if curBeat == 4 then
	    doTweenAlpha('okfine','bg', 1, 2.2, 'linear')
		doTweenAlpha('mehthisugly','healthBar', 1, 2.2, 'linear')
		noteTweenAlpha('bro<:(', 4, 1, 4.6, 'linear')
	    noteTweenAlpha('what', 5, 1, 4.6, 'linear')
	    noteTweenAlpha('is this??', 6, 1, 4.6, 'linear')
	    noteTweenAlpha('AAAAAA', 7, 1, 4.6, 'linear')
		
    end
	
	if curBeat == 12 then
        doTweenAlpha('mehthisugly','healthBar', 1, 2.2, 'linear')
    end
end

here 

or 
[whit.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8514766/whit.txt)
stage lua

**Comment by frantastic24** [comment]
Why do both tweens set the alpha to 1

**Comment by SAB236YT** [comment]
nvm i found a way outta this
