### ISSUE TITLE
screen fade event plz

### ISSUE THREAD

**Issue by GlithModder** [ShadowMario/FNF-PsychEngine#8209]
### What needs to be documented?

screen fade event plz??

**Comment by Draconic-Hybrid** [comment]
Do you mean something like a fade to black? You can just set up a Lua Sprite for that. Make a huge black block, set the camera to "other" so that it'll be placed in front of the hud, set the Alpha Tween to 0, add it, and whenever you need to, Tween it to 1.

**Comment by frantastic24** [comment]
[Read the fucking wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#camerafadecamerastring-colorstring-durationfloatforcedbool)

**Comment by GlithModder** [comment]
> [Read the fucking wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#camerafadecamerastring-colorstring-durationfloatforcedbool)


i don't know how to use it

**Comment by frantastic24** [comment]
The wiki is literally explaining it and even has example scripts that show general Lua syntax

**Comment by GlithModder** [comment]
> The wiki is literally explaining it and even has example scripts that show general Lua syntax

I just don't understand, so I'm asking for help and if possible an event

**Comment by frantastic24** [comment]
Have you tried using the search feature since there are post with scripts that do this already

**Comment by NonCanonBF** [comment]
@GlithModder use this

`function onCreate()
    cameraFlash(game, 'ffffff', 0.5, false)
end`

To explain this, the onCreate() will make the fade start at the start of the countdown, if you want to make it go at a specific time, use this instead.

`function onStepHit()
    if curStep == (step the flash will happen) then
        cameraFade(game, 'ffffff', 0.5,false)
    end
end`
