### ISSUE TITLE
I NEED HELP WITH LUA

### ISSUE THREAD

**Issue by Sebasyn0se** [ShadowMario/FNF-PsychEngine#821]
### Describe your problem here.

What i wrote bad? i mean, is a problem in the code because i added the sprites and xml files in the game, if i try adding a normal luasprite, it works, but if i try with a animatedluasprite, the game gives me errors lol

![test-ddlc-bg lua - Visual Studio Code 04_11_2021 23_03_06](https://user-images.githubusercontent.com/93066244/140446046-98c5b099-f079-47f1-9d35-fc694279289a.png)
![Friday Night Funkin'_ Psych Engine 04_11_2021 23_03_14](https://user-images.githubusercontent.com/93066244/140446055-ebcd3cd1-a5a9-45a0-a8f0-e81938829715.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

**Comment by KutikiPlayz** [comment]
in the addAnimationByPrefix, try removing all the stuff like tag:String and just have it like 

addAnimationByPrefix('yuri', 'Yuri BG', 'Yuri BG', 24, true)
