### ISSUE TITLE
Compile issue... again.

### ISSUE THREAD

**Issue by Draconic-Hybrid** [ShadowMario/FNF-PsychEngine#8211]
### Describe your bug here.

So I had all those warnings last time, and people said it was fine. But now I have this and I'm not sure what to make of it

### Command Prompt/Terminal logs (if existing)

```bash
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Achievements and PlayState to add achievements

**Comment by TechHopGitHub** [comment]
Oof, same with me here, and i don't know how to solve it...

**Comment by TechHopGitHub** [comment]
Just got it!

Install these things in Visual Studio Installer:
MSVC v142 - VS 2019 C++ x64/x86 build tools
Windows SDK (10.0.17763.0)

then try compiling.

**Comment by TechHopGitHub** [comment]
Oh, they are in the visual studio installer. download the visual studio 2019 community build (https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=community&rel=16&utm_medium=microsoft&utm_source=docs.microsoft.com&utm_campaign=download+from+relnotes&utm_content=vs2019ga+button) and search those in the extentions, or build tools tab. it installs 5gb of crap, but it is neccesary.

**Comment by Draconic-Hybrid** [comment]
Thanks!

**Comment by TechHopGitHub** [comment]
> Thanks!

Your welcome!
