### ISSUE TITLE
Tweening problems

### ISSUE THREAD

**Issue by LEON-BROTHER** [ShadowMario/FNF-PsychEngine#8212]
### Describe your problem here.

So I tried to tween a object and it worked.
But then I noticed it only works once and idk why 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Tweens set values, not add to them
Use a formula

**Comment by LEON-BROTHER** [comment]
> Tweens set values, not add to them Use a formula
Oh ok thanks

**Comment by frantastic24** [comment]
You can close this

**Comment by LEON-BROTHER** [comment]
Still doesn't work could you give me an example to tween something to idk x = 100 then bring it back to x = 0 and again to x = 100 again.
With doTweenX

**Comment by frantastic24** [comment]
This is one way to do it
```lua
function onSongStart()
     doTweenX('tween', 'tag', 100, 1)
end

function onTweenCompleted(tag)
     if tag == 'tween' then
          if getProperty('tag.x') == 100 then
               doTweenX('tween', 'tag', 0, 1)
           else
               doTweenX('tween', 'tag', 100, 1)
          end
     end
end
```

**Comment by LEON-BROTHER** [comment]
Yes it worked thanks!
