### ISSUE TITLE
4 dodging animations in Bullet_Note lua

### ISSUE THREAD

**Issue by BlankHuh** [ShadowMario/FNF-PsychEngine#8213]
### What is your question?

hey guys, how do i added 4 dodging animations for bf in Bullet_Note Lua file, like 4 dodging animations in d-side

**Comment by Draconic-Hybrid** [comment]
The four dodging animations require a different character .json entirely.
Once you have that, use this:

Replace boyfriendName with what you've named the respective character file to.
```
local dodgeAnims = {"dodgeLEFT", "dodgeDOWN", "dodgeUP", "dodgeRIGHT"}
function goodNoteHit(id, direction, noteType, isSustainNote)
	if noteType == 'Bullet_Note' then
		if boyfriendName == 'bf-accelerant' then
			characterPlayAnim('boyfriend', dodgeAnims[direction + 1], true);
		else
			characterPlayAnim('boyfriend', 'dodge', true);
		end
		setProperty('boyfriend.specialAnim', true);
        end
end
```
