### ISSUE TITLE
How do i crash the entire game in lua

### ISSUE THREAD

**Issue by pasta870** [ShadowMario/FNF-PsychEngine#8215]
### What is your question?

i need code for it for anti cheat

**Comment by MaybeMaru** [comment]
you know you could just use the end song function or setting the health to low numbers right

**Comment by silvashp** [comment]
> you know you could just use the end song function or setting the health to low numbers right

nah crashing the game is way flashier and cooler

**Comment by ManMaster707** [comment]
I think you can use:

`setProperty('dad', 'nkjkkjfjk')`-- that value doesn't exist so it crashes the game

(bear in mind that the crash that this causes is slow)

**Comment by pasta870** [comment]
dont work

**Comment by frantastic24** [comment]
skill issue, it works

**Comment by BoagerEpic301** [comment]
weirdest ive heard someone say skill issue before

**Comment by ItzDoggoDev** [comment]
makeAnimatedLuaSprite('crashgame','num0', -1000, -1000)
