### ISSUE TITLE
Why do my lua scripts suddenly end?

### ISSUE THREAD

**Issue by xenkap** [ShadowMario/FNF-PsychEngine#8216]
### What is your question?

My lua script runs for a while before abruptly ending. No idea why, didn't put a close() anywhere. Help

**Comment by MaybeMaru** [comment]
share the script lmao

**Comment by xenkap** [comment]
i split the script into 2 parts (one in custom_notetypes like where it should be and one in scripts) as a solution. here's the script though
[snowball - Copy.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8519492/snowball.-.Copy.txt)

**Comment by ShadowMario** [comment]
It was a memory leak on lua, it's fixed now
