### ISSUE TITLE
Noteskin is broken

### ISSUE THREAD

**Issue by pasta870** [ShadowMario/FNF-PsychEngine#8219]
### Describe your bug here.

![Screenshot_20220419-174012](https://user-images.githubusercontent.com/96292419/163976182-edb1cad5-760f-4111-ba5f-183029c57f46.jpg)
I was gonna make a "downscroll but upscroll" note skin but i got this

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Wrong XML animations

**Comment by pasta870** [comment]
``xml
<TextureAtlas imagePath="game.png" width="2048" height="2048">
<SubTexture name="down confirm0" x="0" y="0" width="170" height="207" frameX="-0" frameY="-393" frameWidth="170" frameHeight="600"/>
<SubTexture name="down confirm1" x="170" y="0" width="170" height="206" frameX="-0" frameY="-394" frameWidth="170" frameHeight="600"/>
<SubTexture name="right confirm0" x="170" y="206" width="170" height="206" frameX="-0" frameY="-394" frameWidth="170" frameHeight="600"/>
<SubTexture name="left confirm1" x="0" y="207" width="170" height="201" frameX="-0" frameY="-399" frameWidth="170" frameHeight="600"/>
<SubTexture name="right confirm2" x="340" y="0" width="170" height="201" frameX="-0" frameY="-399" frameWidth="170" frameHeight="600"/>
<SubTexture name="up confirm2" x="340" y="201" width="170" height="201" frameX="-0" frameY="-399" frameWidth="170" frameHeight="600"/>
<SubTexture name="up confirm1" x="0" y="408" width="170" height="200" frameX="-0" frameY="-400" frameWidth="170" frameHeight="600"/>
<SubTexture name="left confirm0" x="340" y="402" width="170" height="197" frameX="-0" frameY="-403" frameWidth="170" frameHeight="600"/>
<SubTexture name="up confirm0" x="170" y="412" width="170" height="184" frameX="-0" frameY="-416" frameWidth="170" frameHeight="600"/>
<SubTexture name="arrowDOWN" x="510" y="0" width="158" height="154" frameX="-9" frameY="-440" frameWidth="170" frameHeight="600"/>
<SubTexture name="arrowUP" x="510" y="154" width="158" height="154" frameX="-5" frameY="-442" frameWidth="170" frameHeight="600"/>
<SubTexture name="blue0" x="510" y="308" width="158" height="154" frameX="-0" frameY="-0" frameWidth="158" frameHeight="154"/>
<SubTexture name="green0" x="510" y="462" width="158" height="154" frameX="-0" frameY="-0" frameWidth="158" frameHeight="154"/>
<SubTexture name="arrowLEFT" x="0" y="608" width="154" height="157" frameX="-6" frameY="-442" frameWidth="170" frameHeight="600"/>
<SubTexture name="arrowRIGHT" x="154" y="608" width="154" height="157" frameX="-10" frameY="-440" frameWidth="170" frameHeight="600"/>
<SubTexture name="purple0" x="308" y="599" width="154" height="157" frameX="-0" frameY="-0" frameWidth="154" frameHeight="157"/>
<SubTexture name="red0" x="668" y="0" width="156" height="157" frameX="-0" frameY="-0" frameWidth="156" frameHeight="157"/>
<SubTexture name="up press1" x="462" y="616" width="154" height="150" frameX="-5" frameY="-433" frameWidth="170" frameHeight="600"/>
<SubTexture name="right press0" x="616" y="616" width="149" height="151" frameX="-11" frameY="-435" frameWidth="170" frameHeight="600"/>
<SubTexture name="right press1" x="668" y="157" width="149" height="151" frameX="-11" frameY="-432" frameWidth="170" frameHeight="600"/>
<SubTexture name="down press0" x="668" y="308" width="150" height="146" frameX="-9" frameY="-438" frameWidth="170" frameHeight="600"/>
<SubTexture name="left press1" x="668" y="454" width="147" height="149" frameX="-6" frameY="-436" frameWidth="170" frameHeight="600"/>
<SubTexture name="up press0" x="0" y="767" width="145" height="141" frameX="-9" frameY="-441" frameWidth="170" frameHeight="600"/>
<SubTexture name="down press1" x="145" y="767" width="143" height="139" frameX="-13" frameY="-441" frameWidth="170" frameHeight="600"/>
<SubTexture name="left press0" x="288" y="766" width="140" height="142" frameX="-12" frameY="-441" frameWidth="170" frameHeight="600"/>
<SubTexture name="green hold end0" x="765" y="603" width="51" height="66" frameX="-0" frameY="-0" frameWidth="51" frameHeight="66"/>
<SubTexture name="blue hold end0" x="765" y="669" width="51" height="65" frameX="-0" frameY="-0" frameWidth="51" frameHeight="65"/>
<SubTexture name="purple hold end0" x="765" y="734" width="51" height="65" frameX="-0" frameY="-0" frameWidth="51" frameHeight="65"/>
<SubTexture name="red hold end0" x="428" y="799" width="52" height="65" frameX="-0" frameY="-0" frameWidth="52" frameHeight="65"/>
<SubTexture name="red hold piece0" x="480" y="799" width="52" height="45" frameX="-0" frameY="-0" frameWidth="52" frameHeight="45"/>
<SubTexture name="blue hold piece" x="480" y="844" width="51" height="45" frameX="-0" frameY="-0" frameWidth="51" frameHeight="45"/>
<SubTexture name="green hold piece0" x="531" y="844" width="51" height="45" frameX="-0" frameY="-0" frameWidth="51" frameHeight="45"/>
<SubTexture name="purple hold piece0" x="532" y="799" width="51" height="45" frameX="-0" frameY="-0" frameWidth="51" frameHeight="45"/>
<SubTexture name="right confirm1" x="170" y="206" width="170" height="206" frameX="-0" frameY="-394" frameWidth="170" frameHeight="600"/>
</TextureAtlas>

**Comment by pasta870** [comment]
<TextureAtlas imagePath="game.png" width="2048" height="2048">
<SubTexture name="down confirm0" x="0" y="0" width="170" height="207" frameX="-0" frameY="-393" frameWidth="170" frameHeight="600"/>
<SubTexture name="down confirm1" x="170" y="0" width="170" height="206" frameX="-0" frameY="-394" frameWidth="170" frameHeight="600"/>
<SubTexture name="right confirm0" x="170" y="206" width="170" height="206" frameX="-0" frameY="-394" frameWidth="170" frameHeight="600"/>
<SubTexture name="left confirm1" x="0" y="207" width="170" height="201" frameX="-0" frameY="-399" frameWidth="170" frameHeight="600"/>
<SubTexture name="right confirm2" x="340" y="0" width="170" height="201" frameX="-0" frameY="-399" frameWidth="170" frameHeight="600"/>
<SubTexture name="up confirm2" x="340" y="201" width="170" height="201" frameX="-0" frameY="-399" frameWidth="170" frameHeight="600"/>
<SubTexture name="up confirm1" x="0" y="408" width="170" height="200" frameX="-0" frameY="-400" frameWidth="170" frameHeight="600"/>
<SubTexture name="left confirm0" x="340" y="402" width="170" height="197" frameX="-0" frameY="-403" frameWidth="170" frameHeight="600"/>
<SubTexture name="up confirm0" x="170" y="412" width="170" height="184" frameX="-0" frameY="-416" frameWidth="170" frameHeight="600"/>
<SubTexture name="arrowDOWN" x="510" y="0" width="158" height="154" frameX="-9" frameY="-440" frameWidth="170" frameHeight="600"/>
<SubTexture name="arrowUP" x="510" y="154" width="158" height="154" frameX="-5" frameY="-442" frameWidth="170" frameHeight="600"/>
<SubTexture name="blue0" x="510" y="308" width="158" height="154" frameX="-0" frameY="-0" frameWidth="158" frameHeight="154"/>
<SubTexture name="green0" x="510" y="462" width="158" height="154" frameX="-0" frameY="-0" frameWidth="158" frameHeight="154"/>
<SubTexture name="arrowLEFT" x="0" y="608" width="154" height="157" frameX="-6" frameY="-442" frameWidth="170" frameHeight="600"/>
<SubTexture name="arrowRIGHT" x="154" y="608" width="154" height="157" frameX="-10" frameY="-440" frameWidth="170" frameHeight="600"/>
<SubTexture name="purple0" x="308" y="599" width="154" height="157" frameX="-0" frameY="-0" frameWidth="154" frameHeight="157"/>
<SubTexture name="red0" x="668" y="0" width="156" height="157" frameX="-0" frameY="-0" frameWidth="156" frameHeight="157"/>
<SubTexture name="up press1" x="462" y="616" width="154" height="150" frameX="-5" frameY="-433" frameWidth="170" frameHeight="600"/>
<SubTexture name="right press0" x="616" y="616" width="149" height="151" frameX="-11" frameY="-435" frameWidth="170" frameHeight="600"/>
<SubTexture name="right press1" x="668" y="157" width="149" height="151" frameX="-11" frameY="-432" frameWidth="170" frameHeight="600"/>
<SubTexture name="down press0" x="668" y="308" width="150" height="146" frameX="-9" frameY="-438" frameWidth="170" frameHeight="600"/>
<SubTexture name="left press1" x="668" y="454" width="147" height="149" frameX="-6" frameY="-436" frameWidth="170" frameHeight="600"/>
<SubTexture name="up press0" x="0" y="767" width="145" height="141" frameX="-9" frameY="-441" frameWidth="170" frameHeight="600"/>
<SubTexture name="down press1" x="145" y="767" width="143" height="139" frameX="-13" frameY="-441" frameWidth="170" frameHeight="600"/>
<SubTexture name="left press0" x="288" y="766" width="140" height="142" frameX="-12" frameY="-441" frameWidth="170" frameHeight="600"/>
<SubTexture name="green hold end0" x="765" y="603" width="51" height="66" frameX="-0" frameY="-0" frameWidth="51" frameHeight="66"/>
<SubTexture name="blue hold end0" x="765" y="669" width="51" height="65" frameX="-0" frameY="-0" frameWidth="51" frameHeight="65"/>
<SubTexture name="purple hold end0" x="765" y="734" width="51" height="65" frameX="-0" frameY="-0" frameWidth="51" frameHeight="65"/>
<SubTexture name="red hold end0" x="428" y="799" width="52" height="65" frameX="-0" frameY="-0" frameWidth="52" frameHeight="65"/>
<SubTexture name="red hold piece0" x="480" y="799" width="52" height="45" frameX="-0" frameY="-0" frameWidth="52" frameHeight="45"/>
<SubTexture name="blue hold piece" x="480" y="844" width="51" height="45" frameX="-0" frameY="-0" frameWidth="51" frameHeight="45"/>
<SubTexture name="green hold piece0" x="531" y="844" width="51" height="45" frameX="-0" frameY="-0" frameWidth="51" frameHeight="45"/>
<SubTexture name="purple hold piece0" x="532" y="799" width="51" height="45" frameX="-0" frameY="-0" frameWidth="51" frameHeight="45"/>
<SubTexture name="right confirm1" x="170" y="206" width="170" height="206" frameX="-0" frameY="-394" frameWidth="170" frameHeight="600"/>
</TextureAtlas>

**Comment by frantastic24** [comment]
What

**Comment by pasta870** [comment]
wait

**Comment by pasta870** [comment]
<TextureAtlas imagePath="game.png" width="2048" height="2048">

<SubTexture name="down confirm0" x="0" y="0" width="170" height="207" frameX="-0" frameY="-393" frameWidth="170" frameHeight="600"/>

<SubTexture name="down confirm1" x="170" y="0" width="170" height="206" frameX="-0" frameY="-394" frameWidth="170" frameHeight="600"/>

<SubTexture name="right confirm0" x="170" y="206" width="170" height="206" frameX="-0" frameY="-394" frameWidth="170" frameHeight="600"/>

<SubTexture name="left confirm1" x="0" y="207" width="170" height="201" frameX="-0" frameY="-399" frameWidth="170" frameHeight="600"/>

<SubTexture name="right confirm2" x="340" y="0" width="170" height="201" frameX="-0" frameY="-399" frameWidth="170" frameHeight="600"/>

<SubTexture name="up confirm2" x="340" y="201" width="170" height="201" frameX="-0" frameY="-399" frameWidth="170" frameHeight="600"/>

<SubTexture name="up confirm1" x="0" y="408" width="170" height="200" frameX="-0" frameY="-400" frameWidth="170" frameHeight="600"/>

<SubTexture name="left confirm0" x="340" y="402" width="170" height="197" frameX="-0" frameY="-403" frameWidth="170" frameHeight="600"/>

<SubTexture name="up confirm0" x="170" y="412" width="170" height="184" frameX="-0" frameY="-416" frameWidth="170" frameHeight="600"/>

<SubTexture name="arrowDOWN" x="510" y="0" width="158" height="154" frameX="-9" frameY="-440" frameWidth="170" frameHeight="600"/>

<SubTexture name="arrowUP" x="510" y="154" width="158" height="154" frameX="-5" frameY="-442" frameWidth="170" frameHeight="600"/>

<SubTexture name="blue0" x="510" y="308" width="158" height="154" frameX="-0" frameY="-0" frameWidth="158" frameHeight="154"/>

<SubTexture name="green0" x="510" y="462" width="158" height="154" frameX="-0" frameY="-0" frameWidth="158" frameHeight="154"/>

<SubTexture name="arrowLEFT" x="0" y="608" width="154" height="157" frameX="-6" frameY="-442" frameWidth="170" frameHeight="600"/>

<SubTexture name="arrowRIGHT" x="154" y="608" width="154" height="157" frameX="-10" frameY="-440" frameWidth="170" frameHeight="600"/>

<SubTexture name="purple0" x="308" y="599" width="154" height="157" frameX="-0" frameY="-0" frameWidth="154" frameHeight="157"/>

<SubTexture name="red0" x="668" y="0" width="156" height="157" frameX="-0" frameY="-0" frameWidth="156" frameHeight="157"/>

<SubTexture name="up press1" x="462" y="616" width="154" height="150" frameX="-5" frameY="-433" frameWidth="170" frameHeight="600"/>

<SubTexture name="right press0" x="616" y="616" width="149" height="151" frameX="-11" frameY="-435" frameWidth="170" frameHeight="600"/>

<SubTexture name="right press1" x="668" y="157" width="149" height="151" frameX="-11" frameY="-432" frameWidth="170" frameHeight="600"/>

<SubTexture name="down press0" x="668" y="308" width="150" height="146" frameX="-9" frameY="-438" frameWidth="170" frameHeight="600"/>

<SubTexture name="left press1" x="668" y="454" width="147" height="149" frameX="-6" frameY="-436" frameWidth="170" frameHeight="600"/>

<SubTexture name="up press0" x="0" y="767" width="145" height="141" frameX="-9" frameY="-441" frameWidth="170" frameHeight="600"/>

<SubTexture name="down press1" x="145" y="767" width="143" height="139" frameX="-13" frameY="-441" frameWidth="170" frameHeight="600"/>

<SubTexture name="left press0" x="288" y="766" width="140" height="142" frameX="-12" frameY="-441" frameWidth="170" frameHeight="600"/>

<SubTexture name="green hold end0" x="765" y="603" width="51" height="66" frameX="-0" frameY="-0" frameWidth="51" frameHeight="66"/>

<SubTexture name="blue hold end0" x="765" y="669" width="51" height="65" frameX="-0" frameY="-0" frameWidth="51" frameHeight="65"/>

<SubTexture name="purple hold end0" x="765" y="734" width="51" height="65" frameX="-0" frameY="-0" frameWidth="51" frameHeight="65"/>

<SubTexture name="red hold end0" x="428" y="799" width="52" height="65" frameX="-0" frameY="-0" frameWidth="52" frameHeight="65"/>

<SubTexture name="red hold piece0" x="480" y="799" width="52" height="45" frameX="-0" frameY="-0" frameWidth="52" frameHeight="45"/>

<SubTexture name="blue hold piece" x="480" y="844" width="51" height="45" frameX="-0" frameY="-0" frameWidth="51" frameHeight="45"/>

<SubTexture name="green hold piece0" x="531" y="844" width="51" height="45" frameX="-0" frameY="-0" frameWidth="51" frameHeight="45"/>

<SubTexture name="purple hold piece0" x="532" y="799" width="51" height="45" frameX="-0" frameY="-0" frameWidth="51" frameHeight="45"/>

<SubTexture name="right confirm1" x="170" y="206" width="170" height="206" frameX="-0" frameY="-394" frameWidth="170" frameHeight="600"/>

</TextureAtlas>

**Comment by pasta870** [comment]
this is my xml

**Comment by frantastic24** [comment]
i don't see anything wrong with it, can you send the xml and png on a zip? this isn't a bug but just want to test it properly

**Comment by pasta870** [comment]
https://drive.google.com/file/d/1bdVEbvVF6naAnOfPlBiOjkEsF3FkvrYT/view?usp=drivesdk

**Comment by frantastic24** [comment]
upload it directly

**Comment by pasta870** [comment]
i have no idea how

**Comment by frantastic24** [comment]
reading moment
![image](https://user-images.githubusercontent.com/95725102/164115997-87d6bf32-42a6-4a52-aee0-f2930fb7920f.png)

**Comment by pasta870** [comment]
[nerd.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8516967/nerd.zip)
they hate winrar

**Comment by frantastic24** [comment]
yeah it's a problem with your xml, the `frameY` value on a lot of these is pushing the texture out of bounds
there's also an issue with the purple hold end, the animation should be called `pruple end hold`

**Comment by AetherLynx** [comment]
> yeah it's a problem with your xml, the `frameY` value on a lot of these is pushing the texture out of bounds there's also an issue with the purple hold end, the animation should be called `pruple end hold`

i hate that typo lol

**Comment by pasta870** [comment]
> yeah it's a problem with your xml, the `frameY` value on a lot of these is pushing the texture out of bounds there's also an issue with the purple hold end, the animation should be called `pruple end hold`

it was intentionally on the middle

also it still wont work

**Comment by frantastic24** [comment]
it worked for me after deleting those lines, so try again

**Comment by pasta870** [comment]
what lines

**Comment by pasta870** [comment]
https://user-images.githubusercontent.com/96292419/164132816-442aacf2-5d3a-4549-9337-d3faa6a6c1d0.mp4

**Comment by pasta870** [comment]
misclick

**Comment by frantastic24** [comment]
frameY as I literally mentioned above, and you do know you can set strum positions without using a messy XML right?

**Comment by frantastic24** [comment]
you shoud close this

**Comment by frantastic24** [comment]
you should close this
