### ISSUE TITLE
Stage Variables

### ISSUE THREAD

**Issue by AdmiralUsername** [ShadowMario/FNF-PsychEngine#8220]
### Describe your problem here.

How do you find if a song's stage is a pixel stage in a lua script?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nah

**Comment by AetherLynx** [comment]
```lua
getProperty('isPixelStage')
```

**Comment by frantastic24** [comment]
```lua
getPropertyFromClass('PlayState','isPixelStage')
```
