### ISSUE TITLE
While/for i in loops in lua scripts

### ISSUE THREAD

**Issue by PerlIsMe** [ShadowMario/FNF-PsychEngine#8221]
### Describe your problem here.

is there a way to safely input a loop in a callback without breaking/crashing the game? if so,
say

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by PrismLight** [comment]
This will make the script repeat four times, setting i to whatever loop it's on. For this instance, 0, 1, 2 and 3.
```lua
for i=0..3 do
    --script
end
```
The same thing would be with this, except going through 2, 3, 4 and 5.
```lua
for i=2..5 do
    --script
end
```
Hope this helps.

**Comment by tylerandari12** [comment]
so its not a comma?

`for i=2, 5 do
    --script
end`

**Comment by Lorekeeper49** [comment]
> so its not a comma?
> 
> `for i=2, 5 do
>     --script
> end`

It _is_ a comma, you are just missing a number, here's an example
> for i=0,1,3 do
>     --script
> end
