### ISSUE TITLE
Waiting in lua scripts

### ISSUE THREAD

**Issue by PerlIsMe** [ShadowMario/FNF-PsychEngine#8222]
### Describe your problem here.

How do I wait in lua? I want to make a lua sprite play an animation, then wait for it to be complete, so I either want to do a wait, or a way to play an animation then wait for it to complete.

:plea

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
`runTimer()` or

```lua
function onUpdatePost()
     if getProperty('tag.animation.curAnim.finished') and getProperty('tag.animation.curAnim.name') == 'animName' then
          
     end
end
```
