### ISSUE TITLE
How do i make a mechanic. where a character covers the screen. to make him go away you need to press a note?

### ISSUE THREAD

**Issue by JacksRobotics** [ShadowMario/FNF-PsychEngine#8224]
### What is your question?

im making a mod called vs grunkfuss. on psych engine 0.5.2h and i want to add a mechanic. where birthday boy blam covers up the screen. to make him go away press a gray note. And no. im not using lua. Im useing source code

**Comment by Steve35117** [comment]
`function onEvent(name, value1, value2)
	if name == "Boopsie" then
		makeLuaSprite('jiafeiProducts', value1, 0, 0)
		screenCenter('jiafeiProducts', 'XY')
		setObjectCamera('jiafeiProducts', 'camHUD')--or camgame or camother idc asdfgh
		playSound(value2, 187)
		addLuaSprite('jiafeiProducts', true)
	end
end

function onUpdate(noteType)
	if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SIX') then -- put whatever you want(type your key on uppercase)
		doTweenAlpha('cupcakke', 'jiafeiProducts', 0, 1, 'linear')
	end
        if noteType == 'graynote' then
              doTweenAlpha('cupcakke', 'jiafeiProducts', 0, 1, 'linear')
        end
end

function onTweenCompleted(tag) -- reduce lag
    if tag == 'cupcakke' then
		removeLuaSprite('jiafeiProducts')
	end
end`

**Comment by Steve35117** [comment]
> `function onEvent(name, value1, value2) if name == "Boopsie" then makeLuaSprite('jiafeiProducts', value1, 0, 0) screenCenter('jiafeiProducts', 'XY') setObjectCamera('jiafeiProducts', 'camHUD')--or camgame or camother idc asdfgh playSound(value2, 187) addLuaSprite('jiafeiProducts', true) end end
> 
> function onUpdate(noteType) if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SIX') then -- put whatever you want(type your key on uppercase) doTweenAlpha('cupcakke', 'jiafeiProducts', 0, 1, 'linear') end if noteType == 'graynote' then doTweenAlpha('cupcakke', 'jiafeiProducts', 0, 1, 'linear') end end
> 
> function onTweenCompleted(tag) -- reduce lag if tag == 'cupcakke' then removeLuaSprite('jiafeiProducts') end end`

btw value 2 is optional

**Comment by JacksRobotics** [comment]
thankss

**Comment by JacksRobotics** [comment]
also where do i put this code? in mods folder?

**Comment by Steve35117** [comment]
since its an event, yes (on custom_events), also you could put it on your
song but replace the onEvent with onStepHit
and the if name thing with if curstep == ex.1

Am Di., 19. Apr. 2022 um 16:38 Uhr schrieb Jacks Robotics <
***@***.***>:

**Comment by Steve35117** [comment]
> `function onEvent(name, value1, value2) if name == "Boopsie" then makeLuaSprite('jiafeiProducts', value1, 0, 0) screenCenter('jiafeiProducts', 'XY') setObjectCamera('jiafeiProducts', 'camHUD')--or camgame or camother idc asdfgh playSound(value2, 187) addLuaSprite('jiafeiProducts', true) end end
> 
> function onUpdate(noteType) if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SIX') then -- put whatever you want(type your key on uppercase) doTweenAlpha('cupcakke', 'jiafeiProducts', 0, 1, 'linear') end if noteType == 'graynote' then doTweenAlpha('cupcakke', 'jiafeiProducts', 0, 1, 'linear') end end
> 
> function onTweenCompleted(tag) -- reduce lag if tag == 'cupcakke' then removeLuaSprite('jiafeiProducts') end end`

`function makeShit() {
	jiafeiProducts = new FlxSprite().loadGraphic(Paths.image(image path or value1 if its an event));
	jiafeiProducts.screenCenter();
	jiafeiProducts.cameras = [camHUD]; //or camgame or camother idc asdfgh
	FlxG.sound.play(Paths.sound(sound Path or value2), 187);
	add(jiafeiProducts);
}

function goodNoteHit() {
	if (note.noteType == 'graynote'){
		FlxTween.tween(jiafeiProducts, {alpha: 0}, 1, {ease:FlxEase.sineOut, 
			onComplete: function(twn:FlxTween) {
				remove(jiafeiProducts); // reduce lag
			}
		});
	}
}

function update(elapsed) {
	if (FlxG.keys.justPressed.SIX) { // put whatever you want(type your key on uppercase)
		FlxTween.tween(jiafeiProducts, {alpha: 0}, 1, {ease:FlxEase.sineOut, 
			onComplete: function(twn:FlxTween) {
				remove(jiafeiProducts); // reduce lag
			}
		});
	}
	if(SONG.song.toLowerCase() == 'song'// && FlxG.random.bool(50)) {
		makeShit();
		/* switch(curStep/beat) {
			case 5:
				makeShit();
		}
	}
}`

Ive realized its on source. if anything is wrong, tell me

**Comment by JacksRobotics** [comment]
thanks so much for the code. your a awsome guy!

**Comment by JacksRobotics** [comment]
hey when i test the game and put the event. it says Mods/Custom_events/BBB Mechanic.lua1: unexpected symbol near

**Comment by JacksRobotics** [comment]
anyway to fix this?
