### ISSUE TITLE
not a duplicate of the loading screen issue

### ISSUE THREAD

**Issue by RedMik52** [ShadowMario/FNF-PsychEngine#8226]
### Describe your problem here.

I've written an issue about how to add loading screen to song and it was closed because it was a duplicate of #1728.
so, i followed the issue solution but now songs don't load anymore, they just remain in a loading state forever.
(i know that it isn't my pc because i left fnf open for 2-3 hours and it was still blocked) I built in 0.5.2h

Please help me.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
It's literally useless to have a loading screen on desktop, a loading screen is used for downloading assets on HTML5.

**Comment by Randomxdp** [comment]
> It's literally useless to have a loading screen on desktop, a loading screen is used for downloading assets on HTML5.

It can be usefull to load songs with large sprites and heavy stuff , it also gives you something to look at instead of a dark screen
