### ISSUE TITLE
Accuracy 1-100

### ISSUE THREAD

**Issue by SpookyMan16** [ShadowMario/FNF-PsychEngine#8227]
### Describe your problem here.

How do I get the accuracy from 1 - 100 but there is only 2 decimal places

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Only added a few mods

**Comment by Lorekeeper49** [comment]
That's already in for version 0.5 and onward

**Comment by SpookyMan16** [comment]
> That's already in for version 0.5 and onward

In LUA

**Comment by Lorekeeper49** [comment]
Dude, stop using 0.4.2.  Like I said, that's already in 0.5 and onward, so switch to that please

**Comment by ShadowMario** [comment]
Update your Psych Engine version.
