### ISSUE TITLE
DeathCounter 

### ISSUE THREAD

**Issue by Soeiz** [ShadowMario/FNF-PsychEngine#8229]
### Describe your problem here.

Hey, I have a issue in this Lua script, I want to make like if you have the deathcounter to 0 you have a dialogue, if to 1 you have another dialogue, ect. But when I test it, It soft lock and I cannot do anything ! If someone can help me

```
local allowCountdown = false
function onStartCountdown()
	if not allowCountdown and not seenCutscene then
		death = getProperty('deathCounter');
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		if death == 0 then 
			startDialogue('dialogue', 'breakfast');
		end
		if death == 1 then 
			startDialogue('dialogue1', 'breakfast');
		end
		if death == 2 then 
			startDialogue('dialogue2', 'breakfast');
		end
		if death == 3 then 
			startDialogue('dialogue3', 'breakfast');
		end
	end
end

-- Dialogue (When a dialogue is finished, it calls startCountdown again)
function onNextDialogue(count)
	-- triggered when the next dialogue line starts, 'line' starts with 1
end

function onSkipDialogue(count)
	-- triggered when you press Enter and skip a dialogue line that was still being typed, dialogue line starts with 1
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Steve35117** [comment]
well, you actually got one in the pause menu (Blueballed: Int)

**Comment by Soeiz** [comment]
Yes I know, but I use it like (Blueballed: Int) Or something else ?

**Comment by Steve35117** [comment]
> Yes I know, but I use it like (Blueballed: Int) Or something else ?

well, i cant read. well, you could run the timers on function onGameOver() btw does it play on song or after the blueball sound

**Comment by Soeiz** [comment]
All right lol

**Comment by Lorekeeper49** [comment]
You don't need this, there's literally a death counter in the pause menu

**Comment by Soeiz** [comment]
Yes but how do I have the variable of the death counter ??

**Comment by Soeiz** [comment]
Nevermind, I find this out !

**Comment by WolfyTail** [comment]
HOW?

**Comment by Soeiz** [comment]
You can have the death var by doing that : death = getPropertyFromClass('PlayState', 'deathCounter');
