### ISSUE TITLE
ease out effect

### ISSUE THREAD

**Issue by BlankHuh** [ShadowMario/FNF-PsychEngine#8232]
### What is your question?

how do i add ease out effect in title, menu, week menu, freeplay menu and yea

**Comment by PrismLight** [comment]
`FlxTween.tween`
No way to do it in lua lol.

**Comment by BlankHuh** [comment]
> `FlxTween.tween`
> No way to do it in lua lol.

not in lua, in haxe (source)

**Comment by PrismLight** [comment]
Yea it's using `FlxTween.tween`
Use [this](https://haxeflixel.com/documentation/flxtween/) documentation.
