### ISSUE TITLE
Pressing a key sends you to a different song?

### ISSUE THREAD

**Issue by Wolverin18** [ShadowMario/FNF-PsychEngine#8233]
### What is your question?

I wanted to make a song in which you need to press B on the first song in order to get to it. Unfortunately I have no idea how. Can anyone help me?

**Comment by AetherLynx** [comment]
```lua
function onUpdate()
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.B') then
        loadSong('songname', 2)
    end
end
```
songname is, well, the song name
the 2 is for the difficulty id, it is like this:
0: easy
1: normal
2: hard

**Comment by Wolverin18** [comment]
For some reason this isnt working for me, does this work on the bbpanzu action build?

**Comment by frantastic24** [comment]
im assuming you mean shaders build? no, loadSong was added around a month after bbpanzu was removed from the team

**Comment by Wolverin18** [comment]
ok, then i guess this wont work
