### ISSUE TITLE
Can't change the position of health icons along with scroll factor of characters

### ISSUE THREAD

**Issue by dombomb64** [ShadowMario/FNF-PsychEngine#8234]
### Describe your problem here.

I'm trying to add icon offsets using a global Lua script, but the game won't let me change the position of the icons whether that be with the setProperty function or the doTweenX and doTweenY functions. This is not a duplicate of issue #3488 because when I tried to set the angle of an icon using the setProperty function like an answer suggested, it worked fine. However, as soon as I changed it to set iconP2.x instead of iconP2.angle, it did nothing. Here is my code:

```
function onCreatePost()
	--Initial positions
	iconP1DefaultX = getProperty('iconP1.x');
	iconP2DefaultX = getProperty('iconP2.x');
end

function onUpdatePost(elapsed)
	--Reset offsets to 0
	iconP1X = 0;
	iconP1Y = 0;
	iconP2X = 0;
	iconP2Y = 0;

	if (dadName == 'chaseImpostor') then --Will be expanded to include more characters
		iconP2X = 0;
		iconP2Y = 16;
		--debugPrint(getProperty('iconP2.x')); --When I uncomment this the debug output also acts like nothing is different (The only change happens when the icons bop)
	end

	setProperty('iconP2.x', iconP2DefaultX + iconP2X);
	setProperty('iconP2.x', getProperty('healthBar.y') - 75 + iconP2Y);
	iconP2DefaultX = getProperty('iconP2.x') - iconP2X; --Don't let the icon run away

	--doTweenX('iconP2TweenX', 'iconP2', iconP2DefaultX + iconP2X, 0, 'linear');
	--doTweenY('iconP2TweenY', 'iconP2', getProperty('healthBar.y') - 75 + iconP2Y, 0, 'linear');
end
```

Another similar thing I'm curious about is why I can't change the scroll factor of characters. Here is my code:

```
function onUpdate(elapsed)
	if (gfName == 'mattBgNutshell') then
		setScrollFactor('gf', 1, 1);
	end
end
```

P.S.

If anyone is curious as to why I'm adding icon offsets when I can change the image, changing the image would also affect it on the menu.

Also, I just realized that I could have a different icon for the menu, so that'd be a last resort.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, but I did build it on my end anticipating edits.

**Comment by frantastic24** [comment]
have you considered just using `iconP2.offset.x`

**Comment by dombomb64** [comment]
Frankly, I didn't even know that offset variable existed. XD

As for the character groups, I just tried that now and it doesn't seem to work. Here is my code again:

```
function onCreatePost()
	if (gfName == 'mattBgNutshell') then
		setScrollFactor('gfGroup', 1, 1);
	end
end

function onEvent(name, value1, value2)
	if (name == 'Change Character') then
		if (gfName == 'mattBgNutshell') then
			setScrollFactor('gfGroup', 1, 1);
		end
	end
end
```

(I've tried using onCreate and onCreatePost with no success. I've also added my code to the onEvent function.)

**Comment by dombomb64** [comment]
I've found a workaround. Instead of using `gfName`, I used `getProperty('gf.curCharacter')` and it worked fine.

**Comment by frantastic24** [comment]
Surrounding gfName in `' '` turns it into a string, which is why it's not returning the wanted value
Also gf's default scroll is 0.95 which is almost unnoticeable, are you absolutely sure it's not working

**Comment by frantastic24** [comment]
You don't need to change the scroll when changing characters, and I'm pretty sure the code has been working the whole time since the change is barely noticeable
gfName shouldn't be surrounded by `' '` in debugPrint

**Comment by dombomb64** [comment]
Oops. I didn't mean to put `gfName` in quotes in my comment, but I'm pretty sure it wasn't in quotes in the code before I replaced it. My bad.

Also, I was altering the scroll values to be things other than 1 and 1 to help me point it out, and it didn't work then because the if condition was always false because of `gfName` always being `'gf'`.

Well, it does work now, so that's good enough for me.
