### ISSUE TITLE
gfName returns player3 instead of gfVersion

### ISSUE THREAD

**Issue by frantastic24** [ShadowMario/FNF-PsychEngine#8235]
### Describe your bug here.

`player3` is set to null if `gfVersion` isn't found, which causes `gfName` to return null
instead, gfName should be returning `SONG.gfVersion`
![image](https://user-images.githubusercontent.com/95725102/164127913-bff1c29d-8f6e-4b19-a868-12dd197298b1.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by tylerandari12** [comment]
I was about to say change it but some cant compile source lol....

**Comment by frantastic24** [comment]
I've already changed it myself, it still doesn't mean this is what the code should be doing
And anyone can compile, GitHub literally lets you compile your own fork

**Comment by PrismLight** [comment]
> I've already changed it myself, it still doesn't mean this is what the code should be doing And anyone can compile, GitHub literally lets you compile your own fork

And make a pull request out of it.

**Comment by frantastic24** [comment]
Don't see it PR worthy

**Comment by ShadowMario** [comment]
My bad! This is due to me creating gfName before `gfVersion` was implemented

**Comment by frantastic24** [comment]
Fixed in bea4eb12af5b8b20db2b8ca24ae7a9b698b9a893
