### ISSUE TITLE
GetImageExistence()

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8237]
### What feature do you want to get added on the **base** engine?

I would like a function in Lua that allows you to check if an image exists in the game files.
I was thinking something like a `getImageExistence(image:string)` function.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Steve35117** [comment]
its already there its called if(sprite.exists())

**Comment by tylerandari12** [comment]
> its already there its called if(sprite.exists())

Thanks
