### ISSUE TITLE
I just discovered you can edit GF and Logo colors on the latest build

### ISSUE THREAD

**Issue by Steve35117** [ShadowMario/FNF-PsychEngine#8242]
### Describe your bug here.

https://user-images.githubusercontent.com/95169213/164195199-59c89a0d-bd42-4287-8a34-ea0fe781fb0c.mp4
You just need to hold a or d to switch colors

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ManMaster707** [comment]
hold up this isn't a bug

**Comment by denumu07** [comment]
I don't think that's a Bug.

**Comment by Steve35117** [comment]
Yes i know i thought this was a bug but it wasnt

**Comment by sugodick** [comment]
its a easter egg tf

**Comment by Steve35117** [comment]
thx
