### ISSUE TITLE
Custom events in source code

### ISSUE THREAD

**Issue by enjayar625** [ShadowMario/FNF-PsychEngine#8244]
### What is your question?

How do i make custom events in source code?

**Comment by Stilic** [comment]
look at wiki lol

**Comment by enjayar625** [comment]
Bruh again? 
I literally said how to do it in SOURCE CODE
Its clearly not in the wiki

**Comment by Stilic** [comment]
> Bruh again? I literally said how to do it in SOURCE CODE Its clearly not in the wiki

but it is explained for source also

**Comment by Stilic** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Creating-an-Event#on-the-source-code

**Comment by enjayar625** [comment]
oh
