### ISSUE TITLE
(unknown) : type not found : open.utils.internal.extraparamsmacro,  what to do? with this

### ISSUE THREAD

**Issue by bekon4567** [ShadowMario/FNF-PsychEngine#8245]
### Describe your problem here.

what to do if comes out this 

(unknown) : type not found : open.utils.internal.extraparamsmacro
in "command line"

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Steve35117** [comment]
import open.utils.internal.extraparamsmacro;

**Comment by bekon4567** [comment]
and where should I write it?
