### ISSUE TITLE
How do i edit the dialogue box?

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#8246]
### Describe your problem here.

Can anyone tell me how do i edit the dialogue box like, putting it up or make it bigger, etc.

If anyone can make a Lua about it, it would help a lot.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by DewDrags** [comment]
edit fla images and export sprites, and overwrite in
assets/shared/images,you have to replace the speech_bubble.png
