### ISSUE TITLE
Custom Difficulties

### ISSUE THREAD

**Issue by Shelvsk** [ShadowMario/FNF-PsychEngine#8247]
### Describe your problem here.

how i make custom difficulties without source?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i make a KB Sawblade Event (with Lua)

**Comment by roaring213** [comment]
1. Go to data and rename the suffix (-easy or -hard) to the name of your difficulty (-(difficultyname)).
2. If you are making an actual week that shows up in story mode, then make a .png file for your difficulty.
3. If you don't know how to edit the week manually (from the .json file), then go to the main menu of the game and press 7. This will show options for you to select. Select "Week Editor".
4. Go to the "Other" tab and in the "Difficulties" tab, type in your difficulty name.
5. When you're done editing the week, click on "Save Week" and put the .json file in the `mods/weeks` file.

Once you've followed all these steps, the difficulty should show up. I did this in my Cuphead Indie Cross port and these were my results.
![result 1](https://user-images.githubusercontent.com/80852158/164328860-4677b275-dad0-44a3-94f1-48858ac540a0.PNG)
![result 2](https://user-images.githubusercontent.com/80852158/164328895-55526b9e-57cb-46c0-8185-d26b9841fa5b.PNG)
Hope this helped!

**Comment by Shelvsk** [comment]
i do it, but for some reason this happen:
![image](https://user-images.githubusercontent.com/90064741/164528276-e68e9fdd-b0cb-41ea-96d0-af638a401ccd.png)

**Comment by BlearChipmunk** [comment]
> i do it, i create the .png and put on the week and data file but for some reason this happen: ![image](https://user-images.githubusercontent.com/90064741/164528276-e68e9fdd-b0cb-41ea-96d0-af638a401ccd.png)

your png need to be in  mods/images/menudifficulties

**Comment by Shelvsk** [comment]
Thanks, it's worked
![image](https://user-images.githubusercontent.com/90064741/164753346-d272d3d9-3e08-45b4-ad9b-fba5a64f35ff.png)

**Comment by ShadowMario** [comment]
Tutorials updated.

**Comment by UltraFatBoi** [comment]
> i do it, i create the .png and put on the week and data file but for some reason this happen: ![image](https://user-images.githubusercontent.com/90064741/164528276-e68e9fdd-b0cb-41ea-96d0-af638a401ccd.png)

i cannot escape that haxeflixel image
