### ISSUE TITLE
How do I make custom achievements? (No Source Code)

### ISSUE THREAD

**Issue by DevonSonic** [ShadowMario/FNF-PsychEngine#8248]
### Describe your problem here.

I don't know how to make an achievement :(

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by antoSKRLOL** [comment]
n o

**Comment by HiroMizuki** [comment]
impossible with lua at the moment

**Comment by ShadowMario** [comment]
Duplicate of #6511
