### ISSUE TITLE
section

### ISSUE THREAD

**Issue by Lorekeeper49** [ShadowMario/FNF-PsychEngine#8249]
### What is your question?

what is the lua function that calls each section?

**Comment by DEV-idiotXD** [comment]
i made s cript for this
```lua
function onCreate()
timer = 0

function onBeatHit()
	timer = timer + 1
	if timer%4 = 0 then
		--code idk
	end
end
```

**Comment by DEV-idiotXD** [comment]
there isnt a built in one but the beat hit runs 4 times per beat so just use a mod 4 then execute the code

**Comment by frantastic24** [comment]
what the fuck

```lua
function onBeatHit()
	if curBeat % 4 == 0 then

	end
end
```

**Comment by DEV-idiotXD** [comment]
> what the fuck
> 
> ```lua
> function onBeatHit()
> 	if curBeat % 4 == 0 then
> 
> 	end
> end
> ```

xd i havent coded in over a year now dont judge me

**Comment by Lorekeeper49** [comment]
> what the fuck
> 
> ```lua
> function onBeatHit()
> 	if curBeat % 4 == 0 then
> 
> 	end
> end
> ```

this was my original idea, I just didn't know if mod was different for lua that in javascript (the first programing language I worked with)

**Comment by Steviegt6** [comment]
> > what the fuck
> > ```lua
> > function onBeatHit()
> > 	if curBeat % 4 == 0 then
> > 
> > 	end
> > end
> > ```
> 
> this was my original idea, I just didn't know if mod was different for lua that in javascript (the first programing language I worked with)

It'd be pretty bad if they changed a basic mathematical operator arbitrarily...
