### ISSUE TITLE
Why does `bf.json`  have "0" but  `dad.json` not have "0"?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#825]
### What is your question?

`FNF-PsychEngine-main\export\release\windows\bin\assets\characters\bf.json`

![Snipaste_2021-11-05_20-42-41](https://user-images.githubusercontent.com/13177997/140511933-bd25dfe5-7ce8-4c41-9575-012d8fcd9c7c.png)

`FNF-PsychEngine-main\export\release\windows\bin\assets\characters\dad.json`

![Snipaste_2021-11-05_20-36-27](https://user-images.githubusercontent.com/13177997/140511935-15a3c948-b425-417c-827f-6d10ff59a7e2.png)

Why does `bf.json`  have "0" but  `dad.json` not have "0"?

**Comment by lemz1** [comment]
bf has the 0 because the animation would be buggy
Here's why:
So the left hit animation is BF NOTE LEFT
And the left miss animation is BF NOTE LEFT MISS
if you would have just put in BF NOTE LEFT, instead of BF NOTE LEFT0, it would play both animations.
