### ISSUE TITLE
song isn't working

### ISSUE THREAD

**Issue by Lorekeeper49** [ShadowMario/FNF-PsychEngine#8250]
### Describe your bug here.

https://user-images.githubusercontent.com/93066594/164361264-e0c45594-a2c2-430b-b660-21dc937de26f.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
reconvert your files and/or make sure you're loading them from the correct modpack

**Comment by Lorekeeper49** [comment]
looks like I had to just reconvert the file
