### ISSUE TITLE
Accuracy being TOO ACCURATE

### ISSUE THREAD

**Issue by SpookyMan16** [ShadowMario/FNF-PsychEngine#8253]
### Describe your problem here.

how do I remove highlighted bit, the code for it is
local ratingNum = getProperty('ratingPercent') * 100
![aaaaaaaaaa](https://user-images.githubusercontent.com/89250852/164414005-1324de15-b140-4d47-8560-0d921b64ee77.PNG)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by swordcube** [comment]
```
          function roundDecimal(Value, Precision)
		local mult = 1
		for i = 0, Precision)
			mult = mult * 10

		return math.floor(Value * mult) / mult
	 end
```

use this function to round decimals (like ratingPercent)

it's used like so:
```
setTextString('whateveryourscoretextis', roundDecimal(ratingPercent, 2))
```

the accuracy turns from this:
99.9458675438293485748392

to something like this:
99.94

**Comment by NesDoesGithub** [comment]
> 

i get the lua error
mystage.lua:4 'do' expected near 'mult'
