### ISSUE TITLE
Changing GF in the menu

### ISSUE THREAD

**Issue by DvyDyster** [ShadowMario/FNF-PsychEngine#8254]
### I Need Help With Changing GF in the intro menu

I need help with changing GF in the intro menu, Thats it, i tried just replacing the gfbumpin.png and .xml but it doesnt work, i only need help with changing it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by keanu64github** [comment]
That's because it's not gfBumpin, its gfDanceTitle.
