### ISSUE TITLE
Running Lime Test Windows does not work!

### ISSUE THREAD

**Issue by Arctase** [ShadowMario/FNF-PsychEngine#8255]
### Describe your problem here.

PS D:\Categories\Modding\MyModdingStuff\Modding\FNFmodding\MyFirstMod\FNF-PsychEngine-main\FNF-PsychEngine-main> lime test windows
source/Achievements.hx:157: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/MainMenuState.hx:66: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:319: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/CharacterEditorState.hx:94: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/DialogueCharacterEditorState.hx:87: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
D:/Categories/Programming/Haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:145: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/Categories/Programming/Haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:180: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/Categories/Programming/Haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:221: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/Categories/Programming/Haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:515: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/Categories/Programming/Haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:483: characters 37-56 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/Categories/Programming/Haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:484: characters 31-47 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/Categories/Programming/Haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:646: characters 10-42 : Warning : Std.is is deprecated. Use Std.isOfType instead.
source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
D:\Categories\Modding\MyModdingStuff\Modding\FNFmodding\MyFirstMod\FNF-PsychEngine-main\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Clearly you did not

**Comment by Arctase** [comment]
> Clearly you did not

Real helpful.

**Comment by frantastic24** [comment]
I can't see the shit you installed, instead of being sassy go back through the list and try again

**Comment by Robert124l** [comment]
visual studios 2019 components

**Comment by sugodick** [comment]
> ### Describe your problem here.
> PS D:\Categories\Modding\MyModdingStuff\Modding\FNFmodding\MyFirstMod\FNF-PsychEngine-main\FNF-PsychEngine-main> lime test windows source/Achievements.hx:157: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead source/MainMenuState.hx:66: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead source/PlayState.hx:319: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead source/editors/CharacterEditorState.hx:94: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead source/editors/DialogueCharacterEditorState.hx:87: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead D:/Categories/Programming/Haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:145: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/Categories/Programming/Haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:180: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/Categories/Programming/Haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:221: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/Categories/Programming/Haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:515: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/Categories/Programming/Haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:483: characters 37-56 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/Categories/Programming/Haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:484: characters 31-47 : Warning : Std.is is deprecated. Use Std.isOfType instead. D:/Categories/Programming/Haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:646: characters 10-42 : Warning : Std.is is deprecated. Use Std.isOfType instead. source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead D:\Categories\Modding\MyModdingStuff\Modding\FNFmodding\MyFirstMod\FNF-PsychEngine-main\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion Warning: Could not find Visual Studio 2017 VsDevCmd Missing HXCPP_VARS Error: Could not automatically setup MSVC
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Windows x64
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No

ok so just uninstall visual studio 2022 preview or 2021 then install visual studio 2019 and install :

windows 10 sdk 10.0.17763

MSVC v141 build tools
MSVC v142 build tools 

and thats all
