### ISSUE TITLE
Character creator

### ISSUE THREAD

**Issue by MegaMatt2712** [ShadowMario/FNF-PsychEngine#8257]
### Describe your bug here.

When I try to put another character, I put the image file and the xml file in the "shared/images/characters" folder, and when I try to put the character, I put the character's name correctly and it doesn't load. Please fix that in version 0.53h

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nop

**Comment by bf244** [comment]
try putting it in the mods folder

**Comment by ShadowMario** [comment]
You have to put it in `mods/images/characters/`, not `assets/`

![Screenshot_5](https://user-images.githubusercontent.com/44785097/164555321-9a46c4d4-77bc-4429-b4b9-af9e6995e91c.png)

**Comment by MegaMatt2712** [comment]
@ShadowMario Thank you!
