### ISSUE TITLE
how to change a modified version into a new "officialBuild"

### ISSUE THREAD

**Issue by TomyGamy** [ShadowMario/FNF-PsychEngine#8258]
### Describe your problem here.

I'm modifying the engine to make a new one (like grafex), and I would like to know how to make my modification counting like an "officialBuild"

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Project.xml

**Comment by ShadowMario** [comment]
[Drop this on art folder](https://github.com/ShadowMario/FNF-PsychEngine/files/8535182/art.zip)

**Comment by TomyGamy** [comment]
thanks
