### ISSUE TITLE
Beginning and ending dialogue with cutscene issue

### ISSUE THREAD

**Issue by ImASpoopyTurtle** [ShadowMario/FNF-PsychEngine#8259]
### Describe your problem here.

modding with source but using lua for this part, i think i messed up this script when i added a cutscene since it worked perfectly before,

the issue is that after the cutscene the beginning dialogue will work up will loop the entire thing forever
![image](https://user-images.githubusercontent.com/62915204/164557317-dedaff8f-3615-4010-a1a7-7d710d4dac06.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
You didn't set `playDialogue` to false after dialogue plays

**Comment by ImASpoopyTurtle** [comment]
dw i did something else since it was easier to do anyway, + i did that before and it decided not to play the final dialogue
