### ISSUE TITLE
What does each item of BOYFRIEND.xml file mean?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#826]
### What is your question?

Below is `BOYFRIEND.xml` file:

![Snipaste_2021-11-05_21-53-04](https://user-images.githubusercontent.com/13177997/140521540-87de0158-ef13-4095-baf6-a7766689f2bb.png)

What does each item  mean?
1、name
2、x and y
3、width and height
4、frameX and frameY
5、frameWidth and frameHeight
6、there is a four-digit number in the value of name ,like this:
```
BF NOTE DOWN0000
BF NOTE DOWN0001
BF NOTE DOWN0002
BF NOTE DOWN0003
BF NOTE DOWN0004
BF NOTE DOWN0005
```
What does this four-digit number mean?

**Comment by PoleyMagik** [comment]
This isn't really a Psych exclusive thing, might wanna look elsewhere for help regarding character xmls.
