### ISSUE TITLE
Event before a song plays

### ISSUE THREAD

**Issue by StickMation** [ShadowMario/FNF-PsychEngine#8261]
### What is your question?

So is there a way to make an event play before a song like Winter Holiday or like a small animation?

**Comment by Lorekeeper49** [comment]
```
local allowCountdown = false
function onStartCountdown()
    if not allowCountdown and isStoryMode and not seenCutscene then
        setProperty('inCutscene', true);
        --code
        allowCountdown = true;
        return Function_Stop;
    end
    return Function_Continue;
end
```

**Comment by StickMation** [comment]
> ```
> local allowCountdown = false
> function onStartCountdown()
>     if not allowCountdown and isStoryMode and not seenCutscene then
>         setProperty('inCutscene', true);
>         --code
>         allowCountdown = true;
>         return Function_Stop;
>     end
>     return Function_Continue;
> end
> ```

where do i put this?

**Comment by Lorekeeper49** [comment]
in a file in the data folder of the song you want it for named 'script.lua'

**Comment by StickMation** [comment]
So i just, put the event name to replace "'inCutscene'" or something else?

**Comment by Lorekeeper49** [comment]
where I have the comment is where you place the code for the cutscene

**Comment by StickMation** [comment]
So the regular code for a cutscene?

**Comment by Lorekeeper49** [comment]
pretty much

**Comment by StickMation** [comment]
alright it works.  thank you
