### ISSUE TITLE
How to change the size of a character (bf, opponent and gf) in a certain stage

### ISSUE THREAD

**Issue by sky-93** [ShadowMario/FNF-PsychEngine#8262]
### Describe your problem here.

Does anyone know how to change the size of a character (bf, opponent and gf) in a certain stage?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#scale-functions
