### ISSUE TITLE
Object opacity

### ISSUE THREAD

**Issue by EgguMan** [ShadowMario/FNF-PsychEngine#8264]
### What feature do you want to get added on the **base** engine?

Its simple, An object opacity function

something like setObjectOpacity(Object, Opacity, Time to fade to opacity);

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by EgguMan** [comment]
ah I fell for the last one, haha!

**Comment by frantastic24** [comment]
Try reading the wiki

**Comment by EgguMan** [comment]
> Try reading the wiki

I did a control F of it under the object sections and got no results, can you tell me what it is if I missed it?

**Comment by frantastic24** [comment]
Tweens section
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers

**Comment by EgguMan** [comment]
> Tweens section
> https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers

Ah, right
