### ISSUE TITLE
how do I set a character's anim to a special anim

### ISSUE THREAD

**Issue by PerlIsMe** [ShadowMario/FNF-PsychEngine#8267]
### Describe your problem here.

I've heard that turning an anim into a "special anim" makes it mask over any other animation

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
specialAnim only makes the character ignore their idle until the current animation finishes
```lua
setProperty('char.specialAnim', true)
```
