### ISSUE TITLE
Run a script on a specific song

### ISSUE THREAD

**Issue by sky-93** [ShadowMario/FNF-PsychEngine#8268]
### Describe your problem here.

Hi! Does anyone know how I put a script to run on a specific song? my script is like this:

function onCreatePost()

     scaleObject('boyfriend', 1.05, 1.05)
     scaleObject('gf', 1.2, 1.2)
     scaleObject('dad', 1.25, 1.25)

end

and where can I find some list of "functions"? for example "onCreatePost()" or "onCreate()" and what they do...

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by chaostheunderscore** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API
