### ISSUE TITLE
How to make an event in miss?

### ISSUE THREAD

**Issue by EvcazinDeveloper** [ShadowMario/FNF-PsychEngine#8269]
### What is your question?

I mean, you miss and something happens, im using Lua and i need help, is there some way?

**Comment by frantastic24** [comment]
`function noteMiss(id, direction, type, sustain)`
It's on the [wiki](https://raw.githubusercontent.com/ShadowMario/FNF-PsychEngine/main/docs/TemplateScript.lua)
