### ISSUE TITLE
so,mething is wrong

### ISSUE THREAD

**Issue by feder273** [ShadowMario/FNF-PsychEngine#827]
### Describe your problem here.

![Screenshot (9)](https://user-images.githubusercontent.com/91979007/140525546-eefd67d1-e96b-42d8-bea4-e3e5ade4a992.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes but i didnt uninstall visual code

**Comment by ShadowMario** [comment]
Not a psych engine issue
