### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by Shelvsk** [ShadowMario/FNF-PsychEngine#8270]
### Describe your bug here.

I'm trying to delete the events of a song from my week but the events keep triggering even though I delete the .JSON file, what do I do?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i make a KB Sawblade Event and a Saw Note (with Lua)

**Comment by AntCrem** [comment]
Have you tried the clear events button in the debug menu or deleted the "events" JSON file?

**Comment by AntCrem** [comment]
You could try to delete the events within the files in the data folder

**Comment by AetherLynx** [comment]
it's maybe a script in the data folder, or in the scripts folder, or the custom event has a callback like on stepHit or onUpdate or something, or it's the events.json in the data folder.

**Comment by Shelvsk** [comment]
yes, I have a script in the song and in the event there is a function onUpdate, what do I do?

**Comment by Shelvsk** [comment]
i resolved my problem, i just moved the `onUpdate` function to the `onEvent` function and worked

**Comment by SnakDev** [comment]
it's on the .json file maybe
