### ISSUE TITLE
"Add Camera Zoom" does not zoom out

### ISSUE THREAD

**Issue by sky-93** [ShadowMario/FNF-PsychEngine#8271]
### Describe your problem here.

How to make "add camera zoom" event zoom back without needing opponent's notes?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CrusherMods** [comment]
its called "**Add** Camera Zoom" so I don't think you can zoom it out

**Comment by sky-93** [comment]
Every time the event is used after the opponent start singing it begins zooming out

**Comment by Itz-NOT-Miles** [comment]
use positive decimals to zoom in, and negative decimals to zoom out.

**Comment by ShimpelShe** [comment]
last time this happened to me i just placed a note with a strum time of -5000~ ms
