### ISSUE TITLE
pressing 7 opens a song instead of the charting thing

### ISSUE THREAD

**Issue by video-tootarolls00** [ShadowMario/FNF-PsychEngine#8272]
### Describe your problem here.

for my mod i want to make it so that if the player presses 7 on the last song, they get sent to a song to prevent cheating, so can i have a script for that?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by naether** [comment]
```
function onUpdate()
	if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
		endSong(true)
		loadSong('yoursonghere', 'yoursonghere', true);
	end
end
```

**Comment by Mastercopper2346** [comment]
hi

**Comment by video-tootarolls00** [comment]
> ```
> function onUpdate()
> 	if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
> 		endSong(true)
> 		loadSong('yoursonghere', 'yoursonghere', true);
> 	end
> end
> ```

ok thanks
