### ISSUE TITLE
is there some way to add the sound test menu from the vs sonic.exe mod?

### ISSUE THREAD

**Issue by JacksRobotics** [ShadowMario/FNF-PsychEngine#8273]
### What is your question?

im doing a fanmade vs sonic.exe mod and and i want to add the soundtest option to the menu. is it possible? and i want the soundtest menu unlocked.

**Comment by Lorekeeper49** [comment]
Only possible through source, though I'm no source coder so I can't help you code that in

**Comment by JacksRobotics** [comment]
> Only possible through source, though I'm no source coder so I can't help you code that in

i know. im making the mod through source. cuz there is no way to edit the source files with lua.

**Comment by JacksRobotics** [comment]
i know how

**Comment by WoodsSilent05** [comment]
> i know how

How, cuz I want to do something like that.
