### ISSUE TITLE
Performance issue in 0.5.2h

### ISSUE THREAD

**Issue by FloofyWoo** [ShadowMario/FNF-PsychEngine#8276]
### Describe your bug here.

So before I update to 0.5.2h I had 0 issue with performance. 

But ever since I updated to 0.5.2h, I get random massive lag spikes during gameplay and even in the menus. 

The lag spikes last long enough for me to loose my entire health sometimes. 

And I legit can't even fc anything anymore because of said lag spikes. 

I even tried playing on the build before 0.5.2h (0.5.2) and there was no performance issue. 

I only get them on 0.5.2h. 

I rly hope this will be fixed asap.

And I'm pretty sure it has nothing to do with how much stuff I have in my "mods" folder because it ran fine on previous versions.

I have attached clips of rly bad lag spikes I got, I pretty much get that every like 10 seconds.

https://user-images.githubusercontent.com/52764294/164815301-caee385a-cf0c-477e-84dd-7dc8bf68f563.mp4

https://user-images.githubusercontent.com/52764294/164815393-87b23de2-c1ef-4ac1-8d95-e19164bf44d5.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I did not edit anything. unless adding stuff to the mods folder counts as editing.

**Comment by Mastercopper2346** [comment]
i think its just ur pc

**Comment by tylerandari12** [comment]
> i think its just ur pc

But mine does it too tho...

Or it crashes altogether...

**Comment by FloofyWoo** [comment]
> i think its just ur pc

I have 24GB of ram and an RTX2060 so no it's not my pc. and as stated; I did not have that issue with previous versions of psyche engine
