### ISSUE TITLE
Can't Reload Json Correctly

### ISSUE THREAD

**Issue by DummyPointPog** [ShadowMario/FNF-PsychEngine#8278]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/88029043/164861992-e0e353f2-3ef5-4414-b32b-8a90418852a2.png)

Im just getting this Error while trying to Access it

If the Image doesn't load its saying assets/data/song-null.json, Im not sure why, Im using the Mods Folder

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Mastercopper2346** [comment]
is the song folder just showed?

**Comment by DummyPointPog** [comment]
yeah it literally is

**Comment by Mastercopper2346** [comment]
you cant load a difficulty with charting state. you need to go into play state and pause, and go change difficulty.

**Comment by DummyPointPog** [comment]
Found a Temp fix, I Just added another json with -null
