### ISSUE TITLE
chart bug

### ISSUE THREAD

**Issue by FrancoGD476** [ShadowMario/FNF-PsychEngine#828]
### Describe your bug here.

when I want to chart the next section (specifically section 68) it goes back to the beginning and does not let me advance

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

changes I have made: add a character, setting, the character's menu version and a song

**Comment by lemz1** [comment]
If I'm not wrong it has to do with the song's length

**Comment by ShadowMario** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/44785097/140581160-d408d7fb-c1d7-4bae-b31c-6f89e22cf381.png)
