### ISSUE TITLE
Guys, pls answer me! WHY DO I GOT BAN FROM THE SERVER?

### ISSUE THREAD

**Issue by MR-FNF** [ShadowMario/FNF-PsychEngine#8283]
### What is your question?

Yea, why???

**Comment by CrusherMods** [comment]
![image](https://user-images.githubusercontent.com/90648119/164878000-4c8107f7-8fdb-4065-8e67-8be6a72c8b9e.png)
It could've been of this

**Comment by MR-FNF** [comment]
> 

NOT AGAIN...
ALSO HOW ARE YOU GUYS WHO IS ME IN THE DISCORD???`

**Comment by MaybeMaru** [comment]
probably just guessed... and got it right

**Comment by thefatos** [comment]
100% underage moment

**Comment by Reycko** [comment]
> NOT AGAIN... ALSO HOW ARE YOU GUYS WHO IS ME IN THE DISCORD???`

idk if i should put this in r/ihadastroke or in r/brandnewsentence
imma put in on r/idontusereddit

btw send me ur discord so i can help you go back in the server

**Comment by MR-FNF** [comment]
> > NOT AGAIN... ALSO HOW ARE YOU GUYS WHO IS ME IN THE DISCORD???`
> 
> idk if i should put this in r/ihadastroke or in r/brandnewsentence imma put in on r/idontusereddit
> 
> btw send me ur discord so i can help you go back in the server

I am sorry, but @CrusherMods is right...

**Comment by Reycko** [comment]
rip, i was gonna report you to discord for being underage (discord is 13+)

**Comment by CrusherMods** [comment]
> > 
> 
> NOT AGAIN... ALSO HOW ARE YOU GUYS WHO IS ME IN THE DISCORD???`

![image](https://user-images.githubusercontent.com/90648119/164914053-c3bd0319-e55e-4906-8b12-f4fdfb7a2233.png)
maybe cuz of your profile

**Comment by Draconic-Hybrid** [comment]
Discord TOS requires 13+ age. Hold off for a bit.

**Comment by SharkFort** [comment]
Give me link discord server psych engine

**Comment by MR-FNF** [comment]
> > NOT AGAIN... ALSO HOW ARE YOU GUYS WHO IS ME IN THE DISCORD???`
> 
> ![image](https://user-images.githubusercontent.com/90648119/164914053-c3bd0319-e55e-4906-8b12-f4fdfb7a2233.png) maybe cuz of your profile

I KNEW IT…

**Comment by CrusherMods** [comment]
> > > NOT AGAIN... ALSO HOW ARE YOU GUYS WHO IS ME IN THE DISCORD???`
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/90648119/164914053-c3bd0319-e55e-4906-8b12-f4fdfb7a2233.png) maybe cuz of your profile
> 
> 
> 
> I KNEW IT…

if you knew then why ask?
