### ISSUE TITLE
How Do I Make The Camera Follow a Character's Poses via Source Code?

### ISSUE THREAD

**Issue by Tailsic111** [ShadowMario/FNF-PsychEngine#8284]
### Describe your problem here.

I'm trying to put in a moving camera for my custom build of PE 0.4.2 inspired from Dave and Bambi, and I need some help. I'm aiming for something like the camera movement in Gapple 1.2 or V.S. Camellia, and I'm doing it via source code. Any help?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Only changes with the UI, nothing much else. Working to add more though.

**Comment by sugodick** [comment]
you can do with lua in source code. no need of example_mods.

just go to assets and paste this lua :


`                -- Script made by Washo789, please, if you use it or modify it, I would like you to give me credits.
				
local xx = 520; -- Code to change the position of the camera to the left or right for your opponent, Less = Left (They can be negative numbers), More = Right
local yy = 450; -- Code to change the position of the camera up or down for the enemy Less = Down (They can be negative numbers), More = Up
local xx2 = 820; -- Same code as above, but for boyfriend left, right
local yy2 = 450; -- Same code as above, but for boyfriend up, down
local xx3 = 520; -- Same code as above, but for girlfriend left, right
local yy3 = 450; -- Same code as above, but for girlfriend, up, down
local ofs = 35; -- Code to adjust the intensity with which the camera moves, the more numbers, the more intense, and the fewer numbers, less intense
local followchars = true; -- This code is necessary for the script to work, don't even think about deleting it!
local del = 0;
local del2 = 0;

function onUpdate() -- The Main Code
	if del > 0 then
		del = del - 1
	end
	if del2 > 0 then
		del2 = del2 - 1
	end
    if followchars == true then
        if mustHitSection == false then -- Code for the camera to follow the poses of your opponent
            if getProperty('dad.animation.curAnim.name') == 'singLEFT' then
                triggerEvent('Camera Follow Pos',xx-ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singRIGHT' then
                triggerEvent('Camera Follow Pos',xx+ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singUP' then
                triggerEvent('Camera Follow Pos',xx,yy-ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singDOWN' then
                triggerEvent('Camera Follow Pos',xx,yy+ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singLEFT-alt' then
                triggerEvent('Camera Follow Pos',xx-ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singRIGHT-alt' then
                triggerEvent('Camera Follow Pos',xx+ofs,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'singUP-alt' then
                triggerEvent('Camera Follow Pos',xx,yy-ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'singDOWN-alt' then
                triggerEvent('Camera Follow Pos',xx,yy+ofs)
            end
            if getProperty('dad.animation.curAnim.name') == 'idle-alt' then
                triggerEvent('Camera Follow Pos',xx,yy)
            end
            if getProperty('dad.animation.curAnim.name') == 'idle' then
                triggerEvent('Camera Follow Pos',xx,yy)
            end
            if gfSection == true then -- The camera follows GF when she sings, only when the "GF Section" option in the chart editor is activated. 
                if getProperty('gf.animation.curAnim.name') == 'singLEFT' then -- Credits to Serebeat and company for their Slaybells mod,
                    triggerEvent('Camera Follow Pos',xx3-ofs,yy3)              -- That's where I got the gf code from.
                end
                if getProperty('gf.animation.curAnim.name') == 'singRIGHT' then
                    triggerEvent('Camera Follow Pos',xx3+ofs,yy3)
                end
                if getProperty('gf.animation.curAnim.name') == 'singUP' then
                    triggerEvent('Camera Follow Pos',xx3,yy3-ofs)
                end
                if getProperty('gf.animation.curAnim.name') == 'singDOWN' then
                    triggerEvent('Camera Follow Pos',xx3,yy3+ofs)
                end
                if getProperty('gf.animation.curAnim.name') == 'idle-alt' then
                    triggerEvent('Camera Follow Pos',xx3,yy3)
				end
                if getProperty('gf.animation.curAnim.name') == 'singRIGHT-alt' then
                    triggerEvent('Camera Follow Pos',xx3+ofs,yy3)
                end
                if getProperty('gf.animation.curAnim.name') == 'singUP-alt' then
                    triggerEvent('Camera Follow Pos',xx3,yy3-ofs)
                end
                if getProperty('gf.animation.curAnim.name') == 'singDOWN-alt' then
                    triggerEvent('Camera Follow Pos',xx3,yy3+ofs)
                end
                if getProperty('gf.animation.curAnim.name') == 'idle-alt' then
                    triggerEvent('Camera Follow Pos',xx3,yy3)
                end
            end
        else
                 -- Code for the camera to follow the poses of boyfriend
            if getProperty('boyfriend.animation.curAnim.name') == 'singLEFT' then
                triggerEvent('Camera Follow Pos',xx2-ofs,yy2)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT' then
                triggerEvent('Camera Follow Pos',xx2+ofs,yy2)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singUP' then
                triggerEvent('Camera Follow Pos',xx2,yy2-ofs)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN' then
                triggerEvent('Camera Follow Pos',xx2,yy2+ofs)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT-alt' then
                triggerEvent('Camera Follow Pos',xx2+ofs,yy2)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singUP-alt' then
                triggerEvent('Camera Follow Pos',xx2,yy2-ofs)
            end
            if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN-alt' then
                triggerEvent('Camera Follow Pos',xx2,yy2+ofs)
            end
	    if getProperty('boyfriend.animation.curAnim.name') == 'idle-alt' then
                triggerEvent('Camera Follow Pos',xx2,yy2)
            end
        end
    else
        triggerEvent('Camera Follow Pos','','') -- Self explanatory
    end
    
end`

**Comment by Tailsic111** [comment]
I already found an answer over at PsychDiscussions, thanks to TonyTimee, so I'm closing this.

**Comment by Tailsic111** [comment]
> you can do with lua in source code. no need of example_mods.
> 
> just go to assets and paste this lua :
> 
> local xx = 520; -- Code to change the position of the camera to the left or right for your opponent, Less = Left (They can be negative numbers), More = Right local yy = 450; -- Code to change the position of the camera up or down for the enemy Less = Down (They can be negative numbers), More = Up local xx2 = 820; -- Same code as above, but for boyfriend left, right local yy2 = 450; -- Same code as above, but for boyfriend up, down local xx3 = 520; -- Same code as above, but for girlfriend left, right local yy3 = 450; -- Same code as above, but for girlfriend, up, down local ofs = 35; -- Code to adjust the intensity with which the camera moves, the more numbers, the more intense, and the fewer numbers, less intense local followchars = true; -- This code is necessary for the script to work, don't even think about deleting it! local del = 0; local del2 = 0;
> 
> function onUpdate() -- The Main Code if del > 0 then del = del - 1 end if del2 > 0 then del2 = del2 - 1 end if followchars == true then if mustHitSection == false then -- Code for the camera to follow the poses of your opponent if getProperty('dad.animation.curAnim.name') == 'singLEFT' then triggerEvent('Camera Follow Pos',xx-ofs,yy) end if getProperty('dad.animation.curAnim.name') == 'singRIGHT' then triggerEvent('Camera Follow Pos',xx+ofs,yy) end if getProperty('dad.animation.curAnim.name') == 'singUP' then triggerEvent('Camera Follow Pos',xx,yy-ofs) end if getProperty('dad.animation.curAnim.name') == 'singDOWN' then triggerEvent('Camera Follow Pos',xx,yy+ofs) end if getProperty('dad.animation.curAnim.name') == 'singLEFT-alt' then triggerEvent('Camera Follow Pos',xx-ofs,yy) end if getProperty('dad.animation.curAnim.name') == 'singRIGHT-alt' then triggerEvent('Camera Follow Pos',xx+ofs,yy) end if getProperty('dad.animation.curAnim.name') == 'singUP-alt' then triggerEvent('Camera Follow Pos',xx,yy-ofs) end if getProperty('dad.animation.curAnim.name') == 'singDOWN-alt' then triggerEvent('Camera Follow Pos',xx,yy+ofs) end if getProperty('dad.animation.curAnim.name') == 'idle-alt' then triggerEvent('Camera Follow Pos',xx,yy) end if getProperty('dad.animation.curAnim.name') == 'idle' then triggerEvent('Camera Follow Pos',xx,yy) end if gfSection == true then -- The camera follows GF when she sings, only when the "GF Section" option in the chart editor is activated. if getProperty('gf.animation.curAnim.name') == 'singLEFT' then -- Credits to Serebeat and company for their Slaybells mod, triggerEvent('Camera Follow Pos',xx3-ofs,yy3) -- That's where I got the gf code from. end if getProperty('gf.animation.curAnim.name') == 'singRIGHT' then triggerEvent('Camera Follow Pos',xx3+ofs,yy3) end if getProperty('gf.animation.curAnim.name') == 'singUP' then triggerEvent('Camera Follow Pos',xx3,yy3-ofs) end if getProperty('gf.animation.curAnim.name') == 'singDOWN' then triggerEvent('Camera Follow Pos',xx3,yy3+ofs) end if getProperty('gf.animation.curAnim.name') == 'idle-alt' then triggerEvent('Camera Follow Pos',xx3,yy3) end if getProperty('gf.animation.curAnim.name') == 'singRIGHT-alt' then triggerEvent('Camera Follow Pos',xx3+ofs,yy3) end if getProperty('gf.animation.curAnim.name') == 'singUP-alt' then triggerEvent('Camera Follow Pos',xx3,yy3-ofs) end if getProperty('gf.animation.curAnim.name') == 'singDOWN-alt' then triggerEvent('Camera Follow Pos',xx3,yy3+ofs) end if getProperty('gf.animation.curAnim.name') == 'idle-alt' then triggerEvent('Camera Follow Pos',xx3,yy3) end end else -- Code for the camera to follow the poses of boyfriend if getProperty('boyfriend.animation.curAnim.name') == 'singLEFT' then triggerEvent('Camera Follow Pos',xx2-ofs,yy2) end if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT' then triggerEvent('Camera Follow Pos',xx2+ofs,yy2) end if getProperty('boyfriend.animation.curAnim.name') == 'singUP' then triggerEvent('Camera Follow Pos',xx2,yy2-ofs) end if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN' then triggerEvent('Camera Follow Pos',xx2,yy2+ofs) end if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT-alt' then triggerEvent('Camera Follow Pos',xx2+ofs,yy2) end if getProperty('boyfriend.animation.curAnim.name') == 'singUP-alt' then triggerEvent('Camera Follow Pos',xx2,yy2-ofs) end if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN-alt' then triggerEvent('Camera Follow Pos',xx2,yy2+ofs) end if getProperty('boyfriend.animation.curAnim.name') == 'idle-alt' then triggerEvent('Camera Follow Pos',xx2,yy2) end end else triggerEvent('Camera Follow Pos','','') -- Self explanatory end
> 
> end

Is it possible if you can send it in a code?

**Comment by sugodick** [comment]
idk how to do that man im a complete beginner to github.

**Comment by sugodick** [comment]
`local xx = 520; -- Code to change the position of the camera to the left or right for your opponent, Less = Left (They can be negative numbers), More = Right
local yy = 450; -- Code to change the position of the camera up or down for the enemy Less = Down (They can be negative numbers), More = Up
local xx2 = 820; -- Same code as above, but for boyfriend left, right
local yy2 = 450; -- Same code as above, but for boyfriend up, down
local xx3 = 520; -- Same code as above, but for girlfriend left, right
local yy3 = 450; -- Same code as above, but for girlfriend, up, down
local ofs = 35; -- Code to adjust the intensity with which the camera moves, the more numbers, the more intense, and the fewer numbers, less intense
local followchars = true; -- This code is necessary for the script to work, don't even think about deleting it!
local del = 0;
local del2 = 0;

function onUpdate() -- The Main Code
if del > 0 then
del = del - 1
end
if del2 > 0 then
del2 = del2 - 1
end
if followchars == true then
if mustHitSection == false then -- Code for the camera to follow the poses of your opponent
if getProperty('dad.animation.curAnim.name') == 'singLEFT' then
triggerEvent('Camera Follow Pos',xx-ofs,yy)
end
if getProperty('dad.animation.curAnim.name') == 'singRIGHT' then
triggerEvent('Camera Follow Pos',xx+ofs,yy)
end
if getProperty('dad.animation.curAnim.name') == 'singUP' then
triggerEvent('Camera Follow Pos',xx,yy-ofs)
end
if getProperty('dad.animation.curAnim.name') == 'singDOWN' then
triggerEvent('Camera Follow Pos',xx,yy+ofs)
end
if getProperty('dad.animation.curAnim.name') == 'singLEFT-alt' then
triggerEvent('Camera Follow Pos',xx-ofs,yy)
end
if getProperty('dad.animation.curAnim.name') == 'singRIGHT-alt' then
triggerEvent('Camera Follow Pos',xx+ofs,yy)
end
if getProperty('dad.animation.curAnim.name') == 'singUP-alt' then
triggerEvent('Camera Follow Pos',xx,yy-ofs)
end
if getProperty('dad.animation.curAnim.name') == 'singDOWN-alt' then
triggerEvent('Camera Follow Pos',xx,yy+ofs)
end
if getProperty('dad.animation.curAnim.name') == 'idle-alt' then
triggerEvent('Camera Follow Pos',xx,yy)
end
if getProperty('dad.animation.curAnim.name') == 'idle' then
triggerEvent('Camera Follow Pos',xx,yy)
end
if gfSection == true then -- The camera follows GF when she sings, only when the "GF Section" option in the chart editor is activated.
if getProperty('gf.animation.curAnim.name') == 'singLEFT' then -- Credits to Serebeat and company for their Slaybells mod,
triggerEvent('Camera Follow Pos',xx3-ofs,yy3) -- That's where I got the gf code from.
end
if getProperty('gf.animation.curAnim.name') == 'singRIGHT' then
triggerEvent('Camera Follow Pos',xx3+ofs,yy3)
end
if getProperty('gf.animation.curAnim.name') == 'singUP' then
triggerEvent('Camera Follow Pos',xx3,yy3-ofs)
end
if getProperty('gf.animation.curAnim.name') == 'singDOWN' then
triggerEvent('Camera Follow Pos',xx3,yy3+ofs)
end
if getProperty('gf.animation.curAnim.name') == 'idle-alt' then
triggerEvent('Camera Follow Pos',xx3,yy3)
end
if getProperty('gf.animation.curAnim.name') == 'singRIGHT-alt' then
triggerEvent('Camera Follow Pos',xx3+ofs,yy3)
end
if getProperty('gf.animation.curAnim.name') == 'singUP-alt' then
triggerEvent('Camera Follow Pos',xx3,yy3-ofs)
end
if getProperty('gf.animation.curAnim.name') == 'singDOWN-alt' then
triggerEvent('Camera Follow Pos',xx3,yy3+ofs)
end
if getProperty('gf.animation.curAnim.name') == 'idle-alt' then
triggerEvent('Camera Follow Pos',xx3,yy3)
end
end
else
-- Code for the camera to follow the poses of boyfriend
if getProperty('boyfriend.animation.curAnim.name') == 'singLEFT' then
triggerEvent('Camera Follow Pos',xx2-ofs,yy2)
end
if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT' then
triggerEvent('Camera Follow Pos',xx2+ofs,yy2)
end
if getProperty('boyfriend.animation.curAnim.name') == 'singUP' then
triggerEvent('Camera Follow Pos',xx2,yy2-ofs)
end
if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN' then
triggerEvent('Camera Follow Pos',xx2,yy2+ofs)
end
if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT-alt' then
triggerEvent('Camera Follow Pos',xx2+ofs,yy2)
end
if getProperty('boyfriend.animation.curAnim.name') == 'singUP-alt' then
triggerEvent('Camera Follow Pos',xx2,yy2-ofs)
end
if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN-alt' then
triggerEvent('Camera Follow Pos',xx2,yy2+ofs)
end
if getProperty('boyfriend.animation.curAnim.name') == 'idle-alt' then
triggerEvent('Camera Follow Pos',xx2,yy2)
end
end
else
triggerEvent('Camera Follow Pos','','') -- Self explanatory
end

end`

**Comment by Tailsic111** [comment]
> idk how to do that man im a complete beginner to github.

can you at least list where the paragraph things go with the slash key?

**Comment by Tailsic111** [comment]
> you can do with lua in source code. no need of example_mods.
> 
> just go to assets and paste this lua :
> 
> local xx = 520; -- Code to change the position of the camera to the left or right for your opponent, Less = Left (They can be negative numbers), More = Right local yy = 450; -- Code to change the position of the camera up or down for the enemy Less = Down (They can be negative numbers), More = Up local xx2 = 820; -- Same code as above, but for boyfriend left, right local yy2 = 450; -- Same code as above, but for boyfriend up, down local xx3 = 520; -- Same code as above, but for girlfriend left, right local yy3 = 450; -- Same code as above, but for girlfriend, up, down local ofs = 35; -- Code to adjust the intensity with which the camera moves, the more numbers, the more intense, and the fewer numbers, less intense local followchars = true; -- This code is necessary for the script to work, don't even think about deleting it! local del = 0; local del2 = 0;
> 
> function onUpdate() -- The Main Code if del > 0 then del = del - 1 end if del2 > 0 then del2 = del2 - 1 end if followchars == true then if mustHitSection == false then -- Code for the camera to follow the poses of your opponent if getProperty('dad.animation.curAnim.name') == 'singLEFT' then triggerEvent('Camera Follow Pos',xx-ofs,yy) end if getProperty('dad.animation.curAnim.name') == 'singRIGHT' then triggerEvent('Camera Follow Pos',xx+ofs,yy) end if getProperty('dad.animation.curAnim.name') == 'singUP' then triggerEvent('Camera Follow Pos',xx,yy-ofs) end if getProperty('dad.animation.curAnim.name') == 'singDOWN' then triggerEvent('Camera Follow Pos',xx,yy+ofs) end if getProperty('dad.animation.curAnim.name') == 'singLEFT-alt' then triggerEvent('Camera Follow Pos',xx-ofs,yy) end if getProperty('dad.animation.curAnim.name') == 'singRIGHT-alt' then triggerEvent('Camera Follow Pos',xx+ofs,yy) end if getProperty('dad.animation.curAnim.name') == 'singUP-alt' then triggerEvent('Camera Follow Pos',xx,yy-ofs) end if getProperty('dad.animation.curAnim.name') == 'singDOWN-alt' then triggerEvent('Camera Follow Pos',xx,yy+ofs) end if getProperty('dad.animation.curAnim.name') == 'idle-alt' then triggerEvent('Camera Follow Pos',xx,yy) end if getProperty('dad.animation.curAnim.name') == 'idle' then triggerEvent('Camera Follow Pos',xx,yy) end if gfSection == true then -- The camera follows GF when she sings, only when the "GF Section" option in the chart editor is activated. if getProperty('gf.animation.curAnim.name') == 'singLEFT' then -- Credits to Serebeat and company for their Slaybells mod, triggerEvent('Camera Follow Pos',xx3-ofs,yy3) -- That's where I got the gf code from. end if getProperty('gf.animation.curAnim.name') == 'singRIGHT' then triggerEvent('Camera Follow Pos',xx3+ofs,yy3) end if getProperty('gf.animation.curAnim.name') == 'singUP' then triggerEvent('Camera Follow Pos',xx3,yy3-ofs) end if getProperty('gf.animation.curAnim.name') == 'singDOWN' then triggerEvent('Camera Follow Pos',xx3,yy3+ofs) end if getProperty('gf.animation.curAnim.name') == 'idle-alt' then triggerEvent('Camera Follow Pos',xx3,yy3) end if getProperty('gf.animation.curAnim.name') == 'singRIGHT-alt' then triggerEvent('Camera Follow Pos',xx3+ofs,yy3) end if getProperty('gf.animation.curAnim.name') == 'singUP-alt' then triggerEvent('Camera Follow Pos',xx3,yy3-ofs) end if getProperty('gf.animation.curAnim.name') == 'singDOWN-alt' then triggerEvent('Camera Follow Pos',xx3,yy3+ofs) end if getProperty('gf.animation.curAnim.name') == 'idle-alt' then triggerEvent('Camera Follow Pos',xx3,yy3) end end else -- Code for the camera to follow the poses of boyfriend if getProperty('boyfriend.animation.curAnim.name') == 'singLEFT' then triggerEvent('Camera Follow Pos',xx2-ofs,yy2) end if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT' then triggerEvent('Camera Follow Pos',xx2+ofs,yy2) end if getProperty('boyfriend.animation.curAnim.name') == 'singUP' then triggerEvent('Camera Follow Pos',xx2,yy2-ofs) end if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN' then triggerEvent('Camera Follow Pos',xx2,yy2+ofs) end if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT-alt' then triggerEvent('Camera Follow Pos',xx2+ofs,yy2) end if getProperty('boyfriend.animation.curAnim.name') == 'singUP-alt' then triggerEvent('Camera Follow Pos',xx2,yy2-ofs) end if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN-alt' then triggerEvent('Camera Follow Pos',xx2,yy2+ofs) end if getProperty('boyfriend.animation.curAnim.name') == 'idle-alt' then triggerEvent('Camera Follow Pos',xx2,yy2) end end else triggerEvent('Camera Follow Pos','','') -- Self explanatory end
> 
> end

can you please list where the paragraph things go with the slash key? thanks, also where in assets do i place the lua?

**Comment by Tailsic111** [comment]
> > you can do with lua in source code. no need of example_mods.
> > just go to assets and paste this lua :
> > local xx = 520; -- Code to change the position of the camera to the left or right for your opponent, Less = Left (They can be negative numbers), More = Right local yy = 450; -- Code to change the position of the camera up or down for the enemy Less = Down (They can be negative numbers), More = Up local xx2 = 820; -- Same code as above, but for boyfriend left, right local yy2 = 450; -- Same code as above, but for boyfriend up, down local xx3 = 520; -- Same code as above, but for girlfriend left, right local yy3 = 450; -- Same code as above, but for girlfriend, up, down local ofs = 35; -- Code to adjust the intensity with which the camera moves, the more numbers, the more intense, and the fewer numbers, less intense local followchars = true; -- This code is necessary for the script to work, don't even think about deleting it! local del = 0; local del2 = 0;
> > function onUpdate() -- The Main Code if del > 0 then del = del - 1 end if del2 > 0 then del2 = del2 - 1 end if followchars == true then if mustHitSection == false then -- Code for the camera to follow the poses of your opponent if getProperty('dad.animation.curAnim.name') == 'singLEFT' then triggerEvent('Camera Follow Pos',xx-ofs,yy) end if getProperty('dad.animation.curAnim.name') == 'singRIGHT' then triggerEvent('Camera Follow Pos',xx+ofs,yy) end if getProperty('dad.animation.curAnim.name') == 'singUP' then triggerEvent('Camera Follow Pos',xx,yy-ofs) end if getProperty('dad.animation.curAnim.name') == 'singDOWN' then triggerEvent('Camera Follow Pos',xx,yy+ofs) end if getProperty('dad.animation.curAnim.name') == 'singLEFT-alt' then triggerEvent('Camera Follow Pos',xx-ofs,yy) end if getProperty('dad.animation.curAnim.name') == 'singRIGHT-alt' then triggerEvent('Camera Follow Pos',xx+ofs,yy) end if getProperty('dad.animation.curAnim.name') == 'singUP-alt' then triggerEvent('Camera Follow Pos',xx,yy-ofs) end if getProperty('dad.animation.curAnim.name') == 'singDOWN-alt' then triggerEvent('Camera Follow Pos',xx,yy+ofs) end if getProperty('dad.animation.curAnim.name') == 'idle-alt' then triggerEvent('Camera Follow Pos',xx,yy) end if getProperty('dad.animation.curAnim.name') == 'idle' then triggerEvent('Camera Follow Pos',xx,yy) end if gfSection == true then -- The camera follows GF when she sings, only when the "GF Section" option in the chart editor is activated. if getProperty('gf.animation.curAnim.name') == 'singLEFT' then -- Credits to Serebeat and company for their Slaybells mod, triggerEvent('Camera Follow Pos',xx3-ofs,yy3) -- That's where I got the gf code from. end if getProperty('gf.animation.curAnim.name') == 'singRIGHT' then triggerEvent('Camera Follow Pos',xx3+ofs,yy3) end if getProperty('gf.animation.curAnim.name') == 'singUP' then triggerEvent('Camera Follow Pos',xx3,yy3-ofs) end if getProperty('gf.animation.curAnim.name') == 'singDOWN' then triggerEvent('Camera Follow Pos',xx3,yy3+ofs) end if getProperty('gf.animation.curAnim.name') == 'idle-alt' then triggerEvent('Camera Follow Pos',xx3,yy3) end if getProperty('gf.animation.curAnim.name') == 'singRIGHT-alt' then triggerEvent('Camera Follow Pos',xx3+ofs,yy3) end if getProperty('gf.animation.curAnim.name') == 'singUP-alt' then triggerEvent('Camera Follow Pos',xx3,yy3-ofs) end if getProperty('gf.animation.curAnim.name') == 'singDOWN-alt' then triggerEvent('Camera Follow Pos',xx3,yy3+ofs) end if getProperty('gf.animation.curAnim.name') == 'idle-alt' then triggerEvent('Camera Follow Pos',xx3,yy3) end end else -- Code for the camera to follow the poses of boyfriend if getProperty('boyfriend.animation.curAnim.name') == 'singLEFT' then triggerEvent('Camera Follow Pos',xx2-ofs,yy2) end if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT' then triggerEvent('Camera Follow Pos',xx2+ofs,yy2) end if getProperty('boyfriend.animation.curAnim.name') == 'singUP' then triggerEvent('Camera Follow Pos',xx2,yy2-ofs) end if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN' then triggerEvent('Camera Follow Pos',xx2,yy2+ofs) end if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT-alt' then triggerEvent('Camera Follow Pos',xx2+ofs,yy2) end if getProperty('boyfriend.animation.curAnim.name') == 'singUP-alt' then triggerEvent('Camera Follow Pos',xx2,yy2-ofs) end if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN-alt' then triggerEvent('Camera Follow Pos',xx2,yy2+ofs) end if getProperty('boyfriend.animation.curAnim.name') == 'idle-alt' then triggerEvent('Camera Follow Pos',xx2,yy2) end end else triggerEvent('Camera Follow Pos','','') -- Self explanatory end
> > end
> 
> can you please list where the paragraph things go with the slash key? thanks, also where in assets do i place the lua?

nvm about the paragraph things, but where in assets do i place the lua script

**Comment by Tailsic111** [comment]
Where do I paste the Lua in assets tho
