### ISSUE TITLE
Hurt Notes Offset

### ISSUE THREAD

**Issue by KyleOliverDeveloper** [ShadowMario/FNF-PsychEngine#8285]
### Describe your problem here.

Hello. My hurt notes are "glitched" in offset and idk how to change it. Any Help?

Here's image:
![image](https://user-images.githubusercontent.com/94708825/164884340-b9dbf7ae-7e28-4661-ae79-3864628cce52.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

just the hurt notes

**Comment by Mastercopper2346** [comment]
you messed up the offsets of your **xml** file. you need to fix them
