### ISSUE TITLE
Saving data in Lua

### ISSUE THREAD

**Issue by MaybeMaru** [ShadowMario/FNF-PsychEngine#8286]
### What is your question?

Pretty self explanatory, I would like to know how saving data stuff in Lua works since im pretty sure there isnt any documentation yet

**Comment by AetherLynx** [comment]
i answered that question to a guy in discussions but the tab is gone so i have to rewrite it again ffs, here.
Please note that this is from what i understood from using them, they may do something differently but they work for me like this.
```lua

initSaveData('savefilename', 'Folder Name')

flushSaveData('savefilename')

setDataFromSave('savefilename', 'variable name', "variable's value")

getDataFromSave('savefilename', 'variable name')

```

- Explanation

- **InitSaveData:** loads the savefile, if it doesn't exist it creates it, you have to use this function before getting or setting any data. 
SaveFileName: Save file's name.
Folder Name: Folder to load the save file from/create the save file in.

- **FlushSaveData:** i don't know what it does yet, sorry.
SaveFileName: Save file to flush the data from (??)

- **setDataFromSave:** adds a Variable and it's value, pretty much like [ local variable = 0 ] in lua.
SaveFileName: Save File to set the data to.
Variable Name: The name of the value you want to save, like a tag, you should know this.
Variable's Value: The value of that variable, it can be anything, like a string, an integer, a bool, etc.

- **getDataFromSave:** gets previously saved data from the save file. For using this you must use InitSaveData first to load the file.
SaveFileName: Save file to load the data from.
Variable Name: The name of the value you saved.

**Comment by MaybeMaru** [comment]
Thank you so much mate
I will close this now

**Comment by ScarabWasTaken** [comment]
> * Folder Name: Folder to load the save file from/create the save file in.

What root folder is it saving to?
