### ISSUE TITLE
Just a joking question

### ISSUE THREAD

**Issue by MR-FNF** [ShadowMario/FNF-PsychEngine#8287]
### What is your question?

My dad let me play only **1 hour** per day
Is that so less?
MY F*CKING DAD, is he too grumpy??

**Comment by TheiLusion** [comment]
🤔🤔🤔

**Comment by enjayar625** [comment]
Imagine if he sees this

**Comment by AetherLynx** [comment]
this doesn't have anything to do with psych engine, close this.

**Comment by PerlIsMe** [comment]
depends on your age

**Comment by PerlIsMe** [comment]
> depends on your age

if your > 13, then probably yeah, but if < 13 then video gaming time should at least be 2 - 5 hours
