### ISSUE TITLE
After playing a video, Pressing a button crashes the game.

### ISSUE THREAD

**Issue by LilbrosGits** [ShadowMario/FNF-PsychEngine#829]
### Describe your bug here.

After it plays the video, everything looks to be working well until i press an arrow, and then the game crashes, i have tried in every way, through freeplay, and storymode, it just won't work, and i need a fix.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i added a week, new songs and a cutscene

**Comment by ShadowMario** [comment]
For me it sounds like an issue with a custom character (If you're using any) or possibly missing any files, i will need more information.

**Comment by LilbrosGits** [comment]
I figured out the issue, it had something to do with the achievments

**Comment by ShadowMario** [comment]
> I figured out the issue, it had something to do with the achievments

THEN CLOSE THE MF ISSUE
