### ISSUE TITLE
coding in erect remixes

### ISSUE THREAD

**Issue by oof-plays-yt** [ShadowMario/FNF-PsychEngine#8290]
### What is your question?

How do you code in erect remixes? (a bit like this)
![image](https://user-images.githubusercontent.com/99497910/164891999-06d9469b-3b1c-4f36-ae52-b3c9b9286d14.png)

**Comment by Mastercopper2346** [comment]
you need a different folder for the "ex" song.
then in your .json file, it should have "song":your-song-name
Replace the song name (**IN THE .JSON FILE**) with your ex song.
test it out.

**Comment by oof-plays-yt** [comment]
thanks
