### ISSUE TITLE
A sprite that changes image when an arrow is pressed

### ISSUE THREAD

**Issue by sky-93** [ShadowMario/FNF-PsychEngine#8291]
### Describe your problem here.

I'm trying to create a script that detects when an arrow is pressed a sprite changes to the image corresponding to the color of the arrow, but each light sprite is separated into png's (like the cassette girl light), does anyone know a script that can do this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by enjayar625** [comment]
Maybe try editing the change character on key press thing from the wiki and maybe try to change the character names to the bg image names

https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API

https://cdn.discordapp.com/attachments/866856727621795850/880169101891342366/ChangeCharacterScript.lua

It may not work but its worth a shot

**Comment by AetherLynx** [comment]
If you mean when you press a note then:

- Make the sprites' filename end with 1, 2, 3, 4, example: `spriteName1, spriteName2, spriteName3, spriteName4`
- For the image to appear, put the last numbers in the file name based on this:
`1 = Left Arrow | 2 = Down Arrow | 3 = Up Arrow | 4 = Right Arrow`
```lua
--4 is the sprites for each direction. if you want more sprites change 4 to other value.
--change SpriteFile to the sprites name, without the last number
--change X, Y, object camera, and other things as you like.

local definedSpr = 0

function onCreate()
     for i=1,4 do
          makeLuaSprite('spriteName'..i, 'spriteName'..i, 0, 0)
          setObjectCamera('spriteName'..i, 'other') --for showing over the hud
          addLuaSprite('spriteName'..i)
          setProperty('spriteName'..i..'.alpha', 0)
     end
end

function goodNoteHit(id, direction, noteType, isSustainNote)
         if not isSustainNote then
             definedSpr = (direction + 1)
             setProperty('spriteName'..definedSpr..'.alpha', 1)
             doTweenAlpha('fadeAway'..definedSpr, 'spriteName'..definedSpr, 0, 0.5, "linear") --remove this if you don't want it to fade away
         end
end
```

**Comment by sky-93** [comment]
It worked! Thank you!
