### ISSUE TITLE
Code doesn’t launch engine

### ISSUE THREAD

**Issue by FNFUNBLOCKED** [ShadowMario/FNF-PsychEngine#8292]
### Describe your problem here.

Whenever I compile the source code and use lime test windows, it says “Error, source code is not found.”

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Mastercopper2346** [comment]
what

**Comment by Mastercopper2346** [comment]
did you delete any .hx?
