### ISSUE TITLE
Vocals don't load.

### ISSUE THREAD

**Issue by FluffB01** [ShadowMario/FNF-PsychEngine#8294]
### Describe your bug here.

The vocals just don't load in when I make a song. 

Here is how I make songs(I use downloaded build)
1. I make a folder in the mods/songs folder with my songs name.
2. I put the Vocals and Inst(both .ogg files) in it.
3. I boot up Psych Engine and go into the chart editor.
4. I type my songs name and click "Reload Audio"
5. I listen to it only to find out that I can't hear the vocals.
6. I try to make the vocals louder in audacity
7. **doesn't funkin work**
8. I fuse the inst with the vocals in audacity because I can't find any other way to make the vocals load.

Is there anything I'm doing wrong or is this a bug that other people have too?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by frantastic24** [comment]
File should be called Voices, not vocals

**Comment by FluffB01** [comment]
Thanks

sob., 23 kwi 2022, 20:17 użytkownik frantastic24 ***@***.***>
napisał:

**Comment by frantastic24** [comment]
You can close this now

**Comment by ManbiDude** [comment]
file needs to be named voices not vocals

**Comment by frantastic24** [comment]
We already figured it out dude
