### ISSUE TITLE
0.5.2h crashes on longer songs

### ISSUE THREAD

**Issue by Username2120** [ShadowMario/FNF-PsychEngine#8295]
### Describe your bug here.

I Was messing around with adding a couple of different songs to my modded version of Psych Engine, and when i went to make sure Ghost VIP (a song I added to mess with using events) was working, it seemed to crash around the 2:30 mark of the song when I'm not recording and it crashes with 1:46 left in the song while recording with the fps turned down (Shown in first video), its also using pretty much double the memory most other songs are using (Shown in second video). I tried getting rid of the events it was using, but it would still crash at the same times. any help would be great! Thanks!

https://user-images.githubusercontent.com/93958902/164943406-63566c1a-b305-4d6f-8b0a-56032f6b4ed1.mp

https://user-images.githubusercontent.com/93958902/164943509-7cdc8b3d-bb7c-455e-a40f-0341c2f087d4.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Unless adding things to the Mods folder counts, No, i did not edit anything.

**Comment by AetherLynx** [comment]
try setting your fps cap to 60.

**Comment by Username2120** [comment]
almost worked, got to around 0:42.

**Comment by Draconic-Hybrid** [comment]
I feel like that's definitely more of a PC issue, rather than a Psych issue.
