### ISSUE TITLE
[file_open,modsList.txt]

### ISSUE THREAD

**Issue by sky-93** [ShadowMario/FNF-PsychEngine#8298]
### Describe your problem here.

Every time I try to put a mod on my psych engine this error always appears, does anyone know how to solve it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Mastercopper2346** [comment]
what do you mean?

**Comment by Mastercopper2346** [comment]
when you like, make a separate folder in mods/folder/?

**Comment by sky-93** [comment]
When i insert mods into mods folder and try to make a modpack

**Comment by AetherLynx** [comment]
try creating a file in your main psych engine folder (not inside assets, outside, along with the exe) and creating a file called `modsList.txt`, like this

<img src="https://user-images.githubusercontent.com/81195994/164949557-edcd01d0-bcfa-4b7c-a8f2-935601bf4823.png" width=500>

if it still crashes try putting this in the text file:
`[mod's folder name]|1`
example:
`MyMod|1`

**Comment by CatOfTheDarkness** [comment]
> try creating a file in your main psych engine folder (not inside assets, outside, along with the exe) and creating a file called `modsList.txt`, like this
> 
> <img alt="" width="500" src="https://user-images.githubusercontent.com/81195994/164949557-edcd01d0-bcfa-4b7c-a8f2-935601bf4823.png">
> 
> if it still crashes try putting this in the text file: `[mod's folder name]|1` example: `MyMod|1`
![Captura de Tela (164)](https://github.com/ShadowMario/FNF-PsychEngine/assets/124204264/58d3cbbe-0676-4ba1-89d2-9e6ed9a57b23)
if I'm doing something dumb, tell me. I'm doing this because it worked for me in lua. This is source and didn't work.

**Comment by 4ngrythekidd** [comment]
I tried putting [mod's folder name]|1 in the thing but the ENGINE STILL KEEPS CRASHING.

**Comment by 4ngrythekidd** [comment]
I even tried MyMod|1 and it still didn't work.
