### ISSUE TITLE
how can i do this shit?

### ISSUE THREAD

**Issue by Robert124l** [ShadowMario/FNF-PsychEngine#8299]
### Describe your problem here.

[https://youtu.be/fqJcm0xAh1g](url)

### Are you modding a build from source or with Lua?

Source or lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
```lua
function onSongStart()
	setProperty('songLength', number) --fake songLength, in milliseconds
end

function onUpdatePost()
	if getProperty('songLength') < songLength and curBeat >= number then --change curBeat to whatever
		if (getProperty('songLength') + 1000) < songLength then
			setProperty('songLength', getProperty('songLength')+1000) --add 1 second to length
		else
			setProperty('songLength', songLength)
		end
	end
end
```

**Comment by Robert124l** [comment]
> ```lua
> function onSongStart()
> 	setProperty('songLength', number) --fake songLength, in milliseconds
> end
> 
> function onUpdatePost()
> 	if getProperty('songLength') < songLength and curBeat >= number then --change curBeat to whatever
> 		if (getProperty('songLength') + 1000) < songLength then
> 			setProperty('songLength', getProperty('songLength')+1000) --add 1 second to length
> 		else
> 			setProperty('songLength', songLength)
> 		end
> 	end
> end
> ```

I am in phone right now but when i can i will test it (pls don't close this)xd

**Comment by Robert124l** [comment]
> ```lua
> function onSongStart()
> 	setProperty('songLength', number) --fake songLength, in milliseconds
> end
> 
> function onUpdatePost()
> 	if getProperty('songLength') < songLength and curBeat >= number then --change curBeat to whatever
> 		if (getProperty('songLength') + 1000) < songLength then
> 			setProperty('songLength', getProperty('songLength')+1000) --add 1 second to length
> 		else
> 			setProperty('songLength', songLength)
> 		end
> 	end
> end
> ```

XD
![Uploading Captura de pantalla (12).png…]()

**Comment by Robert124l** [comment]
I don't know if it can be seen but it sends me an error, I only put your code as it is without changing anything only the beat, but I don't understand it with placing the numbers, I don't know if you have to place them like this for example: 34 or 0:34 to give you An example.

**Comment by frantastic24** [comment]
Can't see the image

**Comment by frantastic24** [comment]
I literally commented it has to be in milliseconds

**Comment by frantastic24** [comment]
Either way I already tested this code plenty and can confirm it works so
Time to close this

**Comment by Robert124l** [comment]
> Either way I already tested this code plenty and can confirm it works so Time to close this
 Ok i fix one problem and now there is another XDDDD,
now the code works (not how I did it but I was able to make it work) now the problem, regardless of how many seconds I put or the curbeat that I put the code is loaded as soon as the song starts, that is to say that the bar is already lowered as soon as the song starts song and I don't want that, is there something I'm skipping or am I stupid? xd

**Comment by Robert124l** [comment]
> Either way I already tested this code plenty and can confirm it works so Time to close this

now the code works (not how I did it but I was able to make it work) now the problem, regardless of how many seconds I put or the curbeat that I put the code is loaded as soon as the song starts, that is to say that the bar is already lowered as soon as the song starts song and I don't want that, is there something I'm skipping or am I stupid? xd

**Comment by frantastic24** [comment]
I didn't fully get that but I'm assuming you don't want the fake length even though you need it to do the effect?

**Comment by Robert124l** [comment]
> I didn't fully get that but I'm assuming you don't want the fake length even though you need it to do the effect?

no, it is that the script is activated at the beginning of the song, and I want it to work in the middle of the song and yes, the curBeat doesn't work

**Comment by frantastic24** [comment]
It would help if I could see what your script looks like

**Comment by Robert124l** [comment]
[Uploading 20220426_210547.heic…]()

**Comment by Robert124l** [comment]
![Uploading 1127 sin título_20220426210801.png…]()

**Comment by Robert124l** [comment]
> It would help if I could see what your script looks like

https://youtu.be/CPRal-VnMSw ok i send it a video because the fucking png dosen't load

**Comment by frantastic24** [comment]
you didn't type the fake length in milliseconds like the script says and I mentioned above
Also you could've just pasted the code here in a code box

**Comment by Robert124l** [comment]
> you didn't type the fake length in milliseconds like the script says and I mentioned above Also you could've just pasted the code here in a code box

aaaaa now I understand, now just one more thing... hhuu how do I explain this to you

**Comment by Robert124l** [comment]
> you didn't type the fake length in milliseconds like the script says and I mentioned above Also you could've just pasted the code here in a code box

https://youtu.be/uKD8oVbBDiI the evnt work's but the time is in cero and the tbBG it's full before the event work

**Comment by frantastic24** [comment]
Again, it would help if I could see what your code looks like now
Looks like you did not type the length correctly

**Comment by Robert124l** [comment]
The only change i did is the 1:34 to 3.3

**Comment by Robert124l** [comment]
> Again, it would help if I could see what your code looks like now Looks like you did not type the length correctly

The only change i did is the 1:34 to 3.3

**Comment by frantastic24** [comment]
That's not in milliseconds my guy
Is your song 3.33 milliseconds long

**Comment by Robert124l** [comment]
No is 3 minutes

**Comment by Robert124l** [comment]
> That's not in milliseconds my guy Is your song 3.33 milliseconds long

No, it's 3 minutes

**Comment by frantastic24** [comment]
Cool? But why did you type that instead of your fake length in milliseconds

**Comment by Robert124l** [comment]
> Cool? But why did you type that instead of your fake length in milliseconds

because I don't know how to do it ok? if it sounds pretty stupid (and it is)

**Comment by frantastic24** [comment]
Did you try google

**Comment by Robert124l** [comment]
> Did you try google

Lles

**Comment by Robert124l** [comment]
And just send me número like 1,24 or 1.24 qnd it doesn't work

**Comment by frantastic24** [comment]
I don't know what the fuck you used but [here](https://www.google.com/search?q=minutes+to+milliseconds)

**Comment by Robert124l** [comment]
> I don't know what the fuck you used but [here](https://www.google.com/search?q=minutes+to+milliseconds)

nope, even putting 60000 which is a minute, it's still bugged

**Comment by frantastic24** [comment]
Can you AT LEAST show what the code looks like now and a screenshot of the game
I literally can't help if I don't know what you're doing

**Comment by Robert124l** [comment]
> I don't know what the fuck you used but [here](https://www.google.com/search?q=minutes+to+milliseconds)

 here it is, listen if none of this works just give me a random number and I'll polish it https://youtu.be/zSsEbt75dmQ

**Comment by frantastic24** [comment]
Can you not post it as a video I can barely read what that says
And you didn't show what happens in-game
Feels like you're just ignoring what I say

**Comment by Robert124l** [comment]
> Can you not post it as a video I can barely read what that says And you didn't show what happens in-game Feels like you're just ignoring what I say

As in the previous comments, I said they don't load the PNGs, I don't know why, and the gameplay is not necessary since the same thing continues to happen, the event works but the counter is bugged. I will try to give you a better resolution

**Comment by frantastic24** [comment]
GitHub tells you when the image is properly uploaded and even then you can copy paste into a code box what

**Comment by Robert124l** [comment]
> GitHub tells you when the image is properly uploaded and even then you can copy paste into a code box what

yes but i'm not logged in my pc so i can't copy a code box

**Comment by Robert124l** [comment]
> GitHub tells you when the image is properly uploaded and even then you can copy paste into a code box what

okay this is the last video, you were recorded in obs and edited so you can read it and so you know what happens and pls let finish this shit https://youtu.be/v2ONm1wHGcU

**Comment by frantastic24** [comment]
there's nothing wrong with the code as i just tested it, the only weird thing i see is that you're playing dadbattle instead of discarded

**Comment by Robert124l** [comment]
> there's nothing wrong with the code as i just tested it, the only weird thing i see is that you're playing dadbattle instead of discarded

Yes i change to don't do spoilers

**Comment by Robert124l** [comment]
> there's nothing wrong with the code as i just tested it, the only weird thing i see is that you're playing dadbattle instead of discarded

O my fucking god you are a genius

**Comment by Robert124l** [comment]
> there's nothing wrong with the code as i just tested it, the only weird thing i see is that you're playing dadbattle instead of discarded

literally all this time it was bugueando because I changed the script to another song, really thank you very much now if it works and sorry for making you waste all this time xd

**Comment by Robert124l** [comment]
Really really thanks

**Comment by frantastic24** [comment]
it's okay just be a little less vague and more informative when asking for help

**Comment by Robert124l** [comment]
Xd yeah, im so sorry
