### ISSUE TITLE
How do you stop healing for certain difficulty (SOURCE, NO LUA OR BLOCK)

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8301]
### What is your question?

^

**Comment by BeansCool54** [comment]
Search for the line `health += note.hitHealth * healthGain;` then replace it with 
`if(CoolUtil.difficultyString() == 'YOURDIFFICULTY') {
health += note.hitHealth * healthGain;}`

**Comment by Mastercopper2346** [comment]
thx
