### ISSUE TITLE
after a song ends the vocals glitch out

### ISSUE THREAD

**Issue by CuddleInnit** [ShadowMario/FNF-PsychEngine#8302]
### Describe your bug here.

When the songs end, the vocals start freaking out just glitching just spamming a singular note over and over until the inst ends.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by frantastic24** [comment]
it means vocals are shorter than the instrumental, just extending it gets rid of the noise

**Comment by Lorekeeper49** [comment]
> it means vocals are shorter than the instrumental, just extending it gets rid of the noise

This is basically the answer, just know that this audio glitch became known when week 6 came out when Spirit would spam the start of the song
