### ISSUE TITLE
RAM?

### ISSUE THREAD

**Issue by SupaFromSupasShow** [ShadowMario/FNF-PsychEngine#8303]
### What is your question?

Hey so is there a psych engine build that supports 4 Gigs of RAM?

**Comment by ShadowMario** [comment]
Psych Engine uses a max of 4GB RAM, just like any other fnf mod out there

**Comment by SupaFromSupasShow** [comment]
![Screenshot 2022-05-16 182132](https://user-images.githubusercontent.com/92897376/168691890-1977f97e-b31f-4035-8891-201b99e85b57.png)
this is my ram
