### ISSUE TITLE
How do I make bf not play an animation when hitting a note?

### ISSUE THREAD

**Issue by PerlIsMe** [ShadowMario/FNF-PsychEngine#8305]
### Describe your problem here.

I want to make a note similar to the "No Animation" Note Type, but with some new features along with it. How do I do it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yee

**Comment by tylerandari12** [comment]
```
if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
	setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true); --Miss has no penalties
end
```
Try this...

**Comment by Draconic-Hybrid** [comment]
Add `setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true)` to the `if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Custom Note' then`

**Comment by PerlIsMe** [comment]
> Add `setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true)` to the `if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Custom Note' then`

thanks
