### ISSUE TITLE
How can I do Custom Health bars ?

### ISSUE THREAD

**Issue by FlintIshe** [ShadowMario/FNF-PsychEngine#8307]
### What is your question?

Basically just like indie cross (again) 

Like Each song have it's own healthbar, Is it possible on PsychEngine?

**Comment by AetherLynx** [comment]
just put a script in the data folder of the song to make a sprite over the healthbar but under the icons (you might have to change their object order)

or an universal script using the `if songName == 'song' then`

**Comment by FlintIshe** [comment]
Thanks!
