### ISSUE TITLE
Poosay

### ISSUE THREAD

**Issue by Steve35117** [ShadowMario/FNF-PsychEngine#8308]
### Describe your problem here.

How to play dialogues after videos

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Smack my ass like the drum

**Comment by Steve35117** [comment]
another question
how to finish video after pressing a key

**Comment by WilliamGaming12** [comment]
> another question how to finish video after pressing a key

i dont know but, bb-panzu made a script 'bout it in the Sunday mod

the bad thing is that it's psych engine so you may have to pass it to psych engine by some way OR download a ported psych engine Sunday mod and put the script in your mod
