### ISSUE TITLE
Sprites for custom daddy dearest aren't functioning

### ISSUE THREAD

**Issue by Yuioserg** [ShadowMario/FNF-PsychEngine#8309]
### Describe your problem here.

Hi, I'm trying to replace daddy dearest with my own custom character, but the sprites don't show up as expected. Could someone help me with this? The sprites are mislocated and every time he does the idle animation the sprites go invisible and reappear repeatedly.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added several reskins to characters.

**Comment by frantastic24** [comment]
Fix your XML
