### ISSUE TITLE
how do i make a new menu and a passcode?

### ISSUE THREAD

**Issue by jjjj976** [ShadowMario/FNF-PsychEngine#831]
### Describe your problem here.

like in fnf vs baldi how you type a code to get in piracy and how to get new menu things like story mode options free play.
number 1:  how to custom menus?
number 2: how do i make a passcode to enter a song?

### Are you modding a build from source or with Lua?

Source and lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

im making a mod so i did edit

**Comment by cfgexe** [comment]
mind if i steal this idea?
lol im out of ideas

**Comment by NS-Unfair** [comment]
If you want to add some kind of secret week with a passcode, you can do that by inserting this code in the update function in StoryMenuState.hx:
                secArr=[FlxG.keys.pressed.FOUR,FlxG.keys.pressed.ONE,FlxG.keys.pressed.NINE,FlxG.keys.pressed.SIX];
		if(secretStuff<secArr.length) {
			if(secArr[secretStuff+1]==true) {
				secretStuff+=1;
				FlxG.sound.play(Paths.sound('scrollMenu'));
			}
		} else if(secretStuff>=secArr.length) {
			if (stopspamming == false)
				{
					FlxG.sound.play(Paths.sound('confirmMenu'));
	
					grpWeekText.members[curWeek].startFlashing();
					if(grpWeekCharacters.members[1].character != '') 
                                        grpWeekCharacters.members[1].animation.play('confirm');
					stopspamming = true;
				}
	
				// We can't use Dynamic Array .copy() because that crashes HTML5, here's a workaround.
				var songArray:Array<String> = [];
				var leWeek:Array<Dynamic> = WeekData.weeksLoaded.get(WeekData.weeksList[curWeek]).songs;
				for (i in 0...leWeek.length) {
					songArray.push(leWeek[i][0]);
				}
				
				// Force Difficulty to be unfair
				curDifficulty=3;
				// Nevermind that's stupid lmao
				//PlayState.storyPlaylist = songArray; 
				PlayState.isStoryMode = true;
				PlayState.storyPlaylist = ['test'];
				selectedWeek = true;
	
				var diffic = CoolUtil.difficultyStuff[curDifficulty][1];
				if(diffic == null) diffic = '';
	
				PlayState.storyDifficulty = 3;
	
				PlayState.SONG = Song.loadFromJson(PlayState.storyPlaylist[0].toLowerCase() + diffic, 
                                PlayState.storyPlaylist[0].toLowerCase());
				PlayState.storyWeek = curWeek;
				PlayState.campaignScore = 0;
				PlayState.campaignMisses = 0;
				new FlxTimer().start(1, function(tmr:FlxTimer)
				{
					LoadingState.loadAndSwitchState(new PlayState(), true);
					FreeplayState.destroyFreeplayVocals();
				});
			//FlxG.sound.play(Paths.sound('cancelMenu'));
		}

And add this line of code to class StoryMenuState:
        var secretStuff:Int = 0;
	var secArr=[];


For your first question, I don't have an answer yet

**Comment by Real-Pog** [comment]
hey this is the owner of this request which line on studio code do i put this on?

**Comment by Real-Pog** [comment]
@NS-Unfair ?

**Comment by ShadowMario** [comment]
Too complicated for explaining in a github post or even explaining it in words.

**Comment by ImaginationSuperHero528** [comment]
> Too complicated for explaining in a github post or even explaining it in words.

Wha... what?! To comp- too complicated?! You closed this cause it's too complicated to explain?! I'm sorry but wtf?!

**Comment by sans400** [comment]
> var secretStuff:Int = 0;
> var secArr=[];

what line do i put that code in storymenustate?
