### ISSUE TITLE
Character scaling

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#8310]
### Describe your problem here.

https://github.com/ShadowMario/FNF-PsychEngine/issues/1087 this but in lua

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Mods folder

**Comment by frantastic24** [comment]
Read the wiki

**Comment by CheesecakeForever** [comment]
i cannot find anything i am an idiot

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#scale-functions

**Comment by CheesecakeForever** [comment]
thx
