### ISSUE TITLE
Directories

### ISSUE THREAD

**Issue by Lorekeeper49** [ShadowMario/FNF-PsychEngine#8311]
### Describe your bug here.

I know that this is a problem that's been going on for a while, but the stage jsons within our modpacks don't work properly with directories.  Any time we put a folder name into the directory json, no matter what, the lua always goes to images and not the folder that was called in the directory

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SnakDev** [comment]
it's not used at all

**Comment by Lorekeeper49** [comment]
> it's not used at all

It should be so that the files are more organized
