### ISSUE TITLE
select character psych engine 0.5.2h

### ISSUE THREAD

**Issue by Epiclol374** [ShadowMario/FNF-PsychEngine#8313]
### Describe your problem here.

help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by MaybeMaru** [comment]
what do you mean

**Comment by tylerandari12** [comment]
*helps*

**Comment by tylerandari12** [comment]
Could we have a little more info than just "help" please?

**Comment by Lorekeeper49** [comment]
I think he wants us to help with figuring out how to make it so that we can select a character for a song

**Comment by Epiclol374** [comment]
exact, lorekeeper49

**Comment by ManbiDude** [comment]
draw a character and use spritesheet and XML maker or adobe animate and click 8 and watch JahdaMans tutorial if u want a character for a song without making one press 7 and pick the character that you want

**Comment by tylerandari12** [comment]
Im actually trying to do that right now lol...
