### ISSUE TITLE
How to add a waring screen (Like reset score warning) when choosing a difficulty?

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8314]
### Describe your problem here.

title is it, i need this

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

what

**Comment by hayfii** [comment]
![image](https://user-images.githubusercontent.com/94598301/173120770-3bc5d76b-a092-4fdd-abd4-3e6c0df44bf6.png)
