### ISSUE TITLE
Note Hold anims not working

### ISSUE THREAD

**Issue by Kitsuism** [ShadowMario/FNF-PsychEngine#8318]
### Describe your bug here.

I've added note hold animations to my character so that they don't jitter when holding a note, but it doesn't work at all and it keeps shaking when they hold a note
https://user-images.githubusercontent.com/87594698/165000108-b95246fd-0a3d-4b1a-833f-933190c30ea1.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by frantastic24** [comment]
that's how sing animations work, it depends on BPM. if you want them to not jitter, use a higher BPM
`-loop` animations only trigger after the initial animation ends

**Comment by Kitsuism** [comment]
that's... a little dumb, but it makes sense i guess. thanks for at least telling me ig
