### ISSUE TITLE
How to make animated Backgrounds?

### ISSUE THREAD

**Issue by EvcazinDeveloper** [ShadowMario/FNF-PsychEngine#8320]
### Describe your problem here.

So, im making an VS Sonic.exe 3.0 FanMade for Psych Engine

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i only use LUA as coding as my Visual Studio 2019 Community don't help.

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Custom-Sprites-Functions
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#animations-functions
