### ISSUE TITLE
Missing modsList

### ISSUE THREAD

**Issue by Sadge-Mann** [ShadowMario/FNF-PsychEngine#8321]
### Describe your problem here.

When I try to open the "Mods" section of 0.5.2/0.5.2h builds of Psych, it crashes saying that I'm missing modsList.txt. They're fresh installs so I'm wondering why it won't allow me to access the Mods tab.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Lorekeeper49** [comment]
Is modsList.txt in the folder with the exe?  If not create that file, because apparently the game doesn't automatically do that anymore

**Comment by machonessiebaby** [comment]
should create the file whenever you open MODS
