### ISSUE TITLE
How do I make a character's animation special?

### ISSUE THREAD

**Issue by PerlIsMe** [ShadowMario/FNF-PsychEngine#8323]
### Describe your problem here.

I've heard of making a character's animation special to make it complete before any next animations can play.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yee

**Comment by frantastic24** [comment]
#8267 why are you asking again

**Comment by PerlIsMe** [comment]
> #8267 why are you asking again

for some reason it I wasn't able to find it via filtering
