### ISSUE TITLE
Add Documentation for Creating a Custom Difficulty WITHOUT Source Code

### ISSUE THREAD

**Issue by Grape-Boy** [ShadowMario/FNF-PsychEngine#8325]
### What needs to be documented?

In the documentation for [adding a new difficulty](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Adding-a-New-Difficulty), it says you need the source code to add a new difficulty, even though you can do that without it, like in issue #8247.

I made a useless issue about trying to code it in a build when I could have just looked at the documentation (if it was updated)

**Comment by Grape-Boy** [comment]
Maybe, but there's no documentation for using the `Difficulties` inside the `Other` tab in the `Week Editor`.

**Comment by ShadowMario** [comment]
Tutorial updated.
