### ISSUE TITLE
Type mechanic without source (no?)

### ISSUE THREAD

**Issue by AnFnfModmaker** [ShadowMario/FNF-PsychEngine#8326]
### What is your question?

There's a way that i can make type mechanic like monochrome without source code? Like an event? (probably not, kill me 😀)

**Comment by Lorekeeper49** [comment]
Phantom attack did it, here's the link:
https://gamebanana.com/mods/362915

All you need to do is find the code for the locking notes with buttons you need to press code in the stage lua script

**Comment by DEV-idiotXD** [comment]
setProperty('boyfriend.stunned', true);

to make it so u cant hit notes
