### ISSUE TITLE
How can i make an animated stage object bounce in sync to the characters idle animations / bpm

### ISSUE THREAD

**Issue by Kitsuism** [ShadowMario/FNF-PsychEngine#8328]
### What is your question?

function onBeatHit() doesn't work they go fast no matter what bpm it is but i want them to bounce in sync with people's idles

script below

function onCreate()
	-- background shit

	makeLuaSprite('Sky','Stages/Street/Sky', -885,-500);
	addLuaSprite('Sky',false);
	
	makeLuaSprite('Mountains','Stages/Street/Mountains', -885,-500);
	addLuaSprite('Mountains',false);
	
	makeLuaSprite('Floor','Stages/Street/Street', -885,-700);
	addLuaSprite('Floor',false);
	setScrollFactor('Floor', 1,1);

	--abelone setup
	makeAnimatedLuaSprite('Abelone','Stages/Street/Abelone', -200,110)
	addAnimationByPrefix('Abelone','AbeloneBop','Abelone',24,true)
	objectPlayAnimation('Abelone','Abelone',false)
	--scaleObject('Abelone', 1, 1);
	setScrollFactor('Abelone', 1, 1);
	addLuaSprite('Abelone',false);

	--gays setup
	makeAnimatedLuaSprite('Gays','Stages/Street/Gays', 1200,160)
	addAnimationByPrefix('Gays','GayBop','Gays',24,true)
	objectPlayAnimation('Gays','Gays',false)
	setScrollFactor('Gays', 1, 1);
	addLuaSprite('Gays',false);

	--cassette setup
	makeAnimatedLuaSprite('Cassettegirl','Stages/Street/Cassettegirl', 220,20)
	addAnimationByPrefix('Cassettegirl','CassetteBop','Cassette',24,true)
	objectPlayAnimation('Cassettegirl','Cassettegirl',false)
	setScrollFactor('Cassettegirl', 1, 1);
	addLuaSprite('Cassettegirl',false);
	
	--make them bounce to the BPM (i think)
	function onBeatHit()
		objectPlayAnimation('Abelone', 'AbeloneBop');
		objectPlayAnimation('Gays', 'GayBop');
		objectPlayAnimation('Cassettegirl', 'CassetteBop');
		
		
	end

end

**Comment by frantastic24** [comment]
```lua
if curBeat % 2 == 0 then
     
end
```

**Comment by frantastic24** [comment]
You made your animations loop, change it to false

**Comment by Mastercopper2346** [comment]
#8522
