### ISSUE TITLE
forceful update

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#8330]
### Describe your bug here.

um this problem is 2 parts the next one will be in the enhancement thing
but i recently tried added another character to my mod but it crashed when i tried it
and yes i gave it an icon
and with my problem not working and with it forcing me to update(more on that in the next thing)
it feels like the game wont let me add to it and is trying to force me to update
i would update
i tried
but there is more folders
and more stuff
me get confuzzled on it
my main point will be stated in the next thing
edit: here's the next thing: https://github.com/ShadowMario/FNF-PsychEngine/issues/8331#issue-1214594950

### Command Prompt/Terminal logs (if existing)

```bash
no
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

N O

**Comment by frantastic24** [comment]
Close this one too, this isn't even a bug report
