### ISSUE TITLE
less forceful open-up 

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#8331]
### What feature do you want to get added on the **base** engine?

just me but i feel like it shouldn't force me back to my browser to update
i would update but i stated why i cant in the last post( https://github.com/ShadowMario/FNF-PsychEngine/issues/8330#issue-1214586350 (please look at this if you haven't) )
all in all i feel like it should go softer on the "hey you. yeah you. You need to update" part
and that it should be easier to port to the next update
or have a tutorial on how to port your mod to the next update
thank you

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
It doesn't force you to update

**Comment by creeperkidking** [comment]
ye but it forces be to the page

**Comment by frantastic24** [comment]
Update your game, this issue is invalid
