### ISSUE TITLE
Modify event groups

### ISSUE THREAD

**Issue by Maxenswel** [ShadowMario/FNF-PsychEngine#8333]
### What feature do you want to get added on the **base** engine?

On the chart editor, I'd like to click (or another manipulation) on an event group to edit the events inside it instead of removing the event group entirely and making a new one.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by keanu64github** [comment]
Hold "Control" to modify existing notes/events.

**Comment by Grape-Boy** [comment]
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Useful feature

you failed the test
