### ISSUE TITLE
Disable the debug menu

### ISSUE THREAD

**Issue by powerful29** [ShadowMario/FNF-PsychEngine#8334]
### Describe your problem here.

I wanna disable the `debug` menu in a song and idk how can you give script please

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

It's not build

**Comment by Mastercopper2346** [comment]
```
function onUpdate()
	if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
		--code
	end
end
```

**Comment by powerful29** [comment]
ok let me try

**Comment by powerful29** [comment]
It didn't work

**Comment by powerful29** [comment]
> ```
> function onUpdate()
> 	if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
> 		--code
> 	end
> end
> ```

dude it dosn't work comon

**Comment by Mastercopper2346** [comment]
Replace --code WITH SOME CODE

**Comment by powerful29** [comment]
Like I wanna make it go to song how could i make it?

**Comment by powerful29** [comment]
BRUH

**Comment by DEV-idiotXD** [comment]
goto InputFormatter.hx and remove the part where it says 

```haxe
			case SEVEN:
				return "7";
```

and remove it if you want it to only work if u want to put an if and blah blah blah and wutever

**Comment by powerful29** [comment]
What the f*** IT'S NOT SOURCE CODE IT'S NOT BUILD

**Comment by DEV-idiotXD** [comment]
> What the f*** IT'S NOT SOURCE CODE IT'S NOT BUILD

and?

**Comment by FNaS2ToySonic** [comment]
function onUpdate(elapsed)
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
        endSong()
    end
end --Crashes the game, or ends the song
