### ISSUE TITLE
Options in PauseState

### ISSUE THREAD

**Issue by CasualCypress** [ShadowMario/FNF-PsychEngine#8337]
### What feature do you want to get added on the **base** engine?

So in the kade engine 1.8 build, when your playing a song an pause it an it has the 'Options' Feature an takes to the OptionsState, I technically added it in psych i have a video of it, but when you leave the optionsState it only goes back to the title menu not back to the song you where playing on.

[Video]https://user-images.githubusercontent.com/66497511/165175205-e84f59ab-7497-44a1-9165-2115e42772db.mp4

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by keanu64github** [comment]
Like this?

https://user-images.githubusercontent.com/59621417/165435174-66f13957-88a0-43fa-83fa-822be934821d.mp4

**Comment by keanu64github** [comment]
Change the options switch (for choosing what option does what) for the options select with this
![Step 1](https://user-images.githubusercontent.com/59621417/165435609-8912f0cb-6b80-4d9f-b7c1-ee3c09c1773f.png)
Add these at the beginning where they are first specified (Don't re-add menuBG, it's just there so you know where to put it.
![Step 2](https://user-images.githubusercontent.com/59621417/165435696-0665b0d0-9982-40f1-92ca-b2e071339d20.png)
Add this after those variables from last step.
![Step 3](https://user-images.githubusercontent.com/59621417/165435792-5dcbeda0-78dc-42a4-8749-57c8ef47cf10.png)
Add this in onUpdate (Don't re-add UI_DOWN_P or whatever cuz its just for locating where it needs to go lol)
![Step 4](https://user-images.githubusercontent.com/59621417/165436091-38a855b5-9cc5-453d-8e4f-8d325ab41af0.png)

then it should work probably (worked for me i literally just added this to my mod to see how to do it.)
