### ISSUE TITLE
How do I move the lane of the arrows using lua code

### ISSUE THREAD

**Issue by NonCanonBF** [ShadowMario/FNF-PsychEngine#8339]
### Describe your problem here.

I dont understand how to make the lanes move with the arrow.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by machonessiebaby** [comment]
noteTweenX("NoteMove1", 0, 370, 0.5, cubeInOut)
	noteTweenX("NoteMove2", 1, 510, 0.5, cubeInOut)
	noteTweenX("NoteMove3", 2, 610, 0.5, cubeInOut)
	noteTweenX("NoteMove4", 3, 720, 0.5, cubeInOut)
	noteTweenX("NoteMove5", 4, 410, 0.5, cubeInOut)
	noteTweenX("NoteMove6", 5, 530, 0.5, cubeInOut)
	noteTweenX("NoteMove7", 6, 620, 0.5, cubeInOut)
	noteTweenX("NoteMove8", 7, 710, 0.5, cubeInOut)


notes range 0-7

notemove is the order of the group they move
value 1 
0-7 are notes

0-3 opponent notes
4-7 player notes
if u wana tween Y chaneg noteTweenX replace X with Y 
2nd value is the location x and y are inverted
value 3 is the time
value 4 cubeInOut is the tween type

sorry if i explained badly im tired rn
also the script above puts opponent notes on top of player notes

**Comment by NonCanonBF** [comment]
@machonessiebaby I meant by spinning the lane at which the arrows come from.

**Comment by NonCanonBF** [comment]
like notes coming from right to left

**Comment by machonessiebaby** [comment]
> @machonessiebaby I meant by spinning the lane at which the arrows come from.

thats a sorce code thing

**Comment by machonessiebaby** [comment]
> like notes coming from right to left

not possible in lua

**Comment by machonessiebaby** [comment]
> like notes coming from right to left

nevermind disregard what i said its possible
noteTweenDirection("name", "note", "rotation", "time", "Tween")
