### ISSUE TITLE
Introducing: MIDDLE SCROLL EVENT

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8340]
### What feature do you want to get added on the **base** engine?

I made this from scratch, and i didnt copy

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
[middlescrollevent.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8558880/middlescrollevent.zip)

**Comment by Mastercopper2346** [comment]
@ShadowMario please change this label, (BUT DON'T CLOSE)

**Comment by DEV-idiotXD** [comment]
> @ShadowMario please change this label, (BUT DON'T CLOSE)

i think this should be a pr

**Comment by frantastic24** [comment]
a pr for a lua event?? this isn't what issues is for so yeah this should be closed

**Comment by CrusherMods** [comment]
1. I don't think ShadowMario would add anything softcoded with lua into the base engine
2. Even if this was hardcoded with source it should've gone in a Pull Request

**Comment by cherryiguess** [comment]
we have enough events so this is unnecessary

**Comment by tylerandari12** [comment]
> we have enough events so this is unnecessary 

We don't lol.

But this specific thing is Lua so we don't need it as a hard coded thing...

**Comment by Mastercopper2346** [comment]
idk how to make pr

**Comment by frantastic24** [comment]
Keep it closed

**Comment by Mastercopper2346** [comment]
no

**Comment by CrusherMods** [comment]
> idk how to make pr

Just google it... It's not that hard to open a new tab and type "How to make a Pull Request on Github"

**Comment by MaybeMaru** [comment]
bruh this is a simple af script, if you can do it easily in Lua why add it into the main game
Also if you want to make a pr then program the thing in Haxe at least

**Comment by Mastercopper2346** [comment]
https://github.com/Mastercopper2346/Note-tweens-with-.lua

**Comment by kpsm485** [comment]
oh crap im 13 days early!!! D:
