### ISSUE TITLE
Scroll speed never changing?

### ISSUE THREAD

**Issue by BoomBrine** [ShadowMario/FNF-PsychEngine#8344]
### Describe your problem here.

So I posted a mod a while ago and left it at that, but later I realized that the scroll speed change event hasn't been working for me. I did some experimenting and I couldn't figure it out. Eventually I just downloaded a fresh source code, but even then, the event doesn't do anything AND I noticed that if you try to change the scroll speed normally for the whole song, it still doesn't do anything. I didn't edit anything to my knowledge.

https://user-images.githubusercontent.com/103866692/165224354-554162cc-05e9-46fd-beef-6302a1aee881.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Your scroll speed type is set to constant

**Comment by BoomBrine** [comment]
Where would I change that? That might sound stupid but I don't remember ever turning this on so I'm kind of lost.
