### ISSUE TITLE
[General]: Can someone turn this image into an icon? (the head lol)

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#8345]
### What is your question?

![xd](https://user-images.githubusercontent.com/74252758/165313803-465638b3-b85d-469b-b812-8dbb87f0647f.jpg)
turn rush e guy's head into an icon. im using it for a RUSH E mod. also include a defeat icon (which is a jealous guy)

**Comment by cherryiguess** [comment]
do it yourself

**Comment by acap09** [comment]
> do it yourself

im bad lol

**Comment by Stilic** [comment]
shut up
