### ISSUE TITLE
I need help with the color thing for the credits

### ISSUE THREAD

**Issue by SpringProdAlt** [ShadowMario/FNF-PsychEngine#8348]
### Describe your problem here.

I don't know how to work with the color codes in the credits.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

A lot of things

**Comment by CrunchBar41** [comment]
They are just hex codes so here's a site that can help you with that: https://www.color-hex.com/
