### ISSUE TITLE
The character is black 

### ISSUE THREAD

**Issue by AnFnfModmaker** [ShadowMario/FNF-PsychEngine#8349]
### Describe your bug here.

Idk if its the png is bugeed
 but when i click in load image the character just becomes black 
![image](https://user-images.githubusercontent.com/99932351/165387214-195f748f-2912-4758-9b34-9232b8f586e1.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
pc issue

**Comment by AnFnfModmaker** [comment]
> pc issue

a?

**Comment by frantastic24** [comment]
then it's your file, why report it here

**Comment by AnFnfModmaker** [comment]
> then it's your file, why report it here

because the png is working on others things like discord, but the png is not working on fnf

**Comment by frantastic24** [comment]
You just said it wasn't working here?? Which one is it? If it shows up as a black box then lower the resolution because your PC can't take it

**Comment by silvashp** [comment]
issue: the character is black 💀

**Comment by AnFnfModmaker** [comment]
> issue: the character is black 💀

💀

**Comment by AnFnfModmaker** [comment]
> You just said it wasn't working here?? Which one is it? If it shows up as a black box then lower the resolution because your PC can't take it

yeah i think my pc is not loading it, idk why, because i used just a single sprite to make it, but, yeah.
