### ISSUE TITLE
yep

### ISSUE THREAD

**Issue by 616-com** [ShadowMario/FNF-PsychEngine#8350]
### Describe your bug here.

i try to compile psych engine but says you need a project but i got the project.xml

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i edite

**Comment by frantastic24** [comment]
Probably not running the command from the source folder

**Comment by SnakDev** [comment]
and you need to keep project.xml open id you are building from cmd or powershell yes, it's pretty stupid

**Comment by frantastic24** [comment]
No??
