### ISSUE TITLE
How to do I make a menu like vs Imposter? (Source/Lua)

### ISSUE THREAD

**Issue by EasyTaleNickOfficial** [ShadowMario/FNF-PsychEngine#8352]
### What is your question?

How do I make a menu like this? 
![image](https://user-images.githubusercontent.com/99566839/165198708-6a82b4a0-03a0-42c3-96bf-bc20760fe857.png)
Source

**Comment by DEV-idiotXD** [comment]
just learn how to add clickable buttons in haxe then change the menu code lol
