### ISSUE TITLE
How would I replace the intro text with a video instead?

### ISSUE THREAD

**Issue by CrunchBar41** [ShadowMario/FNF-PsychEngine#8353]
### Describe your problem here.

I would like to replace the intro text, or at least some of it with a video cutscene. Is it possible in Psych?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Changed most of the States to be a different background and different music.

**Comment by Steve35117** [comment]
switch(sickBeats)
case 1:
(new FlxVideo().start('name'));

**Comment by CrunchBar41** [comment]
![image](https://user-images.githubusercontent.com/95093250/165625038-86094a2a-3d1f-4312-b5e1-b3b4ce3adfe4.png)
I'm not exactly sure where to go from there, as I placed that but now I get those two messages.

**Comment by tylerandari12** [comment]
(new FlxVideo('name').start());

I'm no source builder but I think it needs to go like this...

**Comment by CrunchBar41** [comment]
Seemed to get rid of the Not enough arguments line, but the field start still remains. No clue how to fix it, and tried using the code in Playstate as well to see if that works but even though I have all the brackets, it says there are brackets missing. I'm a beginner coder so I'm just a bit confused as to why this is happening.

**Comment by Steve35117** [comment]
> (new FlxVideo('name').start());
> 
> I'm no source builder but I think it needs to go like this...

oh yeah thx
