### ISSUE TITLE
How to make the arrows' lane go from right to left.

### ISSUE THREAD

**Issue by NonCanonBF** [ShadowMario/FNF-PsychEngine#8354]
### Describe your problem here.

I am trying to do a mod chart and I don't know how to make the arrows that are coming from down to up, go from left to right.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by silvashp** [comment]
you mean sidescroll?

**Comment by FNaS2ToySonic** [comment]
Make .lua script and paste this:

function onUpdate()
    songPos = getSongPosition()
    for n = 0,1 do
        setPropertyFromGroup("strumLineNotes", n+4, "x", 100)
        setPropertyFromGroup("strumLineNotes", 4, "y", 100)
        setPropertyFromGroup("strumLineNotes", 5, "y", 250)
    end
    for h = 2,3 do
        setPropertyFromGroup("strumLineNotes", h+4, "x", 100)
        setPropertyFromGroup("strumLineNotes", 6, "y", 400)
        setPropertyFromGroup("strumLineNotes", 7, "y", 550)
    end

    setPropertyFromGroup("strumLineNotes", 0, "x", 10000)
    setPropertyFromGroup("strumLineNotes", 1, "x", 2020)
    setPropertyFromGroup("strumLineNotes", 2, "x", 3040)
    setPropertyFromGroup("strumLineNotes", 3, "x", 46000)

    
    setPropertyFromGroup("strumLineNotes",4,"direction", 180)
    setPropertyFromGroup("strumLineNotes",5,"direction", 180)

    setPropertyFromGroup("strumLineNotes",4,"angle", 90)
    setPropertyFromGroup("strumLineNotes",5,"angle", 90)

    setPropertyFromGroup("strumLineNotes",6,"direction", 180)
    setPropertyFromGroup("strumLineNotes",7,"direction", 180)

    setPropertyFromGroup("strumLineNotes",6,"angle", 90)
    setPropertyFromGroup("strumLineNotes",7,"angle", 90)
end

function onUpdatePost()
    songPos = getSongPosition()
    notesLenght = getProperty("notes.length")
    for i = 0,notesLenght,1 do
        songPos = getSongPosition()
        setPropertyFromGroup("notes",i,"angle", 90)
    end
end

**Comment by FNaS2ToySonic** [comment]
> Make .lua script and paste this: (its from right to left)
> 
> function onUpdate() songPos = getSongPosition() for n = 0,1 do setPropertyFromGroup("strumLineNotes", n+4, "x", 100) setPropertyFromGroup("strumLineNotes", 4, "y", 100) setPropertyFromGroup("strumLineNotes", 5, "y", 250) end for h = 2,3 do setPropertyFromGroup("strumLineNotes", h+4, "x", 100) setPropertyFromGroup("strumLineNotes", 6, "y", 400) setPropertyFromGroup("strumLineNotes", 7, "y", 550) end
> 
> ```
> setPropertyFromGroup("strumLineNotes", 0, "x", 10000)
> setPropertyFromGroup("strumLineNotes", 1, "x", 2020)
> setPropertyFromGroup("strumLineNotes", 2, "x", 3040)
> setPropertyFromGroup("strumLineNotes", 3, "x", 46000)
> 
> 
> setPropertyFromGroup("strumLineNotes",4,"direction", 180)
> setPropertyFromGroup("strumLineNotes",5,"direction", 180)
> 
> setPropertyFromGroup("strumLineNotes",4,"angle", 90)
> setPropertyFromGroup("strumLineNotes",5,"angle", 90)
> 
> setPropertyFromGroup("strumLineNotes",6,"direction", 180)
> setPropertyFromGroup("strumLineNotes",7,"direction", 180)
> 
> setPropertyFromGroup("strumLineNotes",6,"angle", 90)
> setPropertyFromGroup("strumLineNotes",7,"angle", 90)
> ```
> 
> end
> 
> function onUpdatePost() songPos = getSongPosition() notesLenght = getProperty("notes.length") for i = 0,notesLenght,1 do songPos = getSongPosition() setPropertyFromGroup("notes",i,"angle", 90) end end

From left to right version:

```
function onUpdate()
    songPos = getSongPosition()
    for n = 0,1 do
        setPropertyFromGroup("strumLineNotes", n+4, "x", 1100)
        setPropertyFromGroup("strumLineNotes", 4, "y", 550)
        setPropertyFromGroup("strumLineNotes", 5, "y", 400)
    end
    for h = 2,3 do
        setPropertyFromGroup("strumLineNotes", h+4, "x", 1100)
        setPropertyFromGroup("strumLineNotes", 6, "y", 250)
        setPropertyFromGroup("strumLineNotes", 7, "y", 100)
    end

    setPropertyFromGroup("strumLineNotes", 0, "x", 10000)
    setPropertyFromGroup("strumLineNotes", 1, "x", 2020)
    setPropertyFromGroup("strumLineNotes", 2, "x", 3040)
    setPropertyFromGroup("strumLineNotes", 3, "x", 46000)

    
    setPropertyFromGroup("strumLineNotes",4,"direction", 360)
    setPropertyFromGroup("strumLineNotes",5,"direction", 360)

    setPropertyFromGroup("strumLineNotes",4,"angle", 270)
    setPropertyFromGroup("strumLineNotes",5,"angle", 270)

    setPropertyFromGroup("strumLineNotes",6,"direction", 360)
    setPropertyFromGroup("strumLineNotes",7,"direction", 360)

    setPropertyFromGroup("strumLineNotes",6,"angle", 270)
    setPropertyFromGroup("strumLineNotes",7,"angle", 270)
end

function onUpdatePost()
    songPos = getSongPosition()
    notesLenght = getProperty("notes.length")
    for i = 0,notesLenght,1 do
        songPos = getSongPosition()
        setPropertyFromGroup("notes",i,"angle", 270)
    end
end
```

**Comment by NonCanonBF** [comment]
i cant thatnk you enough
