### ISSUE TITLE
Variable for current hit combo

### ISSUE THREAD

**Issue by StarryTS** [ShadowMario/FNF-PsychEngine#8355]
### What feature do you want to get added on the **base** engine?

I know the engine currently has a hit variable that counts how many hits you get on a song, but a variable for your _current_ combo seems like a cool idea.

Say you got a combo of 100, 1000, etc. Cool, you made it. However, if there was a variable that counts your current combo, you could code in events that trigger from your combo via Lua.

I think events like those are what really give that extra bit of entertainment or excitement, a cheer of "You made it!" as, say, BF's anim changes to bust cooler poses.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons. IDK, everybody is putting that down and I don't know how this part works because I'm dumb.

**Comment by frantastic24** [comment]
you can already do that

**Comment by StarryTS** [comment]
Okay, but where

![gameplayVariables](https://user-images.githubusercontent.com/83148927/165426816-81cc5962-69b5-44b8-ad76-c81f9ce0e25e.png)

**Comment by frantastic24** [comment]
`getProperty('combo')`

**Comment by StarryTS** [comment]
Well what d'you know, you learn something new every day
Thanks a lot for telling me

**Comment by frantastic24** [comment]
getProperty can do funny things!!

**Comment by StarryTS** [comment]
True, I always have to find out what getProperty CAN get because I can't find anywhere in the wiki that specifies

**Comment by frantastic24** [comment]
you should read source files for that, documenting them is just too much work

**Comment by LuckyMist8** [comment]
So How Would I Use getProperty('combo') To Trigger Events?

Like If The Combo Is A 10 Streak, Trigger Screen Shake
How Do I Write That As Lua Script?

**Comment by CrusherNotDrip** [comment]
> So How Would I Use getProperty('combo') To Trigger Events?
> 
> 
> 
> Like If The Combo Is A 10 Streak, Trigger Screen Shake
> 
> How Do I Write That As Lua Script?

`if getProperty('combo') == 10 then`

**Comment by LuckyMist8** [comment]
> > So How Would I Use getProperty('combo') To Trigger Events?
> > Like If The Combo Is A 10 Streak, Trigger Screen Shake
> > How Do I Write That As Lua Script?
> 
> `if getProperty('combo') == 10 then`

Under What Function?
onCreate, onCreatePost, onUpdate, onUpdatePost etc. ?

My Current Script That Won't Work Is This : 
`function onCreatePost()`
`      if getProperty('combo') == 10 then`
`         makeAnimatedLuaSprite('dadflames', 'starLightning', 75, 0)`
`			setObjectCamera('dadflames', 'camHUD')`
`			scaleObject('dadflames', 0.5, 0.5)`
`			addAnimationByPrefix('dadflames', 'flames', 'STAR LIGHTNING', 24, true)`
`			addLuaSprite('dadflames', false)`
`			objectPlayAnimation('dadflames', 'flames', true)`
`		end `

It Doesn't Trigger When I Hit 10 Combo

**Comment by LuckyMist8** [comment]
> > So How Would I Use getProperty('combo') To Trigger Events?
> > Like If The Combo Is A 10 Streak, Trigger Screen Shake
> > How Do I Write That As Lua Script?
> 
> `if getProperty('combo') == 10 then`

For Future Reference, `if getProperty('combo') == 10 then` Works Under The Function `function onUpdatePost()` For Me Anyway

Thanks Crusher
