### ISSUE TITLE
IntroText.txt doesn't load in ModPacks

### ISSUE THREAD

**Issue by Daboss7173** [ShadowMario/FNF-PsychEngine#8357]
### Describe your bug here.

Any modpack with an "introText.txt" in the modpack (in the /data directory) currently doesn't load at all. Please fix to allow for intro text editing in modpacks.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I haven't changed any source code.

**Comment by keanu64github** [comment]
It has to be the highest priority enabled mod for it to work.
