### ISSUE TITLE
How do I make the opponent play an animation when bf hits a note?

### ISSUE THREAD

**Issue by supermase120** [ShadowMario/FNF-PsychEngine#8358]
### Describe your problem here.

I am trying to make a bullet note mechanic and I want to make the opponent play a shooting animation like hank accelerant did.

I made bf play has dodging animaton when he hits a bullet note, but I am having trouble with the opponents animation

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Use the same function but with `'dad'` instead

**Comment by keanu64github** [comment]
opponentNoteHit

**Comment by frantastic24** [comment]
> bf hits a note

**Comment by BocaIoachim** [comment]
triggerEvent('Play Animation', '< your animation name >', 'dad')

**Comment by AdmiralUsername** [comment]
function goodNoteHit(noteType)
    if noteType == note:String then
        characterPlayAnim('dad', anim:String, forced:Bool = false);
    end
end

**Comment by Shelvsk** [comment]
```
function goodNoteHit(noteType)
    if noteType == 'Your_Note' then
        characterPlayAnim('dad', 'Your_Anim', false);
    end
end
```

**Comment by Lorekeeper49** [comment]
> ```
> function goodNoteHit(noteType)
>     if noteType == 'Your_Note' then
>         characterPlayAnim('dad', 'Your_Anim', false);
>     end
> end
> ```

You'd actually want to change false to true
