### ISSUE TITLE
...

### ISSUE THREAD

**Issue by 616-com** [ShadowMario/FNF-PsychEngine#8360]
i try to make a psych engine mod but when i put a song with the data and the song in the folders the game crashes and i try with gamebanana and github (i think same) edition and it crashes

**Comment by frantastic24** [comment]
Your title doesn't explain the problem, "doesn't work" isn't an explanation

**Comment by 616-com** [comment]
how i delete this

**Comment by frantastic24** [comment]
okay but you still didn't show what the error is, if there is any, or what files you're using

**Comment by MaybeMaru** [comment]
- It doesnt work
- Could you give more info?
- *Adds suspense dots*
