### ISSUE TITLE
Help: Death anims

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#8361]
### Describe your bug here.

So i made my character, wrote the script and all, but the death animation doesn't work. Help?
Script:
```
function onCreate()
	setPropertyFromClass('GameOverSubstate', 'characterName', 'tailsdead');
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

mods folder

**Comment by frantastic24** [comment]
Provide files and explain what doesn't work

**Comment by CheesecakeForever** [comment]
It just plays the animation of BF, not my animation.
[tailsdead.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8575640/tailsdead.txt)
there, the .json of the character and idk if i need to send anything more

**Comment by frantastic24** [comment]
if the character doesn't change it means something in your script is causing problems or the character name is wrong
send the full script you're using, and make sure your files are in the right folder and have the correct names

**Comment by CheesecakeForever** [comment]
script:
```
function onCreatePost()
    setProperty('gf.alpha', 0);
end

function onCreate()
	setPropertyFromClass('GameOverSubstate', 'characterName', 'tailsdead');
end
```

**Comment by CheesecakeForever** [comment]
The character is in the mods/characters folder.

**Comment by SnakDev** [comment]
you need to use .lua not .txt
