### ISSUE TITLE
source code line to lua if possible

### ISSUE THREAD

**Issue by AntCrem** [ShadowMario/FNF-PsychEngine#8362]
### Describe your problem here.

does anyone know how to make this line of code from within source code work in a lua script? (from Vs Void)

				new FlxTimer().start(3, function(tmr:FlxTimer)
					{
						if(spacerocks.y == -65) FlxTween.tween(spacerocks, {y: -30}, 2.9, 
							{ease: FlxEase.quadInOut});
						else  FlxTween.tween(spacerocks, {y: -65}, 2.9, 
							{ease: FlxEase.quadInOut});
					}, 0);

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nu

**Comment by frantastic24** [comment]
```lua
     runTimer('rocks', 3, 0)

function onTimerCompleted(tag)
     if tag == 'rocks' then
          if getProperty('spacerocks.y') == -65 then
               doTweenY('rocksY', 'spacerocks', -30, 2.9, 'quadInOut')
          else
               doTweenY('rocksY', 'spacerocks', -65, 2.9, 'quadInOut')
          end
     end
end
```

**Comment by AntCrem** [comment]
holy moly thanks homie
