### ISSUE TITLE
in the character editor there should be an option to put a "beat" on certain frames

### ISSUE THREAD

**Issue by Slimquickhunt** [ShadowMario/FNF-PsychEngine#8365]
### What feature do you want to get added on the **base** engine?

in the character editor there should be an option to put a "beat" on certain frames as to make it on that frame a beat gets hit

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tylerandari12** [comment]
What exactly is a "beat"?

**Comment by Slimquickhunt** [comment]
so you know when a character puts there head down on there idle I'm saying there should be a feature where you can pick the frame or frames it happens on

**Comment by frantastic24** [comment]
that means changing how beats are calculated for a feature with little use

**Comment by Slimquickhunt** [comment]
> that means changing how beats are calculated for a feature with little use

thats not exactly what it would do for example for the people in front player and opponent there idle animation plays once every other beat what I'm saying is that you could put the frame on wich the animations starts each beat or other beat like how GF head hits every beat it wouldn't change how it was calculated because it doesn't change anything besides an animation

**Comment by frantastic24** [comment]
I barely got that but isn't that what indices are for

**Comment by tylerandari12** [comment]
`character.danceEveryNumBeats`?

**Comment by DefNotDylan** [comment]
You could probably do this using a LUA event. Either using **characterDance('dad/boyfriend/gf')**, or **characterPlayAnim('dad/boyfriend/gf', 'idleanimationname', true)** in a LUA event, and then placing the event wherever you want a beat in the chart editor. I haven't tested it yet, so I'm not sure if it would work. One main problem I could think of is that the normal idle animation would play in the middle of the new beat, but I'm not sure.
