### ISSUE TITLE
LUA extra menus and options in game over in lua

### ISSUE THREAD

**Issue by Slimquickhunt** [ShadowMario/FNF-PsychEngine#8366]
### Describe your problem here.

how to make in LUA extra menus and options in game over, also extra thing Is there a possible way to make checkpoints in songs (like if you have a 10 minute song or song that gets really hard at one point you can add a checkpoint)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by tylerandari12** [comment]
Lua not LUA
