### ISSUE TITLE
How do I move the Game Over Camera with LUA

### ISSUE THREAD

**Issue by Purpleslimeboi** [ShadowMario/FNF-PsychEngine#8367]
### What is your question?

I'm re-asking this question because last time I asked, the post turned into a 404.
I added a custom death sprite, but when I die, the camera goes wayyy to far from the sprite. I'm just asking if I can move the camera so that it focuses on the sprite.
Somebody asked me how I coded in the sprites, I just stole the code from the Example Scripts in the Wiki. How I added them: I just altered the code and put it in the PsychEngine/Mods/Scripts folder. I don't see any X or Y values. If I'm doing it wrong, can somebody tell me the proper way to add the Death Sprites in?

**Comment by DanyG7** [comment]
Those are configured with the Character editor

**Comment by Purpleslimeboi** [comment]
> Those are configured with the Character editor
The sprites are already aligned, the camera just goes away from where it needs to be
