### ISSUE TITLE
Changing name engine

### ISSUE THREAD

**Issue by powerful29** [ShadowMario/FNF-PsychEngine#8368]
### Describe your problem here.

Listen this not source code or a build
I want to change name engine it means psychic engine to Dave or bambi engine
soo can any body tell me the file thats inside it name eninge to change it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

It's not build OR SOURCE CODE OR LUE

**Comment by CrusherMods** [comment]
1. You dont edit the app name with a file
2.
```
function onCreate() --if this doesn't work use onUpdate(elapsed)
    setPropertyFromClass("openfl.Lib", "application.window.title", "Friday Night Funkin': VS Roboscrew")
end
```

**Comment by CrusherMods** [comment]
try this in a lua script
```
function onUpdate(elapsed)
    setPropertyFromClass("openfl.Lib", "application.window.title", "Dave Engine")
end
```

**Comment by keanu64github** [comment]
do onCreatePost instead of onUpdate cuz it wont waste as much memory

**Comment by CrusherMods** [comment]
> do onCreatePost instead of onUpdate cuz it wont waste as much memory

true

**Comment by powerful29** [comment]
> do onCreatePost instead of onUpdate cuz it wont waste as much memory

How?

**Comment by powerful29** [comment]
> try this in a lua script
> 
> ```
> function onCreatePost()
>     setPropertyFromClass("openfl.Lib", "application.window.title", "Dave Engine")
> end
> ```

Where should i put it?

**Comment by powerful29** [comment]
WHERE THE F### SHOULD I PUT IT

**Comment by CrusherMods** [comment]
> WHERE THE F### SHOULD I PUT IT

in a lua script

**Comment by CrusherMods** [comment]
> > > WHERE THE F### SHOULD I PUT IT
> > 
> > 
> > in a lua script
> 
> SHOULD I PLACE IT IN MODS/SCRIPTS?!

yes

**Comment by powerful29** [comment]
> 

Fok it dosn't work

**Comment by CrusherNotDrip** [comment]
> > > 
> 
> > 
> 
> > Fok it dosn't work
> 
> 
> 
> underaged mother fucker, it is way easier to do this on source code :rofl:

so true

**Comment by void0851exe** [comment]
but how to do it without source????
