### ISSUE TITLE
Event Songs with Lua

### ISSUE THREAD

**Issue by Shelvsk** [ShadowMario/FNF-PsychEngine#8369]
### Describe your problem here.

im trying put events with a script an i put this on one part of music, but dont work's, what did i make wrong?
```
function onBeatHit()
    if curBeat == 208 then
        triggerEvent('Add Camera Zoom')
    end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
You didn't type any values

**Comment by Shelvsk** [comment]
the "Add Camera Zoom" event has the values ​​"0.015" and "0.03" as default, even if you don't put anything, so I'm sure it's not that, and also because I tried to put values ​​and it still didn't work

**Comment by frantastic24** [comment]
Are notes being hit before, during or after the event is triggered and do you have camera zoom I turned on?

**Comment by machonessiebaby** [comment]
use this instead of triggering an event that only works with shake and screen pos

    setProperty('camGame.zoom', 5)
    doTweenZoom('begin', 'camGame', '6', 3, 'quadOut')

5 = zoom amount

6 = zoom out
3 = time

**Comment by Shelvsk** [comment]
thanks

**Comment by frantastic24** [comment]
You can close this
