### ISSUE TITLE
Error C2177: constant too big

### ISSUE THREAD

**Issue by LrgeAlvaro8882** [ShadowMario/FNF-PsychEngine#837]
### Describe your problem here.

I've got an error when compiling.
Everything goes right until it stops and says:
./src/PlayState.cpp(5683): error C2177: constant too big
How do I fix it?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a lot of stuff inside PlayState.hx and it just doesn't compile.

**Comment by ShadowMario** [comment]
You added a variable that is too big.

**Comment by ShadowMario** [comment]
So... nothing to ask? Alright.
