### ISSUE TITLE
How do i make the notes go like this.

### ISSUE THREAD

**Issue by NonCanonBF** [ShadowMario/FNF-PsychEngine#8370]
### Describe your problem here.

I trying to mod chart, and I don't understand how to make the notes that come up go in a certain direction. This is my concept of the mod chart. I am also making it so that it can be triggered by using onStepHit()
![Screenshot 2022-04-27 173147](https://user-images.githubusercontent.com/92188076/165650432-f8649d5f-9fe4-49a2-a00f-dbce56c455fd.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by NonCanonBF** [comment]
the arrows indicate which way the notes come from.

**Comment by FNaS2ToySonic** [comment]
function onUpdate(elapsed)
	songPos = getSongPosition()
	local currentBeat = (songPos/5000)*(curBpm/70)
	local currentBeat2 = (songPos/500)*(curBpm/70)

	--setProperty('glitch.x', -800 + 200 * math.sin((currentBeat+2*0.24) *math.pi)) delete "--" to make wavy bg
    --setProperty('glitch.y', -300 + 100 * math.sin((currentBeat+2*0.24) *math.pi))
    --setProperty('glitch.scale.y', 1.5 + 0.5 * math.sin((currentBeat+0*0.24) *math.pi))
    --setProperty('glitch.angle', 10 - 10 * math.sin((currentBeat+0*0.24) *math.pi))

    noteTweenX('defaultPlayerStrumX0', 4, 600 + 300 * math.tan((currentBeat+0 *0.25) * math.pi), 0.00001, 'quadInOut')
    noteTweenX('defaultPlayerStrumX1', 5, 600 + 300 * math.tan((currentBeat+0 *0.25) * math.pi), 0.00001, 'quadInOut')
    noteTweenX('defaultPlayerStrumX2', 6, 600 - 300 * math.tan((currentBeat+4 *0.25) * math.pi), 0.00001, 'quadInOut')
    noteTweenX('defaultPlayerStrumX3', 7, 600 - 300 * math.tan((currentBeat+4 *0.25) * math.pi), 0.00001, 'quadInOut')

    setPropertyFromGroup("strumLineNotes", 4, "y", 100)
    setPropertyFromGroup("strumLineNotes", 5, "y", 220)
    setPropertyFromGroup("strumLineNotes", 6, "y", 440)
    setPropertyFromGroup("strumLineNotes", 7, "y", 560)

    setPropertyFromGroup("strumLineNotes", 0, "x", 10000)
    setPropertyFromGroup("strumLineNotes", 1, "x", 2020)
    setPropertyFromGroup("strumLineNotes", 2, "x", 3040)
    setPropertyFromGroup("strumLineNotes", 3, "x", 46000)

    setPropertyFromGroup("strumLineNotes",4,"direction", 360)
    setPropertyFromGroup("strumLineNotes",5,"direction", 360)

    setPropertyFromGroup("strumLineNotes",6,"direction", 180)
    setPropertyFromGroup("strumLineNotes",7,"direction", 180)
end

**Comment by FNaS2ToySonic** [comment]
function onUpdate(elapsed)
	songPos = getSongPosition()
	local currentBeat = (songPos/5000)*(curBpm/30)
	local currentBeat2 = (songPos/500)*(curBpm/30)

	--setProperty('glitch.x', -800 + 200 * math.sin((currentBeat+2*0.24) *math.pi)) delete "--" to make wavy bg
    --setProperty('glitch.y', -300 + 100 * math.sin((currentBeat+2*0.24) *math.pi))
    --setProperty('glitch.scale.y', 1.5 + 0.5 * math.sin((currentBeat+0*0.24) *math.pi))
    --setProperty('glitch.angle', 10 - 10 * math.sin((currentBeat+0*0.24) *math.pi))

    noteTweenX('defaultPlayerStrumX0', 4, 600 + 300 * math.tan((currentBeat+0 *0.25) * math.pi), 0.00001, 'quadInOut')
    noteTweenX('defaultPlayerStrumX1', 5, 600 + 300 * math.tan((currentBeat+0 *0.25) * math.pi), 0.00001, 'quadInOut')
    noteTweenX('defaultPlayerStrumX2', 6, 600 - 300 * math.tan((currentBeat+4 *0.25) * math.pi), 0.00001, 'quadInOut')
    noteTweenX('defaultPlayerStrumX3', 7, 600 - 300 * math.tan((currentBeat+4 *0.25) * math.pi), 0.00001, 'quadInOut')

    setPropertyFromGroup("strumLineNotes", 4, "y", 100)
    setPropertyFromGroup("strumLineNotes", 5, "y", 220)
    setPropertyFromGroup("strumLineNotes", 6, "y", 440)
    setPropertyFromGroup("strumLineNotes", 7, "y", 560)

    setPropertyFromGroup("strumLineNotes", 0, "x", 10000)
    setPropertyFromGroup("strumLineNotes", 1, "x", 2020)
    setPropertyFromGroup("strumLineNotes", 2, "x", 3040)
    setPropertyFromGroup("strumLineNotes", 3, "x", 46000)

    setPropertyFromGroup("strumLineNotes",4,"direction", 360)
    setPropertyFromGroup("strumLineNotes",5,"direction", 360)

    setPropertyFromGroup("strumLineNotes",6,"direction", 180)
    setPropertyFromGroup("strumLineNotes",7,"direction", 180)
end
-- i made something like that, yea it's actuallt onUpdate(elapsed)
