### ISSUE TITLE
lua script not working

### ISSUE THREAD

**Issue by AntCrem** [ShadowMario/FNF-PsychEngine#8371]
### What is your question?

So I have a lua script that's supposed to make a BG sprite slowly move up and down but has no effect. I'm most likely being a goofy goober and missing something.

here is the code

runTimer('spacerocks', 3, 0);

function onTimerCompleted(tag)
     if tag == 'spacerocks' then
          if getProperty('spacerocksY') == -65 then
               doTweenY('spacerocksY', 'spacerocks', -30, 2.9, 'quadInOut')
          else
               doTweenY('spacerocksY', 'spacerocks', -65, 2.9, 'quadInOut')
          end
     end
end

**Comment by frantastic24** [comment]
you didn't put runTimer under any function

**Comment by AntCrem** [comment]
I just tried that but still didn't work

**Comment by frantastic24** [comment]
what did you try

**Comment by frantastic24** [comment]
i see what's also wrong
why is it `getProperty('spacerocksY')` instead of `getProperty('spacerocks.y') `

**Comment by Lorekeeper49** [comment]
Making runTimer have a loop amount of 0 won't work, the loop amount must be 1 or higher for it to work, I found this out the hard way (as in my game crashed when it I tried)
Now that I think about it, that doesn't really make sense, the premade dialogue script runs a timer without loops defined and that works

**Comment by frantastic24** [comment]
okay the tag in onTimerCompleted is also wrong

> Making runTimer have a loop amount of 0 won't work, the loop amount must be 1 or higher for it to work

no it works just fine

> runs a timer without loops defined

that means loop is set to 1
