### ISSUE TITLE
what is going on in character editor? when i load an image not from the basegame, it doesnt work

### ISSUE THREAD

**Issue by RamenDoodleSoup** [ShadowMario/FNF-PsychEngine#8372]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/104543302/165668312-dd2a1c7e-4efb-460b-8ee2-4b74d99c1686.png)
whenever i load an image that isnt from the basegame, it doesnt load.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by AntCrem** [comment]
If there is still the old character JSON you should change the names within that file maybe?

**Comment by RamenDoodleSoup** [comment]
> If there is still the old character JSON you should change the names within that file maybe?

oh i didn't think you needed a .json to add a new character, ill try that

**Comment by RamenDoodleSoup** [comment]
uh...
![image](https://user-images.githubusercontent.com/104543302/165670327-d6ba477b-45c2-4a0d-adbc-f2e5b75a7fff.png)

**Comment by AntCrem** [comment]
Hmm If you can send me the files I can try to fix it for you

**Comment by RamenDoodleSoup** [comment]
> Hmm If you can send me the files I can try to fix it for you
ok sure here ya go
[smnio.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8579299/smnio.zip)

**Comment by AntCrem** [comment]
> > Hmm If you can send me the files I can try to fix it for you
> 
> ok sure here ya go [smnio.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8579299/smnio.zip)

alrighty thanks I shall work on it now hang tight

**Comment by RamenDoodleSoup** [comment]
alright thanks :>

**Comment by AntCrem** [comment]
[SMINOfixy.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8579379/SMINOfixy.zip)

See if this works

**Comment by RamenDoodleSoup** [comment]
alright thanks, it works now! quick question before i close this, what did you do to make it work

**Comment by AntCrem** [comment]
I used an older version of the engine and made everything again from scratch

**Comment by RamenDoodleSoup** [comment]
oh ok
