### ISSUE TITLE
Why aren't the assets being found in the new library I made?

### ISSUE THREAD

**Issue by KutikiPlayz** [ShadowMario/FNF-PsychEngine#8373]
### What is your question?

Basically I made a new folder for assets for a specific thing, and as far as I'm aware I have it all set up properly in project.xml, basically the same way all the week2 through 6 folders are in there, and yet, when I try to get assets from said folder, it can't find them and says they don't exist.

![Screenshot (1378)](https://user-images.githubusercontent.com/73810550/165724363-131ff6c6-65a3-4502-8abe-0d9aa6e92c32.png)

Why's this happening?
What's the difference between the folder I added and the other folders already there?
I've been searching everywhere for an answer and have yet to find anything

**Comment by CrusherMods** [comment]
What exactly do you plan on adding with the assets?
and check that your images are put in assets/bendy/images assets/cup/images assets/sans/images

**Comment by KutikiPlayz** [comment]
> What exactly do you plan on adding with the assets? and check that your images are put in assets/bendy/images assets/cup/images assets/sans/images

basically I'm just recreating indie cross for the purpose of learning cool shit that the mod does and also to test my coding skills with haxe
and they are indeed in the images folder of each one
