### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by enderfunkin** [ShadowMario/FNF-PsychEngine#8375]
### Describe your problem here.

![2022-04-28_16-48-35](https://user-images.githubusercontent.com/78095941/165736865-87e03e5e-be9f-448d-9e9f-67aab5d9af7b.png)
I did everything according to the tutorial, but it turned out to be bullshit

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Missing visual studio components
