### ISSUE TITLE
how do i make the options state play the pause music (source)

### ISSUE THREAD

**Issue by SAB236YT** [ShadowMario/FNF-PsychEngine#8376]
### What is your question?

how do i make the options state play the pause music (source)?

**Comment by CrunchBar41** [comment]
In MainMenuState
case 'options':
	LoadingState.loadAndSwitchState(new options.OptionsState());
	FlxG.sound.playMusic(Paths.music('songname'), 1, true);

**Comment by keanu64github** [comment]
Maybe this?
case 'options':
LoadingState.loadAndSwitchState(new options.OptionsState());
FlxG.sound.playMusic(Paths.music(ClientPrefs.pauseMusic), 1, true);

**Comment by SAB236YT** [comment]
yea like that but i put it literally in the OptionState.hx file but is playing null

**Comment by SAB236YT** [comment]
and in the menustate i put FlxG.sound.music.volume = 0;
