### ISSUE TITLE
 fatal error C1083!

### ISSUE THREAD

**Issue by salumod** [ShadowMario/FNF-PsychEngine#8379]
### Describe your problem here.

source/Achievements.hx:157: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/MainMenuState.hx:66: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:319: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/CharacterEditorState.hx:94: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/DialogueCharacterEditorState.hx:87: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
F:/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:145: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
F:/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:180: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
F:/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:221: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
F:/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:515: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
F:/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:483: characters 37-56 : Warning : Std.is is deprecated. Use Std.isOfType instead.
F:/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:484: characters 31-47 : Warning : Std.is is deprecated. Use Std.isOfType instead.
F:/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:646: characters 10-42 : Warning : Std.is is deprecated. Use Std.isOfType instead.
source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

Compiling group: haxe
cl.exe -Iinclude -IF:/haxe/haxe/lib/discord_rpc/git/linc/ -IF:/haxe/haxe/lib/linc_luajit/git//linc/ -I D:/FNF-PsychEngine-0.5.2h/source/vlc/cpp/include/ -I D:/FNF-PsychEngine-0.5.2h/source/vlc/cpp/src/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdD:\FNF-PsychEngine-0.5.2h\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IF:/haxe/haxe/lib/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/__boot__.cpp
 - src/openfl/display/GraphicsShaderFill.cpp  [haxe,release]
 - src/discord_rpc/DiscordRpc.cpp
 - src/haxe/ds/GenericCell_hscript_Token.cpp
 - src/openfl/display3D/_internal/_AGALConverter/SourceRegister.cpp  [haxe,release]
 - src/lime/system/JNIMethod.cpp  [haxe,release]
 - src/lime/media/AudioManager.cpp  [haxe,release]
 - src/flixel/input/gamepad/id/OUYAID.cpp
 - src/lime/_internal/format/PNG.cpp  [haxe,release]
 - src/flixel/addons/ui/AnchorPoint.cpp
Error: DiscordRpc.cpp
**F:/haxe/haxe/lib/discord_rpc/git/linc/linc_discord_rpc.h(7): fatal error C1083: 无法打开包括文件: “../lib/discord-rpc/include/discord-rpc.h”: No such file or directory**

 - src/flixel/addons/ui/interfaces/IFlxUIButton.cpp

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by Theoyeah** [comment]
you didn't install something

**Comment by zacksgamerz** [comment]
install the discord rpc lib

**Comment by salumod** [comment]
I've installed it

**Comment by salumod** [comment]
> 安装不和谐的 rpc 库

I've installed it, but I can't open the include file yet

**Comment by salumod** [comment]
> 安装不和谐的 rpc 库

thank you
I reinstalled it and can now compile
