### ISSUE TITLE
Yes, another bg problem

### ISSUE THREAD

**Issue by Sebasyn0se** [ShadowMario/FNF-PsychEngine#838]
### Describe your problem here.

With your help i added the animated characters in the background, but they arent sync with the music. i mean they do their idle dance but too fast, can i change it in lua or i need to change the source code? I tried to change the frames, the animation goes more slow, but it's still out of sync with the music, i just need to change the bpm of the animations i guess. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

**Comment by DEV-idiotXD** [comment]
put the pla anim script in

function onbeathit()

instead of

function onupdate()



@ShadowMario close it

**Comment by ShadowMario** [comment]
> function onbeathit()

Small typo: it has some uppercase letters.
`function onBeatHit()`
This is important because if it's named wrong it won't be executed.
