### ISSUE TITLE
how to make a script work on a specific difficulty

### ISSUE THREAD

**Issue by Epiclol374** [ShadowMario/FNF-PsychEngine#8381]
### Describe your problem here.

help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by Grape-Boy** [comment]
Use the `difficulty` variable.
If the difficulty is Easy, then `difficulty` is 0; if the difficulty is Normal, then `difficulty` is 1; and if the difficulty is Hard, `difficulty` is 2.

So, you could probably make it so the script only works on a specific difficulty by adding this line:
```lua
if difficulty ~= 2 then
    close(false)
end
```

**Comment by keanu64github** [comment]
or a better way is 
`if difficultyName == "your difficulty (for example, Easy)" then
	-- code here
end`

**Comment by Epiclol374** [comment]
Thanks for the help :D
