### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by KitKatGit** [ShadowMario/FNF-PsychEngine#8382]
### Describe your bug here.

I was making a Vs. Whitty Psych Port on 5.1 the other day, then the audio stopped working, all of it; The title music, level songs, the pause menu, etc. I thought it was a bug only with 5.1, so I moved to 5.2h to see if it is different. It was all still muted, the songs are all .ogg files, they've been placed in there respective folders. and I'm genuinely annoyed by this, if you want - you can add me on discord if you'd like to see what I mean. My laptop was not muted either.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only changed sprites, added charts, weeks, music, and a change of title gf's speaker sprite, and bouncing logo

**Comment by Grape-Boy** [comment]
Maybe you pressed 0 ?

**Comment by Lorekeeper49** [comment]
There's literally an official whitty definitive edition on gamebanana that is entirely softcoded into psych engine, you don't need to make this port yourself

**Comment by ManbiDude** [comment]
Maybe You Pressed 0
