### ISSUE TITLE
Long Songs don't work

### ISSUE THREAD

**Issue by Brad2024** [ShadowMario/FNF-PsychEngine#8383]
### Describe your bug here.

Whenever I try to get a song that's longer than 5 minutes to work, then song just crashes before I can finish it. It usually crashes at 4 minutes and 50 seconds of the song, but it can crash earlier or later than that.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, the game is pre-compiled, nothing should be fundementally altered.

**Comment by frantastic24** [comment]
Lower your fps target

**Comment by tylerandari12** [comment]
I have the same problem...

Ima try that...

**Comment by Mastercopper2346** [comment]
idk what u mean.

**Comment by Mastercopper2346** [comment]
i ported qt into pysch engine, and it had censory overload with 5:30 time and termination with a time of 5:18 and i had no problems.

**Comment by tylerandari12** [comment]
> Mastercopper2346

We have poopy computers unlike you lol...

**Comment by Mastercopper2346** [comment]
no it literally takes 4 hours for my pc to compile the source code

**Comment by Mastercopper2346** [comment]
if anything, **MY** pc is slow.

**Comment by AetherLynx** [comment]
set your fps cap to 60
