### ISSUE TITLE
How to add custom achivements to lua

### ISSUE THREAD

**Issue by GamingIQ** [ShadowMario/FNF-PsychEngine#8384]
### What is your question?

I'm trying to add Achievements for my mod and I haven't found any Youtube tutorials only tutorials on source code, so plz tell me how, Thanks!

**Comment by frantastic24** [comment]
You can't

**Comment by GamingIQ** [comment]
but in the folders there's a folder named "Achievements" and I don't know how to use it

**Comment by frantastic24** [comment]
They're not used, there are several other posts clarifying this

**Comment by frantastic24** [comment]
close this
