### ISSUE TITLE
Changing the name of the Application when Quitting a song

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#8385]
### Describe your problem here.

So, I'm trying to add something that when Quitting a Song, the Application Name Changes.

For Example: I have a lua script that changes application name when ENTERING a song:
`function onCreatePost()
    setPropertyFromClass("openfl.Lib", "application.window.title", "Special Engine: " .. songName)
end`

And one when a Song Ends:
`function onEndSong()
    setPropertyFromClass("openfl.Lib", "application.window.title", "Special Engine")
end`

But I don't have a script for when you quit the song. (that is, Pause, then Exit To Menu)

What Function should I insert, this one to be exact:
`function __()
    setPropertyFromClass("openfl.Lib", "application.window.title", "Special Engine")
end`
so when you quit a song, the application name changes?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment]
`onDestroy()`, you don't need onEndSong

**Comment by frantastic24** [comment]
onDestroy does that

**Comment by fnfdemonboi314159** [comment]
ok, got it working. thanks!
