### ISSUE TITLE
openURL() if possible…

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8387]
### What feature do you want to get added on the **base** engine?

If it doesn’t already exist, an `openURL(URL:string)` function would be really useful. Like in the Bob mod when the site is opened when you die…

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ManMaster707** [comment]
It's a cool feature, but it could lead to malicious people using this to open URLs with viruses, malwares...
And I think you can already do that by downloading the site as an .html file and writing `io.open('namehere.html')` in your script.

**Comment by machonessiebaby** [comment]
https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/611

**Comment by cherryiguess** [comment]
no

**Comment by Mastercopper2346** [comment]
good idea

**Comment by tylerandari12** [comment]
> [mayo78/PSYCHDISCUSSIONS#611](https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/611)

Thanks but Im on Lua not source...

**Comment by tylerandari12** [comment]
> no

Why not?

**Comment by tylerandari12** [comment]
> It's a cool feature, but it could lead to malicious people using this to open URLs with viruses, malwares... And I think you can already do that by downloading the site as an .html file and writing `io.open('namehere.html')` in your script.

I dont think big mod creators would do this...
However Ill try your alternative...

**Comment by tylerandari12** [comment]
> > It's a cool feature, but it could lead to malicious people using this to open URLs with viruses, malwares... And I think you can already do that by downloading the site as an .html file and writing `io.open('namehere.html')` in your script.
> 
> I dont think big mod creators would do this... However Ill try your alternative...

I do have one question however...
Where do I put the html?

**Comment by redstonemaster60** [comment]
> I do have one question however... Where do I put the html?

Did you figure out where to put the html? I'm trying this myself and can't find where.
