### ISSUE TITLE
different voices in one difficulty

### ISSUE THREAD

**Issue by bendyloq** [ShadowMario/FNF-PsychEngine#8390]
### What is your question?

my question is if you can, for example, choose the hard difficulty, the voices change than choosing the other difficulties, like Vs Skipper

**Comment by Mastercopper2346** [comment]
#8290

**Comment by Mastercopper2346** [comment]
coincidence, it is exactly 100 issues  before this one.

**Comment by bendyloq** [comment]
I thank you so

**Comment by bacondanger** [comment]
easy. first, you make a new folder in songs and name it whatever (ex: song name purple, a new folder named purple-onlybf). Then go to your json file and scroll to the bottom. Then rename the `"song": "purple"` to `"song": "purple-onlybf"`.
this changes vocals!

(note: you still need the inst and voices file in the folder, this just changes what song to use.)

**Comment by bacondanger** [comment]
wait im late. Oops
