### ISSUE TITLE
Alt section not working

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8393]
### Describe your bug here.

when i try to do alt section is doesnt work but the alt notes do

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i did not.

**Comment by frantastic24** [comment]
Are you trying to do alt sections for bf

**Comment by Lorekeeper49** [comment]
Hate to break it to you, but the option to make a section play the alternate animation only applies for the opponent, you're gonna have to manually place alt animation notes

**Comment by Mastercopper2346** [comment]
bruh

**Comment by Mastercopper2346** [comment]
ill just edit the source code so it can work out.

**Comment by frantastic24** [comment]
Now close this
