### ISSUE TITLE
Text Files and Save Data.

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8395]
### What is your question?

I saw in 0.5.2 there were some features added that let you use save data and load text files to Lua. Any clue how to use this?

![Text and Save](https://user-images.githubusercontent.com/97060639/166100384-a8fe2fcd-631a-4e79-abd5-e65a5bdc3c03.PNG)

Or was it removed?

**Comment by frantastic24** [comment]
#8286

**Comment by tylerandari12** [comment]
Thanks
