### ISSUE TITLE
Opening .txt files without os. and io.

### ISSUE THREAD

**Issue by ManMaster707** [ShadowMario/FNF-PsychEngine#8397]
### Describe your problem here.

I'm trying to get the game to open a .txt file when you die without using `os.`, so I tried using `io.open()` and `io.popen()`, they worked with other types of files, but they didn't work with .txt files, so I'm wondering if there's another way to open those type of files without `os.` and `io.`(the file's name and path are correct)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i just added things trough the "mods" folder.

**Comment by BombasticTom** [comment]
getTextFromFile(name) i think

**Comment by keanu64github** [comment]
yes

**Comment by keanu64github** [comment]
> getTextFromFile(name) i think

yeah

**Comment by ManMaster707** [comment]
> getTextFromFile(name) i think

It doesn't work for me, but if you want more information I wanted a separate .txt file being opened in the user's computer trough a command, like in the documic.txt sonic mod

**Comment by BombasticTom** [comment]
i think you'd need os for that, which is currently unavailable.

you would have to download an action build from actions section of this git repo
