### ISSUE TITLE
resetting keybinds from files

### ISSUE THREAD

**Issue by BarGames** [ShadowMario/FNF-PsychEngine#8402]
### Describe your bug here.

so i made a chart
that took me around the last 3 days 
and today before i finished it i found a cool mod i wanted to try out
and ofc its a dave and bambi mod so i tried setting multiple of my keys to the same one, i saw it didnt work so i decided to do the same on the ui section
basically now i cant play the chart because i cant scroll up and down in the menu or really anywhere
i tried deleted controls.sol and stuff and its still broken
i would really be happy if i can fix this because i wasted a long time on it
thanks

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i just added characters, a background, a song and made a chart

**Comment by frantastic24** [comment]
delete controls_v2
![image](https://user-images.githubusercontent.com/95725102/166115753-efb10d15-4dd2-4e68-9e73-278391334596.png)

**Comment by BarGames** [comment]
> 

thank you so much it works
