### ISSUE TITLE
How Do I Add Custom Achievements?

### ISSUE THREAD

**Issue by ARandomDuude** [ShadowMario/FNF-PsychEngine#8403]
### Describe your problem here.

The new 0.5.2 update lets you add achievements and I don't know how to code so I need the script.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
it doesn't, the folder is unused
same goes for shaders

**Comment by ARandomDuude** [comment]
Ok thank you.

**Comment by frantastic24** [comment]
You forgot to close
