### ISSUE TITLE
How do i make menubg not change its color to pink on main menu?

### ISSUE THREAD

**Issue by JacksRobotics** [ShadowMario/FNF-PsychEngine#8404]
### What is your question?

im making a fnf mod. and i dont like. how the menubg changes it color to pink. is there anyway to make it stay yellow?

**Comment by CrusherMods** [comment]
if your on source code you can remove this line I think
![image](https://user-images.githubusercontent.com/90648119/166118888-1e9cde55-7dd6-4a25-8747-94b08f75acb0.png)

if your on mods folder then ig just make the image as the same as the yellow one

**Comment by JacksRobotics** [comment]
thanks
