### ISSUE TITLE
how do i make the LoadingState.hx work

### ISSUE THREAD

**Issue by SAB236YT** [ShadowMario/FNF-PsychEngine#8409]
### What is your question?

how do i make the LoadingState.hx work

**Comment by Mastercopper2346** [comment]
just delete `#if NO_PRELOAD_ALL` and `#end` in the file

**BUT IT WILL STAY ON THE LOADING STATE FOREVER.**

**Comment by SAB236YT** [comment]
> just delete `#if NO_PRELOAD_ALL` and `#end` in the file
> 
> **BUT IT WILL STAY ON THE LOADING STATE FOREVER.**

how am i supposed to make it really load?

**Comment by SAB236YT** [comment]
if can't then ill' just use the indie cross source
