### ISSUE TITLE
Game crashes when leaving TitleState

### ISSUE THREAD

**Issue by Vinny-Lol** [ShadowMario/FNF-PsychEngine#841]
### Describe your bug here.

Whenever I try to leave to go to MainMenuState from TitleState the game just crashes.

### Command Prompt/Terminal logs (if existing)

```bash
The instruction at 0x00007FF6A30FD103 referenced memory at 0x0000000000000000. The memory could not be read.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I have edited PlayState, CreditsState, GameOverSubstate, and Achievements.

**Comment by ShadowMario** [comment]
No fucking clue mate.
Any errors on console?

**Comment by ShadowMario** [comment]
No reply... damn
