### ISSUE TITLE
(Lua) Hardlight Blending

### ISSUE THREAD

**Issue by AnomaleZ** [ShadowMario/FNF-PsychEngine#8414]
### What is your question?

Quick question, does hardlight blending work?
I tried setBlendMode('obj','hardlight') and setBlendMode('obj','hard')
None of which solved.
I feel like I'm missing something.

**Comment by keanu64github** [comment]
hard light blending doesn't look like it works... :(

**Comment by ShadowMario** [comment]
That's how it works in haxe idk
