### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ManbiDude** [ShadowMario/FNF-PsychEngine#8416]
### Describe your problem here.

I Tried Making A Bg But Keeps Giving Me A Error

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes

**Comment by frantastic24** [comment]
it would help if you like SHOWED the error you know

**Comment by MaybeMaru** [comment]
wHaT?! 
sharing the code and the error?
nah bro stop dreaming

**Comment by MaybeMaru** [comment]
Also you didnt say the changes you did to the build

**Comment by ManbiDude** [comment]
i did

**Comment by ManbiDude** [comment]
im not dreaming

**Comment by ManbiDude** [comment]
btw the code was deleted
