### ISSUE TITLE
How do I disable controls?

### ISSUE THREAD

**Issue by dombomb64** [ShadowMario/FNF-PsychEngine#8419]
### Describe your problem here.

I want to make it so that, when you don’t dodge a projectile, it disables your controls for a bit. I’ve got the dodging part down, but I don’t know how to disable the player’s controls. Can anybody show me how?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by keanu64github** [comment]
If you mean making the player not be able to hit notes you should do (im hoping you already know how to make a part of a script only work for a certain arrow type) setProperty('boyfriend.stunned', true/false)

**Comment by dombomb64** [comment]
Thank you! It worked perfectly!
