### ISSUE TITLE
Pause Song

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8420]
### What is your question?

Is there any way to get which song will play on the pause screen?

**Comment by Draconic-Hybrid** [comment]
Yep, it's `getPropertyFromClass('PauseSubState', 'songName')` I believe

`setPropertyFromClass('PauseSubState', 'songName', 'breakfast') --song must be in /music`
to change the pause music

**Comment by tylerandari12** [comment]
Ok thank you...
