### ISSUE TITLE
how to make the effect of floating?

### ISSUE THREAD

**Issue by bendyloq** [ShadowMario/FNF-PsychEngine#8421]
### What is your question?

the question is about how to make the characters float, you know, that they go up and down repeatedly giving the effect

**Comment by JavoniCraft** [comment]
`function onUpdate(elapsed)

    if curStep >= 0 then
  
      songPos = getSongPosition()
  
      local currentBeat = (songPos/1000)*(bpm/80)
  
      doTweenY(dadTweenY, 'dad', 30-110*math.sin((currentBeat*0.25)*math.pi),0.001)
  
    end
  
  end

function opponentNoteHit()
       health = getProperty('health')
    if getProperty('health') > 0.1 then
       setProperty('health', health- 0.01);
	end
end
`

**Comment by TrustVVorthy** [comment]
is this possible with an Lua Sprite?

**Comment by JavoniCraft** [comment]
yes, also sorry that i left a healthdrain script in there, too
