### ISSUE TITLE
How to make one animation have more priority than another?

### ISSUE THREAD

**Issue by HollowKnighttec** [ShadowMario/FNF-PsychEngine#8422]
### What is your question?

checking what I'm doing, I would like to know how to make a "Dodge" animation run from start to finish without interruption of note animations

**Comment by keanu64github** [comment]
If you already did a check to make a script only work for a certain notetype, it would be `	for i = 0, 7 do
		setPropertyFromGroup('unspawnNotes', i, 'noAnimation', true)
	end`

**Comment by Lorekeeper49** [comment]
Setting bf's special animation property to true should work since it overrides all animations until _the_ special animation is finished (I forget the code for that)
