### ISSUE TITLE
sink 4 more arrows as the third player

### ISSUE THREAD

**Issue by sanscachondo** [ShadowMario/FNF-PsychEngine#8423]
### What is your question?

more or less it's something like Bonedoogle, add another arrow box for a third player (opponent) in the middle of the song

**Comment by ManMaster707** [comment]
ironically enough, there IS a Bonedoggle port that uses this, just download the mod and look for the script
https://gamebanana.com/mods/372092

**Comment by sanscachondo** [comment]
thank
