### ISSUE TITLE
getting bf, gf, dad camera position 

### ISSUE THREAD

**Issue by BillyLOLwkwk** [ShadowMario/FNF-PsychEngine#8425]
### What is your question?

bro, how to get the value of `bf.cameraPosition` and `boyfriendCameraOffset[0] / [1]` ?
i'm really dont know how to use `getPropertyFromGroup`. any one know how to get that value ?

**Comment by Stilic** [comment]
```lua
local camOffset = getProperty('boyfriendCameraOffset')
-- you can now access it like: boyfriendCameraOffset[1] for the first element of the array
```
