### ISSUE TITLE
How do I check if a note gets hit with-in a callback function?

### ISSUE THREAD

**Issue by PerlIsMe** [ShadowMario/FNF-PsychEngine#8427]
### Describe your problem here.

title says it all man

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by AetherLynx** [comment]
[read the wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API#example-scripts)
```lua
function goodNoteHit(id, direction, noteType, isSustainNote)
    --code
end
```

**Comment by Lorekeeper49** [comment]
```lua
function opponentNoteHit(id, direction, noteType, isSustainNote)
    --code
end
```

This is for the opponent's side obviously

**Comment by PerlIsMe** [comment]
I don't think functions work with in call backs

**Comment by PerlIsMe** [comment]
> I don't think functions work with in call backs

that was my problem

**Comment by Stilic** [comment]
> I don't think functions work with in call backs

wdym
