### ISSUE TITLE
how do i add a warning screen to fnf. and a mouse to the main menu?

### ISSUE THREAD

**Issue by JacksRobotics** [ShadowMario/FNF-PsychEngine#8429]
### What is your question?

im making a mod with jumpscares . and i want to add a warning screen. i also want to add the flx mouse to the main menu just like in yoshi engine.

**Comment by GioVasMor15** [comment]
how about making a danger screen as a cutscene?

**Comment by JacksRobotics** [comment]
> how about making a danger screen as a cutscene?

i dont have any cutscenes for the mod

**Comment by Wither362** [comment]
> ### What is your question?
> im making a mod with jumpscares . and i want to add a warning screen. i also want to add the flx mouse to the main menu just like in yoshi engine.

The flx mouse you can activate it in the `project.xml` file, if you don’t know what line is, just tell it to me and I will give you the lines

**Comment by JacksRobotics** [comment]
> > ### What is your question?
> > im making a mod with jumpscares . and i want to add a warning screen. i also want to add the flx mouse to the main menu just like in yoshi engine.
> 
> The flx mouse you can activate it in the `project.xml` file, if you don’t know what line is, just tell it to me and I will give you the lines

kk thanks

**Comment by Wither362** [comment]
[this line](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/Project.xml#L154)

**Comment by JacksRobotics** [comment]
oof. well the code is there. but i dont know what to chose. there are 3 lines of it.



which one

**Comment by Wither362** [comment]
Any of them

**Comment by JacksRobotics** [comment]
kk but how do i enable them. what do i type

**Comment by DewDrags** [comment]
mouse script :
folder Phych engine/mods/scripts

**Comment by DewDrags** [comment]
I'll see if I can make a warning lua script

**Comment by JacksRobotics** [comment]
kk

**Comment by JacksRobotics** [comment]
i found out that if you go to titlestate.hx you can change flxg.mouse.visible = false; to true. and i can also edit the warning flashing lights text.
