### ISSUE TITLE
Random Colors

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8431]
### What is your question?

Is there a way to set a sprite's color to a random color?

**Comment by keanu64github** [comment]
`setProperty('whatever.color', getRandomInt(-16777216, -1))` (i chose those numbers because the first one is "000000" hex and the last one is "FFFFFF" in hex.)

**Comment by keanu64github** [comment]
I mean, you should set the getRandomInt as a variable like randomColorInt or something so you can get everything the same color but ok

**Comment by tylerandari12** [comment]
I'll see what I can do...
Thanks...
