### ISSUE TITLE
Animated Sprite

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#8433]
### Describe your problem here.

So basically i wanna make an event where an animated sprite appears and then it dissapears after the animation has been played but nothing works.

Like if in Value1, you put the name of the sprite and then the sprite plays or something like that

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Chidubemmo** [comment]
Its already in the downloadable build and its called play animation

**Comment by WilliamGaming12** [comment]
> Its already in the downloadable build and its called play animation

i dont mean from a character, from something own like an own xml

**Comment by Mastercopper2346** [comment]
Use:

- [ ] runTimer
- [ ] addAnimationByPrefix
- [ ] addAnimatedLuaSprite

idk what else

**Comment by keanu64github** [comment]
orr do `if (getProperty('yourObject.animation.curAnim.finished') == true) then 
removeLuaSprite('yourObject', true) 
end` i guess

**Comment by Lorekeeper49** [comment]
> Use:
> 
> - [ ] runTimer
> - [ ] addAnimationByPrefix
> - [ ] addAnimatedLuaSprite
> 
> idk what else

addAnimatedLuaSprite is deprecated so use addLuaSprite instead since it adds the sprite no matter if it's animated or not

**Comment by WilliamGaming12** [comment]
> Use:
> 
> * [ ]  runTimer
> * [ ]  addAnimationByPrefix
> * [ ]  addAnimatedLuaSprite
> 
> idk what else

Thank you, more and less i got an idea of it and now i created a script of it. God lord, it was kinda hard
