### ISSUE TITLE
Strums stay lit if pausing right after hitting a note

### ISSUE THREAD

**Issue by Itsgithubfellow** [ShadowMario/FNF-PsychEngine#8434]
### Describe your bug here.

This is a strange one. If you hit a note, and pause immediately, then resume the game, the strum would stay lit, even if you're not holding down the note. The effect reverses when you hit a new note. In the image provided, I am not holding down any notes, yet my strums are lit up. 
![strums bug](https://user-images.githubusercontent.com/59983463/166154670-4766a74b-b68d-4b32-a4c8-bfa7bd8a4db8.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited TitleState.hx, PlayState.hx, CoolUtil.hx, and MainMenuState.hx

**Comment by Mastercopper2346** [comment]
that's not a bug. its just a engine thing.

**Comment by Mastercopper2346** [comment]
im pretty sure **ALL** Engines have this effect.

**Comment by keanu64github** [comment]
> im pretty sure **ALL** Engines have this effect.

Yeah

**Comment by Itsgithubfellow** [comment]
Wow, I didn't know what, interesting.
