### ISSUE TITLE
Enemy notes not glow

### ISSUE THREAD

**Issue by SpookyMan16** [ShadowMario/FNF-PsychEngine#8435]
### Describe your problem here.

How do I make the opponents notes not glow?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Mastercopper2346** [comment]
like not glow?
**Be more specific.**

**Comment by Lorekeeper49** [comment]
No animation on the character or have the notes go straight past the opponent's strumline

**Comment by SpookyMan16** [comment]
> like not glow? **Be more specific.**

Yes that is what I mean.

**Comment by FlintIshe** [comment]
You mean when the opponent hit the note then then the notes won't flash ? 
 
if it is, then its kinda impossible

**Comment by Stilic** [comment]
you can only do that in source

**Comment by SteveCoolFart** [comment]
i did it without sorce and im not teaching cuz stupid

**Comment by tylerandari12** [comment]
> i did it without sorce and im not teaching cuz stupid

Bruh

**Comment by tylerandari12** [comment]
Only thing I could think of is use some new note sprites that don't have the animations.
