### ISSUE TITLE
HUD Zoom

### ISSUE THREAD

**Issue by Joanarr** [ShadowMario/FNF-PsychEngine#8436]
### Describe your problem here.

How can I zoom out the HUD at the same rate as the stage when changing camera zooms?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SAB236YT** [comment]
idk if i can do what u are talking but is simple a camera zoom

if name == "Set Hud Zoom" then
        
        if value2 == '' then
      	  setProperty('camHUD.zoom' ,value1)

**Comment by Joanarr** [comment]
Whenever I use camHUD.zoom, it works for only a split second before it zooms it back to the default zoom. It essentially treats it as an Add Camera Zoom event instead of a Set Camera zoom event

**Comment by Rajbir98** [comment]
I am also trying to port camellia week 2 for personal use can any body help me

**Comment by Rajbir98** [comment]
Seems like i can make it work.
`        function onUpdate()
                setProperty('camHUD.zoom' ,0.5)
         end`

**Comment by Rajbir98** [comment]
but i don't know how to stop this onUpdate
