### ISSUE TITLE
I can't turn off the BOTPLAY function

### ISSUE THREAD

**Issue by VanoMango** [ShadowMario/FNF-PsychEngine#8437]
I downloaded psych engine for the first time, and when I tried to play, I immediately had botplay enabled. I've tried turning it off in the settings, but there's nothing there.
![1](https://user-images.githubusercontent.com/104733615/166159986-e211cbda-0146-4880-bdda-99dfa0aa6f49.png)
![2](https://user-images.githubusercontent.com/104733615/166159988-b9a3ede7-7706-4009-bbe2-7a8380956244.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by keanu64github** [comment]
Click Control on the Freeplay Menu, then find BotPlay, then disable it.

**Comment by VanoMango** [comment]
> Нажмите «Управление» в меню «Свободная игра», затем найдите «BotPlay» и отключите его.

Thanks, you save my day

**Comment by Lorekeeper49** [comment]
> Click Control on the Freeplay Menu, then find BotPlay, then disable it.

You can actually do this in the story menu too

**Comment by Grape-Boy** [comment]
> Thanks, you save my day

You can close this issue

**Comment by keanu64github** [comment]
I forgot that too 😅
