### ISSUE TITLE
im new to lua and c++ so how do you fix this?

### ISSUE THREAD

**Issue by hgamingyt** [ShadowMario/FNF-PsychEngine#8439]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/81877937/166167865-138321c1-6233-4296-bf74-283fe035bc54.png)
![image](https://user-images.githubusercontent.com/81877937/166167963-0a4f69b5-9e9e-41a8-9ef9-0f06341d35e5.png)
Thanks!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheLeerName** [comment]
try delete export folder

**Comment by Stilic** [comment]
try reinstalling visual studio shit

**Comment by Grape-Boy** [comment]
You need to install (or reinstall) the Windows 10 SDK components using the Visual Studio Installer:
https://stackoverflow.com/a/59803149
https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/
