### ISSUE TITLE
Custom Note doesn't play Custom Sound (WITH CODE AND FILES NOW =D !)

### ISSUE THREAD

**Issue by Johferson** [ShadowMario/FNF-PsychEngine#844]
### Describe your bug here.

Like the title says. I put the custom sound in mods/(mymod)/sounds.

Code:
```
function onCreate()
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is an Mine
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Mine Note' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'MINE_assets'); 
			setPropertyFromGroup('unspawnNotes', i, 'hitHealth', '0'); 
			setPropertyFromGroup('unspawnNotes', i, 'missHealth', 0.250); 
			setPropertyFromGroup('unspawnNotes', i, 'hitCausesMiss', true);
			
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress', false) then 
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true); 			
			end
		end
	end
end
function goodNoteHit(id, direction, noteType, isSustainNote)
	if noteType == 'Mine Note' then
		 playSound('expMine', 1);
	end
end

```
Files:
[files.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/7489776/files.zip)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

None

**Comment by Johferson** [comment]
now pls don't close it instantly =D

**Comment by SrtHero278** [comment]
It seems correct. Maybe try changing "direction" to "noteData" perhaps?

**Comment by drakonieyah** [comment]
> It seems correct. Maybe try changing "direction" to "noteData" perhaps?

That's not the issue. I am using the same code, and no issues for me. I don't know why though.

**Comment by ShadowMario** [comment]
`mods/sounds/expMine.ogg` couldn't be found, that's it, if you're executing this note type outside of your mod folder specifically designed's Mod it will crash the game because it doesn't searches for the sound.
