### ISSUE TITLE
"source/PlayState.hx:4302: characters 2-10 : Expected }" when there is no where to put a "}"

### ISSUE THREAD

**Issue by Itsgithubfellow** [ShadowMario/FNF-PsychEngine#8440]
### Describe your problem here.

Either I'm blind, or haxe is being dumb.

I'm fairly new to FNF modding, FYI, so don't bash me in the comments if the solution is right infront of my eyes.

While trying to test the game, the command prompt kept giving me the error "source/PlayState.hx:4302: characters 2-10 : Expected }" When I go to check the specific line of code, I see that it doesn't require a "}". I've tried things from deleting the new dodge code to even adding the unneeded bracket to no avail. 

I have provided images. Any help would be appreciated.
![lines of code](https://user-images.githubusercontent.com/59983463/166169861-f54f5a00-5534-4d9e-9e22-a3dc18b0bb85.png)
![error message](https://user-images.githubusercontent.com/59983463/166169862-734a2398-055b-40eb-ac7d-0ade31072146.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

In PlayState.hx, I made it so in Tutorial, pressing space would play the dodge animation for BF.

**Comment by Grape-Boy** [comment]
put a `}` before the line `var lightningStrikeBeat:Int = 0;`, above the beatHit function

**Comment by Itsgithubfellow** [comment]
thanks, it worked!

**Comment by Itsgithubfellow** [comment]
I don't know why haxe sometimes doesn't give the correct line for where the error is.

**Comment by DewDrags** [comment]
I only program with lua srry
