### ISSUE TITLE
how to make an event that serves to hide the HUD, and another event that does the same but in reverse

### ISSUE THREAD

**Issue by Epiclol374** [ShadowMario/FNF-PsychEngine#8441]
### Describe your problem here.

I'm talking about hiding the life bar, the arrows, basically everything, and that there is another event capable of reversing the effect

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by frantastic24** [comment]
```lua
function onEvent(name, v1, v2)
	if name == 'HUD visibility' then
		setProperty('camHUD.visible', not getProperty('camHUD.visible'))
	end
end
```

**Comment by Lorekeeper49** [comment]
> ```lua
> function onEvent(name, v1, v2)
> 	if name == 'HUD visibility' then
> 		setProperty('camHUD.visible', not getProperty('camHUD.visible'))
> 	end
> end
> ```

You can just replace 'not getProperty ('camHUD.visible')' with false

**Comment by frantastic24** [comment]
no? you can't turn it back on if i did

**Comment by Lorekeeper49** [comment]
> no? you can't turn it back on if i did

```lua
setProperty('camHUD.visible', true) --this should work
```

**Comment by frantastic24** [comment]
you do know that's doing the same thing i did?

**Comment by Lorekeeper49** [comment]
Well I just found out that you can just set the hud's opacity by doing this
```lua
setProperty('camHUD.alpha', [int]);
```

**Comment by frantastic24** [comment]
cool but that makes the script longer

**Comment by Grape-Boy** [comment]
> You can just replace 'not getProperty ('camHUD.visible')' with false

but wouldn't that just set it to false ? the point of
```lua
not getProperty('camHUD.visible')
```
so that it's something you can toggle, otherwise you would need a second event to turn it back on

**Comment by Epiclol374** [comment]
Thanks! but couldn't you make a smoother transition instead of disappearing all at once?

**Comment by Grape-Boy** [comment]
> Thanks! but couldn't you make a smoother transition instead of disappearing all at once?

```lua
function onEvent(name, v1, v2)
    if name == "HUD visibility" then
        if string.lower(v1) == "on" or v1 == "" or v1 == " " then
            doTweenAlpha("HUDvisibleTween", "camHUD", 1, v2, "sineOut")
        elseif string.lower(v1) == "off" then
            doTweenAlpha("HUDinvisibleTween", "camHUD", 0, v2, "sineOut")
        end
    end
end
```

v1 should be "on", " " or empty if you want to make the HUD visible, and "off" if you want to make it invisible.
v2 is for the duration of the tween, a smaller duration makes the tween appear or disappear faster.

**Comment by Epiclol374** [comment]
THXXXX!!!!!
