### ISSUE TITLE
How to install mods that don't have exe?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#8443]
### What is your question?

How to install mods that don't have exe?
for example:
https://gamebanana.com/mods/367798

it said:

> PUT THIS IN YOUR LATEST PSYCH ENGINE BUILD

I follow that guide above, but I can't find the songs in the menu page.

![image](https://user-images.githubusercontent.com/13177997/166214060-5ef6059d-16c8-4c4d-9de7-88c0a3dcda98.png)

**Comment by Stilic** [comment]
How to install mods that doesn't have a .exe:
1. Unzip the mod and put it in the `mods` folder of your Psych Engine folder.
2. Open up the game then go to the mods menu and check if your mod is ON.
3. Exit the menu and you should be good to go!

**Comment by tylerandari12** [comment]
Bruh

![Bruh](https://user-images.githubusercontent.com/97060639/166596087-fb531870-2d2e-470e-b9e7-e270b3d11eef.PNG)
