### ISSUE TITLE
how do i remove the scroll thing on the main menu.

### ISSUE THREAD

**Issue by JacksRobotics** [ShadowMario/FNF-PsychEngine#8444]
### What is your question?

hi ive added my menubg. but when i open the game. and when i select the menu freeplay (no not when i press enter on freeplay.) the menu moves down a bit. heres a example

https://user-images.githubusercontent.com/100966392/166229044-d76f5211-32b3-4499-89e5-71fb360b66f1.mp4

.

**Comment by Grape-Boy** [comment]
Set the bg's scroll factor to 0, 0.
Go to line 75, or where you create the bg sprite and put
```haxe
bg.scrollFactor.set();
```
instead of
```haxe
bg.scrollFactor.set(0, yScroll);
```

**Comment by JacksRobotics** [comment]
> Set the bg's scroll factor to 0, 0. Go to line 75, or where you create the bg sprite and put
> 
> ```hx
> bg.scrollFactor.set();
> ```
> 
> instead of
> 
> ```hx
> bg.scrollFactor.set(0, yScroll);
> ```

thanks

**Comment by Grape-Boy** [comment]
np, you can close this issue now if it works
