### ISSUE TITLE
Adding Cutscenes In Psych Engine 0.5.2H

### ISSUE THREAD

**Issue by TaviGamer44** [ShadowMario/FNF-PsychEngine#8445]
### Describe your problem here.

I have a problem with adding cutscenes in Psych Engine 0.5.2H.
when I type:
case 'IEEIEUI'
startVideo('IEEIEUI');
Is it because the cutscene name is the same as the song name??? Idk I'm not too good at this

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a song, removed characters, added a week, added a stage

**Comment by CrusherMods** [comment]
Its
case 'IEEIEUI'**:**
startVideo('IEEIEUI');

**Comment by TaviGamer44** [comment]
> Its case 'IEEIEUI'`:` startVideo('IEEIEUI'); I believe


I put that, and also changed the name of the cutscene but it still doesn't work.

case 'IEEIEUI':
startVideo('1');
like that
