### ISSUE TITLE
How to display the accuracy percent on a seperate text?

### ISSUE THREAD

**Issue by NesDoesGithub** [ShadowMario/FNF-PsychEngine#8446]
### Describe your problem here.

I'm trying to display the accuracy percent on a seperate text, but when i press a note the text stays on 0%.
Here is the code and a picture. It worked for the score but not the accuracy.

![fdsifgsdfdgsiu](https://user-images.githubusercontent.com/95316430/166236810-fc2ab112-b6d5-431a-be71-1459e82470fe.png)

The code:
```
function onCreatePost()
    makeLuaText("accuracy", getProperty('ratingPercent') .. '%', 500, 620, 720 - 50)
    setTextAlignment("accuracy", 'right')
    setTextFont("accuracy","Press Start 2P.ttf")
    setTextSize('accuracy', 50)
    setTextBorder('accuracy', 0, 'FFFFFF')
    setProperty("accuracy.y", 5)
    addLuaText("accuracy")
end

function onUpdatePost(elapsed)
   setTextString('accuracy', round(getProperty('ratingPercent') * 100, 2) .. '%')
end

```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by BombasticTom** [comment]
why using onUpdatePost instead on goodNoteHit?

**Comment by BombasticTom** [comment]
oh yeah lua doesn't have round

this isn't python

**Comment by Lorekeeper49** [comment]
> oh yeah lua doesn't have round
> 
> this isn't python

math.round

**Comment by BombasticTom** [comment]
I don't think it works either

**Comment by NesDoesGithub** [comment]
> > oh yeah lua doesn't have round
> > this isn't python
> 
> math.round

this code kinda ended up working but then the percentages were TOO accurate and idk how to round decimals in lua 
```
function onUpdate()
	setTextString("accuracy", getProperty('ratingPercent') .. '%')
end

```

![fsfgsfhsgfiu](https://user-images.githubusercontent.com/95316430/166328978-b311aaa3-2755-45b2-8d63-78188addf88e.png)

**Comment by NesDoesGithub** [comment]
i fixed it and it now displays correctly

**Comment by Alexandir19** [comment]
> i fixed it and it now displays correctly

Can you share how did you fix it? I've been trying to do it too

**Comment by pasta870** [comment]
' | Accuracy: ' .. math.floor(rating*10000)/100 ..'%')
