### ISSUE TITLE
Chromatic aberration when the opponent presses a note (Lua/Script)

### ISSUE THREAD

**Issue by AssasinShadows** [ShadowMario/FNF-PsychEngine#8448]
### Describe your problem here.

I need some script that makes when the opponent presses a note it creates a chromatic aberration effect for a few milliseconds

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by tylerandari12** [comment]
Lua not LUA

**Comment by AssasinShadows** [comment]
> Lua not LUA

Does it really affect anything?
I'm still going to change it
