### ISSUE TITLE
Does anybody have any idea how I would turn this into a stage

### ISSUE THREAD

**Issue by Aden-Mystio** [ShadowMario/FNF-PsychEngine#8450]
### Describe your problem here.

Help
![1651519093651](https://user-images.githubusercontent.com/104238200/166344364-68f4e4eb-b4b6-40a0-805d-c2b66ac73223.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

E

**Comment by Lorekeeper49** [comment]
We're gonna need your image files

**Comment by Aden-Mystio** [comment]
> We're gonna need your image files

The image file is right there, I don't understand what you're asking.

**Comment by Lorekeeper49** [comment]
> > We're gonna need your image files
> 
> The image file is right there, I don't understand what you're asking.

You mean that the image shown is the only image in the stage?

**Comment by DewDrags** [comment]
Aim not charter srry

**Comment by Aden-Mystio** [comment]
> > > We're gonna need your image files
> > 
> > The image file is right there, I don't understand what you're asking.
> 
> You mean that the image shown is the only image in the stage?

Yes that's the only image for the stage

**Comment by fnfdemonboi314159** [comment]
It's dangerous to go alone. take this:

`function onCreate()`
`	-- background shit`
`	makeLuaSprite('yourimage', 'yourimage', -600, -300);`
`	setScrollFactor('yourimage', 0.9, 0.9);`
`	addLuaSprite('yourimage', false);`
`	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore`
`after loading the stage`
`end`

**Comment by Aden-Mystio** [comment]
> > > It's dangerous to go alone. take this:
> > > `function onCreate()`
> > > `	-- background shit`
> > > `	makeLuaSprite('yourimage', 'yourimage', -600, -300);`
> > > `	setScrollFactor('yourimage', 0.9, 0.9);`
> > > `	addLuaSprite('yourimage', false);`
> > > `	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore`
> > > `after loading the stage`
> > > `end`
> > 
> > Lol Thank you! One more question, where would I put this LUA script directly into the game files
> 
> mods\stages

Thanks dude

**Comment by fnfdemonboi314159** [comment]
> > > > It's dangerous to go alone. take this:
> > > > `function onCreate()`
> > > > `	-- background shit`
> > > > `	makeLuaSprite('yourimage', 'yourimage', -600, -300);`
> > > > `	setScrollFactor('yourimage', 0.9, 0.9);`
> > > > `	addLuaSprite('yourimage', false);`
> > > > `	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore`
> > > > `after loading the stage`
> > > > `end`
> > > 
> > > 
> > > Lol Thank you! One more question, where would I put this LUA script directly into the game files
> > 
> > 
> > mods\stages
> 
> Thanks dude

no problem :)

**Comment by DewDrags** [comment]
all in stage change the example stage to the name of your stage as you like.
then put the stage images in mods/image.
just in case I leave you a video :
https://www.youtube.com/watch?v=CDboRB9UpmM

**Comment by Aden-Mystio** [comment]
> It's dangerous to go alone. take this:
> 
> `function onCreate()`
> `	-- background shit`
> `	makeLuaSprite('yourimage', 'yourimage', -600, -300);`
> `	setScrollFactor('yourimage', 0.9, 0.9);`
> `	addLuaSprite('yourimage', false);`
> `	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore`
> `after loading the stage`
> `end`

![20220504_095814_HDR.jpg](https://user-images.githubusercontent.com/104238200/166709446-6dce0c79-4748-4a11-ba8f-ecd0a4e66780.jpg)

**Comment by DewDrags** [comment]
dellet all file in stage and retry

**Comment by DewDrags** [comment]
watch video : https://www.youtube.com/watch?v=CDboRB9UpmM

**Comment by fnfdemonboi314159** [comment]
> > It's dangerous to go alone. take this:
> > `function onCreate()`
> > `	-- background shit`
> > `	makeLuaSprite('yourimage', 'yourimage', -600, -300);`
> > `	setScrollFactor('yourimage', 0.9, 0.9);`
> > `	addLuaSprite('yourimage', false);`
> > `	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore`
> > `after loading the stage`
> > `end`
> 
> ![20220504_095814_HDR.jpg](https://user-images.githubusercontent.com/104238200/166709446-6dce0c79-4748-4a11-ba8f-ecd0a4e66780.jpg)

watch this video: https://www.youtube.com/watch?v=3RVOoEBvnaY

**Comment by fnfdemonboi314159** [comment]
> > > It's dangerous to go alone. take this:
> > > `function onCreate()`
> > > `	-- background shit`
> > > `	makeLuaSprite('yourimage', 'yourimage', -600, -300);`
> > > `	setScrollFactor('yourimage', 0.9, 0.9);`
> > > `	addLuaSprite('yourimage', false);`
> > > `	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore`
> > > `after loading the stage`
> > > `end`
> > 
> > 
> > ![20220504_095814_HDR.jpg](https://user-images.githubusercontent.com/104238200/166709446-6dce0c79-4748-4a11-ba8f-ecd0a4e66780.jpg)
> 
> watch this video: https://www.youtube.com/watch?v=3RVOoEBvnaY

this uses an outdated version of psych but it should still work in 0.5.2h

**Comment by DewDrags** [comment]
yes
