### ISSUE TITLE
Simplify the Achievements system.

### ISSUE THREAD

**Issue by SirScrubBunsDEV** [ShadowMario/FNF-PsychEngine#8451]
### What feature do you want to get added on the **base** engine?

So, I'm making a mod with custom achievements and I want to get rid of all the old ones. While I was doing this, I realized it was probably way harder than it needed to be. Maybe make each achievement its own image and not a grid like the base game icon grid.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by BombasticTom** [comment]
tbh making it like that would be as useful as when icons were split

**Comment by SirScrubBunsDEV** [comment]
Which is useful? I don't get your point

**Comment by BombasticTom** [comment]
read the comment again
did I say I was against your idea? no. not at all. I actually support it

**Comment by tylerandari12** [comment]
That might allow achievements with Lua.

**Comment by Itz-Miles** [comment]
This is how achievements in Lua worked, but the base-achievements loader conflicted with the mod-achievements loader, causing some weird sort of achievement duplicating bug. Dunno much else about it.

**Comment by ShadowMario** [comment]
More simple than writing 5 lines??? You guys never have enough of it jesus fuck dude
