### ISSUE TITLE
Type in a code in main menu lua

### ISSUE THREAD

**Issue by lyke916** [ShadowMario/FNF-PsychEngine#8452]
### Describe your problem here.

Is there a lua code for psych engine where you can type in a code in the main menu and it takes you to a song?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Lua scripts aren't loaded in menus

**Comment by tylerandari12** [comment]
> Lua scripts aren't loaded in menus

Sad truth.

**Comment by Randomxdp** [comment]
> > Lua scripts aren't loaded in menus
> 
> Sad truth.

Wth bruh, i understand yall dont want to touch haxe , or you want to make your mod portable, its just not possible without a rework

**Comment by tylerandari12** [comment]
> > > Lua scripts aren't loaded in menus
> 
> > 
> 
> > Sad truth.
> 
> 
> 
> Wth bruh, i understand yall dont want to touch haxe , or you want to make your mod portable, its just not possible without a rework

There are some who don't have the software and have trouble getting it.

That's why they ask here so they can see if there's an answer.

**Comment by lyke916** [comment]
> Lua scripts aren't loaded in menus
