### ISSUE TITLE
Force Animation

### ISSUE THREAD

**Issue by FlintIshe** [ShadowMario/FNF-PsychEngine#8453]
### What is your question?

How can I force a character's animation to play while he's singing?

**Comment by Wither362** [comment]
You can create a note that when a character touches it, it doesn’t do nothing, and playing the animation with an separated event

**Comment by FlintIshe** [comment]
How about in a situation like this 
https://youtu.be/5UddhyHsQRw

**Comment by Wither362** [comment]
I think what you can do is when the player attacks, create a sprite (let's call it _sprans_) and overlay it, making sans behind that _sprans_ and sans not showing, and make another sprite (lets call it _spranimation_) above the _sprans_ and do that _spranimation_ do the sans dodge animation

**Comment by FlintIshe** [comment]
oooo, ok now I know what I need to do, Thanks!
