### ISSUE TITLE
LUA or FLA

### ISSUE THREAD

**Issue by Aden-Mystio** [ShadowMario/FNF-PsychEngine#8455]
### What is your question?

So a sound effect linked to the LUA or FLA? I would like to add this [sfx](https://drive.google.com/file/d/1iCN5SO36gzeHkiE515ih6cuKCHbrIRvy/view?usp=sharing) to[ this ](https://drive.google.com/file/d/1n0w0s4IqUv8poYxiLItYMur6ljtqRBPK/view?usp=sharing)

**Comment by Shelvsk** [comment]
add `playSound('Release')`

**Comment by Aden-Mystio** [comment]
Where would I put it directly?

**Comment by tylerandari12** [comment]
If you want the sound to play when you hit it put it under goodNoteHit.
if you want it to play when you miss  put it under opponentNoteHit.

**Comment by tylerandari12** [comment]
Hit:
```
-- Function called when you hit a note (after note hit calculations)
-- id: The note member id, you can get whatever variable you want from this note, example: "getPropertyFromGroup('notes', id, 'strumTime')"
-- noteData: 0 = Left, 1 = Down, 2 = Up, 3 = Right
-- noteType: The note type string/tag
-- isSustainNote: If it's a hold note, can be either true or false
function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'Attack' then
		characterPlayAnim('dad', 'hit', true);
		characterPlayAnim('boyfriend', 'throw', true);
		cameraShake(none, 0.01, 0.1); -- none is nothing anyway
		playSound('Release')
	end
end
```

Miss:
```
-- Called after the note miss calculations
-- Player missed a note by letting it go offscreen
function noteMiss(id, noteData, noteType, isSustainNote)
	if noteType == 'Attack' then
		playSound('Release')
	end
end
```

**Comment by Aden-Mystio** [comment]
It's still not working

function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is an Attack Note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Attack' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'ATTACK_assets'); --Change texture
			setPropertyFromGroup('unspawnNotes', i, 'hitHealth', '0.5'); --Default value is: 0.023, health gained on hit
			setPropertyFromGroup('unspawnNotes', i, 'missHealth', '0'); --Default value is: 0.0475, health lost on miss
			setPropertyFromGroup('unspawnNotes', i, 'hitCausesMiss', false);

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true); --Miss has no penalties
			end
		end
	end
	--debugPrint('Script started!')
end

-- Function called when you hit a note (after note hit calculations)
-- id: The note member id, you can get whatever variable you want from this note, example: "getPropertyFromGroup('notes', id, 'strumTime')"
-- noteData: 0 = Left, 1 = Down, 2 = Up, 3 = Right
-- noteType: The note type string/tag
-- isSustainNote: If it's a hold note, can be either true or false
function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'Attack' then
		characterPlayAnim('dad', 'hit', true);
		characterPlayAnim('boyfriend', 'throw', true);
		cameraShake(none, 0.01, 0.1); -- none is nothing anyway
	end
end

-- Called after the note miss calculations
-- Player missed a note by letting it go offscreen
function noteMiss(id, noteData, noteType, isSustainNote)
	if noteType == 'Attack' then
		-- nothing
	end

**Comment by Aden-Mystio** [comment]
And I changed Release to Slash

**Comment by tylerandari12** [comment]
Hmm...
one sec...

**Comment by tylerandari12** [comment]
If this doesn't work i don't know what will...

```
function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		--Check if the note is an Attack Note
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Attack' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'ATTACK_assets'); --Change texture
			setPropertyFromGroup('unspawnNotes', i, 'hitHealth', '0.5'); --Default value is: 0.023, health gained on hit
			setPropertyFromGroup('unspawnNotes', i, 'missHealth', '0'); --Default value is: 0.0475, health lost on miss
			setPropertyFromGroup('unspawnNotes', i, 'hitCausesMiss', false);

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true); --Miss has no penalties
			end
		end
	end
	--debugPrint('Script started!')
end

-- Function called when you hit a note (after note hit calculations)
-- id: The note member id, you can get whatever variable you want from this note, example: "getPropertyFromGroup('notes', id, 'strumTime')"
-- noteData: 0 = Left, 1 = Down, 2 = Up, 3 = Right
-- noteType: The note type string/tag
-- isSustainNote: If it's a hold note, can be either true or false
function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'Attack' then
		characterPlayAnim('dad', 'hit', true);
		characterPlayAnim('boyfriend', 'throw', true);
		cameraShake(none, 0.01, 0.1); -- none is nothing anyway
		playSound("Slash", 1, "SlashingSound")-- Thanks tylerandari12!
	end
end

-- Called after the note miss calculations
-- Player missed a note by letting it go offscreen
function noteMiss(id, noteData, noteType, isSustainNote)
	if noteType == 'Attack' then
		-- nothing
	end
end
```

**Comment by Aden-Mystio** [comment]
> If this doesn't work i don't know what will...
> 
> ```
> function onCreate()
> 	--Iterate over all notes
> 	for i = 0, getProperty('unspawnNotes.length')-1 do
> 		--Check if the note is an Attack Note
> 		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Attack' then
> 			setPropertyFromGroup('unspawnNotes', i, 'texture', 'ATTACK_assets'); --Change texture
> 			setPropertyFromGroup('unspawnNotes', i, 'hitHealth', '0.5'); --Default value is: 0.023, health gained on hit
> 			setPropertyFromGroup('unspawnNotes', i, 'missHealth', '0'); --Default value is: 0.0475, health lost on miss
> 			setPropertyFromGroup('unspawnNotes', i, 'hitCausesMiss', false);
> 
> 			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
> 				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true); --Miss has no penalties
> 			end
> 		end
> 	end
> 	--debugPrint('Script started!')
> end
> 
> -- Function called when you hit a note (after note hit calculations)
> -- id: The note member id, you can get whatever variable you want from this note, example: "getPropertyFromGroup('notes', id, 'strumTime')"
> -- noteData: 0 = Left, 1 = Down, 2 = Up, 3 = Right
> -- noteType: The note type string/tag
> -- isSustainNote: If it's a hold note, can be either true or false
> function goodNoteHit(id, noteData, noteType, isSustainNote)
> 	if noteType == 'Attack' then
> 		characterPlayAnim('dad', 'hit', true);
> 		characterPlayAnim('boyfriend', 'throw', true);
> 		cameraShake(none, 0.01, 0.1); -- none is nothing anyway
> 		playSound("Slash", 1, "SlashingSound")-- Thanks tylerandari12!
> 	end
> end
> 
> -- Called after the note miss calculations
> -- Player missed a note by letting it go offscreen
> function noteMiss(id, noteData, noteType, isSustainNote)
> 	if noteType == 'Attack' then
> 		-- nothing
> 	end
> end
> ```

I appreciate you trying but it didn't work. I even tried changing "SlashingSound" to just "Slash" still didn't work and the attack animation name is "attack" not "throw"

**Comment by tylerandari12** [comment]
Ive got nothing else...

Sorry ;-;

**Comment by tylerandari12** [comment]
But I do have a question...
whats the point of `cameraShake(none, 0.01, 0.1);`?

**Comment by Aden-Mystio** [comment]
> But I do have a question...
> whats the point of `cameraShake(none, 0.01, 0.1);`?

I have no idea
The Lua file for it was in a fnf mod pack dodging and dancing

**Comment by tylerandari12** [comment]
Remove it and try one last time...
I think I know whats wrong. (Its something with errors that  arent fatal.)

**Comment by Aden-Mystio** [comment]
> But I do have a question...
> whats the point of `cameraShake(none, 0.01, 0.1);`?

Here's the link for it https://youtu.be/-6HqF9tkRmY

**Comment by Aden-Mystio** [comment]
> > But I do have a question...
> > whats the point of `cameraShake(none, 0.01, 0.1);`?
> 
> Here's the link for it https://youtu.be/-6HqF9tkRmY

The animation works in game too

**Comment by Aden-Mystio** [comment]
> > > But I do have a question...
> > > whats the point of `cameraShake(none, 0.01, 0.1);`?
> > 
> > Here's the link for it https://youtu.be/-6HqF9tkRmY
> 
> The animation works in game too

https://youtube.com/shorts/VbDKGjlnjXg?feature=share

**Comment by Aden-Mystio** [comment]
> Remove it and try one last time...
> I think I know whats wrong. (Its something with errors that  arent fatal.)

Do you mind disgusting this in discord dms? My username is Aden-Mystio#9184
