### ISSUE TITLE
A button for the mouse to go back in mods

### ISSUE THREAD

**Issue by Arionic** [ShadowMario/FNF-PsychEngine#8456]
### What feature do you want to get added on the **base** engine?

A button for the mouse to go back in mods.
Its frustrating that i can manage the mods easy with the mouse and to go back to menu i need to press backspace.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by BombasticTom** [comment]
use yoshicrafter engine :shadowtroll:

**Comment by tylerandari12** [comment]
> use yoshicrafter engine :shadowtroll:

lol

**Comment by ShadowMario** [comment]
skill issue
