### ISSUE TITLE
How do i make the opponent drain health at a specific time?

### ISSUE THREAD

**Issue by xXReb3caaXx** [ShadowMario/FNF-PsychEngine#8457]
### Describe your problem here.

u already read the title but im just gonna ask it again with an example.

How do i make the opponent drain health at a specific time by using LUA?

Example: i want to make the opponent drain the player’s health (note obviously) in the time “ 1:46 “

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by acap09** [comment]
curSongPos way
```bash
function onUpdatePost(elapsed)
    curSongPosSec = getPropertyFromClass('Conductor', 'songPosition')/1000;
    health = getProperty('health');
end

function opponentNoteHit(id, dir, type, sustain)
    if curSongPosSec > 106 then
        if health < 0.1 and not sustain then
            setProperty('health', health - 0.2)
        end
    end
end
```
this is not tested (curSongPos)

curStep way
```bash
function onUpdatePost(elapsed)
    health = getProperty('health');
end

function opponentNoteHit(id, dir, type, sustain)
    if curStep > 1018 then
        if health < 0.1 and not sustain then
            setProperty('health', health - 0.1)
        end
    end
end
```
this is not tested, though i think it works (curStep)
