### ISSUE TITLE
Psych Engine Source is not compile

### ISSUE THREAD

**Issue by DendyGG** [ShadowMario/FNF-PsychEngine#8458]
### Describe your bug here.

i write in command prompt lime test windows and source is not compiled with error

### Command Prompt/Terminal logs (if existing)

```bash
source/Discord.hx:18: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:28: characters 4-14 : Type not found : DiscordRpc
source/Discord.hx:33: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:38: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:43: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:80: characters 3-13 : Type not found : DiscordRpc
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I rewrite Discord.hx in source i reinstall discord_rpc polymod and linc_luajit

**Comment by CrusherMods** [comment]
Are you sure you used `haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc` in command prompt or powershell or whatever???

**Comment by DendyGG** [comment]
> Are you sure you used `haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc` in command prompt or powershell or whatever???

Command Prompt
