### ISSUE TITLE
Sprite Change During Song On Accuracy/Misses/Health

### ISSUE THREAD

**Issue by SonicXFire1987** [ShadowMario/FNF-PsychEngine#8459]
### Describe your problem here.

How do I have the Opponent's Sprite change during a song depending on your Accuracy, your number of Misses or where your Health is. 

for example
Dad becomes Spookys after 15 misses
Mom becomes gf when accuracy is 50.00%
Monster becomes pico when bf health is at less than 0.3

how do i do that with Lua

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I just added new characters and Notes and changed some sprites and a few lua scripts

**Comment by frantastic24** [comment]
Change character event

**Comment by SonicXFire1987** [comment]
i know how that event works. but i want it to only change on one of those things i listed. i dont want it to happen at a certain part of the song, i want it to happen anytime depending how the player plays. I know its possible since the nonsense mod does it and its made on psych engine. is there a Lua code I can use or is it only possible on the source?

**Comment by frantastic24** [comment]
You could do `onRecalculateRating()` and I'm pretty sure all these variables have shortcuts on the wiki

**Comment by SonicXFire1987** [comment]
ok ill check it and if i find it ill close this

**Comment by SonicXFire1987** [comment]
found it thanks!
