### ISSUE TITLE
making a notetype with pressing space

### ISSUE THREAD

**Issue by SAB236YT** [ShadowMario/FNF-PsychEngine#8461]
### What is your question?

that one up there

**Comment by BombasticTom** [comment]
???

**Comment by Draconic-Hybrid** [comment]
That's... not enough info.

**Comment by tylerandari12** [comment]
He wants an extra strum for space...

**Comment by SAB236YT** [comment]
> He wants an extra strum for space...

Wdym an extra strum? No no no i mean like `if keyJustPressed('space')` I tried but it wont work

**Comment by BombasticTom** [comment]
it's because it has to be looped

**Comment by tylerandari12** [comment]
> > He wants an extra strum for space...
> 
> Wdym an extra strum? No no no i mean like `if keyJustPressed('space')` I tried but it wont work

I thought you meant something like shaggy mod...

Sorry about that.

**Comment by SAB236YT** [comment]
> it's because it has to be looped

Wdym looped

**Comment by tylerandari12** [comment]
https://gamebanana.com/mods/352021

Combine this in your mod folder...
