### ISSUE TITLE
Allow setting a negative note offset

### ISSUE THREAD

**Issue by junetried** [ShadowMario/FNF-PsychEngine#8465]
### What feature do you want to get added on the **base** engine?

Currently (up to and including the latest version) it is not possible to set a note offset to a negative value. This makes it harder to play on setups with a lower delay than usual.

For example, I experience about -20 ms of delay with the game, which is not a problem I can fix in Psych Engine. There are other engines which do not have this limitation (including Kade Engine, I believe) where the delay can be set properly.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by TheRealJake12** [comment]
fuck yeah. Kade Engine

**Comment by junetried** [comment]
@ShadowMario Hey, this issue isn't resolved and shouldn't be closed right now. Pruning stale issues is kind of annoying.

**Comment by MemeHovy** [comment]
> @ShadowMario Hey, this issue isn't resolved and shouldn't be closed right now. Pruning stale issues is kind of annoying.

he has his notifications off

**Comment by MemeHovy** [comment]
and pinging him (on github) will likely get you banned from the repo more quickly
