### ISSUE TITLE
How do i make a change background event

### ISSUE THREAD

**Issue by official-ys** [ShadowMario/FNF-PsychEngine#8467]
### What is your question?

How do i make a custom event that can make the background change?

It would be great if u could tell me where to put the code and how it works

**Comment by frantastic24** [comment]
#3137

**Comment by official-ys** [comment]
thanks lemme close it

**Comment by frantastic24** [comment]
I don't recommend making it an event though

**Comment by Mastercopper2346** [comment]
#8480
