### ISSUE TITLE
Tween for camera Y?

### ISSUE THREAD

**Issue by EgguMan** [ShadowMario/FNF-PsychEngine#8468]
### Describe your problem here.

Hi! I would like to know if there is something like a tweenCameraY(); in the Lua? I say like becuase it obv doesn't exist, but, what could be some easy alternatives? 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope!

**Comment by tylerandari12** [comment]
`doTweenY("yourTweenHere", "camGame", 100, 5, "Linear")`

`camGame` can be `camHUD` or `camOther`

Yes they act as objects.

**Comment by EgguMan** [comment]
> `doTweenY("yourTweenHere", "camGame", 100, 5, "Linear")`
> 
> `camGame` can be `camHUD` or `camOther`
> 
> Yes they act as objects.

WHAT??

thanks for letting me know!

**Comment by EgguMan** [comment]
> `doTweenY("yourTweenHere", "camGame", 100, 5, "Linear")`
> 
> `camGame` can be `camHUD` or `camOther`
> 
> Yes they act as objects.

going back on this, it does not load anything outside of camera view. just a black void

**Comment by tylerandari12** [comment]
> > `doTweenY("yourTweenHere", "camGame", 100, 5, "Linear")`
> 
> > 
> 
> > `camGame` can be `camHUD` or `camOther`
> 
> > 
> 
> > Yes they act as objects.
> 
> 
> 
> going back on this, it does not load anything outside of camera view. just a black void

I think that's how it's supposed to work.

If you want to move the camera itself the use `triggerEvent("Camera Follow Pos", "x", "y")`
