### ISSUE TITLE
I need help on my .lua script.

### ISSUE THREAD

**Issue by MarkToonsHD** [ShadowMario/FNF-PsychEngine#847]
### Describe your problem here.

So I'm trying to make a script that'll make the notes in an upward-downward motion while going side to side. When I run a song with the script, the notes go side to side, but the only not that'll go up and down is the note on the right. Can someone help me? I've been trying to fix this for days.
![image](https://user-images.githubusercontent.com/77655973/140602937-059b5c0e-a4c4-4ce5-a443-be5f798b3c1e.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by SrtHero278** [comment]
The first value in the parenthesis is the tag which is a string value. You're also missing a 5th string value which is the easing method.

**Comment by MarkToonsHD** [comment]
> The first value in the parenthesis is the tag which is a string value. You're also missing a 5th string value which is the easing method.

Ok, but I'm still bad at coding, so what should it look like?

**Comment by ShadowMario** [comment]
The first value is not a number, the first value is the tween tag, it must be an unique string with whatever name you prefer, if two tweens are started with the same tag, the first tween will be cancelled to give space to the second one!
