### ISSUE TITLE
Html5 not working

### ISSUE THREAD

**Issue by sammysonic12345** [ShadowMario/FNF-PsychEngine#8470]
### Describe your bug here.

it not working

### Command Prompt/Terminal logs (if existing)

```bash
lime test html5 -release
source/WeekData.hx:11: characters 8-19 : You cannot access the sys package while targeting js (for sys.io.File)
source/editors/WeekEditorState.hx:34: characters 8-16 :     referenced here
source/editors/MasterEditorMenu.hx:119: characters 37-52 :     referenced here
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by Daboss7173** [comment]
Yeah I have the same issue. 
I am pretty sure it's caused by mod pack support. It sorta makes sense you can't use it in html5.
It's an issue exclusive to psyche engine versions 0.4.0+ i think
