### ISSUE TITLE
icon change?

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8471]
### Describe your problem here.

Is there like a way to change the icon without the change character event? This would really help.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

what

**Comment by frantastic24** [comment]
Create a fake icon, you can't change health bar color though

**Comment by tylerandari12** [comment]
> Create a fake icon, you can't change health bar color though

That should be a thing if possible.

**Comment by frantastic24** [comment]
It's very easy to add through source so I encourage people to do that until there are plans to add it officially

**Comment by Mastercopper2346** [comment]
i can **DO** Source. just tell me.

**Comment by Mastercopper2346** [comment]
and here are a few examples of icon changes (HEALTHBAR COLORS CHAGE TOO):
https://www.youtube.com/watch?v=KYQG9Z04rsY (icons change 7:05 to 7:10)

https://www.youtube.com/watch?v=cFpQOWt3ryM (icons change 1:50 to 1:55)

**Comment by Mastercopper2346** [comment]
HELLO

**Comment by Mastercopper2346** [comment]
**HELLO!!?**

**Comment by Mastercopper2346** [comment]
But, look at  the examples above,

**Comment by Mastercopper2346** [comment]
and i looked in the files, theres no other characters but the main ones.

**Comment by Mastercopper2346** [comment]
HELLO

**Comment by frantastic24** [comment]
you had enough time to do it yourself but you chose to be annoying and keep bumping this

**Comment by Mastercopper2346** [comment]
I DONT KNOW HOW

**Comment by Mastercopper2346** [comment]
THATS THE REASON I CREATED THIS

**Comment by frantastic24** [comment]
Look in playstate dude it's not that hard

**Comment by Mastercopper2346** [comment]
iconP2.changeIcon('icon')

YOU said in other disscusion, cmon man.

**Comment by Mastercopper2346** [comment]
but ill look.

**Comment by Mastercopper2346** [comment]
aslo, what is the goodNoteHit thing for source?

**Comment by frantastic24** [comment]
> YOU said in other disscusion

A discussion that's a month, I don't even know what it has to do with you not wanting to do something yourself

**Comment by frantastic24** [comment]
> YOU said in other disscusion

A discussion that's a month old??? I don't even know what it has to do with you not wanting to do something yourself

**Comment by Mastercopper2346** [comment]
I had waited 2 days
