### ISSUE TITLE
skip dialouge button

### ISSUE THREAD

**Issue by Kingmaxthe2** [ShadowMario/FNF-PsychEngine#8473]
### What feature do you want to get added on the **base** engine?

I've been messing with the Lua for the dialogue and cannot find a way to set a skip button or anything similar. Maybe there's some "endDialogue" thing that I'm missing or it might not exist at all. And if that's the case I'm requesting some way to do that or a lead in the direction of coding a skip button for dialogue.

-thank you!
-Max :)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by HiroMizuki** [comment]
![image](https://user-images.githubusercontent.com/72695242/166837386-de858315-8139-4e73-b3ef-02145fa59c04.png)
try this, at PlayState, inside of the override function update

**Comment by HiroMizuki** [comment]
and of course, change the "YOURKEYOFPREF" at "FlxG.keys.justPressed.YOURKEYOFPREF" to any other valid key that u want

**Comment by HiroMizuki** [comment]
that's the source way
if u want Lua, idk wtf to do

**Comment by BeastlyGhost** [comment]
> that's the source way if u want Lua, idk wtf to do

```
function onUpdate()
--
    if getProperty('inCutscene') then
        if keyboardJustPressed('SHIFT') then -- example key
            setProperty('inCutscene', false)
        end
    end
--
end
```

**Comment by ShadowMario** [comment]
Done.
