### ISSUE TITLE
Does anyone have a script that makes a lua sprite get closer to you if you miss and if you miss that many times it jumpscares and sets your hp on 0.01?

### ISSUE THREAD

**Issue by SquareCatALT** [ShadowMario/FNF-PsychEngine#8474]
And to explain more, the jumpscare fades away and makes a static noise?

**Comment by PrismLight** [comment]
Go to [Mayo's Psych Discussion's](https://github.com/mayo78/PSYCHDISCUSSIONS/discussions) for asking for something so specific.
Also try to make it before you ask someone else.

**Comment by SquareCatALT** [comment]
ok
