### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by PerlIsMe** [ShadowMario/FNF-PsychEngine#8476]
### What needs to be documented?

it was added in 0.5.2h I think

**Comment by frantastic24** [comment]
No

**Comment by PerlIsMe** [comment]
> No

why not?

**Comment by frantastic24** [comment]
0.5.2 doesn't support softcoded achievements

**Comment by PerlIsMe** [comment]
> 0.5.2 doesn't support softcoded achievements

there's a folder labeled "achievements"

**Comment by Mastercopper2346** [comment]
> 0.5.2 doesn't support softcoded achievements
^ this

**Comment by Mastercopper2346** [comment]
Well yes, they were **ADDED** but not **CODED** in.

**Comment by DewDrags** [comment]
then delete it

**Comment by MaybeMaru** [comment]
I swear to god people write stuff without checking first

**Comment by BeastlyGhost** [comment]
the achoevements folder goes unused, the one with images inside assets/images is just so it would be easier to add achievements later on
