### ISSUE TITLE
Custom Achievements

### ISSUE THREAD

**Issue by PerlIsMe** [ShadowMario/FNF-PsychEngine#8477]
### Describe your problem here.

How do I make custom achievements? It was added in 0.5.2h

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
It was not

**Comment by Mastercopper2346** [comment]
i think softcoded achievements were GOING to be added, but then they didnt finish it, so, no softcoded achievements.
