### ISSUE TITLE
Audio offset option for charting

### ISSUE THREAD

**Issue by SussyFellow** [ShadowMario/FNF-PsychEngine#8479]
### What feature do you want to get added on the **base** engine?

Sometimes, when charting a song, one runs into the issue of the beats in the song not lining up 1:1 with the note grid, likely because there's some arbitrary length of silence or noise before the song starts, meaning that even if you get the BPM and all that correct you'd still have to zoom in and use really awkward in-between grid spaces to make the charting feel FULLY synced. There is, I think, a straightforward (in concept if not in execution) solution to this which other rhythm games like Stepmania have had for quite some time. Audio offset! Letting a charter offset what the game recognizes as "the first beat" in a song (or in this case at what point in the audio the charting grid begins).
![image](https://user-images.githubusercontent.com/88362641/166623565-ad12b15b-3a83-4f11-91fd-2606421608b5.png)
(pic at charting zoom x1)
![image](https://user-images.githubusercontent.com/88362641/166623610-ac80a854-69fa-4bd4-b4e1-d8c48d0dfced.png)
(pic at charting zoom x8, with an additional note showing where a note would have to be to ACTUALLY sync with the audio)
This should demonstrate what I mean by a song's audio not being in sync with the grid, despite the BPM being correct and whatnot.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tylerandari12** [comment]
There's already an offset for the audible stuff...
There should be a thing for those visual lines tho...

**Comment by MarkimusZer0** [comment]
> There's already an offset for the audible stuff... There should be a thing for those visual lines tho...

I'm not sure what you mean because the "Audio Offset" option in the Psych Chart editor doesn't do shit

**Comment by ShadowMario** [comment]
In progress

**Comment by ShadowMario** [comment]
Done.
