### ISSUE TITLE
Custom Hurt Notes not working

### ISSUE THREAD

**Issue by ArezalGame89** [ShadowMario/FNF-PsychEngine#848]
### Describe your problem here.

Basically i followed psych engine's tutorial to make a code, so i copy pasted HURT note to INSTA note, instead of atleast normal notes, some weird small notes appear and it doesn't take my health at all. help me please

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

edited playState, menuState and titleState and more states

**Comment by titopops** [comment]
im pretty sure this happens if the game either: cannot find the image in the folder its supposed to be (usually where the same image of the Hurt Note image is probably) or  your using a different arrow skin (no idea about this one, but its happened to me)

**Comment by ShadowMario** [comment]
Show an screenshot.

**Comment by ShadowMario** [comment]
Nothing in 4 days, closing this.
