### ISSUE TITLE
How to change ONLY bf's note skin, WITH SOURCE ONLYYYYYY

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8480]
### Describe your problem here.

I want to change bf's skin texture (yes, at all times) when in a song.
ONLYYYYYY SOURCE CODE

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

what

**Comment by Mastercopper2346** [comment]
HELLO

**Comment by Grape-Boy** [comment]
Just use a BF reskin

**Comment by DewDrags** [comment]
And what does that have to do with the change of notes?

**Comment by TwistChris** [comment]
First for noteskin. It's easy, go to the source/StrumNote.hx file.

Go to line 13 make space, write.

public var notetype:String = 'normal';

after go to the line 29 after the word player:Int write

,notetype:String

after go in line 33 space, write

this.notetype = notetype;

after go to line 40 space twice, go to line 41

switch (notetype)
		{
			case 'normal':
				skin = 'NOTE_assets';
			case 'bf':
				skin = 'NOTE2_assets';
		}

After go to source/PlayState.hx file in line 1996 and replace that

var babyArrow:StrumNote = new StrumNote(ClientPrefs.middleScroll ? STRUM_X_MIDDLESCROLL : STRUM_X, strumLine.y, i, player);

By that

var babyArrow:StrumNote

after go in line 1997 space write

if (player == 1)
				{
					babyArrow = new StrumNote(ClientPrefs.middleScroll ? STRUM_X_MIDDLESCROLL : STRUM_X, strumLine.y, i, player,'normal');
				}
				else
				{
			                babyArrow = new StrumNote(ClientPrefs.middleScroll ? STRUM_X_MIDDLESCROLL : STRUM_X, strumLine.y, i, player,'normal');
		                }
                        if (songName == 'blammed')
                                if (player == 1)
				{
					babyArrow = new StrumNote(ClientPrefs.middleScroll ? STRUM_X_MIDDLESCROLL : STRUM_X, strumLine.y, i, player,'bf');
				}
				else
				{
					babyArrow = new StrumNote(ClientPrefs.middleScroll ? STRUM_X_MIDDLESCROLL : STRUM_X, strumLine.y, i, player,'normal');
			        }

after go to the file source/editors/EditorsPlayState.hx go to line 944 after the word player write

,'normal'

For the end, add a NOTE_ASSETS CUSTOM PNG and XML in assets/preload/images has the name of NOTE2_ASSETS.

Now For Custom Notes

go to the Note.hx file after go to line 102 space, write

case 'BF Note':
                                        mustPress;
                                        reloadNote('BF');

Next go to the ChartingState.hx file then go to line 65, write

,

space, write

'BF Note'

Then add a NOTE_ASSETS CUSTOM PNG and XML in assets/shared/images which has the name of BFNOTE_ASSETS.

start the game go to the blammed song. boyfriend to his own noteskin and for the notes. Go to ChartingState. Now you use your custom notes for bf.

I hope you understood and also I use a translator.

**Comment by Grape-Boy** [comment]
> And what does that have to do with the change of notes?
> 
> El mié, 4 may 2022 a las 9:39, Grape-Boy ***@***.***>)
> escribió:
> 
> > Just use a BF reskin

oh lol sorry i must have misread the title

**Comment by Mastercopper2346** [comment]
thx, but organize plz or give downloads for each .hx

**Comment by hayfii** [comment]
> thx, but organize plz or give downloads for each .hx

You're called lazy

**Comment by DewDrags** [comment]
ah

**Comment by DewDrags** [comment]
there is a script in the psych engine discord that let's you change the
Noteskins depending on who the opponent is, with some edits the script can
also be used to change the player's Noteskins as well, HOWEVER. This does
overwrite your custom noteskins
