### ISSUE TITLE
Framerate capped at 31 FPS upon opening.

### ISSUE THREAD

**Issue by LemonadeOnDiscord** [ShadowMario/FNF-PsychEngine#8484]
### Describe your bug here.

Upon opening the game, 95% of the time will it be capped at 31 FPS, despite my settings having the max FPS be 160. This issue persists throughout **every single executable mod I have that uses Psych Engine**, it is not specific to the main version I have. Updating Psych versions have not yielded any better results. Reinstalling the mods does not work either. I am uncertain as to why this would be a hardware issue, but just in-case, I have 8GB of RAM, a Nvidia GeForce GTX 1650, and an Intel Core I5. This issue is the most confusing to me as, well, it doesn't happen 100% of the time. Just most of the time.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by BombasticTom** [comment]
try deleting the sol files maybe that's the problem

**Comment by Mastercopper2346** [comment]
Well, the original max fps cap from the og fnf was 40, mabye it has to do with that.
