### ISSUE TITLE
How to make animated icons by source code not lua.

### ISSUE THREAD

**Issue by TwistChris** [ShadowMario/FNF-PsychEngine#8485]
### Describe your problem here.

Hello, first I am using psych engine version 4.2.0. So lua animated icons don't work. I tested before asking this question. So I try by the source code. I helped myself with the source code of hypno lullaby. The icons are animated except when I play a music, they remain non-animated. So I tried to make a copy of icons but they will be animated in PlayState.hx file. The icons were finally animated. But the problem the animated icons are blocked. They are stuck at the bottom left of the screen. They don't move. They are simply animated. The X has problem I believe. I advise you to look at my repository it is called 'PE-0.4.2-ANDROID-BUILD-TC' and go to the PlayState.hx file and look towards the icons to better understand my problem. Give me two solutions. 1.corrected the X of animated icons. 2.use another method but which uses the source code. and also I use a translator.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5/Browser

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I modify the PlayState.hx and HealthIcon.hx files.

**Comment by DewDrags** [comment]
sorry but I don't animate in code only in lua even though you can't animate
icons in lua because shadow mario hasn't created an interface for that
option so I can't help you even if it was lua

**Comment by TwistChris** [comment]
I managed to fix the problem. Thank you. And also I change my method for animated icons.

**Comment by Mastercopper2346** [comment]
#8522
