### ISSUE TITLE
How to get amount of notes in song

### ISSUE THREAD

**Issue by GMan2006i** [ShadowMario/FNF-PsychEngine#8486]
### Describe your problem here.

How do I get the total amount of notes (unloaded or not) in a song of any or a certain type?
I.E. something like
getProperty('UnspawnNoteAmount')
or what ever

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, Some Minor Playstate and discord stuff, mostly the playstate, it being adding a FlxTrail event

**Comment by tylerandari12** [comment]
Leaving this comment to come back here on my computer.

**Comment by frantastic24** [comment]
`getProperty('unspawnNotes.length')`
