### ISSUE TITLE
How to add a waring screen (Like reset score warning) when choosing a difficulty? (Reupload cuz no one saw last one)

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8487]
### Describe your problem here.

i need this to tell someone about the difficulty, 
so thats why i need this.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

what

**Comment by DewDrags** [comment]
the question means you want to create a difficulty?

**Comment by Mastercopper2346** [comment]
no

**Comment by DewDrags** [comment]
so?

**Comment by hayfii** [comment]
![image](https://user-images.githubusercontent.com/94598301/173120702-24c70db9-388f-4dd5-bbfe-ce7c733448c5.png)
Cap lines

**Comment by Mastercopper2346** [comment]
*Also ONE month ago
