### ISSUE TITLE
Compiling straight from source, loading stuck at ~70% when playing a song.

### ISSUE THREAD

**Issue by bencamos** [ShadowMario/FNF-PsychEngine#8488]
### Describe your problem here.

When compiling straight from the release using `haxelib run lime test windows -debug` on Windows, the game launches and runs as expected. However when attempting to play any song the game gets stuck on the "PSYCH ENGINE SUPREMACY" loading screen at roughly 70%.

I've poked around the source trying to find what causes this and found nothing.
Changing the preload also seems to have no effect on the issue.
![image](https://user-images.githubusercontent.com/85905323/166735843-d411a7ce-1f9c-4f6e-9667-e228650dc09f.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Randomxdp** [comment]
Did you enable the loading screen?

**Comment by bencamos** [comment]
> Did you enable the loading screen?

No, not at all. I just downloaded it directly from releases and compiled it.
