### ISSUE TITLE
when I launch the mod, this is displayed, what should I do with this? please help!!!

### ISSUE THREAD

**Issue by Aloekunyep** [ShadowMario/FNF-PsychEngine#8489]
### Describe your problem here.
when I launch the mod, this is displayed, what should I do with this? please help!!!

source/Discord.hx:7: characters 8-16 : Type not found : llua.Lua
source/Discord.hx:8: characters 8-18 : Type not found : llua.State
source/Discord.hx:96: characters 45-50 : Type not found : State

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by tylerandari12** [comment]
You updated haxe?

**Comment by Aloekunyep** [comment]
Yes

**Comment by ELJHOSEPE** [comment]
hello to me also happens that error, do you have any solution?
