### ISSUE TITLE
Dodge mechanic help

### ISSUE THREAD

**Issue by TNT-King** [ShadowMario/FNF-PsychEngine#8491]
### Describe your problem here.

When i'm triyng to make a dodge mechanic with lua, the animation is just freezing and BF Is white. But if i press space, his back to normal color but still in the dodge anim. Here is my code: " function onCreate()
    isDodging = true
end

function onUpdate()
    if isDodging == false then
        characterPlayAnim('boyfriend', 'dodge', false);
        setPropertyFromClass('GameOverSubstate', 'characterName', 'bf'); --Character json file for the death animation
        setPropertyFromClass('GameOverSubstate', 'deathSoundName', 'fnf_loss_sfx'); --put in mods/sounds/
        setPropertyFromClass('GameOverSubstate', 'loopSoundName', 'gameOver'); --put in mods/music/
        setPropertyFromClass('GameOverSubstate', 'endSoundName', 'gameOverEnd'); --put in mods/music/
    end

    if isDodging == true then
        characterPlayAnim('boyfriend', 'dodge', true);
        setPropertyFromClass('GameOverSubstate' == false)
    end

    if keyJustPressed('space') then
        isDodging = true
    end

    if keyReleased('space') then
        isDodging = false
        characterPlayAnim('boyfriend', 'dodge', false);
    end

    function onStepHit()
        if curStep == 50 then isDodging = true
    end
 end
end" Pls help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JacksRobotics** [comment]
i think its imposible to do with lua

**Comment by MaybeMaru** [comment]
im sure it is pretty damn possible but just not coded correctly

**Comment by impostor5875** [comment]
did you just try to set a substate to false

what

**Comment by TNT-King** [comment]
Impostor5875, i was gonna do that but i had to sleep LOL

**Comment by TNT-King** [comment]
But that actully worked in a way + By changing some code

**Comment by TNT-King** [comment]
If u wanna try, then here is the code :D
