### ISSUE TITLE
reload song not working in chart editor

### ISSUE THREAD

**Issue by VsSpongKid** [ShadowMario/FNF-PsychEngine#8494]
### Describe your bug here.

when i type the song name and press reload song in chart editor i type it correctly and i cant play the audio and when i scroll it doesnt scroll

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i tried alot to fix it but it didnt work

**Comment by frantastic24** [comment]
That means your files are broken, re-export or reconvert them
