### ISSUE TITLE
Flip X option in DIALOGUE PORTRAIT EDITOR

### ISSUE THREAD

**Issue by AbelitoGamerYT** [ShadowMario/FNF-PsychEngine#8499]
### What feature do you want to get added on the **base** engine?

Sometimes you want to flip your sprite to put it on the opposite side of the dialog but you realize that **there is no option to Flip X in the dialog portrait editor**, and make a different spritesheet with the only difference that is flipped is not the best solution.

This could help speed up the creation of dialog portraits

PD: Flip the sprite , NOT MOVE IT

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
we need this.
