### ISSUE TITLE
Play dialogues BEFORE AND AFTER cutscene

### ISSUE THREAD

**Issue by AbelitoGamerYT** [ShadowMario/FNF-PsychEngine#8501]
### Describe your problem here.

I want to play 2 different dialogues, the first one before the cinematic and the second one once the cutscene is done, but I can't find a way to do it 

Can someone help me with this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Lorekeeper49** [comment]
This is all I can think of
```lua
local allowCountdown = false;
function onStartCountdown()
    if isStoryMode and not allowCountdown and not seenCutscene then
        startVideo('name');
        runTimer('dialogue' videoLength+0.8);
        allowCountdown = true;
        return Function_Stop
    end
end
function onTimerCompleted(t)
    if t == 'dialogue' then
        runDialogue('dialogue' 'music')
    end
end
```
