### ISSUE TITLE
songs wont load pls help (source)

### ISSUE THREAD

**Issue by Isaagomen** [ShadowMario/FNF-PsychEngine#8502]
### Describe your bug here.

*Songs wont load (source)*

### Command Prompt/Terminal logs (if existing)

```bash
*When i go into the game, i save the .json in the folder and the song too but when i try to load it after i leave and i come back, it says transformation-null (transformation is the song name)*
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

*Yes, custom menus*

**Comment by SnakDev** [comment]
it already got fixed get a new build
