### ISSUE TITLE
How do you set a players hp low or high rather then in the middle? (By using lua)

### ISSUE THREAD

**Issue by xXReb3caaXx** [ShadowMario/FNF-PsychEngine#8504]
### Describe your problem here.

How do you set a players hp low or high at the beginning of the song instead of putting its hp in the middle?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by keanu64github** [comment]
`setProperty('health', yourValue)` yourValue should be between 0 (instakill) and 2 (full health) idk why fnf doesnt do 0-100 but ok.
also, put this code in onCreatePost().

**Comment by Lorekeeper49** [comment]
> idk why fnf doesnt do 0-100 but ok.
It's using percentages which is always done in decimals
> between 0 (instakill) and 2 (full health) 
If it's between 0 and 2, does that mean you can have 200% hp or is 100% just the middle of the healthbar?  I thought the middle was 50%

**Comment by frantastic24** [comment]
HP can't go past 2, which is 100% health
