### ISSUE TITLE
Changing the achievement pictures into individual images.

### ISSUE THREAD

**Issue by TechnikTil** [ShadowMario/FNF-PsychEngine#8505]
### What feature do you want to get added on the **base** engine?

This isn't a thing to get added lol. Just it would be pretty nice to have the achievement icons in individual images.

Example:
![image](https://user-images.githubusercontent.com/89487150/167013475-24ec4cc4-8408-4152-aa41-1e5fdcb9d2ed.png)
a new folder called achievements then in there are the
![image](https://user-images.githubusercontent.com/89487150/167013719-1a4cdfd0-e58e-4903-a29e-ac6838845d60.png)
icons for the achievements. (The locked icon could be moved in there and it can be called its save tag)

In 150 x 150

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Stilic** [comment]
oh that's cool

**Comment by JVgradiz** [comment]
that is an good idea
