### ISSUE TITLE
Sustain notes are not shown outside of chart editor

### ISSUE THREAD

**Issue by snazzyostrich** [ShadowMario/FNF-PsychEngine#8507]
### Describe your bug here.

If a sustain note is used in a chart, it will appear as a normal note. I have tried remaking the chart, but the issue persists.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Where's the chart

**Comment by snazzyostrich** [comment]
In the data folder.

**Comment by frantastic24** [comment]
That is not what I meant
Send the file

**Comment by snazzyostrich** [comment]
I’ll try tomorrow

**Comment by Lorekeeper49** [comment]
This only happens to me when the BPM is below 150, any note with a length of one step will show as a normal note and anything longer will show as an actual long note

**Comment by snazzyostrich** [comment]
> This only happens to me when the BPM is below 150, any note with a length of one step will show as a normal note and anything longer will show as an actual long note What I described is normal

is there a way to fix it?

**Comment by Lorekeeper49** [comment]
> > This only happens to me when the BPM is below 150, any note with a length of one step will show as a normal note and anything longer will show as an actual long note What I described is normal
> 
> is there a way to fix it?

there is not

**Comment by snazzyostrich** [comment]
alr
