### ISSUE TITLE
making the notes invisible

### ISSUE THREAD

**Issue by glitchygmr** [ShadowMario/FNF-PsychEngine#8508]
### Describe your problem here.

I am trying to make the notes (the ones at the bottom, not the scrolling ones) invisible. I need help, as I've tried everything i can think of.
heres what i have so far, please tell me what i'm doing wrong
```
-- Event notes hooks
function onEvent(name, value1, value2)
	if name == 'invisible notes' then
		yesno = tonumber(value1);
		if yesno < 0 then
			yesno = 0;
		end

		if yesno == 0 then
			for i=0,4,1 do
				setPropertyFromGroup('playerStrums', i, 'alpha', 0)
				setPropertyFromGroup('opponentStrums', i, 'alpha', 0)
			end
		else
			for i=0,4,1 do
				setPropertyFromGroup('playerStrums', i, 'alpha', 1)
				setPropertyFromGroup('opponentStrums', i, 'alpha', 1)
			end
		end
		--debugPrint('Event triggered: ', name, yesno, targetAlpha);
	end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing in the base game, just in mods folders

**Comment by ManMaster707** [comment]
I think you can do this by just making an empty image with an xml identical to `NOTE_ASSETS.png` and then set it as the note's texture

**Comment by glitchygmr** [comment]
> I think you can do this by just making an empty image with an xml identical to `NOTE_ASSETS.png` and then set it as the note's texture

that might actually work, thank you
