### ISSUE TITLE
Hurt notes changes texture

### ISSUE THREAD

**Issue by AnthonyYTB** [ShadowMario/FNF-PsychEngine#8509]
### Describe your problem here.

I'm trying to put custom noteskin for my mod, but the problem is that when i use the noteskin, it also changes the hurt notes texture. How can i fix that?
### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing expect in the mod folders.

**Comment by Wither362** [comment]
Don’t use _, rename the noteskin deleting the _ and writing a space instead, and then you can do it!

**Comment by Wither362** [comment]
Hmm, I don’t know

**Comment by Wither362** [comment]
But what you can do is rename this issue to “hurt note changes texture”

**Comment by AnthonyYTB** [comment]
> But what you can do is rename this issue to “hurt note changes texture”

Yea good idea
