### ISSUE TITLE
Keys

### ISSUE THREAD

**Issue by TNT-King** [ShadowMario/FNF-PsychEngine#8511]
### What is your question?

What is the difference between: Pressed & justPressed in lua. cuz in haxe ik what it does, but for me justPressed works the same as pressed

**Comment by Shelvsk** [comment]
justPressed is to squeeze, Pressed is to hold

**Comment by Mastercopper2346** [comment]
justPressed has more keybind options

**Comment by AetherLynx** [comment]
**justPressed** executes the code ONCE if the key was held for 1 frame, **Pressed** executes the code for every frame the key is held.
