### ISSUE TITLE
SPRITES OBJECT REPEATING WHY

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#8514]
### What is your question?

I have a short question, how do i make my animated Sprite stop playing in a loop? (WITHOUT USING TIMER)

**Comment by Mastercopper2346** [comment]
in the line of objectPlayAnimation, turn true to false

**Comment by WilliamGaming12** [comment]
> in the line of objectPlayAnimation, turn true to false

By some reason, it freezes and i don't want that

`function onEvent(name, value1, value2)
	if name == 'mic' then

	objectPlayAnimation('wait', 'mic', 'mic throw', false);
	makeAnimatedLuaSprite('mic', 'mic', 400, 200);
	luaSpriteAddAnimationByPrefix('mic', 'mic', 'mic', 26, true);
	luaSpritePlayAnimation('mic', 'mic');
	scaleLuaSprite('mic', 1, 1); 
	addLuaSprite('mic', true);
	end
end`

**Comment by AetherLynx** [comment]
> By some reason, it freezes and i don't want that

i think it's because you're making the object play the animation when it hasn't even been created, try putting it at the bottom (under addLuaSprite)

**Comment by ShadowMario** [comment]
`luaSpriteAddAnimationByPrefix('mic', 'mic', 'mic', 26, true);`
Change true to false.
