### ISSUE TITLE
Events difficulty

### ISSUE THREAD

**Issue by Shelvsk** [ShadowMario/FNF-PsychEngine#8516]
### Describe your problem here.

how do i put events on certain difficulties? like: normal difficulty has events and hard difficulty has more events than normal difficulty

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

2 custom difficulties

**Comment by tylerandari12** [comment]
```
if difficulty == 0 then
     --code
end

--[[
0 = easy
1 = normal
2 = hard
]]
```

**Comment by Shelvsk** [comment]
I haver 2 new difficulties, i put 3 and 4 for It?

**Comment by Mastercopper2346** [comment]
I'm not actually sure about that.

**Comment by tylerandari12** [comment]
> I have 2 new difficulties, i put 3 and 4 for It?

Yes

It goes in the order their in when you scroll through the story menu...

**Comment by Lorekeeper49** [comment]
Events can actually be in the chart file itself, they don't have to be in a separate json, that separate events.json is only for if you want the events to happen on every difficulty

**Comment by Wither362** [comment]
If you save the `events.json`, those events will be in all the difficulties of that song, but if instead you didn’t saved the `events.json` and the differents difficulties have different events, those events will be loaded when you select the different difficulties

**Comment by Shelvsk** [comment]
Oh, thanks
