### ISSUE TITLE
how do i add a new difficaulty in psych engine 5.2h?

### ISSUE THREAD

**Issue by JacksRobotics** [ShadowMario/FNF-PsychEngine#8517]
### What is your question?

it says in the top

**Comment by CrusherMods** [comment]
on Source:
Go to the wiki it tells you
on Lua:
1. Go to the Week Editor
2. Click Other
3. 
![image](https://user-images.githubusercontent.com/90648119/167199639-83f2451b-c91b-41e6-a836-18d7c53a78fd.png)

**Comment by AbelitoGamerYT** [comment]
**If you're using the source, check this out:
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Adding-a-New-Difficulty**

**If you are using lua**, go to the "other" tab of the week editor and add the vanilla difficulties, plus the one you want to create (If you want, you can remove the vanilla difficulties so only your difficulty can be selected.)
![PsychEngine_KuGHYDhpBR](https://user-images.githubusercontent.com/77520810/167220349-69da49ed-5233-4f71-a76f-cc781f7db94f.png)

Then, In the images folder of your mod, you have to make a new folder called "menudifficulties" and put there the png of your new difficulty. (the image has to be named exactly as you put it in the week editor, in this example, my difficulty is called extreme, so my image is called the same)
![explorer_jPC8yKlrWh](https://user-images.githubusercontent.com/77520810/167220920-9842c533-99ae-47c4-a459-c7267dfcb5b9.png)

At this point you should be able to see your difficulty in your week in Story mode and freeplay.

Now obviously don't forget to add the new charts for this difficulty and name them like this
[NameOfTheSong]-[NameOfYourDifficulty]
Example:
![o0LAGOOhUB](https://user-images.githubusercontent.com/77520810/167221634-fc48e7f7-dd61-4526-8618-bd2355199aad.png)

Congratulations! Your new difficulty now works.

**Comment by Mastercopper2346** [comment]
For source:

**Go to CoolUtil.hx**

Around the top you should see
**public static var defaultDifficulties**Go ahead and add the difficulty.

And if you want to change "normal" in any way, you have do some further editing.

After that, go to **assets/preload/images/menudifficulties** and  add the image. (Make sure it's the exact SAME name)

Then, test it out.

**Comment by Theoyeah** [comment]
BOOO YOU SUCK GUYS WE DONT EVEN NEEED SOURCE FOR ADDING DIFFICULTYS

**Comment by JacksRobotics** [comment]
> BOOO YOU SUCK GUYS WE DONT EVEN NEEED SOURCE FOR ADDING DIFFICULTYS

yeah i know. but im using source to make mods with custom menus etc.
