### ISSUE TITLE
Psych engine crashes when playing a song, help :((

### ISSUE THREAD

**Issue by SE2607** [ShadowMario/FNF-PsychEngine#8518]
### Describe your problem here.

So I have this copy of psych engine 0.5.1 which i'm using for a mod, it uses source code and everything

Like 2 days ago I compiled it for something and **when I try to play a song the game just crashes**, even though I didn't even edit anything in the source, tho I do think it has to do with the source
And it happens literally in every song, not just the ones from the mod

if anyone knows a solution please tell me, I don't want this to happen again :((

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

just healthicon.hx, main.hx, titlestate.hx, playstate.hx, and creditstate.hx

**Comment by maxisepYT1** [comment]
Can you display the Terminal/Prompt when the game crashes?

**Comment by voxovistired** [comment]
Just as Max said previously, could you show Terminal when the game crashes and the line of code that is faulty if possible (given that it's a syntax error). Thank you 👍
