### ISSUE TITLE
how to make animated icons without source code

### ISSUE THREAD

**Issue by trollgeman** [ShadowMario/FNF-PsychEngine#852]
### Describe your problem here.

so uhhhhhh im makin a mod, im stupid dumb dumb so im using the mod folder to create it, and i wondered how you would make animated icons
does anybody know how to do this (without source code)?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no im using the mods folder

**Comment by siegereal** [comment]
you simply j

**Comment by trollgeman** [comment]
ok

**Comment by siegereal** [comment]
> ok

ok

**Comment by GrateSkata** [comment]
you can't. i've been modding since the dawn of times and everybody knows you can't even add your own songs without using the source code.

**Comment by trollgeman** [comment]
this is psych engine though-

**Comment by SrtHero278** [comment]
Yea this is psych engine. You can easily add mods. But for the animated icons, I don't know. You could try making the icons blank and make Animated Lua Sprites for the icons, but that means you have to do a bunch of tweens, figure out how to switch sprites if you're using a losing icon as well, and that's just complicated.

**Comment by GrateSkata** [comment]
mods folder barely even works, i didnt even know it exists

**Comment by drakonieyah** [comment]
> you can't. i've been modding since the dawn of times and everybody knows you can't even add your own songs without using the source code.

You can. Sounds like you just never bothered to look up how.

> mods folder barely even works, i didnt even know it exists

What it needs to do, it does. So to me it seems like you have some personal issues.

**Comment by GrateSkata** [comment]
bro you're an asshole, anyways i have more experience with kade engine then psych engine so dont look up to me for fuckin answers

**Comment by PoleyMagik** [comment]
> mods folder barely even works, i didnt even know it exists

Psych mod folder is actually pretty robust, it can do most things a mod would need to do perfectly fine. Unfortunately I don't think there is a way to have animated icons, tho i dont know all too much about controlling the hud elements so I could be wrong.

**Comment by drakonieyah** [comment]
> bro you're an asshole, anyways i have more experience with kade engine then psych engine so dont look up to me for fuckin answers

I'm an asshole? You are the one throwing shit around saying the engine doesn't work, when you are an imbecile who didn't bother to ask or look up why. If you've got nothing to say, then why do you comment under a post and give false info?

**Comment by Gavman69** [comment]
/\/\/\
facts

**Comment by Gavman69** [comment]
> > bro you're an asshole, anyways i have more experience with kade engine then psych engine so dont look up to me for fuckin answers
> 
> I'm an asshole? You are the one throwing shit around saying the engine doesn't work, when you are an imbecile who didn't bother to ask or look up why. If you've got nothing to say, then why do you comment under a post and give false info?

facts

**Comment by acap09** [comment]
so uhh, the question?

**Comment by ShadowMario** [comment]
Hide the original icons and make your own icon logic, it's too long for me to explain or even want to type it here.
I'd suggest checking PlayState.hx source code and studying how icons work to recreate it in Lua.

**Comment by lemonsxeed** [comment]
hey, i made a code for it, may not be the cleanest but it works
````lua
local addedVariable = 520

function onCreate()
    doTweenAlpha('iconDadFadeEventTween', 'iconP2', 0, 0.001, 'linear');
makeAnimatedLuaSprite('iconBounce', 'iconBounce', 520, 10)
    setLuaSpriteScrollFactor('iconBounce');
    addLuaSprite('iconBounce', true);
    setObjectOrder('iconBounce', 25)
    updateHitbox('iconBounce');
    setObjectCamera('iconBounce','hud');
end

function onBeatHit()
        addAnimationByPrefix('iconBounce', 'bounce', 'pico bounce idle', 24, true)
end

function onUpdate(elapsed)
function goodNoteHit(id, direction, noteType, isSustainNote)
if getProperty('health') < 2 then
removeLuaSprite('iconBounce',true)
    addedVariable = 820  - (600 * ((getProperty('health')/2)*100) *0.01)
    makeAnimatedLuaSprite('iconBounce', 'iconBounce', addedVariable, 10)
    setLuaSpriteScrollFactor('iconBounce');
    addLuaSprite('iconBounce', true);
    setObjectOrder('iconBounce', 25)
    updateHitbox('iconBounce');
    setObjectCamera('iconBounce','hud');
end
end
function noteMiss(id, direction, noteType, isSustainNote)
if getProperty('health') > 0.01 then
removeLuaSprite('iconBounce',true)
    addedVariable = 820  - (600 * ((getProperty('health')/2)*100) *0.01)
    makeAnimatedLuaSprite('iconBounce', 'iconBounce', addedVariable, 10)
    setLuaSpriteScrollFactor('iconBounce');
    addLuaSprite('iconBounce', true);
    setObjectOrder('iconBounce', 25)
    updateHitbox('iconBounce');
    setObjectCamera('iconBounce','hud');
end
end
end```` also change 'pico bounce idle' to your animation name on ur xml and change the /iconbounce to ur image, example: /funicharacterbounce
