### ISSUE TITLE
how to change .exe thingie

### ISSUE THREAD

**Issue by GamingIQ** [ShadowMario/FNF-PsychEngine#8520]
### Describe your problem here.

once you enter the psych engine folder it says like PsychEngine.exe I wanna change that to like AMOGUS.exe

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by voxovistired** [comment]
This is something you would most likely want to edit within the "Project.xml" file before compiling. This can be located on line 5 of the file.

**Comment by GamingIQ** [comment]
i said lua

**Comment by frantastic24** [comment]
rename the file genius

**Comment by maxisepYT1** [comment]
Rename the .exe file

**Comment by GamingIQ** [comment]
im an ide
