### ISSUE TITLE
how to add custom options (LUA)

### ISSUE THREAD

**Issue by GamingIQ** [ShadowMario/FNF-PsychEngine#8521]
### What is your question?

I would like to add youtube as an option anyway to help?

**Comment by voxovistired** [comment]
What do you mean by "add YouTube as an option"? You didn't really specify.

**Comment by GamingIQ** [comment]
I wanna add a brand new option on the main menu called Youtube that sends you to my YT channel

**Comment by frantastic24** [comment]
you can't

**Comment by voxovistired** [comment]
Not something that can be done within lua bud

**Comment by GamingIQ** [comment]
ok thanks

**Comment by BombasticTom** [comment]
> Not something that can be done within lua bud

if you download my mod on the other hand 😏

**Comment by GamingIQ** [comment]
ok, send the mod link plz?

**Comment by BombasticTom** [comment]
nvm i didn't read that you need it in main menu
you can use credits on the other hand
