### ISSUE TITLE
HOW TO ADD ANIMATED ICONS (source)

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8522]
### Describe your problem here.

I NEED THIS FOR MY PORT

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i did not.

**Comment by Mastercopper2346** [comment]
ehhhhhhhhhhhhhhhhhhhhhhhhh ill just use a lua script and put it in mods/scripts lol

**Comment by voxovistired** [comment]
Bro why did you close it then reopen it if you solved your own question...

**Comment by Mastercopper2346** [comment]
i did it so if anyone KNOWS how tp do it in source, THEY CAN TELL ME.

**Comment by SrtHero278** [comment]
```
iconP1.frames = Paths.getSparrowAtlas('icons/[ICONNAME]')
iconP2.frames = Paths.getSparrowAtlas('icons/[ICONNAME]')

iconP1.animation.addByPrefix('normal', 'normal', 24, true);
iconP2.animation.addByPrefix('normal', 'normal', 24, true);
```
I might be a Lua person, but I know how to make animations with Haxe.

**Comment by IdiotLimitedEdition** [comment]
Should I put them in PlayState?

**Comment by Mastercopper2346** [comment]
Yes.

**Comment by Emeninja972** [comment]
> ```
> iconP1.frames = Paths.getSparrowAtlas('icons/[ICONNAME]')
> iconP2.frames = Paths.getSparrowAtlas('icons/[ICONNAME]')
> 
> iconP1.animation.addByPrefix('normal', 'normal', 24, true);
> iconP2.animation.addByPrefix('normal', 'normal', 24, true);
> ```
> 
> I might be a Lua person, but I know how to make animations with Haxe.

What is P1 And P2 mean?

**Comment by C8tdan** [comment]
IconP1: the player's icon
IconP2: the opponent's icon

**Comment by davidfnf** [comment]
in what line do i put his on for psych engine 0.6.3?
