### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by Aden-Mystio** [ShadowMario/FNF-PsychEngine#8523]
### Describe your problem here.

What am I doing wrong with [this character](https://youtu.be/DYMTuaLGcxQ)
[Assets](https://drive.google.com/drive/folders/18vaX9VqcVKMQpqtcpvC03C5VgMBwYsq-?usp=sharing)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

idk what to put here

**Comment by XS09-dev** [comment]
Using lua.
Anyways. I genuinely have no idea but you could redo the json or xml. (Json using one of the working characters json) and xml by creating a new xml.

**Comment by Aden-Mystio** [comment]
> Using lua.
> Anyways. I genuinely have no idea but you could redo the json or xml. (Json using one of the working characters json) and xml by creating a new xml.

Nvm I got it working
