### ISSUE TITLE
MODCHART QUESTION/HELP

### ISSUE THREAD

**Issue by JustHuman0169** [ShadowMario/FNF-PsychEngine#8525]
### What is your question?

how should i make modchart like this: [in 44 sec in this vid](https://youtu.be/aZ-ezh6x814) 

anything source or lua

**Comment by Lorekeeper49** [comment]
Use the noteTweenAngle callback, how that works is in the wiki

**Comment by JustHuman0169** [comment]
> Use the noteTweenAngle callback, how that works is in the wiki
