### ISSUE TITLE
compiling problems

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#8526]
### Describe your problem here.

EVERY time i lime test it just after a lot of normal errors it says this:
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
i've tried everything; reinstalling multiple programs (haxe, git, even source code itself) but it would not solve it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Missing visual studio components

**Comment by BernardoGP4504** [comment]
No there's not anything missing, i think it is because that I have another
version of VSCode (2021) installed

Em sáb, 7 de mai de 2022 12:53, frantastic24 ***@***.***>
escreveu:

**Comment by frantastic24** [comment]
So that means you are missing components, and I'm pretty sure vscode version doesn't matter since that's just used to edit code, unless you meant studio

**Comment by BernardoGP4504** [comment]
What studio? And also what is missing?

Em sáb, 7 de mai de 2022 14:51, frantastic24 ***@***.***>
escreveu:

**Comment by neondev27** [comment]
go to Visual Studio İnstaller, select Change, Select İndividual Components and write MSVC in search bar, select 2017 versions of MSVC, download and try again

**Comment by BernardoGP4504** [comment]
> go to Visual Studio İnstaller, select Change, Select İndividual Components and write MSVC in search bar, select 2017 versions of MSVC, download and try again

didn't work

**Comment by neondev27** [comment]
> > go to Visual Studio İnstaller, select Change, Select İndividual Components and write MSVC in search bar, select 2017 versions of MSVC, download and try again
> 
> didn't work

ok
