### ISSUE TITLE
Difficulty Thing (Source)

### ISSUE THREAD

**Issue by FlintIshe** [ShadowMario/FNF-PsychEngine#8529]
### What is your question?

How can I move the difficulty thing to the upper of the week (Like In the picture)? But no matter what Y value I type it just goes left or right like the x value

Sorry i am bad at explaining
![exmaple](https://user-images.githubusercontent.com/101379721/167263366-b0882ded-ce23-44c5-9e6a-dcaef6bcde3f.png)

**Comment by Mastercopper2346** [comment]
there is usually one forcing the placement.

**Comment by FlintIshe** [comment]
> there is usually one forcing the placement.

then what should I do? I tried remove it from the group but It doesn't work

**Comment by FlintIshe** [comment]
Oh wait nvrm I just figured out I just need to type "sprDifficulty.offset" I am so stupid
