### ISSUE TITLE
trying to compile but got an error

### ISSUE THREAD

**Issue by frrozenjr** [ShadowMario/FNF-PsychEngine#853]
### Describe your problem here.

got this while compiling

Called from ? line 1
Called from CommandLineTools.hx line 1895
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 125
Called from CommandLineTools.hx line 1703
Called from lime/tools/ProjectXMLParser.hx line 21
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 50
Called from lime/tools/ProjectXMLParser.hx line 2043
Called from lime/tools/ProjectXMLParser.hx line 1528
Called from lime/tools/ProjectXMLParser.hx line 608
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 709
Called from /Users/runner/hostedtoolcache/haxe/4.2.1/x64/std/neko/_std/sys/FileSystem.hx line 69
Called from /Users/runner/hostedtoolcache/haxe/4.2.1/x64/std/neko/_std/sys/FileSystem.hx line 60
Uncaught exception - std@sys_file_type

any help?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited a lot of stuff for stages and notes also added a new file called Shaders.hx which is taken from dave and bambi mod.

**Comment by ShadowMario** [comment]
Can't help with Shader stuff specially considering it is taken from another mod.
