### ISSUE TITLE
how to add loading screens LUA

### ISSUE THREAD

**Issue by GamingIQ** [ShadowMario/FNF-PsychEngine#8531]
### What is your question?

how to add loading screens before song plz help

**Comment by EnzoMunizz0** [comment]
Unfortunately there's no way to do that, at least so far

**Comment by GamingIQ** [comment]
umm, how to use it?

**Comment by keanu64github** [comment]
You have to put the script in the scripts folder then the (something like)
“loading whatever” in mods/images (or your mod folder images)

**Comment by GamingIQ** [comment]
whoops forgot to close it
