### ISSUE TITLE
The Paloose Note (Golden Apple 1.2)

### ISSUE THREAD

**Issue by MateuszCoder** [ShadowMario/FNF-PsychEngine#8534]
### Describe your problem here.

i need the Paloose notes from GApple 1.2 from Ferocious. and yes lua. 0.5.2h

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

uhhhhhhh.....

**Comment by voxovistired** [comment]
Sounds like a problem you would have to deal with. This doesn't have any regards to your code once so ever. If you want the notes just go through the asset folder of the mod and find it yourself.

**Comment by SrtHero278** [comment]
make a lua file in [ModFolder]/custom_notetypes.
then put stuff in the lua file.

**Comment by MateuszCoder** [comment]
> make a lua file in [ModFolder]/custom_notetypes. then put stuff in the lua file.

ok but i wan't to know how to make the arrows move

**Comment by MateuszCoder** [comment]
oh WAIT I GOT IT!!!

**Comment by MateuszCoder** [comment]
> oh WAIT I GOT IT!!!

and it's this!
```
local this = 50
function goodNoteHit(id, noteData, noteType, isSustainNote)
	if noteType == 'Paloose Note' then
		noteTweenY('move',0,this,0.01,'linear');
		noteTweenY('move1',1,this,0.01,'linear');
		noteTweenY('move2',2,this,0.01,'linear');
		noteTweenY('move3',3,this,0.01,'linear');
		noteTweenY('move4',4,this,0.01,'linear');
		noteTweenY('move5',5,this,0.01,'linear');
		noteTweenY('move6',6,this,0.01,'linear');
		noteTweenY('move7',7,this,0.01,'linear');
		this = this + 3;
	end
end
```

**Comment by PrismLight** [comment]
OMG SHADOWMARIO MADE A LABEL FOR DAVE AND BAMBI YAY

**Comment by REALHaydenGaming** [comment]
Made it since GA 1.2 launch.
