### ISSUE TITLE
How to put Shaders in the Shaders Folder in Mods

### ISSUE THREAD

**Issue by Enmadaio999** [ShadowMario/FNF-PsychEngine#8535]
### Describe your problem here.

How I can make a shader able for Psych Engine, cuz I wanna try with a RBG Shader I found on ShaderToy but it doesn't work.
PD: I tried with the vhs shader I found on Game Over Files, but nothing

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ActualeAnEggDog** [comment]
shadow mario forgot to delete this folder.
