### ISSUE TITLE
TITLE MENU PROBLEM

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#8536]
### Describe your problem here.

First of all, i wanna change the beat hit of the title screen but i don't find the part where the code is, can someone tell me where is it?

What i've meant with that is by changing how fast the GF dance title moves and the same with the logo

And i don't think u can make this on Lua, if someone achieves to do it in Lua, can he pass the script?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by frantastic24** [comment]
gfDanceTitle.json

**Comment by CrusherMods** [comment]
in gfDanceTitle.json
you can change the bpm there

**Comment by WilliamGaming12** [comment]
bruh im so dumb, thank you guys
