### ISSUE TITLE
I use winning icons but I want to make them animated

### ISSUE THREAD

**Issue by Djlethug** [ShadowMario/FNF-PsychEngine#8539]
### Describe your problem here.

I saw many scripts for animated icons but since I use 3 icons (neutral,losing and winning) I wanted to ask if someone can help me
(Source or lua)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I was updating to the newer version so yeah

**Comment by enjayar0625** [comment]
just copy and paste the code of the neutral/losing icons then edit it to the winning icons thing
