### ISSUE TITLE
Animations Not assigning

### ISSUE THREAD

**Issue by BoiNoName** [ShadowMario/FNF-PsychEngine#854]
### Describe your bug here.

so to make it short
I'm currently trying to add a new character into pysch engine, 
I've put the sprite sheet and xml file into the character folder
Went on pysch , went on character editor, and chose pico, and reloaded the image
As i went to assign the animations , whenever i did it would always jsut stay as the first sprite shown on the sprite sheet and nothing would change
I've tried remaking both the sprite sheet and the xml but to no avail.

Sorry im bad with discribing things so i hope this video would help explain my issue (i had to use a google drive link since the video is too big for github)
https://drive.google.com/file/d/1g4MndMrJcbiLVXTFkdKG6tXEFXRjxVGW/view?usp=sharing

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by titopops** [comment]
there is no animation chosen for the animation, go in the xml file and put for example, for the idle animation, if your idle animation for the character is BF idle dance, then put that in, something like this
![image](https://user-images.githubusercontent.com/93490646/140626477-1d251588-59ca-4d64-ae4e-36e69b808bd4.png)
also, if your still having problems with animations, FNF is case senstive, so if you put bf idle dance instead of BF idle dance, then the animation doesn't work

**Comment by BoiNoName** [comment]
I tried changing the name in the xml to something different and to "idle dance" but no matter what, it would still just do "idle (ERROR!)" and same goes for any other animation i put, it just goes "*animation name* (ERROR!)" and nothing at all has changed :/

**Comment by titopops** [comment]
> I tried changing the name of the animations in the xml to something different and to "idle dance" with idle but no matter what, it would still just do "idle (ERROR!)" and same goes for any other animation i put, it just goes "_animation name_ (ERROR!)" and nothing at all has changed :/

i think i confused you? it would be something like this

![image](https://user-images.githubusercontent.com/93490646/140630866-06a4c0eb-ebbc-4c79-8026-fd0e7a47c8a3.png)

![image](https://user-images.githubusercontent.com/93490646/140630880-d3ea491b-09e9-422b-baf0-77f74d24b77d.png)

![image](https://user-images.githubusercontent.com/93490646/140630882-a38c2c80-289d-4de4-bdbc-fb16e2ad933b.png)


tbh i have no idea if that helped but to be fair i have no idea how your doing this

**Comment by BoiNoName** [comment]
> > I tried changing the name of the animations in the xml to something different and to "idle dance" with idle but no matter what, it would still just do "idle (ERROR!)" and same goes for any other animation i put, it just goes "_animation name_ (ERROR!)" and nothing at all has changed :/
> 
> i think i confused you? it would be something like this
> 
> ![image](https://user-images.githubusercontent.com/93490646/140630866-06a4c0eb-ebbc-4c79-8026-fd0e7a47c8a3.png)
> 
> ![image](https://user-images.githubusercontent.com/93490646/140630880-d3ea491b-09e9-422b-baf0-77f74d24b77d.png)
> 
> ![image](https://user-images.githubusercontent.com/93490646/140630882-a38c2c80-289d-4de4-bdbc-fb16e2ad933b.png)
> 
> tbh I have no idea if that helped but to be fair i have no idea how your doing this

Yea- I did get a bit confused sorry about that

But i remade the xml to put for example "Kyanh Idle" , "Kyanh Down" , Etc but the same error still occurs 

and if it helps the way I'm doing this is that I'm using the spritesheet + xml generator (https://gamebanana.com/tools/7136)
I select the frames and give them an animation prefix, then i export it and put it into the characters folder
and if helps further I recorded the process: https://drive.google.com/file/d/1NzlccEn4X5MXPA-IeKZw8a1nhwuxMt9j/view?usp=sharing

**Comment by titopops** [comment]
> > > I tried changing the name of the animations in the xml to something different and to "idle dance" with idle but no matter what, it would still just do "idle (ERROR!)" and same goes for any other animation i put, it just goes "_animation name_ (ERROR!)" and nothing at all has changed :/
> > 
> > 
> > i think i confused you? it would be something like this
> > ![image](https://user-images.githubusercontent.com/93490646/140630866-06a4c0eb-ebbc-4c79-8026-fd0e7a47c8a3.png)
> > ![image](https://user-images.githubusercontent.com/93490646/140630880-d3ea491b-09e9-422b-baf0-77f74d24b77d.png)
> > ![image](https://user-images.githubusercontent.com/93490646/140630882-a38c2c80-289d-4de4-bdbc-fb16e2ad933b.png)
> > tbh I have no idea if that helped but to be fair i have no idea how your doing this
> 
> Yea- I did get a bit confused sorry about that
> 
> But i remade the xml to put for example "Kyanh Idle" , "Kyanh Down" , Etc but the same error still occurs
> 
> and if it helps the way I'm doing this is that I'm using the spritesheet + xml generator (https://gamebanana.com/tools/7136) I select the frames and give them an animation prefix, then i export it and put it into the characters folder and if helps further I recorded the process: https://drive.google.com/file/d/1NzlccEn4X5MXPA-IeKZw8a1nhwuxMt9j/view?usp=sharing

if you want, i could try to assign the animations myself

**Comment by BoiNoName** [comment]
> > > > I tried changing the name of the animations in the xml to something different and to "idle dance" with idle but no matter what, it would still just do "idle (ERROR!)" and same goes for any other animation i put, it just goes "_animation name_ (ERROR!)" and nothing at all has changed :/
> > > 
> > > 
> > > i think i confused you? it would be something like this
> > > ![image](https://user-images.githubusercontent.com/93490646/140630866-06a4c0eb-ebbc-4c79-8026-fd0e7a47c8a3.png)
> > > ![image](https://user-images.githubusercontent.com/93490646/140630880-d3ea491b-09e9-422b-baf0-77f74d24b77d.png)
> > > ![image](https://user-images.githubusercontent.com/93490646/140630882-a38c2c80-289d-4de4-bdbc-fb16e2ad933b.png)
> > > tbh I have no idea if that helped but to be fair i have no idea how your doing this
> > 
> > 
> > Yea- I did get a bit confused sorry about that
> > But i remade the xml to put for example "Kyanh Idle" , "Kyanh Down" , Etc but the same error still occurs
> > and if it helps the way I'm doing this is that I'm using the spritesheet + xml generator (https://gamebanana.com/tools/7136) I select the frames and give them an animation prefix, then i export it and put it into the characters folder and if helps further I recorded the process: https://drive.google.com/file/d/1NzlccEn4X5MXPA-IeKZw8a1nhwuxMt9j/view?usp=sharing
> 
> if you want, i could try to assign the animations myself
Sure! 
Thank you so much!
![Kyanh](https://user-images.githubusercontent.com/65833167/140654213-8afb916d-90c9-4c53-8f35-0e978f338b5d.png)
(had to put the xml on google drive again since it isnt compatible :/) https://drive.google.com/file/d/1c47ygFoo7jj2Zh2bBUz569fpXMntcTk5/view?usp=sharing

**Comment by titopops** [comment]
[you are the welcome.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/7492773/you.are.the.welcome.zip)
k here

**Comment by BoiNoName** [comment]
> [you are the welcome.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/7492773/you.are.the.welcome.zip) k here

Okii again thank you so so much for the help i cant thank you enough
i've been trying to fix this for hours, so thank you so so much ^v^
