### ISSUE TITLE
I need help with stage (asking again because no one really answered)

### ISSUE THREAD

**Issue by Aden-Mystio** [ShadowMario/FNF-PsychEngine#8540]
### Describe your problem here.

https://youtu.be/Hvh7qhxJ1mM
I need some help with my stage
function onCreate()
-- background shit
makeLuaSprite('stageback', 'Avastage', -400, -300);
setScrollFactor('stageback', 1.10, 1.10);

makeLuaSprite('stagefront', 'Cameos', -400, 300);
setScrollFactor('stagefront', 0.9, 0.9);
scaleObject('stagefront', 1.10, 1.10);

addLuaSprite('stageback', false);
addLuaSprite('stagefront', false);

close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by voxovistired** [comment]
You can't just say you need help with the stage and not specify the problem.

**Comment by Aden-Mystio** [comment]
> You can't just say you need help with the stage and not specify the problem. 

Watch the video

**Comment by voxovistired** [comment]
> > You can't just say you need help with the stage and not specify the problem.
> 
> Watch the video

It means that it's poorly positioned, I would suggest adjusting the y axis of the "stageback." Assuming there isn't an issue with the scroll factor (which I would assume there isn't.)

**Comment by Aden-Mystio** [comment]
> > > You can't just say you need help with the stage and not specify the problem.
> > 
> > Watch the video
> 
> It means that it's poorly positioned, I would suggest adjusting the y axis of the "stageback." Assuming there isn't an issue with the scroll factor (which I would assume there isn't.)

How do I change the Y-axis?

**Comment by voxovistired** [comment]
> > > > You can't just say you need help with the stage and not specify the problem.
> > > 
> > > 
> > > Watch the video
> > 
> > 
> > It means that it's poorly positioned, I would suggest adjusting the y axis of the "stageback." Assuming there isn't an issue with the scroll factor (which I would assume there isn't.)
> 
> How do I change the Y-axis?

I'll provide a screenshot of something that I found that will be useful for you
![Screenshot_1559](https://user-images.githubusercontent.com/66130669/167276293-0a2e3918-0715-4090-a1f5-32e65dd3747c.png)
!

**Comment by Aden-Mystio** [comment]
I don't really get LUA but thank you

**Comment by voxovistired** [comment]
> I don't really get LUA but thank you

You're welcome :)

**Comment by frantastic24** [comment]
Reading the wiki is helpful

**Comment by FlintIshe** [comment]
If you wanna make a animated sprite on your stage just put

makeAnimatedLuaSprite('tags', 'ursprite', 'x', 'y')
addAnimationByPrefix('tags', 'idle', 'animation in xml', 24, 'true') --true means it loops, false means no loops
objectPlayAnimation('tags', true);

addLuaSprite('tags', true) --true means it's in front of the character, false means its behind the character
