### ISSUE TITLE
Changing countdown sprites

### ISSUE THREAD

**Issue by YKoF-CALm** [ShadowMario/FNF-PsychEngine#8541]
### Describe your problem here.

Title is pretty self-explanatory. I'm pretty sure this has been asked before, but I can't find any answers for this.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing.

**Comment by bacondanger** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API#example-scripts 
use the "Changing Game Over Sprites/Sounds" file and set the file names to the name of the 3, 2, 1, go assets.

I have no idea if this will work, this is just me guessing.

**Comment by frantastic24** [comment]
Place your files inside `images`, names must match with base files

**Comment by Lorekeeper49** [comment]
use this and change the names as needed to make the sperate 3 2 1 counter be for a specific song, just make sure it's in that song's data folder
[script.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8646480/script.txt)

**Comment by YKoF-CALm** [comment]
> use this and change the names as needed to make the sperate 3 2 1 counter be for a specific song, just make sure it's in that song's data folder [script.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8646480/script.txt)

I've tried this method before, but it will overlap the normal countdown sprites themselves.

**Comment by YKoF-CALm** [comment]
> Place your files inside `images`, names must match with base files

I know that will work, but I want to change this for specific songs only. Probably should've added that into the title, sorry.

**Comment by YKoF-CALm** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API#example-scripts use the "Changing Game Over Sprites/Sounds" file and set the file names to the name of the 3, 2, 1, go assets.
> 
> I have no idea if this will work, this is just me guessing.

I don't think this will work, since the sprites are in Playstate, and the script is changing variables in the GameOverSubstate.

**Comment by enjayar0625** [comment]
> > https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API#example-scripts use the "Changing Game Over Sprites/Sounds" file and set the file names to the name of the 3, 2, 1, go assets.
> > I have no idea if this will work, this is just me guessing.
> 
> I don't think this will work, since the sprites are in Playstate, and the script is changing variables in the GameOverSubstate.

i think just do what the guy said and put the images in mods/images then if u want specific song put the WhateverSubState script into the song's data folder

idk but it might work

**Comment by frantastic24** [comment]
> for specific songs only

That's also possible, you can just make them invisible and then create and tween/animate/whatever your own

```lua
function onCountdownTick(counter)
     setProperty('countdownReady.visible', 0)
     setProperty('countdownSet.visible', 0)
     setProperty('countdownGo.visible', 0)

     if counter == 0 then -- "Three"
          -- there usually isn't a sprite here
     elseif counter == 1 then -- "Two"
          -- "ready?" sprite
     elseif counter == 2 then -- "One"
          -- "set!?" sprite
     elseif counter == 3 then -- "Go"
          -- "go!" sprite
     end
end
```
That's just the base of the code because idk how you want your countdown to look like

**Comment by YKoF-CALm** [comment]
> > for specific songs only
> 
> That's also possible, you can just make them invisible and then create and tween/animate/whatever your own
> 
> ```lua
> function onCountdownTick(counter)
>      setProperty('countdownReady.visible', 0)
>      setProperty('countdownSet.visible', 0)
>      setProperty('countdownGo.visible', 0)
> 
>      if counter == 0 then -- "Three"
>           -- there usually isn't a sprite here
>      elseif counter == 1 then -- "Two"
>           -- "ready?" sprite
>      elseif counter == 2 then -- "One"
>           -- "set!?" sprite
>      elseif counter == 3 then -- "Go"
>           -- "go!" sprite
>      end
> end
> ```
> 
> That's just the base of the code because idk how you want your countdown to look like

I see. I'll give it a go.

**Comment by YKoF-CALm** [comment]
> > for specific songs only
> 
> That's also possible, you can just make them invisible and then create and tween/animate/whatever your own
> 
> ```lua
> function onCountdownTick(counter)
>      setProperty('countdownReady.visible', 0)
>      setProperty('countdownSet.visible', 0)
>      setProperty('countdownGo.visible', 0)
> 
>      if counter == 0 then -- "Three"
>           -- there usually isn't a sprite here
>      elseif counter == 1 then -- "Two"
>           -- "ready?" sprite
>      elseif counter == 2 then -- "One"
>           -- "set!?" sprite
>      elseif counter == 3 then -- "Go"
>           -- "go!" sprite
>      end
> end
> ```
> 
> That's just the base of the code because idk how you want your countdown to look like

Yep, this works, thanks.
