### ISSUE TITLE
Videos Won't Play On Linux Even With VLC Installed

### ISSUE THREAD

**Issue by Gibberditoslumber** [ShadowMario/FNF-PsychEngine#8542]
### Describe your bug here.

When A Lua File Try's To Load A Video (.mp4 or .webm) It Will Result In The Terminal Saying "Segmentation fault (core dumped)" Even After I Intalled VLC

### Command Prompt/Terminal logs (if existing)

```bash
Segmentation fault (core dumped)
```
### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

None

**Comment by voxovistired** [comment]
The VLC stuff that is currently used only works for windows (currently)

**Comment by Gibberditoslumber** [comment]
i saw code for VLC support on linux

**Comment by Gibberditoslumber** [comment]
i saw code for VLC support in FNF-PsychEngine/git/source/vlc/cpp/lib/linux

**Comment by voxovistired** [comment]
As I've said. It only works with Windows. This issue has been discussed multiple times. It is a known bug.

**Comment by Gibberditoslumber** [comment]
ok

**Comment by Gibberditoslumber** [comment]
I Made A Commit That Will Fix This Problem So No More Complaining From Me
