### ISSUE TITLE
How to put a Dodge Event and Attack Script in Psych Engine 5.2 (No Source)

### ISSUE THREAD

**Issue by Enmadaio999** [ShadowMario/FNF-PsychEngine#8543]
### Describe your problem here.

How I can put a dodge and attack event in Psych Engine

Requirements:
Dodge Event:
- No image alert
- When the Space is pressed, an image will make an animation
Attack Script:
- When the Shift is pressed, an image will make an animation
- The Attack Script will only be active to use when a Parry Note is pressed

and yea I wanna make Devil's Gambit Psych Port

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SrtHero278** [comment]
put a txt and a lua file in <ModFolder>/custom_events.
then put stuff in the lua file.
