### ISSUE TITLE
Unknown Compilation Issue.

### ISSUE THREAD

**Issue by JamieleBrown** [ShadowMario/FNF-PsychEngine#8544]
### Describe your problem here.

Im trying to compile the game, but whenever I do, it just does this, I'm not sure why it happens and I don't know how to stop it, please help me!

![Screenshot (473)](https://user-images.githubusercontent.com/30990630/167282409-3a66fd84-4be4-40fc-90dc-ee48262820d4.png)

Extra info: The error may appear more than once, at the max 3 times.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited clientprefs.hx to add two new configs, an attack and a dodge.
I also edited titlestate.hx to change the intro to the game.

**Comment by Wither362** [comment]
Reinstall haxe 4.2.4 and reinstall the things you have to install to compile

**Comment by JamieleBrown** [comment]
I just tried that, and it still provided the same error
