### ISSUE TITLE
Is it possible to change the speed of the notes during the song?

### ISSUE THREAD

**Issue by GidraCreeper750** [ShadowMario/FNF-PsychEngine#8545]
### What is your question?

Maybe there is a special event or something like that for this? If not, is there any other way to do something like this?

**Comment by enjayar0625** [comment]
yes

**Comment by GidraCreeper750** [comment]
> yes

How?

**Comment by frantastic24** [comment]
There is an event

**Comment by Lorekeeper49** [comment]
the event is called 'change scroll speed'

**Comment by GidraCreeper750** [comment]
> the event is called 'change scroll speed'

Ah... got it... Why am I so dumb and didn't notice it all the time. Thanks

**Comment by frantastic24** [comment]
You can close this now

**Comment by tylerandari12** [comment]
`triggerEvent("Change Scroll Speed", "speed", "duration")` if you want to use it in a script.

However it is safe to close now...

**Comment by ImaginationSuperHero528** [comment]
> `triggerEvent("Change Scroll Speed", "speed", "duration")` if you want to use it in a script.
> 
> However it is safe to close now...

yes... yes it is

**Comment by Martinelplayz** [comment]
> `triggerEvent("Change Scroll Speed", "speed", "duration")` if you want to use it in a script.
> 
> However it is safe to close now...

sorry to necropost but how exactly would you be able to make the duration permanent for the rest of the song?

**Comment by Lorekeeper49** [comment]
> > `triggerEvent("Change Scroll Speed", "speed", "duration")` if you want to use it in a script.
> > However it is safe to close now...
> 
> yes... yes it is

since the duration is defined in seconds, you can make the duration set to as many seconds the song is and it will increase as the song progresses

**Comment by tylerandari12** [comment]
> > > `triggerEvent("Change Scroll Speed", "speed", "duration")` if you want to use it in a script.
> > > However it is safe to close now...
> > 
> > 
> > yes... yes it is
> 
> since the duration is defined in seconds, you can make the duration set to as many seconds the song is and it will increase as the song progresses

Hold up...
