### ISSUE TITLE
Winning icons not working

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8547]
### Describe your bug here.

Im using 0.5.2h, and winning icons are not working.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, not really

**Comment by frantastic24** [comment]
Reporting a bug of a feature that doesn't exist

**Comment by Mastercopper2346** [comment]
bruh

**Comment by Mastercopper2346** [comment]
there are like 100000 videos like:
https://www.youtube.com/watch?v=BqLyi-IqzwY
https://www.youtube.com/watch?v=hWhVck6emII
https://www.youtube.com/watch?v=8CCNf7tB7ng
https://www.youtube.com/watch?v=fI3_4P6tKtw
https://www.youtube.com/watch?v=7yD6dWJTQxc
and so on.

**Comment by CrusherMods** [comment]
> there are like 100000 videos like: https://www.youtube.com/watch?v=BqLyi-IqzwY https://www.youtube.com/watch?v=hWhVck6emII https://www.youtube.com/watch?v=8CCNf7tB7ng https://www.youtube.com/watch?v=fI3_4P6tKtw https://www.youtube.com/watch?v=7yD6dWJTQxc and so on.

yeah but its not in the base engine itself
those are just tutorials for your own mods
therefore you can add winning icons but its not a feature in the base engine itself

**Comment by frantastic24** [comment]
> there are like 100000 videos

Then you can go through those 100000 videos to see what you did wrong

**Comment by Mastercopper2346** [comment]
thing is, i did everything right, but in the result, the frames are messed up.
and the "winning icon frame" is the "losing frame" somehow.

**Comment by Mastercopper2346** [comment]
nvm, i found my error
