### ISSUE TITLE
ADD SHADERS BACK

### ISSUE THREAD

**Issue by luacoder279** [ShadowMario/FNF-PsychEngine#8548]
### What feature do you want to get added on the **base** engine?

ADD DA SHADERS BACK!!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by ManMaster707** [comment]
damn chill (also you failed the test)

**Comment by SonicProYT** [comment]
use demolition engine
it has shaders

**Comment by CrusherMods** [comment]
bro failed the test

**Comment by NS-Unfair** [comment]
Chill, shaders are still in Psych Engine. Shaders are just being softcoded.

**Comment by PrismLight** [comment]
funni dab kids

**Comment by JVgradiz** [comment]
wath are shaders?

**Comment by PrismLight** [comment]
> wath are shaders?

GLSL code that can create or modify sprites in a way.

**Comment by JVgradiz** [comment]
> > wath are shaders?
> 
> GLSL code that can create or modify sprites in a way.

Thanks
