### ISSUE TITLE
Title Screen Easter Eggs

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [ShadowMario/FNF-PsychEngine#8550]
### Describe your bug here.

Uh for me the images don't work there just have's logo.
[Click me for a video.](https://youtu.be/-C_Sx1xo4lE)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Base 0.5.2h

**Comment by tylerandari12** [comment]
The Images have had their names changed or don't exist at all...
Try reinstalling the game to fix this. (And don't forget to save your mods.)

**Comment by NS-Unfair** [comment]
This easter egg was removed due to something that has happened. They forgot to remove the easter egg code, so you can still access this title screen easter egg. So reinstalling will do nothing because the easter egg assets don't exist anymore.

**Comment by frantastic24** [comment]
Is this a fresh install or did you just replace files

**Comment by ImaginationSuperHero528** [comment]
> Is this a fresh install or did you just replace files

Replace

**Comment by frantastic24** [comment]
Did you replace the manifest folder

**Comment by ImaginationSuperHero528** [comment]
> Did you replace the manifest folder

yes

**Comment by frantastic24** [comment]
It always worked fine for me so just do a fresh install because you likely missed something when updated
