### ISSUE TITLE
Scroll Speed Arrow Type

### ISSUE THREAD

**Issue by Martinelplayz** [ShadowMario/FNF-PsychEngine#8552]
### Describe your problem here.

I'm trying to make a new arrow type that changes the scroll speed when missed.
but i have no idea how. my main issue is that i don't know how to **FIND** the scroll speed (variable? property?) and change it by a specific amount. on top of that i may want to set an timer, and when the timer is up to set the scroll speed back to normal.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no. i have not

**Comment by Mastercopper2346** [comment]
you have to use `triggerEvent`.

**Comment by Lorekeeper49** [comment]
```lua
local newSpeed = 1.01 --change to a different value if you don't want it to increase each miss
function noteMiss(i,d,t,l)
    if t == 'your note' then
        triggerEvent('Change Scroll Speed', newSpeed, 'change time in seconds')
        newSpeed = newSpeed + 0.01 --for increasing the speed each miss
    end
end
