### ISSUE TITLE
Changing the difficulty in charting mode crashes game

### ISSUE THREAD

**Issue by NS-Unfair** [ShadowMario/FNF-PsychEngine#8553]
### Describe your bug here.

Basically, if you try to change the difficulty, the game crashes.

How to reproduce the bug:
  1.  Go into charting mode
  2.  Change the time to any time
  4. Try changing the difficulty

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Other than a Lua script that says "Hello World," none.

**Comment by SnakDev** [comment]
Sir, how the frick do you change the difficulty in the chart editor? Because it's impossible.
