### ISSUE TITLE
Conditions for knowing what character is over BF

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#8555]
### Describe your problem here.

In more detail, I wanted to use a lua script to play different sounds for different characters in the game over screen.
Example 1: Bob's Onslaught - When BF gets spiked, you hear completely different sounds that Bob actually killed BF.
Example 2: Tord Red Fury - When BF gets shot, you hear different sounds for when Tord kills BF.

Could anyone give me code for a conditional to test what character is replacing BF?
Note: I am NOT SAYING I NEED CODE FOR CUSTOM GAMEOVER SCREENS. I need this to do different Gameover Screens for Different Characters.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, External Mod Folder.

**Comment by frantastic24** [comment]
```lua
function onGameOver()
     if boyfriendName == 'name' then

     end
end
```

**Comment by fnfdemonboi314159** [comment]
thanks dude, really appreciate it!
