### ISSUE TITLE
Discord RPC Update.

### ISSUE THREAD

**Issue by InsKal** [ShadowMario/FNF-PsychEngine#8556]
### What feature do you want to get added on the **base** engine?

Well, basically i want to request a change for discord RPC in Psych Engine, so, when you are in a song, the engine should search for the Opponent Json Name, so It should be like _"Battling Against (Opponent Json Name)!"_, And the stuff of the song name and that stuff that is already un the discord RPC.

(I don't know if I explained well)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
You can already change it yourself

**Comment by Mastercopper2346** [comment]
> You can already change it yourself

You can, you need to know know to do it though.

**Comment by frantastic24** [comment]
Not like it's hard

**Comment by tylerandari12** [comment]
> Not like it's hard

How exactly do you do it then?

**Comment by frantastic24** [comment]
```lua
changePresence('details', 'state', 'smallImageKey', hasStartTimestamp, endTimestamp)
```

**Comment by tylerandari12** [comment]
> ```lua
> changePresence('details', 'state', 'smallImageKey', hasStartTimestamp, endTimestamp)
> ```

I just discovered you need to put this in `onUpdate()` or `onUpdatePost()` because this thing is updating like a bottle rocket.

**Comment by tylerandari12** [comment]
>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by InsKal** [comment]
> You can already change it yourself

yeah but that being in the unmodified psych engine would be cool, or at least i think that is cool

**Comment by frantastic24** [comment]
but i just told you it is ???

**Comment by frantastic24** [comment]
> I just discovered you need to put this in `onUpdate()` or `onUpdatePost()`

no you don't, all the callbacks you need to properly update it already exist

**Comment by tylerandari12** [comment]
> > I just discovered you need to put this in `onUpdate()` or `onUpdatePost()`
> 
> no you don't, all the callbacks you need to properly update it already exist

Not for me.
Ill change it to one thing and its instantly back to "Tutorial-Hard 0:00"

**Comment by frantastic24** [comment]
`onSongStart()` works fine here
![image](https://user-images.githubusercontent.com/95725102/167516491-10d4659c-9b16-4320-ac26-a4b1c681159e.png)

**Comment by tylerandari12** [comment]
> `onSongStart()` works fine here ![image](https://user-images.githubusercontent.com/95725102/167516491-10d4659c-9b16-4320-ac26-a4b1c681159e.png)

Oh I was talking the Time at the bottom.
But the top works fine.

**Comment by frantastic24** [comment]
works fine here too

**Comment by tylerandari12** [comment]
Good :D

**Comment by tylerandari12** [comment]
While this is still relevant how does the `smallImageKey` work?

**Comment by frantastic24** [comment]
it grabs the opponent's icon and uses it as a small icon, it only works with base game characters
![image](https://user-images.githubusercontent.com/95725102/167518666-6be23d3d-bf5d-48e3-8b87-d4ce2cc9d2b8.png)

**Comment by tylerandari12** [comment]
Ok makes semse.
Thanks.

**Comment by frantastic24** [comment]
this should've been closed already

**Comment by tylerandari12** [comment]
Not my issue...

**Comment by tylerandari12** [comment]
Seriously I cant close...

**Comment by tylerandari12** [comment]
@InsKal You can close this now lol

**Comment by InsKal** [comment]
> @InsKal You can close this now lol

ok

**Comment by frantastic24** [comment]
There's no grid and that's not how it works
The icon needs to exist in discord's database for the game, which we obviously don't have access to

**Comment by Noel3454565FNF** [comment]
sorry i forgor ;-;
