### ISSUE TITLE
Combo Textures

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8558]
### What is your question?

Is it possible to change the texture of the combo stuff?

Like when it says "Combo", "Sick", "Good", "Bad", "Sh*t" and the numbers?

This is not for a golden apple port...

And I'm on Lua...

**Comment by tylerandari12** [comment]
I should mention this is NOT for a golden apple port...

**Comment by tylerandari12** [comment]
One more thing...
I'm on Lua...

**Comment by tylerandari12** [comment]
But how to change them with Lua?

**Comment by frantastic24** [comment]
You can't

**Comment by tylerandari12** [comment]
> You can't

Nuuuuuuuu...
