### ISSUE TITLE
Winning State when u end a song (NOT WINNING ICONS)

### ISSUE THREAD

**Issue by SAB236YT** [ShadowMario/FNF-PsychEngine#8559]
### What feature do you want to get added on the **base** engine?

When u end a song add a winning screen (Like FNF Modding + (optionable on the option menu on gameplay))

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Joalor64GH** [comment]
sounds interesting, tbh. maybe it could use the unused "WIN!" animation from the base game?

**Comment by SAB236YT** [comment]
> sounds interesting, tbh. maybe it could use the unused "WIN!" animation from the base game?

u damn. u thinked the same as me. do you think it at the end of the song? like https://www.youtube.com/watch?v=Fc_yCzKX294&ab_channel=Foxy_Jr

**Comment by Joalor64GH** [comment]
> > sounds interesting, tbh. maybe it could use the unused "WIN!" animation from the base game?
> 
> u damn. u thinked the same as me. do you think it at the end of the song?

something like that ye

**Comment by PrismLight** [comment]
> > > sounds interesting, tbh. maybe it could use the unused "WIN!" animation from the base game?
> > 
> > 
> > u damn. u thinked the same as me. do you think it at the end of the song?
> 
> something like that ye

Maybe the end of the week. It would be pretty annoying to see that screen during every song in a week. Unless it's freeplay.

**Comment by ImaginationSuperHero528** [comment]
So basically the end screen that happens at the end of the song... so ok I understand!

**Comment by tylerandari12** [comment]
This may be already possible...
Requires thorough knowledge in Lua tho...

**Comment by SAB236YT** [comment]
pls shadow add this

**Comment by SAB236YT** [comment]
#8562 can somone see this as i can make a video of how it looks like?

**Comment by PrismLight** [comment]
> This may be already possible... Requires thorough knowledge in Lua tho...

Who said we needed LincLUA?

**Comment by ImaginationSuperHero528** [comment]
Just make a Lua one.
