### ISSUE TITLE
Help ._.

### ISSUE THREAD

**Issue by SAB236YT** [ShadowMario/FNF-PsychEngine#8562]
### Describe your problem here.

source/PlayState.hx:3239: characters 46-58 : Module WinningState does not define type WinningState
source/PlayState.hx:3239: characters 46-58 : ... For function argument 'target'
source/PlayState.hx:3305: characters 45-57 : Module WinningState does not define type WinningState
source/PlayState.hx:3305: characters 45-57 : ... For function argument 'target'

pls help

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

options state and client prefs for a winning state option

**Comment by PrismLight** [comment]
We don't even know what the winning state option is.
