### ISSUE TITLE
 (unknown) : type not found : open.utils.internal.extraparamsmacro, what to do with this?

### ISSUE THREAD

**Issue by bekon4567** [ShadowMario/FNF-PsychEngine#8564]
### Describe your problem here.

what to do if it comes out

  (unknown) : type not found : open.utils.internal.extraparamsmacro
in "command line"

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Why did you open a duplicate of your own post
