### ISSUE TITLE
How do i use character indices

### ISSUE THREAD

**Issue by Plotsh** [ShadowMario/FNF-PsychEngine#8565]
### Describe your problem here.

Just need to know how to use the character indices on the char editor

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
it tells the game which frames of the animation to play

**Comment by tylerandari12** [comment]
If your animation was called "shoot" with 10 frames then playing the shoot animation will go through all 10 frames of shoot.
If you set the indices to "1, 5, 10" then it would only play frames 1, 5, and 10.

**Comment by Plotsh** [comment]
> If your animation was called "shoot" with 10 frames then playing the shoot animation will go through all 10 frames of shoot. If you set the indices to "1, 5, 10" then it would only play frames 1, 5, and 10.

thx
