### ISSUE TITLE
Animation Stopping?

### ISSUE THREAD

**Issue by glitchygmr** [ShadowMario/FNF-PsychEngine#8566]
### Describe your problem here.

I used characterPlayAnim to play an animation, but for some reason the animation only plays for like a single beat and then stops?
i havent had this problem before so I need to know whats happening.
code here:
`function onBeatHit()
	if curBeat == 504 then
		characterPlayAnim('dad', 'transform', false)
		playSound('bobSpooky', 1)
		makeGraphic('black', 2000, 2000, '000000')
		setObjectCamera('black', 'other')
		runTimer('scary', 1.7, 1)
		function onTimerCompleted(scary)
			addLuaSprite('black', true)
			cameraFade('other', '000000', 0.1, true)
		end
	end
end
`
everything else is working correctly, so I don't know why only the animation doesn't work.
please help! ^^

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing in the base game, just in mods folders

**Comment by frantastic24** [comment]
```lua
setProperty('dad.specialAnim', true)
```
or use triggerEvent
```lua
triggerEvent('Play Animation', 'transform', 'dad')
```

**Comment by tylerandari12** [comment]
in case you cant read his code

```

function onBeatHit() 
     if curBeat == 504 then 
          characterPlayAnim('dad', 'transform', false) 
          playSound('bobSpooky', 1) 
          makeGraphic('black', 2000, 2000, '000000') 
          setObjectCamera('black', 'other') 
          runTimer('scary', 1.7, 1) 
     end 
end 
function onTimerCompleted(scary) 
     addLuaSprite('black', true) 
     cameraFade('other', '000000', 0.1, true) 
end 

```

**Comment by glitchygmr** [comment]
> that's also not how you use onTimerCompleted, it works but will probably give you problems down the line
> 
> ```lua
> function onTimerCompleted(tag)
> 	if tag == 'scary' then
> 		--code
> 	end
> end
> ```

i did have timer completed separate, i just moved it to see if that was causing the issue (it wasnt so I left it)

> or use triggerEvent
> `triggerEvent('Play Animation', 'transform', 'dad')`
i tried that, same issue

>`setProperty('dad.specialAnim', true)`
was that in the wiki? i looked all over and havent seen that, ill try it now

**Comment by frantastic24** [comment]
> i tried that, same issue

you didn't explain what the exact issue was so i assumed the character was idling, if the issue is that the character sings then you can't fix that

**Comment by glitchygmr** [comment]
> > i tried that, same issue
> 
> you didn't explain what the exact issue was so i assumed the character was idling, if the issue is that the character sings then you can't fix that

my bad, yes the character is idling but the event didnt stop the idle (for some reason)

**Comment by glitchygmr** [comment]
> ```lua
> setProperty('dad.specialAnim', true)
> ```


it worked, thank you
