### ISSUE TITLE
Accessing new stage variables with Lua

### ISSUE THREAD

**Issue by YKoF-CALm** [ShadowMario/FNF-PsychEngine#8567]
### Describe your problem here.

Basically, I wish to know if you can access the new stage variables with Lua (hide_girlfriend, camera_boyfriend, camera_opponent, camera_girlfriend and camera_speed). If yes, how do I access them with Lua?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

**Comment by Lorekeeper49** [comment]
They are properties, you can use `setProperty` and `getProperty` to access them

**Comment by YKoF-CALm** [comment]
I tried setProperty('camera_boyfriend.x', -300), but it doesn't work.

**Comment by YKoF-CALm** [comment]
Bumping this issue because I still can't figure it out.

**Comment by frantastic24** [comment]
```lua
(getProperty('boyfriendCameraOffset')[1]) --x offset
(getProperty('boyfriendCameraOffset')[2]) --y offset
```
i don't think you can change them right now

**Comment by YKoF-CALm** [comment]
Alright, I'll try this out later, thanks.

**Comment by YKoF-CALm** [comment]
Tried this, sorry for the late reply. but it doesn't work.  Although, I used a slightly modified version of it, plus I was using setProperty. It just crashes the game if you run it.

**Comment by frantastic24** [comment]
I've already tested them myself so I can confirm they work, and I already said it may not be possible to change them

**Comment by YKoF-CALm** [comment]
Alright, I see. Whatever, I might just sub in with the Camera Move Pos event for now.
