### ISSUE TITLE
white game over bg?

### ISSUE THREAD

**Issue by glitchygmr** [ShadowMario/FNF-PsychEngine#8568]
### Describe your problem here.

I doubt this is possible, but could it be possible to make a white object in the game over scene as a bg?
i've got this much
```Lua
function onGameOverStart()
    makeGraphic('whit', 2000, 2000, 'FFFFFF')
    addLuaSprite('whit', false)
end
```
it doesnt work (obviously) but is there a way to make something like this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing in the base game, just in mods folders

**Comment by Mastercopper2346** [comment]
does it work?

**Comment by glitchygmr** [comment]
i already said it didnt in the og post

**Comment by NonCanonBF** [comment]
make the f's lowercase

**Comment by glitchygmr** [comment]
> make the f's lowercase

it still didnt do anything

**Comment by DoggoGamerYT** [comment]
try doing this
not sure if it works but here

function onGameOverStart()
    makeLuaSprite('whit', '', 0,0, 'FFFFFF') 
    makeGraphic('whit', 2000, 2000, 'FFFFFF')
    addLuaSprite('whit', false)
end

**Comment by glitchygmr** [comment]
> try doing this not sure if it works but here
> 
> function onGameOverStart() makeLuaSprite('whit', '', 'FFFFFF') makeGraphic('whit', 2000, 2000, 'FFFFFF') addLuaSprite('whit', false) end

It worked, thank you!!
![image](https://user-images.githubusercontent.com/92896412/169876392-c0014623-c861-40fd-9219-8c8e50f8e7e5.png)
