### ISSUE TITLE
the no source code achievement is not working

### ISSUE THREAD

**Issue by DJ-IS-THE-GOD** [ShadowMario/FNF-PsychEngine#8570]
### Describe your bug here.

when I write a script for the no source code achievement it didn't work and there's no menu for the no source code achievement

### Command Prompt/Terminal logs (if existing)

```bash
idk
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

FIX IT

**Comment by frantastic24** [comment]
Softcoded achievements aren't supported

**Comment by DJ-IS-THE-GOD** [comment]
wait what!?!?!?

**Comment by frantastic24** [comment]
Not supported
Close this

**Comment by SomeDudeMod** [comment]
is not supported kid. idiot close this shit.

**Comment by Mastercopper2346** [comment]
calm down he just didn't know

**Comment by jimmyjamescool** [comment]
> is not supported kid. idiot close this shit.

stop being toxic on this form. he didnt know.

**Comment by Wither362** [comment]
bb-panzu said that he will not add the custom achievements with the duplication bug, and bb-panzu isnt here anymore...
