### ISSUE TITLE
Why You deleted 0.5.2h (for Shadow Mario)

### ISSUE THREAD

**Issue by enderfunkin** [ShadowMario/FNF-PsychEngine#8574]
### What is your question?

Why You deleted 0.5.2h (for Shadow Mario)
Why You deleted 0.5.2h (for Shadow Mario)
Why You deleted 0.5.2h (for Shadow Mario)

**Comment by SpookyMan16** [comment]
> uhh.. what??
> 
> 0.5.2h isn't deleted

in releases it is

**Comment by CrusherMods** [comment]
either way cant you get it off gamebanana?????

**Comment by ActualMandM** [comment]
looks to just be hidden

https://github.com/ShadowMario/FNF-PsychEngine/releases/tag/0.5.2h

**Comment by Mastercopper2346** [comment]
hmm, why is that?

**Comment by frantastic24** [comment]
It's not removed or hidden

**Comment by endergames231** [comment]
I apologize to everyone that I wrote this
I just had that moment hidden away
Right now I'm showing up

**Comment by endergames231** [comment]
> kids istg ![image](https://user-images.githubusercontent.com/90648119/167656128-3d1414ba-0bb0-46b4-9662-8a9dda94473c.png)

Shut up you youngster
I had that moment hidden or there was a bug

**Comment by endergames231** [comment]
(FOR SHADOW MARIO)
I'm sorry that I wrote this
at that moment I had a bug or was it hidden
Right now everything is fine with us

**Comment by frantastic24** [comment]
Close this

**Comment by CrusherMods** [comment]
> > kids istg ![image](https://user-images.githubusercontent.com/90648119/167656128-3d1414ba-0bb0-46b4-9662-8a9dda94473c.png)
> 
> Shut up you youngster I had that moment hidden or there was a bug

gamebanana still exists you could've downloaded psych from there
also close this since I see you found the build
