### ISSUE TITLE
Base game color healthbar

### ISSUE THREAD

**Issue by SpookyMan16** [ShadowMario/FNF-PsychEngine#8575]
### Describe your problem here.

How do I make a base game colored healthbar?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Mastercopper2346** [comment]
like source code?

**Comment by tylerandari12** [comment]
> like source code?

Read it thoroughly.

Also you'd need new character .jsons with red and green healthbars.

**Comment by Mastercopper2346** [comment]
oh that? look in the older versions of psych engine or kade engine.

**Comment by ShadowMario** [comment]
You can't change health bar colors in lua
