### ISSUE TITLE
If Difficulty Then Code

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#8576]
### Describe your problem here.

So, I'm coding custom Difficulties, and I need some code for the difficulty. For Example:

`function onCreatePost()`
`	if (replace this with code that detects the Difficulty Text) == "Tough" then`
`		addLuaScript('customScripts/myscript')`
`	end`
`end`

Is there a line of code to get the Text format of a custom Difficulty?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, External Mod Folder.

**Comment by Mastercopper2346** [comment]
```
function onCreatePost()
      if difficulty == 2 then
            addLuaScript('scripts/myscript')
      end
end
```

**Comment by Mastercopper2346** [comment]
boy, difficulties have a number. 0 = easy, 1 = normal and 2 = hard.
Also give me the difficulty order.

**Comment by fnfdemonboi314159** [comment]
what? all I need is a way to know if the difficulty is the Tough Difficulty. That's all I'm asking.

**Comment by Mastercopper2346** [comment]
you need a number

**Comment by Mastercopper2346** [comment]
>Also give me the difficulty order.

Thats why i SAID that.

**Comment by Lorekeeper49** [comment]
```lua
function onCreatePost()
      if difficulty == 3 then
            --code
      end
end
```

**Comment by fnfdemonboi314159** [comment]
You know what, Nevermind.
