### ISSUE TITLE
The character move when must hit section

### ISSUE THREAD

**Issue by Killloo** [ShadowMario/FNF-PsychEngine#8578]
### What is your question?

The character move when the camera follow the character in must hit section, how to fix?

**Comment by frantastic24** [comment]
Probably an issue with your .XML

**Comment by EgguMan** [comment]
I am having the same issue. The XML is directly from adobe, so that cannot be the case.

**Comment by Mastercopper2346** [comment]
>The character move when the camera follow the character in must hit section, how to fix?

Rephase that, i dont get it

**Comment by EgguMan** [comment]
> > The character move when the camera follow the character in must hit section, how to fix?
> 
> Rephase that, i dont get it

basically, when a must hit section changes, a character moves with the screen. like an object set to the hud or other.

**Comment by ShadowMario** [comment]
The problem is in your XML file.
