### ISSUE TITLE
Why wont this code work?

### ISSUE THREAD

**Issue by EgguMan** [ShadowMario/FNF-PsychEngine#8579]
### Describe your problem here.

the following code will not work

function goodNoteHit(id, noteData, noteType, isSustainNote)
    if noteType == 'Metal Virus' then
		health=health - 1
		characterPlayAnim('boyfriend', 'hurt', true);
    end
end

function onTimerCompleted(tag)
    if tag=="HT" then
        health=health - noteTime
        noteTime=noteTime+0.25
    end
end
  

function onGameOver()
    playSound('ex_death', 0.8);
end

function onCreate()
	noteTime = -0.5
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Metal Virus' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'Metal virus'); --Change texture
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashDisabled', true);
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') == true then --Lets Opponent's instakill notes get ignored
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true); --Miss has no penalties
			end
		end
	end
end

the not texture and everything works, so I have no clue why the note is not playing the animation or anything upon being hit. it heals you too! 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Mastercopper2346** [comment]
use `(setProperty('health'), getProperty('health') -1)`

**Comment by Lorekeeper49** [comment]
change the string `'boyfriend'` to `'bf'`
