### ISSUE TITLE
Game occasionally crashes when I try to do anything (Downloaded build)

### ISSUE THREAD

**Issue by ColdlordXRepositories** [ShadowMario/FNF-PsychEngine#8581]
### Describe your bug here.

Before this happens, there is always a missing texture that appears (gf turning into a black square as an example)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added a PNG and XML to mods/images/characters and a PNG to mods/images/icons

**Comment by frantastic24** [comment]
Your PC has low memory

**Comment by Theoyeah** [comment]
Try to check if your machine is x36 or x64. And check your game if it is the correct
