### ISSUE TITLE
Im trying to run a script, but then it says error when there is no error

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8582]
### Describe your problem here.

It says this:
![error](https://user-images.githubusercontent.com/101440491/167742371-0d149dda-8f4d-43c2-a4be-efd793fdf763.png)

But this is the script:
![script](https://user-images.githubusercontent.com/101440491/167742422-c0b311ad-82f4-4843-95a6-a797e696ada6.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, not really

**Comment by tylerandari12** [comment]
You need to put the 2 in a string.
All events are read as strings so when it receives a number it gets confused.

**Comment by tylerandari12** [comment]
Also put the code under onCreatePost() as events dont exist until everything is loaded.

**Comment by NonCanonBF** [comment]
@tylerandari12 what about the two, the two has no comma, right, or does it not matter

**Comment by tylerandari12** [comment]
> @tylerandari12 what about the two, the two has no comma, right, or does it not matter
> 
> 

I actually didn't notice that.

There does need to be a comma tho

**Comment by NonCanonBF** [comment]
yeah, i was kinda confused and then i noticed it

**Comment by Mastercopper2346** [comment]
(aslo i zoomed in everything NOT to leak the mod

**Comment by tylerandari12** [comment]
> ill leave it open so when im done, ill give the link.

"ShadowMario has closed this issue."
