### ISSUE TITLE
D&B RGB Scroll Event

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#8587]
### Describe your problem here.

I'm trying to replicate the Dave and Bambi RGB Scroll Event (used in Polygonized, Furiosity, Glitch, etc.) as a lua Event. is it even possible to replicate the D&B RGB Scroll Effect with lua?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, External Mod Folder.

**Comment by Fronekowy** [comment]
What do you mean?

**Comment by fnfdemonboi314159** [comment]
oof. alright.
