### ISSUE TITLE
How to setcameratarget between two curbeats (Lua!)

### ISSUE THREAD

**Issue by Troystar23** [ShadowMario/FNF-PsychEngine#8592]
### What is your question?

As in the title I am using Lua and I am trying to set the camera target to dad at curbeat 192 to 224. and I know in source code it looks something like if curBeat > 192 && curBeat < 224 {. But in Lua '&' isnt accepted or used so im not sure how I would do this, so if anyone could give me a hand on how I could do this that would be great :) (the main reason I want to set the camera between these two curbeats is that after setting it to dad and 192 it immediately switches to boyfriend after :(....)
here is an image to look at what I had originally 
![image](https://user-images.githubusercontent.com/97416596/167888850-b7a03c8f-9423-411e-a2bc-0b5a6a7539ec.png)

**Comment by frantastic24** [comment]
`if curBeat > 192 and curBeat < 224 then`
