### ISSUE TITLE
How do I add multikey into the Psych Engine Source?

### ISSUE THREAD

**Issue by TheWorksOfBH** [ShadowMario/FNF-PsychEngine#8593]
### Describe your problem here.

**NOTE TO SHADOWMARIO: THIS IS NOT A RECOMMENDATION. I JUST NEED SOME HELP WITH MY OWN BUILD.**

I wanted to make my own Psych Engine build so then I could make charted covers of Thunderstorm from VS Shaggy and Absurde from Funkin' Physics.

Yes. I know. There is Psych Engine multikey. But I want to make my own build with not just multikey features, but some other things not in the OG engine (EG Winning icons, Ripple BGs etc.), and the Psych Engine multikey source code is gone.

So, does anyone know how to add multikeys in the source?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, not yet.

**Comment by tylerandari12** [comment]
No clue how to do it with source but I know how with Lua.

https://gamebanana.com/mods/352021

**Comment by FanKid** [comment]
just download this and copy some code from it. note: this is made chebtheidk. since tposejank deleted or private his source, this is the only source left for ek in 5.2h i can find.
