### ISSUE TITLE
How to stop a health drain at a specific time.

### ISSUE THREAD

**Issue by xXReb3caaXx** [ShadowMario/FNF-PsychEngine#8595]
### Describe your problem here.

So how do you stop a health drain in a specific time? Ex: at 0:52 the health drain should stop. (LUA)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by xChillax** [comment]
Depends on how you coded it. but it is overall done in the same way.
Show your script, as there are many ways to do it.

For example, if you are doing it on a timer, just stop the timer. If it's a constant health reduction, then just make it so it checks whenever your health is below a certain number and make it stop the drain health function.

**Comment by tylerandari12** [comment]
Send me your script and I'll make you a new one.

**Comment by Lorekeeper49** [comment]
You can actually do this
```lua
local noteHealthDrain = 0;
local conHealthDrain = 0;
function onEvent(n, v1, v2)
    if n == 'Health Drain' then
        if v2 == 'con'
            noteHealthDrain = 0;
            conHealthDrain = v1;
        else
            conHealthDrain = 0;
            noteHealthDrain = v1;
        end
    end
end
function opponentNoteHit()
    if not getProperty('health') == noteHealthDrain then
        setProperty('health', getProperty('health')-noteHealthDrain);
    end
end
function onUpdate(e)
    if not getProperty('health') == conHealthDrain then
        setProperty('health', getProperty('health')-conHealthDrain * e);
    end
end

**Comment by tylerandari12** [comment]
> Ex: at 0:52 the health drain should stop. (LUA)

Lua not LUA

**Comment by tylerandari12** [comment]
> > > Ex: at 0:52 the health drain should stop. (LUA)
> > 
> > 
> > Lua not LUA
> 
> It honestly DOES NOT MATTER!

Yes it does.

The creators of Lua were very insistent on people spelling it Lua and not LUA.
Look it up...

**Comment by xChillax** [comment]
If you wanna know the proper etymology behind it (and probably why they are upset about it):
* LUA (in all caps) is used when talking about a file extension. - "Grab all the LUA files and drop them in a new folder"
* Lua is the language itself. - "It's coded in Lua."


Either way, good to know this issue was solved.
