### ISSUE TITLE
How do I add a custom setting to the settings menu in downloaded build

### ISSUE THREAD

**Issue by funtime-foxy1** [ShadowMario/FNF-PsychEngine#8597]
### Describe your problem here.

I want to add a setting to the settings menu for **_allowing dialogue even when not in story mode._** How can I do this? Thanks to **all** answers.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't edit any .hx files. Only created lua files in mods/data/song

**Comment by frantastic24** [comment]
You need source

**Comment by funtime-foxy1** [comment]
> You need source

oh ok thanks for helping!
