### ISSUE TITLE
How to add custom setting on source

### ISSUE THREAD

**Issue by funtime-foxy1** [ShadowMario/FNF-PsychEngine#8598]
### Describe your problem here.

I want to make a toggle for **_allowing dialoge when not in story mode._** _Any_ help please? Thanks!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by SAB236YT** [comment]
eh is easy just go to the setting menu u wanna go. then copy one of the option and customize the names, then lez take an example like `downScroll` this is the name of the option in the coding. STEP 2 go to ClientPrefs.hx and do things like this (ME LAZY EXPLAIN STEP 2)

`public static var optionname:Bool = (set true or false);`

`FlxG.save.data.optionname = optionname;`

`if(FlxG.save.data.optionname != null) {
	  flashing = FlxG.save.data.optionname;
}`

for the third step idk source dialouge but in lua just set 

`if optionname then` then the dialouge lua code 

hope this helps ya

**Comment by funtime-foxy1** [comment]
> eh is easy just go to the setting menu u wanna go. then copy one of the option and customize the names, then lez take an example like `downScroll` this is the name of the option in the coding. STEP 2 go to ClientPrefs.hx and do things like this (ME LAZY EXPLAIN STEP 2)
> 
> `public static var optionname:Bool = (set true or false);` around the first lines
> 
> `FlxG.save.data.optionname = optionname;` starting off at line 94
> 
> `if(FlxG.save.data.optionname != null) {` `optionname = FlxG.save.data.optionname;` `}`
> 
> start at line 139. for the third step idk source dialouge but in lua just set
> 
> `if optionname then` then the dialouge lua code
> 
> hope this helps ya

Where are the setting menu scripts? or editor

**Comment by funtime-foxy1** [comment]
> > eh is easy just go to the setting menu u wanna go. then copy one of the option and customize the names, then lez take an example like `downScroll` this is the name of the option in the coding. STEP 2 go to ClientPrefs.hx and do things like this (ME LAZY EXPLAIN STEP 2)
> > `public static var optionname:Bool = (set true or false);` around the first lines
> > `FlxG.save.data.optionname = optionname;` starting off at line 94
> > `if(FlxG.save.data.optionname != null) {` `optionname = FlxG.save.data.optionname;` `}`
> > start at line 139. for the third step idk source dialouge but in lua just set
> > `if optionname then` then the dialouge lua code
> > hope this helps ya
> 
> Where are the setting menu scripts? or editor

Never Mind, Thanks!
