### ISSUE TITLE
Someone fix this pls

### ISSUE THREAD

**Issue by Plotsh** [ShadowMario/FNF-PsychEngine#8599]
### Describe your problem here.

Can someone pls fix this lol

```
jumping = false
function onUpdatePost(elapsed)
	 keyJustPressed('up') and not jumping then
		doTweenY('boyfriendJumpY', 'boyfriend', defaultBoyfriendY + 200, 0.3, 'cubeOut')
		setProperty('boyfriend.stunned', true)
		characterPlayAnim('boyfriend', 'hey', true)
		jumping = true
	end
end

function onTweenCompleted(tag)
	if tag == 'boyfriendJumpY' then
		doTweenY('boyfriendJumpBackY', 'boyfriend', defaultBoyfriendY + 350, 0.2, 'cubeIn')
		runTimer('delay', 0.2, 1)
	end
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'delay' then
		setProperty('boyfriend.stunned', false) --lmao
		jumping = false
	end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by tylerandari12** [comment]
Why are you using the up keybind tho?
Some people play with the arrows lol.
(I'll test the script by the way.)

**Comment by tylerandari12** [comment]
![Stoopid](https://user-images.githubusercontent.com/97060639/167957870-df0662f8-7455-4e0a-9889-eaadccb73f50.png)

if?

**Comment by Plotsh** [comment]
> ![Stoopid](https://user-images.githubusercontent.com/97060639/167957870-df0662f8-7455-4e0a-9889-eaadccb73f50.png)
> 
> if?

Holy shit i didnt saw that sorry lmao

**Comment by tylerandari12** [comment]
Fastest issue ever.

**Comment by Plotsh** [comment]
> Why are you using the up keybing tho?

i was on mobile

**Comment by tylerandari12** [comment]
> > Why are you using the up keybing tho?
> 
> i was on mobile

Makes sense.

**Comment by fnfdemonboi314159** [comment]
> Fastest issue ever.

hold my mod.
