### ISSUE TITLE
I can't change the camera zoom on one specific song

### ISSUE THREAD

**Issue by dombomb64** [ShadowMario/FNF-PsychEngine#8600]
### Describe your problem here.

On my cover of a song and only that cover, I can't change the camera zoom. It does change the variable, but nothing happens. I tried commenting out the song's whole script and also setting the variable in said script instead of my custom event script. Can anybody help?

https://user-images.githubusercontent.com/49823019/167969853-426d9c24-7b40-4705-acaf-dfbe89b83e98.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by CrusherMods** [comment]
Im pretty sure as soon as a note gets hit it will start to work

**Comment by dombomb64** [comment]
Thank you! That was it!
