### ISSUE TITLE
Stages crash game

### ISSUE THREAD

**Issue by DevAntiSocial** [ShadowMario/FNF-PsychEngine#8603]
### Describe your bug here.

Loading a custom stage = no game

help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
That means your script has something wrong

**Comment by FlintIshe** [comment]
Show us the script instead of just being slience

**Comment by DevAntiSocial** [comment]
> Show us the script instead of just being slience

Oop sorry i haven't been on GitHub all day 😅

**Comment by FlintIshe** [comment]
The Lua File of the stage or something

**Comment by tylerandari12** [comment]
Remove the `close()` line and see if that does anything.

**Comment by DevAntiSocial** [comment]
> Remove the `close()` line and see if that does anything.

THANKS YOU SO MUCH

**Comment by tylerandari12** [comment]
> > Remove the `close()` line and see if that does anything.
> 
> THANKS YOU SO MUCH

Im gonna make a bug report on this because thats not supposed to happen.
