### ISSUE TITLE
Psych Engine Freeplay Sections

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#8608]
### Describe your problem here.

You know the Dave and Bambi mod, or the VS Ron: The Resurrection 2.5 mod, right? Well, in both mods, freeplay is divided into sections. and I wanted to use Sections to divide freeplay into different sections.

For these examples, I will use VS Dave and Bambi.

Example 1: Story Songs
House, Insanity, Polygonized, Furiosity, Blocked, Corn Theft, Maze, Splitathon

Example 2: Bonus Songs
Mealie, Bonus Song, Shredder, Splitathon 2, etc.

Example 3: Joke Songs
Supernovae, Glitch, VS Dave Thanksgiving

Example 4: ???

Cheating, Unfairness

Example 5: Old Songs

Old House, Old Insanity, Old Furiosity, Old Blocked, Old Corn Theft, Old Maze, Old Splitathon

You get the idea, here's what I think could work out:
The Sections are different songs that will link to different songs with a menu.
Are there any lua scripts for menus like this? Cause I do NOT want to use the source code.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment]
Lua scripts don't run in menus

**Comment by fnfdemonboi314159** [comment]
> Lua scripts don't run in menus

Ik, I'm talking about Section 1 being a song, but it redirects you to a menu similar to settings with lua.

**Comment by tylerandari12** [comment]
> > Lua scripts don't run in menus
> 
> 
> 
> Ik, I'm talking about Section 1 being a song, but it redirects you to a menu similar to settings with lua.

So a pre game menu.

**Comment by fnfdemonboi314159** [comment]
> > > Lua scripts don't run in menus
> > 
> > 
> > Ik, I'm talking about Section 1 being a song, but it redirects you to a menu similar to settings with lua.
> 
> So a pre game menu.

mhm.
