### ISSUE TITLE
I need help like tons of it

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [ShadowMario/FNF-PsychEngine#8609]
### Describe your problem here.

Everytime we try to port for my engine ( FunkedEngine )
heres the errors
source/editors/WeekEditorState.hx:583: characters 15-23 : Type not found : WeekFile
source/editors/MasterEditorMenu.hx:21: lines 21-188 : Defined in this class
source/editors/WeekEditorState.hx:48: characters 15-23 : Type not found : WeekFile
source/editors/MasterEditorMenu.hx:21: lines 21-188 : Defined in this class
source/MainMenuState.hx:52: characters 3-11 : Module WeekData does not define type WeekData
source/StoryMenuState.hx:50: characters 24-32 : Module WeekData does not define type WeekData
source/StoryMenuState.hx:50: characters 24-32 : For function argument 'nextState'
source/MainMenuState.hx:26: lines 26-297 : Defined in this class
source/FreeplayState.hx:60: characters 3-11 : Module WeekData does not define type WeekData
source/FreeplayState.hx:67: characters 17-25 : Module WeekData does not define type WeekData
source/FreeplayState.hx:91: characters 3-11 : Module WeekData does not define type WeekData
source/FreeplayState.hx:144: characters 3-11 : Module WeekData does not define type WeekData
source/FreeplayState.hx:486: characters 24-32 : Module WeekData does not define type WeekData
source/FreeplayState.hx:221: characters 14-22 : Module WeekData does not define type WeekData
source/FreeplayState.hx:374: characters 29-37 : Module WeekData does not define type WeekData
source/ResetScoreSubState.hx:32: characters 11-19 : Module WeekData does not define type WeekData
source/ResetScoreSubState.hx:97: characters 26-34 : Module WeekData does not define type WeekData
source/ResetScoreSubState.hx:97: characters 26-34 : For function argument 'week'
source/PlayState.hx:4448: characters 30-38 : Module WeekData does not define type WeekData
source/PlayState.hx:3229: characters 40-48 : Module WeekData does not define type WeekData
source/PlayState.hx:3229: characters 40-48 : For function argument 'key'
source/PlayState.hx:3233: characters 32-40 : Module WeekData does not define type WeekData
source/PlayState.hx:3233: characters 32-40 : For function argument 'week'
source/TitleState.hx:90: characters 3-11 : Module WeekData does not define type WeekData 
or this one
source/editors/MasterEditorMenu.hx:177: characters 3-11 : Module WeekData does not define type WeekData
source/PlayState.hx:9: characters 8-20 : Type name WiggleEffectType is redefined from module WeekData
source/PlayState.hx:219: characters 17-29 : Module WiggleEffect does not define type WiggleEffect
source/CoolUtil.hx:17: lines 17-138 : ... Defined in this class
source/PlayState.hx:107: characters 2-47 : Method set_songSpeed required by property songSpeed is missing
source/animateatlas/AtlasFrameMaker.hx:49: characters 14-22 : Class has no field instance
source/FunkinLua.hx:110: characters 15-23 : Module WeekData does not define type WeekData
source/FunkinLua.hx:110: characters 15-23 : ... For function argument 'data'
source/FunkinLua.hx:111: characters 33-45 : Class has no field seenCutscene
source/FunkinLua.hx:143: characters 35-43 : Class has no field instance
source/FunkinLua.hx:144: characters 35-43 : Class has no field instance
source/FunkinLua.hx:145: characters 36-44 : Class has no field instance
source/FunkinLua.hx:146: characters 28-36 : Class has no field instance
source/FunkinLua.hx:147: characters 29-37 : Class has no field instance
source/FunkinLua.hx:157: characters 38-46 : Class has no field instance
source/FunkinLua.hx:158: characters 38-46 : Class has no field instance
source/FunkinLua.hx:159: characters 37-45 : Class has no field instance
source/FunkinLua.hx:160: characters 37-45 : Class has no field instance
source/FunkinLua.hx:161: characters 39-47 : Class has no field instance
source/FunkinLua.hx:162: characters 39-47 : Class has no field instance
source/FunkinLua.hx:215: characters 36-44 : Class has no field instance
source/FunkinLua.hx:215: characters 26-53 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/FunkinLua.hx:1921: characters 14-22 : Class has no field instance
source/FunkinLua.hx:224: characters 15-23 : Class has no field instance
source/FunkinLua.hx:246: characters 36-44 : Class has no field instance
source/FunkinLua.hx:246: characters 26-53 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
source/FunkinLua.hx:252: characters 19-27 : Class has no field instance
source/FunkinLua.hx:271: characters 14-22 : Class has no field instance
source/FunkinLua.hx:276: characters 17-25 : Class has no field instance
source/FunkinLua.hx:278: characters 15-23 : Class has no field instance
source/FunkinLua.hx:279: characters 15-23 : Class has no field instance
source/FunkinLua.hx:1972: characters 16-24 : Class has no field instance
source/FunkinLua.hx:1973: characters 30-38 : Class has no field instance
source/FunkinLua.hx:1974: characters 43-51 : Class has no field instance
source/FunkinLua.hx:1975: characters 30-38 : Class has no field instance
source/FunkinLua.hx:2037: characters 20-28 : Class has no field instance
source/FunkinLua.hx:2037: characters 76-84 : Class has no field instance
source/FunkinLua.hx:385: characters 17-25 : Class has no field instance
source/FunkinLua.hx:387: characters 52-60 : Class has no field instance
source/FunkinLua.hx:389: characters 22-30 : Class has no field instance
source/FunkinLua.hx:391: characters 52-60 : Class has no field instance
source/FunkinLua.hx:403: characters 17-25 : Class has no field instance
source/FunkinLua.hx:404: characters 40-48 : Class has no field instance
source/FunkinLua.hx:411: characters 17-25 : Class has no field instance
source/FunkinLua.hx:412: characters 38-46 : Class has no field instance
source/FunkinLua.hx:1811: characters 16-24 : Class has no field instance
source/FunkinLua.hx:1812: characters 14-22 : Class has no field instance
source/FunkinLua.hx:1813: characters 14-22 : Class has no field instance
source/FunkinLua.hx:1814: characters 14-22 : Class has no field instance
source/FunkinLua.hx:1822: characters 16-24 : Class has no field instance
source/FunkinLua.hx:1823: characters 25-33 : Class has no field instance
source/FunkinLua.hx:1825: characters 16-24 : Class has no field instance
source/FunkinLua.hx:1826: characters 25-33 : Class has no field instance
source/FunkinLua.hx:433: characters 15-23 : Class has no field instance
source/FunkinLua.hx:435: characters 17-25 : Class has no field instance
source/FunkinLua.hx:436: characters 17-25 : Class has no field instance
source/FunkinLua.hx:446: characters 15-23 : Class has no field instance
source/FunkinLua.hx:448: characters 17-25 : Class has no field instance
source/FunkinLua.hx:449: characters 17-25 : Class has no field instance
source/FunkinLua.hx:459: characters 15-23 : Class has no field instance
source/FunkinLua.hx:461: characters 17-25 : Class has no field instance
source/FunkinLua.hx:462: characters 17-25 : Class has no field instance
source/FunkinLua.hx:472: characters 15-23 : Class has no field instance
source/FunkinLua.hx:474: characters 17-25 : Class has no field instance
source/FunkinLua.hx:475: characters 17-25 : Class has no field instance
source/FunkinLua.hx:485: characters 15-23 : Class has no field instance
source/FunkinLua.hx:487: characters 17-25 : Class has no field instance
source/FunkinLua.hx:488: characters 17-25 : Class has no field instance
source/FunkinLua.hx:503: characters 15-23 : Class has no field instance
source/FunkinLua.hx:505: characters 17-25 : Class has no field instance
source/FunkinLua.hx:506: characters 17-25 : Class has no field instance
source/FunkinLua.hx:518: characters 39-47 : Class has no field instance
source/FunkinLua.hx:518: characters 88-96 : Class has no field instance
source/FunkinLua.hx:521: characters 15-23 : Class has no field instance
source/FunkinLua.hx:523: characters 17-25 : Class has no field instance
source/FunkinLua.hx:524: characters 17-25 : Class has no field instance
source/FunkinLua.hx:532: characters 39-47 : Class has no field instance
source/FunkinLua.hx:532: characters 88-96 : Class has no field instance
source/FunkinLua.hx:535: characters 15-23 : Class has no field instance
source/FunkinLua.hx:537: characters 17-25 : Class has no field instance
source/FunkinLua.hx:538: characters 17-25 : Class has no field instance
source/FunkinLua.hx:546: characters 39-47 : Class has no field instance
source/FunkinLua.hx:546: characters 88-96 : Class has no field instance
source/FunkinLua.hx:549: characters 15-23 : Class has no field instance
source/FunkinLua.hx:551: characters 17-25 : Class has no field instance
source/FunkinLua.hx:552: characters 17-25 : Class has no field instance
source/FunkinLua.hx:560: characters 39-47 : Class has no field instance
source/FunkinLua.hx:560: characters 88-96 : Class has no field instance
source/FunkinLua.hx:563: characters 15-23 : Class has no field instance
source/FunkinLua.hx:565: characters 17-25 : Class has no field instance
source/FunkinLua.hx:566: characters 17-25 : Class has no field instance
source/FunkinLua.hx:606: characters 39-47 : Class has no field instance
source/FunkinLua.hx:606: characters 88-96 : Class has no field instance
source/FunkinLua.hx:609: characters 15-23 : Class has no field instance
source/FunkinLua.hx:611: characters 17-25 : Class has no field instance
source/FunkinLua.hx:612: characters 17-25 : Class has no field instance
source/FunkinLua.hx:620: characters 39-47 : Class has no field instance
source/FunkinLua.hx:620: characters 88-96 : Class has no field instance
source/FunkinLua.hx:623: characters 15-23 : Class has no field instance
source/FunkinLua.hx:625: characters 17-25 : Class has no field instance
source/FunkinLua.hx:626: characters 17-25 : Class has no field instance
source/FunkinLua.hx:1836: characters 16-24 : Class has no field instance
source/FunkinLua.hx:1837: characters 38-46 : Class has no field instance
source/FunkinLua.hx:1840: characters 14-22 : Class has no field instance
source/FunkinLua.hx:638: characters 14-22 : Class has no field instance
source/FunkinLua.hx:640: characters 16-24 : Class has no field instance
source/FunkinLua.hx:642: characters 15-23 : Class has no field instance
source/FunkinLua.hx:642: characters 61-70 : Arrays of mixed types are only allowed if the type is forced to Array
source/FunkinLua.hx:642: characters 61-70 : Int should be String
source/FunkinLua.hx:684: characters 14-22 : Class has no field instance
source/FunkinLua.hx:685: characters 14-22 : Class has no field instance
source/FunkinLua.hx:688: characters 14-22 : Class has no field instance
source/FunkinLua.hx:689: characters 14-22 : Class has no field instance
source/FunkinLua.hx:692: characters 14-22 : Class has no field instance
source/FunkinLua.hx:693: characters 14-22 : Class has no field instance
source/FunkinLua.hx:696: characters 14-22 : Class has no field instance
source/FunkinLua.hx:697: characters 14-22 : Class has no field instance
source/FunkinLua.hx:700: characters 14-22 : Class has no field instance
source/FunkinLua.hx:701: characters 14-22 : Class has no field instance
source/FunkinLua.hx:704: characters 14-22 : Class has no field instance
source/FunkinLua.hx:705: characters 14-22 : Class has no field instance
source/FunkinLua.hx:709: characters 14-22 : Class has no field instance
source/FunkinLua.hx:712: characters 14-22 : Class has no field instance
source/FunkinLua.hx:715: characters 21-29 : Class has no field instance
source/FunkinLua.hx:725: characters 34-42 : Class has no field instance
source/FunkinLua.hx:726: characters 34-42 : Class has no field instance
source/FunkinLua.hx:727: characters 32-40 : Class has no field instance
source/FunkinLua.hx:728: characters 35-43 : Class has no field instance
source/FunkinLua.hx:729: characters 36-44 : Class has no field instance
source/FunkinLua.hx:730: characters 34-42 : Class has no field instance
source/FunkinLua.hx:731: characters 35-43 : Class has no field instance
source/FunkinLua.hx:732: characters 35-43 : Class has no field instance
source/FunkinLua.hx:740: characters 34-42 : Class has no field instance
source/FunkinLua.hx:741: characters 34-42 : Class has no field instance
source/FunkinLua.hx:742: characters 32-40 : Class has no field instance
source/FunkinLua.hx:743: characters 35-43 : Class has no field instance
source/FunkinLua.hx:751: characters 34-42 : Class has no field instance
source/FunkinLua.hx:752: characters 34-42 : Class has no field instance
source/FunkinLua.hx:753: characters 32-40 : Class has no field instance
source/FunkinLua.hx:754: characters 35-43 : Class has no field instance
source/FunkinLua.hx:765: characters 14-22 : Class has no field instance
source/FunkinLua.hx:779: characters 14-22 : Class has no field instance
source/FunkinLua.hx:784: characters 14-22 : Class has no field instance
source/FunkinLua.hx:787: characters 14-22 : Class has no field instance
source/FunkinLua.hx:788: characters 14-22 : Class has no field instance
source/FunkinLua.hx:791: characters 14-22 : Class has no field instance
source/PauseSubState.hx:268: characters 13-21 : Class has no field instance
source/PauseSubState.hx:270: characters 13-21 : Class has no field instance
source/FunkinLua.hx:801: characters 14-34 : Class has no field cancelMusicFadeTween
source/FunkinLua.hx:802: characters 48-56 : Class has no field instance
source/StoryMenuState.hx:50: characters 24-32 : Module WeekData does not define type WeekData
source/StoryMenuState.hx:50: characters 24-32 : ... For function argument 'nextState'
source/FunkinLua.hx:46: lines 46-2048 : ... Defined in this class
source/FunkinLua.hx:814: characters 14-22 : Class has no field instance
source/FunkinLua.hx:823: characters 23-31 : Class has no field instance
source/FunkinLua.hx:825: characters 23-31 : Class has no field instance
source/FunkinLua.hx:827: characters 23-31 : Class has no field instance
source/FunkinLua.hx:833: characters 16-24 : Class has no field instance
source/FunkinLua.hx:835: characters 16-24 : Class has no field instance
source/FunkinLua.hx:837: characters 16-24 : Class has no field instance
source/FunkinLua.hx:843: characters 23-31 : Class has no field instance
source/FunkinLua.hx:845: characters 23-31 : Class has no field instance
source/FunkinLua.hx:847: characters 23-31 : Class has no field instance
source/FunkinLua.hx:853: characters 16-24 : Class has no field instance
source/FunkinLua.hx:855: characters 16-24 : Class has no field instance
source/FunkinLua.hx:857: characters 16-24 : Class has no field instance
source/FunkinLua.hx:865: characters 14-22 : Class has no field instance
source/FunkinLua.hx:1909: characters 44-52 : Class has no field instance
source/FunkinLua.hx:1910: characters 48-56 : Class has no field instance
source/FunkinLua.hx:1912: characters 20-28 : Class has no field instance
source/FunkinLua.hx:882: characters 14-22 : Class has no field instance
source/FunkinLua.hx:885: characters 14-22 : Class has no field instance
source/FunkinLua.hx:888: characters 14-22 : Class has no field instance
source/FunkinLua.hx:938: characters 19-27 : Class has no field instance
source/FunkinLua.hx:939: characters 17-25 : Class has no field instance
source/FunkinLua.hx:941: characters 19-27 : Class has no field instance
source/FunkinLua.hx:941: characters 52-60 : Class has no field instance
source/FunkinLua.hx:942: characters 17-25 : Class has no field instance
source/FunkinLua.hx:944: characters 19-27 : Class has no field instance
source/FunkinLua.hx:945: characters 17-25 : Class has no field instance
source/FunkinLua.hx:950: characters 27-35 : Class has no field instance
source/FunkinLua.hx:951: characters 44-52 : Class has no field instance
source/FunkinLua.hx:951: characters 75-83 : Class has no field instance
source/FunkinLua.hx:952: characters 24-32 : Class has no field instance
source/FunkinLua.hx:1797: characters 17-25 : Class has no field instance
source/FunkinLua.hx:1801: characters 38-46 : Class has no field instance
source/FunkinLua.hx:1804: characters 14-22 : Class has no field instance
source/FunkinLua.hx:1807: characters 13-21 : Class has no field instance
source/FunkinLua.hx:965: characters 14-22 : Class has no field instance
source/FunkinLua.hx:975: characters 14-22 : Class has no field instance
source/FunkinLua.hx:982: characters 17-25 : Class has no field instance
source/FunkinLua.hx:983: characters 15-23 : Class has no field instance
source/FunkinLua.hx:993: characters 17-25 : Class has no field instance
source/FunkinLua.hx:994: characters 41-49 : Class has no field instance
source/FunkinLua.hx:1017: characters 17-25 : Class has no field instance
source/FunkinLua.hx:1018: characters 42-50 : Class has no field instance
source/FunkinLua.hx:1035: characters 17-25 : Class has no field instance
source/FunkinLua.hx:1036: characters 15-23 : Class has no field instance
source/FunkinLua.hx:1047: characters 17-25 : Class has no field instance
source/FunkinLua.hx:1048: characters 15-23 : Class has no field instance
source/FunkinLua.hx:1058: characters 17-25 : Class has no field instance
source/FunkinLua.hx:1059: characters 41-49 : Class has no field instance
source/FunkinLua.hx:1067: characters 20-28 : Class has no field instance
source/FunkinLua.hx:1073: characters 37-45 : Class has no field instance
source/FunkinLua.hx:1073: characters 72-80 : Class has no field instance
source/FunkinLua.hx:1074: characters 21-29 : Class has no field instance
source/FunkinLua.hx:1074: characters 56-64 : Class has no field instance
source/FunkinLua.hx:1075: characters 30-38 : Class has no field instance
source/FunkinLua.hx:1075: characters 65-73 : Class has no field instance
source/FunkinLua.hx:1076: characters 28-36 : Class has no field instance
source/FunkinLua.hx:1076: characters 63-71 : Class has no field instance
source/FunkinLua.hx:1077: characters 30-38 : Class has no field instance
source/FunkinLua.hx:1077: characters 65-73 : Class has no field instance
source/FunkinLua.hx:1079: characters 18-26 : Class has no field instance
source/FunkinLua.hx:1088: characters 17-25 : Class has no field instance
source/FunkinLua.hx:1089: characters 41-49 : Class has no field instance
source/FunkinLua.hx:1104: characters 17-25 : Class has no field instance
source/FunkinLua.hx:1105: characters 41-49 : Class has no field instance
source/FunkinLua.hx:1120: characters 17-25 : Class has no field instance
source/FunkinLua.hx:1121: characters 41-49 : Class has no field instance
source/FunkinLua.hx:1141: characters 18-26 : Class has no field instance
source/FunkinLua.hx:1145: characters 39-47 : Class has no field instance
source/FunkinLua.hx:1157: characters 15-23 : Class has no field instance
source/FunkinLua.hx:1162: characters 17-25 : Class has no field instance
source/FunkinLua.hx:1163: characters 15-23 : Class has no field instance
source/FunkinLua.hx:1166: characters 22-30 : Class has no field instance
source/FunkinLua.hx:1167: characters 15-23 : Class has no field instance
source/FunkinLua.hx:1180: characters 17-25 : Class has no field instance
source/FunkinLua.hx:1181: characters 15-23 : Class has no field instance
source/FunkinLua.hx:1195: characters 17-25 : Class has no field instance
source/FunkinLua.hx:1196: characters 21-29 : Class has no field instance
source/FunkinLua.hx:1197: characters 24-32 : Class has no field instance
source/FunkinLua.hx:1198: characters 21-29 : Class has no field instance
source/FunkinLua.hx:1225: characters 18-26 : Class has no field instance
source/FunkinLua.hx:1226: characters 34-42 : Class has no field instance
source/FunkinLua.hx:1228: characters 23-31 : Class has no field instance
source/FunkinLua.hx:1229: characters 34-42 : Class has no field instance
source/FunkinLua.hx:1244: characters 17-25 : Class has no field instance
source/FunkinLua.hx:1245: characters 21-29 : Class has no field instance
source/FunkinLua.hx:1246: characters 24-32 : Class has no field instance
source/FunkinLua.hx:1247: characters 21-29 : Class has no field instance
source/FunkinLua.hx:1290: characters 16-24 : Class has no field instance
source/FunkinLua.hx:1297: characters 18-26 : Class has no field instance
source/FunkinLua.hx:1298: characters 16-24 : Class has no field instance
source/FunkinLua.hx:1300: characters 16-24 : Class has no field instance
source/FunkinLua.hx:1307: characters 15-23 : Class has no field instance
source/FunkinLua.hx:1326: characters 18-26 : Class has no field instance
source/FunkinLua.hx:1327: characters 16-24 : Class has no field instance
source/FunkinLua.hx:1329: characters 15-23 : Class has no field instance
source/FunkinLua.hx:1330: characters 16-24 : Class has no field instance
source/FunkinLua.hx:1331: characters 16-24 : Class has no field instance
source/FunkinLua.hx:1330: characters 16-24 : Class has no field instance
source/FunkinLua.hx:1331: characters 16-24 : Class has no field instance
source/FunkinLua.hx:1330: characters 16-24 : Class has no field instance
source/FunkinLua.hx:1331: characters 16-24 : Class has no field instance
source/FunkinLua.hx:1338: characters 50-58 : Class has no field instance
source/FunkinLua.hx:1339: characters 15-23 : Class has no field instance
source/FunkinLua.hx:1340: characters 15-23 : Class has no field instance
source/FunkinLua.hx:1344: characters 50-58 : Class has no field instance
source/FunkinLua.hx:1345: characters 15-23 : Class has no field instance
source/FunkinLua.hx:1349: characters 50-58 : Class has no field instance
source/FunkinLua.hx:1350: characters 15-23 : Class has no field instance
source/FunkinLua.hx:1356: characters 24-32 : Class has no field instance
source/FunkinLua.hx:1357: characters 15-23 : Class has no field instance
source/FunkinLua.hx:1364: characters 24-32 : Class has no field instance
source/FunkinLua.hx:1365: characters 15-23 : Class has no field instance
source/FunkinLua.hx:1373: characters 24-32 : Class has no field instance
source/FunkinLua.hx:1374: characters 39-47 : Class has no field instance 
I dont know what to do 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5/Browser

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, well not yet

**Comment by JackoCatacomb** [comment]
jeSUS CHRIST

try redoing all the haxelib stuff
