### ISSUE TITLE
how to add dialogue after video cutscene?

### ISSUE THREAD

**Issue by ethaxo99** [ShadowMario/FNF-PsychEngine#861]
### What is your question?

Both the video and dialogue .lua files have to be named "script", but they need to both be in the same folder. Is there a way to play dialogue after a video cutscene?

**Comment by PoleyMagik** [comment]
this should work i think
```
local allowCountdown = false
function onStartCountdown()
	-- Block the first countdown, play video and start a timer of 0.8 seconds to play the dialogue
	if not allowCountdown and isStoryMode and not seenCutscene then
		startVideo('testVideo');
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('dialogue', 'breakfast');
	end
end

-- Dialogue (When a dialogue is finished, it calls startCountdown again)
function onNextDialogue(count)
	-- triggered when the next dialogue line starts, 'line' starts with 1
end

function onSkipDialogue(count)
	-- triggered when you press Enter and skip a dialogue line that was still being typed, dialogue line starts with 1
end
```

**Comment by ShadowMario** [comment]
> this should work i think
> 
> ```
> local allowCountdown = false
> function onStartCountdown()
> 	-- Block the first countdown, play video and start a timer of 0.8 seconds to play the dialogue
> 	if not allowCountdown and isStoryMode and not seenCutscene then
> 		startVideo('testVideo');
> 		setProperty('inCutscene', true);
> 		runTimer('startDialogue', 0.8);
> 		allowCountdown = true;
> 		return Function_Stop;
> 	end
> 	return Function_Continue;
> end
> 
> function onTimerCompleted(tag, loops, loopsLeft)
> 	if tag == 'startDialogue' then -- Timer completed, play dialogue
> 		startDialogue('dialogue', 'breakfast');
> 	end
> end
> 
> -- Dialogue (When a dialogue is finished, it calls startCountdown again)
> function onNextDialogue(count)
> 	-- triggered when the next dialogue line starts, 'line' starts with 1
> end
> 
> function onSkipDialogue(count)
> 	-- triggered when you press Enter and skip a dialogue line that was still being typed, dialogue line starts with 1
> end
> ```

No it wouldn't, this would start the video and dialogue at the same time
https://github.com/ShadowMario/FNF-PsychEngine/issues/748
