### ISSUE TITLE
Week 7

### ISSUE THREAD

**Issue by UltimateGamer303** [ShadowMario/FNF-PsychEngine#8612]
### What is your question?

In the Achievements PNG File, it shows tankman. IDK if that is supposed to be there, like if Psych Engine is supposed to have week 7? If not, oh well. Just I would like to know.
![achievementgrid tank](https://user-images.githubusercontent.com/96801398/168158876-2119fb19-1371-4d28-8ccc-8a1646f37d66.png)

**Comment by tylerandari12** [comment]
They probably haven`t added it because week 7 is still newgrounds exclusive.

**Comment by CrusherMods** [comment]
> They probably haven`t added it because week 7 is still newgrounds exclusive.

no its not
your allowed to have week 7 in your mods now
![image](https://user-images.githubusercontent.com/90648119/168408195-dae80aab-2229-409c-b014-17bfe53cda13.png)

**Comment by UltimateGamer303** [comment]
@ShadowMario, sorry for pinging you or whatever. But do you have an Idea on when week 7 version will release for psych?
