### ISSUE TITLE
i have seen this asked 3 times + myself (reasking cuz no response besides a dude who needed it too)

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#8613]
### What is your question?

how would i add a bootup cutseen man

**Comment by Stilic** [comment]
close this and open a issue with help wanted instead of doing a question bruh

**Comment by NS-Unfair** [comment]
What do you mean by a "bootup" cutscene? Do you mean a cutscene that plays on song start?

**Comment by machonessiebaby** [comment]
> What do you mean by a "bootup" cutscene? Do you mean a cutscene that plays on song start?

when the game is executed in source
