### ISSUE TITLE
are you happy i deleted the ek git?

### ISSUE THREAD

**Issue by tposejank** [ShadowMario/FNF-PsychEngine#8614]
### What is your question?

i hope you are, i am, idgaf. i'm leaving this cringe, ass motherfucker community i am tired of being pushed back by all of you, enjoy  sadness, i dont have access to my gb anymore dont expect updates worse in gjolt.
![lol](https://yt3.ggpht.com/a/AGF-l7-IAZPtHVlC-zp8PI2ibmDGWkB3YVi-jyp1YA=s900-c-k-c0xffffffff-no-rj-mo)

idc if im banned, i can create alts, in any world i would every try doing so im not the right mind for that im not a crybaby. i'm not even gonna say why im just tired of having to work on this shit. like its so boring, i hear the word "keys" every day it has my mind like this.
![t1 a](https://i.ytimg.com/vi/xVVX6XUrWDk/maxresdefault.jpg)

goodbye :)

**Comment by PrismLight** [comment]
wtf is ur problem

**Comment by Keoiki** [comment]
go cry elsewhere

**Comment by cyn-8** [comment]
![20200612_014504.jpg](https://user-images.githubusercontent.com/58795684/168190031-d550ba99-0306-408a-87e5-ab8e9e479b28.jpg)

**Comment by TKTems** [comment]
"im not a crybaby" BRO YOU ARE WEEEPING YOU ARE ON THE FLOOR SOBBING NAWW NAWWWWW

**Comment by Steviegt6** [comment]
hi tposejank!!!

**Comment by ShadowMario** [comment]
malding hard

**Comment by tposejank** [comment]
> "im not a crybaby" BRO YOU ARE WEEEPING YOU ARE ON THE FLOOR SOBBING NAWW NAWWWWW

?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????

**Comment by FinderFromMac** [comment]
what's going on
