### ISSUE TITLE
Random Kill Note

### ISSUE THREAD

**Issue by Shelvsk** [ShadowMario/FNF-PsychEngine#8617]
### Describe your problem here.

I'm trying to create a system for a note that always when pressed can randomly kill or not, I've tried a math.random() but it wasn't very efficient, can anyone help me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ManMaster707** [comment]
use this
```lua
function goodNoteHit(id, direction, noteType, isSustainNote)
    if noteType == 'notenamehere' then
        random = getRandomInt(0, 1);-- makes what happens when you hit the note random
        if random == 1 then-- 0 = no instakill, 1 = instakill
            setProperty('health', -500)
```

**Comment by Shelvsk** [comment]
not worked, but thanks for try

**Comment by ManMaster707** [comment]
> not worked
did you change 'notenamehere' to your notetype's name? because if no, then the script won't work.

**Comment by Shelvsk** [comment]
Yes i changed, but the note is not killing

**Comment by tylerandari12** [comment]
> Yes i changed, but the note is not killing

You must be very lucky then.

**Comment by Shelvsk** [comment]
I don't think that this is the case ;-; but i will do some tests

**Comment by Shelvsk** [comment]
dudes `getRandomInt()` is not on the API, obviously it's not working

**Comment by frantastic24** [comment]
> dudes `getRandomInt()` is not on the API

![image](https://user-images.githubusercontent.com/95725102/168670969-31e58190-5a2a-4245-8040-eab53d0e6cbb.png)


this should work better anyway

```lua
    if noteType == 'name' then
	if getRandomBool(50) then
		setProperty('health', -1)
	end
    end
```

**Comment by Shelvsk** [comment]
thanks, this is really better it's working now
