### ISSUE TITLE
Game Over

### ISSUE THREAD

**Issue by FlintIshe** [ShadowMario/FNF-PsychEngine#8620]
### What is your question?

How can I play a Sound when the player is dead?

Addtional Question : 
Also how can I also play a sound when pressed the retry button

**Comment by xChillax** [comment]
It's pretty straightforward to do as you can simply intercept said functions triggering.

**Play a sound on player's death:**
```
function onGameOver()
    playSound('missnote1', 1.0)

    return Function_Continue;
end
```

**Play a sound when pressing retry:**
```
function onGameOverConfirm(retry)
    if retry then
        playSound('missnote1', 1.0)
    end
end
```

**Comment by FlintIshe** [comment]
Thanks! 

But is it possible to play a sound depending on how many times we get blueballed like : 

if blueBalled == 2 then
         playSound('mythorataaaaaaaa', 2)
end

**Comment by tylerandari12** [comment]
#8633
`getPropertyFromClass("PlayState", "deathCounter")`

**Comment by xChillax** [comment]
(oh thanks git notifications for only triggering now and thank you Tyler btw)

If you want to use it in a clean way you could do:
```
function onGameOverConfirm(retry)
    local deathCounter = getPropertyFromClass("PlayState", "deathCounter")

    if retry then
        if deathCounter == 1 then
            playSound("missnote1", 1.0)
        elseif deathCounter == 2 then
            playSound("missnote2", 1.0)
        else
            playSound("missnote3", 1.0)
        end
    end
end
```
