### ISSUE TITLE
About how to change the stage in the middle of the song

### ISSUE THREAD

**Issue by Guranlikesblue** [ShadowMario/FNF-PsychEngine#8623]
### Describe your problem here.

#3137
When I try to change the stage using Lua, which is mentioned in this article, the game crashes when changing the stage in the chart.
Probably I think my way is bad
I put that code in the song data file as script.lua
I'm new to programming and don't understand lua scripts very well
If you know something, I'm glad if you tell me

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes. Add character. Add stages and winning icons in PlayState.hx. Add Custom Note in Lua.

**Comment by obamacat9** [comment]
you cant bg are sprites so you have to change sprites so merge the two bgs your trying to use in the same script

**Comment by Guranlikesblue** [comment]
> you cant bg are sprites so you have to change sprites so merge the two bgs your trying to use in the same script

How do you do that?
I really don't know anything, so I want more explanation.
I'm sorry many times

**Comment by FlintIshe** [comment]
```
Example: makeLuaSprite('thing', 'thing', 0,0
                addLuaSprite('thing', false)             --your og bg sprite



         end



```
To change at midSong

```
function onStepHit()
         if curStep == yourcurStephere   --look in the chart editor  
               removeLuaSprite('thing') --remove the og sprite 
               makeLuaSprite('yourtag', 'imagefile', 0,0 )  --makes new stage/bg sprite
               setScrollFactor('yourtag', 0.9, 0.9)
               addLuaSprite('yourtag', false)

           
        end
end

      

```

**Comment by Guranlikesblue** [comment]
> ```
> Example: makeLuaSprite('thing', 'thing', 0,0
>                 addLuaSprite('thing', false)             --your og bg sprite
> 
> 
> 
>          end
> ```
> 
> To change at midSong
> 
> ```
> function onStepHit()
>          if curStep == yourcurStephere   --look in the chart editor  
>                removeLuaSprite('thing') --remove the og sprite 
>                makeLuaSprite('yourtag', 'imagefile', 0,0 )  --makes new stage/bg sprite
>                setScrollFactor('yourtag', 0.9, 0.9)
>                addLuaSprite('yourtag', false)
> 
>            
>         end
> end
> 
>       
> ```
> 
> it may be works

I got an error saying "'then' expected near 'remove LuaSprite'"
Where do you put "then"?
And at what event will it be called?
After all "Play Animation"?

**Comment by Guranlikesblue** [comment]
>And at what event will it be called? After all "Play Animation"?

I'm sorry, I was a little misunderstood, you can ignore the event

**Comment by FlintIshe** [comment]
can you send the picture about the error?

**Comment by frantastic24** [comment]
The if statement is missing `then`
I would also recommend making the sprites beforehand and not adding them when you need to switch stage, to prevent lag spikes

**Comment by Guranlikesblue** [comment]
> can you send the picture about the error?

This is a picture of the error
![1652691350990](https://user-images.githubusercontent.com/89185139/168556561-a7ecb5ca-bdcf-4185-b1c0-2c765c637857.jpg)
![1652691372149](https://user-images.githubusercontent.com/89185139/168556606-51776ba7-a166-474f-80ae-ef82a46fc4ce.jpg)

**Comment by Guranlikesblue** [comment]
`function onCreate()
	makeLuaSprite('spookyEvil', 'halloweenevil_bg_low', -200, -100);
	addLuaSprite('spookyEvil', false);
	scaleObject('spookyEvil', 1, 1);
	
function onStepHit()
	if curStep == 319 then
		setProperty('gf.visible', false);
		removeLuaSprite('spookyEvil');
		makeLuaSprite('spookyEvilfront', 'halloweenevil', -200, -100);
		setScrollFactor('spookyEvilfront', 1, 1);
		addLuaSprite('spookyEvilfront', false);
		scaleObject('spookyEvilfront', 1, 1);
	
	end
end`

I tried adding `then` after `if curStep == 319`, but I got another error!
Error is `Error on lua script! assets/data/devour/script3.lua:16: 'end' expected (to close 'function' at line 1) near '<eof>'`
What is `<eof>`!?
Is there anything else wrong with this error?

**Comment by frantastic24** [comment]
Didn't close onCreate

**Comment by Guranlikesblue** [comment]
function onCreate()
	makeLuaSprite('spookyEvil', 'halloweenevil_bg_low', -200, -100);
	addLuaSprite('spookyEvil', false);
	scaleObject('spookyEvil', 1, 1);
end

function onStepHit()
	if curStep == 319 then
		setProperty('gf.visible', false);
		removeLuaSprite('spookyEvil');
		makeLuaSprite('spookyEvilfront', 'halloweenevil', -200, -100);
		addLuaSprite('spookyEvilfront', false);
		scaleObject('spookyEvilfront', 1, 1);
	end
end

I closed `function onCreate` () and removed `setScrollFactor` and it was successful!
Thank you to those who answered!

**Comment by oisintheblue** [comment]
wtf is "yourtag" and "imagefile" which one is new bg
