### ISSUE TITLE
How to make a sprite fade in then fade out?

### ISSUE THREAD

**Issue by AntCrem** [ShadowMario/FNF-PsychEngine#8626]
### Describe your problem here.

I was wondering how I can make a sprite slowly fade inwards then outwards using lua

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nu

**Comment by Meme1079** [comment]
`doTweenAlpha('tag', 'obj', opacity, time, ease)`

Example:
`doTweenAlpha('funnyAlpha', 'funny, 0, 1, 'linear)`
