### ISSUE TITLE
So many bugs jeez did you even test v5.2h

### ISSUE THREAD

**Issue by ethanlolcat3** [ShadowMario/FNF-PsychEngine#8627]
### Describe your bug here.

Here are the most major ones:
-Sometimes trying to load a song (including loading it from the chart editor) will crash the game for no reason.
-Sometimes restarting a song will crash the game for no reason.
-Sometimes trying to exit a song will crash the game for no reason.
-Sometimes while in the chart editor, the game will crash for no reason.
(seriously wtf is causing the game to crash at seemingly random)
-For some reason changing the offset and then loading a song will crash the game. However it works after re-opening the game.
-In the character editor, sometimes a bug will happen that will make it impossible to type in text boxes as well as making the drop down menu's for the characters and the animation act weird.
-Sometimes after playing a song and then loading another song, GF will be non-existent, and proceed to be non-existent even after loading a different song (I've also observed that she will also absent from the adjust delay and combo menu thingy). This can also happen with BF, although it usually happens after GF has already been erased from this planet.

I seriously don't understand how any of this could even happen considering how small of an update v5.2h was.

Note: The only bug that has appeared in v5.2 is the character editor one. The rest are only in v5.2h.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, the source code has not been messed with in anyway.

**Comment by ethanlolcat3** [comment]
![image](https://user-images.githubusercontent.com/98861770/168339396-4c01563c-a5ff-4286-b93b-ab5d43ffac80.png)
i meant to put in not any lol

**Comment by ManMaster707** [comment]
personally, I think it's a pc issue, check if your windows is 32-bit or 64-bit

**Comment by ethanlolcat3** [comment]
> personally, I think it's a pc issue, check if your windows is 32-bit or 64-bit

My computer is 64 bit.

**Comment by tylerandari12** [comment]
Entering the change difficulty menu if all 3 difficulties aren`t in the data folder will also crash the game.

**Comment by ShadowMario** [comment]
Holy shit how much i fucking hate dave & bambi fans
