### ISSUE TITLE
how do i remove the color changing thingy on freeplay and options? and credits?

### ISSUE THREAD

**Issue by JacksRobotics** [ShadowMario/FNF-PsychEngine#8628]
### What is your question?

i want it to stay as menuBG. and not change its color.

**Comment by Mastercopper2346** [comment]
edit menuBGMagenta to be the same color.

**Comment by JacksRobotics** [comment]
> edit menuBGMagenta to be the same color.

i did. but psych engine uses code that in freeplay. when you urselected a song, it will change the back color. same goes with options. if you urselected graphics or other it changes

**Comment by MaybeMaru** [comment]
delete the tween color part in source

**Comment by JacksRobotics** [comment]
> delete the tween color part in source

thanks

**Comment by PrismLight** [comment]
> > delete the tween color part in source
> 
> Wait where is the tween thingy?

https://github.com/ShadowMario/FNF-PsychEngine/blob/b6c64fcf3039ddc2252ee9bb4c5adc67d26d4345/source/MainMenuState.hx#L94

**Comment by JacksRobotics** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/blob/b6c64fcf3039ddc2252ee9bb4c5adc67d26d4345/source/MainMenuState.hx#L94

i meant for freeplay. to make the background stop changing color and make it stay as menubg

**Comment by PrismLight** [comment]
> > https://github.com/ShadowMario/FNF-PsychEngine/blob/b6c64fcf3039ddc2252ee9bb4c5adc67d26d4345/source/MainMenuState.hx#L94
> 
> i meant for freeplay. to make the background stop changing color and make it stay as menubg

https://github.com/ShadowMario/FNF-PsychEngine/blob/b6c64fcf3039ddc2252ee9bb4c5adc67d26d4345/source/FreeplayState.hx#L444-L448

**Comment by JacksRobotics** [comment]
> > > https://github.com/ShadowMario/FNF-PsychEngine/blob/b6c64fcf3039ddc2252ee9bb4c5adc67d26d4345/source/MainMenuState.hx#L94
> > 
> > 
> > i meant for freeplay. to make the background stop changing color and make it stay as menubg
> 
> https://github.com/ShadowMario/FNF-PsychEngine/blob/b6c64fcf3039ddc2252ee9bb4c5adc67d26d4345/source/FreeplayState.hx#L444-L448

THANK YOU SO MUCH!!
