### ISSUE TITLE
How do I hide just the info/accuracy bar in LUA?

### ISSUE THREAD

**Issue by XperiorTR** [ShadowMario/FNF-PsychEngine#8629]
### Describe your problem here.

How do I hide just the info/accuracy bar in lua? (the thing with the ratings, accuracy, score and misses)
I dont want to hide anything else.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by AetherLynx** [comment]
`setProperty('scoreTxt.visible', false)`

**Comment by XperiorTR** [comment]
thanks it worked
