### ISSUE TITLE
I'm trying to run and writes this, what should I do?

### ISSUE THREAD

**Issue by Aloekunyep** [ShadowMario/FNF-PsychEngine#8630]
### Describe your problem here.

I'm trying to run and writes this, what should I do?

Error: Could not find haxelib "linc_luajit", does it need to be installed?

what should I do with it?

I've literally tried everything

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Mastercopper2346** [comment]
install `haxelib install linc_luajit`

**Comment by Stilic** [comment]
stop open issues like this and read the readme instead of asking

**Comment by Stilic** [comment]
now close this please

**Comment by Aloekunyep** [comment]
I've already tried haxelib install linc_luajit, it doesn't work for some reason

**Comment by Stilic** [comment]
> I've already tried haxelib install linc_luajit, it doesn't work for some reason

try reinstalling haxe

**Comment by Aloekunyep** [comment]
it didn't work

**Comment by Stilic** [comment]
> it didn't work

`haxelib git linc_luajit https://github.com/AndreiRudenko/linc_luajit`

**Comment by Aloekunyep** [comment]
it didn't work

>

**Comment by Stilic** [comment]
> it didn't work
> 
> >

what is the error?

**Comment by Aloekunyep** [comment]
in the same

Error: Could not find haxelib "linc_luajit", does it need to be installed?

**Comment by Stilic** [comment]
> in the same
> 
> Error: Could not find haxelib "linc_luajit", does it need to be installed?

why did you typed this time in cmd?

**Comment by Aloekunyep** [comment]
Lime test windows

If I understand you correctly

**Comment by Stilic** [comment]
> Lime test windows
> 
> If I understand you correctly

i mean, retry the command for install luajit shit and show the output.
