### ISSUE TITLE
Entering the change difficulty menu if all 3 difficulties aren`t in the data folder will crash the game.

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8632]
### Describe your bug here.

If the `easy`, `normal`, and `hard` difficulties dont all exist when you open the `change difficulty` menu on the pause screen, the game will crash.

Most annoying thing ever.

### Command Prompt/Terminal logs (if existing)

```bash
E
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing changed.

**Comment by obamacat9** [comment]
this only happens when it wants to it has happened to me

**Comment by tylerandari12** [comment]
Yus

**Comment by tylerandari12** [comment]
Made a new issue about this lol...

**Comment by tylerandari12** [comment]
It appears to be fixed now :D
