### ISSUE TITLE
getProperty("deaths")

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8633]
### What feature do you want to get added on the **base** engine?

Someone in #8620 said they would like a variable to tell how many times the player has died.
And I liked it.
So im making another issue. (Im on a roll **XD**)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ActualMandM** [comment]
```lua
getPropertyFromClass("PlayState", "deathCounter")
```

**Comment by tylerandari12** [comment]
Fastest issue ever.
Thanks a lot :D

**Comment by FlintIshe** [comment]
lmao ok thanks alot

**Comment by FlintIshe** [comment]
[jez.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8694370/jez.zip)

I discovered some issues lol
