### ISSUE TITLE
Different Game Over For A Specific Song

### ISSUE THREAD

**Issue by cyborghenry** [ShadowMario/FNF-PsychEngine#8634]
### Describe your problem here.

so like i want to make it so in a specific song i want an image to appear when you die instead of bf's skeleton
and i dont know how to do this myself
please help me

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No i didnt edit anything

**Comment by Stilic** [comment]
there is a example on the wiki lmao (lua api section)

**Comment by cyborghenry** [comment]
o ok

**Comment by cyborghenry** [comment]
which one 💀

**Comment by Stilic** [comment]
> which one 💀

https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API#example-scripts
the one who changes the game over shit

**Comment by cyborghenry** [comment]
o ok

**Comment by cyborghenry** [comment]
thanks
