### ISSUE TITLE
Vocals

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#8635]
### Describe your problem here.

So a friend of mine is trying to make the vocals of a character but he can't, he says that he looks like he's talking instead of singing. He uses FL studio

Can someone help me? Sending a tutorial or something would be good too but i would like to you guys to tell me how to make vocals from an existing audio.
(ignore the lua shit)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by MaybeMaru** [comment]
This is not related to the engine but Ig I recommed the bbpanzu tutorial on how to make vocals
