### ISSUE TITLE
shaders

### ISSUE THREAD

**Issue by Aldoxseaburre223** [ShadowMario/FNF-PsychEngine#8638]
### Describe your problem here.

hi, I am currently doing a mod in version 0.5.2h and I am trying to add shaders, but when I put the level, they do not work, I have downloaded the .exe directly, the codes I used at the moment are
addVCREffect('camGame',0.06,true,true,true)
addChromaticabberationEffect('game' ,0.003
please can someone help me 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
0.5.2 doesn't have shaders

**Comment by Aldoxseaburre223** [comment]
and, which version of the psiych engine have shaders?

**Comment by MateoSorianoGi** [comment]
> and, which version of the psiych engine have shaders?

Its 0.5.1
