### ISSUE TITLE
Can't hide healthBarBG

### ISSUE THREAD

**Issue by fistiG** [ShadowMario/FNF-PsychEngine#8639]
### Describe your problem here.

I'm tryin' to hide healthBarBG for my custom healthbar but I can't. How to fix it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by wubbzyfan** [comment]
function onCreatePost()
        setProperty('healthBar.visible', false)
	setProperty('healthBarBG.visible', false)
	setProperty('iconP1.visible', false)
	setProperty('iconP2.visible', false)
end

**Comment by tylerandari12** [comment]
@wubbzyfan
Is your username a reference to wow wow Wubbzy?

**Comment by FlintIshe** [comment]
Close this thing if it works
