### ISSUE TITLE
i need help for psych engine

### ISSUE THREAD

**Issue by h0ppies** [ShadowMario/FNF-PsychEngine#8641]
### Describe your bug here.

i just downloaded the psych engine 0.5.2h and every time i go on a song except  tutorial and it crashes every time. Also gf keeps turning into a black square.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i edited changed the menu music

**Comment by frantastic24** [comment]
Issue with your PC, not enough memory

**Comment by SnakDev** [comment]
yes also the files might be corrupted
