### ISSUE TITLE
What am I doing wrong here

### ISSUE THREAD

**Issue by Aden-Mystio** [ShadowMario/FNF-PsychEngine#8642]
### Describe your problem here.

[Character help](https://youtu.be/gWvurJGRQDg)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

idk what to put here

**Comment by Lorekeeper49** [comment]
This animations need to be named singLEFT, singRIGHT, singUP, singDOWN, singLEFTmiss, singRIGHTmiss, singUPmiss, and singDOWNmiss

**Comment by Aden-Mystio** [comment]
> This animations need to be named singLEFT, singRIGHT, singUP, singDOWN, singLEFTmiss, singRIGHTmiss, singUPmiss, and singDOWNmiss

I got it working nvm
