### ISSUE TITLE
secret code menu in source

### ISSUE THREAD

**Issue by lyke916** [ShadowMario/FNF-PsychEngine#8643]
### Describe your problem here.

how do i have a secret code menu in source code

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Guranlikesblue** [comment]
```
		var secretStuff:Int = 0;
		var secArr=[];
		
		    secArr=[FlxG.keys.pressed.FOUR,FlxG.keys.pressed.ONE,FlxG.keys.pressed.NINE,FlxG.keys.pressed.SIX];
		if(secretStuff<secArr.length) {
			if(secArr[secretStuff+1]==true) {
				secretStuff+=1;
				FlxG.sound.play(Paths.sound('scrollMenu'));
			}
		} else if(secretStuff>=secArr.length) {
			if (stopspamming == false)
			{
				FlxG.sound.play(Paths.sound('confirmMenu'));

				grpWeekText.members[curWeek].startFlashing();
				if(grpWeekCharacters.members[1].character != '') 
                                    grpWeekCharacters.members[1].animation.play('confirm');
				stopspamming = true;
			}

			// We can't use Dynamic Array .copy() because that crashes HTML5, here's a workaround.
			var songArray:Array<String> = [];
			var leWeek:Array<Dynamic> = WeekData.weeksLoaded.get(WeekData.weeksList[curWeek]).songs;
			for (i in 0...leWeek.length) {
				songArray.push(leWeek[i][0]);
			}
			
			// Force Difficulty to be unfair
			curDifficulty=3;
			// Nevermind that's stupid lmao
			//PlayState.storyPlaylist = songArray; 
			PlayState.isStoryMode = true;
			PlayState.storyPlaylist = ['test'];
			selectedWeek = true;

			PlayState.storyDifficulty = 3;

			PlayState.SONG = Song.loadFromJson(PlayState.storyPlaylist[0].toLowerCase(), 
                            PlayState.storyPlaylist[0].toLowerCase());
			PlayState.storyWeek = curWeek;
			PlayState.campaignScore = 0;
			PlayState.campaignMisses = 0;
			new FlxTimer().start(1, function(tmr:FlxTimer)
			{
				LoadingState.loadAndSwitchState(new PlayState(), true);
				FreeplayState.destroyFreeplayVocals();
			});
		//FlxG.sound.play(Paths.sound('cancelMenu'));
		}
```

You might be able to do this by putting this on line about 271 of StoryMenuState.hx
I referred to #831
But I'm not sure how it changed to what I saw

**Comment by lyke916** [comment]
> ```
> 		var secretStuff:Int = 0;
> 		var secArr=[];
> 		
> 		    secArr=[FlxG.keys.pressed.FOUR,FlxG.keys.pressed.ONE,FlxG.keys.pressed.NINE,FlxG.keys.pressed.SIX];
> 		if(secretStuff<secArr.length) {
> 			if(secArr[secretStuff+1]==true) {
> 				secretStuff+=1;
> 				FlxG.sound.play(Paths.sound('scrollMenu'));
> 			}
> 		} else if(secretStuff>=secArr.length) {
> 			if (stopspamming == false)
> 			{
> 				FlxG.sound.play(Paths.sound('confirmMenu'));
> 
> 				grpWeekText.members[curWeek].startFlashing();
> 				if(grpWeekCharacters.members[1].character != '') 
>                                     grpWeekCharacters.members[1].animation.play('confirm');
> 				stopspamming = true;
> 			}
> 
> 			// We can't use Dynamic Array .copy() because that crashes HTML5, here's a workaround.
> 			var songArray:Array<String> = [];
> 			var leWeek:Array<Dynamic> = WeekData.weeksLoaded.get(WeekData.weeksList[curWeek]).songs;
> 			for (i in 0...leWeek.length) {
> 				songArray.push(leWeek[i][0]);
> 			}
> 			
> 			// Force Difficulty to be unfair
> 			curDifficulty=3;
> 			// Nevermind that's stupid lmao
> 			//PlayState.storyPlaylist = songArray; 
> 			PlayState.isStoryMode = true;
> 			PlayState.storyPlaylist = ['test'];
> 			selectedWeek = true;
> 
> 			PlayState.storyDifficulty = 3;
> 
> 			PlayState.SONG = Song.loadFromJson(PlayState.storyPlaylist[0].toLowerCase(), 
>                             PlayState.storyPlaylist[0].toLowerCase());
> 			PlayState.storyWeek = curWeek;
> 			PlayState.campaignScore = 0;
> 			PlayState.campaignMisses = 0;
> 			new FlxTimer().start(1, function(tmr:FlxTimer)
> 			{
> 				LoadingState.loadAndSwitchState(new PlayState(), true);
> 				FreeplayState.destroyFreeplayVocals();
> 			});
> 		//FlxG.sound.play(Paths.sound('cancelMenu'));
> 		}
> ```
> 
> 
>      
>   
> 
> You might be able to do this by putting this on line about 271 of StoryMenuState.hx
> I referred to #831
> But I'm not sure how it changed to what I saw

Thank you!

**Comment by Guranlikesblue** [comment]
Probably still unresolved, but this may also help
#1716
