### ISSUE TITLE
Waveform in chart editor offset by ~1 step, bpm changes offset it even more.

### ISSUE THREAD

**Issue by CyndaquilDAC** [ShadowMario/FNF-PsychEngine#8644]
### Describe your bug here.

pretty self explanatory, this makes it really annoying to chart and can cause problems for a lot of people. screenshot below, i have play sound toggled so I know this isnt a mistake on my end.

![image](https://user-images.githubusercontent.com/65635932/168449218-da0bbf7d-50aa-4d76-b83a-048b52078311.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

This is a vanilla build of the latest version of psych with no mods installed, I am charting on top of spookeez to be implemented into a custom build later.

**Comment by tylerandari12** [comment]
Somethings up with your BPM...

**Comment by tylerandari12** [comment]
> > Somethings up with your BPM...
> 
> thats a reasonable bpm

I used a bpm tapper and it’s completely different.

**Comment by CyndaquilDAC** [comment]
im not actually charting spookeez im charting a different song on top of spookeez lmao
