### ISSUE TITLE
lua help

### ISSUE THREAD

**Issue by XperiorTR** [ShadowMario/FNF-PsychEngine#8645]
### Describe your problem here.

both of these dont work and i dont know why
im hoping i did something stupid lol
(they work out of the if statements)
![image](https://user-images.githubusercontent.com/80666310/168449915-d8f8a165-da21-4b6e-a10c-34e3dcd87ff5.png)
![image](https://user-images.githubusercontent.com/80666310/168449958-53f2bce9-7116-4d40-aaf5-804983417cf6.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by FlintIshe** [comment]
may be put circInOut or linear will work, idk
