### ISSUE TITLE
Invalid char 125 at position 152

### ISSUE THREAD

**Issue by LucasOnGithub** [ShadowMario/FNF-PsychEngine#8646]
### Describe your bug here.

For the past month now I've been getting this error every time I try to go into one of my custom songs in the Freeplay menu, chart editor, and the story mode menu. I don't know what the issue is, every psych engine build I download, from source to lua, and when I try to and paste the mod into the mods folder, going into any of the songs just, doesn't work.

![stupid error](https://user-images.githubusercontent.com/35154566/168452220-7f980fbd-f6e5-4c33-896d-de0ab153dd3a.png)

### Command Prompt/Terminal logs (if existing)

_not that i know of._

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I did, (from when I was making this on a source build). I edited titlestate.hx for the bpm, text at the start of the titlescreen (the "shoutout to newgrounds" or "psych engine made by" or something. i also edited freeplay state.hx to get rid of "awards mods" and "donate" from the menu. aswell as credit state.hx (I probably edited more things but I don't really remember them).

**Comment by frantastic24** [comment]
That means one of your .jsons is broken

**Comment by LucasOnGithub** [comment]
> That means one of your .jsons is broken

**Comment by LucasOnGithub** [comment]
> That means one of your .jsons is broken

do i have to find the json and then delete or fix it?

**Comment by LucasOnGithub** [comment]
now when I added the stage to the mods folder, it completely breaks for no reason, and it gives a fuck ton of more errors. there's nothing wrong with the stage at all. here's the contents of the stage.

```
function onCreate()

	makeLuaSprite('gre', 'green_hill', -250, 432);
	setScrollFactor('gre', 1.1, 1.1);
	scaleObject('gre', 3.5, 1.75);


	addLuaSprite('gre',false)

end
```
```
{
	"directory": "",
	"defaultZoom": 0.7,
	"isPixelStage": false,

	"boyfriend": [780, 100],
	"girlfriend": [380, 130],
	"opponent": [100, 100],
}
```

![WHY](https://user-images.githubusercontent.com/35154566/168452577-791bba6b-5d4b-4ec3-a992-55a431cf6d26.png)

**Comment by LucasOnGithub** [comment]
and yes, the image for the stage is in the images folder.

**Comment by tylerandari12** [comment]
The game doesnt like us.

**Comment by NS-Unfair** [comment]
`
 {
	"directory": "",
	"defaultZoom": 0.7,
	"isPixelStage": false,

	"boyfriend": [780, 100],
	"girlfriend": [380, 130],
	"opponent": [100, 100], <-- Remove this colon
 }
`

**Comment by Lorekeeper49** [comment]
> `
>  {
> 	"directory": "",
> 	"defaultZoom": 0.7,
> 	"isPixelStage": false,
> 
> 	"boyfriend": [780, 100],
> 	"girlfriend": [380, 130],
> 	"opponent": [100, 100], <-- Remove this colon
>  }
> `

It's not a colon, it's a comma

**Comment by LucasOnGithub** [comment]
> `
> 
> ```
> {
> 	"directory": "",
> 	"defaultZoom": 0.7,
> 	"isPixelStage": false,
> 	
> 	"boyfriend": [780, 100],
> 	"girlfriend": [380, 130],
> 	"opponent": [100, 100], <-- Remove this *comma
> }
> ```
> 
> `

Damn I'm an idiot. I never realized a comma was the problem. thanks for the help! it took me so long on how to figure this out.
