### ISSUE TITLE
Is my LUA file outdated or something?

### ISSUE THREAD

**Issue by bruh-guy** [ShadowMario/FNF-PsychEngine#8648]
### Describe your bug here.

I don't recall if I used a preset to make it or if it was already premade but I had a LUA file for the week 7 stage. It's worked perfectly in every previous version of the engine but it suddenly doesn't. The images and scripts are straight copy-pasted too, which makes it more confusing. Whether the images are separate or in a designated "Tankstage" folder, the stage is completely black and shows nothing. What's going on?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I have not touched the source code at all.

**Comment by frantastic24** [comment]
Can't tell what's going on if you show literally none of your files

**Comment by bruh-guy** [comment]
[week7shit.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8696391/week7shit.zip)

sorry, here you go.

**Comment by frantastic24** [comment]
It's probably because of `os.time`, which isn't supported in newer versions

**Comment by bruh-guy** [comment]
Sorry, I don't know too much about how this works. Should I remove it, replace it with something else, or will the entire LUA file just not work anymore?

**Comment by bruh-guy** [comment]
It's a little different now. Everything's still black but Haxefixel logos pop up where stuff should be. I think I might need to get a new LUA file or something. Maybe you could edit it how you think it should be and send me it to see if it works?

**Comment by frantastic24** [comment]
That means the texture paths are incorrect iirc

**Comment by bruh-guy** [comment]
Thank you! Shit's finally working again.

**Comment by ShadowMario** [comment]
This means you're using my stolen Week 7 lua port so lmao
