### ISSUE TITLE
Sprite Name

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8649]
### What is your question?

Is there a way to get the name of the original image of a sprite?
I need to get the name of `iconP1` but I dont know how. ;-;

**Comment by Mastercopper2346** [comment]
just look in the files, its not that hard

**Comment by tylerandari12** [comment]
> just look in the files, its not that hard

I wish it was that easy.
I need to access the variable **inside a script**.
But its ok I found a different soloution.
