### ISSUE TITLE
VERY VERY BIG QUESTION

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8650]
### What is your question?

What is the group for bf's notes?

This will be very helpful

**Comment by tylerandari12** [comment]
A big question indeed.

**Comment by Mastercopper2346** [comment]
pls i need answer

**Comment by FlintIshe** [comment]
wdym groups

**Comment by Mastercopper2346** [comment]
like `getPropertyFromGroup`.

**Comment by frantastic24** [comment]
No, the question is if by "group" you mean `playerStrums` or `mustHit` notes

**Comment by Mastercopper2346** [comment]
yeah `mustHit` cuz `playerStrums` are the idle notes and i don't want that

**Comment by frantastic24** [comment]
```lua
getPropertyFromGroup('unspawnNotes', i, 'mustPress')
```
