### ISSUE TITLE
how do I add this very complicated character?

### ISSUE THREAD

**Issue by Lorekeeper49** [ShadowMario/FNF-PsychEngine#8651]
### What is your question?

so I want to add vs retro's minus sakuroma to my RetroKamex charts (link: https://gamebanana.com/mods/336786) for the chart of Frostbite 2, but I just found out that that character uses a limb-based spritemap to do the animations, is there any way I can work this on Lua?

**Comment by tylerandari12** [comment]
Tweens centered around the stage jsons x and y...

**Comment by Lorekeeper49** [comment]
Dude, here are the files, the txt files were originally jsons
![spritemap](https://user-images.githubusercontent.com/93066594/169669713-dc5959e7-c236-46ce-a730-f394f8f8e89f.png)
[spritemap.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8748373/spritemap.txt)

**Comment by frantastic24** [comment]
place atlas files in a folder (or just copy it from the source), set the spriteType to `'texture'` when making the sprite then add animations as usual

**Comment by Lorekeeper49** [comment]
> place atlas files in a folder (or just copy it from the source), set the spriteType to `'texture'` when making the sprite then add animations as usual

I actually want to make it a defined character

**Comment by frantastic24** [comment]
Then just type the folder path in the character editor, same thing

**Comment by AyMarte** [comment]
You gotta use Adobe Animate to edit that into a sprite sheet in xml. lol
