### ISSUE TITLE
close() closes the entire game instead of just the script.

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8652]
### Describe your bug here.

Me and the person in #8603 have had this problem where typing `close()` will crash the game and I don't think that's how it works.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing changed.

**Comment by Mastercopper2346** [comment]
doesnt happen for me.

**Comment by tylerandari12** [comment]
does for me

It might be a memory issue

**Comment by Steviegt6** [comment]
As per `close`'s definition [here](https://github.com/ShadowMario/FNF-PsychEngine/blob/a67f796577677bf975965c75126a16c4ef76d374/source/FunkinLua.hx#L1429), it should only close the script. The script is pushed to a list which is handled [here](https://github.com/ShadowMario/FNF-PsychEngine/blob/f4cf818dac20859fd0223206609ba91b6818831f/source/PlayState.hx#L4760). This simply removes it from the list of scripts to use and stops the execution of the script. If the game is closing, it is a result of some error in the script or game, whether it be a memory issue or something else.

**Comment by tylerandari12** [comment]
> As per `close`'s definition [here](https://github.com/ShadowMario/FNF-PsychEngine/blob/a67f796577677bf975965c75126a16c4ef76d374/source/FunkinLua.hx#L1429), it should only close the script. The script is pushed to a list which is handled [here](https://github.com/ShadowMario/FNF-PsychEngine/blob/f4cf818dac20859fd0223206609ba91b6818831f/source/PlayState.hx#L4760). This simply removes it from the list of scripts to use and stops the execution of the script. If the game is closing, it is a result of some error in the script or game, whether it be a memory issue or something else.
> 
> 
> 
> Since you closed this issue, I assume you confirmed it to be a memory problem?

I'm not the only one to experience this issue which is why I reported it...

It only happens on stage scripts however...
