### ISSUE TITLE
I think psychic engine should make a tutorial for the no source code achievement

### ISSUE THREAD

**Issue by DJ-IS-THE-GOD** [ShadowMario/FNF-PsychEngine#8653]
### What feature do you want to get added on the **base** engine?

please make a no source code achievement tutorial please make a no source code achievement tutorial please make a no source code achievement tutorial

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by Mastercopper2346** [comment]
the soft coded achievements were removed, and they forgot to delete the folder.

**You also failed the test.**

**Comment by MaybeMaru** [comment]
I swear to god people never look up stuff before posting

**Comment by silvashp** [comment]
dumbass

**Comment by PrismLight** [comment]
Psych**ic** engine.
Once again...
