### ISSUE TITLE
Game got slow down(bug?)

### ISSUE THREAD

**Issue by BorisC04** [ShadowMario/FNF-PsychEngine#8655]
### Describe your bug here.

I compile the engine on my two pc and the first pc(windows 10) works fine and well. However,  when I do the same to the second pc(windows 11), stuff starts to go wrong. Basically the game slow down like it is in 0.25x speed. The fps is 30 while the cap is 240(I am 100% sure my pc can go much more than 30) The menu took years to load. Weird enough, stuff go back to normal when I play any song and the game seems ok(although it is still stuck in 30fps) I have no idea why. Every time I boot up the game the same thing happens. Sometimes it didn't have the problem but it's rare and I have no idea why. Here is a video. I zip it because the video is more than 10MB and github doesn't like it. Btw I edited nothing it is the default stuff downloaded from here.
[FNF bug video.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8694858/FNF.bug.video.zip)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by jimmyjamescool** [comment]
thats a windows issue, nothing wrong is with the game. (i think)

**Comment by ShadowMario** [comment]
I can't load the video, i don't know what format it originally was. MP4 doesn't work.

**Comment by machonessiebaby** [comment]
noting is inside your compressed video file use [streamables](https://streamable.com/) for uploading

**Comment by BorisC04** [comment]
Here is the video that I failed to upload, sorry about that.

https://streamable.com/x92bs8
https://streamable.com/4j7ok0

There is one more thing that I want to address is my windows 10 pc is a crap(can't even upgrade to windows 11) and the pc I have problem on is much better on hardware in terms of CPU, GPU, RAM and stuff like that. It won't make sense for a pc with better hardware to run worse than a crappy one so I am pretty sure I did something wrong on software stuff. Another thing worth mentioning is the animation is really smooth, but slow. It is not lag but like the speed assigned to it doesn't work as intended.

**Comment by BorisC04** [comment]
> thats a windows issue, nothing wrong is with the game. (i think)

What do you mean by that? The operating system or hardware?

**Comment by frantastic24** [comment]
Iirc this happened to me when I forced vsync through external software and changed fps cap in-game to something higher than my monitor's refresh rate

**Comment by frantastic24** [comment]
It's really not

**Comment by machonessiebaby** [comment]
> Here is the video that I failed to upload, sorry about that.
> 
> https://streamable.com/x92bs8 https://streamable.com/4j7ok0
> 
> There is one more thing that I want to address is my windows 10 pc is a crap(can't even upgrade to windows 11) and the pc I have problem on is much better on hardware in terms of CPU, GPU, RAM and stuff like that. It won't make sense for a pc with better hardware to run worse than a crappy one so I am pretty sure I did something wrong on software stuff. Another thing worth mentioning is the animation is really smooth, but slow. It is not lag but like the speed assigned to it doesn't work as intended.

this is a frame bug it will fix somtimes if you
a reset pc
b restart game
c recompile
d (if lua) redownload

(save progress before shutdown)(im not an expert but i had this work for me)

**Comment by jimmyjamescool** [comment]
> > @jimmyjamescool thats a windows issue, nothing wrong is with the game. (i think)
> 
> What do you mean by that? The operating system or hardware?

the hardware you prob dont have enough ram, memory, cpu, or smth else i dunno

**Comment by BorisC04** [comment]
> > Here is the video that I failed to upload, sorry about that.
> > https://streamable.com/x92bs8 https://streamable.com/4j7ok0
> > There is one more thing that I want to address is my windows 10 pc is a crap(can't even upgrade to windows 11) and the pc I have problem on is much better on hardware in terms of CPU, GPU, RAM and stuff like that. It won't make sense for a pc with better hardware to run worse than a crappy one so I am pretty sure I did something wrong on software stuff. Another thing worth mentioning is the animation is really smooth, but slow. It is not lag but like the speed assigned to it doesn't work as intended.
> 
> this is a frame bug it will fix somtimes if you a reset pc b restart game c recompile d (if lua) redownload
> 
> (save progress before shutdown)(im not an expert but i had this work for me)

I tried a, b and c so many times and they won't work
Also what do you mean by redownload lua, the `linc_lua jit`?

**Comment by BorisC04** [comment]
> > > @jimmyjamescool thats a windows issue, nothing wrong is with the game. (i think)
> > 
> > 
> > What do you mean by that? The operating system or hardware?
> 
> the hardware you prob dont have enough ram, memory, cpu, or smth else i dunno

It would be not making sense when my pc with problem has better hardware than the one that works, unless the companies scam me

**Comment by BorisC04** [comment]
Anyone can help me or give me some advice to solve this problem? I am stuck with this issue for so long

**Comment by ShadowMario** [comment]
The issue is the following: Your PC sucks
To solve this issue: Buy a new PC
:+1:
