### ISSUE TITLE
How would i add a bootup cutseen

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#8659]
### Describe your problem here.

How would i make it so when you open the mod it will play a cutseen

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

A lot of source and mods folder

**Comment by ArthurYago** [comment]
I think its easier to do it with lua, but idk if lua can play an cutscene in main menu

**Comment by machonessiebaby** [comment]
> I think its easier to do it with lua, but idk if lua can play an cutscene in main menu

lua cant mess with menu

**Comment by Itz-NOT-Miles** [comment]
put this line of code in titleState.hx:  startVideo("your video's name");

**Comment by machonessiebaby** [comment]
> put this line of code in titleState.hx: startVideo("your video's name");

this bugged but i will try again

**Comment by machonessiebaby** [comment]
> put this line of code in titleState.hx: startVideo("your video's name");
![image](https://user-images.githubusercontent.com/56323671/168914750-39cd9f46-b757-4c55-982f-0520a273be35.png)

**Comment by Itz-NOT-Miles** [comment]
for 0.4 hotfixes and beyond, you might have to try: PlayState.instance.startVideo("your video name");
If forcing a function from playstate doesn't work, try: new FlxVideo('your video name")

**Comment by machonessiebaby** [comment]
> for 0.4 hotfixes and beyond, you might have to try: PlayState.instance.startVideo("your video name"); If forcing a function from playstate doesn't work, try: new FlxVideo('your video name");

thank you

**Comment by machonessiebaby** [comment]
> for 0.4 hotfixes and beyond, you might have to try: PlayState.instance.startVideo("your video name"); If forcing a function from playstate doesn't work, try: new FlxVideo('your video name");

i keep getting null object refrence
![image](https://user-images.githubusercontent.com/56323671/169165026-eb135937-dca9-4bbd-8322-a377e50275aa.png)

i have a cache loading screen file it will play after would i put the fxl video pr the playstate under case one what line would i put it under?

**Comment by Itz-NOT-Miles** [comment]
I'm not near a compile target I can test videos on, gimmie a moment later today to check where to put n`ew FlxVideo('your video name");`, or figure out why it isn't working.

**Comment by Itz-NOT-Miles** [comment]
new FlxVideo('assets/videos/"your video name".mp4);

**Comment by BrightEyesFox** [comment]
i tried and none of it works

**Comment by Itz-NOT-Miles** [comment]
Put your 1280x720p .mp4 file in the Psych Engine's root folder. `assets>videos`. Place the line,  `new FlxVideo('your video name".mp4);` in the .hx file where you want the video to play, and then compile it. It works if you follow this. Never tell someone SOUCRE CODE doesn't work, otherwise it's something wrong with your build.

**Comment by BrightEyesFox** [comment]
![image](https://user-images.githubusercontent.com/91453227/170559516-25c42d8b-1bec-4a3d-b3d7-d4c6be7b2a36.png)

**Comment by Itz-NOT-Miles** [comment]
you two should show me what your code blocks look like, there shouldn't be any issues with syntax. Videos work just fine.

`new FlxVideo(assets/videos/videonName.mp4');`

![Screenshot (42)](https://user-images.githubusercontent.com/101573375/170723533-27486f29-8275-4c64-b516-cb4d8176c04d.png)

**Comment by BrightEyesFox** [comment]
dont have pc access rn so imma say it from memory:

case 1:

             // skip.Intro()

             new Flx video("brap".mp4);

i think it was something like this idk i dont remember

**Comment by machonessiebaby** [comment]
> Itz

it goes case 1 then 3 cuz 2 breaks the code 0 idea why
![image](https://user-images.githubusercontent.com/56323671/170774080-485d74a3-870f-4ae6-863e-39e2dcb2e377.png)

**Comment by PrismLight** [comment]
> dont have pc access rn so imma say it from memory:
> 
> case 1:
> 
> ```
>          // skip.Intro()
> 
>          new Flx video("brap".mp4);
> ```
> 
> i think it was something like this idk i dont remember

`new Flx video("assets/videos/brap.mp4");`
lol

**Comment by Itz-NOT-Miles** [comment]
were guys keeping the quotes in the whole time??

**Comment by BrightEyesFox** [comment]
> were you guys keeping the quotes in the whole time??

how was i supposed to know? you didnt say NOT to include the quotes?

**Comment by BrightEyesFox** [comment]
ok i changed the code and now it works, thanks
![image](https://user-images.githubusercontent.com/91453227/170823334-2e52dc11-b617-48a7-8622-6fed1f328c95.png)

**Comment by AxzonZero** [comment]
Wait so what line in TitleState.hx do I put "new FlxVideo(assets/videos/videonName.mp4')?" 
I want it on startup..

**Comment by Al-AmeenAdewunmi** [comment]
Yeah, so I put in the code, but when I try building it I end up with:

"source/TitleState.hx:664: characters 9-17 : Type not found : FlxVideo"

What should I do?
