### ISSUE TITLE
How to change upcoming song, like in Sansational.

### ISSUE THREAD

**Issue by ArthurYago** [ShadowMario/FNF-PsychEngine#8660]
### Describe your problem here.

Im porting Indie Cross Sans to Psych Engine, but i don't know what to do with Sansational, first, i want that, if you attack Sans, the upcoming song will be Burning In Hell, not Final Stretch and second, i want to change the chart mid song, like, if you attack Sans, that part will have bone notes.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I just added the songs, the dodge event and attack mechanic.

**Comment by Mastercopper2346** [comment]
```
function onUpdate()
     if keyJustPressed('space') then
          hell = true
          charPlayAnim('boyfriend', 'attack', true);
     end
end

function onDestroy()
     if hell == true then
          loadSong('Burning-in-hell,' 2);
     end
end
```

**Comment by ArthurYago** [comment]
Holy Sheet thx

**Comment by ArthurYago** [comment]
but, where did you find it?

**Comment by xChillax** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/blob/bea4eb12af5b8b20db2b8ca24ae7a9b698b9a893/source/FunkinLua.hx#L262

This file has all the available Lua functions. A bunch of them are not documented in the wiki.

**Comment by WoodsSilent05** [comment]
> ```
> function onUpdate()
>      if keyJustPressed('space') then
>           hell = true
>           charPlayAnim('boyfriend', 'attack', true);
>      end
> end
> 
> function onDestroy()
>      if hell == true then
>           loadSong('Burning-in-hell,' 2);
>      end
> end
> ```

that does not work it just crashes the game, and the script does not like anything + the 2 on where the 2 is. it yells at me that ) is supposed to be there but it is there so idk but it does not work in the build 0.5.2h

**Comment by Mastercopper2346** [comment]
```
function onUpdate()
     if keyJustPressed('space') then
          hell = true
          charPlayAnim('boyfriend', 'attack', true);
     end
end

function onDestroy()
     if hell == true then
          endSong()
          loadSong('Burning-in-hell,' 2);
     end
end
```

Try that

**Comment by WoodsSilent05** [comment]
same thing but it does not crash the game when the 2 is removed, the script just does nothing.

**Comment by WoodsSilent05** [comment]
Also i tried lots of other things to moddify it but it did not work

**Comment by Noel3454565FNF** [comment]
i find something in the adapted indee cross psych engine
i think this can help ya

local allowEndSong = false
function onEndSong()
    if not allowEndSong and not seenCutscene and isStoryMode then
        if attack < 3 then
            loadSong('Final-Stretch',difficuty)
            return Function_Stop
        elseif attack >= 3 then
            loadSong('Burning-In-Hell',difficuty)
            return Function_Stop
        end
    end
end

**Comment by Noel3454565FNF** [comment]
> Aussi, j’ai essayé beaucoup d’autres choses pour le moddifier mais cela n’a pas fonctionné

I FINALLY FOUND HOW IT IS WORK:
you have to change "fracture" by the name of your song, and if your song is not on the same week this not work

function onUpdate(elapsed)
	if keyJustPressed('space') then
		loadSong('fracture', -1);
		return Function_Stop
	end
end
