### ISSUE TITLE
How do I use shaders

### ISSUE THREAD

**Issue by coolaydang** [ShadowMario/FNF-PsychEngine#8661]
### What is your question?

I have no idea how to use shaders

**Comment by machonessiebaby** [comment]
soft coded do not work 5.2h removed them those are leftovers

**Comment by coolaydang** [comment]
but why :(((

**Comment by tylerandari12** [comment]
> but why :(((

Adding shaders is a costly procedure.

Too costly for Lua...

**Comment by ShadowMario** [comment]
> > but why :(((
> 
> Adding shaders is a costly procedure.
> 
> Too costly for Lua...

That's not why it was removed bro
It was using code from people without their consent, that's why i removed it

**Comment by tylerandari12** [comment]
> > > but why :(((
> 
> > 
> 
> > Adding shaders is a costly procedure.
> 
> > 
> 
> > Too costly for Lua...
> 
> 
> 
> That's not why it was removed bro
> 
> It was using code from people without their consent, that's why i removed it

Oki
