### ISSUE TITLE
Is there a way to change the player's arrow colors?

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8663]
### Describe your problem here.

and no, don't mention #7844, it doesn't work for me.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

what

**Comment by tylerandari12** [comment]
```
function onCreate()
    setPropertyFromGroup('playerStrums', 0, 'color', value:Int)
    setPropertyFromGroup('playerStrums', 1, 'color', value:Int)
    setPropertyFromGroup('playerStrums', 2, 'color', value:Int)
    setPropertyFromGroup('playerStrums', 3, 'color', value:Int)
end
--replace playerStrums with opponentStrums for opponents strums
```
If it doesnt work the i dont know what to tell you...

**Comment by Mastercopper2346** [comment]
`playerStrums` is the **strumline**, not the actual **note**.

**Comment by Mastercopper2346** [comment]
@ShadowMario, @frantastic24, @everyone, help.

**Comment by Mastercopper2346** [comment]
> function onCreate()
    setPropertyFromGroup('playerStrums', 0, 'color', value:Int)
    setPropertyFromGroup('playerStrums', 1, 'color', value:Int)
    setPropertyFromGroup('playerStrums', 2, 'color', value:Int)
    setPropertyFromGroup('playerStrums', 3, 'color', value:Int)
end

basically, its #7844.
bruh

**Comment by Mastercopper2346** [comment]
also it doesnt work

**Comment by Mastercopper2346** [comment]
i got SOMETHING working, here it is.
```
function onCreatePost()
	for i = 0, getProperty('unspawnNotes.length') do
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == '' then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'BFNOTE_assets'); --Change texture
			setPropertyFromGroup('unspawnNotes', i, 'mustPress')
		end
	end
end
```
Problem is, that changes for the OPPONENT, and also even if its mustHitSection the opponent plays.

**Comment by Mastercopper2346** [comment]
NVM I GOT IT
```
function onCreatePost()
	for i = 0, getProperty('unspawnNotes.length') do
		if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'BFNOTE_assets'); --Change texture
		end
	end
end
```
