### ISSUE TITLE
Theres A way to make this effect? without lua (idk if i already asked it 💀)

### ISSUE THREAD

**Issue by Plotsh** [ShadowMario/FNF-PsychEngine#8666]
### What is your question?

![Screenshot_20220511-174316](https://user-images.githubusercontent.com/84821153/168504195-e16487f4-9628-4b13-8afd-1acc279a522d.png)

**Comment by jimmyjamescool** [comment]
Thats an .hx Shader. it means you cant drag it in without source code.

**Comment by jimmyjamescool** [comment]
for example, the swirly backround thingy in dave and bambi is an .hx file. plus the eyesores effect is a .hx file

**Comment by jimmyjamescool** [comment]
if you have the sonic.exe source code. copy and paste the .hx file into the source directory

**Comment by jimmyjamescool** [comment]
(for psych engine source directory that is)
