### ISSUE TITLE
help i can't build the game 

### ISSUE THREAD

**Issue by sebby09559** [ShadowMario/FNF-PsychEngine#8667]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/42832765/168518171-bd03facf-b6cf-4c7a-a1c0-0ca1a00b6003.png)
 can anyone help me with this

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i added my own stuff in the example mods folder

**Comment by Mastercopper2346** [comment]
> # Are you modding a build from source or with Lua?
> Lua

...

**Comment by Mastercopper2346** [comment]
also you cant really compile html5.

**Comment by zeonagames** [comment]
same error :(

**Comment by Wither362** [comment]
you cant access sys while targeting html5, try to fix it with what i just tell you
