### ISSUE TITLE
How to change chart mid song

### ISSUE THREAD

**Issue by ArthurYago** [ShadowMario/FNF-PsychEngine#8670]
### Describe your problem here.

Im porting Indie Cross Sans to Psych Engine, and i want that, if you attack sans in Sansational, it will have bone notes,  maybe i can make invisible notes, that you cant press, but if you attack him, it will switch to a bone note, but i don't know how to make it unpresseble

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing that could ruin everything

**Comment by Mastercopper2346** [comment]
Make a new noteType, and use this.
```
chartDifference = false
     if 'keysJustPressed('space) then
          chartDifference = true
          -- other code
     end
end
```

**Comment by ArthurYago** [comment]
ok, but what i put in other code? @Mastercopper2346
