### ISSUE TITLE
Jump Animation Not Working (Lua)

### ISSUE THREAD

**Issue by NesDoesGithub** [ShadowMario/FNF-PsychEngine#8672]
### Describe your problem here.

I am making a running character and they jump over obstacles throughout the level, there is a seperate animation for the jumping animation for the legs, but the jumping animation will not work. When the timer runs the 'firebfthing' (running) animation keeps on playing.

```
    makeAnimatedLuaSprite('firebflegs','pcport/bflegs', -42, 90);
	addAnimationByPrefix('firebflegs','firebfthing','runfire',24,true);
    addAnimationByPrefix('firebflegs','jump','jumpfire',24,true);
    objectPlayAnimation('firebflegs','firebfthing',false);
    setScrollFactor('firebflegs', 1, 1);
	scaleObject('firebflegs', 10, 10);
	setProperty('firebflegs.antialiasing',false)
```

```
local bfjumping = false

function onUpdate()
    if bfjumping == true then
        objectPlayAnimation('firebflegs','jump',false);
    end

    if bfjumping == false then
        objectPlayAnimation('firebflegs','firebfthing',false);
    end
end
```

```
function onTimerCompleted(tag, loops, loopsLeft)

    if tag == 'jumpstairs1' then
        doTweenY('bfmoveY', 'boyfriend', -216, 0.5, 'sineOut')
        doTweenY('bffirelegsmoveY', 'firebflegs', -476, 0.5, 'sineOut')
        runTimer('jumpstairs1-2', 0.5, 1)
        bfjumping = true
    end

    if tag == 'jumpstairs1-2' then
        doTweenY('bfmoveY', 'boyfriend', 350, 0.5, 'sineIn')
        doTweenY('bffirelegsmoveY', 'firebflegs', 90, 0.5, 'sineIn')
        runTimer('jumpstairsend', 0.5, 1)
    end

    if tag == 'jumpstairsend' then
        bfjumping = false
    end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by ArthurYago** [comment]
lemme fix some things

function onCreate()
    makeAnimatedLuaSprite('firebflegs', 'pcport/bflegs', -42, 90);
    addAnimationByPrefix('firebflegs', 'firebfthing', 'runfire', 24, true);
    addAnimationByPrefix('firebflegs', 'jump', 'jumpfire', 24, true);
    objectPlayAnimation('firebflegs', 'firebfthing', false);
    setScrollFactor('firebflegs', 1, 1);
    scaleObject('firebflegs', 10, 10);
    setProperty('firebflegs.antialiasing', false)
end

local bfjumping = false

function onTimerCompleted(tag, loops, loopsLeft)
    if tag == 'jumpstairs1' then
        doTweenY('bfmoveY', 'boyfriend', -216, 0.5, 'sineOut');
        doTweenY('bffirelegsmoveY', 'firebflegs', -476, 0.5, 'sineOut');
        runTimer('jumpstairs1-2', 0.5, 1);
        bfjumping = true
    end

    if tag == 'jumpstairs1-2' then
        doTweenY('bfmoveY', 'boyfriend', 350, 0.5, 'sineIn');
        doTweenY('bffirelegsmoveY', 'firebflegs', 90, 0.5, 'sineIn');
        runTimer('jumpstairsend', 0.5, 1)
    end

    if tag == 'jumpstairsend' then
        bfjumping = false
    end
end

function onUpdate()
    if bfjumping == true then
        objectPlayAnimation('firebflegs', 'jump',false)
    elseif bfjumping == false then
        objectPlayAnimation('firebflegs', 'firebfthing', false)
    end
end

and, did you used runTimer()?

**Comment by NesDoesGithub** [comment]
> lemme fix some things
> 
> function onCreate() makeAnimatedLuaSprite('firebflegs', 'pcport/bflegs', -42, 90); addAnimationByPrefix('firebflegs', 'firebfthing', 'runfire', 24, true); addAnimationByPrefix('firebflegs', 'jump', 'jumpfire', 24, true); objectPlayAnimation('firebflegs', 'firebfthing', false); setScrollFactor('firebflegs', 1, 1); scaleObject('firebflegs', 10, 10); setProperty('firebflegs.antialiasing', false) end
> 
> local bfjumping = false
> 
> function onTimerCompleted(tag, loops, loopsLeft) if tag == 'jumpstairs1' then doTweenY('bfmoveY', 'boyfriend', -216, 0.5, 'sineOut'); doTweenY('bffirelegsmoveY', 'firebflegs', -476, 0.5, 'sineOut'); runTimer('jumpstairs1-2', 0.5, 1); bfjumping = true end
> 
> ```
> if tag == 'jumpstairs1-2' then
>     doTweenY('bfmoveY', 'boyfriend', 350, 0.5, 'sineIn');
>     doTweenY('bffirelegsmoveY', 'firebflegs', 90, 0.5, 'sineIn');
>     runTimer('jumpstairsend', 0.5, 1)
> end
> 
> if tag == 'jumpstairsend' then
>     bfjumping = false
> end
> ```
> 
> end
> 
> function onUpdate() if bfjumping == true then objectPlayAnimation('firebflegs', 'jump',false) elseif bfjumping == false then objectPlayAnimation('firebflegs', 'firebfthing', false) end end
> 
> and, did you used runTimer()?

yes i did, i don't see any difference in your code compared to mine
