### ISSUE TITLE
source file open using modded haxe i guess

### ISSUE THREAD

**Issue by jimmyjamescool** [ShadowMario/FNF-PsychEngine#8673]
### What feature do you want to get added on the **base** engine?

you probably arent gonna do this but how about the source file in the directory. so you can edit the source without compiling or debug (probably cant work but who cares *also shut the fuck up winzip im not paying 10% of my life savings*)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by frantastic24** [comment]
that's not how source works wtf

**Comment by Mastercopper2346** [comment]
thx @ShadowMario
