### ISSUE TITLE
Achievement keeps playing for no reason

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8674]
### Describe your bug here.

https://user-images.githubusercontent.com/101440491/168693820-acde69b7-bc0b-41e8-a483-a63105c7455a.mp4

This weird error keeps happening and it's annoying. I just beat week1 of my new engine, (with no misses), and this happened.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't touch anything with achievements.

**Comment by machonessiebaby** [comment]
weird bug try redownloading engine week 7 Achievement is coded in just wont play unless some bug happens

**Comment by Mastercopper2346** [comment]
it's fresh, though.

**Comment by CrusherMods** [comment]
> it's fresh, though.

he didnt even say you were on another song

**Comment by ShadowMario** [comment]
Your engine.
