### ISSUE TITLE
What should i do?

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8675]
### Describe your problem here.

Should i use a dodge `note` or a dodge `function`?
I need help.

Before you say "nOt A rEaL iSsUe" please just help, don't be useless.

And i WILL close this in about 3 days

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

what

**Comment by Lorekeeper49** [comment]
Dodge notes are easier to code so do that

**Comment by Mastercopper2346** [comment]
i have both of them.

**Comment by Mastercopper2346** [comment]
but, a script i have is preventing me from doing that.

**Comment by Mastercopper2346** [comment]
so, `function` it is!

**Comment by Mastercopper2346** [comment]
wait.

**Comment by Mastercopper2346** [comment]
know what nvm
