### ISSUE TITLE
Switch character not switching the character i want it to switch

### ISSUE THREAD

**Issue by ColdlordXRepositories** [ShadowMario/FNF-PsychEngine#8677]
### Describe your bug here.

https://user-images.githubusercontent.com/49921877/168704670-262aa546-e112-49c2-a84c-a545a528f840.mp4

I want to switch the opponent, but it switches bf instead

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added 3 characters and 4 songs plus a custom event, but nothing with the change character event

**Comment by frantastic24** [comment]
Value 1 is incorrect

**Comment by Lorekeeper49** [comment]
Set value 1 to 'dad' (no quotes)

**Comment by ColdlordXRepositories** [comment]
> Set value 1 to 'dad' (no quotes)

i did that

**Comment by ColdlordXRepositories** [comment]
got it. i put a capital D in dad

**Comment by SnakDev** [comment]
all of it has to be uppercase
