### ISSUE TITLE
How I can change color of the Song Time Bar - Puntuation (Event)

### ISSUE THREAD

**Issue by Enmadaio999** [ShadowMario/FNF-PsychEngine#8678]
### Describe your problem here.

Title says all of that
pls don't say: just put a lua file and txt file, then put the lua stuff
:(

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
`setProperty('timeBar.color', hex color)`

**Comment by Rajbir98** [comment]
this issue should be closed

**Comment by NightmaresPlayz** [comment]
Wait, this is in script
