### ISSUE TITLE
dumbass compiling issue

### ISSUE THREAD

**Issue by silvashp** [ShadowMario/FNF-PsychEngine#8680]
### Describe your bug here.

grrrrr ime so angry:
PS C:\Users\Janek\Desktop\moron> lime build windows
source/Achievements.hx:157: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/MainMenuState.hx:66: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:320: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/CharacterEditorState.hx:94: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/DialogueCharacterEditorState.hx:87: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
D:/haxe axe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:145: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/haxe axe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:180: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/haxe axe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:221: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/haxe axe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:515: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/haxe axe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:483: characters 37-56 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/haxe axe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:484: characters 31-47 : Warning : Std.is is deprecated. Use Std.isOfType instead.
D:/haxe axe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:646: characters 10-42 : Warning : Std.is is deprecated. Use Std.isOfType instead.
source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\Janek\Desktop\moron\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Missing visual studio components

**Comment by frantastic24** [comment]
If the error is there then you're missing something idk what else to tell you

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943455-cf2b94d6-1039-486c-a5c0-b73e0659ab86.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943486-6533b816-e04f-49b7-a4d4-b0d8285deac6.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943503-e003dfad-c278-4f9e-bc3c-494b420b3ba1.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943517-8d92212f-7810-45e9-a758-48ff52f7e1da.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943543-83a6b6f1-02ec-4399-9ce7-dc1797e5e17e.gif)

**Comment by jimmyjamescool** [comment]
![Uploading the rainboe stick.gif…]()

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943572-acb5d753-0626-4fb4-ac35-84063b148b3d.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943602-eb1c8b41-f861-4b08-9cea-f0330056a1cf.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943620-013b6845-19e7-4e61-908c-b553b0064330.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943656-a4fe7f5e-9e8a-460a-bf69-db7bb28932d5.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943674-5629a56c-319d-4e77-a6b2-877b8ca7f737.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943706-0caccb83-a1a9-4053-8a54-33825fc6bd98.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943725-3a9a71bc-4a67-467a-81b1-bd6397b62020.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943737-5c8d0740-5a3c-438d-ad64-6985f9ca13b5.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943746-60d6a079-964f-410a-b18c-bde45616b292.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943752-ead6654a-8f5b-4ee1-9970-2e6681eb6d25.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943781-a2a8c637-f31e-4167-8f5a-6f26773301a4.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943793-a1ef5777-d452-42e2-bacf-3e5fc5dd66fa.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943807-f368c4b6-e636-4fa3-a207-fe627c798f0c.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943819-2131c48f-0bc5-4740-b559-45f8d387ac49.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943838-de70a9f9-d6da-46a1-8c1c-a29c87e3e035.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943852-7dda2fb3-5c2c-4235-89cf-dfce53851f41.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943858-594a54e0-92b1-4117-a44c-c0b47a2286ec.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943876-d7e4079b-51dd-4aa5-8fb0-53de10a03c8d.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943906-b77213b0-ecf3-4060-92ad-4bde53101af5.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943918-6d2865b2-2597-4587-92fc-2941c3e8f7c6.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943931-e56717d3-bd1d-475d-9815-824b11d1cfb3.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943939-daa14fcf-982b-40b1-adbf-c38cca8b6665.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943952-d3ef29ba-a7d2-438c-ba33-579e7a2340e0.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943963-fb2a6ccd-6dff-4c01-acb1-27a13e6d09b8.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943971-6f1c0103-2e3e-4b40-9c21-786583e73283.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943979-b24a6edd-434a-45d2-ab4f-098acf307481.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168943996-204c7ee1-b8ba-4f9f-aed6-e7c7a6e6e15d.gif)

**Comment by jimmyjamescool** [comment]
![the rainboe stick](https://user-images.githubusercontent.com/98002066/168944309-6b6a2e0a-34af-4023-ac42-2b626fbace37.gif)

**Comment by silvashp** [comment]
fuck you jim

**Comment by jimmyjamescool** [comment]
> fuck you jim

no
