### ISSUE TITLE
Add Animation Stop for character

### ISSUE THREAD

**Issue by fistiG** [ShadowMario/FNF-PsychEngine#8681]
### What feature do you want to get added on the **base** engine?

I want to add the ability to stop the animation of the character.

It's all lol

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ArthurYago** [comment]
characterDance(character:String)

this makes your char play idle 
try it

**Comment by fistiG** [comment]
No, I need to stop current animation, like SMB. FUNK MIX - GAME OVER mario transition

**Comment by ShadowMario** [comment]
> No, I need to stop current animation, like SMB. FUNK MIX - GAME OVER mario transition

I have no idea what the hell that means, explain in words

**Comment by PrismLight** [comment]
> > No, I need to stop current animation, like SMB. FUNK MIX - GAME OVER mario transition
> 
> I have no idea what the hell that means, explain in words

Pretty sure he/she means that they want a lua/source script to just stop the animation that the character is playing and have it play it's idle anim.

**Comment by fistiG** [comment]
> > No, I need to stop current animation, like SMB. FUNK MIX - GAME OVER mario transition
> 
> I have no idea what the hell that means, explain in words

Oops, sorry for ignorin' *_*
Like just stop character animation, like
```haxe
boyfriend.animation.curAnim.stop()
```

or smth like that. Again, I sorry for ignorin'

**Comment by ShadowMario** [comment]
`boyfriend.animation.curAnim.stop()` or `boyfriend.animation.curAnim.pause()`????
If you need it on lua you can just `setProperty('boyfriend.animation.curAnim.paused', true)`
