### ISSUE TITLE
How to make the screen shake when the boyfriend(player) sings

### ISSUE THREAD

**Issue by NavaGaming** [ShadowMario/FNF-PsychEngine#8683]
### Describe your problem here.

bruhj help pls

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nah

**Comment by frantastic24** [comment]
```lua
function goodNoteHit()
     cameraShake('camera', intensity, duration)
end
```

**Comment by Lorekeeper49** [comment]
> ```lua
> function goodNoteHit()
>      cameraShake('camera', intensity, duration)
> end
> ```

Hold up, there's a function called 'cameraShake'? I've literally been using `triggerEvent('Camera Shake', intensity, duration);` to work the camera shake on note hit

**Comment by tylerandari12** [comment]
> > ```lua
> > function goodNoteHit()
> >      cameraShake('camera', intensity, duration)
> > end
> > ```
> 
> Hold up, there's a function called 'cameraShake'? I've literally been using `triggerEvent('Camera Shake', intensity, duration);` to work the camera shake on note hit

Lol

Check the wiki as there's more you can do with the cameras...
