### ISSUE TITLE
New Menu Transition

### ISSUE THREAD

**Issue by JVgradiz** [ShadowMario/FNF-PsychEngine#8685]
### Describe your problem here.

I did an new menu "PlayMenuState" and it is working, exept the end of the transition dissapear at the start of the playMenu

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

_No response

### The file of the playmenustate
[PlayMenuState.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8720315/PlayMenuState.zip)
_

**Comment by Stilic** [comment]
we can't help you if you don't provide the source code for these files
