### ISSUE TITLE
Yo i need some help

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#8686]
### Describe your problem here.

I need help adding a custom option that allows me to change the menu music

this is what i have so far
```	var option:Option = new Option('Main Menu Song:',
		"What song do you prefer for the Main Menu?",
		'MainMenuMusic',
		'string',
		'freakymenu',
		['None', 'OldMenu', 'freakymenu']);
	addOption(option);
	option.onChange = onChangeMainMusic;

	var changedDaMusic:Bool = false;
function onChangeMainMusic()
{
	if(ClientPrefs.mainMusic == 'None')
		FlxG.sound.music.volume = 0;
	else
		FlxG.sound.playMusic(Paths.music(Paths.formatToSongPath(ClientPrefs.mainMusic)));

	changedDaMusic = true;
}

override function destroy()
{
	if(changedDaMusic) FlxG.sound.playMusic(Paths.music('freakyMenu'));
	super.destroy();
}
```

Clientprefs.hx code

```
// line 141
	}
		FlxG.save.data.MainMenuMusic = MainMenuMusic;

		if(FlxG.save.data.MainMenuMusic != null) {
		MainMenuMusic= FlxG.save.data.MainMenuMusic;
	}



//line 33
	public static var MainMenuMusic:String = 'freakymenu';
```
 (im using similar code to the pause Screen song) VisualsUISubState.hx

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

sound changes and 2 custom achievements, 4 custom credits playstate.hx titlestate.hx main.hx Everything inside of source\editors options

**Comment by machonessiebaby** [comment]
> Okay, so did you edit ClientPrefs.hx? You need to add your option variables there. Just copy off another option and change it.

this still does not work

**Comment by FunkyPikmin** [comment]
I think I see the problem. This is what the pause song option code should look like:

		var option:Option = new Option('Pause Screen Song:',
			"What song do you prefer for the Pause Screen?",
			'pauseMusic',
			'string',
			'Tea Time',
			['None', 'Breakfast', 'Tea Time']);
		addOption(option);
		option.onChange = onChangePauseMusic;

**Comment by FunkyPikmin** [comment]
Where the first variable is the option name, second is description, third is save data variable, fourth is option type, 5th is default choice and 6th are the choices.

**Comment by machonessiebaby** [comment]
> Where the first variable is the option name, second is description, third is save data variable, fourth is option type, 5th is default choice and 6th are the choices.

@FunkyPikmin what would i do in client prefs?

**Comment by FunkyPikmin** [comment]
> > Where the first variable is the option name, second is description, third is save data variable, fourth is option type, 5th is default choice and 6th are the choices.
> 
> @FunkyPikmin what would i do in client prefs? i dont really understand sorry

No need to apologise. Just copy the code of another option and paste it next to it. You need to do three things:

	public static var (save data variable):String = 'FE2CM';
	
	FlxG.save.data.(save data variable) = (save data variable);
	
			if(FlxG.save.data.(save data variable) != null) {
			(save data variable)= FlxG.save.data.(save data variable);
		}

Replace the (save data variable) with the save data variable from the options. Can you figure out where to paste the three things? Look at the other option code for reference.

**Comment by FunkyPikmin** [comment]
I'm sorry if I suck at explaining.

**Comment by machonessiebaby** [comment]
> > > Where the first variable is the option name, second is description, third is save data variable, fourth is option type, 5th is default choice and 6th are the choices.
> > 
> > 
> > @FunkyPikmin what would i do in client prefs? i dont really understand sorry
> 
> No need to apologise. Just copy the code of another option and paste it next to it. You need to do three things:
> 
> ```
> public static var (save data variable):String = 'FE2CM';
> 
> FlxG.save.data.(save data variable) = (save data variable);
> 
> 		if(FlxG.save.data.(save data variable) != null) {
> 		(save data variable)= FlxG.save.data.(save data variable);
> 	}
> ```
> 
> Replace the (save data variable) with the save data variable from the options. Can you figure out where to paste the three things? Look at the other option code for reference.

is this in client prefs?

**Comment by machonessiebaby** [comment]
got it

> I'm sorry if I suck at explaining.

what do i do for onChangeMainMusic

for option.onChange = onChangeMainMenu

**Comment by FunkyPikmin** [comment]
You'd have to add this:

	var changedDaMusic:Bool = false;
	function onChangeMainMusic()
	{
		if(ClientPrefs.mainMusic == 'None')
			FlxG.sound.music.volume = 0;
		else
			FlxG.sound.playMusic(Paths.music(Paths.formatToSongPath(ClientPrefs.mainMusic)));

		changedDaMusic = true;
	}

	override function destroy()
	{
		if(changedDaMusic) FlxG.sound.playMusic(Paths.music('freakyMenu'));
		super.destroy();
	}

**Comment by FunkyPikmin** [comment]
is 'mainMusic' the save data variable in ClientPrefs.hx?

**Comment by machonessiebaby** [comment]
> is 'mainMusic' the save data variable in ClientPrefs.hx?

no i bbelive not ill check

**Comment by machonessiebaby** [comment]
> is 'mainMusic' the save data variable in ClientPrefs.hx?

what code would i use for mainusic? i looked in client prefs and saw nothing similar to how pause works

**Comment by machonessiebaby** [comment]
> is 'mainMusic' the save data variable in ClientPrefs.hx?

@FunkyPikmin 

![image](https://user-images.githubusercontent.com/56323671/169660276-b83aede6-19b2-42a1-9fd4-ff53a9acd04a.png)

**Comment by FunkyPikmin** [comment]
I'm sorry, but I'm not sure how to add this specific option. I'm very busy, though, so, I'm very sorry if my advice sucked @$$. Maybe wait for someone else to help. Sorry.

**Comment by machonessiebaby** [comment]
its ok
