### ISSUE TITLE
Source Code Compiling Error

### ISSUE THREAD

**Issue by T-Github2** [ShadowMario/FNF-PsychEngine#8687]
### Describe your problem here.

When running the `lime test windows` command, it stops after saying "Stdlib.Sys.Break" Any idea what this could mean or how I could go about fixing it? 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by HiroMizuki** [comment]
i've never seen something like that, but this line appears for me when i cancel the compilation with Ctrl+C in the prompt
