### ISSUE TITLE
Dialogue before cutscene

### ISSUE THREAD

**Issue by Xeno4K** [ShadowMario/FNF-PsychEngine#8688]
### Describe your problem here.

I haven't found any posts about this so I hope this isnt a dupe but, is there a way to have a dialogue BEFORE a cutscene? basically...
dialogue>cutscene>song
 
and if possible, can you do
dialogue>cutscene>dialogue>song 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JVgradiz** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/748
