### ISSUE TITLE
shadow mario please release my family

### ISSUE THREAD

**Issue by jimmyjamescool** [ShadowMario/FNF-PsychEngine#8690]
### What is your question?

its been 5 years since ive seen them, let them go and get me out of this empty storage room with a computer. 
oh god the maggots and dust are building up help me now.

**Comment by jimmyjamescool** [comment]
THEY CRAWLED INTO MY STOMACH DEAR GOD SHADOW GET ME OUT NOOOOOOOOOWWWWWWW

**Comment by Lorekeeper49** [comment]
any way we can help?!

**Comment by jimmyjamescool** [comment]
no. im trying to scratch on the door, didnt work.

**Comment by BorisC04** [comment]
Who trapped you, shadow from sonic the hedgehog?

**Comment by BorisC04** [comment]
btw you can call the damn cops if you can access internet

**Comment by Stilic** [comment]
@ShadowMario help this issue is trash and is a pure joke
@jimmyjamescool shut up and go outside, you need to fix your small brain

**Comment by HiroMizuki** [comment]
what the fuck 💀

**Comment by jimmyjamescool** [comment]
> Who trapped you, shadow from sonic the hedgehog?

no shadow mario the developur mane

**Comment by jimmyjamescool** [comment]
> @ShadowMario help this issue is trash and is a pure joke @jimmyjamescool shut up and go outside, you need to fix your small brain

nice self roast ya got there
![the rainboe stick](https://user-images.githubusercontent.com/98002066/169143938-cc3851ce-cae3-4eb7-984e-1a1c9509db5b.gif)

**Comment by Stilic** [comment]
> > @ShadowMario help this issue is trash and is a pure joke @jimmyjamescool shut up and go outside, you need to fix your small brain
> 
> you get banned if you ping shadow a bit

grrrrr shut up and close this

**Comment by BorisC04** [comment]
> > Who trapped you, shadow from sonic the hedgehog?
> 
> no shadow mario the developur mane

oh my god shadow mario from super mario sunshine
![download](https://user-images.githubusercontent.com/103830375/169309456-d6a917c2-9c86-46cb-a59d-b289d74c0efa.jpg)

**Comment by tylerandari12** [comment]
Should've had the help wanted label...

**Comment by ShadowMario** [comment]
I won't release them.
