### ISSUE TITLE
missing documentation #1

### ISSUE THREAD

**Issue by jimmyjamescool** [ShadowMario/FNF-PsychEngine#8691]
### What needs to be documented?

not sure about if you documented this but if not u forgor to document *modcharts*

EXAMPLE: (the cheating modchart i yoinked)

function onStartCountdown()
defaultDadY = getCharacterY('dad')
end

function onUpdate(elapsed)
setPropertyFromClass('ClientPrefs', 'middleScroll', false)
if middleScroll == true then
endSong()
end
songPos = getSongPosition()
		local currentBeat = (songPos/5000)*(curBpm/60)

		noteTweenX(defaultPlayerStrumX0, 4, defaultPlayerStrumX0 - 50*math.sin((currentBeat+4*0.25)*math.pi), 0.5)
		noteTweenX(defaultPlayerStrumX1, 5, defaultPlayerStrumX1 - 350 + 2000*math.sin((currentBeat+8*0.25)*math.pi), 3)
		noteTweenX(defaultPlayerStrumX2, 6, defaultPlayerStrumX2 - 50*math.sin((currentBeat+4*0.25)*math.pi), 0.5)
		noteTweenX(defaultPlayerStrumX3, 7, defaultPlayerStrumX3 - 350 + 2000*math.sin((currentBeat+8*0.25)*math.pi), 3)

		noteTweenX(defaultOpponentStrumX0, 0, defaultOpponentStrumX0 + 50*math.sin((currentBeat+4*0.25)*math.pi), 0.5)
		noteTweenX(defaultOpponentStrumX1, 1, defaultOpponentStrumX1 + 350 - 2000*math.sin((currentBeat+8*0.25)*math.pi), 3)
		noteTweenX(defaultOpponentStrumX2, 2, defaultOpponentStrumX2 + 50*math.sin((currentBeat+4*0.25)*math.pi), 0.5)
		noteTweenX(defaultOpponentStrumX3, 3, defaultOpponentStrumX3 + 350 - 2000*math.sin((currentBeat+8*0.25)*math.pi), 3)
setCharacterY('dad', getCharacterY('dad') + (math.sin(currentBeat) * 0.6))
function onMoveCamera(focus)
	if focus == 'boyfriend' then
		-- called when the camera focus on boyfriend
	elseif focus == 'dad' then
		setProperty('camFollowPos.y',getProperty('camFollowPos.y') + (math.sin(currentBeat) * 0.6))
	end
end
function opponentNoteHit(id, direction, noteType, isSustainNote)
setProperty('health', getProperty('health') - 1 * ((getProperty('health')/22))/3)
end
function noteMissPress(direction)
setProperty('health', getProperty('health') + 0.023)
end
end

**Comment by jimmyjamescool** [comment]
btw the worms are in my brain

**Comment by frantastic24** [comment]
The engine doesn't need to document a common mechanic in rhythm games and for the love of god learn how to fucking format code

**Comment by Stilic** [comment]
shut up this is documented
or if not exit this place, get logic in your stupid brain and look at the source code
you will understand better

**Comment by Mastercopper2346** [comment]
modchart? if you think about it, the whole wiki is a modchart, just separate.

**Comment by silvashp** [comment]
what an idiot

**Comment by CrusherMods** [comment]
> what an idiot

fr
