### ISSUE TITLE
I guess I need some help with editing the title screen or photoshopping

### ISSUE THREAD

**Issue by Aden-Mystio** [ShadowMario/FNF-PsychEngine#8692]
### Describe your problem here.

I wanted to make this the title screen for my mod
![Untitled48_20220513213654](https://user-images.githubusercontent.com/104238200/168948698-20c7a161-bba9-4445-93dd-cb9288ac27d4.png)
But unfortunately my editing skills are trash
If you can help me thanks 
Here's this if you need it 
![Untitled48_20220517220254](https://user-images.githubusercontent.com/104238200/168948761-60025ff5-8319-4f42-aa84-13971ca68330.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

E

**Comment by Stilic** [comment]
no
