### ISSUE TITLE
Rating Camera Options

### ISSUE THREAD

**Issue by PainChungles** [ShadowMario/FNF-PsychEngine#8694]
### What feature do you want to get added on the **base** engine?

I'd like the option to be able to choose whether the rating and number score is on drawn on camHUD or on camGame either through options or Lua
P.S I've tried changing it through Lua but it didn't work, I don't know if I did it wrong or something but I don't think I did

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by XperiorTR** [comment]
Here, you can do this with Lua.
`setObjectCamera('scoreTxt', 'game')` 
![image](https://user-images.githubusercontent.com/80666310/169104141-492b598c-5e1d-4253-9803-91f5825088e6.png)
