### ISSUE TITLE
I can't figure out how to play sound effects with the dialogues.

### ISSUE THREAD

**Issue by AnthonyYTB** [ShadowMario/FNF-PsychEngine#8697]
### Describe your problem here.

I'm trying to put sound effects with the dialogues but i'm not sure where i'm suppose to put the .ogg files, can someone tell me pls?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, the files in the mod folder.

**Comment by Lorekeeper49** [comment]
mods/sounds

**Comment by AnthonyYTB** [comment]
> mods/sounds

Alright thanks
