### ISSUE TITLE
Editable Lua functions

### ISSUE THREAD

**Issue by Lorekeeper49** [ShadowMario/FNF-PsychEngine#8698]
### What is your question?

Can someone give me a list of editable Lua functions (include parameters if that function has any) so that I know what to use for each scenario?

**Comment by Lorekeeper49** [comment]
Here are the ones I know right now
```lua
onUpdate(e)
onStepHit()
onBeatHit()
onCreate()
onCreatePost()
onEvent(n, v1, v2)
goodNoteHit(i, d, t, l)
opponentNoteHit(i, d, t, l)
onTweenCompleted(t)
onTimerCompleted(t, l, ll)
onStartCountdown()
onCountdownTick(c)
```
Let me know if any others

**Comment by tylerandari12** [comment]
> Here are the ones I know right now
> ```lua
> onUpdate(e)
> onStepHit()
> onBeatHit()
> onCreate()
> onCreatePost()
> onEvent(n, v1, v2)
> goodNoteHit(i, d, t, l)
> opponentNoteHit(i, d, t, l)
> onTweenCompleted(t)
> onTimerCompleted(t, l, ll)
> onStartCountdown()
> onCountdownTick(c)
> onEndSong()
> ```
> Let me know if any others

onUpdatePost()
onCheckForAcievement() - might now work

**Comment by frantastic24** [comment]
The wiki has a list with most of them, the rest you can easily find inside source files

**Comment by AntiPlayzz** [comment]
you can find them [here](https://raw.githubusercontent.com/ShadowMario/FNF-PsychEngine/main/docs/TemplateScript.lua)
