### ISSUE TITLE
I want to do a "ScaleTweenX" but hands me over an error

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#8703]
### Describe your problem here.

I used the example in the wiki page so why isn't working?

here's the code:
doTweenX('scaleTweenX', 'boyfriend.scale', -1, 0.01, 'linear');
doTweenY('scaleTweenY', 'boyfriend.scale', 0, 0.01, 'linear');

It's to flip the player but when I play the song with the script in it, the error says: 
"script.lua:2: attempt to call global 'doTweenX' (a nil value)"

I'm using **v0.5.2h** btw
![FNF_Scale-errorBlur](https://user-images.githubusercontent.com/105890618/169413118-624ac1e0-17e3-4284-9687-6380d6e67b69.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just modded in the "example_mods" folder

**Comment by frantastic24** [comment]
looks like you put this without a function
you should show your full script next time

**Comment by TFLTV** [comment]
> looks like you put this without a function you should show your full script next time

I deleted "doTweenX" and didn't work
also tried deleting "scaleTweenX" neither did it work 
(and, I might be dumb but, idk what a function is (well in this case) so I just deleted the ones I **thought** were functions
kinda noob at coding lol)

**Comment by frantastic24** [comment]
actually idk why you're even using tweens for this, there are basic properties to flip sprites
```lua
function onCreatePost() --this is what you were missing
     setProperty('boyfriend.flipX', true)
     setProperty('boyfriend.flipY', true)
end
```
and instead of doing a tween to set a property just do this and leave tweens for smooth effects
`setProperty('boyfriend.scale.y', 0)` or `scaleObject('boyfriend', xScale, yScale)`
