### ISSUE TITLE
Can't use scale tweens

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#8706]
### Describe your problem here.

I can't use scale tweens just gives an error
but idk if I can't use tweens at all, I just know scale tweens don't work.

i'm using version **v0.5.2h**

the code:
doTweenX('scaleTweenX', 'boyfriend.scale', 1.5, 0.01, 'linear');
doTweenY('scaleTweenY', 'boyfriend.scale', 1.5, 0.01, 'linear');
[eof]

(btw, that code was from the github wiki page why is it not working??)
error:
![FNF_Scale-errorBlur](https://user-images.githubusercontent.com/105890618/169426400-f6d81df6-0937-4042-a79b-8531009f5f7d.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just modded in the "example_mods" folder

**Comment by frantastic24** [comment]
Why did you open the exact same issue again

**Comment by TFLTV** [comment]
> Why did you open the exact same issue again
I was hoping someone would ask me this so I can explain.
your last answer didn't work but, found out another way. 
but I still wanted to see if I _could_ try to find out how to use scale tweens
to use them in the future y'know. I'd rather just find it now. there's no point in _NOT_ finding it out when I **can**.
**_I'd just get it out of the way_**.

**Comment by frantastic24** [comment]
I explained in the last issue you were missing a function, and you never even showed your script
Read the wiki, it has example scripts

**Comment by TFLTV** [comment]
> I explained in the last issue you were missing a function, and you never even showed your script Read the wiki, it has example scripts

let me check, I thought you said "get rid of a function" thanks to my brain.

**Comment by TFLTV** [comment]
> I explained in the last issue you were missing a function, and you never even showed your script Read the wiki, it has example scripts

@frantastic24 
still didn't work when I put the ScaleScript from the wiki in my song
(boyfreind is supposed to get bigger when the camrea is focusing at him)

**Comment by Mastercopper2346** [comment]
show the full script

**Comment by frantastic24** [comment]
Don't just say it doesn't work without showing your code

**Comment by tylerandari12** [comment]
Put your tween under onCreate().

**Comment by tylerandari12** [comment]
Psyche exclusive functions will not work unless they're under a psyche function.

**Comment by TFLTV** [comment]
> Psyche exclusive events will not work unless they're under a psyche function.

sorry everybody I was so funkin stupid I found the tween and timer on the wiki I was missing

	onTweenCompleted('bfScaleTweenX')

yeah, i'm stupid. I can agree on that

**Comment by frantastic24** [comment]
I don't know how that fixed anything because that's not how the function works but okay

**Comment by TFLTV** [comment]
> I don't know how that fixed anything because that's not how the function works but okay

idk just worked lol
