### ISSUE TITLE
I can't play videos in source.

### ISSUE THREAD

**Issue by Itz-Miles** [ShadowMario/FNF-PsychEngine#8707]
### Describe your bug here.

I was testing some of the VLCbitmap code by playing a video in source: `new FlxVideo('assets/videos/test');`, but nothing seems to get it to work. Is the directory the game set causing an issue? I have my video in `export/release/windows/bin/assets/videos`

### Command Prompt/Terminal logs (if existing)

```bash
settin' path: file:///C:\Users\demdi\FNF-Itz Funkin Minecraft\FNF- ItzFunkinMinecraft\export\release\windows\bin//assets/videos/test
source/vlc/VlcBitmap.hx:502: VLC ERROR - File not found?
source/FlxVideo.hx:126: An error has occured while trying to load the video.
Please, check if the file you're loading exists.
```
```


### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes. I have a custom 0.5.1 build, no changes have been made to any of the video handler code though.

**Comment by Itz-Miles** [comment]
is it happening because of this function in FlxVideo.hx?
```
	function checkFile(fileName:String):String
	{
		var pDir = "";
		var appDir = "file:///" + Sys.getCwd() + "/";

		if (fileName.indexOf(":") == -1) // Not a path
			pDir = appDir;
		else if (fileName.indexOf("file://") == -1 || fileName.indexOf("http") == -1) // C:, D: etc? ..missing "file:///" ?
			pDir = "file:///";

		return pDir + fileName;
	}
```

**Comment by frantastic24** [comment]
did you try adding the file extension to the path

**Comment by Itz-Miles** [comment]
Thanks, adding the file extension name worked! I was trying to follow the callback code for the [Lua function](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Functions-for-Dialogues-and-Cutscenes#startvideovideofilestring), so I left the extension name off thinking the same file system would find it.
