### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by Aden-Mystio** [ShadowMario/FNF-PsychEngine#8708]
### What is your question?

Does anyone know what font the "Sick" "Good" "Bad" and "Shit" font is? I would like to do this 
![Untitled53_20220519224410](https://user-images.githubusercontent.com/104238200/169448832-d0bb93fb-1df2-4821-bb14-99fdaf321961.png)
in that style

**Comment by frantastic24** [comment]
It's not a font, it's hand drawn

**Comment by Aden-Mystio** [comment]
That makes more sense in hindsight
