### ISSUE TITLE
how do i add a warning screen on main menu like vs tinky winky?????

### ISSUE THREAD

**Issue by JacksRobotics** [ShadowMario/FNF-PsychEngine#8709]
### What is your question?

how??????

**Comment by Itz-NOT-Miles** [comment]
what's VS. tinky winky? I doubt Shadow Mario has played that, let alone anyone else I know. Warning screens are already in base psych engine, in what state do you want it? (MainMenuState, PlayState, e.t.c)

**Comment by JacksRobotics** [comment]
> what's VS. tinky winky? I doubt Shadow Mario has played that, let alone anyone else I know. Warning screens are already in base psych engine, in what state do you want it? (MainMenuState, PlayState, e.t.c)

the vs tinky winky mod made by bonespook https://gamebanana.com/mods/309180
the mod uses kade. i want to know how to add the loading screen to psych engine..

**Comment by Itz-NOT-Miles** [comment]
Simple. before compiling, locate Project.xml, and delete this on line 65: `<define name="PRELOAD_ALL" unless="web" />`.
When deleting this line, the game will compile without "preloading" defined; it will use loadingState.hx that's usually specific to web.

**Comment by JacksRobotics** [comment]
> Simple. before compiling, locate Project.xml, and delete this on line 65: `<define name="PRELOAD_ALL" unless="web" />`. When deleting this line, the game will compile without "preloading" defined; it will use loadingState.hx that's usually specific to web.

will it show the warning screen image i made?

**Comment by Itz-Miles** [comment]
I was on campus for a bit. You either have to replace funkay.png with your image of choice, or change what filename it should look for.
