### ISSUE TITLE
Ghost notes when charting

### ISSUE THREAD

**Issue by Maselek01** [ShadowMario/FNF-PsychEngine#871]
### Describe your bug here.

Occasional notes appearing in gameplay but not in the chart editor.
Note: I'm not making a build, why do you HAVE to choose something for that option, I'm just making a chart

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't.

**Comment by SrtHero278** [comment]
If you're making a custom build with modified source code, that's making a build with source. If you're just making a mod you can just drag and drop into the mods folder, that's making a build with lua.

**Comment by TBiscuit1** [comment]
Also, if you are making a chart, there is a bug that occasionally happen, a note can get heavly offset and it will look like the note is perfectly placed but in reality it's like 2-3 section after or before it... weird bug, check every note and if a note doesn't turn transparent when you go over it in the chart editor (or is tranparent by default) you caught the glitched note!

**Comment by ShadowMario** [comment]
For me it sounds like that issue from copy and paste sections from 0.4.1, if that's the case it has been patched and you're playing on an outdated build

**Comment by ShadowMario** [comment]
No reply, bruh.
