### ISSUE TITLE
Cam follows position on objects or whatever just help me

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#8710]
### Describe your problem here.

So in short words, I have this bug here with the moving camera when the characters start singing, by some reason, the camera doesn't move when my secondary character sings. The game takes my secondary character as an object so, is there a way to make that, if an object starts singing, the camera moves too?

Another idea is to modify the script to make that, anything that touches the note, it makes the camera move by the note position (left note will make the camera go left, etc.)

I really need help on this 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Lorekeeper49** [comment]
Use the `Camera Follow Pos` event and coordinate it so that the secondary character is in the middle
Note: the x and y pos for the secondary character may not be the same as the camera x and y

**Comment by WilliamGaming12** [comment]
> 

What'd u mean with tht? Like i did it and it doesn't work
Maybe i don't know how to use the script lol

**Comment by Lorekeeper49** [comment]
> > 
> 
> What'd u mean with tht? Like i did it and it doesn't work
> Maybe i don't know how to use the script lol

Place the event where the second character starts singing and it will work, I'd give you an example but I'm not at my computer right now, I will record one when I am though so that you'll understand

**Comment by Lorekeeper49** [comment]
[example](https://drive.google.com/file/d/1PFNonsjQutCUvDEPJaQS0tMquNeXhjxB/view?usp=sharing)
