### ISSUE TITLE
Extension of trophies to the Gamejolt API.

### ISSUE THREAD

**Issue by SirScrubBunsDEV** [ShadowMario/FNF-PsychEngine#8712]
### What feature do you want to get added on the **base** engine?

There are several existing integrations that allow you to hook up trophies to Gamejolt, but only one works with Psych and it's laggy to oblivion.

Being able to hook Psych to the Gamejolt API easily would open the door for so many great things!

1: People could make XP based unlockables,

2: Mods could have score leaderboards

And a lot more (I'm just too lazy to keep listing)

At the very least, you could make modifications to an existing integration or pull someone in to help you out.

Either way, this is a feature I have sought out for for a **LONG** time

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tylerandari12** [comment]
Noice...

**Comment by Stilic** [comment]
no

**Comment by tylerandari12** [comment]
> no

Why not?

**Comment by Stilic** [comment]
> > no
> 
> Why not?

because psych is not on gamejolt
now close this issue please

**Comment by ShadowMario** [comment]
I've had enough of Gamejolt users fucking me up, so no.
