### ISSUE TITLE
Can I make a Cuphead like death screen?

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#8713]
### What is your question?

I want it like this:
https://user-images.githubusercontent.com/105890618/169623713-f9192d0a-0d7a-464a-8bab-80625709362c.mp4

(Without the BF ghost and "YOU DIED" text just the death card)
so like, can I make it, so the screen won't go black (just a little dark tho) and show the death card on screen like that?
also, one more, without the running BF on the card.

edit: Can I do this with only .lua code btw?

**Comment by machonessiebaby** [comment]
this is more help wanted category and also not possible in lua at least i know cuz you have to change the bf death and add the ability to scroll and add a amain menu and retry

**Comment by TFLTV** [comment]
> this is more help wanted category and also not possible in lua at least i know cuz you have to change the bf death and add the ability to scroll and add a amain menu and retry

worth a shot. maybe I can make a mp4 play when you die?
with this code:

function onGameOver()
	startVideo('video-name-here');
	return Function_Continue;
end

**Comment by frantastic24** [comment]
> not possible in lua

It's possible if you know how to use Lua

**Comment by ShadowMario** [comment]
![fucktard](https://user-images.githubusercontent.com/44785097/170141502-aacd8edc-7876-4ee7-8045-776bab73a387.png)

**Comment by TFLTV** [comment]
> ![fucktard](https://user-images.githubusercontent.com/44785097/170141502-aacd8edc-7876-4ee7-8045-776bab73a387.png)

1. Vs Cuphead is not a mod but is in fact a whole other game
2. that's indie cross

**Comment by frantastic24** [comment]
Which is literally an fnf mod
What the fuck are you talking about
