### ISSUE TITLE
BG Fade to White then back?

### ISSUE THREAD

**Issue by roaring213** [ShadowMario/FNF-PsychEngine#8714]
### Describe your problem here.

It's basically like Final Stretch. here, a video to explain:

https://user-images.githubusercontent.com/80852158/169627333-3546dada-d5cf-4dc0-bc04-85dfa31bbcc0.mp4
Here is the script I used for the event (in case you think i should edit anything):
```
function onEvent(name)
    if name == 'White BG & Black Characters' then
        doTweenColor('BFthing', 'boyfriend', '000000', 0.5, 'linear');
        doTweenColor('sansthing', 'dad', '000000', 0.5, 'linear');
    end
end
```
and for the stage (in case i need to do anything with it. also, i don't think .brightness is a thing. i'm an idiot.)
```
function onCreate()
	-- background shit
	makeLuaSprite('hall', 'hall', -200, -100);
	setLuaSpriteScrollFactor('hall', 0.9, 0.9);
	scaleObject('hall', 1.5, 1.5);

	-- sprites that only load if Low Quality is turned off
	if not lowQuality then
	end

	addLuaSprite('hall', false);
	
	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end

function onEvent(name)
	if name == 'White BG & Black Characters' then
		setProperty('hall.brightness', 100);
	end
	if name == 'White BG & Black Characters End' then
		setProperty('hall.brightness', 0);
	end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Almost everything in the Indie Cross Sans week. Just need Burning in Hell & Bad Time.

**Comment by TFLTV** [comment]
I'm not very good, but try changing the color of the background (fetching everything in the bg and changing the color of it
on a certain curstep (you can still use "curstep" in bg code)) kinda' new at github too just signed up

**Comment by roaring213** [comment]
> I'm not very good, but try changing the color of the background (fetching everything in the bg and changing the color of it on a certain curstep (you can still use "curstep" in bg code)) kinda' new at github too just signed up

Can you make an example for me to replicate off of and put in my game?

**Comment by frantastic24** [comment]
make an invisible white graphic, overlay it over your background, tween alpha
