### ISSUE TITLE
Bug in Psyche Engine

### ISSUE THREAD

**Issue by Talesant** [ShadowMario/FNF-PsychEngine#8715]
### Describe your bug here.

When I used "lime test windows" it showed split in the source, but I don't know where it came from.

### Command Prompt/Terminal logs (if existing)

```bash
Called from ? line 1
Called from CommandLineTools.hx line 1895
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 126
Called from CommandLineTools.hx line 641
Called from lime/tools/PlatformTarget.hx line 98
Called from WindowsPlatform.hx line 736
Called from WindowsPlatform.hx line 471
Called from lime/tools/HXProject.hx line 1266
Uncaught exception - Invalid field access : split
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I tried lime test windows and this happened.

**Comment by AllMesi** [comment]
what haxe version are you using?
