### ISSUE TITLE
needed help in psych engine Android port

### ISSUE THREAD

**Issue by bz001** [ShadowMario/FNF-PsychEngine#8717]
### Describe your problem here.

how can i add new keyboards such as space and enter in the Android port without coding.Thanks!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by Randomxdp** [comment]
BRUH DONT PUT THIS ISSUE HERE

**Comment by bz001** [comment]
> 

but where can i ask the question?

**Comment by tylerandari12** [comment]
> > 
> 
> 
> 
> but where can i ask the question?

Pretty sure your fine with this question here.

I don't think he knows what he's talking about lol.

**Comment by ShadowMario** [comment]
This isn't about the android port.
