### ISSUE TITLE
Help coding in a custom main menu music option

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#8718]
### Describe your problem here.

I am trying to add in an option to change the main menu music

VisualUISubState.hx

```	var option:Option = new Option('Main Menu Song:',
		"What song do you prefer for the Main Menu?",
		'MainMenuMusic',
		'string',
		'freakymenu',
		['None', 'OldMenu', 'freakymenu']);
	addOption(option);
	option.onChange = onChangeMainMusic;

	var changedDaMusic:Bool = false;
function onChangeMainMusic()
{
	if(ClientPrefs.mainMusic == 'None')
		FlxG.sound.music.volume = 0;
	else
		FlxG.sound.playMusic(Paths.music(Paths.formatToSongPath(ClientPrefs.mainMusic)));

	changedDaMusic = true;
}

override function destroy()
{
	if(changedDaMusic) FlxG.sound.playMusic(Paths.music('freakyMenu'));
	super.destroy();
}```


Clientprefs.hx


```
//line 33

	public static var MainMenuMusic:String = 'freakymenu';

//line 142

	FlxG.save.data.MainMenuMusic = MainMenuMusic;

		if(FlxG.save.data.MainMenuMusic != null) {
		MainMenuMusic= FlxG.save.data.MainMenuMusic;
	}```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

sound changes and 2 custom achievements, 4 custom credits playstate.hx titlestate.hx main.hx Everything inside of source\editors options

**Comment by Wither362** [comment]
the first letter of vars name shouldt be in upper case letters, they should be in low case
