### ISSUE TITLE
Invalid Char?

### ISSUE THREAD

**Issue by Theemoldy01** [ShadowMario/FNF-PsychEngine#8719]
### Describe your bug here.

I open the mods tab in psych engine and I get greeted with "Invalid char at 41 position 114" what can I do to fix this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I mostly edited fonts, Icon and playstate and don't know whats wrong with it

**Comment by frantastic24** [comment]
not a bug, one of your pack.json is broken

**Comment by Theemoldy01** [comment]
oh okay, well I now i know that is there by any chance a way to fix it? recompile or make a new pack.json?

**Comment by frantastic24** [comment]
fix the json

**Comment by tylerandari12** [comment]
Send the json and I can try to fix it.

**Comment by Theemoldy01** [comment]
Okay! where to do so exactly? On here or with another platform?

**Comment by Lorekeeper49** [comment]
> Okay! where to do so exactly? On here or with another platform?

You can convert it to a txt file and send it here provided it'll be allowed, yesterday I tried to send in a file and it was for some odd reason rejected giving me this message: 'the file is not part of the list'

**Comment by Theemoldy01** [comment]
I'll send a google drive link to it if thats alright

**Comment by Lorekeeper49** [comment]
> I'll send a google drive link to it if thats alright

Yeah, go ahead

**Comment by Theemoldy01** [comment]
https://drive.google.com/drive/folders/1aCaoyiPHh4MHq8-tS_GYc5K-kuhlktks?usp=sharing

**Comment by Theemoldy01** [comment]
heres my google drive link for the pack.json :)

**Comment by Wither362** [comment]
> https://drive.google.com/drive/folders/1aCaoyiPHh4MHq8-tS_GYc5K-kuhlktks?usp=sharing

Can you give access to it? Because for example, ***I*** can *not* enter it

**Comment by Theemoldy01** [comment]
https://drive.google.com/drive/folders/1aCaoyiPHh4MHq8-tS_GYc5K-kuhlktks?usp=sharing

This should work now

**Comment by frantastic24** [comment]
You didn't close the description string

**Comment by Theemoldy01** [comment]
Oh my bad, do you need that to get in?

**Comment by Theemoldy01** [comment]
Also sorry if this is taking awhile i kinda haven't done most of these things for support

**Comment by Theemoldy01** [comment]
https://drive.google.com/drive/folders/1aCaoyiPHh4MHq8-tS_GYc5K-kuhlktks?usp=sharing

**Comment by Theemoldy01** [comment]
hopefully I did this correctly

**Comment by frantastic24** [comment]
No that's what's wrong with your file

**Comment by Wither362** [comment]
Remove (or delete) the code you have and paste this one:
```hello
{
	"name": "Revved Up Funkin!",
	"description": "The Addition to Adrio night funkin (some things may not be canon)”,
	"restart": false,
	"color": [170, 0, 255] 
} 
```

**Comment by Theemoldy01** [comment]
Okay, so do I just copy and paste that in the pack.json since i tried doing that and It still didn't work

**Comment by Wither362** [comment]
WTH, wait, do you have more mods?

**Comment by Theemoldy01** [comment]
I might actually yea, there isn't a json pack for it tho

**Comment by Wither362** [comment]
That’s the problem, do the same what I just told you and change the name and description
