### ISSUE TITLE
7+ minute songs just crash

### ISSUE THREAD

**Issue by carWoah** [ShadowMario/FNF-PsychEngine#872]
### Describe your bug here.

im charting a 12 minute song
it consistently crashes around the 5:30 mark when playtesting.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

ive got custom events n shit but i dont know how those would change anything(theres no custom event placed at the time of the crash.)

**Comment by nicho01022** [comment]
Hm not sure.
Sorry I can't help much

**Comment by GrateSkata** [comment]
i think it's because ur pc stinks and u havent saved the chart

**Comment by GrateSkata** [comment]
also its lua based so use source code for that

**Comment by CrusherMods** [comment]
That might be on you because I made little-man into the engine and I completed it so

**Comment by GrateSkata** [comment]
^^^

**Comment by FuseIsHere813** [comment]
> That might be on you because I made little-man into the engine and I completed it so

This.
