### ISSUE TITLE
Replay System (originally from Kade, then done on Leather)

### ISSUE THREAD

**Issue by Mariogamerexpert** [ShadowMario/FNF-PsychEngine#8720]
### What feature do you want to get added on the **base** engine?

Hey Psych devs! If the replay system hasn't already been added to the engine, I'd recommend doing so. I just got a new record on God Eater from the Shaggy mod (v2.7) that uses 0.3.2 (which, yes, I'm aware is far off from the newest version of Psych). Sadly, there's no replay system so in order to capture my record again I'd have to pull it off on camera. :(

Again, for the next 0.5.x release, could you add the replay system if it's not already in there? If it is, I'm looking forward to it!

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tylerandari12** [comment]
Using save data this might be possible within Lua...

Not sure how tho...

**Comment by ShadowMario** [comment]
No.
