### ISSUE TITLE
GetSongPosition() and GetPropertyClass(?) doesn't work (0.5.2h)

### ISSUE THREAD

**Issue by InfinityNess** [ShadowMario/FNF-PsychEngine#8722]
### Describe your bug here.

So if you try and get song position with _GetSongPosition()_ or  _getPropertyClass('Conductor', 'songPosition')_ will result a error, "mods/data/opposition/script.lua:3: attempt to call global 'GetSongPosition' (a nil value)" and if you use getPropertyClass, its the same error, I might be stupid or it's not just me.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I made a little changes in playstate for when you press 7 in the first song, you get loaded into a another.

**Comment by frantastic24** [comment]
you didn't show your script but my guess is you are calling a function before it's loaded, and `getPropertyFromClass` is misspelled

**Comment by TFLTV** [comment]
`hha`

**Comment by tylerandari12** [comment]
Its `getSongPosition()` and not `GetSongPosition()`

I know I'm annoyed too...

**Comment by tylerandari12** [comment]
Make sure you don`t capitalize the first letter...

**Comment by InfinityNess** [comment]
I didn't, doesn't really matter because I downgraded to psych engine 0.4.2. Tested it and it worked, it was just me being stupid.
