### ISSUE TITLE
Animations in CE

### ISSUE THREAD

**Issue by TurboGames0731** [ShadowMario/FNF-PsychEngine#8728]
### Describe your problem here.

Okay, so I have the .png and .xml files for a character, and when i put the png's name and reload, it says "(animation name) ERROR!". They're all set to "singLEFT" and so on. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, this is a fresh GB build.

**Comment by TurboGames0731** [comment]
edit:
the xml is
`<TextureAtlas imagePath="max.png">
<SubTexture name="max singDOWN0000" x="0" y="0" width="422" height="463" frameX="-124" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max singDOWN0001" x="422" y="0" width="424" height="463" frameX="-124" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max idle0000" x="846" y="0" width="422" height="463" frameX="-124" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max idle0001" x="0" y="463" width="422" height="463" frameX="-124" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max idle0002" x="422" y="463" width="417" height="463" frameX="-124" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max idle0003" x="0" y="463" width="422" height="463" frameX="-124" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max singLEFT0000" x="1268" y="0" width="475" height="463" frameX="-71" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max singLEFT0001" x="1268" y="463" width="475" height="463" frameX="-71" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max singRIGHT0000" x="839" y="463" width="419" height="463" frameX="-127" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max singRIGHT0001" x="0" y="926" width="429" height="463" frameX="-127" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max singUP0000" x="429" y="926" width="460" height="463" frameX="-124" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max singUP0001" x="889" y="926" width="437" height="463" frameX="-124" frameY="-116" frameWidth="600" frameHeight="600"/>
</TextureAtlas>`

**Comment by TurboGames0731** [comment]
edit: the xml is
`<TextureAtlas imagePath="max.png">
<SubTexture name="max singDOWN0000" x="0" y="0" width="422" height="463" frameX="-124" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max singDOWN0001" x="422" y="0" width="424" height="463" frameX="-124" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max idle0000" x="846" y="0" width="422" height="463" frameX="-124" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max idle0001" x="0" y="463" width="422" height="463" frameX="-124" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max idle0002" x="422" y="463" width="417" height="463" frameX="-124" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max idle0003" x="0" y="463" width="422" height="463" frameX="-124" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max singLEFT0000" x="1268" y="0" width="475" height="463" frameX="-71" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max singLEFT0001" x="1268" y="463" width="475" height="463" frameX="-71" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max singRIGHT0000" x="839" y="463" width="419" height="463" frameX="-127" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max singRIGHT0001" x="0" y="926" width="429" height="463" frameX="-127" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max singUP0000" x="429" y="926" width="460" height="463" frameX="-124" frameY="-116" frameWidth="600" frameHeight="600"/>
<SubTexture name="max singUP0001" x="889" y="926" width="437" height="463" frameX="-124" frameY="-116" frameWidth="600" frameHeight="600"/>
</TextureAtlas>`

**Comment by frantastic24** [comment]
That means the XML animation on the editor is wrong

**Comment by TurboGames0731** [comment]
what do i change it to?

**Comment by TurboGames0731** [comment]
i've gone through and fixed the animations before opening the issue

**Comment by frantastic24** [comment]
Change it to whatever animation you have on your XML, I can't tell you what to do because you didn't post your files

**Comment by TurboGames0731** [comment]
been doing it for an hour now, nothing works

**Comment by frantastic24** [comment]
> you didn't post your files

Character json and XML

**Comment by frantastic24** [comment]
![image](https://user-images.githubusercontent.com/95725102/169675659-e477eb66-e90c-4069-8885-26e54b211453.png)
![image](https://user-images.githubusercontent.com/95725102/169675656-4331dd96-b52e-41d5-beb4-50a48c39202b.png)

**Comment by ShadowMario** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Creating-a-Character
