### ISSUE TITLE
How do i put assets infront bf n shit in a stage in source code?

### ISSUE THREAD

**Issue by AntiPlayzz** [ShadowMario/FNF-PsychEngine#8730]
### Describe your problem here.

i already know how to do it in lua which is addLuaSprite('theSky',true) but i would like to replicate this in source code, help would be appreciated! :)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Coins609** [comment]
I am not sure what the best way to do it is but this is the way i do it
![Capture](https://user-images.githubusercontent.com/103952849/169718174-98804970-2547-4203-b773-2c9bbbb11e6d.PNG)

**Comment by AntiPlayzz** [comment]
got it working from someone else just now but thank you for your input anyway! :)
