### ISSUE TITLE
Actual Normal Health Bar Colors and BF-Old trigger.

### ISSUE THREAD

**Issue by SIG7Pro** [ShadowMario/FNF-PsychEngine#8734]
### What feature do you want to get added on the **base** engine?

An option for normal health bar colors (and maybe the 9 press for bf-old icon trigger as well).
Example: Kade Engine has an option for normal health bar colors, and it has kept the "Press 9 to change the icon to BF-Old."
Or is it possible to do that with a LUA script? (Haven't done FNF'PE LUA before.)

**Comment by BeastlyGhost** [comment]
https://cdn.discordapp.com/attachments/922851578996744252/978068986401009714/vanillapatch2.zip try this

**Comment by tylerandari12** [comment]
Pressing 9 is possible with Lua...
But the health bar could be added...

For now youd need to change the JSONs to get the colors...

**Comment by Itz-NOT-Miles** [comment]
I should make a pull request that ties vanilla easter eggs to the "engine watermarks" option. If Psych watermarks are enabled, the easter eggs can't be activated, vice versa. (Shadow removed them to improve lua functionality, and for some other reasons)
