### ISSUE TITLE
Enemy note reaction coding with lua

### ISSUE THREAD

**Issue by SpookyMan16** [ShadowMario/FNF-PsychEngine#8737]
### What feature do you want to get added on the **base** engine?

basically you can toggle enemy note reaction with lua, it is possible as shown here: https://drive.google.com/file/d/1xQaPv4bKf8QcIyJ7cKg8FT3X1Xz2ws3h/view?usp=sharing

all the coder would have to do in their lua script is:
setProperty("enemyNoteReact", false)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
What is "Enemy Note Reaction" supposed to mean

**Comment by tylerandari12** [comment]
You can remove the animation from an arrow...

`setPropertyFromGroup("unspawnNotes", i, "noAnimation", true);`

However I feel there should be a thing that allows you to disable the strum animations for specific notes...

**Comment by tylerandari12** [comment]
I just thought about it and I think I understand...

You can miss notes as the player...
There needs to be a variable for notes that the ENEMY is forced to miss...
(According to him there is...)

**Comment by frantastic24** [comment]
bro posted the entirety of playstate instead of explaining the two lines they changed wtf
basically they just want an option to disable opponent strum animations

**Comment by cyn-8** [comment]
you can just use lua play the strum notes default animations when a note is hit

**Comment by ShadowMario** [comment]
> I just thought about it and I think I understand...
> 
> You can miss notes as the player... There needs to be a variable for notes that the ENEMY is forced to miss... (According to him there is...)

That can be done by setting `ignoreNote` to true, can i close this issue then?

**Comment by machonessiebaby** [comment]
i would just use a play animation event in sync when the note comes make sure ignoreNote is true
