### ISSUE TITLE
Fullscreen while the application is windowed

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#8739]
### Describe your bug here.

I unlocked **theater mode**.

I haven't seen this bug _ever_ and I have **no** idea how it happened. I was just playing Psych engine and I noticed it
This is the **_only_** [footage](https://www.youtube.com/watch?v=KT50kTrieHY) I have

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

(This is my alt fnf engine I Just play mods on this one) I added crazy and impossible diffuculty with source, downloaded like 50 mods.

**Comment by tylerandari12** [comment]
The way the video was recorded doesn't show anything...

Also you can change window stuff with Lua so that might be intentional...

**Comment by Draconic-Hybrid** [comment]
My only guess would be a weird bug that, if you alt-tab and then return to the app, the game still thinks you're holding down alt, so as a result, when you press enter, it thinks you're doing the alt-enter fullscreen. Seeing as you hit pause momentarily in that video, that's the only thing I can think of. To fix it, just press alt once, to make sure the game detects that you released alt.
