### ISSUE TITLE
question about furiosity and polygonized colors

### ISSUE THREAD

**Issue by feder273** [ShadowMario/FNF-PsychEngine#874]
### What is your question?

does somebody know how to do that colors thing like on furiosity

**Comment by PoleyMagik** [comment]
Shaders, dunno how exactly, go look at their source code.

**Comment by GrateSkata** [comment]
yeah i dunno how, im pretty sure VS. Dave uses Kade Engine so you might as well shift to that and just copy what they use

**Comment by ShadowMario** [comment]
![fucktard](https://user-images.githubusercontent.com/44785097/140672872-110a8747-7704-435a-bd57-0cb0e846bbc4.png)
