### ISSUE TITLE
How to make bf die with one miss?

### ISSUE THREAD

**Issue by TrigJop** [ShadowMario/FNF-PsychEngine#8740]
### What is your question?

How to make bf die with one miss?
P.S With lua script

**Comment by WilliamGaming12** [comment]
Make a notetype where if you miss, it quits like 500 of damage, put it in bf's side everytime he sings

Like an insta kill note but u gotta press it or u die.

Here's an example:
`function onCreate()
	--Iterate over all notes
	for i = 0, getProperty('unspawnNotes.length')-1 do
		if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Bullet_Note' then --Check if the note on the chart is a Bullet Note
			setPropertyFromGroup('unspawnNotes', i, 'texture', 'Bullet_Note'); --Change texture
			setPropertyFromGroup('unspawnNotes', i, 'hitHealth', '0.023'); --Default value is: 0.023, health gained on hit
			setPropertyFromGroup('unspawnNotes', i, 'missHealth', '1000'); --if it's negative it heals, if its positive, it damages
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashHue', 0); --custom notesplash color, why not
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashSat', -20);
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashBrt', 1);

			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then --Doesn't let Dad/Opponent notes get ignored
				setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', false); --Miss has penalties
			end
		end
	end
	--debugPrint('Script started!')
end

local shootAnims = {"LEFTshoot", "DOWNshoot", "UPshoot", "RIGHTshoot"}
function goodNoteHit(id, direction, noteType, isSustainNote)
	if noteType == 'Bullet_Note' then
		--nothing
	end
end

function noteMiss(id, direction, noteType, isSustainNote)
	if noteType == 'Bullet_Note' and difficulty == 2 then
		--nothing i guess
	end
end`

**Comment by WilliamGaming12** [comment]
goofy ahh colocation

**Comment by frantastic24** [comment]
```lua
function onCreatePost()
     setProperty('instakillOnMiss', true)
end
```

**Comment by BeastlyGhost** [comment]
> ```lua
> function onCreatePost()
>      setProperty('instakillOnMiss', true)
> end
> ```

we can probably extend this and add

```lua
function onCreatePost()
     setProperty('instakillOnMiss', true)
end

function onDestroy()
     setProperty('instakillOnMiss', false)
end
```

**Comment by frantastic24** [comment]
it's not changing clientprefs so it's not needed

**Comment by ShadowMario** [comment]
> it's not changing clientprefs so it's not needed

This is true! It's a temporary variable.
Closing this now since it's resolved.
