### ISSUE TITLE
Change the X and Y position of a character (BF, GF, Opponent)

### ISSUE THREAD

**Issue by Staichi54** [ShadowMario/FNF-PsychEngine#8743]
### Describe your problem here.

So im using the last version of the psych engine and i have a backgrpund with a certain space for the characters, but i cant change his positions with the code, everytime i try change a value in the code, the game close, so if someone can help me, it will be thankful

The actual last version is 0.5.2h

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Just add a backgorund

**Comment by Lorekeeper49** [comment]
Which one are you doing?
```lua
--this? (which crashes the game)
function onCreate() 
    doTweenX('moveCharX', char, x, t, ease);
    doTweenY('moveCharY', char, y, t, ease);
end

--or this? (which works)
function onCreatePost() 
    doTweenX('moveCharX', char, x, t, ease);
    doTweenY('moveCharY', char, y, t, ease);
end
```
if neither then send us the code so that we can debug

**Comment by Staichi54** [comment]
Im not using lua, im trying to change the x and y position in the source directly

In my case i try

boyfriend.x = 100;
dad.x = 0; 

In the case of the stage (in the PlayState.hx), if i delete that, the game load normally, but if i put that in the code, the game crash

**Comment by Staichi54** [comment]
> Which one are you doing?
> 
> ```lua
> --this? (which crashes the game)
> function onCreate() 
>     doTweenX('moveCharX', char, x, t, ease);
>     doTweenY('moveCharY', char, y, t, ease);
> end
> 
> --or this? (which works)
> function onCreatePost() 
>     doTweenX('moveCharX', char, x, t, ease);
>     doTweenY('moveCharY', char, y, t, ease);
> end
> ```
> 
> if neither then send us the code so that we can debug

Sorry, i didn't quote the answer

**Comment by NS-Unfair** [comment]
Where exactly are you placing those lines of code? You should make sure they're placed after boyfriend and dad are created.

**Comment by NS-Unfair** [comment]
@Staichi54

**Comment by NS-Unfair** [comment]
What was the error message?

**Comment by Staichi54** [comment]
@NS-Unfair There's no message, the game just close, check
![imagen_2022-05-27_155653405](https://user-images.githubusercontent.com/73539099/170788342-80184b56-6e9e-49e5-a007-2794f9bdd905.png)
