### ISSUE TITLE
How do I add uncharted songs into Psych Engine?

### ISSUE THREAD

**Issue by furryChrisUSER** [ShadowMario/FNF-PsychEngine#8745]
### Describe your problem here.

I've tried searching everywhere and I can't find an answer so I'm going to try asking. I want to add a song and make a custom chart for it. How would I go about doing that? I have done all of the things I need for it to work but when I try to play the song it freezes the chart and the timer is set to 0:00.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added the song's instrumental and voices already and I added data but it was copied from Fresh. I renamed the data to the respective song name in the files and I went into the data and changed the name of the song (Fresh) to the one I'm trying to add. But that is when my song does not work.

**Comment by frantastic24** [comment]
Reconvert/re-export your music files
