### ISSUE TITLE
Credits background color error

### ISSUE THREAD

**Issue by coolray742** [ShadowMario/FNF-PsychEngine#8746]
### Describe your bug here.

when I made my custom part of the credits the background colour just quickly fades to black and not the colour I wanted it to set even though the credits.txt colour code in HTML is fine
![image](https://user-images.githubusercontent.com/83708844/169738669-07119cab-22d0-41d6-a5d5-d225ab4c44fd.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by tylerandari12** [comment]
Need more info...

What does your color thing look like?

**Comment by coolray742** [comment]
> Need more info...
> 
> What does your color thing look like?

Does this help? or do you need something in particular?
![image](https://user-images.githubusercontent.com/83708844/169742445-61250f33-3b60-42fb-9490-426ed4bc8aea.png)

**Comment by tylerandari12** [comment]
Try removing the 0x..
But somethings wrong with the R value...

**Comment by frantastic24** [comment]
Add `FF` after `0x`, it's transparency value

**Comment by coolray742** [comment]
> Add `FF` after `0x`, it's transparency value
Oh, it worked! thank you so much, I appreciate it!
