### ISSUE TITLE
iterate over spawned notes

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8747]
### What is your question?

I know you can iterate over the notes that havent spawned in yet with:
```
for i = 0, getProperty("unspawnNotes.length") - 1 do
     --code lol
end
```
but how do I iterate over the notes that HAVE spawned in?

**Comment by frantastic24** [comment]
`notes`

**Comment by tylerandari12** [comment]
Thanks my guy...
