### ISSUE TITLE
is this normal?

### ISSUE THREAD

**Issue by coolray742** [ShadowMario/FNF-PsychEngine#8748]
### Describe your problem here.

when i am compiling the code i see this message, do you guys know if this is supposed to happen?
![image](https://user-images.githubusercontent.com/83708844/169741513-352f0c8f-fcd7-48db-a680-521100966d27.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
It's normal, doesn't cause any issues

**Comment by coolray742** [comment]
> It's normal, doesn't cause any issues
ah ok thank you!
