### ISSUE TITLE
idk :( Do you k?

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8749]
### What is your question?

I'm trying to make the notes spin but I'm stuck...

While I try to debug myself I decided to post here...

(EDIT: I want the colored arrows moving, Not the note strums.)

```
local Rot = 0
function onUpdate(elapsed)
	Rot = Rot + 1
	for i = 0, getProperty("notes.length") - 1 do
		--Check if the note is an Instakill Note
		if --[[getPropertyFromGroup("notes", i, "noteType") == "AXENOTE" and]] getPropertyFromGroup("notes", i, "isSustainNote") == false then
			setPropertyFromGroup("notes", i, "angle", Rot)
		end
	end
end
```

Keep in mind there are no errors...

**Comment by Meme1079** [comment]
this `setPropertyFromGroup("notes", i, "angle", Rot)` wont work cuz there angle

```lua
local Rot = 0
function onUpdate(elapsed)
    Rot = Rot + 1
	for i = 0, getProperty('notes.length')-1 do
		--Check if the note is an Instakill Note
		if --[[getPropertyFromGroup('notes', i, 'noteType') == 'AXENOTE' and]] getPropertyFromGroup('notes', i, 'isSustainNote') == false then
            noteTweenAngle('Oppo0', 0, Rot, 0.1, 'linear')
            noteTweenAngle('Oppo1', 1, Rot, 0.1, 'linear')
            noteTweenAngle('Oppo2', 2, Rot, 0.1, 'linear')
            noteTweenAngle('Oppo3', 3, Rot, 0.1, 'linear')
            noteTweenAngle('Play4', 4, Rot, 0.1, 'linear')
            noteTweenAngle('Play5', 5, Rot, 0.1, 'linear')
            noteTweenAngle('Play6', 6, Rot, 0.1, 'linear')
            noteTweenAngle('Play7', 7, Rot, 0.1, 'linear')
		end
	end
end
```

**Comment by tylerandari12** [comment]
This is a nice script but I had it like it was for a reason...
You see I dont want the strums moving around, I want just the arrows spinning...

Like this:
![ArrowLol](https://user-images.githubusercontent.com/97060639/169758954-6a618e9c-a5fd-4f45-af56-d7f2d7026421.png)

**Comment by Meme1079** [comment]
Sorry but it's impossible to do it, I just can't find a way to do it

**Comment by tylerandari12** [comment]
> Sorry but it's impossible to do it, I just can't find a way to do it

It's ok :(

**Comment by cyn-8** [comment]
u gotta set the notes `copyAngle` to false at the beginning of the script cuz it defaults to true and that means the note copies the angle of the respective strum every frame

also just a suggestion
use elapsed as a factor in the angle increment so that ppl with higher fps dont get ultra fast spin

**Comment by tylerandari12** [comment]
> u gotta set the notes `copyAngle` to false at the beginning of the script cuz it defaults to true and that means the note copies the angle of the respective strum every frame
> 
> also just a suggestion
> use elapsed as a factor in the angle increment so that ppl with higher fps dont get ultra fast spin

Haha fest spin go brrrrrr!

But I will see about the copyAngle thing.
