### ISSUE TITLE
goodNoteHit not responding

### ISSUE THREAD

**Issue by Abdul3891** [ShadowMario/FNF-PsychEngine#8750]
### Describe your bug here.

Tryna edit my script here that updates note counter, judgement, and more, but goodNoteHit can't.. umm.. how do I say this.. trigger.
Code:
`function goodNoteHit(id, direction, noteType, isSustainNote)
    if not isSustainNote then
        strumTime = getPropertyFromGroup('notes', id, 'strumTime')
        songPos = getPropertyFromClass('Conductor', 'songPosition')
        rOffset = getPropertyFromClass('ClientPrefs','ratingOffset')
	    sizeZoomCur = 46
	     local noteDiffSign = strumTime - songPos + rOffset
    local noteDiffAbs = math.abs(noteDiffSign)
    local totalNotesForNow = handleNoteDiff(noteDiffAbs)
    -- local rawJudgements = cancelExistingJudgements(noteDiffAbs)
    -- debugPrint(rawJudgements)
    -- local notesHitDiff = totalNotesForNow - rawJudgements
    -- addHits(noteHitDiff)
    showMsDiffOnScreen(noteDiffSign)
    curTotalNotesHit = curTotalNotesHit + totalNotesForNow
    counterUpdated = counterUpdated + 1`
But in reality the text size isn't increasing.

### Command Prompt/Terminal logs (if existing)

```bash
None
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Meme1079** [comment]
I don't know if this the full script but, I think you forgot putting 'end'

```lua
function goodNoteHit(id, direction, noteType, isSustainNote) 
    if not isSustainNote then 
        strumTime = getPropertyFromGroup('notes', id, 'strumTime') 
        songPos = getPropertyFromClass('Conductor', 'songPosition') 
        rOffset = getPropertyFromClass('ClientPrefs','ratingOffset') 
        sizeZoomCur = 46 
        local noteDiffSign = strumTime - songPos + rOffset 
        local noteDiffAbs = math.abs(noteDiffSign) 
        local totalNotesForNow = handleNoteDiff(noteDiffAbs) 
        -- local rawJudgements = cancelExistingJudgements(noteDiffAbs) 
        -- debugPrint(rawJudgements) 
        -- local notesHitDiff = totalNotesForNow - rawJudgements 
        -- addHits(noteHitDiff) 
        -- showMsDiffOnScreen(noteDiffSign) 
        curTotalNotesHit = curTotalNotesHit + totalNotesForNow 
        counterUpdated = counterUpdated + 1
    end -- you forgot to put this
end -- and this      
```

**Comment by Meme1079** [comment]
can you send the full script, i think sending a part of the script won't help me

**Comment by Abdul3891** [comment]
> I don't know if this is the full script but, I think you forgot putting 'end'
> 
> ```lua
> function goodNoteHit(id, direction, noteType, isSustainNote) 
>     if not isSustainNote then 
>         strumTime = getPropertyFromGroup('notes', id, 'strumTime') 
>         songPos = getPropertyFromClass('Conductor', 'songPosition') 
>         rOffset = getPropertyFromClass('ClientPrefs','ratingOffset') 
>         sizeZoomCur = 46 
>         local noteDiffSign = strumTime - songPos + rOffset 
>         local noteDiffAbs = math.abs(noteDiffSign) 
>         local totalNotesForNow = handleNoteDiff(noteDiffAbs) 
>         -- local rawJudgements = cancelExistingJudgements(noteDiffAbs) 
>         -- debugPrint(rawJudgements) 
>         -- local notesHitDiff = totalNotesForNow - rawJudgements 
>         -- addHits(noteHitDiff) 
>         -- showMsDiffOnScreen(noteDiffSign) 
>         curTotalNotesHit = curTotalNotesHit + totalNotesForNow 
>         counterUpdated = counterUpdated + 1
>     end -- you forgot to put this
> end -- and this      
> ```

Full code:
`-- Debug stuff
luaDebugMode = true
luaDepracatedWarnings = true
-- Show millisecond with judgement

local a1 = 0.254829592;
local a2 = -0.284496736;
local a3 = 1.421413741;
local a4 = -1.453152027;
local a5 = 1.061405429;
local p = 0.3275911;
local curTotalNotesHit = 0
local counterUpdated = 0
local actualRatingHere = 0.00
local msDiffTimeLimit = 1800  -- how many ms after hitting a note should the ms rating disappear
local lastMsShowUp = 0
local msTextVisible = false
local sizeZoomMin = 35

function onCreate()
    -- the 540 is the x pos of the text; the 360 is the y pos of the text. Note that y pos is from the top.
    makeLuaText('msTxt', ' ', 300, screenWidth / 2 - 300 / 2, 270)
    makeLuaText('noteHitNum', 'Total notes hit: 0', 300, screenWidth / 2 - 300 / 2, 222)
    makeLuaText('judgement', ' ', 300, screenWidth / 2 - 300 / 2, 241) 
    makeLuaText('sick', 'Perfect: 0', 300, screenWidth / 2 - 300 / 2, 425)
    makeLuaText('good', 'Good: 0', 300, screenWidth / 2 - 300 / 2, 444)
    makeLuaText('bad', 'Bad: 0', 300, screenWidth / 2 - 300 / 2, 463)
    makeLuaText('shit', 'Shit: 0', 300, screenWidth / 2 - 300 / 2, 482)
    makeLuaText('combo', '', 300, screenWidth / 2 - 300 / 2, 195)
    makeLuaText('score', 'Score: 0', 300, screenWidth / 2 - 300 / 2, 385)
    makeLuaText('accuracy', 'Accuracy: 0.00%', 300, screenWidth / 2 - 300 / 2, 405)
    setTextSize('judgement', 34)
    setTextSize('msTxt', 34)
    setTextSize('noteHitNum', 34)
    setTextSize('sick', 34)
    setTextSize('good', 34)
    setTextSize('bad', 34)
    setTextSize('shit', 34)
    setTextSize('combo', 34)
    setTextSize('score', 34)
    setTextSize('accuracy', 34)
    setTextBorder('noteHitNum', 2, '000000')
    setTextBorder('judgement', 2, '000000')
    setTextBorder('msTxt', 2, '000000') 
    setTextBorder('sick', 3, '000000')
    setTextBorder('good', 3, '000000')
    setTextBorder('bad', 3, '000000')
    setTextBorder('shit', 3, '000000')
    setTextBorder('combo', 3, '000000')
    setTextBorder('score', 2, '000000')
    setTextBorder('accuracy', 2, '000000')
    setTextFont('msTxt', 'pixel.otf')
    addLuaText('judgement') 
    addLuaText('msTxt') 
    addLuaText('noteHitNum') 
    addLuaText('sick')
    addLuaText('good')
    addLuaText('bad')
    addLuaText('shit')
    addLuaText('combo')
    notes = 0
    sizeZoomCur = 34
    setProperty('scoreTxt.text', 'Score: 0 | Accuracy: 0.00% | Rating: ?') 
    end



function onUpdatePost(elapsed)
	-- start of "update", some variables weren't updated yet
    -- This updates the contents of the score text.
    -- the rating name is not drawn from the game source.
    -- debugPrint(curTotalNotesHit)
    if botPlay then
    setProperty('botplayTxt.text', 'Autoplay')
end 
    s = getProperty('sicks')
    g = getProperty('goods')
    b = getProperty('bads')
    sh = getProperty('shits')
    combo = getProperty('combo')
    setTextString('sick', 'Perfect: ' ..s.. '')
    setTextString('good', 'Good: ' ..g.. '')
    setTextString('bad', 'Bad: ' ..b.. '') 
    setTextString('shit', 'Shit: ' ..sh.. '')
    setTextString('combo', 'Combo: ' ..combo.. '')
    if sizeZoomCur > 34 then
          sizeZoomCur = sizeZoomCur - 2
    end
    setTextSize('combo', sizeZoomCur) 
    setTextSize('judgement', sizeZoomCur) 
            addLuaText('msTxt')
        addLuaText('noteHitNum')
        addLuaText('judgement')
        addLuaText('sick')
        addLuaText('good')
        addLuaText('bad')
        addLuaText('shit')
        addLuaText('combo') 
    -- DETERMING WHETHER TO HIDE THE MS DIFF
    local curSongPosRightNow = getPropertyFromClass('Conductor', 'songPosition')
    if curSongPosRightNow - lastMsShowUp > msDiffTimeLimit and msTextVisible then
        removeLuaText('msTxt', false)
        removeLuaText('judgement', false)
        removeLuaText('noteHitNum', false)
        setTextString('msTxt', '')
        setTextString('judgement', '')
        addLuaText('msTxt')
        addLuaText('noteHitNum')
        addLuaText('judgement')
        addLuaText('sick')
        addLuaText('good')
        addLuaText('bad')
        addLuaText('shit')
        addLuaText('combo')
        msTextVisible = false
    end 
    -- Update score text
    setProperty('scoreTxt.visible', true) 
      if getProperty('ratingPercent') == 1 then
    ratingN = 'Pure Perfect!!'
elseif getProperty('ratingPercent') >= 0.975 then
    ratingN = 'Nearly perfect!'
elseif getProperty('ratingPercent') >= 0.95 then
    ratingN = 'So sick!'
elseif getProperty('ratingPercent') >= 0.9 then
    ratingN = 'Sick!'
elseif getProperty('ratingPercent') >= 0.85 then
    ratingN = 'Nearly sick!'
elseif getProperty('ratingPercent') >= 0.8 then
    ratingN = 'Great!'
elseif getProperty('ratingPercent') >= 0.7 then
    ratingN = 'Good'
elseif getProperty('ratingPercent') >= 0.675 then
    ratingN = 'Nice'
elseif getProperty('ratingPercent') >= 0.6 then
    ratingN = 'Meh'
elseif getProperty('ratingPercent') >= 0.5 then
    ratingN = 'Bruh'
elseif getProperty('ratingPercent') >= 0.4 then
    ratingN = 'Bad' 
elseif getProperty('ratingPercent') >= 0.35 then
    ratingN = 'Really bad!'
elseif getProperty('ratingPercent') >= 0.2 then
    ratingN = 'Shit'
elseif getProperty('ratingPercent') >= 0.1 then
    ratingN = 'You Suck!'
elseif getProperty('ratingPercent') > 0 then
    ratingN = 'You REALLY Suck!!'
elseif miss >= 1 then
    ratingN = 'Are you trying to get 0%?'
else
    ratingN = 'NOT PLAYING'
end 

points = getProperty('songScore')
scoreStr = tostring(score)
acc = getProperty('ratingPercent') * 10000
accRound = math.floor(acc) / 100
accStr = tostring(accRound)
miss = getProperty('songMisses')
missStr = tostring(miss)
if botPlay then
    ratingM = 'Perfect Full Combo'
    setProperty('sicks', notesStr)
    setProperty('goods', '0')
    setProperty('bads', '0')
    setProperty('shits', '0')
elseif getProperty('ratingFC') == 'SFC' then
    ratingM = 'Perfect Full Combo'
elseif getProperty('ratingFC') == 'GFC' then
    ratingM = 'Good Full Combo'
elseif getProperty('ratingFC') == 'FC' then
    ratingM = 'Full Combo'
elseif getProperty('ratingFC') == 'SDCB' then
    ratingM = 'Single Digit Misses'
elseif getProperty('ratingFC') == 'Clear' then
    ratingM = 'Clear'
else 
    ratingM = '?'
end  
-- debugPrint('Score: ' ..scoreStr.. ' | Accuracy: ' ..accStr.. '% | Misses: ' ..missStr.. '| GF says: ' ..ratingN.. ' (' ..ratingM.. ')')
setProperty('scoreTxt.text', 'Score: '..scoreStr..' | Accuracy: '..accStr..' | Misses: ' ..missStr.. ' | Rating: ' ..ratingN.. ' (' ..ratingM.. ')')
end




function updateAccuracy(strumTime, songPos, rOffset) -- HELPER FUNCTION
   
end


function showMsDiffOnScreen(diff)  -- remove everything in this function if you don't want ms timings.
    removeLuaText('msTxt', false)
    local msDiffStr = string.format("%.3fms", -diff)
    -- debugPrint(msDiffStr)
    local textColor = ratingTextColor(diff)
    setTextColor('msTxt', textColor)
    setTextColor('judgement', textColor)
    if botPlay then
         setTextString('msTxt', '0.000ms (botplay)')
    else
         setTextString('msTxt', msDiffStr)
    end
    if diff > 399 then
         setTextString('msTxt', '')
    end
    addLuaText('msTxt')
    lastMsShowUp =  getPropertyFromClass('Conductor', 'songPosition')
    msTextVisible = true

    -- local msDiffStr = string.format("%.3f", diff)
    -- msDiffStr = msDiffStr + 'ms'
    debugPrint(msDiffStr)
 
end

function ratingTextColor(diff)
    health = getProperty('health')
    local absDiff = math.abs(diff)
    if botPlay then
        addScore(400)
        setRatingPercent(1)
        setTextString('judgement', 'Perfect!')
        if health < 1 then
             setProperty('health', health + 0.05)
        end
        perfectStr = tostring(perfect) 
        return '00FFFF'
    elseif absDiff < 46.0 then
        setTextString('judgement', 'Perfect!')
        addScore(50) 
        if health < 1 then
             setProperty('health', health + 0.05)
        end
        return '00FFFF'
    elseif absDiff < 91.0 then
        addScore(35)
        setTextString('judgement', 'Good!')
        return '00AA00'
    elseif absDiff < 136.0 then
        addScore(40)
        setTextString('judgement', 'Bad')
        return 'FF8800'
    else
        addScore(50)
        setTextString('judgement', 'Very bad!')
        return 'FF0000'
    end
end
    

function cancelExistingJudgements(diff) -- HELPER FUNCTION
    if diff < 46.0 then
        return 1.0
    elseif diff < 91.0 then
        return 0.75
    elseif diff < 136.0 then
        return 0.5
    else
        return 0.0
    end
end

function handleNoteDiff(diff) -- HELPER FUNCTION
    local maxms = diff
    local ts = 1

    local max_points = 1.0;
    local miss_weight = -1.0; -- used to be -5.5; this should be a lot less harsh.
    local ridic = 5 * ts;
    local max_boo_weight = 166
    local ts_pow = 0.75;
    local zero = 65 * ts^ts_pow
    local power = 2.5;
    local dev = 22.7 * ts^ts_pow

    if (maxms <= ridic) then -- // anything below this (judge scaled) threshold is counted as full pts
        return max_points
    elseif (maxms <= zero) then -- // ma/pa region, exponential
        return max_points * erf((zero - maxms) / dev)
    elseif (maxms <= max_boo_weight) then -- // cb region, linear
        return (maxms - zero) * miss_weight / (max_boo_weight - zero)
    else
        return miss_weight
    end
end

function erf(x)  -- HELPER FUNCTION
    local sign = 1;
    if (x < 0) then
        sign = -1;
    end
    x = math.abs(x);
    local t = 1.0 / (1.0 + p * x);
    local y = 1.0 - (((((a5 * t + a4) * t) + a3) * t + a2) * t + a1) * t * math.exp(-x * x);

    return sign * y;
end

function opponentNoteHit(isSustainNote)
    addScore(350)
    setProperty('scoreTxt.text', ' Score: ' ..scoreStr.. ' | Accuracy: ' ..accStr.. '% | Misses: ' ..missStr.. ' | Rating: ' ..ratingN.. ' (' ..ratingM.. ')') 
end

function onEndSong()
	if botPlay then
	    setScore(0)
	    setRatingPercent(0)
	end
end

function goodNoteHit(id, direction, noteType, isSustainNote)
    if not isSustainNote then
        strumTime = getPropertyFromGroup('notes', id, 'strumTime')
        songPos = getPropertyFromClass('Conductor', 'songPosition')
        rOffset = getPropertyFromClass('ClientPrefs','ratingOffset')
	    sizeZoomCur = 46
	     local noteDiffSign = strumTime - songPos + rOffset
    local noteDiffAbs = math.abs(noteDiffSign)
    local totalNotesForNow = handleNoteDiff(noteDiffAbs)
    -- local rawJudgements = cancelExistingJudgements(noteDiffAbs)
    -- debugPrint(rawJudgements)
    -- local notesHitDiff = totalNotesForNow - rawJudgements
    -- addHits(noteHitDiff)
    showMsDiffOnScreen(noteDiffSign)
    curTotalNotesHit = curTotalNotesHit + totalNotesForNow
    counterUpdated = counterUpdated + 1
    -- curAccuracy = curTotalNotesHit / counterUpdated
    -- debugPrint(curTotalNotesHit)
    -- setHits(curTotalNotesHit)
    -- getProperty(totalNotesHit)
    
    -- debugPrint(curTotalNotesHit / counterUpdated)
    actualRatingHere = curTotalNotesHit / counterUpdated
    -- debugPrint(tln)
    -- setProperty('totalNotesHit', curTotalNotesHit)
    -- setProperty('totalPlayed', counterUpdated)

    -- ratingStr = accuracyToRatingString(curAccuracy * 100)
    -- setProperty('ratingPercent', math.max(0, curAccuracy))
    -- setProperty('ratingName', ratingStr)
    triggerEvent('Add Camera Zoom', '0.015', '-0.005')
    notes = notes + 1
    notesStr = tostring(notes)
    setTextString('noteHitNum', 'Total notes hit: '..notesStr..'') 
    alpha = 1 
    else
        addScore(350)
        setProperty('scoreTxt.text', 'Score: ' ..scoreStr.. ' | Accuracy: ' ..accStr.. '% | Misses: ' ..missStr.. ' | Rating: ' ..ratingN.. ' (' ..ratingM.. ')')
    end
    
end  `

**Comment by frantastic24** [comment]
seems to be working fine here
![image](https://user-images.githubusercontent.com/95725102/169921164-4f6f3cb0-6fb1-41e7-b9ac-faa9298faeae.png)
