### ISSUE TITLE
BF dies after one miss and the charting speed is stuck to 2! help!

### ISSUE THREAD

**Issue by HaruBaru69** [ShadowMario/FNF-PsychEngine#8751]
### Describe your problem here.

BF dies after one miss and the charting speed is stuck to 2! help!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a modfolder

**Comment by frantastic24** [comment]
Press Control in freeplay/story menu

**Comment by CrusherMods** [comment]
Step 1: Press CTRL in Story Mode or Freeplay
Step 2: (For problem 1)
![image](https://user-images.githubusercontent.com/90648119/169900462-8c302f7f-0d51-43e8-8f90-632157f399d6.png)
Step 3: (For problem 2)
![image](https://user-images.githubusercontent.com/90648119/169900537-7899e308-6ccf-4420-822c-55e45ecc42b2.png)

**Comment by HaruBaru69** [comment]
> Step 1: Press CTRL in Story Mode or Freeplay Step 2: (For problem 1) ![image](https://user-images.githubusercontent.com/90648119/169900462-8c302f7f-0d51-43e8-8f90-632157f399d6.png) Step 3: (For problem 2) ![image](https://user-images.githubusercontent.com/90648119/169900537-7899e308-6ccf-4420-822c-55e45ecc42b2.png)

Thanks! this worked!

**Comment by frantastic24** [comment]
You can close this now
