### ISSUE TITLE
How do animated icon?

### ISSUE THREAD

**Issue by FuionCuzWhyNot** [ShadowMario/FNF-PsychEngine#8752]
### Describe your problem here.

Can i add animated icon?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i add character

**Comment by bf244** [comment]
bf 

function onCreatePost()
	makeAnimatedLuaSprite('Dad', 'icons/icon-bfgod', getProperty('iconP1.x'), getProperty('iconP1.y'))

	luaSpriteAddAnimationByPrefix('Dad', 'move', 'idle', 24, false);  -- change here

	setObjectCamera('Dad', 'hud')
	addLuaSprite('Dad', true)
	setProperty('Dad.flipX', true) --mirror sprite horizontally
	setObjectOrder('Dad', getObjectOrder('iconP1') + 1)
	setProperty('iconP1.alpha', 0)
      scaleObject('Dad', 0.5, 0.5);
end
--------------------------------------------------------------------------------------------------------------------------------
function onUpdate()
	setProperty('Dad.x', getProperty('iconP1.x') + -10) -- change here
	setProperty('Dad.angle', getProperty('iconP1.angle'))
	setProperty('Dad.y', getProperty('iconP1.y') + -90) -- and here
end
---------------------------------------------------------------------------------------------------------------------------------
function onBeatHit()
	-- triggered 4 times per section
	if curBeat % 2 == 0 then -- change here
		objectPlayAnimation('Dad', 'move');
	end
end

**Comment by bf244** [comment]
function onCreatePost()
	makeAnimatedLuaSprite('Dad', 'icons/icon-youricon', getProperty('iconP2.x'), getProperty('iconP2.y'))

	luaSpriteAddAnimationByPrefix('Dad', 'move', 'idle', 24, false);  -- change here

	setObjectCamera('Dad', 'hud')
	addLuaSprite('Dad', true)
	setProperty('Dad.flipX', true) --mirror sprite horizontally
	setObjectOrder('Dad', getObjectOrder('iconP2') + 1)
	setProperty('iconP2.alpha', 0)
      scaleObject('Dad', 0.5, 0.5);
end
--------------------------------------------------------------------------------------------------------------------------------
function onUpdate()
	setProperty('Dad.x', getProperty('iconP2.x') + -10) -- change here
	setProperty('Dad.angle', getProperty('iconP2.angle'))
	setProperty('Dad.y', getProperty('iconP2.y') + -90) -- and here
end
---------------------------------------------------------------------------------------------------------------------------------
function onBeatHit()
	-- triggered 4 times per section
	if curBeat % 2 == 0 then -- change here
		objectPlayAnimation('Dad', 'move');
	end
end

dad

**Comment by PurpleSSSnake** [comment]
He modding with **source**

**Comment by Staichi54** [comment]
@bf244 where should I put all that code?
