### ISSUE TITLE
defaultCamZoom error that crashes the game on gameover

### ISSUE THREAD

**Issue by Joanarr** [ShadowMario/FNF-PsychEngine#8755]
### Describe your bug here.

I've been using setProperty('defaultCamZoom', value1); many a time in psych modding via custom events, stage, or song luas to control the camera zoom. Normally it works fine but some reason getting two gameovers yields the error message Invalid field: defaultCamZoom. 
![error](https://user-images.githubusercontent.com/47956549/169917876-0ee5e1f4-549b-4203-a8d2-fdc7ce58ca0e.PNG)
I tried defaultCamzoom, defaultCameraZoom, etc., but those all had much more frequent error messages and wouldn't even let the song load. So defaultCamZoom should be correct, right? Why is it not correct when gameover, and why only the second gameover?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
show your script

**Comment by Joanarr** [comment]
function onEvent(name, value1, value2)
	if name == 'Default Camera Zoom' then
		if value1 == '' then
		-- do nothing lol
		else
			setProperty('defaultCamZoom', value1);
		end

		if value2 == '' then
		-- do nothing lol
		else
			setProperty('cameraSpeed', value2);
		end
	end
end

That's what I use for the custom event

**Comment by Joanarr** [comment]
```
local xx = 200;
local yy = 450;
local xx2 = 550;
local yy2 = 450;
local ofs = 0;
local followchars = true;
local allowCountdown = false

function onCreate()

end

function onUpdate()
	if followchars == true then
		if mustHitSection == false then
			ofs = 20
			if getProperty('dad.animation.curAnim.name') == 'singLEFT' then
				triggerEvent('Camera Follow Pos',xx-ofs,yy)
			end
			if getProperty('dad.animation.curAnim.name') == 'singRIGHT' then
				triggerEvent('Camera Follow Pos',xx+ofs,yy)
			end
			if getProperty('dad.animation.curAnim.name') == 'singUP' then
				triggerEvent('Camera Follow Pos',xx,yy-ofs)
			end
			if getProperty('dad.animation.curAnim.name') == 'singDOWN' then
				triggerEvent('Camera Follow Pos',xx,yy+ofs)
			end
			if getProperty('dad.animation.curAnim.name') == 'singLEFT-alt' then
				triggerEvent('Camera Follow Pos',xx-ofs,yy)
			end
			if getProperty('dad.animation.curAnim.name') == 'singRIGHT-alt' then
				triggerEvent('Camera Follow Pos',xx+ofs,yy)
			end
			if getProperty('dad.animation.curAnim.name') == 'singUP-alt' then
				triggerEvent('Camera Follow Pos',xx,yy-ofs)
			end
			if getProperty('dad.animation.curAnim.name') == 'singDOWN-alt' then
				triggerEvent('Camera Follow Pos',xx,yy+ofs)
			end
			if getProperty('dad.animation.curAnim.name') == 'idle-alt' then
				triggerEvent('Camera Follow Pos',xx,yy)
			end
			if getProperty('dad.animation.curAnim.name') == 'idle' then
				triggerEvent('Camera Follow Pos',xx,yy)
			end
		else
			ofs = 15
			if getProperty('boyfriend.animation.curAnim.name') == 'singLEFT' then
				triggerEvent('Camera Follow Pos',xx2-ofs,yy2)
			end
			if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT' then
				triggerEvent('Camera Follow Pos',xx2+ofs,yy2)
			end
			if getProperty('boyfriend.animation.curAnim.name') == 'singUP' then
				triggerEvent('Camera Follow Pos',xx2,yy2-ofs)
			end
			if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN' then
				triggerEvent('Camera Follow Pos',xx2,yy2+ofs)
			end
			if getProperty('boyfriend.animation.curAnim.name') == 'idle-alt' then
				triggerEvent('Camera Follow Pos',xx2,yy2)
			end
			if getProperty('boyfriend.animation.curAnim.name') == 'idle' then
				triggerEvent('Camera Follow Pos',xx2,yy2)
			end
		end
	else
		if mustHitSection == false then
			ofs = 5
			if getProperty('dad.animation.curAnim.name') == 'singLEFT' then
				triggerEvent('Camera Follow Pos',xx-ofs,yy)
			end
			if getProperty('dad.animation.curAnim.name') == 'singRIGHT' then
				triggerEvent('Camera Follow Pos',xx+ofs,yy)
			end
			if getProperty('dad.animation.curAnim.name') == 'singUP' then
				triggerEvent('Camera Follow Pos',xx,yy-ofs)
			end
			if getProperty('dad.animation.curAnim.name') == 'singDOWN' then
				triggerEvent('Camera Follow Pos',xx,yy+ofs)
			end
			if getProperty('dad.animation.curAnim.name') == 'singLEFT-alt' then
				triggerEvent('Camera Follow Pos',xx-ofs,yy)
			end
			if getProperty('dad.animation.curAnim.name') == 'singRIGHT-alt' then
				triggerEvent('Camera Follow Pos',xx+ofs,yy)
			end
			if getProperty('dad.animation.curAnim.name') == 'singUP-alt' then
				triggerEvent('Camera Follow Pos',xx,yy-ofs)
			end
			if getProperty('dad.animation.curAnim.name') == 'singDOWN-alt' then
				triggerEvent('Camera Follow Pos',xx,yy+ofs)
			end
			if getProperty('dad.animation.curAnim.name') == 'idle-alt' then
				triggerEvent('Camera Follow Pos',xx,yy)
			end
			if getProperty('dad.animation.curAnim.name') == 'idle' then
				triggerEvent('Camera Follow Pos',xx,yy)
			end
		else
			ofs = 5
			if getProperty('boyfriend.animation.curAnim.name') == 'singLEFT' then
				triggerEvent('Camera Follow Pos',xx2-ofs,yy2)
			end
			if getProperty('boyfriend.animation.curAnim.name') == 'singRIGHT' then
				triggerEvent('Camera Follow Pos',xx2+ofs,yy2)
			end
			if getProperty('boyfriend.animation.curAnim.name') == 'singUP' then
				triggerEvent('Camera Follow Pos',xx2,yy2-ofs)
			end
			if getProperty('boyfriend.animation.curAnim.name') == 'singDOWN' then
				triggerEvent('Camera Follow Pos',xx2,yy2+ofs)
			end
			if getProperty('boyfriend.animation.curAnim.name') == 'idle-alt' then
				triggerEvent('Camera Follow Pos',xx2,yy2)
			end
			if getProperty('boyfriend.animation.curAnim.name') == 'idle' then
				triggerEvent('Camera Follow Pos',xx2,yy2)
			end
		end
	end
end
```
That's the song lua in the chart folder

**Comment by Joanarr** [comment]
```
function onCreate()
	if boyfriendName == 'johnny' then
		addCharacterToList('johnny-dead', 'boyfriend');
		setPropertyFromClass('GameOverSubstate', 'characterName', 'johnny-dead')
		setPropertyFromClass('GameOverSubstate', 'deathSoundName', 'johnny_dies')
	end
	if boyfriendName == 'tsu-real' then
		addCharacterToList('tsu-dead', 'boyfriend');
		setPropertyFromClass('GameOverSubstate', 'characterName', 'tsu-dead')
		setPropertyFromClass('GameOverSubstate', 'deathSoundName', 'tsu_dies')
	end
	if boyfriendName == 'sticky-player' then
		setPropertyFromClass('GameOverSubstate', 'characterName', 'sticky-player')
	else

	end
end
```
This lua is in the scripts folder so it always loads. For Johnny and Tsu, the death animation directs to separate sprite sheets and character jsons, but for Sticky it uses the same character json when dead and when playing

**Comment by frantastic24** [comment]
no crashes here, is there anything specific happening when it crashes

**Comment by Joanarr** [comment]
Specifically when the player dies, either by pressing R or missing enough notes. The error message will appear, and after clicking OK the game closes.

**Comment by frantastic24** [comment]
i mean more specific because it's not crashing on death for me

**Comment by Joanarr** [comment]
That's all the specifics I have. I have no idea what else is causing it, hence why I'm so confused and opened this issue in the first place

**Comment by Joanarr** [comment]
And on another song with all the same lua scripts (the song lua is a duplicate), the error doesn't appear.

**Comment by Joanarr** [comment]
oh wait
I noticed that the error only happens when I press R during the countdown before the song starts. I was misremembering when I said that the error also happens when enough notes are missed

**Comment by Joanarr** [comment]
it's fine when game over happens after the song starts

**Comment by frantastic24** [comment]
still working

**Comment by Joanarr** [comment]
Does it work for you when you press R during countdown?

**Comment by frantastic24** [comment]
yes it's fine, can you explain where you're using the event exactly? as in where/when and how you're triggering it? maybe check any other instance where you changed the variable even without the event

**Comment by Joanarr** [comment]
I'm just triggering the event in the chart, the time that it gets triggered is recorded in events.json

**Comment by Joanarr** [comment]
Sometimes it's more likely to crash if the setProperty line is in the song lua, ie different zooms depending on mustHitSection being true or not

**Comment by Joanarr** [comment]
but that still doesn't guarantee anything, it's really inconsistent

**Comment by frantastic24** [comment]
you could try adding `if not inGameOver then`

> I'm just triggering the event in the chart, the time that it gets triggered is recorded in events.json

that doesn't really answer my question

**Comment by Joanarr** [comment]
i think it's just one of those weird problems that's specific to my computer. I think I'll just have to work around it the best I can in the meantime, thanks for for the feedback tho
