### ISSUE TITLE
Is it possible to limit a week and/or song to a certain difficulty within the LUA version of Psych Engine?

### ISSUE THREAD

**Issue by DannybotDev** [ShadowMario/FNF-PsychEngine#8758]
### What is your question?

I think the title is pretty self explanatory. I have a set of charts that are intended to only be played on hard mode. Obviously the game would crash if another difficulty is chosen. Also, I know that this is easy to do via the source code, but I've been slowly moving to the LUA version as I think It's better practice for this engine specifically.

**Comment by frantastic24** [comment]
Check the week editor, there is a field for difficulties

**Comment by DannybotDev** [comment]
Didn't see that haha, thanks for the help I appreciate it!
