### ISSUE TITLE
Change Difficulty menu will crash the game..

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8759]
### Describe your bug here.

Pretty self explanatory...

(The change difficulty in the pause menu btw...)

CAUSES:
- If easy, normal, and hard difficulties are not present in the data folder.
- If you edit the chart in debug mode.
- When it feels like it.

### Command Prompt/Terminal logs (if existing)

```bash
;-;
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing changed.

**Comment by TFLTV** [comment]
you can manually and or get rid of difficulty's by going in the week
editor and writing (difficulty's you want to be here) in the "OTHER" tab
in the week editor

example: Normal, Hard
example 2: Easy, hard
another example for some reason: Normal, Easy

**Comment by ShadowMario** [comment]
Just fucking put your files correctly in the folder already fucking god my christ
