### ISSUE TITLE
How to call a secret song using the Easter egg in the title menu?

### ISSUE THREAD

**Issue by Guranlikesblue** [ShadowMario/FNF-PsychEngine#8761]
### Describe your problem here.

As the title says, I want to know how to call a secret song using an Easter egg.
I also want to open the secret song to the free play menu When you release it.
What should I do?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes. Add character. Add stages and winning icons in PlayState.hx. Add Custom Note in Lua.

**Comment by Guranlikesblue** [comment]
Find another way

**Comment by CheesecakeForever** [comment]
how?

**Comment by Guranlikesblue** [comment]
> how?

Like when playing souls with omnipresent mod v2

**Comment by CheesecakeForever** [comment]
Nvm you can close it, for anyone who wonders, there is code in D-Sides 2.5 source

**Comment by Guranlikesblue** [comment]
> Nvm you can close it, for anyone who wonders, there is code in D-Sides 2.5 source

Thank you for telling me that!!

**Comment by davidfnf** [comment]
can i try it in psych engine 0.6.3?

**Comment by MemeHovy** [comment]
> can i try it in psych engine 0.6.3?

knock yourself out

**Comment by davidfnf** [comment]
wait in what source can i find the code at

**Comment by davidfnf** [comment]
is it tiltle state or what?
