### ISSUE TITLE
FlxVideo has no field start

### ISSUE THREAD

**Issue by BrightEyesFox** [ShadowMario/FNF-PsychEngine#8762]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/91453227/170069585-5f953694-62f9-4100-8212-5a9048349b20.png)
![image](https://user-images.githubusercontent.com/91453227/170069715-6ffa2dae-8624-4270-b895-b7d559651750.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Edited StoryMenuState.hx to make a song select menu

**Comment by Fridox-lol** [comment]
same so i cant help

**Comment by ShadowMario** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/44785097/170141347-1da01227-832f-4901-9135-1fb73f203ea0.png)
That's not how you use it
