### ISSUE TITLE
Song crashes 

### ISSUE THREAD

**Issue by RedMik52** [ShadowMario/FNF-PsychEngine#8763]
### What is your question?

so i'm working on a mod for a while now and today when i tried to play a song, the song carshes.
It's not the game itself because other songs dosen't crash and it isn't the difficulty.

Please help me

**Comment by BrightEyesFox** [comment]
are you using lua or source to make the mod?
did you use an lua script in the song?
is there an error message when it crashes?
if so does it say anything?

you have to provide details, and not just say "my game crashed"

**Comment by RedMik52** [comment]
i use lua and source but the song it's in lua
i just used a credits script but the same script is in all the songs
no it dosen't it just crashes on the first note

**Comment by RedMik52** [comment]
@BrightEyesFox

**Comment by BrightEyesFox** [comment]
> i use lua and source but the song it's in lua
> i just used a credits script but the same script is in all the songs
> no it dosen't it just crashes on the first note

can you send the script then? also try removing the song script and see if the game still crashes

**Comment by RedMik52** [comment]
ok

**Comment by RedMik52** [comment]
the song crashed anyways

**Comment by BrightEyesFox** [comment]
> the song crashed anyways

then idk what your problem is
