### ISSUE TITLE
Custom Lua Sections

### ISSUE THREAD

**Issue by Lorekeeper49** [ShadowMario/FNF-PsychEngine#8767]
### What feature do you want to get added on the **base** engine?

My idea: have 2 dropdowns for each section, one for Boyfriend and one for the opponent, any Lua scripts that we put into the custom_sections folder will show up on both dropdowns unless otherwise stated with a Lua callback maybe named `setSectionDropdown('custom_section', dropdown{0 or 1})`.  This way we can do different things for a section based on the code in the Lua script.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Lorekeeper49** [comment]
> unnecessary as you can just make the script happen on the first beat of that section

But it makes charting things like this less tedious
![image](https://user-images.githubusercontent.com/93066594/170287054-910405be-f042-4d3f-8f21-ad73aea6d139.png)

**Comment by ShadowMario** [comment]
That's not how it works
