### ISSUE TITLE
can you make it so it brings you to a website

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#8769]
### What is your question?

I know this is done with the **credits** _but_
how do you do this in a song? or when you die?

**Comment by PrismLight** [comment]
With source, just do `CoolUtil.browserLoad(link)`. With lua, I don't know.

**Comment by TFLTV** [comment]
@PrismLight 

oh, well thanks
i'll go see if that works
and if not then... idk whats after

**Comment by TFLTV** [comment]
where would I put `CoolUtil.browserLoad(yes, I put the link here don't even ask)`

**Comment by PrismLight** [comment]
You can find `public function endSong():Void` for the end of the song.

**Comment by TFLTV** [comment]
> You can find `public function endSong():Void` for the end of the song.

where do I put the code in CoolUtil.hx? that's what I meant. sorry for the inconvenience

**Comment by PrismLight** [comment]
> > You can find `public function endSong():Void` for the end of the song.
> 
> where do I put the code in CoolUtil.hx? that's what I meant. sorry for the inconvenience

You don't put it in CoolUtil.hx. the reason `CoolUtil.` is in there is because the FUNCTION is from CoolUtil.hx.

**Comment by TFLTV** [comment]
> > > You can find `public function endSong():Void` for the end of the song.
> > 
> > 
> > where do I put the code in CoolUtil.hx? that's what I meant. sorry for the inconvenience
> 
> You don't put it in CoolUtil.hx. the reason `CoolUtil.` is in there is because the FUNCTION is from CoolUtil.hx.

then where do I put it (I do not do Haxe coding I am most experienced with Lua)

**Comment by meeptey2** [comment]
> > > > You can find `public function endSong():Void` for the end of the song.
> > > 
> > > 
> > > where do I put the code in CoolUtil.hx? that's what I meant. sorry for the inconvenience
> > 
> > 
> > You don't put it in CoolUtil.hx. the reason `CoolUtil.` is in there is because the FUNCTION is from CoolUtil.hx.
> 
> then where do I put it (I do not do Haxe coding I am most experienced with Lua)

You'll have to find the related function for what you want to do. For example, if you want to direct the player to the website when they die, put it in `doDeathCheck` in PlayState.hx

**Comment by TFLTV** [comment]
> > > > > You can find `public function endSong():Void` for the end of the song.
> > > > 
> > > > 
> > > > where do I put the code in CoolUtil.hx? that's what I meant. sorry for the inconvenience
> > > 
> > > 
> > > You don't put it in CoolUtil.hx. the reason `CoolUtil.` is in there is because the FUNCTION is from CoolUtil.hx.
> > 
> > 
> > then where do I put it (I do not do Haxe coding I am most experienced with Lua)
> 
> You'll have to find the related function for what you want to do. For example, if you want to direct the player to the website when they die, put it in `doDeathCheck` in PlayState.hx

cool
