### ISSUE TITLE
Error: Uncaught exception on main thread: Invalid field access : nodeType

### ISSUE THREAD

**Issue by Thefrickencrap** [ShadowMario/FNF-PsychEngine#877]
### Describe your problem here.

Error: Uncaught exception on main thread: Invalid field access : nodeType

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

**Comment by DEV-idiotXD** [comment]
boi u put nodetype instead of notetype XD

**Comment by ShadowMario** [comment]
Where???

**Comment by Thefrickencrap** [comment]
where do i put notetype

**Comment by DEV-idiotXD** [comment]
> Where???

it said 

Error: Uncaught exception on main thread: Invalid field access : nodeType

meaning it didnt expect the it to be nodetype u miss spelled it

**Comment by Thefrickencrap** [comment]
i know i just mean where do i respell

**Comment by DEV-idiotXD** [comment]
> i know i just mean where do i respell

it never said in the error the line and which .hx file

**Comment by ShadowMario** [comment]
> > Where???
> 
> it said
> 
> Error: Uncaught exception on main thread: Invalid field access : nodeType
> 
> meaning it didnt expect the it to be nodetype u miss spelled it

Thanks Sherlock, but where did this bug happen????

**Comment by Thefrickencrap** [comment]
dont  know it says it on kade ,ninja, cool, and psych

**Comment by DEV-idiotXD** [comment]
> > > Where???
> > 
> > 
> > it said
> > Error: Uncaught exception on main thread: Invalid field access : nodeType
> > meaning it didnt expect the it to be nodetype u miss spelled it
> 
> Thanks Sherlock, but where did this bug happen????

boi i said it never said where it was

**Comment by ShadowMario** [comment]
This issue is weird as hell and seems to be something that happens only to you, i don't think i can help with that.

**Comment by arandomkid1** [comment]
the nodetype error keeps happening to me and its getting annoying
