### ISSUE TITLE
So I'm making a Song Randomizer-

### ISSUE THREAD

**Issue by Punkinator7** [ShadowMario/FNF-PsychEngine#8770]
### Describe your problem here.

I made a script that goes with an empty song (a song with no inst or voices, just the chart) that sends you to a random song within a list that's defined with an array of strings that contain song names to use with loadSong().
 this song's data folder is in the mods/data folder and any songs within said data folder and the vanilla songs load and work fine. 
But trouble arises (and the main point of this issue) is that I tried to load a song that is inside its own folder (like mods/thatmod/data instead of just mods/data) and it fails to load it, resulting in it staying within the empty song and not doing anything else. Is there a way for me to load a song from something like mods/thatmod/data or is that not possible / implemented? I want it to be able to use any song, regardless of the mod and how it was structured for compatibility sake.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, using 0.5.2h.

**Comment by frantastic24** [comment]
Not possible
