### ISSUE TITLE
GF layering? over on dad sprite

### ISSUE THREAD

**Issue by Den198888** [ShadowMario/FNF-PsychEngine#8775]
### Describe your problem here.

idk how can i make GF on top of dad sprite but when i am using 
setObjectOrder('gf', getObjectOrder('dad') + 1)
it just increased GF sprite FPS for no reason and it didn't go in front of dad 

I don't even know how to do it on Source code

source or lua please help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by impostor5875** [comment]
gfGroup, not just gf

**Comment by Den198888** [comment]
TYSM🥰 it works now thank you :D
