### ISSUE TITLE
Deleting caracters files and mods folders, don't delete them in-game...

### ISSUE THREAD

**Issue by ProtoManoBr** [ShadowMario/FNF-PsychEngine#8776]
### Describe your problem here.

(Unnecessary warning that this text was made with google translator)
I don't know if this fits more in "Bug" or "Help Wanted", but I'll post on this in "Help Wanted" because I think it makes more sense.
I wanted to delete a character files because when I tried to use the character in a song or in the character editor, "null object refence" appeared, so I deleted the .png .xml and .json files, but when I compiled the game, it was still in the character editor, (and obviously, it was still giving the "null object refence" error and closing my game). It also happened to me before with a mod folder. 
I deleted it, but the mod was still in the game. But at least I was able to disable the mod using the "-debug" thing. But I still wanted to know how to permanently remove files and folders from the game, and only reappear in the game when the files are actually in the "example-mods" folder!
Here are some screenshots for you to understand the problem better.
![1](https://user-images.githubusercontent.com/96201772/170291664-37c9c885-8de3-4948-ae31-64eef675655f.png)
![2](https://user-images.githubusercontent.com/96201772/170291668-b38750a5-ef45-44cb-97ec-ac7444b4f150.png)
![3](https://user-images.githubusercontent.com/96201772/170291677-b7af24d2-63e9-4a77-aaf9-15702f887ecf.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not on the main part of the engine, but I changed some files in the Sky Reman. mod folder before deleting it, (2 .json files, 2 .ogg and 1 png). Nothing too important I think.

**Comment by frantastic24** [comment]
Delete them from the export folder

**Comment by TFLTV** [comment]
you have to delete them in the export folder
but this is annoying tbh
