### ISSUE TITLE
How do i enable and disable the game over music during lose cutscenes?

### ISSUE THREAD

**Issue by TaviGamer44** [ShadowMario/FNF-PsychEngine#8777]
### What is your question?

So I have a cutscene for when you lose, and when the cutscene plays it also plays the game over song. I used this code:
`function onGameOver()
          startVideo('video-name-here');
          return Function_Continue;
end`
posted by https://github.com/roaring213 on github.com/ShadowMario/FNF-PsychEngine/issues/8731. 
I am using Lua code placed in the data folder of "test" on the source code. 
the Lua and the video will be in the attached zip folder if you want to use the files for yourself.
Thanks for helping
[v&l.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8772513/v.l.zip)
!

**Comment by AdmiralUsername** [comment]
change the gameover music to a blank *.ogg file using an example lua script in the examples page

**Comment by TFLTV** [comment]
function onCreate()
	setPropertyFromClass('GameOverSubstate', 'loopSoundName', 'gameOver'); --put in mods/music/
	setPropertyFromClass('GameOverSubstate', 'endSoundName', 'gameOverEnd'); --put in mods/music/
end

just make an ogg have no sound or just have the music name as [blank]

**Comment by frantastic24** [comment]
you don't need an empty file, just type a file that doesn't exist

**Comment by TFLTV** [comment]
> you don't need an empty file, just type a file that doesn't exist

thats exactly what I said: "or just have the music name as [blank]" (like in the variable)

**Comment by frantastic24** [comment]
Then why propose having an empty file lying around a

**Comment by TaviGamer44** [comment]
bruh no I need to:
-die
-disable game over music
-play cutscene
-end cutscene
-enable game over music

**Comment by impostor5875** [comment]
playing a cutscene during the game over is possible

but you can't enable or disable the game over music using lua

**Comment by tylerandari12** [comment]
> Then why propose having an empty file lying around

I thought it crashed when an audio file that doesn't exist was played...
