### ISSUE TITLE
Stage that plays a video as a background

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#8779]
### What is your question?

Can I make a stage that plays a video? Like this  https://youtu.be/9b82ZFdm8CQ?t=966

**Comment by ManMaster707** [comment]
You'll need .webm files for that, which are currently not in the engine.

**Comment by TFLTV** [comment]
I **_think_** you can do that with sprite sheets

**Comment by MaybeMaru** [comment]
that would be extremely unoptimised

**Comment by tylerandari12** [comment]
This can't be done at the moment but I think it needs to be an option in the future lol...
