### ISSUE TITLE
IntroText.json in mods folder

### ISSUE THREAD

**Issue by Maxenswel** [ShadowMario/FNF-PsychEngine#8780]
### What feature do you want to get added on the **base** engine?

I would like to add my custom quotes on the intro of my mod, but I'm doing a modpack (you don't have a .exe in it) but we can't. So, I'd be cool if we could put a IntroText.json in the mods folder that works. Thanks !

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ManMaster707** [comment]
IntroText.txt already works, but only on the mod at the top of your "mods" menu

**Comment by tylerandari12** [comment]
> IntroText.txt already works, but only on the mod at the top of your "mods" menu

Does it work the same as Kade Engine?

**Comment by ShadowMario** [comment]
The top mod can do that.
