### ISSUE TITLE
CLOSED CUZ YEA

### ISSUE THREAD

**Issue by MegaMatt2712** [ShadowMario/FNF-PsychEngine#8781]

**Comment by machonessiebaby** [comment]
bro this will not be added till its added to itch.io close this

**Comment by ManMaster707** [comment]
uh oh #2015

**Comment by TFLTV** [comment]
this is cringe

**Comment by PrismLight** [comment]
Shadow is already adding week 7 lol.
Also week 8 is coming soon.
So close this.
Even if it never gets added to itch.

**Comment by CrusherMods** [comment]
imagine not knowing how to see 💀 

![image](https://user-images.githubusercontent.com/90648119/170365245-a248ac5c-6dbd-4954-a365-4a604ced568c.png)

![image](https://user-images.githubusercontent.com/90648119/170365425-7a0c243a-e7eb-4e85-b35c-98dfd4e2c025.png)

**Comment by frantastic24** [comment]
You didn't close it
