### ISSUE TITLE
different visual ratings in songs

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#8782]
### What feature do you want to get added on the **base** engine?

every song has the normal "sick!!" or "good!" and y'know.

### onto the main stuff

what if you can make a custom "sick!!" rating,
then place it in your "data" folder and into your song data folder.
then while playing that song it'll load that .png instead of the default?

and if not, any custom ones... then **don't** try to load those non-existent ones and use the default.

### other things that can be used with this:
- week menu can have the option to do this in the "other" tab if you don't want to manually drag all those in the song data folders or, make the rating, then drop it into images folder and have the name as "sick-(your week name)" (without the quotation marks) to do the same thing
- custom combo numbers
- more customization
- and maybe more, but I ran out of ideas. because I'm not that creative sometimes, and it was one of those times while I was writing this.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
You can mess with rating in lua now

**Comment by TFLTV** [comment]
> You can mess with rating in lua now

oh, sorry lol
