### ISSUE TITLE
Dialogue sounds for specific characters

### ISSUE THREAD

**Issue by AntCrem** [ShadowMario/FNF-PsychEngine#8784]
### Describe your problem here.

Is there a way I can have different voices for different characters instead of having the same sound for all of them?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nu

**Comment by frantastic24** [comment]
Edit the json directly and add the sound field on every line

**Comment by BernardoGP4504** [comment]
edit the `dialogue.json` file and add `"sound": "the sound"` into each talking part you want (if the part already has it, just fill it)

> "the sound"
is the sound you want
