### ISSUE TITLE
Flashing Lights

### ISSUE THREAD

**Issue by Erlicer** [ShadowMario/FNF-PsychEngine#8788]
### Describe your problem here.

is there any way to make flashing Lights appear only if the flashing Lights option is activated?.-. like "getPropertyFromClass('ClientPrefs', 'flashingLights') == true" ?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Meme1079** [comment]
try this

```lua
function onUpdate() 
    if flashingLights == true then
        debugPrint('did it work?')
    end    
end
```

**Comment by PrismLight** [comment]
on update hat the heck?

**Comment by frantastic24** [comment]
```lua
if flashingLights then

end
```

**Comment by Erlicer** [comment]
> try this
> 
> ```lua
> function onCreatePost()
>     if getPropertyFromClass('ClientPrefs', 'flashing') == true then
>         debugPrint('did it work?')
>     end    
> end
> ```

Nope

**Comment by Erlicer** [comment]
Yeah, thanks

**Comment by Erlicer** [comment]
Nope
