### ISSUE TITLE
"converting"

### ISSUE THREAD

**Issue by SAB236YT** [ShadowMario/FNF-PsychEngine#8789]
### What is your question?

how do i turn this from lua to source?

`function onCreatePost()
    makeLuaText('hits', 'Pentagon: ' .. getProperty('songHits'), 200, 0, 350);
    makeLuaText('sicks', 'Rectangles: ' .. getProperty('sicks'), 200, 0, 375);
    makeLuaText('goods', 'Triangles: ' .. getProperty('goods'), 200, 0, 400);
    makeLuaText('bads', 'Squares: ' .. getProperty('bads'), 200, 0, 425);
    makeLuaText('shits', 'Circles: ' .. getProperty('shits'), 200, 0, 450);
    addLuaText('hits');
    addLuaText('sicks');
    addLuaText('goods');
    addLuaText('bads');
    addLuaText('shits');
end

function onRecalculateRating()
    setTextString('hits', 'Pentagon: ' .. getProperty('songHits'));
    setTextString('sicks', 'Rectangles: ' .. getProperty('sicks'));
    setTextString('goods', 'Triangles: ' .. getProperty('goods'));
    setTextString('bads', 'Squares: ' .. getProperty('bads'));
    setTextString('shits', 'Circles: ' .. getProperty('shits'));
end`

**Comment by PrismLight** [comment]
FunkinLua.hx

**Comment by SAB236YT** [comment]
> FunkinLua.hx

wdym? i men like in playstate.hx

**Comment by PrismLight** [comment]
> > FunkinLua.hx
> 
> wdym? i men like in playstate.hx

look at funkin lua and match the lua functions with the ones in funkin lua.

**Comment by the-funky-lad** [comment]
> > > FunkinLua.hx
> > 
> > 
> > wdym? i men like in playstate.hx
> 
> look at funkin lua and match the lua functions with the ones in funkin lua.

look, hes asking on how to make lua code into source code
