### ISSUE TITLE
Error When Playing Week 7 

### ISSUE THREAD

**Issue by Gibberditoslumber** [ShadowMario/FNF-PsychEngine#8791]
### Describe your bug here.

so i was playing week 7 when all of the sudden when it tried to load Stress It Crashed 

### Command Prompt/Terminal logs (if existing)

```bash
source/Discord.hx:68: Discord Client initialized
source/Discord.hx:18: Discord Client starting...
source/Discord.hx:25: Discord Client started.
source/LoadingState.hx:162: Setting asset folder to week7
source/Conductor.hx:75: new BPM map BUDDY []
source/PlayState.hx:3649: LOADING NEXT SONG
source/PlayState.hx:3650: guns-hard
source/LoadingState.hx:162: Setting asset folder to week7
source/Conductor.hx:75: new BPM map BUDDY []
source/Conductor.hx:75: new BPM map BUDDY []
source/PlayState.hx:3649: LOADING NEXT SONG
source/PlayState.hx:3650: stress-hard
source/LoadingState.hx:162: Setting asset folder to week7
source/Conductor.hx:75: new BPM map BUDDY []
source/animateatlas/AtlasFrameMaker.hx:65: Creating: [Pico Badass]
Killed
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

None

**Comment by Gibberditoslumber** [comment]
tried agian crashed

**Comment by Gibberditoslumber** [comment]
so it's not a one time thing

**Comment by Luc4s-adv** [comment]
You have Low ram, The Cutcenes (mainly from Stress) contain huge and heavy sprites sheet Mainly the tankman and GF sprites but stress cutscenes, not to mention of course the character sprites themselves, The solution I give you is if you are using source code, remove the cutcenes programming and replace it with a video version of it, or just change the sprites to lighter sprites (or if you have Adobe animate, export the sprites in bitmaps as was done with pico in the stress cutcenes) 💀

**Comment by Gibberditoslumber** [comment]
no i don't have low ram i have a gaming pc it has linux

**Comment by Gibberditoslumber** [comment]
and also i cant replace it with video because playing videos on linux wont work

**Comment by Luc4s-adv** [comment]
hmm, well then it complicates, maybe something in the source code is not compatible with your pc anyway, well, can you play stress for freeplay?, If yes, then maybe it's ram memory, Week 7 is the Week that consumes the most ram among the other 6

**Comment by BeastlyGhost** [comment]
since 0.5.3 is a beta, this might be an issue with the atlas themselves, which, just try it again and it should work properly, i haven't ran into this issue while running it on linux

that, or download the engine again from the latest commit, hope it helps

**Comment by Gibberditoslumber** [comment]
> since 0.5.3 is a beta, this might be an issue with the atlas themselves, which, just try it again and it should work properly, i haven't ran into this issue while running it on linux
> 
> that, or download the engine again from the latest commit, hope it helps

*Sigh* I'm Using 0.5.2h
