### ISSUE TITLE
pause screen audio bug

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#8792]
### Describe your bug here.

audio in psych engine for the audio freaks out sometimes (this is the first time its happened to me

https://user-images.githubusercontent.com/56323671/170604183-19ee12d5-954e-4f98-892b-2ca501eee199.mp4

)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

sound changes and 2 custom achievements, 4 custom credits playstate.hx titlestate.hx main.hx healthicon.hx  a LOT MORE

**Comment by ShadowMario** [comment]
Very likely caused by your PlayState change
