### ISSUE TITLE
Linux build crashes

### ISSUE THREAD

**Issue by Teuxml** [ShadowMario/FNF-PsychEngine#8793]
### Describe your bug here.

My linux build (no errors or extra warnings, no changed code) crashes whenever I try to save or play a chart after going on debug mode

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by tylerandari12** [comment]
I heard Linux was an experimental thing...
However I'm also experiencing multiple debug mode issues so you're not the only one...

**Comment by BeastlyGhost** [comment]
> I heard Linux was an experimental thing... However I'm also experiencing multiple debug mode issues so you're not the only one...

no, linux is not experimental, and in fact the charting menu has a bit of a problem with memory usage which has been fixed a while ago, I'd either wait for the update or download the newest one from [here](https://github.com/ShadowMario/FNF-PsychEngine/actions)
