### ISSUE TITLE
An Event so that the Opponent and GF sing at the same time

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#8795]
### Describe your problem here.

Title says it all mate.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, External Mod Folder.

**Comment by smg2fromdiscord** [comment]
https://drive.google.com/file/d/16fMJvtZMGiBv3useM7cEnOqJ-o4Ah142/view?usp=sharing
here ya go man

**Comment by fnfdemonboi314159** [comment]
> https://drive.google.com/file/d/16fMJvtZMGiBv3useM7cEnOqJ-o4Ah142/view?usp=sharing here ya go man put it in custom_notetypes

Thanks man!
