### ISSUE TITLE
How to change the noteskin on mid-song? is it needs lua?

### ISSUE THREAD

**Issue by ZakyFerdian** [ShadowMario/FNF-PsychEngine#8797]
### Describe your problem here.

Hi, i always wondering if i could change the noteskin mid-song, does it need lua? If you have one can you send it? 

-ZakyFerdian 🙏

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No i didn't, i don't even know how to edit those.

**Comment by ZakyFerdian** [comment]
Anyone who have answer pls tell me, i needed it for my song

**Comment by smg2fromdiscord** [comment]
yes, it is infact possible to change noteskins during songs and yes there is a lua script for it. https://drive.google.com/file/d/1ZanXokVMDsqdLRuwYtCvCMuy-sotJ3dZ/view?usp=sharing
this is a google drive file that i uploaded with all the things you can do with changing notetypes
theres 3 different versions, one for only bf, one for only the opponent, and one for changing both sides.
instructions on how to use them should be in there txt files.
hope this helped!

**Comment by ZakyFerdian** [comment]
Thank You! Hope God bless you!

**Comment by ZakyFerdian** [comment]
Thank You!
