### ISSUE TITLE
changing healthbars length

### ISSUE THREAD

**Issue by smg2fromdiscord** [ShadowMario/FNF-PsychEngine#8798]
### Describe your problem here.

Is there a way to change the healthbars length going into a song using lua? im just wondering as i need it for a mod

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i have only added characters.

**Comment by FlintIshe** [comment]
setProperty('healthBar.scale.x', 2)

**Comment by smg2fromdiscord** [comment]
do you possibly know how to make the health go past its original health? (like make it balanced with the healthbar)

**Comment by FlintIshe** [comment]
> do you possibly know how to make the health go past its original health? (like make it balanced with the healthbar)

Nope

**Comment by Wither362** [comment]
> do you possibly know how to make the health go past its original health? (like make it balanced with the healthbar)

What do you mean with that, because you can use `setProperty('healthBar.scale.x', 1)`, or you can use:
```lua
if(getProperty('health') > value) then
  setProperty('health', maxHealth)
end
```
(Note, if you use the second code, replace `value` by the maximum health, and replace `maxHealth` by the maximum health
