### ISSUE TITLE
2nd character plays an animation

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#8799]
### Describe your problem here.

Alright i have this bug here for a long time and it's: I wanna add secondary character's where they work on both sides (boyfriend and dad sides) and where they can play animations using an event but, nothing works. I REALLY need help on this

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Lorekeeper49** [comment]
```lua
function onEvent(n, v1, v2)
    if n == 'Object Play Animation' then
        objectPlayAnimation(v1, v2, true);
    end
end

**Comment by WilliamGaming12** [comment]
> ```lua
> function onEvent(n, v1, v2)
>     if n == 'Object Play Animation' then
>         objectPlayAnimation(v1, v2, true);
>     end
> end
> ```

By some reason, the animation keeps playing, maybe it's because I'm using this script: 
https://www.youtube.com/watch?v=zyT9gWKwOi4&t=202s
