### ISSUE TITLE
Found a Mind Games leftover

### ISSUE THREAD

**Issue by FuseIsHere813** [ShadowMario/FNF-PsychEngine#88]
A "Psy_Dialogue" was found in the flies, not sure if this is needed for example of a dialogue.

**Comment by YumDev12** [comment]
I Think Its From The Vs Psy Mod Beacuse I Think The Engine Is That Mod

**Comment by YumDev12** [comment]
I Dont Know If Its Needed

**Comment by ShadowMario** [comment]
It is a leftover yeah, but that's because i didn't made a Dad Dialogue portrait yet
