### ISSUE TITLE
How do i make animated backgrounds?

### ISSUE THREAD

**Issue by Plotsh** [ShadowMario/FNF-PsychEngine#8801]
### What is your question?

Im recreating comrade distant memories and idk how to make the background animated, it just stays static. Someone knows a script or smth to make it animated? moving like in "soda disco funk" song

heres the screenshot with the static bg
![Screenshot_20220527-115148](https://user-images.githubusercontent.com/84821153/170743804-51cdcec2-626f-4fbc-bfd0-e059c6194252.png)

**Comment by Plotsh** [comment]
i meant like, it moves like in soda disco funk song

**Comment by Lorekeeper49** [comment]
> i meant like, it moves like in soda disco funk song

Tweens

**Comment by WilliamGaming12** [comment]
If you mean with Loops, then search on youtube idk lmao. I saw some tutorials 'bout it

**Comment by Plotsh** [comment]
yea imma try

**Comment by BendyGaming0** [comment]
change the position of the background each frame (remember to multiply by elapsed) and apply the modulo operator to get the remainder of a division therefore looping the position in a certain range (if the start position is positive there are some more math things) here's a code example:

`function onCreate()
    makeLuaSprite('example', 'example', 100, 100)
    addLuaSprite('example') --you should probably have a second loop sprite
end

function onUpdate( elapsed )
    setProperty('example.y', getProperty('example.y') + 100*elapsed)
    setProperty('example.y', clampNum(-100, 1000, getProperty('example.y')))
end

function clampNum(min, max, num)
   return ((num - min) % (max - min)) + min
end`
