### ISSUE TITLE
How to get which note arrows are where... (not strums)

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8802]
### What is your question?

So I'm iterating over all the notes with...

```
for i = 0, getProperty("unspawnNotes.length")-1 do
	setPropertyFromGroup("unspawnNotes", i, "offsetAngle", 180)
	setPropertyFromGroup("unspawnNotes", i, "offsetX", 60)
end
```
...and I wanna know what the variable would be to check if the arrow is being hit by the opponent...
(You know, with `getPropertyFromGroup("unspawnNotes", i, "<something>")`)

**Comment by tylerandari12** [comment]
I'll also take what strum line the arrow is on if you can only get that...

**Comment by frantastic24** [comment]
`mustPress`

**Comment by BrightEyesFox** [comment]
> `mustPress`

guh???

**Comment by frantastic24** [comment]
?

**Comment by tylerandari12** [comment]
> `mustPress`

What's that supposed to do?

**Comment by frantastic24** [comment]
What you asked ??
> check if the arrow is being hit by the opponent...

**Comment by frantastic24** [comment]
That is how it works, unless you meant the note *was hit* by the opponent for some reason?
There is a custom note script on the wiki you can check to see this is how it works
