### ISSUE TITLE
How do i quit og credit icons??

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#8803]
### What is your question?

So what i wanna do is, quit the Main credits that appears on the credits
If you don't know what I'm talking about, I'm refering to this (and the icons below)
![Captura de pantalla (54)](https://user-images.githubusercontent.com/102251392/170757965-b3fb3442-9139-4aae-b660-9aa7217835ca.png)

**Comment by frantastic24** [comment]
No

**Comment by WilliamGaming12** [comment]
> No

No 👍

**Comment by tylerandari12** [comment]
If you mean add them in then [head to the bottom of this](https://github.com/ShadowMario/FNF-PsychEngine/wiki).

If you mean remove them then that's kinda impossible...

> > No
> 
> No :+1:

No :+1: :+1:

**Comment by Wither362** [comment]
> > No
> 
> No 👍

Don’t do it, if you use Psych Engine, you credit Psych Engine creators.
Only… NO

**Comment by WilliamGaming12** [comment]
ok folks, as you say.

**Comment by Wither362** [comment]
> ok folks, as you say.

But if you want to put your credits, go [here: https://github.com/ShadowMario/FNF-PsychEngine/wiki#q-how-can-i-create-a-custom-credits](https://github.com/ShadowMario/FNF-PsychEngine/wiki#q-how-can-i-create-a-custom-credits)
