### ISSUE TITLE
How to find OG events

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#8804]
### Describe your problem here.

I wanna find the code n' stuff for the built in psych engine events 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just modded in the "example_mods" folder

**Comment by frantastic24** [comment]
look up their names in PlayState

**Comment by TFLTV** [comment]
> look up their names in PlayState

cool
