### ISSUE TITLE
How to use isColliding

### ISSUE THREAD

**Issue by ArthurYago** [ShadowMario/FNF-PsychEngine#8805]
### Describe your problem here.

I've seen something in the 0.5.1 update, they added isColliding, but i don't know what is it and how to use it, i really wanna know.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by NS-Unfair** [comment]
Where did you find this variable? I can't find it in the source code.

**Comment by frantastic24** [comment]
It was changed to `objectsOverlap` not long ago
It does as it says, check if objects overlap
```lua
objectsOverlap('obj1', 'obj2')
```

**Comment by ArthurYago** [comment]
ok

**Comment by tylerandari12** [comment]
Useful :O
