### ISSUE TITLE
Text Outlines

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#8806]
### What is your question?

How do i make the borders of a text THICCer?
Like this:
![Captura de pantalla (55)](https://user-images.githubusercontent.com/102251392/170771088-df8a372f-c864-4c9c-a63d-e476bf9049f0.png)

**Comment by Lorekeeper49** [comment]
```lua
setTextBorder('tag', border{int});

**Comment by WilliamGaming12** [comment]
> ```lua
> setTextBorder('tag', border{int});
> ```

how does that work? like i dont know how do use it

**Comment by PrismLight** [comment]
> > ```lua
> > setTextBorder('tag', border{int});
> > ```
> 
> how does that work? like i dont know how do use it

`border(int)` should be replace with a whole number.
