### ISSUE TITLE
Song audio not loading

### ISSUE THREAD

**Issue by imalink100** [ShadowMario/FNF-PsychEngine#8807]
### Describe your bug here.

The song audio isn't loading. I remembered to put "Inst.ogg" and "Voices.ogg". Instead of loading the audio, it is silent while just repeating the first 0.1 seconds of the chart.
![image](https://user-images.githubusercontent.com/106406304/170780719-7aef7d9b-377d-46e6-8e4d-cf011036f590.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Broken files, re-export them

**Comment by imalink100** [comment]
Ok, i'll try

**Comment by imalink100** [comment]
It works! Thanks.
