### ISSUE TITLE
Entering difficulty menu crashes game

### ISSUE THREAD

**Issue by NS-Unfair** [ShadowMario/FNF-PsychEngine#8808]
### Describe your bug here.

I don't have any info on this bug other than the game crashes.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I have made no changes to the build

**Comment by NS-Unfair** [comment]
I have found out this only happens when you go into charting mode

**Comment by Wither362** [comment]
How many difficulties does it have?

**Comment by tylerandari12** [comment]
I made a similar post about this and Shadow Mario himself said...

"Just fix Youre files for crying out loud."

**Comment by SnakDev** [comment]
If you go from the mod menu to chart editor and open like that it's not going to work because it looks for the normal chart
If you are loading chart editor from a song then it has to be the same difficulty
