### ISSUE TITLE
How do I make a rotating background in Lua?

### ISSUE THREAD

**Issue by NesDoesGithub** [ShadowMario/FNF-PsychEngine#8809]
### Describe your problem here.

How do I make a rotating background like this in Lua? (Disassambler from VS. Shaggy v2.5) 
https://youtu.be/7OFw9WPhox4?t=102

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by frantastic24** [comment]
that's not rotating the background, it's rotating the game camera
[read tween and timers](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers#notetweenangletagstring-noteint-valuedynamic-durationfloat-easestring)

**Comment by NesDoesGithub** [comment]
> 

yes, i figured that out, although i don't know how to make it rotate left and right on beat.

i tried this code but it didn't work
```
function onBeatHit()
    if curBeat % 4 == 1 then
        doTweenAngle('camerathing', 'camera', 10, 1, 'linear')
    end
    
    if curBeat % 2 == 2 then
        doTweenAngle('camerathing', 'camera', -10, 1, 'linear')
    end
end
```

**Comment by frantastic24** [comment]
Probably something like this idk
```lua
if curBeat % 4 == 2 then
     doTweenAngle('camerathing', 'camGame', 10, crochet/1000, 'linear') --probably change ease
elseif curBeat % 4 == 0 then
     doTweenAngle('camerathing', 'camGame', -10, crochet/1000, 'linear')
end
```

**Comment by tylerandari12** [comment]
Ima make a way without tweens lol...
Very ineficient but it was fun...

```
local Speed = 0.05 -- adds up quick
local angle = 5

-- cam be `Game`, `HUD`, or `Other`
-- there can be multiple cameras
local cameras = {"Game"}

local Radians = 0

function onUpdate()
	Radians = Radians + Speed -- add some speed

	for i, v in pairs(cameras) do
		setProperty("cam"..v..".angle", math.sin(Radians) * angle)
	end
end
```
