### ISSUE TITLE
Can't Load File

### ISSUE THREAD

**Issue by PizzamemesYT** [ShadowMario/FNF-PsychEngine#8810]
### Describe your bug here.

Whenever I try to load/extract the source code it will say "Windows Cannot Open This Folder", and talks about how the file is invalid, is there any way you can help me fix this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by machonessiebaby** [comment]
picture?
