### ISSUE TITLE
Compiling Psych Error: source/Main.hx:18: characters 37-47 : Module TitleState does not define type TitleState

### ISSUE THREAD

**Issue by TheRedperson** [ShadowMario/FNF-PsychEngine#8811]
### Describe your bug here.

If I try compiling the game I get this error:
source/Main.hx:18: characters 37-47 : Module TitleState does not define type TitleState
NOTE: I have not edited this file, I have only edited Project.XML.

### Command Prompt/Terminal logs (if existing)

```bash
source/Main.hx:18: characters 37-47 : Module TitleState does not define type TitleState
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only Project.XML

**Comment by BeastlyGhost** [comment]
go to TitleState.hx and change the name after "class" to "TitleState"

**Comment by TheRedperson** [comment]
gives the same error :/

**Comment by Wither362** [comment]
Can you show `TitleState.hx` and `Main.hx`?

**Comment by Wither362** [comment]
Can you show the `Project.xml` file please?
