### ISSUE TITLE
how can i create this effect? (Lua)

### ISSUE THREAD

**Issue by AssasinShadows** [ShadowMario/FNF-PsychEngine#8812]
### Describe your problem here.

https://www.youtube.com/watch?v=4-JejI1syyo How can I do that chromatic effect when the enemy presses a note?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by BrightEyesFox** [comment]
the vocal effect is in the song, fnf cant edit the audio

**Comment by AssasinShadows** [comment]
> the vocal effect is in the song, fnf cant edit the audio

i mean the chromatic aberration effect when the opponent presses a note

**Comment by tylerandari12** [comment]
He wants the screen glitching. (which I have no clue how to do) :(

It might be a shaders thing...

**Comment by BrightEyesFox** [comment]
oh ok then its probably a shader, cant help ya there

**Comment by ShadowMario** [comment]
You can't.

**Comment by ActualeAnEggDog** [comment]
i think
onopponentnotehit()
      addchromaticabberationeffect(camHUD,2.2)
