### ISSUE TITLE
How can I change the offsets of Story Menu's week image?

### ISSUE THREAD

**Issue by 18JARD** [ShadowMario/FNF-PsychEngine#8813]
### What is your question?

I am trying to put the image of "Week M" on the top center of the screen

![Screenshot (104)](https://user-images.githubusercontent.com/104999939/170809194-235a1584-e2a9-4b27-9334-e5c0d1e5971d.png)

How can I do this via source code (Using Psych Engine 0.5.2)?

**Comment by FlintIshe** [comment]
Go StoryMenuState and find weekThing.x 

under weekThing.x type weekThing.offset.y += value;


(may be)

**Comment by 18JARD** [comment]
I actually used weekThing.offset.y += 420; . Thanks!
