### ISSUE TITLE
How to play vedio cutscene after a dialog(LUA)?

### ISSUE THREAD

**Issue by MOON-on-GitHub** [ShadowMario/FNF-PsychEngine#8817]
### What is your question?

How to play vedio cutscene after a dialog with LUA file?

Like Screenplay(AGOTI mod)
↓↓ Like This ↓↓
https://youtu.be/y1djhkvbk_I

**Comment by machonessiebaby** [comment]
local allowCountdown = false;
local playDialogue = false;
function onStartCountdown()
    -- Block the first countdown and start a timer of 0.8 seconds to play the dialogue
    if not allowCountdown and not seenCutscene then
        startVideo('.mp4 file name');
        allowCountdown = true;
        playDialogue = true;
        return Function_Stop;
end
if playDialogue then
        setProperty('inCutscene', true);
        runTimer('startDialogue', 0.8);
  startDialogue('JsonFileName', 'SongNamefortext');
        playDialogue = true;
        return Function_Stop;
    end
    return Function_Continue;
end


function onTimerCompleted(tag, loops, loopsLeft)
    if tag == 'startDialogue' then -- Timer completed, play dialogue
        startDialogue('JsonFileName', 'SongNamefortext');
    end
end

**Comment by MOON-on-GitHub** [comment]
> 

I mean, the dialog is first and video cutscene is second.
