### ISSUE TITLE
Menu wont freaking move

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#8818]
### Describe your problem here.

i have been trying to get the menu to move for a while now but whatever i put
its still centered

Game:
![image](https://user-images.githubusercontent.com/56323671/170826952-cb43a04e-672f-4ab9-ac16-0a6975150008.png)

code:

![image](https://user-images.githubusercontent.com/56323671/170826981-ecf0cc2c-2b2c-4411-86f2-10b1012cabeb.png)

2nd try:

![image](https://user-images.githubusercontent.com/56323671/170827016-ab8de741-ddd6-4704-8023-58bfeb0f3635.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

sound changes and 2 custom achievements, 4 custom credits playstate.hx titlestate.hx main.hx healthicon.hx  a LOT MORE

**Comment by PrismLight** [comment]
Try re-adding the `screenCenter(X);` line.

**Comment by machonessiebaby** [comment]
> Try re-adding the `screenCenter(X);` line.

well my mod entirly broke :( so i cant test this

**Comment by machonessiebaby** [comment]
> Try re-adding the `screenCenter(X);` line.

Still is stuck in center @PrismLight 

![image](https://user-images.githubusercontent.com/56323671/170842606-0b625799-4893-444e-b4ef-a0392624a1ff.png)


or is it 250?

**Comment by FlintIshe** [comment]
may be remove the screenCenter(X) if you're trying to move it to the right or left

**Comment by 18JARD** [comment]
> > Try re-adding the `screenCenter(X);` line.
> 
> Still is stuck in center @PrismLight
> 
> ![image](https://user-images.githubusercontent.com/56323671/170842606-0b625799-4893-444e-b4ef-a0392624a1ff.png)
> 
> or is it 250?

Delete menuItem.screenCenter(X) or else it will always stay on center.

**Comment by PrismLight** [comment]
Maybe do -= to make sure it changes.

**Comment by machonessiebaby** [comment]
> Maybe do -= to make sure it changes.

wont work
