### ISSUE TITLE
skipcountdown bugs out first section of the chart

### ISSUE THREAD

**Issue by ColdVee** [ShadowMario/FNF-PsychEngine#8821]
### Describe your bug here.

turning on skip countdown fucks up the first half of the first section, the notes get removed for some raeson and i cant do anything about it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

didn't touch anything, its all lua

**Comment by tylerandari12** [comment]
I forgot that property existed lol...

**Comment by ShadowMario** [comment]
Fixed! Thank you for spotting this dumb mistake i've done.
