### ISSUE TITLE
spawnNoteSplash errpr

### ISSUE THREAD

**Issue by TonyTimee** [ShadowMario/FNF-PsychEngine#8823]
### Describe your bug here.

when i went to compile it gave me a error about spawnNoteSplashes.
i did not edit the function
so i dont know what is wrong

### Command Prompt/Terminal logs (if existing)

```bash
source/PlayState.hx:3962: characters 2-8 : Expected }
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited PlayState.hx to add some features i want for my mod (stages, winning icons, shaders, health drain, etc)

**Comment by frantastic24** [comment]
Missing } to close a function, the error explicitly says it

**Comment by TonyTimee** [comment]
> Missing } to close a function, the error explicitly says it

![image](https://user-images.githubusercontent.com/88756260/170836082-09ed553a-3682-4d98-b4bd-3ed65e5cc625.png)
it doesnt look like its not missing }

**Comment by frantastic24** [comment]
It's probably one of the functions above it

**Comment by TonyTimee** [comment]
> It's probably one of the functions above it Idk what you edited but go through those edits again

nvm it was the camera movement script i tried to hard code

**Comment by frantastic24** [comment]
This can be closed then
