### ISSUE TITLE
Default Cam Zoom

### ISSUE THREAD

**Issue by anotheralone** [ShadowMario/FNF-PsychEngine#8824]
### Describe your problem here.

Well, I'll start with details, I'm using VERSION 0.4.2, since I did most of the content there, but anyway, I'm trying to put the default Zoom that occurs during FNF songs, which occur on a certain beat of the song, but I can't find anything that helps me add Zoom MANUALLY.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I changed most of the Engine's PlayState.hx Layout, but I didn't get to mess with Zoom contents, I removed "if (SONG == anysong)" to not get disorganized.

**Comment by BeastlyGhost** [comment]
search for function stepHit()

then add this
```
if (curStep = AAA && SONG.song.toLowerCase() == 'ZZZ')
{
    defaultCamZoom = B.B;
}
```
change ZZZ to a valid song
change AAA to a valid curStep (you can take a look at that with the chart editor or haxe's debug menu
change B.B to a valid value for zooming

**Comment by anotheralone** [comment]
`source/PlayState.hx:2972: characters 23-66 : Int should be Bool
source/PlayState.hx:2972: characters 13-66 : Bool should be Int
source/PlayState.hx:2972: lines 2972-2975 : Int should be Bool`

----

`        if (curStep = 12 && SONG.song.toLowerCase() == 'Tutorial')
        {
            defaultCamZoom = 0.8;
        }`

**Comment by BeastlyGhost** [comment]
> ```
> source/PlayState.hx:2972: characters 23-66 : Int should be Bool
> 
> source/PlayState.hx:2972: characters 13-66 : Bool should be Int
> 
> source/PlayState.hx:2972: lines 2972-2975 : Int should be Bool
> ```
> 
> ```
>         if (curStep = 12 && SONG.song.toLowerCase() == 'Tutorial')
>         {
>             defaultCamZoom = 0.8;
>         }
> ```

curStep **==** 12
defaultCamZoom **==** 0.8

**Comment by ShadowMario** [comment]
> ```
> source/PlayState.hx:2972: characters 23-66 : Int should be Bool
> 
> source/PlayState.hx:2972: characters 13-66 : Bool should be Int
> 
> source/PlayState.hx:2972: lines 2972-2975 : Int should be Bool
> ```
> 
> ```
>         if (curStep = 12 && SONG.song.toLowerCase() == 'Tutorial')
>         {
>             defaultCamZoom = 0.8;
>         }
> ```

```haxe
if (curStep == 12 && SONG.song == 'Tutorial')
{
        defaultCamZoom = 0.8;
}
```

There.
