### ISSUE TITLE
how the hell to scale opponent

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#8826]
### Describe your problem here.

how do you scale the opponent I tried this:
`	doTweenX('dadScaleTweenX', 'dad.scale', 0.5, 0.001, 'elasticInOut')
	doTweenY('dadScaleTweenY', 'dad.scale', 0.8, 0.001, 'elasticInOut')
	onTweenCompleted('dadScaleTweenX')
	onTweenCompleted('dadScaleTweenY')`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just modded in the "example_mods" folder

**Comment by frantastic24** [comment]
Stop using tweens for everything challenge failed
```
function onCreatePost()
     scaleObject('dad', scaleX, scaleY)
end
```
That's also not how onTweenCompleted works

**Comment by TFLTV** [comment]
> function onCreatePost()
>      scaleObject('dad', scaleX, scaleY)
> end

cool it worked
