### ISSUE TITLE
How To Compile Source Code?

### ISSUE THREAD

**Issue by StefanBETA** [ShadowMario/FNF-PsychEngine#8830]
### What is your question?

How You Can Compile Source Code On Mobile?
Can You Active,I Just Wanna Want To Compile The Source Code ;(.

**Comment by Wither362** [comment]
You can’t, only in computer

**Comment by Gabriel2019rsAlt** [comment]
Make sure you have Github and Actions enabled. Just go to settings Actions and enable all actions.

**Comment by Wither362** [comment]
In `settings/actions/general`

**Comment by ShadowMario** [comment]
Android/iOS doesn't have official support.
