### ISSUE TITLE
Use of large table crashes the game.

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8831]
### Describe your bug here.

I think this is a Haxe issue but I'll make a post to let you know...
This isn't the first time this has happened...

So I'm making a script to flip the arrow positions and put the opponent on the player's side and vice versa...

However it crashes at the tables...

```
function onCreatePost()

	local X = {defaultOpponentStrumX0, defaultOpponentStrumX1, defaultOpponentStrumX2, defaultOpponentStrumX3, defaultplayerStrumX0, defaultplayerStrumX1, defaultplayerStrumX2, defaultplayerStrumX3}
	local Y = {defaultOpponentStrumY0, defaultOpponentStrumY1, defaultOpponentStrumY2, defaultOpponentStrumY3, defaultplayerStrumY0, defaultplayerStrumY1, defaultplayerStrumY2, defaultplayerStrumY3}

	for i = 0, 3 do
		setPropertyFromGroup("opponentStrums", i,  "x", X[i + 1])
		setPropertyFromGroup("opponentStrums", i,  "y", Y[i + 1])
	end
	for i = 0, 3 do
		setPropertyFromGroup("playerStrums", i, "x", X[i + 5])
		setPropertyFromGroup("playerStrums", i, "y", Y[i + 5])
	end
end
```

### Command Prompt/Terminal logs (if existing)

```bash
None. It just crashed...
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing changed.

**Comment by Meme1079** [comment]
No lol having a large table wouldn't effect it, but this is affecting it >> `X[i + 1]` << don't put any alphabet except if its a global or local variable

```lua
function onCreatePost()
	local Xdad = {defaultOpponentStrumX0, defaultOpponentStrumX1, defaultOpponentStrumX2, defaultOpponentStrumX3} 
	local Ydad = {defaultOpponentStrumY0, defaultOpponentStrumY1, defaultOpponentStrumY2, defaultOpponentStrumY3} 

        local Xbf = {defaultplayerStrumX0, defaultplayerStrumX1, defaultplayerStrumX2, defaultplayerStrumX3}
        local Ybf = {defaultplayerStrumY0, defaultplayerStrumY1, defaultplayerStrumY2, defaultplayerStrumY3}

	for i = 0, 3 do
		setPropertyFromGroup("opponentStrums", i,  "x", i + Xdad[1])
		setPropertyFromGroup("opponentStrums", i,  "y", i + Ydad[1])
	end
	for i = 0, 3 do
		setPropertyFromGroup("playerStrums", i, "x", i + Xbf[1])
		setPropertyFromGroup("playerStrums", i, "y", i + Ybf[1])
	end
end
```

**Comment by tylerandari12** [comment]
> No lol having a large table wouldn't effect it, but this is affecting it >> `X[i + 1]` << don't put any alphabet except if its a global or local variable
> 
> ```lua
> function onCreatePost()
> 	local Xdad = {defaultOpponentStrumX0, defaultOpponentStrumX1, defaultOpponentStrumX2, defaultOpponentStrumX3} 
> 	local Ydad = {defaultOpponentStrumY0, defaultOpponentStrumY1, defaultOpponentStrumY2, defaultOpponentStrumY3} 
> 
>         local Xbf = {defaultplayerStrumX0, defaultplayerStrumX1, defaultplayerStrumX2, defaultplayerStrumX3}
>         local Ybf = {defaultplayerStrumY0, defaultplayerStrumY1, defaultplayerStrumY2, defaultplayerStrumY3}
> 
> 	for i = 0, 3 do
> 		setPropertyFromGroup("opponentStrums", i,  "x", i + Xdad[1])
> 		setPropertyFromGroup("opponentStrums", i,  "y", i + Ydad[1])
> 	end
> 	for i = 0, 3 do
> 		setPropertyFromGroup("playerStrums", i, "x", i + Xbf[1])
> 		setPropertyFromGroup("playerStrums", i, "y", i + Ybf[1])
> 	end
> end
> ```

Smort

**Comment by tylerandari12** [comment]
UPDATE: It didnt move the arrows but it also didnt crash...
