### ISSUE TITLE
Animation before Countdown 

### ISSUE THREAD

**Issue by StickMation** [ShadowMario/FNF-PsychEngine#8832]
### Describe your problem here.

So im trying to add where once the countdown starts a bf animation plays then goes back to his idle, anyone know how to do that?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited the title and play state just to move the menu and title screen, everything is the same

**Comment by Lorekeeper49** [comment]
```lua
function onStartCountdown()
    --code
end

**Comment by MOON-on-GitHub** [comment]
If you mean Vedio Cutscene,

```
local allowCountdown = false
function onStartCountdown()
	if not allowCountdown and isStoryMode and not seenCutscene then --Block the first countdown
		startVideo('putyourmp4videonamehere');
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end
```

**Comment by StickMation** [comment]
> ```lua
> function onStartCountdown()
>     --code
> end
> ```

yeah uhhh...can i tried to add this and it didnt work. it either shows an error or just doesnt work

**Comment by StickMation** [comment]
wait nvm i got it working
