### ISSUE TITLE
End Song cutscene only play for 1 sec

### ISSUE THREAD

**Issue by FlintIshe** [ShadowMario/FNF-PsychEngine#8834]
### Describe your problem here.

The cutscene just play for 1 second and it quits the song, I can't fix it

https://user-images.githubusercontent.com/101379721/170860978-cc461564-6573-4268-86fd-77f9db162437.mp4

I end the song quickly to show the issue

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by dum-du-m** [comment]
show your code

**Comment by FlintIshe** [comment]
> show your code

[source.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8793758/source.zip)

here

**Comment by FlintIshe** [comment]
nvrm I fixed it (may be)
