### ISSUE TITLE
warning lua?

### ISSUE THREAD

**Issue by TurboGames0731** [ShadowMario/FNF-PsychEngine#8835]
### What is your question?

is there a .lua script i could use to show an image before the song starts? kinda like the screen shake warnings in sns, only an image.

**Comment by BendyGaming0** [comment]
the cutscene scripts have the code to stop the countdown and instead of showing a cutscene you can show an image (which is what I'm thinking you're trying to do) and just start the song when they press enter

**Comment by TurboGames0731** [comment]
i'll try it thanks
