### ISSUE TITLE
Freeplay Sections work, while Difficulty Change doesn't.

### ISSUE THREAD

**Issue by Gabriel2019rsAlt** [ShadowMario/FNF-PsychEngine#8836]
### Describe your problem here.

Hello! I have gotten the **VS Dave Freeplay Sections** in **PE 0.5.2h**, but the **difficulty change won't work.**
**I tried copying almost everything that had "difficulty"** in it. Guess what?
IT DIDN'T WORK! I am hoping someone will **help me out with difficulty change.**
I'll drop here my **FreeplayState.hx** just for someone to edit it for me.
Regards, **Gab**. Thanks for reading

**[FreeplayStateB.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8793434/FreeplayStateB.txt)**

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

It was touched until, I completely gave up, so I "almost" anything that had "difficulty change".

**Comment by ActualeAnEggDog** [comment]
i think you can dont use difficulties lol
