### ISSUE TITLE
Let scripts be executed outside songs

### ISSUE THREAD

**Issue by dum-du-m** [ShadowMario/FNF-PsychEngine#8837]
### What feature do you want to get added on the **base** engine?

I would like to be able to use scripts in states outside of songs

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
Duplicate, it's a won't do

**Comment by dum-du-m** [comment]
> Duplicate, it's a won't do

oh

**Comment by dum-du-m** [comment]
> Duplicate, it's a won't do

@frantastic24 why doe

**Comment by frantastic24** [comment]
Idk I'm not a dev don't ask me

**Comment by TheKitBoi** [comment]
> > Duplicate, it's a won't do
> 
> @frantastic24 why doe

Cus lua is not possible outside other states than playstate

**Comment by dum-du-m** [comment]
> > > Duplicate, it's a won't do
> > 
> > 
> > frantastic24 why doe
> 
> Cus lua is not possible outside other states than playstate

that kinda makes no sense
