### ISSUE TITLE
How to get enemy / player character name in script.lua?

### ISSUE THREAD

**Issue by shoopdawhoop574** [ShadowMario/FNF-PsychEngine#8838]
### Describe your problem here.

I am trying to use a script for a song that appears in multiple weeks, some with less difficulties / difficulties in different orders. Because of that, I can't change the script by difficulty using "if difficulty == 0 then" but each difficulty has different enemy / player characters.

How do I get the enemy / player's name? (e.g. if the player is bf-pixel in that difficulty then be able to get 'bf-pixel' in the lua script and change health drain or other mechanic as a result)

Thanks

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Wither362** [comment]
Use `dadName`, `boyfriendName` and `gfName`

**Comment by shoopdawhoop574** [comment]
Thank you!
