### ISSUE TITLE
How to do custom stages?

### ISSUE THREAD

**Issue by realkeys** [ShadowMario/FNF-PsychEngine#8839]
### Describe your problem here.

Heyo! So, I'm currently trying to port the [Vs Annie mod](http://gamebanana.com/mods/46918) to Psych, but am confused on how to make the stages. I did the **.json** stage files but don't know what to do next.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes. I changed the logoBumpin image.

**Comment by frantastic24** [comment]
Create a .lua for your stage, then read the wiki, it has all the functions you need and example scripts
