### ISSUE TITLE
How do I make a video play when the player presses 7? (LUA)

### ISSUE THREAD

**Issue by XperiorTR** [ShadowMario/FNF-PsychEngine#8840]
### Describe your problem here.

How do I make a video play when the player presses 7 (enters the chart editor)
I want to stop the player from accesing the chart editor and I want it to play a video before chrashing the game on purpose.
I have tried doing it but it either plays a video every frame or it goes into the chart editor before the video can play

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CattinQ** [comment]
Mix 7 thing with cutscene script

i think...

**Comment by Lorekeeper49** [comment]
You can probably use `keyJustPressed()`, but the hard part is getting the keys to work since, according to the wiki, you can only use `left`, `right`, `up`, `down`, `enter`, `space`, `backspace`, and `escape`.  It's definitely possible to do what you want to do, I just don't know how to do it.

**Comment by XperiorTR** [comment]
> Lorekeeper49
i tried `getPropertyFromClass('flixel.FlxG', 'keys.justPressed.7')` which works but it the game enters the chart editor before anything could happen

**Comment by Shelvsk** [comment]
i don't tested but will probably works:
```
function onUpdate()
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
        setProperty('inCutscene', true)
        startVideo('yourVideo')
        runTimer('crash', 5) --change the 5 number for your video duration
    end
end

function onTimerCompleted(tag)
    if tag == 'crash' then
        setProperty('inCutscene', false)
        close()
    end
end
```

if not worked try this: (i don't tested too)
```
function onUpdate()
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
        setProperty('inCutscene', true)
        endSong()
        startVideo('yourVideo')
        runTimer('crash', 5) --change the 5 number for your video duration
    end
end

function onTimerCompleted(tag)
    if tag == 'crash' then
        close()
    end
end
```
