### ISSUE TITLE
Rainbow eyesore in psych engine

### ISSUE THREAD

**Issue by CattinQ** [ShadowMario/FNF-PsychEngine#8841]
### What is your question?

How i make a rainbow eyesore in psych engine? I don't know code. Please For 0.4.2 Source

**Comment by lyke916** [comment]
you have to know how to download shaders which you need to know code to do

**Comment by jmxamongusmodder** [comment]
> you have to know how to download shaders which you need to know code to do

they removed shaders sadly.

**Comment by CrusherMods** [comment]
the label 💀
