### ISSUE TITLE
im having problems with lua

### ISSUE THREAD

**Issue by GrumpDaGrunt2022** [ShadowMario/FNF-PsychEngine#8844]
### Describe your bug here.

Ok So I Was Watching A Tutorial Of How To Add Backgrounds And Need Lua So I Download The Lua And Did Everything They Did So When I Tried It Didn’t Work And I Realized Maybe I'm Doing It Wrong So i Check And Its Fine But It Was The Engine I Was Using 0.4.2 and he had 0.5.2 so i don’t know what to do since im on mac using a no code tutorial bc im not a coder so i need a basically need 0.5.2 to work the lua and cant since there is no version of mac for that and i will need it bc the mod i'm working on if i finish it on this engine all i need is a bg and dont have one please understand that what i'm doing will be very helpfully and will be a cool future product.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

no i really just added my sprites

**Comment by frantastic24** [comment]
1) you can get update source builds from the actions tab
2) that's may be an error in your code and not a bug at all
3) at least report a bug properly, that's barely readable

**Comment by ShadowMario** [comment]
0.4.2 isn't supported anymore.
