### ISSUE TITLE
introText.txt not working on mods

### ISSUE THREAD

**Issue by pasta870** [ShadowMario/FNF-PsychEngine#8846]
### Describe your bug here.

So i wanted to add my custom introtext in my mod but it wont work

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i did not

**Comment by Lorekeeper49** [comment]
Make sure your mod is listed at the top of modsList.txt

**Comment by pasta870** [comment]
folder name or name in pack.json

**Comment by pasta870** [comment]
i read it as introtext im stupid

**Comment by pasta870** [comment]
but it still wont work

**Comment by jmxamongusmodder** [comment]
Heres a quick fix for both ill start with the mod one. The mod one only appers when you add a mod to the mods folder that is in a seperate folder and you boot up the game and load that mod. Intro text one.. I think you need to be on a source? but it should work other then that. Source may be better then lua but for me it both works the same
