### ISSUE TITLE
how do i make achievements without source code?

### ISSUE THREAD

**Issue by umynumytoons** [ShadowMario/FNF-PsychEngine#8848]
### Describe your problem here.

i dont know to make achievements without code and on youtube all of does video's was just source

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by umynumytoons** [comment]
bruh

**Comment by tylerandari12** [comment]
*screams in agony*

**Comment by silvashp** [comment]
retard

**Comment by Wither362** [comment]
You can’t until bb-panzu fixes de duplication bug, so close this useless pr, and make sure that your PR **hasn’t been already taken *26 TIMES!***,
