### ISSUE TITLE
The Version of FNF

### ISSUE THREAD

**Issue by CasualCypress** [ShadowMario/FNF-PsychEngine#8849]
### What feature do you want to get added on the **base** engine?

since you added the week7 assets, songs, an stages should you change the version at the bottom left of the title screen 

![Screenshot 2022-05-30 110630](https://user-images.githubusercontent.com/66497511/171029675-c498d0b1-2f34-4a7a-8bb8-87cf121c3519.png)

change it to v0.2.8

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
It's not released yet 👍
