### ISSUE TITLE
How to make animation play based on misses

### ISSUE THREAD

**Issue by AntCrem** [ShadowMario/FNF-PsychEngine#8850]
### Describe your problem here.

How can I make it so certain animations play when you have more than a certain number of misses? something similar to nonsense

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nu

**Comment by Lorekeeper49** [comment]
I know you want to do it with misses but it's actually easier to use `getAccuracy()` for accuracy conditions instead

**Comment by AntCrem** [comment]
Yeah, your probably right but how would I make it so an animation will play at a certain curStep when you have a certain accuracy?

**Comment by Lorekeeper49** [comment]
```lua
function onStepHit()
    if curStep == animStep then
        if getAccuracy() >= 50 then
            triggerEvent('Play Animation', 'highAccur', 'bf') --might need to switch the values (I don't really remember which value is which and I'm not bothering checking
        else
             triggerEvent('Play Animation', 'lowAccur', 'bf') --might need to switch the values (I don't really remember which value is which and I'm not bothering checking
        end
    end
end

**Comment by AntCrem** [comment]
thanks homie
