### ISSUE TITLE
Changing Health Drain Value mid-song

### ISSUE THREAD

**Issue by HJacet** [ShadowMario/FNF-PsychEngine#8853]
### What is your question?

Currently I am using this script to activate Health Drain;

function opponentNoteHit()
       health = getProperty('health')
    if getProperty('health') > 0.1 then
       setProperty('health', health- 0.02);
       end
end

 but would there be a way to change the Drain Value (health- 0.02) mid-song? Like for example if you get to a specific section of the song, it would activate the script and increase/decrease the value of the health drain.

Any answer I could use right now, thanks!

**Comment by frantastic24** [comment]
curBeat or curStep

**Comment by Wither362** [comment]
Use this:
```lua
local healthDrainValue = 0.02
function opponentNoteHit()
  health = getProperty('health')
  if getProperty('curBeat') == lol then
    healthDrainValue = newValue
  end

  if getProperty('health') > 0.1 then
    setProperty('health', health-healthDrainValue);
  end
end
```

and change lol by the curBeat, and change newValue by the new value of health drain
