### ISSUE TITLE
setGraphicSize( ) bug

### ISSUE THREAD

**Issue by 0-skid** [ShadowMario/FNF-PsychEngine#8854]
### Describe your problem here.

i tried to scale a lua sprite with the setGraphicSize( ) thing, but the object won't show in the stage when i do that:
![image](https://user-images.githubusercontent.com/85322671/171053229-9c442b0e-dd94-4a4e-90c2-a59c803259c0.png)
![image](https://user-images.githubusercontent.com/85322671/171053258-7108dc3c-cddf-4180-b831-c8b57d6006f4.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
You want `scaleObject()`
`setGraphicSize()` sets the pixel width/height
