### ISSUE TITLE
Someone Fix this pls lmao

### ISSUE THREAD

**Issue by Plotsh** [ShadowMario/FNF-PsychEngine#8855]
### What is your question?

i was trying to do a script that when u press a note, the song ends but it isnt working, can someone fix it pls?

```
function onStartSong()
	if keyJustPressed('up')
	
		or keyJustPressed('down')
		
		or keyJustPressed('left')
		
		or keyJustPressed('right') then
		endSong()
	end
end
```

**Comment by frantastic24** [comment]
use `function onUpdate()`

**Comment by Plotsh** [comment]
> use `function onUpdate()`

pog that worked (im new to coding scripts and stuff so don't expect too much from me

**Comment by tylerandari12** [comment]
One question...

Why? Lol
