### ISSUE TITLE
how to use time functions

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#8857]
### Describe your problem here.

how to use GetSongPosition() or OnStep() or OnBeat()

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just modded in the "example_mods" folder

**Comment by Lorekeeper49** [comment]
`getSongPosition()` is just as it says, use it when you want the want to use code based on how much progress the player has made

`onStep()` is actually named `onStepHit()` and is used like this
```lua
function onStepHit()
    --code
end
```

`onBeat()` is actually named `onBeatHit()` and is used like this
```lua
function onBeatHit()
    --code
end
```

**Comment by Wither362** [comment]
Function `onBeatHit()` and function `onStepHit()` are used like a `for`, like this:
```lua
local thing = 0
local thing2 = 0

function onBeatHit()
  thing = thing + 1 --every beat (4 times a section), it will increase the variable "thing" the value by 1
end

function onStepHit()
  thing2 = thing2 + 1 --every step (4 times a beat, 16 times a section), it will increase the variable "thing2" by 1
end
```

While `getSongPosition()` is a return function, it can be used like this:
```lua
function onCreate()
  if getSongPosition() == 1 then
    crashGame()
  end
end
```

**Comment by TFLTV** [comment]
> `getSongPosition()` is just as it says, use it when you want the want to use code based on how much progress the player has made
> 
> `onStep()` is actually named `onStepHit()` and is used like this:
> 
> ```lua
> function onStepHit() --calls every step (4 times a beat, 16 times a section)
>     --code
> end
> ```
> 
> `onBeat()` is actually named `onBeatHit()` and is used like this:
> 
> ```lua
> function onBeatHit() --calls every beat (4 times a section)
>     --code
> end
> ```

how would I do a health drain occurring on a step then. this didn't work wat I did wrong?
`function onStepHit() --health drain starts on step 400 (but I never got it working)
	if curstep == 400 then
		function opponentNoteHit()
			health = getProperty('health')
			if getProperty('health') > 0.01 then
				setProperty('health', health - 0.045);
			end
		end
	end
end

`

**Comment by ShadowMario** [comment]
```lua
function opponentNoteHit()
	if curstep == 400 then
		if getHealth() > 0.01 then
			addHealth(-0.045);
		end
	end
end
```
