### ISSUE TITLE
Fatal error: exception Out of memory

### ISSUE THREAD

**Issue by Zarmvation** [ShadowMario/FNF-PsychEngine#8858]
Describe your problem here.

so i was just making my mod and it had a lot of progress in it and while i was doing that i was putting the characters in the game but the files were connected to my old characters files so i deleted that and i restarted my psych engine and then when i tried to compile it it says Fatal error: exception Out of memory and i was panicking and now all my progress is gone someone please help me im freaking out.

 Are you modding a build from source or with Lua?

Source

What is your build target?

Windows x64

Did you edit anything in this build? If so, mention or summarize your changes.
no only example_mods

**Comment by Wither362** [comment]
You don’t have memory space, try deleting files that you don’t need, and compile again, if it didn’t work, delete more files, and again, and again, but if it still doesn’t work, try compiling in another computer
