### ISSUE TITLE
Is it possible to add a poster thingy that shows which character you are fighting 

### ISSUE THREAD

**Issue by EndorrrH** [ShadowMario/FNF-PsychEngine#8860]
### What is your question?

so pretty much the poster would fly onto the screen btw i cant animate that so.... its just gonna have to be done using the coding and it would stay on there until some notes come in and it would just fly away heres the image im tryna use for this to work https://gyazo.com/27b6eb5ce980b5de46e14b03bd97b63a

**Comment by FlintIshe** [comment]
function onCreate()
        doTweenX('tag', 'yourthing', 20, 3, 'circInOut')
end

function opponentNoteHit(id,data,type,amogus,sus)
       doTweenX('tag', 'youthing', 1500, 2, 'circInOut')
end

sorry if it did't work i am bad at coding

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers

**Comment by EndorrrH** [comment]
wait.... i wonder if this can be done with source

**Comment by frantastic24** [comment]
it's literally just tweens, you can do it either way
