### ISSUE TITLE
A little problem with the difficulty slider

### ISSUE THREAD

**Issue by ouie5th** [ShadowMario/FNF-PsychEngine#8863]
### Describe your problem here.

So, I followed the instructions on the wiki on how to make a new difficulty. it all went smoothly (I didn't use source code because the game can't seem to run on it) until it came to the difficulty slider. In the Story Mode menu, the difficulty slider wouldn't load the crazy image, but instead would show another Hard mode or another Easy mode if I went to the left. Do you know why this occurs or is there something I missed?
![newdifficultynotworking](https://user-images.githubusercontent.com/106591733/171156676-d61f42be-427f-486a-8b74-228ecc8f5063.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

readthetextabovelol

**Comment by Shelvsk** [comment]
check if the .json song file ends with your difficulty name, if yes, check if you have the images/menudifficulties folder and put your difficulty image on it, if yes, show a print from the images/menudifficulties folder and the your song data file and i'll try to solve this

**Comment by theo2yeah** [comment]
It is a common bug, you can only fix that by adding the difficulty images before compiling the actual game

**Comment by ShadowMario** [comment]
You added it to the wrong folder then, it's supposed to go in `mods/<your mod name here>/menudifficulties/`
