### ISSUE TITLE
How To Make Custom Main Menu Like In Mod Bob And Bosip In LUA?

### ISSUE THREAD

**Issue by ArtemB0Y** [ShadowMario/FNF-PsychEngine#8868]
### Describe your problem here.

I Don't Know How To Make Main Menu On LUA Like In Bob And Bosip

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CrusherMods** [comment]
you can only use lua to mess around with stuff in-game
not menus

**Comment by ArtemB0Y** [comment]
@CrusherMods what is that? stuff in-game?

**Comment by frantastic24** [comment]
Lua scripts only run during songs

**Comment by CrusherMods** [comment]
> @CrusherMods what is that? stuff in-game?

like if your in a song

**Comment by PrismLight** [comment]
end process

**Comment by PrismLight** [comment]
Doubtful guess, but imagine something like this could work.

```lua
function onCreate()
setPropertyFromClass('MainMenuState', 'menuItem.x', 69)
debugPrint('funni-lol')
end
```

**Comment by PrismLight** [comment]
> 1st of all: bob and bosip bad 2nd of all: lua scripts don't work on menus 3rd of all: shadow mario doesn't play many mods so you shouldn't ask stuff like this 4th of all: bob and bosip bad

1*4=4

**Comment by tylerandari12** [comment]
Lua not LUA

**Comment by ShadowMario** [comment]
You can only do it in source 👍

**Comment by ArtemB0Y** [comment]
@ShadowMario okay
