### ISSUE TITLE
week 7 background isn't working.

### ISSUE THREAD

**Issue by SuperWA-HOOMan** [ShadowMario/FNF-PsychEngine#8871]
### Describe your bug here.

the background for week 7 (and everything else in the week 7 assets folder) doesn't load in.
![now scra](https://user-images.githubusercontent.com/91621932/171311107-4f66f1e3-b974-409c-bcd9-0f83050567a0.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed the main menu and changed the icons to add winning icons. I also removed the time bar and time bar bg and added a gf version.

**Comment by frantastic24** [comment]
did you do a clean install

**Comment by SuperWA-HOOMan** [comment]
a what

**Comment by frantastic24** [comment]
Did you just replace files to update or did you put them in an empty folder

**Comment by SuperWA-HOOMan** [comment]
like what files and what update

**Comment by frantastic24** [comment]
The files. Where did you place them
On top of an older engine version, or in a new folder (clean install)
If you replaced files you probably missed something, do a clean install

**Comment by SuperWA-HOOMan** [comment]
the mod im making was originally on 0.5.1, and then i downloaded 0.5.2h separately and moved all the stuff from the 0.5.1 version over to this one

**Comment by SuperWA-HOOMan** [comment]
ok what files
do you mean the week 7 files

**Comment by SuperWA-HOOMan** [comment]
like are you asking if i tried to put week 7 in an older version or something?

**Comment by SuperWA-HOOMan** [comment]
fixed it
it turns out i screwed up the project.xml file
