### ISSUE TITLE
Colored Code

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#8872]
### What is your question?

I see people sent code that has pretty colors like this:
![33FFC032-24E3-4CCD-A99D-DFBB283AD391](https://user-images.githubusercontent.com/97060639/171342448-d6f96dd2-0b03-4af0-b89d-819e9a604957.jpeg)
However mine always looks like this:
![83348303-D5EA-4206-A8A9-295A3997AF84](https://user-images.githubusercontent.com/97060639/171342490-1470fbbd-62c9-486a-b75f-ac432b7bfa78.jpeg)
How do I make mine look pretty?

**Comment by Wither362** [comment]
Reply to this comment and you will see what we do:
```lua
function replayToThisComment()
  function lookUppperThisCode()
    andYouWillSeeWhatItIs()
  end
end
```

**Comment by tylerandari12** [comment]
> Reply to this comment and you will see what we do:
> 
> ```lua
> 
> function replayToThisComment()
> 
>   function lookUppperThisCode()
> 
>     andYouWillSeeWhatItIs()
> 
>   end
> 
> end
> 
> ```

0-0
Beautiful :0

**Comment by tylerandari12** [comment]
'''lua

local Speed
=0.05
local angle
=5
adds up quick
cam be
"Game
" HUD
or
Other
there can be multiple cameras
local cameras
= {"'Game" }
local Radians
=0
function onUpdate()
Radians
= Radians + Speed
for i, v in pairs (cameras) de
setProperty("cam"..v
end
end

'''

**Comment by Wither362** [comment]
> '''lua
> 
> local Speed =0.05 local angle =5 adds up quick cam be "Game " HUD or Other there can be multiple cameras local cameras = {"'Game" } local Radians =0 function onUpdate() Radians = Radians + Speed for i, v in pairs (cameras) de setProperty("cam"..v end end
> 
> '''

Lol, don’t use **’**, use **```**

**Comment by tylerandari12** [comment]
> > '''lua
> 
> > 
> 
> > local Speed =0.05 local angle =5 adds up quick cam be "Game " HUD or Other there can be multiple cameras local cameras = {"'Game" } local Radians =0 function onUpdate() Radians = Radians + Speed for i, v in pairs (cameras) de setProperty("cam"..v end end
> 
> > 
> 
> > '''
> 
> 
> 
> Lol, don’t use **’**, use **```**

Sorry I'm on my phone right now

**Comment by Wither362** [comment]
> ```lua
> local Speed
> =0.05
> local angle
> =5
> adds up quick
> cam be
> "Game
> " HUD
> or
> Other
> there can be multiple cameras
> local cameras
> = {"'Game" }
> local Radians
> =0
> function onUpdate()
> Radians
> = Radians + Speed
> for i, v in pairs (cameras) de
> setProperty("cam"..v
> end
> end```
> ```

Yeah! Now use spaces, it have to be like this: 
```lua
local Speed = 0.05
local angle = 5
-- adds up quick cam be "Game" "HUD" or "Other"
-- there can be multiple cameras
local cameras = {"'Game" }
local Radians = 0
function onUpdate()
  Radians = Radians + Speed
  for i, v in pairs (cameras) do
    setProperty("cam"..v
  end
end
```

**Comment by Wither362** [comment]
And take in mind that it gphave to be like this:

**` ``**
code
**```**

Not like this:
Code```

**Comment by tylerandari12** [comment]
> And take in mind that it gphave to be like this:
> 
> 
> 
> **` ``**
> 
> code
> 
> **```**
> 
> 
> 
> Not like this:
> 
> Code```

Like I said I'm on my phone lol...

But thanks a lot :D

**Comment by Wither362** [comment]
And for other color codes, use the extension file, for example:
| Language code | Extension of the file | What to use to color it |
| ------------- | ------------- | ------------- |
| LUA  | lua  | lua |
| JavaScript  | js  | js |
| Haxe | hx | hx |

Do you get it?

**Comment by Wither362** [comment]
And if you want to write things more advanced, I recommend you to read this: [https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/about-writing-and-formatting-on-github](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/about-writing-and-formatting-on-github), and then go down the page for more writing
