### ISSUE TITLE
help i cant compile

### ISSUE THREAD

**Issue by NyaMuffi** [ShadowMario/FNF-PsychEngine#8873]
### Describe your bug here.

i installed everything i need but this error suddenly happened out of nowhere and then i tried lime test windows -clean and it worked but the next time i compiled it it showed the error again and whe i tried clean it wouldnt work then i tried installing visual studio and i found sdk but not msvc which is weird

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\T\Desktop\FNF-PsychEngine-0.4.2\export\release\windows\obj>setlocal enabledelayedexpansion
C:\Users\T\Desktop\FNF-PsychEngine-0.4.2\export\release\windows\obj>()
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing i tried a new buld and same thing

**Comment by Wither362** [comment]
Install vs code and visual studio
