### ISSUE TITLE
My song has no voice track, yet its still checking for a voice track despite the fact that i said no voice track

### ISSUE THREAD

**Issue by ColdlordXRepositories** [ShadowMario/FNF-PsychEngine#8875]
### Describe your bug here.

title.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added 3 songs in story menu, and a character, plus a stage.

**Comment by frantastic24** [comment]
explain if there is an error pop up or something? because leaving the option unchecked works fine

**Comment by frantastic24** [comment]
that's not the game looking for vocals, that's the game not being able to read your Inst file because you exported it incorrectly

**Comment by the-funky-lad** [comment]
close this since the frantastic individual explained the thing to you
