### ISSUE TITLE
Can't make a new character

### ISSUE THREAD

**Issue by imalink100** [ShadowMario/FNF-PsychEngine#8877]
### Describe your bug here.

I can't make a new character because if i try, intead of loading the character an error pops up saying "Invalid character at (position)"

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I tried switching the words, it didn't work.

**Comment by frantastic24** [comment]
not a bug, one of your files is broken
