### ISSUE TITLE
GF Menu thing

### ISSUE THREAD

**Issue by LucaGoku** [ShadowMario/FNF-PsychEngine#888]
### Describe your problem here.

I'm Porting V.S. Aflac and when I start the game, it seems offset

What it would look like in V.S. Aflac:
![image](https://user-images.githubusercontent.com/92657248/140771226-e478f9aa-c753-4241-be7a-5c665e4e74be.png)

What it looks like in Pysch Engine:
![image](https://user-images.githubusercontent.com/92657248/140771346-72772a06-3a87-46d2-ac84-f87d3c771774.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't

**Comment by ShadowMario** [comment]
Edit TitleState.hx

**Comment by LucaGoku** [comment]
> Edit TitleState.hx

But how do I know where to put the x and y?
