### ISSUE TITLE
The game is slowed down for no reason

### ISSUE THREAD

**Issue by BorisC04** [ShadowMario/FNF-PsychEngine#8880]
### Describe your problem here.

My game is slowed down every time I run it and back to normal after I played any song.
The problem is stated at #8655 but ShadowMario closed it saying my pc sucks
I am pretty darn sure this isn't the case. My old crappy pc can run perfectly while new pc with **much better hardware** can't? Don't make sense to me at all. I am sure it is either wrong compiling or system software having issues.
Anyone has same problem and knows how to solve it?
Videos:
https://streamable.com/x92bs8
https://streamable.com/4j7ok0

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
I already mentioned vsync and high frame cap causes this, which you didn't respond to and just opened the same issue again

**Comment by ShadowMario** [comment]
If the latest github repo didn't solve this then it's your PC's skill issue.
