### ISSUE TITLE
my game over changer completely breaks the game over with the new update

### ISSUE THREAD

**Issue by greentophat** [ShadowMario/FNF-PsychEngine#8881]
### Describe your problem here.

so i had this code for a while before the build:

```
function onGameOver()
	setPropertyFromClass('GameOverSubstate', 'characterName', getProperty('boyfriend.curCharacter'))
	return Function_Continue;
end
```

and i just assumed the new build broke it with that code.
but then i removed the code and it kept happening. i still had no ability to die.
players 1, 2, and gf are all custom characters.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Do you have practice mode off

**Comment by greentophat** [comment]
> Do you have practice mode off

yes. i do.
