### ISSUE TITLE
Time bar

### ISSUE THREAD

**Issue by schwiftified** [ShadowMario/FNF-PsychEngine#8883]
### What is your question?

How can i move the time bar on source?

**Comment by tylerandari12** [comment]
I'd guess the sprite would be called `timeBar` but I'm no source guy...

**Comment by WortwL** [comment]
^

just find timeBar on playstate class

**Comment by BendyGaming0** [comment]
"timeBarBG" and "timeTxt" are the objects you're looking for

**Comment by PogofruitKM** [comment]
> "timeBarBG" and "timeTxt" are the objects you're looking for

```timeBarBG``` is attached to ```timeBar```
And ```timeTxt``` is separate, just change x and y positions of timeBar and timeTxt
