### ISSUE TITLE
Was there ever a build version of psych engine?

### ISSUE THREAD

**Issue by Cr0s5H34D** [ShadowMario/FNF-PsychEngine#8884]
### What is your question?

For some odd reason, i remember i had a build version of psych engine, i had it on my old laptop but i recently broke it. im on another laptop with psych engine, but right now, i cannot find the build version of psych engine anywhere, was it even real or never existed?

**Comment by XS09-dev** [comment]
Ye. Go to actions and any recent compiled version. Click on it and scroll down to artifacts and click your os

**Comment by ShadowMario** [comment]
Psych Engine isn't real, maybe the real Psych Engine is the friends we made along the way.
