### ISSUE TITLE
(closed)

### ISSUE THREAD

**Issue by EndorrrH** [ShadowMario/FNF-PsychEngine#8886]
(clsoed)

**Comment by EndorrrH** [comment]
I'll put up another issue for someone to make some chromatics for parm pam and cheese

**Comment by Lorekeeper49** [comment]
I don't think this is where you post this

**Comment by frantastic24** [comment]
This isn't the place to ask kid

**Comment by TFLTV** [comment]
close it bruh

**Comment by CrusherMods** [comment]
at least click close like its not that hard
even my 1 year old cousin can do that

**Comment by CrusherMods** [comment]
AYYY HE CLICKED IT

**Comment by EndorrrH** [comment]
i dont know much about github

terrible eyesight maybe?

**Comment by CrusherMods** [comment]
> i dont know much about github
> 
> terrible eyesight maybe?

oh that makes more sense now
