### ISSUE TITLE
Funny modchart

### ISSUE THREAD

**Issue by EndorrrH** [ShadowMario/FNF-PsychEngine#8887]
### What is your question?

im tryna do some funny modchart heres a screenshot:
![Screenshot_38](https://user-images.githubusercontent.com/93217327/171739391-31fe1933-e644-4879-aa76-87b4d1546801.png)

**Comment by frantastic24** [comment]
stop posting useless issues

**Comment by EndorrrH** [comment]
imma just wait until shadowmario closes this
