### ISSUE TITLE
Need some help coding a feature. (Source)

### ISSUE THREAD

**Issue by elixioo** [ShadowMario/FNF-PsychEngine#8888]
### Describe your problem here.

Hello! I have been making a menu for my mod and I need some help coding a feature! Basically, I made a Covers and Remixes Menu. I have all of the buttons ready, but i'm not sure how i would do this: Transport the player to a specific song after hitting it with left click. This may be a obvious question, but its been almost 6 months since i've used HaxeFlixel. Help would be appreciated!!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Wither362** [comment]
put this in the switch statement in menustate.hx (this isn’t tested!):
```hx
case 'lol': // the menu select thing
	var songName:String = 'lol' // the song name
	var difficultyNum:Int = 0; // the difficulty number, set to -1 to the playstate story difficulty
	var song = Highscore.formatSong(songName, difficultyNum);
	PlayState.SONG = Song.loadFromJson(song, songName);
	if(difficultyNum == -1)
		difficultyNum = PlayState.storyDifficulty;
	PlayState.storyDifficulty = difficultyNum;
	PlayState.instance.persistentUpdate = false;
	LoadingState.loadAndSwitchState(new PlayState());

	FlxG.sound.music.pause();
	FlxG.sound.music.volume = 0;
	if(PlayState.instance.vocals != null)
	{
		PlayState.instance.vocals.pause();
		PlayState.instance.vocals.volume = 0;
	}
```

**Comment by PrismLight** [comment]
> put this in the switch statement in menustate.hx (this isn’t tested!):
> 
> ```hx
> case 'lol': // the menu select thing
> 	var songName:String = 'lol' // the song name
> 	var difficultyNum:Int = 0; // the difficulty number, set to -1 to the playstate story difficulty
> 	var song = Highscore.formatSong(songName, difficultyNum);
> 	PlayState.SONG = Song.loadFromJson(song, songName);
> 	if(difficultyNum == -1)
> 		difficultyNum = PlayState.storyDifficulty;
> 	PlayState.storyDifficulty = difficultyNum;
> 	PlayState.instance.persistentUpdate = false;
> 	LoadingState.loadAndSwitchState(new PlayState());
> 
> 	FlxG.sound.music.pause();
> 	FlxG.sound.music.volume = 0;
> 	if(PlayState.instance.vocals != null)
> 	{
> 		PlayState.instance.vocals.pause();
> 		PlayState.instance.vocals.volume = 0;
> 	}
> ```

_AHEMM_
You MISSED a semicolon. `var songName:String = 'lol'`
