### ISSUE TITLE
Death note thing i wanna make

### ISSUE THREAD

**Issue by EndorrrH** [ShadowMario/FNF-PsychEngine#8889]
### What is your question?

Is there a way to make a death note that put something on your note and makes it so you cant use it anymore line in the voltz anymore only for 10 seconds.

**Comment by EndorrrH** [comment]
i fucking suck at spelling

**Comment by CrusherMods** [comment]
> i fucking suck at spelling

you should see me type on my phone 💀

**Comment by Lorekeeper49** [comment]
```lua
function goodNoteHit(i, d, t, l)
    if t == 'your note' then
        setProperty('bf.stunned', true)
        runTimer('stunTimer', 10)
    end
end
function onTimerCompleted(t, l, ll)
    if t == 'stunTimer' then
        setProperty('bf.stunned', false)
    end
end
```
hasn't been tested so I don't know if it'll work

**Comment by Lupingllogi111** [comment]
setProperty('boyfriend.stunned', [either true or false])
Use a timer to set it to false after you press it
