### ISSUE TITLE
Moving arrows teleport?

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#889]
### Describe your bug here.

I'm making a custom event for moving arrows but the arrow will only move when I pause the game, and it will teleport to the destination instantly.

Example:
![image](https://user-images.githubusercontent.com/93293747/140783615-1a02e54c-1495-4af3-8635-1585f6281d27.png)

![image](https://user-images.githubusercontent.com/93293747/140783724-2f44dfb8-9c05-419b-b520-77f356871ea1.png)

![image](https://user-images.githubusercontent.com/93293747/140783755-14d82f9a-9def-4d4b-9033-c7fa93a371d1.png)

![image](https://user-images.githubusercontent.com/93293747/140783780-4a660b98-ddae-41c3-af64-b21383172aa0.png)

here's the code for the event, just in case it's something to do with that.
```
function mysplit (inputstr, sep)
    if sep == nil then
        sep = "%s";
    end
    local t={};
    for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
        table.insert(t, str);
    end
    return t;
end

-- Event notes hooks
function onEvent(value1, value2)
    local tableee=mysplit(value2,", "); -- Splits value1 into a table
    noteTweenX(value1, tableee[1], tableee[3], "quartInOut");
    noteTweenY(value1, tableee[2], tableee[3], "quartInOut");
end
```

and the instructions
```
Change Note Position

Value 1: Note (0-7)
Value 2: x value, y value, duration
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Everything I've done has been within the mods folder.

**Comment by ShadowMario** [comment]
the onEvent hook is wrong.

`function onEvent(name, value1, value2)`

Remember to check if `name == "My event name"`
