### ISSUE TITLE
Song crashes when trying to play it on story mode

### ISSUE THREAD

**Issue by Funnynamehere** [ShadowMario/FNF-PsychEngine#8891]
### Describe your bug here.

When i try to play a song using story mode, the game crashes (and for some reason, the song loads using freeplay

https://user-images.githubusercontent.com/106783125/171751839-8c9ad63f-7d33-46ea-a0a7-7d09d5492770.mp4

)

(stop recording = game crashed)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Funnynamehere** [comment]
> provide your files if you're going to report a bug like this

the files have everything they need, inst and voices, the .json (for the chart) and the name in the week (atleast i think is everything)

**Comment by frantastic24** [comment]
i'm not asking if you have the files, i'm telling you to post them here so the bug can be reproduced (that's the point of a report)

**Comment by Funnynamehere** [comment]
> i'm not asking if you have the files, i'm telling you to post them here so the bug can be reproduced (that's the point of a report)
[files.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8828340/files.zip)

**Comment by Funnynamehere** [comment]
> what about the scripts you're using, those are the most likely to be causing this


i think i put "lua" accidentally (sorry)

**Comment by frantastic24** [comment]
but you also said you didn't edit anything? unless the game is still crashing without your edits, this isn't a bug and you may want to go over your own code again

**Comment by Funnynamehere** [comment]
> but you also said you didn't edit anything? unless the game is still crashing without your edits, this isn't a bug and you may want to go over your own code again

i just edited the basics, but the song just started to crash when i added the other songs (i tried to remove the songs, but stills crashing)
