### ISSUE TITLE
Export?

### ISSUE THREAD

**Issue by Just-Julian** [ShadowMario/FNF-PsychEngine#8896]
### What is your question?

How do you export source code to one folder like the base Psych Engine?

**Comment by WortwL** [comment]
make sure you have installed all the thing needed to compile

right click the folder that contain your source
click git bash
type

> lime build windows

**Comment by Just-Julian** [comment]
Where is git bash?

**Comment by tylerandari12** [comment]
> Where is git bash?
> 
> 
> 
> 

I think it's a program that needs to be installed...
