### ISSUE TITLE
Marvelous Rating

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#8900]
### Describe your problem here.

I wanted to try to code in a Marvelous Rating for my mod. There are Sicks, Goods, Bads, and Shits, but I want to include a Marvelous Rating which is when you hit the Note PERFECTLY. I am using a sourced version of Psych 0.5.1 but I charted some of the songs in 0.5.2h, should translate over through the versions. 💀

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by fnfdemonboi314159** [comment]
I should point this out: I compiled the build, and I am using Lua to add stuff to it.

**Comment by ActualeAnEggDog** [comment]
i think you need to use source. try copying OS engine source

**Comment by TheRealJake12** [comment]
or look at my fork of kade which has the marv rating. https://github.com/TheRealJake12/Kade-Engine-Community.git as well as all the option shit and everything. Lua can't do everything. Lua isn't the solution to everything.

**Comment by fnfdemonboi314159** [comment]
OOF! I was thinking there was a way, thanks for the reminder.
