### ISSUE TITLE
Engine keeps crashing when I use Blammed lights on a custom stage

### ISSUE THREAD

**Issue by Lupingllogi111** [ShadowMario/FNF-PsychEngine#8902]
### Describe your problem here.

When I use Bammed lights on a custom stage ( I swear this is the first time I use them) it keeps crashing my game.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by PrismLight** [comment]
Blammed Lights was forcefully exclusive to Week 3 now.

**Comment by ShadowMario** [comment]
Blammed Lights is gone 👍
