### ISSUE TITLE
my psych engine keeps crashing when its going into another song

### ISSUE THREAD

**Issue by lyke916** [ShadowMario/FNF-PsychEngine#8904]
### Describe your bug here.

how do i fix it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

mods folder

**Comment by Wither362** [comment]
The song chart is wrong or corrupted or something like that

**Comment by WilliamGaming12** [comment]
or it's because it's not json, for that, go to the part where is the charting (the folder), then put near the difficulty ".json"

**Comment by lyke916** [comment]
> or it's because it's not json, for that, go to the part where is the charting (the folder), then put near the difficulty ".json"

the song files are jsons, so it must be what @Wither362 said

**Comment by lyke916** [comment]
> The song chart is wrong or corrupted or something like that

it was wrong, thank you!
