### ISSUE TITLE
Better chart editor

### ISSUE THREAD

**Issue by EndorrrH** [ShadowMario/FNF-PsychEngine#8905]
### What feature do you want to get added on the **base** engine?

1. a typing mode (you can use your keyboard to chart)
2. more events (more chart editor events)
3. better ui (better chart editor ui)
4. playstation thingy (playstation port)
5. noteskins (new noteskins)
6. healthbar revamp (revamping the healthbar)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Lorekeeper49** [comment]
Keys 1-8 can be used to place notes
Everything else besides the better ui can be done by creating them on your computer

**Comment by ManMaster707** [comment]
What do you mean by "playstation port"?

**Comment by frantastic24** [comment]
1) already exists
2) make them yourself
3) haxe limitation, it's fine as it is
4) what the fuck
5) make them yourself
6) revamp what, it's fine as it is

**Comment by EndorrrH** [comment]
i wish i could just delete most of my posts
