### ISSUE TITLE
Dialogue after song

### ISSUE THREAD

**Issue by Alt-Reality** [ShadowMario/FNF-PsychEngine#891]
### Describe your problem here.

So im working on a mod with one song, and we want to have dialogue before the song, and also after the song. Starting dialogue before the song works fine, but its the after-song dialogue thats confusing me. what should the name of the dialogue.json be for the after song dialogue, and what should the code be?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

PlayState.hx for stage code, FreeplayState, StoryMenuState, and CoolUtil to remove a difficulty.

**Comment by ShadowMario** [comment]
Add this to finishSong() function:
![Screenshot_5](https://user-images.githubusercontent.com/44785097/141163740-0784520e-c782-4b22-b06f-81b6022baef1.png)

Then you add this new function:
```haxe
function postSongDialogue()
{
	timeBarBG.visible = false;
	timeBar.visible = false;
	timeTxt.visible = false;
	canPause = false;
	endingSong = true;
	camZooming = false;
	updateTime = false;
	inCutscene = true;
	
	var file:String = Paths.json(songName + '/dialogueEnd');
	var dialogueJson:String = DialogueBoxPsych.parseDialogue(file);
	startDialogue('dialogueEnd');
}
```

Name your dialogue file `dialogueEnd.json` and put it inside the charts folder

**Comment by Alt-Reality** [comment]
![image](https://user-images.githubusercontent.com/88809517/141203374-571dc062-820e-48e0-b755-ec4c29762c27.png)
![image](https://user-images.githubusercontent.com/88809517/141203418-e92a77a3-e94b-44ad-ae6f-6de49f3bbc3b.png)
@ShadowMario 
not sure what to do here
