### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by Gabri7075** [ShadowMario/FNF-PsychEngine#8912]
### What is your question?

How to remove the healthbar hud? (Downloaded Build)

not all, just this:
![healthBar](https://user-images.githubusercontent.com/88889291/171970092-c4df7dce-4fa0-40a6-bbeb-33eacd317bb7.png)

**Comment by BendyGaming0** [comment]
"healthBarBG" and "healthBar" are what make up the health bar in the UI, so just run "setProperty('object.visible', false)" on both of them
