### ISSUE TITLE
I can't access my discussions and mentions anymore...

### ISSUE THREAD

**Issue by PrincessI** [ShadowMario/FNF-PsychEngine#8914]
### What is your question?

So, I returned here after a while, and I realized I can't view the discussion posts I previously made (Image Dialogue Tutorial, Starlight Mayhem question, etc). Instead, I'm greeted to this:

![Screenshot (556)](https://user-images.githubusercontent.com/97416116/171974503-19f3a31d-7643-494e-aaec-020c90ee12f6.png)

Strangely, I still get notified via email about being mentioned in posts, but when I tried viewing them on the website, I get the same error. Can anyone tell me what's happening and how to fix this? I can't figure out the problem...

**Comment by CrusherMods** [comment]
discussions were disabled

in fortnite terms in case you dont understand:
Shadow Mario pump shotgunned Psych Engine Discussions and then Shadow Mario placed #1

**Comment by PrincessI** [comment]
> discussions were disabled
> 
> in fortnite terms in case you dont understand: Shadow Mario pump shotgunned Psych Engine Discussions and then Shadow Mario placed #1

Is that so? Man, that's a bit of a let down... But thanks a bunch for letting me know. :)

**Comment by CrusherMods** [comment]
> > discussions were disabled
> > in fortnite terms in case you dont understand: Shadow Mario pump shotgunned Psych Engine Discussions and then Shadow Mario placed #1
> 
> Is that so? Man, that's a bit of a let down... But thanks a bunch for letting me know. :)

there is 2 alt psych discussions though

https://github.com/mayo78/PSYCHDISCUSSIONS/
https://github.com/Theoyeah/PsychEngineDiscussions/

**Comment by PrincessI** [comment]
> > > discussions were disabled
> > > in fortnite terms in case you dont understand: Shadow Mario pump shotgunned Psych Engine Discussions and then Shadow Mario placed #1
> > 
> > 
> > Is that so? Man, that's a bit of a let down... But thanks a bunch for letting me know. :)
> 
> there is 2 alt psych discussions though
> 
> https://github.com/mayo78/PSYCHDISCUSSIONS/ https://github.com/Theoyeah/PsychEngineDiscussions/

**Comment by PrincessI** [comment]
> > > > discussions were disabled
> > > > in fortnite terms in case you dont understand: Shadow Mario pump shotgunned Psych Engine Discussions and then Shadow Mario placed #1
> > > 
> > > 
> > > Is that so? Man, that's a bit of a let down... But thanks a bunch for letting me know. :)
> > 
> > 
> > there is 2 alt psych discussions though
> > https://github.com/mayo78/PSYCHDISCUSSIONS/ https://github.com/Theoyeah/PsychEngineDiscussions/

**Comment by PrincessI** [comment]
Thanks a lot for the links!

**Comment by CrusherMods** [comment]
> Thanks a lot for the links!

np

**Comment by Mastercopper2346** [comment]
What about that…. Image dialogue tutorial?

**Comment by PrincessI** [comment]
> What about that…. Image dialogue tutorial?

I can remake that. I don't have the screenshots anymore though, so I need to redo it.
