### ISSUE TITLE
Scrolling bg

### ISSUE THREAD

**Issue by joxu13v** [ShadowMario/FNF-PsychEngine#8915]
### Describe your problem here.

I need help to make an animated bg like nigthmare run of indie cross using .Lua 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ManMaster707** [comment]
in that mod the bg has an xml, so check the wiki [here](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Custom-Sprites-Functions#makeanimatedluaspritetagstring-imagestring-xfloat-yfloat)
