### ISSUE TITLE
Event not working right

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8916]
### Describe your problem here.

The script is:
```
			case 'Dodge':
				dodgeImage = new BGSprite('sword', 0, 0);
				dodgeImage.visible = false;
				add(dodgeImage);

				new FlxTimer().start(0.1, function(tmr:FlxTimer)
					{
						dodgeImage.visible = true;
					});

				new FlxTimer().start(1, function(tmr:FlxTimer)
					{
						if (FlxG.keys.justPressed.SPACE)
							{
								dodgeImage.visible = false;
								boyfriend.playAnim('dodge', true);
							}
							else {
								health -= 2;
								vocals.volume = 0;
								doDeathCheck(true);
							};
					});
```
the error is that pressing space doesn't do anything, and even if i press space, i still die.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i edited PlayState.hx and tried to add a new event

**Comment by CrusherMods** [comment]
```haxe
dodgeImage = new BGSprite('sword', 0, 0);
```
should be
```haxe
var dodgeImage:BGSprite = new BGSprite('sword', 0, 0);
```

**Comment by Mastercopper2346** [comment]
ok

**Comment by Mastercopper2346** [comment]
lemme try

**Comment by Mastercopper2346** [comment]
ok, no errors! thx!

**Comment by Mastercopper2346** [comment]
wait

**Comment by Mastercopper2346** [comment]
the space thing is not working

**Comment by frantastic24** [comment]
You use the `update` function when checking for inputs, not a timer

**Comment by hayfii** [comment]
> the space thing is not working

3 months of source coding? Nah, stop capping stupid kid it doesn't make you look good :)

**Comment by hayfii** [comment]
This ain't Psych Engine issue, it's just your brain issue! You need to learn more.

**Comment by hayfii** [comment]
BGSprite is used for backgrounds, you literally need to stop capping young man.

**Comment by Mastercopper2346** [comment]
> 3 months of source coding? Nah, stop capping stupid kid it doesn't make you look smart :)

First of all, I didn’t make the script.
Second of all, I can show you proof that I HAVE been working on a mod for 3 months.

**Comment by hayfii** [comment]
> > 3 months of source coding? Nah, stop capping stupid kid it doesn't make you look smart :)
> 
> First of all, I didn’t make the script. Second of all, I can show you proof that I HAVE been working on a mod for 3 months.

If you're SO ADVANCED in coding why did you steal the script? I don't need a fake proof sorry.

**Comment by Mastercopper2346** [comment]
> If you're SO ADVANCED in coding why did you steal the script? I don't need a fake proof sorry.

did I say I was advanced?

**Comment by hayfii** [comment]
> > If you're SO ADVANCED in coding why did you steal the script? I don't need a fake proof sorry.
> 
> did I say I was advanced?

You said
![image](https://user-images.githubusercontent.com/94598301/173333543-0f4efc8e-9986-41ea-8e11-9d52093037ee.png)
with UPPERCASE.

**Comment by Mastercopper2346** [comment]
But did I say I was advanced?

**Comment by Mastercopper2346** [comment]
So just leave me alone
