### ISSUE TITLE
Background Change Lua Script

### ISSUE THREAD

**Issue by MOON-on-GitHub** [ShadowMario/FNF-PsychEngine#8917]
### What is your question?

how to change background middle song?(LUA)

I want Event and change background to value 1

**Comment by frantastic24** [comment]
There are a lot of posts about this already, look it up before asking #3137

**Comment by Lorekeeper49** [comment]
For static:
```lua
function onEvent(n, v1, v2)
    if n == 'bg change' then
        makeLuaSprite('newbg', v1) --will be made at (0,0)
        addLuaSprite('newbg', false)
    end
end
```
For animated:
```lua
function onEvent(n, v1, v2)
    if n == 'bg change' then
        makeAnimatedLuaSprite('newbg', v1) --will be made at (0,0)
        addAnimationByPrefix('newbg', v2, 24, true)
        addLuaSprite('newbg', false)
        objectPlayAnimation('newbg', v2, true)
    end
end

**Comment by MOON-on-GitHub** [comment]
> 

Thank you very much!

**Comment by frantastic24** [comment]
Precache your images if you're gonna use that

**Comment by Lorekeeper49** [comment]
> For animated:
> ```lua
> function onEvent(n, v1, v2)
>     if n == 'anim bg change' then
>         makeAnimatedLuaSprite('newbg', v1) --will be made at (0,0)
>         addAnimationByPrefix('newbg', v2, 24, true)
>         addLuaSprite('newbg', false)
>         objectPlayAnimation('newbg', v2, true)
>     end
> end
> ```

I made a mistake here, it's supposed to be this:
```lua
function onEvent(n, v1, v2)
    if n == 'anim bg change' then
        makeAnimatedLuaSprite('newbg', v1) --will be made at (0,0)
        addAnimationByPrefix('newbg', 'anim', v2, 24, true)
        addLuaSprite('newbg', false)
        objectPlayAnimation('newbg', 'anim', true)
    end
end
```

**Comment by oisintheblue** [comment]
i did it but the bg turned black

**Comment by diamond-124** [comment]
> Precache your images if you're gonna use that

how do i do that?

**Comment by frantastic24** [comment]
It's on the wiki
