### ISSUE TITLE
(if possible) using getProperty() (or similar) in a .lua script for character data

### ISSUE THREAD

**Issue by karma999-taken** [ShadowMario/FNF-PsychEngine#8918]
### Describe your problem here.

Exactly as the title says, I need to know if you can get character offsets from a .json character file, and animation names from .xml files using a .lua script. Thanks in advance

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by ManMaster707** [comment]
for offsets:
```lua
--replace 'boyfriend' with 'dad' or 'gf' for different characters
getProperty('boyfriend.offset.x')
getProperty('boyfriend.offset.y')
```
for animation names, I don't know how to get them from an xml, but you can check if they're being played:
```lua
--same thing here
if getProperty('boyfriend.animation.curAnim.name') == 'animationnamehere' then

**Comment by karma999-taken** [comment]
> for offsets:
> 
> ```lua
> --replace 'boyfriend' with 'dad' or 'gf' for different characters
> getProperty('boyfriend.offset.x')
> getProperty('boyfriend.offset.y')
> ```
> 
> for animation names, I don't know how to get them from an xml, but you can check if they're being played (animation names from the json though):
> 
> ```lua
> --same thing here
> if getProperty('boyfriend.animation.curAnim.name') == 'animationnamehere' then
> ```

>character offsets from a .json file
Here I'm still only getting them from an actual in-game character... thanks for the comment still

**Comment by ManMaster707** [comment]
> character offsets from a .json file
Here I'm still only getting them from an actual in-game character... thanks for the comment still

if you mean that, then It's the closest thing I could think of (also np)

**Comment by Mastercopper2346** [comment]
@ManMaster707 i blocked you

**Comment by TFLTV** [comment]
> @ManMaster707 i blocked you

r/Nobodyasked

**Comment by Lorekeeper49** [comment]
```lua
getProperty('character.offsets.x');
getProperty('character.offsets.y');
```
Replace 'character' with the character file name for the offsets you want to collect

**Comment by ManMaster707** [comment]
> @ManMaster707 i blocked you

but why? I did absolutely NOTHING to you. I just tried to answer this issue, at least tell me why.
