### ISSUE TITLE
How to hide timer using Lua?

### ISSUE THREAD

**Issue by JavoniCraft** [ShadowMario/FNF-PsychEngine#8919]
### Describe your problem here.

I want to hide the timer so players can't see how long the song is. Can someone give me a script to do so?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Added my own music and charting

**Comment by Phoneguytech75** [comment]
You could do this:
```lua
function onCreate()
    setProperty('timeBarBG.visible', false);
    setProperty('timeBar.visible', false);
    setProperty('timeTxt.visible', false);
end
```

**Comment by JavoniCraft** [comment]
Thank you, but is there script for hiding the healthbar too?

**Comment by Phoneguytech75** [comment]
> Thank you, but is there script for hiding the healthbar too?

Yes just add these to the onCreate function
```lua
setProperty('healthBar.alpha', 0)
setProperty('iconP1.alpha', 0)
setProperty('iconP2.alpha', 0)
```

**Comment by JavoniCraft** [comment]
Okay, thank you!

**Comment by frantastic24** [comment]
You can close this

**Comment by Steve35117** [comment]
`function oncreate()
setPropertyFromClass('ClientPrefs', 'timeBarType', 'Disabled)
end`
