### ISSUE TITLE
Custom characters crash the song almost instantly

### ISSUE THREAD

**Issue by VortexGotTaken** [ShadowMario/FNF-PsychEngine#892]
### Describe your problem here.

I have a custom character that I have been trying to add. I have check like 5 time and all the files are named correctly and the animations are correct in the character editor. When the song is loaded with the character it just sits in the first frame of its idle and after less then a second of the song playing the game crashes without an error message or anything. I followed the guide on the wiki step by step yet it refuses to work. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I have not edited any of the code, just added week and character files.

**Comment by ShadowMario** [comment]
Idle animation is named wrong, make it all lowercase, these are the correct idle animations names: `idle`, `danceLeft`, `danceRight`
