### ISSUE TITLE
Main Menu Items

### ISSUE THREAD

**Issue by anotheralone** [ShadowMario/FNF-PsychEngine#8920]
### Describe your problem here.

I'm having some problems with the game's Main Menu, for example, in attachment 1, you can see that the items are stuck together, and I have no idea how to separate them in the Source Code, I've tried several things, and nothing works.

![download](https://user-images.githubusercontent.com/106446845/172010959-b13615f2-c290-411d-b01b-b1ad9e76c730.png)

Version I'm using: 0.4.2

Code of menuItem:

		for (i in 0...optionShit.length)

		{
			var offset:Float = 108 - (Math.max(optionShit.length, 3) - 3) * 80;
			var menuItem:FlxSprite = new FlxSprite(0, (i * 140)  + offset);
			menuItem.scale.x = scale;
			menuItem.scale.y = scale;
			menuItem.frames = Paths.getSparrowAtlas('mainmenu/menu_' + optionShit[i]);
			menuItem.animation.addByPrefix('idle', optionShit[i] + " basic", 24);
			menuItem.animation.addByPrefix('selected', optionShit[i] + " white", 24);
			menuItem.animation.play('idle');
			menuItem.ID = i;
			menuItem.scale.set(0.6, 0.6);
			menuItem.y += 100;
			menuItem.x += 100;
			menuItems.add(menuItem);
			var scr:Float = (optionShit.length - 3) * 1.5;
			if(optionShit.length < 4) scr = 0;
			menuItem.scrollFactor.set(0, scr);
			menuItem.antialiasing = ClientPrefs.globalAntialiasing;
			//menuItem.setGraphicSize(Std.int(menuItem.width * 0.58));
			menuItem.updateHitbox();
		}`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited the FLA images, and removed 2 items (Achievements, FreePlay)

**Comment by Phoneguytech75** [comment]
Is the cog and the options text in the same file. If so you might want to separate them.
