### ISSUE TITLE
easily accessible dialogue music

### ISSUE THREAD

**Issue by TurboGames0731** [ShadowMario/FNF-PsychEngine#8921]
### What feature do you want to get added on the **base** engine?

i think in the dialogue editor, there should be a box where you type in the name of a song to play during the dialogue. (for example, if i wanted to have a song called RADIO play, i'd type in music/RADIO.)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
already can do in lua

**Comment by Lorekeeper49** [comment]
This is how the startDialogue function works
```lua
startDialogue(dialogueFile{string}, music{string})
```
dialogueFile{string}, as you might already know, is the dialogue json that you want to play which should go into the songs data folder

music{string} is the music that plays during the dialogue, the file goes in mods/music

**Comment by ShadowMario** [comment]
You can already do that both in lua and source code
