### ISSUE TITLE
How to play a cutscene first then dialogue?

### ISSUE THREAD

**Issue by EvcazinDeveloper** [ShadowMario/FNF-PsychEngine#8922]
### Describe your problem here.

Im making a countryballs mod and i don't know how to **play a cutscene, then have a dialogue**! Please help!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by anotheralone** [comment]
Code that ShadowMario had already sent for a question like this.

```
local allowCountdown = false;
local playDialogue = false;
function onStartCountdown()
	-- Block the first countdown and start a timer of 0.8 seconds to play the dialogue
	if not allowCountdown and isStoryMode and not seenCutscene then
		startVideo('videoCutscene');
		allowCountdown = true;
		playDialogue = true;
		return Function_Stop;
	elseif playDialogue then
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		playDialogue = false;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('dialogue', 'breakfast');
	end
end
```

**Comment by Mastercopper2346** [comment]
for me, it just freezes

**Comment by anotheralone** [comment]
> for me, it just freezes

Is your video in the example_mods/videos folder? (Or already compiled: in mods/videos folder)
