### ISSUE TITLE
AZERTY pls

### ISSUE THREAD

**Issue by Galbio** [ShadowMario/FNF-PsychEngine#8923]
### What feature do you want to get added on the **base** engine?

Add an AZERTY support because it's super annoying in character editor.
Otherwise with some xml it's required to change the animation name

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by frantastic24** [comment]
I believe that is a haxe limitation so not much can be done

**Comment by ManMaster707** [comment]
Don't the animation names on the xml don't matter? you can name an idle animation 'lol' and it could still work.

**Comment by Galbio** [comment]
I know but it's so boring for everything, like just an option where it would replace all keys (I was guessing that if there is a way to change the controls, changing from QWERTY to AZERTY was possible)

**Comment by frantastic24** [comment]
> haxe limitation

**Comment by ShadowMario** [comment]
Haxe limitation.
