### ISSUE TITLE
how do i detect when you beat a week and when you beat a song?

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#8924]
### What is your question?

title

**Comment by Lorekeeper49** [comment]
```lua
function onEndSong()
    --code
end
```
This is for beating a song, not sure about a week though

**Comment by machonessiebaby** [comment]
> ```lua
> function onEndSong()
>     --code
> end
> ```
> 
> This is for beating a song, not sure about a week though

i need source for granting achievements and game jolt trophies

**Comment by machonessiebaby** [comment]
youd think beating a week in source would be like

case 1 | 2 | 3
thing
end

**Comment by tylerandari12** [comment]
If the last song in a week is beaten in story mode, then your code should trigger...
(I'm on my phone so I can't give the actual code.)
