### ISSUE TITLE
Dialogue Issue

### ISSUE THREAD

**Issue by HurricaneSRB2** [ShadowMario/FNF-PsychEngine#8925]
### Describe your bug here.

When i added the script.lua file to play my dialogue, it played the song and the dialogue at the same time. Also, when the dialogue finishes, hold notes bug out and prevent you from holding them.

### Command Prompt/Terminal logs (if existing)

```bash
/Applications/Friday\ Night\ Funkin\'.app/Contents/MacOS/PsychEngine ; exit;
source/Discord.hx:18: Discord Client starting...
source/Discord.hx:68: Discord Client initialized
source/Discord.hx:25: Discord Client started.
source/Paths.hx:356: oh no its returning null NOOOO
source/Paths.hx:356: oh no its returning null NOOOO
source/Paths.hx:356: oh no its returning null NOOOO
source/LoadingState.hx:162: Setting asset folder to shared
source/Conductor.hx:75: new BPM map BUDDY []
source/FunkinLua.hx:81: lua file loaded succesfully:mods/Hurricane/data/whirlwind/script.lua
source/PlayState.hx:3245: LOADING NEXT SONG
source/PlayState.hx:3246: cyclone-hard
source/LoadingState.hx:162: Setting asset folder to shared
source/Conductor.hx:75: new BPM map BUDDY []
source/FunkinLua.hx:81: lua file loaded succesfully:mods/Hurricane/data/cyclone/script.lua
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by frantastic24** [comment]
This is a duplicate
![Screenshot_2022-06-04-15-39-26-468.jpg](https://user-images.githubusercontent.com/95725102/172021246-f3b6992d-18c5-4982-9c5e-3230aae57e5b.jpg)

**Comment by Mastercopper2346** [comment]
no

**Comment by Mastercopper2346** [comment]
i have the same problem

**Comment by HurricaneSRB2** [comment]
> This is a duplicate ![Screenshot_2022-06-04-15-39-26-468.jpg](https://user-images.githubusercontent.com/95725102/172021246-f3b6992d-18c5-4982-9c5e-3230aae57e5b.jpg)

So what is the link?

**Comment by HurricaneSRB2** [comment]
> This is a duplicate ![Screenshot_2022-06-04-15-39-26-468.jpg](https://user-images.githubusercontent.com/95725102/172021246-f3b6992d-18c5-4982-9c5e-3230aae57e5b.jpg)

No, its not a duplicate. I found where that was said and the person was making dialogue from source code, not lua.

**Comment by frantastic24** [comment]
It's a duplicate of other posts, the screenshot isn't related to that

**Comment by HurricaneSRB2** [comment]
> It's a duplicate of other posts, the screenshot isn't related to that The issue is also the exact same in source and Lua so it doesn't matter

Alright i fixed it anyway

**Comment by Aidentheawesome23** [comment]
how did you fix it

**Comment by HurricaneSRB2** [comment]
> how did you fix it

I put it on [game banana](https://gamebanana.com/mods/381724) with a bunch of other fixes. It should cause dialogue to work now
