### ISSUE TITLE
Chart Freeze + No Audio (Action Build)

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [ShadowMario/FNF-PsychEngine#8926]
### Describe your bug here.

[Click Here](https://youtu.be/ZMYP412bQlA)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No Action download

**Comment by ManMaster707** [comment]
Seems like the .ogg files aren't converted properly, if they come from any other type of file, go on google and search a converter from the original file extension to ogg, they're easy to find

**Comment by TFLTV** [comment]
> Seems like the .ogg files aren't converted properly, if they come from any other type of file, go on google and search a converter from the original file extension to ogg, they're easy to find

converters don't work on google just go in a audio editing software like audacity, FL studio or LMMS and export the original audio as a .ogg

**Comment by frantastic24** [comment]
> converters don't work on google 

Incorrect

**Comment by tylerandari12** [comment]
Iether the oggs aren't in format like stated above or your audio device isn't plugged in...

**Comment by SnakDev** [comment]
fnf uses ogg vorbis

**Comment by ImaginationSuperHero528** [comment]
Nvm was another software interrupting but it still happens sometimes.

**Comment by ArdoDev-stupid** [comment]
if it can't get the audio padding, that happens

**Comment by rodney528** [comment]
> > converters don't work on google 
> 
> Incorrect

Correct actually, online converters are bitches.
