### ISSUE TITLE
Note x

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8927]
### What is your question?

what are the x positions for each note? (including dad notes)

**Comment by Lupingllogi111** [comment]
_**defaultPlayerStrumX0 - Player's default left arrow X
defaultPlayerStrumY0 - Player's default left arrow Y
defaultOpponentStrumX0 - Opponent's default left arrow X
defaultOpponentStrumY0 - Opponent's default left arrow Y
defaultPlayerStrumX1 - Player's default down arrow X
defaultPlayerStrumY1 - Player's default down arrow Y
defaultOpponentStrumX1 - Opponent's default down arrow X
defaultOpponentStrumY1 - Opponent's default down arrow Y
defaultPlayerStrumX2 - Player's default up arrow X
defaultPlayerStrumY2 - Player's default up arrow Y
defaultOpponentStrumX2 - Opponent's default up arrow X
defaultOpponentStrumY2 - Opponent's default up arrow Y
defaultPlayerStrumX3 - Player's default right arrow X
defaultPlayerStrumY3 - Player's default right arrow Y
defaultOpponentStrumX3 - Opponent's default right arrow X
defaultOpponentStrumY3 - Opponent's default right arrow Y**_
Copy pasted

**Comment by Mastercopper2346** [comment]
Not really what I’m going for..

**Comment by hayfii** [comment]
> Not really what I’m going for..

You wanna know all the notes' x position?

**Comment by Mastercopper2346** [comment]
Yes

**Comment by hayfii** [comment]
> Yes

Here
```
0 = Left
1 = Down
2 = Up
3 = Right

Player: 0, Arrow 0 X Position: 92
Player: 0, Arrow 1 X Position: 204
Player: 0, Arrow 2 X Position: 316
Player: 0, Arrow 3 X Position: 428
Player: 1, Arrow 0 X Position: 732
Player: 1, Arrow 1 X Position: 844
Player: 1, Arrow 2 X Position: 956
Player: 1, Arrow 3 X Position: 1068
```

**Comment by Mastercopper2346** [comment]
Thanks!

**Comment by hayfii** [comment]
> Thanks!

No problem.
