### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Plotsh** [ShadowMario/FNF-PsychEngine#8929]
### What is your question?

How do i flip health bar im making a mod that you play on left side and need to flip health bar pls

**Comment by Mastercopper2346** [comment]
`setProperty('healthbar.angle', 180)`
try that

**Comment by Lorekeeper49** [comment]
> `setProperty('healthbar.angle', 180)`
> try that

That flips the colors around, not reverse the health

**Comment by Plotsh** [comment]
> `setProperty('healthbar.angle', 180)` try that

thats what i need, imma just reverse the icons now
