### ISSUE TITLE
Difficulty image not showing up?

### ISSUE THREAD

**Issue by ColdlordXRepositories** [ShadowMario/FNF-PsychEngine#8930]
### Describe your bug here.

![Friday Night Funkin'_ Psych Engine 6_4_2022 9_28_23 PM](https://user-images.githubusercontent.com/49921877/172030986-f53f0523-37eb-498e-8235-b06298814bb8.png)
![menudifficulties 6_4_2022 9_28_50 PM](https://user-images.githubusercontent.com/49921877/172030988-49afbc42-c675-47a2-bf98-9cee029c3dbb.png)
I did all I needed to do, and the difficulty image doesn't show up in story mode. Its simply just the last difficulty image shown. All other occurrences of the difficulty work fine, just not the image itself.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added a week, and a new difficulty.

**Comment by frantastic24** [comment]
It goes in mods not assets

**Comment by ColdlordXRepositories** [comment]
> It goes in mods not assets

oh

im an idiot

**Comment by ColdlordXRepositories** [comment]
> It goes in mods not assets

Which folder do I put it in? There is no folder called difficulties.

**Comment by frantastic24** [comment]
You can create folders

**Comment by BeastlyGhost** [comment]
> > It goes in mods not assets
> 
> Which folder do I put it in? There is no folder called difficulties.

it goes to mods/images/menudifficulties
