### ISSUE TITLE
how do u add a custom dialogue box

### ISSUE THREAD

**Issue by jaywronaldisdumb** [ShadowMario/FNF-PsychEngine#8931]
### Describe your problem here.

I wanna make the dialogue box a different image

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Lorekeeper49** [comment]
For a specific song or the entire mod?

**Comment by jaywronaldisdumb** [comment]
entire mod

**Comment by Lorekeeper49** [comment]
The original image for the dialogue box is called 'speech_bubble.png', just place an image in modpack/images with the same name and you should be good to go
