### ISSUE TITLE
How to add health drain in source code 

### ISSUE THREAD

**Issue by zeadd21g1233** [ShadowMario/FNF-PsychEngine#8932]
### What is your question?

help i need health drain

and you can stop it and make it work

like 

healthdrain = false;
start health drain

healthdrain = true;

ineed that 

i making cuphead

mechanics 

all things are ready

just i need healthdrain 
to mehcanic

what ido help pls

**Comment by BendyGaming0** [comment]
probably right before the death check you can have a line of code like:
`if (healthdrain)`
`health -= 0.5 * elapsed;`

**Comment by zeadd21g1233** [comment]
but how to make run and stop damage

**Comment by zeadd21g1233** [comment]
source/PlayState.hx:2284: characters 13-24 : Unknown identifier : healthdrain

**Comment by Randomxdp** [comment]
> source/PlayState.hx:2284: characters 13-24 : Unknown identifier : healthdrain

dumb
