### ISSUE TITLE
Multi-section copying.

### ISSUE THREAD

**Issue by EasonPlayz** [ShadowMario/FNF-PsychEngine#8934]
### What feature do you want to get added on the **base** engine?

Multi-section copying in the chart editor so that charters don't have to keep copying and pasting for forever.
Seriously, my fingers are tired of copying and pasting sections.

_**Consider this!!!!**_

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tylerandari12** [comment]
I will put this in a way Shadow Mario would put it...

"Stop being lazy."

I know I'm annoyed too...
