### ISSUE TITLE
Making Character Skins for the base game characters

### ISSUE THREAD

**Issue by Lividowly** [ShadowMario/FNF-PsychEngine#8936]
### What feature do you want to get added on the **base** engine?

You guys should implement a feature for making character mod skins as a character select screen, if you put a skin mod folder in the pysch's mod folder, it would be a nice way for beginner fnf modders to create a mod with reliative ease#8936

**Comment by Stilic** [comment]
no

**Comment by TheKitBoi** [comment]
Shadow Mario gives you a denied label

**Comment by frantastic24** [comment]
Deleting the test, that's a new one

**Comment by tylerandari12** [comment]
I feel instead they should have a thing where if a mod pack is installed, it should be checked before the assets folder...

This adds skin functionality without adding a new folder...

**Comment by frantastic24** [comment]
The engine already does that
