### ISSUE TITLE
Song does not load properly.

### ISSUE THREAD

**Issue by Likemea** [ShadowMario/FNF-PsychEngine#8937]
### Describe your bug here.

Hello, I made my own mod, and I already have the icons, weeks, sprites, etc. The only one problem I have, is that the song does not load correctly, and instead turns into a zero second long song, even though i put the files CORRECTLY. (yes, they're .ogg, yes they are in the assets/songs and mods/songs file.) I even double checked that everything is in place, and that everything is in a correct format.
![image](https://user-images.githubusercontent.com/106814227/172053847-04f75e0e-e6fc-4e2e-a805-a49c03f96bb2.png)
![image](https://user-images.githubusercontent.com/106814227/172053856-d88521e3-d05c-4f1b-97e7-6736f4807310.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment]
You exported your music files incorrectly so the game can't read them
There are many posts like this already

**Comment by Likemea** [comment]
> You exported your music files incorrectly so the game can't read them There are many posts like this already

Hi there, I exported them using Audacity. The files were originally mp3 so i used audacity and exported it into .ogg, then named the files ''Inst'' and ''Voices'' respectively. If that's the problem, what do I need to do? What kind of exporter do I need to use?

**Comment by frantastic24** [comment]
You can just use an online converter

**Comment by Likemea** [comment]
> You can just use an online converter
Alright, thanks. I'm going to try this. I'll come back and tell you if it works or not. Apologies for the inconveniences

**Comment by Likemea** [comment]
YO DUDE, IT WORKED! Thanks for the help!
