### ISSUE TITLE
"sys.io.File" package error

### ISSUE THREAD

**Issue by GDev28** [ShadowMario/FNF-PsychEngine#8938]
### Describe your bug here.

In the source version 5.0.2h and above there is an error on the WeekData script. 

### Command Prompt/Terminal logs (if existing)

```bash
"You cannot access the sys package while targeting js (for sys.io.File)"
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, this error is constant even when using clean source files from 5.0.2h and above

**Comment by Phoneguytech75** [comment]
I don't think that error should be showing when compiling to windows

**Comment by GDev28** [comment]
> I don't think that error should be showing when compiling to windows

But if you remove the package the error disappears

**Comment by Phoneguytech75** [comment]
Does it look like this in the file:
![image](https://user-images.githubusercontent.com/88546046/172067446-f106b812-2529-4a15-86e2-81f59c7f3986.png)
If not then you might want to change it.
The MODS_ALLOWED thing is only true if you are playing on pc
