### ISSUE TITLE
2nd character goes off of his offset

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#8941]
### Describe your problem here.

So i have this problem here that, when my second character plays a note, it keeps there, I NEED HELP ON THIS

Code:
`-- Script made by Catbrother Everything with help by NardBruh. Credit is not needed but would be nice! :)
--i modified the script actually for make better shit

leftoffsets = {'-9', '10'}
downoffsets = {'0', '-30'}
upoffsets = {'-6', '50'}
rightoffsets = {'0', '27'}
name_of_notetype = 'NOTE_player2'
name_of_notetype2 = 'both' -- you don't need this, but if you want a notetype that has multiple characters to sing you can use this.

function onCreate()
	makeAnimatedLuaSprite('Dad2', 'characters/WilliamOpponent', 400, 870); -- Change to characters idle in XML
	addAnimationByPrefix('Dad2', 'idle', 'WilliamOpponent idle', 20, false); -- Change to characters idle in XML
    addAnimationByPrefix('Dad2', 'singLEFT', 'WilliamOpponent left', 20, false); -- Change to characters leftnote in XML
    addAnimationByPrefix('Dad2', 'singDOWN', 'WilliamOpponent down', 20, false); -- Change to characters downnote in XML
    addAnimationByPrefix('Dad2', 'singUP', 'WilliamOpponent up', 20, false); -- Change to characters upnote in XML
    addAnimationByPrefix('Dad2', 'singRIGHT', 'WilliamOpponent right', 20, false); -- Change to characters rightnote in XML
	objectPlayAnimation('Dad2', 'idle');
	addLuaSprite('Dad2', false); -- false = add behind characters, true = add over characters
	scaleObject('Dad2', 0.8, 0.8);

	FlipX = false

	if FlipX == true then
		setPropertyLuaSprite('Dad2', 'flipX', true);
	else
		setPropertyLuaSprite('Dad2', 'flipX', false);
	end
end
function onCountdownTick(counter)
	-- counter = 0 -> "Three"
	-- counter = 1 -> "Two"
	-- counter = 2 -> "One"
	-- counter = 3 -> "Go!"
	-- counter = 4 -> Nothing happens lol, tho it is triggered at the same time as onSongStart i think
	if counter % 2 == 0 then
			objectPlayAnimation('Dad2', 'idle');
	end
end

function onBeatHit()
	-- triggered 4 times per section
	if curBeat % 2 == 0 then
		objectPlayAnimation('Dad2', 'idle');
		setProperty('Dad2' .. '.offset.x', idleoffsets[1]);
		setProperty('Dad2' .. '.offset.y', idleoffsets[2]);
	end
	doIdle = false
end

lastNote = {0, ""}

local singAnims = {"singLEFT", "singDOWN", "singUP", "singRIGHT"}
function opponentNoteHit(id, direction, noteType, isSustainNote)
	if noteType == name_of_notetype or noteType == name_of_notetype2 then
		objectPlayAnimation('Dad2', singAnims[direction + 1], false);

		if direction == 0 then
			setProperty('Dad2' .. '.offset.x', leftoffsets[1]);
			setProperty('Dad2' .. '.offset.y', leftoffsets[2]);

			if isSustainNote then
				objectPlayAnimation('Dad2', singAnims[direction + 1], true);
			end
		elseif direction == 1 then
			setProperty('Dad2' .. '.offset.x', downoffsets[1]);
			setProperty('Dad2' .. '.offset.y', downoffsets[2]);

			if isSustainNote then
				objectPlayAnimation('Dad2', singAnims[direction + 1], true);
			end
		elseif direction == 2 then
			setProperty('Dad2' .. '.offset.x', upoffsets[1]);
			setProperty('Dad2' .. '.offset.y', upoffsets[2]);

			if isSustainNote then
				objectPlayAnimation('Dad2', singAnims[direction + 1], true);
			end
		elseif direction == 3 then
			setProperty('Dad2' .. '.offset.x', rightoffsets[1]);
			setProperty('Dad2' .. '.offset.y', rightoffsets[2]);

			if isSustainNote then
				objectPlayAnimation('Dad2', singAnims[direction + 1], true);
			end
		end
	end
end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Why are the offsets strings

**Comment by Lorekeeper49** [comment]
First of all: the offset numbers should not be strings
And secondly:
```lua
setProperty('Dad2' .. '.offsets.x') --this is inefficient

setProperty('Dad2.offsets.x') --this is better

**Comment by frantastic24** [comment]
Also this
```lua
		if isSustainNote then
			objectPlayAnimation('Dad2', singAnims[direction + 1], true);
		end
```
?????
