### ISSUE TITLE
Window move help

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#8943]
### Describe your problem here.

i need some help making the window move down the screen this is my code so far
![image](https://user-images.githubusercontent.com/56323671/172074396-f8717163-fa91-4269-9522-81e203dbac4c.png)
i just need to make it move left or right but currently it does nothing

copy paste code so its easier to help with a fix
i think i may be too used to 4.2 then 5.2h but yk

```speed = 50

function onUpdate()
songPos = getSongPosition()
currentBeat = (songPos/5000)*(curBpm/60)

setPropertyFromClass('openfl.Lib','application.windows.x', math.cos(currentBeat*speed)*1250+1250)
setPropertyFromClass('openfl.Lib','application.windows.y', math.tan(currentBeat*speed)*1000+200)
end```






### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

sound changes and 2 custom achievements, 4 custom credits playstate.hx titlestate.hx main.hx healthicon.hx  a LOT MORE

**Comment by Itz-Miles** [comment]
I remember the respective tags being `'application.window.x'`, and `'application.window.y'`.

**Comment by machonessiebaby** [comment]
> I remember the respective tags being `'application.window.x'`, and `'application.window.y'`.



i fixed that but its still broke


```

**Comment by machonessiebaby** [comment]
```

**Comment by Itz-Miles** [comment]
I heard that they updated the syntax for the onUpdate() stuff. You could check the wiki to see what/when you want the script to work, paste what error the script is giving, check the script's file location, or even change what's in the script to look for differences. Otherwise, there's nothing wrong with the code now.

**Comment by machonessiebaby** [comment]
> I heard that they updated the syntax for the onUpdate() stuff. You could check the wiki to see what/when you want the script to work, paste what error the script is giving, check the script's file location, or even change what's in the script to look for differences. Otherwise, there's nothing wrong with the code now.

i may have fucked up the funkin lua when i added the gamejolt api who knows man also the wiki half the scripts dont work  on there anymore for me

**Comment by machonessiebaby** [comment]
im on the github build when they remove Awards grid
