### ISSUE TITLE
Dialogue plays during song even though i have the dialogue script in the scripts folder.

### ISSUE THREAD

**Issue by Aidentheawesome23** [ShadowMario/FNF-PsychEngine#8945]
### Describe your bug here.

when I play a song with dialogue, the song plays while the dialogue plays, and afterward either the inst stops playing or the song breaks.

### Are you modding a build from source or with Lua?

Source then built and used lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i changed the title menu and stuff but nothing related to gameplay.

**Comment by Mastercopper2346** [comment]
weird. give us your script

**Comment by Aidentheawesome23** [comment]
`local allowCountdown = false
function onStartCountdown()
	-- Block the first countdown and start a timer of 0.8 seconds to play the dialogue
	if not allowCountdown and isStoryMode and not seenCutscene then
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('dialogue', 'breakfast');
	end
end

-- Dialogue (When a dialogue is finished, it calls startCountdown again)
function onNextDialogue(count)
	-- triggered when the next dialogue line starts, 'line' starts with 1
end

function onSkipDialogue(count)
	-- triggered when you press Enter and skip a dialogue line that was still being typed, dialogue line starts with 1
end`

**Comment by acap09** [comment]
coloured version
```lua
local allowCountdown = false
function onStartCountdown()
-- Block the first countdown and start a timer of 0.8 seconds to play the dialogue
if not allowCountdown and isStoryMode and not seenCutscene then
setProperty('inCutscene', true);
runTimer('startDialogue', 0.8);
allowCountdown = true;
return Function_Stop;
end
return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
if tag == 'startDialogue' then -- Timer completed, play dialogue
startDialogue('dialogue', 'breakfast');
end
end

-- Dialogue (When a dialogue is finished, it calls startCountdown again)
function onNextDialogue(count)
-- triggered when the next dialogue line starts, 'line' starts with 1
end

function onSkipDialogue(count)
-- triggered when you press Enter and skip a dialogue line that was still being typed, dialogue line starts with 1
end
```

**Comment by tylerandari12** [comment]
better colored version
```lua
local allowCountdown = false
function onStartCountdown()
   -- Block the first countdown and start a timer of 0.8 seconds to play the dialogue
   if not allowCountdown and isStoryMode and not seenCutscene then
      setProperty('inCutscene', true);
      runTimer('startDialogue', 0.8);
      allowCountdown = true;
      return Function_Stop;
   end
   return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
   if tag == 'startDialogue' then -- Timer completed, play dialogue
      startDialogue('dialogue', 'breakfast');
   end
end

-- Dialogue (When a dialogue is finished, it calls startCountdown again)
function onNextDialogue(count)
   -- triggered when the next dialogue line starts, 'line' starts with 1
end

function onSkipDialogue(count)
   -- triggered when you press Enter and skip a dialogue line that was still being typed, dialogue line starts with 1
end
```

**Comment by Aidentheawesome23** [comment]
Guys I don’t need coloured version. I need to know how to solve the problem

**Comment by BernardoGP4504** [comment]
try putting the dialogue script in the song's chart folder
