### ISSUE TITLE
getting health color

### ISSUE THREAD

**Issue by 0-skid** [ShadowMario/FNF-PsychEngine#8950]
### Describe your problem here.

i need to get the healthbar color of the opponent for something with lua, how would i do that? i'm assuming if it's possible you need to use getProperty()

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by bruh1cat** [comment]
You can screenshot your screen and use the eyedropper tool in paint 3d or paint to get the color.

**Comment by 0-skid** [comment]
> You can screenshot your screen and use the eyedropper tool in paint 3d or paint to get the color.

yes but i want it to be automatic, if it's possible to do so

**Comment by bruh1cat** [comment]
I tried to do it but it gives 16777215, this is what I wrote: 
function onUpdate()
    debugPrint("Current health: ", getProperty("healthBar.color"))
end

**Comment by 0-skid** [comment]
huh, probably isn't possible then
