### ISSUE TITLE
Is there a list that list all properties?

### ISSUE THREAD

**Issue by Lupingllogi111** [ShadowMario/FNF-PsychEngine#8952]
### What is your question?

Is there a list of all the properties you can changed using setProperty(), setPropertyFromGroup(), etc?

**Comment by BuggieTheBug** [comment]
where do i find the list?

**Comment by TheKitBoi** [comment]
> where do i find the list?

https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Value-Setting-and-Getting-Functions
