### ISSUE TITLE
Chart not working properly

### ISSUE THREAD

**Issue by Likemea** [ShadowMario/FNF-PsychEngine#8953]
### Describe your bug here.

Hello, I have recently made a few charts for some custom songs. I saved them and put them in their respective folders. Expecting them to load in when I clicked ''Reload JSON'', I just got the default chart (when you load a song) and not the chart I made. What have I missed?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by machonessiebaby** [comment]
put in the name into box reload audio then json and make sure to load events sometimes too but this maybe due to some error im not an expert thats why i backup mine

**Comment by Likemea** [comment]
> This is likely an error on your part, explain what you mean by "default chart" A different song? Difficulty? Old chart??

Yes, a different, normal song like Bopeebo or Blammed.

**Comment by Likemea** [comment]
> put in the name into box reload audio then json and make sure to load events sometimes too but this maybe due to some error im not an expert thats why i backup mine

Doesn't work, sadly! I tried both case sensitive methods, and doing load events first, reload audio second and reload json third.

**Comment by frantastic24** [comment]
The game should just crash if the chart file isn't found so this is probably an issue with your chart, post all the difficulties

**Comment by Likemea** [comment]
> The game should just crash if the chart file isn't found so this is probably an issue with your chart, post all the difficulties

My song only has ''Hard'' difficulty, I don't know if adding easy and normal should fix it.

**Comment by 8bitjake** [comment]
you need a normal difficulty for reloading to work.

**Comment by frantastic24** [comment]
is the song in your json correct
![image](https://user-images.githubusercontent.com/95725102/172235618-3b0dae15-b9f2-4549-866f-d2c925e4da8a.png)
there's too little information for me to help much

**Comment by Likemea** [comment]
> is the song in your json correct ![image](https://user-images.githubusercontent.com/95725102/172235618-3b0dae15-b9f2-4549-866f-d2c925e4da8a.png) there's too little information for me to help much

Nope, Fresh is replaced by Interrogation. Also i have both normal and hard difficulties, i just checked.

**Comment by frantastic24** [comment]
Still needs more info
If the game isn't crashing then it's loading what you told it to load, I'd recommend trying to reload autosave and saving the file in the proper folder again if possible

**Comment by Lorekeeper49** [comment]
Make sure the json file itself is also named 'interrogation', if it's named anything that's in assets/data, it will go with that one no matter what for no known reason

**Comment by Likemea** [comment]
The interrogation json is located both in assets/data and mods/data and it still wont work. I'll update you on this after i try some common fixes, thanks!

**Comment by Likemea** [comment]
> still waiting for the files to be posted to see what the problem is

My apologies, but json files aren't supported in github. If you need any other files tell me.

**Comment by frantastic24** [comment]
you can change extensions

**Comment by Likemea** [comment]
> you can change extensions

ok
[interrogation.txt](https://github.com/ShadowMario/FNF
[interrogation-hard.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8856118/interrogation-hard.txt)
-PsychEngine/files/8856116/interrogation.txt)

**Comment by Likemea** [comment]
> both charts are just bopeebo?? it's loading bopeebo's chart because the chart is literally bopeebo

Yeah i think that's the issue, but I don't know how to make my own chart, so I just replaced it with bopeebo, thinking that it would overwrite it. Guess not.

**Comment by frantastic24** [comment]
So there there is no issue? If you want a blank chart there is a button to delete all notes
