### ISSUE TITLE
Mid Song Arrow go (bye bye)

### ISSUE THREAD

**Issue by EyadTheHedgehog** [ShadowMario/FNF-PsychEngine#8954]
### Describe your problem here.

hey so im trying to make the notes of the opponent to disappear and making the player's notes in the middle (like a middle chart)
in a middle of someting
i tried curStep and curBeat but it doesnt seem working
Help
![image](https://user-images.githubusercontent.com/68159082/172211460-233437f6-61b3-4a0e-b67d-75d2d1fbc22b.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
`function onStepHit()`
