### ISSUE TITLE
Code that checks the existence of a file

### ISSUE THREAD

**Issue by Shelvsk** [ShadowMario/FNF-PsychEngine#8956]
### What feature do you want to get added on the **base** engine?

is like:

`checkFileExistence(type:String, name:String)`

examples:

```
if not checkFileExistence('json', 'events') then
    close()
end
```

```
if checkFileExistence('png', 'somethingLmao') then
    --do anything
end
```

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tylerandari12** [comment]
`checkFileExistance(path:string)`
I would format it like this...

But this should be added lol...
