### ISSUE TITLE
Play An Animation When Note Pressed

### ISSUE THREAD

**Issue by WinV-Bros** [ShadowMario/FNF-PsychEngine#8957]
### Describe your problem here.

i want to make a note that plays an animation when you press the note.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Shelvsk** [comment]
this:

```
function goodNoteHit()
    characterPlayAnim('boyfriend', 'your animation', true)
end
```

if you want to do the animation on a specific note put this:

```
function goodNoteHit(noteType)
    if noteType == 'your Note' then
        characterPlayAnim('boyfriend', 'your animation', true)
    end
end
```

**Comment by WinV-Bros** [comment]
what if you wanted to play 2 animations? one after the other?

**Comment by Shelvsk** [comment]
try this:
```
function goodNoteHit()
    characterPlayAnim('boyfriend', 'your animation', true)
    runTimer('secondAnim', 0.76) --change the number value for the duration of the first animation
end

function onTimerCompleted(tag)
    if tag == 'secondAnim' then
        characterPlayAnim('boyfriend', 'second animation', true)
    end
end
```

if you used `noteType` just add the same runTimer on the if statement and put the function onTimerCompleted out of function goodNoteHit with the same code

**Comment by Lorekeeper49** [comment]
> ```lua
> function goodNoteHit(noteType)
>     if noteType == 'your Note' then
>         characterPlayAnim('boyfriend', 'your animation', true)
>     end
> end
> ```

What you're doing here won't exactly work as the character only plays the animation for like half a second that way (plus there's only one parameter and the first parameter is always the strumtime no matter how you name it).
Use this instead:
```lua
function goodNoteHit(i, d, t, l)
    if t == 'your Note' then
        triggerEvent('Play Animation', 'your animation', 'bf')
    end
end
```
This will make the note work and the entire animation will actually play
