### ISSUE TITLE
randomize

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#8958]
### Describe your problem here.

how to make random stuff
how to randomize things

randomize opponent

(I just genuinely don't know how to random things in Lua in like, any coding thing)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just modded in the "example_mods" folder

**Comment by Lorekeeper49** [comment]
```lua
math.random(min, max); --this calls a random number within the minimum and maximum numbers listed

**Comment by tylerandari12** [comment]
> ```lua
> math.random(min, max); --this calls a random number within the minimum and maximum numbers you placed

This works but it will generate the same output every time...
