### ISSUE TITLE
health drain lolololl

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#8959]
### Describe your problem here.

fatty:
```
function onUpdate()
	setProperty('health', health - 0.001);
end
```
doesn't work

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just modded in the "example_mods" folder

**Comment by CrusherMods** [comment]
setProperty('health', **getProperty(**health**)** - 0.001);

**Comment by frantastic24** [comment]
`addHealth(-0.001)` is simpler

**Comment by TFLTV** [comment]
> setProperty('health', **getProperty(**health**)** - 0.001);

dosen't work 🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀

**Comment by CrusherMods** [comment]
> > setProperty('health', **getProperty(**health**)** - 0.001);
> 
> 
> 
> dosen't work 🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀🗿🗿🗿💀💀💀

oh wait im a fucking idiot my bad try adding "" around **health** in the getProperty shit
