### ISSUE TITLE
isFreeplay

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#8960]
### What is your question?

Does isFreeplay or isFreePlay exist?

**Comment by frantastic24** [comment]
`isStoryMode`

**Comment by CrusherMods** [comment]
no
only isStoryMode exists

**Comment by bruh1cat** [comment]
> no only isStoryMode exists

Oh, but is there a way to idk play a sound when I enter freeplay?

**Comment by frantastic24** [comment]
it's the same thing
