### ISSUE TITLE
Cutscene in Freeplay

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#8961]
### What is your question?

How can I make a cutscene play in Freeplay and Story mode?

**Comment by frantastic24** [comment]
just don't check in you're in story mode

**Comment by bruh1cat** [comment]
> just don't check if you're in story mode

Can't believe it was that easy.

**Comment by MarkTent** [comment]
> just don't check if you're in story mode

I did that but then the game crashed right after the video finished playing
