### ISSUE TITLE
Animated icons

### ISSUE THREAD

**Issue by StickDeveloper** [ShadowMario/FNF-PsychEngine#8965]
I need help on how to make animated icons with an example and where to put the .lua file

**Comment by ThethingOP** [comment]
Find the script on game banana and put the .lua file on mods/data

**Comment by StickDeveloper** [comment]
> Find the script on game banana and put the .lua file on mods/data

do you know where the lua script is, like how I can find it?

**Comment by FlintIshe** [comment]
https://gamebanana.com/questions/24306
may be its this
