### ISSUE TITLE
Image scroll

### ISSUE THREAD

**Issue by FlintIshe** [ShadowMario/FNF-PsychEngine#8966]
### Describe your problem here.

How can i make this image scroll infinitely
![shit](https://user-images.githubusercontent.com/101379721/172291218-e52b5c11-f0a5-4dcd-9875-8504b344d0aa.png)

I have absolutely no idea

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Lorekeeper49** [comment]
Use tweens to make it move, the only thing I don't know how to do it make it loop

**Comment by Mastercopper2346** [comment]
i think i saw a few of these in mayos disscusions

**Comment by FlintIshe** [comment]
lol nvrm guess imma go to animate it then

**Comment by Mastercopper2346** [comment]
wait

**Comment by Mastercopper2346** [comment]
https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/809

left and right here
