### ISSUE TITLE
Trying to add new menu buttons.

### ISSUE THREAD

**Issue by AnthonyYTB** [ShadowMario/FNF-PsychEngine#8967]
### Describe your problem here.

I'm trying to add a new button to the main menu of my mod, but can't figure out how. I searched on YT and Google but i didn't find any tutorial. The button i want to add ("appearances") will allow the player to switch from different appearances for Boyfriend and Girlfriend. 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing expect in the mod folders.

**Comment by tylerandari12** [comment]
Is this on the main menu or is this before a song starts?

**Comment by Mastercopper2346** [comment]
not possible in lua, you need source code.

**Comment by AnthonyYTB** [comment]
> Is this on the main menu or is this before a song starts?

On the main menu

**Comment by AnthonyYTB** [comment]
> not possible in lua, you need source code.

Oh okay, but how do I do that exactly?

**Comment by hayfii** [comment]
You never know these Lua thingy only works on PlayState? lol
