### ISSUE TITLE
How can I make a Dodge Note animated? (LUA)

### ISSUE THREAD

**Issue by YourRedditor** [ShadowMario/FNF-PsychEngine#8972]
### Describe your problem here.

I've been trying to figure out how can I make a Dodge Note animated like the Halo Notes in The Vs Tricky mod?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Notes are automatically animated, just give them more frames

**Comment by TarnSpill** [comment]
In my opinion you need have "lua of notes" and animated them. After this you save with "png, xml" and in chart menu select notes
