### ISSUE TITLE
NPS thing

### ISSUE THREAD

**Issue by Plotsh** [ShadowMario/FNF-PsychEngine#8973]
### What is your question?

Yea its self explaining right? for the ppl who didnt understand, its the notes per second (NPS) 

does someone have it? 

forgot to say, its a script

**Comment by Meme1079** [comment]
```lua
local Nps = 0
local NoteHit = false;
function onStepHit()
    if NoteHit == true then
        Nps = Nps - 2 * 4 -- math is funny
    end    
end

function onUpdatePost(elapsed)
    local ratePercent = getProperty('ratingPercent') -- no more round!

    local ratingFull = math.max(ratePercent * 100, 0)
    local ratingFullAsStr = string.format("%.2f", ratingFull)
    -- ratingFull and ratingFullAsStr were taken from HaxeLua Complex Accuracy, so shout to him

    local BeforeScore = 'Score: '..score..' | Misses: '..misses..' | Rating: '..ratingName..' | NPS: '..Nps
    local FinalScore = 'Score: '..score..' | Misses: '..misses..' | Rating: '..ratingName..' ('..ratingFullAsStr..'%) - '..ratingFC..' | NPS: '..Nps

    if ratingName == '?' then
        setTextString('scoreTxt', BeforeScore)
    else
        setTextString('scoreTxt', FinalScore)  
    end

    if Nps < 0 then
        Nps = 0
        NoteHit = false;
    end   
end
    
function goodNoteHit(id, direction, noteType, isSustainNote)
    if not isSustainNote then
        Nps = Nps + 1
        NoteHit = false;
    end

    ezTimer('drain', 1, function()
        NoteHit = true;
    end)  
end

timers = {}
function ezTimer(tag, timer, callback) -- Better
    table.insert(timers,{tag, callback})
    runTimer(tag, timer)
end

function onTimerCompleted(tag)
    for k,v in pairs(timers) do
        if v[1] == tag then
            v[2]()
        end
    end
end
```

**Comment by Plotsh** [comment]
> ```lua
> local Nps = 0
> local NoteHit = false;
> function onStepHit()
>     if NoteHit == true then
>         Nps = Nps - 2 * 4 -- math is funny
>     end    
> end
> 
> function onUpdatePost(elapsed)
>     local ratePercent = getProperty('ratingPercent') -- no more round!
> 
>     local ratingFull = math.max(ratePercent * 100, 0)
>     local ratingFullAsStr = string.format("%.2f", ratingFull)
>     -- ratingFull and ratingFullAsStr were taken from HaxeLua Complex Accuracy, so shout to him
> 
>     local BeforeScore = 'Score: '..score..' | Misses: '..misses..' | Rating: '..ratingName..' | NPS: '..Nps
>     local FinalScore = 'Score: '..score..' | Misses: '..misses..' | Rating: '..ratingName..' ('..ratingFullAsStr..'%) - '..ratingFC..' | NPS: '..Nps
> 
>     if ratingName == '?' then
>         setTextString('scoreTxt', BeforeScore)
>     else
>         setTextString('scoreTxt', FinalScore)  
>     end
> 
>     if Nps < 0 then
>         Nps = 0
>         NoteHit = false;
>     end   
> end
>     
> function goodNoteHit(id, direction, noteType, isSustainNote)
>     if not isSustainNote then
>         Nps = Nps + 1
>         NoteHit = false;
>     end
> 
>     ezTimer('drain', 1, function()
>         NoteHit = true;
>     end)  
> end
> 
> timers = {}
> function ezTimer(tag, timer, callback) -- Better
>     table.insert(timers,{tag, callback})
>     runTimer(tag, timer)
> end
> 
> function onTimerCompleted(tag)
>     for k,v in pairs(timers) do
>         if v[1] == tag then
>             v[2]()
>         end
>     end
> end
> ```

i will test it and say if it works

**Comment by Plotsh** [comment]
holy shi thx so much

**Comment by Plotsh** [comment]
yo, @Meme1079 can ya make it compatible wih another huds? cuz i tried it and it just got disabled when i used another hud heres the screenshot of the 2 huds enabled
![Screenshot_20220609-172155](https://user-images.githubusercontent.com/84821153/172950168-83640f97-05bd-4c6e-9b69-0259289f9239.png)

**Comment by Plotsh** [comment]
nvm got it
