### ISSUE TITLE
Force animation

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#8974]
### Describe your problem here.

How can I force a character to play a animation even though they're already playing one?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
The current animation is overridden if you play another one

**Comment by frantastic24** [comment]
singing will also override your animation

**Comment by Mastercopper2346** [comment]
Wait

**Comment by Mastercopper2346** [comment]
I’m making a script for this

**Comment by Mastercopper2346** [comment]
Wait till I make it

**Comment by bruh1cat** [comment]
Sure but I’ll test it tomorrow
