### ISSUE TITLE
how to change visual rating

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#8976]
### Describe your problem here.

I made an issue (enhancement) #8782 for visual ratings 

@ShadowMario said "You can mess with rating in lua now"
how would I use the new function, do I have to reinstall the source or uh... do other stuff?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just modded in the "example_mods" folder

**Comment by tylerandari12** [comment]
For once the wiki has something for this...
Check [this](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#scoreaccuracy-functions) for more info.

**Comment by frantastic24** [comment]
That's not what they asked for

**Comment by TFLTV** [comment]
sick

**Comment by TFLTV** [comment]
> That's not what they asked for
> 
> ```lua
> setProperty('ratingsData[0].image', 'image') --change "Sick" image
> ```
> 
> Read the commit changes for more info

where are the commit chnages

**Comment by frantastic24** [comment]
In commits lol

**Comment by TFLTV** [comment]
> In commits lol

**where is that**

**Comment by TFLTV** [comment]
okay `setProperty('ratingsData[0].image', 'image') --change "Sick" image` dosen't work uh... Do I need to download something?????????????????

**Comment by tylerandari12** [comment]
> That's not what they asked for
> 
> ```lua
> setProperty('ratingsData[0].image', 'image') --change "Sick" image
> ```
> Read the commit changes for more info

I thought this was only possible in source 0-0

**Comment by TFLTV** [comment]
> > That's not what they asked for
> > ```lua
> > setProperty('ratingsData[0].image', 'image') --change "Sick" image
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Read the commit changes for more info
> 
> I thought this was only possible in source 0-0

pretty sure shadow mario added it recently
