### ISSUE TITLE
Sprites playing once then not working

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#8977]
### Describe your problem here.

When I first put the event the sprites appear but after that it doesn't.

function onCreate()
--variables
Dodged = false;
canDodge = false;
DodgeTime = 0;
precacheImage('slash hit')
makeAnimatedLuaSprite('slash hit', 'slash hit', 1010, 600)
scaleLuaSprite('slash hit', 1, 1)
setObjectCamera('slash hit', 'game')
luaSpriteAddAnimationByPrefix('slash hit', 'slash hit', 'slash hit', 12, true)
luaSpritePlayAnimation('slash hit', 'slash hit')

precacheImage('slash')
makeLuaSprite('slash', 'slash', 200, 300)
scaleLuaSprite('slash', 1, 1)
setObjectCamera('slash', 'game')
setProperty('slash.alpha', 0.9)
end

function onEvent(name)
if name == "jaduAttack" then
--Get Dodge time
DodgeTime = (1)

--Make Dodge Sprite
addLuaSprite('slash', true)
doTweenX('slashxtween', 'slash', 900, 0.5, 'linear')
doTweenY('slashytween', 'slash', 640, 0.5, 'linear')

makeAnimatedLuaSprite('spacebar', 'spacebar', 520, 150)
luaSpriteAddAnimationByPrefix('spacebar', 'spacebar', 'spacebar', 24, true)
luaSpritePlayAnimation('spacebar', 'spacebar')
setObjectCamera('spacebar', 'other')
scaleLuaSprite('spacebar', 1, 1);
addLuaSprite('spacebar', true)

--Set values so you can dodge
canDodge = true;
runTimer('Died', DodgeTime);

end
end

function onUpdate()
if canDodge == true and keyJustPressed('space') then

Dodged = true;
addLuaSprite('slash hit', true)
doTweenAlpha('spacebarAlpha', 'spacebar', 0, 0.5, 'linear')
canDodge = false

end
end

function onTimerCompleted(tag, loops, loopsLeft)
if tag == 'Died' and Dodged == false then
setProperty('health', -2)
removeLuaSprite('spacebar')
removeLuaSprite('slash hit')
removeLuaSprite('slash')

elseif tag == 'Died' and Dodged == true then
Dodged = false
removeLuaSprite('slash hit')
removeLuaSprite('slash')

end
end

function onTweenCompleted()
if tag == 'spacebarAlpha' then
removeLuaSprite('spacebar')
end
end

Here's a video about it:

https://youtu.be/KI0qvnzMphA

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Because you deleted the sprites

**Comment by bruh1cat** [comment]
> Because you deleted the sprites

I'm and idiot

**Comment by bruh1cat** [comment]
> Because you deleted the sprites

How come the spacebar sprite was still there?

**Comment by frantastic24** [comment]
Because unlike the slash sprites, it's created every time the event is called

**Comment by bruh1cat** [comment]
Ok so, if I move 
precacheImage('slash hit')
    makeAnimatedLuaSprite('slash hit', 'slash hit', 1010, 600)
    scaleLuaSprite('slash hit', 1, 1)
    setObjectCamera('slash hit', 'game')
    luaSpriteAddAnimationByPrefix('slash hit', 'slash hit', 'slash hit', 12, true)
	luaSpritePlayAnimation('slash hit', 'slash hit')
    
    precacheImage('slash')
    makeLuaSprite('slash', 'slash', 200, 300)
    scaleLuaSprite('slash', 1, 1)
    setObjectCamera('slash', 'game')
    setProperty('slash.alpha', 0.9)

to the function onEvent() then it'll be fixed?

**Comment by frantastic24** [comment]
It'd probably be easier to just add `false` at the end of each `removeLuaSprite()` so the sprites aren't destroyed
