### ISSUE TITLE
Custom menus

### ISSUE THREAD

**Issue by LeonGamerPS4** [ShadowMario/FNF-PsychEngine#8978]
### What is your question?

how do i add entirely custom menus to the engine?
in other words, i want to make the menus look like this
![608534d89b7ff 1](https://user-images.githubusercontent.com/98667115/172500354-3b8cd5dd-2f7f-4534-b6f2-2e9dd97b3630.jpg)

**Comment by TarnSpill** [comment]
- Well, it can be done. For this you need "source code and working compile" and minimal knowledge about "fnf PE encoding"
There is links for tutorial: https://youtu.be/J8tE2fR8h9o
(sorry for bad Eng, I try to help how I can)
