### ISSUE TITLE
source/PlayState.hx:506: characters 3-7 : Expected }

### ISSUE THREAD

**Issue by LucasOnGithub** [ShadowMario/FNF-PsychEngine#8979]
### Describe your bug here.

I was adding a stage to my mod and then the code broke for some reason I can't figure out. if someone could help me fix it, it would really help out.

![image](https://user-images.githubusercontent.com/35154566/172507327-1cdd367b-9216-4d35-bea8-b20b9befba48.png)

![image](https://user-images.githubusercontent.com/35154566/172507263-4cb9a237-5d67-45db-a053-c3818c7d7d9f.png)

### Command Prompt/Terminal logs (if existing)

```bash
I don't have any but the stage code is on 506-526.
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited playstate.hx for the stage

**Comment by SrtHero278** [comment]
![image](https://user-images.githubusercontent.com/93018286/172510516-a6d817a3-1ca3-4e42-be86-988e8638bbea.png)
try removing these. unless you're using if statements or loops, switch statements should only have two brackets.

**Comment by LucasOnGithub** [comment]
> Reference in new issue

i did that and it still gives the exact same error. i dont know why this is happening

![image](https://user-images.githubusercontent.com/35154566/172513065-f2a4cc6e-a705-43eb-b87c-fa8b0fb6c76b.png)

![image](https://user-images.githubusercontent.com/35154566/172513113-7d26a372-793f-4086-bcbc-2aa059a71818.png)

**Comment by QuestioningAccount** [comment]
not really big on coding but i think you messed up here
![image](https://user-images.githubusercontent.com/101908449/172516428-b329c7b1-932b-4b75-aa81-82c70f853b2f.png)

**Comment by QuestioningAccount** [comment]
![image](https://user-images.githubusercontent.com/101908449/172516491-85963976-4d13-42ee-a627-f552e6cd22e0.png)
i think you messed up here, not exactly big on coding so idk

**Comment by LucasOnGithub** [comment]
I don't know what to do it just won't fix. I need someone to help me out because I have no idea on how to fix this. this is a difficult error to deal with :(

![image](https://user-images.githubusercontent.com/35154566/172737377-35c82d36-0adc-422a-843f-a3370422d980.png)

**Comment by LucasOnGithub** [comment]
all the code i added was broken

**Comment by LucasOnGithub** [comment]
none of it worked

**Comment by LucasOnGithub** [comment]
i wanna die now
