### ISSUE TITLE
Screen shake only during alt animations

### ISSUE THREAD

**Issue by AntCrem** [ShadowMario/FNF-PsychEngine#8980]
### Describe your problem here.

How can I make it so the screen shakes only when the opponent is using their alt animations? 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nu

**Comment by frantastic24** [comment]
`if noteType == 'Alt Animation' or altAnim then`
