### ISSUE TITLE
Camera flashing on beat

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#8981]
### Describe your problem here.

I want to make a script that is somewhat like this:

function onStepHit()
if curStep == ??? then
cameraFlash('game', '???', onBeat, forced:Bool)

Basically I want it to start flashing on beat but start at a certain point then end on another point.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Shelvsk** [comment]
i don't know if this will works but try this:

```
function onStepHit()
    if curStep == 1 then --change the 1 number for the your step value
        cameraFlash('game', 'FFFFFF', onBeat, false) --change the FFFFFF for your color in hex
    end
end
```

**Comment by frantastic24** [comment]
```lua
function onBeatHit()
     if flashingLights and curBeat >= startBeat and curBeat <= endBeat then

     end
end
```
