### ISSUE TITLE
Can u use a cutscene and a dialouge in a song

### ISSUE THREAD

**Issue by Fortfight** [ShadowMario/FNF-PsychEngine#8983]
### What is your question?

i downloaded both of them and it didnt work

**Comment by bruh1cat** [comment]
[cutscene then dialogue.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8858423/cutscene.then.dialogue.zip)

**Comment by Fortfight** [comment]
> [cutscene then dialogue.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8858423/cutscene.then.dialogue.zip)

thanks

**Comment by bruh1cat** [comment]
np

**Comment by bruh1cat** [comment]
> > [cutscene then dialogue.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8858423/cutscene.then.dialogue.zip)
> 
> thanks

Here's the opposite just in cas
[song then cutscene.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8865484/song.then.cutscene.zip)
e

**Comment by Fortfight** [comment]
it didnt work for me

**Comment by bruh1cat** [comment]
It has to be exactly like the file name

**Comment by Fortfight** [comment]
i did that it just skips to the dialoge

**Comment by bruh1cat** [comment]
What exactly is the problem?

**Comment by Fortfight** [comment]
i am trying to play the dialouge and the cutscene (sorry about switching it)

**Comment by bruh1cat** [comment]
Like immediately after the diayor agter the song ends?

**Comment by Fortfight** [comment]
after the cutscene i was tying to get the dialoge to play

**Comment by Fortfight** [comment]
yes

**Comment by bruh1cat** [comment]
Well sorry but I can’t help you maybe try downloading the original, https://gamebanana.com/tools/7845

**Comment by Fortfight** [comment]
so do you remove the dialoge script

**Comment by bruh1cat** [comment]
If its the one that contains the dialogue, no if it’s the script that I gave you save it just in case

**Comment by Fortfight** [comment]
or the ctsceen script or both

**Comment by Fortfight** [comment]
thanks for trying to help

**Comment by Fortfight** [comment]
thanks for trying to help
