### ISSUE TITLE
Random Death Quotes

### ISSUE THREAD

**Issue by Al-AmeenAdewunmi** [ShadowMario/FNF-PsychEngine#8984]
### Describe your problem here.

Yeah, so I'm trying to figure out how to add randomized death quotes to a song similar to Week 7. I know this was asked and answered before, but that was only for Source, not Lua. And I've tried using pieces of code I've searched for and have been unsuccessful. So what can I do?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Lupingllogi111** [comment]
```
function onGameOver()
        quote = math.random([minimum value], [maximum value])
         runTimer([your values])
end
function onTimerCompleted(tag, loops, loopsLeft)
          if tag == '(your tag)' then
                    if quote == (value) then  
                                playSound([file], 1)
                    elseif quote == (value 2) then
                                playSound([file], 1
                     (repeat until you have done all of your quotes)
                    end
        end
                    
end
```
Not tested, so I don't know if it works

**Comment by Al-AmeenAdewunmi** [comment]
> ```
> function onGameOver()
>         quote = math.random([minimum value], [maximum value])
>          runTimer([your values])
> end
> function onTimerCompleted(tag, loops, loopsLeft)
>           if tag == '(your tag)' then
>                     if quote == (value) then  
>                                 playSound([file], 1)
>                     elseif quote == (value 2) then
>                                 playSound([file], 1
>                      (repeat until you have done all of your quotes)
>                     end
>         end
>                     
> end
> ```
> 
> Not tested, so I don't know if it works

I keep getting "unexpected symbol near '[' ". Also what do I put in for "your tag"?

**Comment by frantastic24** [comment]
You're not supposed to keep these `[ ]`, read the wiki script examples to learn basic syntax

**Comment by Al-AmeenAdewunmi** [comment]
Okay, I got past the error messages, so I think I'm getting somewhere. However the sound files still don't load up when getting a Game Over. They're simply named "1.ogg, 2.ogg, etc". This is my current setup.

```
function onGameOver()
        quote = math.random(1, 3)
         runTimer(1, 2, 3)
end
function onTimerCompleted(tag, loops, loopsLeft)
          if tag == '(your tag)' then
                    if quote == (1) then  
                                playSound(file, 1)
                    elseif quote == (2) then
                                playSound(file, 2)
                    end
        end
                    
end
```

**Comment by frantastic24** [comment]
File paths and tags are strings, surrounded by `' '`, again, read examples

**Comment by Al-AmeenAdewunmi** [comment]
Tried looking at examples. I have this typed in now but it's still not working. Isn't it possible you could just, correct the code for me or something?

```
function onGameOver()
        quote = math.random(1, 3)
         runTimer(1, 2, 3)
end
function onTimerCompleted(tag, loops, loopsLeft)
          if tag == '1' then
                    if quote == (1) then  
                                playSound('1', 1)
                    elseif quote == (2) then
                                playSound('2', 1)
					elseif quote == (3) then
                                playSound('3', 1)
                    end
        end
                    
end
```

**Comment by frantastic24** [comment]
```lua
runTimer('1', 2, 1) --tag wasn't a string and it was set to play 3 times
```

**Comment by Al-AmeenAdewunmi** [comment]
Uh, when I inserted that code, something went wrong. BF can't die even when pressing R for a quick restart. But when I go to the pause menu, that's when the audio files start to load. So basically, the files load, but now the Game Over is broken. Now what?

**Comment by frantastic24** [comment]
Add `return Function_Continue` at the end of `onGameover()`

**Comment by Al-AmeenAdewunmi** [comment]
Like this?
```
function onGameOver()
        quote = math.random(1, 3)
         runTimer('1', 2, 1)
		return Function_Continue
end
```

**Comment by Lorekeeper49** [comment]
Don't use `math.random(min, max)`, for whatever reason, it outputs the same value every single time, use `getRandomInt(min, max)` instead

**Comment by Al-AmeenAdewunmi** [comment]
Well uh, thanks, but I'm still stumped by my setup. Currently it's looking like:

```
function onGameOver()
        quote = getRandomInt(1, 3)
         runTimer('1', 2, 1)
return Function_Continue
end

function onTimerCompleted(tag, loops, loopsLeft)
          if tag == '1' then
                    if quote == (1) then  
                                playSound('1', 1)
                    elseif quote == (2) then
                                playSound('2', 1)
					elseif quote == (3) then
                                playSound('3', 1)
                    end
        end
                    
end
```

**Comment by Al-AmeenAdewunmi** [comment]
Still nothing.

**Comment by Al-AmeenAdewunmi** [comment]
Oh shit, it works perfectly now. The Game Over loads and the audio files load. Nice. Thanks.
