### ISSUE TITLE
Zoom out

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#8986]
### Describe your problem here.

How do I make this zoom out?

function onEvent(name, value1, value2)
    if Name == 'tween zoom (end)' then
        doTweenZoom('tween zoom (end)', 'camGame', value1, value2, 'linear')
    end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by tylerandari12** [comment]
Set `value1` to a number below `1` such as `0.5`...

**Comment by bruh1cat** [comment]
> Set `value1` to a number below `1` such as `0.5`...

I’ll show you what the problem is tomorrow bc it’s really late for me rn.

**Comment by frantastic24** [comment]
value2 is duration, [it's on the wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers)

**Comment by bruh1cat** [comment]
> value2 is duration, [it's on the wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers)

That's what I put as value 2 but it dosent work like the original event

**Comment by frantastic24** [comment]
idk what this "original event" is

**Comment by bruh1cat** [comment]
> idk what this "original event" is

Sorry for not explaining it well, but I'm trying to replicate a event that was made on source code to lua. The original event has these two values: 
tween zoom (start)",
"2",
"2"

"tween zoom (end)",
"2",
"2"

But when I tried to put value 1 to zoom it worked but duration to value 2 it doesn't seem to work, so idk what is value 2

**Comment by bruh1cat** [comment]
Original: https://youtu.be/T7R6iVN7LjQ?t=857

Mine:
https://user-images.githubusercontent.com/98327930/172697192-40558306-31f3-412b-9f16-1859e0b6e442.mp4
