### ISSUE TITLE
Good and bad ending

### ISSUE THREAD

**Issue by joxu13v** [ShadowMario/FNF-PsychEngine#8987]
### Describe your problem here.

I want to make a good or bad ending based on the mises of the song like sky, using the stage file

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
```lua
badEndingMisses = 5;
skipSongEnds = 1; --don't change this
function onEndSong()
    if skipSongEnds > 0 then
        if getMisses() >= badEndingMisses then
            --do your bad ending shit here
        else
            --do your good ending shit here
        end
        return Function_Stop;
    end
    return Function_Continue;
end
```

**Comment by Mastercopper2346** [comment]
Omg shadow Mario

**Comment by Destrug** [comment]
How to make different paths like sans in indie cross but based on how much u pressed a "mod chart note"?

**Comment by Usakima966** [comment]
> ```lua
> badEndingMisses = 5;
> skipSongEnds = 1; --don't change this
> function onEndSong()
>     if skipSongEnds > 0 then
>         if getMisses() >= badEndingMisses then
>             --do your bad ending shit here
>         else
>             --do your good ending shit here
>         end
>         return Function_Stop;
>     end
>     return Function_Continue;
> end
> ```

where do i put it in im a beginer
