### ISSUE TITLE
Bug Report: Game Fails To Compile

### ISSUE THREAD

**Issue by Gibberditoslumber** [ShadowMario/FNF-PsychEngine#8989]
### Describe your bug here.

I Compiled the game and this happend 
|
|
|
|
|
|
\/
### Command Prompt/Terminal logs (if existing)

```bash
myname@penguin:~/haxelib/FNF-PsychEngine$ lime test linux
source/FunkinLua.hx:2491: characters 7-36 : Bool should be Int
source/FunkinLua.hx:341: lines 341-345 : Int should be Bool
source/FunkinLua.hx:341: lines 341-345 : For function argument 'f'
source/FunkinLua.hx:447: lines 447-450 : Int should be Bool
source/FunkinLua.hx:447: lines 447-450 : For function argument 'f'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux x86_64

### Did you edit anything in this build? If so, mention or summarize your changes.

none

**Comment by theo2yeah** [comment]
do on cmd:
`haxelib remove linc_luajit`
then do:
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

**Comment by Phoneguytech75** [comment]
> ```shell
> lime test linux
> ```

I've tried linux once on github codespaces. It doesn't work.

**Comment by Gibberditoslumber** [comment]
it does

**Comment by Gibberditoslumber** [comment]
i tested it with my terminal

**Comment by Gibberditoslumber** [comment]
and its Debian

**Comment by Mastercopper2346** [comment]
Try getting a fresh FunkinLua.hx

**Comment by Phoneguytech75** [comment]
> i tested it with my terminal

hmmm maybe it's a codespace problem

**Comment by Phoneguytech75** [comment]
Oh never mind. I didn't know there was a patch out for it.

**Comment by Gibberditoslumber** [comment]
loading mods kill the game now:
`source/Discord.hx:68: Discord Client initialized`
`source/Discord.hx:18: Discord Client starting...`
`source/Discord.hx:25: Discord Client started.`
`source/Paths.hx:356: oh no its returning null NOOOO`
`source/Paths.hx:356: oh no its returning null NOOOO`

`[file_contents,assets/data/atrocity/atrocity-hard.json]`
`Error : [file_contents,assets/data/atrocity/atrocity-hard.json]`

**Comment by hayfii** [comment]
> loading mods kill the game now:
> 
> ```shell
> source/Discord.hx:68: Discord Client initialized
> source/Discord.hx:18: Discord Client starting...
> source/Discord.hx:25: Discord Client started.
> source/Paths.hx:356: oh no its returning null NOOOO
> source/Paths.hx:356: oh no its returning null NOOOO
> 
> [file_contents,assets/data/atrocity/atrocity-hard.json]
> Error : [file_contents,assets/data/atrocity/atrocity-hard.json]
> ```

Uh, it says atrocity-hard.json is missing.

**Comment by Gibberditoslumber** [comment]
don't ask
