### ISSUE TITLE
"Record mode" for chart editor

### ISSUE THREAD

**Issue by EpsilonTheDerg** [ShadowMario/FNF-PsychEngine#8990]
### What feature do you want to get added on the **base** engine?

A mode or toggle in the chart editor that lets you place arrows on the left four columns with your actual player keys (and maybe on the right four with the alt player keys) at the conductor's strum time (aligned to the grid, of course) as the song is playing. I'm often not confident in my charts actually being fun to play when I simply draw them out with the mouse and redoing large portions of a project discourages me. It'd be fun to instead ad-lib along with a song to see what naturally comes out of my fingers.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by TFLTV** [comment]
vortex editor (use keys 1234 for the first 4 and 5678 for the others)

**Comment by EpsilonTheDerg** [comment]
Oh is that what that is

Huh

Nevermind
