### ISSUE TITLE
Score counter

### ISSUE THREAD

**Issue by jayprr** [ShadowMario/FNF-PsychEngine#8993]
### Describe your problem here.

Is there any way to get the score counter that is seen in the base game?
![image](https://user-images.githubusercontent.com/107157112/172735613-656d6e95-2625-4a5d-88b2-88cb2359b0d1.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by bruh1cat** [comment]
[Custom Info Bar v5.1.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8865722/Custom.Info.Bar.v5.1.zip)


Hope this helps

**Comment by bruh1cat** [comment]
I edited that one to only show the score combo and misses, here's the original one https://gamebanana.com/tools/9217

**Comment by bruh1cat** [comment]
> > 
> 
> Yeah that works fine! is there any way to just change it to the score count without the misses and combo? :)

Sorry for responding so late, I'll edit it to that if I can.

**Comment by bruh1cat** [comment]
Like this
![Screenshot (173)](https://user-images.githubusercontent.com/98327930/172900185-ec7bf8b2-107b-470e-854f-98e4a7c8dd4d.png)
?

**Comment by bruh1cat** [comment]
Or do you want the 0 to be closer to the :

**Comment by jayprr** [comment]
> Or do you want the 0 to be closer to the :

Just a little closer would be fine :)

**Comment by jayprr** [comment]
> So like this ![Screenshot (174)](https://user-images.githubusercontent.com/98327930/172901528-3b261285-445b-43e9-89d3-f3e37eb77408.png)
that is perfect!

**Comment by jayprr** [comment]
yeah that is perfect!

**Comment by bruh1cat** [comment]
[Custom Info Bar v5.1.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8872364/Custom.Info.Bar.v5.1.zip)

**Comment by jayprr** [comment]
woah, how did you even edit the script to say that?

**Comment by bruh1cat** [comment]
To say what?

**Comment by bruh1cat** [comment]
No problem :)
