### ISSUE TITLE
Add A 'Tutorial' label

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#8995]
### What feature do you want to get added on the github page?

I understand if you don't want to do it, but it will be very helpful.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
Oops I misclicked

**Comment by frantastic24** [comment]
That's not what issues are for

**Comment by Mastercopper2346** [comment]
I know, but he deleted the discussions mmm

**Comment by ShadowMario** [comment]
That's still literally not what Issues are for, if you want Tutorials try this magical website:
https://www.google.com/
