### ISSUE TITLE
Compiling is not working right

### ISSUE THREAD

**Issue by Sonicwithtophat** [ShadowMario/FNF-PsychEngine#8996]
### What needs to be documented?

C:\Users\Owner\Downloads\FNF-PsychEngine-main\FNF-PsychEngine-main>lime test windows
source/Achievements.hx:132: characters 30-54 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/MainMenuState.hx:66: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:365: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/CharacterEditorState.hx:94: characters 3-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/editors/DialogueCharacterEditorState.hx:87: characters 3-40 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:/Users/Owner/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:145: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/Users/Owner/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:180: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/Users/Owner/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:221: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/Users/Owner/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:515: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/Users/Owner/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:483: characters 37-56 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/Users/Owner/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:484: characters 31-47 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/Users/Owner/haxe/haxe/lib/hscript/2,4,0/hscript/Interp.hx:646: characters 10-42 : Warning : Std.is is deprecated. Use Std.isOfType instead.
source/options/NoteOffsetState.hx:57: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\Owner\Downloads\FNF-PsychEngine-main\FNF-PsychEngine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths

what do these mean.

**Comment by Wither362** [comment]
Install visua studio and vs code

**Comment by frantastic24** [comment]
VS Code isn't necessary

**Comment by Wither362** [comment]
> VS Code isn't necessary

For me it was…

**Comment by Sonicwithtophat** [comment]
@Wither362 Ya'll, i have Visual studio

**Comment by Sonicwithtophat** [comment]
> It's just a code editor, you don't need it to compile

what must i do

**Comment by FlintIshe** [comment]
use windows powershell god dammit

**Comment by Sonicwithtophat** [comment]
@FlintIshe "C:\Users\Owner\Downloads\FNF-PsychEngine-main\FNF-PsychEngine-main>lime test windows" literally from the powershell

**Comment by frantastic24** [comment]
> @frantastic24 for 64 but pcs, you DO need visual studio

I was talking about code and why did you ping me

**Comment by Itz-Miles** [comment]
I had a [pull request](https://github.com/ShadowMario/FNF-PsychEngine/blob/aae6b044668126526a188a60c0a4f7bfd8fa49ab/README.md) up that goes over compilation instructions. Follow them, and it should compile.

**Comment by Sonicwithtophat** [comment]
@Itz-Miles Ok thanks
