### ISSUE TITLE
How To Make Achievement On LUA Please Give Code

### ISSUE THREAD

**Issue by ArtemB0Y** [ShadowMario/FNF-PsychEngine#8997]
### Describe your problem here.

I Want Make Achievement After You Unlockin' Secret Song, But Don't Know A Code For That, Give Code Plz

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by CrusherMods** [comment]
Its not a thing...

**Comment by JorosTheModderPH** [comment]
^

**Comment by Mastercopper2346** [comment]
Soft coded achievements were removed, but the folder wasn’t deleted.

**Comment by 0-skid** [comment]
it was removed because of a bug where it wouldn't stop giving the same achievement over again

**Comment by hayfii** [comment]
You don't have to use capslock on every sentence, it's not how English works and "It's Wasting Your Time".

**Comment by tylerandari12** [comment]
Lua not LUA

**Comment by Wither362** [comment]
# YOU CANT UNTIL BB-PANZU FIXES THE DUPLICATION BUG! AND BB-PANZU INST HERE ANYMORE! MAYBE YOU WILL HAVE TO WAIT MONTHS, YEARS, **DECADES** UNTIL SOMEONE FIXES IT!! **STOP DOING THIS NONSENSE ISSUES!!!!**

**Comment by Mastercopper2346** [comment]
> # YOU CANT UNTIL BB-PANZU FIXES THE DUPLICATION BUG! AND BB-PANZU INST HERE ANYMORE! MAYBE YOU WILL HAVE TO WAIT MONTHS, YEARS, DECADES UNTIL SOMEONE FIXES IT!! STOP DOING THIS NONSENSE ISSUES!!!!

Bro chill and take a chill pill, he didn’t know

**Comment by Wither362** [comment]
> > # YOU CANT UNTIL BB-PANZU FIXES THE DUPLICATION BUG! AND BB-PANZU INST HERE ANYMORE! MAYBE YOU WILL HAVE TO WAIT MONTHS, YEARS, DECADES UNTIL SOMEONE FIXES IT!! STOP DOING THIS NONSENSE ISSUES!!!!
> 
> Bro chill and take a chill pill, he didn’t know

sorry, wait, did you wanted to me to write it like this?:
###### YOU CANT UNTIL BB-PANZU FIXES THE DUPLICATION BUG! AND BB-PANZU INST HERE ANYMORE! MAYBE YOU WILL HAVE TO WAIT MONTHS, YEARS, DECADES UNTIL SOMEONE FIXES IT!! STOP DOING THIS NONSENSE ISSUES!!!!

# OR NO??!! IM VERY ANGRY BECAUSE IVE SEEN _A LOT_ OF THIS ISSUES AND IM STARTING TO GO CRAZY!!!!!!!!!

**Comment by CrusherMods** [comment]
> > # YOU CANT UNTIL BB-PANZU FIXES THE DUPLICATION BUG! AND BB-PANZU INST HERE ANYMORE! MAYBE YOU WILL HAVE TO WAIT MONTHS, YEARS, DECADES UNTIL SOMEONE FIXES IT!! STOP DOING THIS NONSENSE ISSUES!!!!
> 
> Bro chill and take a chill pill, he didn’t know

im pretty sure its fucking obvious by now that everyone would know
either way the new update will remove the folder so soon we might stop actually getting these issues

**Comment by Wither362** [comment]
> 

Yeah! Thats what im refering to!

**Comment by Mastercopper2346** [comment]
Speaking of new update, week 7 is going to come out!

**Comment by Wither362** [comment]
> Speaking of new update, week 7 is going to come out!

Is already out

**Comment by tylerandari12** [comment]
> > Speaking of new update, week 7 is going to come out!
> 
> 
> 
> Is already out

He means on psyche engine...

**Comment by Wither362** [comment]
> > > Speaking of new update, week 7 is going to come out!
> > 
> > 
> > Is already out
> 
> He means on psyche engine...

its already out!
