### ISSUE TITLE
Offsets for 'Confirm animation'

### ISSUE THREAD

**Issue by JackBlak** [ShadowMario/FNF-PsychEngine#8998]
### What is your question?

Im trying to add my custom bf, and he has his own confirm animation in the menu.
I can set his position just fine, but his 'confirm' sprites dont align with the 'Idle' Sprites (pressing spacebar)

So i wonder how I can adjust the offsets for the 'confirm' sprites.

**Comment by Mastercopper2346** [comment]
Just go into the character editor and do it 💀

**Comment by JackBlak** [comment]
> Just go into the character editor and do it 💀

How would character editor help me adjust the offsets for the **menu**'s confirm sprites ?

**Comment by JackBlak** [comment]
> Just go into the character editor and do it 💀

How would character editor adjust the position for the **menu**'s confirm sprites ?

**Comment by CrusherMods** [comment]
im pretty sure Character.hx has an offset function
look through that then put it in main menu or something

**Comment by JackBlak** [comment]
> im pretty sure Character.hx has an offset function look through that then put it in main menu or something

it's alright i already figured out a simple way
And no, character.hx doesnt have offset for menu character, nor is it able to set position for the "confirm animation"
