### ISSUE TITLE
I want to detect if there is silence in the start of the song.

### ISSUE THREAD

**Issue by Phoneguytech75** [ShadowMario/FNF-PsychEngine#9000]
### Describe your problem here.

I want to make a option that allows you to skip to the start of your turn.
Something like how osu does it:
![image](https://user-images.githubusercontent.com/88546046/172920961-dc3eee20-3ff4-479b-8cdb-373f8df14ab6.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Mastercopper2346** [comment]
I don’t think it’s possible

**Comment by Itz-Miles** [comment]
This is already a feature in 0.5.2, but you can make a script to set the conductor position only when it isn't the players turn.

**Comment by Lorekeeper49** [comment]
> This is already a feature in 0.5.2

Incorrect, if you're referring to the skip time feature for charting mode, then you should know that that isn't the same thing

**Comment by Itz-Miles** [comment]
It is quite literally moving the conductor's position. It serves as a realistic way of solving their problem, because their question was nonsensical. If the player doesn't like the opponent's turn, (silence, vocals, or anything else) they can change the song position to the player's turn.

**Comment by Mastercopper2346** [comment]
> This is already a feature in 0.5.2, but you can make a script to set the conductor position only when it isn't the players turn.

I forgot about that

**Comment by Phoneguytech75** [comment]
I think i worded my issue poorly. Sorry.

Is there any way to find the first note the player occurs and figure out how long it will take until it spawns.

**Comment by Itz-Miles** [comment]
Yeah I'll look at json scraping when I'm not a little preoccupied. I'll grab strumtimes for the sections that aren't the must hit ones, so the player can set the conductor past them. You'll be able to skip parts of a song that don't have any player notes on them.
