### ISSUE TITLE
Hud events

### ISSUE THREAD

**Issue by TheManwhoisdyinghere** [ShadowMario/FNF-PsychEngine#9001]
### Describe your problem here.

Does anyone know how to make events happen on the hud? i mean the UI or whatever its called

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

_no i did not yet_

**Comment by Mastercopper2346** [comment]
setObjectCamera(‘tag’, ‘camHUD’);
setProperty(‘camHUD.angle’, value);

These are a few examples of use/tweening camHUD.

**Comment by TheManwhoisdyinghere** [comment]
wait its cant be that easy?

**Comment by TheManwhoisdyinghere** [comment]
ok so now the question is where i put this.

**Comment by Mastercopper2346** [comment]
Example:

local turn = 45;
function onCounterTick — idk if this works but try
     if counter 2% == 0 then
          setProperty(‘camHUD.angle’, turn);
     end
     if counter 2% == 2 then — never tried this
          setProperty(‘camHUD.angle’, -turn);
     end
end
