### ISSUE TITLE
custom icon beat

### ISSUE THREAD

**Issue by LeonGamerPS4** [ShadowMario/FNF-PsychEngine#9002]
### Describe your problem here.

i want to change how the icons on the health bar bop. is there a way to do that?
(example: how the icons bop in week 7)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes i changed HealthIcon.hx to the 0.4.2 version, and it still doesn’t bop in the way i want it

**Comment by Mastercopper2346** [comment]
> yes i changed HealthIcon.hx to the 0.4.2 version, and it still doesn’t bop in the way i want it
bopping is in playstate not healthIcon

**Comment by Mastercopper2346** [comment]
or it might just be 0.4.2

**Comment by LeonGamerPS4** [comment]
how do you change how like the icon moves? (the icon moves down smoothly like in week 7)

**Comment by hayfii** [comment]
If you want a custom icon beat, IconHealth.hx isn't the place for you to modify the bop. It's in PlayState.

**Comment by LeonGamerPS4** [comment]
where do you find where the icon can bop in playstate

**Comment by hayfii** [comment]
> where do you find where the icon can bop in playstate

Somewhere in beathit and update function

**Comment by ShadowMario** [comment]
The icon bopping is inside `update` in PlayState.hx

![Screenshot_4](https://user-images.githubusercontent.com/44785097/174229884-ba56dfb4-74a3-4e13-80e4-ce526aea7425.png)
