### ISSUE TITLE
Someone Have  a Script that makes the health bar the most lower possible?

### ISSUE THREAD

**Issue by Plotsh** [ShadowMario/FNF-PsychEngine#9003]
### What is your question?

as im using a hud on the side, i need a script thst makes the healthbar stays on the lower possible place on the screen (just lower it) idk how to do it pls someone lmao

**Comment by FlintIshe** [comment]
setProperty('healthBar.x')
setProperty('healthBarBG.x')

may be

**Comment by Plotsh** [comment]
> setProperty('healthBar.x') setProperty('healthBarBG.x')
> 
> may be

sorry for the late answer, but yea it didnt work

**Comment by Plotsh** [comment]
> setProperty('healthBar.x') setProperty('healthBarBG.x')
> 
> may be
sorry for the late answer lmao didnt work

**Comment by Plotsh** [comment]
heh got it
