### ISSUE TITLE
3rd stage + always getting Expected }

### ISSUE THREAD

**Issue by CharlesRBLX** [ShadowMario/FNF-PsychEngine#9006]
### Describe your problem here.

so i am trying to add a 3rd stage for a psych engine version of vs sonic.exe, but whenever i try to compile it, it just says that it got "Expected }" is there any way to fix this?
<img width="960" alt="Screenshot 2022-06-10 002403" src="https://user-images.githubusercontent.com/99976788/172996144-09a0b21a-c537-40f8-9989-3b29a89c2d3e.png">
<img width="407" alt="Screenshot 2022-06-10 002341" src="https://user-images.githubusercontent.com/99976788/172996155-02b16318-367c-427b-8b3b-46da84c45b54.png">

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by hayfii** [comment]
What are you trying to do?

**Comment by tylerandari12** [comment]
Most likely missing a bracket somewhere...

**Comment by ShadowMario** [comment]
Leaked build :-1:
