### ISSUE TITLE
function on alt animation?

### ISSUE THREAD

**Issue by qvilligan** [ShadowMario/FNF-PsychEngine#9009]
### Describe your problem here.

i need help making a lua funciton for when an alt-animation is played.

i want this to play when an alt animation is used

	makeAnimatedLuaSprite('ghostdown','characters/ghost', ghdwnx,ghdwny)
	addAnimationByPrefix('ghostdown','alt down','ghost Down alt',24,false)
	addLuaSprite('ghostdown',false)
	objectPlayAnimation('ghostdown','alt down',true)
	setProperty('ghostdown.alpha',0)

and if it isnt an alt animation, this
	makeAnimatedLuaSprite('ghostdown','characters/ghost', ghdwnx,ghdwny)
	addAnimationByPrefix('ghostdown','down','ghost Down',24,false)
	addLuaSprite('ghostdown',false)
	objectPlayAnimation('ghostdown','down',true)
	setProperty('ghostdown.alpha',0)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
[Check callbacks on wiki](https://raw.githubusercontent.com/ShadowMario/FNF-PsychEngine/main/docs/TemplateScript.lua)
