### ISSUE TITLE
'Change Character' for 'Dad' event not working. (I'm using v0.4.2) (Using Mods folder)

### ISSUE THREAD

**Issue by FanKid** [ShadowMario/FNF-PsychEngine#901]
### Describe your bug here.

I was trying to make a BETADCIU song 'Nyeh' playable by TJ255, but when I tried changing the 'Dad' character, it only changes the 'BF' character. Is this a bug that is should be fixed?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, just the mods folder.

**Comment by cfgexe** [comment]
where did you try to edit it from?

**Comment by FanKid** [comment]
@cfgexe I just used the chart editor by placing event notes on the side and tested it using Henry and Tankman as the 'Dad' character and it's only changing the 'BF' character.

**Comment by Bruno215Brochado** [comment]
You need to write '1' in value 1 to change opponent character

**Comment by FanKid** [comment]
@Bruno215Brochado Dang, I forgot, also I should've read the desc more. Thanks!

**Comment by acap09** [comment]
I THINK THIS ISSUE IS SOLVED, so please close this

**Comment by NotEpik** [comment]
0 = bf
1 = dad
2 = gf

**Comment by FuseIsHere813** [comment]
Yeah close this issue bozo.

**Comment by ShadowMario** [comment]
Duplicate of #312, close your motherfucking issue if you're done with it.
