### ISSUE TITLE
psych engine bugs encountered when trying to compile game into a build so i can mod

### ISSUE THREAD

**Issue by bloxboi** [ShadowMario/FNF-PsychEngine#9010]
### Describe your problem here.

i am trying to build the game but it says theres no discord_rpc in it. how can i fix this.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by hayfii** [comment]
This isn't a bug, it's just you didn't install DiscordRPC.

Open CMD (Command Prompt) then paste this:
```haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc

**Comment by bloxboi** [comment]
this happened when i tried to build it: 
![image](https://user-images.githubusercontent.com/104321099/173135265-d5993a92-bc02-4d7f-9919-508c0c6b73ed.png)

**Comment by bloxboi** [comment]
nvm it probs works

**Comment by CrusherMods** [comment]
> this happened when i tried to build it: ![image](https://user-images.githubusercontent.com/104321099/173135265-d5993a92-bc02-4d7f-9919-508c0c6b73ed.png) EDIT: nvm it probs works
> 
> ANOTHER EDIT: bruh. this happened: ![image](https://user-images.githubusercontent.com/104321099/173141291-e4860543-9b33-413e-b61a-8a0696fc0886.png)

For PlayState you need to include a `,` or `]` somewhere in your code.

**Comment by bloxboi** [comment]
well the source code files had this semicolon in every piece of code 
example: 
![image](https://user-images.githubusercontent.com/104321099/173154280-85fa059d-3d39-4699-a5ca-2f698dadcaf1.png)

**Comment by hayfii** [comment]
> well the source code files had this semicolon in every piece of code example: ![image](https://user-images.githubusercontent.com/104321099/173154280-85fa059d-3d39-4699-a5ca-2f698dadcaf1.png)

That's not a problem.

**Comment by bloxboi** [comment]
I modified it

**Comment by hayfii** [comment]
> I modified it for a mod I'm making

I don't know then.

**Comment by Wither362** [comment]
> well the source code files had this semicolon in every piece of code
> example:
> ![image](https://user-images.githubusercontent.com/104321099/173154280-85fa059d-3d39-4699-a5ca-2f698dadcaf1.png)

Can you show the lines before that lines?

**Comment by bloxboi** [comment]
The command prompt I ued to build the game. I figured out the problem. But whenever I try to build it, it crashes. What's going on?

**Comment by bloxboi** [comment]
I downloaded another build and deleted the previous one btw
