### ISSUE TITLE
How to get highscore data from a song

### ISSUE THREAD

**Issue by KirbyKid256** [ShadowMario/FNF-PsychEngine#9011]
### What is your question?

Is there a way to get certain data from a song's highscore? Such as the score, rating, or ratingFC string? I ask because I already released my own mod about a week ago, and the current system I have means that people would have to replay the songs that they've already completed for the save data to update.

**Comment by Itz-Miles** [comment]
Dunno why you'd only need to grab those, but you can parse the data saved in the user's .sol files. 
`user name > AppData(hidden file) > Roaming > ShadowMario > PsychEngine > ninjamuffin99`
The save data should carry over to following versions if the game's/mod's directory doesn't change.

**Comment by KirbyKid256** [comment]
I know where it is. And I assume that I can use the lua save data functions to grab it, but how would I know what exactly to grab? (How do I read the .sol files?)
FYI, I want to use this to recreate an entire menu.

**Comment by Itz-Miles** [comment]
If your source mod has a new directory, I recommend duplicating and modifying Highscore.hx that runs after Main.hx. It'l grab save data from another location and flush it before the titlescreen.

**Comment by Itz-Miles** [comment]
For lua, that system mostly stores external vars other than save data, the game's system should handle it for you. If you want it like that though, use the same functions you use to write to the file as the ones you use to read them.

**Comment by Itz-Miles** [comment]
Turns out the wiki wasn't updated, check for `getTextFromFile()`'s source callback in funkinLua.hx check highscore.hx to see what variables to load.

**Comment by Itz-Miles** [comment]
`initSaveData()` and `flushSaveData()`

**Comment by KirbyKid256** [comment]
So I'm able to get simple variables from the funkin.sol file like noteOffset and framerate, but the main problem is getting certain variables from maps.

**Comment by Itz-Miles** [comment]
I dunno how to get array stuffs with lua, I'm currently working on a source mod. Best advice I got is converting source code from Highscore.hx to lua.

**Comment by KirbyKid256** [comment]
Well, then I think I already have that covered. I just wanted to make sure if there was another way to do it via lua.
