### ISSUE TITLE
How do i add botplay to the settings?

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#9013]
### Describe your problem here.

I need to know this, please help lmao

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Mastercopper2346** [comment]
okay, where do you want you option to be? gameplay, visuals, etc.

**Comment by WilliamGaming12** [comment]
> okay, where do you want you option to be? gameplay, visuals, etc.

gameplay's the best otpion for me

**Comment by Mastercopper2346** [comment]
```
		var option:Option = new Option('Botplay',
			"If checked, botplay is turned on.",
			'botplay',
			'bool',
			false);
		addOption(option);
```
put this in GameplaySettingsSubstate.hx

**Comment by Mastercopper2346** [comment]
`public static var botPlay:Bool = false;`
put this in ClientPrefs.hx

**Comment by WilliamGaming12** [comment]
> `public static var botPlay:Bool = false;`
> 
> `FlxG.save.data.botPlay = botPlay;`
> 
> ```
> 		if(FlxG.save.data.mechanics != null) {
> 			mechanics = FlxG.save.data.mechanics;
> 		}
> ```
> 
> put these bad boys in ClientPrefs.hx

souce/Clientprefs.hx:149: characters 4-13: unkown indentifier : mechanics
it appears that

**Comment by Mastercopper2346** [comment]
Oop I forgot to change that 💀

**Comment by WilliamGaming12** [comment]
> Oop I forgot to change that 💀

well if i reemplaze "mechanics" with "botplay!", it'll show but, by SOME reason, i cant check it, it doesn't let me

**Comment by Mastercopper2346** [comment]
You forgot to do something/did it wrong

**Comment by Wither362** [comment]
> > Oop I forgot to change that 💀
> 
> well if i reemplaze "mechanics" with "botplay!", it'll show but, by SOME reason, i cant check it, it doesn't let me

You have to replace it with `botPlay`, not `botplay`

**Comment by WilliamGaming12** [comment]
> > > Oop I forgot to change that 💀
> > 
> > 
> > well if i reemplaze "mechanics" with "botplay!", it'll show but, by SOME reason, i cant check it, it doesn't let me
> 
> You have to replace it with `botPlay`, not `botplay`

So yeah, now i can check it but, when you check it, it does nothing like, it stills without the botplay

**Comment by Mastercopper2346** [comment]
That was just the option part 💀

**Comment by Wither362** [comment]
Ok

**Comment by Wither362** [comment]
Let me create a tutorial

**Comment by WilliamGaming12** [comment]
> Let me create a tutorial

alright

**Comment by Wither362** [comment]
Do you have vs code?

**Comment by WilliamGaming12** [comment]
> Do you have vs code?

yes, i code with that

**Comment by Wither362** [comment]
Tutorial: In case that you have [Vs Code (VSC)](https://code.visualstudio.com/), go to `PlayState.hx`, go to line 301 and copy and paste this code: 
```hx
cpuControlled = ClientPrefs.botPlay;

```

**Comment by WilliamGaming12** [comment]
> Wither362

stills without working for some reason

**Comment by WilliamGaming12** [comment]
well i'll discover later, thank you either way guys
