### ISSUE TITLE
How can I make this loop?

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#9014]
### Describe your problem here.

This: 

doTweenX('somethingxtween', 'something', -1150, 2, 'quadIn')

function onTweenCompleted()
    if tag == 'something' then
        doTweenX('something1xtween', 'something', -985, 2, 'quadIn')
    end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
```lua
function onTweenCompleted(tag)
     if tag == 'somethingxtween' then
          if getProperty('something.x') == -985 then
               doTweenX('somethingxtween', 'something', -1150, 2, 'quadIn')
          else
               doTweenX('somethingxtween', 'something', -985, 2, 'quadIn')
          end
     end
end
```

**Comment by bruh1cat** [comment]
> ```lua
> function onTweenCompleted(tag)
>      if tag == 'somethingxtween' then
>           if getProperty('something.x') == -985 then
>                doTweenX('somethingxtween', 'something', -1150, 2, 'quadIn')
>           else
>                doTweenX('somethingxtween', 'something', -985, 2, 'quadIn')
>           end
>      end
> end
> ```

It doesn't loop

**Comment by frantastic24** [comment]
What does your code look like

**Comment by bruh1cat** [comment]
makeLuaSprite('skull_kid_bg_1D', 'skull_kid_bg_1D', -1620, -530);
	   scaleObject('skull_kid_bg_1D', 1.4, 1.4);
       addLuaSprite('skull_kid_bg_1D', false)
       doTweenX('skull_kid_bg_darkPart_symbols54xtween', 'skull_kid_bg_darkPart_symbols54', -1150, 2, 'quadIn')
function onTweenCompleted(tag)
    if tag == 'skull_kid_bg_darkPart_symbols54xtween' then
         if getProperty('skull_kid_bg_darkPart_symbols54.x') == -985 then
              doTweenX('skull_kid_bg_darkPart_symbols54xtween', 'skull_kid_bg_darkPart_symbols54', -1150, 2, 'quadIn')
         else
              doTweenX('skull_kid_bg_darkPart_symbols541xtween', 'skull_kid_bg_darkPart_symbols54', -985, 2, 'quadIn')
         end
    end
end

**Comment by frantastic24** [comment]
Why did you change the tag in the last tween, it needs all 3 tags to be the same to work

**Comment by bruh1cat** [comment]
This Calling this function will cancel another tween that is using the same tag!

**Comment by frantastic24** [comment]
> onTween**Completed**

You sure?

**Comment by bruh1cat** [comment]
?

**Comment by bruh1cat** [comment]
It worked

**Comment by frantastic24** [comment]
It's not cancelling another tween because said tween already ended though, the reply just read as if there was an issue to me
