### ISSUE TITLE
Psych engine character glitch

### ISSUE THREAD

**Issue by Roselyn393** [ShadowMario/FNF-PsychEngine#9016]
### Describe your bug here.

Whenever i use psych engine to use a character, i enter the character sprite names and what comes up is the character's spritesheet which has me really confused. don't know if its an internal error caused by my norton or what. i'm not sure if others are having this issue but it seems to only happen to me as i've seen

### Command Prompt/Terminal logs (if existing)

```bash
none
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Roselyn393** [comment]
here's a picture for proof and better understanding
![image](https://user-images.githubusercontent.com/103345463/173166436-359e62df-7e90-4e51-a7d0-54eab295d14d.png)

**Comment by Mastercopper2346** [comment]
Not a psych engine glitch, it’s an error in you xml

**Comment by Roselyn393** [comment]
> Not a psych engine glitch, it’s an error in you xml

my friend tried the xml and it worked perfectly fine for him

**Comment by CrusherMods** [comment]
> here's a picture for proof and better understanding ![image](https://user-images.githubusercontent.com/103345463/173166436-359e62df-7e90-4e51-a7d0-54eab295d14d.png)

one of takis spritesheet always bugs out
there is two of them
use Taki_Assets

**Comment by Roselyn393** [comment]
> > here's a picture for proof and better understanding ![image](https://user-images.githubusercontent.com/103345463/173166436-359e62df-7e90-4e51-a7d0-54eab295d14d.png)
> 
> one of takis spritesheet always bugs out there is two of them use Taki_Assets

okay, i'll see cause from what i have the taki_assets is bugged

**Comment by Roselyn393** [comment]
okay nvm, but the thing is i still get the glitch on other spritesheets, any ideas why?

**Comment by Mastercopper2346** [comment]
Idk

**Comment by Mastercopper2346** [comment]
Reopen your engine, that’s the only way

**Comment by Roselyn393** [comment]
okay, thanks alot
