### ISSUE TITLE
can someone do me a favor and tell me what the fuck an invalid escape sequence is

### ISSUE THREAD

**Issue by ColdlordXRepositories** [ShadowMario/FNF-PsychEngine#9017]
### Describe your problem here.

![Error 6_10_2022 9_33_11 PM](https://user-images.githubusercontent.com/49921877/173167572-35288aad-77b2-4841-abc7-b3ed2fe8177e.png)
im just trying to make a stage and this happens everytime i select it
function onCreate()
	-- background shit
	makeLuaSprite('House', 'House', -600, -300);
	setScrollFactor('House', 0.9, 0.9);

        addLuaSprite ('House', false);

	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end
lua file if you need it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Trying to work a bg that doesnt even have 21 lines in either its json or lua files

Edit: github is bugged so the code thing doesnt work 
Edit 2: its not even an error with the lua code itself, as I stole some code from another psych mod and the bg worked perfectly on that one
Edit: I FIGURED IT OUT, ITS THE \USERS IN THE DIRECTORY I PUT
Edit Again: eh nope its the \ and the next character for some reason

**Comment by Mastercopper2346** [comment]
Weird. I’ve never seen this error before.

**Comment by Lorekeeper49** [comment]
`close()` is supposed to have nothing in the parentheses, that's probably what's causing the error

**Comment by ColdlordXRepositories** [comment]
> `close()` is supposed to have nothing in the parentheses, that's probably what's causing the error

Thanks! I'll try it.

**Comment by ColdlordXRepositories** [comment]
> `close()` is supposed to have nothing in the parentheses, that's probably what's causing the error

Didn't work, still causing the error

**Comment by ColdlordXRepositories** [comment]
I did it!!! It was where the image was, not any of the code.
