### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Dancraft87** [ShadowMario/FNF-PsychEngine#9021]
### What is your question?

How can I make the notes move in the middle of a song?

**Comment by machonessiebaby** [comment]
so i can answer 2

so go to chart editor and go to where ever you want this is lua

now use


``` 
if curStep>= then
    	noteTweenX("NoteMove1", 0, 800, 2, cubeInOut)
	noteTweenX("NoteMove2", 1, 910, 2, cubeInOut)
	noteTweenX("NoteMove3", 2, 1020, 2, cubeInOut)
	noteTweenX("NoteMove4", 3, 1130, 2, cubeInOut)
	noteTweenX("NoteMove5", 4, 100, 2, cubeInOut)
	noteTweenX("NoteMove6", 5, 210, 2, cubeInOut)
	noteTweenX("NoteMove7", 6, 320, 2, cubeInOut)
	noteTweenX("NoteMove8", 7, 430, 2, cubeInOut)
end```

for the Y axis just change noteTweenX to noteTweenY

X & Y are inverted for some odd reason


now NoteMove idk


but the numbers 0-7 are the notes 0-4 opponent 5-7 player

3rd value the x or y location (inverted)

4th is time

5th is tween type


script below swaps notes

**Comment by Mastercopper2346** [comment]
@machonessiebaby can you help me in #8927 please?

**Comment by Dancraft87** [comment]
> para que pueda responder 2
> 
> así que ve al editor de gráficos y ve a donde quieras, esto es lua
> 
> Ahora usa
> 
> ```
> if curStep>= then
>     	noteTweenX("NoteMove1", 0, 800, 2, cubeInOut)
> 	noteTweenX("NoteMove2", 1, 910, 2, cubeInOut)
> 	noteTweenX("NoteMove3", 2, 1020, 2, cubeInOut)
> 	noteTweenX("NoteMove4", 3, 1130, 2, cubeInOut)
> 	noteTweenX("NoteMove5", 4, 100, 2, cubeInOut)
> 	noteTweenX("NoteMove6", 5, 210, 2, cubeInOut)
> 	noteTweenX("NoteMove7", 6, 320, 2, cubeInOut)
> 	noteTweenX("NoteMove8", 7, 430, 2, cubeInOut)
> end
> ```
> 
> --para el eje Y simplemente cambie noteTweenX a noteTweenY
> 
> --X e Y están invertidos por alguna extraña razón
> 
> --ahora NoteMove idk
> 
> --pero los números 0-7 son las notas 0-4 oponente 5-7 jugador
> 
> --3er valor la ubicación x o y (invertida)
> 
> --4to es tiempo
> 
> --5th es de tipo interpolación
> 
> --script arriba intercambia notas
> 
> (Soy malo explicando)

Muchas gracias :)
¿Alguien sabe si mi pregunta #1 se puede hacer en lua o es con una animación de un personaje?

**Comment by Dancraft87** [comment]
Thank you very much! :)

Can someone tell me if my question #1 can be done in an event in lua , with an animation in Adobe Animate , or is it done programmatically?
