### ISSUE TITLE
How to use achievements file?

### ISSUE THREAD

**Issue by MOON-on-GitHub** [ShadowMario/FNF-PsychEngine#9023]
### What is your question?

(after 0.5.2h) in mods file, there is a file named achievements.

how to use it?

**Comment by machonessiebaby** [comment]
its unused softcoded broke shadow forgot to remove folder same with shaders

**Comment by Mastercopper2346** [comment]
Bro try to use the Search function before making a question like this.

**Comment by Mastercopper2346** [comment]
He removed it but forgot to delete the folder

**Comment by pasta870** [comment]
shadow mario fogor to remove 
![unknown-1](https://user-images.githubusercontent.com/96292419/173213258-baee6770-abd1-4757-876a-a227e2892b2e.png)

**Comment by tylerandari12** [comment]
> shadow mario fogor to remove 
> 
> ![unknown-1](https://user-images.githubusercontent.com/96292419/173213258-baee6770-abd1-4757-876a-a227e2892b2e.png)
> 
> 

Rage out the "Dave and Bambi" and that's a killer mod idea...

**Comment by Wither362** [comment]
YOU CANT
