### ISSUE TITLE
Tween error

### ISSUE THREAD

**Issue by Soeiz** [ShadowMario/FNF-PsychEngine#9024]
### Describe your problem here.

Hey, I am making a new state for the menu and I can't find out why it making me errors. It says me this "The object does not have the property "x"" Here is the file, maybe it's only some shitty errors lol

When I don't add the tween thing everything's working fine.

[FanartsState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8884172/FanartsState.txt)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a new state for the menu with tween.

**Comment by Mastercopper2346** [comment]
which object?

**Comment by hayfii** [comment]
You don't have to add " to the tween.
[FanartsState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8884192/FanartsState.txt)

**Comment by Soeiz** [comment]
Yeah but then it's making me that 

source/FanartsState.hx:100: characters 19-26 : Unknown identifier : sprite1
source/FanartsState.hx:100: characters 19-26 : ... For function argument 'Object'
source/FanartsState.hx:101: characters 19-26 : Unknown identifier : sprite2
source/FanartsState.hx:101: characters 19-26 : ... For function argument 'Object'

**Comment by hayfii** [comment]
> Yeah but then it's making me that
> 
> source/FanartsState.hx💯 characters 19-26 : Unknown identifier : sprite1 source/FanartsState.hx💯 characters 19-26 : ... For function argument 'Object' source/FanartsState.hx:101: characters 19-26 : Unknown identifier : sprite2 source/FanartsState.hx:101: characters 19-26 : ... For function argument 'Object'

This is because you put the var inside create.

**Comment by hayfii** [comment]
> Yeah but then it's making me that
> 
> source/FanartsState.hx💯 characters 19-26 : Unknown identifier : sprite1 source/FanartsState.hx💯 characters 19-26 : ... For function argument 'Object' source/FanartsState.hx:101: characters 19-26 : Unknown identifier : sprite2 source/FanartsState.hx:101: characters 19-26 : ... For function argument 'Object'

[FanartsState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8884401/FanartsState.txt)

**Comment by Soeiz** [comment]
Thanks !

**Comment by hayfii** [comment]
> Thanks !

No problem.

**Comment by Soeiz** [comment]
I don't know why when I added sprites it's making me that again but with these sprites

[FanartsState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8885639/FanartsState.txt)
 
source/FanartsState.hx:62: characters 3-10 : Unknown identifier : sprite4
source/FanartsState.hx:63: characters 3-10 : Unknown identifier : sprite4
source/FanartsState.hx:64: characters 3-10 : Unknown identifier : sprite4
source/FanartsState.hx:65: characters 3-10 : Unknown identifier : sprite4
source/FanartsState.hx:66: characters 3-10 : Unknown identifier : sprite4
source/FanartsState.hx:67: characters 7-14 : Unknown identifier : sprite4
source/FanartsState.hx:67: characters 7-14 : ... For function argument 'Object'
source/FanartsState.hx:68: characters 3-10 : Unknown identifier : sprite5
source/FanartsState.hx:69: characters 3-10 : Unknown identifier : sprite5
source/FanartsState.hx:70: characters 3-10 : Unknown identifier : sprite5
source/FanartsState.hx:71: characters 3-10 : Unknown identifier : sprite5
source/FanartsState.hx:72: characters 3-10 : Unknown identifier : sprite5
source/FanartsState.hx:73: characters 7-14 : Unknown identifier : sprite5
source/FanartsState.hx:73: characters 7-14 : ... For function argument 'Object'
source/FanartsState.hx:74: characters 3-10 : Unknown identifier : sprite6
source/FanartsState.hx:75: characters 3-10 : Unknown identifier : sprite6
source/FanartsState.hx:76: characters 3-10 : Unknown identifier : sprite6
source/FanartsState.hx:77: characters 3-10 : Unknown identifier : sprite6
source/FanartsState.hx:78: characters 3-10 : Unknown identifier : sprite6
source/FanartsState.hx:79: characters 7-14 : Unknown identifier : sprite6
source/FanartsState.hx:79: characters 7-14 : ... For function argument 'Object'
source/FanartsState.hx:80: characters 3-10 : Unknown identifier : sprite7
source/FanartsState.hx:81: characters 3-10 : Unknown identifier : sprite7
source/FanartsState.hx:82: characters 3-10 : Unknown identifier : sprite7
source/FanartsState.hx:83: characters 3-10 : Unknown identifier : sprite7
source/FanartsState.hx:84: characters 3-10 : Unknown identifier : sprite7
source/FanartsState.hx:85: characters 7-14 : Unknown identifier : sprite7
source/FanartsState.hx:85: characters 7-14 : ... For function argument 'Object'
source/FanartsState.hx:86: characters 3-10 : Unknown identifier : sprite8
source/FanartsState.hx:87: characters 3-10 : Unknown identifier : sprite8
source/FanartsState.hx:88: characters 3-10 : Unknown identifier : sprite8
source/FanartsState.hx:89: characters 3-10 : Unknown identifier : sprite8
source/FanartsState.hx:90: characters 3-10 : Unknown identifier : sprite8
source/FanartsState.hx:91: characters 7-14 : Unknown identifier : sprite8
source/FanartsState.hx:91: characters 7-14 : ... For function argument 'Object'
source/FanartsState.hx:145: characters 19-26 : Unknown identifier : sprite4
source/FanartsState.hx:145: characters 19-26 : ... For function argument 'Object'
source/FanartsState.hx:149: characters 19-26 : Unknown identifier : sprite4
source/FanartsState.hx:149: characters 19-26 : ... For function argument 'Object'
source/FanartsState.hx:150: characters 19-26 : Unknown identifier : sprite5
source/FanartsState.hx:150: characters 19-26 : ... For function argument 'Object'
source/FanartsState.hx:153: characters 19-26 : Unknown identifier : sprite4
source/FanartsState.hx:153: characters 19-26 : ... For function argument 'Object'
source/FanartsState.hx:154: characters 19-26 : Unknown identifier : sprite5
source/FanartsState.hx:154: characters 19-26 : ... For function argument 'Object'
source/FanartsState.hx:155: characters 19-26 : Unknown identifier : sprite6
source/FanartsState.hx:155: characters 19-26 : ... For function argument 'Object'
source/FanartsState.hx:158: characters 19-26 : Unknown identifier : sprite5
source/FanartsState.hx:158: characters 19-26 : ... For function argument 'Object'
source/FanartsState.hx:159: characters 19-26 : Unknown identifier : sprite6
source/FanartsState.hx:159: characters 19-26 : ... For function argument 'Object'
source/FanartsState.hx:160: characters 19-26 : Unknown identifier : sprite7
source/FanartsState.hx:160: characters 19-26 : ... For function argument 'Object'
source/FanartsState.hx:163: characters 19-26 : Unknown identifier : sprite6
source/FanartsState.hx:163: characters 19-26 : ... For function argument 'Object'
source/FanartsState.hx:164: characters 19-26 : Unknown identifier : sprite7
source/FanartsState.hx:164: characters 19-26 : ... For function argument 'Object'
source/FanartsState.hx:165: characters 19-26 : Unknown identifier : sprite8
source/FanartsState.hx:165: characters 19-26 : ... For function argument 'Object'
source/FanartsState.hx:168: characters 19-26 : Unknown identifier : sprite7
source/FanartsState.hx:168: characters 19-26 : ... For function argument 'Object'
source/FanartsState.hx:169: characters 19-26 : Unknown identifier : sprite8
source/FanartsState.hx:169: characters 19-26 : ... For function argument 'Object'

**Comment by hayfii** [comment]
> 

You SHOULD follow what I've did earlier.
[FanartsState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8885830/FanartsState.txt)

**Comment by Soeiz** [comment]
Thank you lmao 😭I haven't noticed the "var sprite3:FlxSprite" thay you have made

**Comment by hayfii** [comment]
h

> Thank you lmao 😭I haven't noticed the "var sprite3:FlxSprite" that you have made

It's fine ig..

**Comment by Mastercopper2346** [comment]
Yes, always make sure ‘var’ it’s before every sprite creation
