### ISSUE TITLE
GF title speed

### ISSUE THREAD

**Issue by AntCrem** [ShadowMario/FNF-PsychEngine#9025]
### Describe your problem here.

So I want to change the gf title sprites speed using it's json but the "bpm" only affects the logo. anyway to fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nu

**Comment by Mastercopper2346** [comment]
i dont think you can doanything else if you're using lua. you need source for anything else
