### ISSUE TITLE
Help with tables and tweens

### ISSUE THREAD

**Issue by ManMaster707** [ShadowMario/FNF-PsychEngine#9027]
### Describe your problem here.

I might be just incompetent with tables or lua, but these two tweens here with tables as their variable to tween don't seem to work, could anybody help me out?
here's the code:
```lua
-- its tablin' time
upHUD = {'timeBar','timeBarBG','timeTxt'}
downHUD = {'healthBar','healthBarBG','hbBorder','iconP1','iconP2','scoreTxt'}

function onEvent(name, value1, value2) 
	if name == 'canonS Trigger' then
		if value1 == 'yes' then
			doTweenY('upHUDTweenY', upHUD, getProperty(upHUD..'.y') - 100, 1, 'quadInOut');
                        doTweenY('downHUDTweenY', downHUD, getProperty(downHUD..'.y') + 400, 1, 'quadInOut');
			debugPrint('lol')-- just a test
		elseif value1 == 'no' then
			--cameraFlash('game', '0xFFFF0000', 1, false);
		end	
	end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i just added things trough the "mods" folder.

**Comment by Wither362** [comment]
True and false shouldn’t be in a string

**Comment by Wither362** [comment]
> I did that to avoid the game from breaking, but you made me realize that I could change the values to 'yes' and 'no' or numbers, but that doesn't work either.

Nononononono, use `true` or `false` without `"`

**Comment by Wither362** [comment]
Use this code in the `custom_events` folder:
```lua
-- its tablin' time
local upHUD = {'timeBar','timeBarBG','timeTxt'}
local downHUD = {'healthBar','healthBarBG','hbBorder','iconP1','iconP2','scoreTxt'}

function onEvent(name, value1, value2) 
	if string.lower(name) == 'canons trigger' then
		if string.lower(value1) == 'yes' then
			doTweenY('upHUDTweenY', upHUD, getProperty(upHUD..'.y') - 100, 1, 'quadInOut');
                        doTweenY('downHUDTweenY', downHUD, getProperty(downHUD..'.y') + 400, 1, 'quadInOut');
			debugPrint('lol')-- just a test
		elseif string.lower(value1) == 'no' then
			--cameraFlash('game', '0xFFFF0000', 1, false);
		end	
	end
end
```
I don’t know if it will work, I don’t code with lua…

**Comment by ManMaster707** [comment]
why `string.lower(name)`?

**Comment by Wither362** [comment]
> why `string.lower(name)`?

For lowercasing it

**Comment by ManMaster707** [comment]
The code you sent still doesn't work, thanks for trying though

**Comment by frantastic24** [comment]
You have to use a `for` function to iterate over every value in the array

**Comment by Wither362** [comment]
> You have to use a `for` function to iterate over every value in the array

im that case, let me update the code
