### ISSUE TITLE
compiling source code with an already made mod (mods folder)

### ISSUE THREAD

**Issue by jayprr** [ShadowMario/FNF-PsychEngine#9028]
### Describe your problem here.

Ok, so i changed the application name and made my own discord rich presence for a mod, and when i compile it it is just base psych engine source. i dont really know much about this but im guessing its just because its compiling base source code. Is there any way to compile it (get the discord rich presence and application name) and it loading up the assets in the mods folder instead of base source code? sorry if this sounds stupid lmao

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Edited Discord.hx to get the rich presence, and edited the Project.xml file for the application name.

**Comment by MaybeMaru** [comment]
I dont really know what you mean but if I guess you can add your mod in the example mods folder in source and when you compile the mod will be in the mods folder

**Comment by jayprr** [comment]
yeah, that works but it has a custom main menu and im not sure how to port it into source

**Comment by Wither362** [comment]
Compile it without the mod, and then add it
