### ISSUE TITLE
Don't answer this i'm going to ask in a better way later

### ISSUE THREAD

**Issue by MTFutureWasTaken** [ShadowMario/FNF-PsychEngine#9029]
### Describe your problem here.

Hi. I'm trying to make a script makes so that when you hit a note, text will appear telling you the rating of the note you just pressed (so if you hit a down note and you got a 'good' rating, text will appear above the gray down arrow saying 'good'). I'm not having much problems so far except for this one, I don't know how to identify if the player hits a sick, or a good, etc. I do have a script that does something that does something sort of similar to what I'm doing (it's the custom rating assets script from Vs, Whitty) but I don't understand anything about it. Can anybody help?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Mastercopper2346** [comment]
> Hi. I'm trying to make a script makes so that when you hit a note, text will appear telling you the rating of the note you just pressed (so if you hit a down note and you got a 'good' rating, text will appear above the gray down arrow saying 'good'). I'm not having much problems so far except for this one, I don't know how to identify if the player hits a sick, or a good, etc. I do have a script that does something that does something sort of similar to what I'm doing (it's the custom rating assets script from Vs, Whitty) but I don't understand anything about it. Can anybody help?

Just put the images in mods/images.
Everything else is bulit in.

**Comment by MTFutureWasTaken** [comment]
At first, I didn't understand what you were saying, but I do now and I think I explained myself a bit badly. I'm not trying to replace the 'Sick!' or 'Good' images (if I wanted to, I would've already known to put the images in mods/images (sorry if I was rude on this part)). I'm trying to make a script where text appears above the gray arrow saying what rating you got when you hit a note.

**Comment by MTFutureWasTaken** [comment]
The problem is... I don't how to make the script identify the rating when the player hits a note with a 'Sick!' rating or a 'Good' rating.
