### ISSUE TITLE
Gf shit

### ISSUE THREAD

**Issue by Roselyn393** [ShadowMario/FNF-PsychEngine#9030]
### What is your question?

Is there any way using .lua scripts/custom notetypes that i can get girlfriend to play her scared animation on note hit like in the taki songs of friday night fever in kade

**Comment by CrusherMods** [comment]
kinda simple
just
```lua
function opponentNoteHit(id, noteData, noteType, isSustainNote)
    characterPlayAnim('gf', 'scared', true)
end
```

**Comment by Mastercopper2346** [comment]
> kinda simple
just
```
function opponentNoteHit(id, noteData, noteType, isSustainNote)
    characterPlayAnim('gf', 'scared', true)
end
```

This should work.

**Comment by Mastercopper2346** [comment]
Also how do you get the colored code-
