### ISSUE TITLE
slow speed bug

### ISSUE THREAD

**Issue by KyroTheGamer** [ShadowMario/FNF-PsychEngine#9033]
### Describe your bug here.

whenever i install a fnf mod and add it to the mods folder the entire mod loads and all the songs are there but the arrow speed is very slow and i check the debug menu and crank the speed to 10 and no difference, It was still super slow and it was impossible for me to actually get a good accuracy on these new mods.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no other than the mod files being added to the mods folder

**Comment by frantastic24** [comment]
Press Control in Story/Freeplay menu and change scroll type
