### ISSUE TITLE
.lua scripts not loading

### ISSUE THREAD

**Issue by GamingIQ** [ShadowMario/FNF-PsychEngine#9034]
### Describe your problem here.

i put an lua script in one of my songs and after a day it stopped working plz fix
function onCreate()
makeLuaText('watermark', songName .. " | Created By BalloonBoyXd", 0, 25, 500); -- You can edit the created by Prisma Text just dont change anything else
    setTextSize('watermark', 20);
    addLuaText('watermark');
end 
plus
local allowCountdown = false
function onStartCountdown()
	-- Block the first countdown and start a timer of 0.8 seconds to play the dialogue
	if not allowCountdown and isStoryMode and not seenCutscene then
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('dialogue', 'breakfast');
	end
end

-- Dialogue (When a dialogue is finished, it calls startCountdown again)
function onNextDialogue(count)
	-- triggered when the next dialogue line starts, 'line' starts with 1
end

function onSkipDialogue(count)
	-- triggered when you press Enter and skip a dialogue line that was still being typed, dialogue line starts with 1
end

local allowEndShit = false

function onEndSong()
 if not allowEndShit and isStoryMode and not seenCutscene then
  setProperty('inCutscene', true);
  startDialogue('dialogue2', 'breakfast'); 
  allowEndShit = true;
  return Function_Stop;
 end
 return Function_Continue;
end
plus 
function opponentNoteHit() -- Code for the opponent to drain your health when he sings
    health = getProperty('health')
    if getProperty('health') > 0.4 then -- This is the maximum that the enemy will drain your health, then do nothing.
        setProperty('health', health- 0.017); -- How much health does the enemy drain from you, the more, the more health and the less, the less health
    end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

um no?

**Comment by frantastic24** [comment]
"plz fix" without even showing your script

**Comment by Mastercopper2346** [comment]
@frantastic24 help me in #9031 pls

**Comment by frantastic24** [comment]
No 💖💖

**Comment by pasta870** [comment]
show us the fucking script 
![bad_word](https://user-images.githubusercontent.com/96292419/173213223-55fb2784-acb3-4374-879b-c82f708e852c.png)

**Comment by Mastercopper2346** [comment]
> No 💖💖
Ok :(

**Comment by Wither362** [comment]
Delete the unnecessary functions plz

**Comment by GamingIQ** [comment]
@Wither362 ?

**Comment by Wither362** [comment]
> @Wither362 ?

Yeah?

**Comment by Wither362** [comment]
Ok, ok, let me rewrite the code for better review

**Comment by Wither362** [comment]
```lua
function onCreate()
	  makeLuaText('watermark', songName .. " | Created By BalloonBoyXd", 0, 25, 500); -- You can edit the created by Prisma Text just dont change anything else
	  setTextSize('watermark', 20);
	  addLuaText('watermark');
end
--plus
local allowCountdown = false
function onStartCountdown()
	 -- Block the first countdown and start a timer of 0.8 seconds to play the dialogue
	  if not allowCountdown and isStoryMode and not seenCutscene then
	  	  setProperty('inCutscene', true);
	  	  runTimer('startDialogue', 0.8);
	  	  allowCountdown = true;
	  	  return Function_Stop;
	  end
	  return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	  if tag == 'startDialogue' then -- Timer completed, 	  	  	play dialogue
	  	  startDialogue('dialogue', 'breakfast');
	  end
end
--[[
-- Dialogue (When a dialogue is finished, it calls startCountdown again)
function onNextDialogue(count)
-- triggered when the next dialogue line starts, 'line' starts with 1
end

function onSkipDialogue(count)
-- triggered when you press Enter and skip a dialogue line that was still being typed, dialogue line starts with 1
end
]]--

local allowEndShit = false

function onEndSong()
	  if not allowEndShit and isStoryMode and not seenCutscene then
	  	  setProperty('inCutscene', true);
	  	  startDialogue('dialogue2', 'breakfast');
	  	  allowEndShit = true;
	  	  return Function_Stop;
	  end
	  return Function_Continue;
end
--plus
function opponentNoteHit() -- Code for the opponent to drain your health when he sings
	  health = getProperty('health')
	  if getProperty('health') > 0.4 then -- This is the maximum that the enemy will drain your health, then do nothing.
	  	  setProperty('health', health- 0.017); -- How much health does the enemy drain from you, the more, the more health and the less, the less health
	  end
end
```
Try using that code
