### ISSUE TITLE
error

### ISSUE THREAD

**Issue by vrfunkine** [ShadowMario/FNF-PsychEngine#9035]
### Describe your bug here.

 
C:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/math/FlxPoint.hx:485: characters 3-15 : { get : () -> { set : (Float, Float) -> { _inPool : Bool } } } should be flixel.util.IFlxPool<flixel.math.FlxPoint>

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
That seems like an issue with your haxe and not the game

**Comment by vrfunkine** [comment]
like do i need to update or just something Wong it with it

**Comment by vrfunkine** [comment]
its on 4.2.4

**Comment by Mastercopper2346** [comment]
> its on 4.2.4

i have the same haxe version.
try going to the same file (of your verison) and copy and paste all the code.

Or is it already fresh 👀

**Comment by vrfunkine** [comment]
can you show me
