### ISSUE TITLE
Ghost trail but with another character

### ISSUE THREAD

**Issue by AntCrem** [ShadowMario/FNF-PsychEngine#9036]
### Describe your problem here.

is it possible to make it so when a ghost toggle trail event is active it instead makes a ghost of another character instead of the current one (ghost trail event from psychic)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nu

**Comment by Lorekeeper49** [comment]
I'm not entirely sure what you mean

**Comment by hayfii** [comment]
The ghost trail event is made on source code :)
