### ISSUE TITLE
Afterimage

### ISSUE THREAD

**Issue by Roselyn393** [ShadowMario/FNF-PsychEngine#9037]
### What is your question?

Is there any way to make a character have an afterimage of the previous animation on Note hit?

**Comment by Lorekeeper49** [comment]
I made a Lua script that works with this, it's posted in the discord server
![Screenshot_20220612-202902.png](https://user-images.githubusercontent.com/93066594/173274342-3bff4915-c9df-4e39-aa04-08b19f2c80bb.png)

**Comment by Roselyn393** [comment]
whats the discord server

**Comment by Roselyn393** [comment]
i need it

**Comment by Roselyn393** [comment]
please

**Comment by hayfii** [comment]
> whats the discord server

It's on the gamebanana page, pay more attention next time.

**Comment by Roselyn393** [comment]
where's the gamebanana, i don't see it anywhere

> > whats the discord server
> 
> It's on the gamebanana page, pay more attention next time.

also very rude

**Comment by hayfii** [comment]
> where's the gamebanana, i don't see it anywhere
> 
> > > whats the discord server
> > 
> > 
> > It's on the gamebanana page, pay more attention next time.
> 
> also very rude

So you fucking want me to be rude huh? Pay more attention to the gamebanana page so you don't have to be dumb.

**Comment by hayfii** [comment]
> where's the gamebanana, i don't see it anywhere
> 
> > > whats the discord server
> > 
> > 
> > It's on the gamebanana page, pay more attention next time.
> 
> also very rude

https://gamebanana.com/mods/309789
https://discord.gg/2ka77eMXDv
