### ISSUE TITLE
3 Questions

### ISSUE THREAD

**Issue by Dancraft87** [ShadowMario/FNF-PsychEngine#9038]
### What is your question?

1-How can I make a character move around the screen? (Like Cuphead's hadoken in FNF Indie Cross)

2-How can I make a cutscene in the middle of the song using .lua?

3-How to remove the black background from the Game Over screen using .lua?

**Comment by Lorekeeper49** [comment]
1. No idea
2. Impossible
3. Impossible

**Comment by Dancraft87** [comment]
Ok :(
