### ISSUE TITLE
Strumline Stuff

### ISSUE THREAD

**Issue by Roselyn393** [ShadowMario/FNF-PsychEngine#9039]
### What is your question?

Just looking for a way to make either the opponents/players/both strumline(s) invisible?

**Comment by Lorekeeper49** [comment]
Opponent:
```lua
noteTweenAlpha('0', 0, 0, duration, 'linear');
noteTweenAlpha('1', 1, 0, duration, 'linear');
noteTweenAlpha('2', 2, 0, duration, 'linear');
noteTweenAlpha('3', 3, 0, duration, 'linear');
```
Player:
```lua
noteTweenAlpha('4', 4, 0, duration, 'linear');
noteTweenAlpha('5', 5, 0, duration, 'linear');
noteTweenAlpha('6', 6, 0, duration, 'linear');
noteTweenAlpha('7', 7, 0, duration, 'linear');
```
Combine them for both

**Comment by Roselyn393** [comment]
i tried that but it doesn't seem to work
here's the code i'm using

**

> function onStepHit()
> 	if curStep >= 0 and curStep <= 120 then
> 		noteTweenAlpha('0', 0, 0, duration, 'linear');
> 		noteTweenAlpha('1', 1, 0, duration, 'linear');
> 		noteTweenAlpha('2', 2, 0, duration, 'linear');
> 		noteTweenAlpha('3', 3, 0, duration, 'linear');
> 		noteTweenAlpha('4', 4, 0, duration, 'linear');
> 		noteTweenAlpha('5', 5, 0, duration, 'linear');
> 		noteTweenAlpha('6', 6, 0, duration, 'linear');
> 		noteTweenAlpha('7', 7, 0, duration, 'linear');
> 	end
> end

**

**Comment by Lorekeeper49** [comment]
replace 'duration' with a number, it's measured in seconds

**Comment by Roselyn393** [comment]
oh ok

**Comment by Roselyn393** [comment]
how would i make it visible again then?

**Comment by Roselyn393** [comment]
and btw, it's still not working

**Comment by Roselyn393** [comment]
function onStepHit()
	if curStep >= 0 and curStep <= 120 then
		noteTweenAlpha('0', 0, 0, 0, 'linear');
		noteTweenAlpha('1', 1, 0, 0, 'linear');
		noteTweenAlpha('2', 2, 0, 0, 'linear');
		noteTweenAlpha('3', 3, 0, 0, 'linear');
		noteTweenAlpha('4', 4, 0, 0, 'linear');
		noteTweenAlpha('5', 5, 0, 0, 'linear');
		noteTweenAlpha('6', 6, 0, 0, 'linear');
		noteTweenAlpha('7', 7, 0, 0, 'linear');
	end
end

**Comment by FlintIshe** [comment]
`noteTweenAlpha('0', 0, 0, 0, 'linear');
noteTweenAlpha('1', 1, 0, 0, 'linear');
noteTweenAlpha('2', 2, 0, 0, 'linear');
noteTweenAlpha('3', 3, 0, 0, 'linear');
noteTweenAlpha('4', 4, 0, 0, 'linear');
noteTweenAlpha('5', 5, 0, 0, 'linear');
noteTweenAlpha('6', 6, 0, 0, 'linear');
noteTweenAlpha('7', 7, 0, 0, 'linear');`

to 

noteTweenAlpha('noteAlpha1', 0, 1, 0.1, 'linear');
noteTweenAlpha('noteAlpha2', 1, 1, 0.1, 'linear');
noteTweenAlpha('noteAlpha3', 2, 1, 0.1, 'linear');
noteTweenAlpha('noteAlpha4', 3, 1, 0.1, 'linear');
noteTweenAlpha('noteAlpha5', 4, 1, 0.1, 'linear');
noteTweenAlpha('noteAlpha6', 5, 1, 0.1, 'linear');
noteTweenAlpha('noteAlpha7', 6, 1, 0.1, 'linear');
noteTweenAlpha('noteAlpha8', 7, 1, 0.1, 'linear');

**Comment by Roselyn393** [comment]
> 

it still doesn't wanna work and besides i wanna make the notes appear and dissapear instantly

**Comment by FlintIshe** [comment]
may be remove ; , if i doesn't  work then idk

**Comment by Lorekeeper49** [comment]
> > 
> 
> it still doesn't wanna work and besides i wanna make the notes appear and dissapear instantly

The duration needs to be 0.001 for that to work, I don't know why it has to be that specific

**Comment by Roselyn393** [comment]
ok, it worked thanks
