### ISSUE TITLE
Step event or Beat Events?

### ISSUE THREAD

**Issue by LucasOnGithub** [ShadowMario/FNF-PsychEngine#9040]
### What is your question?

How do you do events on Step using Function's in stage code? like Mid Song Events from Kade Engine.

**Comment by CrusherMods** [comment]
either
```lua
function onStepHit()
--code goes here
end
```
or use
```lua
if curStep == curstepgoeshere then
-- code goes here
end
```

**Comment by LucasOnGithub** [comment]
im not really the best at coding so could you show an example?

> either
> 
> ```lua
> function onStepHit()
> --code goes here
> end
> ```
> 
> or use
> 
> ```lua
> if curStep == curstepgoeshere then
> -- code goes here (Btw you can use < and > to replace the == if you need)
> end
> ```

im not really the best at coding so could you show an example?

**Comment by LucasOnGithub** [comment]
please?

**Comment by hayfii** [comment]
> please?

Like this for example:
```
function onStepHit()
    if curStep == curstepgoeshere then
         objectPlayAnimation('boyfriend', 'hey', false)
    end
end
```

**Comment by LucasOnGithub** [comment]
> > please?
> 
> Examples:
> 
> StepHit
> 
> ```
> function onStepHit()
>     if curStep == curstepgoeshere then
>          objectPlayAnimation('boyfriend', 'hey', false)
>     end
> end
> ```
> 
> BeatHit
> 
> ```
> function onBeatHit()
>     if curBeat == curbeatgoeshere then
>          objectPlayAnimation('boyfriend', 'hey', false)
>     end
> end
> ```
> 
> This plays Hey! animation on Boyfriend when the curBeat/curStep is the same as your specified value.

Thanks!
