### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by bambitheone82112** [ShadowMario/FNF-PsychEngine#9041]
### What feature do you want to get added on the **base** engine?

can you make modding the game more easier than playing the game?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by CrusherMods** [comment]
its literally so easy rn
tf you mean

**Comment by Lorekeeper49** [comment]
Test = failed

**Comment by hayfii** [comment]
Use Kade Engine if you think it's not easy enough 🤓
Don't do requests like this, it'll probably make you hated, please learn how to code with Haxe.

**Comment by tylerandari12** [comment]
> Don't do requests like this, it's useless + it'll probably make you hated, please learn how to code with Haxe.

Me who's computer can't physically handle compiling the source code: 🥲

**Comment by Mastercopper2346** [comment]
FAILED THE TESTTTTTTTT

**Comment by hayfii** [comment]
> > Don't do requests like this, it's useless + it'll probably make you hated, please learn how to code with Haxe.
> 
> Me who's computer can't physically handle compiling the source code: 🥲

The compiling cannot be improved, do you know that?

**Comment by Mastercopper2346** [comment]
> Me who's computer can't physically handle compiling the source code: 🥲

Meanwhile my pc: *takes four hours to compile (for the first time)*

**Comment by ShadowMario** [comment]
![image](https://user-images.githubusercontent.com/44785097/174228231-1f7b99e7-d3d2-46c7-af2a-3c5833d5ad86.png)
