### ISSUE TITLE
How do I add text to the retry screen?

### ISSUE THREAD

**Issue by MTFutureWasTaken** [ShadowMario/FNF-PsychEngine#9043]
### Describe your problem here.

I mean, it's a simple question. I don't think I have to explain this. I'll explain more if needed but I think this is simple to understand for now.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by hayfii** [comment]
Not with lua of course.

**Comment by MTFutureWasTaken** [comment]
> ```lua
> local name = 'name of text'
> 
> function onGameOver()
>         makeLuaText(name, text, width, x, y)
> end
> function onGameOverConfirm(retry)
>         removeLuaText(name, destroy)
> end
> ```
> 
> Use that code, `name` is what name you want for the text, `destroy` is for not having that text again

Thanks.
