### ISSUE TITLE
Loading screen gets stuck

### ISSUE THREAD

**Issue by WolfyTail** [ShadowMario/FNF-PsychEngine#9044]
### Describe your problem here.

Hi, I tried to enable the Loading screen in my FNF mod. I deleted "NO_PRELOAD_ALL" and "#end" from _LoadingState.hx_, but when I enter any song, **the game just gets stuck**. How could I fix that?

PD: I know this would be useless in desktop build, I read it like 50 times in the "issues" page, but please, help.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by trayfellow** [comment]
if your song is modded through the mods folder it wont load since mods folder stuff is loaded with filesystem instead

**Comment by WolfyTail** [comment]
I've tried to open "tutorial" (assets/data/tutorial) but it doesn't load.

**Comment by Mastercopper2346** [comment]
> if your song is modded through the mods folder it wont load since mods folder stuff is loaded with filesystem instead

Not true.

**Comment by trayfellow** [comment]
> > if your song is modded through the mods folder it wont load since mods folder stuff is loaded with filesystem instead
> 
> Not true.

i tried readding the loading screen once to desktop and stuff works except mod folder songs

**Comment by Mastercopper2346** [comment]
I’ve tried on tutorial

**Comment by WolfyTail** [comment]
> > > if your song is modded through the mods folder it wont load since mods folder stuff is loaded with filesystem instead
> > 
> > 
> > Not true.
> 
> i tried readding the loading screen once to desktop and stuff works except mod folder songs

What did you do? Did you erase #NO_PRELOAD_ALL and #end from LoadingState.hx?

**Comment by Mastercopper2346** [comment]
Yes

**Comment by WolfyTail** [comment]
Which one did you delete? Line 164 or line 179?

**Comment by WolfyTail** [comment]
Nevermind. I had to download again _LoadingState.hx_ and it worked.
Thanks.
