### ISSUE TITLE
Sing and miss animations doing weird stuff

### ISSUE THREAD

**Issue by Zer0PXL** [ShadowMario/FNF-PsychEngine#9045]
### Describe your problem here.

This is a pretty simple problem that I always fix without knowing how... So I want to know how do I actually solve this

https://user-images.githubusercontent.com/84981290/173243828-f3aef4c5-8bd6-495d-81d6-178c0f6d6efa.mp4

?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CrusherMods** [comment]
add a 0 after the animation name in xml on the character editor if that makes sense

**Comment by Zer0PXL** [comment]
What is this fix 💀
Anyway, thank you!
