### ISSUE TITLE
HOW to COMPILE source code?

### ISSUE THREAD

**Issue by AdmiralUsername** [ShadowMario/FNF-PsychEngine#9047]
### What is your question?

I feel that the source code compilation tutorial is not very useful.
I DON'T KNOW HOW.
SAYING TO "Find an FNF compilation tutorial" ISN'T VERY HELPFUL.
I'VE BEEN TRYING FOR MONTHS.
THIS IS GETTING ANNOYING.
Please help.

**Comment by TFLTV** [comment]
find it on the [main page](https://github.com/ShadowMario/FNF-PsychEngine) and copy and paste everything (the code n' stuff thats shown below the code and files) in there into COMMAND PROMPT. do other things like install haxe, github and all the other things then type in "cd (your directory to the engine)" and press enter

**Comment by LucasOnGithub** [comment]
either go to here: `https://tinyurl.com/psych-engine-tutorial` or here: `https://tinyurl.com/kade-engine-tutorial` the Kade engine one explains more details.

**Comment by Itz-Miles** [comment]
I have a [pull request](https://github.com/ShadowMario/FNF-PsychEngine/blob/aae6b044668126526a188a60c0a4f7bfd8fa49ab/README.md) up that explains how to compile the newest version of Psych Engine. Follow it, and it should compile. 
(be patient on windows; it takes a while to make all the cpp files, even on a good pc)

**Comment by Wither362** [comment]
Also, look [here: https://github.com/Theoyeah/Theoyeah-Engine/wiki/Compile-the-Game](https://github.com/Theoyeah/Theoyeah-Engine/wiki/Compile-the-Game)
