### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by suskas** [ShadowMario/FNF-PsychEngine#9048]
Question

Hi how do i add characters in the main menu? I followed and copied all the tutorials but i keep getting errors
i need some help!

Example of it from a video:
![Screenshot 2022-06-12 202130](https://user-images.githubusercontent.com/95119042/173247687-e3fd0d98-c230-41fc-ba58-0b8166f56448.png)

**Comment by WoodsSilent05** [comment]
Are you using the newest version or the version the person was using in the video?

**Comment by CrusherMods** [comment]
maybe include the errors

**Comment by suskas** [comment]
> Are you using the newest version or the version the person was using in the video?

Yes the person was using the newest version

**Comment by suskas** [comment]
> maybe include the errors

MainMenuState.hx:183: characters 4-8 : Missing ;

Those are the errors I'm getting

**Comment by CrusherMods** [comment]
> > maybe include the errors
> 
> MainMenuState.hx:183: characters 4-8 : Missing ;
> 
> Those are the errors I'm getting

your missing a **;** somewhere

**Comment by Wither362** [comment]
> > maybe include the errors
> 
> MainMenuState.hx:183: characters 4-8 : Missing ;
> 
> Those are the errors I'm getting

Bro, write a `;` at the end of line `182`

**Comment by suskas** [comment]
fixed it and thx!
