### ISSUE TITLE
i used several BG change events i grabbed from random sources, when the bg is changed the bg is black

### ISSUE THREAD

**Issue by oisintheblue** [ShadowMario/FNF-PsychEngine#9050]
### Describe your problem here.

the bg was supposed to change to a sunset version of the bg. 

i set value 1 to the new stage  name
and value 2 to the old stage name. is it becuase i used the PNG's name? (my custom stages are only ONE image with json and lua files, just to make it easier)

all BG change events i tried to use were all ones that didn't require source code.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by oisintheblue** [comment]
Another one i tried had a different result; It did change the image, but the position was incorrect and only appeared for 10 seconds and then it went back to the original stage

https://user-images.githubusercontent.com/100409599/173264568-bea9b81a-0a74-439b-8950-9cfc417a09fe.mp4

this was the current bg change script i have now

**Comment by oisintheblue** [comment]
this was the script

```
function onEvent(name, value1, value2)
     -- pro
	makeLuaSprite(value2, value1, -600, -300);
	setScrollFactor(value2, 0.9, 0.9);
	addLuaSprite(value2, false);
    
    
    
    end
```

**Comment by Mastercopper2346** [comment]
Change -600(x) -300(y) to the correct positions.

**Comment by Mastercopper2346** [comment]
Plus it triggers every time any event is triggered.

**Comment by oisintheblue** [comment]
oh, thanks. But what about making it NOT dissapear after 4 beats?
