### ISSUE TITLE
Indie Cross Style Cutscene

### ISSUE THREAD

**Issue by Xeno4K** [ShadowMario/FNF-PsychEngine#9051]
### Describe your problem here.

I want a cutscene in my mod thats unskippable, and then it plays the regular FNF menu. Or vice vercsa, in which the intro plays and then it shows the cutscene after pressing Start

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Alot of Source and Lua things

**Comment by Itz-Miles** [comment]
You'd have to be a little more specific; ShadowMario doesn't play a lot of mods. You want an unskippable video cutscene to play before TitleState?

**Comment by Xeno4K** [comment]
> You'd have to be a little more specific; ShadowMario doesn't play a lot of mods. You want an unskippable video cutscene to play before TitleState?

Yes, and before or after title state, preferably after.

**Comment by Xeno4K** [comment]
> For videos outside of playstate, you can put this line anywhere you want: `new FlxVideo('assets/videos/your video name.mp4');`

I put this in MainMenuState.hx, but the cutscene audio plays, but the cutscene itself isnt there.

**Comment by Itz-Miles** [comment]
what platform are you on, and did you add the video before the background was added?

**Comment by Xeno4K** [comment]
> what platform are you on, and did you add the video before the background was added?

Im on windows, and how do I know specifically where to add the video before the background?

**Comment by Itz-Miles** [comment]
You want to make sure the video is added after the BG. Search for the second `add(versionShit);` in MainMenuState.hx, and add your video line right under it. This makes sure the video is laid on top of the menu so it can be seen.

**Comment by Xeno4K** [comment]
> You want to make sure the video is added after the BG. Search for the second `add(versionShit);` in MainMenuState.hx, and add your video line right under it. This makes sure the video is laid on top of the menu so it can be seen.

Thanks, you helped me make it appear but theres still one more tiny little problem. I want the cutscene to act like how it would in a week, but unskippable. In the cutscene I can still hear the main menu music as well as press the menu buttons while the cutscenes showing, I want it to be just the cutscene, then it loads the main menu.

**Comment by Itz-Miles** [comment]
I was away for a bit. I'm making a cutscene state.

**Comment by Xeno4K** [comment]
> I was away for a bit. I'm making a cutscene state. What is your video's filename?

Cutscene-Shape1

**Comment by Matriniii** [comment]
> new FlxVideo('assets/videos/your video name.mp4');

how, i need it so can you pls explain how
@Xeno4K

**Comment by Itz-Miles** [comment]
> > new FlxVideo('assets/videos/your video name.mp4');
> 
> how, i need it so can you pls explain how @Xeno4K

It depends on two factors now; whether you compile in release mode, and if you're using hxCodec.

For non-release targets using hxCodec, use these two lines anywhere in any file you like.
```
var video:MP4Handler = new MP4Handler();
video.playVideo(filepath);
```
For release targets, you can't make a new state that interrupts outdatedState if it's enabled. You can play it anywhere else though.

**Comment by StinkTheStinker** [comment]
is there a way to make the cutscene out of a spritesheet?

**Comment by ThatXS1Guy** [comment]
> Reference

Could you explain how to do this before the opening menu appears aswell?
