### ISSUE TITLE
What the heck just happened

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#9053]
### Describe your problem here.

I tried to compile my game, and this happened:
![erorr](https://user-images.githubusercontent.com/101440491/173278042-1c64ecf1-571c-4f48-855a-2141e6a11968.png)
The code is:
![code](https://user-images.githubusercontent.com/101440491/173278084-080bfb34-c574-43b1-bb1f-1bd7bc7a56e4.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added the funtion, but it comes but error

**Comment by hayfii** [comment]
You forgot to save...

**Comment by Itz-Miles** [comment]
You also have to clarify what kind of variable it is if you're declaring and using it in the same line.
 `var warningText:FlxText = new FlxText(350, 300, "Press SPACE!", 500);`

**Comment by hayfii** [comment]
![image](https://user-images.githubusercontent.com/94598301/173324696-ff8310ef-eda3-40b0-b618-da97fb7d0949.png)
This doesn't seem right, even if you stole the code your "smart brain" could have fixed it.

**Comment by Wither362** [comment]
Ehm, those aren’t the lines that are giving errors

**Comment by hayfii** [comment]
> Ehm, those aren’t the lines that are giving errors

Good eyes

**Comment by Mastercopper2346** [comment]
> > Ehm, those aren’t the lines that are giving errors

> good eyes

I know that, plus I edited it and forgot to close 💀
