### ISSUE TITLE
Character tweens

### ISSUE THREAD

**Issue by jaywronaldisdumb** [ShadowMario/FNF-PsychEngine#9054]
### Describe your problem here.

I want to add a tween on the gf to make her move to the right on the stage

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by hayfii** [comment]
Wdym? Can you be more specific?

**Comment by jaywronaldisdumb** [comment]
I want to make the gf move with tweens but im not sure what tween to use

**Comment by Lorekeeper49** [comment]
```lua
doTweenX('movegfx', 'gf', POS, duration, 'linear');
doTweenY('movegfy', 'gf', POS, duration, 'linear');
doTweenAlpha('gfalphs', 'gf', opacity, duration, 'linear');
```
Use either of these
