### ISSUE TITLE
I can't compile the game due to this error >:(

### ISSUE THREAD

**Issue by nebniywolf** [ShadowMario/FNF-PsychEngine#9056]
### I can't compile the game due to this error. Psych Engine 0.4.2!

![2022-06-13_201834](https://user-images.githubusercontent.com/104686407/173409183-ef988ac8-453f-49d0-968f-58fb33a6b75e.jpg)
![2022-06-13_200526](https://user-images.githubusercontent.com/104686407/173408271-6ae5a97c-bbe8-4509-9f3a-3d591e5797b8.jpg)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Im edit this
![2022-06-13_202125](https://user-images.githubusercontent.com/104686407/173409671-3ab7173f-fab2-406b-9ce7-4daa5444223d.jpg)
![2022-06-13_202135](https://user-images.githubusercontent.com/104686407/173409690-91fb9266-f9a3-405d-9d53-5926fbb33b5e.jpg)

**Comment by nebniywolf** [comment]
I can send you the source code. Necessary?

**Comment by Wither362** [comment]
Write a `}` before the line 1639, that is this:
```hx
var debugNum:Int = 0;
```

**Comment by nebniywolf** [comment]
I don't know where to write }

**Comment by Wither362** [comment]
> I don't know where to write }

Before what I said you

**Comment by Wither362** [comment]
> I can send you the source code. Necessary?

Well, if you give it to me, I will fix all the errors and unnecessary things from the code and I’ll give it to you

**Comment by Wither362** [comment]
> Okay, where do you want it sent?

Drive

**Comment by nebniywolf** [comment]
Okay, one minute.

**Comment by nebniywolf** [comment]
https://drive.google.com/file/d/1_y4b48iq5qV6oP7j8d4GefBVCCsrkpJP/view?usp=sharing

**Comment by Wither362** [comment]
Ok

**Comment by nebniywolf** [comment]
This

**Comment by Wither362** [comment]
I don’t have access

**Comment by nebniywolf** [comment]
Oh

**Comment by Wither362** [comment]
If you make it public, anyone with the link can access to it

**Comment by nebniywolf** [comment]
https://drive.google.com/file/d/1_y4b48iq5qV6oP7j8d4GefBVCCsrkpJP/view?usp=sharing

**Comment by Wither362** [comment]
> https://drive.google.com/file/d/1_y4b48iq5qV6oP7j8d4GefBVCCsrkpJP/view?usp=sharing

Now I have access, I will fix it

**Comment by nebniywolf** [comment]
Oh

**Comment by nebniywolf** [comment]
Sorry
idk this settings

**Comment by Wither362** [comment]
Here’s: https://drive.google.com/file/d/11mlEm_oF9TVU3AGJI4EzEC3s4vpy302o/view?usp=drivesdk

**Comment by nebniywolf** [comment]
Thank you!

**Comment by Wither362** [comment]
> Thank you!

Look if it gives errors and if in case that it gives it, said it to me

**Comment by Wither362** [comment]
Delete the line 3016

**Comment by nebniywolf** [comment]
![2022-06-14_142719](https://user-images.githubusercontent.com/104686407/173566876-ad1b7461-6fb8-4aed-91ec-20425c981934.jpg)

**Comment by Wither362** [comment]
Look it by yourself in the psych engine playstate

**Comment by nebniywolf** [comment]
This?
![2022-06-14_142719](https://user-images.githubusercontent.com/104686407/173567318-1f587d69-6963-45f4-bfa4-b80913218cda.jpg)

**Comment by Wither362** [comment]
> This?
> ![2022-06-14_142719](https://user-images.githubusercontent.com/104686407/173567318-1f587d69-6963-45f4-bfa4-b80913218cda.jpg)

You miss the `onSongComplete`, look at the psych engine playstate and copy the missing code

**Comment by nebniywolf** [comment]
Im test

**Comment by nebniywolf** [comment]
![2022-06-14_143422](https://user-images.githubusercontent.com/104686407/173567944-a7574654-76e7-45f8-b0de-2420e4f41d9f.jpg)

**Comment by Wither362** [comment]
> ![2022-06-14_143422](https://user-images.githubusercontent.com/104686407/173567944-a7574654-76e7-45f8-b0de-2420e4f41d9f.jpg)

Duplicate means that one of the functions that is declarating is already declared, and the unknown identifier means that you need code, with this information, solve it by yourself please

**Comment by nebniywolf** [comment]
![2022-06-14_144048](https://user-images.githubusercontent.com/104686407/173568968-a5e7e9f1-d0d7-4799-a9a3-3297fcae0196.jpg)

**Comment by nebniywolf** [comment]
![2022-06-14_144115](https://user-images.githubusercontent.com/104686407/173569032-eab07c5a-deff-4e9d-93ed-df7fd21e06b1.jpg)

**Comment by Wither362** [comment]
Delete that pink `}`

**Comment by nebniywolf** [comment]
![2022-06-14_144641](h
![2022-06-14_144657](https://user-images.githubusercontent.com/104686407/173569959-16155557-9874-4433-b297-717de7f30ee3.jpg)
ttps://user-images.githubusercontent.com/104686407/173569951-1c89d9d7-eb0b-4aab-ada7-de4698cb7df8.jpg)

**Comment by nebniywolf** [comment]
![2022-06-14_144641](https://user-images.githubusercontent.com/104686407/173569998-c54dd5c7-96e6-42ab-97b2-61bef98fc5eb.jpg)

**Comment by nebniywolf** [comment]
### _bruh_

**Comment by Wither362** [comment]
Uh

**Comment by nebniywolf** [comment]
Yes?

**Comment by Wither362** [comment]
The code that have an extra tab (``) should be in a function

**Comment by nebniywolf** [comment]
What do you mean?

**Comment by Wither362** [comment]
> What do you mean?

Do you know what’s tab?

**Comment by nebniywolf** [comment]
no
<._.>

**Comment by nebniywolf** [comment]
This?
![2022-06-14_145439](https://user-images.githubusercontent.com/104686407/173571226-5d0deaa1-e0d7-4a04-b49b-2c5b1d79c4d9.jpg)

**Comment by Wither362** [comment]
No

**Comment by nebniywolf** [comment]
And what?

**Comment by Wither362** [comment]
this is a tab ![tab key](https://static3.depositphotos.com/1003004/153/i/950/depositphotos_1536137-stock-photo-keyboard-tab-key.jpg)

**Comment by Wither362** [comment]
Is a big space

**Comment by nebniywolf** [comment]
Ok
And?

**Comment by nebniywolf** [comment]
public function?

**Comment by Wither362** [comment]
Ok okokoko

**Comment by Wither362** [comment]
Delete the lines from 1531 up to 1541

**Comment by nebniywolf** [comment]
![2022-06-14_150112](https://user-images.githubusercontent.com/104686407/173573252-014cee46-4965-4b62-aaa8-e65fec8e39c9.png)

**Comment by nebniywolf** [comment]
64 comments

**Comment by nebniywolf** [comment]
ok

**Comment by nebniywolf** [comment]
![2022-06-14_151004](https://user-images.githubusercontent.com/104686407/173573815-8f4d30b2-c144-4e25-a8ed-27e311c4652c.jpg)

**Comment by nebniywolf** [comment]
bro

**Comment by nebniywolf** [comment]
im install new engine

**Comment by nebniywolf** [comment]
Can I finish?

**Comment by nebniywolf** [comment]
Okay, I'm done. Good luck in your mod!
