### ISSUE TITLE
How to add new directories for weeks, Like week 6, week 7, etc

### ISSUE THREAD

**Issue by tdog8785** [ShadowMario/FNF-PsychEngine#9057]
### Describe your problem here.

I am creating new weeks for my mod and since I'm using source code I wanted to make everything more professional looking, instead of putting all of my stage files inside of shared. So I created the new weeks like week 8 and week 9 for example. And it's just showing a black background. I know it's working because the Default Zoom works just fine. I also filled out the directory location on the stage file and it's still not working. I did notice that when I do load a song from the new weeks or go into story mode it says "source/Paths.hx:358: oh no its returning null NOOO" So maybe that could be the game telling me something I just can't tell.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by CrusherMods** [comment]
look in project.xml

**Comment by ShadowMario** [comment]
Copy all instances of `week7` in Project.xml and change to your folder's name
