### ISSUE TITLE
Execute code from clicking on someone's credits section.

### ISSUE THREAD

**Issue by AntiPlayzz** [ShadowMario/FNF-PsychEngine#9059]
### Describe your problem here.

How do you execute some code from pressing enter on someone's credits section, i think it pretty much explains itself, help would be appreciated!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Stilic** [comment]
no cuz security issue

**Comment by hayfii** [comment]
What kind of code?

**Comment by AntiPlayzz** [comment]
> What kind of code?

like example opening up a song when the section is pressed

**Comment by CPPxfnfmodsmaker** [comment]
![headings-rendered](https://user-images.githubusercontent.com/101651840/173579201-1fda64e7-a6a1-49ab-bb97-f2e1fe9c5970.png)

**Comment by hayfii** [comment]
> > What kind of code?
> 
> like example opening up a song when the section is pressed

Sure can do, give me your CreditsState.hx.

**Comment by AntiPlayzz** [comment]
[Alright, here it is.](https://github.com/ShadowMario/FNF-PsychEngine/files/8900152/CreditsState.zip)

**Comment by AntiPlayzz** [comment]
> > > What kind of code?
> > 
> > 
> > like example opening up a song when the section is pressed
> 
> Sure can do, give me your CreditsState.hx.
[Alright, here it is.](https://github.com/ShadowMario/FNF-PsychEngine/files/8900161/CreditsState.zip)

**Comment by hayfii** [comment]
> > > > What kind of code?
> > > 
> > > 
> > > like example opening up a song when the section is pressed
> > 
> > 
> > Sure can do, give me your CreditsState.hx.
> > [Alright, here it is.](https://github.com/ShadowMario/FNF-PsychEngine/files/8900161/CreditsState.zip)

What's the song name and difficulty?

**Comment by AntiPlayzz** [comment]
> 

you can make it just test on normal difficulty and pick any credit
