### ISSUE TITLE
how to make notes' alpha change? (event)

### ISSUE THREAD

**Issue by acap09** [ShadowMario/FNF-PsychEngine#906]
### Describe your problem here.

im trying to make an event where Player 2 (the opponent)'s notes fade in and out using 1 event. I just need a note Alpha change or something

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

added 2 new weeks, 4 characters, 2 songs and charts

### not important

this section is not important at all

**Comment by ShadowMario** [comment]
`noteTweenAlpha`, [check this out](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers#notetweenalphatagstring-noteint-valuedynamic-durationfloat-easestring)
