### ISSUE TITLE
Wont Compile

### ISSUE THREAD

**Issue by KashperIsCool** [ShadowMario/FNF-PsychEngine#9062]
### Describe your problem here.

The Game Wont Compile even when i download a new version
![bru](https://user-images.githubusercontent.com/105392885/173674365-0c6989a6-c1ea-46c4-b9bd-8c18f7575548.png)
 and i lost my whole mod but its alr i didnt have anything really,

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Install new luajit

```
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
```

**Comment by KashperIsCool** [comment]
@frantastic24 it didnt work

**Comment by frantastic24** [comment]
Something went wrong on your end then

**Comment by Wither362** [comment]
Run 
```cmd
haxelib remove linc_luajit
```
and run
```cmd
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
```
