### ISSUE TITLE
how to customize notes to very far?

### ISSUE THREAD

**Issue by ArtemB0Y** [ShadowMario/FNF-PsychEngine#9066]
### Describe your problem here.

i want customize notes, but them must be a far, give code plz

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Mastercopper2346** [comment]
> i want customize notes, but them must be a far, give code plz

What do you mean byt that?

**Comment by Wither362** [comment]
Resize the notes to small to create a far effect

**Comment by ArtemB0Y** [comment]
> Resize the notes to small to create a far effect

Give Example

**Comment by ArtemB0Y** [comment]
> > i want customize notes, but them must be a far, give code plz
> 
> What do you mean by that?

ah! okay

**Comment by Wither362** [comment]
> > Resize the notes to small to create a far effect
> 
> Give Example

Resize it to `size / 3` (is an example) and then use the code

**Comment by ArtemB0Y** [comment]
> > > Resize the notes to small to create a far effect
> > 
> > 
> > Give Example
> 
> Resize it to `size / 3` (is an example) and then use the code



> > > Resize the notes to small to create a far effect
> > 
> > 
> > Give Example
> 
> Resize it to `size / 3` (is an example) and then use the code

ok, thanks
