### ISSUE TITLE
Files don't stop doing things when deleted?

### ISSUE THREAD

**Issue by Pipis-man** [ShadowMario/FNF-PsychEngine#9067]
### Describe your bug here.

There is a bug where scripts will keep running, even when deleted. I tried removing them from the recycle bin and not even that fixed it.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Added two new pause menu tracks

**Comment by AntiPlayzz** [comment]
Delete it from the export

**Comment by ShadowMario** [comment]
It's not a bug, it keeps files cached until you close the game or enter a song from another mod/vanilla to reduce loading times.
