### ISSUE TITLE
Perlin Noise

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#9070]
### What is your question?

How could I add perlin noise using Lua?
I was thinking something like `math.noise(x:int, y:int)` but it didnt work :(

**Comment by ManMaster707** [comment]
If you want to generate an image using code (from wikipedia), my best guess is to try [this](https://gist.github.com/kymckay/25758d37f8e3872e1636d90ad41fe2ed) or [this](https://stackoverflow.com/questions/33425333/lua-perlin-noise-generation-getting-bars-rather-than-squares),

if you want to do some obsolete math thing (from your code), then idk what you're even talking about,

hope this helps.

**Comment by tylerandari12** [comment]
That's what I was looking for. Thanks!
