### ISSUE TITLE
Alpha Tween on animated sprite

### ISSUE THREAD

**Issue by AntCrem** [ShadowMario/FNF-PsychEngine#9071]
### Describe your problem here.

So I'm trying to do a alpha tween on a animated lua sprite and it doesn't work

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nu

**Comment by frantastic24** [comment]
It works exactly the same animated or not, if it doesn't then you did something wrong
And if you're asking for help you're supposed to show the script

**Comment by AntCrem** [comment]
right sorry 
function onBeatHit()

	if curBeat == 340 then
	doTweenAlpha('bg','darkSpaceBG', 0.15, 1, 'linear')

**Comment by frantastic24** [comment]
Post the entire script, not just this small piece

**Comment by ManMaster707** [comment]
my best guess from this snippet is that the sprite's tag is incorrect, because it works fine for me, try checking if the sprite's tag is the same as the original tag found in the stage's lua file.

(though @frantastic24 is right, post the entire script)

**Comment by roaring213** [comment]
Tweens on sprites don't work, I've tried this before, but it was an X tween.

**Comment by frantastic24** [comment]
> Tweens on sprites don't work

???? That's a problem with your code
