### ISSUE TITLE
Opponent skip notes

### ISSUE THREAD

**Issue by Scorpion105951** [ShadowMario/FNF-PsychEngine#9072]
### Describe your problem here.

I want make something like event when opponent skip notes, something like song Buffer from NuSky

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by jmxamongusmodder** [comment]
just steal the code from NuSky also its called a miss note if you want to do it without porting code then just use the no animation note.

**Comment by jmxamongusmodder** [comment]
> just steal the code from NuSky also its called a miss note if you want to do it without porting code then just use the no animation note.

The camera movement is an event in nusky LOL

**Comment by ShadowMario** [comment]
![](https://user-images.githubusercontent.com/44785097/174229569-bfa663e9-51cf-4571-a2f1-fc712a574254.png)

**Comment by Scorpion105951** [comment]
> just steal the code from NuSky also its called a miss note if you want to do it without porting code then just use the no animation note.

i forgot about what opponent can dont hit notes if u wrote this in code. But, ty

**Comment by Scorpion105951** [comment]
> ![](https://user-images.githubusercontent.com/44785097/174229569-bfa663e9-51cf-4571-a2f1-fc712a574254.png)

lol, i wrote what i want to opponent skip notes, it doesnt matter khow u nusky or no
