### ISSUE TITLE
Help me pls (stage coding)

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#9074]
### Describe your problem here.

I want to code a stage that has a stage change triggered by Play Animation. In value1 you write 1 and it changes the stage. What am i doing wrong?

```
			case 'stagecat': //Secret Bongo Cat
				var bg:BGSprite = new BGSprite('stageback', -600, -200, 0.9, 0.9);
				add(bg);

				var stageFront:BGSprite = new BGSprite('stagefront', -650, 600, 0.9, 0.9);
				stageFront.setGraphicSize(Std.int(stageFront.width * 1.1));
				stageFront.updateHitbox();
				add(stageFront);

				var bgCat:BGSprite = new BGSprite('catpaper', -600, -200, 0.9, 0.9);
				add(bgCat);

				function triggerEvent(eventName:String, value1:String, value2:String) {
					switch(eventName)
						case 'Play Animation':
							if value1 = '1'
								bgCat.alpha = 0;
							end
						end
					end
				end

```
P.S. i am not very advanced at coding, i know mainly LUA

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, PlayState.hx, TitleState.hx and StoryMode.hx (idk maybe i got the names wrong)

**Comment by hayfii** [comment]
Contact me on Discord Hayfi#0004
(cuz i willbe asking many questions)

**Comment by CheesecakeForever** [comment]
I don't have discord.

**Comment by Itz-Miles** [comment]
Make sure your event function is nested under onupdate(elapsed), and call it, case 'catPlayAnimation': so it doesn't overlap other cases.

**Comment by CheesecakeForever** [comment]
> Make sure your event function is nested under onupdate(elapsed), and call it, case 'catPlayAnimation': so it doesn't overlap other cases.

as i mentioned, i don't know how to do this in source. If you could, can you post the fixed script? thanks for the reply tho

**Comment by hayfii** [comment]
> > Make sure your event function is nested under onupdate(elapsed), and call it, case 'catPlayAnimation': so it doesn't overlap other cases.
> 
> i don't know how to do this in source, i just know lua. If you could, can you post the fixed script? thanks for the reply tho



> I don't have discord.

oh well

**Comment by Itz-Miles** [comment]
go to chartingstate.hx next, and add your event description to the list. You're all good!

**Comment by hayfii** [comment]
> go to chartingstate.hx next, and add your event description to the list. You're all good!

ok nevermind he helped you

**Comment by CheesecakeForever** [comment]
Thank you so much! Gonna test it out and see what happens!

**Comment by CheesecakeForever** [comment]
> > go to chartingstate.hx next, and add your event description to the list. You're all good!
> 
> ok nevermind he helped you

Thanks for your help too!

**Comment by CheesecakeForever** [comment]
source/PlayState.hx:2749: characters 5-10 : Unknown identifier : bgCat

**Comment by hayfii** [comment]
> source/PlayState.hx:2749: characters 5-10 : Unknown identifier : bgCat

at your stage, replace var bgCat:BGSprite with bgCat
then at lines like 136 or somewhere else add var bgCat:BGSprite;

**Comment by CheesecakeForever** [comment]
Finally, it's compiling! Thank you!

**Comment by CheesecakeForever** [comment]
You are probably getting annoyed at this point, but when i put the event it doesn't do anything. Help?

**Comment by CheesecakeForever** [comment]
Yessssss i got it to work!! Thank you all!
