### ISSUE TITLE
Cam Effect?

### ISSUE THREAD

**Issue by KashperIsCool** [ShadowMario/FNF-PsychEngine#9076]
### Describe your problem here.

how do i add a effect like bbpanzu did in this live stream
![Screenshot 2022-06-16 153147](https://user-images.githubusercontent.com/105392885/174150196-54093cf7-9898-4f83-a84c-d3e0cf38cddf.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by 8bitjake** [comment]
for some reason, effects were removed. sorry bud

**Comment by Mastercopper2346** [comment]
Wait their still can do in source

**Comment by Mastercopper2346** [comment]
Reopen it
