### ISSUE TITLE
How To Size Window In Song?

### ISSUE THREAD

**Issue by ArtemB0Y** [ShadowMario/FNF-PsychEngine#9077]
### Describe your problem here.

I Wan't Make Mechanic With Sizing Window In Song! Give Code Plz!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by KashperIsCool** [comment]
do haxelib remove https://github.com/nebulazorua/linc_luajit
then haxelib install https://github.com/nebulazorua/linc_luajit
^ Worked For Me :)

**Comment by BendyGaming0** [comment]
I think you are looking for something like this
`setPropertyFromClass('lime.app.Application', 'current.window.width', 1280)`
width can be exchanged with height, x or y.

**Comment by ArtemB0Y** [comment]
> I think you are looking for something like this `setPropertyFromClass('lime.app.Application', 'current.window.width', 1280)` width can be exchanged with height, x or y.

thanks, that full code?
