### ISSUE TITLE
issue to issue

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#9078]
### Describe your problem here.

I've been waiting for a fucking week:
#8976
 █ █ █ █ █ █ █ █ █ █ i wrote this at 3 am 😳 😳 █ █ █ █ █ █ █ █ █ █ █ █ █ █ 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just modded in the "example_mods" folder

**Comment by ShadowMario** [comment]
some mf literally answered your question stop doing other posts

**Comment by TFLTV** [comment]
how do I delete issues

**Comment by Mastercopper2346** [comment]
No

**Comment by TFLTV** [comment]
> No

like the one from commits

**Comment by Mastercopper2346** [comment]
?

**Comment by TFLTV** [comment]
> ?

https://github.com/ShadowMario/FNF-PsychEngine/commits
