### ISSUE TITLE
Stage BG is just black

### ISSUE THREAD

**Issue by Xeno4K** [ShadowMario/FNF-PsychEngine#9079]
### Describe your problem here.

When I try to play the song, the stage BG doesnt appear, its just pitch black. When I press 7 and go into chart editor, the stage is still there. Everything else is fine, but its just the BG that doesnt appear.

This pops up in CMD as well

source/Paths.hx:357: oh no its returning null NOOOO

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Alot of things in source and assets

**Comment by CrusherMods** [comment]
the file was located in the wrong place according to your error

**Comment by Xeno4K** [comment]
> the file was located in the wrong place according to your error

so which folder in assets should i put stage BGs in?

**Comment by Lorekeeper49** [comment]
> > the file was located in the wrong place according to your error
> 
> so which folder in assets should i put stage BGs in?

stages

**Comment by BlearChipmunk** [comment]
nope, the stage images need to be on the "mods/images" folder, if you want them to be on a custom one just make another inside that folder, like this "mods/images/bgcrap" and then in your lua you need to make this to make the engine recognize the file "bgcrap/nameofthebgimage" 

it should look like this

		makeLuaSprite('stage1/BG_WALL', 'stage1/BG_WALL', -152, -171);
		setScrollFactor('BG_WALL', 1.1, 1.1);
		scaleObject('BG_WALL', 2.3, 2.3);

	addLuaSprite('stage1/BG_WALL', false);

**Comment by CrusherMods** [comment]
> nope, the stage images need to be on the "mods/images" folder, if you want them to be on a custom one just make another inside that folder, like this "mods/images/bgcrap" and then in your lua you need to make this to make the engine recognize the file "bgcrap/nameofthebgimage"
> 
> it should look like this
> 
> ```
> 	makeLuaSprite('stage1/BG_WALL', 'stage1/BG_WALL', -152, -171);
> 	setScrollFactor('stage1/BG_WALL', 1.1, 1.1);
> 	scaleObject('stage1/BG_WALL', 2.3, 2.3);
> 
> addLuaSprite('stage1/BG_WALL', false);
> ```

hes on source
it doesn't need to go there

**Comment by Xeno4K** [comment]
figured out how to fix
