### ISSUE TITLE
camera shake is broken or is it me?

### ISSUE THREAD

**Issue by OliwerGamer64** [ShadowMario/FNF-PsychEngine#9081]
### Describe your problem here.

one day i put camera shake event and for me won't work i unchecked and won't work again pls help me or else i will cry

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

using 0.4.2

**Comment by ShadowMario** [comment]
0.4.2 isn't supported anymore

**Comment by Mastercopper2346** [comment]
It goes like:
V1: 12, 0.05
V2: 12, 0.05

V1: duration then shake for the game
V2: duration then shake for the HUD(UI)

Don’t worry. I had the same problem too.
