### ISSUE TITLE
3 features for the next update!!!

### ISSUE THREAD

**Issue by OliwerGamer64** [ShadowMario/FNF-PsychEngine#9082]
### What feature do you want to get added on the **base** engine?

1. The Gain Note: gain note will help you gain into +2 health if you hit it this happens
2. The GF Scared Event: 1. seconds to 1.7 or 5.2 or anything 2. leave number 2 blank
3. and lastly, The Camera Rotate: 1. speeds 1 2 and 3 2. leave number 2 blank
what do you think?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Better LUA mod support idea

**Comment by ShadowMario** [comment]
no

**Comment by Mastercopper2346** [comment]
Failed the test

**Comment by Mastercopper2346** [comment]
1. Will never add
2. Good idea, could be added
3. Uhh how is that supposed to work?

**Comment by impostor5875** [comment]
make these all yourself, these are all possible in lua
