### ISSUE TITLE
How do i make the camera zoom in and black out when i select a section in the main menu

### ISSUE THREAD

**Issue by GitHubSmelz** [ShadowMario/FNF-PsychEngine#9085]
### Describe your problem here.

i want to make the effect of the camera zooming in when you select a section in the main menu like this vs. mouse thing does
using lua (because im kinda stupid with source, and also with lua but im better at lua i swear) so i want some help with the code

here is an example of how the zooming in looks:

https://user-images.githubusercontent.com/105386082/174200215-c92759c6-2b78-4821-a2ca-b3b790560db9.mp4

yeah something like that, i would appreciate some help in doing it

(also ignore my clear lack of knowledge of the english language, because im spanish)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
You need source

**Comment by GitHubSmelz** [comment]
well in that case i will download source, code the main menu camera zoom and with the compiled build i will do everything else with lua because im lazy, thanks kind stranger
![iforgorhowtosource](https://user-images.githubusercontent.com/105386082/174202081-fcf89186-1edc-4cc4-b58a-4e94a38ffd49.jpg)


> You need source
