### ISSUE TITLE
? ERROR OF FUNKIN LUA

### ISSUE THREAD

**Issue by JAMES0711PVPYT** [ShadowMario/FNF-PsychEngine#9086]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/95061460/174203426-5d0c00a5-9761-4aab-af11-96cd7eb4901a.png)
Error for source/FunkinLua.hx:2519: characters 7-35 : Int should be Bool

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes but only of Main

**Comment by L044washere** [comment]
Redownload the engine, that may work.

**Comment by Gibberditoslumber** [comment]
no use [This ](https://github.com/nebulazorua/linc_luajit)

**Comment by ShadowMario** [comment]
```haxe
haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
```

**Comment by JAMES0711PVPYT** [comment]
Thanks :)
