### ISSUE TITLE
cannot copy introText.txt

### ISSUE THREAD

**Issue by L044washere** [ShadowMario/FNF-PsychEngine#9087]
### Describe your problem here.

help i was trying to compile and this appeared
Error: Cannot copy to "export/release/windows/bin/assets/data/introText.txt", is the file in use?

what is this i need help
if you have a solution, tell me
thanks

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I had some edited files but i started from scratch so i don't remember well

**Comment by CrusherMods** [comment]
your psych engine build probably needs to be closed

**Comment by L044washere** [comment]
> your psych engine build probably needs to be closed

Thanks for the help! I closed it and it now works good!

**Comment by hayfii** [comment]
> > your psych engine build probably needs to be closed
> 
> Wait, so I uninstall the build or what do I do exactly? sorry, i'm new for this kinda stuff.

Close opened files from the source code duh

**Comment by ShadowMario** [comment]
Close your currently opened instance of PsychEngine.exe

**Comment by L044washere** [comment]
It seem to work but:
Standard library not found. You may need to set your `HAXE_STD_PATH` environment variable
I don't get this, what this means? (yea i don't know anything about this type of stuff)
