### ISSUE TITLE
How do i add a change noteskin event (Source code)?

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#9092]
### Describe your problem here.

The title.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, PlayState.hx, TitleState.hx and StoryMode.hx (idk maybe i got the names wrong)

**Comment by BlearChipmunk** [comment]
here is the lua event

`
function onCreate()
   precacheImage('mods/images/stepmaniacool')

end

function onEvent(name, value1, value2) 
	if name == 'noteskinchangeOPPT' then
	if value1 == '' then
	-- do nothing lol
	else
		for i = 0, getProperty('opponentStrums.length')-1 do
			setPropertyFromGroup('opponentStrums', i, 'texture', value1);
		end
		for i = 0, getProperty('unspawnNotes.length')-1 do
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') == false then
			setPropertyFromGroup('unspawnNotes', i, 'texture', value1);
			end
		end
	end 
	
	if value2 == '' then
	-- do nothing lol
	else
		for i = 0, getProperty('unspawnNotes.length')-1 do
			if getPropertyFromGroup('unspawnNotes', i, 'mustPress') == false then
			setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', value2);
			end
		end
	end
end
end
`

and this is the txt file


Sets the Noteskin for Opponent side to a png and xml found in mods/images 
value 1: the Noteskin's name
value 2: the Noteskin's Splashes (Optional)
if blank will do nothing
WILL NOT CHANGE THE CUSTOM NOTES OR THIER SPLASHES

**Comment by CheesecakeForever** [comment]
Thank you, but I need source code.

**Comment by BlearChipmunk** [comment]
whoops, my bad

**Comment by CheesecakeForever** [comment]
Look it's not bad someone else might need this
