### ISSUE TITLE
Help on making event (source code)

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#9094]
### Describe your problem here.

So i want to make a white flash event that fades after it's triggered. Can someone post me the code if you know how to? I would be very grateful. You will also be credited in the credits screen and on gamebanana.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, PlayState.hx, TitleState.hx and StoryMode.hx (idk maybe i got the names wrong)

**Comment by ShadowMario** [comment]
The github issues are not for asking people to code things to you.
