### ISSUE TITLE
Girlfriend In front (LUA)

### ISSUE THREAD

**Issue by Maxenswel** [ShadowMario/FNF-PsychEngine#9097]
### Describe your problem here.

Is it possible to place the girfriend in front of the boyfriend and the opponent in LUA plz ? (not in front of the HUD) thanks

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Maxenswel** [comment]
> you shoud add her like a bg image and then in the add lua sprite you need to change from false to true addLuaSprite('girl', true);

I tried it, but the danceLeft and danceRight thing can't be done

**Comment by frantastic24** [comment]
`setObjectOrder()` and `getObjectOrder()` ([wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#object-orderremoving))


>  danceLeft and danceRight thing can't be done

That's literally just using a variable

**Comment by Mastercopper2346** [comment]
OR simply use `setObjectCamera(‘girlfriend’, ‘camHUD’);`

**Comment by ShadowMario** [comment]
> OR simply use `setObjectCamera(‘girlfriend’, ‘camHUD’);`
that's awful

`setObjectOrder('girlfriendGroup', getObjectOrder('boyfriendGroup') + 1);`

**Comment by Mastercopper2346** [comment]
:(

**Comment by Maxenswel** [comment]
> > OR simply use `setObjectCamera(‘girlfriend’, ‘camHUD’);`
> > that's awful
> 
> `setObjectOrder('gfGroup', getObjectOrder('boyfriendGroup') + 1);`

which function and where exactly (data/my song) ?
