### ISSUE TITLE
What am i doing wrong?

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#9100]
### Describe your problem here.

I am adding a secret passcode to the story menu and it just gives me the debug output:
`source/StoryMenuState.hx:276: characters 2-4 : Expected }`

here's my StoryMenuState.hx:
[StoryMenuState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8930820/StoryMenuState.txt)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, PlayState.hx, TitleState.hx and StoryMode.hx (idk maybe i got the names wrong)

**Comment by NS-Unfair** [comment]
Fixed it for ya. You put your code outside of the update function.

[StoryMenuState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8931363/StoryMenuState.txt)

**Comment by CheesecakeForever** [comment]
Thank you so, so, SO much!!

**Comment by CheesecakeForever** [comment]
So I compiled it, and now when i type the passcode (changed to "bongo" now) it doesn't redirect me to the song. Help?
