### ISSUE TITLE
Video problem

### ISSUE THREAD

**Issue by Baneis556** [ShadowMario/FNF-PsychEngine#9101]
### Describe your problem here.

This is the error when i try to compile:
C:/HaxeToolkit/haxe/lib/flixel-ui/2,3,3/flixel/addons/ui/FlxUIPopup.hx:23: characters 13-19 : Field facing has different type than in flixel.IFlxSprite
C:/HaxeToolkit/haxe/lib/flixel/4,11,0/flixel/FlxSprite.hx:1425: characters 2-45 : ... Interface field is defined here
C:/HaxeToolkit/haxe/lib/flixel-ui/2,3,3/flixel/addons/ui/FlxUIPopup.hx:23: characters 13-19 : ... Int should be flixel.util.FlxDirectionFlags
The strange thing is that it wasn't giving this error, after I re-download the source code, it gives me an error that the hxCodec didn't exist, after I installed it and followed the guidelines of this website: https://lib.haxe.org/p/hxCodec/
It started giving this error

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Stilic** [comment]
get latest haxe and haxeflixel and remove the Popup.hx file inside source folder.

**Comment by Baneis556** [comment]
Everything is up to date and this Popup.hx file apparently never existed, the strange thing is that it wasn't giving this error, after I re-download the source code, it gives me an error that the hxCodec didn't exist, after I installed it and followed the guidelines of this website: https://lib.haxe.org/p/hxCodec/
It started giving this error
