### ISSUE TITLE
Character Swap Event

### ISSUE THREAD

**Issue by TurboGames0731** [ShadowMario/FNF-PsychEngine#9105]
### Describe your problem here.

When I use the character swap event, I'll put switch dad to relapse-alt and it'll switch boyfriend. how do i fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Added a custom week and new characters

**Comment by tylerandari12** [comment]
Could I see your script?

**Comment by TurboGames0731** [comment]
where is it? it's one of the scripts that are in the engine when it's downloaded off of gb

**Comment by frantastic24** [comment]
Don't put any caps on the value

**Comment by TurboGames0731** [comment]
it works now, thank you!
