### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by MegaMatt2712** [ShadowMario/FNF-PsychEngine#9109]
### Describe your problem here.

How i can put a custom background? I want to put this background:
![3d-world](https://user-images.githubusercontent.com/104169313/174454604-ee79eef5-d567-4517-8ebe-d6a86502cd8f.png)

Pls help me

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TurboGames0731** [comment]
https://cdn.discordapp.com/attachments/866856727621795850/900523259345371177/ExampleStage.zip
