### ISSUE TITLE
Multiplayer?

### ISSUE THREAD

**Issue by roaring213** [ShadowMario/FNF-PsychEngine#9110]
### What feature do you want to get added on the **base** engine?

Multiplayer would be a GREAT idea for FNF Psych Engine. Yes, I know there is an FNF Multiplayer, but when it comes to mods, you're very limited with your options. You can't add mechanics, special notes, custom backgrounds etc. Adding Multiplayer to Psych Engine would be an EXTREME step-up from FNF Multiplayer, so yeah.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
No

**Comment by roaring213** [comment]
> No

why?

**Comment by frantastic24** [comment]
There is a search feature, use it

**Comment by roaring213** [comment]
> There is a search feature, use it

wdym

**Comment by frantastic24** [comment]
Look up an older issue where shadowmario already said this won't be added

**Comment by roaring213** [comment]
> Look up an older issue where shadowmario already said this won't be added

can you tag it here?

**Comment by frantastic24** [comment]
You can look it up yourself 👍 don't forget to close this too

**Comment by roaring213** [comment]
> You can look it up yourself 👍 don't forget to close this too

I did, & all that showed up was this request

**Comment by frantastic24** [comment]
I'm not teaching you how to do a basic search and I already said this won't be added because it implies way too much work and is unnecessary

**Comment by Swapper1** [comment]
That just the feature from Kickstarter Campaign for the Full Ass game, but we're not going to doing it.

**Comment by Gibberditoslumber** [comment]
> ### What feature do you want to get added on the **base** engine?
> Multiplayer would be a GREAT idea for FNF Psych Engine. Yes, I know there is an FNF Multiplayer, but when it comes to mods, you're very limited with your options. You can't add mechanics, special notes, custom backgrounds etc. Adding Multiplayer to Psych Engine would be an EXTREME step-up from FNF Multiplayer, so yeah.
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Stage Editor, 6K+ support, and winning icons.

They'll have to port forward it through haxelib witch they're not gonna do

**Comment by roaring213** [comment]
@frantastic24 i found the issue you were talking about closing this now.
