### ISSUE TITLE
How to make the Camera Zoom in when you select a Menu

### ISSUE THREAD

**Issue by GitHubSmelz** [ShadowMario/FNF-PsychEngine#9113]
### Describe your problem here.

ok so a few days ago, i made a discussion on how to add the funny camera zooming in when you select any section in the main menu, someone responded "you need source" and i have 0 knowledge on how to use source and which hx file to open (its probably CustomFadeTransition idk) or what is the line of code i need so i would like some help on the subject

im gonna use the same example i used before to let ya'll know what im talking about:

https://user-images.githubusercontent.com/105386082/174203402-a38a60d3-27ae-4fad-9a5c-4aac35ecd093.mp4

(im probably gonna get slapped in the face for not knowing how to do this)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by AquaStrikr** [comment]
That's a custom animation from Mic'd Up Engine's mainmenustate.hx, I recommend you to check Mic'd Up's repository
