### ISSUE TITLE
Hitsounds act weirdly on Botplay with hurt notes

### ISSUE THREAD

**Issue by theamazingnater** [ShadowMario/FNF-PsychEngine#9117]
### Describe your bug here.

If you open a song that has hurt notes with Botplay enabled, and Hitsounds on 100% volume, it'll play the sound constantly, as if it's hitting the hurt note multiple times in a row. 
I placed multiple psych hurt notes in Bopeebo to ensure it wasn't my modded notes, and sure enough, it happens with base hurt notes too.

https://user-images.githubusercontent.com/55967100/174466358-1aea09a5-7097-427a-83ff-bd74388bd607.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
fixed in source a while ago
