### ISSUE TITLE
NOTEPAD EVENT

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#9118]
### Describe your problem here.

Is there a way to make an event that opens a notepad? Like on the D-SIDES mod. If there is, could you pass me the script? it would really help me

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by HaxLua** [comment]
@WilliamGaming12 Look at the sonic.exe 2.0 source code and go in GameOveSubstate.hx look for the function youFuckedUp

**Comment by WilliamGaming12** [comment]
> @WilliamGaming12 Look at the sonic.exe 2.0 source code and go in GameOveSubstate.hx look for the function youFuckedUp

I mean that it oppens the aplication, not  that it's made in the game, like the mighty.zip mod

**Comment by Mastercopper2346** [comment]
`io.open`
