### ISSUE TITLE
opponent skips a notetype ? (Source)

### ISSUE THREAD

**Issue by theo2yeah** [ShadowMario/FNF-PsychEngine#9122]
### What is your question?

Yeah, how could I do that ? As I am making some notetypes but idk how to make it that the opponent don't actually press it

**Comment by PogofruitKM** [comment]
```setPropertyFromGroup('unspawnNotes', i, 'ignoreNote', true);```

Oh and delete 
```if getPropertyFromGroup('unspawnNotes', i, 'mustPress')```

**Comment by frantastic24** [comment]
That's some funny looking source code there

`ignoteNote = true`
