### ISSUE TITLE
A problem with Git

### ISSUE THREAD

**Issue by gghj678910** [ShadowMario/FNF-PsychEngine#9124]
### Describe your problem here.

I install git and after this run haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.
But i have this error: "Error: Could not use git, please make sure it is installed and available in your PATH."

P.S. I check. Git exist in my PATH.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by gghj678910** [comment]
Sorry for bad english

**Comment by Wither362** [comment]
did you double-clicked on the git file?

**Comment by gghj678910** [comment]
> did you double-clicked on the git file?

If you mean on installer then yes
