### ISSUE TITLE
How do i make a Freeplay (or Story Mode) Song Passcode?

### ISSUE THREAD

**Issue by CheesecakeForever** [ShadowMario/FNF-PsychEngine#9125]
### Describe your problem here.

The title. I found an older issue but it doesn't seem to work for me. If anyone could tell me how to do it, i'd be very thankful.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, PlayState.hx, TitleState.hx and StoryMode.hx (idk maybe i got the names wrong)

**Comment by Mastercopper2346** [comment]
I need this code for an option

**Comment by zeadd21g1233** [comment]
code open secret song 
in freeplay ?
like i tipe 
TEST
open TEST SONG 

i have code for this

**Comment by CheesecakeForever** [comment]
YES! i would be very thankful if you shared the code, @zeadd21g1233 !

**Comment by CheesecakeForever** [comment]
Nevermind, D-Sides source code :D
