### ISSUE TITLE
i can't play animated cutscenes or dialogue cutscenes on mac

### ISSUE THREAD

**Issue by AlmondsDiscs** [ShadowMario/FNF-PsychEngine#9127]
### Describe your bug here.

do i have to explain again?
its all in the title
well not really
so basically when i try to open a week with cutscenes the game just crashes
i did try the haxelib install hxCodec
it didn't work
is there something im doing wrong?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

well all i did was put cutscene.lua in the data/songnamehere folder and did nothing with the haxe coding

**Comment by ShadowMario** [comment]
Animated cutscenes aren't supported in Mac and there's no estimated date on when will support be added (if it even gets added at all).
