### ISSUE TITLE
How do i get psych engine with shaders?

### ISSUE THREAD

**Issue by JacksRobotics** [ShadowMario/FNF-PsychEngine#9128]
### What is your question?

im making a fnf mod that looks like from the 90's i wanna add the old tv static thing

**Comment by ManMaster707** [comment]
If you really want it, then try downloading the build mentioned [here](https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/366) (with the WayBack Machine if necessary),
and putting in a .lua script:
```lua
 addVCREffect('camGame')
 addVCREffect('camHud')
 addVCREffect('camOther')-- I'm not sure if this works 100 percent
```

**Comment by JacksRobotics** [comment]
> If you really want it, then try downloading the build mentioned [here](https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/366) (with the WayBack Machine if necessary), and putting in a .lua script:
> 
> ```lua
>  addVCREffect('camGame')
>  addVCREffect('camHud')
>  addVCREffect('camOther')-- I'm not sure if this works 100 percent
> ```

i have a question? what is the site to the way back machine?

**Comment by deathline1938** [comment]
![W O W](https://user-images.githubusercontent.com/94227585/174620464-ceb4af79-5107-4786-bc0f-0af714a5b099.png)
cool :+1:

**Comment by deathline1938** [comment]
function onStepHit()
    if stepHitFuncs[curStep] then 
        stepHitFuncs[curStep]()
    end
end

stepHitFuncs = {
    [10] = function()

 addVCREffect('camGame')-- im change script little bit
 addVCREffect('camHud')
 addVCREffect('camOther')-- I'm not sure if this works 100 percent         
    end
}

**Comment by ManMaster707** [comment]
> what is the site to the way back machine?

just search "the wayback machine" on google lololol
