### ISSUE TITLE
Song descriptions (only on freeplay)

### ISSUE THREAD

**Issue by ManMaster707** [ShadowMario/FNF-PsychEngine#9129]
### What feature do you want to get added on the **base** engine?

I would like to be able to make songs on the freeplay have their own descriptions appear when highlighted, it could be useful for epilepsy warnings, to explain some mechanics in the song, or just a general introduction, it would work like this:

in the .json file of a week:
![examplelol](https://user-images.githubusercontent.com/101059988/174488404-82ce411e-9e6e-4f9b-aab1-bf0d5156a3f0.png)

in the freeplay:
![example2boogaloo](https://user-images.githubusercontent.com/101059988/174488585-c83fcd88-2c83-48e7-89c9-b2b6bcb5c015.png)

and of course, in the freeplay section of the week editor, there would be something that could let you type in the description of a song, while showing a preview of said description.

(forgot to mention, but the description will be appropiately sized based on how much space does the song's name and icons take)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by JavoniCraft** [comment]
Kinda reminds me of SMB Funk Mix, where they have descriptions in the freeplay menu.

**Comment by ManMaster707** [comment]
> Kinda reminds me of SMB Funk Mix, where they have descriptions in the freeplay menu.

In fact, I was inspired by that!

**Comment by ShadowMario** [comment]
No.

**Comment by ManMaster707** [comment]
> No.

zad :(
