### ISSUE TITLE
What are the steps of adding a stage into the game?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#913]
What are the steps of  adding  a stage into the game?

**Comment by acap09** [comment]
like, recreate it?

**Comment by zwl1619** [comment]
@acap09  The animation of the "mall" stage is created in adobe animate or in the game?

**Comment by zwl1619** [comment]
> like, recreate it?

Create another one with animation.

**Comment by acap09** [comment]
im still learning how to make animated background

**Comment by PoleyMagik** [comment]
[bbpanzu's guide](https://www.youtube.com/watch?v=qxMyoudrFPs) is pretty comprehensive, I'd suggest using that. Background guide starts around the 49 min. mark, tho feel free to skip if you feel you feel you understand the concepts he's showing off.
