### ISSUE TITLE
Building fails because of Lua class

### ISSUE THREAD

**Issue by Fl1pNatic** [ShadowMario/FNF-PsychEngine#9131]
### Describe your bug here.

Build just fails. I pulled the last commit from main repo, on the main branch.
```
git status
On branch main
Your branch is up to date with 'origin/main'.
```
The cause is FunkinLua.hx
I personally don't see any way of fixing it myself.

### Command Prompt/Terminal logs (if existing)

```bash
> lime build windows
source/FunkinLua.hx:342: lines 342-346 : Int should be Bool
source/FunkinLua.hx:342: lines 342-346 : ... For function argument 'f'
source/FunkinLua.hx:448: lines 448-451 : Int should be Bool
source/FunkinLua.hx:448: lines 448-451 : ... For function argument 'f'
```
```


### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by frantastic24** [comment]
Install the new luajit, it's on the readme file

**Comment by TheKitBoi** [comment]
Did you git this
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

**Comment by Fl1pNatic** [comment]
> Install the new luajit, it's on the readme file

Thanks, it worked like a charm
