### ISSUE TITLE
The custom song wont work

### ISSUE THREAD

**Issue by MKUKPL** [ShadowMario/FNF-PsychEngine#9134]
### Describe your problem here.

Im trying to make a custom song but it cant find iver the song and Json evan though they are in the "mods" folders

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by LucasOnGithub** [comment]
why does it say your modding with source when your adding the song to mods?

**Comment by Lorekeeper49** [comment]
Check to make sure that the folder has hyphens (-) in place of spaces.
If that's the case then check to make sure if the ogg files are named 'Inst' and 'Voices'.
If so then check to make sure you're spelling the song name correctly in the chart editor
If everything checks out then it's a problem with your files and you might have to redownload them
