### ISSUE TITLE
"error while loading shared libraries: libluajit-5.1.so.2: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by GenesisGreen** [ShadowMario/FNF-PsychEngine#9136]
### Describe your bug here.

When trying to launch Psych Engine from the terminal (I use Linux Mint 20.3 so that's why I have to use it), the terminal responds with "error while loading shared libraries: libluajit-5.1.so.2: cannot open shared object file: No such file or directory" and the game does not open. How do I fix this? I tried reinstalling LuaJit but that did not work.

### Command Prompt/Terminal logs (if existing)

```bash
error while loading shared libraries: libluajit-5.1.so.2: cannot open shared object file: No such file or directory
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by Gibberditoslumber** [comment]
```bash
sudo apt install libluajit-5.1*
```

**Comment by GenesisGreen** [comment]
When I tried installing it, the terminal came up with:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libluajit-5.1
E: Couldn't find any package by glob 'libluajit-5.1'

**Comment by GenesisGreen** [comment]
Just realized that when copy and pasting the command, I forgot to include the * at the end. Now it is working just fine. Thank you for responding!

**Comment by ShadowMario** [comment]
If you've already resolved it then close the issue... Not sure if you noticed but we have a huge spam of issues going on (over 300 open) and this would really help me.

**Comment by Gibberditoslumber** [comment]
> Just realized that when copy and pasting the command, I forgot to include the * at the end. Now it is working just fine. Thank you for responding!

You're Welcome
