### ISSUE TITLE
defaultStrumXY for lua scripts

### ISSUE THREAD

**Issue by naether** [ShadowMario/FNF-PsychEngine#9138]
### What feature do you want to get added on the **base** engine?

so something like

```
if direction <= 3 then
	yourMom = _G["defaultOpponentStrumXY"..direction]
end
if direction >= 4 then
	yourMom = _G["defaultPlayerStrumXY"..direction]
end
```

can be shortened into

`yourMom = _G["defaultStrumXY"..direction]`

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
Already exists in the wiki.

**Comment by naether** [comment]
💀
