### ISSUE TITLE
Deprecated code

### ISSUE THREAD

**Issue by TheSmoothWarrior** [ShadowMario/FNF-PsychEngine#9141]
### What is your question?

I was looking through the source code using VS Code and I couldn't help but notice that in several places FlxCamera.defaultCameras is used when you should be using FlxG.cameras.setDefaultDrawTarget instead.

Are you ever going to address this and if not why?

**Comment by TheRealJake12** [comment]
> ### What is your question?
> 
> I was looking through the source code using VS Code and I couldn't help but notice that in several places FlxCamera.defaultCameras is used when you should be using FlxG.cameras.setDefaultDrawTarget instead.
> 
> Are you ever going to address this and if not why?

dont worry about it. Its fine. Just a warning and if you do what it says, it breaks the game
