### ISSUE TITLE
screen that prevents people form playing on website

### ISSUE THREAD

**Issue by video-tootarolls00** [ShadowMario/FNF-PsychEngine#9145]
### Describe your problem here.

if my mod gets added on a website, i want a screen that tells them to download the actual mod instead. but they cant exit the screen and they are stuck on there, give me a script and an example image please.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by impostor5875** [comment]
```lua
function onStartCountdown()
	if buildTarget == 'browser' then
		makeLuaSprite('noWebsite', 'your image name here', 0, 0) --image should be 1280 x 720
		setObjectCamera('noWebsite', 'camHUD')
		addLuaSprite('noWebsite', true)
		return Function_Stop
	end
	return Function_Continue
end
```

**Comment by Mastercopper2346** [comment]
Cant they just delete the script-

**Comment by impostor5875** [comment]
> Cant they just delete the script-

no because you obviously can't go into the files of websites

**Comment by Mastercopper2346** [comment]
Uhhhh yes they can

**Comment by Mastercopper2346** [comment]
For example: 
Gameverse. 
They can add a WHOLE Entire section in the main menu and it functions correctly.

**Comment by TFLTV** [comment]
> For example: Gameverse. They can add a WHOLE Entire section in the main menu and it functions correctly.

how about you do it in source code.  they can't edit it that way, right?

**Comment by Mastercopper2346** [comment]
> how about you do it in source code. they can't edit it that way, right?

Bruh you can only edit stuff in playstate win lua editing the menu requires source 💀

**Comment by roaring213** [comment]
> Uhhhh yes they can
> 
> Edit: I mean before they release the mod

You can probably make a password for the file in order to delete it.

**Comment by Mastercopper2346** [comment]
Good idea, BUT HOW ARE TIU GONNA DO THAT?

**Comment by roaring213** [comment]
> Good idea, BUT HOW ARE TIU GONNA DO THAT?

https://www.youtube.com/watch?v=45iEZx9BvKY
