### ISSUE TITLE
Recently Built Psych Engine Controls Do Not Work

### ISSUE THREAD

**Issue by PurpleJuice400** [ShadowMario/FNF-PsychEngine#9149]
### Describe your bug here.

I recently installed the psyche engine to start working on a mod following the instructions on a video by Longest Solo Ever (The video in question for reference: https://www.youtube.com/watch?v=4IuC8ti6_4o). I followed the tutorial and the game opens perfectly , however, that is all the code can do. Nothing happens when I input keys. It starts in full screen, but I can't get out of full screen. I press enter, and nothing happens. Is this supposed to happen, or did I miss something and I am just being stupid?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, the code is untouched as of now.

**Comment by Lorekeeper49** [comment]
Try clicking window or the game icon on your taskbar and then attempt to put in inputs

**Comment by bambitheone82112** [comment]
try to restart or idk
