### ISSUE TITLE
Bug after compiling the game

### ISSUE THREAD

**Issue by bambitheone82112** [ShadowMario/FNF-PsychEngine#9150]
### Describe your bug here.

so recently i compiled my game perfectly and when i opened, the engine crashed by called error! null engine name reference

### Command Prompt/Terminal logs (if existing)

```bash
i forgot
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Project.xml and how do i suppos to edit the app name on source

**Comment by Mastercopper2346** [comment]
U broke ur project.xml!

**Comment by bambitheone82112** [comment]
> U broke ur project.xml!

nope, i dont broke it, its just a bug

**Comment by Mastercopper2346** [comment]
You said you edited the project.xml! You probably did something wrong because project.xml doesn’t give you errors on compiling, and it’s basically the game itself!

**Comment by bambitheone82112** [comment]
> You said you edited the project.xml! You probably did something wrong because project.xml doesn’t give you errors on compiling, and it’s basically the game itself!

im quiting psych im getting start on os or others idk
