### ISSUE TITLE
making watermark on a song

### ISSUE THREAD

**Issue by bambitheone82112** [ShadowMario/FNF-PsychEngine#9151]
### Describe your problem here.

so i finished building my awesome mod and i forgot to put watermarks on the song in 0:01 so help me 
(KEEP THIS AS A SECRET: i forgot to put the watermarks on a song in 0:01 with a lua)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

how do i edit in lua

**Comment by silvashp** [comment]
test: failed
