### ISSUE TITLE
Cutscene after Dialogue to finish the week in Story Mode (FNF Psych - Lua Script)

### ISSUE THREAD

**Issue by XavierXP1** [ShadowMario/FNF-PsychEngine#9152]
### Describe your problem here.

Hi there! So, I'm trying to code on FNF Psych Engine in .lua script that, on the last song of the week, it will play the post-dialogue before the cutscene and then it will finish the week. Like this ---> (Last Song of the week > Post-Dialogue > Cutscene > End Week)

But I couldn't find any script for that and Idk how to code it.

Can you help me, please?

P.S. It's FNF Psych Engine and I want the .lua script with the code to help me on.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by bambitheone82112** [comment]
go to https://www.mediafire.com/file/6nra6eecagy30ow/the_thing.rar/file

**Comment by ShadowMario** [comment]
Issues aren't supposed to be used to request code.
