### ISSUE TITLE
Holding shift should make you go father in the chart editor (READ POST)

### ISSUE THREAD

**Issue by EgguMan** [ShadowMario/FNF-PsychEngine#9153]
### What feature do you want to get added on the **base** engine?

While holding shift and pressing A or D, you should move 4 sections instead of 1.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
This already exists and works literally the same way you said.
