### ISSUE TITLE
A few more zoom options for the chart editor

### ISSUE THREAD

**Issue by tensixtyoclock** [ShadowMario/FNF-PsychEngine#9154]
### What feature do you want to get added on the **base** engine?

I would like to be able to use 1.5x, 3x, and 6x zoom options in the chart editor. Having to zoom all the way up to 12x for moderately slow triplets can get very tedious very quickly, so these zoom options would make it easier to chart triplets.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
You can easily do that yourself

**Comment by Wither362** [comment]
you have the quants

**Comment by ShadowMario** [comment]
Done
