### ISSUE TITLE
hi. request. READ.

### ISSUE THREAD

**Issue by N1CKN0TAD3** [ShadowMario/FNF-PsychEngine#9156]
### What feature do you want to get added on the **base** engine?

hi. so i just wanted to say, can you list in the wiki of how to remove certain things from the main menu selection screen? thanks.

T4anoa (if I bothered you, I'm sorry. just a suggestion)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Code optimization that would make the game faster. (You should make a PR if this is your request, by the way.)

**Comment by CrusherMods** [comment]
1. you cant remove main menu crap in lua
2. you failed the test

**Comment by Mastercopper2346** [comment]
> this is more like a Documentation

Right, but you can only create/make stuff in PlayState with lua.

**Comment by Mastercopper2346** [comment]
Plus he failed the test
