### ISSUE TITLE
How Do You Make A Character Float Up And Down In Source Code

### ISSUE THREAD

**Issue by DaRealDotZ** [ShadowMario/FNF-PsychEngine#9157]
### What is your question?

Read Title

**Comment by Mastercopper2346** [comment]
Idk

**Comment by CrusherMods** [comment]
> Idk

THEN WHY COMMENT

**Comment by PogofruitKM** [comment]
Put this in ```override public function create``` AFTER the characters. (Preferably right behind ```callOnLuas('onCreatePost', []);```)
```FlxTween.tween(dad, {y: (dad.y - 40)}, 3.5, {type: FlxTweenType.PINGPONG, ease: FlxEase.quadInOut, loopDelay: 0});```

**Comment by DaRealDotZ** [comment]
Thanks I Will Test It Later
