### ISSUE TITLE
Cutscene after Dialogue in FNF Psych Engine

### ISSUE THREAD

**Issue by XavierXP1** [ShadowMario/FNF-PsychEngine#9158]
### What is your question?

Can someone help me how can I make a post-dialog before the cutscene?

Like, on the end of the last song of the week, it starts a post-dialogue and then a cutscene to end the week. :(

**Comment by themushroom1** [comment]
i was also trying that too ;-;

**Comment by noskincz** [comment]
cant you just make the dialouge trigger after the song?
in the lua file?
