### ISSUE TITLE
post-dialogue before cutscene issue. please help

### ISSUE THREAD

**Issue by themushroom1** [ShadowMario/FNF-PsychEngine#9159]
### Describe your problem here.

So, I was making a mod and I'm trying to code to make the post-dialogue starts after the song and before the ending cutscene of the week, like this:

last song of the week > post dialog > cutscene > end week

Can someone help?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't, 'cause I don't wanna mess with the code to crash the entire mod.

**Comment by ShadowMario** [comment]
Send your code.
