### ISSUE TITLE
What are the steps of adding a note skin?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#916]
### What is your question?

What are the steps of adding a note skin?

**Comment by acap09** [comment]
just draw the notes and make it into an xml file. (p.s if you dont know how to, this [gamebanana tool](https://gamebanana.com/tools/download/7136) makes it easier)

**Comment by acap09** [comment]
for lua, put it in mods/images
for source, idk

**Comment by zwl1619** [comment]
@acap09 After  putting it in mods/images, how to use it?

**Comment by acap09** [comment]
> @acap09 After putting it in mods/images, how to use it?

@zwl1619 um maybe go to the chart editor of a song and then type in "[your-new-note-type]" in there. idk this part i havent tried yet

**Comment by monishrules** [comment]
1. get the png and xml go to mods/images and put it there.
2. if you want to have all the song in the mod to have it rename it to NOTE_assets and restart the game
3. if you want a single song to have it rename something other than that and go to chart editor of the song under the reload sav json section it says noteskin type and enter the name there
