### ISSUE TITLE
How do I swap the positions of the characters and their strumlines and icons from the beginning of a song.

### ISSUE THREAD

**Issue by CheesusSliced** [ShadowMario/FNF-PsychEngine#9160]
### Describe your problem here.

Hi. I'm making a spamton mod and I want to have bf and his icon and strumline on the left and spamton and his icon and strumline on the right, since thats the way you would face in deltarune if you were following the story. Heres an example: https://www.youtube.com/watch?v=ntIQxCxTP_g . I'd prefer to do this in lua if possible but if I have to do it in the actual source code then that works too. I don't want it to effect every song, just one.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by bruh1cat** [comment]
Make another character json of spamton and bf with spamton having "Playable character" checked and "Flip X" for bf. About the noteswap just give me a second.

**Comment by CheesusSliced** [comment]
What about the icons though

**Comment by bruh1cat** [comment]
[switch.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8954056/switch.zip)

**Comment by bruh1cat** [comment]
> What about the icons though

If you want I could flip.

**Comment by CheesusSliced** [comment]
> 

I can flip the x but I’m talking about having them switch sides

**Comment by bruh1cat** [comment]
be sure to put the script in the song folder, for example: mods/data/song-name

**Comment by CheesusSliced** [comment]
Alr thx

**Comment by bruh1cat** [comment]
Make another .json using the same characters and put them where the you want them to be.
