### ISSUE TITLE
Am I doing something wrong?

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#9161]
### Describe your problem here.

Why isn't this working

function onCreate()
    noteTweenX('defaultOpponentStrumX0', '0', -365, 0.1, 'linear')
    noteTweenX('defaultOpponentStrumX1', '1', -365, 0.1, 'linear')
    noteTweenX('defaultOpponentStrumX2', '2', -365, 0.1, 'linear')
    noteTweenX('defaultOpponentStrumX3', '3', -365, 0.1, 'linear')

    noteTweenX('defaultPlayerStrumX4', '4', 635, 0.1, 'linear')
    noteTweenX('defaultPlayerStrumX5', '5', 635, 0.1, 'linear')
    noteTweenX('defaultPlayerStrumX6', '6', 635, 0.1, 'linear')
    noteTweenX('defaultPlayerStrumX7', '7', 635, 0.1, 'linear')
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Second value should be an int
Also use setProperty instead

**Comment by bruh1cat** [comment]
is this how you use setProperty for moving notes? 
setProperty('defaultPlayerStrumX0', -365)

**Comment by frantastic24** [comment]
No
```lua
setPropertyFromGroup('strumLineNotes', StrumID, 'x', Xvalue)
```
