### ISSUE TITLE
Add this cool thing

### ISSUE THREAD

**Issue by bambitheone82112** [ShadowMario/FNF-PsychEngine#9162]
### What feature do you want to get added on the **base** engine?

hi, i just wanted to add psych engine a judgement counter and ms counter so pls, the zip name should be PsychEngine-Windows64JudgementMs

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by CrusherMods** [comment]
failed test

**Comment by bambitheone82112** [comment]
> failed test

lmao

**Comment by silvashp** [comment]
you failed the test

**Comment by Mastercopper2346** [comment]
@bambitheone82112 did you misclick or what?

Btw you still failed

**Comment by SrtHero278** [comment]
![image](https://user-images.githubusercontent.com/93018286/175753013-c3c5c2e4-1872-4bdb-abb5-494975a7c29a.png)
failed.
