### ISSUE TITLE
How do i change the app name

### ISSUE THREAD

**Issue by bambitheone82112** [ShadowMario/FNF-PsychEngine#9164]
### Describe your problem here.

so i wanted to change the app name on psych engine so i need a lua script for that
and how do
it be
named?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Bro. Stop doing this in lua selection

**Comment by CrusherMods** [comment]
```lua
function onCreate()
    setPropertyFromClass('openfl.Lib', 'application.window.title', "Friday Night Funkin': im gay");
end
```

**Comment by GabPortt** [comment]
I found this: https://www.youtube.com/watch?v=5dSdqehmlm8
Hope this helps!

**Comment by CrusherMods** [comment]
> I found this: https://www.youtube.com/watch?v=5dSdqehmlm8 Hope this helps!

he said in lua lmao

**Comment by bambitheone82112** [comment]
> ```lua
> function onCreate()
>     setPropertyFromClass('openfl.Lib', 'application.window.title', "Friday Night Funkin': im gay");
> end
> ```

what do i name

**Comment by CrusherMods** [comment]
> > ```lua
> > function onCreate()
> >     setPropertyFromClass('openfl.Lib', 'application.window.title', "Friday Night Funkin': im gay");
> > end
> > ```
> 
> what do i name

literally anything you want

**Comment by Mastercopper2346** [comment]
Ew in lua

**Comment by bambitheone82112** [comment]
> > > ```lua
> > > function onCreate()
> > >     setPropertyFromClass('openfl.Lib', 'application.window.title', "Friday Night Funkin': im gay");
> > > end
> > > ```
> > 
> > 
> > what do i name
> 
> literally anything you want

it wont work

**Comment by CrusherMods** [comment]
> > > > ```lua
> > > > function onCreate()
> > > >     setPropertyFromClass('openfl.Lib', 'application.window.title', "Friday Night Funkin': im gay");
> > > > end
> > > > ```
> > > 
> > > 
> > > what do i name
> > 
> > 
> > literally anything you want
> 
> it wont work

then you fucked up something cuz it works for me

or use onCreatePost

**Comment by BernardoGP4504** [comment]
> > > > > ```lua
> > > > > function onCreate()
> > > > >     setPropertyFromClass('openfl.Lib', 'application.window.title', "Friday Night Funkin': im gay");
> > > > > end
> > > > > ```
> > > > 
> > > > 
> > > > what do i name
> > > 
> > > 
> > > literally anything you want
> > 
> > 
> > it wont work
> 
> then you fucked up something cuz it works for me
> 
> or use onCreatePost

also tell people **it should be in mods/scripts**
