### ISSUE TITLE
Missing Document: Shaders.hx

### ISSUE THREAD

**Issue by bambitheone82112** [ShadowMario/FNF-PsychEngine#9165]
### What needs to be documented?

so the file, "shaders.hx" is not in source because modders cannot make fnf wavy bg for psych without soucre if they want to make a wavy bg. so if anyone else want to make a wavy bg, "shaders.hx" should be added! hope it will be added in the next update!

**Comment by Mastercopper2346** [comment]
Shaders we’re removed
