### ISSUE TITLE
Hold notes issue

### ISSUE THREAD

**Issue by Roselyn393** [ShadowMario/FNF-PsychEngine#9166]
### Describe your bug here.

After playing a video on CountdownTick and using the return functions hold notes fail to work properly and if too many exist the player cannot live

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Why are you doing it on countdown tick which isn't affected by Function_Stop

**Comment by Roselyn393** [comment]
i tried a bunch of stuff, i've tried onSongStart, onBeatHit, onStepHit, onUpdate, but it all results the same issues

**Comment by Mastercopper2346** [comment]
Then give us the script

**Comment by Roselyn393** [comment]
function onSongStart()
playVideo('Broadcasting')
end

**Comment by ShadowMario** [comment]
You have to start a video cutscene in onStartCountdown() and return Function_Stop, there's a script for running dialogues on the Lua Script API, you just have to run a video instead of dialogue there.
