### ISSUE TITLE
The same week appears twice in the story mode and in the freeplay.

### ISSUE THREAD

**Issue by GabPortt** [ShadowMario/FNF-PsychEngine#9172]
### Describe your bug here.

I'm porting a mod to the psych engine but when i created a custom week it apperars twice in the story mode and in the freeplay.
I really have no idea what i can do to fix this and i feel like i have tried everything i could do. PLs help me.

(sorry for the bad english :[ ).

### Command Prompt/Terminal logs (if existing)

Nothing.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Mastercopper2346** [comment]
Show files

**Comment by Lorekeeper49** [comment]
> Show files

I am unsure if we need them, he is basically stating that the same week is in 2 locations on the same screen
Though I have actually never seen this happen before, perhaps you might have 2 week files with different names (of course) but with the exact same contents

**Comment by GabPortt** [comment]
https://user-images.githubusercontent.com/101673478/175254371-7989e7ad-0681-44bb-ba4f-1e75e90cadec.mp4
![weekdup](https://user-images.githubusercontent.com/101673478/175255296-52fa732e-5fc3-46cf-a78c-965878800fa4.png)
The week i was talking about is "Rhythmrage".
I hope this helps.

**Comment by Lorekeeper49** [comment]
find weeks/weekList.txt and make sure the same week isn't listed twice, that may be what's causing it

**Comment by Setter-Function** [comment]
Check the 'weeks' file in the 'export' file. Maybe there are two same weeks in there.
Here's the file path.
export\release\windows\bin\assets\weeks (There may be some differences from yours)

**Comment by Setter-Function** [comment]
Check the 'weeks' folder in the 'export' folder. Maybe there are two same weeks in there.
Here's the file path.
export\release\windows\bin\assets\weeks (This might be some different from yours)
