### ISSUE TITLE
Change camera depending on who's turn it is

### ISSUE THREAD

**Issue by KalashniPepsi** [ShadowMario/FNF-PsychEngine#9173]
### Describe your problem here.

The opponent in my mod is alot larger than the average opponent so i was wondering if it would be possible to change the camera's zoom depending on who's turn it is.
(Preferably LUA but Source answers also work)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by frantastic24** [comment]
```lua
function onBeatHit()
     if curBeat % 4 == 0 then
          if not mustHitSection then
               setProperty('defaultCamZoom', opponentzoom)
          else
               setProperty('defaultCamZoom', bfzoom)
          end
     end
end
```

**Comment by KalashniPepsi** [comment]
How exactly am i supposed to use this? Adding the code with no changes just zooms the camera out infinitely and adding numbers does nothing.

**Comment by frantastic24** [comment]
You can close this then
