### ISSUE TITLE
Can I unpair Icons from the healthbar?

### ISSUE THREAD

**Issue by FA305** [ShadowMario/FNF-PsychEngine#9175]
### Describe your problem here.

I have been struggling to get the icons unpaired from the healthbar. And i actually did at one point! I used the "setObjectCamera" function to make the icons move with something else and not on the healthbar itself...however. The icons still wouldn't move via there "x" and would stay next to the healthbar. I have tried everything I can think of...please someone help.
![Screenshot (8)](https://user-images.githubusercontent.com/108034427/175168964-a11fcbc4-5b14-41e5-8ed3-dc569e7fd632.png)
Is there any way i can just delete the default icons and just create a new pair in between the notes (where botplay is)? Would they still react to low health?

Or can I make it to where the icons are stuck and dont move (bewteen the falling notes where "botplay" is) and just keep the original icons...?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
change the icons position through function onCreatePost
