### ISSUE TITLE
What does runGlobally do?

### ISSUE THREAD

**Issue by RowanSkie** [ShadowMario/FNF-PsychEngine#9176]
### What is your question?

So, I've noticed that in the latest commits, there's a boolean in pack.json on the default mods called runGlobally.

Is this the answer for #7002? What does it do?

```json
{
	"name": "Name",
	"description": "Description",
	"restart":false,
	"runGlobally": false,
	"color": [170, 0, 255]
}
```

**Comment by CrusherMods** [comment]
when its on it basically runs whatever is in the folder across all mods on psych
also the json is kinda fucked up
its supposed to be runsGlobally not runGlobally but that never got fixed so you have to rename

**Comment by RowanSkie** [comment]
Does it allow overwriting base Psych Engine assets too or just everything on the mods folder?

**Comment by CrusherMods** [comment]
> Does it allow overwriting base Psych Engine assets too or just everything on the mods folder?

base assets can also be overwritten too

**Comment by RowanSkie** [comment]
Ah, nice. I guess #7002 did get done after all.

**Comment by frantastic24** [comment]
It's been a feature for a long time now
