### ISSUE TITLE
Long notes are output shorter than I input in the game.

### ISSUE THREAD

**Issue by Setter-Function** [ShadowMario/FNF-PsychEngine#9178]
### Describe your bug here.

(Bad English)
In the chart editor, when I input long notes, save the file, and restart the game, they're output shorter than I input in the game.
For example, when I input a long note of length 3, it is output as length 2.
In the chart editor map, the lengths are as I input. But in-game shows different results...
How do I solve this problem? Does anyone experience this error, too?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

An error occurred while adding notes in the chart editor supported by the game.

**Comment by Mastercopper2346** [comment]
MOST likely not a bug. charting and in game is different.
Or its your zoom

**Comment by Setter-Function** [comment]
> MOST likely not a bug. charting and in game is different. Or its your zoom

OK, I thought there was a bug in the system because it was the same even if I installed the engine again.
Maybe there's a problem with my computer. Thank you for your answer.

**Comment by Lorekeeper49** [comment]
> > MOST likely not a bug. charting and in game is different. Or its your zoom
> 
> OK, I thought there was a bug in the system because it was the same even if I installed the engine again.
> Maybe there's a problem with my computer. Thank you for your answer.

It's not a problem with your computer, it happens to me too and this actually due to the BPM changing how sustain lengths add and subtract to match up with a single step

**Comment by Setter-Function** [comment]
> 

I see. Then what should I do?

**Comment by Setter-Function** [comment]
> > > MOST likely not a bug. charting and in game is different. Or its your zoom
> > 
> > 
> > OK, I thought there was a bug in the system because it was the same even if I installed the engine again.
> > Maybe there's a problem with my computer. Thank you for your answer.
> 
> It's not a problem with your computer, it happens to me too and this actually due to the BPM changing how sustain lengths add and subtract to match up with a single step

I see. Then what should I do?

**Comment by Paracosm-Daemon** [comment]
> > > > MOST likely not a bug. charting and in game is different. Or its your zoom
> > > 
> > > 
> > > OK, I thought there was a bug in the system because it was the same even if I installed the engine again.
> > > Maybe there's a problem with my computer. Thank you for your answer.
> > 
> > 
> > It's not a problem with your computer, it happens to me too and this actually due to the BPM changing how sustain lengths add and subtract to match up with a single step
> 
> I see. Then what should I do?

I do a weird workaround to this in my modified version of Psych Engine by using Math.round() instead of Math.floor() for the floorSus variable in PlayState.hx, line 2358.

Basically just replace that line with this:
```haxe
var floorSus:Int = Math.round(susLength);
```
It won't be perfect, but it'll be enough to have the length *kinda* match.

**Comment by Setter-Function** [comment]
> 

Ohh I tried the way you suggested and it really worked! Thank you so much for you and everyone.

**Comment by Setter-Function** [comment]
> > > > > MOST likely not a bug. charting and in game is different. Or its your zoom
> > > > 
> > > > 
> > > > OK, I thought there was a bug in the system because it was the same even if I installed the engine again.
> > > > Maybe there's a problem with my computer. Thank you for your answer.
> > > 
> > > 
> > > It's not a problem with your computer, it happens to me too and this actually due to the BPM changing how sustain lengths add and subtract to match up with a single step
> > 
> > 
> > I see. Then what should I do?
> 
> I do a weird workaround to this in my modified version of Psych Engine by using Math.round() instead of Math.floor() for the floorSus variable in PlayState.hx, line 2358.
> 
> Basically just replace that line with this:
> 
> ```hx
> var floorSus:Int = Math.round(susLength);
> ```
> 
> It won't be perfect, but it'll be enough to have the length _kinda_ match.

Ohh I tried the way you suggested and it really worked! Thank you so much for you and everyone.
