### ISSUE TITLE
Using cursor on main menu

### ISSUE THREAD

**Issue by Itsgithubfellow** [ShadowMario/FNF-PsychEngine#9179]
### What is your question?

I wanted to make it so you can use your mouse cursor instead of the directional buttons to click things on the main menu. How can I do this?

Coding using the psych engine 0.5.1 source code.

**Comment by Roselyn393** [comment]
u don't lmao

**Comment by Roselyn393** [comment]
i'm kidding, i have no fucking idea but try looking really hard through the internet, i'm sure someone has asked this question a million times before
