### ISSUE TITLE
Custom Note Help

### ISSUE THREAD

**Issue by Godofbacon1** [ShadowMario/FNF-PsychEngine#9180]
### Describe your problem here.

Hello So I want to make a new note for the game but if u miss the note u will gain health but if u press it u will die instatly i did the press part but the miss i didnt can anyone give me soulotion?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I just edited some i made that when u press the note u die instantly

**Comment by frantastic24** [comment]
```lua
function noteMiss(id, direction, type, sustain)

end
```

**Comment by Godofbacon1** [comment]
Thanks And Btw I putted the assets for the texture notes in mods>images and i putted the exact same name of the file but it didnt work can u help me
