### ISSUE TITLE
Windowed fullscreen

### ISSUE THREAD

**Issue by EgguMan** [ShadowMario/FNF-PsychEngine#9182]
### What feature do you want to get added on the **base** engine?

alt+enter does full screen, but it would be better if it was windowed fullscreen. So, say, I can click on my code and not have the game close.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
Pretty sure this is Haxe bullshit my guy
