### ISSUE TITLE
Rating text thing

### ISSUE THREAD

**Issue by GamingIQ** [ShadowMario/FNF-PsychEngine#9183]
### What feature do you want to get added on the **base** engine?

so like I asked how to add this in #9108 it's like when you get 100% Perfect!! i wanna change that text to like 100% AMONG US yeah

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by CrusherMods** [comment]
I'm pretty sure its possible
and you failed the test lmao

**Comment by GamingIQ** [comment]
how do you do it and what's the test?

**Comment by GamingIQ** [comment]
whops sorry 6k winning icons and stage editor

**Comment by Mastercopper2346** [comment]
Use the search function, u should find one

**Comment by ShadowMario** [comment]
My guy they literally already gave you the answer on the issue you linked

**Comment by hayfii** [comment]
Do you meant "GamingLowIQ"?

**Comment by hayfii** [comment]
Did you meant "GamingLowIQ"?
