### ISSUE TITLE
addLuaScript() works more like require

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#9186]
### What feature do you want to get added on the **base** engine?

If this isnt possible thats fine just dont harass me for it...

I've heard stuff going around that `require` is gonna get removed next update, so I have a workaround for it...
If a Lua script is loaded via `addLuaScript()` and it returns something then it shouldoutput that to `addLuaScript()`. From there it can be saved as a variable.

EXAMPLE:
```
--script 1 (the one to be loaded through addLuaScript())
local A = 69420
return A
```
```
--script 2 (the one loading script 1 through addLuaScript())
local modName -- whatever the path to script 1 is
local B = addLuaScript(ModName)
debugPrint(B) -- prints 69420
```

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
Isn't that what cd9d35f did

**Comment by tylerandari12** [comment]
> Isn't that what [cd9d35f](https://github.com/ShadowMario/FNF-PsychEngine/commit/cd9d35fa0b945f3029f4729ad095795bb8603fb3) did

I have no way to do merging stuff and its a huge pain to compile the source code...
But thats cool...

**Comment by frantastic24** [comment]
1) you don't need to merge anything
2) GitHub actions
3) why is this still open

**Comment by tylerandari12** [comment]
> 1) you don't need to merge anything
> 2) GitHub actions
> 3) why is this still open

What on earth is a GitHub action? (You don't need to answer)

**Comment by CrusherMods** [comment]
> > 1. you don't need to merge anything
> > 2. GitHub actions
> > 3. why is this still open
> 
> What on earth is a GitHub action? (You don't need to answer)

bruh
![image](https://user-images.githubusercontent.com/90648119/175625054-fc2a565b-82e5-4e27-a89e-d43d99bae3c8.png)
