### ISSUE TITLE
How to add a warning when you start the mod

### ISSUE THREAD

**Issue by Itsgithubfellow** [ShadowMario/FNF-PsychEngine#9187]
### What is your question?

My question is how to add a warning when you open the mod. So I am working on a mod and one of the songs has a lot of flashing lights and I want to have a warning when you start up the mod that tells the player that there will be flashing lights. I don't know how to do it. Also I use source code if you wanted to know. Pysch engine version 0.5.1

**Comment by Roselyn393** [comment]
https://github.com/mayo78/PSYCHDISCUSSIONS/discussions/60

**Comment by Itsgithubfellow** [comment]
Thanks!

**Comment by Mastercopper2346** [comment]
MAYO DELETED HIS DISCUSSIONS
