### ISSUE TITLE
How do you code custom dialogue boxes in Lua?

### ISSUE THREAD

**Issue by Lorekeeper49** [ShadowMario/FNF-PsychEngine#9188]
### What is your question?

this is for a mod I'm working on and the director said this: 'instead of doing portraits we'll be doing illustrations/panels for parts of the dialogue'

**Comment by hayfii** [comment]
Is the custom dialogue box for a song or the whole mod?

**Comment by Lorekeeper49** [comment]
It will be for certain songs

**Comment by Lorekeeper49** [comment]
> Is the custom dialogue box for a song or the whole mod?

It will be for certain songs

**Comment by hayfii** [comment]
> > Is the custom dialogue box for a song or the whole mod?
> 
> It will be for certain songs

Then it's not possible in lua

**Comment by Lorekeeper49** [comment]
> > > Is the custom dialogue box for a song or the whole mod?
> > 
> > It will be for certain songs
> 
> Then it's not possible.

Oh, well then

**Comment by NKTCurrect** [comment]
Use it, https://gamebanana.com/mods/384704
