### ISSUE TITLE
Is there a lua function that gets the total number of notes before the game starts?

### ISSUE THREAD

**Issue by RowanSkie** [ShadowMario/FNF-PsychEngine#9190]
### What is your question?

So, the context of the title question is that I basically want to create a new scoring system via Lua that makes it that the score is capped at 1 million.

I'm not yet *that* versed in Haxe's programming language, so no source editing at the moment.

So I figured that basically, I have to find a way to set the score based on what type of note hit, and how many notes there are to do so.

The former is a future me problem, which is why the question is for the latter.

**Comment by frantastic24** [comment]
Try `getProperty('unspawnNotes.length')`

**Comment by RowanSkie** [comment]
Huh, good to know. Is there any documentation about it I can read about that?

I've read this page of the wiki https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions and will `addScore()` work at least for the future me problem with the `getProperty('unspawnNotes.length')`? 

What I'm seeing in pseudo code right now is:

```
totalNotes = getProperty('unspawnNotes.length')
sickscore = 1000000/totalNotes
goodscore = (1000000/totalNotes) * 0.75
badscore = (1000000/totalNotes) * 0.65
shitscore = (1000000/totalNotes) * 0.50

if hit(sick) then:
   addScore(sickscore)
elseif hit(good) then:
   AddScore(goodscore)
elseif hit(bad) then:
   AddScore(badscore)
elseif hit(shit) then:
   AddScore(shitscore)
else:
   addScore(0)
```
