### ISSUE TITLE
website prevention

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#9191]
### Describe your problem here.

how to prevent people from playing on website
I want this on source because I don't think they will be able to change the source code ('they' is referring to the people who put the mods on a website)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just modded in the "example_mods" folder

**Comment by SrtHero278** [comment]
you can use if statements with build types.
```
#if html5
    //Code that stops them from playing
#else
    Usual code
#end
```

**Comment by TFLTV** [comment]
> on source, you can use if statements with build types.
> 
> ```
> #if html5
>     //Code that stops them from playing
> #else
>     //Usual code
> #end
> ```

do I have to put anything in the '//Usual code' spot (sorry noob at haxe)
