### ISSUE TITLE
move lua objects event

### ISSUE THREAD

**Issue by Maxenswel** [ShadowMario/FNF-PsychEngine#9192]
### Describe your problem here.

Is there an event that lets you move an object in a lua stage, similar to how the bus in Unloaded moves ?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by bruh1cat** [comment]
doTweenX(tag:String, vars:String, value:Dynamic, duration:Float, ease:String)

**Comment by bruh1cat** [comment]
Not sure about triggering it via an event, but you can paste this in stage.lua or a script just put this: doTweenX(tag:String, vars:String, value:Dynamic, duration:Float, ease:String)

**Comment by Maxenswel** [comment]
> Not sure about triggering it via an event, but you can paste this in stage.lua or a script just put this: doTweenX(tag:String, vars:String, value:Dynamic, duration:Float, ease:String)

Ok thank you ! I'll try it out
