### ISSUE TITLE
Screen randomly freezes yet you can still hear the game

### ISSUE THREAD

**Issue by mincraft0990** [ShadowMario/FNF-PsychEngine#9193]
### Describe your bug here.

This bug always happens for me (whether it is modified pe or not), but sometimes pe will randomly freeze the screen, you can still hear it, but the screen freezes. I've tried everything, minimizing, changing screen resolution, restarting, and I even tried reinstalling windows (I had to for something else), yet nothing works. Does anyone know how to fix this, or why it even happens?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Lorekeeper49** [comment]
It's lag due to your PC specs (no offense)

**Comment by mincraft0990** [comment]
> It's lag due to your PC specs (no offense)

Don't think it's because of that, I could be running a stable 240 fps and it can still happen

**Comment by mincraft0990** [comment]
I mean, I used psych engine on my phone and it never does that. Can't possibly be resources.

**Comment by NikolaPopbot5** [comment]
Is the engine trying to load other sprites like for example:
Tails switching to Xenophane or "left corner edd" in challeng-edd? If so It may be an issue due to the engine struggling to load external characters and read its XML data.

**Comment by mincraft0990** [comment]
Yeah, usually. Is there a way to fix this problem or is it a problem on my side?

**Comment by frantastic24** [comment]
That's your PC not being strong enough, you can somewhat reduce the spikes by precaching images though

**Comment by mincraft0990** [comment]
Ok, thanks for the information!
