### ISSUE TITLE
New window

### ISSUE THREAD

**Issue by gghj678910** [ShadowMario/FNF-PsychEngine#9195]
### Describe your problem here.

How to make new window and edit it settings like borderless, width, height, fullscreen?
Help please!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Very-very small changes

**Comment by ShadowMario** [comment]
Too advanced for me to tell you in a github issue.
