### ISSUE TITLE
How to change opponent icon with bf places

### ISSUE THREAD

**Issue by NavaGaming** [ShadowMario/FNF-PsychEngine#9198]
### Describe your problem here.

I want to make BF icon at the left side of the hp bar, would be pretty cool as event

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Lorekeeper49** [comment]
```
function onEvent(n, v1, v2)
    if n == 'your event' then
        local x1 = getProperty('iconP1.x')
        local y1 = getProperty('iconP1.y')
        local x2 = getProperty('iconP2.x')
        local y2 = getProperty('iconP2.y')
        setProperty('iconP2.x', x1)
        setProperty('iconP2.y', y1)
        setProperty('iconP1.x', x2)
        setProperty('iconP1.y', y2)
    end
end
```
don't know if this'll work but it's worth a shot

**Comment by NavaGaming** [comment]
> ```
> function onEvent(n, v1, v2)
>     if n == 'your event' then
>         local x1 = getProperty('iconP1.x')
>         local y1 = getProperty('iconP1.y')
>         local x2 = getProperty('iconP2.x')
>         local y2 = getProperty('iconP2.y')
>         setProperty('iconP2.x', x1)
>         setProperty('iconP2.y', y1)
>         setProperty('iconP1.x', x2)
>         setProperty('iconP1.y', y2)
>     end
> end
> ```
> 
> don't know if this'll work but it's worth a shot

K, u tried, but it not works
