### ISSUE TITLE
Expected

### ISSUE THREAD

**Issue by MegaMatt2712** [ShadowMario/FNF-PsychEngine#9199]
### Describe your problem here.

I was making a new event, and I get this error when I try to compile the game: source/editors/ChartingState.hx:94: characters 26-27 : Expected ]
<img width="527" alt="image" src="https://user-images.githubusercontent.com/104169313/175721172-28853823-f2bd-4d40-aeee-f1a85f6f530b.png">

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yep, ChartingState.hx and PlayState.hx

**Comment by CrusherMods** [comment]
your missing a **]** somewhere near line 94

**Comment by MegaMatt2712** [comment]
@CrusherMods No

**Comment by CrusherMods** [comment]
> @CrusherMods No

then you prob forgot to put a **,** at the end of the **]**

**Comment by MegaMatt2712** [comment]
> then you prob forgot to put a **,** at the end of the **]**

No

**Comment by SrtHero278** [comment]
Can we see line 94?

**Comment by Mastercopper2346** [comment]
GIVE US THE CODE

**Comment by Mastercopper2346** [comment]
What
