### ISSUE TITLE
Chart and song

### ISSUE THREAD

**Issue by Kaakskakwk** [ShadowMario/FNF-PsychEngine#920]
### Describe your problem here.

My song is stuck at 0:00 I already add the chart and the songs btw
![F806BEEF-7182-40C3-A808-F71FD5C5CC53](https://user-images.githubusercontent.com/71873309/140934771-96fe349f-7605-44c9-a256-5fea2d9bee58.jpeg)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

**Comment by monishrules** [comment]
if there is any space in the song names add "-" between them and in the json as well

**Comment by NotEpik** [comment]
i think it about song folder i think you use "mp3" files not "ogg" if you use "ogg" then i dont know now

**Comment by ShadowMario** [comment]
Your song Instrumental file couldn't be found in `mods/songs/your-song-name/Inst.ogg`
