### ISSUE TITLE
Cant compile anymore

### ISSUE THREAD

**Issue by Baneis556** [ShadowMario/FNF-PsychEngine#9200]
### Describe your problem here.

Hi, hxCodec error guy here(again), so, i tried to reinstall all the things(git,haxe and his librays) using this scrip.bat:https://drive.google.com/file/d/1JT3EE7dJk9MKNzr2-YbojiMwJ23Mh4L2/view(which is in the Friday Night Funkin' source code compilation tutorial) but... it only get the things worse, now i cant compile the default game, Seriously, i've tried several things, and nothing works, please help me, i don't know what to do anymore
![shit1](https://user-images.githubusercontent.com/88361915/175753027-276a244d-246a-4327-8ebc-c0a3c3281683.PNG)
![shit2](https://user-images.githubusercontent.com/88361915/175753029-8e2a1f1b-2c5a-433f-8829-5fb255629709.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by PogofruitKM** [comment]
You didn't install lime correctly. Follow ALL intructions given for Vanilla AND Psych Engine.

**Comment by Baneis556** [comment]
> 

Ya I just uninstalled everything and installed it again and now it's working. Thanks :)
