### ISSUE TITLE
character change event changes both characters in freeplay but not charting mode

### ISSUE THREAD

**Issue by tinoposts** [ShadowMario/FNF-PsychEngine#9201]
### Describe your bug here.

trying to make a triple trouble style song but when i change characters, it changes both characters in freeplay. but in charting mode, it only changes the opponent.

events.json
`{
	"song": {
		"speed": 3.2,
		"stage": "factory",
		"player1": "bf",
		"player2": "catty",
		"player3": null,
		"events": [
			[
				106746.575342466,
				[
					[
						"Change Character",
						"0",
						"bf"
					]
				]
			],
			[
				106849.315068493,
				[
					[
						"Change Character",
						"1",
						"penny"
					]
				]
			],
			[
				133047.94520548,
				[
					[
						"Change Character",
						"0",
						"bf"
					]
				]
			],
			[
				133150.684931507,
				[
					[
						"Change Character",
						"1",
						"viccell"
					]
				]
			],
			[
				238253.424657535,
				[
					[
						"Change Character",
						"0",
						"bf"
					]
				]
			],
			[
				238356.164383562,
				[
					[
						"Change Character",
						"1",
						"penny"
					]
				]
			],
			[
				290856.164383562,
				[
					[
						"Change Character",
						"0",
						"bf"
					]
				]
			],
			[
				290958.904109589,
				[
					[
						"Change Character",
						"1",
						"stove"
					]
				]
			],
			[
				406531.193266215,
				[
					[
						"Change Character",
						"0",
						"bf"
					]
				]
			],
			[
				406621.554711998,
				[
					[
						"Change Character",
						"1",
						"penny"
					]
				]
			]
		],
		"notes": [],
		"splashSkin": null,
		"validScore": false,
		"gfVersion": "gf",
		"bpm": 146,
		"arrowSkin": "",
		"needsVoices": true,
		"song": "triple trouble"
	}
}`

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by tinoposts** [comment]
![image](https://user-images.githubusercontent.com/46033418/175754734-4328cddb-9ffa-40bb-b6b5-07b8775d502f.png)
what am i doing wrong psych engine lords

**Comment by Lorekeeper49** [comment]
> ![image](https://user-images.githubusercontent.com/46033418/175754734-4328cddb-9ffa-40bb-b6b5-07b8775d502f.png)
> what am i doing wrong psych engine lords

Unsure what you're doing wrong but, why are the events that are literally one step apart from each other not combined into one event for organization's sake?

**Comment by tinoposts** [comment]
honestly i dont remember why i did that

guess i thought it would work if the events were separated instead of being together

**Comment by tinoposts** [comment]
don't know how it worked but i fixed the issue by putting the events in the chart's json instead of a separate json
