### ISSUE TITLE
The camera won't move.

### ISSUE THREAD

**Issue by Setter-Function** [ShadowMario/FNF-PsychEngine#9202]
### Describe your problem here.

Just like the title.
I'm making a custom week. The problem is that the camera has to move for each character's turn, but the screen is fixed.
Does anyone know why?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
must hit sections

**Comment by Setter-Function** [comment]
> must hit sections

Thank you! I just found out. Have a good day!
