### ISSUE TITLE
is there any reason why UI controls are tied to variabes?

### ISSUE THREAD

**Issue by Itz-Miles** [ShadowMario/FNF-PsychEngine#9203]
### What is your question?

I've been working with source, why are they tied to variables? I'm assuming I'm forgetting something obscure like substate persistence or gamepad support, so I came here.

example in PauseSubState.hx:
```
                var upP = controls.UI_UP_P;
		var downP = controls.UI_DOWN_P;
		var accepted = controls.ACCEPT;

		if (upP)
		{
			changeSelection(-1);
		}
		if (downP)
		{
			changeSelection(1);
		}
```

**Comment by BeastlyGhost** [comment]
no reason at all, this is base game stuff that doesn't really need to be changed, you can either just do `if (controls.UI_UP_P)` or ties those to variables

**Comment by ShadowMario** [comment]
Shortening, nothing big.
