### ISSUE TITLE
hey hi hello wassup

### ISSUE THREAD

**Issue by Steve35117** [ShadowMario/FNF-PsychEngine#9204]
### Describe your problem here.

so im creating a mod where if the opponent presses as example the left note, an animation will play and if it presses the right note, another animation plays. it doesnt work lolz. can you help me?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Flop

**Comment by noskincz** [comment]
how about the xml or the json files?

**Comment by Steve35117** [comment]
bye beatays i forgor i putted this in another path lolzzzzz
