### ISSUE TITLE
Game is stuck at 60 FPS and slows down if the FPS cap is turned up

### ISSUE THREAD

**Issue by LucilleExtri** [ShadowMario/FNF-PsychEngine#9206]
### Describe your bug here.

Recently ive been experiencing PycheEngine randomly being capped at 60 FPS by force and slowing down in speed when the FPS cap is higher

It isnt lag as the game returns to normal speed after playing a song, still capped at 60 FPS
The FPS counter is also red
![image_2022-06-25_164507026](https://user-images.githubusercontent.com/108197643/175790002-b50cf48f-36b1-4f6b-b22e-cf4e6a7fd437.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
If you have external software forcing vsync on, disable it

**Comment by Mastercopper2346** [comment]
Or your pc has been running to long

**Comment by LucilleExtri** [comment]
> If you have external software forcing vsync on, disable it Or lower your fps cap

Is this it?
![image_2022-06-25_212843558](https://user-images.githubusercontent.com/108197643/175795580-4afec5e2-4652-425e-a693-eccd406d6f9e.png)

**Comment by LucilleExtri** [comment]
> Or your pc has been running to long

I always turn it off after not using it

**Comment by frantastic24** [comment]
Yes that's the option, you should be able to disable it just for this game

**Comment by LucilleExtri** [comment]
> Yes that's the option, you should be able to disable it just for this game

It worked, thanks!

**Comment by frantastic24** [comment]
Don't forget to close this

**Comment by LucilleExtri** [comment]
woops, alright thanks man
