### ISSUE TITLE
Events in LUA

### ISSUE THREAD

**Issue by JdogGamezYT** [ShadowMario/FNF-PsychEngine#9209]
### Describe your problem here.

So either I'm stupid or it's broken, I'm trying to use the triggerevent line in LUA, and the event always just seems to either not work or break. Am I doing something wrong?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Can't tell if it's wrong or not if you don't show what you did

**Comment by JdogGamezYT** [comment]
[lua.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/8985663/lua.zip)
Here is the custom event (zoom.lua and zoom.txt) and the lua script (camzoom.lua). Basically, I want the camera to zoom when it focuses on the opponent, and the lua script just deosn't trigger the events.

**Comment by frantastic24** [comment]
Why are you calling an event in the first place, you can just use setProperty directly (and preferably under `onBeatHit()` or `onSectionHit()`)

**Comment by JdogGamezYT** [comment]
I'm really bad with LUA, I should look at the wiki.
