### ISSUE TITLE
Game Crashes within entering any song

### ISSUE THREAD

**Issue by randomaccount20** [ShadowMario/FNF-PsychEngine#9210]
### Describe your bug here.

I recently downloaded 0.6.0 ver and switched all my mods to it, i started to play the game and my songs i have in the engine, but suddenly, when i tried to play ugh, tried to go to chart editor to test the events, and tried to play tutorial, it crashed. Is there any solution to this problem?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only switched all my stuff i have in the previous ver to the ver that i recently installed.

**Comment by Mastercopper2346** [comment]
There’s no 0.6.0-

**Comment by randomaccount20** [comment]
![imagen](https://user-images.githubusercontent.com/91567975/175794146-9a0912cf-ad9c-4e1c-bcca-a98e4cd55647.png)
bottom left

**Comment by randomaccount20** [comment]
![imagen](https://user-images.githubusercontent.com/91567975/175794163-e5be12ca-76f1-4b19-b363-014a6743e873.png)
bottom left of psych engine

**Comment by Mastercopper2346** [comment]
WHAT

**Comment by CrusherMods** [comment]
> There’s no 0.6.0-

yes there is 💀 
maybe read releases
