### ISSUE TITLE
I need a lot of help with a new menu

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#9212]
### Describe your problem here.

So im trying to make a custom menu that displays Fan Art for the mod fi anyone makes any and i need help with how to make a custom menu to do this the way im gonna do it is it will be displayed in a frame but now i dont know how i would make this work

i just need the basic load images stuff, Image positions, PRELOADING and then ill be good

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

A LOT OF SOURCE STUFF

**Comment by machonessiebaby** [comment]
sorry i have been dead on github for a while trying to figure out how to  do this

**Comment by Mastercopper2346** [comment]
Is ok

**Comment by Mastercopper2346** [comment]
I can help

**Comment by machonessiebaby** [comment]
> I can help

Thank you
