### ISSUE TITLE
chart slows down

### ISSUE THREAD

**Issue by coolaydang** [ShadowMario/FNF-PsychEngine#9214]
### Describe your bug here.

for some reason my chart slows down and I have no idea what's causing it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited MainMenuState.hx but removed the code that I added

**Comment by Mastercopper2346** [comment]
Check your gameplay changers menu

**Comment by coolaydang** [comment]
thx

**Comment by ShadowMario** [comment]
Close the fucking issue
