### ISSUE TITLE
Problem with the "Philly Glow" event

### ISSUE THREAD

**Issue by DaRealMrRainbow** [ShadowMario/FNF-PsychEngine#9215]
### Describe your bug here.

So whenever I tried to use the event in psych engine, it crashed with this message:

### Command Prompt/Terminal logs (if existing)

```bash
editors/ChartingState.hx (line 1452)
flixel/addons/ui/FlxUI.hx (line 164)
flixel/addons/ui/FlxUIInputText.hx (line 46)
flixel/addons/ui/FlxInputText.hx (line 466)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I am using the engine for my own mod without source code.

**Comment by frantastic24** [comment]
It's not meant to be used outside of the pico stage

**Comment by CrusherMods** [comment]
its not to be used on any other stage I thought this was literally easy to notice 😭

**Comment by ShadowMario** [comment]
This event is purposely hardcoded to Week 3.
