### ISSUE TITLE
Crash on Psych engine

### ISSUE THREAD

**Issue by TobyanimationsStudios** [ShadowMario/FNF-PsychEngine#9217]
### Describe your problem here.

i updated my engine and i was making my mods and the engine CRASHES
there's the crashes logs
==================================================
CRASH #1
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 105)
FreeplayState.hx (line 370)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/calling-me/calling-me-normal.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
========================================================}
CRASH #2

C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
editors/ChartingState.hx (line 2452)
editors/ChartingState.hx (line 2417)
editors/ChartingState.hx (line 2412)
editors/ChartingState.hx (line 2391)
editors/ChartingState.hx (line 1890)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/characters/bf.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i dont edited nothing

**Comment by Mastercopper2346** [comment]
It literally says you don’t have bf.json and don’t have calling-me normal.json

**Comment by PogofruitKM** [comment]
```calling-me-normal``` should appear as just ```calling-me```
And well, reinstall Haxe and try again.
