### ISSUE TITLE
QUANTIZE CHARTING BUG

### ISSUE THREAD

**Issue by bbpanzu** [ShadowMario/FNF-PsychEngine#9218]
### Describe your bug here.

The quantization in the charting menu fucks up depending on your Note Offset settings. here's a fix for the ChartingState.hx. very important as i am a vortex editor main

```
	override function updateCurStep():Void 
	{
		
		var lastChange = Conductor.getBPMFromSeconds(Conductor.songPosition);

		var shit = ((Conductor.songPosition ) - lastChange.songTime) / lastChange.stepCrochet;
		curDecStep = lastChange.stepTime + shit;
		curStep = lastChange.stepTime + Math.floor(shit);
	}
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i gave it a cute tophat :3

**Comment by Mastercopper2346** [comment]
BBPANZU BACK ON PSYCH ENGINE!!??

**Comment by ShadowMario** [comment]
Fixed on Kade's PR

**Comment by bbpanzu** [comment]
nah it's not i checked
https://files.catbox.moe/co8gf1.mp4
here's me pressing down on vortex mode with my note offset at 250
