### ISSUE TITLE
Cant compile source because of funkin lua

### ISSUE THREAD

**Issue by CodyGGaT** [ShadowMario/FNF-PsychEngine#9219]
### Describe your bug here.

funkin lua is giving me problems compiling the source

### Command Prompt/Terminal logs (if existing)

```bash
source/FunkinLua.hx:333: lines 333-337 : Int should be Bool
source/FunkinLua.hx:333: lines 333-337 : ... For function argument 'f'
source/FunkinLua.hx:439: lines 439-442 : Int should be Bool
source/FunkinLua.hx:439: lines 439-442 : ... For function argument 'f'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by TheKitBoi** [comment]
Use this
haxelib git linc_luajit https://github.com/nebulazorua/linc_luaji

**Comment by CodyGGaT** [comment]
theres nothing there

**Comment by frantastic24** [comment]
Run that in your command line, this isn't a bug you just didn't install the new luajit

**Comment by CodyGGaT** [comment]
then why is there nothing on the page

**Comment by frantastic24** [comment]
If you read it you'll notice it's missing a `t` at the end, this is also the same link that's on the readme

**Comment by CodyGGaT** [comment]
yea now it says "You already have linc_luajit version git installed.
Updating linc_luajit version git ..."

**Comment by CodyGGaT** [comment]
its doing nothing

**Comment by frantastic24** [comment]
Uninstall any luajit you have and install the new one I guess
Either way this isn't a bug

**Comment by CodyGGaT** [comment]
i already figured it out
