### ISSUE TITLE
charting problem

### ISSUE THREAD

**Issue by dimuzicle** [ShadowMario/FNF-PsychEngine#922]
### Describe your bug here.

when I try to chart song with 4x or 8x speed there is some delay in notes

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
Not the charter's fault, it's either your song or if you're using wireless earphones they might be laggy.
