### ISSUE TITLE
This is my first time getting this error message and idk how to fix

### ISSUE THREAD

**Issue by Begyosh** [ShadowMario/FNF-PsychEngine#9220]
### Describe your problem here.

![![8E4AAE07-0BE2-44DD-95E4-EB3C91BE8283](https://user-images.githubusercontent.com/108202285/175795250-24fb7e68-fb57-4a2a-bce5-4207b7eeca50.jpeg)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I added the holy note from the vs mami mod and whenever I try to use it I get this message

**Comment by Mastercopper2346** [comment]
Th Is going on? 2nd message in one day

**Comment by noskincz** [comment]
its saying that the object (holy note) is non readable or something idk
