### ISSUE TITLE
Pico Speaker Crash

### ISSUE THREAD

**Issue by Bupisreal** [ShadowMario/FNF-PsychEngine#9221]
### Describe your bug here.

When I went into the character editor bc I wanted to check out the week 7 characters, and when I clicked on the Pico Speaker character in the list, and error popped up and the game crashed

[PsychEngine_2022-06-25_21'09'57.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8985807/PsychEngine_2022-06-25_21.09.57.txt)

### Command Prompt/Terminal logs (if existing)

```bash
idk
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Mastercopper2346** [comment]
Missing pico speaker in characters I believe
