### ISSUE TITLE
Crash in Chart Editor

### ISSUE THREAD

**Issue by Traxing** [ShadowMario/FNF-PsychEngine#9222]
### Describe your bug here.

I was just getting my charts made to how I like them. I was getting ready to play my new Dadbattle, but then I got this error message. ( btw it told me to put this here and let me know if the text file is not visible).

[PsychEngine_2022-06-25_19'36'43.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8985827/PsychEngine_2022-06-25_19.36.43.txt)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I just changed scroll speed or song speed.

**Comment by Roselyn393** [comment]
it was maybe a test for the crash handler that they just added, try redownloading it again cause at that time the source might've been for a purpose

**Comment by Mastercopper2346** [comment]
IT SAYS MISSING dadbattle.json

**Comment by bambitheone82112** [comment]
is it have a script to block it?
