### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by VeritonR** [ShadowMario/FNF-PsychEngine#9223]
### Describe your bug here.

When trying to play the mod "Vs Sonic.exe Encore" in the engine version "0.6" the game crashes
This bug did not occur in version "0.5.2h"
![bug](https://user-images.githubusercontent.com/67881127/175796786-2f053526-229a-44ab-a3b6-7d90321ab931.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
Try again in 0.6.1
Close the issue if the problem was solved.
