### ISSUE TITLE
I literally can't run the engine on my PC

### ISSUE THREAD

**Issue by Zyanes** [ShadowMario/FNF-PsychEngine#9224]
### Describe your bug here.

I just downloaded the 0.6 update but the game doesn't even open, my cursor just shows the loading sign for a brief moment but nothing really happens.

### Are you modding a build from source or with Lua?

Not modding a build at all, i'm using vanilla PE.

### What is your build target?

Windows 10 x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Bissthefreak** [comment]
Me too.

**Comment by ShadowMario** [comment]
Try again in 0.6.1
