### ISSUE TITLE
FunkinLua.hx Bug preventing me from Compiling my Psych Engine Build.

### ISSUE THREAD

**Issue by AverageHeli** [ShadowMario/FNF-PsychEngine#9225]
### Describe your bug here.

The newest Psych Engine build is.. Well very buggy for me when it comes to compiling. 

Whenever I try compiling my build, the Terminal log states

" source/FunkinLua.hx:333: lines 333-337 : Int should be Bool "
" source/FunkinLua.hx:333: lines 333-337 : ... For function argument 'f' "

Now, I have already tried to resolve this issue using the linc_luajit  strategy, but now it is stuck loading and keeps on saying

" Updating linc_luajit version git ... " 

and never finishes loading. If anyone knows a solution to this problem, please help!

### Command Prompt/Terminal logs (if existing)

```bash
source/FunkinLua.hx:333: lines 333-337 : Int should be Bool
source/FunkinLua.hx:333: lines 333-337 : ... For function argument 'f'
source/FunkinLua.hx:439: lines 439-442 : Int should be Bool
source/FunkinLua.hx:439: lines 439-442 : ... For function argument 'f'

You already have linc_luajit version git installed.
Updating linc_luajit version git ...
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

The only thing I've done is add stages in Playstate.hx, add different named ratings, and added stuff in modding.

**Comment by Playertrip777** [comment]
Do `haxelib remove linc_luajit`, then reinstall it again.
