### ISSUE TITLE
Game crashes barely just opening it

### ISSUE THREAD

**Issue by MijaeLio** [ShadowMario/FNF-PsychEngine#9227]
### Describe your bug here.

I think the title says it all, it's the first time this has happened to me and I have no idea how to solve it, in previous versions this didn't happen to me (also sorry for the image being spanish, but the point is on the error: "0xc000007b").

If anyone knows how to fix it, please tell me, thank you very much.

![image](https://user-images.githubusercontent.com/87155057/175798617-da5a95f7-97b0-4e59-b9e4-e5c47b600215.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited Playstate (to add stages) and ClientPrefs (add options), just to port a mod I was working on Psych 0.5.1 but I don't think that what I have done has affected the game in this way

**Comment by Mastercopper2346** [comment]
Did you go to options to ADD the option?

**Comment by MijaeLio** [comment]
> Did you go to options to ADD the option?

Yeah, and if I hadn't, it wouldn't even have affected the game

**Comment by Mastercopper2346** [comment]
Did you do anything with options.hx

**Comment by MijaeLio** [comment]
> Did you do anything with options.hx

Yeah, but just to add a option substate for my mod's options

**Comment by Mastercopper2346** [comment]
You can add it in a certain substate
