### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by blowers69** [ShadowMario/FNF-PsychEngine#9228]
### Describe your problem here.

So, when I compiled the source code for 0.6, this error showed up.
![source](https://user-images.githubusercontent.com/90225757/175798828-e2d13135-63bc-4b5a-8dff-c5c2fbe604d1.png)

Does anyone know how to fix this error?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by machonessiebaby** [comment]
did u install everything needed?

**Comment by blowers69** [comment]
I don’t know can you tell me what to install

**Comment by blowers69** [comment]
nvm I fixed it
