### ISSUE TITLE
Character Editor extra stuff

### ISSUE THREAD

**Issue by Lost-Daemon** [ShadowMario/FNF-PsychEngine#9229]
### What feature do you want to get added on the **base** engine?

Add player offsets for the character editor (that only take effect when the character is in the player position) and a checkbox that when checked, it will switch singLEFT and singRIGHT anims when they are selected as player. It's much more efficient than making duplicates of a character and wasting space.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by NavaGaming** [comment]
We NEED Stage Editor Really badly.

**Comment by Lost-Daemon** [comment]
Stage editor is not being requested, shadowmario already stated that he will make it later. Also that's not what the request is about.
