### ISSUE TITLE
Game Crashes while playing

### ISSUE THREAD

**Issue by AlexTheCat15** [ShadowMario/FNF-PsychEngine#9231]
### Describe your bug here.

Recently downloaded v0.6.0, and when I ported all my mods and started playing, it froze, the music stopped playing, then I heard like 3 seconds of the song and then it crashed. So... help?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not yet because I don't know how to lmao

**Comment by frantastic24** [comment]
Memory leak that just now got fixed in source

**Comment by AlexTheCat15** [comment]
> Memory leak that just now got fixed in source

And is the Null Object Reference also fixed?

**Comment by frantastic24** [comment]
I haven't seen that error myself yet so I don't know
