### ISSUE TITLE
i don't know whats happening

### ISSUE THREAD

**Issue by todybox** [ShadowMario/FNF-PsychEngine#9234]
### Describe your problem here.

![report](https://user-images.githubusercontent.com/96970552/175800658-64d31150-5042-4154-9324-2c532e57f59f.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i add DynamicShaderHandler.hx Shader.hx ShaderSprite.hx, and changed some funkinlua.hx

**Comment by Daggerman090** [comment]
same thing popped up for me
