### ISSUE TITLE
Compiling source code of 0.6

### ISSUE THREAD

**Issue by ModdedFNF** [ShadowMario/FNF-PsychEngine#9235]
### Describe your bug here.

when I try compiling the game, it puts an error of the FunkinLua.hx file, with the error:

source/FunkinLua.hx:2706: characters 7-35 : Int should be Bool

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't edit anything, i just compile first the source without edits before code my shit

**Comment by BeastlyGhost** [comment]
open up your command prompt and type these
`haxelib install hxCodec`
`haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit`

then compile

**Comment by ModdedFNF** [comment]
Thank you, it now works perfectly

**Comment by ModdedFNF** [comment]
Closed cuz resolved
