### ISSUE TITLE
Character Editor Bug

### ISSUE THREAD

**Issue by MOON-on-GitHub** [ShadowMario/FNF-PsychEngine#9239]
### Describe your bug here.

![Psych Engine Error](https://user-images.githubusercontent.com/106433334/175807905-f004efaf-c3d5-4557-8950-29e04ccb3b07.png)
If I try to load pico-speaker on Character Editor, It crashes.

### Command Prompt/Terminal logs (if existing)

```bash
Character.hx [line 373]
Character.hx [line 252]
editors/CharacterEditorState.hx [line 925]
editors/CharacterEditorState.hx [line 434]
FIxUIDropDownMenuCustom.jx [line 500]
FIxUIDropDownMenuCustom.jx [line 361]
flixel/ui/FIxButton.hx [line 521]
openfl/events/EventDispatcher.hx [line 402]
openfl/display/DisplayObject.hx [line 1399]

Uncaught Error: Null Object Reference
Please report this error to the GitHub page:
https://github.com/ShadowMario/FNF-PsychEngine
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't edit anything

**Comment by ShadowMario** [comment]
You have to open it while in Stress.
