### ISSUE TITLE
Note Tween Direction

### ISSUE THREAD

**Issue by FNaS2ToySonic** [ShadowMario/FNF-PsychEngine#9240]
### What needs to be documented?

I was looking in FunkinLua.hx, and i found
noteTweenDirection("TweenName", "NoteId", "Value", "Lenght", "EasingType")

so why to not add it in the wiki?

Note 1: default direction value is 90
Note 2: you cant type something like "defaultOpponentStrumDirection0 + 16" its not working, because default"Player/Opponent"StrumDirection"NoteId" doesnt exists

**Comment by machonessiebaby** [comment]
this is cool but incredibly buggy
