### ISSUE TITLE
Cutscene Desync

### ISSUE THREAD

**Issue by AdmiralUsername** [ShadowMario/FNF-PsychEngine#9241]
### Describe your bug here.

During Tankman's cutscenes, the video and audio desync due to lag, sometimes resulting in the audio playing before or after the video does.

P.S: The bug report forces you to select what you are modding from, I am not modding with Lua or Source. This is just the default build.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by machonessiebaby** [comment]
they did this cutscene in a weird way it plays an audio over an xml and sprite sheet file playing so tankmans pos will jump too
