### ISSUE TITLE
FunkinLua Error

### ISSUE THREAD

**Issue by Knuxy03** [ShadowMario/FNF-PsychEngine#9242]
### Describe your bug here.

When i was compiling the source, This error happens

### Command Prompt/Terminal logs (if existing)

```bash
source/FunkinLua.hx:2706: characters 7-35 : Int should be Bool
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by BombasticTom** [comment]
you gave an integer value to a bool variable

**Comment by kingyomoma** [comment]
they didnt edit anything in the build
run haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit in your command prompt/powershell

**Comment by BombasticTom** [comment]
oh
