### ISSUE TITLE
Sudden lag spikes that didn't happen on previous versions

### ISSUE THREAD

**Issue by ManMaster707** [ShadowMario/FNF-PsychEngine#9244]
### Describe your bug here.

Sadly I can't show proof for now, but bear with me.

While playing a level, the game, every once in a while, just freezes the screen and the inputs for a second, causing annoying lag spikes that make you miss the notes.
I'm on 0.6, but it didn't happen on previous versions, so it's not my pc's fault, and it happens on every song, from the tutorial to mods.

### Command Prompt/Terminal logs (if existing)

```bash
Nothing.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i just added things trough the "mods" folder.

**Comment by machonessiebaby** [comment]
i have 2 reasons
1: your LUA files are using a lot of memory
2: your pc sucks

**Comment by ManMaster707** [comment]
> i have 2 reasons
1: your LUA files are using a lot of memory
2: your pc sucks

I've already said that the lag didn't happen on previous versions, so it's not the pc's fault, and the lag happened even when the mods folder was empty.

**Comment by KatoriAnh553** [comment]
0.6.0 sucks at handling laggy stuff

**Comment by GreenWolf123** [comment]
This is specifically why I switched out of Kade, and now it's followed me here.

**Comment by ohyeah388** [comment]
having this problem too, memory usage is only around 500mb, (on previous versions my pc can handle 800+mb before dipping framerates). This is definitely a new version bug

**Comment by Lethrial** [comment]
I get the exact same issues on PE 0.6.0 and the other engines/mods you guys are describing. Recorded a video of me playing through Bopeebo with the lag spikes, and they cause some really harsh misses. (Build is fully vanilla, I have a few Lua mods installed but they shouldn't be interfering here) https://streamable.com/elfjip

**Comment by Traxing** [comment]
I am also having this problem. My laptop could easily run some pretty good mods on 0.5.2h, but now I'm suddenly getting lag spikes with 0.6.0. Really hope they come out with a patch or something to fix this.

**Comment by ShadowMario** [comment]
Try again in 0.6.1
Close the issue if the problem was solved.

**Comment by ManMaster707** [comment]
> Try again in 0.6.1
Close the issue if the problem was solved.

I updated to 0.6.1, and now the lag seems shortened to a few milliseconds, without interrupting gameplay, thank you @ShadowMario!
