### ISSUE TITLE
the game crashes when loading a song

### ISSUE THREAD

**Issue by RayZxyo** [ShadowMario/FNF-PsychEngine#9245]
### What is your question?

C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 105)
FreeplayState.hx (line 370)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/you-cant-run-remix/you-cant-run-remix-hard.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

**Comment by tensichan83** [comment]
I had a similar bug that brought me down too!
In my case, it fell out with the below.
`PANIC: unprotected error in call to Lua API (attempt to call a nil value)`

**Comment by BeastlyGhost** [comment]
you song file doesn't exist, look at the line after "Uncaught Error", it references a file that was not found
