### ISSUE TITLE
Turn a int into a bool

### ISSUE THREAD

**Issue by suskas** [ShadowMario/FNF-PsychEngine#9246]
### Describe your bug here.

so i downloaded the latest update of the engine and i got an error that and int should be a bool
![e](https://user-images.githubusercontent.com/95119042/175813516-5eaf9eef-9676-402b-92f6-f173357edc0f.png)
![Screenshot 2022-06-26 135757](https://user-images.githubusercontent.com/95119042/175813523-19260d9d-b0d6-48f9-ae94-31bf2dca6989.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

.

**Comment by tensichan83** [comment]
This problem can be solved by editing the file "FunkinLua.hx".
Go to the problematic line 2706 and change the "1" to "false" and you can now build!
![image](https://user-images.githubusercontent.com/93047573/175814412-cd836caa-a95c-47fb-a4f0-73877f6abd54.png)

**Comment by suskas** [comment]
thank you so much now i can compile thx!!!
