### ISSUE TITLE
I'm getting quite a few crashes

### ISSUE THREAD

**Issue by OcelotZombie** [ShadowMario/FNF-PsychEngine#9248]
### Describe your bug here.

So here's the scene, I'm just having a nice day doing some charting when I decide to add an event because yes. Now in the last update I was able to do this very easily without crashes but....with a new update comes new crashes. So I add the event and go to type in my variables when bam, game crashes. I really have no idea but I'm attaching the crashes I got for charting.
[PsychEngine_2022-06-26_07'06'11.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8986620/PsychEngine_2022-06-26_07.06.11.txt)
[PsychEngine_2022-06-26_07'20'59.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8986621/PsychEngine_2022-06-26_07.20.59.txt)
[PsychEngine_2022-06-26_07'31'34.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/8986622/PsychEngine_2022-06-26_07.31.34.txt)
(I hope the text file work).

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I did add in sprites and songs to the Mods folder as all creators do

**Comment by ManMaster707** [comment]
If that event you put was the 'Philly Lights' event, it's intended to only work in week 3.

If that event was another, then idk.
