### ISSUE TITLE
i dont understand

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#9249]
### Describe your bug here.

so idk why but during hold notes or some songs the notes or tail pieces will disappear and not count to misses and then they make the scroll sound i prob fucked up playstate when i was fixing an error (will get vid in a bit)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

A LOT OF SOURCE STUFF

**Comment by ShadowMario** [comment]
You definitely fucked PlayState, i can't help with that

**Comment by machonessiebaby** [comment]
> You definitely fucked PlayState, i can't help with that

damn i just updated when they added the better achievements and i reverted playstate weird

**Comment by machonessiebaby** [comment]
> You definitely fucked PlayState, i can't help with that

cuz when i reverted it it still did it i think nit may or may not be a lua script but ill check it out
