### ISSUE TITLE
Crashing near the end of a song.

### ISSUE THREAD

**Issue by Jaldabo** [ShadowMario/FNF-PsychEngine#9250]
### Describe your bug here.

Game crashes near the end of a song on certain tracks. Happens every time most notably with Ballistic on any difficulty. Base game is fine, so I assume it is a luasprite issue. If I can provide more information in any way, please let me know.

https://user-images.githubusercontent.com/104400900/175815560-27ba7c5a-693f-4d97-8b18-1c031445d9c1.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

 The build is unmodified and no source code was touched.

**Comment by ShadowMario** [comment]
Try again in 0.6.1
Close the issue if the problem was solved.
