### ISSUE TITLE
Lag Spikes

### ISSUE THREAD

**Issue by AdmiralUsername** [ShadowMario/FNF-PsychEngine#9251]
### Describe your bug here.

During songs the game will lag for a split second but for no reason. Causing you to miss notes when you did press keys. Doesn't happen on 0.5.2h. Really annoying to happen on a RHYTHM GAME.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't touch anything, I wasn't modding. New build. Game just lags.

**Comment by ManMaster707** [comment]
This seems to happen to me, you and @ZeitHeld, so it isn't a personal issue, that's the best I can tell you about this.
