### ISSUE TITLE
game crash on 0.6.0

### ISSUE THREAD

**Issue by Cross-Blackwood** [ShadowMario/FNF-PsychEngine#9252]
### Describe your bug here.

I'm playing this on a toaster and i choosed to play the song "blammed" then it was laggy so i did go to the charting change the background so it would lag less then i got an error screen
![psych crashed](https://user-images.githubusercontent.com/108225122/175816879-3124a078-e9fe-405f-958c-9b10b73bd67b.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i didn't edited anything i just downloaded it and then played

**Comment by machonessiebaby** [comment]
the background is a required thing there is a new even hardcoded to week 3 any other bg will break the even resulting in this error

**Comment by ShadowMario** [comment]
Philly Glow crashes on any other stages, it's locked to stage Philly.
