### ISSUE TITLE
I get a bug while loading a song!（ソングの読み込み中にバグが起きます！）

### ISSUE THREAD

**Issue by tensichan83** [ShadowMario/FNF-PsychEngine#9253]
### Describe your bug here.

While running the "lime test windows" command, I tried to play a song in story mode, free play, and it crashed with something like the image below appearing in the command prompt.
（「lime test windows」コマンドを実行中に、ストーリーモード、フリープレイで曲を再生しようとしたら、コマンドプロンプトに下の画像のようなものが表示され、クラッシュしてしまいました。）
![image](https://user-images.githubusercontent.com/93047573/175818440-d8228b3a-61ed-4d46-9a4f-988966f76e6f.png)

The exported files are experiencing the same symptoms. How can I improve it?
Please help!
（エクスポートされたファイルも同様の症状が起きています。どのようにすれば改善しますか？助けてください！）

### Command Prompt/Terminal logs (if existing)

```bash
source/Discord.hx:18: Discord Client starting...
source/Discord.hx:68: Discord Client initialized
source/Discord.hx:25: Discord Client started.
source/FreeplayState.hx:368: dad-battle
source/FreeplayState.hx:374: CURRENT WEEK: week1
source/LoadingState.hx:162: Setting asset folder to shared
source/Conductor.hx:135: new BPM map BUDDY []
source/FunkinLua.hx:87: lua file loaded succesfully:mods/scripts/ScoreTxt colour.lua
PANIC: unprotected error in call to Lua API (attempt to call a nil value)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited various hx files and converted them to Japanese.

**Comment by ShadowMario** [comment]
Could you show have you edited? And how maybe send ScoreTxt colour.lua too

**Comment by tensichan83** [comment]
Is it OK if it is partly in Japanese?

**Comment by tensichan83** [comment]
I'm sorry. I did one more build and was able to solve the problem. Sorry for the inconvenience.

**Comment by ShadowMario** [comment]
> Is it OK if it is partly in Japanese?

I guess so?
