### ISSUE TITLE
Bug on 6.0

### ISSUE THREAD

**Issue by Psychenginehelper** [ShadowMario/FNF-PsychEngine#9254]
### Describe your bug here.

Game crashes when i load a song
![2022-06-26 (3)](https://user-images.githubusercontent.com/108227479/175819556-8ad666cc-3b7e-45e1-ac0e-8fab1ca35b06.png)

### Command Prompt/Terminal logs (if existing)

```bash
It made a folder called crash,
and then made a txt that had this in it
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 105)
FreeplayState.hx (line 370)
flixel/FlxState.hx (line 202)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/bopeebo/bopeebo-hard.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No this a built download.

**Comment by ShadowMario** [comment]
File is missing.
Delete the assets/ folder and redownload the build.
