### ISSUE TITLE
HOW DO I FIX THIS??

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#9255]
### Describe your problem here.

<img width="392" alt="image" src="https://user-images.githubusercontent.com/102251392/175819603-37dcfc01-b059-483b-851a-66ca6adf31b7.png">
How the fuck do i fix this like, the notes appears out of the chart editor, it happends with 0.6 build and the 0.5.2h build

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ManMaster707** [comment]
change the song's bpm

**Comment by WilliamGaming12** [comment]
> change the song's bpm

<img width="479" alt="image" src="https://user-images.githubusercontent.com/102251392/175820140-1823590d-f177-458a-9b8f-fe629762c144.png">
WORSE than before

**Comment by ManMaster707** [comment]
> WORSE than before

if you've decreased the bpm, increase it, and viceversa, until it seems editable

**Comment by WilliamGaming12** [comment]
> > WORSE than before
> 
> if you've decreased the bpm, increase it, or viceversa, until it seems editable

By some reason, it stills happends the same
By the other hand, it's the only chart that looks like that (uneditable), it might be 'cause it's from one of the first psych engine updates charts.

**Comment by ShadowMario** [comment]
Clear section.
