### ISSUE TITLE
Enter confirm doesn't animate

### ISSUE THREAD

**Issue by Fridox-lol** [ShadowMario/FNF-PsychEngine#9256]
### Describe your bug here.

In 0.6.0, the "Press Enter To Begin" confirm animation is just one frame.

https://user-images.githubusercontent.com/98615647/175819914-ff137654-81bb-4294-92a0-5f0b8c77e3c2.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ManMaster707** [comment]
It's like this maybe because of [this pr](https://github.com/ShadowMario/FNF-PsychEngine/pull/9022), that was merged before 0.6

**Comment by ShadowMario** [comment]
You have flashing lights turned off.
