### ISSUE TITLE
What does the Vortex Editor do?

### ISSUE THREAD

**Issue by Fridox-lol** [ShadowMario/FNF-PsychEngine#9257]
### Describe your problem here.

read the title

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by machonessiebaby** [comment]
i think it helps with note timings

**Comment by ShadowMario** [comment]
Helps with note quants and you can add notes by pressing 1-8 in your keyboard
