### ISSUE TITLE
Cannot Build Psych Engine

### ISSUE THREAD

**Issue by MoonyOSC** [ShadowMario/FNF-PsychEngine#9258]
### Describe your bug here.

I keep trying to build psych engine 0.6 and this warning keeps happening.

### Command Prompt/Terminal logs (if existing)

```bash
source/FunkinLua.hx:333: lines 333-337 : Int should be Bool
source/FunkinLua.hx:333: lines 333-337 : ... For function argument 'f'
source/FunkinLua.hx:439: lines 439-442 : Int should be Bool
source/FunkinLua.hx:439: lines 439-442 : ... For function argument 'f'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Install the new luajit, it's on the readme
