### ISSUE TITLE
I can't open credits (using the newest version)

### ISSUE THREAD

**Issue by RobumViren849** [ShadowMario/FNF-PsychEngine#9260]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/44604766/175827108-536c8bbc-53d4-468f-a1b9-de29bb3542b6.png)

### Are you modding a build from source or with Lua?

Compiled build

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
Try again in 0.6.1
Close the issue if the problem was solved.
