### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by manguytj5** [ShadowMario/FNF-PsychEngine#9261]
### Describe your bug here.

i was normaly playing fnf and i had an error so yeah

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2494)
PlayState.hx (line 2422)
PlayState.hx (line 1051)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
Try again in 0.6.1
Close the issue if the problem was solved.
