### ISSUE TITLE
Angle Tween help

### ISSUE THREAD

**Issue by hotpocketsarepoggers** [ShadowMario/FNF-PsychEngine#9267]
### Describe your problem here.

I'm trying to make a sprite swing left and right but it's not working(I already have the sprite set at a angle -20)

function onCreatePost()

	        if('bg3.angle' == -20) then
		doTweenAngle('bgLightB', 'bg3.angle', 45, 4, 'quadInOut');
		end
		
		if ('bg3.angle' == 45) then
		doTweenAngle('bgLightB',' bg3.angle', -20, 4, 'quadInOut');
	        end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by frantastic24** [comment]
Use another function, onCreatePost() is only called once while the stage is being loaded

**Comment by hotpocketsarepoggers** [comment]
what function should I use?

**Comment by PogofruitKM** [comment]
Or if you're weird enough you can use ```function onUpdatePost()``` (it will take resources I really don't recommend this)

**Comment by ShadowMario** [comment]
The actual issue are the lines you've put like this:
`if('bg3.angle' == -20) then`

You have to use getProperty to get the angle, like `if getProperty('bg3.angle') == -20 then`
