### ISSUE TITLE
Start Countdown Mid Song

### ISSUE THREAD

**Issue by LucasOnGithub** [ShadowMario/FNF-PsychEngine#9269]
### Describe your problem here.

I'm trying to play an animation in the beginning then start the song, but I don't know how to skip the countdown, then play the animation, then start the song. if possible, post some example code in the comments.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

not really.

**Comment by LucasOnGithub** [comment]
I guess no one wanted to help me.

**Comment by LucasOnGithub** [comment]
I guess no one wanted to help me.

**Comment by Lorekeeper49** [comment]
You can skip the countdown by doing this:
```lua
function onCreate()
    setProperty('skipCountdown', true)
end
```
Playing it midsong is something I'm trying to figure out myself

**Comment by AyMarte** [comment]
If you're trying to do something similar to the Endless song in the Sonic.exe mod, here is an example event of triggering it:

- Countdown.lua `
local waitTime
local waitDelayTime
function onCreatePost()
	waitTime = bpm*(bpm*0.00001)
	waitDelayTime = (bpm*(bpm*0.00001))+0.06
end

function countdown(counters)
	if counters == 'all' then
		runTimer('countdown3', waitDelayTime)
	elseif counters == 'getReady' then
		makeLuaText('getReady', 'THREE', 0, 0, 0)
		setObjectCamera('getReady', 'hud')
		setTextSize('getReady', 200)
		addLuaText('getReady')
		doTweenAlpha('gr', 'getReady', 0, waitTime, 'linear')
		playSound('intro3')
		screenCenter('getReady')
	elseif counters == 'ready' then
		makeLuaText('ready', 'TWO', 0, 0, 0)
		setObjectCamera('ready', 'hud')
		setTextSize('ready', 200)
		addLuaText('ready')
		doTweenAlpha('r', 'ready', 0, waitTime, 'linear')
		playSound('intro2')
		screenCenter('ready')
	elseif counters == 'set' then
		makeLuaText('set', 'ONE', 0, 0, 0)
		setObjectCamera('set', 'hud')
		setTextSize('set', 200)
		addLuaText('set')
		doTweenAlpha('s', 'set', 0, waitTime, 'linear')
		playSound('intro1')
		screenCenter('set')
	elseif counters == 'go' then
		makeLuaText('go', 'GO!', 0, 0, 0)
		setObjectCamera('go', 'hud')
		setTextSize('go', 200)
		addLuaText('go')
		doTweenAlpha('gg!!', 'go', 0, waitTime, 'linear')
		playSound('introGo')
		screenCenter('go')
	end
end

function onTimerCompleted(t, loop, loopLeft)
	if t == 'countdown3' then
		countdown('getReady')
		runTimer('countdown2', waitDelayTime)
	elseif t == 'countdown2' then
		countdown('ready')
		runTimer('countdown1', waitDelayTime)
	elseif t == 'countdown1' then
		countdown('set')
		runTimer('countdown0', waitDelayTime)
	elseif t == 'countdown0' then
		countdown('go')
	end
end

function onEvent(n, v1)
	if n == "Countdown" then
		if v1 == 'all' then
			countdown('all')
		elseif v1 == 'getReady' or 'Get Ready' or 'ready' or 'set' or 'go' or 'go!' or 4 or 3 or 2 or 1 then
			if v1 == 'ready' or 'set' or 'go' then
				countdown(v1)
			elseif v1 == 'go!' then
				countdown('go')
			elseif v1 == 4 or 3 or 2 or 1 then
				counts = {'getReady','ready','set','go'}
				countdown(counts[tonumber(v1)])
			end
		end
	end
end
`
- Countdown.txt `

Plays a countdown

Value 1: Can be either "all" (for full), "getReady",
          "Get Ready", "set", "go", "go!", "4", "3",
           "2", or "1".
`
It isn't really like a countdown, but it is similar to one
