### ISSUE TITLE
This bug issue was a mistake

### ISSUE THREAD

**Issue by LukeTheEpicGamer** [ShadowMario/FNF-PsychEngine#9270]
### Describe your bug here.

The game crashes after pressing on story mode on version 6.0

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Mastercopper2346** [comment]
Is there an error

**Comment by LukeTheEpicGamer** [comment]
That was late sorry it’s normal now

**Comment by Mastercopper2346** [comment]
Just close ot

**Comment by CrusherMods** [comment]
close the gawdzamn issue
