### ISSUE TITLE
press enter to start error

### ISSUE THREAD

**Issue by TurboGames0731** [ShadowMario/FNF-PsychEngine#9277]
### Describe your bug here.

alr, this is minor, but in 6.0, pressing enter on the title screen freezes the "Press Enter to start" image to it's first flashing frame

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment]
You have flashing lights off, it's meant to do that

**Comment by TurboGames0731** [comment]
oh, that's cool
