### ISSUE TITLE
I used a event then the game crashed.

### ISSUE THREAD

**Issue by Embreon69** [ShadowMario/FNF-PsychEngine#9278]
### Describe your bug here.

I tried testing a event, then the game crashed, I have a image if you want it.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
If you have an image why didn't you post it, and why didn't you explain which event you used and how

**Comment by im557** [comment]
i want to see the image, or a video showing me how it crashed

**Comment by ShadowMario** [comment]
Try again in 0.6.1
Close the issue if the problem was solved.
