### ISSUE TITLE
I can't download the source

### ISSUE THREAD

**Issue by Robert124l** [ShadowMario/FNF-PsychEngine#9280]
### Describe your bug here.

When i extract the rar it send me an error: "the file is damaged" it send me. (Forget it, it was brave xd)

### Command Prompt/Terminal logs (if existing)

```bash
Lol
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Robert124l** [comment]
> close this??

Yeah

**Comment by bambitheone82112** [comment]
is your hard disk or memory full?

**Comment by Robert124l** [comment]
> is your hard disk or memory full?

**Comment by Robert124l** [comment]
Shit i forget to close this XD

**Comment by djnbeeman** [comment]
> is your hard disk or memory full?

when a file is damaged it means the file is corrupted and has nothing to do with your storage.

**Comment by Robert124l** [comment]
> > is your hard disk or memory full?
> 
> when a file is damaged it means the file is corrupted and has nothing to do with your storage.

no, it was not the same in my case. It was brave that it was bugged, I downloaded it through google and it already worked.
