### ISSUE TITLE
So Whenever I Open Freeplay I Get This Error Messasge

### ISSUE THREAD

**Issue by Begyosh** [ShadowMario/FNF-PsychEngine#9283]
### Describe your problem here.

![Friday Night Funkin'_ Psych Engine 6_26_2022 9_33_24 PM](https://user-images.githubusercontent.com/108202285/175849382-fbc40d3a-f56a-47f6-b6d2-62602e32e548.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

I Added The Charachter Holy Mami And Then I Tried To See If The Character Worked And When I Went To Freeplay I Get This Message And Then It Closes My Game, Plz Help

**Comment by CrusherMods** [comment]
Make sure you put the character inside "characters", if you put it inside "weeks" then haxe explodes itself.

**Comment by Begyosh** [comment]
Thanks For The Help :)
(This Solved My Problem, Thanks)
