### ISSUE TITLE
Whenever I Try To Put Miku And Mami In The Same Song My Game Crashes, plz help

### ISSUE THREAD

**Issue by Begyosh** [ShadowMario/FNF-PsychEngine#9285]
### Describe your problem here.

So, i put the song The-End In Psych Engine And It Works, The Problem Im Having Is That I Put The Mami Background And My Game Does'nt Crash, Then I Put Miku As BF And It Does'nt Crash, Then Its When I Put Mami In Is When The Game Crashes,Plus I Tried To Put Miku And Mami In The Same Song in Fresh And Whenever I Press Enter, One Of Them Is Always Invisible, And Everytime I Re-open Psych Engine The Invisible Character Is Switched With The Other One, Plz Help
![Friday Night Funkin'_ Psych Engine 6_26_2022 10_32_59 PM](https://user-images.githubusercontent.com/108202285/175854983-06532fa1-cd22-4807-8a6c-be48eb887e9e.png)
 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

**Comment by ShadowMario** [comment]
XML issue
