### ISSUE TITLE
Beat Per Section offsets note when placed

### ISSUE THREAD

**Issue by TBiscuit1** [ShadowMario/FNF-PsychEngine#9290]
### Describe your bug here.

When the "Beat Per Section" option is not 4, notes will offset.

Only way I can explain it is if I turn sections into fractions

With a bps of 4
If I place a note at 0/16, it will place at 0/16
if I place a note at 1/16, it will place at 1/16
That is the normal behavior

With a bps of 2
If I place a note at 0/8, it will place at 0/16
If I place a note at 1/8, it will place at 2/16
Note the "2/16" and not "1/8".
When it register, it is fine, but when it place it thinks it's a normal 4 bps section and offset the note

With a bps of 6
If I place a note at 0/24, it will place at 0/16
If I place a note at 1/24, it will place at 0.66/16
Again, same issue here, it convert to a 16 fraction and offset, but this time backwards

Black X -> Where I clicked
Red   O -> Where the note placed
BPS of 2
![exemple-bps-2](https://user-images.githubusercontent.com/53101126/175885322-ad95a5f6-83ae-4edb-8121-dbee0bf6374a.PNG)
BPS of 6
![exemple-bps-6](https://user-images.githubusercontent.com/53101126/175885326-9bde1077-8496-41cc-b05b-a3642ce94694.PNG)

### Command Prompt/Terminal logs (if existing)

```bash
Unaplicable
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, and Lua can't modify the chart editor anyway

**Comment by TBiscuit1** [comment]
I just realised that the Vortex Editor could be at fault too

**Comment by ShadowMario** [comment]
Not a bug.

**Comment by TBiscuit1** [comment]
????????????

If it's REALLY not a bug, then it is super stupid
Shouldn't it be logical that the note should spawn where I click and not relative to where I click on the section?

I find it hard to believe that it isn't bug and you must have miss understood me, there is no way

**Comment by TheKitBoi** [comment]
> ????????????

Visual Issue

**Comment by TBiscuit1** [comment]
> > ????????????
> 
> Visual Issue

No it's not? I just retried it and the note where placed at the wrong location (aka in the next section) and not how I placed them
