### ISSUE TITLE
Crash bug when i try to open any custom song

### ISSUE THREAD

**Issue by fregnub** [ShadowMario/FNF-PsychEngine#9293]
### Describe your bug here.

![Bild_2022-06-27_133930281](https://user-images.githubusercontent.com/108274498/175932920-2a58bc6c-ee6f-4436-978a-f4896254bddb.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I only edited things in the mods folder and the logo bump file in assets

**Comment by bambitheone82112** [comment]
is your chart from kade engine? if its, you get an error
is your character sprite same with kade? if it, then you get an error
is your song only the voices? if its, you cant chart a song

**Comment by Raltyro** [comment]
> is your chart from kade engine? if its, you get an error is your character sprite same with kade? if it, then you get an error is your song only the voices? if its, you cant chart a song

didnt you see the error

**Comment by Raltyro** [comment]
anyway what was it trying to load because the Paths.hx (line 352) shows that it broke when it tries to load the bitmapdata

**Comment by fregnub** [comment]
> 

Nope, everything was purely on psych engine 0.5.2
All songs are complete

**Comment by fregnub** [comment]
> is your chart from kade engine? if its, you get an error is your character sprite same with kade? if it, then you get an error is your song only the voices? if its, you cant chart a song

everything was on psych engine 0.5.2 before i upgraded. every song was complete and nothing was from kade.

**Comment by ShadowMario** [comment]
Note Splash file missing
