### ISSUE TITLE
How do i add judgement counter?

### ISSUE THREAD

**Issue by bambitheone82112** [ShadowMario/FNF-PsychEngine#9294]
### Describe your problem here.

so i wanted to add judgement counter in psych engine with a lua script putted in `mods/scripts` so idk how to code so help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CrusherMods** [comment]
go to a psych discussion
im sure one of them has a judgement counter
(note: if your going to mayo's discussions its only open for 1 more week and your not allowed to create a discussion there)

**Comment by bambitheone82112** [comment]
> go to a psych discussion im sure one of them has a judgement counter (note: if your going to mayo's discussions its only open for 1 more week and your not allowed to create a discussion there)

the discussion is deleted
