### ISSUE TITLE
Error when you adding custom character.

### ISSUE THREAD

**Issue by Arlaik** [ShadowMario/FNF-PsychEngine#9296]
### Describe your bug here.

I am tryied make a mod

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 217)
C:\HaxeToolkit\haxe\std/haxe/xml/Parser.hx (line 117)
C:\HaxeToolkit\haxe\std/Xml.hx (line 122)
flixel/graphics/frames/FlxAtlasFrames.hx (line 250)
editors/CharacterEditorState.hx (line 840)
editors/CharacterEditorState.hx (line 520)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: haxe.xml.XmlParserException: Expected node name at line 2 char 2
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes i making mod

**Comment by frantastic24** [comment]
Your XML seems to be broken

**Comment by Arlaik** [comment]
I didn't make an Xml file, Adobe Flash generated it for me


пн, 27 июн. 2022 г. в 19:50, frantastic24 ***@***.***>:

**Comment by frantastic24** [comment]
the error doesn't lie, at least post your XML to check

**Comment by ShadowMario** [comment]
Adobe Flash's XML files are bugged, to fix it you have to press Save As and change file encoding to UTF-8.
![Screenshot_1](https://user-images.githubusercontent.com/44785097/178045394-f7f773b7-0e8d-4cc1-bf30-fbf49d1205b6.png)
