### ISSUE TITLE
Inst/Voices too low/high

### ISSUE THREAD

**Issue by GWRRailway** [ShadowMario/FNF-PsychEngine#9298]
### What is your question?

How am I meant to make the inst or voices louder of quieter? Idk if this should be made with events or lua.

**Comment by CrusherMods** [comment]
you should do this with something like audacity or something similar

**Comment by Itz-Miles** [comment]
When charting the song, you can set how low or high the Inst or Vocals are.

**Comment by PogofruitKM** [comment]
> When charting the song, you can set how low or high the Inst or Vocals are.

It only works in the Charting state and doesn't affect the actual playstate. 
But you can certainly try ```setSoundVolume(null, <new volume>)``` and replace new volume with your volume. (Only instrumental!)
You can change the volume of instrumental of a song, but not vocals.
