### ISSUE TITLE
Lua Characters

### ISSUE THREAD

**Issue by radpas1213** [ShadowMario/FNF-PsychEngine#9299]
### What feature do you want to get added on the **base** engine?

Ability to make/add Characters by lua.

It should be a simple character add so you can control what animation is played, basically a blank character that does nothing while still being in their own character group. And also a function that gets called whenever BF, GF, or the Dad is dancing. 

While there is already a way to use offsets for lua sprites it gets kinda annoying when you have to restart the game when making a workaround of a lua character using sprites instead. I'm adding this on my own build for a mod I'm working on but these features would be very cool if it were in psych already.

Let me know if there's a reason you don't/won't do this tho.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by radpas1213** [comment]
I know, I've also done it. What I'm saying is it would be cool for it to be in base psych engine instead of making my own build.

**Comment by frantastic24** [comment]
You don't need your own build??
