### ISSUE TITLE
why my program crash when i die

### ISSUE THREAD

**Issue by MMalkeZ** [ShadowMario/FNF-PsychEngine#9303]
### Describe your bug here.

I don't know how to explain better than that, after the  0.6.0 update, every time I die the game crash and this error window pops up
![Screenshot_133](https://user-images.githubusercontent.com/108292251/175993624-89d5107b-c4ea-43d2-a703-008e674e5379.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't edit anything on the source code

**Comment by frantastic24** [comment]
Are you using a modchart

**Comment by MMalkeZ** [comment]
> Are you using a modchart

You mean events or scripts? if that's so, yes

**Comment by frantastic24** [comment]
I meant specifically anything that affects arrows but you should've posted the scripts you're using anyways

**Comment by frantastic24** [comment]
alright i found the issue, your death character is missing an animation: `firstDeath`

**Comment by frantastic24** [comment]
bf isn't used as a death character anymore, a different character and image is used now

**Comment by MMalkeZ** [comment]
> bf isn't used as a death character anymore, a different character and image is used now

guess i'm f***ed now

**Comment by frantastic24** [comment]
uhh no just install the game properly

**Comment by MMalkeZ** [comment]
> uhh no just install the game properly

wdym instal properly? i downloaded the regular 0.6.0, i didn't modified the source code or anything, it is the normal game

**Comment by frantastic24** [comment]
did you check bf-dead is there and that you updated the manifest folder if you didn't do a fresh install
