### ISSUE TITLE
Health Bar Problem

### ISSUE THREAD

**Issue by MrXCable** [ShadowMario/FNF-PsychEngine#9304]
### Describe your problem here.

I was trying to make a custom healthbar, where the edges are circular, but the colors are over the bg. Is there a fix to this?
![Screenshot_26](https://user-images.githubusercontent.com/96361193/176005255-61868db1-388b-4b92-a70e-2f39799b134c.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Lost-Daemon** [comment]
Move the healthbarBG code to below the healthBar code.

**Comment by MrXCable** [comment]
> 

it crashes the game when i load a song when i do that

**Comment by MrXCable** [comment]
> Move the healthbarBG code to below the healthBar code.

it crashes the game when i do that.

**Comment by MrXCable** [comment]
UPDATE: i fixed it. thank you!
