### ISSUE TITLE
A MOD ERROR OF INDIE CROSS FOR PSYCH ENGINE

### ISSUE THREAD

**Issue by JAMES0711PVPYT** [ShadowMario/FNF-PsychEngine#9307]
### Describe your bug here.

D:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 318)
D:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 99)
D:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
ModsMenuState.hx (line 733)
ModsMenuState.hx (line 329)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid char 100 at position 32
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Command Prompt/Terminal logs (if existing)

```bash
D:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 318)
D:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 99)
D:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
ModsMenuState.hx (line 733)
ModsMenuState.hx (line 329)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added the mod and not funtion

**Comment by frantastic24** [comment]
One of your json files is broken

**Comment by JAMES0711PVPYT** [comment]
Can fixed?
please?

**Comment by frantastic24** [comment]
You can fix it yourself

**Comment by JAMES0711PVPYT** [comment]
ok , entonces gracias
