### ISSUE TITLE
i need to make a custom dialogue box but only for two songs, is there a way how?

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#9308]
### Describe your problem here.

same problem as #8931 but i only need it for specific songs

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

The thing i editted related to dialogue is the script that plays it by making dialogue bg's

**Comment by hayfii** [comment]
No, there's not.
