### ISSUE TITLE
How do you move arrows? pls help!!

### ISSUE THREAD

**Issue by cheemynugget** [ShadowMario/FNF-PsychEngine#931]
### Describe your problem here.

So in dave and bambi i seen the arrows move and i was wondering if i can do that in psych. 

FOR SHADOWMARIO: In dave and bambi the arrows move left and right speratley and sometimes even in circles

https://www.youtube.com/watch?v=em-87F0UL-w&t=42s - cheating

https://www.youtube.com/watch?v=vicmsm4YTlM unfairness

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

so far ive added characters and changed stage lua codes and a bit more but not much

**Comment by lolbruhfart** [comment]
well try this PS. change bg farm to your bg name then put then paste in stage lua file

local angleshit = 1;
local anglevar = 1;
function onCreate()
	makeLuaSprite('bg','bgfarm',-343.15, -295.45)
	addLuaSprite('bg',false)
	
end

function onBeatHit()
	if curBeat < 388 then
		triggerEvent('Add Camera Zoom', 0.00000000005,0.000000000005)

		if curBeat % 2 == 0 then
			angleshit = anglevar;
		else
			angleshit = -anglevar;
		end
		setProperty('camHUD.angle',angleshit*500)
		setProperty('camGame.angle',angleshit*6)
		doTweenAngle('turn', 'camHUD', angleshit, stepCrochet*0.002, 'circOut')
		doTweenX('tuin', 'camHUD', -angleshit*25, crochet*0.001, 'linear')
		doTweenAngle('tt', 'camGame', angleshit, stepCrochet*0.002, 'circOut')
		doTweenX('ttrn', 'camGame', -angleshit*22, crochet*0.001, 'linear')
	else
		setProperty('camHUD.angle',0)
		setProperty('camHUD.x',0)
		setProperty('camHUD.x',0)
	end
		
end

function onStepHit()
	if curBeat < 388 then
		if curStep % 4 == 0 then
			doTweenY('rrr', 'camHUD', -12, stepCrochet*0.002, 'circOut')
			doTweenY('rtr', 'camGame.scroll', 12, stepCrochet*0.002, 'sineIn')
		end
		if curStep % 4 == 2 then
			doTweenY('rir', 'camHUD', 0, stepCrochet*0.002, 'sineIn')
			doTweenY('ryr', 'camGame.scroll', 0, stepCrochet*0.002, 'sineIn')
		end
	end
end

**Comment by MarkToonsHD** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/771
