### ISSUE TITLE
It keeps on crashing when loading a custom icon

### ISSUE THREAD

**Issue by KazuiShoto** [ShadowMario/FNF-PsychEngine#9310]
### Describe your bug here.

every time I try and add a custom icon in the character editor it crashes

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, it was a fresh copy of the engine that had a few other assets added

**Comment by frantastic24** [comment]
show logs
