### ISSUE TITLE
when i try to load a song everything except the audio loads

### ISSUE THREAD

**Issue by imalink100** [ShadowMario/FNF-PsychEngine#9311]
### Describe your bug here.

the audio doesnt load, it says 0/0 in the chart editor? i tried re-adding the files, it didn't work. 
![image](https://user-images.githubusercontent.com/106406304/176087905-5f3462bb-b99b-4334-be3c-e617914e3d65.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i tried re-adding the files, it didn't work

**Comment by frantastic24** [comment]
Your files are broken, re-export/reconvert them

**Comment by imalink100** [comment]
i've seen that reply on all of the bug reports so no

**Comment by frantastic24** [comment]
Post your files then

**Comment by CrusherMods** [comment]
> i've seen that reply on all of the bug reports so no

someone had the same issue and it got resolved by following that

it is an audio problem

**Comment by frantastic24** [comment]
Is it that hard to compress a file
You could've also uploaded them to a public drive folder or something, it's not that hard to work around

**Comment by imalink100** [comment]
> Is it that hard to compress a file You could've also uploaded them to a public drive folder or something, it's not that hard to work around

this is the song: https://www.youtube.com/watch?v=FPSFxicebj0

**Comment by frantastic24** [comment]
That's not what I asked for

**Comment by imalink100** [comment]
> That's not what I asked for

Then what did you ask for?

**Comment by frantastic24** [comment]
Files, not a YouTube video

**Comment by frantastic24** [comment]
We are trying to see if your files are broken or not, the actual audio doesn't matter. A YouTube video doesn't help

**Comment by imalink100** [comment]
> We are trying to see if your files are broken or not, the actual audio doesn't matter. A YouTube video doesn't help

https://drive.google.com/drive/folders/1ScabhRLAf237UPi-bzxB3apVkN7QUj4q

**Comment by frantastic24** [comment]
i was correct, you fucked up the conversion
after doing it propertly it works

**Comment by imalink100** [comment]
> i was correct, you fucked up the conversion after doing it propertly it works

How do YOU know?

**Comment by frantastic24** [comment]
because i just tested it genius

**Comment by imalink100** [comment]
> because i just tested it genius

what do you mean by that

**Comment by frantastic24** [comment]
the file you sent me, it didn't work until i converted it properly

**Comment by imalink100** [comment]
> the file you sent me, it didn't work until i converted it properly

ok send me the working version

**Comment by frantastic24** [comment]
I don't have it anymore, you can use an online converter

**Comment by imalink100** [comment]
> I don't have it anymore, you can use an online converter

i did that to get the one that didnt work

**Comment by frantastic24** [comment]
Just make sure you are converting to ogg vorbis, there is also more than just one converter you can try

**Comment by frantastic24** [comment]
Since the problem has been found you should close this

**Comment by imalink100** [comment]
ok
