### ISSUE TITLE
0.6.1 compile error 

### ISSUE THREAD

**Issue by XS09-dev** [ShadowMario/FNF-PsychEngine#9312]
### Describe your bug here.

Int should be bool in funkinlua.hx

### Command Prompt/Terminal logs (if existing)

```bash
source/FunkinLua.hx:342: lines 342-346 : Int should be Bool
source/FunkinLua.hx:342: lines 342-346 : ... For function argument 'f'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No. I didn't add/edit anything yet.

**Comment by frantastic24** [comment]
Install the new luajit

**Comment by XS09-dev** [comment]
ok
