### ISSUE TITLE
Dialogues thing

### ISSUE THREAD

**Issue by joxu13v** [ShadowMario/FNF-PsychEngine#9314]
### What is your question?

How can i have backgrounds in a dilogue like hex or starlight mayhem using .lua, to make something like a comic

**Comment by BernardoGP4504** [comment]
add those lines as said:
```
                makeLuaSprite('bgimage', 'your image', -100, 0);
		scaleObject('bgimage', 1.3, 1.3);
		addLuaSprite('bgimage', true);
```
at the first if (specifically from line 5 to 7)

`removeLuaSprite('bgimage');` at the end of that if (line 13)
and that's it. Please tell me if you need changing ones

**Comment by BernardoGP4504** [comment]
change '`'your image'`' to the image you need (including the quotes)

**Comment by joxu13v** [comment]
Do you know how to change the image when moving from one dialog to another?

**Comment by BernardoGP4504** [comment]
go into **`script.lua`** (the file that plays the dialogue) and follow the instructions:
find `function onNextDialogue(count)` and inside it add an if:
```
if count == [dialogue] then
                removeLuaSprite('bgimage1');
		makeLuaSprite('bgimage2', 'your image', -100, 0);
		scaleObject('bgimage2', 1.3, 1.3);
		addLuaSprite('bgimage2', true);
end
```
also change the first bg that we added (only the 'bgimage' part) to 'bgimage1'
![Captura de Tela (12)](https://user-images.githubusercontent.com/101405920/176459589-765966c7-8874-4589-ae8c-001f4e9c0b95.png)
### things you have to change

1. [dialogue] - the dialogue line (number) that you want to change but it's not what you think!! 'line' starts with 1 so ex:
if i said 2 in that if, it would happen at line 3
so change it to the line you want -1
2. the remove in the first if should be the last bg you added like: if i added two bgs then the remove would be to remove the second bg

**Comment by BernardoGP4504** [comment]
also you can add as many as you want

**Comment by joxu13v** [comment]
Thanjs a lot
