### ISSUE TITLE
Lag spikes during gameplay, probably found the issue. (0.6.x)

### ISSUE THREAD

**Issue by ParaKrei** [ShadowMario/FNF-PsychEngine#9315]
### Describe your bug here.

This is a bug that has been showing up in other issues... but I think I have pinpointed the issue.

After messing around with settings, such as: **botplay**, **practice mode**, **zoom score text on note hit**, and **hide hud**... I found out that the **score text was somehow lagging the game.**

_With botplay/practice_, I found out that when the game starts to calculate the rating percent along with everything else in the score text, **the game will have constant lag spikes during gameplay as soon as the player hits a note**. Such can be seen when the rating is still a question mark.

After I set the scoreTxt,visible variable to false via a Lua script, the game ran fine.

I hope this can help anyone on this project to fix the lag spikes, as it happens with the base songs and modded songs.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No change to source, I don't know Haxe yet.

**Comment by ParaKrei** [comment]
### --Update--
Just turned off my scoreTxt-disabling script and went to **Week 1**, and I noticed that the memory was fluctuating wildly **after a note is hit, shooting up to around 766.4MB, then lagging the game, then going back to around 550MB.**
Seems like another memory issue... how odd.

**Comment by tylerandari12** [comment]
#9322
Its intentional...

**Comment by frantastic24** [comment]
That has nothing to do with this
scoreTxt updates were changed recently so try the latest commits
