### ISSUE TITLE
BF icon changing to flixel icon

### ISSUE THREAD

**Issue by bambitheone82112** [ShadowMario/FNF-PsychEngine#9316]
### Describe your bug here.

i might forgot the crash

sooo i was making a psych gain event and after i test it, the bf icon changes to flixel icon so help me fixing this massive rare bug or idk

### Command Prompt/Terminal logs (if existing)

```bash
null object reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

idk

**Comment by frantastic24** [comment]
Show the event

**Comment by bambitheone82112** [comment]
> Show the event

the gain.lua script took the bf icon over the flixel icon

**Comment by CrusherMods** [comment]
> > Show the event
> 
> 
> 
> the gain.lua script took the bf icon over the flixel icon

we dont know whats inside the file though 🤦‍♂️

**Comment by djnbeeman** [comment]
> > > Show the event
> > 
> > 
> > the gain.lua script took the bf icon over the flixel icon
> 
> we dont know whats inside the file though 🤦‍♂️

true :trollface:

**Comment by ShadowMario** [comment]
You have to show the crash log/trace and maybe your lua code aswell.

**Comment by hayfii** [comment]
> > Show the event
> 
> the gain.lua script took the bf icon over the flixel icon

We need the script smartie!

**Comment by bambitheone82112** [comment]
> > > Show the event
> > 
> > 
> > the gain.lua script took the bf icon over the flixel icon
> 
> We need the script smartie!

the script is:

function onEvent(name, value1, value2) 
	drainValue = tonumber(value1);
	curHealth = getProperty('health');
		if drainValue == null then
		drainValue = 0.02;
		
		else 
		damageValue = 0.02 + drainValue;
		end
		if name == 'Gain' then
			if curHealth < 2 then
			setProperty('health', curHealth + damageValue);
			
			end
			if curHealth > 2 then
			setProperty('health', 2);
		end
	end
end

**Comment by bambitheone82112** [comment]
> You have to show the crash log/trace and maybe your lua code aswell.

the crash log is null object reference after the song ends

**Comment by frantastic24** [comment]
Screenshot the log

**Comment by tylerandari12** [comment]
```lua
function onEvent(name, value1, value2)
drainValue = tonumber(value1);
curHealth = getProperty('health');
if drainValue == nil --[[Thanks, tylerandari12]] then
drainValue = 0.02;

	else 
	damageValue = 0.02 + drainValue;
	end
	if name == 'Gain' then
		if curHealth < 2 then
		setProperty('health', curHealth + damageValue);
		
		end
		if curHealth > 2 then
		setProperty('health', 2);
	end
end
end
```

**Comment by bambitheone82112** [comment]
> Screenshot the log

too late i dont have it
