### ISSUE TITLE
how do you get songs to exist after doing something

### ISSUE THREAD

**Issue by cheemynugget** [ShadowMario/FNF-PsychEngine#932]
### Describe your problem here.

For example pressing 7 on the keyboard on one song takes to another song

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

so far ive added characters and changed stage lua codes and a bit more but not much

**Comment by ShadowMario** [comment]
```lua
function onUpdate(elapsed)
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
        endSong();
    end
end
```
This should work i think?

**Comment by cheemynugget** [comment]
> ```lua
> function onUpdate(elapsed)
>     if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
>         endSong();
>     end
> end
> ```
> 
> This should work i think?

it doesnt work it just crashes the game, also how do i  make it take me to another song when i press 7 like for example press 7 seven on (songname) and it starts another song

**Comment by perngjiafu** [comment]
go to chartingstate or smth idrk

**Comment by FuseIsHere813** [comment]
> > ```lua
> > function onUpdate(elapsed)
> >     if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
> >         endSong();
> >     end
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This should work i think?
> 
> it doesnt work it just crashes the game, also how do i make it take me to another song when i press 7 like for example press 7 seven on (songname) and it starts another song

for source code, Go to PlayState.hx and find line 1819, make a new line, and add this: `if (FlxG.keys.justPressed.SEVEN)
				{
					switch (curSong.toLowerCase())
					{
						case 'your-song-name':
						PlayState.SONG = Song.loadFromJson("your-song-name", "your-song-name"); // This is the song it loads after pressing 7 on a song
						FlxG.save.data.cheatingFound = true;
						FlxG.switchState(new PlayState());
						return;
					}
				}`

**Comment by ShadowMario** [comment]
> go to chartingstate or smth idrk

If you don't know why are you even replying

**Comment by ShadowMario** [comment]
```lua
function onUpdate(elapsed)
    if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.FOUR') then
        endSong();
    end
end
```
Tested this and it worked.
Press 4 to skip song.
If it still crashes you might need to update to 0.4.2 (if you're not on this version)

**Comment by PDL2CGamejolt** [comment]
> > > ```lua
> > > function onUpdate(elapsed)
> > >     if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
> > >         endSong();
> > >     end
> > > end
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This should work i think?
> > 
> > 
> > it doesnt work it just crashes the game, also how do i make it take me to another song when i press 7 like for example press 7 seven on (songname) and it starts another song
> 
> for source code, Go to PlayState.hx and find line 1819, make a new line, and add this: `if (FlxG.keys.justPressed.SEVEN) { switch (curSong.toLowerCase()) { case 'your-song-name': PlayState.SONG = Song.loadFromJson("your-song-name", "your-song-name"); // This is the song it loads after pressing 7 on a song FlxG.save.data.cheatingFound = true; FlxG.switchState(new PlayState()); return; } }`

can you do it for lua

**Comment by PDL2CGamejolt** [comment]
> > > > ```lua
> > > > function onUpdate(elapsed)
> > > >     if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.SEVEN') then
> > > >         endSong();
> > > >     end
> > > > end
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > This should work i think?
> > > 
> > > 
> > > it doesnt work it just crashes the game, also how do i make it take me to another song when i press 7 like for example press 7 seven on (songname) and it starts another song
> > 
> > 
> > for source code, Go to PlayState.hx and find line 1819, make a new line, and add this: `if (FlxG.keys.justPressed.SEVEN) { switch (curSong.toLowerCase()) { case 'your-song-name': PlayState.SONG = Song.loadFromJson("your-song-name", "your-song-name"); // This is the song it loads after pressing 7 on a song FlxG.save.data.cheatingFound = true; FlxG.switchState(new PlayState()); return; } }`
> 
> can you do it for lua

NVM, it's an old reply.
