### ISSUE TITLE
Massive lag spikes in version 0.6.x during songs

### ISSUE THREAD

**Issue by LeoroyX** [ShadowMario/FNF-PsychEngine#9320]
### Describe your bug here.

It seems that when playing songs in the newer versions of Psych, causes a massive spike in memory shooting it to very high levels up to 1000MB in less than 5 seconds then goes back to 500MB to then return spiking once I start hitting notes again. I'm not sure what causes it though. What's interesting, however, is that, during BOTPLAY sessions, there's no memory spikes and the game runs normally as well as when I disable HUD elements, which feels odd. Is there a reason as to why?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, nothing was touched.

**Comment by tylerandari12** [comment]
I thought it was normal for it to hang around 1000MB :O

**Comment by LeoroyX** [comment]
> I thought it was normal for it to hang around 1000MB :O

While I agree, since FNF tends to go that high (and even higher in cases like Kade Engine or its mods), It IS creating major spikes and it is not normal for the memory to start building up and fluctuating at ridiculous speeds when you press a note during songs, I think that alone is what's causing the major spikes.
