### ISSUE TITLE
Is it normal for the engine to use 1000 MB?

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#9322]
### What is your question?

This isn't causing me many problems but I was just wondering as it seems **WAY** higher than it used to be...

**Comment by ManMaster707** [comment]
For me it's perfectly normal, on 5.2h it rarely causes lag

**Comment by ShadowMario** [comment]
Yes.
Now Freeplay keeps your PlayState files loaded in RAM so it can load faster when you go into another song from the same week.

**Comment by polybiusproxy** [comment]
> > Yes. Now Freeplay keeps your PlayState files loaded in RAM so it can load faster when you go into another song from the same week.
> 
> Thats nice :0 My game crashes (no crash handler report btw) when it reaches 1100MB but i think thats a proplem on my end...

Upgrade your RAM.
