### ISSUE TITLE
Whenever i use the DadBattle Stage Light it crashes.

### ISSUE THREAD

**Issue by marbloxy** [ShadowMario/FNF-PsychEngine#9325]
### Describe your bug here.

Whenever i go in a song, press 7 and use the DadBattle Stage Light, it crashes.

### Command Prompt/Terminal logs (if existing)

```bash
Paths.hx (line 352)
BGSprite.hx (line 24)
PlayState.hx (line 2462)
PlayState.hx (line 2411)
PlayState.hx (line 1054)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i did not edit anything in this build.

**Comment by frantastic24** [comment]
It's hardcoded for the week 1 stage only, you're not supposed to use it outside of that

**Comment by SleepyzDotExe** [comment]
> It's hardcoded for the week 1 stage only, you're not supposed to use it outside of that

I see. How can I get rid of the event outside of the game (Whenever I go to the song it crashes, even in the charter) Like in the files or something?

**Comment by marbloxy** [comment]
> It's hardcoded for the week 1 stage only, you're not supposed to use it outside of that

i used the week 1 stage in the tutorial

**Comment by frantastic24** [comment]
seems to be crashing because you don't have the stage light sprites in your game files

**Comment by ShadowMario** [comment]
Week 1 is the only place where you can use Dadbattle Spotlight
