### ISSUE TITLE
Lag spikes

### ISSUE THREAD

**Issue by Smokva4** [ShadowMario/FNF-PsychEngine#9328]
### Describe your bug here.

so when i play song the memory is 600 and is going to 700 and going to 600 and it makes lag spikes

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i edited titlestate discord achievments creditsstate and mainmenustate

**Comment by LeoroyX** [comment]
> it might the song be overcharted like thearchy from strident crisis

Not really, I have the same issue with dadbattle. So it's not overcharting the problem. There's a issue here that explains some of their finds and I also think the problem already got adressed by one of the devs, and it has something to do with how the score calculation is handled in the newer versions, leading to absurd memory spikes. I think it will be fixed next update for sure.

**Comment by polybiusproxy** [comment]
> apparently putting this in a script fixes the lag for some reason (for me, at least)
> 
> ```lua
> function onUpdate()
>     setProperty('scoreTxt.alpha', 0);
> end
> ```

HaxeFlixel unloads the sprite when it's alpha is set to 0.
This means, that when changing the alpha back to any number that isn't zero, will produce a little lag spike when loading back the sprite.

**Comment by Smokva4** [comment]
> apparently putting this in a script fixes the lag for some reason (for me, at least)
> 
> ```lua
> function onUpdate()
>     setProperty('scoreTxt.alpha', 0);
> end
> ```

in what script i need to put this ?

**Comment by frantastic24** [comment]
> #9322

That has literally nothing to do with this, did you even read the issue

That aside, scoreTxt updates were changed recently so I recommend checking the latest commits

**Comment by MGDFURRY** [comment]
> 

![image](https://user-images.githubusercontent.com/40258538/177231775-6db4d27f-491a-4578-9036-24be2504d519.png)
