### ISSUE TITLE
i like how in some mods the icons like squish so how can i do that?

### ISSUE THREAD

**Issue by cheemynugget** [ShadowMario/FNF-PsychEngine#933]
### Describe your problem here.

Just look at what i mean look at the icons in this vid 
https://www.youtube.com/watch?v=d44tic94vwg

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

so far ive added characters and changed stage lua codes and a bit more but not much

**Comment by lolbruhfart** [comment]
There is probably a function in the source to make the intensity of the icon beats crazy

**Comment by ShadowMario** [comment]
```lua
function onUpdate(elapsed)
    setProperty('iconP1.scale.x`, getProperty('iconP1.scale.y') * 1.75);
end
```
Something like this should work

**Comment by ShadowMario** [comment]
> There is probably a function in the source to make the intensity of the icon beats crazy

Don't post anything if you don't have anything HELPFUL to say.
