### ISSUE TITLE
source/MainMenuState.hx:130: characters 88-90 : Expected , or ) error

### ISSUE THREAD

**Issue by XolinYT** [ShadowMario/FNF-PsychEngine#9336]
### What feature do you want to get added on the **base** engine?

source/MainMenuState.hx:130: characters 88-90 : Expected , or )
this what says psych engine when i am use lime test windows....

### To test your sight, and reliability, please select the option of what should NOT be requested.

Code optimization that would make the game faster. (You should make a PR if this is your request, by the way.)

**Comment by CrusherMods** [comment]
1. this should go in help wanted, not enhancement
2. your missing an , or ) near line 130
3. you failed the test
