### ISSUE TITLE
How do i make jacks in the chart editor???

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#9339]
### What is your question?

<img width="181" alt="image" src="https://user-images.githubusercontent.com/102251392/176219827-a6b45fca-267c-4e90-ad95-9c2238f41046.png">
Like those ones

**Comment by Wither362** [comment]
Quants

**Comment by Superyoshi94** [comment]
hold shift

**Comment by WilliamGaming12** [comment]
> hold shift

thank you very much
