### ISSUE TITLE
Missing "Easter Eggs"

### ISSUE THREAD

**Issue by LieutenantJoe** [ShadowMario/FNF-PsychEngine#9342]
### Describe your bug here.

Version 6.1 reverted my title screen back to the default Girlfriend, when it was previously ShadowMario. I attempted to enter the code to use him again, but nothing happened.
Writing this to make sure if this is either a bug, or an intentional removal.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Outside of installing dozens of mods, none of the dance files are removed or altered.

**Comment by JulianCharizard** [comment]
I had the same but idk what it is sry

**Comment by tylerandari12** [comment]
> Seems like they forgot to define it as official build, secrets aren't removed it's just a slipup

Oh I thought that was intentional...
