### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by schwiftified** [ShadowMario/FNF-PsychEngine#9343]
### Describe your bug here.

i added gf to the follow pose script and it gives me this error
![error](https://user-images.githubusercontent.com/96924332/176249492-dee05aec-455e-485a-9ee9-9b0dc98c669e.png)

heres the script:
[follow.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9003549/follow.txt)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i added gf, xx3, yy3 and ofs3

**Comment by frantastic24** [comment]
this isn't a bug, it's an error on your code and the error is literally telling you

**Comment by schwiftified** [comment]
ah

**Comment by schwiftified** [comment]
the thing is i just started lua and i dont know much about it

**Comment by frantastic24** [comment]
now close this

**Comment by frantastic24** [comment]
read the error, you are missing an `end`

**Comment by schwiftified** [comment]
thx

**Comment by LucasOnGithub** [comment]
hey im here now

**Comment by schwiftified** [comment]
this is closed
