### ISSUE TITLE
BF/Dad Animation on Step Hit?

### ISSUE THREAD

**Issue by LucasOnGithub** [ShadowMario/FNF-PsychEngine#9344]
### What is your question?

I need the code for animation playing on step hit, because events are kind of buggy and don't work that well on my version.

**Comment by frantastic24** [comment]
[animation functions](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-General-Functions#characterplayanimcharacterstring-animstring-forcedbool--false)
[variables](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Variables#gameplay-variables)
