### ISSUE TITLE
Weird Week Difficulty Bug

### ISSUE THREAD

**Issue by TheGuyTree64** [ShadowMario/FNF-PsychEngine#9346]
### Describe your bug here.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/108364816/176259385-4fdd1463-b2d4-415d-a859-c4a9cfddc788.png">
This error pops up when I'm selecting different difficulties on the story menu.

### Command Prompt/Terminal logs (if existing)

```bash
Paths.hx (line 352)
StoryMenuState.hx (line 335)
StoryMenuState.hx (line 234)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added a new difficulty.

**Comment by frantastic24** [comment]
missing week image files
