### ISSUE TITLE
Event Error? Anyone help?

### ISSUE THREAD

**Issue by IsThisProGamersX** [ShadowMario/FNF-PsychEngine#9347]
### Describe your bug here.

Is about the new update 0.6.1, that I use the Event Dadbattle Spotlight on a different song in the chart editor and it crashes and show a Crash Handler.

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2455)
PlayState.hx (line 2411)
PlayState.hx (line 1054)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, only I put some mods.

**Comment by NS-Unfair** [comment]
Not sure why this happens; this event worked for me on other weeks. What values are you passing to the event?

**Comment by frantastic24** [comment]
Week doesn't matter, stage does
