### ISSUE TITLE
I can't pause the game nor can I leave a song when it ends and I can't die

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [ShadowMario/FNF-PsychEngine#9348]
### Describe your bug here.

I can't pause the game nor can I leave a song when it ends and I can't die

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No Base download from GB

**Comment by frantastic24** [comment]
Happens when scripts don't have `return Function_Continue`, check yours

**Comment by ImaginationSuperHero528** [comment]
> Happens when scripts don't have `return Function_Continue`, check yours

No like in general! I even removed the mods folder!

**Comment by ImaginationSuperHero528** [comment]
Nvm had to reload now it's not being stupid now to just find the script... I'm gonna hate this.
