### ISSUE TITLE
I just clicked on a text field, and...

### ISSUE THREAD

**Issue by CatCentralGitHub** [ShadowMario/FNF-PsychEngine#9349]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/88316465/176275528-a0c518d8-9c02-4443-b526-5db2398c9057.png)
I just clicked on a text field and this happened...

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I'm not modding anything, just editing a chart.

**Comment by Itz-Miles** [comment]
Did you change the pathname of an image file that reloads charting state/the note grid? It won't be able to find the splashes or note assets for example, causing it to crash when trying to reload the notes.

**Comment by CatCentralGitHub** [comment]
Nope.
