### ISSUE TITLE
Looking at Pico's Speaker sprite completely crashes the game

### ISSUE THREAD

**Issue by BZAnimations** [ShadowMario/FNF-PsychEngine#9351]
### What is your question?

![NewCanvas1](https://user-images.githubusercontent.com/69319318/176287244-4b202ef9-2ff0-41f9-b251-3de45386ec40.png)

So i went into the character editor and out of curiosity i decided to check out how pico's speaker sprites in stress work, so i clicked his name in the list of characters and this happens every time, i'm just kinda wondering why it does that

**Comment by frantastic24** [comment]
you need to load stress first
