### ISSUE TITLE
Why is a bigger spritesheet with few discernable differences smaller in mebibytes?

### ISSUE THREAD

**Issue by Itz-Miles** [ShadowMario/FNF-PsychEngine#9353]
### What is your question?

I was comparing my current srpitesheet from a loose setting in a sprite packer to the current spritesheet I downloaded off Psych 0.6, and I noticed the latter was smaller in (filesize?) despite being larger in size with the same bitmap data. There were explanations for this that I thought of, but I've come here to ask.
![Screenshot (72)](https://user-images.githubusercontent.com/95124554/176310208-4a0625a6-77df-476f-9f5f-c2590df08c4f.png)

**Comment by RowanSkie** [comment]
It's most likely actually rubbish data that's trimmed in the base Psych Engine one. One that can easily be removed via apps like [PNGGauntlet](https://pnggauntlet.com/).

**Comment by ShadowMario** [comment]
How is this related to Psych Engine
