### ISSUE TITLE
help with the key pressed function

### ISSUE THREAD

**Issue by BlearChipmunk** [ShadowMario/FNF-PsychEngine#9354]
### Describe your problem here.

the thing is that i want the arrows move when you press a key, for example if i press "left" all the arrows move, i tried but failed, this is the code that i am trying to use

function keyPressed (key)

if key == 'left' then
noteTweenX('defaultPlayerStrumX0', 4 , defaultPlayerStrumX0 - 40, 0.05 , 'quadInOut');
noteTweenX('defaultPlayerStrumX1', 5 , defaultPlayerStrumX1 - 40, 0.05 , 'quadInOut');
noteTweenX('defaultPlayerStrumX2', 6 , defaultPlayerStrumX2 - 40, 0.05 , 'quadInOut');
noteTweenX('defaultPlayerStrumX3', 7 , defaultPlayerStrumX3 - 40, 0.05 , 'quadInOut');
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
That's not how it works
```lua
function onUpdate()
     if keyJustPressed('key') then --check wiki for keys 

     end
end
```

**Comment by BlearChipmunk** [comment]
thanks a lot! but sadly it kinda work, maybe is the ease...

**Comment by frantastic24** [comment]
Well it works so this can be closed

**Comment by BlearChipmunk** [comment]
i solved it, and to help someone else

if keyPressed('left') then
noteTweenX('defaultPlayerStrumX0', 4 , defaultPlayerStrumX0 - 40, 0.05 , 'linear');
noteTweenX('defaultPlayerStrumX1', 5 , defaultPlayerStrumX1 - 40, 0.05 , 'linear');
noteTweenX('defaultPlayerStrumX2', 6 , defaultPlayerStrumX2 - 40, 0.05 , 'linear');
noteTweenX('defaultPlayerStrumX3', 7 , defaultPlayerStrumX3 - 40, 0.05 , 'linear');
end

if keyPressed('down') then
noteTweenY('defaultPlayerStrumY0', 4 , defaultPlayerStrumY0 + 40, 0.05 , 'linear');
noteTweenY('defaultPlayerStrumY1', 5 , defaultPlayerStrumY1 + 40, 0.05 , 'linear');
noteTweenY('defaultPlayerStrumY2', 6 , defaultPlayerStrumY2 + 40, 0.05 , 'linear');
noteTweenY('defaultPlayerStrumY3', 7 , defaultPlayerStrumY3 + 40, 0.05 , 'linear');
end

if keyPressed('up') then
noteTweenY('defaultPlayerStrumY0', 4 , defaultPlayerStrumY0 - 40, 0.05 , 'linear');
noteTweenY('defaultPlayerStrumY1', 5 , defaultPlayerStrumY1 - 40, 0.05 , 'linear');
noteTweenY('defaultPlayerStrumY2', 6 , defaultPlayerStrumY2 - 40, 0.05 , 'linear');
noteTweenY('defaultPlayerStrumY3', 7 , defaultPlayerStrumY3 - 40, 0.05 , 'linear');
end

if keyPressed('right') then
noteTweenX('defaultPlayerStrumX0', 4 , defaultPlayerStrumX0 + 40, 0.05 , 'linear');
noteTweenX('defaultPlayerStrumX1', 5 , defaultPlayerStrumX1 + 40, 0.05 , 'linear');
noteTweenX('defaultPlayerStrumX2', 6 , defaultPlayerStrumX2 + 40, 0.05 , 'linear');
noteTweenX('defaultPlayerStrumX3', 7 , defaultPlayerStrumX3 + 40, 0.05 , 'linear');
end

thanks frantastic!
