### ISSUE TITLE
Mod Menu Bug

### ISSUE THREAD

**Issue by Psychenginehelper** [ShadowMario/FNF-PsychEngine#9355]
### Describe your bug here.

I tried to edit the background asset for the week and it came up with this 
![2022-06-28 (9)](https://user-images.githubusercontent.com/108227479/176337296-8989986c-ead0-4932-b6bf-d9f94e452e9e.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No this a built download.

**Comment by frantastic24** [comment]
file path seems to be incorrect

**Comment by Psychenginehelper** [comment]
> file path seems to be incorrect

Ill see if i can edit it without it crashing, ive seen then going on with every text in psych engine
