### ISSUE TITLE
Bring back the discussions tab

### ISSUE THREAD

**Issue by Ace5542** [ShadowMario/FNF-PsychEngine#9358]
### What feature do you want to get added on the **base** engine?

The discussion tab helped me and a lot of people get answers for our problems and help others answer theirs, I would really want that back

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ImaginationSuperHero528** [comment]
There's fan ones join those

**Comment by ShadowMario** [comment]
No.

**Comment by ImaginationSuperHero528** [comment]
> > There's fan ones join those
> 
> Where? :0

Look around ig I'm pretty sure if you check #nochat-downloads-lua-scripts you should find one actually.
