### ISSUE TITLE
Making character icons disappear via Lua

### ISSUE THREAD

**Issue by RowanSkie** [ShadowMario/FNF-PsychEngine#9359]
### Describe your problem here.

Heyo, all! I'm starting out simple with LUA by trying this script, which should've basically hid both the BF/Enemy icons.

```lua
function onCreate()
	precacheImage('icons/icon-blank')
	
	setProperty('iconP1', 'icons/icon-blank')
	setProperty('iconP2', 'icons/icon-blank')
end
```

Will that work?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
That will probably crash your game
```lua
function onCreatePost()
     setProperty('iconP1.visible', false)
end
```

**Comment by RowanSkie** [comment]
> That will probably crash your game
> 
> ```lua
> function onCreatePost()
>      setProperty('iconP1.visible', false)
> end
> ```

Yeah, it did actually. Heh.

**Comment by RowanSkie** [comment]
Before I close this, is there actually a list of variables that people can use? It seems to be a common question.

**Comment by frantastic24** [comment]
Wiki has a bunch of shortcuts, there is a pretty extensive haxe wiki online and you can find game specific variables in source

**Comment by RowanSkie** [comment]
Alright.
