### ISSUE TITLE
Charting State

### ISSUE THREAD

**Issue by Franczesko111** [ShadowMario/FNF-PsychEngine#9361]
### Describe your bug here.

When trying to port the V.S Carol Golf mod and loading the JSON for it the game broke! Pretty sure it's with the load JSON button. If not then I'm sorry.

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
editors/ChartingState.hx (line 2908)
editors/ChartingState.hx (line 428)
Prompt.hx (line 44)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/golf/golf-hard.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by ShadowMario** [comment]
Missing golf-hard.json.
