### ISSUE TITLE
a new error

### ISSUE THREAD

**Issue by salumod** [ShadowMario/FNF-PsychEngine#9366]
### Describe your bug here.

When I compile the game, an error appears
help

### Command Prompt/Terminal logs (if existing)

```bash
D:\psych engine V0.6.1\FNF-PsychEngine>lime test windows
source/PlayState.hx:67: characters 8-22 : Type not found : vlc.MP4Handler
source/FunkinLua.hx:342: lines 342-346 : Int should be Bool
source/FunkinLua.hx:342: lines 342-346 : ... For function argument 'f'
source/PlayState.hx:1498: characters 13-23 : Type not found : MP4Handler
source/PlayState.hx:984: characters 42-47 : Bool should be Null<Array<String>>
source/PlayState.hx:984: characters 42-47 : ... For optional function argument 'dialogueList'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing

**Comment by salumod** [comment]
> 尝试在cmd中，应该解决funkinlua的错误： `haxelib remove linc_luajit` `haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit`

It hasn't changed

**Comment by ShadowMario** [comment]
`haxelib remove hxCodec`
`haxelib install hxCodec`
