### ISSUE TITLE
Week 7 Cutscene is bugged.

### ISSUE THREAD

**Issue by EvcazinDeveloper** [ShadowMario/FNF-PsychEngine#9367]
### Describe your bug here.

As you start week 7 in ugh, the camera does not change to BF and Tankman's sprite's offsets are bugged.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't.

**Comment by ShadowMario** [comment]
No.
