### ISSUE TITLE
game suddenly crashes when i try to add events

### ISSUE THREAD

**Issue by LausivLol** [ShadowMario/FNF-PsychEngine#9368]
### Describe your bug here.

Erm uh, out of the many abrupt crashes this one's the most annoying, I literally try to add an event and the game suddenly just crashes
![image_2022-06-29_094918194](https://user-images.githubusercontent.com/108374339/176452831-edee75cd-a8cd-440b-8fb0-02f70db8b54a.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
Do you have any information about replicating this issue?

**Comment by BernardoGP4504** [comment]
click the dropdown menu again and select the event you want

**Comment by Dismatiyt** [comment]
Game is missing events propobly

**Comment by KillerAvecRage** [comment]
Try to find the image for an event in charting in the assets folder, because maybe this is what it's missing, you shouldn't touch the heart of Psych Engine, it works without (surprinsingly) but it's highly unstable

**Comment by frantastic24** [comment]
This is a month old and that's not even the issue, it's an oversight when the game tries to write data into notes
