### ISSUE TITLE
i have a few questions

### ISSUE THREAD

**Issue by DEV-idiotXD** [ShadowMario/FNF-PsychEngine#937]
### What is your question?

1. how do you make it so when you enter story it enters into a song instead of storymode?

2.how to make arrows move

3.how to use the  keyJustPressed(name:String) ex.
 keyJustPressed('accept')
           function whenacceptpressed()
cuz idk howto use it

**Comment by NotEpik** [comment]
i think the first question you need source code and change the script that make it go in story menu to join game in PlayState.hx i guess i also forgot in StoryModeState.hx i dont know i forgot i didnt code a source code for 1 month i don't know if i was correct but to be easy i think you go steal wait i mean check the stickman vs fnf source code in StoryModeState.hx and try to figure out the code and then add it in psych engine bla bla idk i never do it

**Comment by DEV-idiotXD** [comment]
> i think the first question you need source code and change the script that make it go in story menu to join game in PlayState.hx i guess i also forgot in StoryModeState.hx i dont know i forgot i didnt code a source code for 1 month i don't know if i was correct but to be easy i think you go steal wait i mean check the stickman vs fnf source code in StoryModeState.hx and try to figure out the code and then add it in psych engine bla bla idk i never do it

  ok but how do i use the keypressed functions?

**Comment by ShadowMario** [comment]
Go to line 218 of MainMenuState.hx and replace this:
![Screenshot_4](https://user-images.githubusercontent.com/44785097/141161587-073ace2c-a1de-494e-9d46-c85d7b8f6c67.png)

with this:
```haxe
var weekNumber:Int = 0;
var songsPlaylist:Array<String> = [
    'Satin Panties',
    'High',
    'Milf'
];

PlayState.storyPlaylist = songsPlaylist;
PlayState.isStoryMode = true;
selectedWeek = true;
PlayState.storyDifficulty = 2; //hard

PlayState.SONG = Song.loadFromJson(PlayState.storyPlaylist[0].toLowerCase() + diffic, PlayState.storyPlaylist[0].toLowerCase());
PlayState.storyWeek = weekNumber;
PlayState.campaignScore = 0;
PlayState.campaignMisses = 0;
LoadingState.loadAndSwitchState(new PlayState(), true);
```

**Comment by NotEpik** [comment]
> Go to line 218 of MainMenuState.hx and replace this: ![Screenshot_4](https://user-images.githubusercontent.com/44785097/141161587-073ace2c-a1de-494e-9d46-c85d7b8f6c67.png)
> 
> with this:
> 
> ```hx
> var weekNumber:Int = 0;
> var songsPlaylist:Array<String> = [
>     'Satin Panties',
>     'High',
>     'Milf'
> ];
> 
> PlayState.storyPlaylist = songsPlaylist;
> PlayState.isStoryMode = true;
> PlayState.storyDifficulty = 2; //hard
> 
> PlayState.SONG = Song.loadFromJson(PlayState.storyPlaylist[0].toLowerCase() + diffic, PlayState.storyPlaylist[0].toLowerCase());
> PlayState.storyWeek = weekNumber;
> PlayState.campaignScore = 0;
> PlayState.campaignMisses = 0;
> LoadingState.loadAndSwitchState(new PlayState(), true);
> ```

hey i try use it but i got this error

```
source/MainMenuState.hx:230: characters 89-95 : Unknown identifier : diffic
source/MainMenuState.hx:230: characters 89-95 : For function argument 'jsonInput'
```
