### ISSUE TITLE
Does the runHaxeCode() function only run C code?

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#9372]
### What is your question?

I don't know Haxe too well so I decided to ask...

**Comment by tylerandari12** [comment]
> You know there's a discord server right?

(Yes I know.)
If there's a discord server why are you here and not there?

Also there's a new function called `runHaxeCode()` and I was wondering what language is "Haxe code."

**Comment by impostor5875** [comment]
i've messed around with it a little, and basically one of the things you can do with it is run source code functions in lua
(this is not the only thing you can do, just one of the things i've found)

examples: `runHaxeCode('game.startCountdown();')` would start another countdown, and `runHaxeCode('game.loadAndSwitchState(new mainMenuState());')` is pretty fun to mess around with

**Comment by ImaginationSuperHero528** [comment]
> i've messed around with it a little, and basically one of the things you can do with it is run source code functions in lua
> (this is not the only thing you can do, just one of the things i've found)
> 
> examples: `runHaxeCode('game.startCountdown();')` would start another countdown, and `runHaxeCode('game.loadAndSwitchState(new mainMenuState());')` is pretty fun to mess around with

Oo0

**Comment by tylerandari12** [comment]
> ActionScript, you could've googled it

I dont know where to look up the question I asked but I'll look into action scripts...

**Comment by frantastic24** [comment]
You don't know how to type "haxe language"??

**Comment by ImaginationSuperHero528** [comment]
> 

@impostor5875 the switch menu state thing does not work in gives me an error.

**Comment by tylerandari12** [comment]
> You don't know how to type "haxe language"??

I know what Haxe is capable of compiling more than 1 language...
And I also know that Psyche Engine is made in what looks like C (correct me if I'm wrong tho)
So I was wondering if C was the only language usable with the `runHaxeCode()` function...

**Comment by tylerandari12** [comment]
I feel we'd be arguing on this all day and after rereading this I think the "haxe Code" im thinking of is `actionscript`
