### ISSUE TITLE
problem with the new update

### ISSUE THREAD

**Issue by terineos** [ShadowMario/FNF-PsychEngine#9375]
### Describe your bug here.

when I boot up psyche engine on the, as of 06/29/22, latest update, it crashes if i try to go to story mode, or freeplay. and it comes up with a bunch of errors but the one that, to me, sticks out the most is "Invalid char 93 at position 308"
![image](https://user-images.githubusercontent.com/108429816/176518632-705002c3-4fd4-48c8-895c-75f1bba183f3.png)
and yes I am on windows 7, so that could be the cause.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

all i did was add some mods into the mod folder

**Comment by frantastic24** [comment]
your json is broken

**Comment by ImaginationSuperHero528** [comment]
Re-download the mods or psych engine
