### ISSUE TITLE
When i open the debug menu it crush

### ISSUE THREAD

**Issue by marck500** [ShadowMario/FNF-PsychEngine#9376]
### Describe your bug here.

i've done a custom song, and in gameplay it doesn't read the chart.
Then i tried to open the debug menu and it crush with this message:"editor/ChartingState.hx (line 2524)   editor/ChartingState.hx (line 2110)   editor/ChartingState.hx (line 287)         flixel/FlxGame.hx (line 673)   flixel/FlxGame.hx (line 724)    flixel/FlxGame.hx (line 677)   flixel/FlxGame.hx (line 551)        openfl/event/EventDispatcher.hx (line 402)    openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

Please report this error to this page:https://github.com/ShadowMario/FNF-PsychEngine

>Crash Handler written by:sqirra-rng

please help me!

P.S.:This error happend only with my custom song, with the others is all normal.

### Command Prompt/Terminal logs (if existing)

```bash
editor/ChartingState.hx (line 2524)   editor/ChartingState.hx (line 2110)   editor/ChartingState.hx (line 287)         flixel/FlxGame.hx (line 673)   flixel/FlxGame.hx (line 724)    flixel/FlxGame.hx (line 677)   flixel/FlxGame.hx (line 551)        openfl/event/EventDispatcher.hx (line 402)    openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

Please report this error to this page:https://github.com/ShadowMario/FNF-PsychEngine

>Crash Handler written by:sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes

**Comment by frantastic24** [comment]
post the chart, it's useless if you don't
