### ISSUE TITLE
crashed randomly

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#9377]
### Describe your bug here.

the title :trollface: :trollface: :trollface: 

### Command Prompt/Terminal logs (if existing)

```bash
I was playing the .exe from the 'export' folder so, there was nothing to see (also my command prompt wasn't opened)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nah, just copied my mod from 0.5.2h (which was not using source)

**Comment by frantastic24** [comment]
Learn how to report a bug
