### ISSUE TITLE
no music/sound at all after closing in week editor

### ISSUE THREAD

**Issue by MarioLOLZ** [ShadowMario/FNF-PsychEngine#9378]
### Describe your bug here.

exactly as the title says. i was in week editor, finished the week editing so i closed the whole thing. after i opened it again it doesn't have any soud at all, no menu sounds, no background music, even no music in songs. i've even tried deleting the psych engine that i have, and replacing it, and even after that it still has no sound

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Unmute the game

**Comment by MarioLOLZ** [comment]
fuck

**Comment by frantastic24** [comment]
You can close this then
