### ISSUE TITLE
How do you a make a text that the player can type in what it says?

### ISSUE THREAD

**Issue by MTFutureWasTaken** [ShadowMario/FNF-PsychEngine#9379]
### Describe your problem here.

So basically... you know the mechanic from the Blantados Monochrome Monika Cover? Yeah, that but just the typeable text.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by frantastic24** [comment]
You asked how to do it, that script should give a good base to go off of

**Comment by MTFutureWasTaken** [comment]
Do you remember the submitter name? I can't really find anything.

**Comment by MTFutureWasTaken** [comment]
Nevermind. I remembered I had a port of Monochrome.
