### ISSUE TITLE
Multiple sprite sheets for a character

### ISSUE THREAD

**Issue by dombomb64** [ShadowMario/FNF-PsychEngine#9383]
### Describe your problem here.

I've made sprites for a character, but Adobe Animate says the maximum sprite sheet size can't fit it. Is it possible to use multiple sheets for a character like the Tricky mod does for Tricky's third form? If not, it's okay, because I can just split it into two characters, but I'd prefer if it were one.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment]
No

**Comment by dombomb64** [comment]
So, it's not possible? Okay, that's fine. I can't use a texture atlas because each unique frame is a different bitmap, but it's okay because I can just make multiple characters.
