### ISSUE TITLE
Can't die / No pause menu error

### ISSUE THREAD

**Issue by Valentino4572** [ShadowMario/FNF-PsychEngine#9384]
### Describe your bug here.

so uhh, I downloaded version 0.6.1 of the engine and when I tried to pause, it didn't work, the same with the R button, I couldn't die and go to the game over screen, I don't know if it happened only with me but the configured buttons are not the error here.

Addition Info:
- Used Windows 32 Bits
- Tested in FNF Songs and Mods song
- Don't edit anything in the build
- Don't use Lua

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ImaginationSuperHero528** [comment]
Double check if there are lua scripts.

**Comment by tylerandari12** [comment]
> Double check if there are lua scripts.

And make sure they return iether `Function_Stop` or `Function_Continue`...
