### ISSUE TITLE
Game crashing everytime Bf note is played

### ISSUE THREAD

**Issue by TheRealFunker** [ShadowMario/FNF-PsychEngine#9386]
### Describe your bug here.

Every time a not is played on Bf's side the game gives me a error message and crashes, i have no idea what's happening sience i can't open debug menu because no one happened me when I opened an issue, but im sure there werent any "wrong" notes or events so I don't have idea what's happening.
![Screenshot 2022-06-29 214054](https://user-images.githubusercontent.com/108310392/176568755-671da9cc-a4f0-42eb-8953-ad0a0b8afac0.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, not the build it self only with the mods folder.

**Comment by Wither362** [comment]
There isn’t gf

**Comment by frantastic24** [comment]
Did you by any chance delete the combo sprite
