### ISSUE TITLE
charactor creation

### ISSUE THREAD

**Issue by traucmahrs** [ShadowMario/FNF-PsychEngine#9387]
### Describe your bug here.

When i put the name of the icon the create me charactor its make appear an error message en close the game
![error message](https://user-images.githubusercontent.com/108441276/176573827-28860000-344a-43b8-817a-3fb1cab67c24.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i didnt touch anything

**Comment by Grape-Boy** [comment]
maybe your character's icon doesn't exist

**Comment by Wither362** [comment]
The character icon doesn’t exists, make sure that the icon image starts with `icon-`

**Comment by traucmahrs** [comment]
that the problems the icon exist and its start with icon-

**Comment by Wither362** [comment]
> that the problems the icon exist and the image name start with icon-

Is the image in images/icons ?

**Comment by traucmahrs** [comment]
Yes the icon is in the custom icon place

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :3 juillet 2022 13:10
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [ShadowMario/FNF-PsychEngine] charactor creation (Issue #9387)


that the problems the icon exist and the image name start with icon-

Is the image in images/icons ?
