### ISSUE TITLE
Bug song

### ISSUE THREAD

**Issue by AngiDou11** [ShadowMario/FNF-PsychEngine#9388]
### Describe your bug here.

When you die on any song it puts this:

### Command Prompt/Terminal logs (if existing)

```bash
GameOverSubstate.hx (line 106)
flixel/FlxState.hx (line 203)
flixel/FlxState.hx (line 212)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Death character is missing animations

**Comment by Grape-Boy** [comment]
make sure your death character has an animation called `firstDeath`
