### ISSUE TITLE
Source/CreditsState.hx:95: characters 46-47 : Expected , or ]

### ISSUE THREAD

**Issue by MatiMaassG** [ShadowMario/FNF-PsychEngine#9389]
### Describe your problem here.

I use the source code of 0.5.2h of Psych Engine
I edited CreditsState and i test but i got this error.
Someone can help me to fix this error?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, i edited CreditsState.hx, i edited the credits.

**Comment by CrusherMods** [comment]
Your missing a**,** or **]** somewhere near line 95.

**Comment by Wither362** [comment]
You miss a `]` in line 94

**Comment by RedstoneRuler** [comment]
It's kind of self-explanatory, isn't it?
