### ISSUE TITLE
bug in 0.6.1 if i go to custom credits

### ISSUE THREAD

**Issue by TarnSpill** [ShadowMario/FNF-PsychEngine#9393]
### Describe your bug here.

Paths.hx (line 352)
AttachedSprite.hx (line 27)
CreditsState.hx (line 133)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, like lua scripts

**Comment by TarnSpill** [comment]
bruh no, this will with clear psych enigne

**Comment by TarnSpill** [comment]
Ok i fixed this. just no edits files of main game

**Comment by frantastic24** [comment]
Not a bug, you are missing credit icons
