### ISSUE TITLE
How to make note move like thearchy?

### ISSUE THREAD

**Issue by bambitheone82112** [ShadowMario/FNF-PsychEngine#9396]
### Describe your problem here.

i was modcharting and i had a great idea  so i started making note move with math.sin but i runned into a problem, the bug log is:
mods/data/exasperation/exasperation.lua/ expected near noteTweenX

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by tylerandari12** [comment]
Also all the modcharts in Strident Crisis are open sourced. You can just take them from there...

https://github.com/ShadowMario/FNF-PsychEngine/files/9029536/script.zip

**Comment by CrusherMods** [comment]
> Waiting for the "OMG not dave and bambi again" tag...
> 
> Also you mean the Thearchy from Strident Crisis right?

actually bambitheone82112 got banned so
