### ISSUE TITLE
Setting Boyfriend's health to 0 with Lua softlocks the game and memory leaks.

### ISSUE THREAD

**Issue by AndrewIdot** [ShadowMario/FNF-PsychEngine#9397]
### Describe your bug here.

Basically, after setting Boyfriend's health to 0 in a song via a lua script (or I think lua notetypes? not sure), the game thinks Boyfriend IS dead (based on the onGameOver function behaviour happening), however the song continues, and you are unable to pause, alongside not being able to die. 
Towards the end of the song, the game starts memory leaking and after the song finishes, you're stuck in it, with the game still memory leaking.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by tylerandari12** [comment]
Try setting it to -500...

Also make sure all `onGameOver()` functions return iether `Function_Stop` or `Function_Continue`...

**Comment by ShadowMario** [comment]
Weird, i did it right now on a test lua script and it worked finna 👍
