### ISSUE TITLE
how to make enemy notes not glow

### ISSUE THREAD

**Issue by GMB-YT** [ShadowMario/FNF-PsychEngine#9400]
### Describe your problem here.

i tried to do but didn't work

![image](https://user-images.githubusercontent.com/92611799/176679076-6f36cc38-8a1b-4bb5-a84a-00646a030aac.png)
  like classic engine.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Grape-Boy** [comment]
go to `PlayState.hx`, find the line where `StrumPlayAnim` is called with the first argument being `true`
by hitting `Ctrl + F` on the keyboard, then typing "StrumPlayAnim(true" without the quotes, then, before `StrumPlayAnim`, just add `//`.
this will stop the function from being called and the notes won't glow

now compile your game and see if the notes still glow
