### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by TheFNFDummie** [ShadowMario/FNF-PsychEngine#9401]
### Describe your bug here.

Everytime time i change the oppenent to my custome one, it crashes
![Screenshot 2022-06-30 203722](https://user-images.githubusercontent.com/108473102/176691428-16c90096-533e-4316-b742-32de14df77e7.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by ShadowMario** [comment]
Crashing on `iconP2.animation.curAnim.curFrame = 0;`
It looks like you fucked iconP2 up.
