### ISSUE TITLE
Chart editor bug (playing in chart editor)

### ISSUE THREAD

**Issue by Daboss7173** [ShadowMario/FNF-PsychEngine#9402]
### Describe your bug here.

When pressing esc in the chart editor to play a song in it, sometimes the first note in the first measure played is missing :o

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No because I'm using lua to mod.

**Comment by Lorekeeper49** [comment]
This happens a lot to me too, I mainly just use the skip time feature now to test parts of a chart

**Comment by ImaginationSuperHero528** [comment]
Yeah that's on purpose @Daboss7173.
