### ISSUE TITLE
Error while compiling Psych Engine on Linux (Ubuntu)

### ISSUE THREAD

**Issue by SmileyFry52** [ShadowMario/FNF-PsychEngine#9403]
### Describe your problem here.

I'm trying to compile Psych Engine, but instead it gives me an error message right before it starts. I'd like a pointer to what library I might have installed wrong or forgot to install completely.

![image](https://user-images.githubusercontent.com/108477097/176707012-9dc57050-7a16-46c6-980d-89e1dc204a81.png)

".PsychEngine: error while loading shared libraries: libluajit-5.1.so.2: cannot open shared object file: No such file or directory"

Any help would be greatly appreciated!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited PlayState.hx, but it worked fine on my Windows laptop.

**Comment by Grape-Boy** [comment]
try to install/update [libluajit](https://packages.ubuntu.com/en/bionic/libluajit-5.1-2) (idk if this is a good source)
