### ISSUE TITLE
note tween isnt working

### ISSUE THREAD

**Issue by xav07theboi** [ShadowMario/FNF-PsychEngine#9404]
### Describe your problem here.

my note tween isnt working im trying to make it so the players notes go to the opponents original left arrow
location
and the oppenents arrows go to players original right arrow location
here is the code:
function onCreate()
wat = false
bruh = 0
originalopposx = false
originalplayposx = false
end
function onSongStart()
wat = true
end
function onUpdate(elapsed)
wait(wat == true)
bruh = bruh + 1
if bruh >= 8 then
bruh = 0
end
if not originalopposx == false and bruh == 7 then
originalopposx = getPropertyFromGroup('opponentStrums', bruh, 'x');
end
if bruh < 4 then
            notePosX = getPropertyFromGroup('opponentStrums', bruh, 'x');
            notePosY = getPropertyFromGroup('opponentStrums', bruh, 'y');
        else
            notee = bruh - 4;
            notePosX = getPropertyFromGroup('playerStrums', notee, 'x');
            notePosY = getPropertyFromGroup('playerStrums', notee, 'y');
        end
if not originalplayposx == false and bruh == 0 then
originalplayposx = getPropertyFromGroup('playerStrums', notee, 'x');
end
	if noteposX == originalplayposx and not originalopposx == false then
	noteTweenX('tagname', bruh, originalopposx, math.random(1, 10), 'quartInOut')
	elseif notePosX == originalopposx and not originalplayposx == false then
	noteTweenX('taname', bruh, originalplayposx, math.random(1, 10), 'circInOut')
	end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
It's fucking lua

**Comment by Lorekeeper49** [comment]
> > `wait()` isn't a thing
> > 
> > ```lua
> > function onSongStart()
> >      for i=0, 3 do
> >           noteTweenX(i, i, _G['defaultPlayerStrumX'..i], getRandomInt(1, 10), 'quartInOut')
> >           noteTweenX(i+4, i+4, _G['defaultOpponentStrumX'..i], getRandomInt(1, 10), 'circInOut')
> >      end
> > end
> > ```
> 
> 
> thats kade modcharting api tho

Well this isn't kade engine so you're gonna have to use something else

**Comment by frantastic24** [comment]
It's fucking lua.

**Comment by xav07theboi** [comment]
> It's fucking lua.

it is lua butengine

**Comment by xav07theboi** [comment]
> `wait()` isn't a thing
> 
> ```lua
> function onSongStart()
>      for i=0, 3 do
>           noteTweenX(i, i, _G['defaultPlayerStrumX'..i], getRandomInt(1, 10), 'quartInOut')
>           noteTweenX(i+4, i+4, _G['defaultOpponentStrumX'..i], getRandomInt(1, 10), 'circInOut')
>      end
> end
> ```

i will try that

**Comment by xav07theboi** [comment]
> 

thank you! i should be able to config this to work a little diffrent
