### ISSUE TITLE
Loading custom song in Story Mode or Freeplay causes an error to appear. (Psych Engine 0.6.1)

### ISSUE THREAD

**Issue by NewSajgonki** [ShadowMario/FNF-PsychEngine#9405]
### Describe your problem here.

When im trying to lauch a custom song from Story Mode or Freeplay this shows up:

![error pe1](https://user-images.githubusercontent.com/108466805/176712757-8fffcac5-442f-48ac-9c6c-940d4d3f1c75.png)
 
 This is my code:
 {"song":{"song":"npc-test","bpm":165.0,"needsVoices":true,"player1":"bf","player2":"noob","speed":2.3,"notes": [deleted the rest but normally it has whole blammed script {except the first one lol} bcos the rest are arrows wich are 1:47 minutes (time of blammed song) and my song is just only 1:00 minute
 (time of my song)]
  

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I simply made a map, menu map, character, menu character, copied the song from blammed and was about to recreate the chart because i got the Inst and Voices and their .ogg and also my character was already put in.

**Comment by frantastic24** [comment]
remove philly lights event from your chart

**Comment by frantastic24** [comment]
PHILLY LIGHTS❗❗❗❗

**Comment by NewSajgonki** [comment]
ok thanks
