### ISSUE TITLE
Dying makes u get an error and screen goes brrrrrrrrrrrrrrrrr

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#9406]
### Describe your bug here.

Basically when i pressed "R", the game instead of showing the deathscreen, it show this error:
<img width="705" alt="image" src="https://user-images.githubusercontent.com/102251392/176723096-f1d1411b-e715-4e17-8d84-e9be9d7b6f19.png">
I tried by missing the notes but, the error appeared again.

After u get the error, the game crashes, even the error appears in the non-builded psych engine.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I left it how it was (it means no)

**Comment by WilliamGaming12** [comment]
> Happens when your death screen character is missing animations

i got all of them, the three of them

**Comment by frantastic24** [comment]
what's the character, if it's bf his death animations are stored separately

**Comment by WilliamGaming12** [comment]
no it was by the caps, am so dumb

**Comment by frantastic24** [comment]
this can be closed then?

**Comment by tylerandari12** [comment]
> this can be closed then?

This is a rare phenomenon where they're so excited to go get they're thing to work that they forget to close the thing...

**Comment by ImaginationSuperHero528** [comment]
@WilliamGaming12 close this.
