### ISSUE TITLE
Transfer PyschEngine

### ISSUE THREAD

**Issue by KashperIsCool** [ShadowMario/FNF-PsychEngine#9407]
### Describe your problem here.

How Do I Transfer My PyschEngine Files To The New Version 0.6.1

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by NewSajgonki** [comment]
Just try downloading the newest version and delete the old one (or keep it if you want to)

**Comment by Lorekeeper49** [comment]
> Just try downloading the newest version and delete the old one (or keep it if you want to)

I'm pretty sure he has some added code that he wants in the new version
