### ISSUE TITLE
IDK what is this error

### ISSUE THREAD

**Issue by Galbio** [ShadowMario/FNF-PsychEngine#9408]
### Describe your bug here.

I was porting the Tabi mod and when I launch Genocide I got an error. And I don't think it's due to Lua (I don't use source code)
I've checked but there was the data, the song, the character, I haven't put the icon because I've changed the name of Berzerk Tabi's icon but otherwise I don't see any problem.
Here is a screenshot of the error

![image](https://user-images.githubusercontent.com/101997612/176746474-db8c9814-e45b-488c-97d9-6fa6e545a13d.png)

Hope the problem get fix in 0.6.2

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I've ported Tabi, otherwise no. I've put Lua because I'm forced I don't have a choice.

**Comment by frantastic24** [comment]
show lua scripts

**Comment by Galbio** [comment]
there is no lua script except for the stage but here it is



function onCreate()
   makeLuaSprite('bg','youhavebeendestroyed',-500,-300);
   addLuaSprite('bg',false);

   makeLuaSprite('table', 'overlayingsticks', -510, -230);
   addLuaSprite('table',false);

   makeLuaSprite('thing','glowyfurniture',-500,-310);
   addLuaSprite('thing',false);

   makeLuaSprite('boomdead','boomdead',350,410);
   addLuaSprite('boomdead',false);
end

**Comment by frantastic24** [comment]
your note texture xml is missing animations

**Comment by NewSajgonki** [comment]
i got the same error ngl

**Comment by Galbio** [comment]
oh ok
