### ISSUE TITLE
Stage

### ISSUE THREAD

**Issue by AverageFNFFan** [ShadowMario/FNF-PsychEngine#9409]
### Describe your bug here.

I have been trying to port eteled into psych engine and I came across a problem, when trying to add my stage this keeps on happening:

PlayState.hx (line 2455)
PlayState.hx (line 2306)
PlayState.hx (line 1054)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

If you can, please help. if you need my stage code here it is:

function onCreate()
	-- background shit
	makeLuaSprite('miichannel', 'miichannel', -600, -300);
	setScrollFactor('miichannel', 0.9, 0.9);

	makeAnimatedLuaSprite('miibuttons', 'miibuttons', -2050, -550);
	setScrollFactor('miibuttons', 1.0, 1.0);
	addAnimationByPrefix('miibuttons','stagecurtains','stagecurtains',24,false)

	addLuaSprite('miichannel', false);
	addLuaSprite('miibuttons', true);
	
	close(true); --For performance reasons, close this script once the stage is fully loaded, as this script won't be used anymore after loading the stage
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed menu bg and title screen and stuff but none of that is prompting my problem

**Comment by frantastic24** [comment]
Remove dadbattle spotlight from your chart events
