### ISSUE TITLE
Crashed which i in main menu

### ISSUE THREAD

**Issue by raindow05** [ShadowMario/FNF-PsychEngine#9410]
### Describe your bug here.

pls how fixed

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
MainMenuState.hx (line 116)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
how many times are you going to rename this

**Comment by raindow05** [comment]
how to fixed? where find these files

**Comment by frantastic24** [comment]
`assets/images/mainmenu`
