### ISSUE TITLE
LOL Null Object Reference

### ISSUE THREAD

**Issue by AlexTheCat15** [ShadowMario/FNF-PsychEngine#9411]
### Describe your bug here.

lol Null Object Reference still happens in 6.1. Not as much as 6.0, but still. Is there any problem?
PlayState.hx (line 2482)
PlayState.hx (line 2411)
PlayState.hx (line 1054)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only added other songs from mods, but some just cause this error

**Comment by frantastic24** [comment]
They added error logs for a reason

**Comment by AlexTheCat15** [comment]
> They added error logs for a reason

What error logs

**Comment by frantastic24** [comment]
where you saw the null object reference

**Comment by AlexTheCat15** [comment]
> where you saw the null object reference

In the game? I don't get it

**Comment by frantastic24** [comment]
the window that pops up when the game crashes, it literally tells you to post it here

**Comment by AlexTheCat15** [comment]
> the window that pops up when the game crashes, it literally tells you to post it here

And now? I wait for 6.2?

**Comment by AlexTheCat15** [comment]
> > it literally tells you to post it here

I already did

**Comment by AlexTheCat15** [comment]
> I already did

Or do you mean a photo of it

**Comment by frantastic24** [comment]
no that works, i was expecting it to be down here so i didn't see it
looks like you're trying to use philly glow outside of week 3, you can't do that

**Comment by AlexTheCat15** [comment]
> no that works, i was expecting it to be down here so i didn't see it looks like you're trying to use philly glow outside of week 3, you can't do that

Then what's the point of adding philly glow then?

**Comment by frantastic24** [comment]
for week 3?? the update notes literally state it's hardcoded

**Comment by AlexTheCat15** [comment]
> for week 3?? the update notes literally state it's hardcoded

Bruh then
