### ISSUE TITLE
How to change the exe icon

### ISSUE THREAD

**Issue by WinV-Bros** [ShadowMario/FNF-PsychEngine#9412]
### Describe your problem here.

i want to change the exe icon so it isn't the default one

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by blowerslol** [comment]
You can't change the icon in LUA. you have to use source code.

**Comment by Lorekeeper49** [comment]
> You can't change the icon in LUA. you have to use source code.

Doesn't changing `icon.ico` change the exe icon?

**Comment by blowerslol** [comment]
No, it won’t. I’ve tried to do that along time ago and it didn’t work. If you want to change the executable icon without source code, you have to use resource hacker or something like that.

**Comment by MTFutureWasTaken** [comment]
> You can't change the icon in LUA. you have to use source code.

umm... actually.... https://discord.com/channels/922849922175340586/922851578996744252/991726909668991036

**Comment by blowerslol** [comment]
> > You can't change the icon in LUA. you have to use source code.
> 
> umm... actually.... https://discord.com/channels/922849922175340586/922851578996744252/991726909668991036

you copied a random discord message?

**Comment by MTFutureWasTaken** [comment]
> > > You can't change the icon in LUA. you have to use source code.
> > 
> > 
> > umm... actually.... https://discord.com/channels/922849922175340586/922851578996744252/991726909668991036
> 
> you copied the link a random discord message?

it's a discord link to a message in the psych discord with the code to change the exe icon to the note you pressed

**Comment by MTFutureWasTaken** [comment]
> > > > You can't change the icon in LUA. you have to use source code.
> > > 
> > > 
> > > umm... actually.... https://discord.com/channels/922849922175340586/922851578996744252/991726909668991036
> > 
> > 
> > you copied the link a random discord message?
> 
> it's a discord link to a message in the psych discord with the code to change the exe icon to the note you pressed

demostration of the script by 900n1: (the og makes look like notes, so 900n1 modified it but whatever) https://www.youtube.com/watch?v=UuVf0lJu4yc

**Comment by blowerslol** [comment]
> > > > > You can't change the icon in LUA. you have to use source code.
> > > > 
> > > > 
> > > > umm... actually.... https://discord.com/channels/922849922175340586/922851578996744252/991726909668991036
> > > 
> > > 
> > > you copied the link a random discord message?
> > 
> > 
> > it's a discord link to a message in the psych discord with the code to change the exe icon to the note you pressed
> 
> demostration of the script by 900n1: (the og makes look like notes, so 900n1 modified it but whatever) https://www.youtube.com/watch?v=UuVf0lJu4yc

Alright, but that just changes it to the Notes you pressed, not an actual icon.

**Comment by BendyGaming0** [comment]
lime.app.Application.current.window.setIcon() can change the icon using a lime image (lime.graphics.Image) which can be loaded from a openfl bitmapdata (openfl.display.BitmapData) which can be loaded from a file (BitmapData.loadFile('my/path.png'))

so something like this can be used using hscript in lua

`Application.current.window.setIcon( Image.fromBitmapData( BitmapData.fromFile( Paths.modImage( 'myIcon.png' ) ) ) );`

**Comment by ImaginationSuperHero528** [comment]
Go into the art folder and edit icon16 to 64 and iconOG

**Comment by MTFutureWasTaken** [comment]
> > > > > > You can't change the icon in LUA. you have to use source code.
> > > > > 
> > > > > 
> > > > > umm... actually.... https://discord.com/channels/922849922175340586/922851578996744252/991726909668991036
> > > > 
> > > > 
> > > > you copied the link a random discord message?
> > > 
> > > 
> > > it's a discord link to a message in the psych discord with the code to change the exe icon to the note you pressed
> > 
> > 
> > demostration of the script by 900n1: (the og makes look like notes, so 900n1 modified it but whatever) https://www.youtube.com/watch?v=UuVf0lJu4yc
> 
> Alright, but that just changes it to the Notes you pressed, not an actual icon.

yeah, but if changed correctly it could be a normal icon script

**Comment by ImaginationSuperHero528** [comment]
> Go into the art folder and edit icon16 to 64 and iconOG

@WinV-Bros

**Comment by WinV-Bros** [comment]
> > You can't change the icon in LUA. you have to use source code.
> 
> umm... actually.... https://discord.com/channels/922849922175340586/922851578996744252/991726909668991036

can you send the script because I'm not in the server

**Comment by ImaginationSuperHero528** [comment]
> > > You can't change the icon in LUA. you have to use source code.
> > 
> > 
> > umm... actually.... https://discord.com/channels/922849922175340586/922851578996744252/991726909668991036
> 
> can you send the script because I'm not in the server

@WinV-Bros WTF I JUST TOLD YOU HOW BESIDES THEIR WAY MAKES IT SO YOU HAVE TO BE IN THE SONG

**Comment by MTFutureWasTaken** [comment]
> > > You can't change the icon in LUA. you have to use source code.
> > 
> > 
> > umm... actually.... https://discord.com/channels/922849922175340586/922851578996744252/991726909668991036
> 
> can you send the script because I'm not in the server
https://cdn.discordapp.com/attachments/922851578996744252/991726909761277992/funninotesonwindowicon.zip
if you want to have just one icon, you're either going to have to modify the script or the assets

**Comment by ImaginationSuperHero528** [comment]
> Go into the art folder and edit icon16 to 64 and iconOG

@WinV-Bros dude

**Comment by PatoFlamejanteTV** [comment]
> > > > You can't change the icon in LUA. you have to use source code.
> > > 
> > > 
> > > umm... actually.... https://discord.com/channels/922849922175340586/922851578996744252/991726909668991036
> > 
> > 
> > can you send the script because I'm not in the server
> 
> https://cdn.discordapp.com/attachments/922851578996744252/991726909761277992/funninotesonwindowicon.zip if you want to have just one icon, you're either going to have to modify the script or the assets

https://web.archive.org/web/20220726190158/https://cdn.discordapp.com/attachments/922851578996744252/991726909761277992/funninotesonwindowicon.zip

link found on wayback machine, the original discord link was DELETED!! PLEASE USE ANOTHER WEBSITES FOR HOSTING!!!!!!!!
