### ISSUE TITLE
How to change the Ratings data

### ISSUE THREAD

**Issue by AlexTheCat15** [ShadowMario/FNF-PsychEngine#9413]
### What is your question?

So in the 6.0 version changes, it says **_Ratings data can be changed through Lua_**. So, how do i do that? I want to see how so I can easily change them.

**Comment by frantastic24** [comment]
```lua
setProperty('ratingsData[0].image', 'image path')
```
change array for other ratings and image for other properties, check `Conductor.hx` for properties

**Comment by AlexTheCat15** [comment]
> ```lua
> setProperty('ratingsData[0].image', 'image path')
> ```
> 
> change array for other ratings and image for other properties, check `Conductor.hx` for properties

Where do I put the code in?

**Comment by BeastlyGhost** [comment]
https://cdn.discordapp.com/attachments/922851578996744252/983418835770155128/Ratings_Modifier.lua

**Comment by AlexTheCat15** [comment]
> https://cdn.discordapp.com/attachments/922851578996744252/983418835770155128/Ratings_Modifier.lua

Does this go into mods/scripts? Or another place?

**Comment by BeastlyGhost** [comment]
mods/scripts

**Comment by AlexTheCat15** [comment]
> mods/scripts

I'll try it, thanks

**Comment by AlexTheCat15** [comment]
It worked! Thanks!
