### ISSUE TITLE
help

### ISSUE THREAD

**Issue by bambitheone82112** [ShadowMario/FNF-PsychEngine#9415]
### Describe your problem here.

so i was coding through lua untill i type noteTweenD and then i frogot d is not a note move so i try and  the game says Die. i dont think this is a rare bug but i cant pause no closing game, dying, it has to play forever and im on a new pc so help. i think this is fake but i saw bf running because of the blood i dont think theres a bloody image on psych engine so help

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CrusherMods** [comment]
1. no proof
2. aint no fucking way thats real 💀

**Comment by ShadowMario** [comment]
Finally a good reason to ban you

**Comment by CrusherMods** [comment]
> Useless pull request maker & vandalised for a few Github page's (pe tutorial's & os engine)
> 
> 

and the actual fnf repo
