### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by MaxGamesYT** [ShadowMario/FNF-PsychEngine#9416]
### Describe your problem here.

There's a weird crash thing on 6.1
![Screenshot 2022-06-30 231930](https://user-images.githubusercontent.com/93287203/176817190-14c59bb2-bfdb-48b2-9df4-0322092278d3.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

Didnt edit anything

**Comment by frantastic24** [comment]
Icon file path is incorrect

**Comment by fr459** [comment]
Reality
