### ISSUE TITLE
Health Icon Dialogue Issue

### ISSUE THREAD

**Issue by PrincessI** [ShadowMario/FNF-PsychEngine#9417]
### Describe your bug here.

I'm using the Lua Psych Engine. I was working on my mod, and in the story mode dialogue, the healthbar and health icons are visible and cut into the dialogue box. Because of this, it also blocks some of the words. It only happens when my last song for the week is finished. Here's what it looks like:

![Screenshot (614)](https://user-images.githubusercontent.com/97416116/176827805-de3b41e9-99ef-4579-96b7-0e46e8af6705.png)

Is there a way to fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I did the normal procedure of adding dialogue cutscenes (download the script lua, placing it in the song's data folder, etc)

**Comment by NewSajgonki** [comment]
idk if its possible (probably is) but try making the icons and the icon bar invisible while the text box is shown

**Comment by Lorekeeper49** [comment]
> idk if its possible (probably is) but try making the icons and the health* bar invisible while the text box is shown

The icon tags are `iconP1` and `iconP2` respectively, so you can easily change those values, but I don't know the tag for the healthbar yet

**Comment by Meme1079** [comment]
It make's the healthBar, icons, and score invisible

```lua
function onCreatePost()
     setProperty('iconP1.visible', false)
     setProperty('iconP2.visible', false)
     setProperty('healthBar.visible', false)
     setProperty('healthBarBG.visible', false)
     setProperty('scoreTxt.visible', false)
end
```

**Comment by PrincessI** [comment]
> It make's the healthBar, icons, and score invisible
> 
> ```lua
> function onCreatePost()
>      setProperty('iconP1.visible', false)
>      setProperty('iconP2.visible', false)
>      setProperty('healthBar.visible', false)
>      setProperty('healthBarBG.visible', false)
>      setProperty('scoreTxt.visible', false)
> end
> ```

While this did work, it will make them invisible for the entire song and not just the dialogue cutscene, however. So I'll use this as a last resort. Thanks, though!

**Comment by frantastic24** [comment]
If only there was a way to, I don't know, change the value again?

```lua
setProperty('iconP1.visible', true)
```
Would you look at that

**Comment by PrincessI** [comment]
I got it all figured out now! (I'll leave this here for people in the future who need this)

You copy @Meme1079 's "function onCreatePost()" setProperty lines and paste them inside the script's "function onEndSong()" section. Here's my setup and the results:

![Screenshot (615)](https://user-images.githubusercontent.com/97416116/176941990-43752188-8051-4fbc-baf5-b3ed9008114e.png)
![Screenshot (617)](https://user-images.githubusercontent.com/97416116/176942000-e08e1d0d-75e0-4161-8e32-c1edf664a482.png)
