### ISSUE TITLE
My characters suddenly doesn't work

### ISSUE THREAD

**Issue by Galbio** [ShadowMario/FNF-PsychEngine#9420]
### Describe your bug here.

I was porting Tabi into psych. I wanted to unite the old et new version into one so I do both version in a different folder in mod
And when I finish both of them I start modifying some files name and moving the different icons, sprite sheet etc...
And from nowhere in the character editor the character disappear and there is error everywhere even though the folder with the xml and character is still present and hasn't changed. I try to play a song to see and I got this message error.

![image](https://user-images.githubusercontent.com/101997612/176870568-c2724f62-6748-44e8-ae1f-761fdd371ffc.png)

Help wanted pls

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

The build itself no... just the mod folder

**Comment by Moisloud** [comment]
THIS IS HAPPENING TO ME TO

**Comment by ShadowMario** [comment]
0.6.1 or 0.6.2?

**Comment by Mastercopper2346** [comment]
Add a 6 before the issue number :trollface:
