### ISSUE TITLE
What is the purpose of the "-loop" suffix at the end of some character animations?

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#9425]
### What is your question?

Certain character animations in the base engine have a `-loop` suffix at the end of them..

For example theres an `idle` animation and theres an `idle-loop` animation...

Whats the purpose of this suffix?

**Comment by Raltyro** [comment]
its for animations after idle or any animation ended,
when it ended, it switch to the loop animation

**Comment by tylerandari12** [comment]
Interesting...

Thanks :D
