### ISSUE TITLE
Week 7 "addition"

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#9427]
### What feature do you want to get added on the **base** engine?

As PE adds to EVERY WEEK something new, like, Philly Glow (Aka Blammed Lights), Dad Spotlight
I could also see something like that on that one "ascending" part of "Guns".
Of course, one could use either of them, but I just think, that it doesn't really fit the atmosphere of the warzone. But it really deserves some kind of "glow-up"

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by ShadowMario** [comment]
It doesn't need a glow up, it's already perfect.

**Comment by Mastercopper2346** [comment]
My guy took so long to get everything perfect
