### ISSUE TITLE
psych crash

### ISSUE THREAD

**Issue by someuser987** [ShadowMario/FNF-PsychEngine#9430]
### Describe your bug here.

i was trying to put a character but some kind of crash appeared, the character's death animation was on the spritesheet and when i pressed the reset key (i was testing the animation) this crash appeared:

Paths.hx (line 352)
Character.hx (line 164)
Boyfriend.hx (line 16)
GameOverSubstate.hx (line 53)
PlayState.hx (line 3224)
PlayState.hx (line 2991)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i didn't edit anithing related to the source code.

**Comment by ZeitHeld** [comment]
Do you have the death animation named correctly?
Is it in a character.json? (yes, death anims need it, ex. epiphany monika who has her own character & spritesheet for dying)
are xml & png named the same?

Otherwise, can you maybe show the character?

**Comment by Moisloud** [comment]
THIS IS HAPPENING TO ME TO

**Comment by someuser987** [comment]
this was on the 0.6.1 and the character is the CN Takeover boyfriend, and yes, i checked if the animations the xml and the .json.
