### ISSUE TITLE
How to make the camera follow the players when playing a note? (LUA)

### ISSUE THREAD

**Issue by bendyloq** [ShadowMario/FNF-PsychEngine#9436]
### What is your question?

(there is not much mystery)

**Comment by Mastercopper2346** [comment]
use search funtion-

**Comment by bendyloq** [comment]
> usa la funcion de busqueda-

and how?

**Comment by ImaginationSuperHero528** [comment]
> > usa la funcion de busqueda-
> 
> and how?

Ctrl + F
