### ISSUE TITLE
Unable to Pause/Die

### ISSUE THREAD

**Issue by Draconic-Hybrid** [ShadowMario/FNF-PsychEngine#9437]
### Describe your bug here.

So with the new update of 0.6, I learned that my scripts won't let me die (Resetting does nothing) nor will it let me pause. The thing that confuses me is that the game clearly registers both as actually happening (I have a script to change the window name when you pause or die), yet they... don't.

I saw "Major Lua Reworks" in the patch notes, could it be that? And if so, how should I rearrange my code?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, this is my downloaded build

**Comment by frantastic24** [comment]
Add `return Function_Continue` at the end of the function

**Comment by Raltyro** [comment]
^ do this for now

there a bug in psych where if a callback returns none beside Function_examplehere, it should defaults to Function_Continue and would continue anyway, but it mischeck as if its Function_Stop

**Comment by ShadowMario** [comment]
Use 0.6.2
