### ISSUE TITLE
Erro apertar em "Story Mode"

### ISSUE THREAD

**Issue by jpsannttos** [ShadowMario/FNF-PsychEngine#9438]
When entering the Psych Engine, then press "Story Mode". An error appears saying "StoryMenuState.hx (line 130)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught error: null object reference
Please report this bug on the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng"                        How can I solve it? This is a crash

[crash Psych Engine.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9032171/crash.Psych.Engine.txt)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
i think something is wrong with one of your week files

**Comment by BeastlyGhost** [comment]
um dos teus arquivos de week estão formatados incorretamente, só recrie eles pelo editor de weeks e deve funcionar

**Comment by Mastercopper2346** [comment]
What @BeastlyGhost Said:

one of your week files is formatted incorrectly, just recreate them through the weeks editor and it should work
