### ISSUE TITLE
Icons and runsGlobally error

### ISSUE THREAD

**Issue by JakeLeBOFFICIAL** [ShadowMario/FNF-PsychEngine#9439]
### Describe your bug here.

Okay, so I tried to make angry icons for Senpai and icons for BF holding GF, but for whatever reason 'runsGlobally' prevents them from working, and I have no idea why.

All I know is that it made me a very frustrated person.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
works fine here

**Comment by ShadowMario** [comment]
You're either lying or you don't know what the hell you're talking about
