### ISSUE TITLE
Ending cutscenes and where do I save dialogue picture and XML

### ISSUE THREAD

**Issue by ToBAYT** [ShadowMario/FNF-PsychEngine#944]
### What is your question?

Can I make ending cutscenes after the final song of the mod and if so, how and where do I save the dialogue png and XML

**Comment by Alexis412** [comment]
Don't mind me just making my first comment ever

**Comment by ShadowMario** [comment]
Dialogue picture and XML goes inside mods/images/dialogue/, which is also the same folder as of where the .json files
If you mean a video after the song ends: https://github.com/ShadowMario/FNF-PsychEngine/issues/230
