### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Fortfight** [ShadowMario/FNF-PsychEngine#9445]
### What is your question?

i dont have the folder preload do i just make the folder

**Comment by CrusherMods** [comment]
depends are you on source?

**Comment by Mastercopper2346** [comment]
“Preload only appears on source, so he’s on source

**Comment by frantastic24** [comment]
Except they literally said they don't have preload

**Comment by CrusherMods** [comment]
> “Preload only appears on source, so he’s on source

but he didnt say he was though
