### ISSUE TITLE
A ton of "not found" messages out of nowhere

### ISSUE THREAD

**Issue by NicklGames** [ShadowMario/FNF-PsychEngine#9446]
### Describe your problem here.

![image](https://user-images.githubusercontent.com/60806448/176989154-a5ef266b-7372-4813-85fc-4522775eef45.png)
i have absolutely no idea why that happening, yesterday it worked fine

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Paracosm-Daemon** [comment]
this is just haxe starting the language server lmao, either give it a minute to do its thing, or hit ctrl + shift + p to bring up visual studio code's palette and find this
![image](https://user-images.githubusercontent.com/98495978/176994990-0dbf3733-0ef5-4a4f-94d6-27c9ac678c10.png)

**Comment by Moisloud** [comment]
I think this is also happening to me

**Comment by Grape-Boy** [comment]
That's just a Visual Studio thing; it happens to me too. Like the reply above me said, give it some time and the errors will disappear.

**Comment by Wither362** [comment]
It happens sometimes, or you don’t have haxeflixel installed, or is normal, let it be like that

**Comment by Grape-Boy** [comment]
Don't forget to install Haxe/HaxeFlixel extensions to make coding easier.
