### ISSUE TITLE
character not working anymore

### ISSUE THREAD

**Issue by Moisloud** [ShadowMario/FNF-PsychEngine#9449]
### Describe your bug here.

I am adding a character when I go to debug and select the character it says "Uncaught object reference" Idk why it says this cuz I have fixed it multiple times and still doesn't work so I think there is a problem with something cuz this also happen when I was making a json so maybe there are some bugged stuff. 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Moisloud** [comment]
OH and also nvm I added a character so yeah I Did edit one thing in this build? If so, mention or summarize your changes.

**Comment by Wither362** [comment]
The character is missing an animation

**Comment by Moisloud** [comment]
"The character is missing an animation"
which animation

**Comment by frantastic24** [comment]
Can't tell if you don't show the log or the files, that's literally the whole point of reporting a bug

**Comment by Mastercopper2346** [comment]
@Wither362 that doesn’t matter
