### ISSUE TITLE
How do I change the place where the notes come from in the screen?

### ISSUE THREAD

**Issue by MTFutureWasTaken** [ShadowMario/FNF-PsychEngine#9450]
### Describe your problem here.

It's a simple question.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by Mastercopper2346** [comment]
Chart Editor

**Comment by MTFutureWasTaken** [comment]
> Chart Editor

No, I mean if I wanted to make the notes come from the top right, how could I do that?

**Comment by Grape-Boy** [comment]
> > Chart Editor
> 
> No, I mean if I wanted to make the notes come from the top right, how could I do that?

I don't know if it works yet, but you need to change the direction property of the strums or something like that. Check FunkinLua.hx for a function that has something to do with direction by using Ctrl + F.

**Comment by MTFutureWasTaken** [comment]
> > > Chart Editor
> > 
> > 
> > No, I mean if I wanted to make the notes come from the top right, how could I do that?
> 
> I don't know if it works yet, but you need to change the direction property of the strums or something like that. Check FunkinLua.hx for a function that has something to do with direction by using Ctrl + F.

I found this. "Lua_helper.add_callback(lua, "noteTweenDirection", function(tag:String, note:Int, value:Dynamic, duration:Float, ease:String)"

**Comment by Grape-Boy** [comment]
> I found this. \"Lua_helper.add_callback(lua, \"noteTweenDirection\", function(tag:String, note:Int, value:Dynamic, duration:Float, ease:String)\

That must be it, use the function in a script and the notes will come from a different direction. There's probably documentation available on the Psych Wiki. (on GitHub)

**Comment by MTFutureWasTaken** [comment]
> > I found this. "Lua_helper.add_callback(lua, "noteTweenDirection", function(tag:String, note:Int, value:Dynamic, duration:Float, ease:String)\
> 
> That must be it, use the function in a script and the notes will come from a different direction. There's probably documentation available on the Psych Wiki. (on GitHub)

Yeah, it's that. I tried on my script. Thanks.

**Comment by Grape-Boy** [comment]
> > > I found this. "Lua_helper.add_callback(lua, "noteTweenDirection", function(tag:String, note:Int, value:Dynamic, duration:Float, ease:String)\
> > 
> > That must be it, use the function in a script and the notes will come from a different direction. There's probably documentation available on the Psych Wiki. (on GitHub)
> 
> Yeah, it's that. I tried it on my script. Thanks.

No problem. By the way, I checked and there's no documentation yet.
