### ISSUE TITLE
a thing of the playstate

### ISSUE THREAD

**Issue by ModdedFNF** [ShadowMario/FNF-PsychEngine#9453]
### Describe your problem here.

when i try to compile psych 0.6.2, i have this error:
source/PlayState.hx:67: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1496: characters 13-23 : Type not found : MP4Handler
please tell me how to fix it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't edit anything, i just compile first the source without edits before code my shit

**Comment by Wither362** [comment]
> source/PlayState.hx:67: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1496: characters 13-23 : Type not found : MP4Handler

install it

**Comment by ShadowMario** [comment]
You downloaded the wrong version of hxCodec
