### ISSUE TITLE
Stage JSON

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#9454]
### What is your question?

I wanted to change the zoom of the stage, but then found something I was a bit confused at

`"directory": ""`

is that like for where the stage assets are saved at?
like in example

```
JSON:
"directory": "class"

Directory:
"MYMOD/images/class"
```

or how do I have to understand it like?

**Comment by frantastic24** [comment]
In vanilla tells the game where to look for week specific assets (making them inaccessible for everything else)
In mods, it does nothing

**Comment by BernardoGP4504** [comment]
yes, similar to this. It works as telling the game what folder (only in `assets/`) to look for the images for sprites
also change camera zoom by `"defaultZoom": `

**Comment by ShadowMario** [comment]
"directory" is used by vanilla weeks, normally you'd set it to "week6", "week4".
It allows using these folders inside assets/
