### ISSUE TITLE
Swap Section Bug

### ISSUE THREAD

**Issue by Galbio** [ShadowMario/FNF-PsychEngine#9455]
### Describe your bug here.

In the Chart Editor,the Swap Section option doesn't work and instead swap the section above the one selected,

Before :
![image](https://user-images.githubusercontent.com/101997612/177004239-6bc89c1a-87e8-4e88-b6d7-621b01a0430d.png)

After : 
![image](https://user-images.githubusercontent.com/101997612/177004257-2587e6a0-5b4a-4afd-b846-96b175880e90.png)

It's very annoying

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Mastercopper2346** [comment]
Why are there notes above it anyway

**Comment by Galbio** [comment]
I have no idea
