### ISSUE TITLE
How to show difficulty differently on free play with LUA?

### ISSUE THREAD

**Issue by MOON-on-GitHub** [ShadowMario/FNF-PsychEngine#9456]
### What is your question?

I don't mean this
![화면 캡처 2022-07-02 232247](https://user-images.githubusercontent.com/106433334/177004775-bc06c72a-dd92-47a6-8aa9-04f3748c2b80.png)
I just want to show normal to another text on free play for LUA.
like this
![화면 캡처 2022-07-02 232459](https://user-images.githubusercontent.com/106433334/177004834-de083c45-16df-4781-860b-407e900c25f2.png) 
![화면 캡처 2022-07-02 232607](https://user-images.githubusercontent.com/106433334/177004841-7d3d1b36-b3f8-4050-92ee-640da49c3c73.png)

**Comment by Meme1079** [comment]
You can't do that in lua

**Comment by ManMaster707** [comment]
You can't currently do it unless you do what you showed in the first image. (remeber that you can't do lowercase without editing the source code)
