### ISSUE TITLE
A song error 

### ISSUE THREAD

**Issue by osevendot-two** [ShadowMario/FNF-PsychEngine#9457]
### Describe your problem here.

I tried to port hard 2 break in this engine but this thing prompts up every time:

C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 105)
editors/ChartingState.hx (line 2882)
editors/ChartingState.hx (line 427)
Prompt.hx (line 44)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Any help on this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Mastercopper2346** [comment]
THATS NOT NEW

**Comment by Grape-Boy** [comment]
Hello fellow Cheeky enjoyer, I think that's an issue with spaces in the file's name and the folder's name.
