### ISSUE TITLE
Elements missing in stage

### ISSUE THREAD

**Issue by zuzumi-f** [ShadowMario/FNF-PsychEngine#9458]
### Describe your bug here.

Some elements does not appear in 0.6.2 build like:
- Courtains in Daddy Dearest and GF stage
- LimoDance in Mommy Mearest Week
- PixelGirls in Sempai Week

The build is the already compiled one, no the source one

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Disable low quality bozo

**Comment by zuzumi-f** [comment]
wait i didn't enable it
