### ISSUE TITLE
Add Stage Editor

### ISSUE THREAD

**Issue by LitUpYT123** [ShadowMario/FNF-PsychEngine#9459]
### What feature do you want to get added on the **base** engine?

Mostly an Idea than a suggestion, you make a stage editor that can modify the character's position and when you save the stage, it comes at as a .JSON file

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by frantastic24** [comment]
🤡

**Comment by Galbio** [comment]
Never propose Shadow Mario a stage editor.

**Comment by Galbio** [comment]
![image](https://user-images.githubusercontent.com/101997612/177008064-07843015-68c1-459d-a985-0a34bee4097e.png)
Close the issue while you can

**Comment by ManMaster707** [comment]
*insert audio of the king from clash royale saying **GRRR** *

(seriously though, can't you read? You failed the test AND requested somerthing that has been told not to do multiple times.)

**Comment by CrusherMods** [comment]
🍿 free popcorn while we wait for this to get closed

**Comment by Mastercopper2346** [comment]
Shadow Mario on is way to. ban this guy:
![94729E9C-3B1B-4553-860D-89C4E1BBB4A8](https://user-images.githubusercontent.com/101440491/177017193-b922c38c-1bce-4f4b-9f3d-c4a571a2a393.png)

**Comment by silvashp** [comment]
you failed the test

**Comment by Wither362** [comment]
> ### What feature do you want to get added on the **base** engine?
> Mostly an Idea than a suggestion, you make a stage editor that can modify the character's position and when you save the stage, it comes at as a .JSON file
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Useful feature

Really? Go to theoyeah engine for the stage editor and br8ng it back to psych engine

**Comment by CrusherMods** [comment]
> Shadow Mario on is way to ban this guy:
> 
> ![94729E9C-3B1B-4553-860D-89C4E1BBB4A8](https://user-images.githubusercontent.com/101440491/177017193-b922c38c-1bce-4f4b-9f3d-c4a571a2a393.png)
> 
> 

that photo is cap
he would have a minigun

**Comment by machonessiebaby** [comment]
how to get banned 101

**Comment by tylerandari12** [comment]
Run while you still can :O

Or get banned idk...

**Comment by tylerandari12** [comment]
> 

I didnt expect a legitimate answer :o

**Comment by tylerandari12** [comment]
> Shadow Mario on is way to ban this guy: ![94729E9C-3B1B-4553-860D-89C4E1BBB4A8](https://user-images.githubusercontent.com/101440491/177017193-b922c38c-1bce-4f4b-9f3d-c4a571a2a393.png)
![177017193-b922c38c-1bce-4f4b-9f3d-c4a571a2a393](https://user-images.githubusercontent.com/97060639/177051763-181410f7-f0ec-4ee7-85d1-a55dc1243de6.png)

**Comment by Wither362** [comment]
> Shadow Mario on is way to ban this guy: ![94729E9C-3B1B-4553-860D-89C4E1BBB4A8](https://user-images.githubusercontent.com/101440491/177017193-b922c38c-1bce-4f4b-9f3d-c4a571a2a393.png)
> ![177017193-b922c38c-1bce-4f4b-9f3d-c4a571a2a393](https://user-images.githubusercontent.com/97060639/177051763-181410f7-f0ec-4ee7-85d1-a55dc1243de6.png)

Oh, he seems friendly!
