### ISSUE TITLE
Trail for characters

### ISSUE THREAD

**Issue by joxu13v** [ShadowMario/FNF-PsychEngine#9460]
### What is your question?

How do i add a trail event to get ghost animations like in mid-fight masses using .lua

**Comment by ManMaster707** [comment]
A script like that is on the psych engine discord server, though I can't send you the link now, it's easy to find.

**Comment by Lorekeeper49** [comment]
![Screenshot_20220702-114452.png](https://user-images.githubusercontent.com/93066594/177012809-18054fe4-cdf3-4566-b85a-6f563f1ce83b.png)
This is what you're looking for (I don't know how to link to message)

**Comment by joxu13v** [comment]
where can I get it?

**Comment by joxu13v** [comment]
Where can I get the link to that server?

**Comment by Lorekeeper49** [comment]
> Where can I get the link to that server?

https://discord.gg/2ka77eMXDv

**Comment by tylerandari12** [comment]
https://discord.com/channels/922849922175340586/922851578996744252/985339093451960391

Youre welcome :D

**Comment by tylerandari12** [comment]
https://discord.com/channels/922849922175340586/922851578996744252/985339093451960391

(I dont think it went through the first time...)

**Comment by ImaginationSuperHero528** [comment]
I made an update for a script @ShadowMario made! [Click here for discord post](https://discord.com/channels/922849922175340586/922851578996744252/988516830048030730)

**Comment by ImaginationSuperHero528** [comment]
It's a lot better than the ghost animations thing

**Comment by ImaginationSuperHero528** [comment]
no offense to the creator of that script
