### ISSUE TITLE
How to layer a object above characters.. (lua stage)

### ISSUE THREAD

**Issue by AzzyDrezzy12** [ShadowMario/FNF-PsychEngine#9461]
### Describe your problem here.

How to make an object layered above the characters using lua (stage)?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment]
[It's on the wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Custom-Sprites-Functions#addluaspritetagstring-frontbool--false)
