### ISSUE TITLE
Character switch bug

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#9462]
### Describe your bug here.

when i use character switch event (at 00:49 into the song) even if i put GF, Dad or Bf: it only changes BF
but when i use the event in any other part of the song it works normally

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, pretty much just added two custom events

**Comment by Mastercopper2346** [comment]
Value 1: 
0: bf
1: dad
2: gf

Value 2: 
(Character name

**Comment by BernardoGP4504** [comment]
> Value 1: 0: bf 1: dad 2: gf
> 
> Value 2: (Character name

thanks
