### ISSUE TITLE
mechas, changing line of game pages and smthn other

### ISSUE THREAD

**Issue by neondev27** [ShadowMario/FNF-PsychEngine#9465]
### What is your question?

how i can add mechas, change pages of game's line  (ex. after press enter, it brings a cutscenes and opens key binding for one time before start) and how i can port it to unity?

**Comment by frantastic24** [comment]
What the fuck

**Comment by neondev27** [comment]
maybe it comes as fantastic but i need know it for make better mod for fnf in this engine

**Comment by Grape-Boy** [comment]
If you want to add mechanics, you could make a custom note type and/or a custom event. You need to learn a bit of lua to script these.
