### ISSUE TITLE
Dialogue Bug with Mac Build in "actions"

### ISSUE THREAD

**Issue by adamsaustria** [ShadowMario/FNF-PsychEngine#9466]
### Describe your bug here.

Basically everytime I try to play a song when adding a mods folder, the dialogue is buggy as in the song starts before dialogue is finsihed 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
This is a duplicate

**Comment by adamsaustria** [comment]
what do you mean duplicate

**Comment by CrusherMods** [comment]
someone alr made this issue

> what do you mean duplicate

**Comment by frantastic24** [comment]
Not the first issue about it

**Comment by adamsaustria** [comment]
i really want it to be fixed so bad because i really want to play mod without the issue of dialogue being buggy
