### ISSUE TITLE
Song loading

### ISSUE THREAD

**Issue by SuperSaiyanBoi** [ShadowMario/FNF-PsychEngine#9467]
### Describe your bug here.

Pressed Enter on the song and then this happen :

![Desktop Screenshot 2022 07 02 - 15 24 56 77](https://user-images.githubusercontent.com/108200494/177014133-a2462d5b-7b82-44d6-b728-7c96e7f09a2c.png)

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
FreeplayState.hx (line 307)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/cocao-(bside)/cocao-(bside)-easier.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not

**Comment by frantastic24** [comment]
Not a bug you literally typed the song name incorrectly bruh

**Comment by Wither362** [comment]
The song name is `cocoa` not `cocao`

**Comment by ZeitHeld** [comment]
cocao

**Comment by Raltyro** [comment]
cacao

**Comment by ShadowMario** [comment]
cocao

**Comment by DevCarl1** [comment]
damn fuck
