### ISSUE TITLE
"Hit causes Miss"

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#9468]
### What is your question?

I know that the `"Hurt Notes"` might have been easier to not press, but does it also apply to `Custom Notes`?
Like, I have notes that kill, and normally I wouldn't hit them at all. or just very very little.
I even have **video proof** _(but then don't mind the mechanic, focus on the bongo cat and the dark red notes. you can even go frame by frame if you want - psych 0.6.2 btw)_
So, instead of just trying to "nerf" the hurt notes **only**, it would be cool, if only those notes which have `"hitCausesMiss"` turned **true**. soft and hard coded ones-

_I would appreciate it_

-------------------------------

https://user-images.githubusercontent.com/76132257/177016995-d3b86ed9-2afe-4366-9e17-ac2bb63241ec.mp4

**Comment by frantastic24** [comment]
you can change their hitboxes

**Comment by ZeitHeld** [comment]
how?

**Comment by frantastic24** [comment]
`lateHitMult`/`earlyHitMult`

**Comment by ZeitHeld** [comment]
that must be new-
Is it in FunkinLua.hx?

**Comment by frantastic24** [comment]
no they're variables in Note.hx, earlyHitMult isn't new but the other one is

**Comment by ZeitHeld** [comment]
In that case, would I have to increase the late hit?

**Comment by frantastic24** [comment]
bigger multiplier = easier to hit late/early

**Comment by ZeitHeld** [comment]
I see-
thanks!
