### ISSUE TITLE
psych wont take my chart

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#9470]
### Describe your bug here.

i have the song files in the songs folder i have the week with the right name of the song and the chart json file is named and put where its meant to
but it keeps showing this
![errer](https://user-images.githubusercontent.com/83985038/177024869-db4a03f4-e497-4bac-9b73-39c41201a676.PNG)
s
im using thee precompiled version and have no coding experience

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Not a bug
Misspelled name, name has spaces or file is outright missing

**Comment by creeperkidking** [comment]
oh ye i 100% had spaces
thank you so much

**Comment by creeperkidking** [comment]
nvm it still wont work

**Comment by frantastic24** [comment]
Did you replace spaces in both the folder name and each chart file

**Comment by creeperkidking** [comment]
oh sorry i was redoing it over again i will come back if it still wont work :)

**Comment by Grape-Boy** [comment]
> oh sorry i was redoing it over again i will come back if it still wont work :)

Don't forget to close this issue once it's resolved

**Comment by creeperkidking** [comment]
ye i fixed it sorry
