### ISSUE TITLE
Random Mod Menu and Week Crash

### ISSUE THREAD

**Issue by Welcometodahub** [ShadowMario/FNF-PsychEngine#9473]
### Describe your bug here.

I've been using Psych Engine for some time and after a while, it started to give me this error while opening the mod menu:
![Screenshot (563)](https://user-images.githubusercontent.com/108602572/177026266-a561ef4e-708e-4e15-98ec-4eda17ec89b3.png)
It's kinda annoying, but not a major problem.

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2469)
PlayState.hx (line 2324)
PlayState.hx (line 1053)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added some mods into the Psych Engine's mod folder.

**Comment by frantastic24** [comment]
One of your JSON files is incorrectly formatted

**Comment by Welcometodahub** [comment]
> One of your JSON files is incorrectly formatted

Do you know which folder it would probably be in specifically or is it just a random JSON file related to Psych Engine?

**Comment by frantastic24** [comment]
If it happens in the mod menu then the only json loaded there is pack.json

**Comment by frantastic24** [comment]
The other error you posted is because dadbattle lights are only for dadbattle stage

**Comment by Welcometodahub** [comment]
> If it happens in the mod menu then the only json loaded there is pack.json
Do I have to add another json file in the same folder?

**Comment by frantastic24** [comment]
I just said the only json loaded is pack.json
Fix that file

**Comment by Welcometodahub** [comment]
> I just said the only json loaded is pack.json Fix that file

Ok thanks.
