### ISSUE TITLE
Color Tween Thing

### ISSUE THREAD

**Issue by YKoF-CALm** [ShadowMario/FNF-PsychEngine#9474]
### Describe your problem here.

Is there a way to revert a color change to a character? (As in, you change the character sprite to a certain color, then you want it to go back to normal)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing.

**Comment by FlintIshe** [comment]
may be no

**Comment by frantastic24** [comment]
`0xFFFFFFFF`

**Comment by YKoF-CALm** [comment]
> `0xFFFFFFFF`

This works. Thanks.
