### ISSUE TITLE
How do i add ghost animations to my characters?

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#9475]
### What is your question?

The title says it all.

**Comment by Grape-Boy** [comment]
You mean afterimages ?

**Comment by tylerandari12** [comment]
The ghost animation is for positioning your character...

**Comment by BendyGaming0** [comment]
Im pretty sure you're talking about the trail spirit leaves behind. that would be FlxTrail, you can use HScript with `runHaxeCode()` and `addHaxeLibrary()` to do this

**Comment by WilliamGaming12** [comment]
> Im pretty sure you're talking about the trail spirit leaves behind. that would be FlxTrail, you can use HScript with `runHaxeCode()` and `addHaxeLibrary()` to do this

And how do i basically use them, i just code in lua lmaoooo

**Comment by BendyGaming0** [comment]
`addHaxeLibrary('FlxTrail', 'flixel.addons.effects')`
`runHaxeCode('game.addBehindDad(new FlxTrail(game.dad, null, 4, 24, 0.3, 0.069));')`
you can change the values but id recommend referring to the HaxeFlixel api so you know what you are doing

**Comment by tylerandari12** [comment]
> `addHaxeLibrary('FlxTrail', 'flixel.addons.effects')` `runHaxeCode('game.addBehindDad(new FlxTrail(game.dad, null, 4, 24, 0.3, 0.069));')` you can change the values but id recommend referring to the HaxeFlixel api so you know what you are doing

Where could I see a list of things that can be done with `runHaxeCode()`?
Iy doesnt need to be a peoperly formatted thing it could just be a reference in the source code...

**Comment by BendyGaming0** [comment]
Basically it just runs Haxe code (HScript specifically) so anything you can do with source you (probably) can do with runHaxeCode()

if you don't know haxe or haxeFlixel you can refer to their documentations and apis (id also recommend looking at the HScript documentation)

**Comment by Grape-Boy** [comment]
> > `addHaxeLibrary('FlxTrail', 'flixel.addons.effects')` `runHaxeCode('game.addBehindDad(new FlxTrail(game.dad, null, 4, 24, 0.3, 0.069));')` you can change the values but id recommend referring to the HaxeFlixel api so you know what you are doing
> 
> wait but, where do i put these thingies?

Inside a script :
```haxe
function onCreatePost()
    addHaxeLibrary('FlxTrail', 'flixel.addons.effects')`
    runHaxeCode('game.addBehindDad(new FlxTrail(game.dad, null, 4, 24, 0.3, 0.069));')
end
```
I haven't tested this, yet.

**Comment by WilliamGaming12** [comment]
well i got an event 'bout it, from the spongebob parodies mod, thanks folks anyways!
