### ISSUE TITLE
song no longer loads anymore

### ISSUE THREAD

**Issue by JaceDankhover** [ShadowMario/FNF-PsychEngine#9477]
### Describe your problem here.

i didnt have any issues with my song loading before, but in some recent update, I can no longer load my song without getting a Null Object Reference error
![image](https://user-images.githubusercontent.com/43685280/177043247-739e8a66-8609-4e2b-aea8-2e9352769b73.png)
here is the song data (had to upload as a txt file, json isnt supported)
[shinzo-democracy.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9034901/shinzo-democracy.txt)

I tried using an older version of Psych just now, and it works fine in it.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing, used the most recent release.

**Comment by frantastic24** [comment]
Remove dadbattle spotlight event from your chart

**Comment by JaceDankhover** [comment]
it works, but why does dadbattle spotlight break the game? i could use it before and it worked fine.

**Comment by frantastic24** [comment]
It doesn't break the game, it's hardcoded for week 1 stage

**Comment by JaceDankhover** [comment]
so i guess he changed the ability for it to work on other stages, for some reason

**Comment by frantastic24** [comment]
It never worked in other stages

**Comment by JaceDankhover** [comment]
it did for me, before it was changed. i changed the code back for it to work on all stages, so now i can use the original events.json file
but thank you for telling me what the issue was, I was going insane wondering why it wasn't working.
