### ISSUE TITLE
randomized note positions

### ISSUE THREAD

**Issue by Matriniii** [ShadowMario/FNF-PsychEngine#9478]
### Describe your problem here.

I have a script that should change the position of the notes randomly but it puts them in the top corner instead, like this:
![image](https://user-images.githubusercontent.com/108286693/177047235-cdda5004-2315-418b-b88d-589bcd51f991.png)
my code:
![03 07 2022_16 54 36_REC](https://user-images.githubusercontent.com/108286693/177047444-3e19749d-a0c8-4198-a831-ed5bfe8309b6.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

added credit icons, thats it

**Comment by frantastic24** [comment]
You are supposed to close `_G[]` right after `..i`

**Comment by Matriniii** [comment]
ok, ill try now

**Comment by Matriniii** [comment]
it says unexpected symbol near [

**Comment by Matriniii** [comment]
line 4

**Comment by frantastic24** [comment]
What
I told you to close `_G` earlier, not move it?

**Comment by Matriniii** [comment]
oh, sry, im new to coding

**Comment by Matriniii** [comment]
where should it go?

**Comment by frantastic24** [comment]
`_G['defaultPlayerStrumX'..i]`

**Comment by Matriniii** [comment]
oh ok, thank you

**Comment by Matriniii** [comment]
IT WORKED, tysm

**Comment by frantastic24** [comment]
Don't forget to close this

**Comment by Matriniii** [comment]
oh yeah lol
