### ISSUE TITLE
Uhhh just tried to open freeplay and this happened

### ISSUE THREAD

**Issue by adedman** [ShadowMario/FNF-PsychEngine#9480]
### Describe your bug here.

I was on a compiled version of psych and opened freeplay and this happened

### Command Prompt/Terminal logs (if existing)

```bash
FreeplayState.hx (line 74)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Something is wrong with your week file
