### ISSUE TITLE
Idk with the source code

### ISSUE THREAD

**Issue by SG-ProBlue** [ShadowMario/FNF-PsychEngine#9481]
### Describe your problem here.

when I complie the build with the source code u know
the build it does not appear in the export folder, only the mods, assets, plugins and manifest folders are exported, not the program or game, this did not happen to me with other versions such as 0.5 or 0.52
I don;t know if it is a problem or something but I don't know I'm new in coding yeah

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i just export all with the source code, I didn't touch anything

**Comment by Raltyro** [comment]
```
lime build windows -64 -clean
```

make sure that it does not errors in the console nor stops
if it does, please screenshot it and show the error here

**Comment by SG-ProBlue** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/103392118/177228693-86f7ec52-1771-4470-abbf-8e79188d61f0.png)
I tried 3 times and it didn't work

**Comment by ShadowMario** [comment]
Duplicate.
Read the readme file.
