### ISSUE TITLE
Stage isn’t working

### ISSUE THREAD

**Issue by DevAntiSocial** [ShadowMario/FNF-PsychEngine#9485]
### Describe your bug here.

I’m on 0.6.0 and my stage isn’t loading as of now I have one thing in my stage file 

function onCreate()
    makeLuaSprite('Nu!Neon', 'Nu!Neon', 0, 100)
    addAnimationByPrefix('Nu!Neon', 'idle', 'Neon Idle', 24, true)
    playAnimation('Nu!Neon', 'idle', true)
    addLuaSprite('Nu!Neon', true)

    close(true)
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMario** [comment]
playAnim, not playAnimation
