### ISSUE TITLE
 How can I create achievements for completing weeks on different difficulties?

### ISSUE THREAD

**Issue by gamertigoxd** [ShadowMario/FNF-PsychEngine#9486]
### Describe your problem here.

Hello, I would like to know how to make achievements for completing a week in different difficulties, example: completing week 1 in hell difficulty gives you an achievement, then completing it in normal difficulty gives you another, something like that but with each week, if anyone knows can you help please I would appreciate it, I currently use version 0.4.2 of the psych engine (because it is at this moment where I understand some of the code)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Raltyro** [comment]
Only in Source, not lua btw

to do this you add a new array in Achievements.hx
make a new case in a switch statement in checkForAchievement function in Playstate.hx
Then add your own achievement variable here in endSong function in Playstate.hx
![image](https://user-images.githubusercontent.com/78720179/177064850-0df120c8-1fa5-4f6d-aebd-6344a714da3c.png)

**Comment by tylerandari12** [comment]
If you beat the last song of your week in a certain difficulty and in story mode, than give the achievement...
