### ISSUE TITLE
Agoti 的箭頭無法正常運作 Agoti's arrows don't work properly

### ISSUE THREAD

**Issue by louie1116** [ShadowMario/FNF-PsychEngine#9487]
### What feature do you want to get added on the **base** engine?

( Google Translate )
Agoti's arrows don't work properly

![image](https://user-images.githubusercontent.com/100325874/177062435-9e7aa072-aef6-4735-83fc-1765d2f124b7.png)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Raltyro** [comment]
Custom Arrows can be a little funky for Psyche
You have to fix yourself for that sorry

**Comment by tylerandari12** [comment]
That looks sick :0

**Comment by Mastercopper2346** [comment]
输入 xml 文件或查看是否可以在 note .hx 中修复（在源代码中）

**Comment by Grape-Boy** [comment]
XML issue

**Comment by ShadowMario** [comment]
Custom arrows made by editing Note Data normally have issues on Psych.
