### ISSUE TITLE
Arrow movement loop?

### ISSUE THREAD

**Issue by TheManwhoisdyinghere** [ShadowMario/FNF-PsychEngine#9488]
### Describe your problem here.

is there a way to make a modchart that loops over and over so i dont have to copy and paste for every curstep?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Raltyro** [comment]
```lua
function onStepHit()
	local sPerSec = curStep % 16
	
	if (sPerSec == 0) then
		-- your codes here
	elseif (sPerSec == 8) then
		-- your codes here
	end
end
```

**Comment by TheManwhoisdyinghere** [comment]
thank you
