### ISSUE TITLE
Dialogue Font

### ISSUE THREAD

**Issue by AgentF4Z** [ShadowMario/FNF-PsychEngine#9493]
### Describe your problem here.

Hi, just wondering, how do I change the font for dialogue? I found out how to change the font for normal font things but I dont know for the dialogue.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Raltyro** [comment]
you can't
you have to do it in source

**Comment by AgentF4Z** [comment]
damn
