### ISSUE TITLE
Song and chart not working

### ISSUE THREAD

**Issue by RubenDatOneBoi3446** [ShadowMario/FNF-PsychEngine#9494]
### Describe your bug here.

https://user-images.githubusercontent.com/108199247/177072615-8e11739d-d45d-44ba-b15d-6c91c6cabd89.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
You are playing on Android, this doesn't belong here

**Comment by RubenDatOneBoi3446** [comment]
> 

Mm.. oh well 
I mean it's still psych engine

**Comment by RubenDatOneBoi3446** [comment]
> > 
> 
> Mm.. oh well I mean it's still psych engine

I just need to figure how to fix this

**Comment by balt700beta20again** [comment]
what version are you using

**Comment by frantastic24** [comment]
> it's still psych engine

It's a fork, go report a bug there

**Comment by RubenDatOneBoi3446** [comment]
> what version are you using
6.2

**Comment by ShadowMario** [comment]
It's a fork.
Invalid issue.
