### ISSUE TITLE
how do i use this?

### ISSUE THREAD

**Issue by TheManwhoisdyinghere** [ShadowMario/FNF-PsychEngine#9495]
### Describe your problem here.

how do i use doTweenZoom(tag:String, vars:String, value:Dynamic, duration:Float, ease:String)?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Same as any other tween but instead of an object you type in a camera

**Comment by TheManwhoisdyinghere** [comment]
what

**Comment by Lorekeeper49** [comment]
> what
> can you give me a example
> 

Either `camHUD` `camGame` or `camOther`

**Comment by frantastic24** [comment]
The wiki literally has an example and a list of cameras
