### ISSUE TITLE
Animated Stages

### ISSUE THREAD

**Issue by StickMation** [ShadowMario/FNF-PsychEngine#9498]
### Describe your problem here.

So im trying to add an animated bg and when i add another animated sprite or normal sprite, it only shows the first animated sprite i added. 
`function onCreate()

 makeAnimatedLuaSprite('back','Emerald Zone/Wall',0,-400);
 addAnimationByPrefix('back','Walla','Wall',24,true);
 addLuaSprite('back',false);
 objectPLayAnimation('back','Walla',true);
 setScrollFactor('back',1,1);

 makeLuaSprite('floor','Emerald Zone/Ground',0,300);
 addLuaSprite('floor',false);
 setScrollFactor('floor',1,1);

 makeAnimatedLuaSprite('couch','Emerald Zone/cat',1820,300);
 addAnimationByPrefix('couch','The Cat','cat',24,true);
 addLuaSprite('couch',false);
 objectPLayAnimation('couch','The Cat',true);
 setScrollFactor('couch',1,1);

end

function onBeatHit()

end

function onStepHit()

end

function onUpdate()

end
`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I only edited the mainmenu, just to change the buttons locations

**Comment by frantastic24** [comment]
There is an uppercase L in objectPlayAnimation

**Comment by StickMation** [comment]
> There is an uppercase L in objectPlayAnimation

i feel like a dumbass but it works now so thank you
