### ISSUE TITLE
Problem Compile

### ISSUE THREAD

**Issue by MateoSorianoGi** [ShadowMario/FNF-PsychEngine#95]
C:\Users\Usuario\Downloads\FNF-PsychEngine-0.4\FNF-PsychEngine-0.4>lime test windows -debug
source/Achievements.hx:146: characters 3-71 : (camera : flixel.FlxCamera, value : Bool) -> Void should be Array<flixel.FlxCamera>
source/MainMenuState.hx:53: characters 40-47 : Expected expression

hi, how should i fix this? i fixed everything.

**Comment by ShadowMario** [comment]
Well, you didn't show me any piece of the code from MainMenuState/Achievements so it's impossible for me to figure out the issue.

**Comment by MateoSorianoGi** [comment]
ok. here.

MainMenuState Code:
FlxG.cameras.reset(camGame);
FlxG.cameras.add(camAchievement);
FlxG.cameras.setDefaultDrawTarget = [dynamic];
                                                                  ⬆
                                                             (this part is showing me red)

Achievements Code:
var cam:Array<flixel.FlxCamera> = FlxG.cameras.setDefaultDrawTarget;
                                ⬆
                        (this part too)
if(camera != null) {
cam = [camera];

**Comment by ShadowMario** [comment]
`var cam:Array<flixel.FlxCamera> = FlxG.cameras.setDefaultDrawTarget;`
You know that's not how you use setDefaultDrawTarget, right?

**Comment by MateoSorianoGi** [comment]
i dont think so or idk
