### ISSUE TITLE
Give event for loading video plz

### ISSUE THREAD

**Issue by ArtemB0Y** [ShadowMario/FNF-PsychEngine#9500]
### Describe your problem here.

i want make mechanic with loading video which will appear, i must have event for this

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TFLTV** [comment]
what do you mean 'i want make mechanic with loading video which will appear' dosen't make sense

**Comment by TheKitBoi** [comment]
[Video-Event.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/9041066/Video-Event.zip)

here
