### ISSUE TITLE
Moving Window Mid Song

### ISSUE THREAD

**Issue by KashperIsCool** [ShadowMario/FNF-PsychEngine#9501]
### Describe your problem here.

How Do I Make A Thing To Make The Window Move Mid Song Like Vs Bob (ik that vs bob is KE but there has too be a way, right?)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by tylerandari12** [comment]
> ![fucktard](https://user-images.githubusercontent.com/44785097/177198027-896b28c7-01ae-4b3b-845d-89bba6ce9787.png)
> 
> 

Light mode :O

**Comment by WilliamGaming12** [comment]
> ![fucktard](https://user-images.githubusercontent.com/44785097/177198027-896b28c7-01ae-4b3b-845d-89bba6ce9787.png)

This guy is using light mode lmaoo

**Comment by CrusherMods** [comment]
> > ![fucktard](https://user-images.githubusercontent.com/44785097/177198027-896b28c7-01ae-4b3b-845d-89bba6ce9787.png)
> 
> This guy is using light mode lmaoo

its an old screenshot lmao

**Comment by TonyTimee** [comment]
The Y:
setPropertyFromClass('openfl.Lib', 'application.window.y', 1000*math.sin(SineElap)/10+windowy)

The X:
setPropertyFromClass('openfl.Lib', 'application.window.x', 1000*math.cos(SineElap)/5+windowx)

either one make sure you put

```lua
local SineElap = 0;
SineElap = SineElap + (elapsed * 3)
```

**Comment by KashperIsCool** [comment]
@TonyTimee where do i put this?

**Comment by TonyTimee** [comment]
> 

```lua
local SineElap = 0;

function onUpdatePost(elapsed)
SineElap = SineElap + (elapsed * 3)
setPropertyFromClass('openfl.Lib', 'application.window.x', 1000*math.cos(SineElap)/5+windowx) --setPropertyFromClass('openfl.Lib', 'application.window.y', 1000*math.sin(SineElap)/10+windowy) for the Y
end
```

**Comment by KashperIsCool** [comment]
@TonyTimee where do i put it? is it a lua script? event? what and where do i put it???

**Comment by TonyTimee** [comment]
> @TonyTimee where do i put it? is it a lua script? event? what and where do i put it???

this is a lua script
put it in scripts, data, stages, etc

**Comment by KashperIsCool** [comment]
@TonyTimee Thank You It Works!, but is there a way to put it in a part of the song then stop it, and is there a way too make it faster?

**Comment by TonyTimee** [comment]
> @TonyTimee Thank You It Works!, but is there a way to put it in a part of the song then stop it, and is there a way too make it faster?

Reccomend Using A Step Hit And Locals

EX:

```lua
local SineElap = 0;
local windowX = false;
local windowY = false;

function onCreate()
    windowy = getPropertyFromClass("openfl.Lib", "application.window.y")
    windowx = getPropertyFromClass("openfl.Lib", "application.window.x")
end

function onStepHit()
if curStep == 11 then
windowX = true;
windowY = false;
end
if curStep == 22 then
windowX = false;
windowY = true;
end
if curStep == 33 then
windowX = true;
windowY = true;
end
if curStep == 44 then
windowX = false;
windowY = false;
end
end

function onUpdatePost(elapsed)
    SineElap = SineElap + (elapsed * 3)
if windowX == true then
        setPropertyFromClass('openfl.Lib', 'application.window.x', 1000*math.cos(SineElap)/10+windowx)
end
if windowY == true then
        setPropertyFromClass('openfl.Lib', 'application.window.y', 1000*math.sin(SineElap)/10+windowy)
end
end
```

making it look faster im not sure


note give creds to OfficialCB not me
comment that issue/questions [here](https://gamebanana.com/tuts/15095)

**Comment by KashperIsCool** [comment]
@TonyTimee Bro I LOVE YOU, how would you use "minimized:Bool" ?
