### ISSUE TITLE
Wavy stage code

### ISSUE THREAD

**Issue by Doodikhaldi21** [ShadowMario/FNF-PsychEngine#9502]
### Describe your bug here.

When I was doing the wavy stage I got problem when I did lime test windows and here is my playstate

I can't send playstate but you can add my discord to send it .𝑝𝑛𝑔#6506

I will use google drive soo u can download the playstate and if you fixed that send me google drive link download

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\user\Desktop\Hard rage source>lime test windows
source/PlayState.hx:465: characters 7-10 : Missing ;
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited playstate trying to add wavy stage

**Comment by Doodikhaldi21** [comment]
Wait a minute I will give download

**Comment by Doodikhaldi21** [comment]
here https://drive.google.com/file/d/1DuQFKONoZHtMrx3Yfo6aaOuJPKFHuNH7/view?usp=sharing

**Comment by frantastic24** [comment]
The error quite literally tells you what you need to fix and in which line
Also don't fucking report a bug YOU caused

**Comment by Doodikhaldi21** [comment]
bro it says missing ; i already putted that

**Comment by TheKitBoi** [comment]
> bro it says missing ; i already putted that

where U ASS

**Comment by frantastic24** [comment]
If the error is still there you clearly did it wrong
