### ISSUE TITLE
Blend Modes dont work

### ISSUE THREAD

**Issue by AshoXD** [ShadowMario/FNF-PsychEngine#9503]
### Describe your bug here.

I add a sprite thats literally a white cube png, and i did setBlendMode('shoe', 'invert') (the sprite is called shoe), but in game, it just doesnt works

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Itz-Miles** [comment]
After looking at the newest FunkinLua, the blend modes are there and functioning.
```
function blendModeFromString(blend:String):BlendMode {
		switch(blend.toLowerCase().trim()) {
			case 'add': return ADD;
			case 'alpha': return ALPHA;
			case 'darken': return DARKEN;
			case 'difference': return DIFFERENCE;
			case 'erase': return ERASE;
			case 'hardlight': return HARDLIGHT;
			case 'invert': return INVERT;
			case 'layer': return LAYER;
			case 'lighten': return LIGHTEN;
			case 'multiply': return MULTIPLY;
			case 'overlay': return OVERLAY;
			case 'screen': return SCREEN;
			case 'shader': return SHADER;
			case 'subtract': return SUBTRACT;
		}
		return NORMAL;
	}
```
You might want to explain/show why you named your graphic `shoe`, if the callbacks aren't the issue. Maybe blend modes don't work on `makeGraphic()` for all I know, I think it's an error somewhere in your script though.

**Comment by frantastic24** [comment]
some of them just don't seem to work but i don't think it's an issue with game

**Comment by ShadowMario** [comment]
Haxe issue.

**Comment by AshoXD** [comment]
Wait so i have to put the graphic name, or the sprite name?
Shoe is the name of the sprite
