### ISSUE TITLE
I cant test my songs for my mod :(

### ISSUE THREAD

**Issue by vocodexxcalimetalrapha** [ShadowMario/FNF-PsychEngine#9504]
### What needs to be documented?

![q](https://user-images.githubusercontent.com/108695018/177209661-a91bdee3-52f0-44ba-9fd3-5ac24f515b8f.png)

**Comment by CrusherMods** [comment]
this should go in help wanted not documentation!

**Comment by SrtHero278** [comment]
![image](https://user-images.githubusercontent.com/93018286/177211260-85869427-92a6-4629-9238-13534f0e476b.png)
`-normal` shouldn't normally be there. make sure you typed in `Normal` (case sensitive) correctly in the week's json.

**Comment by vocodexxcalimetalrapha** [comment]
THANKS

**Comment by BeastlyGhost** [comment]
close the issue
