### ISSUE TITLE
Botplay for Lua code

### ISSUE THREAD

**Issue by zeadd21g1233** [ShadowMario/FNF-PsychEngine#9505]
### What is your question?

how to make botplay dodge

or make botplay attack in mid song

i have everything

just i want to know how to enable botplay

something like this

(this code doesn't work)
if (Botplay == true)
{
Dodged = true;
}
the mechainc for Indie cross mechanic
cuphead 
i made all mechaincs for cuphead
i want how to make codes for botplay
make him like attack or dodge 
if curStep == 40 then

if Botplay  == true then
Attack = true;
end
end

**Comment by KutikiPlayz** [comment]
use `getProperty('cpuControlled')` instead of botplay

**Comment by zeadd21g1233** [comment]
hm like that

if canDodge == true and getProperty('cpuControlled') and keyJustPressed('space') then
   Dodged = true;
   canDodge = false  
end
and then i play game botplay dies

**Comment by frantastic24** [comment]
Now you're telling the code to force the player to have botplay on
Use an `or` condition

**Comment by zeadd21g1233** [comment]
Okay thanks the code work perfectuly
