### ISSUE TITLE
Can't open the engine at all

### ISSUE THREAD

**Issue by PixelatedLuisDev** [ShadowMario/FNF-PsychEngine#9506]
### Describe your bug here.

I'm using version 6.2, and I tried to open the engine but instead it crashed showing this error:

[lime.utils.Preloader] ERROR: There is no asset library with an ID of "week7"

My guess is that some week 7 files could be missing from the build. I did not delete the .zip while things were being downloaded, so i'm unsure what really happened with the files. I'll try and re-download the build and see what happens.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Problem with your files, either missing files in assets or in manifest
