### ISSUE TITLE
FUNCTION ONBEATHIT DOESN'T WORK

### ISSUE THREAD

**Issue by Sebasyn0se** [ShadowMario/FNF-PsychEngine#951]
### What is your question?

you told me that i need to add the function beathit to sync the animated bg characters with the music, but the characters dont appear lol, here you have the code, please tell me what im writing bad.

function onCreate()
	
	if not lowQuality then
		
		makeLuaSprite('classroomcloset', 'classroomcloset', -650, -600);
		setLuaSpriteScrollFactor('classroomcloset', 0.9, 0.9);
		scaleObject('classroomcloset', 1.15, 1.15);
		
		makeLuaSprite('classroombg', 'classroombg', -650, -600);
		setLuaSpriteScrollFactor('classroombg', 0.9, 0.9);
		scaleObject('classroombg', 1.15, 1.15);

		makeLuaSprite('classroomdesks', 'classroomdesks', 0, 200);
		setLuaSpriteScrollFactor('classroomdesks', 0.9, 0.9);
		scaleObject('classroomdesks', 1.15, 1.15);

		function onBeathit()

			makeAnimatedLuaSprite('yuri', 'yuri', 200, 160);
			addAnimationByPrefix('yuri', 'Idle', 'Yuri BG', 24, true);
			setLuaSpriteScrollFactor('yuri', 0.9, 0.9);
			scaleObject('yuri', 0.7, 0.7);

			makeAnimatedLuaSprite('sayori', 'sayori', 1200, 250);
			addAnimationByPrefix('sayori', 'Idle', 'Sayori BG', 24, true);
			setLuaSpriteScrollFactor('sayori', 0.9, 0.9);
			scaleObject('sayori', 0.7, 0.7);

		end

	end

	addLuaSprite('classroomcloset', false);
	addLuaSprite('classroombg', false);
	addLuaSprite('classroomdesks', false);
	addLuaSprite('yuri', false);
	addLuaSprite('sayori', false);
	
	close(true); 
end

![test-ddlc-bg lua - Visual Studio Code 10_11_2021 13_50_13](https://user-images.githubusercontent.com/93066244/141156702-1c3b7562-3dbd-49db-94be-28d34beb5a02.png)

**Comment by ShadowMario** [comment]
It's `onBeatHit`, not `onBeathit`

Plus you can't use an issue inside another issue...

**Comment by Sebasyn0se** [comment]
it still not working

**Comment by DEV-idiotXD** [comment]
> it still not working

boi at the end put ()
