### ISSUE TITLE
Can you add custom var keys from playstate to lua

### ISSUE THREAD

**Issue by zeadd21g1233** [ShadowMario/FNF-PsychEngine#9510]
### What is your question?

i made custom var key

using

private var debugKeysCharacter:Array<FlxKey>;
and im add 
private var TestKey:Array<FlxKey>;

and im add

TestKey = ClientPrefs.copyKey(ClientPrefs.keyBinds.get('Test'));

ican port key to lua ?

like i go to controls options and change custom key and change in lua

**Comment by ShadowMario** [comment]
no
