### ISSUE TITLE
windows.h error

### ISSUE THREAD

**Issue by Elstanderweon** [ShadowMario/FNF-PsychEngine#9511]
### Describe your bug here.

always when I try to compile the game I get the windows.h error and I don't know what it is :(

### Command Prompt/Terminal logs (if existing)

```bash
lime test windows -debug
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no no edite nada

**Comment by WilliamGaming12** [comment]
I think it's a problem with Haxe or with Visual Studio 2019
