### ISSUE TITLE
Custom Icons refuse to load

### ISSUE THREAD

**Issue by Roselyn393** [ShadowMario/FNF-PsychEngine#9512]
### Describe your bug here.

When getting an icon onto the character's healthbar like in the character editor/elsewhere a screen pops up saying psych has crashed

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/FlxGraphic.hx (line 617)
flixel/FlxSprite.hx (line 405)
HealthIcon.hx (line 45)
editors/ChartingState.hx (line 2457)
editors/ChartingState.hx (line 539)
FlxUIDropDownMenuCustom.hx (line 500)
FlxUIDropDownMenuCustom.hx (line 361)
flixel/ui/FlxButton.hx (line 521)
flixel/addons/ui/FlxUITypedButton.hx (line 1172)
flixel/addons/ui/FlxUIButton.hx (line 362)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

**Comment by ShadowMario** [comment]
Thank you for giving no information about your actual healthicon or whatsoever 👍

**Comment by BernardoGP4504** [comment]
maybe you named the png for the icon wrong. All icons' images must include a `icon-` before the actual icon image name
or the file must be missing

**Comment by frantastic24** [comment]
> must include a `icon-`

They don't

**Comment by Lorekeeper49** [comment]
> > must include a `icon-`
> 
> They don't 

Last I checked they do, could you show an example of the icons working without that prefix?

**Comment by frantastic24** [comment]
When even was the last time you checked
This has been a thing since like 0.4

**Comment by Lorekeeper49** [comment]
> When even was the last time you checked
> This has been a thing since like 0.4

0.6.2 actually, though I never even bothered to test that because I didn't want to know what would happen

**Comment by Roselyn393** [comment]
turns out the icon can't be any bigger than 350 by 150 or psych will crash

**Comment by frantastic24** [comment]
Curious because I have a 400x167 and 365x180 icons and they work fine

**Comment by Roselyn393** [comment]
must just be mine then
