### ISSUE TITLE
Stopping the countdown can break onCreate()

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [ShadowMario/FNF-PsychEngine#9513]
### Describe your bug here.

Basically, I discovered that if a script prevents the countdown from starting, other scripts that use onCreate will break those scripts.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No Base Download

**Comment by perngjiafu** [comment]
put it on data lmao

**Comment by ImaginationSuperHero528** [comment]
> put it on data lmao

?? Dude it's in general!

**Comment by ShadowMario** [comment]
No.
