### ISSUE TITLE
Error after title screen

### ISSUE THREAD

**Issue by Teddy0008** [ShadowMario/FNF-PsychEngine#9516]
### Describe your problem here.

I get an error after the game tries to load the main menu (it cannot do it)
![image](https://user-images.githubusercontent.com/85173021/177260146-8b3e38b8-f566-451f-a17c-541618c3e2eb.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by machonessiebaby** [comment]
you broke something i have done this before
