### ISSUE TITLE
Funkin Lua giving errors dispite not being edited

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#9519]
### Describe your bug here.

funkin lua keeps giving me 
![image](https://user-images.githubusercontent.com/56323671/177354931-ad1d98e3-d31a-4c90-ac2c-5fe0c3cd18d8.png)
these errors and i never touched that i only touched mods folder and the playstate folder for ratings

### Command Prompt/Terminal logs (if existing)

```bash
source/FunkinLua.hx:342: lines 342-346 : Int should be Bool
source/FunkinLua.hx:342: lines 342-346 : ... For function argument 'f'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

playstate mods folder

**Comment by frantastic24** [comment]
Because you didn't install the new luajit

**Comment by machonessiebaby** [comment]
> Because you didn't install the new luajit

i had no idea it changed weird
