### ISSUE TITLE
onPause breaking the pause function

### ISSUE THREAD

**Issue by LieutenantJoe** [ShadowMario/FNF-PsychEngine#9521]
### Describe your bug here.

Using any LUA code that has onPause as a function disables pausing for some reason. Commenting out the function and any code within it reenables pausing, but this screws over anyone who wants something to happen on pause.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, externally (Adding a script with an onPause function)

**Comment by frantastic24** [comment]
`return Function_Continue`
