### ISSUE TITLE
how to fix this crash

### ISSUE THREAD

**Issue by Ari-bs** [ShadowMario/FNF-PsychEngine#9523]
### Describe your bug here.

cras
[PsychEngine_2022-07-05_19'41'04.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9048418/PsychEngine_2022-07-05_19.41.04.txt)
h

### Command Prompt/Terminal logs (if existing)

```bash
Note.hx (line 124)
PlayState.hx (line 2353)
PlayState.hx (line 1053)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

how to fix
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i ported songs but

**Comment by adamsaustria** [comment]
i know its doing the same thing with me

**Comment by tylerandari12** [comment]
Somethings wrong with your notes...

If the song your porting has different note skins than the normal ones thats your problem...

**Comment by Ari-bs** [comment]
> Somethings wrong with your notes...
> 
> If the song your porting has different note skins than the normal ones thats your problem..,

wait, you mean if i changed the color notes in the options? (also i didn't add any special notes)

**Comment by tylerandari12** [comment]
> > Somethings wrong with your notes...
> > If the song your porting has different note skins than the normal ones thats your problem..,
> 
> wait, you mean if i changed the color notes in the options? (also i didn't add any special notes)

No lol...

I looked in the source code where it said something happened and it said it had a problem loading the notes...
"null object reference" means that somethings not there whether it be an animation in the XML or a nonexistent image...
