### ISSUE TITLE
.VBS and .BAT question

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#9529]
### What is your question?

can I load a .vbs or .bat file. (how do you load other files)

**Comment by tylerandari12** [comment]
the closest thing to loading theese things would be `getTextFromFile()` but I dont thinks thats what your looking for...

**Comment by TFLTV** [comment]
> the closest thing to loading theese things would be `getTextFromFile()` but I dont thinks thats what your looking for...

this popped up and jumpscared me lol

**Comment by TFLTV** [comment]
> the closest thing to loading theese things would be `getTextFromFile()` but I dont thinks thats what your looking for...

btw is this lua?

**Comment by tylerandari12** [comment]
> > the closest thing to loading theese things would be `getTextFromFile()` but I dont thinks thats what your looking for...
> 
> this popped up and jumpscared me lol



> > the closest thing to loading theese things would be `getTextFromFile()` but I dont thinks thats what your looking for...
> 
> btw is this lua?

yea

no clue how to do source

**Comment by TFLTV** [comment]
> getTextFromFile()

how do I specify which file im gonna load (using 0.5.2 + the thing im trying to load is 'errork.vbs')

**Comment by tylerandari12** [comment]
> > getTextFromFile()
> 
> how do I specify which file im gonna load (using 0.5.2 + the thing im trying to load is 'errork.vbs')

Where's the file located?

If you just stuck it into the mods folder youd need to do `getTextFromFile("errork.vbs")` which will return the contents of the file in text form...

if its in a modpack youd need to do  `getTextFromFile("(mod name here)/errork.vbs")`.

**Comment by tylerandari12** [comment]
To make it somple the base folder is the mods folder...

**Comment by TFLTV** [comment]
> > > getTextFromFile()
> > 
> > 
> > how do I specify which file im gonna load (using 0.5.2 + the thing im trying to load is 'errork.vbs')
> 
> Where's the file located?
> 
> If you just stuck it into the mods folder youd need to do `getTextFromFile("errork.vbs")` which will return the contents of the file in text form...
> 
> if its in a modpack youd need to do `getTextFromFile("(mod name here)/errork.vbs")`.

1. inside the data folder for the song
2. so does that fix my problem?
3. I don't use different mod folders to make it easier to mod (with source)

**Comment by tylerandari12** [comment]
> > > > getTextFromFile()
> > > 
> > > 
> > > how do I specify which file im gonna load (using 0.5.2 + the thing im trying to load is 'errork.vbs')
> > 
> > 
> > Where's the file located?
> > If you just stuck it into the mods folder youd need to do `getTextFromFile("errork.vbs")` which will return the contents of the file in text form...
> > if its in a modpack youd need to do `getTextFromFile("(mod name here)/errork.vbs")`.
> 
> 1. inside the data folder for the song
> 2. so does that fix my problem?
> 3. I don't use different mod folders to make it easier to mod (with source)
> 
> what Im trying to do: vbs means Visual Basic Script Im trying to run this code (which is in the .vbs): X=MsgBox("test",0+64,"title") which makes a error message


It would be `getTextFromFile("data/errork.vbs")` but thats not what `getTextFromFile()` does...

I dont think I can help with that...
