### ISSUE TITLE
MP4Handler Not Found

### ISSUE THREAD

**Issue by Magniill** [ShadowMario/FNF-PsychEngine#9533]
### Describe your bug here.

I was building an ordinary Psych Engine 0.6.2 build, but while i was building, it popped up that there was no vlc.MP4Handler and MP4Handler.

### Command Prompt/Terminal logs (if existing)

```bash
source/PlayState.hx:67: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1496: characters 13-23 : Type not found : MP4Handler
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited one image only

**Comment by Itz-Miles** [comment]
Psych Engine 0.6+ uses the new hx codec stuff. You'll wanna add it by typing `haxelib install hxCodec` in your terminal.

**Comment by Magniill** [comment]
whoops

**Comment by final-23** [comment]
another way:
if you use hxcodec(git), you should todo:
delete this:
#if VIDEOS_ALLOWED
import vlc.MP4Handler;
#end
then do this:
Change var video:MP4Handler = new MP4Handler(); To
var video:VideoHandler = new VideoHandler();

then run lime test windows

**Comment by final-23** [comment]
keep in connected with OS Engine

**Comment by final-23** [comment]
because MP4Handler is Old Version
VideoHandler is New Version

**Comment by Noel3454565FNF** [comment]
> 

not working for me :,(
