### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kle6401-scratch** [ShadowMario/FNF-PsychEngine#9534]
### Describe your problem here.

heya I have occurred on powershell

source/FunkinLua.hx:342: lines 342-346 : Int should be Bool
source/FunkinLua.hx:342: lines 342-346 : ... For function argument 'f'

what does it mean and what should I do 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by FireIce421** [comment]
I have the exact same problem here.

**Comment by kle6401-scratch** [comment]
> 

thanks CrusherMods for fixing the issue

**Comment by CrusherMods** [comment]
if you fixed the issue close the issue
