### ISSUE TITLE
Test fnf json

### ISSUE THREAD

**Issue by manguytj5** [ShadowMario/FNF-PsychEngine#9535]
### Describe your bug here.

fnf json doesnt work

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
editors/ChartingState.hx (line 2908)
editors/ChartingState.hx (line 428)
Prompt.hx (line 57)
flixel/FlxState.hx (line 146)
flixel/FlxState.hx (line 208)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/test/test-hard.json]
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
You are missing a hard difficulty chart

**Comment by manguytj5** [comment]
> You are missing a hard difficulty chart

oh

**Comment by manguytj5** [comment]
my bad sorry

**Comment by frantastic24** [comment]
Close the issue

**Comment by tylerandari12** [comment]
If youre going into a chart by pressing 7 in a song, load a song on normal and it'll let you through just fine...

This issue can be closed if your problem is solved...
