### ISSUE TITLE
Game crashes when entering story mode or freeplay on MacOS

### ISSUE THREAD

**Issue by GenesisGreen** [ShadowMario/FNF-PsychEngine#9536]
### Describe your bug here.

I compiled Psych Engine 0.6.2 on MacOS and when trying to play in story mode or freeplay, the game tells me this
![Screen Shot 2022-07-06 at 9 54 24 AM](https://user-images.githubusercontent.com/85078030/177603467-0ffcd44f-9397-457e-986d-114dd359be35.png)
:

### Command Prompt/Terminal logs (if existing)

```bash
/usr/local/lib/haxe/std/haxe/format/JsonParser.hx (line 318)
/usr/local/lib/haxe/std/haxe/format/JsonParser.hx (line 110)
/usr/local/lib/haxe/std/haxe/format/JsonParser.hx (line 90)
/usr/local/lib/haxe/std/haxe/format/JsonParser.hx (line 57)
WeekData.hx (line 222)
WeekData.hx (line 190)
WeekData.hx (line 178)
StoryMenuState.hx (line 58)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid char 93 at position 85
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by:
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment]
Not a bug
One of your week files is broken
