### ISSUE TITLE
The black and white...

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#9537]
### What is your question?

Is there a way to make an image with color turn black and white?
Or should I just make a separate b&w asset?

**Comment by Paracosm-Daemon** [comment]
you could try using the ColorSwap shader, mess with saturation

**Comment by frantastic24** [comment]
Make a colorswap shader with -1 saturation and apply it to your sprite
You can do it with `runHaxeCode()` if with lua, I also made a PR that adds it as its own Lua function #9532

**Comment by tylerandari12** [comment]
Interesting...
Ill see what I can do...

And Ill actually close this unlike most issues out there lol...

**Comment by CrusherMods** [comment]
> Interesting... Ill see what I can do...
> 
> And Ill actually close this unlike most issues out there lol...

W person fr
