### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by AgentF4Z** [ShadowMario/FNF-PsychEngine#9539]
### Describe your bug here.

For some reason when trying to make another character play an animation, it broke and crashed

https://user-images.githubusercontent.com/92244297/177646693-05ef3cac-6b1c-4b12-be53-65a3504bd08b.mp4

![image](https://user-images.githubusercontent.com/92244297/177647017-012885cb-6e4c-4d2a-8a56-06de502474f1.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Can't even read the error, and you didn't post the script

**Comment by AgentF4Z** [comment]
> Can't even read the error, and you didn't post the script

fixed the video

**Comment by Paracosm-Daemon** [comment]
line 2868 in PlayState:
```haxe
if(!startingSong && !endingSong && boyfriend.animation.curAnim.name.startsWith('idle')) {
```
either boyfriend doesn't exist, or curAnim doesn't exist, which is why you get that Null Object Reference error

**Comment by ShadowMario** [comment]
Boyfriend character has an invalid animation.
You did something wrong.

**Comment by Mateeyyyyy** [comment]
i dont understand same thing happend to me but it crashed when i added the character to a song the only one that didn't crash the game was changing gf into the character
