### ISSUE TITLE
How to have custom dialogue fonts

### ISSUE THREAD

**Issue by GrimTheDragonLord** [ShadowMario/FNF-PsychEngine#9540]
### Describe your problem here.

Fonts are a thing and im trying to give each of my character their own unique fonts when they speak. Recently I downloaded a script made by 'Super_Hugo' that helped with this somewhat but the problem was ALL the dialogue was the same ONE font. I need different fonts across different characters and the dialogue editor dosent show any of this. What can I do?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I've changed MANY things but my focus is dialogue which i've only added portraits and sounds for that.

**Comment by WilliamGaming12** [comment]
https://gamebanana.com/mods/384704

Right on that link budd, u can even change the dialogue box.

**Comment by GrimTheDragonLord** [comment]
> https://gamebanana.com/mods/384704
> 
> Right on that link budd, u can even change the dialogue box.

I thank you for this but if you read my comment its what I've already tried to use and cant make work <3
