### ISSUE TITLE
Process Creation Failure: CL.EXE

### ISSUE THREAD

**Issue by FireIce421** [ShadowMario/FNF-PsychEngine#9542]
### Describe your problem here.

Compiling group: haxe
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/ -IC:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/ -I C:/HaxeToolkit/haxe/lib/hxCodec/2,5,1/lib/vlc/include/ -I C:/HaxeToolkit/haxe/lib/hxCodec/2,5,1/lib/vlc/src/ -nologo -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\User\desktop\FNF-PsychEngine-Main\export\release\windows\obj\obj/msvc64-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_CHECK_POINTER(haxe) -DHXCPP_STACK_LINE(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/flixel/input/actions/_FlxSteamController/FlxSteamControllerMetadata.cpp
 - src/sys/io/_Process/Stdout.cpp
 - src/openfl/display/_internal/Context3DElementType.cpp
Process creation failure : cl.exe

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Only changed executable name in Project.xml (also changed resolution from 720p to 1080p)

**Comment by FireIce421** [comment]
What i changed for Project.xml: ![image](https://user-images.githubusercontent.com/92722498/177738678-b8217dc4-183b-4999-a45e-2687356c1cc4.png)

**Comment by ShadowMario** [comment]
I assume you had other issues cuz i just did this right now and it worked to me.

**Comment by FireIce421** [comment]
i don't know how that happened

**Comment by FireIce421** [comment]
i'll reinstall source later and try again

**Comment by FireIce421** [comment]
> I assume you had other issues cuz i just did this right now and it worked to me.

oh wait i forgot to mention did you change the 720p setting to 1080p
