### ISSUE TITLE
PlayState and FunkinLua

### ISSUE THREAD

**Issue by TarnSpill** [ShadowMario/FNF-PsychEngine#9543]
### Describe your problem here.

source/PlayState.hx:67: characters 8-22 : Type not found : vlc.MP4Handler
source/FunkinLua.hx:342: lines 342-346 : Int should be Bool
source/FunkinLua.hx:342: lines 342-346 : ... For function argument 'f'
source/PlayState.hx:1496: characters 13-23 : Type not found : MP4Handler

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by kingyomoma** [comment]
did the MP4Handler error disappear or is it still there?

if you are still getting the Funkin' Lua problem try doing `haxelib remove linc_luajit` and then run the second command again

**Comment by TarnSpill** [comment]
> did the MP4Handler error disappear or is it still there?
> 
> if you are still getting the Funkin' Lua problem try doing `haxelib remove linc_luajit` and then run the second command again

everything also doesn't work
