### ISSUE TITLE
chart editor crashed while saving chart. i am in pain.

### ISSUE THREAD

**Issue by travisgamemaker** [ShadowMario/FNF-PsychEngine#9547]
### Describe your bug here.

tried saving a chart and psych crashed :(

### Command Prompt/Terminal logs (if existing)

```bash
editors/ChartingState.hx (line 2950)
editors/ChartingState.hx (line 2931)
editors/ChartingState.hx (line 416)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no. this is a precompiled build.

**Comment by ShadowMario** [comment]
Fixed right now
