### ISSUE TITLE
Crashes going into Freeplay for the "Saul Goodman" fanmod

### ISSUE THREAD

**Issue by your-angel** [ShadowMario/FNF-PsychEngine#9548]
### Describe your bug here.

Added the Saul Goodman mod, crashes upon attempt to enter "Freeplay" mode. Upon removal of the files, works normally.

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/FlxGraphic.hx (line 617)
flixel/FlxSprite.hx (line 405)
HealthIcon.hx (line 45)
HealthIcon.hx (line 20)
FreeplayState.hx (line 133)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

I have the MadVan mod installed from BBPANZU, BITE, and Nerd Emoji Mod installed.

**Comment by Paracosm-Daemon** [comment]
the crash happens when the freeplay icon tries to load, except the icon doesn't exist
