### ISSUE TITLE
StoryMode Problem

### ISSUE THREAD

**Issue by AlbiedoesRandom** [ShadowMario/FNF-PsychEngine#9549]
### Describe your bug here.

When I Started to port mods to psych engine i went onto storymode and my game crashed and said something about storymode playstate

### Command Prompt/Terminal logs (if existing)

```bash
StoryMenuState.hx (line 275)
flixel/group/FlxGroup.hx (line 740)
StoryMenuState.hx (line 273)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i didnt

**Comment by BernardoGP4504** [comment]
something major like sprites or animations are missing
