### ISSUE TITLE
where are the mp4 coding and what line in the version 0.4.2 

### ISSUE THREAD

**Issue by gummybear17** [ShadowMario/FNF-PsychEngine#955]
### Describe your problem here.

the reason why im asking this is because so i can build it without the mp4 video support or is it hard coded in the hx files 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

**Comment by ToBAYT** [comment]
Go to every file, do ctrl f and type MP4. Should help

**Comment by ToBAYT** [comment]
My guess is that it is somewhere in playstate

**Comment by ShadowMario** [comment]
`startVideo`, PlayState.hx
