### ISSUE TITLE
Character Editor Copy And Pasting Bug

### ISSUE THREAD

**Issue by TonyTimee** [ShadowMario/FNF-PsychEngine#9552]
### Describe your bug here.

When i copy some thing from the XML
it always Puts it for example
```sky mad downsky mad down``` and not just ```sky mad down```

Kinda Annoying Bug

What i mean
![image](https://user-images.githubusercontent.com/88756260/177892405-49557aba-5090-44b7-803e-542b45defe3d.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no changes

**Comment by Lorekeeper49** [comment]
That might be due to your PC or keyboard doing the command twice

**Comment by frantastic24** [comment]
No it's an actual bug

**Comment by ShadowMario** [comment]
This has already been fixed on the newest commits
