### ISSUE TITLE
A crash that occurs whenever I play a ported mod.

### ISSUE THREAD

**Issue by Itsyoboi653** [ShadowMario/FNF-PsychEngine#9553]
### Describe your bug here.

This bug is occurring whenever I play ported mods that I downloaded from modpacks, and gamebanana. It lets me past the meu, and into either freeplay or story mode, but crashes whenever _any_ song plays. Sometimes without even a crash report. 

Sometimes I get one though, and this is what it looks like. 

### Command Prompt/Terminal logs (if existing)

Paths.hx (line 352)
NoteSplash.hx (line 51)
NoteSplash.hx (line 19)
PlayState.hx (line 1044)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added tons of mod ports, but that's genuinely it. I had the same issue with another version of Psych Engine with tons of mods, and the same thing happened. It's almost like it transferred over to this new, and clean download I did of it.

**Comment by frantastic24** [comment]
that's not a bug, you are missing splash note textures

**Comment by Itsyoboi653** [comment]
It says though that I have the splash textures? So I don't get what's happening. I have the base splash textures, and all the mod folders I ported have splash textures too. I can't find where the 'missing splash textures' that I need are.
