### ISSUE TITLE
How do I use function eventEarlyTrigger(name)

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#9556]
### Describe your problem here.

So I'm trying to use this function, but i have NO idea how it's used. I don't even know where to put it! Do I put it in the event or some script file or? And do I put my event stuff in this function or the onevent function?

So can someone please explain to me how it works, and maybe even give an example.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
Read the template script.

**Comment by wubbzyfan** [comment]
i tried. it does not work.

even the example does not work.

i'm not even sure if this function even exists in the code!

**Comment by VoidedBattery** [comment]
Maybe try all ideas that you can think of until it works?
