### ISSUE TITLE
Force Vocals Event

### ISSUE THREAD

**Issue by dombomb64** [ShadowMario/FNF-PsychEngine#9557]
### Describe your problem here.

I’m trying to make an event that forces the vocals to play so that voice lines can play even if you just missed. However, for some reason, I still can’t hear the voice line after missing, even though I set the same exact property that the game does.

The code:
```
function onEvent(name, value1, value2)
	if name == 'Force Vocals' then
		setProperty('vocals.volume', 1);
	end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by hayfii** [comment]
on update function

**Comment by hayfii** [comment]
```
local fv = false

function onEvent(name, value1, value2)
	if name == 'Force Vocals' then
		fv = true
	end
end

function onUpdate(elapsed)
     if fv then
          setProperty('vocals.volume', 1);
     end
```

**Comment by frantastic24** [comment]
use `noteMiss()`, you don't need or want this running every frame

**Comment by dombomb64** [comment]
This is what worked for me:

local forceVocals = false;

```
function onEvent(name, value1, value2)
	if name == 'Force Vocals' then
		forceVocals = true
	end
end

function onBeatHit()
	if forceVocals == true then
		setProperty('vocals.volume', 1);
		forceVocals = false;
	end
end
```

I had to set `forceVocals` back to false after so that it would only stay once.

**Comment by frantastic24** [comment]
That still triggers unnecessarily

**Comment by dombomb64** [comment]
I want it to trigger at the moment (or soon after), not on the next miss, because what if the player didn't miss and it triggers way later? This is good enough for me.
