### ISSUE TITLE
Why does my game lag when i load an event

### ISSUE THREAD

**Issue by ytboogy** [ShadowMario/FNF-PsychEngine#9558]
### Describe your problem here.

when an event happens (specifically these 2 which are attached) my game lags a lot

i have an intel core i5 and a GTX 1650 (if that helps)

Can you provide me something that doesn't lag or a fix for this

[the files.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/9070626/the.files.zip)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, MainMenuState.hx and ChartingState.hx

**Comment by frantastic24** [comment]
Because you're making the game run through every note, and for some reason you're doing it twice

**Comment by ShadowMario** [comment]
> Because you're making the game run through every note, and for some reason you're doing it twice

^
Also, graphics card doesn't help in FNF that much since most of it runs through your CPU btw.
