### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by Jo3sDX** [ShadowMario/FNF-PsychEngine#9559]
### Describe your bug here.

Yesterday everything worked fine, today I open up Psych Engine and BOOM, it crashed, some .hx files are broken, should I redownload? No idea why, it just happened :/ (I downloaded Psych Engine from the gamebanana page)
![the error](https://user-images.githubusercontent.com/102918263/177968271-6986c786-9fb6-46af-9499-1f52e9800596.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added mods (Whitty) and added a Angry senpai icon (I had to replace icon-face.png with a angry senpai icon because it wouldn't work)

**Comment by FunkinFriend88** [comment]
I have the same problem bro...

**Comment by ShadowMario** [comment]
Logo image is missing
