### ISSUE TITLE
Animation intervals

### ISSUE THREAD

**Issue by Haano137** [ShadowMario/FNF-PsychEngine#956]
### Describe your problem here.

Is there any way to set the, lack of a better word, BPM, of certain animations? Kinda like the "GF Speed" event but for everything else, with also the option to make things slower?

Ideally, I would like to do this with camera zoom, hud zoom, player animations, and opponent animations.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

None

**Comment by ShadowMario** [comment]
At the moment, no, i will add a thing for it on the next update
