### ISSUE TITLE
week logo is haxe flixel logo

### ISSUE THREAD

**Issue by FNFUNBLOCKED** [ShadowMario/FNF-PsychEngine#9561]
### Describe your problem here.

i made a week for psych engine, and added the picture in the weeks folder in the mods folder, but after doing that it still shows flixel logo

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i added a week but thats it

**Comment by FunkinFriend88** [comment]
Go to the week editor select the week that you made and rename the week file

**Comment by FNFUNBLOCKED** [comment]
oh ok thanks
