### ISSUE TITLE
problem with the health bar

### ISSUE THREAD

**Issue by Texty-face** [ShadowMario/FNF-PsychEngine#9562]
### Describe your bug here.

every time I add something custom (like a song, a chart, a character, an icon or a background) the health bar disappear
![Screenshot (39)](https://user-images.githubusercontent.com/108941093/178009264-a3e73c16-b276-4c0f-9451-2d87d60a7412.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i only added a chart and a song in the photo

**Comment by frantastic24** [comment]
You have Hide HUD on

**Comment by Mastercopper2346** [comment]
💀
