### ISSUE TITLE
Psych Engine (0.6.2) not compiling everytime

### ISSUE THREAD

**Issue by NotAhmedEpic** [ShadowMario/FNF-PsychEngine#9563]
### Describe your bug here.

I have tried to compile Psych Engine for the first time, I have everything downloaded for it and it just gives me an error saying Int should be Bool and then something else I dont understand. I dont even know how to fix this so please god help me.

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\user\Downloads\FNF-PsychEngine-0.6.2\FNF-PsychEngine-0.6.2>lime test windows
source/FunkinLua.hx:342: lines 342-346 : Int should be Bool
source/FunkinLua.hx:342: lines 342-346 : ... For function argument 'f'

C:\Users\user\Downloads\FNF-PsychEngine-0.6.2\FNF-PsychEngine-0.6.2>
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I changed Application Name, File name and removed if=OfficialBuild in Project.xml. I also removed VIDEOS_ALLOWED line

**Comment by Grape-Boy** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/issues/9543#issuecomment-1177513596

**Comment by NotAhmedEpic** [comment]
Grape-Boy that fixed it, thanks
