### ISSUE TITLE
Visual Studio 2017 VsDevCmd not found

### ISSUE THREAD

**Issue by NotAhmedEpic** [ShadowMario/FNF-PsychEngine#9564]
### Describe your bug here.

I have installed everything required for compiling Psych Engine, including Visual Studio itself, but the game still doesnt compile. No more comments

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\user\Downloads\FNF-PsychEngine-0.6.2\FNF-PsychEngine-0.6.2\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

C:\Users\user\Downloads\FNF-PsychEngine-0.6.2\FNF-PsychEngine-0.6.2>
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I changed Application Name, File name and removed if=OfficialBuild in Project.xml

**Comment by chillultimated** [comment]
You have to Install this thing on the screenshot in Visual Studio (it's written in Russian, but you can understand by the icon), you need every plugin that SDK and MSVC
![Снимок экрана 2022-07-09 042433](https://user-images.githubusercontent.com/86905561/178032221-e7945e20-0c3a-4367-8e69-9234f128dfd7.png)
