### ISSUE TITLE
Freeplay bug

### ISSUE THREAD

**Issue by chillultimated** [ShadowMario/FNF-PsychEngine#9565]
### Describe your bug here.

After I launched song through freeplay I get this
![2022-07-09_04-17-41](https://user-images.githubusercontent.com/86905561/178031498-8ceb5dd2-1a4a-45b9-aebf-1e0c7db86b13.png)
 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, I just added some stuff in "mods" folder

**Comment by frantastic24** [comment]
Not a bug
It's literally explained in the screenshot, your chart is missing
