### ISSUE TITLE
Resizing the game window's width without the screen crunching (in LUA)

### ISSUE THREAD

**Issue by ManMaster707** [ShadowMario/FNF-PsychEngine#9566]
### What is your question?

I tried to resize the window's width by using
`setPropertyFromClass('openfl.Lib', 'application.window.width', 1280-320)`
 but the height of the game's screen (not the window itself) literally crunched (idk how to explain it, look at the borders), here's an example on how the screen should look:

![bruhmoment](https://user-images.githubusercontent.com/101059988/178044914-27fb2b9e-f56c-418c-8872-a6c6e8ed2070.png)

Is there a way to make the game screen not leave those empty spaces? (`setPropertyFromClass('FlxG', 'height', 4000)` doesn't work)

**Comment by EyeDaleHim** [comment]
I'd advise using FlxG Scale Mode but they are not the results you are looking for, trust me.

**Comment by ManMaster707** [comment]
> I'd advise using FlxG Scale Mode but they are not the results you are looking for, trust me.

I'm still curious, how'd you do it?

**Comment by EyeDaleHim** [comment]
> > I'd advise using FlxG Scale Mode but they are not the results you are looking for, trust me.
> 
> I'm still curious, how'd you do it?

Please check the [HaxeFlixel API](https://api.haxeflixel.com/flixel/system/scaleModes/index.html).

**Comment by ManMaster707** [comment]
> Please check the [HaxeFlixel API](https://api.haxeflixel.com/flixel/system/scaleModes/index.html).

Sorry to bothering you this much, but I've checked there and made a script with the recently added lines, but it doesn't seem to work, am I doing anything wrong here? I know next to nothing about those functions, so I could've made some dumb messups
```lua
function onSongStart()
	addHaxeLibrary('FlxG.scaleMode', 'FillScaleMode')
	runHaxeCode([[
	FlxG.scaleMode = new FillScaleMode();
	]])
end

**Comment by EyeDaleHim** [comment]
> > Please check the [HaxeFlixel API](https://api.haxeflixel.com/flixel/system/scaleModes/index.html).
> 
> Sorry for bothering you this much, but I've checked there and made a script with the recently added lines, but it doesn't seem to work, am I doing anything wrong here? I know next to nothing about those functions, so I could've made some dumb messups
> 
> ```lua
> function onSongStart()
> 	addHaxeLibrary('FlxG.scaleMode', 'FillScaleMode')
> 	runHaxeCode([[
> 	FlxG.scaleMode = new FillScaleMode();
> 	]])
> end
> ```

`FlxG.scaleMode` is not a folder.

**Comment by ManMaster707** [comment]
`flixel.system.scaleModes` is a folder, right? Because I replaced it but it still won't work

**Comment by EyeDaleHim** [comment]
> nevermind, I had to swap the values, it worked, but now it also gives me this:
> 
> ```
> flixel/FlxCamera.hx (line 1253)
> flixel/FlxCamera.hx (line 1061)
> flixel/FlxGame.hx (line 749)
> flixel/FlxGame.hx (line 677)
> flixel/FlxGame.hx (line 551)
> openfl/events/EventDispatcher.hx (line 402)
> openfl/display/DisplayObject.hx (line 1399)
> 
> Uncaught Error: Null Object Reference
> Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine
> 
> > Crash Handler written by: sqirra-rng
> ```
> 
> how do I fix this?

Please show your script.

**Comment by ManMaster707** [comment]
> Please show your script.

here you go:
```lua
function onCreate()
	-- background shit
	setPropertyFromClass('lime.app.Application', 'current.window.width', 1280)
end

function onSongStart()
	--setPropertyFromClass('lime.app.Application', 'current.window.width', 1280-320)
	setPropertyFromClass('openfl.Lib', 'application.window.width', 1280-320)
	--setPropertyFromClass('FlxG', 'height', 4000)
	addHaxeLibrary('FillScaleMode', 'flixel.system.scaleModes')
	runHaxeCode([[
		FlxG.scaleMode = new FillScaleMode();
	]])
end

function onCreatePost()	
	for i=0,3 do
		setPropertyFromGroup('opponentStrums',i,'texture', 'oppNOTE_assets')
	end	

	for i=0, getProperty('unspawnNotes.length')-1 do
		if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
		    setPropertyFromGroup('unspawnNotes', i, 'texture', 'oppNOTE_assets')
		end
    end
end
