### ISSUE TITLE
Error with source

### ISSUE THREAD

**Issue by Psychenginehelper** [ShadowMario/FNF-PsychEngine#9569]
### Describe your bug here.

i try to compile my edited psych engine then git just spams
y
![2022-07-08](https://user-images.githubusercontent.com/108227479/178062461-eaa36c87-1374-4edb-af3f-f18c34cca109.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited the main menu state.hx, the discord rpc.hx and the playstate.hx

**Comment by frantastic24** [comment]
There is a pipebomb in your mailbox

**Comment by Psychenginehelper** [comment]
ikr

**Comment by EyeDaleHim** [comment]
I don't think watching a YouTube video and you screenshotting it is going to help.
