### ISSUE TITLE
How to copy a stage from another mod? It is a folder, not only an image.

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#957]
### What is your question?

How to copy a stage from another mod? It is a folder, not only an image.
If it is only an image , I know the steps of adding it to my mod.
But how to add it to my game if it is a folder.

**Comment by ShadowMario** [comment]
What is that even supposed to mean 🤨

**Comment by cheemynugget** [comment]
> What is that even supposed to mean 🤨

i think its like how week 7 has its assets in a folder with seperate sprites, or how week 6 has trees, bgs in seperate images

**Comment by zwl1619** [comment]
> > What is that even supposed to mean 🤨
> 
> i think its like how week 7 has its assets in a folder with seperate sprites, or how week 6 has trees, bgs in seperate images

@cheemynugget Yes, it is.  How to add it into the game?
