### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by cpeezywastaken** [ShadowMario/FNF-PsychEngine#9570]
### Describe your bug here.

I tried to use dadbattle spotlight in the sink mod, but the game gave me a crash report.

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2455)
PlayState.hx (line 2411)
PlayState.hx (line 1054)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added the Dadbattle spotlight event to the song called sink (soinc song)

**Comment by frantastic24** [comment]
Duplicate, stop fucking using events hardcoded for a specific stage

**Comment by cpeezywastaken** [comment]
Shit, I didn’t realize it was only for the default stage
My bad lmao

**Comment by frantastic24** [comment]
Close the issue
