### ISSUE TITLE
CRASH!

### ISSUE THREAD

**Issue by SollaxxREALONE** [ShadowMario/FNF-PsychEngine#9571]
### Describe your problem here.

PlayState.hx (line 2469)
PlayState.hx (line 2425)
PlayState.hx (line 1053)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Don't use dadbattle spotlight

**Comment by SollaxxREALONE** [comment]
what do you mean its basically ALL events crashing! version 0.6.2

**Comment by SollaxxREALONE** [comment]
i think i screwed the assets or idk

**Comment by SollaxxREALONE** [comment]
that crash wasnt from the dadbattle spotlight it was simply on ALL EVENTS!
