### ISSUE TITLE
Timetxt thing (again)

### ISSUE THREAD

**Issue by schwiftified** [ShadowMario/FNF-PsychEngine#9572]
### What is your question?

How can i move timetxt on lua?

**Comment by TonyTimee** [comment]
try getProperty('timeTxt.x', value);

**Comment by ManMaster707** [comment]
```lua
function onCreatePost()
    setProperty('timeTxt.x', getProperty('timeTxt.x') + 100)-- just an example
    setProperty('timeTxt.y', getProperty('timeTxt.y') + 100) 
end

**Comment by schwiftified** [comment]
> 

just sends the timetxt flying, the x and y just makes it go slower or faster

**Comment by ManMaster707** [comment]
>just sends the timetxt flying, the x and y just makes it go slower or faster

This happens if you put it in the function `onUpdate()` , but if you have to then use this code:

```lua
object = 'timeTxt'
function onUpdate()
if getPropertyFromClass('flixel.FlxG', 'keys.justPressed.T') then
    debugPrint(getProperty(object..'.x')..', ', getProperty(object..'.y'))
  end
end
```

This will make so that when you press T it shows the exact location of the time text, so then you can do it without issues

**Comment by schwiftified** [comment]
> ```lua
>   end
> end
> ```

i dont want that

**Comment by schwiftified** [comment]
i dont want the T ket thing, i just want to know how i can move the time txt

**Comment by frantastic24** [comment]
You got your answer already
