### ISSUE TITLE
Game crash!

### ISSUE THREAD

**Issue by AngelGamer94GIT** [ShadowMario/FNF-PsychEngine#9573]
### Describe your bug here.

Paths.hx (line 352)
Alphabet.hx (line 388)
Alphabet.hx (line 149)
Alphabet.hx (line 69)
editors/MasterEditorMenu.hx (line 56)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

This appeared while I was charting, idk why

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't

**Comment by frantastic24** [comment]
Duplicate, stop fucking using events hardcoded for a stage

**Comment by frantastic24** [comment]
you are missing `alphabet.png`
