### ISSUE TITLE
Animator for cutscene?

### ISSUE THREAD

**Issue by PotatoKing0419** [ShadowMario/FNF-PsychEngine#9574]
### Describe your problem here.

![POTATO KING COVER](https://user-images.githubusercontent.com/92553022/178069377-ae30e67d-e166-4adf-afbd-aaceb9f64ddc.jpg)

Hi!

I'm making an FNF Mod called Vs. Potato King, and I wanted an animator for cutscenes cuz I only do pixel animations. I'm hoping to make this a pretty high quality mod, but I mainly just need someone that can do smooth animation with a nice software (That I'm to broke to have) like adobe animate or whatever. I will give all the credit I possibly can, because again, I'm too broke to pay people :|

The Vs. Potato King Team so far has 3 people and it's probably around halfway done for the v2 update.
My Discord is Potato King#8785
Plz help ;-;

Thanks!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
not the place to ask

**Comment by ManMaster707** [comment]
I think you should ask [here](https://github.com/Theoyeah/PsychEngineDiscussions/discussions) instead
