### ISSUE TITLE
Hide Hud event

### ISSUE THREAD

**Issue by TheManwhoisdyinghere** [ShadowMario/FNF-PsychEngine#9577]
### Describe your problem here.

Does anyone have a Hide Hud event just laying around on your computers?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
There's several posted here already, search before opening an issue

**Comment by Lorekeeper49** [comment]
I have something better
```lua
function onEvent(n, v1, v2)
    if n == 'hud alpha' then
        doTweenAlpha('hudalpha', 'camHUD', v1, v2, 'linear'); --v1 is opacity or transparency, v2 is duration
    end
end
```
