### ISSUE TITLE
cant add Freeplay-only songs

### ISSUE THREAD

**Issue by creeperkidking** [ShadowMario/FNF-PsychEngine#9579]
### Describe your bug here.

I checked the hide in story menu thing and it did...….but it also hid it from the Freeplay
I even tried checking the hide from Freeplay but that hid it for both too
i use the precompiled 0.5.2h version

### Command Prompt/Terminal logs (if existing)

```bash
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by creeperkidking** [comment]
added note: just found out that the week just wont exist
it wont show up

**Comment by creeperkidking** [comment]
nvm i think i fixed it but i will keep this open for now just incase it breaks again

**Comment by EyeDaleHim** [comment]
> nvm i think i fixed it but i will keep this open for now just incase it breaks again

I recommend you do have to close this issue though, even if it will break again. You can re-open your issue I believe.

**Comment by TheBeast94YT** [comment]
You have to create a week for the Freeplay songs to appear, press 7 on the menu after the title screen and press Enter on the Week Editor.

**Comment by creeperkidking** [comment]
i did
