### ISSUE TITLE
What i need to write there

### ISSUE THREAD

**Issue by Sebasyn0se** [ShadowMario/FNF-PsychEngine#958]
### Describe your problem here.

i added the onBeatHit function, but what i need to write to add the sprite to it, i tried adding all the animation and sprite source inside the function, but it doesn't load, also i tried to do it inside the onCreate function and it didn't work either.
![test-ddlc-bg lua - Visual Studio Code 11_11_2021 12_22_54](https://user-images.githubusercontent.com/93066244/141323572-4a67793e-2746-42a1-a943-608089a60bfb.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ShadowMario** [comment]
You need to show more (The start of your script too)

**Comment by Sebasyn0se** [comment]
here you have

i wrote "if curBeat > 264" because the song has 264 beats
![test-ddlc-bg lua - Visual Studio Code 11_11_2021 19_21_08](https://user-images.githubusercontent.com/93066244/141377491-4af95c2f-c91b-45cb-b027-3954a4ab5ea5.png)
![test-ddlc-bg lua - Visual Studio Code 11_11_2021 19_21_11](https://user-images.githubusercontent.com/93066244/141377503-f20f15c7-51ba-4f25-b659-8e4642f2849b.png)

**Comment by ShadowMario** [comment]
...Are you on Low Quality mode?
You made the sprites not get spawned when on Low Quality

**Comment by Sebasyn0se** [comment]
Nop, im not in low quality mode, and i didn't write that because i dont need low quality lol

**Comment by perngjiafu** [comment]
just remove the if not lowQuality

**Comment by NotEpik** [comment]
that not cool everyone are doing doki doki takeover psych engine port  but I finish it after it come out for 1 day NOICE

**Comment by ShadowMario** [comment]
> that not cool everyone are doing doki doki takeover psych engine port but I finish it after it come out for 1 day NOICE

Don't say anything at all if you don't have anything relevant to say.
