### ISSUE TITLE
how to flip the player strumline X-axis

### ISSUE THREAD

**Issue by Matriniii** [ShadowMario/FNF-PsychEngine#9580]
### Describe your problem here.

i want to make the strumline flip on X so left = right, right = left, up = down, down = up if its possible, also its on beat hit.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by machonessiebaby** [comment]
make another character that has those swapped animations then on a beat hit in editor you can use a change character event for this
so you have

char name here
flipped char name here

**Comment by Matriniii** [comment]
not the anims but the actual strumline itself
