### ISSUE TITLE
Little Code Fix

### ISSUE THREAD

**Issue by EyeDaleHim** [ShadowMario/FNF-PsychEngine#9581]
### What feature do you want to get added on the **base** engine?

For this code right here.
![image](https://user-images.githubusercontent.com/71162374/178108593-136d1f2b-86cf-4091-9e46-7de9f6a0a6e0.png)

I recommend using this one below.
```haxe
FlxG.sound.music.onComplete = finishSong.bind(false);
```
Although I will not make a PR for this as I have a current one available, and I won't bother to.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Code optimization that would make the game faster. (You should make a PR if this is your request, by the way.)

**Comment by EyeDaleHim** [comment]
This should also apply to some other code but is one of the minor code fixes to prevent functions like `onSongComplete`.

**Comment by impostor5875** [comment]
🤓

**Comment by impostor5875** [comment]
also you failed the test
