### ISSUE TITLE
Can somebody send the source code / github link of a build with the 1280x960 resolution option?

### ISSUE THREAD

**Issue by NesDoesGithub** [ShadowMario/FNF-PsychEngine#9582]
### What is your question?

Can somebody send over that? Because I really need it for a project i'm doing with Psych Engine.

**Comment by EyeDaleHim** [comment]
![image](https://user-images.githubusercontent.com/71162374/178112136-0c52b734-48f9-455f-9b11-257f145ea4e3.png)

Don't be lazy.

**Comment by NesDoesGithub** [comment]
> ![image](https://user-images.githubusercontent.com/71162374/178112136-0c52b734-48f9-455f-9b11-257f145ea4e3.png)
> 
> Don't be lazy. File located is `FNFPROJECT/Project.xml`

No, I'm trying to see how I could change the resolution for a certain song, I know how to do that via the project.xml.

**Comment by hayfii** [comment]
> > ![image](https://user-images.githubusercontent.com/71162374/178112136-0c52b734-48f9-455f-9b11-257f145ea4e3.png)
> > Don't be lazy. File located is `FNFPROJECT/Project.xml`
> 
> No, I'm trying to see how I could change the resolution for a certain song, I know how to do that via the project.xml.

From lua or source??

**Comment by NesDoesGithub** [comment]
> > > ![image](https://user-images.githubusercontent.com/71162374/178112136-0c52b734-48f9-455f-9b11-257f145ea4e3.png)
> > > Don't be lazy. File located is `FNFPROJECT/Project.xml`
> > 
> > 
> > No, I'm trying to see how I could change the resolution for a certain song, I know how to do that via the project.xml.
> 
> From lua or source??

from source

**Comment by hayfii** [comment]
> > > > ![image](https://user-images.githubusercontent.com/71162374/178112136-0c52b734-48f9-455f-9b11-257f145ea4e3.png)
> > > > Don't be lazy. File located is `FNFPROJECT/Project.xml`
> > > 
> > > 
> > > No, I'm trying to see how I could change the resolution for a certain song, I know how to do that via the project.xml.
> > 
> > 
> > From lua or source??
> 
> from source

You can try this I guess
```
openfl.Lib.application.window.width = 1280;
openfl.Lib.application.window.height =  960;
```

**Comment by hayfii** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/71162374/178112136-0c52b734-48f9-455f-9b11-257f145ea4e3.png)
> > > > > Don't be lazy. File located is `FNFPROJECT/Project.xml`
> > > > 
> > > > 
> > > > No, I'm trying to see how I could change the resolution for a certain song, I know how to do that via the project.xml.
> > > 
> > > 
> > > From lua or source??
> > 
> > 
> > from source
> 
> You can try this I guess (I'm not sure what you mean)
> 
> ```
> openfl.Lib.application.window.width = 1280;
> openfl.Lib.application.window.height = 960;
> ```

If you meant by resizing the game screen you can try
```
FlxG.resizeGame(1280, 960);
```

If you want to resize it before the song loads/the whole PlayState loads:
![image](https://user-images.githubusercontent.com/94598301/178118775-d5f9580b-0c11-4fa7-999d-606d77d3831d.png)
