### ISSUE TITLE
I have a question about docs

### ISSUE THREAD

**Issue by funtime-foxy1** [ShadowMario/FNF-PsychEngine#9583]
### What is your question?

Hey, im trying to download the video example and for me I just get a page that says this: 

![image_2022-07-09_121632654](https://user-images.githubusercontent.com/70809736/178114008-d83174fa-eaa9-48f2-9ce8-43d892ea9bca.png)

Can someone help pls?

**Comment by EyeDaleHim** [comment]
Wait until SM fixes it.

**Comment by funtime-foxy1** [comment]
> Wait until SM fixes it.

can i atleast have the files?

**Comment by LilMewo** [comment]
> > Wait until SM fixes it.
> 
> can i atleast have the files?
 
where are u gettin that error i'll try to get u the files 🙂

**Comment by TheKitBoi** [comment]
it looks like the discord message link removed the message

**Comment by funtime-foxy1** [comment]
nvm got it Thanks for the help!
