### ISSUE TITLE
So i need help (again) with a custom option

### ISSUE THREAD

**Issue by machonessiebaby** [ShadowMario/FNF-PsychEngine#9585]
### Describe your problem here.

so i have all the code but it leads to this error:
![image](https://user-images.githubusercontent.com/56323671/178117625-01f2fd81-9070-4836-9be2-ccd5af344932.png)
code

```
lines 102-125

		var option:Option = new Option('Main Menu Song:',
		"What song do you prefer for the Main Menu?",
		'mainmenumusic',
		'string',
		'freakymenu',
		['None', 'OldMenu', 'freakymenu']);
	addOption(option);
	option.onChange = onChangeMainMusic;

	var changedDaMusic:Bool = false;
function onChangeMainMusic()
{
	if(ClientPrefs.mainMusic == 'None')
		FlxG.sound.music.volume = 0;
	else
		FlxG.sound.playMusic(Paths.music(Paths.formatToSongPath(ClientPrefs.mainMusic)));

	changedDaMusic = true;
}

override function destroy(){
	if(changedDaMusic) FlxG.sound.playMusic(Paths.music('freakyMenu'));
	super.destroy();
}
```
error location 122-125

```
override function destroy(){
	if(changedDaMusic) FlxG.sound.playMusic(Paths.music('freakyMenu'));
	super.destroy();
}

```
![image](https://user-images.githubusercontent.com/56323671/178117728-21b1a3d2-0007-41f1-98f7-5d5bfb34d122.png)

### Are you modding a build from source or with Lua?

Source & Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

visual ui substate options.hx playstate.hx freeplaystate.hx many more

**Comment by JP297** [comment]
Yo idk if it's fixed or not but this is how the code should look

override function destroy()
{
	if(changedDaMusic) FlxG.sound.playMusic(Paths.music('freakyMenu'));
	super.destroy();
}

**Comment by machonessiebaby** [comment]
> Yo idk if it's fixed or not but this is how the code should look
> 
> override function destroy() { if(changedDaMusic) FlxG.sound.playMusic(Paths.music('freakyMenu')); super.destroy(); }

bro i have been waiting for so long ill test this out

**Comment by machonessiebaby** [comment]
> override function destroy()
> {
> if(changedDaMusic) FlxG.sound.playMusic(Paths.music('freakyMenu'));
> super.destroy();
> }

still broken sadly 
![image](https://user-images.githubusercontent.com/56323671/187551375-232fee9f-77ab-417b-8da1-137b641763bd.png)

**Comment by TheKitBoi** [comment]
override function destroy()
{
    if(changedDaMusic) FlxG.sound.playMusic(Paths.music('freakyMenu'));
    {
    super.destroy();
    }
}

**Comment by machonessiebaby** [comment]
i wont ever get this done so yoink goodbye issue
