### ISSUE TITLE
game crashed when pressing note

### ISSUE THREAD

**Issue by SuperSonic472** [ShadowMario/FNF-PsychEngine#9586]
### Describe your problem here.

I was testing player sprites for a mod I was making and 
![image](https://user-images.githubusercontent.com/64370131/178117950-fb6702fc-c61c-45db-abf3-d39117418b5f.png)
this is probably a json error because uh idk I used the player sprite and the entire sheet broke because the sprite creator has one sheet that could be the problem
[TactieP but zipped so i can send it.zip](https://github.com/ShadowMario/FNF-PsychEngine/files/9077658/TactieP.but.zipped.so.i.can.send.it.zip)
m

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by SuperSonic472** [comment]
ignore the build stuff lol its not lua i was just editing character files

**Comment by EyeDaleHim** [comment]
Wait what version are you in

**Comment by EyeDaleHim** [comment]
Oh nevermind, considering you are in (possibly) the latest version, you might wanna try fixing your character animations a bit, since I only found out it pinpoints to the boyfriend idle check thing.

**Comment by SuperSonic472** [comment]
well thats weird because i edited the other json in the same way and it worked
