### ISSUE TITLE
Polymod Error

### ISSUE THREAD

**Issue by Nullyz** [ShadowMario/FNF-PsychEngine#9588]
### Describe your problem here.

every time I use ''Lime test Windows'' after a few seconds this error appears I've tried to uninstall and install polymod again but it still has the same error
![saaaaaa](https://user-images.githubusercontent.com/95359581/178119474-e66d25d0-e1a5-4679-bcd8-92a25d0d0e93.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by EyeDaleHim** [comment]
That... isn't Psych Engine I believe.

**Comment by BeastlyGhost** [comment]
this isn't psych, you're working with the base game, but as a fix for the error, remove everything related to Polymod on the game states, and project.xml
