### ISSUE TITLE
getObjectOrder nil value when layering GF

### ISSUE THREAD

**Issue by AbyssalChaos** [ShadowMario/FNF-PsychEngine#9589]
### Describe your problem here.

I'm using the code  `setObjectOrder('gfGroup', getObjectOrder('dadGroup') + 1);` but when i run the script the engine tells me "attempt to call global getObjectOrder (a nil value)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ManMaster707** [comment]
put the code inside a function like `onCreate()`

**Comment by AbyssalChaos** [comment]
ah, i missed that part, thank you! :)
