### ISSUE TITLE
A too big variable

### ISSUE THREAD

**Issue by LrgeAlvaro8882** [ShadowMario/FNF-PsychEngine#959]
### Describe your problem here.

I get the Error C2177: constant too big and they told me that there is a variable that is too big but I can't seem to find it.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a lot of stuff inside PlayState.hx

**Comment by ShadowMario** [comment]
Duplicate of #837
