### ISSUE TITLE
Script works but keeps crashing

### ISSUE THREAD

**Issue by ManMaster707** [ShadowMario/FNF-PsychEngine#9590]
### Describe your problem here.

In my now closed issue I created a script, that shows its results but keeps crashing, I'm gonna show the code and the error that the crash handler gives me, and I have no clue on how to fix this.

The code:
```lua
function onCreate()
	-- background shit
	setPropertyFromClass('lime.app.Application', 'current.window.width', 1280)
end

-- I think the problem is located here but I could be wrong
function onSongStart()
	--setPropertyFromClass('lime.app.Application', 'current.window.width', 1280-320)
	setPropertyFromClass('openfl.Lib', 'application.window.width', 1280-320)
	--setPropertyFromClass('FlxG', 'height', 4000)
	addHaxeLibrary('FillScaleMode', 'flixel.system.scaleModes')
	runHaxeCode([[
		FlxG.scaleMode = new FillScaleMode();
	]])
end

function onCreatePost()	
	for i=0,3 do
		setPropertyFromGroup('opponentStrums',i,'texture', 'oppNOTE_assets')
	end	

	for i=0, getProperty('unspawnNotes.length')-1 do
		if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
		    setPropertyFromGroup('unspawnNotes', i, 'texture', 'oppNOTE_assets')
		end
    end
end
```
the error:
```
flixel/FlxCamera.hx (line 1253)
flixel/FlxCamera.hx (line 1061)
flixel/FlxGame.hx (line 749)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
``` 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i just added things trough the "mods" folder.

**Comment by BeastlyGhost** [comment]
window stuffs are crashing, not exactly sure which one, my guess is that `FlxG.scaleMode` is not really working, try enabling `luaDebugMode` to see if the game returns with any additional useful information

**Comment by BeastlyGhost** [comment]
> insert "need more information" label here

**Comment by ManMaster707** [comment]
> try enabling luaDebugMode to see if the game returns with any additional useful information

with lua debug mode it just returns: "Couldnt find object: green", but "green" it's not mentioned whatsoever in my script, so idk if that's useful or not

**Comment by BeastlyGhost** [comment]
> > try enabling luaDebugMode to see if the game returns with any additional useful information
> 
> with lua debug mode it just returns: "Couldnt find object: green", but "green" it's not mentioned whatsoever in my script, so idk if that's useful or not

green refers to the actual name for the up arrow on the xml file, maybe your file doesn't have the correct names for noteskins???

**Comment by BeastlyGhost** [comment]
I have this script which might help changing noteskins in general if you wish to take a look at it, because apparently the noteskin is **one** of the problems ur facing

```Haxe
function onCreatePost()
    bfTex = 'noteskins/' .. 'NOTE_assets' -- change your boyfriend noteskin here
    dadTex = 'noteskins/' .. 'NOTE_assets' -- change your dad noteskin here
    bfStrumline = 'playerStrums'
    dadStrumline = 'opponentStrums'

    applyOnBF = true -- whether to enable the skin for boyfriend
    applyOnDad = false -- whether to enable the skin for dad

    if applyOnBF then
        for i = 0, 3 do setPropertyFromGroup(bfStrumline, i, 'texture', bfTex) end
        for i = 0, getProperty('unspawnNotes.length') - 1 do
            if getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
                setPropertyFromGroup('unspawnNotes', i, 'texture', bfTex)
            end
        end
    end

    if applyOnDad then
            for i = 0, 3 do setPropertyFromGroup(dadStrumline, i, 'texture', dadTex) end
            for i = 0, getProperty('unspawnNotes.length') - 1 do
            if not getPropertyFromGroup('unspawnNotes', i, 'mustPress') then
                setPropertyFromGroup('unspawnNotes', i, 'texture', dadTex)
            end
        end
    end
end
```

**Comment by ManMaster707** [comment]
>green refers to the actual name for the up arrow on the xml file, maybe your file doesn't have the correct names for noteskins???

the thing is that there isn't an xml file, it's a pixel spritesheet, and it works just fine

**Comment by BeastlyGhost** [comment]
> > green refers to the actual name for the up arrow on the xml file, maybe your file doesn't have the correct names for noteskins???
> 
> the thing is that there isn't an xml file, it's a pixel spritesheet, and it works just fine

huh, weird, it should get your noteskin correctly then, yet it's returning an error on it

**Comment by ManMaster707** [comment]
> huh, weird, it should get your noteskin correctly then, yet it's returning an error on it

Then maybe it's just the engine freaking out a bit, though I'm still wondering what the crash handler error meant by "Null Object Reference"

**Comment by BeastlyGhost** [comment]
> > huh, weird, it should get your noteskin correctly then, yet it's returning an error on it
> 
> Then maybe it's just the engine freaking out a bit, though I'm still wondering what the crash handler error meant by "Null Object Reference"

it means that some _specific_ object is returning null, in this case, from what the crash handler prints out, it looks like something is wrong with the cameras in specific, so I suppose it's actually related to scale modes or maybe the window resolution itself changing

**Comment by ManMaster707** [comment]
> > > huh, weird, it should get your noteskin correctly then, yet it's returning an error on it
> > 
> > 
> > Then maybe it's just the engine freaking out a bit, though I'm still wondering what the crash handler error meant by "Null Object Reference"
> 
> it means that some _specific_ object is returning null, in this case, from what the crash handler prints out, it looks like something is wrong with the cameras in specific, so I suppose it's actually related to scale modes or maybe the window resolution itself changing

the window resolution didn't crash before inplementing the scale modes, so it must be the scale modes, is there a way to inplement them without crashing?

**Comment by ManMaster707** [comment]
Closing this since I can work without the scale modes just fine, just a thing I wanted to do.
