### ISSUE TITLE
Countdown thing (Lua)

### ISSUE THREAD

**Issue by MTFutureWasTaken** [ShadowMario/FNF-PsychEngine#9591]
### Describe your problem here.

Is there a way to turn the countdown on and off mid-song?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by frantastic24** [comment]
#7155

**Comment by MTFutureWasTaken** [comment]
> #7155


I should have specified mid-song.

**Comment by frantastic24** [comment]
There's no countdown midsong

**Comment by MTFutureWasTaken** [comment]
> There's no countdown midsong

Yeah, but... you know what I mean, right? I mean that I need to find a way to stop the song mid-song and then turn it back on.

**Comment by frantastic24** [comment]
You could've explained it better from the start
Just make a space in your song and make a fake countdown during it
