### ISSUE TITLE
A way to change the difficulty directly in the Chart Editor

### ISSUE THREAD

**Issue by Galbio** [ShadowMario/FNF-PsychEngine#9592]
### What feature do you want to get added on the **base** engine?

An option in Chart Editor to change the difficulty instead of selecting the song, play the song, change the difficulty of the song, go back in chart editor and replace all the events that been erased (I know it's possible to make a file called events.json but if you wanna make custom events for a certain difficulty it's just not practical.

It would be a button in the song section of chart editor. And since image speak more than words, here is a fan made version of what it would look like.

![image](https://user-images.githubusercontent.com/101997612/178123084-9567e474-a6ea-4a21-9410-7e3012d3186a.png)

The "Alt" difficulty would be based on if the song has a prefix in the data folder (like dadbattle-alt or -crazy.json)
Of course it can be implemented in a better way since I've done this draw with Paint but I think it's a good feature.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
Didn’t you just do it-
And you can make a pr-

**Comment by Galbio** [comment]
It's a montage, I made it on Paint

**Comment by Mastercopper2346** [comment]
Ok

**Comment by BeastlyGhost** [comment]
interesting concept, yeah i'm doin' it

**Comment by ShadowMario** [comment]
No longer needed as you can load charts directly now
