### ISSUE TITLE
side to side middle scroll notes

### ISSUE THREAD

**Issue by Aidenkp112** [ShadowMario/FNF-PsychEngine#9593]
### What is your question?

im working on this old mod i dont really even work on and in one song i want to make bfs notes to be middle scroll (same with opponent) but at a certain point they'll go side to side

idk how to make it but i've tried and i haven't been able to make it

**Comment by EyeDaleHim** [comment]
Please elaborate further.

**Comment by Aidenkp112** [comment]
ok so basically the notes will be middle scroll for the entire song (bfs are visible but not opponents) and at a certain point in the song bfs notes go from one side to another

thats the best i can give

**Comment by Lorekeeper49** [comment]
The best way you can do this is to use `noteTweenX`, check the wiki to figure out how to use it
