### ISSUE TITLE
A few coding stuff i wanna know how to do (source code)

### ISSUE THREAD

**Issue by Nightmaremat** [ShadowMario/FNF-PsychEngine#9594]
### Describe your problem here.

I want to know how to code/put the main menu options on the bottom of the screen

I have 2 more questions :

How do i code JumpScares

How do i make health draining notes or notes that if you dont press it takes a certain amount of health away

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Not really i just added some custom events thats really it

**Comment by EyeDaleHim** [comment]
Not a valid issue.
