### ISSUE TITLE
New secret title screen sprites don't go away when reopening the game, and there's no toggle I could find.

### ISSUE THREAD

**Issue by TheBeast94YT** [ShadowMario/FNF-PsychEngine#9596]
### Describe your bug here.

In 0.6.2, there's this .txt file in the assets folder that said the following:

### "shadow" or "bb" on the title screen!"

Me, being the idiot I am used those inputs and saw custom sprites for the title screen. However, I can't get the original GF sprites on the title screen back. Even rebooting Psych Engine still has the secret images appear.

This isn't that much of a problem, but for perfectionists like me who despise stuff you can't go back on, it's kind of a detriment in the sense, considering how not everyone wants characters they've never heard of on their screen with no warning. (No offense to the people in these sprites.)

But yeah, how do I disable this?

### Command Prompt/Terminal logs (if existing)

```bash
None, this is more of an oversight than a real error. But still worth looking at (unless I can press a button or something to fix it lmao)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not in particular to affect my issue, but yes. I added image, song, and chart data. I didn't remove any GF sprites or the custom ones mentioned.

**Comment by frantastic24** [comment]
Bro type the code again

**Comment by TheBeast94YT** [comment]
> Bro type the code again

you've gotta be kidding me

though why can't it tell us that to disable it
