### ISSUE TITLE
how to remove debug

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#9599]
### Describe your problem here.

how to remove da bug (how to remove charting/debug mode)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No (other than the accuracy 'ratingStuff'), just modded in the "example_mods" folder

**Comment by ZeitHeld** [comment]
in the pause menu during a song, you can disable it.
or if you wanna return to the menu, you can go back to the menu.

**Comment by ItzOldFlagDEV** [comment]
Use not lime build windows -debug but use lime build windows on power shell window (VScode Power shell window)

**Comment by TFLTV** [comment]
> Use not lime build windows -debug but use lime build windows on power shell window (VScode Power shell window)

I've never used either of those
