### ISSUE TITLE
How to open a file using LUA?

### ISSUE THREAD

**Issue by redstonemaster60** [ShadowMario/FNF-PsychEngine#9601]
### What is your question?

I've tried using io.open, however it's not opening the files and i'm not sure if i'm maybe just putting them in the wrong directory, or if there's another issue. (If it matters, i'm trying to open a .png file) If possible, just a basic explanation of how to open a file with LUA will do. Thanks

**Comment by frantastic24** [comment]
These are Lua functions you can look up on google, they're not related to the engine

**Comment by redstonemaster60** [comment]
Ok thanks.
