### ISSUE TITLE
How can I implement loading screens before starting a song?

### ISSUE THREAD

**Issue by Epiclol374** [ShadowMario/FNF-PsychEngine#9604]
### Describe your problem here.

I already described it in the title xdd

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

**Comment by frantastic24** [comment]
Loading screens are useless on desktop and there's at least 20 other posts about this

**Comment by TFLTV** [comment]
> Loading screens are useless on desktop and there's at least 20 other posts about this

what makes them useless?

**Comment by frantastic24** [comment]
On HTML they are used to download assets, this does not happen in desktop

**Comment by deathline1938** [comment]
local bg = 'LOADING NAME HERE' -- type here your loading name

local allowCountdown = false

function onStartCountdown()
    if not allowCountdown then
	    return Function_Stop
	end

	if allowCountdown then
	    return Function_Continue
	end
end

function onCreatePost()
	makeLuaSprite('LOADING NAME HERE', 'loading' , 0, -13) -- type here too
	runTimer('fadeTimer', 3.0, 1)

	addLuaSprite('LOADING NAME HERE', true) -- and here
	scaleObject('LOADING NAME HERE', 0.69, 0.69) -- and here...
	setObjectCamera('LOADING NAME HERE', 'camOther') -- true and here
end

function onTimerCompleted(tag)
    if tag == 'fadeTimer' then
	    doTweenAlpha('delete', 'LOADING NAME HERE', 0, 0.5, 'backIn') -- yep type here too
		allowCountdown = true
		startCountdown()
		
	end
end

function onTweenCompleted(tag)
    if tag == 'delete' then
	    removeLuaSprite('LOADING NAME HERE', true) -- type here too lol
		
	end
end

**Comment by deathline1938** [comment]
```
local bg = 'LOADING NAME HERE' -- type here your loading name

local allowCountdown = false

function onStartCountdown()
    if not allowCountdown then
	    return Function_Stop
	end

	if allowCountdown then
	    return Function_Continue
	end
end

function onCreatePost()
	makeLuaSprite('LOADING NAME HERE', 'loading' , 0, -13) -- type here too
	runTimer('fadeTimer', 3.0, 1)

	addLuaSprite('LOADING NAME HERE', true) -- and here
	scaleObject('LOADING NAME HERE', 0.69, 0.69) -- and here...
	setObjectCamera('LOADING NAME HERE', 'camOther') -- true and here
end

function onTimerCompleted(tag)
    if tag == 'fadeTimer' then
	    doTweenAlpha('delete', 'LOADING NAME HERE', 0, 0.5, 'backIn') -- yep type here too
		allowCountdown = true
		startCountdown()
		
	end
end

function onTweenCompleted(tag)
    if tag == 'delete' then
	    removeLuaSprite('LOADING NAME HERE', true) -- just type here too lol
		
	end
end
```
