### ISSUE TITLE
'PlayAnim' gives weird offsets to scaled lua sprites that use 'updateHitbox'

### ISSUE THREAD

**Issue by AppleHair** [ShadowMario/FNF-PsychEngine#9605]
### The bug

So the current PlayAnim code (0.6.2) applies offsets like this:
![image](https://user-images.githubusercontent.com/95587502/178151111-075841cf-b060-4a06-9e71-4568cf08d9e2.png)

and when updateHitbox is used after a lua sprite is scaled, it changes the offset like this:
![image](https://user-images.githubusercontent.com/95587502/178151198-0eb9b265-215e-4e27-a6e8-9ee911c5522d.png)

This means that if a scaled lua sprite, that used updateHitbox, tries to use PlayAnim, the offset it got from updateHitbox will be ignored and replaced by (0,0), which can result in weird-looking offsets that make the lua sprite look like it is in a different position.

### Example

a scaled lua sprite that the offset it got from updateHitbox wasn't replaced (objectPlayAnimation):
![image](https://user-images.githubusercontent.com/95587502/178152188-62f2937f-379b-47d5-b027-7fc98cceb44f.png)

a scaled lua sprite that the offset it got from updateHitbox was replaced (PlayAnim):
![image](https://user-images.githubusercontent.com/95587502/178152377-2c959457-5d29-4e90-85b6-a9d3f0a69bf3.png)

### Why this matters

Although you can just give up on updateHitbox, change the lua sprite's position and it should look fine in most cases, this solution results in position values that don't represent the position of the sprite accurately enough and make it harder to do stuff that involve aligning one lua sprite with another (which is the reason people use updateHitbox in the first place).

### Potential Solution

I think a good solution to this will be to add a new boolean argument to PlayAnim that will tell it if it needs to take updateHitbox into consideration and to make the function apply offsets like this:

1. set the sprite's offset to (0,0)
2. if I need to take updateHitbox into consideration, then use updateHitbox on the sprite
3. if the animation exists, then **add** the animation offset to the current offset of the sprite

these changes should result in a something that looks like this:
![image](https://user-images.githubusercontent.com/95587502/178153695-0b3574d9-5c65-4e98-8b97-27040a863667.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

of course not.

**Comment by ShadowMario** [comment]
That's how haxe handles offsets my guy.
