### ISSUE TITLE
Sustain notes do not recalculate the rating

### ISSUE THREAD

**Issue by dum-du-m** [ShadowMario/FNF-PsychEngine#9606]
### Describe your bug here.

Title is self explanatory

https://user-images.githubusercontent.com/79086250/178154340-2abcfd67-c350-4f29-87ee-24581ee8f109.mp4

.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didnt do anything

**Comment by frantastic24** [comment]
?

https://user-images.githubusercontent.com/95725102/178163587-fe50065f-ba50-453f-a219-b6ebeb40f21b.mp4

**Comment by dum-du-m** [comment]
> ?
> 
>  Friday.Night.Funkin._.Psych.Engine.2022-07-10.18-55-59.mp4

are you on 0.6.2

**Comment by dum-du-m** [comment]
i couldnt find a commit that fixes it  but its probably only when you have one sustain note at once idk

**Comment by Dismatiyt** [comment]
Maybe your input code

**Comment by dum-du-m** [comment]
> > only when you have one sustain note at once idk
> 
> No that was just for the funny, it works fine either way

i just tried it on the latest commit and it still didnt do it

**Comment by ShadowMario** [comment]
It isn't supposed to do it?
