### ISSUE TITLE
SFC PROBLEM

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#9607]
### Describe your bug here.

I got a good and still had a SFC. it happened to me 2 times 1 time on guns and 1 time on stress

### Command Prompt/Terminal logs (if existing)

```bash
source/FreeplayState.hx:375: guns-hard
source/FreeplayState.hx:381: CURRENT WEEK: week7
source/LoadingState.hx:162: Setting asset folder to week7
source/Conductor.hx:135: new BPM map BUDDY []
source/FunkinLua.hx:96: lua file loaded succesfully:mods/scripts/CustomRate.lua
source/Conductor.hx:135: new BPM map BUDDY []
source/LoadingState.hx:162: Setting asset folder to week7
source/Conductor.hx:135: new BPM map BUDDY []
source/FunkinLua.hx:96: lua file loaded succesfully:mods/scripts/CustomRate.lua
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No (other than the accuracy 'ratingStuff'), just modded in the "example_mods" folder

**Comment by BeastlyGhost** [comment]
you actually didn't, you got a GFC, but the score bar doesn't properly update, will fix this sooner or later
