### ISSUE TITLE
i got a error that told me to report it to the github so idk

### ISSUE THREAD

**Issue by tordlover69** [ShadowMario/FNF-PsychEngine#9608]
### Describe your bug here.

![error!](https://user-images.githubusercontent.com/109040096/178158147-ca8c711a-c347-44a3-afba-0e9472c2fa2b.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Stress pico needs `picospeakers.json` chart to work

**Comment by Lorekeeper49** [comment]
Anytime you want to use picospeaker in a song, `picospeaker.json` must be in the song data folder.  Not sure why considering everytime I saw stress on different channels, the shoot pattern was the same but the directions were different, making it seem like the directions were randomized

**Comment by frantastic24** [comment]
Because they are randomized, that's how it works

This issue can be closed

**Comment by Dismatiyt** [comment]
Why tf you are using pico speaker in Satin Panties song?

**Comment by frantastic24** [comment]
I'm talking about animations, not the chart
