### ISSUE TITLE
too much to fit in a title

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#9609]
### What feature do you want to get added on the **base** engine?

icon editor, custom '3 2 1 GO' OGGs (in a specific song),
custom '3 2 1 GO' images (in a specific song), 
dialogue fonts, dialogue text colors, custom dialogue boxes.

ICON EDITOR FEATURES: animated icons, scale icons, get icon color, (everything else that was in the character editor that was related to icons),
special health changes (what I mean is like you can add something so whenever the health value hits that point it'll change the icon), new function: OnIconChange (or something like that), show icon resolution (for getting a resolution (because if you want
a bigger workspace (or higher quality icons) it can fetch what resolution it needs to be)), icon lua code. 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
You can already do pretty much all of these
