### ISSUE TITLE
Return Value not supported

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#961]
### What is your question?

How can I use **i** for defaultPlayerStrumX.

### the trashy code I made ###
```
function onUpdate(elapsed)
		songPos = getSongPosition()
		local currentBeat = (songPos/2000)*(bpm/60)
		for i = 0,3 do
	setPropertyFromGroup('playerStrums', i, 'x', defaultPlayerStrumX..i + math.sin(currentBeat+i * 0.504) * 15);

	setPropertyFromGroup('opponentStrums', i, 'x', defaultOpponentStrumX..i + math.sin(currentBeat+i * 0.504) * 15);
	end
end
```

When I change **defaultPlayerStrumX..i/defaultOpponentStrum..i** to **defaultPlayerStrumX0/defaultPlayerStrumX0** it works,
 so I guess the problem has to do something with **defaultPlayerStrum/defaultOpponentStrum**

**Comment by ShadowMario** [comment]
Change `defaultOpponentStrumX..i` to `_G[defaultOpponentStrumX..i]`, This will get the actual variable instead of a string.
