### ISSUE TITLE
Opponent arrows

### ISSUE THREAD

**Issue by joxu13v** [ShadowMario/FNF-PsychEngine#9611]
### Describe your problem here.

How can I change the arrows with the rival at a certain point in the song and return to its original state using .lua?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Value-Setting-and-Getting-Functions
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Variables#gameplay-variables

**Comment by AdmiralUsername** [comment]
tween opponent note X values to +650
tween player note X values to -650
