### ISSUE TITLE
please man how

### ISSUE THREAD

**Issue by TheManwhoisdyinghere** [ShadowMario/FNF-PsychEngine#9612]
### Describe your problem here.

is there a way to make a stage object have Antialiasing

i don't like how when i make something really big it just looks really bad

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
You could've looked it up before asking #8147

**Comment by frantastic24** [comment]
You could've looked it up before asking #8157
