### ISSUE TITLE
Stop with Issues now (New Disscusions)

### ISSUE THREAD

**Issue by BerdlyEC** [ShadowMario/FNF-PsychEngine#9614]
### What is your question?

https://github.com/BerdlyEC/Engine-Discussions

@ShadowMario Now cry about it bitch

**Comment by TFLTV** [comment]
dont tell me what to do

**Comment by BerdlyEC** [comment]
> dont tell me what to do
It's for no More use to Issues

**Comment by Lorekeeper49** [comment]
> dont tell me what to do

You're not ShadowMario

**Comment by Mastercopper2346** [comment]
Mayo had his discussions with over 1000 discussions…
Even though it got banned, @Theoyeah is the 2nd- oldest

**Comment by ShadowMario** [comment]
My retard in christ, i have notifications turned off, pinging me is no use dumbass.
![image](https://user-images.githubusercontent.com/44785097/178614324-e50c8745-846b-47ef-8c7b-a20cbf5283e8.png)

**Comment by ShadowMario** [comment]
Of course it's a fucking dave and bambi fan
