### ISSUE TITLE
arrow flip

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#9615]
### Describe your problem here.

how to flip arrows to make it so oppenent arrows are on the other side (same with bf)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No (other than the accuracy 'ratingStuff'), just modded in the "example_mods" folder

**Comment by Username2120** [comment]
[Lua](https://drive.google.com/file/d/1iFng_cTg0Ri4GUF2dsDsHB9dtF5XfXfZ/view?usp=sharing)[txt](https://drive.google.com/file/d/1kMY6WOGlMxymlUwNOpT4R5HMKK9j6zSw/view?usp=sharing) hopefully this is what you are looking for.

**Comment by TFLTV** [comment]
> [Lua](https://drive.google.com/file/d/1iFng_cTg0Ri4GUF2dsDsHB9dtF5XfXfZ/view?usp=sharing) [txt](https://drive.google.com/file/d/1kMY6WOGlMxymlUwNOpT4R5HMKK9j6zSw/view?usp=sharing) hopefully this is what you are looking for.

it won't let me open the lua file

**Comment by Username2120** [comment]
you should just be able to drop it into the events folder, if thats what you mean.

**Comment by TFLTV** [comment]
> you should just be able to drop it into the events folder, if thats what you mean.

now it lets me open it up compoters are wird

**Comment by TFLTV** [comment]
> you should just be able to drop it into the events folder, if thats what you mean.

oh, I meant like, I coulden't see the code inside

**Comment by Username2120** [comment]
ah, got it. well i hope it was what you were looking for, based on the fact you closed this ill assume it was.
