### ISSUE TITLE
Android Pause Button

### ISSUE THREAD

**Issue by BerdlyEC** [ShadowMario/FNF-PsychEngine#9617]
### Describe your problem here.

![Screenshot_20220402-140139.png](https://user-images.githubusercontent.com/101206464/161395755-1c486c1a-02e9-46af-8666-aa73101740c7.png)

But the script dont works good.

Script:
```
function onStartCountdown()
        makeAnimatedLuaSprite('pause', 'androidcontrols/pausebutton', 0, 588);
        addAnimationByPrefix('pause', 'pause', 'pause', 24, false);
		addAnimationByPrefix('pause', 'pausePress', 'pausePressed', 24, false);
		addLuaSprite('pause', true);
		setObjectCamera('pause', 'other')
	end

function onUpdate()
		if (getMouseX('camHUD') > 0 and getMouseX('camHUD') < 132) and (getMouseY('camHUD') > 588 and getMouseY('camHUD') < 720 and mouseClicked('pause')) then
			objectPlayAnimation('pause', 'pausePress', false);
			pause()
		else
			objectPlayAnimation('pause', 'pause', true);
		end

end
```
(PLEASE DONT USE THIS, cuz dont works)

Please help me!!!!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

Android

**Comment by frantastic24** [comment]
Not supported

**Comment by TheKitBoi** [comment]
good luck getting that 'omg not dave & bambi again' tag

**Comment by BerdlyEC** [comment]
https://github.com/MAJigsaw77/FNF-PsychEngine-With-Android-Support

**Comment by TheKitBoi** [comment]
> https://github.com/MAJigsaw77/FNF-PsychEngine-With-Android-Support

Then why would you post this issue here

**Comment by frantastic24** [comment]
Then go make an issue over there and not here
