### ISSUE TITLE
I've just entered in Chart Editor

### ISSUE THREAD

**Issue by Galbio** [ShadowMario/FNF-PsychEngine#9623]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/101997612/178293897-28cbe79e-0d86-4bc4-a462-302b41596bef.png)

Nothing to say

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I just entered Chart Editor, if anyone has an idea reply to this message pls

**Comment by frantastic24** [comment]
bf.json is missing, it says it right there

**Comment by Galbio** [comment]
Ok, still a bug but whatever

**Comment by frantastic24** [comment]
You shouldn't delete bf's json anyways
