### ISSUE TITLE
lime test windows error

### ISSUE THREAD

**Issue by Nullyz** [ShadowMario/FNF-PsychEngine#9624]
### Describe your problem here.

it's me here again good when I use the lime test windows command it just gives this error that is in the image
![image](https://user-images.githubusercontent.com/95359581/178302962-56f0bace-3eba-44ed-9eae-3f711bdc46f2.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Missing visual studio components

**Comment by Hazardows** [comment]
To solve this you must go to the Visual Studio installation program and look for the option to modify installation, You will then see a list of components that you can add. From this list select the checkbox for the "HXCPP_VARS" component. Many options will appear but you just have to select the most up-to-date one and then run the installation program. After this, the component that you need to execute the compilation task successfully will be installed.

**Comment by Hazardows** [comment]
After doing this you just have to execute the command "lime test windows"
