### ISSUE TITLE
Changing stages in Dadbattle crashes the game

### ISSUE THREAD

**Issue by SlickSquid35** [ShadowMario/FNF-PsychEngine#9625]
### Describe your bug here.

It says it in the title; if I try to change the stage in dadbattle it crashes, I first noticed this when trying to load a custom stage, it crashed, I tried again a few times, and it still crashes, and then i tried switching it to the Philly stage, it still crashed.

But I might know the problem, When version 0.6.2 came out dadbattle had a section where the screen turns dark and spotlights appear and fog covers the bottom of the screen, and im thinking because of that feature, changing stages where the feature cannot be activated overloads Psych engine and crashes the game

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I did not edit anything, this is purely from the Gamebanana download, No source code

**Comment by frantastic24** [comment]
Not a bug, the event is hardcoded for the stage
