### ISSUE TITLE
Unexpected error in my opinion (Null Object Reference)

### ISSUE THREAD

**Issue by Dismatiyt** [ShadowMario/FNF-PsychEngine#9627]
### Describe your bug here.

I got a crash when I miss too much in song:
"PlayState.hx (line 3076)
flixel/group/FlxGroup.hx (line 769)
PlayState.hx (line 3031)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng"
Is it fixable or I must wait until next version of psych engine?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I added some lua features like: Custom combo and rating, timebar color and Side info

**Comment by Dismatiyt** [comment]
And Yes, I am using the newest Psych Engine 0.6.2

**Comment by frantastic24** [comment]
not a bug
note texture is missing `end` animations

**Comment by Dismatiyt** [comment]
Thanks bro

pon., 11 lip 2022, 21:12 użytkownik frantastic24 ***@***.***>
napisał:

**Comment by Dismatiyt** [comment]
In my mod there's no Instakill note so that was the problem.

**Comment by Dismatiyt** [comment]
nahhh still the same I must just find in another stuff

**Comment by frantastic24** [comment]
like i said this isn't a bug, don't reopen this

**Comment by frantastic24** [comment]
I have no idea what you're talking about but the error is related to your note texture

**Comment by Dismatiyt** [comment]
Okay I found in my custom notes line that precaches image that doesn't exists lol

**Comment by Dismatiyt** [comment]
and I deleted it

**Comment by Dismatiyt** [comment]
maybe that is the notes thing but idk

**Comment by frantastic24** [comment]
I never mentioned lua

**Comment by Dismatiyt** [comment]
It happend when I changed no animation notes to my notes. Maybe I must bring back old chart

**Comment by Dismatiyt** [comment]
Because you said note texture is missing end animations.

**Comment by Dismatiyt** [comment]
Yep it was
