### ISSUE TITLE
In any song that is not of the Engine

### ISSUE THREAD

**Issue by ghost** [ShadowMario/FNF-PsychEngine#9628]
### Describe your bug here.

What happens is that when i get into a song nothing happens and it just stays there stiff, it doesn't matter If It has cinematics, It still goes on like this.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
what does that mean
is the time just stuck at 0? explain

**Comment by Dismatiyt** [comment]
> what does that mean is the time just stuck at 0? explain

He propably means that song is not working and it stucks at 0 minut and 0 seconds.

Propobly he uses the unsoported ogg file that is downloaded from the internet and not taken from the mod or the music program/app/website.

**Comment by frantastic24** [comment]
Yeah I know what they "probably" mean but it's not my job to guess what their issue is, it's on them to explain their own fucking report
