### ISSUE TITLE
how to add cutscenes from the holiday mod

### ISSUE THREAD

**Issue by GamingIQ** [ShadowMario/FNF-PsychEngine#9629]
### Describe your problem here.

I wanna add cutscenes like you have to press enter to go to the next page like a book,
at the start of this link: https://www.youtube.com/watch?v=jcMvXwuBV1o you will see what I'm talking about.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by ShadowMario** [comment]
Holiday mod's lua code is there (It's a LUA mod after all), go get it.
