### ISSUE TITLE
Multiple of the same custom event at the same time?

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#963]
## Problem

I've made a custom event that involves moving arrows, but when multiple of the event are used at the same time it overrides the previous one to do the current one.

Any suggestions?

```
function mysplit (inputstr, sep)
    if sep == nil then
        sep = "%s";
    end
    local t={};
    for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
        table.insert(t, str);
    end
    return t;
end

-- Event notes hooks
function onEvent(name, value1, value2)
    if name == "MoveArrow" then
        local tableee=mysplit(value2,", "); -- Splits value1 into a table
        value1 = tonumber(value1);

        if value1 < 4 then
            notePosX = getPropertyFromGroup('opponentStrums', value1, 'x');
            notePosY = getPropertyFromGroup('opponentStrums', value1, 'y');
        else
            notee = value1 - 4;
            notePosX = getPropertyFromGroup('playerStrums', notee, 'x');
            notePosY = getPropertyFromGroup('playerStrums', notee, 'y');
        end

        newnotePosX = notePosX + tableee[1];
        newnotePosY = notePosY + tableee[2];

        noteTweenX("",value1,newnotePosX,tableee[3],"quartInOut");
        noteTweenY("",value1,newnotePosY,tableee[3],"quartInOut");
    end
end
```
Here's the code, if that helps in any way.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Everything I've done has been within the mods folder.

**Comment by ShadowMario** [comment]
`noteTweenX(""`
You have to set an unique tag for the tweens. You made both the X and Y tween have blank tags, which means when noteTweenY starts, it will cancel the other tween with the same tag (noteTweenX)
