### ISSUE TITLE
how do i download video example for lua api

### ISSUE THREAD

**Issue by ghost** [ShadowMario/FNF-PsychEngine#9631]
### Describe your problem here.

i clicked it and got this:
https://cdn.discordapp.com/attachments/840678333602857040/888568130283139082/bopeeboTestVideo.zip
:(

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no?

**Comment by machonessiebaby** [comment]
yep it just broke find a yt tutorial and copy from video or they may have put in desc
