### ISSUE TITLE
I need to compile the source code

### ISSUE THREAD

**Issue by Hazardows** [ShadowMario/FNF-PsychEngine#9633]
### Describe your problem here.

You see, I need to compile the source code of the game but when I run the "lime test windows -debug" task, instead of compiling the game I get a lot of messages saying that there are syntax errors in writing the source code. I have tried to fix many of them but there are too many errors so I need to know how to compile the source code in the right way so that I don't get these error messages

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by Mastercopper2346** [comment]
Give all the error information

**Comment by Mastercopper2346** [comment]
He means he tried to fix THEN he came here lol

**Comment by Hazardows** [comment]
ok i alredy fix it

**Comment by Hazardows** [comment]
the problem was that i deleted a line of the code
