### ISSUE TITLE
It keeps crashing

### ISSUE THREAD

**Issue by thefirecreator** [ShadowMario/FNF-PsychEngine#9635]
### Describe your bug here.

I keep getting a specific error and dont know how to fix it
![bruh](https://user-images.githubusercontent.com/109120740/178391862-e459a940-b876-4721-9e2a-995d83abd339.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Ye, I tried to change who you play as

**Comment by frantastic24** [comment]
Your character is missing animations #9539

**Comment by thefirecreator** [comment]
> 

how can i find what animations are missing

**Comment by frantastic24** [comment]
There's only 5 basic animations so that should not be hard to check
