### ISSUE TITLE
really weird crash

### ISSUE THREAD

**Issue by aflacc** [ShadowMario/FNF-PsychEngine#9636]
### Describe your bug here.

all of a sudden the game would begin crashing and its really weird. boyfriend wouldn't show up and the opponent is stuck on one animation
![image](https://user-images.githubusercontent.com/60161366/178409266-f7bc4573-f127-4317-9e01-9e8f6d24e5c0.png)
bf should be there but instead is replaced by the evil haxeflixel logo

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2856)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Dismatiyt** [comment]
Bro, I got the same. It's just note missing "end" animation so check if you have it in your notes. Btw, what version of PE you are using?

**Comment by Dismatiyt** [comment]
or maybe is the issue with missing animations. (There's 5 basic: signUP, signDOWN, signLEFT, signRIGHT and IDLE)

**Comment by aflacc** [comment]
never mind i figured it out so apparenlty i accidentally used a seperate json file that wasnt finished rather than the finished one and accidentally put a space in the boyfrinedn spritesheet file

**Comment by alberfingernoodle** [comment]
omg it’s Aflac fnaf
