### ISSUE TITLE
Building problem

### ISSUE THREAD

**Issue by Onsibitic** [ShadowMario/FNF-PsychEngine#9639]
### Describe your problem here.

I've just downloaded the new psych version and this error pops up, anyone can help?

![image](https://user-images.githubusercontent.com/106243040/178448097-c1a5ac10-199d-4ca4-b818-abd6b6a5eb1f.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ArdoDev-stupid** [comment]
do you haxe nebulolarza's linc luajit?
if u don't, just use this:
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

**Comment by TFLTV** [comment]
install OR reinstall luajit. thats how I did it

**Comment by TFLTV** [comment]
> None worked



> None worked

I saw someone else try to build it using 'lime test windows -debug' have you tried 'lime test windows'?

**Comment by BeastlyGhost** [comment]
```
haxelib remove hxCodec
haxelib remove linc_luajit

haxelib install hxCodec
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
```
