### ISSUE TITLE
How add stages to Psych Engine

### ISSUE THREAD

**Issue by SuusyMogus25** [ShadowMario/FNF-PsychEngine#9640]
### Describe your problem here.

How add stages to Psych Engine

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I have build from github

**Comment by ItzOldFlagDEV** [comment]
Check this: https://www.youtube.com/watch?v=3RVOoEBvnaY

**Comment by ItzOldFlagDEV** [comment]
Check this: https://www.youtube.com/watch?v=3RVOoEBvnaY
