### ISSUE TITLE
Game crashes whenever i die

### ISSUE THREAD

**Issue by HyperGitMain** [ShadowMario/FNF-PsychEngine#9641]
### Describe your bug here.

It crashes when i enter the GameOverSubstate

### Command Prompt/Terminal logs (if existing)

```bash
GameOverSubstate.hx (line 106)
flixel/FlxState.hx (line 203)
flixel/FlxState.hx (line 212)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i was source code editing, but for some reason idk why, it just crashes whenever i die or reset to the GameOverSubstate, i did not edit any code thats used for the GameOverSubstate, all i did in PlayState was add new rating names, rating fc, winning icons, and editing the rating fc bool variable since the rating name kept saying null

**Comment by HyperGitMain** [comment]
the bug was like at 0.6.2, i did edit like the assets, characters i left in the files are only BOYFRIEND, DADDY_DEAREST, GF_assets, Hyper, and spooky_kids_assets

**Comment by TFLTV** [comment]
Is there a death animation?

**Comment by SirBluberryDev** [comment]
**make it apart of the base mod**

**Comment by HyperGitMain** [comment]
did 0.6.2 change which death animation is used for the GameOverSubstate, as i was updating the mod version from 0.5.2h to 0.6.2

**Comment by frantastic24** [comment]
The engine now uses a separate character for death state
