### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ghost** [ShadowMario/FNF-PsychEngine#9642]
### Describe your bug here.

The game crashed when I quit out of a song in a mod

### Command Prompt/Terminal logs (if existing)

```bash
(logs from crash folder)
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
editors/ChartingState.hx (line 2908)
editors/ChartingState.hx (line 428)
Prompt.hx (line 44)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/all-powerful-psychic/all-powerful-psychic-hard.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I downloaded the Mind Games mod and edited the name of the song Psychic on hard mode to All-Powerful Psychic.

**Comment by CrusherMods** [comment]
missing json most likely

**Comment by LilMewo** [comment]
> missing json most likely

no, I edited it in chart editor
