### ISSUE TITLE
How do I put in lua, a song composed by user thing?

### ISSUE THREAD

**Issue by mariokid718** [ShadowMario/FNF-PsychEngine#9644]
### Describe your problem here.

NO SOURCE CODE
How do I in lua put a song composed by (song composer) thing on the side of my song when it starts?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/LUA-Script-API:-Custom-Text
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers

**Comment by mariokid718** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/wiki/LUA-Script-API:-Custom-Text https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers

I do not understand the lua script at all. Thanks for trying to help tho!

**Comment by Mastercopper2346** [comment]
It’s not a script, it’s examples

**Comment by TheKitBoi** [comment]
[creatorCreds.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9097222/creatorCreds.txt)

Here the script is from TKTEMS
You can add or edit the text on the songArrays line

**Comment by mariokid718** [comment]
THANK YOU SO MUCH!
