### ISSUE TITLE
songname

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#9647]
### Describe your problem here.

what's the songname variable

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No (other than the accuracy 'ratingStuff'), just modded in the "example_mods" folder

**Comment by KutikiPlayz** [comment]
curSong

**Comment by TFLTV** [comment]
> curSong

didn't work. is something wrong?
```
function onCreate()
    if curSong == 'Bopeebo' then
        setProperty('ratingsData[0].image', 'magical') --change "Sick" image
    end
end
```

**Comment by BeastlyGhost** [comment]
PlayState.SONG.song

**Comment by TFLTV** [comment]
> PlayState.SONG.song

what does that mean

**Comment by BeastlyGhost** [comment]
> > PlayState.SONG.song
> 
> what does that mean

it references the current song playing on playstate

**Comment by TFLTV** [comment]
> > > PlayState.SONG.song
> > 
> > 
> > what does that mean
> 
> it references the current song playing on playstate

so, I type that in the lua script?

**Comment by BeastlyGhost** [comment]
do

```Lua
if songName == 'song' then
   --code
end
```

**Comment by TFLTV** [comment]
> ```lua
> if songName == 'song' then
>    --code
> end
> ```

ooo

**Comment by TFLTV** [comment]
> do
> 
> ```lua
> if songName == 'song' then
>    --code
> end
> ```


how do you make it so whatever song is in there will not run that code

**Comment by BeastlyGhost** [comment]
you are already specifiyng that said song will have said properties, so you don't need that

**Comment by TFLTV** [comment]
> you are already specifiyng that said song will have said properties, so you don't need that

but I'm making every song have that code
