### ISSUE TITLE
GFC Note

### ISSUE THREAD

**Issue by Coolboy0516** [ShadowMario/FNF-PsychEngine#9649]
### Describe your problem here.

Hello, can you help me make a note where if you don't get a Sick, when you press the note, you die? I already got the designs of them.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I removed all weeks except tutorial.

**Comment by BeastlyGhost** [comment]
```Lua
function onUpdatePost()
if ratingFC != 'SFC' or ratingFC != 'GFC' then
      setHealth(0);
end
```

**Comment by Coolboy0516** [comment]
Thanks man!

**Comment by BeastlyGhost** [comment]
> Thanks man!

mb

```
function onUpdatePost()
  if ratingFC == 'FC' or ratingFC == 'SDCB' or ratingFC == 'Clear' then
        setHealth(0);
  end
end
```

**Comment by TFLTV** [comment]
> 

I made a simpler way of doing this!
```lua
function onUpdatePost()
    if ratingFC == 'SFC' or ratingFC == '' then
    else
          setHealth(0);
    end
  end
```
