### ISSUE TITLE
Custom event script does not download

### ISSUE THREAD

**Issue by benpng** [ShadowMario/FNF-PsychEngine#9651]
### What needs to be documented?

so if i go to the sample scripts and click on the custom event one it wont work 
This is what appears
![IMG_20220713_004213](https://user-images.githubusercontent.com/56793857/178652272-39658e88-ef8d-4fff-a9cf-edac61b4ed98.jpg)

**Comment by Mastercopper2346** [comment]
1. Not enough space
See how much space you have

**Comment by benpng** [comment]
> 1. Not enough space
>    See how much space you have

i have like 800gb of space left so
