### ISSUE TITLE
Custom note type doesn't appear in Chart creator

### ISSUE THREAD

**Issue by Coolboy0516** [ShadowMario/FNF-PsychEngine#9652]
### Describe your problem here.

The custom note type in my mod won't appear in my mod, can someone tell me what's going on? Here's the link for my mod. https://drive.google.com/file/d/1ELcgBGh6ZBgpTNro_F29rud_GQ37g-AY/view?usp=sharing

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I removed all weeks except tutorial.

**Comment by Mastercopper2346** [comment]
Check to see how if the mod pack is on

**Comment by Lorekeeper49** [comment]
I can't access the folder

**Comment by Coolboy0516** [comment]
How?
