### ISSUE TITLE
"Malformed file. Source files must be encoded with UTF-8."

### ISSUE THREAD

**Issue by actuallygoodname** [ShadowMario/FNF-PsychEngine#9657]
### Describe your problem here.

after a while of not compiling psyche engine (maybe i haven't updated it or something idk) when i tried to compile the game multiple "Malformed file. Source files must be encoded with UTF-8." errors occurred 
i hadn't edited the source code that much since i had last opened it, and i had only edited the "StoryMenuState" file
i've also never edited the FreeplayMenuState file at all, so i'm not completely sure why this is happening
![image_2022-07-12_215224106](https://user-images.githubusercontent.com/95445733/178640594-0d495d74-99a7-4d55-ac60-91ea648c016b.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

i changed a few things in the StoryMenuState file

**Comment by RowanSkie** [comment]
Open your files in Notepad++, head to "Encoding" and then set it to UTF-8.

And probably redownload everything since it's already UTF-8.
