### ISSUE TITLE
PsychEngine Crash bug

### ISSUE THREAD

**Issue by NoVaroLuvsFNF** [ShadowMario/FNF-PsychEngine#9659]
### Describe your bug here.

Hello PsychEngine Team. Please help me! My game keeps crashing when I run PsychEngine. I didn't even added a source code or compile anything but still it keeps crashing and this error pops up: 

Paths.hx (line 352)
TitleState.hx (line 327)
TitleState.hx (line 227)
flixel/util/FlxTimer.hx (line 195)
flixel/util/FlxTimer.hx (285)
flixel/FlxGame.hx (line 745)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I tried to remove GF and replace her with someone else...

**Comment by LuckyTheLuckyBlock** [comment]
same thing happend to me, if you didnt name the new file "gfDanceTitle" or the sprite sheet names arent "gfDance", it wont work. if none of that happend, idk what happend.

**Comment by NoVaroLuvsFNF** [comment]
Thx. I fixed the bug and my game doesn't crash anymore :D

But I still have problems compiling my game. I downloaded and installed everything that are needed for compiling the game with source code. But still whenever I try to compile my game there's a error appearing in command prompt and Powershell that FunkinLua.hx line 342-346 Int should be Bool. Another error pops up later saying line 342 characters 55-56 missing ;

Please help me fix these errors. I really want to compile my game with winning icons :(

I use Visual Studio Code 2022 Community for coding the source code.

**Comment by theo2yeah** [comment]
> Thx. I fixed the bug and my game doesn't crash anymore :D
> 
> But I still have problems compiling my game. I downloaded and installed everything that are needed for compiling the game with source code. But still whenever I try to compile my game there's a error appearing in command prompt and Powershell that FunkinLua.hx line 342-346 Int should be Bool. Another error pops up later saying line 342 characters 55-56 missing ;
> 
> Please help me fix these errors. I really want to compile my game with winning icons :(
> 
> I use Visual Studio Code 2022 Community for coding the source code.

Actually, it is recommanded to use Visual Studio *2019* as 2022 as some missing components needed for compiling

**Comment by frantastic24** [comment]
Uninstall luajit and install the one on the readme

**Comment by NoVaroLuvsFNF** [comment]
Ummm I don't see any readme. I uninstalled linc_luajit. Can you please give me the link of the luajit that I should download? Also I did install Visual Studio 2019 but when I run it, it shows Visual Studio 2022 :/

Can you please give me the link of visual studio 2019 with the compiling components? :(

**Comment by frantastic24** [comment]
The readme is shown in the repository by default, and you have a file search feature

**Comment by NoVaroLuvsFNF** [comment]
Ummm I'm still very confused. Do I find linc_luajit in command prompt? And what is respitory by default and how do I get there? And I don't see any file search feature... :/
I reinstalled linc_luajit Version 0.0.4. Is this the correct version that I need to install? 
And can you please give me Visual Studio 2019 Community download link?

**Comment by frantastic24** [comment]
The readme is the very first thing you see when opening this repository, there is no way you can miss it
Also, consider using Google

**Comment by NoVaroLuvsFNF** [comment]
Do I install linc_luajit from here? 

https://lib.haxe.org/p/linc_luajit/

**Comment by NoVaroLuvsFNF** [comment]
And which repository exactly??

**Comment by frantastic24** [comment]
You're not even reading my replies so good luck

**Comment by NoVaroLuvsFNF** [comment]
Noooo please don't leave :(

I am reading your replies, I just can't understand most of the things you're saying :(

please help me :<
