### ISSUE TITLE
How do you like go through hues of background

### ISSUE THREAD

**Issue by cheemynugget** [ShadowMario/FNF-PsychEngine#966]
### Describe your problem here.

I want the background to change colors like hue shifts

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

so far ive added characters and changed stage lua codes and a bit more but not much

**Comment by ShadowMario** [comment]
Shaders aren't supported in Lua yet.
