### ISSUE TITLE
Auto-update mechanism

### ISSUE THREAD

**Issue by RowanSkie** [ShadowMario/FNF-PsychEngine#9660]
### What feature do you want to get added on the **base** engine?

Been thinking for a while and basically, the idea I had is an auto-updater for Psych Engine. We do already have an outdated warning system, why not add an auto-updating mechanism?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by tylerandari12** [comment]
It certainly would make updating with modpacks in the mods folder easier...

**Comment by EyeDaleHim** [comment]
It's not that easy :/

**Comment by ShadowMario** [comment]
Clicking a button to download is so hard :(
