### ISSUE TITLE
Mechanics screen

### ISSUE THREAD

**Issue by joxu13v** [ShadowMario/FNF-PsychEngine#9663]
### Describe your problem here.

I'm looking to make a pre-song screen that explains a bit of the mechanics after the cutscene and dialogue similar to that of indie cross using .lua
Can you help me?
![1657726833504](https://user-images.githubusercontent.com/98199731/178774631-f5b427ba-f10a-435e-b9a4-55818d7f96ad.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
[Warning-Notice.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9103961/Warning-Notice.txt)
heres the file
put your image in mods/images, needs to be 1280x720
Rename the .txt to .lua

**Comment by TheKitBoi** [comment]
you can now close it
