### ISSUE TITLE
Hiding menu items

### ISSUE THREAD

**Issue by Soeiz** [ShadowMario/FNF-PsychEngine#9665]
### Describe your problem here.

Hi, I need some help for hiding menu items when they are not selected, at there "idle" pose.
I want them to disapear when their animations are not "selected"
Any help ? I upload the file here so that you can edit.
[MainMenuState.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9104103/MainMenuState.txt)
 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

MainMenuState

**Comment by EyeDaleHim** [comment]
```haxe
function changeItem(huh:Int = 0)
{
	curSelected = FlxMath.wrap(curSelected + huh, 0, menuItems.length - 1);

	if (curSelected >= menuItems.length)
		curSelected = 0;
	if (curSelected < 0)
		curSelected = menuItems.length - 1;

	menuItems.forEach(function(spr:FlxSprite)
	{
		spr.animation.play('idle');
		spr.visible = false;
		spr.updateHitbox();

		if (spr.ID == curSelected)
		{
			spr.animation.play('selected');
			var add:Float = 0;
			if(menuItems.length > 4) {
				add = menuItems.length * 8;
			}
			camFollow.setPosition(spr.getGraphicMidpoint().x, spr.getGraphicMidpoint().y - add);
			spr.centerOffsets();
		}
	});

```
I highly recommend not to ask people to do your work.

**Comment by Soeiz** [comment]
Thanks and I just asked for help, since I struggled making it.
