### ISSUE TITLE
idk how do i name it

### ISSUE THREAD

**Issue by WlloX** [ShadowMario/FNF-PsychEngine#9669]
### Describe your bug here.

when trying to load "Ectospasm" it would crash, here is repor
[PsychEngine_2022-07-13_20'18'25.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9104894/PsychEngine_2022-07-13_20.18.25.txt)
t

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 4427)
PlayState.hx (line 3092)
flixel/group/FlxGroup.hx (line 769)
PlayState.hx (line 3031)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

base game with mods

**Comment by frantastic24** [comment]
do you have any scripts that affect notes/strums

**Comment by WlloX** [comment]
i dont think so

**Comment by frantastic24** [comment]
something seems to be wrong with your notes, so check carefully
