### ISSUE TITLE
how to warp bg and add effects

### ISSUE THREAD

**Issue by cheemynugget** [ShadowMario/FNF-PsychEngine#967]
### Describe your problem here.

how u do that like look at the bg here

https://www.youtube.com/watch?v=em-87F0UL-w&t=60s

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

so far ive added characters and changed stage lua codes and a bit more but not much

**Comment by ShadowMario** [comment]
Shaders aren't supported yet in Lua.

**Comment by cheemynugget** [comment]
> Shaders aren't supported yet in Lua.

oh. is it gonna be supported soon?

**Comment by ByronisJoan** [comment]
yes
