### ISSUE TITLE
Problem with custom splashes

### ISSUE THREAD

**Issue by Dismatiyt** [ShadowMario/FNF-PsychEngine#9671]
### Describe your problem here.

I am using newest version of psych engine and I wanna import splashes from cancelles Sonic.exe mod and do code thing in lua that replaces original splashes with splashes from cancelled Sonic PC port creepypasta mod.
`function onCreate()
    if getPropertyFromGroup('unspawnNotes', i, 'noteType') == 'Note' then
        setPropertyFromGroup('unspawnNotes', i, 'noteSplashTexture', 'BloodSplash'); -- change splash
    end
end`
![Zrzut ekranu (25)](https://user-images.githubusercontent.com/109104924/178818738-25398e32-aa3b-42eb-9060-4ee24200466a.png)
Am I doing something wrong or this is an issue?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I edited combe stuff and that's it

**Comment by Mastercopper2346** [comment]
No

**Comment by Mastercopper2346** [comment]
He accidentally used them for the NOTE texture then the actual SLASH texture

**Comment by Mastercopper2346** [comment]
Wait nvm

**Comment by frantastic24** [comment]
You can edit replies instead of posting three different ones tf

**Comment by Dismatiyt** [comment]
I was trying and the same result :(

**Comment by Dismatiyt** [comment]
Nahhh

**Comment by Dismatiyt** [comment]
I'm gonna close this as not planned because no one is replying

**Comment by Dismatiyt** [comment]
clode

**Comment by Dismatiyt** [comment]
closing is not working

**Comment by Dismatiyt** [comment]
Yeah and now it's working
