### ISSUE TITLE
health bar problem

### ISSUE THREAD

**Issue by BernardoGP4504** [ShadowMario/FNF-PsychEngine#9672]
### Describe your problem here.

![Captura de Tela (14)](https://user-images.githubusercontent.com/101405920/178822547-98cb7d1d-5ef1-4c92-bb4c-7971778b7691.png)
same as #9304 but on pre compiled build

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, basically tried loading a custom healthbar image in mods/images

**Comment by BernardoGP4504** [comment]
Also, I've tried this multiple times and it didn't work

Em qua, 13 de jul de 2022 17:09, frantastic24 ***@***.***>
escreveu:

**Comment by frantastic24** [comment]
You used it wrong then

**Comment by BernardoGP4504** [comment]
Then at least tell how to use it because the wiki just shows it without an
example

Em qua, 13 de jul de 2022 19:37, frantastic24 ***@***.***>
escreveu:

**Comment by frantastic24** [comment]
It's one line of code, use both order functions there and figure it out

**Comment by itsDARK768** [comment]
You no longer need to do that, I just thought to myself how to add this kind of thing and I think this should work

function onCreatePost()
	runHaxeCode([[
		healthBarBG.loadGraphic(Paths.image('imageFileHere'));
	]])
end

Replace the image with your health bar image
Only works with psych 0.6.2 since thats when the runhaxe thing was added

**Comment by itsDARK768** [comment]
wait, lemme fix smth

**Comment by itsDARK768** [comment]
function onCreatePost()
	runHaxeCode([[
		game.healthBarBG.loadGraphic(Paths.image('imageFileHere'));
	]])
end

There we go

**Comment by frantastic24** [comment]
You don't need runHaxeCode

**Comment by BernardoGP4504** [comment]
> function onCreatePost()
> runHaxeCode([[
> game.healthBarBG.loadGraphic(Paths.image('imageFileHere'));
> ]])
> end

still has the damn bug

**Comment by BernardoGP4504** [comment]
> You no longer need to do that, I just thought to myself how to add this kind of thing and I think this should work
> 
> function onCreatePost() runHaxeCode([[ healthBarBG.loadGraphic(Paths.image('imageFileHere')); ]]) end
> 
> Replace the image with your health bar image Only works with psych 0.6.2 since thats when the runhaxe thing was added

also the 0.6.1 version works with runHaxeCode

**Comment by BernardoGP4504** [comment]
nvm fixed it
