### ISSUE TITLE
How to do a 3D sprites?

### ISSUE THREAD

**Issue by TalesTheFex** [ShadowMario/FNF-PsychEngine#9674]
### Describe your problem here.

I would like to make 3d character sprites for fnf, but how to do it? On request in the browser and on YouTube, it gives out sprites in paint 3d, but I need to take a separate model and make sprites like in sonic.exe in the battle with Tails doll or in the mod of fnaf

![ahtk](https://user-images.githubusercontent.com/99151748/178837990-c1729db0-bef4-454f-8db6-78370856a47e.png)
![cxx](https://user-images.githubusercontent.com/99151748/178838061-386b5045-b7e7-458c-be09-96c14e4c5a26.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Mastercopper2346** [comment]
You cant code anything. You have to draw it (without black outlines)

**Comment by frantastic24** [comment]
This isn't psych engine related

**Comment by ShadowMario** [comment]
Not psych engine related
