### ISSUE TITLE
how do i do this?

### ISSUE THREAD

**Issue by TheManwhoisdyinghere** [ShadowMario/FNF-PsychEngine#9676]
### Describe your problem here.

**does anyone know how to put stage objects on the hud?**
and also have it be animated?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Read the wiki

**Comment by TheManwhoisdyinghere** [comment]
> Read the wiki

that. doesn't help if i dont know what im doing.

**Comment by frantastic24** [comment]
That's the point of reading the wiki
Don't expect people to code for you

**Comment by TheManwhoisdyinghere** [comment]
> That's the point of reading the wiki Don't expect people to code for you

👍

**Comment by NotEpik** [comment]
setObjectCamera('that funny object name', 'hud')

**Comment by Parsellol** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Custom-Sprites-Functions#makeanimatedluaspritetagstring-imagestring-xfloat-yfloat

https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#setobjectcameraobjstring-camerastring
