### ISSUE TITLE
is this source code only or can it be used as a script?

### ISSUE THREAD

**Issue by TheManwhoisdyinghere** [ShadowMario/FNF-PsychEngine#9679]
### Describe your problem here.

Is there a way to make the **opponent's side be in downscroll and not change boyfriends** as well with a script or is this source coding only?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Meme1079** [comment]
```lua
function onCreatePost()
     for i = 0,7 do
          setPropertyFromGroup('opponentStrums', i, 'downScroll', true)
          setPropertyFromGroup('opponentStrums', i, 'y', 570)
     end
end
```
