### ISSUE TITLE
Here Is My Question

### ISSUE THREAD

**Issue by Raulmegapro2303** [ShadowMario/FNF-PsychEngine#9681]
### What is your question?

Why Don't Add A Stage Editor?

**Comment by TheRealJake12** [comment]
close this. He's working on it.

**Comment by TFLTV** [comment]
> ### What is your question?
> Why Don't Add A Stage Editor?

close this

**Comment by Mastercopper2346** [comment]
CLOSE BEDORW BANNED

**Comment by tylerandari12** [comment]
CCLOSE THIS AND RUN BEFORE ITS TOO LATE!!!

**Comment by Mastercopper2346** [comment]
👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏

**Comment by tylerandari12** [comment]
Good job :D
