### ISSUE TITLE
Songs won't start countdowns if the 'onStartCountdown' function is used without 'return Function_Continue;' in it.

### ISSUE THREAD

**Issue by ChoccyMilk2** [ShadowMario/FNF-PsychEngine#9687]
### Describe your bug here.

(this happens on versions 0.6.1 and up)

function OnStartCountdown()
return Function_Continue;         (without this the song doesn't play at all)
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited the mods folder.

**Comment by itsDARK768** [comment]
Well no crap mate, that line continues the function.

**Comment by ChoccyMilk2** [comment]
> Well no crap mate, that line continues the function.

it worked before without needing it 0n 0.5.2h, there's no reason it shouldn't work on 0.6 unless it had been changed in the update.
Thats why i want to know also if this is a bug or whether or not this was intended.

**Comment by Mastercopper2346** [comment]
its not a bug, thats how lua works
