### ISSUE TITLE
Making dad (enemy) not able to press hurt notes.

### ISSUE THREAD

**Issue by guizinhomartinez** [ShadowMario/FNF-PsychEngine#969]
### What feature do you want to get added on the base engine?

When doing charts where dad (enemy) has hurt notes he just gives up and press all of them making it kinda strange.
It would be cool to see dad not being able to press them to feel like he's actually playing, instead of just pressing all of the notes without caring what he presses.

**Comment by ShadowMario** [comment]
ignoreNote variable
