### ISSUE TITLE
Something Wrong with NoteTweenAlpha

### ISSUE THREAD

**Issue by Roselyn393** [ShadowMario/FNF-PsychEngine#9691]
### Describe your bug here.

When Using a .lua Script A few Note Tweens will work but the remaining note Tween Alpha's will not work keeping the notes visible

Here's the code i used, it might be me or it might be the Lua Script Api

### function onUpdate()
	if curStep == 0 then
          noteTweenAlpha('Blah1', 0, 0, 0.001, 'linear');
	  noteTweenAlpha('Blah2', 1, 0, 0.001, 'linear');
	  noteTweenAlpha('Blah3', 2, 0, 0.001, 'linear');
	  noteTweenAlpha('Blah4', 3, 0, 0.001, 'linear');
  	  noteTweenAlpha('Blah5', 4, 0, 0.001, 'linear');
	  noteTweenAlpha('Blah6', 5, 0, 0.001, 'linear');
	  noteTweenAlpha('Blah7', 6, 0, 0.001, 'linear');
          noteTweenAlpha('Blah8', 7, 0, 0.001, 'linear');
    end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing In the build

**Comment by Roselyn393** [comment]
Note, when using skip time to set it back to 0 after song starts it works

**Comment by frantastic24** [comment]
Not a bug , strums get tweened at the start, overriding your tween
Use `setProperty('skipArrowStartTween', true)`

**Comment by Roselyn393** [comment]
alr thanks
