### ISSUE TITLE
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths

### ISSUE THREAD

**Issue by theo2yeah** [ShadowMario/FNF-PsychEngine#9693]
### Describe your problem here.

For some reason, for 3 days, i was blocked by this error while compiling
after this:
 ` ` `
source/options/NoteOffsetState.hx:60: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
 ` ` `
This happened
 ` ` `
F:\Jeux\FRIDAY NIGHT FUNKIN'\Theoyeah-Engine\export\release\windows\obj>setlocal enabledelayedexpansion 
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
 ` ` `
I tried to re-install everything, even trying to use Haxe 4.2.5, checking 4 times if i had the correct components and still, **nothing happened**

It would be extremely grateful if someone can help me fix this issue

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

huuhhhhh, too much stuff to list

**Comment by theo2yeah** [comment]
Fixed, i tried using a specific version of visual studio 2019 and it works!

**Comment by KELOTOMU** [comment]
What 2019 version do I need?

**Comment by MaIfunctional** [comment]
I'm sorry to revive this, but which 2019 version did you use to solve this issue? I have had the same error as well.
