### ISSUE TITLE
Help me for my mod

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#9694]
# Issue
I need Help. i'm making a (source code) mod and i need to know what method i sould do.
The name is 'Poison Note'

## Method 1:
Make you health slowly go down. More you press it, faster it goes down.
(i have to use poopy lua for this >:( )

## Method 2:
Your health is forced to a (low) random amount for 5-10 seconds

# 
Also good job if you read the title right

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

what

**Comment by aflacc** [comment]
why did you put the name backwards that was uncalled for

**Comment by Mastercopper2346** [comment]
To see if anyone would come
