### ISSUE TITLE
How do I change the ratings at the bottom?

### ISSUE THREAD

**Issue by PotatoKing0419** [ShadowMario/FNF-PsychEngine#9695]
### Describe your problem here.

So that stuff at the bottom with the rating stuff like      Rating: Perfect!! (100%)

How do I turn that into something like     Rating: Show-off (100%)

or     Rating: Bruh (50%)

or     Rating: Ur Trash Kid (0%)

I use lua cuz i suck at source code

Idc if its a script or an event or whatever i just want it in my mod plz ;-;

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by Lorekeeper49** [comment]
The vs Whitty definitive edition has a Kade engine accuracy script that changes those ratings and makes the accuracy millisecond based.  There's only one problem though: there is no way to make the accuracy not be millisecond based while using that script, trust me, I've tried.  So in that case, you might not want to use it if you don't want millisecond based accuracy

**Comment by NotEpik** [comment]
[This should help!](https://gamebanana.com/tools/9776)

**Comment by PotatoKing0419** [comment]
> [This should help!](https://gamebanana.com/tools/9776)

Thanks!
