### ISSUE TITLE
I NEED HELP WITH THIS BUG IN PSYCH 0.5.1

### ISSUE THREAD

**Issue by WilliamGaming12** [ShadowMario/FNF-PsychEngine#9696]
### Describe your bug here.

When i try to compile the game, this error appears:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/102251392/179078164-a80103c7-682c-45c6-b9c5-8fd7b91cf099.png">
I NEED THIS VERSION OF PSYCH

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Mastercopper2346** [comment]
Idk

**Comment by frantastic24** [comment]
Outdated version isn't a valid bug

**Comment by CrusherMods** [comment]
update haxe

**Comment by SollaxxREALONE** [comment]
update the engine to 0.6.2

**Comment by WilliamGaming12** [comment]
dude i need this version for put the charts in KE

**Comment by WilliamGaming12** [comment]
bruh i need this for be able to put the charts in  
a kade engine mod. Versions that are higher than 0.5.1 doesn't work on kade engine
