### ISSUE TITLE
Dadbattle Spotlight

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#9701]
### Describe your bug here.

Game crashes, when using the Dadbattle Spotlight anywhere else
(Tested on Week 7 songs)

Edit:
Looked up in code, and it can be only used on "stage" which is a bit of a shame tho
(reason: the smoke)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not really, no

**Comment by BeastlyGhost** [comment]
not a bug, both Dadbattle Spotlight and Philly Glow are hardcoded to their stages to avoid the same deal we had with Blammed Lights

**Comment by ZeitHeld** [comment]
what was the problem with it?

**Comment by BeastlyGhost** [comment]
> what was the problem with it?

people milking it as they didn't have creativity in mind apparently, shadowmario then got rid of Blammed Lights and hardcoded the new Philly Glow to week 3, to avoid similar issues, he also hardcoded Dadbattle Spotlight to week 1

keep in mind, they are hardcoded to their weeks, not specifically Blammed and Dadbattle, you can use then as long as you are still on Week 1 or Week 3

**Comment by ZeitHeld** [comment]
that's sad.

even though the blammed lights didn't make that much for me. often it was even out of place.
Though, then I think I'll try to get away with a softcoded version for personal uses

might also help me learning
