### ISSUE TITLE
Adding a Song Issue

### ISSUE THREAD

**Issue by Qecci** [ShadowMario/FNF-PsychEngine#9702]
### Describe your bug here.

You know the whole "Reload Audio" option inside the chart editor, right? Well I'm clicking that, and nothing is happening.
I have the correct folder, I put the audio inside of the correct folder, I have the audio as a .ogg, and it's still not working.
Help.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by ZeitHeld** [comment]
make sure there is at least one file called
`"Inst.ogg"`

exact capitalization

**Comment by Qecci** [comment]
> make sure there is at least one file called `"Inst.ogg"`
> 
> exact capitalization

I have it exactly named that.

**Comment by itsDARK768** [comment]
Check the inst and voices files to make sure that there is audio and also make sure your game is not muted.

**Comment by Qecci** [comment]
Okay, that was magic. I did nothing and it fixed itself.

**Comment by frantastic24** [comment]
Close the issue then
