### ISSUE TITLE
issue with the source code

### ISSUE THREAD

**Issue by aflacc** [ShadowMario/FNF-PsychEngine#9703]
### Describe your problem here.

im trying to compile version 0.6.2 and im getting this error:
```
source/FunkinLua.hx:342: lines 342-346 : Int should be Bool
source/FunkinLua.hx:342: lines 342-346 : For function argument 'f'
```
I looked at the what it's referring to and its referring to these lines (342-346)
```
}else if(Lua.isboolean(luaInstance.lua,-1)){
							Lua.pushboolean(lua, Lua.toboolean(luaInstance.lua, -1));
						}else{
							Lua.pushnil(lua);
						}
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no i literally just downloaded the source code

**Comment by frantastic24** [comment]
Uninstall luajit and install the one on the readme
