### ISSUE TITLE
How the heck do I use the adobe animate texture atlas

### ISSUE THREAD

**Issue by itsDARK768** [ShadowMario/FNF-PsychEngine#9704]
### Describe your problem here.

I have been sitting here for a few minutes trying to figure out how to use these for json characters since I want to test out some stuff, I have tried reading the official tutorial but that barely helped at all.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing but adding a single lua stage

**Comment by Mastercopper2346** [comment]
idk but i heard somthing about using 8-UTF

**Comment by frantastic24** [comment]
Make a folder anywhere in images and place your files inside, in the character editor type that directory
