### ISSUE TITLE
Spooky House Stage

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#9705]
### Describe your bug here.

Did.. nobody really notice that before? Or mention it, like, at all?
The Week2 Stage is.. a bit off centered. Or at least for me, with my weird screen

I think the brighter layer should hit the screen end-

![image](https://user-images.githubusercontent.com/76132257/179119842-dec601c0-a4f6-4153-9148-8f2efb390c74.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

n o

**Comment by itsDARK768** [comment]
Just lower that part, thats all you really need to do.

**Comment by itsDARK768** [comment]
but source is required.

**Comment by ZeitHeld** [comment]
And I can't compile at all. My computer says no then
And I guess it would be nice for everyone

**Comment by frantastic24** [comment]
Pretty sure this is from the original game

**Comment by ZeitHeld** [comment]
damn, it is-
though, it wouldn't be bad to fix it-

![image](https://user-images.githubusercontent.com/76132257/179122609-fc783c7d-d188-4ade-9f4f-c28104b0b251.png)

**Comment by BernardoGP4504** [comment]
change the `"camera_boyfriend"`'s y value (second number in brackets)
