### ISSUE TITLE
White Void instead of Black

### ISSUE THREAD

**Issue by Gabri7075** [ShadowMario/FNF-PsychEngine#9706]
### What is your question?

Hi!
Is it possible to change the black void to a different color in .lua/Downloaded Build?

Thanks!

**Comment by frantastic24** [comment]
you can just use `makeGraphic()` with white

**Comment by Gabri7075** [comment]
How do I use it?

**Comment by frantastic24** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#makegraphicobjstring-widthint-heightint-colorstring

**Comment by Mastercopper2346** [comment]
Necessarily the VOID, I don’t think you can even do that with source this is the closest thing it can be done.
