### ISSUE TITLE
Freeplay crashed!

### ISSUE THREAD

**Issue by AngelGamer94GIT** [ShadowMario/FNF-PsychEngine#9707]
### Describe your bug here.

Hi its me again, I literally opened the freeplay menu and crashed.

FreeplayState.hx (line 74)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

Im not using the source by the way.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't

**Comment by fnfdemonboi314159** [comment]
It might be cause some files are in the wrong place :skull:

Have you checked the weeks folder and the files in said folder?

**Comment by fnfdemonboi314159** [comment]
> It might be cause some files are in the wrong place 💀
> 
> Have you checked the weeks folder and the files in said folder?

I would know, I've had this issue before.
