### ISSUE TITLE
Disable difficulty

### ISSUE THREAD

**Issue by LucaGoku** [ShadowMario/FNF-PsychEngine#971]
### Describe your problem here.

Can i disable a difficulty for just 1 week? I'm porting V.S. Matt btw

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didn't

**Comment by DEV-idiotXD** [comment]
just make all the charts the same or delete the code for easy and normal and leave the one difficulty u want

**Comment by LucaGoku** [comment]
@DEV-idiotXD The week 1 is Easy, Normal, Hard and Old and the week 2 is Easy, Normal and Hard

**Comment by ShadowMario** [comment]
No, but you can make all charts the same.

**Comment by LucaGoku** [comment]
@ShadowMario What do you mean?

**Comment by DEV-idiotXD** [comment]
> @ShadowMario What do you mean?

take a hint?

get the chart for the difficulty u want then copy and paste it twice then just rename it

**Comment by LucaGoku** [comment]
Ok
