### ISSUE TITLE
How do i make my arrow sprites work?

### ISSUE THREAD

**Issue by NewSajgonki** [ShadowMario/FNF-PsychEngine#9711]
### What is your question?

So i wanted to make a custom arrow sprite but idk how to lol :V (also im just modding fnf and im not a coder lol)
here are my sprites:
![NOTE_assets](https://user-images.githubusercontent.com/108466805/179237182-cb2b6c1b-6f24-428a-a0e0-b9b86da16140.png)

**Comment by noskincz** [comment]
if you are using downloaded buld just go to chrat editor and there should be somwhere a box and above it says: note texture, write in the name of your note texture and then it should be done

**Comment by NewSajgonki** [comment]
but when ever i set note texture to my own it crashes

**Comment by NewSajgonki** [comment]
i don't have any adobe

**Comment by NewSajgonki** [comment]
Also im using a coding program called Microsoft Visual Studio

**Comment by noskincz** [comment]
[githubnotes.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9122231/githubnotes.txt)
heres a .txt file just change the name and format and you will have working note sprites

**Comment by NewSajgonki** [comment]
the .txt file doesn't work either

**Comment by BeastlyGhost** [comment]
change the text extension to xml and change it's name to your note assets name

**Comment by NewSajgonki** [comment]
oooh right xd

**Comment by NewSajgonki** [comment]
nah still nothing

**Comment by ROCK201888** [comment]
1.replace the normal note sprite if you want all songs have the custom note sprite       2.if you just want 1 or more songs, put the sprite in to mods/image, and go to the song you want to have the notes, go to chart debug(press 7 in song) and open "song", and type in your custom note sprite's name under "note texture:"
