### ISSUE TITLE
Freeplay songs to the left

### ISSUE THREAD

**Issue by Isaagomen** [ShadowMario/FNF-PsychEngine#9714]
### Describe your problem here.

So basically, i want the freeplay songs to go to the left, i know how to do it with menus but not freeplay. can someone help me??

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by SuperSonic472** [comment]
its already on the left please find a actual problem
