### ISSUE TITLE
Major Screw-Up in the Options

### ISSUE THREAD

**Issue by Bopple-McNuggets** [ShadowMario/FNF-PsychEngine#9717]
### Describe your problem here.

So basically, my brother somehow accidentally changed my controls so that the only way to accept is with "PgUp". The problem is that this button is also connected to "Back", so any time I try to accept a menu option, it sends me back to the title screen before I can advance. Is there any way to change this outside of the options menu, or accept using a different input I'm missing? If I can't change this I may be permanently locked out of anything in Psych Engine.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
#8402
