### ISSUE TITLE
Uuuhhh need a hypno's lullaby hud on psych 0.5.2h+

### ISSUE THREAD

**Issue by Plotsh** [ShadowMario/FNF-PsychEngine#9718]
### What is your question?

![Screenshot_20220715-194205](https://user-images.githubusercontent.com/84821153/179323271-cba81ae8-8dc1-4249-8d9a-7c170d4c8dba.png)
if someone can make it ill be happy

**Comment by Superiron12321** [comment]
what do you mean by hud, do you mean the information bar?

**Comment by frantastic24** [comment]
That's literally the psych hud

**Comment by Lorekeeper49** [comment]
> That's literally the psych hud

It's actually a little bit different if you couldn't tell, that why they're trying to change the default hud to that

**Comment by frantastic24** [comment]
Oh wow it doesn't have brackets!! So different
They're not even "trying to change it" they literally just told someone else to do it for them

**Comment by Superiron12321** [comment]
put this under help wanted, and instead ask for someone to to tell you how to do it

**Comment by frantastic24** [comment]
You can also just fucking search in issues because this has been answered many times already

**Comment by BeastlyGhost** [comment]
```Lua
function onUpdatePost()
    if ratingFC == '' then -- if the FC is nothing
        setProperty('scoreTxt.text', 'Score: ' .. score .. ' | Combo Breaks: ' .. misses .. ' | Accuracy: 0.00%')
    else
        setProperty('scoreTxt.text', 'Score: ' .. score .. ' | Combo Breaks: ' .. misses .. ' | Accuracy: ' ..round(rating * 100, 2).. ' [' ..ratingFC..']')
    end
end

function round(x, n)
  n = math.pow(10, n or 0)
  x = x * n
  if x >= 0 then x = math.floor(x + 0.5) else x = math.ceil(x - 0.5) end
  return x / n
end
```

**Comment by Plotsh** [comment]
> ```lua
> function onUpdatePost()
>     if ratingFC == '' then -- if the FC is nothing
>         setProperty('scoreTxt.text', 'Score: ' .. score .. ' | Combo Breaks: ' .. misses .. ' | Accuracy: 0%')
>     else
>         setProperty('scoreTxt.text', 'Score: ' .. score .. ' | Combo Breaks: ' .. misses .. ' | Accuracy: ' ..round(rating * 100, 2).. '% [' ..ratingFC..']')
>     end
> end
> 
> function round(x, n)
>   n = math.pow(10, n or 0)
>   x = x * n
>   if x >= 0 then x = math.floor(x + 0.5) else x = math.ceil(x - 0.5) end
>   return x / n
> end
> ```
> 
> NOTICE: change `onUpdatePost()` to `onUpdateScore()` if you are using the actions build, or the next update came out

nice
