### ISSUE TITLE
Trouble with a tween event

### ISSUE THREAD

**Issue by ADuckInBlack** [ShadowMario/FNF-PsychEngine#9720]
### Describe your problem here.

Hello! I have an event I made to spin the notes when triggered, and it seems to only trigger once even though I have 4 of the event down. Help would be appreciated!

(Side note: It only spins one note at the moment, as I wanna do the rest once a troubleshoot this one.)

(Code):
![image](https://user-images.githubusercontent.com/33814766/179327511-e90ee543-d572-4931-907b-2dc41fb9cba8.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment]
Either make the angle reset to 0 once it finishes or make it tween by adding to the current angle

**Comment by ADuckInBlack** [comment]
good idea!

**Comment by ADuckInBlack** [comment]
good news! it sorta worked, and the solution was way simpler than i had thought, but it's still not perfect. i can't figure out a way to properly reset it, so i used a tween and it looks a little weird as it spins back into position. i'd say this issue is completed, but if there's any way to improve the code, i'd appreciate the help.
![image](https://user-images.githubusercontent.com/33814766/179336207-8139e91e-6617-452d-afef-69c369f1a568.png)

**Comment by frantastic24** [comment]
1. Why is there a function inside a function
2. Why are you using a tween, setProperty exists

**Comment by ADuckInBlack** [comment]
> 1. Why is there a function inside a function
> 2. Why are you using a tween, setProperty exists

1. I have no idea what the alternatives are. (me bad programmer)
2. I don't know which property is the note rotation.

**Comment by frantastic24** [comment]
The alternative is... Not having one inside the other?
The property is literally in the function name

**Comment by ADuckInBlack** [comment]
> The alternative is... Not having one inside the other? The property is literally in the function name

Fair point.
Also, can you elaborate?

**Comment by frantastic24** [comment]
Look at the tween function you're using, what property could it be

**Comment by ADuckInBlack** [comment]
Oh! Damn! I see what you mean!

**Comment by ADuckInBlack** [comment]
I also just realized why having a function inside a function was a mistake.

**Comment by ADuckInBlack** [comment]
After hours of research, trial, and error, I've finally made it work. Thanks for helping, man!


(Here's the code by the way, if you're curious.)
![image](https://user-images.githubusercontent.com/33814766/179389792-e022c227-f0df-4bdb-b46d-68867a308ca0.png)

**Comment by ADuckInBlack** [comment]
just realized i forgot to remove the variable i used for debugging
