### ISSUE TITLE
funkinlua

### ISSUE THREAD

**Issue by InfinityKid2048** [ShadowMario/FNF-PsychEngine#9723]
### Describe your problem here.

I downloaded 6.2 and it won't compile because of a problem in funkinlua.hx. It works perfectly with 6.0 and below

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, it's a fresh copy of 0.62

**Comment by TheKitBoi** [comment]
Send in the Error Details
