### ISSUE TITLE
I have no idea what happened

### ISSUE THREAD

**Issue by Lorekeeper49** [ShadowMario/FNF-PsychEngine#9729]
### Describe your problem here.

I built the game with the proper command and it worked, then I decided to start changing the code and the command prompt abruptly doesn't recognize any of my commands once I try to build the game again.  what did I do to cause this?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed project.xml but that's it

**Comment by EyeDaleHim** [comment]
Not enough information, provide what you changed, and what errors did it give.

**Comment by Lorekeeper49** [comment]
> Not enough information, provide what you changed, and what errors did it give.

There were no errors, the command prompt just wouldn't recognize the command

**Comment by Lorekeeper49** [comment]
Looks like I just needed to reinstall haxe
