### ISSUE TITLE
BF's Death Animation Appearing No Matter What

### ISSUE THREAD

**Issue by SomeDumbasss** [ShadowMario/FNF-PsychEngine#973]
### Describe your bug here.

When I created a new "BF" player, I gave it a much different animation than the regular blueballed death. I made sure to name the things "firstDeath", "deathLoop", and "deathConfirm" as those are the same as normal BF. Going to a song and testing it, it just resorted back to BF getting blueballed. If anyone knows a work-around from this, please let me know. If not, I'll just simply wait for the next version of Psych Engine.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No edits were made in the source code.

**Comment by DEV-idiotXD** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API

here scroll down till you find example scripts and see the example for setpropertyfromgroup example then change the stuff to be the same as the corresponding stuff

**Comment by SomeDumbasss** [comment]
> https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API
> 
> here scroll down till you find example scripts and see the example for setpropertyfromgroup example then change the stuff to be the same as the corresponding stuff

And where exactly do I put the edited script?

**Comment by SrtHero278** [comment]
Well it says 'script.lua' so I think you should put it in your song data folder

**Comment by SomeDumbasss** [comment]
Nice! It worked. Thanks so much.

**Comment by DEV-idiotXD** [comment]
> Nice! It worked. Thanks so much.

np
