### ISSUE TITLE
direction?

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#9730]
### Describe your problem here.

so how does 'direction' work?

I'm sure this is close to how it works:
```lua
function goodNoteHit(direction)
    if direction == 2 then
        --code 'n stuff
    end
end
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No (other than the accuracy 'ratingStuff'), just modded in the "example_mods" folder

**Comment by Lorekeeper49** [comment]
0 is left
1 is down
2 is up
3 is right

That's basically the gist of it

**Comment by frantastic24** [comment]
`direction` is the second value, with that function you're only getting `id`
```lua
function goodNoteHit(id, direction, type, sustain)
```
You can change their names, but the order will always be the same

**Comment by TFLTV** [comment]
> `direction` is the second value, with that function you're only getting `id`
> 
> ```lua
> function goodNoteHit(id, direction, type, sustain)
> ```
> 
> You can change their names, but the order will always be the same

lol it worked

**Comment by TFLTV** [comment]
and I forgot to close
