### ISSUE TITLE
Custom Opponents (dad) Notes

### ISSUE THREAD

**Issue by Omlight1** [ShadowMario/FNF-PsychEngine#9731]
### Describe your problem here.

Hello! I'm making my mod, and i'm have issue. I'm don't know how to make custom opponents notes in **Psych Engine 4.2**. Like it be in Bob and Bosip mod. Like: 
https://cdn.discordapp.com/attachments/982251158926155796/997779081514979378/dad.png
Please, help me!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I'm edited PlayState.hx, and HealthIcon.hx

**Comment by FlintIshe** [comment]
I only know how to do with lua , source I have no idea
