### ISSUE TITLE
BENDY659

### ISSUE THREAD

**Issue by BENDY659** [ShadowMario/FNF-PsychEngine#9733]
### Describe your bug here.

I wanted to see the sprites of "pico-speaker", but this error crashes! I hope it will be fixed :)
( I'm Russian and I don't know English well, so I can write something wrong, but I did everything right )
initially, I thought that I had made up my mind, went, opened a clean version and it's the same there, I just wanted to see what part of the sprites is responsible for what. And then there is nothing incomprehensible in ".xml", and in ".png" too:(
[translator]
[PsychEngine_2022-07-16_21'52'21.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9125794/PsychEngine_2022-07-16_21.52.21.txt)

### Command Prompt/Terminal logs (if existing)

```bash
Character.hx (line 373)
Character.hx (line 252)
editors/CharacterEditorState.hx (line 925)
editors/CharacterEditorState.hx (line 434)
FlxUIDropDownMenuCustom.hx (line 500)
FlxUIDropDownMenuCustom.hx (line 361)
flixel/ui/FlxButton.hx (line 521)
flixel/addons/ui/FlxUITypedButton.hx (line 1172)
flixel/addons/ui/FlxUIButton.hx (line 362)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I launched a completely clean version

**Comment by TFLTV** [comment]
Вы запустили его в режиме чартов, если это так, то вам нужен
pico-speaker.json в папке данных песни?
[translator]

**Comment by TFLTV** [comment]
Я узнал! выберите песню «stress» и перейдите в режим чарта и 
нажмите «backspace» и зайдите в редактор персонажей 
выберите «pico-speaker» и готово!
[translator]

**Comment by BENDY659** [comment]
thanks, I'll try)

**Comment by BENDY659** [comment]
Thank you so much for your help)
