### ISSUE TITLE
Healthbar

### ISSUE THREAD

**Issue by schwiftified** [ShadowMario/FNF-PsychEngine#9738]
### What is your question?

How can i move the healthbar on lua?

**Comment by tylerandari12** [comment]
The sprites that are the bar are `healthBar` and `healthBarBg` (or `healthBarBG` im not sure)

`healthBar` is the colorful part of the bar
`healthBarBg` is the part behind the bar

They function like normal Lua sprites and can be manipulated with `setProperty()`

**Comment by BernardoGP4504** [comment]
```
setProperty('healthBar.x', value here)
setProperty('healthBarBG.x', value here)
```
or
```
setProperty('healthBar.y', value here)
setProperty('healthBarBG.y', value here)
```
`value here` = where to move it

**Comment by schwiftified** [comment]
thanks

**Comment by JamJarIsDumb** [comment]
Does this still work or has it changed?

**Comment by BernardoGP4504** [comment]
> Does this still work or has it changed?

It has been changed on 0.7 and above
Now it's only `healthBar.x` and `healthBar.y`. Moving those 2 applies on the entire health bar
