### ISSUE TITLE
changing bg mid song

### ISSUE THREAD

**Issue by whizlmao** [ShadowMario/FNF-PsychEngine#9739]
### Describe your bug here.

idk if this is a genuine bug or im just a lil slow but whenever i change the bg in this one point of the song the offset it very wrong and ive went into mods/stages and changed the offset nothing worke

https://user-images.githubusercontent.com/109429038/179362385-e62245c7-6c2c-4ddb-8f0f-02613868380f.mp4

^^^^ video proof

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i added background to the game thats it

**Comment by BernardoGP4504** [comment]
would you mind send over the script for this just so i can test it

**Comment by frantastic24** [comment]
Is this done using `playAnim`? If so, use `objectPlayAnimation`
