### ISSUE TITLE
I don't get many objects in the main weeks

### ISSUE THREAD

**Issue by ElcreeperGDxd** [ShadowMario/FNF-PsychEngine#9740]
### Describe your bug here.

in week 2 I don't get gf when I play and when I go to the monster song I don't get moster (character), week 4 I don't get mommy's bodyguards, week 5 I don't get daddy or mommy and when the third song starts it closes, week 6 I don't get sempai's faanatics and week 7 in the third song I don't get tankmans being shot by pico, it's funny because pico doesn't shoot anything, I need help with this.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by tylerandari12** [comment]
Only thing I would think is that low quality mode is on in the settings...

**Comment by ElcreeperGDxd** [comment]
> 

when I opened it, it was not in low quality, then I activated it in low quality and the same thing happened.
