### ISSUE TITLE
Changing spirit's character mid song but the trail stays the same

### ISSUE THREAD

**Issue by tdog8785** [ShadowMario/FNF-PsychEngine#9742]
### Describe your problem here.

I am trying to have spirit change characters mid song but only problem is that the evil trail doesn't follow the character change and it stays as the regular spirit and doesn't follow the new character.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing worth noting

**Comment by ShadowMario** [comment]
Because it is attached to the original Dad character...
