### ISSUE TITLE
endSong() crashes the game...

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#9744]
### Describe your bug here.

Pretty self explanatory...
`endSong()` will sometimes crash and other times make it where you cant hit notes...
(`exitSong()` is fine tho)
The reason I'm making this is because whenever a song ends the game crashes with no error output and I'm confused...

### Command Prompt/Terminal logs (if existing)

```bash
none :(
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing changed. On 0.6.2 by the way.

### IF YOURE TOO LAZY TO DO ANYTHING ABOUT THIS PUT THIS IN THE SCRIPTS FOLDER:
```lua
-- if the song crashes put this in the scripts folder
function onUpdate()
	if getSongPosition() > songLength - 2 then
		exitSong()
	end
end
```

**Comment by machonessiebaby** [comment]
please show your Lua script please

**Comment by tylerandari12** [comment]
I'm more worried about it crashing at the end of a song but here...

a debug thing to end the song early
```lua
function onUpdate()
     if keyboardJustPressed("E") then
          endSong()
     end
end
```

**Comment by TheKitBoi** [comment]
> I'm more worried about it crashing at the end of a song but here...
> 
> a debug thing to end the song early
> 
> ```lua
> function onUpdate()
>      if keyboardJustPressed("E") then
>           endSong()
>      end
> end
> ```

then add the
function on endSong()
end
because that will fix the crashing

**Comment by BernardoGP4504** [comment]
use `onEndSong()`

**Comment by tylerandari12** [comment]
> use `onEndSong()`

Thats whats crashing the game tho...

**Comment by tylerandari12** [comment]
HERE'S A TEMPORARY WORKAROUND!!!
```lua
-- if the song crashes put this in the scripts folder
function onUpdate()
	if getSongPosition() > songLength - 2 then
		exitSong()
	end
end
```

**Comment by tylerandari12** [comment]
> > I'm more worried about it crashing at the end of a song but here...
> > a debug thing to end the song early
> > ```lua
> > function onUpdate()
> >      if keyboardJustPressed("E") then
> >           endSong()
> >      end
> > end
> > ```
> 
> then add the function onendSong() end because that will fix the crashing

You mean...
```lua
function onEndSong()
      return Function_Continue
end
```
?

**Comment by TheKitBoi** [comment]
> > > I'm more worried about it crashing at the end of a song but here...
> > > a debug thing to end the song early
> > > ```lua
> > > function onUpdate()
> > >      if keyboardJustPressed("E") then
> > >           endSong()
> > >      end
> > > end
> > > ```
> > 
> > 
> > then add the function onendSong() end because that will fix the crashing
> 
> You mean...
> 
> ```lua
> function onEndSong()
>       return Function_Continue
> end
> ```
> 
> ?

havent you see my reply
replace onEndSong with onendSong
that why its the opposite

**Comment by tylerandari12** [comment]
> 

Took me a minute to understand this but I think I've got it...

```lua
function onendSong()
      return Function_Continue
end
```

**Comment by tylerandari12** [comment]
I now see no reason to keep this open...
