### ISSUE TITLE
Another healthBar thing

### ISSUE THREAD

**Issue by schwiftified** [ShadowMario/FNF-PsychEngine#9745]
### What is your question?

How can i make the healthbar like this?
![example](https://user-images.githubusercontent.com/96924332/179367656-1879f84d-8228-4e51-aaf5-fac31fc2be44.png)

**Comment by bruh1cat** [comment]
https://gamebanana.com/tools/9651

**Comment by BernardoGP4504** [comment]
```
setProperty('healthBar.angle', your value)
setProperty('healthBarBG.angle', your value)
```
you already know what `your value` is

**Comment by BernardoGP4504** [comment]
> ```
> setProperty('healthBar.angle', your value)
> setProperty('healthBarBG.angle', your value)
> ```
> 
> you already know what `your value` is

with this you can set it to be at whatever angle (rotation)

**Comment by schwiftified** [comment]
> ```
> setProperty('healthBar.angle', 90)
> ```

thanks
