### ISSUE TITLE
Random loading screen error

### ISSUE THREAD

**Issue by Nullyz** [ShadowMario/FNF-PsychEngine#9748]
### Describe your problem here.

hi guys I'm here again, well I'm using version 0.5.2h (sharders) and well I tried to put random loading screen and got this error: 
Error: Cache.cpp
./src/Cache.cpp(320): error C2440: 'initializing': unable to convert from 'openfl::media::Sound' to 'String'
./src/Cache.cpp(320): note: Constructor for class 'String' is declared as 'explicit'
./src/Cache.cpp(336): error C2440: 'initializing': unable to convert from 'openfl::media::Sound' to 'String'
./src/Cache.cpp(336): note: Constructor for class 'String' is declared as 'explicit'

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, Vcr effect and Random loadings screens and cache.hx

**Comment by TonyTimee** [comment]
delete the sound part
