### ISSUE TITLE
Testing Events Within Chart Editor

### ISSUE THREAD

**Issue by TonyTimee** [ShadowMario/FNF-PsychEngine#9750]
### What feature do you want to get added on the **base** engine?

When You Press ESC you can Test The Chart, Right?

Well What if You Can Test Events As Well

Examples can be if you place the screen shake event on curStep 32, frequency 0.05, for 0.6 seconds
it will play that in the test chart editor.

hope its understandable, horrible at explaining

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
That would create issues with a lot of events

**Comment by ShadowMario** [comment]
> That would create issues with a lot of events

^ This guy understands my pain
