### ISSUE TITLE
Note "Replacer"

### ISSUE THREAD

**Issue by twizinho** [ShadowMario/FNF-PsychEngine#9752]
### What feature do you want to get added on the **base** engine?

here's how it works:

you select a note that has a type, for example, a Hurt Note. 
and if you click a button on the Chart Editor, **all the notes in the entire chart** with that same type will be selected and can be _easily_ switched to another type.

i don't know if this can be made, but if it can, it would be really cool.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
Kool

**Comment by Mastercopper2346** [comment]
I’ll do pr

**Comment by Mastercopper2346** [comment]
nvm

**Comment by Lorekeeper49** [comment]
Easy workaround: 
1. Save the chart
2. Open the json and use Ctrl+H for find and replace
3. Type the notetype in find and the replacement notetype in replace and replace all
Replacing normal notes is a little bit complicated that I don't really know how to explain it but I'm sure you can figure out like I did.

**Comment by tylerandari12** [comment]
This is what I call USEFUL...
