### ISSUE TITLE
Every time i open this song (no source code)

### ISSUE THREAD

**Issue by TjUsesGithub** [ShadowMario/FNF-PsychEngine#9753]
### Describe your bug here.

I have no clue, every time i play this song it does this error

### Command Prompt/Terminal logs (if existing)

```bash
Song.hx (line 141)
Song.hx (line 132)
PlayState.hx (line 3864)
PlayState.hx (line 3736)
flixel/util/FlxTimer.hx (line 195)
flixel/util/FlxTimer.hx (line 285)
flixel/FlxGame.hx (line 745)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment]
provide files, something seems to be wrong with your week or chart

**Comment by TFLTV** [comment]
imagine using pico-speaker

**Comment by CrusherMods** [comment]
> imagine using pico-speaker

not a pico-speaker problem
