### ISSUE TITLE
help needed in custom mainmenu

### ISSUE THREAD

**Issue by bz001** [ShadowMario/FNF-PsychEngine#9755]
### Describe your problem here.

are there have anyway to custom mainmenu with lua instead of coding? thanks!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
No

**Comment by CrusherMods** [comment]
lua stuff only works in-game

**Comment by SrtHero278** [comment]
yea it only works in songs.

**Comment by Mastercopper2346** [comment]
Bruh 💀

**Comment by TheKitBoi** [comment]
https://gamebanana.com/mods/371888
Then go to here if want to move the images
