### ISSUE TITLE
Lag Start Screen

### ISSUE THREAD

**Issue by lucianofnfs** [ShadowMario/FNF-PsychEngine#9756]
### Describe your bug here.

Hello! I have a problem the start screen of the game looks LAG. but the FPS counter indicates 70-150. can you help me to solve that problem? THANK YOU!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
A video would be helpful
Is it just slow or is it actually lagging, if it's just slow then this is caused by forcing vsync and setting the fps cap higher than your refresh rate
