### ISSUE TITLE
Discord RPC with runHaxeCode()

### ISSUE THREAD

**Issue by dombomb64** [ShadowMario/FNF-PsychEngine#9759]
### Describe your problem here.

Is it possible to use `runHaxeCode()` to change the game shown on Discord? I tried copy-pasting the code from the `new()` function in `Discord.hx` into the `runHaxeCode()` function in my script, but it didn’t do anything.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by BeastlyGhost** [comment]
at this time, no, you would have to modify source for that

**Comment by tylerandari12** [comment]
There's already a Lua function for this...
```lua
changePresence(details:String, state:String, ?smallImageKey:String, ?hasStartTimestamp:Bool, ?endTimestamp:Float)
```

It's found on line 2052 [FunkinLua.hx](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/FunkinLua.hx#L2052) to back this up...

**Comment by dombomb64** [comment]
How do I use it? It's not doing anything. Also, is there a way to change the game being shown?
