### ISSUE TITLE
Game lags and cuts off sprites when opened after being overloaded

### ISSUE THREAD

**Issue by dombomb64** [ShadowMario/FNF-PsychEngine#9760]
### Describe your bug here.

If I reboot my game after it crashes, it’ll lag at specific parts and cut certain edges off various sprites. If I want this to stop, I have to reboot my computer. I think this only happens when the game is overloaded rather than any crash.

Edit: Also, the game’s just been overloading on the pause menu while I’m scripting.

Edit 2: It actually seems like it can overload if I have the game idle on any menu because it did the same thing on the freeplay menu.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Mastercopper2346** [comment]
Pc problem

**Comment by dombomb64** [comment]
How can you tell? This hasn’t been happening for me before the update, as far as I can tell.

**Comment by dombomb64** [comment]
It seems to have fixed itself.

**Comment by dombomb64** [comment]
It started doing it again, and it bluescreened my computer twice today. If anybody else comes across their title screen running at 26 FPS with cut-off graphics, SAVE EVERYTHING, because a blue screen is coming.

**Comment by frantastic24** [comment]
A whole new level of potato PC

**Comment by dombomb64** [comment]
Update: It stopped again, but it’ll probably come back.

**Comment by frantastic24** [comment]
It's either your PC or a haxe issue, either way it's not something psych can fix so you should close this

**Comment by dombomb64** [comment]
Okay, it might be a Haxe issue, because although I use a laptop, it's a good one and can run other things like modded Minecraft with little lag, if any at all. I'll close the issue for good now.

**Comment by dombomb64** [comment]
After Psych Engine 0.6.3 released, the issue seems to have vanished! Glad that's done with. ^_^
Also, it seems that the FPS dipping very briefly upon re-focusing on the window probably did have something to do with that, because it doesn't do that anymore.

**Comment by ColinCartoons** [comment]
then close the discussion svwfdshkwhfskbk\kjskbsfksfkbhsafklbasklbasfklhadskbjlasf

**Comment by ColinCartoons** [comment]
[ඞ](https://c.r74n.com/among-us/)
