### ISSUE TITLE
Issues on the Change Characther Event

### ISSUE THREAD

**Issue by 4729578395Beta** [ShadowMario/FNF-PsychEngine#9762]
### Describe your bug here.

So... I use the Change Characther Event and the values that i put is Value 1: Dad Value 2: 2nd Video: shadow-bambi-3d, 1st Video: pico
And then i start it to test it but the event changed instead, switched it to BF to Shadow Bambi 3D(2nd Video) and Pico (1st Video)

https://user-images.githubusercontent.com/109490196/179432038-3a7ac827-b9e0-423d-87bf-ac55a39fb4e3.mp4

https://user-images.githubusercontent.com/109490196/179432046-39c77920-c271-45c1-a88e-835a331f1166.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Only The Second Video is a edited build cuz i added things on the mods folder

**Comment by CrusherMods** [comment]
try putting dad in lowercase

**Comment by frantastic24** [comment]
Value 1 should be all lowercase
This has been fixed in source
