### ISSUE TITLE
Original files still appear even after deleting them

### ISSUE THREAD

**Issue by NotAhmedEpic** [ShadowMario/FNF-PsychEngine#9766]
### Describe your bug here.

I deleted all of the original FNF files, for example all the songs starting from Tutorial --- Stress and replaced them with my mod's songs, but they still appear in the exported game's files. Same with characters and weeks.
![bugreport](https://user-images.githubusercontent.com/97828056/179442012-fc9e6e4f-ba12-4904-8103-19a0dad99573.png)
![bugreport2](https://user-images.githubusercontent.com/97828056/179442130-cc1159c8-ed97-417c-90f2-0d3d87cc581e.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I replaced every vanilla FNF file with my mod's files.

**Comment by blowerslol** [comment]
This isn't a bug or anything, the source code adds the OG files to the assets. in order for this to work, you have to go in the export's assets folder, and replace the stuff.

**Comment by NotAhmedEpic** [comment]
> This isn't a bug or anything, the source code adds the OG files to the assets. in order for this to work, you have to go in the export's assets folder, and replace the stuff.

Oh, thanks. I just thought its a bug that it adds og files.
