### ISSUE TITLE
something about achievementGrid

### ISSUE THREAD

**Issue by WaFl-XIV** [ShadowMario/FNF-PsychEngine#977]
### What is your question?

I changed the achievements lists (removing the achievements for main weeks, adding achievements for my custom weeks, and adding an achievement for beating any week on a custom difficulty) and tried getting one of them. The game crashed, so I figured it's because I don't have the achievement texture for it. How do I add a texture for custom achievements?

**Comment by cfgexe** [comment]
add a 150x150px photo to the next available spot in achievementGrid.png
repeat until all assets are there

**Comment by ShadowMario** [comment]
the achievements image is a 150x150 grid ordered by achievement ID.
Just extend the image/canvas size and add your icons there.
