### ISSUE TITLE
PLEASE ADD FULLSCREEN BACK!

### ISSUE THREAD

**Issue by CookiesAndMika** [ShadowMario/FNF-PsychEngine#9770]
### What feature do you want to get added on the **base** engine?

full screen is gone, sadge 
![Depressed](https://user-images.githubusercontent.com/109516150/179486351-bdea66b0-25f6-4da5-bab7-16fcf1854b30.png)

### To test your sight, and reliability, please select the option of what should NOT be requested.

Actual feedback

**Comment by BeastlyGhost** [comment]
you failed the basic test.


press alt+enter

**Comment by TFLTV** [comment]
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Actual feedback

rookie mistake

**Comment by TheKitBoi** [comment]
> ### What feature do you want to get added on the **base** engine?
> full screen is gone, sadge ![Depressed](https://user-images.githubusercontent.com/109516150/179486351-bdea66b0-25f6-4da5-bab7-16fcf1854b30.png)
> 
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Actual feedback

**Comment by TheKitBoi** [comment]
![image](https://user-images.githubusercontent.com/84044666/179553426-2a0b5128-9f03-4a40-bef1-b5916a85ea0d.png)

**Comment by alberfingernoodle** [comment]
> ![image](https://user-images.githubusercontent.com/84044666/179553426-2a0b5128-9f03-4a40-bef1-b5916a85ea0d.png)

WHO ARE YOU YOU DEVIOUS FAKER

**Comment by CrusherMods** [comment]
> > ![image](https://user-images.githubusercontent.com/84044666/179553426-2a0b5128-9f03-4a40-bef1-b5916a85ea0d.png)
> 
> WHO ARE YOU YOU DEVIOUS FAKER

your the faker

**Comment by tylerandari12** [comment]
That's some nice art but you should close this and use `alt + enter`...
