### ISSUE TITLE
Crash Report - On level load

### ISSUE THREAD

**Issue by xChillax** [ShadowMario/FNF-PsychEngine#9771]
### Describe your bug here.

As the title says I am having a crashing issue when attempting to load a level on a specific difficulty.

I'm not really sure why it crashes since the "hard" version of the song works completely fine, the only difference is that "expert" has more notes, which to me doesn't really make much sense.

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
FreeplayState.hx (line 377)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error [file_contents,assets/data/songname/songname-expert.json]

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No changes were made to the base game.

**Comment by TFLTV** [comment]
does the difficulty exist?

**Comment by frantastic24** [comment]
> I think the crash log could be updated to explain these crashes.

It's quite literally telling you a file is missing, it does enough to explain the error but the issue is that 90% of people here automatically assume it's the game's fault instead of their files being fucked

**Comment by xChillax** [comment]
It doesn't really do that, it just tells you where the issue might be, which would lead to the user having to basically open each one of these files, go to the specific lines of code and then try and figure out what exactly broke in the process, and that is not exactly very "literal" as you are saying. You would only be able to tell knowing exactly how it happened.

I don't see why not add a generic description, it's done by many crash report apps and it helps develop things faster, most tools I use have this feature, which is why I might consider opening a PR adding this feature. The same could be done for other crash reports if I find more, it's just a nice QoL basically.

**Comment by xChillax** [comment]
> It gives you the exact file and exact line???

Not sure what you mean by this, you are just agreeing to what I said. Crash logs tell you where you should be looking to *figure out* the issue. It never even tells you what the exact issue is. Crash logs help you pinpoint where to look, if you think they are some kind of magical thing that figures it out on its own, then no, that's not how it works.
A database with the issues is needed to have an exact answer, crash logs usually just show you where the game stopped working and you work from there.

> How hard is it to open 2 files and read 2 lines

While the action is that simple as you mentioned, this statement is also false since you would need to actually read more than two lines to figure it out, as those single two lines don't do much by themselves as they are related to functions that would give you a better idea of what the issue really is.
It is also worth mentioning that this only applies to people who know how to read code in the first place, but for the general user, it doesn't always apply.
Not everyone checks the source files to figure stuff out when making simple modifications that to start with, don't require the source code.

Also if you noticed, this crash log actually leads you to at least seven different files, some are from the source files of the game, and some require you to have Haxe installed to see what the issue might be (or read it from someplace that hosts it). Which to me doesn't sound that believable from someone that works on the game without compiling-and you are probably already aware that this is the case for a lot of people.

> Considering the huge majority of "bug reports" here aren't caused by the engine, no it's not

From what I see a lot of reports here are merely people asking for features or not even reading the documentation and then asking why something isn't working, but actual crash reports seem to be pretty rare. I've been using Psych Engine for a while, from around the time it was first made, and this is the first time it ever crashed for me.

> You are missing the logic of crash reports being meant for crashes actually caused by the engine and not because the user can't read

Using your words, it is an engine issue since it failed to prevent something that can be prevented very easily, all due to it not being able to handle this correctly. If this version of the game is meant to be mod-friendly a check could easily be put in place to avoid this and save time for everyone. And before you say something, the game actually has checks for preventing other crashes, so that's no excuse.

It also would have saved time for yourself, that for some reason decided to look at a closed and solved issue, and reply? That simply won't have happened.

Anyways, this motivated me to make a better system for the game, so in the end, despite wasting our time, it ended up in a good thing, so thank you for inspiring me, in your own kind of way. lol

**Comment by frantastic24** [comment]
Nice job nitpicking and looking for every possible technicality 
![03551a92565d099e7db55b609fd2e60b.jpg](https://user-images.githubusercontent.com/95725102/179630737-6570e663-6707-4f7d-bddf-7fef955b2b06.jpg)

**Comment by xChillax** [comment]
Suele pasar when you talk about complex stuff. lol
