### ISSUE TITLE
What are the normal notes health loss and gain?

### ISSUE THREAD

**Issue by CatMaster8232** [ShadowMario/FNF-PsychEngine#978]
### What is your question?

I need to know what the health gain or loss is as I'm not good at digging through source code. If someone could tell me what they or even better make a template ordinary note (as the template on github is an instakill note) that'd be great. Thank you!

**Comment by SrtHero278** [comment]
Note.hx, lines 62 and 63:

	```
public var hitHealth:Float = 0.023;
	public var missHealth:Float = 0.0475;
```

**Comment by CatMaster8232** [comment]
Thank you!
