### ISSUE TITLE
Error: hxCodec

### ISSUE THREAD

**Issue by nebniywolf** [ShadowMario/FNF-PsychEngine#9786]
### PLS FAST!!!!

Error: Could not find haxelib "hxCodec", does it need to be installed?

Please help me!
![Screenshot 2022-07-18 213849](https://user-images.githubusercontent.com/104686407/179579971-3ce46b2e-db00-44c3-801e-410dcdfe1ed9.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by TheKitBoi** [comment]
Do
haxelib install hxCodec

**Comment by nebniywolf** [comment]
Thanks!

**Comment by hayfii** [comment]
> Thanks!

Bro never read the full building instructions 💀
