### ISSUE TITLE
how to add song without weeks?

### ISSUE THREAD

**Issue by raindow05** [ShadowMario/FNF-PsychEngine#9789]
### What is your question?

i have made secret song and after in Freeplay show song, i coded in source code here how to make it

**Comment by JustJack8** [comment]
addSong('songname', weeknumber, 'icon', freeplaycolor);

**Comment by nikkalotz** [comment]
how do you use freeplaycolor? in the code it's defined as an integer, not FlxColor
how do i use it

**Comment by MemeHoovy** [comment]
it works like RGB Red Green Blue

**Comment by nikkalotz** [comment]
how do you format it? would you type something like 255,255,255 or 255255255 or something with spaces

**Comment by MemeHoovy** [comment]
like this 255,255,255
