### ISSUE TITLE
Uncaught Error: Null Object Reference

### ISSUE THREAD

**Issue by Trevpro432** [ShadowMario/FNF-PsychEngine#9790]
### Describe your bug here.

Here is the crash report

PlayState.hx (line 2868)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

Lua or source idk i think a am using Source

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Knucks07** [comment]
im having this same issue and its usually when im using sprites after creating their .json files with the editor. they work in the editor and then when i save it (whether im working with source or lua) and select it in the chart editor it gives me this error message (and no i dont forget to compile, i do it every time)

**Comment by frantastic24** [comment]
#9539

**Comment by Knucks07** [comment]
oh thx

**Comment by Knucks07** [comment]
i dont think im having that problem tho, its not during the song its before it even starts right when i hit enter on the chart editor with a different opponent sprite chosen, specifically a custom sprite.

**Comment by TheKitBoi** [comment]
you should close this issue

**Comment by Knucks07** [comment]
then how do i fix the issue?

**Comment by Knucks07** [comment]
its different

**Comment by Knucks07** [comment]
whatever ill try to figure it out, thx

**Comment by TheKitBoi** [comment]
![image](https://user-images.githubusercontent.com/84044666/179635727-95b92679-1232-4322-9bdc-2fd9a3154673.png)

**Comment by Knucks07** [comment]
its not mine btw

**Comment by Knucks07** [comment]
i cant

**Comment by Knucks07** [comment]
and also aaaack light mode

**Comment by TheKitBoi** [comment]
then press close issue at the bottom right corner

**Comment by Knucks07** [comment]
i dont have that sry

**Comment by TheKitBoi** [comment]
what do you mean

**Comment by Knucks07** [comment]
![image_2022-07-18_195258249](https://user-images.githubusercontent.com/109554747/179635900-37e9a7b0-78c0-4d01-b655-8a8bf39b0d78.png)

**Comment by Knucks07** [comment]
![image_2022-07-18_195413082](https://user-images.githubusercontent.com/109554747/179636021-936d9a24-9efb-47f5-80cf-551265096cb5.png)

**Comment by Knucks07** [comment]
talk to them ig

**Comment by TheKitBoi** [comment]
ok

**Comment by TheKitBoi** [comment]
and he aint gonna lisen because he rarely checks his issues to see if it got fixed or not
