### ISSUE TITLE
how to use global functions or something

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#9794]
### Describe your problem here.

I've never done this but how to use variables from another script (this one is in the 'scripts' folder)
```lua
OldAspectRatio = false

function onCreate()
    if OldAspectRatio == true then
        makeLuaSprite('crtscreen','OldAspectRatio/crtscreen',0,0)
        setLuaSpriteScrollFactor('crtscreen',160,90)
        addLuaSprite('crtscreen',true)
    
        makeLuaSprite('bars','OldAspectRatio/bars',0,0)
        setLuaSpriteScrollFactor('bars',160,90)
        addLuaSprite('bars',true)

        setProperty('bars.antialiasing',false)
        setProperty('crtscreen.antialiasing',false)

        setObjectCamera('bars','camOther')
        setObjectCamera('crtscreen','camOther')

        scaleObject('crtscreen',4,4)
        scaleObject('bars',4,4)
	end
end

function onUpdate( elapsed )
    local squish= 80

    if not middlescroll and OldAspectRatio == true then
		noteTweenX('0',0,defaultOpponentStrumX0+squish,0.01,'linear')
		noteTweenX('1',1,defaultOpponentStrumX1+squish,0.01,'linear')
		noteTweenX('2',2,defaultOpponentStrumX2+squish,0.01,'linear')
		noteTweenX('3',3,defaultOpponentStrumX3+squish,0.01,'linear')
		noteTweenX('4',4,defaultPlayerStrumX0-squish,0.01,'linear')
		noteTweenX('5',5,defaultPlayerStrumX1-squish,0.01,'linear')
		noteTweenX('6',6,defaultPlayerStrumX2-squish,0.01,'linear')
		noteTweenX('7',7,defaultPlayerStrumX3-squish,0.01,'linear')
    end
end
```
and this one is inside the  song data folder:
```lua
OldAspectRatio = true
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No (other than the accuracy 'ratingStuff'), just modded in the "example_mods" folder

**Comment by Lorekeeper49** [comment]
I think you do `script_name.variable`

**Comment by Mastercopper2346** [comment]
Put `local` in front

**Comment by TFLTV** [comment]
> I think you do `script_name.variable`

do I have to put in the path of the script

**Comment by TFLTV** [comment]
> Put `local` in front

what does 'local' mean and why is it not working?

**Comment by Lorekeeper49** [comment]
> > Put `local` in front
> 
> what does 'local' mean and why is it not working?

```lua
local variable;
```
This is the same as creating a new variable

**Comment by TFLTV** [comment]
> > > Put `local` in front
> > 
> > 
> > what does 'local' mean and why is it not working?
> 
> ```lua
> local variable;
> ```
> 
> This is the same as creating a new variable

I want to use a varible from another script not from the same one
