### ISSUE TITLE
new error thing i found 

### ISSUE THREAD

**Issue by higbigmig** [ShadowMario/FNF-PsychEngine#9795]
### Describe your bug here.

i tried to add camera zooms and it crashes, well crashed, _twice_. so like help 
see the issue in image form here https://twitter.com/BSonicdude/status/1549249550623248387/photo/1 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Mastercopper2346** [comment]
Make sure you place the event before typing n stuff
