### ISSUE TITLE
add week 6 cutscene

### ISSUE THREAD

**Issue by GMB-YT** [ShadowMario/FNF-PsychEngine#9796]
### Describe your problem here.

How to add a cutscene where senpai turns into Spirit to my custom song

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by GMB-YT** [comment]
or source

**Comment by FireIce421** [comment]
you kinda don't, you have to make the file a character
