### ISSUE TITLE
i found this  bug that had too do with songs in the 6.2 ver

### ISSUE THREAD

**Issue by jackgittalk** [ShadowMario/FNF-PsychEngine#9798]
### Describe your bug here.

C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
FreeplayState.hx (line 344)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/oceans/oceans.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Command Prompt/Terminal logs (if existing)

```bash
thats the crash i made it ogg and yet still didn't work i was going too do the chart but the songs mods are a problem
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nothing yet

**Comment by frantastic24** [comment]
Missing chart

**Comment by jackgittalk** [comment]
maybe but okay

**Comment by frantastic24** [comment]
It's what the error says so 👍 missing chart

**Comment by SrtHero278** [comment]
yea file has a problem finding `assets/data/oceans/oceans.json`.
