### ISSUE TITLE
Changing note priority of custom note types.

### ISSUE THREAD

**Issue by karma999-taken** [ShadowMario/FNF-PsychEngine#9799]
### Describe your problem here.

I'm using custom note types with lua, specifically hurt notes. I don't know how to change the note priority so you don't accidentally hit them while hitting a regular note too. Need help solving this so I can actually make some of my old charts playable 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No source edits.

**Comment by frantastic24** [comment]
```lua
setPropertyFromGroup('unspawnNotes', i, 'lowPriority', true)
```
