### ISSUE TITLE
Simplesmente não abre

### ISSUE THREAD

**Issue by Aranha-fera** [ShadowMario/FNF-PsychEngine#9800]
### Describe your bug here.

Eu baixei a 0.6 e não abriu, tentei executar como administrador e também nada, reiniciei o computador e até agora não abre.
Baixei a 0.6.1 e a 0.6.2 e os dois não funcionam. Incrivelmente a 0.5.2 funciona certinho.
Ajuda por favor ae :(
Uso um laptop da lenovo com windows 10, Intel Core i5-8250U, memória de 8 gigas e a placa integrada Intel UHD Graphics 620

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Não alterei nada, e não abre

**Comment by Mastercopper2346** [comment]
I literally use the same pc

**Comment by Mastercopper2346** [comment]
But i never updated… stay at 0.5.2, is better

**Comment by ShadowMario** [comment]
Apaga a pasta do seu save, deve ter corrompido.
`%appdata%\Roaming\ShadowMario\PsychEngine`

**Comment by Aranha-fera** [comment]
> Apaga a pasta do seu save, deve ter corrompido. `%appdata%\Roaming\ShadowMario\PsychEngine`

Nada de abrir mano, mas na pasta ShadowMario tem outros mods como "Confrontig your self, FunkinAtFreddys, HighEffortErect, HypnosLullaby, Marioexe e VsDarkon
socorro parceiro
![image](https://user-images.githubusercontent.com/109605033/180100249-0d23b778-3ce4-49f1-ae78-6d749530a940.png)

**Comment by Aranha-fera** [comment]
> Apaga a pasta do seu save, deve ter corrompido. `%appdata%\Roaming\ShadowMario\PsychEngine`

Apaguei tudo na pasta, reinstalei e até agora nada, está ficando difícil ajudar meu amigo no mod dele :(

**Comment by Aranha-fera** [comment]
> Apaga a pasta do seu save, deve ter corrompido. `%appdata%\Roaming\ShadowMario\PsychEngine`

Aguardo resposta e mesmo deletando o save do appdata ainda não abre o psych engine
