### ISSUE TITLE
Can't open Story Mode or Freeplay

### ISSUE THREAD

**Issue by ChasingFlavors** [ShadowMario/FNF-PsychEngine#9801]
### Describe your bug here.

Hello, whenever I click on Story Mode or Freeplay, it gives me the below error. I didn't have this error on 0.5.2, and only had it when updating to 0.6.2.
![image](https://user-images.githubusercontent.com/83851918/179790214-0bea14e9-0753-4038-8f1e-d4aee526d855.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I added a mod I was working on to the Mods Folder.

**Comment by frantastic24** [comment]
Week file is broken

**Comment by ChasingFlavors** [comment]
thanks
