### ISSUE TITLE
os charts estão mais rapido do que o normal

### ISSUE THREAD

**Issue by getfreak** [ShadowMario/FNF-PsychEngine#9802]
### Describe your bug here.

todos os charts etavão muito lentos mas depois que eu mudei alguma coisa no options ficou muito mais rapido em todos os charts, acho que o jogo esta colocando o dobro nas velosidades tipo velosidade 1 tem a velosidade do 2, e isso acontece em todos os psych engine de versão mais baixa até a mais alta tirando os psych engine modificados como o d side e o b3

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

apenas coloquei coisas no mods e adisonei novas dificuldade sem mecher com source code do jogo

**Comment by CrusherMods** [comment]
Pressione CTRL no Freeplay e altere o tipo de rolagem ou a velocidade de rolagem (usei um tradutor se não fizer sentido btw)
