### ISSUE TITLE
Change to Custom Difficulty

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#9805]
### Describe your bug here.

When chanigng to a custom difficulty via the pause menu, my game crashed-
though from custom to "Normal" was fine

But idk if it was just random, or the issue is something else

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2740)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not via source

**Comment by Mastercopper2346** [comment]
Sometimes it just crashes lol
