### ISSUE TITLE
it crashes alot

### ISSUE THREAD

**Issue by FFoxyyy** [ShadowMario/FNF-PsychEngine#9806]
### Describe your bug here.

i died because i wanted to exit a song but pause wasnt working, so i died but it said some code shit i dont know

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i added scripts to scripts folders, if that counts.

**Comment by TheKitBoi** [comment]
Send in the Lua Scripts and ill see if there's any problems

**Comment by FFoxyyy** [comment]
@TheKitBoi  sorry for late response but, it shows this error:
![Screenshot 2022-07-22 174000](https://user-images.githubusercontent.com/96933785/180583793-8782fae8-61f4-4e8a-8af6-a0a621ec353a.png)
