### ISSUE TITLE
Change Character for hscript chars

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [ShadowMario/FNF-PsychEngine#9808]
### What feature do you want to get added on the **base** engine?

As the title states can we get the ability to change a character we added via script
```haxe
bfGhost = new Boyfriend(bfX - 400, bfY, 'bf');
/* Stupid Example */
bfGhost = change Boyfriend('bf-car');
```
Please?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Lorekeeper49** [comment]
`triggerEvent('Change Character', v1, v2)`

**Comment by TheKitBoi** [comment]
> `triggerEvent('Change Character', v1, v2)`

that's lua

**Comment by ShadowMario** [comment]
That's already possible, just add your character to game.boyfriendGroup, game.dadGroup or game.gfGroup 🤦

**Comment by ImaginationSuperHero528** [comment]
> That's already possible, just add your character to game.boyfriendGroup, game.dadGroup or game.gfGroup 🤦 

@ShadowMario tell me how to then idk! I'm not a source guy.

**Comment by rodney528** [comment]
me who's a source guy now
