### ISSUE TITLE
Weird Alpha Bug with Pause

### ISSUE THREAD

**Issue by MikeGames573** [ShadowMario/FNF-PsychEngine#9809]
### Describe your bug here.

I was messing with alpha in lua and there are some really weird bugs, like something that has alpha 0 goes to 1 when i pause or something with alpha 1 and don't dissapear until i pause.
Here is a video showing the problem. It really is a big problem for me, i hope this post help to fix this bug.

https://user-images.githubusercontent.com/102537206/179837821-ca704953-ce62-418b-a665-0413dad834fa.mp4

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Just Making a Lua Mod Pack

**Comment by Mastercopper2346** [comment]
Only source code can fix this

**Comment by frantastic24** [comment]
Bad script issue

**Comment by MikeGames573** [comment]
Value 1 is the alpha and value 2 is the duration
Here is the script:
function onEvent(name, value1, value2)
    if name == 'Stagnant Sketch Alpha' then
        if value1 == '' or value1 == '0' then
            setProperty('evilClubBGScribbly.alpha', value1)
        elseif (value2) then
            doTweenAlpha('Change Stagnant Stage', 'evilClubBGScribbly', value1, value2, 'linear')
            setProperty('cameraSpeed', 2)
        end
    end
end

**Comment by frantastic24** [comment]
You need to convert value1 and 2 into int/float first

**Comment by MikeGames573** [comment]
> You need to convert value1 and 2 into int/float first

How do i do that?

**Comment by frantastic24** [comment]
`tonumber()`
