### ISSUE TITLE
How to add a stage that is a folder like week 7?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#981]
### What is your question?

How to add a stage that is a folder like week 7?
it has several assets in a folder with seperate sprites.
What are the steps of adding it?

**Comment by SrtHero278** [comment]
For Lua mods, go to mods/images and make a folder then with the _image name_ parameter in the makeLuaSprite function, do 
**'[Folder Name]/[Image Name]'**

**Comment by ShadowMario** [comment]
The steps for creating a folder is pressing right click and clicking on "New Folder"
For adding sprites to this folder you just have to drag your images to the folder 👍
