### ISSUE TITLE
help

### ISSUE THREAD

**Issue by lilythepan320** [ShadowMario/FNF-PsychEngine#9812]
### What is your question?

![Capture](https://user-images.githubusercontent.com/99970305/179872142-4ba48c6f-bcad-4921-94c2-da9ec15a7366.JPG)

**Comment by SrtHero278** [comment]
Maybe try replacing `#if LUA_ALLOWED` with `#if LUA_ALLOWED && MODS_ALLOWED` in `TitleState.hx`.
and replacing lines 2263 to 2266 in `FunkinLua.hx` with
```
#if MODS_ALLOWED
if(!absolute)
    File.saveContent(Paths.mods(path), content);
else
    File.saveContent(path, content);
#else
File.saveContent(path, content);
#end
```
