### ISSUE TITLE
Source Code Notes

### ISSUE THREAD

**Issue by WoodsSilent05** [ShadowMario/FNF-PsychEngine#9813]
### Describe your problem here.

I want to make a note type (Drain note) but I want it in source (for some reason lol)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Added new texture and new xml for the note

**Comment by Mastercopper2346** [comment]
https://github.com/Mastercopper2346/FNF-PsychEngine/commits/poison-note

Only take code from July 19th.
