### ISSUE TITLE
Pressing [R] doesn't garantee to kill when using certain scripts

### ISSUE THREAD

**Issue by TBiscuit1** [ShadowMario/FNF-PsychEngine#9815]
### Describe your bug here.

When you press the [R] key, it will set the health to 0, but there is the problem of script that utilise health under or equal to 0

For exemple, my LUA script use that mechanic to allow the player to have more then the normal 100% hp, virtually making it 200% or even more by using the value from 2 to -2 instead of 2 to 0

But in this case, pressing [R] just set the health to 50% since 0 = 50% with my script, making the player invincible since he can just spam [R] and never go to 0%

There is 2 solution, the lazy way, and the proper way

Lazy Way: Set the health to some ridiculous negative number instead of 0
Proper Way: Force a Game Over instead of setting the health

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, it's fully vanilla (other then LUA Script)

**Comment by frantastic24** [comment]
How is this a bug
It's a problem with your script

**Comment by Mastercopper2346** [comment]
In source code, r DOES set your health to 0, just set it man

**Comment by TBiscuit1** [comment]
> How is this a bug 
> It's a problem with your script

While it is a problem with my script, the r key should def bypass any lua script to just kill the player instead of causing issue with scripts that include anti-death mechanic

> In source code, r DOES set your health to 0, just set it man

I can't, I am not modifying the source code
I guess I could just check for the R key, but then if it's disabled idk if it's possible for the script to know it is (maybe a getPropertyFromClass or something like that, I'll see)

**Comment by frantastic24** [comment]
>  r key should def bypass any lua script

That's just unrealistic and unnecessary
This is a problem with YOUR script, the game is not responsible for that

**Comment by steviegt6** [comment]
The R key in its current form is a hacky solution and should be redone. It's a "problem" with their script because of undefined behavior.

**Comment by ShadowMario** [comment]
Problem with your script.
