### ISSUE TITLE
Error when compile test

### ISSUE THREAD

**Issue by mikloe** [ShadowMario/FNF-PsychEngine#9818]
### Describe your problem here.

I compile to test the source code fnf psych engine 0.6.2 and i sea in console error:
PS C:\Users\boss\Desktop\psych> lime test windows
source/FunkinLua.hx:342: lines 342-346 : Int should be Bool
source/FunkinLua.hx:342: lines 342-346 : ... For function argument 'f'
what i must write in 342-346 lines?
pls help me
![Знімок екрана 2022-07-20 153629](https://user-images.githubusercontent.com/99079736/179983528-a56bcafa-a970-43b6-b56f-6ecd8c1c80aa.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes redacted Titlestate.hx and Mainmenustate.hx but it worked before I added them to build 0.6.2 and it works as expected (I looked at the code of build 0.6.2) in the console it does not write Mainmeustate.hx, and about Titlestate.hx it says that lines 585-589 are not used (code: if(!closedState) { sickBeats++; switch (sickBeats) { case 1: skipIntro(); case 3: #if PSYCH_WATERMARKS createCoolText(['Psych Engine by'], 15); #else createCoolText(['ninjamuffin99', 'phantomArcade', 'kawaisprite', 'evilsk8er']); #end // credTextShit.visible = true; case 3: #if PSYCH_WATERMARKS addMoreText('Shadow Mario', 15); addMoreText('RiverOaken', 15); addMoreText('shubs', 15); )

**Comment by TheRealJake12** [comment]
you gotta update lua.

**Comment by mikloe** [comment]
Ok
thanks
