### ISSUE TITLE
Voice Track Not playing

### ISSUE THREAD

**Issue by TamirPlaysYoutube** [ShadowMario/FNF-PsychEngine#982]
### Describe your bug here.

I loaded taco data file and Inst and voices in the debug menu and press space, and it’s not heard, I’m almost done with the mod

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

?

**Comment by TamirPlaysYoutube** [comment]
Ok everything is fixed now

**Comment by ShadowMario** [comment]
...Then close the issue???
