### ISSUE TITLE
events dont work like at all

### ISSUE THREAD

**Issue by ivorivorhepl** [ShadowMario/FNF-PsychEngine#9821]
### Describe your bug here.

whenever i add events and reload the song it just crashes the game. please help lmao

### Command Prompt/Terminal logs (if existing)

```bash
Song.hx (line 223)
Song.hx (line 167)
PlayState.hx (line 3343)
PlayState.hx (line 1279)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nah i did not

**Comment by ManMaster707** [comment]
If you're using 'Dadbattle Spotlight' or 'Philly Lights', then it's intentional, they can be used only on specific stages.

**Comment by ivorivorhepl** [comment]
i did not use those events. i used "change character" and it still crashes

**Comment by frantastic24** [comment]
What version are you using
Those lines in Song.hx don't exist 
If possible, post screenshots of the lines of code the log mentions

**Comment by ivorivorhepl** [comment]
can i post the code?

**Comment by ivorivorhepl** [comment]
also i used the latest ver
