### ISSUE TITLE
The file "Export" is missing for my psych engine main file 

### ISSUE THREAD

**Issue by arandombambi** [ShadowMario/FNF-PsychEngine#9822]
### What needs to be documented?

Im here with my psych engine source or main file and it has no "Export" Folder
![psych engine](https://user-images.githubusercontent.com/109686972/180038526-db206800-a9d0-4788-af64-f19a81451b88.PNG)

**Comment by arandombambi** [comment]
can someone help:<

**Comment by frantastic24** [comment]
You need to compile it first

**Comment by CrusherMods** [comment]
1. doesn't need to be documented
 2. its not included in the source code so you have to compile the game to get the folder

**Comment by arandombambi** [comment]
ok

> 1. doesn't need to be documented
> 2. its not included in the source code so you have to compile the game to get the folder
