### ISSUE TITLE
My custom stages doesn't work

### ISSUE THREAD

**Issue by MaxGamex485** [ShadowMario/FNF-PsychEngine#9823]
### Describe your bug here.

For some reason I just created a new stage and when I saved it the other stages that I have didn't work including the new one and then it crashes

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 2469)
PlayState.hx (line 2324)
PlayState.hx (line 1053)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MaxGamex485** [comment]
Thanks!!

**Comment by frantastic24** [comment]
Close the issue
