### ISSUE TITLE
Need some help.

### ISSUE THREAD

**Issue by TheSkyBeetle** [ShadowMario/FNF-PsychEngine#9824]
### Describe your problem here.

StrumNote.hx (line 139)
flixel/group/FlxGroup.hx (line 175)
flixel/group/FlxGroup.hx (line 175)
flixel/addons/ui/FlxUIState.hx (line 212)
MusicBeatState.hx (line 66)
PlayState.hx (line 2878)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No I didn't.

**Comment by DillyzThe1** [comment]
So, from what, I'm seeing here, you may or may not be trying to load a custom strum note skin.
I would like you to actually describe what's _really_ happening as there is a huge lack of information for other people to go off of.
For anyone viewing, [here's the line causing the issue](https://github.com/ShadowMario/FNF-PsychEngine/blob/main/source/StrumNote.hx#L139). This crash means that the current animation is null & there is surprisingly no check to see if it's actually there.

Check if your note skin:
- Is in the images folder and even exists
- Has a PNG and an XML
- Has the XML names lining up with the original sprite sheet of the strum line notes
- Was exported from Adobe Animate on atlas type Sparrow V2
