### ISSUE TITLE
The difficulty section is skewed to the left.

### ISSUE THREAD

**Issue by Setter-Function** [ShadowMario/FNF-PsychEngine#9826]
### What is your question?

To be exact, the location of the images used in the section.
This agenda includes 'hard' and 'easy' except 'normal'.
It bothers me a little. Is there a way to move them to the center? Well of course I can ignore this. But if there is a solution, I will try.
![2022-07-21 (5)](https://user-images.githubusercontent.com/108081370/180045579-16989172-c4e3-4bb9-bedf-790ab63394d5.png)
![2022-07-21 (3)](https://user-images.githubusercontent.com/108081370/180045587-080f23b3-54da-4799-a437-471ad8da1442.png)
![2022-07-21 (4)](https://user-images.githubusercontent.com/108081370/180045588-1a374e5b-6bd4-44d4-8e31-fbc0700494fb.png)
Thank you for reading.

**Comment by SrtHero278** [comment]
it is a small thing, but it's understandable why you don't want this.
Maybe try adding some blank space to easy and hard?
![image](https://user-images.githubusercontent.com/93018286/180087805-9d3f2308-ea71-41c7-9bf3-ee220d28249b.png)

**Comment by Lorekeeper49** [comment]
You've cursed me with be unable to unseen it

**Comment by Setter-Function** [comment]
thank you everyone

**Comment by Setter-Function** [comment]
Guys, it's been a long time since I posted this issue. I don't know if anyone will read this, but I brought a solution.
(v0.5.2h, StoryMenuState.hx, line 345)
```haxe
switch(curDifficulty)
{
	case 0:
		sprDifficulty.loadGraphic('easy');
		sprDifficulty.x = leftArrow.x + 130;
		sprDifficulty.offset.x = 20;
	case 1:
		sprDifficulty.loadGraphic('normal');
		sprDifficulty.x = leftArrow.x + 130;
		sprDifficulty.offset.x = 70;
	case 2:
		sprDifficulty.loadGraphic('hard');
		sprDifficulty.x = leftArrow.x + 130;
		sprDifficulty.offset.x = 20;
}
```
Add this. Then this issue will be fixed.
