### ISSUE TITLE
Psych Engine Song Limit

### ISSUE THREAD

**Issue by CMarkV** [ShadowMario/FNF-PsychEngine#9827]
### What is your question?

The Psych Engine Song limit is around ~25:30 I was wondering if there was any way to increase it like another minute or two.

I've heard its possible but it gives lag, but I don't mind the lag.

When you load a song that's longer than the limit (~25:30) it just goes to _negative section count_ or whichever limit that is, And gets broken unable to play.

I was Wondering if there is a way to increase the limit to like 27 minutes.

![Screenshot_for_negative_shiz](https://user-images.githubusercontent.com/109691199/180052854-6463c1c8-37fd-4656-95a7-ea4670518d97.png)

**Comment by DillyzThe1** [comment]
I'm pretty sure that's just the HaxeFlixel's limit on how much data can be loaded into the game. 
(Possibly depending on memory usage)
This isn't a "Psych Engine" limit or "an added limit to prevent 30 minute long printer recordings", it's just how the engine works.
The actual value of that time in milliseconds shouldn't overflow a float, though. (1,620,000ms/3.402823466 E + 38ms)
If you wanna do some research, you can check out the [FlxSound source code here](https://github.com/HaxeFlixel/flixel/blob/master/flixel/system/FlxSound.hx).

Besides, why exactly do you have a _27 minute long_ audio file in a rhythm game?

**Comment by impostor5875** [comment]
least insane bambi fan:

**Comment by REALHaydenGaming** [comment]
Yes lol, haxeflixel limit's, sorry :(

**Comment by CMarkV** [comment]
Well thanks anyway ill just cut it down then

**Comment by REALHaydenGaming** [comment]
If you need to know it: It is 25:21, hope it helps
