### ISSUE TITLE
Custom icons doesn't appear

### ISSUE THREAD

**Issue by MaxGamex485** [ShadowMario/FNF-PsychEngine#9829]
### Describe your bug here.

I'm not sure why it happens but I just tried to load in my custom characters and their icons doesn't load, I'm pretty sure there isn't any misspelling and the imege file starts with icon-

### Command Prompt/Terminal logs (if existing)

There's nothing

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by DillyzThe1** [comment]
I feel as if there is a huge lack of information regarding how you set it up or how the icons actually look, but here's a bunch of things to check:
- Is it in a mod folder?
- Inside the mod folder, is it in images/icons?
- Is the image 300x150?
- Does the character's JSON file have the icon as the same name? 
- If your icons are still failing, is it loading bf/dd icons or the test icons?
- Is the icon name _actaully_ "icon-yourIconNameHere"?

**Comment by MaxGamex485** [comment]
1.-Yes, specifically on mods\"MyModName"
2.-Yes
3.-Yes
4.-Yes
5.-Yes, all icons load instead of my custom icons
6.-Yes

**Comment by MaxGamex485** [comment]
Hey, nevermind, now they work for some reason

**Comment by DillyzThe1** [comment]
Alright, you should probably close this now.
I did forget to mention rebooting the game, so sorry about that.
