### ISSUE TITLE
Add a Quit option on main menu

### ISSUE THREAD

**Issue by Hayak0** [ShadowMario/FNF-PsychEngine#9833]
### What feature do you want to get added on the **base** engine?

I know it's not a big deal but it might be better than pressing alt f4..!
tittle explains too much..

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by Mastercopper2346** [comment]
Bruh

**Comment by Mastercopper2346** [comment]
No

**Comment by DillyzThe1** [comment]
i mean most games use this and it would probably be good if the original game _actually_ made it onto platforms like the switch
but as of now this is kindof just redundant for a newgrounds pc game

**Comment by ZeitHeld** [comment]
You can also still press the Close button from application windows (usually a red x), to close it
ALT F4 is not the only solution

**Comment by REALHaydenGaming** [comment]
Go on OS Engine, they already have that in, just copy and paste the code over to the new psych engine

**Comment by DillyzThe1** [comment]
> Go on OS Engine, they already have that in, just copy and paste the code over to the new psych engine

personally i would fully discourage randomly copying from another engine's source code without permission or even credits

if you need the function for closing the game, it's Sys.exit(0); and must be used on the sys package
as for the texture, open the fla if you have adobe aninate or just load a png from elsewhere

**Comment by ShadowMario** [comment]
Or you could... press the exit button
