### ISSUE TITLE
How do I use function onStepHit

### ISSUE THREAD

**Issue by DevAntiSocial** [ShadowMario/FNF-PsychEngine#9834]
### Describe your problem here.

I’m trying to add an asset mid song using onStepHit but can’t get it to work

code:
local curstep 

function onStepHit
       if curstep == 2927 then
             makeanimatedLuaSprite(‘image’, ‘file location’, 100, 100)
             addAnimationByPrefix(‘image’, ‘dance’, ‘ XML LINE’, 24, true
             playAnim(‘image’, ‘dance’, false(
             addLuaSprite(‘image’, true)
       end
end

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TheKitBoi** [comment]
Your Need to replace the function onStepHit to function onStepHit()

**Comment by TheKitBoi** [comment]
You can now close this issue

**Comment by frantastic24** [comment]
Case sensitivity
