### ISSUE TITLE
ultracrash??

### ISSUE THREAD

**Issue by nousername757** [ShadowMario/FNF-PsychEngine#9835]
### Describe your bug here.

so, I'm trying to slightly edit an existing mod to give each character their own note skin

for some reason when I do this, it causes the game to crash mid-song, and then the game crashes with the same error whenever I try to load any song or even the chart editor, the only way to fix is to reinstall

[PsychEngine_2022-07-21_07'36'04.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9154994/PsychEngine_2022-07-21_07.36.04.txt)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

probably not

**Comment by frantastic24** [comment]
missing note `end` animations

**Comment by nousername757** [comment]
oh, i accidentally used a kade format XML instead of a psych one for one of my noteskins, whoops

super weird how that makes *all* songs crash though, not just the one it's used in
