### ISSUE TITLE
Menu editor

### ISSUE THREAD

**Issue by jmastermills** [ShadowMario/FNF-PsychEngine#9840]
### What feature do you want to get added on the **base** engine?

It would be cool if there was a menu editor
like you could edit menus and add new menu

![Untieeetled](https://user-images.githubusercontent.com/83708251/180124768-165cbaa2-7b07-4481-a48f-b76c8c96589e.png)

this is just a ruff sketch of what It could be 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Useful feature

**Comment by CrusherMods** [comment]
failed the test

**Comment by Mastercopper2346** [comment]
Failed test + useless + probably a lua user :\
