### ISSUE TITLE
31 fps cap

### ISSUE THREAD

**Issue by 31fpsptsd** [ShadowMario/FNF-PsychEngine#9841]
### Describe your bug here.

im randomly put into a 31 fps cap somtimes after opening or even beating/losing a song normally i can run all psyce engine mods at 240fps

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by BlearChipmunk** [comment]
that is the problem, the engine breaks if you play over 150 fps, try to delete the config file of psych and play between 60-150fps
