### ISSUE TITLE
Game Crash Mid Gameplay

### ISSUE THREAD

**Issue by FujiwaraZachWatterson** [ShadowMario/FNF-PsychEngine#9842]
### Describe bug.

I have a problem about my project crash in mid song (like triple trouble)

but it didn't show an error message at all

this is the main problem

(not sure why)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I do not edit the build

**Comment by Justudude321** [comment]
Seems to happen on any song that aren't from tutorial-week 7, they'll probably fix it when they notice it as well
