### ISSUE TITLE
Some script problem

### ISSUE THREAD

**Issue by Fxnty** [ShadowMario/FNF-PsychEngine#9845]
### What is your question?

I've been having the problem of not being able to execute a script, I've been trying for a while now and nothing has worked out for me at all
Image:
![issue](https://user-images.githubusercontent.com/90153740/180207543-1b5fc44c-a190-4056-8564-641b1c2740f6.PNG)

**Comment by ManMaster707** [comment]
I can't explain all the problems here so I'll send the fixed script instead:

```lua
function noteMiss(id, direction, noteType, isSustainNote)
    if noteType == 'Healing' then
        setProperty('health', getProperty('health') - 0.0005);
    end
    
    if noteType == 'Healing' and getProperty('health') == 0.0005 then
        runTimer('No_health_for_u', 0.3, 1)-- you can't have 0.4 loops
    else
        setProperty('health', -500)
    end
end
