### ISSUE TITLE
Need help with a script

### ISSUE THREAD

**Issue by Superiron12321** [ShadowMario/FNF-PsychEngine#9849]
### Describe your problem here.

I want to make a script similar to the zanta bouncing script, but, I don't know how I would do this, is there a way to this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by ZeitHeld** [comment]
You can download the holiday mod, and then copy the script-

And then modify it

**Comment by Superiron12321** [comment]
> You can download the holiday mod, and then copy the script-
> 
> And then modify it

Which script would this be, i've checked the mod but I cant find the script

**Comment by Lorekeeper49** [comment]
> You can download the holiday mod, and then copy the script-
> 
> And then modify it

I'm pretty sure that the zanta bobbing is just part of the idle animation

**Comment by Superiron12321** [comment]
> > You can download the holiday mod, and then copy the script-
> > And then modify it
> 
> I'm pretty sure that the zanta bobbing is just part of the idle animation

No, its not

**Comment by ZeitHeld** [comment]
> > You can download the holiday mod, and then copy the script-
> > And then modify it
> 
> Which script would this be, i've checked the mod but I cant find the script

I think it is in the `zantaStage.lua`

**Comment by Superiron12321** [comment]
> > > You can download the holiday mod, and then copy the script-
> > > And then modify it
> > 
> > 
> > Which script would this be, i've checked the mod but I cant find the script
> 
> I think it is in the `zantaStage.lua`

I think it might be in there, but when putting other character into the stage nothing happens

**Comment by ZeitHeld** [comment]
I had the same issue, and tried to figure it out-
Though, I couldn't solve it yet-

Maybe try to analyze the script, so you can figure out, what it does

**Comment by BernardoGP4504** [comment]
i think i found it
```lua
doTweenY('character', 'character.offset', 0, 0.08, 'linear')

```
`character` = the character
so change each `'character'` instance in this line to be your character
