### ISSUE TITLE
fps cap

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#9851]
### What is your question?

how do I modify the fps cap so I can be GAMING

**Comment by ManMaster707** [comment]
search around the options menu

**Comment by TFLTV** [comment]
> search around the options menu

how to get more than 240 fps

**Comment by CrusherMods** [comment]
> > search around the options menu
> 
> how to get more than 240 fps

either
a. modify psych
b. dont and cope

**Comment by TheKitBoi** [comment]
> how to get more than 240 fps

Look just go to source/options/GraphicsSettingsSubState.hx
Find line 72
![image](https://user-images.githubusercontent.com/84044666/180325152-0e3ba7df-8f4f-4702-82ca-fb65bc8d775e.png)
and change the option.maxValue from 240 to whatever fucking number you want

also good luck finding better issues from more fps

**Comment by TFLTV** [comment]
> > how to get more than 240 fps
> 
> Look just go to source/options/GraphicsSettingsSubState.hx Find line 72 ![image](https://user-images.githubusercontent.com/84044666/180325152-0e3ba7df-8f4f-4702-82ca-fb65bc8d775e.png) and change the option.maxValue from 240 to whatever fucking number you want
> 
> also good luck finding better issues from more fps

I can now but min value to 1
