### ISSUE TITLE
why does this happen when i make a new .hx file?

### ISSUE THREAD

**Issue by im557** [ShadowMario/FNF-PsychEngine#9852]
### Describe your problem here.

![sdsaaaaaaaaaaa](https://user-images.githubusercontent.com/96075081/180307995-0909aa97-b0ef-4d4f-938d-0e79575dc8fa.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

many

**Comment by BeastlyGhost** [comment]
you need to import that file to your state with `import <fileName>` (no ext, should be `import NoteskinStuff`)
