### ISSUE TITLE
Song randomizer?

### ISSUE THREAD

**Issue by Emeninja972** [ShadowMario/FNF-PsychEngine#9854]
### What feature do you want to get added on the **base** engine?

A script to randomize the songs in a week for like mod random picks. 

Kinda stupid idea but yeah.

### Idea
Yes

### PS:
if your gonna come here to say some annoying stuff then go.

### To test your sight, and reliability, please select the option of what should NOT be requested.
Stage Editor, 6K+ support, and winning icons.

**Comment by CrusherMods** [comment]
Failed test

**Comment by TheKitBoi** [comment]
> ### To test your sight, and reliability, please select the option of what should NOT be requested.
> Useful feature

lets see how many times he gonna fail the test
