### ISSUE TITLE
Menu image on fnf startup

### ISSUE THREAD

**Issue by mariokid718** [ShadowMario/FNF-PsychEngine#9855]
### Describe your problem here.

In Vs. Impostor V2, do you remember that one screen that popped up when you start the mod that said something like "Thanks for playing this mod!" or something like that. Is it possible to do that in lua? (REFRENCE HERE) https://www.youtube.com/watch?v=rszFA5M4pe4&t=14s

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by mariokid718** [comment]
If anyone has pre made code can u send?

**Comment by frantastic24** [comment]
No

**Comment by mariokid718** [comment]
Okay then

**Comment by TheKitBoi** [comment]
also lua cannot be used outside of songs

**Comment by mariokid718** [comment]
Okay!
