### ISSUE TITLE
Thing that happened when trying to test a character and background

### ISSUE THREAD

**Issue by Foxyloloolool** [ShadowMario/FNF-PsychEngine#9857]
### Describe your bug here.

So when I was trying to test a character and background that said this: PlayState.hx (line 2469)
PlayState.hx (line 2324)
PlayState.hx (line 1053)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

If there is a fix for this please tell me

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I only added the character and background

**Comment by frantastic24** [comment]
Duplicate
Remove dadbattle spotlight from chart
