### ISSUE TITLE
What does the  parameters of sectionnotes mean?

### ISSUE THREAD

**Issue by zwl1619** [ShadowMario/FNF-PsychEngine#986]
### What is your question?

There is a events.json file and it has a "sectionNotes" like this:
![image](https://user-images.githubusercontent.com/13177997/141483201-2c65438d-0104-4b0d-8d73-6d2fb180d72e.png)

```
"sectionNotes": [
	[
		24000,
		-1,
		"Change Character",
		"1",
		"flipbf"
	]
	],
```
Questions:
1、What does the  parameters of sectionnotes mean? 
2、What  else parameters does it have?
3、Is there a tutorial for creating a `event.json` file?

**Comment by ShadowMario** [comment]
...You can literally save or load the events on the Chart Editor.
