### ISSUE TITLE
Error when not having the correct file

### ISSUE THREAD

**Issue by Luscious77** [ShadowMario/FNF-PsychEngine#9860]
### Describe your bug here.

![Capture](https://user-images.githubusercontent.com/52294187/180396487-de5414d9-eee6-46a3-85b6-edfeac185ec7.PNG)

to recreate the issue get a song in your mods folder mods/data/kaboom the error occurred when naming the chart json in a different way to there folder name so like kaboom/kaboom-x.json
 

### Command Prompt/Terminal logs (if existing)

```bash
C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/File.hx (line 30)
Song.hx (line 104)
FreeplayState.hx (line 377)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: [file_contents,assets/data/endless-paradox/endless-paradox-hard.json]
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

its a fresh download of the latest release v0.6.2

**Comment by BernardoGP4504** [comment]
huh that's strange as the game loads it from the `assets\` folder here but it is supposed to load from `mods\`

**Comment by Luscious77** [comment]
i did some more looking around and this happens also when the difficulties of the song are messed up too.
in essence its a missing file error, i think.
