### ISSUE TITLE
Awards documentation missing

### ISSUE THREAD

**Issue by MrGenie151** [ShadowMario/FNF-PsychEngine#9861]
### What needs to be documented?

I've been wondering how you make your own custom awards on the downloaded build since there is no documentation on the matter. Can this be fixed?

**Comment by frantastic24** [comment]
You can't

**Comment by BernardoGP4504** [comment]
you can't

**Comment by tylerandari12** [comment]
Technically you could but there's no direct implementation and therefore nothing can be documented...

**Comment by ShadowMario** [comment]
You can't yet
