### ISSUE TITLE
limit onUpdate() based on fps

### ISSUE THREAD

**Issue by AetherLynx** [ShadowMario/FNF-PsychEngine#9862]
### Describe your problem here.

i have an health drain script that drains your health if a condition is true, this is the code
```lua
function onUpdate(elapsed)
        if toggleDrain and not dodged then
                setProperty('health', getProperty('health') - 0.009)
        elseif toggleDrain and dodged then
                toggleDrain = false
                dodged = false
        end
end
```
simple, it works, but i have an issue.
i know onUpdate() means "every frame", but that means that if my FPS is higher the funcion will update faster
meaning that if health drain is active and my fps is 60, it will drain my health 60 times a second, if it's 240 fps, it will drain my health 240 times a second. i don't want that.

Is there a way so the code only works as if it were 60fps? because if the player has 240 fps they will die faster than a 60fps player.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
You could do something like
```lua
setProperty('health', getProperty('health') - (0.009 / (60 / framerate)))
```

**Comment by ShadowMario** [comment]
`setHealth(getHealth() - 0.5 * elapsed)`
