### ISSUE TITLE
Playstate.hx - FunkinLua Error

### ISSUE THREAD

**Issue by yoyoscreations** [ShadowMario/FNF-PsychEngine#9863]
### Describe your problem here.

this thing appears when I do the "lime test html5" command:
![image](https://user-images.githubusercontent.com/109829117/180573995-b1af46e2-0f3c-4c5e-b1d0-f74047718481.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no I just tried to compile it on html5

**Comment by TheKitBoi** [comment]
It will not be fixed until they release the update

**Comment by CrusherMods** [comment]
to fix on html5
cover some code with #if LUA_ALLOWED
