### ISSUE TITLE
TWO questions

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#9864]
### What is your question?

whats the debug folder inside export?
and if I complete a week and unlock another week if I publish that build will it still be unlocked (also same question with awards)

**Comment by TheKitBoi** [comment]
For Question 1 if you do lime build or test win -debug
Open the game and press f2 it will show the debug mode
You can view errors

**Comment by BeastlyGhost** [comment]
for question two, no it won't, as the save data for every computer is different

**Comment by TFLTV** [comment]
> for question two, no it won't, as the save data for every computer is different

thank this engine
