### ISSUE TITLE
 The latest commit crashes with songs longer than 6 mins

### ISSUE THREAD

**Issue by Punkinator7** [ShadowMario/FNF-PsychEngine#9866]
### Describe your bug here.

Every time I try to play longer songs (Triple Trouble, Four way Fracture, etc) they always crash around the 6 min mark and what's strange about it is that it only occurs on pre-release builds (like for example using the latest commit rather than the latest version) for some reason and the usual crash handler doesn't pop up or create a log i n the crash folder like I expect it to. it is the weirdest bug I've seen bro and I dunno why it does this.  it is a 64 bit build on windows 10.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I am using the latest Commit to this github. other than that nothing in source has changed.

**Comment by Justudude321** [comment]
Same thing happens to me but really on any song I try to complete with a few exceptions, might be some issue in playstate

**Comment by Punkinator7** [comment]
I'm gonna try the latest commit and see if it fixed it or not.

**Comment by Punkinator7** [comment]
I assume this is gonna be an issue for a good while

**Comment by frantastic24** [comment]
Yeah it's a Lua memory leak again
I have a PR that fixes it if you're interested in fixing it yourself in the meantime #9532

**Comment by Punkinator7** [comment]
Thanks, I've been testing different builds that are from this git specifically, and only the stable builds don't have this problem. could be a memory leak, and if so, is a little weird since psych doesn't really use more than 2 gigs of ram by itself (1280 mbs is the highest I've seen) until it stops crashing I'm going to omit the commit tag because it is gonna be quite a few more commits into the future before they merge the PR.

**Comment by Justudude321** [comment]
I found that this one works better [#10239](https://github.com/ShadowMario/FNF-PsychEngine/pull/10239)

**Comment by Punkinator7** [comment]
I'm gonna run a quick test and if it doesn't crash than I'll close it

**Comment by Punkinator7** [comment]
the pr seems to not have fixed the issue, cause after reinstalling it it seems to still crash at the same spot.

**Comment by Punkinator7** [comment]
or at least the one that beastly made so until #10239 is merged I think this issue will persist

**Comment by Punkinator7** [comment]
thank god this was fixed
