### ISSUE TITLE
Warning screen w/ lua only

### ISSUE THREAD

**Issue by ppsn19** [ShadowMario/FNF-PsychEngine#9868]
### Describe your problem here.

I would like to make a custom warning screen (something along the lines of "viewer discretion is advised"), preferably in Lua.
It should show every time my mod is ran. Any possible way?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Linux

**Comment by Mastercopper2346** [comment]
You cant really do it when the mod opens, you can do it before a song starts

**Comment by BlearChipmunk** [comment]
nope, that is on source and is on flashingstate.hx file, that is the warning of the flashing lights

**Comment by Mastercopper2346** [comment]
Why reopen

**Comment by TheKitBoi** [comment]
> I would like to make a custom warning screen (something along the lines of "viewer discretion is advised"), preferably in Lua. It should show every time my mod is ran. Any possible way?

Lua is not usable outside of songs

**Comment by ppsn19** [comment]
> Why reopen

Accidentally pressed the close button, my bad.
