### ISSUE TITLE
Portrait Editor Bug

### ISSUE THREAD

**Issue by Galbio** [ShadowMario/FNF-PsychEngine#9869]
### Describe your bug here.

I've just write in 'Image file name:' the name of the the necessary png and xml and then it crashed

![image](https://user-images.githubusercontent.com/101997612/180601878-68b68855-051e-4036-8141-e10e55985713.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by BernardoGP4504** [comment]
probably it is missing or you typed it wrong
