### ISSUE TITLE
Discord RPC doesn't close

### ISSUE THREAD

**Issue by NexIsDumb** [ShadowMario/FNF-PsychEngine#9870]
### Describe your bug here.

Pretty self explanatory from the title: 
basically I noticed that when you're playing a song and close the game (using the window X) the Rich Presence on Discord (about the song and stuff) is still visible.

This doesn't happens always, for example: the first time it happened I reopened the game, then did the same thing as before (play a song in-game, and then close the window again with the X) it closed. On the 3rd try tho, it happened again, the RCP was still visible (also the timer sometimes is still visible too; even tho it reaches 0). This happens mostly after compiling (Note: I didn't touch anything in the source about the rpc). I dunno if it's just me, that's why I'm asking.

![immagine_2022-07-23_155344143](https://user-images.githubusercontent.com/87421482/180608072-9a11fd70-e3fb-435c-a7e4-8dfb6172e400.png)

I tried to search functions (in the source) about closing the game for trying to make update the RPC when closing, but nothing.

Any help please?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No; Nothing about Discord RPC

**Comment by frantastic24** [comment]
Pretty sure that is a discord issue

**Comment by NexIsDumb** [comment]
> Pretty sure that is a discord issue

Welp I honestly dunno, that's why I asked lol

**Comment by frantastic24** [comment]
It happens with any other app so I highly doubt the game has anything to do with it

**Comment by iankevinluna11** [comment]
you could use the task manager sometimes the fnf stays open when i take it out if it doesn't work then it's not the game's fault

**Comment by NexIsDumb** [comment]
> 

Oh yeah right, I didn't think about that

**Comment by NexIsDumb** [comment]
Yeah Im actually dumb, and a lot lmfao
