### ISSUE TITLE
Shader question

### ISSUE THREAD

**Issue by MTFutureWasTaken** [ShadowMario/FNF-PsychEngine#9871]
### Describe your problem here.

How do I convert frag files for them to work on Psych?
(I'm just asking for things I need to replace in the shader file itself, nothing else.)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by MTFutureWasTaken** [comment]
Close #9871

**Comment by Raltyro** [comment]
you might wanna check psych engine discord server and go to help-scripts pins
![image](https://user-images.githubusercontent.com/78720179/180613329-b8f8e6c6-b418-43bb-963c-73f7a248d455.png)
