### ISSUE TITLE
Timebar

### ISSUE THREAD

**Issue by Akumalol** [ShadowMario/FNF-PsychEngine#9873]
### Describe your problem here.

how can i change the color of the time bar like sonic.exe?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by TheKitBoi** [comment]
Go to source/PlayState.hx
go to line 1033 timeBar.createFilledBar (0xFF000000, 0xFFFFFFFF);
And replace 0xFFFFFFFF to 0xFF000000

**Comment by TFLTV** [comment]
#8856
"borrow" the code from there

**Comment by Mastercopper2346** [comment]
He’s using source

**Comment by REALHaydenGaming** [comment]
It's actually pretty easy:
- Go to Playstate.hx.
- Go and find line 1033
# RECOMMEND!
- Have a color HUE extension on VS Code
- Change that color for your liking!
# HARDER WAY!
-  Have some experience with that color change.

Hope this help's!

**Comment by ivorivorhepl** [comment]
use this code 		timeBar.createFilledBar(FlxColor.BLACK, FlxColor.RED);

**Comment by ivorivorhepl** [comment]
well search up in PlayState.hx; timeBar.createFilledBar(0xFF000000, 0xFFFFFFFF); and replace it with timeBar.createFilledBar(FlxColor.BLACK, FlxColor.RED); simple

**Comment by ivorivorhepl** [comment]
not for me
