### ISSUE TITLE
bypass spam killer

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#9874]
### Describe your bug here.

you can spam and you won't die

https://user-images.githubusercontent.com/105890618/180618795-91876aff-459e-4b82-a497-eeea061428db.mp4

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No (other than the accuracy 'ratingStuff'), just modded in the "example_mods" folder

**Comment by ManMaster707** [comment]
I don't think it's a bug, you can do it but at the cost of your fingers, your accuracy and your reputation, a fair trade if you ask me.

(Plus it isn't that easy to spam trust me)

**Comment by TFLTV** [comment]
> I don't think it's a bug, you can do it but at the cost of your **fingers**, your accuracy and your reputation, a fair trade if you ask me.
> 
> (Plus it isn't that easy to spam trust me)

my finger are fine you just press them in a simple pattern

**Comment by ManMaster707** [comment]
> my finger are fine you just press them in a simple pattern

Well then play a dave and bambi song with it, i dare you

**Comment by TFLTV** [comment]
that audio 

> > my finger are fine you just press them in a simple pattern
> 
> Well then play a dave and bambi song with it, i dare you

but dave and bambi is kade engine

**Comment by TheKitBoi** [comment]
> but dave and bambi is kade engine
then get PE Ports

**Comment by REALHaydenGaming** [comment]
Oh hey, underaged user, and D&B again

@ShadowMario lock again, it is fucking dave and bambi related again

**Comment by ShadowMario** [comment]
It was removed
