### ISSUE TITLE
i can't get the "play with your mouse script"!

### ISSUE THREAD

**Issue by wubbzyfan** [ShadowMario/FNF-PsychEngine#9875]
### What needs to be documented?

the link (https://cdn.discordapp.com/attachments/840678333602857040/888568120728502272/script.lua) doesn't seem to work!

**Comment by TFLTV** [comment]
well, I have the script so here ya go:
[script.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9174451/script.txt)
(change .txt to .lua)

**Comment by wubbzyfan** [comment]
thanks

**Comment by Mastercopper2346** [comment]
Close it

**Comment by ImaginationSuperHero528** [comment]
@wubbzyfan close this
