### ISSUE TITLE
Simple problem about BGs/stages

### ISSUE THREAD

**Issue by WeirdManGuy** [ShadowMario/FNF-PsychEngine#9876]
### Describe your problem here.

idk if im dumb, but im having a problem with the LUA file of the custom stage i have. its the "<oef> expected near 'end'" error, yet im fairly certain the code is correct.
![stupidbug](https://user-images.githubusercontent.com/75181663/180621084-8aee6ae9-144d-4d3a-ac04-7455407d83f2.png)
if someone could help me fix this that would be pretty cool

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I haven't edited anything in the build besides the song itself, but that all is working fine.

**Comment by frantastic24** [comment]
Why is there an end in the middle of the function

**Comment by WeirdManGuy** [comment]
> Why is there an end in the middle of the function

not totally sure, i was watching a video and i didnt see them remove the middle end

**Comment by frantastic24** [comment]
It should not be there

**Comment by WeirdManGuy** [comment]
> It should not be there

ah, thanks

**Comment by frantastic24** [comment]
Close the issue
