### ISSUE TITLE
misssssssssssssssss

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#9878]
### Describe your problem here.

I made a miss animations and a normal animations (idle, singUP, etc) but the miss animations would play after the normal animations (except idle of course) is tjis a bug or am I doing it wrong

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No (other than the accuracy 'ratingStuff'), just modded in the "example_mods" folder

**Comment by BernardoGP4504** [comment]
add a 0 after the xml name for the animation

**Comment by TFLTV** [comment]
> add a 0 after the xml name for the animation

what do you mean? the xml name? the animation name in the xml? the image path? the animation name im entering in the the animation in the character editor in the animations tab? is the miss animations supposed to be in a defferent sprite sheet?

**Comment by Mastercopper2346** [comment]
In the engine

**Comment by Davesunavaiable** [comment]
so basically, if the main anim on the xml is called "left' and the miss is called "left_miss" then it plays them both, idk why. just make the names on the xmls different

**Comment by BernardoGP4504** [comment]
In the engine when you were to put the .xml anim field just put a 0 after
it like for example: left0

Em sáb, 23 de jul de 2022 19:55, Davesunavaiable ***@***.***>
escreveu:

**Comment by TFLTV** [comment]
naming it that just made it wors
![Web capture_23-7-2022_1841_github com](https://user-images.githubusercontent.com/105890618/180625582-b3025eb8-f1c3-4291-aa10-d10e71de8f12.jpeg)
e

**Comment by TFLTV** [comment]
oh yeah Im ADDING miss animations to a character (that I made)

**Comment by BernardoGP4504** [comment]
> naming it that just made it wors ![Web capture_23-7-2022_1841_github com](https://user-images.githubusercontent.com/105890618/180625582-b3025eb8-f1c3-4291-aa10-d10e71de8f12.jpeg) e

I meant on the singing anim XML name in the field in character editor

**Comment by TFLTV** [comment]
> > naming it that just made it wors ![Web capture_23-7-2022_1841_github com](https://user-images.githubusercontent.com/105890618/180625582-b3025eb8-f1c3-4291-aa10-d10e71de8f12.jpeg) e
> 
> I meant on the singing anim XML name in the field in character editor

so the name in the fla dosen't matter so in the engine update singLEFT to left0 and the miss anim left_miss

**Comment by BernardoGP4504** [comment]
Not that way

Em sáb, 23 de jul de 2022 20:15, TFLTV ***@***.***> escreveu:

**Comment by TFLTV** [comment]
what good information
![Web capture_23-7-2022_18261_github com](https://user-images.githubusercontent.com/105890618/180626120-b8c0a0d0-adfa-465d-bff8-cc44413c5562.jpeg)

**Comment by BernardoGP4504** [comment]
Sorry for taking too long but like, the animation name for singing
animations are singLEFT or the other animations.
I meant as the xml field inside the game (in character editor) not on the
fla file itself

Em sáb, 23 de jul de 2022 20:34, TFLTV ***@***.***> escreveu:

**Comment by BlearChipmunk** [comment]
is an easy solution, here it is 
![image](https://user-images.githubusercontent.com/89166594/180627655-bdd5ab0d-9220-461e-aa5a-33bc68be06e9.png)

**Comment by Mastercopper2346** [comment]
@BlearChipmunk youre misunderstanding.
He’s asking how to ADD miss animations he's not saying there’s a BUG

**Comment by Mastercopper2346** [comment]
@TFLTV in the animation name, if you want the left miss to `singLEFTmiss` in the animation name

**Comment by TFLTV** [comment]
what does this mean?
![Web capture_23-7-2022_211027_github com](https://user-images.githubusercontent.com/105890618/180629262-c0b09553-0459-4e0f-ace8-f4d994ee85dd.jpeg)

**Comment by Lorekeeper49** [comment]
> what does this mean?
> ![Web capture_23-7-2022_211027_github com](https://user-images.githubusercontent.com/105890618/180629262-c0b09553-0459-4e0f-ace8-f4d994ee85dd.jpeg)
> 
> 
> 

Look at the bf character data to easily figure that out
