### ISSUE TITLE
Change gf sprite depending health 

### ISSUE THREAD

**Issue by BlearChipmunk** [ShadowMario/FNF-PsychEngine#9882]
### Describe your problem here.

as in the title i want to change the "mood" of gf when your health is below... to say some value 50% her sprite is going to change to a "angry" mood and if the health is over 50% the sprite of gf changes to "happy" again

i tried something but is not working...

`
function onCreate()
	addCharacterToList('gfmad', 'girlfriend');
	addCharacterToList('gfhappy', 'girlfriend');
end

function onUpdate(elapsed)
if bofriendName == 'boe' then
	if getProperty('health') > 0.5 then
        triggerEvent('Change Character','GF','gfhappy')
	else
        triggerEvent('Change Character','GF','gfmad')
    end
    
end
end
`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

a lot of stuff

**Comment by Mastercopper2346** [comment]
Change 0.5 to 1

**Comment by Mastercopper2346** [comment]
1 is half health system weird lol

**Comment by Mastercopper2346** [comment]
Here

**Comment by Mastercopper2346** [comment]
```
function onCreate()
     addCharacterToList('gfmad', 'girlfriend');
     addCharacterToList('gfhappy', 'girlfriend');
end

function onUpdate(elapsed)
     if boyfriendName == 'boe' then
          if getProperty('health') > 0.5 then
               triggerEvent('Change Character','GF','gfhappy');
          else
               triggerEvent('Change Character','GF','gfmad')
          end
     end
end

**Comment by BlearChipmunk** [comment]
it works! but sadly the "boyfriendName" thing breaks the script, and it also breaks modcharts, thanks a lot for that tip bud!
