### ISSUE TITLE
trigger thing IDKKK

### ISSUE THREAD

**Issue by TFLTV** [ShadowMario/FNF-PsychEngine#9884]
### What is your question?

wheres the code that triggers debug mode (IN SOURCE)

**Comment by REALHaydenGaming** [comment]
oh my fucking god, press 7 or you're damn debug keys (2nd debug key)

your underaged (under 13 years old), fucking reporting that account for suspiciously being underaged

**Comment by TFLTV** [comment]
> oh my fucking god, press 7 or you're damn debug keys (2nd debug key)
> 
> your underaged (under 13 years old), fucking reporting that account for suspiciously being underaged

no i mean the code that triggers it so i can change the keybind

**Comment by Mastercopper2346** [comment]
@REALHaydenGaming you went too far with that, and YOU didn’t even read it correctly.

**Comment by REALHaydenGaming** [comment]
Shut the fuck up, he is underaged.
and I also know it's in client prefs.

**Comment by Mastercopper2346** [comment]
You still don’t get it 💀

**Comment by Mastercopper2346** [comment]
Wait nvm

**Comment by Lorekeeper49** [comment]
@REALHaydenGaming what even qualifies as underage evidence here?

**Comment by FlintIshe** [comment]
if (FlxG.keys.anyJustPressed(debugKeysChart) && !endingSong && !inCutscene)
		{
			openChartEditor();
		}

May be this is what you're looking for

**Comment by TFLTV** [comment]
> ```
> if (FlxG.keys.anyJustPressed(debugKeysChart) && !endingSong && !inCutscene)
> 	{
> 		openChartEditor();
> 	}
> ```
> 
> May be this is what you're looking for

what file is this in?

**Comment by tylerandari12** [comment]
> oh my fucking god, press 7 or you're damn debug keys (2nd debug key)
> 
> 
> 
> your underaged (under 13 years old), fucking reporting that account for suspiciously being underaged

What's wrong with being underaged? This isn't Discord...

**Comment by REALHaydenGaming** [comment]
> > oh my fucking god, press 7 or you're damn debug keys (2nd debug key)
> > your underaged (under 13 years old), fucking reporting that account for suspiciously being underaged
> 
> What's wrong with being underaged? This isn't Discord...

I know, I know I was going too far
because I had a bad day. But being underaged is against tos.

**Comment by tylerandari12** [comment]
> > > oh my fucking god, press 7 or you're damn debug keys (2nd debug key)
> > > your underaged (under 13 years old), fucking reporting that account for suspiciously being underaged
> > 
> > 
> > What's wrong with being underaged? This isn't Discord...
> 
> I know, I know I was going too far because I had a bad day. But being underaged is against tos.

I understand the bad day lol but TOS on github?

**Comment by REALHaydenGaming** [comment]
> > > > oh my fucking god, press 7 or you're damn debug keys (2nd debug key)
> > > > your underaged (under 13 years old), fucking reporting that account for suspiciously being underaged
> > > 
> > > 
> > > What's wrong with being underaged? This isn't Discord...
> > 
> > 
> > I know, I know I was going too far because I had a bad day. But being underaged is against tos.
> 
> I understand the bad day lol but TOS on github?

Yes

**Comment by TFLTV** [comment]
> ```
> if (FlxG.keys.anyJustPressed(debugKeysChart) && !endingSong && !inCutscene)
> 	{
> 		openChartEditor();
> 	}
> ```
> 
> May be this is what you're looking for

I am no longer struggling to find stuff in source because I finnaly know what "state" means at the end of the file names
