### ISSUE TITLE
3rd strumline

### ISSUE THREAD

**Issue by Hazardows** [ShadowMario/FNF-PsychEngine#9888]
### What is your question?

How can I add a 3rdstrumline in a song of my mod as it happens in the song "Bonedogle" of the "Indie Cross" mod ? (whith lua scripts)

**Comment by Gostar64** [comment]
Try using this https://gamebanana.com/mods/370379 (It may not work with 0.6.2)

**Comment by stevebresch730** [comment]
this dude forgot to close the issue lol (i know this is off topic but #9929)
