### ISSUE TITLE
please fix that issue

### ISSUE THREAD

**Issue by Bobgamingultimate** [ShadowMario/FNF-PsychEngine#9894]
### Describe your bug here.

when i was trying to make my own character an error appeared

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
editors/CharacterEditorState.hx (line 840)
editors/CharacterEditorState.hx (line 520)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i changed only mods folder

**Comment by REALHaydenGaming** [comment]
Maybe it has something to do with the  .json/sprite sheet/icons.

Not a good coder, but I think it has something to do with those 3 reasons
