### ISSUE TITLE
Am i doing something wrong?

### ISSUE THREAD

**Issue by Behoiler** [ShadowMario/FNF-PsychEngine#9897]
### What needs to be documented?

I have encountered a problem. Whenever i download the source engine i have some files missing, and when i try to test "Lime test windows" it has something to do with a missing file. for example the source folder is missing. Is it normal?

![84ab1485f3e04d5c0971701cde84dad6](https://user-images.githubusercontent.com/109869544/180760894-1baa576c-81d9-40f8-b6ae-67fad7ff7599.png)

**Comment by BeastlyGhost** [comment]
the source folder is missing

**Comment by kingyomoma** [comment]
the `example_mods` folder is also missing

**Comment by Behoiler** [comment]
ik is this a glitch?

**Comment by Behoiler** [comment]
because i didnt get them when i downloaded it

**Comment by smithrwiofh45675** [comment]
CHEEE a mi me pasa lo mismo se pudo solucionar ?

**Comment by smithrwiofh45675** [comment]
o como puedo resolver el problema ?

**Comment by Behoiler** [comment]
nvm all i had to do is reinstall winrar.

**Comment by Behoiler** [comment]
> o como puedo resolver el problema ?

tal vez pueda darte los archivos necesarios

**Comment by CrusherMods** [comment]
> nvm all i had to do is reinstall winrar.

if you fixed the issue
you should probably close it

**Comment by StefanBETA2008** [comment]
Yeah, Correct

**Comment by NS-Unfair** [comment]
@Behoiler please close the issue. You have solved the issue.

**Comment by DisLolTV** [comment]
No, he's having the same problem as I have. Windows 11 is deleting important files without our permission.
