### ISSUE TITLE
Something wrong with some events!

### ISSUE THREAD

**Issue by HeartinaRosebud** [ShadowMario/FNF-PsychEngine#9898]
### Describe your bug here.

![2022-07-25](https://user-images.githubusercontent.com/88090270/180767878-3c044d58-0c68-4fdb-8600-a5402412e853.png)
There's soemthing wrong with some events...

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by Mastercopper2346** [comment]
Place the event before putting values

**Comment by TFLTV** [comment]
I think it's because the selected note (the one that was selected) it tries to add that data and fails, I accidently selected an event and placed it as a note with values inside of it. just place it down then change the values. whatever event thats selected can be changed in the ui
