### ISSUE TITLE
IDK whats happening. 

### ISSUE THREAD

**Issue by MKUKPL** [ShadowMario/FNF-PsychEngine#9899]
### Describe your bug here.

Paths.hx (line 352)
editors/EditorPlayState.hx (line 847)
editors/EditorPlayState.hx (line 753)
editors/EditorPlayState.hx (line 603)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Missing rating textures
