### ISSUE TITLE
hey I'm trying to make a fnf mod if the psych eginge and it had a error everytime I treid open the songs please help

### ISSUE THREAD

**Issue by teamSnf** [ShadowMario/FNF-PsychEngine#9900]
### Describe your bug here.

it won't load and says error 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I made sure I did not edit any of the code

**Comment by frantastic24** [comment]
You are supposed to show the error

**Comment by TFLTV** [comment]
does it have a .json file? (Is the chart saved?)

**Comment by Flamebio15** [comment]
yes I remade the songs and the whole broke the only thing that did not break was the tutorial but the 3 songs I was working broken I still have the assets and icon's and dialogue saved but the frist week songs broken basic I was trying to make a mod

**Comment by frantastic24** [comment]
you still haven't provided any information, this issue is useless

**Comment by teamSnf** [comment]
> you still haven't provided any information, this issue is useless

#
![Screenshot 2022-07-25 164107](https://user-images.githubusercontent.com/105557915/180861351-f68373f2-cce1-4330-bdd6-81a375cc430b.png)
proof

**Comment by teamSnf** [comment]
> you still haven't provided any information, this issue is useless

![Screenshot 2022-07-25 164107](https://user-images.githubusercontent.com/105557915/180861724-7ff8308c-8528-4a21-a942-b2e3b368b9fb.png)
proof

**Comment by CrusherMods** [comment]
> > you still haven't provided any information, this issue is useless
> 
> ![Screenshot 2022-07-25 164107](https://user-images.githubusercontent.com/105557915/180861724-7ff8308c-8528-4a21-a942-b2e3b368b9fb.png) proof

your missing a chart

**Comment by VMan-2002** [comment]
amazing how easy it is for your problem to be identified when you provide the error message

**Comment by BlearChipmunk** [comment]
and to fix that you need to enter in the chart editor pressing 7 on the main menu

**Comment by TFLTV** [comment]
> and to fix that you need to enter in the chart editor pressing 7 on the main menu

press SEVEN on your keyboard while on the story mode button in the main menu and select chart editor put your song name in the textbox in the "song" tab and reload the audio or since I'm assuming you already have a normal chart since the image shows you're trying to play hard mode just play a song on normal then do the steps in the start of this comment and just reload the chart and edit that one then, once you're done just save it as the difficulty

**Comment by tylerandari12** [comment]
if youre entering by pressing 7 in a song then load the song on normal and youre problem will be fixed...

or make a copy of your chart called `knownentity-hard.json` and put it with the original chart...
