### ISSUE TITLE
How do i add character

### ISSUE THREAD

**Issue by okimcool-0** [ShadowMario/FNF-PsychEngine#9901]
### Describe your problem here.

When I tried loading a character, I got this error message: """"""""""""""""""""flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
editors/CharacterEditorState.hx (line 840)
editors/CharacterEditorState.hx (line 520)
flixel/ui/FlxButton.hx (line 521)
flixel/ui/FlxButton.hx (line 507)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng """"""""""""""" (this and the spam quotes weren't there i just couldn't use bold for some reason)
Can someone tell me what this error message means and help me add the character

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no I just tried loading a character in character editor

**Comment by Tigedraglon10** [comment]
I've had the same problem, except im not on the source, so I don't really know how to figure it out

**Comment by KingRGames** [comment]
I'm having the same problem!
