### ISSUE TITLE
Engine crashes or freezes when using aux, con, ptr and other Windows forbidden names into the Character Editor

### ISSUE THREAD

**Issue by YoshiCrafter29** [ShadowMario/FNF-PsychEngine#9902]
### Describe your bug here.

I've run through this issue while using Psych Engine.

The steps to reproduce it are very simple:
- Open the Character Editor
- Type anything that starts with the forbidden Windows names such as CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9.

For AUX, the engine will freeze upon entering the last character
![image](https://user-images.githubusercontent.com/81191621/180813948-9c8cbcf6-60c1-4083-aeaa-b90828c115e0.png)

For CON, the engine will simply crash with the following error.
![image](https://user-images.githubusercontent.com/81191621/180814104-81fbd7b0-9b99-4de9-8b6a-7f6d1d2eae20.png)

By checking the source code, the exception is thrown by the `loadGraphic` function, probably caused by loading an inexistant file.
I also noticed that `FileSystem.exists();` always returns `true` for every forbidden name, which may be the cause of the issue.

Loading CON via `File.getContent` or any other function will throw this exception `[file_contents,con]`, which may be the cause of why the engine crashes.

A fix for it would be to check if the path contains any of these forbidden names in an alternative FileSystem.exists function, but its up to you.

PS: This crash also happens on other editors when refreshing any file with these names.

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/FlxGraphic.hx (line 617)
flixel/FlxSprite.hx (line 405)
HealthIcon.hx (line 45)
editors/CharacterEditorState.hx (line 762)
flixel/addons/ui/FlxUI.hx (line 164)
flixel/addons/ui/FlxUIInputText.hx (line 46)
flixel/addons/ui/FlxInputText.hx (line 466)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

None

**Comment by Mastercopper2346** [comment]
Not really a bug, it’s built-in into your pc. So it’s a WINDOWS problem not a PSYCH ENGINE problem

**Comment by CrusherMods** [comment]
> Not really a bug, it’s built-in into your pc. So it’s a WINDOWS problem not a PSYCH ENGINE problem

it is a psych problem though
it happens when you enter a forbidden name inside the CHARACTER CREATOR inside PSYCH ENGINE

**Comment by AdrianCD5** [comment]
> when you enter a forbidden name inside the CHARACTER CREATOR inside PSYCH ENGINE
... and try to search for a forbidden filename, on Windows software. 
This seems pretty trivial. You already know the problem, there's no reason it to ever come up since you can't name files forbidden names in the first place.

**Comment by Psychenginehelper** [comment]
Im pretty sure that it tries to put it on and it gets confused and breaks, like 0.6.2 does.

**Comment by YoshiCrafter29** [comment]
> > when you enter a forbidden name inside the CHARACTER CREATOR inside PSYCH ENGINE
> 
> ... and try to search for a forbidden filename, on Windows software. This seems pretty trivial. You already know the problem, there's no reason it to ever come up since you can't name files forbidden names in the first place.

It prevents any characters that starts with any of these forbidden Windows names from being typed in the health icon field tho

**Comment by YoshiCrafter29** [comment]
woops

**Comment by AdrianCD5** [comment]
> > > when you enter a forbidden name inside the CHARACTER CREATOR inside PSYCH ENGINE
> > 
> > 
> > ... and try to search for a forbidden filename, on Windows software. This seems pretty trivial. You already know the problem, there's no reason it to ever come up since you can't name files forbidden names in the first place.
> 
> It prevents any characters that starts with any of these forbidden Windows names from being typed in the health icon field tho

i didn't think of that yeah, nvm. i forgot the health icon box updated every keystroke.

**Comment by TBiscuit1** [comment]
One way to bypass the problem for the moment is to type the icon name WITHOUT the 3rd letter then insert it in the end (or go in the file itself)
Not fancy, but it will atleast allow to avoid the crash
