### ISSUE TITLE
Engine dies when I use the "change character" event

### ISSUE THREAD

**Issue by ConentL** [ShadowMario/FNF-PsychEngine#9904]
### Describe your bug here.

The title is self explanatory, but I'll explain the behavior of this bug (or at least what I know about it) in case it helps.

-The bug doesn't occur in official/vanilla songs (Tested it in Bopeebo and Eggnog)
-Trying to use vanilla stages is also not fixing it.

Here's a picture to show that I did the things right with the event :
![image_2022-07-25_143321843](https://user-images.githubusercontent.com/109982932/180839112-d68dc04e-5b27-4469-bbda-a7b2230cf4f9.png)

I hope someone can help me, as the bug has been really annoying and makes it impossible for me to work properly.

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/frames/FlxAtlasFrames.hx (line 250)
Character.hx (line 164)
PlayState.hx (line 1407)
PlayState.hx (line 2452)
PlayState.hx (line 2317)
PlayState.hx (line 1051)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Absolutely nothing other than adding a song and a stage via lua.

**Comment by frantastic24** [comment]
Not a bug
You character is missing files

**Comment by ConentL** [comment]
> Not a bug You character is missing files

Checked on the images, apparently Adobe exported wrongly the sprite sheet (Idk how but it happened)

Thanks for the help dude!
