### ISSUE TITLE
Psych engine 0.6.2 song crash

### ISSUE THREAD

**Issue by RubenDatOneBoi3446** [ShadowMario/FNF-PsychEngine#9905]
### Describe your problem here.

Everytime I load up a song it shows the stage and the characters but nothing happens, no arrows, no time bar,
Nothing it just stays at that

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by bbpanzu** [comment]
you need a
`return Function_Continue`
on your onStartCountdown function

**Comment by Mastercopper2346** [comment]
Or you don’t have your songs in the right place

**Comment by Lanward** [comment]
You sure?

**Comment by RubenDatOneBoi3446** [comment]
Yah but what do I use the return Function_Continue on? And it's in songs/songname

**Comment by RubenDatOneBoi3446** [comment]
Oop wait

**Comment by RubenDatOneBoi3446** [comment]
I don't think I have any onStartCountdown function
