### ISSUE TITLE
This problem is driving me crazy.

### ISSUE THREAD

**Issue by Tigedraglon10** [ShadowMario/FNF-PsychEngine#9906]
### Describe your problem here.

PlayState.hx (line 2928)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
Uncaught Error: Null Object Reference

Crash Handler written by: sqirra-mg

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by kingyomoma** [comment]
which version are you using? line 2928 of `PlayState.hx` doesn't have anything related to an object

**Comment by Tigedraglon10** [comment]
> which version are you using? line 2928 of `PlayState.hx` doesn't have anything related to an object

Im on the newest version

**Comment by TheKitBoi** [comment]
if the script that causing this issue
then send it
