### ISSUE TITLE
How do I change what camera layer a sprite is on?

### ISSUE THREAD

**Issue by DevAntiSocial** [ShadowMario/FNF-PsychEngine#9909]
### Describe your problem here.

I’m trying to make it so I have a transition is a song but it doesn’t cover the notes

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
[it's on the wiki](https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Object-Functions#setobjectcameraobjstring-camerastring)

**Comment by Mastercopper2346** [comment]
`setObjectCamera(tag:String, camera:String)`

tag- your object’s tag
camera- can be game, hud, or other
