### ISSUE TITLE
Startup cutscene

### ISSUE THREAD

**Issue by MaxGamesYT** [ShadowMario/FNF-PsychEngine#9910]
### What is your question?

Anyone know how to make a cutsene that plays when you open the game with lua?

**Comment by MaxGamesYT** [comment]
> 

Dang

**Comment by TheKitBoi** [comment]
> Anyone know how to make a cutsene that plays when you open the game with lua?

Lua scripts cannot be used outside of songs

**Comment by frantastic24** [comment]
Close the issue
