### ISSUE TITLE
null object refrence

### ISSUE THREAD

**Issue by superarell** [ShadowMario/FNF-PsychEngine#9912]
### Describe your bug here.

so I have two characters for my mod that seem to not have worked over a bug in the system. and it's from not the character but the actual build its self

### Command Prompt/Terminal logs (if existing)

```bash
flixel/graphics/frames/FlxAtlasFrames.hx (line 246)
character.hx (line 164)
Editors/CharacterEditorState.hx (line 925)
Editors/CharacterEditorState.hx (line 434)
FlxUIDropDownMenuCustom.hx (line 500)
FlxUIDropDownMenuCustom.hx (line 361)
fixel/ui/FixButton.hx (line 521
fixel/addons/ui/FlxUITypedButton.hx (line 1172)
fixel/addons/ui/FlxUIButton.hx (line 362)
openfl/events/EventDispancer.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i have not edited the build

**Comment by frantastic24** [comment]
you exported your textures incorrectly

**Comment by superarell** [comment]
> you exported your textures incorrectly

i forgot the code for the sprites XD

**Comment by TFLTV** [comment]
you forgor to close the issue XD
