### ISSUE TITLE
Change note hue in a script?

### ISSUE THREAD

**Issue by Jaldabo** [ShadowMario/FNF-PsychEngine#9913]
### What is your question?

I want to be able to change note hue/color (this menu's values) using a script that goes in a respective song's data folder. What string can I use to accomplish this?
![image](https://user-images.githubusercontent.com/104400900/180915636-3078561c-34d2-4798-8bf6-5b2b17d93c61.png)

**Comment by tylerandari12** [comment]
```lua
local Hue = 0

function onCreatePost()
	for i = 0, 3 do
		setPropertyFromGroup("opponentStrums", i, "hue", Hue) --replace "hue" with "saturation" or "brightness" for those effects
		setPropertyFromGroup("playerStrums", i, "hue", Hue)
	end
end
```
