### ISSUE TITLE
My game does not compile

### ISSUE THREAD

**Issue by FlameOn60HzR** [ShadowMario/FNF-PsychEngine#9917]
### Describe your bug here.

My game does not compile I only put Lime test windows but nothing happens or puts me nungun type of error only does not compile

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Pues solo codifique el juego XD

**Comment by frantastic24** [comment]
Not enough information

**Comment by Mastercopper2346** [comment]
GIVE THE ERROR
