### ISSUE TITLE
Compiling 

### ISSUE THREAD

**Issue by XP013** [ShadowMario/FNF-PsychEngine#9918]
### Describe your problem here.

I tried to compile but I keep on getting this error 
"Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC"
I tried to search up and find solutions and couldn't find anything

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Missing visual studio components

**Comment by XP013** [comment]
> 

Do you know what visual studio components I need?

**Comment by frantastic24** [comment]
The error doesn't specify so you'll have to go through the list again

**Comment by XP013** [comment]
> The error doesn't specify so you'll have to go through the list again

by list you mean by the building process?
