### ISSUE TITLE
How do i make dialogue appear on freeplay and story mode?

### ISSUE THREAD

**Issue by Plotsh** [ShadowMario/FNF-PsychEngine#9919]
### What is your question?

i only know scripts that make dialogue appear in story mode only, but i want it to appear when entering a song from freeplay too

**Comment by frantastic24** [comment]
Just remove the story mode check

**Comment by Plotsh** [comment]
> Just remove the story mode check

im using the 0.5.1 cuz 0.5.2h+ dont work for me so i need a script unfortunately

**Comment by Plotsh** [comment]
nvm did it
