### ISSUE TITLE
How do I disable the countdown without having dialogue

### ISSUE THREAD

**Issue by DevAntiSocial** [ShadowMario/FNF-PsychEngine#9921]
### Describe your problem here.

Title says it all :)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Mastercopper2346** [comment]
`return Function_Stop`

**Comment by Mastercopper2346** [comment]
full code:

```
function onStartCountdown()
     return Function_Stop;
end

```
