### ISSUE TITLE
Variable for Accuracy

### ISSUE THREAD

**Issue by fnfdemonboi314159** [ShadowMario/FNF-PsychEngine#9922]
### Describe your problem here.

I am making a VS Nonsense Psych Port, and I am currently using Variables to make the mod run. But I can't find a variable for the Accuracy. Is there a variable for the accuracy?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I am making an External Mod Folder.

**Comment by Mastercopper2346** [comment]
`accuracy`

**Comment by stevebresch730** [comment]
`accuracy` sorry to be pushy but #9914

**Comment by stevebresch730** [comment]
also there is a vs nonsense psych port already

**Comment by fnfdemonboi314159** [comment]
> also there is a vs nonsense psych port already

oh, really?

**Comment by stevebresch730** [comment]
> > also there is a vs nonsense psych port already
> 
> oh, really?

i don have the mod link but you can search it up

**Comment by fnfdemonboi314159** [comment]
> > > also there is a vs nonsense psych port already
> > 
> > 
> > oh, really?
> 
> i don have the mod link but you can search it up

alright then.

**Comment by stevebresch730** [comment]
i guess i solved it.. yipee

**Comment by fnfdemonboi314159** [comment]
Don't get comfy. I still need one thing

**Comment by stevebresch730** [comment]
oh?

**Comment by fnfdemonboi314159** [comment]
And that is debugging the script I have.

**Comment by fnfdemonboi314159** [comment]
here is that lua script for Common Sense:

```
local allowCountdown = false
function onStartCountdown()
	if not allowCountdown and isStoryMode and not seenCutscene then
		startVideo('Cutscene1');
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onEndSong()
	if not allowEnd and isStoryMode then
		if accuracy > 75 then
			startVideo('Cutscene2');
		else
			startVideo('Cutscene2_bad');
		end
		allowEnd = true;
		return Function_Stop;
	end
	return Function_Continue;
end
```

**Comment by fnfdemonboi314159** [comment]
When I test it out, only the `onStartCountdown()` part executes, not the `onEndSong()` part. What did I do wrong?

**Comment by stevebresch730** [comment]
i mean, im not good with code so idk

**Comment by fnfdemonboi314159** [comment]
> i mean, im not good with code so idk

it can wait for everyone else, not just you.

**Comment by stevebresch730** [comment]
ok
