### ISSUE TITLE
This has to do with an answer

### ISSUE THREAD

**Issue by lemz1** [ShadowMario/FNF-PsychEngine#993]
### What needs to be documented?

Hi @ShadowMario,
In this issue #961 , You answered me to change `defaultOpponentStrumX..i` to `_G[defaultOpponentStrumX..i]`
but this still gave me the error (return value not supported)
I figured out that it has to be `_G['defaultOpponentStrumX'..i]` (notice the `'` around the `defaultOpponentStrumX`)
If this is just a problem with me, then yeah my bad and sorry.
Else, I wanted to tell you this, so that in the future a person doesn't have to figure that out.
But hey, in the end you still helped, so thanks.

I am sorry if I wrote that rudely or it offended you.
I really don't mean any harm.

**Comment by ShadowMario** [comment]
oh yeah i forgot to put the quotes in it
