### ISSUE TITLE
How TO Make 3RD Strums (Source code) 

### ISSUE THREAD

**Issue by zeadd21g1233** [ShadowMario/FNF-PsychEngine#9931]
### Describe your problem here.

i want to make 3rd strums in source code

in psych engine 0.5.2h version

like bonedoggle

and only one song have 3rd strums in chart editor Like Indie cross bonedoggle
not all Songs
(Source code)
(Source code)
(Source code)
(Source code)
(Source code)
(NO LUA)
(NO LUA)
(NO LUA)
(NO LUA)
(NO LUA)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope Nothing

**Comment by CrusherMods** [comment]
this is not the place to ask for code.

**Comment by zeadd21g1233** [comment]
if this why there to many comments ask for a code  to help  in own mods

and Where The Place to Ask About codes

**Comment by zeadd21g1233** [comment]
if this why there to many comments ask for a code  to help  in own mods

and Where The Place to Ask About codes

**Comment by TheKitBoi** [comment]
> and Where The Place to Ask About codes
![image](https://user-images.githubusercontent.com/84044666/181518170-997a960e-90ef-45aa-a70b-57e999b00384.png)
read this image

**Comment by tylerandari12** [comment]
Now that I think about it...

Where do you ask about this sorta stuff?

**Comment by CrusherMods** [comment]
> and Where The Place to Ask About codes

Try looking in a [psych discussion](https://github.com/Theoyeah/PsychEngineDiscussions/discussions)
