### ISSUE TITLE
Crashes when adding character to a song 

### ISSUE THREAD

**Issue by JulianGeckoWasp** [ShadowMario/FNF-PsychEngine#9932]
### Describe your bug here.

Hello! I made a character and when I try to load it in ANY song I get this error:
![image](https://user-images.githubusercontent.com/110136934/181383441-d256fa12-0a6a-4653-b4c3-a3d564d2a180.jpg)
Can anybody help? Thanks!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No I just added a character and icons

**Comment by frantastic24** [comment]
character icon is missing animations, are you using a script to change it?

**Comment by JulianGeckoWasp** [comment]
> character icon is missing animations, are you using a script to change it?

I’m not using a script to change it, and I forgot to mention the character doesn’t use an icon. It uses the gray face.

**Comment by frantastic24** [comment]
your character needs an icon

**Comment by JulianGeckoWasp** [comment]
> your character needs an icon

Late reply but thanks! I will now close this thread:
