### ISSUE TITLE
Multiple Key moving

### ISSUE THREAD

**Issue by SorbetLover** [ShadowMario/FNF-PsychEngine#9934]
### What is your question?

Im searching a multi arrow reciever  movement for this engine (i want to move it like in crucify in the part that the notes go down and up

**Comment by NotEpik** [comment]
local newY = 250

noteTweenY('PlayerStrumY0', 4, newY, 1, 'linearInOut')
noteTweenY('PlayerStrumY1', 5, newY, 1, 'linearInOut')
noteTweenY('PlayerStrumY2', 6, newY, 1, 'linearInOut')
noteTweenY('PlayerStrumY3', 7, newY, 1, 'linearInOut')

**Comment by SorbetLover** [comment]
OH thx il try

**Comment by SorbetLover** [comment]
it works thx :)

**Comment by SorbetLover** [comment]
do you know how to repair that error
![image](https://user-images.githubusercontent.com/89319609/181845820-22c878bd-de79-4b5f-90c0-3664ca7e5fd9.png)
 
 this is the script
![image](https://user-images.githubusercontent.com/89319609/181845889-50c06b1a-cc6f-414f-8e90-01150b94995c.png)

**Comment by SorbetLover** [comment]
> ```
> local newY = 250
> 
> noteTweenY('PlayerStrumY0', 4, newY, 1, 'linearInOut')
> noteTweenY('PlayerStrumY1', 5, newY, 1, 'linearInOut')
> noteTweenY('PlayerStrumY2', 6, newY, 1, 'linearInOut')
> noteTweenY('PlayerStrumY3', 7, newY, 1, 'linearInOut')
> ```
> 
> you have to do some scripting with this template to get it to move up and down 👍

it works whitout my edit

im gettin this error 
![image](https://user-images.githubusercontent.com/89319609/181846086-1c032d9f-4b89-4638-a6bc-3c078129e8eb.png)

im trying to repair it but idk much LUA
![image](https://user-images.githubusercontent.com/89319609/181846154-f2fe3ed3-1700-468b-a9f5-47ab589b923a.png)

**Comment by SorbetLover** [comment]
thx
