### ISSUE TITLE
Smooth camera movement (reissued AGAIN so please give a solution and sorry for making so much duplicates)

### ISSUE THREAD

**Issue by stevebresch730** [ShadowMario/FNF-PsychEngine#9938]
### Describe your problem here.

i am making a psych based engine but i also want it to have smooth camera movement but i dont know how to do it can someone **`PLEASE`** help me???

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

yes. i edited mainmenustate

**Comment by frantastic24** [comment]
No, stop opening duplicates

**Comment by stevebresch730** [comment]
> No, stop opening duplicates

sorry man i just really wanted to know :(

**Comment by Thedumbdude** [comment]
in the vs curse malediction song fanmade mod by cape there is a script with smooth camera movment in the malediction folder in the data folder

**Comment by stevebresch730** [comment]
> in the vs curse malediction song fanmade mod by cape there is a script with smooth camera movment in the malediction folder in the data folder

thank you SO much bro this really helped me!
