### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by Aden-Mystio** [ShadowMario/FNF-PsychEngine#9939]
### Describe your bug here.

N

### Command Prompt/Terminal logs (if existing)

```bash
What is error code "Invalid char 0 at position 0" this is showing up when I boot the game up
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by frantastic24** [comment]
Not a bug
One of your files is broken, but what you posted isn't very descriptive

**Comment by Aden-Mystio** [comment]
> Not a bug
> One of your files is broken, but what you posted isn't very descriptive 

What would a "Broken file" be?

**Comment by Aden-Mystio** [comment]
> Not a bug One of your files is broken, but what you posted isn't very descriptive

This is my copy for the engine https://drive.google.com/drive/folders/1q_hukSQyoV7QFqo11lcgs0w6OWHvEaom?usp=sharing

**Comment by frantastic24** [comment]
> What would a "Broken file" be?

Seems like an incorrectly formatted json or xml
