### ISSUE TITLE
More custom value slots!

### ISSUE THREAD

**Issue by ItsCapp** [ShadowMario/FNF-PsychEngine#994]
### What feature do you want to get added on the base engine?

Value 1 and Value 2 are currently the only values that you can see in-game, which means if you want to have more than 2 variables, you need to mess around with splitting into tables.

![image](https://user-images.githubusercontent.com/93293747/141524599-bbf81fd3-8634-4186-9e10-00856a447659.png)

Please! add more!

while I'm talking about the values, what about value titles?
![image](https://user-images.githubusercontent.com/93293747/141525226-7639ad37-0069-4ab5-a32b-1474cae9d21a.png)
Maybe being able to change the "Value 1" or "Value 2" above the input box to whatever you want?

**Comment by SrtHero278** [comment]
This WOULD be helpful. I love it. But it might be tougher for custom lua events.

**Comment by ItsCapp** [comment]
> But it might be tougher for custom lua events. (Talking about the value title part)

just a little suggestion ¯\_(ツ)_/¯ came into my head while I was writing it

**Comment by perngjiafu** [comment]
you dont.

you cant.... but you need to rewrite almost the whole code in the source file

**Comment by nintendofan44** [comment]
I got a better idea.
why not instead of having like, x value or y value,
have instead value 3 or value 4

**Comment by ItsCapp** [comment]
> I got a better idea. why not instead of having like, x value or y value, have instead value 3 or value 4
> 
> maybe?
That's the thing I'm trying to get across,

> which means if you want to have more than 2 variables, you need to mess around with splitting into tables.
The "x value" and "y value" thing is just a suggestion
