### ISSUE TITLE
Error when opening Mods menu

### ISSUE THREAD

**Issue by AyeRitter** [ShadowMario/FNF-PsychEngine#9940]
### Describe your bug here.

Whenever I try to open the mods menu with my mods, it immediently crashes.

### Command Prompt/Terminal logs (if existing)

```bash
Crash Handler:
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 318)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 99)
C:\HaxeToolkit\haxe\std/haxe/format/JsonParser.hx (line 57)
ModsMenuState.hx (line 733)
ModsMenuState.hx (line 329)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Invalid char 86 at position 75
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i added a few mods, some of them being older but i don't think that should be an issue

**Comment by frantastic24** [comment]
Not a bug
One of your modpack json is incorrectly formatted
