### ISSUE TITLE
Displayed Length of Sustain Notes

### ISSUE THREAD

**Issue by ZeitHeld** [ShadowMario/FNF-PsychEngine#9941]
### Describe your bug here.

Any Sustain Notes, that exceed the length of one Beat, will be displayed shorter by one Step.
(Look at attached images for better understanding)

In this Example, all Notes should be having the same length, and line up properly. But in-Game, they don't.

In Chart Editor:
![image](https://user-images.githubusercontent.com/76132257/181517863-8497ab75-4d1b-40df-aca0-dc58eee69992.png)

In Song:
![image](https://user-images.githubusercontent.com/76132257/181518199-ab07fd7d-d232-4123-ad0e-faa784e7bf7f.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not via source

**Comment by Lorekeeper49** [comment]
This happens on other engines too

**Comment by ZeitHeld** [comment]
> This happens on other engines too

It's an error none the less- And I hate it-
And I really hope, that it will be fixed with the next update of fnf, or AT LEAST, the final version
