### ISSUE TITLE
Shaders

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#9946]
### What is your question?

How do I use shaders?

**Comment by stevebresch730** [comment]
This might help https://www.youtube.com/watch?v=g938mK2zsX0

**Comment by bruh1cat** [comment]
> This might help https://www.youtube.com/watch?v=g938mK2zsX0

Doesn't work in either 0.5.1 or 0.6.2 (https://github.com/ShadowMario/FNF-PsychEngine/actions/runs/2755397702) and the build he mentioned is expired.
