### ISSUE TITLE
how 

### ISSUE THREAD

**Issue by Demonlove142** [ShadowMario/FNF-PsychEngine#9947]
### Describe your problem here.

![Screenshot 2022-07-28 181957](https://user-images.githubusercontent.com/85841514/181646956-d7bde1da-83d4-4c33-8286-df8be02e4be0.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by tylerandari12** [comment]
Remove the `close(true)` line as its closing your script before it has a chance to go more than once...

**Comment by Mastercopper2346** [comment]
Also remove the spaces

**Comment by tylerandari12** [comment]
Also spawning the `guy` sprite at 5000, 5000 will put him WAY off the screen in case you cant see him...

**Comment by tylerandari12** [comment]
One least thing its `onBeatHit()` not `onBeathit()` (capital H)

**Comment by NotEpik** [comment]
me looking at the script and sees that it creates the sprite every time the beat hits: 😐

here i fix most of the part where it create the sprite every time the beat hits and setting the loop of the animation to false and also force the object to play the animation every time it beat:

```
function onCreate()
	makeAnimatedLuaSprite('yoo','guy ', 500, 500)
	addAnimationByPrefix('yoo','bump','guy ',24,false)
	setScrollFactor('yoo'),0.9,0.9)
	addLuaSprite('yoo',true)
end

function onBeatHit()
	if curBeat % 2 == 0 then -- remove this if you want it to bop head like gf
		objectPlayAnimation('yoo','bump',true)
	
	end
end
```

**Comment by Mastercopper2346** [comment]
```
function onCreate()
	makeAnimatedLuaSprite('yoo', 'guy', 0, 300) -- FIX THE POSITION OR IT WILL BE OUT OF RANGE
	addAnimationByPrefix('yoo', 'bump', 'guy' ,24 ,false)
	setScrollFactor('yoo',0.9,0.9)
	addLuaSprite('yoo', false) -- change for behind characters
end

function onBeatHit()
	if curBeat % 2 == 0 then -- remove this if you want it to bop head like gf
		objectPlayAnimation('yoo','bump',true)
	end
end
```
Fixed version.
(We don’t know the cords cuz we don’t got the image. This is my guess.

**Comment by tylerandari12** [comment]
```lua
function onCreate()
	makeAnimatedLuaSprite('yoo', 'guy', 0, 300) -- FIX THE POSITION OR IT WILL BE OUT OF RANGE
	addAnimationByPrefix('yoo', 'bump', 'guy' ,24 ,false)
	setScrollFactor('yoo',0.9,0.9)
	addLuaSprite('yoo', false) -- change for behind characters
end

function onBeatHit()
	if curBeat % 2 == 0 then -- remove this if you want it to bop head like gf
		objectPlayAnimation('yoo','bump',true)
	end
end
```

**Comment by Mastercopper2346** [comment]
Bruh that’s literally mine :/

**Comment by tylerandari12** [comment]
> Bruh that’s literally mine :/

But in color :D
