### ISSUE TITLE
Song freezes when I load it!

### ISSUE THREAD

**Issue by JulianGeckoWasp** [ShadowMario/FNF-PsychEngine#9948]
### Describe your bug here.

Hello, I made a song and when I try to load it in the thing just freezes.

https://user-images.githubusercontent.com/110136934/181648766-a23cc789-a779-4796-8d35-12290dd2d913.MOV

Does anybody have a fix?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not at all, just added a character, dialogue, and this song

**Comment by frantastic24** [comment]
Not a bug
You exported your instrumental incorrectly

**Comment by JulianGeckoWasp** [comment]
> Not a bug
> You exported your instrumental incorrectly

What is the correct way to do so?

**Comment by frantastic24** [comment]
OGG Vorbis iirc, just about any online converter works for this

**Comment by JulianGeckoWasp** [comment]
> OGG Vorbis iirc, just about any online converter works for this

Just did it. It’s working! I will now close this thread.
