### ISSUE TITLE
compiling problem

### ISSUE THREAD

**Issue by schwiftified** [ShadowMario/FNF-PsychEngine#9950]
### Describe your problem here.

everytime i compile the psych engine source code this error happens 
<img width="943" alt="image" src="https://user-images.githubusercontent.com/96924332/181661059-5d0532b4-0264-4656-b41c-12e5a9b94769.png">

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by frantastic24** [comment]
Those are not errors

**Comment by schwiftified** [comment]
??

> Those are not errors

**Comment by frantastic24** [comment]
They don't affect compiling the game, this has been explained before and isn't specific to this engine

**Comment by schwiftified** [comment]
> They don't affect compiling the game, this has been explained before and isn't specific to this engine

what can i do?

**Comment by schwiftified** [comment]
> They don't affect compiling the game, this has been explained before and isn't specific to this engine

thanks
