### ISSUE TITLE
Dialogue box over game over?

### ISSUE THREAD

**Issue by SlimyPennies** [ShadowMario/FNF-PsychEngine#9951]
### Describe your problem here.

I'm not a programmer (I don't do anything besides splice together what other people have written), but I for some reason decided to try and make it so when you get a game over, a dialogue box appears over it, kinda like in Undertale??? In my research, I found that VS Ace and VS Retrospecter both have done the same thing I was aiming for, but there's two problems. They're in Kade Engine, and they seem like they alter the source code to achieve it?? I was hoping I could get it to work with just Lua??

Anyways, here's the closest I could get to it working. It's simply a script file in the song's data folder. (Because I was HOPING I could have unique boxes for each song.)

<details>
<summary>My Miserable Excuse For Code?</summary>

function onGameOverStart()
	startDialogue('dialogue', 'breakfast');
	end

function onNextDialogue(count)

end

function onSkipDialogue(count)

end

</details>

I consider this my "best attempt" despite it being the most simple because you can actually hear the text being written. I think maybe the text box is being rendered under the game over, but I don't have any way to prove this, and I couldn't find a way to rectify that, even if that were the case.

I've spent way too long on this, and now the sunk cost fallacy is in full swing. I have scoured, I have searched, I have seen my results flooded with too many kids asking how to make their characters say voice lines, it's insane. Please help this noob.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x86/x32

**Comment by Lorekeeper49** [comment]
I'm pretty sure that this is impossible to do without modifying the source code

**Comment by NotEpik** [comment]
This took me an hour to do but it will work in Lua just some fps drop happening while the game over happens:

https://user-images.githubusercontent.com/88980162/181803659-6a0ae01f-7125-468e-8d51-74fa0354ae17.mp4

here's the script: 

```
local dialogRan = false
local songIsPlaying = false

function onCreate()
	precacheImage('characters/BOYFRIEND_DEAD')
	precacheSound('fnf_loss_sfx')
end

function onPause()
	if dialogRan then
		return Function_Stop;
	end
end

function onGameOver()
	setPropertyFromClass('Conductor', 'songPosition', getPropertyFromClass('Conductor', 'songPosition') - 16)
	setProperty('vocals.time', 0)
	setProperty('vocals.volume', 0)

	if not dialogRan then
		dialogRan = true

		setProperty('dad.alpha', 0)
		setProperty('boyfriend.alpha', 0)
		setProperty('gf.alpha', 0)

		makeLuaSprite('blackBG', 'stageback', -5000, -5000, 0)
		makeGraphic('blackBG', 10000, 10000, '000000')
		setObjectCamera('blackBG', 'game')
		setObjectOrder('blackBG', 100)
		addLuaSprite('blackBG')

		makeAnimatedLuaSprite('deadBF', 'characters/BOYFRIEND_DEAD', getProperty('boyfriend.x') - 37, getProperty('boyfriend.y') - 11)

		addAnimationByPrefix('deadBF', 'firstDeath', 'BF dies', 24, false)
		addAnimationByPrefix('deadBF', 'deathLoop', 'BF Dead Loop', 24, true)
		addAnimationByPrefix('deadBF', 'deathConfirm', 'BF Dead confirm', 24, false)

		--scaleObject('deadBF', getProperty('boyfriend.width'), getProperty('boyfriend.height')) | this just make the sprite disappear
		setObjectCamera('deadBF', 'game')
		setObjectOrder('deadBF', 101)
		addLuaSprite('deadBF')

		setProperty('timeBarBG.visible', false)
		setProperty('timeBar.visible', false)
		setProperty('timeTxt.visible', false)
		setProperty('scoreTxt.visible', false)
		setProperty('healthBar.y', screenHeight + 100)
		--setProperty('healthBar.visible', false) | this won't fully made the healthbar invisible
		setProperty('iconP1.visible', false)
		setProperty('iconP2.visible', false)

		for i = 0, 3, 1 do
			setPropertyFromGroup('opponentStrums', i, 'visible', false)
			setPropertyFromGroup('playerStrums', i, 'visible', false)

			setPropertyFromGroup('opponentStrums', i, 'alpha', 0)
			setPropertyFromGroup('playerStrums', i, 'alpha', 0)
		end

		setProperty('inCutscene', true)

		runTimer("deadSound", 0.3)
		runTimer("camSetBF", 0.75)
		runTimer("playLoop", 2.5)
	end

	return Function_Stop;
end

function onNextDialogue(line)
	if line == 2 then
		setProperty('inCutscene', false)
		setProperty('camHUD.alpha', 0)
	end
end

local restarted = false

function onUpdate()
	if dialogRan then
		if songIsPlaying then
			objectPlayAnimation('deadBF', 'deathLoop', false)
			setProperty('deadBF.x', (cameraX - 150) - 37)
			setProperty('deadBF.y', (cameraY - 200) - 5)
		end

		if keyJustPressed('accept') or keyJustPressed('space') then
			if getProperty('inCutscene') == false then
				if not restarted then
					restarted = true
					songIsPlaying = false
					objectPlayAnimation('deadBF', 'deathConfirm', true)
					setProperty('deadBF.x', (cameraX - 150) - 37)
					setProperty('deadBF.y', (cameraY - 200) - 69)
	
					stopSound('gameOver')
					playMusic('gameOverEnd', 1, false)
		
					doTweenAlpha('bfByeBye', 'deadBF', 0, 2.5, 'linearInOut')
					runTimer('endItAll', 3.75)
				end
			end
		elseif keyJustPressed('back') then
			exitSong(false);
		end
	end
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'deadSound' then
		playSound('fnf_loss_sfx', 1)
	elseif tag == 'camSetBF' then
		startDialogue('gameOverDialogue')
		doTweenX('bfX', 'deadBF', (cameraX - 150) - 37, 0.75, 'quadOut')
		doTweenY('bfY', 'deadBF', (cameraY - 200) - 11, 0.75, 'quadOut')
		--cameraSetTarget("boyfriend") | won't work after death
	elseif tag == 'playLoop' then
		playMusic('gameOver', 0.75, false)
		songIsPlaying = true
	elseif tag == 'endItAll' then
		restartSong(false);
	end
end
```

**Comment by SlimyPennies** [comment]
> This took me an hour to do but it will work in Lua just some fps drop happening while the game over happens:
> 
>  bandicam.2022-07-29.23-25-04-233.mp4 
> here's the script (I've edited some parts of the script in here so you can set value to anything you want but it might not work):
> 
> ```
> -- PUTS IN ASSETS/DATA/song-name or MODS/DATA/song-name
> 
> local dialogRan = false
> local songIsPlaying = false
> local deadSprite = "'characters/BOYFRIEND_DEAD'" -- set it to your death prite so it won't overwrite lol
> local lostSound = "fnf_loss_sfx" -- and set this to the sound that plays when you died
> local songName = "gameOver" -- also set it to your song that loops when you died
> local deathEnd = "gameOverEnd" -- set it to the sound that plays when the player chose to retry
> 
> function onCreate()
> 	precacheImage(deadSprite)
> 	precacheSound(lostSound)
> end
> 
> function onPause()
> 	if dialogRan then
> 		return Function_Stop;
> 	end
> end
> 
> function onGameOver()
> 	setPropertyFromClass('Conductor', 'songPosition', getPropertyFromClass('Conductor', 'songPosition') - 16)
> 	setProperty('vocals.time', 0)
> 	setProperty('vocals.volume', 0)
> 
> 	if not dialogRan then
> 		dialogRan = true
> 
> 		setProperty('dad.alpha', 0)
> 		setProperty('boyfriend.alpha', 0)
> 		setProperty('gf.alpha', 0)
> 
> 		makeLuaSprite('blackBG', 'stageback', -5000, -5000, 0)
> 		makeGraphic('blackBG', 10000, 10000, '000000')
> 		setObjectCamera('blackBG', 'game')
> 		setObjectOrder('blackBG', 100)
> 		addLuaSprite('blackBG')
> 
> 		makeAnimatedLuaSprite('deadBF', deadSprite, getProperty('boyfriend.x') - 37, getProperty('boyfriend.y') - 11)
> 
> 		addAnimationByPrefix('deadBF', 'firstDeath', 'BF dies', 24, false)
> 		addAnimationByPrefix('deadBF', 'deathLoop', 'BF Dead Loop', 24, true)
> 		addAnimationByPrefix('deadBF', 'deathConfirm', 'BF Dead confirm', 24, false)
> 
> 		--scaleObject('deadBF', getProperty('boyfriend.width'), getProperty('boyfriend.height')) | this just make the sprite disappear
> 		setObjectCamera('deadBF', 'game')
> 		setObjectOrder('deadBF', 101)
> 		addLuaSprite('deadBF')
> 
> 		setProperty('timeBarBG.visible', false)
> 		setProperty('timeBar.visible', false)
> 		setProperty('timeTxt.visible', false)
> 		setProperty('scoreTxt.visible', false)
> 		setProperty('healthBar.y', screenHeight + 100)
> 		--setProperty('healthBar.visible', false) | this won't fully made the healthbar invisible
> 		setProperty('iconP1.visible', false)
> 		setProperty('iconP2.visible', false)
> 
> 		for i = 0, 3, 1 do
> 			setPropertyFromGroup('opponentStrums', i, 'visible', false)
> 			setPropertyFromGroup('playerStrums', i, 'visible', false)
> 
> 			setPropertyFromGroup('opponentStrums', i, 'alpha', 0)
> 			setPropertyFromGroup('playerStrums', i, 'alpha', 0)
> 		end
> 
> 		setProperty('inCutscene', true)
> 
> 		runTimer("deadSound", 0.3)
> 		runTimer("camSetBF", 0.75)
> 		runTimer("playLoop", 2.5)
> 	end
> 
> 	return Function_Stop;
> end
> 
> function onNextDialogue(line)
> 	if line == --[[2]] then -- set it to all the lines that appear in the dialog just make sure to add an extra line without any text and decrease the value by one
> 		setProperty('inCutscene', false)
> 		setProperty('camHUD.alpha', 0)
> 	end
> end
> 
> local restarted = false
> 
> function onUpdate()
> 	if dialogRan then
> 		if songIsPlaying then
> 			objectPlayAnimation('deadBF', 'deathLoop', false)
> 			setProperty('deadBF.x', (cameraX - 150) - 37)
> 			setProperty('deadBF.y', (cameraY - 200) - 5)
> 		end
> 
> 		if keyJustPressed('accept') or keyJustPressed('space') then
> 			if getProperty('inCutscene') == false then
> 				if not restarted then
> 					restarted = true
> 					songIsPlaying = false
> 					objectPlayAnimation('deadBF', 'deathConfirm', true)
> 					setProperty('deadBF.x', (cameraX - 150) - 37)
> 					setProperty('deadBF.y', (cameraY - 200) - 69)
> 	
> 					stopSound(songName)
> 					playMusic(deathEnd, 1, false)
> 		
> 					doTweenAlpha('bfByeBye', 'deadBF', 0, 2.5, 'linearInOut')
> 					runTimer('endItAll', 3.75)
> 				end
> 			end
> 		elseif keyJustPressed('back') then
> 			exitSong(false);
> 		end
> 	end
> end
> 
> function onTimerCompleted(tag, loops, loopsLeft)
> 	if tag == 'deadSound' then
> 		playSound(lostSound, 1)
> 	elseif tag == 'camSetBF' then
> 		startDialogue('your dialog') -- put dialog file name here!!
> 		doTweenX('bfX', 'deadBF', (cameraX - 150) - 37, 0.75, 'quadOut')
> 		doTweenY('bfY', 'deadBF', (cameraY - 200) - 11, 0.75, 'quadOut')
> 		--cameraSetTarget("boyfriend") | won't work after death
> 	elseif tag == 'playLoop' then
> 		playMusic(songName, 0.75, false)
> 		songIsPlaying = true
> 	elseif tag == 'endItAll' then
> 		restartSong(false);
> 	end
> end
> ```

Dude, thank you so much!! If you ever need a piece of dumb art for like a project you're working on or whatever, just let me know! I'll do it, no questions asked. I owe you. However, I know this is the equivalent of asking Jesus for a second bottle of wine, but I can't for the life of me get it to actually work on my end. Can you please link the files you used in the video (The script.json and the dialogue.json) so I can actually look at it? I'm probably missing something very dumb. I want you to look at me and assume I have the coding knowledge of a newborn child born in the prehistoric era, untouched by technology. That's what we're dealing with, buddy.

**Comment by NotEpik** [comment]
> > This took me an hour to do but it will work in Lua just some fps drop happening while the game over happens:
> > bandicam.2022-07-29.23-25-04-233.mp4
> > here's the script (I've edited some parts of the script in here so you can set value to anything you want but it might not work):
> > ```
> > -- PUTS IN ASSETS/DATA/song-name or MODS/DATA/song-name
> > 
> > local dialogRan = false
> > local songIsPlaying = false
> > local deadSprite = "'characters/BOYFRIEND_DEAD'" -- set it to your death prite so it won't overwrite lol
> > local lostSound = "fnf_loss_sfx" -- and set this to the sound that plays when you died
> > local songName = "gameOver" -- also set it to your song that loops when you died
> > local deathEnd = "gameOverEnd" -- set it to the sound that plays when the player chose to retry
> > 
> > function onCreate()
> > 	precacheImage(deadSprite)
> > 	precacheSound(lostSound)
> > end
> > 
> > function onPause()
> > 	if dialogRan then
> > 		return Function_Stop;
> > 	end
> > end
> > 
> > function onGameOver()
> > 	setPropertyFromClass('Conductor', 'songPosition', getPropertyFromClass('Conductor', 'songPosition') - 16)
> > 	setProperty('vocals.time', 0)
> > 	setProperty('vocals.volume', 0)
> > 
> > 	if not dialogRan then
> > 		dialogRan = true
> > 
> > 		setProperty('dad.alpha', 0)
> > 		setProperty('boyfriend.alpha', 0)
> > 		setProperty('gf.alpha', 0)
> > 
> > 		makeLuaSprite('blackBG', 'stageback', -5000, -5000, 0)
> > 		makeGraphic('blackBG', 10000, 10000, '000000')
> > 		setObjectCamera('blackBG', 'game')
> > 		setObjectOrder('blackBG', 100)
> > 		addLuaSprite('blackBG')
> > 
> > 		makeAnimatedLuaSprite('deadBF', deadSprite, getProperty('boyfriend.x') - 37, getProperty('boyfriend.y') - 11)
> > 
> > 		addAnimationByPrefix('deadBF', 'firstDeath', 'BF dies', 24, false)
> > 		addAnimationByPrefix('deadBF', 'deathLoop', 'BF Dead Loop', 24, true)
> > 		addAnimationByPrefix('deadBF', 'deathConfirm', 'BF Dead confirm', 24, false)
> > 
> > 		--scaleObject('deadBF', getProperty('boyfriend.width'), getProperty('boyfriend.height')) | this just make the sprite disappear
> > 		setObjectCamera('deadBF', 'game')
> > 		setObjectOrder('deadBF', 101)
> > 		addLuaSprite('deadBF')
> > 
> > 		setProperty('timeBarBG.visible', false)
> > 		setProperty('timeBar.visible', false)
> > 		setProperty('timeTxt.visible', false)
> > 		setProperty('scoreTxt.visible', false)
> > 		setProperty('healthBar.y', screenHeight + 100)
> > 		--setProperty('healthBar.visible', false) | this won't fully made the healthbar invisible
> > 		setProperty('iconP1.visible', false)
> > 		setProperty('iconP2.visible', false)
> > 
> > 		for i = 0, 3, 1 do
> > 			setPropertyFromGroup('opponentStrums', i, 'visible', false)
> > 			setPropertyFromGroup('playerStrums', i, 'visible', false)
> > 
> > 			setPropertyFromGroup('opponentStrums', i, 'alpha', 0)
> > 			setPropertyFromGroup('playerStrums', i, 'alpha', 0)
> > 		end
> > 
> > 		setProperty('inCutscene', true)
> > 
> > 		runTimer("deadSound", 0.3)
> > 		runTimer("camSetBF", 0.75)
> > 		runTimer("playLoop", 2.5)
> > 	end
> > 
> > 	return Function_Stop;
> > end
> > 
> > function onNextDialogue(line)
> > 	if line == --[[2]] then -- set it to all the lines that appear in the dialog just make sure to add an extra line without any text and decrease the value by one
> > 		setProperty('inCutscene', false)
> > 		setProperty('camHUD.alpha', 0)
> > 	end
> > end
> > 
> > local restarted = false
> > 
> > function onUpdate()
> > 	if dialogRan then
> > 		if songIsPlaying then
> > 			objectPlayAnimation('deadBF', 'deathLoop', false)
> > 			setProperty('deadBF.x', (cameraX - 150) - 37)
> > 			setProperty('deadBF.y', (cameraY - 200) - 5)
> > 		end
> > 
> > 		if keyJustPressed('accept') or keyJustPressed('space') then
> > 			if getProperty('inCutscene') == false then
> > 				if not restarted then
> > 					restarted = true
> > 					songIsPlaying = false
> > 					objectPlayAnimation('deadBF', 'deathConfirm', true)
> > 					setProperty('deadBF.x', (cameraX - 150) - 37)
> > 					setProperty('deadBF.y', (cameraY - 200) - 69)
> > 	
> > 					stopSound(songName)
> > 					playMusic(deathEnd, 1, false)
> > 		
> > 					doTweenAlpha('bfByeBye', 'deadBF', 0, 2.5, 'linearInOut')
> > 					runTimer('endItAll', 3.75)
> > 				end
> > 			end
> > 		elseif keyJustPressed('back') then
> > 			exitSong(false);
> > 		end
> > 	end
> > end
> > 
> > function onTimerCompleted(tag, loops, loopsLeft)
> > 	if tag == 'deadSound' then
> > 		playSound(lostSound, 1)
> > 	elseif tag == 'camSetBF' then
> > 		startDialogue('your dialog') -- put dialog file name here!!
> > 		doTweenX('bfX', 'deadBF', (cameraX - 150) - 37, 0.75, 'quadOut')
> > 		doTweenY('bfY', 'deadBF', (cameraY - 200) - 11, 0.75, 'quadOut')
> > 		--cameraSetTarget("boyfriend") | won't work after death
> > 	elseif tag == 'playLoop' then
> > 		playMusic(songName, 0.75, false)
> > 		songIsPlaying = true
> > 	elseif tag == 'endItAll' then
> > 		restartSong(false);
> > 	end
> > end
> > ```
> 
> Dude, thank you so much!! If you ever need a piece of dumb art for like a project you're working on or whatever, just let me know! I'll do it, no questions asked. I owe you. However, I know this is the equivalent of asking Jesus for a second bottle of wine, but I can't for the life of me get it to actually work on my end. Can you please link the files you used in the video (The script.json and the dialogue.json) so I can actually look at it? I'm probably missing something very dumb. I want you to look at me and assume I have the coding knowledge of a newborn child born in the prehistoric era, untouched by technology. That's what we're dealing with, buddy.

[dialogGameOverLua.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9224084/dialogGameOverLua.txt)
[gameOverDialogue.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9224085/gameOverDialogue.txt)

Me when I can't upload .lua and .json: I will turn it into .txt then

**Comment by SlimyPennies** [comment]
> > > This took me an hour to do but it will work in Lua just some fps drop happening while the game over happens:
> > > bandicam.2022-07-29.23-25-04-233.mp4
> > > here's the script (I've edited some parts of the script in here so you can set value to anything you want but it might not work):
> > > ```
> > > -- PUTS IN ASSETS/DATA/song-name or MODS/DATA/song-name
> > > 
> > > local dialogRan = false
> > > local songIsPlaying = false
> > > local deadSprite = "'characters/BOYFRIEND_DEAD'" -- set it to your death prite so it won't overwrite lol
> > > local lostSound = "fnf_loss_sfx" -- and set this to the sound that plays when you died
> > > local songName = "gameOver" -- also set it to your song that loops when you died
> > > local deathEnd = "gameOverEnd" -- set it to the sound that plays when the player chose to retry
> > > 
> > > function onCreate()
> > > 	precacheImage(deadSprite)
> > > 	precacheSound(lostSound)
> > > end
> > > 
> > > function onPause()
> > > 	if dialogRan then
> > > 		return Function_Stop;
> > > 	end
> > > end
> > > 
> > > function onGameOver()
> > > 	setPropertyFromClass('Conductor', 'songPosition', getPropertyFromClass('Conductor', 'songPosition') - 16)
> > > 	setProperty('vocals.time', 0)
> > > 	setProperty('vocals.volume', 0)
> > > 
> > > 	if not dialogRan then
> > > 		dialogRan = true
> > > 
> > > 		setProperty('dad.alpha', 0)
> > > 		setProperty('boyfriend.alpha', 0)
> > > 		setProperty('gf.alpha', 0)
> > > 
> > > 		makeLuaSprite('blackBG', 'stageback', -5000, -5000, 0)
> > > 		makeGraphic('blackBG', 10000, 10000, '000000')
> > > 		setObjectCamera('blackBG', 'game')
> > > 		setObjectOrder('blackBG', 100)
> > > 		addLuaSprite('blackBG')
> > > 
> > > 		makeAnimatedLuaSprite('deadBF', deadSprite, getProperty('boyfriend.x') - 37, getProperty('boyfriend.y') - 11)
> > > 
> > > 		addAnimationByPrefix('deadBF', 'firstDeath', 'BF dies', 24, false)
> > > 		addAnimationByPrefix('deadBF', 'deathLoop', 'BF Dead Loop', 24, true)
> > > 		addAnimationByPrefix('deadBF', 'deathConfirm', 'BF Dead confirm', 24, false)
> > > 
> > > 		--scaleObject('deadBF', getProperty('boyfriend.width'), getProperty('boyfriend.height')) | this just make the sprite disappear
> > > 		setObjectCamera('deadBF', 'game')
> > > 		setObjectOrder('deadBF', 101)
> > > 		addLuaSprite('deadBF')
> > > 
> > > 		setProperty('timeBarBG.visible', false)
> > > 		setProperty('timeBar.visible', false)
> > > 		setProperty('timeTxt.visible', false)
> > > 		setProperty('scoreTxt.visible', false)
> > > 		setProperty('healthBar.y', screenHeight + 100)
> > > 		--setProperty('healthBar.visible', false) | this won't fully made the healthbar invisible
> > > 		setProperty('iconP1.visible', false)
> > > 		setProperty('iconP2.visible', false)
> > > 
> > > 		for i = 0, 3, 1 do
> > > 			setPropertyFromGroup('opponentStrums', i, 'visible', false)
> > > 			setPropertyFromGroup('playerStrums', i, 'visible', false)
> > > 
> > > 			setPropertyFromGroup('opponentStrums', i, 'alpha', 0)
> > > 			setPropertyFromGroup('playerStrums', i, 'alpha', 0)
> > > 		end
> > > 
> > > 		setProperty('inCutscene', true)
> > > 
> > > 		runTimer("deadSound", 0.3)
> > > 		runTimer("camSetBF", 0.75)
> > > 		runTimer("playLoop", 2.5)
> > > 	end
> > > 
> > > 	return Function_Stop;
> > > end
> > > 
> > > function onNextDialogue(line)
> > > 	if line == --[[2]] then -- set it to all the lines that appear in the dialog just make sure to add an extra line without any text and decrease the value by one
> > > 		setProperty('inCutscene', false)
> > > 		setProperty('camHUD.alpha', 0)
> > > 	end
> > > end
> > > 
> > > local restarted = false
> > > 
> > > function onUpdate()
> > > 	if dialogRan then
> > > 		if songIsPlaying then
> > > 			objectPlayAnimation('deadBF', 'deathLoop', false)
> > > 			setProperty('deadBF.x', (cameraX - 150) - 37)
> > > 			setProperty('deadBF.y', (cameraY - 200) - 5)
> > > 		end
> > > 
> > > 		if keyJustPressed('accept') or keyJustPressed('space') then
> > > 			if getProperty('inCutscene') == false then
> > > 				if not restarted then
> > > 					restarted = true
> > > 					songIsPlaying = false
> > > 					objectPlayAnimation('deadBF', 'deathConfirm', true)
> > > 					setProperty('deadBF.x', (cameraX - 150) - 37)
> > > 					setProperty('deadBF.y', (cameraY - 200) - 69)
> > > 	
> > > 					stopSound(songName)
> > > 					playMusic(deathEnd, 1, false)
> > > 		
> > > 					doTweenAlpha('bfByeBye', 'deadBF', 0, 2.5, 'linearInOut')
> > > 					runTimer('endItAll', 3.75)
> > > 				end
> > > 			end
> > > 		elseif keyJustPressed('back') then
> > > 			exitSong(false);
> > > 		end
> > > 	end
> > > end
> > > 
> > > function onTimerCompleted(tag, loops, loopsLeft)
> > > 	if tag == 'deadSound' then
> > > 		playSound(lostSound, 1)
> > > 	elseif tag == 'camSetBF' then
> > > 		startDialogue('your dialog') -- put dialog file name here!!
> > > 		doTweenX('bfX', 'deadBF', (cameraX - 150) - 37, 0.75, 'quadOut')
> > > 		doTweenY('bfY', 'deadBF', (cameraY - 200) - 11, 0.75, 'quadOut')
> > > 		--cameraSetTarget("boyfriend") | won't work after death
> > > 	elseif tag == 'playLoop' then
> > > 		playMusic(songName, 0.75, false)
> > > 		songIsPlaying = true
> > > 	elseif tag == 'endItAll' then
> > > 		restartSong(false);
> > > 	end
> > > end
> > > ```
> > 
> > 
> > Dude, thank you so much!! If you ever need a piece of dumb art for like a project you're working on or whatever, just let me know! I'll do it, no questions asked. I owe you. However, I know this is the equivalent of asking Jesus for a second bottle of wine, but I can't for the life of me get it to actually work on my end. Can you please link the files you used in the video (The script.json and the dialogue.json) so I can actually look at it? I'm probably missing something very dumb. I want you to look at me and assume I have the coding knowledge of a newborn child born in the prehistoric era, untouched by technology. That's what we're dealing with, buddy.
> 
> [dialogGameOverLua.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9224084/dialogGameOverLua.txt) [gameOverDialogue.txt](https://github.com/ShadowMario/FNF-PsychEngine/files/9224085/gameOverDialogue.txt)
> 
> Me when I can't upload .lua and .json: I will turn it into .txt then

Dude, holy shit, it works?? Sorry for the late reply, I was distracted with work and then forgot about this thread. For some reason, it refused to work in 32 so I swapped over to 64 (Why was I using 32 to begin with? Who knows?) and it worked perfectly. You are a god amongst men, I tell ya. Thank you. <3
