### ISSUE TITLE
How to change health bar in different song?

### ISSUE THREAD

**Issue by deathline1938** [ShadowMario/FNF-PsychEngine#9952]
### Describe your problem here.

![healthBar-short](https://user-images.githubusercontent.com/94227585/181681858-383664e7-369f-4381-8aba-28d82df84da9.png)

how to change another health bar in another song?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by FlintIshe** [comment]
may be just hide the current healthbar and load your new healthbar image idk

**Comment by frantastic24** [comment]
```lua
loadGraphic(object, image)
```
