### ISSUE TITLE
Vortex editor update

### ISSUE THREAD

**Issue by Mastercopper2346** [ShadowMario/FNF-PsychEngine#9953]
### What feature do you want to get added on the **base** engine?

Holding 1-8 on vortex editor should make sustain notes so you can chart the song very easier

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by NS-Unfair** [comment]
To add to this feature request, I think there should be another keybind you have to hold to do that or a togglable option.

**Comment by Mastercopper2346** [comment]
Mmm, makes sense.
