### ISSUE TITLE
Grayscaling

### ISSUE THREAD

**Issue by YKoF-CALm** [ShadowMario/FNF-PsychEngine#9954]
### Describe your problem here.

Just wondering if it's possible to grayscale the following:

- Characters
- Lua sprites
- Icons

If yes, how do I do it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing.

**Comment by NS-Unfair** [comment]
Use shaders if you are on the latest version. It isn't documented yet, but you can learn a little Haxe to see how the functions work and learn GLSL to make the shaders. You can find the functions in `FunkinLua.hx`  under "shader shit."

**Comment by tylerandari12** [comment]
> Use shaders if you are on the latest version. It isn't documented yet, but you can learn a little Haxe to see how the functions work and learn GLSL to make the shaders. You can find the functions in `FunkinLua.hx` under the comment "shader shit."

We got shaders back!?

**Comment by YKoF-CALm** [comment]
Yeah, I saw the shader functions, but then I saw a commit saying "shader stuff in progress" or something like that, so I dunno.
I'll probably ignore the shader stuff now and just code the other things. I'll get to shaders later (AKA when I probably find a shader later online IDK).
