### ISSUE TITLE
Opening a URL with runHaxeCode()

### ISSUE THREAD

**Issue by tylerandari12** [ShadowMario/FNF-PsychEngine#9955]
### Describe your problem here.

I'm trying to see if its possible to use `runHaxeCode()` to open a URL (Because why not?)

Am I on the  right track with this code?

```lua
function onCreate()
	addHaxeLibrary("kha", "System")
end

function onStartCountdown()
	return Function_Stop;
end

function OpenUrl(URL)
	debugPrint("Loading Url: "..URL)
	runHaxeCode("System.loadUrl("..URL..")")
end

function onUpdate()
	if keyJustPressed("accept") then
		OpenUrl("https://youtube.com")
	end
end
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing changed.

**Comment by TheAverageGitHubUser** [comment]
kha seems interesting, but you can use 
```haxe 
CoolUtil.openBrowser
``` 
for url load

**Comment by tylerandari12** [comment]
> kha seems interesting, but you can use
> 
> ```hx
> CoolUtil.openBrowser
> ```
> 
> for url load

:0
