### ISSUE TITLE
update the wiki

### ISSUE THREAD

**Issue by alex-codes-stuff** [ShadowMario/FNF-PsychEngine#9956]
### What feature do you want to get added on the **base** engine?

seriously, the wiki is missing SO much stuff. Ive been waiting for it to get updated for so, god damn, long.
Litteraly, im on my hands and knees.
unless im an idiot, and the wiki somehow isnt actually missing a lot of stuff,
PLEASE, SHADOWMARIO, UPDATE THE WIKI
also, i didnt know what label to choose so i decided enhancement would fit the best

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by frantastic24** [comment]
Me brother in Christ there is a documentation label
Pretty sure this is a duplicate anyways

**Comment by Mastercopper2346** [comment]
Duplicate, and put in documentation, but yeah, we do need this.

Besides the new difficulty update I requested, Nothing has been updated since June.

**Comment by tylerandari12** [comment]
I'm still waiting for someone to be like "Fine I'll do it myself..." and make a fanmade wiki...
(I cant outside of Lua because I dont know source...)

**Comment by CrusherMods** [comment]
> I'm still waiting for someone to be like "Fine I'll do it myself..." and make a fanmade wiki...
> 
> (I cant outside of Lua because I dont know source...)

someone is making one rn from what I know
or its alr finished idk

**Comment by NS-Unfair** [comment]
Thought ShadowMario or someone else would update the wiki in the next update.
