### ISSUE TITLE
Characters Animate Fast when their Order is greater than -1

### ISSUE THREAD

**Issue by MrGenie151** [ShadowMario/FNF-PsychEngine#9958]
### Describe your bug here.

Character's order is is to -1 on any stage/song by default. Upon changing the order to anything greater than -1 with the setObjectOrder() function, the character's animation speed doubles. This, to me, is a critical issue.

### Command Prompt/Terminal logs (if existing)

```bash
No terminal logs because no crashes happened.
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing edited.

**Comment by frantastic24** [comment]
Change the group instead of the character, I think it's a haxe issue

**Comment by Mastercopper2346** [comment]
Or just decrease the fps..?
