### ISSUE TITLE
Strumline Events

### ISSUE THREAD

**Issue by SorbetLover** [ShadowMario/FNF-PsychEngine#9959]
### What feature do you want to get added on the **base** engine?

Add a strumline event that  edits the angle etc

**Comment by frantastic24** [comment]
Failed the test + already possible

**Comment by SorbetLover** [comment]
idk how to use this 💀

**Comment by SorbetLover** [comment]
idk how to use this , and idk how to rotate the strumlines

**Comment by frantastic24** [comment]
If only there was a wiki with that information!!

**Comment by SorbetLover** [comment]
but idk how to code 💀 i want an event for this , like the ''MoveArrow'' event

**Comment by frantastic24** [comment]
Don't ask people to code it for you
And don't reopen this

**Comment by NotEpik** [comment]
https://github.com/ShadowMario/FNF-PsychEngine/wiki/Lua-Script-API:-Tweens-and-Timers

**Comment by tylerandari12** [comment]
> Failed the test + already possible

Cant fail it if it's not there...

**Comment by NS-Unfair** [comment]
Bruh this isn't the place to learn how to program in Lua. You can look at [this](lua.org) to learn how to program.
