### ISSUE TITLE
Winning Icons

### ISSUE THREAD

**Issue by KingRGames** [ShadowMario/FNF-PsychEngine#9968]
### Describe your problem here.

How do I code in winning icons and how do I do it?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by CrusherMods** [comment]
Not the place to ask.

**Comment by TheKitBoi** [comment]
Read this
To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by TheKitBoi** [comment]
![BC64E17F-72CF-427E-BEE0-D436BC2EC9FB](https://user-images.githubusercontent.com/84044666/181923722-8787bdef-d06e-4ea7-af6a-03b656fac769.jpeg)

**Comment by Mastercopper2346** [comment]
https://www.youtube.com/watch?v=hWhVck6emII

**Comment by TFLTV** [comment]
> https://www.youtube.com/watch?v=hWhVck6emII

he's using lua

**Comment by TFLTV** [comment]
I think set change the character to the same character but with the winning Icon as the normal icon when bf has 20 health but if not change the character back.  should work with bf too.

**Comment by NS-Unfair** [comment]
It's actually really easy if you know how to read the source code. In the "updatePost" function, you can overwrite the animation frame to be whatever you want.

```

iconFrames = {
    {20, 1}, -- If less than 20 percent, frame is 1. Losing icon
    {80, 0}, -- If less than 101 percent, frame is 0. Neutral icon
    {101, 2}, -- If less than 101 percent, frame is 2. Winning icon

    -- You can add more frames if you want to
    -- {[Less than Percent], [Frame]}
}

function onUpdatePost()
    -- Winning icon for player
    DisplayIconFrames('iconP1', iconFrames)
    -- Winning icon for opponent
    DisplayIconFrames('iconP2', iconFrames)
end

-- I made it customizable for newbies
function DisplayIconFrames(icon, percentStuff)
    for k,v in pairs(percentStuff) do
        if getProperty'healthBar.percent' < v[1] then
            -- Sets the icon frame to whatever index 2 of variable v is
            setProperty(icon .. '.animation.curAnim.curFrame', v[2])
        end
    end
end

```

@TheKitBoi read that again. That is for feature requests **only**.

**Comment by BernardoGP4504** [comment]
> Read this ![BC64E17F-72CF-427E-BEE0-D436BC2EC9FB](https://user-images.githubusercontent.com/84044666/181923722-8787bdef-d06e-4ea7-af6a-03b656fac769.jpeg)

he isn't requesting it, he's asking how to do it
