### ISSUE TITLE
Winning Icons

### ISSUE THREAD

**Issue by KingRGames** [ShadowMario/FNF-PsychEngine#9969]
### What is your question?

How do I code winning Icons in fnf?

**Comment by TheKitBoi** [comment]
Read this
![BC64E17F-72CF-427E-BEE0-D436BC2EC9FB](https://user-images.githubusercontent.com/84044666/181923722-8787bdef-d06e-4ea7-af6a-03b656fac769.jpeg)

**Comment by Mastercopper2346** [comment]
https://www.youtube.com/watch?v=hWhVck6emII

**Comment by Mastercopper2346** [comment]
@TheKitBoi That doesn't specifically mean that he can't get help on coding them!!

**Comment by Mastercopper2346** [comment]
It's saying not i request to be added into the ENGINE

**Comment by Mastercopper2346** [comment]
No he didn’t
