### ISSUE TITLE
How to change the title screen when a week is cleared

### ISSUE THREAD

**Issue by Setter-Function** [ShadowMario/FNF-PsychEngine#9970]
### Describe your problem here.

(0.5.2h)
(Bad English)
When a week is finished, I would like to permanently change the title character sprite to another sprite unless %appdata% is deleted.
Let me give you an example.

Example Objective: When the tutorial week is finished, let's make the gf title permanently change to the bbpanzu title.

I only brought the parts that I added or changed. So there are many skipped codes.
Anyways... this is the way I tried.

Suppose this is 'TitleState.hx'.
```haxe
// line 38
import PlayState;
```
In 'TitleState.hx', add 'importPlayState;' to recall functions in 'PlayState.hx'.
The ones to be used are 'isStoryMode', 'storyPlaylist.length', and 'usedPractice'.
```haxe
// line 306
default:
	gfDance.frames = Paths.getSparrowAtlas('gfDanceTitle');
	gfDance.animation.addByIndices('danceLeft', 'gfDance', [30, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], "", 24, false);
	gfDance.animation.addByIndices('danceRight', 'gfDance', [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], "", 24, false);

    if(WeekData.getWeekFileName() == 'tutorial' && PlayState.isStoryMode && PlayState.storyPlaylist.length <= 1 && !PlayState.usedPractice) {
        gfDance.frames = Paths.getSparrowAtlas('BBBump');
        gfDance.animation.addByIndices('danceLeft', 'BB Title Bump', [30, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], "", 24, false);
        gfDance.animation.addByIndices('danceRight', 'BB Title Bump', [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], "", 24, false);
    }
```
To check whether the tutoreal week is cleared or not, 'isStoryMode', 'storyPlaylist.length', and 'usedPractice' are used.
I entered 'PlayState.' for each of the aforementioned objects. (cuz it's imported paths)
Therefore, 'PlayState.isStoryMode', 'PlayState.storyPlaylist', and 'PlayState.usedPractice'.

Suppose this is 'PlayState.hx'.
```haxe
// line 4438
var usedPractice:Bool = (ClientPrefs.getGameplaySetting('practice', false) || ClientPrefs.getGameplaySetting('botplay', false));
```
I deleted this code, and
```haxe
// line 233
public static var usedPractice:Bool = (ClientPrefs.getGameplaySetting('practice', false) || ClientPrefs.getGameplaySetting('botplay', false));
```
added this.

Now run the game and beat the tutorial. And let's go back to the title screen. It worked. But...
The problem starts here. When I close the game and run it again, it goes back to the gf title.
Yes... Title screen changes are not be saved. Or not be lasted..

I know how to implement this similarly by using Achievements. But that also has pros and cons, and I prefer this method.
I'm not good at programming. So I need your help.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by Mastercopper2346** [comment]
You should edit `StoryMenuMode` too..

**Comment by Setter-Function** [comment]
> You should edit `StoryMenuMode` too..

uh.. sorry, I don't follow. How do I do this?

**Comment by Setter-Function** [comment]
.
