### ISSUE TITLE
Pysch engine crashed when i was changing my charcter in chart editor

### ISSUE THREAD

**Issue by sonicgamer2319** [ShadowMario/FNF-PsychEngine#9974]
### Describe your bug here.

PlayState.hx (line 2928)
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by:https://user-images.githubusercontent.com/110268185/181863877-0d4f44f2-63e8-4765-962f-99b3d9dd3ce8.png sqirra-rSSSsss

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i didnt

**Comment by frantastic24** [comment]
Not a bug
Character is missing an icon
