### ISSUE TITLE
How do you make the opponent's notes go downscroll while the player's note go upscroll?

### ISSUE THREAD

**Issue by AzzyDrezzy12** [ShadowMario/FNF-PsychEngine#9975]
### Describe your problem here.

How do you make the opponent's notes go downscroll while the player's notes go upscroll?

Here's an exact image if you don't understand what I mean

![exmple](https://user-images.githubusercontent.com/33179418/181988571-f97e3bb5-fe1e-495e-818a-b8269dd15d4f.png)

Is this possible with lua? (mainly because source never works with me). (ik the character on the right side sucks.)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment]
You should search issues before opening one #9679
