### ISSUE TITLE
PsychEngine.exe wont opening

### ISSUE THREAD

**Issue by Buldog323** [ShadowMario/FNF-PsychEngine#9976]
### Describe your bug here.

When i click on exe file Psych engine wont open at all

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No i didnt

**Comment by frantastic24** [comment]
PC issue

**Comment by NS-Unfair** [comment]
Try double clicking

**Comment by Mastercopper2346** [comment]
> Try double clicking

I was about to say that.

**Comment by TFLTV** [comment]
> Try double clicking

I swear if this is the answer then this person has probably never touched a computer

**Comment by Buldog323** [comment]
> 

I managed, but I had to create a new account on my pc and run the psych engine there (I don't know how it works, but it works)

**Comment by tylerandari12** [comment]
> > Try double clicking
> 
> I swear if this is the answer then this person has probably never touched a computer

They be on that iPhone 13 pro max that they're daddy bought them...

**Comment by ROCK201888** [comment]
i think you delete some kind of file that pysch engine need or some kind of script
