### ISSUE TITLE
When I select an animation it continues in the idle animation.

### ISSUE THREAD

**Issue by arandombambi** [ShadowMario/FNF-PsychEngine#9977]
### Describe your bug here.

i was editing my character in character editor (by clicking 8) and i selected left animation, but it didnt load the left animation and yes was still in the idle animation.
![the error](https://user-images.githubusercontent.com/109686972/181994773-5f33a146-1a4a-4ea5-80c6-be23ec3e66a8.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i didnt edited anything here.

**Comment by frantastic24** [comment]
That's not how it works
Read the text on the bottom right

**Comment by arandombambi** [comment]
> That's not how it works Read the text on the bottom right

oh thanks i never knew that
