### ISSUE TITLE
How can I create a shader with runHaxeCode?

### ISSUE THREAD

**Issue by bruh1cat** [ShadowMario/FNF-PsychEngine#9978]
### What is your question?

Title

also where can I learn the stuff I can do with runHaxeCode and addHaxeLibrary?

**Comment by tylerandari12** [comment]
Good news is you dont have to...
Shaders were just added back not too long ago...

**Comment by bruh1cat** [comment]
with lua?

**Comment by bruh1cat** [comment]
> Good news is you dont have to... Shaders were just added back not too long ago...

also what build?
