### ISSUE TITLE
source code error

### ISSUE THREAD

**Issue by LucasOnGithub** [ShadowMario/FNF-PsychEngine#9979]
### Describe your problem here.

i got the latest psych engine build, and then tried to build it, and then got **source/FunkinLua.hx:342: lines 342-346 : Int should be Bool
source/FunkinLua.hx:342: lines 342-346 : ... For function argument 'f'** and i didnt even edit any source code

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by frantastic24** [comment]
Uninstall luajit and install the one on the readme

**Comment by LucasOnGithub** [comment]
> Uninstall luajit and install the one on the readme

alright ill try that!

**Comment by LucasOnGithub** [comment]
havent closed this in awhile. sorry shadowmario!
