### ISSUE TITLE
Event not working.

### ISSUE THREAD

**Issue by justanundertalefan** [ShadowMario/FNF-PsychEngine#9980]
### Describe your problem here.

Can anyone explain why this isn't working?
`function onEvent(name)
if name == 'die' and botplay == true then
setTextString('botplayTxt', 'die')
setProperty('health', 0)
end
end`

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by frantastic24** [comment]
`botPlay`

**Comment by justanundertalefan** [comment]
thanks lol
