### ISSUE TITLE
mash space event or you die?

### ISSUE THREAD

**Issue by ripsyhehe** [ShadowMario/FNF-PsychEngine#9983]
### Describe your problem here.

how can i make an event where you have to mash space instead of pressing it once to survive, and also have like 3 secs before you die if you dont mash fast enough but if you mash it like 7 times you survive?  

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
Use a variable that counts how many presses, make a timer that checks the amount

**Comment by ripsyhehe** [comment]
thats what im trying to figure out is how to do that

**Comment by frantastic24** [comment]
Lua variables are easy to find on google
Timers are documented on wiki
