### ISSUE TITLE
"Change Character" Event crashes the game.

### ISSUE THREAD

**Issue by SilverSnow07** [ShadowMario/FNF-PsychEngine#9985]
### Describe your bug here.

Psych Engine crashes upon triggering the "Change Character" event. I already added the sprites with xml and json, everything already set up and when I change the current characters to the new ones, the game crashes and gives me this error message:

PlayState.hx (line 4182)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/ShadowMario/FNF-PsychEngine

> Crash Handler written by: sqirra-rng

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, everything added was made using the mods folder.

**Comment by Mastercopper2346** [comment]
Character is probably spelt wrong.

**Comment by SilverSnow07** [comment]
Nope, I had just tested it out again and apparently, the game saves some data that I had deleted a some time ago because I wasn't using them anymore. Even if I change the "events.json" file to match what I want or change the events via debug menu, the game still recognizes the deleted files and crashes.
