### ISSUE TITLE
hi, do newer version of psych support shaders?

### ISSUE THREAD

**Issue by ZakyFerdian** [ShadowMario/FNF-PsychEngine#9986]
### What is your question?

I'm just asking if newer psych support, I wanna help someone make a mod

**Comment by MemeHoovy** [comment]
From what I know, yes.

**Comment by ThatGuy099** [comment]
0.5.1 is one of the versions that supports them, any version that goes up like 0.5.2 , 0.5.2h does not support them :(

**Comment by ZakyFerdian** [comment]
thx to y'all people, this case now closed
