### ISSUE TITLE
help with making event pressing a key a certain amount of times?

### ISSUE THREAD

**Issue by ripsyhehe** [ShadowMario/FNF-PsychEngine#9987]
### Describe your problem here.

iykyk. im trying to make an event where you press a key a certain number of times to achieve something, someone PLEASE help me ive been stuck trying to figure this out for three days ive gotten no sleep. someone just please give a script example ill do the rest

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by frantastic24** [comment]
You already have an open issue, don't make duplicates

**Comment by Mastercopper2346** [comment]
*sigh*

**Comment by TheKitBoi** [comment]
> iykyk. im trying to make an event where you press a key a certain number of times to achieve something, someone PLEASE help me ive been stuck trying to figure this out for three days ive gotten no sleep. someone just please give a script example ill do the rest

No + Stop making Duplicates

**Comment by Mastercopper2346** [comment]
```
spacePresses = 0;

function onUpdate(elapsed)
     if keysJustPressed(‘space’) then
          spacePresses = spacePresses + 1;
     end
end

function onStepHit()
     if curStep == (step) and spacePresses > 7 then
          setHealth(0);
     end
end
```

**Comment by ripsyhehe** [comment]
tysm man, sorry for asking (and possibly annoying you)
