### ISSUE TITLE
How do i change the strum notes hp?

### ISSUE THREAD

**Issue by sans400** [ShadowMario/FNF-PsychEngine#9989]
### Describe your problem here.

I'm trying to change the strum notes hp so it wont continuously give me hp,like the sonic.exe mod
when pressing the stum note no hp was given when it was held. Some help would be appreciated

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64 Version 0.5.2h

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes i edited PlayState.hx, TitleState.hx i added a Secret code, ChartingState.hx, CoolUtil To Add More Difficulties, and more that i don't remember

**Comment by Mastercopper2346** [comment]
#9620

**Comment by sans400** [comment]
> #9620

I was asking the for the code to do that

**Comment by Mastercopper2346** [comment]
IT GAS THE CODE IN PLAYSTATE!!!

**Comment by sans400** [comment]
Ik. what line do i put it on?
