### ISSUE TITLE
My notes crused

### ISSUE THREAD

**Issue by Isa1l** [ShadowMario/FNF-PsychEngine#9992]
### Describe your bug here.

during the song everything goes fine but at one point the arrows disappear but they appear and the texture of the video description breaks:https://youtu.be/yDgnJOHmfyM

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

 No, I didn't edit anything.

**Comment by tylerandari12** [comment]
That's what happens when your scroll speed goes to 0...
