### ISSUE TITLE
logo broke

### ISSUE THREAD

**Issue by thefirecreator** [ShadowMario/FNF-PsychEngine#9995]
### Describe your problem here.

i tried changing the title logo but now it just kinda does this (idk if this is a bug or not so i put it here)
![image](https://user-images.githubusercontent.com/109120740/182049646-eddd9015-d2f0-46fe-8613-18dbda9c24ba.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

changed title logo

**Comment by Mastercopper2346** [comment]
It’s not a bug, you messed with the animation that makes it play.

**Comment by thefirecreator** [comment]
how do i unmess it up?
