### ISSUE TITLE
Health Bar Position 

### ISSUE THREAD

**Issue by Superiron12321** [ShadowMario/FNF-PsychEngine#9999]
### Describe your problem here.

I want to move the health bar, similar position to the fight or flight health bar position. Anyone know how to do this? Thanks.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope

**Comment by frantastic24** [comment]
Search issues before making one #9738

**Comment by Superiron12321** [comment]
> Search issues before making one #9738

Thank you, and yes, i did search issues, at the time i didn't see that one.
